### ISSUE TITLE
Revive multigpu testing

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#100006]
### 🐛 Describe the bug

@ngimel brought to my attention, that we do not have multigpu testing for `test_ops` and `test_jit`
It would be good idea to move all test decorated with `@needsMultiGPU` to a separate file and create its own periodic config for multigpu tests

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra

**Comment by ngimel** [comment]
They don't need to, it's just easier to run only multi-gpu tests on multi-gpu job this way. Alternatively, we could add more testfiles to run in multi-gpu jobs and filter to run only those that require multigpu.

**Comment by janeyx99** [comment]
https://github.com/pytorch/pytorch/issues/92173 would be fixed if we could broaden multigpu testing

**Comment by malfet** [comment]
This has been done a while back
