### ISSUE TITLE
Inductor origins still not accurate

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#100096]
### 🐛 Describe the bug

Given

```
import torch

@torch.compile()
def f(x):
    y = x * 2
    z = torch.cumsum(y, 0)
    return z + 1

f(torch.randn(3, device='cuda'))
```

you end up with

```
def call(args):
    arg0_1, = args
    args.clear()
    with torch.cuda._DeviceGuard(0):
        torch.cuda.set_device(0) # no-op to ensure context
        buf0 = empty_strided((3, ), (1, ), device='cuda', dtype=torch.float32)
        stream0 = get_cuda_stream(0)
        triton_poi_fused_cumsum_mul_0.run(arg0_1, buf0, 3, grid=grid(3), stream=stream0)
        del arg0_1
        buf1 = aten.cumsum(buf0, 0)
        del buf0
        buf2 = buf1
        assert_size_stride(buf2, (3, ), (1, ))
        del buf1
        buf3 = buf2; del buf2  # reuse
        triton_poi_fused_add_1.run(buf3, 3, grid=grid(3), stream=stream0)
        return (buf3, )
```

cumsum should not be attributed to the first kernel, which doesn't actually do cumsum.

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel @Xia-Weiwen @desertfire @Chillee 

### Versions

master

**Comment by vadimkantorov** [comment]
@ezyang btw how does one get such code printouts? :)

**Comment by ezyang** [comment]
`TORCH_LOGS=output_code`, and go bug @mlazos to update the docs ;)

**Comment by Chillee** [comment]
@ezyang Hmm... the reason for this is that we enforce contiguity of inputs when we get to cumsum. So the cumsum is what makes the prior kernel materialized.
