### ISSUE TITLE
Make Dataloader easy to support multiprocess with dill.

### ISSUE THREAD

**Issue by One-sixth** [pytorch/pytorch#100077]
### 🚀 The feature, motivation and pitch

By default, Dataloader's multiprocessing uses pickle. It cannot pick complex types.
Use a flag to allow DataLoader to switch to the multiprocess library, which can allow us to successfully transfer more complex dataset loaders, such as containing lambda functions.

The multiprocess's interface is exactly the same as multiprocessing, and transitions seamlessly.

I currently use this hack Dataloader to use multiprocess.
```python
import torch
from torch.utils.data.dataloader import DataLoader
from torch.utils.data.dataset import Dataset

import multiprocessing
multiprocessing.set_start_method('spawn', force=True)

# Flag
use_multiprocess = True

if use_multiprocess:
    import multiprocess
    multiprocess.set_start_method('spawn', force=True)
    # hack here.
    torch.utils.data.dataloader.python_multiprocessing = multiprocess
    new_multiprocess_ctx = multiprocess.get_context()

else:
    new_multiprocess_ctx = None


class SimpleDataset(Dataset):
    def __init__(self):
        # lambda function here
        self.func = lambda x: x+1

    def __len__(self):
        return 1000

    def __getitem__(self, i):
        return self.func(i)


if __name__ == '__main__':
    ds = SimpleDataset()

    dl = DataLoader(ds, 1, multiprocessing_context=new_multiprocess_ctx, num_workers=2)

    for x in dl:
        print(x)

```

I think better interface.
```python
dl = DataLoader(ds, 1, multiprocessing_context=multiprocess.get_context(), num_workers=2)
```
or
```python
dl = DataLoader(ds, 1, use_multiprocess_lib=True, num_workers=2)
```

cc @SsnL @VitalyFedyunin @ejguan @NivekT @dzhulgakov

**Comment by ejguan** [comment]
You can use `DataLoader2` with `DataPipe` to support `dill` for Multiprocesssing.

**Comment by Aidyn-A** [comment]
> You can use `DataLoader2` with `DataPipe` to support `dill` for Multiprocesssing.


`DataLoader2` got removed in #88848

**Comment by ejguan** [comment]
You can find it from https://github.com/pytorch/data

**Comment by One-sixth** [comment]
@ejguan Thanks for the reply, I got it.
