### ISSUE TITLE
`torch.utils.data.DataLoader.__init__()` does not document `multiprocessing_context` argument

### ISSUE THREAD

**Issue by felixdivo** [pytorch/pytorch#100076]
### 📚 The doc issue

The argument is somewhat described in the text above (search for "multiprocessing") but not in the docstring of the class.

See: https://pytorch.org/docs/stable/_modules/torch/utils/data/dataloader.html#DataLoader

### Suggest a potential alternative/fix

Add a line in the docstring.

cc @svekars @carljparker @SsnL @VitalyFedyunin @ejguan @NivekT @dzhulgakov

**Comment by Schefflera-Arboricola** [comment]
Can I please work on this issue?

**Comment by ejguan** [comment]
Please feel free to open a PR to fix it. The doc seems existing in the inline string though. https://github.com/pytorch/pytorch/blob/004f3d71aaec0ed2ddbb52c887d04a403186ebd4/torch/utils/data/dataloader.py#L166-L168

**Comment by felixdivo** [comment]
One could also amend the type hint(s) in the actual signature.

**Comment by NivekT** [comment]
`multiprocessing_context` was recently added to the doc (#99371), it is visible on the `main` branch's doc as well (not in 2.0):

https://pytorch.org/docs/main/_modules/torch/utils/data/dataloader.html#DataLoader

Please feel free to re-open the issue if you feel that it should be added elsewhere (that doesn't already exist in `main`).
