### ISSUE TITLE
Numerical error building up with `tensor.item()`

### ISSUE THREAD

**Issue by gautierronan** [pytorch/pytorch#100039]
### 🐛 Describe the bug

A different numerical error is building up when repeateadly calling `.item()` on a tensor.
```python
import torch

x = 0.0
y = torch.tensor(0.0)
eps = torch.tensor(0.001)
for i in range(1_000_000):
    x += eps.item()
    y += eps

print(f"x = {x}")
print(f"y = {y.item()}")

# x = 1000.0000474974513
# y = 991.1415405273438
```

### Versions

PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Jan 11 2023, 10:02:19)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] pytorch-lightning==2.0.0
[pip3] torch==1.13.1
[pip3] torch-scatter==2.1.1
[pip3] torch-sparse==0.6.17
[pip3] torchaudio==0.13.1
[pip3] torchcde==0.2.5
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.11.4
[pip3] torchqdynamics==0.1.0
[pip3] torchqoc==1.0
[pip3] torchsde==0.2.5
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] pytorch-lightning         2.0.0                    pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torch-scatter             2.1.1                    pypi_0    pypi
[conda] torch-sparse              0.6.17                   pypi_0    pypi
[conda] torchaudio                2.0.1                    pypi_0    pypi
[conda] torchcde                  0.2.5                    pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchqdynamics            0.1.0                    pypi_0    pypi
[conda] torchqoc                  1.0                       dev_0    <develop>
[conda] torchsde                  0.2.5                    pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi

**Comment by drisspg** [comment]
By default torch factory functions I.e. `y = torch.tensor(0.0)` will use float32 types. If instead you construct y with: 
`y = torch.tensor(0.0, dtype=torch.float64)`
and run the above script I get output:

```
x = 1000.0000474974513
y = 1000.0000474974513
```

**Comment by gautierronan** [comment]
I don't see how this is related. Calling `.item()` on a tensor gives the same value, even if it is a float32 tensor.
```python
import torch
torch.set_printoptions(precision=19)

eps = torch.tensor(0.001)

print(eps)
print(eps.item())

# tensor(0.0010000000474974513)
# 0.0010000000474974513
```

**Comment by gautierronan** [comment]
Also, if I run the script with `range(2)` or `range(3)`, I get very different behavior:
```python
x = 0.0
y = torch.tensor(0.0)
eps = torch.tensor(0.001)
for i in range(2):
    x += eps.item()
    y += eps

print(f"x = {x}")
print(f"y = {y.item()}")

# x = 0.0020000000949949026
# y = 0.0020000000949949026
```

```python
x = 0.0
y = torch.tensor(0.0)
eps = torch.tensor(0.001)
for i in range(3):
    x += eps.item()
    y += eps

print(f"x = {x}")
print(f"y = {y.item()}")

# x = 0.003000000142492354
# y = 0.003000000026077032
```

**Comment by drisspg** [comment]
I wrote up this godbolt to try and better explain what is happening under the hood:
https://godbolt.org/z/Mv5GjGhnr

Let me know if this helps!
