### ISSUE TITLE
[Dynamo] How to better handle customized list/dict 

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#100181]
### 🐛 Describe the bug

This is a pattern I found from Meta internal user case:
```
import torch
import logging
import torch._dynamo
from typing import Any, List, Optional

torch._logging.set_logs(dynamo=logging.DEBUG)

class _non_none_list(list):
    def append(self, obj: Any):
        if obj is not None:
            super().append(obj)

    def extend(self, lst: Optional[List[Any]]):
        if lst is not None:
            super().extend(x for x in lst if x is not None)

def fn(x):
    a = _non_none_list()
    a.append(x)
    a.append(x + 1)
    return torch.cat(a, dim=1)

x = torch.rand(2, 2)
print(fn(x))
opt_fn = torch.compile(backend="eager")(fn)
print(opt_fn(x))
```

There are three major graph breaks:
* ```Unsupported: call_function UserDefinedClassVariable() [] {}``` when calling ```_non_none_list()```.
* ```Unsupported: non-function or method super: <method 'append' of 'list' objects>``` when calling ```super().append(obj)```
* ```Unsupported: call_function args: UserDefinedObjectVariable(_non_none_list) ConstantVariable(int)``` when calling ```torch.cat(a, dim=1)```.

However, if I switch the customized list to python builtin list, there is no graph break. I'd like to know what is dynamo's story to handle customized list/dict. 

### Versions

N/A

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by yanboliang** [comment]
cc @jansel

**Comment by jansel** [comment]
We already have some handling for `dict` subclasses.  I think it would be possible to improve that, though not sure how common a pattern like this is.

**Comment by yanboliang** [comment]
Had advised customers to rewrite it into two functions: ```_list_append_non_none``` and ```_list_extend_non_none```, then there is no graph break. I'll close this issue.
