### ISSUE TITLE
Subclassed `TransformerEncoderLayer` breaks scripting of TransformerEncoder

### ISSUE THREAD

**Issue by ecly** [pytorch/pytorch#100188]
### 🐛 Describe the bug

For my use case, I need to subclass `TransformerEncoderLayer` to make some minor modifications to support SwiGLU.
It seems however that no matter what subclass of `nn.TransformerEncoderLayer` is supplied to the `TransformerEncoder`, the class `nn.TransformerEncoderLayer` is unknown for the `isinstance` check performed for sparsity fast path checks at scripting time. This is also the case if the current `isinstance` is replaced with `torch.jit.isinstance`.

```python
import torch
from torch.nn import TransformerEncoder, TransformerEncoderLayer
class MyCustomerLayer(TransformerEncoderLayer):
    pass

encoder = TransformerEncoder(MyCustomerLayer(d_model=256, nhead=8), num_layers=6)
torch.jit.script(encoder)
```

This produces the following error on nightly:
```python
/home/ecly/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/jit/_recursive.py:266: UserWarning: 'batch_first' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
Traceback (most recent call last):
  File "/home/ecly/.pyenv/versions/3.10.6/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ecly/.pyenv/versions/3.10.6/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ecly/Programming/work/myrepo/reproduce.py", line 7, in <module>
    torch.jit.script(encoder)
  File "/home/ecly/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/jit/_script.py", line 1284, in script
    return torch.jit._recursive.create_script_module(
  File "/home/ecly/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/jit/_recursive.py", line 480, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/ecly/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/jit/_recursive.py", line 546, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/ecly/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
Unknown type name 'torch.nn.TransformerEncoderLayer':
  File "/home/ecly/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 237
        why_not_sparsity_fast_path = ''
        str_first_layer = "self.layers[0]"
        if not isinstance(first_layer, torch.nn.TransformerEncoderLayer):
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            why_not_sparsity_fast_path = f"{str_first_layer} was not TransformerEncoderLayer"
        elif first_layer.norm_first :
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230427+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 12.2.1 20230201
Clang version: 15.0.7
CMake version: version 3.26.3
Libc version: glibc-2.37

Python version: 3.10.6 (main, Dec 21 2022, 10:52:50) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.37
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 531.68
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 9 3950X 16-Core Processor
CPU family:                      23
Model:                           113
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        7000.03
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload umip rdpid
Virtualization:                  AMD-V
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       512 KiB (16 instances)
L1i cache:                       512 KiB (16 instances)
L2 cache:                        8 MiB (16 instances)
L3 cache:                        16 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==2.1.0.dev20230427+cpu
[conda] Could not collect

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg

**Comment by mikekgfb** [comment]
Can you just pass the SwiGLU activation function callable to the TransformerEncoderLayer()?
```
torch.nn.TransformerEncoderLayer(d_model, nhead, dim_feedforward=2048, dropout=0.1, activation=<function relu>, layer_norm_eps=1e-05, batch_first=False, norm_first=False, device=None, dtype=None)
[...]

```
as per https://pytorch.org/docs/stable/generated/torch.nn.TransformerEncoderLayer.html with 

activation ([Union](https://docs.python.org/3/library/typing.html#typing.Union)[[str](https://docs.python.org/3/library/stdtypes.html#str), [Callable](https://docs.python.org/3/library/typing.html#typing.Callable)[[[Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)], [Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)]]) – the activation function of the intermediate layer, can be a string (“relu” or “gelu”) or a unary callable. Default: relu

**Comment by ecly** [comment]
@mikekgfb sadly the SwiGLU activation has a trainable parameter as well, so it requires a few changes to the `TransformerEncoderLayer` to support, so the `activation` keyword argument's flexibility is not enough to use it.

**Comment by mikekgfb** [comment]
> @mikekgfb sadly the SwiGLU activation has a trainable parameter as well, so it requires a few changes to the `TransformerEncoderLayer` to support, so the `activation` keyword argument's flexibility is not enough to use it.

What happens if you pass a constructor for your SwiGLU module as activation since nn.modules are callables?

**Comment by mikekgfb** [comment]
Root cause for the specific problem is that isinstance() in torchscript does not work.  Various workarounds might be considered, either in torchscript or in the TEL module itself (likely degrading function for non-TS users).

**Comment by ecly** [comment]
@mikekgfb makes sense and is understandable. Sorry for the slow response. I will check tomorrow whether it is feasible for me to reuse the standard `TransformerEncoderLayer` with a stateful activation like you show, and share some code both if I'm successful and if I'm not.

**Comment by ecly** [comment]
@mikekgfb it gets a little messy because of the need to modify `dim_feedforward` of the `TransformerEncoderLayer` when using SwiGLU. I just need to delegate the responsibility of changing that dimension to the place in which the `TransformerEncoderLayer` is instantiated, instead of inside the subclass, but that is not hugely problematic.

The implementation that I have right now (that is incompatible with TorchScript) uses a customer layer defined as:

```python
class _TransformerEncoderLayerSwiGLU(nn.TransformerEncoderLayer):
    def __init__(
        self,
        d_model: int,
        nhead: int,
        dim_feedforward: int,
        dropout: float = 0.1,
        norm_first: bool = False,
        gate_multiple_of: int = 128,
        **_kwargs,
    ) -> None:
        super().__init__(
            d_model,
            nhead,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            activation=F.silu,
            norm_first=norm_first,
        )
        # Reference:
        #     https://github.com/facebookresearch/llama/blob/main/llama/model.py
        dim_feedforward = int(2 * dim_feedforward / 3)
        dim_feedforward = gate_multiple_of * (
            (dim_feedforward + gate_multiple_of - 1) // gate_multiple_of
        )
        self.linear1 = nn.Linear(d_model, dim_feedforward)
        self.linear2 = nn.Linear(dim_feedforward, d_model)
        self.linear3 = nn.Linear(d_model, dim_feedforward)

    def _ff_block(self, x):
        x = self.linear2(
            self.dropout(self.activation(self.linear1(x)) * self.linear3(x))
        )
        return self.dropout2(x)
```

The workaround I was toying with prior to your suggestion of the stateful activation was simply to use a subclass of `TransformerEncoder` where I changed the `forward` function to remove the `isinstance`, but I do think that it may still be cleaner to use your proposed approach.

**Comment by jhoareau** [comment]
FYI @ecly SwiGLU uses 3 linear layers instead of 2 in the base Transformer feedforward implementation, because that's inherently how we can gate it and get the accuracy boost, so we'll be forced to subclass in all cases

**Comment by ecly** [comment]
@jhoareau you are right, but I don't think it's the 3rd layer that is the problem. As @mikekgfb's was eluding to, we can have the 3rd linear layer stored inside the activation, which almost works in this case, e.g. using something like:
```python
class _SwiGLU(nn.Module):
    def __init__(self, d_model: int, dim_feedforward: int):
        super().__init__()
        self.linear3 = nn.Linear(d_model, dim_feedforward)

    def forward(self, x):
        return F.silu(x) * self.linear3(x)


def get_swiglu_encoder_layer(
    d_model: int,
    nhead: int,
    dim_feedforward: int,
    gate_multiple_of: int = 128,
    **kwargs,
):
    # Reference:
    #     https://github.com/facebookresearch/llama/blob/main/llama/model.py
    dim_feedforward = int(2 * dim_feedforward / 3)
    dim_feedforward = gate_multiple_of * (
        (dim_feedforward + gate_multiple_of - 1) // gate_multiple_of
    )
    activation = _SwiGLU(d_model, dim_feedforward)
    return nn.TransformerEncoderLayer(
        d_model, nhead, dim_feedforward, activation=activation, **kwargs
    )
```

But sadly, since we are feeding the original `x` into the `linear3`, and not the `x` that has already been processed by `linear1` (which is all we would have access to in our activation), this is not adequate for this use case. So indeed, it seems we are stuck with simply subclassing `TransformerEncoder` to remove the `isinstance` check for now, if we want to continue using TorchScript.

**Comment by mikekgfb** [comment]
Thanks for this thorough investigation!  Thus far we have established isinstance is broken with respect to subclasses and almost unusable because torchscript does not have a view of the class hierarchy. (Notice that calls to super().function are not supported today either)  @davidberard98 and I have discussed a possible path forward that would address the issue at hand with the example that you gave, and is reasonably compatible with eager mode execution.  There is no implementation yet, and no ETA, nor a proof of full viability.

We are increasingly of the mind that the best path forward is for developers to write their own Transformer Encoder (and Decoder…) class since the dominant amount of work is in the layer and the encoder adds but a loop (e.g., https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/transformer.py#L373-L379)

The transformer encoder/decoder layers in turn might either call nn.MHA (or F.MHA), or the newly introduced SDPA operator since the overhead of all MHA variants is both considerable and yet insufficient to express all possible operating modes and variants for multi head attention.  Thus, calling sdpa directly will cut out a lot of the processing that is performed for unused options of F.MHA. (A good example of using sdpa is Andrej Karpathy’s nanoGPT.)

A big thank you to my colleagues @cpuhrsch  and @davidberard98 for many discussions and sharing their insights with me, and to @dberard for digging into the torchscript implementation of isinstance.

**Comment by ecly** [comment]
Sounds good @mike. This is indeed roughly also the option I have ended up implementing for now, i.e. a custom `TransformerEncoder` subclass, where I copy the forward function from the PyTorch one, and remove the `isinstance` check. This approach immediately works with TorchScript.

**Comment by mikekgfb** [comment]
> Sounds good @mike. This is indeed roughly also the option I have ended up implementing for now, i.e. a custom `TransformerEncoder` subclass, where I copy the forward function from the PyTorch one, and remove the `isinstance` check. This approach immediately works with TorchScript.

https://github.com/pytorch/pytorch/pull/102045 fixes this properly, allowing you to subclass TransformerEncoderLayer (and TransformerDecoderLayer too).  

Since you're subclassing TEL, you need to honor its interfaces, i.e., implement Nested Tensor support.  If you don't want to do that, Just define your own layer that does not subsclass transformerencoderlayer, and you can pass that to Transformerencoder.
