### ISSUE TITLE
test_multi_gpu_recompile_on_index_cpu regressed

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#100136]
`pytest test/inductor/test_torchinductor.py -k test_multi_gpu_recompile_on_index_cpu` fails on the main branch. https://github.com/pytorch/pytorch/pull/100135 moves the test to the right place so that CI can guard it.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10

**Comment by ngimel** [comment]
Is the test fixed now?

**Comment by desertfire** [comment]
> Is the test fixed now?

No, it's not. My diff (https://github.com/pytorch/pytorch/pull/100135) won't be able to land unless someone fixes the problem.

**Comment by desertfire** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/100135
