### ISSUE TITLE
Only allow people with write access to PyTorch to create SEV

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#100143]
### 🐛 Describe the bug

Some invalid SEV are created recently, may be by mistake or may be not.  So we should limit SEV creation to people with write access to PyTorch.  Here are some examples:

* https://github.com/pytorch/pytorch/issues/100142
* https://github.com/pytorch/pytorch/issues/99959

### Versions

PyTorch CI

cc @ZainRizvi @kit1980 @clee2000

**Comment by clee2000** [comment]
* remove ci sev lable by default
* remove timeline section
