### ISSUE TITLE
[Dynamo] Run in infinite recursion when tracing list which pointing to itself

### ISSUE THREAD

**Issue by ftxj** [pytorch/pytorch#100150]
### 🐛 Describe the bug

The example to reproduce the error is the following:
```python
import torch
root = []                
root[:] = [root, root, None, None] 
def test_bug():
    return root

fn = test_bug
fn = torch.compile(fn)

print(fn())
```

### Versions

PyTorch version: 2.0.0a0+1767026
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-156-generic-x86_64-with-glibc2.29
Is CUDA available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.0.0a0+1767026
[pip3] torch-tensorrt==1.4.0.dev0
[pip3] torchaudio==0.13.0.dev20220612+cu113
[pip3] torchdata==0.4.1
[pip3] torchmetrics==0.9.3
[pip3] torchtext==0.13.0a0+fae8e8c
[pip3] torchvision==0.14.0.dev20220612+cu113
[pip3] triton==2.1.0
[conda] Could not collect

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by anijain2305** [comment]
https://github.com/pytorch/pytorch/pull/100296 should fix this. It avoids the infinite recursion but with a graph break (the list assignment falls back to eager).
