### ISSUE TITLE
same issues after installs, uninstalls and reboots

### ISSUE THREAD

**Issue by roxasr** [pytorch/pytorch#100120]
### 🐛 Describe the bug

looking at the requirements to build and deserialize a model that was saved, I found outputs from 
torch.cuda.is_available() False after cudatoolkit install 11.7 and driver 516.25 installed. i removed all the newer and older cudatool kits and the graphics drivers and after required and gut instincts, i rebooted again. Following the https://docs.nvidia.com/deeplearning/cudnn/pdf/cuDNN-Support-Matrix.pdf, i am working with Python 3.9.16 and torch 2.0 on windows 10 and still trying to figure out why I am still getting the same error message torch.cuda.is_available() False and nvidia-smi shows
| NVIDIA-SMI 516.25       Driver Version: 516.25       CUDA Version: 11.7

### Versions

StatusCode        : 200
StatusDescription : OK
Content           :
                    # Unlike the rest of the PyTorch this file must be python2 compliant.
                    # This script outputs relevant system environment info
                    # Run it with `python collect_env.py`.
                    import datetime
                    import locale
                    impor...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
                    Strict-Transport-Security: max-age=31536000
                    X-Content-Type-Options: nosniff
                    ...
Forms             : {}
Headers           : {[Connection, keep-alive], [Content-Security-Policy, default-src 'none'; style-src
                    'unsafe-inline'; sandbox], [Strict-Transport-Security, max-age=31536000],
                    [X-Content-Type-Options, nosniff]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 21550

**Comment by zou3519** [comment]
Can you please run and show us the output of `python collect_env.py`?

**Comment by ptrblck** [comment]
Looks like a double post from [here](https://discuss.pytorch.org/t/incompatibility-with-cuda-cudnn-torch-and-conda-anaconda/178621/7?u=ptrblck) which uses wrong install commands not shown in the install instructions.

**Comment by ngimel** [comment]
Closing, please reopen if @ptrblck's diagnosis is wrong.
