### ISSUE TITLE
Logging suggestions upon Dynamo error do not log

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#100109]
When I hit an error during compilation, I see a message like:
```
torch._dynamo.exc.TorchRuntimeError: 

from user code:
   File "/.../transformers/src/transformers/models/t5/modeling_t5.py", line 559, in <resume in forward>
    scores += position_bias_masked

Set torch._dynamo.config.verbose=True or TORCHDYNAMO_VERBOSE=1 for more information
```
However, setting `torch._dynamo.config.verbose=True` and running with `TORCHDYNAMO_VERBOSE=1` both do not print any logs (though, running with `TORCH_LOGS=dynamo` does).

1. Is the suggestion in the error message out of date?
2. Where can we find the current selection of logging options and how to enable them?
Maybe https://pytorch.org/docs/stable/dynamo/troubleshooting.html is not up to date?

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by wconstab** [comment]
yea, this is out of date info. You want `TORCH_LOGS=+dynamo` for debug, or drop the `+` for info.  (note: if you type something wrong into `TORCH_LOGS` itll tell you the valid component options you can choose from, and i am just saying dynamo from memory but could be wrong)

@mlazos do you want to update the docs? or else i can help with that.

**Comment by mlazos** [comment]
Yeah I can update the docs, I was planning on doing it for the docathon but I can start now since people are making mistakes with it.
