### ISSUE TITLE
torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275

### ISSUE THREAD

**Issue by janelu9** [pytorch/pytorch#100142]
deepspeed 0.9.0
torch 2.0
`torch.distributed.barrier()`

NCCL error in:
torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275

**Comment by huydhn** [comment]
This is not how `ci: sev` label should be used, please create a bug report to PyTorch instead https://github.com/pytorch/pytorch/issues/new?assignees=&labels=&template=bug-report.yml
