### ISSUE TITLE
[BE] More informative error messages in `THPVariable_set_grad`

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#100174]
https://github.com/pytorch/pytorch/blob/31f311a816c026bbfca622d6121d6a7fab44260d/torch/csrc/autograd/python_variable.cpp#L896
When the gradient metadata does not match the corresponding tensor's metadata, `THPVariable_set_grad()` raises an error, e.g.:
```
RuntimeError: assigned grad has data of a different type
```
Including what leads to the mismatch would be very helpful. For example, for the above message, if we could see something like:
```
RuntimeError: assigned grad has data of type torch.float16 that differs from the required torch.float32
```
A similar idea applies for mismatched devices and sizes.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @malfet

**Comment by awgu** [comment]
Following up on this, consider the following two asserts:
https://github.com/pytorch/pytorch/blob/31f311a816c026bbfca622d6121d6a7fab44260d/torch/csrc/autograd/python_variable.cpp#L920-L923
https://github.com/pytorch/pytorch/blob/31f311a816c026bbfca622d6121d6a7fab44260d/torch/csrc/autograd/python_variable.cpp#L924-L929
Can the second one (which is checked after the first) ever be triggered?

If I look at `options()`, it includes the `device`:
https://github.com/pytorch/pytorch/blob/31f311a816c026bbfca622d6121d6a7fab44260d/aten/src/ATen/core/TensorBase.h#L557-L561

```
>>> t = torch.randn((3, 3), device="cuda")
>>> g = torch.randn((3, 3), device="cpu")
>>> t.grad = g
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: assigned grad has data of a different type
```

**Comment by albanD** [comment]
I would expect `type_equal()` to only check the dtype? But maybe that's not true.

We would definitely be happy with a PR improving these errors!

**Comment by awgu** [comment]
https://github.com/pytorch/pytorch/blob/e6f9bc500b4043ea6bdfdc84981df18028413200/c10/core/TensorOptions.h#L364-L367
Maybe the first clause on the dispatch key equality is causing the non-intuitive behavior since it seems to be a function of the device?
https://github.com/pytorch/pytorch/blob/e6f9bc500b4043ea6bdfdc84981df18028413200/c10/core/TensorOptions.h#L439-L442

**Comment by bdhirsh** [comment]
```
   THPUtils_assertRet( 
       -1, 
       grad.get_device() == var.get_device(), 
       "assigned grad has data located on a different device"); 
 } 
```

It looks like `get_device()` checks that the device **index** matches, e.g. `cuda:0` vs `cuda:` ([code](https://github.com/pytorch/pytorch/blob/31f311a816c026bbfca622d6121d6a7fab44260d/aten/src/ATen/core/TensorBase.h#L412))

For the first check involving `type_equal()` - dispatch keys take into account the device type, but not the device index. So that first check will only error if e.g. the two tensors are on `cpu` vs `cuda`, but not if the two tensors have different indices, like `cuda:0` vs `cuda:1`.
