### ISSUE TITLE
Illegal instruction in ARM64 (ver 2.0.0)

### ISSUE THREAD

**Issue by NitCoh** [pytorch/pytorch#100156]
### 🐛 Describe the bug

Illegal instruction while importing torch. (version 2.0.0)
AWS Machine: a1.large
AMI: amzn2-ami-kernel-5.10-hvm-2.0.20230418.0-arm64-gp2

python code:
import torch

example:
>>> import torch
Illegal instruction

Note: Downgrading to 1.13.1 solves the issue.

### Versions

Can't run collect_env.py on version 2.0.0 cause I can't import torch.
But, downgrading to 1.13.1 solves the issue, so here are the details:

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (aarch64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.26

Python version: 3.9.0 (default, Apr 27 2023, 08:22:43)  [GCC 7.3.1 20180712 (Red Hat 7.3.1-15)] (64-bit runtime)
Python platform: Linux-5.10.177-158.645.amzn2.aarch64-aarch64-with-glibc2.26
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
BogoMIPS:            166.66
L1d cache:           32K
L1i cache:           48K
L2 cache:            2048K
NUMA node0 CPU(s):   0,1
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid

Versions of relevant libraries:
[pip3] torch==1.13.1
[conda] Could not collect

cc @seemethere @malfet

**Comment by vmc-7645** [comment]
I'm getting the same issue with my Cortex-A53. It's weird as one version of the board works (same exact chipset aside for RAM), but the other (newer) version doesn't.

**Comment by wtarreau** [comment]
2.0.0 used to crash for me on an A72 as well, upgrading to 2.0.1 fixed it.

**Comment by malfet** [comment]
Was fixed in 2.0.1, closing
