### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'mps' for torch==2.0.0 on MacOS

### ISSUE THREAD

**Issue by ANYMS-A** [pytorch/pytorch#100165]
### 🐛 Describe the bug

Can't find mps module for torch==2.0.0 on MacOS.

```python
import torch
torch.mps
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.6 (default, Oct 18 2022, 12:41:40)  [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-13.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchvision==0.15.1
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/98837

**Comment by albanD** [comment]
Closing as this is fixed in master and will be in future releases.
You can explicitly import it as a temporary workaround: `from torch import mps`.

**Comment by KE7** [comment]
<3
