### ISSUE TITLE
torch.nonzero crashes if invoked from multiple threaded

### ISSUE THREAD

**Issue by yxhdxy** [pytorch/pytorch#100285]
### 🐛 Describe the bug

```python
import torch
import numpy as np
image_tensor = torch.tensor(np.random.rand(256, 256, 3) * 255, dtype=torch.float32, device="mps")
image_tensor
'''
-[_MTLCommandBuffer addCompletedHandler:]:867: failed assertion `Completed handler provided after commit call'
'''
``` 

### Versions

PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A
OS: macOS 13.3.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.22.3
Libc version: N/A
Python version: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:13)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
CPU:
Apple M1 Pro
Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[conda] numpy                     1.24.2           py38hac8ee1c_0    conda-forge
[conda] pytorch                   2.0.0                   py3.8_0    pytorch
[conda] torchaudio                2.0.0                  py38_cpu    pytorch
[conda] torchvision               0.15.0                 py38_cpu    pytorch

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Hmm, can you provide any additional details on your system setup? I can not reproduce it using neither conda nor wheel packages for 2.0.0

**Comment by yxhdxy** [comment]
HI Malfet,

While I'm attempting to run this script in PyCharm's Python Console, the error occurs. 
<img width="871" alt="image" src="https://user-images.githubusercontent.com/101998546/235262182-5ed8bd81-9974-462c-8670-5c689c147fb5.png">


However, if I use terminal, everything goes well.

Thanks 

> Hmm, can you provide any additional details on your system setup? I can not reproduce it using neither conda nor wheel packages for 2.0.0

**Comment by yxhdxy** [comment]
> HI Malfet,
> 
> While I'm attempting to run this script in PyCharm's Python Console, the error occurs. <img alt="image" width="871" src="https://user-images.githubusercontent.com/101998546/235262182-5ed8bd81-9974-462c-8670-5c689c147fb5.png">
> 
> However, if I use terminal, everything goes well.
> 
> Thanks
> 
> > Hmm, can you provide any additional details on your system setup? I can not reproduce it using neither conda nor wheel packages for 2.0.0

Works well in JupyterNotebook and VScode as well.

**Comment by golmschenk** [comment]
Hello! I'm getting the same error when attempting to view the properties of an MPS tensor at a breakpoint in PyCharm. A minimal example of code is:
```
import torch
from torch.nn import Conv1d

device = torch.device('mps')

m = Conv1d(16, 33, 3, stride=2).to(device)
input = torch.randn(20, 16, 50).to(device)
output = m(input)  # Breakpoint here.
```
If PyCharm is not inspecting the tensor the crash does not occur. However, as soon as I open the `input` tensor dropdown in PyCharm. I have also encountered the error in more complex code cases, when switching frames in the debugger (rather than viewing the properties of a variable). Perhaps @yxhdxy error is occurring because PyCharm is attempting to inspect something causing the error?

Video of error occurring:

https://user-images.githubusercontent.com/1691031/236091492-2676dc22-14eb-4ff3-bf10-c09d12b2d51a.mov

**Comment by hmliunian** [comment]
I have the same problem that doesn't occur when I use the runtime. But it only appears when I use the debugger

**Comment by malfet** [comment]
Hmm, can anyone reproduce it outside of PyCharm? For example in pdf?

**Comment by malfet** [comment]
Ok, I have a reproducer outside of PyCharm:
```python
import torch
import threading

def f1(x, y):
    z=torch.add(x, y)
    print(z)

x=torch.rand(3, 3, device="mps")
y=torch.rand(3, 3, device="mps")

t1 = threading.Thread(target=f1, args=(x, y))
t2 = threading.Thread(target=f1, args=(x, y))
t1.start()
t2.start()
```

And this happens due to the bug in `non_zero_out` which calls `stream->synchronize()` outside of `dispatch_sync` block, i.e. following fixes the issues:
```cpp
diff --git a/aten/src/ATen/native/mps/operations/Indexing.mm b/aten/src/ATen/native/mps/operations/Indexing.mm
index 4138f26612f..397722f77f0 100644
--- a/aten/src/ATen/native/mps/operations/Indexing.mm
+++ b/aten/src/ATen/native/mps/operations/Indexing.mm
@@ -323,7 +323,9 @@ static Tensor nonzero_fallback(const Tensor& self) {
     MPSGraphTensor* scatterDataTensor_ = nil;
   };
 
-  stream->synchronize(SyncType::COMMIT_AND_WAIT);
+  dispatch_sync(stream->queue(), ^() {
+    stream->synchronize(SyncType::COMMIT_AND_WAIT);
+  });
   int64_t total_nonzero = at::count_nonzero(self).item<int64_t>();
   at::native::resize_output(out_, {total_nonzero, nDim});
   if (out_.numel() == 0) {
```

**Comment by pauluskim** [comment]
@malfet Thanks for the amazing finding.
But could you let me know where the mps/operations/Indexing.mm file is in?
I can't find it under torch library.
