### ISSUE TITLE
DISABLED trunk / win-vs2019-cuda11.7-py3 / test

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#100273]
> For example, DISABLED pull / win-vs2019-cpu-py3 / test (default). Once
> created, the job will be disabled within 15 minutes. You can check the
> list of disabled jobs at https://ossci-metrics.s3.amazonaws.com/disabled-jobs.json

> If you need to get this out ASAP instead of waiting for 15 minutes,
> you can manually trigger the workflow at https://github.com/pytorch/test-infra/actions/workflows/update_disabled_tests.yml
> once the issue is created to update the above JSON list right away.

> Noted: you need to have write access to PyTorch repo to disable CI
> jobs. The issue will be rejected otherwise.

## Reason
Windows CUDA tests are broken with the new AMI https://hud.pytorch.org/pytorch/pytorch/commit/c4bed869d16e9e0b761b82dda9130cfc14479141

cc @seemethere @malfet @pytorch/pytorch-dev-infra @atalman

**Comment by huydhn** [comment]
The root cause has been identified to be a newer numpy version 1.24.3 https://anaconda.org/anaconda/numpy

**Comment by ZainRizvi** [comment]
> The root cause is likely to be a newer numpy version 1.24.3 https://anaconda.org/anaconda/numpy (uploaded 7h ago)

Yup. Here's the error we're seeing in the logs:
```
C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\nn\init.py:412: UserWarning: Failed to 
initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered 
internally at C:\actions-runner\_work\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
```

**Comment by huydhn** [comment]
From what I see in the failures, the old AMI is `ami-0cb5dda04b9db295d` and the newer one is `ami-00c4c6048677336a7`.  The theory is that Windows build job was built with the old one, and the test job used the newer one, thus the mismatch.  If both use the same AMI, the issue should be mitigated?

**Comment by ZainRizvi** [comment]
> If both use the same AMI, the issue should be mitigated?

Yup, sounds right
