### ISSUE TITLE
Unable to Run PyTorch C++ Frontend Example from Documentation

### ISSUE THREAD

**Issue by brennschlus** [pytorch/pytorch#100246]
### 🐛 Describe the bug

I am having trouble running the C++ PyTorch example from this [tutorial](https://pytorch.org/tutorials/advanced/cpp_frontend.html). Specifically, after downloading the latest C++ LibTorch distribution with ROCm support in my Fedora Linux machine, I wrote the following code in dcgan.cpp:

```cpp

#include <torch/torch.h>
#include <iostream>

int main() {
  torch::Tensor tensor = torch::eye(3);
  std::cout << tensor << std::endl;
}
```

I also created a CMakeLists.txt file with the following contents:

```cmake

cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(dcgan)

set(Torch_DIR /path/to/libtorch/share/cmake/Torch)
set(CMAKE_PREFIX_PATH /path/to/libtorch)
set(USE_ROCM ON)
set(USE_CUDA OFF)

find_package(Torch REQUIRED)

add_executable(dcgan dcgan.cpp)
target_link_libraries(dcgan "${TORCH_LIBRARIES}")
set_property(TARGET dcgan PROPERTY CXX_STANDARD 14)
```

However, when I run cmake, I receive the following error message:

```bash

CMake Error at /path/to/libtorch/libtorch/share/cmake/Caffe2/Caffe2Targets.cmake:101 (set_target_properties):
  The link interface of target "torch_hip_library" contains:

    roc::rocblas

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /path/to/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:110 (include)
  /path/to/libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:9 (find_package)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Steps to Reproduce

   - Download the latest C++ LibTorch distribution with ROCm support in Fedora Linux.
   - Write the dcgan.cpp file and CMakeLists.txt file as shown above.
   - Run cmake.

Expected Behavior

- cmake should generate the build files correctly.

Actual Behavior

- cmake fails with the above error message.

Additional Information

  -  Operating System: Fedora Linux
  -  LibTorch Version: 2.0 + rocm 5.4.2
  - GPU: AMD Radeon RX 6700 XT   

### Versions

PyTorch version: 2.0.0+rocm5.4.2
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.4.22803-474e8620

OS: Fedora Linux 38 (Workstation Edition) (x86_64)
GCC version: (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
Clang version: 16.0.0 (Fedora 16.0.0-2.fc38)
CMake version: version 3.25.0
Libc version: glibc-2.37

Python version: 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.2.12-200.fc37.x86_64-x86_64-with-glibc2.37
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Radeon RX 6700 XT
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.4.22803
MIOpen runtime version: 2.19.0
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 5700X 8-Core Processor
CPU family:                      25
Model:                           33
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        2
Frequency boost:                 enabled
CPU(s) scaling MHz:              62%
CPU max MHz:                     4661.7178
CPU min MHz:                     2200.0000
BogoMIPS:                        6799.82
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        32 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.3
[pip3] numpydoc==1.5.0
[pip3] open-clip-torch==2.7.0
[pip3] pytorch-lightning==1.9.4
[pip3] pytorch-triton-rocm==2.0.1
[pip3] torch==2.0.0+rocm5.4.2
[pip3] torchaudio==2.0.1+rocm5.4.2
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.11.4
[pip3] torchsde==0.2.5
[pip3] torchvision==0.15.1+rocm5.4.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] numpydoc                  1.5.0           py310h06a4308_0  
[conda] open-clip-torch           2.7.0                    pypi_0    pypi
[conda] pytorch-lightning         1.9.4                    pypi_0    pypi
[conda] pytorch-triton-rocm       2.0.1                    pypi_0    pypi
[conda] torch                     2.0.0+rocm5.4.2          pypi_0    pypi
[conda] torchaudio                2.0.1+rocm5.4.2          pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchsde                  0.2.5                    pypi_0    pypi
[conda] torchvision               0.15.1+rocm5.4.2          pypi_0    pypi

cc @jbschlosser @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by jeffdaily** [comment]
Looks like CMake is trying to find the rocblas package and cannot.  Do you have rocblas installed using fedora's package manager?

**Comment by tada123** [comment]
I had similar problem and found that the problem is in the CMake itself.
Don't really know what happened, but **removing** the `cmake_minimum_required(VERSION 3.0 FATAL_ERROR)` from `CMakeLists.txt` solved the issue (probably some compatibility layer).

If the above still not working, you might try adding to CMake module path `export CMAKE_MODULE_PATH=/opt/rocm/lib/cmake/`
