### ISSUE TITLE
GCP hosts unable to connect to docker daemon

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#100398]
> NOTE: Remember to label this issue with "`ci: sev`"

inductor benchmarking jobs will fail
https://github.com/pytorch/pytorch/actions/runs/4847702302/jobs/8638468604#step:5:68
```
Prepare all required actions
Getting action download info
Run ./.github/actions/setup-linux
Run set -euo pipefail
ami-id: Runner is from Google Cloud Platform, No info on ec[2](https://github.com/pytorch/pytorch/actions/runs/4847702302/jobs/8638468604#step:5:2) metadata
instance-id: Runner is from Google Cloud Platform, No info on ec2 metadata
instance-type: Runner is from Google Cloud Platform, No info on ec2 metadata
system info Linux gh-ci-gcp-a100-19 5.15.0-10[3](https://github.com/pytorch/pytorch/actions/runs/4847702302/jobs/8638468604#step:5:3)1-gcp #38~20.04.1-Ubuntu SMP Sun Mar 12 04:47:58 UTC 2023 x8[6](https://github.com/pytorch/pytorch/actions/runs/4847702302/jobs/8638468604#step:5:7)_64 x86_64 x86_64 GNU/Linux
Run if systemctl is-active --quiet docker; then
Docker daemon is running...
Run nick-fields/retry@3e91a01664abd3c5cd539100d10d33b9c5b68482
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth": dial unix /var/run/docker.sock: connect: permission denied
Warning: Attempt 1 failed. Reason: Child_process exited with error code 1
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth": dial unix /var/run/docker.sock: connect: permission denied
Warning: Attempt 2 failed. Reason: Child_process exited with error code 1
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth": dial unix /var/run/docker.sock: connect: permission denied
Error: Final attempt failed. Child_process exited with error code 1
```

## Current Status
*Status could be: preemptive, ongoing, mitigated, closed. Also tell people if they need to take action to fix it (i.e. rebase)*.

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 10/30 7:27a incident began
- 10/30 8:30a detected by <method>
- 10/30 9:00 pm root caused as…
- 10/30 9:10 pm mitigated by…
- 10/31 10: am closed by…

</details>

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by seemethere** [comment]
Mitigated this manually by running the following commands:

```bash
#!/usr/bin/env bash

# Gather all running instances with the name gh-ci-*-a100
gcloud compute instances list --filter="STATUS=RUNNING and NAME:gh-ci and NAME:a100" --format='value(name)' > inventory

# Add ubuntu user to docker group
for node in $(cat inventory); do 
    (set -x; gcloud compute ssh ${node} --command 'sudo usermod -aG docker ubuntu'); 
done

# Restart service to force login / logout of ubuntu user to apply group changes
for node in $(cat inventory); do 
    (set -x; gcloud compute ssh ${node} --command 'set -x; cd /home/weiwangmeta/actions-runner && sudo ./svc.sh stop && sudo ./svc.sh start'); 
done
```

Basic tl;dr of the root cause it is that the Github runner daemon service runs as a specific user, recently that user was changed which was found out by looking through the bash history with:

```bash
# svc.sh is a github runner daemon paradigm for install the service to a specific user
history | grep 'svc.sh install'
# the output for this was something like `sudo ./svc.sh install ubuntu`
# meaning the service was installed recently for the ubuntu user
# another way to check this would be to run a workflow on the runner itself and just `echo $USER`
```

**Comment by desertfire** [comment]
> ```shell
> svc.sh install
> ```

Do we need to do this if we spin a new runner, or restart an existing runner? e.g. gh-ci-gcp-a100-8 is offline now. If I take it back, do I need to run this manually?

**Comment by seemethere** [comment]
> > ```shell
> > svc.sh install
> > ```
> 
> Do we need to do this if we spin a new runner, or restart an existing runner? e.g. gh-ci-gcp-a100-8 is offline now. If I take it back, do I need to run this manually?

Running `install` is not required but running `start` is required
