### ISSUE TITLE
We would then like each process to span two GPUs each (DDP)

### ISSUE THREAD

**Issue by alicera** [pytorch/pytorch#100303]
### 📚 The doc issue

https://github.com/pytorch/examples/tree/main/distributed/ddp#argument-passing-convention

Do you have the example for  process to span two GPUs?

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by ngimel** [comment]
This mode is not supported iirc

**Comment by kumpera** [comment]
DDP only supports a single GPU per process and we have no plans to change that.
