### ISSUE TITLE
3x regression in JIT LSTM speeds

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#10032]
On a branch that hasn't pulled master in 7-days:

Benchmarking LSTM model forward pass with 1 layer, 512 hidden size, 512 input size, 100 seq length. All the weights have requires_grad=True.
```
thnn    cudnn   jit
9.2708  6.6107  11.4282
```
On current master:
```
thnn    cudnn   jit
9.8962  6.6269  30.7209
```

cc @zdevito

**Comment by zou3519** [comment]
One (probably minor) factor is that torch.chunk no longer distributes over some torch.add operations that used to happen.

**Comment by SsnL** [comment]
can you bisect?

**Comment by zou3519** [comment]
Appears to be memory leak. `torch.cuda.memory_allocated` scales linearly with the number of loops I run my LSTM

**Comment by zou3519** [comment]
Repro script, for reference:
```
import sys
import torch

@torch.jit.script
def fn(x, w_ih):
    return x * w_ih.t()

def foo():
    x = torch.randn(1, 1, device='cuda')
    wih = torch.randn(1, 1, device='cuda', requires_grad=True)

    fn(x, wih)
    return

# Initialize cuda things...
a = torch.randn(3, 3, device='cuda')

allocated = torch.cuda.memory_allocated()

foo()

now_allocated = torch.cuda.memory_allocated()
if allocated < now_allocated:
    print("leaked: {} bytes".format(now_allocated - allocated))
    exit(1)
```

**Comment by zou3519** [comment]
I think I've found a shared_ptr reference cycle:

ExecutionPlanAutogradFunction owns a vector of SharedVariable (https://github.com/pytorch/pytorch/blob/65d32b17057a35938d932b5071585be15e19af55/torch/csrc/jit/graph_executor.cpp#L98)

When it captures an input to save for backwards, this is called: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/graph_executor.cpp#L87. This creates a SharedVariable with a shared_ptr to the original ExecutionPlanAutogradFunction, completing the reference cycle.

Breaking the cycle should make this issue go away.

**Comment by fmassa** [comment]
I reopened this because I believe we only fixed the memory leak, and not the slowdown?

**Comment by soumith** [comment]
@fmassa i believe the slowdown was because of the memory leak.

**Comment by zou3519** [comment]
Yes the slowdown was due to memory leak
