### ISSUE TITLE
[BUG] add 1 to different tensor but get same value

### ISSUE THREAD

**Issue by zlw21gxy** [pytorch/pytorch#100370]
## Issue description

Generating a list of random tensors using device mps (M2 gpu), then I add a value on each by index, but it feedbacks the same value. Which means `data[1] + 1 = data[2] + 1` but of course `data[1]` is not equal to `data[2]`

So so so weird!!!

## Code example

```
import torch
d = torch.randint(0, 50000, size=(32, ), device=torch.device("mps"))
# d = torch.rand(size=(32, ), device=torch.device("mps"))

print(d)
print(d.dtype)
print("d1", d[1])
print("d1 + 1", d[1] + 1)
print("d2", d[2])
print("d2 + 1", d[2] + 1)
```
the output is 
```
tensor([ 6343,  1605, 28616,  2264, 12151, 13417,  1629, 32512,  4441, 43177,
         6520, 18301,  3608, 35951, 17655,  6629, 21160, 35743, 44574, 16854,
        24114, 26402, 16203, 26529, 45812, 46216, 19513, 30223, 37758, 14296,
         5785, 19335], device='mps:0')
torch.int64
d1 tensor(1605, device='mps:0')
d1 + 1 tensor(6344, device='mps:0')
d2 tensor(28616, device='mps:0')
d2 + 1 tensor(6344, device='mps:0')
```
So when you add 1 on each item in the tensor, it gives back the same value.

other Arithmetic operations are not correct as well
```
import torch
d = torch.randint(0, 50000, size=(32, ), device=torch.device("mps"))
# d = torch.rand(size=(32, ), device=torch.device("mps"))

print(d)
print(d.dtype)
print("d1", d[1])
print("d1 * 2", d[1] * 2)
print("d2", d[2])
print("d2 * 2", d[2] * 2)
```

## System Info

PyTorch version: 1.13.0.dev20220718
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:52:34)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-13.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by skotapati** [comment]
Does not repro with latest nightly, please reopen if the issue is observed again

```
>>> print("d1", d[1])
d1 tensor(37367, device='mps:0')
>>> print("d1 + 1", d[1] + 1)
d1 + 1 tensor(37368, device='mps:0')
>>> print("d2", d[2])
d2 tensor(23430, device='mps:0')
>>> print("d2 + 1", d[2] + 1)
d2 + 1 tensor(23431, device='mps:0')
```
