### ISSUE TITLE
[SPMD] Provides a common FX utility function to find a list of descendants of a set of nodes that can be moved

### ISSUE THREAD

**Issue by fegin** [pytorch/pytorch#100397]
### 🚀 The feature, motivation and pitch

FX graph transformation is a crucial technique for improving the communication and computation overlapping in DistCompiler. One common approach to optimizing this process involves rearranging the order of subgraphs within the given FX graph. However, currently, each transformation requires its own helper to identify the list of nodes before performing the move, leading to duplicated implementation.

To address this issue, a common API is desired that can be used across all transformations to identify the list of nodes that need to be moved. This would streamline the process and eliminate the need for duplicated implementation. An example of an existing implementation can be found in the following repository: https://github.com/pytorch/pytorch/blob/main/torch/distributed/_spmd/graph_optimization.py#L971.

By adopting a common API for identifying the list of nodes to move during FX graph transformation, the development process for DistCompiler can become more efficient and streamlined. This, in turn, can lead to better performance and more reliable results.

**Comment by awgu** [comment]
TIL about the "distributed-backlog" label.
