### ISSUE TITLE
_sfdp_init is extremely expensive for startup time, even on networks that don't benefit from it

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#100376]
### 🐛 Describe the bug

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/13564/235464215-6867ef63-1cdf-4054-a622-d5da14642e18.png">

In this speedscope profile, compiling a relatively trivial CPU program from cold start, sfdp_init is taking up a whopping three seconds, out of eight seconds end to end compile time.

To reproduce, I was just profiling this script:

```
import torch
import torch._dynamo
torch._inductor.config.cpp.inject_relu_bug_TESTING_ONLY = 'accuracy'
torch._dynamo.config.repro_after = "aot"
torch._dynamo.config.repro_level = 4
torch._dynamo.config.debug_dir_root = "/tmp/tmp5qmh2x01"
@torch.compile()
def inner(x):
    for _ in range(3):
        x = torch.sin(x)
    x = torch.relu(x)
    for _ in range(3):
        x = torch.cos(x)
    return x

inner(torch.randn(20, 20).to("cpu"))
```

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh @jansel 

### Versions

master

**Comment by jansel** [comment]
_sfdp_init just calls aot_autograd on a tiny function 8 times to create patterns.

We should just cache the result of this to disk.

**Comment by anijain2305** [comment]
cc @aorenste

**Comment by eellison** [comment]
Was fixed by https://github.com/pytorch/pytorch/pull/108894
