### ISSUE TITLE
Serializer breaks with custom classes

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#1003]
```python
import torch
class A:
    pass
torch.save(A(), 'a.pth')

# File ".../python2.7/site-packages/torch/serialization.py", line 120, in save
#    return _save(obj, f, pickle_module, pickle_protocol)
#  File ".../python2.7/site-packages/torch/serialization.py", line 186, in _save
#    pickler.dump(obj)
#  File ".../python2.7/site-packages/torch/serialization.py", line 150, in persistent_id
#    elif torch.is_storage(obj):
#   File ".../python2.7/site-packages/torch/__init__.py", line 100, in is_storage
#    return obj.__class__ in _storage_classes
# AttributeError: class A has no attribute '__class__'
```

Is it expected behavior?

Root cause seems to be te that `torch.is_tensor(obj)` and `torch.is_storage(obj)` expect an object to have the attribute `__class__`. And somehow serializer calls `torch.is_storage(A)` which blows (`torch.is_storage(A())` does not).

**Comment by soumith** [comment]
```
class A(object):
    pass
torch.save(A(), 'a.pth')
```

Classes have to be derived from `object` in py2 afaik.

**Comment by vadimkantorov** [comment]
I think the ones derived from object are called new-style classes or something like that.

I have patched `is_storage` and `is_tensor` to have:
`getattr(obj, "__class__", None) in _storage_classes`. It has solved the issue.

It may still be good to make is_tensor and is_storage to be robust to objects of old-style classes.

**Comment by soumith** [comment]
can you send a PR with that patch. Yes, if it's an easy fix, probs worth supporting old-style classes.

**Comment by soumith** [comment]
fixed in master. will be in next release.
