### ISSUE TITLE
Stop importing HuggingFace transformers in DataClassVariable

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#100386]
### 🐛 Describe the bug

There are some HF specific hacks here:

```
class DataClassVariable(ConstDictVariable):
    """             
    This is a bit of a hack to deal with
    transformers.file_utils.ModelOutput() from huggingface.
        
    ModelOutput causes trouble because it a a mix of a dataclass and a
    OrderedDict and it calls super() methods implemented in C.
    """ 
        
    # ModelOutput() excludes None, though generic datclasses don't
    include_none = False
                
    @staticmethod
    @functools.lru_cache(None)
    def _patch_once():
        from transformers.file_utils import ModelOutput
                
        for obj in ModelOutput.__dict__.values():
            if callable(obj):
                skip_code(obj.__code__)
            
    @staticmethod
    def is_matching_cls(cls):
        try:
            from transformers.file_utils import ModelOutput
    
            return issubclass(cls, ModelOutput)
        except ImportError:
            return False

```

Importing transformers takes about 0.5s; it would be much better if we could avoid importing it at all if the model in question doesn't involve transformers.

### Versions

master

cc @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @zou3519 @aakhundov @soumith @wconstab @ngimel @Xia-Weiwen @desertfire

**Comment by anijain2305** [comment]
cc @williamwen42

**Comment by ezyang** [comment]
This is still happening even in 0a1b3be2163ea99633f95c4927bd816eb713e9bd

**Comment by mlazos** [comment]
We no longer import, we check if the module has been imported and if not don't assume it isn't an HF class.
