### ISSUE TITLE
DISABLED test_equal (__main__.TestTorch)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#100340]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_torch.py%3A%3ATestTorch%3A%3Atest_equal)).

The cause seems to point to https://github.com/pytorch/pytorch/pull/100024 (or D45282119 as it was landed internally)

cc @mruberry @houseroad @ezyang

**Comment by ezyang** [comment]
Yeah, this is only failing in the inductor config. @houseroad as a quick unblock, just disable this on the inductor config with skipIfTorchDynamo

**Comment by huydhn** [comment]
Closing to see if https://github.com/pytorch/pytorch/pull/100364 helps fix the issue

**Comment by huydhn** [comment]
Reopen till https://github.com/pytorch/pytorch/pull/100364 is landed
