### ISSUE TITLE
Have mergebot properly handle review comments

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#100406]
If a user invokes `pytorchbot merge` while signing off on the PR, github classifies the comment as a "review comment" instead of a "direct comment."

Direct comments are correctly handled by mergebot, but not review comments.  This has led to [multiple occurrences](https://github.com/search?q=repo%3Apytorch%2Fpytorch+%22Reason%3A+Comment+with+id%22&type=pullrequests) where devs try to merge changes they're reviewing, but it fails

### The ask:
Do one of the following:
- Prevent pytorchbot from doing anything during a review comment, asking users to use a direct comment instead to merge their changes
- (Preferred) Make pytorchbot handle merges from review comments as well. This will prob require searching the github graphql api for the [reviewcomment]( https://docs.github.com/en/graphql/reference/objects#pullrequestreviewcomment)

### Additional context
This is a review comment:
![Image](https://user-images.githubusercontent.com/4468967/235515755-31c99d8e-b726-4c58-935c-7faffb8c7dd4.png)

cc @kit1980 @huydhn @clee2000

**Comment by kit1980** [comment]
I actually implemented this long time ago and it was working fine: https://github.com/pytorch/test-infra/pull/233

But then the functionality was removed (temporarily :-D) in https://github.com/pytorch/test-infra/pull/376 and was never re-enabled.

**Comment by kit1980** [comment]
Actually, looks like this PR was supposed to re-enable the functionality : https://github.com/pytorch/test-infra/pull/480
