### ISSUE TITLE
Inductor graph viz doesnt print to correct directory

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#100567]
## Repro

```python
import torch
import torch._inductor.config as iconfig
iconfig.trace.enabled = True
iconfig.trace.graph_diagram = True
torch.set_float32_matmul_precision('high')

class ToyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.l = torch.nn.Linear(100, 100)
        self.relu = torch.nn.ReLU()
    
    def forward(self, x):
        return self.relu(self.l(x))

m = ToyModel().to(device="cuda:0")

m = torch.compile(m)
input_tensor = torch.randn(100).to(device="cuda:0")
out = m(input_tensor)
```

Then `python graph.py` or `TORCH_COMPILE_DEBUG=1 graph.py`

## Logs

```
[2023-05-03 18:07:10,289] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 0
Writing FX graph to file: /home/ubuntu/test/torch_compile_debug/run_2023_05_03_18_07_08_335607-pid_50924/torchinductor/model__0_forward_13.0/graph_diagram.svg
[2023-05-03 18:07:10,522] torch._inductor.graph: [DEBUG] Output code written to: /tmp/torchinductor_ubuntu/sc/cscetc5qkf35jotys4kkq5qwlxueums3fwpqtkoza7qqtbf3wpxp.py
```

Problem is  the folder where SVG is supposedly at is empty 

```
(sourcetorch) ubuntu@ip-172-31-1-136:~/test/torch_compile_debug/run_2023_05_03_18_07_08_335607-pid_50924/torchinductor$ ls
aot_model___0_debug.log
```

But it is actually where the inductor code is generated

```
(sourcetorch) ubuntu@ip-172-31-1-136:/tmp/torchinductor_ubuntu/sc/cscetc5qkf35jotys4kkq5qwlxueums3fwpqtkoza7qqtbf3wpxp.debug$ ls
fx_graph_readable.py  fx_graph_runnable.py  fx_graph_transformed.py  graph_diagram.svg  ir_post_fusion.txt  ir_pre_fusion.txt  output_code.py
```

cc @ezyang @soumith @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by fishmingyu** [comment]
Same issue here, does anyone find a solution?

**Comment by mlazos** [comment]
I'll take a look

**Comment by mlazos** [comment]
@msaroufim I ran your repro and it works on main?

**Comment by peterbell10** [comment]
@mlazos the directory renaming happens here
https://github.com/pytorch/pytorch/blob/28720ad5858db4a84ea5478256a87d04e0252b50/torch/_inductor/graph.py#L900

However, it might silently fail to rename to files and so stay in the correct directory:
https://github.com/pytorch/pytorch/blob/28720ad5858db4a84ea5478256a87d04e0252b50/torch/_inductor/debug.py#L247-L252

e.g. on my machine it failed because `/tmp` is on a different device:
```
[Errno 18] Invalid cross-device link: '/home/pbell/torch_compile_debug/run_2023_06_30_18_26_25_699767-pid_737566/torchinductor/model__0_backward_28.1' -> '/tmp/torchinductor_pbell/dm/cdmdpoyrb3nsxbk4oee6llalq6ubnv5fplhkrjvcsubfegiwlaba.debug'
```

However, if I move my inductor cache directory into my home directory then I do see the renaming happen.
```
TORCHINDUCTOR_CACHE_DIR=$HOME/torchinductor_cache
```

**Comment by mlazos** [comment]
@peterbell10 thanks! make sure the correct directory is printed then

**Comment by mlazos** [comment]
@peterbell10 actually you're describing the inverse problem, for you the artifacts are in the debug dir, but don't appear in the source code dir unless you make it an accessible directory. 

Somehow @msaroufim is seeing the artifacts in the cache directory but not the original directory that they should've been written to.

**Comment by peterbell10** [comment]
@mlazos I'm giving a reason why the issue might not reproduce for you.

**Comment by mlazos** [comment]
> @mlazos I'm giving a reason why the issue might not reproduce for you. The `V.debug.rename` line is the one that moves the files, but if it silently fails then you won't observe the issue.

But mark's issue is different - the files are already in the cache directory but *not* the debug directory. The steps are 1) files get written to debug dir 2) files get copied with 'rename' to the cache dir. Somehow in mark's case 1 is getting skipped, while 2 is succeeding

**Comment by fishmingyu** [comment]
Interestingly, I've noticed the peculiar situation mentioned by @mlazos regarding Case 1 does occur. However, after the debugging process, the files are silently removed. Consequently, I've found that the debug file only exists in the /tmp directory. Do you know which part of the code could correspond to this phenomenon?

**Comment by fishmingyu** [comment]
![image](https://github.com/pytorch/pytorch/assets/46808682/2c55eb33-c919-4fe1-ad07-8bc9e60d16cd)

**Comment by fishmingyu** [comment]
The image provided above serves as evidence to aid your understanding of Case 1. However, these files vanish quickly once the debugging process terminates.

**Comment by peterbell10** [comment]
> But mark's issue is different - the files are already in the cache directory but not the debug directory. 

Yes, this is what you will see when the rename command succeeds.

> The steps are 1) files get written to debug dir 2) files get copied with 'rename' to the cache dir. Somehow in mark's case 1 is getting skipped, while 2 is succeeding

No, this is wrong. The files are 1) written to the debug directory then 2) _moved_ with 'rename' into the cache dir. The debug directory is now empty because the files have been moved elsewhere.

**Comment by peterbell10** [comment]
This also explains why @fishmingyu sees the files in the debug directory while debugging. Their break point must be before the rename command.

**Comment by mlazos** [comment]
Ah thanks I'm dumb, rename is ... renaming haha. Yeah I can change that to a copy then and print a message when it doesn't succeed.
