### ISSUE TITLE
Unknown exception in libtorch ge op

### ISSUE THREAD

**Issue by qqqhhh-any** [pytorch/pytorch#100524]
### 🐛 Describe the bug

I use libtorch to deploy yolov5-seg，in the part of postprocessing some code could not work and I could not get any exception msg.
here the code which oppose to crop the mask vectorized
```
        torch::Tensor downsampled_bboxes = box.clone();
        int iw = 640;
        int ih = 640;
        downsampled_bboxes.slice(1, 0) *= mw / (float)iw;
        downsampled_bboxes.slice(1, 2) *= mw / (float)iw;
        downsampled_bboxes.slice(1, 3) *= mh / (float)ih;
        downsampled_bboxes.slice(1, 1) *= mh / (float)ih;
        std::vector<torch::Tensor> x1_y1_x2_y2 = torch::chunk(downsampled_bboxes.unsqueeze(2), 4, 1);
        torch::Tensor r = torch::arange(mw).unsqueeze(0).unsqueeze(0);
        torch::Tensor c = torch::arange(mh).unsqueeze(0).unsqueeze(2);
        r = r.repeat({ x1_y1_x2_y2[0].size(0),1, 1 });
        c = c.repeat({ x1_y1_x2_y2[1].size(0),1,1 });
        masks = masks * ((r >= x1_y1_x2_y2[0]) * (r < x1_y1_x2_y2[2]) * (c >= x1_y1_x2_y2[1]) * (c < x1_y1_x2_y2[3]));
```
the code go down in the last line,I print the sizes of **r** and **x1_y1_x2_y2[0]**
```
r sizes: [92, 1, 160]
x1_y1_x2_y2[0] sizes:  [92, 1, 1]
```
It seems that libtorch could not broadcast the tensort to the same dim automatically，so I try the code like that
```
auto expanded = torch::broadcast_tensors({ x1_y1_x2_y2[0], r })[0];
auto s1 = r.ge(expanded);
```
now they are in the same sizes but it still not work,I could not catch any wrong msg too.
```
r sizes: [92, 1, 160]
expanded sizes: [92, 1, 160]
Unknown exception
```

### Versions

libtorch 2.0+cu117
Visual studio 2019
Windows10,i7-12700H,RTX3060 Laptop

Collecting environment information...
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
Clang version: Could not collect
CMake version: version 3.24.0
Libc version: N/A

Python version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 531.61
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:

Revision=

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-lightning==1.6.5
[pip3] torch==1.12.0+cu116
[pip3] torchaudio==0.12.0+cu116
[pip3] torchfile==0.1.0
[pip3] torchmetrics==0.9.3
[pip3] torchtext==0.13.0
[pip3] torchvision==0.13.0+cu116
[conda] blas                      1.0                         mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] cudatoolkit               11.3.1               h59b6b97_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2021.4.0           haa95532_640    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.4.0            py39h2bbff1b_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.3.1            py39h277e83a_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.2.2            py39hf11a4ad_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] numpy-base                1.22.3           py39hca35cd5_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch-lightning         1.6.5                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torch                     1.12.0+cu116             pypi_0    pypi
[conda] torchaudio                0.12.0+cu116             pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchmetrics              0.9.3                    pypi_0    pypi
[conda] torchtext                 0.13.0                   pypi_0    pypi
[conda] torchvision               0.13.0+cu116             pypi_0    pypi

cc @jbschlosser

**Comment by janeyx99** [comment]
Hi! Have you confirmed that it is the `(r >= x1_y1_x2_y2[0])` portion of that line causing the unknown exception and not the rest of the line? I would recommend chunking the computations into different lines to seeing where it may be causing the exception if you haven't isolated the problem already.

I do agree that "Unknown Exception" is not a useful error message and it would be helpful to know exactly what triggers the error.

**Comment by qqqhhh-any** [comment]
I am sorry that I used ```try{...}catch(std::exception e){...}``` to catch the exception,when I try ```catch(c10::Error e){...}```,I got useful error message,thank you!ps: It seems that libtorch exception not implemented from std::exception
