### ISSUE TITLE
DISABLED test_scalar_cuda (__main__.TestContentStoreCUDA)

### ISSUE THREAD

**Issue by jataylo** [pytorch/pytorch#100539]
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_content_store.py%3A%3ATestContentStoreCUDA%3A%3Atest_scalar_cuda)).

Most likely introduced by https://github.com/pytorch/pytorch/pull/100467 (https://github.com/pytorch/pytorch/commit/409fc7a4c72f353b6c907a944d9a763e4bc8906)

cc: @jithunnair-amd @dllehr-amd 

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by janeyx99** [comment]
Is ROCm going to take a look at this? Or are you suggesting @ezyang (author of the suspected PR) to take a look?

**Comment by janeyx99** [comment]
Okay, that sounds good to me
