### ISSUE TITLE
RuntimeError when using autocast with CPU device and float32 dtype, works correctly on CUDA device

### ISSUE THREAD

**Issue by PershingSquare** [pytorch/pytorch#100565]
## Describe the bug

When using the `torch.autocast()` context manager with a CPU device and `float32` dtype, the following code throws a `RuntimeError: "Currently, AutocastCPU only support Bfloat16 as the autocast_cpu_dtype"`

The following code runs successfully
```
with torch.autocast(device_type='cuda', dtype=torch.float32):
  print(torch.ones(10))
```

However, when this code is run
```
with torch.autocast(device_type='cpu', dtype=torch.float32):
  print(torch.ones(10))
```
the following error is encountered.

```
/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py:216: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
CPU Autocast only supports dtype of torch.bfloat16 currently.
  warnings.warn(error_message)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-3-d2a33234ab60>](https://localhost:8080/#) in <cell line: 1>()
----> 1 with torch.autocast(device_type='cpu', dtype=torch.float32):
      2   print(torch.ones(10))

[/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py](https://localhost:8080/#) in __enter__(self)
    245             self.prev_fastdtype = torch.get_autocast_cpu_dtype()
    246             torch.set_autocast_cpu_enabled(self._enabled)
--> 247             torch.set_autocast_cpu_dtype(self.fast_dtype)  # type: ignore[arg-type]
    248             torch.autocast_increment_nesting()
    249         elif self.device == 'xpu':

RuntimeError: Currently, AutocastCPU only support Bfloat16 as the autocast_cpu_dtype
```

## Expected Behavior

Autocast should just be turned off but not throw any errors.

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0+cu118
PyTorch CXX11 ABI: No
IPEX version: N/A
IPEX commit: N/A
Build type: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
IGC version: N/A
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.147+-x86_64-with-glibc2.31
Is XPU available: N/A
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration: 
N/A
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) CPU @ 2.00GHz
Stepping:                        3
CPU MHz:                         2000.176
BogoMIPS:                        4000.35
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        1 MiB
L3 cache:                        38.5 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.1+cu118
[pip3] torchdata==0.6.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.1
[pip3] torchvision==0.15.1+cu118
[conda] N/A
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel

**Comment by jbschlosser** [comment]
Hey @PershingSquare, this looks like the correct and expected behavior to me. Something unsupported is being explicitly asked for, and I think it would be unexpected to silently auto-disable autocast in this case. I will leave it to the experts in this area to decide how to move forward.

**Comment by PershingSquare** [comment]
Thank you for your response. I understand that the warning is helpful in situations where the dtype is not supported by the CPU autocast.

However, I would like to highlight that the behavior between CPUs and GPUs is not consistent. In GPUs, when autocast is disabled, no errors or warnings are given. In CPUs, autocast errors out, even when it is disabled.

This inconsistency can make it more difficult to write portable code that works across different devices. It would be helpful if the behavior could be made consistent between CPUs and GPUs, or if there could be a way to disable autocast without triggering an error.

https://github.com/pytorch/pytorch/blob/main/torch/amp/autocast_mode.py#L258

**Comment by leslie-fang-intel** [comment]
Hi @PershingSquare, I think the suggested way to write autocast disabled context should be 
```
with torch.autocast(device_type='cuda', enabled=False):
  print(torch.ones(10))
```
Does it sound good to you for writing portable code that works across different devices?

**Comment by Grzego** [comment]
Hi, is there a reason why this code fails:
```python
with amp.autocast("cpu", dtype=torch.float32, enabled=False):
    x = torch.zeros(10)
```
with following error:
```bash
RuntimeError: Currently, AutocastCPU only support Bfloat16 as the autocast_cpu_dtype
```
even when autocast is explicitly disabled? Is there some behavior `autocast` context turns on even when it should be disabled?

**Comment by jgong5** [comment]
> even when autocast is explicitly disabled? Is there some behavior `autocast` context turns on even when it should be disabled?

Passing `torch.float32` to `dtype` is not supported. If you want to disable autocast, simply passing `False` to `enabled`.

**Comment by Grzego** [comment]
@jgong5 I mean it is disabled (you can see `enabled=False` in the code) and it still raises an exception when `dtype` is not supported which I thing is strange. It's inconvenient that to disable autocast you need to pass both `dtype=None`(*) and `enabled=False`, because in case of unsupported type it will raise exception no matter if enabled or not.

(*) I know that `dtype=None` is the default, but in my case I usually pass `dtype` to my experiments via command line argument and this means I have to handle this quirky behavior explicitly.

**Comment by jgong5** [comment]
> (*) I know that `dtype=None` is the default, but in my case I usually pass `dtype` to my experiments via command line argument and this means I have to handle this quirky behavior explicitly.

Maybe we can revise things to ignore `dtype` when `enabled=False`. Thoughts? @leslie-fang-intel

**Comment by leslie-fang-intel** [comment]
Yean, I think it makes sense. Fix it in https://github.com/pytorch/pytorch/pull/107280.

**Comment by leslie-fang-intel** [comment]
Hi @PershingSquare, I think https://github.com/pytorch/pytorch/pull/107348 landed to fix this issue. I am going to close it. Feel free to reopen it if any other issues. Thanks.
