### ISSUE TITLE
Add tools to torchgen

### ISSUE THREAD

**Issue by huihoaan** [pytorch/pytorch#100684]
### 🚀 The feature, motivation and pitch

I have some custom operators, and I've already generated the Dispatcher-related code with torchgen. But I want these operators can be called in python.
So I want to put the files  `tool/*` that generates the python binding into torchgen. Or is there any other way to do it?

cc @ezyang @bhosmer @bdhirsh

**Comment by ezyang** [comment]
This will be a fairly annoying refactor as many build systems hard code paths to tools/. Maybe you can figure out how to do the refactor so that the library code lives in torchgen, but the stubs stay in tools.
