### ISSUE TITLE
Compile torch2.0 from source

### ISSUE THREAD

**Issue by yingtongxiong** [pytorch/pytorch#100618]
### 🐛 Describe the bug

Hello, I want to compile torch2.0 from source. And I followed the readme in https://github.com/pytorch/pytorch/blob/main/README.md. However, when I compiled it, I met some problems.

The following is the bug information.
/pytorch/c10/cuda/CUDACachingAllocator.cpp:1152:15: error: ‘nvmlProcessInfo_v1_t’ was not declared in this scope; did you mean ‘nvmlProcessInfo_t’?
 1152 |   std::vector<nvmlProcessInfo_v1_t> procs(8);
      |               ^~~~~~~~~~~~~~~~~~~~
      |               nvmlProcessInfo_t
/pytorch/c10/cuda/CUDACachingAllocator.cpp:1152:35: error: template argument 1 is invalid
 1152 |   std::vector<nvmlProcessInfo_v1_t> procs(8);
      |                                   ^
/pytorch/c10/cuda/CUDACachingAllocator.cpp:1152:35: error: template argument 2 is invalid
/pytorch/c10/cuda/CUDACachingAllocator.cpp:1153:29: error: request for member ‘size’ in ‘procs’, which is of non-class type ‘int’
 1153 |   unsigned int size = procs.size();
      |                             ^~~~
/pytorch/c10/cuda/CUDACachingAllocator.cpp:1156:41: error: request for member ‘data’ in ‘procs’, which is of non-class type ‘int’
 1156 |               nvml_device, &size, procs.data())) ==
      |                                         ^~~~
/pytorch/c10/cuda/CUDACachingAllocator.cpp:1158:11: error: request for member ‘resize’ in ‘procs’, which is of non-class type ‘int’
 1158 |     procs.resize(size);
      |           ^~~~~~
/pytorch/c10/cuda/CUDACachingAllocator.cpp:1165:23: error: invalid types ‘int[unsigned int]’ for array subscript

How can I solve this? Anybody can provide some suggestions?

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 10.1.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.17

Python version: 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: 11.2.67
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                96
On-line CPU(s) list:   0-95
Thread(s) per core:    2
Core(s) per socket:    24
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
Stepping:              7
CPU MHz:               3000.000
BogoMIPS:              6000.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0-23,48-71
NUMA node1 CPU(s):     24-47,72-95
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni spec_ctrl intel_stibp flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+7d1a95b046
[conda] magma-cuda112             2.5.2                         1    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-include               2023.1.0         h06a4308_46342  
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+7d1a95b046          pypi_0    pypi

**Comment by shivamkc01** [comment]
This issue is related to Torch2.0 and the NVIDIA Management Library (NVML) version incompatibility. This issue occurs because of the use of the 'nvmlProcessInfo_v1_t' type that was introduced in the newer version of NVML, which is not compatible with the version of NVML that Torch2.0 is using.

To resolve this issue, you can follow these steps:

- Upgrade the NVIDIA Management Library (NVML) to the latest version.
- Update the Torch2.0 source code to use the latest NVML API by replacing 'nvmlProcessInfo_v1_t' with 'nvmlProcessInfo_t' in the affected source file.
- Re-compile Torch2.0 from the source after the above steps.

To upgrade the NVML library, you can download the latest NVML version from NVIDIA's website and install it on your system. After installing the latest NVML library, you need to update the Torch2.0 source code by replacing 'nvmlProcessInfo_v1_t' with 'nvmlProcessInfo_t' in the file 'CUDACachingAllocator.cpp'. After updating the file, you can recompile Torch2.0 from the source.

**Comment by yingtongxiong** [comment]
Okay, thank you very much.

**Comment by rmast** [comment]
According to https://developer.nvidia.com/nvidia-management-library-nvml there recently has not been released a new version. Cuda 5.5 has been deprecated quite some years ago (even before compute capability 1.1, and compute capability 3.0 is soon out of support?) and I'm building with Cuda 11.2. I just changed the variable name as suggested and it continues to compile.

**Comment by rmast** [comment]
"The NVIDIA Management Library can be downloaded as part of the [GPU Deployment Kit](https://developer.nvidia.com/tesla-deployment-kit)." 

"The GPU Deployment Kit is part of the [CUDA Toolkit](https://developer.nvidia.com/cuda-downloads), in versions 8 and later, and is no longer available as a separate download."

**Comment by rmast** [comment]
The apparently succesful builds with that commit were with Cuda 11.7 and Cuda 11.8:
https://github.com/pytorch/pytorch/commit/8548cb3dd5b907e9f0b63ed42260929bd3ea1364
For a K80 there is a special Linux-install to make it Cuda 11.8 compatible, but as the K80's will be phased out August '31 at Azure I wonder whether anyone would invest in getting it to work that way. K80's support up to Cuda 11.2 (driver 460) on Ubuntu 20 and Cuda 11.4 (driver 470) on Ubuntu 18, which Ubuntu version is already out of support.

**Comment by rmast** [comment]
On this page https://raw.githubusercontent.com/NVIDIA/nvidia-settings/master/src/nvml.h
there is some relation with 
#ifdef NVML_NO_UNVERSIONED_FUNC_DEFS

**Comment by rmast** [comment]
|nvmlProcessInfo_v1_t is introduced in Cuda Toolkit 470.42.01:
https://github.com/NVIDIA/nvidia-settings/blame/main/src/nvml.h
Good argument to look for a Cuda toolkit 470 with cuda 11.4.

**Comment by rmast** [comment]
There is a 470 driver for Ubuntu 20.04:
https://www.nvidia.com/download/driverResults.aspx/182614/en-us/
I'll try it...
