### ISSUE TITLE
_functorch/deprecated.py makes use of __doc__

### ISSUE THREAD

**Issue by ameentj** [pytorch/pytorch#100680]
### 🐛 Describe the bug

I'm using torch.compile in my code, which in turn imports functorch, which has the following code:

  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/deprecated.py", line 49, in setup_docs

    functorch_api.__doc__ = torch_func_api.__doc__ + warning_note

I'm running performance sensitive code so I'm running with ENV PYTHONOPTIMIZE=2 which disables all __doc__ effectively setting them to None.

This causes the following error and crashes:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

You should identify that PYTHONOPTIMIZE or the OO flag is set and behave differently in the functorch deprecation warning module. Perhaps disabling it?
     

### Versions

torch 2.0.0

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by malfet** [comment]
Fix is straightforward, just guard setup_docs with `sys.flags.optimize < 2`, PR is coming...
