### ISSUE TITLE
Does this mean onnx do not support spatialBN operator?

### ISSUE THREAD

**Issue by veepersgit** [pytorch/pytorch#10062]
I am using pytorch to train a shuffleNet model which uses spatialBN operator. And I'm trying this way: Pytorch model->onnx model->caffe2 model. It works smoothly. But when I try to do the inference using the well-transfered caffe2 model. It comes this:

Unexpected Error: [enforce fail at spatial_batch_norm_op.cc:11] X.ndim() >= 3 && X.ndim() <= 5.  Error from operator: 
input: "1967" input: "1103" input: "1104" input: "1105" input: "1106" output: "1968" name: "" type: "SpatialBN" arg { name: "is_test" i: 1 } arg { name: "epsilon" f: 0.001 } arg { name: "momentum" f: 0.9 } device_option { device_type: 0 cuda_gpu_id: 0 }

Does this mean onnx do not support spatialBN operator? 

cc @BowenBao @neginraoof

**Comment by soumith** [comment]
cc: @houseroad @bddppq

**Comment by houseroad** [comment]
`SpatialBN` is caffe2 op, which is the implementation of BatchNormalization in Caffe2. According to your error message, it seems the input `X`'s dimension is >5 or <3, which is not supported by the implementation in SpatialBN. You can compare your shufflenet with the one in our model zoo: https://github.com/onnx/models/tree/master/shufflenet

**Comment by YueshangGu** [comment]
Hi, I got the same question when convert onnx to caff2, error like this

[E operator_schema.cc:82] Argument 'is_test' is required for Operator 'SpatialBN'.
RuntimeError: [enforce fail at operator.cc:138] schema->Verify(operator_def). Operator def did not pass schema checking: input: "339" input: "2" input: "3" input: "4" input: "5" output: "340" name: "" type: "SpatialBN" arg { name: "epsilon" f: 1e-05 } arg { name: "momentum" f: 1 } device_option { device_type: 0 cuda_gpu_id: 0 }

have you solved this question? what should I do?
@veepersgit

**Comment by AndTseren** [comment]
@YueshangGu, 
in network forward you should add these few rows above problem BN layer:
sz = x.size()
x = x.view(sz[0], sz[1], -1)
and one row after BN layer:
x = x.view(sz[0], sz[1])

**Comment by ranka47** [comment]
@AndTseren I can't edit the source code so I won't be able to make the changes you suggested.

Issue: I created an ONNX model from version 1.8.0 and opset version 8. Then I converted the model to caffe2 using the CLI and got two `.pb` files. When I try to load them using `Predictor` as tested by @veepersgit I receive the same issue,

```
[W init.h:137] Caffe2 GlobalInit should be run before any other API calls.
[W init.h:137] Caffe2 GlobalInit should be run before any other API calls.
[W predictor_config.cc:90] Caffe2 is compiled without optimization passes.
[E operator_schema.cc:101] Argument 'is_test' is required for Operator 'SpatialBN'.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/caffe2/python/workspace.py", line 187, in Predictor
    return C.Predictor(StringifyProto(init_net), StringifyProto(predict_net))
RuntimeError: [enforce fail at operator.cc:199] schema->Verify(operator_def). Operator def did not pass schema checking: input: "conv1/Relu:0" input: "batchNorm1/gamma/read/_1__cf__1:0" input: "batchNorm1/beta/read/_0__cf__0:0" input: "batchNorm2/moving_mean/read/_6__cf__6:0" input: "batchNorm1/moving_variance/read/_3__cf__3:0" output: "batchNorm1/FusedBatchNorm:0" name: "batchNorm1/FusedBatchNorm" type: "SpatialBN" arg { name: "epsilon" f: 0.001 } device_option { device_type: 0 device_id: 0 
```

When I looked the code of creating BatchNormalization [here](https://github.com/pytorch/pytorch/blob/f326045b3757236aabe367dfca1894be14ce31ef/caffe2/onnx/backend.cc#L1227), it adds the attribute of `is_test` if the opset version >= 7. However, it isn't happening in my case. Is there any way to debug the opset version or any solution for this issue?

**Comment by ranka47** [comment]
The issue is resolved for me. I was using the command-line utility suggested on the [README](https://github.com/pytorch/pytorch/tree/master/caffe2/python/onnx). However, it points to their tutorial in deprecated version of the [code](https://github.com/onnx/tutorials/blob/master/tutorials/OnnxCaffe2Import.ipynb).

The command-line utility (installed using the pip install onnx-caffe2) still has the [`_known_opset_version = 3`](https://github.com/onnx/onnx-caffe2/blob/e0cb48bc2d40b4e8c700e5a8c866d4ffd327457c/onnx_caffe2/backend.py#L121). This was causing the error. After I used the conversion utility through Python APIs in PyTorch library by importing,
```
from caffe2.python.onnx.backend import Caffe2Backend as c2
```
I was successfully able to run inference on the converted model.

**Comment by garymm** [comment]
Seems this issue is with the caffe2 runtime, not with the torch.onnx module, so removing `module: onnx` label.
