### ISSUE TITLE
will pytorch2.0 update it's rocm version? 

### ISSUE THREAD

**Issue by PennyFranklin** [pytorch/pytorch#100625]
amd update the rocm to version 5.5.0, and it may add the 7900xtx support. i wonder if the pytorch will update it's version so I can run sdwebui without docker 

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by iDeNoh** [comment]
It's not just rdna3 support, from what I've read it should also see SDP support, so we can also benefit from the memory saving benefits of that.

**Comment by PennyFranklin** [comment]
that sounds pretty good, and I hope it will be published soon

**Comment by jithunnair-amd** [comment]
Sorry to disappoint, but you won't be seeing any pytorch 2.0 wheels on pytorch.org with rocm5.5.

**Comment by sunway513** [comment]
But we can work on the nightly WHL with ROCm5.5 :-)

**Comment by PennyFranklin** [comment]
can you please tell me where to download the nightly version?

**Comment by PennyFranklin** [comment]
thanks a lot,I'm very glad to hear that. After half a year, I can't wait to use my GPU to run sdwebui.

**Comment by iDeNoh** [comment]
Excellent! Glad to hear it!

**Comment by PennyFranklin** [comment]
well, the pytorch 2.0.1 released, but not support rocm 5.5.0

**Comment by sunway513** [comment]
> well, the pytorch 2.0.1 released, but not support rocm 5.5.0

The ROCm version upgrade should always happen with the nightly WHL first, before it can be used for release/point-release. We're working on the ROCm5.5 upgrade for the nightly, please stay tuned.

**Comment by PennyFranklin** [comment]
thanks. I've seen the pytorch nightly version in the rocm  docker webpage, but I didn't learn how to use the docker, so I can only wait for now :)

**Comment by iDeNoh** [comment]
> > well, the pytorch 2.0.1 released, but not support rocm 5.5.0
> 
> The ROCm version upgrade should always happen with the nightly WHL first, before it can be used for release/point-release. We're working on the ROCm5.5 upgrade for the nightly, please stay tuned.

A chance for a general eta on that? I'm trying to decide if I want to go through the process of trying to build from source on my own if it's going to be a few weeks or if I should be patient lol.

Also, is there any truth to the rumor that we'll be seeing improvements to memory utilization sue to SDP memory attention with 2.0 and 5.5?

**Comment by sunway513** [comment]
It usually takes a month of time for nightly whl upgrade with newer ROCm. @jithunnair-amd  can comment further.

**Comment by PennyFranklin** [comment]
Very glad to hear. After resolving the issue with whether my 7900xtx graphics card can run stable diffusion program, the next step is to further improve efficiency. Personally, I feel that the potential of RDNA3 architecture graphics cards is great.

**Comment by iDeNoh** [comment]
> PR to upgrade to ROCm5.5 nightly wheels is up! #102242

I'm personally ecstatic to hear that we're getting close. Any idea when we can reasonably expect this to hit nightlies near us?

**Comment by timingobituary** [comment]
Pytorch 2.1.0 ROCm5.5 nightly is up! Sadly with my RX 7900 XTX I get segmentation fault (core dumped) errors if I try to use torch
https://download.pytorch.org/whl/nightly/torch/

**Comment by jithunnair-amd** [comment]
> Pytorch 2.1.0 ROCm5.5 nightly is up! Sadly with my RX 7900 XTX I get segmentation fault (core dumped) errors if I try to use torch https://download.pytorch.org/whl/nightly/torch/

Is that simply when importing torch, or when running a workload?

**Comment by jithunnair-amd** [comment]
Here's how you can install PyTorch nightly wheels for ROCm5.5:
`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.5`

**Comment by timingobituary** [comment]
> > Pytorch 2.1.0 ROCm5.5 nightly is up! Sadly with my RX 7900 XTX I get segmentation fault (core dumped) errors if I try to use torch https://download.pytorch.org/whl/nightly/torch/
> 
> Is that simply when importing torch, or when running a workload?

Import torch works fine
This is essentially what I see when I try to use torch:
\>>> import torch
\>>> print(torch.\_\_version\_\_)
2.1.0.dev20230614+rocm5.5
\>>> torch.cuda.is_available()
True
\>>> torch.cuda.get_device_name(torch.cuda.current_device())
'Radeon RX 7900 XTX'
\>>> torch.randn(10).to(torch.cuda.current_device())
Segmentation fault (core dumped)

However torch.tensor([5, 5, 5] device=torch.cuda.current_device()) doesn't cause a segmentation fault so maybe I'm doing something wrong.

**Comment by jeffdaily** [comment]
We weren't able to reproduce your issue on our own dev systems, so we're thinking it might be a difference in our setups.

Did you install ROCm using these steps? 

https://rocmdocs.amd.com/en/develop/deploy/linux/quick_start.html

**Comment by timingobituary** [comment]
Thank you for taking the time to help diagnose the issue!

I originally used the AMDGPU install script where I had the issue described before.
So I thought that maybe my install was not correct, I completely uninstalled ROCm again using [https://rocmdocs.amd.com/en/develop/deploy/linux/installer/uninstall.html](url).

I then tried installing it again using the quick start you mentioned but in the end I got the same issue: torch.randn function causes a segmentation fault.

I tried reinstalling it again and after checking the logs a bit more carefully I found 1 error.
![image](https://github.com/pytorch/pytorch/assets/111178966/ddd141a1-982e-4108-85a8-b257a360493a)

I'm installing amdgpu-dkms while I have a different kernel version (6.3.7 vs 6.0.5), could this be the cause of the issue?
I'm also using Fedora 38, so that might also be part of it

**Comment by PennyFranklin** [comment]
well... Im managed to export PATH and successfully installed torch,even open sd-webui smoothly,but ran into the error while gengrate the first picture ,call MiOpen error:(
![截图 2023-06-17 11-08-48](https://github.com/pytorch/pytorch/assets/104998459/df0c29a4-9fec-437e-a86d-c53828d95b4d)

**Comment by jithunnair-amd** [comment]
> well... Im managed to export PATH and successfully installed torch,even open sd-webui smoothly,but ran into the error while gengrate the first picture ,call MiOpen error:( ![截图 2023-06-17 11-08-48](https://user-images.githubusercontent.com/104998459/246583125-df0c29a4-9fec-437e-a86d-c53828d95b4d.png)

That error indicates you need to have the c++ headers installed. Try something like: `sudo apt install libstdc++-12-dev`

**Comment by PennyFranklin** [comment]
thanks! i successfully generate the picture, 512x512, 16it/s.

**Comment by sunway513** [comment]
@PennyFranklin thanks for the update! We're excited to see you were able to get the SD workload running on Navi31 GPUs using the ROCm5.5 based PyTorch nightly whl :-) 
Please let us know if you have additional questions, thanks! 
Kudos to @jithunnair-amd @jeffdaily and @BLOrange-AMD who made the preview support possible :-)

**Comment by VasyaYovbak** [comment]
> @PennyFranklin thanks for the update! We're excited to see you were able to get the SD workload running on Navi31 GPUs using the ROCm5.5 based PyTorch nightly whl :-) Please let us know if you have additional questions, thanks! Kudos to @jithunnair-amd @jeffdaily and @BLOrange-AMD who made the preview support possible :-)

https://docs.amd.com/en/latest/release/windows_support.html#supported-skus
Finally, it happened))) AMD added Rocm support for Windows. We are waiting for an update from PyTorch )

**Comment by hqnicolas** [comment]
You could also try this:
https://gist.github.com/hqnicolas/6d9bfa997667626742c0918b95e67171
