### ISSUE TITLE
ONNX Opset 16 GridSample Does Not Support 5D Volumetric Input Tensor

### ISSUE THREAD

**Issue by yang-Michael** [pytorch/pytorch#100790]
### 🚀 The feature, motivation and pitch

[#92209](https://github.com/pytorch/pytorch/issues/92209)

I need to use the gridsample operator in my code. I can use onnx in Pytorch1.12.0 to do this successfully, but there are errors in infer, because 5D input is not supported, so I checked the update log for Pytorch 2.0, found that as of now, the latest pytorch onnx does not support 5D input, so please ask:

When Will ONNX's GridSample support for 5D volumetric input be implemented?

**Comment by simangels** [comment]
any update on this ?????

**Comment by htwin** [comment]
any update on this ????? I also encountered this problem

**Comment by aviziskind** [comment]
I also encountered this issue recently when exporting an ONNX model with a 3D spatial transformer layer (which uses volumetric grid-sampling). Any update on when this feature will be added?

**Comment by htwin** [comment]
any update on this ?????

**Comment by htwin** [comment]
> I also encountered this issue recently when exporting an ONNX model with a 3D spatial transformer layer (which uses volumetric grid-sampling). Any update on when this feature will be added?

Do you have any other methods to solve this problem?

**Comment by aviziskind** [comment]
No, I have not yet found a solution to this problem. I am hoping this feature will be added soon to PyTorch.

**Comment by Luckygyana** [comment]
@aviziskind , @htwin Did you guys get any solution for the above?

**Comment by col-in-coding** [comment]
any update on this ?????

**Comment by thiagocrepaldi** [comment]
@liqunfu FYI

**Comment by leimao** [comment]
This is a good starting point:
https://github.com/pytorch/pytorch/pull/92212

**Comment by daikankan** [comment]
any update?

I use pytorch_1.13.1,
convert pytorch model to onnx use torch.onnx.export(opset_version=16),
then convert onnx model to tensorrt-8.6.1.6, and get error:

Error[3]: [network.cpp::addGridSample::1537] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/network.cpp::addGridSample::1537, condition: input.getDimensions().nbDims == 4

**Comment by saikiran321** [comment]
Using pull request of @liqunfu, I have built pytorch from source. using this torch i was able to successfully convert my mode to onnx.

Test the onnx_opset 20 using the torch from this docker image. _**[docker.io/saikiran321/pytorch_opset_20](docker.io/saikiran321/pytorch_opset_20)**_

**Comment by SergeySandler** [comment]
@saikiran321, is the above link correct? I am getting the page not found error.

**Comment by saikiran321** [comment]
I have updated it, pls check

**Comment by SergeySandler** [comment]
@saikiran321, _torch.onnx.export_ does not  fail with OnnxExporterError: Unsupported with _saikiran321/pytorch_opset_20_. 
Unfortunately it now fails with _ValueError: only one element tensors can be converted to Python scalars, after producing_ after producing _UserWarning: ONNX export mode is set to TrainingMode.EVAL, but operator 'instance_norm' is set to train=True. Exporting with train=True_.
Do you think this error could be specific to the build provided? I will add more details in https://github.com/google-deepmind/tapnet/issues/79.

**Comment by SergeySandler** [comment]
@saikiran321, just curious about _saikiran321/pytorch_opset_20_ image. While _nvidia-smi_ reports _CUDA Version: 12.4_, 
`python3 -c "import torch; print(torch.cuda.is_available())"`
 prints _False_. Is this intentional?

**Comment by saikiran321** [comment]
Hi @SergeySandler, I have compiled the pytorch with cpu only, you can compile from scratch for gpu. I have compile only for testing a project i'm working

fetch code from this  [pull request](https://github.com/pytorch/pytorch/pull/118828).

**Comment by titaiwangms** [comment]
@liqunfu Could you confirm whether this is solved?

**Comment by dat-nguyenvn** [comment]
any update ?

**Comment by liqunfu** [comment]
> @liqunfu Could you confirm whether this is solved?

Yes torchscript onnx export now support GirdSample in 5D.
https://github.com/pytorch/pytorch/blob/17186bd5b657c4d415aa8749fc0d268b75928f93/torch/onnx/symbolic_opset20.py#L49
