### ISSUE TITLE
torch.nn.MultiheadAttention : key_padding_mask and is_causal breaks

### ISSUE THREAD

**Issue by pfeatherstone** [pytorch/pytorch#100709]
### 🐛 Describe the bug

When using `nn.MultiheadAttention()` with `key_padding_mask` and `is_causal=True`, I get the error:
```
Explicit attn_mask should not be set when is_causal=True
```
Though the docs say that you can't mix `attn_mask` and `is_causal=True`, there is nothing that says you can't mix `key_padding_mask` and `is_causal=True`.

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.26.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 745

Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.8.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
CPU family:                      6
Model:                           158
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        10
CPU max MHz:                     4700.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7399.70
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        1.5 MiB (6 instances)
L3 cache:                        12 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.1
[pip3] torch==2.0.0
[pip3] torch-stoi==0.1.2
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.0
[pip3] torchmetrics==0.11.4
[pip3] torchtext==0.15.1
[pip3] torchtyping==0.1.4
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] Could not collect

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @albanD @mruberry @walterddr @mikaylagawarecki

**Comment by pfeatherstone** [comment]
It would be really cool if this worked. Right now my machine instantly runs out of memory because i'm having to manually build by attention mask.

**Comment by pfeatherstone** [comment]
Did you mean nightly build ?

**Comment by mikekgfb** [comment]
I referred to PyTorch 2.0.1, a bug fix release that was just published.  (Alternatively, nightlies would also contain the fix in question.)

**Comment by pfeatherstone** [comment]
i've updated. Now i get the error:
```
Need attn_mask if specifying the is_causal hint. You may use the Transformer module method `generate_square_subsequent_mask` to create this mask.
```

**Comment by pfeatherstone** [comment]
Creating that `attn_mask` makes my machine run out of memory immediately. It would be great if I could just specify `is_causal=True` and `key_padding_mask`, then under the hood, ideally somewhere deep in C++ or CUDA, it would create a triangular mask as and when it needed while using the absolute minimum amount of memory. I'm sure there is a BLAS function for multiplying with a lower/upper triangular matrix...

**Comment by pfeatherstone** [comment]
It looks like using `torch.nn.functional.scaled_dot_product_attention` wouldn't help either since you have to either specify `attn_mask` or `is_causal`. So to replicate `key_padding_mask`, I would have to create `attn_mask`, which again would make my machine run out of memory.

**Comment by pfeatherstone** [comment]
I think in general we are still a few years away from making transformers a practical model that runs on normal GPUs. Whether it means implementations become more efficient or "normal" GPUs become beefier I don't know. But I can't use transformers without first downsampling my data heavily, then upsampling it at the end.

**Comment by mikekgfb** [comment]
Thanks for confirming that the interface works correctly in 2.0.1! 

Demand for device memory is an unfortunate fact of life, and we have all seen the dreaded OOM .  That being said Transformers are practical and used in many applications like LLMs and LDMs today, and our implementations have been leading the charge in reducing memory consumption, e.g., allowing us to double the batch size on training nanoGPT => https://pytorch.org/blog/accelerating-large-language-models/ - one answer to the problem you are encountering may be to reduce the batch size.

For inference applications, I encourage you to explore the use of Nested Tensors to represent per-example padding.  For training, which has allowed us to see large gains in efficiency.

**Comment by pfeatherstone** [comment]
It would still be great if `torch.nn.functional.scaled_dot_product_attention()` supported setting both `attn_mask` and `is_causal=True`. In which case it ignores the upper triangular part of `attn_mask` and implicitly assumes it's either set to False or -inf. This would allow us to do some sort of relative positional encoding and causal masking at the same time while saving compute and memory.

**Comment by cpuhrsch** [comment]
@pfeatherstone - Could I kindly ask you to open a separate feature request for that change to `scaled_dot_product_attention`? It sounds like a useful combination. We might also be able to address this with sparse formatted attention masks or other specialized mask formats.

**Comment by pfeatherstone** [comment]
#101531

**Comment by peterdonnelly1** [comment]
> It looks like using `torch.nn.functional.scaled_dot_product_attention` wouldn't help either since you have to either specify `attn_mask` or `is_causal`. So to replicate `key_padding_mask`, I would have to create `attn_mask`, which again would make my machine run out of memory.

Don't take this as gospel, but it seems that you can use both together of the token dimensions are a perfect square, (or maybe just THESE perfecrt squares (64, 128, 256, 512)) but not other wise.  

Seems weird to me also that you can't mix and match 'is_causal' with the 'attn_mask'.
