### ISSUE TITLE
parameter prefetch_factor in DataLoader class

### ISSUE THREAD

**Issue by abcsimple** [pytorch/pytorch#100703]
### 📚 The doc issue

In torch 1.9.0, the defination of _prefetch_factor_  in class _DataLoader_ is: Number of **samples** loaded in advance by each worker... However in the latest version(2.0), the defination is Number of **batches** loaded in advance by each worker. If prefetch_factor=2, can I say that in version 1.9.0, 2 * num_worker samples are prefetched but 2 * num_worker * batch_size samples are prefetched in torch 2.0?

cc @svekars @carljparker @SsnL @VitalyFedyunin @ejguan @NivekT @dzhulgakov

**Comment by ejguan** [comment]
@abcsimple 

The behavior of `DataLoader`'s prefetch is always getting `2 * num_worker * batch_size`. We landed a PR to correct the docstring. Thanks.
