### ISSUE TITLE
Nightly torch.compile fails with dynamically patched `nn.module.forward`

### ISSUE THREAD

**Issue by haijieg** [pytorch/pytorch#100733]
### 🐛 Describe the bug

When an `nn.Module` forward is modified during runtime, `torch.compile` fails.

```
import torch
import torch.nn as nn
import functools

model = nn.Linear(5, 5)
old_forward = model.forward


@functools.wraps(old_forward)
def new_forward(*args, **kwargs):
    return old_forward(*args, **kwargs)


model.forward = new_forward
model = torch.compile(model, backend='eager')
model(torch.randn(1, 5))
```

Output
```
Traceback (most recent call last):
  File "/home/jgu/Projects/dynamite/env/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1228, in get_fake_value
    return wrap_fake_exception(
  File "/home/jgu/Projects/dynamite/env/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 848, in wrap_fake_exception
    return fn()
  File "/home/jgu/Projects/dynamite/env/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1229, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/jgu/Projects/dynamite/env/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1292, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_method forward(*(Linear(in_features=5, out_features=5, bias=True), FakeTensor(..., size=(1, 5))), **{}):
Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.t.default(*(Parameter containing:
tensor([[ 0.1118,  0.2579,  0.2571, -0.2395,  0.2391],
        [-0.3907, -0.2695,  0.2111, -0.4282, -0.2784],
        [ 0.1674,  0.3213, -0.1111,  0.2801,  0.3222],
        [-0.0022,  0.2045, -0.2440,  0.2014, -0.3790],
        [ 0.4095, -0.2653, -0.2879,  0.2875, -0.1032]], requires_grad=True),), **{})
(scroll up for backtrace)
```

Expected Output: exit 0

### Impact

I accidentally hit this when running a model that implicitly uses hugging face's accelerate module with torch.compile. HF's accelerate dynamically patches model.forward to do device offload. https://github.com/huggingface/accelerate/blob/main/src/accelerate/hooks.py#L118

### Versions

torch==2.1.0.dev20230428+cu117

The above example works with torch2.0 but fails on nightly

cc @ezyang @gchanan @zou3519 @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @soumith @desertfire

**Comment by awgu** [comment]
I wonder if HuggingFace should be using the pre/post-forward hooks:
https://github.com/pytorch/pytorch/blob/59cb02db54324a00ffd37d8ef292bc340eac9df6/torch/nn/modules/module.py#L1353
https://github.com/pytorch/pytorch/blob/59cb02db54324a00ffd37d8ef292bc340eac9df6/torch/nn/modules/module.py#L1417

**Comment by soulitzer** [comment]
The reason this happens is that when you get `original_forward = model.forward`, its a method bound to the particular model instance. And when dynamo invokes methods, it handles nn modules in a particular way (deleting this if-block removes the error):
https://github.com/pytorch/pytorch/blob/3e2ea32dabddd62347633b9cee0d91badb4130fc/torch/_dynamo/variables/functions.py#L303-L321

In particular, there's this logic here:
```python
return self.obj.call_method( 
     tx, self.fn.__name__, args, kwargs, constant=self.is_constant 
 ).add_options(self) 
```
that calls the current "forward" attribute of the object based on the function's name `Linear.forward`, and that means that in your code example, when it reaches `return old_forward(*args, **kwargs)`, it is actually calling into `new_forward`.

One workaround here is to get the unbound forward method of the original class:
```python
import torch
import torch.nn as nn
import torch._dynamo

model = nn.Linear(5, 5)

def new_forward(*args, **kwargs):
    return nn.Linear.forward(model, *args, **kwargs)

model.forward = new_forward

fn = torch.compile(model, backend='eager')
fn(torch.randn(1, 5))
```

Interestingly, this also makes it so that if you try to do the same thing again later, e.g. if you want to compose multiple wrappers together, that would actually work
```python
model = nn.Linear(5, 5)

def new_forward1(*args, **kwargs):
    return nn.Linear.forward(model, *args, **kwargs)

print("Is method originally:", inspect.ismethod(model.forward))  # True
model.forward = new_forward1

old_forward = model.forward
print("Is method now:", inspect.ismethod(old_forward))   # False

def new_forward2(*args, **kwargs):
    return old_forward(*args, **kwargs)

fn = torch.compile(model, backend='eager')
fn(torch.randn(1, 5))
```

**Comment by rohan-varma** [comment]
@soulitzer does your workaround still work if I try to monkey patch the forward of a module that is already torch.compiled? And in general, is this workaround supported / recommended by core + PT2? 

Also, any ideas why the particular error shows up as having to do with FakeTensors or why FakeTensors play a role here?

**Comment by soulitzer** [comment]
> And in general, is this workaround supported / recommended by core + PT2?

Yeah this is a good question. A larger discussion is whether we think patching `nn.module.forward` should be something that we consider hacky or should be considered officially part of the API surface that we support.

It feels like the pre/post forward hooks seem enough for the huggingface use case, unless they really care that even if people register hooks afterwards, the logic in their hooks are more "closely nested" to the original forward.

In general though there are still use cases that would benefit from wrapping nn.module forward. For example if I wanted to apply checkpoint to a module without having to module forward code, or messing with FQN. Perhaps its worth exposing a new API officially that would apply these types of wrappers, e.g. these wrappers could be invoked during _call_impl just like where the other hooks are.

**Comment by jbschlosser** [comment]
cc @mikaylagawarecki worth adding this as a known limitation of torch.compile + modules. Also, unrelated, but torch.compile()ing a module then running e.g. `eval()` should be in that list as well

**Comment by soulitzer** [comment]
> does your workaround still work if I try to monkey patch the forward of a module that is already torch.compiled?

@rohan-varma  It seems so:

```python
model = nn.Linear(5, 5)
print("Is method originally:", inspect.ismethod(model.forward))   # True

model = torch.compile(model, backend='eager')
old_forward = model.forward
# model.forward is no longer a method after doing torch.compile
print("Is method now:", inspect.ismethod(old_forward))  # False

def new_forward(*args, **kwargs):
    return old_forward(*args, **kwargs)

model.forward = new_forward

fn = torch.compile(model, backend='eager')
fn(torch.randn(1, 5))

```
