### ISSUE TITLE
Inconsistent casting of types for 'cpu' and 'mps' devices

### ISSUE THREAD

**Issue by MSciesiek** [pytorch/pytorch#100717]
### 🐛 Describe the bug

The same code crushes runtime for 'mps' accelerator (apple silicon chip), but works fine for 'cpu':

this works:
```
torch.zeros([1], dtype=torch.int64, device=torch.device('cpu').bernoulli(0.5)
```
this doesn't (resulting in a crash):
```
torch.zeros([1], dtype=torch.int64, device=torch.device('mps').bernoulli(0.5)
```
and this works:
```
torch.zeros([1], dtype=torch.int64, device=torch.device('mps').float().bernoulli(0.5).long()
```
Error message:
```
loc("mps_less"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":248:0)): error: input types 'tensor<1xf32>' and 'tensor<1xsi64>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
```

### Versions

PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.6 (default, Mar 10 2023, 20:16:38)  [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchvision==0.15.1
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Can repro on trunk, fix is coming...
