### ISSUE TITLE
Ability to pass cmake vars in docker build

### ISSUE THREAD

**Issue by kcarlson** [pytorch/pytorch#100866]
### 🚀 The feature, motivation and pitch

More recent pytorch docker images do not provide caffe2 for example. 
This would be possible if cmake vars could be passed to the build script.
It would also enable toggling any cmake variable in custom images.

### Alternatives

Forking the repo and adding the variables directly in the dockerfile

**Comment by malfet** [comment]
I was about to suggest, that I would gladly review a PR that adds something like that, but see you've already proposed one.
