### ISSUE TITLE
`run_test.py` doesn't work on local machines

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#100887]
### The Ask
1. Fix `test/run_test.py` so that it can run locally on dev boxes
2. Prevent regressions by adding a job to CI that invokes `run_test.py` in a configuration matching most dev boxes. This can be filtered to just run a couple tests.

### User feedback

As per @AlbanD:

> "run_test.py" is very much broken for local use...
> It can't even run a single test anymore, failing with "test_nn.py: error: unrecognized arguments: --shard-id=0 --num-shards=1 --reruns=2" for every one of them.
> 
> Do we have a plan for "run_test.py" in general? if it is expected to only be usable in CI, shouldn't we make it error out if people try to use it outside of it?

run_test.py is also needed to run cpp extension tests

**Comment by huydhn** [comment]
I guess we are missing something here as `python test/run_test.py -i test_nn --verbose` locally without any issue.  Those unrecognized arguments comes from some pytest plugins: `pytest-shard` and `pytest-rerunfailures` specifically (`pytest-flakefinder` is also pretty useful).  So I think the fix here is to either:

1.  Add instruction on which dependencies are needed by `run_test.py`.  `pip install -r .ci/docker/requirements-ci.txt` would have them all
2. Or dynamically exclude these flags when the plugins are not installed

**Comment by albanD** [comment]
> pip install -r .ci/docker/requirements-ci.txt

I was definitely missing that!
It would be great if something would point to that file when libs are missing!

**Comment by clee2000** [comment]
should be fixed by https://github.com/pytorch/pytorch/pull/100916
