### ISSUE TITLE
Support for 'aten::unflatten' operator when exporting to ONNX opset version 12

### ISSUE THREAD

**Issue by eliashossain001** [pytorch/pytorch#100826]
### 🐛 Describe the bug

Hello, I'm currently facing an issue while trying to export a PyTorch model **(AlignTTS of coqui-ai)** to ONNX format using the onnx.export() function with opset_version=12. Specifically, I'm getting an error message indicating that the 'aten::unflatten' operator is not supported for this opset version. I would like to request support for this operator when exporting to ONNX opset version 12. It would be very helpful if this operator could be added to the ONNX exporter or if there is a workaround or alternative solution to this issue. I have already tried lowering the opset version, but none of the solutions seem to have worked. I came across the issues of [#98190](https://github.com/pytorch/pytorch/issues/98190), which suggested applying a custom symbolic function, but I don't understand how this can be done. I would appreciate any assistance you can provide. 

Thank you!

Here is my code:

```


from typing import Dict
import torch
import torch.onnx as onnx
from torch.utils.tensorboard import SummaryWriter

import torch
import torchvision
import os
import torch.nn.functional as F
from TTS.tts.configs.shared_configs import BaseDatasetConfig,BaseAudioConfig,CharactersConfig
from TTS.tts.configs.glow_tts_config import GlowTTSConfig
from TTS.tts.configs.align_tts_config import AlignTTSConfig
from TTS.utils.audio import AudioProcessor
from TTS.tts.utils.text.tokenizer import TTSTokenizer
from TTS.tts.models.glow_tts import GlowTTS
from TTS.tts.models.align_tts import AlignTTS
from TTS.tts.datasets import load_tts_samples
from trainer import Trainer, TrainerArgs
from TTS.tts.models.align_tts import AlignTTSArgs
import torch.jit
import sys
from torch import nn
from torch.onnx.symbolic_helper import parse_args, _unimplemented
from torch.onnx import register_custom_op_symbolic


class AlignTTSModelClass(nn.Module):
    def __init__(self, num_graphemes, seq_len):
        super().__init__()

        # Create an instance of the AlignTTSConfig class with the desired parameters
        config = AlignTTSConfig(
            # model_name="align_tts",
            model_args=AlignTTSArgs(
                num_chars=num_graphemes,
                out_channels=80,
                hidden_channels=256,
                hidden_channels_dp=256,
                encoder_type="fftransformer",
                encoder_params={"hidden_channels_ffn": 1024, "num_heads": 2, "num_layers": 6, "dropout_p": 0.1},
                decoder_type="fftransformer",
                decoder_params={"hidden_channels_ffn": 1024, "num_heads": 2, "num_layers": 6, "dropout_p": 0.1},
                length_scale=1.0,
                num_speakers=0,
                use_speaker_embedding=False,
                use_d_vector_file=False,
                d_vector_dim=0,
            )
        )

        # Create an instance of the AlignTTS class using the config
        self.align_tts = AlignTTS(config)

        # Set the input shape of the model
        self.input_shape = (seq_len, num_graphemes)
        
   
    def forward(self, x: torch.Tensor, x_lengths: torch.Tensor, y: torch.Tensor, y_lengths: torch.Tensor) -> Dict[str, torch.Tensor]:
        # Perform the forward pass through the AlignTTS model, passing the additional arguments
        aux_input = {"d_vectors": None} # dummy input for the "aux_input" argument
        phase = None # dummy input for the "phase" argument
        return self.align_tts.forward(x, x_lengths, y, y_lengths, aux_input, phase)
    
    
if __name__ == '__main__':
    # Parameters
    batch_size = 8
    num_graphemes = 105
    seq_len = 256

    # Load the PyTorch checkpoint
    checkpoint_path = '/home/elias/male_checkpoint.pth'
    checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))

    dummy_input = torch.randint(low=0, high=num_graphemes, size=(batch_size, seq_len), dtype=torch.long)
    dummy_input_lengths = torch.randint(low=1, high=seq_len+1, size=(batch_size,))
    dummy_output_lengths = torch.randint(low=1, high=seq_len+1, size=(batch_size,))
    dummy_output = torch.randn(batch_size, seq_len, 80)

    model = AlignTTSModelClass(num_graphemes=num_graphemes, seq_len=seq_len)
    # Enable autograd profiler
    torch.autograd.profiler.profile(enabled=True, use_cuda=False)

    # Perform a forward pass of the model
    with torch.autograd.profiler.record_function("model_inference"):
        model(dummy_input, dummy_input_lengths, dummy_output, dummy_output_lengths)

    # Disable autograd profiler
    torch.autograd.profiler.profile(enabled=False)

    model = torch.nn.DataParallel(model)
    
    # Load the state dictionary from the checkpoint
    state_dict = checkpoint['model']
    model_state_dict = model.state_dict()
    for name, param in state_dict.items():
        if name not in model_state_dict:
            print(f"Ignoring parameter '{name}' in the checkpoint because it does not exist in the model")
        elif param.shape != model_state_dict[name].shape:
            print(f"Ignoring parameter '{name}' in the checkpoint because its shape does not match the corresponding model parameter")
        else:
            model_state_dict[name] = param

    # Load the state dictionary into the model
    model.load_state_dict(model_state_dict, strict=False)
    
 
    # Export the model to ONNX format
    onnx_path = '/home/elias/male_model.onnx'
    
    torch.onnx.utils.export(model.module, (dummy_input, dummy_input_lengths, dummy_output, dummy_output_lengths), onnx_path,
            verbose=True, export_params=True, opset_version=12, 
            input_names=['input', 'input_lengths', 'output_lengths'],
            output_names=['output'],
            dynamic_axes={'input': {0: 'batch_size', 1: 'seq_len'},
                          'input_lengths': {0: 'batch_size'},
                          'output_lengths': {0: 'batch_size'},
                          'output': {0: 'batch_size', 1: 'seq_len'}})
    
    print('Export to ONNX has been successful!!')

   

============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::unflatten' to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>


Traceback (most recent call last):
  File "/home/elias/script/onnx_2.py", line 111, in <module>
    torch.onnx.utils.export(model.module, (dummy_input, dummy_input_lengths, dummy_output, dummy_output_lengths), onnx_path,
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/onnx/utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/onnx/utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::unflatten' to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

```

### Versions

```
CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
Stepping:              2
CPU MHz:               1499.969
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-39

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1+cu117
[pip3] torchvision==0.15.1+cu117
[pip3] triton==2.0.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchaudio                2.0.1+cu117              pypi_0    pypi
[conda] torchvision               0.15.1+cu117             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
```

**Comment by shivamkc01** [comment]
Hi @eliashossain001,
You can try exporting the model using a lower opset version that supports the **'aten::unflatten**' operator. You can specify a lower opset version, such as **opset_version=11**, in the **onnx.export()** function to see if it resolves the issue.

Why the issue is The '**aten::unflatten'** operator in PyTorch is used to reshape a tensor according to specified dimensions. However, support for exporting this operator to ONNX opset version 12 is currently missing.

Please let me know if it isn't working for you; I would greatly appreciate your opinion.

**Comment by eliashossain001** [comment]
@shivamkc01 I've tried using various versions of opset, including version 11, but none of them seem to have solved my problem. I'm still experiencing the same issues!

**Comment by titaiwangms** [comment]
It needs at least opset version 13 for now.

**Comment by eliashossain001** [comment]
@titaiwangms I used the opset version 13 to run, however, I'm getting the similar error!!

**Comment by titaiwangms** [comment]
Try nightly then

**Comment by eliashossain001** [comment]
@titaiwangms Thanks for the feedback, I'm actively working to solve it.

**Comment by 0de554kw** [comment]
The same issue with exporting BridgeTower using torch.onnx.export,
 
`"""BridgeTower_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JCtJCI0kREuLPh7BcfIJDsEzzVtSOY9_
"""

!pip install transformers pillow onnx

from transformers import BridgeTowerProcessor, BridgeTowerModel
from PIL import Image
import requests
import numpy as np
import torch

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
text = "hello world"
processor = BridgeTowerProcessor.from_pretrained("BridgeTower/bridgetower-base")
model = BridgeTowerModel.from_pretrained("BridgeTower/bridgetower-base")
inputs = processor(image, text, return_tensors="pt")

input_ids_o  = torch.rand(inputs['input_ids'].shape).type(torch.LongTensor)
attention_mask_o  = torch.rand(inputs['attention_mask'].shape).type(torch.LongTensor)
pixel_values_o  = torch.rand(inputs['pixel_values'].shape).type(torch.FloatTensor)
pixel_mask_o  = torch.rand(inputs['pixel_mask'].shape).type(torch.LongTensor)

torch.onnx.export(
    model,
    args=(input_ids_o, attention_mask_o, pixel_mask_o, pixel_values_o),
    f="bridgetower.onnx",
    opset_version=18,
    verbose=True 
)`

I have tried  opsets from 10 to 18

============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::unflatten' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

**Comment by titaiwangms** [comment]
@0de554kw you can either try nightly or wait until 2.1.0 released.

**Comment by eliashossain001** [comment]
@0de554kw DId you try making a custom operator to bypass the aten::unflatten issues? I went to solve and @titaiwangms suggested me to work on it nightly, however, none of these seems to have worked for me.

**Comment by haojiang1** [comment]
> 

Same for me, nightly doesn't work for me.

**Comment by eliashossain001** [comment]
@haojiang1 If you have a solution to the problem, I would appreciate it if you could share it with me. Additionally, I'm actively seeking alternative methods to solve the problem. I would be grateful if you could inform me of any alternative approaches you may have.

**Comment by Yebi1837** [comment]
hi I am also actively blocked by this work. Does anyone have a solution yet?

**Comment by eliashossain001** [comment]
@Yebi1837 Not yet, I haven't found any solution!

**Comment by Yebi1837** [comment]
@eliashossain001 so this nightly [patch](https://github.com/pytorch/pytorch/pull/99056) doesn't work? 
Unfortunately I couldn't upgrade my PyTorch so I am moving ahead to try build MHA module myself without using unflatten OP.

**Comment by Nagaloop** [comment]
Same for me, so yet is there a solution to solve it?

**Comment by eliashossain001** [comment]
@Nagaloop Not yet

**Comment by fengyuentau** [comment]
Installing `pytorch < 2.0.0` works for me.

**Comment by gcr** [comment]
I'm able to export a transformer model that fails this way to onnx.

```
!pip3 install -U --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
```

Make sure to restart the runtime after, and make sure that `torch.__version__` evaluates to a version at least after `2.1.0.dev20230808+cpu`.

In my case, I'm converting Intel's ZoeDepth model to onnx; there were some other small issues that required editing that model's source files, but this particular issue no longer happens.

```
import onnx
model.eval()
torch.onnx.export(
    model,
    torch.randn(1, 3, 384, 512),
    'zoedepth_n.onnx',
    opset_version=13,
)
```

**Comment by coderjoonwoo** [comment]
pytorch nightly version works for me as of today. FYI my environment is conda and the installation command was 'conda install pytorch torchvision cpuonly -c pytorch-nightly'.

**Comment by justinchuby** [comment]
@fdwr do you perhaps have some suggestions around the ONNX opset support in WinML?

**Comment by justinchuby** [comment]
@coderjoonwoo 

I learned from @fdwr that WinML now supports opset 15. 

WinML is built as part of ONNX Runtime, downloadable from the GitHub releases page: https://github.com/microsoft/onnxruntime/releases
Or nuget: https://www.nuget.org/packages/Microsoft.AI.MachineLearning

If you see an error loading the model please let us now.

**Comment by coderjoonwoo** [comment]
@justinchuby  Happy to know that ONNX supports aten::unflatten. I want current https://learn.microsoft.com/en-us/windows/ai/windows-ml/onnx-versions show the same information. Thanks to the mismatch, I found libtorch as a substitute and it works for me if I don't mind a few compiler warnings causing memory leaks.
