### ISSUE TITLE
NameError('math is not defined') in Triton codegen for llama with dynamic shapes

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#100972]
### 🐛 Describe the bug

Repro:

```
benchmarks/dynamo/torchbench.py --inductor --dynamic-shapes --devices cuda --inference --accuracy  --only llama
```

Gives:

```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CompilationError: at 13:15:    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
    xmask = xindex < xnumel
    rbase = tl.arange(0, RBLOCK)[None, :]
    x0 = xindex
    _tmp3 = tl.full([XBLOCK, RBLOCK], float("-inf"), tl.float32)
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r1 = rindex
        tmp0 = tl.load(in_ptr0 + (r1 + x0 + (ks0*x0)), rmask & xmask, eviction_policy='evict_last', other=0)
        tmp1 = math.sqrt(ks1)
               ^
NameError('math is not defined')
```

Some fixes that don't work:

Teaching Triton to codegen tl.math.sqrt https://gist.github.com/ezyang/2c2e61f6a40b4cba466651d3ecbd0316 fails with

```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CompilationError: at 13:28:    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
    xmask = xindex < xnumel
    rbase = tl.arange(0, RBLOCK)[None, :]
    x0 = xindex
    _tmp3 = tl.full([XBLOCK, RBLOCK], float("-inf"), tl.float32)
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r1 = rindex
        tmp0 = tl.load(in_ptr0 + (r1 + x0 + (ks0*x0)), rmask & xmask, eviction_policy='evict_last', other=0)
        tmp1 = tl.math.sqrt(ks1)
                            ^
ValueError('input arg type does not match.Expect one of dict_keys([(triton.language.fp32,), (triton.language.fp64,)]), got (triton.language.int32,)')
```

Using the ceil/floor hoisting to hoist this out https://gist.github.com/ezyang/c8007f966724ad52e7dd5af564bad9b5 fails with:

```
  File "/data/users/ezyang/d/pytorch/torch/_inductor/compile_fx.py", line 331, in run
    return model(new_inputs)
  File "/tmp/torchinductor_ezyang/2s/c2sxzsabdfa34kk23cck4rgh6gcqgtw6zv5hux5cm5hlvk5iig4f.py", line 1035, in call
    triton_red_fused__softmax_div_5.run(buf25, buf26, buf27, s1, ps6, triton_red_fused__softmax_div_5_xnumel, triton_red_fused__softmax_div_5_rnumel, grid=grid(triton_red_fused__softmax_div_5_xnumel), stream=stream0)
  File "/data/users/ezyang/d/pytorch/torch/_inductor/triton_heuristics.py", line 343, in run
    return launcher(
  File "<string>", line 6, in launcher
TypeError: 'float' object cannot be interpreted as an integer
```

The full generated code is https://gist.github.com/ezyang/fd38597cbc2c61cee4710a8a0d871b2c

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire 

### Versions

master

**Comment by AlphaAtlas** [comment]
I think #101228 may be related?

**Comment by AlphaAtlas** [comment]
I am getting what seems like a similar error in another llama repo using `dynamic=true`

[llama_error.txt](https://github.com/pytorch/pytorch/files/11458871/llama_error.txt)

Which also seems similar to https://github.com/pytorch/pytorch/issues/101228

Or maybe is unrelated :shrug:

**Comment by ezyang** [comment]
from @ngimel:

> sqrt is coming from here https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/llama/model.py#L138, self.head_dim is defined here https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/llama/model.py#L76, it should be specialized as it comes from integer module constructor arguments, but instead it is sent as an input to fx graph. How can we make it specialized?

**Comment by ezyang** [comment]
Model doesn't fail if you force assume-static-by-default:

```
benchmarks/dynamo/torchbench.py --inductor --dynamic-shapes --dynamic-batch-only --devices cuda --inference --accuracy  --only llama
```

The problem is that llama modifies nn modules:

```
    def forward(self, x: torch.Tensor, start_pos: int, freqs_cis: torch.Tensor, mask: Optional[torch.Tensor]):
        bsz, seqlen, _ = x.shape
        xq, xk, xv = self.wq(x), self.wk(x), self.wv(x)

        xq = xq.view(bsz, seqlen, self.n_local_heads, self.head_dim)
        xk = xk.view(bsz, seqlen, self.n_local_heads, self.head_dim)
        xv = xv.view(bsz, seqlen, self.n_local_heads, self.head_dim)

        xq, xk = apply_rotary_emb(xq, xk, freqs_cis=freqs_cis)

        self.cache_k = self.cache_k.to(xq)
        self.cache_v = self.cache_v.to(xq)
```

in `torchbenchmark/models/llama/model.py`

This causes the module to get unspecialized, which means we will attempt to compile accesses to its parameters with symbolic shapes if assume static by default is False (which it is).

This policy... doesn't seem obviously wrong to me. In reality you would fix it by using assume static by default.  Maybe we should still fix the codegen though.
