### ISSUE TITLE
I can't infer my model trained by pytorch=1.10, in pytorch=2.0

### ISSUE THREAD

**Issue by lhc741** [pytorch/pytorch#100935]
### 🐛 Describe the bug

I trained a model with UpsamplingBilinear2d operator in  pytorch=1.10, but I can't infer it in pytorch=2.0
The error is: AttributeError: 'UpsamplingBilinear2d' object has no attribute 'recompute_scale_factor' 
A few model structure：
```python
class SegmentationHead(nn.Sequential):

    def __init__(self, in_channels, out_channels, kernel_size=3, activation=None, upsampling=1):
        super(SegmentationHead, self).__init__()
        self.conv2d = nn.Conv2d(in_channels, out_channels, kernel_size=kernel_size, padding=kernel_size // 2)
        self.upsampling = nn.UpsamplingBilinear2d(scale_factor=upsampling) if upsampling > 1 else nn.Identity()
        self.activation = Activation(activation)
    def forward(self, x):
        x = self.conv2d(x)
        x = self.upsampling(x)
        x = self.activation(x)
        return x
```
And other projects also with this trouble like:
https://github.com/search?q=AttributeError%3A+%27Upsample%27+object+has+no+attribute+%27recompute_scale_factor%27&type=issues

It seems like some wrong from pytorch=1.11:
https://github.com/pytorch/pytorch/blob/bc2c6edaf163b1a1330e37a6e34caf8c553e4755/torch/nn/modules/upsampling.py#L140

### Versions

from pytorch=1.11~2.0

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by ezyang** [comment]
This is an oopsie where we added a new attribute and forgot to update the deserialization code. Relatively easy to fix, consider sending us a PR.

**Comment by lhc741** [comment]
> This is an oopsie where we added a new attribute and forgot to update the deserialization code. Relatively easy to fix, consider sending us a PR.
Thank you for your reply. I appreciate your suggestion to send a PR, but I’m not very familiar with the deserialization code.

**Comment by albanD** [comment]
You can add to this class https://github.com/pytorch/pytorch/blob/9ff547a57fe7f5f110a07ee7cdf933bb521d0966/torch/nn/modules/upsampling.py#L158
The proper code to make sure that on loading this field is populated in such a way that it preserves the old behavior. You can see an example of that here: https://github.com/pytorch/pytorch/blob/cb668b1291ccdf5ebc045b6d0a566dab1e97f450/torch/nn/modules/activation.py#L1033-L1038

**Comment by tfsingh** [comment]
I'd be happy to work on this for you, @lhc741 . I'll try to get a PR up by the end of the week.

**Comment by jbschlosser** [comment]
cc @mikaylagawarecki you can add things like this to your list of possible BC issues :)
