### ISSUE TITLE
[docs bug] wrong indexing of class name

### ISSUE THREAD

**Issue by ain-soph** [pytorch/pytorch#100944]
### 📚 The doc issue

Similar to #73631, there is document issue again for [torch.backends.cudnn](https://pytorch.org/docs/stable/backends.html#module-torch.backends.cudnn). It shall be `torch.backends.cudnn.benchmark`, but it is now `torch.backends.cudnn.torch.backends.cudnn.benchmark`.

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/13214530/236988608-5e5f242a-45a2-404d-a80e-0d04e4d1d79e.png">

This issue actually occurs for all attributes in [the backends page](https://pytorch.org/docs/stable/_sources/backends.rst.txt). I don't know if it happens for other pages.

### Suggest a potential alternative/fix

I'll link a PR soon.

cc @svekars @carljparker

**Comment by ain-soph** [comment]
Btw, I don't think this search item is expected: 
[torch.backends.cuda.torch.backends.cuda.size](https://pytorch.org/docs/stable/backends.html?highlight=torch+backends+cuda+size#torch.backends.cuda.torch.backends.cuda.size)
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/13214530/236990422-0b34a26b-684c-4b89-8d77-beac68d65e75.png">

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/13214530/236990394-f5db697d-1bff-4b78-b714-0dcfedada819.png">

**Comment by albanD** [comment]
Sounds good!
