### ISSUE TITLE
windows pytorch 0.4.1 error=48 : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by gongliyu** [pytorch/pytorch#10094]
## Issue description
After I updated windows pytorch from 0.4.0 to 0.4.1,  one of my network code throws an error. I tried to downgrade back to 0.4.0. The code works well on 0.4.0.

The error messages are shown below:
THCudaCheck FAIL file=c:\programdata\miniconda3\conda-bld\pytorch_1532505617613\work\aten\src\thc\generic/THCTensorMathPairwise.cu line=102 error=48 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "classification.py", line 173, in <module>
    logits = model(X, edges)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "classification.py", line 119, in forward
    net = self.hidden_layers(nodes, edges)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\experiment\citation\models.py", line 34, in forward
    net = torch.cat([x(net, edges) for x in self.layers[i]], dim=1)
  File "D:\experiment\citation\models.py", line 34, in <listcomp>
    net = torch.cat([x(net, edges) for x in self.layers[i]], dim=1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\experiment\citation\nn.py", line 35, in forward
    nodes = F.dropout(nodes, self.feature_dropout, self.training)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py", line 595, in dropout
    return _functions.dropout.Dropout.apply(input, p, training, inplace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\_functions\dropout.py", line 40, in forward
    ctx.noise.bernoulli_(1 - ctx.p).div_(1 - ctx.p)
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at c:\programdata\miniconda3\conda-bld\pytorch_1532505617613\work\aten\src\thc\generic/THCTensorMathPairwise.cu:102

## System Info
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Home
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Quadro M520
Nvidia driver version: 385.54
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy (1.14.1)
[pip] numpydoc (0.7.0)
[pip] torch (0.4.1)
[conda] pytorch                   0.4.1           py36_cuda90_cudnn7he774522_1    pytorch

**Comment by soumith** [comment]
cc: @peterjc123 can you check if we didn't compile 0.4.1 with compute capability 5.0? We should be doing https://github.com/pytorch/builder/blob/master/conda/pytorch-0.4.1/build.sh#L8

3.0, 5.0+PTX, 6.0, 6.1, 7.0

**Comment by soumith** [comment]
The new binaries are updated for Windows.

If you have previously installed via anaconda, you have to do:

```
conda uninstall -y pytorch
conda clean -t -y
```

and then reinstall pytorch.


If you have installed via `pip` command on https://pytorch.org, first uninstall pytorch via `pip uninstall torch` and then rerun that command (so that the new wheel is downloaded and installed)
