### ISSUE TITLE
when i try to use FullyShardedDataParallel to finetune a LLM with huggingface peft library, pytorch raise error ValueError: `FlatParameter` requires uniform `requires_grad`

### ISSUE THREAD

**Issue by zhujc000** [pytorch/pytorch#100945]
## Issue description:

          when i try to use FullyShardedDataParallel to finetune a LLM with huggingface peft library, pytorch raise error ValueError: 

`FlatParameter` requires uniform `requires_grad`. i also notice this issue:https://github.com/pytorch/pytorch/issues/76501. base on 

the description of issue 76501, peft will not support in current pip installed pytorch 2.0.0 ?

## Code example
   model = ChatGLMForConditionalGeneration.from_pretrained(pretrained_model_name_or_path=BASE_DIR,
                                                            config=config)
    print("model loaded")

    peft_config = LoraConfig(task_type=TaskType.CAUSAL_LM,
                             inference_mode=False,
                             r=12,
                             lora_alpha=32,
                             lora_dropout=0.1)

    model = get_peft_model(model, peft_config=peft_config)
    print("peft model loaded")
    model.print_trainable_parameters()

    torch.cuda.set_device(rank)

    glm_auto_wrap_policy = functools.partial(
        transformer_auto_wrap_policy,
        transformer_layer_cls={
            GLMBlock,
        },
    )

    model = FullyShardedDataParallel(model,
                                     auto_wrap_policy=glm_auto_wrap_policy,
                                     cpu_offload=CPUOffload(offload_params=True),
                                     device_id=torch.cuda.current_device(),
                                     sharding_strategy=ShardingStrategy.FULL_SHARD)

    ...
    normal train code

- PyTorch
- How you installed PyTorch: pip
- OS: CentOS
- PyTorch version:2.0.0
- Python version:3.9.7
- CUDA/cuDNN version: CUDA Version: 11.8
- GPU models and configuration:NVIDIA T4

cc @zhaojuanmao @mrshenli @rohan-varma @awgu

**Comment by awgu** [comment]
This is a known limitation for FSDP. Every parameter in a module wrapped by `FullyShardedDataParallel` must have the same `requires_grad` for `use_orig_params=False`. You can try `use_orig_params=True` to avoid the error (using a PyTorch nightly build), but you may find that the memory usage is still high. Reducing that will require some fundamental design changes.

**Comment by GitOutOfMyBed** [comment]
I am encountering this problem. Can someone explain further what the answer above means? What exactly is "use_orig_params" and how do you set it, and how does setting it to true/false change things?

**Comment by shassan97** [comment]
I ran into this issue when using fixed sin-cos embeddings in a ViT model which has requires_grad=False. Is there a way to use sin-cos positional embeddings in a vision transformer model with FSDP?

**Comment by PistonY** [comment]
Do you have plans to fix this?

**Comment by awgu** [comment]
I am not up to date on the latest in HF PEFT, but if you use FSDP2 (https://github.com/pytorch/pytorch/issues/114299, https://github.com/pytorch/torchtitan/blob/main/docs/fsdp.md), then you can mix frozen and non-frozen parameters however you want. torchtune has examples, including for LoRA: https://github.com/pytorch/torchtune/blob/main/recipes/lora_finetune_distributed.py

**Comment by ZhengRachel** [comment]
> I am encountering this problem. Can someone explain further what the answer above means? What exactly is "use_orig_params" and how does setting it to true/false change things?

Same here. ```use_orig_params=True``` solved for me but could someone please provide some insights on what's the difference between True and False?
