### ISSUE TITLE
weight initializations for conv2d and linear

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#101]
Allow different weight initialization schemes for conv2d and linear.
See: https://github.com/Kaixhin/nninit for some schemes.

**Comment by felipefariax** [comment]
I thought to add another class called Initializers, that would have a function that we could pass the weights and a string with the initialization_name. Also add an string argument to every layer called "initialization".

Do you think that this is the best approach? If not, what would be the best way to do this?

**Comment by apaszke** [comment]
I think it's better to pass in a function as the initializer and call it with weights as argument. It's clean, verbose, and you don't have to do error checking for invalid/incompatible strings. For example:

```python
nn.Linear(20, 20, weight_init=nn.init.orthogonal)
```

Do you want to implement it, or was your comment only a suggestion?

**Comment by jekbradbury** [comment]
Chainer has a nice approach, where the initializer argument is a little polymorphic (can be a callable or a scalar/matrix value). Looks like this:
```python
super().__init__(
    maxout=Maxout(maxout_size, maxout_size, 2, initialW=initializers.GlorotUniform()),
    softmax_linear=Linear(maxout_size, task.num_classes, initialW=0))
```

**Comment by felipefariax** [comment]
@apaszke, I am thinking to implement it.

I think that String-like is cleaner. But we could go the way Chainer implements it, as shown by @jekbradbury. With strings or class names being accepted.

What do you guys think?
