### ISSUE TITLE
[BE] Refactor logic for MultiTensorApply

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#101096]
### 🚀 The feature, motivation and pitch

Context: https://github.com/pytorch/pytorch/pull/100811#discussion_r1187576042

It would be a valuable next step to refactor the multitensorapply code to allow for better engineering in terms of clarity. The code currently is convoluted and we should break up the for-loop into separate preprocessing and kernel call steps. Desirable outcomes:
- allow people to more easily understand what is going on
- lessen the chance that bugs will be introduced accidentally

### Alternatives

do nothing

cc @crcrpar @mcarilli @ngimel

**Comment by tfsingh** [comment]
I'd love to make an attempt at this, but I'm somewhat new to CUDA (I have a rough idea of the programming model and have experience writing small kernels). Do you think this would be a good issue for me?

**Comment by janeyx99** [comment]
@tfsingh Most of the refactoring I anticipate will be in C++, but having a bit of understanding of CUDA kernels will be helpful for understanding what is going on. Thus, I’d say to go for it! Let me know if you have questions :)

**Comment by crcrpar** [comment]
just wondering if anyone is working on this?
I won't in a week or two though

**Comment by tfsingh** [comment]
Yes, I'm making an attempt at this issue.

**Comment by janeyx99** [comment]
https://github.com/pytorch/pytorch/pull/109402 has made an attempt refactoring and resolved the bug that originally triggered this request. Closing for that reason. Thanks @tfsingh for volunteering to work on it though!
