### ISSUE TITLE
About libtorch

### ISSUE THREAD

**Issue by yingtongxiong** [pytorch/pytorch#101063]
### 🐛 Describe the bug

Hi，I download the libtorch from the website https://pytorch.org/
<img width="624" alt="捕获" src="https://github.com/pytorch/pytorch/assets/45058324/a872ece0-fa55-4f87-bd09-6c703af4206c">
And the version is above. However, when I compile my code, I have met some problems
/libtorch/lib/libtorch_cpu.so: undefined reference to `powf@GLIBC_2.27'
/libtorch/lib/libtorch_cpu.so: undefined reference to `log2f@GLIBC_2.27'
/libtorch/lib/libtorch_cpu.so: undefined reference to `lgammaf@GLIBC_2.23'
/libtorch/lib/libtorch_cpu.so: undefined reference to `expf@GLIBC_2.27'
/libtorch/lib/libtorch_cpu.so: undefined reference to `exp2f@GLIBC_2.27'
/libtorch/lib/libtorch_cpu.so: undefined reference to `lgamma@GLIBC_2.23'
/libtorch/lib/libtorch_cpu.so: undefined reference to `logf@GLIBC_2.27'

And my glibc version is 2.27. So, I don't know where's wrong? Who can tell me why this happened? And Any suggestions?

### Versions

cuda: 11.7
gcc: 10.1.0
glibc:2.27

cc @seemethere @malfet

**Comment by krishnatoshniwal** [comment]
@yingtongxiong  what was the resolution for this?

**Comment by ireaml** [comment]
@yingtongxiong did you manage to fix this? Thanks!
