### ISSUE TITLE
Torch distributed fails when using GPU

### ISSUE THREAD

**Issue by MicheleDelliVeneri** [pytorch/pytorch#101172]
### 🐛 Describe the bug

When running the following script employing the nccl backend, I get an initialization error. Both scripts are run with the following command
```
CUDA_LAUNCH_BLOCKING=1 torchrun --standalone --nnodes=1 --nproc_per_node=2  test_2.py
```

**CPU Test**
```
import os

import torch
from torch import nn
import multiprocessing as mp

torch.distributed.init_process_group(backend="gloo")
rank = int(os.environ["LOCAL_RANK"])
device = f"cuda:{rank}"
torch.cuda.set_device(device)

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))
    

if __name__ == "__main__":
    model = ToyModel()
    model = model.to(device)
    model = torch.nn.parallel.DistributedDataParallel(
        model, device_ids=[rank], broadcast_buffers=False 
    )
    print('Model created on the rank: {}'.format(rank))
    print('The device is: {}'.format(device))
    print('the number of cpus (cores) are: {}'.format(mp.cpu_count()))
    print('The number of gpus are: {}'.format(torch.cuda.device_count()))
    print('the number of available threads are: {}'.format(torch.get_num_threads()))
```
I get the following output:
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Model created on the rank: 0
The device is: cuda:0
the number of cpus (cores) are: 24
The number of gpus are: 2
the number of available threads are: 1
Model created on the rank: 1
The device is: cuda:1
the number of cpus (cores) are: 24
The number of gpus are: 2
the number of available threads are: 1
```

**GPU Test**
changing the backend to nccl

```
import os

import torch
from torch import nn
import multiprocessing as mp

torch.distributed.init_process_group(backend="nccl")
rank = int(os.environ["LOCAL_RANK"])
device = f"cuda:{rank}"
torch.cuda.set_device(device)

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))
    

if __name__ == "__main__":
    model = ToyModel()
    model = model.to(device)
    model = torch.nn.parallel.DistributedDataParallel(
        model, device_ids=[rank], broadcast_buffers=False 
    )
    print('Model created on the rank: {}'.format(rank))
    print('The device is: {}'.format(device))
    print('the number of cpus (cores) are: {}'.format(mp.cpu_count()))
    print('The number of gpus are: {}'.format(torch.cuda.device_count()))
    print('the number of available threads are: {}'.format(torch.get_num_threads()))
```

I get the following error message
```
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/michele/GitHub/DeepFocus_Speed/utils/test_2.py", line 26, in <module>
    model = torch.nn.parallel.DistributedDataParallel(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 809, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/utils.py", line 210, in _verify_param_shape_across_processes
Traceback (most recent call last):
  File "/home/michele/GitHub/DeepFocus_Speed/utils/test_2.py", line 26, in <module>
    return dist._verify_params_across_processes(process_group, tensors, logger)
           ^^^    ^model = torch.nn.parallel.DistributedDataParallel(^
^^ ^ ^^ ^ ^ ^  ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 809, in __init__

torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1165, unhandled cuda error, NCCL version 2.17.1
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'initialization error'
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/utils.py", line 210, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1165, unhandled cuda error, NCCL version 2.17.1
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'initialization error'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4394) of binary: /home/michele/anaconda3/envs/deepfocus/bin/python
Traceback (most recent call last):
  File "/home/michele/anaconda3/envs/deepfocus/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
test_2.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-05-11_11:01:09
  host      : michelepc.
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 4395)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-11_11:01:09
  host      : michelepc.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4394)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
Any help is highly appreciated. 
Thank you, 
Michele 

### Versions

Update on the Configuration due to CMake and Cla: 

Collecting environment information...
PyTorch version: 2.1.0.dev20230508+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1660 Ti
GPU 1: NVIDIA GeForce GTX 1660 Ti

Nvidia driver version: 531.79
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) W-2265 CPU @ 3.50GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        7
BogoMIPS:                        7008.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_vnni flush_l1d arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       384 KiB (12 instances)
L1i cache:                       384 KiB (12 instances)
L2 cache:                        12 MiB (12 instances)
L3 cache:                        19.3 MiB (1 instance)
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0.dev20230508+cu121
[pip3] torchaudio==2.1.0.dev20230508+cu121
[pip3] torchio==0.18.91
[pip3] torchvision==0.16.0.dev20230508+cu121
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+7d1a95b046          pypi_0    pypi
[conda] torch                     2.1.0.dev20230508+cu121          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230508+cu121          pypi_0    pypi
[conda] torchio                   0.18.91                  pypi_0    pypi
[conda] torchvision               0.16.0.dev20230508+cu121          pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by Aidyn-A** [comment]
@MicheleDelliVeneri, can you please share a NCCL log?
```
NCCL_DEBUG=INFO CUDA_LAUNCH_BLOCKING=1 torchrun --standalone --nnodes=1 --nproc_per_node=2 nccl.py
```

**Comment by MicheleDelliVeneri** [comment]
Hi @Aidyn-A thank you for your comment. I have run the command and I get the following error

`FO CUDA_LAUNCH_BLOCKING=1 torchrun --standalone --nnodes=1 --nproc_per_node=2 nccl.py
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/cuda/nccl.py", line 4, in <module>
    import torch.cuda
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/__init__.py", line 23, in <module>
    from ._utils_internal import get_file_path, prepare_multiprocessing_environment, \
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/_utils_internal.py", line 4, in <module>
    import tempfile
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/cuda/random.py", line 3, in <module>
    from . import _lazy_init, _lazy_call, device_count, current_device
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/cuda/nccl.py", line 4, in <module>
    import torch.cuda
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/__init__.py", line 23, in <module>
    from ._utils_internal import get_file_path, prepare_multiprocessing_environment, \
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/_utils_internal.py", line 4, in <module>
    import tempfile
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/cuda/random.py", line 3, in <module>
    from . import _lazy_init, _lazy_call, device_count, current_device
ImportError: attempted relative import with no known parent package
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2475) of binary: /home/michele/anaconda3/envs/deepfocus/bin/python
Traceback (most recent call last):
  File "/home/michele/anaconda3/envs/deepfocus/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michele/anaconda3/envs/deepfocus/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
nccl.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-05-12_11:21:31
  host      : michelepc.
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2476)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-12_11:21:31
  host      : michelepc.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2475)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html`


Apparently, there is an ImportError in the /torch/cuda/random.py script when it tries to import these functions from the __init__.py
 `from . import _lazy_init, _lazy_call, device_count, current_device`

**Comment by Aidyn-A** [comment]
How did you install PyTorch? Seems like a an error in python modules. Can you please reinstall and try again?

**Comment by fduwjj** [comment]
It seems to be working on my side. My environment is also Ubuntu.

**Comment by MicheleDelliVeneri** [comment]
After installing through docker, I was able to successfully employ both GPUs. Thank you all for the assistance. 
Cheers!

**Comment by JerryDaHeLian** [comment]
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1347, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.5
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument'
I have encountered the same problem, has anyone solved it?
