### ISSUE TITLE
Masked copy returns a broken gradient for one of the arguments

### ISSUE THREAD

**Issue by Smerity** [pytorch/pytorch#1011]
When using `masked_copy` the variable that is copied from is not given a correct (full sized) gradient.

```
import torch
from torch.autograd import Variable

x = Variable(torch.rand(4), requires_grad=True)
y = Variable(torch.ones(4), requires_grad=True)
m = Variable(torch.ByteTensor([1, 1, 0, 1]))

z = x.masked_copy(m, 2 * y)

print('x', x)
print('y', y)
print('z', z)

loss = z.sum()
loss.backward()
print('xg', x.grad)
print('yg', y.grad)

y.data.add_(y.grad.data)
```

The above code results in `RuntimeError: inconsistent tensor size at /Users/soumith/code/pytorch-builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:827` as `y` is a torch.FloatTensor of size 4 and `y.grad` is a torch.FloatTensor of size 3.

This appears to be an issue with https://github.com/pytorch/pytorch/blob/16a133ed9abfc8d6c0c574586451c4e600a6c2a6/torch/autograd/_functions/tensor.py#L403 which specifically uses `grad_tensor2 = grad_output.masked_select(mask) ` which returns only the number of elements in the mask that are active.

If we change that line to `grad_tensor2 = grad_output.clone().masked_fill_(mask.eq(0), 0)`, the code works.

```
import torch
from torch.autograd import Variable

class MaskedCopy(torch.autograd.function.InplaceFunction):

    def forward(self, tensor1, mask, tensor2):
        assert not self.needs_input_grad[1], "MaskedCopy can't differentiate " \
            "the mask"
        if not self.inplace:
            tensor1 = tensor1.clone()
        else:
            self.mark_dirty(tensor1)
        self.save_for_backward(mask)
        return tensor1.masked_copy_(mask, tensor2)

    def backward(self, grad_output):
        mask, = self.saved_tensors
        grad_tensor1 = grad_tensor2 = None
        if self.needs_input_grad[0]:
            grad_tensor1 = grad_output.clone().masked_fill_(mask, 0)
        if self.needs_input_grad[2]:
            grad_tensor2 = grad_output.clone().masked_fill_(mask.eq(0), 0)
        return grad_tensor1, None, grad_tensor2

x = Variable(torch.rand(4), requires_grad=True)
y = Variable(torch.ones(4), requires_grad=True)
m = Variable(torch.ByteTensor([1, 1, 0, 1]))

z = MaskedCopy()(x, m, 2 * y)

print('x', x)
print('y', y)
print('z', z)

loss = z.sum()
loss.backward()
print('xg', x.grad)
print('yg', y.grad)

y.data.add_(y.grad.data)
```

Was there a reason that the gradient for the second argument, `y`, was supposed to be sparse?

(nudge @apaszke as he was the last one to touch that line :))

**Comment by Smerity** [comment]
To note, I ran into this whilst looking to implement zoneout re: https://github.com/pytorch/pytorch/issues/561.

For now I've avoided `current.masked_copy(noise, prev)` and am instead using `noise * current + (1 - noise) * prev` (where `noise` is a binary dropout mask containing [0, 1]).

**Comment by apaszke** [comment]
I think it's ok. The problem is in how masked_copy is defined. It doesn't copy the corresponding indices from the source tensor, but only the first #nonzero elements from the mask. 😕

**Comment by Smerity** [comment]
Gosh, thank you @apaszke for the much needed clarification on my end!

I may provide a pull request for the documentation to help others avoid my mistake.

> Copies elements from source into this tensor at positions where the mask is one. The mask should have the same number of elements as this tensor. The source should have at least as many elements as the number of ones in mask.

The first sentence can be misread as "copy elements from a given position i in B to A (i.e. A[i] = B[i])" and I assumed the last sentence meant "at least as many elements as the (maximum index of a one) in mask".

Both are me misreading the documentation but I will try to ensure others don't make my mistake. I will separately implement a function equivalent to my mental image of `masked_copy` and use that for zoneout instead :)

**Comment by apaszke** [comment]
Yes, yes. I think we should deprecate the function as it is right now and use `masked_scatter` or something similar. This behavior surprised me too a few times 😕 We'll have to discuss that, sorry for the problem!
