### ISSUE TITLE
[torch.compile] nn.Sequential not working with OptimizedModule

### ISSUE THREAD

**Issue by shingjan** [pytorch/pytorch#101165]
### 🐛 Describe the bug

My repro:

```
import torch
import torch.nn as nn
import torch._dynamo as dynamo

mod = nn.Sequential(*[nn.Linear(2,2)])

opt_mod = dynamo.optimize("eager")(mod)

inp = torch.randn(2,2)

# This works fine
for m in mod:
    inp = m(inp)

# This failed
for m in opt_mod:
    inp = m(inp)
```

stacktrace:
```
Traceback (most recent call last):
  File "test2.py", line 13, in <module>
    for m in opt_mod:
TypeError: 'OptimizedModule' object is not iterable
```

It looks like `OptimizedModule` doesn't preserve the mixin pattern of `nn.Sequential`. Is this something `torch.compile` should support?

### Versions

PyTorch version: 2.0.0a0+gitc263bd4
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070
Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by msaroufim** [comment]
The intent of an OptimizedModule is purely to call a module and print it

In this case I believe we'd instead recommend, `torch.compile()` works as well over functions

```python
import torch
import torch.nn as nn

mod = nn.Sequential(*[nn.Linear(2,2)])


@torch.compile
def seq():
  inp = torch.randn(2,2)

  for m in mod:
      inp = m(inp)

seq()
```

**Comment by shingjan** [comment]
@voznesenskym this should be sufficient. Will leave comments at #101168. which is more related if needed.
