### ISSUE TITLE
Fork run CI from upstream remote (more than 10,000 emails) 

### ISSUE THREAD

**Issue by donhuvy** [pytorch/pytorch#101184]
### 🐛 Describe the bug

Fork run CI from upstream remote

### Versions

![image](https://github.com/pytorch/pytorch/assets/1328316/45e7f6af-434f-4e4b-b609-c2c5af3554de)

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
In the meantime, you could turn off the action on your end right away by disable it on https://github.com/donhuvy/pytorch/settings/actions.  At least, it would stop the spamming.

![Screenshot 2023-05-11 at 18 36 24](https://github.com/pytorch/pytorch/assets/475357/4f43fe6d-84e8-49a3-be79-b79aacea8dc5)

**Comment by clee2000** [comment]
Closing as there is a quick solution.  For anyone facing a similar problem in the future, most jobs have `if: github.repository_owner == 'pytorch'` to stop them from running on forks, so if there is a job in particular that you keep getting notifications about, please let us know, or open a PR to add that in.
