### ISSUE TITLE
Executing `torch.cuda.is_available()` on a computer without an NVIDIA GPU will exit abnormally

### ISSUE THREAD

**Issue by djkcyl** [pytorch/pytorch#101147]
### 🐛 Describe the bug

I ran `torch.cuda.is_available()` on a computer without an nvidia graphics card, and the python process simply ended without any output

After execution I can see `WerFault` in the task manager

```
torch.cuda.is_available()
```

```
A:\Data\DDSP-SVC 3.0>python\python.exe
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.get_device_name(0)
```

### Versions

![image](https://github.com/pytorch/pytorch/assets/59153990/f1b9c31d-c09a-4b91-93d2-e79f27e5f97a)

Yes, it doesn't output anything

pytorch 2.0.1+cu118
Windows10
Python 3.10.11

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht

**Comment by Blackhex** [comment]
@cpuhrsch Can you please be a little bit more specific about the system you are running, e.g. what brand of GPU do you have?

**Comment by djkcyl** [comment]
A Lenovo office computer with no discrete graphics, only Intel core graphics (UHD 630) i5-10500

**Comment by alinpahontu2912** [comment]
@djkcyl can you tell me what command you are using to build pytorch? Since you don't have Nvidia graphics card, you can not use Cuda cores, so what do you mean by _+cu118_ ?

**Comment by alinpahontu2912** [comment]
Hello @djkcyl, in order to use Pytorch with cuda cores, you need to have an Nvidia GPU. Since you have an integrated graphics card, this will not work for you, but there is also a Pytorch CPU-ony version available [here](https://pytorch.org/get-started/locally/) so you can use that one.

**Comment by iremyux** [comment]
Closing this issue since it no longer looks relevant.
