### ISSUE TITLE
RuntimeError: Unrecognized CachingAllocator option: C

### ISSUE THREAD

**Issue by kanwalVirk** [pytorch/pytorch#101158]
### 🐛 Describe the bug

I have installed pytorch 2.0.0+cu117,torchaudio 2.0.1+cu117 for my project. Previously it was running perfect and using the gpu as well. but suddenly , it has started giving an error "Traceback (most recent call last):
  File "C:\Users\hp\PycharmProjects\Roberta_sindhiPost_processing\main.py", line 21, in <module>
    device_name = torch.cuda.get_device_name(i)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 365, in get_device_name
    return get_device_properties(device).name
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: C"

below is the code snippet:

import torch
import pandas as pd

from transformers import RobertaForMaskedLM, RobertaTokenizer,AutoConfig

from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from sklearn.preprocessing import LabelEncoder
import numpy as np
import time
import torchmetrics.functional as metrics
import torch
print(torch.cuda.is_available())
if torch.cuda.is_available():
    # Get the number of available GPUs
    device_count = torch.cuda.device_count()
    print(f"Number of available GPUs: {device_count}")

    #Iterate through each GPU and print its name
    for i in range(device_count):
        device_name = torch.cuda.get_device_name(i)
        print(f"Device {i}: {device_name}")
else:
    print("CUDA is not available")
# Read in the data from the Excel file
device = torch.device("cuda")

### Versions

import torch
import pandas as pd

from transformers import RobertaForMaskedLM, RobertaTokenizer,AutoConfig

from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from sklearn.preprocessing import LabelEncoder
import numpy as np
import time
import torchmetrics.functional as metrics
import torch
print(torch.cuda.is_available())
if torch.cuda.is_available():
    # Get the number of available GPUs
    device_count = torch.cuda.device_count()
    print(f"Number of available GPUs: {device_count}")

    #Iterate through each GPU and print its name
    for i in range(device_count):
        device_name = torch.cuda.get_device_name(i)
        print(f"Device {i}: {device_name}")
else:
    print("CUDA is not available")
# Read in the data from the Excel file
device = torch.device("cuda")

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @ngimel

**Comment by alinpahontu2912** [comment]
@kanwalVirk hello, I tried recreating the issue, but could not. Are you still dealing with it? Can you provide some more details about how you run into this issue? I would like to ask you if you tried running something else right before this code snippet, as my guess is pytorch reserved too much gpu memory and since there was no memory left, it resulted in this error.

**Comment by kanwalVirk** [comment]
Hey, thanks for reaching out!
This issue has been resolved by invalidating caches(option available in
file menu of pycharm IDE)

**Comment by alinpahontu2912** [comment]
Thank you for your reply @kanwalVirk, well noted. I believe we can now close the issue.

**Comment by HaleyBG** [comment]
I meet the question "RuntimeError: Unrecognized CachingAllocator option: 0" because pytorch is not matched with Cuda's version.
