### ISSUE TITLE
[torch.compile] Inference time accumulates over repeated calls to model

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [pytorch/pytorch#101109]
### 🐛 Describe the bug

I'm following the steps from the [torch compile tutorial](https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html).
This yields the following script:

```
import torch
torch.set_float32_matmul_precision('high')

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = torch.nn.Linear(100, 10)

    def forward(self, x):
        return torch.nn.functional.relu(self.lin(x))

mod = MyModule()
opt_mod = torch.compile(mod)
print(opt_mod(torch.randn(10, 100)))


# Returns the result of running `fn()` and the time it took for `fn()` to run,
# in seconds. We use CUDA events and synchronization for the most accurate
# measurements.
def timed(fn):
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)
    start.record()
    result = fn()
    end.record()
    torch.cuda.synchronize()
    return result, start.elapsed_time(end) / 1000

# Generates random input and targets data for the model, where `b` is
# batch size.
def generate_data(b):
    return (
        torch.randn(b, 3, 128, 128).to(torch.float32).cuda(),
        torch.randint(1000, (b,)).cuda(),
    )

N_ITERS = 10

from torchvision.models import densenet121
def init_model():
    return densenet121().to(torch.float32).cuda()


def evaluate(mod, inp):
    return mod(inp)

model = init_model()

# Reset since we are using a different mode.
import torch._dynamo
torch._dynamo.reset()

evaluate_opt = torch.compile(evaluate, mode="reduce-overhead")

inp = generate_data(16)[0]
print("eager:", timed(lambda: evaluate(model, inp))[1])
print("compile:", timed(lambda: evaluate_opt(model, inp))[1])

eager_times = []
compile_times = []
for i in range(N_ITERS):
    inp = generate_data(16)[0]
    _, eager_time = timed(lambda: evaluate(model, inp))
    eager_times.append(eager_time)
    print(f"eager eval time {i}: {eager_time}")

print("~" * 10)

compile_times = []
for i in range(N_ITERS):
    inp = generate_data(16)[0]
    _, compile_time = timed(lambda: evaluate_opt(model, inp))
    compile_times.append(compile_time)
    print(f"compile eval time {i}: {compile_time}")
print("~" * 10)

import numpy as np
eager_med = np.median(eager_times)
compile_med = np.median(compile_times)
speedup = eager_med / compile_med
print(f"(eval) eager median: {eager_med}, compile median: {compile_med}, speedup: {speedup}x")
print("~" * 10)
```

Evaluation times for the compiled version appear to pile up and as a result, are extremely slow.
Running this script for more iterations on my end shows a continuation of this behavior.

### Error logs

> 
> tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2519, 0.0000, 0.0000,
>          0.2867],
>         [1.5657, 0.0000, 0.0000, 0.0000, 0.0000, 0.3117, 0.5609, 0.0000, 1.2810,
>          0.1967],
>         [0.9423, 0.0000, 0.2721, 0.5260, 1.0152, 0.0000, 0.5620, 0.0000, 0.6227,
>          0.8371],
>         [0.0000, 0.7119, 0.3199, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
>          0.0000],
>         [0.7951, 0.0000, 0.0736, 0.0000, 0.0000, 0.2634, 1.5863, 0.0000, 0.4739,
>          0.3322],
>         [0.3439, 0.0337, 0.3078, 0.0000, 0.0000, 0.2049, 0.0000, 0.0541, 0.0000,
>          0.0000],
>         [0.2732, 1.1019, 0.0000, 0.6324, 0.0000, 0.0000, 0.0000, 0.0000, 0.1473,
>          0.0000],
>         [0.2578, 0.0000, 0.2144, 0.0851, 0.5904, 0.4402, 0.0000, 0.0000, 0.0000,
>          0.0000],
>         [0.3485, 0.0000, 0.1471, 0.0000, 0.6141, 0.0000, 0.1978, 0.0000, 0.0000,
>          0.4271],
>         [0.0000, 0.0000, 0.0000, 0.1259, 0.0000, 0.4666, -0.0000, 0.3399, 0.4941,
>          0.2402]], grad_fn=<CompiledFunctionBackward>)
> eager: 1.5149393310546875
> compile: 39.321484375
> eager eval time 0: 0.025001983642578125
> eager eval time 1: 0.027041791915893554
> eager eval time 2: 0.017296415328979492
> eager eval time 3: 0.01745715141296387
> eager eval time 4: 0.017307647705078123
> eager eval time 5: 0.017722368240356445
> eager eval time 6: 0.017344512939453126
> eager eval time 7: 0.017300479888916014
> eager eval time 8: 0.017123327255249024
> eager eval time 9: 0.017169408798217774
> ~~~~~~~~~~
> compile eval time 0: 0.41368167114257814
> compile eval time 1: 1.4542213134765625
> compile eval time 2: 2.204075927734375
> compile eval time 3: 2.96568115234375
> compile eval time 4: 3.8222724609375
> compile eval time 5: 4.544783203125
> compile eval time 6: 5.3709169921875
> compile eval time 7: 6.14615234375
> compile eval time 8: 7.1200185546875
> compile eval time 9: 7.8451650390625
> ~~~~~~~~~~
> (eval) eager median: 0.017326080322265625, compile median: 4.18352783203125, speedup: 0.004141499953605712x
> ~~~~~~~~~~

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230506+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.8 (main, Nov  4 2022, 13:48:29) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-1075-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7R32
Stepping:                        0
CPU MHz:                         3298.921
BogoMIPS:                        5599.76
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        4 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr wbnoinvd arat npt nrip_save rdpid

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0.dev20230506+cu118
[pip3] torchaudio==2.1.0.dev20230507+cu118
[pip3] torchvision==0.16.0.dev20230507+cu118
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+7d1a95b046          pypi_0    pypi
[conda] torch                     2.1.0.dev20230506+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230507+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230507+cu118          pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by ArturNiederfahrenhorst** [comment]
I should add that for the training portion of the script, I observe a significant speedup (~1.6x).
It's only the evaluation that displays such behavior.

**Comment by msaroufim** [comment]
I just tried this out, copy pasted in your code in a colab notebook with a T4 GPU and could not observe this effect

I wonder if this is an AMD CPU bug 🤔


```
eager: 7.9563837890625
compile: 76.4205234375
eager eval time 0: 0.04618108749389648
eager eval time 1: 0.033769439697265625
eager eval time 2: 0.023085439682006836
eager eval time 3: 0.02314035224914551
eager eval time 4: 0.02309529685974121
eager eval time 5: 0.025725311279296875
eager eval time 6: 0.023477279663085937
eager eval time 7: 0.03307110214233398
eager eval time 8: 0.024245248794555665
eager eval time 9: 0.024409568786621094
~~~~~~~~~~
compile eval time 0: 0.016942943572998047
compile eval time 1: 0.017201152801513672
compile eval time 2: 0.0174149112701416
compile eval time 3: 0.017115135192871094
compile eval time 4: 0.016670112609863282
compile eval time 5: 0.016529407501220703
compile eval time 6: 0.016635904312133788
compile eval time 7: 0.017121280670166016
compile eval time 8: 0.017549983978271483
compile eval time 9: 0.017198047637939452
~~~~~~~~~~
(eval) eager median: 0.02432740879058838, compile median: 0.017118207931518553, speedup: 1.421142264886036x
~~~~~~~~~~
```

**Comment by ArturNiederfahrenhorst** [comment]
I ran the same script on a different machine with the following environment:

# Environment
```
Collecting environment information...
PyTorch version: 2.1.0.dev20230506+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.8 (main, Nov  4 2022, 13:48:29) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-1075-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         3102.342
BogoMIPS:                        4999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        8 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0.dev20230506+cu118
[pip3] torchaudio==2.1.0.dev20230507+cu118
[pip3] torchvision==0.16.0.dev20230507+cu118
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+7d1a95b046          pypi_0    pypi
[conda] torch                     2.1.0.dev20230506+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230507+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230507+cu118          pypi_0    pypi
```

# Results
```
tensor([[0.2472, 0.0000, 0.0000, 0.0482, 0.0000, 0.2422, 0.0423, 0.0000, 0.1446,
         0.0000],
        [0.0000, 0.0000, 0.4590, 0.0000, 0.0000, 0.2811, 0.0068, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.3194, 0.0000, 0.0000, 1.6058, 0.2840, 0.0000, 0.0000,
         0.0000],
        [0.2472, 0.0688, 0.8910, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1523,
         0.0000],
        [0.0000, 0.0000, 0.0076, 0.2925, 0.0000, 0.0000, 0.0276, 0.0000, 0.0000,
         0.0000],
        [0.7625, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.4026,
         0.0000],
        [0.0000, 1.2170, 0.0000, 1.1033, 0.0000, 0.4615, 0.0000, 0.0267, 0.0000,
         0.0000],
        [0.0000, 0.6465, 0.0279, 0.0000, 0.0000, 0.3790, 0.5854, 0.0000, 0.2965,
         0.1342],
        [0.0000, 0.7102, 0.0000, 0.0000, 0.0000, 0.1638, 0.0000, 0.0000, 0.0000,
         0.6474],
        [0.0000, 0.0000, 0.6990, 0.0000, 0.0000, 0.0000, 0.7750, -0.0000, -0.0000,
         -0.0000]], grad_fn=<CompiledFunctionBackward>)
eager: 1.7229237060546876
compile: 79.1370078125
eager eval time 0: 0.03541980743408203
eager eval time 1: 0.03436851119995117
eager eval time 2: 0.024642911911010743
eager eval time 3: 0.02446614456176758
eager eval time 4: 0.024901952743530274
eager eval time 5: 0.025876192092895507
eager eval time 6: 0.025234367370605467
eager eval time 7: 0.024645183563232424
eager eval time 8: 0.02447974395751953
eager eval time 9: 0.024640735626220704
~~~~~~~~~~
compile eval time 0: 0.47005316162109373
compile eval time 1: 1.513473876953125
compile eval time 2: 2.26557958984375
compile eval time 3: 3.2647978515625
compile eval time 4: 4.084760498046875
compile eval time 5: 5.060740234375
compile eval time 6: 5.97577490234375
compile eval time 7: 6.9299697265625
compile eval time 8: 8.0047373046875
compile eval time 9: 8.7670224609375
~~~~~~~~~~
(eval) eager median: 0.02477356815338135, compile median: 4.572750366210938, speedup: 0.005417651559647497x
~~~~~~~~~~
```

@msaroufim Any advice on how to proceed? I'm unsure what changes I could make.

**Comment by ezyang** [comment]
@eellison could this be https://github.com/pytorch/pytorch/pull/101129 ?
