### ISSUE TITLE
Deterministic inductor triton compilation

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#101105]
### 🐛 Describe the bug

torch.use_deterministic_algorithms is extremely handy debugging tool but it does not work with the inductor/triton backend right now. We should make it work.

IIRC, @ngimel told me that there is some operation which Triton is unlikely to support in the near future, so we would have to go to fallback handwritten CUDA kernels in this case.

Some other things we'd have to expunge: Use of atomic_add in scatter/scatter_reduce

### Versions

master

cc @mruberry @kurtamohler @soumith @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by ngimel** [comment]
When `use_deterministic_algorithms` is set, inductor authomatically falls back to eager deterministic implementations of scatter/index_put and friends.

**Comment by ezyang** [comment]
So does that mean that there is nothing to do?

**Comment by ngimel** [comment]
Hopefully yes, set global deterministic mode + disable inductor autotuning produces deterministic results on the cases that we've tried.

**Comment by anijain2305** [comment]
> Hopefully yes, set global deterministic mode + disable inductor autotuning produces deterministic results on the cases that we've tried.

Setting deterministic algorithm today should even disable inductor autotuning today (this helped reduce flakiness in `sebotnet` model)

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/issues/94855 complaining about a nondeterminism case; may or may not have been fixed in the meantime.

**Comment by ngimel** [comment]
Tentatively closing, if there's still unexpected nondeterministic computation please reopen
