### ISSUE TITLE
Cmakelist Architecture and c code modification

### ISSUE THREAD

**Issue by zsk423200** [pytorch/pytorch#10111]
hello, i want to add some print info in c code, but i am not clear the cmakelist architecture, and how to use which cmakelist to compile the cpp which i have modified. for example, i want to compile DataChannelGloo.cpp, which cmakelist i should use.
document is best.

**Comment by ezyang** [comment]
Please see https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for up to date instructions on how to build PyTorch.
