### ISSUE TITLE
bug report: out of memory when using torchvision.models.densenet169 with drop_rate

### ISSUE THREAD

**Issue by StephenChou0119** [pytorch/pytorch#10116]
## Issue description
out of memory when using torchvision.models.densenet169 with drop_rate = 0.2 even batchsize =1.
when check the memory usage with 'nvidia-smi', the number  increases slowly, it may be related to the 'inplace' parameter of F.dropout. 
when drop_rate = 0.0, there is no exception.
## Code example
drop_rate = 0.2
model_ft = models.densenet169(pretrained=True, drop_rate=drop_rate)
## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080

Nvidia driver version: 390.59
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.1.2
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.14.0)
[pip3] numpydoc (0.7.0)
[conda] pytorch                   0.4.0            py36hdf912b8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] torchvision               0.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by SsnL** [comment]
When dropout > 0, we have to save the mask for backward, and hence use more memory. So you probably were right on the edge before using dropout. This is expected.
