### ISSUE TITLE
[ONNX] OnnxFunction of aten_index_put_bool operation isn't consistent to aten::index_put inx FX exporter

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#101150]
### 🐛 Describe the bug

Need below in `test_fx_op_consistency.py`

```python
    xfail(
        "index_put",
        matcher=lambda sample: (sample.args[0][0].dtype == torch.bool) and (sample.kwargs.get("accumulate") == False),
        reason=onnx_test_common.reason_dynamo_does_not_support("Unknown reason!"),
    ),
```

However, the ops_test.py of this OnnxFunction is actually passed.

cc @justinchuby 

### Versions

Nightly

**Comment by justinchuby** [comment]
What was the error?

**Comment by justinchuby** [comment]
Thanks, it is now being fixed by @fatcat-z

**Comment by fatcat-z** [comment]
> Thanks, it is now being fixed by @fatcat-z

This is index_put op, not index op with bool parameter which is I'm working on.
