### ISSUE TITLE
Argument "device" in torch.tensor() behaves differently than that described in doc

### ISSUE THREAD

**Issue by Z-2ez4U** [pytorch/pytorch#101274]
### 📚 The doc issue

The doc says "if device=None and data is not a tensor then the result tensor is constructed on the CPU". But after calling "torch.set_default_device(torch.device('cuda'))", torch.tensor(device=None) will convert a numpy array into a GPU tensor.

### Suggest a potential alternative/fix

Maybe "If None, uses the current device for the default tensor type", the description consistent with other functions in [Creation Ops](https://pytorch.org/docs/stable/torch.html#creation-ops).

cc @svekars @carljparker

**Comment by albanD** [comment]
Hi,
We indeed missed updating this doc after adding the default device API.
We would accept a PR updating this!

**Comment by Z-2ez4U** [comment]
> Hi, We indeed missed updating this doc after adding the default device API. We would accept a PR updating this!

Thx! I found the same issue in doc of "tensor.as_tensor()".
