### ISSUE TITLE
Should be ok to call _dynamo.export and torch.compile under FakeTensorMode

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#101288]
### 🐛 Describe the bug

This will require either: (1) ensuring that the eval frame handler disables fake tensor mode before doing anything serious, or (2) we refactor all of Dynamo to work if there is a fake tensor mode or not. Probably (1) is easiest.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @anijain2305 @Xia-Weiwen @desertfire @thiagocrepaldi 

### Versions

master

**Comment by BowenBao** [comment]
IIRC this is completed?
