### ISSUE TITLE
aten_op in Caffe2 doesn't correctly track dependencies

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#10127]
Steps to reproduce:
1. Check out 685224aa14b59d011d0926d615846a60f138e4ba
2. Do a full build with `FULL_CAFFE2=1 python setup.py build_deps develop`
3. Update to 4070005081f9bc5f00d10793daf9c41056f4f7fb 
4. Try a rebuild with `FULL_CAFFE2=1 python setup.py build_deps develop`

It fails saying:

```
./caffe2/contrib/aten/aten_op.h: In lambda function:
./caffe2/contrib/aten/aten_op.h:6236:33: error: ‘thnn_grid_sampler_bilinear3d’ is not a member of ‘at’
               auto the_result = at::thnn_grid_sampler_bilinear3d(self, grid, padding_mode);
```

It looks like `aten_op.h` did not get regenerated.

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
This is still not fixed.

**Comment by SsnL** [comment]
Yes. This seems 90% times be the reason that I have to clean before rebuilding.

**Comment by rohan-varma** [comment]
Having the same issue right now as well.

**Comment by ezyang** [comment]
declassifying as caffe2 as this affects normal pytorch builds

**Comment by ngoldbaum** [comment]
I'm not able to reproduce this using the steps in the issue description because of https://github.com/pytorch/pytorch/issues/19457. Is there by any chance a more up-to-date pair of commits to use to reproduce this issue?

**Comment by ezyang** [comment]
I think you could probably reproduce this by writing a commit that adds a new native function, doing a build, then deleting that new native function and rebuilding.
