### ISSUE TITLE
load model with pytorch0.4 with model saved with pytorch0.3

### ISSUE THREAD

**Issue by xiaopuLee** [pytorch/pytorch#10120]
When I load the weight saved with pytorch0.3  with pytorch 0.4.
I met this exceptions.

RuntimeError: storages don't support slicing

import torch
import sys
cp = torch.load(<model_saved_from_pytorch_0.3>, map_location=lambda storage, loc: storage)

how can I fix this?
please help me.

**Comment by ailzhang** [comment]
Could you give an simple model that trigger this? Thanks

**Comment by zou3519** [comment]
Are you on 0.4.1?

**Comment by Grzego** [comment]
I experienced the same issue. I got the same error:
`RuntimeError: storages don't support slicing`.

I believe this line is responsible: https://github.com/pytorch/pytorch/blob/master/torch/serialization.py#L513

Is there a quick fix to this issue?

**Comment by hyperfraise** [comment]
Same problem here, would very much like a solution :D

**Comment by ailzhang** [comment]
@Grzego  @hyperfraise  could any of you provide a simple repro script for this issue? Thanks!

**Comment by Grzego** [comment]
@ailzhang [Here is a gist (model file is on google drive, link in gist)](https://gist.github.com/Grzego/c7b93447f382e4d7437a596abadae4a2). Hope this helps!

**Comment by hyperfraise** [comment]
Also doesn't work with 0.4.0

**Comment by hyperfraise** [comment]
For those who are compelled to use cuda 9.2, and thus pytorch 0.4.1 you can actually install pytorch 0.4.0 to read your former models with this command 

'''
pip3 install http://download.pytorch.org/whl/cu91/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
'''
Fortunately, it does work with cuda 9.2

**Comment by hyperfraise** [comment]
Also, I tried modifying torch/serialization.py and change this


`                    deserialized_objects[view_key] = storage[offset:offset + view_size]`
into this
`                    deserialized_objects[view_key] = torch.Storage([storage[x] for x in range(offset,offset + view_size)])`
It loads zithout error, but the model doesn't produce the right outputs.

**Comment by ezyang** [comment]
Minimal repro:

```
# From PyTorch 0.3
import torch

t = torch.zeros(4);
s1 = t.storage()[:2]
s2 = t.storage()[2:]
torch.save([s1, s2], 'foo.ser')
```

then:

```
# From master
import torch
torch.load("foo.ser")
```

**Comment by ezyang** [comment]
Or, if at all possible, if you could upload/send me one of the saved models, that would be very helpful.

**Comment by ailzhang** [comment]
@ezyang There's one saved model from @Grzego 's gist. 
https://drive.google.com/open?id=1su6Dk0PkSfVXT0FUabc4fi-_pqI1RLgV
I can repro the issue with his script & model.

**Comment by ezyang** [comment]
Here is a workaround that might help. I need to make sure it doesn't leak memory though:

```
diff --git a/torch/csrc/generic/Storage.cpp b/torch/csrc/generic/Storage.cpp
index 94c0b85bd..f7708978e 100644
--- a/torch/csrc/generic/Storage.cpp
+++ b/torch/csrc/generic/Storage.cpp
@@ -160,8 +160,32 @@ static PyObject * THPStorage_(get)(THPStorage *self, PyObject *index)
     return THPUtils_(newReal)(value);
   /* Slice index */
   } else if (PySlice_Check(index)) {
-    THPUtils_setError("storages don't support slicing");
-    return nullptr;
+    Py_ssize_t start, stop, slicelength, step;
+    int64_t len = THWStorage_(size)(LIBRARY_STATE self->cdata);
+    if (!THPUtils_parseSlice(index, len, &start, &stop, &step, &slicelength))
+      return NULL;
+    if (step != 1) {
+      THPUtils_setError("Trying to slice with a step of %" PRId64 ", but only a step of "
+          "1 is supported", (int64_t)step);
+      return NULL;
+    }
+
+    scalar_t *data = THWStorage_(data)(LIBRARY_STATE self->cdata);
+
+    at::StorageImpl* old_storage = self->cdata;
+    c10::raw::intrusive_ptr::incref(old_storage);
+    at::Storage new_storage(c10::make_intrusive<at::StorageImpl>(
+      old_storage->dtype(),
+      slicelength,
+      at::DataPtr(static_cast<void*>(data + start),
+                  old_storage,
+                  [](void* s) { c10::raw::intrusive_ptr::decref(static_cast<at::StorageImpl*>(s)); },
+                  old_storage->device()),
+      nullptr,
+      false));
+
+    PyObject *_ret = THPStorage_(New)(new_storage.unsafeReleaseStorageImpl());
+    return _ret;
   }
   PyErr_Format(PyExc_TypeError, "can't index a " THPStorageStr " with %s",
       THPUtils_typename(index));
```

**Comment by ezyang** [comment]
@hyperfraise When you loaded your model after applying your workaround (which should have worked, by the way), did you train it more, or were the weights frozen at that point?

**Comment by ezyang** [comment]
I'm still interested in knowing if your models behave differently after this change. Shout if that's the case.

**Comment by hyperfraise** [comment]
I saved the model jsut like outlined in the pytorch official guideline. I save the `.state_dict()`, as well as the optimizer state_dict and some integers stating the number of epoch, iterations...

**Comment by hyperfraise** [comment]
@ezyang I loaded the model for inference, but couldn't due to this error. I didn't try training it further.

**Comment by hyperfraise** [comment]
To use master need I compile pytorch from source ? I always pip install from pytorch.org
