### ISSUE TITLE
Faketensor error when add new backend for pytorch

### ISSUE THREAD

**Issue by tianxiangsong** [pytorch/pytorch#101244]
### 🐛 Describe the bug

We choose PrivateUse1 to prototype our customized backend, when test faketesor, it is error.

example:
`import torch
from torch._subclasses.fake_tensor import FakeTensorMode
with FakeTensorMode():
       a = torch.ones([10], device=“new_device”)
       b = torch.ones([10], device=“new_device”)
       c = a + b
print(c)`

error:
RuntimeError: Failed running call_method add(*(FakeTensor(FakeTensor(…, device=‘meta’, size=(1, 3, 5, 5)), new_device:0), FakeTensor(FakeTensor(…, device=‘meta’, size=(1, 3, 5, 5)), new_device:0)), **{}):

tensor’s device must be meta, got new_device instead

### Versions

Collecting environment information...
PyTorch version: 2.0.0a0+gitc8632cb
Is debug build: True
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.0 (default, Nov 15 2020, 14:28:56)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.4.152
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           151
Model name:                      12th Gen Intel(R) Core(TM) i5-12400
Stepping:                        2
CPU MHz:                         3400.000
CPU max MHz:                     4400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4992.00
Virtualization:                  VT-x
L1d cache:                       288 KiB
L1i cache:                       192 KiB
L2 cache:                        7.5 MiB
L3 cache:                        18 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.0a0+gitc8632cb
[pip3] torch-musa==2.0.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.24.3           py39h14f4228_0
[conda] numpy-base                1.24.3           py39h31eccc5_0
[conda] torch                     2.0.0a0+gitc8632cb          pypi_0    pypi
pure virtual method called
terminate called without an active exception
Aborted (core dumped)

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by Yepgang** [comment]
### 🐛 Describe the bug

It seems that there is a problem with the PrivateUse1's support for faketensor

##case1: test 'new_device' with torch.compile()
```python
import torch

class SimpleModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x, y):
        r0 = x.add(y)
        return r0

device = 'new_device'
lhs = torch.randn(1, 3, 5, 5).to(device)
rhs = torch.randn(1, 3, 5, 5).to(device)

mod = SimpleModule().to(device)
optimized_mod = torch.compile(mod)

res = optimized_mod(lhs, rhs)
res.to('cpu')
print(f'res_shape={res.shape}\noptimized_res={res}')
```
error:
```
Traceback (most recent call last):
  File "/path-to-torch/torch/_dynamo/utils.py", line 1196, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "/path-to-torch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/path-to-torch/torch/_subclasses/fake_tensor.py", line 987, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/path-to-torch/torch/_subclasses/fake_tensor.py", line 1176, in dispatch
    return self.wrap_meta_outputs_with_default_device_logic(r, func, args, kwargs)
  File "/path-to-torch/torch/_subclasses/fake_tensor.py", line 1232, in wrap_meta_outputs_with_default_device_logic
    return tree_map(partial(wrap), r)
  File "/path-to-torch/torch/utils/_pytree.py", line 196, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/path-to-torch/torch/utils/_pytree.py", line 196, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/path-to-torch/torch/_subclasses/fake_tensor.py", line 1260, in wrap
    return converter.from_meta_and_device(
  File "/path-to-torch/torch/_subclasses/fake_tensor.py", line 288, in from_meta_and_device
    assert (
AssertionError: tensor's device must be `meta`, got new_device instead

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path-to-torch/torch/_dynamo/utils.py", line 1152, in get_fake_value
    return wrap_fake_exception(
  File "/path-to-torch/torch/_dynamo/utils.py", line 808, in wrap_fake_exception
    return fn()
  File "/path-to-torch/torch/_dynamo/utils.py", line 1153, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/path-to-torch/torch/_dynamo/utils.py", line 1206, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_method add(*(FakeTensor(FakeTensor(..., device='meta', size=(1, 3, 5, 5)), new_device:0), FakeTensor(FakeTensor(..., device='meta', size=(1, 3, 5, 5)), new_device:0)), **{}):
tensor's device must be `meta`, got new_device instead
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/host/workspace/mt-pytorch/grace/debug.py", line 27, in <module>
    res = optimized_mod(lhs, rhs)
  File "/path-to-torch/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path-to-torch/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/path-to-torch/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/path-to-torch/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/path-to-torch/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/path-to-torch/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/path-to-torch/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/path-to-torch/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/path-to-torch/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/path-to-torch/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/path-to-torch/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/path-to-torch/torch/_dynamo/symbolic_convert.py", line 1726, in run

Aborted (core dumped)
```

##case2: test 'new_device' with fake tensor

``` python
import torch
from torch._subclasses.fake_tensor import FakeTensorMode

device = 'new_device'

with FakeTensorMode():
    x = torch.empty(1).to(device)
    y = torch.empty(1).to(device)
    z = x + y

print(z)
```

error
```
Traceback (most recent call last):
  File "faketensor.py", line 15, in <module>
    z = x + y
  File "/path-to-torch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/path-to-torch/torch/_subclasses/fake_tensor.py", line 987, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/path-to-torch/torch/_subclasses/fake_tensor.py", line 1176, in dispatch
    return self.wrap_meta_outputs_with_default_device_logic(r, func, args, kwargs)
  File "/path-to-torch/torch/_subclasses/fake_tensor.py", line 1232, in wrap_meta_outputs_with_default_device_logic
    return tree_map(partial(wrap), r)
  File "/path-to-torch/torch/utils/_pytree.py", line 196, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/path-to-torch/torch/utils/_pytree.py", line 196, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/path-to-torch/torch/_subclasses/fake_tensor.py", line 1260, in wrap
    return converter.from_meta_and_device(
  File "/path-to-torch/torch/_subclasses/fake_tensor.py", line 288, in from_meta_and_device
    assert (
AssertionError: tensor's device must be `meta`, got new_device instead

Aborted (core dumped)
```

### Versions

PyTorch version: 2.0.0a0+git3d12f52
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 14.0.0 (git@github.mthreads.com:mthreads/mtcc.git 4ec302eea3b975b9d3ae73bd44cee1fd3fe0453a)
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.4.152
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           151
Model name:                      12th Gen Intel(R) Core(TM) i5-12400
Stepping:                        2
CPU MHz:                         3400.000
CPU max MHz:                     4400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4992.00
Virtualization:                  VT-x
L1d cache:                       288 KiB
L1i cache:                       192 KiB
L2 cache:                        7.5 MiB
L3 cache:                        18 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.0a0+git3d12f52
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.0.0a0+git3d12f52          pypi_0    pypi

**Comment by albanD** [comment]
cc @ezyang

**Comment by ezyang** [comment]
Actually, @eellison, could you take a first look here? Feel free to bat it back to me if needed.

**Comment by eellison** [comment]
sorry missed this earlier but i'll take a look!

**Comment by eellison** [comment]
@tianxiangsong would you check if fixes the error: 

```
diff --git a/c10/core/DispatchKey.h b/c10/core/DispatchKey.h
index 40be3f9dc5d..781d47840c0 100644
--- a/c10/core/DispatchKey.h
+++ b/c10/core/DispatchKey.h
@@ -40,11 +40,11 @@ namespace c10 {
   _(HPU, extra)                                 \
   _(VE, extra)                                  \
   _(Lazy, extra)                                \
-  _(Meta, extra)                                \
   _(MTIA, extra)                                \
   _(PrivateUse1, extra)                         \
   _(PrivateUse2, extra)                         \
-  _(PrivateUse3, extra)
+  _(PrivateUse3, extra)                         \
+  _(Meta, extra)
 
 // WARNING!  If we add a new per-backend functionality key that has higher
 // priority than Autograd, then make sure you update EndOfRuntimeBackendKeys
```

**Comment by tianxiangsong** [comment]
> @tianxiangsong would you check if fixes the error:
> 
> ```
> diff --git a/c10/core/DispatchKey.h b/c10/core/DispatchKey.h
> index 40be3f9dc5d..781d47840c0 100644
> --- a/c10/core/DispatchKey.h
> +++ b/c10/core/DispatchKey.h
> @@ -40,11 +40,11 @@ namespace c10 {
>    _(HPU, extra)                                 \
>    _(VE, extra)                                  \
>    _(Lazy, extra)                                \
> -  _(Meta, extra)                                \
>    _(MTIA, extra)                                \
>    _(PrivateUse1, extra)                         \
>    _(PrivateUse2, extra)                         \
> -  _(PrivateUse3, extra)
> +  _(PrivateUse3, extra)                         \
> +  _(Meta, extra)
>  
>  // WARNING!  If we add a new per-backend functionality key that has higher
>  // priority than Autograd, then make sure you update EndOfRuntimeBackendKeys
> ```

We have been using it in this way, it is useful. Thank you!

**Comment by tianxiangsong** [comment]
> 

if you change you local "DispatchKey.h" file, it is neccessary for you to re-compile pytorch.
