### ISSUE TITLE
version 0.4.1 torch.arange dtype change

### ISSUE THREAD

**Issue by jt120** [pytorch/pytorch#10122]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
in version 0.4.1 torch.arange dtype change, so the toturial at 
https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#define-the-network
cannot work

we need update the docu on upper url

## Code example
loss = nn.MSELoss()
input = torch.autograd.Variable(torch.randn(10))
target = torch.arange(1, 11)
#target = torch.arange(1, 11,dtype=torch.float32)
#default dtype of torch.arange change for 0.4.1, in 0.4.0, default is torch.float32, but in 0.4.1, default is torch.int32
output = loss(input, target)
print(output)

these code would throw blew error

> RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'target'

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS: windows 7
- PyTorch version: 0.4.1
- Python version: 3.6
- CUDA/cuDNN version: None
- GPU models and configuration: None
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by SsnL** [comment]
Thanks for reporting! Tutorials are updated now. :)
