### ISSUE TITLE
Docker container PyTorch v2.0.1 missing on Docker Hub

### ISSUE THREAD

**Issue by janvdp** [pytorch/pytorch#101267]
### 🐛 Describe the bug

Currently, there is no [Docker container on Docker Hub](https://hub.docker.com/r/pytorch/pytorch/tags) for the [latest stable version of PyTorch (v2.0.1)](https://pytorch.org/get-started/locally/)

### Versions

v2.0.1 

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by malfet** [comment]
Please note, that there is one on ghcr, but we should mirror to Docker:
https://github.com/orgs/pytorch/packages/container/package/pytorch

**Comment by atalman** [comment]
@janvdp can you please try
```
docker pull ghcr.io/pytorch/pytorch:2.0.1-runtime
or 
docker pull ghcr.io/pytorch/pytorch:2.0.1-devel
```

Please let us know if you have issue using docker images from this location

**Comment by escape0707** [comment]
I've tested the new docker image and:

```
$ python --version
Python 3.10.11
$ pip show torch
Name: torch
Version: 2.0.0
```

Plus `vscode-cli` can't run:

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
$ .bin/code --version
.bin/code: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by .bin/code)
.bin/code: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by .bin/code)
```

Can we update the based Linux distro, too?

**Comment by atalman** [comment]
hi @escape0707 and @janvdp sorry about this, we just regenerated the image which uses latest pytorch 2.0.1 you can get it from here: https://github.com/orgs/pytorch/packages/container/package/pytorch

Will update Linux distro as well once this PR is cherry-picked into release: https://github.com/pytorch/pytorch/pull/101301

**Comment by escape0707** [comment]
Thanks for the update! I'm ready to test it once the image based on Ubuntu 20.04 is out.

**Comment by escape0707** [comment]
`pip show torch` now gives 2.0.1 but `cat /etc/os-release` still gives Ubuntu Bionic and vscode-cli still can't run.

**Comment by escape0707** [comment]
@malfet Did anything go wrong with the Docker build action? It's been over 1 hour https://github.com/pytorch/pytorch/actions/runs/4963298691/jobs/8882390753

**Comment by malfet** [comment]
@escape0707 looks like it's hanging in `tzdata.postinst configure` trying to recall env var to force it to be a non-interactive session
```
/usr/bin/perl -w /usr/share/debconf/frontend /var/lib/dpkg/info/tzdata.postinst configure
```

**Comment by escape0707** [comment]
Maybe I don't have the permission to see where the Action got hanged... I can't expand that step `Run docker build / push` to see the details.

**Comment by malfet** [comment]
@escape0707 I've cancelled the workflow, you should be able to see it now

**Comment by escape0707** [comment]
@malfet Thanks for the maintenance! I can finally tell my classmates to use vscode-cli in our shared server!

```
Apptainer> cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
...
Apptainer> .bin/code --version
code-cli 1.78.0 (commit 252e5463d60e63238250799aef7375787f68b4ee)
```

**Comment by malfet** [comment]
> I can finally tell my classmates to use vscode-cli in our shared server!
<sarcasm>What have I done!?! As result of my actions some it might take longer for some to discover the joy of vim</sarcasm>

**Comment by malfet** [comment]
@atalman please feel free to promote ghcr image to Docker Hub

**Comment by escape0707** [comment]
> What have I done!?! As result of my actions some it might take longer for some to discover the joy of vim

LOL, I like vim, too. But a normie old friend of my simply won't learn is and use Nano and VSCode with copilot :facepalm: ... I take being able to let him use containers rather than mixing very kind of python package installation method like https://xkcd.com/1987/ as a huge win XD

**Comment by atalman** [comment]
Docker container are also uploaded to our usual repo:
https://hub.docker.com/repository/docker/pytorch/pytorch
Closing this issue
