### ISSUE TITLE
torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment.

### ISSUE THREAD

**Issue by hhswgww** [pytorch/pytorch#101255]
### 🐛 Describe the bug

 ERROR：torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment, Please use functorch.experimental.control_flow.cond to explicitly capture the control flow

i am trying to use a torch(2.1.0.dev20230510+cu118) dynamo export a function with control flow. The relevant code is as follows，interesting thing is： when the control condition is “if b.dim < 0:”， it works fine； if the control condition is “if b.sum() < 0:”， the error comes as  " torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment, Please use functorch.experimental.control_flow.cond to explicitly capture the control flow "。（The relevant situation is basically consistent with the description in the link ：https://pytorch.org/functorch/nightly/ux_limitations.html）

when i try to find how to use functorch.experimental.control_flow.cond,i found the document is empty。how can i get 
instructions for  this function？

~~~
from typing import List
import torch
import torch._dynamo as dynamo

def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.tensor]):
    print("my_compiler() called with FX graph:")
    gm.graph.print_tabular()
    return gm.forward

@dynamo.optimize(my_compiler)
def foo(a, b):
    x = a/(torch.abs(a)+1)
    if b.sum() < 0:
    # if b.dim < 0:
        b = b*-1
    else:
        b = b-1
    return x*b

graph, guards=torch._dynamo.export(foo,torch.rand(10),torch.rand(10))
print("the output is:---------------------------------------------")
print(guards) 
~~~
<img width="988" alt="image" src="https://github.com/pytorch/pytorch/assets/51430740/2cb9a50c-593a-4827-bc28-70307e83d912">

### Versions

torch 2.1.0 20230510;cuda 11.8

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by voznesenskym** [comment]
Set dynamic=True :)

**Comment by ezyang** [comment]
@voznesenskym uhhh, no? You need torch.cond for this

There are a bunch of examples of using cond() in test/dynamo/test_export.py, take a look and see if you can figure it out.

cc @zou3519 do we have plans for docs on these

**Comment by zou3519** [comment]
> cc @zou3519 do we have plans for docs on these

Not yet. Maybe after we decide on what the API should look like and kick them to a namespace that is not under functorch (import functorch is deprecated)

**Comment by hhswgww** [comment]
@ezyang I have found the corresponding usage example in test/dynamo/test_export.py , thanks a lot.
