### ISSUE TITLE
quantizedCPU maxpool3d

### ISSUE THREAD

**Issue by OldaKodym** [pytorch/pytorch#101386]
### 🚀 The feature, motivation and pitch

I am working on a quantized 3D U-net architecture.  However, tracing a quantization-aware trained model is not possible because the 3D maxpooling op seems to be not implemented for quantizedCPU backend. Since similar modules like 2D maxpool/3D avgpool are implemented, I don't see a particular reason why 3D maxpool shouldn't be as well.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by leslie-fang-intel** [comment]
@OldaKodym I will take a look of this Issue. If you can provide test case to reproduce this issue would be helpful.

**Comment by OldaKodym** [comment]
@leslie-fang-intel  Thanks! Here you go.

```
import torch


class ModelWithMaxPool(torch.nn.Module):
    def __init__(self):
        super(ModelWithMaxPool, self).__init__()
        self.mp = torch.nn.MaxPool3d(2)
        self.quant = torch.quantization.QuantStub()
        self.dequant = torch.quantization.DeQuantStub()
        self.qconfig = torch.quantization.get_default_qat_qconfig('qnnpack')

    def forward(self, x):
        x = self.quant(x)
        x = self.mp(x)
        x = self.dequant(x)
        return x


model = ModelWithMaxPool()
torch.quantization.prepare_qat(model, inplace=True)
model = torch.ao.quantization.convert(model)
traced_model = torch.jit.trace(model, torch.randn(1, 1, 32, 32, 32))
```

Will throw 
```
NotImplementedError: Could not run 'aten::max_pool3d_with_indices' with arguments from the 'QuantizedCPU' backend. ...
```

Switching to 2D, tracing runs fine.

**Comment by jerryzh168** [comment]
looks like this is fixed, please feel free to reopen if not
