### ISSUE TITLE
All performance improvements for older GPU's have been erased. 

### ISSUE THREAD

**Issue by pflky** [pytorch/pytorch#101342]
### 🐛 Describe the bug

Using a 1080ti, and Torch 2.x, older CUDA architectures like 6.1, are seeing all performance increases completely evaporated.  Used to get nearly double the speed.

### Versions

Pytorch 2.x

cc @ngimel

**Comment by zou3519** [comment]
Do you have a self-contained script which we could use to reproduce the problem?

**Comment by pflky** [comment]
I'm not sure what you mean by self contained script. I also noticed an odd behavior of processing taking vastly different times with each generation using Stable Diffusion. The first generation takes about 13-16 seconds, and then bounces around from 10-12 seconds with each generation after.  Previously, FP32 generations took around 6 seconds on the 1080ti, and 8 seconds with FP16. Now it's 9-10 seconds on FP32, and 10-12 on FP16. 

Of course, the caveat for the 1080ti specifically is that it has higher FP32 performance because FP16 is weak on that card, to explain just in case one might expect FP16 to have higher performance since newer cards tend to have stronger FP16 performance. 

I've tried every variation of launch arguments to try to see the old performance level, but with no luck. And as far as I'm aware, nothing itself has changed with Automatic1111 itself to cause such a loss in performance, so I think the main culprit is Pytorch 2.0.1 itself. 

I know Pytorch is supposed to be backwards compatible and set to build itself based on the CUDA architecture the GPU supports, but maybe there's an issue going on with that, where it's not building for the proper CUDA architecture or something is preventing it from operating properly on CUDA architectures (such as Computer 6.1)

**Comment by ngimel** [comment]
Self contained script means the script that can be run on its own and will demonstrate better perf on previous pytorch versions. You could also profile your benchmarks on old and new versions and see where are the differences https://pytorch.org/docs/stable/profiler.html?highlight=profiler+profile#torch.profiler.profile
