### ISSUE TITLE
DTensor __torch_dispatch__ not called for custom ops

### ISSUE THREAD

**Issue by ashari4** [pytorch/pytorch#101322]
### 🐛 Describe the bug

`DTensor.__torch_dispatch__ ` is not called when invoking a custom op with a C++ implementation that's registered using the `TORCH_LIBRARY` API.

Instead, the C++ implementation, which expects a regular `torch.Tensor` instead of a `DTensor`, is directly called. 

repro:

```
cpu_mesh = DeviceMesh('cpu', [0, 1])
global_x = torch.rand(256, 256)
global_w = torch.rand(256, 256)
global_b = torch.rand(256)

dist_x = distribute_tensor(global_x, cpu_mesh, [Replicate()])
dist_w = distribute_tensor(global_w, cpu_mesh, [Replicate()])
dist_b = distribute_tensor(global_b, cpu_mesh, [Replicate()])

result1 = torch.nn.functional.linear(dist_x, dist_w, dist_b) #  hits DTensor.__torch_dispatch__ as expected
result2 = custom_op(dist_x, dist_w, dist_b) # never hits DTensor.__torch_dispatch__. Directly hits the C++ implementation
```

`DTensor.__torch_dispatch__` is hit as expected when running `torch.nn.functional.linear`:

```
__torch_dispatch__ (\home\ashari\pytorch\torch\distributed\_tensor\api.py:225)
__torch_function__ (\home\ashari\pytorch\torch\_tensor.py:1298)
```

However, `DTensor.__torch_dispatch__` is not hit when running `custom_op`:

```
__call__ (\home\ashari\pytorch\torch\_ops.py:646)
__torch_function__ (\home\ashari\pytorch\torch\_tensor.py:1298)
__call__ (\home\ashari\pytorch\torch\_ops.py:646)
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git516d667
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
Clang version: Could not collect
CMake version: version 3.25.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz
Stepping:                        7
CPU MHz:                         4301.596
CPU max MHz:                     4600.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        7599.80
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        6 MiB
L3 cache:                        8.3 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.1.0a0+git54c27bf
[conda] Could not collect

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by albanD** [comment]
Hi,
It depends how your custom op is registered!
In particular you need to make sure that you actually hit the backend keys and don't stop "too early". The loose ordering within the dispatcher is AMP -> Autograd (including CompositeImplicitAutograd) -> TorchDispatch -> Backends

**Comment by ashari4** [comment]
it looks like i dont need to explicitly register the python dispatch key; that happens automatically when i define a non-trivial `__torch_dispatch__` function. 

the issue ended up being that i implicitly registered my custom op with the AutogradOther dispatch key:

```
TORCH_LIBRARY(custom_ops, m) {
m.def("custom_op", TORCH_FN(my_func));
}
```

the fix was to register my backend implementation only with a specific dispatch key and not AutogradOther:

```
TORCH_LIBRARY_IMPL(custom_ops, CUDA, m) {
m.impl("custom_op", TORCH_FN(my_func));
}

```
