### ISSUE TITLE
[Performance Issue] Inference time increases on CPU the more you train the model on a TitanX.

### ISSUE THREAD

**Issue by hagerrady13** [pytorch/pytorch#10140]
I have a [UNet model](https://github.com/milesial/Pytorch-UNet/blob/master/unet/unet_model.py) that I train on a [2x80x608] image. The model is trained on a TitanX pascal GPU for 100 epochs. When I test the trained model on a an intel i5 machine with no gpu, inference time grows as I train the model for more epochs. 
For instance, I get 500 ms if I load a checkpoint trained for 10 epochs while i get 5 seconds if I load another checkpoint saved after 100 epochs. This is not exclusive to the intel i5 cpu and the same behavior still holds on a Xeon CPU. 

Note that the checkpoint sizes are the same no matter what epoch it is saved at.

**Can anyone explain this behavior?**

System Info:
- PyTorch is installed with Conda, version 0.4
- Ubuntu 16
- CUDA 9.0 and cuDNN 7.1
- Python version: 3.6

**Comment by vadimkantorov** [comment]
Or maybe flush denorm issue?

**Comment by hagerrady13** [comment]
@soumith I ran the anomaly detection on different checkpoints and on the whole training process but got no evidence of having nans in my model.

**Comment by soumith** [comment]
@hagerrady13 that's suspicious. Do you see the memory of the process increasing over time? maybe that can explain the slowdown

**Comment by hagerrady13** [comment]
@apaszke Is [this ](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Context.cpp) what you are talking about? How do I use it to be enabled on a CPU?

**Comment by vadimkantorov** [comment]
@hagerrady13 For enabling flushing denormalized values that slow down CPU, you may check out https://pytorch.org/docs/stable/torch.html?highlight=set_flush#torch.set_flush_denormal

**Comment by vadimkantorov** [comment]
@somith @apaszke Cuda compiler can also accept `-ftz=true`, but it seems no way to enable it at runtime :(

**Comment by hagerrady13** [comment]
Yes @vadimkantorov , [that](https://pytorch.org/docs/stable/torch.html?highlight=set_flush#torch.set_flush_denormal) was the solution!! 
I enabled "set_flush_denorm" in case of CPU and now different checkpoints have the same inference time. Many thanks!
