### ISSUE TITLE
Fused Adam on large model gives CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by johnc-keen** [pytorch/pytorch#101449]
### 🐛 Describe the bug

```python
# RuntimeError: CUDA error: an illegal memory access was encountered
# happens on iteration 3 if fused=True on the Adam optimizer
# Happens with 3B or 4B parameters, but not 1B.
#
# Tested on A100 80GB
#
# Nvidia Pytorch container 23.04-py3
# https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch
#
# torch version:  2.1.0a0+fe05266
# cuda version :  12.1
# cudnn version:  8900

use_fused = True

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

import torch
import torch.nn as nn
import torch.nn.functional as F

class DenseNet(nn.Module):
    def __init__(self, in_dim, out_dim, max_parameters, increment, final_bias=True):
        super().__init__()        
        total_parameters = 0
        dim = in_dim
        self.linear_layers = nn.ParameterList()
        bias = False
        while total_parameters < max_parameters:
            if total_parameters + dim * increment + (dim + increment) * out_dim >= max_parameters:
                break
            self.linear_layers.append(nn.Linear(dim, increment, bias=bias) )
            total_parameters += dim * increment
            dim += increment
        self.num_acts = dim
        self.final_layer = nn.Linear(dim, out_dim, bias=final_bias)
        
    def forward(self, x):
        input = x
        for layer in self.linear_layers:
            x2 = layer(x)
            x2 = F.relu(x2)
            x = torch.cat( (x,x2), dim=1 )                
        x = self.final_layer(x)        
        return x

dev = 'cuda'    
frame_width = 64
frame_height = 32
image_channels = 3
frame_size = frame_width*frame_height
observation_size = 256
fovea = 16    
batch = 1

print('torch version: ', torch.__version__)
print('cuda version : ', torch.version.cuda)
print('cudnn version: ', torch.backends.cudnn.version())

print('building model')
reconstruct_parms = 3_000_000_000
reconstruct_step = 256
weights_model = DenseNet(2, observation_size * frame_size, reconstruct_parms, reconstruct_step, final_bias=False).to(device=dev)
print(weights_model)

optim = torch.optim.Adam(weights_model.parameters(), fused=use_fused)

fovea_flat = torch.zeros(batch, 3, observation_size, device=dev)
fovea_xy = torch.zeros(batch,2, device=dev)
frames_gpu_flat = torch.zeros(batch, frame_size*image_channels, device=dev)

for u in range(100):            
    generated_weights = weights_model(fovea_xy)
    generated_weights = generated_weights.view(batch, observation_size, frame_size)
    reconstruction = fovea_flat @ generated_weights
    reconstruction = reconstruction.permute(0,2,1).reshape(batch, frame_size*image_channels)
    decode_loss = F.mse_loss(reconstruction, frames_gpu_flat)

    print(u)
    optim.zero_grad()
    decode_loss.backward()        
    optim.step()
        
print('done')
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 83
     81     optim.zero_grad()
     82     decode_loss.backward()        
---> 83     optim.step()
     85 print('done')

File /usr/local/lib/python3.8/dist-packages/torch/optim/optimizer.py:280, in Optimizer.profile_hook_step.<locals>.wrapper(*args, **kwargs)
    276         else:
    277             raise RuntimeError(f"{func} must return None or a tuple of (new_args, new_kwargs),"
    278                                f"but got {result}.")
--> 280 out = func(*args, **kwargs)
    281 self._optimizer_step_code()
    283 # call optimizer step post hooks

File /usr/local/lib/python3.8/dist-packages/torch/optim/optimizer.py:33, in _use_grad_for_differentiable.<locals>._use_grad(self, *args, **kwargs)
     31 try:
     32     torch.set_grad_enabled(self.defaults['differentiable'])
---> 33     ret = func(self, *args, **kwargs)
     34 finally:
     35     torch.set_grad_enabled(prev_grad)

File /usr/local/lib/python3.8/dist-packages/torch/optim/adam.py:141, in Adam.step(self, closure)
    130     beta1, beta2 = group['betas']
    132     self._init_group(
    133         group,
    134         params_with_grad,
   (...)
    138         max_exp_avg_sqs,
    139         state_steps)
--> 141     adam(
    142         params_with_grad,
    143         grads,
    144         exp_avgs,
    145         exp_avg_sqs,
    146         max_exp_avg_sqs,
    147         state_steps,
    148         amsgrad=group['amsgrad'],
    149         beta1=beta1,
    150         beta2=beta2,
    151         lr=group['lr'],
    152         weight_decay=group['weight_decay'],
    153         eps=group['eps'],
    154         maximize=group['maximize'],
    155         foreach=group['foreach'],
    156         capturable=group['capturable'],
    157         differentiable=group['differentiable'],
    158         fused=group['fused'],
    159         grad_scale=getattr(self, "grad_scale", None),
    160         found_inf=getattr(self, "found_inf", None),
    161     )
    163 return loss

File /usr/local/lib/python3.8/dist-packages/torch/optim/adam.py:281, in adam(params, grads, exp_avgs, exp_avg_sqs, max_exp_avg_sqs, state_steps, foreach, capturable, differentiable, fused, grad_scale, found_inf, amsgrad, beta1, beta2, lr, weight_decay, eps, maximize)
    278 else:
    279     func = _single_tensor_adam
--> 281 func(params,
    282      grads,
    283      exp_avgs,
    284      exp_avg_sqs,
    285      max_exp_avg_sqs,
    286      state_steps,
    287      amsgrad=amsgrad,
    288      beta1=beta1,
    289      beta2=beta2,
    290      lr=lr,
    291      weight_decay=weight_decay,
    292      eps=eps,
    293      maximize=maximize,
    294      capturable=capturable,
    295      differentiable=differentiable,
    296      grad_scale=grad_scale,
    297      found_inf=found_inf)

File /usr/local/lib/python3.8/dist-packages/torch/optim/adam.py:553, in _fused_adam(params, grads, exp_avgs, exp_avg_sqs, max_exp_avg_sqs, state_steps, grad_scale, found_inf, amsgrad, beta1, beta2, lr, weight_decay, eps, maximize, capturable, differentiable)
    551     device_found_inf = found_inf_dict[device]
    552 torch._foreach_add_(device_state_steps, 1)
--> 553 torch._fused_adam_(
    554     device_params,
    555     device_grads,
    556     device_exp_avgs,
    557     device_exp_avg_sqs,
    558     device_max_exp_avg_sqs,
    559     device_state_steps,
    560     amsgrad=amsgrad,
    561     lr=lr,
    562     beta1=beta1,
    563     beta2=beta2,
    564     weight_decay=weight_decay,
    565     eps=eps,
    566     maximize=maximize,
    567     grad_scale=device_grad_scale,
    568     found_inf=device_found_inf,
    569 )
    570 if device_found_inf is not None:
    571     torch._foreach_sub_(device_state_steps, [device_found_inf] * len(device_state_steps))

RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+fe05266
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Graphics Device
GPU 1: Graphics Device
GPU 2: Graphics Device
GPU 3: Graphics Device

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       1
NUMA node(s):                    4
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7742 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1700.575
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4491.77
Virtualization:                  AMD-V
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-15,64-79
NUMA node1 CPU(s):               16-31,80-95
NUMA node2 CPU(s):               32-47,96-111
NUMA node3 CPU(s):               48-63,112-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.1.0a0+fe05266
[pip3] torch-tensorrt==1.4.0.dev0
[pip3] torchtext==0.13.0a0+fae8e8c
[pip3] torchvision==0.15.0a0
[pip3] triton==2.0.0
[conda] Could not collect


cc @vincentqb @jbschlosser @albanD @janeyx99

**Comment by ngimel** [comment]
cc @janeyx99, @crcrpar

**Comment by Caselles** [comment]
I'm having the same issue with AdamW.

**Comment by crcrpar** [comment]
will look into it though I'm speculating it has something to do with 32bit indexing

**Comment by Godricly** [comment]
Is this one fixed in nightly pytorch?

**Comment by janeyx99** [comment]
should be!

**Comment by Godricly** [comment]
The demo code runs OK with `torch                    2.2.0.dev20230906+cu118`.
But my problem is the same with this :( Maybe Apex is a update too.
/https://github.com/microsoft/Megatron-DeepSpeed/issues/202

**Comment by janeyx99** [comment]
Ah, are you suggesting that this bug occurs for Apex? CC'ing @crcrpar from Nvidia regarding this, but it would be good raising up that issue with Apex instead of here.

**Comment by Godricly** [comment]
Well. It's a bug occurs on all fusedAdam implementations I have found. I actually bypassed the bug in Megatron-Deepspeed using latest pytorch implementation. I'll post a issue for apex. Thank you for your reply.
