### ISSUE TITLE
inconsistent behavior of torch.cat() for 1-dimensional variables and tensors

### ISSUE THREAD

**Issue by scheidan** [pytorch/pytorch#1014]
I think I found an unexpected behavior of `torch.cat()`. It behaves differently for 1 dimensional variables and tensors:
```Python
x = torch.rand(1)
X = Variable(x)

x.size() == X.size()            # true

torch.cat((x,x),0)              # ok
torch.cat((x,x),1)              # ok

torch.cat((X,X),0)              # ok
torch.cat((X,X),1)              # -> fails
```

but everything works for 2 dimensional tensors:
```Python
y = torch.rand(2,1)
Y = Variable(y)

y.size() == Y.size()            # true

torch.cat((y,y),0)              # ok
torch.cat((y,y),1)              # ok

torch.cat((Y,Y),0)              # ok
torch.cat((Y,Y),1)              # ok
```

Thanks for all your work!

**Comment by bordingj** [comment]
in the one-dimensional case, the variables/tensors only has 1 dimension, so you cannot concatenate them on a second dimension. This is consistent with numpy.

**Comment by bordingj** [comment]
to be consistent with numpy it should fail for both variables and tensors in the one-dimensional case.
