### ISSUE TITLE
 Exporting the operator 'aten::scatter_reduce' to ONNX opset version 15 is not supported

### ISSUE THREAD

**Issue by luchangli03** [pytorch/pytorch#101535]
### 🐛 Describe the bug

```
dst = dst.scatter_reduce(-2, dst_idx.expand(n, r, c), src, reduce="mean")
```

### Versions

pytorch version 2.0.1

**Comment by titaiwangms** [comment]
#102048 should be able to partially support aten::scatter_reduce as long as you use opset_version >= 16. However, `reduce='mean'` won't be supported, as it's not in ONNX spec (https://github.com/onnx/onnx/issues/5100)

**Comment by SkylerHuang** [comment]
@titaiwangms  It seems that aten:: scatter_reduce is not supported yet. When converting to onnx, it still reports an error.
`Exporting the operator 'aten::scatter_reduce' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None`
I don't know if there is a configuration problem. My pytorch version is 2. 0. 1 and my onnx version is 1. 13. 1
![image](https://github.com/pytorch/pytorch/assets/24433500/cea433d0-e80c-4c12-8dd1-506a17170a04)

**Comment by titaiwangms** [comment]
@tedtroxell Is your torch version capable of running this CI test https://github.com/pytorch/pytorch/blob/28dc1a093f49432ab15aafa1f662d7ed6c86cb05/test/onnx/test_pytorch_onnx_onnxruntime.py#L4219-L4239?

Or you could try a mini repro on this.

**Comment by tedtroxell** [comment]
@titaiwangms I'll test it out and verify by eod. Thanks!

**Comment by tedtroxell** [comment]
@titaiwangms I was not able to pass that test with either the stable or nightly version unless you add additional env variables. 

### Test Code:
```
import torch
class Model(torch.nn.Module): 
    def __init__(self): 
        super().__init__() 

    def forward(self, args): 
        x, index, input = args
        y_max = input.scatter_reduce(0, index, x, reduce="amax") 
        y_sum = input.scatter_reduce(0, index, x, reduce="sum") 
        y_min = input.scatter_reduce(0, index, x, reduce="amin") 
        y_mul = input.scatter_reduce(0, index, x, reduce="prod") 
        return y_max, y_sum, y_min, y_mul 

model = Model() 
model.eval() 

src = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0]) 
index = torch.tensor([0, 1, 0, 1, 2, 1]) 
input = torch.tensor([1.0, 2.0, 3.0, 8.0]) 

torch.onnx.export(
    model, 
    [src,index,input], 
    f"test.onnx",
    input_names='x,index,input'.split(','),
    opset_version=18,
    verbose=True,
)
```

This fails with stable and nightly
`python test-onnx.py` 

the stable branch provides the same error as above.

this is the error you get back from nightly
```
Traceback (most recent call last):
  File "test-onnx.py", line 21, in <module>
    torch.onnx.export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1656, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/_internal/onnx_proto_utils.py", line 221, in _add_onnxscript_fn
    import onnx
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 11, in <module>
    from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors, convert_model_to_external_data
  File "/opt/conda/lib/python3.8/site-packages/onnx/external_data_helper.py", line 14, in <module>
    from .onnx_pb import TensorProto, ModelProto
  File "/opt/conda/lib/python3.8/site-packages/onnx/onnx_pb.py", line 8, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "/opt/conda/lib/python3.8/site-packages/onnx/onnx_ml_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/opt/conda/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

when you add `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` as an env variable it does work. E.g. `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python python test-onnx.py` is successful.

I'll review my code to double check if I missed something. Thanks for all of your hard work!

**Comment by justinchuby** [comment]
Opset version 18 is not supported. Please consider using 17

**Comment by MaanavD** [comment]
Hi @luchangli03 @tedtroxell 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary.
