### ISSUE TITLE
onnx runtime error

### ISSUE THREAD

**Issue by Sigrid-Z** [pytorch/pytorch#101502]
### 🐛 Describe the bug

I have already converted my pytorch model to onnx, but I encountered new bugs when converting onnx to engine and using onnxruntime to infer onnx model. 
When I do onnx inference:
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Expand node. Name:'/encoder/node_encoder/Expand' Status Message: /encoder/node_encoder/Expand: left operand cannot broadcast on dim 1 LeftShape: {1,6,32}, RightShape: {1,33,32}`

Even if I fix the code concerning the shape error, and convert the model to onnx once more, the onnx inference would report new bugs concerning the shape in following calculations in the model:
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'/aggregator/Add_80' Status Message: /aggregator/Add_80: right operand cannot broadcast on dim 0 LeftShape: {162,15}, RightShape: {152,15}
`
Seems the bug fixing has no end. Is there any efficient way to solve the problem, thank you.

### Versions

1st error related codes in the model:
```
feat_embedding_packed = pack_padded_sequence(feat_embedding_batched, seq_lens_batched, batch_first=True, enforce_sorted=False)

```
2ed error related codes in the model:
```
# Dummy encodings for goal nodes
dummy_enc = torch.zeros_like(node_encodings)
node_encodings = torch.cat((node_encodings, dummy_enc), dim=1)
# Gather node encodings along traversed paths
node_enc_selected = node_encodings[batch_idcs, traversals_batched]
```

**Comment by titaiwangms** [comment]
Hi @Sigrid-Z,

It seems like you would need `dynamic_axes` in [torch.onnx.export](https://pytorch.org/docs/stable/onnx.html#torch.onnx.export)? I would try enable dynamic axes.

**Comment by Sigrid-Z** [comment]
Hi @titaiwangms ,
Thank you but I've already enabled dynamic_axes and this parameter can only solve the dynamic problem for the 1st&last node of the whole graph. It cannot change the shape from static to dynamic for nodes inside the network.

**Comment by Zalways** [comment]
i met similar issue when i use the exported onnx model to inference on cuda:
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running TopK node. Name:'/model/TopK' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument

can you help me with my problem?

@titaiwangms @drisspg  @scw @svenstaro @thiagocrepaldi

**Comment by Zalways** [comment]
> @Zalways please provide a full repro script, otherwise we can't debug

thankyou for your reply!
i exported two kind of model, cpu and cuda, only cpu version can woek well, cuda version will show the error log .

[res18_50char_cuda_192_320_quant.zip](https://github.com/pytorch/pytorch/files/14517359/res18_50char_cuda_192_320_quant.zip)
this is the cuda onnx model

and this is the code i used to export and inference:
[export_infer.zip](https://github.com/pytorch/pytorch/files/14517374/export_infer.zip)

and my env:
cuda 11.8  torch 2.0.0 onnxruntime 1.16.0 detectron2  ubuntu20

**Comment by Zalways** [comment]
> @Zalways please provide a full repro script, otherwise we can't debug

[repro.txt](https://github.com/pytorch/pytorch/files/14517573/repro.txt)

this is the details to repro! thank you!

**Comment by Zalways** [comment]
> @Zalways please provide a full repro script, otherwise we can't debug

hi！Sorry to bother you, is there any progress on you? I'm still baffled by this question, please give me some constructive advice so I can try them
