### ISSUE TITLE
Better "This PR needs a label" error message

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#101694]
## Context

If a PR doesn't have a label for release notes, the merge fails with the following error:
![image](https://github.com/pytorch/pytorch/assets/5652049/c97e4b06-e532-4cb1-b725-ce38f6036d39)

This error message is confusing, especially if your PR has labels already. The reason is not that the PR needs a label, the reason is that the PR needs a "release notes: " or a "topic: not user facing" label.

Yes, that's what the body of the message says "... please use a label starting with...". But we can make the error message clearer (and despite knowing this, I get tripped up by this every once in a while).

## Proposal

Rename `topic: not user facing` to `release notes: not user facing`. This has some implications for the release notes tooling.
Change the error message to say "Reason: This PR needs a `release notes:` label"

This makes it clearer to the user what they need and eliminates the ambiguity.

cc @ZainRizvi @kit1980 @huydhn @clee2000 @pytorch/pytorch-dev-infra

**Comment by kit1980** [comment]
I agree on all points.
I'll do this starting with just changing the error message.

I also have a fix (should be merged today) for an issues that in forked PRs the errors message is not posted before the actual merge attempt - https://github.com/pytorch/pytorch/pull/101467

**Comment by kit1980** [comment]
The 'Change the error message to say "Reason: This PR needs a release notes: label"' is done some time ago.
I'm moving the "Rename topic: not user facing to release notes: not user facing" part to https://github.com/pytorch/pytorch/issues/104282 and closing this one.
