### ISSUE TITLE
Triton chokes on large floating constants

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#101684]
### 🐛 Describe the bug

```python 
def fn():
    a = torch.ones([4], dtype=torch.float64, device="cuda")
    return (a + 2e50)
```

This function works as expected in eager, but returns `inf` when compiled. The crux is that float literals in triton are treated as `float32`, while they are treated as `float64` in Python.

I don't think there's currently a workaround in triton for this issue.

### Versions

master

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by lezcano** [comment]
Tracking triton issue https://github.com/openai/triton/issues/1686

**Comment by ngimel** [comment]
on triton side I think we can generate tl.full with the needed datatype.
