### ISSUE TITLE
UnsupportedOperatorError: Exporting the operator 'aten::broadcast_to' to ONNX opset version 14 is not supported. 

### ISSUE THREAD

**Issue by darwinharianto** [pytorch/pytorch#101768]
### 🚀 The feature, motivation and pitch

Unable to export owlvitForObjectDetection from huggingface transformers library.

**Comment by neonhuang** [comment]
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::broadcast_to' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.1.0a0+4136153'
>>>
