### ISSUE TITLE
CMake Error: Imported target 'c10' references missing file '/usr/lib/lib/libc10.so.1.8.0

### ISSUE THREAD

**Issue by roman-ellerbrock** [pytorch/pytorch#101743]
### Issue Description
I have created a Dockerfile based on Ubuntu:latest that installs Torch, build-essentials, and cmake. When attempting to configure a minimal CMakeLists.txt that includes a 'find_package(torch)', I encounter the following error:

```
-- Caffe2: Protobuf version 3.12.4
CMake Error at /usr/lib/aarch64-linux-gnu/cmake/Caffe2/Caffe2Targets.cmake:116 (message):
  The imported target "c10" references the file

     "/usr/lib/lib/libc10.so.1.8.0"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/aarch64-linux-gnu/cmake/Caffe2/Caffe2Targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/aarch64-linux-gnu/cmake/Caffe2/Caffe2Config.cmake:116 (include)
  /usr/lib/aarch64-linux-gnu/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:4 (find_package)
```

### Steps to reproduce

1. Create a Dockerfile based on ubuntu that installs build-essentials, torch and cmake via apt-get. 
```
FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libtorch-dev

WORKDIR /app

COPY . .

WORKDIR /app/build
```
2. Create a CMakeLists.txt and a minimal main.cpp into the work directory
```
cmake_minimum_required(VERSION 3.12)
project(MyProject)

find_package(Torch REQUIRED)

add_executable(myapp main.cpp)
target_link_libraries(myapp ${TORCH_LIBRARIES})
```
3. create the image via `docker build -t pytorch_issue .`
4.  run it interactively `docker run -it pytorch_issue /bin/bash`
5. run cmake from build directory: `cmake ..`

### Expected Result
cmake finishes without a torch-related error.

### Hotfix
Extending Chun Cai's and actionparsnip's [suggestions](https://answers.launchpad.net/ubuntu/+source/pytorch/+question/702180) to the following issues, one can 

1. locate /usr/lib/lib/libc10.so.1.8.0 via `dpkg -L libtorch-dev | grep libc10.so.1.8.0` which results in `/usr/lib/aarch64-linux-gnu/libc10.so`
2. create a symlink to this file `mkdir /usr/lib/lib; ln -s /usr/lib/aarch64-linux-gnu/libc10.so /usr/lib/lib/`
3. repeat this for /usr/lib/lib/libtorch_cpu.so.1.8.0 and libtorch.so.1.8.0
4. now cmake cannot find the path: "/usr/lib/include" which can be fixed via `mkdir /usr/lib/include; ln -s  /usr/include/torch/ /usr/lib/include`
5. The library should now configures any issues

### Additional Information

- the code is executed on a MacBook 2023 with Apple silicon processor.
- this is my first raised issue in a large project. I hope it's

### Error logs

-- Caffe2: Protobuf version 3.12.4
CMake Error at /usr/lib/aarch64-linux-gnu/cmake/Caffe2/Caffe2Targets.cmake:116 (message):
  The imported target "c10" references the file

     "/usr/lib/lib/libc10.so.1.8.0"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/aarch64-linux-gnu/cmake/Caffe2/Caffe2Targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/aarch64-linux-gnu/cmake/Caffe2/Caffe2Config.cmake:116 (include)
  /usr/lib/aarch64-linux-gnu/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:4 (find_package)

### Minified repro

Does not apply, since it's a compile error and not a runtime error.

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (aarch64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.49-linuxkit-aarch64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
Byte Order:                      Little Endian
CPU(s):                          6
On-line CPU(s) list:             0-5
Vendor ID:                       0x00
Model:                           0
Thread(s) per core:              1
Core(s) per cluster:             6
Socket(s):                       -
Cluster(s):                      1
Stepping:                        0x0
BogoMIPS:                        48.00
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] No relevant packages
[conda] Could not collect

cc @seemethere @malfet @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by malfet** [comment]
Wow: https://packages.ubuntu.com/focal/libtorch3-dev

**Comment by roman-ellerbrock** [comment]
I didn't realize it libtorch-dev delivered an ancient PyTorch. I guess the solution is to use pytorch/pytorch:latest instead of ubuntu:latest and skip the installation attempt via apt-get. Apologies for the confusion and thanks for the quick help.

**Comment by malfet** [comment]
Just to clarify, `libtorch-dev` is not PyTorch, it's torch-on-lua, see this website (and http is not a mistake in url) http://torch.ch/

**Comment by cdluminate** [comment]
This is a downstream bug, and is already fixed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=997931

In recent Debian/Ubuntu releases, `libtorch-dev` is indeed PyTorch, not Torch7.
https://tracker.debian.org/pkg/pytorch

@malfet This issue can be closed.

**Comment by cdluminate** [comment]
While I don't hope downstream bugs to be reported upstream and make the upstream confused, it still happens.
Please feel free to assign downstream debian packaging bug to me on github in the future.

**Comment by malfet** [comment]
Thank you for the update, @cdluminate 
Closing.
