### ISSUE TITLE
Gamma distribution does still not have a CDF implementation

### ISSUE THREAD

**Issue by krikru** [pytorch/pytorch#101742]
### 🚀 The feature, motivation and pitch

This issue is the same as  #41637, which has been closed without having been solved. The facebook-github-bot closed the issue as completed in [6eaa324](https://github.com/pytorch/pytorch/commit/6eaa324c9fff2e5cb0ff8ddb71665ef1e594d623), but the linked commit does not implement a CDF function for the gamma distribution, and simply leaving a comment pointing out that the issue is in fact still unsolved doesn't seem to help to reopen the issue. To draw attention to it, I therefore open this issue instead and refer back to it from this.

**Comment by janeyx99** [comment]
I've reopened the issue as most of the context is there. Thank you for bringing this to awareness. Will close this as followup discussion should go in the original issue.
