### ISSUE TITLE
Python 3.10 Union operator `|` is not supported in jit script

### ISSUE THREAD

**Issue by awbraunstein** [pytorch/pytorch#101777]
### 🐛 Describe the bug

When using the new python 3.10 style of type annotations for unions (`|`) as defined in https://peps.python.org/pep-0604/ with `torch.jit.script`, a `RuntimeError` is raised.

For the given minimal example:
```python
from typing import Union
import torch

@torch.jit.script
def jit_test(
    ok: Union[int, float], bad: int | float
) -> None:
    pass
```

The traceback is:
```
(env) ➜  torch_test python test.py
Traceback (most recent call last):
  File "/Users/awb/torch_test/test.py", line 6, in <module>
    def jit_test(
  File "/Users/awb/torch_test/env/lib/python3.10/site-packages/torch/jit/_script.py", line 1341, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 
Expression of type | cannot be used in a type expression:
  File "/Users/awb/torch_test/test.py", line 7
@torch.jit.script
def jit_test(
    ok: Union[int, float], bad: int | float
                                ~~~~~~~~~~~ <--- HERE
) -> None:
    pass
```

We would expect that the `bad` argument is treated identically as the `ok` argument since their typing is functionally equivalent.

### Versions

```
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 (main, May 17 2023, 17:29:08) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[conda] Could not collect
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by janeyx99** [comment]
To give some context: `torch.jit.script` is no longer under development and so will not be receiving updates to support new Python features. @eellison may have more to add.

**Comment by mostafarohani** [comment]
thanks for the response @janeyx99 ; i am a bit surprised by this message. `torch.compile` doesn't completely replace all the features of `torch.jit.script` and `torch.jit.trace` right? for example with the latter set you can save and then load a model without needing the python model instantiated. That's not true of torch.compile right now if I understand correct?

**Comment by msaroufim** [comment]
@mostafarohani that's right it's an awkward transitionary period until `torch._dynamo.export()` is ready

**Comment by mostafarohani** [comment]
i see @msaroufim ; it would be awesome if the pytorch team can update this thread when they have rough ETAs on when dynamo export and the mentioned stop gaps will be ready

**Comment by randolf-scholz** [comment]
I have written a pull request with a patch that almost works. There is a single test that's failing (out of 50), which I have commented out to see if the CI finds anything else.

```python
    def test_union_optional_of_union_return(self):
        @torch.jit.script
        def fn() -> None | str | int:
            y: Optional[int | str] = "foo"
            return y
```

For this one, JIT-compilation fails with exception

```
RuntimeError: 
Return value was annotated as having type Union[int, NoneType, str] but is actually of type Optional[Union[int, str]]:
  File "/home/rscholz/GIT/CONTRIBUTING/pytorch/testB.py", line 37
def fn(flag: int) -> None | str | int:
    y: Optional[int | str] = "foo"
    return y
    ~~~~~~~~ <--- HERE
```

Something goes wrong with the comparison in this case. Maybe someone experienced with JIT internals can review the PR and point me to the error, or maybe we can merge it anyhow, since this exception requires archaic annotation anyway it is quite common nowadays to use `None | T` instead of `Optional[T]`. Pandas for instance mandates it in their stub files.
