### ISSUE TITLE
Fix annotation update code in qat_utils.py

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#101820]
### 🐛 Describe the bug

this is used to track this task

### Versions

master

cc @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by andrewor14** [comment]
@jerryzh168 Is this task done already? If not, can you add more detail?

**Comment by andrewor14** [comment]
Ok, closing this for now. :) We can open a more specific issue if you don't think this is addressed.
