### ISSUE TITLE
Tensor Decomposition examples 

### ISSUE THREAD

**Issue by nnlbu** [pytorch/pytorch#101892]
### 📚 The doc issue

Hi, 

The documentation for the **Tensor section of Pytorch** is not efficient. There are no examples. Like this one, you are just referred to elsewhere which is not ideal! 

[TORCH.TENSOR.SVD](https://pytorch.org/docs/stable/generated/torch.Tensor.svd.html#torch.Tensor.svd) 

**The tensor** section is the most important part, and to my understanding it suffers from not having examples and explanations. 

### Suggest a potential alternative/fix

Examples like reconstruction of various **Tensor decompositions** can be very helpful. 

Please consider this. Thank you. 

cc @svekars @carljparker @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by jbschlosser** [comment]
Hey @nnlbu, thanks for the report! Please see the [docs here](https://pytorch.org/docs/stable/generated/torch.svd.html) for actual useful info.

Making actionable to fix the reported link and at least point [here](https://pytorch.org/docs/stable/generated/torch.svd.html).

**Comment by lezcano** [comment]
Tensor.svd takes you to torch.svd which takes you to https://pytorch.org/docs/stable/generated/torch.linalg.svd.html?highlight=linalg+svd#torch.linalg.svd, which I think has plenty of examples.

**Comment by nnlbu** [comment]
Yes, but the references are matrix based and it is not for the tensors. 
Currently based on page 12, [there are](https://arxiv.org/pdf/1711.10781.pdf) these 3 python tensor frameworks: 

- TensorLy 
- pytensor 
- scikit-tensor  
- 
scikit-tensor is not maintained anymore and TensorLy does not have comprehensive documentation either. Pytorch is most used for this, yet no major attention is given to the tensor documentation. 

There are just references to the matrix-based decompositions.

**Comment by lezcano** [comment]
We just support matrix-based decompositions. Tensors are considered as batches of matrices, as described in the documentation. If you want tensor decompositions, you'll need to go to third party libraries that build upon PyTorch.

**Comment by IvanYashchuk** [comment]
CuQuantum project provides tensor SVD and it should be working with PyTorch tensors
https://docs.nvidia.com/cuda/cuquantum/python/api/generated/cuquantum.cutensornet.tensor_svd.html#cuquantum.cutensornet.tensor_svd

**Comment by IvanYashchuk** [comment]
I think the main confusion here comes from "torch.Tensor" documentation. In PyTorch it's not a mathematical tensor, it's a Python object that is used in PyTorch for array data. The documentation for "torch.Tensor" describes methods for this object.
Here, `some_tensor.svd()` is equivalent to calling `torch.linalg.svd(some_tensor)`.

**Comment by nnlbu** [comment]
Thanks @IvanYashchuk @lezcano 
I thought this needed some attention. Third-party libraries often are not sufficient.

**Comment by lezcano** [comment]
Closing, as the documentation is correct in master.
