### ISSUE TITLE
[PT2] Provide public API to get compile options/configs

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#101832]
[From Meta internal use case]
For inductor, we have two ways to set up config:
* Set up via ```torch._inductor.config.triton.cudagraphs = True```.
* Passing in options when calling ```torch.compile(model, options={"triton.cudagraphs": True})```.

There is requirement that we would like to get ```torch.compile``` config for further usage. E.g, the training platform wants to get if model is compiled with cudagraph enabled and trigger further action. But currently the configs from the above two sources are merged internally, there is no public API to access this. 

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by williamwen42** [comment]
@qihqi's dataclass config PR may impact this: https://github.com/pytorch/pytorch/pull/103041.
