### ISSUE TITLE
How to add/save parameters (metadata) to pytorch model

### ISSUE THREAD

**Issue by naseemap47** [pytorch/pytorch#101860]
### 🚀 The feature, motivation and pitch

When I working on pytorch model, its difficult for me to keep variables required to run the model.
If I can add metadata to my model, I am not required to save parameters separately.

So any one knows, how to add metadata to pytorch model?

**Comment by jbschlosser** [comment]
Hey @naseemap47! This question is better suited for the [PyTorch forums](https://discuss.pytorch.org/), where you're likely to receive more assistance. Please note that the issues here are reserved for problems within PyTorch itself. Closing for now but feel free to reopen if you identify a PyTorch bug.

**Comment by naseemap47** [comment]
Thank you @jbschlosser for you replay.
