### ISSUE TITLE
Update minimum supported gcc to gcc-9

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#101839]
### 🚀 The feature, motivation and pitch

As this is the first compiler that has full support for C++17 features, for example https://en.cppreference.com/w/cpp/header/filesystem or [`std::exclusive_scan`](https://en.cppreference.com/w/cpp/algorithm/exclusive_scan) (for more info, see  https://godbolt.org/z/q19MPs1rP )

### Alternatives

Do not use C++17

cc @seemethere

**Comment by albanD** [comment]
Note that our minimum clang and msvc versions already support c++ 17

**Comment by malfet** [comment]
We already require VS2019 (which support C++17) as well as clang-7

**Comment by Skylion007** [comment]
This is blocking the upgrade of NCCL @malfet https://github.com/pytorch/pytorch/pull/101457 . We really should update to a modern GCC version

**Comment by Skylion007** [comment]
Also affects: https://github.com/pytorch/pytorch/pull/96217

**Comment by malfet** [comment]
I think we've finally ready for this

**Comment by adamjstewart** [comment]
> Note that our minimum clang and msvc versions already support c++ 17

Where can I find these minimum supported compiler versions documented?
