### ISSUE TITLE
MacOS build produce 2.3Gb artifacts

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#101800]
### 🐛 Describe the bug

While looking at https://github.com/pytorch/pytorch/actions/runs/5003410724 I've noticed two 2.3Gb artifacts of MacOS test runs:
<img width="657" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/ca4c0ca0-ec43-460f-ad19-3ead9adda69f">

Need to investigate what are those, and are they really needed

### Versions

CI

cc @albanD

**Comment by huydhn** [comment]
Opps! They are the conda environment I add when trying to debug MacOS dependencies issue a while back https://github.com/pytorch/pytorch/blob/main/.github/workflows/_mac-test.yml#L217-L224.  They are uploaded only when the job fail for debugging purpose.  I don't think we need this anymore and I will clean it up
