### ISSUE TITLE
PyTorch contains customized versions of some files from CUTLASS source tree

### ISSUE THREAD

**Issue by alexsamardzic** [pytorch/pytorch#101804]
Recently, [PR 100881](https://github.com/pytorch/pytorch/pull/100881) added customized versions of several files from CUTLASS source tree into PyTorch source tree, under `aten/src/ATen/native/sparse/cuda/cutlass`.  This was needed in order to support linear operator with structured sparse weight matrix, so that optimized sparse GEMM available on tensor cores on NVIDIA Ampere GPUs could be utilized through CUTLASS, for better performance.  However, having to maintain these customized files is sub-optimal, and for this reason a [PR](https://github.com/NVIDIA/cutlass/pull/951) is created in CUTLASS repo, to have the functionality required implemented directly in CUTLASS.  Hopefully, needed functionality will be eventually implemented upstream in CUTLASS, and this issue is to eventually utilize it from upstream, and then remove mentioned files from PyTorch source tree.

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by cpuhrsch** [comment]
cc @albanD

**Comment by alexsamardzic** [comment]
Fixed by [PR 107612](https://github.com/pytorch/pytorch/pull/107612).
