### ISSUE TITLE
Requisting Branch with: PERF_WITH_AVX=0, PERF_WITH_AVX2=0, PERF_WITH_AVX512=0

### ISSUE THREAD

**Issue by mironkraft** [pytorch/pytorch#101872]
### 🚀 The feature, motivation and pitch

Well for old equipment which is not able to process this level

More information: 
https://github.com/oobabooga/text-generation-webui/issues/2163

### Additional context

There are several bugs because of this, you can check complete debugg @:

https://github.com/oobabooga/text-generation-webui/issues/2163#issuecomment-1554837395

**Comment by jbschlosser** [comment]
Hey @mironkraft, FYI I'd suggest asking for help building with AVX / AVX2 disabled on the  [PyTorch forums](https://discuss.pytorch.org/), as you're more likely to receive assistance there. Note that the issues here are reserved for issues within PyTorch itself. Closing for now but feel free to reopen if you identify a bug within PyTorch itself.
