### ISSUE TITLE
Error, attribute exists on the Python module, but we failed to convert Python type: 'list' to a TorchScript type 

### ISSUE THREAD

**Issue by lix19937** [pytorch/pytorch#101864]
### 🐛 Describe the bug

When I use **detectron2** TorchScript to export onnx,  the code use python list,  will report  error, This attribute exists on the Python module, but we failed to convert Python type: 'list' to a TorchScript type

```
RuntimeError: 
Module 'ResNet' has no attribute 'stages_and_names' (This attribute exists on the Python module, but we failed to convert Python type: 'list' to a TorchScript type.):
  File "/usr/local/lib/python3.7/dist-packages/detectron2/modeling/backbone/resnet.py", line 435
        if "stem" in self._out_features:
            outputs["stem"] = x
        for stage, name in self.stages_and_names:
                           ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            x = stage(x)
            if name in self._out_features:
```   

https://github.com/facebookresearch/detectron2/issues/2734  has the same error, it suggest to use torch1.8,  but not work for me. 

How to slove it ?   Thanks
 

### Versions

 ```
torch                         1.10.2+cu113     
detectron2                 0.6                   
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by FreshmanMa** [comment]
> Hi @lix19937,
> 
> We’ve gone ahead and closed this issue because it is stale. If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!
> 
> Thanks, ONNX Converter team

Have you deal with it?
