### ISSUE TITLE
This is a concise reproduction of my code, when the input batch is not the same size as before the batch, it will lead to memory leaks, the actual scenario is ocr accepting images of different sizes as input

### ISSUE THREAD

**Issue by chaodreaming** [pytorch/pytorch#101921]
### 🐛 Describe the bug

import random
import torch
from torch import nn
import torch.utils.checkpoint as cp
if __name__ == '__main__':
    class FullyConvNet(nn.Module):
        def __init__(self):
            super(FullyConvNet, self).__init__()

            # 卷积层
            self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)
            self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
            self.conv3 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)

            # 全卷积层
            self.fc1 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
            self.fc2 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)
            self.fc3 = nn.Conv2d(in_channels=256, out_channels=2, kernel_size=3, padding=1)

        def forward(self, x):
            # 卷积层
            x = cp.checkpoint(self.conv1, x)
            x = nn.functional.relu(x,inplace=True)
            x = nn.functional.max_pool2d(x, 2)

            x = cp.checkpoint(self.conv2, x)
            x = nn.functional.relu(x,inplace=True)
            x = nn.functional.max_pool2d(x, 2)

            x = cp.checkpoint(self.conv3, x)
            x = nn.functional.relu(x,inplace=True)
            x = nn.functional.max_pool2d(x, 2)

            # 全卷积层
            x = cp.checkpoint(self.fc1, x)
            x = nn.functional.relu(x,inplace=True)
            x = cp.checkpoint(self.fc2, x)
            x = nn.functional.relu(x,inplace=True)
            # x = self.fc3(x)

            # 返回结果
            return x
    model=FullyConvNet()
    model=model.to("cuda:0")
    for i in range(100000):
        images = torch.randn((8, 3, 448, 448))
        # images = torch.randn((8, 3, random.randint(224, 448), random.randint(224, 448)))
        images=images.to("cuda:0")
        model(images)

### Versions

--2023-05-20 09:40:01--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 21676 (21K) [text/plain]
正在保存至: ‘collect_env.py’

collect_env.py                       100%[======================================================================>]  21.17K  --.-KB/s    用时 0.01s 

2023-05-20 09:40:01 (1.62 MB/s) - 已保存 ‘collect_env.py’ [21676/21676])

Collecting environment information...
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-41-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn.so.8.8.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.8.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.8.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.8.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.8.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.8.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.8.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
架构：                           x86_64
CPU 运行模式：                   32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
字节序：                         Little Endian
CPU:                             20
在线 CPU 列表：                  0-19
厂商 ID：                        GenuineIntel
型号名称：                       12th Gen Intel(R) Core(TM) i7-12700
CPU 系列：                       6
型号：                           151
每个核的线程数：                 2
每个座的核数：                   12
座：                             1
步进：                           2
CPU 最大 MHz：                   4900.0000
CPU 最小 MHz：                   800.0000
BogoMIPS：                       4224.00
标记：                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
虚拟化：                         VT-x
L1d 缓存：                       512 KiB (12 instances)
L1i 缓存：                       512 KiB (12 instances)
L2 缓存：                        12 MiB (9 instances)
L3 缓存：                        25 MiB (1 instance)
NUMA 节点：                      1
NUMA 节点0 CPU：                 0-19
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-lightning==1.8.4.post0
[pip3] reformer-pytorch==1.4.4
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.1+cu118
[pip3] torchmetrics==0.11.0
[pip3] torchtext==0.6.0
[pip3] torchvision==0.15.1+cu118
[pip3] triton==2.0.0
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-lightning         1.8.4.post0              pypi_0    pypi
[conda] reformer-pytorch          1.4.4                    pypi_0    pypi
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torchaudio                2.0.1+cu118              pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchtext                 0.6.0                    pypi_0    pypi
[conda] torchvision               0.15.1+cu118             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by chaodreaming** [comment]
import random
import torch
from torch import nn
import torch.utils.checkpoint as cp
if __name__ == '__main__':
    class FullyConvNet(nn.Module):
        def __init__(self):
            super(FullyConvNet, self).__init__()

            # 卷积层
            self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)
            self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
            self.conv3 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)

            # 全卷积层
            self.fc1 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
            self.fc2 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)
            self.fc3 = nn.Conv2d(in_channels=256, out_channels=2, kernel_size=3, padding=1)

        def forward(self, x):
            # 卷积层
            x = cp.checkpoint(self.conv1, x)
            x = nn.functional.relu(x,inplace=True)
            x = nn.functional.max_pool2d(x, 2)

            x = cp.checkpoint(self.conv2, x)
            x = nn.functional.relu(x,inplace=True)
            x = nn.functional.max_pool2d(x, 2)

            x = cp.checkpoint(self.conv3, x)
            x = nn.functional.relu(x,inplace=True)
            x = nn.functional.max_pool2d(x, 2)

            # 全卷积层
            x = cp.checkpoint(self.fc1, x)
            x = nn.functional.relu(x,inplace=True)
            x = cp.checkpoint(self.fc2, x)
            x = nn.functional.relu(x,inplace=True)
            # x = self.fc3(x)

            # 返回结果
            return x
    model=FullyConvNet()
    model=model.to("cuda:0")
    for i in range(100000):
        images = torch.randn((8, 3, 448, 448))
        # images = torch.randn((8, 3, random.randint(224, 448), random.randint(224, 448)))
        images=images.to("cuda:0")
        model(images)

**Comment by chaodreaming** [comment]
No leakage when the input is fixed dimension

**Comment by chaodreaming** [comment]
After testing, even using torch.utils.checkpoint did not improve

**Comment by chaodreaming** [comment]
After experimental analysis, the problem appeared in 2.0, 1.12.0 normal

**Comment by bdhirsh** [comment]
@chaodreaming I'm not able to reproduce your memory leak. Are you able to try on a recent nightly?

Here's the script I used (lightly edited from yours, since it had a couple syntax errors:

```
import random                                                                                                                                                                                                                                        import torch
from torch import nn
import torch.utils.checkpoint as cp

class FullyConvNet(nn.Module):

    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)

        self.fc1 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
        self.fc2 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)
        self.fc3 = nn.Conv2d(in_channels=256, out_channels=2, kernel_size=3, padding=1)

    def forward(self, x):
        x = cp.checkpoint(self.conv1, x)
        x = nn.functional.relu(x,inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        x = cp.checkpoint(self.conv2, x)
        x = nn.functional.relu(x,inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        x = cp.checkpoint(self.conv3, x)
        x = nn.functional.relu(x,inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        x = cp.checkpoint(self.fc1, x)
        x = nn.functional.relu(x,inplace=True)
        x = cp.checkpoint(self.fc2, x)
        x = nn.functional.relu(x,inplace=True)
        # x = self.fc3(x)

        return x

model = FullyConvNet()
model = model.to("cuda:0")

for i in range(1000):
    print(torch.cuda.memory_allocated())
    images = torch.randn((8, 3, random.randint(224, 448), random.randint(224, 448)), device='cuda:0')
    model(images)
```

**Comment by wellescastro** [comment]
I don't have a minimal reproducible example, but I also detected the same behavior in my code base: using different-sized images causes memory leaks after upgrading to PT 2.0. I had to downgrade to 1.13. There is also no leakage with fixed input-size images.

**Comment by wellescastro** [comment]
I'll try to extract the relevant code and get back with a reproducible example

**Comment by wellescastro** [comment]
Well, I still haven't stopped to isolate the bug in my case, but with a slightly modified version of @Vincentx15 code I got the following results using the colaboratory T4 (2.0.1+cu118):
```
epoch: [0] - max cpu memory: 3663MiB
epoch: [1] - max cpu memory: 4178MiB
epoch: [2] - max cpu memory: 4675MiB
epoch: [3] - max cpu memory: 5175MiB
epoch: [4] - max cpu memory: 5663MiB
epoch: [5] - max cpu memory: 6141MiB
epoch: [6] - max cpu memory: 6621MiB
epoch: [7] - max cpu memory: 7094MiB
epoch: [8] - max cpu memory: 7557MiB
epoch: [9] - max cpu memory: 8008MiB
epoch: [10] - max cpu memory: 8458MiB
epoch: [11] - max cpu memory: 8906MiB
epoch: [12] - max cpu memory: 9347MiB
epoch: [13] - max cpu memory: 9777MiB
epoch: [14] - max cpu memory: 10198MiB
```
The memory increase seems odd, here's the code:
```
import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset
import time
import resource
import random

np.random.seed(0)
random.seed(0)
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True

class ToyDataset(Dataset):
    def __init__(self):
        self.enable_variable_size = True

    def __len__(self):
        return 1000

    def __getitem__(self, item):
        if self.enable_variable_size:
          d1, d2, d3 = np.random.randint(50, 100, size=3)
        else:
          d1, d2, d3 = 100, 100, 100
        data = np.random.randn(d1, d2, d3).astype(np.float32)
        return data[None, ...]


class ToyModel(torch.nn.Module):
    def __init__(self, out_channels=10, num_convs=3):
        super(ToyModel, self).__init__()
        self.module_dict = torch.nn.ModuleDict()
        for i in range(num_convs):
            conv_op = torch.nn.Conv3d(in_channels=1 if i == 0 else out_channels,
                                      out_channels=out_channels,
                                      kernel_size=3)
            self.module_dict[f"conv_{i}"] = conv_op

    def forward(self, x):
        for k, op in self.module_dict.items():
            x = op(x)
        return x


def train(model, device, loader, n_epochs=10):
    print("starting training..")
    time_init = time.time()
    for epoch in range(n_epochs):
        for input_tensor in loader:
            with torch.no_grad():
                input_tensor = torch.from_numpy(input_tensor[None, ...]).to(device)
                _ = model(input_tensor)
        print(f"epoch: [{epoch}] - max cpu memory: {get_cpu_memory()}MiB")

def get_cpu_memory():
    return int(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss * 10 ** 3 / 2 ** 20)


train_loader = DataLoader(dataset=ToyDataset(), collate_fn=lambda x: x[0], num_workers=2)
device = f'cuda' if torch.cuda.is_available() else 'cpu'
model = ToyModel().to(device)
train(model=model, device=device, loader=train_loader, n_epochs=100)
```
If I disable the variable size images, I got a steady memory usage around 3155MiB

**Comment by chaodreaming** [comment]
I certainly know that disabling it can avoid this problem, but my requirements are variable, so can't this problem be solved

**Comment by chaodreaming** [comment]
```
import random
import torch
from torch import nn
import torch.utils.checkpoint as cp

class FullyConvNet(nn.Module):
    def __init__(self):
        super(FullyConvNet, self).__init__()

        # 卷积层
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)

        # 全卷积层
        self.fc1 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
        self.fc2 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)
        self.fc3 = nn.Conv2d(in_channels=256, out_channels=2, kernel_size=3, padding=1)

    def forward(self, x):
        # 卷积层
        x = torch.utils.checkpoint.checkpoint(self.conv1, x)
        x = nn.functional.relu(x, inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        x = torch.utils.checkpoint.checkpoint(self.conv2, x)
        x = nn.functional.relu(x, inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        x = torch.utils.checkpoint.checkpoint(self.conv3, x)
        x = nn.functional.relu(x, inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        # 全卷积层
        x = torch.utils.checkpoint.checkpoint(self.fc1, x)
        x = nn.functional.relu(x, inplace=True)
        x = torch.utils.checkpoint.checkpoint(self.fc2, x)
        x = nn.functional.relu(x, inplace=True)

        x = self.fc3(x)

        # 返回结果
        return x

model = FullyConvNet()
model = model.to("cuda:0")

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
loss_function = nn.CrossEntropyLoss()

for i in range(100000):
    images = torch.randn((8, 3, 448, 448))
    images = images.to("cuda:0")
    model.zero_grad()

    outputs = model(images)
    # loss = loss_function(outputs, targets)  # 计算损失函数
    # loss.backward()
    # optimizer.step()  # 更新模型参数
```

**Comment by chaodreaming** [comment]
I'm very sorry for the formatting issue with the previous code. It has been adjusted now and comes with an experimental memory growth chart. It's not GPU graphics memory, but the memory of the memory module
![image](https://github.com/pytorch/pytorch/assets/49591435/569abb47-09a6-45e3-9acb-564bac0e597a)

```
import random
import torch
from torch import nn
import torch.utils.checkpoint as cp
from tqdm import tqdm
class FullyConvNet(nn.Module):
    def __init__(self):
        super(FullyConvNet, self).__init__()

        # 卷积层
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=64, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)

        # 全卷积层
        self.fc1 = nn.Conv2d(in_channels=256, out_channels=512, kernel_size=3, padding=1)
        self.fc2 = nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=3, padding=1)
        self.fc3 = nn.Conv2d(in_channels=1024, out_channels=1024, kernel_size=3, padding=1)

    def forward(self, x):
        # 卷积层
        x = self.conv1(x)
        x = nn.functional.relu(x, inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        x = self.conv2(x)
        x = nn.functional.relu(x, inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        x = self.conv3( x)
        x = nn.functional.relu(x, inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        # 全卷积层
        x = self.fc1(x)
        x = nn.functional.relu(x, inplace=True)
        x = self.fc2(x)
        x = nn.functional.relu(x, inplace=True)

        x = self.fc3(x)

        # 返回结果
        return x

model = FullyConvNet()
model = model.to("cuda:0")

for epoch in tqdm(range(100)):
    for i in tqdm(range(100000)):
        images = torch.randn((8, 3, random.randint(32,448),random.randint(224,1024)))
        images = images.to("cuda:0")
        outputs = model(images)

```

**Comment by chaodreaming** [comment]
> 我无法重现您的内存泄漏。你能试穿最近的每晚吗？
> 
> 这是我使用的脚本（从您的脚本中略微编辑，因为它有几个语法错误：
> 
> ```
> import random                                                                                                                                                                                                                                        import torch
> from torch import nn
> import torch.utils.checkpoint as cp
> 
> class FullyConvNet(nn.Module):
> 
>     def __init__(self):
>         super().__init__()
> 
>         self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)
>         self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
>         self.conv3 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)
> 
>         self.fc1 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
>         self.fc2 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)
>         self.fc3 = nn.Conv2d(in_channels=256, out_channels=2, kernel_size=3, padding=1)
> 
>     def forward(self, x):
>         x = cp.checkpoint(self.conv1, x)
>         x = nn.functional.relu(x,inplace=True)
>         x = nn.functional.max_pool2d(x, 2)
> 
>         x = cp.checkpoint(self.conv2, x)
>         x = nn.functional.relu(x,inplace=True)
>         x = nn.functional.max_pool2d(x, 2)
> 
>         x = cp.checkpoint(self.conv3, x)
>         x = nn.functional.relu(x,inplace=True)
>         x = nn.functional.max_pool2d(x, 2)
> 
>         x = cp.checkpoint(self.fc1, x)
>         x = nn.functional.relu(x,inplace=True)
>         x = cp.checkpoint(self.fc2, x)
>         x = nn.functional.relu(x,inplace=True)
>         # x = self.fc3(x)
> 
>         return x
> 
> model = FullyConvNet()
> model = model.to("cuda:0")
> 
> for i in range(1000):
>     print(torch.cuda.memory_allocated())
>     images = torch.randn((8, 3, random.randint(224, 448), random.randint(224, 448)), device='cuda:0')
>     model(images)
> ```

I updated it above

**Comment by chaodreaming** [comment]
@bdhirsh

**Comment by bdhirsh** [comment]
> I updated it above

I ran this snippet locally on a commit off of the main branch (`7b6dc72ffae43d340a08ab79da8334a09bf41f14`), and I can't reproduce the memory leak.

@chaodreaming can you try re-running on a nightly and see if the problem still goes away?

**Comment by eqy** [comment]
@bdhirsh 
I believe the confusion is that the complaint is about host-side memory usage similar to #98688 while the script itself is measuring device memory usage.

e.g., this modified script shows increasing host memory usage
```
import random
import torch
from torch import nn
import torch.utils.checkpoint as cp

import resource

class FullyConvNet(nn.Module):

    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)

        self.fc1 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
        self.fc2 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)
        self.fc3 = nn.Conv2d(in_channels=256, out_channels=2, kernel_size=3, padding=1)

    def forward(self, x):
        x = cp.checkpoint(self.conv1, x)
        x = nn.functional.relu(x,inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        x = cp.checkpoint(self.conv2, x)
        x = nn.functional.relu(x,inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        x = cp.checkpoint(self.conv3, x)
        x = nn.functional.relu(x,inplace=True)
        x = nn.functional.max_pool2d(x, 2)

        x = cp.checkpoint(self.fc1, x)
        x = nn.functional.relu(x,inplace=True)
        x = cp.checkpoint(self.fc2, x)
        x = nn.functional.relu(x,inplace=True)
        # x = self.fc3(x)

        return x

model = FullyConvNet()
model = model.to("cuda:0")

for i in range(1000):
    images = torch.randn((8, 3, random.randint(224, 448), random.randint(224, 448)), device='cuda:0')
    model(images)
    max_mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024  # MB
    max_cuda_mem = torch.cuda.max_memory_allocated() / 1024 / 1024  # MB
    print(f"iter: {i} cpu: {max_mem} cuda: {max_cuda_mem}")
```

In general, some additional memory usage is expected with dynamic shapes as each dynamic shape will cause an additional cuDNN execution plan to be cached in host memory. However it appears that caching execution plans (which is done in cuDNN v8 API) vs. caching algo perf data (which is done in v7 API) consumes significantly more memory.

I will follow-up to check if there is anything we can do to reduce the overhead in V8.

@chaodreaming 
你可以使用 `TORCH_CUDNN_V8_API_DISABLED=1` env var 暂时 workaround

**Comment by chaodreaming** [comment]
> 

I tried this method, although the growth rate has slowed down, but the memory is still rising, even if you can not use 2.0 to significantly increase the speed, I also hope that the 4090 can keep the speed does not decrease, using 1.12 can not give full play to the 4090 speed

**Comment by flyfrank** [comment]
> > 
> 
> I tried this method, although the growth rate has slowed down, but the memory is still rising, even if you can not use 2.0 to significantly increase the speed, I also hope that the 4090 can keep the speed does not decrease, using 1.12 can not give full play to the 4090 speed


I encountered a similar problem in pytorch 1.13.1, how did you solve it

**Comment by eqy** [comment]
In 1.13.1 you can disable the cuDNN V8 API via `TORCH_CUDNN_V8_API_DISABLED=1`
