### ISSUE TITLE
`torch.compile` fails to fuse backward pass when using `torch.autograd.Function`

### ISSUE THREAD

**Issue by thecharlieblake** [pytorch/pytorch#101937]
### 🐛 Describe the bug

Operations implemented using `torch.autograd.Function` and wrapped in `torch.compile` are not fused in the backward pass.

---

I've provided a minimal reproducer to demonstrate this. Taking the function:
```
def times2_loop(x):
    for _ in range(10):
        x *= 2
    return x
```
I provide 3 alternative versions:
1. **`times2_custom_loop`**:  exactly the same as `times2_loop`, but with each `* 2` implemented as an operation with a custom gradient (via `torch.autograd.Function`)
2. **`times2_loop_compiled`**: `times2_loop` wrapped in `torch.compile`
3. **`times2_custom_loop_compiled`**: `times2_custom_loop` wrapped in `torch.compile`

I would expect the basic version and the "custom" version to both speed up considerably when wrapped in `torch.compile`. This is true in the forward pass, but only the basic version speeds up in the backward pass, indicating that no fusion is taking place for the "custom" version.

Results for my benchmarks on these functions are as follows:

![torch_compile_custom_grad_plot](https://github.com/pytorch/pytorch/assets/17354715/795ec6fa-1415-482d-9ed2-086375d0c489)

The forward plot is as expected: the compiled version of the op is faster for both the regular (green) and custom-gradient implementation (red).

The backward plot is not: only the regular version of the compiled op is faster (green). The custom-gradient implementation (red) is just as slow as the non-compiled version.

(For the full reproducer, see the following notebook: [reproducer.ipynb.zip](https://github.com/pytorch/pytorch/files/11523279/reproducer.ipynb.zip))

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.26

Python version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.10.157-139.675.amzn2.x86_64-x86_64-with-glibc2.26
Is CUDA available: True
CUDA runtime version: 11.0.221
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               79
Model name:          Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:            1
CPU MHz:             2701.691
CPU max MHz:         3000.0000
CPU min MHz:         1200.0000
BogoMIPS:            4599.99
Hypervisor vendor:   Xen
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            46080K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] numpydoc==1.5.0
[pip3] torch==2.0.1
[pip3] triton==2.0.0
[conda] mkl                       2023.0.0         h84fe81f_25396    conda-forge
[conda] mkl-service               2.4.0           py310h3605609_14    intel
[conda] mkl_fft                   1.3.1           py310hcab1719_22    intel
[conda] mkl_random                1.2.2           py310hbf47bc3_22    intel
[conda] mkl_umath                 0.1.1           py310hf66a691_32    intel
[conda] numpy                     1.22.3          py310hf0956d0_5    intel
[conda] numpy-base                1.22.3          py310h45c9ace_5    intel
[conda] numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by ezyang** [comment]
Cc @voznesenskym

**Comment by Chillee** [comment]
In the past, we've done graph breaks on autograd.Function objects, but we should have largely resolved those issues recently. Assigning to @voznesenskym

**Comment by ngimel** [comment]
@thecharlieblake can you check if this works on nightly?

**Comment by voznesenskym** [comment]
@thecharlieblake please try it on main, closing as fixed, reopen if you have issues :) Ty for filing.

**Comment by thecharlieblake** [comment]
I've just tried this on main and can confirm it now works. Apologies for not trying this before submitting and taking up your time. I didn't anticipate you were working on this so actively - I stand impressed! Thanks all.

**Comment by voznesenskym** [comment]
> I've just tried this on main and can confirm it now works. Apologies for not trying this before submitting and taking up your time. I didn't anticipate you were working on this so actively - I stand impressed! Thanks all.

No worries at all, and ty for submitting a notebook, it makes repro delightful. Please keep filing issues on anything you find!
