### ISSUE TITLE
Ordering of CUDNN versions

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#1019]
Hello,

thank you for pytorch! I sincerely enjoy toying around with it.

In pytorch/torch/backends/cudnn/__init__.py the ordering of cudnn versions to be loaded is

'libcudnn.so.6.0.5', 'libcudnn.so.6.0.10', 'libcudnn.so.5.1.5', 'libcudnn.so.5.1.3',
'libcudnn.so.5.0.5', 'libcudnn.so.5.1.10'

If there isn't a reason to not use 5.1.10, (or 6.0.10 for that matter), it would be great to use descending order.
I ran into this when using RNN with dropout while having libcudnn 5.0.5 and 5.1.10 installed in parallel and got "dropout supported only in cudnn v5.1 and above" from rnn.py:211 much to my surprise.

Thank you

Thomas

**Comment by soumith** [comment]
hi Thomas, we are fixing this altogether by just using the version found at compile-time, here:
https://github.com/pytorch/pytorch/pull/1017

**Comment by t-vi** [comment]
Cool, thanks!
