### ISSUE TITLE
Softplus float16 calculation error in mps backend

### ISSUE THREAD

**Issue by CaoE** [pytorch/pytorch#101946]
### 🐛 Describe the bug

import torch
import torch.nn.functional as F

x = torch.randn((20), dtype=torch.float16).to("mps").requires_grad_()
y = F.softplus(x, 3, 0.2)

Error was raised  : input types 'tensor<20xf16>' and 'tensor<1xf32>' are not broadcast compatible

### Versions

This issue was found in pre-ci, and I don't have a mac to reproduce this bug. For details please see https://github.com/pytorch/pytorch/actions/runs/5036308820/jobs/9032481013?pr=98745

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
Here is the fix: #101948.

Let me know once #98745 is merged so I can rebase this PR, thank you!
