### ISSUE TITLE
ROCm: Importing PyTorch before TensorFlow causes the latter to fail spectacularly

### ISSUE THREAD

**Issue by hameerabbasi** [pytorch/pytorch#101900]
### 🐛 Describe the bug

```python
import torch
import tensorflow as tf
tf.zeros(1)
```

xref tensorflow/tensorflow#60642

### Versions

PyTorch version: 2.0.1+rocm5.4.2
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.4.22803-474e8620

OS: EndeavourOS Linux (x86_64)
GCC version: (GCC) 13.1.1 20230429
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.37

Python version: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-6.3.2-arch1-1-x86_64-with-glibc2.37
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Radeon VII
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.4.22803
MIOpen runtime version: 2.19.0
Is XNNPACK available: True

CPU:
Architektur:                     x86_64
CPU Operationsmodus:             32-bit, 64-bit
Adressgrößen:                    39 bits physical, 48 bits virtual
Byte-Reihenfolge:                Little Endian
CPU(s):                          12
Liste der Online-CPU(s):         0-11
Anbieterkennung:                 GenuineIntel
Modellname:                      Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Prozessorfamilie:                6
Modell:                          158
Thread(s) pro Kern:              2
Kern(e) pro Sockel:              6
Sockel:                          1
Stepping:                        10
Skalierung der CPU(s):           92%
Maximale Taktfrequenz der CPU:   4700,0000
Minimale Taktfrequenz der CPU:   800,0000
BogoMIPS:                        7402,02
Markierungen:                    fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
Virtualisierung:                 VT-x
L1d Cache:                       192 KiB (6 Instanzen)
L1i Cache:                       192 KiB (6 Instanzen)
L2 Cache:                        1,5 MiB (6 Instanzen)
L3 Cache:                        12 MiB (1 Instanz)
NUMA-Knoten:                     1
NUMA-Knoten0 CPU(s):             0-11
Schwachstelle Itlb multihit:     KVM: Mitigation: VMX disabled
Schwachstelle L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Schwachstelle Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Schwachstelle Meltdown:          Mitigation; PTI
Schwachstelle Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Schwachstelle Retbleed:          Mitigation; IBRS
Schwachstelle Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Schwachstelle Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Schwachstelle Spectre v2:        Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Schwachstelle Srbds:             Mitigation; Microcode
Schwachstelle Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-lightning==1.9.0
[pip3] pytorch-triton-rocm==2.0.1
[pip3] torch==2.0.1+rocm5.4.2
[pip3] torchaudio==2.0.2+rocm5.4.2
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.2+rocm5.4.2
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch-lightning         1.9.0                    pypi_0    pypi
[conda] pytorch-triton-rocm       2.0.1                    pypi_0    pypi
[conda] torch                     2.0.1+rocm5.4.2          pypi_0    pypi
[conda] torchaudio                2.0.2+rocm5.4.2          pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchvision               0.15.2+rocm5.4.2          pypi_0    pypi

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo

**Comment by jbschlosser** [comment]
Sounds like more of a TensorFlow issue :) Feel free to reopen if investigation there indicates some bug within PyTorch.
