### ISSUE TITLE
a strange torch.no_grad behaviour when used with lazy_property from distributions

### ISSUE THREAD

**Issue by serhii-havrylov** [pytorch/pytorch#10207]
Recently I encountered a weird bug, that can be reproduced with the next snippet of code:

```python
import torch
from torch.nn import functional as F
from torch.distributions.one_hot_categorical import OneHotCategorical


scores = torch.tensor([[1, 4, 2],
                       [8, 4, 4]], dtype=torch.float32, requires_grad=True)
probs = F.softmax(scores, dim=-1)
cat = OneHotCategorical(probs)

print(cat.logits.requires_grad)
with torch.no_grad():
    print(cat.logits.requires_grad)

sample = cat.sample()
log_prob = cat.log_prob(sample)
loss = log_prob.sum()
loss.backward()
```
If one removes the print function right before the `no_grad` context manager there is going to be a runtime error when calling `backward`: `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

It turns out that calling lazy property `cat.logits` within the `no_grad` context manager will create an attribute which doesn't require grad and if one uses `cat.logits` outside `no_grad` it still will not require grad, even though it should. You can see this strange interplay of `lazy_property` and `no_grad` in this example: 

```python
import torch
from torch.distributions.utils import lazy_property


class MyScores:
    def __init__(self, score):
        self.score = score

    @lazy_property
    def negative_score(self):
        return -self.score


scores = torch.tensor([[1, 4, 2],
                       [8, 4, 4]], dtype=torch.float32, requires_grad=True)
my_scores = MyScores(scores)

with torch.no_grad():
    print(my_scores.negative_score.requires_grad)

loss = my_scores.negative_score.sum()
loss.backward()
```
This is not necessarily a bug, because the expected behaviour of the `no_grad` that whatever computations are created inside this context manager they are not going to require grad. So calling `my_scores.negative_score` within `no_grad` will create `negative_score` attribute which will not require grad as expected. The thing is that it is somewhat counterintuitive that my_scores.negative_score still doesn't require grad outside of the context manager. A user doesn't really know that it is a lazy property and expects it to have the same `require_grad` property as in the `probs` variable. Thus, the usage of the `lazy_property` within distributions can lead to the somewhat obscure bugs.

In my case I was sampling some noise, and used `logits` to obtain correct `dtype` and `device`:
```python
with torch.no_grad():
     uniforms = T.empty(sample_shape, dtype=cat.logits.dtype, device=cat.logits.device).uniform_()
```
It was really surprising to see `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn` later when calling `loss.backward()`

PyTorch version is 0.4

**Comment by fmassa** [comment]
I've debugged this problem with @serhii-havrylov earlier on, and it sounds like it's a bad interaction between `lazy_property` and the `no_grad` context manager.

cc @fritzo

**Comment by fritzo** [comment]
IIRC @neerajprad and @alicanb and I encountered this problem early, and @apaszke recommended always using `with torch.grad_enabled():` inside `@lazy_property` methods in case the gradient was enabled later on. I don't believe we ever made a complete pass over the `@lazy_property` implementations to make this consistent across all distributions. Also I believe the strategy to disable gradients was to ensure that a distribution is **created** inside a `with torch.no_grad()` context; this way its parameters should be detached (due to `.expand()` or `broadcast_tensors` being called internally).

**Comment by fritzo** [comment]
Also I believe the best solution is to improve our documentation (there's no simple coding fix due to the out-of-order execution). @serhii-havrylov feel free to incorporate any clarifying text you could into the distribution docs, or we could add some clarifying text and cc you on the PR.

**Comment by SsnL** [comment]
:) I think we fixed this in https://github.com/pytorch/pytorch/pull/7708, which is part of 0.4.1. Can you try that?

**Comment by serhii-havrylov** [comment]
@SsnL Yes, it work! Thanks a lot!
