### ISSUE TITLE
Torchbench doesn't work with USE_DISTRIBUTED=0

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#102086]
### 🐛 Describe the bug

Running `python benchmarks/dynamo/torchbench.py` after building with `USE_DISTRIBUTED=0` hits the following error. It'd be good to build with `USE_DISTRIBUTED=0` in CI in one of the tests that's using torchbench to avoid regressions of this kind.

```python
Traceback (most recent call last):
  File "benchmarks/dynamo/torchbench.py", line 16, in <module>
    from common import BenchmarkRunner, main
  File "/home/paperspace/git/pytorch/benchmarks/dynamo/common.py", line 39, in <module>
    from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
  File "/home/paperspace/git/pytorch/torch/distributed/fsdp/__init__.py", line 1, in <module>
    from .flat_param import FlatParameter
  File "/home/paperspace/git/pytorch/torch/distributed/fsdp/flat_param.py", line 30, in <module>
    from torch.distributed._tensor import DTensor
  File "/home/paperspace/git/pytorch/torch/distributed/_tensor/__init__.py", line 6, in <module>
    import torch.distributed._tensor.ops
  File "/home/paperspace/git/pytorch/torch/distributed/_tensor/ops/__init__.py", line 2, in <module>
    from .embedding_ops import *  # noqa: F403
  File "/home/paperspace/git/pytorch/torch/distributed/_tensor/ops/embedding_ops.py", line 6, in <module>
    from torch.distributed._tensor.api import _Partial, DTensorSpec, Replicate, Shard
  File "/home/paperspace/git/pytorch/torch/distributed/_tensor/api.py", line 8, in <module>
    import torch.distributed._tensor.dispatch as op_dispatch
  File "/home/paperspace/git/pytorch/torch/distributed/_tensor/dispatch.py", line 10, in <module>
    from torch.distributed._tensor.device_mesh import DeviceMesh
  File "/home/paperspace/git/pytorch/torch/distributed/_tensor/device_mesh.py", line 6, in <module>
    import torch.distributed._functional_collectives as funcol
  File "/home/paperspace/git/pytorch/torch/distributed/_functional_collectives.py", line 6, in <module>
    import torch.distributed.distributed_c10d as c10d
  File "/home/paperspace/git/pytorch/torch/distributed/distributed_c10d.py", line 17, in <module>
    from torch._C._distributed_c10d import (
ModuleNotFoundError: No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package
```

### Versions

master

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by H-Huang** [comment]
A fix might just be to guard DDP and FSDP imports in `benchmark/dynamo/common.py` like we do for xla

https://github.com/pytorch/pytorch/blob/e132f09e8878418fb98a4b76a441a324452354ec/benchmarks/dynamo/common.py#L50-L54

**Comment by lezcano** [comment]
Yep, that's what we do in many other places, e.g.,
https://github.com/pytorch/pytorch/blob/e132f09e8878418fb98a4b76a441a324452354ec/torch/_dynamo/allowed_functions.py#L112-L113
The fix should be along those lines, but it'd be good to have this config on CI so that we are sure we don't regress.

**Comment by albanD** [comment]
Do you actually try to use these components here or you only need the import to work @lezcano ?
I feel like a nicer fix would be to allow importing all distributed components even when built with USE_DISTRIBUTED=0.

**Comment by lezcano** [comment]
I just want to be able to use torchbench (and more generally, anything in PyTorch) when compiling with `USE_DISTRIBUTED=0`.

**Comment by wconstab** [comment]
@albanD is proposing a deeper change here where torch distributed APIs are all importable, regardless of build.  This would be a nice change. @kumpera do you have a sense how much effort this would be?

It seems like it'd be pretty trivial to just fix torchbench here to unblock this PR.  Maybe @xuzhao9 could help with a patch that stops us importing _C.distributed without a graceful try/except?

**Comment by albanD** [comment]
Note that there are cases where it's not possible to do a local fix for things like typing or public API checks!

**Comment by xuzhao9** [comment]
@wconstab From the stacktrace, it seems to be `pytorch/benchmarks/dynamo/common.py` importing FSDP, not the `pytorch/benchmark` code.

That being said, it is very likely that third-party model code in Torchbench also import FSDP/DDP in their code or even being called to initialize the distributed environment. Currently we only test the code works on the PyTorch nightly release.

**Comment by wconstab** [comment]
thanks for pointing that out @xuzhao9 - I've put a simple patch up, which should unblock @lezcano.  I'm also going to spend a little time seeing what it takes to enable importing FSDP without a distributed build.
