### ISSUE TITLE
[Caffe2] Can I convert Caffe2 to Caffe?

### ISSUE THREAD

**Issue by dedoogong** [pytorch/pytorch#10203]
I'm trying to convert Keypoint-R-CNN example model based on Detectron/Caffe2 to Caffe. 
By default, Detectron divides the model into "base" part and "head" part, but I made a new Caffe prototxt including both keypoint net and net(base net) after extracting detectron_net.pbtxt and detectron_keypoint_net_pbtxt together and manually changed each names of items. 

Also, I found it's possible to convert all of Caffe2's weight/bias to numpy arrays and then those to Caffe using FetchBlob("weight name").
 
But now, I feel confused that it seems like, there would be no matching CUDA/cuDNN implementation in Caffe2 for Caffe's "Deconvolution(gpu)"  code( Does "ConvTranspose" work same as "Deconvolution"?)

Plus, some of Caffe's hyper parameters in prototxt are gone in Caffe2's pbtxt such as " num_output" or "lr_mult" in convolution_param. 

Not only that, Detectron's convert_pkl_to_pb.py converts the example weight file(.pkl, arond 480MB) to so small 2 .pb files(less than 200KB in total) with fusing AffineTransform option. If I apply this fusing option, it merge some blobs, so the original network structure is changed and reduced. As there is no AffineTransform layer in Caffe, I need to turn on this option. 

So, I would like someone to tell me that Caffe2 can be translated to Caffe or not.
Is there anybody who succeed in converting Caffe2 model to Caffe?
I'm also considering ONNX or MMdnn. 

Thank you in advance!

**Comment by dedoogong** [comment]
now I ported caffe2 to caffe successfully~!

**Comment by RyanHTR** [comment]
> now I ported caffe2 to caffe successfully~!

Hi. Could you elaborate how you convert Caffe2 model to Caffe? I am trying to convert Mask R-CNN based on Detectron/Caffe2 to Caffe. Thanks very much~

**Comment by frizk123** [comment]
> now I ported caffe2 to caffe successfully~!

How did you do that?

**Comment by gangulypritha** [comment]
> now I ported caffe2 to caffe successfully~!

Hi, Could you kindly elaborate on the procedure?

**Comment by fuzzyBatman** [comment]
> now I ported caffe2 to caffe successfully~!

This is not helping the rest of us :'(

**Comment by reactivetype** [comment]
@dedoogong  Can you please explain which method or tool you used? Thank you.
