### ISSUE TITLE
Torch metaclass conflict error

### ISSUE THREAD

**Issue by nitesh-acog** [pytorch/pytorch#102069]
### 🐛 Describe the bug

My error specifically says
from torch_geometric.nn import MessagePassing
# inheriting message passing itself gave this metaclass conflict.
```
packages/torch_geometric/init.py", line 2, in
import torch_geometric.data
File "/opt/conda/lib/python3.9/site-packages/torch_geometric/data/init.py", line 7, in
from .batch import Batch
File "/opt/conda/lib/python3.9/site-packages/torch_geometric/data/batch.py", line 11, in
from torch_geometric.data.dataset import IndexType
File "/opt/conda/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 20, in
class Dataset(torch.utils.data.Dataset, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases.
```

I had to remove all the abstract classes from all the dependent modules in site packages of torch to make it work .
python=3.9.16
torch=1.13.1
torch_geometric=2.3.1

### Versions

python=3.9.16
torch=1.13.1
torch_geometric=2.3.1

**Comment by soulitzer** [comment]
Closing because it sounds like this issue should be opened at torch_geometric.
Feel free to reopen if you think this is a problem with pytorch itself, it would be nice to have a pytorch only repro.

**Comment by deardeer7** [comment]
> ### 🐛 Describe the bug
> My error specifically says from torch_geometric.nn import MessagePassing
> 
> # inheriting message passing itself gave this metaclass conflict.
> ```
> packages/torch_geometric/init.py", line 2, in
> import torch_geometric.data
> File "/opt/conda/lib/python3.9/site-packages/torch_geometric/data/init.py", line 7, in
> from .batch import Batch
> File "/opt/conda/lib/python3.9/site-packages/torch_geometric/data/batch.py", line 11, in
> from torch_geometric.data.dataset import IndexType
> File "/opt/conda/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 20, in
> class Dataset(torch.utils.data.Dataset, ABC):
> TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases.
> ```
> 
> I had to remove all the abstract classes from all the dependent modules in site packages of torch to make it work . python=3.9.16 torch=1.13.1 torch_geometric=2.3.1
> 
> ### Versions
> python=3.9.16 torch=1.13.1 torch_geometric=2.3.1

Hello, I also encountered this problem. Have you solved it? If so, how did you resolve it?
