### ISSUE TITLE
RuntimeError: Could not infer dtype of numpy.int64

### ISSUE THREAD

**Issue by yurivict** [pytorch/pytorch#102026]
### 🐛 Describe the bug

The following error occurs while running one Deep Graph Library testcase:
```
[yuri@yv /usr/ports/math/py-dgl/work-py39/dgl-1.1.0/examples/pytorch/mvgrl/graph]$ python3.9 main.py 
Traceback (most recent call last):
  File "/usr/ports/math/py-dgl/work-py39/dgl-1.1.0/examples/pytorch/mvgrl/graph/main.py", line 70, in <module>
    dataset = load(args.dataname)
  File "/usr/ports/math/py-dgl/work-py39/dgl-1.1.0/examples/pytorch/mvgrl/graph/dataset.py", line 182, in load
    graph = dgl.graph(edge_indexes)
  File "/usr/local/lib/python3.9/site-packages/dgl/convert.py", line 162, in graph
    (sparse_fmt, arrays), urange, vrange = utils.graphdata2tensors(data, idtype)
  File "/usr/local/lib/python3.9/site-packages/dgl/utils/data.py", line 186, in graphdata2tensors
    data.format, tuple(F.tensor(a) for a in data.arrays)
  File "/usr/local/lib/python3.9/site-packages/dgl/utils/data.py", line 186, in <genexpr>
    data.format, tuple(F.tensor(a) for a in data.arrays)
  File "/usr/local/lib/python3.9/site-packages/dgl/backend/pytorch/tensor.py", line 52, in tensor
    return th.as_tensor(data, dtype=dtype)
RuntimeError: Could not infer dtype of numpy.int64
```

requirements.txt doesn't require any particular version of numpy, so numpy-1.23.1 should be suitable.

### Versions

py39-pytorch-2.0.0
py39-numpy-1.23.1,1
py39-dgl-1.1.0
FreeBSD 13.2 STABLE

cc @mruberry @rgommers

**Comment by rgommers** [comment]
@yurivict this does not seem unexpected to me. A numpy dtype isn't a pytorch dtype, and I have no expectations about using a numpy dtype as an argument to a pytorch function will work. Is this a regression? If so, do you know what version of pytorch or numpy broke things for you?

**Comment by yurivict** [comment]
I don't know if this is a regression. I didn't run with previous versions.

Could it be a problem that PyTorch is built w/out Numpy support?

**Comment by rgommers** [comment]
Not impossible, but I have a regular PyTorch 1.9.0 install with Conda and can reproduce this:
```python
>>> import torch
>>> import numpy as np
>>> t = torch.as_tensor([3, 4], dtype=torch.int64)
>>> t = torch.as_tensor([3, 4], dtype=np.int64)
Traceback (most recent call last):
  File "<ipython-input-9-e7361c5bb7d8>", line 1, in <module>
    t = torch.as_tensor([3, 4], dtype=np.int64)
TypeError: as_tensor(): argument 'dtype' must be torch.dtype, not type
```

I think this is a case of "please don't do that".

**Comment by yurivict** [comment]
In case of DGL the error message is different (same as in the subject).

I don't know what is going on. When DGL was released they probably tested it and it probably succeeded somehow.

**Comment by rgommers** [comment]
I had a look at the DGL code, it's at https://github.com/dmlc/dgl/blob/c83350dade3d0d2062c1a61a9b6a15d7db1f4016/python/dgl/utils/data.py#L168-L186. It looks like a bug in DGL to me, the intent is to keep the `int64`/`int32` dtype, but not to mix dtype objects between libraries. I suggest you file an issue against DGL, and if they do think there's something in PyTorch (or NumPy) that broke a contract, a standalone reproducer would be helpful.

**Comment by yurivict** [comment]
When PyTorch is built with Numpy support this error goes away.

**Comment by yurivict** [comment]
Building PyTorch with Numpy fixes the problem.
