### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_70'

### ISSUE THREAD

**Issue by zhengduoru** [pytorch/pytorch#10201]
my environment:
Centos
python3.6
CUDA9.0
cudnn7.0
and my server GPU is V100

what can I do when  nvcc fatal   : Unsupported gpu architecture 'compute_70'

**Comment by soumith** [comment]
please use the issue template and re-file the issue. We dont have enough information to help you. https://raw.githubusercontent.com/pytorch/pytorch/master/.github/ISSUE_TEMPLATE.md
