### ISSUE TITLE
"setup.py clean" deletes configuration files of IDE.

### ISSUE THREAD

**Issue by shkit** [pytorch/pytorch#10206]
## Issue description

I'm using Visual Studio Code and Visual Studio. These IDEs store configurations to FOLDER/.vscode and FOLDER/.vs.
When I do "setup.py clean", these folders are deleted because those are described in .gitignore file.
Thus I need to reconfigure IDE settings whenever I executes "setup.py clean".

I think a behaviour of "setup.py clean" may be overkill and might be need to add "clean_ignore_list" (contain .vscode, .vs, and so on) to setup.py.

**Comment by ezyang** [comment]
Happy to take a patch that fixes this. We can probably split the .gitignore file into a "should be cleaned" and "should not be cleaned" section, and only read out the should be cleaned section.

**Comment by peterjc123** [comment]
@ezyang @soumith It seems the PR is merged, can we close this issue?

**Comment by soumith** [comment]
closed via #10233
