### ISSUE TITLE
HuggingFace models for inductor tests should be proxied or cached

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#102181]
Otherwise the tests fail if there is a HuggingFace server issue with things like this:

Failed to load model: 504 Server Error: Gateway Time-out for url: https://huggingface.co/timm/lcnet_050.ra2_in1k/resolve/main/model.safetensors

Example failing workflow: https://github.com/pytorch/pytorch/actions/runs/5070248456/jobs/9105679021

**Comment by huydhn** [comment]
@PaliC has done some preliminary work on this.  Huggingface is tougher because of its size, but agree that we should find a way to handle upstream outage gracefully

**Comment by clee2000** [comment]
kind of dup of https://github.com/pytorch/pytorch/issues/95645
