### ISSUE TITLE
In Con2d layer,how to pad "Same" not "Zero"

### ISSUE THREAD

**Issue by a1363901216** [pytorch/pytorch#1021]
In Con2d layer,how to pad "Same" not "Zero".

In tensorflow , i see the option to choose whether pad  the "Same" pixel as edge or pad  "Zero" pixel .But dose pytorch have that option?

**Comment by soumith** [comment]
pytorch does not have this option. if you want to do something like this, you have to explicitly pad via nn.functional.pad in the replicate mode: http://pytorch.org/docs/nn.html#torch.nn.functional.pad

**Comment by a1363901216** [comment]
thanks

**Comment by rtaori** [comment]
Why does pytorch not have this feature? It would greatly help with quick prototyping
