### ISSUE TITLE
[Dynamo] Invalid link

### ISSUE THREAD

**Issue by weimingzha0** [pytorch/pytorch#102183]
### 📚 The doc issue

The link in the following test is broken:

We can find it on [line 20 of convert_frame.py](https://github.com/pytorch/torchdynamo/blob/main/torchdynamo/convert_frame.py#L200), with a signature as follows:

### Suggest a potential alternative/fix

We can find it on `line 222 of convert_frame.py
<https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/convert_frame.py#L222>`__, with a signature as follows:

cc @svekars @carljparker @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by weimingzha0** [comment]
PS: the doc is https://pytorch.org/docs/stable/dynamo/guards-overview.html

**Comment by ezyang** [comment]
Send us the fix, but use 'y' to turn this into a specific commit permalink
