### ISSUE TITLE
Verify if view_to_reshape conversion is safe in inductor

### ISSUE THREAD

**Issue by shunting314** [pytorch/pytorch#102229]
### 🚀 The feature, motivation and pitch

This issue tracks the followup to https://github.com/pytorch/pytorch/pull/99773#discussion_r1203256649 .

We do view_to_reshape conversion in the layout optimization PR ( https://github.com/pytorch/pytorch/pull/99773 ). But in general view to reshape conversion can be unsafe.

```
y = x.view(...)
x.mul_(2)
```

if we change view to reshape, y may lose the updates.

Alternatively
```
y = x.view(...)
y.mul_(2)
```
may also have issue.

But AOTAutograd may already handled the mutation nicely. Need verify.

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by ezyang** [comment]
This is AOTautograd/functionalization's job, there won't be any mutations in the graph at inductor.

**Comment by bdhirsh** [comment]
I think the risk here is mostly for inference, since inductor wants the copy_() mutations in the graph. If there's an input that we take a view of (that turns into a reshape + clone), and we mutate the view, inductor will be silently wrong.
