### ISSUE TITLE
torch.utils.checkpoint fails with torch.autograd.grad even when use_reentrant=False

### ISSUE THREAD

**Issue by mariusarvinte** [pytorch/pytorch#102223]
### 🐛 Describe the bug

The following code fails to execute with gradient checkpointing on the latest stable branch, even though the documentation for `use_reentrant=False` suggests that it should be compatible with `torch.autograd.grad`:

```python

import torch
from torch.utils.checkpoint import checkpoint

def run_fn(tensor):
    y = tensor * 2
    z = y.sum()
    grads = torch.autograd.grad(z, tensor)
    return grads[0]

x = torch.tensor([1.0, 2.0], requires_grad=True)
y = checkpoint(run_fn, x, use_reentrant=False)
z = y.sum()
z.backward()
print(x.grad)
```

Error traceback:
```
Traceback (most recent call last):
  File "/home/primitive_grad_cp.py", line 15, in <module>
    loss.backward()
  File "/home/user/miniconda3/envs/torch/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/user/miniconda3/envs/torch/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

There are also some comments in the `checkpoint` source code indicating that this behavior should be supported and even showing a minimal (but non-runnable) demo:
https://github.com/pytorch/pytorch/blob/f8896b7b0eac34e51dee243406b83bcac275cd4f/torch/utils/checkpoint.py#L578-L589

I've tried setting `retain_graph=True` in the `autograd.grad` call, but with no luck.

### Versions

OS: Ubuntu 20.04.4 LTS (x86_64)

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.6           py311ha02d727_1  
[conda] mkl_random                1.2.2           py311ha02d727_1  
[conda] numpy                     1.24.3          py311h08b1b3b_1  
[conda] numpy-base                1.24.3          py311hf175353_1  
[conda] pytorch                   2.0.1           py3.11_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2               py311_cu118    pytorch
[conda] torchtriton               2.0.0                     py311    pytorch
[conda] torchvision               0.15.2              py311_cu118    pytorch

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by soulitzer** [comment]
Hey, thanks for the report. This should be expected behavior because autograd.grad inside the forward producing a tensor that does not require grad. Typically you'd want to pass create_graph=True to autograd. to help with this, and additionally in this particular case, you'd also want to modify your function so that it has a second order derivative, e.g. by changing the mul by 2 into a sin.

```python
import torch
from torch.utils.checkpoint import checkpoint

def run_fn(tensor):
    y = tensor.exp()
    z = y.sum()
    grads = torch.autograd.grad(z, tensor, create_graph=True)
    return grads[0]

x = torch.tensor([1.0, 2.0], requires_grad=True)
y = checkpoint(run_fn, x, use_reentrant=False)
z = y.sum()
z.backward()
print(x.grad)
```

**Comment by mariusarvinte** [comment]
Thank you for the prompt reply and corrections, sorry for naively using `2*x`, indeed it doesn't have second order grads.

Your example makes sense, but running it leads to another error (had seen this before while trying many variants of `create_graph`, `retain_graph` and `torch.enable_grad` context):

```
Traceback (most recent call last):
  File "/home/marvinte/research/ode-attacks/primitive_grad_cp.py", line 38, in <module>
    y = checkpoint(run_fn, x, use_reentrant=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvinte/miniconda3/envs/torch_2p0_stable/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 251, in checkpoint
    return _checkpoint_without_reentrant(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvinte/miniconda3/envs/torch_2p0_stable/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 432, in _checkpoint_without_reentrant
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvinte/research/ode-attacks/primitive_grad_cp.py", line 34, in run_fn
    grads = torch.autograd.grad(z, tensor, create_graph=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvinte/miniconda3/envs/torch_2p0_stable/lib/python3.11/site-packages/torch/autograd/__init__.py", line 303, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvinte/miniconda3/envs/torch_2p0_stable/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 420, in unpack
    _unused = function(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvinte/research/ode-attacks/primitive_grad_cp.py", line 34, in run_fn
    grads = torch.autograd.grad(z, tensor, create_graph=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvinte/miniconda3/envs/torch_2p0_stable/lib/python3.11/site-packages/torch/autograd/__init__.py", line 303, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvinte/miniconda3/envs/torch_2p0_stable/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 402, in inner_unpack
    raise RuntimeError("You are calling backwards on a tensor that is never exposed. Please open an issue.")
RuntimeError: You are calling backwards on a tensor that is never exposed. Please open an issue.
```

What did end up working for us (credits to @dxoigmn) was to borrow a technique from MAML + checkpointing and actually set `use_reentrant=True` as in the snippet below:

```Python
import torch
from torch.utils.checkpoint import checkpoint

def run_fn(x):
    create_graph = torch.is_grad_enabled()
    with torch.enable_grad():
        y = torch.exp(x)
        z = y.sum()
        grads = torch.autograd.grad(z, x, create_graph=create_graph)[0]
    return grads if grads.requires_grad else grads.clone().requires_grad_(True)

x = torch.tensor([1.0, 2.0], requires_grad=True)
y = checkpoint(run_fn, x)
z = y.sum()
z.backward()
print(x.grad)
```

This runs successfully and produces a non-zero gradient, which also seems to be correct when used in minimization. Still a bit worried about the `clone` and whether this is the true gradient though.
```
tensor([2.7183, 7.3891])
```

**Comment by soulitzer** [comment]
From the error message it looks like you are still using an older version of PyTorch which doesn't have the latest version of checkpointing.

**Comment by mariusarvinte** [comment]
I am not sure if this intended, but is it possible that using `autograd.grad` inside a checkpoint with `use_reentrant=False` triggers an unnecessary function call?

See the code below, where we were able to use the workaround mentioned in https://github.com/pytorch/pytorch/issues/102223#issuecomment-1563292639 to achieve the same result using `use_reentrant=True` and only two function calls. When there's no `autograd.grad`, `use_reentrant=False` also leads to two proper function calls.

```Python
import torch
from torch.utils.checkpoint import checkpoint

def run_fn(tensor):
    print('Running with use_reentrant=False and autograd.grad')
    y = tensor.exp()
    z = y.sum()
    grads = torch.autograd.grad(z, tensor, create_graph=True)
    return grads[0]

x = torch.tensor([1.0, 2.0], requires_grad=True)
y = checkpoint(run_fn, x, use_reentrant=False)
z = y.sum()
z.backward()
print('Grad with use_reentrant=False', x.grad)

import torch
from torch.utils.checkpoint import checkpoint

def run_fn(x):
    print('Running with use_reentrant=True and autograd.grad')
    create_graph = torch.is_grad_enabled()
    with torch.enable_grad():
        y = torch.exp(x)
        z = y.sum()
        grads = torch.autograd.grad(z, x, create_graph=create_graph)[0]
    return grads

x = torch.tensor([1.0, 2.0], requires_grad=True)
y = checkpoint(run_fn, x, use_reentrant=True)
z = y.sum()
z.backward()
print('Grad with use_reentrant=True + workaround', x.grad)

def run_fn(tensor):
    print('Running with use_reentrant=False and no autograd.grad')
    y = tensor.exp()
    z = y.sum()
    output = z + tensor
    return output

x = torch.tensor([1.0, 2.0], requires_grad=True)
y = checkpoint(run_fn, x, use_reentrant=False)
z = y.sum()
z.backward()
```
And its output on the nightly version:
```
Running with use_reentrant=False and autograd.grad
Running with use_reentrant=False and autograd.grad
Running with use_reentrant=False and autograd.grad
Grad with use_reentrant=False tensor([2.7183, 7.3891])
Running with use_reentrant=True and autograd.grad
Running with use_reentrant=True and autograd.grad
Grad with use_reentrant=True + workaround tensor([2.7183, 7.3891])
Running with use_reentrant=False and no autograd.grad
Running with use_reentrant=False and no autograd.grad
```

The gradients appear to be correct, we didn't measure the exact overhead (run/memory), but the additional function call did stand out. We won't rely on the workaround, just thought it may be relevant to bring up.
