### ISSUE TITLE
torch.sum got error output on aarch64 machine

### ISSUE THREAD

**Issue by heidongxianhua** [pytorch/pytorch#102258]
### 🐛 Describe the bug

on ARM64 machine,

```
import torch
a = torch.ones(2,3,6).float()
b = torch.sum(a)
print(b)
# got tensor(28.), it should be 36
c = torch.mean(a)
print(c)
# tensor(0.7778), it should be 1.
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gita8ea417
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (AltArch) (aarch64)
GCC version: (GCC) 8.3.0
Clang version: 15.0.5 (clang-5c68a1cb1231 flang-5c68a1cb1231)
CMake version: version 3.18.1
Libc version: glibc-2.32

Python version: 3.8.16 (default, Mar  2 2023, 03:16:31)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.14.0-115.el7a.0.1.aarch64-aarch64-with-glibc2.26
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                192
On-line CPU(s) list:   0-191
Thread(s) per core:    1
Core(s) per socket:    48
Socket(s):             4
NUMA node(s):          4
Model:                 0
CPU max MHz:           2600.0000
CPU min MHz:           200.0000
BogoMIPS:              200.00
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              24576K
NUMA node0 CPU(s):     0-47
NUMA node1 CPU(s):     48-95
NUMA node2 CPU(s):     96-143
NUMA node3 CPU(s):     144-191
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0a0+gita8ea417
[pip3] torchvision==0.15.1
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.0.0a0+gitc263bd4          pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi

**Comment by soulitzer** [comment]
I cannot reproduce this on my arm64 machine

**Comment by ptrblck** [comment]
Based on the [Prerequisites](https://github.com/pytorch/pytorch#prerequisites):
> A C++17 compatible compiler, such as clang

C++17 is needed, which is fully supported in GCC 9+ according to [gcc.gnu.org/projects/cxx-status.](https://gcc.gnu.org/projects/cxx-status.html#cxx17):
> Some C++17 features are available since GCC 5, but support was experimental and the ABI of C++17 features was not stable until GCC 9. 

so it seems you might need to stick to GCC 9.4.0 or newer.

**Comment by FFFrog** [comment]
> Based on the [Prerequisites](https://github.com/pytorch/pytorch#prerequisites):
> 
> > A C++17 compatible compiler, such as clang
> 
> C++17 is needed, which is fully supported in GCC 9+ according to [gcc.gnu.org/projects/cxx-status.](https://gcc.gnu.org/projects/cxx-status.html#cxx17):
> 
> > Some C++17 features are available since GCC 5, but support was experimental and the ABI of C++17 features was not stable until GCC 9.
> 
> so it seems you might need to stick to GCC 9.4.0 or newer.

Ok, thank you for your reply :D
Btw, could you mind to show us the version of gcc/g++/cmake in ci/cd of meta?
