### ISSUE TITLE
vmap not working on torch.linspace

### ISSUE THREAD

**Issue by ConnorStoneAstro** [pytorch/pytorch#102208]
### 🐛 Describe the bug

For my current application I need to use linspace, meshgrid and some other functions that don't natively support batching. I am using vmap to batch the code which from what I understand should be supported. However I am getting the error below. 

I can get around linspace by using arange and a couple operations. But I am pretty sure this should work (or I am missing something really obvious) so I thought I should file a bug report.

Code to reproduce:
```python
import torch
from functools import partial

batch_lin = torch.vmap(partial(torch.linspace, steps = 10))
start = torch.tensor([1.,2.,3.])
stop = torch.tensor([25.,26.,27.])
print(batch_lin(start, stop))
```

Error trace:
```
Traceback (most recent call last):
  File "/home/connor/Documents/Life_2023/Summer/indexing test/vmaptest.py", line 7, in <module>
    print(batch_lin(start, stop))
  File "/home/connor/venvs/PY39/lib/python3.9/site-packages/torch/_functorch/vmap.py", line 434, in wrapped
    return _flat_vmap(
  File "/home/connor/venvs/PY39/lib/python3.9/site-packages/torch/_functorch/vmap.py", line 39, in fn
    return f(*args, **kwargs)
  File "/home/connor/venvs/PY39/lib/python3.9/site-packages/torch/_functorch/vmap.py", line 619, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
RuntimeError: vmap: It looks like you're calling .item() on a Tensor. We don't support vmap over calling .item() on a Tensor, please try to rewrite what you're doing with other operations. If error is occurring somewhere inside PyTorch internals, please file a bug report.
```

### Versions

PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Linux Mint 20 (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
Stepping:                        12
CPU MHz:                         3117.620
CPU max MHz:                     4100.0000
CPU min MHz:                     400.0000
BogoMIPS:                        3799.90
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        6 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] levmarq-torch==0.0.1
[pip3] numpy==1.24.3
[pip3] torch==2.0.0
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

**Comment by ConnorStoneAstro** [comment]
Related to this `torch.arange` seems to have the same issue with vmap. So I'm actually not sure what to do for a workaround without just a really big for loop.

**Comment by zou3519** [comment]
The following is kind of a workaround, assuming `start, end` are both Tensors:
```py
start + torch.arange(0, steps + 1) * (end - start) / (steps - 1)
```

**Comment by ConnorStoneAstro** [comment]
Thanks @zou3519 ! that is very helpful :) Hopefully a vmap-able version can be included in pytorch soon, but this will certainly cover my current situation

**Comment by zou3519** [comment]
Just so I remember:
- first thing we'd need to do is add a linspace/arange overload that take in Tensors and make sure the PyTorch dispatcher factory functions codegen doesn't implode
- after that, we would add a batching rule for linspace/arange

**Comment by zou3519** [comment]
Lifting priority due to user activity

**Comment by qqaatw** [comment]
Would like to implement the first thing (and the second perhaps), looks interesting to me.

**Comment by zou3519** [comment]
@qqaatw, please feel free

**Comment by ConnorStoneAstro** [comment]
@zou3519 if `torch.linspace` works then I think that is all I need. The place where I use `arange` is here: https://github.com/Autostronomy/AutoPhot/blob/e1f1f2ea5edfca3b42372f74c2f0fe4eb18d49e1/autophot/image/image_header.py#L327

but your earlier comment demonstrates how to bypass vmap in `arange` and I think that will work for my scenario. I can even reproduce `arange` using `linspace` if it now accepts tensor arguments.

**Comment by zou3519** [comment]
I think this works now due to https://github.com/pytorch/pytorch/pull/105451? (cc @qqaatw to confirm)

**Comment by qqaatw** [comment]
Yes it should work. Let me know if you have any issues with it!
