### ISSUE TITLE
SequenceParallel produces incorrect results

### ISSUE THREAD

**Issue by dskhudia** [pytorch/pytorch#102280]
### 🐛 Describe the bug

With and without SequenceParallel I see completely different results for trained weights. Run the following script on >= 2 gpu system to reproduce the issue with a recent nightly build of PyTorch. I made sure that repeated runs of the script give the same results and init weights/randomly generated data is the same between parallel/no-parallel runs. I expect some differences in trained weights between the two due to parallelization causing different order of floating-point operations but the difference below seems like more than that. 

```
# compare printed results between these two invocations
python tp_test.py --world_size=2 --no-parallel
up_proj weights from rank 0: Parameter containing:
tensor([[ 0.3426,  0.4145, -0.1512,  0.5347],
        [-0.1410,  0.0398, -0.1694,  0.3112],
        [ 0.4646, -0.4368,  0.4722,  0.0977],
        [ 0.4059,  0.0838,  0.2833, -0.1676],
        [ 0.4057,  0.0864, -0.2370,  0.0982],
        [-0.2373, -0.0625, -0.1972,  0.3366],
        [-0.4108, -0.2630, -0.0346, -0.3649],
        [ 0.0012, -0.6982,  0.8978, -0.6387],
        [ 0.4212,  0.0048, -0.0502,  0.2359],
        [ 0.1207,  0.5201,  0.0743, -0.3389],
        [ 0.1208, -0.1652,  0.2325,  0.4673],
        [ 0.2753, -0.3249,  0.3791,  0.1172],
        [ 0.2760, -0.2949, -0.4984, -0.2219],
        [-0.4612,  0.4034,  0.2963,  0.1345],
        [ 0.1375, -0.0244,  0.4080, -0.3391],
        [ 0.0060, -0.5171,  0.4913, -0.3219]], device='cuda:0',
       requires_grad=True)
python tests/tp_test.py --world_size=2 --parallel
up_proj weights from rank 1: DTensor(local_tensor=tensor([[ 0.4413,  0.4390, -0.0543,  0.3170],
        [-0.1617,  0.0137, -0.1313,  0.3228],
        [ 0.4131, -0.3785,  0.4637,  0.1032],
        [ 0.4573,  0.1255,  0.3162, -0.2850],
        [ 0.4140,  0.1107, -0.2445,  0.0729],
        [-0.3083, -0.3576,  0.0914,  0.4270],
        [-0.3838, -0.2067, -0.1727, -0.2991],
        [ 0.0139, -1.0228,  1.7231, -1.0329]], device='cuda:1'), device_mesh=DeviceMesh:([0, 1]), placements=[Shard(dim=0)])
up_proj weights from rank 0: DTensor(local_tensor=tensor([[ 0.4413,  0.4390, -0.0543,  0.3170],
        [-0.1617,  0.0137, -0.1313,  0.3228],
        [ 0.4131, -0.3785,  0.4637,  0.1032],
        [ 0.4573,  0.1255,  0.3162, -0.2850],
        [ 0.4140,  0.1107, -0.2445,  0.0729],
        [-0.3083, -0.3576,  0.0914,  0.4270],
        [-0.3838, -0.2067, -0.1727, -0.2991],
        [ 0.0139, -1.0228,  1.7231, -1.0329]], device='cuda:0'), device_mesh=DeviceMesh:([0, 1]), placements=[Shard(dim=0)]) 
```

```
# tp_test.py
import argparse
import os
from packaging import version
import torch
import torch.nn as nn
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
from torch.distributed.tensor.parallel.fsdp import enable_2d_with_fsdp
from torch.utils.data import DataLoader, Dataset
from torch.nn.parallel import DistributedDataParallel as DDP

def is_torch_2_or_higher():
    if version.parse(torch.__version__) >= version.parse('2.0.0'):
        return True
    return False

if is_torch_2_or_higher():
    from torch.distributed._tensor import DeviceMesh  # type: ignore
    from torch.distributed.tensor.parallel import \
        parallelize_module  # type: ignore
    from torch.distributed.tensor.parallel.fsdp import \
        enable_2d_with_fsdp  # type: ignore
    from torch.distributed.tensor.parallel.style import SequenceParallel

class MyDataset(Dataset):
    def __init__(self, random_seed):
        super().__init__()
        torch.manual_seed(random_seed)
        self.values = torch.randn(4, 4)

    def __len__(self):
        return len(self.values)

    def __getitem__(self, index):
        return self.values[index]
class MPTMLP(nn.Module):

    def __init__(self,
                 d_model: int,
                 expansion_ratio: int,
                 device = None):
        super().__init__()
        self.up_proj = nn.Linear(d_model,
                                 expansion_ratio * d_model,
                                 device=device)
        self.act = nn.GELU(approximate='none')
        self.down_proj = nn.Linear(expansion_ratio * d_model,
                                   d_model,
                                   device=device)
        self.down_proj._is_residual = True  # type: ignore

    def forward(self, x):
        return self.down_proj(self.act(self.up_proj(x)))

class myMod(nn.Module):
    def __init__(self):
        super().__init__()
        self.ln1 = nn.LayerNorm(4)
        self.mlp = MPTMLP(4, 4, device='cpu')

    def forward(self, x):
        x = self.ln1(x)
        x = self.mlp(x)
        return x
 def setup(rank, world_size):
    torch.manual_seed(42)
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "12355"
    # initialize the process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
    torch.cuda.set_device(rank)
    print(f" rank {rank} has joined")


def cleanup():
    dist.destroy_process_group()
def demo_2d(rank, args):
    """
    """
    setup(rank, args.world_size)
    oned_mesh = DeviceMesh(
        device_type="cuda",
        mesh=torch.arange(0, args.world_size),
    )

    model = myMod().cuda(rank)

    if args.parallel:
        model = parallelize_module(
            model,
            oned_mesh,
            {"mlp": SequenceParallel()},
        )
    model.cuda(rank)
    fsdp_is_available = enable_2d_with_fsdp()
    if not fsdp_is_available:
        raise RuntimeError("2D parallelism with FSDP is not available but required!")

    model = FSDP(model)
    # Create a optimizer for the parallelized module.
    LR = 0.25
    optimizer = torch.optim.SGD(model.parameters(), lr=LR)

    dataset = MyDataset(0)

    sampler = torch.utils.data.DistributedSampler(dataset)
    dataloader = DataLoader(dataset, shuffle=False, sampler=sampler)
    for data in dataloader:
        data = data.cuda(rank)
        output = model(data)
        loss = output.sum()
        loss.backward()
        optimizer.step()

    with FSDP.summon_full_params(model):
        print(f"up_proj weights from rank {rank}: {model.mlp.up_proj.weight}")
    cleanup()
def run_demo(demo_fn, args):
    mp.spawn(demo_fn, args=(args,), nprocs=args.world_size, join=True)


if __name__ == "__main__":
    n_gpus = torch.cuda.device_count()
    parser = argparse.ArgumentParser()
    # This is passed in via cmd
    parser.add_argument("--world_size", type=int, default=n_gpus)
    parser.add_argument("--iter_nums", type=int, default=4)
    parser.add_argument("--model_parallel_size", type=int, default=2)
    parser.add_argument("--parallel", action=argparse.BooleanOptionalAction)
    args = parser.parse_args()
    # The main entry point is called directly without using subprocess
    if n_gpus < 2:
        print("Requires at least 2 GPUs to run.")
    elif not is_torch_2_or_higher():
        print(
            "PyTorch doesn't have Tensor Parallelism available," " need >= 2.0"
        )
    else:
        run_demo(demo_2d, args)
```

### Versions

Collecting environment information...

Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB

Nvidia driver version: 515.48.07
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              1
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7513 32-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         1499.640
CPU max MHz:                     2600.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        5200.48
Virtualization:                  AMD-V
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-7
NUMA node1 CPU(s):               8-15
NUMA node2 CPU(s):               16-23
NUMA node3 CPU(s):               24-31
NUMA node4 CPU(s):               32-39
NUMA node5 CPU(s):               40-47
NUMA node6 CPU(s):               48-55
NUMA node7 CPU(s):               56-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0.dev20230524+cu118
[pip3] torchaudio==2.1.0.dev20230524+cu118
[pip3] torchvision==0.16.0.dev20230524+cu118
[conda] No relevant packages

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by awgu** [comment]
cc: @fduwjj

**Comment by dskhudia** [comment]
This seems like interaction better DTensor and FSDP sharding is messing up the weights. The following are DTensors printed before FSDP and after the model was FSDP'ed. After FSDP'ed model has the same local DTensor on both the ranks. 

```
    print(f"before FSDP up_proj weights from rank {rank}: {model.mlp.up_proj.weight}")
    model = FSDP(model)
    with FSDP.summon_full_params(model):
        print(f"after FSDP up_proj weights from rank {rank}: {model.mlp.up_proj.weight}")
```

```
before FSDP up_proj weights from rank 0: DTensor(local_tensor=tensor([[ 0.3823,  0.4150, -0.1171,  0.4593],
        [-0.1096,  0.1009, -0.2434,  0.2936],
        [ 0.4408, -0.3668,  0.4346,  0.0936],
        [ 0.3694,  0.0677,  0.2411, -0.0706],
        [ 0.3854,  0.0739, -0.2334,  0.1274],
        [-0.2304, -0.0586, -0.2031,  0.3317],
        [-0.3947, -0.2305, -0.1412, -0.3006],
        [ 0.0472, -0.4938,  0.4516, -0.4247]], device='cuda:0'), device_mesh=DeviceMesh:([0, 1]), placements=[Shard(dim=0)])
before FSDP up_proj weights from rank 1: DTensor(local_tensor=tensor([[ 0.3860,  0.0832, -0.1624,  0.3090],
        [ 0.0779,  0.4040,  0.0547, -0.1577],
        [ 0.1343, -0.1356,  0.2104,  0.4464],
        [ 0.2890, -0.2186,  0.2886,  0.0895],
        [ 0.2539, -0.3048, -0.4950, -0.1932],
        [-0.3835,  0.4103,  0.1440,  0.2071],
        [ 0.1581, -0.0087,  0.3913, -0.3553],
        [ 0.0315, -0.3413,  0.1542, -0.1722]], device='cuda:1'), device_mesh=DeviceMesh:([0, 1]), placements=[Shard(dim=0)])
after FSDP up_proj weights from rank 0: DTensor(local_tensor=tensor([[ 0.3823,  0.4150, -0.1171,  0.4593],
        [-0.1096,  0.1009, -0.2434,  0.2936],
        [ 0.4408, -0.3668,  0.4346,  0.0936],
        [ 0.3694,  0.0677,  0.2411, -0.0706],
        [ 0.3854,  0.0739, -0.2334,  0.1274],
        [-0.2304, -0.0586, -0.2031,  0.3317],
        [-0.3947, -0.2305, -0.1412, -0.3006],
        [ 0.0472, -0.4938,  0.4516, -0.4247]], device='cuda:0'), device_mesh=DeviceMesh:([0, 1]), placements=[Shard(dim=0)])
after FSDP up_proj weights from rank 1: DTensor(local_tensor=tensor([[ 0.3823,  0.4150, -0.1171,  0.4593],
        [-0.1096,  0.1009, -0.2434,  0.2936],
        [ 0.4408, -0.3668,  0.4346,  0.0936],
        [ 0.3694,  0.0677,  0.2411, -0.0706],
        [ 0.3854,  0.0739, -0.2334,  0.1274],
        [-0.2304, -0.0586, -0.2031,  0.3317],
        [-0.3947, -0.2305, -0.1412, -0.3006],
        [ 0.0472, -0.4938,  0.4516, -0.4247]], device='cuda:1'), device_mesh=DeviceMesh:([0, 1]), placements=[Shard(dim=0)])
```

**Comment by fduwjj** [comment]
Looks like you only have 2 GPUs and currently we can support 1 rank per GPU. So there is no way to do 2D parallel there. You might need to first create a 2D device mesh like what we did in https://github.com/pytorch/examples/blob/main/distributed/tensor_parallelism/two_d_parallel_example.py. Thanks!

**Comment by dskhudia** [comment]
@fduwjj Thanks for taking a look. What I am trying is slightly different. For 2-gpu example, rank 0 and rank 1 sequence parallelize a block using a 1-D deviceMesh, FSDP across rank 0 and rank 1 and then use the standard dataloader with distributedSampler. Since sequence parallel can accept different inputs across tp ranks, this should work right?

**Comment by fduwjj** [comment]
We don't recommend multiple ranks per GPU unfortunately. Closed the issue for now since this is not a bug indeed.
