### ISSUE TITLE
OOM kill on pip install

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#1022]
When I attempt to install Torch with pip, the process gets OOM killed:

```
ezyang@sabre:~/Dev$ pip install https://download.pytorch.org/whl/cu75/torch-0.1.10.post2-cp27-none-linux_x86_64.whl 
Collecting torch==0.1.10.post2 from https://download.pytorch.org/whl/cu75/torch-0.1.10.post2-cp27-none-linux_x86_64.whl
  Downloading https://download.pytorch.org/whl/cu75/torch-0.1.10.post2-cp27-none-linux_x86_64.whl (360.3MB)
    99% |████████████████████████████████| 360.3MB 32.1MB/s eta 0:00:01Killed
```

dmesg:

```
[326093.958653] Out of memory: Kill process 14093 (pip) score 452 or sacrifice child
[326093.958669] Killed process 14093 (pip) total-vm:5029612kB, anon-rss:4217296kB, file-rss:4kB
```

Feel free to close this if it is by design that 4G is not enough memory to install Torch (yes I don't have very much memory) but perhaps there is something here worth investigating?

**Comment by soumith** [comment]
thanks for reporting this.

We ship binaries, which means that all pip is doing is: unzipping the package on your computer and moving files into the right location.

With this context, there is very little I see I can do from the package side to improve this.

When I get time, I can try to simulate this in a limited memory environment and try to find out the exact reasons and report something to the pip folks upstream, but as the task is not really actionable from my side, I'll close this issue.

**Comment by diwu1989** [comment]
You can `wget` the whl package locally and then run `pip install` on it, that seems to use less memory

**Comment by rkingery** [comment]
I'm still seeing this problem when trying to pip install torch inside the base Ubuntu Docker container. It'll get 99% installed and then kill. Other packages install fine.

**Comment by vikramriyer** [comment]
I am facing the exact issue as one faced by @rkingery.

**Comment by heiner** [comment]
Same issue here.

Can be fixed by increasing Docker memory (e.g. https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container).

@diwu1989's comment is interesting though: Is there a less demanding way of downloading and installing PyTorch than pip?

**Comment by heiner** [comment]
(Turns out a `pip download torch` followed by `pip install torch*.whl` does not go OOM for me.)

**Comment by perber** [comment]
I got the same issue. Another way to install the package is to use the --no-cache-dir option. 
It worked on our environment. 
`pip --no-cache-dir install torch`
Hopefully this helps some one.

**Comment by espears1** [comment]
I am experiencing this same problem but `--no-cache-dir` does not solve it.

**Comment by bthiban** [comment]
`RUN pip install -r requirements.txt --no-cache-dir ` when your torch is inside requirements.txt

**Comment by espears1** [comment]
@bthiban I mentioned that in https://github.com/pytorch/pytorch/issues/1022#issuecomment-722712423 but unfortunately is did not solve the problem.
