### ISSUE TITLE
Using torch.cuda.stream  in multiple GPUs cannot speed up

### ISSUE THREAD

**Issue by wangshankun** [pytorch/pytorch#102342]
i found using torch.cuda api unable to speed up；

Whether or not I add synchronization, this for loop always executes sequentially

![image](https://github.com/pytorch/pytorch/assets/3970271/9f35c9b7-7f83-49ab-9676-21c9c3152c97)

**This is my test code:**
```
import torch, time
import torch.cuda.comm
import torch.nn.functional as F

a = torch.randn(4, 8192, 4096)
b = a.clone()
c = a.clone()
x = torch.randn(4, 512, 8192)

tp_num = 4
tp_streams = [torch.cuda.Stream(device=i) for i in range(tp_num)]

a_chunks = torch.cuda.comm.scatter(a, devices=range(tp_num), dim=0)
b_chunks = torch.cuda.comm.scatter(b, devices=range(tp_num), dim=0)
c_chunks = torch.cuda.comm.scatter(c, devices=range(tp_num), dim=0)
x_chunks = torch.cuda.comm.broadcast(x, [i for i in range(tp_num)])

a_results = []
b_results = []
c_results = []

torch.cuda.synchronize()
st_time = time.time()
for i in range(tp_num):
    with torch.cuda.stream(tp_streams[i]):
        a_chunk = a_chunks[i].permute(0, 2, 1)
        a_chunk = torch.flatten(a_chunk, start_dim=0, end_dim=1)
        a_out   = F.linear(x_chunks[i], a_chunk) 

        b_chunk = b_chunks[i].permute(0, 2, 1)
        b_chunk = torch.flatten(b_chunk, start_dim=0, end_dim=1)
        b_out   = F.linear(x_chunks[i], b_chunk) 
    
        c_chunk = c_chunks[i].permute(0, 2, 1)
        c_chunk = torch.flatten(c_chunk, start_dim=0, end_dim=1)
        c_out   = F.linear(x_chunks[i], c_chunk) 
    
        a_results.append(a_out)
        b_results.append(b_out)
        c_results.append(c_out)
        #tp_streams[i].synchronize() #does not affect time
    #torch.cuda.synchronize(i)#Whether to synchronize in series, does not affect time
    
torch.cuda.synchronize()
a_res = torch.cuda.comm.gather(a_results, dim=0, destination='cuda:0')
b_res = torch.cuda.comm.gather(b_results, dim=0, destination='cuda:0')
c_res = torch.cuda.comm.gather(c_results, dim=0, destination='cuda:0')
print(time.time() - st_time)

is_equal = torch.equal(a_res, b_res) and torch.equal(a_res, c_res)
print(is_equal)
```

Collecting environment information...
PyTorch version: 1.10.0a0+ecc3718
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.0
Libc version: glibc-2.31

Python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-211-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.4.48
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.182.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       32
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7413 24-Core Processor
Stepping:                        1
CPU MHz:                         2645.031
BogoMIPS:                        5290.06
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        4 GiB
NUMA node0 CPU(s):               0-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw invpcid_single ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xsaves clzero arat pku ospke overflow_recov succor

Versions of relevant libraries:
[pip3] flake8==3.7.9
[pip3] numpy==1.23.5
[pip3] nvidia-dlprof-pytorch-nvtx==1.3.0
[pip3] onnx2pytorch==0.4.1
[pip3] pytorch-lightning==1.5.8
[pip3] pytorch-quantization==2.1.0
[pip3] pytorch-transformers==1.1.0
[pip3] pytorchcv==0.0.67
[pip3] torch==1.10.0a0+ecc3718
[pip3] torchmetrics==0.6.2
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.11.0a0
[pip3] torchvision==0.11.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] nvidia-dlprof-pytorch-nvtx 1.3.0                    pypi_0    pypi
[conda] onnx2pytorch              0.4.1                    pypi_0    pypi
[conda] pytorch-lightning         1.5.8                    pypi_0    pypi
[conda] pytorch-quantization      2.1.0                    pypi_0    pypi
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] pytorchcv                 0.0.67                   pypi_0    pypi
[conda] torch                     1.10.0a0+ecc3718          pypi_0    pypi
[conda] torchmetrics              0.6.2                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchtext                 0.11.0a0                 pypi_0    pypi
[conda] torchvision               0.9.1                    pypi_0    pypi

cc @ngimel

**Comment by ngimel** [comment]
Duplicate of #59692
