### ISSUE TITLE
[torch.compile] ModuleList does not correctly test for truth

### ISSUE THREAD

**Issue by chedatomasz** [pytorch/pytorch#102315]
### 🐛 Describe the bug

Truth testing of empty torch.nn.ModuleList() is broken under torch.compile.
Firstly, it sometimes returns true, breaking the contract of empty lists being falsy.
Moreover, `True if emptylist else False` evaluates differently than `bool(emptylist)`.
This is still reproducible in the latest nightly, as of May 25th, and using backend='eager'.

### Error logs

N/A

### Minified repro

```
#handcrafted repro, as no crash happens
import torch
print(torch.__version__) #2.1.0.dev20230525+cu118
class IfModule(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.emptylist = torch.nn.ModuleList()
  def forward(self):
    if self.emptylist:
      print("True")
    else:
      print("False")
    return

non_compiled = IfModule()
compiled = torch.compile(IfModule(), backend="eager")

print("Normal:")
non_compiled() #False
print("Compiled:")
compiled() #True

print("Related:")
print("Non compiled:")
print(bool(torch.nn.ModuleList())) #False
print("Compiled:")
print(bool(torch.compile(torch.nn.ModuleList()))) #True

def x():
  print(True if torch.nn.ModuleList() else False)
torch._dynamo.reset()
torch.compile(x, backend='eager')()#true

def x():
  print(bool(torch.nn.ModuleList()))
torch._dynamo.reset()
torch.compile(x, backend='eager')()#false


```

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230525+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.107+-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7B12
Stepping:                        0
CPU MHz:                         2250.000
BogoMIPS:                        4500.00
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        512 KiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save umip rdpid

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0.dev20230525+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

**Comment by chedatomasz** [comment]
cc @ptrblck

**Comment by eqy** [comment]
CC @jansel

**Comment by ngimel** [comment]
cc @yanboliang, should be an easy fix?

**Comment by yanboliang** [comment]
Yes, let me send a PR.

**Comment by chedatomasz** [comment]
The fix addresses only some variants of the issue. See below for new repro:
```
print(torch.__version__) #2.1.0.dev20230528+cu118
print("Issue 1: Change of truthiness of directly compiled module")
torch._dynamo.reset()
print("Non compiled:")
print(bool(torch.nn.ModuleList())) #False
print("Compiled:")
print(bool(torch.compile(torch.nn.ModuleList()))) #True

print("Issue 2: Change of if condition resolution")
def x():
  print(True if torch.nn.ModuleList() else False)
torch._dynamo.reset()
print("Non compiled:")
x() #False
print("Compiled:")
torch.compile(x, backend='eager')() #True

print("Issue 3: if(x) non-equivalent with if(bool(x)) - compare with output in Issue 2")
def x():
  print(True if bool(torch.nn.ModuleList()) else False)
torch._dynamo.reset()
print("Non compiled:")
x() #False
print("Compiled:")
torch.compile(x, backend='eager')() #False
```

**Comment by chedatomasz** [comment]
cc @yanboliang @eqy @jansel @ngimel

**Comment by ngimel** [comment]
The first example is invalid - you are not calling compiled module, and calling `torch.compile()` on a module produces callable which is supposed to return truthy boolean.

**Comment by yanboliang** [comment]
Yes, as @ngimel mentioned, the first example is invalid. For the second one, it's a very rare case which hits a Dynamo bug, I'll send a PR to fix it.
