### ISSUE TITLE
[Dynamo] Better graph-break message for unsupported ctx managers

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#102339]
### 🐛 Describe the bug

Repro:
```
import torch
import torch._dynamo
import logging
import warnings

torch._logging.set_logs(dynamo=logging.DEBUG)

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(10, 10)

    def forward(self, x):
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            return self.layer(x)


x = torch.randn(10, 10)

m = MyModule()
print(m(x))

opt_m = torch.compile(backend="eager", fullgraph=True)(m)
print(opt_m(x))
```

Error:
```
torch._dynamo.exc.Unsupported: setattr(UserDefinedObjectVariable) <slot wrapper '__setattr__' of 'object' objects>
```

The root cause is we can't handle the context manager, so we fall back to eager. Need to figure out a better way to handle unsupported context managers or print better logs.

### Versions

N/A

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov @ngimel

**Comment by anijain2305** [comment]
Perhaps a good action item is a better log.
