### ISSUE TITLE
CI bug, win-vs2019-cpu-py3 workflow failed

### ISSUE THREAD

**Issue by heidongxianhua** [pytorch/pytorch#102330]
### 🐛 Describe the bug

strange error
https://pipelines.actions.githubusercontent.com/serviceHosts/7d146c05-69c3-4c20-a0e7-818111670117/_apis/pipelines/1/runs/3004023/signedlogcontent/18?urlExpires=2023-05-26T03%3A07%3A05.1959641Z&urlSigningMethod=HMACV1&urlSignature=AjZxK0DxOmpX7XKnvkG3zaZQdx9PIjLJloHXon9zrOI%3D

### Versions

NA

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
The link you've shared have expired.

**Comment by heidongxianhua** [comment]
yeah, I push a null commit again and it works well.

**Comment by heidongxianhua** [comment]
but today I meet another strange errror ,it seems like internet error.
![image](https://github.com/pytorch/pytorch/assets/22924371/ada384bc-2cef-44bd-96c9-0d7e1f82e9f2)

**Comment by huydhn** [comment]
Yes, the latest error you share is a GitHub issue.  It happened across CI jobs last Friday for a while and didn't limit to only Windows.  You might also want to rebase any PR you have to include some recent CI fixes for Windows.

**Comment by heidongxianhua** [comment]
> Yes, the latest error you share is a GitHub issue. It happened across CI jobs last Friday for a while and didn't limit to only Windows. You might also want to rebase any PR you have to include some recent CI fixes for Windows.

yeah  now it is ok.
