### ISSUE TITLE
Libtorch C++: cannot load new tensor to cuda after cudaDeviceReset()

### ISSUE THREAD

**Issue by JMLiu-SEU** [pytorch/pytorch#102371]
### 🐛 Describe the bug

cudaDeviceReset();
torch::Device device(torch::kCUDA, 0);
cudaError_t error = cudaSetDevice(device.index());
if (error != cudaSuccess) {
    std::cerr << "Failed to set CUDA device: " << cudaGetErrorString(error) << std::endl;
}
real = real.to(device);
where real is a tensor already defined on cpu and there raise a memory exeption after execution this line.

### Versions

cuda11.6 
win10
RTX-3090Ti
libtorch-win-shared-with-deps-2.0.0+cu117

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @ngimel

**Comment by Aidyn-A** [comment]
What is the error message you are seeing? I guess this happens because of absence of cuda context. Could you please try this code snippet:
```C++
cudaDeviceReset();
torch::Device device(torch::kCUDA, 0);

cudaError_t error = cudaSetDevice(device.index());
if (error != cudaSuccess) {
std::cerr << "Failed to set CUDA device: " << cudaGetErrorString(error) << std::endl;
}

error = cudaFree(0);
if (error != cudaSuccess) {
std::cerr << "Failed to create CUDA context: " << cudaGetErrorString(error) << std::endl;
}

real = real.to(device);
```

**Comment by JMLiu-SEU** [comment]
no cudaError occured using your code until it comes to real=real.to(device), and it raised c10::Error in 0x00007FFA2302CB69.

**Comment by ezyang** [comment]
You need to lookup at the windows popup error modal (or make it show up if it's not showing up), it will tell you the actual problem. chances are something's wrong with cuda.

**Comment by JMLiu-SEU** [comment]
Actually I am using devicereset in a for loop, and I observed that when first enter the loop, proj.todevice is success and real.to 
device is still success after cudareset, However then secondlly enter the loop, proj.todevice failed 
for(int i=0;i<5;i++)
{
    proj = proj.to(device); //proj a cpu tensor
    cudaDeviceReset();
    real = real.to(device); //real a cpu tensor
} 
![image](https://github.com/pytorch/pytorch/assets/59131320/c06bf26a-f5d9-4e9f-bfd7-299f0576acc8)
and is this the popup error modal you are suggesting? I am using visual studio

**Comment by ngimel** [comment]
Why do you expect anything to work after cudaDeviceReset? When first initializing cuda, pytorch calls a few setup functions to make sure everything is operating properly, cudaDeviceReset destroys all allocated resources and no subsequent pytorch calls involving device functions will succeed.

**Comment by JMLiu-SEU** [comment]
As you can see, after called the cudaDeviceReset and did some operations, I reinitialized cuda in the for loop.

**Comment by JMLiu-SEU** [comment]
> You need to lookup at the windows popup error modal (or make it show up if it's not showing up), it will tell you the actual problem. chances are something's wrong with cuda.

actually I upgraded my cuda version to11.8 and the .to() function works well, Thankyou

**Comment by soad89** [comment]
> 
Did you just upgrade to 11.8? I tried, but it did not help on my side.
