### ISSUE TITLE
[Dynamo] Support several missing torch.* ops

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#102340]
### 🐛 Describe the bug

This is the list of torch.* ops that we are missing support, but was used frequently in 14k github models:
* torch.is_complex
* torch.get_autocast_gpu_dtype
* torch.nn.init._calculate_correct_fan

### Versions

N/A

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

**Comment by yanboliang** [comment]
For ```torch.nn.init._calculate_correct_fan``` we should add support under ```TorchVariable.call_function``` and compute the result during compilation. It's a bit complicated, so we can skip it for the hackday task.

**Comment by fduwjj** [comment]
Hi, @yanboliang do you mean something like 

`  result = TorchVariable(torch.mul, **options).call_function(
                tx, [result, kwargs["value"]], {}
            )`?
