### ISSUE TITLE
Add support ONNX Opset 19

### ISSUE THREAD

**Issue by giangluu352001** [pytorch/pytorch#102430]
### 🚀 The feature, motivation and pitch

Onnx v1.14.0 has just released opset 19 . Please add support for exporting DeformConv and AdaptiveAveragePool2d to opset 19.

**Comment by justinchuby** [comment]
Is AdaptiveAveragePool added in opset 19?

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
