### ISSUE TITLE
Build error - CUDA path containing backslash

### ISSUE THREAD

**Issue by cbogdanmihai** [pytorch/pytorch#10242]
Hello,

Having issues while building pytorch.
CUDA path is constructed or changed to have backslash but has an added "\include".

C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0\include

Environment: Win 10, Cuda 8, CUDDN 7.1, Py 2.7, cmake 3.12, VS 2017.

ERROR:

CustomBuild:
  Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/Release/caffe2_gpu_generated_THCReduceApplyUtils.cu.obj
  CMake Warning (dev) at caffe2_gpu_generated_THCReduceApplyUtils.cu.obj.Release.cmake:82 (set):
    Syntax error in cmake code at

      C:/PY/Projects/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCReduceApplyUtils.cu.obj.Release.cmake:82

    when parsing string

      C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include;C:/PY/Projects/pytorch/aten/src;C:/PY/Projects/pytorch/build;C:/PY/Projects/pytorch;;
  C:/PY/Projects/pytorch/third_party/protobuf/src;C:/PY/Projects/pytorch/cmake/../third_party/eigen;C:/PY/Projects/pytorch/cmake/../third_party/pybind11/in
  clude;C:/PY/Projects/pytorch/cmake/../third_party/cub;C:/PY/Projects/pytorch/third_party/onnx;C:/PY/Projects/pytorch/build/third_party/onnx;C:/Program Fi
  les/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include;C:/PY/Projects/pytorch/build/caffe2/at
  en/src/TH;C:/PY/Projects/pytorch/aten/src/TH;C:/PY/Projects/pytorch/aten/src/THC;C:/PY/Projects/pytorch/build/caffe2/aten/src/THC;C:/PY/Projects/pytorch/
  build/caffe2/aten/src/THC;C:/PY/Projects/pytorch/aten/src/THC;C:/PY/Projects/pytorch/aten/src/THCUNN;C:/PY/Projects/pytorch/aten/src/ATen/cuda;C:/PY/Proj
  ects/pytorch/build/caffe2/aten/src/TH;C:/PY/Projects/pytorch/aten/src/TH;C:/PY/Projects/pytorch/aten/src/TH;C:/PY/Projects/pytorch/build/caffe2/aten/src/
  TH;C:/PY/Projects/pytorch/aten/src;C:/PY/Projects/pytorch/build/caffe2/aten/src;C:/PY/Projects/pytorch/build/aten/src;C:/PY/Projects/pytorch/aten/src/THN
  N;C:/PY/Projects/pytorch/aten/src/THCUNN;C:/PY/Projects/pytorch/aten/src;C:/PY/Projects/pytorch/aten/../third_party/catch/single_include;C:/PY/Projects/p
  ytorch/build/caffe2/aten/src/ATen;C:/PY/Projects/pytorch/aten/src/ATen/..;C:/PY/Projects/pytorch/build/caffe2/aten/src/ATen;C:/PY/Projects/pytorch/third_
  party/protobuf/src;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include;C:/Pro
  gram Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0\include;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include

    Invalid escape sequence \i

    Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run
    "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy
    command to set the policy and suppress this warning.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) at caffe2_gpu_generated_THCReduceApplyUtils.cu.obj.Release.cmake:178 (execute_process):
    Syntax error in cmake code at

      C:/PY/Projects/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCReduceApplyUtils.cu.obj.Release.cmake:178

    when parsing string

      C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/bin/nvcc.exe;-M;-D__CUDACC__;C:/PY/Projects/pytorch/aten/src/THC/THCReduceApplyUtils.cu;-o;C:
  /PY/Projects/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCReduceApplyUtils.cu.obj.NVCC-depend;-ccbin;C:/Program
   Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64;-m64;-Dcaffe2_gpu_EXPORTS;-DNOMINMAX;-D_CRT_SECURE_NO_DEPRE
  CATE=1;-DUSE_MSC_ATOMICS=1;-Xcompiler;,"/wd4267","/wd4251","/wd4522","/wd4522","/wd4838","/wd4305","/wd4244","/wd4190","/wd4101","/wd4996","/wd4275","/EH
  a","-DONNX_NAMESPACE=onnx_torch","-openmp","/MP","/bigobj","-DHAVE_AVX_CPU_DEFINITION","-DHAVE_AVX2_CPU_DEFINITION","/MD","/O2","/Ob2","/DNDEBUG","/MP","
  /bigobj";-D_MWAITXINTRIN_H_INCLUDED;-D__STRICT_ANSI__;-Wno-deprecated-gpu-targets;-DONNX_NAMESPACE=onnx_torch;-gencode;arch=compute_50,code=sm_50;-Xcudaf
  e;--diag_suppress=cc_clobber_ignored;-Xcudafe;--diag_suppress=integer_sign_change;-Xcudafe;--diag_suppress=useless_using_declaration;-Xcudafe;--diag_supp
  ress=set_but_not_used;-Xcompiler;-MD;--expt-relaxed-constexpr;--expt-extended-lambda;-Xcompiler;/wd4819;-Xcompiler;/wd4503;-Xcompiler;/wd4190;-Xcompiler;
  /wd4244;-Xcompiler;/wd4251;-Xcompiler;/wd4275;-Xcompiler;/wd4522;-Wno-deprecated-gpu-targets;--expt-extended-lambda;-gencode;arch=compute_50,code=sm_50;-
  DCUDA_HAS_FP16=1;-D__CUDA_NO_HALF_OPERATORS__;-D__CUDA_NO_HALF_CONVERSIONS__;-D__CUDA_NO_HALF2_OPERATORS__;-DNVCC;-IC:/Program Files/NVIDIA GPU Computing
   Toolkit/CUDA/v8.0/include;-IC:/PY/Projects/pytorch/aten/src;-IC:/PY/Projects/pytorch/build;-IC:/PY/Projects/pytorch;-IC:/PY/Projects/pytorch/third_party
  /protobuf/src;-IC:/PY/Projects/pytorch/cmake/../third_party/eigen;-IC:/PY/Projects/pytorch/cmake/../third_party/pybind11/include;-IC:/PY/Projects/pytorch
  /cmake/../third_party/cub;-IC:/PY/Projects/pytorch/third_party/onnx;-IC:/PY/Projects/pytorch/build/third_party/onnx;-IC:/PY/Projects/pytorch/build/caffe2
  /aten/src/TH;-IC:/PY/Projects/pytorch/aten/src/TH;-IC:/PY/Projects/pytorch/aten/src/THC;-IC:/PY/Projects/pytorch/build/caffe2/aten/src/THC;-IC:/PY/Projec
  ts/pytorch/aten/src/THCUNN;-IC:/PY/Projects/pytorch/aten/src/ATen/cuda;-IC:/PY/Projects/pytorch/build/caffe2/aten/src;-IC:/PY/Projects/pytorch/build/aten
  /src;-IC:/PY/Projects/pytorch/aten/src/THNN;-IC:/PY/Projects/pytorch/aten/../third_party/catch/single_include;-IC:/PY/Projects/pytorch/build/caffe2/aten/
  src/ATen;-IC:/PY/Projects/pytorch/aten/src/ATen/..;-IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0\include

    Invalid escape sequence \i

    Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run
    "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy
    command to set the policy and suppress this warning.
  Call Stack (most recent call first):
    caffe2_gpu_generated_THCReduceApplyUtils.cu.obj.Release.cmake:203 (cuda_execute_process)
  This warning is for project developers.  Use -Wno-dev to suppress it.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26433 for x64
  Copyright (C) Microsoft Corporation.  All rights reserved.

  tmpxft_0000c0ec_00000000-1.cpp
  nvcc fatal   : Host compiler targets unsupported OS.
  CMake Error at caffe2_gpu_generated_THCReduceApplyUtils.cu.obj.Release.cmake:219 (message):
    Error generating
    C:/PY/Projects/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/Release/caffe2_gpu_generated_THCReduceApplyUtils.cu.obj

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited
with code 1. [C:\PY\Projects\pytorch\build\caffe2\caffe2_gpu.vcxproj]

**Comment by peterjc123** [comment]
The actual error is this:nvcc fatal : Host compiler targets unsupported OS. Please use MSVC 14.11 toolset.

**Comment by cbogdanmihai** [comment]
Using 14.11 toolset, following exact install instructions... Below is the build config:

-- ******** Summary ********
-- General:
--   CMake version         : 3.12.0
--   CMake command         : C:/Program Files/CMake/bin/cmake.exe
--   Git version           :
--   System                : Windows
--   C++ compiler          : C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
--   C++ compiler version  : 19.14.26433.0
--   BLAS                  : MKL
--   CXX flags             :         /wd4267 /wd4251 /wd4522 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /EHa -DONNX_NAMESPACE=onnx_torch -openmp /MP /bigobj
--   Build type            : Release
--   Compile definitions   : NOMINMAX;_CRT_SECURE_NO_DEPRECATE=1;USE_MSC_ATOMICS=1
--   CMAKE_PREFIX_PATH     :
--   CMAKE_INSTALL_PREFIX  : C:/PY/Projects/pytorch/torch/lib/tmp_install
--
--   BUILD_CAFFE2          : OFF
--   BUILD_ATEN            : ON
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_PYTHON          : OFF
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : OFF
--   USE_ASAN              : OFF
--   USE_ATEN              : OFF
--   USE_CUDA              : 1
--     CUDA static link    : OFF
--     USE_CUDNN           : ON
--     CUDA version        : 8.0
--     cuDNN version       : 7.1.4
--     CUDA root directory : C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0
--     CUDA library        : C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cuda.lib
--     cudart library      : C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cudart_static.lib
--     cublas library      : C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cublas.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cublas_device.lib
--     cufft library       : C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cufft.lib
--     curand library      : C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/curand.lib
--     cuDNN library       : C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0\lib/x64\cudnn.lib
--     nvrtc               : C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/nvrtc.lib
--     CUDA include path   : C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include
--     NVCC executable     : C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/bin/nvcc.exe
--     CUDA host compiler  : $(VCInstallDir)Tools/MSVC/$(VCToolsVersion)/bin/Host$(Platform)/$(PlatformTarget)
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_GLOO              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               :
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : OFF
--   USE_OBSERVERS         : OFF
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : OFF
--   Public Dependencies  :
--   Private Dependencies : cpuinfo;onnxifi_loader
-- Configuring done
-- Generating done
-- Build files have been written to: C:/PY/Projects/pytorch/build

(base) c:\PY\Projects\pytorch\build>msbuild INSTALL.vcxproj /p:Configuration=Release
Microsoft (R) Build Engine version 15.7.180.61344 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

**Comment by peterjc123** [comment]
Sorry, I updated my last post. You should use MSVC 2015 when you build for CUDA 8. Please refer to the build steps on the main page of this repo.

**Comment by peterjc123** [comment]
Have you skipped this part in the README:
```cmd
REM As for CUDA 8, VS2015 Update 2 or up is required to build PyTorch. Use the following two lines.
set "PREBUILD_COMMAND=%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
set PREBUILD_COMMAND_ARGS=x64
```

**Comment by cbogdanmihai** [comment]
No, using exact steps as described in the readme.md, but now I have found that changing the line:
set "PREBUILD_COMMAND=%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
to
set "PREBUILD_COMMAND=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
results in:

Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 05.08.2018 17:56:16.
Project "c:\PY\Projects\pytorch\build\INSTALL.vcxproj" on node 1 (default targets).
Project "c:\PY\Projects\pytorch\build\INSTALL.vcxproj" (1) is building "C:\PY\Projects\pytorch\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v 141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio t ools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\PY\Projects\pytorch\build\ZERO_CHECK.vcxproj]
Done Building Project "C:\PY\Projects\pytorch\build\ZERO_CHECK.vcxproj" (default targets) -- FAILED.

**Comment by peterjc123** [comment]
The build tools for v141 (Platform Toolset = 'v 141') cannot be found.
Just install it and try again.

**Comment by cbogdanmihai** [comment]
They are installed :) just checked

**Comment by peterjc123** [comment]
I see. Then you are probably using the wrong msbuild. Let's skip this and use ninja instead. Try these:
```cmd
pip install ninja
set CMAKE_GENERATOR=Ninja
REM And then the steps in README.md
```

**Comment by cbogdanmihai** [comment]
With ninja i have the following error:

[413/692] Linking CXX shared library bin\caffe2.dll
FAILED: bin/caffe2.dll lib/caffe2.lib
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=caffe2\CMakeFiles\caffe2.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo @CMakeFiles\caffe2.rsp  /out:bin\caffe2.dll /implib:lib\caffe2.lib /pdb:bin\caffe2.pdb /dll /version:0.0 /INCREMENTAL:NO   && cd ."

LINK: command "C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo @CMakeFiles\caffe2.rsp /out:bin\caffe2.dll /implib:lib\caffe2.lib /pdb:bin\caffe2.pdb /dll /version:0.0 /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\caffe2.dll.manifest" failed (exit code 1000) with the following output:
LINK : fatal error LNK1000: unknown error at 00007FF6FB5A4241; consult documentation for technical support options
ninja: build stopped: subcommand failed.
Failed to run 'tools\build_pytorch_libs.bat --use-cuda --use-nnpack caffe2 nanopb libshm_windows'

**Comment by peterjc123** [comment]
You'll need this patch: https://download.microsoft.com/download/8/1/d/81dbe6bb-ed92-411a-bef5-3a75ff972c6a/vc14-kb4020481.exe

**Comment by cbogdanmihai** [comment]
Seems it is now compiling. Thanks!
