### ISSUE TITLE
Best practices clarification for determining accelerator availability e.g should one use  `torch.has_mps` or `torch.backends.mps.is_available()` and so on for cuda, etc

### ISSUE THREAD

**Issue by dsm-72** [pytorch/pytorch#102484]
### 📚 The doc issue

What is the best way to check accelerator availability without knowing what system you are on / which version of torch is compiled?

Here is a very simplistic example

```python
accel = 'cpu'
if torch.backends.mps.is_available():
    accel = 'mps'
elif torch.cuda.is_available():
    accel = 'cuda'
```

Or should it be

```python
accel = 'cpu'
if torch.has_mps:
    accel = 'mps'
elif torch.has_cuda:
    accel = 'cuda'
```

### Suggest a potential alternative/fix

Clarify in the documentation somewhere. 

cc @svekars @carljparker @albanD @kulinseth @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/pytorch/issues/52675

**Comment by malfet** [comment]
Removing `module: mps` and adding `python-frontend` and  `triage_review` as I would like some feedback on the matter.
IMO it would be good to standardize on `torch.backends.XYZ.is_built()` and `torch.backends.XYZ.is_available()`

Looking at the implementation. `torch.has_cuda` is the same as `torch.backends.cuda.is_built()` and `torch.has_mps` is the same as `torch.backends.mps.is_built()`.

**Comment by dsm-72** [comment]
There is also `cudnn`

**Comment by janeyx99** [comment]
From discussion: the has_* seems to be private-intended and are not as well documented. We should standardize on the is_available(). 

Actionable next steps:
- [ ] Gradually deprecate the has_* versions. There's also the confusion of whether it means it's built vs available. @malfet 
- [ ] Standardize is_built() and is_available() as well

**Comment by dsm-72** [comment]
@malfet can we add somewhere in the docs about best practices for determining accelerators of an unknown system?
