### ISSUE TITLE
RuntimeError using torch.nn.functional.pad when using MPS

### ISSUE THREAD

**Issue by gordon0907** [pytorch/pytorch#102453]
### 🐛 Describe the bug

I'm having an issue with `torch.nn.function.pad` when using _MPS backend_ on an Apple Silicon macOS. I encountered this issue when I try to run a project made by others ([ECCV2022-RIFE](https://github.com/megvii-research/ECCV2022-RIFE)). Moreover, I have found a Closed Issue #87277  that reports a very similar bug to mine. The only difference is that I'm having this problem when using pad with `mode='replicate'` (instead of the default `'constant'`).

Here below is a minimal example to demonstrate the problem:
```
import torch
y = torch.rand((1, 1, 3, 32, 32))
y_pad = torch.nn.functional.pad(y, (5, 5, 5, 5, 5, 5), mode='replicate')
```
When the above code is run on CPU by default, everything works well and no error is raised.

But when the device is set to MPS and run the same code (as shown below):
```
import torch
y = torch.rand((1, 1, 3, 32, 32), device='mps')
y_pad = torch.nn.functional.pad(y, (5, 5, 5, 5, 5, 5), mode='replicate')
```
Below's error is raised:
```
Traceback (most recent call last):
  File "/Users/gordon/PycharmProjects/ECCV2022-RIFE/DEBUG.py", line 3, in <module>
    y_pad = torch.nn.functional.pad(y, (5, 5, 5, 5, 5, 5), mode='replicate')
RuntimeError: Argument #8: Padding size should be less than the corresponding input dimension, but got: padding (5, 5) at dimension 2 of input 5
```
Although I think this is probably a bug, I'm sorry for causing inconvenience if it turns out to be a misjudgment.

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[conda] No relevant packages

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by spzala** [comment]
With the current `main` branch (PT version 2.3.0a0+git8ec8d78), I couldn't reproduce the issue running the provided code snippet with `mps` backend on Apple M1 Max. We should close it @cpuhrsch @gordon0907 Thanks!

**Comment by gordon0907** [comment]
I gave it a try just now, using Pytorch 2.1.2, and I also cannot reproduce the issue anymore. So, I will close this issue here, thanks.

**Comment by spzala** [comment]
Thanks @gordon0907 !!
