### ISSUE TITLE
torch.onnx.errors.CheckerError: The model does not have an ir_version set properly.

### ISSUE THREAD

**Issue by zll0000** [pytorch/pytorch#102479]
### 🐛 Describe the bug

torch=1**.13.1
onnx=1.14.0

[libprotobuf ERROR /opt/conda/conda-bld/pytorch_1670525552411/work/third_party/protobuf/src/google/protobuf/message_lite.cc:457] onnx_torch.ModelProto exceeded maximum protobuf size of 2GB: 8266614040
Traceback (most recent call last):
  File "/data03/zhangxiaolei/anaconda3/envs/LLM/lib/python3.8/site-packages/torch/onnx/utils.py", line 1652, in _export
    _C._check_onnx_proto(proto, full_check=True)
RuntimeError: The model does not have an ir_version set properly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_construct_conformer.py", line 399, in <module>
    cli_main()
  File "model_construct_conformer.py", line 395, in cli_main
    main(args)
  File "model_construct_conformer.py", line 203, in main**
    return _main(cfg, sys.stdout)
  File "model_construct_conformer.py", line 299, in _main
    torch.onnx.export(
  File "/data03/anaconda3/envs/LLM/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/data03/anaconda3/envs/LLM/lib/python3.8/site-packages/torch/onnx/utils.py", line 1654, in _export
    raise errors.CheckerError(e)
torch.onnx.errors.CheckerError: The model does not have an ir_version set properly.

### Versions

torch=1**.13.1
onnx=1.14.0

**Comment by Adesoji1** [comment]
@zll0000  can you share the full code so i can resolve the issue for you by reproducing it?

**Comment by zll0000** [comment]
@Adesoji1 
I just export pytorch model to onnx with torch.onnx.export(),  the code as follows:
torch.onnx.export(
            encoder,
            (src_tokens),
            "encoder.onnx",
            opset_version=15,
            input_names=["src_tokens"],
            output_names=["output"],
            verbose=False,
            dynamic_axes={
            'src_tokens':{1:'input_len'},
            'output':{0:'output_len'}
            }
        )

but the model is large, so I meet the problem

**Comment by BowenBao** [comment]
Seems like this is the source of bug. It happens when torch model is < 2GB but exported ONNX model > 2GB.
```
[libprotobuf ERROR /opt/conda/conda-bld/pytorch_1670525552411/work/third_party/protobuf/src/google/protobuf/message_lite.cc:457] onnx_torch.ModelProto exceeded maximum protobuf size of 2GB: 8266614040
```

cc @fatcat-z

**Comment by MaanavD** [comment]
Hi @zll0000 , 

We’ve gone ahead and closed this issue because it is stale and should've been aided with #103278
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary.
