### ISSUE TITLE
Using Maximal Update Parametrization (µP) as the default initialization method

### ISSUE THREAD

**Issue by srkunze** [pytorch/pytorch#102477]
### 🚀 The feature, motivation and pitch

Using muP as the default parameter initializer as it represents a unique point in the parametrization space.

### Alternatives

Status Quo

### Additional context

https://github.com/microsoft/mup
https://arxiv.org/abs/2011.14522

cc @vincentqb @jbschlosser @albanD @janeyx99

**Comment by albanD** [comment]
Hey!
I'm afraid that changing the default initialization would be breaking backward compatibility so following old discussions about this, we were not favorable to do this.
If you want this to be added to torch.nn.init please open an issue for that and that might be a good addition!
