### ISSUE TITLE
[REQUEST] - Update Multiprocessing best practices with CPU device

### ISSUE THREAD

**Issue by mingfeima** [pytorch/pytorch#102498]
### 📚 The doc issue

The current documentation on `torch.multiprocessing` is primarily focusing on CUDA device. User is highly possible to encounter oversubscription issue when following the instructions on a CPU device. On a CPU device, it is usually necessary to do explicit thread affinity binding else well as numa control, just as explained at [Tuning Guide for AI on the 4th Generation Intel® Xeon® Scalable Processors](https://www.intel.com/content/www/us/en/developer/articles/technical/tuning-guide-for-ai-on-the-4th-generation.html)

Also the example from [mnist_hogwild](https://github.com/pytorch/examples/tree/main/mnist_hogwild) is better to be updated at the same time, to give a more clear hands-on practice of how to do multiprocessing on CPU device.

### Suggest a potential alternative/fix

We aim to complete the document as part of PyTorch Docathon 2023. cc @VitalyFedyunin @jingxu10

**Comment by svekars** [comment]
Closing as this seems to be completed.
