### ISSUE TITLE
torch.mean produces wrong computation result on Windows

### ISSUE THREAD

**Issue by bowen-xiao96** [pytorch/pytorch#10248]
## Issue description

PyTorch 0.4.0 torch.mean produces wrong result

## Code example

This happens when trying to calculate the mean pixel value of CIFAR10 dataset.
Following is the code:
```
import os, sys
import numpy as np

import torch

from torchvision.datasets import CIFAR10
from torch.utils.data import DataLoader
from torchvision import transforms

cifar10_dir = 'cifar'
dataset = CIFAR10(
    cifar10_dir,
    train=True,
    transform=transforms.ToTensor()
)

dataloader = DataLoader(
    dataset,
    batch_size=256,
    shuffle=False,
    num_workers=0,
    pin_memory=False,
    drop_last=False
)

# calculate mean and std of cifar10 training set
data = list()
for x, _ in dataloader:
    # x: torch tensor
    # n x c x h x w
    data.append(x)

data = torch.cat(data, dim=0)
print(data.size())

data = torch.transpose(data, 0, 1).contiguous()
data = data.view(data.size(0), -1)
print(data.size())
mean = torch.mean(data, dim=1)

print(mean)
```
It produces `tensor([ 0.3277,  0.3277,  0.3277])`

If we replace the last few lines with numpy calculation

```
data = data.numpy()
print(data.shape)

data = np.transpose(data, (1, 0, 2, 3))
data = np.reshape(data, (data.shape[0], -1))
print(data.shape)
mean = np.mean(data, axis=1)

print(mean)
```

The result is `[0.49139968 0.48215827 0.44653124]`, which is correct, while the computation results of standard deviation (torch.std and np.std) are the same
## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Enterprise 2016 LTSB
GCC version: (GCC) 6.4.0
CMake version: version 3.6.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.0)
[pip] torchfile (0.1.0)
[pip] torchnet (0.0.2)
[pip] torchvision (0.2.1)
[conda] pytorch-cpu               0.4.0           py36_cpuhe774522_1    pytorch
[conda] torchfile                 0.1.0                     <pip>
[conda] torchnet                  0.0.2                     <pip>
[conda] torchvision               0.2.1                     <pip>

**Comment by peterjc123** [comment]
@bowen-xiao96 Yes, I can reproduce this issue and I can get the same result on a Linux box.

**Comment by RohitKeshari** [comment]
@soumith any idea why it is happening. I can also reproduce this issue on ubuntu16.04 with PyTorch version '0.4.0'

**Comment by soumith** [comment]
I have tried to reproduce this on Linux and on OSX, I cannot reproduce the issue.

here are outputs:

Linux:
```
0.4.1
0.2.1
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /tmp/cifar-10-python.tar.gz
torch.Size([50000, 3, 32, 32])
torch.Size([3, 51200000])
tensor([0.4915, 0.4823, 0.4468])
```

OSX:

```
0.5.0a0+dfe459a
0.2.1
Files already downloaded and verified
(50000, 3, 32, 32)
(3, 51200000)
tensor([0.4915, 0.4823, 0.4468])
```

**Comment by bowen-xiao96** [comment]
@soumith problem seems to be specific to version 0.4.0. After I upgrade pytorch to 0.4.1 on Windows, the issue disappeared.

**Comment by aywi** [comment]
@bowen-xiao96 @peterjc123 @soumith @zou3519 This problem seems to be specific to CPU version of PyTorch 0.4.0. I can reproduce it on Windows 10 + PyTorch 0.4.0 using Bowen's code. But when I added `.cuda()` to the `data`, this problem disappeared. I guessed there are some floating-point numerical issues in the CPU version of C library, just like #8710 #9286. Not sure whether current version solved all the problems.

**Comment by soumith** [comment]
Okay it looks like we fixed it between 0.4.0 and 0.4.1. I think I remember the PRs that fixed this.

**Comment by bowen-xiao96** [comment]
@soumith Thank you very much.

**Comment by rtarquini** [comment]
I'm seeing this issue on the Nvidia Xavier with version 1.1.   [CPU mean is incorrect ]

>>> torch.__version__
'1.1.0a0+ceb9702'

I can write up a new bug if needed. 

-Rich
