### ISSUE TITLE
torch._inductor.fx_passes.split_cat: [WARNING] couldn't find split args

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#102416]
```
./benchmarks/dynamo/torchbench.py --backend=inductor --inference --performance --only detectron2_fasterrcnn_r_50_c4
```

Print out:
```
...
[2023-05-26 16:09:54,098] torch._inductor.fx_passes.split_cat: [WARNING] couldn't find split args
...
```

@devashishshankar what is the user expected to do when they see this warning?  Is this a bug?  Should we lower the severity?

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10

**Comment by devashishshankar** [comment]
Yeah, we could lower the severity. I suspect this could be happening because users have not passed the `dim` argument in split. So, another way could be to just default that to 0. I will raise a quick PR to fix this
