### ISSUE TITLE
AttributeError: 'torch._C.ScriptDict' object has no attribute 'save'

### ISSUE THREAD

**Issue by JxuHenry** [pytorch/pytorch#102514]
I want to convert the pytorch generated model to an Android usable model

import torch

model = torch.load("./model.pt")
traced_scripted_model = torch.jit.script(model)  
torch.jit.save(traced_scripted_model, "./model_mobile.pt")

but it got following error
File "/root/miniconda3/lib/python3.9/site-packages/torch/jit/_serialization.py", line 81, in save
    m.save(f, _extra_files=_extra_files)
AttributeError: 'torch._C.ScriptDict' object has no attribute 'save'

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by cxgincsu** [comment]
how do you solve this?

**Comment by ArpanGyawali** [comment]
@JxuHenry How was the issue solved?

**Comment by LovePelmeni** [comment]
did someone solve it? Stumbled into the same problem :/

**Comment by JxuHenry** [comment]
Please modify how your model is saved.

**Comment by LouisJULIEN** [comment]
I got the issue and the problem was that I wasn't loading the model properly. The problem wasn't in the saving part.

```python
neural_network_model =  torch.load("./model.pt") # no jit!!
checkpoint = torch.load(
    'path/to/my_checkpoint_.pt',
    map_location=torch.device('cpu'))
neural_network_model.load_state_dict(checkpoint)

model_scripted = torch.jit.script(neural_network_model)
model_scripted.save(f'/path/to/jit_saved_model.pt')
```
