### ISSUE TITLE
Replace deprecated set-output GitHub command with Environment Files

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#102550]
Currently our tests print this warning:

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

 `set-output` is used here:
 https://github.com/pytorch/pytorch/blob/e71ab214226af1f9dbded944e939c6447e0e8f09/.github/scripts/parse_ref.py#L12
 https://github.com/pytorch/pytorch/blob/e71ab214226af1f9dbded944e939c6447e0e8f09/.github/scripts/filter_test_configs.py#L340

cc @seemethere @malfet @pytorch/pytorch-dev-infra @mruberry

**Comment by malfet** [comment]
@kit1980 this is only called as a fallback, see:
https://github.com/pytorch/pytorch/blob/e71ab214226af1f9dbded944e939c6447e0e8f09/.github/scripts/parse_ref.py#L8-L12

But there are other issues like that in the workflows.

**Comment by malfet** [comment]
Fixed by updating `actions/core` to 1.10.0 in  https://github.com/seemethere/download-artifact-s3/pull/4
First pull.yml without any warnings in months:
https://github.com/pytorch/pytorch/actions/runs/5137112837
