### ISSUE TITLE
_nnz method silently overflows for large sparse compressed tensors

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#102520]
## Issue description

As in the title.

## Code example

```python
>>> import torch
>>> nnz = 2**31
>>> a = torch.sparse_csr_tensor(torch.arange(nnz + 1, dtype=torch.int64), torch.zeros(nnz, dtype=torch.int64), torch.ones(nnz), (nnz, 1))
>>> a._nnz()
-2147483648
```
The expected result is `2147483648`.

```python
>>> torch.sparse.check_sparse_tensor_invariants.enable()
>>> a = torch.sparse_csr_tensor(torch.arange(nnz + 1, dtype=torch.int64), torch.zeros(nnz, dtype=torch.int64), torch.ones(nnz), (nnz, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: crow_indices.shape[-1] must be equal to the number of rows + 1 (=-2147483647), but got 2147483649
```
The expected behavior is no exception or a correct exception message (clearly, `rows + 1` cannot be negative).

## System Info

- PyTorch version: main

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer

**Comment by nikitaved** [comment]
Oh, I guess all methods calling into MKL/cuSparse have this issue ... Regarding these, we could solve it by writing our own "partitioner" and an "output aggregator" to process in chucks of sizes no more than `int32`.

**Comment by pearu** [comment]
@nikitaved , yes, I agree about the existence of the systematic issue of indices conversions. The ultimate solution would be to support both 32 and 64-bit indices in MKL/cuSparse so that the indices conversions would not be required anymore. Locally, I can now build pytorch against MKL ILP64 (a PR is coming up), so that's a small step forward in this direction...

**Comment by nikitaved** [comment]
This is great! And cuSparse is just as flexible in that regard, right?

**Comment by pearu** [comment]
> This is great! And cuSparse is just as flexible in that regard, right?

Routines from cuSparse support both 32 and 64-bit indices but there is an exception:
https://docs.nvidia.com/cuda/cusparse/index.html#cusparsespgemm that currently supports only 32-bit indices.
