### ISSUE TITLE
[feature request] Support ATen:expand() operator for ONNX export

### ISSUE THREAD

**Issue by tensorbuffer** [pytorch/pytorch#10252]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
Exporting pytorch to onnx model that contains aten::expand() operator fails

Provide a short description.
Pls refer to below code example to repro the issue.
- With pytorch 0.4.0 (git checkout v0.4.0):
graph(%0 : Float(1, 128, 20, 30)) {
  %1 : Float(1, 1, 20, 30) = onnx::ReduceMean[axes=[1], keepdims=1](%0), scope: Model
  %2 : Float(1, 128, 1, 1) = onnx::AveragePool[kernel_shape=[20, 30], pads=[0, 0, 0, 0], strides=[20, 30]](%0), scope: Model
  %3 : Float(1!, 128!, 20, 30) = aten::expand[size=[1, 128, 20, 30]](%1), scope: Model
  %4 : Float(1, 128, 20, 30) = onnx::Mul[broadcast=1, axis=0](%3, %2), scope: Model
  return (%4);
}

Traceback (most recent call last):
  File "onnx_export_sample_model.py", line 24, in <module>
    torch.onnx.export(model, dummy_input, "sampe_model.onnx", verbose=True, export_params=True)
  File "/root/programs/pytorch/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/root/programs/pytorch/torch/onnx/utils.py", line 84, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names)
  File "/root/programs/pytorch/torch/onnx/utils.py", line 154, in _export
    _onnx_opset_version, defer_weight_export)
RuntimeError: ONNX export failed: Couldn't export operator aten::expand

- With top of tree pytorch (8/5/2018):
Traceback (most recent call last):
  File "onnx_export_sample_model.py", line 24, in <module>
    torch.onnx.export(model, dummy_input, "sampe_model.onnx", verbose=True, export_params=True)
  File "/root/programs/pytorch/torch/onnx/__init__.py", line 26, in export
    return utils.export(*args, **kwargs)
  File "/root/programs/pytorch/torch/onnx/utils.py", line 94, in export
    operator_export_type=operator_export_type)
  File "/root/programs/pytorch/torch/onnx/utils.py", line 247, in _export
    example_outputs, propagate)
  File "/root/programs/pytorch/torch/onnx/utils.py", line 201, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type)
  File "/root/programs/pytorch/torch/onnx/utils.py", line 129, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/root/programs/pytorch/torch/onnx/__init__.py", line 51, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/root/programs/pytorch/torch/onnx/utils.py", line 470, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/root/programs/pytorch/torch/onnx/symbolic.py", line 83, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/root/programs/pytorch/torch/onnx/symbolic.py", line 40, in _parse_arg
    raise RuntimeError("ONNX symbolic expected a constant value in the trace")
RuntimeError: ONNX symbolic expected a constant value in the trace

## Code example
import torch
import torch.onnx
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

    def forward(self, x):
        x_mean = x.mean(1, keepdim = True)
        x_pool = F.avg_pool2d(x, x.size()[2:])
        x = x_mean * x_pool
        return x

model = Model()
model.cpu()
model.train(False)

input_shape = (128, 20, 30)
dummy_input = Variable(torch.randn(1, *input_shape))
torch.onnx.export(model, dummy_input, "sampe_model.onnx", verbose=True, export_params=True)

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source):
docker file commands:
RUN cd /root/programs/pytorch; pip install -r "caffe2/requirements.txt"; \
    CMAKE_ARGS="-DCAFFE2_LINK_LOCAL_PROTOBUF=OFF -DBUILD_CUSTOM_PROTOBUF=OFF -DUSE_CUDA=OFF" python setup_caffe2.py develop
RUN cd /root/programs/pytorch; pip install -r "requirements.txt"; \
    NO_CUDA=1 python setup.py build develop

- OS: ubuntu16.04
- PyTorch version: tried both: '0.4.0a0+3749c58', '0.5.0a0+f57e4ce'
- Python version: 2.7
- CUDA/cuDNN version: NA
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
aten::expand is now supported for most of the use cases. Please upgrade PyTorch to the latest version to get the latest updates to ONNX export. Feel free to reopen this issue if you still see any issue in the latest version.
