### ISSUE TITLE
The im2col implementation request!

### ISSUE THREAD

**Issue by thisismohitgupta** [pytorch/pytorch#1025]
im2col implementation is really necessary for my project both forward and backward that can run on GPU and so far I am unable to make this function. Any help please ?

**Comment by ngimel** [comment]
im2col implementation is here 
https://github.com/pytorch/pytorch/blob/master/torch/lib/THCUNN/im2col.h
and it is used e.g. in Spatial Convolutions here
https://github.com/pytorch/pytorch/blob/master/torch/lib/THCUNN/generic/SpatialConvolutionMM.cu#L164-L169
What are you trying to do? Won't Convolution modules that are already present fit your needs?

**Comment by soumith** [comment]
im2col is being tracked here: https://github.com/pytorch/pytorch/issues/419
If you have an interest in implementing it, reply on that task, I will give you pointers.
