### ISSUE TITLE
Minor sphinx issue

### ISSUE THREAD

**Issue by themightyoarfish** [pytorch/pytorch#10258]
https://github.com/pytorch/pytorch/blob/7be071a829f5bbaa643ccacdd20b1508f78a2d78/torch/_torch_docs.py#L5893

For some reason, sphinx does not correctly render directives such as  
```
:math:`foo`<stuff>
```
where `<stuff>` is not preceded by a space. This causes the code to be rendered verbatim.

**Comment by vishwakftw** [comment]
@themightyoarfish Can you check now? It seems to have been resolved, possibly due to a Sphinx upgrade.

**Comment by vishwakftw** [comment]
@soumith This can be closed; the fix has landed in https://github.com/pytorch/pytorch/commit/492b7d410b03fef9b0438f64fb5d4383402b973e
