### ISSUE TITLE
import torch with alpine fails

### ISSUE THREAD

**Issue by agunapal** [pytorch/pytorch#102592]
### 🐛 Describe the bug

I am trying to run a docker container with PyTorch installed with alpine as base image.

Dockerfile is 

```
FROM python:3.9-alpine

RUN apk --update upgrade

RUN apk add --no-cache \
    curl \
    bash

RUN python -m pip install -U pip setuptools

RUN python -m pip install --no-cache-dir torch==2.0.0+cpu -f https://download.pytorch.org/whl/torch_stable.html;

ENTRYPOINT ["python", "-c", "import torch"]
```

Error 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/torch/__init__.py", line 228, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.9/site-packages/torch/__init__.py", line 187, in _load_global_deps
    raise err
  File "/usr/local/lib/python3.9/site-packages/torch/__init__.py", line 168, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: Error relocating /usr/local/lib/python3.9/site-packages/torch/lib/libgomp-a34b3233.so.1: pthread_attr_setaffinity_np: symbol not found
```

Based on some google search results, I installed GLIBC as follows. This is still not resolving the issue.

```
FROM python:3.9-alpine

RUN apk --update upgrade

RUN apk add --no-cache \
    curl \
    bash

ENV GLIBC_VERSION 2.35-r1

# Download and install glibc
RUN curl -Lo /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
  curl -Lo glibc.apk "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk" && \
  curl -Lo glibc-bin.apk "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk" && \
  apk add --force-overwrite glibc-bin.apk glibc.apk && \
  /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib && \
  echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
  rm -rf glibc.apk glibc-bin.apk /var/cache/apk/*

RUN python -m pip install -U pip setuptools

RUN python -m pip install --no-cache-dir torch==2.0.0+cpu -f https://download.pytorch.org/whl/torch_stable.html;

ENTRYPOINT ["python", "-c", "import torch"]
```

### Versions

N/A

cc @seemethere @malfet

**Comment by malfet** [comment]
Alpine is shipped with musl libc, while PyTorch is build/tested against glibc..

**Comment by malfet** [comment]
Alpine is shipped with musl libc, while PyTorch is build/tested against glibc..

**Comment by agunapal** [comment]
Closing this. Was able to use PyTorch with slim

**Comment by vedpathakpranit** [comment]
@agunapal you have mentioned, Was able to use PyTorch with slim, can you please share which image ??

**Comment by apexDev37** [comment]
I run Torch successfully with the base image: `slim-bullseye`🔥
The image has a smaller footprint and ships with the required libraries, including `glibc`.

```
python:3.12                                 381 MB
python:3.12-slim-bullseye                  46.8 MB    # This worked.
python:3.12.3-alpine3.19                   20.7 MB
```

More details in this [PR](https://github.com/martinoywa/sentiment-api/pull/1).

**Comment by vishwa3908** [comment]
OSError: Error relocating /usr/local/lib/python3.10/site-packages/torch/lib/libgomp-a34b3233.so.1: pthread_attr_setaffinity_np: symbol not found
getting this error when using torch with python 3.10 alpine image
ubuntu have far more vulnerability issues any workaround for alpine ?

**Comment by vishwa3908** [comment]
OSError: Error relocating /usr/local/lib/python3.10/site-packages/torch/lib/libgomp-a34b3233.so.1: pthread_attr_setaffinity_np: symbol not found
getting this error when using torch with python 3.10 alpine image
ubuntu have far more vulnerability issues any workaround for alpine ?

**Comment by hteeyeoh** [comment]
@vishwa3908 did you managed to resolve this issue on alpine? I'm facing the similar issue where I have tried to compile pytorch from src which it was not able to compile successfully
