### ISSUE TITLE
aten.mean errors out in inductor lowerings for 0d tensor

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#102546]
`mean` and possibly other reductions error out in lowerings when input is 0d and reduction dimension is specified. Eager allows specifying dimension of 0 or -1 for 0d tensor. 
Sidenote: I think this would have been caught if we started testing OpInfos with all samples
```
import torch

def fn(x):
    return x.mean(0)

x = torch.randn((), device="cuda")
print("eager ", fn(x))
opt = torch.compile(fn)
print("compiled ", opt(x))
```
Error:
```
  File "/scratch/ngimel/work/pytorch/torch/_inductor/lowering.py", line 3706, in <genexpr>
    denom = sympy_product(size[i] for i in axis)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: IndexError: list index out of range
  target: aten.mean.dim
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='arg0_1', layout=FixedLayout('cuda', torch.float32, size=[], stride=[]))
  ))
  args[1]: [0]
```  

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10

**Comment by jansel** [comment]
Should be fixed by https://github.com/pytorch/pytorch/issues/102546
