### ISSUE TITLE
Exporting the operator \'aten::fused_moving_avg_obs_fake_quant\' to ONNX opset version 13  is not supported

### ISSUE THREAD

**Issue by saeedadeeb103** [pytorch/pytorch#102694]
### 🚀 The feature, motivation and pitch

May i know if there is a way to fix this or when it will be added, im trying to export quantized model but it will always fail due to that ONNX opset V13 doesnt support fused_moving_avg_obs_fake_quant

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
