### ISSUE TITLE
[ONNX] Export Error for torch.full_like, torch.zeros_like torch.new_zeros when dtype Argument is None

### ISSUE THREAD

**Issue by iK1D** [pytorch/pytorch#102693]
### 🐛 Describe the bug

Exporter will use float32 as default dtype when exporting torch.full_like/torch.zeros_like/torch.new_zeros (or some other similar functions) when the dtype Argument is None, but the torch doc says if dtype Argument is None, the target dtype should be same as input tensor. This bug causes running failure for quite some Huggingface models that calling these torch functions on tensor of int64 dtype.

### Versions

All versions.

**Comment by BowenBao** [comment]
Thanks for reporting this. Do you have issues/links to the failing huggingface models?

**Comment by tungld** [comment]
Perhaps this merged PR #103048 can fix this.

**Comment by BowenBao** [comment]
Closing per fixed by https://github.com/pytorch/pytorch/pull/103048.
