### ISSUE TITLE
Incorrect type signature in nn.Module.register_full_backward_pre_hook documentation

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#102645]
### 📚 The doc issue

The documentation for `torch.nn.Module.register_full_backward_pre_hook` lists the expected return type of the the hook as `Tensor or None`, but it should be `tuple[Tensor] or None`.

https://pytorch.org/docs/main/generated/torch.nn.Module.html#torch.nn.Module.register_full_backward_pre_hook

cc @svekars @carljparker @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by jennychristopher** [comment]
I would like work on this issue
