### ISSUE TITLE
UNSTABLE periodic / linux-focal-rocm5.4.2-py3.8 / test

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#102789]
> For example, UNSTABLE pull / win-vs2019-cpu-py3 / test (default). Once
> created, the job will be disabled within 15 minutes. You can check the
> list of disabled jobs at https://ossci-metrics.s3.amazonaws.com/unstable-jobs.json

> If you need to get this out ASAP instead of waiting for 15 minutes,
> you can manually trigger the workflow at https://github.com/pytorch/test-infra/actions/workflows/update_disabled_tests.yml
> once the issue is created to update the above JSON list right away.

> Noted: you need to have write access to PyTorch repo to disable CI
> jobs. The issue will be rejected otherwise.

## Reason
The unstable periodic ROCm distributed job can now be moved from unstable periodic workflow into an issue

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by jithunnair-amd** [comment]
@huydnn This issue is out-of-date IIUC, since CI is now on ROCm5.5 and ROCm5.6? Can this be closed?

**Comment by huydhn** [comment]
Yeah, we should close this one as the job name has been updated

**Comment by jithunnair-amd** [comment]
Okay, as long as there's something that will keep the ROCm distributed CI job in unstable for now...
