### ISSUE TITLE
@pytorchbot -r squash

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#102749]
### 🚀 The feature, motivation and pitch

A workflow that might be unique to me is
1. Make some changes, write a new test, test passes locally
2. Push to CI, something breaks
3. Push a fix, something else breaks

And so my branch ends up looking like lots of small commits

Then there's some new big change I need to integrate so I try rebasing but `@pytorchbot rebase` tries to resolve conflicts per commit which I don't want to do since the small commits represent intermediate work and I get errors like this https://github.com/pytorch/pytorch/pull/102182#issuecomment-1572348557

Instead was hoping to have a mode that's closer to a squash workflow `@pytorchbot -r squash` or `@pytorchbot squash` that would squash all my commits into a single one and then rebase onto main. When my final state PR is merged it also gets squashed and merged

### Alternatives

A local workflow like
* `git rebase -i` 
* Squash everything
* Force push
* `@pytorchbot rebase`

cc @ZainRizvi @kit1980 @huydhn @clee2000

**Comment by ZainRizvi** [comment]
For the rebase, you can rebase locally as well in fast-forward mode with this command:
`git pull --rebase origin main`

That'll rebase your changes onto the latest main.

**Comment by malfet** [comment]
I think in case when rebase does not work cleanly, squash is not guaranteed to make things any better, so IMO it's not a priority for the team to add this functionality.

But if you have cycles to add this functionality and check that this would help, I'll be more than happy to review :)
(Though I'm not sure how to mark experimental features on the mergebot, as again, not sure if team has cycles to maintain it)

**Comment by msaroufim** [comment]
No worries I can always make the changes locally, this was more of a nice to have so gonna just close this
