### ISSUE TITLE
Torch.cudaa.device_count() shows only one gpu in MIG A100

### ISSUE THREAD

**Issue by chi2liu** [pytorch/pytorch#102715]
### 🐛 Describe the bug

Hi, I have an a100 machine and the configuration for MIG is following.

![image](https://github.com/pytorch/pytorch/assets/19861628/483281b9-6a00-4904-a29b-297afe358347)

![image](https://github.com/pytorch/pytorch/assets/19861628/ea71766b-71c3-4fdb-ae28-99ac9bf4ccf2)

and `torch.cuda.device_count()` shows only one gpu. How could I solve it?

torch is 1.13.1

### Versions

1.13.1

cc @ptrblck

**Comment by ptrblck** [comment]
This is expected as only a single MIG instance is visible in a process.

**Comment by ptrblck** [comment]
That's correct since a process can access only a single MIG instance.
This is a CUDA limitation and unrelated to PyTorch.
For more information, refer to the [MIG user guide](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/).

**Comment by edenbuaa** [comment]
@edenbuaa
