### ISSUE TITLE
Incomplete type annotations for `Callable`s in `nn.functional`

### ISSUE THREAD

**Issue by lkct** [pytorch/pytorch#102768]
### 🐛 Describe the bug

In `torch/nn/functional.pyi` (which is generated from `...pyi.in`), there's a list of annotations like
```python
max_pool1d: Callable
max_pool2d: Callable
max_pool3d: Callable
...
logsigmoid: Callable
softplus: Callable
softshrink: Callable
...
```
These are not quite useful as type hints, except for telling us they're callable objects (instead of tensors etc.).

It would be better to annotate them with the signature of each function.

### Versions

master

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by lkct** [comment]
Just took a look into it. I think I can work on a PR to fix.

But before that, could anyone please answer: should we prefer
```python
func: Callable[[Args], Return]
```
or
```python
def func(args: Args) -> Return: ...
```
(Any style guide?)

**Comment by ngimel** [comment]
Please send a PR, are there other examples for similar functions that you can follow? Otherwise, no particulat preference

**Comment by lkct** [comment]
> Please send a PR, are there other examples for similar functions that you can follow? Otherwise, no particulat preference

The annotations in question are originally `Callable` but I think the majority of similar functions in torch are annotated in `def` style. I'll find a solution to adopt `def`.
