### ISSUE TITLE
threshold(x, 0, 0) consistently faster than relu(x)

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#10276]
In `CUDA_LAUNCH_BLOCKING=1 ipython`,
```py
In [26]: x = torch.randn(200,300,400)

In [27]: %timeit -n 100 torch.nn.functional.threshold(x, 0, 0)
71.5 ms ± 308 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [28]: %timeit -n 100 torch.nn.functional.relu(x)
78.9 ms ± 269 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [29]: xc = x.cuda()

In [30]: %timeit -n 100 torch.nn.functional.threshold(xc, 0, 0)
883 µs ± 2.23 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [31]: %timeit -n 100 torch.nn.functional.relu(xc)
1.79 ms ± 2.78 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

```

**Comment by t-vi** [comment]
So the fundamental reason is that `clamp_out` is implemented using [`copy_` + `clamp_`](https://github.com/pytorch/pytorch/blob/0d03219a421310c2c8c0f287284e27e31ee74562/aten/src/ATen/native/cuda/CUDAUnaryOps.cpp#L17), when the [original THC clamp](https://github.com/pytorch/pytorch/blob/0d03219a421310c2c8c0f287284e27e31ee74562/aten/src/THC/generic/THCTensorMathPointwise.cu#L92) used to just copy while clamping.
I'd say the best way to fix this might be to move the clamp code and kernel to ATen proper and not punting it to TH/THC, but one could also replace `_th_clamp_` (and min max friends) with `_th_clamp_out` and call it with self, self when we want `_th_clamp_`.
