### ISSUE TITLE
CI bug, calculate-docker-image failed 

### ISSUE THREAD

**Issue by heidongxianhua** [pytorch/pytorch#102806]
### 🐛 Describe the bug

In my PR, many ci workflow failed because of  calculate-docker-image failed 
https://github.com/pytorch/pytorch/pull/102047

https://github.com/pytorch/pytorch/actions/runs/5150890768/jobs/9275686994?pr=102047

### Versions

None

cc @ZainRizvi @kit1980 @huydhn @clee2000

**Comment by msaroufim** [comment]
I had the same issue, you need to rebase to master and the error will go away

**Comment by huydhn** [comment]
Yes, a rebase is needed to get the newer version of that GitHub action.  I can see that you have done that https://github.com/pytorch/pytorch/pull/102047#issuecomment-1573038954 and the issue has been addressed.  Please feel free to re-open this issue if you encounter other issues with `calculate-docker-image`.  I apologize for the inconvenience.  One way to avoid this from happening again is to make this a generic action and move it out of PyTorch repo into https://github.com/pytorch/test-infra/tree/main/.github/actions
