### ISSUE TITLE
Error of producing csr sparse matrix by 'torch.sparse_csr_tensor'

### ISSUE THREAD

**Issue by TTyyds-art** [pytorch/pytorch#102808]
### 🐛 Describe the bug

I have used the following codes to produce a sparse matrix, but the output is wrong.
```
from torch import arange  
import torch   
lam = [1, 2, 3, 4, 5, 6]  
il = arange(len(lam))  
matrix= torch.sparse_csr_tensor(il, il, lam)  
print(matrix.to_dense()) 
```
Its output:
```
tensor([[1, 0, 0, 0, 0, 0],
        [0, 2, 0, 0, 0, 0],
        [0, 0, 3, 0, 0, 0],
        [0, 0, 0, 4, 0, 0],
        [0, 0, 0, 0, 5, 6]])
```
Normally, the output should be a diag matrix with a shape of (6, 6).  I use SciPy to produce the same matrix again:

```
from numpy import arange
from scipy.sparse import csr_matrix as sparse
lam = [1, 2, 3, 4, 5, 6]
il = arange(len(lam))
matrix = sparse((lam, (il, il)))
print(matrix.toarray())
```

The output:
```
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
```
**The comparison of two outputs from SciPy and PyTorch demonstrates there are bugs in 'torch.sparse_csr_tensor'.**

### Versions

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              72
On-line CPU(s) list: 0-71
Thread(s) per core:  2
Core(s) per socket:  18
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
Stepping:            4
CPU MHz:             1000.078
CPU max MHz:         3700.0000
CPU min MHz:         1000.0000
BogoMIPS:            4600.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            25344K
NUMA node0 CPU(s):   0-17,36-53
NUMA node1 CPU(s):   18-35,54-71
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.1
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.8.0              h37601d7_11    conda-forge
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.6            py39h417a72b_1  
[conda] mkl_random                1.2.2            py39h417a72b_1  
[conda] numpy                     1.23.5           py39hf6e8229_1  
[conda] numpy-base                1.23.5           py39h060ed82_1  
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by nikitaved** [comment]
It is not a bug, looks like in the scipy example the matrix is constructed from a COO representation. In PyTorch, a sparse compressed format is constructed from it's corresponding compressed representation, i.e. (indptr, indices). Once the very first argument to sparse car constructor is replaced with `arange(6 + 1)`, the so called indptr representation, the result is as expected.
Alternatively, one could do `torch.sparse_coo_tensor(il, il, ...).to_sparse(layout=torch.sparse_csr)`.

**Comment by TTyyds-art** [comment]
Sorry, may there is something wrong with the codes you provided?
```
from torch import arange  
import torch   
lam = [1, 2, 3, 4, 5, 6]  
il = arange(len(lam))  
matrix= torch.sparse_coo_tensor(il, il, lam).to_sparse(layout=torch.sparse_csr)  
print(matrix.to_dense()) 
```
One error occurs:
```
matrix= torch.sparse_coo_tensor(il, il, lam).to_sparse(layout=torch.sparse_csr)
RuntimeError: indices must be sparse_dim x nnz, but got: [6]
```

**Comment by TTyyds-art** [comment]
In the document of torch.sparse:

>The values of sparse dimensions in deduced `size` is computed from the size of  `crow_indices`  and the maximal index value in `col_indices`. If the number of columns needs to be larger than in the deduced `size` then the `size` argument must be specified explicitly.

It is different from the method in SciPy, I should re-understand this method of producing sparse matrices. I have been trying to replace the SciPy with Pytorch for days ago, and my idea about the production of sparse matrices is totally from SciPy. That is the reason I believed that a bug occurred.

**Comment by TTyyds-art** [comment]
> It is not a bug, looks like in the scipy example the matrix is constructed from a COO representation. In PyTorch, a sparse compressed format is constructed from it's corresponding compressed representation, i.e. with (indptr, indices). Once the very first argument to the sparse csr constructor is replaced with , the so called indptr argument, the result is as expected. With the given arguments in the repro the result is also as expected, since the first argument hints at a (6-1) x 6 matrix. Alternatively, one could do .`arange(6 + 1)``torch.sparse_coo_tensor(il, il, lam).to_sparse(layout=torch.sparse_csr)`

I agree.

**Comment by amjames** [comment]
@TTyyds-art
> > ... That is the reason I believed that a bug occurred.

> I agree 

Do you still believe a bug has occurred or are you satisfied by @nikitaved 's answer indicating why this is not a bug but rather a difference between our API and that of SciPy's?
