### ISSUE TITLE
Check Torch operator compatibility for ONNX

### ISSUE THREAD

**Issue by NatanBagrov** [pytorch/pytorch#102834]
### 🚀 The feature, motivation and pitch

Is there a way to check a support of an operator with ONNX, without trying to convert to model?

Example:
The [`torch.scatter_reduce(...)`](https://pytorch.org/docs/stable/generated/torch.scatter_reduce.html) function is not supported in ONNX at the moment.

I'm wondering is it possible to have something like `torch.onnx.is_supported(lambda: torch.scatter_reduce(a,b,c,d))`

### Alternatives

You can wrap the conversion with try-except but then you get an error that is in the "model"-level and not the block level.

### Additional context

Related to [this issue](https://github.com/onnx/onnx/issues/5273).

**Comment by BowenBao** [comment]
cc @justinchuby

**Comment by titaiwangms** [comment]
https://pytorch.org/docs/stable/onnx_supported_aten_ops.html

**Comment by NatanBagrov** [comment]
Thanks @titaiwangms , I'm familiar with the docs. These are, however, docs, and it is not future proof, because later (hopefully) more operators will be supported, and it is not trivial to go over the docs each version and modify their code accordingly.

**Comment by NatanBagrov** [comment]
> The docs are generated. So they will be up to date if that’s what your concern was.

Nope, that wasn't my concern.
Simply looking for a nicer API to check compatibility programmatically

**Comment by justinchuby** [comment]
There are usually transformations done to the model when we convert so whether a torch op is supported depends on how it is used. I will need to think more on how we can provide an api like this.

**Comment by justinchuby** [comment]
There is https://github.com/pytorch/pytorch/blob/7108c035bc0309f60fc86d32a42335b8808576f9/torch/onnx/utils.py#L1305 which gives you an approximate.

**Comment by justinchuby** [comment]
Should we expose the decomp table from onnx dynamo? @BowenBao
