### ISSUE TITLE
torch.cat doesn't support keyword arguments

### ISSUE THREAD

**Issue by DmitryUlyanov** [pytorch/pytorch#1028]
Hello, 

For now this example will throw a error
```python
a = torch.FloatTensor(4,5)
b = torch.FloatTensor(4,7)

torch.cat((a,b), dimension=1)
```
```
TypeError: cat() takes no keyword arguments
```

while docs say there is a named argument with default value. 

```python
a = torch.FloatTensor(4,5)
b = torch.FloatTensor(4,7)

a= torch.autograd.Variable(a)
b= torch.autograd.Variable(b)

torch.cat((a,b), dimension=1)
```
This also fails with the same error.

It would be also nice to change `dimension` to `dim` in future for coherence with other functions.

**Comment by episodeyang** [comment]
I second this! running into the same problem.

**Comment by jihunchoi** [comment]
I think addbmm and baddbmm should also be modified. (at least its docstring)
According to addbmm's docstring, it says
`addbmm(beta=1, mat, alpha=1, batch1, batch2, out=None) -> Tensor`,
however positional arguments after the keyword argument is not allowed in python.
As a big fan of using keyword arguments whenever possible, it would be great for me if I can use keyword arguments on every C binding.

**Comment by soumith** [comment]
fixed in master. will be in next release.
