### ISSUE TITLE
Error running cartpole using DQN

### ISSUE THREAD

**Issue by vrunm** [pytorch/pytorch#102994]
### 🐛 Describe the bug

I am trying to get a PyTorch implementation of DQN to run on CartPole-v1, however, it will not solve the problem and I cannot figure out what the bug could be.

The code runs, however, no learning/ improvement in episodic returns is observed.

I want to try and keep as much of this code intact as possible, and not completely rewrite it with another implementation.
```
import pickle
import tqdm
from torch.nn import MSELoss
import math
from collections import deque
import random
import gymnasium as gym
import torch
import torch.nn as nn
import torch.nn.functional as F




class neural_net(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1=nn.Linear(4,128)
        self.l2=nn.Linear(128,128)
        self.l3=nn.Linear(128,2)


    def forward(self,input):
        out=F.relu(self.l1(input))
        out=F.relu(self.l2(out))
        out=self.l3(out)
        return out

class ReplayBuffer():
    def __init__(self):
        self.max_len=10000
        self.capacity=0
        self.memory=deque([],maxlen=self.max_len)

    def push(self, transition):
        self.memory.append(transition)
        if self.capacity<self.max_len:
            self.capacity +=1


    def pull(self,batch_size):
        return random.sample(self.memory,batch_size)

    def __len__(self):
        return self.capacity



def update_target(net1,net2):
    net1.load_state_dict(net2.state_dict())

def soft_update(target, source, tau=0.005):
    for target_param, param in zip(target.parameters(), source.parameters()):
        target_param.data.copy_(target_param.data * (1.0 - tau) + param.data * tau)




def dqn(epsilon=0.9,alpha=1e-4,number_of_episodes=10000,gamma=0.99):
    env=gym.make("CartPole-v1")    # 4d states,   2 actions left right

    model=neural_net()
    target=neural_net()
    update_target(target,model)

    replay_buffer=ReplayBuffer()

    number_of_episodes_seen=0
    total_number_of_frames_seen=0

    criterion=MSELoss()
    optim=torch.optim.Adam(params=model.parameters(),lr=alpha)

    for i in tqdm.tqdm(range(number_of_episodes)):
        number_of_episodes_seen+=1
        state,_=env.reset()
        ep_done=False

        state = torch.tensor(state, dtype=torch.float32).unsqueeze(0)

        while not ep_done:
            action_values=model(state)

            r = random.random()
            if r>epsilon:
                action=torch.argmax(action_values).item()  #the greedy action
            else:
                action=random.choice([0,1])  #the epsilon greedy action

            next_state,reward,terminated,truncated,_=env.step(action)
            total_number_of_frames_seen+=1

            #update epsilon
            epsilon = 0.05 + (0.9 - 0.05) * math.exp(-1 * total_number_of_frames_seen / 1000)

            ep_done=terminated or truncated


            next_state=torch.tensor(next_state,dtype=torch.float32).unsqueeze(0)
            reward=torch.tensor([reward],dtype=torch.float32)
            done=torch.tensor([ep_done])
            action=torch.tensor([action])

            replay_buffer.push([state,action,reward,next_state,done])

            state=next_state


            if len(replay_buffer)>=128:
                batch=replay_buffer.pull(128)
                # this will look like [[s,a,r,s'],[s,a,r,s'],...]

                batch = list(zip(*batch))
                #converts it to [(s,s,s,,..),(a,a,a,,...),(r,r,r...),(s',s',s'...),(done,done,done...),(w,w,w,...)]

                state_batch=torch.concat(batch[0],dim=0)
                action_batch=torch.concat(batch[1],dim=0).type(torch.int64)
                scalar_reward_batch=torch.concat(batch[2],dim=0)
                next_state_batch=torch.concat(batch[3],dim=0)
                done_batch=torch.concat(batch[4],dim=0).type(torch.bool)

                action_values=model(state_batch)
                action_values=action_values.gather(1,action_batch.unsqueeze(1))
                # note: needed to unsqueeze because action_batch needs to have same shape as model outputs in gather



                next_state_action_values = target(next_state_batch)
                next_state_action_values = next_state_action_values.gather(1,next_state_action_values.argmax(dim=1).unsqueeze(1))


                y = scalar_reward_batch.unsqueeze(1) + ~done*gamma*next_state_action_values


                loss=criterion(action_values, y)
                optim.zero_grad()
                loss.backward()
                optim.step()
                soft_update(target, model)
                ## the model is now updated



        #episode has terminated



        if number_of_episodes_seen%50==0:
            #run an eval episode

            state,_= env.reset()
            ep_done=False
            total_return = 0.
            state = torch.tensor(state,dtype=torch.float32).unsqueeze(0)

            while not ep_done:
                action=model(state).argmax().item()
                next_state,reward,terminated,truncated,_=env.step(action)

                next_state = torch.tensor(next_state, dtype=torch.float32).unsqueeze(0)

                total_return+=reward

                state=next_state

                ep_done=terminated or truncated



            print("\n_______________________\n episode:",number_of_episodes_seen,"\nnumber of frames seen:",total_number_of_frames_seen,"\nscalarised reward: ",total_return,"\n_______________________")

    return model

model=dqn()

a=open("model","wb")
pickle.dump(model,a)
a.close()

```

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.109+-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 470.161.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.00GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        3
BogoMIPS:                        4000.32
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        1 MiB (1 instance)
L3 cache:                        38.5 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT Host state unknown

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] msgpack-numpy==0.4.8
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-ignite==0.4.12
[pip3] pytorch-lightning==2.0.2
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.0
[pip3] torchinfo==1.8.0
[pip3] torchmetrics==0.11.4
[pip3] torchtext==0.15.1
[pip3] torchvision==0.15.1
[conda] cudatoolkit               11.7.0              hd8887f6_10    nvidia
[conda] magma-cuda118             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] msgpack-numpy             0.4.8                    pypi_0    pypi
[conda] numpy                     1.23.5          py310h53a5b5f_0    conda-forge
[conda] pytorch-ignite            0.4.12                   pypi_0    pypi
[conda] pytorch-lightning         2.0.2                    pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchaudio                2.0.1                    pypi_0    pypi
[conda] torchdata                 0.6.0                    pypi_0    pypi
[conda] torchinfo                 1.8.0                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchtext                 0.15.1                   pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi

**Comment by jbschlosser** [comment]
Hey @vrunm, I suggest posting a question like this to the [PyTorch forums](https://discuss.pytorch.org/), as you're more likely to receive assistance there. Note that the issues here are reserved for problems within PyTorch itself. Closing for now but feel free to reopen if the discussion there leads to clear identification of a PyTorch bug.
