### ISSUE TITLE
Not sure what is wrong, 

### ISSUE THREAD

**Issue by NeVeREire** [pytorch/pytorch#102939]
### 🐛 Describe the bug

It was working the last time I ran it, I ran an update and now i'm getting this when trying to train a lora

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 4700
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 2350
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 2
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 2
  gradient ccumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 2350
steps:   0%|                                                                                  | 0/2350 [00:00<?, ?it/s]╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\train_db.py:477 in <module>                        │
│                                                                                                  │
│   474 │   args = parser.parse_args()                                                             │
│   475 │   args = train_util.read_config_from_file(args, parser)                                  │
│   476 │                                                                                          │
│ ❱ 477 │   train(args)                                                                            │
│   478                                                                                            │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\train_db.py:245 in train                           │
│                                                                                                  │
│   242 │   )                                                                                      │
│   243 │                                                                                          │
│   244 │   if accelerator.is_main_process:                                                        │
│ ❱ 245 │   │   accelerator.init_trackers("dreambooth" if args.log_tracker_name is None else arg   │
│   246 │                                                                                          │
│   247 │   loss_list = []                                                                         │
│   248 │   loss_total = 0.0                                                                       │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:5 │
│ 48 in _inner                                                                                     │
│                                                                                                  │
│    545 │   │   │   │   )                                                                         │
│    546 │   │                                                                                     │
│    547 │   │   def _inner(*args, **kwargs):                                                      │
│ ❱  548 │   │   │   return PartialState().on_main_process(function)(*args, **kwargs)              │
│    549 │   │                                                                                     │
│    550 │   │   return _inner                                                                     │
│    551                                                                                           │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:2 │
│ 031 in init_trackers                                                                             │
│                                                                                                  │
│   2028 │   │   │   │   if getattr(tracker_init, "requires_logging_directory"):                   │
│   2029 │   │   │   │   │   # We can skip this check since it was done in `__init__`              │
│   2030 │   │   │   │   │   self.trackers.append(                                                 │
│ ❱ 2031 │   │   │   │   │   │   tracker_init(project_name, self.logging_dir, **init_kwargs.get(s  │
│   2032 │   │   │   │   │   )                                                                     │
│   2033 │   │   │   │   else:                                                                     │
│   2034 │   │   │   │   │   self.trackers.append(tracker_init(project_name, **init_kwargs.get(st  │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\accelerate\tracking.py:83   │
│ in execute_on_main_process                                                                       │
│                                                                                                  │
│    80 │   @wraps(function)                                                                       │
│    81 │   def execute_on_main_process(self, *args, **kwargs):                                    │
│    82 │   │   if getattr(self, "main_process_only", False):                                      │
│ ❱  83 │   │   │   return PartialState().on_main_process(function)(self, *args, **kwargs)         │
│    84 │   │   else:                                                                              │
│    85 │   │   │   return function(self, *args, **kwargs)                                         │
│    86                                                                                            │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\accelerate\tracking.py:190  │
│ in __init__                                                                                      │
│                                                                                                  │
│   187 │   │   super().__init__()                                                                 │
│   188 │   │   self.run_name = run_name                                                           │
│   189 │   │   self.logging_dir = os.path.join(logging_dir, run_name)                             │
│ ❱ 190 │   │   self.writer = tensorboard.SummaryWriter(self.logging_dir, **kwargs)                │
│   191 │   │   logger.debug(f"Initialized TensorBoard project {self.run_name} logging to {self.   │
│   192 │   │   logger.debug(                                                                      │
│   193 │   │   │   "Make sure to log any initial configurations with `self.store_init_configura   │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\wri │
│ ter.py:246 in __init__                                                                           │
│                                                                                                  │
│    243 │   │   # Initialize the file writers, but they can be cleared out on close               │
│    244 │   │   # and recreated later as needed.                                                  │
│    245 │   │   self.file_writer = self.all_writers = None                                        │
│ ❱  246 │   │   self._get_file_writer()                                                           │
│    247 │   │                                                                                     │
│    248 │   │   # Create default bins for histograms, see generate_testdata.py in tensorflow/ten  │
│    249 │   │   v = 1e-12                                                                         │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\wri │
│ ter.py:276 in _get_file_writer                                                                   │
│                                                                                                  │
│    273 │   def _get_file_writer(self):                                                           │
│    274 │   │   """Returns the default FileWriter instance. Recreates it if closed."""            │
│    275 │   │   if self.all_writers is None or self.file_writer is None:                          │
│ ❱  276 │   │   │   self.file_writer = FileWriter(                                                │
│    277 │   │   │   │   self.log_dir, self.max_queue, self.flush_secs, self.filename_suffix       │
│    278 │   │   │   )                                                                             │
│    279 │   │   │   self.all_writers = {self.file_writer.get_logdir(): self.file_writer}          │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\wri │
│ ter.py:75 in __init__                                                                            │
│                                                                                                  │
│     72 │   │   # TODO: See if we can remove this in the future if we are                         │
│     73 │   │   # actually the ones passing in a PosixPath                                        │
│     74 │   │   log_dir = str(log_dir)                                                            │
│ ❱   75 │   │   self.event_writer = EventFileWriter(                                              │
│     76 │   │   │   log_dir, max_queue, flush_secs, filename_suffix                               │
│     77 │   │   )                                                                                 │
│     78                                                                                           │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\tensorboard\summary\writer\ │
│ event_file_writer.py:72 in __init__                                                              │
│                                                                                                  │
│    69 │   │   │   pending events and summaries to disk.                                          │
│    70 │   │   """                                                                                │
│    71 │   │   self._logdir = logdir                                                              │
│ ❱  72 │   │   tf.io.gfile.makedirs(logdir)                                                       │
│    73 │   │   self._file_name = (                                                                │
│    74 │   │   │   os.path.join(                                                                  │
│    75 │   │   │   │   logdir,                                                                    │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\tensorboard\lazy.py:65 in   │
│ __getattr__                                                                                      │
│                                                                                                  │
│    62 │   │   # over load_once() and avoid polluting the module's attrs with our own state.      │
│    63 │   │   class LazyModule(types.ModuleType):                                                │
│    64 │   │   │   def __getattr__(self, attr_name):                                              │
│ ❱  65 │   │   │   │   return getattr(load_once(self), attr_name)                                 │
│    66 │   │   │                                                                                  │
│    67 │   │   │   def __dir__(self):                                                             │
│    68 │   │   │   │   return dir(load_once(self))                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'tensorflow' has no attribute 'io'
steps:   0%|                                                                                  | 0/2350 [00:00<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\newpc_53bcer\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in                │
│ _run_module_as_main                                                                              │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\newpc_53bcer\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code       │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\accelerate\commands\acceler │
│ ate_cli.py:45 in main                                                                            │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\accelerate\commands\launch. │
│ py:923 in launch_command                                                                         │
│                                                                                                  │
│   920 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   921 │   │   sagemaker_launcher(defaults, args)                                                 │
│   922 │   else:                                                                                  │
│ ❱ 923 │   │   simple_launcher(args)                                                              │
│   924                                                                                            │
│   925                                                                                            │
│   926 def main():                                                                                │
│                                                                                                  │
│ C:\Users\newpc_53bcer\Documents\Lora\kohya_ss\venv\lib\site-packages\accelerate\commands\launch. │
│ py:579 in simple_launcher                                                                        │
│                                                                                                  │
│   576 │   process.wait()                                                                         │
│   577 │   if process.returncode != 0:                                                            │
│   578 │   │   if not args.quiet:                                                                 │
│ ❱ 579 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   580 │   │   else:                                                                              │
│   581 │   │   │   sys.exit(1)                                                                    │
│   582                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\newpc_53bcer\\Documents\\Lora\\kohya_ss\\venv\\Scripts\\python.exe',
'train_db.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5',
'--train_data_dir=C:/Users/newpc_53bcer/Documents/Models/EB/image', '--resolution=512,512',
'--output_dir=C:/Users/newpc_53bcer/Documents/Models/EB/model',
'--logging_dir=C:/Users/newpc_53bcer/Documents/Models/EB/log', '--save_model_as=safetensors', '--output_name=embst',
'--max_data_loader_n_workers=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2',
'--max_train_steps=2350', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234',
'--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1',
'--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

**Comment by janeyx99** [comment]
Hey! This bug report is not very legible and could use some clarification on what is going wrong. I am going to close for now for that reason, and also from looking at the logs, the issue seems to not be torch related but either tensorflow related or trainer related. If this is indeed a torch issue, please don't hesitate to reopen with the right details.
