### ISSUE TITLE
how to setting the protoc: tcpip and rdma

### ISSUE THREAD

**Issue by zsk423200** [pytorch/pytorch#10294]
when install from source, and set USE_GLOO_IBVERBS=1, it support ib and tcp when transportation, so how to choose one of them

**Comment by teng-li** [comment]
I will try to use IBVERB first, if fails, it will fall back to TCP.  So if USE_GLOO_IBVERBS is enabled, it should always use IBVERB and RDMA first.

Or you can use NCCL too and that will always try to use Infiniband.

**Comment by teng-li** [comment]
This is answered.
