### ISSUE TITLE
weight_norm cannot be deepcopy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#102981]
### 🐛 Describe the bug

```
import torch
import torch.nn as nn
from torch.nn.utils import weight_norm
import copy

m = weight_norm(nn.Linear(20, 40), name='weight')
m2 = copy.deepcopy(m)
```

fails with

```
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/w.py", line 7, in <module>
    m2 = copy.deepcopy(m)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/data/users/ezyang/b/pytorch/torch/_tensor.py", line 86, in __deepcopy__
    raise RuntimeError(
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

This prevents deepcopy from working on HF Wav2Vec2

### Versions

main

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by medmabcf** [comment]
Hi @ezyang 
I think the deepcopy function failed because it is not currently supported for Tensors that are not created explicitly by the use.
You can try using the clone method,
import torch.nn as nn
from torch.nn.utils import weight_norm

m = weight_norm(nn.Linear(20, 40), name='weight')
m2 = nn.Linear(20, 40)
m2.weight = nn.Parameter(m.weight.clone())

**Comment by ezyang** [comment]
New plan is https://github.com/pytorch/pytorch/pull/103001

**Comment by albanD** [comment]
We won't fix this as the weight_norm implementation in question is deprecated and the new version landed and can properly be deepcopied!

**Comment by HLBayes** [comment]
> We won't fix this as the weight_norm implementation in question is deprecated and the new version landed and can properly be deepcopied!

could you please tell us which Pytorch version has fixed this bug?

**Comment by jbschlosser** [comment]
@HLBayes check out the deepcopyable `torch.nn.utils.parametrizations.weight_norm` as an alternative to the old `torch.nn.utils.weight_norm`.

**Comment by HLBayes** [comment]
> @HLBayes check out the deepcopyable `torch.nn.utils.parametrizations.weight_norm` as an alternative to the old `torch.nn.utils.weight_norm`.

Thanks for your reminder.

I find version 2.1.0 or later (may be only available in `pytorch-nightly` currently) could work well both for `torch.nn.utils.parametrizations.weight_norm` code and `deepcopy` a weight_normed net.

Thanks for your help.
