### ISSUE TITLE
 Inductor FX passes split_cat fusion bug due to unnormalized torch.cat call

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#102950]
### 🐛 Describe the bug

Repo:
```
import torch

def fn(x):
    return torch.cat(torch.split(x, 1), dim=-1)


x = torch.rand(2, 3).to("cuda")
print(fn(x))
opt_fn = torch.compile(fn)
print(opt_fn(x))
```

Error:
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: flatten() has invalid args: start_dim cannot come after end_dim

While executing %flatten : [#users=1] = call_function[target=torch.flatten](args = (%movedim, -1, 0), kwargs = {})
```

### Versions

N/A

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @bertmaher

**Comment by jansel** [comment]
cc @devashishshankar

**Comment by bertmaher** [comment]
I messed this up a bunch when implementing cat/pointwise sinking.  If it helps, here's how we ended up normalizing cat args: https://github.com/pytorch/pytorch/blob/4bb2b65ea4912ec32d4106c122385aaad682b83e/torch/_inductor/fx_passes/pre_grad.py#L289-L299
