### ISSUE TITLE
Bug: test_cuda.py running error!

### ISSUE THREAD

**Issue by lk1983823** [pytorch/pytorch#102942]
## Issue description

I have run the test_cuda.py in pytorch/test/ file , but find an error.

```
Traceback (most recent call last):
  File "/media/lk2/sgccai/15_DLAcceleration/pytorch-main/test/test_cuda.py", line 28, in <module>
    from torch.cuda._memory_viz import segment_plot
ImportError: cannot import name 'segment_plot' from 'torch.cuda._memory_viz' (/home/lk2/anaconda3/envs/ai/lib/python3.10/site-packages/torch/cuda/_memory_viz.py)
```
In addtion, when run a certain clip of the code to test profile_plot, it shows another error.
My code is:
```
with torch.profiler.profile(
            with_stack=True,
            profile_memory=True,
            record_shapes=True
        ) as prof:
    x = torch.rand(128, 128, device='cuda')
    x * x + x * x
    plot = profile_plot(prof)
```
The error is:
```
STAGE:2023-06-05 09:58:25 13664:13664 ActivityProfilerController.cpp:311] Completed Stage: Warm Up
STAGE:2023-06-05 09:58:27 13664:13664 ActivityProfilerController.cpp:317] Completed Stage: Collection
STAGE:2023-06-05 09:58:27 13664:13664 ActivityProfilerController.cpp:321] Completed Stage: Post Processing
Traceback (most recent call last):
  File "/media/lk2/sgccai/15_DLAcceleration/lukuan_lightning_test/torch_viz.py", line 69, in <module>
    plot = profile_plot(prof)
  File "/home/lk2/anaconda3/envs/ai/lib/python3.10/site-packages/torch/cuda/_memory_viz.py", line 415, in profile_plot
    for event in memory_profile._op_tree.sorted_nodes:
AttributeError: 'profile' object has no attribute '_op_tree'
```
Thank you !

- PyTorch :
- How you installed PyTorch (pip):
- OS: Ubuntu 18.04
- PyTorch version: 2.0.1+cu117
- Python version: 3.10
- CUDA/cuDNN version: 8.5
- GPU models and configuration: 2*RTX2080Ti
- GCC version (if compiling from source): 7.5.0
- CMake version:
- Versions of any other relevant libraries:

**Comment by janeyx99** [comment]
Hi! This is likely an error with the dependencies of your local build system. Could you follow the directions at https://pytorch.org/get-started/locally/ and ensure there's only one torch installed?

**Comment by lk1983823** [comment]
> Hi! This is likely an error with the dependencies of your local build system. Could you follow the directions at https://pytorch.org/get-started/locally/ and ensure there's only one torch installed?

@janeyx99 I removed the old torch and followed the locally install instruction and installed pytorch 2.0.1. However, it still shows error. Should I git clone the main thread and build it from source ?

**Comment by janeyx99** [comment]
Ah, segment_plot looks to be recently added in  https://github.com/pytorch/pytorch/commit/d6d8d3484e971c3575bae11d87cb132947e21e21. It should be available in our nightlies (installable with pip) or from source.

**Comment by sasikumari2i** [comment]
Hi,
  I am facing the same error still, tried installing pytorch from source but not solved. Is there any update on this ?
