### ISSUE TITLE
Extend RegisterDispatchKey for custom code.

### ISSUE THREAD

**Issue by huihoaan** [pytorch/pytorch#102967]
### 🚀 The feature, motivation and pitch

In current code, when we used class `RegisterDispatchKey` to generate code, the following template is fixed and cannot add additional logic to the code.
https://github.com/pytorch/pytorch/blob/f79d2b45fbb2bb47df206e770a525ee420194738/torchgen/dest/register_dispatch_key.py#L537-L549

The reason we want to add custom code is because we have some of our own tools, like precision comparison tools. Before each operator is called, our tools's API needs to be called. And if this part of the code is added in each operator implementation, the code is too redundant and easy to forget . So we want `RegisterDispatchKey` to be extended for custom code like https://github.com/pytorch/pytorch/pull/101333

### Alternatives

I think by passing in a custom template or a `{custom code}` reserving placeholders +callback functions.
If there is a better way to implement it, please tell me what I should do.

cc @ezyang @bhosmer @bdhirsh

**Comment by bdhirsh** [comment]
hmm we could figure out how to thread more custom code into these templates, but it's pretty hairy: you need a way to tell the codegen what custom logic should be inserted. The main way to do this today is by adding more metadata into a yaml file (the codegen input - XLA example [here](https://github.com/pytorch/xla/blob/master/codegen/xla_native_functions.yaml)). It's also not totally clear what you would put in the yaml file, to tell the codegen what to do:

(1) Do we put raw C++ code in the yaml file that the codegen stamps into the template? Or something else. Every op has a unique schema, so you'd need the hooks that you use to work for all operators (if your hooks only need the operator name this isn't a problem, but if they need the actual arguments and/or output then now you have a variable number of arguments/types).

(2) We'd (ideally) want any extra information that we stuff into the yaml to be backend-agnostic, and useful to other backends using the codegen pipeline.

My take is that I would probably lean away from adding more hooks into this template code, unless we can do it in a relatively backend-agnostic way that provides value to other backends (cc @ezyang if you have any opinions).

For what it's worth: in eager mode, you can actually use `TorchDispatch` modes to easily compare numerical results op-by-op across different devices- example here: https://github.com/albanD/subclass_zoo/blob/main/numerical_consistency_mode.py (thanks to @albanD for writing it up!).

> Does this look relevant for dispatch keys or is this more one of our offered extension points?

I'd put this more under "existing extension points for external backends" (this issue more about custom codegen in particular).

**Comment by ezyang** [comment]
torchgen doesn't change too much. Start by patching up the code as you need, and then once you have a reasonably complete set of use cases you can come back and propose a more generic API.
