### ISSUE TITLE
[feature request] Matrix rank

### ISSUE THREAD

**Issue by JiangWenPL** [pytorch/pytorch#10292]
## Issue description

I want to have function looks like `torch.matrix_rank()` that is similar to `np.linalg.matrix_rank()`

**Comment by vishwakftw** [comment]
@SsnL Is this worth adding to ATen ?

**Comment by vishwakftw** [comment]
I had an implementation ready before I asked you this, so just wanted to confirm if I could send it in.

**Comment by vishwakftw** [comment]
This can be closed now.
