### ISSUE TITLE
Add register_full_backward_pre_hook in pytorch version 1.x

### ISSUE THREAD

**Issue by sdc17** [pytorch/pytorch#102997]
### 🚀 The feature, motivation and pitch

Currently only the versions >= 2.0 implements [register_full_backward_pre_hook](https://pytorch.org/docs/stable/generated/torch.jit.ScriptModule.html?highlight=hook#torch.jit.ScriptModule.register_full_backward_pre_hook) and would it possible to add the corresponding implementation in version 1.x? For example, it is weird that pytorch 1.13 supports [register_forward_hook](https://pytorch.org/docs/1.13/generated/torch.nn.Module.html?highlight=hook#torch.nn.Module.register_forward_hook), [register_forward_pre_hook](https://pytorch.org/docs/1.13/generated/torch.nn.Module.html?highlight=hook#torch.nn.Module.register_forward_pre_hook), [register_full_backward_hook](https://pytorch.org/docs/1.13/generated/torch.nn.Module.html?highlight=hook#torch.nn.Module.register_full_backward_hook) , but not [register_full_backward_pre_hook](https://pytorch.org/docs/stable/generated/torch.jit.ScriptModule.html?highlight=hook#torch.jit.ScriptModule.register_full_backward_pre_hook). My dilemma is that I can't upgrade to pytorch 2.0 for compatibility reasons, however I need to use the [register_full_backward_pre_hook](https://pytorch.org/docs/stable/generated/torch.jit.ScriptModule.html?highlight=hook#torch.jit.ScriptModule.register_full_backward_pre_hook) to turn on a specific flag before each backward.  Thx for your reading.

**Comment by solomonkaura** [comment]
Am having a similar issue, is there a way out to achieve a similar result as register_full_backward_pre_hook in 1.X. thank you

**Comment by sdc17** [comment]
Hi, I have had to upgrade to version 2.0, and haven't found a solution for 1.x versions yet.

**Comment by solomonkaura** [comment]
I was able to use 1.X
what I did was use the grad_input of the layer after the current layer to represent the grad_output of the current layer. I assumed that, since the output of the current layer is the input to the next layer, the grad_output of the current layer should be the same as the grad_input of the next layer
it seems to work but, I am not sure if that's right.
