### ISSUE TITLE
Libtorch C++ torch::nn::functional::conv2d exception

### ISSUE THREAD

**Issue by JMLiu-SEU** [pytorch/pytorch#102962]
### 🐛 Describe the bug

I  have a libtorch tensor and a filter kernel both moved to gpu and a conv options. The conv operation gives me the correct result but when the programme ends there throws an exception. 
![image](https://github.com/pytorch/pytorch/assets/59131320/2c5d39bc-c011-4017-8843-080461c01bb8)

**Code:**
```C++
//filter function
torch::Tensor conv_filter(int projWidth) {
    torch::Tensor filter = torch::ones({ 1, 1, 1, projWidth });
    int mid = std::floor(projWidth / 2);

    for (int i = 0; i < projWidth; ++i) {
        if ((i - mid) % 2 == 0) {
            filter[0][0][0][i] = 0;
        }
        else {
            filter[0][0][0][i] = -0.5 / (M_PI * M_PI * (i - mid) * (i - mid));
        }
        if (i == mid) {
            filter[0][0][0][i] = 1.0 / 8.0;
        }
    }
    filter = filter;
    return filter;
}
```
```C++
//main 
const int AngleNum = 32;
int projWidth = 1629; 
int projHeight = 1629;
torch::Tensor ramp = conv_filter(projWidth).to(torch::kCUDA, device);
torch::nn::functional::Conv2dFuncOptions conv_options;
conv_options.stride({ 1, 1 }).padding({ 0, static_cast<int>(projWidth / 2) });
residual = residual.view({ 1, 1, AngleNum * projHeight, projWidth });
residual = torch::nn::functional::conv2d((residual), ramp, conv_options);  
residual = residual.view({ 1, 1, AngleNum, projHeight, projWidth });
```

### Versions

win10
cuda11.6
libtorch 2.0.0+cu117

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @jbschlosser

**Comment by JMLiu-SEU** [comment]
> Needs repro--am curious to see if this problem is isolated to Windows.

hi, is there any progress? thankyou

**Comment by Alectros** [comment]
@JMLiu-SEU, did you find a solution to this issue? I got exactly the same problem. 
My versions is:
win10
cuda 11.7
LibTorch 2.0.0 + cu117 (i tried also LibTorch 2.0.1 and got the same behaviour)

**Comment by JMLiu-SEU** [comment]
> @JMLiu-SEU, did you find a solution to this issue? I got exactly the same problem. My versions is: win10 cuda 11.7 LibTorch 2.0.0 + cu117 (i tried also LibTorch 2.0.1 and got the same behaviour)

sure，you can replace the dlls in libtorch w.r.t cudnn_* with those in nvidia cudnn package, then bug fixed
