### ISSUE TITLE
Error:Read timeout when start pytorch 

### ISSUE THREAD

**Issue by zsk423200** [pytorch/pytorch#10295]
i change my presentation:

install from source:
`python setup.py install`
and use gloo, get the error:
`[/home/zhoushengkai/code/pytorch_v0.4.1/third_party/gloo/gloo/transport/ibverbs/buffer.cc:108] Read timeout LID: 5 QPN: 27156 PSN: 14966066`

but install from binaries, and also use gloo, is ok.
i print info, and show it has block at broadcast (waitRecv)when start pytorch

today, i reinstall with the command:
`USE_GLOO_IBVERBS=0 python setup.py build develop`
is ok, and i know this way is only support tcp  rather than IB 

what's more, i run on a server which has only one IB card and phys_port_cnt is 1, and i test in single mechine, use 
![image](https://user-images.githubusercontent.com/18025765/44246710-33fb0500-a212-11e8-9c86-7666a4acbc58.png)
Data does not pass through the NIC, and form a loop in protocol layer. in two-mechine test, data go through the NIC

so why get error when i use IB mode

**Comment by ailzhang** [comment]
@zsk423200  Do you have IB setup correctly in your environment(like a list of ib devices)? `LID: 5 QPN: 27156 PSN: 14966066` is specific to IB communication.

**Comment by zsk423200** [comment]
@ailzhang I checked it out a few times and found nothing wrong, ib test in is ok.
i find the issue: https://github.com/pytorch/pytorch/pull/2903  the problem has been discussed there, the difference is that it get error in the first epoch. In addition, when I set the data loader to 0, it works fine.

**Comment by zsk423200** [comment]
Hi, @teng-li @KaiyuYue 
i find you have discussed this question there: https://github.com/pytorch/pytorch/issues/6267, and i met the same problem. pytorch version is 0.4.1, python  3.6, i set data loader to 0, it works fine, otherwise get error(Read Timeoyt), and the master gpu hang. so do you have any solution

**Comment by zsk423200** [comment]
@apaszke do you have any idea about this issue, it bother me too much

**Comment by zsk423200** [comment]
@KaiyuYue I eventually will train in multi-machine, so must solve this problem. DP mode can not be used in Multi-machine distributed training.

**Comment by zsk423200** [comment]
The problem has been solved， by use spawn mode:
`multiprocessing.set_start_method('spawn',force=True)`

**Comment by JianboDong** [comment]
@zsk423200 I met the same problem, except that I'm using Python2.7, and single thread on each node. Do you have any suggestion on solving my problem? Thanks
