### ISSUE TITLE
`F.group_norm` throwing dtype error if `input` and `weight` differ in dtype

### ISSUE THREAD

**Issue by jamesbraza** [pytorch/pytorch#102922]
### 🐛 Describe the bug

Please see the below code snippet from `torch==2.0.1`:

```python
import torch
import torch.nn.functional as F

N = 10
F.group_norm(
    input=torch.randn(1, N, 1, dtype=torch.float64),
    num_groups=1,
    weight=torch.ones(N, dtype=torch.float32),
)
```

When run, it leads to:

```python
/path/to/venv/bin/python /path/to/a.py 
Traceback (most recent call last):
  File "/path/to/a.py ", line 5, in <module>
    F.group_norm(
  File "/path/to/venv/lib/python3.11/site-packages/torch/nn/functional.py", line 2530, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mixed dtype (CPU): expect input to have scalar type of BFloat16
```

This one took me some time to root cause in practice.  The issue is `input` has dtype `float64`, and `weight` has dtype `float32` (different).  This leads to this exception about `BFloat16`.

I think there are a few possible resolutions:
- Catching and re-throwing with a better `Exception` message: `TypeError("Please make sure all inputs to group_norm share the same dtype.") from RuntimeError("...")`
- `torch` automatically casts to the type of `input` or `weight`/`bias` (unsure which is better)

Aside: how `BFloat16` relates to `float32` and `float64` isn't clear to me, and perhaps a `TypeError` (and not `RuntimeError`) is the correct exception type for this `BFloat16` error.

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.11.3 (main, May 12 2023, 17:57:28) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-12.6-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] mypy==1.3.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch3dunet==1.5.1
[pip3] torch==2.0.1

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by albanD** [comment]
Hey!
Mixed dtype is indeed not supported in general and only bf16 sometimes does.
I do agree that we should fix the error message to indeed say that the inputs are not the right dtype and don't mention bf16 here.

**Comment by poorneshwar9441** [comment]
@albanD Basically we have to throw an error if input.dtype != weights.dtype , Instead of Runtime error this should be Type error right?? any one assigned??
