### ISSUE TITLE
Conv2d returns drastically different results on ROCm (MI250X) vs CPU

### ISSUE THREAD

**Issue by v-iashin** [pytorch/pytorch#102968]
### 🐛 Describe the bug

Here is the snippet showing the drastic difference in an environment with ROCm:

```python
import torch
torch.__version__
# '2.0.1+rocm5.4.2'
layer = torch.nn.Conv2d(1, 768, kernel_size=16, stride=10)
x = torch.rand(10, 1, 128, 66)
layer.to('cuda:0')(x.to('cuda:0')).sum()
# tensor(10433.3145, device='cuda:0', grad_fn=<SumBackward0>)
layer.to('cpu')(x.to('cpu')).sum()
# tensor(1619.2983, grad_fn=<SumBackward0>)
```

Locally, I have an NVidia GPU and here is the snippet with the results with CUDA:

```python
import torch
torch.__version__
'2.0.0'
layer = torch.nn.Conv2d(1, 768, kernel_size=16, stride=10)
x = torch.rand(10, 1, 128, 66)
layer.to('cuda:0')(x.to('cuda:0')).sum()
# tensor(244.4510, device='cuda:0', grad_fn=<SumBackward0>)
layer.to('cpu')(x.to('cpu')).sum()
# tensor(244.4510, grad_fn=<SumBackward0>)
# `torch.allclose` returns True
```

* Interestingly, `nn.Linear` does not exhibit this behaviour, ie the numbers match.
* I also tried to copy the inputs, weight, and biases of the `layer` to the NVidia machine and it was giving the same results on `cpu` and `cuda`.

### Versions

Collecting environment information...
PyTorch version: 2.0.1+rocm5.4.2
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.4.22803-474e8620

OS: SUSE Linux Enterprise Server 15 SP4 (x86_64)
GCC version: (SUSE Linux) 7.5.0
Clang version: 15.0.0  (324a8e7de6a18594c06a0ee5d8c0eda2109c6ac6)
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.14.21-150400.24.11_12.0.57-cray_shasta_c-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI250X
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.4.22803
MIOpen runtime version: 2.19.0
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7A53 64-Core Processor
CPU family:                      25
Model:                           48
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       1
Stepping:                        1
Frequency boost:                 enabled
CPU max MHz:                     3541.0149
CPU min MHz:                     1500.0000
BogoMIPS:                        3992.29
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       2 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        32 MiB (64 instances)
L3 cache:                        256 MiB (8 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-15,64-79
NUMA node1 CPU(s):               16-31,80-95
NUMA node2 CPU(s):               32-47,96-111
NUMA node3 CPU(s):               48-63,112-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] numpy==1.24.1
[pip3] pytorch-triton-rocm==2.0.1
[pip3] torch==2.0.1+rocm5.4.2
[pip3] torchaudio==2.0.2+rocm5.4.2
[pip3] torchvision==0.15.2+rocm5.4.2
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton-rocm       2.0.1                    pypi_0    pypi
[conda] torch                     2.0.1+rocm5.4.2          pypi_0    pypi
[conda] torchaudio                2.0.2+rocm5.4.2          pypi_0    pypi
[conda] torchvision               0.15.2+rocm5.4.2          pypi_0    pypi

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo

**Comment by jeffdaily** [comment]
Thank you for pointing this out.  I was able to reproduce.  I have forwarded this on to our MIOpen team.  There seems to be a bug in the implicit gemm implementation.  Work around is to disable the igemm algorithm by setting MIOPEN_DEBUG_CONV_IMPLICIT_GEMM=0.

**Comment by v-iashin** [comment]
What's the scope of this? Does it affect all versions of PyTorch+rocm or specific MIOpen versions? 

Should I notify the cluster support team?

**Comment by jeffdaily** [comment]
@v-iashin this is fixed in latest nightly wheel.  We happen to build MIOpen from source for our wheels and were able to patch the MIOpen sources to provide this fix outside of the normal ROCm release cadence.  

Patches were applied on 6/18 to our MIOpen branch.  A new wheel builder image was prepared on 6/21.  Nightly wheels as of 6/22 should have the fix.  Thank you for your patience.
