### ISSUE TITLE
pytorch 2.0 compile

### ISSUE THREAD

**Issue by aiyb1314** [pytorch/pytorch#102964]
### 🐛 Describe the bug

torch.compile(model) 

### Error logs

RuntimeError: Triton Error [CUDA]: misaligned address

### Versions

[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-lightning         2.0.2                    pypi_0    pypi
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torchaudio                2.0.1+cu118              pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchvision               0.15.1+cu118             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by awgu** [comment]
You probably need to provide more info to get help.

**Comment by aiyb1314** [comment]
I ran some programs with cuda code and got errors using torch.compile
RuntimeError: Triton Error [CUDA]: misaligned address

**Comment by aiyb1314** [comment]
I'm sorry, I don't quite follow you.
