### ISSUE TITLE
Extend torch.min and torch.max to higher dimensions

### ISSUE THREAD

**Issue by kingwmk** [pytorch/pytorch#102927]
### 🚀 The feature, motivation and pitch

Extend torch.min and torch.max to higher dimensions, that is, change dim (int) – the dimension to reduce. to dim (list[int]) – the dimensions to reduce.
out (tuple, optional) – the tuple of two output tensors (min, min_indices).
take torch.nonzero as example.
Returns:
If as_tuple is False, the output tensor containing indices. If as_tuple is True, one 1-D tensor for each dimension, containing the indices of each nonzero element along that dimension.

**Comment by lezcano** [comment]
This is implemented in [`torch.amin`](https://pytorch.org/docs/stable/generated/torch.amin.html)
