### ISSUE TITLE
Errir building pytorch from source on Windows 10 Linking CXX shared library bin\torch_cuda.dll

### ISSUE THREAD

**Issue by lolo912** [pytorch/pytorch#102929]
### 🐛 Describe the bug

I tried to build pytorch from source on Windows 10 for my old GPU (Nvidia geforce 730) with CUDA 11.7, with cmake and Ninja.
The build goes to step 4121/4623 and fails when reaching this command : 
Linking CXX shared library bin\torch_cuda.dll

### Error logs

[4121/4623] Linking CXX shared library bin\torch_cuda.dll
FAILED: bin/torch_cuda.dll lib/torch_cuda.lib
cmd.exe /C "cd . && D:\condaEnv\Library\bin\cmake.exe -E vs_link_dll --intdir=caffe2\CMakeFiles\torch_cuda.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_cuda.rsp  /out:bin\torch_cuda.dll /implib:lib\torch_cuda.lib /pdb:bin\torch_cuda.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO  && cd ."
LINK: command "C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_cuda.rsp /out:bin\torch_cuda.dll /implib:lib\torch_cuda.lib /pdb:bin\torch_cuda.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\torch_cuda.dll.manifest" failed (exit code 1120) with the following output:
   Création de la bibliothèque lib\torch_cuda.lib et de l'objet lib\torch_cuda.exp
LINK : warning LNK4098: conflit entre la bibliothèque par défaut 'LIBCMT' et les autres bibliothèques ; utilisez /NODEFAULTLIB:library
magma.lib(dgeqrf_mgpu.cpp.obj) : error LNK2019: symbole externe non résolu dgeqrf_ référencé dans la fonction magma_dgeqrf2_mgpu
magma.lib(dgeqrf2_gpu.cpp.obj) : error LNK2001: symbole externe non résolu dgeqrf_
magma.lib(dgeqrf_gpu.cpp.obj) : error LNK2001: symbole externe non résolu dgeqrf_
magma.lib(dgeqrf.cpp.obj) : error LNK2001: symbole externe non résolu dgeqrf_
magma.lib(dgeqrf_m.cpp.obj) : error LNK2001: symbole externe non résolu dgeqrf_

### Minified repro

...

### Versions

....

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by lolo912** [comment]
Solved after adding lapack to my conda env with : conda install -c conda-forge lapack
But now i have other symbols not found :
magma.lib(zgeev.cpp.obj) : error LNK2019: symbole externe non résolu zscal_ référencé dans la fonction magma_zgeev
magma.lib(zlabrd_gpu.cpp.obj) : error LNK2001: symbole externe non résolu zscal_
magma.lib(zgetf2_nopiv.cpp.obj) : error LNK2001: symbole externe non résolu zscal_
magma.lib(zlatrd2.cpp.obj) : error LNK2001: symbole externe non résolu zscal_
magma.lib(zgeev.cpp.obj) : error LNK2019: symbole externe non résolu zdscal_ référencé dans la fonction magma_zgeev
magma.lib(ztrevc3_mt.cpp.obj) : error LNK2001: symbole externe non résolu zdscal_
magma.lib(zlatrsd.cpp.obj) : error LNK2001: symbole externe non résolu zdscal_
magma.lib(zgeev.cpp.obj) : error LNK2019: symbole externe non résolu idamax_ référencé dans la fonction magma_zgeev
magma.lib(dgeev.cpp.obj) : error LNK2001: symbole externe non résolu idamax_
magma.lib(dtrevc3_mt.cpp.obj) : error LNK2001: symbole externe non résolu idamax_
magma.lib(zlatrsd.cpp.obj) : error LNK2001: symbole externe non résolu idamax_
magma.lib(zgesdd.cpp.obj) : error LNK2019: symbole externe non résolu zgemm_ référencé dans la fonction magma_zgesdd
magma.lib(ztrevc3_mt.cpp.obj) : error LNK2001: symbole externe non résolu zgemm_
magma.lib(zgetrf_nopiv.cpp.obj) : error LNK2001: symbole externe non résolu zgemm_

**Comment by lolo912** [comment]
I solved my own problem,

Those magma errors was just a consequence of MKL library not found by my cmake (those symbols not found by magma are in the LAPACK and BLAS libraries, both included in MKL).

Adding those environment variables solved my problem on windows :

CMAKE_LIBRARY_PATH=D:\Pytorch requirements\mkl\lib
CMAKE_PREFIX_PATH=D:\Pytorch requirements\mkl\lib
MKLROOT=D:\Pytorch requirements\mkl
And to finish add to PATH variable : D:\Pytorch requirements\mkl\lib

Considering that D:\Pytorch requirements\mkl\ is the path where i installed my mkl library dowloaded as an archive here : https://s3.amazonaws.com/ossci-windows/mkl_2020.2.254.7z

I don't know which of those env variables resolved the problem, but now it works, cmake found the MKL library well !
Regards

**Comment by iremyux** [comment]
@lolo912 

It seems like you've solved your own problem :) Do you think this issue can be closed?

**Comment by iremyux** [comment]
I am closing this issue due to inactiveness. Please feel free to create a new issue if you think there is a problem or if you have a feature request.
