### ISSUE TITLE
Centos6.9+python3.7+pytorch1.12.1 build succeed,but import error

### ISSUE THREAD

**Issue by zhb0920** [pytorch/pytorch#103067]
### 🐛 Describe the bug

>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/meda_home/hongbin/miniconda3/lib/python3.7/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: /meda_home/hongbin/miniconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so: undefined symbol: aligned_alloc

### Versions

Centos6.9
python3.7
pytorch1.12.1

**Comment by jbschlosser** [comment]
Hey @zhb0920, it looks like there may be an issue in your environment. I suggest posting a question like this in the [PyTorch forums](https://discuss.pytorch.org/), as you're more likely to receive assistance there. Please feel free to reopen if discussion there identifies a likely bug within PyTorch.
