### ISSUE TITLE
DISABLED test_adamax (optim.test_optim.TestOptim)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#103006]
Platforms: dynamo

Technically a dup of https://github.com/pytorch/pytorch/issues/86474 

this test gets run twice, once in optim/test_optim, where its defined, and once in test_optim, where it gets imported.  The import causes them to have slightly different names.  Thanks @huydhn  for figuring this out

@janeyx99 

cc @vincentqb @jbschlosser @albanD @janeyx99 @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy

**Comment by janeyx99** [comment]
Closing this as https://github.com/pytorch/pytorch/issues/103322 should encompass this skip.
