### ISSUE TITLE
lit-llama lora fine tuning NetworkXUnbounded: Infinite capacity path, flow unbounded above

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#103055]
### 🐛 Describe the bug

lit-llama version 8aa65ba33e844c283c0a84b9758445fe0c6aab2d

Enable torch.compile with

```
diff --git a/finetune/lora.py b/finetune/lora.py
index 1873701..2d18ee8 100644
--- a/finetune/lora.py
+++ b/finetune/lora.py
@@ -73,6 +73,8 @@ def main(
     
     mark_only_lora_as_trainable(model)
 
+    model = torch.compile(model, dynamic=True)
+
     optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
     model, optimizer = fabric.setup(model, optimizer)
     train(fabric, model, optimizer, train_data, val_data, tokenizer_path, out_dir)
```

Work around unrelated bug with

```
diff --git a/lit_llama/lora.py b/lit_llama/lora.py
index 0f644e2..3f46d1a 100644
--- a/lit_llama/lora.py
+++ b/lit_llama/lora.py
@@ -320,7 +320,7 @@ class MergedLinear(nn.Linear, LoRALayer):
                     self.lora_B.unsqueeze(-1),  # (256, 2) -> (256, 2, 1)
                     groups=sum(self.enable_lora)
                 ).transpose(-2, -1)  # (64, 4, 64) @ (256, 2, 1) -> (64, 256, 64) -> (64, 64, 256)
-                result += self.zero_pad(after_B) * self.scaling  # (64, 64, 256) after zero_pad (64, 64, 384)
+                result = result + self.zero_pad(after_B) * self.scaling  # (64, 64, 256) after zero_pad (64, 64, 384)
             return result
```

Patch in Triton fix https://github.com/openai/triton/pull/1741

Use standard setup instructions, `python finetune/lora.py`

Fails with

```
NetworkXUnbounded: Infinite capacity path, flow unbounded above
```

The graph that was generated: https://gist.github.com/ezyang/71460c07dfc86d297090888e077bd88e

I think this is the corresponding joint graph https://gist.github.com/ezyang/65e55a66c9cee4120c1ba242bbaef358

This also affects finetune/adapter.py, so it's probably an issue in the llama model itself

cc @gchanan @zou3519 @msaroufim @wconstab @bdhirsh @anijain2305 @Chillee 

### Versions

main

**Comment by malfet** [comment]
Seems like a hi-pri to me, but defer it to @ezyang

**Comment by voznesenskym** [comment]
@ezyang to comment and close out

**Comment by ezyang** [comment]
@Chillee has a better llama implementation that will be open sourced soon and you should use instead of lit-llama, if you need this

**Comment by ezyang** [comment]
https://github.com/pytorch-labs/gpt-fast (private right now)

**Comment by mlazos** [comment]
Closing, since the gpt-fast repo is public now
