### ISSUE TITLE
Disabling MPI fails, unable to build on Centos7

### ISSUE THREAD

**Issue by prashantserai** [pytorch/pytorch#10300]
## Issue description
Hi! I'm building PyTorch from Source. I did a Git pull of the repo, and the CMake would complain about MPI not available (error message below).
I also tried to disable use of CAFFE2, MPI, and NUMA, but it still looks for MPI (and tries to build Caffe2..!!!)

##Code Example
cd ~/pytorch/centos7/;
make clean;
BUILD_CAFFE2=false;USE_MPI=false;USE_NUMA=false;
python setup.py install

##Error Message
CMake Error in /cbica/home/seraip/pytorch/centos7/torch/lib/build/THD/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

## System Info
- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): Source
- Build command you used (if compiling from source): python setup.py install
- OS: Centos7
- PyTorch version: 0.4
- Python version: 2.7
- CUDA/cuDNN version: 9.0/7.0
- GPU models and configuration: GeForce GTX 960
- GCC version (if compiling from source): 4.9.2
- CMake version: 3.11.2
- Versions of any other relevant libraries: LAPACK 3.2.1

**Comment by soumith** [comment]
USE_MPI is not well defined for `python setup.py install`.

Here's what you need:

`USE_DISTRIBUTED=0 python setup.py install`
