### ISSUE TITLE
PyTorch should not use `windows.8xlarge.nvidia.gpu` to test binary builds

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#103104]
### 🐛 Describe the bug

Because binary tests are tiny, so smallest machine we can get is better, and also `windows.8xlarge.nvidia.gpu` are often queued. From [hud/metircs](https://hud.pytorch.org/metrics):
<img width="668" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/27bc37f2-6e51-4a04-a084-b4ef76f16b96">

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
@malfet is this still a concern? I take it this will require some testing to find the smallest possible machine size that works.
