### ISSUE TITLE
breakpoint() in torch.compile region behaves oddly

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#103169]
### 🐛 Describe the bug

I expect breakpoint() to induce a graph break and let me inspect the frame

```
import torch

@torch.compile(backend="eager")
def f(x):
    breakpoint()
    return x + 1

f(torch.randn(1))
```

However, when I run this, I actually get dropped in some weird, synthetic catch_errors frame

```
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu019.ftw1 ~/local/a/pytorch (f15e82f7)]$ python z.py
--Call--
> /data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py(407)catch_errors()
-> @functools.wraps(callback)
(Pdb) bt
  /data/users/ezyang/a/pytorch/z.py(8)<module>()
-> f(torch.randn(1))
  /data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py(286)_fn()
-> return fn(*args, **kwargs)
  /data/users/ezyang/a/pytorch/z.py(5)f()
-> breakpoint()
> /data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py(407)catch_errors()
-> @functools.wraps(callback)
```

I can get to the frame I care about by typing `up`, but this threw me for a loop the first time it happened to me.

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @wconstab

**Comment by mitsu-h** [comment]
Hi, I'd like to try and improve it. Can you assign it to me?

**Comment by ezyang** [comment]
use comptime.breakpoint() instead
