### ISSUE TITLE
DISABLED test_roi_align_dynamic_shapes_cuda (__main__.DynamicShapesCudaTests)

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#103157]
Platforms: linux, rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/inductor%2Ftest_torchinductor_dynamic_shapes.py%3A%3ADynamicShapesCudaTests%3A%3Atest_roi_align_dynamic_shapes_cuda)).

Related to https://github.com/pytorch/pytorch/issues/103156

**Comment by malfet** [comment]
Should be fixed by https://github.com/pytorch/pytorch/commit/b8caa2b08f2b692ff11ea398a8356d0faaf2e68b
