### ISSUE TITLE
Refactor mm_plus_mm to check conditions upfront

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#103101]
### 🚀 The feature, motivation and pitch

We always lower `x @ y + a @ b` to [tuned_mm_plus_mm](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/fx_passes/post_grad.py#L138-L139) even though we only lower to the fused op in special conditions, see https://github.com/pytorch/pytorch/blob/08c4a442fd589f380ac0dd6f1126d6e144f449e5/torch/_inductor/kernel/mm_plus_mm.py#L154-L159. 

We could refactor this check to occur in the pattern matching pass so that these mms/adds aren't prevented from participating in other patterns or fusions.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225

**Comment by sidn77** [comment]
Hi, sorry for not discussing the change before posting a PR.
Below are the changes proposed in the PR

`def is_valid_mm_plus_mm(match: Match):
    mm_nodes = filter_nodes(match.nodes, aten.mm)
    # The dim of matrix multiplication should not match for passthrough
    return get_arg_value(mm_nodes, 2, "dim") != get_arg_value(mm_nodes, 1, "dim")

@register_lowering_pattern(
    CallFunction(
        aten.add,
        CallFunction(aten.mm, Arg(), Arg()),
        CallFunction(aten.mm, Arg(), Arg()),
    ),
    extra_check=is_valid_mm_plus_mm
)
def mm_plus_mm(match: Match, mat1, mat2, mat3, mat4):
    return inductor.kernel.mm_plus_mm.tuned_mm_plus_mm(mat1, mat2, mat3, mat4)`

This moves the check in pattern matching pass. But, I am not sure that if this will be able to handle both the aten.mm function calls...

Thanks,
Sid

**Comment by hgl71964** [comment]
Hi, I created another PR hopefully fix this problem
