### ISSUE TITLE
TORCH_LOGS=guards doesn't print tensor match guards

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#103248]
### 🐛 Describe the bug

This is confusing because the tensor match guards are a pretty important part of what guards we check, but they're completely omitted from the debug output

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @aakhundov

**Comment by mlazos** [comment]
I ran into this as well, it's [this code](https://github.com/pytorch/pytorch/blame/61cd6058135969c06df0164e17fbc962b03e7572/torch/_dynamo/convert_frame.py#LL492C13-L493C18) which filters out all of the guards. If I remove this though, it undoes the desired effect of your PR that added it. Should we just print the tensor guards + guards with code? wdyt

**Comment by ezyang** [comment]
I'd like it if we printed `__tensor_match(...)` instead of what the old code had.

**Comment by anijain2305** [comment]
Fixes https://github.com/pytorch/pytorch/issues/103248
