### ISSUE TITLE
Undeterministic behavior in testing in dynamo.

### ISSUE THREAD

**Issue by tugsbayasgalan** [pytorch/pytorch#103213]
### 🐛 Describe the bug

TorchDynamo uses object ID to figure out which functions/modules to be traced (https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/allowed_functions.py#L283). 
This is problematic when you are running unittests (python test/dynamo/test_misc.py) where one unittest uses allow_in_graph API which directly adds entry to this global allowed_functions tracker. (https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/__init__.py#L90). The reason is once the test that uses allow_in_graph finishes, we don't delete the object id from it directly. As a result, another test that uses different object with same object id will be assumed to be in this allowlist incorrectly. 

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @Xia-Weiwen @ipiszy

**Comment by yanboliang** [comment]
Good catch! I think we should reset them at ```torch._dynamo.reset()```, but firstly need to have a separate place to store the custom added allowed function ids. cc @anijain2305

**Comment by anijain2305** [comment]
Which test is this? We should just add a `disallow_in_graph` counterpart in the test for that.

**Comment by anijain2305** [comment]
Ideal way is to clean the udf allow list on torch._dynamo.reset.

**Comment by zou3519** [comment]
This is a silent correctness issue, right? Users could encounter this if they use the allow_in_graph API
