### ISSUE TITLE
Windows builds with CUDA 9.2

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#10326]
CC @yf225 @peterjc123 

We don't currently install CUDA 9.2 on our Windows AMIs, so that is the first thing that would need to be done.

**Comment by yf225** [comment]
There are some issues with the Jenkins client when we create a new AMI (it doesn't connect to Jenkins master). I will try to figure it out.

**Comment by yf225** [comment]
Update: CUDA 9.2 is added into our Windows AMI. We might want to consider adding a CUDA 9.2 Windows CI, or changing current CI to CUDA 9.2.

**Comment by ezyang** [comment]
This is fixed.
