### ISSUE TITLE
distributed.gather shape constraints

### ISSUE THREAD

**Issue by TiboDMZ** [pytorch/pytorch#103305]
### 📚 The doc issue

For distributed.gather(tensor, tensorlist, **kwargs) with backend NCCL
It is not documented what are the shape constraints for gather tensorlist.
I thought for the destination call, the tensors in tensor_list must simply be of the size of the tensor input of each corresponding rank,
but this is not the case, 
I had an incorrect shape error with on rank 0 tensor of shape (70, 1), on rank 1 tensor of shape (76, 1) 
and a tensor_list on rank 1 with in position 0 a tensor of shape (70, 1), in position 1 a tensor of shape (76, 1)
After searching for the cause of the error, I found a forum message on a somewhat similar issue with all_gather that stated the shape of the tensor in tensor_list must all be equal ? Is that correct ? Or non-increasing (so that last tensor can have less than full size) ? I worked around the issue using asynchronous send and receive instead of a gather, but this could do with better specification.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @rohan-varma

**Comment by rohan-varma** [comment]
cc @kwen2501 @H-Huang
