### ISSUE TITLE
Are complex tensors on any plan?

### ISSUE THREAD

**Issue by thuyen** [pytorch/pytorch#1033]
I am doing some [FFT](https://github.com/thuyen/signal) and manually manipulating operations with complex numbers is little bit inconvenient. Supporting complex numbers could be great!!

**Comment by soumith** [comment]
we had a complex number backend for torch called ztorch with a limited cuda backend. it's not in our plans to port it over, there are very few people using complex numbers currently to justify the effort over higher priority tasks

**Comment by Roger-luo** [comment]
I was trying to add complex number for TH, because I need a network with complex parameters for research and is the macro name `real` a little bit inconvenient, like in ztorch, it could be a little bit confusing in the source code. Maybe use `num` for `real`, `Num` for `Real` and `NUM` for `REAL` in the source would be more convenient, if complex number will be implemented in the future?

**Comment by fmassa** [comment]
@Roger-luo there has been some work by @PhilippPelz on that, and seems that he has already done some progress in it in https://github.com/pytorch/pytorch/issues/755

**Comment by PhilippPelz** [comment]
see https://github.com/PhilippPelz/pytorch it's compiling, most math working. ffts are broken right now. working on it next week.

**Comment by PhilippPelz** [comment]
I didnt bother about the naming, after all its super easy to understand what's going on.

**Comment by PhilippPelz** [comment]
Help with tests would be very much appreciated, so it can be merged at some point

**Comment by apaszke** [comment]
Let's keep the discussion in #755.

**Comment by lamhoson** [comment]
Any suggestion for latest complex tensor module to be used in PyTorch ?  I need one to handle my research works for complex numbers.

**Comment by Roger-luo** [comment]
@lamhoson working on it: https://github.com/Roger-luo/pytorch-complex

And please keep discussion in #755

**Comment by lamhoson** [comment]
Noted with thanks.




发自网易邮箱 iPhone 版
On 09/14/2018 10:05, Rogerluo wrote:

@lamhoson working on it: https://github.com/Roger-luo/pytorch-complex

And please keep discussion in #755

**Comment by soumith** [comment]
locking the issue so that everyone can move to https://github.com/pytorch/pytorch/issues/755 for discussion
