### ISSUE TITLE
Expose Tensor.retains_grad property in Python API

### ISSUE THREAD

**Issue by ringohoffman** [pytorch/pytorch#103485]
### 🚀 The feature, motivation and pitch

Somewhat Related [Add Tensor.nbytes() / Tensor.itemsize() #12728](https://github.com/pytorch/pytorch/issues/12728) & [Add itemsize and nbytes properties to Tensor #98322](https://github.com/pytorch/pytorch/pull/98322)

The `retains_grad` attribute already exists:

https://github.com/pytorch/pytorch/blob/5f77be8bbef5b7e8f1a02525e93ac43e48884aa7/torch/optim/optimizer.py#L553

it is just not exposed to the Python API. This is leading to type checking issues in `torch/optim/Optimizer.py`: [Merge and improve torch optim optimizer type stubs #102593](https://github.com/pytorch/pytorch/pull/102593#top).

### Alternatives

Do nothing.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @malfet @rgommers @xuzhao9 @gramster

**Comment by ringohoffman** [comment]
@ezyang @janeyx99

**Comment by ezyang** [comment]
To be clear, you just need a type annotation for it right? You can put it in the appropriate pyi file in torch/_C
