### ISSUE TITLE
no += method for torch.tanh

### ISSUE THREAD

**Issue by morningmorningwind** [pytorch/pytorch#10346]
if we run something like 

y = y0
y += torch.tanh(x)

where y0, x are Tensors

I would throw the following error:

_RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation_

My guess is that this "+=" operation is not properly defined in torch.tanh
because when I change the syntax to y = y+ torch.tanh(x), everything works correctly.

My pytorch version is '0.4.0', python version is 2.7.15

**Comment by albanD** [comment]
Hi,

Please use the [forum](https://discuss.pytorch.org/) to ask questions.

The problem is that if y's value is needed by some operation to compute the backward pass, then you will see this error if you try to modify it inplace. And `+=` is doing an inplace change.
