### ISSUE TITLE
Cannot #include <ATen/native/ForeachUtils.h>

### ISSUE THREAD

**Issue by zhuhaozhe** [pytorch/pytorch#103408]
### 🐛 Describe the bug

Cannot `#include <ATen/native/ForeachUtils.h>` after https://github.com/pytorch/pytorch/commit/74b7a6c75e698378882d30958908073407f97fb3.

This commit `include <ATen/native/utils/ParamsHash.h>` which will not be installed by `python setup.py install` https://github.com/pytorch/pytorch/blob/main/setup.py#L1096-L1105.
Should `'include/ATen/native/utils/*.h' be added here?

### Versions

>>> torch.__version__
'2.1.0.dev20230611+cpu'

**Comment by mikaylagawarecki** [comment]
@zhuhaozhe Could you provide more detail on what you mean here

cc Also cc @crcrpar who added the corresponding commit

**Comment by crcrpar** [comment]
Ah that's right. I should have added that header to package_data but I think the commit have been reverted

**Comment by mikaylagawarecki** [comment]
Sounds good, I will close this issue as complete for now then since the offending PR has been reverted :) 

Feel free to reopen otherwise
