### ISSUE TITLE
Normal return earlier without entering normal_kernel<RNG>

### ISSUE THREAD

**Issue by yewentao256** [pytorch/pytorch#103418]
### 🚀 The feature, motivation and pitch

Hello, I noticed that when we call the normal function with an empty shape, it produces an empty tensor. For example:

```py
import torch

a = torch.randn(5, 0)
print(a)            # tensor([], size=(5, 0))
print(a.numel())    # 0
print(hex(a.untyped_storage().data_ptr()))  # 0x0
```

In this case, calling the normal_kernel seems unnecessary as it consumes time and resources. It appears that the normal_kernel invokes the `tensor iterator` and `serial_for_each`, which could be relatively costly.

Would it be beneficial to add some code to the `normal_impl_` function in `aten/src/ATen/native/DistributionTemplates.h` to return earlier in such cases?

### Alternatives

```c++
template<template<typename> class normal_kernel, typename RNG>
Tensor& normal_impl_(Tensor& self, double mean, double std, c10::optional<Generator> gen) {
  CHECK_NORMAL_STD(std);
  /* ####code added here#### */
  if (self.numel() == 0) {
    return self;
  }
  if (self.is_complex()) {
    auto float_tensor = at::view_as_real(self);
    // variance for normal distribution of the real and imaginary values
    // is half of the input variance
    normal_kernel<RNG>()(float_tensor, mean, std/(std::sqrt(2)), gen);
  } else {
    normal_kernel<RNG>()(self, mean, std, gen);
  }
  return self;
}
```

### Additional context

<img width="984" alt="企业微信截图_f7087827-50d0-42e7-9d23-fce9a31e755c" src="https://github.com/pytorch/pytorch/assets/44945378/1218696a-48ac-403b-986d-6869be80269d">

cc @fritzo @neerajprad @alicanb @nikitaved

**Comment by jgong5** [comment]
Make sense to me. Welcome to contribute a PR to enhance it. You may also need to consider other tensor constructors like `uniform`.

**Comment by yewentao256** [comment]
The pr has been merged, close this issue.
