### ISSUE TITLE
Comparing pytorch and theano speed

### ISSUE THREAD

**Issue by singlasahil14** [pytorch/pytorch#1034]
I created the following two models:
Pytorch model:
```
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2(x), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return F.log_softmax(x)

model = Net()
if args.cuda:
    model.cuda()

optimizer = optim.SGD(model.parameters(), lr=args.lr, momentum=args.momentum)
```

Keras model (with theano backend):
```
# number of convolutional filters to use
nb_filters = 10
# size of pooling area for max pooling
pool_size = (2, 2)
# convolution kernel size
kernel_size = (5, 5)

model = Sequential()

model.add(Convolution2D(nb_filters, kernel_size[0], kernel_size[1],
                        border_mode='valid',
                        input_shape=input_shape))
model.add(MaxPooling2D(pool_size=pool_size))
model.add(Activation('relu'))
model.add(Convolution2D(2*nb_filters, kernel_size[0], kernel_size[1]))
model.add(MaxPooling2D(pool_size=pool_size))
model.add(Activation('relu'))

model.add(Flatten())
model.add(Dense(320))
model.add(Activation('relu'))
model.add(Dense(50))
model.add(Activation('relu'))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adadelta',
              metrics=['accuracy'])

model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
          verbose=1, validation_data=(X_test, Y_test))
score = model.evaluate(X_test, Y_test, verbose=0)
```

The time for theano model comes out to be 1 second per epoch. For pytorch model it is 6 seconds per epoch. Am I making a mistake or is pytorch really this slow?

**Comment by apaszke** [comment]
Are you running on CPU or on CUDA?

**Comment by singlasahil14** [comment]
I am using CUDA (with cudNN) for both the runs. My guess is pytorch is slow because it is reading data from the hard drive, while keras is reading into the main memory first. But even then, will there be a 6x difference?

**Comment by apaszke** [comment]
Depends on the data loading code... I thought you benchmarked only the model runtime.

**Comment by singlasahil14** [comment]
I benchmarked only the model runtime. But this was one difference in both the codes.

**Comment by singlasahil14** [comment]
But I doubt that will make a difference, because what keras creates an in memory queue of training batches, so that a batch doesn't have to be fetched from the hard disk once training on another batch is complete. I am assuming pytorch would be doing something like that too.So it shouldn't make such a huge difference.

**Comment by soumith** [comment]
as it's self-reflected, the benchmark is presumably flawed. as core devs, we don't see any bugs or features to be added. correct us if I'm wrong.

**Comment by jekbradbury** [comment]
@singlasahil14 This should move to discuss.pytorch.org, but if you link a full snippet there to reproduce your PyTorch experiment, we can try to figure out what’s going on.
