### ISSUE TITLE
narrow tensor to zero elements fails with misleading error message

### ISSUE THREAD

**Issue by alexholdenmiller** [pytorch/pytorch#10351]
Hi all,

I expected narrowing a tensor to length zero to give me an empty tensor, but instead it gave an error that the target size exceeded the size of the tensor (at least this error message isn't exactly right, even if an error is the expected behavior).

```
>>> import torch
>>> a = torch.Tensor([1,2,3])
>>> a.narrow(0, 0, 1)
tensor([1.])
>>> a.narrow(0, 0, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: start (0) + length (0) exceeds dimension size (3).
>>> torch.__version__
'0.4.1'
```

Thanks!

**Comment by zou3519** [comment]
Fixed in master, closing
