### ISSUE TITLE
[Inductor] Constant folding support for FX module captured by Dynamo Export 

### ISSUE THREAD

**Issue by leslie-fang-intel** [pytorch/pytorch#103582]
### 🐛 Describe the bug

As discussed here https://github.com/pytorch/pytorch/pull/101164#discussion_r1195953417, the Quantization 2.0 with Inductor backend needs the support of constant folding pass in order to do weight prepack for convolution and linear operations.

The general use case in Quantization 2.0 with Inductor backend is as:  
 https://github.com/pytorch/pytorch/blob/040d2cc96953290bfe49e32dbb250fa9df6f51ce/test/quantization/pt2e/test_quantize_pt2e_fx.py#L325-L446

- Step1: `torchdynamo.export` to capture the fx graph.
- Step2: Pass the quantization 2.0 flow to generate reference quantized module.
- Step3: Use `compile_fx` lower into Inductor with the reference quantized module.

When I try to use constant passes inside inductor with the example in this [gist](https://gist.github.com/leslie-fang-intel/c1e1fe49ae9478425d39e14775fde7ea), I got the error of 
```
  File "/home/lesliefang/pytorch_1_7_1/inductor_quant/pytorch/torch/_functorch/aot_autograd.py", line 2273, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/lesliefang/pytorch_1_7_1/inductor_quant/pytorch/torch/_functorch/aot_autograd.py", line 1535, in aot_dispatch_base
    compiled_fw = compiler(fw_module, flat_args)
  File "/home/lesliefang/pytorch_1_7_1/inductor_quant/pytorch/torch/_inductor/compile_fx.py", line 710, in inference_compiler
    fw_metadata=torch._guards.TracingContext.get().fw_metadata,
AttributeError: 'NoneType' object has no attribute 'fw_metadata'
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git69a2611
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.17

Python version: 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.19.5-1.el7.elrepo.x86_64-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    1
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel Genuine CPU
Stepping:              10
CPU MHz:               1199.980
CPU max MHz:           2900.0000
CPU min MHz:           1200.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27
NUMA node1 CPU(s):     28-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] torch==2.1.0a0+git193d841
[pip3] torchvision==0.15.0a0+5850f37
[conda] mkl                       2023.0.0            intel_25398    intel
[conda] mkl-include               2023.0.0            intel_25398    intel
[conda] mkl-include               2023.0.0                  <pip>
[conda] mkl-service               2.4.0           py38h3605609_14    intel
[conda] mkl-static                2023.0.0                  <pip>
[conda] mkl_fft                   1.3.1           py38hcab1719_22    intel
[conda] mkl_random                1.2.2           py38hbf47bc3_22    intel
[conda] mkl_umath                 0.1.1           py38hf66a691_32    intel
[conda] numpy                     1.23.1                    <pip>
[conda] numpy                     1.22.3           py38hf0956d0_5    intel
[conda] numpy-base                1.22.3           py38h45c9ace_5    intel

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @eellison

**Comment by leslie-fang-intel** [comment]
Hi @eellison, as we discussed here https://github.com/pytorch/pytorch/pull/100652#discussion_r1220065231, will you help to further take a look of this issue? Or do you have any suggestions where to get start?

**Comment by andrewor14** [comment]
@leslie-fang-intel What is the status/priority of this? Is this still an issue?

**Comment by leslie-fang-intel** [comment]
I think we can close this issue now. Constant folding and weight prepack supported inside Inductor.
