### ISSUE TITLE
Disabling DISTRIBUTED fails, unable to build on Centos7

### ISSUE THREAD

**Issue by prashantserai** [pytorch/pytorch#10350]
## Issue description

Hi! I'm building PyTorch from Source. I did a Git pull of the repo, and the CMake would complain about MPI not available (error message below).

At first, [#10300](https://github.com/pytorch/pytorch/issues/10300),  I tried  "BUILD_CAFFE2=false;USE_MPI=false;USE_NUMA=false;" but to no avail.

On @soumith 's suggestion, I also tried USE_DISTRIBUTED=0, but again the same error persists.

Please help.

Full installation log here: [full_pytorch_installation_failure_log.txt](https://github.com/pytorch/pytorch/files/2270346/full_pytorch_installation_failure_log.txt)

## Code example
cd pytorch;
cd centos7;
make clean;
USE_DISTRIBUTED=0; python setup.py install;

...
CMake Error in /cbica/home/seraip/pytorch/centos7/torch/lib/build/THD/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path
...

Full installation log here: [full_pytorch_installation_failure_log.txt](https://github.com/pytorch/pytorch/files/2270346/full_pytorch_installation_failure_log.txt)

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): Source
- Build command you used (if compiling from source): python setup.py install
- OS: Centos7
- PyTorch version: 0.4
- Python version: 2.7
- CUDA/cuDNN version: 9.0/7.0
- GPU models and configuration: GeForce GTX 960
- GCC version (if compiling from source): 4.9.2
- CMake version: 3.11.2
- Versions of any other relevant libraries: LAPACK 3.2.1

**Comment by ezyang** [comment]
don't put a semicolon after `USE_DISTRIBUTED=0`. It's not being applied.
