### ISSUE TITLE
How to add testing capabilities for third party devices

### ISSUE THREAD

**Issue by Bin1024** [pytorch/pytorch#103506]
### 🚀 The feature, motivation and pitch

The current community test cases are all cpu and cuda based, there is no ability to look after third party devices, for example many test cases use the @onlycuda decorator, any suggestions for improvements for the privateuse1 device？

**Comment by mikaylagawarecki** [comment]
There is a `PrivateUse1TestBase` if that might be helpful. What improvements are you looking for here?


https://github.com/pytorch/pytorch/blob/71b560208c1d1e60ab0ca693ac02d05515ec9700/torch/testing/_internal/common_device_type.py#L567-L592

**Comment by Bin1024** [comment]
Yeah，I know this. We can instantiate privateuse1 test cases trough `instantiate_device_type_tests` . However, some test base case is decorated by `OnlyCuda`, how to reuse onlycuda's test cases for third party devices？Can you give some advice on this.
