### ISSUE TITLE
suggest adding comments to the nn.Linear method.

### ISSUE THREAD

**Issue by develly** [pytorch/pytorch#103577]
### 📚 The doc issue

I wanted to convert a 3-dimensional tensor using the nn.Linear layer. Since there was no information about 3-dimensional inputs in the nn.Linear documentation, I searched on Google. The most commonly searched method is using view(-1, F) for the transformation.

However, the nn.Linear library also supports inputs with dimensions higher than 3.

*****
I would appreciate it if this information could be explicitly stated in the official documentation
and it would be helpful if the underlying principle behind this support is also specified.
*****

### Suggest a potential alternative/fix

The nn.Linear library also supports inputs with dimensions higher than 3.
I would appreciate it if this information could be explicitly stated in the official documentation
and it would be helpful if the underlying principle behind this support is also specified.

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by Schefflera-Arboricola** [comment]
I would like to work on this issue :)

**Comment by cpuhrsch** [comment]
Thanks for opening the issue @develly and thanks for your contribution @Schefflera-Arboricola.

Hm, but the documentation already says


        - Input: :math:`(*, H_{in})` where :math:`*` means any number of
          dimensions including none and :math:`H_{in} = \text{in\_features}`.

This explicitly says *means any number of dimensions*. 

Does this address your concern? Otherwise, I probably am misreading your issue.

**Comment by develly** [comment]
Thank you for your kind response.
I didn't see that part. I will close the issue.
