### ISSUE TITLE
ATen Core Headers Were Installed to ATen/core/core/*.h instead of ATen/core/*.h

### ISSUE THREAD

**Issue by huanghoujing** [pytorch/pytorch#10353]
## Issue Description

I git clone pytorch to `$PYTORCH_HOME`, and installed it using cmake to directory `$PYTORCH_HOME/build/install`. The ATen core headers were installed to `$PYTORCH_HOME/build/install/include/ATen/core/core/*.h` instead of `$PYTORCH_HOME/build/install/include/ATen/core/*.h` (**I think this is abnormal, because compiling custom operators requires `<ATen/core/*.h>`. See below.**).

The result of `tree $PYTORCH_HOME/build/install/include/ATen`:

```
ATen
`-- core
    `-- core
        |-- AlignOf.h
        |-- ArrayRef.h
        |-- ATenCoreTest.h
        |-- Backtrace.h
        |-- C++17.h
        |-- CoreAPI.h
        |-- DeviceType.h
        |-- Error.h
        |-- Half.h
        |-- Half-inl.h
        |-- IdWrapper.h
        |-- intrusive_ptr.h
        |-- optional.h
        |-- SmallVector.h
        `-- UniqueVoidPtr.h
```

In the [DensePose](https://github.com/facebookresearch/DensePose) project which uses Caffe2, when I built custom operators:
```bash
# In DensePose project
mkdir build && cd build
cmake .. -DCaffe2_DIR=$PYTORCH_HOME/build/install/share/cmake/Caffe2
make
```

The `make` command threw error of not finding `<ATen/core/Error.h>` for `caffe2/core/logging.h`:
```
Scanning dependencies of target caffe2_detectron_custom_ops
[ 12%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
In file included from /home/users/houjing.huang/Software/pytorch/build/install/include/caffe2/core/allocator.h:6:0,
                 from /home/users/houjing.huang/Software/pytorch/build/install/include/caffe2/core/context.h:9,
                 from /home/users/houjing.huang/Project/DensePose/detectron/ops/pool_points_interp.h:13,
                 from /home/users/houjing.huang/Project/DensePose/detectron/ops/pool_points_interp.cc:10:
/home/users/houjing.huang/Software/pytorch/build/install/include/caffe2/core/logging.h:10:29: fatal error: ATen/core/Error.h: No such file or directory
 #include <ATen/core/Error.h>
                             ^
compilation terminated.
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o] Error 1
make[1]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make: *** [all] Error 2
```

I found these lines in file `$PYTORCH_HOME/build/install_manifest.txt`:
```
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/ATenCoreTest.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/AlignOf.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/ArrayRef.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/Backtrace.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/C++17.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/CoreAPI.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/DeviceType.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/Error.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/Half-inl.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/Half.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/IdWrapper.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/SmallVector.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/UniqueVoidPtr.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/intrusive_ptr.h
/mnt/data-1/data/houjing.huang/Software/pytorch/build/install/include/ATen/core/core/optional.h
```

## System Info

- PyTorch or Caffe2: Caffe2
- How you installed PyTorch (conda, pip, source): source, referring to [caffe2.ai](https://caffe2.ai/docs/getting-started.html?platform=centos&configuration=cloud)
- Build command to install Pytorch/Caffe2 (if compiling from source): 

    ```bash
    git clone --recursive https://github.com/pytorch/pytorch
    cd pytorch
    mkdir build && cd build
    cmake \
    -DCUDA_TOOLKIT_ROOT_DIR=$HOME/Software/cuda-8.0 \
    -DCMAKE_INSTALL_PREFIX=${PWD}/install ..
    make -j12 install
    ```

- OS: CentOS Linux release 7.4.1708
- PyTorch version: master branch, commit f57e4ce1d59aab53e48b0ae93a7ef7e9a4dc1e2e
- Python version: 2.7
- CUDA/cuDNN version: CUDA 8.0, cuDNN 7
- GPU models and configuration:
- GCC version (if compiling from source): 4.8.5
- CMake version: 3.12.0
- Versions of any other relevant libraries: DensePose master branch, commit [e118a4](https://github.com/facebookresearch/DensePose/tree/e118a4c352cbaf849d70f47886ce3f6cba76116e)

## Log Files When Installing Pytorch/Caffe2

- The log of pytorch `cmake ..`: [log](https://github.com/huanghoujing/pytorch-caffe2-cmake-log/blob/master/cmake_output_houjing.huang.txt)
- The log of pytorch `make -j12 install`: [log](https://github.com/huanghoujing/pytorch-caffe2-cmake-log/blob/master/make_install_output_houjing.huang.txt)
- [`install_manifest.txt`](https://github.com/huanghoujing/pytorch-caffe2-cmake-log/blob/master/install_manifest.txt)

## Is It A BUG?

I manually copied `$PYTORCH_HOME/build/install/include/ATen/core/core/*.h` to `$PYTORCH_HOME/build/install/include/ATen/core/*.h` and then it's ok to build custom operators and run the tests.

It seems a bug of Pytorch/Caffe2 `make install`?

**Comment by akuz** [comment]
I got the same on Mac, already posted another bug report ;)
