### ISSUE TITLE
Write meta function for rshift

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#103606]
### 🐛 Describe the bug

This is to track support for adding rshfit meta function. While writing some de-quantization code this error popped up:
`NotImplementedError: could not find kernel for aten.__rshift__.Scalar at dispatch key DispatchKey.Meta`

### Versions

Nightly

**Comment by cpuhrsch** [comment]
@drisspg I don't think this is the correct label for this issue. Since you're also sending the PR I won't add the correct one that alerts a bunch of people.
