### ISSUE TITLE
Backend dispatch "QuantizedPrivateUse1" error after replacing "PrivateUse1"

### ISSUE THREAD

**Issue by fmo-mt** [pytorch/pytorch#103663]
### 🐛 Describe the bug

I noticed that PyTorch has already included a customize quantization backend [QuantizedPrivateUse1](https://github.com/pytorch/pytorch/blob/main/c10/core/Backend.h#L53). To implement pytorch quantization for a backend (not CUDA or CPU), we would register implemented functions like: 
```C++
TORCH_LIBRARY_IMPL(quantized, QuantizedPrivateUse1, m) {
  m.impl(TORCH_SELECTIVE_NAME("quantized::empty.memory_format"), TORCH_FN(my_empty_unknown_quantized));
  m.impl(TORCH_SELECTIVE_NAME("quantized::empty_quantized"), TORCH_FN(my_empty_quantized));
}
// and
TORCH_LIBRARY_IMPL(aten, PrivateUse1, m) {
  m.impl("quantize_per_tensor", &my_quantize_per_tensor);
}
```
and during runtime, I would rename this `PrivateUse1` backend to something else like:
```python
torch.utils.rename_privateuse1_backend("my_custom")
```
so I can do below:
```python
float_tensor = torch.randn(1, 3, 14).to('my_custom')  # passed
quantized = torch.quantize_per_tensor(float_tensor, 0.1, 1, torch.qint8)  # passed
quantized.to('cpu')  # error
```
which would throw an error:
```
NotImplementedError: Could not run 'aten::empty_quantized' with arguments from the 'Quantizedmy_custom' backend.
```

This maybe caused when replacing backend string "PrivateUse1" to "my_custom" and it also replaces "QuantizedPrivateUse1" to "Quantizedmy_custom", which I think is a bug.

### Versions

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.0.0a0+git45533da
[pip3] torchvision==0.15.2
[conda] No relevant packages

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by HDCharles** [comment]
@heidongxianhua it looks like you landed this code for quantizedprivateuse1 backend, can youu clarify is this is intended?

**Comment by heidongxianhua** [comment]
> @heidongxianhua it looks like you landed this code for quantizedprivateuse1 backend, can you clarify how is this is intended to work?

yeah, sorry to delay. In fact this log message is expected, only when printing logs, the `PrivateUse1` will be replaced with `my_custom` which you renamed. And all the disptachkey related to `PrivateUse1` will be replaced, because we want users to be aware of `my_custom` (which you renamed `privateuse1` to your own device name) and not `privateue1` directly.  According to the dispatchkey of `CUDA`, all the log info is `**CUDA`, so as for the dispatchkey of `PrivateUse1`, all the log info should be `**my_custom`.

**Comment by fmo-mt** [comment]
> > @heidongxianhua it looks like you landed this code for quantizedprivateuse1 backend, can you clarify how is this is intended to work?
> 
> yeah, sorry to delay. In fact this log message is expected, only when printing logs, the `PrivateUse1` will be replaced with `my_custom` which you renamed. And all the disptachkey related to `PrivateUse1` will be replaced, because we want users to be aware of `my_custom` (which you renamed `privateuse1` to your own device name) and not `privateue1` directly. According to the dispatchkey of `CUDA`, all the log info is `**CUDA`, so as for the dispatchkey of `PrivateUse1`, all the log info should be `**my_custom`.

Thanks for replying, but I do implement these functions that called by QuantizedPrivateUse1 backend (which failed to call and throw an error as you see above), so are there other works I need to do to make sure PyTorch know exactly how to dispatch theses functions?

**Comment by heidongxianhua** [comment]
as for your error message, `NotImplementedError: Could not run 'aten::empty_quantized' with arguments from the 'Quantizedmy_custom' backend.`, you should register and implement the `empty_quantized`, which means you should register it to the `aten` namespace not `quantized`

**Comment by fmo-mt** [comment]
> as for your error message, `NotImplementedError: Could not run 'aten::empty_quantized' with arguments from the 'Quantizedmy_custom' backend.`, you should register and implement the `empty_quantized`, which means you should register it to the `aten` namespace not `quantized`

When I replaced my code to:
```c++
// TORCH_LIBRARY_IMPL(quantized, QuantizedPrivateUse1, m) {
TORCH_LIBRARY_IMPL(aten, QuantizedPriateUse1, m) {
  m.impl(TORCH_SELECTIVE_NAME("quantized::empty.memory_format"), TORCH_FN(my_empty_unknown_quantized));
  m.impl(TORCH_SELECTIVE_NAME("quantized::empty_quantized"), TORCH_FN(my_empty_quantized));
}
// and
TORCH_LIBRARY_IMPL(aten, PrivateUse1, m) {
  m.impl("quantize_per_tensor", &my_quantize_per_tensor);
}
```
pytorch would throw an error like:
```
terminate called after throwing an instance of 'c10::Error'
  what():  impl("quantized::empty.memory_format", ...): Explicitly provided namespace (quantized) in operator name does not match namespace of enclosing TORCH_LIBRARY
_IMPL block (aten).  Move this definition to the TORCH_LIBRARY_IMPL block corresponding to this namespace (and consider deleting the namespace from your schema string
.)
```
so I think we need a way to register my backend and let pytorch know exactly how to dispatch these methods correctly.
