### ISSUE TITLE
[feature request] callback or hook when dataset iteration restarts

### ISSUE THREAD

**Issue by samson-wang** [pytorch/pytorch#10364]
In some cases, I would like to do some stuff at the beginning of each epoch.

One can implement a Sampler to explicitly call a customer dataset function before return a iterator.

However, I think a default callback/hook entry in Dataset and Dataloader is much easier and handy.

Here is what I use in practice.

In dataset base class.
```
class Dataset(object):
....
    def restart(self):
        '''callback entry'''
        pass
```

In dataloader , callback when new an iterator
```
class _DataLoaderIter(object):
    def __init__(self, loader):
        self.dataset = loader.dataset
        self.dataset.restart()
        ...
```

Thanks.

**Comment by SsnL** [comment]
Hmm when to start a new DataLoaderIter is completely in the hand of users. I don't see why we should provide this.

**Comment by sebastianberns** [comment]
You might want to check out [ignite](https://github.com/pytorch/ignite/) which provides an [event system](https://pytorch.org/ignite/concepts.html#events-and-handlers) similar to what you’re asking for (Events.EPOCH_STARTED).

[Here’re some examples](https://github.com/pytorch/ignite/tree/master/examples) to get you started.

**Comment by samson-wang** [comment]
@sebastianberns It's cool. Thanks!

@SsnL I see. Just do it before each epoch iteration. Forget it. lol
