### ISSUE TITLE
RuntimeError: Function not implemented at /pytorch/torch/lib/THD/process_group/General.cpp:17

### ISSUE THREAD

**Issue by mjc14** [pytorch/pytorch#10363]
i find some problem, the same code and same env.  some machine my code can work,but some machine have some error as follow:

    dist.init_process_group('nccl', world_size=world_size, init_method='file://shared_distributed')
  File "/home/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
    group_name, rank)
RuntimeError: Function not implemented at /pytorch/torch/lib/THD/process_group/General.cpp:17

- PyTorch :
 installed PyTorch by ,pip
- OS:
linux
- PyTorch version:
0.4.0
- Python version:
3.6.6
- CUDA/cuDNN version:
cuda/9.0              4) nccl/2.1.15-cuda9.0
- GPU models and configuration:
NVIDIA-SMI 390.67                 Driver Version: 390.67
Tesla K40m

**Comment by TairuiWang** [comment]
any idea to solve this? I have the same problem

**Comment by mjc14** [comment]
sorry ,i did not find the solution. i change to other machine , it did not have this problem.

**Comment by ngimel** [comment]
Closing due to age.
