### ISSUE TITLE
Default qconfig for onednn backend silently causes numeric saturation on CPUs without avx512_vnni

### ISSUE THREAD

**Issue by andravin** [pytorch/pytorch#103646]
The default quantization configuration for the onednn backend causes numeric saturation during inference on any CPU that does not have the Intel AVX-512 Vector Neural Network Instructions (VNNI).

The model output will be wrong on all CPUs that do not report `avx512_vnni` in `/proc/cpuinfo`.

This has been verified with torch versions 1.13.1, 2.0.0, and 2.0.1. 

When VNNI is not available,  the onednn backend silently chooses [kernels that assume multiplications are 7-bit x 8-bit](https://oneapi-src.github.io/oneDNN/dev_guide_int8_computations.html#inputs-of-mixed-type-u8-and-s8).

These kernels are incompatible with the default onednn qconfig, which uses 8-bits for both weights and activations, as indicated by the argument `reduce_range=False`.

https://github.com/pytorch/pytorch/blob/3d6fd07c46e23250c7e12b6965b4e8b0f85df4c1/torch/ao/quantization/qconfig.py#L247-L249

We noticed the issue because our quantization unit tests failed on most of the CPUs in our lab when using the onednn backend. The tests passed on all CPUs when using the x86 backend.

Note the two machines that had VNNI were a server and a laptop; the machines that failed were a workstation, a laptop, and several servers.

The default qconfig for the x86 backend sets `reduce_range=True` so that the quantization uses 7-bit activations to avoid this issue. It is surprising to the user that the onednn has the same issue even though it chooses `reduce_range=False` by default. 
 
The documentation does not mention the VNNI requirement for the correct operation of onednn with the default configuration.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by leslie-fang-intel** [comment]
Thanks for reporting this issue @andravin. Will take a look and keep you updated.

**Comment by jgong5** [comment]
@andravin BTW, it is recommended to use the default "x86" backend on x86 CPUs. Underneath, it will automatically dispatch to oneDNN or FBGEMM kernel according to CPU types and the kernel efficiency. On the other hand, we will amend the documentation to recommend using onednn backend only on CPUs with VNNI. Please review the PR 
@leslie-fang-intel submitted: https://github.com/pytorch/pytorch/pull/103653. Thanks.

**Comment by andravin** [comment]
Thank you for responding so quickly. For our use case, we want a reference implementation for 8-bit x 8-bit quantization that works on all x86 CPUs. Speed is secondary. The "x86" backend uses `reduce_range=True` in the default qconfig, so I expect it to use 7-bit x 8-bit.

Is there a quantization backend that can be used as a reference implementation for 8-bit on all x86 CPUs, even if it runs slower? 7-bit quantization does not fit our use case.

Also, the user might appreciate a function that checks the CPU for AVX512-VNNI support. Here is an example:
https://github.com/casparvl/pytorch/blob/aebe64b632fb112ce3db894c82b0c900d8e34ffa/torch/testing/_internal/common_utils.py#L621-L628

Also, it might be helpful to generate a warning if the "onednn" backend is used on a CPU without AVX512-VNNI.

**Comment by HDCharles** [comment]
would it make sense to just change the default observer to check for that instructionset and set reduce range if its not there?

**Comment by jgong5** [comment]
> would it make sense to just change the default observer to check for that instructionset and set reduce range if its not there?

Are you suggesting to add an option for "automatically" set reduce range? I guess the main problem is that the machine for calibration could be different from the machine that the quantized model is deployed.

**Comment by andravin** [comment]
@jgong5 Thanks for mentioning `convert_to_reference_fx`; that fits our use case exactly.

**Comment by supriyar** [comment]
@jgong5, @leslie-fang-intel is this resolved? Please feel free to close it if so

**Comment by leslie-fang-intel** [comment]
I think it's got resolved by PR: https://github.com/pytorch/pytorch/pull/103653
@andravin feel free to re-open it if further questions.
