### ISSUE TITLE
No pretrained parameter for all VGG models

### ISSUE THREAD

**Issue by hubertlee915** [pytorch/pytorch#1037]
The doc said there is a "pretrained" parameter for models as follows:
torchvision.models.vgg11
torchvision.models.vgg13
torchvision.models.vgg16
torchvision.models.vgg19

but actually they don't have the parameter.

**Comment by DmitryUlyanov** [comment]
Take a look at https://github.com/pytorch/vision/issues/106

**Comment by hubertlee915** [comment]
Thank you for your answer!
