### ISSUE TITLE
Different source for identical tensors on `MetaConverter`.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#103762]
### 🐛 Describe the bug

**Command:** `python torchbench.py -d cpu --amp --accuracy --backend inductor --inference --dynamic-shapes --only yolov3`

During the execution of `yolov3` benchmark, there are 2 different sources that are getting assigned to the same tensor (calling `id` on them returns the same number): `LocalSource('p')` and `GetItemSource(LocalSource('out'), index=88)`.

Instrumenting the functions that modify `MetaConverter.tensor_memo` with print statements, I see the following:

```python
# tensor_memo is set for this id here, using this source.
MetaConverter.meta_tensor: before set_tensor_memo: LocalSource(local_name='p')
MetaConverter.set_tensor_memo: <weakref at 0x7f596fd346d0; to 'Tensor' at 0x7f59701a77c0> (id: 140022109599680)
MetaConverter.set_tensor_memo: key: Tensor(torch.Size([4, 255, 12, 16]), dtype=torch.bfloat16)
...
# tensor_memo retrieves the tensor stored above.
# These are the only lines that reference id: 140022109599680
FakeTensorConverter.from_real_tensor: GetItemSource(base=LocalSource(local_name='out'), index=88, index_is_slice=False)
FakeTensorConverter._get_memo: <weakref at 0x7f596f5b9a40; to 'Tensor' at 0x7f59701a77c0> (id: 140022109599680)
FakeTensorConverter._get_memo: key: Tensor(torch.Size([4, 255, 12, 16]), dtype=torch.bfloat16)
```

**Problem:** the value retrieved by `_get_memo` for the second source is the same as the one added for the first.
Is this expected behavior?

-----

**Context:** on #102563, I am mapping `Source -> sympy.Symbol` inside `ShapeEnv` function. When `ShapeEnv.produce_guards` was called, there were some sources that hadn't gone through `ShapeEnv.create_symbolic_sizes_strides_storage_offset` before (the function where I actually create the mappings). Turns out that the reason for that was because it was early returning when it found the tensor in `MetaConverter.tensor_memo`.

### Versions

based on commit: `96fd28364085a7bfe73138b005ce9552fd5fa081`

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ysiraichi** [comment]
cc @ezyang

**Comment by ezyang** [comment]
This is an interesting question.

Naively, I would expect it OK for the same tensor to show up from multiple sources. After all, if I have a function that takes two arguments x and y, I need to account for cases when x and y are different, as well as when they are the same. Aliasing of the inputs materially impacts the compiled graph in multiple cases, including if we mutate the tensors (including metadata mutation), if we do an `is` test, or if we backwards through them. Thus, it would be reasonable for Dynamo to specialize on the aliasing relationship of inputs (see also conversation between @voznesenskym and @jansel in https://github.com/pytorch/pytorch/pull/103205/files/0c29a878850bd17774e25edb592c76e6afa26afd#r1226962921 I don't know if we actually do so.

Assuming we guard on aliasing relationships, then when we encounter the same tensor accessed via a different source, we should collapse the sources to a single source, and add a guard that the two sources have the same identity tensor. This should resolve your downstream problem.

Not sure if you should actually do this. @mlazos what was your plan?

**Comment by ysiraichi** [comment]
The problem seems to go away on: `18dacf7e793`
