### ISSUE TITLE
nn.Linear() different output for the same inputs

### ISSUE THREAD

**Issue by tpnn68** [pytorch/pytorch#103728]
### 🐛 Describe the bug

I ran the code below. It should be equal as expected. But It is slightly different at 0.0001.
So nn.Linear() produce diffrent outputs. How can I solve it? Thanks.

`import torch
import torch.nn as nn

linear2 = nn.Linear(128, 550, bias=False).cuda()

input = torch.rand(32, 128).cuda()

output1 = linear2(input)

out = []
for i in range(input.shape[0]):
    cc = linear2(input[i])
    out.append(cc)

output2 = torch.stack(out)

print(output1)
print(output2)

eq = output1 == output2
print(eq)
if False in eq:
    print("not equal")
`

outputs:
`tensor([[ 0.1507,  0.0995, -0.3166,  ..., -0.1692, -0.5239, -0.5212],
        [ 0.4370,  0.1335, -0.3252,  ...,  0.4012, -0.5054, -0.3509],
        [ 0.2244, -0.1164, -0.4885,  ..., -0.0036, -0.6535, -0.4262],
        ...,
        [ 0.1959,  0.3744, -0.5349,  ...,  0.2673, -0.8506, -0.5047],
        [ 0.1315,  0.2482, -0.7471,  ...,  0.1816, -0.5079, -0.4606],
        [ 0.5691,  0.1456, -0.3202,  ..., -0.3013, -0.6323, -0.1929]],
       device='cuda:0', grad_fn=<MmBackward0>)

tensor([[ 0.1506,  0.0996, -0.3166,  ..., -0.1691, -0.5239, -0.5211],
        [ 0.4369,  0.1335, -0.3251,  ...,  0.4012, -0.5054, -0.3507],
        [ 0.2245, -0.1164, -0.4884,  ..., -0.0035, -0.6535, -0.4259],
        ...,
        [ 0.1959,  0.3745, -0.5349,  ...,  0.2675, -0.8507, -0.5046],
        [ 0.1315,  0.2482, -0.7470,  ...,  0.1817, -0.5078, -0.4606],
        [ 0.5691,  0.1456, -0.3201,  ..., -0.3013, -0.6322, -0.1928]],
       device='cuda:0', grad_fn=<StackBackward0>)

tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]], device='cuda:0')
not equal`

### Versions

Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.28

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-100-generic-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.4.48
CUDA_MODULE_LOADING set to:
GPU models and configuration:
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe

Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 57 bits virtual
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Gold 6326 CPU @ 2.90GHz
Stepping:            6
CPU MHz:             899.982
CPU max MHz:         3500.0000
CPU min MHz:         800.0000
BogoMIPS:            5800.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            24576K
NUMA node0 CPU(s):   0-15,32-47
NUMA node1 CPU(s):   16-31,48-63
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] bert4torch==0.2.7
[pip3] flake8==4.0.1
[pip3] lion-pytorch==0.1.2
[pip3] numpy==1.23.5
[pip3] PaLM-rlhf-pytorch==0.2.1
[pip3] snntorch==0.6.2
[pip3] torch==1.10.0
[pip3] torch-tb-profiler==0.3.1
[pip3] torch4keras==0.0.6
[pip3] torchaudio==0.10.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.11.1
[pip3] torchviz==0.0.2
[conda] bert4torch                0.2.7                    pypi_0    pypi
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.3.1               h2bc3f7f_2    defaults
[conda] cudatoolkit-dev           11.4.0           py39h3811e60_2    conda-forge
[conda] libblas                   3.9.0            12_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            12_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            12_linux64_mkl    conda-forge
[conda] lion-pytorch              0.1.2                    pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py39h7f8727e_0    defaults
[conda] mkl_fft                   1.3.1            py39hd3c417c_0    defaults
[conda] mkl_random                1.2.2            py39h51133e4_0    defaults
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] palm-rlhf-pytorch         0.2.1                    pypi_0    pypi
[conda] pytorch                   1.10.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] snntorch                  0.6.2                    pypi_0    pypi
[conda] torch-tb-profiler         0.3.1                    pypi_0    pypi
[conda] torch4keras               0.0.6                    pypi_0    pypi
[conda] torchaudio                0.10.0               py39_cu113    pytorch
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.11.1               py39_cu113    pytorch
[conda] torchviz                  0.0.2                    pypi_0    pypi

**Comment by Schefflera-Arboricola** [comment]
hi, the slight difference is caused by rounding errors. you can use `eq = torch.allclose(output1, output2, atol=1e-4)` instead of `eq = output1 == output2`

**Comment by zou3519** [comment]
This is expected, please see https://pytorch.org/docs/stable/notes/numerical_accuracy.html#batched-computations-or-slice-computations for details.

**Comment by nobody81127** [comment]
I applied a floating-point error analysis algorithm to calculate the error bounds for the result of output1, and I found that the result of output2 falls within this range. Therefore, I believe this is indeed a floating-point error, likely caused by differences in the order of operations. @zou3519
