### ISSUE TITLE
Zero-dimensional tensor.tolist() returns float

### ISSUE THREAD

**Issue by alxmopo3ov** [pytorch/pytorch#10371]
Hello!

```python
import torch
print(torch.FloatTensor([3.15]).squeeze().tolist())
print(type(torch.FloatTensor([3.15]).squeeze().tolist()).__name__)
```
prints
```
3.1500000953674316
float
```

Seems like zero-dimensional tensors (i.e. scalars introduced in torch 0.4) have a bit confusing behavior of the tolist method: it returns the value itself not wrapped to list

Is it bug or expected behavior?

Thank you!

**Comment by fmassa** [comment]
I believe this is expected behavior.
We actually have (almost all the time) that

```python
torch.tensor(tensor.tolist()) == tensor
```

Also, this is the same behavior as numpy.

**Comment by alxmopo3ov** [comment]
Ok, thank you!
