### ISSUE TITLE
[ONNX] Discuss improvements to Diagnostic public API

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#103713]
### 🐛 Describe the bug

Currently, when we use the diagnostic system through `@diagnostics.diagnose_call`, we need to create an extra utility function, that usually is only used once because it is function-signature-specific.

To diagnose
```def foo(a: int, b: float, c : bool)
      pass
```

We need to first create a helper:
```
def _foo_formatter(fx: Callable, diagnostic_context: diagnostics.DiagnosticContext,, a: int, b: float, c : bool)
    return "string_consuming_a_or_b_or_c"
```

Next we decorate the function
```
    @diagnostics.diagnose_call(
        diagnostics.rules.XXX,
        diagnostic_message_formatter=_foo_formatter,
    )
```

This is error prone because 
* every time the function/method signature changes, the utility signature must also change, which creates unnecessary coupling.
* beartype error message is not trivial to understand
* call site becomes cluttered with utlities flying around

A proposal is to replace the formatter as callable to string.
We can leverage how decorators are implemented and automatically create a hidden lambda/utility function that mimics the callable signature.
`diagnose_call` receives the callable, then it inspects the callable and find out the function/method signature. Next it builds a temporary function with the inspected signature and its implementation `return USER_FORMAT_STRING`

That would make the use of the decorator simpler to the user because they won't need to change the utility signature every time the callable also changes. They only pass the string they want to print, like python formatted strings already work.

### Versions

main

**Comment by BowenBao** [comment]
String formatter loses flexibility. The older design was to look at the string format defined in `rules.yaml`. That serves the same effect as what you have proposed. But no more advanced reasoning.

And still the main concern about flakiness around argument/signature changes over time is not addressed. I don't think there is a way around that, as long as we want to offer the convenience function. Whatever we do it will always break when signature changes, i.e. argument renamed, argument removed, etc. We can come up with adversarial examples like swapping order of two args with same type and it won't even be detected by beartype as error.

If this really is a concern imo we should just drop it.

**Comment by thiagocrepaldi** [comment]
The idea is to use `inspect` to capture the function signature. Wouldn't that solve the problem of signature changes?!

**Comment by BowenBao** [comment]
user string format needs either argument name or argument position for formatting. i.e. f"optype: {node.op}", or f"{args[0].op}". How to handle signature changes like arg renaming or arg positional change?

**Comment by thiagocrepaldi** [comment]
> user string format needs either argument name or argument position for formatting. i.e. f"optype: {node.op}", or f"{args[0].op}". How to handle signature changes like arg renaming or arg positional change?

The API would get a string, not a resolved string. `"optype: {node.op}"` instead of `f"optype: {node.op}"`, so if `node` exists in the function/method signature, we should be good

the `diagnose_call` would have code that would build a function or lambda and runtime which received the user string. the return of that function would be `return f"{USER_FORMAT_STRING" which then would expand the specified string and create the proper message. Makes sense?

**Comment by BowenBao** [comment]
Lol, my point is there is no guarantee `node` exists. You basically ignored the second sentence in my last comment. People rename it to `fx_node` and it crash. This issue is about robustness against signature change. The proposal does not improve that.

**Comment by thiagocrepaldi** [comment]
Oh got it, but that would happen even with a `print(f"{node.op}")` or `logging.info(f"{node.op}")`. It is the user responsibility to keep the message up to date. No API in the world can do that for them lol
