### ISSUE TITLE
Installtion issues

### ISSUE THREAD

**Issue by srinivasans74** [pytorch/pytorch#103874]
### 🐛 Describe the bug

Hi All i tried installation Pytorch from source since i had to make some modifications. I had used USE_CUDA=OFF to disable the CUDA portion to be build. 

when i run python3 setup.py install. I am facing the below issue
[4634/6992] Building CXX object third_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/src/FbgemmI8DepthwiseAvx2.cc.o
ninja: build stopped: subcommand failed.
It just stops the ninja build here. 

I only want to use pytorch for rocm, what else should i comment off in the below installation

```
**Also i have attached the changes made in the setup file**

# Welcome to the PyTorch setup.py.
#
# Environment variables you are probably interested in:
#
#   DEBUG
#     build with -O0 and -g (debug symbols)
#
#   REL_WITH_DEB_INFO
#     build with optimizations and -g (debug symbols)
#
#   MAX_JOBS
#     maximum number of compile jobs we should use to compile your code
USE_CUDA=0
#     disables CUDA build
#
#   CFLAGS
#     flags to apply to both C and C++ files to be compiled (a quirk of setup.py
#     which we have faithfully adhered to in our build system is that CFLAGS
#     also applies to C++ files (unless CXXFLAGS is set), in contrast to the
#     default behavior of autogoo and cmake build systems.)
#
#   CC
#     the C/C++ compiler to use
#
# Environment variables for feature toggles:
#
USE_CUDNN=0
#     disables the cuDNN build
#
#USE_FBGEMM=0
#     disables the FBGEMM build
#
#   USE_KINETO=0
#     disables usage of libkineto library for profiling
#
#   USE_NUMPY=0
#     disables the NumPy build
#
#   BUILD_TEST=0
#     disables the test build
#
#USE_MKLDNN=0
#     disables use of MKLDNN
#
#   USE_MKLDNN_ACL
#     enables use of Compute Library backend for MKLDNN on Arm;
#     USE_MKLDNN must be explicitly enabled.
#
#   MKLDNN_CPU_RUNTIME
#     MKL-DNN threading mode: TBB or OMP (default)
#
#   USE_STATIC_MKL
#     Prefer to link with MKL statically - Unix only
#   USE_ITT=0
#     disable use of Intel(R) VTune Profiler's ITT functionality
#
#   USE_NNPACK=0
#     disables NNPACK build
#
#   USE_QNNPACK=0
#     disables QNNPACK build (quantized 8-bit operators)
#
#   USE_DISTRIBUTED=0
#     disables distributed (c10d, gloo, mpi, etc.) build
#
#   USE_TENSORPIPE=0
#     disables distributed Tensorpipe backend build
#
#   USE_GLOO=0
#     disables distributed gloo backend build
#
#   USE_MPI=0
#     disables distributed MPI backend build
#
#   USE_SYSTEM_NCCL=0
#     disables use of system-wide nccl (we will use our submoduled
#     copy in third_party/nccl)
#
#BUILD_CAFFE2_OPS=0
#     disable Caffe2 operators build
#
#BUILD_CAFFE2=0
#     disable Caffe2 build
#
#   USE_IBVERBS
#     toggle features related to distributed support
#
#   USE_OPENCV
#     enables use of OpenCV for additional operators
#
#   USE_OPENMP=0
#     disables use of OpenMP for parallelization
#
#   USE_FFMPEG
#     enables use of ffmpeg for additional operators
#
#   USE_FLASH_ATTENTION=0
#     disables building flash attention for scaled dot product attention
#
#   USE_LEVELDB
#     enables use of LevelDB for storage
#
#   USE_LMDB
#     enables use of LMDB for storage
#
#   BUILD_BINARY
#     enables the additional binaries/ build
#
#   ATEN_AVX512_256=TRUE
#     ATen AVX2 kernels can use 32 ymm registers, instead of the default 16.
#     This option can be used if AVX512 doesn't perform well on a machine.
#     The FBGEMM library also uses AVX512_256 kernels on Xeon D processors,
#     but it also has some (optimized) assembly code.
#
#   PYTORCH_BUILD_VERSION
#   PYTORCH_BUILD_NUMBER
#     specify the version of PyTorch, rather than the hard-coded version
#     in this file; used when we're building binaries for distribution
#
#   TORCH_CUDA_ARCH_LIST
#     specify which CUDA architectures to build for.
#     ie `TORCH_CUDA_ARCH_LIST="6.0;7.0"`
#     These are not CUDA versions, instead, they specify what
#     classes of NVIDIA hardware we should generate PTX for.
#
PYTORCH_ROCM_ARCH="gfx908"
#     specify which AMD GPU targets to build for.
#     ie `PYTORCH_ROCM_ARCH="gfx908";gfx906"`
#
#   ONNX_NAMESPACE
#     specify a namespace for ONNX built here rather than the hard-coded
#     one in this file; needed to build with other frameworks that share ONNX.
#
#   BLAS
#     BLAS to be used by Caffe2. Can be MKL, Eigen, ATLAS, FlexiBLAS, or OpenBLAS. If set
#     then the build will fail if the requested BLAS is not found, otherwise
#     the BLAS will be chosen based on what is found on your system.
#
#   MKL_THREADING
#     MKL threading mode: SEQ, TBB or OMP (default)
#
#   USE_REDIS
#     Whether to use Redis for distributed workflows (Linux only)
#
#   USE_ZSTD
#     Enables use of ZSTD, if the libraries are found
#
# Environment variables we respect (these environment variables are
# conventional and are often understood/set by other software.)
#
#   CUDA_HOME (Linux/OS X)
#   CUDA_PATH (Windows)
#     specify where CUDA is installed; usually /usr/local/cuda or
#     /usr/local/cuda-x.y
#   CUDAHOSTCXX
#     specify a different compiler than the system one to use as the CUDA
#     host compiler for nvcc.
#
#   CUDA_NVCC_EXECUTABLE
#     Specify a NVCC to use. This is used in our CI to point to a cached nvcc
#
#   CUDNN_LIB_DIR
#   CUDNN_INCLUDE_DIR
#   CUDNN_LIBRARY
#     specify where cuDNN is installed
#
#   MIOPEN_LIB_DIR
#   MIOPEN_INCLUDE_DIR
#   MIOPEN_LIBRARY
#     specify where MIOpen is installed
#
#   NCCL_ROOT
#   NCCL_LIB_DIR
#   NCCL_INCLUDE_DIR
#     specify where nccl is installed
#
#   NVFUSER_SOURCE_DIR
#     specify nvfuser root directory
#
#   NVTOOLSEXT_PATH (Windows only)
#     specify where nvtoolsext is installed
#
#   ACL_ROOT_DIR
#     specify where Compute Library is installed
#
#   LIBRARY_PATH
#   LD_LIBRARY_PATH
#     we will search for libraries in these paths
#
#   ATEN_THREADING
#     ATen parallel backend to use for intra- and inter-op parallelism
#     possible values:
#       OMP - use OpenMP for intra-op and native backend for inter-op tasks
#       NATIVE - use native thread pool for both intra- and inter-op tasks
#       TBB - using TBB for intra- and native thread pool for inter-op parallelism
#
#   USE_TBB
#      enable TBB support
#
#   USE_SYSTEM_TBB
#      Use system-provided Intel TBB.
#
#   USE_SYSTEM_LIBS (work in progress)
#      Use system-provided libraries to satisfy the build dependencies.
#      When turned on, the following cmake variables will be toggled as well:
#        USE_SYSTEM_CPUINFO=ON USE_SYSTEM_SLEEF=ON BUILD_CUSTOM_PROTOBUF=OF
```

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-72-generic-x86_64-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 515.105.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

**Comment by janeyx99** [comment]
Hi, could you remove the # at the start of each line in your collect_env output to make this issue readable? Also, to confirm, were you following the instructions here https://github.com/pytorch/pytorch#from-source?

**Comment by srinivasans74** [comment]
Hi I followed all the instruction, In fact i reinstalled a fresh new copy of pytorch and these were the steps followed

conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
python tools/amd_build/build_amd.py
python setup.py develop

I am able to get pytorch running but the output from get_collect_envs.py is strange

PyTorch version: 2.1.0a0+git7ce932a
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 0.0.0

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

**Comment by janeyx99** [comment]
What is the problem?

**Comment by srinivasans74** [comment]
> What is the problem?

I am not able to detect my amd gpu

**Comment by janeyx99** [comment]
You probably wanna run something like

`python setup.py clean && PYTORCH_ROCM_ARCH="gfx908" python setup.py develop`

**Comment by srinivasans74** [comment]
> You probably wanna run something like
> 
> `python setup.py clean && PYTORCH_ROCM_ARCH="gfx908" python setup.py develop`



> You probably wanna run something like
> 
> `python setup.py clean && PYTORCH_ROCM_ARCH="gfx908" python setup.py develop`

Hi my rocm versionn is 5.3 So i am using an older version
PYTORCH_BUILD_VERSION=1.11 PYTORCH_BUILD_NUMBER=0 MAX_JOBS=48  PYTORCH_ROCM_ARCH="gfx908"python3 setup.py develop

**Comment by janeyx99** [comment]
Sure, I'm not sure why PYTORCH_BUILD_VERSION=1.11 and PYTORCH_BUILD_NUMBER=0 are necessary but I'll let you figure it out. Basically, don't edit the actual setup.py script but just pass in those environment variables as you call `python setup.py develop` to configure your build.

**Comment by srinivasans74** [comment]
> 

Hi I used the exact steps mentioned. Still my gpu is not getting detected

PyTorch version: 2.1.0a0+git7ce932a
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 0.0.0

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

**Comment by janeyx99** [comment]
Please run a clean step before starting your next build to clear any existing cache. If you're expecting CUDA to be picked up, then something in your environment may be preventing cuda from being found. 

If you want to trial run to make sure the right flags are set, run the same command with `CMAKE_ONLY=True` as well, and check the output to see that CUDA has been picked up.

**Comment by srinivasans74** [comment]
> Please run a clean step before starting your next build to clear any existing cache. If you're expecting CUDA to be picked up, then something in your environment may be preventing cuda from being found.
> 
> If you want to trial run to make sure the right flags are set, run the same command with `CMAKE_ONLY=True` as well, and check the output to see that CUDA has been picked up.

Hi we need to mention export HIP_PLATFORM=amd

otherwise it will not detect it

**Comment by janeyx99** [comment]
Ah, so has the issue been resolved?

**Comment by srinivasans74** [comment]
Yes it is

**Comment by janeyx99** [comment]
Nice, closing then!
