### ISSUE TITLE
FSDP full precision `model.eval` silently failing 

### ISSUE THREAD

**Issue by mikeyshulman** [pytorch/pytorch#103862]
### 🐛 Describe the bug

I'm calling `model.eval()` on an FSDP wrapped model to evaluate performance in full precision. Some parameters are not getting cast properly, leading to incorrect results (but no errors). 

### Fix that works: 
Traversing the `wrapped_model.named_modules()` and setting `module.train(False)` on the correct modules (prone to breakage)

### Fix that doesn't work but may be illuminating in debugging: 
Traversing the wrapped module and calling `module.train(False)` instead of calling `wrapped_model.eval()` makes the failure not silent: `F.scaled_dot_product_attention` throws an error that it got inputs of fp32 but expected inputs of bf16. Specifically, calling `module.train(False)` on the module that is the block for FSDP wrapping causes the break.

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230609+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1035-oracle-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 515.105.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-127
Off-line CPU(s) list:            128-255
Thread(s) per core:              1
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7J13 64-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         2550.000
CPU max MHz:                     3673.0950
CPU min MHz:                     1500.0000
BogoMIPS:                        4899.83
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-15
NUMA node1 CPU(s):               16-31
NUMA node2 CPU(s):               32-47
NUMA node3 CPU(s):               48-63
NUMA node4 CPU(s):               64-79
NUMA node5 CPU(s):               80-95
NUMA node6 CPU(s):               96-111
NUMA node7 CPU(s):               112-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f1
6c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt
 xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+9820899b38
[pip3] torch==2.1.0.dev20230609+cu118
[pip3] torchaudio==2.1.0.dev20230609+cu118
[pip3] torchvision==0.16.0.dev20230609+cu118
[pip3] triton==2.0.0
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+9820899b38          pypi_0    pypi
[conda] torch                     2.1.0.dev20230609+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230609+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230609+cu118          pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @zhaojuanmao @mrshenli @rohan-varma @awgu

**Comment by awgu** [comment]
IIUC, calling `model.eval()` is equivalent to calling `module.train(False)` on all `module`s in `model.modules()`. However, your fix is to only call `module.train(False)` on "correct" modules (i.e. a strict subset).

Your issue description suggests that FSDP is not keeping model parameters in full precision, but I wanted to check the following just in case:
1. Do you know if for your case, it is possible that there are modules whose computation changes when `self.training == False` but you expect the computation from `self.training == True`? Could this be being confounded with parameter dtypes not being cast properly?
2. Otherwise, is it possible that the silent incorrectness is from not casting activation dtypes correctly? (e.g., FSDP still casts input activations to low precision, which implicitly causes computations to happen in low precision when they should not?)

This is where having some kind of minimal repro will greatly help us narrow down the issue.

**Comment by awgu** [comment]
> Some parameters are not getting cast properly, leading to incorrect results (but no errors).

> In eval mode, I confirm that the model weights all get cast properly to fp32 but the input to the layer remains in bf16

Given the second statement, I will assume that this overrides the first statement. In that case, the issue may be the same issue as in the linked comment thread: https://github.com/pytorch/pytorch/pull/99546#discussion_r1180898687

**Comment by mikeyshulman** [comment]
so if I read that right, setting `cast_forward_inputs=True` and `cast_root_forward_inputs=False` should fix it? Is that correct?

I confirm that policy for mixed precision seems to resolve the issue. 

Thanks for the help here!

**Comment by awgu** [comment]
@mikeyshulman I think that is a valid temporary workaround. We are discussing how to address this properly though (cc: @rohan-varma).

**Comment by mikeyshulman** [comment]
much appreciated!

**Comment by rohan-varma** [comment]
@mikeyshulman https://github.com/pytorch/pytorch/pull/104223 should fix, can you try it out? thanks!

**Comment by rohan-varma** [comment]
should be resolved
