### ISSUE TITLE
torch.nn.CrossEntropyLoss

### ISSUE THREAD

**Issue by umang299** [pytorch/pytorch#103813]
### 🐛 CrossEntropyLoss() showing conflicting behavior on Windows Vs Online interpreters.

I am trying to perform semantic segmentation. I am using a dataset with 59 classes. My predicted mask has shape 
```[4, 59, 256, 256]``` (float) and Ground Truth Mask is of shape ```[4, 256, 256]``` (float).

I passed these two tensors to the CrossEntropyLoss() function. 
```loss = criterion(pred, target)```

It returns the following error on window 11 with python 3.10.10  and torch version 2.0.1.

```RuntimeError: expected scalar type Long but found Float```

When i run the same command with the exact same variable in kaggle kernel or google Collaboratory it does not throw any error. 

This is a major blocker for me to complete my project. Anyone who has faced a similar problem in the past and was able to debug it can provide a solution.

**Comment by umang299** [comment]
@mingfeima Sure. 


```
criterion = torch.nn.CrossEntropyLoss()
preds = torch.randn((4, 59, 256, 256), dtype=torch.float32)
labels = torch.randn((4, 256, 256), dtype=torch.float32)

loss = criterion(preds, labels)
```

**Comment by mingfeima** [comment]
@jiayisunx could you please take a look at this one ?

**Comment by umang299** [comment]
Can someone address this issue? It is a major blocker to my project. Kindly, take it up on priority. Feel free to reach out for any additional details required from my end. 

Thank you

**Comment by jiayisunx** [comment]
Please refer to the shape requirements of input and target of torch.nn.CrossEntropyLoss in pytorch docs:
![image](https://github.com/pytorch/pytorch/assets/50946601/a6428237-caa7-4e1a-a746-13e3b9a6a801)
So the correct way to use it is:
```
criterion = torch.nn.CrossEntropyLoss()
preds = torch.randn((4, 59, 256, 256), dtype=torch.float32)
labels = torch.empty((4, 256, 256), dtype=torch.long).random_(59)
loss = criterion(preds, labels)
```
or
```
criterion = torch.nn.CrossEntropyLoss()
preds = torch.randn((4, 59, 256, 256), dtype=torch.float32)
labels = torch.randn((4, 59, 256, 256), dtype=torch.float32).softmax(dim=1)
loss = criterion(preds, labels)
```
