### ISSUE TITLE
Loading a network which has nn.Inception layer with 'load_lua'

### ISSUE THREAD

**Issue by kentkawai** [pytorch/pytorch#1038]
Hi,

Is there any way to load a torch network which has nn.Inception layer?
I used 'load_lua' function to load saved t7 file, but this yields error.

`torch.utils.serialization.read_lua_file.T7ReaderException: don't know how to deserialize Lua class nn.Inception. If you want to ignore this error and load this object as a dict, specify unknown_classes=True in reader's constructor`

**Comment by apaszke** [comment]
`nn.Inception` is not an official module, so we don't support it. You can reimplement in it Python and extract weights by loading the model with `unknown_classes=True` (as the error message says).
