### ISSUE TITLE
Add an option to `nn.Module.register_forward_hook`/`torch.nn.modules.module.register_module_forward_hook` that guarantees a Module forward (post) hook is always run

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/pytorch#103997]
### 🚀 The feature, motivation and pitch

[nn.Module forward hooks](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.register_forward_hook) are hooks that are run every time **after** `nn.Module.forward()` is run. There is also a [global registration nn.Module forward hook registration function](https://pytorch.org/docs/stable/generated/torch.nn.modules.module.register_module_forward_hook.html#torch.nn.modules.module.register_module_forward_hook)

There have been recent asks to add hooks that allow you to register a context manager to `nn.Module.forward()`.

Context managers have `__enter__` and `__exit__` methods defined.

One solution here is for users to 
1) register a [forward pre-hook](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.register_forward_hook) that contains the definitions of  `__init__` and `__enter__` of the context manager
2) register a [forward hook](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.register_forward_hook) that contains the definition of `__exit__` of the context manager

A gap with the above solution is that if `nn.Module.forward()` or something else before the post hook errors out, the forward (post) hook might not be called. In order to address this, we should add a new kwarg to `nn.Module.register_foward_hook` that **guarantees that the post hook will be run**, which ensures that the context will be properly exited.

In contrast to adding the ability to register a context manager hook to `nn.Module.forward`, this solution offers clearer granularity over the ordering of entering/exiting the context manager with other forward pre-hooks/forward hooks that are registered.

cc @albanD @mruberry @jbschlosser @walterddr

**Comment by soulitzer** [comment]
cc @rohan-varma @mrshenli

**Comment by yaroslavvb** [comment]
Happy about this change, looks like I can deprecate [autograd-lib](https://pypi.org/project/autograd-lib/) finally and use built-in functionality
