### ISSUE TITLE
L-BFGS crashes when first step fails tolerance check

### ISSUE THREAD

**Issue by jcjohnson** [pytorch/pytorch#1039]
Minimal test case:
https://gist.github.com/jcjohnson/7ee9124d45d09573b7e6282d5a8ba97a

Suppose that the first call to `step()` fails this tolerance check:

https://github.com/pytorch/pytorch/blob/master/torch/optim/lbfgs.py#L193

Then the next time `step()` is called, `state['n_iter']` will be 1 and `state['t']` will be `None`, so it will crash here:

https://github.com/pytorch/pytorch/blob/master/torch/optim/lbfgs.py#L138

I'm not 100% sure that this is the right thing to do, but I think that swapping these two blocks fixes the problem:

https://github.com/pytorch/pytorch/blob/master/torch/optim/lbfgs.py#L192
https://github.com/pytorch/pytorch/blob/master/torch/optim/lbfgs.py#L196

**Comment by soumith** [comment]
fixed in master.
