### ISSUE TITLE
How can I reference `torchvision` in sphinx?

### ISSUE THREAD

**Issue by themightyoarfish** [pytorch/pytorch#10400]
The `objects.inv` sphinx inventory for the `torch` package is hosted at [https://pytorch.org/docs/master/objects.inv](https://pytorch.org/docs/master/objects.inv), so the following works in `conf.py`:
```
intersphinx_mapping = {'python': ('https://docs.python.org/', None),
                        'torch': ('https://pytorch.org/docs/master/', None)}
```
However, a reference such as `torchvision.datasets` is met with a `reference target not found` warning by Sphinx. I tried using `'torchvision': ('https://pytorch.org/docs/master/', None)` as well, but that didn't help. What must be done?

**Comment by soumith** [comment]
you have to copy over torchvision rst files over, like here: https://github.com/pytorch/builder/blob/master/jenkins/pytorch/build_nimbix.sh#L344-L346
