### ISSUE TITLE
torch.compile drops Python thread_locals

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#104066]
### 🐛 Describe the bug

The following code:

```py
import threading
import torch._dynamo

FOO = threading.local()
FOO.x = torch.zeros(1)

@torch.compile(backend='aot_eager')
def f(x):
    assert isinstance(FOO.x, torch.Tensor) 
    return torch.cat([x, FOO.x])
inp = torch.ones(1)
f(inp)
```
raises
```
TorchRuntimeError: Failed running call_function <built-in method cat of type object at 0x7fb24554ae40>(*(
[FakeTensor(..., size=(1,)), None],), **{}):
expected Tensor as element 1 in argument 0, but got NoneType
```

It looks like FOO.x somehow becomes None when passed to torch.cat.

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

**Comment by kflu** [comment]
I also tried switching to contextvars, dynamo also don't work with contextvars


```
# TRY CONTEXTVARS
import contextvars
FOO = contextvars.ContextVar("kkk")
class Foo: pass
FOO = Foo()


FOO.x = torch.zeros(1)
def f(x):
    # thread local is lost during export
    assert FOO.x is not None
    return torch.cat([x, FOO.x])
inp = torch.ones(1)
f(inp)

torch._dynamo.export(f, inp)
```

> AssertionError: Dynamo input/output is not consistent with traced input/output

**Comment by zou3519** [comment]
The root cause looks like our handling for when `inspect.getattr_static` fails is wrong.
- [We try to `inspect.getattr_static` on the threading.local object](https://github.com/pytorch/pytorch/blob/afc788a99c1853e815283854ef6f168b250eaf2c/torch/_dynamo/variables/user_defined.py#L386)
- If this fails, [we set `subobj` to None](https://github.com/pytorch/pytorch/blob/afc788a99c1853e815283854ef6f168b250eaf2c/torch/_dynamo/variables/user_defined.py#L388)
- And then [we return ConstantVariable(None) as the result of getattr](https://github.com/pytorch/pytorch/blob/afc788a99c1853e815283854ef6f168b250eaf2c/torch/_dynamo/variables/user_defined.py#L436)

**Comment by bdhirsh** [comment]
round-robin assigning the dynamo error to @williamwen42 (feel free to un-assign if you don't have bandwidth)

**Comment by zou3519** [comment]
I'm a bit of a Dynamo noob, but, is the following the correct approach for this?
- create a ThreadLocalVariable to track threading.local()
- var_getattr on ThreadLocalVariable just returns getattr(thing, name). We know that it's safe to call this getattr (that it won't execute some more code that we need to introspect)

**Comment by kflu** [comment]
Richard and I tried to use contextvars (which is much more proper than thread local anyways), and it also seems to fail:

```
import torch._dynamo
import contextvars
FOO = contextvars.ContextVar("kkk")
FOO.set(1)

def f(x):
    return x + FOO.get()
inp = torch.ones(1)
f(inp)
torch._dynamo.export(f, inp)

# output:

Unsupported: call_method UserDefinedObjectVariable(ContextVar) get [] {}

from user code:
   File "<ipython-input-7-c3980f2f0cea>", line 7, in f
    return x + FOO.get()

```
