### ISSUE TITLE
loss function with if else statement

### ISSUE THREAD

**Issue by alicera** [pytorch/pytorch#104094]
### 📚 The doc issue

https://github.com/yang-ruixin/PyTorch-Image-Models-Multi-Label-Classification/blob/15a7fb12aae42a0ae42666274f8d41500079ab99/timm/models/multi_label_model.py

https://neptune.ai/blog/pytorch-loss-functions

There are 10 numbers, including 1,2,3,4,...10
I design the 
predict : [1,2]
target : [1,2]

here is the loss compute:
```
nums = 2
def compute_loss(predict, target, nums):
    loss_sum = 0
    for num in range(nums):
        pred = int(predict[0][num])
        if target[0][num] in [pred-1, pred, pred+1]:
            loss_sum += 0
        else:
            loss_sum += 1
    return loss_sum
```

But meet 
  File "train.py", line 144, in main
    loss.backward()
AttributeError: 'int' object has no attribute 'backward'

do you have the doc to processing if else loss and using custom value loss

**Comment by lezcano** [comment]
This is not a bug in PyTorch but bug in the code (the gradients are not being propagated to `target`). Consider posting this in https://discuss.pytorch.org/ to ask for help on how to use PyTorch effectively.
