### ISSUE TITLE
Error on printing non-contiguous tensors

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#10402]
## Issue description

`get_summarized_data` in `_tensor_str.py` crashes when (unintentionally) a non-contiguous `tensor` is printed. 
The `.view(-1)` call in [this line of code](https://github.com/pytorch/pytorch/blob/e9ad74357e43d90f773abe31de88bd5f61db23eb/torch/_tensor_str.py#L216) throws an error, as `view(-1)` cannot be called on an non-contiguous `tensor`.

## Code example

```python
import torch
import torch.nn as nn

batch_size = 10
channels = 3
h, w = 16, 16
x = torch.randn(batch_size, channels, h, w)

pool = nn.AvgPool2d((1, 2), (1, 2))
output = pool(x)
output = output.view(batch_size, channels, h//2, 2, w//2)
print(output.select(3, 1).mul_(-1))
```

This code snippet crashes in the last line. I've noticed this issue while working in the Spyder IDE (REPL), where the line of code is also printed without the explicit `print` statement.

## System Info

Noticed this in all versions `> 0.4.0`, i.e. `0.4.1` and `0.5.0a0+1a0f4b5`.
[This commit](https://github.com/pytorch/pytorch/commit/90e75c65286b3799ebfd4e69d1ce0890519e581f#diff-f4eb2d7bbb99a6ea648fcc476f38659eR200) seems to be related to this issue.

## Workaround

We could call `self = self.contiguous()` before the line in question.
If `self` is already contiguous, this should result in a no-op.

I'll create a PR with this fix.

**Comment by vishwakftw** [comment]
An alternative workaround would be to call `reshape(-1)` instead on `view(-1)`. IIRC `.contiguous().view(...)` is equivalent to `.reshape(...)`.

**Comment by ptrblck** [comment]
Would you prefer calling `reshape(-1)` for every `self[i]` for `start` and `end` or rather once `contiguous()` on `self`?

I've timed it with a quick script and the latter seems to be a bit faster:
```python
# reshape
x = torch.randn(2000, 40, 20)
x.is_contiguous()
y = x.permute(0, 2, 1)
y.is_contiguous()

t0 = time.perf_counter()
for i in range(y.size(0)):
    y[i].reshape(-1)
t1 = time.perf_counter()
print(t1 - t0)

# contiguous
x = torch.randn(2000, 40, 20)
x.is_contiguous()
y = x.permute(0, 2, 1)
y.is_contiguous()

t0 = time.perf_counter()
y = y.contiguous()
for i in range(y.size(0)):
    y[i].view(-1)
t1 = time.perf_counter()
print(t1 - t0)
```

**Comment by vishwakftw** [comment]
Oh I didn't notice the other `view(-1)`. Sorry about that.

**Comment by ptrblck** [comment]
I'll have to rebase again, as I accidentally pushed some other PR to my current master.

**Comment by SsnL** [comment]
@soumith I disagree. We should use `reshape`, but not on every slice, instead, we should do `self = self.reshape(self.size(0), -1)` and just use slice in the loop. `reshape` is nicer because it doesn't copy if the strides are compatible. E.g., considering tensor 
```
// can come from a_2x3x4_tensor[:, :, ::2]

sizes:   [2, 3, 2]
strides: [12, 4, 2]
```
Then `self.reshape(self.size(0), -1)` gives you a view with
```
sizes:   [2, 6]
strides: [12, 2]
```
but `contiguous` copies.

**Comment by colesbury** [comment]
We should avoid operations that may copy the whole tensor in printing code. At most the extra memory used should be proportional to the data that's actually printed.

Printing a big tensor shouldn't cause an OOM.

**Comment by ptrblck** [comment]
@SsnL As far as I understand from [your comment](https://github.com/pytorch/pytorch/pull/10405#discussion_r209359147) the way to go would be to `reshape` `start` and `end` `tensors`:
```python
[get_summarized_data(self[i]).reshape(-1) for i in ... ]
```
This could still copy `self[i]`, if it's non-contiguous, couldn't it?

**Comment by lantiga** [comment]
An alternate way would be to build an index tensor for just the elements that will be printed (typically not a lot) and then just use advanced indexing. This should avoid calls to ‘contiguous’ and extra allocations would be proportional to what’s actually being printed.

**Comment by vishwakftw** [comment]
Can this be closed now?
