### ISSUE TITLE
`Tensor.shape` not documented

### ISSUE THREAD

**Issue by albertz** [pytorch/pytorch#104038]
### 📚 The doc issue

I think this is a quite important attribute, or not? So I would expect that it is documented [here for the `Tensor` object](https://pytorch.org/docs/stable/tensors.html#torch.Tensor) and also maybe in the [Tensor Attributes list](https://pytorch.org/docs/stable/tensor_attributes.html)?

### Suggest a potential alternative/fix

Add some documentation on `Tensor.shape`.

cc @svekars @carljparker @albanD

**Comment by jbschlosser** [comment]
Sure, we'd accept a PR documenting it. `torch/_tensor_docs.py` seems like a good place.
