### ISSUE TITLE
Improve top level package description for MPS package

### ISSUE THREAD

**Issue by davidradl** [pytorch/pytorch#104183]
### 📚 The doc issue

I am new to PyTorch and found page [https://pytorch.org/docs/stable/mps.html](https://pytorch.org/docs/stable/mps.html) where it said "This package enables an interface for accessing MPS backend in python". I did not know what MPS stood for. I think the top level package for an area should expand the acronym and explain something about it.

### Suggest a potential alternative/fix

I suggest changing this section in https://github.com/pytorch/pytorch/blob/main/torch/mps/__init__.py to

`This package enables an interface for accessing MPS (Metal Performance Shaders) backend in Python. MPS is an acceleration backend for MacOS that utilizes GPU for computations.`

I am happy to make this change, if it is agreed upon.

cc @svekars @carljparker @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by davidradl** [comment]
I am just getting my CLA sorted out so the pr can proceed.

**Comment by davidradl** [comment]
The CLA is sorted out - waiting for approval.

**Comment by malfet** [comment]
Thank you very much for creating an issue and proposing a fix.
