### ISSUE TITLE
Network does not return any thing, not even None and breaks loops

### ISSUE THREAD

**Issue by Jakobhenningjensen** [pytorch/pytorch#104162]
### 🐛 Describe the bug

I just installed torch via `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`.

I have created a network 

```python
class NeuralNetwork(nn.Module):

    def __init__(self):
        super(NeuralNetwork, self).__init__()

    def forward(self, x):
        return x

```
and a training loop

```python

net = NeuralNetwork()
criterion = CrossEntropyLoss()
N_EPOCHS = 10

for e in range(N_EPOCHS):
    print(e)
    for x, y in dataLoader: # `dataLoader` is a DataLoader object
        logit = net(x)

        loss = criterion(logit, y)
        optimizer.zero_grad()

        loss.backward()

        optimizer.step()
```

Running the code only prints "0" but no error is thrown.
I have narrowed it down to it being the `net(x)` call.

If I do a short test

```python
net = NeuralNetwork()#.to(device)
x = torch.rand(1, 28, 28)
net(x)
```
then the last `net(x)` does return anything.

Doing 

```python
a = net(x)
print(a)
```
results in `no variable named "a"`

### Versions

PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA RTX A3000 Laptop GPU
Nvidia driver version: 531.14
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2611
DeviceID=CPU0
Family=207
L2CacheSize=10240
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2611
Name=11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.1+cu117
[pip3] torchaudio==2.0.2+cu117
[pip3] torchvision==0.15.2+cu117
[conda] Could not collect

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by ZailiWang** [comment]
Hi, did you run the script on CPU or GPU? I didn't re-produce the issue on Win11 PT 2.0.1 CPU release.

**Comment by Jakobhenningjensen** [comment]
I have tried on both GPU and CPU.
Agreed, it is very strange that nothing (not even None) is produced. I can even debug and step through the `forward` function without any errors, but the issue still occurs

**Comment by Jakobhenningjensen** [comment]
I have repaired python, and I get results when using the CPU.
Using the GPU the issue still persists

**Comment by malfet** [comment]
@Jakobhenningjensen can you please elaborate, how did you repaired Python on your system?

**Comment by Jakobhenningjensen** [comment]
> @Jakobhenningjensen can you please elaborate, how did you repaired Python on your system?
> 

I just ran python311.exe and chose "repair".

**Comment by alinpahontu2912** [comment]
Hey @Jakobhenningjensen have you tried running the code with the latest pytorch release ? Is it still happening ?

**Comment by alinpahontu2912** [comment]
I am closing this issue because o flack of activity, please feel free to open a new one if needed.
