### ISSUE TITLE
Re-enable `test_typing`

### ISSUE THREAD

**Issue by lkct** [pytorch/pytorch#104119]
### 🚀 The feature, motivation and pitch

Further to the discussion in #103376 and OH, we need some tests for static type checking with `reveal_type` on `Tensor` methods.

However, `test_typing` is currently in the blocklist and is broken, confirmed in https://github.com/pytorch/pytorch/issues/103376#issuecomment-1595010512 (cc @ezyang @malfet @rgommers @xuzhao9 @gramster @seemethere @pytorch/pytorch-dev-infra @huydhn).

My plan is to to re-enable it, and then in #103376 I can add some more reveal tests.

### Alternatives

Create a new test for #103376, but it will include a lot of code duplication with the existing `test_typing`.

### Additional context

`test_typing` is added to the blocklist when the blocklist is introduced in #64246 c5d80e41b0271163aa1900c002dbf5d430c4b953. I'm not sure why it was blocked. If it's because it was broken, I can fix it (actually very easy); if it's because it was slow (can take 5~10 mins w/o cache), we will anyway need to spend that time for the reveal test; if it's other reasons, please tell me. (cc @malfet as the commit author).

**Comment by lkct** [comment]
Two problems, which are relevant no matter we're reviving `test_typing` or starting a new test (cc @malfet):

- [`mypy.ini`](https://github.com/pytorch/pytorch/blob/main/mypy.ini) loads the numpy plugin for mypy, which is introduced into numpy in 1.21. However, some CI tests are using numpy==1.20.3 which I assume is bundled in the docker image.
  - We need to decide whether to stick to `mypy.ini`. The plugins can only be specified through a config file, and cannot be overridden through command line.
  - Related error logs: https://github.com/pytorch/pytorch/actions/runs/5360904925/jobs/9726512984
- mypy breaks on CI runs with Python 3.10 and 3.11, warning `Positional-only parameters are only supported in Python 3.8 and greater`.
  - This is a known issue with mypy==0.960 (which we are using) and fixed in a future version. Ref: python/mypy#13627
  - Related error logs: https://github.com/pytorch/pytorch/actions/runs/5360904925/jobs/9726508624

---

> (can take 5~10 mins w/o cache)

Seems I overestimated. Normally should finish in 2-3 mins, and the cache can save 1-2. There may be some problems with my local setup, and `python test/run_test.py -i test_typing` can take an unbearable time while `python test/test_typing.py` is normal.

**Comment by ezyang** [comment]
Let's just upgrade numpy and mypy. Is the fixed mypy version released yet? We may have to wait until then.

**Comment by clee2000** [comment]
This was reenabled about a year ago
