### ISSUE TITLE
how to optimize torch.argwhere?

### ISSUE THREAD

**Issue by Soikie** [pytorch/pytorch#104159]
`t0 = time.time()
xx = torch.argwhere(x)  ## x.shape = (15120,150) x.device = cuda:0 and the gpu is gtx1050
print(time.time() - t0)`

the output is always near 0.15s,how can i reduce the cost time ? or there is other high efficient methods to replace argwhere? 

cc @albanD

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

For your particular question, you are missing proper synchronization with the GPU for time.time() to be accurate so I am not sure if these numbers are important.

Also in general, functions like argwhere/nonzero/etc that return indices are not very efficient and the best thing to do is not use them. In particular things like masking can be good ways around that.
If you give details about what you're trying to achieve on the forum, I'm sure someone will be able to help you.
