### ISSUE TITLE
Stop zeroing out non-differentiable outputs in AOTAutograd

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#104272]
### 🚀 The feature, motivation and pitch

Today, we create zero tensors for non-differentiable outputs in `autograd.Function`. Also see https://github.com/pytorch/pytorch/pull/98659#issuecomment-1518201753 

```
import torch
import torch._dynamo
from torch.utils._pytree import tree_map

torch.set_default_device('cuda')

def bench(f, name=None, iters=100, warmup=5, display=True, profile=False):
    import time
    from triton.testing import do_bench

    for _ in range(warmup):
        f()
    if profile:
        with torch.profiler.profile() as prof:
            f()
        prof.export_chrome_trace(f"{name if name is not None else 'trace'}.json")

    us_per_iter = do_bench(lambda: f())*1000

    if name is None:
        res = us_per_iter
    else:
        res= f"{name}: {us_per_iter:.3f}us"

    if display:
        print(res)
    return res

@torch.compile
def f(x):
    return x * 2, (x * 3).detach()

inp = torch.randn(2**20, device='cuda', requires_grad=True)
bench(lambda: f(inp)[0].sum().backward(), profile=True)
```
<img width="673" alt="image" src="https://github.com/pytorch/pytorch/assets/6355099/f8beef63-03e7-4b9f-a792-215d5ed35478">

cc @ezyang @gchanan @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
Let's do this!

**Comment by Chillee** [comment]
@soulitzer This isn't actually turned on yet in AOTAutograd right?

**Comment by soulitzer** [comment]
Whoops no, yeah this should be open

**Comment by kbadz-pl** [comment]
@soulitzer @Chillee I would like to test this feature - is there a way to enable it?

**Comment by soulitzer** [comment]
@kbadz-pl  Not yet, but we'd accept a PR for this. We recently added a private autograd Function setting that would help with this. https://github.com/pytorch/pytorch/pull/104291

**Comment by bdhirsh** [comment]
hmm @albanD, why is this BC-breaking? (Assuming we only do this for AOTAutograd)

**Comment by soulitzer** [comment]
Initial proposal was to modify an existing custom Function API, but we decided to add a new private API instead, so this should no longer be bc-breaking.

**Comment by Chillee** [comment]
Resolved by https://github.com/pytorch/pytorch/pull/110721
