### ISSUE TITLE
getattr on `__slots__` object potentially suspicious

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#104289]
### 🐛 Describe the bug

@jansel pointed out that https://github.com/pytorch/pytorch/blob/afc788a99c1853e815283854ef6f168b250eaf2c/torch/_dynamo/variables/user_defined.py#L367 looked suspicious. The check should be something like ("if the object has slots AND no custom getattr, then we know how to handle it. Otherwise, the getattr may be unsafe").

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by davidberard98** [comment]
round-robin assigned to @mlazos

**Comment by mlazos** [comment]
Tried this out in #121879, and it induces a lot of failures. I think we don't support getattr_static with slots even without a custom getattr.
