### ISSUE TITLE
RuntimeError "sizes must be non-negative" (0.4.1)

### ISSUE THREAD

**Issue by evanfeinberg** [pytorch/pytorch#10424]
In the transition from PyTorch 0.3.1 --> 0.4.1, we noticed the following error. When initializing a tensor beginning with a dimension of size -1 (to account for inconsistent batch sizes), the following error is thrown:

`RuntimeError: sizes must be non-negative`

Simple reproducing example...
`x = torch.FloatTensor(-1,2)`
`x_batch = torch.FloatTensor([[0., 1.], [2., 3.]])`
`x.resize_as_(x_batch).copy_(x_batch)`
`x_var = Variable(x)`

(even just the first line will reproduce it)

This was not the case in PyTorch <= 0.3.1. 

We successfully resolved the issue by simply replacing "-1" with "0", though thought we should report this in case the change should be made clearer in documentation or if other PyTorch users upgrade to 0.4, run into this error, and are seeking a solution.

Regardless of this relatively minor issue, thanks for all your incredible work on PyTorch and for the community for being so active and responsive around it.

**Comment by ezyang** [comment]
Thanks for the report. I don't think -1 size dimension was ever supposed to work in the Tensor constructor, and we'd prefer to give an error in this case. Should be easy enough for people to fix, if they notice it :)

**Comment by evanfeinberg** [comment]
Sounds good, thanks @ezyang !

**Comment by fmassa** [comment]
This is probably an issue with your input image size. Inception excerpts images of size 299

**Comment by george-studenko** [comment]
Thanks @fmassa you are right!, 

I had images at 224,  changing it to 299 did the trick, had to fix another known issue (aux_logits=False) and now it is training!

**Comment by Sphinxs** [comment]
If normalization it's applied, is it impossible to use Inception V3 ?
