### ISSUE TITLE
Merge requests have been timing out for the past week

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#104205]
Examples: https://github.com/pytorch/pytorch/pull/104138#issuecomment-1608266572 and https://github.com/pytorch/pytorch/pull/97223#issuecomment-1608166596 

cc @kit1980 who suggested opening this issue.

**Comment by malfet** [comment]
Looks like a github hiccup/issue to me, as of this moment it claims that https://github.com/pytorch/pytorch/pull/104138 still have 8 pending workflows, among them https://github.com/pytorch/pytorch/actions/runs/5374627162/jobs/9750401595?pr=104138 which started 15 hours ago:
<img width="1334" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/81ec5fe5-cff5-4fbe-988f-591075ce83f5">
