### ISSUE TITLE
[ONNX] Decompose private ops before handing over to ONNX

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#104257]
Private ops like `aten::_embedding_bag`, `aten::_unsafe_index` and `aten::_fft_c2c` (seen from the bench) are better decomposed to public aten/prims ops before dispatching.

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @SherlockNoMad

**Comment by BowenBao** [comment]
I don't feel this is ONNX specific, unless these ops already have decomp.

**Comment by BowenBao** [comment]
```python
import torch
import torch._decomp

for decomp_type in ["pre_autograd", "post_autograd"]:
    decomps = torch._decomp.get_decompositions(
        [
            torch.ops.aten._embedding_bag,
            torch.ops.aten._unsafe_index,
            torch.ops.aten._fft_c2c,
        ],
        type=decomp_type,
    )

    print(f"decomps: {decomps} for type: {decomp_type}")
```
```
decomps: {} for type: pre_autograd
decomps: {} for type: post_autograd
```
Guess this means they don't have decomp. (What is "pre_autograd" vs "post_autograd"?)

**Comment by BowenBao** [comment]
Found https://github.com/pytorch/pytorch/issues/76514 related.

**Comment by ezyang** [comment]
pre autograd means we run the decomp before running autograd (e.g., we would differentiate the decomposition). Post autograd decomps don't need to be differentiable.
