### ISSUE TITLE
Revisit pytorchbot logic when reverting PRs exported from internal diffs

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#104232]
### 🐛 Describe the bug

This issue has been raised several times by our oncall where a PR exported from an internal diff could not be reverted if the diff is not yet landed, for example https://github.com/pytorch/pytorch/pull/100652.  Oncall should be able to revert the PR in this case. 

### Versions

PyTorch bot

cc @ZainRizvi @kit1980 @clee2000 @malfet

**Comment by clee2000** [comment]
I think there was a recent regression

**Comment by ZainRizvi** [comment]
Please add instructions on how to work around this to our runbook or build it into tooling

**Comment by huydhn** [comment]
Update the runbook at https://docs.google.com/document/d/1JBWlm9Aa1jBpaRW3xvHgyTBlmT_8lxH5BpCtJNOjajE
