### ISSUE TITLE
`index_put_` Internal Assert Failed

### ISSUE THREAD

**Issue by JulianKnodt** [pytorch/pytorch#104217]
### 🐛 Describe the bug

![image](https://github.com/pytorch/pytorch/assets/7675847/a218bd38-63fa-40f1-9179-430428ec847e)
![image](https://github.com/pytorch/pytorch/assets/7675847/58fadce6-a943-40b3-a5c2-1e70639d6110)

The issue is that the source tensor has 4 dimensions (B x W x H x C), with the last dimension C of size 4, and the output is a tensor that is a float (Shape = [1]). I expected the output to automatically be broadcasted to the right size, but it seems this was not accounted for.

Also, I would expect that index put would allow for specific dimensions to be accumulated into it, instead of currently requiring all dimensions to be set and match exactly with input and output.

### Versions
<summary>
<details>
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.24.4
Libc version: glibc-2.35

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 531.14
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          64
On-line CPU(s) list:             0-63
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen Threadripper 3970X 32-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        7386.15
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload umip rdpid
Virtualization:                  AMD-V
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       1 MiB (32 instances)
L1i cache:                       1 MiB (32 instances)
L2 cache:                        16 MiB (32 instances)
L3 cache:                        16 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] img2vec-pytorch==1.0.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] pytorch-lightning==1.4.2
[pip3] pytorch-msssim==0.2.1
[pip3] pytorch3d==0.7.4
[pip3] torch==1.13.1
[pip3] torchmetrics==0.6.0
[pip3] torchvision==0.14.1
[conda] Could not collect
</details
</summary>

**Comment by lezcano** [comment]
You may want to do `value[(z,v,u) += out_latents`

**Comment by JulianKnodt** [comment]
Ah I specifically used `index_put` because there were repeated indices, and accumulate I believe makes it correct.
I found that indexing with `+=` does not lead to the output I expected.

**Comment by lezcano** [comment]
You are completely right. In that case, you'll need to perform the broadcasting manually yourself via `unsqueeze`s and `expand`s.

**Comment by JulianKnodt** [comment]
What do you mean by that? Do you mean for index put?

**Comment by lezcano** [comment]
My point is that you can implement broadcasting yourself by reshaping the tensors manually. Can you provide a minimal self-contained repro of the issue?

**Comment by JulianKnodt** [comment]
It seems to only repro on cuda:
```
import torch
a = torch.randn(1,32,32,4)
z = torch.tensor([0])
b = torch.randn(33,1)
idx0 = torch.randint(32, (33,))
idx1 = torch.randint(32, (33,))

# note: accumulate is necessary
# note all the cudas are necessary
a.cuda().index_put_((z.cuda(), idx0.cuda(), idx1.cuda()), b.cuda(), accumulate=True).shape
```

**Comment by lezcano** [comment]
A workaround: you can just `torch.compile` it
```python
import torch
a = torch.randn(1, 32, 32, 4, device="cuda")
z = torch.tensor([0], device="cuda")
b = torch.randn(33, 1, device="cuda")
idx0 = torch.randint(32, (33,), device="cuda")
idx1 = torch.randint(32, (33,), device="cuda")

@torch.compile
def f(a, z, b, idx0, idx1):
    a.index_put_((z, idx0, idx1), b, accumulate=True)

f(a, z, b, idx0, idx1)
```

**Comment by JulianKnodt** [comment]
I've found a fix for my specific use case, so there's no worries for me to find a workaround.
But since it's an internal error I thought it would be good to report it.
Altho I feel this specific case seems a bit rare, I've never seen any code use index_put 🤪

**Comment by lezcano** [comment]
The internal error should just be upgraded to a nicer error, it's just that htat code is fairly old. Closing for now as this is expected and torch.compile also offers a workaround.

**Comment by JulianKnodt** [comment]
I don't believe this should be closed, as when running without cuda, it works fine. Therefore, I'd either expect it to be a consistent error for all cases or there to be no error.

**Comment by lezcano** [comment]
Left open. Could you please improve the OP and the title of the issue then?

**Comment by lezcano** [comment]
In fact, this is a duplicate of https://github.com/pytorch/pytorch/issues/93248, which, in turn, is a duplicate of https://github.com/pytorch/pytorch/issues/79987
