### ISSUE TITLE
UnsupportedOperatorError: Exporting the operator 'aten::erfc' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

### ISSUE THREAD

**Issue by YI-MAX-YAN** [pytorch/pytorch#104392]
### 🐛 Describe the bug

I want to run a .pth model to .oxnn. This my code.
```
state_dict = load_state_dict(torch.load(paths))
model_cls = TestModel()
model = model_cls.from_state_dict(state_dict).eval()
opset_version = 18
onnx_file_name = paths.split('.')[0]
dummy_input = torch.rand(1, 3, 512, 768) 
torch.onnx.export(model, 
                  dummy_input, 
                   #onnx_file_name+".onnx",
                  opset_version=opset_version)
```
It occurs this error' #UnsupportedOperatorError: Exporting the operator 'aten::erfc' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.'
Then, I search this problem(https://github.com/pytorch/pytorch/issues/97262) and write the Custom operators.
```
opset_version = 18
custom_opset = onnxscript.values.Opset(domain="torch.onnx", version=1)
@onnxscript.script(custom_opset)
def erfc(x):
    y = 1-op.erf(x)
    return y  

def custom_erfc(g: jit_utils.GraphContext, x):
    return g.onnxscript_op(erfc).setType(x.type())

torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::erfc",
    symbolic_fn=custom_erfc,
    opset_version=opset_version,
) 
```
```
======= Diagnostic Run torch.onnx.export version 2.1.0.dev20230628+cu118 =======
verbose: False, log level: 40
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "/home/yisy/anaconda3/envs/pytorchnightly/lib/python3.10/site-packages/torch/onnx/utils.py", line 1655, in _export
    _C._check_onnx_proto(proto)
RuntimeError: No Op registered for erf with domain_version of 18

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yisy/Documents/pth2onnx/pth2onxx.py", line 53, in <module>
    write_onxx_model(model, paths)
  File "/home/yisy/Documents/pth2onnx/pth2onxx.py", line 40, in write_onxx_model
    torch.onnx.export(model, 
  File "/home/yisy/anaconda3/envs/pytorchnightly/lib/python3.10/site-packages/torch/onnx/utils.py", line 507, in export
    _export(
  File "/home/yisy/anaconda3/envs/pytorchnightly/lib/python3.10/site-packages/torch/onnx/utils.py", line 1657, in _export
    raise errors.CheckerError(e) from e
torch.onnx.errors.CheckerError: No Op registered for erf with domain_version of 18
```

### Versions

pytorch 2.1.0(nightly)
python 3.10

**Comment by YI-MAX-YAN** [comment]
opset_version = 18
custom_opset = onnxscript.values.Opset(domain="torch.onnx", version=1)
@onnxscript.script(custom_opset)
def erfc(x):
    y = 1 - op.Erf(x)
    return y @ x

def custom_erfc(g: jit_utils.GraphContext, x):
    return g.onnxscript_op(erfc).setType(x.type())

torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::erfc",
    symbolic_fn=custom_erfc,
    opset_version=opset_version,
)

**Comment by YI-MAX-YAN** [comment]
`opset_version = 18
custom_opset = onnxscript.values.Opset(domain="torch.onnx", version=1)
@onnxscript.script(custom_opset)
def erfc(x):
    y = 1 - op.Erf(x)
    return y @ x

def custom_erfc(g: jit_utils.GraphContext, x):
    return g.onnxscript_op(erfc).setType(x.type())

torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::erfc",
    symbolic_fn=custom_erfc,
    opset_version=opset_version,
) ` Fix this problem

**Comment by YI-MAX-YAN** [comment]
```
opset_version = 18
custom_opset = onnxscript.values.Opset(domain="torch.onnx", version=1)
@onnxscript.script(custom_opset)
def erfc(x):
y = 1 - op.Erf(x)
return y @ x

def custom_erfc(g: jit_utils.GraphContext, x):
return g.onnxscript_op(erfc).setType(x.type())

torch.onnx.register_custom_op_symbolic(
symbolic_name="aten::erfc",
symbolic_fn=custom_erfc,
opset_version=opset_version,
)
```
Fix this problem

**Comment by lcmlzh** [comment]
> ```
> opset_version = 18
> custom_opset = onnxscript.values.Opset(domain="torch.onnx", version=1)
> @onnxscript.script(custom_opset)
> def erfc(x):
>     y=op.Sub(1, op.Erf(x))
>     return y
> 
> def custom_erfc(g: jit_utils.GraphContext, x):
> return g.onnxscript_op(erfc).setType(x.type())
> 
> torch.onnx.register_custom_op_symbolic(
> symbolic_name="aten::erfc",
> symbolic_fn=custom_erfc,
> opset_version=opset_version,
> )
> ```
> 
> Fix this problem

When I used the above program, I was able to successfully export the onnx model, but when I used the model to reason, the following error occurred：

failed:Node (/gaussian_conditional/erfc) Op (erfc) [ShapeInferenceError] Inference error(s): (op_type:Erf, node name: n1): [TypeInferenceError] Input 0 expected to have type but instead is null.

Have you encountered any related problems? Thank you for your help.

**Comment by ZhangYuef** [comment]
> > ```
> > opset_version = 18
> > custom_opset = onnxscript.values.Opset(domain="torch.onnx", version=1)
> > @onnxscript.script(custom_opset)
> > def erfc(x):
> >     y=op.Sub(1, op.Erf(x))
> >     return y
> > 
> > def custom_erfc(g: jit_utils.GraphContext, x):
> > return g.onnxscript_op(erfc).setType(x.type())
> > 
> > torch.onnx.register_custom_op_symbolic(
> > symbolic_name="aten::erfc",
> > symbolic_fn=custom_erfc,
> > opset_version=opset_version,
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Fix this problem
> 
> When I used the above program, I was able to successfully export the onnx model, but when I used the model to reason, the following error occurred：
> 
> failed:Node (/gaussian_conditional/erfc) Op (erfc) [ShapeInferenceError] Inference error(s): (op_type:Erf, node name: n1): [TypeInferenceError] Input 0 expected to have type but instead is null.
> 
> Have you encountered any related problems? Thank you for your help.

@lcmlzh I met the same problem. This is my inference code:
```
onnx_model = onnx.load("cheng2020.onnx")
onnx_model_graph = onnx_model.graph
onnx_session = onnxruntime.InferenceSession(onnx_model.SerializeToString())

input_shape = (1, 3, 500, 500)
x = torch.randn(input_shape).numpy()
onnx_output = onnx_session.run("output")
```

Error results:
```
---------------------------------------------------------------------------
Fail                                      Traceback (most recent call last)
[<ipython-input-26-a6e0883fac8e>](https://localhost:8080/#) in <cell line: 3>()
      1 onnx_model = onnx.load("cheng2020.onnx")
      2 onnx_model_graph = onnx_model.graph
----> 3 onnx_session = onnxruntime.InferenceSession(onnx_model.SerializeToString())
      4 
      5 input_shape = (1, 3, 500, 500)

1 frames
[/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py](https://localhost:8080/#) in _create_inference_session(self, providers, provider_options, disabled_optimizers)
    472             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    473         else:
--> 474             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
    475 
    476         if disabled_optimizers is None:

Fail: [ONNXRuntimeError] : 1 : FAIL : Node (/gaussian_conditional/erfc) Op (erfc) [ShapeInferenceError] Inference error(s): (op_type:Erf, node name: n1): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:CastLike, node name: n2): [TypeInferenceError] Input 1 expected to have type but instead is null
(op_type:Sub, node name: n3): [TypeInferenceError] Input 0 expected to have type but instead is null
```
