### ISSUE TITLE
[ONNX] Incorrect export of aten::slice()

### ISSUE THREAD

**Issue by ilyasher** [pytorch/pytorch#104314]
### 🐛 Describe the bug

The ONNX exporter incorrectly exports the following model:

```python
import torch

class SliceModel(torch.nn.Module):
    def forward(self, data, start, end):
        return data[:, :, start:end]

data = torch.randn((1,40,41))

# Index using 1D tensors
start_index = torch.tensor([36], dtype=torch.int64)
end_index = torch.tensor([41], dtype=torch.int64)

# Using this instead works.
# start_index = torch.tensor(36, dtype=torch.int64)
# end_index = torch.tensor(41, dtype=torch.int64)

model = SliceModel()
print("Forward function succeeds: ", model(data, start_index, end_index).shape)

# Exported model fails with Onnx Runtime
torch.onnx.export(model, (data, start_index, end_index), "slice.onnx", opset_version=18,)
```

The model runs fine in pytorch, but ONNXRuntime gives the following error:

`[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'/Slice' Status Message: slice.cc:193 FillVectorsFromInput Starts must be a 1-D array`

The produced model is correct if I change `start_index` and `end_index` to be 0-D tensors instead of 1D.

### Versions

PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A5000

**Comment by BowenBao** [comment]
Tricky advanced indexing.

cc @thiagocrepaldi this is an issue with dynamo as well, and frankly doesn't seem like will ever get supported.
datapoint: `torch._dynamo.exc.Unsupported: Dynamic slicing on data-dependent value is not supported`
with
```
onnx.save(torch.onnx.dynamo_export(model, data, start_index, end_index).model_proto, "slice.onnx")
```

**Comment by ilyasher** [comment]
Not sure about dynamo, but I just filed a PR to fix this issue in `torch.onnx.export`
