### ISSUE TITLE
Problems of exposing const char * field in struct ncclConfig_t 

### ISSUE THREAD

**Issue by ehuaa** [pytorch/pytorch#104340]
### 🐛 Describe the bug

In https://github.com/pytorch/pytorch/pull/97394 , a user can tune the parameters of ncclConfig_t. While ncclConfig_t has a const char * field called netName 
![image](https://github.com/pytorch/pytorch/assets/5137359/ccca8f60-98ef-4275-ab0c-e120e39cfab5)

when we assign net_name with code below: eg. **nccl_options.config.net_name = "IB"**, this field turned out to be an unreadable code. such as 
![image](https://github.com/pytorch/pytorch/assets/5137359/b90fd767-15f4-4729-bed3-2c2a485f904d)
which i supposed it to be IB.  
Is the wrong transition between char * and string cause this error, and how can i fix it to assign the net_name correctly, thanks!

### Versions

Name: torch
Version: 2.1.0a0+git7cef719

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by ehuaa** [comment]
@kwen2501 @syed-ahmed

**Comment by syed-ahmed** [comment]
@ehuaa apologies for the late reply. I'll fix this.
