### ISSUE TITLE
[feature request] torch.roll like numpy.roll

### ISSUE THREAD

**Issue by mariosfourn** [pytorch/pytorch#10434]
## Feature Request

Apply numpy-like array manipulation routines for torch tensors. In particular:

flip(m, axis)   | Reverse the order of elements in an array along the given axis.
fliplr(m) |         Flip array in the left/right direction.
flipud(m) |        Flip array in the up/down direction.
roll(a, shift[, axis]) | Roll array elements along a given axis.
rot90(m[, k, axes]) | Rotate an array by 90 degrees in the plane specified by axes.

**Comment by vishwakftw** [comment]
`flip` is available from `0.4.1`, and `rot90` is in the works (@weiyangfb). I think `fliplr` and `flipud` are special cases of `flip`.

**Comment by mariosfourn** [comment]
Thanks, I didn't realise it was added. How about `roll`?

**Comment by vishwakftw** [comment]
`roll` has not been added yet, as far as I know.

**Comment by zou3519** [comment]
@mariosfourn we will work on it. I probably won't work on it but I am assigning the task to myself right now to reserve it.

**Comment by upriser7** [comment]
@zou3519 I'm new to Pytorch and I'd like to contribute, can I take this on?

**Comment by zou3519** [comment]
Sorry @upriser7, I assigned this task to someone already :(. Please feel free to pick other tasks from our issues list! (and tag me/someone else to verify that the task is beginner friendly)

**Comment by zou3519** [comment]
Closed by @nairbv in #13261
