### ISSUE TITLE
Behaviour of `ScriptModule.save()`'s `f` parameter is undocumented

### ISSUE THREAD

**Issue by fish-face** [pytorch/pytorch#104359]
The following docstring: https://github.com/pytorch/pytorch/blob/044a8e3305bdff28780cdab757b859abf2fc76d9/torch/jit/_script.py#L711 implies the method works the same as `torch.jit.save`, but it does not: the latter accepts a file-like object, whilst the former silently converts any object to a string and treats it as a path. This should be fixed or documented.

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by kit1980** [comment]
Please fill free to send a PR to fix this.

**Comment by Anish7575** [comment]
Hi, I would like to fix this, but what's the preferred solution. Is it to change the argument type to file-type object or should we make sure the description of arguments is updated ?

**Comment by davidradl** [comment]
@fish-face  @Anish7575  I have had a quick look at this. I think the save() method that you are referring to is the implementation of torch.jit.save. There is no other save function in this file and this file is for jit only. This is not torch.save() which you rightly say takes different parameters. I think the docs are correct as-is. Am I missing something?

**Comment by fish-face** [comment]
I think so: `torch.jit.save` (not `torch.save()`) works fine with a
file-like object, but this method doesn't.

**Comment by Anish7575** [comment]
https://github.com/pytorch/pytorch/blob/044a8e3305bdff28780cdab757b859abf2fc76d9/torch/jit/_serialization.py#L18
This has the torch.jit.save function implementation, in which we are saving the file-object directly, where as the function shown in the issue saves the file path as string. Also can someone explain the difference between these two functions ?

**Comment by davidradl** [comment]
@fish-face 

So the original reported problem is in class `RecursiveScriptModule` . It seems like all the functions just do a passthrough of the arguments in a generic way. But the documentation may be more specific. Are you saying that a test shows this not working?

**Comment by Anubhab2003** [comment]
Can You Explain whats is all about?

**Comment by davidradl** [comment]
@Anubhab2003 , the way I am seeing this (@fish-face let me know if you disagree).

There are some functions defines in RecusiveScriptModule. This module appears to be a facade for the real c++ functions, so it just calls the underlying functions in most cases. The reported issue is 
```
   def save(self, f, **kwargs):
            r"""
            save(f, _extra_files={})

            See :func:`torch.jit.save <torch.jit.save>` for details.
            """
            return self._c.save(str(f), **kwargs)
```

so the function prototype (`**kwargs` )mismatches the documentation which is more specific with the `_extra_files`.

I think the `**kwargs` is just an easy way to pass down generic parameters to an underlying method. This seems reasonable as it means we do not need to keep the prototypes of the functions corresponding with the underlying functions (the docs for the functions do match the underlying C implementation of the function).

So the question is, is it worth changing the prototype from  **kwargs to the specific arguments for each method. Personally I think if the existing style works then do not change it. I guess the only advantage might be that if the caller sent in arguments that did not match the underlying function prototype then this would be caught at the python layer and might give a more informative error.

**Comment by JaredLevi18** [comment]
I sent a PR, hope it helps to solve the issue.
