### ISSUE TITLE
Accessing grad_fn throws when re-executing a loaded script module

### ISSUE THREAD

**Issue by lantiga** [pytorch/pytorch#10433]
## Issue description

Exporting a traced model, importing it back, running it on some input and printing the output fails with 
```
TypeError: Don't know how to create Python object for N5torch3jit12_GLOBAL__N_129ExecutionPlanAutogradFunctionE
```

### Exporting a traced model

```
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

model = Model()
x = torch.zeros(1)
trace = torch.jit.trace(x)(model)
trace.save('foobar.pt')
```

### Importing the traced model

```
import torch
model = torch.jit.load('foobar.pt')
x = torch.zeros(1)
z = model(x)
print(z)
```
produces
```
Traceback (most recent call last):
  File "run_model_new.py", line 10, in <module>
    print(z)
  File "/Users/lantiga/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/tensor.py", line 60, in __repr__
    return torch._tensor_str._str(self)
  File "/Users/lantiga/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/_tensor_str.py", line 259, in _str
    if self.grad_fn is not None:
TypeError: Don't know how to create Python object for N5torch3jit12_GLOBAL__N_129ExecutionPlanAutogradFunctionE
```
In fact, just accessing `z.grad_fn` outside the print statement triggers the exception.

The exception doesn't show up if the imported model is run in a `torch.no_grad()` context:
```
import torch
model = torch.jit.load('foobar.pt')
x = torch.zeros(1)
with torch.no_grad():
    z = model(x)
print(z)
```
In this case, accessing `z.grad_fn` correctly returns `None`.

## System Info
PyTorch version: 0.5.0a0+ab6afc2
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.9.4

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

**Comment by lantiga** [comment]
Basically, `ExecutionPlanAutogradFunction` is set as `grad_fn` in `ExecutionPlan::runWithGrad` https://github.com/pytorch/pytorch/blob/29406a2c4c36d3c155abed16cf75f26af44426d4/torch/csrc/jit/graph_executor.cpp#L173-L175

However, `ExecutionPlanAutogradFunction` is never registered through `registerCppFunction`, which triggers the exception in `functionToPyObject` https://github.com/pytorch/pytorch/blob/86eeeab7587ec5ae4f77c57daf681eef26ed5209/torch/csrc/autograd/python_cpp_function.cpp#L203-L207

The question is, should it be registered, or should we instead treat this case specially in `THPVariable_get_grad_fn`? https://github.com/pytorch/pytorch/blob/aa7af94656a9361224e6d24f9ca922bf5b3f5a67/torch/csrc/autograd/python_variable.cpp#L171-L180

**Comment by zdevito** [comment]
Pretty sure this issue has been addressed. Reopen if I am mistaken.
