### ISSUE TITLE
Error message when mean(0) on empty cuda tensor is misleading

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#10449]
## Issue description

CUDA Tensor seems not to check the shape of tensor in mean() function. `torch.tensor([]).cuda().mean(0)` should throw "invalid dimension 0" not to mislead.

## Code example

When I do this on CPU:
```
>>> torch.tensor([]).mean(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: invalid argument 2: invalid dimension 0 at /Users/qbx2/pytorch/aten/src/TH/generic/THTensorMath.c:3897
```

### When I do this on GPU:
```
>>> torch.tensor([]).cuda().mean(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: invalid argument 2: out of range at /Users/qbx2/pytorch/aten/src/THC/generic/THCTensor.c:23
```

### Without specifying dimension:
```
>>> torch.tensor([]).cuda().mean()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: invalid argument 1: empty Tensor at /Users/qbx2/pytorch/aten/src/THC/generic/THCTensorMathReduce.cu:305
```

## System Info
PyTorch version: 0.4.0a0+3749c58
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: V9.2.148
GPU models and configuration: GT 750M
Nvidia driver version: 387.10.10.10.40.105 (Up to date)
cuDNN version: Probably one of the following:
/usr/local/cuda/lib/libcudnn.7.dylib
/usr/local/cuda/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.13.3)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.0a0+3749c58)
[conda] torch                     0.4.0a0+3749c58           <pip>

**Comment by zou3519** [comment]
cc @gchanan

**Comment by gchanan** [comment]
This has been fixed on master, see below:
```
In [1]: import torch

In [2]: torch.cuda.is_available()
Out[2]: True

In [3]: torch.tensor([]).mean(0)
Out[3]: tensor(nan)

In [4]: import numpy as np

In [5]: np.array([]).mean(0)
/data/users/gchanan/anaconda3/bin/ipython:1: RuntimeWarning: Mean of empty slice.
  #!/data/users/gchanan/anaconda3/bin/python
/data/users/gchanan/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Out[5]: nan

In [6]: torch.tensor([]).cuda().mean(0)
Out[6]: tensor(nan, device='cuda:0')

In [7]: torch.tensor([]).cuda().mean()
Out[7]: tensor(nan, device='cuda:0')

In [8]: torch.tensor([]).mean()
Out[8]: tensor(nan)
```
