### ISSUE TITLE
nn.module deepcopy() does not preserve fake tensor mode

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#104465]
When you construct an nn.module inside of a `FakeTensorMode`, every instantiated parameter will become a FakeTensor, with a `.fake_mode` attribute pointed to the currently set `FakeTensorMode`.

However, it looks like if you deepcopy the module, the deepcopy'd module's parameters get a `FakeTensorMode` at a different memory address. This isn't great for downstream consumers like AOTAutograd and friends, which generally expect there to be a single shared fake mode across all inputs / parameters.

If I understand correctly, we don't have a real contract around the semantics of `deepcopy` for arbitrary nn modules. However, module deepcopy'ing is used directly in our codebase today ([example](https://github.com/pytorch/pytorch/blob/b1e4378b05f580ddb3495a4f0e5efe1a0d53d203/torch/nn/modules/transformer.py#L819)), so maybe we should just figure out how to ensure that our `FakeTensorMode` is consistent across deepcopies.

Repro:
```
import torch
from torch._subclasses.fake_tensor import FakeTensorMode
import copy

with FakeTensorMode() as m:
    lin1 = torch.nn.Linear(2, 2)
    lin2 = copy.deepcopy(lin1)
    print(lin1.weight.fake_mode)
    print(lin1.bias.fake_mode)
    # the fake_modes on lin2 has a different memory address vs. the ones on lin1
    print(lin2.weight.fake_mode)
    print(lin2.bias.fake_mode)
```

cc @ezyang @msaroufim @wconstab @anijain2305

**Comment by bdhirsh** [comment]
One option: what do we think of having `copy.deepcopy(FakeTensorMode)` be a no-op that returns the original mode? That shouldn't be too hard. I'll put up a tentative PR.

**Comment by davidberard98** [comment]
arbitrarily triaged to eellison

**Comment by ezyang** [comment]
The difficulty is that our desired semantics (copy tensors but don't copy fake tensor mode) disagree with deepcopy semantics (completely copy every recursicely reachable object). That being said, the deepcopy guarantees are not very strong, since user defined implementations of deepcopy can choose to share objects, so it seems reasonable and desirable for deepcopy on fake tensor to not recurse into the fake tensor mode.

**Comment by eellison** [comment]
You can use `FakeCopyMode` for this use case.


```
import torch
from torch._subclasses.fake_tensor import FakeTensorMode
import copy

with FakeTensorMode() as m:
    lin1 = torch.nn.Linear(2, 2)

with torch._subclasses.fake_tensor.FakeCopyMode(m):
    lin2 = copy.deepcopy(lin1)
    print(lin1.weight.fake_mode)
    print(lin1.bias.fake_mode)
    # the fake_modes are all the same address
    print(lin2.weight.fake_mode)
    print(lin2.bias.fake_mode)
```
