### ISSUE TITLE
DISABLED test_cuda_assert_should_stop_common_device_type_test_suite_cuda (__main__.TestTestingCUDA)

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#104413]
Platforms: <fill this in or delete. Valid labels are: asan, linux, mac, macos, rocm, win, windows.>

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_testing.py%3A%3ATestTestingCUDA%3A%3Atest_cuda_assert_should_stop_common_device_type_test_suite_cuda)).

cc @ptrblck

**Comment by malfet** [comment]
PR has been reverted, closing
