### ISSUE TITLE
Subgraph rewriter cannot handle skip connections

### ISSUE THREAD

**Issue by andrewor14** [pytorch/pytorch#104469]
Models like ResNet rely on skip connections, but subgraph rewriter may silently [filter out the matches](https://github.com/pytorch/pytorch/blob/ddd7da754664abc9d7bc6260c95d5c43f28c08c1/torch/fx/passes/utils/matcher_utils.py#L355-L360) when applied to these models because the matched subgraphs are not "self contained", i.e. one or more of the matched nodes are used outside of the matched subgraph. This self-contained check was likely added to ensure correctness, but it prevents QAT from being able rewrite subgraphs for these models without adding manual logic to duplicate the offending nodes:

https://github.com/pytorch/pytorch/blob/ddd7da754664abc9d7bc6260c95d5c43f28c08c1/torch/ao/quantization/_pt2e/qat_utils.py#L578-L625

This hack works for the skip connections in ResNet but may not work for other models with similar architectures. Just wanted to raise this issue to see if some form of this workaround can be built into the subgraph rewriter itself, so it'll just work out of the box for these type of models.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @ezyang @SherlockNoMad @EikanWang @wenzhe-nrv @kimishpatel @angelayi

**Comment by supriyar** [comment]
how does the subgraph rewriter logic work when we don't have skip connections? i.e. would the subgraph rewriter be able to match the pattern correctly?

cc @angelayi thoughts on which module label would be the right one here?

**Comment by angelayi** [comment]
Let's say you have a pattern graph `b --> c --> d`.

If you have the following graph (with no skip connections):
```
a --> b --> c --> d
```
Then yes, the subgraph rewriter can match the pattern and replace it correctly to something like:
```
a --> <replacement graph> 
```

But if there's a pattern node being used by something outside of the pattern (like a skip connection):
```
a --> b --> c --> d
       \
        --> e
```
The subgraph rewriter can match on the `b --> c --> d`, but it won't replace that graph with the replacement graph because the node `e` is using some node within this pattern. So the workaround that we have in quantization right now duplicates the node `b`:
```
a --> b1 --> c --> d
 \
  --> b2 --> e
```
And then subgraph rewriter can replace it correctly:
```
a --> <replacement graph>
 \
  --> b2 --> e
```

But I'm not sure if this is an issue that should be solved by the generic subgraph rewriter. If we had another node that was using `c` and is not in the pattern graph, would we then copy all the nodes up until `c`?

**Comment by kimishpatel** [comment]
I agree with Angela wrt subgraph rewriter cannot quite do this automagically. @andrewor14 what would "subgraph rewriter handling this" look like?

Also if this is only during convert step, I think duplicating dq nodes is an approach we were gonna take, right?

**Comment by andrewor14** [comment]
> Also if this is only during convert step, I think duplicating dq nodes is an approach we were gonna take, right?

That is true. However, relying on duplicating dq nodes for QAT is fragile; what if the node we need to duplicate is not dq, but something else? Then we would have to add another hack for that specific node type.

**Comment by andrewor14** [comment]
I think there are two cases:
1. Skip connections where the "leaked" node is a placeholder of the match pattern
2. Skip connections where the "leaked" node is matched in the pattern itself

Handling case (1) is much easier than handling case (2); we can just duplicate that placeholder node. I agree that handling case (2) is outside the scope of the subgraph rewriter, and this is probably a niche case.

For QAT, we ran into case (1), so the workaround is duplicating the `dequantize` node (which is a placeholder node of the pattern). My concern here is it just so happens in ResNet that the node we need to duplicate is `dequantize`. In other models it could be something else. If the subgraph rewriter could handle this case more generally for us, then that would simplify the QAT implementation.

Thoughts? @kimishpatel @angelayi @jerryzh168

**Comment by andrewor14** [comment]
I think there are two cases:

Skip connections where the "leaked" node is a placeholder of the match pattern
Skip connections where the "leaked" node is matched in the pattern itself
Handling case (1) is much easier than handling case (2); we can just duplicate that placeholder node. I agree that handling case (2) is outside the scope of the subgraph rewriter, and this is probably a niche case.

For QAT, we ran into case (1), so the workaround is duplicating the dequantize node (which is a placeholder node of the pattern). My concern here is it just so happens in ResNet that the node we need to duplicate is dequantize. In other models it could be something else. If the subgraph rewriter could handle this case more generally for us (e.g. in your example, duplicate node `b`), then that would simplify the QAT implementation.

Thoughts? @kimishpatel @angelayi @jerryzh168

**Comment by andrewor14** [comment]
I think there are two cases:

1. Skip connections where the "leaked" node is a placeholder of the match pattern
2. Skip connections where the "leaked" node is matched in the pattern itself

Handling case (1) is much easier than handling case (2); we can just duplicate that placeholder node. I agree that handling case (2) is outside the scope of the subgraph rewriter, and this is probably a niche case.

For QAT, we ran into case (1), so the workaround is duplicating the `dequantize` node (which is a placeholder node of the pattern). My concern here is it just so happens in ResNet that the node we need to duplicate is `dequantize`. In other models it could be something else. If the subgraph rewriter could handle this case more generally for us (e.g. in your example, duplicate node `b`), then that would simplify the QAT implementation.

Thoughts? @kimishpatel @angelayi @jerryzh168

**Comment by vkuzo** [comment]
@andrewor14  can you paste some real examples of what quantization is trying to do here?  Original graph, quantized graph, what are you trying to replace with what, etc.
