### ISSUE TITLE
[ONNX][TypePromo] Automate codegen type promotion rules

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#104452]
Maybe we should have an exclusive file with the auto generated content? That would make future update easier, maybe even automated without having to parse stuff like "# DO NOT EDIT MANUALLY !!!"

_Originally posted by @thiagocrepaldi in https://github.com/pytorch/pytorch/pull/104063#discussion_r1247218389_

**Comment by BowenBao** [comment]
We should first investigate if https://github.com/pytorch/pytorch/issues/103640 is plausible.

**Comment by justinchuby** [comment]
@BowenBao feel free to update or close this one!

**Comment by BowenBao** [comment]
Closing as not planned.
