### ISSUE TITLE
Support rocm 5.6 ASAP

### ISSUE THREAD

**Issue by johnnynunez** [pytorch/pytorch#104419]
### 🚀 The feature, motivation and pitch

"""
We’ve also seen tremendous interest from developers wanting to run the ROCm open software platform for AI and ML on our Radeon™ consumer and Radeon™ Pro workstation GPUs and have heard the community challenges with specific driver issues on unsupported GPUs. I’m pleased to say that we have fixed the reported issues in ROCm 5.6 and we are committed to expanding our support going forward.  

We plan to expand ROCm support from the currently supported[ AMD RDNA 2 workstation GPUs: the Radeon Pro v620 and w6800](https://docs.amd.com/en/docs-5.0.2/CHANGELOG.html#radeon-pro-v620-and-w6800-workstation-gpus) to select AMD RDNA 3 workstation and consumer GPUs. Formal support for RDNA 3-based GPUs on Linux is planned to begin rolling out this fall, starting with the 48GB Radeon PRO W7900 and the 24GB Radeon RX 7900 XTX, with additional cards and expanded capabilities to be released over time.

"""

pd: https://community.amd.com/t5/rocm/new-rocm-5-6-release-brings-enhancements-and-optimizations-for/ba-p/614745/jump-to/first-unread-message

ROCm 5.6 also brings performance improvements for OpenAI Triton, CuPy, and HIP Graph.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by PennyFranklin** [comment]
the team has  just work out the nightly version with rocm5.5 for several days , and perhaps there's no rc5.6 version, maybe rc5.7 next I guess.
