### ISSUE TITLE
DISABLED test_index_out_of_bounds_exception_cuda (__main__.TestCuda)

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#104414]
Platforms: <fill this in or delete. Valid labels are: asan, linux, mac, macos, rocm, win, windows.>

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_cuda_expandable_segments.py%3A%3ATestCuda%3A%3Atest_index_out_of_bounds_exception_cuda)).

cc @ptrblck

**Comment by malfet** [comment]
Closing, as underlying PR has been reverted
