### ISSUE TITLE
using nn.functional.interpolation but fails on ONNX export

### ISSUE THREAD

**Issue by yancz1989** [pytorch/pytorch#10446]
Hi, everyone,

I'm implementing some segmentation model, and need to use ONNX to convert to caffe2 model. with following code, I have specified the align_corners variable to False, explicitly.

    for encode, decoder in zip(encodes[::-1][1:], self.decode_layers[1:]):
      x = decoder(torch.cat([F.interpolate(x, encode.size()[2:], mode = 'bilinear', align_corners = False), encode], 1))
    return self.segmentation(F.interpolate(x, input_shp, mode = 'bilinear', align_corners = False))

However, when I use ONNX to export this model to caffe2, following error occurs:

/usr/local/lib/python3.5/dist-packages/torch/onnx/symbolic.py:69: UserWarning: ONNX export failed on upsample_bilinear2d because align_corners == True not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
Traceback (most recent call last):
  File "pytorch2caffe.py", line 99, in <module>
    export_params=True)      # store the trained parameter weights inside the model file
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/__init__.py", line 21, in _export
    return utils._export(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py", line 232, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_bilinear2d

This is strange, since I have explicitly set align_corners to False.

Can anyone help me on this issue? Any kind of suggestion is welcomed. Thanks for your kindly information.

**Comment by houseroad** [comment]
Could you provide a minimum code snippet to reproduce the problem?

https://github.com/pytorch/pytorch/pull/10550, we can successfully export.

**Comment by AndersAsa** [comment]
I am having same problem trying to export RetinaNet (https://github.com/kuangliu/pytorch-retinanet). Can you get this to run?

import torch
import torch.onnx
from torch import nn
from torch.autograd import Variable
import torch.nn.functional as F

class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        
    def forward(self, x):
        h1 = x
        h2 = F.interpolate(x, size=h1.size()[-2:], mode='bilinear', align_corners=False)
        h = torch.cat([h1, h2], dim=1)
        return h

model = SimpleNet()
x = Variable(torch.randn(1, 3, 10, 10)).cpu()
torch_out = torch.onnx._export(model, x, '~/temp/test_bilinear_onnx_export.txt', export_params=True, verbose=True)
print('finished onnx export')

**Comment by thedch** [comment]
Here's a code snippet that might shed some light on the issue -- 

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx
from onnx import shape_inference, utils

class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 10, kernel_size=1)

    def forward(self, x):
        x = F.interpolate(x, (100,100), mode='bilinear', align_corners=False)
        # x = F.relu(x)
        x = self.conv1(x)
        return x

filename = 'basic.onnx'
model = SimpleNet()
inputs = torch.randn(1, 3, 224, 224)
torch.onnx.export(model, inputs, filename)

graph = onnx.load(filename)
graph = shape_inference.infer_shapes(graph)
print(graph.graph)
```

At the bottom of the output is a list of tensors in the model:

```
input {
  name: "0"
  type {
    tensor_type {
      elem_type: FLOAT
      shape {
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 3
        }
        dim {
          dim_value: 224
        }
        dim {
          dim_value: 224
        }
      }
    }
  }
}
input {
  name: "1"
  type {
    tensor_type {
      elem_type: FLOAT
      shape {
        dim {
          dim_value: 10
        }
        dim {
          dim_value: 3
        }
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 1
        }
      }
    }
  }
}
input {
  name: "2"
  type {
    tensor_type {
      elem_type: FLOAT
      shape {
        dim {
          dim_value: 10
        }
      }
    }
  }
}
output {
  name: "4"
  type {
    tensor_type {
      elem_type: FLOAT
      shape {
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 10
        }
        dim {
          dim_value: 100
        }
        dim {
          dim_value: 100
        }
      }
    }
  }
}
```

Notice there is no tensor `3`, which is the output of the interpolate op:

```
node {
  input: "0"
  output: "3"
  op_type: "Upsample"
...
```

and the input of the conv op:

```
node {
  input: "3"
  input: "1"
  input: "2"
  output: "4"
  op_type: "Conv"
...
```

However, if I uncomment the `F.relu` and comment the `F.interpolate`: 

```python
    def forward(self, x):
        # x = F.interpolate(x, (100,100), mode='bilinear', align_corners=False)
        x = F.relu(x)
        x = self.conv1(x)
        return x
```

and rerun the code, the very bottom of the output now has a `value_info` section, which contains the needed tensor `3`. 

```
value_info {
  name: "3"
  type {
    tensor_type {
      elem_type: FLOAT
      shape {
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 3
        }
        dim {
          dim_value: 224
        }
        dim {
          dim_value: 224
        }
      }
    }
  }
}
```

which lines up with the relu node (notice output = 3): 

```
node {
  input: "0"
  output: "3"
  op_type: "Relu"
```

and the conv node (notice input = 3):

```
node {
  input: "3"
  input: "1"
  input: "2"
  output: "4"
  op_type: "Conv"
```

So it seems like the F.interpolate operation is not properly being saved in the trace export? Let me know if I am missing a command or something that handles this behavior.

**Comment by houseroad** [comment]
@thedch I have use your code to generate the trace. 

I have the tensor 3 in the value_info section:

```
value_info {
  name: "3"
  type {
    tensor_type {
      elem_type: FLOAT
      shape {
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 3
        }
        dim {
          dim_value: 100
        }
        dim {
          dim_value: 100
        }
      }
    }
  }
}
```

The trace seems good to me.

**Comment by thedch** [comment]
@houseroad hmmmm, interesting. I have tried it on two different systems and both times I do not get the `value_info` 3 tensor. What are your system / package details etc?

```>>> import torch; torch.__version__
'0.4.1'
>>> import onnx; onnx.__version__
'1.3.0'```

**Comment by houseroad** [comment]
I always stick to the master. Can you try to update your pytorch master?

ONNX package should be fine.

**Comment by thedch** [comment]
hi @houseroad -- thank you very much for your help. you are right, nightly build of pytorch fixes this problem:

```
$ conda list | grep -E "pytorch|onnx"
onnx                      1.3.0                     <pip>
pytorch-nightly           1.0.0.dev20180929         py3.6_0    pytorch
```

prints:

```
value_info {
  name: "3"
  type {
    tensor_type {
      elem_type: FLOAT
      shape {
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 3
        }
        dim {
          dim_value: 100
        }
        dim {
          dim_value: 100
        }
      }
    }
  }
}
```

Note to any future readers: at the time of this writing, the standard `conda install -c conda-forge onnx` gives version 1.1.2, which *does not* have `shape_inference`. As such, you must install pytorch nightly *and* build onnx from source to get the code snippet I posted above to work.

**Comment by bhack** [comment]
@thedch Will it work with dynamic shape_factor or size?

**Comment by monchin** [comment]
Hello, @houseroad , I have tried to export F.interpolate(mode='bilinear') as example shows, and it works. But I found that the parameter @align_corners must be set False, or the export would be failed. In the model I used before, I set align_corners True, so I'm wondering if it could be exported when this parameter is set True in the future.
My version:
python: 3.6.5
pytorch: 1.0.0.dev20181125
onnx: 1.3.0

**Comment by alwc** [comment]
> import torch import torch.nn as nn import torch.nn.functional as F import onnx from onnx import shape_inference, utils class SimpleNet(nn.Module): def __init__(self): super().__init__() self.conv1 = nn.Conv2d(3, 10, kernel_size=1) def forward(self, x): x = F.interpolate(x, (100,100), mode='bilinear', align_corners=False) # x = F.relu(x) x = self.conv1(x) return x filename = 'basic.onnx' model = SimpleNet() inputs = torch.randn(1, 3, 224, 224) torch.onnx.export(model, inputs, filename) graph = onnx.load(filename) graph = shape_inference.infer_shapes(graph) print(graph.graph)

@thedch I got `Segmentation fault (core dumped)` when I tried to run the code. I'm using `onnx` 1.3.0 and `pytorch` 1.0.0.dev20181129.

**Comment by lyuwenyu** [comment]
@houseroad  

torch can export `inferpolate` successfully, but `onnx.checker.check_model(onnxmodel)` got error.

-------------
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx
from onnx_tf.backend import prepare

class MM(nn.Module):
	def __init__(self, ):
		super(MM, self ).__init__()
		self.conv = nn.Sequential(nn.Conv2d(2, 10, 3, 2, 1), nn.BatchNorm2d(10), nn.ReLU())

	def forward(self, x):
		x = self.conv(x)
		return F.interpolate(x, scale_factor=2, mode='bilinear', align_corners=False)
		return x

dtype = torch.float
data = torch.rand(1, 2, 5, 5).to(dtype=dtype)
mm = MM().to(dtype=dtype)
mm.eval()

torch.onnx.export(mm, data, 'x.onnx', verbose=False, export_params=True)
onnxmodel = onnx.load('x.onnx')
onnx.checker.check_model(onnxmodel)



Traceback (most recent call last):
  File "test.py", line 41, in <module>
    onnx.checker.check_model(onnxmodel)
  File "~/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx/checker.py", line 82, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].

==> Context: Bad node spec: input: "11" input: "12" output: "13" op_type: "Upsample" attribute { name: "mode" s: "nearest" type: STRING } doc_string:
```




```
python: 3.6
onnx: 1.30
pytorch: 1.0.0.dev20181201
```

**Comment by houseroad** [comment]
Yeah, it got changed in recent master, and the changes were not included in the onnx 1.3.0 release. Could you switch to onnx master branch?

**Comment by glenn-jocher** [comment]
I have the same error. **This is a PyTorch 1.0 error.** Is there any known solution?

**Comment by ezyang** [comment]
Reopening for now, as it doesn't seem to be resolved

**Comment by xxradon** [comment]
Actually,unsample error  come from onnx's code,not pytorch's,so you should follow this #1655 (comment).and problem may be handled.

**Comment by CrawlingD** [comment]
I tried to convert a trained model from pytorch to tensorflow.
If I set `align_corners=True `, there would be small bias between the outputs of pytorch and tensorflow, but if I set `align_corners=False `, the output would be much more biased. And it seemed that onnx-tf didn't store the `align_corners` param.

```
python: 3.6.7
onnx: 1.41
pytorch-nightly: 1.0.0.dev20190306'
```

**Comment by bpinaya** [comment]
Having the same issue of @CrawlingD on Pytorch 1.2

**Comment by suruoxi** [comment]
> I tried to convert a trained model from pytorch to tensorflow.
> If I set `align_corners=True `, convert failed, and there would be small bias between the model outputs of pytorch and tensorflow, but if I set `align_corners=False `, convert succeed, but the outputs would be much more biased. Also it seemed that onnx-tf didn't store the `align_corners` param.
> 
> ```
> python: 3.6.7
> onnx: 1.41
> pytorch-nightly: 1.0.0.dev20190306'
> ```

Same Issue on PyTorch1.2.

**Comment by ezyang** [comment]
According to https://github.com/onnx/onnx/issues/1655 the issue has been fixed in onnx. Please update onnx and let us know if it is still not fixed there. I'm closing this issue.
