### ISSUE TITLE
Incorrect Example Code and Explanation in TorchDynamo Documentation

### ISSUE THREAD

**Issue by x1on9f31** [pytorch/pytorch#104500]
### 📚 The doc issue

When I was going through the [TorchDynamo Overview](https://pytorch.org/docs/stable/dynamo/get-started.html#getting-started), I found the following content confusing.

As in the simple example below, 
```python
import torch
def fn(x, y):
    a = torch.cos(x).cuda()
    b = torch.sin(y).cuda()
    return a + b
new_fn = torch.compile(fn, backend="inductor")
input_tensor = torch.randn(10000).to(device="cuda:0")
a = new_fn(input_tensor, input_tensor)
```
and the documentation right following the above code:
> This example will not actually run faster. Its purpose is to demonstrate the `torch.cos()` and `torch.sin()` features which are examples of pointwise ops as in they operate element by element on a vector.

The contents are talking about the example code, which is correct. However, when it comes to the paragraph below:

> TorchDynamo supports many different backends but inductor specifically works by generating [Triton](https://github.com/openai/triton) kernels and we can inspect them by running TORCH_COMPILE_DEBUG=1 python trig.py with the actual generated kernel being
```python
@pointwise(size_hints=[16384], filename=__file__, meta={'signature': {0: '*fp32', 1: '*fp32', 2: 'i32'}, 'device': 0, 'constants': {}, 'configs': [instance_descriptor(divisible_by_16=(0, 1, 2), equal_to_1=())]})
@triton.jit
def kernel(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 10000
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), xmask)
    tmp1 = tl.sin(tmp0)
    tmp2 = tl.sin(tmp1)
    tl.store(out_ptr0 + (x0 + tl.zeros([XBLOCK], tl.int32)), tmp2, xmask)
```
The content is quite confusing to me:
1. There has never been a `trig.py`;
2. If I assume the content of `trig.py` is the code in the first block, the generated code should be `tmp1 = tl.cos(tmp0)` not `tmp1 = tl.sin(tmp0)`.

I did some search to figure out what was going on. Then I find that this get-started page might be migrated from this [official blog](https://pytorch.org/blog/Accelerating-Hugging-Face-and-TIMM-models/#a-toy-exmaple). In the blog, the toy example is 
```python
import torch
def fn(x, y):
    a = torch.sin(x).cuda()
    b = torch.sin(y).cuda()
    return a + b
new_fn = torch.compile(fn, backend="inductor")
input_tensor = torch.randn(10000).to(device="cuda:0")
a = new_fn(input_tensor, input_tensor)
```
So I realize that the developer who wrote the documentation for TorchDynamo might write the wrong example code for the docs of Dynamo by mistake.

By the way, in the official blog, the explanation of the code is also incorrect, in the blog, the code is two `torch.sin(x)` but in the following contents, the author says there are `torch.cos()` and `torch.sin()`

### Suggest a potential alternative/fix
A simple fix could just fix the given code example to
```python
import torch
def fn(x, y):
    a = torch.sin(x).cuda()
    b = torch.sin(y).cuda()
    return a + b
new_fn = torch.compile(fn, backend="inductor")
input_tensor = torch.randn(10000).to(device="cuda:0")
a = new_fn(input_tensor, input_tensor)
```
which will make the code and the generated contents consistent. And change the following content
>This example will not actually run faster. Its purpose is to demonstrate the `torch.sin()` and `torch.sin()` features which are examples of pointwise ops as in they operate element by element on a vector. 

Otherwise, if we want to demonstrate the `torch.cos()` and `torch.sin()` features, we then will need to change the generated code. Please correct me if I get something wrong.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by davidberard98** [comment]
@x1on9f31 Your suggestion sounds good to me. Would you like to open a PR for this?

**Comment by x1on9f31** [comment]
@davidberard98 Thanks for your reply. I can file a PR for this but could you please tell me which way shall we use? According to the corresponding explanation, I think we should correct the generated kernel code.

**Comment by davidradl** [comment]
@x1on9f31  @davidberard98 
I was looking at this. It still does not look quite right. The code has been changed to 

```
  tmp1 = tl.cos(tmp0)
       tmp2 = tl.sin(tmp0)
       tmp3 = tmp1 + tmp2 
```

This means that the cosine and the sine are both being issued on the same variable tmp0. They should be on the 2 different variables. I am not sure how the 2 input variables are represented in tmp0.

**Comment by x1on9f31** [comment]
@davidradl Thanks for pointing that out. However, if we look at the source code, we can find that although `new_fn` has two input variables, we only pass `input_tensor` twice to it (`a = new_fn(input_tensor, input_tensor)`. So both `tmp1` and `tmp2` are issued on `tmp0`. I hope this addresses your concern.
