### ISSUE TITLE
Misleading error messages for torch.nn.ConstantPad2d and torch.nn.ConstantPad3d

### ISSUE THREAD

**Issue by GwiHwan-Go** [pytorch/pytorch#104508]
### 🐛 Describe the bug

While working with the ConstantPad3d and ConstantPad2d functions in PyTorch, I noticed that providing an input tensor with incompatible dimensions raises a RuntimeError as follows:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/anaconda3/envs/torch20/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/torch20/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anaconda3/envs/torch20/lib/python3.9/site-packages/torch/nn/modules/padding.py", line 25, in forward
    return F.pad(input, self.padding, 'constant', self.value)
RuntimeError: Padding length too large

```
This exception is raised when the following code is executed:

```python 
import torch.nn as nn

m = nn.ConstantPad3d(padding=1, value=1)
m(torch.rand([1,2]))

l = nn.ConstantPad2d(padding=1, value=1)
l(torch.rand([2]))

```
However, the error message "Padding length too large" doesn't directly address the issue of incompatible tensor dimensions. This could potentially lead to some confusion for users when troubleshooting their code.

I propose that the error message be made more descriptive. For example, it could indicate that the "input dimension should be bigger than {} dimensions, but got {}-dimensional tensor for argument", or something along those lines. This would make it clear to the users that the dimensions of the input tensor are not compatible with the padding function they are trying to use.

I believe this change will greatly improve the developer experience. Please let me know if there are any concerns or if further information is required. Thank you for your attention to this matter.

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+440fd1bf20
[pip3] torch==2.1.0.dev20230622+cu118
[pip3] torchaudio==2.1.0.dev20230622+cu118
[pip3] torchvision==0.16.0.dev20230622+cu118
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.6            py39h417a72b_1  
[conda] mkl_random                1.2.2            py39h417a72b_1  
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] pytorch-triton            2.1.0+440fd1bf20          pypi_0    pypi
[conda] torch                     2.1.0.dev20230622+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230622+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230622+cu118          pypi_0    pypi

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Hi @GwiHwan-Go thanks for the issue, we would accept a PR that improves [this error message](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/PadNd.cpp#L181)!

**Comment by GwiHwan-Go** [comment]
Thank you for looking into this issue.
