### ISSUE TITLE
[torch.compile] Guards failures due to storage offsets in new nightly 

### ISSUE THREAD

**Issue by JonasGeiping** [pytorch/pytorch#104563]
### 🐛 Describe the bug

Hi, I just wanted to quickly report this issue. In the newest nightly, static code that used to compile without problems broke for me. The model takes views into a tensor as inputs  (see simplified example below). I turns out that with the newest nightly, it is recompiling on every storage offset.

The problem is fixed if the view is cloned before being handed to the model.

### Error logs

```
[2023-07-03 19:54:32,259] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (64)
   function: 'forward' ()
   reasons:    reasons: tensor 'L['input_ids']' storage_offset mismatch, expected 63, actual 64
```

### Minified repro

A sketch of the problem (but not directly runnable):

        input_ids = torch.randint(0, 256, (1024,))
        for seq_idx in range(0, max(1, input_ids.shape[1] - 2)), 2):
            model_inputs = input_ids[:, seq_idx : seq_idx + 3]
           compiled_model(model_inputs)

Workaround:
```
        input_ids = torch.randint(0, 256, (1024,))
        for seq_idx in range(0, max(1, input_ids.shape[1] - 2), 2):
            model_inputs = input_ids[:, seq_idx : seq_idx + 3].clone()
           compiled_model(model_inputs)
```

### Versions

```
[2023-07-03 20:01:32,613] GPU : NVIDIA RTX A4000. CUDA: 12.1.
[2023-07-03 20:01:32,615] Platform: linux, Python: 3.10.11, PyTorch: 2.1.0.dev20230703
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ezyang** [comment]
Cc @voznesenskym

**Comment by ezyang** [comment]
I think this is because https://github.com/pytorch/pytorch/pull/104204 is too aggro. I suspect that Inductor actually generates polymorphic code for storage offsets automatically, so we should always treat these as "dynamic" no matter what.

**Comment by eellison** [comment]
The likely source for this issue was reverted. @JonasGeiping would you confirm that on a nightly containing [bfd995f0d6bf87262613b5e89d871832ca9e9938](https://github.com/pytorch/pytorch/commit/bfd995f0d6bf87262613b5e89d871832ca9e9938) this no longer repros ?

**Comment by JonasGeiping** [comment]
@eellison Yeah, the recompilation does not occur on the 6th of July nightly.
