### ISSUE TITLE
Complex autograd: 

### ISSUE THREAD

**Issue by thomasediolausson** [pytorch/pytorch#104514]
### 🐛 Describe the bug

Hi! 

I'm trying to use complex autograd mechanics to optimize a problem with a custom FFT function. I'm hitting an error in the backward pass.

```RuntimeError: grad can be implicitly created only for real scalar outputs but got torch.complex64```

I hope that this is an okay platform to ask a question like this even when it's a custom library involved.

I have some code to reproduce the error and show what I'm trying to achieve.

`import sigpy as sp
import torch
import torch.nn.functional as F
import numpy as np
my_device = "cuda"
x_dim = y_dim = 500
my_fft = sp.to_pytorch_function(sp.linop.FFT((x_dim,y_dim), axes=(-1, -2)))
phantom = torch.tensor(sp.shepp_logan((x_dim,y_dim)), device=my_device, dtype=torch.cfloat, requires_grad=True)
phantom_fft = my_fft.apply(phantom) 
vectors = [torch.arange(0, s, device=my_device) for s in (x_dim,y_dim)]
grids = torch.meshgrid(vectors)
orig_grid = torch.stack(grids)[None,:,:,:] 
orig_grid = orig_grid.type(dtype=torch.float32)
for i in range(len((x_dim,y_dim))):
    orig_grid[:, i, ...] = 2 * (orig_grid[:, i, ...] / ((x_dim,y_dim)[i] - 1) - 0.5)
orig_grid = orig_grid.permute(0, 2, 3, 1)
orig_grid = orig_grid[..., [1, 0]]
warped_phantom = F.grid_sample(phantom[None,None,:,:].real, orig_grid)
warped_phantom_fft = my_fft.apply(warped_phantom[0,0,:,:])
loss = torch.mean(warped_phantom_fft-phantom_fft)**2
loss.backward()`

Thanks

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230702
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Quadro P6000
Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD Ryzen Threadripper 3970X 32-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     3700.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        7400.69
Virtualization:                  AMD-V
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        16 MiB
L3 cache:                        128 MiB
NUMA node0 CPU(s):               0-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.1.0.dev20230702
[pip3] torchaudio==2.1.0.dev20230702
[pip3] torchvision==0.16.0.dev20230702
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-fft                   1.3.6                    pypi_0    pypi
[conda] mkl-random                1.2.2                    pypi_0    pypi
[conda] mkl-service               2.4.0                    pypi_0    pypi
[conda] mkl_fft                   1.3.6           py310h1128e8f_1  
[conda] mkl_random                1.2.2           py310h1128e8f_1  
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] numpy-base                1.25.0          py310hb5e798b_0  
[conda] pytorch                   2.1.0.dev20230702 py3.10_cuda12.1_cudnn8.9.2_0    pytorch-nightly
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torch                     2.1.0.dev20230702          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230702          pypi_0    pypi
[conda] torchtriton               2.1.0+440fd1bf20           py310    pytorch-nightly
[conda] torchvision               0.16.0.dev20230702          pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by lezcano** [comment]
The gradient is only mathematically defined for functions onto the real numbers. Your function takes complex values, hence the error.

The forum is often a better place for these questions: https://discuss.pytorch.org/
