### ISSUE TITLE
VGG19,enocder ,Decoder given error at loading model at testing time

### ISSUE THREAD

**Issue by praveenkumarchandaliya** [pytorch/pytorch#10455]
c = torch.load('../output/decoder_epoch_30.pth')
netE.load_state_dict(c)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
**KeyError: 'unexpected key "decoder_dense.0.weight" in state_dict'**

**Comment by soumith** [comment]
it looks like a user-land bug. Please post questions at https://discuss.pytorch.org
