### ISSUE TITLE
Memory use with torch.nn.functional.cosine_similarity() nearly doubled from torch 1.11.0 to torch 2.0.1 

### ISSUE THREAD

**Issue by colleenjg** [pytorch/pytorch#104564]
### 🐛 Describe the bug

Torch code that I ran with no problem on [**Google Colab**](https://colab.research.google.com/) (default configuration) a year ago is now failing with an out-of-memory error. Specifically, calling `torch.nn.functional.cosine_similarity()` seems to require around double the amount of memory it used to, to the point where this fails:

```
import torch
mat = torch.nn.functional.cosine_similarity(torch.rand((1, 4000, 100)), torch.rand((4000, 1, 100)), dim=2)
```

as the operation requires more than the amount of RAM available (12.7 GB). If I run the same but on a GPU (15 GB of RAM), I get the following error when it crashes:

```OutOfMemoryError: CUDA out of memory. Tried to allocate 5.96 GiB (GPU 0; 14.75 GiB total capacity; 12.05 GiB already allocated; 2.57 GiB free; 12.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF```

These errors occur with `torch==2.0.1+cu118` and `torchvision==0.15.2+cu118`. If I downgrade to `torch==1.11.0+cu102` and `torchvision==0.12.0+cu102`, the code runs fine. It's still a big operation, but from Colab's resources management panel, it looks like the memory use peaks at 7 GB before dropping down, so much lower than with torch 2.0.1. (I haven't tested any other torch versions between `1.11` and `2.0.1`.)

I don't see any indication in the [documentation](https://pytorch.org/docs/stable/generated/torch.nn.functional.cosine_similarity.html) that the function or how it is called has changed. Also, if I reduce the `4000` dimension to `3000`, the code runs in both versions, and I get the same results, when I seed the RNG. So I assume that something has changed in the implementation details?

Thank you!

### Versions

```Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.107+-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7B12
Stepping:                        0
CPU MHz:                         2249.998
BogoMIPS:                        4499.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        512 KiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save umip rdpid

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect```

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by colleenjg** [comment]
**Acknowledgment:** Thanks to @spirosChv who pointed out this bug in our public Colab notebook, and figured out that downgrading to torch 1.11 provides a temporary fix.

**Comment by spirosChv** [comment]
> @spirosChv Thanks for the clarification. Just remind that consumed RAM in my test case should be 0.3GB, not 3GB

Yes, I made the same mistake. In my local system is around the value you posted.

**Comment by colleenjg** [comment]
Thank you for taking the time to take a look @ZailiWang and @spirosChv! 

Are you sure though that `psutil` is giving a correct estimate?  I got a similar number around 400 MB when running it on my local machine (`torch 1.10`), but (1) that seems way to low for the size of the operation, and (2) if I track my memory use with `htop`, it actually goes up by ~7 GB while running the function. So I'm not sure `psutil` is right for measuring peak memory used by a function.

If I run the operation on my local machine that has 16 GB of RAM, using `torch 2.0.0`, I get an out-of-memory crash, like on Colab. Perhaps you could also try eyeballing peak memory use using `htop`, and see whether the numbers line up? I'm wondering whether it's possible that the call is also using >10 GB of RAM on your machines, but isn't crashing because you have more than 16 GB of RAM available?  

Also, I'm running all this on CPU (Intel Core i7-6700HQ) on Ubuntu 22.04.

**Comment by spirosChv** [comment]
@colleenjg you are right. I just checked the code with `htop` and the consumption reaches ~7.5 GB of memory.

**Comment by colleenjg** [comment]
Ok, that's good to know! And that is with `torch 2.0`? If so, it sounds like you aren't having this issue locally.

**Comment by lezcano** [comment]
The algorithm that computes it was changed in https://github.com/pytorch/pytorch/pull/31378 (which was merged only last year) for one that is more stable. I reckon that that's the commit that's at fault.

**Comment by lezcano** [comment]
I would suggest you try torch.compile-ing your own cosine similarity function. That'd be much faster and would use much less memory than the one we currently have for eager.

**Comment by colleenjg** [comment]
@lezcano Thank you for spotting the link! Yup, that definitely looks like it's the cause.

**Comment by colleenjg** [comment]
Ok, so yeah, for a simple 2D input, where the similarity is computed across `dim=1`, the following produces the same result and runs much faster, with little memory use:

```
def cosine_similarity(t1, t2, eps=1e-8):

    # get normalization value
    t1_div = torch.linalg.norm(t1, dim=1, keepdims=True)
    t2_div = torch.linalg.norm(t2, dim=1, keepdims=True)

    # normalize, avoiding division by 0
    t1_norm = t1 / torch.clamp(t1_div, eps)
    t2_norm = t2 / torch.clamp(t2_div, eps)

    mat = torch.matmul(t1 / t1_div, t2_norm.T)
    return mat
```

**Comment by lezcano** [comment]
You probably mean
```python
    mat = torch.matmul(t1_norm, t2_norm.T)
```
and multiplying by `math.sqrt(eps)`, right?

Also, the following should produce even better code:
```python
def cosine_similarity(t1, t2, dim=1, eps=1e-8):
    # get normalization value
    t1_div = torch.linalg.vector_norm(t1, dim=dim, keepdims=True)
    t2_div = torch.linalg.vector_norm(t2, dim=dim, keepdims=True)

    # normalize, avoiding division by 0
    t1_norm = t1 / torch.clamp(t1_div, math.sqrt(eps))
    t2_norm = t2 / torch.clamp(t2_div, math.sqrt(eps))

    return (t1_norm * t2_norm).sum(dim=dim)
```
That is:
- Perf: Use product + sum for small reductions, as it can be fused with previous ops
- Style: use `vector_norm` over norm always, as it has cleaner semantics

The only issue here is that, if you give it a tensor with a norm that's too small, the this will zero-out the gradients along those elements, while on eager we are careful not to do this. If you want that same behaviour, I believe the following code should achieve that:

```python
@torch.compile
def cosine_similarity(t1, t2, dim=-1, eps=1e-8):
    # get normalization value
    t1_div = torch.linalg.vector_norm(t1, dim=dim, keepdims=True)
    t2_div = torch.linalg.vector_norm(t2, dim=dim, keepdims=True)

    t1_div = t1_div.clone()
    t2_div = t2_div.clone()
    with torch.no_grad():
        t1_div.clamp_(math.sqrt(eps))
        t2_div.clamp_(math.sqrt(eps))

    # normalize, avoiding division by 0
    t1_norm = t1 / t1_div
    t2_norm = t2 / t2_div

    return (t1_norm * t2_norm).sum(dim=dim)
```

**Comment by lezcano** [comment]
The memory consumption should be better now, hopefully. That being said, this is the poster child example of an operation that would fare much better under `torch.compile` (broadcasting pointwise op into a reduction), as `torch.compile` is able to compute these without instantiating the intermediary `(4000, 4000, 100)` tensor.

**Comment by colleenjg** [comment]
Noted! Thank you so much, @lezcano for tacking this, and for the additional advice!
