### ISSUE TITLE
Wrong functionalization of as_strided leads to wrong results

### ISSUE THREAD

**Issue by ShaharGottlieb** [pytorch/pytorch#104505]
### 🐛 Describe the bug

according to documentation (https://pytorch.org/docs/stable/generated/torch.as_strided.html), "as_strided" should override the existing strides and offset of the tensor storage (as opposed to other view operations which are composite in nature).
Thus, when functionalizating as_strided, we should not add it on top of previous  view operations.

This issue leads to incorrect results of torch.compile.

reproducer:
* note that when not using a custom compiler, then torch fails to compile all together
* using core_aten_decompositions doesn't change the issue

```
import torch
import torch._dynamo
import logging
import numpy as np
import torchvision.models as models

from torch._dynamo.backends.common import aot_autograd
from torch._decomp import core_aten_decompositions

print(torch.__version__)

def main():
    def inner_compiler(gm: torch.fx.GraphModule, example_inputs):
        gm.graph.print_tabular()
        return gm.forward

    def foo(a):
        e = a.diagonal()
        f = e.as_strided((2,), (1,), 0)
        f.add_(1.0)
        return a

    a = torch.randn(2, 4)
    a_ref = a.clone()
    torch._dynamo.reset()
    aot_backend = aot_autograd(fw_compiler=inner_compiler)#, decompositions=core_aten_decompositions())
    compiled_model = torch.compile(foo, dynamic=True, backend=aot_backend)
    out_ref = foo(a_ref)
    print(out_ref)
    out = compiled_model(a)
    print(out)
    print(out == out_ref)


main()
```

### Error logs

when not using custom compiler:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py](https://localhost:8080/#) in call_user_compiler(self, gm)
    669             else:
--> 670                 compiled_fn = compiler_fn(gm, self.fake_example_inputs())
    671             _step_logger()(logging.INFO, f"done compiler function {name}")

42 frames
AttributeError: The underlying op of 'aten.sym_storage_offset' has no overload name 'name'

While executing %sym_storage_offset : [#users=3] = call_function[target=torch.ops.aten.sym_storage_offset](args = (%arg0_1,), kwargs = {})
Original traceback:
  File "<ipython-input-3-6e27d662c8bc>", line 18, in foo
    e = a.diagonal()

The above exception was the direct cause of the following exception:

BackendCompilerFailed                     Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py](https://localhost:8080/#) in call_user_compiler(self, gm)
    673         except Exception as e:
    674             compiled_fn = gm.forward
--> 675             raise BackendCompilerFailed(self.compiler_fn, e) from e
    676         return compiled_fn
    677 

BackendCompilerFailed: debug_wrapper raised AttributeError: The underlying op of 'aten.sym_storage_offset' has no overload name 'name'

While executing %sym_storage_offset : [#users=3] = call_function[target=torch.ops.aten.sym_storage_offset](args = (%arg0_1,), kwargs = {})
Original traceback:
  File "<ipython-input-3-6e27d662c8bc>", line 18, in foo
    e = a.diagonal()

Set torch._dynamo.config.verbose=True for more information

You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

### Versions

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21676  100 21676    0     0   102k      0 --:--:-- --:--:-- --:--:--  102k
Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.107+-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) CPU @ 2.00GHz
Stepping:                        3
CPU MHz:                         2000.144
BogoMIPS:                        4000.28
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        1 MiB
L3 cache:                        38.5 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kadeng @svekars @brycebortree @msaroufim @bdhirsh @anijain2305 @chauhang @carljparker @wconstab

**Comment by bdhirsh** [comment]
Unfortunately, I don't think there's an easy fix to this. As you pointed out, `as_strided()` is non-compositional. In fact, as_strided() can cause all sorts of problems that are not easy to solve in `torch.compile` and functionalization. Another example is that `as_strided` can be used to view outside the range of an existing tensor:
```
def f(x_slice):
    # this will not work well with functionalization or torch.compile either
    x_larger = x_slice.as_strided((1000, (1,))

x = torch.randn(1000)
x_slice = x[:10]
f(x_slice)
```

Long term, @ezyang has mentioned adding a version of `as_strided` that is compositional and making pytorch stride-agnostic. Short term, we should probably add some docs that `as_strided()` does not play well with `torch.compile` when used in a non-compositional way.

**Comment by ezyang** [comment]
@bdhirsh That being said, if we're willing to guard on the exact strideness and storage offset on the input, it should be possible to support the non-compositional as_strided "directly" (since it will always behave identically from run to run.) This will help as long as the as_strided strides aren't computed in some way. If the as_strided strides are computed, the best fix is to work out how to represent it compositionally... this is harder than it sounds unfortunately.

**Comment by voznesenskym** [comment]
@bdhirsh to update

**Comment by bdhirsh** [comment]
No major update:

(1) You can technically work around by using other view ops in your program instead of as_strided

(2) I should probably brainstorm with Ed at some point on ways to make the as_strided situation better. Although it seems very difficult to ensure that we're correct 100% of the time with as_strided?

(3) alternative: we should just graph break on as_strided, assuming it's rare enough that this won't cause major perf issues (I think this is the case, but would like a second opinion)

(4) otherwise, we might want to add a warning to the docs for torch.as_strided until we fix the behavior (or decide to graph break)

**Comment by ezyang** [comment]
If we have good alternatives for common as strided usage, graph breaking on it seems very reasonable, and in all likelihood will make people's code faster too, since as strided backwards is famously slow.

There is a complicated correct fix but whatever, I'm not sure I care

**Comment by bdhirsh** [comment]
@jansel also mentioned at a previous triage meeting that (cc'ing to confirm I'm summarizing everything correctly):

(1) as_strided on its own is relatively common to see in user code, and (generally?) is not used in a way that will cause correctness issues with compile (which makes unconditionally graph breaking a risk).

(2) The correctness issue is probably only really coming up when we have user-code with as_strided + a mutation.

So one alternative is to only do something when we detect mutations on an `as_strided` alias. However:
(1) We can't really graph break when we encounter that, since we won't encounter it till we run functionalization in AOTAutograd
(2) We could error in that case, since it's hopefully pretty rare, but having torch.compile raise a loud error is not a great UX
(3) We could warn, so the user at least knows that the as_strided + mutation in their model has the potential to be problematic. The warning won't be super actionable though.

@ezyang what do you think of the above? IMO, warning is probably the least contentious option. Erroring would be nice, although it carries the assumption that as_strided + mutation in user code is actually very rare (which seems like.. a reasonable assumption?)

**Comment by ezyang** [comment]
I mean, we can always ship the error and have it link to this issue and see if people start complaining.

**Comment by xadupre** [comment]
I think I faced the same issue with a slice. Here is my finding. 

1. The output is tagged as "alias_of_input" at https://github.com/pytorch/pytorch/blob/main/torch/_functorch/_aot_autograd/collect_metadata_analysis.py#L419
2. The model is compiled and executed, 
3. The output is changed: data pointer comes from the input, strides comes from the output
   at https://github.com/pytorch/pytorch/blob/main/torch/_functorch/_aot_autograd/functional_utils.py#L240

In my case just avoid tagging output as `alias_of_input` would solve the issue but I did not find any way to disable it.

```python
import copy
from typing import List
import torch
from torch._dynamo.backends.common import aot_autograd


def my_compiler(graph_module: torch.fx.GraphModule, args: List[torch.Tensor]):

    def run(x):
        y = x[:, 1:2].contiguous()
        print("run:", y, y.data_ptr(), y.stride())  #  [[1, 5, 9]], P1, (1, 1)
        return y

    return run


class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x[:, 1:2]  # replace this line by x.clone()[:, 1:2] fixes the issue, is there any other way?


aot_compiler = aot_autograd(fw_compiler=my_compiler)

model = MyModule()

compiled_model = torch.compile(
    copy.deepcopy(model), backend=aot_compiler, dynamic=False, fullgraph=True
)

x = torch.arange(12, requires_grad=True, dtype=torch.float32).reshape((-1, 4))

baseline_result = model(x)
result = compiled_model(x)

print("expected:", baseline_result)  # [[1, 5, 9]]
print("compiled:", result)  # [[0, 1, 2]], expected is [[1, 5, 9]]
print("----------")
print("Verification")
print("x.data_ptr(): ", x.data_ptr())  # P0
print(
    "baseline_result, ptr, strides:",
    baseline_result.data_ptr(),  # P2
    baseline_result.stride(),  # (4, 1)
)
print("result, ptr, strides:", result.data_ptr(), result.stride())  # P0, (1, 1)
print("result.data_ptr() == x.data_ptr()", result.data_ptr() == x.data_ptr())  # True

"""
Complete output:

::

    run: tensor([[1.],
            [5.],
            [9.]]) 94157005401152 (1, 1)
    expected: tensor([[1.],
            [5.],
            [9.]], grad_fn=<SliceBackward0>)
    compiled: tensor([[0.],
            [1.],
            [2.]], grad_fn=<AsStridedBackward0>)
    ----------
    Verification
    x.data_ptr():  94157091846528
    baseline_result, ptr, strides: 94157091846532 (4, 1)
    result, ptr, strides: 94157091846528 (1, 1)
    result.data_ptr() == x.data_ptr() True
```

**Comment by bdhirsh** [comment]
I opted for a slightly more conservative check in https://github.com/pytorch/pytorch/pull/122502, where I only ban as_strided + mutation in cases where we think the as_strided is used non-compositionally
