### ISSUE TITLE
Inconsistency in nn.ChannelShuffle Behavior with Empty Input Tensor on CPU and CUDA

### ISSUE THREAD

**Issue by GwiHwan-Go** [pytorch/pytorch#104603]
I've observed an inconsistent behavior when applying the nn.ChannelShuffle operation on an empty input tensor on different backends (CPU and CUDA).

The following code executed on CUDA raises a NotImplementedError:
```python
import torch
groups = 2
m = torch.nn.ChannelShuffle(groups=groups)
input_tensor = torch.rand([6, 0, 6], dtype=torch.float32).to('cuda')
m.to('cuda')
m(input_tensor)

```
The error message received is:
```
NotImplementedError: Could not run 'aten::channel_shuffle' with arguments from the 'CUDA' backend.
```
However, when I execute the same code snippet on CPU, no error is thrown. I've noticed that this situation is reminiscent of the previously reported issue #76616.

Version ::

PyTorch version: 2.1.0.dev20230622+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 12.0.0-3ubuntu1~20.04.5
CMake version: version 3.26.1
Libc version: glibc-2.31

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-152-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2070
GPU 1: NVIDIA GeForce RTX 2070
GPU 2: NVIDIA GeForce RTX 2070
GPU 3: NVIDIA GeForce RTX 2070

Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by drisspg** [comment]
https://github.com/pytorch/pytorch/blob/d3ba8901d8640eb16f88b2bfef9df7fa383d4b47/aten/src/ATen/native/native_functions.yaml#L4297

**Comment by drisspg** [comment]
[https://github.com/pytorch/pytorch/blob/d3ba8901d8640eb16f88b2bfef9df7fa383d4b47/aten/src/ATen/native/native_functions.yaml#L4297

As you ](https://github.com/pytorch/pytorch/blob/d3ba8901d8640eb16f88b2bfef9df7fa383d4b47/aten/src/ATen/native/native_functions.yaml#L4297)

**Comment by mikaylagawarecki** [comment]
To avoid the NotImplementedError you could update this line 

https://github.com/pytorch/pytorch/blob/d3ba8901d8640eb16f88b2bfef9df7fa383d4b47/aten/src/ATen/native/native_functions.yaml#L4299

to 

`CPU, CUDA: channel_shuffle`

Would be happy to review a PR that adds this!

cc @kimishpatel who added channel shuffle, is there a reason why it was CPU-only?

**Comment by GwiHwan-Go** [comment]
I'm also curious about why this function was implemented as CPU-only.

**Comment by kimishpatel** [comment]
> To avoid the NotImplementedError you could update this line
> 
> https://github.com/pytorch/pytorch/blob/d3ba8901d8640eb16f88b2bfef9df7fa383d4b47/aten/src/ATen/native/native_functions.yaml#L4299
> 
> to
> 
> `CPU, CUDA: channel_shuffle`
> 
> Would be happy to review a PR that adds this!
> 
> cc @kimishpatel who added channel shuffle, is there a reason why it was CPU-only?

It was added mainly for inference optimization on edge side, hence did not add cuda implementation.

**Comment by jbschlosser** [comment]
> I'm also curious about why this function was implemented as CPU-only.

Most likely because it's much more work to write a CUDA impl.
