### ISSUE TITLE
Xcode 15 Beta infinite loop when compiling ReduceOpsKernel.cpp.DEFAULT.cpp

### ISSUE THREAD

**Issue by derekelewis** [pytorch/pytorch#104673]
### 🐛 Describe the bug

clang appears to go into an infinite loop with default optimizations when building ReduceOpsKernel.cpp.DEFAULT.cpp w/ Xcode 15. Reproducible on 10.13 and 10.14 (Beta 1, 2, and 3) and all betas of Xcode 15, including Beta 3 released today. Compiles & links fine when building with CMAKE_BUILD_TYPE=Debug or removing -O2 and -O3 flags at compile time. 

Not sure if this is a PyTorch issue or Apple developer tools - please close if it is the latter. 

Compile command:

`
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DAT_PER_OPERATOR_HEADERS -DCAFFE2_BUILD_MAIN_LIB -DCPUINFO_SUPPORTED_PLATFORM=1 -DFMT_HEADER_ONLY=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DNNP_CONVOLUTION_ONLY=0 -DNNP_INFERENCE_ONLY=0 -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -Dtorch_cpu_EXPORTS -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/build/aten/src -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/aten/src -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/build -I/Users/dlewis/work/repos/third-party/pytorch/pytorch -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/cmake/../third_party/benchmark/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/onnx -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/build/third_party/onnx -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/foxi -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/build/third_party/foxi -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/torch/csrc/api -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/torch/csrc/api/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/caffe2/aten/src/TH -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/build/caffe2/aten/src/TH -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/build/caffe2/aten/src -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/build/caffe2/../aten/src -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/torch/csrc -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/miniz-2.1.0 -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/kineto/libkineto/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/kineto/libkineto/src -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/aten/src/ATen/.. -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/FXdiv/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/c10/.. -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/pthreadpool/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/cpuinfo/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/aten/src/ATen/native/quantized/cpu/qnnpack/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/aten/src/ATen/native/quantized/cpu/qnnpack/src -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/cpuinfo/deps/clog/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/NNPACK/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/FP16/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/fmt/include -I/Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/flatbuffers/include -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/cmake/../third_party/googletest/googlemock/include -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/cmake/../third_party/googletest/googletest/include -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/protobuf/src -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/XNNPACK/include -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/cmake/../third_party/eigen -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/build/include -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=braced-scalar-init -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wvla-extension -Wnewline-eof -Winconsistent-missing-override -Winconsistent-missing-destructor-override -Wno-range-loop-analysis -Wno-pass-failed -Wsuggest-override -Wno-error=pedantic -Wno-error=old-style-cast -Wno-error=inconsistent-missing-override -Wno-error=inconsistent-missing-destructor-override -Wconstant-conversion -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-missing-braces -Wunused-lambda-capture -Qunused-arguments -fcolor-diagnostics -faligned-new -Wno-unused-but-set-variable -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DUSE_MPS -Wno-unused-private-field -Wno-missing-braces -O3 -DNDEBUG -DNDEBUG -std=gnu++17 -arch arm64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fPIC -D__NEON__ -DTH_HAVE_THREAD -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-type-limits -Wno-array-bounds -Wno-strict-overflow -Wno-strict-aliasing -Wno-missing-braces -Wno-range-loop-analysis -fvisibility=hidden -O2 -O3 -DCPU_CAPABILITY=DEFAULT -DCPU_CAPABILITY_DEFAULT -MD -MT caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp.o -MF caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp.o.d -o caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp.o -c /Users/dlewis/work/repos/third-party/pytorch/pytorch/build/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp
  501 46639 46638   0  4:55PM ttys000    3:29.62 /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple arm64-apple-macosx14.0.0 -Wundef-prefix=TARGET_OS_ -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name ReduceOpsKernel.cpp.DEFAULT.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -mllvm -extra-vectorizer-passes -fno-strict-return -ffp-contract=on -fno-rounding-math -ffp-exception-behavior=ignore -funwind-tables=1 -fobjc-msgsend-selector-stubs -target-sdk-version=14.0 -fvisibility-inlines-hidden-static-local-var -target-cpu apple-m1 -target-feature +v8.5a -target-feature +crc -target-feature +lse -target-feature +rdm -target-feature +crypto -target-feature +dotprod -target-feature +fp-armv8 -target-feature +neon -target-feature +fp16fml -target-feature +ras -target-feature +rcpc -target-feature +zcm -target-feature +zcz -target-feature +fullfp16 -target-feature +sm4 -target-feature +sha3 -target-feature +sha2 -target-feature +aes -target-abi darwinpcs -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=lldb -target-linker-version 902.11 -fcoverage-compilation-dir=/Users/dlewis/work/repos/third-party/pytorch/pytorch/build -resource-dir /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0 -dependency-file caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp.o.d -skip-unused-modulemap-deps -MT caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp.o -sys-header-deps -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/cmake/../third_party/googletest/googlemock/include -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/cmake/../third_party/googletest/googletest/include -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/protobuf/src -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/XNNPACK/include -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/cmake/../third_party/eigen -isystem /Users/dlewis/work/repos/third-party/pytorch/pytorch/build/include -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -D AT_PER_OPERATOR_HEADERS -D CAFFE2_BUILD_MAIN_LIB -D CPUINFO_SUPPORTED_PLATFORM=1 -D FMT_HEADER_ONLY=1 -D FXDIV_USE_INLINE_ASSEMBLY=0 -D HAVE_MMAP=1 -D HAVE_SHM_OPEN=1 -D HAVE_SHM_UNLINK=1 -D MINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -D NNP_CONVOLUTION_ONLY=0 -D NNP_INFERENCE_ONLY=0 -D ONNXIFI_ENABLE_EXT=1 -D ONNX_ML=1 -D ONNX_NAMESPACE=onnx_torch -D USE_EXTERNAL_MZCRC -D _FILE_OFFSET_BITS=64 -D torch_cpu_EXPORTS -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/build/aten/src -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/aten/src -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/build -I /Users/dlewis/work/repos/third-party/pytorch/pytorch -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/cmake/../third_party/benchmark/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/onnx -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/build/third_party/onnx -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/foxi -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/build/third_party/foxi -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/torch/csrc/api -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/torch/csrc/api/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/caffe2/aten/src/TH -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/build/caffe2/aten/src/TH -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/build/caffe2/aten/src -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/build/caffe2/../aten/src -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/torch/csrc -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/miniz-2.1.0 -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/kineto/libkineto/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/kineto/libkineto/src -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/aten/src/ATen/.. -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/FXdiv/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/c10/.. -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/pthreadpool/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/cpuinfo/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/aten/src/ATen/native/quantized/cpu/qnnpack/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/aten/src/ATen/native/quantized/cpu/qnnpack/src -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/cpuinfo/deps/clog/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/NNPACK/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/FP16/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/fmt/include -I /Users/dlewis/work/repos/third-party/pytorch/pytorch/third_party/flatbuffers/include -D USE_PTHREADPOOL -D NDEBUG -D USE_KINETO -D LIBKINETO_NOCUPTI -D LIBKINETO_NOROCTRACER -D USE_PYTORCH_QNNPACK -D USE_XNNPACK -D SYMBOLICATE_MOBILE_DEBUG_HANDLE -D USE_MPS -D NDEBUG -D NDEBUG -D __NEON__ -D TH_HAVE_THREAD -D CPU_CAPABILITY=DEFAULT -D CPU_CAPABILITY_DEFAULT -internal-isystem /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1 -internal-isystem /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/local/include -internal-isystem /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include -internal-externc-isystem /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include -internal-externc-isystem /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -O3 -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=braced-scalar-init -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wvla-extension -Wnewline-eof -Winconsistent-missing-override -Winconsistent-missing-destructor-override -Wno-range-loop-analysis -Wno-pass-failed -Wsuggest-override -Wno-error=pedantic -Wno-error=old-style-cast -Wno-error=inconsistent-missing-override -Wno-error=inconsistent-missing-destructor-override -Wconstant-conversion -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-missing-braces -Wunused-lambda-capture -Wno-unused-but-set-variable -Werror=format -Werror=cast-function-type -Wno-unused-private-field -Wno-missing-braces -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-type-limits -Wno-array-bounds -Wno-strict-overflow -Wno-strict-aliasing -Wno-missing-braces -Wno-range-loop-analysis -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -Wno-reserved-identifier -Wno-gnu-folding-constant -std=gnu++17 -fdeprecated-macro -fdebug-compilation-dir=/Users/dlewis/work/repos/third-party/pytorch/pytorch/build -ferror-limit 19 -fvisibility=hidden -fvisibility-inlines-hidden -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fno-cxx-modules -fcxx-exceptions -fexceptions -faligned-allocation -fmax-type-align=16 -fcommon -fcolor-diagnostics -vectorize-loops -vectorize-slp -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation -fno-odr-hash-protocols -clang-vendor-feature=+enableAggressiveVLAFolding -clang-vendor-feature=+revert09abecef7bbf -clang-vendor-feature=+thisNoAlignAttr -clang-vendor-feature=+thisNoNullAttr -mllvm -disable-aligned-alloc-awareness=1 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp.o -x c++ /Users/dlewis/work/repos/third-party/pytorch/pytorch/build/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp.DEFAULT.cpp
`

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gitc00dd43
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.0 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.34.3)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.11.3 (main, May 15 2023, 18:01:31) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.0
[pip3] torch==2.1.0a0+gitc00dd43
[conda] numpy                     1.25.0                   pypi_0    pypi
[conda] torch                     2.1.0a0+gitc00dd43          pypi_0    pypi

cc @malfet @seemethere @albanD

**Comment by albanD** [comment]
cc @kulinseth

**Comment by derekelewis** [comment]
Submitted feedback to Apple. Apple requested the that ReduceOpsKernel.cpp be compiled with -fcrash-diagnostics=all -gen-reproducer, which outputs the full preprocessed file used for compilation and a script to run compilation of the file. Files are in the below gist, which reproduce the clang infinite loop when building ReduceOpsKernel.cpp.

https://gist.github.com/derekelewis/98e53d533250b00da76e38369093c70f

**Comment by kulinseth** [comment]
> Submitted feedback to Apple. For any Apple employees it is feedback case #FB12533740. Apple requested that ReduceOpsKernel.cpp be compiled with -fcrash-diagnostics=all -gen-reproducer, which outputs the full preprocessed file used for compilation and a script to run compilation of the file. Files are in the below gist, which reproduce the clang infinite loop when building ReduceOpsKernel.cpp.
> 
> https://gist.github.com/derekelewis/98e53d533250b00da76e38369093c70f

Hi @derekelewis , thanks for filling the issue. The issue has been fixed in the `clang` toolchain and will be part of upcoming clang release. I will update here with the version number when the build is ready to go out.

**Comment by derekelewis** [comment]
@kulinseth Xcode 15 Beta 6 appears to have fixed this. I will close this now. Thanks!
