### ISSUE TITLE
[FSDP] ValueError: `FlatParameter` requires uniform `requires_grad`

### ISSUE THREAD

**Issue by ChrisLiu6** [pytorch/pytorch#104690]
### 🐛 Describe the bug

Hi! I am trying to wrap a transformer model with `torch.distributed.fsdp.FullyShardedDataParallel`. Since I am working with the PEFT setting, in each Attention or FFN layer, there exist both `requires_grad=True` and `requires_grad=False` parameters.  When I try to wrap the model with FSDP, the following ERROR occurs: 
``` bash
ValueError: `FlatParameter` requires uniform `requires_grad`
```

The following is a minimal example to reproduce the error:
``` python
# test.py
import os
import functools

import torch
import torch.nn as nn

from torch.distributed.fsdp import (
    FullyShardedDataParallel as FSDP,
    MixedPrecision,
    ShardingStrategy,
)
from torch.distributed.fsdp.wrap import (
    transformer_auto_wrap_policy,
)

torch.distributed.init_process_group(backend='nccl', init_method="env://",
                                     world_size=int(os.environ['WORLD_SIZE']), rank=int(os.environ["RANK"]))
torch.cuda.set_device(int(os.environ["RANK"]))
torch.distributed.barrier()

class Attention(nn.Module):
    def __init__(self):
        super().__init__()
        self.q = nn.Linear(100, 100)

        self.k_nograd = nn.Linear(100, 100)
        for param in self.k_nograd.parameters():
            param.requires_grad=False

class FFN(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(100, 100)

        self.linear_nograd = nn.Linear(100, 100)
        for param in self.linear_nograd.parameters():
            param.requires_grad=False


class TransformerBlock(nn.Module):
    def __init__(self):
        super().__init__()
        self.attn = Attention()
        self.ffn = FFN()


model = TransformerBlock()

model = FSDP(
    model,
    auto_wrap_policy=functools.partial(
        transformer_auto_wrap_policy,
        transformer_layer_cls=[Attention, FFN],
    ),
    limit_all_gathers=True,
    use_orig_params=True,
    sync_module_states=True,
    mixed_precision=MixedPrecision(
        param_dtype=torch.bfloat16,
        reduce_dtype=torch.bfloat16,
        buffer_dtype=torch.bfloat16,
    ),
    sharding_strategy=ShardingStrategy.SHARD_GRAD_OP,
    device_id=torch.cuda.current_device(),
    ignored_parameters=[param for param in model.parameters() if not param.requires_grad]
)


```
``` bash
# bash
torchrun --nproc_per_node=2 test.py
```

I assume this error is related to https://github.com/pytorch/pytorch/issues/91167, but I've already set `use_orig_params=True`. I also find that the model can be successfully wrapped when set 
```python
    auto_wrap_policy=functools.partial(
        transformer_auto_wrap_policy,
        transformer_layer_cls=[],
    ),
```
so I think this could be related to the `transformer_auto_wrap_policy`.

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000
GPU 4: NVIDIA RTX A6000
GPU 5: NVIDIA RTX A6000
GPU 6: NVIDIA RTX A6000
GPU 7: NVIDIA RTX A6000

Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-254
Off-line CPU(s) list:            255
Thread(s) per core:              1
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7H12 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1495.041
CPU max MHz:                     2600.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        5199.79
Virtualization:                  AMD-V
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-15,128-143
NUMA node1 CPU(s):               16-31,144-159
NUMA node2 CPU(s):               32-47,160-175
NUMA node3 CPU(s):               48-63,176-191
NUMA node4 CPU(s):               64-79,192-207
NUMA node5 CPU(s):               80-95,208-223
NUMA node6 CPU(s):               96-111,224-239
NUMA node7 CPU(s):               112-127,240-254
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] open-clip-torch==2.20.0
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl    defaults
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342    defaults
[conda] mkl-service               2.4.0           py310h5eee18b_1    defaults
[conda] mkl_fft                   1.3.6           py310h1128e8f_1    defaults
[conda] mkl_random                1.2.2           py310h1128e8f_1    defaults
[conda] numpy                     1.24.3          py310h5f9d8c6_1    defaults
[conda] numpy-base                1.24.3          py310hb5e798b_1    defaults
[conda] open-clip-torch           2.20.0                   pypi_0    pypi
[conda] pytorch                   2.0.1           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2               py310_cu117    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.2              py310_cu117    pytorch

cc @zhaojuanmao @mrshenli @rohan-varma @awgu

**Comment by awgu** [comment]
Thanks for submitting this issue! We are actively investigating how to improve our parameter-efficient fine-tuning support.

For now, here are a few comments:
- If you want to avoid the `ValueError` with `use_orig_params=True`, you will need to use a nightly release since the change  (https://github.com/pytorch/pytorch/pull/98221) was not part of the 2.0.1 release.
- If you pass the frozen parameters to `ignored_parameters`, then FSDP will not shard them. That may not be the behavior you want.
    - JFYI, we removed the `ignored_parameters` constructor argument and replaced it with `ignored_states`.
    https://github.com/pytorch/pytorch/blob/8d65635378b828b4272cddbcc6c9f99be6e06146/torch/distributed/fsdp/fully_sharded_data_parallel.py#L361
- Even if you use `use_orig_params=True` on the nightly release, you will see unexpectedly high memory usage. This is because the gradient memory will still be as if you did not freeze parameters (as a limitation of our flat parameter design).
- What you can try is to do something like the following for now:
```
def lambda_fn(module: nn.Module):
    if isinstance(module, (Attention, FFN)):
        return True  # like transformer_auto_wrap_policy
    if isinstance(module, nn.Linear) and all(p.requires_grad for p in module.parameters()):
        return True  # wrap each trainable linear separately
    return False
auto_wrap_policy = functools.partial(lambda_auto_wrap_policy, lambda_fn=lambda_fn)
model = FSDP(model, ..., auto_wrap_policy=auto_wrap_policy)
```

**Comment by ChrisLiu6** [comment]
> Thanks for submitting this issue! We are actively investigating how to improve our parameter-efficient fine-tuning support.
> 
> For now, here are a few comments:
> 
> * If you want to avoid the `ValueError` with `use_orig_params=True`, you will need to use a nightly release since the change  ([[FSDP] Allow non-uniform `requires_grad` for `use_orig_params=True` #98221](https://github.com/pytorch/pytorch/pull/98221)) was not part of the 2.0.1 release.
> * If you pass the frozen parameters to `ignored_parameters`, then FSDP will not shard them. That may not be the behavior you want.
>   
>   * JFYI, we removed the `ignored_parameters` constructor argument and replaced it with `ignored_states`.
>     https://github.com/pytorch/pytorch/blob/8d65635378b828b4272cddbcc6c9f99be6e06146/torch/distributed/fsdp/fully_sharded_data_parallel.py#L361
> * Even if you use `use_orig_params=True` on the nightly release, you will see unexpectedly high memory usage. This is because the gradient memory will still be as if you did not freeze parameters (as a limitation of our flat parameter design).
> * What you can try is to do something like the following for now:
> 
> ```
> def lambda_fn(module: nn.Module):
>     if isinstance(module, (Attention, FFN)):
>         return True  # like transformer_auto_wrap_policy
>     if isinstance(module, nn.Linear) and all(p.requires_grad for p in module.parameters()):
>         return True  # wrap each trainable linear separately
>     return False
> auto_wrap_policy = functools.partial(lambda_auto_wrap_policy, lambda_fn=lambda_fn)
> model = FSDP(model, ..., auto_wrap_policy=auto_wrap_policy)
> ```


Thanks for your reply! It solves my problem.
Just still a bit confused about "passing the frozen parameters to ignored_parameters may not be the behavior I want". I thought that, now that the frozen parameters do not incur the costly optimizer states & gradients to save in memory, I may prefer to 
always hold a complete (unshared) version of the parameters in each rank to avoid the communication cost in each iteration. Is my understanding wrong? If it is, in what condition should I use the `ignored_states` argument? Thanks!

**Comment by awgu** [comment]
>  I thought that, now that the frozen parameters do not incur the costly optimizer states & gradients to save in memory, I may prefer to
always hold a complete (unshared) version of the parameters in each rank to avoid the communication cost in each iteration. Is my understanding wrong?

I think if holding the full unsharded parameters in GPU memory is tolerable, then passing them to `ignored_states` is okay. However, I would be careful on whether doing so is actually okay. Let us try do some back-of-the-envelope calculation.

---

- Assuming an optimizer like Adam that requires 2x optimizer states per parameter, the model memory is normally **4x** the parameter memory (1x from parameters, 1x from gradients, and 2x from the optimizer states).
- If only **10%** of your model parameters are trainable, then you expect this to decrease to **1.3x** (1x from parameters, 0.1x from gradients, and 0.2x from optimizer states).
- If you use FSDP, then ideally you shard this 1.3x over your GPUs. Assuming **8** GPUs, maybe you end up with **~0.3x** (giving some buffer for all-gathering and intermediates etc.).
- However, if you do not shard the model parameters (like you propose), then you end up with something like **1.1x** because you only shard the gradients/optimizer states, which are already reduced from have only 10% of the model being trainable. In that case, FSDP is not doing much.

Given the existing FSDP design there are a few things to note:
- For `use_orig_params=False`, you must wrap frozen parameters separately. (I have a PR open to improve the error messaging here.)
- For `use_orig_params=True`, you _can_ wrap frozen parameters with non-frozen parameters together, but you will use gradient memory equivalent to not freezing any parameters.
    - Let us revisit our example for this case. We would end up with **~0.43x** memory (0.1 * 2x / 8 = 0.025x for optimizer states; 1x parameters -> ~0.2x after sharding over 8 GPUs; and 1x gradients -> ~0.2x after sharding over 8 GPUs). This is still less memory than not sharding the model parameters (though it requires more communication).

---

In summary:
- For max memory savings, we should prefer to wrap frozen parameters separately (e.g. to get closer to the ~0.3x model-state memory usage).
- If we absolutely cannot, we can use `use_orig_params=True` and pay the cost of higher gradient memory usage (e.g. to still get ~0.43x memory usage).
- If we can afford to not shard the model parameters (e.g. using ~1.1x memory), then we may follow your approach of ignoring the frozen parameters to save on FSDP communication.


Let me know if anything is confusing or if I made a mistake somewhere!

**Comment by ChrisLiu6** [comment]
> > I thought that, now that the frozen parameters do not incur the costly optimizer states & gradients to save in memory, I may prefer to
> > always hold a complete (unshared) version of the parameters in each rank to avoid the communication cost in each iteration. Is my understanding wrong?
> 
> I think if holding the full unsharded parameters in GPU memory is tolerable, then passing them to `ignored_states` is okay. However, I would be careful on whether doing so is actually okay. Let us try do some back-of-the-envelope calculation.
> 
> * Assuming an optimizer like Adam that requires 2x optimizer states per parameter, the model memory is normally **4x** the parameter memory (1x from parameters, 1x from gradients, and 2x from the optimizer states).
> * If only **10%** of your model parameters are trainable, then you expect this to decrease to **1.3x** (1x from parameters, 0.1x from gradients, and 0.2x from optimizer states).
> * If you use FSDP, then ideally you shard this 1.3x over your GPUs. Assuming **8** GPUs, maybe you end up with **~0.3x** (giving some buffer for all-gathering and intermediates etc.).
> * However, if you do not shard the model parameters (like you propose), then you end up with something like **1.1x** because you only shard the gradients/optimizer states, which are already reduced from have only 10% of the model being trainable. In that case, FSDP is not doing much.
> 
> Given the existing FSDP design there are a few things to note:
> 
> * For `use_orig_params=False`, you must wrap frozen parameters separately. (I have a PR open to improve the error messaging here.)
> * For `use_orig_params=True`, you _can_ wrap frozen parameters with non-frozen parameters together, but you will use gradient memory equivalent to not freezing any parameters.
>   
>   * Let us revisit our example for this case. We would end up with **~0.43x** memory (0.1 * 2x / 8 = 0.025x for optimizer states; 1x parameters -> ~0.2x after sharding over 8 GPUs; and 1x gradients -> ~0.2x after sharding over 8 GPUs). This is still less memory than not sharding the model parameters (though it requires more communication).
> 
> In summary:
> 
> * For max memory savings, we should prefer to wrap frozen parameters separately (e.g. to get closer to the ~0.3x model-state memory usage).
> * If we absolutely cannot, we can use `use_orig_params=True` and pay the cost of higher gradient memory usage (e.g. to still get ~0.43x memory usage).
> * If we can afford to not shard the model parameters (e.g. using ~1.1x memory), then we may follow your approach of ignoring the frozen parameters to save on FSDP communication.
> 
> Let me know if anything is confusing or if I made a mistake somewhere!

Thank you sooooooooo much for your detailed explanation!! It is very helpful and has cleared up all my confusion. Thank you very much!

**Comment by awgu** [comment]
@samar-khanna 
I think if you cannot change the module, then your best bet is to apply `FullyShardedDataParallel` to `LoRALinear` with `use_orig_params=True`. You will use more gradient memory, but otherwise, things should still work.

**Comment by awgu** [comment]
We are working on a new FSDP that would address this issue more fundamentally. E.g., in @samar-khanna 's case, we can apply FSDP to `LoRALinear` _and_ use the expected amount of memory.

Example unit test:
https://github.com/pytorch/pytorch/blob/58047205ed098c04ec045e66fc39dcc70b60600b/test/distributed/_composable/fsdp/test_fully_shard_frozen.py#L36

**Comment by Sunrise1111** [comment]
> We are working on a new FSDP that would address this issue more fundamentally. E.g., in @samar-khanna 's case, we can apply FSDP to `LoRALinear` _and_ use the expected amount of memory.
> 
> Example unit test:
> 
> https://github.com/pytorch/pytorch/blob/58047205ed098c04ec045e66fc39dcc70b60600b/test/distributed/_composable/fsdp/test_fully_shard_frozen.py#L36

Hello, may I ask which version supports this capability? I encountered this problem in 2.0.1

**Comment by awgu** [comment]
@Sunrise1111 For addressing this error in existing FSDP, you want a newer version, e.g. >= 2.2. For the new FSDP, you want the latest nightlies.
