### ISSUE TITLE
MacOS Sonoma Beta bus error w/ MPS & M2

### ISSUE THREAD

**Issue by derekelewis** [pytorch/pytorch#104642]
### 🐛 Describe the bug

SIGBUS received on MacOS Sonoma Beta 2 on a MacBook Pro M2 with stable, nightly & source build from HEAD. Does not occur on my MacBook Pro M1. 

Reproducible when running ```python test/test_mps.py```:

```
loc("mps_select"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/fe2afe83-06e7-11ee-80c3-f6357a1003e8/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":294:0)): error: 'anec.gain_offset_control' op result #0 must be 4D/5D memref of 16-bit float or 8-bit signed integer or 8-bit unsigned integer values, but got 'memref<1x5x1x5xi1>'
loc("mps_select"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/fe2afe83-06e7-11ee-80c3-f6357a1003e8/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":294:0)): error: 'anec.gain_offset_control' op result #0 must be 4D/5D memref of 16-bit float or 8-bit signed integer or 8-bit unsigned integer values, but got 'memref<5x10x1x5xi1>'
...../Users/dlewis/miniconda3/envs/pytorchnightly/lib/python3.11/site-packages/torch/autograd/__init__.py:319: UserWarning: An output with one or more elements was resized since it had shape [], which does not match the required output shape [1]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /Users/dlewis/work/repos/third-party/pytorch/pytorch/aten/src/ATen/native/Resize.cpp:35.)
  result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
...........x.........................xx..x...x.xxxxxx....xx..xx...xx.....ssssxxxxxxxxxxx..xx..xx......./Users/dlewis/miniconda3/envs/pytorchnightly/lib/python3.11/site-packages/torch/testing/_internal/opinfo/core.py:1107: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at /Users/dlewis/work/repos/third-party/pytorch/pytorch/aten/src/ATen/native/Convolution.cpp:1012.)
  return self.op(*args, **kwargs)
...x....zsh: bus error  python test_mps.py
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gitc00dd43
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.0 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.29.1)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.11.3 (main, May 15 2023, 18:01:31) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.0
[pip3] torch==2.1.0a0+gitc00dd43
[conda] numpy                     1.25.0                   pypi_0    pypi
[conda] torch                     2.1.0a0+gitc00dd43           dev_0    <develop>

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by derekelewis** [comment]
Reproduced on Beta 3 that was released today for both stable and HEAD.

**Comment by Guido-Hwang** [comment]
same in tensorflow
