### ISSUE TITLE
tensor.random_(0) cause `core dumped`

### ISSUE THREAD

**Issue by chenyuntc** [pytorch/pytorch#1046]
I was using IPython to debug, but when I type below it causes exception and exit ipython directly.
```ipython
In [1]: import torch

In [2]: a = torch.Tensor(3)

In [3]: a.random_(0)
[1]    29993 floating point exception (core dumped)  ipython2

```
I think it would be better if pytorch could raise error like below rather than exit directly.
```
RuntimeError: upper bound must be greater or equal than lower bound 
```

**Comment by vadimkantorov** [comment]
Also, the [doc](http://pytorch.org/docs/tensors.html?highlight=random_#torch.Tensor.random_) is a bit confusing about multiple dispatch. Calling `random_(5)` will be equivalent `random_(to=5)`, not to `random_(generator=5)`. Though not sure how important it is.
