### ISSUE TITLE
F.scaled_dot_product_attention explanation code not working

### ISSUE THREAD

**Issue by maxjeblick** [pytorch/pytorch#104652]
### 📚 The doc issue

When looking into the documentation of [scaled_dot_product_attention](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html), the corresponding equivalent python code is not working as expected. In particular, the code
```
L = 10
S = 10
attn_mask = torch.ones(L, S, dtype=torch.bool).tril(diagonal=0).bool()
attn_mask = attn_mask.masked_fill(not attn_mask, -float('inf')) if attn_mask.dtype==torch.bool else attn_mask
```
gives `RuntimeError: Boolean value of Tensor with more than one value is ambiguous`. I also noticed the return statement below, which is minor, however.

### Suggest a potential alternative/fix

Implement a working example that implements/gives a simplified approximation for `F.scaled_dot_product_attention`. This may be useful for debugging.

cc @svekars @carljparker

**Comment by vadimkantorov** [comment]
- `not attn_mask` should probably be `~attn_mask`
- also maybe `.bool()` is not needed

i wonder if it's a good idea to have `tril`/`triu` to accept a fill value (0 by default) to make this pattern more idiomatic

**Comment by janeyx99** [comment]
cc @drisspg

**Comment by drisspg** [comment]
An example reference implemntation could look like 
```

def ref_attention(
    query, key, value, is_causal, attn_mask=None, dropout_p=0.0, scale=None
):
    scale = 1 / math.sqrt(math.sqrt(query.size(-1))) if scale is None else scale
    query *= scale
    key *= scale
    attn_weights = torch.matmul(query, key.transpose(-2, -1))
    if is_causal:
        assert attn_mask is None
        temp_mask = (
            torch.ones((query.shape[-2], key.shape[-2]), device=query.device)
            .tril_()
            .bool()
        )
        mask = torch.zeros_like(temp_mask, dtype=query.dtype)
        mask.masked_fill_(temp_mask.logical_not(), float("-inf"))
        attn_weights.add_(mask)

    if attn_mask is not None:
        attn_weights.add_(attn_mask)
    attn_weights = torch.softmax(attn_weights, dim=-1)
    attn_weight = torch.dropout(attn_weight, dropout_p)
    return torch.matmul(attn_weights, value)
```

I will put up a PR to fix the docs to do logical not and remove the return value

**Comment by drisspg** [comment]
My PR makes the code runnable but is for sure not the source of truth on the refernce implementation. For that I would suggest looking at the math implementation:

https://github.com/pytorch/pytorch/blob/d64bada876d007344359bf740a0e49e4def19a97/aten/src/ATen/native/transformers/attention.cpp#L639

**Comment by maxjeblick** [comment]
Awesome thanks! A more verbose python implementation that does not need to match the reference implementation 100% should be fine.

**Comment by mikekgfb** [comment]
> * `not attn_mask` should probably be `~attn_mask`
> * also maybe `.bool()` is not needed
> 
> i wonder if it's a good idea to have `tril`/`triu` to accept a fill value (0 by default) to make this pattern more idiomatic (even if in "reference" implementations): #97892

https://github.com/pytorch/pytorch/pull/101487 defines a function _generate_square_subsequent_mask (which already exists as a static member of Transformer, but that call can't be torchscripted... oh, the joys of torchscript).  We could promote that function to functional.py (sans _) and avoid future everybody having to code their own.

Bonus points - this new flavor of the old has both dtype and device factory args to conjure up "just the right mask at the right place" at the right time.  (That PR needs some reviewing love.)
