### ISSUE TITLE
AttributeError: 'ReduceLROnPlateau' object has no attribute 'get_last_lr'

### ISSUE THREAD

**Issue by ani-bg** [pytorch/pytorch#104687]
### 🐛 ReduceLROnPlateau and many other LRScheduler subclasses do not call super class constructor 
as follows,

```Python,
super().__init__(optimizer, last_epoch, verbose) 
```

As a result, they are not inheriting many base class functionalities like `get_last_lr`.  Hence, calling this function gives following error:

```
AttributeError: 'ReduceLROnPlateau' object has no attribute 'get_last_lr'
```

Calling the superclass constructor should solve the issue in these classes.

cc @vincentqb @jbschlosser @albanD @janeyx99

**Comment by janeyx99** [comment]
We would accept a fix for this!

**Comment by ani-bg** [comment]
I'll work on it!

**Comment by janeyx99** [comment]
Ah! Sorry I had not seen your message--would you still like to work on it? Note that fixing this issue will also fix https://github.com/pytorch/pytorch/issues/106767 which explains more deeply why this was the case in the first place and there may be certain caveats to consider. Let's continue further discussion there to consolidate everything into one place!
