### ISSUE TITLE
torch.compile fails with "INTERNAL ASSERT FAILED" when compiling GPT-2

### ISSUE THREAD

**Issue by nipunagarwala** [pytorch/pytorch#104610]
### 🐛 Describe the bug

I am trying an experiment to run the open source GPT-2 model in pytorch through torch.compile to get an optimized, fused graph and them examine that.
On doing so, I get internal assertions firing which ask me to report the bug to pytorch.
Could someone help explain why the bug is firing, and if so, what a workaround would be?

```python
import torch
from torch.fx.experimental.proxy_tensor import make_fx
from torch.fx.experimental.symbolic_shapes import ShapeEnv
from torch._inductor.compile_fx import compile_fx_inner

import torch.fx as fx
from torch._subclasses import FakeTensorMode

import onnx
from onnx import numpy_helper
from transformers import GPT2Model, GPT2LMHeadModel, GPT2Tokenizer


def flatten(inputs):
    return [[flatten(i) for i in inputs] if isinstance(inputs, (list, tuple)) else inputs]


device = torch.device("cuda")
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2Model.from_pretrained('gpt2')
model = model.to(device)
input_ids_1 = torch.tensor(
	[[tokenizer.encode("Here is some text to encode Hello World", add_special_tokens=True)]], device='cuda')

input_names = None
inputs_flatten = flatten(input_ids_1)
if input_names is None:
	input_names = []
	for i, _ in enumerate(inputs_flatten):
		input_names.append('input' + str(i+1))


opt_model = torch.compile(model, mode='max-autotune', fullgraph=True)
torch.onnx.export(opt_model, input_ids_1, "./", verbose=True, input_names=input_names,
			  operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)

```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: list_trace[idx] == nullptr INTERNAL ASSERT FAILED at "../torch/csrc/jit/frontend/tracer.cpp":1016, please report a bug to PyTorch. 
```


### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230701+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4080
Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Stepping:                        9
CPU MHz:                         4200.000
CPU max MHz:                     4500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        8400.00
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+440fd1bf20
[pip3] torch==2.1.0.dev20230701+cu121
[pip3] torchaudio==2.1.0.dev20230702+cu121
[pip3] torchvision==0.16.0.dev20230702+cu121
[pip3] triton==2.0.0
[conda] Could not collect

```
cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by davidradl** [comment]
I do not get this error when running this code using a cpu. It fails in the export for me.

I see the pytorch code does 

```
  AT_ASSERT(idx < list_trace.size());
  AT_ASSERT(list_trace[idx] == nullptr);
```
your error is failing on the second assert. 

My thoughts are:
This function is given a size and an index, and the index can be less than the size. The second assert seems to be assuming that list_trace elements would be from 0 to idx-1 and that attempting to address the element at idx would null pointer.  But if the index idx can be less than the size, then I assume there are indexable elements up to size, so addressing element at idx will not nullptr - if so then this assert should be removed as it does not make sense.

**Comment by nipunagarwala** [comment]
My thought is this assert might be firing on GPUs too because of the same reason you mentioned.
GPUs might have more kernel fusion and compiler optimizations than CPUs, leading to more graph modifications during the trace.

Do you think that is possible?
How do we double check your hypothesis and rerun?

**Comment by davidradl** [comment]
@nipunagarwala the easiest test would be to remove the assert and test to see at least if this test scenario works. I guess addressing past the end of a valid object could give a malicious user access to content they should not have access to. I think the assert should be changed to  `AT_ASSERT(list_trace[size] == nullptr);` which would police this sort of malicious scenario.
I have not got easy access to a GPU environment, can you make this change and test locally? It would be good to know if it fails later - especially in a related way.

**Comment by nipunagarwala** [comment]
@davidradl  So I ran the above code on a GPU, removed the assert, and rebuilt PyTorch. I then hit the following

    lambda: torch.empty_strided(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: size == list_trace.size() INTERNAL ASSERT FAILED at "/home/nipunagarwala/Documents/BlackwellNext/pytorch/torch/csrc/jit/frontend/tracer.cpp":1014, please report a bug to PyTorch. 

Looks like there is something more intrinsic in the pytorch that is being flagged.

**Comment by nipunagarwala** [comment]
As an experiment, I commented out the following asserts just to see what happens.
```
  AT_ASSERT(size == list_trace.size());
  AT_ASSERT(idx < list_trace.size());
  AT_ASSERT(list_trace[idx] == nullptr);
```
I end up getting the following error:

```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: 0 INTERNAL ASSERT FAILED at "/home/nipunagarwala/pytorch/aten/src/ATen/core/boxing/KernelFunction.cpp":14, please report a bug to PyTorch. fallthrough_kernel was executed but it should have been short-circuited by the dispatcher. This could occur if you registered a fallthrough kernel as a override for a specific operator (as opposed to a backend fallback); this is NOT currently supported, and we do not intend to add support for it in the near future.  If you do find yourself in need of this, let us know in the bug tracker.
```

Not sure why torch.onnx.export is not liking the export. I thought OperatorExportTypes.ONNX_ATEN_FALLBACK took care of the concern, but looks like now.

**Comment by justinchuby** [comment]
@BowenBao @thiagocrepaldi an attempt to export a `torch.compile`ed model to onnx?

**Comment by nipunagarwala** [comment]
@thiagocrepaldi Are we able to export any optimized models?
I was hoping to do symbolic analysis, do automatic graph transformations (like torch.compile) using make_fx and then export them.
At least, is it possible to visualize the optimized graph using Netron or some other popular visualization app?

**Comment by thiagocrepaldi** [comment]
> @thiagocrepaldi Are we able to export any optimized models? I was hoping to do symbolic analysis, do automatic graph transformations (like torch.compile) using make_fx and then export them. At least, is it possible to visualize the optimized graph using Netron or some other popular visualization app?

Not with `torch.onnx.export`. It is not meant to be used with `make_fx`, `torch.compile`, `torch.export` or any other Dynamo API. This is a by design limitation because `torch.onnx.export` is based on `TorchScript` graphs while `torch.compile` and `torch.export` are based on FX `GraphModule` graphs. FX graphs are meant to replace `TorchScript`, not to augment each other.

`torch.onnx.dynamo_export` on the other hand does call `torch._dynamo.export` (similar to `torch.export`) and does handle FX graphs. We will provide APIs to allow users to optimize both the FX and ONNX graphs, but that should come officially with PyTorch 2.1

**Comment by thiagocrepaldi** [comment]
As mentioned before, `torch.onnx.export` was not designed to support neither `torch.compile` or `torch.export`. There is no plan to add such support as well

However, the proposed model can be exported to onnx using `torch.onnx.dynamo_export` which is compatible with `torch.export`

Here is the repro

```python
import torch
from torch.fx.experimental.proxy_tensor import make_fx
from torch.fx.experimental.symbolic_shapes import ShapeEnv
from torch._inductor.compile_fx import compile_fx_inner

import torch.fx as fx
from torch._subclasses import FakeTensorMode

import onnx
from onnx import numpy_helper
from transformers import GPT2Model, GPT2LMHeadModel, GPT2Tokenizer


def flatten(inputs):
    return [[flatten(i) for i in inputs] if isinstance(inputs, (list, tuple)) else inputs]


device = torch.device("cuda")
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2Model.from_pretrained('gpt2')
model = model.to(device)
input_ids_1 = torch.tensor(
	[[tokenizer.encode("Here is some text to encode Hello World", add_special_tokens=True)]], device='cuda')

input_names = None
inputs_flatten = flatten(input_ids_1)
if input_names is None:
	input_names = []
	for i, _ in enumerate(inputs_flatten):
		input_names.append('input' + str(i+1))

torch.onnx.dynamo_export(model, input_ids_1, export_options=torch.onnx.ExportOptions(dynamic_shapes=True)).save("gpt2.onnx")
```

The ONNX file look like

<img width="1017" alt="image" src="https://github.com/pytorch/pytorch/assets/5469809/f2c7e128-e465-41c9-9d28-82dd74baf6db">

**Comment by mlazos** [comment]
@nipunagarwala is your issue resolved?

**Comment by MaanavD** [comment]
Hey @nipunagarwala ,

I've gone ahead and closed the issue as we haven't heard back from you in a while! Feel free to reopen the issue if necessary.
