### ISSUE TITLE
How to integrate the new cpp file with Pytorch geometroic?

### ISSUE THREAD

**Issue by shivanisankhyan** [pytorch/pytorch#104617]
### 🚀 The feature, motivation and pitch

I am using neighbour loader function in my code, which uses sample_adj_cpu function to sample neighbours. I am making some changes in this function which is present in the following file. 

File link:
[[pytorch_sparse](https://github.com/rusty1s/pytorch_sparse/tree/master)/[csrc](https://github.com/rusty1s/pytorch_sparse/tree/master/csrc)/[cpu](https://github.com/rusty1s/pytorch_sparse/tree/master/csrc/cpu)
/sample_cpu.cpp](url) 

How to integrate these changes in Pytorch geometric?

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by amjames** [comment]
Closing this as a duplicate of #104764
