### ISSUE TITLE
Export ONNX model with custom op in Pytorch 2.0 raises AttributeError: ‘function’ object has no attribute ‘to_function_proto’

### ISSUE THREAD

**Issue by GPhilo** [pytorch/pytorch#104700]
### 🐛 Describe the bug

Exporting a model using a custom op by following the instructions in the [torch.onnx guide](https://pytorch.org/docs/stable/onnx.html) fails with an AttributeError (full traceback below).

Sample code reproducing the issue:

Requirement: `pip install pytorch-scatter` (used just as a convenient way to provide a custom op that I know needs to be handled via a custom symbolic function)

```python
from torch_scatter import scatter_max
import torch

class MyModel(torch.nn.Module):
    def forward(self, src: torch.Tensor, idx: torch.Tensor):
        return scatter_max(src, idx)

m = MyModel().eval()
src = torch.ones([3,10], dtype=torch.float32)
idx = torch.randint(0, 4, [3, 10], dtype=torch.long)

def sym_scatter_max(g, src, index, dim, out, dim_size):
    return g.op(
                "torch_scatter::scatter_max",
                src,
                index,
                dim_size_i=-1,
                outputs=2
            )
torch.onnx.register_custom_op_symbolic('torch_scatter::scatter_max', sym_scatter_max, 1)

with torch.no_grad():
    torch.onnx.export(m, (src, idx), 'mymodel.onnx', verbose=False, opset_version=13, custom_opsets={'torch_scatter':1}, do_constant_folding=True)
```

Running this raises the following error:
```
Traceback (most recent call last):
  File "/myproject/sample_torch.py", line 23, in <module>
    torch.onnx.export(m, (src, idx), 'mymodel.onnx', verbose=False, opset_version=13, custom_opsets={'torch_scatter':1}, do_constant_folding=True)
  File "/myenvs/py310_torch2/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/myenvs/py310_torch2/lib/python3.10/site-packages/torch/onnx/utils.py", line 1620, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "/myenvs/py310_torch2/lib/python3.10/site-packages/torch/onnx/_internal/onnx_proto_utils.py", line 237, in _add_onnxscript_fn
    _find_onnxscript_op(
  File "/myenvs/py310_torch2/lib/python3.10/site-packages/torch/onnx/_internal/onnx_proto_utils.py", line 279, in _find_onnxscript_op
    onnx_function_list.append(onnx_fn.to_function_proto())  # type: ignore[attr-defined]
AttributeError: 'function' object has no attribute 'to_function_proto'
```

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: CentOS 7 (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)
Clang version: Could not collect
CMake version: version 3.25.2
Libc version: glibc-2.26

Python version: 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.247-168.349.amzn2int.x86_64-x86_64-with-glibc2.26
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.9.1
/usr/lib64/libcudnn_adv_infer.so.8.9.1
/usr/lib64/libcudnn_adv_train.so.8.9.1
/usr/lib64/libcudnn_cnn_infer.so.8.9.1
/usr/lib64/libcudnn_cnn_train.so.8.9.1
/usr/lib64/libcudnn_ops_infer.so.8.9.1
/usr/lib64/libcudnn_ops_train.so.8.9.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               79
Model name:          Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:            1
CPU MHz:             2700.869
CPU max MHz:         3000.0000
CPU min MHz:         1200.0000
BogoMIPS:            4600.02
Hypervisor vendor:   Xen
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            46080K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.0
[pip3] torch==2.0.1
[pip3] torch-scatter==2.1.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.6           py310h1128e8f_1  
[conda] mkl_random                1.2.2           py310h1128e8f_1  
[conda] numpy                     1.25.0          py310h5f9d8c6_0  
[conda] numpy-base                1.25.0          py310hb5e798b_0  
[conda] pytorch                   2.0.1           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-scatter             2.1.1                    pypi_0    pypi
[conda] torchaudio                2.0.2               py310_cu118    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.2              py310_cu118    pytorch

cc @ezyang @gchanan @zou3519

**Comment by carsonswope** [comment]
I am seeing this issue also. It is fixed by reverting to 1.13.1
