### ISSUE TITLE
Pytorch-CUDA 11.8 for Jetson AGX Orin

### ISSUE THREAD

**Issue by rahulswa08** [pytorch/pytorch#104778]
### 🐛 Describe the bug

Hello everyone,

I am working on a Jetson AGX orin 32GB platform with jetpack 5.1 installed. I have to updated CUDA on my jetson to 11.8 and updated all my settings to CUDA 11.8 using [link](https://developer.nvidia.com/blog/simplifying-cuda-upgrades-for-nvidia-jetson-users/)

I have checked the installation using `nvcc --version` which points to CUDA 11.8 and even the soft link to `/usr/local/cuda` and `/usr/local/cuda-11` are pointed to `/usr/local/cuda-11.8`

Now I installed pytorch using the instructions given [here](https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html)

When I type `torch.version.cuda` it outputs 11.4.  And I’m facing issues with this, because when I try to install `pytorch-3d`.  Because it says pytorch is build for CUDA-11.4 but pytorch-3d is trying to build for CUDA-11.8.

### Versions

Pytorch : torch-2.0.0+nv23.05-cp38-cp38-linux_aarch64.whl 
Jetpack : 5.1.1
Platform : Jetson AGX Orin 32GB

I’m not sure why I’m facing this issue.  Am I doing anything wrong here? or it this a limitation of this library?

Could anyone help me solve this issue?

Thanks!!

**Comment by jbschlosser** [comment]
Hey @rahulswa08, this sounds like it may be an environment issue. As such, I'll encourage you to post on the [PyTorch Forums](https://discuss.pytorch.org/), as you'll have more luck receiving assistance there. Note that the issues here are reserved for problems within PyTorch. Closing this issue for now, but if discussion on the forums indicates that there is a likely PyTorch bug, please feel free to reopen.
