### ISSUE TITLE
Subgraph matcher returned a false match

### ISSUE THREAD

**Issue by andrewor14** [pytorch/pytorch#104775]
I ran into a "bug" where the subgraph matcher returned a match, but the matched pattern doesn't actually exist in the original model. This resulted in the following error in subgraph rewriter:

```
  File "/home/andrewor/local/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/fx/subgraph_rewriter.py", line 218, in replace_pattern_with_filters
    return _replace_pattern(gm, pattern, replacement, match_filters, ignore_literals)
  File "/home/andrewor/local/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/fx/subgraph_rewriter.py", line 326, in _replace_pattern
    gn = match.nodes_map[node]
KeyError: div__scalar
```

Matched pattern looks like this (doesn't exist in the original model):
```
def forward(self, x):
    arg0, = fx_pytree.tree_flatten_spec(([x], {}), self._in_spec)
    empty_like_default = torch.ops.aten.empty_like.default(arg0, memory_format = torch.contiguous_format)
    bernoulli__float = torch.ops.aten.bernoulli_.float(empty_like_default);  empty_like_default = None
    div__scalar = torch.ops.aten.div_.Scalar(bernoulli__float, 0.5);  bernoulli__float = None
    mul_tensor = torch.ops.aten.mul.Tensor(arg0, div__scalar);  arg0 = div__scalar = None
    return pytree.tree_unflatten([mul_tensor], self._out_spec)
```

Returned nodes map looks like this (doesn't look the same as the match pattern above):

```
NODES MAP: 
   mul_tensor :  mul_tensor
   arg0 :  arg0
```

For more detail, see P784006912.

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by angelayi** [comment]
Update: it's because the `ignore_literals` flag is on. 

A smaller example is:
```
def orig_graph(x):
    return add(x, 1)

def pattern_graph(x):
    a = mul(a, x)
    return add(x, a)
```

Because we ignore literals, it checks the `1` with `a` and just returns true and finishes matching.

Probably we should only ignore literals from the pattern graph? I haven't fully thought this out

**Comment by mlazos** [comment]
@andrewor14 is this resolved?

**Comment by mlazos** [comment]
Closing, since this seems resolved, feel free to reopen if needed.
