### ISSUE TITLE
How to integrate the new cpp file with Pytorch geometric? 

### ISSUE THREAD

**Issue by shivanisankhyan** [pytorch/pytorch#104764]
### 🚀 The feature, motivation and pitch

I am using neighbour loader function in my code, which uses sample_adj_cpu function to sample neighbours. I am making some changes in this function which is present in the following file.

File link:
[[pytorch_sparse](https://github.com/rusty1s/pytorch_sparse/tree/master)/[csrc](https://github.com/rusty1s/pytorch_sparse/tree/master/csrc)/[cpu](https://github.com/rusty1s/pytorch_sparse/tree/master/csrc/cpu)
/sample_cpu.cpp](url)

How to integrate these changes in Pytorch geometric?

Alternatives
No response

Additional context
No response

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by mikaylagawarecki** [comment]
It seems like you are trying to integrate a new file in `pytorch_sparse` library into `pytorch_geometric`. This issue should probably be filed in the `pytorch_geometric` library

**Comment by jbschlosser** [comment]
Closing for now but feel free to reopen if there is some need for a PyTorch core change.
