### ISSUE TITLE
Possible memory leak during training of compiled `timm` model

### ISSUE THREAD

**Issue by VarIr** [pytorch/pytorch#104773]
### 🐛 Describe the bug

We train classification models from latest `timm` on millions of images over multiple epochs.

Since upgrading to `torch>=2.0.0` and using `torch.compile()` we observe continually increasing main memory usage during training/validation: The process uses more RAM with each minibatch processed by the network, until we eventually get OOM errors. Memory profiling points to the `outputs = model(data)` call.
The same code without calling `torch.compile(model)` has approx. constant memory usage throughout the training loop.

We observe this issue for various architectures, whereas larger architectures appear to have a steeper memory increase over time. Below, I attach a script (modified transfer learning example from Pytorch tutorials) to reproduce this issue with a small network from timm as showcase (tinynet). 

[example.py.zip](https://github.com/pytorch/pytorch/files/11983258/example.py.zip)

### Error logs

(no error logs; memory usage increases until process is killed by OS due to OOM)

### Minified repro

(relevant here? Also, created .py is too large for this form...)

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Quadro RTX 8000
Nvidia driver version: 525.125.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   44 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          144
On-line CPU(s) list:             0-143
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7552 48-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              36
Socket(s):                       2
Stepping:                        0
BogoMIPS:                        4391.78
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves xsaveerptr virt_ssbd arat rdpid
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       2.3 MiB (72 instances)
L1i cache:                       2.3 MiB (72 instances)
L2 cache:                        36 MiB (72 instances)
L3 cache:                        32 MiB (2 instances)
NUMA node(s):                    3
NUMA node0 CPU(s):               0-47
NUMA node1 CPU(s):               48-95
NUMA node2 CPU(s):               96-143
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.0
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] numpy                     1.25.0          py310ha4c1d20_0    conda-forge
[conda] pytorch                   2.0.1           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.2              py310_cu117    pytorch

#### Manually added by OP
timm==0.9.2

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by eellison** [comment]
cc @Chillee you fixed a similar issue, right ?  @VarIr could you try seeing if you can repro this on a nightly build ?

**Comment by VarIr** [comment]
@eellison Thanks for the quick reply. Indeed it seems this is already fixed in `'2.1.0.dev20230707+cu118'`.

**Comment by Chillee** [comment]
Yes this was the relevant issue: https://github.com/pytorch/pytorch/issues/96937
