### ISSUE TITLE
Inductor codegen error: AttributeError("'constexpr' object has no attribute 'type'") - HuggingFace llama

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#104759]
### 🐛 Describe the bug

Repro script: https://gist.github.com/ezyang/321e9ab5ead6e5fdfecadbe5dfd4a963

Fails with:

```
triton.compiler.errors.CompilationError: at 18:39:    yoffset = tl.program_id(1) * YBLOCK
    yindex = yoffset + tl.arange(0, YBLOCK)[None, :]
    ymask = yindex < ynumel
    y2 = yindex
    x3 = xindex
    x0 = xindex % 4
    x1 = (xindex // 4)
    tmp12 = tl.load(in_ptr2 + (x0 + (4*y2) + (4800*x1)), xmask & ymask).to(tl.float32)
    tmp0 = y2
    tmp1 = 1000
    tmp2 = tmp0 < tmp1
    tmp3 = tl.broadcast_to(1, [XBLOCK, YBLOCK])
                                       ^
AttributeError("'constexpr' object has no attribute 'type'")
```

Repro was extracted from https://github.com/fxmarty/accelerated-pytorch-transformers-generation/pull/14

### Versions

main

cc @gchanan @zou3519 @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by Chillee** [comment]
Issue is that Triton doesn't support `tl.broadcast_to(1, [XBLOCK, YBLOCK])`.

We generate it here: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/codegen/triton.py#L1055

So, we have a check right above it that's supposed to catch this case, but in this case, `index_str` was 1, but `index` was `(x3//16) + 1`, which after simplification becomes 1. 

Right solution is probably to add a simplify_indexing here
![image](https://github.com/pytorch/pytorch/assets/6355099/3629c584-3a07-485f-a3d0-5ad97e962b7e)

**Comment by ezyang** [comment]
This fix works
