### ISSUE TITLE
[conda] Older PyTorch versions (<1.5.1) no longer available on PyTorch's conda channel

### ISSUE THREAD

**Issue by nickfraser** [pytorch/pytorch#104754]
Not sure if this issue is a duplicate but I tried searching for issues on both the PyTorch and Torchvision repos and couldn't find anything. I'm guessing this is intentional and was done for reasons not apparent to me, but I'm creating this issue in the hope that this was somehow an oversight. It appears that the `pytorch` channel on conda has deleted `pytorch` packages that are older than [v1.5.1](https://anaconda.org/pytorch/pytorch/files) and `torchvision` packages that are older than [v0.6.1](https://anaconda.org/pytorch/torchvision/files). I'm hoping these older releases can be restored as I personally have several projects (for example, [logicnets](https://github.com/Xilinx/logicnets/)) based on these older versions, which I know can reproduce results from several papers.

Unfortunately, this means that following basic instructions for "getting started" for older PyTorch versions on the [PyTorch website](https://pytorch.org/get-started/previous-versions/#v140) fail.

For example:

```
conda create -n pt1.4 pytorch==1.4.0 torchvision==0.5.0 cpuonly -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - torchvision==0.5.0

Current channels:

  - https://conda.anaconda.org/pytorch/linux-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Note, a `pytorch` package is found from Anaconda's `main` channel, but one doesn't appear to exist from the `pytorch` channel.

I haven't tried installing these older versions from `pip`, but I suspect that they would work and that it would workaround this issue.

**Comment by nickfraser** [comment]
See [this comment](https://github.com/pytorch/vision/issues/7725#issuecomment-1624983948) for the likely culprit and potential future solution.

**Comment by jbschlosser** [comment]
Closing this issue to consolidate conversation on the other thread.
