### ISSUE TITLE
Add support for NEON ISA in the Inductor C++ backend

### ISSUE THREAD

**Issue by Rohanjames1997** [pytorch/pytorch#104729]
### 🚀 The feature, motivation and pitch

Context: The TorchInductor C++ backend currently supports vectorization in C++ Codegen through two Intel ISAs: AVX2 and AVX512, as mentioned in the [Update 5 Blog](https://dev-discuss.pytorch.org/t/torchinductor-update-5-cpu-backend-backend-performance-update-and-deep-dive-on-key-optimizations/1117#vectorization-in-c-codegen-4). While the Aten library does support Arm as well, we are yet to leverage its NEON/SVE ISAs to generate optimized kernels. The blog also [mentions](https://dev-discuss.pytorch.org/t/torchinductor-update-5-cpu-backend-backend-performance-update-and-deep-dive-on-key-optimizations/1117#vectorization-in-c-codegen-4:~:text=It%20can%20be,sub%2Dclasses.) that the VecISA class can be subclassed in order to support other ISAs.

Proposal: I am working on providing NEON ISA support for the TorchInductor's C++ backend. Particularly, I intend to provide a NEON implementation of the `vec_reduce_all()` function, which currently has optimized [AVX2 and AVX512 intrinsics implementations](https://github.com/pytorch/pytorch/blob/ced5c89b6fbe827a538b7ada96b2f9a5989871c7/aten/src/ATen/cpu/vec/functional_base.h#L37-L79) for x86 processors introduced by @mingfeima in #73953, as well as a [slow path](https://github.com/pytorch/pytorch/blob/ced5c89b6fbe827a538b7ada96b2f9a5989871c7/aten/src/ATen/cpu/vec/functional_base.h#L12-L28) implementation for other processors including Arm. I have implemented a NEON version for the function, wired up the Inductor's generated C++ to invoke this NEON path on Arm CPUs & I've seen performance improvements, particularly in the Softmax operation.

Posting this here for any discussion before raising a PR.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen @ngimel

**Comment by jgong5** [comment]
Thanks for the heads-up @Rohanjames1997 . The inductor C++ backend leverages `Vectorized` interface directly. So as long as there is NEON counterpart of `Vectorized` support, the enabling should be fairly straightforward. You mentioned you are going to add `vec_reduce_all()`, I guess it is for fp32? Besides that, are you going to support fp16 and bf16? If you can support the data type conversion between fp32 and fp16, or fp32 and bfloat16, supporting these two low-precision data types should also be straightforward since compute is implemented with fp32.

Another thing worth checking is related to the fusion of conv and gemm in the end-to-end model. We leverage oneDNN to implement these fusion kernels and exposed as external calls to be invoked from inductor. Since oneDNN already supports ARM via ACL, I guess those parts can also be leveraged as it, may need some validations though.

**Comment by Rohanjames1997** [comment]
Thanks for the response, @jgong5!

- Yes, I will be adding support for fp32. The existing datatype conversion between fp32 and bf16 does seem to work on Arm as well, but it will require further validation. Hence I shall take it up in a different PR.
- Indeed, fusion of conv and gemm is something I've started looking into & want to implement. If you could point me to where oneDNN's fusion logic is implemented in the PyTorch codebase, that would be of great help!

**Comment by jgong5** [comment]
@Rohanjames1997 here is the place where we do the fusion now: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/fx_passes/mkldnn_fusion.py. Users don't have to call the fusion API explicitly. We register the fusion patterns (e.g., post-op fusions) into the inductor to get them applied to invoke the native fusion ops/kernels registered here: https://github.com/pytorch/pytorch/blob/1b24a75175f57dfbbadb796a0009a2fe5aa10acf/aten/src/ATen/native/mkldnn/Conv.cpp#L1107

ARM path can reuse this since the Conv/Gemm is also accelerated via oneDNN.

**Comment by Rohanjames1997** [comment]
@jgong5 Thanks, that helps.
It seems like the code that you pointed to that invokes the native fusion kernels is part of the else condition of `#if !AT_MKLDNN_ENABLED()`. 

One important question - how to I build Pytorch such that `AT_MKLDNN_ENABLED()` is 1? 

I am building Pytorch from source on Arm, but I can never get to set the `AT_MKLDNN_ENABLED()` to 1. And due to this, many pieces of code that are wrapped in similar if conditions do not get compiled. I've set both `USE_MKLDNN` and `USE_MKLDNN_ACL` but those are responsible for setting `AT_MKLDNN_ENABLED()` and `AT_MKLDNN_ACL_ENABLED()`. I'd like to know the procedure to set  `AT_MKLDNN_ENABLED()` (even when building from source on Intel).

Thanks!

**Comment by Rohanjames1997** [comment]
@jgong5 Thanks, that helps.

The code that you pointed to is compiled when `AT_MKLDNN_ENABLED()` is set to 1. This is the case when I built Pytorch from source on ARM after building ACL, I confirmed that by checking the config file inside Aten. (I set `USE_MKLDNN=1` and `USE_MKLDNN_ACL=1` while building & provide the correct path to ACL). So theoretically, ARM should have leveraged the fusion code as is, right?
Yet, for some reason, the inductor generated C++ code for BERT incorporates fusion on Intel, but not on ARM. 

What could be the reason(s) for this? Am I missing some flags, or should I be changing any particular config parameters? 

Thanks.

**Comment by jgong5** [comment]
> Yet, for some reason, the inductor generated C++ code for BERT incorporates fusion on Intel, but not on ARM.

Can you elaborate on this? There is one missing piece that for fp32 linear, we are using MKL instead of oneDNN since it is faster on x86 CPUs. It should be not hard to add oneDNN counterpart in the case of ARM. But I just wanted to make sure you were hitting this case.

**Comment by Rohanjames1997** [comment]
@jgong5 That makes some sense. I did see the mkl::_mkl_linear as part of the profiling output of BERT.

But, I see that fusion is leveraged for conv operations as well. I'll explain with minimal code example below
#### Conv2D layer + GELU
I ran this simple model (code below) on Intel and on ARM. 
On Intel, it leveraged the `mkldnn::_convolution_pointwise` function, while not on ARM. This happens even though the pattern is registered on ARM as well (I checked that [these functions](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/fx_passes/mkldnn_fusion.py#L911-L914) get executed). And, this [line](https://github.com/pytorch/pytorch/blob/1b24a75175f57dfbbadb796a0009a2fe5aa10acf/aten/src/ATen/native/mkldnn/Conv.cpp#L1107) is compiled when `AT_MKLDNN_ENABLED()` is set to 1, which is true for both Intel and ARM. Could you shed light on why this is the case?

<details><summary>Model Code</summary>
<p>

```
import torch
import torch.nn as nn
from torch.profiler import profile, record_function, ProfilerActivity

model_conv = nn.Sequential(nn.Conv2d(3, 64, 7, 2, 3), nn.GELU()).eval()
compiled_model_conv = torch.compile(model_conv)
inputs = torch.randn(1, 3, 224, 224)

with torch.set_grad_enabled(False):
    for _ in range(40):
        compiled_model_conv(inputs) #Warmup

    with profile(activities=[ProfilerActivity.CPU]) as prof:
        with record_function("model_conv_inference"):
            for _ in range(10):
                compiled_model_conv(inputs)

print(prof.key_averages().table(sort_by="self_cpu_time_total"))
```
</p>
</details> 

<details><summary>Profile output on x86. This uses mkldnn::_convolution_pointwise</summary>
<p>

----------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                              Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls  
    mkldnn::_convolution_pointwise        89.85%      22.251ms        90.16%      22.326ms       2.233ms            10  
              model_conv_inference         9.69%       2.399ms       100.00%      24.764ms      24.764ms             1  
                     aten::resize_         0.25%      63.000us         0.25%      63.000us       6.300us            10  
               aten::empty_strided         0.16%      39.000us         0.16%      39.000us       3.900us            10  
                       aten::empty         0.05%      12.000us         0.05%      12.000us       1.200us            10  
----------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  

</p>
</details> 

<details><summary>Profile output on ARM. This uses aten::mkldnn_convolution</summary>
<p>

----------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                        Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls  
        model_conv_inference        44.63%      62.063ms       100.00%     139.067ms     139.067ms             1  
    aten::mkldnn_convolution        29.32%      40.775ms        54.63%      75.970ms       7.597ms            10  
                 aten::copy_        24.94%      34.682ms        24.94%      34.682ms       3.468ms            10  
    TorchDynamo Cache Lookup         0.63%     874.000us         0.63%     874.000us      87.400us            10  
                 aten::empty         0.23%     314.000us         0.23%     314.000us      10.467us            30  
          aten::_convolution         0.07%      96.000us        54.70%      76.066ms       7.607ms            10  
                 aten::clone         0.06%      78.000us        25.11%      34.917ms       3.492ms            10  
           aten::convolution         0.05%      64.000us        54.74%      76.130ms       7.613ms            10  
           aten::as_strided_         0.04%      52.000us         0.04%      52.000us       5.200us            10  
            aten::contiguous         0.03%      43.000us        25.14%      34.960ms       3.496ms            10  
            aten::empty_like         0.02%      26.000us         0.11%     157.000us      15.700us            10  
----------------------------  ------------  ------------  ------------  ------------  ------------  ------------  

</p>
</details> 

<details><summary>Inductor-generated code on x86 </summary>
<p>

```
from ctypes import c_void_p, c_long
import torch
import math
import random
from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()


kernel_cpp_0 = async_compile.cpp('''
#include "/tmp/torchinductor_ubuntu/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h"
extern "C" void kernel(const float* __restrict__ in_ptr0,
                       float* __restrict__ out_ptr0)
{
    {
        #pragma GCC ivdep
        for(long i0=0; i0<0; i0+=1)
        {
            #pragma GCC ivdep
            for(long i1=0; i1<6272; i1+=1)
            {
                float tmp1[8*8] __attribute__ ((aligned (8)));
                for (long i0_inner = 0; i0_inner < 8; i0_inner++)
                {
                    auto tmp0 = at::vec::Vectorized<float>::loadu(in_ptr0 + (8*i1) + (50176*i0_inner) + (401408*i0));
                    tmp0.store(tmp1 + 8*i0_inner);
                }
                at::vec::transpose_mxn<float,8,8>(tmp1, 8, out_ptr0 + (8*i0) + (24*i1), 3);
            }
            #pragma GCC ivdep
            for(long i1=50176; i1<50176; i1+=1)
            {
                for (long i0_inner = 0; i0_inner < 8; i0_inner++)
                {
                    auto tmp0 = in_ptr0[i1 + (50176*i0_inner) + (401408*i0)];
                    out_ptr0[i0_inner + (3*i1) + (8*i0)] = tmp0;
                }
            }
        }
        #pragma GCC ivdep
        for(long i0=0; i0<3; i0+=1)
        {
            #pragma GCC ivdep
            for(long i1=0; i1<50176; i1+=1)
            {
                auto tmp0 = in_ptr0[i1 + (50176*i0)];
                out_ptr0[i0 + (3*i1)] = tmp0;
            }
        }
    }
}
''')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1, arg2_1 = args
    args.clear()
    buf0 = empty_strided((1, 3, 224, 224), (150528, 1, 672, 3), device='cpu', dtype=torch.float32)
    kernel_cpp_0(c_void_p(arg2_1.data_ptr()), c_void_p(buf0.data_ptr()))
    del arg2_1
    buf1 = torch.ops.mkldnn._convolution_pointwise(buf0, arg0_1, arg1_1, (3, 3), (2, 2), (1, 1), 1, 'gelu', [], 'none')
    assert_size_stride(buf1, (1, 64, 112, 112), (802816, 1, 7168, 64))
    del arg0_1
    del arg1_1
    return (buf1, )


if __name__ == "__main__":
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((64, 3, 7, 7), (1, 0, 0, 0), device='cpu', dtype=torch.float32)
    arg1_1 = rand_strided((64, ), (1, ), device='cpu', dtype=torch.float32)
    arg2_1 = rand_strided((1, 3, 224, 224), (150528, 50176, 224, 1), device='cpu', dtype=torch.float32)
    print_performance(lambda: call([arg0_1, arg1_1, arg2_1]))

```
</p>
</details> 

<details><summary>Inductor-generated code on ARM </summary>
<p>

```
from ctypes import c_void_p, c_long
import torch
import math
import random
import os
import tempfile
from math import inf, nan
from torch._inductor.hooks import run_intermediate_hooks
from torch._inductor.utils import maybe_profile

from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()


cpp_fused_gelu_0 = async_compile.cpp('''
#include "/tmp/torchinductor_ubuntu/px/cpxv3fnctmkbg7itd75jcmhyzfsv4f7jegurcwusvdsugah5ypta.h"
extern "C" void kernel(float* in_out_ptr0)
{
    {
        for(long i0=static_cast<long>(0L); i0<static_cast<long>(802816L); i0+=static_cast<long>(8L))
        {
            auto tmp0 = at::vec::Vectorized<float>::loadu(in_out_ptr0 + static_cast<long>(i0));
            auto tmp1 = at::vec::Vectorized<float>(static_cast<float>(0.5));
            auto tmp2 = tmp0 * tmp1;
            auto tmp3 = at::vec::Vectorized<float>(static_cast<float>(0.7071067811865476));
            auto tmp4 = tmp0 * tmp3;
            auto tmp5 = tmp4.erf();
            auto tmp6 = at::vec::Vectorized<float>(static_cast<float>(1.0));
            auto tmp7 = tmp5 + tmp6;
            auto tmp8 = tmp2 * tmp7;
            tmp8.store(in_out_ptr0 + static_cast<long>(i0));
        }
    }
}
''')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1, arg2_1 = args
    args.clear()
    assert_size_stride(arg0_1, (64, 3, 7, 7), (147, 49, 7, 1))
    assert_size_stride(arg1_1, (64, ), (1, ))
    assert_size_stride(arg2_1, (1, 3, 224, 224), (150528, 50176, 224, 1))
    buf0 = extern_kernels.convolution(arg2_1, arg0_1, arg1_1, stride=(2, 2), padding=(3, 3), dilation=(1, 1), transposed=False, output_padding=(0, 0), groups=1)
    assert_size_stride(buf0, (1, 64, 112, 112), (802816, 12544, 112, 1))
    del arg0_1
    del arg1_1
    del arg2_1
    buf1 = buf0; del buf0  # reuse
    cpp_fused_gelu_0(c_void_p(buf1.data_ptr()))
    return (buf1, )


def benchmark_compiled_module(times=10, repeat=10):
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((64, 3, 7, 7), (147, 49, 7, 1), device='cpu', dtype=torch.float32)
    arg1_1 = rand_strided((64, ), (1, ), device='cpu', dtype=torch.float32)
    arg2_1 = rand_strided((1, 3, 224, 224), (150528, 50176, 224, 1), device='cpu', dtype=torch.float32)
    return print_performance(lambda: call([arg0_1, arg1_1, arg2_1]), times=times, repeat=repeat)


if __name__ == "__main__":
    from torch._inductor.utils import compiled_module_main
    compiled_module_main('None', benchmark_compiled_module)
```
</p>
</details> 

#### Linear layer + GELU
This, like you mentioned, calls `mkl::_mkl_linear` on Intel. Is the oneDNN counterpart already part of the Pytorch repo? Is it [mkldnn::_linear_pointwise](https://github.com/pytorch/pytorch/blob/1b24a75175f57dfbbadb796a0009a2fe5aa10acf/aten/src/ATen/native/mkldnn/Linear.cpp#L433C29-L433C54) ? After resolving the conv issue mentioned before, I'd like to wire it up so that it indeed calls the mkldnn version instead of aten's. Any tips/advice would be much appreciated!
<details><summary>Model Code</summary>
<p>

```
  import torch
  import torch.nn as nn
  from torch.profiler import profile, record_function, ProfilerActivity
  
  model_linear = nn.Sequential(nn.Linear(1024, 1024), nn.GELU()).eval()
  compiled_model_linear = torch.compile(model_linear)
  inputs = torch.randn(1024, 1024)
  
  with torch.set_grad_enabled(False):
      for _ in range(40):
          compiled_model_linear(inputs) #Warmup
  
      with profile(activities=[ProfilerActivity.CPU]) as prof:
          with record_function("model_linear_inference"):
              for _ in range(10):
                  compiled_model_linear(inputs)
  
  print(prof.key_averages().table(sort_by="self_cpu_time_total"))
```
</p>
</details> 

<details><summary>Profile output on x86</summary>
<p>

--------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                      Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls  
          mkl::_mkl_linear        83.92%      18.204ms        84.27%      18.279ms       1.828ms            10  
    model_linear_inference        15.73%       3.412ms       100.00%      21.691ms      21.691ms             1  
               aten::empty         0.35%      75.000us         0.35%      75.000us       7.500us            10  
--------------------------  ------------  ------------  ------------  ------------  ------------  ------------  

</p>
</details> 

<details><summary>Profile output on ARM</summary>
<p>

----------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                        Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls  
                 aten::addmm        79.69%      32.795ms        82.57%      33.978ms       3.398ms            10  
      model_linear_inference        15.08%       6.204ms       100.00%      41.153ms      41.153ms             1  
                 aten::copy_         2.82%       1.162ms         2.82%       1.162ms     116.200us            10  
    TorchDynamo Cache Lookup         1.98%     816.000us         1.98%     816.000us      81.600us            10  
         aten::empty_strided         0.24%     100.000us         0.24%     100.000us      10.000us            10  
            aten::as_strided         0.13%      55.000us         0.13%      55.000us       2.750us            20  
                aten::expand         0.05%      21.000us         0.05%      21.000us       2.100us            10  
          aten::resolve_conj         0.00%       0.000us         0.00%       0.000us       0.000us            20  
----------------------------  ------------  ------------  ------------  ------------  ------------  ------------  

</p>
</details> 

<details><summary>Inductor-generated code on x86 </summary>
<p>

```
from ctypes import c_void_p, c_long
import torch
import math
import random
from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()


kernel_cpp_0 = async_compile.cpp('''
#include "/tmp/torchinductor_ubuntu/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h"
extern "C" void kernel(float* __restrict__ in_out_ptr0,
                       const float* __restrict__ in_ptr0)
{
    #pragma omp parallel num_threads(8)
    {
        {
            #pragma omp for 
            for(long i0=0; i0<1024; i0+=1)
            {
                for(long i1=0; i1<128; i1+=1)
                {
                    auto tmp0 = at::vec::Vectorized<float>::loadu(in_out_ptr0 + (8*i1) + (1024*i0));
                    auto tmp1 = at::vec::Vectorized<float>::loadu(in_ptr0 + 8*i1);
                    auto tmp2 = tmp0 + tmp1;
                    auto tmp3 = at::vec::Vectorized<float>(static_cast<float>(0.5));
                    auto tmp4 = tmp2 * tmp3;
                    auto tmp5 = at::vec::Vectorized<float>(static_cast<float>(0.7071067811865476));
                    auto tmp6 = tmp2 * tmp5;
                    auto tmp7 = tmp6.erf();
                    auto tmp8 = at::vec::Vectorized<float>(static_cast<float>(1));
                    auto tmp9 = tmp7 + tmp8;
                    auto tmp10 = tmp4 * tmp9;
                    tmp10.store(in_out_ptr0 + (8*i1) + (1024*i0));
                }
                #pragma omp simd simdlen(4) 
                for(long i1=1024; i1<1024; i1+=1)
                {
                    auto tmp0 = in_out_ptr0[i1 + (1024*i0)];
                    auto tmp1 = in_ptr0[i1];
                    auto tmp2 = tmp0 + tmp1;
                    auto tmp3 = static_cast<float>(0.5);
                    auto tmp4 = tmp2 * tmp3;
                    auto tmp5 = static_cast<float>(0.7071067811865476);
                    auto tmp6 = tmp2 * tmp5;
                    auto tmp7 = std::erf(tmp6);
                    auto tmp8 = static_cast<float>(1);
                    auto tmp9 = tmp7 + tmp8;
                    auto tmp10 = tmp4 * tmp9;
                    in_out_ptr0[i1 + (1024*i0)] = tmp10;
                }
            }
        }
    }
}
''')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1, arg2_1, arg3_1 = args
    args.clear()
    buf0 = torch.ops.mkl._mkl_linear(arg3_1, arg2_1, arg0_1, None, 1024)
    del arg0_1
    del arg2_1
    del arg3_1
    buf1 = buf0; del buf0  # reuse
    kernel_cpp_0(c_void_p(buf1.data_ptr()), c_void_p(arg1_1.data_ptr()))
    del arg1_1
    return (buf1, )


if __name__ == "__main__":
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((1024, 1024), (1024, 1), device='cpu', dtype=torch.float32)
    arg1_1 = rand_strided((1024, ), (1, ), device='cpu', dtype=torch.float32)
    arg2_1 = rand_strided((3490017, 1), (1, 0), device='cpu', dtype=torch.float32)
    arg3_1 = rand_strided((1024, 1024), (1024, 1), device='cpu', dtype=torch.float32)
    print_performance(lambda: call([arg0_1, arg1_1, arg2_1, arg3_1]))

```
</p>
</details> 

<details><summary>Inductor-generated code on ARM </summary>
<p>

```
from ctypes import c_void_p, c_long
import torch
import math
import random
import os
import tempfile
from math import inf, nan
from torch._inductor.hooks import run_intermediate_hooks
from torch._inductor.utils import maybe_profile

from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()


cpp_fused_gelu_0 = async_compile.cpp('''
#include "/tmp/torchinductor_ubuntu/px/cpxv3fnctmkbg7itd75jcmhyzfsv4f7jegurcwusvdsugah5ypta.h"
extern "C" void kernel(float* in_out_ptr0)
{
    #pragma omp parallel num_threads(16)
    {
        {
            #pragma omp for 
            for(long i0=static_cast<long>(0L); i0<static_cast<long>(1048576L); i0+=static_cast<long>(8L))
            {
                auto tmp0 = at::vec::Vectorized<float>::loadu(in_out_ptr0 + static_cast<long>(i0));
                auto tmp1 = at::vec::Vectorized<float>(static_cast<float>(0.5));
                auto tmp2 = tmp0 * tmp1;
                auto tmp3 = at::vec::Vectorized<float>(static_cast<float>(0.7071067811865476));
                auto tmp4 = tmp0 * tmp3;
                auto tmp5 = tmp4.erf();
                auto tmp6 = at::vec::Vectorized<float>(static_cast<float>(1.0));
                auto tmp7 = tmp5 + tmp6;
                auto tmp8 = tmp2 * tmp7;
                tmp8.store(in_out_ptr0 + static_cast<long>(i0));
            }
        }
    }
}
''')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1, arg2_1 = args
    args.clear()
    assert_size_stride(arg0_1, (1024, 1024), (1024, 1))
    assert_size_stride(arg1_1, (1024, ), (1, ))
    assert_size_stride(arg2_1, (1024, 1024), (1024, 1))
    buf0 = empty_strided((1024, 1024), (1024, 1), device='cpu', dtype=torch.float32)
    extern_kernels.addmm(arg1_1, arg2_1, as_strided(arg0_1, (1024, 1024), (1, 1024)), alpha=1, beta=1, out=buf0)
    del arg0_1
    del arg1_1
    del arg2_1
    buf1 = buf0; del buf0  # reuse
    cpp_fused_gelu_0(c_void_p(buf1.data_ptr()))
    return (buf1, )


def benchmark_compiled_module(times=10, repeat=10):
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((1024, 1024), (1024, 1), device='cpu', dtype=torch.float32)
    arg1_1 = rand_strided((1024, ), (1, ), device='cpu', dtype=torch.float32)
    arg2_1 = rand_strided((1024, 1024), (1024, 1), device='cpu', dtype=torch.float32)
    return print_performance(lambda: call([arg0_1, arg1_1, arg2_1]), times=times, repeat=repeat)


if __name__ == "__main__":
    from torch._inductor.utils import compiled_module_main
    compiled_module_main('None', benchmark_compiled_module)
```
</p>
</details>

**Comment by jgong5** [comment]
@Rohanjames1997 for convolution fusions, I don't think the fusion logic would depend on CPU arch. Can you try the latest pytorch code and also make sure you have set `TORCHINDUCTOR_FREEZING=1`? For linear, we open turn on `_linear_pointwise` when `_is_mkldnn_bf16_supported` returns `True`. But the fusion kernel implementation should work for fp32 too. You search for `_is_mkldnn_bf16_supported` and try to turn it on for ARM regardlessly.

**Comment by Rohanjames1997** [comment]
@jgong5 ,
When I run my model with the latest PyTorch code and `TORCHINDUCTOR_FREEZING=1`, I get the following error: 
`AttributeError: '_OpNamespace' 'mkl' object has no attribute '_mkl_reorder_linear_weight'`.  This stems from [line 899](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/fx_passes/mkldnn_fusion.py#L899) of mkldnn_fusion.py. 
If I replace `torch.ops.mkl._mkl_reorder_linear_weight` with `torch.ops._mkldnn_reorder_linear_weight`, there is no error, `mkldnn::_convolution_pointwise` is indeed called, and I see post-op fusion occurring in the generated code. Is this replacement a valid fix? (Is it a bug in the first place?). 
Running my linear model still throws a similar error, stemming from [this line](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/fx_passes/mkldnn_fusion.py#L856), and doing a similar replacement here results in other errors.

To turn on `_linear_pointwise`, I had to forcefully `is_bf16_weight = True`. The function that you mentioned - `mkldnn._is_mkldnn_bf16_supported()` returned True on ARM, but the `mkl_linear` [path](https://github.com/pytorch/pytorch/blob/bf46b6653fe41a8cab70f35269f1898f1ebd9544/torch/_inductor/fx_passes/mkldnn_fusion.py#L871) was triggered when `is_bf16_weight` was False and that resulted in an error on ARM, as expected. Setting my linear model's type to bfloat16() (model.bfloat16()) did not work either, as Inductor raised another error: 
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: could not create a primitive descriptor
```
That is why I had to set `is_bf16_weight = True`. And then, the `_linear_pointwise` was invoked.

In both scenarios - conv and linear, the post-op fusion paths showed regressions in performance as compared to the paths without fusion. Could this be due to the way ACL implements oneDNN? Or could I be doing something differently to see perf gains?

Thanks!

**Comment by jgong5** [comment]
> AttributeError: '_OpNamespace' 'mkl' object has no attribute '_mkl_reorder_linear_weight'. This stems from [line 899](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/fx_passes/mkldnn_fusion.py#L899) of mkldnn_fusion.py.

This is probably due to mkl not enabled in ARM build (which is expected).

> In both scenarios - conv and linear, the post-op fusion paths showed regressions in performance as compared to the paths without fusion. Could this be due to the way ACL implements oneDNN fusion kernels? Or could I be doing something differently to see perf gains?

Not sure whether it is expected for ARM with oneDNN. Probably @nSircombe can comment more on this. One thing you can check is to tune on "ONEDNN_VERBOSE=1" in the environment and see if the right kernels are invoked.

**Comment by Rohanjames1997** [comment]
> This is probably due to mkl not enabled in ARM build (which is expected).

Okay, that makes sense. So, does it mean that the Conv fusion logic depends on CPU arch, unlike previously thought? Pytorch in its current state does not seem to support fusion for ARM. Is there a plan to enable it? I can create a separate issue to take it up if required.

> Not sure whether it is expected for ARM with oneDNN. Probably @nSircombe can comment more on this. One thing you can check is to tune on "ONEDNN_VERBOSE=1" in the environment and see if the right kernels are invoked.

Sure, looking forward to it. I shall check if the right kernels are invoked.

**Comment by jgong5** [comment]
> So, does it mean that the Conv fusion logic depends on CPU arch, unlike previously thought?

No, there is no arch-dependent logic in pytorch for conv fusion. As long as oneDNN support the same level of conv fusion for ARM, we should support it in pytorch too. Only linear fp32 depends on MKL but can be switched to oneDNN on ARM as I mentioned previously.

> Pytorch in its current state does not seem to support fusion for ARM. Is there a plan to enable it? I can create a separate issue to take it up if required.

Sure. Also welcome to any contribution if you'd like to.

**Comment by Rohanjames1997** [comment]
> No, there is no arch-dependent logic in pytorch for conv fusion. 

I may have misunderstood, but from my **conv** model experiment (Conv2D + GELU) with the latest PyTorch code and `TORCHINDUCTOR_FREEZING=1`, I get the following error: `AttributeError: '_OpNamespace' 'mkl' object has no attribute '_mkl_reorder_linear_weight'`. So, it seems as if even the conv fusion path tries to make use of MKL regardless of cpu arch? (Instead of oneDNN?) 

Thanks again for the help!

**Comment by Rohanjames1997** [comment]
@jgong5 It seems as if #106049 has fixed the last issue that we discussed. Thanks @angelayi !

**Comment by Rohanjames1997** [comment]
@jgong5 , #106122 seems to have reverted a few of @angelayi 's changes. 

Particularly, ` if is_bf16_weight or (not torch._C.has_mkl)` has become `if is_bf16_weight`. With this change, oneDNN's fusion kernels are no longer invoked on aarch64, even with `TORCHINDUCTOR_FREEZING=1`.

Is there another way ARM users can invoke oneDNN's fusion kernels now? 
TIA!

**Comment by jgong5** [comment]
> Particularly, ` if is_bf16_weight or (not torch._C.has_mkl)` has become `if is_bf16_weight` in a few places.

 Oh, this seems something not expected. cc @XiaobingSuper to take a look if we need a further fix.

> And with this change: if not is_bf16_weight and (free_symbols(batch_size) or (not torch._C.has_mkl)): return False 
oneDNN's fusion kernels are no longer invoked on aarch64, even with TORCHINDUCTOR_FREEZING=1.

The intention is to avoid doing weight prepacking for fp32 linear on x86 since we are using mkl, not onednn. For aarch64, you can revise the code to always use onednn linear similar to how it is used with bf16 on x86.
