### ISSUE TITLE
Error during backward when using F.scaled_dot_product_attention on H100

### ISSUE THREAD

**Issue by DaniNem** [pytorch/pytorch#104766]
### 🐛 Describe the bug

Hey,

When doing backward on a model that uses F.scaled_dot_product_attention on H100 I get the following error:

```
import torch
from timm.models.vision_transformer import vit_tiny_patch16_224

model = vit_tiny_patch16_224()
model.to("cuda")
input = torch.rand([1,3,224,224],device="cuda")
output = model(input)
output.mean().backward()
```

```
Traceback (most recent call last):
  File "...", line 72, in <module>
    output.mean().backward()
  File "..../lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "..../python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

```

While running this code all seems good:

```
import torch
from timm.models.vision_transformer import vit_tiny_patch16_224

model = vit_tiny_patch16_224()
for block in model.blocks:
     block.attn.fused_attn = False
model.to("cuda")
input = torch.rand([1,3,224,224],device="cuda")
output = model(input)
output.mean().backward()


```

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.8.12 (default, Jun 25 2023, 21:54:24)  [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1028-nvidia-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

Nvidia driver version: 525.125.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          224
On-line CPU(s) list:             0-223
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8480CL
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              56
Socket(s):                       2
Stepping:                        7
CPU max MHz:                     3800.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4000.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
L1d cache:                       5.3 MiB (112 instances)
L1i cache:                       3.5 MiB (112 instances)
L2 cache:                        224 MiB (112 instances)
L3 cache:                        210 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-55,112-167
NUMA node1 CPU(s):               56-111,168-223
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchvideo2==0.0.3
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by ptrblck** [comment]
The issue is reproducible in `2.0.1+cu118` on an H100 and fails in:
```
========= COMPUTE-SANITIZER
========= Illegal instruction
=========     at 0x1b50 in void attention_kernel_backward_batched<AttentionBackwardKernel<cutlass::arch::Sm80, float, (bool)1, (int)64>>(T1::Params)
=========     by thread (0,2,0) in block (0,1,0)
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x30b492]
=========                in /usr/local/cuda/compat/lib.real/libcuda.so.1
=========     Host Frame: [0x1488c]
=========                in /usr/local/lib/python3.10/dist-packages/torch/lib/libcudart-d0da41ae.so.11.0
=========     Host Frame:cudaLaunchKernel [0x6c318]
=========                in /usr/local/lib/python3.10/dist-packages/torch/lib/libcudart-d0da41ae.so.11.0
=========     Host Frame:void attention_kernel_backward_batched<AttentionBackwardKernel<cutlass::arch::Sm80, float, true, 64> >(AttentionBackwardKernel<cutlass::arch::Sm80, float, true, 64>::Params) [0x2f39d9b]
=========                in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
=========     Host Frame:auto at::native::_efficient_attention_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, bool)::{lambda(auto:1, int)#1}::operator()<AttentionBackwardKernel<cutlass::arch::Sm80, float, true, 64> >(AttentionBackwardKernel<cutlass::arch::Sm80, float, true, 64>, int) const [clone .isra.0] [0x2ee1e3f]
=========                in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
=========     Host Frame:at::native::_efficient_attention_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, bool)::{lambda()#2}::operator()() const [0x2f00fbe]
=========                in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
=========     Host Frame:at::native::_efficient_attention_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, bool) [0x2f1e224]
=========                in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
=========     Host Frame:at::(anonymous namespace)::(anonymous namespace)::wrapper_CUDA___efficient_attention_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, bool) [0x2f85bc0]
=========                in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
```

However, no failures in the CUDA 11.8 (`2.1.0.dev20230706+cu118`) and 12.1 (`2.1.0.dev20230706+cu121`) nightly.
