### ISSUE TITLE
Nondeterministic segfault in test_content_store.py under Dynamo config

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#104719]
### 🐛 Describe the bug

Running `PYTORCH_TEST_WITH_DYNAMO=1 python test/test_content_store.py -v` enough (~5 times) leads to a segfault. Weirdly, some unrelated PRs (e.g. https://github.com/pytorch/pytorch/pull/104481) seem to cause the segfault to be triggered more consistently. 

Stack trace looks like the following and involves Python GC and weakrefs.: https://gist.github.com/zou3519/799c8c069d220beca9fa56a908044212 

### Versions

main; Python 3.10.4

cc @mruberry @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

**Comment by ezyang** [comment]
There isn't really much point in testing this under Dynamo, it's very synthetic, shall we just skip this test suite under PYTORCH_TEST_WITH_DYNAMO?

**Comment by zou3519** [comment]
Yeah I can do that

**Comment by anijain2305** [comment]
Closing.
