### ISSUE TITLE
inductor/triton fails on `view(..., dtype=torch.int16)`

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#104791]
It looks like triton can't handle bitcasting `float16` to `int16`. This example works on cpu though. Repro:
```
import torch

@torch.compile
def f(x):
    x_view = x.view(dtype=torch.int16)
    return x_view.mul(2)

x = torch.ones(4, dtype=torch.float16, device='cuda')
out = f(x)
```

output:
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CompilationError: at 8:19:def triton_(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 4
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), xmask).to(tl.float32)
    tmp1 = tmp0.to(tl.int16, bitcast=True)
                   ^
ValueError('Cannot bitcast data-type of size 32to data-type of size 16')
```

One question: should triton be able to handle this? Otherwise, maybe we can change the lowering for `view.dtype` to fall back to eager when it sees an fp16->int16 conversion.

I ran into this when trying to use @jcaip 's `SparseSemiStructuredTensor` subclass prototype with torch.compile.

cc @ezyang @msaroufim @wconstab @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen @ngimel

**Comment by bdhirsh** [comment]
I made a potential fix here, that just has inductor fall back to eager when it sees `fp16_tensor.view(dtype=torch.int16)`: https://github.com/pytorch/pytorch/pull/104793. Happy to land it, or discard it if we think there's a better way.

**Comment by ezyang** [comment]
to avoid breaking, we should downcast the float32 to float16 and then extract the integer representation at that point

**Comment by bdhirsh** [comment]
Hmm, why are we upcasting to `float32` in the first place? It looks like the repro upcasts the input to `float32` before trying to do the conversion:
```
    tmp0 = tl.load(in_ptr0 + (x0), xmask).to(tl.float32)
    tmp1 = tmp0.to(tl.int16, bitcast=True)
```

**Comment by eellison** [comment]
https://github.com/pytorch/pytorch/blob/1a661639f77a172df5d1ccd6987049292c6f3440/torch/_inductor/codegen/triton.py#L69-L76

copy-pasting what Jason posted somewhere else:

```
That fp32 upcasting is needed for correctness:
1) Eager mode kernels do the exact same up casting (as Elias said, this is just a good idea since fp32 precision is free for bandwidth bound kernels)
2) We decompose eager mode kernels into smaller pieces, and those decomps don't model the internal upcasts within the decomposed kernel.
3) Those decomps will get re-fused by inductor, if we did the internal ops within the kernel in fp16 we would have worse precision than eager mode.
```

**Comment by vadimkantorov** [comment]
maybe there should be no upcasting for this case specifically...

**Comment by bdhirsh** [comment]
> maybe there should be no upcasting for this case specifically...

Hmm, that might be hard in the general case. What if we have a function that takes in an fp16 tensor and views it as an int16, but we also need to do some arbitrary compute with that fp16 tensor? (which would require the higher precision accumulation dtype)

def f(fp16_inp):
    out = fp16_inp.sum()  # do something with the fp16 that **does** require upcasting
    return fp16_inp.view(dtype=torch.int16) + out.view(dtype=torch.int16)

**Comment by vadimkantorov** [comment]
I think this is less likely as `.view(int16)` is usually used for some tricky scenarios where we need to change the representation.

But other than that, if there is a non-view(int16) consuming node, could .to(float32) be inserted later before that other node, so that .view is connected directly to the load output?
