### ISSUE TITLE
[JIT] Autodiff assumes every Value* has a distinct Value* representing its gradient

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#10484]
In [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/autodiff.cpp#L540).

Possible fix: realize this invariant by inserting an `prim::Identity` node before inserting things into the `grad_map`. Optimize all of them out after AD.

**Comment by zdevito** [comment]
Pretty sure this has been fixed, or is obsolete. Reopen if I am wrong.
