### ISSUE TITLE
Easy to accidentally pass logging.DEBUG or other level to artifact flags

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#104885]
### 🐛 Describe the bug

I saw someone write this

```
torch._logging.set_logs(recompiles=logging.DEBUG, dynamic=logging.INFO, guards=logging.INFO)
```

But guards only takes bools. This accidentally works because INFO is non-zero.

cc @mlazos 

### Versions

main

**Comment by mlazos** [comment]
I'll add asserts
