### ISSUE TITLE
code.py filename is not allowed

### ISSUE THREAD

**Issue by elexunix** [pytorch/pytorch#104825]
### 🐛 Describe the bug

```
$ cat > code.py
print('a')
$ python3 -c 'import torch'
```

It is important that the filename is 'code.py'

### Versions

a
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.26.0
Libc version: glibc-2.35

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 525.85.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       GenuineIntel
Model name:                      13th Gen Intel(R) Core(TM) i7-13700KF
CPU family:                      6
Model:                           183
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
Stepping:                        1
CPU max MHz:                     5400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6835.20
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       640 KiB (16 instances)
L1i cache:                       768 KiB (16 instances)
L2 cache:                        24 MiB (10 instances)
L3 cache:                        30 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.0
[pip3] torchtext==0.15.1
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by ezyang** [comment]
works for me

```
(/home/ezyang/local/d/pytorch-env) [ezyang@devgpu019.ftw1 ~/local/d/pytorch (796c714e)]$ cat > code.py
print('a')
(/home/ezyang/local/d/pytorch-env) [ezyang@devgpu019.ftw1 ~/local/d/pytorch (796c714e)]$ python -c 'import torch'
(/home/ezyang/local/d/pytorch-env) [ezyang@devgpu019.ftw1 ~/local/d/pytorch (796c714e)]$ 
```

**Comment by elexunix** [comment]
Whoever encounters this in the future, I have checked in a clean docker container, it turned out the issue was "sympy":
torch + sympy==1.9 has this bug
torch + sympy==1.12 has not!

**Comment by elexunix** [comment]
The bug turned out to be not even in scipy, but in pdb (default python library, on which both sympy and torch depended)
Here is a very simple reproduction __without ANY external libraries__ in plain ubuntu container:
`docker run -it --rm ubuntu`
inside the container:
```apt update && apt install -y python3
echo 'raise kek' > code.py
python3 -c 'import pdb'```
