### ISSUE TITLE
[dynamo][higher_order_op] assert in check_kwargs leads to error instead of graph-break

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#104884]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/blob/e695b397e16e46e17481ab26517c9713a62e8c4a/torch/_dynamo/variables/higher_order_ops.py#L223-L227

cc: @zou3519 

### Versions

master

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

**Comment by anijain2305** [comment]
Please use `unimplemented` to graph break.

**Comment by laithsakka** [comment]
@anijain2305 based on your comment above shall I close this issue? sounds like its expected to to throw error on failing assertions?
