### ISSUE TITLE
torch.sum crash on Windows

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#10483]
"I am trying to check the count of element-wise equality between two tensors. I have narrowed my issue down to the following short example. The last line results in an “Illegal instruction” message and crashing out of Python."
```
import torch

torch.manual_seed(1)
x = torch.randint(0, 5, (1000, ))

x.eq(x).sum()
```
"I am using Python 3.6.4 in iPython 6.5.0 with torch 0.4.1 on Windows 10."

originally reported from the forums: https://discuss.pytorch.org/t/unable-to-sum-the-result-of-an-equality-test/23059

**Comment by jacobcvt12** [comment]
Further information: I am using a VMware virtual machine - according to the system information within the virtual machine, I have an Intel Xeon CPU E5-2680.

**Comment by soumith** [comment]
@jacobcvt12 your VMWare virtual machine has to have SSE, SSE2, SSE3 and SSE4, SSE4.1, SSE4.2 enabled. If you dont enable them, then Illegal Instruction is an expected error message.

**Comment by soumith** [comment]
you can run the [CPU-Z](https://www.cpuid.com/softwares/cpu-z.html) utility inside your Windows VM to check if those instructions are supported.

**Comment by jacobcvt12** [comment]
Thanks @soumith - I'll check that

**Comment by zou3519** [comment]
You need SSE4.3

**Comment by ezyang** [comment]
@zou3519 Did we officially document which instruction sets our binaries support?

In any case, I believe that if you compile from source you can get PyTorch using the set of instructions your computer supports. For some newer instructions, we do compile multiple times with and without so we can distribute a single set of binaries, but we have to pick a cut off somewhere (or bloat our binary sizes by a lot more.)

**Comment by zou3519** [comment]
I don't think it's officially documented; documentation like that would be helpful. I was quoting from @soumith

**Comment by BPavol** [comment]
Are there any compiled versions(maybe unofficial) for Windows without SSE4.3 requirement for older CPU?
I try compile from source but on my laptop it already takes 8 hours!
And still it didn't work because of another issue(https://github.com/pytorch/pytorch/issues/11203).

**Comment by soumith** [comment]
you're right. I meant 4.2 and got confused.

https://github.com/pytorch/pytorch/blob/cca247635c6edb323176eeac7a18d3e9ab71c558/cmake/Modules/FindSSE.cmake#L111-L115

Our build comes with Defaults of SSE1, SSE2, SSE3, SSE4.1, SSE4.2

**Comment by BPavol** [comment]
Than why I encountered same error. My CPU support all of it.
Here is screen from CPU-Z:
![my_cpu](https://user-images.githubusercontent.com/1245656/45700560-29af8c00-bb6d-11e8-83b7-7f7c09cfc29b.png)

**Comment by peterjc123** [comment]
@BPavol Did you enable them in the VM? Is this the screenshot you made in the VM?

**Comment by BPavol** [comment]
@peterjc123 I don't use VM. I use PyTorch directly on my laptop. But I give up installing it on Windows.
It is so frustrating and takes many hours to resolve problems and trying to compiling from source. Easier solution was to install Debian as another OS on my laptop. There works at least PyTorch for CPU. Only inconvenience is that my GeForce 310m is compatible only with CUDA 6.5 and minimal CUDA requirement is 8.0 (for compiling from source it is 7.0). 

Do you think if I get it work on Windows will it work with my old GeForce 310m? Because there I have CUDA 9.2 installed.

**Comment by peterjc123** [comment]
@BPavol I feel sad that you give up. Still, I wish you happy with Debian. As for your question, I think that it is meaningless to use this GPU due to its low calculation power.

**Comment by ngimel** [comment]
Closing due to age
