### ISSUE TITLE
Incomplete Documentation for torch.nn.FractionalMaxPool2d API

### ISSUE THREAD

**Issue by PhyllisJi** [pytorch/pytorch#104861]
### Description:
I've come across an issue related to incomplete documentation in the torch.nn.FractionalMaxPool2d. It appears that the output_size and output_ratio parameters must be set and only one of them can be set, while the other should either use the default value or remain unassigned. Although the error message provides a hint about this constraint, it is not mentioned in the official documentation. I believe it would be helpful to include this constraint in the official documentation.

### Steps to Reproduce:

Use this API.

Set both output_size and output_ratio parameters, or set none of them and use their default value.

Observe the error message indicating the constraint violation.

### Expected Behavior:
The official documentation should clearly mention the constraint regarding the usage of the output_size and output_ratio parameters in the torch.nn.FractionalMaxPool2d interface.

### Additional Information:
I've encountered this while working on my project and believe that adding this constraint to the documentation will greatly benefit other users of the library.

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Thanks for the catch @PhyllisJi! This applies for FractionalMaxPool3d as well. We would accept a PR that updates the documentation to note that that either one of `output_size` or `output_ratio` must be set.
