### ISSUE TITLE
Regression in Maml due to dynamic shapes

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#104805]
### 🐛 Describe the bug

`python benchmarks/dynamo/torchbench.py --backend inductor --amp --performance --only maml --inference --cold-start-latency`

https://gist.github.com/eellison/88ee0f18bbe7eaf4c6385c386be878f2

>   File "/data/users/dberard/pytorch/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/data/users/dberard/pytorch/torch/_functorch/aot_autograd.py", line 2841, in forward
               assert all(
                    isinstance(x, (int, float, torch.SymInt, torch.SymFloat))
                    for x in symint_outs
                )

### Versions

master

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by bdhirsh** [comment]
I've confirmed that this only repro's when using inductor + cudagraphs. In particular, when the assert fails, the forward-graph we're running looks like this:
```
# primals_1 is a (sym)int, primals_2 and primals_3 are tensors
def forward(self, primals_1, primals_2, primals_3):
    mul = torch.ops.aten.mul.Tensor(primals_2, 0.4);  primals_2 = None
    sub = torch.ops.aten.sub.Tensor(primals_3, mul);  primals_3 = mul = None
    return [sub, primals_1]
```

So we expect our compiled forward to return a [torch.Tensor, torch.SymInt].

When I print out the types of the outputs, I see:
```
(Pdb) print([type(x) for x in fw_outs])
[<class 'torch.Tensor'>, <class 'NoneType'>]
```

We're returning None, when the graph we send to inductor dictates that we should have directly returned `primals_1`.

One thing that looks suspicious: when I try to step into that function at runtime, it appears that we're trying to run it with cudagraph trees. My understanding was that if any of our inputs are symints (aka dynamic shapes are enabled), then we won't use cudagraphs.

@eellison does that sound right to you? My rough guess so far is that the logic we have to turn off cudagraphs when we see SymInts is probably not working properly.

**Comment by bdhirsh** [comment]
Nevermind - looks like if cudagraphs sees any inputs to the graph that are symbolic ints, it will just guard on those values and force a recompile (code: https://github.com/pytorch/pytorch/blob/48a49b2683ffa21eb1b472e503c129c043c18f87/torch/_inductor/compile_fx.py#L348)

I tried to make my own min-repro, but was unsuccessful. It looks like somewhere in the cudagraph code, we should be directly returning one of the integer-inputs as an output, and we aren't.

**Comment by bdhirsh** [comment]
FWIW: maml appears to be running the same tiny subgraph using cudagraphs many times (200+) in a loop, and it's not until iteration 217 that it incorrectly returns a `None`:
```
...
CTR: 210, fw_outs[1]=64, fw_outs2[1]=64
CTR: 211, fw_outs[1]=64, fw_outs2[1]=64
CTR: 212, fw_outs[1]=64, fw_outs2[1]=64
CTR: 213, fw_outs[1]=64, fw_outs2[1]=64
CTR: 214, fw_outs[1]=64, fw_outs2[1]=64
CTR: 215, fw_outs[1]=64, fw_outs2[1]=64
CTR: 216, fw_outs[1]=64, fw_outs2[1]=64
CTR: 217, fw_outs[1]=None, fw_outs2[1]=None
```

That loop looks like it's coming from here: https://github.com/pytorch/benchmark/blob/3df1cc93cccda38506f96d039d80b1888a7d6fb0/torchbenchmark/models/maml/meta.py#L123 (the graph captured is inside that map() call, there are 10+ params to map over, and that entire loop is run `self.update_step` number of times).

**Comment by eellison** [comment]
Fixed now
