### ISSUE TITLE
Pytorch 2.0.1 Profiler generate invalid separator path inside JSON using tensorboard_trace_handler

### ISSUE THREAD

**Issue by antoine-lavrard** [pytorch/pytorch#104841]
### 🐛 Describe the bug

On windows, the tensorboard_trace_handler use the separador \ in the file path instead of / or \\ breaking the json file.

## To reprocuce 
steps to reproduce : (same than Issue #60187 )
run the tutorial [pytorch-profiler-with-tensorboard](https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html)

## expected behaviour

To escape the separator correctly on the json file. Ex: \\, like in PR #60187 

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4070 Ti
Nvidia driver version: 528.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3500
DeviceID=CPU0
Family=205
L2CacheSize=8192
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3500
Name=13th Gen Intel(R) Core(TM) i5-13600KF
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.25.0
[pip3] torch==2.0.1+cu118
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==2.0.2+cu117
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h8bd8f75_46356
[conda] mkl-service               2.4.0           py310h2bbff1b_1
[conda] mkl_fft                   1.3.6           py310h4ed8f06_1
[conda] mkl_random                1.2.2           py310h4ed8f06_1
[conda] numpy                     1.25.0          py310h055cbcc_0
[conda] numpy-base                1.25.0          py310h65a83cf_0
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torch                     2.0.1+cu118              pypi_0    pypi
[conda] torch-tb-profiler         0.4.1                    pypi_0    pypi
[conda] torchaudio                2.0.2+cu117              pypi_0    pypi
[conda] torchmetrics              0.11.4             pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.15.2                   pypi_0    pypi

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by davidberard98** [comment]
@antoine-lavrard I believe this is fixed in the nightly builds.

**Comment by antoine-lavrard** [comment]
I tested it with nightly, it was indeed fixed.
