### ISSUE TITLE
Python 3.11+ not yet supported for torch.compile

### ISSUE THREAD

**Issue by henghamao** [pytorch/pytorch#104918]
### 🐛 Describe the bug

torch version 2.0.1
python 3.11

### Error logs

python3.11
/site-packages/torch/_dynamo/eval_frame.py", line 377, in check_if_dynamo_supported
    raise RuntimeError("Python 3.11+ not yet supported for torch.compile")
RuntimeError: Python 3.11+ not yet supported for torch.compile

### Versions

torch version 2.0.1
python 3.11

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by msaroufim** [comment]
You wanna try out the nightlies, 3.11 is now supported so 3.12 is next https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/eval_frame.py#L487

**Comment by malfet** [comment]
Closing as indeed 3.11 support was added in nightlies.
