### ISSUE TITLE
mypy hints internal error while trying to check types, but lint runner hides it

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#104940]
### 🐛 Describe the bug

Run `mypy torch/_export/exported_program.py` and it will fail with:
```
pytorch/torch/_dynamo/variables/tensor.py:362: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.960
pytorch/torch/_dynamo/variables/tensor.py:362: : note: please use --show-traceback to print a traceback when reporting a bug
``` 

But `mypy_linter` adapter will swallow this error, which results in `lintrunner` aborting lint check at random subset of files and typing error popping up if run on files individually, but got occluded by the INTERNAL ERROR

### Versions

CI

cc @ezyang @gchanan @zou3519 @rgommers @xuzhao9 @gramster @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Tentatively grabbing for myself. `mypy-1.x.y` does not have this problem, but it uncovers gazillion of new lint violations, so to solve the issue two things must be done:
 - Update mypy
 - Fix `mypy_linter` to never ignore internal errors

**Comment by huydhn** [comment]
cc @PaliC As I remember you are trying to upgrade mypy to a newer version as part of the effort to bring lintrunner to fbcode.
