### ISSUE TITLE
After linalg_cholesky decomposition, the tensor changes from row major to clo major! It's not normal.

### ISSUE THREAD

**Issue by majestichou** [pytorch/pytorch#104953]
### 🐛 Describe the bug

After linalg_cholesky decomposition, the tensor changes from row major to clo major!
The code is as follows:
```
#include <torch/torch.h>
#include <iostream>

void PrintTensorMemory(torch::Tensor& A)
{
    auto len = A.reshape({-1}).size(0);
    auto p = A.data_ptr<float>();
    for (int loop = 0; loop < len; loop++)
        printf("(%.4f)", *(p+loop));
    printf("\n");
}

int main() {
    int num = 4;
    printf("*==================================================\n");
    auto A = torch::randn({num, num}, torch::kFloat);
    auto B = torch::matmul(A, A.mT());
    B += torch::eye(num, torch::kFloat);
    std::cout << B << std::endl;
    PrintTensorMemory(B);
    auto C = torch::linalg_cholesky(B);
    std::cout << C << std::endl;
    PrintTensorMemory(C);
    return 0;
}
```
The output is as follows:
*==================================================
 2.6427 -1.7089 -0.2577 -1.0933
-1.7089  3.7843 -0.2697 -0.0687
-0.2577 -0.2697  3.1155  1.6527
-1.0933 -0.0687  1.6527  3.9267
[ CPUFloatType{4,4} ]
(2.6427)(-1.7089)(-0.2577)(-1.0933)(-1.7089)(3.7843)(-0.2697)(-0.0687)(-0.2577)(-0.2697)(3.1155)(1.6527)(-1.0933)(-0.0687)(1.6527)(3.9267)
 1.6256  0.0000  0.0000  0.0000
-1.0512  1.6368  0.0000  0.0000
-0.1585 -0.2666  1.7376  0.0000
-0.6725 -0.4739  0.8171  1.6069
[ CPUFloatType{4,4} ]
(1.6256)(-1.0512)(-0.1585)(-0.6725)(0.0000)(1.6368)(-0.2666)(-0.4739)(0.0000)(0.0000)(1.7376)(0.8171)(0.0000)(0.0000)(0.0000)(1.6069)
Unfortunately, matrix C is stored on a column-major basis! 
Before linalg_cholesky, the matrix is stored on a row-major basis,
After  linalg_cholesky, the matrix is stored on a col-major basis.
The storage sequence of matrix elements has changed and is inconsistent after linalg_cholesky. It's not normal.
### Versions

pytorch C++ API:  2.1.0.dev20230710+cpu
Centos7.9
g++ 7.3

**Comment by ezyang** [comment]
PyTorch is allowed to choose what output stride you get. To force row-major, call contiguous().
