### ISSUE TITLE
ARM64 nightly whl, lack of LAPACK support

### ISSUE THREAD

**Issue by heidongxianhua** [pytorch/pytorch#104950]
### 🐛 Describe the bug

```
>>> import torch
>>> a = torch.rand(2,3)
>>> b = torch.linalg.qr(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Calling torch.geqrf on a CPU tensor requires compiling PyTorch with LAPACK. Please use PyTorch built with LAPACK support.
>>> exit()
```

for ARM whl, it shoud also need build with LAPACK by default.

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230710
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (AltArch) (aarch64)
GCC version: (GCC) 7.5.0
Clang version: 15.0.5 (clang-5c68a1cb1231 flang-5c68a1cb1231)
CMake version: version 3.18.1
Libc version: glibc-2.32

Python version: 3.8.16 (default, Mar  2 2023, 03:16:31)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.14.0-115.el7a.0.1.aarch64-aarch64-with-glibc2.26
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                192
On-line CPU(s) list:   0-191
Thread(s) per core:    1
Core(s) per socket:    48
Socket(s):             4
NUMA node(s):          4
Model:                 0
CPU max MHz:           2600.0000
CPU min MHz:           200.0000
BogoMIPS:              200.00
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              24576K
NUMA node0 CPU(s):     0-47
NUMA node1 CPU(s):     48-95
NUMA node2 CPU(s):     96-143
NUMA node3 CPU(s):     144-191
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0a0+git2418b94
[pip3] torch-npu==2.1.0
[pip3] torchvision==0.15.1
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.1.0a0+git2418b94          pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi

[torch-2.1.0.dev20230710-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl](https://download.pytorch.org/whl/nightly/cpu/torch-2.1.0.dev20230710-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl)

cc @malfet @seemethere

**Comment by heidongxianhua** [comment]
And we have noticed that, the nightly build whl does not specify the version depended whls, such `numpy`, on X86 it has been set to version of 1.15 with the command `pip install -q numpy==1.15`, but on ARM it install numpy with `/opt/conda/bin/conda install -y -c conda-forge python=3.8 numpy`, which will install the newest version. But it may cause error if the numpy version is not consistent when running torch.
And maybe the USE_LAPACK should be set to 1 by default on ARM.
@xncqr could you have a look?

**Comment by xncqr** [comment]
@heidongxianhua,
Can we get more specific on "may cause error" since numpy v1.15 is rather old and has many security vulnerabilities. It would be more apt to get numpy dependency updated for x86. Am concerned about version locking as it does add security risk and adds additional management overhead, as well as, conflicts with other projects like [benchmarks](https://github.com/pytorch/benchmark/blob/main/requirements.txt).

@snadampal,
Your thoughts on USE_LAPACK? you know any additional dependencies we might need to enable this and do we want this enabled?

**Comment by snadampal** [comment]
Hi @xncqr , I don't see any dependency, nor any conflicts to have USE_LAPACK. Please enable and see how the build goes. Thank you!

**Comment by xncqr** [comment]
@heidongxianhua,

Believe you are expecting the following:
```
import torch
a = torch.rand(2,3)
b = torch.linalg.qr(a)
print(b)
torch.return_types.linalg_qr(
Q=tensor([[-0.7239, -0.6899],
        [-0.6899,  0.7239]]),
R=tensor([[-0.9173, -1.0816, -1.1109],
        [ 0.0000, -0.0353, -0.1853]]))
```
need to add lapack-dev package to the OS. PyTorch will see it on build. Give a bit and will see about adding to the build process [here](https://github.com/pytorch/builder/blob/main/aarch64_linux/aarch64_ci_build.sh#L15). Need to test it out.

**Comment by heidongxianhua** [comment]
> @heidongxianhua,
> 
> Believe you are expecting the following:
> 
> ```
> import torch
> a = torch.rand(2,3)
> b = torch.linalg.qr(a)
> print(b)
> torch.return_types.linalg_qr(
> Q=tensor([[-0.7239, -0.6899],
>         [-0.6899,  0.7239]]),
> R=tensor([[-0.9173, -1.0816, -1.1109],
>         [ 0.0000, -0.0353, -0.1853]]))
> ```
> 
> need to add lapack-dev package to the OS. PyTorch will see it on build. Give a bit and will see about adding to the build process [here](https://github.com/pytorch/builder/blob/main/aarch64_linux/aarch64_ci_build.sh#L15). Need to test it out.

 I have made a test, when the torch version is 2.0.1 which installed by pip torch==2.0.1 on ARM64, it works well.
```
Python 3.8.16 (default, Mar  2 2023, 03:16:31)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.0.1'
>>> import os
>>> os.uname()
posix.uname_result(sysname='Linux', nodename='arm', release='4.14.0-115.el7a.0.1.aarch64', version='#1 SMP Sun Nov 25 20:54:21 UTC 2018', machine='aarch64')
>>> a = torch.rand(2,3)
>>> b = torch.linalg.qr(a)
>>> print(b)
torch.return_types.linalg_qr(
Q=tensor([[-0.5584, -0.8296],
        [-0.8296,  0.5584]]),
R=tensor([[-1.0044, -0.8398, -0.8006],
        [ 0.0000, -0.4937,  0.1233]]))
>>>
```

so for consistency,  maybe we should USE_LAPACK=1.

**Comment by heidongxianhua** [comment]
> @heidongxianhua, Can we get more specific on "may cause error" since numpy v1.15 is rather old and has many security vulnerabilities. It would be more apt to get numpy dependency updated for x86. Am concerned about version locking as it does add security risk and adds additional management overhead, as well as, conflicts with other projects like [benchmarks](https://github.com/pytorch/benchmark/blob/main/requirements.txt).
> 
> @snadampal, Your thoughts on USE_LAPACK? you know any additional dependencies we might need to enable this and do we want this enabled?

yeah, In https://github.com/pytorch/pytorch/actions/runs/5516843118/jobs/10058689778, on ARM64, it install numpy by conda pip install numpy, it will install the version of 1.24. And I meet the error is as following, and I have test it with numpy==1.22, 1.19, it does not work, it only works well when the version is greater or equal to 1.23. 
```
Python 3.8.16 (default, Mar  2 2023, 03:16:31)
>>> import torch
>>> import os
>>> import numpy as np
>>> torch.__version__
'2.1.0.dev20230710'
>>> os.uname()
posix.uname_result(sysname='Linux', nodename='arm', release='4.14.0-115.el7a.0.1.aarch64', version='#1 SMP Sun Nov 25 20:54:21 UTC 2018', machine='aarch64')
>>> np.__version__
'1.21.2'
>>> a = np.array([2,3])
>>> b = torch.from_numpy(a)
<stdin>:1: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xe . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Numpy is not available
>>> exit()
```

And on X86, I get the following, it works well when numpy version is 1.15, 1.19, 1.21, 1.23, 1.24
```
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
>>> import torch
>>> import os
>>> import numpy as np
>>> torch.__version__
'2.1.0.dev20230711+cpu'
>>> os.uname()
posix.uname_result(sysname='Linux', nodename='ubuntu', release='4.15.0-76-generic', version='#86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020', machine='x86_64')
>>> np.__version__
'1.15.0'
>>> a = np.array([2])
>>> b = torch.from_numpy(a)
```

And I notice that in the readme the suggested numpy version is 1.21.2 for python3.8, https://github.com/pytorch/pytorch/blob/main/.ci/docker/common/install_conda.sh#L62 , so on ARM64,maybe we set it to 1.21.2

**Comment by heidongxianhua** [comment]
And now I have give a PR to test it, could you have a look? @[xncqr](https://github.com/xncqr)

**Comment by xncqr** [comment]
@heidongxianhua,

Adding the lapack, as you are doing in the PR, will git pucked up by the build, adding to the wheels (tested this using ubuntu). I commented in your PR as I think you are trying to use the debian "lapack-dev" and would need to use the RHEL "lapack-devel". Otherwise the logic looks good.

**Comment by xncqr** [comment]
the plot thickens. Using ubuntu 20.04 and lapack-dev, resolves the issue, but using manylinux (centos7) with lapack-devel does not. Attempted with lapack lapack64 (and their devel packages) and the build does not include LAPACK. I even set USE_LAPACK=ON to force the issue and made no change.

In effect, I found OpenBlas builds with LAPACK but in our case, am seeing the following:
```
2023-07-17T01:41:45.2314139Z [33mCMake Warning at cmake/Modules/FindLAPACK.cmake:150 (message):
2023-07-17T01:41:45.2314683Z   OpenBlas has been compiled with Lapack support, but cgesdd can not be used
2023-07-17T01:41:45.2315151Z Call Stack (most recent call first):
2023-07-17T01:41:45.2315551Z   cmake/Dependencies.cmake:1725 (find_package)
2023-07-17T01:41:45.2315922Z   CMakeLists.txt:718 (include)
2023-07-17T01:41:45.2316131Z 
2023-07-17T01:41:45.2316267Z [0m
2023-07-17T01:41:45.2316710Z -- It seems OpenBlas has not been compiled with Lapack support
2023-07-17T01:41:45.2317260Z -- Cannot find a library with LAPACK API. Not using LAPACK.
```

I'm researching this issue. @snadampal, might need a bit of your assistance on this one. I do believe we can build OpenBLAS without LAPACK, but not sure if PyTorch will actually build with the LAPACK installed on the OS.

**Comment by xncqr** [comment]
Last night I attempted to build using OpanBLAS from the conda repository rather than building from source. This caused PyTorch build to not see BLAS and/or LAPACK. Working on a local setup to see if maybe a library path is missing as that feels like the case at this point. My last thought is to build OpenBLAS from source without LAPACK and then verify path for LAPACK.

Not really sure why all this mess with manylinux_2014 docker image over ubuntu:20.04 image, where adding LAPACK by package manager solves the issue. I would prefer to use ubuntu:20.04 but to maintain the manylinux compatibility, really need to use the manylinux_2014 image.

**Comment by xncqr** [comment]
Look like my assessment is correct from local testing. the library path where openblas and lapack are located were not making it through the build process. I have a fix under test ATM and will update on the results.

**Comment by xncqr** [comment]
@heidongxianhua, go ahead and close you PR. Build PR [#1462](https://github.com/pytorch/builder/pull/1462) solves the issue and am working to get it reviewed.

**Comment by xncqr** [comment]
to wrap this together. here is the one of the build logs with the update from PR [#1462](https://github.com/pytorch/builder/pull/1462) on the builder repo.
[1_manywheel-py3_10-cpu-aarch64-build  build.txt](https://github.com/pytorch/pytorch/files/12113403/1_manywheel-py3_10-cpu-aarch64-build.build.txt)
NOTE that OpenBlas and LAPACK are both being compiled now, which was not the case before.
```
2023-07-18T20:35:25.1073336Z --   USE_BLAS              : 1
2023-07-18T20:35:25.1073712Z --     BLAS                : open
2023-07-18T20:35:25.1074108Z --     BLAS_HAS_SBGEMM     : 
2023-07-18T20:35:25.1074504Z --   USE_LAPACK            : 1
2023-07-18T20:35:25.1074896Z --     LAPACK              : open
```
