### ISSUE TITLE
CPU Fallback does not handle input mutations on tensorlists

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#104965]
The CPUFallback code appears to not work properly if foreach ops like `_foreach_add_(..)`. hit the fallback. From a quick look:

This bit of the CPUFallback logic is meant to find all input arguments that are mutable tensors, and copy the mutated data back to the original input: https://github.com/pytorch/pytorch/blob/999abd56a7be3d73f0d2e9ab06356c7281a3307d/aten/src/ATen/native/CPUFallback.cpp#L109

We **only** check this for input args of type `Tensor` though, and not other arguments (namely `TensorList`). We already track input arguments of type TensorList here: https://github.com/pytorch/pytorch/blob/999abd56a7be3d73f0d2e9ab06356c7281a3307d/aten/src/ATen/native/CPUFallback.cpp#L77. We just need to loop through that list and mutate the inputs that have mutable alias annotations.

**Comment by FFFrog** [comment]
Hi, Can you assign this issue to me? Thank you a lot.
