### ISSUE TITLE
ONNX export process  failed to keep consistence of input_names specified

### ISSUE THREAD

**Issue by JohnHerry** [pytorch/pytorch#104949]
### 🐛 Describe the bug

When I use the torch.onnx.export to make the ONNX format model, the result onnx model, when loaded with onnxruntime, is failed to keep the input_names identical with my settings.

eg.
```
import torch
import torch.nn as nn

class MyModel(nn.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.layer = nn.Linear(10,  1)

    def forward(self, input_a, input_b=None):    # the input_b is not actually used in the forward computation 
         return self.layer(input_a)

#  Here we export the trained model!  the file "MyModel_checkpoint_file.pt" is the training result
my_model = torch.load("MyModel_checkpoint_file.pt")
my_model.eval()

input_names = ["input_a", "input_b"]
output_names = ["output"]
fake_input_a = torch.rand(10)
fake_input_b = torch.rand(10)
with torch.no_grad():
    torch.onnx.export(
         model=my_model,
         args = (fake_input_a, fake_input_b),
         f = "result.onnx",
         input_names = input_names,
         output_names = output_names
    )
```
Here I got a "result.onnx”  model file,  I specified that it should take two inputs, names "input_a", and "input_b";   although in fect the parameter "input_b" is not really used  in the graph.

But when I load the onnx model with onnxruntime

```
import onnxruntime
session = onnxruntime.InferenceSession("result.onnx", providers=["CPUExecutionProvider"])
for input in session.get_inputs():
    print(input.name)
```
the result  output string is only "input_a",  No "input_b" at All.

So there is an dis-consistence  between the exportation and inference.

I do not known  the detail of the onnx conversion, I guess that this process may have removed the input items that not really used in the final onnx graph.  But in my  view,  I would like to keep the input_names just as I had specified, even if it is not really used. So that in the software project using this model, the inference interface is fixed as I had designed. 

### Versions

python == 3.8.5
torch  == 1.10.2+cu111
onnxruntime == 1.14.1

**Comment by MaanavD** [comment]
Hi @JohnHerry ,

We’ve gone ahead and closed this issue because we think it can be resolved with our new `torch.onnx.dynamo_export` api. Please try that instead! If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. 

Thanks,
ONNX Converter team
