### ISSUE TITLE
Issue with documentation of torch.fake_quantize_per_tensor_affine

### ISSUE THREAD

**Issue by shreyas-bk** [pytorch/pytorch#105085]
### 📚 The doc issue

In the example provided at [https://pytorch.org/docs/stable/generated/torch.fake_quantize_per_tensor_affine.html#torch-fake-quantize-per-tensor-affine](https://pytorch.org/docs/stable/generated/torch.fake_quantize_per_tensor_affine.html#torch-fake-quantize-per-tensor-affine), I was confused about why there is a change in the output for when scale is made a tensor (torch.tensor(0.1)) and zero_point is made a tensor (torch.tensor(0)).

Even though the input x is the same, the reported values are different (tensor([0.1000, 1.0000, 0.4000, 0.0000]) vs tensor([0.6000, 0.4000, 0.0000, 0.0000])). When I test it locally, I get the same output tensor values. For example:

```
>>> import torch
>>> x = torch.randn(4)
>>> x
tensor([ 0.0960,  0.7145, -0.4411,  0.8018])
>>> torch.fake_quantize_per_tensor_affine(x, 0.1, 0, 0, 255)
tensor([0.1000, 0.7000, 0.0000, 0.8000])
>>> torch.fake_quantize_per_tensor_affine(x, torch.tensor(0.1), torch.tensor(0), 0, 255)
tensor([0.1000, 0.7000, 0.0000, 0.8000])
```

Shouldn't the example also have the same outputs?

Also, the formula for the output is given as:
`output=min(quant_max,max(quant_min,std::nearby_int(input/scale)+zero_point))
`

Since the function does fake quantization and dequantization, shouldn't the formula be:
`output=(min(quant_max,max(quant_min,std::nearby_int(input/scale)+zero_point))-zero_point)*scale
`

Thanks and please let me know if I've understood anything incorrectly.

### Suggest a potential alternative/fix

Rewrites to [https://github.com/pytorch/pytorch.github.io/blob/master/docs/2.0/generated/torch.fake_quantize_per_tensor_affine.html](https://github.com/pytorch/pytorch.github.io/blob/master/docs/2.0/generated/torch.fake_quantize_per_tensor_affine.html)

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by jcaip** [comment]
Yes @shreyas-bk, that documentation looks incorrect. Are you interested in making a PR to fix the outputs as well as the formula? If so feel free to add me as a reviewer.

**Comment by shreyas-bk** [comment]
Seems like it was covered in this PR #104453

**Comment by jcaip** [comment]
Ah gotcha, thanks for flagging this.

**Comment by shreyas-bk** [comment]
@jcaip the formula for torch.fake_quantize_per_channel_affine ([https://pytorch.org/docs/stable/generated/torch.fake_quantize_per_channel_affine.html](https://pytorch.org/docs/stable/generated/torch.fake_quantize_per_channel_affine.html)) should have a similar fix right? I can add a PR for that.

**Comment by jcaip** [comment]
@shreyas-bk Yes please do!
