### ISSUE TITLE
DISABLED test_compile_vmap_hessian_cuda (__main__.TestCompileTransformsCUDA)

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#105013]
Platforms: rocm

Disabling this unit test since it showed up in our local CI testing for ROCm5.6 CI upgrade PR: https://github.com/pytorch/pytorch/pull/103092

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @BLOrange-AMD

**Comment by huydhn** [comment]
Reopen this as I'm seeing this test is causing a memory leak on ROCm https://hud.pytorch.org/pytorch/pytorch/commit/3ca81aed4261f7bce3111c8905d979872f545f12
