### ISSUE TITLE
Optimizing Dispatch Key Set Operations in redispatch

### ISSUE THREAD

**Issue by yewentao256** [pytorch/pytorch#105028]
### 🚀 The feature, motivation and pitch

```c++
// torch/csrc/autograd/generated/VariableType_0.cpp
at::Tensor mul_Tensor(c10::DispatchKeySet ks, const at::Tensor & self, const at::Tensor & other) {
  // ...
  auto _tmp = ([&]() {
    at::AutoDispatchBelowADInplaceOrView guard;
    return at::redispatch::mul(ks & c10::after_autograd_keyset, self_, other_);
  })();
  auto result = std::move(_tmp);
  // ...
  return result;
}
```

Hello,  I notice that `at::AutoDispatchBelowADInplaceOrView guard` is used to add c10::autograd_dispatch_keyset_with_ADInplaceOrView to the local thread's exclude list. This set includes the following keys:

```c++
    DispatchKey::AutogradFunctionality,
    DispatchKey::AutogradOther,
    DispatchKey::AutogradNestedTensor,
    DispatchKey::ADInplaceOrView
```

However, the mul operation is then redispatched with a new dispatch key set, calculated as `ks & c10::after_autograd_keyset`.

The `c10::after_autograd_keyset` includes

```c++
constexpr DispatchKeySet after_autograd_keyset =
    DispatchKeySet(DispatchKeySet::FULL_AFTER, c10::DispatchKey::AutogradOther);
```

This process involves two steps:

1. Adding `c10::autograd_dispatch_keyset_with_ADInplaceOrView` to the exclude list.
2. Calculating `ks & c10::after_autograd_keyset` for redispatching.

It appears that for certain operations, such as multiplication, redispatching using `ks & c10::after_autograd_keyset` is sufficient.

I'm wondering if there's a way to optimize this into a single step. For instance, could we expand the range of the guard to avoid the need for calculating `ks & c10::after_autograd_keyset`? Alternatively, could we remove the guard and simply use `ks & c10::after_autograd_keyset_with_new_range` to redispatch the kernel?

However, I'm not sure if there are any scenarios where this could cause issues. For example, if we remove the guard and then use `ks & c10::after_autograd_keyset_new_range` to dispatch to kernel B, and kernel B subsequently requests another dispatch, could this result in a loop call returning to `VariableType_0.cpp`? If there are scenarios like this, could you please provide some insight?

Thank you for your time!

**Comment by ezyang** [comment]
The problem is that, after the initial redispatch, there may be further calls to the dispatcher, and only the exclude set ensures that they get skipped. So unfortunately I don't think your optimization works.

**Comment by yewentao256** [comment]
Yes, you're right. Only the exclude set ensures that some dispatch calls get skipped, I've confirmed this through compiling a local version of PyTorch myself.

For example:

With guard:

```bash
 [call] op=[aten::isfinite], key=[AutogradCPU]
  # ...
  [call] op=[aten::abs], key=[AutogradCPU]
   [redispatch] op=[aten::abs], key=[CPU]
    # ...
    [call] op=[aten::abs.out], key=[CPU]
```

Without guard:

```bash
[call] op=[aten::isfinite], key=[AutogradCPU]
  # ...
  [call] op=[aten::abs], key=[AutogradCPU]
   [redispatch] op=[aten::abs], key=[CPU]
    # ...
    [call] op=[aten::abs.out], key=[AutogradCPU]
     [redispatch] op=[aten::abs.out], key=[ADInplaceOrView]
      [redispatch] op=[aten::abs.out], key=[CPU]
```

Moreover, it's more adaptable to use a two-step process (1. a global limit, 2. a local calculation limit) to manage the dispatch procedure. Hence, I agree with your assessment that this optimization doesn't work. Thanks!
