### ISSUE TITLE
Inductor backend for CPU inference extremely slow

### ISSUE THREAD

**Issue by alexdauenhauer** [pytorch/pytorch#105075]
### 🐛 Describe the bug

related forum post https://discuss.pytorch.org/t/inductor-backend-for-cpu-inference-extremely-slow/183881

I was trying to compare using `torch.compile` to other optimization methods and doing this on CPU results in pretty unexpected behavior to me. I was attempting to compile a huggingface transformers model for text classification. Here are my machine specs
```python
# platform and psutils
Machine type: x86_64
Processor type: 
Platform type: Linux-4.19.0-24-cloud-amd64-x86_64-with-glibc2.28
Operating system: Linux
Operating system release: 4.19.0-24-cloud-amd64
Operating system version: #1 SMP Debian 4.19.282-1 (2023-04-29)
Number of physical cores: 4
Number of logical cores: 8
# cpuinfo
python_version: 3.10.11.final.0 (64 bit)
cpuinfo_version: [9, 0, 0]
cpuinfo_version_string: 9.0.0
arch: X86_64
bits: 64
count: 8
arch_string_raw: x86_64
vendor_id_raw: GenuineIntel
brand_raw: Intel(R) Xeon(R) CPU @ 2.30GHz
hz_advertised_friendly: 2.3000 GHz
hz_actual_friendly: 2.3000 GHz
hz_advertised: [2300000000, 0]
hz_actual: [2299998000, 0]
model: 63
family: 6
l3_cache_size: 47185920
l2_cache_size: 262144
l1_data_cache_size: 32768
l1_instruction_cache_size: 32768
l2_cache_line_size: 256
l2_cache_associativity: 6
```
When I follow [this tutorial](https://pytorch.org/tutorials/intermediate/inductor_debug_cpu.html#performance-profiling), I can see the speedup when I just run the same input over and over again with `timeit` like the tutorial does. I see about a 40% speedup which I guess is expected.

Where things become weird is when I try to run it on an actual set of unique texts (rather than the same input over and over). In this case the model starts to take an extremely long time to run, upwards of 10s per sample. Can someone help me understand what is going on here? Here is the code I am testing this with

```python
import time
import timeit
import random
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

NUM_ITERS = 50

### FOLLOWING TUTORIAL ###

# load base model
model_id = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_id)
base_model = AutoModelForSequenceClassification.from_pretrained(model_id)

# create inputs
text = "This is just a sample text I am using as a test."
# inputs = tokenizer(text, padding="max_length", return_tensors="pt")
inputs = tokenizer(text, return_tensors="pt")

# compile the model
print("compiling the model...")
comp_model = torch.compile(base_model)
with torch.no_grad():
    comp_model(**inputs)

print("running timeit on eager mode...")
with torch.no_grad():
    # warmup
    for _ in tqdm(range(10)):
        base_model(**inputs)
    
    eager_t = timeit.timeit("base_model(**inputs)", number=NUM_ITERS, globals=globals())

print("running timeit on compiled mode...")
with torch.no_grad():
    # warmup
    for _ in tqdm(range(10)):
        comp_model(**inputs)
    
    inductor_t = timeit.timeit("comp_model(**inputs)", number=NUM_ITERS, globals=globals())


# now run on a set of unique texts
sample_size = 10
sample = random.sample(TEXTS, 10)

print("running inference on base model...")
with torch.no_grad():
    # warmup
    for _ in tqdm(range(10)):
        base_model(**inputs)
    
    base_total_time = 0
    for text in tqdm(sample):
        new_inputs = tokenizer(text, return_tensors='pt')
        start = time.time()
        base_model(**new_inputs)
        base_total_time += time.time() - start

print("running inference on compiled mode...")
with torch.no_grad():
    # warmup
    for _ in tqdm(range(10)):
        comp_model(**inputs)
    
    comp_total_time = 0
    for text in tqdm(sample):
        new_inputs = tokenizer(text, return_tensors='pt')
        start = time.time()
        comp_model(**new_inputs)
        comp_total_time += time.time() - start

print(f"eager repeat inputs: {eager_t * 1000 / NUM_ITERS} ms/iter")
print(f"inductor repeat inputs: {inductor_t * 1000 / NUM_ITERS} ms/iter")
print(f"speed up ratio: {eager_t / inductor_t}")
print(f"eager unique inputs: {(base_total_time / sample_size) * 1000} ms/iter")
print(f"inductor unique inputs: {(comp_total_time / sample_size) * 1000} ms/iter")
# compiling the model...
# running timeit on eager mode...
# 100%|██████████| 10/10 [00:01<00:00,  9.14it/s]
# running timeit on compiled mode...
# 100%|██████████| 10/10 [00:00<00:00, 36.74it/s]
# running inference on base model...
# 100%|██████████| 10/10 [00:00<00:00, 28.27it/s]
# 100%|██████████| 10/10 [00:00<00:00, 15.81it/s]
# running inference on compiled mode...
# 100%|██████████| 10/10 [00:00<00:00, 38.31it/s]
# 100%|██████████| 10/10 [02:17<00:00, 13.78s/it]
# eager repeat inputs: 35.97641162000059 ms/iter
# inductor repeat inputs: 25.08608974000026 ms/iter
# speed up ratio: 1.4341179511382955
# eager unique inputs: 61.79332733154297 ms/iter
# inductor unique inputs: 13781.427097320557 ms/iter
``````

Additionally my VM also kept crashing which made me think it was running out of memory. I watched `htop` during the execution loop. each iteration the memory would jump up by 1G. So it must be compiling a new model on each iteration? How do I avoid the massive re-compile times in an inference loop? If I were serving this model wouldn't each inference call just act like the next iteration in an inference loop so I would expect the same behavior?

### Error logs

no error, just very very slow

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.28

Python version: 3.10.11 (main, May  3 2023, 17:22:50) [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-4.19.0-24-cloud-amd64-x86_64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:            0
CPU MHz:             2299.998
BogoMIPS:            4599.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            46080K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi

not using conda, it just exists on the VM from initial setup

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by XiaobingSuper** [comment]
@alexdauenhauer, could you help check the shapes of the unique input path? if the shapes are always changed, you can try to turn on the dynamic shapes feature to reduce the compile time(```torch._dynamo.config.automatic_dynamic_shapes = True``` and ```torch._dynamo.config.assume_static_by_default = False```).

**Comment by alexdauenhauer** [comment]
thank you @XiaobingSuper . When I try that I get this error
```python
AttributeError: torch._dynamo.config.automatic_dynamic_shapes does not exist
```

**Comment by ezyang** [comment]
Need a nightly

**Comment by alexdauenhauer** [comment]
ah ok thanks @ezyang . I installed the nightly and set those config options and now it appears to work
```python
eager repeat inputs: 34.528447820048314 ms/iter
inductor repeat inputs: 26.406813920184504 ms/iter
speed up ratio: 1.3075582659995153
eager unique inputs: 62.97576427459717 ms/iter
inductor unique inputs: 59.268784523010254 ms/iter
```
so a very small speed up. Thank you!
