### ISSUE TITLE
nGPUs_per_process in init_multigpu_helper is Wrong

### ISSUE THREAD

**Issue by qipengh** [pytorch/pytorch#105049]
### 🐛 Describe the bug

The key points:

- nGPUs is the total GPUs available

- world_size is the number of processes in the test

- If world_size < nGPUs, then each process can get multiple GPUs

In this case, we divide the total GPUs by the world size to determine the number of GPUs per process

- If world_size > nGPUs, then we have more processes than GPUs.

In this case, each process will get 1 GPU, which is handled separately.

Code now:
```python
def init_multigpu_helper(world_size: int, backend: str):
    """Multigpu tests are designed to simulate the multi nodes with multi
    GPUs on each node. Nccl backend requires equal #GPUs in each process.
    On a single node, all visible GPUs are evenly
    divided to subsets, each process only uses a subset.
    """
    nGPUs = torch.cuda.device_count()
    visible_devices = range(nGPUs)

    # If rank is less than or equal to number of available GPU's
    # then each rank can be mapped to corresponding GPU.
    nGPUs_per_process = 1
    if world_size > nGPUs:
        nGPUs_per_process = nGPUs // world_size
    rank_to_GPU = {
        i: list(visible_devices[i * nGPUs_per_process : (i + 1) * nGPUs_per_process])
        for i in range(world_size)
    }
    return rank_to_GPU
```
I think the correct code is this:
```python
    if world_size < nGPUs:
        nGPUs_per_process = nGPUs // world_size
```

### Versions

https://github.com/pytorch/pytorch/blob/main/torch/testing/_internal/common_distributed.py#L451

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by kumpera** [comment]
I reviewed the usage of init_multigpu_helper and all cases follow `world_size <= nGPUs` so while the code is wrong, it's not a practical problem.

Besides that, we should remove usage of init_multigpu_helper as the underlying feature is scheduled for removal soon.
