### ISSUE TITLE
I don't how to bulid pytorch in my cpu

### ISSUE THREAD

**Issue by miaowahexiaohuolong** [pytorch/pytorch#105047]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

my cpu is ppcle64

- PyTorch or Caffe2: i want to bulid pytorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS: Contens8
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by davidradl** [comment]
hi, did you follow [https://github.com/pytorch/pytorch/blob/main/CONTRIBUTING.md](https://github.com/pytorch/pytorch/blob/main/CONTRIBUTING.md) on building locally. If so what did not work?

I see a very old version for this cpu in anaconda [https://conda.anaconda.org/pytorch/linux-ppc64le/](https://conda.anaconda.org/pytorch/linux-ppc64le/).
I am not sure what the eligible list of cpus are for PyTorch. I see the list of backends (cpu, cuda etc) - I suspect if there is anything special needed for a power cpu, then you would need a custom backend.

**Comment by miaowahexiaohuolong** [comment]
i was so happy that you help my to find this https://conda.anaconda.org/pytorch/linux-ppc64le/.  And now i know the pytorch can be used in my cpu. But i want to know how to bulid this pytorch and which pytorch'version can i use.  I use the contributing.md but it doesn't work

**Comment by soulitzer** [comment]
Hey! Closing as issues are for bug reports and feature requests only, for questions please visit the forum https://discuss.pytorch.org/
