### ISSUE TITLE
torch.load error on OSX  'module' object has no attribute '_rebuild_tensor'

### ISSUE THREAD

**Issue by cheezer** [pytorch/pytorch#1050]
Hi, 

I encounter the following error when I load the data using torch.load.

Traceback (most recent call last):
  File "/Users/qzxie/workspace/openNMT/src/train_bucket.py", line 358, in main
    dataset = torch.load(data)
  File "/Users/qzxie/tools/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 222, in load
    return _load(f, map_location, pickle_module)
  File "/Users/qzxie/tools/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 370, in _load
    result = unpickler.load()
AttributeError: 'module' object has no attribute '_rebuild_tensor'

I tried to load the same data on linux. It worked fine.

I think the error is due to a recent update of either torch.save or torch.load. The error appeared after I updated my pytorch yesterday.

**Comment by colesbury** [comment]
You've saved your data file with a newer version of PyTorch and tried loading it with an older version of PyTorch.  Your Linux machine is running PyTorch built from master. To load the file on your Mac, you need to build from source or wait until Wednesday when the new version of PyTorch is released.

**Comment by cheezer** [comment]
Thanks! I have already tried to build from source on Mac. Is it OK to just run git pull and python setup.py install?

**Comment by soumith** [comment]
see readme for exact instructions

**Comment by hyqneuron** [comment]
I'm having the same issue. I tried building from source and still the same. How do I verify I'm importing the one I built locally? Previously I was using the one installed through wheel.

**Comment by apaszke** [comment]
```
>>> import torch
>>> torch.__file__
```

**Comment by hyqneuron** [comment]
@apaszke lol `torch.__file__` isn't as informative as it should be. It just pointed me to `/usr/local/lib/python2.7/...`. But I've uninstalled all the previous torch packages installed through pip and rerun the local setup script and it seems to work!

**Comment by rishabh135** [comment]
I am also facing the same issue and I am pretty sure that I have the most recent version of pytorch (0.1.10+ac) , can somebody resolve this issue ? My config : Linux .0-95-generic #142-Ubuntu  x86_64 x86_64 x86_64 GNU/Linux

`
>>> import torch
>>> torch.__version__
'0.1.10+ac9245a'
>>> execfile("main_model.py")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "main_model.py", line 123, in <module>
    vgg.load_state_dict(torch.load(model_dir + 'vgg_conv.pth'))
  File "/users/gpu/arishabh/anaconda2/envs/opencv2/lib/python2.7/site-packages/torch/serialization.py", line 222, in load
    return _load(f, map_location, pickle_module)
  File "/users/gpu/arishabh/anaconda2/envs/opencv2/lib/python2.7/site-packages/torch/serialization.py", line 370, in _load
    result = unpickler.load()
AttributeError: 'module' object has no attribute '_rebuild_tensor'

`

**Comment by hyqneuron** [comment]
The newest is 0.1.11. Try that. The pip version also works. 

Yunqing
