### ISSUE TITLE
test_view_dynamic_zero_dim no longer testing zero input

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#105066]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/pull/104828#discussion_r1261361082

Filing an issue as requested by @thiagocrepaldi @titaiwangms 

I don't think the exported model should work with a zero size input. The reason is that we 0/1 specialize on tracing; when you trace a model that has size 2, we assume that if you dynamically vary the shape, you won't vary it to 0 or 1. It is strange to have a model that exports and works with either size 0, or size 2.

If there is a more realistic example, we should put it in here instead.

### Versions

main

**Comment by BowenBao** [comment]
iiuc the unittest's intention could be to op test scenarios from rcnn models where it may return zero boxes depending on input image. Based on recommendation, I suppose we should add a larger snippet that doesn't start for size 0 input but captures how one is emitted in the middle/output. 

@ezyang Do you happen to know if such behavior from vision models is dynamically supported by symbolic tracing?

**Comment by ezyang** [comment]
Zero size input is legitimate, we sort of support this: if you ask whether or not something is equal to zero, we will always say False, but the hypothesis is the traced graph will work anyway for the zero case.

**Comment by titaiwangms** [comment]
Re-enable in #127349
