### ISSUE TITLE
cudagraph tree segfault

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#105169]
### 🐛 Describe the bug

```
        def test_dynamic_backward(self):
            @torch.compile(mode="reduce-overhead")
            def foo(x):
                x = torch.cat([x, x])
                return torch.addmm(x, x, x).relu(), x.size(0)

            inp = torch.randn(2, 4, device="cuda", requires_grad=True)
            r1, s1 = foo(inp)
            r1.sum().backward()
            g1 = inp.grad
            inp.grad = None
            r2, s2 = foo(inp)
            r2.sum().backward()
            g2 = inp.grad
            inp.grad = None
            self.assertEqual(r1, r2)
            self.assertEqual(s1, s2)
            self.assertEqual(g1, g2)
```

put this test in test/inductor/test_cudagraph_trees.py and it segfaults

### Versions

main

cc @gchanan @zou3519 @mcarilli

**Comment by ezyang** [comment]
backtrace https://gist.github.com/ezyang/42d16b73c898068a8c286a374f198970

**Comment by ezyang** [comment]
cc @eellison

**Comment by eellison** [comment]
I can repro this in the test file, but weirdly enough when run in a stand alone file there is no error.

**Comment by eellison** [comment]
If you add:

```
            r1 + r1
            self.assertEqual(r1, r2)
```

You get 

> RuntimeError: Error: accessing tensor output of CUDAGraphs that has been overwritten by a subsequent run. Stack trace: File "/home/eellison/pytorch/test/inductor/test_cudagraph_trees.py", line 213, in foo
    return torch.addmm(x, x, x).relu(), x.size(0). To prevent overwriting, clone the tensor outside of torch.compile() before running the model again.

I'll try to more robustly mark it invalid.

**Comment by eellison** [comment]
This no longer repros, and have pr for better error msg here: https://github.com/pytorch/pytorch/pull/109750
