### ISSUE TITLE
PT2 custom ops does not work with future annotations

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#105157]
PT2 custom ops does not work with future annotations

_Originally posted by @BowenBao in https://github.com/pytorch/pytorch/pull/105156#discussion_r1262892912_
            

Repro:
```python
from __future__ import annotations

import torch

@torch.library.custom_op("mylibrary::foo_op", mutates_args={})
def foo_op(x: torch.Tensor) -> torch.Tensor:
    return x.clone()


```
`ValueError: custom_op(...)(func): Parameter x has unsupported type torch.Tensor. The valid types are: dict_keys([<class 'torch.Tensor'>, typing.Union[torch.Tensor, NoneType], typing.Sequence[torch.Tensor], typing.Sequence[typing.Union[torch.Tensor, NoneType]], <class 'int'>, typing.Union[int, NoneType], typing.Sequence[int], typing.Union[typing.Sequence[int], NoneType], <class 'float'>, typing.Union[float, NoneType], typing.Sequence[float], typing.Union[typing.Sequence[float], NoneType], <class 'bool'>, typing.Union[bool, NoneType], typing.Sequence[bool], typing.Union[typing.Sequence[bool], NoneType], <class 'str'>, typing.Union[str, NoneType], typing.Union[int, float, bool], typing.Union[int, float, bool, NoneType], typing.Sequence[typing.Union[int, float, bool]], <class 'torch.dtype'>, typing.Union[torch.dtype, NoneType], <class 'torch.device'>, typing.Union[torch.device, NoneType]]). Got func with signature (x: 'torch.Tensor') -> 'torch.Tensor')`

cc @ezyang @anijain2305 @chauhang @zou3519 @bdhirsh @msaroufim @wconstab

**Comment by ezyang** [comment]
cc @zou3519

**Comment by zou3519** [comment]
Thanks for the bug report. We're still in the middle of developing this API, I will take a look

**Comment by mlazos** [comment]
@zou3519 following up, is this still an issue?

**Comment by zou3519** [comment]
still an issue
