### ISSUE TITLE
MacOS arm64 runners are not available in CI

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#105108]
## Current Status
mitigated

## Error looks like
MacOS arm64 runners are not available following build will fail: ``trunk / macos-12-py3-arm64 / build``

## Incident timeline (all times pacific)
Jul 12 7:40 pm EST First job failed
Jul 12 8:56 pm EST as OSS CI oncall this issue is noticed and investigation is started
Jul 13 12:40AM EST runner reprovisioned

## User impact
MacOS arm64 runners are not available following build will fail: ``trunk / macos-12-py3-arm64 / build``

## Root cause
github daemon auto-updated in all instances at the same time, downloading a new version and then failing to start.

## Mitigation
tbd

## Prevention/followups
tbd

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
@atalman timeline does not seem to
be reported in correct timezone (it says detected at 8:56pst, but right now is 8:09pst)

**Comment by atalman** [comment]
runner reprovision is completed,  setting this as mitigated

**Comment by huydhn** [comment]
Closing this now as this is old and has been mitigated.
