### ISSUE TITLE
RuntimeError with AdaptiveMaxPool3d in certain conditions

### ISSUE THREAD

**Issue by GwiHwan-Go** [pytorch/pytorch#105113]
### 🐛 Describe the bug

I've found that a RuntimeError is thrown when using the torch.nn.AdaptiveMaxPool3d module with an output size of [0, 0, 0] with other layers.

The RuntimeError raised in this context states: adaptive_avg_pool3d_backward(): Expected grad_output to have non-zero size for non-batch dimensions, but grad_output has sizes [2, 0, 0, 0] with dimension 1 being empty.

Here's a repro code
```python
import torch
from torch import nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc = nn.Linear(1,2)
        self.pool = nn.AdaptiveMaxPool3d(output_size=[0, 0, 1], return_indices=True)

    def forward(self, x):
        x = self.fc(x)
        print('After fc', x.size())
        x = self.pool(x)
        
        return x

# Model instantiation
model = MyModel()

# Input definition
input_tensor = torch.rand([2, 2, 1, 1])

# Forward pass
model(input_tensor)  # No error

# Model compilation and forward pass
torch.compile(model)(input_tensor)  # RuntimeError
```
🧐 Expected Behavior
Although setting the output size to [0, 0, 0] in AdaptiveMaxPool3d could be considered as unusual usage, this error does not arise when I run this code without torch.compile(). I would expect consistency between the behavior of the non-compiled and compiled versions of the model. If this discrepancy is intended behavior, please feel free to close this issue.
Please let me know if there's any additional information that could assist in resolving this issue. I'd be happy to help further.

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+440fd1bf20
[pip3] torch==2.1.0.dev20230709+cu121
[pip3] torchaudio==2.1.0.dev20230709+cu121
[pip3] torchvision==0.16.0.dev20230709+cu121
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+440fd1bf20          pypi_0    pypi
[conda] torch                     2.1.0.dev20230709+cu121          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230709+cu121          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230709+cu121          pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by ZailiWang** [comment]
Please refer the analysis
https://github.com/pytorch/pytorch/issues/105057#issuecomment-1633658478

**Comment by GwiHwan-Go** [comment]
#105057
