### ISSUE TITLE
Support an option to keep weights as attributes in aot_autograd

### ISSUE THREAD

**Issue by tehbone** [pytorch/pytorch#105188]
### 🚀 The feature, motivation and pitch

I am looking at a `torch.compile()` backend and with the current `aot_autograd()` implementation the created graphmodule treats all of the module parameters as input to the graph module. Since in my particular use case I know the parameters are frozen, I'd like to be able to precalculate subgraphs which depend on such parameters. Perhaps an additional parameter on the aot_autograd() invocation could control this behavior?

### Additional context

Sample model:
```python
class Model(nn.Module):
    def __init__(self, i, o):
        super().__init__()
        self._w = nn.Parameter(torch.randn((o, i)))
        self._b = nn.Parameter(torch.randn((o)))

    def forward(x):
        return torch.addmm(self._b, x, (self._w * self._w * self._w).t())
```
After compilation with aot_autograd yields:
```
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: f32[4096], arg1_1: f32[4096, 1024], arg2_1: f32[100, 1024]):
        mul: f32[4096, 1024] = torch.ops.aten.mul.Tensor(arg1_1, arg1_1)
        mul_1: f32[4096, 1024] = torch.ops.aten.mul.Tensor(mul, arg1_1);  mul = arg1_1 = None
        t: f32[1024, 4096] = torch.ops.aten.t.default(mul_1);  mul_1 = None
        addmm: f32[100, 4096] = torch.ops.aten.addmm.default(arg0_1, arg2_1, t);  arg0_1 = arg2_1 = t = None
        return (addmm,)
```
This is a rather extreme example, but the only necessary argument to the module is `arg2_1`.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by Chillee** [comment]
cc: @eellison

**Comment by eellison** [comment]
This is implemented but not yet really documented with `torch._inductor.config.freezing`. There's a little bit of a write up about it here: https://github.com/pytorch/pytorch/issues/103990 (although that's mostly about another issue).

**Comment by tehbone** [comment]
Does that imply use of the inductor backend?

**Comment by eellison** [comment]
It does, but you could do something similar in your backend. Is your backend using aot_autograd ?

**Comment by tehbone** [comment]
Thanks for the tip. It is using `aot_autograd`, and I'm able to emulate the functionality with my own backend.

**Comment by eellison** [comment]
Cool, i'm going to close this issue then. If this comes up again for different backend maybe we can standardize this into a backend api, but for now going to leave as is.
