### ISSUE TITLE
Custom Symbolic Function Registration for ONNX Error 

### ISSUE THREAD

**Issue by NickGeneva** [pytorch/pytorch#105160]
### 🐛 Describe the bug

The `register_custom_op_symbolic` function, part of `torch.onnx` does not see to be working properly for me. 
I am following this simple example found in the [documentation](https://pytorch.org/docs/stable/onnx.html#c-operators) using a contributed operator thats part of onnxruntime-gpu. I noted that the [ONNX unit tests](https://github.com/pytorch/pytorch/blob/main/test/onnx/test_custom_ops.py) do not check the functionality using a custom namespace, so I am assuming this doc example is correct. I tried to do some digging into the [`torch/_ops.py`](https://github.com/pytorch/pytorch/blob/main/torch/_ops.py#L707) but was not able to follow how ops are dynamically created.

I am running in the [Nvidia PyTorch container 23.06](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags), only additional install I do is `pip install onnxruntime-gpu`.

I cannot get the symbolic operation to register properly (I can't call it from torch.ops). Here's a minimal example (based on the example in the docs linked above):

```
# Create custom symbolic function

import torch
from torch.onnx.symbolic_helper import parse_args
@parse_args('v', 'i')
def symbolic_foo_forward(g: torch.Graph, input: torch.Value, ndim: int):
    output = g.op(
        "com.microsoft::Rfft",
        input,
        normalized_i=0,
        onesided_i=1,
        signal_ndim_i=ndim,
    )
    return output

# Register custom symbolic function
from torch.onnx import register_custom_op_symbolic
register_custom_op_symbolic('custom_ops::foo_forward', symbolic_foo_forward, 9)

class FooModel(torch.nn.Module):
    def __init__(self, ndim):
        super(FooModel, self).__init__()
        self.ndim = ndim

    def forward(self, input1):
        # Calling custom op
        return torch.ops.custom_ops.foo_forward(input1, self.ndim)


dummy_input1 = torch.randn(3,3,3)
model = FooModel(1)
torch.onnx.export(model, (dummy_input1), 'model.onnx')
```

The error is related to accessing the symbolic ops in PyTorch, so I am guessing its an issue with this register function. I would expect `torch.ops.custom_ops.foo_forward` to be callable since I registered the operator.

```
=========== Diagnostic Run torch.onnx.export version 2.1.0a0+4136153 ===========
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 709, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator custom_ops::foo_forward

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/gh-forks/modulus/fft_testing.py", line 32, in <module>
    torch.onnx.export(model, (dummy_input1), 'model.onnx')
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 507, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1567, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1124, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1000, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 904, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/workspace/gh-forks/modulus/fft_testing.py", line 27, in forward
    return torch.ops.custom_ops.foo_forward(input1, self.ndim)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 713, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'custom_ops' object has no attribute 'foo_forward'

```

Any help would be appreciated, thanks!

### Versions

```
[pip3] numpy==1.22.2
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.1.0a0+4136153
[pip3] torch-tensorrt==1.5.0.dev0
[pip3] torchdata==0.7.0a0
[pip3] torchtext==0.16.0a0
[pip3] torchvision==0.16.0a0
[pip3] triton==2.1.0
[conda] Could not collect
```

**Comment by justinchuby** [comment]
I understand `torch.ops.custom_ops.foo_forward` does not exist as a torch op. You would still need to use a valid torch operator in your model.

**Comment by NickGeneva** [comment]
Thanks for the reply @justinchuby 

I was under the impression the `register_custom_op_symbolic('custom_ops::foo_forward', symbolic_foo_forward, 9)` would do this for me in Python. At least this is what my take away from the example I linked and [api docs](https://github.com/pytorch/pytorch/blob/main/torch/onnx/utils.py#L1981) was.

There are also some info in the [ONNX documentation](https://github.com/onnx/tutorials/blob/main/PyTorchCustomOperator/README.md#export-the-operator-to-onnx) on this but some of it seems a little mixed up between namespace and domain. Perhaps I am missing something.

**Comment by justinchuby** [comment]
This registration will only link an existing torch operator with the ONNX representation for the torch.onnx exporter, but the op needs to be valid for torch JIT to run in the first place, before we can export. I think there is a different mechanism for registering custom ops in dynamo which may be easier. @BowenBao do you have more info?

**Comment by NickGeneva** [comment]
Thanks for the clarification @justinchuby 

So this test in the [onnx/caffe folder](https://github.com/pytorch/pytorch/blob/main/test/onnx_caffe2/test_custom_ops.py#L13) would be more inline with the process. 

I suppose I was getting confused in the [documented example](https://pytorch.org/docs/stable/onnx.html#c-operators) with `custom_domain::Foo` and `custom_ops::foo_forward`. It still not exactly clear what is what.

For example in the [onnx/caffe test](https://github.com/pytorch/pytorch/blob/main/test/onnx_caffe2/test_custom_ops.py#L13):
```
   op_source = """
        #include <torch/script.h>

        torch::Tensor custom_add(torch::Tensor self, torch::Tensor other) {
          return self + other;
        }

        static auto registry =
          torch::RegisterOperators("custom_namespace::custom_add", &custom_add);
        """

        torch.utils.cpp_extension.load_inline(
            name="custom_add",
            cpp_sources=op_source,
            is_python_module=False,
            verbose=True,
        )

        class CustomAddModel(torch.nn.Module):
            def forward(self, a, b):
                return torch.ops.custom_namespace.custom_add(a, b)

        def symbolic_custom_add(g, self, other):
            return g.op("Add", self, other)

       torch.onnx.register_custom_op_symbolic(
            "custom_namespace::custom_add", symbolic_custom_add, 9
        )
```
the C++ operator is registered under `custom_namespace::custom_add` which is used in the python register function. But the `g.op()` just has `Add`. Which is confusing, what is the `g.op()` linking to then, the ONNX operator?

In my case `com.microsoft::Rfft` is the ONNX contributed symbolic operation that I want to link to Pytorch's `rfft`. So would I register this under `fft::rfft` or something of that spirit?

**Comment by justinchuby** [comment]
Yes. 

register_custom_op_symbolic('aten::rfft', symbolic_foo_forward, 9)

seems to be what you would want
