### ISSUE TITLE
torch.compile leaks memory after compiled object is deleted, no apparent way to clean

### ISSUE THREAD

**Issue by CoffeeVampir3** [pytorch/pytorch#105181]
### 🐛 Describe the bug

Consider a program like this:
```
pipe = StableDiffusionXLPipeline.from_pretrained(base_model_path, torch_dtype=torch.float16, use_safetensors=True, variant="fp16")
pipe.to("cuda")
pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)

#...
for x in pipe.__module__:
    del x
del pipe
gc.collect()
torch.cuda.empty_cache()
torch.cuda.synchronize()
```

After deleting pipe their is still a tremendous amount of memory residing on the gpu as a result of torch.compile. IF torch.compile is omitted in this program, their is only a small amount of residual memory leaked by torch. However, there's more than 10+GB leaked as a result of compile that has no obvious way of being cleaned. Is their a way to clean up compiled graph memory?

### Minified repro

```
from diffusers import DiffusionPipeline
import torch, gc
#Any model will suffice for demonstration, this is from huggingface diffusers
pipe = DiffusionPipeline.from_pretrained(base_model_path, torch_dtype=torch.float16, use_safetensors=True, variant="fp16")
pipe.to("cuda")
pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)

#...
for x in pipe.__module__:
    del x
del pipe
gc.collect()
torch.cuda.empty_cache()
torch.cuda.synchronize()
```

### Versions

python3 collect_env.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21653  100 21653    0     0   4126      0  0:00:05  0:00:05 --:--:--  4352
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: EndeavourOS Linux (x86_64)
GCC version: (GCC) 12.3.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.37

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-6.4.3-arch1-1-x86_64-with-glibc2.37
Is CUDA available: True
CUDA runtime version: 12.2.91
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090 Ti
GPU 1: NVIDIA RTX A4000

Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.9.2
/usr/lib/libcudnn_adv_infer.so.8.9.2
/usr/lib/libcudnn_adv_train.so.8.9.2
/usr/lib/libcudnn_cnn_infer.so.8.9.2
/usr/lib/libcudnn_cnn_train.so.8.9.2
/usr/lib/libcudnn_ops_infer.so.8.9.2
/usr/lib/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          20
On-line CPU(s) list:             0-19
Vendor ID:                       GenuineIntel
Model name:                      12th Gen Intel(R) Core(TM) i7-12700KF
CPU family:                      6
Model:                           151
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        2
CPU(s) scaling MHz:              50%
CPU max MHz:                     5000.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7222.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       512 KiB (12 instances)
L1i cache:                       512 KiB (12 instances)
L2 cache:                        12 MiB (9 instances)
L3 cache:                        25 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-19
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced / Automatic IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] lion-pytorch==0.1.2
[pip3] lovely-numpy==0.2.9
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-lightning==1.9.4
[pip3] torch==2.0.1
[pip3] torchaudio==2.1.0.dev20230630
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.11.4
[pip3] torchsde==0.2.5
[pip3] torchvision==0.16.0.dev20230630
[pip3] triton==2.0.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] lion-pytorch              0.1.2                    pypi_0    pypi
[conda] lovely-numpy              0.2.9                    pypi_0    pypi
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] open-clip-torch           2.20.0                   pypi_0    pypi
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch-nightly
[conda] pytorch-lightning         1.9.4                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230630     py310_cu121    pytorch-nightly
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchsde                  0.2.5                    pypi_0    pypi
[conda] torchvision               0.16.0.dev20230630     py310_cu121    pytorch-nightly
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @ipiszy

**Comment by ezyang** [comment]
Try torch._dynamo.reset()?

**Comment by williamwen42** [comment]
I'm having trouble repro'ing - I get 7794MiB allocated before the `del`s, but afterward, I only get 848MiB. Maybe also try setting things to `None` instead of `del`'ing? I found in my own personal testing elsewhere that this helped.

If you're still seeing a memory leak, can you confirm if you still see leaks with the `eager` or `aot_eager` backends?

**Comment by CoffeeVampir3** [comment]
With either None or del it's the same result for me. You can see here on nvtop, the slight dip at the end here (far right) shows some memory was in fact deleted, but there's still a huge amount of memory retained.

![image](https://github.com/pytorch/pytorch/assets/48565901/a8c6d30f-4dcc-4198-bdf4-5a8b42ba5e7d)

Here is the exact same program, where I've simply commented out the torch.compile:
![image](https://github.com/pytorch/pytorch/assets/48565901/808e8255-4f53-41a3-83d1-ce6b19d6d098)

Using backend="eager" (same result as dynamo)
![image](https://github.com/pytorch/pytorch/assets/48565901/5dda0985-f213-42a7-b788-0b98790bbfac)

Using backend="aot_eager" (same result as dynamo)
![image](https://github.com/pytorch/pytorch/assets/48565901/988dafbb-e759-46f1-8346-94ccd2800fdf)

Dynamo reset is working and drops the memory correctly:
```
for x in pipe.__module__:
    del x
del pipe
gc.collect()
torch._dynamo.reset()
torch.cuda.empty_cache()
torch.cuda.synchronize()
```
![image](https://github.com/pytorch/pytorch/assets/48565901/bc73e297-692c-4d81-add0-4d18e49493a4)

I'm unsure how to leave this issue and I'll leave it to your discretion. Cheers.

**Comment by ezyang** [comment]
I think the residual memory is too big for it to be only this, but remember that the CUDA context also takes up GPU memory and it won't get freed even if you reset.

**Comment by ezyang** [comment]
https://zdevito.github.io/2022/08/16/memory-snapshots.html may be helpful

**Comment by Fidget-Spinner** [comment]
It might possibly help a little if we deleted and reinitialized the entire `eval_frame` module as well in `torch._dynamo.reset()` after https://github.com/pytorch/pytorch/pull/109419 is merged. That should force any references the module itself holds to be free.

**Comment by mlazos** [comment]
@CoffeeVampir3,  does a `torch._dynamo.reset()` help this issue? There have been some improvements around this as well. Can you try running on the latest nightly?

cc @williamwen42

**Comment by anijain2305** [comment]
Closing this for now because of lack of reproduction. Please feel free to reopen if you see the issue.
