### ISSUE TITLE
third_party FP16 @ 43d6d17 won't compile with Intel compiler

### ISSUE THREAD

**Issue by sparticlesteve** [pytorch/pytorch#10523]
## Issue description

PyTorch master currently uses FP16 @ 43d6d17, but this misses this typo fix which is critical for Intel compilers:
https://github.com/Maratyszcza/FP16/commit/785a90fce76bda2a8d23a800a1c9fb8fab114584

Hopefully I don't need to provide any additional details to motivate this. It should be clear that this line in the buggy version cannot compile (and I confirmed when trying to build v0.4.1):
https://github.com/Maratyszcza/FP16/blob/43d6d17df48ebf622587e7ed9472ea76573799b9/include/fp16/bitcasts.h#L18

Can we bump the FP16 version?

**Comment by Maratyszcza** [comment]
I will take it
