### ISSUE TITLE
Enable Mypy Checking in torch/_inductor

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#105230]
### 🚀 The feature, motivation and pitch

Type checking can find bugs, but more importantly serves as documentation. We should enable mypy type checking for inductor.   

To enable a file remove it from [the `MYPYNOFOLLOW` exclude list](https://github.com/pytorch/pytorch/blob/main/.lintrunner.toml#L199). Tag yourself next to a file if you are working on it. Then run mypy on the file locally to see what needs to be fixed. 

Especially if you are new to pytorch or inductor, I would recommend using https://github.com/Instagram/MonkeyType as an aide and running part of the inductor test suite: `test/inductor/test_torchinductor.py`

- [x] torch/_inductor/autotune_process.py
- [x] torch/_inductor/codegen/__init__.py
- [x] torch/_inductor/codegen/triton_foreach.py (@mlazos)
- [x] torch/_inductor/codegen/triton_utils.py (@masnesral)
- [x] torch/_inductor/codegen/common.py
- [x] torch/_inductor/codegen/cpp.py (@masnesral)
- [x] torch/_inductor/codegen/triton.py (@masnesral)
- [x] torch/_inductor/codegen/wrapper.py
- [x] torch/_inductor/coordinate_descent_tuner.py
- [x] torch/_inductor/cuda_properties.py https://github.com/pytorch/pytorch/pull/105620
- [x] torch/_inductor/exc.py https://github.com/pytorch/pytorch/pull/109176
- [x] torch/_inductor/freezing.py (@int3)
- [x] torch/_inductor/fx_passes/__init__.py
- [x] torch/_inductor/fx_passes/freezing_patterns.py
- [x] torch/_inductor/fx_passes/mkldnn_fusion.py https://github.com/pytorch/pytorch/pull/108131
- [x] torch/_inductor/fx_passes/pre_grad.py https://github.com/pytorch/pytorch/pull/109952
- [x] torch/_inductor/fx_passes/quantization.py https://github.com/pytorch/pytorch/pull/108131
- [x] torch/_inductor/fx_passes/replace_random.py
- [x] torch/_inductor/fx_passes/split_cat.py https://github.com/pytorch/pytorch/pull/109951
- [x] torch/_inductor/fx_passes/fuse_attention.py
- [x] torch/_inductor/fx_passes/group_batch_fusion.py (@int3)
- [x] torch/_inductor/fx_passes/joint_graph.py https://github.com/pytorch/pytorch/pull/109955
- [x] torch/_inductor/fx_passes/pad_mm.py https://github.com/pytorch/pytorch/pull/109954
- [x] torch/_inductor/fx_passes/post_grad.py
- [x] torch/_inductor/fx_utils.py (@int3)
- [x] torch/_inductor/hooks.py
- [x] torch/_inductor/kernel/__init__.py (@masnesral)
- [x] torch/_inductor/kernel/bmm.py (@masnesral)
- [x] torch/_inductor/kernel/conv.py
- [x] torch/_inductor/kernel/mm.py (@masnesral)
- [x] torch/_inductor/kernel/mm_common.py
- [x] torch/_inductor/kernel/mm_plus_mm.py (@masnesral)
- [x] torch/_inductor/metrics.py
- [x] torch/_inductor/scheduler.py (@ipiszy) #105600
- [x] torch/_inductor/select_algorithm.py
- [x] torch/_inductor/test_operators.py
- [x] torch/_inductor/triton_helpers.py
- [x] torch/_inductor/virtualized.py https://github.com/pytorch/pytorch/pull/108916
- [x] torch/_inductor/config.py
- [x] torch/_inductor/__init__.py
- [x] torch/_inductor/bounds.py (@masnesral)
- [x] torch/_inductor/codecache.py (@masnesral)
- [x] torch/_inductor/compile_fx.py https://github.com/pytorch/pytorch/pull/105830
- [x] torch/_inductor/cudagraph_trees.py
- [x] torch/_inductor/debug.py https://github.com/pytorch/pytorch/pull/109335
- [x] torch/_inductor/decomposition.py (@masnesral)
- [x] torch/_inductor/dependencies.py
- [x] torch/_inductor/graph.py
- [x] torch/_inductor/index_propagation.py https://github.com/pytorch/pytorch/pull/105622
- [x] torch/_inductor/inductor_prims.py https://github.com/pytorch/pytorch/pull/109173
- [x] torch/_inductor/ir.py (@int3)
- [x] torch/_inductor/lowering.py (@aakhundov)
- [x] torch/_inductor/optimize_indexing.py https://github.com/pytorch/pytorch/pull/105621
- [x] torch/_inductor/pattern_matcher.py (@int3)
- [x] torch/_inductor/sizevars.py
- [x] torch/_inductor/triton_heuristics.py
- [x] torch/_inductor/utils.py https://github.com/pytorch/pytorch/pull/106252

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by Illucious** [comment]
do i just have to add these files in list

**Comment by kamathhrishi** [comment]
Hi, I will add the codegen files

**Comment by SaadMahm00d** [comment]
Not able to tag myself in the list, but I'd love to take a crack at sizevars.py

**Comment by Cyril-Anto** [comment]
@eellison It seems like the fix for the fx_passes/post_grad.py file has been addressed specifically for that file, and the entire issue has been marked as resolved. Can I still work on the remaining files?

**Comment by eellison** [comment]
@Cyril-Anto yea definitely, that was just a github thing. thanks for your help!

**Comment by leslie-fang-intel** [comment]
I will enable `mkldnn_fusion.py`

**Comment by int3** [comment]
This is all done!
