### ISSUE TITLE
[Inductor.utils] - using torch.compile w/ FSDP, generates wall of repetitive warnings "using Triton random, expect differences from eager"

### ISSUE THREAD

**Issue by lessw2020** [pytorch/pytorch#105204]
### 🐛 Describe the bug

Summary - running with FSDP and torch.compile will generate screenfuls of the same single warning:
"[WARNING]" using Triton random, expect difference from eager"

This is propogated over and over, and then duplicated * every rank.
The effect for the user is this:
<img width="1058" alt="not_helpful" src="https://github.com/pytorch/pytorch/assets/46302957/35fcf58f-8de4-4099-af96-27b99b46a5aa">

This really wants to be a one and done warning.  Make the point, and move on. 

Steps to reproduce:
1 - git clone transformer framework repo:
https://github.com/lessw2020/transformer_framework.git

2 - dependencies = pip install transformers datasets vit-pytorch

3 - you can run T5 (defaults to small) by "bash run_training.sh" (note this is a torchrun script, check gpu count but defaults to 4).

4 - That should run T5 and show the warning wall. 

### Versions

Versions
PyTorch version: 2.1.0.dev20230713+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.16 | packaged by conda-forge | (main, Feb 1 2023, 21:39:03) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1036-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
GPU models and configuration:
GPU 0: NVIDIA A10G
GPU 1: NVIDIA A10G
GPU 2: NVIDIA A10G
GPU 3: NVIDIA A10G

Nvidia driver version: 525.85.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+440fd1bf20
[pip3] torch==2.1.0.dev20230628+cu121
[pip3] torch-model-archiver==0.5.3b20220226
[pip3] torch-workflow-archiver==0.2.8b20230512
[pip3] torchaudio==2.1.0.dev20230628+cu121
[pip3] torchserve==0.6.0b20220513
[pip3] torchtext==0.14.1
[pip3] torchvision==0.16.0.dev20230628+cu121
[pip3] vit-pytorch==1.2.2
[conda] blas 1.0 mkl conda-forge
[conda] captum 0.5.0 0 pytorch
[conda] cudatoolkit 11.7.0 hd8887f6_11 conda-forge
[conda] ffmpeg 4.3 hf484d3e_0 pytorch
[conda] libblas 3.9.0 16_linux64_mkl conda-forge
[conda] libcblas 3.9.0 16_linux64_mkl conda-forge
[conda] liblapack 3.9.0 16_linux64_mkl conda-forge
[conda] magma-cuda117 2.6.1 1 pytorch
[conda] mkl 2022.2.1 h84fe81f_16997 conda-forge
[conda] numpy 1.24.3 py39h6183b62_0 conda-forge
[conda] pytorch-cuda 11.7 h778d358_5 pytorch
[conda] pytorch-mutex 1.0 cuda pytorch
[conda] pytorch-triton 2.1.0+440fd1bf20 pypi_0 pypi
[conda] torch 2.1.0.dev20230628+cu121 pypi_0 pypi
[conda] torch-model-archiver 0.5.3 py39_0 pytorch
[conda] torch-workflow-archiver 0.2.8 py39_0 pytorch
[conda] torchaudio 2.1.0.dev20230628+cu121 pypi_0 pypi
[conda] torchserve 0.6.0 py39_0 pytorch
[conda] torchtext 0.14.1 py39 pytorch
[conda] torchvision 0.16.0.dev20230628+cu121 pypi_0 pypi
[conda] vit-pytorch 1.2.2 pypi_0 pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by williamwen42** [comment]
Right now, we're logging the message for every graph (https://github.com/pytorch/pytorch/blob/fb376f80a2f2ceb68322d27433ce22a87c9793e5/torch/_inductor/lowering.py#L1457). You could also try disabling the `developer_warnings` inductor config (see https://github.com/pytorch/pytorch/blob/fb376f80a2f2ceb68322d27433ce22a87c9793e5/torch/_inductor/utils.py#L727). Do you have an expectation for when the warning should be logged?

cc @jansel

**Comment by lessw2020** [comment]
Ok that makes sense re: every graph.  
For FSDP, you are going to graph break at every collective... which means a lot of warnings b/c we have a lot of collectives, and hence the entire wall of warnings in the console.

re: expectation - personally I would be fine not seeing it at all, I don't think the info conveyed is very surprising/valuable. 
 Perhaps go from showing by default to only showing when some form of debug flag is flipped, otherwise just have a global 'one and done' warning. 
 
Note that per graph ultimately makes minimal sense though, esp for distributed now integrating with torch.compile where atm every collective generates a graph break. 

Thanks for the info above.  I'll play with the utils/dev_warning and add that to the best practices for now for people using FSDP + compile to work around it.

**Comment by wconstab** [comment]
could we just make the warning `once globally` instead of `once per graph`?  I am also fine just disabling the warning if others agree.  This should be alleviated by the fsdp tracing effort too, but that's not going to land soon enough to avoid doing a quick fix for this now.

**Comment by jansel** [comment]
Let's just lower this to logging.INFO.
