### ISSUE TITLE
Libtorch CPU c++ cmake: fatal error LNK1181: cannot open input file 'mkl_intel_ilp64.lib'

### ISSUE THREAD

**Issue by CURTLab** [pytorch/pytorch#105215]
### 🐛 Describe the bug

I wanted to try libtorch (CPU) for C++ and downloaded the latest version from the website (libtorch-win-shared-with-deps-debug-2.0.1+cpu.zip).

I used MSVC 2019 x64 as compiler and a custom build of QtCreator (12.0.0-beta1) as IDE.

However, I could not even compile the simple example as I always get the following linkage error:
```
[1/1 17.0/sec] Linking CXX executable TestTorch2.exe
FAILED: TestTorch2.exe 
cmd.exe /C "cd . && C:\Qt\Tools\CMake_64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\TestTorch2.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~4\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo CMakeFiles\TestTorch2.dir\main.cpp.obj  /out:TestTorch2.exe /implib:TestTorch2.lib /pdb:TestTorch2.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console -LIBPATH:C:\Qt\Sci++\Intel\oneAPI\mkl\2023.1.0\lib C:\Qt\Sci++\libtorch\lib\c10.lib  C:\Qt\Sci++\libtorch\lib\kineto.lib  C:\Qt\Sci++\libtorch\lib\torch.lib  C:\Qt\Sci++\libtorch\lib\torch_cpu.lib  C:\Qt\Sci++\libtorch\lib\c10.lib  mkl_intel_ilp64.lib  mkl_intel_thread.lib  mkl_core.lib  C:\Qt\Sci++\Intel\oneAPI\compiler\latest\windows\compiler\lib\intel64_win\libiomp5md.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "C:\PROGRA~2\MICROS~4\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo CMakeFiles\TestTorch2.dir\main.cpp.obj /out:TestTorch2.exe /implib:TestTorch2.lib /pdb:TestTorch2.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console -LIBPATH:C:\Qt\Sci++\Intel\oneAPI\mkl\2023.1.0\lib C:\Qt\Sci++\libtorch\lib\c10.lib C:\Qt\Sci++\libtorch\lib\kineto.lib C:\Qt\Sci++\libtorch\lib\torch.lib C:\Qt\Sci++\libtorch\lib\torch_cpu.lib C:\Qt\Sci++\libtorch\lib\c10.lib mkl_intel_ilp64.lib mkl_intel_thread.lib mkl_core.lib C:\Qt\Sci++\Intel\oneAPI\compiler\latest\windows\compiler\lib\intel64_win\libiomp5md.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:TestTorch2.exe.manifest" failed (exit code 1181) with the following output:
LINK : fatal error LNK1181: cannot open input file 'mkl_intel_ilp64.lib'
```

Here is my cmake configuration. I also tried to add the mkl libraries manually without success.
```cmake
cmake_minimum_required(VERSION 3.23)

project(TestTorch2 LANGUAGES CXX)

list(APPEND CMAKE_PREFIX_PATH "C:/Qt/Sci++/libtorch")
#list(APPEND CMAKE_LIBRARY_PATH "C:/Qt/Sci++/Intel/oneAPI/mkl/2023.1.0/lib/intel64")
#list(APPEND CMAKE_PREFIX_PATH "C:/Qt/Sci++/Intel/oneAPI/mkl/2023.1.0/lib/intel64")

#find_package(Torch PATHS "C:/Program Files/Python38/Lib/site-packages/torch/")
#find_package(Torch PATHS "C:/Qt/Sci++/libtorch/")
find_package(Torch REQUIRED)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")

add_executable(TestTorch2 main.cpp)

target_link_libraries(TestTorch2 PRIVATE
	${TORCH_LIBRARIES}
	#"C:/Qt/Sci++/Intel/oneAPI/mkl/2023.1.0/lib/intel64/mkl_intel_ilp64.lib"
)
```

### Versions

PyTorch version: 2.0.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Education
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: N/A

Python version: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: False
CUDA runtime version: 11.2.67
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce MX130
Nvidia driver version: 536.40
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=1910
DeviceID=CPU0
Family=198
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2112
Name=Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[conda] Could not collect

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @jbschlosser

**Comment by CURTLab** [comment]
Ok, I found the error.

I had to change the file `libtorch/share/Caffe2/public/mkl.cmake` in line 17:
```cmake
# TODO: This is a hack, it will not pick up architecture dependent
# MKL libraries correctly; see https://github.com/pytorch/pytorch/issues/73008
set_property(
  TARGET caffe2::mkl PROPERTY INTERFACE_LINK_DIRECTORIES
  ${MKL_ROOT}/lib)
```

to

```cmake
# TODO: This is a hack, it will not pick up architecture dependent
# MKL libraries correctly; see https://github.com/pytorch/pytorch/issues/73008
set_property(
  TARGET caffe2::mkl PROPERTY INTERFACE_LINK_DIRECTORIES
  ${MKL_ROOT}/lib/intel64)
```

I also noticed that ${MKL_INCLUDE_DIR} is empty in my configuration, but that doesn't affect the build.

**Comment by ezyang** [comment]
Hmm, do you think you can update the cmake to link both directories, perhaps?

**Comment by CURTLab** [comment]
I can have a look. I think the best way would be to use the path from `FindMKL.cmake`. However, the version in `pytorch/cmake/Modules/FindMKL.cmake` doesn't export the path. It only sets `${CMAKE_LIBRARY_PATH}`.

**Comment by CURTLab** [comment]
I have also successfully tested the version that links both directories:

```cmake
set_property(
  TARGET caffe2::mkl PROPERTY INTERFACE_LINK_DIRECTORIES
  ${MKL_ROOT}/lib ${MKL_ROOT}/lib/intel64)
```

But if you add `intel64`, you should also include the case for `intel64_win`, `32`, `32_win`.

**Comment by ezyang** [comment]
It seems relatively harmless to add them all
