### ISSUE TITLE
[Pytorch cuda] A possible bug of 'torch.cuda.is_available()' 

### ISSUE THREAD

**Issue by outthme** [pytorch/pytorch#10529]
## Issue description

When I calling **'torch.cuda.is_available()'** from both Ubuntu Terminal AND Pycharm, the function call  **'is_available()'** returns True in the terminal AND false in Pycharm.  Then I suppose they mistakenly call different **'torch._C._cuda_getDeviceCount()'**,  however their function calls direct to the same **'_C.cpython-35m-x86_64-linux-gnu.so'**. I don't understand why these confused results return?
## Code example
There are two debug screenshots that show my issue:
* Ubuntu Terminal && PDB:
![2018-08-15 11 04 06](https://user-images.githubusercontent.com/5744449/44130153-a68c89bc-a07e-11e8-9575-5f1e758869af.png)
* Pycharm Debug infos:
![2018-08-15 11 00 03](https://user-images.githubusercontent.com/5744449/44130201-ead70426-a07e-11e8-9276-972195933997.png)

## System Info
PyTorch version: 0.5.0a0+fa5d95a
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 384.111
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     0.5.0a0+fa5d95a           <pip>

**Comment by ezyang** [comment]
Does this happen with the 0.4.1 official binaries?

**Comment by outthme** [comment]
Actually, these issues occurred under my Pytorch build from source version which cloned from the current Pytorch gitHub master branch.

**Comment by outthme** [comment]
Did I missing something extra building parameters when I build the Pytorch source code?

**Comment by outthme** [comment]
After a few tries, I found that when I start my Pycharm from terminal commands, torch.cuda.is_available() is works. Maybe I missed some environment variables in my Pycharm default configurations.

**Comment by aowais2** [comment]
I am currently facing the same issue using Anaconda Spyder
