### ISSUE TITLE
DISABLED test_fused_optimizers_with_large_tensors (optim.test_optim.TestOptim)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#105254]
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_optim.py%3A%3ATestOptim%3A%3Atest_fused_optimizers_with_large_tensors)).

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jithunnair-amd** [comment]
@huydnn @clee2000 We're e a bit confused why this issue is not taking effect.

**Comment by janeyx99** [comment]
Unsure if my title change will work better, but if it doesn't, we should just add a skip in the code itself.

**Comment by jithunnair-amd** [comment]
ah of course! Actually, yes, that should work .... we just faced this in another case
