### ISSUE TITLE
submodules defined in list are not auto-registered as parameters

### ISSUE THREAD

**Issue by splintersu** [pytorch/pytorch#1053]
`
class Net(th.nn.Module):
	def __init__(self):
		super(Net , self).__init__()
		
		self.conv1d = [\
			th.nn.Conv1d(config.WORD_VEC_SIZE , 1 , 3),\
			th.nn.Conv1d(config.WORD_VEC_SIZE , 1 , 4),\
			th.nn.Conv1d(config.WORD_VEC_SIZE , 1 , 5)\
		]
....

a = Net()
`
after call a.cuda(), the Conv1d submodules are still in CPU mode, which indicates that these submodules defined in list are not auto registered as parameters of the Net Class.

**Comment by apaszke** [comment]
This is expected. Use `nn.ModuleList`.
