### ISSUE TITLE
Autograd bug with inplace op

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#10532]
See code below. 

```py
import torch
import torch.nn as nn

net = nn.Sequential(
  nn.InstanceNorm2d(1),
  nn.ReLU(True)
)

x = torch.randn(1, 1, 1, 1, requires_grad=True)

g, = torch.autograd.grad(net(x).pow(2), [x], create_graph=True)
torch.autograd.grad(g.sum(), [x])
```

gdb tells me that the error is from saved variable of ThresholdBackward1. I'll look into it more.

**Comment by SsnL** [comment]
note: this may seem weird but both the InstanceNorm and the MaxPool is necessary to reproduce this! At least for this experiment. I haven't gotten time to find the exact reason yet.

**Comment by SsnL** [comment]
Update: doesn't trigger with `relu_` instead of `threshold_` hmm. keep looking

**Comment by SsnL** [comment]
so here is what ive found: the bug trigger when CopySlice calls its wrapped Function, but unfortunately the function was already called (somehow) before this can freed its buffer. Haven't really figured out why it could happen.

**Comment by SsnL** [comment]
bug still exists

**Comment by albanD** [comment]
@SsnL I think this is the same problem as the one fixed by #15219 
The thing is that this creates a cycle that cannot be collected in the computational graph and I haven't had time to think how to fix it :/

**Comment by HuiZeng** [comment]
met the same problem :(

**Comment by SsnL** [comment]
fwiw, the code used to work around may 2018.
