### ISSUE TITLE
einsum with complex number 

### ISSUE THREAD

**Issue by jy19Phy** [pytorch/pytorch#105321]
### 🐛 Describe the bug

# define two tensors 
import torch
x = torch.tensor([[1.+0.j, 0.+0.j], [0.+0.j, 0.+0.j]])
#	 Compute the trace of the matrix product
	result = torch.einsum('i j, j i', x, x)

# print the result 
	print(result)

### Versions

zsh: command not found: wget

**Comment by khushi-411** [comment]
Hi, this works completely fine. Please make sure you have the correct installation.
```python
>>> import torch
>>> x = torch.tensor([[1.+0.j, 0.+0.j], [0.+0.j, 0.+0.j]])
>>> x
tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]])
>>> result = torch.einsum('i j, j i', x, x)
>>> result
tensor(1.+0.j)
>>> torch.__version__
'2.1.0a0+git76ad21d'
```
Also, so that you know, PyTorch developers usually prefer such discussions in [discussion forum](https://discuss.pytorch.org/). That's very active; you should use it :)

**Comment by mikaylagawarecki** [comment]
Closing as complete since this works on master. Feel free to reopen otherwise!
