### ISSUE TITLE
the problem for RNN training with DataParallel

### ISSUE THREAD

**Issue by wqn628** [pytorch/pytorch#10537]
hello, today I train the nn.LSTM with multi-gpu by nn.DataParallel. I set the batch_size=12 in data.DataLoader, so the shape of input is (12, T, *), T represents the max frame in the 12 sentences(these 12 sentences has been padded into equal length), and * represents the dimension of the feature for each frame. the number of gpu is 3. But the error as follows: I confused by this error for a long time. Any help would be appreciated。。。

```
File "/search/speech/wangqingnan/Anaconda/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/search/speech/wangqingnan/Anaconda/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/search/speech/wangqingnan/Anaconda/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
ValueError: Expected `len(lengths)` to be equal to batch_size, but got 12 (batch_size=4).
```

**Comment by SsnL** [comment]
Can you show us a small script that reproduce the issue?

**Comment by soumith** [comment]
when you are using nn.LSTM with nn.DataParallel, you either have to use `batch_first=True` for nn.LSTM.
Either ways, please use https://discuss.pytorch.org for questions.

**Comment by wqn628** [comment]
yes, i use batch_first=True for nn.LSTM, but the error occurs still.

**Comment by wqn628** [comment]
`class LSTM(nn.Module):
def init(self, input_size, hidden_layer, hidden_size, num_classes,
rnn_type=‘lstm’, dropout=0.0, bidirect=True, residual=False):
super(LSTM, self).init()
if bidirect:
layer = [nn.LSTM( input_size=input_size, hidden_size=hidden_size, batch_first=True, bidirectional=bidirect, dropout=dropout)]
for i in range(hidden_layer):
layer.append(nn.LSTM(hidden_size2, hidden_size, batch_first=True, dropout=0.0, bidirectional=bidirect))
self.lstm = nn.Sequential(layer)
self.lstm.add_module(“conn”,nn.LSTM(hidden_size2, num_classes, batch_first=True, dropout=0.0, bidirectional=bidirect))
def forward(self, x, input_len):
max_length = x.shape[1]
x = rnn_pack.pack_padded_sequence(x, input_len, batch_first=True)
x = self.lstm(x)
out , _ = rnn_pack.pad_packed_sequence(x, total_length=max_length, batch_first=True)
return out`
=========================================================
    if th.cuda.is_available():
        if args.multi_gpu == 1:
            if th.cuda.device_count() > 1:
                logger.info("Let's use {} GPUs!".format(th.cuda.device_count()))
                nnet = nn.DataParallel(nnet, device_ids=[0,1,2]) # dim = 0 [30, xxx] -> [10, ...], [10, ...], [10, ...] on 3 GPUs
            elif th.cuda.device_count() == 1:
                logger.info("!!!WARNINGS:Only 1 GPU detected and Let's use the only one GPUs!!!")
            else:
                logger.info("!!!!!ERROR!!!!!")
        else:
            logger.info("!!!Training on single GPU!!!")
          
    else:
        logger.info("!!!WARNINGS:NO GPUs detected! AND The Net Will Be Trained On CPU!!!")
    logger.info(nnet)
    criterion = nn.CrossEntropyLoss()
=========================================================
def train_one_epoch(nnet, criterion, optimizer, train_loader, num_parallel, is_rnn=False):
nnet.train()
pos_frames = 0.0
train_frames = 0.0
for index, (key, feats, labels, len_list) in enumerate(train_loader):
print “=============”
print key
print feats.shape ##(12,T,)
print labels.shape ##(12,T)
#print type(len_list)
#print len_list.shape
print “=============”
labels = labels.view(labels.shape[0], labels.shape[1])
input_len = np.array(len_list)
input_sort_id = np.argsort(-input_len)
input_len = input_len[input_sort_id]
feat_mat = feats[th.LongTensor(input_sort_id)]
feat_mat = Variable(feat_mat.cuda())
input_unsort_id = th.LongTensor(np.argsort(input_sort_id))
optimizer.zero_grad()
if is_rnn:
label_mat = labels.view(labels.size(0) * labels.size(1))
targets = Variable(label_mat.cuda())
out = nnet(feat_mat, input_len)
out = out[input_unsort_id]
out_num = out.shape[2]
max_frame = int(max(len_list))
 .......
=====================================
the error ：
![image](https://user-images.githubusercontent.com/17527574/44184717-e368a680-a142-11e8-8618-e0d4457b3384.png)

**Comment by memray** [comment]
Encountered the same problem when using multiple GPUs, used batch_first=True as well. Looks like the `lengths` list is not properly segmented. Any solution to it?

**Comment by kashpop** [comment]
Encountered the same error. Any updates on the solution?

**Comment by memray** [comment]
@kashpop 
Use nn.utils.rnn.pad_packed_sequence() and set the total_length argument solved my problem. It forces the returned sequence to be equal length.

**Comment by Sisi0518** [comment]
Encountered the same error. @memray  And I use the  nn.utils.rnn.pad_packed_sequence() and set the total_lengths to the max_sentence_len in a batch. Code is as follow. But it doesn't work. 
Is the total_length argument related to batch size?


def forward(self, x, lengths):
        """Handles variable size captions
        """
        # Embed word ids to vectors
        total_length = x.size(1)
        x = self.embed(x)
        packed = pack_padded_sequence(x, lengths, batch_first=True)

        # Forward propagate RNN
        out, _ = self.rnn(packed)

        # Reshape *final* output to (batch_size, hidden_size)
        padded = pad_packed_sequence(out, batch_first=True, total_length=total_length)
        cap_emb, cap_len = padded

        if self.use_bi_gru:
            cap_emb = (cap_emb[:,:,:cap_emb.size(2)/2] + cap_emb[:,:,cap_emb.size(2)/2:])/2

        # normalization in the joint embedding space
        if not self.no_txtnorm:
            cap_emb = l2norm(cap_emb, dim=-1)

        return cap_emb, cap_len

**Comment by TianweiXing** [comment]
@Sisi0518 Did you solved the problem?
I encountered the exact same problem. But after setting "total_length" to the max length of the sequence in my dataset, the problem still exists....

**Comment by yuyangstatistics** [comment]
@wqn628 
> input_len = input_len[input_sort_id]
> feat_mat = feats[th.LongTensor(input_sort_id)]
> feat_mat = Variable(feat_mat.cuda())
 
In your code, the input features are processed on 3 GPUs, so actually each GPU deals with the **feat_mat** in a batch of size 4. But since you didn't send **input_len** to multiple GPUs, so each GPU deals with **input_len** in a batch of size 12, and this is what the error message means.

You can modify the code as follows. Based on the documentation of `pack_padded_sequence()`, the `lengths` argument can be a tensor, so it would be fine. I had the similar issues as you and I fixed it in this way. Hope this helps.
```python
input_len = Variable(torch.from_numpy(input_len[input_sort_id])).int().cuda()
feat_mat = feats[th.LongTensor(input_sort_id)]
feat_mat = Variable(feat_mat.cuda())
```
