### ISSUE TITLE
torch.nan_to_num not implemented for ComplexFloat

### ISSUE THREAD

**Issue by yifengd** [pytorch/pytorch#105462]
### 🐛 Describe the bug

torch.nan_to_num is not implemented for complex tensors and raises and Error. I assume this is a bug, since torch.isnan() works.

Minimal Example:
```python
import torch

print(torch.nan_to_num(torch.tensor(1j))
```

Expected output:
```
tensor(1j)
```

Actual output:
```
Traceback (most recent call last):
  File "/home/ec2-user/.pycharm_helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
RuntimeError: "nan_to_num" not implemented for 'ComplexFloat'
```

### Versions

PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.26

Python version: 3.8.16 (default, Mar 10 2023, 03:07:48)  [GCC 7.3.1 20180712 (Red Hat 7.3.1-15)] (64-bit runtime)
Python platform: Linux-5.10.179-171.711.amzn2.x86_64-x86_64-with-glibc2.2.5
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.85.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:            7
CPU MHz:             2925.448
BogoMIPS:            4999.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-lightning==2.0.3
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] No relevant packages

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by cpuhrsch** [comment]
Marking this as high priority to discuss whether we'd accept a PR that implements this / whether it's possible to do this

**Comment by ezyang** [comment]
This seems reasonable to me.

**Comment by lezcano** [comment]
In `linalg` we use the current workaround
https://github.com/pytorch/pytorch/blob/18bcf62bbcf7ffd47e3bcf2596f72aa07a07d65f/aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.cpp#L1738-L1746
This workaround works for our use case, but in general, this should be implemented as `x.masked_fill(torch.isnan(x), newval)` albeit in a kernel.

**Comment by janeyx99** [comment]
After group discussion, we have a consensus to implement this since isnan is already defined for complex. Marking as actionable.

**Comment by kurtamohler** [comment]
I can work on this
