### ISSUE TITLE
not bug -- Suggestion of edit to RuntimeError from torch.solve() / torch.linalg.solve()

### ISSUE THREAD

**Issue by rubenalv** [pytorch/pytorch#105452]
### 🐛 Describe the bug

This is not a bug, just a suggestion to edit an error message to make it more comprehensive.

In:
https://github.com/pytorch/pytorch/blob/964d29f312c97fd367d1818dcf097f3b283959a2/torch/_linalg_utils.py#L105
I suggest to replace the
`RuntimeError: This function was deprecated since version 1.9 and is now removed. Please use the torch.linalg.solve function instead.`
by something more informative as
`RuntimeError: This function was deprecated since version 1.9 and is now removed. Please replace torch.solve(B,A).solution by torch.linalg.solve(A,B), and beware of the reversion of attributes.`

For more info, I started an issue by mistake here https://github.com/pyg-team/pytorch_geometric/issues/7670, with more details. In summary, the reversion of attributes can lead to wrong output, if the tensors dimensions are compatible with the function call (if the dimensions are not compatible another error is thrown and the user will more likely realise the problem).

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

cc @svekars @carljparker @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by lezcano** [comment]
We would accept a fix for that. The deprecation message we had in the previous function before the removal was more informative and included an update guide.

The PR would dig up the error message that the previous linalg functions (`solve`, `lstsq`, etc) used to throw and use it to improve the message that we currently throw.

**Comment by franklinscudder** [comment]
I'd like to work on this!

**Comment by lezcano** [comment]
Go for it, just send a PR
