### ISSUE TITLE
[benchmark] Rename the count field FunctionCount

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#105471]
The `count` field is in `FunctionCount` defined in `torch/utils/benchmark/utils/valgrind_wrapper/timer_interface.py` is redefining the built in field of tuple. Consider renaming.

>              Hmm, do you mind renaming it to something else? How about `counter`? or `invocation_count` (though strictly speaking out of scope of this PR)

_Originally posted by @malfet in https://github.com/pytorch/pytorch/pull/105424#discussion_r1266832538_
            

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by awmle** [comment]
Hi @justinchuby, it seems to me the `count` field of `FunctionCount` is used in `timer_interfact.py` and `test_benchmark_utils.py` only. I can make this change.
