### ISSUE TITLE
UNSTABLE inductor / linux-focal-cpu-py3.8-gcc7-inductor / test (inductor_huggingface_cpu_accuracy)

### ISSUE THREAD

**Issue by PaliC** [pytorch/pytorch#105481]
> Please provide a brief reason on why you need to mark this job as unstable.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ezyang** [comment]
ditto, tell us more

**Comment by huydhn** [comment]
This doesn't look flaky in trunk anymore, not quite sure why it was marked as unstable
