### ISSUE TITLE
support FlashAttention-2

### ISSUE THREAD

**Issue by nick008a** [pytorch/pytorch#105474]
### 🚀 The feature, motivation and pitch

https://github.com/Dao-AILab/flash-attention

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg

**Comment by drisspg** [comment]
Yup I am working on this.

**Comment by bhack** [comment]
https://github.com/openai/triton/pull/1970

**Comment by bhack** [comment]
For who is interested, just in the case it will land earlier, Meta is working at this also at:
https://github.com/facebookresearch/xformers/issues/795

**Comment by bhack** [comment]
It was not (auto)connect to the ticket but @drisspg draft PR is at https://github.com/pytorch/pytorch/pull/105602

**Comment by bhack** [comment]
Triton merged..

**Comment by bhack** [comment]
@drisspg What is missing to close this?

**Comment by drisspg** [comment]
This has landed as of this PR: https://github.com/pytorch/pytorch/pull/105602. It looks like the PR never got linked
