### ISSUE TITLE
Implement NEON version of ERF()

### ISSUE THREAD

**Issue by Rohanjames1997** [pytorch/pytorch#105493]
### 🚀 The feature, motivation and pitch

Currently, the fp32 `erf()` function on Intel machines goes through either the [AVX-512 path](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/cpu/vec/vec512/vec512_float.h#L187-L218) or the [AVX-2 path ](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/cpu/vec/vec256/vec256_float.h#L158-L189). These implementations are much faster than the corresponding std math & SLEEF implementations (as described in #91613). But the same function on ARM takes the [std::erf()](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/cpu/vec/vec256/vec256_float_neon.h#L391-L396) path, or the SLEEF path, but that is hard to invoke (#105335). 

Since the `erf()` function is a hotspot for transformer models (GELU activation), I propose adding a NEON intrinsics implementation for `erf()` as well. I see around 50-60% speed improvements after doing so. Posting this here for discussion/comments before raising a PR.

cc @malfet @seemethere

**Comment by malfet** [comment]
@Rohanjames1997 if you have neon-accelerated ERF implementation, please do not hesitate to propose a PR and ask me to review it

**Comment by Rohanjames1997** [comment]
Thanks @malfet, I have raised the PR #105610
