### ISSUE TITLE
[ONNX] FX produce valid node names in models

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#105515]
Currently we see names like `LayerNorm(L__self___embed_layer_norm)_14` for functions and `weight.output.1` for tensors. We need to make them valid C variable names to follow the ONNX standard: https://onnx.ai/onnx/repo-docs/IR.html#names-within-a-graph

> All names MUST adhere to [C90 identifier syntax rules](https://en.cppreference.com/w/c/language/identifier).
> Names of nodes, inputs, outputs, initializers, and attributes are organized into several namespaces. Within a namespace, each name MUST be unique for each given graph.

cc @BowenBao

**Comment by BowenBao** [comment]
For tensors (initializers) we can simply revert back to replacing '.' with '_'. In fact it was a recent change to keep the '.' to match with names from torch `state_dict`, `named_parameters` and `named_buffers`.  

For functions it is a combination of qualified nn module class name and module variable name. I think we can keep just qualified nn module class name and apply the same '.' -> '_' replacement.

Should we add this rule into onnx checker?

**Comment by justinchuby** [comment]
We can put more info in the description I think. Context for adding the rule to the checker: https://github.com/onnx/onnx/issues/5348

**Comment by justinchuby** [comment]
@BowenBao I think this is done?

**Comment by BowenBao** [comment]
No it is not, we are not enforcing the rule, and there are violations.
