### ISSUE TITLE
Least squares method calculation result is incorrect.  torch.linalg.lstsq

### ISSUE THREAD

**Issue by wxhuu** [pytorch/pytorch#105511]
## Issue description

 I have a problem with my least squares calculation using torch.linalg.lstsq. The dimensions of Pcorr and Pprior_b are (248000, 34) and (248000, 1) respectively. The resulting solution is not accurate. Here is my code. Can you help me identify the problem?

## Code example
def calculateBHC_torch(Praw, Pseg, Pseg2, Pprior):
    batch_size = Praw.shape[0]  # batchSize
    channels = Praw.shape[1]  # channels
    proj_num = Praw.shape[2]  # h 400
    proj_w = Praw.shape[3]  # w 620
    outPut = torch.zeros((batch_size, channels, proj_num, proj_w), dtype=torch.float32).cuda()
    
    for b in range(batch_size):
        for ch in range(channels):
            Pcorr = torch.zeros((proj_num, proj_w, 34), dtype=torch.float32).cuda()
            pos = 1
            for i in range(5):
                for j in range(5):
                    for k in range(5):
                        if 1 <= (i + j + k) <= 4:
                            # Compute the value for this combination of i, j, k
                            Pcorr[:, :, pos - 1] = torch.pow(Praw[b, ch], i / 2) * torch.pow(Pseg[b, ch], j / 2) * \
                                                   torch.pow(Pseg2[b, ch], k / 2)
                            pos += 1

            Pcorr = Pcorr.reshape(proj_w * proj_num, pos - 1) # 248000,34
            Pprior_b = Pprior[b, ch].reshape(proj_w * proj_num, 1) # 248000 1

            # Solve a linear matrix equation
           
            C = torch.linalg.lstsq(Pcorr,Pprior_b)[0]
            Pcorr = torch.matmul(Pcorr, C)
            Pcorr = Pcorr.reshape(proj_num, proj_w)
            outPut[b, ch] = Pcorr
    return outPut

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by lezcano** [comment]
Could you please post this in the forums https://discuss.pytorch.org/?

Now, at first sight, I think that the issue may be that your matrix may be rank-deficient (or close to rank deficient) and `linalg.lstsq` on CUDA does not handle this case, [as per the docs](https://pytorch.org/docs/stable/generated/torch.linalg.lstsq.html#torch.linalg.lstsq).

Closing this one, but feel free to tag me if you open an issue in the forums and we can discuss further there.
