### ISSUE TITLE
[ONNX] Exporting the operator 'aten::exponential' to opset version 13 is not supported

### ISSUE THREAD

**Issue by yu2888** [pytorch/pytorch#105520]
### 🐛 Describe the bug

'aten::exponential' seems not supported by onnx. One way I know is to create a custom function and register it, but it doesn't work.

### Versions

--2023-07-19 14:32:17--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21653 (21K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py                      100%[===================================================================>]  21.15K  --.-KB/s    in 0.001s  

2023-07-19 14:32:18 (22.8 MB/s) - ‘collect_env.py’ saved [21653/21653]

**Comment by davidradl** [comment]
hi, could you supply a piece of code that recreates this please. also you should put the contents of the collect_env.py here, so we can see your environment.

**Comment by yu2888** [comment]
import torch
from torch.onnx import register_custom_op_symbolic

def custom_exp(x):
    """Custom implementation of the exponential function."""
    sign = torch.sign(x)
    abs_x = torch.abs(x)
    exp_int = torch.floor(abs_x)
    exp_frac = abs_x - exp_int
    exp_approx = torch.pow(2.0, exp_int)
    exp_residual = torch.exp(exp_frac * torch.log(torch.tensor(2.0)))
    return sign * exp_approx * exp_residual

def custom_exp_symbolic(symbolic_graph, inputs, attrs, opset_version):
    """Symbolic function for custom_exp."""
    return symbolic_graph.op("CustomExp", inputs)

# Register custom op with PyTorch
register_custom_op_symbolic("aten::exponential", custom_exp_symbolic, 13)

""" some functinon """

    img = torch.randn(1, 11 ,3, 256, 512).cuda()
    imu = torch.randn(1, 101, 6).cuda()


    # Export the model
    torch.onnx.export( 
    model,               # model being run
    (img, imu), # model input (or a tuple for multiple inputs)
    "tester.onnx",   # where to save the model (can be a file or file-like object)
    export_params=True,        # store the trained parameter weights inside the model file
    opset_version=13,          # the ONNX version to export the model to
    do_constant_folding=True,  # whether to execute constant folding for optimization
    input_names = ['img', 'imu'],   # the model's input names
    output_names = ['output'] # the model's output names
    )

**Comment by yu2888** [comment]
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 21.10 (x86_64)
GCC version: (Ubuntu 11.2.0-7ubuntu2) 11.2.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.34

Python version: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-35-generic-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 510.73.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           80
Model name:                      AMD Ryzen 7 5700G with Radeon Graphics
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1400.000
CPU max MHz:                     4672.0698
CPU min MHz:                     1400.0000
BogoMIPS:                        7585.41
Virtualization:                  AMD-V
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        4 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; LFENCE, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] numpy-quaternion==2022.4.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] nomkl                     1.0                  h5ca1d4c_0    conda-forge
[conda] numpy                     1.24.3          py310ha4c1d20_0    conda-forge
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchaudio                2.0.2                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by yu2888** [comment]
import torch
from torch.onnx import register_custom_op_symbolic

def custom_exp(x):
    """Custom implementation of the exponential function."""
    sign = torch.sign(x)
    abs_x = torch.abs(x)
    exp_int = torch.floor(abs_x)
    exp_frac = abs_x - exp_int
    exp_approx = torch.pow(2.0, exp_int)
    exp_residual = torch.exp(exp_frac * torch.log(torch.tensor(2.0)))
    return sign * exp_approx * exp_residual

def custom_exp_symbolic(symbolic_graph, inputs, attrs, opset_version):
    """Symbolic function for custom_exp."""
    return symbolic_graph.op("CustomExp", inputs)

# Register custom op with PyTorch
register_custom_op_symbolic("aten::exponential", custom_exp_symbolic, 13)

"""main function"""

    img = torch.randn(1, 11 ,3, 256, 512).cuda()
    imu = torch.randn(1, 101, 6).cuda()


    # Export the model
    torch.onnx.export( 
    model,               # model being run
    (img, imu), # model input (or a tuple for multiple inputs)
    "tester.onnx",   # where to save the model (can be a file or file-like object)
    export_params=True,        # store the trained parameter weights inside the model file
    opset_version=13,          # the ONNX version to export the model to
    do_constant_folding=True,  # whether to execute constant folding for optimization
    input_names = ['img', 'imu'],   # the model's input names
    output_names = ['output'] # the model's output names
    )

**Comment by shubhambhokare1** [comment]
Hi @yu2888 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team
