### ISSUE TITLE
[Fatal Bug] changed nn.Module.training does not trigger recompilation.

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#105653]
### 🐛 Describe the bug

Here is the sample code:

```python
import torch
from torch import nn

from torch import _dynamo
from torch._functorch.aot_autograd import aot_module_simplified
import functorch
from functorch.compile import make_boxed_func

def graph_processing_pytorch(gm, example_inputs):
    # graph transform (graph optimization) for the captured graph in pytorch
    print("captured graph in pytorch")
    gm.print_readable()

def graph_processing_aot_forward(gm, example_inputs):
    # graph transform (graph optimization) for the captured graph in aot autograd forward graph
    print("captured graph in aot autograd forward")
    gm.print_readable()

def graph_processing_aot_backward(gm, example_inputs):
    # graph transform (graph optimization) for the captured graph in aot autograd backward graph
    print("captured graph in aot autograd backward")
    gm.print_readable()

def forward_compiler(gm, example_inputs):
    graph_processing_aot_forward(gm, example_inputs)
    return make_boxed_func(gm.forward)

def backward_compiler(gm, example_inputs):
    graph_processing_aot_backward(gm, example_inputs)
    return make_boxed_func(gm.forward)

def custom_backend(gm, example_inputs):
    graph_processing_pytorch(gm, example_inputs)
    return aot_module_simplified(
        gm, example_inputs,
        fw_compiler=forward_compiler,
        bw_compiler=backward_compiler
    )

class BackboneModel(nn.Module):

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.drop1 = nn.Dropout(0.5)
        self.bn1 = nn.BatchNorm2d(6)

    def forward(self, x):
        x = self.bn1(self.drop1(x))
        return x


model = BackboneModel()

opt_model = torch.compile(model, backend=custom_backend)

input = torch.randn(64, 6, 32, 32)

output1 = opt_model(input)

# calling .eval in the whole model works
# opt_model.eval()

# calling .eval in sub model does not trigger re-compilation
opt_model.drop1.eval()
opt_model.bn1.eval()

output2 = opt_model(input)
output3 = opt_model(input)

print((output2 - output3).abs().max().item()) # huge number, nondeterministic!
```

It seems only the `.eval` call in the whole model works. The `training` flag in sub-models are not respected. As a result, after I call `eval` for all the sub-models, the output is still nondeterministic.

### Versions

pytorch 2.0.1

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ezyang** [comment]
This is probably the same thing as https://github.com/pytorch/pytorch/issues/100061

**Comment by youkaichao** [comment]
Yeah, I think the problem is the guard condition does not guard on `training` flag in sub-models.

**Comment by youkaichao** [comment]
@ezyang Is it possible to get the guards of each subgraph so that users can check the correctness of captured graph?

**Comment by ezyang** [comment]
TORCH_LOGS=guards

they're very long though, ask questions if you need help interpreting.

**Comment by youkaichao** [comment]
I don't see any guards output with TORCH_LOGS=guards . Maybe it is related with https://github.com/pytorch/pytorch/issues/103248 .

Meanwhile, my suggestions is, can we pass guards to compiler functions along with the captured subgraph? I think a subgraph with corresponding guards and example_inputs together makes a complete captured graph. It tells the compiler under which condition the graph holds, what is the graph, and what is the example input.

The current compiler backend signature: `def custom_backend(gm, example_inputs):`

Suggested: `def custom_backend(gm, example_inputs, guards):`

I suppose the change should be easy, as guards are already there, and pytorch only needs to pass them to compilers, so that we can easily check the correctness of guards for each subgraph.

**Comment by ezyang** [comment]
I don't understand what you'd do with the guards. For one, you can't run the guard without access to the f_locals of the frame the compiled code corresponds to...

**Comment by anijain2305** [comment]
@youkaichao Can you please check if this https://github.com/pytorch/pytorch/pull/108528 fixes the issue?

**Comment by youkaichao** [comment]
@anijain2305 Thanks for the message! I have built the `main`, and tested the case. It works now. Add I also added the case to the tests at https://github.com/pytorch/pytorch/pull/108750 . Please have a look when you have time :)
