### ISSUE TITLE
[build system refactor] delete build_pytorch_libs.{sh,bat}, move functionality into cmake layer

### ISSUE THREAD

**Issue by anderspapitto** [pytorch/pytorch#10562]
currently, to build libtorch and its dependent libs, you invoke build_pytorch_libs.{sh,bat}. For the most part, these just call out to cmake several times. They also do a little bit of fiddling with variables, and copy around some output files to particular locations. All of this can and should just be done with cmake, with the benefits of

- one less middleman script to debug through
- easier for newcomers ("just run cmake")
- removes duplication and code drift between windows and unix build scripts (there are already a number of divergences)

**Comment by ngimel** [comment]
Closing due to age
