### ISSUE TITLE
Syntax error when compileing Megatron-LM models.

### ISSUE THREAD

**Issue by torshie** [pytorch/pytorch#105636]
### 🐛 Describe the bug

Sorry, I haven't reproduced this bug with a simple demo.

Use `@torch.compile`to annotate `CoreAttention.forward` method in this file https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/transformer.py, then train a simple model can reproduce this bug.

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 364, in _compile
    check_fn = CheckFunctionManager(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/guards.py", line 548, in __init__
    self.check_fn = self.compile_check_fn(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/guards.py", line 645, in compile_check_fn
    exec(py_code, global_builder.scope, out)
  File "<string>", line 2
    return lambda name,self,dtype,___stack0,required_len,tensor_shape,___odict_getitem(self,**___kwargs_ignored: ___guarded_code.valid and ___check_type_id(name, 93889009977280) and name == 'mpu' and ___check_type_id(self, 93889097820512) and str(dtype) == 'torch.bfloat16' and ___check_type_id(self.buffer, 93889009989056) and ___check_type_id(required_len, 93889009992480) and required_len == 134217728 and ___check_type_id(tensor_shape, 93889009978272) and len(tensor_shape) == 3 and ___check_type_id(tensor_shape[0], 93889009992480) and ___check_type_id(tensor_shape[1], 93889009992480) and ___check_type_id(tensor_shape[2], 93889009992480) and tensor_shape == (32, 2048, 2048) and tensor_shape[0] == 32 and tensor_shape[1] == 2048 and tensor_shape[2] == 2048 and ___check_tensors(___stack0, ___odict_getitem(self.buffer, ('mpu', torch.bfloat16)))
                                                                                      ^
SyntaxError: invalid syntax
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-4.19.91-012.ali4000.alios7.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A10
GPU 1: NVIDIA A10

Nvidia driver version: 470.103.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
Stepping:                        6
BogoMIPS:                        5799.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       3 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        80 MiB (64 instances)
L3 cache:                        96 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-63
NUMA node1 CPU(s):               64-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.0.0
[pip3] torch-tensorrt==1.4.0.dev0
[pip3] torchdata==0.6.0
[pip3] torchtext==0.15.1
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] Could not collect

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @wconstab

**Comment by torshie** [comment]
I further investigated this bug, it's related to the following function call.
```python
        # preallocting input tensor: [b * np, sq, sk]
        matmul_input_buffer = mpu.get_global_memory_buffer().get_tensor(
            (output_size[0]*output_size[1], output_size[2], output_size[3]),
            query_layer.dtype, "mpu")
```
If `torch.compile` doesn't cover this function call, everything works fine, otherwise the syntax error will show.

I tried to copy this out to a new file (with other required stuff), but `torch.compile` works fine in this case.

**Comment by ezyang** [comment]
cc @voznesenskym

**Comment by mlazos** [comment]
@torshie, does this still occur for you? If so can you provide a full repro (not simple is fine too, sharing your script for instance)

**Comment by mlazos** [comment]
I haven't been able to repro, I'm going to close due to inactivity, feel free to reopen
