### ISSUE TITLE
[Caffe2] Error C2370 when compiling DLL.

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#10568]
## Issue description

Getting error `C2370` when compiling as DLL.
For example:
```
error C2370: 'caffe2::FLAGS_caffe2_use_fatal_for_enforce': redefinition; different storage class
```

## System Info

- PyTorch or Caffe2: C2
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): cmake
- OS: Win10
- PyTorch version: master
- VS version (if compiling from source): 2017
- CMake version: 3.12

**Comment by peterjc123** [comment]
Maybe we should close this?

**Comment by xkszltl** [comment]
Yes.
