### ISSUE TITLE
_meta_copy check fails on scalar value

### ISSUE THREAD

**Issue by dnlby96** [pytorch/pytorch#105685]
### 🐛 Describe the bug

`_meta_copy` added in https://github.com/pytorch/pytorch/pull/100115 fails when src is a scalar value

```
import torch
from torch import _dynamo as dynamo

@dynamo.optimize('eager')
def func():
    t = torch.rand(3,4)
    t.copy_(3)
    print(t)

func()
```

The following error is raised
```
torch._dynamo.exc.TorchRuntimeError: Failed running call_method copy_(*(FakeTensor(..., size=(3, 4)), 3), **{}):
'int' object has no attribute 'to'

from user code:
   File "test.py", line 7, in func
    t.copy_(3)
 ```

However, running the script without dynamo works
```
import torch

def func():
    t = torch.rand(3,4)
    t.copy_(3)
    print(t)

func()
```

Output
```
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
```

### Versions

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.7
[pip3] dalle2-pytorch==1.14.2
[pip3] ema-pytorch==0.2.3
[pip3] flake8==6.0.0
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] open-clip-torch==2.18.0
[pip3] pytorch-transformers==1.2.0
[pip3] pytorch-triton==2.1.0+9e3e10c5ed
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.2.2
[pip3] torch==2.1.0.dev20230720+cu121
[pip3] torch-fidelity==0.3.0
[pip3] torch-struct==0.5
[pip3] torchaudio==2.1.0.dev20230720+cu121
[pip3] torchbenchmark==0.0.7
[pip3] torchdata==0.7.0.dev20230508
[pip3] torchmetrics==0.11.4
[pip3] torchrec-nightly==2023.5.1
[pip3] torchtext==0.16.0.dev20230508+cpu
[pip3] torchvision==0.16.0.dev20230720+cu121
[pip3] triton==2.0.0
[pip3] vector-quantize-pytorch==1.2.2
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] clip-anytorch             2.5.2                    pypi_0    pypi
[conda] coca-pytorch              0.0.7                    pypi_0    pypi
[conda] dalle2-pytorch            1.14.2                   pypi_0    pypi
[conda] ema-pytorch               0.2.3                    pypi_0    pypi
[conda] functorch                 1.14.0a0+b71aa0b          pypi_0    pypi
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] open-clip-torch           2.18.0                   pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] pytorch-triton            2.1.0+9e3e10c5ed          pypi_0    pypi
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.2.2                    pypi_0    pypi
[conda] torch                     2.1.0.dev20230720+cu121          pypi_0    pypi
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230720+cu121          pypi_0    pypi
[conda] torchbenchmark            0.0.7                    pypi_0    pypi
[conda] torchdata                 0.7.0.dev20230508          pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchrec-nightly          2023.5.1                 pypi_0    pypi
[conda] torchtext                 0.16.0.dev20230508+cpu          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230720+cu121          pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
[conda] vector-quantize-pytorch   1.2.2                    pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by shingjan** [comment]
One other thing that looks odd to me is that the above code snippet, specifically `t.copy_(3)`, only dispatches into `aten.copy_.default` instead of `aten.copy_.int`. It seems like for some reason the dispatch key generated from the function call will prioritize `copy_.default` over `copy_.int/float`. I wonder if this is expected @bdhirsh . Thanks!

**Comment by ezyang** [comment]
This is probably not too hard to fix, just test if the src is a non-Tensor. You wanna send a PR?

**Comment by shingjan** [comment]
Thanks! @ezyang PR #111705 is up for fixing this. Let me know if we want a test case for it.
