### ISSUE TITLE
problem: corrupted size vs. prev_size when using python3.6

### ISSUE THREAD

**Issue by NewEricWang** [pytorch/pytorch#10567]
Hi, I install tensorflow-1.9; then install pytorch=0.4 at python2 and python3 respectively.
I use python2 to run my code, no error is reported; but when using python3 to run it, an error is report after finishing run. The error like as follows: 
Error in `/restools/tools/miniconda/miniconda3/bin/python': corrupted size vs. prev_size: 0x000055b2bcb5c690 ***

**Comment by zou3519** [comment]
Does installing pytorch 0.4.1 help at all?

**Comment by NewEricWang** [comment]
@zou3519 ,  pytorch 0.4.1 has not help.

**Comment by NewEricWang** [comment]
Hi, I found the solution of the error. Just export the following variable:
export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
But I don’t understand why it fixes the problem, and so sadly :(!

Furthermore， my other script will report error when using the setting.

**Comment by hyperfraise** [comment]
Same problem under python3.7, torch 1.0.1, and this doesn't fix it :/ Problem is espacially fierce (and not deterministic) when training groupnorms

**Comment by ngimel** [comment]
Closing due to age

**Comment by NagabhushanSN95** [comment]
> Hi, I found the solution of the error. Just export the following variable: export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4" But I don’t understand why it fixes the problem, and so sadly :(!
> 
> Furthermore， my other script will report error when using the setting.

Man! Thanks a ton for this. This worked!

I've tried so many things and couldn't fix this problem at all. One of my GPUs was effectively unusable due to this. You saved me!
