### ISSUE TITLE
this may be a bug，scatter()

### ISSUE THREAD

**Issue by TonFard** [pytorch/pytorch#105794]
### 🐛 Describe the bug

```python
import torch

idx1 = torch.tensor([[1], [2], [2]])
print(idx1)
idx2 = torch.tensor([[1, 2, 2]]).t()
print(idx2)

# idx1 and idx2 are the same but the output results are different. Why?

a = torch.tensor([[0.6280, 0.5672, 0.3760],
                  [0.4340, 0.9902, 0.1539],
                  [0.4585, 0.2638, 0.6983]])

print(a.gather(0, idx1))
print(a.gather(0, idx2))

# this is output
tensor([[1],
        [2],
        [2]])
tensor([[1],
        [2],
        [2]])
tensor([[0.5672],
        [0.3760],
        [0.3760]])
tensor([[0.4340],
        [0.4585],
        [0.4585]])
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.31

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA Graphics Device
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           165
Model name:                      Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
Stepping:                        5
CPU MHz:                         2900.000
CPU max MHz:                     4800.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5799.77
Virtualization:                  VT-x
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torchaudio==0.12.1+cu113
[pip3] torchgeometry==0.1.2
[pip3] torchstat==0.0.7
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchaudio                0.12.1+cu113             pypi_0    pypi
[conda] torchgeometry             0.1.2                    pypi_0    pypi
[conda] torchstat                 0.0.7                    pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @mruberry @kurtamohler @mikaylagawarecki

**Comment by ZailiWang** [comment]
Hi, with 20230709 nightly the outputs are same (same with your idx2 result). Would you update to latest nightly and verify again? thanks.

**Comment by TonFard** [comment]
i can't understand, what's your mean

**Comment by ZailiWang** [comment]
PyTorch releases wheel files for installation on a daily basis, which is called 'nightly' version. You can install a nightly version by command
```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
```
Per my test, the reported issue cannot be reproduced with the nightly version. It should have been fixed.

**Comment by TonFard** [comment]
okay, thank you

**Comment by mikaylagawarecki** [comment]
Closing as this doesn't reproduce on master :)

```
import torch

torch.manual_seed(0)
idx1 = torch.tensor([[1], [2], [2]])
print(idx1)
idx2 = torch.tensor([[1, 2, 2]]).t()
print(idx2)

# idx1 and idx2 are the same but the output results are different. Why?

a = torch.tensor([[0.6280, 0.5672, 0.3760],
                  [0.4340, 0.9902, 0.1539],
                  [0.4585, 0.2638, 0.6983]])

print(a.gather(0, idx1))
print(a.gather(0, idx2))
```

prints

```
tensor([[1],
        [2],
        [2]])
tensor([[1],
        [2],
        [2]])
tensor([[0.4340],
        [0.4585],
        [0.4585]])
tensor([[0.4340],
        [0.4585],
        [0.4585]])
```
