### ISSUE TITLE
Report C10:error when  using torch::hann_window  in Libtorch

### ISSUE THREAD

**Issue by v3551G** [pytorch/pytorch#105788]
### 🐛 Describe the bug

#include <torch/script.h> // One-stop header.
#include <torch/torch.h>
int nfft = 64;
int window_length = 64;
int hop_length = int(window_length / 2);
torch::Tensor window = torch::hann_window(window_length);
torch::Tensor input_spectgram = torch::stft(input, nfft, hop_length, window_length, window, false, true, true); 

just as you see above,  I'm using STFT to process the input data, However, a bug is reported as follows when the line -6 (i.e the line creating hann_window) is performed, 
-------------------------------
 Unhandled Exception 0x00007 There is an unhandled exception at ffAD8DA2BAC (located in AF detection torch.exe): Microsoft C++ Exception: c10::Error at memory location 0x000000CD001c2110.
--------------------------------

Can you help me fix this issue?

### Versions

Windows 10, Visual studio 2019,  Libotrch:1.10.2,
I'm  sure the environment is configured successfully, since other torch API can be normally used 

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by andreigh** [comment]
I ran the code below successfully on Windows:

```
int main(int argc, char** argv) {
	int nfft = 64;
	int window_length = 64;
	int hop_length = int(window_length / 2);
	torch::Tensor window = torch::hann_window(window_length);
	torch::Tensor input = at::tensor(c10::complex<float>(1.0, 2.0), at::dtype(at::kComplexFloat));
	torch::Tensor input_spectgram = torch::stft(input, nfft, hop_length, window_length, window, false, true, true);
        return 0;
}
```
@v3551G can you confirm if something simple like this still throws the exception ?

**Comment by alinpahontu2912** [comment]
Hello @vgao1996 , are you still dealing with this issue ? Can you also provide the input tensor you used, as I think the problem might be related to that? I ran into that error myself, but the fix suggested [here](https://discuss.pytorch.org/t/problem-using-han-window/155475) helped.  Does that help you too?

**Comment by v3551G** [comment]
Thank you, the question has been addressed.
________________________________
发件人: Stefan-Alin Pahontu ***@***.***>
发送时间: 2023年10月5日 22:00
收件人: pytorch/pytorch ***@***.***>
抄送: V3551G ***@***.***>; Mention ***@***.***>
主题: Re: [pytorch/pytorch] Report C10:error when using torch::hann_window in Libtorch (Issue #105788)


Hello @vgao1996<https://github.com/vgao1996> , are you still dealing with this issue ? Can you also provide the input tensor you used, as I think the problem might be related to that? I ran into that error myself, but the fix suggested here<https://discuss.pytorch.org/t/problem-using-han-window/155475> helped. Does that help you too?

―

**Comment by alinpahontu2912** [comment]
I am closing this issue since it seems resolved, but feel free to open a new issue if you encounter any problems or have feature requests.
