### ISSUE TITLE
[FSDP] Nightlies fail when reloading checkpoints but works fine with v2.0.1

### ISSUE THREAD

**Issue by pacman100** [pytorch/pytorch#105727]
### 🐛 Describe the bug

Nightlies fail when reloading checkpoints with error:
```
File "/home/sourab/accelerate/src/accelerate/utils/fsdp_utils.py", line 192, in load_fsdp_optimizer
    flattened_osd = FSDP.optim_state_dict_to_load(optim_state, model, optimizer)
  File "/home/sourab/miniconda3/envs/hf/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1879, in optim_state_dict_to_load
    state_dict_settings = FullyShardedDataParallel.get_state_dict_type(model)
  File "/home/sourab/miniconda3/envs/hf/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 728, in get_state_dict_type
    for submodule in FullyShardedDataParallel.fsdp_modules(module):
  File "/home/sourab/miniconda3/envs/hf/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 537, in fsdp_modules
    return traversal_utils._get_fsdp_states(module)
  File "/home/sourab/miniconda3/envs/hf/lib/python3.10/site-packages/torch/distributed/fsdp/_traversal_utils.py", line 96, in _get_fsdp_states
    fsdp_states, _ = _get_fsdp_states_with_modules(module)
  File "/home/sourab/miniconda3/envs/hf/lib/python3.10/site-packages/torch/distributed/fsdp/_traversal_utils.py", line 80, in _get_fsdp_states_with_modules
    visited_modules.add(submodule)
TypeError: unhashable type: 'dict'
```

Steps to reproduce:
1. pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
2. pip install accelerate[testing]
3. below cmd commands:
```
cd accelerate
export CUDA_VISIBLE_DEVICES="2,3"
export RUN_SLOW="yes"
export WANDB_DISABLED="true"

pytest -sv tests/fsdp/test_fsdp.py
```

V2.0.1 works fine.

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230720+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA DGX Display
GPU 4: NVIDIA A100-SXM4-80GB

Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] lion-pytorch==0.0.6
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] pytorch-lightning==1.9.0
[pip3] pytorch-triton==2.1.0+9e3e10c5ed
[pip3] torch==2.1.0.dev20230720+cu118
[pip3] torchaudio==2.1.0.dev20230720+cu118
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.16.0.dev20230720+cu118
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] lion-pytorch              0.0.6                    pypi_0    pypi
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.6           py310h1128e8f_1  
[conda] mkl_random                1.2.2           py310h1128e8f_1  
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] numpy-base                1.25.0          py310hb5e798b_0  
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-lightning         1.9.0                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-triton            2.1.0+9e3e10c5ed          pypi_0    pypi
[conda] torch                     2.1.0.dev20230720+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230720+cu118          pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchvision               0.16.0.dev20230720+cu118          pypi_0    pypi

cc @zhaojuanmao @mrshenli @rohan-varma @awgu

**Comment by awgu** [comment]
See https://github.com/huggingface/accelerate/pull/1755

**Comment by awgu** [comment]
As a BE item, we can add type validation on the input args to provide a better error message.

cc: @fegin we can save this as a ramp up task? does not really matter to me

**Comment by awgu** [comment]
https://github.com/huggingface/accelerate/pull/1755
