### ISSUE TITLE
UNSTABLE periodic / linux-bionic-cuda11.8-py3.9-gcc7 / test (multigpu)

### ISSUE THREAD

**Issue by PaliC** [pytorch/pytorch#105762]
> Please provide a brief reason on why you need to mark this job as unstable.

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
The multigpu job is relied upon to test several optim and distributed features among others. Tentatively marking as high pri as we should stabilize ASAP.

**Comment by janeyx99** [comment]
Following discussion: @atalman noticed this job has been flaky for a while now and will keep investigating

**Comment by huydhn** [comment]
The potential fix has been merged https://github.com/pytorch/pytorch/pull/105759.  So far so good, but we'll still need to monitor it further.  I'll close this issue to make failures more obvious instead of being hidden as an unstable job.
