### ISSUE TITLE
[Caffe2] Error C2487 when building DLL.

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#10570]
## Issue description

VS complains about `C2487` if there're nested `CAFFE2_API`.

```
caffe2\core\operator_schema.h(269): error C2487: 'Arg_IsTest': member of dll interface class may not be declared with dll interface
caffe2\core\context_base.h(171): error C2487: 'static_context_': member of dll interface class may not be declared with dll interface
caffe2\core\context.h(209): error C2487: 'reporter_': member of dll interface class may not be declared with dll interface
```

## System Info
- PyTorch or Caffe2: C2
- How you installed PyTorch (conda, pip, source): src
- Build command you used (if compiling from source): cmake
- OS: Win10
- PyTorch version: master
- VS version (if compiling from source): 2017
- CMake version: 3.12

**Comment by peterjc123** [comment]
Maybe we should close this?

**Comment by xkszltl** [comment]
Yes
