### ISSUE TITLE
Dynamo test pipeline failed on MaxPool2d test when changed to use f-string

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#105716]
### 🐛 Describe the bug

Tests

[linux-bionic-py3.11-clang9 / test (dynamo, 1, 2, linux.2xlarge)](https://hud.pytorch.org/pr/pytorch/pytorch/105436#15182560189) ([gh](https://github.com/pytorch/pytorch/actions/runs/5604098622/jobs/10251876391))
[linux-bionic-py3.8-clang9 / test (dynamo, 1, 2, linux.2xlarge)](https://hud.pytorch.org/pr/pytorch/pytorch/105436#15182563911) ([gh](https://github.com/pytorch/pytorch/actions/runs/5604098622/jobs/10251879196))

fails when the string format call in `cls_name = 'MaxPool{}d'.format(num_dim)` is changed to f-string in `_test_maxpool_indices`. For some reason the name becomes `MaxPool1d` even when it should be `MaxPool2d`

I could not reproduce in either a linux environment or on an m1 mac. It only happens in CI.

https://github.com/pytorch/pytorch/pull/105436#issuecomment-1642786366

### Versions

```
PyTorch version: 2.1.0a0+git2d16f88
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] numpy==1.25.1
[pip3] pytorch==2.1.0a0+git2d16f88
[conda] Could not collect
```

cc @seemethere @malfet @pytorch/pytorch-dev-infra @mruberry @ZainRizvi @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @anijain2305 @Xia-Weiwen @ipiszy

**Comment by anijain2305** [comment]
cc @yanboliang Lets check if we can reproduce this and close if not.

**Comment by anijain2305** [comment]
Already fixed on main.
