### ISSUE TITLE
vmap function ignores keyword arguments on some functions

### ISSUE THREAD

**Issue by ishiihiro** [pytorch/pytorch#105736]
### 🐛 Describe the bug

I encountered a bug where the vmap function does not respect the keyword arguments on some functions, such as F.cross_entropy. For example, the following code snippet
```python
import torch
from torch.nn import fucntional as F

y = torch.randn(2, 3)
t = torch.tensor([-1, 2])

torch.vmap(F.cross_entropy)(y, t, ignore_index=-1)
```
gives an error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ishiihiro/.pyenv/versions/asdl/lib/python3.9/site-packages/torch/_functorch/vmap.py", line 434, in wrapped
    return _flat_vmap(
  File "/Users/ishiihiro/.pyenv/versions/asdl/lib/python3.9/site-packages/torch/_functorch/vmap.py", line 39, in fn
    return f(*args, **kwargs)
  File "/Users/ishiihiro/.pyenv/versions/asdl/lib/python3.9/site-packages/torch/_functorch/vmap.py", line 619, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
  File "/Users/ishiihiro/.pyenv/versions/asdl/lib/python3.9/site-packages/torch/nn/functional.py", line 2704, in nll_loss
    return torch._C._nn.nll_loss_nd(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: index -1 is out of bounds for dimension 1 with size 3
```
even though I specified “ignore_index=-1” as a keyword argument.
In addition, I observed that the same bug affects “F.nll_loss” and “nn.CrossEntropyLoss(ignore_index=-1)” functions, and that the “weight” argument is also ignored by vmap.
This error does not occur when I use F.cross_entropy without vmap. I expected vmap to pass the keyword arguments to the function it is mapping over. Is this a bug or a limitation of vmap? If it is a bug, how can I fix it or work around it? If it is a limitation, is there any plan to support keyword arguments in vmap in the future?

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.4 (default, Apr 17 2021, 00:37:59)  [Clang 12.0.0 (clang-1200.0.32.29)] (64-bit runtime)
Python platform: macOS-13.4.1-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz

Versions of relevant libraries:
[pip3] functorch==2.0.0
[pip3] numpy==1.25.0
[pip3] torch==2.0.1
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

**Comment by zou3519** [comment]
I can reproduce this error. Not sure what's wrong yet. This may be a scalar tensor handling issue

**Comment by kshitij12345** [comment]
I think the above code has bug because as per the docs, target should always have value between `0` and `C-1` but target has `-1`.

Doc Ref: https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html
Doc Ref: https://pytorch.org/docs/stable/generated/torch.nn.NLLLoss.html

-------

As for the reason why it works on eager and not with vmap is

**Eager**: Eager code has roughly the following structure.

```python
if (curr_idx == ignore_idx): continue

# Do bounds check
```

Implementation code will work with a negative target if `ignore_index==negative_target` (I think this is a bug in eager). It will fail if `target=[-2]` and `ignore_idx=-1` with `IndexError: Target -2 is out of bounds.` 

**Vmap**: vmap implementation only works valid indices i.e. between 0 and C-1.

**Comment by ishiihiro** [comment]
Thank you for your reply. However, I think you might have missed [the part of the doc](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#:~:text=if%20ignore_index%20is%20specified%2C%20this%20loss%20also%20accepts%20this%20class%20index%20(this%20index%20may%20not%20necessarily%20be%20in%20the%20class%20range)) that says “if ignore_index is specified, this loss also accepts this class index (this index may not necessarily be in the class range)”. This means that the functions should accept a class index that is outside of the class range, as long as it matches the ignore_index. For example, if ignore_index=-1, then the functions should accept -1 as a valid target value and ignore it for the loss computation. This is the expected behavior of these functions, and it works fine without vmap. The bug is that vmap does not respect this behavior and throws an error when it encounters a target value equal to ignore_index. I hope this clarifies my issue.

**Comment by kshitij12345** [comment]
@ishiihiro You are right, I missed that line! Thanks
