### ISSUE TITLE
[TransformerEngine&Kineto] `RuntimeError: *tag_it == Tag::Tensor INTERNAL ASSERT FAILED`

### ISSUE THREAD

**Issue by danthe3rd** [pytorch/pytorch#105748]
### 🐛 Describe the bug

Hello,
I'm running some tests on H100 with TransformerEngine, and this simple code causes an assertion failure when enabling fp8 (corresponding issue in TransformerEngine: https://github.com/NVIDIA/TransformerEngine/issues/336):

### Repro
```python
import time
import torch
import torch.nn as nn
from torch.profiler import profile, record_function, ProfilerActivity
import transformer_engine.pytorch as te
from transformer_engine.common import recipe

dim, n_heads = 128, 1
seqlen = 128
batch_size = 2


model = te.TransformerLayer(
    hidden_size=dim,
    ffn_hidden_size=dim * 4,
    num_attention_heads=n_heads)
model.to("cuda").to(torch.float16)
inp = torch.randn([
    batch_size,
    seqlen,
    dim], device="cuda", dtype=torch.float16, requires_grad=True)

fp8_recipe = recipe.DelayedScaling(fp8_format=recipe.Format.E4M3)
fp8 = True

def forward():
    with te.fp8_autocast(enabled=fp8, fp8_recipe=fp8_recipe):
        with torch.no_grad():
            model(inp)

forward() # <- this is necessary to repro the bug
with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True) as prof:
    forward()
    # <- Crash happens here

```

### Log
```
STAGE:2023-07-21 16:13:56 216479:216479 ActivityProfilerController.cpp:312] Completed Stage: Warm Up
STAGE:2023-07-21 16:13:57 216479:216479 ActivityProfilerController.cpp:318] Completed Stage: Collection
STAGE:2023-07-21 16:13:57 216479:216479 ActivityProfilerController.cpp:322] Completed Stage: Post Processing
(base) user@compute-node-1:~/bench$python bug_fp8.py 
/home/user/TransformerEngine/transformer_engine/pytorch/transformer.py:227: DeprecationWarning: Arguments `attention_softmax_in_fp32` and `apply_query_key_layer_scaling`are deprecated and will be fully removed in future releases.
  warnings.warn(
STAGE:2023-07-21 16:14:34 216714:216714 ActivityProfilerController.cpp:312] Completed Stage: Warm Up
/home/user/TransformerEngine/transformer_engine/pytorch/jit.py:151: UserWarning: nvfuser integration in TorchScript is deprecated. (Triggered internally at ../torch/csrc/jit/codegen/cuda/interface.cpp:235.)
  return bias_dropout_add_fused_train_(x, bias, residual, prob)
Traceback (most recent call last):
  File "/home/user/bench/bug_fp8.py", line 33, in <module>
    with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True) as prof:
  File "/home/user/miniconda3/lib/python3.11/site-packages/torch/profiler/profiler.py", line 563, in __exit__
    self.stop()
  File "/home/user/miniconda3/lib/python3.11/site-packages/torch/profiler/profiler.py", line 576, in stop
    self._transit_action(self.current_action, None)
  File "/home/user/miniconda3/lib/python3.11/site-packages/torch/profiler/profiler.py", line 604, in _transit_action
    action()
  File "/home/user/miniconda3/lib/python3.11/site-packages/torch/profiler/profiler.py", line 155, in stop_trace
    self.profiler.__exit__(None, None, None)
  File "/home/user/miniconda3/lib/python3.11/site-packages/torch/autograd/profiler.py", line 281, in __exit__
    self.kineto_results = _disable_profiler()
                          ^^^^^^^^^^^^^^^^^^^
RuntimeError: *tag_it == Tag::Tensor INTERNAL ASSERT FAILED at "../torch/csrc/profiler/collection.cpp":220, please report a bug to PyTorch. 1
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230721+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1033-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.2.91
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          192
On-line CPU(s) list:             0-191
Thread(s) per core:              2
Core(s) per socket:              48
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7R13 Processor
Stepping:                        1
CPU MHz:                         2650.000
BogoMIPS:                        5300.00
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       3 MiB
L1i cache:                       3 MiB
L2 cache:                        48 MiB
L3 cache:                        384 MiB
NUMA node0 CPU(s):               0-47,96-143
NUMA node1 CPU(s):               48-95,144-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save vaes vpclmulqdq rdpid

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+9e3e10c5ed
[pip3] torch==2.1.0.dev20230721+cu121
[pip3] torchaudio==2.1.0.dev20230721+cu121
[pip3] torchvision==0.16.0.dev20230721+cu121
[pip3] triton-nightly==2.1.0.dev20230720050651
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+9e3e10c5ed          pypi_0    pypi
[conda] torch                     2.1.0.dev20230721+cu121          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230721+cu121          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230721+cu121          pypi_0    pypi
[conda] triton-nightly            2.1.0.dev20230720050651          pypi_0    pypi

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by davidberard98** [comment]
Minimal repro here

```python
import torch

def fn(x, y):
    return torch.cat([x, y])

fn_opt = torch.compile(fn, dynamic=True)
with torch.profiler.profile(record_shapes=True) as prof:
    for i in range(10):
        x = torch.rand(i*2+4, 8, device='cuda')
        y = torch.rand(i*2+5, 8, device='cuda')
        fn_opt(x, y)

prof.export_chrome_trace("h100_issue.json")
```

Will try to write a fix within the next few days
