### ISSUE TITLE
Revisit checkpoint naming mismatch with torch name (and ONNX initializer name as a consequence)

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#105751]
Addresses https://github.com/pytorch/pytorch/blob/main/torch/onnx/_internal/fx/serialization.py#L138-L152 within `save_model_with_external_data` utility.

The hugging face model, for example, may have a checkpoint with keys `transformer.h.0.attn.bias` while the fx model has name `h.0.attn.bias`

Track why this discrepancy happens and fix it, if applicable

**Comment by janeyx99** [comment]
I’m supposing this is a tracking issue for ONNX who already has context. If this is not meant as that, please include more details in the issue description and let us know if there is a better owner/maintainer for the issue.
