### ISSUE TITLE
crash using distributed with overlapping ProcessGroup

### ISSUE THREAD

**Issue by Alan-Chen99** [pytorch/pytorch#105772]
### 🐛 Describe the bug

```python
import os

import torch
import torch.distributed as dist
import torch.multiprocessing as mp


def debug_group(group):
    tensor = torch.tensor([10 ** dist.get_rank()], dtype=torch.float).cuda()
    dist.all_reduce(tensor, group=group)
    print(dist.get_rank(), tensor)


def par_main(rank: int, n: int, m: int):
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "11355"
    dist.init_process_group("nccl", rank=rank, world_size=n * m)
    torch.cuda.set_device(rank)
    rank_mat = [list(range(i * n, (i + 1) * n)) for i in range(m)]
    row_group, _ = dist.new_subgroups_by_enumeration(rank_mat)
    col_group, _ = dist.new_subgroups_by_enumeration(list(map(list, zip(*rank_mat))))

    dist.barrier()
    debug_group(row_group)
    dist.barrier()
    debug_group(col_group)
    dist.barrier()
    dist.destroy_process_group()


def run(n=3, m=2):
    mp.spawn(par_main, args=(n, m), nprocs=n * m, join=True)


if __name__ == "__main__":
    run()
```

```
3 tensor([111000.], device='cuda:3')
5 tensor([111000.], device='cuda:5')
4 tensor([111000.], device='cuda:4')
0 tensor([111.], device='cuda:0')
2 tensor([111.], device='cuda:2')
1 tensor([111.], device='cuda:1')
Traceback (most recent call last):
  File "experimental/alan/crash.py", line 41, in <module>
    run()
  File "experimental/alan/crash.py", line 37, in run
    mp.spawn(par_main, args=(n, m), nprocs=n * m, join=True)
  File "/home/alan/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/alan/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/alan/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 2 terminated with signal SIGBUS
```

Note: for this specific case it runs when removing all barriers. For my actual use case it crashes without any barrier.

### Versions

PyTorch version: 2.1.0.dev20230721+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090
GPU 2: NVIDIA GeForce RTX 4090
GPU 3: NVIDIA GeForce RTX 4090
GPU 4: NVIDIA GeForce RTX 4090
GPU 5: NVIDIA GeForce RTX 4090

Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          48
On-line CPU(s) list:             0-47
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7443P 24-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         1500.000
CPU max MHz:                     4035.6440
CPU min MHz:                     1500.0000
BogoMIPS:                        5700.21
Virtualization:                  AMD-V
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        12 MiB
L3 cache:                        128 MiB
NUMA node0 CPU(s):               0-47
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] pytorch-triton==2.1.0+9e3e10c5ed
[pip3] torch==2.1.0.dev20230721+cu118
[conda] Could not collect

### Environment Variables
```
NV_LIBCUBLAS_VERSION=11.11.3.6-1
NVIDIA_VISIBLE_DEVICES=all
COLORTERM=truecolor
NV_NVML_DEV_VERSION=11.8.86-1
NV_CUDNN_PACKAGE_NAME=libcudnn8
NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.16.2-1+cuda11.8
NV_LIBNCCL_DEV_PACKAGE_VERSION=2.16.2-1
HOSTNAME=devcontainer
NVIDIA_REQUIRE_CUDA=cuda>=11.8 brand=tesla,driver>=450,driver<451 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=510,driver<511 brand=unknown,driver>=510,driver<511 brand=nvidia,driver>=510,driver<511 brand=nvidiartx,driver>=510,driver<511 brand=geforce,driver>=510,driver<511 brand=geforcertx,driver>=510,driver<511 brand=quadro,driver>=510,driver<511 brand=quadrortx,driver>=510,driver<511 brand=titan,driver>=510,driver<511 brand=titanrtx,driver>=510,driver<511 brand=tesla,driver>=515,driver<516 brand=unknown,driver>=515,driver<516 brand=nvidia,driver>=515,driver<516 brand=nvidiartx,driver>=515,driver<516 brand=geforce,driver>=515,driver<516 brand=geforcertx,driver>=515,driver<516 brand=quadro,driver>=515,driver<516 brand=quadrortx,driver>=515,driver<516 brand=titan,driver>=515,driver<516 brand=titanrtx,driver>=515,driver<516
NV_LIBCUBLAS_DEV_PACKAGE=libcublas-dev-11-8=11.11.3.6-1
NV_NVTX_VERSION=11.8.86-1
NV_CUDA_CUDART_DEV_VERSION=11.8.89-1
NV_LIBCUSPARSE_VERSION=11.7.5.86-1
NV_LIBNPP_VERSION=11.8.0.86-1
NCCL_VERSION=2.16.2-1
PWD=/home/alan
NV_CUDNN_PACKAGE=libcudnn8=8.9.0.131-1+cuda11.8
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NV_NVPROF_DEV_PACKAGE=cuda-nvprof-11-8=11.8.87-1
NV_LIBNPP_PACKAGE=libnpp-11-8=11.8.0.86-1
NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
NV_LIBCUBLAS_DEV_VERSION=11.11.3.6-1
NVIDIA_PRODUCT_NAME=CUDA
NV_LIBCUBLAS_DEV_PACKAGE_NAME=libcublas-dev-11-8
NV_CUDA_CUDART_VERSION=11.8.89-1
HOME=/home/alan
VIRTUAL_ENV=/home/alan/venv
CUDA_VERSION=11.8.0
NV_LIBCUBLAS_PACKAGE=libcublas-11-8=11.11.3.6-1
NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE=cuda-nsight-compute-11-8=11.8.0-1
NV_LIBNPP_DEV_PACKAGE=libnpp-dev-11-8=11.8.0.86-1
NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-8
NV_LIBNPP_DEV_VERSION=11.8.0.86-1
GO_VERSION=1.20.3
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm
NV_LIBCUSPARSE_DEV_VERSION=11.7.5.86-1
LESSOPEN=| /usr/bin/lesspipe %s
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
NV_CUDNN_VERSION=8.9.0.131
MAVEN_HOME=/usr/share/maven
SHLVL=1
NV_CUDA_LIB_VERSION=11.8.0-1
NVARCH=x86_64
NV_CUDNN_PACKAGE_DEV=libcudnn8-dev=8.9.0.131-1+cuda11.8
NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-8
NV_LIBNCCL_PACKAGE=libnccl2=2.16.2-1+cuda11.8
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
PS1=(venv) ${debian_chroot:+($debian_chroot)}\u@\h:\w\$ 
NV_CUDA_NSIGHT_COMPUTE_VERSION=11.8.0-1
NV_NVPROF_VERSION=11.8.87-1
PATH=/home/alan/venv/bin:/home/alan/.cargo/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/alan/.local/bin:/home/
NV_LIBNCCL_PACKAGE_NAME=libnccl2
NV_LIBNCCL_PACKAGE_VERSION=2.16.2-1
```

Update: It appears that the bug only happen when running inside docker
Update2: can reproduce on nvidia/cuda:11.8.0-devel-ubuntu20.04 and nvidia/cuda:12.2.0-devel-ubuntu20.04

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by kumpera** [comment]
Could you provide the logs of the ranks and not the main process?

**Comment by Alan-Chen99** [comment]
I was able to fix this by increasing shared memory inside the container to `--shm-size=10240m` instead of `--shm-size=1024m`
