### ISSUE TITLE
DDP with DataLoader num_workers>0 seems to result in GIL (CPU summing to 100%)

### ISSUE THREAD

**Issue by CalumF** [pytorch/pytorch#105841]
### 🐛 Describe the bug

When running the pl Trainer with ddp on a single node with multiple gpus and DataLoader(..., num_workers=2) (or >0) CPU use seems to max at 100% - when num_woerkers=0 it will go much higher.

Running the below boring model results in very slow data loading with htop outputs like this:
![image](https://github.com/pytorch/pytorch/assets/46681532/7f796b45-0c26-4eeb-96a6-43f61e1047ad)

It looks like there are 100%/16 workes = ~6.25% each

On the other hand if I run it with num_workers=0 I get faster training and much better CPU utilisation:
![image](https://github.com/pytorch/pytorch/assets/46681532/5dfd889f-ce07-43d9-8660-2f5dc8a1d5c6)

When using num_workers=0 in practice with more complex dataloading workflows it is still a bottleneck (but still better utilisation than n>0).

Is this how it's supposed to function? The docs seem to suggest setting num_workers=num_cpus however it seems like num_workers is per device?

Any help/advice would be appreciated!

```python

import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, Dataset
import pytorch_lightning as pl
tmpdir = os.getcwd()


class RandomDataset(Dataset):
    def __init__(self, shape, num_samples) -> None:
        super().__init__()
        self.shape = shape
        self.num_samples = num_samples
    
    def __len__(self):
        return self.num_samples
    
    def __getitem__(self, idx):
        return torch.randn(self.shape)**(5/4)

num_samples = 10000
train = RandomDataset((3, 2048, 2048), num_samples)
train = DataLoader(train, batch_size=32, pin_memory=True, num_workers=2)
val = RandomDataset((3, 2048, 2048), num_samples)
val = DataLoader(val, batch_size=32, pin_memory=True, num_workers=2)

class BoringModel(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Conv2d(3, 1, 1)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        self.log('train_loss', loss)
        return loss


    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"x": loss}


    def test_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        self.log('test_loss', loss)
        return {"y": loss}


    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]

def test(tmpdir):
    # init model
    model = BoringModel()

    # Initialize a trainer
    trainer = pl.Trainer(
        accelerator='gpu',
        strategy='ddp',
        devices=8,
        max_epochs=1,
        precision='bf16-mixed',
        default_root_dir=tmpdir
    )

    trainer.fit(model, train)

test(tmpdir)
```

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.10.0-23-cloud-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA RTX A4000
GPU 1: NVIDIA RTX A4000
GPU 2: NVIDIA RTX A4000
GPU 3: NVIDIA RTX A4000
GPU 4: NVIDIA RTX A4000
GPU 5: NVIDIA RTX A4000
GPU 6: NVIDIA RTX A4000
GPU 7: NVIDIA RTX A4000

Nvidia driver version: 510.85.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   40 bits physical, 48 bits virtual
CPU(s):                          30
On-line CPU(s) list:             0-29
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       30
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7313 16-Core Processor
Stepping:                        1
CPU MHz:                         3000.039
BogoMIPS:                        6000.07
Virtualization:                  AMD-V
L1d cache:                       1.9 MiB
L1i cache:                       1.9 MiB
L2 cache:                        15 MiB
L3 cache:                        480 MiB
NUMA node0 CPU(s):               0-29
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr wbnoinvd arat npt nrip_save umip pku ospke vaes vpclmulqdq rdpid arch_capabilities

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.24.4
[pip3] pytorch-lightning==2.0.5
[pip3] segmentation-models-pytorch==0.3.3
[pip3] torch==2.0.1
[pip3] torch-tb-profiler==0.4.1
[pip3] torchmetrics==0.12.0.dev0
[pip3] torchview==0.2.6
[pip3] torchvision==0.15.2
[pip3] torchviz==0.0.2
[pip3] triton==2.0.0
[conda] No relevant packages

**Comment by haoyudong-97** [comment]
Hi, did you solve this issue? I'm facing the same issue now
