### ISSUE TITLE
Use easyocr to identify pictures, torch reports lack of mps

### ISSUE THREAD

**Issue by a1boyband** [pytorch/pytorch#105895]
### 🐛 Describe the bug

env:
centos:8
python:3.6

[root@nessus-server ~]# easyocr -l ch_sim -f 222.png --gpu=False
Traceback (most recent call last):
  File "/usr/local/bin/easyocr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/easyocr/cli.py", line 252, in main
    quantize=args.quantize)
  File "/usr/local/lib/python3.6/site-packages/easyocr/easyocr.py", line 75, in __init__
    elif torch.backends.mps.is_available():
AttributeError: module 'torch.backends' has no attribute 'mps'

[root@nessus-server ~]# python3
Python 3.6.8 (default, Jun 26 2023, 20:26:30)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch import mps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'mps'
>>>

### Versions

[root@nessus-server ~]# pip3 show easyocr
Name: easyocr
Version: 1.7.0
Summary: End-to-End Multi-Lingual Optical Character Recognition (OCR) Solution
Home-page: https://github.com/jaidedai/easyocr
Author: Rakpong Kittinaradorn
Author-email: r.kittinaradorn@gmail.com
License: Apache License 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: ninja, numpy, opencv-python-headless, Pillow, pyclipper, python-bidi, PyYAML, scikit-image, scipy, Shapely, torch, torchvision
Required-by:
[root@nessus-server ~]#

[root@nessus-server ~]# pip3 show torch
Name: torch
Version: 1.10.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib64/python3.6/site-packages
Requires: dataclasses, typing-extensions
Required-by: easyocr, torchaudio, torchvision

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by albanD** [comment]
Hi,

The mps package was added in recent versions of PyTorch but you're running 1.10.1.
Please updgrade to 2.0+ to get this feature.

**Comment by malfet** [comment]
Closing, as it seems like a very straightforward version compatibility problem: easyocr-1.7.0 is not compatible with torch-1.10.0, but easyocr-1.5.0 is, so either downgrade easyocr, or upgrade your version of pytorch.
Also, feel free to open an issue against easyocr to recommend specify minsupported version of dependencies for their release
