### ISSUE TITLE
Exporting the operator 'aten::grad' to ONNX opset version 18 is not supported.

### ISSUE THREAD

**Issue by Tihaw** [pytorch/pytorch#105838]
### 🚀 The feature, motivation and pitch

I am attampting to conver a model from pytorch to ONNX, inside which there is a gradient calculation operation:
torch.autograd.grad(params...)
(I was using the backward hooks to get gradients, but torchscript does not support that)

And then when it calls
jitscriptModule = torch.jit.script(model)   # good, and torchscript pt model works well
torch.onnx.export(jitscriptModule, tensor, "converted.onnx") # bad, operator not supported occurs.

torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::grad' to ONNX opset version 18 is not supported.

### Alternatives

Using pytorch 2.0.1

### Additional context

Will this feature be supported by future pytorch? 

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
