### ISSUE TITLE
UNSTABLE pull / linux-bionic-cuda12.1-py3.10-gcc9-sm86 / test (default)

### ISSUE THREAD

**Issue by DanilBaibak** [pytorch/pytorch#105908]
The new changes introduced the additional use of onnx - https://github.com/pytorch/pytorch/pull/105618. Potentially tests consume more memory than before. This caused the OOM issue.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
The OOM error is fixed by reverting https://github.com/pytorch/pytorch/pull/104310
