### ISSUE TITLE
CUDA out of memory / linux.g5.4xlarge.nvidia.gpu

### ISSUE THREAD

**Issue by DanilBaibak** [pytorch/pytorch#105905]
## Current Status
There is a "CUDA out of memory" error for  linux.g5.4xlarge.nvidia.gpu instances.

## Error looks like
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 21.99 GiB of which 7.96 GiB is free. Process 1488 has 248.00 MiB memory in use. Process 1582 has 4.36 GiB memory in use. Process 3537 has 248.00 MiB memory in use. Process 8671 has 8.90 GiB memory in use. Process 8829 has 252.00 MiB memory in use. Of the allocated memory 3.11 GiB is allocated by PyTorch, and 5.46 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.
```

## Incident timeline (all times pacific)
* The incident began at 2023-07-25 06:59:27
*  It was detected 2023-07-25 09:48:00

## User impact
The `linux-bionic-cuda12.1-py3.10-gcc9-sm86` jobs are stuck in the queue.

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by DanilBaibak** [comment]
Ran "Do Terraform Release" to refresh the infrastructure.

**Comment by albanD** [comment]
Which test causes that? Why nn/inductor?

**Comment by mikaylagawarecki** [comment]
I think it is in reference to this which was reverted https://github.com/pytorch/pytorch/pull/104310#issuecomment-1650310307

cc @DanilBaibak please correct me if I'm wrong

**Comment by DanilBaibak** [comment]
Correct, the issue is related to PR [#104310](https://github.com/pytorch/pytorch/pull/104310)

**Comment by DanilBaibak** [comment]
The cause of failure was PR [#104310](https://github.com/pytorch/pytorch/pull/104310). The PR has been reverted. The author works on a fix.
