### ISSUE TITLE
Dynamo silently ignores TorchDispatchMode

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#105929]
### 🐛 Describe the bug

This test fails:

```
diff --git a/test/dynamo/test_misc.py b/test/dynamo/test_misc.py
index 4ac6b803ddb..43083783cc3 100644
--- a/test/dynamo/test_misc.py
+++ b/test/dynamo/test_misc.py
@@ -38,6 +38,7 @@ from torch._dynamo.testing import (
     unsupported,
 )
 
+from torch.utils._python_dispatch import TorchDispatchMode
 from torch._dynamo.utils import CompileProfiler, ifdynstaticdefault
 from torch.ao.quantization import MinMaxObserver
 from torch.ao.quantization.fake_quantize import FakeQuantize
@@ -6040,6 +6041,22 @@ def ___make_guard_fn():
         self.assertEqual(counter.frame_count, 1)
         self.assertEqual(counter.op_count, 3)
 
+    def test_mode_guard(self):
+        class RewriteAddToMul(TorchDispatchMode):
+            def __torch_dispatch__(self, func, types, args=(), kwargs=None):
+                if func is torch.ops.aten.add.Tensor:
+                    func = torch.ops.aten.mul.Tensor
+                return func(*args, **kwargs)
+
+        def fn(x):
+            return x + x
+
+        x = torch.tensor([3.0])
+        with RewriteAddToMul():
+            r = fn(x)
+            opt_r = torch.compile(fn)(x)
+        self.assertEqual(r, opt_r)
+
     def test_tracing_nested_py_tree(self):
         import torch.utils._pytree as pytree
 
```

Note that if you don't make torch.compile unconditionally bail out and have it handle torch dispatch mode, you need to add appropriate guards; this test doesn't exercise that the guards are correct.

### Versions

main

cc @gchanan @zou3519 @kadeng @Chillee @albanD @samdow @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @wconstab @aakhundov @Xia-Weiwen @ipiszy

**Comment by ezyang** [comment]
cc @voznesenskym @bdhirsh @wanchaol

**Comment by anijain2305** [comment]
@voznesenskym @yanboliang and I discussed this. There are 2 ways

1) Graph break for now - Look at the dispatcher stack in convert_frame.py and essentially skip. Nicer way is to make a VT and `unimplement` most parts of it.
2) Actually support it - requires more discussion

**Comment by bdhirsh** [comment]
This test still fails for me. Related to https://github.com/pytorch/pytorch/issues/114405 (fyi if you're interested @jon-chuang). In addition to generating "subclass guards" for graph inputs that are subclasses, we should also be guarding on the current torchdispatch mode stack

**Comment by ezyang** [comment]
Standalone repro and yes it still fails

```
(/home/ezyang/local/b/pytorch-env) [ezyang@devgpu005.nha1 ~/local/b/pytorch (0a1b3be2)]$ python ak.py
tensor([9.])
tensor([6.])
(/home/ezyang/local/b/pytorch-env) [ezyang@devgpu005.nha1 ~/local/b/pytorch (0a1b3be2)]$ cat ak.py
import torch
from torch.utils._python_dispatch import TorchDispatchMode

class RewriteAddToMul(TorchDispatchMode):
    def __torch_dispatch__(self, func, types, args=(), kwargs=None):
        if func is torch.ops.aten.add.Tensor:
            func = torch.ops.aten.mul.Tensor
        return func(*args, **kwargs)

def fn(x):
    return x + x

x = torch.tensor([3.0])
with RewriteAddToMul():
    r = fn(x)
    opt_r = torch.compile(fn)(x)
print(r)
print(opt_r)
```

**Comment by bdhirsh** [comment]
From talking with @zou3519:

* dynamo should either error or graph break on TorchDispatchModes by default

* modes that we care about (e.g. FlopCounter) should have some way of telling us that we should not graph break on them, similar to `is_traceable_wrapper_subclass()` (which dynamo uses to know if a subclass is safe to compile

* one piece of weirdness today is that: for subclasses, we only care about them getting traced through at compile time. But for modes, we have modes like FlopCounter today that want to interpose only at runtime. We need to decide whether modes + compile should only interpose at runtime, or if we want a way for a user to specify whether their mode should interpose at compile time vs runtime.
