### ISSUE TITLE
torch.compile(cpu) does not handle float16 properly

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#105914]
### 🐛 Describe the bug

```python
import torch
a = torch.randn(64, dtype=torch.float16)

@torch.compile
def f(a, dim=-1):
    na = torch.linalg.vector_norm(a, dim=dim)
    eps = 1e-8
    return na.clamp_min(eps)

f(a)
```

This does work with `bfloat16`. The issue here is that `bfloat16` works because there exists the magic helper function
https://github.com/pytorch/pytorch/blob/5f6c6ff4cf27e4924aee4e3c951efe83bf95c106/torch/_inductor/codegen/cpp.py#L2516
This function inserts the necessary `to_dtype`s for `bfloat16` to work. This hack should either be removed or generalised to other dtypes.

### Versions

master

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by lezcano** [comment]
Found when writing https://github.com/pytorch/pytorch/pull/104771

**Comment by jgong5** [comment]
> cc @jgong5 @XiaobingSuper No idea why the tag was not tagging you guys

Ah, no idea but this should work after this PR is landed: https://github.com/pytorch/pytorch/pull/100857, cc @zhuhaozhe

**Comment by zhuhaozhe** [comment]
Already supported by https://github.com/pytorch/pytorch/pull/100857. Feel free to re-open if not corrected.
