### ISSUE TITLE
Dynamo Not Preserving Bufferness

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#106060]
### 🐛 Describe the bug

```
import torch

class Mod(torch.nn.Module):
    def __init__(self):
        super(Mod, self).__init__()
        self.register_buffer("buffer", torch.rand([4], device="cuda"))

    def forward(self, x):
        # should be a no-op, but causes dynamo to lose the static input
        self.buffer = self.buffer.to(x)
        return self.buffer + x

@torch.compile(mode="reduce-overhead")
def foo(mod, inp):
    mod(inp)


m = Mod()
foo(m, torch.rand([4], device="cuda"))
```

Will result in 0 static inputs / no buffers passed to aot_autograd. This is a minified repro of llama issue I'm looking at that prevents cudagraph speed ups (1.6x -> 4.4 on TB inference)

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov @yanboliang 

### Versions

master

**Comment by voznesenskym** [comment]
This repro doesn't run as is, a modified script to better illustrate the issue runs fine

```
import torch
from torch.func import functional_call
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

import torch

class Mod(torch.nn.Module):
    def __init__(self):
        super(Mod, self).__init__()

        self.buffer = torch.tensor([0.5, 0.5, 0.5, 0.5])

    def forward(self, x):
        # should be a no-op, but causes dynamo to lose the static input
        self.buffer = self.buffer.to(x)
        self.buffer.add_(x)
        return self.buffer + x

eager_mod = Mod()
eager_result = eager_mod(torch.tensor([0.5, 0.5, 0.5, 0.5], device="cuda"))
out_mod = torch._dynamo.optimize("eager", nopython=True)(Mod())
compiled_result = out_mod(torch.tensor([0.5, 0.5, 0.5, 0.5], device="cuda"))
```

Please resubmit as a failing unit test?

**Comment by voznesenskym** [comment]
changing to register buffer is the fix to get what Elias wants.

**Comment by eellison** [comment]
```
diff --git a/torch/_inductor/compile_fx.py b/torch/_inductor/compile_fx.py
index 62c57c8cb7d..fb5333f764f 100644
--- a/torch/_inductor/compile_fx.py
+++ b/torch/_inductor/compile_fx.py
@@ -280,6 +280,10 @@ def compile_fx_inner(
     user_visible_outputs=frozenset(),
     layout_opt=None,
 ):
+
+    print("num_fixed", num_fixed)
+    print(len(list(gm.named_buffers())))
+
     if dynamo_utils.count_calls(gm.graph) == 0:
         return make_boxed_func(gm.forward)
 
 ```
 
 Still gives 0 fixed/ 0 buffers

**Comment by eellison** [comment]
I think because of the set attr on the Graph Module we convert it to unspecialized, and dont preserver bufferness:
```
        elif isinstance(obj, variables.NNModuleVariable):
            if not tx.output.is_root_tracer():
                raise AttributeMutationError(
                    "Can't inplace modify module params/buffers inside HigherOrderOp"
                )
            obj.convert_to_unspecialized(tx)
```

This is kind of a funny case, because the getattr and the setattr are the same variable, so it's a no-op. E.g. we would also make an unspecialized module on `nn_module.buffer = nn_module.buffer`.

**Comment by yanboliang** [comment]
> This is kind of a funny case, because the getattr and the setattr are the same variable, so it's a no-op. E.g. we would also make an unspecialized module on nn_module.buffer = nn_module.buffer.

I think they are different in dynamo, ```setattr``` may trigger side effect.

**Comment by ezyang** [comment]
I guess we can special case this if you really want to....

**Comment by eellison** [comment]
I submitted pr

**Comment by eellison** [comment]
Fix: https://github.com/pytorch/pytorch/pull/106092
