### ISSUE TITLE
Specifying parameters for RNN classes (for signature helpers) and document RNNBase

### ISSUE THREAD

**Issue by hasteinmetz** [pytorch/pytorch#106085]
### 📚 The doc issue

The RNN, LSTM, and GRU classes are initialized with *args and **kwargs, despite the docstring specifying a list of possible arguments. This can be a mild annoyance for those using editors with signature helpers and may confuse users about PyTorch's implementation of RNNs.

Additionally, there is no documentation of the RNNBase class to explain its purpose in the PyTorch codebase. 

### Suggest a potential alternative/fix

Trivial changes to the [RNN.py](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/rnn.py#L449) file to specify the initialization parameters of each RNN class with appropriate type signatures. This will benefit those using editors with signature helpers.

Write a short docstring for the RNNBase class that (1) explains that it is a base implementation of all RNNs and (2) directs users to other documentation.

I'd be happy to make these changes!

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @zou3519

**Comment by mikaylagawarecki** [comment]
https://github.com/pytorch/pytorch/issues/103845 mentions the same issue, closing in favor of that
