### ISSUE TITLE
Feature Request: `resize_()` with -1 dimension

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#1060]
It seems the Tensor can be resized with -1 dimension, which is very convenient to be batch size. 

This can be done in Numpy:
```
a = np.zeros([5*4*3])
a.reshape([-1, 3])
```
with the shape `[20, 3]`

However, in PyTorch
```
a = torch.zeros([5*4*3])
a.resize_([-1, 3])
```
with the shape `None`, i.e. the data is even missing. 

Hope this feature could be added.

**Comment by soumith** [comment]
you shouldn't use resize to reshape. `.view` is for this purpose. resize is to resize the raw storage size.

```
a = torch.zeros(5*4*3)
a.view(-1, 3)
```
