### ISSUE TITLE
DISABLED test_triton_template_with_epilogues_and_dynamic_shape (__main__.TestDoBench)

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#106026]
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/inductor%2Ftest_max_autotune.py%3A%3ATestDoBench%3A%3Atest_triton_template_with_epilogues_and_dynamic_shape)).

Looks like it was introduced by https://hud.pytorch.org/pytorch/pytorch/commit/98956c5320534cb66fd0dd69bc632122e16adba9

@jataylo to look into this further

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by huydhn** [comment]
I will keep this open for now until after 2.1.1 release to keep release branch sanity.
