### ISSUE TITLE
`torch.conj()` slice assignment not working

### ISSUE THREAD

**Issue by OverLordGoldDragon** [pytorch/pytorch#106051]
### 🐛 Describe the bug

`x[:] = torch.conj(x)` doesn't work, `x[:] = torch.mean(x)` works, and `x[:].imag = -x.imag` works. Seems something's up with `storage`. Not reproduced in `torch 1.13.1`.

```python
import torch

x0 = torch.tensor([5 + 1j, 2 + 2j])
x0 = torch.conj(x0)
print(x0); print()

x1 = torch.tensor([5 + 1j, 2 + 2j])
xc1 = torch.conj(x1)
print(xc1)
x1[:] = xc1
print(x1); print()

x2 = torch.tensor([5 + 1j, 2 + 2j])
xc2 = torch.tensor([5 - 1j, 2 - 2j])
print(xc2)
x2[:] = xc2
print(x2); print()

print(xc1 == xc2)
print(xc1.storage())
print(xc2.storage())
```
```
tensor([5.-1.j, 2.-2.j])

tensor([5.-1.j, 2.-2.j])
tensor([5.+1.j, 2.+2.j])

tensor([5.-1.j, 2.-2.j])
tensor([5.-1.j, 2.-2.j])

tensor([True, True])
 (5+1j)
 (2+2j)
[torch.storage.TypedStorage(dtype=torch.complex64, device=cpu) of size 2]
 (5-1j)
 (2-2j)
[torch.storage.TypedStorage(dtype=torch.complex64, device=cpu) of size 2]
```

### Versions

<details><summary><b>wget output</b></summary>

```
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4060 Laptop GPU
Nvidia driver version: 528.66
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2100
DeviceID=CPU0
Family=198
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2100
Name=13th Gen Intel(R) Core(TM) i7-13700HX
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] numpydoc==1.5.0
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[conda] blas                      2.117                       mkl    conda-forge
[conda] blas-devel                3.9.0              17_win64_mkl    conda-forge
[conda] libblas                   3.9.0              17_win64_mkl    conda-forge
[conda] libcblas                  3.9.0              17_win64_mkl    conda-forge
[conda] liblapack                 3.9.0              17_win64_mkl    conda-forge
[conda] liblapacke                3.9.0              17_win64_mkl    conda-forge
[conda] mkl                       2022.1.0           h6a75c08_874    conda-forge
[conda] mkl-devel                 2022.1.0           h57928b3_875    conda-forge
[conda] mkl-include               2022.1.0           h6a75c08_874    conda-forge
[conda] numpy                     1.24.4          py311h0b4df5a_0    conda-forge
[conda] numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
[conda] pytorch                   2.0.1           py3.11_cuda11.8_cudnn8_0    pytorch
[conda] pytorch-cuda              11.8                 h24eeafa_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
```

</details>

It says Windows 10 but I'm on Windows 11.

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by bdhirsh** [comment]
tentatively marking hi-pri for silent correctness (although I'm not sure how common it is for people to perform interesting slices and mutations on conjugated tensors). Smaller repro:
```
>>> x[0].conj()
tensor(1.-1.j)
>>> x = torch.tensor([1 + 1j, 1 + 1j])
>>> print(x[0])
tensor(1.+1.j)
>>> print(x[0].conj())
tensor(1.-1.j)
>>> x[0] = x[0].conj()
>>> print(x[0]) # this should print (tensor1.-1.j)
tensor(1.+1.j)
```

**Comment by OverLordGoldDragon** [comment]
Thanks, this is important in signal processing and related ML.

**Comment by lezcano** [comment]
Note that, in the meantime, you can call [conj_physical](https://pytorch.org/docs/stable/generated/torch.conj_physical.html) to avoid these issues altogether.

**Comment by ezyang** [comment]
Aliasing rears its ugly head.

When you say

```
x1 = torch.tensor([5 + 1j, 2 + 2j])
xc1 = torch.conj(x1)
print(xc1)
x1[:] = xc1
print(x1); print()
```

xc1 is an alias of x1. When you say `x1[:] = xc1`, you're effectively reading from a tensor at the same time you are writing to it. Most of our kernels cannot handle this situation correctly.

You can reproduce this situation with a normal view:

```
x = torch.arange(4).view(2, 2)
xt = x.T
print(xt)
x[:] = xt
print(x)
```

where mercifully we do error

```
tensor([[0, 2],
        [1, 3]])
Traceback (most recent call last):
  File "/data/users/ezyang/d/pytorch/test.py", line 6, in <module>
    x[:] = xt
RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.
```

We need to reproduce this error for conjugates. If anyone wants to try to do this, I'm happy to advise.

**Comment by vishalj0501** [comment]
Hello 
I am a complete beginner to Contributions in PyTorch.
Can I try this?

**Comment by OverLordGoldDragon** [comment]
I reproduced the ezyang's `view` example in `torch 1.13.1`, while `conj` still works properly. 

If Pytorch 2 has this issue with lazy evaluation, it may be better make `conj` -> `conj_physical` and have `conj` become `conj_lazy`, since this is very unintuitive behavior, especially since Pytorch 1 worked otherwise, and it deviates from NumPy.

Some additional debug info:

```python
x = torch.tensor([1 + 1j])
xc = torch.conj(x)
xc[:] = torch.resolve_conj(xc)
print(xc)
print(x)
```
```
tensor([1.-1.j])
tensor([1.+1.j])
```

```python
x = torch.tensor([1 + 1j])
xc = torch.conj(x)
xc[:] = torch.conj_physical(xc)
print(xc)
print(x)
```
```
tensor([1.+1.j])
tensor([1.-1.j])
```

**Comment by ezyang** [comment]
We had a pretty detailed conversation about this when complex was introduced, and the problem is that lazy conjugation is really really important for writing "natural" complex code. Though... this predates torch.compile. I'm more sympathetic to changing it to physically conjugate now that we have compilation... when it supports complex lol

**Comment by ezyang** [comment]
But also, I doubt it's a big deal if we error in this case. @vishalj0501 to get started, find where the analogous error is reported in C++, and then figure out where to replicate this error check for the conj path.

**Comment by vishalj0501** [comment]
@ezyang I'm not able to figure it out, I'm finding the codebase overwhelming, Ig I might need a little bit of hand holding.
Sorry

**Comment by znb899** [comment]
Hello
Can I try this with you @vishalj0501 ?

**Comment by FFFrog** [comment]
@ezyang , Sorry to bother you。

The difference between main and v1.13.1 mainly lies in the fast path of copy. There is not much difference in other aspects. Both support lazy conj.

I have a question, and apologies if anyone has asked a similar question before.

Take v1.13.1 as an example

```Python
>>> import torch
>>> x = torch.tensor([[5 + 1j, 2 + 2j], [4 + 1j, 9 + 4j]])
>>> xc = x.conj()
>>> x
tensor([[5.+1.j, 2.+2.j],
        [4.+1.j, 9.+4.j]])
>>> xc
tensor([[5.-1.j, 2.-2.j],
        [4.-1.j, 9.-4.j]])
>>> y = torch.tensor([[2 + 2j, 3 + 1j], [7 + 1j, 2 - 6j]])
>>> y
tensor([[2.+2.j, 3.+1.j],
        [7.+1.j, 2.-6.j]])
>>> x[:] = y
>>> x
tensor([[2.+2.j, 3.+1.j],
        [7.+1.j, 2.-6.j]])
>>> xc
tensor([[2.-2.j, 3.-1.j],
        [7.-1.j, 2.+6.j]])
```

When we change the value of `x`, `xc` will also be changed. Is this the expected result?

For `x`, since the conjugate bit is not stored in the storage, it cannot be sensed whether other conjugate complex tensors share the storage, so it cannot be cloned in advance.

**Comment by ezyang** [comment]
It's the fast path code, patch is very simple, coming.
