### ISSUE TITLE
"Graph break: inline in skipfiles:" is a bad message

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#106050]
### 🐛 Describe the bug

TORCH_LOGS=graph_breaks should produce user-understandable logs, but a log like `Graph break: inline in skipfiles: LazyGetItemMixin.__getitem__  | __getitem__ ` is completely impenetrable to any standard user. Need more info.

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @wconstab @Xia-Weiwen @ipiszy

**Comment by anijain2305** [comment]
cc @yanboliang if his tracing work already supports this.

**Comment by yanboliang** [comment]
Yes, I'll enhance the skip/inline loggings in my upcoming PRs.
