### ISSUE TITLE
[ONNX] Reduce 'onnxfunction_dispatcher' warnings on nearest match

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#106057]
[Sample diagnostics](https://microsoft-my.sharepoint.com/:u:/p/bowbao/ERcSZ8HpsW5Cp9yw6YbEgkQBxjgIGkg1jU0zwGkYwY8C7g?e=JYvuDp) produced from exporting `xcit_large_24_p8_224`.

Initial triage of warning types:

- [x] Potential incorrect fallback. E.g. `aten.div.Tensor_Mode`.
- [ ] Optional input. E.g., `bias` input of `aten.convolution.default`. -> Optional[INPUT] is not supported in matching. 
- [ ] Attribute dtype mismatch. E.g., `alpha` of `aten.add.Tensor`. -> Attribute: `alpha` INT vs FLOAT
- [x] Sequence type input. E.g., `self` input of `aten.getitem`. -> **Empty inputs (This is expected warning.)**
- [ ] Attribute set mismatch. E.g., `aten_linalg_vector_norm`. -> dtype is not provided by ATen (dtype=-1)
- [ ] aten.clone.default. -> memory_format is missing.  
...

**Comment by titaiwangms** [comment]
`aten.getitem` doesn't seem like an issue though, as it's just not providing the right inputs/attributes as opschema expected. And `aten.div.Tensor_Mode` I think it's a bug of spliting "_". I will check it.
