### ISSUE TITLE
MPS cumprod gradient is broken even when using cpu fallback on macos 13.2.1

### ISSUE THREAD

**Issue by Mr4k** [pytorch/pytorch#106112]
### 🐛 Describe the bug

While working on #104688 (which enables support for mps accelerated cumprod), I noticed that the gradient test of cumprod (`test_output_grad_match_cumprod_cpu_float32`) was failing only on the task [macos-12-py3-arm64-mps](https://github.com/pytorch/pytorch/actions/runs/5658964066/job/15332115951?pr=104688#logs). This task counter intuitively seems to use macos version 13.2.1 (see the Print Runner OS/HW Info section in the job). 

Originally I assumed this was my mistake or a bug with the mps cumprod op on 13.2.1 However I tried a version of the pr where I fell back to the cpu for cumprod instead of using the mps operation and noticed the issue was still there. However the problem could have still been in my code and I did not have a computer with mac os 13.2.1 to easily test on. So I created a [test pr](https://github.com/pytorch/pytorch/pull/106096) which changes none of the core pytorch code from main but runs the failing test `test_output_grad_match_cumprod_cpu_float32`with `PYTORCH_ENABLE_MPS_FALLBACK` enabled. 

You can see for yourself by looking at the results of the macos-12-py3-arm64-mps job on that pr that `test_output_grad_match_cumprod_cpu_float32` is failing with the exact same error despite none of the actually pytorch code changing. This confirms that the error is not in the code for #104688 but somewhere else in the gradient code for cumprod on mps. The gradient of cumprod uses [a bunch of different ops besides cumprod](https://github.com/pytorch/pytorch/blob/6f1042c0496731694635f559b9ae48a0d79d9099/aten/src/ATen/native/ReduceOps.cpp#L629) when not creating a graph so the problem could be in the mps versions of any of those.

If you have access to a mac with version 13.2.1 then reproing should be as easy as:
```
PYTORCH_ENABLE_MPS_FALLBACK=1 pytest test/test_mps.py -k test_output_grad_match_cumprod_cpu_float32 
```

Unfortunately I cannot fix this bug as I do not have access to the operating system it's breaking on except through the CI.

### Versions

In this particular case I don't think this makes sense because I repro'ed this error via the CI not on my computer. Since I cannot run `python collect_env.py` on the CI machine I cannot report much info.
```
machdep.cpu.brand_string: Apple M1
kern.osproductversion: 13.2.1
```

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by hvaara** [comment]
Ref #125318

@pytorchbot close
