### ISSUE TITLE
Installed caffe2 through conda install, but imdb is disabled

### ISSUE THREAD

**Issue by hangwudy** [pytorch/pytorch#10618]
I installed the caffe2 through the anaconda3
`conda install -c caffe2 caffe2-cuda9.0-cudnn7`

Everything is fine but the lmdb.
When I try the caffe2 tutorial CIFAR10_Part1, I met the problem:

`RuntimeError: [enforce fail at db.h:190] db_. Cannot open db: .....`
I read the forums and find that's because lmdb is not turned on by compiling.
But I just used the conda install.
So I try to turn on the lmdb and compile the source with the command 

`./build_anaconda.sh --cuda 9.0 --cudnn 7 --install-locally -DCUDA_HOST_COMPILER=/usr/bin/gcc-5
`

But I got the Error likes following:
```
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:63: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o] Error 1
CMakeFiles/Makefile2:1440: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```
How could I solve the problem? Thanks!

## System Info

- Caffe2
- How you installed Caffe2 (conda, pip, source): conda
- Build command you used (if compiling from source): `./build_anaconda.sh --cuda 9.0 --cudnn 7 --install-locally -DCUDA_HOST_COMPILER=/usr/bin/gcc-5`
- OS: Ubuntu 18.04
- Python version: 2.7
- CUDA/cuDNN version: 9.0
- GPU models and configuration: 1070
- GCC version (if compiling from source): 6

**Comment by pjh5** [comment]
That build command does not turn on lmdb. You will also have to pass -DUSE_LMDB=ON and also add lmdb to the conda dependencies https://github.com/pytorch/pytorch/blob/master/conda/caffe2/meta.yaml#L19 . lmdb is turned off by default b/c the dependency resolution of conda can sometimes pick a lmdb that leads to issues.

**Comment by hangwudy** [comment]
@pjh5 Thanks very much for your explanation. 
Could you tell me how to pass -DUSE_LMDB=ON when I try to install pre-built binaries with conda command `conda install -c caffe2 caffe2-cuda9.0-cudnn7` ?

**Comment by pjh5** [comment]
@hangwudy commands like -DUSE_FOO affect how the libraries are built. When installing the pre-built binaries all the code has already been built, so at this time no new features such as lmdb or leveldb or anything else can be added. It is impossible to pass any sort of build commands into a 'conda install' and have an effect. The pre-built binaries come with the most common 'default' configeration, but to get other functionality (such as lmdb) you will need to build from source.

Also, note that the package is now
conda install -c pytorch pytorch-nightly
