### ISSUE TITLE
FSDP multi node training fails to overlap forward allgather and backward reduce scatter with compute

### ISSUE THREAD

**Issue by hanzhi713** [pytorch/pytorch#106177]
### 🐛 Describe the bug

Single node training gives the correct overlap. Multinode does not and have the following trace. 

![image](https://github.com/pytorch/pytorch/assets/21034047/b7912e4d-a7ef-4c1b-abd5-8bd14df84a69)

The reproducing code is here: https://github.com/hanzhi713/FSDP_llama_repro

### Versions

torch nightly 2.1.0.dev20230727+cu121

All nodes have 8x NVIDIA A100-SXM4-80GB. Single node has driver version: 530.30.02, multi-node training uses 16 nodes and uses driver 450.191.01 with cuda 12.1 compat library installed. 

Let me know if you can or can't reproduce the problem. cc @zhaojuanmao @mrshenli @rohan-varma @awgu @fegin

**Comment by awgu** [comment]
Could you send me the trace?

**Comment by hanzhi713** [comment]
Here is the trace for a single worker (just a randomly picked worker). [trace.tar.gz](https://github.com/pytorch/pytorch/files/12188965/trace.tar.gz)

**Comment by awgu** [comment]
Your trace unfortunately does not have the flow arrows for collectives (something broke), so it is a bit tedious to analyze. What is interesting to me is that there is no overlap for the all-gathers in forward either, so maybe it is not only related to the backward prefetching.

Could you share the single-node trace? (I just want to take a look at the traces first without setting up the repro since I need to get the compute resources then.)

**Comment by hanzhi713** [comment]
Here's the trace from a single node training. [single_node.tar.gz](https://github.com/pytorch/pytorch/files/12197676/single_node.tar.gz)

Due to someone else using GPU 0, this trial runs on GPU 1-7 only (so 7 GPUs instead of 8). I don't think this will make any difference though.

**Comment by hanzhi713** [comment]
> Your trace unfortunately does not have the flow arrows for collectives (something broke), so it is a bit tedious to analyze. What is interesting to me is that there is no overlap for the all-gathers in forward either, so maybe it is not only related to the backward prefetching.
> 
> Could you share the single-node trace? (I just want to take a look at the traces first without setting up the repro since I need to get the compute resources then.)

I also noticed myself that the arrows are missing for collectives. Maybe this have something to do with something being "INVALID" in the trace

![image](https://github.com/pytorch/pytorch/assets/21034047/346dd270-eb94-43a5-9edb-2a51803f7cd5)

**Comment by hanzhi713** [comment]
I just confirmed that the difference in behavior between single-node and multi-node training is **not** caused by the difference in environment/driver version. I managed to run single node training using the exactly the same docker image and host nvidia driver version as the multi-node case, and results are the same. That is, under identical environment settings, single node training gives the correct computation/communication overlap behavior while multi-node training doesn't.

**Comment by hanzhi713** [comment]
I figure out the problem. The person who wrote the launch script for multi-node dispatch set the environment variable `CUDA_DEVICE_MAX_CONNECTIONS=1` in that script. I don't know why, but I guess things like that do happen.

**Comment by hanzhi713** [comment]
The problem resolved after I unset `CUDA_DEVICE_MAX_CONNECTIONS`. If you've spent a lot of time on this, I'm really sorry.

**Comment by awgu** [comment]
No worries! I am glad you were able to resolve it!
