### ISSUE TITLE
Feature: a simple text logger for pytorch

### ISSUE THREAD

**Issue by sjiang95** [pytorch/pytorch#106288]
### 🚀 The feature, motivation and pitch

Pytorch provides comprehensive loggers such as [torch.utils.tensorboard](https://pytorch.org/docs/stable/tensorboard.html) and [torchtnt loggers](https://pytorch.org/tnt/stable/utils/loggers.html#module-torchtnt.utils.loggers). But there are too complicated for the cases that the user only wants to check a text training message such as

```bash
The training started at YYYY/MM/DD HH/MM/SS
...
The statedict of epoch 36 has been saved to /some/path
...
The training finished at YYYY/MM/DD HH/MM/SS
```

Besides, it seems that the torchtnt loggers poorly support text message logs.

Write the text messages to text log file via a text logger is the most simple and direct way to solve this.

Is there a text logger that could handle all console outputs? This is necessary for the training process traceback.

### Alternatives

I indeed have found a solution: the mmcv's logger https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/logging.py.

This logger can be easily integrated to the existing projects by

```python
import os
from datetime import datetime

import torch
print(f"{torch.__version__=}")
import torch.distributed as dist
import torch.multiprocessing as mp

from utils.logging import get_logger
from prettytable import PrettyTable

work_dir=os.path.join("work_dirs", "logs")
os.makedirs(work_dir, exist_ok=True)

def worker(rank:int, worldsize:int):
    start_time = datetime.now()
    print(f"{start_time.strftime('%Y/%m/%d %H:%M:%S.%f')}: Training started.")
    logfilename = os.path.join(
            work_dir, f"mmcv{start_time.strftime('%Y%m%d_%H%M%S.%f')}.log")
    dist.init_process_group(backend="gloo", init_method="tcp://localhost:12345", world_size=worldsize, rank=rank)
    getrank=dist.get_rank()
    logger=get_logger(name="mmcvlog", log_file=logfilename)
    for i in range(10):
        logger.info(f"[rank {getrank}] msg from step {i}")
    tb=PrettyTable(field_names=["key", "value"])
    tb.add_rows([["lr", "1e-4"],
                 ["epochs", "100"]])
    logger.info(f"\n{tb}")
    logger.warning("This is a warning msg")
    logger.error("This is an error msg")
    logger.info(f"[rank {getrank}] exit")

if __name__=="__main__":
    worldS=2
    mp.spawn(worker, args=(worldS,), nprocs=worldS)
```

This logger has the following advantanges:
- it prints to text log file and console with a formatted string of `%(asctime)s - %(name)s - %(levelname)s - %(message)s`
- it is compatible with torch.multiprocessing. Only rank0 prints messages.

For example
	
```bash
2023-07-31 11:02:24,909 - mmcvlog - INFO - [rank 0] msg from step 0
2023-07-31 11:02:24,914 - mmcvlog - INFO - [rank 0] msg from step 1
2023-07-31 11:02:24,917 - mmcvlog - INFO - [rank 0] msg from step 2
2023-07-31 11:02:24,921 - mmcvlog - INFO - [rank 0] msg from step 3
2023-07-31 11:02:24,922 - mmcvlog - INFO - [rank 0] msg from step 4
2023-07-31 11:02:24,931 - mmcvlog - INFO - [rank 0] msg from step 5
2023-07-31 11:02:24,933 - mmcvlog - INFO - [rank 0] msg from step 6
2023-07-31 11:02:24,935 - mmcvlog - INFO - [rank 0] msg from step 7
2023-07-31 11:02:24,937 - mmcvlog - INFO - [rank 0] msg from step 8
2023-07-31 11:02:24,939 - mmcvlog - INFO - [rank 0] msg from step 9
2023-07-31 11:02:24,951 - mmcvlog - INFO - 
+--------+-------+
|  key   | value |
+--------+-------+
|   lr   |  1e-4 |
| epochs |  100  |
+--------+-------+
2023-07-31 11:02:24,953 - mmcvlog - WARNING - This is a warning msg
2023-07-31 11:02:24,956 - mmcvlog - ERROR - This is an error msg
2023-07-31 11:02:24,957 - mmcvlog - INFO - [rank 0] exit
```

### Additional context

I wish to discuss the possibility of integrating this logger to pytorch as, for example, `torch.utils.textlogger`.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @albanD

**Comment by albanD** [comment]
cc @mlazos @vfdev-5

**Comment by vfdev-5** [comment]
@sjiang95 as you mentioned torchtnt in the issue description, I can also suggest as another alternative ignite's `setup_logger` : https://pytorch.org/ignite/utils.html#ignite.utils.setup_logger (possible to configure the formatting and it also supports DDP).

**Comment by sjiang95** [comment]
@vfdev-5 @albanD thank you. I have tested the `ignite.utils.setup_logger` and this is exactly what I want.
