### ISSUE TITLE
dynamo struggles with list of tensor elements

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#106207]
### 🐛 Describe the bug

```python
def fn():
    x = torch.tensor([1, 2, 3, 4, 5, 6], dtype=torch.int64)
    y = [x[0], x[2], x[4]]
    return torch.LongTensor(y)
```

fails to compile throwing a
```
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <class 'torch.LongTensor'>(*([FakeTensor
(..., size=(), dtype=torch.int64), FakeTensor(..., size=(), dtype=torch.int64), FakeTensor(..., size=(), d
type=torch.int64)],), **{}):
The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy alloca
tion, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
```

Same same if we use a `torch.as_tensor` in place of the `LongTensor` call. It actually passes if we change it by a `torch.tensor`.

### Versions

master

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

**Comment by andrzeng** [comment]
Hi, I wish to work on this issue.  However this is my first PyTorch issue and I have a question about the _TorchDynamoContext.__call__() function in eval_frames.py. What is the purpose of each line in 
`on_enter()
            prior = set_eval_frame(callback)
            backend_ctx = backend_ctx_ctor()
            backend_ctx.__enter__()
            dynamic_ctx = enable_dynamic(self.dynamic)
            dynamic_ctx.__enter__()`?

Thank you very much
