### ISSUE TITLE
Use torch.device() with torch.load(..., map_location=torch.device())

### ISSUE THREAD

**Issue by PavelTemirchev** [pytorch/pytorch#10622]
It will be useful to allow map_location to be an instance of torch.device for transferability.
By now attempt to do so gives an error:
TypeError: 'torch.Device' object is not callable

**Comment by SsnL** [comment]
Hi this has been possible since 0.4. Maybe you are getting error because `torch.device` constructor expects arguments so you can't call as `torch.device()`.

**Comment by PavelTemirchev** [comment]
Are you sure?
Here a small example leading to the error.
What I'm doing wrong?

>>> import torch
>>> torch.__version__
'0.4.0'
>>> a = torch.zeros(1)
>>> torch.save(a, 'file')
>>> a = torch.load('file', map_location='cpu')
>>> a
tensor([ 0.])
>>> a = torch.load('file', map_location=torch.device('cpu'))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-1a71c81826ea> in <module>()
      3 a = torch.load('file', map_location='cpu')
      4 a
----> 5 a = torch.load('file', map_location=torch.device('cpu'))

~/anaconda3/lib/python3.6/site-packages/torch/serialization.py in load(f, map_location, pickle_module)
    301         f = open(f, 'rb')
    302     try:
--> 303         return _load(f, map_location, pickle_module)
    304     finally:
    305         if new_fd:

~/anaconda3/lib/python3.6/site-packages/torch/serialization.py in _load(f, map_location, pickle_module)
    467     unpickler = pickle_module.Unpickler(f)
    468     unpickler.persistent_load = persistent_load
--> 469     result = unpickler.load()
    470 
    471     deserialized_storage_keys = pickle_module.load(f)

~/anaconda3/lib/python3.6/site-packages/torch/serialization.py in persistent_load(saved_id)
    435             if root_key not in deserialized_objects:
    436                 deserialized_objects[root_key] = restore_location(
--> 437                     data_type(size), location)
    438             storage = deserialized_objects[root_key]
    439             if view_metadata is not None:

~/anaconda3/lib/python3.6/site-packages/torch/serialization.py in restore_location(storage, location)
    321     else:
    322         def restore_location(storage, location):
--> 323             result = map_location(storage, location)
    324             if result is None:
    325                 result = default_restore_location(storage, location)

TypeError: 'torch.Device' object is not callable

**Comment by SelvamArul** [comment]
@PavelTemirchev I had the same issue but upgrading torch to version `0.4.1` solved this.

**Comment by HaleTom** [comment]
This seems to be a duplicate of #17.

**Comment by cooleel** [comment]
Nice. met the same issue with torch 0.4, and solved with the solution provided here.
Thanks all.
