### ISSUE TITLE
Feature request: timeline for network transfers 

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#10628]
My network wall-clock time overhead for PyTorch DDP 3x more than expected on AWS. To troubleshoot it would be useful to get something like [Horovod Timeline](https://github.com/uber/horovod/blob/master/docs/timeline.md) . IE, a way to see timeline of all network transfers, their times and their sizes during a step.

**Comment by teng-li** [comment]
@yaroslavvb  I believe you and I synced offline on this, I do believe NVVP has already had this support and we don't have any immediate plan on supporting this

**Comment by teng-li** [comment]
Resolved offline
