### ISSUE TITLE
collecting torch2.0.1+CU117 

### ISSUE THREAD

**Issue by noobsorry23** [pytorch/pytorch#106236]
### 🐛 Describe the bug

hello, I can't install oobabooga text-generation-webui. I don't know what to do. Someone can help me ?

### Versions

![Capture](https://github.com/pytorch/pytorch/assets/140857922/548ac0a6-6a07-497d-94bf-0001d21af6ea)

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by malfet** [comment]
Please use https://discuss.pytorch.org/ to ask generic question about PyTorch usage and github issue to report an unexpected behaviour in PyTorch. 

So closing this one, but don't hesitate to open a new issue if you run into a problem with the framework

P.S. You've missed the most import part (which is at the bottom of stack trace) in your screenshot. Also, better copy-n-paste text verbatim, as screenshots are harder to read/parse for error messages)
