### ISSUE TITLE
torch DDP oom caused by weak protocol

### ISSUE THREAD

**Issue by leiwen83** [pytorch/pytorch#106294]
### 🐛 Describe the bug

Current torch DDP distributed trainiing protocol is weak, that it use simple tcp protocol listening over master port to choose action to exectue. While it is efficient, but it may cause issue when abonormal network traffic comes.

Here we met an OOM issue, which cause machine quickly run out cpu memory. And we root cause this issue to be torch DDP mistake nmap scan message as addHandler message, and create a very large mmaped pool hold to prepare the incoming message.

Process to reproduce DDP OOM:
```
nmap -p[master port] -sS -sV [torch DDP master node IP]
```

The trigger trace is as:
```
https://github.com/pytorch/pytorch/blob/v2.0.1/torch/csrc/distributed/c10d/TCPStore.cpp#L588
-> https://github.com/pytorch/pytorch/blob/v2.0.1/torch/csrc/distributed/c10d/TCPStore.cpp#L281
-> https://github.com/pytorch/pytorch/blob/v2.0.1/torch/csrc/distributed/c10d/TCPStore.cpp#L384
-> https://github.com/pytorch/pytorch/blob/v2.0.1/torch/csrc/distributed/c10d/Utils.hpp#L659

inline std::string recvString(int socket) {
  SizeType valueSize;
  recvBytes<SizeType>(socket, &valueSize, 1);
  std::vector<char> value(valueSize);
  recvBytes<char>(socket, value.data(), value.size());
  return std::string(value.data(), value.size());
}
```
@recvString, it would parse nmap message into a very large mesage to recv, more than 1T, which lead torch to request 1T+ memory to system, leading to OOM.

It is very common to use nmap to scan port in data center, so shall we consider to make torch DDP protocol more robust to such kind of "attack"? I think only add some magic number would greatly reduce such issue.

Thx

### Versions

Seems to me, since DDP is supported, this issue is existed.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

**Comment by wconstab** [comment]
@kumpera Wdyt about modifying our send/recv functions to use a magic number?

Any concern about increased latency from this?

Any concern about BC issues when implementing this change?  (i'm assuming that the same version of pytorch would always be used on all ranks, so this should be safe to ignore)

**Comment by juncgu** [comment]
> @kumpera Wdyt about modifying our send/recv functions to use a magic number? Probably best to put the change in send/recvBytes so its applies everywhere. I'm not sure if it's worth the change though. Do we need DDP to be robust to nmap attacks?
> 
> Any concern about increased latency from this?
> 
> Any concern about BC issues when implementing this change? (i'm assuming that the same version of pytorch would always be used on all ranks, so this should be safe to ignore)

Hi @wconstab, we tried to add a magic number to TCPStore queries (https://github.com/pytorch/pytorch/pull/107607). It can filter out the invalid messages coming from nmap and prevents the relative DDP OOM issue. Also, it is lightweight than applying in send/recvBytes.

Best,
Juncheng

**Comment by wenjianhn** [comment]
We perform regular scans of the entire data center using nmap, but this often causes PyTorch DDP to run out of memory. 

I think it's a good start to add the magic number, as supporting authentication for RPC can be tricky. 
This issue provides more information: https://github.com/pytorch/pytorch/issues/46904. 
cc @lw
