### ISSUE TITLE
Slow test has been broken since Jul 26th

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#106307]
### 🐛 Describe the bug

Last successful commit: https://hud.pytorch.org/pytorch/pytorch/commit/dc19f8a6b5d051cd01a1fad6bfadb898ba466f6e
First broken commit: https://hud.pytorch.org/pytorch/pytorch/commit/4137d6e4997f76304f478bf56f7296e9bae46fbd

Signatures are different but here are some patterns:
 - Gradcheck tests timeout: see [this](https://github.com/pytorch/pytorch/actions/runs/5705273352/job/15460184303) for example
 - Foreach tests are flaky: file https://github.com/pytorch/pytorch/issues/106303
 - Distributed test violate some sort of usage assert: https://github.com/pytorch/pytorch/issues/106305

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Adding triage review to decide what to do about those: disable or file a high-pri issue for fwd fixes

**Comment by atalman** [comment]
we investigated issue second issue with @DanilBaibak 
- Foreach tests are flaky: file https://github.com/pytorch/pytorch/issues/106303 

culprit PR was identified and reverted: https://github.com/pytorch/pytorch/pull/106043

**Comment by DanilBaibak** [comment]
The culprit PR was successfully reverted - #106043
Slow tests are completely green - https://hud.pytorch.org/pytorch/pytorch/commit/2b427ae3a7e2a948879876a135bbbad51ea93d63
