### ISSUE TITLE
NaNs in ouput of Conv3d

### ISSUE THREAD

**Issue by yakovdan** [pytorch/pytorch#106332]
### 🐛 Describe the bug

Hi, 
The output of a Conv3d layer contains NaN values. 
The input has no NaN values nor do the weights of the layer. No bias is used. 

This happens rarely, but consistently: given the same input and  weights, there are NaN values in the output every time. 
I can provide the input and weights if needed. 

Thanks!

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230720+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.19.0-50-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
CPU family:                      6
Model:                           158
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        10
CPU max MHz:                     4600.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6399.96
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        1.5 MiB (6 instances)
L3 cache:                        12 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.7.10
[pip3] flake8-comprehensions==3.14.0
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.1
[pip3] pytorch-ignite==0.4.11
[pip3] pytorch-triton==2.1.0+9e3e10c5ed
[pip3] torch==2.1.0.dev20230720+cu121
[pip3] torchaudio==2.1.0.dev20230720+cu121
[pip3] torchvision==0.16.0.dev20230720+cu121
[conda] numpy                     1.25.1                   pypi_0    pypi
[conda] pytorch-ignite            0.4.11                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+9e3e10c5ed          pypi_0    pypi
[conda] torch                     2.1.0.dev20230720+cu121          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230720+cu121          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230720+cu121          pypi_0    pypi

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Hi @yakovdan, thanks for the issue. Could you provide a minimal repro of this please?

**Comment by yakovdan** [comment]
@mikaylagawarecki 
A particular combination of input tensor and weights are needed. Can I provide links to my google drive?
```
import torch
input_tensor = torch.load('conv3dtestinput.pt').to('cpu')
conv_layer = torch.load('conv3dtest.pt').to('cpu')
output = conv_layer(input_tensor)
print(output.isnan().any()) # Expected False, got True. 
```

**Comment by yakovdan** [comment]
@mikaylagawarecki 
attached are links to the files mentioned in the repro script above
[conv3dtest.pt](https://drive.google.com/file/d/1hgMPFHPD_4OIyDP4hFlh2e1eM0oiRSyc/view?usp=drive_link)
[conv3dtestinput.pt](https://drive.google.com/file/d/1mRCOV6zjyq9odxmt0IRIgHzVGA9A92QU/view?usp=drive_link)

**Comment by mingfeima** [comment]
@yanbing-j could you please help debug this one ?

**Comment by ZhaoqiongZ** [comment]
Hi @yakovdan , thanks for your report! I try to reproduce with your input test tensor, and I've send request to download the conv3dtestinput.pt and conv3dtest.pt, Could you please help approve the request?  My google account is isabellezheng for your reference.

**Comment by yanbing-j** [comment]
> @yanbing-j could you please help debug this one ?

Sure.

**Comment by yakovdan** [comment]
@ZhaoqiongZ Sure, access granted. Thank you!

**Comment by ZhaoqiongZ** [comment]
Hi @yanbing-j , I can reproduce this issue on Xeon.

**Comment by yakovdan** [comment]
Please note that the same bug with the same data happens on an RTX 4090 with CUDA as well.

**Comment by yanbing-j** [comment]
Please note that, without mkldnn enabled, slow_conv3d has the same bug as well.

**Comment by yakovdan** [comment]
@yanbing-j 
I've tried the same experiment as your first point and got the same result.
Regarding sizes, I do not have a smaller input to reproduce. I've never seen this appear in my code with smaller tensors. 
Regarding very small or very large values, I'll have to check and get back to you.
Perhaps you can pick a particular NaN value in the output tensor the trace the calculation that produces it? You can prune the input tensor to remove values that do not participate.

**Comment by yanbing-j** [comment]
@ZhaoqiongZ , could you please help verify this issue in CUDA? If this can reproduce in CUDA, then it is not a CPU only issue.

**Comment by yakovdan** [comment]
@yanbing-j @ZhaoqiongZ 
Ok, so I checked for very small and very large values in the input tensor and sure enough, the input tensor contains an inf. 
This was caused by an overflow when using mixed precision training. I apologize for having missed this. I suggest we close the issue if it's alright with you.

**Comment by ZhaoqiongZ** [comment]
Hi @yakovdan , sure, no problem, please close this issue!

**Comment by yanbing-j** [comment]
Hi @yakovdan , thanks for the confirmation. Then we need to check both `isnan` and `isinf` next time.
