### ISSUE TITLE
DISABLED slow / linux-bionic-cuda12.1-py3.10-gcc9-sm86 / test (slow, 2, 2, linux.g5.4xlarge.nvidia.gpu) 

### ISSUE THREAD

**Issue by DanilBaibak** [pytorch/pytorch#106306]
## Reason
PR #105206 broke one of the slow test "test_testing.py::TestTestingCUDA::test_cuda_assert_should_not_stop_common_distributed_test_suite_cuda"

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Err, why disable the entire workflow, when one can disable a single test (as done in https://github.com/pytorch/pytorch/issues/106305 )
