### ISSUE TITLE
[torch.compile] autograd.Function with multiple return values

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#106389]
### 🐛 Describe the bug

```
import torch
import torch._dynamo

class Foo(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        ctx.save_for_backward(x)
        return x.sin(), x.sin()
    @staticmethod
    def backward(ctx, grad0, grad1):
        x, = ctx.saved_tensors
        return grad * x.cos(), grad * x.cos()

@torch.compile(backend='aot_eager', fullgraph=True)
def f(x):
    return Foo.apply(x)

x = torch.randn([], requires_grad=True)
f(x)
```
produces:
```
le.call_function(self, tx, args, kwargs)
    771     return None
    773 p_args = (
    774     *(arg.as_proxy() for arg in args),
    775     *(arg for arg in body_lifted_freevars.keys()),
    776 )
--> 777 r = body_r.as_proxy().node.meta["example_value"]
    778 example_value = r
    780 _, p_kwargs = proxy_args_kwargs([], kwargs)

InternalTorchDynamoError: 'tuple' object has no attribute 'node'

```

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

**Comment by voznesenskym** [comment]
Half hearted attempt - https://github.com/pytorch/pytorch/pull/105103/files should be an easy fix to pick up.

**Comment by zou3519** [comment]
Sorry, I haven't reviewed this yet because it is kind of complicated and there are some open design questions

@ysiraichi if you have extra cycles, I would recommend tackling https://github.com/pytorch/pytorch/issues/107315 before this, since having the right design for pytrees could simplify our life here

**Comment by zou3519** [comment]
Quick brain dump:

Concretely, there are two problems here:
- speculate_subgraph with nested collection of Tensor inputs
- speculate_subgraph with nested collection of Tensor outputs

The ideal end goal for both of these is that the body_fn should look like it has flat inputs and flat outputs. This is not the case today (if we use torch._higher_order_ops.wrap on a function that returns a collection of Tensors, then it returns the collection as-is). To get to this state, we are going to need to do some finagle-ing of the inputs and outputs.

Now, open question about if this is a good end goal or not. Would any HigherOrderOps prefer that we do not flatten the inputs and outputs?

**Comment by ysiraichi** [comment]
I am not that familiar with `HigherOrderOps`, but there were two test cases that caught my attention:
- `test_grad_pytree`
- `test_vmap_pytree_inputs`

```python
def test_grad_pytree(self):
    ...
    def fn(x):
        x1, x2 = x
        return x1.sin().sum() + x2

    def wrapper_fn(x):
        return torch.func.grad(fn)(x)

    expected = torch.compile(wrapper_fn, backend="aot_eager", fullgraph=False)((x1, x2))
```

For consistency, I'd assume the tuple argument remains as a tuple. On the other hand, I'd argue that we should flatten the output of the forward so as to match a flattened backwards input.

Again, I'm not really familiar with `HigherOrderOps`, so I probably don't have the whole picture, here.
