### ISSUE TITLE
Symbolic size not traced for some NumPy tensors

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#106376]
### 🐛 Describe the bug

To reproduce, checkout https://github.com/pytorch/pytorch/pull/106211.

The following program has two issues

```python
import torch
import numpy as np


def _inf_nan_preprocess(t, t_np):
    t_np = np.nan_to_num(t_np)
    return t, t_np


@torch.compile
def fn():
    # shape, dims format
    test_cases = (
        (3, 3),
        (4, 4),
        (5, 5),
    )

    for shape in test_cases:
        t = torch.randn(shape, dtype=torch.complex64)
        t_np = np.random.randn(*shape).astype(np.complex64)

        _, t_np = _inf_nan_preprocess(t, t_np)
        print(t, t_np)  # Just a side effect so that compilation kicks in


fn()
```

1. It errors out in the third case, as it tries to execute the `(4, 4)` case and it fails
2. If not tensor `t` is passed to `_inf_nan_preprocess`, no compilation happens

The error it throws is:
```
  File "/tmp/torchinductor_lezcano/2o/c2o5vzmhd5js5f2vjs55rwqi4qnrzma5ib24xporljfnq6tc2nx6.py", line 83, in call
    assert_size_stride(arg0_1, (4, 4), (4, 1))
AssertionError: expected size 5==4, stride 5==4 at dim=0
```

I believe that point 1 is caused by these issues:
- No guards are installed for `t_np` in `_inf_nan_preprocess`. We just find guards for `t`.
- The shape `(4, 4)` of `t_np` is baked into the AOT graph.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov @ysiraichi @larryliu0820 

### Versions

https://github.com/pytorch/pytorch/pull/106211

**Comment by voznesenskym** [comment]
Discussed offline, will look @lezcano

**Comment by larryliu0820** [comment]
@voznesenskym let me know if I can help! Love to learn more about sym size.

**Comment by lezcano** [comment]
This was fixed by adding sources to numpy tensors (I think that's what fixed this)
