### ISSUE TITLE
DISABLED test_cat_addmm (__main__.TestDoBench)

### ISSUE THREAD

**Issue by jataylo** [pytorch/pytorch#106451]
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/inductor%2Ftest_max_autotune.py%3A%3ATestDoBench%3A%3Atest_cat_addmm)).

Same issue as https://github.com/pytorch/pytorch/issues/106026, still investigating root cause. Currently seems like the triton template tests will fail on ROCm GPUs upstream due to lower number of SMs to return True in https://github.com/pytorch/pytorch/blob/main/torch/_inductor/utils.py#L655

cc: @jithunnair-amd 

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang

**Comment by huydhn** [comment]
I can still see this is failing in ROCm trunk https://hud.pytorch.org/pytorch/pytorch/commit/2dc37f4f70076c0390e9787c6a941aab926c5bea.  I wonder if the reason is that ROCm is now not part of viable/strict update anymore. cc @clee2000

**Comment by jataylo** [comment]
@huydhn Strange... this PR https://github.com/pytorch/pytorch/pull/111467 should have stopped this test running on current ROCm runners.

**Comment by huydhn** [comment]
Reopen this issue until we finish 2.1.1 branch cut.  An AI here is to figure out how to handled resolved disabled issues in release branch, which might not have the fix in main
