### ISSUE TITLE
Tensor changed after switching device 

### ISSUE THREAD

**Issue by ranchlai** [pytorch/pytorch#106474]
### 🐛 Describe the bug

Tensor changed after switching device: 

```python
import torch
a = torch.tensor([1])
a = a.to("cuda:0")
print(a.to("cuda:1"))
>> tensor([0], device='cuda:1')
```

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.27.0
Libc version: glibc-2.27

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.90.1.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.0.221
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090

Nvidia driver version: 525.60.11
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  2
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               49
Model name:          AMD EPYC 7532 32-Core Processor
Stepping:            0
CPU MHz:             1500.000
CPU max MHz:         2400.0000
CPU min MHz:         1500.0000
BogoMIPS:            4800.10
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            16384K
NUMA node0 CPU(s):   0-63
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate sme ssbd rsb_ctxsw ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip overflow_recov succor smca

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.19.5
[pip3] torch==2.0.1
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchvision==0.8.2
[pip3] triton==2.0.0
[conda] blas                      2.16                        mkl    defaults
[conda] cudatoolkit               11.0.221             h6bb024c_0    defaults
[conda] libblas                   3.8.0                    16_mkl    defaults
[conda] libcblas                  3.8.0                    16_mkl    defaults
[conda] liblapack                 3.8.0                    16_mkl    defaults
[conda] liblapacke                3.8.0                    16_mkl    defaults
[conda] mkl                       2020.2                      256    defaults
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchaudio                0.7.2                      py38    pytorch
[conda] torchvision               0.8.2                py38_cu110    pytorch
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ptrblck

**Comment by mikaylagawarecki** [comment]
I was unable to reproduce on main

```
import torch
a = torch.tensor([1])
a = a.to("cuda:0")
print(a.to("cuda:1"))
# tensor([1], device='cuda:1')
```

**Comment by cpuhrsch** [comment]
Same here

**Comment by ranchlai** [comment]
My device is RTX4090.

**Comment by ranchlai** [comment]
could be hardware failure.  I am closing this. Thanks.
