### ISSUE TITLE
[feature request] Move binary_cross_entropy_with_logits into ATen

### ISSUE THREAD

**Issue by goldsborough** [pytorch/pytorch#10648]
@ebetica mentioned it would be nice to have [`torch.binary_cross_entropy_with_logits`](https://pytorch.org/docs/stable/nn.html#torch.nn.functional.binary_cross_entropy_with_logits) in C++. Seems like a reasonable thing to move into ATen. It's currently implemented in Python.

The only tricky bit is that the the reduction is currently taken as a string `"mean" | "sum" | "none"`. To support all three, we could have the C++ function just return the unreduced tensor, then you can write `torch::binary_cross_entropy_with_logits(...).sum()` or `.mean()` yourself, which is fine. Same in Python, we can just call `.sum()` or `.mean()` on the result in the implementation of `binary_cross_entropy_with_logits` (i.e. no change to the public Python API).

CC @ailzhang

**Comment by ebetica** [comment]
Fyi there is a Reduction mode or something for these losses.
