### ISSUE TITLE
AOTAutograd should detect false aliasing.

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#106457]
Today, if you write code like this:

```
@torch.compile
def f(x, y):
    x.add_(1)
    y.add_(1)

base = torch.ones(2, 2)
x = base[:, 0]
y = base[:, 1]
f(x, y)
```

Then AOTAutograd will attempt to perform some complicated "synthetic base" logic detailed [here](https://github.com/pytorch/pytorch/blob/b37a50afda55c5b73298016d10fca1f8c6f65055/torch/_functorch/aot_autograd.py#L2283).

The synthetic base logic is important for general cases where you have two inputs that alias the same memory, and a mutation on one input needs to be reflected to the other input.

But there are two problems with the example above;

(1) The repro above exhibits **false aliasing**. Even though `x` and `y` share the same storage, their memory locations are actually completely disjoint. We can generate significantly more efficient code if we detect this false aliasing. Otherwise, if we run the "synthetic base" logic, we will have to materialize two updated versions of `base` throughout the compiled graph for `f`.

(2) The synthetic base logic has a few complicated corner cases that it cannot handle. In particular, if your inputs alias each other and have non-trivial `._base` attributes, this is a case that we don't currently handle today. Fixing it is pretty non-trivial ([code](https://github.com/pytorch/pytorch/blob/main/torch/_functorch/aot_autograd.py#L1817)).

What should we do? In theory, we should be able to use the sizes/strides/storage_offset of our two inputs to figure out that they do **not** have any overlapping memory, even though they alias the same storage.

We have a version of this check in C++ today, but it only handles very simple cases because it needs to run in eager mode, which means it needs to be fast. It cannot handle the check above, because it bails out if either of its inputs are non-contiguous. Since we are compiling, we have the luxury of being okay with being a bit slower in how we check for overlapping memory.

Context: this appears to show up in the Shampoo optimizer. This could also potentially help other cases, such as:
- FSDP (uses flat params)
- LSTM (I believe the LSTM module has an optimization where its parameters are part of a single buffer)

cc @ezyang @msaroufim @wconstab @anijain2305 @zou3519

**Comment by jon-chuang** [comment]
Hello @bdhirsh , may I know what happens when the input shapes are dynamic? Do your optimizations still apply?

**Comment by bdhirsh** [comment]
@jon-chuang I tested it out (added `dynamic=True` to the repro above), and it errors haha:
```
  File "/data/users/hirsheybar/e/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 989, in merge_view_inputs
    arg_to_old_idx_map = {arg: i for (i, arg) in enumerate(fwd_inputs)}
  File "/data/users/hirsheybar/e/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 989, in <dictcomp>
    arg_to_old_idx_map = {arg: i for (i, arg) in enumerate(fwd_inputs)}
  File "/data/users/hirsheybar/e/pytorch/torch/__init__.py", line 303, in __hash__
    raise TypeError("unhashable type: non-singleton SymInt")
```

Looks like we rely on hashing arguments in the linked optimization, and we can't hash SymInts. TBH this case is hit very rarely, so I'm not sure that it's the highest-priority thing to fix

**Comment by bdhirsh** [comment]
I'm going to close this issue now, since we now have (some) support for false aliasing detection [here](https://github.com/pytorch/pytorch/blob/main/torch/_functorch/_aot_autograd/input_output_analysis.py#L334). We can re-open this issue if we decide that we need to beef it up further (this was enough to detect false aliasing for shampoo params)
