### ISSUE TITLE
jit model of qnnpack's int8 activation can not be executed on x86_64 using libtorch but python script works well

### ISSUE THREAD

**Issue by TingfengTang** [pytorch/pytorch#106598]
### 🐛 Describe the bug

I use the following python code to produce a quantized model and execute it in python environment. It works well, but fails when I use LibTorch to inference.

python code:
```
import torch

class Model(torch.nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.conv_test=torch.nn.Conv2d(1,3,(3,3))
    def forward(self,x):
        x=self.conv_test(x)
        return x
input=torch.randn(1,1,15,15)
model=Model()

import torch.ao.quantization.quantize_fx as quantize_fx
import copy

model_to_quantize=copy.deepcopy(model)
model_to_quantize.train()

from torch.ao.quantization.qconfig_mapping import QConfigMapping
from torch.ao.quantization.qconfig import default_symmetric_qnnpack_qat_qconfig

qconfig=default_symmetric_qnnpack_qat_qconfig
qconfig_mapping = QConfigMapping().set_global(qconfig)
backend_config=torch.ao.quantization.backend_config.qnnpack.get_qnnpack_backend_config()
torch.backends.quantized.engine = 'qnnpack'

model_prepared = quantize_fx.prepare_qat_fx(model_to_quantize,qconfig_mapping=qconfig_mapping,example_inputs=input,backend_config=backend_config)
model_prepared(input)
model_prepared(input)
model_quantized = quantize_fx.convert_fx(model_prepared,qconfig_mapping=qconfig_mapping,backend_config=backend_config)


model_trace=torch.jit.trace(model_quantized,input)
torch.jit.save(model_trace,'model_one_conv.pth')

model_trace_reload=torch.jit.load('model_one_conv.pth')

result_ref=model_quantized(input)
result_model_trace_reload=model_trace_reload(input)
equal_flag=torch.allclose(result_ref,result_model_trace_reload)
print('Result equal flag:{}'.format(equal_flag))
if equal_flag:
    print('The qnnpack config jit model can be executed on my x86_64 machine')
```

result:
```
Result equal flag:True
The qnnpack config jit model can be executed on my x86_64 machine
```

The following C++ invoking code would produce errors when I execute the model

C++code
```
#include <iostream>
#include "torch/torch.h"
#include "torch/script.h"
int main(int argc, char* argv[])
{
    torch::jit::script::Module module;
    try{
        module=torch::jit::load("./model_one_conv.pth");
    }
    catch(const c10::Error& e){
        std::cerr<<"error loading model:"<<e.what()<<std::endl;
        throw;
    }
    std::cout<<"loading model success"<<std::endl;
    std::cout<<"thread number of the machine is:"<<torch::get_num_threads()<<std::endl;
    torch::set_num_threads(1);
    std::vector<torch::jit::IValue> inputs;
    inputs.push_back(torch::randn({1,1,15,15}));
    at::Tensor output=module.forward(inputs).toTensor();
    std::cout<<output<<std::endl;
    std::cout<<"calc finished"<<std::endl;
}
```

CMakeList.txt:
```
cmake_minimum_required(VERSION 3.18 FATAL_ERROR)
project(example-app)

find_package(Torch REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")

add_executable(example-app test.cpp)
target_link_libraries(example-app "${TORCH_LIBRARIES}")
set_property(TARGET example-app PROPERTY CXX_STANDARD 17)
```

error message:
```
(torch2.01) root@./libTorchTest/build# ./example-app 
loading model success
thread number of the machine is:48
terminate called after throwing an instance of 'std::runtime_error'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch/fx/graph_module.py", line 15, in forward
    conv_test_input_scale_0 = self.conv_test_input_scale_0
    input = torch.quantize_per_tensor(x, conv_test_input_scale_0, conv_test_input_zero_point_0, 12)
    _0 = torch.dequantize((conv_test).forward(input, ))
                           ~~~~~~~~~~~~~~~~~~ <--- HERE
    return _0
  File "code/__torch__/torch/ao/nn/quantized/modules/conv.py", line 86, in forward
    input: Tensor) -> Tensor:
    _packed_params = self._packed_params
    conv_test = ops.quantized.conv2d(input, _packed_params, 0.013804719783365726, 0)
                ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return conv_test

Traceback of TorchScript, original code (most recent call last):
/home/sfadmin/anaconda3/envs/torch2.01/lib/python3.9/site-packages/torch/_ops.py(502): __call__
/home/sfadmin/anaconda3/envs/torch2.01/lib/python3.9/site-packages/torch/ao/nn/quantized/modules/conv.py(469): forward
/home/sfadmin/anaconda3/envs/torch2.01/lib/python3.9/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/home/sfadmin/anaconda3/envs/torch2.01/lib/python3.9/site-packages/torch/nn/modules/module.py(1501): _call_impl
<eval_with_key>.6(8): forward
/home/sfadmin/anaconda3/envs/torch2.01/lib/python3.9/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/home/sfadmin/anaconda3/envs/torch2.01/lib/python3.9/site-packages/torch/nn/modules/module.py(1501): _call_impl
/home/sfadmin/anaconda3/envs/torch2.01/lib/python3.9/site-packages/torch/fx/graph_module.py(271): __call__
/home/sfadmin/anaconda3/envs/torch2.01/lib/python3.9/site-packages/torch/fx/graph_module.py(662): call_wrapped
/home/sfadmin/anaconda3/envs/torch2.01/lib/python3.9/site-packages/torch/jit/_trace.py(1056): trace_module
/home/sfadmin/anaconda3/envs/torch2.01/lib/python3.9/site-packages/torch/jit/_trace.py(794): trace
quant.py(33): <module>
RuntimeError: quantized::conv2d (ONEDNN): data type of input should be QUint8.

Aborted (core dumped)
```

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-104-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.3.58
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
  MIG 7g.40gb     Device  0:
GPU 1: NVIDIA A100-PCIE-40GB
  MIG 3g.20gb     Device  0:
  MIG 2g.10gb     Device  1:
  MIG 2g.10gb     Device  2:
GPU 2: NVIDIA A100-PCIE-40GB
  MIG 3g.20gb     Device  0:
  MIG 2g.10gb     Device  1:
  MIG 2g.10gb     Device  2:
GPU 3: NVIDIA A100-PCIE-40GB
  MIG 3g.20gb     Device  0:
  MIG 2g.10gb     Device  1:
  MIG 2g.10gb     Device  2:

Nvidia driver version: 470.82.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-89
Off-line CPU(s) list:            90-95
Thread(s) per core:              1
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         3452.988
CPU max MHz:                     4000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        6000.00
Virtualization:                  VT-x
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        24 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==2.0.1+cu117
[pip3] torch-pruning==1.0.0
[pip3] torch-scatter==2.1.0+pt112cu113
[pip3] torch-tb-profiler==0.4.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] torch                     2.0.1+cu117              pypi_0    pypi
[conda] torch-pruning             1.0.0                    pypi_0    pypi
[conda] torch-scatter             2.1.0+pt112cu113          pypi_0    pypi
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by supriyar** [comment]
for consistency, can you try setting the quantized engine to 'qnnpack' in the C++ code as well? 

@digantdesai would you know if it is possible to execute qnnpack quantized models in a c++ environment?

**Comment by TingfengTang** [comment]
Thanks, @supriyar , I follow the code snippet of [https://github.com/pytorch/pytorch/issues/28945#issuecomment-549399690](url), and set the qengine to 'qnnpack' in my c++ code on Linux_x86_64, it works! 
But another question arises, when I run the testing code on win10_x86_64 to print the supported backend list, it shows windows doesn't support 'qnnpack'.
The code snippet I used:
```
#include <iostream>
#include "torch/torch.h"
#include "torch/script.h"
int main(int argc, char* argv[])
{
    auto qengines = at::globalContext().supportedQEngines();
    for(auto qengine:qengines)
    {
        std::cout<<c10::toString(qengine)<<std::endl;
    }
}
```

the supported backends are:
```
NoQEngine
ONEDNN
X86
FBGEMM
```
Is 'qnnpack' natively unsupported on windows platform or I should rebuild it on windows, Thanks.

**Comment by mcr229** [comment]
yes qnnpack does not have support on windows platforms in OSS.
