### ISSUE TITLE
cover to onnx error

### ISSUE THREAD

**Issue by WangHHY19931001** [pytorch/pytorch#106505]
### 🐛 Describe the bug

code：

```python
import torch.onnx
import torchaudio
from torch import nn


class DataCov(nn.Module):
    def __init__(self):
        super(DataCov, self).__init__()

        self.transform = nn.Sequential(
            torchaudio.transforms.MelSpectrogram(sample_rate=48000, n_fft=1536, hop_length=768, f_min=20, f_max=20000)
        )

    def forward(self, x1):
        return self.transform(x1)



if __name__ == '__main__':
    model = DataCov()
    model.eval()
    model = torch.jit.script(model)

    x = torch.randn(1, 48000 * 12, requires_grad=True)
    args = (x,)
    torch.onnx.export(model, args, 'DataCov.onnx', export_params=True, opset_version=15)

```

error：

```
C:\Users\dell\miniconda3\envs\onnx_cov\lib\site-packages\torch\onnx\_internal\jit_utils.py:306: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::stft' to ONNX opset version 15 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>


Traceback (most recent call last):
  File "D:\onnx_cov\main.py", line 15, in <module>
    torch.onnx.export(model, args, 'DataCov.onnx', export_params=True, opset_version=15)
  File "C:\Users\dell\miniconda3\envs\onnx_cov\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\Users\dell\miniconda3\envs\onnx_cov\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\dell\miniconda3\envs\onnx_cov\lib\site-packages\torch\onnx\utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\dell\miniconda3\envs\onnx_cov\lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\dell\miniconda3\envs\onnx_cov\lib\site-packages\torch\onnx\utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::stft' to ONNX opset version 15 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: (Rev5, Built by MSYS2 project) 13.1.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:










Revision=

Versions of relevant libraries:
[pip3] numpy==1.25.0
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl    defaults
[conda] cpuonly                   2.0                           0    pytorch
[conda] mkl                       2023.1.0         h8bd8f75_46356    defaults
[conda] mkl-service               2.4.0           py310h2bbff1b_1    defaults
[conda] mkl_fft                   1.3.6           py310h4ed8f06_1    defaults
[conda] mkl_random                1.2.2           py310h4ed8f06_1    defaults
[conda] numpy                     1.25.1                   pypi_0    pypi
[conda] numpy-base                1.25.0          py310h65a83cf_0    defaults
[conda] pytorch                   2.0.1              py3.10_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                2.0.2                 py310_cpu    pytorch
[conda] torchvision               0.15.2                py310_cpu    pytorch

```

**Comment by sandhya-suman-ux** [comment]
C:\Users\JNTU-HYD\AppData\Local\Programs\Python\Python310>python C:\FFC-main\pthtoonnx.py ffc_resnet50
my models: <class 'list'>
list of my models: ['ffc_resnet101', 'ffc_resnet152', 'ffc_resnet18', 'ffc_resnet200', 'ffc_resnet26', 'ffc_resnet34', 'ffc_resnet50', 'ffc_resnext101_32x8d', 'ffc_resnext50_32x4d']
None
=> creating model 'ffc_resnet18'
x
C:\Users\JNTU-HYD\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\onnx\_internal\jit_utils.py:306: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::fft_rfftn' to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>


Traceback (most recent call last):
  File "C:\FFC-main\pthtoonnx.py", line 183, in <module>
    torch.onnx.export(model, dummy_input, onnx_model_path, export_params=True, opset_version=11)
  File "C:\Users\JNTU-HYD\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\Users\JNTU-HYD\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\JNTU-HYD\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\onnx\utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\JNTU-HYD\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\JNTU-HYD\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\onnx\utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::fft_rfftn' to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

**Comment by justinchuby** [comment]
`stft` is support since opset version 17. Please set `opset_version=17` or higher.

**Comment by WangHHY19931001** [comment]
> ```python
> x = torch.randn(1, 48000 * 12, requires_grad=True)
>     args = (x,)
>     torch.onnx.export(model, args, 'DataCov.onnx', export_params=True, opset_version=15)
> ```
    model = DataCov()
    model.eval()
    model = torch.jit.script(model)
    x = torch.randn(1, 48000 * 12, requires_grad=True)
    args = (x,)
    torch.onnx.export(model, args, path, export_params=True, opset_version=17)

C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\_internal\jit_utils.py:306: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::stft' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>


Traceback (most recent call last):
  File "D:\mos_cov_to_android\main.py", line 189, in <module>
    export_datacov_onnx('DataCov.onnx')
  File "D:\mos_cov_to_android\main.py", line 183, in export_datacov_onnx
    torch.onnx.export(model, args, path, export_params=True, opset_version=17)
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
            ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\mos_cov_to_android\Lib\site-packages\torch\onnx\utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::stft' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
