### ISSUE TITLE
[feature request] [Caffe2] Add "sigmoid" layer into the brew API

### ISSUE THREAD

**Issue by CarlosYeverino** [pytorch/pytorch#10656]
It would be very nice to include the "sigmoid" layer into the brew API. I think it's a pretty standard activation function to be in there such as relu and tanh.

As far as I know and checked, this layer is not included yet in brew:
https://github.com/pytorch/pytorch/blob/master/caffe2/python/brew.py

**Comment by harouwu** [comment]
Hi @CarlosYeverino , thanks for your interest. Sigmoid is a simple operator.  there is not actually helper needed for sigmoid. A recommended way to do it is just 
`net.Sigmoid(input, output)`
