### ISSUE TITLE
torch.FloatTensor and similar accept, but ignore device argument

### ISSUE THREAD

**Issue by arogozhnikov** [pytorch/pytorch#10655]
## Code example

```
torch.FloatTensor([1], device=torch.device('cuda:0')).device # cpu
torch.IntTensor([1], device=torch.device('cuda:0')).device     # cpu
```
- same story when passing string 'cuda:0'. 
- checked that these constructors indeed expect device parameter

- PyTorch or Caffe2: pytorch 0.4.1
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source): NA
- OS: ubuntu 16
- PyTorch version: 0.4.1
- Python version: 3.6
- CUDA/cuDNN version: 9.0
- GPU models and configuration: 1070
- GCC version (if compiling from source): NA
- CMake version: NA
- Versions of any other relevant libraries: NA

**Comment by zou3519** [comment]
We should probably error out in this case. torch.FloatTensor is our legacy constructor; please use the `torch.tensor` constructor.

**Comment by zou3519** [comment]
#10499 will fix this.
