### ISSUE TITLE
install cuda version always get cpuonly

### ISSUE THREAD

**Issue by lcxsnow** [pytorch/pytorch#106565]
### 🐛 Describe the bug

I found that when installing PyTorch with CUDA version 1.9.1 or below, the cpuonly library is also installed, which prevents training from using the GPU. Even after uninstalling cpuonly, it still doesn’t work.

I have experimented with versions 1.10.1, 1.10.0, 1.9.1, 1.9.0, 1.8.1 and 1.8.0.

### Versions

Collecting environment information...
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.16 (default, Jun 12 2023, 18:09:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: 11.4.152
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 470.182.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn.so.8.6.0
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.6.0
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.6.0
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.6.0
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.6.0
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.6.0
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               33
Model name:          AMD Ryzen 9 5950X 16-Core Processor
Stepping:            0
CPU MHz:             2197.976
CPU max MHz:         3400.0000
CPU min MHz:         2200.0000
BogoMIPS:            6799.97
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.0a0+e4e171a
[pip3] torchvision==0.9.1
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] cudatoolkit               11.3.1              h9edb442_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h95df7f1_0    conda-forge
[conda] mkl_fft                   1.3.1            py38h8666266_1    conda-forge
[conda] mkl_random                1.2.2            py38h1abd341_0    conda-forge
[conda] numpy                     1.24.3           py38h14f4228_0  
[conda] numpy-base                1.24.3           py38h31eccc5_0  
[conda] pytorch                   1.8.1               py3.8_cpu_0  [cpuonly]  pytorch
[conda] torchaudio                0.8.1                      py38    pytorch
[conda] torchvision               0.9.1                  py38_cpu  [cpuonly]  pytorch

**Comment by jonbakerfish** [comment]
Same problem here. Using the command provided by the website will always install the CPU version. I need to use
`pip3 install torch==2.0.1+cu117  --index-url https://download.pytorch.org/whl/cu117` to install the GPU version.

**Comment by atalman** [comment]
Closing this - no longer applicable

**Comment by atalman** [comment]
@lcxsnow as per previous-versions page: https://pytorch.org/get-started/previous-versions/ 
```
 pip install torch==1.10.1+cu102 torchvision==0.11.2+cu102 torchaudio==0.10.1 -f https://download.pytorch.org/whl/cu102/torch_stable.html
Looking in links: https://download.pytorch.org/whl/cu102/torch_stable.html
Collecting torch==1.10.1+cu102
  Downloading https://download.pytorch.org/whl/cu102/torch-1.10.1%2Bcu102-cp38-cp38-linux_x86_64.whl (881.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 881.9/881.9 MB 3.2 MB/s eta 0:00:00
Collecting torchvision==0.11.2+cu102
  Downloading https://download.pytorch.org/whl/cu102/torchvision-0.11.2%2Bcu102-cp38-cp38-linux_x86_64.whl (23.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 26.7 MB/s eta 0:00:00
Collecting torchaudio==0.10.1
  Downloading https://download.pytorch.org/whl/cu102/torchaudio-0.10.1%2Bcu102-cp38-cp38-linux_x86_64.whl (2.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 22.7 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in /home/atalman/miniconda3/envs/py38/lib/python3.8/site-packages (from torch==1.10.1+cu102) (4.11.0)
Requirement already satisfied: numpy in /home/atalman/.local/lib/python3.8/site-packages (from torchvision==0.11.2+cu102) (1.24.4)
Collecting pillow!=8.3.0,>=5.3.0 (from torchvision==0.11.2+cu102)
  Downloading pillow-10.3.0-cp38-cp38-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
Downloading pillow-10.3.0-cp38-cp38-manylinux_2_28_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 77.6 MB/s eta 0:00:00
Installing collected packages: torch, pillow, torchvision, torchaudio
  Attempting uninstall: torch
    Found existing installation: torch 2.4.0.dev20240513+cpu
    Uninstalling torch-2.4.0.dev20240513+cpu:
      Successfully uninstalled torch-2.4.0.dev20240513+cpu
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.18.0.dev20240227+cu121
    Uninstalling torchvision-0.18.0.dev20240227+cu121:
      Successfully uninstalled torchvision-0.18.0.dev20240227+cu121
Successfully installed pillow-10.3.0 torch-1.10.1+cu102 torchaudio-0.10.1+cu102 torchvision-0.11.2+cu102
```

**Comment by atalman** [comment]
closing this issue for now
