### ISSUE TITLE
[dynamo] Unsupported to trace through Boolean Tensor indexing

### ISSUE THREAD

**Issue by OrenLeung** [pytorch/pytorch#106580]
### 🐛 Describe the bug

even though indexing by boolean tensor is supported in normal torch, it is not supported in dynamo

### Reprod Script
```python
import torch

def reprod_function(t: torch.Tensor, a: torch.Tensor):
    t[a] *= 0.2
    return t

reprod_function_compile = torch.compile(reprod_function, backend="eager", fullgraph=True)

x  = torch.rand(1,2,3)
y = torch.rand(1,2,3).to(torch.bool)
z = reprod_function(x,y)
print(z.dtype)
z = reprod_function_compile(x,y)
print(z.dtype)
```

### Traceback
```python
File "PATH_TO_PYTHON_LIB/site-packages/torch/_dynamo/variables/builtin.py", line 450, in call_function
    unimplemented("dynamic Tensor.__getitem__(bool[])")
  File "PATH_TO_PYTHON_LIB/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: dynamic Tensor.__getitem__(bool[])

from user code:
   File "./reprod.py", line 4, in reprod_function
    t[a] *= 0.2

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

cc: @cchan @ezhang887 @ezyang

### Versions

torch==2.0.1
python==3.8

### Workaround
```python
t = torch.where(a, t * 0.2, t) 
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by shingjan** [comment]
looks similar to https://github.com/pytorch/pytorch/issues/101168 as `__getitem__/__setitem__ ` not supported in user-defined/dynamic variables.

**Comment by OrenLeung** [comment]
> looks similar to #101168 as `__getitem__/__setitem__ ` not supported in user-defined/dynamic variables.

i am a bit confused. can you explain how it is similar to #101168 when #101168 error is `setattr` not being supported?

**Comment by OrenLeung** [comment]
> looks similar to #101168 as `__getitem__/__setitem__ ` not supported in user-defined/dynamic variables.

@shingjan i am a bit confused. can you explain how it is similar to #101168 when #101168 error is `setattr` not being supported?

**Comment by shingjan** [comment]
@OrenLeung my bad. Overlooked the terms on the ticket mentioed above. Nvm!

**Comment by OrenLeung** [comment]
> @OrenLeung my bad. Overlooked the terms on the ticket mentioed above. Nvm!

@shingjan no worries. wish `setattr` was supported too lol

**Comment by chauhang** [comment]
@OrenLeung Is this issue resolved now with https://github.com/pytorch/pytorch/pull/107844

**Comment by ezyang** [comment]
works now with ` torch._dynamo.config.capture_dynamic_output_shape_ops = True`
