### ISSUE TITLE
Inductor generates more kernels than we expected when cat/stack inputs

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#106688]
with @xw285cornell @xuzhao9 
### 🐛 Describe the bug

Repro
```
import torch
import logging

torch._logging.set_logs(dynamo=logging.DEBUG, inductor=logging.DEBUG)
torch._dynamo.config.suppress_errors = False


def fn(x1, x2, x3, w1, w2, w3):
    x = torch.stack([x1, x2, x3])
    w = torch.stack([w1, w2, w3])

    y = torch.bmm(x, w)

    return y

x1 = torch.randn(5, 4).cuda()
x2 = x1 + 1
x3 = x1 + 2
w1 = torch.randn(4, 3).cuda()
w2 = w1 + 1
w3 = w1 + 2

args = [x1, x2, x3, w1, w2, w3]

ref = fn(*args)
print(ref)

res = torch.compile(fn)(*args)
print(res)

```

Look at the [Inductor output code](https://gist.github.com/yanboliang/d0a083be0ca1428a51977099b47a3a85), we found the generated kernels are not optimal:
* It allocates a large buffer ```buf3``` to store the whole inputs (x1, x2, x3) and ```buf7``` to store the whole weights (w1, x2, x3), which are optimal.
* However, it launches 6 small kernels (```triton_poi_fused_stack_*```) to copy inputs [x1, x2, x3, w1, x2, x3] to the corresponding buffer offset, which is not optimal IMO. Can we just land 2 kernels (one for inputs and one for weight) to do the copy work?

Context:
* We found this issue from batch fusion, where we are trying to fuse multiple ```mm``` into one ```bmm``` to reduce the number of launched kernels. However, we found after fusing```mm``` into ```bmm```, the generated code introduced the same amount of copy kernels, which eliminates the perf gain.

### Versions

N/A

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by yanboliang** [comment]
cc @jansel

**Comment by jansel** [comment]
Agreed, we should be able to do this with fewer kernels.  This might also be a good use for foreach kernels: cc @mlazos

**Comment by mlazos** [comment]
I've been looking for a reason to do this. @yanboliang let's discuss tm, this should be relatively easy to do
