### ISSUE TITLE
Question about garbage collection without GPU sync 

### ISSUE THREAD

**Issue by NmomoN** [pytorch/pytorch#106660]
### 🐛 Describe the bug

I found that in `void garbage_collect_cached_blocks()`

```
    size_t gc_threshold = static_cast<size_t>(
        CachingAllocatorConfig::garbage_collection_threshold() *
        allowed_memory_maximum);
```
If the `torch._C._cuda_setMemoryFraction` function is not called，`allowed_memory_maximum` value is 0. The value of `gc_threshold` is also 0. The garbage collection without GPU sync mechanism does not take effect. And there's no prompt.
So I think it's more reasonable whether to use `device_total` (obtained using `cudaMemGetInfo`) when `allowed_memory_maximum` is 0.

### Versions

https://github.com/pytorch/pytorch/blob/dc22b4fdb1b4af1f0b7b77a78b30237d337d7109/c10/cuda/CUDACachingAllocator.cpp#L2577C47-L2577C47

**Comment by albanD** [comment]
cc @zdevito
