### ISSUE TITLE
torch.einsum 400x slower than numpy.einsum on a simple contraction

### ISSUE THREAD

**Issue by fritzo** [pytorch/pytorch#10661]
## Issue description

`torch.einsum` is 400x slower than `numpy.einsum` on a simple contraction. This is making some Pyro models very slow.

## Code example

```py
import torch, numpy, timeit
x = torch.randn((2, 2000))
y = torch.randn((2, 2, 2000))
equation = 'ac,abc->cb'

time0 = timeit.default_timer()
for _ in range(1000):
    _ = torch.einsum(equation, [x, y])

time1 = timeit.default_timer()
for _ in range(1000):
    _ = numpy.einsum(equation, x.numpy(), y.numpy())

time2 = timeit.default_timer()
print('torch: {}'.format(time1 - time0))
print('numpy: {}'.format(time2 - time1))
```
```
torch: 3.97460007668
numpy: 0.00863790512085
```

## System Info

```
$ python collect_env.py
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.3
GCC version: Could not collect
CMake version: version 3.12.0

Python version: 2.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     0.4.0                     <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                     <pip>
```

**Comment by fritzo** [comment]
cc @t-vi

**Comment by fritzo** [comment]
cc @neerajprad

**Comment by t-vi** [comment]
So at first sight, we seem to inherit a lot of slowdown from bmm.
I get
```
0.0
torch: 5.314521988999331
numpy: 0.005557203001444577
torch.bmm: 5.034999315999812
```
from the script below.
Quite likely, bmm doesn't like large batches of small multiplications. When replacing "2" by "200" as the smaller dimensions, there is a single digit factor between the speeds (which still is rather large).
If possible, I'd like to fix this in bmm, but I haven't tracked down the root cause yet.

```
import torch, numpy, timeit
x = torch.randn((2, 2000))
y = torch.randn((2, 2, 2000))
xp = x.permute(1, 0).view(2000, 1, 2)
yp = y.permute(2, 0, 1)
equation = 'ac,abc->cb'

time0 = timeit.default_timer()
for _ in range(1000):
    _ = torch.einsum(equation, [x, y])

time1 = timeit.default_timer()
for _ in range(1000):
    _ = numpy.einsum(equation, x.numpy(), y.numpy())

time2 = timeit.default_timer()

for _ in range(1000):
    _ = torch.bmm(xp, yp)
time3 = timeit.default_timer()

# check that we calculate the right thing.
print((torch.einsum(equation, [x, y])-torch.bmm(xp, yp).squeeze()).abs().max().item())

print('torch: {}'.format(time1 - time0))
print('numpy: {}'.format(time2 - time1))
print('torch.bmm: {}'.format(time3 - time2))
```

**Comment by t-vi** [comment]
So the inefficiency comes from `bmm` on CPU iterating over the batch dimension and relegating to the matrix multiplication.
I have a tentative CPU fix that just spells out the bmm contraction (currently for `batch > 10 * contraction size`, but I would need to investigate the tradeoff) and parallelizes over the batch dimension.

The GPU bmm uses cublas' batch gemm (if available / applicable) so I would leave that alone for the moment unless we identify inferior performance there, too. I don't know how it compares e.g. to magma.

Fun facts:
- Numpy's `bmm` actually delegates to numpy's einsum which has all sorts of contraction operations for various setups. 
- MKL seems to have a batch gemm, one might use that eventually.

**Comment by fritzo** [comment]
@t-vi thanks for digging in to find the root cause!

**Comment by weiyangfb** [comment]
@t-vi can I help move this forward? I have some free cycles to pick up this issue.

**Comment by t-vi** [comment]
He. I've been away from the GPU, I'll push a commit for your review.

**Comment by t-vi** [comment]
Seems that this has regressed again to a factor of 40-50 on my computer...

**Comment by neerajprad** [comment]
> Seems that this has regressed again to a factor of 40-50 on my computer...

The example above seems to be ~8X slower on my system (OSX) using the conda nightly build.

**Comment by alexjc** [comment]
This is now only a factor of 3x slower on pytorch 1.1.0. (Both CPU.)
```
torch: 0.11358046904206276
numpy: 0.0478258840739727
```

**Comment by artemru** [comment]
The benchmark on bigger arrays is less optimistic, I've got x50 factor with pytoch=1.2.0, CPU only, 4 cores:
```python
import torch, numpy 
x = torch.randn((10**5, 2000)) 
y = torch.randn((10**5, 2, 2000)) 
equation = 'ac,abc->cb' 
%timeit numpy.einsum(equation, x.numpy(), y.numpy())
# 180 ms ± 25.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit torch.einsum(equation, [x, y]).shape
10.4 s ± 331 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Should not we reopen this issue ?

**Comment by qzhu2017** [comment]
I got the similar speed as @artemru reported. I also attempted to use [opt-einsum](https://pypi.org/project/opt-einsum/) to optimize the order in my code where einsum was used in several places. However, it does not help in general. Will someone work on this in near future?

**Comment by t-vi** [comment]
So the issue we dealt with here was slowness of `torch.bmm` underlying `torch.einsum`. This has been solved.
The issue that you want solved is recorded as https://github.com/pytorch/pytorch/issues/21760.
From what I read there, it is being worked on.
