### ISSUE TITLE
Inconsistent output of torch.mm when called in two mathematically equivalent way

### ISSUE THREAD

**Issue by geblue** [pytorch/pytorch#10660]
Hi,

 I tired to use torch.mm to get matrix multiplication, but found it returned slightly different results when I called it in two equivalent way.

Assume we have two matrix  matrix_a and matrix_b and want to get the matrix multiplication matrix_a@matrix_b
1. First, I use matrix_a and matrix_b as input directly, torch.mm(matrix_a, matrix_b)
2. On the other hand, I call torch.mm with each row of matrix_a together with matrix_b as inputs, and then concatenate the results.

The two results are expected to be exactly the same, but they are still slightly diferent. So can somebody explain the reason?

Thanks,

Here is my test code.

```
torch.manual_seed(0)

matrix_a = torch.randn([5, 4])
matrix_b = torch.randn([4, 4])
values = torch.randn([5, 4])

# 1. call torch.mm directly on matrix_a and matrix_b.
torch.mm(matrix_a, matrix_b, out=values)

# save the result in buffer.
values_1 = values.clone()

# 2. call torch.mm on each row of matrix_a and matrix_b.
batch_size = matrix_a.size(0)
for b in range(batch_size):
    torch.mm(matrix_a[b:b+1], matrix_b, out=values[b:b+1])

# value and value_1 are supposed to be equal. But they are not.
logger.info("difference between two values: %s" % (torch.sum(torch.abs(values - values_1))))
for b in range(batch_size):
    logger.info("batch id: %s" % b)
    logger.info(values_1[b].data.numpy())
    logger.info(values[b].data.numpy())
```

Here is the output.

>  2018-08-18 21:32:11,294 INFO 87997 [test.py:81] difference between two values: tensor(1.00000e-06 *
>        1.3113)
> 2018-08-18 21:32:11,295 INFO 87997 [test.py:83] batch id: 0
> 2018-08-18 21:32:11,295 INFO 87997 [test.py:84] [-0.89934576  0.11556479 -0.48109883 -0.3961889 ]
> 2018-08-18 21:32:11,295 INFO 87997 [test.py:85] [-0.89934576  0.11556476 -0.4810989  -0.39618894]
> 2018-08-18 21:32:11,296 INFO 87997 [test.py:83] batch id: 1
> 2018-08-18 21:32:11,296 INFO 87997 [test.py:84] [ 2.6500921   0.5928108  -2.213797    0.39320117]
> 2018-08-18 21:32:11,296 INFO 87997 [test.py:85] [ 2.6500921   0.59281075 -2.2137969   0.3932012 ]
> 2018-08-18 21:32:11,296 INFO 87997 [test.py:83] batch id: 2
> 2018-08-18 21:32:11,296 INFO 87997 [test.py:84] [ 1.3148142  3.5158207 -2.2286756 -2.1263554]
> 2018-08-18 21:32:11,297 INFO 87997 [test.py:85] [ 1.3148141  3.515821  -2.2286754 -2.1263554]
> 2018-08-18 21:32:11,297 INFO 87997 [test.py:83] batch id: 3
> 2018-08-18 21:32:11,297 INFO 87997 [test.py:84] [-0.25188264  1.0855039   1.4054772  -0.47265998]
> 2018-08-18 21:32:11,297 INFO 87997 [test.py:85] [-0.25188267  1.085504    1.4054773  -0.47265998]
> 2018-08-18 21:32:11,298 INFO 87997 [test.py:83] batch id: 4
> 2018-08-18 21:32:11,298 INFO 87997 [test.py:84] [ 1.250929   3.790292  -1.7040166 -2.443583 ]
> 2018-08-18 21:32:11,298 INFO 87997 [test.py:85] [ 1.250929   3.790292  -1.7040166 -2.443583 ]

**Comment by soumith** [comment]
Here's a thread where I go through why you dont get the "exact" same results, and why this is expected, due to floating point numbers: https://github.com/pytorch/pytorch/issues/9146#issuecomment-409331986
