### ISSUE TITLE
torch.det compute error 

### ISSUE THREAD

**Issue by Xinchengzelin** [pytorch/pytorch#106603]
### 🐛 Describe the bug

The grad_fn affects the result of `torch.det`  ?  why convert the tensor to  numpy, the result is also wrong?

 [covariance_matrices.zip](https://github.com/pytorch/pytorch/files/12257702/covariance_matrices.zip)

```
import torch
# file
covariance_matrices = torch.load("covariance_matrices.pt")
c = covariance_matrices[43,1,-8]
print("-"*50)
print("c: \n", c)
print("-"*50)
print("det: \n",torch.det(c))
print("-"*50)
print("index det: \n",c[0,0]*c[1,1] - c[0,1]*c[1,0])
print("-"*50)
print("compute det manualy: \n",(1.7533e+03)*(9.9205e+17) - (4.1705e+10)*(4.1705e+10))

print("-"*50)
n = c.detach().cpu().numpy()
print("numpy det: \n",np.linalg.det(n))
print(n)

print("-"*50)
t = torch.tensor([[1.7533e+03, 4.1705e+10],
        [4.1705e+10, 9.9205e+17]])

print("new tensor det: \n", torch.det(t))

```

output:

```
--------------------------------------------------
c: 
 tensor([[1.7533e+03, 4.1705e+10],
        [4.1705e+10, 9.9205e+17]], device='cuda:0', grad_fn=<SelectBackward0>)
--------------------------------------------------
det: 
 tensor(-3.3443e+14, device='cuda:0', grad_fn=<DetLuBasedHelperBackward0>)
--------------------------------------------------
index det: 
 tensor(-2.8147e+14, device='cuda:0', grad_fn=<SubBackward0>)
--------------------------------------------------
compute det manualy: 
 5.423999999986893e+16
--------------------------------------------------
numpy det: 
 -277851450000000.0
[[1.7533e+03 4.1705e+10]
 [4.1705e+10 9.9205e+17]]
--------------------------------------------------
new tensor det: 
 tensor(5.4237e+16)
```

### Versions

PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.14.0-1059-oem-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA RTX A4000
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          40
On-line CPU(s) list:             0-39
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
Stepping:                        7
CPU MHz:                         2400.000
CPU max MHz:                     3200.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4800.00
Virtualization:                  VT-x
L1d cache:                       640 KiB
L1i cache:                       640 KiB
L2 cache:                        20 MiB
L3 cache:                        27.5 MiB
NUMA node0 CPU(s):               0-9,20-29
NUMA node1 CPU(s):               10-19,30-39
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==3.8.4
[pip3] numpy==1.19.0
[pip3] numpydoc==1.4.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.10.2+cu113
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==2.0.4
[pip3] torch-scatter==2.0.9
[pip3] torch-tb-profiler==0.4.0
[pip3] torchvision==0.11.3+cu113
[conda] numpy                     1.19.0                   pypi_0    pypi
[conda] numpydoc                  1.4.0                    pypi_0    pypi
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.10.2+cu113             pypi_0    pypi
[conda] torch-cluster             1.5.9                    pypi_0    pypi
[conda] torch-geometric           2.0.4                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchvision               0.11.3+cu113             pypi_0    pypi

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by lezcano** [comment]
You can:
1. Update to a newer PyTorch version, that one is way too old
2. Compute the determinant in `float64`. That's what NumPy is doing.
3. See https://pytorch.org/docs/stable/notes/numerical_accuracy.html#extremal-values-in-linalg when it comes to stability issues in PyTorch (the determinant is *very* badly conditioned, you might want to consider taking the [`slogdet`](https://pytorch.org/docs/stable/generated/torch.linalg.slogdet.html))

**Comment by Xinchengzelin** [comment]
> You can:
> 
> 1. Update to a newer PyTorch version, that one is way too old
> 2. Compute the determinant in `float64`. That's what NumPy is doing.
> 3. See https://pytorch.org/docs/stable/notes/numerical_accuracy.html#extremal-values-in-linalg when it comes to stability issues in PyTorch (the determinant is _very_ badly conditioned, you might want to consider taking the [`slogdet`](https://pytorch.org/docs/stable/generated/torch.linalg.slogdet.html))

Thanks your help. 
1. The `torch.linalg` is always update? so the newer version PyTorch could handle the stability issues better? 
2. With respect to the stability issues, I wan't to replace `torch.inv` with `torch.pinv`,  the graident is easily computed to be NaN, Could you give me some advises?

**Comment by lezcano** [comment]
Always prefer the linalg functions in `torch.linalg`. That being said, you are using a very old version fo PyTorch, updating to a newer one should help.

The inv / pinv question seems unrelated. Feel free to open a topic in https://discuss.pytorch.org/ and we can discuss it there.

Closing this one, as this is expected as per https://pytorch.org/docs/stable/notes/numerical_accuracy.html#extremal-values-in-linalg
