### ISSUE TITLE
Dynamo graph break on triplet_margin_with_distance_loss

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#106649]
### 🐛 Describe the bug

python test/inductor/test_torchinductor_opinfo.py -k test_comprehensive_nn_functional_triplet_margin_with_distance_loss_cuda_float32

>   File "/scratch/eellison/work/pytorch/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/scratch/eellison/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1156, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/scratch/eellison/work/pytorch/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/scratch/eellison/work/pytorch/torch/_dynamo/variables/torch.py", line 723, in call_function
    *proxy_args_kwargs(args, kwargs),
  File "/scratch/eellison/work/pytorch/torch/_dynamo/utils.py", line 504, in proxy_args_kwargs
    f"call_function args: {typestr(*args)} {typestr(*list(kwargs.values()))}"
  File "/scratch/eellison/work/pytorch/torch/_dynamo/exc.py", line 143, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function args: TensorVariable() TensorVariable() TensorVariable() ConstantVariable(float) NNModuleVariable()

related: https://github.com/pytorch/pytorch/issues/105534

### Versions

master

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov @peterbell10 @ngimel @yf225 @kadeng @muchulee8

**Comment by anijain2305** [comment]
Instructions to repro this 

1) Edit file - `test/inductor/test_torchinductor_opinfo.py` and comment out this line

~~~
diff --git a/test/inductor/test_torchinductor_opinfo.py b/test/inductor/test_torchinductor_opinfo.py
index 49fff64b5cd..3fa62738b90 100644
--- a/test/inductor/test_torchinductor_opinfo.py
+++ b/test/inductor/test_torchinductor_opinfo.py
@@ -220,7 +220,7 @@ inductor_expected_failures_single_sample["cpu"] = {
     "nn.functional.avg_pool2d": {i64},
     "nn.functional.local_response_norm": {i64},
     "nn.functional.rrelu": {f32, f64},
-    "nn.functional.triplet_margin_with_distance_loss": {f16, f32, f64, i32, i64},
+    # "nn.functional.triplet_margin_with_distance_loss": {f16, f32, f64, i32, i64},
     "nonzero_static": {b8, f16, f32, f64, i32, i64},
     "normal": {f16, f32, f64},
     ("normal", "in_place"): {f16, f32, f64},
~~~ 

2) Run `python test/inductor/test_torchinductor_opinfo.py -k test_comprehensive_nn_functional_triplet_margin_with_distance_loss_cpu_float32`
