### ISSUE TITLE
Update README.md to include examples

### ISSUE THREAD

**Issue by Tincaniam** [pytorch/pytorch#106600]
### 📚 The doc issue

Update README.md to include impressive short examples of what PyTorch can do for newcomers.

The existing documentation for PyTorch is very well crafted and thorough. However, as it is now one of the most popular machine learning libraries for Python, and more people are coming to machine learning now than ever before, I believe that the beginning of their ReadMe could cater more toward a beginner to machine learning than it does currently. Currently their ReadMe seems more to cater towards those experienced with Machine Learning and why they should use PyTorch, with no examples given within the first several pages. This change adds brief and impressive code snippets to demonstrate how easily one can create power machine learning tools with small amounts of code utilizing the PyTorch library.

### Suggest a potential alternative/fix

Early in the README.md could be updated  with simple and powerful examples that make it clear to newer developers to the project what developers can do with PyTorch.

See example below starting at **line 9** in README.md

You can reuse your favorite Python packages such as NumPy, SciPy, and Cython to extend PyTorch when needed.

## What Can PyTorch Do?
- Define a tensor filled with zeros:
    - ```
      import torch
      zeros_tensor = torch.zeros((3, 3))
      ```
- Compute the element-wise exponential of a tensor:
    - ```
      import torch
      tensor = torch.tensor([1.0, 2.0, 3.0])
      exp_tensor = torch.exp(tensor)
      ```
- Perform a matrix multiplication using PyTorch:
    - ```
      import torch
      A = torch.tensor([[1, 2], [3, 4]])
      B = torch.tensor([[5, 6], [7, 8]])
      result = torch.matmul(A, B)
      ```
- Create a simple neural network layer with PyTorch:
    - ```
      import torch.nn as nn
      layer = nn.Linear(in_features=10, out_features=5)
      ```
Our trunk health (Continuous Integration signals) can be found at [hud.pytorch.org](https://hud.pytorch.org/ci/pytorch/pytorch/main).

cc @svekars @carljparker

**Comment by 0takugod** [comment]
I agree with this opinion.

**Comment by albanD** [comment]
Hey!

We already have pretty detailed intro documentation. Maybe we simply want to add a link from the readme to https://pytorch.org/tutorials/beginner/basics/intro.html what do you think?

**Comment by Tincaniam** [comment]
> Hey!
> 
> We already have pretty detailed intro documentation. Maybe we simply want to add a link from the readme to https://pytorch.org/tutorials/beginner/basics/intro.html what do you think?

Hey, I agree that the intro documentation is excellent and detailed. Potentially linking this intro documentation early in the README could help direct newcomers more easily to the right place and accomplish this goal.

My primary goal for this issue to showcase to newcomers how easily they can use PyTorch, but perhaps this is a difficult ask for just the README.

**Comment by albanD** [comment]
I think that adding this link as the first line in https://github.com/pytorch/pytorch#more-about-pytorch would be a good way to share this. Would you be able to send a PR for this?

**Comment by Tincaniam** [comment]
Sounds good. Pull request #107344 sent.
