### ISSUE TITLE
Dynamo Graph Break on torch.Tensor.__getitem__

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#106648]
### 🐛 Describe the bug

We support `tensor.__getitem__` and `tensor[..]` but graph break on `torch.Tensor.__getitem__`. Because we graph break here we do not get torch.compile test coverage for Tensor indexing opinfo. 

```
import torch

@torch.compile()
def foo(x):
    return x.__getitem__([1, 2])

x = torch.rand([5, 5, 5])
# works
foo(x)

@torch.compile()
def foo(x):
    return torch.Tensor.__getitem__([1, 2])

# graph break
foo(x)
```

Related: https://github.com/pytorch/pytorch/issues/105534

### Versions

master

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov @peterbell10 @ngimel @yf225 @kadeng @muchulee8

**Comment by anijain2305** [comment]
Check if _getitem__ returns  a view.

**Comment by eellison** [comment]
Wdym ?
