### ISSUE TITLE
Segmentation Fault in `2.0.1+rocm5.4.2` when creating a simple NN model

### ISSUE THREAD

**Issue by calvinp0** [pytorch/pytorch#106679]
### 🐛 Describe the bug

Hey, I have PyTorch with ROCM installed but whenever I attempt to run a simple model I have created, I receive either segmentation fault from a python script or a dead kernel in jupyter notebook.

The following class of my model is like so:

```python
class NonLinearRegModel(nn.Module):
    def __init__(self, in_features, out_features, hidden_layers: list = [5000, 1000, 500, 100], dropout: float = 0.5, activation: str = 'relu'):
        super(NonLinearRegModel, self).__init__()

        # List of activation functions
        activation_functions = {
            'relu': nn.ReLU(),
            'leaky_relu': nn.LeakyReLU(),
            'tanh': nn.Tanh(),
            'sigmoid': nn.Sigmoid(),
            'selu': nn.SELU(),
            'prelu': nn.PReLU()
        }
        
        # List to hold the layers
        self.layers = nn.ModuleList()
        
        # Initial First Layer
        # Layer: NonLinear -> BatchNorm -> Activation -> Dropout
        self.layers.append(nn.Linear(in_features, hidden_layers[0]))
        #self.layers.append(nn.LayerNorm(hidden_layers[0]))  # Rather than using BatchNorm1d as this normalises across the batch dimension, LayerNorm normalises across the feature dimension
        self.layers.append(nn.BatchNorm1d(hidden_layers[0]))
        self.layers.append(activation_functions[activation])
        self.layers.append(nn.Dropout(dropout))
        
        # Constructing intermediate hidden layers
        for i in range(len(hidden_layers) - 1):
            self.layers.append(nn.Linear(hidden_layers[i], hidden_layers[i+1]))
            self.layers.append(nn.BatchNorm1d(hidden_layers[i+1]))
            self.layers.append(activation_functions[activation])
            self.layers.append(nn.Dropout(dropout))
        
        # Final output layer
        self.layers.append(nn.Linear(hidden_layers[-1], out_features))
        
    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return x  
```

And when I attempt to train the model with this code:

```python
# Training Loop

# Init lists to store the losses and METRICS
train_losses = []
test_losses = []
train_maes = []
test_maes = []

train_mses = []
test_mses = []

train_r2s = []
test_r2s = []

for epoch in range(epochs):
    
    
    ### Training
    model_0.train()
    
    # 1. Forward Propagation
    y_pred = model_0(X_train)
    
    # 2. Loss Calculation
    loss = log_cosh_loss(y_pred, y_train)
    train_losses.append(loss.item())
    train_pred_np = y_pred.detach().cpu().numpy()
    train_true_np = y_train.detach().cpu().numpy()

    train_maes.append(mean_absolute_error(train_true_np, train_pred_np))
    train_mses.append(mean_squared_error(train_true_np, train_pred_np))
    train_r2s.append(r2_score(train_true_np, train_pred_np))
    
    # 3. Zero Grad Optimization
    optimizer.zero_grad()
    
    # 4. Backward Propagation
    loss.backward()
    
    # 5. Step Optimization
    optimizer.step()
    
    ### Validation
    model_0.eval() # set model to evaluation mode
    # 1. Forward Propagation
    with torch.no_grad():
        y_pred_test = model_0(X_test)
        
        # 2. Loss Calculation
        test_loss = log_cosh_loss(y_pred_test, y_test)
        test_losses.append(test_loss.item())  # Store test loss for this epoch
        test_pred_np = y_pred_test.detach().cpu().numpy()
        test_true_np = y_test.detach().cpu().numpy()

        test_maes.append(mean_absolute_error(test_true_np, test_pred_np))
        test_mses.append(mean_squared_error(test_true_np, test_pred_np))
        test_r2s.append(r2_score(test_true_np, test_pred_np))

    # Scheduler Step
    scheduler.step(test_loss)

    if epoch % 500 == 0:
        print(f'Epoch {epoch} | Train Loss: {train_losses[-1]} | Test Loss: {test_losses[-1]}')
        print(f'Train MAE: {train_maes[-1]} | Test MAE: {test_maes[-1]}')
        print(f'Train MSE: {train_mses[-1]} | Test MSE: {test_mses[-1]}')
        print(f'Train R^2: {train_r2s[-1]} | Test R^2: {test_r2s[-1]}')
        print("---------------------------------------------------")
```

I get the aforementioned error. I have also tried the nightly version of pytorch and get the same issue.

### Versions

PyTorch version: 2.0.1+rocm5.4.2
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.4.22803-474e8620

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)  [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Radeon RX 6600
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.4.22803
MIOpen runtime version: 2.19.0
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          20
On-line CPU(s) list:             0-19
Vendor ID:                       GenuineIntel
Model name:                      12th Gen Intel(R) Core(TM) i7-12700KF
CPU family:                      6
Model:                           151
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        2
CPU max MHz:                     5000.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7219.20
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       512 KiB (12 instances)
L1i cache:                       512 KiB (12 instances)
L2 cache:                        12 MiB (9 instances)
L3 cache:                        25 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-19
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton-rocm==2.0.1
[pip3] torch==2.0.1+rocm5.4.2
[pip3] torchaudio==2.0.2+rocm5.4.2
[pip3] torchvision==0.15.2+rocm5.4.2
[conda] nomkl                     1.0                  h5ca1d4c_0    conda-forge
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton-rocm       2.0.1                    pypi_0    pypi
[conda] torch                     2.0.1+rocm5.4.2          pypi_0    pypi
[conda] torchaudio                2.0.2+rocm5.4.2          pypi_0    pypi
[conda] torchvision               0.15.2+rocm5.4.2          pypi_0    pypi

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jithunnair-amd** [comment]
@calvin Please confirm this using `rocminfo | grep gfx`, but I think your GPU has a gfx arch of gfx1032. If so, there is currently no plan to directly add support for this architecture to Pytorch dockers/wheels. However, you might be able to make progress using `HSA_OVERRIDE_GFX_VERSION=10.3.0`

**Comment by calvinp0** [comment]
Hey @jithunnair-amd, you were absolutey right, I have gfx1032.

```bash
rocminfo | grep gfx
  Name:                    gfx1032                            
  Name:                    amdgcn-amd-amdhsa--gfx1032 
```

I set the environment variable to your recommendation and it worked! Thank you so much :)
