### ISSUE TITLE
Add .devcontainer to PyTorch and ensure local CPU development works

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#106714]
# Sumary

First step in this project: #106713 

## Status = Done
This support was added in this PR: https://github.com/pytorch/pytorch/pull/98252

**Comment by jlamperez** [comment]
Hi @drisspg thank you for adding this option.

I tried it in vscode but had problems because of Python 3.11 and conda dependencies.

If I replace the image with `mcr.microsoft.com/vscode/devcontainers/miniconda:0.202.25-3` that uses Python 3.10 it solves the dependency problem.

Regards,

**Comment by drisspg** [comment]
@jlamperez Thanks for the feedback, would you mind opening up a PR to make that change and I can review/merge 😄
