### ISSUE TITLE
conflict with fastText

### ISSUE THREAD

**Issue by techkang** [pytorch/pytorch#10676]
## Issue description

It seems that fastText is conflict with pytorch.

## Code example

```
import fastText   
import torch  
```

## System Info

`bash: 行 1: 15992 段错误 env "PYTHONUNBUFFERED"="1" "PYTHONPATH"="/root/.pycharm_helpers/pycharm_matplotlib_backend:/root/fastText:/root/fastText/ae:/root/fastText/temp" "PYCHARM_HOSTED"="1" "JETBRAINS_REMOTE_RUN"="1" "PYCHARM_MATPLOTLIB_PORT"="51582" "PYTHONIOENCODING"="UTF-8" /root/anaconda3/bin/python -u /root/fastText/temp.py`
[environment]
- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source): No
- OS: CentOS Linux 7 (Core)
- PyTorch version: 0.4.1
- Python version: 3.6.5
- CUDA/cuDNN version: No
- GPU models and configuration: No
- GCC version (if compiling from source): 4.8.5
- CMake version: 3.6.2
- Versions of any other relevant libraries:
  - fasttext 0.8.22

I substitute all `pip3` in collect_env.py to `pip` because I use anaconda and my command to use pip3 is pip.
```
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
CMake version: version 3.6.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.1)
[pip] torchfile (0.1.0)
[pip] torchnet (0.0.4)
[pip] torchvision (0.2.1)
[conda] faiss-cpu                 1.3.0            py36_cuda0.0_1    pytorch
[conda] torch                     0.4.1                     <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchnet                  0.0.4                     <pip>
[conda] torchvision               0.2.1                     <pip>
```

**Comment by zou3519** [comment]
How did you build fasttext?

**Comment by techkang** [comment]
I just follow the guide of fastText:
```
$ git clone https://github.com/facebookresearch/fastText.git
$ cd fastText
$ pip install .
```

**Comment by weiyangfb** [comment]
possibly related to https://github.com/pytorch/pytorch/issues/9129 ? Have you tried `compiled with gcc 4.9.2`? And can we get a gdb trace for
```
import fastText   
import torch  
```
