### ISSUE TITLE
[Inductor][cpu] torchbench model doctr_det_predictor perf regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#106770]
### 🐛 Describe the bug

**doctr_det_predictor** Perf regression tracked on https://github.com/pytorch/pytorch/issues/93531#issuecomment-1668825530

|   |  2023-08-06 nightly  |   |     |   |  2023-08-02 nightly  |   |     |   |  Result Comp  |     |   |
|  ---- |  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
|  model | batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|doctr_det_predictor	|1	|0.649268	 |3.384136689	|2.19721166	|1	|1.182882	 |1.861407945	|2.201825953	|0.55	|1	|0.55

2023-08-06 nightly
SW	| Nightly commit	| Main commit
-- | -- | --
Pytorch|[a8638d6](https://github.com/pytorch/pytorch/commit/a8638d6)|[](https://github.com/pytorch/pytorch/commit/)
Torchbench|/|[770d5cf7](https://github.com/pytorch/benchmark/commit/770d5cf7)
torchaudio|[dc83b38](https://github.com/pytorch/audio/commit/dc83b38)|[](https://github.com/pytorch/audio/commit/)
torchtext|[c11d758](https://github.com/pytorch/text/commit/c11d758)| [](https://github.com/pytorch/text/commit/)
torchvision|[58366ab](https://github.com/pytorch/vision/commit/58366ab)|[](https://github.com/pytorch/vision/commit/)
torchdata|[1d231d1](https://github.com/pytorch/data/commit/1d231d1)|[](https://github.com/pytorch/data/commit/)
dynamo_benchmarks|[f228c8b](https://github.com/pytorch/pytorch/commit/f228c8b)|/

2023-08-02 nightly
SW	| Nightly commit	| Main commit
-- | -- | --
Pytorch|[c89b169](https://github.com/pytorch/pytorch/commit/c89b169)|[92cac6b](https://github.com/pytorch/pytorch/commit/92cac6b)
Torchbench|/|[770d5cf7](https://github.com/pytorch/benchmark/commit/770d5cf7)
torchaudio|[dc83b38](https://github.com/pytorch/audio/commit/dc83b38)|[66f661d](https://github.com/pytorch/audio/commit/66f661d)
torchtext|[c11d758](https://github.com/pytorch/text/commit/c11d758)| [60bea66](https://github.com/pytorch/text/commit/60bea66)
torchvision|[58366ab](https://github.com/pytorch/vision/commit/58366ab)|[a6dea86](https://github.com/pytorch/vision/commit/a6dea86)
torchdata|[1d231d1](https://github.com/pytorch/data/commit/1d231d1)|[757c032](https://github.com/pytorch/data/commit/757c032)
dynamo_benchmarks|[f228c8b](https://github.com/pytorch/pytorch/commit/f228c8b)|/

### Versions

bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) multiple inference performance torchbench doctr_det_predictor float32 first static default 0

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @wconstab

**Comment by mlazos** [comment]
@ESI-SYD, has this been resolved?

**Comment by mlazos** [comment]
Closing, since this appears to be resolved, feel free to reopen if needed
