### ISSUE TITLE
[Dyanmo] Pre-allocate flag should be a ONNXRuntime inference session level attribute

### ISSUE THREAD

**Issue by wschin** [pytorch/pytorch#106869]
### 🚀 The feature, motivation and pitch

Now DORT stores pre-allocated flag in `OrtBackend.preallocate_output` which looks a bit more global than it can be. Because pre-allocated memory is not needed by all execution providers (e.g., CUDA execution provider doesn't need it). 

DORT PR: https://github.com/pytorch/pytorch/pull/106589

**Comment by MaanavD** [comment]
@wschin again, closing as PR was merged. Reopen if needed.
