### ISSUE TITLE
Build Debug PyTorch with OpenBLAS on Windows Arm64

### ISSUE THREAD

**Issue by cristianPanaite** [pytorch/pytorch#106848]
We need the Debug build of PyTorch on WoArm64 to be able to deeply investigate some test failures.
For this example, we are using OpenBLAS as BLAS/LAPACK implementation

## Steps to build PyTorch on Windows Arm64
1. Install git, Visual Studio 2022 or VS Build Tools 2022, Python 3.11 Arm64 with Debug binaries from [Python Releases for Windows | Python.org](https://www.python.org/downloads/windows/)
2. Open a CMD as admin
3. Open Arm64 Native Tools Command Prompt for VS2022
4. `git clone -–recursive -b develop https://github.com/xianyi/OpenBLAS.git` 
5. `cd OpenBLAS`
6. `mkdir build` 
7. `cd build` 
8. `cmake .. -G Ninja -DBUILD_TESTING=0`
9. `cmake --build . --config Debug`
10. `cmake --install . --prefix ../install`
11. `cd ../..`
12. `set BLAS=OpenBLAS`
13. `set OpenBLAS_HOME=your\path\to\OpenBLAS\install`
14. `set CMAKE_BUILD_TYPE=Debug`
15. `set LIB=your\path\to\Python\Python311\libs`
16. `git clone -–recursive -b run-tests https://github.com/Blackhex/pytorch.git` (this fork and branch contains some necessary changes for Windows Arm64 compatibility)
17. `cd pytorch`
18. `git submodule sync`
19. `git submodule update --init --recursive`
20. `pip install –r requirements.txt`
21. `python setup.py install`

#### Error
```
LINK : fatal error LNK1104: cannot open file 'python311_d.lib'
```

#### Solution
1. Verify you have debug binaries of Python installed
2. Don't forget about step number 15
-----
#### Error
```
C:\Users\AWE\Documents\pytorch_openBlas_debug\pytorch\functorch\csrc\dim\dim.cpp
C:\Users\AWE\AppData\Local\Programs\Python\Python311-arm64\include\internal/pycore_opcode.h(242): error C2143: syntax error: missing ']' before 'constant'
C:\Users\AWE\AppData\Local\Programs\Python\Python311-arm64\include\internal/pycore_opcode.h(242): error C3260: 'constant': skipping unexpected token(s) before lambda body
C:\Users\AWE\Documents\pytorch_openBlas_debug\pytorch\functorch\csrc\dim\dim.cpp(3255): fatal error C1004: unexpected end-of-file found
```
#### Solution: Not found yet

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex

**Comment by iremyux** [comment]
Closing this issue as it is no longer a priority. 
We managed to build Pytorch with APL on Arm64 and will be centering our focus around this.
