### ISSUE TITLE
[Dynamo] ONNXRuntime Backend Shold Allow External Allocator

### ISSUE THREAD

**Issue by wschin** [pytorch/pytorch#106867]
### 🚀 The feature, motivation and pitch

DORT (Dynamo-ONNXRuntime) creates inference session in DORT using the following code.

```
def _create_onnx_session(onnx_proto, eps: Tuple[str, ...], session_options):
    # TODO(wschin): enable external allocators.
    return onnxruntime.InferenceSession(
        onnx_proto, providers=eps, sess_options=session_options
    )
```

Since no external allocator is provided, ORT and PyTorch manage memory using different allocators. This can result higher memory peak, so we should pass PyTorch's allocator to ORT.

DORT PR: https://github.com/pytorch/pytorch/pull/106589

**Comment by MaanavD** [comment]
Associated PR was merged. Closing issue. @wschin feel free to reopen if needed.
