### ISSUE TITLE
[Dynam] a graph pass in Dynamo-ONNXRuntime backend needs revision

### ISSUE THREAD

**Issue by wschin** [pytorch/pytorch#106871]
### 🚀 The feature, motivation and pitch

A pass `_replace_to_copy_with_to` was added in the early days of dynamo development. As dynamo becomes more matured, we should try to remove this. If this is really needed, this should be implemented as a pass in ONNX exporter.

```
            # TODO(wschin): this is required for removing aten::_to_copy in _replace_to_copy_with_to.
            _replace_to_copy_with_to(prim_graph_module)
```

DORT PR: https://github.com/pytorch/pytorch/pull/106589

**Comment by MaanavD** [comment]
@wschin again, closing as PR was merged. Reopen if needed.
