### ISSUE TITLE
[Dynamo] Integration exporter's diagnostic system into ONNXRuntime backend

### ISSUE THREAD

**Issue by wschin** [pytorch/pytorch#106873]
### 🚀 The feature, motivation and pitch

As title. DORT doesn't have any diagnostic features, so reusing the system from ONNX exporter seems a good idea.

DORT PR: https://github.com/pytorch/pytorch/pull/106589

**Comment by MaanavD** [comment]
@wschin again, closing as PR was merged. Reopen if needed.
