### ISSUE TITLE
[Inductor][cpu] gptj6B & llama model perf regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#106945]
### 🐛 Describe the bug

<html>
<body>
<p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Result 1: use_dynamo = True</p>

Model | precision | cpp_wrapper | latency[1]/first_latency/avg_latency/p90_latency/p99_latency | lastsuccessful | ratio(last / current)
-- | -- | -- | -- | -- | --
gptj6B | bfloat16 | False | 5903.844,0.309,0.179,0.182,0.183 | 2900.329,0.239,0.083,0.086,0.088 | 0.49,0.77,0.46,0.47,0.48,
gptj6B | bfloat16 | True | 5890.007,0.306,0.179,0.181,0.183 | 2822.583,0.242,0.082,0.085,0.086 | 0.48,0.79,0.46,0.47,0.47,
llama7B | bfloat16 | False | 4571.566,0.226,0.139,0.143,0.144 | 3263.394,0.330,0.093,0.095,0.096 | 0.71,1.46,0.67,0.66,0.67,
llama7B | bfloat16 | True | 4593.618,0.227,0.140,0.143,0.144 | 3477.320,0.329,0.091,0.093,0.094 | 0.76,1.45,0.65,0.65,0.65,

</body>
</html>

For reproduce:

bash env_prepare.sh bfloat16 llm_bench_spr
[scripts](https://github.com/chuanqi129/inductor-tools/tree/yudong/groovy_new/scripts/llmbench)

### Versions

Pytorch: 	4734e4d
transformers: 	4.31.0
TORCH_VISION: 	ffdb719
TORCH_TEXT: 	3f2c002
TORCH_AUDIO: 	ed89176
TORCH_DATA: 	76bcef9
TORCH_BENCH: 	0b7147fd

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by XiaobingSuper** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/107123.
