### ISSUE TITLE
[Inductor][cpu][]static cppwrapper] torchbench model squeezenet1_1 perf regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#106964]
### 🐛 Describe the bug

tracked on https://github.com/pytorch/pytorch/issues/93531#issuecomment-1669541354

|   |  2023-08-06 nightly  |   |     |   |  2023-07-30 nightly  |   |     |   |  Result Comp  |     |   |
|  ---- |  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
|  model | batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|squeezenet1_1	|16	|1.936166	 |0.008108466	|0.015699336	|16	|2.888515	 |0.005393675	|0.015579711	|0.67	|0.99	|0.67

2023-08-06 nightly
SW	| Nightly commit	| Main commit
-- | -- | --
Pytorch|[a8638d6](https://github.com/pytorch/pytorch/commit/a8638d6)|[](https://github.com/pytorch/pytorch/commit/)
Torchbench|/|[770d5cf7](https://github.com/pytorch/benchmark/commit/770d5cf7)
torchaudio|[dc83b38](https://github.com/pytorch/audio/commit/dc83b38)|[](https://github.com/pytorch/audio/commit/)
torchtext|[c11d758](https://github.com/pytorch/text/commit/c11d758)| [](https://github.com/pytorch/text/commit/)
torchvision|[58366ab](https://github.com/pytorch/vision/commit/58366ab)|[](https://github.com/pytorch/vision/commit/)
torchdata|[1d231d1](https://github.com/pytorch/data/commit/1d231d1)|[](https://github.com/pytorch/data/commit/)
dynamo_benchmarks|[f228c8b](https://github.com/pytorch/pytorch/commit/f228c8b)|/

2023-07-30 nightly
SW information:

SW	| Nightly commit	| Main commit
-- | -- | --
Pytorch|[0ff243f](https://github.com/pytorch/pytorch/commit/0ff243f)|[858ca65](https://github.com/pytorch/pytorch/commit/858ca65)
Torchbench|/|[770d5cf7](https://github.com/pytorch/benchmark/commit/770d5cf7)
torchaudio|[dc83b38](https://github.com/pytorch/audio/commit/dc83b38)|[66f661d](https://github.com/pytorch/audio/commit/66f661d)
torchtext|[c11d758](https://github.com/pytorch/text/commit/c11d758)| [60bea66](https://github.com/pytorch/text/commit/60bea66)
torchvision|[58366ab](https://github.com/pytorch/vision/commit/58366ab)|[a6dea86](https://github.com/pytorch/vision/commit/a6dea86)
torchdata|[1d231d1](https://github.com/pytorch/data/commit/1d231d1)|[757c032](https://github.com/pytorch/data/commit/757c032)
dynamo_benchmarks|[f228c8b](https://github.com/pytorch/pytorch/commit/f228c8b)|/

### Versions

bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) multiple inference performance torchbench squeezenet1_1  float32 first static cpp 0

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by chunyuan-w** [comment]
The regression is caused by https://github.com/pytorch/pytorch/pull/105173.
It's not specific to cpp wrapper. Default wrapper will also have this regression.

It's caused by this change of `return clone(x)`. Before this PR, it is `return x`.
https://github.com/pytorch/pytorch/blob/384e0d104fd077d31efafc564129660e9b7a0f25/torch/_inductor/lowering.py#L494-L497

**Comment by chunyuan-w** [comment]
@ESI-SYD I checked the report on 0828 and the regression has been fixed. Could you please help confirm and close this issue if that's the case?

**Comment by ESI-SYD** [comment]
Comeback to 0.005462357, closing
