### ISSUE TITLE
[Inductor][cpu][]dynamic shape] timms model tf_mixnet_l perf regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#106962]
### 🐛 Describe the bug

**tf_mixnet_l** Perf regression tracked on https://github.com/pytorch/pytorch/issues/93531#issuecomment-1672396290

|   |  2023-08-07 nightly  |   |     |   |  2023-07-30 nightly  |   |     |   |  Result Comp  |     |   |
|  ---- |  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
|  model | batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|tf_mixnet_l	|1	|0.905778	 |0.044584924	|0.040384043	|1	|1.205404	 |0.033378007	|0.040233983	|0.75	|1	|0.75

2023-08-07 nightly
torchbench : 770d5cf7
torch :  2.1.0a0+git5e438d5
torchvision :  0.16.0a0+128d52a
torchtext :  0.16.0a0+f3ca0c4
torchaudio :  2.1.0a0+618aad9
torchdata :  0.7.0a0+484a3c8
dynamo_benchmarks : nightly

2023-07-30 nightly 
torchbench : 561abe38
torch :  2.1.0a0+git6298ac6
torchvision :  0.16.0a0+4af3309
torchtext :  0.16.0a0+c8fbcc9
torchaudio :  2.1.0a0+df62414
torchdata :  0.7.0a0+d583269
dynamo_benchmarks : nightly

### Versions

bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) single inference performance timm_models tf_mixnet_l float32 first dynamic default 0

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by chunyuan-w** [comment]
@ESI-SYD I checked the report on 0828 and the regression has been fixed (seems related with this PR https://github.com/pytorch/pytorch/pull/107640). Could you please help confirm and close this issue if that's the case?
