### ISSUE TITLE
torch.stack on torch.Tensor subclass

### ISSUE THREAD

**Issue by apadhiUCLS** [pytorch/pytorch#106982]
### 🐛 Describe the bug

I'm trying to make a tensor subclass that has an extra instance attribute to store data, and I need to store multiple of these subclass objects in a tensor. When I use `torch.stack` to store them, the elements of the stacked tensor no longer have the extra attribute that they were assigned.

Do you know how we can store multiple of these subclass objects in a tensor (or in a subclass of a tensor) while preserving the extra attributes?

Thank you for your help!

```
class tensorExtra(torch.Tensor):
    
    @staticmethod
    def __new__(cls, extra, *args, **kwargs):
        obj = super()._make_subclass(cls, torch.tensor([1,1]), *args, **kwargs)
        obj.__init__(extra)
        return obj
        
    
    def __init__(self, extra):
        self.extra=extra
        
obj1=tensorExtra("abc")
obj2=tensorExtra("def")
list_of_objs=[obj1,obj2]
stacked=torch.stack(list_of_objs)

print(obj1.extra)
print(stacked[0].extra)
```

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.4 (arm64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.11)
CMake version: version 3.27.1
Libc version: N/A

Python version: 3.9.17 (main, Jul  5 2023, 15:44:56)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-11.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] numpydoc==1.5.0
[pip3] torch==2.0.1
[pip3] torch_geometric==2.4.0
[pip3] torch-scatter==2.1.1
[pip3] torch-sparse==0.6.17
[pip3] torchaudio==2.0.2
[pip3] torchmetrics==1.0.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.15.2
[conda] numpy                     1.24.3           py39h1398885_0  
[conda] numpy-base                1.24.3           py39h90707a3_0  
[conda] numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
[conda] pytorch                   2.0.1           gpu_mps_py39h20d1048_0  
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torch-scatter             2.1.1                    pypi_0    pypi
[conda] torch-sparse              0.6.17                   pypi_0    pypi
[conda] torchaudio                2.0.2                    pypi_0    pypi
[conda] torchmetrics              1.0.1                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

**Comment by jbschlosser** [comment]
> When I use torch.stack to store them, the elements of the stacked tensor no longer have the extra attribute that they were assigned.

Note that `torch.stack()` returns a *new* tensor consisting of the concatenated elements.

I'm not quite sure how you want the attributes to be preserved, but you can customize the behavior of torch.* functions using `__torch_function__` on your subclass (see [Extending PyTorch](https://pytorch.org/docs/stable/notes/extending.html) for more info).

```python
class tensorExtra(torch.Tensor):
    ...

    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}
        output = super().__torch_function__(func, types, args, kwargs)
        if func is torch.stack:
            # store a list of extra attributes from each of the stack args
            output.extra = [arg.extra for arg in args[0] if isinstance(arg, tensorExtra)]
        return output
```

```python
stacked = torch.stack([tensorExtra('abc'), tensorExtra('def')])
print(stacked.extra)  # ['abc', 'def'] 
```

I'll also point you to the [PyTorch forums](https://discuss.pytorch.org/), where we recommend this sort of question be discussed. Note that the issues here are reserved for problems within PyTorch itself. Closing for now but please feel free to reopen if you identify some issue within PyTorch.

**Comment by apadhiUCLS** [comment]
Thank you for your help!
