### ISSUE TITLE
[Inductor][cpu][]dynamic shape] torchbench model densenet121 perf regression with cppwrapper

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#106963]
### 🐛 Describe the bug

tracked on https://github.com/pytorch/pytorch/issues/93531#issuecomment-1668942966

|   |  2023-08-06 nightly  |   |     |   |  2023-07-30 nightly  |   |     |   |  Result Comp  |     |   |
|  ---- |  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
|  model | batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
| densenet121	|64	|1.472447	 |0.247399298	|0.364282354	|64	|1.811041	 |0.200867155	|0.363778653	|0.81	|1	|0.81

2023-08-06 nightly 
SW	| Nightly commit	| Main commit
-- | -- | --
Pytorch|[a8638d6](https://github.com/pytorch/pytorch/commit/a8638d6)|[](https://github.com/pytorch/pytorch/commit/)
Torchbench|/|[770d5cf7](https://github.com/pytorch/benchmark/commit/770d5cf7)
torchaudio|[dc83b38](https://github.com/pytorch/audio/commit/dc83b38)|[](https://github.com/pytorch/audio/commit/)
torchtext|[c11d758](https://github.com/pytorch/text/commit/c11d758)| [](https://github.com/pytorch/text/commit/)
torchvision|[58366ab](https://github.com/pytorch/vision/commit/58366ab)|[](https://github.com/pytorch/vision/commit/)
torchdata|[1d231d1](https://github.com/pytorch/data/commit/1d231d1)|[](https://github.com/pytorch/data/commit/)
dynamo_benchmarks|[f228c8b](https://github.com/pytorch/pytorch/commit/f228c8b)|/

2023-07-30 nightly 
SW information:

SW	| Nightly commit	| Main commit
-- | -- | --
Pytorch|[0ff243f](https://github.com/pytorch/pytorch/commit/0ff243f)|[858ca65](https://github.com/pytorch/pytorch/commit/858ca65)
Torchbench|/|[770d5cf7](https://github.com/pytorch/benchmark/commit/770d5cf7)
torchaudio|[dc83b38](https://github.com/pytorch/audio/commit/dc83b38)|[66f661d](https://github.com/pytorch/audio/commit/66f661d)
torchtext|[c11d758](https://github.com/pytorch/text/commit/c11d758)| [60bea66](https://github.com/pytorch/text/commit/60bea66)
torchvision|[58366ab](https://github.com/pytorch/vision/commit/58366ab)|[a6dea86](https://github.com/pytorch/vision/commit/a6dea86)
torchdata|[1d231d1](https://github.com/pytorch/data/commit/1d231d1)|[757c032](https://github.com/pytorch/data/commit/757c032)
dynamo_benchmarks|[f228c8b](https://github.com/pytorch/pytorch/commit/f228c8b)|/

### Versions

bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) multiple inference performance torchbench densenet121 float32 first dynamic cpp 0

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by chunyuan-w** [comment]
Same as issue https://github.com/pytorch/pytorch/issues/106964: the regression is caused by https://github.com/pytorch/pytorch/pull/105173.
It's not specific to cpp wrapper. Default wrapper will also have this regression.

**Comment by chunyuan-w** [comment]
@ESI-SYD I checked the report on 0828 and the regression has been fixed. Could you please help confirm and close this issue if that's the case?

**Comment by ESI-SYD** [comment]
comeback to 0.184018458, closing
