### ISSUE TITLE
ROCm CI upgrade in progress

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#106919]
ROCm CI runners are being upgraded for hardware/software in a phased manner. This might impact your CI runs on ROCm.

## Current Status
Ongoing. If your ROCm CI runs get abruptly killed due to a runner being rebooted as part of the upgrade, please retrigger the ROCm CI using a rebase.
NOTE: ROCm CI is currently in the "unstable" category.

## Error looks like
Abrupt end of output for the ROCm CI log

## Incident timeline (all times pacific)
Started Aug 10 

## User impact
ROCm CI jobs will be disrupted

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
Routine SW upgrade as part of runner maintenance

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by linuxreitt** [comment]
For those of us having wasted a good ammount of our lives attempting to get our AMD more bark than bite, good for nothing GPU's to do something other than Gaming, it would be nice to see some development now that AMD have finally put forward some ROCm for Windows, I notice that the PyTorch get started pages still has not aknowledged anything of the sort exists!
<img width="403" alt="Pytorch" src="https://github.com/pytorch/pytorch/assets/124739751/c14b90b7-c728-4cca-b736-42b8e915ac00">

**Comment by malfet** [comment]
@jithunnair-amd is this still ongoing? If not, should we perhaps change it from a SEV to a high-priority issue?

**Comment by jithunnair-amd** [comment]
@malfet This SEV is for a very specific ROCm CI driver upgrade task, just to indicate to developers that ROCm CI is undergoing an upgrade. We're still working on the upgrade.

**Comment by jeffdaily** [comment]
ROCm CI driver upgrade is completed.
