### ISSUE TITLE
Trainable parameter

### ISSUE THREAD

**Issue by kiratben** [pytorch/pytorch#106948]
### 🚀 The feature, motivation and pitch

Hi,
How can I integrate a trainable parameter ranging from 2 to 10 using Torch? This parameter doesn't directly participate in the output operations, but its updates need to be maintained during training.

**Comment by jbschlosser** [comment]
Hey @kiratben! This question is better suited to the [PyTorch forums](https://discuss.pytorch.org/), as you'll have better luck receiving assistance there. Note that the issues here are reserved for problems within PyTorch itself. Closing for now but feel free to reopen if an issue within PyTorch is identified.
