### ISSUE TITLE
[feature request] [onnx] Support QuantLinear/DequantLinear float16 inputs (opset19 and maybe "backport"-support them for opset17)

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#107023]
### 🚀 The feature, motivation and pitch

They added standardized support for float16 inputs for QuantLinear/DequantLinear: https://github.com/onnx/onnx/blob/main/docs/Changelog.md#QuantizeLinear-19 and https://github.com/onnx/onnx/blob/main/docs/Changelog.md#dequantizelinear-19

When doing a hack to force it to be float16, got `UserWarning: The exported ONNX model failed ONNX shape inference.The model will not be executable by the ONNX Runtime.If this is unintended and you believe there is a bug,please report an issue at https://github.com/pytorch/pytorch/issues.Error reported by strict ONNX shape inference: [ShapeInferenceError] (op_type:QuantizeLinear, node name: /qkv/_input_quantizer/QuantizeLinear): x typestr: T1, has unsupported type: tensor(float16) (Triggered internally at /opt/pytorch/pytorch/torch/csrc/jit/serialization/export.cpp:1410.)`

Related: https://github.com/pytorch/pytorch/issues/102430

**Comment by vadimkantorov** [comment]
Discovered when trying to make work NVidia's `pytorch_quantization` which uses onnx as intermediate representation and uses torch's fakequant functions

cc @ttyio 
OP: https://github.com/NVIDIA/TensorRT/issues/3095#issuecomment-1672980900

**Comment by vadimkantorov** [comment]
Also, the latest supported opset of 16 is quite outdated, no?

<img width="618" alt="image" src="https://github.com/pytorch/pytorch/assets/1041752/e4ad909a-b28e-43e3-9e97-ef991c2801e0">

**Comment by vadimkantorov** [comment]
Or maybe float16 inputs for Quant/DequantLinear somehow can be hackily enabled for opset 17? (as opsets >17 will not be supported in old exporter torch.onnx.export)

**Comment by Mirian-Hipolito** [comment]
I am facing the same problem, is there any workaround?

**Comment by vadimkantorov** [comment]
My workaround was exporting fp32 model to onnx, and then handling/setting up its quantization/conversion to float16 with TRT

Another workaround might be moving on from torch.onnx.export to torch.onnx.dynamo_export, but it's likely not very stable

**Comment by MaanavD** [comment]
Closing the issue now! @vadimkantorov dynamo export should be more stable now, so feel free to test using that if necessary. 

Also tagging @Mirian-Hipolito
