### ISSUE TITLE
Apply fusion more aggressively in NAdam and Adagrad compilation

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#107006]
### 🚀 The feature, motivation and pitch

Currently NAdam compiles to > 5 kernels and Adagrad does as well. See https://github.com/pytorch/pytorch/blob/4df84c3b4d93ea53c9ca169f32a0dc4619bee797/test/inductor/test_compiled_optimizers.py#L4

for current kernel counts. Ideally these should fully fuse, but likely there are issues due to the presence of mutation. A good place to start is https://github.com/pytorch/pytorch/blob/4df84c3b4d93ea53c9ca169f32a0dc4619bee797/torch/_inductor/scheduler.py#L4

Specifically https://github.com/pytorch/pytorch/blob/4df84c3b4d93ea53c9ca169f32a0dc4619bee797/torch/_inductor/scheduler.py#L644

Ideally the rules should be able to be modified to soundly allow these to fuse fully. 

Contact @mlazos for more details

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @wconstab @Xia-Weiwen @ngimel

**Comment by Idank96** [comment]
@mlazos
Can you provide a code example that utilizes this function with NAdam or Adagrad?
or did you meant that by running the test files you mentioned I will get the relvant outputs (> 5 kernels ) that utilize the method can_fuze?
Thanks

**Comment by mlazos** [comment]
> @mlazos Can you provide a code example that utilizes can_fuze() with NAdam or Adagrad? or did you meant that by running the test files you mentioned I will get the relvant outputs (> 5 kernels ) that utilize the method can_fuze? How to run the test? with pytest? Thanks

Yeah that test file should have code that you can run with pytest or unittest. The number of kernels for NAdam and Adagrad are currently set to 5, if you set a breakpoint in can_fuse you'll see that it gets called a few times. And you'll have to figure out exactly why it's returning false more often than we expect.

**Comment by Idank96** [comment]
I can't run the test for some reason... Is it possible that it's not compatible with Windows? I am update here:  https://github.com/pytorch/pytorch/issues/108300
In short if `(HAS_CPU or HAS_CUDA) and not TEST_WITH_ROCM` (test_compiled_optimizers.py) is returned False and also the function `make_test` which is @requires_cuda() function is not executed.
although my system  versions has cuda installed:
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY

**Comment by jon-chuang** [comment]
Hello @mlazos, I would like to tackle this issue, as part of my investigations into Inductor scheduler and AOTAutograd behaviour in the presence of mutations.

---

### Discussion

Firstly I would like to note that NAdam is behaving same as Adam now (kernel_count=2). I am still left wondering where the decision not to fuse into a single kernel is made.

rprop, rmsprop and adadelta are optimized (kernel_count=1).

Adagrad is poor as before (kernel_count=5) while ASGD without for_each is the poorest (kernel_count=12) and decent otherwise (kernel_count=2).

Hence, I will be focusing my investigations on:
1. Fusing Adagrad
2. Since Adam is very popular, figure out of kernel_count=2 is in fact the right decision.

**Comment by jon-chuang** [comment]
Adagrad:
![model___9](https://github.com/pytorch/pytorch/assets/9093549/af42c2b1-c0e8-479c-b8a0-2f687a9540a4)

Adam/NAdam
![out](https://github.com/pytorch/pytorch/assets/9093549/1610db57-ed91-45c5-b105-dce6766e037e)



Seems like something to do with `fused__foreach`. The horizontal fusions are not happening for for each.

**Comment by jon-chuang** [comment]
adagrad
![model___9](https://github.com/pytorch/pytorch/assets/9093549/24221d84-45d5-424c-8aee-d7e486f812e2)
adam
![out](https://github.com/pytorch/pytorch/assets/9093549/f9b89a65-4c02-4ea9-9a9a-05a58fa253ff)

Seems that the issue lies with trying to horizontally fuse foreach kernels.

**Comment by jon-chuang** [comment]
Updates: 
### **Adagrad case:**
found root case - some params did not follow inputs' device.

### **num_kernels=2 case (Adam, NAdam, AdamW, Adagrad, ASGD):**
Seems to have to do with a `numel` mismatch in fusing foreach kernels. I have a feeling this can be overcome somehow (I am not sure if the heuristics are right i.e. the fusion is actually bad, or if the heuristics are too strict).

**Comment by mlazos** [comment]
@jon-chuang yeah sorry I was on vacation last week. You're correct, basically we do not allow fusion with kernels where there is a numel mismatch.  One potential solutions are to enable a single element kernel to be fused with downstream kernels in the scheduler.
