### ISSUE TITLE
Default sharding leads to timeouts

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#107037]
### 🐛 Describe the bug

While deprecating bionic and gcc7 I often run into a problem, when default shards are so unbalanced that they timeout.
For example, I don't think one can make any changes to the PyTorch codebase to fix cross-ref timeout other than push a fake stats into `test-infa` akin to https://github.com/pytorch/test-infra/commit/495a121bbe498c816dbdc243114ef3eb4b2690c5 (thanks @clee2000 for showing the way)
(i.e in the HUD cross-ref shards take 2 hours respectively (see https://github.com/pytorch/pytorch/actions/runs/5830936375/job/15813709064 and https://github.com/pytorch/pytorch/actions/runs/5830936375/job/15813711682 ), but in my PR, that could not rely on any previous runs one shard finishes in 35 min (https://github.com/pytorch/pytorch/actions/runs/5829238891/job/15808879569) while other times out/barely makes it ( https://github.com/pytorch/pytorch/actions/runs/5829238891/job/15808879453 )

I don't have an actionable proposal here, but imo it would be nice to come up with plan of sorts

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Even more egregious example:
- for `linux-focal-cuda12.1-py3.10-gcc9 / test` 4 shards out of 5 finish in 30 min, while fifth (1st one) times out after running for 5 hours. See [linux-focal-cuda12.1-py3.10-gcc9 / test (default, 2, 5, linux.4xlarge.nvidia.gpu)](https://github.com/pytorch/pytorch/actions/runs/5829238891/job/15809781893#logs) vs https://github.com/pytorch/pytorch/actions/runs/5829238891/job/15809781764

**Comment by huydhn** [comment]
I think we could make it so that if test time is not available on a config, fallback to any other config with the same number of shards. They will run and rebalance after a day

**Comment by huydhn** [comment]
> @huydhn, are you implying that it's a lack of test times stored that's causing the unbalanced sharding? If so, is that because the tests with unknown times are new, or that we just don't emit times for those jobs?

Yup, that's the root cause I think. This happens when you create a new config, i.e. moving from `cuda11.8` to `cuda12.1`.  The name changes, so the code couldn't find the test time for the new `cuda12.1` to balance shards properly.  What @clee2000 has done is manually taking existing values from `cuda11.8` (I assume) and rebrand it with new entries for `cuda12.1`.  The proposal here is to let the sharding code does that instead.

**Comment by clee2000** [comment]
As Huy suggested, I added a set of default times to fall back on if the build env/test config doesn't exist.  While the default might not always be representative of the actual times, it should be better that round robin distributing tests. 
https://github.com/pytorch/pytorch/pull/107325
https://github.com/pytorch/test-infra/pull/4476
