### ISSUE TITLE
Exception when using LayerNorm

### ISSUE THREAD

**Issue by funkyp1ckle** [pytorch/pytorch#107088]
### 🐛 Describe the bug

https://stackoverflow.com/questions/76766586/how-to-use-layernorm-in-libtorch

### Versions

libtorch stable 2.0.1 downloaded from https://pytorch.org/get-started/locally/ with cuda 11.8.

**Comment by colesbury** [comment]
We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org
