### ISSUE TITLE
Doc for dtensor?

### ISSUE THREAD

**Issue by HongLouyemeng** [pytorch/pytorch#107029]
### 🚀 The feature, motivation and pitch

I noticed that torch dtensor has been released, is there a revised standard documentation for dtensor  related API?😊

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

**Comment by H-Huang** [comment]
cc @wanchaol

**Comment by wanchaol** [comment]
@HongLouyemeng Thanks for the interest on DTensor! Sorry so far we haven't got time to publish docs or tutorials yet, we'll have better documentation later this year or so, there're two documentation at this point:
- pytorch tensor parallel API documentation (uses DTensor) https://pytorch.org/docs/main/distributed.tensor.parallel.html
- a bare minimum README inside dtensor directory https://github.com/pytorch/pytorch/tree/main/torch/distributed/_tensor

Feel free to experiment with it and feedbacks are welcomed :) If you have more questions or needs more in-depth discussions, please reach out on the PyTorch Slack channel

**Comment by HongLouyemeng** [comment]
> @HongLouyemeng Thanks for the interest on DTensor! Sorry so far we haven't got time to publish docs or tutorials yet, we'll have better documentation later this year or so, there're two documentation at this point:
> 
> * pytorch tensor parallel API documentation (uses DTensor) https://pytorch.org/docs/main/distributed.tensor.parallel.html
> * a bare minimum README inside dtensor directory https://github.com/pytorch/pytorch/tree/main/torch/distributed/_tensor
> 
> Feel free to experiment with it and feedbacks are welcomed :) If you have more questions or needs more in-depth discussions, please reach out on the PyTorch Slack channel

Hi,I found a lot of test files in the test directory, can I use them as a reference to learn how to use dtensor?😊https://github.com/pytorch/pytorch/tree/main/test/distributed/_tensor

**Comment by HongLouyemeng** [comment]
Hi,Will c10d have standard documentation this year?https://github.com/pytorch/pytorch/blob/main/torch/distributed/distributed_c10d.py#L3883

**Comment by HongLouyemeng** [comment]
> @HongLouyemeng Thanks for the interest on DTensor! Sorry so far we haven't got time to publish docs or tutorials yet, we'll have better documentation later this year or so, there're two documentation at this point:
> 
> * pytorch tensor parallel API documentation (uses DTensor) https://pytorch.org/docs/main/distributed.tensor.parallel.html
> * a bare minimum README inside dtensor directory https://github.com/pytorch/pytorch/tree/main/torch/distributed/_tensor
> 
> Feel free to experiment with it and feedbacks are welcomed :) If you have more questions or needs more in-depth discussions, please reach out on the PyTorch Slack channel

@wanchaol,HI,  Will torch make big changes to dtensor **before the docs are released?**

**Comment by HongLouyemeng** [comment]
question update https://github.com/pytorch/pytorch/issues/108974

**Comment by wanchaol** [comment]
> 
> @wanchaol,HI, Will torch make big changes to dtensor **before the docs are released?** In other words, is the current dtensor a **stable version**?

@HongLouyemeng sorry for the late reply. DTensor is currently in prototype release and we might make big changes if needed, but I think currently the public APIs are becoming relatively stable, so I don't expect to make drastic changes to our public APIs.

**Comment by HongLouyemeng** [comment]
> > @wanchaol,HI, Will torch make big changes to dtensor **before the docs are released?** In other words, is the current dtensor a **stable version**?
> 
> @HongLouyemeng sorry for the late reply. DTensor is currently in prototype release and we might make big changes if needed, but I think currently the public APIs are becoming relatively stable, so I don't expect to make drastic changes to our public APIs.

I found that the current dtensor doesn't meet the needs of distributed linear algebra, do you think this is the right conclusion of dtensor? mpi ecology does quite a bit of distributed linear algebra work

**Comment by HongLouyemeng** [comment]
> @HongLouyemeng Thanks for the interest on DTensor! Sorry so far we haven't got time to publish docs or tutorials yet, we'll have better documentation later this year or so, there're two documentation at this point:
> 
> * pytorch tensor parallel API documentation (uses DTensor) https://pytorch.org/docs/main/distributed.tensor.parallel.html
> * a bare minimum README inside dtensor directory https://github.com/pytorch/pytorch/tree/main/torch/distributed/_tensor
> 
> Feel free to experiment with it and feedbacks are welcomed :) If you have more questions or needs more in-depth discussions, please reach out on the PyTorch Slack channel

Hi, WanChao,I'm in the process of adding coo all_gather to pytorch, and I have some  discussions about how to contact you
<img width="1076" alt="image" src="https://github.com/pytorch/pytorch/assets/48181529/5b154d8c-2fbb-41fe-b323-524bbe9a5aa3">
