### ISSUE TITLE
[regression] nn.MultiheadAttention does not respect adding of floating point mask to attention for the fast path

### ISSUE THREAD

**Issue by HELLORPG** [pytorch/pytorch#107084]
### 🐛 Describe the bug

As in the title, something is wrong when inference nn.MultiheadAttention by float masks.

Here is my code:

```python
import torch
import torch.nn as nn

my_attn = nn.MultiheadAttention(
    embed_dim=256,
    batch_first=True,
    num_heads=8
)
my_attn = my_attn.to("cuda")

x = torch.randn((1, 10, 256), dtype=torch.float, device="cuda")
bool_mask = torch.ones((10, 10), dtype=torch.bool, device="cuda")
bool_mask[:2, :2] = False
bool_mask[2:, 2:] = False

float_mask = torch.randn((10, 10), dtype=torch.float, device="cuda")

my_attn.eval()
with torch.no_grad():
    bool_mask_res, bool_mask_scores = my_attn(
        query=x, key=x, value=x, attn_mask=bool_mask
    )
    print(bool_mask_scores)
    
    float_mask_res, float_mask_scores = my_attn(
        query=x, key=x, value=x, attn_mask=float_mask
    )
    print(float_mask_scores)       # NOTE: the bug is here, the scores will be all 'nan'.
```

The `bool_mask_scores` looks fine, but the `float_mask_scores` is filled with `nan`, and raises a UserWarning:
```
torch/nn/modules/activation.py:1160: UserWarning: Converting mask without torch.bool dtype to bool; this will negatively affect performance. Prefer to use a boolean mask directly. (Triggered internally at /opt/conda/conda-bld/pytorch_1682343995026/work/aten/src/ATen/native/transformers/attention.cpp:150.)
  return torch._native_multi_head_attention(
```
It seems that the `float_mask` is regarded as a bool mask thus causing this nan error. BTW, although the bool mask works correctly, it will raise the same UserWarning!

I see the [documents](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html), knowing that the above code will be processed by the new function `scaled_dot_product_attention()`. 

I try to avoid using this new function by pretending not to be a self-attention module:
```python
import torch
import torch.nn as nn

my_attn = nn.MultiheadAttention(
    embed_dim=256,
    batch_first=True,
    num_heads=8
)
my_attn = my_attn.to("cuda")

x = torch.randn((1, 10, 256), dtype=torch.float, device="cuda")
bool_mask = torch.ones((10, 10), dtype=torch.bool, device="cuda")
bool_mask[:2, :2] = False
bool_mask[2:, 2:] = False

float_mask = torch.randn((10, 10), dtype=torch.float, device="cuda")

my_attn.eval()

with torch.no_grad():
    bool_mask_res, bool_mask_scores = my_attn(
        query=x.clone(), key=x, value=x, attn_mask=bool_mask    # Just use .clone()
    )
    print(bool_mask_scores)
    
    float_mask_res, float_mask_scores = my_attn(
        query=x.clone(), key=x, value=x, attn_mask=float_mask    # Just use .clone()
        #
    )
    print(float_mask_scores)
```
And it works! Both `bool_mask` and `float_mask` now work well without any UserWarning.

I'm wondering if this represents some problem about `scaled_dot_product_attention()`? Or am I misunderstanding?

Thanks a lot!!

P.S.
I also try the Nightly version, but it still doesn't work. And pytorch 1.13.1 doesn't have this problem.

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 3080 Ti

Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 9 5900X 12-Core Processor
CPU family:                      25
Model:                           33
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     3700.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        7399.19
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       384 KiB (12 instances)
L1i cache:                       384 KiB (12 instances)
L2 cache:                        6 MiB (12 instances)
L3 cache:                        64 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.0
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.6           py310h1128e8f_1  
[conda] mkl_random                1.2.2           py310h1128e8f_1  
[conda] numpy                     1.25.0          py310h5f9d8c6_0  
[conda] numpy-base                1.25.0          py310hb5e798b_0  
[conda] pytorch                   2.0.1           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2               py310_cu118    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.2              py310_cu118    pytorch
```[tasklist]
### Tasks
```

cc @ezyang @gchanan @zou3519 @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @bhosmer @cpuhrsch @erichan1 @drisspg

**Comment by mikaylagawarecki** [comment]
> BTW, although the bool mask works correctly, it will raise the same UserWarning!

The reason for this is because `_canonical_mask` always converts the bool mask to a float mask

> I try to avoid using this new function by pretending not to be a self-attention module:
The reason why adding a `.clone()` appears to fix it is because [when qkv are not the same tensor, the fast path is not used](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/activation.py#L1134-L1138), which avoids the path that causes this bug.

For some context, to others reading this the issue with nans is in the math path for SDPA. 

 When you create your float mask with `torch.randn` it eventually gets converted to a bool mask here https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/transformers/attention.cpp#L151-L153, because no value in the float mask is exactly 0, we have a mask of all ones --> we are telling the `masked_softmax` to mask **everything** out!

What `masked_softmax` does is to [fill all masked positions in the input with `-inf`](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cuda/SoftMax.cu#L1023). Which leads to the following issue mentioned in https://github.com/pytorch/pytorch/issues/106545 (i.e. softmax along a row of all `-inf` gives `nans`)

```
>>> x = torch.tensor([-float('inf')] * 2)
>>> x.softmax(-1)
tensor([nan, nan])
>>> x.cuda().softmax(-1)
tensor([nan, nan], device='cuda:0')
```

Hence, you are seeing nans.

However, this isn't a problem unique to the float mask. If I did the same thing you did for bool masks where I set some values in the mask to 0, we would no longer see nans. For example, try this!

```
import torch
import torch.nn as nn

my_attn = nn.MultiheadAttention(
    embed_dim=256,
    batch_first=True,
    num_heads=8
)
my_attn = my_attn.to("cuda")

x = torch.randn((1, 10, 256), dtype=torch.float, device="cuda")
bool_mask = torch.ones((10, 10), dtype=torch.bool, device="cuda")
bool_mask[:2, :2] = False
bool_mask[2:, 2:] = False

float_mask = torch.randn((10, 10), dtype=torch.float, device="cuda")
float_mask[:2, :2] = 0
float_mask[2:, 2:] = 0

my_attn.eval()
with torch.no_grad():
    bool_mask_res, bool_mask_scores = my_attn(
        query=x, key=x, value=x, attn_mask=bool_mask
    )
    print(bool_mask_scores)

    float_mask_res, float_mask_scores = my_attn(
        query=x, key=x, value=x, attn_mask=float_mask
    )
    print(float_mask_scores)  # no longer all nan :)
```

**Comment by HELLORPG** [comment]
Thanks for your reply. 

But I wonder to know why the float mask has been converted to a bool mask? [I read the document](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html), it tells me that the float mask is applied by adding to the attention weight without converting. **Thus although I do not set some values in the mask to 0, it should work well** (float mask just changes the attention weight, and does not result in any 'nan').

**Is there really some BUG with SDPA? OR just because I misunderstood something?**

Looking forward to reply.
Thanks a lot.

**Comment by mikaylagawarecki** [comment]
You are right that the float mask should be added to the attention weight. This is a bug as in the fast path we [do not call into sdpa if `mask` is defined](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/transformers/cuda/attention.cu#L531-L551). Instead, it calls into `masked_softmax` which converts the float --> bool mask.

From offline discussion, we should 
1) re-enable sdpa for the mha fast path when `mask` is defined
2) add further testing for nn.MHA fastpath to prevent such regressions

**Comment by HELLORPG** [comment]
> You are right that the float mask should be added to the attention weight. This is a bug as in the fast path we [do not call into sdpa if `mask` is defined](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/transformers/cuda/attention.cu#L531-L551). Instead, it calls into `masked_softmax` which converts the float --> bool mask.
> 
> From offline discussion, we should
> 
> 1. re-enable sdpa for the mha fast path when `mask` is defined
> 2. add further testing for nn.MHA fastpath to prevent such regressions

Thanks for your reply. This solved my confusion.

I would rollback to PyTorch 1.13.1 to avoid this issue, and looking forward to your updates in the subsequent version~

Thanks again.

**Comment by mikaylagawarecki** [comment]
Re-opening to track the fix for 2.1

**Comment by oOXpycTOo** [comment]
Hi, I believe, similar issue still persists in PyTorch 2.1.1, but for the `TransformerEncoder`. Steps to reproduce:
```
batch_size = 32
num_heads = 2
embed_dim = 256
seq_len = 10
encoder = torch.nn.TransformerEncoderLayer(d_model=embed_dim, nhead=num_heads, dim_feedforward=embed_dim, batch_first=True, norm_first=True, activation="gelu")
encoder.eval()

x = torch.randn(batch_size, seq_len, embed_dim)
mask = torch.randn(seq_len, seq_len)

with torch.no_grad():
    out = encoder(x, src_mask=mask) # produces nans

out_1 = encoder(x, src_mask=mask) # works fine
```

**Comment by jsilbergDS** [comment]
Hello, I wanted to check in on the status of fixing this bug, or ask @oOXpycTOo if you had a good workaround. This gets triggered for me in the val_step (train_step works fine). Version is 2.0.01+cu117. Has this been fixed in a newer version?

**Comment by oOXpycTOo** [comment]
>  or ask @oOXpycTOo if you had a good workaround. 

I resorted to using FlashAttention V2 kernels directly for my task. [`flash_attn_varlen_qkvpacked_func`](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/flash_attn_interface.py#L1217-L1229) did the trick for me. Be careful, when setting arguments for it - don't forget to set dropout to `0.0`, when the layer is in training mode.
