### ISSUE TITLE
Build a check we can defer to runtime, potentially add to the graph

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#107055]
See discussion here https://github.com/pytorch/pytorch/pull/106886/files#r1291433908

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @wconstab @Xia-Weiwen @ipiszy @aakhundov

**Comment by anijain2305** [comment]
@ezyang Do you know if this is already done today?
