### ISSUE TITLE
Dynamo x FSDP - Issue Tracking Master Task

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#107053]
- [ ] https://github.com/pytorch/pytorch/issues/107054

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @wconstab @Xia-Weiwen @ipiszy

**Comment by mlazos** [comment]
Closing since this is tracked elsewhere now
