### ISSUE TITLE
Incorrect gradient computation possibly due to broadcasting

### ISSUE THREAD

**Issue by shenhao-stu** [pytorch/pytorch#107007]
### 🐛 Describe the bug

When computing the gradient of a tensor with respect to its mean, the gradient is incorrectly returned as [0, 0, 0, 0] when it should be [0.75, 0.75, 0.75, 0.75].

The operation is:
$y=x-\operatorname{mean}(x)$
Where the mean is taken across all elements of $x$.
For the gradient with respect to $x_i$ :
$\frac{\partial y}{\partial x_i}=1-\frac{1}{4}$
Because the derivative of $x_i$ with respect to itself is 1 , and the derivative of the mean of $x$ with respect to $x_i$ is $\frac{1}{4}$. But due to broadcasting, the derivative of $y$ with respect to $x.mean()$ is 4. Thus $\frac{\partial y}{\partial x_i}=1-4*\frac{1}{4}$=0. 

Given the chain rule, the gradient with respect to $x$ when $y$ is backpropagated with $[1,1,1,1]$ would indeed be $[0.75,0.75,0.75,0.75]$.

```python
import torch

x = torch.tensor([1,2,3,4], requires_grad=True, dtype=torch.float32)
y = x - x.mean() # y = [1,2,3,4] - 2.5 = [-1.5, -0.5, 0.5, 1.5]
y.backward(torch.ones_like(y))
print(x.grad) # x.grad should be 1-1/4=[0.75, 0.75, 0.75, 0.75] but it is [0, 0, 0, 0]
```

### Versions

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 525.125.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          40
On-line CPU(s) list:             0-39
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       2
Stepping:                        7
CPU max MHz:                     3200.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4800.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       640 KiB (20 instances)
L1i cache:                       640 KiB (20 instances)
L2 cache:                        20 MiB (20 instances)
L3 cache:                        27.5 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.7.0              hd8887f6_10    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.6           py310h1128e8f_1  
[conda] mkl_random                1.2.2           py310h1128e8f_1  
[conda] numpy                     1.24.3          py310h5f9d8c6_1  
[conda] numpy-base                1.24.3          py310hb5e798b_1  
[conda] pytorch                   1.13.1          py3.10_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.13.1              py310_cu117    pytorch
[conda] torchvision               0.14.1              py310_cu117    pytorch

**Comment by yuguo68** [comment]
The gradient computation in the example is correct. Note that $y$ is a vector, not a scalar. Since grads of $y_j$ are 1, the grad of $x_i$ is $\sum_j\frac{\partial y_j}{\partial x_i}=\frac{\partial (\sum_jy_j)}{\partial x_i}=\frac{\partial 0}{\partial x_i}=0$, so the result $dx_i=0$ is expected. Also, $\frac{\partial y_i}{\partial x_i}=\frac{3}{4}$, for $j\neq i$, $\frac{\partial y_j}{\partial x_i}=-\frac{1}{4}$.
