### ISSUE TITLE
Eager foreach_copy

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#107162]
### 🚀 The feature, motivation and pitch

It would be useful to have a foreach_copy in eager! For example, in rprop, there is a for loop copying grads to prevs that could be foreach'd once the API exists.

A GitHub search shows that this has been attempted before and can be revived again https://github.com/pytorch/pytorch/pull/47072. 

cc'ing @crcrpar @jiayisuse 

### Alternatives

Slowness

cc @vincentqb @jbschlosser @albanD @crcrpar @mcarilli

**Comment by vadimkantorov** [comment]
Maybe related: https://github.com/pytorch/pytorch/issues/90539
