### ISSUE TITLE
【libtorch c++ 】 how to make libtorch model  distribute  train and infer  ，please show me one tutorial or example

### ISSUE THREAD

**Issue by mullerhai** [pytorch/pytorch#107146]
### 🐛 Describe the bug

HI， for libtorch  I  found  distribute package ,but  I don't know how to declare  distribute  param to  make the libtorch model  train and infer  on distribute machines  .need our team help, thanks,pleaase  show me one example  distribute train model  code. thanks

### Versions

libtorch 2.0

**Comment by colesbury** [comment]
We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
