### ISSUE TITLE
DISABLED test_comprehensive_tanh_cuda_float16 (__main__.TestInductorOpInfoCUDA)

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#107184]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/inductor%2Ftest_torchinductor_opinfo.py%3A%3ATestInductorOpInfoCUDA%3A%3Atest_comprehensive_tanh_cuda_float16)).

Specific example: https://github.com/pytorch/pytorch/actions/runs/5860028213/job/15887855756

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jataylo** [comment]
https://github.com/pytorch/pytorch/pull/107027 PR in review
