### ISSUE TITLE
The GPU implementation of `aten::_unique2`  contains D2H sync

### ISSUE THREAD

**Issue by mapingshuo** [pytorch/pytorch#107132]
## issue

Hello, I found `torch.unique` introduce a `DtoH (Device -> Pageable) Memcpy`, which force the GPU stream sync to CPU. 

![image](https://github.com/pytorch/pytorch/assets/23031310/9f134d9f-aeea-4950-89d1-128273273490)

![image](https://github.com/pytorch/pytorch/assets/23031310/898bb172-4d4a-4544-a45e-8cbde4472bf5)

can you remove this sync ?

## version

torch 1.11

## source code

https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cuda/UniqueCub.cu#L121

## Example
```
a = torch.randint(1, 500, (4500,), device=torch.device('cuda:0'))
res, index = torch.unique(a, return_inverse=True)
```

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.28

Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-5.4.56.bsk.9-amd64-x86_64-with-debian-10.13
Is CUDA available: True
CUDA runtime version: 11.3.109
[pip3] byted-torch==1.11.0.post2
[pip3] numpy==1.21.5
[pip3] qtorch==0.3.0
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0+cu113
[pip3] torchlibrosa==0.1.0
[pip3] torchvision==0.12.0+cu113

**Comment by colesbury** [comment]
This is expected.

> can you remove this sync ?

No. The shape of the returned Tensor depends on the number of unique elements, which necessitates a device to host sync.
