### ISSUE TITLE
DISABLED test_comprehensive_nn_functional_instance_norm_cuda_float32 (__main__.TestInductorOpInfoCUDA)

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#107180]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/inductor%2Ftest_torchinductor_opinfo.py%3A%3ATestInductorOpInfoCUDA%3A%3Atest_comprehensive_nn_functional_instance_norm_cuda_float32)).

Specific example: https://github.com/pytorch/pytorch/actions/runs/5859996402/job/15887763159

This is test marked as an unexpected success in the log file and as a failure on the CI. We should remove the "expected failure" status for this test for ROCm if that's the correct resolution.

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jataylo** [comment]
https://github.com/pytorch/pytorch/pull/107027 PR in review
