### ISSUE TITLE
torch.compile doesn't support torch.autograd.Function + tensor subclass + save_for_backward

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#107237]
### 🐛 Describe the bug

For float8 training, we'd like to pass tensor subclasses into custom `torch.autograd.Function` and save them for backward.  Currently this is not traceable by dynamo.  Would be great to add this support

Minimal repro: https://gist.github.com/vkuzo/65367060edabcae5c8f3a51db19ed974
Stack trace: https://gist.github.com/vkuzo/a512f18c6e5757efa9ef29cd0b505ca2

### Versions

torch==2.1.0a0+gita14d99b

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

**Comment by vkuzo** [comment]
fails here (https://github.com/pytorch/pytorch/blob/7fb543e36ddca3b96543bce857f76fbeef64fda5/torch/_dynamo/variables/misc.py#L468) because `UserDefinedObjectVariable` doesn't have `as_proxy` defined

**Comment by vkuzo** [comment]
we need https://github.com/pytorch/pytorch/issues/107239 to be done, and this will probably work

**Comment by wconstab** [comment]
@brian feel free to reassign, thought this might be you

**Comment by bdhirsh** [comment]
Yep going to try to look at this a bit this week.

Although I think Vasiliy and I agreed offline that the example subclass was missing `__tensor_flatten__`/`__tensor_unflatten__` methods, which probably caused the initial error. Eventually we might want to graph break / explicitly fall back to eager if torch.compile encounters a `__torch_dispatch__` subclass that doesn't properly advertise as being traceable? But I need to land more subclass support before doing that.
