### ISSUE TITLE
FULL_CAFFE2=1 usage

### ISSUE THREAD

**Issue by deepali-c** [pytorch/pytorch#10728]
I tried building caffe2 and pytorch using `FULL_CAFFE2=1 setup.py install` . I was then able to execute the caffe2 MNIST sample at https://github.com/caffe2/tutorials/blob/master/MNIST.ipynb. 

However, I observed all caffe2 binaries/tests are not built while using FULL_CAFFE2. I am just curious to know if it would be possible to build CPP binaries and tests too using this option in future. Please let me know if that is intended.

**Comment by pjh5** [comment]
You can change this for your local build by changing https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.sh#L269  before calling `FULL_CAFFE2=1 setup.py install`. setuptools doesn't make it easy to propogate flags, so the binaries will probably not be built by default in the near future.
