### ISSUE TITLE
pytorch1.12.0 building erros on win10

### ISSUE THREAD

**Issue by HeiMa2017** [pytorch/pytorch#107203]
### 🐛 Describe the bug

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(77): error: identifier "__ceilf" is undefined in device code

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(82): error: calling a __host__ function("__floorf") from a __global__ function("at::native::_NV_ANON_NAMESPACE::adaptivemaxpool< ::c10::Half> ") is not allowed

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(82): error: identifier "__floorf" is undefined in device code

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(83): error: calling a __host__ function("__ceilf") from a __global__ function("at::native::_NV_ANON_NAMESPACE::adaptivemaxpool< ::c10::Half> ") is not allowed

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(83): error: identifier "__ceilf" is undefined in device code

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(62): error: calling a __host__ function("__floorf") from a __global__ function("at::native::_NV_ANON_NAMESPACE::adaptivemaxpool< ::c10::BFloat16> ") is not allowed

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(62): error: identifier "__floorf" is undefined in device code

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(63): error: calling a __host__ function("__ceilf") from a __global__ function("at::native::_NV_ANON_NAMESPACE::adaptivemaxpool< ::c10::BFloat16> ") is not allowed

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(63): error: identifier "__ceilf" is undefined in device code

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(76): error: calling a __host__ function("__floorf") from a __global__ function("at::native::_NV_ANON_NAMESPACE::adaptivemaxpool< ::c10::BFloat16> ") is not allowed

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(76): error: identifier "__floorf" is undefined in device code

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(77): error: calling a __host__ function("__ceilf") from a __global__ function("at::native::_NV_ANON_NAMESPACE::adaptivemaxpool< ::c10::BFloat16> ") is not allowed

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(77): error: identifier "__ceilf" is undefined in device code

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(82): error: calling a __host__ function("__floorf") from a __global__ function("at::native::_NV_ANON_NAMESPACE::adaptivemaxpool< ::c10::BFloat16> ") is not allowed

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(82): error: identifier "__floorf" is undefined in device code

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(83): error: calling a __host__ function("__ceilf") from a __global__ function("at::native::_NV_ANON_NAMESPACE::adaptivemaxpool< ::c10::BFloat16> ") is not allowed

D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu(83): error: identifier "__ceilf" is undefined in device code

48 errors detected in the compilation of "D:/TorchSrc1.12.0/aten/src/ATen/native/cuda/AdaptiveMaxPooling3d.cu".
AdaptiveMaxPooling3d.cu

### Versions

# Name                    Version                   Build  Channel
astunparse                1.6.3                      py_0    defaults
blas                      1.0                         mkl    defaults
brotlipy                  0.7.0           py39h2bbff1b_1003    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2023.05.30           haa95532_0    defaults
certifi                   2023.7.22        py39haa95532_0    defaults
cffi                      1.15.1           py39h2bbff1b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
cmake                     3.26.4               h693b641_0    defaults
cryptography              41.0.2           py39h31511bf_0    defaults
dataclasses               0.8                pyh6d0b6a4_7    defaults
future                    0.18.3           py39haa95532_0    defaults
idna                      3.4              py39haa95532_0    defaults
intel-openmp              2023.1.0         h59b6b97_46319    defaults
libuv                     1.44.2               h2bbff1b_0    defaults
lz4-c                     1.9.4                h2bbff1b_0    defaults
mkl                       2023.1.0         h8bd8f75_46356    defaults
mkl-include               2023.1.0         haa95532_46356    defaults
mkl-service               2.4.0            py39h2bbff1b_1    defaults
mkl_fft                   1.3.6            py39hf11a4ad_1    defaults
mkl_random                1.2.2            py39hf11a4ad_1    defaults
ninja                     1.10.2               haa95532_5    defaults
ninja-base                1.10.2               h6d14046_5    defaults
numpy                     1.25.0           py39h055cbcc_0    defaults
numpy-base                1.25.0           py39h65a83cf_0    defaults
openssl                   1.1.1v               h2bbff1b_0    defaults
pip                       23.2.1           py39haa95532_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0           py39haa95532_0    defaults
pysocks                   1.7.1            py39haa95532_0    defaults
python                    3.9.7                h6244533_1    defaults
pyyaml                    6.0              py39h2bbff1b_1    defaults
requests                  2.31.0           py39haa95532_0    defaults
setuptools                68.0.0           py39haa95532_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.41.2               h2bbff1b_0    defaults
tbb                       2021.8.0             h59b6b97_0    defaults
typing_extensions         4.7.1            py39haa95532_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16          py39haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.38.4           py39haa95532_0    defaults
win_inet_pton             1.1.0            py39haa95532_0    defaults
xz                        5.4.2                h8cc25b3_0    defaults
yaml                      0.2.5                he774522_0    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
zstd                      1.5.5                hd43e919_0    defaults

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by HeiMa2017** [comment]
Who suffers the probelm like？ it is very appreciate to provide solution of above issue.

**Comment by soulitzer** [comment]
You might want to try again with the latest version of PyTorch

**Comment by alinpahontu2912** [comment]
@HeiMa2017 hello, are you still dealing with this issue? I tried installing pytorch 1.12.0 with python 3.9.7, following this [guide](https://pytorch.org/get-started/previous-versions/#linux-and-windows-8l) and I could not get that error. I also think you should try the latest version of pytorch, if possible.

![Image](https://github.com/pytorch/pytorch/assets/56953855/adbe9966-671f-41c0-a8fd-43d734ca4de0)

**Comment by iremyux** [comment]
Closing this issue since it no longer seems relevant. Please feel free to open a new issue if you entounter any problems or have a feature request.
