### ISSUE TITLE
baddbmm computation accuracy error

### ISSUE THREAD

**Issue by BuaaAlban** [pytorch/pytorch#107221]
### 🐛 Describe the bug

```python
import torch
k = torch.randn(1, 256, 2048)
q = torch.randn(1, 2048, 256)
a =  torch.randn(1,1,2048)

y1 = a.baddbmm(batch1=q,batch2=k,beta =1.0, alpha=0.08838834764831843)

y2 = 1.0*a + 0.08838834764831843*(q @ k)

errors = torch.sum(torch.abs(y1-y2))
#I expect y1 == y2 according to https://pytorch.org/docs/stable/generated/torch.baddbmm.html#torch.baddbmm, but I got different results

#some egs, the error may be small, but big enough to have great influence for the network
#the error is caused by alpha*(q @ k), when alpha is not an integer.

tmp = torch.matmul(q , k)
>>> torch.sum(torch.abs(a.baddbmm(batch1=q,batch2=k,beta =0,alpha=2)-2*tmp))
tensor(0.)
>>> torch.sum(torch.abs(a.baddbmm(batch1=q,batch2=k,beta =0,alpha=1.5)-1.5*tmp))
tensor(20.4355)
>>> 1.5*tmp
tensor([[[-12.5057, -23.4980,   3.9311,  ...,   3.0636, -21.7117,  -7.7373],
         [ 16.6731, -32.0761, -14.7984,  ..., -22.9475,  12.4296, -39.1006],
         [ 28.0811,  32.0373,  18.2207,  ...,  36.2809,   9.2642,  39.3569],
         ...,
         [-20.5763,  -2.7708, -25.8581,  ...,  11.3705,  48.9568,  42.7949],
         [ -4.3969,  14.8652,   0.6504,  ...,  12.9696, -11.0422,  -7.0491],
         [ 19.6472,  19.2192, -26.0836,  ...,  11.0523,  16.5575, -14.6770]]])
>>> a.baddbmm(batch1=q,batch2=k,beta =0,alpha=1.5)
tensor([[[-12.5057, -23.4980,   3.9311,  ...,   3.0636, -21.7117,  -7.7373],
         [ 16.6731, -32.0761, -14.7984,  ..., -22.9475,  12.4296, -39.1006],
         [ 28.0811,  32.0373,  18.2207,  ...,  36.2809,   9.2642,  39.3568],
         ...,
         [-20.5763,  -2.7708, -25.8581,  ...,  11.3705,  48.9568,  42.7949],
         [ -4.3969,  14.8652,   0.6504,  ...,  12.9696, -11.0422,  -7.0491],
         [ 19.6472,  19.2192, -26.0836,  ...,  11.0523,  16.5575, -14.6770]]])
>>> 1.5*tmp-a.baddbmm(batch1=q,batch2=k,beta =0,alpha=1.5)
tensor([[[ 2.8610e-06,  5.7220e-06, -2.3842e-06,  ..., -1.9073e-06,
          -9.5367e-06, -9.5367e-07],
         [-1.9073e-06, -3.8147e-06,  0.0000e+00,  ...,  7.6294e-06,
           5.7220e-06, -1.1444e-05],
         [ 2.2888e-05,  3.8147e-06, -1.9073e-06,  ...,  1.1444e-05,
          -9.5367e-06,  1.5259e-05],
         ...,
         [-1.5259e-05, -9.5367e-06, -7.6294e-06,  ...,  6.6757e-06,
           0.0000e+00,  0.0000e+00],
         [ 2.3842e-06,  1.9073e-06, -9.5367e-07,  ..., -9.5367e-07,
          -2.8610e-06,  2.8610e-06],
         [ 1.9073e-06,  1.9073e-06,  5.7220e-06,  ...,  1.9073e-06,
           1.9073e-06, -7.6294e-06]]])
```

### Versions

```python
>>> torch.__version__
'1.12.0+cu102'
>>> tmp.dtype
torch.float32
>>> tmp.device
device(type='cpu')
```
Collecting environment information...
PyTorch version: 1.12.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.10

Python version: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-128-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: False
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 73F3 16-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         1496.158
CPU max MHz:                     3500.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        6999.94
Virtualization:                  AMD-V
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        16 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-15,32-47
NUMA node1 CPU(s):               16-31,48-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] flake8==3.7.9
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.21.3
[pip3] numpydoc==0.8.0
[pip3] pytorch-lightning==1.5.2
[pip3] pytorch-nndct==0.1.0+1fa95a2
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.12.0
[pip3] torch-stft==0.1.4
[pip3] torchaudio==0.8.0
[pip3] torchmetrics==0.10.3
[pip3] torchprofiler==0.1
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.3                      199    defaults
[conda] mkl-service               1.1.2            py37he904b0f_5    defaults
[conda] mkl_fft                   1.0.10           py37ha843d7b_0    defaults
[conda] mkl_random                1.0.2            py37hd81dba3_0    defaults
[conda] msgpack-numpy             0.4.7.1                  pypi_0    pypi
[conda] numpy                     1.21.3                   pypi_0    pypi
[conda] numpydoc                  0.8.0                    py37_0    defaults
[conda] pytorch-lightning         1.5.2                    pypi_0    pypi
[conda] pytorch-nndct             0.1.0+b073157            pypi_0    pypi
[conda] pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] torch                     1.8.0                    pypi_0    pypi
[conda] torch-stft                0.1.4                    pypi_0    pypi
[conda] torchaudio                0.8.0                    pypi_0    pypi
[conda] torchmetrics              0.10.3                   pypi_0    pypi
[conda] torchvision               0.9.0                    pypi_0    pypi

**Comment by ptrblck** [comment]
Small numerical errors in the posted range of ~1e-6 are expected for `floast32` operations caused by the limited floating point precision and a potentially different order of operations.
A simple example can be seen here:
```python
x = torch.randn(100, 100)
s1 = x.sum()
s2 = x.sum(0).sum(0)
print((s1 - s2).abs())
# tensor(3.0518e-05)
```

> the error may be small, but big enough to have great influence for the network

You might then need to improve the stability of your model as you should note that neither of the results is "more correct" and both show the same error stats compared against a wider dtype, such as `float64`.
