### ISSUE TITLE
Windows Pipelines are failing

### ISSUE THREAD

**Issue by cristianPanaite** [pytorch/pytorch#107220]
## Current Status
ongoing

## Error looks like
`Error: No files were found with the provided path: C:\5864482339\build-results. No artifacts will be uploaded.`

## Incident timeline (all times pacific)
Last successful run: 9:32 PM 

## User impact
Windows pipelines are red

## Root cause
It seems like there is a [linking error](https://github.com/pytorch/pytorch/actions/runs/5864482339/job/15899622919#step:10:10565) during the build. Even if this is happening, the build is still successful (I guess it's false positive). Anyway, the consequence is that the artifacts are not found.

## Mitigation
*TBD*

## Prevention/followups
*TBD*

**Comment by huydhn** [comment]
I revert the change https://github.com/pytorch/pytorch/pull/106988, Windows build is working now.  Please do a rebase if you are seeing this failure on your PR.
