### ISSUE TITLE
Is pytorch version 1.10.2 still maintained? What is the official EOM(End of Maintenance) date?

### ISSUE THREAD

**Issue by reBiocoder** [pytorch/pytorch#107225]
### 🐛 Describe the bug

Is pytorch version 1.10.2 still maintained? What is the official EOM(End of Maintenance) date?

### Versions

pytorch v1.10.2

cc @seemethere @malfet @svekars @carljparker

**Comment by malfet** [comment]
@reBiocoder this feels like a discussion topic that better be asked on https://discuss.pytorch.org

In general, we only maintain latest release, unless there is something really catastrophic with an old one. Is there something that prevents you from upgrading from 1.10 to 2.0?

**Comment by seemethere** [comment]
Going to go ahead and close this, @malfet's response should be sufficient enough here.
