### ISSUE TITLE
[Inductor][cpu][amp] accuracy check failed models until 2023_08_12 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#107367]
### 🐛 Describe the bug

As the title, for reproduce:

bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) multiple inference accuracy **suite model** amp first static default 0

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/yudongsi/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/yudongsi/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>
<body link="#0563C1" vlink="#954F72">

timm_models | adv_inception_v3
-- | --
timm_models | coat_lite_mini
torchbench | doctr_reco_predictor
timm_models | gernet_l
torchbench | llama
timm_models | mobilenetv3_large_100

</body>
</html>

### Versions

torchbench : 770d5cf7
torch :  2.1.0a0+gitc9397a7
torchvision :  0.16.0a0+58366ab
torchtext :  0.16.0a0+c11d758
torchaudio :  2.1.0a0+dc83b38
torchdata :  0.7.0a0+1d231d1
dynamo_benchmarks : f228c8b

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by leslie-fang-intel** [comment]
closed and will track with new conv-bn issue: https://github.com/pytorch/pytorch/issues/108333
