### ISSUE TITLE
[Inductor][cpu][dynamic shapes] some models perf regression on 2023_08_13 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#107364]
### 🐛 Describe the bug

overlap some in https://github.com/pytorch/pytorch/issues/107361

tracked in https://github.com/pytorch/pytorch/issues/93531#issuecomment-1678363694

<html>
<body>
<p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">new_perf_regression</p>

name | batch_size_new | speed_up_new | inductor_new | eager_new | compilation_latency_new | batch_size_old | speed_up_old | inductor_old | eager_old | compilation_latency_old | Ratio Speedup(New/old) | Eager Ratio(old/new) | Inductor Ratio(old/new) | Compilation_latency_Ratio(old/new)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
basic_gnn_edgecnn | 1 | 1.508088 | 0.022154355 | 0.033410716923240005 | 21.568874 | 1 | 1.468842 | 0.01964991 | 0.02886261310422 | 21.41877 | 1.03 | 0.86 | 0.89 | 0.99
timm_efficientnet | 64 | 1.864825 | 0.074686855 | 0.13927791437537498 | 39.110629 | 64 | 2.271973 | 0.061235542999999996 | 0.139125500336339 | 33.733345 | 0.82 | 1.0 | 0.82 | 0.86
fbnetv3_b | 128 | 2.115876 | 0.17903138799999999 | 0.37880821711588797 | 59.657087 | 128 | 2.455233 | 0.15275012699999999 | 0.375037152564591 | 49.887107 | 0.86 | 0.99 | 0.85 | 0.84
lcnet_050 | 128 | 2.363365 | 0.018859103000000002 | 0.04457094396159501 | 30.50393 | 128 | 2.786405 | 0.016052551999999998 | 0.04472891115555999 | 27.911034 | 0.85 | 1.0 | 0.85 | 0.91
mobilevit_s | 64 | 1.352676 | 0.301181983 | 0.407401640036508 | 68.754827 | 64 | 1.518162 | 0.26824332199999995 | 0.4072368182141639 | 65.932567 | 0.89 | 1.0 | 0.89 | 0.96
rexnet_100 | 128 | 1.941472 | 0.17325859500000002 | 0.33637671095184 | 44.630441 | 128 | 2.367995 | 0.141648458 | 0.33542284030171005 | 38.017091 | 0.82 | 1.0 | 0.82 | 0.85
tf_efficientnet_b0 | 128 | 1.903405 | 0.18577254099999999 | 0.353600383402105 | 39.974129 | 128 | 2.192261 | 0.16153199699999998 | 0.35412029727521693 | 35.145862 | 0.87 | 1.0 | 0.87 | 0.88
tinynet_a | 128 | 1.880591 | 0.126142181 | 0.23722185030897097 | 43.22652 | 128 | 2.261306 | 0.104448945 | 0.23619102602217 | 36.879897 | 0.83 | 1.0 | 0.83 | 0.85
llama | 1 | 0.247502 | 0.125853187 | 0.031148915488874 | 31.766273 | 1 | 0.313236 | 0.101271664 | 0.031721930944704 | 31.492961 | 0.79 | 1.02 | 0.8 | 0.99
maml_omniglot | 5 | 2.870874 | 0.000677145 | 0.00194399797473 | 21.827845 | 5 | 3.404081 | 0.000570539 | 0.001942160969659 | 21.747227 | 0.84 | 1.0 | 0.84 | 1.0
yolov3 | 1 | 1.031417 | 0.573838285 | 0.591866562399845 | 40.834887 | 1 | 1.152466 | 0.511394202 | 0.5893644304021319 | 34.296935 | 0.89 | 1.0 | 0.89 | 0.84
cspdarknet53 | 1 | 1.036106 | 0.126511417 | 0.131079238222202 | 38.092295 | 1 | 1.196744 | 0.11079330899999999 | 0.132591227785896 | 32.321586 | 0.87 | 1.01 | 0.88 | 0.85
lcnet_050 | 1 | 1.513589 | 0.002645708 | 0.004004514526012 | 26.734234 | 1 | 1.766807 | 0.00230192 | 0.00406704836944 | 24.969956 | 0.86 | 1.02 | 0.87 | 0.93

</body>
</html>

Repro:
bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) multiple inference performance suite model float32 first dynamic cpp 0

### Versions

target:
torchbench : 770d5cf7
torch :  2.1.0a0+git3748ee4
torchvision :  0.16.0a0+58366ab
torchtext :  0.16.0a0+c11d758
torchaudio :  2.1.0a0+dc83b38
torchdata :  0.7.0a0+1d231d1
dynamo_benchmarks : f228c8b

refer:
torchbench : 770d5cf7
torch :  2.1.0a0+gita8638d6
torchvision :  0.16.0a0+58366ab
torchtext :  0.16.0a0+c11d758
torchaudio :  2.1.0a0+dc83b38
torchdata :  0.7.0a0+1d231d1
dynamo_benchmarks : f228c8b

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by XiaobingSuper** [comment]
According to https://github.com/pytorch/pytorch/issues/93531#issuecomment-1706266294, most models's speed up regression seems fixed, @ESI-SYD , please help double-check it. Thanks!

**Comment by ESI-SYD** [comment]
Checked fixed, closing
