### ISSUE TITLE
Update generic operator tests to run for primtorch ops

### ISSUE THREAD

**Issue by ekamiti** [pytorch/pytorch#107335]
## Issue description

Currently most of the operator groupings in [common_method_invocations](https://github.com/pytorch/pytorch/blob/8507b22fea9ef819452655aa6dd1c42752a4e74a/torch/testing/_internal/common_methods_invocations.py#L20638-L20651) don't include the reference operators and this could lead to unintended mismatch in operator functionality between eager ops and primtorch ops slipping through. Some cases have already been seen of this while creating https://github.com/pytorch/pytorch/pull/104489.  This is issue is being created in order to track and breakdown the changes to multiple pull requests for more manageable pieces for review. The `sparse_*` groupings cannot be currently updated as it seems that sparse tensor support for primtorch is is not yet complete.

https://github.com/pytorch/pytorch/blob/8507b22fea9ef819452655aa6dd1c42752a4e74a/torch/testing/_internal/common_methods_invocations.py#L20638-L20651
- [ ] Update `unary_ufuncs` groupings
- [ ] Update `binary_ufuncs` groupings
- [ ] Update `spectral_funcs` groupings
- [ ] Update `sparse_unary_ufuncs` groupings
- [ ] Update `sparse_csr_unary_ufuncs` groupings
- [ ] Update `sparse_reduction_ops` groupings
- [ ] Update `shape_funcs` groupings
- [ ] Update `reduction_ops` groupings

cc @ezyang @mruberry @Lezcano @peterbell10

**Comment by ezyang** [comment]
Hi, I chatted about this with @ngimel and avoiding refs being tested this way was partially about avoiding inflating test time. So it would be good to make sure we aren't making test times a lot worse.
