### ISSUE TITLE
Getting more human-readable input and output names in the onnx model exported by torch

### ISSUE THREAD

**Issue by AlexHJH** [pytorch/pytorch#107355]
### 🚀 The feature, motivation and pitch

In  pytorch, we use variable names with actual physical meaning for distinguishing the inputs and outputs of the model. The corresponding interface is provided in the torch.onnx.export interface to reflect this, but when `export_modules_as_functions` is used to package the nn.Module, the setting of `output_names` is not correctly reflected if the output of the graph is also the output of a function, as exemplified in the following.
~~~ python
import timm
import torch
import torch.nn as nn

class TestModule(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.conv = nn.Conv2d(3, 32, (3, 3))
        self.relu = nn.ReLU()
        self.pool = nn.AvgPool2d((3, 3), (2, 2))
        
    def forward(self, x):
        x = self.conv(x)
        x = self.relu(x)
        x = self.pool(x)
        return x

module = TestModule()
module.eval()
torch.onnx.export(
    module,
    (torch.ones([1, 3, 64, 64], dtype=torch.float32), ),
    "test.onnx",
    opset_version=15,
    input_names=["input"],
    output_names=["output"],
    export_modules_as_functions={
        nn.AvgPool2d
    }
)
~~~
![test](https://github.com/pytorch/pytorch/assets/30765323/c6f8b687-ce27-4924-a8e9-99cd3f34c0f0)
The output name of the graph is set to the meaningless number `8` instead of `output`.

In `torch.onnx.dynamo_export`, there is not yet an interface for setting input names and output names, and it is hoped that some of the interface settings of `torch.onnx.export` can be migrated to the `torch.onnx.dynamo_export` to improve the readability of the final exported model

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @wconstab

**Comment by justinchuby** [comment]
The dynamo exporter preserves the names from the fx graph: 
![image](https://github.com/pytorch/pytorch/assets/11205048/e0da71c9-2a8e-497b-9f42-c2fdc5ef97a5)

@BowenBao do you know if there are ways to affect the input/output names in the fx graph/dynamo?

**Comment by FelixHo** [comment]
I came across the same, any plans for addressing this? Are there any workarounds that we can consider in the meantime? The workaround I can think of right now is to reload using the ONNX library, then modify the naming, and export it again. 

Any help would be greatly appreciated.

**Comment by zhxchen17** [comment]
afaik @pianpwk is actively working on improving input name for torch.export.export.

**Comment by thiagocrepaldi** [comment]
Dynamo preserves the input name and there is no plan to support custom naming.

**Comment by vvijay-cov** [comment]
@thiagocrepaldi

What is the recommended way to generate an onnx models with identifiable inputs? At the moment, if I export a model with torch.onnx.dynamo_export, I can't make out what inputs it is expecting and therefore can't really use it.

**Comment by justinchuby** [comment]
You can load the model with `onnxscript.ir.from_proto()` and change the input names with

```python
model.graph.inputs[0].name = "new_name"
```

etc.

Install `onnxscript` with `pip install onnxscript`.

**Comment by kabyanil** [comment]
This feature would be really helpful. Custom naming makes the code much more readable and logical.

**Comment by justinchuby** [comment]
Options are added. 

Please test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!
