### ISSUE TITLE
Dynamo pytree registration is distinct from user pytree registration, leading to behavior divergence

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#107315]
### 🐛 Describe the bug

pytree support in Dynamo https://github.com/pytorch/pytorch/pull/101896 is implemented by implementing separate pytree rules that operate on VariableTracker, instead of using the canonical pytree registry. This means that if a user defines their own pytree node registration, Dynamo's behavior will silently diverge from regular eager PyTorch. This recently affected @zhxchen17 who observed that KeyedJaggedTensor was not being correctly handled inside torch.export.

cc @gchanan @zou3519 @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov @zhxchen17 @tugsbayasgalan 

### Versions

main

**Comment by zou3519** [comment]
Maybe it's time to try the "trace through pytree APIs" approach instead of "have pytree rules on VariableTracker"

**Comment by wconstab** [comment]
reading through the comments on https://github.com/pytorch/pytorch/pull/101896, it seems like we have 2 options
(a) dynamo keeps modeling pytree, but it honors the user-registered types in pytorch's pytree impl
(b) we maintain a python pytree impl that dynamo traces, even if we move pytree to c++ - in this case we still need python pytree to use the same type registry as c++

Is (a) actually harder than (b)?  Does dynamo need to 'understand' anything about the user registered types other than wrapping in a generic UserDefinedObjectVariable or something?

**Comment by ezyang** [comment]
I would deeply prefer (b) from a philosophical perspective.

**Comment by wconstab** [comment]
yea now that i think of it, me too.  (a) only appeals as a short term 'improve what already almost works' thing. (b) sounds cleaner.

**Comment by albanD** [comment]
Question from Brian: how is this a silent failure? Why doesn't it loudly fails and fallback to eager?

**Comment by ezyang** [comment]
If a node isn't recognized, you don't traverse into it with pytree. It's not like you raise  an error.

**Comment by ysiraichi** [comment]
@ezyang @zou3519 
I would like to take this on. Just to confirm: in order to solve this issue, I should modify pytree implementation so that dynamo is able to inline them. Correct?

**Comment by ysiraichi** [comment]
Instead, isn't a graph break enough?

**Comment by ezyang** [comment]
Tentatively, inlining through the Python pytree implementation is the most straightforward way to do it, though I don't know if you'll run into unexpected yaks along the way.
