### ISSUE TITLE
[Inductor][cpu][dynamic shapes] some models perf regression on 2023_08_14 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#107361]
### 🐛 Describe the bug

[tracked in https://github.com/pytorch/pytorch/issues/93531#issuecomment-1678596899](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1679305449)

<html>
<body>
<p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">new_perf_regression(llama regression only viewed in single core secnario )</p>

name | batch_size_new | speed_up_new | inductor_new | eager_new | compilation_latency_new | batch_size_old | speed_up_old | inductor_old | eager_old | compilation_latency_old | Ratio Speedup(New/old) | Eager Ratio(old/new) | Inductor Ratio(old/new) | Compilation_latency_Ratio(old/new)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
timm_efficientnet | 64 | 1.80161 | 0.078453506 | 0.14134262094466002 | 103.23573 | 64.0 | 2.156638 | 0.064944659 | 0.140062119496442 | 86.033877 | 0.84 | 0.99 | 0.83 | 0.83
cspdarknet53 | 64 | 1.474625 | 0.361821849 | 0.533551544081625 | 83.206848 | 64.0 | 1.646231 | 0.32140863999999997 | 0.5291128668358399 | 74.674034 | 0.9 | 0.99 | 0.89 | 0.9
eca_botnext26ts_256 | 128 | 1.481745 | 0.458381906 | 0.67920509730597 | 87.280568 | 128.0 | 1.765525 | 0.383932251 | 0.677841987446775 | 84.07814 | 0.84 | 1.0 | 0.84 | 0.96
eca_halonext26ts | 128 | 1.54632 | 0.44726899600000003 | 0.69162099389472 | 96.358421 | 128.0 | 1.751728 | 0.393648549 | 0.689565185442672 | 93.389382 | 0.88 | 1.0 | 0.88 | 0.97
fbnetv3_b | 128 | 2.025044 | 0.186951119 | 0.37858424182423595 | 118.112828 | 128.0 | 2.406976 | 0.156092856 | 0.375711758163456 | 96.311 | 0.84 | 0.99 | 0.83 | 0.82
lcnet_050 | 128 | 2.272198 | 0.019835000999999998 | 0.04506904960219799 | 45.09163 | 128.0 | 2.618577 | 0.016632827 | 0.043554338227179 | 38.14612 | 0.87 | 0.97 | 0.84 | 0.85
mobilevit_s | 64 | 1.338551 | 0.306310889 | 0.41001274678183897 | 145.453919 | 64.0 | 1.495573 | 0.272776138 | 0.407956627037074 | 130.825494 | 0.9 | 0.99 | 0.89 | 0.9
regnety_002 | 128 | 2.032501 | 0.046286264 | 0.094076877866264 | 58.881773 | 128.0 | 2.275769 | 0.040950339999999995 | 0.09319351431145999 | 54.81093 | 0.89 | 0.99 | 0.88 | 0.93
rexnet_100 | 128 | 1.897531 | 0.177675237 | 0.33714427013984705 | 149.267639 | 128.0 | 2.309794 | 0.14523763299999998 | 0.335469013277602 | 134.371602 | 0.82 | 1.0 | 0.82 | 0.9
tf_efficientnet_b0 | 128 | 1.828963 | 0.193690832 | 0.354253365167216 | 110.07121 | 128.0 | 2.174611 | 0.161646728 | 0.351518752822808 | 92.619813 | 0.84 | 0.99 | 0.83 | 0.84
tinynet_a | 128 | 1.828498 | 0.130438908 | 0.23850728240018398 | 109.361486 | 128.0 | 2.212559 | 0.10776662399999999 | 0.238440013830816 | 92.410846 | 0.83 | 1.0 | 0.83 | 0.85
llama | 1 | 0.221285 | 0.146538037 | 0.032426669517545005 | 38.412999 | 1.0 | 0.304898 | 0.105546689 | 0.032180974382722 | 37.597724 | 0.73 | 0.99 | 0.72 | 0.98

</body>
</html>

Repro:

bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) multiple inference performance **suite model** float32 first dynamic default 0
### Versions

target:
torchbench : 770d5cf7
torch :  2.1.0a0+git53551b5
torchvision :  0.16.0a0+ee0690e
torchtext :  0.16.0a0+04a8862
torchaudio :  2.1.0a0+04dc630
torchdata :  0.7.0a0+1ecbe2c
dynamo_benchmarks : nightly

refer:
torchbench : 770d5cf7
torch :  2.1.0a0+git5e438d5
torchvision :  0.16.0a0+128d52a
torchtext :  0.16.0a0+f3ca0c4
torchaudio :  2.1.0a0+618aad9
torchdata :  0.7.0a0+484a3c8
dynamo_benchmarks : nightly

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by XiaobingSuper** [comment]
same as https://github.com/pytorch/pytorch/issues/107364, most models' regression seems be fixed, @ESI-SYD, please  help double check it.

**Comment by ESI-SYD** [comment]
Checked fixed, closing
