### ISSUE TITLE
bceloss weight shape incorrect

### ISSUE THREAD

**Issue by nkundiushuti** [pytorch/pytorch#10732]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

I have an error with BCELoss when using weights with batch size 64:

loss = self.criterion.forward(y_hat, y_batch)
  File "/home/NET1/mironma/anaconda3/envs/fatml/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 486, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/NET1/mironma/anaconda3/envs/fatml/lib/python3.6/site-packages/torch/nn/functional.py", line 1603, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction)
RuntimeError: input and weights have different number of elements: input[64 x 1] has 64 elements, while weights[64 x 64] has 4096 elements at /opt/conda/conda-bld/pytorch_1532579245307/work/aten/src/THCUNN/generic/BCECriterion.cu:14

## Code example
    def train_epoch(self,x,y,w=None):
        self.model.train()
        r = np.arange(x.size(0))
        np.random.shuffle(r)
        r = torch.LongTensor(r).cuda()

        for i in range(0, len(r), self.sbatch):
            if i+self.sbatch<=len(r): b=r[i:i+self.sbatch]
            else: b=r[i:]
            x_batch = torch.autograd.Variable(x[b])
            y_batch = torch.autograd.Variable(y[b])
            if w is not None:
                w_batch = torch.autograd.Variable(w[b])
            #printing w_batch.data.size() gives torch.Size([64])

            self.optimizer.zero_grad()
            # (1) Forward
            y_hat = self.model.forward(x_batch)
            # (2) Compute diff
            if w is not None:
                self.criterion.weight = w_batch
                loss = self.criterion.forward(y_hat, y_batch)
            else:
                loss = self.criterion(y_hat, y_batch)
            # (3) Compute gradients
            loss.backward()
            # (4) update weights
            #torch.nn.utils.clip_grad_norm(self.model.parameters(), self.clipgrad)
            self.optimizer.step()

        return

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source): 
- OS: 
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by SsnL** [comment]
From the clear error message, the weight you computed and manually assigned is wrong.

**Comment by nkundiushuti** [comment]
so the weight it should not have the same size as the batch (one weight per element?) I am sorry but I don't understand. I found different explanations on different forums

**Comment by nkundiushuti** [comment]
so, could you please clarify this?
weight (Tensor, optional) – a manual rescaling weight given to the loss of each batch element. If given, has to be a Tensor of size “nbatch”. 
the size of weight given is torch.Size([64]) which is also the batch size. is that not correct?
