### ISSUE TITLE
NumPy 2.0 Support

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#107302]
NumPy 2.0  is expected to be out in December 2023. See details at https://github.com/numpy/numpy/issues/24300

The major changes are going to be some Python API and behavior improvements. These don't impact PyTorch code itself and our compat layer (https://github.com/pytorch/pytorch/tree/main/torch/_numpy) is targeting 2.0+ already.

There are also C-API changes and in particular while 2.0 ABI will be backward compatible, the current ABI will not be forward compatible with 2.0. This will require some care on our end to make sure things work properly.

In terms of PyTorch future release, it means that, as of today, the expected support matrix looks like:
- PyTorch <=2.1 and nightly until EOY 2023 can live alongside any version of NumPy but the `.numpy()` and `.from_numpy()` functions will ONLY work if the version of NumPy installed is <2.0. Users can build from source against their version of NumPy if they need a more recent version of NumPy.
- PyTorch >=2.2 and nightly after EOY 2023 (once we have a NumPy 2.0 ABI-compatible build) will be fully compatible with all versions of NumPy.

The AIs to ensure this works:
- [ ] Add a helpful error message in PyTorch to give users a helpful error message if they try to use .numpy() or .from_numpy() with numpy 2.0+ today. This will replace the ABI error message from https://github.com/numpy/numpy/blob/7b56da8c46427d487b9337780417a9aad64eb295/numpy/core/code_generators/generate_numpy_api.py#L81-L82 that they will get today by a message asking them use NumPy <2.0 or build from source.
- [ ] Once we have a NumPy 2.0 compatible available, upgrade all our binary build to this version of NumPy and remove the error message above. This will ensure that our produced binaries work with any version of NumPy (including <2.0)
- [ ] Make `torch.compile` compatible with NumPy 2.0. In order to do that, we may need to update the `test/torch_np` tests that we pulled from NumPy

cc @mruberry @rgommers

**Comment by seemethere** [comment]
cc @atalman, @osalpekar

**Comment by malfet** [comment]
IMO we should do some of that for 2.3 (already started by making PyTorch compileable against Numpy-2.0)

**Comment by rgommers** [comment]
> IMO we should do some of that for 2.3 (already started by making PyTorch compilable against Numpy-2.0)

I agree. It is important to build all binaries for the next minor or bugfix release of PyTorch against the latest NumPy 2.0.0 pre-release. That way, it will be ABI-compatible with both 1.x and 2.0, which is going to avoid a lot of problems. If such a release is not done before numpy 2.0.0 final is out (probably 8 weeks from now), then any environments created with `pip install torch numpy` will be quite broken, since no interop between PyTorch and NumPy is possible then. I haven't tried, but it's also possible that `import torch` or use of sub-components will be broken completely, since try-except imports of `numpy` that are scattered around the PyTorch codebase are going to succeed and then give `RuntimeError('ABI mismatch ...')` when used ([example in TorchDynamo](https://github.com/pytorch/pytorch/blob/38d9bb5abcc31ba97927a5399b88afe2cf60bf64/torch/_dynamo/variables/tensor.py#L15-L23)).

The plan posted by @albanD in the issue description still looks right. The first item is probably no longer relevant, since `2.0.0b1` is already available. The second item is urgent. The third one good to do, but the compat issues are probably relatively minor, so not nearly as urgent as handling the ABI compat issue.

**Comment by albanD** [comment]
Note that we still support 3.8+ in PyTorch. So only the version of CPython for which Numpy 2.0 will be released need to be updated. Based on the versions available for the beta, I guess we will need to change the 3.9+ builds of PyTorch only.

I think we should:
1. Locally ensure that all is good to compile and sanity checks
2. Update the trunk builds and make sure our CI is all good for NumPy 2.0
3.  Cherry pick this into the release branch

@atalman I can take care of 1 today, would someone on the Release/Infra team be able to work on 2 and 3 so that we can get this done for the next RC?

**Comment by rgommers** [comment]
Note that numpy `2.0.0rc1` is out now, so the ABI is officially frozen. The only relevant different is that `pybind11<2.12.0` raises an error, but PyTorch already upgraded to pybind11 2.12.0. So I think the build dependency can be upgraded from `2.0.0b1` (as done in https://github.com/pytorch/builder/pull/1747) to `2.0.0rc1`.

**Comment by albanD** [comment]
Thanks for the info Ralf!
@atalman what is the 2.3 status for this? Anything outstanding or we're on track?

**Comment by atalman** [comment]
@albanD : Binaries should be supporting rc1 for both wheels and conda packages now, since this PR is landed: https://github.com/pytorch/builder/pull/1768

**Comment by albanD** [comment]
Tested the RC from https://dev-discuss.pytorch.org/t/pytorch-release-2-3-0-final-rc-is-available/1995 with both the 2.0 and 1.26 versions and everything is working smoothly.
Also version for python 3.8 is properly compatible with the 1.24 release of numpy that is the latest available there.
I'll keep this open until 2.3 is released successfully and then will close.

**Comment by jakirkham** [comment]
Thanks for all of your work here! 🙏

> Binaries should be supporting rc1 for both wheels and conda packages now, since this PR is landed: [pytorch/builder#1768](https://github.com/pytorch/builder/pull/1768) will be cherry-picking this into release and generating an rc

Would it be possible to move the Conda packages to a different label (like `dev` or similar)?

Currently users are picking them up unintentionally when installing from the `pytorch` channel: https://github.com/pytorch/builder/issues/1776

**Comment by atalman** [comment]
@jakirkham removed numpy from pytorch and pytorch-conda conda channel. Thank you for reporting this issue.
pytorch CI is currently using https://anaconda.org/atalman/numpy for numpy 2.0.0rc1 builds until anaconda releases numpy 2.0

**Comment by PaliC** [comment]
Validated pytorch 2.3.0 from ` https://download.pytorch.org/whl/test/cu121` works for `numpy==2.0.0rc1` and `numpy==1.26.4`

**Comment by jakirkham** [comment]
> removed numpy from pytorch and pytorch-conda conda channel. Thank you for reporting this issue. pytorch CI is currently using https://anaconda.org/atalman/numpy for numpy 2.0.0rc1 builds until anaconda releases numpy 2.0

Thanks @atalman! 🙏

Please feel free to close issue: https://github.com/pytorch/builder/issues/1776

Also thanks for all your and the teams work on NumPy 2 support

Sounds good

**Comment by OsitalGele** [comment]
Hi, torch==2.3.1+cu118 still does not support numpy 2. How can I fix? thanks

**Comment by albanD** [comment]
Can you open a separate issue with details on your environment and what the issue is please?

**Comment by dstein64** [comment]
@OsitalGele, are you using Windows? If so, your issue might relate to what's reported in some of the comments in #128860.

**Comment by callej** [comment]
The following code shows compatibility issues with NumPy 2.0

```
import torch
ints_to_tensor = torch.tensor([0, 1, 2, 3, 4])
```

**Error Message:**
_A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'._

_UserWarning: Failed to initialize NumPy: ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
ints_to_tensor = torch.tensor([0, 1, 2, 3, 4])_
<br>

**Environment:**
- Windows 11 Pro, 23H2, Build: 22621.3880
- Python 3.12.4
- torch 2.3.1
- numpy 2.0.0

<br>

Any solutions?

**Comment by nawfalhasan** [comment]
I still get this error

> A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

> If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

> Traceback (most recent call last):  File "D:\Projects\translation\app.py", line 1, in <module>
    from transformers import MarianMTModel, MarianTokenizer
  File "D:\Projects\translation\venv\Lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "D:\Projects\translation\venv\Lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "D:\Projects\translation\venv\Lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "D:\Projects\translation\venv\Lib\site-packages\transformers\utils\generic.py", line 462, in <module>
    import torch.utils._pytree as _torch_pytree
  File "D:\Projects\translation\venv\Lib\site-packages\torch\__init__.py", line 2120, in <module>
    from torch._higher_order_ops import cond
  File "D:\Projects\translation\venv\Lib\site-packages\torch\_higher_order_ops\__init__.py", line 1, in <module>
    from .cond import cond
  File "D:\Projects\translation\venv\Lib\site-packages\torch\_higher_order_ops\cond.py", line 5, in <module>
    import torch._subclasses.functional_tensor
  File "D:\Projects\translation\venv\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 42, in <module>
    class FunctionalTensor(torch.Tensor):
  File "D:\Projects\translation\venv\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 258, in FunctionalTensor
    cpu = _conversion_method_template(device=torch.device("cpu"))
D:\Projects\translation\venv\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


What's the issue with pybind11? I am on PyTorch 2.4 which was released yesterday.

**Comment by Lords08** [comment]
The following code shows compatibility issues with NumPy 2.0 too:
`import torch
img = torch.from_numpy(img).to(cls.device)`

`Numpy is not available

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

cpu = _conversion_method_template(device=torch.device("cpu"))
c:\Users\SISFO\.virtualenvs\len-ai-server-lvANfvbP\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))`

**Comment by malfet** [comment]
Making sure that PyTorch Windows builds are compatible with NumPy-2.0  tracked in https://github.com/pytorch/pytorch/issues/131668

**Comment by FlorisCalkoen** [comment]
> I still get this error when importing. I'm on MacOS 14.6.1, Python 3.12.6, installing via `micromamba create -n torch 'pytorch::pytorch' torchvision -c pytorch`

...
 

Same here.
