### ISSUE TITLE
Typo in pytorch docs (torchvision.transforms Generic Transforms)

### ISSUE THREAD

**Issue by svenrdz** [pytorch/pytorch#1073]
Hey,
I didn't know where to point this issue, so I'll do it here.
I just noticed a typo [there](http://pytorch.org/docs/torchvision/transforms.html#generic-transofrms)
It should be Transforms, not Transofrms

**Comment by soumith** [comment]
thanks, fixed via https://github.com/pytorch/pytorch/commit/2d750b9da5bd305312cf92539a173a1d24ca26e6
The docs should regenerate shortly.
