### ISSUE TITLE
Patch release before v2.1.0?

### ISSUE THREAD

**Issue by wfondrie** [pytorch/pytorch#107303]
### 🐛 Describe the bug

Hi PyTorch team 👋 - we've run into a bug in our tool Casanovo where `NaN`s would randomly appear in the output of our Transformer layers only with `torch.no_grad()` (https://github.com/Noble-Lab/casanovo/issues/186). The issue exists as of v2.0.1, but as far as we can tell has been fixed in the nightly builds.

Are there plans for a new patch release before v2.1.0, which looks like it is currently scheduled for October? If you'd like, I'm also happy to document the bug further, but I suspect it has been addressed as a at least a subset of another issue. Thanks!

### Versions

N/A

cc @seemethere @malfet

**Comment by malfet** [comment]
@wfondrie can you please share a reproducer, as well as whether issues happens on CUDA, cpu or MPS, using eager mode or torch.compile feature? This will help us determine severity of the issue and whether or not it warrants patch release (though to be frank, most likely it is not, at this point)

**Comment by melihyilmaz** [comment]
Hi @malfet - you can find the torch-only reproducer in [this](https://colab.research.google.com/drive/1mRZsQkGzb5Wn9CQAP0KZS9X_Sn3HWVgV?usp=sharing) colab notebook where we produce a NaN output from a non-NaN input and a single `TransformerEncoderLayer` initialized with non-NaN weights.

The issue happens only on CUDA and not on cpu. We suspect that Fast path calculation in `forward()` might be the culprit. Thanks!

**Comment by malfet** [comment]
Considering that 2.1.0 is just a few weeks away, closing this one.
Please note, that with v2.1.0, plans is to have 2 patch releases before v2.2.0.
