### ISSUE TITLE
[Inductor][cpu] models perf regression on 2023_08_02 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#107368]
### 🐛 Describe the bug

tracked in https://github.com/pytorch/pytorch/issues/93531#issuecomment-1665314880

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/yudongsi/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/yudongsi/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link=blue vlink=purple>

name | batch_size_new | speed_up_new | inductor_new | eager_new | batch_size_old | speed_up_old | inductor_old | eager_old | Ratio   Speedup(New/old) | Eager   Ratio(old/new) | Inductor   Ratio(old/new)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
densenet121 | 64 | 1.583203 | 0.23211438 | 0.367484183 | 64 | 2.030915 | 0.187898787 | 0.381606465 | 0.78 | 1.04 | 0.81
phlippe_densenet | 128 | 1.717268 | 0.022964243 | 0.03943576 | 128 | 2.014148 | 0.020431572 | 0.04115221 | 0.85 | 1.04 | 0.89
squeezenet1_1 | 16 | 1.781896 | 0.008795598 | 0.015672841 | 16 | 2.566951 | 0.006104736 | 0.015670558 | 0.69 | 1 | 0.69
timm_vovnet | 32 | 1.43826 | 0.13317279 | 0.191537097 | 32 | 1.618509 | 0.118200374 | 0.191308369 | 0.89 | 1 | 0.89
adv_inception_v3 | 128 | 1.786474 | 0.49242359 | 0.879701941 | 128 | 2.188721 | 0.40113951 | 0.877982469 | 0.82 | 1 | 0.81
dla102 | 128 | 1.847806 | 0.623004438 | 1.151191339 | 128 | 2.106416 | 0.542749545 | 1.143256326 | 0.88 | 0.99 | 0.87
ese_vovnet19b_dw | 128 | 2.155335 | 0.194882305 | 0.420036653 | 128 | 2.530445 | 0.165582818 | 0.418998214 | 0.85 | 1 | 0.85
ghostnet_100 | 128 | 1.895371 | 0.098562741 | 0.186812961 | 128 | 2.222604 | 0.083697114 | 0.18602554 | 0.85 | 1 | 0.85
gluon_inception_v3 | 128 | 1.789646 | 0.494370035 | 0.884747356 | 128 | 2.192417 | 0.403465664 | 0.884564981 | 0.82 | 1 | 0.82
inception_v3 | 128 | 1.824735 | 0.492880361 | 0.899376046 | 128 | 2.212821 | 0.40370852 | 0.893334691 | 0.82 | 0.99 | 0.82
pnasnet5large | 16 | 2.225022 | 0.385175769 | 0.85702456 | 16 | 2.597543 | 0.33161666 | 0.861388534 | 0.86 | 1.01 | 0.86
tf_mixnet_l | 128 | 1.561336 | 0.417719035 | 0.652199767 | 128 | 1.816107 | 0.358174338 | 0.650482922 | 0.86 | 1 | 0.86

</body>

</html>

Repro:

bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) single inference performance **suite model** float32 first static default 0

### Versions

target:

torchbench : 770d5cf7
torch :  2.1.0a0+gitc89b169
torchvision :  0.16.0a0+58366ab
torchtext :  0.16.0a0+c11d758
torchaudio :  2.1.0a0+dc83b38
torchdata :  0.7.0a0+1d231d1
dynamo_benchmarks : f228c8b

refer:

torchbench : 770d5cf7
torch :  2.1.0a0+git0ff243f
torchvision :  0.16.0a0+58366ab
torchtext :  0.16.0a0+c11d758
torchaudio :  2.1.0a0+dc83b38
torchdata :  0.7.0a0+1d231d1
dynamo_benchmarks : f228c8b

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by XiaobingSuper** [comment]
@ESI-SYD I checked that data has been recovered, Please help double-check it.
