### ISSUE TITLE
[docs] should explain `num_directions` in the RNN and LSTM docstrings

### ISSUE THREAD

**Issue by samuela** [pytorch/pytorch#10741]
Right now `num_directions` is used extensively in the documentation without any actual explanation for what it means. (See https://pytorch.org/docs/stable/nn.html#torch.nn.RNN) I'm assuming that this means 1 by default, and 2 for bidirectional models. But this is not explained anywhere, and I can't even be sure that it's correct.

**Comment by rohan-varma** [comment]
It looks like 2 for bidirectional and 1 for default is correct: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L31

**Comment by vishwakftw** [comment]
This can be closed now.
