### ISSUE TITLE
Problems of torch.multinomial

### ISSUE THREAD

**Issue by min-jean-cho** [pytorch/pytorch#107406]
### 🐛 Describe the bug

There are few theoretical problems with sampling from multinomial distribution using `torch.multinomial`.

**Multinomial distribution**
x ~ Multinomial(n, p)
 

- n: the number of independent trials (e.g., n=100 rolls of a dice)

- K: the number of classes (e.g., K=6 for a dice, K=2 for a coin)
the outcome of each trial falls into one of K classes

- p: [p_1, p_2, …, p_k, …, p_K], probabability parameter, a vector 
p_k = the probability that the outcome of a single trial falls into class k 
p_1 + p_2 + ... + p_K = 1

- x: [x_1, x_2, …, x_k, …, x_K], a sample point, a vector
x_k = the number of trials for which the outcome falls into class k
x_1 + x_2 + … + x_K = n

**Problem 1**
The sample point x of multinomial distribution is a vector [x_1, x_2, …, x_K] as noted above.
However, `torch.multinomial(replacement=True)` generates "outcomes of n trials" instead of random variable x that consists of "the number of trial for which the outcome falls into class k". This is very confusing as exemplified here, https://discuss.pytorch.org/t/trying-to-understand-the-torch-multinomial/71643. 

**Example**
```python
import torch

p = torch.tensor([2/10, 3/10, 5/10])
n = 10
out = torch.multinomial(p, n, replacement=True)
print(out) # tensor([1, 2, 1, 2, 2, 2, 1, 2, 0, 2])
 
# User needs to convert out (the outcomes of n trials) 
# to random variable using method as suggested here, 
# https://discuss.pytorch.org/t/trying-to-understand-the-torch-multinomial/71643/4
# This leads to unsound sampling from multinomial distribution
# without requiring user's further understanding and care
x = out.unique(return_counts=True)[1]
print(x) # tensor([1, 3, 6])
```

**Problem 2**
`replacement` option should be removed. `torch.multinomial(replacement=False)` by default. Sampling without replacement makes no sense here.

**Example**
```python
import torch
 
p = torch.tensor([2/10, 3/10, 5/10])
n = 3
out = torch.multinomial(p, n)
print(out) # tensor([1, 0, 2])
 
x = out.unique(return_counts=True)[1]
print(x) # tensor([1, 1, 1])
```

1. By definition of multinomial probability distribution, each trial is independent. Thus, we can observe any outcomes (according to p_k) at any trials. If `replacement=False`, then each trial is not independent (e.g., we cannot observe eye 3 after we once observe eye 3).
2. By definition of multinomial probability distribution, n > 0 and there is no constraint on n. If `replacement=False`, then n is constrained to n <= K.
3. If `replacement=False`, the sample point x, [x_1, ..., x_K], is always [1, …, 1]. In other words, regardless of the values of the parameter p, [p_1, …, p_K], `torch.multinomial(replacement=False)` always behaves in a uniform fashion as if p were [1/K, …, 1/K].
 
Above reasons simply make no sense to multinomial distribution.

### Versions

master

cc @fritzo @neerajprad @alicanb @nikitaved @svekars @carljparker @pbelevich

**Comment by min-jean-cho** [comment]
While digging deeper, I've found a similar issue had been raised https://github.com/pytorch/pytorch/issues/36036 in the past. I think the problem is arising from general confusion of `torch.multinomial` with `numpy.random.choice` (which are not equivalent) as I had previously commented [here](https://github.com/pytorch/pytorch/issues/50034#issuecomment-1569353685). I am curious to know how users had been using `torch.multinomial`, if they are aware of the distinction or have been using incorrectly without knowingly. Would love to hear back comments, thanks!

**Comment by mmattb** [comment]
I did indeed find the replacement=False default quite surprising. Having said that: if the owners changed the default I wouldn't complain too loud. Alternately they could remove the option and provide a second function that performs without replacement.

**Comment by guptaaryan16** [comment]
@min-jean-cho I am interested in working on this issue but am a bit new to PyTorch contributions. So can you help me with this issue if possible and also I wanted to know if this issue is available for docathon.

cc @svekars @carljparker

**Comment by min-jean-cho** [comment]
Hi @guptaaryan16, I'll be working on this issue

**Comment by min-jean-cho** [comment]
Hi, could anyone help provide source file to https://pytorch.org/docs/stable/generated/torch.multinomial.html#torch.multinomial, or which file to edit? Thanks. @svekars @carljparker

**Comment by svekars** [comment]
@min-jean-cho - it is here: https://github.com/pytorch/pytorch/blob/4e67c69a7da80b76740526bc1886582782e9c972/torch/_torch_docs.py#L7788
