### ISSUE TITLE
[feature request][pytorch] finfo as in numpy and finfo for default dtype

### ISSUE THREAD

**Issue by sytrus-in-github** [pytorch/pytorch#10742]
## Issue description

It is nice that pytorch now has `dtype` attribute for tensors and a default dtype so that we can easily switch between different precisions. However, as I understand it:

1. if we want to define e.g. a small value `eps` that is the smallest representable positive value of double, right now we have to switch to numpy and use sth like `np.finfo(np.float64).tiny`.
2. if we want this value to depend on the current default dtype, we have to call `torch.get_default_dtype()`, convert it somehow to numpy dtype, then use `np.finfo`. This must be performed every time we need this number unless we are sure the default dtype is not changed in between.

It would thus be very nice if we have sth like `torch.finfo` similar to `np.finfo` that additionally takes the current default pytorch dtype as the default argument so as to have a hassle-free and efficient way of solving the above problems.

**Comment by alicanb** [comment]
If you don't care about where the code lives: https://github.com/pytorch/pytorch/blob/ddf187c198f8e249e78351ba94e773bf9d21de3a/torch/distributions/utils.py#L20

**Comment by sytrus-in-github** [comment]
@alicanb Thanks! I didn't know that this exists.

However, apart from `tiny` I also use `max` `min` to clamp `inf` and `-inf` to finite values. I guess a proper `finfo` implementation is still beneficial.

**Comment by ragulpr** [comment]
Seconded this. I find myself having more and more dependencies on `torch.distributions.utils._finfo` which is obviously very useful but maybe not stable? I also find myself needing max, min and others.

**Comment by soumith** [comment]
`torch.finfo` would be a good addition I guess, if `numpy` has it.

**Comment by ragulpr** [comment]
Would be great. I guess it's important to get this right as it would be basis for future test-infrastructure. Numpy finfo [currently contains](https://github.com/numpy/numpy/blob/master/numpy/core/getlimits.py):

```
    bits : int
        The number of bits occupied by the type.
    eps : float
        The smallest representable positive number such that
        ``1.0 + eps != 1.0``.  Type of `eps` is an appropriate floating
        point type.
    epsneg : floating point number of the appropriate type
        The smallest representable positive number such that
        ``1.0 - epsneg != 1.0``.
    iexp : int
        The number of bits in the exponent portion of the floating point
        representation.
    machar : MachAr
        The object which calculated these parameters and holds more
        detailed information.
    machep : int
        The exponent that yields `eps`.
    max : floating point number of the appropriate type
        The largest representable number.
    maxexp : int
        The smallest positive power of the base (2) that causes overflow.
    min : floating point number of the appropriate type
        The smallest representable number, typically ``-max``.
    minexp : int
        The most negative power of the base (2) consistent with there
        being no leading 0's in the mantissa.
    negep : int
        The exponent that yields `epsneg`.
    nexp : int
        The number of bits in the exponent including its sign and bias.
    nmant : int
        The number of bits in the mantissa.
    precision : int
        The approximate number of decimal digits to which this kind of
        float is precise.
    resolution : floating point number of the appropriate type
        The approximate decimal resolution of this type, i.e.,
        ``10**-precision``.
    tiny : float
        The smallest positive usable number.  Type of `tiny` is an
        appropriate floating point type.
```
For me; 

* eps
* tiny
* max

Does just fine for now to be honest because I assume `torch.finfo(x).log()` for example would give `maxexp` but at relevant base. 

Relevant: 
Ongoing changes to finfo in [numpy](https://github.com/numpy/numpy/pull/8504) and of course https://en.cppreference.com/w/cpp/types/numeric_limits

**Comment by ragulpr** [comment]
Working on it. Just started with moving things.
https://github.com/ragulpr/pytorch/tree/extend-finfo

I'm going into the deep end when thinking about unit tests.
Do we define the constants w.r.t the C++ assumed [numeric limits](https://en.cppreference.com/w/cpp/types/numeric_limits) or based on torch.eq-operator? And where can I find those definitions? 

Examples;
```
import torch
from torch import finfo

x = torch.tensor([[0]],dtype=torch.float64)

x+finfo(x).eps!=x # True
x+finfo(x).eps/2==x # True
x+finfo(x).tiny==x # True
x+(finfo(x).eps-finfo(x).tiny)==x # False! Why?
finfo(x).max+finfo(x).tiny==float('Inf') # TODO
```

Any pointers @fritzo? 😃

**Comment by fritzo** [comment]
See https://github.com/pytorch/pytorch/blob/master/torch/distributions/utils.py#L8

**Comment by benoitsteiner** [comment]
@ragulpr: I started looking into this yesterday. I started to create a new FInfo class in aten/src/ATen/core, and add an accessor in aten/src/ATen/core/Type.h to create and return a FInfo object for the current Type. WDYT ?

**Comment by soumith** [comment]
@benoitsteiner that sounds good to me.
@ragulpr @benoitsteiner between both of you, please figure out who's working on it, so that the other doesn't duplicate work and gets frustrated :)

**Comment by ragulpr** [comment]
Sounds good @benoitsteiner! Sounds like a more permanent solution so I suggest you take over. Any examples on usage? 
One thing that would be a plus over the current version would be if Finfo eps for example would be a torch scalar of appropriate type.

**Comment by benoitsteiner** [comment]
@ragulpr: Once I'm done we should be able to write code like this:
```
x = torch.randn(2, 3)
finfo = x.dtype.finfo
```
finfo will contain information about the dtype, such as the epsilon, min and max values, and so on. The code is in place, I need to add a few tests and cleanup the code before creating a pull request. In the meantime, we should gather a list of attributes we want to export in the finfo. For now I have bits (number of bits used to encode the data, e.g 32 for floats). I plan to add min, max and epsilon. What else would be useful ?

**Comment by alicanb** [comment]
@benoitsteiner tiny and eps are currently used in `distributions.utils._finfo`

**Comment by sytrus-in-github** [comment]
@benoitsteiner Thanks for working on this! I also use `maxexp` and `minexp`. I guess it would be consistent to use the `numpy.finfo` as a reference.

Also, in this case, what will happen if I call it with some integer type e.g. `torch.int.finfo`? In numpy there is also a `numpy.iinfo` function to get dtype info for integer types. Maybe we could merge this 2 and instead write sth like `dtypeinfo = x.dtype.info` but then `dtypeinfo` will be different for int and float types.

**Comment by ragulpr** [comment]
Sounds very good! Only reservation is I agree with @sytrus-in-github that it sure makes sense to merge `iinfo` and `finfo` for the purpose of automation. 

I'm not in the know about the naming traditions of numeric packages but maybe numpy-style `finfo` and `iinfo` does not need to be strictly followed? Maybe something more like `numeric_limits`?  Because `info` of `x.dtype.info.eps` seems a little vague no?

**Comment by gchanan** [comment]
IMO we should at least match NumPy semantics, i.e. have a `torch.finfo(dtype)` that throws if you pass in an integral dtype and `torch.iinfo(dtype)` that throws if you pass in a floating point dtype.  It seems fine to add additions to that, but they have to be useful.  Having an `finfo` or `iinfo` property on dtype seems error prone (though an intersection of a properties on those two structures could be useful).

**Comment by sytrus-in-github** [comment]
If we want to align with NumPy semantics, since [`numpy.iinfo`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.iinfo.html) provides only `min`, `max`, `bits` properties, which are all covered by [`numpy.finfo`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.finfo.html), we could have sth like:

- `torch.dtype_info(dtype=torch.get_defaut_dtype())` that just returns `min`, `max`, `bits` for all integral and floating point dtype.
- `torch.iinfo(dtype)` mimics [`numpy.iinfo`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.iinfo.html) and raise error for floating dtypes.
- `torch.finfo(dtype=torch.get_defaut_dtype())` mimics [`numpy.finfo`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.finfo.html) (except we might not need `machar`) and raise error for integral dtypes.

As for `torch.dtype` attributes, why no add directly the available dtype information directly as properties? Sth like `torch.double.eps` and `torch.short.max` will be fine but e.g. `torch.long.eps` will raise an error since it is not available.

What do you think?

**Comment by benoitsteiner** [comment]
I've just created a pull request with a partial implementation that adds `torch.iinfo(dtype)` and `torch.finfo(dtype)`. The implementation makes it possible to add a torch.dtype_info(dtype) later on if needed.

**Comment by mruberry** [comment]
PyTorch now has both finfo and iinfo! Closing this issue.
