### ISSUE TITLE
Incorrect code snippet for SavePlanner

### ISSUE THREAD

**Issue by b-chu** [pytorch/pytorch#107490]
### 📚 The doc issue

The following code snippet [here](https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.SavePlanner) is wrong
```
class RenamePlanner(DefaultSavePlanner):
    def set_up_planner(self, state_dict, is_coordinator):
        # prefix all keys with `foo_``
        super().set_up_planner(self, {"foo_" + k: v for k, v in state_dict.items()}, is_coordinator)
```

### Suggest a potential alternative/fix

```
class RenamePlanner(DefaultSavePlanner):
    def set_up_planner(self, state_dict, is_coordinator):
        # prefix all keys with `foo_``
        super().set_up_planner({"foo_" + k: v for k, v in state_dict.items()}, is_coordinator)
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

**Comment by awgu** [comment]
We will accept a PR fixing this if you would like!
