### ISSUE TITLE
`repeat_interleave` does not support tensor indexes on different devices while `repeat` does

### ISSUE THREAD

**Issue by fxmarty** [pytorch/pytorch#107591]
### 🐛 Describe the bug

Hi, the ONNX export of a model using `repeat_interleave` with dynamic shapes fail due to the requirement of the `Tensor.repeat_interleave(repeats: Tuple[Union[Tensor, int]])` tensors to be on the same device. The `Tensor.repeat` operator does not have this requirement. Is this difference intended?

```python
import torch

x = torch.ones(2, 32, 64, 64).to("cuda")
n_repeat = torch.tensor(4).to(torch.int32)

res = x.repeat_interleave(n_repeat, 0)
```
raises `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)`,

while
```python
import torch

x = torch.ones(2, 32, 64, 64).to("cuda")
n_repeat = torch.tensor(4).to(torch.int32)

res = x.repeat(n_repeat, 1, 1, 1)
```
do not.

This is an issue for the ONNX export of `repeat_interleave` on CUDA device where one the indexes of the repeats is dynamic (for example [here](https://github.com/huggingface/transformers/blob/2df24228d68872d79304b932a68cf56de3061f5b/src/transformers/models/sam/modeling_sam.py#L510)) cc @justinchuby

I wonder if the issue comes from the dispatch being on `repeat_interleave_cuda` (instead of ), in turn calling `compute_cuda_kernel` that assumes that the `repeat_ptr` points to data on the device?

### Versions

PyTorch version: 2.1.0.dev20230820+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.9.16 (main, May 15 2023, 23:46:34)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1023-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 510.73.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         2999.998
BogoMIPS:                        5999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] mypy-protobuf==3.4.0
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230820+cu118
[pip3] torch-ort==1.15.0
[pip3] triton==2.0.0
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+e6216047b8          pypi_0    pypi
[conda] torch                     2.1.0.dev20230820+cu118          pypi_0    pypi
[conda] torch-ort                 1.15.0                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by justinchuby** [comment]
Could you share the full stack? The onnx exporter requires all tensors and the model on the same device. Was this possible for you?

**Comment by fxmarty** [comment]
@justinchuby The thing is that the torch.jit.trace (or equivalent) used in torch.onnx.export transforms the `my_tensor.shape[0]` as a Tensor and not a python-native int. So what happens is that a dimension that is passed to `repeat_interleave` is then a Tensor and not an int, and the bug described above arises.

If you'd like to reproduce the full issue:
```
git clone https://github.com/fxmarty/optimum.git
cd optimum && git checkout sam-vision-encoder-onnx
pip install -e .
CUDA_VISIBLE_DEVICES=0 optimum-cli export onnx --model fxmarty/sam-vit-tiny-random --device cuda sam_onnx
```

**Comment by MaanavD** [comment]
Hi @fxmarty ,

We’ve gone ahead and closed this issue because we think it can be resolved with our new `torch.onnx.dynamo_export` api. Please try that instead! If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary.
