### ISSUE TITLE
dynamo: don't graph break on ctx.mark_dirty

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#107593]
### 🐛 Describe the bug

Can we add dynamo support for `torch.autograd.Function::ctx.mark_dirty` without a graph break? It currently graph breaks.

Repro: https://gist.github.com/vkuzo/210b2fdf0e0f14cc01e3b6af6a4c176e
Logs: https://gist.github.com/vkuzo/171e765c492ae5175c558409892c5181

This will be needed for `Float8` training UX.

### Versions

master

cc @ezyang @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @zou3519 @ydwu4 @aakhundov @Xia-Weiwen

**Comment by zou3519** [comment]
was fixed at some point
