### ISSUE TITLE
Running DDP with IPV6 address, the client can not connect to the address. 

### ISSUE THREAD

**Issue by QSHLGZ** [pytorch/pytorch#107563]
### 🐛 Describe the bug

Running DDP processes by the code below
![image](https://github.com/pytorch/pytorch/assets/55902565/f04cc951-292a-48f4-b7d4-47ec4b17c4ef)
The error is:
![image](https://github.com/pytorch/pytorch/assets/55902565/ce8af7bc-d512-43a6-8013-c682e3c6fb06)
The codes in testipv6.py are shown in the following picture, just one line.
![image](https://github.com/pytorch/pytorch/assets/55902565/d85d881b-2427-4a94-a005-c87196471ac8)
The ipv6 address is found by command ifconfig. The ip address with port can be connectted by socket.socket in python. But in elastic launch, it can't be connectted.

### Versions

[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.11.1
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] torch==2.1.0.dev20230810+cpu
[pip3] torchvision==0.15.1
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

**Comment by QSHLGZ** [comment]
@wanchaol Dear sir, when I pass the IPV6 address to torch.distributed.run, the error shown above appeared. Whether the device is cpu or cuda, the error is still here. And, I found the whole process stucked in the elastic launch, (socket.cpp) and not even goes into the train script. The IPV6 address I passed can be connected by 'socket.socket' which is a python api with one more parameter 'network card name' but this parameter can not be found in torch.distributed.run. Could you please help me to solve this problem.

**Comment by awgu** [comment]
I am not sure what is happening, but a repro could be helpful.
