### ISSUE TITLE
Fx Graph nodes generated via aot_module have empty 'stack_trace' attributes

### ISSUE THREAD

**Issue by Adam27X** [pytorch/pytorch#107599]
### 🐛 Describe the bug

I'm using aot_function/aot_module to generate Fx Graphs for a compilation flow. For my use case, generating a backward pass graph is essential so (as far as I'm aware) using aot is really my only option.

When handling nodes of the form `view = mul_3.view([5, 80, 80, 4, 5])` I would like to be able to reference the original source in case it tells me any important information about the constants used in the `view` (are these constants written directly by the user or are they derived from some shape?). I think `node.stack_trace` would provide me with this context but it shows up empty.

### Minified repro

```
import torch
import functorch
from functorch.compile import aot_function, aot_module, make_boxed_func
from typing import List
import torch._dynamo
from torch._dynamo.backends.common import aot_autograd

device = torch.device('cuda')

class test_model(torch.nn.Module):

    def __init__(self):
        super().__init__()

    def forward(self, x):
        return torch.pow(x,3)

model = test_model()
model.eval()

x = torch.rand([5], device=device)
x = x.requires_grad_(True)

torch._dynamo.config.verbose = True
torch._dynamo.reset()

graph_modules = []

def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
  graph_modules.append(gm)
  return make_boxed_func(gm.forward)

model_aot = aot_module(model, fw_compiler=my_compiler, bw_compiler=my_compiler)
result_aot = model_aot(x)
result_backward_aot = torch.autograd.grad(result_aot.sum(),x,retain_graph=True)[0]

forward_graphmodule = graph_modules[0]
for node in forward_graphmodule.graph.nodes:
    if node.stack_trace:
        print(node.stack_trace)

backward_graphmodule = graph_modules[1]
for node in backward_graphmodule.graph.nodes:
    if node.stack_trace:
        print(node.stack_trace)
```

However all of the node.stack_trace objects are `None`. I noticed a similar issue in https://github.com/pytorch/pytorch/issues/90276, which suggested wrapping `my_compiler` with `aot_autograd` as follows:

`my_compiler = aot_autograd(fw_compiler=my_compiler,bw_compiler=my_compiler)`

but that change didn't make any difference.

### Versions

The repro provided above was run from a build of PyTorch from ToT on Friday at the following commit: 

commit 139437bb84608507fdaabdca1fdec709e654a8ef (origin/main, origin/HEAD)
Author: JackCaoG <jackcao@google.com>
Date:   Fri Aug 18 16:58:05 2023 +0000

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by wconstab** [comment]
I'm not sure if we expect stacktraces to exist when using the 'aot_module' entrypoints directly.  More generally, not sure we intend for 'aot_module' to be used as a user-facing trace api.  I assume you already tried using torch.compile/export unsuccessfully and are trying to work around something by doing this, but if not then you should start there.  

cc
@ezyang @SherlockNoMad

**Comment by Adam27X** [comment]
> More generally, not sure we intend for 'aot_module' to be used as a user-facing trace api. I assume you already tried using torch.compile/export unsuccessfully and are trying to work around something by doing this, but if not then you should start there.

Thanks for your reply. For my use case I need to generate an Fx Graph of both the forward and backward passes. I initially thought that only `aot_module`/`aot_function` can support the backward pass in this way -- these methods have separate `fw_compiler` and `bw_compiler` options whereas `torch.compile` doesn't. However, I'm looking deeper into the documentation and now I've found:

`torch.compile(..., backend="aot_eager")`

which claims to trace the backward graph (https://pytorch.org/docs/stable/dynamo/faq.html). Maybe that interface will resolve this issue...I'll try that next.

Some other related info here: https://pytorch.org/docs/stable/dynamo/custom-backends.html

Perhaps I can wrap `my_compiler` with `aot_autograd` and pass that result to `torch.compile` directly. I'll try that too.

**Comment by SherlockNoMad** [comment]
aot_module is not intended to be directly used by user. aot_function or aot_module_simplified should have a better support.

**Comment by Adam27X** [comment]
I bottomed out on this today with some success. Here's a summary of what I found:

Recall that I have this custom compiler so I can process each graph module after they're compiled.

```
graph_modules = []

def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
  graph_modules.append(gm)
  return make_boxed_func(gm.forward)
```

Here's the original approach. This approach fails to provide the stack_trace node attribute.

```
### AOT Module ###
model_aot = aot_module(model, fw_compiler=my_compiler, bw_compiler=my_compiler)
result_aot = model_aot(arg0, arg_1, kw_arg0=kw_arg0, kw_arg1=kw_arg1)
```

Here's the same approach using `aot_module_simplified` instead. I find this API clunkier than `aot_module` so it seems strange to me that this one is the one that is meant to be user facing (note the lack of kw args, etc.). Regardless, the result here is the same: it fails to provide the stack_trace node attribute.

```
### AOT Module Simplified ###
aot_simplified_args = [arg0, arg1, kw_arg0, kw_arg1]
model_aot = aot_module_simplified(model, aot_simplified_args, fw_compiler=my_compiler, bw_compiler=my_compiler)
result_aot = model_aot(*aot_simplified_args)
```

Here's if we use `torch.compile` with the `aot_eager` backend. For my use case I still need to obtain the Fx graphs, which means I had to reverse engineer what `aot_eager` is doing and wrap that approach into my own compiler. This surely isn't meant to be used this way but it does provide the stack traces!

```
### torch.compile with 'aot_eager' backend ###
from torch._dynamo.backends.debugging import boxed_nop

def aot_eager_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    graph_modules.append(gm)
    return boxed_nop(gm, example_inputs)

aot_eager_compiler = aot_autograd(fw_compiler=aot_eager_compiler, bw_compiler=aot_eager_compiler)

model_aot = torch.compile(model, backend=aot_eager_compiler)
result_aot = model_aot(arg0, arg_1, kw_arg0=kw_arg0, kw_arg1=kw_arg1)
```

And finally, best of all: use `torch.compile` with my own compiler wrapped by `aot_autograd`. This was the solution I was looking for.

```
### torch.compile with a custom backend wrapped by aot_autograd ###
my_compiler = aot_autograd(fw_compiler=my_compiler, bw_compiler=my_compiler)

model_aot = torch.compile(model, backend=my_compiler)
result_aot = model_aot(arg0, arg_1, kw_arg0=kw_arg0, kw_arg1=kw_arg1)
```

One other minor annoyance here: when I invoke `model_aot` the general order of the parameters is something like: model.parameters, model.buffers, model.forward parameters. However `aot_module` and `torch.compile` seem to use different strategies to order model.buffers. I was able to reorder the declarations of my buffers such that the two methods agree, which implies that `torch.compile` cares about the order of these declarations and `aot_module` doesn't. This is just an FYI -- the issue I originally brought up here is resolved so we can close this one out.
