### ISSUE TITLE
Ran into flatbuffer verifier problem while compiling tag v2.0.1 in win64

### ISSUE THREAD

**Issue by bones0** [pytorch/pytorch#107537]
### 🐛 Describe the bug

I have an old card (NVIDIA Tesla K40s) so I have to compile all myself (compute capability 3.5). Now, this worked for 2.1.0, but no other wheel does seem to support that already in the environments I used. Now, compiling 2.0.1 runs into the problem described here: https://github.com/google/flatbuffers/issues/7841

The solution there is:
_[dbaileychess](https://github.com/dbaileychess) commented [Mar 3, 2023](https://github.com/google/flatbuffers/issues/7841#issuecomment-1453024929)

Looks like you are using the wrong runtime libraries, which are different from the version you generated the code from. They have to be the same._

Triage decision point 1: Now, OK, should those runtime libraries be included in your repository or do I have to get them elsewhere? 

Since 2.1.0 *did* compile I seem to have not made a fundamental error. My conda-environment does not contain a package named "flatbuffers" so I rekon I did not pull in a too-new-version this way.

(The environment collected contains my 2.1.0 version)

### Error logs

FAILED: caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/mobile/flatbuffer_loader.cpp.obj
"C:\PROGRA~1\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe"  /nologo /TP -DAT_PER_OPERATOR_HEADERS -DCPUINFO_SUPPORTED_PLATFORM=1 -DFMT_HEADER_ONLY=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_EXTERNAL_MZCRC -DUSE_FLASH_ATTENTION -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE=1 -D_UCRT_LEGACY_INFINITY -Dtorch_cpu_EXPORTS -IC:\repos\pytorch\build\aten\src -IC:\repos\pytorch\aten\src -IC:\repos\pytorch\build -IC:\repos\pytorch -IC:\repos\pytorch\cmake\..\third_party\benchmark\include -IC:\repos\pytorch\third_party\onnx -IC:\repos\pytorch\build\third_party\onnx -IC:\repos\pytorch\third_party\foxi -IC:\repos\pytorch\build\third_party\foxi -IC:\repos\pytorch\torch\csrc\api -IC:\repos\pytorch\torch\csrc\api\include -IC:\repos\pytorch\caffe2\aten\src\TH -IC:\repos\pytorch\build\caffe2\aten\src\TH -IC:\repos\pytorch\build\caffe2\aten\src -IC:\repos\pytorch\build\caffe2\..\aten\src -IC:\repos\pytorch\torch\csrc -IC:\repos\pytorch\third_party\miniz-2.1.0 -IC:\repos\pytorch\third_party\kineto\libkineto\include -IC:\repos\pytorch\third_party\kineto\libkineto\src -IC:\repos\pytorch\aten\..\third_party\catch\single_include -IC:\repos\pytorch\aten\src\ATen\.. -IC:\repos\pytorch\c10\.. -IC:\repos\pytorch\third_party\pthreadpool\include -IC:\repos\pytorch\third_party\cpuinfo\include -IC:\repos\pytorch\third_party\fbgemm\include -IC:\repos\pytorch\third_party\fbgemm -IC:\repos\pytorch\third_party\fbgemm\third_party\asmjit\src -IC:\repos\pytorch\third_party\ittapi\src\ittnotify -IC:\repos\pytorch\third_party\FP16\include -IC:\repos\pytorch\third_party\fmt\include -IC:\repos\pytorch\build\third_party\ideep\mkl-dnn\third_party\oneDNN\include -IC:\repos\pytorch\third_party\ideep\mkl-dnn\third_party\oneDNN\src\..\include -IC:\repos\pytorch\third_party\flatbuffers\include -external:I C:\repos\pytorch\build\third_party\gloo -external:I C:\repos\pytorch\cmake\..\third_party\gloo -external:I C:\repos\pytorch\cmake\..\third_party\googletest\googlemock\include -external:I C:\repos\pytorch\cmake\..\third_party\googletest\googletest\include -external:I C:\repos\pytorch\third_party\protobuf\src -external:I C:\repos\pytorch\third_party\XNNPACK\include -external:I C:\repos\pytorch\third_party\ittapi\include -external:I C:\repos\pytorch\cmake\..\third_party\eigen -external:I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -external:I C:\repos\pytorch\third_party\ideep\mkl-dnn\third_party\oneDNN\include -external:I C:\repos\pytorch\third_party\ideep\include -external:I C:\repos\pytorch\caffe2 -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DHAVE_AVX2_CPU_DEFINITION /O2 /Ob2 /DNDEBUG /w /bigobj -DNDEBUG -MD -DCAFFE2_USE_GLOO -DTH_HAVE_THREAD /EHsc /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -O2 -DCAFFE2_BUILD_MAIN_LIB -DONNX_BUILD_MAIN_LIB -openmp:experimental -std:c++17 /showIncludes /Focaffe2\CMakeFiles\torch_cpu.dir\__\torch\csrc\jit\mobile\flatbuffer_loader.cpp.obj /Fdcaffe2\CMakeFiles\torch_cpu.dir\ /FS -c C:\repos\pytorch\torch\csrc\jit\mobile\flatbuffer_loader.cpp
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(491): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(491): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(492): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(492): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(493): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(493): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(498): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(498): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(609): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(609): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(610): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(610): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(611): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(611): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(616): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(616): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1213): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1213): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1305): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1305): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1306): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1306): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1309): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1309): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1392): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1392): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1470): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1470): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1556): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1556): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1819): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1819): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1824): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(1824): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2045): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2045): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2308): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2308): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2314): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2314): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2318): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2318): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2330): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2330): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2331): error C2672: "flatbuffers::Table::VerifyField": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/table.h(115): note: kann "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2331): note: "bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier &,flatbuffers::voffset_t,size_t) const" erwartet, dass 3 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2460): error C2672: "flatbuffers::Verifier::Verify": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/verifier.h(88): note: kann "bool flatbuffers::Verifier::Verify(const size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2460): note: "bool flatbuffers::Verifier::Verify(const size_t) const" erwartet, dass 1 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2463): error C2672: "flatbuffers::Verifier::Verify": keine übereinstimmende überladeC:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/verifier.h(88): note: kann "bool flatbuffers::Verifier::Verify(const size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2463): note: "bool flatbuffers::Verifier::Verify(const size_t) const" erwartet, dass 1 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2466): error C2672: "flatbuffers::Verifier::Verify": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/verifier.h(88): note: kann "bool flatbuffers::Verifier::Verify(const size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2466): note: "bool flatbuffers::Verifier::Verify(const size_t) const" erwartet, dass 1 Argumente - 2 angegeben werden.
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2469): error C2672: "flatbuffers::Verifier::Verify": keine übereinstimmende überladene Funktion gefunden
C:\repos\pytorch\third_party\flatbuffers\include\flatbuffers/verifier.h(88): note: kann "bool flatbuffers::Verifier::Verify(const size_t) const" sein
C:\repos\pytorch\torch/csrc/jit/serialization/mobile_bytecode_generated.h(2469): note: "bool flatbuffers::Verifier::Verify(const size_t) const" erwartet, dass 1 Argumente - 2 angegeben werden.
[5087/6448] Building CXX object caffe2...rc\jit\mobile\nnc\aot_compiler.cpp.obj
ninja: build stopped: subcommand failed.

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+giteab3b26
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 13.2.0
Clang version: 16.0.6
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla K40c
Nvidia driver version: 463.15
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2400
DeviceID=CPU0
Family=198
L2CacheSize=256
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2401
Name=Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
ProcessorType=3
Revision=15620

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.7.7
[pip3] torch==2.1.0a0+giteab3b26
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.11.4
[pip3] torchsde==0.2.5
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0           py311h2bbff1b_0
[conda] mkl_fft                   1.3.1           py311h743a336_0
[conda] mkl_random                1.2.2           py311heda8569_0
[conda] numpy                     1.23.5          py311h54701ec_0
[conda] numpy-base                1.23.5          py311h0424125_0
[conda] pytorch-lightning         1.7.7                    pypi_0    pypi
[conda] torch                     2.1.0a0+giteab3b26          pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchsde                  0.2.5                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by wconstab** [comment]
afaiu the flatbuffer error is caused by some kind of mismatch between versions of flatbuffer header.

it sounds like from your error log, you are trying to compile this line of torch.JIT code ([mobile_bytecode_generated.h(2466)](https://github.com/pytorch/pytorch/blob/v2.0.1/torch/csrc/jit/serialization/mobile_bytecode_generated.h#L2469C6-L2469C118): error C2672:)
:
```
 return verifier.Verify<torch::jit::mobile::serialization::ComplexDouble>(static_cast<const uint8_t *>(obj), 0);
```

meanwhile you should be finding the headers in `C:\repos\pytorch\third_party\flatbuffers\include`-- can you check if the file there exists and appears compatible with the usage site above?

if so, perhaps you do have another version of flatbuffers somewhere in your sys include path.  if not, perhaps you need to refresh/update your thirdparty submodule refs in pytorch?

**Comment by bones0** [comment]
Well, the headers exist. However, "appears compatible" is a bit hard to tell. I have no other flatbuffers code on the machine.

What I get when I fetch and check the status is a "modified" in lots of third_parties. Does that mean the local copy might not be the right one?

`
(ldm) PS C:\repos\pytorch> git status
HEAD detached at v2.0.1
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   third_party/cpuinfo (new commits)
        modified:   third_party/cudnn_frontend (new commits)
        modified:   third_party/cutlass (new commits)
        modified:   third_party/fbgemm (new commits)
        modified:   third_party/flatbuffers (new commits)
        modified:   third_party/gloo (new commits)
        modified:   third_party/ideep (new commits)
        modified:   third_party/kineto (new commits)
        modified:   third_party/nccl/nccl (new commits)
        modified:   third_party/onnx (new commits)
        modified:   third_party/pybind11 (new commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        third_party/mimalloc/
`

I did not intentionally modify anything and git diff does not give me a clue. It does not look like an actual change.

(ldm) PS C:\repos\pytorch> git diff third_party/flatbuffers
diff --git a/third_party/flatbuffers b/third_party/flatbuffers
index d0cede9c90c..01834de25e4 160000
--- a/third_party/flatbuffers
+++ b/third_party/flatbuffers
@@ -1 +1 @@
-Subproject commit d0cede9c90c5257537c293517a21376408b549fa
+Subproject commit 01834de25e4bf3975a9a00e816292b1ad0fe184b
(ldm) PS C:\repos\pytorch>

I tried to revert the whole mess to main but could not get it without any "ghostly" modifications. Now I am sufficiently annoyed and will cleanly clone the whole repository and start over again. We'll see. I will report the results.

**Comment by bones0** [comment]
I see the develop-command is pulling third_party stuff so git pull probably did not update and checkout did likely not downgrade it. So starting from scratch is probably the way to go. I worked in the directory compiling the 2.1.0-version before so the third_party directories were probably messy.

**Comment by bones0** [comment]
That was it. Always start with a fresh and clean clone.

'>>> import torch
>>>
>>> print(torch.__version__)
2.0.0a0+gite9ebda2
>>>
>>> torch.cuda.is_available()
True
>>>
>>> torch.cuda.current_device()
0
>>>
>>> torch.cuda.device(0)
<torch.cuda.device object at 0x000001F75EC17C50>
>>>
>>> torch.cuda.device_count()
1
>>>
>>> torch.cuda.get_device_name(0)
'Tesla K40c'
>>>
>>> t1 = torch.tensor([1, 2, 3]).cuda()
>>> print(t1)
tensor([1, 2, 3], device='cuda:0')
>>>'

Slightly puzzled why checking out the tag v2.0.1 got me a version 2.0.0, though, but that's a story for another day. Let's see if torchvision 0.15.2 ist willing to work with me anyway.
