### ISSUE TITLE
Dynamo doesn't support itertools.accumulate

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#107682]
### 🐛 Describe the bug

```
[rank0]:[2023-08-21 14:24:19,987] [0/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG] Graph break: call_function accumulate in skip_files Builtin accumulate from user code at:                                                                                    
```

from torchrec TwSparseFeaturesDist

```
[rank0]:[2023-08-21 14:24:19,987] [0/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]     self._splits_cumsum: List[int] = [0] + list(itertools.accumulate(splits)) 
```

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

**Comment by anijain2305** [comment]
cc @nakulcr7

**Comment by andrzeng** [comment]
Hey, I'm interested in tackling this bug as my first PyTorch issue. Should I have to get into contact with you guys?

**Comment by ezyang** [comment]
fixed in https://github.com/pytorch/pytorch/pull/108018
