### ISSUE TITLE
`nn.functional.conv{1, 2, 3}d`: contradictions with the doc, plus potentially misleading checks+tests with specified `groups`.

### ISSUE THREAD

**Issue by nikitaved** [pytorch/pytorch#107692]
### 🐛 Describe the bug

Consider a 2d convolution described in https://pytorch.org/docs/main/generated/torch.nn.functional.conv2d.html#torch.nn.functional.conv2d.
From the doc it follows  if `input` is batched, then one would expect that for valid `input` and `weight`, `input.shape[1] == groups * weight.shape[1]` must be `True`. However:

```python
>>> import torch
>>> x = torch.rand(1, 4, 3, 3)
>>> w = torch.rand(5, 2, 3, 3)
>>> torch.nn.functional.conv2d(x, w, groups=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Given groups=2, expected weight to be divisible by 2 at dimension 0, but got weight of size [[5, 2, 3, 3]] instead
```

If we are to check the sample inputs that test `conv2d` (`groups != 1`),
https://github.com/pytorch/pytorch/blob/bcede143bd7e939f5af7a5888ded883bdb610baf/torch/testing/_internal/common_methods_invocations.py#L3849-L3856
we can see that `groups` divide both `weight.shape[0]` and `input.shape[1]`, so the issue is masked.

### Versions

Current master.

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by nikitaved** [comment]
Note that https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html#torch.nn.Conv2d is clear about this relationship. Hence it appears to be just a doc issue.

**Comment by mikaylagawarecki** [comment]
Actionable to fix the docs to be consistent with that of Conv2d
