### ISSUE TITLE
torch.cuda.set_per_process_memory_fraction() not working as intended.

### ISSUE THREAD

**Issue by chrizandr** [pytorch/pytorch#107667]
### 🐛 Describe the bug

Even when setting limits to the GPU memory using `torch.cuda.set_per_process_memory_fraction()` on the cuda device, I am able to allocate more memory than I limit. 

```python
import torch
from torchvision.models import resnet18

# Want to set a 100MB limit on GPU device 0
gpu_id = 0
value = 100

# Get total memory of the device
total_memory = torch.cuda.get_device_properties(gpu_id).total_memory

# Calculate the fraction of memory that is equal to value
memory_fraction = min(1, float(value * 1024 * 1024) / total_memory)

# Set memory limit
torch.cuda.set_per_process_memory_fraction(memory_fraction, gpu_id)

# Create a new model, this is created on CPU
resnet = resnet18(weights=None)
# Move model to GPU device 0
resnet.to(f"cuda:{gpu_id}")
```

After this I can see 430MB allocated to the process in nvidia-smi. Shouldn't this be limited to 100MB?
This snippet however gives an OOM Error, which is as intended. This behaviour only seems to be the case with torchvision models.

```python
import torch

# Want to set a 100MB limit on GPU device 0
gpu_id = 0
value = 100

# Get total memory of the device
total_memory = torch.cuda.get_device_properties(gpu_id).total_memory

# Calculate the fraction of memory that is equal to value
memory_fraction = min(1, float(value * 1024 * 1024) / total_memory)

# Set memory limit
torch.cuda.set_per_process_memory_fraction(memory_fraction, gpu_id)

# Create a tensor of size greater than the memory limit
torch.empty(int(total_memory * memory_fraction * 1.1), dtype=torch.int8, device=f'cuda:{gpu_id}')
```

This first lead me to assume that set_per_process_memory_fraction only imposes a limit on tensors created directly on GPU rather than those that are moved to GPU. However when I create the empty tensor above on CPU and try to move it to the GPU device I get an OOM Error.

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1039-aws-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 535.86.10
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:                        1
CPU MHz:                         3000.000
CPU max MHz:                     3000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4600.00
Hypervisor vendor:               Xen
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        45 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.0.1
[pip3] torch-model-archiver==0.8.1
[pip3] torchserve==0.8.1
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] Could not collect

cc @ptrblck

**Comment by ptrblck** [comment]
> After this I can see 430MB allocated to the process in nvidia-smi. Shouldn't this be limited to 100MB?

No, since the CUDA context etc. will also use memory.
Your model only uses ~45MB and fits into the allowed budged of 100MB.
```python
nb_params = torch.tensor([p.nelement() for p in resnet.parameters()]).sum()
nb_buffers = torch.tensor([p.nelement() for p in resnet.buffers()]).sum()

memory_used = (nb_params + nb_buffers) * next(resnet.parameters()).element_size() / 1024**2
print(memory_used)
# tensor(44.6286)

# Move model to GPU device 0
resnet.to(f"cuda:{gpu_id}")

print(torch.cuda.memory_allocated() / 1024**2)
# 44.6904296875
```
Swap it for `resnet101`, which uses ~170MB and it will properly fail.

**Comment by chrizandr** [comment]
@ptrblck I see. So the CUDA context etc. takes 300 something MB? That seems like a lot. I've never seen that much memory being taken something other than a model. 

Could you tell me what this context includes? Or is there some documentation for this? Thanks.

**Comment by ptrblck** [comment]
> So the CUDA context etc. takes 300 something MB? That seems like a lot. 

Yes, and the currently used ~300MB are small compared to previous releases. The CUDA context contains the driver, CUDA kernels etc. Before CUDA 11.7, *all* kernels were loaded into the context once the library was loaded, which took >1000MB. Starting with 11.7 CUDA implemented lazy kernel/module loading, which now loads CUDA kernels lazily into the context once they are needed. This adds a bit of overhead in the very first execution of each kernel, but saves a lot of memory. This feature was further improved in 11.8. 
In all PyTorch binaries shipping with CUDA 11.7+ we've enabled lazy kernel loading by default, which explains the small context now.

**Comment by chrizandr** [comment]
Alright thank you for the explanation. Closing this.
