### ISSUE TITLE
fullgraph=True doesn't actually raise error when you don't manage full graph inside DDP

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#107639]
### 🐛 Describe the bug

This is same repro as https://github.com/pytorch/pytorch/issues/107637

In the logs https://gist.github.com/ezyang/e4bf7345326092138969387ba364f3ea#file-dist-log-L752-L761 you can see that we don't raise an error when the first graph fails compiling, we just keep going.

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

**Comment by ezyang** [comment]
Maybe this is actually root cause to https://github.com/pytorch/pytorch/issues/107686

**Comment by anijain2305** [comment]
Closing because the parent issue is closed.
