### ISSUE TITLE
`torch._int_mm` may yield wrong results starting cuda 12.1 update 1

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#107671]
### 🐛 Describe the bug

`torch._int_mm` may yield wrong results starting cuda 12.1 update 1

The tests and functionality were re-enabled for versions other than cuda 11.7 in https://github.com/pytorch/pytorch/pull/106840, and failures were later discovered by our internal CI.

The issue has been reported to cublas team. Ref: /4252478

Tested on A100. Short reproduce:
```python
import torch

def genf_int_float(x, y, use_transpose):
    if use_transpose:
        x, y = y, x
    x_int8 = torch.randint(-10, 10, (x, y), dtype=torch.int8, device='cuda')
    x_float = x_int8.to(torch.float32)
    if use_transpose:
        return x_int8.t(), x_float.t()
    return x_int8, x_float

def _test(m, k, n, transpose_a, transpose_b):
    a_int8, a_float = genf_int_float(m, k, transpose_a)
    b_int8, b_float = genf_int_float(k, n, transpose_b)
    c_int32 = torch._int_mm(a_int8, b_int8)
    c_float32 = torch.mm(a_float, b_float)
    print(c_int32[0])
    print(c_float32[0])
    torch.testing.assert_close(c_int32.float(), c_float32)

_test(17, 16, 16, False, True)
```

### Versions

main

cuda 12.1 update 1

A100

cc @ezyang @gchanan @zou3519 @ptrblck @csarofeen @malfet @atalman @eqy @albanD

**Comment by albanD** [comment]
Should we update the code to fallback to another impl when detecting this specific cuda version?

**Comment by albanD** [comment]
Even though this is a private function, since 2.1 will ship with CUDA 12.1, we most likely want a mitigation before then.

**Comment by xwang233** [comment]
The results are correct for cuda 12.1, and started to become wrong in cuda 12.1 update 1. It depends on which cuda 12.1 minor version you will be using.

For the mitigation, we can change this cuda version guard at compile just like it was before
https://github.com/pytorch/pytorch/blob/b0e93e206c5e5ddaba3072032aa9e92cc542edab/aten/src/ATen/native/cuda/Blas.cpp#L682

**Comment by albanD** [comment]
We indeed migrated to 12.1.1 due to https://github.com/pytorch/pytorch/issues/94772

Updating that compile flag will make `_int_mm` raise error for all the release build is that correct?

**Comment by xwang233** [comment]
If you mean test failures, we can skip those tests based on cuda runtime versions.

For functionality concern, an error will unfortunately be raised, at least it's better than silent wrong output.

https://github.com/pytorch/pytorch/blob/b0e93e206c5e5ddaba3072032aa9e92cc542edab/aten/src/ATen/native/cuda/Blas.cpp#L701-L707

**Comment by xwang233** [comment]
I've discussed this with cublas team. There are something wrong with our implementation here,

https://github.com/pytorch/pytorch/blob/cd031f13ba16d68f999144a73c21908db8199934/aten/src/ATen/cuda/CUDABlas.cpp#L1025-L1026

The alpha and beta values here should be of `scaleType`, that is `int32_t` instead of `int8_t` or `float`. I've verified that after fixing this type, the numerical results are correct in the latest cuda 12.2
