### ISSUE TITLE
nvfuser does not respect CMAKE_INSTALL_PREFIX when build (cmake) libtorch

### ISSUE THREAD

**Issue by eval-dev** [pytorch/pytorch#107633]
### 🐛 Describe the bug

I followed the libtorch build instructions from https://github.com/pytorch/pytorch/blob/main/docs/libtorch.rst#building-libtorch-using-cmake:

```
git clone -b main --recurse-submodule https://github.com/pytorch/pytorch.git
mkdir pytorch-build
cd pytorch-build
cmake -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON_EXECUTABLE:PATH=`which python3` -DCMAKE_INSTALL_PREFIX:PATH=../pytorch-install ../pytorch
cmake --build . --target install
```

However, "libnvfuser_codegen.so" is missing from the installation dir "pytorch-install". Looks like it's bc nvfuser_codegen's install destination is hard-coded to <ProjectRoot>/torch/lib. In nvfuser/CMakeLists.txt:

```
set(TORCH_INSTALL_LIB_DIR ${TORCH_ROOT}/torch/lib)
...
install(TARGETS ${NVFUSER_CODEGEN} EXPORT NvfuserTargets DESTINATION "${TORCH_INSTALL_LIB_DIR}")
```

see https://github.com/pytorch/pytorch/blob/2b32a74ab084a9379c9e46a792c95348a6fc0971/third_party/nvfuser/CMakeLists.txt#L21

Please make nvfuser lib install destination settings consistent with other libs.

### Versions

since 2.0.0

cc @kevinstephano @jjsjann123

**Comment by eval-dev** [comment]
@jjsjann123 Can you help take a look?

**Comment by eval-dev** [comment]
2.1.0 has deprecated nvfuser. Closing this issue.

**Comment by jjsjann123** [comment]
Oops, sorry totally missed earlier ping.

Thanks for following up and closing this :bow:
