### ISSUE TITLE
Error in ONNX during Export GLU with Opset 18

### ISSUE THREAD

**Issue by WoodieDudy** [pytorch/pytorch#107685]
### 🐛 Describe the bug

When attempting to export a PyTorch model containing the `glu` function to ONNX format
using opset version 18, an error is encountered during the ONNX shape inference process.
The error message received is as follows:
```
/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py:1672: UserWarning: The exported ONNX model failed ONNX shape inference. The model will not be executable by the ONNX Runtime. If this is unintended and you believe there is a bug, please report an issue at https://github.com/pytorch/pytorch/issues. Error reported by strict ONNX shape inference: [ShapeInferenceError] Shape inference error(s): (op_type:Split, node name: /Split): [ShapeInferenceError] Neither 'split' input nor 'num_outputs' attribute has been given
(op_type:Sigmoid, node name: /Sigmoid): [TypeInferenceError] Input 0 expected to have type but instead is null
(op_type:Mul, node name: /Mul): [TypeInferenceError] Input 0 expected to have type but instead is null
 (Triggered internally at ../torch/csrc/jit/serialization/export.cpp:1403.)
  _C._check_onnx_proto(proto)
```

Code to reproduce
```python
import torch
from torch import nn


class Model(nn.Module):
    def forward(self, x):
        x = nn.functional.glu(x, dim=1)
        return x

model = Model()
model.eval()
x = torch.rand(1024, 512)

torch.onnx.export(
    model, (x,),
    "model.onnx",
    verbose=False,
    opset_version=18,
)
```

### Versions

PyTorch version: 2.1.0.dev20230812+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-152-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB
Nvidia driver version: 525.125.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          80
On-line CPU(s) list:             0-79
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 5320T CPU @ 2.30GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              20
Socket(s):                       2
Stepping:                        6
BogoMIPS:                        4600.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp_epp avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       1.9 MiB (40 instances)
L1i cache:                       1.3 MiB (40 instances)
L2 cache:                        50 MiB (40 instances)
L3 cache:                        60 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-19,40-59
NUMA node1 CPU(s):               20-39,60-79
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] pytorch-lightning==1.9.4
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230812+cu121
[pip3] torch-tensorrt==1.5.0.dev0
[pip3] torchaudio==2.1.0.dev20230813+cu121
[pip3] torchdata==0.7.0a0
[pip3] torchmetrics==1.0.3
[pip3] torchtext==0.16.0a0
[pip3] torchvision==0.16.0.dev20230813+cu121
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by justinchuby** [comment]
Opset 18 support is experimental and it is not supported by torch.onnx.export. Please consider using torch.onnx.dynamo_export with the latest nightly build instead

**Comment by vadimkantorov** [comment]
> Opset 18 support is experimental and it is not supported by torch.onnx.export.

Interestingly, this export succeeds with opset=17

**Comment by justinchuby** [comment]
Yes. Opset 17 is supported

**Comment by justinchuby** [comment]
Yeah. I agree that can be confusing. Opset 18 introduced changes to Reduce* ops that would require a lot of work adapting existing ONNX decompositions to support it. Instead our focus is the new `dynamo_export` exporter. `dynamo_export` is the future of ONNX support in PyTorch.

**Comment by vadimkantorov** [comment]
Or at least fail with a more understandable error :)

**Comment by vadimkantorov** [comment]
@justinchuby There is also https://github.com/pytorch/pytorch/issues/107446, I propose that in new PyTorch version, default `opset_version=17` and that `opset_version>17` errors out for the legacy torch.onnx.export (if it's not replaced by the more mighty torch.onnx.dynamo_export by default)

**Comment by MaanavD** [comment]
Thanks for your suggestions & contributions. Closing the issue now as dynamo export should fix. 

@vadimkantorov :)
