### ISSUE TITLE
Email Subscription 

### ISSUE THREAD

**Issue by samsonmobisa** [pytorch/pytorch#107650]
### 📚 The doc issue

The team should consider of adding an email Subscription option to members looking forward to learn spesific topics.

There is no link referring to github repository to explain more about the described project. 

### Suggest a potential alternative/fix

There is no option where one can subscribe to weekily or monthly news letter from the platform related on specific topics.

Also the team can consider having something like a boot camp forcased on this topics. 

Adding of a link to github repositories projects whenever need
 

![Screenshot_20230822-032745](https://github.com/pytorch/pytorch/assets/92422271/6feb6e78-836b-4b04-8ded-700145078a48)
![Screenshot_20230822-032738](https://github.com/pytorch/pytorch/assets/92422271/aed8ddeb-84a2-4918-ae3b-4dcf1ff7d130)

**Comment by msaroufim** [comment]
A lot of the dev updates will show up on https://dev-discuss.pytorch.org/ - maintaining a mailist is hard work so someone really needs to volunteer to do this

**Comment by samsonmobisa** [comment]
Can volunteer to do that, I think keeping many young people updated with what's going on will add value to them. The next generation of devs need to learn more so as to have better technology of tomorrow. Even tough this tough having faced challenges and struggling as a student and self taught dev. Am sure this will add more value to the community at large

**Comment by msaroufim** [comment]
My suggestion would be to start an unofficial mailing list and see how it goes. Once it's clear that you're committed to it longer term feel free to work with @subramen to make it official

**Comment by samsonmobisa** [comment]
ok

**Comment by samsonmobisa** [comment]
Am looking forward to raise some cash to invest on my internet and upgrading my machine from 4GB ram to a 8 Gb ram. Any support I will greatly appreciate. 
Patreon
https://www.patreon.com/Mobisa

Github sponsors 
https://github.com/sponsors/samsonmobisa?o=sd&sc=t

**Comment by samsonmobisa** [comment]
Am unable to reach out @subramen any contacts

**Comment by msaroufim** [comment]
Yeah I'm sorry i don't feel it's appropriate to be soliciting donations on github issues

**Comment by samsonmobisa** [comment]
My apology I didn't know it's against the violation. Am now aware
