### ISSUE TITLE
DISABLED test_multilayer_var_dynamic_shapes_cpu (__main__.DynamicShapesCpuTests)

### ISSUE THREAD

**Issue by cyyever** [pytorch/pytorch#107705]
Platforms: macos

This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/inductor%2Ftest_torchinductor_dynamic_shapes.py%3A%3ADynamicShapesCpuTests%3A%3Atest_multilayer_var_dynamic_shapes_cpu)).

cc @ezyang

**Comment by huydhn** [comment]
This is failing on MacOS x86 https://hud.pytorch.org/pytorch/pytorch/commit/60bb02a907aa1f5e6f2150d50ea28a48afaa8e95

**Comment by huydhn** [comment]
Still failing on MacOS x86

**Comment by cyyever** [comment]
@huydhn Can we find out the root cause?
