### ISSUE TITLE
Missing description of SGD in list of `torch.optim` algorithms

### ISSUE THREAD

**Issue by gregsadetsky** [pytorch/pytorch#107737]
### 📚 The doc issue

In the `torch.optim` docs, under [Algorithms](https://pytorch.org/docs/stable/optim.html#algorithms), the one-line description of [SGD](https://pytorch.org/docs/stable/generated/torch.optim.SGD.html) does not appear in the table:

![image](https://github.com/pytorch/pytorch/assets/1017304/7e2439dc-eab5-43ca-964e-5934de34efe4)

I believe this is happening because the [first line](https://github.com/pytorch/pytorch/blob/main/torch/optim/sgd.py#L95) of `SGD.__doc__` is `r"""\` i.e. a new line. Compare with `RAdam`'s `__doc__` [here](https://github.com/pytorch/pytorch/blob/bcee3d6fa4164bfc3b4b0c2fcdfec80fbd90b00e/torch/optim/radam.py#L123) which starts immediately with the documentation (and does appear correctly in the Algorithms table mentioned above)

### Suggest a potential alternative/fix

- Check when newline at the beginning of SGD's `__doc__` ([here](https://github.com/pytorch/pytorch/blob/main/torch/optim/sgd.py#L95)) was introduced - was there a reason for it?
- If no clear reason behind it, remove the newline
- Compile the docs, make sure they work & that the SGD one-line-doc appears in the Algorithms table

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by janeyx99** [comment]
This was my bad lol https://github.com/pytorch/pytorch/pull/92336

here's the fix https://github.com/pytorch/pytorch/pull/107738
