### ISSUE TITLE
[jit][script] indexing master task

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#10774]
In order of priority:
- [x] Support multidimensional int indexing `tensor[0, 1]`
- [x] Support ast.ExtSlice in frontend
- [x] Support multidimensional slice/num indexing `tensor[0, 1:2]`
- [x] Support indexing on LHS `tensor[0] = 1`. This is hard because it is mutable and we don't support mutable ops yet.
- [x] Support advanced indexing `tensor[index, 0]` @zou3519
- [x] Support indexing with sequences `tensor[[0, 1], 1]` @zou3519
- [x] Support slices with ranges `tensor[0:4:2]`
- [x] Support ellipses `tensor[..., 1]`. There is a comment in the code that says this is py2 only but I think that comment is misplaced.
- [x] Support None indexing #12810

**Comment by wanchaol** [comment]
Shall we also add indexing var as a lhs? there will be some cases that we want to use it.

**Comment by zou3519** [comment]
@wanchaol sure

**Comment by suo** [comment]
LHS indexing PR: https://github.com/pytorch/pytorch/pull/13486
