### ISSUE TITLE
I want to know how to find the functions implementated in torch. _C.

### ISSUE THREAD

**Issue by EricKani** [pytorch/pytorch#10778]
Hi,

I am very sorry for bothering you for this problem. I often find torch._C in python source code. But I can't find it in this repository. Like torch._C._nn.nll_loss(). Could you please tell me how to find it? What is the rule finding the corresponding c source code?

Thank you very much!

Liu

**Comment by cdluminate** [comment]
try to use any code searching tool, such as ripgrep, from the root of source tree.

**Comment by apaszke** [comment]
Yep, it'd recommend using `grep`. Apart from that there's also #10735 that would make it easier to jump into C++.
