### ISSUE TITLE
Irrecoverable graph break in optimizer init due to not handling RemovableHook

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#107789]
## Context
I recently made a change that would move some load_state_dict casting knowledge into a pre-hook to enable maximum flexibility for users when registering hooks. Therefore, I had added a hook registration to the constructor of the optimizers. This addition seems to cause an irrecoverable graph break when tracing through optimizer __init__ that is appeased if we manually disable, but it feels like dynamo should be able to handle the graph break smoothly without the manual disable.

## Repro
Step 1: comment out the following lines in `torch/_dynamo/eval_frame.py` in https://github.com/pytorch/pytorch/pull/106725. [this is the manual graph break]
```
opt.register_load_state_dict_pre_hook = disable(
                opt.register_load_state_dict_pre_hook
            )
```

Step 2: run this chunk of code
```
import torch

@torch.compile(backend="eager")
def compiled_optim_init(params):
    optimizer = torch.optim.Adagrad(params)
    return optimizer

optimizer = compiled_optim_init([torch.nn.Parameter(torch.randn(2,3))])
```

### Versions

trunk

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

**Comment by janeyx99** [comment]
Also cc @mlazos who had looked into this a bit already

**Comment by mlazos** [comment]
For whoever may look at this, we need weakref support in dynamo

**Comment by anijain2305** [comment]
Can you also paste the graph break log for completeness when you get a chance?

**Comment by janeyx99** [comment]
The PR got reverted and my proposed fix will avoid adding the code to the __init__ so we should be okay now. Closing and will reopen if we run into something similar later.
