### ISSUE TITLE
[FakeTensor] fake tensor mode not working with inference mode on Tensor.item()

### ISSUE THREAD

**Issue by shingjan** [pytorch/pytorch#107898]
### 🐛 Describe the bug

As titled. My repro:

```python
import torch
from torch._subclasses.fake_tensor import FakeTensorMode
with FakeTensorMode():
    with torch.inference_mode():
        torch.tensor(32.).item()
```

stacktrace:
```
Traceback (most recent call last):
  File "repro.py", line 21, in <module>
    torch.tensor(32.).item()
  File "site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "site-packages/torch/_subclasses/fake_tensor.py", line 1233, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "site-packages/torch/_subclasses/fake_tensor.py", line 1437, in dispatch
    r = func.decompose(*args, **kwargs)
  File "site-packages/torch/_ops.py", line 467, in decompose
    return self._op_dk(dk, *args, **kwargs)
  File "site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "site-packages/torch/_subclasses/fake_tensor.py", line 1233, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "site-packages/torch/_subclasses/fake_tensor.py", line 1470, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "site-packages/torch/_subclasses/fake_tensor.py", line 501, in local_scalar_dense
    raise DataDependentOutputException(func)
torch._subclasses.fake_tensor.DataDependentOutputException: aten._local_scalar_dense.default
```

### Versions

PyTorch version: 2.1.0.dev20230817+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 10.5.0-1ubuntu1~22.04) 10.5.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.8.16 (default, Jun 12 2023, 18:09:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-50-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070
Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 9 5900X 12-Core Processor
CPU family:                      25
Model:                           33
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     4950.1948
CPU min MHz:                     2200.0000
BogoMIPS:                        7399.84
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       384 KiB (12 instances)
L1i cache:                       384 KiB (12 instances)
L2 cache:                        6 MiB (12 instances)
L3 cache:                        64 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.7
[pip3] dalle2-pytorch==1.14.2
[pip3] ema-pytorch==0.2.3
[pip3] flake8==6.0.0
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.21.2
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-transformers==1.2.0
[pip3] pytorch-triton==2.1.0+9e3e10c5ed
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.2.5
[pip3] torch==2.1.0.dev20230817+cpu
[pip3] torch-fidelity==0.3.0
[pip3] torch_geometric==2.4.0
[pip3] torch-struct==0.5
[pip3] torchaudio==2.1.0.dev20230817+cpu
[pip3] torchmetrics==1.0.1
[pip3] torchrec-nightly==2023.7.17
[pip3] torchvision==0.16.0.dev20230817+cpu
[pip3] vector-quantize-pytorch==1.6.30
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] clip-anytorch             2.5.2                    pypi_0    pypi
[conda] coca-pytorch              0.0.7                    pypi_0    pypi
[conda] dalle2-pytorch            1.14.2                   pypi_0    pypi
[conda] ema-pytorch               0.2.3                    pypi_0    pypi
[conda] functorch                 1.14.0a0+b71aa0b          pypi_0    pypi
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] open-clip-torch           2.20.0                   pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] pytorch-triton            2.1.0+9e3e10c5ed          pypi_0    pypi
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.2.5                    pypi_0    pypi
[conda] torch                     2.1.0.dev20230817+cpu          pypi_0    pypi
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230817+cpu          pypi_0    pypi
[conda] torchmetrics              1.0.1                    pypi_0    pypi
[conda] torchrec-nightly          2023.7.17                pypi_0    pypi
[conda] torchvision               0.16.0.dev20230817+cpu          pypi_0    pypi
[conda] vector-quantize-pytorch   1.6.30                   pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @eellison

**Comment by shingjan** [comment]
@anijain2305 Thanks for the triage. With `FakeTensorMode(shape_env=ShapeEnv())` instead of `FakeTensorMode()` the above repro works and outputs a `SymFloat`. But there is a `DataDependentOutputException` in the stacktrace. Is data dependent output kinda interchangeable with `DynamicOutputShape`?

**Comment by ezyang** [comment]
Oh, cc @eellison 

What's going on here is that `torch.tensor(32.).item()` is special: when we do a torch.tensor call in fake tensor, we will actually choose to constant propagate 32 if the tensor is small (in this case, it's one elem, so it's small.) For some reason, `inference_mode` impedes this constant propagation process. It probably shouldn't, and I'm guessing it may not be too hard to fix.

**Comment by ezyang** [comment]
So concretely, the reason we lose constant-ness is because under inference_mode, there's an extra `detach_()` call that doesn't const prop. @eellison we should be able to preserve const-ness for this right? Since it's not a real mutating operator.

**Comment by ezyang** [comment]
The detach_ call happens here:

```
Tensor tensor_ctor(
    c10::DispatchKey dispatch_key,
    at::ScalarType scalar_type,
    PythonArgs& r) {
  if (r.idx == 0) {
    PyObject* data = r.pyobject(0);
    if (THPVariable_Check(data)) {
      auto ret = PyErr_WarnEx(
          PyExc_UserWarning,
          "To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() "
          "or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).",
          1);
      if (ret != 0)
        throw python_error();
    }
    
    bool type_inference = r.isNone(1);
    bool pin_memory = r.toBool(3);
    bool args_requires_grad = r.toBool(4);
    auto new_tensor = internal_new_from_data(
        typeIdWithDefault(r, 2, dispatch_key),
        r.scalartypeWithDefault(1, scalar_type),
        r.deviceOptional(2),
        data,
        /*copy_variables=*/true,
        /*copy_numpy=*/true,
        /*type_inference=*/type_inference,
        pin_memory);
    auto names = r.toDimnameListOptional(5);
    if (names) {
      at::namedinference::propagate_names(
          new_tensor, *names, /*validate_names=*/true);
    }
    new_tensor.detach_(); // ensure new_tensor a leaf node
    new_tensor.set_requires_grad(args_requires_grad);
    return new_tensor;
  }
  throw std::runtime_error("tensor(): invalid arguments");
}
```

I guess because inference mode is on we don't desugar it away before it gets to the dispatcher.

**Comment by ezyang** [comment]
also cc @bdhirsh, this is a kind of interesting one for pre-dispatch

**Comment by eellison** [comment]
@ezyang I can look into fixing constant problem with inference_mode... having said that, there are a number of problems inference mode introduces. It generally doesn't compose very well with the rest of the stack. how committed are we to making it work ?

**Comment by shingjan** [comment]
Thanks @ezyang and @eellison for the replies! `inference_mode` is a stable api so I wonder if it makes sense to have an api to disable inference mode during dispatch/torch.compile so that it will make user calling `with torch.inference_mode()` a no-op somehow? I also noticed that `inference_mode` could change the dispatch key (not confirmed yet), which may not work well with `TorchDispatchMode(_dispatch_key=DispatchKey.SomeKey)` in my experience.

**Comment by ezyang** [comment]
@eellison We should make it work, IMO. In this particular case, I don't really think it's inference mode's fault, we just need detach_() to work correctly with const prop

**Comment by bdhirsh** [comment]
Looks like this inference_mode interaction has been fixed. The repro works for me, so I'll close the issue.

FWIW, .item() is a data-dependent call. So if you want to use FakeTensorMode directly like in the above repro, you need to pass in a ShapeEnv (so we know to use dynamic shapes with our fake mode):
```
import torch
from torch._subclasses.fake_tensor import FakeTensorMode
from torch.fx.experimental.symbolic_shapes import ShapeEnv
with FakeTensorMode(shape_env=ShapeEnv()):
    with torch.inference_mode():
        torch.tensor(32.).item()
```

**Comment by shingjan** [comment]
@bdhirsh Thanks for the reply! But I don't think my repro works differently than when it was reported. With this [git 7553c4](7553c495147f3e21a1e27d392d277906a47768e7), the repro gave the same result as [here](https://github.com/pytorch/pytorch/issues/107898#issuecomment-1698265286), in which a DataDependentOutputException is raised when no shape env is passed and a symint is returned with default shape env. I guess the following example makes better sense:
```
import torch
from torch._subclasses.fake_tensor import FakeTensorMode
from torch.fx.experimental.symbolic_shapes import ShapeEnv
# with inference mode
with FakeTensorMode(shape_env=ShapeEnv()):
    with torch.inference_mode():
        print(torch.tensor(32.).item())

# without inference mode
with FakeTensorMode(shape_env=ShapeEnv()):
    print(torch.tensor(32.).item())
```

It looks like inference_mode will make the output of the item from an actual number, e.g. 32 in this case, into a symbolic int oddly. In my case I need to explicitly disable inference_mode as it will bypass any dispatcher above autograd and run directly into cpp.
