### ISSUE TITLE
[Dynamo] Avoid id test on closures

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#107866]
### 🐛 Describe the bug

Suppose you have:

```
def f(x):
  def g(y):
    ...
  graph_break()
  ... some stuff including g ...
```

The continuation frame after the graph break will always recompile, because g is a closure and reallocated every call to f, but we will typically install an ID_MATCH on it.

It would be better if we could introspect into closures and explicitly guard on the freevars bound on it, which may turn out to be constant from run to run.

This showed up in a Meta internal model. An alternative fix is to diagnose why the graph break was happening and fix that instead.

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

**Comment by Fidget-Spinner** [comment]
Alternatively, we could id check on the code object instead. That remains constant throughout. Only the function object wrapping it is allocated newly each time. I'll work on this.
