### ISSUE TITLE
autograd's elu_backward usage seems not correct

### ISSUE THREAD

**Issue by sinkingsugar** [pytorch/pytorch#10784]
currently is:
`elu_backward(grad, alpha, scale, input_scale, output)`

should be:
`elu_backward(grad, alpha, scale, output)`

Reason:
ATen's side I don't see any input_scale parameter

https://github.com/pytorch/pytorch/blob/5fb9b31ed58c6552343df3bc97d6d822f892878d/tools/autograd/derivatives.yaml#L818

**Comment by sinkingsugar** [comment]
Error was on my auto generator side, Type vs Tensor class, my bad :)

**Comment by sinkingsugar** [comment]
Closed it thinking I made a mistake but actually indeed seems wrong.

**Comment by sinkingsugar** [comment]
derivatives.yaml states:
> - Any of the input arguments, tensor or non-tensor, including argument names that only appear in Declarations.cwrap, e.g. 'output'.

So I find it an issue indeed, I am auto generating a *nim* version of torch ( releasing this week hopefully ) and having consistent data is a must.

https://github.com/pytorch/pytorch/search?q=elu_forward&unscoped_q=elu_forward 
returns nothing with input_scale.

Thanks for pointing me out to nn.yaml tho, which I'll go find now.

**Comment by SsnL** [comment]
Well, functions in nn.yaml are not defined by native_functions.yaml nor Declarations.cwrap. So the line you quoted doesn't apply.

**Comment by sinkingsugar** [comment]
I see now!

found it in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/nn.yaml
but it is `elu` just hmm, I wonder how `elu` and `elu_forward` from derivatives.yaml are bound together now?

**Comment by SsnL** [comment]
They are parsed by the codegen script https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/nn_parse.py , and goes a bunch of process functions, one of which generates the _forward and _backward of the nn functions.

**Comment by sinkingsugar** [comment]
Right! so this should in the end generate correctly `elu` and `elu_forward` in Type.h?
If so I must just have a old revision of the build locally

**Comment by sinkingsugar** [comment]
Indeed the issue was on my side.
I need to figure a way to make sure I'm generating correct data, probably sticking to release tags is the best for releases.

Thank you so much @SsnL for your support.

**Comment by SsnL** [comment]
No worries. Glad to help.
