### ISSUE TITLE
FSDP custom args per module

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#107830]
### 🚀 The feature, motivation and pitch

FSDP gives a set of arguments which are global across all wrapped modules. Instead, I would like to wrap some modules with custom args. For example, I have a module that I want to sync only across some GPUs, so I would like to specify custom process_groups which only hit a subset of ranks. 

Currently, PyTorch FSDP works with this but does not support an API to expose it. For example, in this [PR](https://github.com/mosaicml/composer/pull/2460), I monkeypatch `auto_wrap` to allow returning kwargs instead of just a bool which are then used to override the FSDP args for that wrap. This lets me change the process group for specific modules. So far, we remonkeypatch PyTorch every single release since 1.13 since this is critical for us but not supported. It would be amazing if this was supported. 

Our implementation extends auto_wrap to return either a bool or a set of override kwargs. I am happy to upstream this if it is acceptable. 

I imagine this would be useful to squeeze out more performance in general, e.g. some things I might wrap in FULL_SHARD and some in SHARD_GRAD_OP.

### Alternatives

Monkeypatching pytorch https://github.com/mosaicml/composer/pull/2460

cc @zhaojuanmao @mrshenli @rohan-varma @awgu @fegin @penguinwu

**Comment by awgu** [comment]
Sorry that I have not had the chance to look into this yet. I wonder if you could quickly check out `CustomPolicy` here:
https://github.com/pytorch/pytorch/blob/256fed02e930210dbcd7e5e23fcf142362098c2a/torch/distributed/fsdp/wrap.py#L216-L239
Does this work for you guys?

**Comment by mvpatel2000** [comment]
Let me try it out!

**Comment by mvpatel2000** [comment]
CustomPolicy works, forgot to close
