### ISSUE TITLE
[JIT] Allow Tuples/Lists to be passed and returned from python

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#10794]
Right now attempting to return a tuple results in:

```
The only supported return types are tensors, ints and floats
```

Code:
```
import torch

@torch.jit.script
def hi(x):
    return 3, (4, 5)

print(hi)
print(hi(torch.FloatTensor(3)))
```

Tuples and lists should also be tested as arguments to python functions.

Python functions called from script should also be tested for their ability to take/return tuples and lists.

Note: functionality for taking/returning lists is present, but needs to be implemented.

**Comment by apaszke** [comment]
This might have been accidentally fixed in #10637
