### ISSUE TITLE
[JIT] Fixing split/chunk and other operators that return lists

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#10793]
Fixing split/chunk and other operators that return lists:

Operators that return tensor list (e.g. chunk, split) currently flatten the list into outputs.
The tracer explicitly calls flatten_tensor_args to do this. And the `pack` function also flatten these args. This makes these functions unusable from script (and often there are problems with tracing as well, e.g. split does  not trace correctly according to TestJitGenerated.test_split_dim). 
They are unusable in script because script excepts there to be a single list returned from the op, and has no way to know how many elements would be created in the list. Chunk works because of a special case in the compiler that teaches it how to know if there is a constant number of outputs.

To fix this behavior, we need to change the behavior in operators to actually return a single list object. For operators, this means changing `pack(std::vector<Tensor>)` to push a single TensorList rather than individual tensors as outputs.

This will then break fusion/differentiation of chunk nodes which is important for lstms. To fix chunk node differentiation/fusion, we need to replace `aten::chunk` with a different op (lets call it `prim::ConstantChunk`) when the number of chunks is known in the compiler. The differentiator and fuser should then be switched to work with `prim::ConstantChunk`.

This will also break tracing, which calls `flatten_tensor_args` on lists. We need to change this so that when the tracer runs, it 
records a list as:

before:

```
output_0, output_1, output_2 = aten::split(x)
```

after:

```
output_list = aten::split(x)
output_0, output_1, output_2 = prim::UnpackList(output_list)
```

`prim::UnpackList` is like `UnpackTuple` but is required to check that the list has an expected number of elements that 
matches the number of outputs in the op.

At the end we will have:
* ability to call split, chunk, and any other operator from script
* continued ability to call chunk from tracing, and fixing the bugs with split in tracing
* continued ability for lstm code which includes chunk calls to be differentiated and fused because of introducing prim::ConstantChunk in place of chunk in the cases where
  we know it is constant.

**Comment by apaszke** [comment]
Fixed in #10949
