### ISSUE TITLE
add torch.float16 support for xla amp

### ISSUE THREAD

**Issue by kevint324** [pytorch/pytorch#107953]
### 🚀 The feature, motivation and pitch

https://github.com/pytorch/pytorch/blob/main/torch/amp/autocast_mode.py#L308

The "bfloat16 only" limitation is only applied to google TPU but not other backends like GPU and other accelerators.

And XLA itself is kind of a device abstraction, so for the long run, maybe these checks should be moved to lower level.

cc @bdhirsh @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by janeyx99** [comment]
cc @JackCaoG regarding the XLA side too
