### ISSUE TITLE
[Inductor FX graph] Register out-of-tree backend specific patterns in Inductor FX graph post_grad_passes.

### ISSUE THREAD

**Issue by arthuryuan1987** [pytorch/pytorch#107921]
### 🚀 The feature, motivation and pitch

We are moving onto new PyTorch recommended graph solution for Intel extension for PyTorch XPU backend. Before we enabled fusion patterns on Torch ScriptGraph for our out-of-tree backend.
```
static RegisterPreFusionPass custom_pass([](std::shared_ptr<Graph>& g) {
  RemoveProfileNodesAndSpecializeTypes(g);
  xpu_namespace::FusionPass(g);
  // RemoveTensorTypeSpecializations(g);
});
```

We are planning to enable some fusion patterns in Inductor FX graph post_grad_passes. So far, we are following an approach like this, which is an Inductor lowering pattern. 
```
144 @register_lowering_pattern(
145     CallFunction(
146         aten.add,
147         CallFunction(aten.mm, Arg(), Arg()),
148         CallFunction(aten.mm, Arg(), Arg()),
149     )
150 )
```
However, there are two potential issues to us during enabling,
1. Priority compatibility issue. Priority compatibility between in-tree pattern and out-of-tree pattern (register when import intel_extension_for_pytorch). Or maybe, there is no issue for now, will there be priority compatibility issue, if PyTorch adds a new in-tree pattern? We have no detailed priority definition, but coarse distinguish like.
```
 40 # First pass_patterns[0] are applied, then [1], then [2]
 41 pass_patterns = [
 42     PatternMatcherPass(),
 43     PatternMatcherPass(),
 44     PatternMatcherPass(),
 45 ]
```
Here, what's the priority inner of [0] or [1] or [2]?
2. Can Inductor provide a unified device guard for backend specific pattern? Like if example tensor is XPU tensor, then go through XPU registered pattern passes.

### Alternatives

Regarding these two issues, we have a proposal for your review,
1. New a passes set for backend specific passes for registration both for in-tree and out-of-tree usage,
```
# Backend specific passes
backend_specific_passes = {} # Key: backend type, Value: backend specific passes.

# First pass_patterns[0] are applied, then [1], then [2]
pass_patterns = [
    PatternMatcherPass(),
    PatternMatcherPass(),
    PatternMatcherPass(),
]

# patterns applied only in inference
inference_patterns = PatternMatcherPass()
```
2. We can ignore priority inner of backend specific passes, since they are exclusive to each other. Each runtime gets example tensor with certain backend.
3. Give priority to `backend_specific_passes`, `pass_patterns` and `inference_patterns` explicitly and guard by example tensor.
![image](https://github.com/pytorch/pytorch/assets/28250760/8d0199e8-c68a-4385-bdd5-476e3f19d493)
So there are two issues to discuss,
    a. What's your philosophy of priority?
    b. `post_grad_passes` seems backend irrelevant? I cannot find example tensor in it's API.

cc @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by arthuryuan1987** [comment]
@gujinghui @jgong5 @EikanWang

**Comment by jgong5** [comment]
For the custom registered passes, maybe we can add a `pre_custom` and a `post_custom` pass invoked before and after all the vanilla passes, similar to those registered in the TorchScript.

```diff
diff --git a/torch/_inductor/fx_passes/post_grad.py b/torch/_inductor/fx_passes/post_grad.py
index c889ef9a2df..88e6ffc4e23 100644
--- a/torch/_inductor/fx_passes/post_grad.py
+++ b/torch/_inductor/fx_passes/post_grad.py
@@ -67,10 +67,14 @@ def post_grad_passes(gm: torch.fx.GraphModule, is_inference: bool):
         group_batch_fusion_post_grad_passes(gm.graph)
         remove_extra_clones(gm.graph)
 
+        pre_custom_patterns.apply(gm.graph)
         for patterns in pass_patterns:
             patterns.apply(gm.graph)
+        post_custom_patterns.apply(gm.graph)
         if is_inference:
+            pre_custom_inference_patterns.apply(gm.graph)
             inference_patterns.apply(gm.graph)
+            post_custom_inference_patterns.apply(gm.graph)
 
     stable_topological_sort(gm.graph)
     gm.recompile()
```

For device checks, I think it is already supported via the pass validity checker (the `extra_check` argument) on the device tag which is available on the FX node meta.

**Comment by arthuryuan1987** [comment]
Hi, @jansel, any idea of it? Thanks.

**Comment by arthuryuan1987** [comment]
> 

Thanks for your comments. I will file a PR.

**Comment by EikanWang** [comment]
@arthuryuan1987 , please draft a PR, and let's have a quick review.
