### ISSUE TITLE
PyTorch profile issues summary

### ISSUE THREAD

**Issue by npuichigo** [pytorch/pytorch#107955]
### 🐛 Describe the bug

Recenly, I planed to profile the whole training process of my recipe. After reading several [official docs](https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html?highlight=profile), I'm confident it should be easy.

However, a plenty of issues and some [unsatisfactory answer](https://github.com/pytorch/kineto/issues/782#issuecomment-1640960718) make me wonder what the hell is the solution.

1. Distributed view cannot work with PyTorch 2.0 (works in PyTorch 1.11)

Like this [issue](https://github.com/pytorch/kineto/issues/782), when DDP is enabled, it doesn't show in Tensorboard as the doc says. But kernels like `ncclKernel_AllReduce_RING_*` actually exist. Switching to use PyTorch <= 1.11 works. 

2. Dataloader timing doesn't work in PyTorch 2.0 (works in PyTorch)

When using PyTorch 2.0, I cannot get the profile info about data loading, which is a feature regression.
![image](https://github.com/pytorch/pytorch/assets/11533479/c046f1ce-3664-4849-851b-f8703a73a361)

In PyTorch 1.11, it works like below
![image](https://github.com/pytorch/pytorch/assets/11533479/91c91b46-610e-4cd3-9e65-e391ec76eb2d)

3. Hang with PyTorch 1.1 if not profile with schedule(repeat=0) without early break

Let's change the example code in doc to
```
import torch
import torch.nn
import torch.optim
import torch.profiler
import torch.utils.data
import torchvision.datasets
import torchvision.models
import torchvision.transforms as T

transform = T.Compose(
    [T.Resize(224),
     T.ToTensor(),
     T.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
train_set = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
train_loader = torch.utils.data.DataLoader(train_set, batch_size=32, shuffle=True)

device = torch.device("cuda")
model = torchvision.models.resnet18().cuda(device)
criterion = torch.nn.CrossEntropyLoss().cuda(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
model.train()

def train(data):
    inputs, labels = data[0].to(device=device), data[1].to(device=device)
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

with torch.profiler.profile(
        schedule=torch.profiler.schedule(wait=100, warmup=100, active=300, repeat=0),  <- change for long running
        on_trace_ready=torch.profiler.tensorboard_trace_handler('./log/resnet18'),
        record_shapes=True,
        profile_memory=True,
        with_stack=True
) as prof:
    for step, batch_data in enumerate(train_loader):
#        if step >= (1 + 1 + 3) * 2:   <- remove early break
#           break
        train(batch_data)
        prof.step()
```
It hangs after `wait + warmup + active` steps and has 100% CPU usage and memory infinite increasing (memory leak)
![微信截图_20230825183430](https://github.com/pytorch/pytorch/assets/11533479/605e78b6-abe7-4c9c-8229-4e8788c0ab64)
![image](https://github.com/pytorch/pytorch/assets/11533479/c4f1c24d-35d9-4f48-9c96-9996ff7355cd)

4. [profiler.export_stacks doesn't return stack trace unless experimental_config is provided](https://github.com/pytorch/pytorch/issues/100253#top)

5. Warning and occasional crash with PyTorch 1.11

```
[W CPUAllocator.cpp:219] Memory block of unknown size was allocated before the profiling started, profiler results will not include the deallocation event
Segmentation fault (core dumped)
```

6. Hang if CUPTI cannot be find with PyTorch 1.11. Warning in 2.0 of missing CUPTI is not very eye-catching.

Welcome everyone to collect more issues. Currenly, profile is completely unusable. Hope PyTorch team could pay more effort to avoid feature regression and make profiling more stable to use.

7. Verbose warning: https://github.com/pytorch/pytorch/pull/107216

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)                                                                    Python platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090
GPU 2: NVIDIA GeForce RTX 4090
GPU 3: NVIDIA GeForce RTX 4090

Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:                                                                                                                                                   Architecture:                    x86_64                                                                                                                CPU op-mode(s):                  32-bit, 64-bit                                                                                                        Address sizes:                   46 bits physical, 57 bits virtual                                                                                     Byte Order:                      Little Endian                                                                                                         CPU(s):                          128                                                                                                                   On-line CPU(s) list:             0-127
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz                                                                         CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
Stepping:                        6
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       3 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        80 MiB (64 instances)
L3 cache:                        108 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected                                                                                                          Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable                                                                         Vulnerability Retbleed:          Not affected                                                                                                          Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl                                                               Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization                                                  Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence                                     Vulnerability Srbds:             Not affected                                                                                                          Vulnerability Tsx async abort:   Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.0.1+cu118
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==2.0.2+cu118
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+e6216047b8          pypi_0    pypi
[conda] torch                     2.0.1+cu118              pypi_0    pypi
[conda] torch-tb-profiler         0.4.1                    pypi_0    pypi
[conda] torchaudio                2.0.2+cu118              pypi_0    pypi
[conda] torchtts                  0.1                       dev_0    <develop>
[conda] torchvision               0.15.2+cu118             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by npuichigo** [comment]
@ezyang

**Comment by npuichigo** [comment]
Hi @janeyx99, anyone would work on this?

**Comment by aaronenyeshi** [comment]
Hi @npuichigo, the TB plugin has some support form MSFT for fixing issues. I've shared the list of issues related to TB plugin on Kineto: https://github.com/pytorch/kineto/issues?q=is%3Aopen+is%3Aissue+label%3Aplugin. This should include issues 1, 2, and 3 on your list.For issues related to

**Comment by aaronenyeshi** [comment]
Sorry, it seems Microsoft is no longer supporting the TB Plugin for PyTorch Profiler. Please use Google Chrome Tracing for your trace visualization. tb_plugin has been deprecated, please feel free to open new issue in Kineto if you want the OSS community to contribute a fix: https://github.com/pytorch/kineto?tab=readme-ov-file#pytorch-tensorboard-profiler-deprecated

**Comment by janeyx99** [comment]
The original issue seems to be about bugs with the Tensorboard plugin, which was addressed in that the TB plugin is no longer supported for memory tracing and to instead use the chrome tracer to load memory snapshots. In that way, the issue was addressed.

Regarding your warning message:
```
[W CPUAllocator.cpp:219] Memory block of unknown size was allocated before the profiling started, profiler results will not include the deallocation event
```
This message appears when there is memory allocated before the profiler kicked in and is normal (usually the parameters are loaded, and then the profiler kicks in for the training step).

**Comment by famura** [comment]
Thank you @janeyx99 for the clarification
