### ISSUE TITLE
Question on 2D-parallel unit test device mesh usage

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#107974]
The relevant code snippet is as follows:
https://github.com/pytorch/pytorch/blob/c68d0a7042e850cebc4cbe7f717fc11aedf6b9d7/test/distributed/tensor/parallel/test_fsdp_2d_parallel.py#L84-L102

Consider global world size of 8 (i.e. `world_size == 8`) with model parallel size of 2 (i.e. 2 GPUs per tensor parallel group). This code creates a 2D mesh like:
```
>>> torch.arange(8).view(2, -1)
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
```
The data parallel group is retrieved from the 0th dimension, which should be pairs of ranks like `(0, 4)`, `(1, 5)`, etc. We can check which ranks are in the group via something like the following (assuming distributed has been initialized):
```
tp_size = 2
dp_mesh_dim = 0
mesh = DeviceMesh("cuda", torch.arange(dist.get_world_size()).view(tp_size, -1))
dp_pg = mesh.get_dim_groups()[dp_mesh_dim]
if dist.get_rank() == 0:
    print(f"mesh: {mesh}")
    print(
        f"dp_pg size: {dp_pg.size()} "
       f"ranks: {torch.distributed.distributed_c10d.get_process_group_ranks(dp_pg)}"
    )
```
The print output from global rank 0 is as follows:
```
mesh: DeviceMesh:([[0, 1, 2, 3], [4, 5, 6, 7]])
dp_pg size: 2 ranks: [0, 4]
```
Therefore, the `tp_size` (i.e. the `model_parallel_size` in the original unit test) is actually 4, so I think that the variable name is mixed up. Either we should change it to the `data_parallel_size` or we should construct the mesh as `torch.arange(world_size).view(-1, tp_size)`. Let me know if I made a mistake!

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @penguinwu

**Comment by fduwjj** [comment]
@awgu yeah, I was aware of this error.. I forgot to fix it somehow. `model_parallel_size` should be changed to `data_parallel_size `

**Comment by fduwjj** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/107975
