### ISSUE TITLE
Add performance and accuracy regression testing nightlies

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#108]
These will serve to bisect:
- [ ] MNIST
- [ ] PTB Language model
- [ ] small token parser

sort of like smoke tests.

cc @VitalyFedyunin @ngimel @seemethere @malfet @pytorch/pytorch-dev-infra @mruberry

**Comment by KushajveerSingh** [comment]
@soumith I can work on this issue. Can you give me some pointers on where to begin?
