### ISSUE TITLE
[caffe2] libcaffe2.so：onnx_c2::GetEmptyStringAlreadyInited[abi:cxx11]  undefined reference

### ISSUE THREAD

**Issue by hengshanji** [pytorch/pytorch#10807]
I build caffe2 with origin caffe2 + ubuntu16.04 + anaconda3, the cmake summary is : 

-- ******** Summary ********
-- General:
--   CMake version         : 3.6.3
--   CMake command         : /home/hengshan/.conda/envs/caffe2_py2/bin/cmake
--   Git version           : v0.8.1-1502-g3c9081d-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   BLAS                  : Eigen
--   CXX flags             :  -fvisibility-inlines-hidden -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : OFF
--     Protobuf compiler   : 
--     Protobuf includes   : 
--     Protobuf libraries  : 
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.13
--     Python includes     : /home/hengshan/.conda/envs/caffe2_py2/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 6.0.21
--     CUDA root directory : /usr/local/cuda-8.0
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/local/lib/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda-8.0/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda-8.0/include
--     NVCC executable     : /usr/local/cuda-8.0/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : ON
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.3.0
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done

the error is : 
../lib/libcaffe2.so：对‘onnx_c2::GetEmptyStringAlreadyInited[abi:cxx11]()’未定义的引用
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/logging_test.dir/build.make:117: recipe for target 'bin/logging_test' failed
make[2]: *** [bin/logging_test] Error 1
CMakeFiles/Makefile2:1346: recipe for target 'caffe2/CMakeFiles/logging_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/logging_test.dir/all] Error 2
../lib/libcaffe2.so：对‘onnx_c2::GetEmptyStringAlreadyInited[abi:cxx11]()’未定义的引用
collect2: error: ld returned 1 exit status

**Comment by houseroad** [comment]
I think we have fixed this issue, please checkout our master and try again, thanks.
