### ISSUE TITLE
Which key should we use for the scalar varient of the funcs, CompositeImplicitAutograd or  CompositeExplicitAutograd?

### ISSUE THREAD

**Issue by alanhe151220037** [pytorch/pytorch#108035]
### 🐛 Describe the bug

There is something confusing me that for `bitwise_and.Scalar` and ` bitwise_or.Scalar`, one is diapatched to `CompositeExplicitAutograd`, yet the other one is diapatched to `CompositeImplicitAutograd`.
https://github.com/pytorch/pytorch/blob/138e2895d08a6517c5718b2a0118c1b23ff4664c/aten/src/ATen/native/native_functions.yaml#L7917-L7922
https://github.com/pytorch/pytorch/blob/138e2895d08a6517c5718b2a0118c1b23ff4664c/aten/src/ATen/native/native_functions.yaml#L7982-L7985
But, their impl are both simply calling the corresponding tensor varient after converting the scalar into tensor by `wrapped_scalar_tensor`.
https://github.com/pytorch/pytorch/blob/138e2895d08a6517c5718b2a0118c1b23ff4664c/aten/src/ATen/native/BinaryOps.cpp#L1196-L1198
https://github.com/pytorch/pytorch/blob/138e2895d08a6517c5718b2a0118c1b23ff4664c/aten/src/ATen/native/BinaryOps.cpp#L1229-L1231
Similar situations also occur in many other funcs that have scalar varients. Some use `CompositeImplicitAutograd` and some other use `CompositeExplicitAutograd`. So, which key should we use?

### Versions

PyTorch version: 2.1.0a0+git849fbc6
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.5.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.17

Python version: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)  [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.1.0a0+git849fbc6

**Comment by jbschlosser** [comment]
Hey @alanhe151220037! You may have better luck asking a question like this on the [PyTorch Forums](https://discuss.pytorch.org/). Note that the issues here are reserved for issues within PyTorch. Closing for now but feel free to reopen if a bug is identified.
