### ISSUE TITLE
Batching rule for aten::_scaled_dot_product_attention_math not yet implemented

### ISSUE THREAD

**Issue by ManuelPopp** [pytorch/pytorch#108065]
I got the following warning:
`UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::_scaled_dot_product_attention_math. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at ..\aten\src\ATen\functorch\BatchedFallback.cpp:84.)`

Since you asked for it ("If you see any of these cases, please let us know by opening an issue at our GitHub!"), here is the issue!

cc @zou3519 @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @Chillee @samdow @kshitij12345 @janeyx99

**Comment by Chillee** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/133964
