### ISSUE TITLE
dynamo: support torch.autograd.Function with tensor subclass input

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#108068]
### 🐛 Describe the bug

It would be great if dynamo supported tracing through a `torch.autograd.Function` where inputs can be tensor subclasses.  Currently this doesn't work.  This will be useful for ensuring Float8 training code is PT2.0 traceable.  Currently seeing:

```
  File "/data/users/vasiliy/pytorch/torch/_dynamo/variables/builder.py", line 1304, in wrap_fx_proxy_cls
    assert "source" in options and options["source"] is not None
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

repro: https://gist.github.com/vkuzo/56d54666e4e59b439ac0300094732872
concise logs: https://gist.github.com/vkuzo/2b0e37aa76a61033ee0eda7ff1d8d5a4
verbose logs: https://gist.github.com/vkuzo/0ef0845390c43fc2f551b24f3a9a7801

### Versions

master

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

**Comment by anijain2305** [comment]
cc @mlazos for visibility

**Comment by vkuzo** [comment]
@voznesenskym  helped to debug this to the following state:
1. make this change to PT core: https://gist.github.com/vkuzo/ba2239c362c15db822cc5ec89d839235 
2. instead of subclass returning a single varible, make it return a tuple (`return x` -> `return x, dummy`) as a workaround for some other missing functionality (this workaround is fine for float8)

after the two changes above, the test case passes (huge thanks voz!).  Will put up a PR and see if any CI breaks.

**Comment by vkuzo** [comment]
https://github.com/pytorch/pytorch/pull/108093
