### ISSUE TITLE
Aliased Input/Output Requirement in `aot_export_joint_simple`

### ISSUE THREAD

**Issue by gs-olive** [pytorch/pytorch#108079]
### 🐛 Describe the bug

When compiling a simple module with the function [`aot_export_joint_simple`](https://github.com/pytorch/pytorch/blob/054f3f1d8f9eb63ef8437991eba5b8f2aeee920f/torch/_functorch/aot_autograd.py#L4084), the following error is encountered:
```python
Traceback (most recent call last):
  File "~/test.py", line 16, in <module>
    gm = aot_export_joint_simple(Aliased(), [torch.rand((5, 5))], trace_joint=False)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 4134, in aot_export_joint_simple
    raise RuntimeError(f"aot_export_joint_simple does not support outputs that alias inputs. {str(metadata)}")
RuntimeError: aot_export_joint_simple does not support outputs that alias inputs. ViewAndMutationMeta(input_info=[InputAliasInfo(is_leaf=True, mutates_data=False, mutates_metadata=False)], output_info=[OutputAliasInfo(output_type=<OutputType.alias_of_input: 2>, raw_type=<class 'torch.Tensor'>, base_idx=0, dynamic_dims=set())], requires_grad_info=[False], num_intermediate_bases=0, keep_input_mutations=False, traced_tangents=[], num_symints_saved_for_bw=None)
```
The model can be found below:
```python
import torch
from torch._functorch.aot_autograd import aot_export_joint_simple

class Aliased(torch.nn.Module):
    def forward(self, x):
        return (x[None],)

gm = aot_export_joint_simple(Aliased(), [torch.rand((5, 5))], trace_joint=False)
```

If we comment out these lines:
https://github.com/pytorch/pytorch/blob/054f3f1d8f9eb63ef8437991eba5b8f2aeee920f/torch/_functorch/aot_autograd.py#L4133-L4134
Then, the module compiles and returns a graph in which the inputs and outputs are valid and no longer aliased, as so:
```python
graph():
    %arg0_1 : [num_users=1] = placeholder[target=arg0_1]
    %unsqueeze : [num_users=1] = call_function[target=torch.ops.aten.unsqueeze.default](args = (%arg0_1, 0), kwargs = {})
    return (unsqueeze,)
```
Would it be possible to have the input/output alias check in this function be controlled by a flag, since it does not seem required for the output graph to be valid?

Additionally, are there any suggestions for utilities to de-alias inputs from outputs?

### Versions

PyTorch Version: `2.1.0.dev20230825+cu121`

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by gs-olive** [comment]
A similar case is encountered for the following graph:
```python
graph():
    %x : [num_users=1] = placeholder[target=x]
    %y : [num_users=1] = placeholder[target=y]
    %add__tensor : [num_users=1] = call_function[target=torch.ops.aten.add_.Tensor](args = (%x, %y), kwargs = {})
    %relu__default : [num_users=1] = call_function[target=torch.ops.aten.relu_.default](args = (%add__tensor,), kwargs = {})
    return relu__default
```
Even though decompositions are provided to the `aot_export_joint_simple` function which remove these in-place operators, it still fails with the following error:
```python
RuntimeError: 
Found following user inputs located at [0] are mutated. This is currently banned in the aot_export workflow.
If you need this functionality, please file a github issue.

fw_metadata=ViewAndMutationMeta(input_info=[InputAliasInfo(is_leaf=True, mutates_data=True, mutates_metadata=False), InputAliasInfo(is_leaf=True, mutates_data=False, mutates_metadata=False)], output_info=[OutputAliasInfo(output_type=<OutputType.is_input: 3>, raw_type=<class 'torch.Tensor'>, base_idx=0, dynamic_dims=set())], requires_grad_info=[False, False], num_intermediate_bases=0, keep_input_mutations=False, traced_tangents=[FakeTensor(..., size=(5,))], num_symints_saved_for_bw=None)
```

Could the above check be instead applied _after_ the decompositions, since many graphs with in-place operators are decomposed into functional form during the `aot_export_joint_simple` call?

**Comment by ezyang** [comment]
The first case is possible but we would have to think about it. Truly joint tracing does a calling convention change for views, so we would need an entirely separate path to support embedding it into the graph. The nuance here is what happens if you mutate the output view; stock PyTorch autograd is unable to handle differentiating this case, so we have to do something special. In export, this is less of a problem, so you could imagine being able to say you don't care about it. Also you are not even asking for joint, in which case you don't even have any expectation autograd will even work (but then, why are you using the joint export!)

The second case is a bit more problematic. Your graph is mutating x. This is a side effect. If we were to export this graph as just relu(add(x, y)), we would lose this side effect entirely. Sometimes, these mutations are important to preserve (e.g., buffer updates in batch norm). We can't do this silently. To "fix" this, you can clone x inside your graph.

**Comment by gs-olive** [comment]
This makes sense - thanks for the detailed response @ezyang. To answer your question, I am using the `aot_export_joint_simple` in this case because it does not hoist parameters and buffers to graph inputs, whereas the `aot_module_simplified` does. Our use case requires that the parameters and buffers stay as nodes in the graph and not be hoisted to inputs. Do you have suggestions for other functions which can perform AOT tracing but will not modify the parameters and buffers?

**Comment by ezyang** [comment]
Yeah, it kind of just sounds like there's just some more API surface area that @bdhirsh hasn't gotten around to adding yet. @bdhirsh is very high in demand these days, are you interested in helping us spec out the API you want?

**Comment by gs-olive** [comment]
Definitely! I can post a detailed comment here providing the desired details and specification.

**Comment by gs-olive** [comment]
Hello - thank you for the discussion above. I have provided a sample specification for the desired API here. Please let me know if there is anything that might need more clarity in this specification, or any suggested modifications.

```python
def aot_inference_module(
    func: Callable,
    args,
    *,
    decompositions: Optional[Dict] = None,
    dynamic: bool = False,
) -> torch.fx.GraphModule:
    """
    A utility built for inference, tracing only the forward graph and retaining module attributes.

    The function has both export and compile-inspired components. It can support dynamic shapes/dimensions.

    From `aot_export_joint_simple` it has:
    - This function enforces the `no_grad` context, being an inference-only method
    - This function does not hoist the parameters or buffers to inputs, instead leaving them as `get_attr` nodes
    - `args` cannot contain any pytrees (they must have been pytree_flattened already)

    From `aot_module_simplified` it has:
    - This function does not check or enforce any restrictions on input/output aliasing or input mutation
      - This could be controlled by an argument such as `allow_input_aliasing_mutation: bool = False`, if desired
    """
```

**Comment by bdhirsh** [comment]
Hey @gs-olive - we now have `torch.export.export` ([link](https://pytorch.org/docs/stable/export.html)) - it also hoists params/buffers into inputs, but there are some private utils that you can use to do the unlifting yourself. (you can probably re-implement their logic if you're worried about BC). E.g. [here](https://github.com/pytorch/pytorch/blob/main/torch/_export/__init__.py#L217) or [here](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/compile_fx.py#L1158)

**Comment by gs-olive** [comment]
Hi @bdhirsh - thanks for the suggestion. Is it possible to use `torch.export.export` from within a `torch.compile` backend? That is our use-case for the `aot_inference_module`, and our current usage for `aot_export_joint_simple`. From a few sample runs, it seems the `FakeTensorMode` doesn't match, which causes an error to be thrown.

**Comment by bdhirsh** [comment]
Oh - you can probably just use `aot_export_module` directly then, and use the same [utils](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/compile_fx.py#L1158) to unlift the params/buffers

**Comment by bdhirsh** [comment]
As an aside - any reason you're not using AOTAutograd to get proper autograd support, if you're sitting underneath torch.compile?

**Comment by gs-olive** [comment]
The backend I am currently working on is an inference-only compiler, so we do not need the backward graph. The ATen tracing, decompositions, and other general utilities provided by AOT, however, are very useful for the forward graph.

**Comment by mlazos** [comment]
@gs-olive is this considered resolved?

**Comment by gs-olive** [comment]
We have a workaround for the proposed method [mentioned here](https://github.com/pytorch/pytorch/issues/108079#issuecomment-1710887979), so the issue can be closed for now, yes.
