### ISSUE TITLE
Sequence Parallel for non-Pairwise Parallel and uneven MLP layers.

### ISSUE THREAD

**Issue by conceptofmind** [pytorch/pytorch#108106]
Hi all,

Is there a way to apply SequenceParallel to RowwiseParallel and ColwiseParallel layers similar to how it is applied to PairwiseParallel?

```python
class SequenceParallel(PairwiseParallel):
    """
    SequenceParallel concatenate colwise and rowwise styles as a fixed
    pair together with sequence parallel like what Megatron-LM Sequence parallel
    (https://arxiv.org/pdf/2205.05198.pdf) is doing.
    We assume both input and output need to be sharded DTensors.

    .. warning::
        SequenceParallel does not support ``nn.MultiheadAttention``,
        ``nn.Transformer`` well at this moment. One workaround is to apply
        ``ColwiseParallel`` and ``RowwiseParallel`` to the components of
        transformer. We recommend to use ``SequenceParallel`` only
        for even-number-layer MLP for now.
    """

    def __init__(self) -> None:
        super().__init__(make_input_reshard_replicate, make_output_reshard_tensor)
```
I typically will swap the layers with Apex-compatible ones but I am interested in using `parallelize_module` to remove that dependency.

Thank you,

Enrico

### Versions

main (2.1.0a0+git8688965)
```[tasklist]
### Tasks
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

**Comment by awgu** [comment]
cc: @fduwjj

**Comment by fduwjj** [comment]
@conceptofmind yes you can. You just passing different prepare_input and prepare_out to the parallel_style. For example, for sequence parallel can be:
```
ColwiseParallel(_prepare_input=make_input_shard_1d)
RowwiseParallel(_prepare_input=make_input_shard_1d, _prepare_output=make_output_reshard_tensor)
```
This way we call all-gather and reduce-scatter for you internally.

**Comment by conceptofmind** [comment]
> @conceptofmind yes you can. You just passing different prepare_input and prepare_out to the parallel_style. For example, for sequence parallel can be:
> 
> ```
> ColwiseParallel(_prepare_input=make_input_shard_1d)
> RowwiseParallel(_prepare_input=make_input_shard_1d, _prepare_output=make_output_reshard_tensor)
> ```
> 
> This way we call all-gather and reduce-scatter for you internally.

Hi @fduwjj,

Thank you for the response.

To outline an example for comprehension, say you have a column and row parallel layer in Apex:
```python
self.qkv = ColumnParallelLinear(
    args.dim,
    self.n_heads * self.head_dim * 3,
    bias=False,
    gather_output=False,
    init_method=lambda x: x,
    sequence_parallel_enabled=True,
)
self.o = RowParallelLinear(
    args.n_heads * self.head_dim * 3,
    args.dim,
    bias=False,
    input_is_parallel=True,
    init_method=lambda x: x,
    sequence_parallel_enabled=True,
)
```
If we would like to apply PyTorch Sequence Parallelism to using Colwise and Rowwise Parallel linear layers it would follow something like:
```python
device_mesh = DeviceMesh("cuda", torch.arange(0, args.world_size))

parallelized_block = parallelize_module(
    module= model.get_submodule(module_path),
    device_mesh=device_mesh,
    parallelize_plan={
        "qkv": ColwiseParallel(_prepare_input=make_input_shard_1d),
        "o": RowwiseParallel(_prepare_input=make_input_shard_1d, _prepare_output=make_output_reshard_tensor),
    },
    tp_mesh_dim=1,
)
```
Or in the case of an MLP/FF layer with 3 Apex linear layers:
```python
self.w1 = ColumnParallelLinear(
    dim, 
    hidden_dim, 
    bias=False, 
    gather_output=False, 
    init_method=lambda x: x,
    sequence_parallel_enabled=True,
)
self.w2 = RowParallelLinear(
    hidden_dim, 
    dim, 
    bias=False, 
    input_is_parallel=True, 
    init_method=lambda x: x,
    sequence_parallel_enabled=True,
)
self.w3 = ColumnParallelLinear(
    dim, 
    hidden_dim, 
    bias=False, 
    gather_output=False, 
    init_method=lambda x: x,
    sequence_parallel_enabled=True,
)
```
Then the matching PyTorch Sequence Parallel would be:
```python
device_mesh = DeviceMesh("cuda", torch.arange(0, args.world_size))

parallelized_block = parallelize_module(
    module= model.get_submodule(module_path),
    device_mesh=device_mesh,
    parallelize_plan={
        "w1": ColwiseParallel(_prepare_input=make_input_shard_1d),
        "w2": RowwiseParallel(_prepare_input=make_input_shard_1d, _prepare_output=make_output_reshard_tensor),
        "w3": ColwiseParallel(_prepare_input=make_input_shard_1d),
    },
    tp_mesh_dim=1,
)
```
I greatly appreciate your help.

Thank you,

Enrico

**Comment by fduwjj** [comment]
@conceptofmind if you want to use PyTorch native solution, you don't need the `ColumnParallelLinear` and `RowParallelLinear` We will handle the collectives for you. And by specifying different `_prepare_input` and `_prepare_output` you essentially are switching from sequence parallel and tensor parallel.

**Comment by conceptofmind** [comment]
Thank you for the help.

> @conceptofmind if you want to use PyTorch native solution, you don't need the `ColumnParallelLinear` and `RowParallelLinear` We will handle the collectives for you. And by specifying different `_prepare_input` and `_prepare_output` you essentially are switching from sequence parallel and tensor parallel.
