### ISSUE TITLE
Compile error triggered with nn.InstanceNorm with torch.compile()

### ISSUE THREAD

**Issue by GwiHwan-Go** [pytorch/pytorch#108164]
### 🐛 Describe the bug

When using torch.compile on nn.InstanceNorm3d, I encountered an error as described below.
stacktrace
```
  File "/home/guihuan/.conda/envs/night_new/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 1410, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/home/guihuan/.conda/envs/night_new/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 1397, in run_node
    return node.target(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guihuan/.conda/envs/night_new/lib/python3.11/site-packages/torch/nn/functional.py", line 2522, in instance_norm
    _verify_spatial_size(input.size())
  File "/home/guihuan/.conda/envs/night_new/lib/python3.11/site-packages/torch/nn/functional.py", line 2489, in _verify_spatial_size
    raise ValueError(f"Expected more than 1 spatial element when training, got input size {size}")
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <function instance_norm at 0x7f511e6cbce0>(*(FakeTensor(..., device='cuda:0', size=(1, 10, 1, 1, 1)), FakeTensor(..., size=(10,)), FakeTensor(..., size=(10,)), Parameter(FakeTensor(..., size=(10,), requires_grad=True)), Parameter(FakeTensor(..., size=(10,), requires_grad=True)), True, -0.2519806, 2.4881886), **{}):
Expected more than 1 spatial element when training, got input size torch.Size([1, 10, 1, 1, 1])

from user code:
   File "/home/guihuan/LLM/experiments/nightly/fuzz1/4.py", line 7, in <resume in forward>
    x = torch.nn.InstanceNorm3d(num_features=10,eps=2.4881886,momentum=-0.2519806,affine=True,track_running_stats=True)(input=x, )
  File "/home/guihuan/.conda/envs/night_new/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/guihuan/.conda/envs/night_new/lib/python3.11/site-packages/torch/nn/modules/instancenorm.py", line 85, in forward
    return self._handle_no_batch_input(input)
  File "/home/guihuan/.conda/envs/night_new/lib/python3.11/site-packages/torch/nn/modules/instancenorm.py", line 33, in _handle_no_batch_input
    return self._apply_instance_norm(input.unsqueeze(0)).squeeze(0)
  File "/home/guihuan/.conda/envs/night_new/lib/python3.11/site-packages/torch/nn/modules/instancenorm.py", line 36, in _apply_instance_norm
    return F.instance_norm(

```
🔄 To Reproduce
Here's a minimal example to reproduce the issue:
Update(08/31) : revised reproduction code
```python
import torch
import torch.nn as nn
import traceback

def forward(x):
    x = torch.nn.InstanceNorm3d(num_features=10, eps=2.4881886, momentum=-0.2519806, affine=True, track_running_stats=True)(input=x)
    return x

no_op_info = forward(torch.randn([10, 10, 1, 8, 9]))
print(no_op_info)

op_info = torch.compile(forward)(torch.randn([10, 10, 1, 8, 9]).to('cuda'))
print(op_info)
```

If this behavior is intended, or if there are known bugs related to this issue, please feel free to close it. If additional information is needed, I'm more than willing to provide it.

### Versions

PyTorch version: 2.1.0.dev20230828+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2070
GPU 1: NVIDIA GeForce RTX 2070
GPU 2: NVIDIA GeForce RTX 2070
GPU 3: NVIDIA GeForce RTX 2070

Nvidia driver version: 535.86.10
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
CPU family:                      6
Model:                           63
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       2
Stepping:                        2
CPU max MHz:                     3200.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4794.42
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear flush_l1d
Virtualization:                  VT-x
L1d cache:                       512 KiB (16 instances)
L1i cache:                       512 KiB (16 instances)
L2 cache:                        4 MiB (16 instances)
L3 cache:                        40 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230828+cu118
[pip3] torchaudio==2.1.0.dev20230828+cu118
[pip3] torchvision==0.16.0.dev20230828+cu118
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+e6216047b8          pypi_0    pypi
[conda] torch                     2.1.0.dev20230828+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230828+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230828+cu118          pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by bdhirsh** [comment]
I get the same error when I run your repro in eager mode @GwiHwan-Go 
```
import torch
import torch.nn as nn
import traceback

def forward(x):
    
    x = torch.nn.InstanceNorm3d(num_features=10,eps=2.4881886,momentum=-0.2519806,affine=True,track_running_stats=True)(input=x, )        
    return x

op_info = forward(torch.randn([10,1,1,1]).to('cuda'))
print(op_info)
```

So I think this is a legitimate user error?

**Comment by GwiHwan-Go** [comment]
> So I think this is a legitimate user error?

You are correct; the original code may indeed represent a legitimate user error. However, I have an alternative example to consider. In the following code, it appears that only the compiled nn.InstanceNorm3d operation triggers an error in the latest nightly build:
```python
import torch
import torch.nn as nn
import traceback

def forward(x):
    x = torch.nn.InstanceNorm3d(num_features=10, eps=2.4881886, momentum=-0.2519806, affine=True, track_running_stats=True)(input=x)
    return x

# CPU Execution
no_op_info = forward(torch.randn([10, 10, 1, 8, 9]))
print(no_op_info)

# CUDA Execution
op_info = torch.compile(forward)(torch.randn([10, 10, 1, 8, 9]).to('cuda'))
print(op_info)
```
Thank you for looking into this issue.

**Comment by Chillee** [comment]
In this case you're also comparing running on CPU to running on CUDA. If you remove `torch.compile` from the forward it still errors.

**Comment by GwiHwan-Go** [comment]
> In this case you're also comparing running on CPU to running on CUDA. If you remove `torch.compile` from the forward it still errors.

Ye, it's my fault. I forgot moving the layer to GPU first.
