### ISSUE TITLE
accessing the network's source code from a saved model

### ISSUE THREAD

**Issue by iariav** [pytorch/pytorch#10813]
Hi,
i asked this question in the forum already but got no response, but i believe a pytorch developer should have an answer to this so i thought i'll try to ask here as well. sorry if it's not OK..

i just ran several different versions of my network and i saved my models using torch.save().
i now want to reproduce the experiment with the best accuracy but i don’t remember which version of my network’s Class was used in that experiment.
when i tried to load the model with torch.load() i got the following message (which exactly describes the situation i’m in):
**“you can retrieve the original source code by accessing the object’s source attribute or set Module.dump_patches = True` and use the patch tool to revert the changes.”**

problem is i don’t see any “source attribute” in my loaded object and don’t know what the patch tool is.

does anyone know **how can i access the source code of the network’s class definition that was used when the saved model was created**?

thanks a lot

**Comment by soumith** [comment]
point us to your forum post, I'll reply there.

**Comment by iariav** [comment]
@soumith 
thanks!
this is the post - 
https://discuss.pytorch.org/t/accessing-the-nets-class-source-code/22084?u=iariav
