### ISSUE TITLE
`ignore_index` isn't used for MPS backend in CrossEntropyLoss / F.cross_entropy

### ISSUE THREAD

**Issue by ali-tny** [pytorch/pytorch#108148]
### 🐛 Describe the bug

`ignore_index` isn't used properly with the mps backend, and seems to be ignored completely:
1. An error isn't raised for out of range indexes (positive or negative, and whether they're equal to `ignore_index` or not):

firstly, with a negative index that isn't equal to `ignore_index`:
```python
import torch
import torch.nn.functional as F
inputs = torch.Tensor([[0, 1], [1.0, 0], [0, 1]]).to("mps")
targets = torch.LongTensor([1, 0, -100]).to("mps")
F.cross_entropy(inputs, targets, ignore_index=-1, reduction="none")
```
```
tensor([0.3133, 0.3133, -0.0000], device='mps:0')
```
(Ie, no error raised)

and the same issue with a positive index that's out of range:
```python
import torch
import torch.nn.functional as F
inputs = torch.Tensor([[0, 1], [1.0, 0], [0, 1]]).to("mps")
targets = torch.LongTensor([1, 0, 5]).to("mps")
F.cross_entropy(inputs, targets, ignore_index=-1, reduction="none")
```
```
tensor([0.3133, 0.3133, -0.0000], device='mps:0')
```
(Ie, no error raised)

Compare to CPU:
negative index case:
```python
import torch
import torch.nn.functional as F
inputs = torch.Tensor([[0, 1], [1.0, 0], [0, 1]]).to("cpu")
targets = torch.LongTensor([1, 0, -100]).to("cpu")
F.cross_entropy(inputs, targets, ignore_index=-1, reduction="none")
```
```
IndexError: Target -100 is out of bounds.
```

and positive index that's out of range:
```python
import torch
import torch.nn.functional as F
inputs = torch.Tensor([[0, 1], [1.0, 0], [0, 1]]).to("cpu")
targets = torch.LongTensor([1, 0, 5]).to("cpu")
F.cross_entropy(inputs, targets, ignore_index=-1, reduction="none")
```
```
IndexError: Target 5 is out of bounds.
```

2. `ignore_index` target values aren't left out of the average when reduction="mean" (the default), making the loss seem lower than it should be
```python
import torch
import torch.nn.functional as F
inputs = torch.Tensor([[0, 1], [1.0, 0], [0, 1]]).to("mps")
targets = torch.LongTensor([1, 0, -100]).to("mps")
print(F.cross_entropy(inputs, targets, ignore_index=-100, reduction="none"))
print(F.cross_entropy(inputs, targets, ignore_index=-100, reduction="mean"))
```
```
tensor([0.3133, 0.3133, -0.0000], device='mps:0')
tensor(0.2088, device='mps:0')
```
Here 0.2088 == mean([0.3133, 0.3133, -0.0000]), where the final index should be left out of the mean (since the label was -100 == `ignore_index`)

Compare to the CPU backend:
```python
import torch
import torch.nn.functional as F
inputs = torch.Tensor([[0, 1], [1.0, 0], [0, 1]]).to("cpu")
targets = torch.LongTensor([1, 0, -100]).to("cpu")
print(F.cross_entropy(inputs, targets, ignore_index=-100, reduction="none"))
print(F.cross_entropy(inputs, targets, ignore_index=-100, reduction="mean"))
```
```
tensor([0.3133, 0.3133, 0.0000])
tensor(0.3133)
```
The final index is correctly ignored in the mean.
 

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.6 (default, Oct 18 2022, 12:41:40)  [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-13.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.0
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
Due to the way that nll_loss is implemented on mps, it would be a bit costly to check and raise errors for targets that are out of the bounds, so I leave it as is. The incorrect results corresponding to the default `ignore_index` should be fixed by the linked PR.

**Comment by ali-tny** [comment]
@qqaatw totally agree the main thing is the `ignore_index` being ignored. thanks v much!
