### ISSUE TITLE
Tag v0.4.1 leads to 0.5.0a0

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#10814]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

I've built pytorch from source after `git checkout v0.4.1`, however, the version is 0.5.0.
Tag v0.4.1 leads to 0.5.0a0

## Code example
```
>>> import torch
>>> torch.__version__
'0.5.0a0+a24163a'
```

## System Info
Collecting environment information...
PyTorch version: 0.5.0a0+a24163a
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1070 Ti
Nvidia driver version: 396.37
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/lib64/libcudnn.so.7.2.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] magma-cuda90              2.3.0                         1    pytorch
[conda] torch                     0.5.0a0+a24163a           <pip>

**Comment by SsnL** [comment]
yes, see #9926
