### ISSUE TITLE
[feature request] torch.meshgrid improvements

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#10823]
- [ ] torch.meshgrid should assert inputs have same type
- [ ] torch.meshgrid should support varargs (by method of python wrapper) to match numpy api: https://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html

**Comment by upriser7** [comment]
@zou3519, If this issue is beginner friendly, I would like to take this on.

**Comment by zou3519** [comment]
Yes, this one should be beginner friendly, please feel free to pick it up!

**Comment by vishwakftw** [comment]
This can be closed now, I think.
