### ISSUE TITLE
torch-2.1.0.dev20230829 bug 

### ISSUE THREAD

**Issue by wukong1992** [pytorch/pytorch#108227]
### 🐛 Describe the bug

Bug with torch-2.1.0.dev20230829: import torch error:  SystemError: type torch._C._TensorBase has the Py_TPFLAGS_HAVE_GC flag but has no traverse function

### Versions

torch-2.1.0.dev20230829

cc @albanD

**Comment by colesbury** [comment]
@wukong1992, what version of Python are you using?

@albanD, this looks like something you fixed over a year ago in https://github.com/pytorch/pytorch/commit/4b7de265569f7fd731dd1cfea83ce804cc22f7c0.

**Comment by albanD** [comment]
I cannot reproduce this with a recent Python 3.11 version:
```
Python 3.11.4+ (heads/3.11:f207b346d4, Jun 11 2023, 14:30:06) [GCC 12.3.1 20230508 (Red Hat 12.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.1.0.dev20230830+cpu'
```

Will wait for @wukong1992 version to see if there is another version of python I should try

**Comment by malfet** [comment]
This seems to be linux specific, as I can use PyTorch nightlies on MacOS with 3.11 just fine:
```
% python3 -mpip install torch --pre --index-url https://download.pytorch.org/whl/nightly/cpu
...
Successfully installed MarkupSafe-2.1.2 jinja2-3.1.2 mpmath-1.2.1 networkx-3.0rc1 sympy-1.11.1 torch-2.1.0.dev20230830
% python3 -c "import sys;import torch;print(sys.version_info)"
sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
```

**Comment by wukong1992** [comment]
@albanD @colesbury @malfet Thanks for your reply. I run on linux, and my python version is 3.11.5.
