### ISSUE TITLE
[HigherOrderOp] Should support SymInt as input to body function

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#108283]
### 🐛 Describe the bug

Right now, if a SymInt gets passed to the body of a higher-order op, we don't support it:

```py
import torch
from torch._higher_order_ops.wrap import wrap

@torch.compile(backend='eager', fullgraph=True, dynamic=True)
def f(x):
    i = x.size(0)
    return wrap(lambda x, i: x.view(i), x, i)

x = torch.randn(3, 1)
f(x)
```
(try dynamic=False to see it succeed). We should support this; the symint should get recorded as the input of the body function.

NB: wrap(f, *args) is a higher order op whose semantics are to just run f(*args).

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by zou3519** [comment]
NB: there's an open question to *which* higher order ops should actually support symints in their body. The default is probably that all of them should support symints, but specific higher order ops (like cond) might impose restrictions that e.g. all the inputs should be Tensors.

**Comment by ezyang** [comment]
You can always make SymInt "work" by converting it into a 0d tensor before reading it out again in body.
