### ISSUE TITLE
exporting model to ONNX with change to single tensor element fails silently

### ISSUE THREAD

**Issue by newling** [pytorch/pytorch#10820]
## Issue description

Modification to single element of tensor is not exported to ONNX graph

## Code example
```
    def forward(self, x):
        """
        where x is a 2-D tensor
        """
        x[0,0] = 100
        y = torch.cat([x,x], dim = 0)
        return y
```

Exporting the above produces an ONNX Graph with just one node (of op_type Concat). 

It would be good if an error were raised if it is not feasible to export this to ONNX. 

## System Info
- PyTorch version: '0.4.1'

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by spandantiwari** [comment]
@newling - 0.4.1 is quite old. Can you please try the latest version of PyTorch and see if this issue is resolved. Please feel free to reopen this issue if you see any issues with the latest version.
