### ISSUE TITLE
pytorch cnn benchmarks 

### ISSUE THREAD

**Issue by vilmara** [pytorch/pytorch#10836]
Hi all, are there some kind of pytorch cnn benchmarks scripts that I can use?. Some recommendations?

**Comment by peterjc123** [comment]
What about this: https://github.com/mingfeima/convnet-benchmarks?

**Comment by soumith** [comment]
closing via https://github.com/mingfeima/convnet-benchmarks/tree/master/pytorch and https://github.com/pytorch/examples/blob/master/imagenet
