### ISSUE TITLE
compiling for rocm, but getting cuda errors

### ISSUE THREAD

**Issue by iateadonut** [pytorch/pytorch#108344]
### 🐛 Describe the bug

I'm compiling for rocm but getting cuda errors:

notice USE_CUDA=0

using Python 3.10.12 in conda.

export PATH=$PATH:/opt/rocm-5.5.1/bin:/opt/rocm-5.5.1/opencl/bin
export USE_CUDA=0
export CMAKE_CXX_COMPILER=/usr/bin/g++
export CMAKE_C_COMPILER=/usr/bin/gcc
export CC=/usr/bin/gcc
export CXX=/usr/bin/g++

conda install cmake ninja mkl mkl-include

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
# if you are updating an existing checkout
# git submodule sync
git submodule update --init --recursive

conda install cryptography pillow
pip install -r requirements.txt

# Only run this if you're compiling for ROCm
python tools/amd_build/build_amd.py

python setup.py develop

Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o

[5429/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o
FAILED: caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o 
/opt/cache/bin/sccache /usr/bin/g++ -DAT_PER_OPERATOR_HEADERS -DBUILD_ONEDNN_GRAPH -DCAFFE2_BUILD_MAIN_LIB -DCPUINFO_SUPPORTED_PLATFORM=1 -DFMT_HEADER_ONLY=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DIDEEP_USE_MKL -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DNNP_CONVOLUTION_ONLY=0 -DNNP_INFERENCE_ONLY=0 -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_EXTERNAL_MZCRC -DUSE_RPC -DUSE_TENSORPIPE -D_FILE_OFFSET_BITS=64 -Dtorch_cpu_EXPORTS -I/home/user/pytorch310/build/aten/src -I/home/user/pytorch310/aten/src -I/home/user/pytorch310/build -I/home/user/pytorch310 -I/home/user/pytorch310/cmake/../third_party/benchmark/include -I/home/user/pytorch310/third_party/onnx -I/home/user/pytorch310/build/third_party/onnx -I/home/user/pytorch310/third_party/foxi -I/home/user/pytorch310/build/third_party/foxi -I/home/user/pytorch310/torch/csrc/api -I/home/user/pytorch310/torch/csrc/api/include -I/home/user/pytorch310/caffe2/aten/src/TH -I/home/user/pytorch310/build/caffe2/aten/src/TH -I/home/user/pytorch310/build/caffe2/aten/src -I/home/user/pytorch310/build/caffe2/../aten/src -I/home/user/pytorch310/torch/csrc -I/home/user/pytorch310/third_party/miniz-2.1.0 -I/home/user/pytorch310/third_party/kineto/libkineto/include -I/home/user/pytorch310/third_party/kineto/libkineto/src -I/home/user/pytorch310/aten/src/ATen/.. -I/home/user/pytorch310/third_party/FXdiv/include -I/home/user/pytorch310/c10/.. -I/home/user/pytorch310/third_party/pthreadpool/include -I/home/user/pytorch310/third_party/cpuinfo/include -I/home/user/pytorch310/third_party/QNNPACK/include -I/home/user/pytorch310/aten/src/ATen/native/quantized/cpu/qnnpack/include -I/home/user/pytorch310/aten/src/ATen/native/quantized/cpu/qnnpack/src -I/home/user/pytorch310/third_party/cpuinfo/deps/clog/include -I/home/user/pytorch310/third_party/NNPACK/include -I/home/user/pytorch310/third_party/fbgemm/include -I/home/user/pytorch310/third_party/fbgemm -I/home/user/pytorch310/third_party/fbgemm/third_party/asmjit/src -I/home/user/pytorch310/third_party/ittapi/src/ittnotify -I/home/user/pytorch310/third_party/FP16/include -I/home/user/pytorch310/third_party/tensorpipe -I/home/user/pytorch310/build/third_party/tensorpipe -I/home/user/pytorch310/third_party/tensorpipe/third_party/libnop/include -I/home/user/pytorch310/third_party/fmt/include -I/home/user/pytorch310/build/third_party/ideep/mkl-dnn/include -I/home/user/pytorch310/third_party/ideep/mkl-dnn/src/../include -I/home/user/pytorch310/third_party/flatbuffers/include -isystem /home/user/pytorch310/build/third_party/gloo -isystem /home/user/pytorch310/cmake/../third_party/gloo -isystem /home/user/pytorch310/cmake/../third_party/tensorpipe/third_party/libuv/include -isystem /home/user/pytorch310/cmake/../third_party/googletest/googlemock/include -isystem /home/user/pytorch310/cmake/../third_party/googletest/googletest/include -isystem /home/user/pytorch310/third_party/protobuf/src -isystem /home/user/anaconda3/envs/petals-compiletorch310/include -isystem /home/user/pytorch310/third_party/gemmlowp -isystem /home/user/pytorch310/third_party/neon2sse -isystem /home/user/pytorch310/third_party/XNNPACK/include -isystem /home/user/pytorch310/third_party/ittapi/include -isystem /home/user/pytorch310/cmake/../third_party/eigen -isystem /home/user/pytorch310/third_party/ideep/mkl-dnn/include/oneapi/dnnl -isystem /home/user/pytorch310/third_party/ideep/include -isystem /home/user/pytorch310/build/include -D_GLIBCXX_USE_CXX11_ABI=1 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -std=gnu++17 -fPIC -DMKL_HAS_SBGEMM -DTORCH_USE_LIBUV -DCAFFE2_USE_GLOO -DTH_HAVE_THREAD -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-type-limits -Wno-array-bounds -Wno-strict-overflow -Wno-strict-aliasing -Wno-missing-braces -Wno-maybe-uninitialized -fvisibility=hidden -O2 -pthread -DASMJIT_STATIC -fopenmp -MD -MT caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o -MF caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o.d -o caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o -c /home/user/pytorch310/torch/csrc/jit/ir/ir.cpp
/home/user/pytorch310/torch/csrc/jit/ir/ir.cpp: In member function ‘bool torch::jit::Node::hasSideEffects() const’:
/home/user/pytorch310/torch/csrc/jit/ir/ir.cpp:1191:16: error: ‘set_stream’ is not a member of ‘torch::jit::cuda’; did you mean ‘c10::cuda::set_stream’?
 1191 |     case cuda::set_stream:
      |                ^~~~~~~~~~
In file included from /home/user/pytorch310/torch/csrc/jit/ir/ir.h:18,
                 from /home/user/pytorch310/torch/csrc/jit/ir/ir.cpp:1:
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:228:11: note: ‘c10::cuda::set_stream’ declared here
  228 |   _(cuda, set_stream)                \
      |           ^~~~~~~~~~
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:353:35: note: in definition of macro ‘DEFINE_SYMBOL’
  353 |   namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
      |                                   ^
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:354:1: note: in expansion of macro ‘FORALL_NS_SYMBOLS’
  354 | FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
      | ^~~~~~~~~~~~~~~~~
/home/user/pytorch310/torch/csrc/jit/ir/ir.cpp:1192:16: error: ‘_set_device’ is not a member of ‘torch::jit::cuda’; did you mean ‘c10::cuda::_set_device’?
 1192 |     case cuda::_set_device:
      |                ^~~~~~~~~~~
In file included from /home/user/pytorch310/torch/csrc/jit/ir/ir.h:18,
                 from /home/user/pytorch310/torch/csrc/jit/ir/ir.cpp:1:
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:227:11: note: ‘c10::cuda::_set_device’ declared here
  227 |   _(cuda, _set_device)               \
      |           ^~~~~~~~~~~
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:353:35: note: in definition of macro ‘DEFINE_SYMBOL’
  353 |   namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
      |                                   ^
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:354:1: note: in expansion of macro ‘FORALL_NS_SYMBOLS’
  354 | FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
      | ^~~~~~~~~~~~~~~~~
/home/user/pytorch310/torch/csrc/jit/ir/ir.cpp:1193:16: error: ‘_current_device’ is not a member of ‘torch::jit::cuda’; did you mean ‘c10::cuda::_current_device’?
 1193 |     case cuda::_current_device:
      |                ^~~~~~~~~~~~~~~
In file included from /home/user/pytorch310/torch/csrc/jit/ir/ir.h:18,
                 from /home/user/pytorch310/torch/csrc/jit/ir/ir.cpp:1:
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:229:11: note: ‘c10::cuda::_current_device’ declared here
  229 |   _(cuda, _current_device)           \
      |           ^~~~~~~~~~~~~~~
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:353:35: note: in definition of macro ‘DEFINE_SYMBOL’
  353 |   namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
      |                                   ^
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:354:1: note: in expansion of macro ‘FORALL_NS_SYMBOLS’
  354 | FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
      | ^~~~~~~~~~~~~~~~~
/home/user/pytorch310/torch/csrc/jit/ir/ir.cpp:1194:16: error: ‘synchronize’ is not a member of ‘torch::jit::cuda’; did you mean ‘c10::cuda::synchronize’?
 1194 |     case cuda::synchronize:
      |                ^~~~~~~~~~~
In file included from /home/user/pytorch310/torch/csrc/jit/ir/ir.h:18,
                 from /home/user/pytorch310/torch/csrc/jit/ir/ir.cpp:1:
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:230:11: note: ‘c10::cuda::synchronize’ declared here
  230 |   _(cuda, synchronize)               \
      |           ^~~~~~~~~~~
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:353:35: note: in definition of macro ‘DEFINE_SYMBOL’
  353 |   namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
      |                                   ^
/home/user/pytorch310/aten/src/ATen/core/interned_strings.h:354:1: note: in expansion of macro ‘FORALL_NS_SYMBOLS’
  354 | FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
      | ^~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-aligned-allocation-unavailable’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-unused-private-field’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-invalid-partial-specialization’ may have been intended to silence earlier diagnostics
[5430/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/operator_upgraders/utils.cpp.o
[5431/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/operator_upgraders/version_map.cpp.o
[5432/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/mobile/register_ops_common_utils.cpp.o
[5433/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/mobile/promoted_prim_ops.cpp.o
[5434/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/mobile/quantization.cpp.o
[5435/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/operator_upgraders/upgraders.cpp.o
[5436/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/mobile/nnc/context.cpp.o
[5437/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/mobile/upgrader_mobile.cpp.o
[5438/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/passes/add_if_then_else.cpp.o
[5439/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/operator_upgraders/upgraders_entry.cpp.o
[5440/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/mobile/nnc/aot_compiler.cpp.o
[5441/6353] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/passes/bailout_graph.cpp.o
[5442/6353] Building CXX object third_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/src/FbgemmI8DepthwiseAvx2.cc.o
ninja: build stopped: subcommand failed.
Building wheel torch-2.1.0a0+git9ed0b3f
-- Building version 2.1.0a0+git9ed0b3f
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_INSTALL_PREFIX=/home/user/pytorch310/torch -DCMAKE_PREFIX_PATH=/home/user/anaconda3/envs/petals-compiletorch310/lib/python3.10/site-packages;/home/user/anaconda3/envs/petals-compiletorch310 -DNUMPY_INCLUDE_DIR=/home/user/.local/lib/python3.10/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/home/user/anaconda3/envs/petals-compiletorch310/bin/python -DPYTHON_INCLUDE_DIR=/home/user/anaconda3/envs/petals-compiletorch310/include/python3.10 -DPYTHON_LIBRARY=/home/user/anaconda3/envs/petals-compiletorch310/lib/libpython3.10.a -DTORCH_BUILD_VERSION=2.1.0a0+git9ed0b3f -DUSE_CUDA=0 -DUSE_NUMPY=True /home/user/pytorch310
cmake --build . --target install --config Release

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.2.0-31-generic-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      39 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             12
On-line CPU(s) list:                0-11
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
CPU family:                         6
Model:                              165
Thread(s) per core:                 2
Core(s) per socket:                 6
Socket(s):                          1
Stepping:                           3
CPU max MHz:                        4500.0000
CPU min MHz:                        800.0000
BogoMIPS:                           6199.99
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          192 KiB (6 instances)
L1i cache:                          192 KiB (6 instances)
L2 cache:                           1.5 MiB (6 instances)
L3 cache:                           12 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-11
Vulnerability Gather data sampling: Mitigation; Microcode
Vulnerability Itlb multihit:        KVM: Mitigation: VMX disabled
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:             Mitigation; Enhanced IBRS
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Mitigation; Microcode
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] mkl                       2023.1.0         h213fc3f_46343  
[conda] mkl-include               2023.1.0         h06a4308_46343  

cc @malfet @seemethere @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by hongxiayang** [comment]
@iateadonut HI, If you build from source for ROCM, 
1. to install ROCm. https://rocm.docs.amd.com/en/latest/deploy/linux/quick_start.html
2. Recommand you try to build based on ROCm's docker image. Instruction is as below:
 https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm

Thanks.

**Comment by iateadonut** [comment]
The point is that even with the NO_CUDA flag, it still tries to compile with cuda support.

**Comment by hongxiayang** [comment]
based on your error, looks like USE_ROCM flag is not on during building the component. Can you run "rocminfo" and what is the output? thanks.

**Comment by iateadonut** [comment]
thanks.  when i use USE_ROCM, it get passed the point in question.
