### ISSUE TITLE
[inductor][cpu] [amp] acc check fails

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#108333]
<p>amp cpu accuracy check failed models</p>
<p>Repro</p>

bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
single inference performance SUITE MODEL amp first static default 0

<p>new_failures</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>suite</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>gluon_inception_v3</td>
      <td>X</td>
      <td>âˆš</td>
      <td>timm_models</td>
      <td>gluon_inception_v3, [2023-08-26 08:23:43 745] torch._dynamo.utils: [ERROR] RMSE (res-fp64): 0.04454
        (ref-fp64): 0.01602 and shape=torch.Size([1 1000])</td>
    </tr>
    <tr>
      <td>lcnet_050</td>
      <td>X</td>
      <td>âˆš</td>
      <td>timm_models</td>
      <td>lcnet_050, [2023-08-26 08:28:13 614] torch._dynamo.utils: [ERROR] RMSE (res-fp64): 0.26560 (ref-fp64): 0.03031
        and shape=torch.Size([1 1000])</td>
    </tr>
    <tr>
      <td>mobilenetv2_100</td>
      <td>X</td>
      <td>âˆš</td>
      <td>timm_models</td>
      <td>mobilenetv2_100, [2023-08-26 08:31:40 492] torch._dynamo.utils: [ERROR] RMSE (res-fp64): 0.03747 (ref-fp64):
        0.01834 and shape=torch.Size([1 1000])</td>
    </tr>
    <tr>
      <td>mobilevit_s</td>
      <td>X</td>
      <td>âˆš</td>
      <td>timm_models</td>
      <td>mobilevit_s, [2023-08-26 08:33:13 423] torch._dynamo.utils: [ERROR] RMSE (res-fp64): 6.00970 (ref-fp64):
        2.72817 and shape=torch.Size([1 1000])</td>
    </tr>
    <tr>
      <td>	mobilenetv3_large_100</td>
      <td>X</td>
      <td>âˆš</td>
      <td>timm_models</td>
      <td>mobilenetv3_large_100, [2023-09-02 09:18:52 786] torch._dynamo.utils: [ERROR] RMSE (res-fp64): 0.01714 (ref-fp64): 0.00836 and shape=torch.Size([1 1000])</td>
    </tr>
    <tr>
      <td>LayoutLMForSequenceClassification</td>
      <td>X</td>
      <td>âˆš</td>
      <td>timm_models</td>
      <td>LayoutLMForSequenceClassification, [2023-09-09 07:26:27 469] torch._dynamo.utils: [ERROR] RMSE (res-fp64): 0.00157 (ref-fp64): 0.00046 and shape=torch.Size([1 2])</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>
</table>
<p>SW info</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>91bde86</td>
      <td>e00bd83</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>770d5cf7</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>dc83b38</td>
      <td>66f661d</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>c11d758</td>
      <td>60bea66</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>58366ab</td>
      <td>a6dea86</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>1d231d1</td>
      <td>757c032</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>f228c8b</td>
      <td>/</td>
    </tr>
  </tbody>
</table>

**Comment by XiaobingSuper** [comment]
Those models failed because of conv+bn folding, it is a big gap compared with the eager model, we need to update using a high tolerance if the real data set gets similar accuracy.

**Comment by leslie-fang-intel** [comment]
I have picked one of above models `mobilenetv2_100` with cmd `bash inductor_single_test.sh multiple inference accuracy timm_models mobilenetv2_100 amp first static default 0` on CPX system.
Here is the test log
```
Testing with freezing on.
multi-threads testing....
loading model: 0it [00:00, ?it/s]
cpu  eval  mobilenetv2_100
skipping cudagraphs for unknown reason
pass
dev,name,batch_size,accuracy,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
```

@ESI-SYD May I know is there anything missing? Is this issue platform related?

**Comment by ESI-SYD** [comment]
`mobilenetv2_100` only failed on single core scenery,  pls try `bash inductor_single_test.sh single inference accuracy timm_models mobilenetv2_100 amp first static default 0`

**Comment by leslie-fang-intel** [comment]
Thanks @ESI-SYD. For `mobilenetv2_100`, single core scenery also pass in my local CPX system:
```
(inductor) [root@CPX-4 pytorch]# bash inductor_single_test.sh single inference accuracy timm_models mobilenetv2_100 amp first static default 0
Testing with freezing on.
single-thread testing....
loading model: 0it [00:00, ?it/s]
cpu  eval  mobilenetv2_100
skipping cudagraphs for unknown reason
pass
dev,name,batch_size,accuracy,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
cpu,mobilenetv2_100,1,pass,250,1,0,0
```

**Comment by leslie-fang-intel** [comment]
Update the status:

- 4 of models' failures (`gluon_inception_v3`, `mobilenetv2_100`, `mobilevit_s` and `mobilenetv3_large_100`) will be fixed by https://github.com/pytorch/pytorch/pull/109097
- `LayoutLMForSequenceClassification` and `lcnet_050` need further investigation.

**Comment by leslie-fang-intel** [comment]
- 4 of models' failures (`gluon_inception_v3`, `mobilenetv2_100`, `mobilevit_s` and `mobilenetv3_large_100`) will be fixed by https://github.com/pytorch/pytorch/pull/109097
- `LayoutLMForSequenceClassification` should be false alarm which pass in CPX and with little gap to the pass criteria in SPR. 
- `lcnet_050` tried in model level accuracy testing, the accuracy loss exists after doing conv_bn folding with float32 data type and then convert the weights to bfloat16. May be we need to disable conv_bn folding for this model with AMP.
