### ISSUE TITLE
Can't run Test/Inductor test: test_compiled_optimizers.py

### ISSUE THREAD

**Issue by Idank96** [pytorch/pytorch#108300]
### 🐛 Describe the bug

When I run in terminal: 
`pytest test_compiled_optimizers.py`

I encounter the following error:

```

=============================================== test session starts ================================================
platform win32 -- Python 3.11.1, pytest-7.4.0, pluggy-1.3.0
rootdir: ...\Python Projects\PyTorchContribute\pytorch
configfile: pytest.ini
plugins: anyio-3.7.0, hypothesis-6.82.7, pytorch-0.2.1
collected 0 items / 1 error

====================================================== ERRORS ======================================================
____________________________ ERROR collecting test/inductor/test_compiled_optimizers.py ____________________________
ImportError while importing test module '...\Python Projects\PyTorchContribute\pytorch\test\inductor\test_compiled_optimizers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_compiled_optimizers.py:23: in <module>
    from .test_torchinductor import check_model, check_model_cuda, requires_cuda
...\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\assertion\rewrite.py:178: in exec_module
    exec(co, module.__dict__)
test_torchinductor.py:29: in <module>
    from torch._dynamo.testing import (
E   ImportError: cannot import name 'expectedFailureCodegenDynamic' from 'torch._dynamo.testing' (C:\Users\1idan\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\_dynamo\testing.py)

During handling of the above exception, another exception occurred:
...\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_compiled_optimizers.py:25: in <module>
    from test_torchinductor import check_model, check_model_cuda, requires_cuda
E   ModuleNotFoundError: No module named 'test_torchinductor'
------------------------------------------------- Captured stderr --------------------------------------------------
<class 'ModuleNotFoundError'>: No module named 'test_torchinductor'
============================================= short test summary info ==============================================
ERROR test_compiled_optimizers.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================= 1 error in 6.13s =================================================
```
after add at the beginning of test script:
`sys.path.append(r'...\Python Projects\PyTorchContribute\pytorch\test\inductor')`
I got the following error:
`<class 'ImportError'>: cannot import name 'expectedFailureCodegenDynamic' from 'torch._dynamo.testing' (C:\Users\1idan\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\_dynamo\testing.py)`

I need assistance in resolving this issue as I want to run the tests and contribute to pytorch. Thanks.

### Versions
PyTorch version: 2.1.0.dev20230902
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: ??Microsoft Windows 11 Home
GCC version: (MinGW.org GCC-6.3.0-1) 6.3.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.11.0 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:21) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce MX330
Nvidia driver version: 532.09
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=1391
DeviceID=CPU0
Family=198
L2CacheSize=5120
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=1690
Name=11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==0.981
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.25.2
[pip3] torch==2.1.0.dev20230902
[pip3] torchaudio==2.2.0.dev20230902
[pip3] torchvision==0.16.0.dev20230902
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h6b88ed4_46357
[conda] mkl-service               2.4.0           py311h2bbff1b_1
[conda] mkl_fft                   1.3.6           py311hf62ec03_1
[conda] mkl_random                1.2.2           py311hf62ec03_1
[conda] mpmath                    1.2.1                   py311_0    pytorch-nightly
[conda] numpy                     1.25.2          py311hdab7c0b_0
[conda] numpy-base                1.25.2          py311hd01c5d8_0
[conda] pytorch                   2.1.0.dev20230902 py3.11_cuda11.8_cudnn8_0    pytorch-nightly 
[conda] pytorch-cuda              11.8                 h24eeafa_5    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] requests                  2.28.1                  py311_0    pytorch-nightly
[conda] torchaudio                2.2.0.dev20230902          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230902          pypi_0    pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by Idank96** [comment]
After re-installing everything, I managed to run the tests. However, the tests were skipped due to a false if statement:

```
if __name__ == "__main__":
    from torch._dynamo.test_case import run_tests

    if (HAS_CPU or HAS_CUDA) and not TEST_WITH_ROCM:
        run_tests(needs="filelock")
```
Both HAS_CPU and HAS_CUDA are False. What could be the reason for this?



I also attempted to run the tests manually:

```
if __name__ == "__main__":
    from torch._dynamo.test_case import run_tests

    # if (HAS_CPU or HAS_CUDA) and not TEST_WITH_ROCM:
    #     run_tests(needs="filelock")

    CompiledOptimizerTests()
```

However, none of the test lines executed because @requires_cuda seems to be causing issues. For example:

`test_adamw = make_test(AdamW, lr=0.01)`

The make_test function includes the @requires_cuda() decorator:

```
def make_test(optim_cls, closure=None, kernel_count=2, **kwargs):
    @requires_cuda()
    def test_fn(self):
        torch._dynamo.reset()
        torch._inductor.metrics.reset()
        input = torch.ones([10, 10], device="cuda:0")
        model_eager = torch.nn.Sequential(
            *[torch.nn.Linear(10, 10, device="cuda:0") for _ in range(2)]
        )
        model_eager(input).sum().backward()

        input = torch.ones([10, 10], device="cuda:0")
        model_compiled = deepcopy(model_eager)
        model_compiled(input).sum().backward()

        opt_eager = optim_cls(model_eager.parameters(), **kwargs)
        opt_compiled = optim_cls(model_compiled.parameters(), **kwargs)
        compiled_step = compile_opt(opt_compiled, closure=closure)

        with torch.set_grad_enabled(False):
            compiled_step()
            opt_eager.step()

        self.assertEqual(
            list(model_eager.parameters()), list(model_compiled.parameters())
        )

        if self.check_kernel_count:
            # currently, we compile the step and the rest of the computation
            # separately because the step is a single element tensor
            # hence, the usual kernel count is 2
            self.assertEqual(
                torch._inductor.metrics.generated_kernel_count, kernel_count
            )

    return test_fn
```
This may be affecting the test execution. Could you please provide more information or context on why @requires_cuda() is used in the tests? or how to make it pass?

**Comment by Idank96** [comment]
By the way, running python setup.py develop or python setup.py install is a must to run the tests?

**Comment by ezyang** [comment]
We don't actually run inductor tests on Windows at the moment, I don't really expect it to work

**Comment by Idank96** [comment]
> We don't actually run inductor tests on Windows at the moment, I don't really expect it to work

Is it possible to run it with WSL 2? What are the system requirements for running inductor tests and contributing?

Thanks.

**Comment by ezyang** [comment]
Maybe? In that case, try running from root directory of pytorch rather than test subdir

**Comment by Idank96** [comment]
I’m not sure what you mean by running it from the root directory. Could you please explain it to me? I would really appreciate it. Thanks.

**Comment by ezyang** [comment]
I don't know, because I have never tried PyTorch in WSL. Are you able to run basic CUDA programs with your copy of PyTorch? Do you have a working system compiler?

**Comment by Idank96** [comment]
when I run the following code:
```
import torch
print(torch.cuda.is_available())
```
I get False.
When running:
`(pytorch-deps) idan@DESKTOP-*******:~/pytorch$ nvcc --version` 
I get:
`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
`

**Comment by Idank96** [comment]
When running `clang --version`  (compiler)
I get:
```
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```
when I run the following code:
```
import torch
print(torch.cuda.is_available())
```
I get `False`.

When running:
`(pytorch-deps) idan@DESKTOP-*******:~/pytorch$ nvcc --version` 

I get:

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
`

I've installed `cudatoolkit=11.5` in the same environment.

**Comment by alinpahontu2912** [comment]
Hey @Idank96, what is the status of your issue ? From what I now dynamo/triton is not yet supported on windows, so running these tests might not be possible. Have you figured out why the pytorch build fails to recognize cuda in wsl, to me it looks like a version mismatch between the toolkits?

**Comment by Idank96** [comment]
No, but you could close the issue anyway
