### ISSUE TITLE
[Caffe2] CAFFE2-ONNX Parsing error for FASTERRCNN-RESNET50

### ISSUE THREAD

**Issue by ram1897** [pytorch/pytorch#10849]
## Issue description
RuntimeError: [enforce fail at generate_proposals_op.cc:247] im_info_tensor.dims() == (vector<TIndex>{num_images, 3}). 0 vs 1 3Error from operator: 

Provide a short description.
I am trying to convert a Faster RCNN model from Caffe2 to ONNX (Initially the model was trained in Detectron, then converted it's pkl file to caffe2's '.pb' file)

## System Info
Ubuntu 16.04
8 GB RAM
Caffe2 GPU version built from GIT repository.
CUDA -8
CUDNN 6
Python 2.7

**Comment by RainHxj** [comment]
have the same error

**Comment by houseroad** [comment]
Because some ops are not in the ONNX spec yet. One pr is in progress https://github.com/onnx/onnx/pull/1010
