### ISSUE TITLE
```RuntimeError: derivative for aten::linear_backward is not implemented``` with apple silicon

### ISSUE THREAD

**Issue by moonjunyyy** [pytorch/pytorch#108409]
### 🐛 Describe the bug

```RuntimeError: derivative for aten::linear_backward is not implemented``` 
An error occurs with this code on Apple silicon.
I think some of the features are not properly implemented on Metal.

```python
import torch
import torch.nn as nn

x = torch.randn(2, 3, requires_grad=True).to('mps:0')
y = torch.randn(2, 3, requires_grad=True).to('mps:0')
t = torch.randn(2, 3, requires_grad=True).to('mps:0')

fc1 = torch.nn.Linear(3, 3).to('mps:0')
fc2 = torch.nn.Linear(3, 3).to('mps:0')
fc3 = torch.nn.Linear(3, 3).to('mps:0')
model = nn.Sequential(fc1, fc2, fc3)

o = model(x)
o = ((t-o)**2).sum()
g = torch.autograd.grad(o, model.parameters(), create_graph=True)

o2 = model(y)
o2 = ((t-o2)**2).sum()
g2 = torch.autograd.grad(o2, model.parameters(), create_graph=True)

loss = 0
for i in range(len(g)):
    loss += ((g[i] - g2[i]) ** 2).sum()
loss.backward()
```

### Versions

Stable (2.0.1), downloaded with conda

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @kulinseth @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by soulitzer** [comment]
Looks like you are using an older version of PyTorch. Support for double backward for linear on MPS was recently added in https://github.com/pytorch/pytorch/pull/97151.

**Comment by moonjunyyy** [comment]
@soulitzer As I mentioned in the main script, I have used the 2.0.1 version and I downloaded it in august. The #97151 is merged on the march. I think, there is still a problem that has not solved, especially on apple sillicon.

**Comment by moonjunyyy** [comment]
@soulitzer Did you mean nightly version?

**Comment by lezcano** [comment]
Yes, in the nightly version.
