### ISSUE TITLE
The document around dynamo -> custom-backends -> Composable Backends is out of date

### ISSUE THREAD

**Issue by nxdong** [pytorch/pytorch#108405]
### 📚 The doc issue

online doc: https://pytorch.org/docs/stable/dynamo/custom-backends.html#composable-backends

content is out of date. not work in pytorch 2.0.1

**Comment by msaroufim** [comment]
This page is really out of date, you should be checking https://pytorch.org/docs/main/torch.compiler.html if you have concrete feedback please tag @svekars
