### ISSUE TITLE
update for M1 and M2 chip apple silicon

### ISSUE THREAD

**Issue by alex5956** [pytorch/pytorch#108403]
### 🚀 The feature, motivation and pitch

hello could you update the module for M1 and M2 chip apple silicon ?not only for nvidia and cda ?
Cordially

**Comment by soulitzer** [comment]
PyTorch already does support M1 chips - see https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/. If you have a specific feature that doesn't work on M1/M2 feel free to reopen.

**Comment by alex5956** [comment]
i've to select cpu platform ?
