### ISSUE TITLE
CUDA Tensor __rsub__ breaks when device is not 0

### ISSUE THREAD

**Issue by davidmascharka** [pytorch/pytorch#10850]
## Issue description

If a tensor resides on a GPU that is not 0, then the `__rsub__` function raises.

## Code example

``` python
import torch

a = torch.tensor([1]).to('cuda:3') # or any GPU that is not 0

print(a - 1) # __sub__ is fine
print(1 - a) # __rsub__ breaks
# __radd__, __rmul__, __rpow__, __rfloordiv__, and __rtruediv__ all work
```

Output:

``` python
tensor([-1], device='cuda:3')

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-4bb4bfe9af47> in <module>()
      1 print(a - 1)
----> 2 print(1 - a)

~/anaconda3/lib/python3.6/site-packages/torch/tensor.py in __repr__(self)
     55         # characters to replace unicode characters with.
     56         if sys.version_info > (3,):
---> 57             return torch._tensor_str._str(self)
     58         else:
     59             if hasattr(sys.stdout, 'encoding'):

~/anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py in _str(self)
    254             suffix += ', dtype=' + str(self.dtype)
    255 
--> 256         formatter = _Formatter(get_summarized_data(self) if summarize else self)
    257         tensor_str = _tensor_str(self, indent, formatter, summarize)
    258 

~/anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py in __init__(self, tensor)
     74 
     75         if not self.floating_dtype:
---> 76             copy = torch.empty(tensor.size(), dtype=torch.long).copy_(tensor).view(tensor.nelement())
     77             for value in copy.tolist():
     78                 value_str = '{}'.format(value)

RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/generic/THCTensorCopy.cpp:68
```

## System Info
PyTorch version: 0.5.0a0+6993e4a
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 390.67
cuDNN version: libcudnn.so.7.0.3

Reproduced with PyTorch 0.5.0a0+e9ad743 as well.

**Comment by rsokl** [comment]
I've reproduced this bug on PyTorch 0.5.0a0+e9ad743

**Comment by rsokl** [comment]
Any progress on this?

**Comment by yf225** [comment]
We found that `a = 1 - torch.tensor([1]).to('cuda:1')` should put `a` in `cuda:1`, but the result of `a.device` is `cuda:0` which is incorrect, hence the illegal memory access error when trying to access `a`'s memory (e.g. when printing). I will investigate more into this next week.
