### ISSUE TITLE
Exportability problems with `at::RecordFunction` due to ABI mismatch in layout of struct defined in header file

### ISSUE THREAD

**Issue by Jokeren** [pytorch/pytorch#108566]
### 🚀 The feature, motivation and pitch

We are attempting to enable third-party performance tools to collect fine-grained operation information about PyTorch by registering callbacks using `at::RecordFunction`:

https://github.com/pytorch/pytorch/blob/efc7c366f4fbccf649454726a96df291c8a9df43/aten/src/ATen/record_function.h#L126

I've found that although the struct is intended for external users, some of its public methods, such as `forwardThreadId` and `seqNr`, don't return accurate results. This issue might arise from some compiler/linker optimizations. Interestingly, the problem only occurs when PyTorch is installed via `pip install`; everything works as expected when we build it locally.

Minimum Reproducer:

https://gist.github.com/Jokeren/fc756ad6b3b22c6dfcec32d5460a1e03

The `fwd_thread_id` is always `18446744073709551615`, although it should be 0 or 1.

Quote reply from @davidberard98:

> It looks like there is some sort of ABI compatibility difference. My local builds show the `sizeof(RecordFunction)` as 288 bytes, whereas it seems to be 264 bytes for the nightly builds, based on a cursory examination of the raw contents of the RecordFunction object.

### Alternatives

1. We could potentially define some essential getter functions in `.cpp` files to ensure that optimizations like inlining do not interfere. However, I am unable to verify whether this approach is effective or if it leads to performance degradation.
  
2. Alternatively, we might be able to export those functions using `extern "C"`.
  
3. Otherwise, could there be specific compiler settings for the pip distribution that are causing the issue? Everything works fine when we build locally from source.

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98 @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by Jokeren** [comment]
@louisfeng @ezyang @Chillee, this issue might be related to you? My apologies if I've tagged the wrong individuals

**Comment by louisfeng** [comment]
Thanks for reporting this. In our internal builds, we don't observe this problem in execution trace data. If this is a build/release issue, I'm surprised this isn't caught by the CI... Also cc: @aaronenyeshi

**Comment by davidberard98** [comment]
@Jokeren I did some experimentation - on my side, building with `-D_GLIBCXX_USE_CXX11_ABI=0` fixed this. Can you see if this works for you?

**Comment by Jokeren** [comment]
Oh, I see. I'll try it out today. Thanks

Does it mean the pytorch pip distribution was built with `_GLIBCXX_USE_CXX11_ABI=0`?

**Comment by Jokeren** [comment]
@davidberard98 I can confirm that the compilation flag works for me. Thanks again for your help!
