### ISSUE TITLE
GH API issues are preventing multiple ci jobs to start.

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#108524]
## Current Status
Recovered

## Error looks like
```
2023-09-04T13:50:49.2687734Z Download action repository 'pytorch/test-infra@main' (SHA:b7c64078de18cc53be1628e0756896165482c35b)
2023-09-04T13:50:49.5711762Z Download action repository 'pytorch/pytorch@main' (SHA:7e878c9d10e134deb61d2104243e14ef1f3ac291)
2023-09-04T13:52:29.5790374Z ##[warning]Failed to download action 'https://api.github.com/repos/pytorch/pytorch/tarball/7e878c9d10e134deb61d2104243e14ef1f3ac291'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
2023-09-04T13:52:29.5799344Z ##[warning]Back off 15.866 seconds before retry.
2023-09-04T13:54:25.4572998Z ##[warning]Failed to download action 'https://api.github.com/repos/pytorch/pytorch/tarball/7e878c9d10e134deb61d2104243e14ef1f3ac291'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
2023-09-04T13:54:25.4574279Z ##[warning]Back off 17.89 seconds before retry.
2023-09-04T13:56:23.3514907Z ##[error]The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

## Incident timeline (all times pacific)
04/09 18:50 CEST - Incident detected
05/09 04:28 UTC - GHA incident closed at github side
05/09 05:00 UTC - We experienced recover on our CI jobs, starting to gatekeep PRs
05/09 05:30 UTC - Removing merge blocking

## User impact
Most CI jobs are failing with timeout reaching GH API

## Root cause
Investigating if related to GH API incident: https://www.githubstatus.com/incidents/76xp2jd3px64

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by jeanschmidt** [comment]
It looks the issue is on GH side, for now I'll keep this blocked until we observe a improved API response.

**Comment by jeanschmidt** [comment]
Microsoft/Github team have been notified about the issue, waiting for the next steps.

**Comment by jeanschmidt** [comment]
Re-run the workflow is enabling debug seems to suppress the error, or at least make it very unlikely to occur

**Comment by jeanschmidt** [comment]
Reproduced the issue with debug flag: https://github.com/pytorch/pytorch/actions/runs/6077055829/job/16486546491

**Comment by jeanschmidt** [comment]
From now on, GH team have been contacted, all possible details from the issue have been shared with the team. Waiting from their side now.

Updates will follow in 1h

**Comment by jeanschmidt** [comment]
Incident on GH: https://www.githubstatus.com/incidents/tqrmcdmghldw

**Comment by ezyang** [comment]
looks resolved, can we close the SEV?

**Comment by huydhn** [comment]
Lifting the merge blocking status and see how it goes

**Comment by jeanschmidt** [comment]
I just got confirmation from GH team that it should be safe to unblock merges, I am closing the issue and will re-enable in case it is necessary.

**Comment by jeanschmidt** [comment]
Performance is still degraded, I can see failures, so will keep the issue open for now.

**Comment by DanilBaibak** [comment]
Performance degradation increased. I set the merge blocking status.

**Comment by jeanschmidt** [comment]
New GH issue: https://www.githubstatus.com/incidents/frdfpnnt85s8

**Comment by ezyang** [comment]
GH reports issue is cleared

**Comment by jeanschmidt** [comment]
@ezyang I was gatekeeping merging the open issues in order to be sure that the issue wont happen again, as GH marked the issue as resolved multiple times while we still experienced the problems.

please, communicate before taking any actions.

**Comment by jeanschmidt** [comment]
At this moment, all PRs that have green jobs and tried to merge but where blocked by the restriction are forced merged.

I'll evaluate any failures in those jobs, in case it is possible to consider the services recovered I am removing the blocking.

This evaluation will happen at 17:30 CEST or 09:30 Palo Alto time

**Comment by jeanschmidt** [comment]
There are sufficient signals to consider the issue mitigated, I am lifting the merge blocking but will keep the issue open for now to allow users to be aware of the potential issues.
