### ISSUE TITLE
[Quant][PT2E] Quantization Metadata copy causes quantization flow extreme slow 

### ISSUE THREAD

**Issue by leslie-fang-intel** [pytorch/pytorch#108557]
### 🐛 Describe the bug

After commit: ffc0c46092efef1f3b51becc8f5770abcec5c23a, the quantization flow for `densenet121` is extreme slower.
Here is the script to reproduce this issue:  https://gist.github.com/leslie-fang-intel/9cd828623f567a3afbf41564d3546398

- Before this commit, the quantization flow costs `21.5` second to finish the whole quantization flow with above script.
- After this commit, the quantization flow didn't finish in half hour and I have to kill the process. After some triage, looks like quantization flow is recursively visiting https://github.com/pytorch/pytorch/blob/3d2938b1fcfa58bc17abb4014cd4f547c50d0a6f/torch/ao/quantization/pt2e/utils.py#L37.

### Versions
```
Collecting environment information...
PyTorch version: 2.1.0a0+gitb758fb9
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.17

Python version: 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.19.5-1.el7.elrepo.x86_64-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    1
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel Genuine CPU
Stepping:              10
CPU MHz:               2900.461
CPU max MHz:           2900.0000
CPU min MHz:           1200.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27
NUMA node1 CPU(s):     28-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.1.0a0+gitffc0c46
[pip3] torchvision==0.16.0a0+08c9938
[conda] mkl                       2023.0.0            intel_25398    intel
[conda] mkl-include               2023.0.0                  <pip>
[conda] mkl-include               2023.0.0            intel_25398    intel
[conda] mkl-service               2.4.0           py38h3605609_14    intel
[conda] mkl-static                2023.0.0                  <pip>
[conda] mkl_fft                   1.3.1           py38hcab1719_22    intel
[conda] mkl_random                1.2.2           py38hbf47bc3_22    intel
[conda] mkl_umath                 0.1.1           py38hf66a691_32    intel
[conda] numpy                     1.24.3                    <pip>
[conda] numpy                     1.22.3           py38hf0956d0_5    intel
[conda] numpy-base                1.22.3           py38h45c9ace_5    intel

```

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen

**Comment by leslie-fang-intel** [comment]
Hi @kimishpatel @jerryzh168, could you help to take a look of this issue?

**Comment by kimishpatel** [comment]
> Hi @kimishpatel, could you help to take a look of this issue? Not sure if it's a dead loop or due to the code logic is not efficient. cc @jerryzh168

Let me put up a fix. Jerry, actually highlighted this, but I didnt think it will cause such a problem.

**Comment by vkuzo** [comment]
would be nice to add a way to automatically detect these things, a job with a timing of the quantization APIs on a real model should probably do it

**Comment by kimishpatel** [comment]
https://github.com/pytorch/pytorch/pull/108572

**Comment by jerryzh168** [comment]
> would be nice to add a way to automatically detect these things, a job with a timing of the quantization APIs on a real model should probably do it

this could be detected with inception v4 I think, I saw it in https://github.com/pytorch/pytorch/pull/108382 it doesn't finish..

**Comment by kimishpatel** [comment]
> > would be nice to add a way to automatically detect these things, a job with a timing of the quantization APIs on a real model should probably do it
> 
> this could be detected with inception v4 I think, I saw it in #108382 it doesn't finish..


Was that quant or just executorch running?

**Comment by jerryzh168** [comment]
> > > would be nice to add a way to automatically detect these things, a job with a timing of the quantization APIs on a real model should probably do it
> > 
> > 
> > this could be detected with inception v4 I think, I saw it in #108382 it doesn't finish..
> 
> Was that quant or just executorch running?

this one: buck2 run executorch/examples/quantization:example -- -m=ic4

when I interrupt the run I saw it was stuck at find_q_dq_uses or something, so I think this should be related

**Comment by kimishpatel** [comment]
> > > > would be nice to add a way to automatically detect these things, a job with a timing of the quantization APIs on a real model should probably do it
> > > 
> > > 
> > > this could be detected with inception v4 I think, I saw it in #108382 it doesn't finish..
> > 
> > 
> > Was that quant or just executorch running?
> 
> this one: buck2 run executorch/examples/quantization:example -- -m=ic4
> 
> when I interrupt the run I saw it was stuck at find_q_dq_uses or something, so I think this should be related

makes sense

**Comment by leslie-fang-intel** [comment]
Thanks @kimishpatel. Issue has been fixed in https://github.com/pytorch/pytorch/pull/108572.
