### ISSUE TITLE
got error "ninja: error: loading 'build/build.global.ninja': No such file or directory"

### ISSUE THREAD

**Issue by jinserk** [pytorch/pytorch#10857]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
```
Building from source, an error reported related to ninja and stopped the building process
running build_ext
-- Building with NumPy bindings
-- Detected cuDNN at /usr/local/cudnn/lib64/libcudnn.so.7, /usr/local/cudnn/include
-- Not using MIOpen
-- Detected CUDA at /usr/local/cuda
-- Detected MKLDNN at /usr/local/lib/libmkldnn.so, /usr/local/include
-- Using system provided NCCL library at /usr/local/nccl_2.2.13-1+cuda_9.2/lib/libnccl.so.2.2.13, /usr/local/nccl/include
-- Building with distributed package 
ninja: error: loading 'build/build.global.ninja': No such file or directory
Command '['/home/jbaik/.pyenv/versions/3.7.0/lib/python3.7/site-packages/ninja/data/bin/ninja', '-f', 'build/build.global.ninja']' returned non-zero exit status 1.
```
## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): python setup.py build
- OS: CentOS7
- PyTorch version: master branch (ca567862)
- Python version: 3.7.0
- CUDA/cuDNN version: 9.2/7.2.1
- GPU models and configuration: NVIDIA GTX1070
- GCC version (if compiling from source): 4.8.5
- CMake version: 3.12.0
- Versions of any other relevant libraries:

**Comment by zou3519** [comment]
Could you try to clean `python setup.py clean` and rebuild?

**Comment by jinserk** [comment]
Every time I cleaned and build, but it shows the same result.

**Comment by zou3519** [comment]
Try uninstalling ninja and building without reinstalling it?

**Comment by jinserk** [comment]
Oh, it works! Don't we use ninja to build pytorch any more? Thank you so much @zou3519 !
