### ISSUE TITLE
torch.lgamma documentation error

### ISSUE THREAD

**Issue by igm503** [pytorch/pytorch#108527]
### 📚 The doc issue

The documentation for the torch.lgamma function at https://pytorch.org/docs/stable/generated/torch.lgamma.html is inconsistent (and incorrect).

While the text description *correctly* says that torch.lgamma is the natural log of the absolute value of the gamma function of the input:

torch.lgamma(x) = ln(abs(gamma(x)))

the math expression *incorrectly* suggests that torch.lgamma is the natural log of the gamma function of the absolute value of the input:

torch.lgamma(x) = ln(gamma(abs(x)))

### Suggest a potential alternative/fix

Happy to fix by but I can't find the docstring for torch.lgamma that's used to produce the web docs. 

cc @svekars @carljparker

**Comment by ezyang** [comment]
it's in torch/_torch_docs.py
