### ISSUE TITLE
Figure out #108256 for branch cut

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#108583]
In https://github.com/pytorch/pytorch/pull/108256 we modified the pytree API. Now, the API on the 2.1.0 branch and on main diverges. We should figure out which version of the API we actually want going forward and make sure that it is the same on the release branch and on main.

cc @angelayi

**Comment by angelayi** [comment]
The current pytree API on main is:
```
def _register_pytree_node(
    typ: Any,
    flatten_fn: FlattenFunc,
    unflatten_fn: UnflattenFunc,
    to_str_fn: Optional[ToStrFunc] = None,
    maybe_from_str_fn: Optional[MaybeFromStrFunc] = None,
    *,
    to_dumpable_context: Optional[ToDumpableContextFn] = None,
    from_dumpable_context: Optional[FromDumpableContextFn] = None,
) -> None:
```

With `to_str_fn` and `maybe_from_str_fn` not being used and marked as ["deprecated"](https://github.com/angelayi/pytorch/blob/9b08f4a01d873e7f4668e6caba2a8eda8a08cddb/torch/utils/_pytree.py#L101-L104). 

Ideally we want it to be the following, which is also what we have on the 2.1 branch:
```
def _register_pytree_node(
    typ: Any,
    flatten_fn: FlattenFunc,
    unflatten_fn: UnflattenFunc,
    *,
    to_dumpable_context: Optional[ToDumpableContextFn] = None,
    from_dumpable_context: Optional[FromDumpableContextFn] = None,
) -> None:
```

So in that case, is it ok to not do anything?

**Comment by zou3519** [comment]
Thanks for clarifying. Yes, we're good. In 2.1 we'll have 3 positional args, in 2.2 (assuming we don't change the API) we'll have 5 positional args (with two of them being optional). Additional optional positional args is backwards compatible, it's not really FC but we don't maintain FC in OSS.

NB: I don't think we're ever going to actually be able to delete to_str_fn/maybe_from_str_fn for BC issues. Best thing to hope for is that when we do a public pytree release we make a new public `register_pytree_node` function that has everything cledaned up.
