### ISSUE TITLE
TorchInductor workers use "fork" which doesn't work in a multithreaded environment

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#108586]
### 🐛 Describe the bug

TorchInductor workers use "fork" as the default method for spawning processes: https://github.com/pytorch/pytorch/blob/ff38c0e2f9cae35378553c38ccf7188007fed938/torch/_inductor/codecache.py#L1349

"fork" in general is [broken](https://www.microsoft.com/en-us/research/uploads/prod/2019/04/fork-hotos19.pdf) and should not be used in modern systems where multithreading is used commonly. Even [python](https://discuss.python.org/t/switching-default-multiprocessing-context-to-spawn-on-posix-as-well/21868) plans to switch to using "spawn" as the default multiprocessing spawn method.

Creating this issue to follow up from the discussion [here](https://github.com/pytorch/pytorch/pull/87411#issuecomment-1699795308). The usage of "fork" creates non-deterministic situations where application code deadlocks or crashes in a multi-threaded environment. We should switch the default here to be "spawn" or at least give users an option to switch to using "spawn" instead.

This means we need to set `num_workers=0` which slows down compilation times significantly. First compile usually takes about 20mins with `num_workers=16`. However, with `num_workers=0` this goes up to 90mins.

### Versions

main branch

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by ezyang** [comment]
cc @zdevito

**Comment by ezyang** [comment]
In the discussion thread eellison said he was working on this

**Comment by wconstab** [comment]
I assume this is the same issue: https://github.com/pytorch/pytorch/blob/main/test/distributed/test_inductor_collectives.py#L82

Would be good to update the test to remove the bg threads=1 once we (think we) have a fix

**Comment by pritamdamania87** [comment]
@ezyang @wconstab @eellison I have a simple proposal in https://github.com/pytorch/pytorch/pull/108850 that would work for our use case.

**Comment by eellison** [comment]
Since triton holds the gil on compilation, I wouldn't expect just forking to be any different than setting TORCHINDUCTOR_COMPILE_THREADS to 1. 

I have a PR here https://github.com/pytorch/pytorch/pull/108610 and corresponding (WIP) pr here for triton to release gil here: https://github.com/openai/triton/compare/main...eellison:triton:multi_thread?expand=1. 

perf run [here](https://hud.pytorch.org/benchmark/torchbench/inductor_no_cudagraphs?startTime=Fri,%2001%20Sep%202023%2015:37:03%20GMT&stopTime=Fri,%2008%20Sep%202023%2015:37:03%20GMT&granularity=hour&mode=training&dtype=amp&lBranch=gh/eellison/527/head&lCommit=57d8219c00d1c0c37a8f78d60e62600dfbc787d2&rBranch=main&rCommit=e787708ad7650bf017f9ed4517619515fc04d257). 

It's not all the way there yet.

**Comment by pritamdamania87** [comment]
> Since triton holds the gil on compilation, I wouldn't expect just forking to be any different than setting TORCHINDUCTOR_COMPILE_THREADS to 1.

So the problem is not in triton. But we use grpc in our code which is mostly in C/C++ with python bindings. GRPC uses a lot of threads under the hood and as a result a "fork" anywhere in the application causes those threads to deadlock/segfault. There is some discussion of that here: https://github.com/grpc/grpc/blob/master/doc/fork_support.md. However, the recommendations on that page didn't work for us: https://github.com/grpc/grpc/issues/32992.

**Comment by pritamdamania87** [comment]
Closing this out since we can use "spawn" with: https://github.com/pytorch/pytorch/pull/108850
