### ISSUE TITLE
torch.compile operation benchmark result is poor

### ISSUE THREAD

**Issue by zwshan** [pytorch/pytorch#108636]
### 🐛 Describe the bug

I am currently testing the optimization features of torchdynamo and comparing them with the optimization results of TVM. I have already completed the optimization evaluation of various operators in TVM and am now conducting evaluations for dynamo and openxla. However, my operator optimization evaluation results show that torch 2.0 is performing negative optimization. I have tested the following operators as shown in the figure.
<img width="336" alt="image" src="https://github.com/pytorch/pytorch/assets/62176674/98b040a3-6261-4d7e-9198-1f2548139ab3">

### Error logs

<img width="1307" alt="image" src="https://github.com/pytorch/pytorch/assets/62176674/7b9df29b-c788-427d-8631-bf7ecdd5f427">

### Minified repro

main.py
```python
import numpy
import time
from torchDynamo import *
# ------------------------------------------------------------------------------
# User Configurable Variables
# ------------------------------------------------------------------------------
dtype = "float32"

# ------------------------------------------------------------------------------
# Helper Function
# ------------------------------------------------------------------------------

def evaluator(s, inputs, num):
  all_time = []
  for i in range(num):
      torch.cuda.synchronize()
      start = time.time()
      result = s(inputs)
      torch.cuda.synchronize()
      end = time.time()
      elapsed_time = end - start
      all_time.append(elapsed_time)

  # 计算时间的平均值
  average_time = sum(all_time) / num

  return average_time


def evaluate_operation(s, inputs, optimization, log):
  """Evaluate operation correctness and print the performance information.
  Args:
    s: The schedule to be built.
    vars: The argument lists to the function.
    target: The target and option of the compilation.
    inputs: The input tensors.
    standard: The standard result for correctness evaluation.
    optimization: The name of the optimization.
    log: The log list.
  """
  mean_time = evaluator(s, inputs, 1)
  log.append((optimization, mean_time))


def report_performance(log):
  """Convert the log into a performance table.
  Args:
    log: The log list.
  """
  baseline = log[-1][1]
  header = "Benchmark".ljust(20) + "\t" + "Time".rjust(
      10) + "\t" + "SpeedUp".rjust(10)
  split_line = "-" * 50
  print(split_line)
  print(header)
  print(split_line)
  for result in log:
    formatted_time = "{:.2f}".format(result[1])
    formatted_performance = "{:.2f}".format(baseline / result[1])
    print("\033[32m%s\033[0m\t\033[33m%s\033[0m\t\033[34m%s\033[0m" %
          (result[0].ljust(20), str(formatted_time + " ms").rjust(10),
           str(formatted_performance).rjust(10)))


def main():
  # ----------------------------------------------------------------------------
  # Initialization and Baseline
  # ----------------------------------------------------------------------------
  # Initialize the log list.
  log = []

  # Generate random tensor for testing.
  size = (512, 64, 3)
  c, n, k, p, s = size[0], size[0], size[1], size[2], 1
  oc, ic, n, k, p, s = size[0], size[0], size[1], size[2], 1, 1
  data,weight, out = get_conv_data_torch(c, n, k, p, s)


  # ----------------------------------------------------------------------------
  # Register Benchmarks and Dump Report
  # ----------------------------------------------------------------------------
  # Register default schedule.

  s_1 = conv_torch(data, out, k, p, s)
  evaluate_operation(s_1,
                     inputs=data,
                     optimization="torch_conv_default",
                     log=log)


  s_2 = conv_compiled(data, out, k, p, s)
  evaluate_operation(s_2,
                     inputs=data,
                     optimization="torch_conv_dynamo",
                     log=log)

 

  report_performance(log)


if __name__ == "__main__":
  main()

```
torchDynamo.py
```python
import torch
import torch.nn as nn
import numpy as np


def conv_out_size(n, k, p, s):
    """Compute the output size by given input size n (width or height),
    kernel size k, padding p, and stride s
    Return output size (width or height)
    """
    return (n - k + 2 * p)//s + 1



def get_conv_data(oc, ic, n, k, p=0, s=1, constructor=None):
    """Return random 3-D data tensor, 3-D kernel tenor and empty 3-D output
    tensor with the shapes specified by input arguments.

    oc, ic : output and input channels
    n : input width and height
    k : kernel width and height
    p : padding size, default 0
    s : stride, default 1
    constructor : user-defined tensor constructor
    """
    np.random.seed(0)
    data = np.random.normal(size=(ic, n, n)).astype('float32')
    weight = np.random.normal(size=(oc, ic, k, k)).astype('float32')
    on = conv_out_size(n, k, p, s)
    out = np.empty((oc, on, on), dtype='float32')
    if constructor:
        data, weight, out = (constructor(x) for x in [data, weight, out])
    return data, weight, out


def conv_torch(data, out, k, p, s):
    f = nn.Conv2d(data.shape[1], out.shape[1], kernel_size=k, stride=s, padding=p)
    return f

def conv_compiled(data, out, k, p, s):
    f = nn.Conv2d(data.shape[1], out.shape[1], kernel_size=k, stride=s, padding=p)
    f_s = torch.compile(f)
    return f_s

def get_conv_data_torch(c, n, k, p, s):
    data, weight, out = get_conv_data(c, c, n, k, p, s,lambda x: torch.from_numpy(x))
    data = data.unsqueeze(0)  # 在第0个维度前添加一个新维度
    out = out.unsqueeze(0)
    return data, weight, out
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+4136153
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.10.0-23-amd64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100-PCIE-40GB
GPU 4: NVIDIA A100-PCIE-40GB
GPU 5: NVIDIA A100-PCIE-40GB

Nvidia driver version: 470.182.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          256
On-line CPU(s) list:             0-255
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7742 64-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     3414.5500
CPU min MHz:                     1500.0000
BogoMIPS:                        4500.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall sev_es fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
Virtualization:                  AMD-V
L1d cache:                       4 MiB (128 instances)
L1i cache:                       4 MiB (128 instances)
L2 cache:                        64 MiB (128 instances)
L3 cache:                        512 MiB (32 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-63,128-191
NUMA node1 CPU(s):               64-127,192-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.22.2
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.1.0a0+4136153
[pip3] torch-tensorrt==1.5.0.dev0
[pip3] torchdata==0.7.0a0
[pip3] torchtext==0.16.0a0
[pip3] torchvision==0.16.0a0
[pip3] triton==2.1.0
[conda] Could not collect

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by ezyang** [comment]
We don't codegen convolution, so this is not surprising? It will only be as good as cuDNN, perhaps worse if our fixed overheads are worse.

**Comment by peterbell10** [comment]
Note that the compilation time is being included in the benchmark. If I add a warmup call before the timing loop it goes to a slowdown of 1.17x on my machine.  Also the `torch.cuda.synchronize` calls are a bit misleading, this is actually benchmarking CPU inductor.

**Comment by XiaobingSuper** [comment]
As @peterbell10 said, we may need a warmup step to exclude the compile time. @zwshan,  you can set ```export TORCHINDUCTOR_FREEZING=1``` to further improve the performance.

**Comment by zwshan** [comment]
> Note that the compilation time is being included in the benchmark. If I add a warmup call before the timing loop it goes to a slowdown of 1.17x on my machine. Also the `torch.cuda.synchronize` calls are a bit misleading, this is actually benchmarking CPU inductor.

I don't know why my code can't run on the CPU, even when I move the tensor to the CPU first. I can assure you that my results are indeed running on the GPU because I can see a CUDA kernel through nvidia-smi.

**Comment by zwshan** [comment]
> We don't codegen convolution, so this is not surprising? It will only be as good as cuDNN, perhaps worse if our fixed overheads are worse.


I'm sorry I only saw your replies today. It's not just the convolution; all the operators I tested are performing poorly. The list of operators is in the diagram I provided.

**Comment by zwshan** [comment]
> Note that the compilation time is being included in the benchmark. If I add a warmup call before the timing loop it goes to a slowdown of 1.17x on my machine. Also the `torch.cuda.synchronize` calls are a bit misleading, this is actually benchmarking CPU inductor.

thank you! you are right! we need warm up

**Comment by zhxchen17** [comment]
Hi @zwshan thanks for raising the issue. I'm cleaning up the old issues and wondering this issues has been resolved on your side? If that's the case we may close this unless we have more specific ask here.
