### ISSUE TITLE
Recover exact transforms from RandomCrop et al.

### ISSUE THREAD

**Issue by mattphillipskitware** [pytorch/pytorch#10860]
So in at least some of the transforms.py functions (e.g. RandomCrop) the random numbers used to create the transformation are not stored.  Thus it is impossible to recover what values were used for a given (augmented) image.  This is something it would be very useful to have for the purposes of debugging/diagnostics, for example when you have a complex transform and want to ask 'which transform is my model having a hard time with'.

PyTorch devs, would you be interested in having this functionality added to the code base?  What constraints would it need to satisfy?

**Comment by H-Huang** [comment]
This issue was missed, but for the record this can be accomplished with [torch.seed](https://pytorch.org/docs/stable/generated/torch.seed.html)
