### ISSUE TITLE
[inductor] Triton matmul templates should use reduced_precision_reduction flags

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#108621]
In eager mode [we have flags](https://pytorch.org/docs/stable/notes/cuda.html#reduced-precision-reduction-in-fp16-gemms) for using fp16 accumulators in matmuls.

Currently, our Triton matmul templates ignore this flag and always accumulate in float32.  This will make them slower, so we may be leaving some perf on the table in max-autotune mode.

The implementation of this just involves updating the `acc_type` function to read the correct flags:
https://github.com/pytorch/pytorch/blob/c8e72a4a5c6398ad38d41ceee9775f8d4544225c/torch/_inductor/kernel/mm_common.py#L134-L137

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by aakhundov** [comment]
Not sure if that's relevant, but `tl.dot` has an optional argument `out_dtype=triton.language.fp32` ([docs](https://triton-lang.org/main/python-api/generated/triton.language.dot.html#triton.language.dot)). We are currently not setting this flag in the Triton templates (e.g., [here](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/kernel/mm.py#L71)) which may be different from the eager mode's computation on `torch.backends.cuda.matmul.allow_fp16_reduced_precision_reduction = True`.

**Comment by hgl71964** [comment]
Hi, is there any update on this issue? I would like to do some works on inductor/triton otherwise

**Comment by jansel** [comment]
There are two abandoned PRs #108637 and #108982 that were both very close to fixing this issue, but got auto-closed due to inactivity.

Feel free to open a new PR for this if one of those authors doesn't chime in saying they are working in it.

**Comment by hgl71964** [comment]
Can I know why those two issues are abandoned? is it because [triton doesn't support bfloat16](https://github.com/openai/triton/issues/2302)

In that case, should we simply change to the following code? 

```python
def acc_type(dtype):
    mm_cfg = torch.backends.cuda.matmul
    cast_fp16 = (
        dtype == torch.float16 and not mm_cfg.allow_fp16_reduced_precision_reduction
    )
    # BF16 dot acc is currently neither supported in NVIDIA Tensor Cores
    # nor in Triton (via wmma/wgmma)
    # https://github.com/openai/triton/pull/1258#issuecomment-1709385295
    cast_bf16 = dtype == torch.bfloat16
    if cast_fp16:
        return "tl.float16"
    elif cast_bf16:
        return "tl.float32"
    return f"tl.{dtype}".replace("torch.", "")
```

**Comment by jansel** [comment]
As far as I can the authors stopped working on it.  There is no blocker.  This issue is now up for grabs.

**Comment by hgl71964** [comment]
I have created a PR to enable accumulating the float16 dtype, and some tests for the accuracy. Inspired by #108637 and #108982
