### ISSUE TITLE
torch.cross and torch.linalg.cross outputs inconsistent result when input's inner dimension is 3

### ISSUE THREAD

**Issue by drewshark** [pytorch/pytorch#108664]
### 🐛 Describe the bug

Here is the code to reproduce:

```
import torch
import numpy as np
np.random.seed(1234)
shape = (2,3,3)
a = np.random.rand(*shape)
b = np.random.rand(*shape)
a_tensor = torch.tensor(a, dtype=torch.float32)
b_tensor = torch.tensor(b, dtype=torch.float32)
out = torch.cross(a_tensor, b_tensor)
print("torch.cross's Output:\n", out)
out = torch.linalg.cross(a_tensor, b_tensor)
print("torch.linalg.cross's Output:\n", out)
print("Numpy's result: \n", np.cross(a, b))
```
Output:
```
torch.cross's Output:
 tensor([[[ 0.5627,  0.4476, -0.2451],
         [ 0.0349,  0.3025,  0.1757],
         [-0.4891, -0.6415,  0.0620]],

        [[-0.3895,  0.2825,  0.2498],
         [ 0.3167, -0.0926, -0.3452],
         [ 0.2222, -0.0697,  0.1915]]])
torch.linalg.cross's Output:
 tensor([[[-0.1594,  0.2684, -0.3117],
         [ 0.2671, -0.1219, -0.4208],
         [-0.3056,  0.7843, -0.5682]],

        [[ 0.0445, -0.1025, -0.0047],
         [ 0.4102, -0.2264, -0.3213],
         [ 0.3448, -0.3934,  0.3229]]])
Numpy's result: 
 [[[-0.15935776  0.26840489 -0.31173926]
  [ 0.26712543 -0.12190665 -0.42079283]
  [-0.30560534  0.78426594 -0.56817631]]

 [[ 0.04454216 -0.10246619 -0.00469417]
  [ 0.41019871 -0.22644311 -0.32132048]
  [ 0.34476641 -0.3934289   0.3229019 ]]]
```

Note that when I change the shape of a and be to (2,2,3) or (2,4,3) instead of **(2,3,3)**, the issue won't appear.

**Expected behavior**
torch.cross, torch.linalg.cross and np.cross should have the same outputs on the same input

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.109+-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4400.40
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        55 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by lezcano** [comment]
This is because of the insane semantics of `torch.cross`, see [the docs](https://pytorch.org/docs/stable/generated/torch.cross.html):
> If dim is not given, it defaults to the first dimension found with the size 3. Note that this might be unexpected.

Always prefer `linalg.cross` over `torch.cross`.

We should probably turn that line into a warning, and deprecate this function.
