### ISSUE TITLE
ProgressMonitor (Trainer plugin) prints incorrect progress value and percentage

### ISSUE THREAD

**Issue by recastrodiaz** [pytorch/pytorch#1086]
Code to replicate behaviour, extract of [jupyter notebook](https://github.com/recastrodiaz/courses/blob/master/deeplearning1/nbs/lesson1-pytorch.ipynb) In [9]:

```PYTHON
t = trainer.Trainer(model, criterion, optimizer, train_loader)
t.register_plugin(trainer.plugins.ProgressMonitor())
t.register_plugin(trainer.plugins.AccuracyMonitor())
t.register_plugin(trainer.plugins.LossMonitor())
t.register_plugin(trainer.plugins.TimeMonitor())
t.register_plugin(trainer.plugins.Logger(['progress', 'accuracy', 'loss', 'time']))

epochs = 1
t.run(epochs)
```

Prints:
```LOG
progress: 23000/360 (6388.89%)	accuracy: 100.00%  (99.31%)	loss: 0.0058  (0.0368)	time: 705ms    (1249ms)
```

Should print instead:
```
progress: 360/360 (100.00%)	accuracy: 100.00%  (99.31%)	loss: 0.0058  (0.0368)	time: 705ms    (1249ms)
```

I'll send over a PR for this.

**Comment by fmassa** [comment]
I'd not advise using `Trainer`. It's deprecated and will be removed from master at some point in the future.

**Comment by recastrodiaz** [comment]
@fmassa Thanks! 
1) Any suggestions on what to use instead? I was hoping not to roll my own for loops and find an equivalent of keras' [fit_generator](https://keras.io/models/sequential/#fit_generator)
2) Would you happen to know the reasons for its deprecation? I couldn't find much info about it online.
Feel free to close this issue as won't fix.

**Comment by fmassa** [comment]
@recastrodiaz you can try using https://github.com/pytorch/tnt
