### ISSUE TITLE
Result mismatch between real and fake quantization

### ISSUE THREAD

**Issue by CloudyDory** [pytorch/pytorch#108639]
### 🐛 Describe the bug

This is a follow-up to issue #95785. I have compared the results between fake (produced by `torch.quantization.prepare_qat`) and real (produced by `torch.quantization.convert`) quantized toy models, and I find that results are not completely the same.

Here is the code to reproduce the issue:

```python
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

# backend = 'x86'
# backend = 'onednn'
backend = 'qnnpack'
torch.backends.quantized.engine = backend

dev = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# -------- Generate the spiral dataset -------------
n = 10000     # Number of sampels in one class
t = np.random.rand(n*2) * 10.0
noise = np.random.randn(n*2,2) * np.sqrt(0.003)

x = 0.1*t*np.cos(t) + noise[:,0]
x[n:] *= -1
y = 0.1*t*np.sin(t) + noise[:,1]
y[n:] *= -1
data = np.stack((x, y), axis=1)
target = np.hstack( (np.ones(n), np.zeros(n)) ) # Class code

# Randomly shuffle the data
idx = np.arange(len(x))
np.random.shuffle(idx)
data, target = data[idx,:], target[idx]

dataTrain = torch.tensor(data, dtype=torch.float32, device=dev)
targetTrain = torch.tensor(target, dtype=torch.float32, device=dev).unsqueeze(1)

del n,idx,x,y

# ------------ Define the neural network ---------------
class Net(nn.Module):
    def __init__(self, n_feature, n_hidden, n_output):
        super(Net, self).__init__()
        self.quant = torch.quantization.QuantStub()
        self.layers = nn.ModuleList([
            nn.Linear(n_feature, n_hidden),
            nn.ReLU(),
            nn.Linear(n_hidden, n_output)])
        self.dequant = torch.ao.quantization.DeQuantStub()
                    
    def forward(self, x):
        out = self.quant(x)
        for layer in self.layers:
            out = layer(out)
        out = self.dequant(out)
        return out

# -------------- Prepare for training -----------------
network = Net(n_feature=data.shape[1], n_hidden=32, n_output=1).to(dev)

network.eval()
network.qconfig = torch.quantization.get_default_qat_qconfig(backend)
network_fused = torch.quantization.fuse_modules(network, [['layers.0', 'layers.1']])
network_fp32_prepared = torch.quantization.prepare_qat(network_fused.train())
network_fp32_prepared.train()

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(network_fp32_prepared.parameters(), lr = 0.01)

# --------------- Train the model ------------------
max_episode = 1000

for i in range(max_episode):
    logitsTrain  = network_fp32_prepared(dataTrain)
    lossTrain = criterion(logitsTrain, targetTrain)
    optimizer.zero_grad()
    lossTrain.backward()
    optimizer.step()
    
    if i%100 == 0 or i==max_episode-1:
        print('epoch {}, loss_train={:.5f}'.format(i, lossTrain.item())) 

network_fp32_prepared.eval()
network_quant = torch.quantization.convert(network_fp32_prepared.cpu(), inplace=False)

# ----------------- Compare the results -----------------
plt.figure()
plt.plot(network_fp32_prepared(dataTrain.cpu()).detach().cpu().numpy(), network_quant(dataTrain.cpu()).numpy(), marker='.', linestyle='')
plt.title(backend)
plt.xlabel('Fake quantization output')
plt.ylabel('Real quantization output')
plt.show()

```

We can see that the two results are quite close to the diagonal line, but they are not perfectly equal to each other. For regression tasks, the small error may be a problem. I hope to know what is the source of the error, and is it possible to eliminate it?

<img width="1119" alt="image" src="https://github.com/pytorch/pytorch/assets/38786521/ed3d4f36-624f-4b73-b872-a52c4a95146e">

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.11.4 (main, Jul  5 2023, 14:15:25) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.2.0-31-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 535.104.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      48 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             32
On-line CPU(s) list:                0-31
Vendor ID:                          AuthenticAMD
Model name:                         AMD Ryzen 9 7950X 16-Core Processor
CPU family:                         25
Model:                              97
Thread(s) per core:                 2
Core(s) per socket:                 16
Socket(s):                          1
Stepping:                           2
Frequency boost:                    enabled
CPU max MHz:                        5879.8818
CPU min MHz:                        3000.0000
BogoMIPS:                           9000.11
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d
Virtualization:                     AMD-V
L1d cache:                          512 KiB (16 instances)
L1i cache:                          512 KiB (16 instances)
L2 cache:                           16 MiB (16 instances)
L3 cache:                           64 MiB (2 instances)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-31
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.25.0
[pip3] numpydoc==1.5.0
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.8.0              h37601d7_11    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.6           py311ha02d727_1  
[conda] mkl_random                1.2.2           py311ha02d727_1  
[conda] numpy                     1.25.0          py311h08b1b3b_0  
[conda] numpy-base                1.25.0          py311hf175353_0  
[conda] numpydoc                  1.5.0           py311h06a4308_0  
[conda] pytorch                   2.0.1           py3.11_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2               py311_cu118    pytorch
[conda] torchtriton               2.0.0                     py311    pytorch
[conda] torchvision               0.15.2              py311_cu118    pytorch

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by HDCharles** [comment]
its not unexpected that they'll match exactly, you can see the breadth of tests we have:

https://github.com/pytorch/pytorch/blob/main/torch/ao/quantization/fake_quantize.py

but we're not expecting it to be exactly the same because the quantized ops have slightly different numerics depending on the backend.
