### ISSUE TITLE
Fix the imports in `torch.distributed._shard.sharding_spec.__init__.py`

### ISSUE THREAD

**Issue by b-chu** [pytorch/pytorch#108776]
### 🐛 Describe the bug

Similar to #80433, public access to `torch.distributed._shard.sharding_spec.ChunkShardingSpec` is not supported.

One possible fix (similar to #80955) is
```
from .chunk_sharding_spec import (
    ChunkShardingSpec as ChunkShardingSpec,
)
```

### Versions

[pip3] numpy==1.25.2
[pip3] torch==1.13.1+cu117
[pip3] torchtext==0.14.1
[pip3] torchvision==0.14.1+cu117
[conda] Could not collect

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

**Comment by wanchaol** [comment]
@b-chu we are seeking to deprecate ShardedTensor, do you have specific use case needs ShardedTensor and have you considered using DTensor instead?

**Comment by b-chu** [comment]
DTensor currently isn't as well supported as ShardedTensor and breaks with other libraries I use unfortunately.

**Comment by wanchaol** [comment]
> @wanchaol DTensor currently isn't as well supported as ShardedTensor and breaks with other libraries I use unfortunately.

If that's the case, feel free to submit PRs to address this issue, we can help review the changes
