### ISSUE TITLE
Compiled functional collectives fail without graph breaks on CUDA

### ISSUE THREAD

**Issue by ani300** [pytorch/pytorch#108780]
### 🐛 Describe the bug

I've been working on getting an implementation of Tensor Parallel working with torch.compile(), which implies the use of functional collectives so they can be traced and put in a single FX graph for more efficient compilation. While doing that, I noticed the results were completely off compared to the expected ones. This happens both for `all_reduce` and `all_gather_tensor`, which are the functional collectives I tested. The issues described below completely disappear if forcing a graph break right before running the collective and right after. If there's any computation kernel in the same compiled graph right before or after, the result will be wrong.

What makes this even more interesting/hard to debug is that it's not a synchronization issue, at least intra-GPU. I've modified the codegen for both `CollectiveKernel` and `Wait` to add a call to `torch.cuda.synchronize()` and prints of the involved tensors, which hasn't affected the results. Other things that haven't affected results are precision changing to FP16/BF16 from FP32, changing the process groups, and trying different nightlies between today and back to May or so.

In any case, here is a minimal repro of the issue. To run, in a machine with at least 2 GPUs, do:

`torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS repro.py`

```python
import os

import numpy as np
import torch
import torch.distributed as dist
import torch.distributed._functional_collectives as distf
import torch.nn as nn


# Basic process setup
# torch.set_printoptions(linewidth=150, precision=12)
SEED = 42
torch.manual_seed(SEED)  # pytorch random seed
torch.cuda.manual_seed(SEED)
np.random.seed(SEED)  # numpy random seed

rank = int(os.getenv("RANK"))
local_rank = int(os.getenv("LOCAL_RANK"))
world_size = int(os.getenv("WORLD_SIZE"))
device = torch.device("cuda", local_rank)
torch.cuda.set_device(device)
dist.init_process_group("nccl")


def apply_embedding_tp(par_mod: nn.Embedding, mod: nn.Embedding, world_size, rank):
    # Divide the weight matrix along the last dimension.
    output_size_per_partition = mod.embedding_dim // world_size
    with torch.no_grad():
        par_mod.weight.copy_(torch.split(mod.weight, output_size_per_partition, dim=1)[rank])
    # print(f"For rank {rank}, we have the following weights: Base weight {mod.weight} bias {mod.bias}; Par weight {par_mod.weight}, bias {par_mod.bias}")


def _all_reduce(input_: torch.Tensor) -> torch.Tensor:
    """All-reduce the input tensor across model parallel group."""
    world_size = dist.get_world_size()

    if world_size == 1:
        return input_
    # print("Graph break 1")
    out = distf.all_reduce(input_, "sum", list(range(world_size)))
    # print("Graph break 2")
    return out


def _all_gather(input_: torch.Tensor) -> torch.Tensor:
    """Gather the input tensor across model parallel group."""
    world_size = dist.get_world_size()

    if world_size == 1:
        return input_

    last_dim = input_.dim() - 1
    # print("Graph break 1")
    res = distf.all_gather_tensor(input_, 0, dist.distributed_c10d._world._default_pg)
    # print("Graph break 2")
    out = torch.cat(torch.chunk(res, world_size, dim=0), dim=last_dim)

    return out


def _split(input_: torch.Tensor, rank=0, world_size=1) -> torch.Tensor:
    """Split the tensor along its last dimension and keep the
    corresponding slice."""

    if world_size == 1:
        return input_

    # Split along last dimension.
    # Get the size and dimension.
    last_dim = input_.dim() - 1
    last_dim_size = input_.size()[last_dim] // world_size
    # Split.
    input_list = torch.split(input_, last_dim_size, dim=last_dim)

    # Note: torch.split does not create contiguous tensors by default.
    output = input_list[rank].contiguous()

    return output


class _CopyToModelParallelRegion(torch.autograd.Function):
    """Pass the input to the model parallel region."""

    @staticmethod
    def symbolic(graph, input_):
        return input_

    @staticmethod
    def forward(ctx, input_):
        return input_

    @staticmethod
    def backward(ctx, grad_output):
        return _all_reduce(grad_output)


class _ReduceFromModelParallelRegion(torch.autograd.Function):
    """All-reduce the input from the model parallel region."""

    @staticmethod
    def symbolic(graph, input_):
        return _all_reduce(input_)

    @staticmethod
    def forward(ctx, input_):
        return _all_reduce(input_)

    @staticmethod
    def backward(ctx, grad_output):
        return grad_output


class _AllGatherFromModelParallelRegion(torch.autograd.Function):
    """Gather the input from the model parallel region."""

    @staticmethod
    def symbolic(graph, input_):
        return _all_gather(input_)

    @staticmethod
    def forward(ctx, input_):
        ctx.rank = rank
        ctx.world_size = dist.get_world_size()
        return _all_gather(input_)

    @staticmethod
    def backward(ctx, grad_output):
        return _split(grad_output, ctx.rank, ctx.world_size)


def copy_to_tensor_model_parallel_region(input_):
    return _CopyToModelParallelRegion.apply(input_)


def reduce_from_tensor_model_parallel_region(input_):
    return _ReduceFromModelParallelRegion.apply(input_)


def all_gather_from_tensor_model_parallel_region(input_):
    return _AllGatherFromModelParallelRegion.apply(input_)


class Model(nn.Module):
    def __init__(self, vocab_size, emb_dim, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.emb = nn.Embedding(vocab_size, emb_dim)

    def forward(self, x):
        return self.emb(x)


class TPModel(Model):
    def __init__(self, vocab_size, emb_dim, rank, world_size, *args, **kwargs) -> None:
        super().__init__(vocab_size, emb_dim // world_size, *args, **kwargs)
        self.rank = rank
        self.world_size = world_size

    def forward(self, x):
        x_par = copy_to_tensor_model_parallel_region(x)
        y_par = self.emb(x_par)
        return all_gather_from_tensor_model_parallel_region(y_par)


model = Model(32, 32).to(device)
tp_model = TPModel(32, 32, rank, world_size).to(device)

# Copy weights
apply_embedding_tp(tp_model.emb, model.emb, world_size, rank)

tp_model = torch.compile(tp_model)

l_seq = 10
l_batch = 1

# Simulate tokenization on only one process
if rank == 0:
    inp = torch.randint(0, 32, (l_batch, l_seq), dtype=torch.long).to(device)
else:
    inp = torch.zeros([l_batch, l_seq], dtype=torch.long).to(device)
torch.distributed.broadcast(inp, 0)

# See issue #107824 for why no_grad() is needed
with torch.no_grad():
    out = model(inp)
    tp_out = tp_model(inp)
    torch.cuda.synchronize()
    print(f"Error report rank {rank}: {out-tp_out};  Avg abs error: {(out-tp_out).abs().mean()}")
```

Running the repro as is on 2 GPUs on my environment gets the following wrong results (with `TORCH_LOGS="dynamo,graph_breaks,inductor,dynamic,aot_graphs,output_code"` for extra debug information): See incorrect.log
[incorrect.log](https://github.com/pytorch/pytorch/files/12551223/incorrect.log)

If I turn on the two graph breaks around the call to `all_gather_tensor`, the results change to the following (which are the correct/expected ones): See correct.log
[correct.log](https://github.com/pytorch/pytorch/files/12551217/correct.log)

I'm happy to provide any extra information or work together with whoever is best suited to solve this issue.

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230828+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-372.19.1.el8_6.x86_64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB

Nvidia driver version: 515.48.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          80
On-line CPU(s) list:             0-79
Thread(s) per core:              2
Core(s) per socket:              20
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel Xeon Processor (Cascadelake)
Stepping:                        5
CPU MHz:                         2399.998
BogoMIPS:                        4799.99
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.3 MiB
L1i cache:                       1.3 MiB
L2 cache:                        160 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-39
NUMA node1 CPU(s):               40-79
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat pku ospke avx512_vnni md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.0b1
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230828+cu118
[pip3] torchvision==0.16.0.dev20230828+cu118
[conda] numpy                     1.26.0b1                 pypi_0    pypi
[conda] pytorch-triton            2.1.0+e6216047b8          pypi_0    pypi
[conda] torch                     2.1.0.dev20230828+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230828+cu118          pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ani300** [comment]
Adding in the changes in #108811 fixes the issues with the functional `all_reduce`, but `all_gather` still needs the graph breaks to work properly.

**Comment by yf225** [comment]
Smaller repro:
```python
# torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS repro.py

import os

import numpy as np
import torch
import torch.distributed as dist
import torch.distributed._functional_collectives as _functional_collectives
import torch._inductor.config
import torch.nn as nn

rank = int(os.getenv("RANK"))
local_rank = int(os.getenv("LOCAL_RANK"))
world_size = int(os.getenv("WORLD_SIZE"))
device = torch.device("cuda", local_rank)
tag = ""
ranks = list(range(world_size))
group_size = world_size
torch.cuda.set_device(device)
dist.init_process_group("nccl")

class Model(torch.nn.Module):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.emb = torch.nn.Embedding(4, 4)

    def forward(self, x):
        y = self.emb(x)
        last_dim = y.dim() - 1
        res = _functional_collectives.all_gather_tensor(y, 0, ranks, tag)
        out = torch.cat(torch.chunk(res, world_size, dim=0), dim=last_dim)
        return out

torch._inductor.config.allow_buffer_reuse = True

tp_model = Model().cuda()
tp_model_compiled = torch.compile(tp_model)

inp = torch.tensor([[2, 1, 3, 0]], dtype=torch.long, device="cuda")

# See issue #107824 for why no_grad() is needed
with torch.no_grad():
    tp_out = tp_model(inp)
    tp_compiled_out = tp_model_compiled(inp)
    assert torch.allclose(tp_compiled_out, tp_out)
```

We are working on a fix as part of https://github.com/pytorch/pytorch/pull/108811.

**Comment by yf225** [comment]
@ani300 Please feel free to try out the latest https://github.com/pytorch/pytorch/pull/108811 and see if it fixes the issue. Thanks!
