### ISSUE TITLE
[inductor][cpu][dynamic shapes] performance regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#108754]
<p>new_perf_regression 2023-09-03 compare with 2023-08-27 nightly release</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hf_T5_generate</td>
      <td>1</td>
      <td>0.971038</td>
      <td>1.5633510240000001</td>
      <td>1.518073251642912</td>
      <td>942.552728</td>
      <td>1</td>
      <td>1.134897</td>
      <td>1.33691611</td>
      <td>1.51726208249067</td>
      <td>948.933104</td>
      <td>0.86</td>
      <td>1.0</td>
      <td>0.86</td>
      <td>1.01</td>
    </tr>
    <tr>
      <td>pyhpc_equation_of_state</td>
      <td>1</td>
      <td>22.341193</td>
      <td>5.0237999999999996e-05</td>
      <td>0.001122376853934</td>
      <td>12.651067</td>
      <td>1</td>
      <td>25.271428</td>
      <td>4.4846e-05</td>
      <td>0.001133322460088</td>
      <td>12.156882</td>
      <td>0.88</td>
      <td>1.01</td>
      <td>0.89</td>
      <td>0.96</td>
    </tr>
  </tbody>
</table>
<p>SW info</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>ea7e229</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>770d5cf7</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>dc83b38</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>c11d758</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>58366ab</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>1d231d1</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>f228c8b</td>
      <td>/</td>
    </tr>
  </tbody>
</table>

Repro:
bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) multiple inference performance **torchbench hf_T5_generate** float32 first dynamic default 0

bash
[inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
single inference performance **torchbench pyhpc_equation_of_state** float32 first dynamic default 0

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by Valentine233** [comment]
For `hf_T5_generate`, find the PR causing regression: https://github.com/pytorch/pytorch/pull/106192.

**Comment by leslie-fang-intel** [comment]
> For `hf_T5_generate`, find the PR causing regression: #106192.

Looks like a big PR, Need further break down to root-cause.

**Comment by Valentine233** [comment]
**Root cause**
With further break down, this change of `ExternKernel::realize_input` in above PR causes the regression.

<img width="445" alt="image" src="https://github.com/pytorch/pytorch/assets/23010269/69f66fca-aa10-45e3-a7cf-1853fe741491">

Specifically for the external kernel `bmm`, it goes into `convert_to_reinterpret_view` instead of `copy_input` when realizing input. Thus, `bmm` takes longer due to the layout.

**Performance**
The bmm time of running one `output_code` file (`hf_T5_generate__21_inference_57.3/output_code.py`) is calculated.

| Code version | bmm time (s) |
| -------------- | ------------ |
| W/O change | 0.00317847 |
| With change | 0.004867561 |

**Example**
Example of the difference in `output_code`:
_W/O change_
```
buf7 = reinterpret_tensor(buf2, (8, 1, 64), (64, 512, 1))
extern_kernels.bmm(buf7, reinterpret_tensor(buf6, (8, 64, 2), (128, 1, 64), 0), out=buf8)
```
_With change_
`extern_kernels.bmm(reinterpret_tensor(buf2, (8, 1, 64), (64, 0, 1), 0), reinterpret_tensor(buf6, (8, 64, 2), (128, 1, 64), 0), out=buf7)`

cc @Chillee

**Comment by Chillee** [comment]
Hmm, I don’t think this change is necessary to the rest of the PR. That change can probably be reverted.

**Comment by Valentine233** [comment]
> Hmm, I don’t think this change is necessary to the rest of the PR. That change can probably be reverted.

Sure, I will open a PR to revert this change.
