### ISSUE TITLE
torch.sign() - native support for strictly positive/negative values

### ISSUE THREAD

**Issue by DanielEftekhari** [pytorch/pytorch#108788]
Currently, `torch.sign(x)` has the following behavior, where we have as input a tensor `x`, with `x > 0` evaluating to `tensor(True)`:
- `torch.sign(x) = tensor(1.)` (as expected)
- `torch.sign(-x) = tensor(-1.)` (as expected).

But when `x = torch.tensor(0.)`, we have
- `torch.sign(x) = tensor(0.)` ; this is the point I'm raising.

The request is that in the `torch.sign(x)` function, there be a (Boolean) argument, for example `keep_zeros`, which would result in the following behavior:
- A) `torch.sign(torch.tensor(0.), keep_zeros=True) = 0.`
- B) `torch.sign(torch.tensor(0.), keep_zeros=False) = 1.`

where importantly `keep_zeros=True` by default, for consistency with the function's current behavior.

This is valuable to have for a few reasons:
- enables the user to specify which behavior they want, as both are in fact widely seen and valid (and importantly they do lead to different behaviors depending on the program.)
- it is a simple but valuable change, one which would help avoid unnecessary confusion.

I appreciate there are other ways of achieving the same functionality, but in principle if there is a `torch.sign()` function, that function should be able to do just this.

Thank you for your attention.

cc @albanD

**Comment by zou3519** [comment]
It's probably easier if you write your own function that does this (with torch.where?).

**Comment by albanD** [comment]
Since the current implementation is consistent with NumPy and the array API https://data-apis.org/array-api/2022.12/API_specification/generated/array_api.sign.html I don't think we should add this new kwarg.

To make @zou3519 proposal more concrete, what you want here can be done with `torch.where(a > 0, 1, -1)` (make it `>=` to change the sign at 0).
