### ISSUE TITLE
[inductor][cpu][cpp_wrapper] performance regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#108753]
<p>new_perf_regression compare with 2023-08-22 nightly release</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>T5Small</td>
      <td>4</td>
      <td>0.645049</td>
      <td>0.607526311</td>
      <td>0.391884239384239</td>
      <td>43.730784</td>
      <td>4</td>
      <td>0.832136</td>
      <td>0.465242779</td>
      <td>0.387145265145944</td>
      <td>43.323414</td>
      <td>0.78</td>
      <td>0.99</td>
      <td>0.77</td>
      <td>0.99</td>
    </tr>
  </tbody>
</table>
<p>SW info</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>ea7e229</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>770d5cf7</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>dc83b38</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>c11d758</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>58366ab</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>1d231d1</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>f228c8b</td>
      <td>/</td>
    </tr>
  </tbody>
</table>

Repro:
bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) multiple inference performance **suite model** float32 first static cpp 0

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by chunyuan-w** [comment]
I checked the latest data on 0918, inductor performance is back to 0.470748449. The performance difference with 0822 nightly is 1.2%. @ESI-SYD could you please help double confirm this?

**Comment by ESI-SYD** [comment]
Comfirmed
