### ISSUE TITLE
[dtensor] Add debug tool to visualize sharding

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#108746]
Add a debug tool for sharding visualization, put the API in `https://github.com/pytorch/pytorch/tree/main/torch/distributed/_tensor/debug`, where we can define a API

`visualize_sharding(dtensor)`, where it takes in a dtensor, and print out a nice figure about the sharding layout for 1d - 2d tensor, this would greatly help debugging the sharding layout of a particular dtensor. 

One can be creative about what python package to use for sharding visualization in terminal, one example could be https://pypi.org/project/tabulate/

**Comment by thechargedneutron** [comment]
Hi, I can work on this issue.

What kind of sharding layout are we interested in? Is there some existing visualizations that can be a good starting point?
