### ISSUE TITLE
[pytorch] requires_grad=False from torch.tensor ignored when the input tensor has requires_grad=True 

### ISSUE THREAD

**Issue by sytrus-in-github** [pytorch/pytorch#10876]
## Issue description

As shown by the following example, the expected behavior (at least from me) is to copy only the data from `t1` to `t2`, however `torch.tensor()` seems to build up a computation graph from `t1` instead ...

## Code example

```python
>>> t1 = torch.tensor([1,1,1], dtype=torch.float, requires_grad=True)
>>> t2 = torch.tensor(t1, requires_grad=False)
>>> t2.requires_grad
True
>>> t1
tensor([1., 1., 1.], requires_grad=True)
>>> t2
tensor([1., 1., 1.], grad_fn=<CopyBackwards>)
```

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): conda
- OS: Ubuntu 16.04
- PyTorch version: 0.4.1
- Python version: 3.6.3

**Comment by srossi93** [comment]
I think this is an intended behavior. If you want a detached copy of `t1` into `t2`, you can do as follows

```python 
import torch
t1 = torch.tensor([1,1,1], dtype=torch.float, requires_grad=True)
t2 = torch.tensor(t1.data, requires_grad=False)

>>> t1
tensor([1., 1., 1.], requires_grad=True)
>>> t2
tensor([1., 1., 1.])
>>> t2.requires_grad
False

**Comment by sytrus-in-github** [comment]
@srossi93 Thanks. This is also what I used instead when I found out the problem.

Still it is unclear to me what `torch.tensor` intends to do with a Variable input other than just copy its data and create a new tensor ... In any case ignoring a given settings is a strange behavior that should be changed / clearly documented.
