### ISSUE TITLE
[optimize_ddp] moco - NameError: name 's2' is not defined 

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#108877]
### 🐛 Describe the bug

In https://github.com/pytorch/pytorch/issues/101939#issuecomment-1699726230 @jansel reported that when he turns on `--dynamic-shapes` on moco it fails with

```
  File "/tmp/torchinductor_jansel/dd/cdd3xq74ulaveo5x7yion4c5db2hdp4ri3ivhi5typqx3gud4fge.py", line 599, in call
    assert_size_stride(primals_103, (s0, 512, 1 + (((-1) + s2) // 8), 1 + (((-1) + s2) // 8)), (512 + (512*((((-1) + s2) // 8)*(((-1) + s2) // 8))) + (1024*(((-1) + s2) // 8)), 1 + ((((-1) + s2) // 8)*(((-1) + s2) // 8)) + (2*(((-1) + s2) // 8)), 1 + (((-1) + s2) // 8), 1))
NameError: name 's2' is not define
```

I have confirmed that when `optimize_ddp = False`, this error goes away.

Success log: https://gist.github.com/ezyang/3dd898ba65d3fd6451d9b3e01611ebb7
Fail log: https://gist.github.com/ezyang/76d31fb7d0e04e89b8707c946c3e46ff

I have a theory for what is going on here. In dynamic shapes, we require the invariant that all symbolic symbols be explicit inputs to the graph in question. This is required to ensure that you never accidentally pass in an argument like `f32[s0 + s1]` in which case it is impossible to infer what the true s0/s1 variables is. In particular, if you don't pass in the symbol as an explicit argument, Inductor won't bind it.

`optimize_ddp` involves splitting graphs. I doubt that it maintains this invariant when generating graphs, which is the cause of this problem.

Because we are sunsetting `optimize_ddp` soon, I am not sure if it is worth directly fixing this.

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @wanchaol @fduwjj @wz337 @kiukchung @d4l3k @lucasllc @tianyu-l

**Comment by wconstab** [comment]
> I am not sure if it is worth directly fixing this. 
perhaps not, but i'm curious anyway 

> invariant that all symbolic symbols be explicit inputs to the graph in question 
> optimize_ddp involves splitting graphs. I doubt that it maintains this invariant

iirc the partitioner would have to create inputs for each of the things that are passed between subgraphs, unless they are module attrs accessed by getattr nodes.  it should be easy to confirm if the symints in question are or aren't inputs to the graph. (or if they aren't inputs, what are they?)  maybe they are locals, but in the single-graph case dynamo promotes them from local to input, and in the split case that is lost?

**Comment by ezyang** [comment]
The thing about symint inputs is they made not be used. But if any free symbol of any input mentions the input, it must be added as an input!

**Comment by wuxun-zhang** [comment]
@ezyang Hi, I met a use case where I need to insert a new `as_strided` op into a FX graph. The input sizes and strides of `as_strided` op contain SymInts. If I directly use SymInts, then same error is raised (NameError: name 's0' is not defined). Is this a valid case to fix or do you have any advice to workaround this? Thanks:)

The FX graph is like below:

```markdown
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: Sym(s0), arg1_1: Sym(s1), arg2_1: f32[s0, s1, 4, 2], arg3_1: f32[2, s1, 4, s0]):
        # File: tests/test_transpose_inplace_op.py:138, code: inp_0 = torch.transpose(input, 0, 3)
        transpose: f32[2, s1, 4, s0] = torch.ops.aten.transpose.int(arg2_1, 0, 3);  arg2_1 = None

        # File: tests/test_transpose_inplace_op.py:139, code: return inp_0.add_(other)
        add: f32[2, s1, 4, s0] = torch.ops.aten.add.Tensor(transpose, arg3_1);  transpose = arg3_1 = None
        transpose_1: f32[s0, s1, 4, 2] = torch.ops.aten.transpose.int(add, 0, 3);  add = None

        # No stacktrace found for following nodes
        as_strided_0: f32[s0, s1, 4, 2] = torch.ops.aten.as_strided.default(transpose_1, (s0, s1, 4, 2), (8*s1, 8, 2, 1))

        # File: tests/test_transpose_inplace_op.py:139, code: return inp_0.add_(other)
        transpose_2: f32[2, s1, 4, s0] = torch.ops.aten.transpose.int(as_strided_0, 0, 3);  as_strided_0 = None
        return (transpose_1, transpose_2)
```

**Comment by ezyang** [comment]
So the inductor generated code chokes? Can you paste that generated code? Also we fixed some stuff on nightly, so try master if you haven't already

**Comment by wuxun-zhang** [comment]
It's generated by custom HPU backend and the `as_strided` node is inserted manually. If possible, could you please show the links to these stuff changes?
> Also we fixed some stuff on nightly, so try master if you haven't already

**Comment by ezyang** [comment]
https://dev-discuss.pytorch.org/t/state-of-symbolic-shapes-branch/777/72

**Comment by wuxun-zhang** [comment]
Thanks for the link. We will have a try with master version. BTW, if master branch still doesn't work, do you have some advice to work around it in custom backend?

**Comment by alicja-szlachta** [comment]
@ezyang, could you please provide a commit which includes the changes in the link you posted yesterday?

**Comment by ezyang** [comment]
Minimal repro

```
    @patch.object(config, "optimize_ddp", True)
    def test_symbol_splitting(self):
        class Model(nn.Module):
            def __init__(self):
                super().__init__()
                self.weight1 = nn.Parameter(torch.randn(512, 512))
                self.weight2 = nn.Parameter(torch.randn(512, 512))

            def forward(self, x):
                x = torch.cat([x, x])
                y = x @ self.weight1
                z = x + y @ self.weight2
                return z

        model = Model()
        model = FakeDDP(model)

        opt_model = torch.compile(dynamic=True)(model)
        opt_model(torch.randn(20, 512))
```
