### ISSUE TITLE
Doc rendering bug ` <torch.distributions.constraints._GreaterThan object at 0x7f65512f4860>`

### ISSUE THREAD

**Issue by hughperkins** [pytorch/pytorch#10884]
## Issue description

See https://pytorch.org/docs/stable/distributions.html#gumbel , doc seems to have a rendering bug? To me, in Chrome on Mac, looks like:

<img width="674" alt="screen shot 2018-08-26 at 1 44 35 pm" src="https://user-images.githubusercontent.com/123560/44631164-61446300-a936-11e8-844e-8a9473f3b8a4.png">

**Comment by vishwakftw** [comment]
This is an issue with most of the distributions, unfortunately. The issue is that `sphinx` renders the default arguments as it appears in the `__repr__`. One way to fix this is by modifying `__repr__` for the constraints. I'll send in a patch.
