### ISSUE TITLE
FSDP: Can fused AdamW be used in FSDP? Got Runtime error when training FSDP with fused AdamW when saving optimizer states.

### ISSUE THREAD

**Issue by Calvinnncy97** [pytorch/pytorch#108860]
### 🐛 Describe the bug

Hi guys, 

I am new to FSDP and I would like to ask for your help in the following error. 

I am trying to train a Llama2 model with FSDP. However, whenever the optimizer states are to be saved with fused AdamW, it will give me Runtime Error due to the tensor shapes returned. 

```
data_collator = DataCollatorForPretrainDataset(tokenizer=tokenizer)
data_module = dict(train_dataset=train_dataset, eval_dataset=None, data_collator=data_collator)

args = TrainingArguments(output_dir='test_hf_llama', 
                                      fp16=True, 
                                      tf32=True, 
                                      per_device_train_batch_size=1,
                                      num_train_epochs=1, 
                                      learning_rate=0.0005,
                                      lr_scheduler_type="cosine",
                                      warmup_ratio=0.03,
                                      max_grad_norm=1,
                                      fsdp="full_shard auto_wrap",
                                      fsdp_transformer_layer_cls_to_wrap='LlamaDecoderLayer',
                                      evaluation_strategy="no",
                                      save_strategy="steps",
                                      save_steps=1,
                                      save_total_limit=1,
                                      logging_steps=1,
                                      gradient_accumulation_steps=8,
                                      optim='adamw_torch_fused',
                                      'fsdp_config' : {
                                              "use_orig_params" : "true",
)
```

**With use_orig_params=True**
If I run it with `use_orig_params=True`, I get the following error:
```
File "/home/me/llama2.c/.venv/lib/python3.9/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1701, in _gather_orig_param_state   

RuntimeError: shape '[288, 288]' is invalid for input of size 1 
```
Here's the code in `_optim_utils.py`:
```
gathered_state = _all_gather_optim_state(fsdp_state, optim_state)
 
    # Unflatten state values.
    for state_name, value in list(gathered_state.items()):
        # if state_name == 'step':
        #     continue
        if not torch.is_tensor(value) or value.dim() == 0:
            continue
        value = value[: flat_param._numels[param_idx]].reshape(
            flat_param._shapes[param_idx]
        )
        if shard_state:
            assert fsdp_state.process_group is not None
            value = _ext_chunk_tensor(
                value,
                fsdp_state.rank,
                fsdp_state.world_size,
                torch.cuda.device_count(),
                fsdp_state.process_group,
            )
        value = value.cpu()
        gathered_state[state_name] = value
    return gathered_state
```

When I print the keys and value size of `gathered_state`, this is the output:
```
STATES: {'exp_avg': torch.Size([82944]), 'exp_avg_sq': torch.Size([82944]), 'step': torch.Size([1])} 
```

The error makes sense because it is trying to reshape the 'step' value into unflattened tensor.

**With use_orig_params=False**
If I run it with `use_orig_params : False`, I will get the following:
`RuntimeError: output tensor size must be equal to world_size times input tensor size` at line 2532 `work = group._allgather_base(output_tensor, input_tensor)` in `/python3.9/site-packages/torch/distributed/distributed_c10d.py`.

**If I simply use AdamW**
If I simply use AdamW without the fused flag, everything runs fine. 

Is this a bug? Kindly advise :) Really appreciate it. 🙏

### Versions

**Environment**
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: 11.0.1-2
CMake version: version 3.27.2
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.16.0-0.bpo.4-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-255
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7763 64-Core Processor
Stepping:                        1
CPU MHz:                         3114.879
BogoMIPS:                        4890.76
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-15,128-143
NUMA node1 CPU(s):               16-31,144-159
NUMA node2 CPU(s):               32-47,160-175
NUMA node3 CPU(s):               48-63,176-191
NUMA node4 CPU(s):               64-79,192-207
NUMA node5 CPU(s):               80-95,208-223
NUMA node6 CPU(s):               96-111,224-239
NUMA node7 CPU(s):               112-127,240-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.8
[pip3] torch==2.0.1
[pip3] torchmetrics==1.1.1
[pip3] triton==2.0.0
[conda] Could not collect

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @fegin

**Comment by fegin** [comment]
Thanks for reporting the issue. This seems to be a bug to me. We are rewriting `_all_gather_optim_state`, will consider this case.

**Comment by fegin** [comment]
@Calvinnncy97 This seems to be a bug of fused AdamW which it initialized the `step` as a 1-dimensional tensor. The trunk already changed it back to a scalar tensor. I tested FSDP + fused AdamW, the load and save optimizer state dict work correctly.

**Comment by Calvinnncy97** [comment]
@fegin Thank you so much for confirming that it is a bug 😊. I was stuck for 2 days and weren't sure. May I know where is the fix? Couldn't find it in the commits of the main repo. 

Thank you so much for your help!

**Comment by janeyx99** [comment]
It should already be fixed in the latest nightly, so updating your torch would work! https://pytorch.org/ has the installer toggle thing that would give you the command for installing the nightly.

**Comment by Calvinnncy97** [comment]
Oh I see. Got it. Thank you @janeyx99 !

**Comment by fegin** [comment]
@Calvinnncy97 I'll close the issue. Feel free to report it if this still bothers you.
