### ISSUE TITLE
DISABLED test_lstm_packed (__main__.CPUReproTests)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#108824]
Platforms: asan

Although this is already marked as a slow test, this is timing out on slow job itself, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/c75aec90d3e901abd604d075c5695ae561608605.  I need to disable the test until we figure out how to address it.  Is this too slow even for the current timeout value of 30m?

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen @ngimel @clee2000

**Comment by chunyuan-w** [comment]
Hi @huydhn, I created https://github.com/pytorch/pytorch/pull/116453 to reduce the time of this test by using smaller shapes while keeping the same test scope.
