### ISSUE TITLE
DISABLED test_module_with_training_state (__main__.OptimizedModuleTest)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#108838]
This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/dynamo%2Ftest_modules.py%3A%3AOptimizedModuleTest%3A%3Atest_module_with_training_state)).

This is failing in trunk after the revert of https://hud.pytorch.org/pytorch/pytorch/commit/72f24d000195952aa3130e84c7267390405a5ed6.  As the PR is revert due to a merge conflict and will be reland soon, I'm disabled this test temporarily

**Comment by huydhn** [comment]
Closing as the #108750 has been reverted

**Comment by youkaichao** [comment]
@huydhn when yould you apply back these changes?

**Comment by huydhn** [comment]
I think we can reland you change once https://github.com/pytorch/pytorch/pull/108969 merged.

cc @anijain2305

**Comment by youkaichao** [comment]
Do I need to do anything?

**Comment by huydhn** [comment]
Please re-open your PR, rebase it, and merge it again once the above finishes

**Comment by youkaichao** [comment]
Please ping me when it finishes.
