### ISSUE TITLE
UNSTABLE pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default)

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#108874]
> Please provide a brief reason on why you need to mark this job as unstable.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by clee2000** [comment]
I assume this is fixed

**Comment by izaitsevfb** [comment]
Lots of sporadic timeouts recently: https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=200&name_filter=pull%20%2F%20linux-focal-cuda12.1-py3.10-gcc9-sm86%20%2F%20test

Marking job as unstable.

**Comment by izaitsevfb** [comment]
Timeouts were curbed by manually marking offending test as slow: #111524

Moving this job back to stable.

**Comment by huydhn** [comment]
The CUDA illegal memory access error from https://github.com/pytorch/pytorch/issues/116289 strikes again today.  I have already run https://github.com/pytorch/pytorch/actions/runs/7344269084/job/20179929009 to clear the cache to see if this helps, will monitor to see if this restores trunk sanity before closing the issue.

**Comment by jeanschmidt** [comment]
```
FAILED [1.6917s] inductor/test_flex_attention.py::TestTemplatedSDPA::test_builtin_score_mods_bfloat16_score_mod1 - torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacity of 21.98 GiB of which 13.24 GiB is free. Process 30127 has 248.00 MiB memory in use. Process 30150 has 1.03 GiB memory in use. Process 31116 has 248.00 MiB memory in use. Process 1336 has 248.00 MiB memory in use. Process 1379 has 542.00 MiB memory in use. Process 2994 has 6.41 GiB memory in use. Of the allocated memory 5.28 GiB is allocated by PyTorch, and 849.72 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by huydhn** [comment]
I have reverted the change causing that failure in https://github.com/pytorch/pytorch/pull/125515 and cc @clee2000 , so I will close this issue and work with @clee2000 and @drisspg to reland the change.
