### ISSUE TITLE
nanogpt_generate and clip pass regression

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#108884]
### 🐛 Describe the bug

These models regressed from 9/01 -> 9/02. Filing this issue to track / further triage.

https://hud.pytorch.org/benchmark/blueberries/inductor_no_cudagraphs?startTime=Fri,%2001%20Sep%202023%2018:26:13%20GMT&stopTime=Fri,%2008%20Sep%202023%2018:26:13%20GMT&granularity=hour&mode=inference&dtype=bfloat16&lBranch=main&lCommit=ffc0c46092efef1f3b51becc8f5770abcec5c23a&rBranch=main&rCommit=591cb776af68e43f41cba1a29b6219341b75d951

### Versions

master

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by Chillee** [comment]
Seems to have been resolved
