### ISSUE TITLE
CompileId in Dynamo log messages should include restart analysis count

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#108835]
### 🐛 Describe the bug

Instead of `[0/0]` on both analysis 1 and analysis 2, if we restart analysis we should add another number, e.g., `[0/0@1]` or something. Probably best to elide the number if not needed. This makes it visually obvious when analysis was restarted.

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by anijain2305** [comment]
This already happens today.
