### ISSUE TITLE
PyTorch was compiled without cuDNN support. To use cuDNN, rebuild 

### ISSUE THREAD

**Issue by RayAnteku** [pytorch/pytorch#10892]
Hello ,I use pytorh 3.0 with python 2.7 and my cuda is 8.0 and cudnn is 6.0 when I use GPU to run some codes , I saw the following error , how can I handle it ? Thanks

```
UserWarning: PyTorch was compiled without cuDNN support. To use cuDNN, rebuild PyTorch making sure the library is visible to the build system.
  "PyTorch was compiled without cuDNN support. To use cuDNN, rebuild "
```

**Comment by soumith** [comment]
This is a warning. When you compiled PyTorch, it did not detect the CuDNN you have.

**Comment by RayAnteku** [comment]
Thanks for your response, how can I handle this ? @soumith  
I saw somebody using pip to install this pytorch instead of conda install ,and then they can avoid this problem. Do you have some methods??

**Comment by SsnL** [comment]
Maybe just installing cudnn on your machine?

**Comment by SsnL** [comment]
Are you building from source?

**Comment by soumith** [comment]
you are compiling from source. If you install from `pip` or `conda`, using the commands on our website, https://pytorch.org , you should be good to go.

**Comment by Justin4411** [comment]
How do I read these

**Comment by RayAnteku** [comment]
I see, I use the pip install the pytorch 0.3.1 and this problem is now handled. @soumith @SsnL  thanks
