### ISSUE TITLE
Dtensor and jacrev

### ISSUE THREAD

**Issue by HongLouyemeng** [pytorch/pytorch#108974]
### 🚀 The feature, motivation and pitch

Hi,Dtensor can slice the tensor to different devices, how can we combine [jacrev](https://pytorch.org/functorch/stable/generated/functorch.jacrev.html) and [vmap](https://pytorch.org/docs/stable/generated/torch.vmap.html#torch.vmap) with the dtensor ,Make a Jacobi matrix can be sliced to different devices or nodes?Then make this Jacobi matrix global computation?Here's an example, but it looks like it can only be accessed via rank.... **I'm not so sure about the dtensor for algebraic operations.**

### Alternatives
```python

@spawn_threads_and_init_comms
def shard_big_tensor(world_size):
  mesh = DeviceMesh("cpu", [0,1,2,3])
  djac = zeros([D,D], device_mesh=mesh,placements=[Shard(0)])
  djac = compute_jac(xp,djac,world_size,dist.get_rank())
  print(f"on rank: {dist.get_rank()}, dtensor global shape: {djac.shape}, local shape: {djac.to_local().shape}")

def predict(weight, bias, x):
    return F.linear(x, weight, bias).tanh()

def compute_jac(xp,djac,world_size,rank):
    for idx in range(int(D/world_size)):
      vec = unit_vectors[idx+(rank)*int(D/world_size)]
      x = torch.autograd.grad(predict(weight, bias, xp), xp, vec)[0]
      djac.to_local()[idx] = torch.autograd.grad(predict(weight, bias, xp), xp, vec)[0]
      jacobian[idx+(rank)*int(D/world_size)] = djac.to_local()[idx]
    return djac

WORLD_SIZE=4
D = 16
x_origin = torch.randn(D)
jacobian = torch.zeros((D,D))
weight =  torch.randn(D, D)
bias =  torch.randn(D)
x = x_origin.clone() # feature vector
xp = x.clone().requires_grad_()
unit_vectors = torch.eye(D)
shard_big_tensor(WORLD_SIZE)

from torch.func import jacrev
ft_jacobian = jacrev(predict, argnums=2)(weight, bias, x)
assert torch.allclose(ft_jacobian, jacobian)
### Additional context
on rank: 1, dtensor global shape: torch.Size([16, 16]), local shape: torch.Size([4, 16])
on rank: 0, dtensor global shape: torch.Size([16, 16]), local shape: torch.Size([4, 16])
on rank: 2, dtensor global shape: torch.Size([16, 16]), local shape: torch.Size([4, 16])
on rank: 3, dtensor global shape: torch.Size([16, 16]), local shape: torch.Size([4, 16])

```[tasklist]
### Tasks
colab:https://colab.research.google.com/drive/1UqUCEfJDhNDPvZZjDQuOdmxepkqGhaQz?usp=sharing
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @ezyang @msaroufim @albanD @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

**Comment by HongLouyemeng** [comment]
I get this error:NotImplementedError: Operator aten.select.int does not have a sharding strategy registered.

**Comment by HongLouyemeng** [comment]
Maybe we can use global index to handle global tensor?

**Comment by HongLouyemeng** [comment]
I apologise for not describing the problem at first.QAQ

**Comment by wanchaol** [comment]
@HongLouyemeng we haven't fleshed out how dtensor would work properly with functorch yet, any particular usecase for it? cc @zou3519 as we discussed this before

**Comment by HongLouyemeng** [comment]
> @HongLouyemeng we haven't fleshed out how dtensor would work properly with functorch yet, any particular usecase for it? cc @zou3519 as we discussed this before

For example [gaussian newton method](https://en.wikipedia.org/wiki/Gauss%E2%80%93Newton_algorithm),It need handle a jacobian, I want to process it on muilt-device.[Goole Distributed Linear Algebra](https://arxiv.org/pdf/2112.09017.pdf),[Tpetra](https://docs.trilinos.org/dev/packages/tpetra/doc/html/index.html),Maybe torch's dtensor can not do that,@wanchaol @zou3519

**Comment by HongLouyemeng** [comment]
If torch has plans to finish this, I'd love to be involved

**Comment by zou3519** [comment]
Do you have a self-contained script that reproduces the problem you ran into?

**Comment by HongLouyemeng** [comment]
> Do you have a self-contained script that reproduces the problem you ran into?

I made a [simple colab](https://colab.research.google.com/drive/1UqUCEfJDhNDPvZZjDQuOdmxepkqGhaQz?usp=sharing) to test dtensor, and I think dtensor should be able to do functorch and a part of distributed algebra computation.But since devicemesh is currently set up rather spartanly, I guess it's possible that different methods may require repacking process groups and choosing different communication methods based on the communication topology
