### ISSUE TITLE
nn.LayerNorm outputs zeros for single column batch

### ISSUE THREAD

**Issue by jimthompson5802** [pytorch/pytorch#108956]
### 🐛 Describe the bug

On cpu, `nn.LayerNorm` outputs a tensor of all zeros for single column batch in the `torch` nightly version.  The all zero output tensor affects parameter updates.

This issue **does not occur** if there are more than 2 or more columns or in the GA version of `torch`.

Following code demonstrates the issue:
```python
import torch
from torch import nn, functional as F

DIM2_SIZE = 1

if __name__ == "__main__":
    print(f"Torch version: {torch.__version__}")
    torch.manual_seed(42)
    inputs = torch.randn(16, DIM2_SIZE, dtype=torch.float32)

    layer_norm = nn.LayerNorm(DIM2_SIZE)

    outputs = layer_norm(inputs)

    print(f"layer norm output:\n{outputs}")
```
**Output for DIM2SIZE=1**
```
Torch version: 2.2.0.dev20230909+cpu
layer norm output:
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<NativeLayerNormBackward0>)
```

**Output for `DIM2_SIZE=2`**
```
Torch version: 2.2.0.dev20230909+cpu
layer norm output:
tensor([[ 0.9999, -0.9999],
        [ 1.0000, -1.0000],
        [ 1.0000, -1.0000],
        [ 1.0000, -1.0000],
        [-1.0000,  1.0000],
        [ 1.0000, -1.0000],
        [-0.9993,  0.9993],
        [-1.0000,  1.0000],
        [ 1.0000, -1.0000],
        [-1.0000,  1.0000],
        [-1.0000,  1.0000],
        [-1.0000,  1.0000],
        [-0.9392,  0.9392],
        [-1.0000,  1.0000],
        [-0.9997,  0.9997],
        [-1.0000,  1.0000]], grad_fn=<NativeLayerNormBackward0>)
```

**Output for `DIM2_SIZE=4`**
```
TTorch version: 2.2.0.dev20230909+cpu
layer norm output:
tensor([[ 0.8716,  0.5928,  0.2209, -1.6853],
        [ 1.3440, -0.7473,  0.5552, -1.1519],
        [-0.4622,  1.6423, -0.1469, -1.0332],
        [-0.6401, -0.3735, -0.7050,  1.7186],
        [ 1.5784, -0.6330, -1.0476,  0.1023],
        [-1.6203,  0.4198,  0.1115,  1.0889],
        [ 0.4952,  0.5527, -1.7281,  0.6801],
        [-0.7452, -0.1393, -0.7894,  1.6739],
        [-1.0156, -0.5789, -0.0280,  1.6225],
        [ 0.9789, -0.5945,  0.9511, -1.3355],
        [-1.1176,  1.6082, -0.3940, -0.0965],
        [-0.7608,  1.6873, -0.7323, -0.1942],
        [-1.1710, -0.7253,  0.5579,  1.3384],
        [-0.3374,  1.7132, -0.7355, -0.6403],
        [-1.6057,  0.2972,  0.1657,  1.1428],
        [-0.4859,  1.1295, -1.3897,  0.7461]],
       grad_fn=<NativeLayerNormBackward0>)
```

This issue may be related to 
* https://github.com/pytorch/pytorch/issues/108072
* https://github.com/pytorch/pytorch/pull/108089

### Versions

Collecting environment information...
PyTorch version: 2.2.0.dev20230909+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep  7 2023, 13:22:22) [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.15.49-linuxkit-pr-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              1
Core(s) per socket:              12
Socket(s):                       1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Stepping:                        13
CPU MHz:                         2303.966
BogoMIPS:                        4607.93
L1d cache:                       384 KiB
L1i cache:                       384 KiB
L2 cache:                        3 MiB
L3 cache:                        16 MiB
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, STIBP: disabled
Vulnerability Srbds:             Unknown: Dependent on hypervisor status
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 avx2 smep bmi2 erms rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 arat

Versions of relevant libraries:
[pip3] botorch==0.9.2
[pip3] gpytorch==1.11
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.1
[pip3] torch==2.2.0.dev20230909+cpu
[pip3] torchaudio==2.2.0.dev20230909+cpu
[pip3] torchinfo==1.8.0
[pip3] torchmetrics==0.11.4
[pip3] torchtext==0.6.0
[pip3] torchvision==0.17.0.dev20230909+cpu
[conda] Could not collect

**Comment by tringwald** [comment]
I'm not sure if I understand the problem correctly, but isn't a 0 tensor the expected result? Your input tensor has only 1 value per batch element, from which `LayerNorm` would subtract the mean. The mean of a 1 element tensor is the element itself, so you'd subtract the element from itself which is 0. If you observed non-zero values before, those were probably a result of numerical issues and were fixed in #108089.

**Comment by jimthompson5802** [comment]
@tringwald 
The input tensor does not have a single value.  here is the updated program to reproduce the error that displays the input tensor.
```python
import torch
from torch import nn, functional as F

DIM2_SIZE = 1

if __name__ == "__main__":
    print(f"Torch version: {torch.__version__}")
    torch.manual_seed(42)
    inputs = torch.randn(16, DIM2_SIZE, dtype=torch.float32)
    print(f"inputs:\n{inputs}")

    layer_norm = nn.LayerNorm(DIM2_SIZE)

    outputs = layer_norm(inputs)

    print(f"layer norm output:\n{outputs}")
```

Here is the output from the program
```
Torch version: 2.2.0.dev20230909+cpu
inputs:
tensor([[ 1.9269],
        [ 1.4873],
        [ 0.9007],
        [-2.1055],
        [ 0.6784],
        [-1.2345],
        [-0.0431],
        [-1.6047],
        [-0.7521],
        [ 1.6487],
        [-0.3925],
        [-1.4036],
        [-0.7279],
        [-0.5594],
        [-0.7688],
        [ 0.7624]])
layer norm output:
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<NativeLayerNormBackward0>)
```
If the same program is run in Torch 2.0.0, the output from `nn.LayerNorm` is a non-zero tensor.

**Comment by jimthompson5802** [comment]
@tringwald   I re-read your reply.  I misunderstood this part.
>Your input tensor has only 1 value per batch element,

I now understand the point you are making.  Let me discuss this with my colleagues.

**Comment by jimthompson5802** [comment]
@tringwald   Thank you for taking the time for the explanation.

I have a better understanding of the issue and your explanation.  

As I mentioned earlier, the change in output from `nn.LayerNorm` when compared to earlier releases of `torch` caused some confusion.

I appreciate our explanation.  it was helpful.  I'm closing this issue.
