### ISSUE TITLE
UNSTABLE inductor / cuda12.1-py3.10-gcc9-sm80 / test

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#108958]
> Please provide a brief reason on why you need to mark this job as unstable.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by huydhn** [comment]
Not seeing this one flaky anymore, resolving.

**Comment by huydhn** [comment]
https://huggingface.co/ is in maintenance, so marking as unstable as it attempts to download weights from that site and fails, for example, https://hud.pytorch.org/pytorch/pytorch/commit/491c2b46657393a059eada0b9c67bea04efb8198.

The issue can be closed once the site is back up.

**Comment by huydhn** [comment]
The issue has been resolved
