### ISSUE TITLE
[Dynamo] Translate "value in tensor" into something more efficient

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#108904]
### 🐛 Describe the bug

In native CPython, a `value in tensor` tensor must proceed by iterating over tensor using the sequence protocol, testing each element one by one. However, with Dynamo, we can translate this into something more efficient like `torch.any(value == tensor)`, which gives up short circuiting to get a vectorized comparison that also avoids specializing on the numel of tensor. This specialization impedes batch dynamic shapes in https://github.com/pytorch/pytorch/issues/107200

Because `in` is a single bytecode (`COMPARE_OP`) this should be easy to match against in Dynamo.

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by Fidget-Spinner** [comment]
I think it's already doing that though. Or am I mistaken here?

https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/tensor.py#L633-L642

**Comment by ezyang** [comment]
You're right, maybe I misdiagnosed the specialization in the parent issue 🤔
