### ISSUE TITLE
Debugging in forward codes of defined model.

### ISSUE THREAD

**Issue by zwx8981** [pytorch/pytorch#10896]
Hi, I want to debug my model by stepping through lines in model's forward codes. However, when I tried to enter the model, it directly jump into the __call__ method in module.py, how can I reach the forward codes written by myself?

ps: I use Spyder for debugging.

**Comment by SsnL** [comment]
Just use your favorite python debugger. The `__call__` method in module.py will eventually reach your custom `forward` in a few lines.
