### ISSUE TITLE
nn.Flatten gives misleading error on numpy arrays

### ISSUE THREAD

**Issue by martinosorb** [pytorch/pytorch#109033]
### 🐛 Describe the bug

```python
import torch, numpy

F = torch.nn.Flatten()
F(numpy.random.random((32, 2, 32)))
```

Leads to 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martino/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/martino/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/torch/nn/modules/flatten.py", line 46, in forward
    return input.flatten(self.start_dim, self.end_dim)
TypeError: flatten() takes from 0 to 1 positional arguments but 2 were given
```

Which took me a while to debug. I do understand it's not meant to work on Numpy arrays, but this is not the right error message, and mistakes of this kind do happen when writing dataloaders.

### Versions

PyTorch version: 1.13.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.12+ (heads/3.9:f82b32410b, May 17 2022, 18:18:14)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-43-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
CPU family:                      6
Model:                           165
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        2
CPU max MHz:                     5000.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4399.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
Virtualisation:                  VT-x
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        2 MiB (8 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==4.0.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==2.0.8
[pip3] pytorchcv==0.0.67
[pip3] snntorch==0.5.3
[pip3] torch==1.13.1+cu116
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==0.13.1+cu116
[pip3] torchfile==0.1.0
[pip3] torchmetrics==0.9.1
[pip3] torchvision==0.14.1+cu116
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
What is happening here is actually that numpy's `flatten` gets called on your numpy array, with `self.start_dim` and `self.end_dim` on this line :)

https://github.com/pytorch/pytorch/blob/7ac2fcaba7a067da7a995b4d5536c53a01f0f44a/torch/nn/modules/flatten.py#L47

```python
import numpy
numpy.random.random((32, 2, 32)).flatten(1, -1)
```

I agree that this is a confusing error message, but I don't think we should be validating that inputs are torch tensors for all nn modules, as they already have appropriate typehints. 

Perhaps a typechecker/linting might help you catch this error. Let me know if that helps!

**Comment by martinosorb** [comment]
I see, that is not ideal but it makes sense. Thanks.
