### ISSUE TITLE
FSDP + PEFT Prompt Tuning Issue

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#109077]
### 🐛 Describe the bug

In PEFT like prompt tuning, it's common to insert trainable parameters into an LLM while keeping the rest of the model frozen. With FSDP, I'm trying to do the following:

```
model = llama()
apply_prompt_tuning(model) # Adds an extra nn.Embedding parameter, for example
FSDP(model) # note: cannot call FSDP before prompt_tuning, as the embedding won't get sharded
model.load_state_dict(llama_checkpoint, strict=False) # pretrained model checkpoint
```

with strict=False, I'd expect it to ignore the extra embedding I added, and I can just log a warning that it's not initialized (its not expected to be initialized). With local module this works fine, but with FSDP it hits a crash: P824863048

Maybe a fix is to ensure that if `strict=False`, the pre/post load hooks don't crash on missing param FQN issues and instead log warnings.

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin

**Comment by fegin** [comment]
https://github.com/pytorch/pytorch/pull/109116 fixes the issue. Thanks @rohan-varma for implementing the fix.
