### ISSUE TITLE
Cannot assign gradient to HalfTensor

### ISSUE THREAD

**Issue by nehz** [pytorch/pytorch#10901]
## Issue description

Cannot assign gradient to HalfTensor

## Code example

This works:
```
t = th.nn.Parameter(th.tensor([1.])).cuda()
t.grad = th.tensor([1.]).cuda()
```

This fails:
```
t = th.nn.Parameter(th.tensor([1.])).cuda().half()
t.grad = th.tensor([1.]).cuda().half()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: torch.cuda.sparse.HalfTensor is not enabled.
```

## System Info
- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS: Ubuntu 16.04
- PyTorch version: 0.4.1
- Python version: 3.5
- CUDA/cuDNN version: 9.0
- GPU models and configuration: 1080 GTX
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by sebftw** [comment]
I have the same issue.
The problem seem to be that there exists no torch.cuda.sparse.HalfTensor.
Also there is no torch.sparse.HalfTensor. The issue is unrelated to cuda, but it is because your tensor is sparse.

**Comment by gchanan** [comment]
@sebftw I think that issue should be tracked separately, the above issue here has already been resolved.  Could you open a new feature request with that issue which describes why you want to use sparse fp16 tensors?  Thanks!

**Comment by sebftw** [comment]
Alright, I'll do that. Thanks.
