### ISSUE TITLE
AOTAutograd view-replay logic does not handle dtype views well

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#109053]
Example repro from @bertmaher:
```
print(lambda x: x.view(torch.int32)(torch.ones(8))
print(torch.compile(lambda x: x.view(torch.int32), backend="aot_eager")(torch.ones(8)))
# prints:
tensor([1065353216, 1065353216, 1065353216, 1065353216, 1065353216, 1065353216,
        1065353216, 1065353216], dtype=torch.int32)
tensor([1., 1., 1., 1., 1., 1., 1., 1.])
```

The root cause is that:

(1) When we get a graph where an output directly aliases an input (in this case), AOTAutograd needs to manually regenerate the output view at runtime in order to appease the autograd engine

(2) AOTAutograd does this by making an attempt to re-run the same set of views through the autograd engine's view-replay tracking, but when that fails it falls back to running `as_strided()` (code: https://github.com/pytorch/pytorch/blob/main/torch/_functorch/aot_autograd.py#L669)

`as_strided()` isn't actually sufficient in this case: our inputs and outputs have different dtypes, but `as_strided()` does not perform cross-dtype views. The same is actually true for other metadata changes like e.g.`view_as_real`/`view_as_complex`, which AOTAutograd manually handles.

This is a case that would be fixed automatically if AOTAutograd carefully tracked all view-chains that it saw (which would also improve perf, as per this internal issue: https://fb.workplace.com/groups/147416452503510/posts/1211736186131257/).

That will take a decent amount work though. A simpler fix would be to manually check if the dtypes of the input and output are different before running the `.as_strided()`, and doing the bitcast view manually when that happens.

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @anijain2305

**Comment by ezyang** [comment]
Short term and long term; Brian is signed up for short term

**Comment by jon-chuang** [comment]
Hello @bdhirsh may I know where the view chain logic for tensors is defined?

**Comment by bdhirsh** [comment]
@jon-chuang this slipped a bit but I'm going to send a basic fix that just updates the `as_strided()` fallback code to also check if the dtype is different, and directly call `.view(dtype)` at runtime.

The C++ code that we eventually call when we do `new_base._view_func(view_tensor)` is [here](https://github.com/pytorch/pytorch/blob/main/torch/csrc/autograd/python_variable.cpp#L562C10-L562C24)

For what it's worth - there's a tentative long-term plan to kill this `gen_view_from_base()` runtime logic, and instead try to take the graph that dynamo hands us, and partition it at compile time into:
(1) the main compute that we can compile
(2) the outputs that are views, that we need to run at runtime.

And that will alleviate us from having to worry about either using autograd's view-replay, or from having to manually reconstruct the views ourselves.
