### ISSUE TITLE
UNSTABLE pull / linux-focal-py3.8-clang10 / test (dynamo)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#109034]
same as https://github.com/pytorch/pytorch/issues/109028

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by huydhn** [comment]
Reopen as one of the dynamo job starts failing in trunk https://hud.pytorch.org/pytorch/pytorch/commit/c4a22d6918b7ca218f2712d7e7e147aca7127fa3 without any clear reason.  Reverting doesn't help

**Comment by kit1980** [comment]
This started to fail on https://hud.pytorch.org/pytorch/pytorch/commit/bf20b56e9d40dd005399fce05b3a073d8132e04f
This is related to https://github.com/pytorch/pytorch/issues/114453

**Comment by huydhn** [comment]
Closing the issue to put it back because the job looks ok now after https://github.com/pytorch/pytorch/pull/116165

**Comment by kit1980** [comment]
Reopening because the job is still unstable, with flaky `torch._dynamo.exc.InternalTorchDynamoError: cannot set WRITEABLE flag to True of this array` errors.

**Comment by kit1980** [comment]
Closing as the "cannot set WRITEABLE flag to True of this array" issue is fixed.
