### ISSUE TITLE
[ONNX] Provide an option to not generate `report_dynamo_export.sarif`

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#109137]
### 🚀 The feature, motivation and pitch

When bulk converting or running tests, it would be nice to have an option to not create `report_dynamo_export.sarif` because they get overwritten anyways.

cc @BowenBao

**Comment by thiagocrepaldi** [comment]
I would invert the logic. by default, no sarif is created (production mode), but given an env var or flag, sarif would be generated.
this way we are not too verbose by default, poluting user's environment
