### ISSUE TITLE
Introduce 'backend' concept to torch.export.export API

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#109131]
### 🚀 The feature, motivation and pitch

Currently, ONNX exporter is exposed through `torch.onnx.export`, which was the only “export” API on PyTorch repo until PyTorch 2.0 introduced Dynamo and its great backends.

With the introduction of `torch.export` on PyTorch 2.0, there are 2 `export` APIs, namely `torch.onnx.export` and `torch.export.export`, which might confuse users, especially the existing ONNX users.

We propose a way to allow `torch.export.export` to support multiple backends, similar in principle to the `torch.compile` API, which allow backends to produce, for example, either a `GraphModule` with the default `backend=dynamo` or an `onnx.ModelProto` when `backend="onnx"` is specified, unifying both FX and ONNX export APIs into one.

Backend implementation are separate as it is today and users could register extra backends through `register_backend` or list the available ones through `list_backends`

Below is an example on how a model would be exported with the new API

```python
import torch

def f(x, y):
    return x[0] + y

inp = ([torch.ones(1, 3)], torch.ones(1, 3))

exported_program = torch.export.export(f, inp, backend="dynamo", options={})  # ``backend`` and ``options`` are optionals
output = exported_program(*inp)
```

The PR https://github.com/pytorch/pytorch/pull/109649 roughly implements the backend concept

The ONNX exporter could leverage dynamo under the hood and be exported as below:

```python
import torch

def func(x):
    y = x + 1
    z = y.relu()
    return (y, z)
export_options = torch.onnx.ExportOptions()  # TODO: Maybe we can flatten ExportOption in favor of a dict as dynamo?
exported_onnx = torch.export.export(func, (torch.randn(1, 1, 2),), backend="onnx", options={"export_options":  export_options},
)
```

The PR https://github.com/pytorch/pytorch/pull/109650 adds onnx as a backend using the new API. 

### Additional context

This idea was briefly brainstormed with @msaroufim @kit1980 and @malfet who referred @suo as an important stakeholder.

**Comment by msaroufim** [comment]
Just chiming in here FWIW I think this proposal makes sense, I believe XLA team has also asked for this

It'd be healthiest to have an out of core registration mechanism similarily to torch.compile https://pytorch.org/docs/main/torch.compiler_custom_backends.html#registering-custom-backends

**Comment by angelayi** [comment]
Sorry, for missing this issue! Is this still relevant? 
If so, I have a question: what is needed that is different between the dynamo and onnx outputs? Maybe we can look at those issues?

For context, we were thinking about a backend concept so that different backends (XLA, TensorRT, Edge) can get their own dialects of the graph, but after looking at some examples we realized that this might not be needed because torch.export can return a higher level representation of the graph at just the ATen layer. Then these backends can decompose the graph further to their own opsets. For example, Edge will decompose to the Core ATen opset and do some transformations to get to their dialect, and XLA will do subgraph rewriting on the graph to lower to their own operators.

**Comment by thiagocrepaldi** [comment]
> Sorry, for missing this issue! Is this still relevant? If so, I have a question: what is needed that is different between the dynamo and onnx outputs? Maybe we can look at those issues?
> For context, we were thinking about a backend concept so that different backends (XLA, TensorRT, Edge) can get their own dialects of the graph, but after looking at some examples we realized that this might not be needed because torch.export can return a higher level representation of the graph at just the ATen layer. Then these backends can decompose the graph further to their own opsets. For example, Edge will decompose to the Core ATen opset and do some transformations to get to their dialect, and XLA will do subgraph rewriting on the graph to lower to their own operators.

Hi Angela, the discussion I think it is still relevant.

After https://github.com/pytorch/pytorch/pull/111497 we are experimenting similar path as mentioned above for Edge and XLA. First we use `torch.export.export()` to lower the `torch.nn.Module` to Core Aten opset. Next, we use the produced `torch.export.ExportedProgram` to generate a ONNX graph. ONNX graph has a completely different opset/dtype/data representation of ATen.

We are still working on the differences between dynamo and ONNX, but one characteristic that we already noticed is that we don't have the choice, for instance, of not lifting parameters/buffers as input/output, for example. Another aspect is that python/pytorch have implicit type promotion, but ONNX requires explicit casts. Another aspect that would be useful for us would be having fine control over decomposition, including a mechanism to track decomposition to its parent module (it would be useful to know a lowe level matmul came from the torch.nn.Linear module, for example)
