### ISSUE TITLE
torch.var outputs inf for correction>N

### ISSUE THREAD

**Issue by jay746** [pytorch/pytorch#109186]
### 🐛 Describe the bug

torch.var 

```
x = torch.arange(12, dtype=torch.float32).reshape(1,3,2,2)
torch.var(x, dim=2, correction=3)
```

output:
```
>>> torch.var(x, dim=2, correction=3)
tensor([[[inf, inf],
         [inf, inf],
         [inf, inf]]])
>>> 
```
In above N=2 because dim=2 and above example dim=2 is 2
Now if we increase the correction value greater than dim value i.e. 2 in this case then it result in inf for all element.
But as per formula https://pytorch.org/docs/stable/generated/torch.var.html . it should have negative of summation.

### Versions

Versions
Versions of relevant libraries:
[pip3] flake8==5.0.4
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.3
[pip3] pytorch-lightning==1.9.4
[pip3] torch==2.0.1
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.1
[pip3] torchmetrics==0.11.1

cc @svekars @carljparker @albanD

**Comment by tringwald** [comment]
In the corresponding C++ code,  the factor is actually implemented as `1 / max(0, N - correction)`. This explains the `inf` as `1 / 0 = inf`. I guess we have 3 options here:

- Fix the docs to reflect the `max(0, ...)` part
- Report a warning if `correction >= N` and keep the current `inf` behavior
- Throw an error if `correction >= N` and exit

Additionally, the above problem also applies to `torch.std`.

**Comment by albanD** [comment]
Thanks for looking into this.
I think that updating the doc to have the max(0, ...) is the simplest fix here. Would you be able to send a PR with this update?

**Comment by tringwald** [comment]
> Thanks for looking into this. I think that updating the doc to have the max(0, ...) is the simplest fix here. Would you be able to send a PR with this update?

Sure, I'll prepare a PR later.

**Comment by tringwald** [comment]
While preparing the PR, I noticed some other functions that suffer from a similar problem.

- `torch.var`
- `torch.var_mean`
- `torch.std`
- `torch.std_mean`
- `torch.cov`

Unfortunately, the behavior is slightly inconsistent, as only `torch.cov` throws a `UserWarning` if `correction>=observations`. Maybe we should add that to the other 4 functions too.
```
>>> torch.var(torch.randn(3), correction=3)
tensor(inf)
>>> torch.std(torch.randn(3), correction=3)
tensor(inf)
>>> torch.var_mean(torch.randn(3), correction=3)
(tensor(inf), tensor(-0.4473))
>>> torch.std_mean(torch.randn(3), correction=3)
(tensor(inf), tensor(0.7958))
>>> torch.cov(torch.randn(2, 3), correction=3)
<stdin>:1: UserWarning: cov(): degrees of freedom is <= 0 (Triggered internally at ../aten/src/ATen/native/Correlation.cpp:117.)
tensor([[inf, -inf],
        [-inf, inf]])
```

**Comment by albanD** [comment]
throwing a warning sounds good as well. But that will require a bit more work to add the warning at the right place and add proper testing.
If you have time, please do both. If you have limited time, just updating the doc is the most important change I think.

**Comment by tringwald** [comment]
For now, I created a PR for the docs change only. I'll try working on the warning too, but we can also create a new issue for that.
