### ISSUE TITLE
Code slows down massively when using `.to(device)` with multiple seeds running

### ISSUE THREAD

**Issue by davidireland3** [pytorch/pytorch#109111]
### 🐛 Describe the bug

I have a script that takes about 20 mins to run on my machine when running a single seed at a time. However, when I run several (10) seeds at once, the code slows down massively, taking around 3h to complete. I would expect running several seeds at once to slow down a bit but not so drastically, especially given that each seed uses around 950MB of GPU memory and the machine I am running on has 4 GPU's each with 40GB of memory, and I split the jobs evenly across the GPU's (so a max of 3 seeds on one GPU). I've profiled the code and found that what starts to become a lot slower is the `to.(device)` method. Unfortunately I cannot store all of the data on the GPU since it is an RL problem and so there is no static dataset since we collect new data online. Is there a reason why this becomes so much slower with more seeds running? When profiling the code, the `.to(device)` method goes from using 12107ms to 657858ms. 

The version is 1.12.1. Here is a reproducible script that does essentially what the full script does, just cleaned up a bit: 

```
import math
import numpy as np
import torch
import torch.nn as nn


class MLPResidualLayer(nn.Module):
    def __init__(self, dim):
        super(MLPResidualLayer, self).__init__()

        self.fc1 = nn.Linear(dim, dim)
        self.fc2 = nn.Linear(dim, dim)

    def forward(self, x):
        residual = x
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return residual + x


class Network(nn.Module):
    def __init__(self, state_dim, hidden_dim, num_actions, num_heads):
        super(Network, self).__init__()
        self.input_layer = nn.Linear(state_dim, hidden_dim)
        self.resnet = MLPResidualLayer(hidden_dim)
        self.layer_norm = nn.LayerNorm(hidden_dim)
        self.output_heads = VectorizedLinear(hidden_dim, num_actions, num_heads)
        self.num_heads = num_heads

    def forward(self, x):
        x = self.input_layer.forward(x)
        x = self.layer_norm(self.resnet.forward(x))
        x = x.unsqueeze(dim=0).repeat(self.num_heads, 1, 1)
        vals = self.output_heads.forward(x).transpose(0, 1)
        return vals


class VectorizedLinear(nn.Module):
    def __init__(self, in_features, out_features, ensemble_size):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.ensemble_size = ensemble_size

        self.weight = nn.Parameter(torch.empty(ensemble_size, in_features, out_features))
        self.bias = nn.Parameter(torch.empty(ensemble_size, 1, out_features))

        self.reset_parameters()

    def reset_parameters(self):
        stdv = 1. / math.sqrt(self.weight.size(1))
        self.weight.data.uniform_(-stdv, stdv)
        if self.bias is not None:
            self.bias.data.uniform_(-stdv, stdv)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # input: [ensemble_size, batch_size, input_size]
        # weight: [ensemble_size, input_size, out_size]
        # out: [ensemble_size, batch_size, out_size]
        return x @ self.weight + self.bias


class ReplayBuffer:
    def __init__(self, capacity, state_dim, num_heads, action_dim, batch_size=128):
        self.capacity = capacity
        self.batch_size = batch_size
        self.states = torch.randn(size=(capacity, state_dim), dtype=torch.float)
        self.actions = torch.randint(low=0, high=action_dim, size=(capacity, num_heads), dtype=torch.long)
        self.rewards = torch.randn(size=(capacity, 1), dtype=torch.float)
        self.next_states = torch.randn(size=(capacity, state_dim), dtype=torch.float)
        self.dones = torch.randint(low=0, high=2, size=(capacity, 1), dtype=torch.long)
        self.state_dim = state_dim
        self.num_heads = num_heads

    def sample(self):
        idx = np.random.randint(low=0, high=self.capacity, size=self.batch_size)  # when buffer large the probability of sampling a transition more than once -> 0
        return self.states[idx], self.actions[idx], self.rewards[idx], self.next_states[idx], self.dones[idx]

    def __len__(self):
        return self.capacity


device = 'cuda' if torch.cuda.is_available() else 'cpu'
state_dim = 10
action_dim = 3
num_heads = 6
batch_size = 256

net = Network(state_dim, 512, action_dim, num_heads).to(device)
optimiser = torch.optim.Adam(net.parameters())
loss_fn = nn.HuberLoss()
buffer = ReplayBuffer(100000, state_dim, num_heads, action_dim, batch_size)

for update in range(100000):
    if (update + 1) % 1000 == 0:
        print(f"Update {update + 1}")
    states, actions, rewards, next_states, dones = buffer.sample()
    states = states.to(device)
    actions = actions.to(device)
    rewards = rewards.to(device)
    next_states = next_states.to(device)
    dones = dones.to(device)

    vals = net.forward(states).gather(2, actions.unsqueeze(dim=-1)).squeeze(dim=-1).mean(dim=1)
    with torch.no_grad():
        targets = net.forward(next_states).max(dim=-1)[0].mean(dim=-1, keepdim=True)
        targets = rewards + 0.99 * (1 - dones) * targets
    loss = loss_fn(vals, targets.flatten())
    optimiser.zero_grad()
    loss.backward()
    optimiser.step()
```

### Versions

PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-83-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 10.1.243
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 535.86.10
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             28
On-line CPU(s) list:                0-27
Thread(s) per core:                 2
Core(s) per socket:                 14
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) W-2275 CPU @ 3.30GHz
Stepping:                           7
CPU MHz:                            3300.000
CPU max MHz:                        4800.0000
CPU min MHz:                        1200.0000
BogoMIPS:                           6599.98
Virtualization:                     VT-x
L1d cache:                          448 KiB
L1i cache:                          448 KiB
L2 cache:                           14 MiB
L3 cache:                           19.3 MiB
NUMA node0 CPU(s):                  0-27
Vulnerability Gather data sampling: Mitigation; Microcode
Vulnerability Itlb multihit:        KVM: Mitigation: VMX disabled
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:             Mitigation; Enhanced IBRS
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Mitigation; TSX disabled
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.12.1
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.2.0
[pip3] torch-scatter==2.1.0
[pip3] torch-sparse==0.6.16
[pip3] torchaudio==0.12.1
[pip3] torchrl==0.1.1
[pip3] torchvision==0.13.1
[pip3] torchviz==0.0.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.1           py39h6c91a56_0  
[conda] numpy-base                1.23.1           py39ha15fc14_0  
[conda] pyg                       2.2.0           py39_torch_1.12.0_cu113    pyg
[conda] pytorch                   1.12.1          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-cluster           1.6.0           py39_torch_1.12.0_cu113    pyg
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-scatter           2.1.0           py39_torch_1.12.0_cu113    pyg
[conda] pytorch-sparse            0.6.16          py39_torch_1.12.0_cu113    pyg
[conda] torchaudio                0.12.1               py39_cu113    pytorch
[conda] torchrl                   0.1.1                    pypi_0    pypi
[conda] torchvision               0.13.1               py39_cu113    pytorch
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @ptrblck

**Comment by davidireland3** [comment]
thanks for the reply @janeyx99 

it slows down when moving to the cpu too (i.e. calling `.cpu()`, which is needed when getting the action -- it is initially a tensor but the environment expects numpy array so have to take it back to cpu to execute). I can get exact numbers on this as with the `.to` if it would be helpful. 

I should clarify, when I say several seeds, I mean I run the script 10 times from the terminal, each with a different random seed. So essentially the script is running 10 independent instances. I specify which GPU to use in the usual way, by specifying the device to be gpu:x, where x is an argument I pass from the command line as well as the seed.

**Comment by ptrblck** [comment]
I doubt seeding is related to the issue, which is also a double post from [here](https://discuss.pytorch.org/t/code-slows-down-massively-when-running-multiple-seeds-at-once/188152) with my response.

@davidireland3 is there a reason you are cross-posting the same question and expecting multiple users/devs to debug it?

**Comment by davidireland3** [comment]
@ptrblck I didn’t realise it was an issue to post to the GitHub issues as well as the forums. My friend recommended also posting in the issues after I’d told him I’d posted in the forums, and this was before you responded in my original post.

**Comment by davidireland3** [comment]
so @ptrblck, to clarify, you think the issue is not a PyTorch issue even with the resources I am using to run the jobs?

**Comment by ptrblck** [comment]
> you think the issue is not a PyTorch issue even with the resources I am using to run the jobs?

Yes, this is correct as explained in the discussion board. If your script is already utilizing the GPU properly another process won't have a way to run other kernels in parallel as the compute resources are already exhausted.

A simple example would be a `matmul` using a properly maxed out utilization:
```python
# heavy.py
import torch

x = torch.randn(4*1024, 4*1024, device="cuda")
print("start")

for _ in range(1000):
    torch.matmul(x, x)

torch.cuda.synchronize()
print("done")
```
and another approach simulating a CPU-limited use case where I've added `time.sleep` calls which creates whitespaces between the kernel execution and is thus "starving" the GPU:
```python
# light.py
import torch
import time

x = torch.randn(4*1024, 4*1024, device="cuda")
print("start")

for _ in range(100):
    torch.matmul(x, x)
    time.sleep(0.1)

torch.cuda.synchronize()
print("done")
```

A profile would show exactly this:
`heavy.py` executed in isolation:
![image](https://github.com/pytorch/pytorch/assets/11662379/dbd70e3a-6a11-4dd9-b6af-04b04f49d921)
You can see that the kernels are packed and won't leave room for other kernels execution (assuming the `matmul` kernels use all compute resources, which they usually do). You can also see that the CPU can easily run ahead and schedule all kernels in advance letting the GPU just execute them.

`light.py` execution in isolation:
![image](https://github.com/pytorch/pytorch/assets/11662379/168cbaec-5341-437c-8c52-a9d9507211da)
Here the whitespaces are clearly visible and also note the close calls into the kernel from the CPU compared to the actual kernel execution. This script might allow another process to execute kernels "between" these `matmuls` as the GPU is just waiting.

A quick test running the scripts also verifies this.
`heavy.py` in isolation:
```
time python heavy.py 
start
done

real	0m7.990s
user	0m8.383s
sys	0m1.935s
```
`heavy.py` in two different terminals:
```
# term1
time python heavy.py 
start
done

real	0m14.174s
user	0m14.509s
sys	0m1.875s

# term2
time python heavy.py 
start
done

real	0m14.089s
user	0m14.508s
sys	0m1.871s
```
so the runtime ~doubles.
`light.py` in isolation:
```
time python light.py 
start
done

real	0m11.221s
user	0m1.633s
sys	0m1.950s
```
`light.py` in two terminals:
```
# term1
time python light.py 
start
done

real	0m11.243s
user	0m1.602s
sys	0m1.928s

# term2
time python light.py 
start
done

real	0m11.218s
user	0m1.576s
sys	0m1.901s
```
so the runtime stays the same as both processes can schedule and execute work on the GPU in parallel.

**Comment by davidireland3** [comment]
Thanks for the detailed response @ptrblck. 

My knowledge of these things isn't great, and I'm thinking the way I thought of a GPU is not quite right. I assumed that if the memory is large, and more than large enough to run the seeds, then it would not experience any slow down. But it sounds like even using a matmul uses up some other resource of the GPU which can not be alleviated by having a large memory, which is what causes the bottleneck when multiple seeds are running. 

Is there anything that can be done to fix this? I don't think that I can avoid needing the cpu-gpu interactions since the RL environments are run on CPU and not GPU.

**Comment by ptrblck** [comment]
To learn more about block placement and the limited resources in each SM take a look at this excellent talk by Stephen Jones: [GTC 2022 - How CUDA Programming Works - Stephen Jones, CUDA Architect, NVIDIA](https://www.youtube.com/watch?v=QQceTDjA4f4) in particular the section starting from ~28:50.

> Is there anything that can be done to fix this?

Unsure what exactly you want to "fix". You could of course slow down your code in one script allowing other processes to execute workload on your GPU, but this sounds like a bad idea generally.

**Comment by davidireland3** [comment]
@ptrblck thanks again for the response. I suppose by 'fix' I meant to speed up my code but it from what I understand now, it is not possible -- I think the machine I am using is actually not best suited for what I want to do; it seems I need a cluster of smaller GPU's rather than a few large ones. Thanks for all the info, I will mark this as closed now.
