### ISSUE TITLE
Inductor-Compiled Modules Produce  Incorrect Result When Handling Distributive Property of Multiplication

### ISSUE THREAD

**Issue by ChijinZ** [pytorch/pytorch#109105]
### 🐛 Describe the bug

Inductor compiler produces a wrong result when handling **distributive property of multiplication**. Let's take a look at the code snippet I attached. The M1 module calculates ``(c1 * x * y) + (c1 * x)``, and the M2 module calculates ``(c1 * y + c1) * x``. Obviously, their results should be equal when giving the same tensor as inputs. When running without inductor, they produce identical results. However, when running with inductor, they produce very different results. This inconsistency occurs only when using a specific tensor as inputs. I attached it in the zip.

[pt2_mul_distributive_prop_bug.zip](https://github.com/pytorch/pytorch/files/12586696/pt2_mul_distributive_prop_bug.zip)

The version I used is the official nightly-built version (2.2.0.dev20230911+cu118), installed with the official command ``pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118``.

```python
import copy
import numpy as np
import torch
import pickle

class M1(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.c1 = torch.nn.Parameter(torch.tensor([6], dtype=torch.int8), requires_grad=False)
    def forward(self, *args):
        x = args[0]
        y = args[1]
        c1 = self.c1
        mul = torch.mul(c1, x)
        mul_1 = torch.mul(mul, y)
        add = torch.add(mul_1, mul)
        res = add.to(dtype = torch.float64)
        # res = (c1 * x * y) + (c1 * x)
        return res

class M2(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.c1 = torch.nn.Parameter(torch.tensor([6], dtype=torch.int8), requires_grad=False)
    def forward(self, *args):
        x = args[0]
        y = args[1]
        c1 = self.c1
        mul2 = torch.mul(c1, y)
        add = torch.add(mul2, c1)
        mul3 = torch.mul(add, x)
        res = mul3.to(dtype = torch.float64)
        # res = (c1 * y + c1) * x
        return res

# Obviously, (c1 * x * y) + (c1 * x) = (c1 * y + c1) * x
m1 = M1()
m2 = M2()

# inp_1 = [np.array(5, dtype='int8'), np.random.randn(32, 31, 1, 38, 1).astype('int8')]
special_input = pickle.load(open('./1.pickle', 'rb'))
inp_1 = [v for _, v in special_input.items()]

inp_2 = copy.deepcopy(inp_1)

m_out1 = m1(*[torch.from_numpy(v).to('cpu') for v in inp_1])
m_out2 = m2(*[torch.from_numpy(v).to('cpu') for v in inp_2])

# running without inductor will produce consistent results
np.testing.assert_allclose(m_out1, m_out2, rtol=1e-2, atol=1e-3, err_msg=f"Result mismatch")

opt1 = torch.compile(m1, fullgraph=True, backend='inductor', mode=None)
opt2 = torch.compile(m2, fullgraph=True, backend='inductor', mode=None)
opt_out1 = opt1(*[torch.from_numpy(v).to('cpu') for v in inp_1])
opt_out2 = opt2(*[torch.from_numpy(v).to('cpu') for v in inp_2])

# running with inductor will produce inconsistent results
np.testing.assert_allclose(opt_out1, opt_out2, rtol=1e-2, atol=1e-3, err_msg=f"Result mismatch") # Here will raise assertion failure
```

The assertion message:

```shell
# AssertionError: 
# Not equal to tolerance rtol=0.01, atol=0.001
# Result mismatch
# Mismatched elements: 23578 / 37696 (62.5%)
# Max absolute difference: 256.
# Max relative difference: 1.42222222
#  x: array([[[[[150.],
#           [-46.],
#           [120.],...
#  y: array([[[[[150.],
#           [210.],
#           [120.],...
```

### Versions

Collecting environment information...
PyTorch version: 2.2.0.dev20230911+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.1.10-1-pve-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7742 64-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4500.33
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
Virtualization:                  AMD-V
L1d cache:                       2 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        32 MiB (64 instances)
L3 cache:                        256 MiB (16 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.2.0.dev20230911+cu118
[pip3] torchaudio==2.2.0.dev20230911+cu118
[pip3] torchvision==0.17.0.dev20230911+cu118
[conda] Could not collect

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by leslie-fang-intel** [comment]
Looks like overflow happens when running the imperative path of the code snippet and the specific inputs you shared.
Take the result of first element as example: inputs with `c1=6`, `x=5` and `y[0]=4`
- For the result of imperative path, we got the result at first element as `-106` which is due to the overflow.
- CPP Inductor path, we got the result at first element as `150`.

**Comment by ChijinZ** [comment]
> Looks like overflow happens when running the imperative path of the code snippet and the specific inputs you shared. Take the result of first element as example: inputs with `c1=6`, `x=5` and `y[0]=4`
> 
> * For the result of imperative path, we got the result at first element as `-106` which is due to the overflow.
> * CPP Inductor path, we got the result at first element as `150`.

Looks like a very silent overflow bug in the Inductor. Will developers locate and fix this bug?

**Comment by leslie-fang-intel** [comment]
Thanks for the report this issue @ChijinZ. Since the overflow of int8 should be a undefined behavior which depends on the compiler. I think the results difference between `opt_out1` and `opt_out2` with specific inputs (given by you) are as expected. Take the Index of [0, 0, 0, 1, 0] of  `opt_out1` and `opt_out2` as example:

-  `opt_out1[0, 0, 0, 1, 0] is -46` which has overflow
- `opt_out2[0, 0, 0, 1, 0] is 210` which avoid overflow

- Here is the generated code with CPP backend of Mod1
```

cpp_fused__to_copy_add_mul_0 = async_compile.cpp('''
#include "/tmp/torchinductor_root/ib/cibrnuq56cxamjj4krp4zpjvsirbmlolpbnmomodzyd46huzhdw7.h"
extern "C" void kernel(const signed char* in_ptr0,
                       const signed char* in_ptr1,
                       const signed char* in_ptr2,
                       double* out_ptr0)
{
    {
        #pragma GCC ivdep
        for(long i0=static_cast<long>(0L); i0<static_cast<long>(37696L); i0+=static_cast<long>(1L))
        {
            auto tmp0 = in_ptr0[static_cast<long>(0L)];
            auto tmp1 = in_ptr1[static_cast<long>(0L)];
            auto tmp3 = in_ptr2[static_cast<long>(i0)];
            auto tmp2 = decltype(tmp0)(tmp0 * tmp1);
            auto tmp4 = decltype(tmp2)(tmp2 * tmp3);
            auto tmp5 = tmp4 + tmp2;
            auto tmp6 = static_cast<double>(tmp5);
            out_ptr0[static_cast<long>(i0)] = tmp6;
        }
    }
}
''')
```
Int8 overflow happens in calculation of `tmp4`.
- Here is the generated code with CPP backend of Mod2 
```
cpp_fused__to_copy_add_mul_0 = async_compile.cpp('''
#include "/tmp/torchinductor_root/ib/cibrnuq56cxamjj4krp4zpjvsirbmlolpbnmomodzyd46huzhdw7.h"
extern "C" void kernel(const signed char* in_ptr0,
                       const signed char* in_ptr1,
                       const signed char* in_ptr2,
                       double* out_ptr0)
{
    {
        #pragma GCC ivdep
        for(long i0=static_cast<long>(0L); i0<static_cast<long>(37696L); i0+=static_cast<long>(1L))
        {
            auto tmp0 = in_ptr0[static_cast<long>(0L)];
            auto tmp1 = in_ptr1[static_cast<long>(i0)];
            auto tmp4 = in_ptr2[static_cast<long>(0L)];
            auto tmp2 = decltype(tmp0)(tmp0 * tmp1);
            auto tmp3 = tmp2 + tmp0;
            auto tmp5 = decltype(tmp3)(tmp3 * tmp4);
            auto tmp6 = static_cast<double>(tmp5);
            out_ptr0[static_cast<long>(i0)] = tmp6;
        }
    }
}
''')
```
Int8 overflow should happens in calculation of `tmp5 `. However, since it's flowed by a `static_cast<double>`, we suspect compiler has done some optimization to avoid the overflow. That caused the result difference between `opt_out1` and `opt_out2`.

**Comment by jgong5** [comment]
Seems similar to https://github.com/pytorch/pytorch/issues/108520? Since signed overflow is UD, perhaps we can document this as a known issue?

**Comment by ChijinZ** [comment]
Thanks for the detailed analysis @leslie-fang-intel ! The overflow seems to be the root cause.

**Comment by leslie-fang-intel** [comment]
@ChijinZ I am going to close this issue. Feel free to reopen if any further questions.
