### ISSUE TITLE
403 link served on torch index url

### ISSUE THREAD

**Issue by ddelange** [pytorch/pytorch#109102]
### 🐛 Describe the bug

Hi 👋

```
pip install torch torchmetrics~=1.0.0 --extra-index-url https://download.pytorch.org/whl/cu118
```

Will attempt to download torchmetrics 1.0.3 from the torch index:
https://download.pytorch.org/whl/torchmetrics

The link hosted there will respond with 403 forbidden.

Could you remove that link?

Many thanks!

### Versions

Originally posted at https://github.com/Lightning-AI/torchmetrics/issues/2076

cc @ezyang @gchanan @zou3519 @kadeng

**Comment by janeyx99** [comment]
Related to  https://github.com/pytorch/pytorch/issues/109014

**Comment by janeyx99** [comment]
Also, let's move further discussion to #109014. Closing as duplicate.
