### ISSUE TITLE
NAN appears in the backward results of masked.cumprod on macos

### ISSUE THREAD

**Issue by CaoE** [pytorch/pytorch#109166]
### 🐛 Describe the bug

When we add fp16 support for cumprod on CPU, there is a CI failure on macos for masked.cumprod.  I don't have a MacOS machine to reproduce this issue, so I print the results in the UT defined in test_mps.py. https://github.com/pytorch/pytorch/actions/runs/6166735824/job/16736964541. 
`mps_grad_inputs has nan:  tensor(True, device='mps:0')` NAN appears in the backward results of masked.cumprod on macos.

### Versions

latest main branch.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @kulinseth @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by albanD** [comment]
Hey!
The cumprod backward formula is known to be tricky: https://github.com/pytorch/pytorch/blob/c44f816960249d36acf1fb710abb6e348a5d48d9/torch/csrc/autograd/FunctionsManual.cpp#L802
I would check for which input does this nan appears and the corresponding branch in that function.

**Comment by hvaara** [comment]
Ref #125318

@pytorchbot close
