### ISSUE TITLE
potential typo in torch.searchsorted documentation

### ISSUE THREAD

**Issue by ximmao** [pytorch/pytorch#109298]
### 📚 The doc issue

In https://pytorch.org/docs/stable/generated/torch.searchsorted.html
Function descriptions says when right=False, the _left boundary_ of `sorted sentence` is closed. 

but in the followup table example, it seems to suggest that the _right boundary_ is closed when right=False:

sorted_sequence | right | returned index satisfies
-- | -- | --
1-D | False | sorted_sequence[i-1] < values[m][n]...[l][x] <= sorted_sequence[i]
1-D | True | sorted_sequence[i-1] <= values[m][n]...[l][x] < sorted_sequence[i]
N-D | False | sorted_sequence[m][n]...[l][i-1] < values[m][n]...[l][x] <=sorted_sequence[m][n]...[l][i]
N-D | True | sorted_sequence[m][n]...[l][i-1] <= values[m][n]...[l][x] <sorted_sequence[m][n]...[l][i]

cc @svekars @carljparker

**Comment by Deusy94** [comment]
You're right, I think the inequality is wrong in the table, it should be the other way around.
