### ISSUE TITLE
[dynamo] Disable DDPOptimizer or error out if DDPOptimizer + static_graph is detected

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#109261]
### 🐛 Describe the bug

AFAIK, DDPOptimizer doesn't work with DDP when static_graph=True.

Until we have a fix / better solution, we could probably either warn, error out, or automatically disable DDPOptimizer if we detect static_graph=True. That would help with debugging why DDPOptimizer is erroring out.

### Versions

N/A

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @kiukchung @lucasllc @d4l3k

**Comment by ezyang** [comment]
cc @fegin

**Comment by davidberard98** [comment]
on second thought IDK if this is a good idea, because it sounds like DDP static_graph=True + DDPOptimizer doesn't always error out, so adding this might break existing use cases

**Comment by wconstab** [comment]
can you also add the details of what breaks?

**Comment by zhxchen17** [comment]
Hi @davidberard98 I'm cleaning up the old issues and wondering if you still need this to be addressed? Thanks!

**Comment by davidberard98** [comment]
I'm not planning to work on this
