### ISSUE TITLE
Report name of defining class along side function name in Dynamo logs

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#109236]
### 🐛 Describe the bug

Here's a common log message I see:

```
[rank0]:[2023-09-13 11:54:28,851] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line <listcomp> /data/users/ezyang/b/torchrec/torchrec/distributed/dist_data.py:173 (inline depth: 15)
```

This message is annoying because all it says is `<listcomp>` but what I really wanted to know was what class (and function) I was in. In principle, we should be able to figure this, not from the code object (which doesn't really know what class it was defined in) but from the line number.

A shitty implementation that would do better might look like this: when processing `dist_data.py`, read and parse the Python file, giving a stream of tokens. For every line that precedes an increase of indentation, check if it is `class XXX` or `def XXX`; if so, associate all nested lines with `XXX`. This can be done recursively so you get `XXX.YYY`. The line to class/meth table can be cached so we only have to do this once per file.

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @williamwen42 

### Versions

main

**Comment by anijain2305** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/110190
