### ISSUE TITLE
Mistake in torch.stft formula ?

### ISSUE THREAD

**Issue by jedreky** [pytorch/pytorch#109286]
### 📚 The doc issue

I'm referring to the main formula at https://pytorch.org/docs/stable/generated/torch.stft.html. There is an extra $j$ variable under the exponent, whose meaning is not clear, and I think it is just a typo.

### Suggest a potential alternative/fix

Remove the $j$ variable from the formula.

**Comment by Deusy94** [comment]
It's not a typo. Check the STFT definition, j it's just imaginary number, where `j*j=-1`

**Comment by jedreky** [comment]
Oops, my bad, sorry, I forgot some people use j to denote the imaginary unit...
