### ISSUE TITLE
2.1.0RC CPU binary generated import errors 

### ISSUE THREAD

**Issue by nWEIdia** [pytorch/pytorch#109307]
Command I ran: 
 pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/test/cpu 

Environment: pip virtualenv (python3.10.6)  on ubuntu 22.04.2 LTS

Error: 

/torch/autograd/__init__.py", line 446, in <module>
    from torch._C._autograd import (
ImportError: cannot import name '_get_sequence_nr' from 'torch._C._autograd' (unknown location)

cc @seemethere @malfet

**Comment by malfet** [comment]
And I can not reproduce it with venv as well:
```
%  docker run --rm -it ubuntu:22.04 bash -c "apt update; apt install -y python3-venv; python3 -mvenv foobar; source foobar/bin/activate; pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/test/cpu; python3 -c 'import torch;print(torch.__version__, torch.__file__)'"
```

**Comment by nWEIdia** [comment]
Thanks @malfet, looks like this is not a generic error. My particular container still errored out, might be an env issue in that customized container. I will use ubuntu:22.04 container for now.
