### ISSUE TITLE
opinfo test for linalg.eig is not correctly set up

### ISSUE THREAD

**Issue by int3** [pytorch/pytorch#109353]
Per https://github.com/pytorch/pytorch/pull/109165, the gradient computation is failing given the sample inputs, erroring out in the aten code. The aforementioned PR simply sets `check_gradient` to False, but we should have a more thorough fix.

It's unclear to me whether the issue is with the sample inputs, or with the supported backwards dtypes. Hope someone more knowledgeable about linalg.eig can pick this up!

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by lezcano** [comment]
About
Both the eager and compiled versions fail with the following message
when trying to compute the grad:

RuntimeError: linalg_eig_backward: The eigenvectors in the complex
case are specified up to multiplication by e^{i phi}. The specified
loss function depends on this quantity, so it is ill-defined.

Have a look at how we fix this in the opinfo of the SVD, which has a similar issue. 

Feel free to ping me if you get stuck.

**Comment by lezcano** [comment]
Actually, we already do it using
```
    def out_fn(output):
        return output[0], abs(output[1])
```

I bet the issue is that in inductor we don't use `output_process_fn_grad`. The fix would come from using it before computing the gradient. That would fix quite a few functions. See how we use it on eager as an example.
