### ISSUE TITLE
UnsupportedOperatorError: Exporting the operator 'aten::lgamma' to ONNX opset version 18 is not supported.

### ISSUE THREAD

**Issue by ArnyWu** [pytorch/pytorch#109369]
### 🚀 The feature, motivation and pitch

Unable to export to ONNX a model that uses the operation 'aten::lgamma'.

### Alternatives

I have tried adding the operation to symbolic_opsetxx.py as per [this guide](https://pytorch.org/docs/stable/onnx.html#aten-operators), and see [this issue] https://github.com/pytorch/pytorch/issues/98190 but it won't work.

### Additional context

I have tried 

1.  `operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,`

can load on Netron
[tmodule_model.onnx.zip](https://github.com/pytorch/pytorch/files/12619512/tmodule_model.onnx.zip)

but
> Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from onnx_model.onnx failed:Fatal error: org.pytorch.aten:ATen(-1) is not a registered function/op

2. And this
```python
import onnxscript
from onnxscript.onnx_opset import opset18 as op
# Assuming you use opset18
import torch
import onnx
import torch.onnx
custom_opset = onnxscript.values.Opset(domain="torch_onnx", version=18)


#'LGamma'
@onnxscript.script(custom_opset)
def LGamma(X):
    abs_gamma_x = op.Abs(X)
    output = op.Log(abs_gamma_x)
    return output

def custom_lgamma(g, X):
    return g.onnxscript_op(LGamma, X).setType(X.type())

torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::lgamma",  
    symbolic_fn=custom_lgamma,
    opset_version=18,  
)

```
but 

> /usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/jit_utils.py in onnxscript_op(self, onnx_fn, outputs, *raw_args, **kwargs)
> 		    140         # NOTE(titaiwang): This is using class attributes, and it needs to be updated
> 		    141         # if onnx-script makes any change on these.
> 		--> 142         symbolic_name = f"{onnx_fn.opset.domain}::{onnx_fn.opname}"
> 		    143         opset_version = onnx_fn.opset.version
> 		    144 
> 		
> 		AttributeError: 'OnnxFunction' object has no attribute 'opname'

```python
import torch
import onnx
import torch.onnx
from transformers import AutoTokenizer
import onnx.utils
from onnx import helper, shape_inference

model_path = '/content/drive/MyDrive/CHEF/latent_rationale/chefmodel.pt'
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = torch.load(model_path, map_location=device)
tokenizer = AutoTokenizer.from_pretrained("bert-base-chinese")

batch_size = 1
sequence_length = 128
dummy_input_claim = torch.randint(0, 100, (batch_size, sequence_length), dtype=torch.long).to(device)
dummy_input_evidence = torch.randint(0, 100, (batch_size, 5, sequence_length), dtype=torch.long).to(device)

class WrappedModel(torch.nn.Module):
    def __init__(self, model):
        super(WrappedModel, self).__init__()
        self.model = model

    def forward(self, claim_input, evidence_input):
        labels = torch.empty(1, dtype=torch.long, device=claim_input.device)
        with torch.no_grad():
            batch = (claim_input, evidence_input, labels)
            logits = self.model(batch)
            predictions = self.model.predict(logits)
        return predictions

wrapped_model = WrappedModel(model)
wrapped_model.train(False)
wrapped_model.eval()

for p in wrapped_model.parameters():
   p.requires_grad_(False)

dummy_input = (dummy_input_claim, dummy_input_evidence)

#tmodule = torch.jit.trace(wrapped_model , dummy_input)
#smodule = torch.jit.script(wrapped_model)
# to onnx
torch.onnx.export(wrapped_model,
         dummy_input,
         'onnx_model.onnx',
         export_params=True,
         verbose=True,
         input_names=["claim_input", "evidence_input"],
         output_names=["output"],
         opset_version=18,
         #operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
         #custom_opsets = {"torch.onnx": 18},
                  )

onnx_model = onnx.load('./onnx_model.onnx')  # load onnx model
onnx.checker.check_model(onnx_model)  # check onnx model
print(onnx.helper.printable_graph(onnx_model.graph))  # print a human readable model
```

**Comment by justinchuby** [comment]
@titaiwangms looks like we removed opname or something? Do we need to add it back for bc?

**Comment by justinchuby** [comment]
@ArnyWu thanks for testing different solutions. Could you share your PyTorch version?

**Comment by justinchuby** [comment]
To unblock you may do

```
import torch
import onnx
import torch.onnx


def custom_lgamma(g, X):
    return g.op("Log", g.op("Abs", X))

torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::lgamma",  
    symbolic_fn=custom_lgamma,
    # note op sets > 17 is not yet fully supported by the torch.onnx.export converter. You may also test out torch.onnx.dynamo_export for opset 18
    opset_version=17,  
)
```

**Comment by ArnyWu** [comment]
> @ArnyWu thanks for testing different solutions. Could you share your PyTorch version?

```
print(torch.__version__)
2.0.1+cu118
```

**Comment by titaiwangms** [comment]
The pytorch version is too old to be compatible with your onnxscript version:
https://github.com/pytorch/pytorch/blob/f3d14018430b312ac80d1a829b067f27a719fda6/torch/onnx/_internal/jit_utils.py#L143

It's working with nightly.

**Comment by justinchuby** [comment]
We will be fixing this with https://github.com/microsoft/onnxscript/pull/1062. You should be able to get the updated version with `pip install --upgrade onnxscript` by the end of tomorrow.

**Comment by zmtttt** [comment]
have you sloved？
I meet the same problem，
my onnx.model have generated , i want to verify that how it works
code like:
model_path = 'simple_bev.onnx'
print("--begin inferenceSession--")
session = ort.InferenceSession(model_path)
erro:
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from simple_bev.onnx failed:Fatal error: org.pytorch.aten:instance_norm(-1) is not a registered function/op
