### ISSUE TITLE
DISABLED test_scalar (__main__.TestTensorBoardNumpy)

### ISSUE THREAD

**Issue by cyyever** [pytorch/pytorch#109375]
Platforms: win
This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/test_tensorboard.py%3A%3ATestTensorBoardNumpy%3A%3Atest_scalar)).

**Comment by malfet** [comment]
Probably fixed by https://github.com/pytorch/pytorch/pull/109349
