### ISSUE TITLE
Create static analysis tool to improve ONNX export success

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#109303]
### 🚀 The feature, motivation and pitch

Although the ONNX exportes strives to export the model without code changes on user side, some limitations might arise and changes on user script become inevitable

One way to ease the changes on user side is to create a static analysis tool that identifies unsupported patterns and recommend code changes, possibly even making the changes for the user

Integrations with IDEs, such as Visual Studio Code is a plus

Supporting is a must `torch.onnx.dynamo_export` but supporting `torch.onnx.export` woul;d be a great plus

Tools to consider during planning: https://github.com/pytorch/test-infra/tree/main/tools/torchfix and https://libcst.readthedocs.io/en/latest/

**Comment by justinchuby** [comment]
We will use torch fix and the export report for this purpose.
