### ISSUE TITLE
[onnx exporter] Falcon-7b onnx graph exporter issue from huggingface source

### ISSUE THREAD

**Issue by rui-ren** [pytorch/pytorch#109336]
### 🐛 Describe the bug

I have a question regarding [att_mask](https://github.com/pytorch/pytorch/blob/fa623086732dda539d23cc6f58cb4908f8a7be2c/torch/onnx/symbolic_opset14.py#L184-L199) , When running Falcon model with hugginface source, and I got below error message,

```
Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_utils.py", line 325, in get_exception_as_string
    raise exception
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_graph_execution_manager.py", line 395, in _get_exported_model
    torch.onnx.export(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/onnx/utils.py", line 511, in export
    _export(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/onnx/utils.py", line 1577, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/onnx/utils.py", line 1134, in _model_to_graph
    graph = _optimize_graph(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/onnx/utils.py", line 672, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/onnx/utils.py", line 1919, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 306, in wrapper
    return fn(g, *args, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/onnx/symbolic_opset14.py", line 196, in scaled_dot_product_attention
    raise ValueError(
ValueError: Unsupported type for attn_mask: 5.
```

But when setting the `trust_remote_code=True` and using the source from tiiuae/falcon-7b, there is no onnx exporter issue and I can save falcon-7b graph .onnx file. 

Do you happen to see this issue before? Thanks.

## Replicate the issue:
please run below file:
1. docker pull image from mcr
```
docker pull mcr.microsoft.com/aifx/acpt/stable-ubuntu2004-cu118-py310-torch201
```

2. Install below packages:
```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
python -m pip install --retries 3 --pre onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_nightly_cu118.html
```
also:
```
3.	Peft==0.5.0
4.	datasets==2.13.1
5.	Evaluate==0.4.0
6.	Scikit-learn
7.	Transformers==4.33.1
8.	loralib==0.1.2
9.	Optimum==1.13.1
```

3. Pull the optimum package

```
git pull https://github.com/huggingface/optimum.git
```

`cd optimum/examples/onnxruntime/training/language-modeling`

and run below scripts

```
 time torchrun --nproc_per_node 8 run_clm.py --model_name_or_path tiiuae/falcon-7b --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --do_train --do_eval --output_dir /tmp/falcon --overwrite_output_dir --fp16 --deepspeed $ds_config 2>&1 | tee huggingface_with_onnx_issue.txt
```

You will replicate the bug.

**Comment by titaiwangms** [comment]
It looks like the `attn_mask` for op `scaled_dot_product_attention` is not BOOL, nor FLOAT. Unfortunately, we only support these two types for now. Could you check your source code, and make sure `attention_mask` is either one of the types?

**Comment by rui-ren** [comment]
Hi @titaiwangms , Thank for your response. I wonder if we can support fp16 for `attn_mask`,  

When users define customized attention mask using `dtype=torch.float16`, e.g.
```
from torch.nn import functional as F

float_min = torch.finfo(torch.float16).min

attention_mask_fp16 = (attention_mask * 1.0).masked_fill(attention_mask, float_min).to(torch.float16)

attn_output = F.scaled_dot_product_attention(
                 query_layer_, key_layer_, value_layer_, attention_mask_fp16, 0.0, is_causal=False
 )
```
the onnx graph cannot be exported.

When q, k ,v have the fp16 type, we can support this attn_mask to be fp16 type.

```
elif (
        _type_utils.JitScalarType.from_value(attn_mask)
        == _type_utils.JitScalarType.FLOAT
        in (_type_utils.JitScalarType.FLOAT, _type_utils.JitScalarType.HALF)
```

This can export .onnx graph.

I checked the implementation [here](https://github.com/pytorch/pytorch/blob/12da0c70378b5be9135c6fda62a9863bce4a4818/aten/src/ATen/native/transformers/attention.cpp#L678C1-L680C31) , looks like `attn_mask` with `fp16` dtype can be passed.  Correct me if I miss something. Thanks.

**Comment by titaiwangms** [comment]
I think you are right. We should cover fp16. We will accept your PR when it's ready.

**Comment by rui-ren** [comment]
@titaiwangms  Thanks for your review. Will merge that PR when it's ready.
