### ISSUE TITLE
Maybe sqrt twice？

### ISSUE THREAD

**Issue by wtmlon** [pytorch/pytorch#109366]
### 🐛 Describe the bug

the function `_scaled_dot_product_attention_math` code in https://github.com/pytorch/pytorch/blob/34ddf08f2737025fb1447070fae3087889b2e8bb/aten/src/ATen/native/transformers/attention.cpp#L775 `.sqrt()` the `calculate_scale()` return. However, `calculate_scale()` already call `.sqrt()` inside the function in https://github.com/pytorch/pytorch/blob/0cbca85707eb95ad40babc4edadaf614a5ca86e1/aten/src/ATen/native/transformers/sdp_utils_cpp.h#L57 
Is this a bug?

### Versions

main branch

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg

**Comment by drisspg** [comment]
This is not a big, did you read the comment above this line?
