### ISSUE TITLE
[FSDP] Problem with c10d pickle in distributed run 

### ISSUE THREAD

**Issue by jmzeng** [pytorch/pytorch#109396]
### 🐛 Describe the bug

I'm experiencing an issue where there is a pickle error with multi-node distributed training. The error would happen about 190 steps into training and I've previously trained the same data for over 300 steps on a single node. 

See error below:
```
[...]
train_llm.py", line 213, in pretrain
60     trainer.train()
61   File "/usr/lib/python3/dist-packages/transformers/trainer.py", line 1555, in train
62     return inner_training_loop(
63   File "/usr/lib/python3/dist-packages/transformers/trainer.py", line 1815, in _inner_training_loop
64     for step, inputs in enumerate(epoch_iterator):
65   File "/usr/lib/python3/dist-packages/accelerate/data_loader.py", line 593, in __iter__
66     next_batch, next_batch_info = self._fetch_batches(main_iterator)
67   File "/usr/lib/python3/dist-packages/accelerate/data_loader.py", line 534, in _fetch_batches
68     broadcast_object_list(batch_info)
69   File "/usr/lib/python3/dist-packages/accelerate/utils/operations.py", line 456, in broadcast_object_list
70     torch.distributed.broadcast_object_list(object_list, src=from_process)
71   File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
72     return func(*args, **kwargs)
73   File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 2277, in broadcast_object_list
74     object_list[i] = _tensor_to_object(obj_view, obj_size)
75   File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 1970, in _tensor_to_object
76     return _unpickler(io.BytesIO(buf)).load()
77 _pickle.UnpicklingError: invalid load key, '\x01'.
```

The run is launched using 
`torchrun --nnodes=2 --node_rank=1 --nproc-per-node=8 --rdzv-id=428 --rdzv-backend=c10d --rdzv-endpoint=IP1:1234 train_llm.py`

I am using the SFTTrainer with the ConstantLengthDataset and `packing=True`. 

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] pytorch-lightning==2.0.8
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.0.1+cu118
[pip3] torch-optimizer==0.3.0
[pip3] torchdata==0.6.1
[pip3] torchmetrics==0.11.4
[pip3] torchtext==0.15.2+cpu
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[pip3] triton-pre-mlir==2.0.0
[conda] Could not collect

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

**Comment by awgu** [comment]
@jmzeng Perhaps, this issue is better suited for the HuggingFace transformers repo?

**Comment by rahul003** [comment]
This is not necessarily to do with HF. It's some bug in communication of objects probably. We see the same error through torch/distributed/checkpoint/state_dict_saver.py. Here's the stack trace. Note that this doesn't use HF trainer.

```
 File "/opt/ml/code/checkpoints.py", line 153, in _save
checkpoint.save_state_dict(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 119, in save_state_dict
return distW.all_reduce("write", write_data, finish_checkpoint)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 236, in all_reduce
final_result = self.broadcast_object(result)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 88, in broadcast_object
dist.broadcast_object_list(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2277, in broadcast_object_list
object_list[i] = _tensor_to_object(obj_view, obj_size)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1970, in _tensor_to_object
return _unpickler(io.BytesIO(buf)).load()
_pickle.UnpicklingError: invalid load key, '\x00'.

```

**Comment by jmzeng** [comment]
I was able to save a checkpoint previously with the code so that's why I was wondering if it has to do with pytorch. We're running this from inside docker images if that helps with debugging. I also saw this error from another node, not sure which one came first:

```
File "/root/alpha/medical_coding_research/medical_coding_research/modeling/llms/train_llm.py", line 213, in pretrain
64     trainer.train()
65   File "/usr/lib/python3/dist-packages/transformers/trainer.py", line 1575, in train
66     return inner_training_loop(
67   File "/usr/lib/python3/dist-packages/transformers/trainer.py", line 1853, in _inner_training_loop
68     for step, inputs in enumerate(epoch_iterator):
69   File "/usr/lib/python3/dist-packages/accelerate/data_loader.py", line 593, in __iter__
70     next_batch, next_batch_info = self._fetch_batches(main_iterator)
71   File "/usr/lib/python3/dist-packages/accelerate/data_loader.py", line 534, in _fetch_batches
72     broadcast_object_list(batch_info)
73   File "/usr/lib/python3/dist-packages/accelerate/utils/operations.py", line 456, in broadcast_object_list
74     torch.distributed.broadcast_object_list(object_list, src=from_process)
75   File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
76     return func(*args, **kwargs)
77   File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 2267, in broadcast_object_list
78     broadcast(object_tensor, src=src, group=group)
79   File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
80     return func(*args, **kwargs)
81   File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 1566, in broadcast
82     work = default_pg.broadcast([tensor], opts)
83 RuntimeError: NCCL communicator was aborted on rank 6.  Original reason for failure was: [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=84799, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1809191 milliseconds before timing out.```

**Comment by shijie-wu** [comment]
```
File "/opt/ml/code/checkpoints.py", line 153, in _save
checkpoint.save_state_dict(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 119, in save_state_dict
return distW.all_reduce("write", write_data, finish_checkpoint)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 236, in all_reduce
final_result = self.broadcast_object(result)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 88, in broadcast_object
dist.broadcast_object_list(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2277, in broadcast_object_list
object_list[i] = _tensor_to_object(obj_view, obj_size)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1970, in _tensor_to_object
return _unpickler(io.BytesIO(buf)).load()
_pickle.UnpicklingError: invalid load key, '\x00'.
```
a bit more context about this stack trace: we found that it tends to happen when we overwrite checkpoint to an existing folder. while the following comment mentions that the current implementation assumes `checkpoint path is an empty or non-existing directory`, it's unclear how this would cause a pickle error.
https://github.com/pytorch/pytorch/blob/cd31c170c9838766af0d921af2a8f93436195a49/torch/distributed/checkpoint/filesystem.py#L314-L317
is it possible that the pickle is not properly transferred (e.g. https://stackoverflow.com/a/53306038) so that the error could manifests in different places?

cc @awgu @kumpera (author of the comment above) @yuguo68 (most recent author on `_tensor_to_object`)

**Comment by XilunWu** [comment]
> The error would happen about 190 steps into training and I've previously trained the same data for over 300 steps on a single node.
Is there any hardware update between these 2 runs? Could you also provide the NCCL version?

A temporary fix is to use `gloo` for object communication instead.

**Comment by wz337** [comment]
@jmzeng 
```
I'm experiencing an issue where there is a pickle error with multi-node distributed training. The error would happen about 190 steps into training and I've previously trained the same data for over 300 steps on a single node.
```
Could you also provide the PT version when you were able to train over 300 steps on a single node? Thanks.

**Comment by wz337** [comment]
@jmzeng One more question, for your multi-node distributed training, have you successfully checkpointed prior to 190 steps? 
Would it be possible that you can provide us with a minimum repro?

**Comment by wz337** [comment]
Also, is this during model state_dict checkpoint or optimizer state dict checkpoint?

**Comment by jmzeng** [comment]
@wz337 The pytorch version is 2.0.1+cu118. NCCL version is 2.14.3. To answer the following questions:

1. For your multi-node distributed training, have you successfully checkpointed prior to 190 steps?

Yes, I'm always able to save a checkpoint prior to 190 steps. I've actually been testing on a few different settings and I'm actually starting to think it relates to the DataLoader. It fails at about 381 steps with 1 node, 190 steps with 2 node, and 126 steps with 3 nodes. I did check the data, and there are no empty items and the IterableDataset should not be producing empty items either. 

2. Would it be possible that you can provide us with a minimum repro?

I can try to create one, but this fails after hours of training. 

3. Is this during model state_dict checkpoint or optimizer state dict checkpoint?

It's during neither. I was able to save checkpoints previously and these are not checkpoint steps. 

4. What's your dist.init_process_group method? For example, dist.init_process_group("cpu:gloo,cuda:nccl",...).

I am using `nccl` backend. Can test if this happens with `gloo` backend.

**Comment by jmzeng** [comment]
This issue reminds me of the problem slightly, but not completely related:

https://github.com/pytorch/pytorch/issues/69611

However, I'm using linux. I do notice that the system hangs when I set num_workers to anything greater than 0. So I couldn't test whether it was possible to do `num_workers=1`

**Comment by jmzeng** [comment]
Update: the problem was caused by LlamaTokenizerFast being extremely slow on long sequences. I switched to the default LlamaTokenizer works.

https://github.com/huggingface/transformers/issues/25873
