### ISSUE TITLE
Training results from using MPS backend are poor compared to CPU and CUDA

### ISSUE THREAD

**Issue by wayneisaacuy** [pytorch/pytorch#109457]
### 🐛 Describe the bug

I have a Mac M1 GPU and I've been trying to replicate the results in [this google colab notebook](https://colab.research.google.com/drive/1_X7O2BkFLvqyCdZzDZvV2MB0aAvYALLC) on using a transformer-type architecture for time series forecasting. The notebook comes from [this repo](https://github.com/zhouhaoyi/Informer2020). I'm aware that certain issues regarding mps vs cpu and cuda have been raised in the past, such as [this issue using LSTMs on mps](https://github.com/pytorch/pytorch/issues/92615). This code does not utilize lstm and I'm having a hard time identifying the exact PyTorch method that is causing the problem.

In summary, when I run the training phase in the notebook above, I get bad results using the mps backend compared to my Mac M1 CPU as well as CUDA on google colab. (The speed between mps and cuda is a different issue). This is the training loss that I get:

```
Use GPU: mps
>>>>>>>start training : informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8521
val 2857
test 2857
	iters: 100, epoch: 1 | loss: 0.5028459
	speed: 0.2630s[/iter](https://file+.vscode-resource.vscode-cdn.net/iter); left time: 393.6544s
	iters: 200, epoch: 1 | loss: 0.5656900
	speed: 0.2554s[/iter](https://file+.vscode-resource.vscode-cdn.net/iter); left time: 356.7680s
Epoch: 1 cost time: 68.72129678726196
Epoch: 1, Steps: 266 | Train Loss: 0.5757653 Vali Loss: 1.2751399 Test Loss: 1.0501673
Validation loss decreased (inf --> 1.275140).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.9338713
	speed: 0.6757s[/iter](https://file+.vscode-resource.vscode-cdn.net/iter); left time: 831.7784s
	iters: 200, epoch: 2 | loss: 0.9569200
	speed: 0.2548s[/iter](https://file+.vscode-resource.vscode-cdn.net/iter); left time: 288.1538s
Epoch: 2 cost time: 67.94761419296265
Epoch: 2, Steps: 266 | Train Loss: 0.9442326 Vali Loss: 1.4567285 Test Loss: 1.1148015
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.9309775
	speed: 0.6728s[/iter](https://file+.vscode-resource.vscode-cdn.net/iter); left time: 649.2323s
	iters: 200, epoch: 3 | loss: 1.1810662
	speed: 0.2581s[/iter](https://file+.vscode-resource.vscode-cdn.net/iter); left time: 223.2210s
Epoch: 3 cost time: 68.36700391769409
Epoch: 3, Steps: 266 | Train Loss: 0.9918775 Vali Loss: 1.4783044 Test Loss: 1.1274033
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 1.0169864
	speed: 0.6707s[/iter](https://file+.vscode-resource.vscode-cdn.net/iter); left time: 468.7928s
	iters: 200, epoch: 4 | loss: 0.8940969
	speed: 0.2543s[/iter](https://file+.vscode-resource.vscode-cdn.net/iter); left time: 152.3422s
Epoch: 4 cost time: 67.84642291069031
Epoch: 4, Steps: 266 | Train Loss: 0.9954335 Vali Loss: 1.4753704 Test Loss: 1.1228207
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2857
test shape: (89, 32, 24, 7) (89, 32, 24, 7)
test shape: (2848, 24, 7) (2848, 24, 7)
mse:1.0500280857086182, mae:0.7747534513473511
```

In contrast, the loss obtained using cuda, as shown in the google colab notebook, is 
```
Use GPU: cuda:0
>>>>>>>start training : informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8521
val 2857
test 2857
	iters: 100, epoch: 1 | loss: 0.3484939
	speed: 0.0800s/iter; left time: 119.7995s
	iters: 200, epoch: 1 | loss: 0.3274963
	speed: 0.0773s/iter; left time: 108.0117s
Epoch: 1 cost time: 20.9348361492157
Epoch: 1, Steps: 266 | Train Loss: 0.3885468 Vali Loss: 0.6522534 Test Loss: 0.6147651
Validation loss decreased (inf --> 0.652253).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.2812596
	speed: 0.1925s/iter; left time: 236.9607s
	iters: 200, epoch: 2 | loss: 0.2148246
	speed: 0.0797s/iter; left time: 90.1093s
Epoch: 2 cost time: 21.145679235458374
Epoch: 2, Steps: 266 | Train Loss: 0.2568903 Vali Loss: 0.6256742 Test Loss: 0.5904896
Validation loss decreased (0.652253 --> 0.625674).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.2377600
	speed: 0.1962s/iter; left time: 189.2880s
	iters: 200, epoch: 3 | loss: 0.1902070
	speed: 0.0812s/iter; left time: 70.2002s
Epoch: 3 cost time: 21.539507389068604
Epoch: 3, Steps: 266 | Train Loss: 0.2063076 Vali Loss: 0.6280525 Test Loss: 0.5942183
EarlyStopping counter: 1 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.1939584
	speed: 0.1975s/iter; left time: 138.0229s
	iters: 200, epoch: 4 | loss: 0.1632166
	speed: 0.0813s/iter; left time: 48.7252s
Epoch: 4 cost time: 21.655611753463745
Epoch: 4, Steps: 266 | Train Loss: 0.1804204 Vali Loss: 0.6678267 Test Loss: 0.6165376
EarlyStopping counter: 2 out of 3
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.1675630
	speed: 0.1995s/iter; left time: 86.3623s
	iters: 200, epoch: 5 | loss: 0.1715067
	speed: 0.0826s/iter; left time: 27.5224s
Epoch: 5 cost time: 21.931761741638184
Epoch: 5, Steps: 266 | Train Loss: 0.1663280 Vali Loss: 0.6778610 Test Loss: 0.6354805
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2857
test shape: (89, 32, 24, 7) (89, 32, 24, 7)
test shape: (2848, 24, 7) (2848, 24, 7)
mse:0.5913315415382385, mae:0.5571437478065491
```
The mse and the mae using cuda are much lower than that of mps backend. The plots obtained from cuda approximate much better the actual time series data as well.

The GitHub code is mostly written for cuda but I used grep to search the repo and enabled the device to be 'mps' by adding the following code in the file `exp_basic.py`:

```
def _acquire_device(self):
        if self.args.use_gpu:
            if torch.cuda.is_available():
                os.environ["CUDA_VISIBLE_DEVICES"] = str(
                    self.args.gpu) if not self.args.use_multi_gpu else self.args.devices
                device = torch.device('cuda:{}'.format(self.args.gpu))
                print('Use GPU: cuda:{}'.format(self.args.gpu))
            elif getattr(torch,'has_mps',False):
                os.environ['CUDA_VISIBLE_DEVICES'] = '-1' 
                device = "mps"
                print('Use GPU: mps')
```

I believe the error is in the training stage, perhaps gradient computation, because if I load the neural network weights obtained from training using the CPU, and I evaluate the neural network model with mps backend on the test data (without gradient computations), I can reproduce the output of using cpu on the test data.

I also used grep on the whole repository to find what methods from PyTorch were being utilized to identify the source of discrepancy.

Here's a list of methods I found: Conv1d, LayerNorm, Dropout, init.kaiming_normal_, Embedding, Parameter, Linear, BatchNorm1d, ELU, MaxPool1d, torch.softmax, MSELoss, functional.relu. 

I checked Github issues for any mps backend issues with these methods but I couldn't find any. 

Does anyone have suggestions how I can locate the method that's causing the difference between mps and cpu/cuda?

Thanks!

### Versions

python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.5.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.5.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2a0
[conda] numpy                     1.25.2          py311he598dae_0  
[conda] numpy-base                1.25.2          py311hfbfe69c_0  
[conda] pytorch                   2.0.1                  py3.11_0    pytorch
[conda] torchaudio                2.0.2                 py311_cpu    pytorch
[conda] torchvision               0.15.2          cpu_py311he74fb5d_0

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Thank you for reporting the issue, but it's somewhat hard to debug it as is without a smaller reproducer.
Also, can you please try pytorch-2.1.0 release candidate and let me know if results are any different

**Comment by Happyholic1203** [comment]
Minimal code to reproduce training loss difference:
```python
import torch
import torch.nn as nn
vocab_size = 50304
n_embd = 768
ctxlen = 1024
lm_head = nn.Linear(n_embd, vocab_size, bias=False)

def eval_diff(batch_size):
	torch.manual_seed(1234)
	x = torch.randn(batch_size, ctxlen, n_embd)
	y_cpu = lm_head.to('cpu')(x.to('cpu'))
	y_mps = lm_head.to('mps')(x.to('mps'))
	y_diff = (y_cpu - y_mps.to('cpu'))
	print(f'{batch_size=} -> mean: {y_diff.mean().item():.2f}, std: {y_diff.std().item():.2f}, mean_error_per_cell: {y_diff.abs().mean():.5f}')

eval_diff(batch_size=7) # batch_size=7 -> mean: 0.00, std: 0.00, accumulative_error: 0.00000
eval_diff(batch_size=8) # batch_size=8 -> mean: 0.00, std: 0.00, accumulative_error: 0.00000
# After this point, things will explode: note the cpu-mps difference (their stddev) becomes non-negligible
eval_diff(batch_size=9) # batch_size=9 -> mean: -0.00, std: 0.53, accumulative_error: 0.38577
eval_diff(batch_size=20) # batch_size=20 -> mean: 0.00, std: 0.53, accumulative_error: 0.38575
eval_diff(batch_size=40) # batch_size=40 -> mean: 0.00, std: 0.55, accumulative_error: 0.42468
```

I found out about this problem when I tried to reproduce GPT-2 using [nanoGPT](https://github.com/karpathy/nanoGPT) on my M2 Mac Studio.
The loss always explodes on M2 Mac Studio using MPS, while the **exact same training configuration** always works in NVIDIA GPUs.

To see how severe this issue really is:
```shell
$ git clone https://github.com/karpathy/nanoGPT
$ cd nanoGPT
$ python data/openwebtext/prepare.py
# evaluate loss using CPU
$ python train.py --eval_only=True --compile=False --init_from=gpt2 --eval_iters=1 --device=cpu
...
step 0: train loss 3.1262, val loss 3.1564
# evalute loss using MPS
$ python train.py --eval_only=True --compile=False --init_from=gpt2 --eval_iters=1 --device=mps
...
step 0: train loss 97.8176, val loss 96.7708
```

The losses differ dramatically!
- CPU: `3.1262`
- MPS: `97.8176`

I then traced down the computational graph, and I found out the difference comes from `self.lm_head(x)` in `nanoGPT/model.py:GPT:forward`, so I constructed the above minimal code to reproduce the issue.

My current workaround is to use small batch sizes while using MPS. (with gradient accumulation to simulate large batches)

To see how MPS well behaves when batch size is small:
```shell
$ python train.py --eval_only=True --compile=False --init_from=gpt2 --eval_iters=1 --device=mps --batch_size=4
step 0: train loss 3.0152, val loss 3.0037
$ python train.py --eval_only=True --compile=False --init_from=gpt2 --eval_iters=1 --device=mps --batch_size=8
step 0: train loss 3.1941, val loss 3.3834

# explodes!!!
$ python train.py --eval_only=True --compile=False --init_from=gpt2 --eval_iters=1 --device=mps --batch_size=16
step 0: train loss 111.9918, val loss 111.1984
```

However, this workaround is not satisfiable, because it's giving away the edge of MPS, where CPU RAM = GPU RAM.

Also, I think [this issue](https://github.com/pytorch/pytorch/issues/92615) might be related, too.

**Comment by Happyholic1203** [comment]
Minimal code to reproduce training loss difference:
```python
import torch
import torch.nn as nn
vocab_size = 50304
n_embd = 768
ctxlen = 1024
lm_head = nn.Linear(n_embd, vocab_size, bias=False)

def eval_diff(batch_size):
	torch.manual_seed(1234)
	x = torch.randn(batch_size, ctxlen, n_embd)
	y_cpu = lm_head.to('cpu')(x.to('cpu'))
	y_mps = lm_head.to('mps')(x.to('mps'))
	y_diff = (y_cpu - y_mps.to('cpu'))
	print(f'{batch_size=} -> mean: {y_diff.mean().item():.2f}, std: {y_diff.std().item():.2f}, mean_error_per_cell: {y_diff.abs().mean():.5f}')

eval_diff(batch_size=7) # batch_size=7 -> mean: 0.00, std: 0.00, accumulative_error: 0.00000
eval_diff(batch_size=8) # batch_size=8 -> mean: 0.00, std: 0.00, accumulative_error: 0.00000
# After this point, things will explode: note the cpu-mps difference (their stddev) becomes non-negligible
eval_diff(batch_size=9) # batch_size=9 -> mean: -0.00, std: 0.53, accumulative_error: 0.38577
eval_diff(batch_size=20) # batch_size=20 -> mean: 0.00, std: 0.53, accumulative_error: 0.38575
eval_diff(batch_size=40) # batch_size=40 -> mean: 0.00, std: 0.55, accumulative_error: 0.42468
```

I found out about this problem when I tried to reproduce GPT-2 using [nanoGPT](https://github.com/karpathy/nanoGPT) on my M2 Mac Studio.
The loss always explodes on M2 Mac Studio using MPS, while the **exact same training configuration** always works in NVIDIA GPUs.

To see how severe this issue really is:
```shell
$ git clone https://github.com/karpathy/nanoGPT
$ cd nanoGPT
$ python data/openwebtext/prepare.py
# evaluate loss using CPU
$ python train.py --eval_only=True --compile=False --init_from=gpt2 --eval_iters=1 --device=cpu
...
step 0: train loss 3.1262, val loss 3.1564
# evalute loss using MPS
$ python train.py --eval_only=True --compile=False --init_from=gpt2 --eval_iters=1 --device=mps
...
step 0: train loss 97.8176, val loss 96.7708
```

The losses differ dramatically!
- CPU: `3.1262`
- MPS: `97.8176`

I then traced down the computational graph, and I found out the difference comes from `self.lm_head(x)` in `nanoGPT/model.py:GPT:forward`, so I constructed the above minimal code to reproduce the issue.

My current workaround is to use small batch sizes while using MPS. (with gradient accumulation to simulate large batches)

To see how MPS well behaves when batch size is small:
```shell
$ python train.py --eval_only=True --compile=False --init_from=gpt2 --eval_iters=1 --device=mps --batch_size=4
step 0: train loss 3.0152, val loss 3.0037
$ python train.py --eval_only=True --compile=False --init_from=gpt2 --eval_iters=1 --device=mps --batch_size=8
step 0: train loss 3.1941, val loss 3.3834

# explodes!!!
$ python train.py --eval_only=True --compile=False --init_from=gpt2 --eval_iters=1 --device=mps --batch_size=16
step 0: train loss 111.9918, val loss 111.1984
```

However, this workaround is not satisfiable, because it's giving away the edge of MPS, where CPU RAM = GPU RAM.

Also, I think #92615 might be related, too.

**Comment by Happyholic1203** [comment]
I think the bug is in `nn.Linear`, because when I replace `nn.Linear` with manual matrix multiplication, everything works just fine!

To reproduce:
```python
import torch
import torch.nn as nn
C = 1
T = 1024
for outdim in (20, 50304):
    for B in (1, 10, 20):
        l = nn.Linear(C, outdim, bias=False)
        w = torch.randn(outdim, C)
        x = torch.randn(B, T, C)
        l.weight.data = w
        l_out = {'cpu': l(x), 'mps': l.to('mps')(x.to('mps')).to('cpu')}
        matmul_out = {'cpu': x@w.T, 'mps': (x.to('mps')@w.T.to('mps')).to('cpu')}
        for l_dev in ('cpu', 'mps'):
            for matmul_dev in ('cpu', 'mps'):
                assert l_out[l_dev].allclose(matmul_out[matmul_dev]),\
                    f'nn.Linear in {l_dev} disagrees with manual matrix multiplication in {matmul_dev}: {B=}, {outdim=}, stddev={(l_out[l_dev]-matmul_out[matmul_dev]).std()}'

# AssertionError: nn.Linear in mps disagrees with manual matrix multiplication in cpu: B=10, outdim=50304, stddev=1.4391095638275146
```

**Comment by hvaara** [comment]
@wayneisaacuy are you still able to reproduce this issue with the code you referenced?

I'm unable to reproduce with the code from https://github.com/pytorch/pytorch/issues/109457#issuecomment-1991702158.

```python
import torch
import torch.nn as nn
vocab_size = 50304
n_embd = 768
ctxlen = 1024
lm_head = nn.Linear(n_embd, vocab_size, bias=False)

def eval_diff(batch_size):
	torch.manual_seed(1234)
	x = torch.randn(batch_size, ctxlen, n_embd)
	y_cpu = lm_head.to('cpu')(x.to('cpu'))
	y_mps = lm_head.to('mps')(x.to('mps'))
	y_diff = (y_cpu - y_mps.to('cpu'))
	print(f'{batch_size=} -> mean: {y_diff.mean().item():.2f}, std: {y_diff.std().item():.2f}, mean_error_per_cell: {y_diff.abs().mean():.5f}')

eval_diff(batch_size=7) # batch_size=7 -> mean: 0.00, std: 0.00, accumulative_error: 0.00000
eval_diff(batch_size=8) # batch_size=8 -> mean: 0.00, std: 0.00, accumulative_error: 0.00000
# After this point, things will explode: note the cpu-mps difference (their stddev) becomes non-negligible
eval_diff(batch_size=9) # batch_size=9 -> mean: -0.00, std: 0.53, accumulative_error: 0.38577
eval_diff(batch_size=20) # batch_size=20 -> mean: 0.00, std: 0.53, accumulative_error: 0.38575
eval_diff(batch_size=40) # batch_size=40 -> mean: 0.00, std: 0.55, accumulative_error: 0.42468
```

yields

```
batch_size=7 -> mean: 0.00, std: 0.00, mean_error_per_cell: 0.00000
batch_size=8 -> mean: 0.00, std: 0.00, mean_error_per_cell: 0.00000
batch_size=9 -> mean: 0.00, std: 0.00, mean_error_per_cell: 0.00000
batch_size=20 -> mean: 0.00, std: 0.00, mean_error_per_cell: 0.00000
batch_size=40 -> mean: 0.00, std: 0.00, mean_error_per_cell: 0.00000
```

#### env

```
PyTorch version: 2.5.0a0+git648fc6c
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.30.1
Libc version: N/A

Python version: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.15.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==2.0.1
[pip3] optree==0.12.1
[pip3] torch==2.5.0a0+git8d40458
[pip3] torch-tb-profiler==0.4.3
[pip3] torchvision==0.20.0a0+0d80848
[conda] numpy                     2.0.1                    pypi_0    pypi
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] torch                     2.5.0a0+git8d40458           dev_0    <develop>
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchfix                  0.4.0                    pypi_0    pypi
[conda] torchvision               0.20.0a0+0d80848           dev_0    <develop>
```

**Comment by dpwiz** [comment]
> @wayneisaacuy are you still able to reproduce this issue with the code you referenced?

That case doesn't reproduce for me either, however some models still have skyrocketing loss issues.

**Comment by wayneisaacuy** [comment]
Hi all, I have decided not to run any deep learning code on apple hardware for now. It takes a lot of time to fix installation issues and reproducibility issues like this one. I've resorted to using google colab for the interim.

**Comment by hvaara** [comment]
> > @wayneisaacuy are you still able to reproduce this issue with the code you referenced?
> 
> That case doesn't reproduce for me either, however some models still have skyrocketing loss issues.

@dpwiz It would be very helpful to know which models you're seeing issues with. Please open new issues and include reproduction steps if you have them.

**Comment by hvaara** [comment]
> Hi all, I have decided not to run any deep learning code on apple hardware for now. It takes a lot of time to fix installation issues and reproducibility issues like this one. I've resorted to using google colab for the interim.

@wayneisaacuy Sad to hear that your expectations were not fulfilled, but I understand, and happy you found an alternative that works for you. Thank you for opening the issue! I encourage you to keep the reports coming should you encounter any bugs in the future.

I'll close this issue now as the bug seems to have been fixed, but feel free to reopen if there's anything else that needs to be addressed.

@pytorchbot close

**Comment by hvaara** [comment]
@krober10nd Is it the exact same issue as OP? Do you mind opening a new issue if not? Feel free to link to this one if you think it's related. The new issue template will ask you to post code that can reproduce the issue and also explain how to get the versioning information listed under `Versions` in the original comment. The code you're running and expected vs observed behavior you're seeing would be very helpful in reproducing the issue.

On PyTorch 2.7.0, and the main branch compiled from source, I'm getting the same experience as I posted in https://github.com/pytorch/pytorch/issues/109457#issuecomment-2297399836.

**Comment by hunkycolony-003** [comment]
I am facing the same issue when trying to over fit my nanogpt model on a input of size (4, 32) the issue i less when input size is (4, 6). The initial loss is the same but the model is not optimising at all when using mps, on the other hand, it takes under 10 iterarions to make the loss negligible in cpu
