### ISSUE TITLE
[bug][docs]torch.compile.list_backends() should change to torch.compiler.list_backends()

### ISSUE THREAD

**Issue by GuWei007** [pytorch/pytorch#109451]
### 📚 The doc issue

https://pytorch.org/docs/2.1/torch.compiler.html#torch-compiler-overview
As mentioned above, to run your workflows faster, torch.compile through TorchDynamo requires a backend that converts the captured graphs into a fast machine code. Different backends can result in various optimization gains. The default backend is called TorchInductor, also known as inductor, TorchDynamo has a list of supported backends developed by our partners, which can be see by running **torch.compile.list_backends()** each of which with its optional dependencies.
torch.compile.list_backends() should change to torch.compiler.list_backends()
`
>>> torch.compiler.list_backends()
['aot_ts_nvfuser', 'cudagraphs', 'inductor', 'ipex', 'nvprims_nvfuser', 'onnxrt', 'openxla', 'openxla_eval', 'tvm']
>>> torch.__version__
'2.1.0a0+git6d20b39'
>>> torch.compile.list_backends()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'list_backends'
`

### Suggest a potential alternative/fix

torch.compile.list_backends() should change to torch.compiler.list_backends()

cc @svekars @carljparker @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by malfet** [comment]
Thank you very much for reporting the typo. Yes, it should be change
