### ISSUE TITLE
gdb debug pytorch but Undefined command: "torch-tensor-repr"

### ISSUE THREAD

**Issue by YCB-1027** [pytorch/pytorch#109472]
### 🐛 Describe the bug

@ubuntu:~/Desktop/pytorch/pytorch2/pytorch$ conda activate ptenv
(ptenv) @ubuntu:~/Desktop/pytorch/pytorch2/pytorch$ gdb python

>>> import torch
[New Thread 0x7fffdaf5a700 (LWP 19213)]
[New Thread 0x7fffda759700 (LWP 19214)]
[New Thread 0x7fffd5f58700 (LWP 19215)]
[New Thread 0x7fffd5757700 (LWP 19216)]
[New Thread 0x7fffd2f56700 (LWP 19217)]
[New Thread 0x7fffd0755700 (LWP 19218)]
[New Thread 0x7fffcdf54700 (LWP 19219)]

>>> 
>>> a= torch.Tensor([1,2])
>>> a + a
Thread 1 "python" hit Breakpoint 1, 0x00007fffed5131e0 in at::Tensor::add(at::Tensor const&, c10::Scalar const&) const@plt ()
   from /home/ycb/Desktop/pytorch/pytorch2/pytorch/torch/lib/libtorch_python.so
(gdb) n
Single stepping until exit from function _ZNK2at6Tensor3addERKS0_RKN3c106ScalarE@plt,
which has no line number information.
at::Tensor::add (this=0x7ffff7f0b0f8, other=..., alpha=...)
    at /home/ycb/Desktop/pytorch/pytorch2/pytorch/build/aten/src/ATen/core/TensorBody.h:1658
1658	inline at::Tensor Tensor::add(const at::Tensor & other, const at::Scalar & alpha) const {
(gdb) n
(gdb) n

Thread 1 "python" hit Breakpoint 1, at::Tensor::add (this=0x7ffff7f0b0f8, 
    other=..., alpha=...)
    at /home/ycb/Desktop/pytorch/pytorch2/pytorch/build/aten/src/ATen/core/TensorBody.h:1658
1658	inline at::Tensor Tensor::add(const at::Tensor & other, const at::Scalar & alpha) const {
(gdb) torch-tensor-repr
Undefined command: "torch-tensor-repr".  Try "help".
(gdb) 

### Versions

When I was debugging pytorch, I wanted to obtain the data in the tensor, but when I used the compiled pytorch source code gdb, it prompted me that I couldn't find the torch sensor repr command。I would like to know how to solve this problem or how to obtain the data inside the tensor when I debug CNN.cpp

**Comment by malfet** [comment]
Closing, as it does not sound like a PyTorch issue, but rather a general discussion topic on how to use/debug PyTorch, which would be more appropriate to raise in https://discuss.pytorch.org/

P.S. `torch-tensor-repr` command was implemented by https://github.com/pytorch/pytorch/pull/54339 but it hasn't been updated nor tested in a really long time, but at least adding definition of this function works for me when `gdb` is invoked from `pytorch` folder and folder is added to the safe path as described in 
https://github.com/pytorch/pytorch/blob/0ec9f59f70fc98ed8d71af3c89badc88f083872a/.gdbinit#L6-L9
