### ISSUE TITLE
Investigate Strictness of torch.compile `is_big_gpu`

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#109489]
### 🐛 Describe the bug

The check was introduced in https://github.com/pytorch/pytorch/pull/90738 to fix: https://github.com/pytorch/torchdynamo/issues/2015

However, this causes Triton matmul template codegen not to occur on smaller GPUs (sms < 80), including most people's commercial GPUs.

We make two observations:
1. This check was a hotfix that is too strict for most cases
2. V100 is on the testing path of Triton, so it is likely that this issue is fixed

Hence, my proposal is to get rid of the check entirely, as long as CI passes.

CC @jansel as prev discussed (and original code author)

### Error logs

```
[WARNING] not enough SMs to use max_autotune_gemm mode
```

### Minified repro

Use torch.compile on small GPU

### Versions

<details>

PyTorch version: 2.2.0a0+gitc29c493
Is debug build: False
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.2.0-32-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 12.2.128
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU
Nvidia driver version: 535.86.10
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             20
On-line CPU(s) list:                0-19
Vendor ID:                          GenuineIntel
Model name:                         13th Gen Intel(R) Core(TM) i9-13900H
CPU family:                         6
Model:                              186
Thread(s) per core:                 2
Core(s) per socket:                 14
Socket(s):                          1
Stepping:                           2
CPU max MHz:                        5400.0000
CPU min MHz:                        400.0000
BogoMIPS:                           5990.40
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          544 KiB (14 instances)
L1i cache:                          704 KiB (14 instances)
L2 cache:                           11.5 MiB (8 instances)
L3 cache:                           24 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-19
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] jax-triton==0.1.4
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.2.0a0+git84680cb
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.1.0
[conda] Could not collect

</details>
cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen @ngimel

**Comment by jansel** [comment]
I am now recalling that I was hitting resource exhaustion errors on my RTX 4090 with Triton matmuls at some point.  Though a lot has changed since then, so might be worth retesting.

**Comment by jon-chuang** [comment]
What's the best way to comprehensively test (e.g. benchmark scripts/test suites)? 

Anw I think both the OOM issues and out of shared memory issues can both be fixed with the right autotune params, so as long as autotune ignores such failures and has large enough search space it is bound to succeed 🤔 the other piece might be the choice of grid size.

**Comment by jon-chuang** [comment]
Btw, as a side note, may I ask what the state of matmul kernel fusions is and where it is tracked? I was thinking how simple templated pointwise prologue and epilogue may be a good start.

**Comment by msaroufim** [comment]
Most of our benchmark scripts are here https://github.com/pytorch/pytorch/tree/main/benchmarks/dynamo let me know if you have any questions

Re-heuristics cc @eellison since a lot of people have been asking for us for better support on consumer GPUs, we can add a cloud 4090 to our CI to make this easier

**Comment by jansel** [comment]
For triton matmuls to actually be useful on smaller GPUs we may need new configs.

**Comment by jon-chuang** [comment]
> For triton matmuls to actually be useful on smaller GPUs we may need new configs.

XLA mentions that they need to use a decision tree approach to reduce the search space... :thinking: Wonder if there is a simpler approach.

**Comment by jansel** [comment]
Inductor uses a pretty small matmul search space with only ~10 configs.  If all those configs are too big and just error on consumer cards, then we might only be checking 1 or 2 (or 0) configs.

Perhaps we could start using some the heuristics in upstream Triton: https://github.com/openai/triton/blob/main/python/triton/ops/matmul_perf_model.py

**Comment by jon-chuang** [comment]
Some measurements on matmul on commercial GPU (RTX 4070) indicate that the current configs are not optimal for them at certain sizes of M/N.

https://github.com/pytorch/pytorch/pull/110243

Interestingly, however, it can outperform Triton and cuBLAS on larger sizes.

**Comment by nilreml** [comment]
Temporary fix:

```python
# Put these 4 lines at the top of the main script, before any imports
# TODO: remove once https://github.com/pytorch/pytorch/issues/109489 is resolved
from torch._inductor import utils
utils._use_template_for_cuda = lambda x, y: True
```

Using `torch.compile(..., mode='max-autotune')` this gives me a nice 10-90% training speed increase on a 3080 12GB.

(tested using various model and batch sizes, [nanoGPT](https://github.com/karpathy/nanoGPT), PyTorch 2.2, Python 3.11, Debian 12)

> Remember to use `torch.cuda.synchronize()` just before measuring time when benchmarking

**Comment by jansel** [comment]
Let's update the check to be 3080+ then if it seems to work on that.  Someone want to make the PR to update the check?

**Comment by nilreml** [comment]
> For triton matmuls to actually be useful on smaller GPUs we may need new configs.

Re-opening this since I didn't *really* solve the issue at hand (though it does help, thanks @jansel):
Where may I find those triton-related GEMM autotuning configs?

I suspect there are some improvements to performance-to-compilation time trade-offs left on the table and I'd like to have a stab at it.

**Comment by jansel** [comment]
@nilreml feel free to take a look at improving this

**Comment by zhxchen17** [comment]
Hi @nilreml I'm cleaning up the old issues and wondering if there is progress made on this issue? Thanks for looking into this!

**Comment by nilreml** [comment]
Hi @zhxchen17 I've since moved on to bigger GPUs not affected by this, though I believe the original issue still persists.

**Comment by intexcor** [comment]
The problem is still relevant. Compilation behaves strangely on rtx 4070
