### ISSUE TITLE
RNN Documentation is Confusing / Wrong

### ISSUE THREAD

**Issue by thomasahle** [pytorch/pytorch#109443]
### 📚 The doc issue

The docs on https://pytorch.org/docs/stable/generated/torch.nn.RNN.html say:

> For each element in the input sequence, each layer computes the following function:
> 
> h(t) = tanh(x(t) * W_ih^T + b_ih + h(t-1) * W_hh^T + b_hh)
> 
> Where:
> 
> h(t) is the hidden state at time t.
> x(t) is the input at time t.
> h(t-1) is the hidden state of _the previous layer_ at time t-1 or the initial hidden state at time 0.

I'd like to point out the ambiguity surrounding the term "the previous layer" in the context above. The term "layer" here appears to be inconsistent with the definition used in the "num_layers" argument.

For an RNN with `num_layers=1`, the phrase "hidden state of the previous layer at time t-1" could be misinterpreted. Does this mean that we always refer to the initial hidden state since there's no preceding layer? This would imply the RNN isn't recurrent.

Upon testing a `num_layers=1` RNN, I observed that changing the input at t=1 did indeed influence the output at t=10, confirming the network's recurrent nature. Thus, I suspect the correct phrasing should be that x(t) is taken "from the previous layer".

One last thing: It would be useful to have a bit of information on how the RNN is implemented.
Is there a trick to evaluate it over a whole sequence as a batch operation?
Or is there a python/C loop under the hood, making `L` matrix multiplications sequentially for each layer?

### Suggest a potential alternative/fix

> h(t) is the hidden state at time t.
> x(t) is the input at time t _or output from the previous layer_.
> h(t-1) is the hidden state of _the same layer_ at time t-1 or the initial hidden state at time 0.

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @zou3519

**Comment by vadimkantorov** [comment]
Maybe would be worth of adding in the docs a simplistic for-loop based reference RNN impl (with decomposed laied-out rnn cell code directly in the loop)

**Comment by thomasahle** [comment]
I would find that incredible helpful. I look at the simplistic code in the docs of `scaled_dot_product_attention` all the time.

It would also make it clear why training may be less efficient than with transformers, since each cell has to be computed sequentually.

**Comment by mikaylagawarecki** [comment]
We would accept a PR adding a code snippet (similar to [that in the documentation for SDPA](https://pytorch.org/docs/main/generated/torch.nn.functional.scaled_dot_product_attention.html#torch-nn-functional-scaled-dot-product-attention)) that elucidates this behavior

**Comment by thomasahle** [comment]
The thing is, I don't actually know how the RNN works. That's why I was reading the documentation in the first place!
I suggested the gist as a possible starting point of a snippet. But it should probably be verified by somebody who actually knows the pytorch code itself.
