### ISSUE TITLE
Improve IDE autocomplete for torch.Tensor methods

### ISSUE THREAD

**Issue by fleonce** [pytorch/pytorch#109438]
### 🚀 The feature, motivation and pitch

Currently, PyCharm do not provide autocomplete functionality for methods of the torch.Tensor class other than those used directly in the [torch/_tensor.py](../blob/main/torch/_tensor.py) file:
![image](https://github.com/pytorch/pytorch/assets/8986525/1eedd9ae-facd-46e2-9165-3b546888cc25)

However, when using valid methods for `torch.Tensor` such as `torch.Tensor.topk` the IDE references their own built "Binary Skeletons" which includes suboptimal Type Hints for said functions:
![image](https://github.com/pytorch/pytorch/assets/8986525/4e1e249a-6620-428e-a988-513d8632e1e4)

This issue can be resolved by generating a `torch/_tensor.pyi` file similar to `torch/_C/__init__.pyi` containing the correctly typed method stubs for `torch.Tensor` methods. I have gone ahead and added such functionality in https://github.com/pytorch/pytorch/commit/b02e40cd4ebf335d32271e109743a6cb503f6895 and will create a corresponding pull request.

This allows autocomplete to work properly and adds type information to all `torch.Tensor` methods.

### Alternatives

/

### Additional context

Working autocomplete and type hinting:

![image](https://github.com/pytorch/pytorch/assets/8986525/343e0709-993d-4a88-a146-3e6946ed71ce)
![image](https://github.com/pytorch/pytorch/assets/8986525/a1b3d193-c7d6-4252-9c9a-a132b75bfe10)

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by malfet** [comment]
Thank you for reporting the issue, but it feels like it feels like a PyCharm bug rather than a PyTorch one, as `mypy` correctly identifies the type, i.e. output of the following will be:
```python
import torch
x=torch.rand(3, 3)
reveal_type(x.topk)
```

```shell
% mypy foo.py
foo.py:3: note: Revealed type is "def (k: Union[builtins.int, torch.types.SymInt], dim: builtins.int =, largest: builtins.bool =, sorted: builtins.bool =) -> tuple[torch._tensor.Tensor, torch._tensor.Tensor, fallback=torch.return_types.topk]"
```

**Comment by fleonce** [comment]
While I agree that this seems more like a PyCharm bug, addressing this on the PyTorch side would have the side benefit of increasing visibility of the (then to exist) type hinting python stub `_tensor.pyi` file colocated to the actual _tensor.py file, similar to `return_types.py` and `return_types.pyi`. There also already exists an issue about this on the PyCharm side: https://youtrack.jetbrains.com/issue/PY-49401/PyTorch-tensor-comparison-is-falsely-considered-a-boolean Apparently, this is caused by `_TensorBase` being private and therefore not being considered exportable.

PyCharm errors when trying to import `_TensorBase` from `torch._C`, which is probably connected to the fact that the methods are not resolved correctly.

Is there any reason the method descriptions are located in `torch._C._TensorBase` and not in `torch.Tensor` itself?

**Comment by ezyang** [comment]
It's in TensorBase because of how Tensor is implemented: it's a C bound struct, but then we subclass to add some more methods that are more conveniently implemented in Python.

Maybe we can make TensorBase not have a private name anymore? But we can't easily move it from _C...

**Comment by fleonce** [comment]
To not break backwards compatibility one could also then leave `_TensorBase` as an alias to the new `TensorBase`. I can adjust the PR accordingly, if desired.
