### ISSUE TITLE
Cant compile from scratch with either gcc 5.3.0  or 6.4.0

### ISSUE THREAD

**Issue by hjmangalam** [pytorch/pytorch#10953]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
Can't build with:
Currently Loaded Modulefiles:
  1) anaconda/2.7-4.3.1   2) cudnn/6.0            3) cuda/8.0             4) protobuf/3.6.1       5) gcc/6.4.0

in:
 uname -a
Linux compute-5-7.local 3.10.107-1.el6.elrepo.x86_64 #1 SMP Tue Jun 27 10:57:54 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

Provide a short description.
Can't build from source, using either gcc/5.3.0 or 5.4.0 using the same environent as above.

## Code example
Here's the entire build output:
http://termbin.com/pk29

The last few lines of the output are:
`data/apps/sources/pytorch/torch/lib/tmp_install/include/onnx/onnx_onnx_torch.pb.h:2401:10: error: 'PROTOBUF_CONSTEXPR' does not name a type
   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
          ^~~~~~~~~~~~~~~~~~
/data/apps/sources/pytorch/torch/lib/tmp_install/include/onnx/onnx_onnx_torch.pb.h:2542:10: error: 'PROTOBUF_CONSTEXPR' does not name a type
   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
          ^~~~~~~~~~~~~~~~~~
/data/apps/sources/pytorch/torch/lib/tmp_install/include/onnx/onnx_onnx_torch.pb.h:5828:121: error: expected class-name before '{' token
 template <> struct is_proto_enum< ::onnx_torch::AttributeProto_AttributeType> : ::google::protobuf::internal::true_type {};
                                                                                                                         ^
/data/apps/sources/pytorch/torch/lib/tmp_install/include/onnx/onnx_onnx_torch.pb.h:5833:113: error: expected class-name before '{' token
 template <> struct is_proto_enum< ::onnx_torch::TensorProto_DataType> : ::google::protobuf::internal::true_type {};
                                                                                                                 ^
/data/apps/sources/pytorch/torch/lib/tmp_install/include/onnx/onnx_onnx_torch.pb.h:5838:100: error: expected class-name before '{' token
 template <> struct is_proto_enum< ::onnx_torch::Version> : ::google::protobuf::internal::true_type {};
                                                                                                    ^
cc1plus: warning: unrecognized command line option '-Wno-stringop-overflow'
cc1plus: warning: unrecognized command line option '-Wno-zero-length-array'
error: command '/data/apps/gcc/6.4.0/bin/gcc' failed with exit status 1
`

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

The script fails immediately - no torch, which I expected to be included in the pytorch distribution..?

(or fill out the checklist below manually).

You can get the script and run it with:

- PyTorch or Caffe2:
pytorch, recent git checkout

- How you installed PyTorch (conda, pip, source):
python setup.py install

- Build command you used (if compiling from source):

- OS:
CentOS 6.9 Linux, kernel  3.10.107-1.el6.elrepo.x86_64
- PyTorch version:
- Python version:
anaconda/2.7-4.3.1
- CUDA/cuDNN version:

cudnn/6.0            3) cuda/8.0 

- GPU models and configuration:
 NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)

- GCC version (if compiling from source):
5.3.0, 6.4.0
- CMake version:
3.6.1

- Versions of any other relevant libraries:
 protobuf/3.6.1

**Comment by H-Huang** [comment]
Stale issue, reraise if still active.
