### ISSUE TITLE
ConvTranspose2d returns None with FakeTensor 

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#109596]
### 🐛 Describe the bug

```python
import torch
from torch import nn
from torch._subclasses import FakeTensorMode
mode = FakeTensorMode()
large_tensor = torch.randn(64, 16, 32, 32, device="meta")
large_tensor = torch._subclasses.FakeTensor(fake_mode=mode, elem=large_tensor, device="cuda:0")
net = nn.ConvTranspose2d(16, 16, 6).to(device="meta")
for name, p in net.named_parameters():
    fake_p = torch.nn.Parameter(torch._subclasses.FakeTensor(fake_mode=mode, elem=p, device="cuda:0"))
    setattr(net, name, fake_p)
y = net._conv_forward(large_tensor, net.weight, net.bias)
print(type(y))
```

When I manually call the `_conv_forward` of `nn.ConvTranspose2d`, it returns `None`. The call `net(large_tensor)` works properly.

### Versions

cuda 11.8, pytorch main branch.

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @eellison

**Comment by youkaichao** [comment]
@albanD would you mind me adding `_conv_forward` for `nn.ConvTranspose2d/nn.ConvTranspose1d/nn.ConvTranspose3d`? Or are there any reasons that we shouldn't add the method?

**Comment by youkaichao** [comment]
This can be used to invoke convolution with on-the-fly computed weight and bias.

For example, my usage of `_conv_forward` from `nn.Conv2d`:

```python
weight_on_the_fly = conv.weight
bias_on_the_fly = conv.bias
weight_on_the_fly, bias_on_the_fly = fold_bn_into_weights(weight_on_the_fly, bias_on_the_fly, bn_module)
output = conv. _conv_forward(input, weight_on_the_fly, bias_on_the_fly)
```

The above code fails for `nn.ConvTranspose2d` but works for `nn.Conv2d`.

**Comment by albanD** [comment]
You should never call private functions as the end user. Their behavior could change or they could be removed altogether at any time!

If you want functional versions of the nn modules, please look at `torch.nn.functional.*` functions! In your case, I guess you are looking for `torch.nn.functional.conv_transpose2d` ?

**Comment by youkaichao** [comment]
Are another parts of pytorch code (say `_inductor`) considered as end users?

**Comment by albanD** [comment]
In that context, I would say yes. Why would inductor need to rely on that implementation detail of some Module?

**Comment by youkaichao** [comment]
Then I have to duplicate all the code in `_conv_forward` in `_inductor`... Doesn't seem like a very good idea...

**Comment by youkaichao** [comment]
I need this function to run forward of a Conv module with some transformation of its weight.

**Comment by albanD** [comment]
Why not use `torch.nn.utils.stateless.functional_call` ? That is the tool we provide to do that.

**Comment by youkaichao** [comment]
That's a very nice tool! I wasn't aware of it before. I see it is deprecated and `torch.func.functional_call` is now recommended. Is this part of any stable API that I can rely on? Will the semantic change later?

**Comment by albanD** [comment]
Yes that's the same implementation. We're just moving all the "functional" implementations to the `torch.func` namespace. You can rely on it.
