### ISSUE TITLE
[dynamo] torch._dynamo.exc.Unsupported: call_function BuiltinVariable(float) [TensorVariable()] {}

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#109538]
### 🐛 Describe the bug

self explanatory

from exporting emformer at https://github.com/pytorch/pytorch/issues/107188

```
from user code:
   File "/data/users/ezyang/a/torchaudio/torchaudio/models/rnnt_decoder.py", line 293, in forward
    return self._search(enc_out, None, beam_width)
  File "/data/users/ezyang/a/torchaudio/torchaudio/models/rnnt_decoder.py", line 246, in _search
    b_hypos = self._gen_b_hypos(b_hypos, a_hypos, next_token_probs, key_to_b_hypo)
  File "/data/users/ezyang/a/torchaudio/torchaudio/models/rnnt_decoder.py", line 155, in _gen_b_hypos
    score = float(append_blank_score)
```

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jansel** [comment]
```
 score = float(append_blank_score.item())
```
should already be supported, and does the same thing.  So the fix here should be just to trigger our `.item()` handling.

**Comment by nick2432** [comment]
Hi  I would like to work on this issue.

**Comment by oulgen** [comment]
Hi @nick2432 I have already started looking into this and thus assigned it to myself 2 days ago.

**Comment by jon-chuang** [comment]
Also needs to support calling:
`int`, `bool`, `complex`

**Comment by oulgen** [comment]
I'll leave this up-for-grabs as I got occupied with some more urgent work

**Comment by jon-chuang** [comment]
Note that we require `capture_scalar_outputs = True` in order to capture `tensor.item()`

**Comment by jon-chuang** [comment]
For some reason, trying to fix for symint results in data dependent errors. 

```
RuntimeError: Failed running call_function <function sym_int at 0x7fc87454fc70>(*(f0,), **{}):
It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent (and thus we do not know the true value.)  The expression we were trying to evaluate is f0 >= 0 (unhinted: f0 >= 0).  Scroll up to see where each of these data-dependent accesses originally occurred.
```
