### ISSUE TITLE
[dynamo] torch._dynamo.exc.Unsupported: hasattr: ListVariable()

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#109502]
### 🐛 Describe the bug

self explanatory

occurred when porting torch.tensor implementation to Python, the hasattr test is for `__cuda_array_interface__`

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jansel** [comment]
Should be straightforward to fix.  If the ListVariable is a local, we can return `ConstantVariable(hasattr([], name))`.  If the ListVariable is an input, then add a guard and return a `ConstantVariable`.

**Comment by vdesai2014** [comment]
@ezyang can you share a minimal repro?
