### ISSUE TITLE
Wrong example case in TORCH.UNFLATTEN

### ISSUE THREAD

**Issue by JianzheXiao** [pytorch/pytorch#109559]
### 📚 The doc issue

Link https://pytorch.org/docs/stable/generated/torch.unflatten.html

In the third example the doc shows
`>>> torch.unflatten(torch.randn(5, 12, 3), -1, (2, 2, 3, 1, 1)).shape
torch.Size([5, 2, 2, 3, 1, 1, 3])`
which should be incorrect, the correct code should be
`>>> torch.unflatten(torch.randn(5, 12, 3), -2, (2, 2, 3, 1, 1)).shape
torch.Size([5, 2, 2, 3, 1, 1, 3])`

cc @svekars @carljparker

**Comment by malfet** [comment]
Thank you for reporting. Next time you spot a problem like that please do not hesitate to propose a PR with the fix.
