### ISSUE TITLE
`x.to(device="meta")` infinite loops when the python dispatcher is enabled

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#109558]
repro:
```
import torch
with torch._dispatch.python.enable_python_dispatcher():
    x = torch.empty(2)
    y = x.to(device="meta")
```

It seems to infinite loop because:

(1) enabling the python dispatcher enables a bunch of prim decoms
(2) `.to()` calls `prims.device_put()`
(3) `prims.device_put()` calls `aten.to()`

cc @ezyang @mruberry @Lezcano @peterbell10

**Comment by bdhirsh** [comment]
In particular, the meta function for `prims::device_put` calls `aten::to()` [here](https://github.com/pytorch/pytorch/blob/a6d34c60a1a8c7fefebb11f668951e1cbd3f97b3/torch/_prims/__init__.py#L2066), and the meta function for `._to_copy()` (registered from primtorch decomps) is [here](https://github.com/pytorch/pytorch/blob/a6d34c60a1a8c7fefebb11f668951e1cbd3f97b3/torch/_decomp/decompositions.py#L1740) (and calls device_put)

**Comment by eellison** [comment]
Dupe of https://github.com/pytorch/pytorch/issues/103532

**Comment by bdhirsh** [comment]
ah thanks - i'll close
