### ISSUE TITLE
[dynamo] torch._dynamo.exc.Unsupported: torch.* op returned non-Tensor dtype call_function <built-in method promote_types of type object at 0x7f7d9c202160>

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#109508]
### 🐛 Describe the bug

Occurs when you run torch.promote_types in torch.compile'd region. Ran into this when writing polyfill for torch.tensor

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jansel** [comment]
Since we specialize on dtypes, all the args to `promote_types` should be constants we should be able to constant fold through it.

It might be enough to add it to this list:
https://github.com/pytorch/pytorch/blob/92de1d322223fb5584e384971b32c46b93bc2f4b/torch/_dynamo/variables/torch.py#L68-L85
