### ISSUE TITLE
Wrong torch.svd Calculation Result

### ISSUE THREAD

**Issue by yya007** [pytorch/pytorch#10965]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
The torch svd returned an unexpected result in the following case.

## Code example

>>> import numpy as np
>>> a = np.arange(9) - 4
>>> b = a.reshape((3,3))
>>> bt= torch.from_numpy(b.astype(float))
>>> torch.svd(bt)[1]
tensor([7.3485e+00, 2.4495e+00, 3.1251e-17], dtype=torch.float64)

Expected:
7.3485E+0   2.4495E+0  1.8570E-16

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by zou3519** [comment]
What is wrong with this? If the problem is the last element (1.8570E-16 / 3.1251e-17) then the problem looks like floating point error, which is to be expected since you're working with really small numberes.

**Comment by yya007** [comment]
@zou3519 It looks like a floating point error. However, even I changed the tensor type to double, this error still exists. This number is not small enough to overflow in double. In addition, I checked Numpy and the same function in Numpy can get the correct number.

**Comment by zou3519** [comment]
This is what I get from numpy:
```

In [8]: import numpy as np
   ...:
   ...: a = np.arange(9) - 4
   ...: b = a.reshape((3,3))
   ...:
   ...:

In [9]: np.linalg.svd(b)
Out[9]:
(array([[-7.07106781e-01, -5.77350269e-01,  4.08248290e-01],
        [ 2.77656645e-17, -5.77350269e-01, -8.16496581e-01],
        [ 7.07106781e-01, -5.77350269e-01,  4.08248290e-01]]),
 array([7.34846923e+00, 2.44948974e+00, 4.35106603e-18]),
 array([[ 5.77350269e-01,  5.77350269e-01,  5.77350269e-01],
        [ 7.07106781e-01, -1.47944593e-16, -7.07106781e-01],
        [-4.08248290e-01,  8.16496581e-01, -4.08248290e-01]]))
```
which still isn't close to `1.8570E-16`. What are you running?

**Comment by SsnL** [comment]
Pretty sure this is lapack dependent..

**Comment by SsnL** [comment]
Could you post `np.__config__.show()`?

**Comment by yya007** [comment]
>>> np.__config__.show()
atlas_threads_info:
  NOT AVAILABLE
blas_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    extra_compile_args = ['-msse3', '-I/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/System/Library/Frameworks/vecLib.framework/Headers']
    define_macros = [('NO_ATLAS_INFO', 3)]
atlas_blas_threads_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    extra_compile_args = ['-msse3']
    define_macros = [('NO_ATLAS_INFO', 3)]
atlas_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE

**Comment by SsnL** [comment]
Your NumPy is using Accererate, but PyTorch uses MKL. It is natural that they behave slightly differently. Given that the singular value is so small. I would just classify this as precision problem.

**Comment by yya007** [comment]
@SsnL MKL doesn't affect that. Numpy could get correct result when it uses MKL.

**Comment by SsnL** [comment]
@yya007 Why does it not affect that? Accelerate and MKL have different LAPACK implementations. Also multiple LAPACK routine computes SVD (gesvd, gesdd) it is possible that NumPy uses one and PyTorch uses the other.

**Comment by yya007** [comment]
@SsnL I might not explain clearly in the last comment. I let Numpy use MKL and Numpy got the same result as it got before. I thought Numpy and Pytorch should achieve the same results if they both used MKL. However, they still didn't. I attached my new Numpy config. 

I agree that it might be caused by different routines. I just checked Numpy implementations. Numpy seems using gesdd (See https://github.com/numpy/numpy/blob/v1.15.1/numpy/linalg/linalg.py#L8) but we use gesvd in Pytorch (See Declarations.cwrap). 

>>> import numpy as np
>>> np.__config__.show()
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/yuangyao/local/miniconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/yuangyao/local/miniconda/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/yuangyao/local/miniconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/yuangyao/local/miniconda/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/yuangyao/local/miniconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/yuangyao/local/miniconda/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/yuangyao/local/miniconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/yuangyao/local/miniconda/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/yuangyao/local/miniconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/yuangyao/local/miniconda/include']
>>> a = np.arange(9).astype(float) - 4
>>> b = a.reshape((3,3))
>>> np.linalg.svd(b)
(array([[-7.07106781e-01, -5.77350269e-01,  4.08248290e-01],
       [ 8.32667268e-17, -5.77350269e-01, -8.16496581e-01],
       [ 7.07106781e-01, -5.77350269e-01,  4.08248290e-01]]), 
array([7.34846923e+00, 2.44948974e+00, 1.85703319e-16]), 
array([[ 5.77350269e-01,  5.77350269e-01,  5.77350269e-01],
       [ 7.07106781e-01, -5.55111512e-17, -7.07106781e-01],
       [ 4.08248290e-01, -8.16496581e-01,  4.08248290e-01]]))

**Comment by vishwakftw** [comment]
Can this be closed if we have reached an conclusion / impasse?
