### ISSUE TITLE
WHL is incompatible with MacOS 10.12 Sierra with Python 3.6

### ISSUE THREAD

**Issue by shyamalschandra** [pytorch/pytorch#1096]
```
Shyamals-iMac:~ shyamalchandra$ pip install http://download.pytorch.org/whl/torch-0.1.10.post1-cp35-cp35m-macosx_10_6_x86_64.whl 
torch-0.1.10.post1-cp35-cp35m-macosx_10_6_x86_64.whl is not a supported wheel on this platform.
```

Why is this happening when I follow the instructions for OSX, pip, 3.6, and No CUDA support on the pytorch website?

**Comment by soumith** [comment]
are you on a 32-bit mac? (i'm not sure if that's a thing)

**Comment by shyamalschandra** [comment]
@soumith : No, I am using 64-bit MacOS Sierra OS.

**Comment by chenzhekl** [comment]
You are using wheel for Python 3.5 for Python 3.6. The correct `pip install` url should be 

http://download.pytorch.org/whl/torch-0.1.10.post1-cp36-cp36m-macosx_10_7_x86_64.whl
