### ISSUE TITLE
[inductor][cpu] [dynamic shapes][cppwrapper] performance regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#109701]
<p>new_perf_regression 2023-09-17 compare with 2023-09-10 nightly release</p>

<p>Note: multi threads secnario for models above first *, single thread for models between two *</p>

<p>new_perf_regression</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hf_T5_large</td>
      <td>1</td>
      <td>0.956146</td>
      <td>0.495255559</td>
      <td>0.47353662171561406</td>
      <td>329.334921</td>
      <td>1</td>
      <td>1.176139</td>
      <td>0.40203819399999996</td>
      <td>0.472852799452966</td>
      <td>340.740606</td>
      <td>0.81</td>
      <td>1.0</td>
      <td>0.81</td>
      <td>1.03</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>
</table>
<p>SW info</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>0de2555</td>
      <td>d860313</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ffbbebb9</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td>ede4309</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td>45e4b8c</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td>4ac707a</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td>d76d92c</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
      <td>/</td>
    </tr>
  </tbody>
</table>

<p>Repro</p>
<a href=https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh>
  inductor_single_run.sh </a>
<code>
bash inductor_single_run.sh multiple/single inference performance torchbench/huggingface/timm_models model float32 first dynamic cpp 0
</code>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by leslie-fang-intel** [comment]
Suspect same root-cause as https://github.com/pytorch/pytorch/issues/109700 and https://github.com/pytorch/pytorch/issues/109285

**Comment by Valentine233** [comment]
Test `hf_T5_large` with 0917 nightly: `speedup=1.117x`.
Script: `bash inductor_single_test.sh multiple inference performance torchbench hf_T5_large float32 first dynamic cpp 0`.
Could not reproduce.
