### ISSUE TITLE
Issue with pytorch update (version 0.4.1) with cuda9.1.85

### ISSUE THREAD

**Issue by darolt** [pytorch/pytorch#10971]
## Issue description
Pytorch 0.4.0 runs fine on cuda v9.1.85 and python 3.6. However when I update with conda:
conda install pytorch torchvision -c torch
pytorch correctly updates to 0.4.1 but cuda updates to cuda92. Then when running my code I get:
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /opt/conda/conda-bld/pytorch_1532579245307/work/aten/src/THC/THCGeneral.cpp:74

when I run:
conda install pytorch torchvision cuda90 -c torch
or
conda install pytorch torchvision cuda91 -c torch
it always offer me package for cuda92:
added / updated specs: 
    - cuda91
    - pytorch=0.4.1
    - torchvision

pytorch: 0.4.0-py36_cuda9.1.85_cudnn7.1.2_1 pytorch [cuda91] --> 0.4.1-py36_cuda9.2.148_cudnn7.1.4_1 pytorch [cuda92]

## System Info
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX 1060 6GB
GPU 1: Tesla K40c

Nvidia driver version: 387.26
cuDNN version: Probably one of the following:
/usr/local/cuda-9.1/lib64/libcudnn.so
/usr/local/cuda-9.1/lib64/libcudnn.so.7
/usr/local/cuda-9.1/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.1/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.7.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.1.85_cudnn7.1.2_1  [cuda91]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by SsnL** [comment]
cc @soumith

**Comment by soumith** [comment]
@darolt do `conda uninstall cuda90 cuda91 cuda92 pytorch -y`, and then re-run your command. That will fix it.

**Comment by zacharymostowsky** [comment]
So CUDA 9.2 is not compatible with pytorch at this time?

**Comment by soumith** [comment]
@zacharymostowsky it is compatible, with PyTorch v0.4.1. See our website https://pytorch.org for the command to install CUDA 9.2 compatible pytorch

**Comment by xiaoyu1201** [comment]
> @zacharymostowsky it is compatible, with PyTorch v0.4.1. See our website https://pytorch.org for the command to install CUDA 9.2 compatible pytorch

Hi,

I use the Pytorch v 0.4.1, CUDA92, python 3.6.7, torchvision (0.2.1)
but I get this error too:

`cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at ..\aten\src\THC\THCGeneral.cpp:74`

I look forward reading your comments and thank you for your feedback

**Comment by jack17529** [comment]
Can someone please tell why I can't ping the above user?

**Comment by zacharymostowsky** [comment]
@jack17529 The account has been deleted.
