### ISSUE TITLE
Fix torch.utils.benchmark.Timer.timeit while using privateuse1.

### ISSUE THREAD

**Issue by QiuKaida163** [pytorch/pytorch#109776]
### 🐛 Describe the bug

while I use my private device by privateuse1, I will get incorrect time, because torch.utils.benchmark.Timer.timeit can just synchronize in CUDA device.

### Versions

PyTorch version: 1.11.0a0+gitbc2c6ed
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: EulerOS 2.0
GCC version: (GCC) 7.5.0
Clang version: 15.0.5 (clang-5c68a1cb1231 flang-5c68a1cb1231)
CMake version: version 3.16.5
Libc version: glibc-2.17

Python version: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:22:24)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-4.19.90-vhulk2107.1.0.h699.eulerosv2r10.aarch64-aarch64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              1
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       HiSilicon
Model:                           0
Model name:                      Kunpeng-920
Stepping:                        0x1
CPU MHz:                         2600.000
CPU max MHz:                     2600.0000
CPU min MHz:                     200.0000
BogoMIPS:                        200.00
L1d cache:                       8 MiB
L1i cache:                       8 MiB
L2 cache:                        64 MiB
L3 cache:                        128 MiB
NUMA node0 CPU(s):               0-63
NUMA node1 CPU(s):               64-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected

**Comment by ezyang** [comment]
You should just override timer, no?

**Comment by QiuKaida163** [comment]
> You should just override timer, no?

I will close this issue, Because my change was merged. Thanks.
