### ISSUE TITLE
[inductor][cpu] [cppwrapper] performance regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#109703]
<p>new_perf_regression compare with 2023-09-10 nightly release</p>

<p>Note: multi threads secnario for models above first *, single thread for models between two *</p>

<p>new_perf_regression</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>basic_gnn_gin</td>
      <td>1</td>
      <td>1.117776</td>
      <td>0.006346188</td>
      <td>0.007093616637888001</td>
      <td>12.766379</td>
      <td>1</td>
      <td>1.145088</td>
      <td>0.005401989</td>
      <td>0.006185752780032001</td>
      <td>12.959597</td>
      <td>0.98</td>
      <td>0.87</td>
      <td>0.85</td>
      <td>1.02</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>
</table>
<p>SW info</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>0de2555</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ffbbebb9</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
      <td>/</td>
    </tr>
  </tbody>
</table>

<p>Repro</p>
<a href=https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh>
  inductor_single_run.sh </a>
<code>
bash inductor_single_run.sh multiple/single inference performance torchbench/huggingface/timm_models model float32 first static cpp 0
</code>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by chunyuan-w** [comment]
No more regression according to the data of 0925: 0.005152766
@ESI-SYD could you please help double-confirm it?
