### ISSUE TITLE
Profiler should implicitly synchronize gpu devices 

### ISSUE THREAD

**Issue by mwootton** [pytorch/pytorch#109725]
### 🚀 The feature, motivation and pitch

There are currently some unit tests that are flakey due to a race condition when using the profiler.  The pattern typically looks like this:

>             with torch.profiler.profile() as p:
>                 actual = self.func(*inputs, **kwargs)
>             keys = tuple([e.key for e in p.key_averages()])
>             mta_called = any("multi_tensor_apply_kernel" in k for k in keys)

This intent here is to call a function and see if a particular kernel was run.  However it is starting the profiler, dispatching the kernel, then immediately stopping the profiler.  There is no guarantee the kernel executed before the profiler was stopped.  This is a pure race.

The proper fix is to add a 'torch.cuda.synchronize()' inside the context block.  However, it will be an ongoing struggle to identify every unit test that makes this error (including the new ones).  Would it be appropriate to have the context manager add an implicit device synchronize in __exit__?

Generally, a profiler should not be changing the behavior of what it is being profiled.  Would this case be a worthy exception, under principle of least surprise, to benefit casual users?

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98 @jithunnair-amd @pruthvistony 

### Additional context

This seems to be causing random failures for any of the `is_fastpath` tests e.g. `TestForeachCUDA::test_lerp_is_fastpath_True__foreach_lerp_cuda_float32`

**Comment by davidberard98** [comment]
https://github.com/pytorch/pytorch/blob/7e05cd4ecaa037a81c5f54613da68d03f5605b4d/torch/autograd/profiler.py#L294

I believe this already occurs. Do you think you can take a look at why this isn't working in your case?

**Comment by mwootton** [comment]
Most curious.  Will do.  Adding torch.cuda.synchronize() to the sample code above allows it to work every time.  Maybe the actual secret is doing it twice! ;)

**Comment by mwootton** [comment]
Alright, dug a little deeper... and feel silly now.

So yes torch.profiler.__exit__() is calling torch.cuda.synchronize().  It is happening during these test cases that are failing.  A device synchronize is not sufficient here.

What a device synchronize does:

- Block the calling thread until the last op on the gpu completes, then releases the thread immediately, ASAP 

What a device synchronize DOES NOT do:

- Block the calling thread until every listener to the last op gpu completion each gets the callback message and completes whatever subsequent processing they want to do (e.g. log that completion into a profiler record)

So the idea that a hipDeviceSynchronize will ensure the profiling record was collected is pretty silly.  This is a race.  It is probably/possibly a race on cupti as well.  On libroctracer it shows up occasionally with long runs of it "working" and then long runs of it "not working".

I am going to make a kineto change to use a marker to make sure we have all outstanding profiling data up to the instant the profiler was stopped.

**Comment by chaekit** [comment]
Is the test to ensure that a certain kernel was invoked? If so, not sure using profiler is the best way to achieve this since its main purpose is to get performance data.

**Comment by davidberard98** [comment]
@mwootton thanks for the investigation

> Block the calling thread until every listener to the last op gpu completion each gets the callback message and completes whatever subsequent processing they want to do (e.g. log that completion into a profiler record)

curious, do you have an example of this? I don't think I completely understand what scenario this refers to

**Comment by jithunnair-amd** [comment]
> @mwootton thanks for the investigation
> 
> > Block the calling thread until every listener to the last op gpu completion each gets the callback message and completes whatever subsequent processing they want to do (e.g. log that completion into a profiler record)
> 
> curious, do you have an example of this? I don't think I completely understand what scenario this refers to

@davidberard98 I think he is referring to the fact that Kineto profiler relies on roctracer to provide it the information regarding what GPU activity occurred, and just because we call `hipDeviceSynchronize`, it doesn't *guarantee* that all the GPU activity until that point will be recorded by libroctracer in time for the python code to check for the existence of a particular kernel in the GPU activity.
