### ISSUE TITLE
[feature request] `baddbmm` (and `bmm`, `addbmm`) with swap aixs 

### ISSUE THREAD

**Issue by guolinke** [pytorch/pytorch#10988]
currently, these `bmm`s require the input with [k, n, m] x [k, m, p] shape, and product [k, n, p] output.

It that possible to support the swap of first two axis in the first input, so that it is the [n, k, m], and product the [n, k, p] outputs ? 

I know it can be done by permute, but it is somehow not efficient.
Another solution is  use matmul by reshape the first input to [n, k, 1, m], but it often met OOM error, and much slower.

**Comment by fmassa** [comment]
Did you try using `einsum`? I'm not sure we will be introducing such functionality, as it would mean that broadcasting rules would have to be modified in this case, and also we almost always consider the batch dimensions to come first (except in one case)

**Comment by guolinke** [comment]
thanks, I will test the `einsum` .

**Comment by t-vi** [comment]
Currently, `einsum` reduces to `bmm` and will do the permutation for you. So while you won't get a computational advantage from using `einsum`, it probably is the right level of expressiveness (and there isn't much advantage in having arbitrary constructs for permuted axes in terms of expressiveness).
I'm currently investigating the inefficiency pointed out in #10661 - currently it is in both bmm and einsum, and I have a tentative CPU fix, but need to get the GPU dispatching right.

**Comment by fmassa** [comment]
Closing this following the discussion.
Let us know if `einsum` doesn't work for you
