### ISSUE TITLE
Unbacked symint support in cpu inductor backend

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#109897]
### 🐛 Describe the bug

Patch in https://github.com/pytorch/pytorch/pull/109893

The CPU version of nonzero_nobreak test is failing and therefore skipped in this PR. I am not sure why i1 isn't passed into the kernel, Triton inductor doesn't have this problem. It would be great if the cpu inductor crew could take a look.

Repro:

```
python test/inductor/test_torchinductor_dynamic_shapes.py -k test_nonzero_nobreak_cpu
```

### Versions

main

**Comment by leslie-fang-intel** [comment]
Here are some of my finding for why the `i1` is missing as input parameter of the generated kernel:

1. https://github.com/pytorch/pytorch/blob/10c646295d3512237cfb3ab44aa21dfcc9832441/torch/_inductor/codegen/common.py#L1023 only add the var name start as `s` or `ps`. But here the var name is `i1`

2. In the lowering `aten.nonzero.default`, it generates the symbolic size with name start of `i`
CallStack:
* https://github.com/pytorch/pytorch/blob/10c646295d3512237cfb3ab44aa21dfcc9832441/torch/_subclasses/fake_tensor.py#L569
* https://github.com/pytorch/pytorch/blob/10c646295d3512237cfb3ab44aa21dfcc9832441/torch/fx/experimental/symbolic_shapes.py#L2896  which hardcode the name start with `i`

So, it failed to add the size start with `i` as the input parameter of the generated kernel. We will study why triton doesn't have this kind of issue for how to resolve this issue. cc @jgong5

**Comment by leslie-fang-intel** [comment]
Fixed in PR: https://github.com/pytorch/pytorch/pull/110262
