### ISSUE TITLE
torch.mm received an invalid combination of arguments

### ISSUE THREAD

**Issue by mohamedr002** [pytorch/pytorch#10986]
when using that code 

mod= nn.Linear(2,3,bias=False)
x=torch.Tensor([1,1])
print(x)
y=mod(x)

I have got that error 
: torch.mm received an invalid combination of arguments - got (torch.FloatTensor, Variable), but expected one of:
 * (torch.FloatTensor source, torch.FloatTensor mat2)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor, Variable)
 * (torch.SparseFloatTensor source, torch.FloatTensor mat2)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor, Variable).
Please help me

**Comment by SsnL** [comment]
The real error is that `x` is a LongTensor. We should fix the error message.

**Comment by mohamedr002** [comment]
@SsnL,   No x is torch.FloatTensor

**Comment by SsnL** [comment]
Ah my bad. I thought you were using lower case Tensor.

Hmm what's your pytorch version?

**Comment by vishwakftw** [comment]
This seems to work on `master`

**Comment by fmassa** [comment]
You are probably using a PyTorch version prior to 0.4, when Tensors and Variables were different things.
Either update to the latest PyTorch, or wrap your tensor in a `Variable`

**Comment by mohamedr002** [comment]
Thanks it has been solved

Best Regards,
Mohamed Ragab

________________________________
