### ISSUE TITLE
[FSDP ]How to convert sharded_state_dict files into full_state_dict offline without distributed process

### ISSUE THREAD

**Issue by nxphi47** [pytorch/pytorch#109880]
### 🚀 The feature, motivation and pitch

Currently, if I use FSDP with 128 gpus and save checkpoints with sharded_state_dict to avoid gathering the full_state_dict on rank0 for saving, there is no way to obtain the full_state_dict ckpt offline. 

The only way to obtain full_state_dict is to launch the exact 128GPU distributed process with FSDP to load that sharded_state_dict model, then switch to full_state_dict config and save the ckpt to files, which is originally problem we wanted to avoid.

I cannot read the sharded_state_dict file (with `torch.load()`) individually either, except if I launch a 128gpu distributed process to read it. The file contain `ShardedTensor` which requires the same world_size=128 to load.

I would like to have an offline script to read each sharded file and write iterative to a pytorch_model_0.bin, pytorch_model_1.bin, pytorch_model_2.bin...

And then we can load the model with `AutoModelForCausalLM.from_pretrained(...)` by loading each `.bin`

Thanks!

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin

**Comment by wz337** [comment]
You could utilize PyTorch native distributed checkpointing (DCP) for your use case, but note this would require you to launch 128 distributed processes with FSDP and save the checkpointing with DCP again.

I have a tutorial recipe for this, but it's not published yet. The public recipe would be available when 2.1 is released. 
It's a little hard to browse, but you can still refer to DCP_tutorial.rst in this PR. (https://github.com/pytorch/tutorials/pull/2565/files) It shows how you can use DCP to save a FSDP sharded_state_dict and later load into a non FSDP wrapped model in a non-distributed environment.

**Comment by fegin** [comment]
@nxphi47 As @wz337 mentioned, you save `sharded_state_dict` with `DCP`, you can load it back with 1 GPU granted that the memory is enough.

If you want to convert the current checkpoint to full state_dict, you can launch 128 CPU trainers using GLOO. Then each trainer read one file. After getting the `sharded_state_dict` back, you can perform the allgather for each individual tensor.  to get the final state_dict. We have an internal util `torch.distributed.fsdp._shard_utils._gather_state_dict` that performs this gathering but directly using this API for your case will cause CPU OOM. You will have to avoid saving the gathered state_dict on all ranks.
