### ISSUE TITLE
masked_select for meta backend

### ISSUE THREAD

**Issue by albertz** [pytorch/pytorch#109871]
### 🚀 The feature, motivation and pitch

I currently get:
```
NotImplementedError: Could not run 'aten::masked_select' with arguments from the 'Meta' backend
```

I first came here to ask for this being implemented.

While thinking further about it, I realize that this is maybe not really possible? We cannot infer the shape of the result here. Does "meta" support an unknown shape? If not, then instead of raising `NotImplementedError`, I think it should raise some exception which explains this.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @eellison

**Comment by jansel** [comment]
A workaround would be to graph break on the op (call `unimplemented()` in torch/_dynamo/tensor.py or torch/_dynamo/torch.py).  

It should be possible to implement a meta function that introduces an unbacked symint.  The implementation of the `nonzero()` meta function should have an example of this.
