### ISSUE TITLE
Use github.com/apssouza22/chatflow as a conversational layer. It would enable actual API requests to be carried out from natural language inputs.

### ISSUE THREAD

**Issue by GiovanniSmokes** [pytorch/pytorch#109984]
### 🚀 The feature, motivation and pitch

Adding this conversational UI would enable people to 'talk' directly with the backend and API requests to be carried out more effectively. RAG can help with some of the problems function calling by language models face at the moment.

### Alternatives

none

### Additional context

I'm trying to accelerate the adoption of natural language interfaces. https://youtu.be/r3cegH2kviQ

**Comment by albanD** [comment]
Hey!

I'm not sure what is the exact thing you're proposing to do here. If you have a more concrete proposal, feel free to re-open this issue with these details, thanks!
