### ISSUE TITLE
Conv2d returns nan for no reason

### ISSUE THREAD

**Issue by KinWaiCheuk** [pytorch/pytorch#109985]
### 🐛 Describe the bug

I am not sure why Conv2d returns `nan` when my input are all valid values. I have attached `tensor.zip` below which includes `convin.pt` and `input.pt`.

When training my model, `nan` could happen anywhere depending on the seed. Sometimes it takes 1000 steps to have `nan`, sometimes, it takes only 1 step to get `nan`.

```
import torch
convin = torch.load('convin.pt')
coefficients = torch.load('input.pt')
convin(coefficients)
```
[tensors.zip](https://github.com/pytorch/pytorch/files/12710430/tensors.zip)

That's the result you will get when you run the above script.
```
tensor([[[[   nan,    nan,    nan],
          [   nan,    nan,    nan],
          [   nan,    nan,    nan]],

         [[   nan,    nan,    nan],
          [   nan,    nan,    nan],
          [   nan,    nan,    nan]],

         [[   nan,    nan,    nan],
          [   nan,    nan,    nan],
          [   nan,    nan,    nan]],

         [[0.0519, 0.0517, 0.0519],
          [0.0519, 0.0518, 0.0519],
          [0.0519, 0.0518, 0.0518]]],


        [[[   nan,    nan,    nan],
          [   nan,    nan,    nan],
          [   nan,    nan,    nan]],

         [[   nan,    nan,    nan],
          [   nan,    nan,    nan],
          [   nan,    nan,    nan]],
...
          [   nan,    nan,    nan]],

         [[0.0518, 0.0519, 0.0519],
          [0.0520, 0.0516, 0.0521],
          [0.0520, 0.0517, 0.0518]]]], grad_fn=<ConvolutionBackward0>)
```

### Versions

PyTorch version: 2.2.0.dev20230921+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-82-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4070 Ti

Nvidia driver version: 530.41.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             32
On-line CPU(s) list:                0-31
Thread(s) per core:                 1
Core(s) per socket:                 24
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              183
Model name:                         13th Gen Intel(R) Core(TM) i9-13900
Stepping:                           1
CPU MHz:                            2000.000
CPU max MHz:                        5600.0000
CPU min MHz:                        800.0000
BogoMIPS:                           3993.60
Virtualization:                     VT-x
L1d cache:                          576 KiB
L1i cache:                          384 KiB
L2 cache:                           24 MiB
NUMA node0 CPU(s):                  0-31
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] cqt-pytorch==0.0.5
[pip3] numpy==1.24.0
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.2.0.dev20230921+cu121
[pip3] torchaudio==2.2.0.dev20230921+cu121
[pip3] torchmetrics==1.0.3
[pip3] torchnmf==0.3.5
[pip3] torchvision==0.17.0.dev20230921+cu121
[pip3] triton==2.0.0
[pip3] tsne-torch==1.0.1
[conda] cqt-pytorch               0.0.5                    pypi_0    pypi
[conda] cudatoolkit               11.8.0              h4ba93d1_12    conda-forge
[conda] numpy                     1.24.0                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+6e4932cda8          pypi_0    pypi
[conda] torch                     2.2.0.dev20230921+cu121          pypi_0    pypi
[conda] torchaudio                2.2.0.dev20230921+cu121          pypi_0    pypi
[conda] torchmetrics              1.0.3                    pypi_0    pypi
[conda] torchnmf                  0.3.5                    pypi_0    pypi
[conda] torchvision               0.17.0.dev20230921+cu121          pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
[conda] tsne-torch                1.0.1                    pypi_0    pypi

**Comment by tringwald** [comment]
The bias of your conv layer contains nans:

```
tensor([   nan,    nan,    nan, 0.0518], requires_grad=True)
```

**Comment by albanD** [comment]
it is expected for the output to be nan if the bias are NaN, thanks for checking @tringwald !
