### ISSUE TITLE
WelfordReduction seems to have invalid/dead code when reduction_numel <= 1

### ISSUE THREAD

**Issue by int3** [pytorch/pytorch#109963]
I uncovered this trying to add types to `ir.py`. I'm not sure if this ever worked, but I'm pretty sure it doesn't successfully execute now due to the fact that it references an undefined `dst_dtype` local:

https://github.com/pytorch/pytorch/blob/b7a95f4fdb8a79dc459cc757dafcdbd0953b1a62/torch/_inductor/ir.py#L1179
https://github.com/pytorch/pytorch/blob/b7a95f4fdb8a79dc459cc757dafcdbd0953b1a62/torch/_inductor/ir.py#L1203

and also calls `const` with 1 instead of the required 2 arguments:

https://github.com/pytorch/pytorch/blob/b7a95f4fdb8a79dc459cc757dafcdbd0953b1a62/torch/_inductor/ir.py#L1189

Moreover, I wasn't able to find a test that triggered those code paths.

It seems like the code was added in 18b1c2907d672759a2b9c909004636b460fd9a5c. @peterbell10, would you mind taking a look to see if it's actually needed?

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

**Comment by peterbell10** [comment]
These were fixed in #110112
