### ISSUE TITLE
cm3leon_generate failing compilation

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#109926]
### 🐛 Describe the bug

```python
import torch
import importlib 
import sys

sys.path.append("benchmark")
c = "torchbenchmark.models.cm3leon_generate"
module = importlib.import_module(c)

device = "cuda"
benchmark_cls = getattr(module, "Model", None)
benchmark = benchmark_cls(test="eval", device = device)

model, example = benchmark.get_module()

eager = model(*example)

print("eager works")

print("be patient compilation takes a while on this model")
compiled = torch.compile(model)
compiled_out = compiled(*example)
```

### Error logs

Surprisingly this model works both in eager and compiler but is showing up as failing in pt2 dashboard something else is going on

### Versions

n/a

cc @ezyang @wconstab @bdhirsh @anijain2305

**Comment by bdhirsh** [comment]
The first strange thing that I see is that when I run `python install.py --continue_on_fail` in torchbench, these logs:
```
running setup for /data/users/hirsheybar/d/torchbenchmark/torchbenchmark/models/basic_gnn_gcn...OK
running setup for /data/users/hirsheybar/d/torchbenchmark/torchbenchmark/models/basic_gnn_gin...OK
running setup for /data/users/hirsheybar/d/torchbenchmark/torchbenchmark/models/basic_gnn_sage...OK
running setup for /data/users/hirsheybar/d/torchbenchmark/torchbenchmark/models/cm3leon_generate...SKIP - No install.py is found
```

**Comment by bdhirsh** [comment]
Oh on the repro - looks like there is an error running the model in eager mode, but only if you trigger backward:

```
import torch
import importlib 
import sys

sys.path.append("benchmark")
sys.path.append("../torchbenchmark")
c = "torchbenchmark.models.cm3leon_generate"
module = importlib.import_module(c)

device = "cuda"
benchmark_cls = getattr(module, "Model", None)
benchmark = benchmark_cls(test="eval", device = device)

model, example = benchmark.get_module()

eager = model(*example)
eager.sum().backward() 
# this errors  with
# RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by ezyang** [comment]
cm3leon_generate doesn't work with training, it is an inference only implementation

**Comment by bdhirsh** [comment]
oh - well, it looks like we're accidentally running it with `--training` in the benchmark suite. This link is from the inference tab of the dashboard, but I see some `--training` calls in the logs: https://hud.pytorch.org/benchmark/dynamic/inductor_dynamic?startTime=Mon,%2018%20Sep%202023%2015:04:42%20GMT&stopTime=Mon,%2025%20Sep%202023%2015:04:42%20GMT&granularity=hour&mode=inference&dtype=bfloat16&lBranch=main&lCommit=b7a95f4fdb8a79dc459cc757dafcdbd0953b1a62&rBranch=main&rCommit=2c1554a0323107d821be3ff13df7833b9f0b960d

**Comment by msaroufim** [comment]
I added training support btw. Should be included in the next pin

**Comment by ezyang** [comment]
It makes sense that we attempt to run it with training, we always try to run all models with training; for cm3leon i'd expect eager to fail and so we just exclude it entirely.

**Comment by xmfan** [comment]
Btw, you can pull the logs from the HUD by clicking on the git revision next to the model name and find the exact command that failed for the model
<img width="329" alt="image" src="https://github.com/pytorch/pytorch/assets/9547562/2e73a4aa-8cce-4c05-ba58-f35eba511db1">

@bdhirsh all tests run that one logfile, so you'll see both --training and --inference runs. It does require a bit of parsing. I'm pulling them out here for easier reference

In this case (cm3leon_generate, inference):
- default
  - acc pass
  - perf pass
- cudagraphs_freezing
  - acc pass
  - perf fail
    - no error message
- cudagraphs_dynamic
  - acc pass
  - perf fail
    - no error message
- cudagraphs
  - acc pass
  - perf fail
    - no error message
- aot_inductor
  - acc fail
    - ERROR:common:Dynamic control flow is not supported at the moment (P838256290)
  - perf fail
    - Dynamic control flow is not supported at the moment, similar as aot_inductor acc failure, P838259734

**Comment by xmfan** [comment]
The aot_inductor failure looks legit, if the dynamic control flow is intended and truly something we don't support yet, we can add a skip for it

For cudagraphs/cudagraphs_dynamic/cudagraphs_freezing, I am able to run it locally, but it took quite a bit of time before the benchmark started (model load time + compile?), I suspect the missing error message is due to timeout

**Comment by mlazos** [comment]
I'm going to close since it appears we've established the root cause. Feel free to reopen if needed.
