### ISSUE TITLE
profiler doesn't work with multiple workers

### ISSUE THREAD

**Issue by yiftachbeer** [pytorch/pytorch#109969]
### 🐛 Describe the bug

I'm following the code from the [profiler with tensorboard plugin tutorial](https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html?highlight=tensorboard). At a certain point, it suggests to change the number of workers to >0 (4). When I do that, the code fails with the following warning:
```
RuntimeError                              Traceback (most recent call last)
[<ipython-input-2-ec88df51141c>](https://localhost:8080/#) in <cell line: 31>()
     40             break
     41         train(batch_data)
---> 42         prof.step()  # Need to call this at the end of each step to notify profiler of steps' boundary.

3 frames
[/usr/local/lib/python3.10/dist-packages/torch/profiler/profiler.py](https://localhost:8080/#) in step(self)
    532         self.current_action = self.schedule(self.step_num)
    533 
--> 534         self._transit_action(prev_action, self.current_action)
    535         prof.KinetoStepTracker.increment_step(PROFILER_STEP_NAME)
    536 

[/usr/local/lib/python3.10/dist-packages/torch/profiler/profiler.py](https://localhost:8080/#) in _transit_action(self, prev_action, current_action)
    547         if action_list:
    548             for action in action_list:
--> 549                 action()
    550 
    551 

[/usr/local/lib/python3.10/dist-packages/torch/profiler/profiler.py](https://localhost:8080/#) in stop_trace(self)
    137     def stop_trace(self):
    138         assert self.profiler is not None
--> 139         self.profiler.__exit__(None, None, None)
    140 
    141     def export_chrome_trace(self, path: str):

[/usr/local/lib/python3.10/dist-packages/torch/autograd/profiler.py](https://localhost:8080/#) in __exit__(self, exc_type, exc_val, exc_tb)
    229         if self.use_cuda:
    230             torch.cuda.synchronize()
--> 231         self.kineto_results = _disable_profiler()
    232         parsed_results = self._parse_kineto_results(self.kineto_results)
    233         self.function_events = EventList(

RuntimeError: stack.size() INTERNAL ASSERT FAILED at "../torch/csrc/autograd/profiler_python.cpp":963, please report a bug to PyTorch. Python replay stack is empty.
```
I haven't modified anything else, but here's [a notebook showing the error](https://colab.research.google.com/drive/16FKv8sGy5jLRQbrN3PsGI6yTG703UUrZ).

### Versions

/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.00GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        3
BogoMIPS:                        4000.36
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        1 MiB (1 instance)
L3 cache:                        38.5 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by yiftachbeer** [comment]
I also get the same error on pytorch=2.0.0 (if I run `pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118` before running the code). 

Is there any way to profile PyTorch 2 with multiple workers at the moment?

**Comment by yiftachbeer** [comment]
Perhaps related to [https://github.com/pytorch/pytorch/issues/100253](https://github.com/pytorch/pytorch/issues/100253) but the proposed fix (which was apparently commited) does not fix the issue.
Also perhaps related to [https://github.com/pytorch/pytorch/issues/101632](https://github.com/pytorch/pytorch/issues/101632). Setting `with_stack=False` as suggested there works, but naturally removes stack traces which might be desired.
@albanD, is any idea if anybody is already working on a fix?

**Comment by albanD** [comment]
I don't think anyone is looking into this but @aaronenyeshi would know better

**Comment by yiftachbeer** [comment]
This still happens in 2.1. Is this not considered urgent? How do I get it prioritized? @aaronenyeshi

**Comment by aaronenyeshi** [comment]
> Perhaps related to #100253 but the proposed fix (which was apparently commited) does not fix the issue. Also perhaps related to #101632. Setting `with_stack=False` as suggested there works, but naturally removes stack traces which might be desired. @albanD, is any idea if anybody is already working on a fix?

Hi @yiftachbeer, you can try enabling the experimental config to make the stack traces work with legacy tb_plugin. 
```
with profile(
  with_stack=True,
  experimental_config=torch._C._profiler._ExperimentalConfig(verbose=True)
) as prof:
```

We are currently deprecating the Tensorboard plugin, and will replace it with HTA, for reference:
- Tensorboard plugin: with profile(with_stack=True, profile_memory=True, experimental_config=torch._C._profiler._ExperimentalConfig(verbose=True)) as prof:
- HTA: https://github.com/pytorch/kineto/tree/main#holistic-trace-analysis

Tensorboard plugin features are not a priority right now, and @anupambhatnagar is working on adding HTA tutorial documents in replacement.

Sorry about any inconvenience.

**Comment by yiftachbeer** [comment]
This is not a tensorboard plugin related bug, and I've already tried removing its usage and adding the proposed fix with experimental config. This results in the following code:
```
import torch
import torch.nn
import torch.optim
import torch.profiler
import torch.utils.data
import torchvision.datasets
import torchvision.models
import torchvision.transforms as T

transform = T.Compose(
    [T.Resize(224),
     T.ToTensor(),
     T.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
train_set = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
train_loader = torch.utils.data.DataLoader(train_set, num_workers=4, batch_size=32, shuffle=True)

device = torch.device("cuda:0")
model = torchvision.models.resnet18(weights='IMAGENET1K_V1').cuda(device)
criterion = torch.nn.CrossEntropyLoss().cuda(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
model.train()

def train(data):
    inputs, labels = data[0].to(device=device), data[1].to(device=device)
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

with torch.profiler.profile(
        schedule=torch.profiler.schedule(wait=1, warmup=1, active=3, repeat=2),
        record_shapes=True,
        profile_memory=True,
        with_stack=True,
        experimental_config=torch._C._profiler._ExperimentalConfig(verbose=True),
) as prof:
    for step, batch_data in enumerate(train_loader):
        if step >= (1 + 1 + 3) * 2:
            break
        train(batch_data)
        prof.step()  # Need to call this at the end of each step to notify profiler of steps' boundary.
```
which still gives the following error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-3-793f781ea20a>](https://localhost:8080/#) in <cell line: 31>()
     41             break
     42         train(batch_data)
---> 43         prof.step()  # Need to call this at the end of each step to notify profiler of steps' boundary.

3 frames
[/usr/local/lib/python3.10/dist-packages/torch/autograd/profiler.py](https://localhost:8080/#) in __exit__(self, exc_type, exc_val, exc_tb)
    229         if self.use_cuda:
    230             torch.cuda.synchronize()
--> 231         self.kineto_results = _disable_profiler()
    232         parsed_results = self._parse_kineto_results(self.kineto_results)
    233         self.function_events = EventList(

RuntimeError: stack.size() INTERNAL ASSERT FAILED at "../torch/csrc/autograd/profiler_python.cpp":963, please report a bug to PyTorch. Python replay stack is empty.
```
Am I doing something wrong? It seems that the profiler itself (with stack traces) is currently unusable, regardless of tensorboard. Shouldn't this issue be re-opened? @aaronenyeshi

**Comment by aaronenyeshi** [comment]
Sorry, this is a known bug where `with_stack=True` cannot be run back to back. Could you please try using `repeat=1` and see if that can workaround this bug? Re-opening this issue.

**Comment by yiftachbeer** [comment]
@aaronenyeshi Your suggestion works, but naturally alters the result.
To summarize, these are currently possible workarounds:
- setting `num_workers=0`
- setting `repeat=1`
- setting `with_stack=False`

All seem to work, but each comes with its own caveats.
What issue is the bug tracked at, can we get a link here to track it? And can the docs/tutorial be updated to save people the time when they try to run the tutorial as-is and run into this issue?

**Comment by aaronenyeshi** [comment]
> What issue is the bug tracked at, can we get a link here to track it?
Unfortunately, we only have a internal task assigned that is tracking this issue. We can use this issue to continue tracking it in OSS. (If you are a Meta Employee, see: T152887452)

> And can the docs/tutorial be updated to save people the time when they try to run the tutorial as-is and run into this issue?
This is a good idea, I've opened a PR to update the tutorial. We will also be replacing the tensorboard plugin tutorial with an HTA tutorial in the coming months. cc @adnanaziz
