### ISSUE TITLE
torch-<version>.dist-info WHEEL file contains incorrect metadata for M1/M2 macOS platform

### ISSUE THREAD

**Issue by martynas-subonis** [pytorch/pytorch#109970]
### 🐛 Describe the bug

The `pip install` explicitly downloads `torch-<version>-cp310-none-macosx_11_0_arm64.whl`, however, the `WHEEL` metadata file has the tag: `Tag: cp310-cp310-macosx_11_0_x86_64`. Since the `arm64.whl` is downloaded, the tag should contain the `arm64` tag instead of the `x86_64` tag.

### System

```bash
Chip: Apple M2 Max
macOS: 13.5.1
```

### Steps to reproduce

```bash
python3 --version
# Python 3.10.12
python3 -m venv .venv
source .venv/bin/activate
pip install --no-cache-dir torch==2.0.1
# Collecting torch==2.0.1
# Downloading torch-2.0.1-cp310-none-macosx_11_0_arm64.whl (55.8 MB)
# ...
cat .venv/lib/python3.10/site-packages/torch-2.0.1.dist-info/WHEEL
# Wheel-Version: 1.0
# Generator: bdist_wheel (0.38.4)
# Root-Is-Purelib: false
# Tag: cp310-cp310-macosx_11_0_x86_64
```

The same behaviour is seen with `torch==1.13.1` as well. I haven't tested more versions, it could be present there as well.

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.5.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.12 (main, Aug 23 2023, 13:33:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.5.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] torch==2.0.1
[conda] Could not collect

Process finished with exit code 0

cc @seemethere @malfet

**Comment by malfet** [comment]
This should not longer be the case, as we've stopped cross-compiling M1 binaries a while back
