### ISSUE TITLE
Please offer packages with local version `torch==2.1.0+cpu` for macOS

### ISSUE THREAD

**Issue by maxhgerlach** [pytorch/pytorch#110004]
### 🚀 The feature, motivation and pitch

https://download.pytorch.org/whl/test/torch/ offers CPU builds of version 2.1.0 RC. For Intel Linux and Windows both packages are available with local version `2.1.0+cpu`. For macOS there is only version `2.1.0` without an appended local version.

This currently makes it very hard to add PyTorch as a dependency to a project managed with poetry if compatibility to both Linux and macOS is desired. In poetry it's currently not possible to prefer `2.1.0` over `2.1.0+cpu` (https://github.com/python-poetry/poetry/issues/7256) and there's no working way to configure packages from this same source for different systems with different local version numbers.

### Alternatives

Users could host the packages themselves (with controlled version numbers), but that is not possible in all situations.

### Additional context

Poetry is a very popular solution to manage dependencies of complex Python projects. It would be great if PyTorch worked well with it.

cc @malfet @seemethere

**Comment by malfet** [comment]
Closing as implemented, PyTorch should work well with poetry in 2.1 and above. If this is not the case, please do not hesitate to file a separate issue
