### ISSUE TITLE
Feature Request: Support `.numpy()` with CUDA Tensor

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#1100]
When using sending Tensor to GPU by `.cuda()`, if we want to retrieve the array to numpy, we have to firstly send it back to CPU by `var.data.cpu().numpy()`. 

In this case, it has to write a if-else condition for a generic code for both CPU and GPU. 
```
if Tensor in CUDA:
    var.data.cpu().numpy()
else:
   var.data.numpy()
```

It is better to support `numpy()` with both CPU Tensor and CUDA Tensor. So that it is not necessary to write these if-else condition

**Comment by fmassa** [comment]
Note that you can always call `.cpu().numpy()`, even on CPU tensors, so the conditional is not really necessary

**Comment by zuoxingdong** [comment]
Oh, that is great. Thanks a lot for the info. I am closing this issue.
