### ISSUE TITLE
DISABLED test_tags_multiple_checkpoints (__main__.ActivationCheckpointingViaTagsTests)

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#110038]
Platforms: linux, rocm, slow

https://github.com/pytorch/pytorch/actions/runs/6303967068/job/17115576334

This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/dynamo%2Ftest_activation_checkpointing.py%3A%3AActivationCheckpointingViaTagsTests%3A%3Atest_tags_multiple_checkpoints)).

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ZainRizvi** [comment]
Weird thing here is that the error message sounds like something that should be very deterministic, yet it's not

`Error: AssertionError: Passing context_fn to torch.utils.checkpoint is currently not supported under torch.compile`

**Comment by zou3519** [comment]
This might be the Dynamo cache thing where after a certain number of entries we just fall back to eager-mode
