### ISSUE TITLE
argument 'size' must be tuple of ints, but found element of type int at pos 2

### ISSUE THREAD

**Issue by BramVanroy** [pytorch/pytorch#110066]
### 🐛 Describe the bug

A `size` argument expects `int`s as data types. However, this will not work for very large ints. I am not sure whether this is a bug on the side of the implementation or whether massive tensors are simply not supported. In case of the latter, the error message should be improved.

```python
import torch
torch.randint(low=0, high=100, size=(1, int(1e20)))
```

This will yield

> argument 'size' must be tuple of ints, but found element of type int at pos 2

But one might scratch their head because both arguments are `int`s. If there is a cut off, this should be considered in the error. I did not check but I can imagine that the max supported int is a long int in cpp, in which case the Python error message should be different depending on whether or not the given sizes are smaller or larger than the max corresponding cpp type.

### Versions

[pip3] numpy==1.26.0
[pip3] torch==2.0.1
[pip3] triton==2.0.0
[conda] cudatoolkit               11.8.0              h37601d7_11    conda-forge

cc @albanD

**Comment by albanD** [comment]
Hi,

This error message was improved in main. Can you double check that the error message is correct with a nightly build please?

**Comment by BramVanroy** [comment]
I can't really test on non-pypi releases now, but I'll take your word for it. Thanks!

**Comment by albanD** [comment]
Ho the nightly are just a pip install away: https://pytorch.org/get-started/locally/
But I just verified locally that it is fixed, the new error message is: `TypeError: randint(): argument 'size' failed to unpack the object at pos 2 with error "Overflow when unpacking long"`
