### ISSUE TITLE
[inductor][cpu] [cppwrapper] performance regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#110059]
<p>new_perf_regression: 2023-09-24 nightly release vs 2023-09-17 nightly release</p>

<p>Note: multi threads secnario for models above first *, single thread for models between two *</p>

<p>new_perf_regression in 2023-09-24</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hf_GPT2_large</td>
      <td>1</td>
      <td>1.235657</td>
      <td>0.707024497</td>
      <td>0.873639768889529</td>
      <td>90.088849</td>
      <td>1</td>
      <td>1.338079</td>
      <td>0.606709952</td>
      <td>0.811825845862208</td>
      <td>87.929263</td>
      <td>0.92</td>
      <td>0.93</td>
      <td>0.86</td>
      <td>0.98</td>
    </tr>
    <tr>
      <td>hf_T5_large</td>
      <td>1</td>
      <td>0.984055</td>
      <td>0.480984575</td>
      <td>0.47331527595162504</td>
      <td>341.046352</td>
      <td>1</td>
      <td>1.185515</td>
      <td>0.393748912</td>
      <td>0.46679524140968004</td>
      <td>329.681863</td>
      <td>0.83</td>
      <td>0.99</td>
      <td>0.82</td>
      <td>0.97</td>
    </tr>
    <tr>
      <td>pyhpc_isoneutral_mixing</td>
      <td>1048576</td>
      <td>0.547752</td>
      <td>0.033736857999999995</td>
      <td>0.018479431443215996</td>
      <td>27.621908</td>
      <td>1048576</td>
      <td>0.60916</td>
      <td>0.030191551</td>
      <td>0.01839148520716</td>
      <td>29.368355</td>
      <td>0.9</td>
      <td>1.0</td>
      <td>0.89</td>
      <td>1.06</td>
    </tr>
  </tbody>
</table>
<p>SW info</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>24d07d1</td>
      <td>dee1009</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ffbbebb9</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td>ede4309</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td>45e4b8c</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td>4ac707a</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td>d76d92c</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
      <td>/</td>
    </tr>
  </tbody>
</table>
<p>Reference SW info (nightly)</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>ffbbebb9</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+git0de2555</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.16.0a0+8636bf3</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+142d029</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+475b6ae</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+eb9bf61</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
    </tr>
  </tbody>
</table>

<p>Repro</p>
<a href=https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh>
  inductor_single_run.sh </a>
<code>
bash inductor_single_run.sh multiple/single inference performance torchbench/huggingface/timm_models model float32 first static cpp 0
</code>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by chunyuan-w** [comment]
@ESI-SYD could you please help provide guity commit?

**Comment by ESI-SYD** [comment]
I will update guity commit later

**Comment by ESI-SYD** [comment]
Not reproduced, closing and wait for next week's data
