### ISSUE TITLE
 custom_ops._destroy("test::foo") doesn't remove abstract_impl

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#110137]
### 🐛 Describe the bug

self explanatory

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @wconstab

### Versions

main

**Comment by ezyang** [comment]
@zou3519 do you remember if you actually fixed this

**Comment by zou3519** [comment]
this is for one of the prototypes of the new custom op API, which I will purge after I land the newest one, so we can close this when that happens.

**Comment by zou3519** [comment]
NB: if you're here, go use torch.library._scoped_library or torch.library.custom_op for testing. Both will cleanup after themselves
