### ISSUE TITLE
[export] 'nn_module_stack' only contains root module in the exported graph

### ISSUE THREAD

**Issue by lsy323** [pytorch/pytorch#110115]
### 🐛 Describe the bug

'nn_module_stack' only contains root module in the exported graph.

Here is a testing script

```python
import torch

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x, w1, w2):
        m1 = torch.cat([w1, w2]).sum()
        m2 = torch.cat([w1, w2]).sum()
        return x + torch.max(m1) + torch.max(m2)
    
model = M().eval()
args = (torch.rand(2,10), torch.rand(2,10), torch.rand(2,10))
exported_module = torch.export.export(model, args)

for n in exported_module.graph_module.graph.nodes:
    if n.name == "cat_1":
        print("node nn_module_stack: {}".format(n.meta.get("nn_module_stack")))

```

Output
```
node nn_module_stack: {'L__self__': ('', <class '__main__.M'>)}
```

This doesn't seem to be expected, there should be more depths in the `nn_module_stack` info. (e.g. Including `torch.cat`)

Did an initial investigation, the FX graph from `dynamo.export` doesn't contain `nn_module_stack` info, the root module is added [here](https://github.com/pytorch/pytorch/blob/main/torch/_export/__init__.py#L349)

Appreciate any suggestion & help!

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @qihqi @zhxchen17 @gmagogsfm

### Versions

PyTorch version: 2.2.0a0+gitf2639a2

Versions of relevant libraries:
[pip3] numpy==1.25.1
[pip3] torch==2.2.0a0+gitac3190c
[pip3] torch-xla==2.2.0
[pip3] torchvision==0.16.0a0+b9447fd
[conda] numpy                     1.25.1                   pypi_0    pypi
[conda] torch                     2.2.0a0+gitac3190c           dev_0    <develop>
[conda] torch-xla                 2.2.0                     dev_0    <develop>

**Comment by gmagogsfm** [comment]
I don't think `torch.cat` is a module, so it is expected to not be in nn_module_stack.

```
>>> torch.nn.Linear
<class 'torch.nn.modules.linear.Linear'>
>>> torch.cat
<built-in method cat of type object at 0x7fda901747a0>
```

**Comment by lsy323** [comment]
@gmagogsfm Thanks for taking a look and the explanation, I think the behavior is expected. For the `call_function`/`call_method` node, the target name can be retrieve from FX node target. Thanks for the help @gmagogsfm
