### ISSUE TITLE
Docker hub

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#1101]
Do you plan to publish an official entry on docker hub?

**Comment by pineking** [comment]
any update? I think it's an important enhancement.

**Comment by alykhantejani** [comment]
I believe this would just be pushing the image from [this dockerfile](https://github.com/pytorch/pytorch/blob/master/Dockerfile)? If so, I can add it to Docker Hub @apaszke if you like?

**Comment by pineking** [comment]
@apaszke @alykhantejani Configure automated builds on Docker Hub https://docs.docker.com/docker-hub/builds/

**Comment by ngimel** [comment]
@alykhantejani The dockerfile you referenced builds from current master, I don't know if that's desirable. There is a runtime dockerfile in tools/docker that installs current binary release, I'd think that's what should be hosted on the dockerhub.

**Comment by alykhantejani** [comment]
@ngimel yup, that makes more sense. Thanks

**Comment by ngimel** [comment]
Oops, looks like runtime dockerfile would be broken now (see discussion in #beginner, conda packages conflict with conda numpy).

**Comment by alykhantejani** [comment]
@ngimel Just tested, the runtime dockerfile seems to work just fine. Pulls in numpy 1.13.1 which seems to not have any issues.

**Comment by alykhantejani** [comment]
pre-built images are now available, you can run them with:
```
nvidia-docker run --rm -ti --ipc=host pytorch/pytorch:latest
```
