### ISSUE TITLE
CI: rocm `(default, 1, 3, linux.rocm.gpu)` is very slow

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#110181]
## Current Status
ongoing

## Issue looks like
Taking ~2.5 hours on https://github.com/pytorch/pytorch/pull/110167
![image](https://github.com/pytorch/pytorch/assets/9093549/f36d4d3b-93eb-48ee-a0f9-e945643376c6)

Taking 3.5+ hours on https://github.com/pytorch/pytorch/pull/109976
![image](https://github.com/pytorch/pytorch/assets/9093549/68af3813-84be-4034-ac24-2e61ec4e1856)

## User impact
Slower merging

## Root cause
Seems like it may have been introduced in https://github.com/pytorch/pytorch/pull/109817 @malfet 
![image](https://github.com/pytorch/pytorch/assets/9093549/18b78912-8304-4e95-bc80-a65b4b88e41d)

## Mitigation
Not sure

## Prevention/followups
Investigate cause of slow running time or split up tests into smaller test jobs. Try to make the tests run in similar time to CUDA tests (~1.5 hours)

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @seemethere @malfet @pytorch/pytorch-dev-infra @ZainRizvi @kit1980 @huydhn @clee2000
```[tasklist]
### Tasks
```

**Comment by hongxiayang** [comment]
I checked the raw logs of https://github.com/pytorch/pytorch/pull/110167 and https://github.com/pytorch/pytorch/pull/109976.
(1) For the test_api test, in which a few unit tests were added by https://github.com/pytorch/pytorch/pull/109817, is not the root cause of the CI slowness overall. 
The time difference for the whole test_api test suite between the first two pull request are about >4 minutes:
1033 passed in 569.81s (0:09:29) vs.
1033 passed in 306.68s (0:05:06)

(2) As to make the whole CI: rocm " (default, 1, 3, linux.rocm.gpu)" running time to be align with Cuda's timeframe, we will look into it.

**Comment by jon-chuang** [comment]
@hongxiayang, thank you for your follow up.

> As to make the whole CI: rocm " (default, 1, 3, linux.rocm.gpu)" running time to be align with Cuda's timeframe, we will look into it.

Thank you. Generally, I am unsure which of the tests are an overall bottleneck (e.g. are there CUDA tests which also take as long?).

However, 4 hours for a test suite is the bottleneck for some PRs as noted, so that reducing that would be really great.

Perhaps @malfet may have more insight into what are considered long v.s. acceptable times.

**Comment by huydhn** [comment]
Per the discussion with @malfet and @clee2000, let's more ROCm job to its own workflow to be triggered by `ciflow: rocm`.  In the meantime, we could mark ROCm as unstable where it doesn't block merge (but still run and gives CI signals)

**Comment by jithunnair-amd** [comment]
@huydnn That sounds okay for the interim. I'm working on adding a new workflow for ROCm that will run a reduced set of tests on pull_requests (so should take less time). Once we have that, we should be able to move ROCm CI back to stable?

**Comment by huydhn** [comment]
> @huydnn That sounds okay for the interim. I'm working on adding a new workflow for ROCm that will run a reduced set of tests on pull_requests (so should take less time). Once we have that, we should be able to move ROCm CI back to stable?

Yeah, definitely.  Also, as we are still monitoring unstable signals in trunk, if a change breaks ROCm jobs, they would still be reverted as usual.
