### ISSUE TITLE
ONNX export of torch.nn.Transformer still fails

### ISSUE THREAD

**Issue by FedyuninV** [pytorch/pytorch#110255]
### 🐛 Describe the bug

```python
import numpy as np
import torch

model = torch.nn.Transformer(d_model=16,
                            nhead=4,
                            num_encoder_layers=1,
                            num_decoder_layers=1,
                            batch_first=False)

src = torch.tensor(np.random.randn(3,1,16).astype(np.float32))
tgt = torch.tensor(np.random.randn(5,1,16).astype(np.float32))

torch.onnx.export(model,
                  {'src':src, 'tgt':tgt},
                  'torch_nn_transformer.onnx',
                  verbose=False,
                  input_names=['src', 'tgt'],
                  opset_version=15,
                  output_names=['out'],
                  dynamic_axes={
                    'src': {0: 'src_len'},
                    'tgt': {0: 'tgt_len'},
                    'out': {0: 'tgt_len'}
                  })
```

```
C:\Program Files\Python310\lib\site-packages\torch\nn\modules\transformer.py:282: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
Traceback (most recent call last):
  File "D:\ROOT\PythonExperiments\onnx_export_fail.py", line 13, in <module>
    torch.onnx.export(model,
  File "C:\Program Files\Python310\lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "C:\Program Files\Python310\lib\site-packages\torch\onnx\utils.py", line 1613, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Program Files\Python310\lib\site-packages\torch\onnx\utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\Program Files\Python310\lib\site-packages\torch\onnx\utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Program Files\Python310\lib\site-packages\torch\onnx\utils.py", line 915, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "C:\Program Files\Python310\lib\site-packages\torch\jit\_trace.py", line 1290, in _get_trace_graph
    outs = ONNXTracedModule(
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\jit\_trace.py", line 138, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "C:\Program Files\Python310\lib\site-packages\torch\jit\_trace.py", line 129, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1509, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\transformer.py", line 206, in forward
    output = self.decoder(tgt, memory, tgt_mask=tgt_mask, memory_mask=memory_mask,
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1509, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\transformer.py", line 460, in forward
    output = mod(output, memory, tgt_mask=tgt_mask,
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1509, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\transformer.py", line 847, in forward
    x = self.norm2(x + self._mha_block(x, memory, memory_mask, memory_key_padding_mask, memory_is_causal))
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\transformer.py", line 865, in _mha_block
    x = self.multihead_attn(x, mem, mem,
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\module.py", line 1509, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\modules\activation.py", line 1241, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "C:\Program Files\Python310\lib\site-packages\torch\nn\functional.py", line 5440, in multi_head_attention_forward
    attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
TypeError: scaled_dot_product_attention(): argument 'is_causal' (position 6) must be bool, not Tensor
```

BTW:
1. I'm using nightly build because otherwise I have problems with torch.nn.MultiHeadAttention export (see #110070 )
2. Mb it's a good idea to add some part of this to onnx tests. What do you think? It will show any problems with export of any part of the transformer (attention/decoder/encoder/normalization). And I think you will be getting a lot of issues like this one because of transformers popularity...

### Versions

Collecting environment information...
PyTorch version: 2.2.0.dev20230928+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.27.0-rc2
Libc version: N/A

Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU
Nvidia driver version: 536.23
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3601
DeviceID=CPU0
Family=107
L2CacheSize=8192
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3601
Name=AMD Ryzen 7 7745HX with Radeon Graphics
ProcessorType=3
Revision=24834

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] torch==2.2.0.dev20230928+cpu
[pip3] torchaudio==2.2.0.dev20230928+cpu
[pip3] torchvision==0.17.0.dev20230928+cpu
[conda] Could not collect

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg

**Comment by justinchuby** [comment]
Thanks, we should definitely add this to tests.

**Comment by MaanavD** [comment]
Hey @FedyuninV ,

Closing this as stale, please try again using the new `torch.onnx.dynamo_export()` api. Please reopen the issue if  you still run into it.

Thanks,
Maanav

**Comment by SpitchAG** [comment]
exporting the TransformerDecoder still failing with latest torch 2.6.

model = model.transformer.decoder=TransformerDecoder(
  (layers): ModuleList(
    (0-3): 4 x TransformerDecoderLayer(
      (self_attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
      )
      (multihead_attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
      )
      (linear1): Linear(in_features=512, out_features=1024, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (linear2): Linear(in_features=1024, out_features=512, bias=True)
      (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (norm3): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (dropout1): Dropout(p=0.1, inplace=False)
      (dropout2): Dropout(p=0.1, inplace=False)
      (dropout3): Dropout(p=0.1, inplace=False)
    )
  )
  (norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
)

**code to export** (this wrapper doesnt pass any tgt_mask, but same result if i pass tgt_mask)
 
```
torch.onnx.export(onnx_model.eval(), (output, input, src_pad_mask,),
                      "g2p_trans_dec.onnx",
                      opset_version=20,
                      dynamo = True,
                      input_names = ['output', 'input', 'src_pad_mask'],
                      output_names = ['out'],
                      dynamic_shapes = {
                                         'output' : { 0 : torch.export.Dim.DYNAMIC},
                                         'input' : { 0 : torch.export.Dim.DYNAMIC},
                                         'src_pad_mask' : { 1 : torch.export.Dim.DYNAMIC},
                                         'out': { 0 : torch.export.Dim.DYNAMIC} },
                      verify = True,
                      optimize = False)
```


**output of export:**
W0226 14:41:05.483000 16371 torch/onnx/_internal/exporter/_registration.py:66] torchvision is not installed. Skipping torchvision::nms
[torch.onnx] Obtain model graph for `ONNXDeepPhonemizer_trans_dec([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `ONNXDeepPhonemizer_trans_dec([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decomposition...
[torch.onnx] Run decomposition... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅
[torch.onnx] Check the ONNX model...
[torch.onnx] Check the ONNX model... ✅
[torch.onnx] Execute the model with ONNX Runtime...
[torch.onnx] Execute the model with ONNX Runtime... ✅
[torch.onnx] Verify output accuracy...
[torch.onnx] Verify output accuracy... ✅
W0226 14:41:09.043000 16371 torch/onnx/_internal/exporter/_registration.py:66] torchvision is not installed. Skipping torchvision::nms
[torch.onnx] Obtain model graph for `ONNXDeepPhonemizer_dec([...]` with `torch.export.export(..., strict=False)`...
W0226 14:41:09.135000 16371 torch/fx/experimental/symbolic_shapes.py:6307] failed during evaluate_expr(Eq(u0, 1), hint=None, size_oblivious=False, forcing_spec=False
E0226 14:41:09.135000 16371 torch/fx/experimental/recording.py:299] failed while running evaluate_expr(*(Eq(u0, 1), None), **{'fx_node': False})
W0226 14:41:09.135000 16371 torch/fx/experimental/symbolic_shapes.py:6830] Unable to find user code corresponding to {u0}
[torch.onnx] Obtain model graph for `ONNXDeepPhonemizer_dec([...]` with `torch.export.export(..., strict=False)`... ❌

**Comment by justinchuby** [comment]
Please test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!

**Comment by justinchuby** [comment]
Feel free to also provide a script we can run and reproduce the error for us to be able to debug.

**Comment by SpitchAG** [comment]
hello

using  the latest https://download.pytorch.org/whl/nightly/cpu/torch-2.7.0.dev20250227%2Bcpu-cp310-cp310-manylinux_2_28_x86_64.wh,

i am able to export the model if i set the **tgt_is_causal flag to True**. (which is always my use case).
**If i dont add this flag as arg (None), i have failed report that am attaching.**

(Note that i have the same behavior with the 2.6, i probably forgot to set the tgt_casual to true in my previous test. i just reran with this flag to true + 2.6 and it also works, mea culpa.)

as for a script i can just give u my wrapper around the transdecoder, and u just call the onnx export  :
 
`class ONNXDeepPhonemizer_trans_dec(torch.nn.Module):
    def __init__(self, trans_decoder: torch.nn.Module):
        super().__init__()
        self.trans_decoder = trans_decoder
    def forward(self, output, input, src_pad_mask, tgt_mask):
        return self.trans_decoder(output, input, memory_key_padding_mask = src_pad_mask, tgt_mask = tgt_mask)

# trans dec
    onnx_model = ONNXDeepPhonemizer_trans_dec(model.transformer.decoder)
    output = torch.randn(7,1,512)
    input = torch.randn(12, 1, 512)
    mask = torch.triu(torch.ones(7, 7), 1)
    tgt_mask = mask.masked_fill(mask == 1, float('-inf'))
    out = onnx_model(output, input, src_pad_mask, tgt_mask)
    torch.onnx.export(onnx_model.eval(), (output, input, src_pad_mask,tgt_mask,),
                      "g2p_trans_dec.onnx",
                      opset_version=20,
                      dynamo = True,
                      input_names = ['output', 'input', 'src_pad_mask', 'tgt_mask'],
                      output_names = ['out'],
                      dynamic_shapes = {
                                         'output' : { 0 : torch.export.Dim.DYNAMIC},
                                         'input' : { 0 : torch.export.Dim.DYNAMIC},
                                         'src_pad_mask' : { 1 : torch.export.Dim.DYNAMIC},
                                         'tgt_mask' : { 0: torch.export.Dim.DYNAMIC, 1 : torch.export.Dim.DYNAMIC},
                                         #'out': { 0 : torch.export.Dim.DYNAMIC}
                                         },
                      verify = True,
                      report = True,
                      optimize = False)

` 


[export.log](https://github.com/user-attachments/files/19007368/export.log)

**Comment by justinchuby** [comment]
@SpitchAG can you ensure `torch.export.export` works? If not please create a new issue and tag torch.export for us to isolate the issue.
