### ISSUE TITLE
torch.split should match numpy.array_split semantics

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#11029]
Because they make more sense. Currently trying to split a 224-element tensor into 20 chunks returns only 19 tensors, while NumPy divides it into 20 sub-arrays.

**Comment by ptrblck** [comment]
The current implementation takes a single length or list of length to split the tensor.
```python
x = torch.randn(224)
torch.split(x, split_size_or_sections=20)
```
returns 11 tensors of shape `[20]` and 1 of shape `[4]`.

`torch.chunk` seems to be more related to `np.array_split` using an integer:
```python
torch.chunk(x, chunks=20)
```
returns 18 chunks of shape `[12]` and 1 of shape `[8]`,
while `np.array_split` returns 4 chunks of shape `[12]` and 16 of shape `[11]`.

@apaszke What do you think, should `torch.chunk` be rather modified?

**Comment by gchanan** [comment]
I think there was a similar issue filed against this and @yf225 was thinking about working on it at some point.  @yf225 does this sound familiar?

**Comment by gchanan** [comment]
I think https://github.com/pytorch/pytorch/issues/9382 is the relevant issue.

**Comment by yf225** [comment]
Yes I think it's the same as #9382. We can probably pool all discussions to that issue for better tracking. Also please feel free to pick up the task if anyone is interested, or I can come back to it after the high-pri tasks at hand.

**Comment by apaszke** [comment]
My bad, didn't know this issue already exists. Let's move the discussion there.
