### ISSUE TITLE
scaled_dot_product_attention example implementation is incorrect

### ISSUE THREAD

**Issue by samuela** [pytorch/pytorch#110341]
### 📚 The doc issue

Code in https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html does not work. In particular, the `masked_fill` gives an error:
```
In [47]: attn_mask.masked_fill(not attn_mask, -float('inf'))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[47], line 1
----> 1 attn_mask.masked_fill(not attn_mask, -float('inf'))

RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

**Comment by tringwald** [comment]
The torch 2.1 release candidate has an updated [docs page](https://pytorch.org/docs/2.1/generated/torch.nn.functional.scaled_dot_product_attention.html#torch.nn.functional.scaled_dot_product_attention).

**Comment by mikaylagawarecki** [comment]
Closing as this is fixed on `main`
