### ISSUE TITLE
torch._dynamo.exc.Unsupported: unexpected sourceless type bases: (<class 'torchrec.streamable.Pipelineable'>,)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#110315]
This is happening when trying to use `torch.export` on some code involving KJTs.

Internal stack trace: P840857345
Repro: P840859224

Notes:
- This is happening when we trace the construction of KJT, then pass that KJT as input to a module that we have configured to be `preserve_module_call_signature`. 
- If I remove the KJT construction, and pass a KJT we got directly from the input, things work (strange!)
- Ed suggested commenting out [this check](https://github.com/pytorch/pytorch/blob/359c2a53f59aab460fb15ba60f40fda537c33aeb/torch/_dynamo/variables/builtin.py#L1113). When we do this, things will pass, although I gather that this is unsafe because we would not be properly installing guards.

@ezyang says he knows what's going on and can post an OSS repro when he has some time

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @ydwu4 @msaroufim @wconstab @bdhirsh @zou3519 @aakhundov @Xia-Weiwen

**Comment by ezyang** [comment]
Simplified repro:

```
import torch
import abc
import torch.fx._symbolic_trace

class Meta(abc.ABCMeta, torch.fx._symbolic_trace.ProxyableClassMeta):
    def __new__(cls, name, bases, dct):
        x = super().__new__(cls, name, bases, dct)
        x.attr = 100
        return x

class Multistreamable(abc.ABC):
    pass

class Foo(Multistreamable, metaclass=Meta):
    pass

@torch.compile(backend="eager", fullgraph=True)
def f(x):
    typ = type(Foo())
    typ.__bases__
    return x + 1

f(torch.randn(1))
```

**Comment by ezyang** [comment]
cc @Fidget-Spinner, idk if you wanna help us properly model Python's object model in Dynamo so this all works properly

**Comment by Fidget-Spinner** [comment]
Thanks I'll take a look at this.

**Comment by anijain2305** [comment]
This passes on `main`.

There is a larger point of using `SourcelessBuilder` and `VariableBuilder` everywhere instead of constructing one-off variable trackers here and there. We should track that separately.

cc @mlazos
