### ISSUE TITLE
implement dirichlet / beta GPU grad 

### ISSUE THREAD

**Issue by jramapuram** [pytorch/pytorch#11030]
## Issue description
`torch.distributions.Beta` and `torch.distributions.Dirichlet` don't allow for backward() calls on the GPU; the CPU versions works fine though. 

```ipython
In [1]: import torch

In [2]: d = torch.distributions.Dirichlet(torch.sigmoid(torch.randn(3, 4, requir
   ...: es_grad=True))).rsample()

In [3]: torch.mean(d).backward()

In [4]: d = torch.distributions.Dirichlet(torch.sigmoid(torch.randn(3, 4, requir
   ...: es_grad=True).cuda())).rsample()


In [5]: 

In [5]: torch.mean(d).backward()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-d517ed89bac2> in <module>()
----> 1 torch.mean(d).backward()

~/.venv3/lib/python3.6/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
     94                 products. Defaults to ``False``.
     95         """
---> 96         torch.autograd.backward(self, gradient, retain_graph, create_graph)
     97 
     98     def register_hook(self, hook):

~/.venv3/lib/python3.6/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     88     Variable._execution_engine.run_backward(
     89         tensors, grad_tensors, retain_graph, create_graph,
---> 90         allow_unreachable=True)  # allow_unreachable flag
     91 
     92 

~/.venv3/lib/python3.6/site-packages/torch/autograd/function.py in apply(self, *args)
     74 
     75     def apply(self, *args):
---> 76         return self._forward_cls.backward(self, *args)
     77 
     78 

~/.venv3/lib/python3.6/site-packages/torch/autograd/function.py in wrapper(ctx, *args)
    186     def wrapper(ctx, *args):
    187         with torch.no_grad():
--> 188             outputs = fn(ctx, *args)
    189 
    190         if not torch.is_grad_enabled():

~/.venv3/lib/python3.6/site-packages/torch/distributions/dirichlet.py in backward(ctx, grad_output)
     33     def backward(ctx, grad_output):
     34         x, concentration = ctx.saved_tensors
---> 35         return _Dirichlet_backward(x, concentration, grad_output)
     36 
     37 

~/.venv3/lib/python3.6/site-packages/torch/distributions/dirichlet.py in _Dirichlet_backward(x, concentration, grad_output)
     18 def _Dirichlet_backward(x, concentration, grad_output):
     19     total = concentration.sum(-1, True).expand_as(concentration)
---> 20     grad = torch._dirichlet_grad(x, concentration, total)
     21     return grad * (grad_output - (x * grad_output).sum(-1, True))
     22 

RuntimeError: _dirichlet_grad is not implemented for type torch.cuda.FloatTensor

```
Provide a short description.

## Code example

```python
import torch
d = torch.distributions.Dirichlet(torch.sigmoid(torch.randn(3, 4, requires_grad=True))).rsample()
torch.mean(d).backward() # works!
d = torch.distributions.Dirichlet(torch.sigmoid(torch.randn(3, 4, requires_grad=True).cuda())).rsample()
torch.mean(d).backward() # throws above exception
```

## System Info

(base) ➜  /tmp python collect_env.py 
Collecting environment information...
PyTorch version: 0.5.0a0+ddc37d7
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Manjaro Linux
GCC version: (GCC) 8.2.0
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 396.54
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] magma-cuda92              2.3.0                         1    pytorch
[conda] torch                     0.5.0a0+ddc37d7           <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): source 
- OS: arch
- Python version: 3.7

**Comment by jramapuram** [comment]
Note that pyro's `Beta` **does** support GPU `rsample` and there are no issues there. So just need to get those changes ported in.

**Comment by rohitrango** [comment]
Can someone please work on it? 
Also, using the `Beta` distribution causes a memory leak in the training loop. Please see this: [`https://github.com/uber/pyro/issues/1499`](https://github.com/uber/pyro/issues/1499)

**Comment by rohitrango** [comment]
I can work on this issue. Please let me know where I can start.

**Comment by tw991** [comment]
Any update on this issue?

**Comment by xb-chang** [comment]
I have the same issue on both version 0.4.1 and 1.0.0.
Seems still not fixed yet?

**Comment by Diego999** [comment]
Any news on this ?

**Comment by gui11aume** [comment]
@jramapuram and @rohitrango, I believe this issue is relatively easy to fix because everything is already available. Sampling the Dirichlet distribution is done using the Gamma distribution (see [Wikipedia](https://en.wikipedia.org/wiki/Dirichlet_distribution#Gamma_distribution)). So in practice one can already use the following workaround:

    import torch
    g = torch.distributions.Gamma(torch.sigmoid(torch.randn(3, 4, requires_grad=True)), 1).rsample()
    d = g / torch.sum(g)
    torch.mean(d).backward() # works!
    g = torch.distributions.Gamma(torch.sigmoid(torch.randn(3, 4, requires_grad=True).cuda()), 1).rsample()
    d = g / torch.sum(g)
    torch.mean(d).backward() # also works!

In principle, to fix the issue, you just need to redirect `rsample()` to `torch.distributions.Gamma`. The same goes for `torch.distributions.Beta`.

I made a similar comment on related issue https://github.com/pytorch/pytorch/issues/15773.
