### ISSUE TITLE
Unclear exception in F.conv2d for wrong out_channels and groups

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#11033]
## Issue description

The error message using `F.conv2d` is unclear when a wrongly shaped `weight` tensor and `groups` are provided, while the thrown error using `nn.Conv2d` gives the reason for the exception.
[Thread](https://github.com/pytorch/pytorch/issues/11033) in the board.

## Code example

```python
cin, cout = 4, 5
groups = 2
x = torch.randn(1, cin, 24, 24)

weight = torch.randn(cout, cin//groups, 3, 3)
# Unclear error message
F.conv2d(x, weight, groups=groups)
> RuntimeError: std::exception
# Proper error message
nn.Conv2d(cin, cout, kernel_size=3, groups=groups)
> ValueError: out_channels must be divisible by groups
```

## System Info
- OS: Ubuntu 16.04.5 LTS
- PyTorch version: 0.5.0a0+6c7fb15 (installed from source)
- Python version: 2.7
- GCC version (if compiling from source): (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- CMake version: 3.11.1

## Possible reason

While the error message for the module is defined [here](https://github.com/pytorch/pytorch/blob/0b1de747329250fbb290411d819bf10edbc1b858/torch/nn/modules/conv.py#L19), the check seems to be missing in the functional version. 
Currently only the `in_channels` are checked [here](https://github.com/pytorch/pytorch/blob/0b1de747329250fbb290411d819bf10edbc1b858/aten/src/ATen/native/Convolution.cpp#L174) and the `weight.size(0)` [here](https://github.com/pytorch/pytorch/blob/0b1de747329250fbb290411d819bf10edbc1b858/aten/src/ATen/native/Convolution.cpp#L165).

Probably this check might solve this issue:
```
if (weight.size(0) % groups != 0) {
    std::stringstream ss;
    ss << "Given groups=" << groups << ", expected weight to be divisible by "
         << groups << " at dimension 0, but got weight of size " << weight.size()
         << " instead";
    throw std::runtime_error(ss.str());
}
```

If this approach is alright, I can submit a PR.

**Comment by soumith** [comment]
that change looks good. do send a PR (thanks!)
