### ISSUE TITLE
UNSTABLE inductor / linux-jammy-cpu-py3.8-gcc11-inductor / test (inductor_torchbench_dynamic_cpu_accuracy)

### ISSUE THREAD

**Issue by PaliC** [pytorch/pytorch#110321]
> Please provide a brief reason on why you need to mark this job as unstable.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
The job looks ok now after https://hud.pytorch.org/pytorch/pytorch/commit/175b626216cf2a1bdc1a32934549295d2e8d1f3f
