### ISSUE TITLE
Local build breakage on AWS cluster

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#110455]
### 🐛 Describe the bug

The build fails after https://github.com/pytorch/pytorch/pull/109986 was merged.

Repro command on AWS hpcaas:
`python setup.py clean && time CCACHE_DIR=/scratch/mlazos/.ccache_dir CXX=g++ CC=gcc USE_CUDA=1 USE_FBGEMM=0 BUILD_NVFUSER=0 USE_MKLDNN=0 python setup.py develop`

Adding BUILD_TEST=0 fixes the issue as a workaround, but this looks like it should be addressed.

### Versions

PyTorch version: 2.2.0a0+gitef5ff79
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.9.16 (main, Jan 11 2023, 16:05:54)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1041-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         2999.998
BogoMIPS:                        5999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.6
[pip3] dalle2-pytorch==1.14.2
[pip3] ema-pytorch==0.0.10
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-transformers==1.2.0
[pip3] pytorch-warmup==0.1.0
[pip3] rotary-embedding-torch==0.1.5
[pip3] torch==2.2.0a0+gitef5ff79
[pip3] torch-fidelity==0.3.0
[pip3] torch_geometric==2.4.0
[pip3] torch-optimizer==0.1.0
[pip3] torch-struct==0.5
[pip3] torchfile==0.1.0
[pip3] torchmetrics==0.10.0
[pip3] torchrec-nightly==2022.8.18
[pip3] torchx-nightly==2022.8.18
[pip3] triton==2.1.0
[pip3] vector-quantize-pytorch==0.9.2
[conda] blas                      1.0                         mkl  
[conda] clip-anytorch             2.5.2                    pypi_0    pypi
[conda] coca-pytorch              0.0.6                    pypi_0    pypi
[conda] dalle2-pytorch            1.14.2                   pypi_0    pypi
[conda] ema-pytorch               0.0.10                   pypi_0    pypi
[conda] functorch                 1.14.0a0+b71aa0b          pypi_0    pypi
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.1.0           h06a4308_224  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] open-clip-torch           2.20.0                   pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] pytorch-warmup            0.1.0                    pypi_0    pypi
[conda] rotary-embedding-torch    0.1.5                    pypi_0    pypi
[conda] torch                     2.2.0a0+gitef5ff79           dev_0    <develop>
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torchaudio                2.1.0a0+406e9c8           dev_0    <develop>
[conda] torchdata                 0.7.0a0+901b483           dev_0    <develop>
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchmetrics              0.10.0                   pypi_0    pypi
[conda] torchrec-nightly          2022.8.18                pypi_0    pypi
[conda] torchtext                 0.14.0a0+e1b6984          pypi_0    pypi
[conda] torchvision               0.16.0a0+498b9c8           dev_0    <develop>
[conda] torchx-nightly            2022.8.18                pypi_0    pypi
[conda] triton                    2.1.0                     dev_0    <develop>
[conda] vector-quantize-pytorch   0.9.2                    pypi_0    pypi

cc @malfet @seemethere

**Comment by mlazos** [comment]
build log:

https://gist.github.com/mlazos/d2199e2311974e27ed8338745025291c

**Comment by cyyever** [comment]
@mlazos  @colesbury caffe2::Threads is used nowhere. Try to remove the build dir, re-run cmake and it should work.

**Comment by cyyever** [comment]
@mlazos @colesbury caffe2::Threads is used nowhere in PyTorch ecosystem as I can't find it out by GitHub search, the error should be cause by stale cache; try to remove the build dir, re-run cmake and it should work. If it still can't work, caffe2::Threads requirement may be imposed from current install of PyTorch; try to uninstall it before you start a clean build.

**Comment by mlazos** [comment]
I fully cleaned the build dir - is it used by any dependencies? I'm building from source btw

**Comment by cyyever** [comment]
@mlazos  Can you add --trace and --debug-output options to the cmake command line to generate more detailed call stack. It may help find out which old CMake module requiring Caffe2::Threads.

**Comment by t-vi** [comment]
IME, a likely source is the old patching in submodules from 1.x, e.g.:

https://github.com/pytorch/pytorch/blob/49444c3e546bf240bed24a101e747422d1f8a0ee/cmake/GoogleTestPatch.cmake#L23

Of course, a clean checkout should help that, but it seems not so nice to debug.

**Comment by mlazos** [comment]
We're winding down the AWS cluster, so closing.
