### ISSUE TITLE
Probable error/dead code in fx_utils.py

### ISSUE THREAD

**Issue by int3** [pytorch/pytorch#110482]
Details in https://github.com/pytorch/pytorch/pull/109415/files/4d117b5a2f38fd4d676285940b29b50d9d0fccaa#r1327890439

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by Chillee** [comment]
Fixing in this PR: https://github.com/pytorch/pytorch/pull/110464
