### ISSUE TITLE
[optim]: Adagrad with sparse grad is not on multi_tensor testing path + bug

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#110444]
### 🐛 Describe the bug

Bug: should not return here, just call the function
https://github.com/pytorch/pytorch/blob/b25e2f2b5e6bb95fc83a81bca23706bd6f08ae76/torch/optim/adagrad.py#L327

Solution: fix this, and add adagrad sparse to testing path (test_optim, inductor test)

### Versions

Main

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by janeyx99** [comment]
We return here to prevent the function from continuing to run. We could have it run and just return nothing after, but it doesn't seem like that would make a big difference. I may be missing something though and you should let me know.

We should indeed add adagrad sparse to the testing path.

**Comment by jon-chuang** [comment]
The bug is that returning rather than `continue` incorrectly early exits when `len(groups) > 1`

**Comment by janeyx99** [comment]
oh dang

yes that is correct
