### ISSUE TITLE
Windows 10  error LNK2001 and fatal error LNK1120

### ISSUE THREAD

**Issue by zhan2585** [pytorch/pytorch#11041]
## Issue description
I try to install pytorch from source on windows and I got error as following:
`Creating library build\temp.win32-3.6\Release\torch/csrc\_C.cp36-win32.lib and object build\temp.win32-3.6\Release\torch/csrc\_C.cp36-win32.exp
DataLoader.obj : error LNK2001: unresolved external symbol __imp__Py_NoneStruct
Device.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_AsEncodedString
Device.obj : error LNK2001: unresolved external symbol __imp_PyBaseObject_Type
Device.obj : error LNK2001: unresolved external symbol __imp_PyMem_Calloc
Device.obj : error LNK2001: unresolved external symbol __imp_PyCFunction_Type
Device.obj : error LNK2001: unresolved external symbol __imp_PyWeakref_NewRef
Device.obj : error LNK2001: unresolved external symbol __imp_PyThreadState_Get
Device.obj : error LNK2001: unresolved external symbol __imp_PyThread_delete_key_value
Device.obj : error LNK2001: unresolved external symbol __imp_PyThread_get_key_value
Device.obj : error LNK2001: unresolved external symbol __imp_PyImport_ImportModule
Device.obj : error LNK2001: unresolved external symbol __imp_PyBytes_AsString
Device.obj : error LNK2001: unresolved external symbol __imp_PyErr_NormalizeException
Device.obj : error LNK2001: unresolved external symbol __imp_PyErr_Occurred
Device.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_DecodeUTF8
Device.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_AsUTF8AndSize
Device.obj : error LNK2001: unresolved external symbol __imp_PyEval_SaveThread
Device.obj : error LNK2001: unresolved external symbol __imp__PyThreadState_UncheckedGet
Device.obj : error LNK2001: unresolved external symbol __imp_PyExc_RuntimeError
Device.obj : error LNK2001: unresolved external symbol __imp_PyObject_SetAttrString
Device.obj : error LNK2001: unresolved external symbol __imp_PyInstanceMethod_Type
Device.obj : error LNK2001: unresolved external symbol __imp_Py_BuildValue
Device.obj : error LNK2001: unresolved external symbol __imp_PyExc_MemoryError
Device.obj : error LNK2001: unresolved external symbol __imp_PyCapsule_GetContext
Device.obj : error LNK2001: unresolved external symbol __imp_PyFrame_GetLineNumber
Device.obj : error LNK2001: unresolved external symbol __imp_PyGILState_Release
Device.obj : error LNK2001: unresolved external symbol __imp_PyBytes_AsStringAndSize
Device.obj : error LNK2001: unresolved external symbol __imp_PyTuple_New
Device.obj : error LNK2001: unresolved external symbol __imp_PyDict_Size
Device.obj : error LNK2001: unresolved external symbol __imp_PyLong_FromLongLong
Device.obj : error LNK2001: unresolved external symbol __imp_PyErr_SetString
Device.obj : error LNK2001: unresolved external symbol __imp_PyExc_ValueError
Device.obj : error LNK2001: unresolved external symbol __imp_PyDict_Next
Device.obj : error LNK2001: unresolved external symbol __imp_PyBool_Type
Device.obj : error LNK2001: unresolved external symbol __imp_PyThreadState_New
Device.obj : error LNK2001: unresolved external symbol __imp__Py_FalseStruct
Device.obj : error LNK2001: unresolved external symbol __imp_PyErr_Restore
Device.obj : error LNK2001: unresolved external symbol __imp_PyTuple_GetItem
Device.obj : error LNK2001: unresolved external symbol __imp_PyCapsule_GetPointer
Device.obj : error LNK2001: unresolved external symbol __imp_PyModule_AddObject
Device.obj : error LNK2001: unresolved external symbol __imp_PyErr_Fetch
Device.obj : error LNK2001: unresolved external symbol __imp_PyObject_ClearWeakRefs
Device.obj : error LNK2001: unresolved external symbol __imp_PyList_New
Device.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_DecodeUTF16
Device.obj : error LNK2001: unresolved external symbol __imp_PyType_Ready
Device.obj : error LNK2001: unresolved external symbol __imp_PyObject_GetAttrString
Device.obj : error LNK2001: unresolved external symbol __imp_PyErr_Clear
Device.obj : error LNK2001: unresolved external symbol __imp_PyList_Append
Device.obj : error LNK2001: unresolved external symbol __imp_PyTuple_Size
Device.obj : error LNK2001: unresolved external symbol __imp_PyException_SetTraceback
Device.obj : error LNK2001: unresolved external symbol __imp_PyLong_AsLongLongAndOverflow
Device.obj : error LNK2001: unresolved external symbol __imp_PyCapsule_New
Device.obj : error LNK2001: unresolved external symbol __imp_PyCapsule_GetName
Device.obj : error LNK2001: unresolved external symbol __imp_PyBytes_Size
Device.obj : error LNK2001: unresolved external symbol __imp_PyDict_New
Device.obj : error LNK2001: unresolved external symbol __imp_PyInstanceMethod_New
Device.obj : error LNK2001: unresolved external symbol __imp_PyObject_IsInstance
Device.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_DecodeUTF32
Device.obj : error LNK2001: unresolved external symbol __imp_PyMem_Free
Device.obj : error LNK2001: unresolved external symbol __imp_PyTuple_SetItem
Device.obj : error LNK2001: unresolved external symbol __imp_PyDict_GetItemString
Device.obj : error LNK2001: unresolved external symbol __imp_PyThread_create_key
Device.obj : error LNK2001: unresolved external symbol __imp_PyObject_GetItem
Device.obj : error LNK2001: unresolved external symbol __imp_PyObject_CallObject
Device.obj : error LNK2001: unresolved external symbol __imp_PyEval_InitThreads
Device.obj : error LNK2001: unresolved external symbol __imp_PyObject_HasAttrString
Device.obj : error LNK2001: unresolved external symbol __imp_PyProperty_Type
Device.obj : error LNK2001: unresolved external symbol __imp__Py_NotImplementedStruct
Device.obj : error LNK2001: unresolved external symbol __imp_PyGILState_Ensure
Device.obj : error LNK2001: unresolved external symbol __imp_PyCapsule_SetContext
Device.obj : error LNK2001: unresolved external symbol __imp_PyThreadState_DeleteCurrent
Device.obj : error LNK2001: unresolved external symbol __imp_PyExc_TypeError
Device.obj : error LNK2001: unresolved external symbol __imp_PyThreadState_Clear
Device.obj : error LNK2001: unresolved external symbol __imp_PyCFunction_NewEx
Device.obj : error LNK2001: unresolved external symbol __imp_PyCapsule_Type
Device.obj : error LNK2001: unresolved external symbol __imp_PyEval_GetBuiltins
Device.obj : error LNK2001: unresolved external symbol __imp_PyDict_Copy
Device.obj : error LNK2001: unresolved external symbol __imp_PyObject_Str
Device.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_AsUTF8String
Device.obj : error LNK2001: unresolved external symbol __imp_PyExc_IndexError
Device.obj : error LNK2001: unresolved external symbol __imp__Py_TrueStruct
Device.obj : error LNK2001: unresolved external symbol __imp_PyExc_SystemError
Device.obj : error LNK2001: unresolved external symbol __imp_PyObject_SetItem
Device.obj : error LNK2001: unresolved external symbol __imp_PyDict_DelItemString
Device.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_FromString
Device.obj : error LNK2001: unresolved external symbol __imp_PyEval_AcquireThread
Device.obj : error LNK2001: unresolved external symbol __imp__PyType_Lookup
Device.obj : error LNK2001: unresolved external symbol __imp_PyObject_Repr
Device.obj : error LNK2001: unresolved external symbol __imp_PyType_Type
Device.obj : error LNK2001: unresolved external symbol __imp_PyThread_set_key_value
Device.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetDictPtr
Exceptions.obj : error LNK2001: unresolved external symbol __imp_PyErr_NewException
Generator.obj : error LNK2001: unresolved external symbol __imp_PyLong_FromUnsignedLongLong
Generator.obj : error LNK2001: unresolved external symbol __imp_PyObject_Call
Module.obj : error LNK2001: unresolved external symbol __imp__Py_CheckRecursionLimit
Module.obj : error LNK2001: unresolved external symbol __imp_PyErr_WarnEx
Module.obj : error LNK2001: unresolved external symbol __imp_PyExc_RuntimeWarning
Module.obj : error LNK2001: unresolved external symbol __imp_PyLong_FromLong
Module.obj : error LNK2001: unresolved external symbol __imp_PyTuple_GetSlice
Module.obj : error LNK2001: unresolved external symbol __imp_PyErr_Format
Module.obj : error LNK2001: unresolved external symbol __imp_PySequence_Fast
Module.obj : error LNK2001: unresolved external symbol __imp_PyModule_Create2
Module.obj : error LNK2001: unresolved external symbol __imp_PyArg_ParseTuple
Module.obj : error LNK2001: unresolved external symbol __imp_PyCapsule_SetName
Module.obj : error LNK2001: unresolved external symbol __imp_PyEval_RestoreThread
Size.obj : error LNK2001: unresolved external symbol __imp_PyTuple_Type
Size.obj : error LNK2001: unresolved external symbol __imp_PyObject_CallFunctionObjArgs
Size.obj : error LNK2001: unresolved external symbol __imp_PyLong_AsLong
Size.obj : error LNK2001: unresolved external symbol __imp_PyNumber_Index
Size.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_FromStringAndSize
Storage.obj : error LNK2001: unresolved external symbol __imp_PySequence_Size
Storage.obj : error LNK2001: unresolved external symbol __imp_PyBool_FromLong
Storage.obj : error LNK2001: unresolved external symbol __imp_PySlice_Type
Storage.obj : error LNK2001: unresolved external symbol __imp_PySequence_GetItem
Storage.obj : error LNK2001: unresolved external symbol __imp_PyFloat_AsDouble
Storage.obj : error LNK2001: unresolved external symbol __imp_PyBytes_FromString
Storage.obj : error LNK2001: unresolved external symbol __imp_PyLong_AsLongLong
Storage.obj : error LNK2001: unresolved external symbol __imp_PyFloat_FromDouble
Storage.obj : error LNK2001: unresolved external symbol __imp_PyFloat_Type
Storage.obj : error LNK2001: unresolved external symbol __imp_PyType_IsSubtype
Storage.obj : error LNK2001: unresolved external symbol __imp_PyObject_GetBuffer
Storage.obj : error LNK2001: unresolved external symbol __imp_PySequence_Check
Storage.obj : error LNK2001: unresolved external symbol __imp_PyLong_FromVoidPtr
Storage.obj : error LNK2001: unresolved external symbol __imp_PyObject_AsFileDescriptor
Storage.obj : error LNK2001: unresolved external symbol __imp_PyLong_AsVoidPtr
Storage.obj : error LNK2001: unresolved external symbol __imp_PySlice_GetIndicesEx
Storage.obj : error LNK2001: unresolved external symbol __imp_PyArg_ParseTupleAndKeywords
Storage.obj : error LNK2001: unresolved external symbol __imp_PyBuffer_Release
init.obj : error LNK2001: unresolved external symbol __imp_PyModule_New
python_torch_functions.obj : error LNK2001: unresolved external symbol __imp_PyExc_UserWarning
python_variable_methods.obj : error LNK2001: unresolved external symbol __imp_PyLong_FromDouble
init.obj : error LNK2001: unresolved external symbol __imp_PyExc_BufferError
init.obj : error LNK2001: unresolved external symbol __imp_PyObject_SetAttr
init.obj : error LNK2001: unresolved external symbol __imp_PyLong_AsUnsignedLong
init.obj : error LNK2001: unresolved external symbol __imp_PyObject_Malloc
init.obj : error LNK2001: unresolved external symbol __imp_PyLong_FromSsize_t
init.obj : error LNK2001: unresolved external symbol __imp_PyLong_AsUnsignedLongLong
init.obj : error LNK2001: unresolved external symbol __imp_PyList_Size
init.obj : error LNK2001: unresolved external symbol __imp_PyLong_FromUnsignedLong
init.obj : error LNK2001: unresolved external symbol __imp_PyMethod_Type
init.obj : error LNK2001: unresolved external symbol __imp_PyErr_ExceptionMatches
init.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_FromFormat
init.obj : error LNK2001: unresolved external symbol __imp_PyList_GetItem
init.obj : error LNK2001: unresolved external symbol __imp_PyNumber_Check
init.obj : error LNK2001: unresolved external symbol __imp_PyNumber_Long
init.obj : error LNK2001: unresolved external symbol __imp_PyModule_Type
init.obj : error LNK2001: unresolved external symbol __imp_PyLong_FromSize_t
init.obj : error LNK2001: unresolved external symbol __imp_PyNumber_Float
init.obj : error LNK2001: unresolved external symbol __imp_PySequence_Tuple
python_anomaly_mode.obj : error LNK2001: unresolved external symbol __imp_PyDict_SetItemString
python_anomaly_mode.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_Join
python_anomaly_mode.obj : error LNK2001: unresolved external symbol __imp_PyObject_CallMethod
python_function.obj : error LNK2001: unresolved external symbol __imp_PyExc_DeprecationWarning
python_function.obj : error LNK2001: unresolved external symbol __imp_PyObject_GC_UnTrack
python_variable_indexing.obj : error LNK2001: unresolved external symbol __imp_PySlice_Unpack
python_variable_indexing.obj : error LNK2001: unresolved external symbol __imp__Py_EllipsisObject
python_variable_indexing.obj : error LNK2001: unresolved external symbol __imp_PyTuple_Pack
BatchTensor.obj : error LNK2001: unresolved external symbol __imp_PyModule_GetName
BatchTensor.obj : error LNK2001: unresolved external symbol __imp_PyImport_AddModule
init.obj : error LNK2001: unresolved external symbol __imp_PyDict_Contains
init.obj : error LNK2001: unresolved external symbol __imp_PyIter_Next
init.obj : error LNK2001: unresolved external symbol __imp_PyObject_GetIter
init.obj : error LNK2001: unresolved external symbol __imp_PyExc_StopIteration
init.obj : error LNK2001: unresolved external symbol __imp_PyBytes_FromStringAndSize
init.obj : error LNK2001: unresolved external symbol __imp_PyCallable_Check
python_arg_flatten.obj : error LNK2001: unresolved external symbol __imp_PyList_SetItem
python_ir.obj : error LNK2001: unresolved external symbol __imp_PyObject_RichCompareBool
python_tracer.obj : error LNK2001: unresolved external symbol __imp_PyCode_Addr2Line
serialization.obj : error LNK2001: unresolved external symbol __imp_PyLong_AsSsize_t
serialization.obj : error LNK2001: unresolved external symbol __imp_PyMemoryView_FromMemory
python_tensor.obj : error LNK2001: unresolved external symbol __imp_PySet_Add
python_tensor.obj : error LNK2001: unresolved external symbol __imp_PyDict_Merge
python_arg_parser.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_InternFromString
python_arg_parser.obj : error LNK2001: unresolved external symbol __imp_PyDict_GetItem
build\lib.win32-3.6\torch\_C.cp36-win32.pyd : fatal error LNK1120: 173 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX64\\x64\\link.exe' failed with exit status 1120`

Is anyone having the same issues? 

## System Info
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): cmake
- OS: windows 10
- PyTorch version: master
- Python version: 3.6.3
- CMake version: 3.12.1

**Comment by peterjc123** [comment]
Are you building PyTorch for Python x86? It is actually not supported. Please use Python x64 instead.

**Comment by zhan2585** [comment]
It might be the issue.

I have downloaded python-3.6.6-amd64 and installed pytorch using pip. It succeed!
But thanks for the kind reply.
