### ISSUE TITLE
Lambda LR is not working as expected for custom linear scheduler

### ISSUE THREAD

**Issue by Enmartz** [pytorch/pytorch#110480]
### 🐛 Describe the bug

I am trying to implement a linear scheduler using your functions but it is not working properly.

**Implemented code**

```
import matplotlib.pyplot as plt
import torch
import torch.optim as optim
from torch.optim.lr_scheduler import LambdaLR


# Linear learning rate decay function
def linear_lr_decay(epoch, max_epochs, lr_start, lr_end):
    slope = (lr_end - lr_start) / max_epochs
    return lr_start + slope * epoch

# Number of epochs, initial/final learning rates
num_epochs = 100
lr_start = 4e-4
lr_end = 1e-5

# Dummy optimizer (replace with your own optimizer)
model = torch.nn.Linear(10, 1)
optimizer = optim.Adam(model.parameters(), lr=lr_start)

# Create a LambdaLR scheduler with linear decay
scheduler = LambdaLR(optimizer, lambda epoch: linear_lr_decay(epoch, num_epochs, lr_start, lr_end))
# scheduler = LinearLR(optimizer, start_factor=0.8, total_iters=num_epochs)


# Simulate training and log the learning rates
learning_rates = []
for epoch in range(num_epochs):
    # Step the scheduler to update the learning rate
    learning_rates.append(scheduler.get_last_lr()[0])
    optimizer.step()
    scheduler.step()

# Plotting the learning rate
plt.figure(figsize=(10, 6))
plt.plot(range(num_epochs), learning_rates, label='Linear Learning Rate Schedule', color='blue')
plt.xlabel('Epochs')
plt.ylabel('Learning Rate')
plt.title('Linear Learning Rate Schedule')
plt.legend()
plt.grid(True)
plt.show()

```

**Output**

![myplot](https://github.com/pytorch/pytorch/assets/58752635/7d9e04cb-e38a-41bc-a8d7-6d931820fd05)

As you can see, it was expected to have a learning rate between 4e-4 to 1e-5, but this didn't happen.

### Versions

--2023-10-03 17:11:53--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21709 (21K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py      100%[===================>]  21,20K  --.-KB/s    in 0,004s  

2023-10-03 17:11:53 (5,59 MB/s) - ‘collect_env.py’ saved [21709/21709]

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.2.0-33-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 535.113.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      48 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             12
On-line CPU(s) list:                0-11
Vendor ID:                          AuthenticAMD
Model name:                         AMD Ryzen 5 5600X 6-Core Processor
CPU family:                         25
Model:                              33
Thread(s) per core:                 2
Core(s) per socket:                 6
Socket(s):                          1
Stepping:                           2
Frequency boost:                    enabled
CPU max MHz:                        5278,7100
CPU min MHz:                        2200,0000
BogoMIPS:                           8399.67
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                     AMD-V
L1d cache:                          192 KiB (6 instances)
L1i cache:                          192 KiB (6 instances)
L2 cache:                           3 MiB (6 instances)
L3 cache:                           32 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-11
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] numpydoc==1.5.0
[pip3] torch==1.12.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.23.5          py310hd5efca6_0  
[conda] numpy-base                1.23.5          py310h8e6c178_0  
[conda] numpydoc                  1.5.0           py310h06a4308_0  
[conda] pytorch                   1.12.1          cpu_py310hb1f1ab4_1

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by msaroufim** [comment]
There were 2 bugs

1. `slope = (lr_end - lr_start) / (max_epochs -1)`
2. `scheduler = LambdaLR(optimizer, lambda epoch: linear_lr_decay(epoch, num_epochs, lr_start, lr_end) / lr_start)`

Then you get the values you expect

`    print("{:.2e}".format(scheduler.get_last_lr()[0]))`

```
4.00e-04
3.96e-04
3.92e-04
3.88e-04
3.84e-04
3.80e-04
3.76e-04
3.72e-04
3.68e-04
3.65e-04
3.61e-04
3.57e-04
3.53e-04
3.49e-04
3.45e-04
3.41e-04
3.37e-04
3.33e-04
3.29e-04
3.25e-04
3.21e-04
3.17e-04
3.13e-04
3.09e-04
3.05e-04
3.02e-04
2.98e-04
2.94e-04
2.90e-04
2.86e-04
2.82e-04
2.78e-04
2.74e-04
2.70e-04
2.66e-04
2.62e-04
2.58e-04
2.54e-04
2.50e-04
2.46e-04
2.42e-04
2.38e-04
2.35e-04
2.31e-04
2.27e-04
2.23e-04
2.19e-04
2.15e-04
2.11e-04
2.07e-04
2.03e-04
1.99e-04
1.95e-04
1.91e-04
1.87e-04
1.83e-04
1.79e-04
1.75e-04
1.72e-04
1.68e-04
1.64e-04
1.60e-04
1.56e-04
1.52e-04
1.48e-04
1.44e-04
1.40e-04
1.36e-04
1.32e-04
1.28e-04
1.24e-04
1.20e-04
1.16e-04
1.12e-04
1.08e-04
1.05e-04
1.01e-04
9.67e-05
9.27e-05
8.88e-05
8.48e-05
8.09e-05
7.70e-05
7.30e-05
6.91e-05
6.52e-05
6.12e-05
5.73e-05
5.33e-05
4.94e-05
4.55e-05
4.15e-05
3.76e-05
3.36e-05
2.97e-05
2.58e-05
2.18e-05
1.79e-05
1.39e-05
1.00e-05
```

**Comment by Enmartz** [comment]
That is right, the code works properly now. Thanks!
