### ISSUE TITLE
CrossEntropyLoss causes kernel to die when using mps

### ISSUE THREAD

**Issue by tonyPo** [pytorch/pytorch#110463]
### 🐛 Describe the bug

If I calculate the cross entropy loss between two vectors on device=mps, then the python kernel crashed. The same code on device=CPU works correctly.

Code to reproduce
The following code crashes:
```python
import torch
import torch.nn as nn
inputs = torch.Tensor([[0, 1], [1.0, 0], [0, 1]]).to("mps")
targets = torch.LongTensor([1, 0, 1]).to("mps")
loss = nn.CrossEntropyLoss()
loss(inputs, targets)
```

result in the following error message
```python
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
```

The following code works correctly:
```python
import torch
import torch.nn as nn
inputs = torch.Tensor([[0, 1], [1.0, 0], [0, 1]]).to("cpu")
targets = torch.LongTensor([1, 0, 1]).to("cpu")
loss = nn.CrossEntropyLoss()
loss(inputs, targets)
```

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.0 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] torch==2.0.1
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
Could you try running the code in a regular Python runtime, i.e. not in IPython/Jupyter?

**Comment by tonyPo** [comment]
Dear Allan,

Good point. It turns out that if I run it in a regular runtime, then I already get the below error during the import statement of torch

'''python
import torch
import torch.nn as nn
inputs = torch.Tensor([[0, 1], [1.0, 0], [0, 1]]).to("mps")
targets = torch.LongTensor([1, 0, 1]).to("mps")
loss = nn.CrossEntropyLoss()
loss(inputs, targets)
'''

Result in the error

'''
Traceback (most recent call last):
  File "xxx/test_pytorch.py", line 1, in <module>
    import torch
  File "xxx/lib/python3.11/site-packages/torch/__init__.py", line 1476, in <module>
    from torch import func as func
  File "xxx/lib/python3.11/site-packages/torch/func/__init__.py", line 1, in <module>
    from torch._functorch.eager_transforms import (
  File "/xxxr/lib/python3.11/site-packages/torch/_functorch/eager_transforms.py", line 13, in <module>
    from torch.fx.experimental.proxy_tensor import make_fx
  File "/xxx/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 13, in <module>
    from torch._dispatch.python import enable_python_dispatcher
  File "/xxx/lib/python3.11/site-packages/torch/_dispatch/python.py", line 3, in <module>
    import unittest.mock
ModuleNotFoundError: No module named 'unittest.mock'
'''

**Comment by albanD** [comment]
This is a builtin module from cpython so this is most likely caused by bad config.
Can you double check that your python version and all libraries (including pytest, etc) are for your current version of cpython (which seems to be 3.11.5 and not an older version)?

**Comment by tonyPo** [comment]
Dear Albany,

I'm happy to check this, but to be honest I've got no idea how to do this. Could you give me some guidance how to check this? Maybe good to mention that I use Conda.

**Comment by qqaatw** [comment]
> Dear Albany,
> 
> 
> 
> I'm happy to check this, but to be honest I've got no idea how to do this. Could you give me some guidance how to check this? Maybe good to mention that I use Conda.
> 
> 
> 
> 

What I would recommend is to create a fresh Conda environment and install PyTorch and the dependencies needed. After that, check if everything is alright or not.

**Comment by malfet** [comment]
@tonyPo can you explain how you've installed python runtime? (For example can you run `which python` and share the output?)
Judging by "3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ] (64-bit runtime)" I suspect it comes from homebrew, but  my homebrew's python was build on Aug 24th and includes unittest mock:
```
% /opt/homebrew/bin/python3.11
Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import unittest.mock
>>> unittest.mock.__file__
'/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/mock.py'

```

**Comment by tonyPo** [comment]
@malfet, qqaatw
The issue is indeed related to my python installation. I recently switch from an old Mac to a new Mac with an M2 processor. During the migration of the MacBook, numerous Python config files were copied that were not compatible with the M2/arm platform. Hence I had to removed all these and installed python with the package manager, then I installed Conda with the package manager and created an Conda environment. 

I've kind of traced done that the unittest.mock issue is related to the combination VScode and anaconda. I haven't got the exact root cause, but when I restart the computer and create a fresh anaconda environment, then I'm able to import the unites.mock without errors. The file is located in "~/anaconda3/envs/tigger/lib/python3.11/unittest/mock.py"

If I try to run the original code for computing the crossentropy loss on the MPS in the terminal for a new Conda environment then it work fine. However in the original environment I get the following error code:

''' python
Bus error: 10
'''

When I run the code on the CPU then it work correctly.

Both environments have the same python version (and build time), hence I guess it is related to conflicting dependencies.
I will create a new environment and delete the old one. I assume that will resolve the issue.

Thank you for looking into this. Very much appreciated.

**Comment by Wongboo** [comment]
> Dear Allan,
> 
> Good point. It turns out that if I run it in a regular runtime, then I already get the below error during the import statement of torch
> 
> ```python
> import torch
> import torch.nn as nn
> inputs = torch.Tensor([[0, 1], [1.0, 0], [0, 1]]).to("mps")
> targets = torch.LongTensor([1, 0, 1]).to("mps")
> loss = nn.CrossEntropyLoss()
> loss(inputs, targets)
> ```
> 
> Result in the error
> 
> ```
> Traceback (most recent call last):
>   File "xxx/test_pytorch.py", line 1, in <module>
>     import torch
>   File "xxx/lib/python3.11/site-packages/torch/__init__.py", line 1476, in <module>
>     from torch import func as func
>   File "xxx/lib/python3.11/site-packages/torch/func/__init__.py", line 1, in <module>
>     from torch._functorch.eager_transforms import (
>   File "/xxxr/lib/python3.11/site-packages/torch/_functorch/eager_transforms.py", line 13, in <module>
>     from torch.fx.experimental.proxy_tensor import make_fx
>   File "/xxx/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 13, in <module>
>     from torch._dispatch.python import enable_python_dispatcher
>   File "/xxx/lib/python3.11/site-packages/torch/_dispatch/python.py", line 3, in <module>
>     import unittest.mock
> ModuleNotFoundError: No module named 'unittest.mock'
> ```

I have the same kind of error, but when running the demo code results in
```
[1]    36123 bus error  python
```

**Comment by Wongboo** [comment]
Sorry, it's by a completely different new bug, see #112014
