### ISSUE TITLE
bug(aten): poor support for aten `foreach_abs`

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#110458]
### 🐛 Describe the bug
 `aten._foreach_abs` is extern and hence obstructs fusion and `aten._foreach_abs_` has no Meta kernel
 
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
NotImplementedError: aten::_foreach_abs_: attempted to run this operator with Meta tensors, but there was no abstract impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add an abstract impl.Please see the following doc for next steps: https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU/edit

While executing %_foreach_abs_ : [num_users=0] = call_function[target=torch._foreach_abs_](args = ([%x_4, %x_5, %x_6, %x_7],), kwargs = {})
Original traceback:
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/test/inductor/test_compiled_optimizers.py", line 63, in fn
    step_fn(opt_compiled)
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/optim/adamax.py", line 124, in step
    adamax(
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/optim/adamax.py", line 230, in adamax
    func(
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/optim/adamax.py", line 354, in _multi_tensor_adamax
    torch._foreach_abs_(grouped_grads)
```

EDIT:
1. These are actually 2 separate issues: meta kernel can be solved easily with meta registration
2. Why these kernels are extern is yet undiagnosed. Here are two cases:
    - `cannot fuse (1): node1 buf12: ExternKernelSchedulerNode(FallbackKernel)`,`buf12.node.kernel = aten._foreach_abs`
    - `cannot fuse (2): node2 buf14: ExternKernelSchedulerNode(MultiOutput)`,`buf14.node.kernel = None`

In all likelihood, foreach abs has no prim decomp, and hence necessitates fallback.

### Versions

main

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by eellison** [comment]
cc @janeyx99  @mlazos

**Comment by janeyx99** [comment]
We'd take a PR adding a meta registration for _foreach_abs--if that also solves the extern situation, yay.

**Comment by jon-chuang** [comment]
> if that also solves the extern situation, yay.

It did not, so I'm investigating adding a prim decomp for abs as foreach_abs triggers a fallback kernel.

Could you provide any guidance on adding prim decomp for aten ops?

**Comment by janeyx99** [comment]
cc @mlazos have you seen/dealt with a similar problem like this before?

**Comment by janeyx99** [comment]
Oh, I didn't realize there was that update. Thanks for confirming!
