### ISSUE TITLE
DynamicShapesExportTests::test_retracibility_dynamic_shapes times out with ASAN

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#110416]
The test has been timing out for some time, succeeding on retries.

Now it reliably times out: 
see linux-jammy-py3.9-clang12-asan / test (default, 2, 6, linux.4xlarge) at
https://hud.pytorch.org/pytorch/pytorch/commit/16e3f158b947c2c14a98178670f22c047a40807c

> dynamo/test_dynamic_shapes.py::DynamicShapesExportTests::test_retracibility_dynamic_shapes <- test/dynamo/test_export.py Command took >30min, returning 124

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by williamwen42** [comment]
Please re-open if https://github.com/pytorch/pytorch/pull/110414 did not solve this.
