### ISSUE TITLE
[MPS] Unsupported operand type for * with complex tensors

### ISSUE THREAD

**Issue by gautierronan** [pytorch/pytorch#110537]
### 🐛 Describe the bug

```python
import torch
import torch.nn as nn

class MyModule(nn.Module):
    def __init__(self, x, y):
        super().__init__()
        self.register_parameter("x", nn.Parameter(x))
        self.register_buffer("y", y)

x = torch.rand(3, dtype=torch.complex64)
y = torch.rand(3, dtype=torch.complex64)
model = MyModule(x, y).to(device="mps")
model.x * model.y
```
returns
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 17
     15 device = torch.device("mps")
     16 model = MyModule(x, y).to(device)
---> 17 model.forward()

Cell In[1], line 11, in MyModule.forward(self)
     10 def forward(self):
---> 11     return self.x * self.y

TypeError: unsupported operand type(s) for *: 'Parameter' and 'Tensor'
```

### Versions

PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.0 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] torch==2.1.0
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] torch                     2.1.0                    pypi_0    pypi

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by gautierronan** [comment]
Related I guess:
```python
import torch
x = torch.ones(3, dtype=torch.complex64, device='mps')
# TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.
```

**Comment by qqaatw** [comment]
Tentatively assigned myself.

**Comment by qqaatw** [comment]
For the script you pasted in the issue description, it works on my side without the error. 

Confirmed that the following line caused error and it's fixed by the linked issue:

`x = torch.ones(3, dtype=torch.complex64, device='mps')`
