### ISSUE TITLE
[torch.compile] Multiple set operations don't work

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#110599]
### 🐛 Describe the bug

Originally reported by @fmassa 

Examples:
```py
@torch.compile(backend="eager", fullgraph=True)
def f(x):
    y = set({1, 2, 3})
    if 1 in y:
        return x
    return x - 1

f(x)
x = torch.randn(3)
```
```py
y = set({1, 2, 3})
@torch.compile(backend="eager", fullgraph=True)
def f(x):
     if x in y:
         return 1
     return 0

x = torch.randn(3)
f(x)
```

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jon-chuang** [comment]
it seems like https://github.com/pytorch/pytorch/pull/108189 could only handle case where set is instantiated from within compile.

**Comment by eellison** [comment]
cc @lezcano who was making changes to set recently

**Comment by lezcano** [comment]
I'll make sure these work after https://github.com/pytorch/pytorch/pull/110524

**Comment by lezcano** [comment]
Fixed in main.
