### ISSUE TITLE
automate the full source tarball release asset (sdist)

### ISSUE THREAD

**Issue by stefantalpalaru** [pytorch/pytorch#110569]
### 🚀 The feature, motivation and pitch

This release asset - pytorch-vX.Y.Z.tar.gz - appears a few weeks after an official release, like an afterthought, yet is crucial for source-based packages, because it contains all Git submodules: https://github.com/stefantalpalaru/gentoo-overlay/blob/c69c2c2be65abe76649493af8c1099fb406806e7/sci-libs/caffe2/caffe2-2.0.1-r101.ebuild#L14-L16

Please generate it automatically, using a CI workflow, and make sure it runs when a new release is created.

**Comment by malfet** [comment]
We automatically build the release, but not sure if there is a good way to automate attaching it to the tag, 
But we definitely should publish it shortly after the tag is created. cc: @atalman

**Comment by malfet** [comment]
Ok, there is even an automation in place, but I wonder why it did not work this time:
https://github.com/pytorch/pytorch/blob/main/.github/workflows/create_release.yml

**Comment by malfet** [comment]
Ok, I have an idea what is going wrong: concurrencly limits are wrong:
<img width="998" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/01925dba-40e1-4616-8bef-28d42653c53d">

**Comment by stefantalpalaru** [comment]
Can you have cancelling depend on "github.event_name"?

**Comment by malfet** [comment]
Yep, or we don't have to run it on `tag` events at all, but rather on `release` only. PR is coming and hopefully in 2.1.1 it will be published as soon as release is live

**Comment by malfet** [comment]
Let's keep this one open to cherry-pick then change in 2.1.1 and make sure that sources are automatically published as well as runbook updated....

**Comment by atalman** [comment]
need to validate when publishing the release
