### ISSUE TITLE
error in install torch 

### ISSUE THREAD

**Issue by Nguyendai202** [pytorch/pytorch#110503]
### 🐛 Describe the bug

----> 1 detector = Predictor(config)

[c:\Users\lec36\anaconda3\envs\extract_infomation_text\lib\site-packages\vietocr\tool\predictor.py](file:///C:/Users/lec36/anaconda3/envs/extract_infomation_text/lib/site-packages/vietocr/tool/predictor.py) in __init__(self, config)
     10         device = config['device']
     11 
---> 12         model, vocab = build_model(config)
     13         weights = '/tmp/weights.pth'
     14 

[c:\Users\lec36\anaconda3\envs\extract_infomation_text\lib\site-packages\vietocr\tool\translate.py](file:///C:/Users/lec36/anaconda3/envs/extract_infomation_text/lib/site-packages/vietocr/tool/translate.py) in build_model(config)
    128             config['seq_modeling'])
    129 
--> 130     model = model.to(device)
    131 
    132     return model, vocab

[c:\Users\lec36\anaconda3\envs\extract_infomation_text\lib\site-packages\torch\nn\modules\module.py](file:///C:/Users/lec36/anaconda3/envs/extract_infomation_text/lib/site-packages/torch/nn/modules/module.py) in to(self, *args, **kwargs)
   1159             return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
   1160 
-> 1161         return self._apply(convert)
   1162 
   1163     def register_full_backward_pre_hook(
...
--> 289             raise AssertionError("Torch not compiled with CUDA enabled")
    290         if _cudart is None:
    291             raise AssertionError(

AssertionError: Torch not compiled with CUDA enabled

### Versions

healp me, please!

**Comment by exitflynn** [comment]
can you elaborate on the description, like what you were originally trying to do?

**Comment by malfet** [comment]
Thank you very much for creating an issue, but from the description it does not look like anything is wrong with your installation, you've simply installed a CPU only version (which is a default one for Windows platform on PyPI)

For general questions on how to use PyTorch, please use https://discuss.pytorch.org/

If you believe that PyTorch does not work as expected, please do not hesitate to file a new issue, but please provide more details (that can easily be collected by running `python3 -mtorch.utils.collect_env` )
