### ISSUE TITLE
[PyTorch 2.1 regression] TorchScript behavior changed from 2.0.1 (and older) to 2.1

### ISSUE THREAD

**Issue by fxmarty** [pytorch/pytorch#110597]
### 🐛 Describe the bug

The ONNX export caught a behavior change on TorchScript API after PyTorch 2.1 was released. Before, a `Torch._C.Value.node.mustBeNone()` returned `False` for a model with `aten::new_zeros` ops while after PyTorch 2.1 it returns `True`, changing the execution path of the ONNX model export.

There is nothing in the [Pytorch 2.1 Release Notes](https://github.com/pytorch/pytorch/releases/tag/v2.1.0) that mentions a behavior change of this nature

Reproduction:
```
import torch.nn as nn
import torch
import onnxruntime as ort

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.emb = nn.Embedding(50, 64)
    
    def forward(self, x):
        inp = x.new_zeros(x.shape)
        
        return self.emb(inp)

model = MyModel()
inp = torch.Tensor([[2, 5, 6], [3, 2, 5]]).to(torch.int64)

torch.onnx.export(model, (inp,), "model.onnx", opset_version=9)
```

The repro uses `torch.onnx.export` because it calls `torch.jit.trace` and provides an easy entry point to print `new_zeros` arguments. 

The ONNX error is as shown:

```bash
/opt/pytorch/torch/onnx/utils.py:1703: UserWarning: The exported ONNX model failed ONNX shape inference. The model will not be executable by the ONNX Runtime. If this is unintended and you believe there is a bug, please report an issue at https://github.com/pytorch/pytorch/issues. Error reported by strict ONNX shape inference: [ShapeInferenceError] (op_type:Gather, node name: /emb/Gather): indices typestr: Tind, has unsupported type: tensor(float) (Triggered internally at /opt/pytorch/torch/csrc/jit/serialization/export.cpp:1445.)
  _C._check_onnx_proto(proto)
Traceback (most recent call last):
  File "repro_jit_type.py", line 18, in <module>
    torch.onnx.export(model, (inp,), "model.onnx", opset_version=9)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from model.onnx failed:This is an invalid model. Type Error: Type 'tensor(float)' of input parameter (/Constant_output_0) of operator (Gather) in node (/emb/Gather) is invalid.
```

The error above doesn't point to TorchScript, but shows the execution path has changed for ONNX exporter.
Looking into it further and printing the `new_zeros`'s `dtype` argument (from within the [ONNX exporter code](https://github.com/pytorch/pytorch/blob/144cda7f068854dd870c9567781aa2aca6d5e4cf/torch/onnx/symbolic_opset9.py#L388) which has an easy entry point to the `new_zeros` TorchScript node), we can see that on PyTorch 2.1, the `dtype` arg of `new_zeros` is captured as:

```python
> /opt/pytorch/torch/onnx/symbolic_opset9.py(3889)new_zeros()
-> self_dtype = symbolic_helper._try_get_scalar_type(self)
(Pdb) dtype
15 defined in (%15 : NoneType = prim::Constant(), scope: __main__.MyModel::
)
```

However, in PyTorch 2.0.1 and older, it was:

```python
> /opt/conda/envs/ptca/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py(3708)new_zeros()
-> self_dtype = symbolic_helper._try_get_scalar_type(self)
(Pdb) dtype
15 defined in (%15 : Long(device=cpu) = onnx::Constant[value={4}](), scope: __main__.MyModel::
)
```

### Versions

PyTorch 2.1

cc @ezyang @gchanan @zou3519 @kadeng @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by fxmarty** [comment]
[model.onnx.zip](https://github.com/pytorch/pytorch/files/12819009/model.onnx.zip)

Adding the failing model exported from `torch.onnx.export` on 2.1 for reference

**Comment by fxmarty** [comment]
Hi @justinchuby @BowenBao @thiagocrepaldi, this issue is related to the dtype `indices` is exported to.

Minimal reproduction:

```python
import torch.nn as nn
import torch
import onnxruntime as ort

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.emb = nn.Embedding(50, 64)
    
    def forward(self, x):
        inp = x.new_zeros(x.shape)
        
        return self.emb(inp)

model = MyModel()
inp = torch.Tensor([[2, 5, 6], [3, 2, 5]]).to(torch.int64)

torch.onnx.export(model, (inp,), "model.onnx", opset_version=9)

session = ort.InferenceSession("model.onnx", providers=["CPUExecutionProvider"])
```

Debugging, it appears that the issue is due to this where `dtype` is not None
https://github.com/pytorch/pytorch/blob/e9ebda29d87ce0916ab08c06ab26fd3766a870e5/torch/onnx/symbolic_opset9.py#L3707-L3708

and when calling `zeros` and in turn its decorator `symbolic_helper.parse_args`, we used to go into this controlflow for the argument `dtype`,

https://github.com/pytorch/pytorch/blob/e9ebda29d87ce0916ab08c06ab26fd3766a870e5/torch/onnx/symbolic_helper.py#L82-L83

while in 2.1.0 we go into this controlflow

https://github.com/pytorch/pytorch/blob/e9ebda29d87ce0916ab08c06ab26fd3766a870e5/torch/onnx/symbolic_helper.py#L78-L79

This in the `zeros` function, with 2.0.1 we rightfully call `scalar_type = _type_utils.JitScalarType(dtype)` while in 2.1.0 we call `scalar_type = _type_utils.JitScalarType.FLOAT`.

https://github.com/pytorch/pytorch/blob/e9ebda29d87ce0916ab08c06ab26fd3766a870e5/torch/onnx/symbolic_opset9.py#L3690-L3693

It is unclear to me why `mustBeNone` has changed between 2.0.1 and 2.1, do you have any idea? This node is `15 defined in (%15 : NoneType = prim::Constant(), scope: __main__.MyModel::)` with the above example.

Thank you!

**Comment by fxmarty** [comment]
Actually yes, the issue is in the captured `ScriptModule`. Now in 2.1.0 the `dtype` arg of `new_zeros` is captured as `%17 : NoneType = prim::Constant()`, while it used to be capted as `%17 : int = prim::Constant[value=4]() # <tmp 4>+34:11:0`

**Comment by fxmarty** [comment]
Thank you. I'll do the change for `new_zeros` then, though the change in jit.trace may impact (or may not) other op as well.

**Comment by thiagocrepaldi** [comment]
> Actually yes, the issue is in the captured `ScriptModule`. Now in 2.1.0 the `dtype` arg of `new_zeros` is captured as `%17 : NoneType = prim::Constant()`, while it used to be capted as `%17 : int = prim::Constant[value=4]() # <tmp 4>+34:11:0`
> 
> An easy solution is to replace this check
> 
> https://github.com/pytorch/pytorch/blob/e9ebda29d87ce0916ab08c06ab26fd3766a870e5/torch/onnx/symbolic_opset9.py#L3707-L3708
> 
> by
> 
> ```python
>     if dtype.node().mustBeNone() and self_dtype is not None:
>         dtype = self_dtype
> ```
> 
> Is that fine or is the change in `torch.jit.trace` a bug and the issue should be fixed upstream?

@ezyang do you know someone that could help us track a potential regression on TorchScript?

**Comment by thiagocrepaldi** [comment]
@fxmarty I have updated the issue description to capture the root cause you have identified in a previous [comment](https://github.com/pytorch/pytorch/issues/110597#issuecomment-1750488721)

Feel free to update it accordingly. The important is to show that the ONNX exporter detected the behavior change, not caused it so that TorchScript friends can help us here

**Comment by albanD** [comment]
cc @davidberard98 can you take a look at the priority of this please?

**Comment by malfet** [comment]
I wonder if difference is caused by dynamic shapes?

**Comment by ezyang** [comment]
Seems unlikely? This is all TS...

**Comment by sanchitintel** [comment]
The `dtype`, `layout` & `device` arguments of `new_zeros` are being traced as `NoneType`. I'll report back on Friday. Thanks!

**Comment by davidberard98** [comment]
was curious where this came from and ran a bisect. Bisect is still running but I'm pretty sure it's from this PR, which basically makes this exact change: https://github.com/pytorch/pytorch/pull/97564.

will take a look at the linked PRs in the next day or two.

@albanD not familiar with priority levels - perhaps you or someone else from core can judge based on the change in the referenced PR?

**Comment by albanD** [comment]
cc @bdhirsh is your PR expected to impact all forms of tracing this way?

**Comment by bdhirsh** [comment]
@albanD yep - the purpose of that PR was to avoid burning in the defaults of `*_like` factory functions during tracing. And this burning in previously happened at the python binding layer. So all traces that live below the python layer (make_fx, and also torchscript tracing and friends) will be affected by it.

In theory, the semantics of `aten.ones_like(x)` and `aten.ones_like(x, device='cpu')` are the same. But I should have marked that PR as potentially BC-breaking for backends / consumers of that IR 😕.

**Comment by thiagocrepaldi** [comment]
> @albanD yep - the purpose of that PR was to avoid burning in the defaults of `*_like` factory functions during tracing. And this burning in previously happened at the python binding layer. So all traces that live below the python layer (make_fx, and also torchscript tracing and friends) will be affected by it.
> 
> In theory, the semantics of `aten.ones_like(x)` and `aten.ones_like(x, device='cpu')` are the same. But I should have marked that PR as potentially BC-breaking for backends / consumers of that IR 😕.

Thank you. 
Are we considering a change to make this a BC again (maybe for 2.1.1) or the new breaking behavior will stand as is?

**Comment by fxmarty** [comment]
This should probably be re-opened

**Comment by thiagocrepaldi** [comment]
> TBH, the new behavior is better. Maybe we should just have a flag or something to get you the old behavior.

A flag could work.

**Comment by atalman** [comment]
cherry-picked and  validated on rc2 of 2.1.1
