### ISSUE TITLE
On the correctness of torch.signal.windows.cosine

### ISSUE THREAD

**Issue by tqbl** [pytorch/pytorch#110541]
As of writing, `torch.signal.windows.cosine` is implementing the following function:

$h[n] = \sin(\frac{\pi(n+0.5)}{M}),$

where $M$ is the length of the window. (The denominator is $M+1$ when `sym=False`, but my point will be the same.)

This implementation is identical to scipy's, but it deviates from the definition I'm familiar with, which is

$h[n] = \sin(\frac{\pi n}{M-1}).$

As far as I know, the cosine window is the square root of the Hann window. If we use the current implementation, this equality is not satisfied, while the latter definition does indeed satisfy it. For what it's worth, MATLAB also follows the latter definition. I could not find an explanation for scipy's deviation.

### Solution
I suppose there are two choices:
1. Continue following scipy, but make it clear in the documentation that it deviates from the correct definition.
2. Modify the code to implement the correct definition, and perhaps mention how it deviates from scipy in the docs.

cc @mruberry @rgommers

**Comment by vadimkantorov** [comment]
(might also be useful to have a kwarg for specifying non-default, but correct behavior)

**Comment by ezyang** [comment]
We classically follow numpy APIs as closely as possible. A doc update would be appreciated though, as well as a correct matlab definition.
