### ISSUE TITLE
[optim]: `NAdam`, `RAdam` and `_multi_tensor_adadelta` do not support complex types

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#110606]
### 🐛 Describe the bug

It is trivial to add support (by viewing params, grads and intermediates as real via `view_as_real`), but somehow, unlike other optim classes, they inconsistently do not support complex.

### Versions

main

### Tasks
- [ ] adadelta multitensor
- [ ] NAdam
- [ ] RAdam

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by janeyx99** [comment]
Will accept PRs to fix these + add appropriate testing.

**Comment by lezcano** [comment]
Related issue with plenty of PRs as an example for how to do it: https://github.com/pytorch/pytorch/issues/65711

**Comment by haixu-qin** [comment]
Hello. Could I work on this issue?

**Comment by jon-chuang** [comment]
@haixu-qin I would rather I be assigned as there are some subtleties now, regarding the dynamo tracing perf. (Currently undergoing review).

**Comment by haixu-qin** [comment]
@malfet No problem.

**Comment by jon-chuang** [comment]
Oops, we actually missed SGD here. Let me add that too.

**Comment by haixu-qin** [comment]
@malfet No problem.
