### ISSUE TITLE
`torch.nn.RReLU` not working as expected but `torch.rrelu` does

### ISSUE THREAD

**Issue by 27px** [pytorch/pytorch#110620]
### 🐛 Describe the bug

`torch.nn.RReLU` behaves like linear activation function (returns the same value (even for negatives)), however `torch.rrelu` works as expected and returns a random value between upper and lower limit

```python
import torch

x = torch.arange(-10, 10, step=0.5)

y_1 = torch.nn.RReLU(x)

y_2 = torch.rrelu(x)
```

#### Output

```python
y_1 = RReLU(
  lower=tensor([-10.0000,  -9.5000,  -9.0000,  -8.5000,  -8.0000,  -7.5000,  -7.0000,
           -6.5000,  -6.0000,  -5.5000,  -5.0000,  -4.5000,  -4.0000,  -3.5000,
           -3.0000,  -2.5000,  -2.0000,  -1.5000,  -1.0000,  -0.5000,   0.0000,
            0.5000,   1.0000,   1.5000,   2.0000,   2.5000,   3.0000,   3.5000,
            4.0000,   4.5000,   5.0000,   5.5000,   6.0000,   6.5000,   7.0000,
            7.5000,   8.0000,   8.5000,   9.0000,   9.5000]), upper=0.3333333333333333
)

y_2 = tensor([-2.2917, -2.1771, -2.0625, -1.9479, -1.8333, -1.7188, -1.6042, -1.4896,
        -1.3750, -1.2604, -1.1458, -1.0312, -0.9167, -0.8021, -0.6875, -0.5729,
        -0.4583, -0.3438, -0.2292, -0.1146,  0.0000,  0.5000,  1.0000,  1.5000,
         2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,  5.0000,  5.5000,
         6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,  9.0000,  9.5000])
```

### Versions

PyTorch version: 2.1.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2419
DeviceID=CPU0
Family=205
L2CacheSize=5120
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2419
Name=11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] torch==2.1.0
[pip3] torchvision==0.14.1
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi

**Comment by haixu-qin** [comment]
Could you try a class instance Not a class?

**Comment by 27px** [comment]
sorry, my bad, the tensor was going as the `lower` parameter of the class
