### ISSUE TITLE
Pytorch 2.1.0 CUDA 12.x docker image missing

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#110643]
### 🚀 The feature, motivation and pitch

Please add CUDA 12.x official images.

### Additional context

https://github.com/pytorch/pytorch/issues/91122#issuecomment-1749534410

**Comment by malfet** [comment]
Edited the title, @bhack just to confirm, you are asking for a docker images, as otherwise wheels and conda packages indeed has been published, aren't they?

**Comment by bhack** [comment]
Yes official Docker images:
https://hub.docker.com/r/pytorch/pytorch/tags

**Comment by atalman** [comment]
@bhack Good call, let me try to publish CUDA 12.1 versions

**Comment by atalman** [comment]
@bhack Cuda 12.1 images have been uploaded to: https://hub.docker.com/r/pytorch/pytorch/tags
Please confirm it works for you. And we can probably close this issue

**Comment by bhack** [comment]
@atalman As in `pytorch 2.1.0` it is mandoatory `c++17` it is a annoying to patch all third party `c++` `pytorch` extensions when building  in this dev container. 

Why we are not using a `g++` version (like 11)  that default `c++17`?  Or why we have not switched to `22.04 LTS` to default `g++ 11` and `c++17`?

**Comment by malfet** [comment]
Closing this one as docker image has been published. @bhack please do not hesitate to propose a patch (or file another issue) if you believe docker container does not function as expected (or want some improvements)
But let me propose a PR to move docker to 22.04, because why not..

**Comment by bhack** [comment]
What is required to move to 22.04 and kick-off the CI in a PR?
