### ISSUE TITLE
Input and target shapes do not match

### ISSUE THREAD

**Issue by sanayam** [pytorch/pytorch#11067]
While running the code I am getting this error. Can amyone tell what's error? And where I am going wrong? The error is : 
RuntimeError: input and target shapes do not match: input [1 x 3 x 96 x 144], target [1 x 1 x 96 x 144] at /opt/conda/conda-bld/pytorch_1532579805626/work/aten/src/THCUNN/generic/MSECriterion.cu:12

p.s. How should I make input and target shapes match? This happened when I resized the original image. It was running fine with the original image.

**Comment by SsnL** [comment]
MSE requires two input to have same shape, but yours don't.
