### ISSUE TITLE
build pytorch failed

### ISSUE THREAD

**Issue by weishu20** [pytorch/pytorch#11070]
```
[ 92%] Built target caffe2_gpu
Scanning dependencies of target stream_test
[ 92%] Building CXX object caffe2/CMakeFiles/stream_test.dir/__/aten/src/ATen/test/stream_test.cpp.o
[ 93%] Linking CXX executable ../bin/stream_test
/home/weishu/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::GlobalMPIComm()'
/home/weishu/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::MPIMutex()'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/stream_test.dir/build.make:108: recipe for target 'bin/stream_test' failed
make[2]: *** [bin/stream_test] Error 1
CMakeFiles/Makefile2:1407: recipe for target 'caffe2/CMakeFiles/stream_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/stream_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

I didn`t find same problem from issues,Can anybody help me?

**Comment by deepali-c** [comment]
Please check if PR link given at https://github.com/caffe2/caffe2/issues/2551#issuecomment-417124872 helps.

**Comment by weishu20** [comment]
@deepali-c Thank you for your help
before trying your solution,I tried to  add "-DUSE_MPI=OFF" to "cmake ..",and success!!

**Comment by emmra** [comment]
@weishu20
I   have met the same error and have added   "-DUSE_MPI=OFF" to "cmake .."

cmake -DCMAKE_PREFIX_PATH=~/anaconda3/envs/py27-pytorch -DCMAKE_INSTALL_PREFIX=~/anaconda3/envs/py27-pytorch -DUSE_MPI=OFF ..


hc1plus: warning: unrecognized command line option ‘-Wno-stringop-overflow’
[ 98%] Linking CXX executable ../bin/db_throughput
CMakeFiles/db_throughput.dir/db_throughput.cc.o: In function `_GLOBAL__sub_I_db_throughput.cc':
db_throughput.cc:(.text.startup+0xde): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
db_throughput.cc:(.text.startup+0x1a3): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
../lib/libcaffe2.so: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
../lib/libcaffe2.so: undefined reference to `google::SetUsageMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libcaffe2.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
/disk1/g201708021059/gg/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/db_throughput] Error 1
make[1]: *** [binaries/CMakeFiles/db_throughput.dir/all] Error 2
make: *** [all] Error 2

**Comment by ezyang** [comment]
@emmra Do you care about leveldb support? If not, you can turn it off with `-DUSE_LEVELDB=OFF`. Give that a try.

**Comment by skyuuka** [comment]
These changes fixed my issue  https://github.com/pytorch/pytorch/pull/11037/commits/10322d92c9ceea02d693696235e45e6adda4a999

**Comment by emmra** [comment]
@weishu20 @ ezyang c
Have you met this error？

[ 99%] Linking CXX executable ../bin/tutorial_blob
../lib/libcaffe2.so: undefined reference to `google::SetUsageMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/disk1/g201708021059/gg/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/disk1/g201708021059/gg/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/tutorial_blob] Error 1
make[1]: *** [binaries/CMakeFiles/tutorial_blob.dir/all] Error 2
make: *** [all] Error 2

**Comment by H-Huang** [comment]
Stale issue, please re-raise if this is still happening.
