### ISSUE TITLE
torch/cuda/_sanitizer.py uses buggy API in Python 3.11

### ISSUE THREAD

**Issue by vufg** [pytorch/pytorch#110769]
### 🐛 Describe the bug

In Python 3.11, `traceback.walk_stack(None)` will have inconsistent results with Python 3.10, as described in  https://github.com/python/cpython/issues/96092.

I found this API is also used in pytorch:  https://github.com/pytorch/pytorch/blob/main/torch/cuda/_sanitizer.py#L372

I fixed this issue in another project by replacing this API with `inspect.currentframe`. Bring this up to prevent potential bugs.

### Versions

https://github.com/pytorch/pytorch/commit/59592ce9f208fc80be89cef5fa5ad1719c61a619

cc @ptrblck

**Comment by mikaylagawarecki** [comment]
We would accept a PR that fixes this issue

**Comment by malfet** [comment]
Looks like CUDA sanitizer was added by https://github.com/pytorch/pytorch/pull/83984
