### ISSUE TITLE
Dynamo forward hooks registered before compile region (inlined) w/o tensor ops, don't respect is_compiling control flow

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#110765]
### 🐛 Describe the bug
```
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_forward_pre_hook(self.pre_forward, with_kwargs=True)

    def pre_forward(self, module, args, kwargs):
        if torch._utils.is_compiling():
            return args, kwargs

        print("path B")
        return args, kwargs

    def forward(self, x):
        return x

mod = MyModule()
m = torch.compile(mod, backend="eager")
m(torch.tensor([1])) # prints "path A"

```
If we force the `is_compiling` region to have something in it, then it works.

```
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_forward_pre_hook(self.pre_forward, with_kwargs=True)

    def pre_forward(self, module, args, kwargs):
        if torch._utils.is_compiling():
            global _dummy_compiler_variable
            _dummy_compiler_variable += 1     
            return args, kwargs

 
        logging.warning("I don't want this to be printed")
        return args, kwargs
```

This probably happens because the order is:

1) See hook, start inlining
2) Analysis on hook - no tensor compute or torch ops or anything we care about
3) Delegate to eager

### Versions

main

cc @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jon-chuang** [comment]
I was unable to reproduce this.

My script:
```python
_dummy_compiler_variable = torch.tensor([1])

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_forward_pre_hook(self.pre_forward, with_kwargs=True)

    def pre_forward(self, module, args, kwargs):
        if torch._utils.is_compiling():
            global _dummy_compiler_variable
            _dummy_compiler_variable += 1
            print("path A")   
            return args, kwargs

        print("path B")   
        return args, kwargs

    def forward(self, x):
        return x

mod = MyModule()
m = torch.compile(mod, backend="eager")
m(torch.tensor([1])) # prints "path A"
```


https://github.com/pytorch/pytorch/blob/12f97bb2e94d6748d3d39d8f8debefde5b6b8dce/torch/_dynamo/variables/torch.py#L244

Could you provide a repro?

**Comment by voznesenskym** [comment]
> I was unable to reproduce this.
> 
> My script:
> 
> ```python
> _dummy_compiler_variable = 1 # also works with _dummy_compiler_variable = torch.tensor([1])
> 
> class MyModule(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.register_forward_pre_hook(self.pre_forward, with_kwargs=True)
> 
>     def pre_forward(self, module, args, kwargs):
>         if torch._utils.is_compiling():
>             global _dummy_compiler_variable
>             _dummy_compiler_variable += 1
>             print("path A")   
>             return args, kwargs
> 
>         print("path B")   
>         return args, kwargs
> 
>     def forward(self, x):
>         return x
> 
> mod = MyModule()
> m = torch.compile(mod, backend="eager")
> m(torch.tensor([1])) # prints "path A"
> ```
> 
> https://github.com/pytorch/pytorch/blob/12f97bb2e94d6748d3d39d8f8debefde5b6b8dce/torch/_dynamo/variables/torch.py#L244
> 
> Could you provide a repro?

Lol sorry had more context in an fb specific chat. The dummy variables are an example of forcing it to work. 

```
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_forward_pre_hook(self.pre_forward, with_kwargs=True)

    def pre_forward(self, module, args, kwargs):
        if torch._utils.is_compiling():
            return args, kwargs

        print("path B")
        return args, kwargs

    def forward(self, x):
        return x

mod = MyModule()
m = torch.compile(mod, backend="eager")
m(torch.tensor([1])) # prints "path A"
```

**Comment by jon-chuang** [comment]
Ooh yep I reproduced this.

I was also able to reproduce with `_dummy_compiler_variable` not a Tensor as long as there wasn't a print statement under `if torch._utils.is_compiling()`
