### ISSUE TITLE
Make torch._check work in Dynamo

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#110719]
### 🐛 Describe the bug

as stated

### Versions

main

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jon-chuang** [comment]
Hmm, I think this works?

```python
def f(x):
    torch._check(x.shape[0] == 1, lambda: "Failed")
    return x + 1

x = torch.compile(f)(torch.zeros(2))
```
Do you mean with dynamic shapes?
