### ISSUE TITLE
broken links for dynamo troubleshooting

### ISSUE THREAD

**Issue by nairbv** [pytorch/pytorch#110712]
### 📚 The doc issue

these links are broken:

https://github.com/pytorch/torchdynamo/blob/main/documentation/TROUBLESHOOTING.md

Google may be crawling these links, searches keep bringing me to: https://pytorch.org/docs/stable/dynamo/troubleshooting.html

### Suggest a potential alternative/fix

link to correct guides or remove the broken links

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by dmage** [comment]
`dynamo/troubleshooting.html` was renamed into `compile/troubleshooting.rst` by https://github.com/pytorch/pytorch/commit/6110effa86e3b1990540e79ab78fc209528ecce3#diff-d47c26a87db9be94bbaf97152229cff803373539296f8496024b09084ff3b803, and then it was renamed into `torch.compiler_troubleshooting.rst` by https://github.com/pytorch/pytorch/commit/4d3ea5df6599215743d24aaad7dadfc4901d0172#diff-680ea0aaa46d51103fa471f6afc89c62993c4ac770e7514ea55588009d50648d, so the new link is https://pytorch.org/docs/stable/torch.compiler_troubleshooting.html?

The link at https://github.com/pytorch/torchdynamo/blob/main/README.md is outdated too, should it be updated to https://pytorch.org/docs/stable/torch.compiler.html?
