### ISSUE TITLE
Input and target does not match python error

### ISSUE THREAD

**Issue by sanayam** [pytorch/pytorch#11073]
I have attached the screenshot of the code and the error I am getting. Can someone tell me where I am going wrong?
![screenshot-2018-8-30 super-resolution](https://user-images.githubusercontent.com/42597743/44850127-e81c7700-ac79-11e8-8de8-2f0e1e73bec7.png)
![screenshot-2018-8-30 super-resolution 1](https://user-images.githubusercontent.com/42597743/44850129-e81c7700-ac79-11e8-8823-5f5a0add9fd7.png)
![screenshot-2018-8-30 super-resolution 2](https://user-images.githubusercontent.com/42597743/44850130-e81c7700-ac79-11e8-91ae-38c716bde02d.png)
![screenshot-2018-8-30 super-resolution 3](https://user-images.githubusercontent.com/42597743/44850131-e8b50d80-ac79-11e8-8956-fd4f4cea0ddb.png)
![screenshot-2018-8-30 super-resolution 4](https://user-images.githubusercontent.com/42597743/44850132-e8b50d80-ac79-11e8-9940-faa67ec9546a.png)
![screenshot-2018-8-30 super-resolution 5](https://user-images.githubusercontent.com/42597743/44850134-e8b50d80-ac79-11e8-8016-3a543648d307.png)

**Comment by fmassa** [comment]
You target has only one channel, while the output of your model has 3 channels.
Also, those questions should be sent to discuss.pytorch.org
