### ISSUE TITLE
AOTAutograd: set_ on input that ultimately no-ops fails in runtime_wrapper copy_

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#110842]
### 🐛 Describe the bug

This simplified repro is extracted from Voz's FSDP tracing branch:

```
import torch

@torch.compile(backend="aot_eager", fullgraph=True)
def f(p):
    p2 = p.detach()
    p.set_(torch.cat([p, p]))
    x = p * 2
    p.set_(p2)
    return x

f(torch.randn(8))
```

Fails with

```
  File "/data/users/ezyang/a/pytorch/torch/_functorch/aot_autograd.py", line 3936, in forward
    return compiled_fn(full_args)
  File "/data/users/ezyang/a/pytorch/torch/_functorch/aot_autograd.py", line 1513, in g
    return f(*args)
  File "/data/users/ezyang/a/pytorch/torch/_functorch/aot_autograd.py", line 2655, in runtime_wrapper
    original_inpt.copy_(updated_inpt)
RuntimeError: The size of tensor a (8) must match the size of tensor b (16) at non-singleton dimension 0
```

Doesn’t fail on Voz’s branch, because we manually forced AOTAutograd to assume there are no (metadata) mutations on any inputs: https://github.com/pytorch/pytorch/blob/419dcc95a29d8da2232432d5431cacc7024e852d/torch/_functorch/aot_autograd.py#L781 

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym 

### Versions

main

**Comment by ezyang** [comment]
The harder version of this is deleting the `p.set_(p2)` at the end, so that there is now an externally visible metadata mutation.

**Comment by bdhirsh** [comment]
cc @voznesenskym, I see that this repro now fails in dynamo, because we graph-break on the metadata mutation [here](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/tensor.py#L271):

```
  File "/data/users/hirsheybar/a/pytorch/torch/_dynamo/variables/base.py", line 322, in call_function
    unimplemented(f"call_function {self} {args} {kwargs}")
  File "/data/users/hirsheybar/a/pytorch/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function DelayGraphBreakVariable() [TensorVariable()] {}
```

What's the state of inplace-metadata ops (like set_()): do we have just enough working for now to get FSDP working, but metadata-mutating ops will still be graph-broken on?

**Comment by ezyang** [comment]
Graph breaks now
