### ISSUE TITLE
`add.Tensor` will produce `-inf` in output with certain inputs in `fp16`

### ISSUE THREAD

**Issue by lms-mt** [pytorch/pytorch#110805]
### 🐛 Describe the bug

This bug happens for certain inputs. I have a model(Stable diffusion) and use PyTorch to deploy it.
I set the random seed like this:

```
generator = torch.Generator(device).manual_seed(2034)
```

This generator will be used by the model. And then I generate image by iterating:
```
for i in range(N):
    image = model()
```

Each time when it hits `i=1`, which means the second round of image genearation, I got a black filled image, this is abnomal.

So I debug the data flow, I turns out that in second round, one `add.Tensor` op will produce `-inf` elements in output. This affects the final output.

Unfortunately I have no time to dig into the cuda kernel `gpu_kernel_impl` in `CUDALoops.cuh`. I serialized both the two operands of the `add.Tensor` op to help you guys to produce it.

####  Reproducing

Here are two attachments of serailzed two tensors:

https://drive.google.com/file/d/1Rub73LedaTIOKGpFTDm_i4EZUsy-P1K0/view?usp=sharing

https://drive.google.com/file/d/1QU3Tt6miAyeNia2wBosnHZmVgFaq9QCd/view?usp=sharing

Reproduce:

```
import torch

device = "cuda"

# operands shape: [torch.Size([1, 128, 1024, 1024]), torch.Size([1, 128, 1024, 1024])]

left = torch.load("./tensor_operands_0.pt")
right = torch.load("./tensor_operands_1.pt")

output = torch.add(left, right)

print(torch.isinf(output).sum())

```

outputs:

```
tensor(58, device='cuda:0')
```

### Versions

PyTorch version: 2.0.0a0+gitc263bd4
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100 80GB PCIe
GPU 4: NVIDIA A100 80GB PCIe
GPU 5: NVIDIA A100 80GB PCIe
GPU 6: NVIDIA A100 80GB PCIe

Nvidia driver version: 515.48.07
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Gold 6346 CPU @ 3.10GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         3422.811
CPU max MHz:                     3600.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6200.00
Virtualization:                  VT-x
L1d cache:                       1.5 MiB
L1i cache:                       1 MiB
L2 cache:                        40 MiB
L3 cache:                        72 MiB
NUMA node0 CPU(s):               0-15,32-47
NUMA node1 CPU(s):               16-31,48-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.3
[pip3] torch==2.0.0a0+gitc263bd4
[conda] Could not collect

**Comment by mikaylagawarecki** [comment]
More minimal example from inspecting the inputs is

```
torch.tensor([-51296], dtype=torch.float16) + torch.tensor([-15040], dtype=torch.float16)
# tensor([-inf], dtype=torch.float16)
```

**Comment by lms-mt** [comment]
> More minimal example from inspecting the inputs is
> 
> ```
> torch.tensor([-51296], dtype=torch.float16) + torch.tensor([-15040], dtype=torch.float16)
> # tensor([-inf], dtype=torch.float16)
> ```
> 
> Seems like this is expected behavior

So there is expected overflow in fp16 addition, I should figure out why model has this input data in iteration 2.
