### ISSUE TITLE
torch.square outputs incorrect result on an uint8 tensor

### ISSUE THREAD

**Issue by drewshark** [pytorch/pytorch#110854]
### 🐛 Describe the bug

torch.square outputs incorrect result on an uint8 tensor

```
import torch
import numpy as np
np.random.seed(2023)
x = torch.tensor(np.random.randint(0, 100, ()), dtype=torch.uint8)
print(x)  # tensor(87, dtype=torch.uint8)
out = torch.square(x)
print(out)  # tensor(145, dtype=torch.uint8)
```
Expected result should be 7569 I think.

### Versions

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] torch==2.1.0
[pip3] triton==2.1.0
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by vadimkantorov** [comment]
It's probably because it does the computation in the original dtype and stores the output in the original dtype too (7569 does not fit in uint8)...

**Comment by lezcano** [comment]
This is expected as uint8 is not large enough to contain the result. What you get is exactly 87^2 mod 256 = 145
