### ISSUE TITLE
M2 Failing to build example-app in c++

### ISSUE THREAD

**Issue by sjoptra** [pytorch/pytorch#110810]
### 🐛 Describe the bug

Following the exact steps in https://pytorch.org/cppdocs/installing.html, I created the following file structure as indicated 
example-app/
  CMakeLists.txt
  example-app.cpp
  
  when I run 
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/libtorch ..
cmake --build . --config Release

I get the following linker error 

[ 50%] Building CXX object CMakeFiles/example-app.dir/example-app.cpp.o
[100%] Linking CXX executable example-app
ld: warning: directory not found for option '-L/lib/intel64'
ld: warning: directory not found for option '-L/lib/intel64_win'
ld: warning: directory not found for option '-L/lib/win-x64'
ld: unknown option: --no-as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [example-app] Error 1
make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
make: *** [all] Error 2

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.28.1.1)
CMake version: version 3.27.3
Libc version: N/A

Python version: 3.9.6 (default, Aug 12 2023, 13:13:19)  [Clang 15.0.0 (clang-1500.0.37.1) ] (64-bit runtime)
Python platform: macOS-14.1-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==1.19.0

cc @seemethere @malfet @osalpekar @atalman @jbschlosser @albanD

**Comment by malfet** [comment]
@sjoptra can you please specified what version of PyTorch you've tried to use (please note, that libtorch is yet not available for Apple Silicon so one has to use PyTorch wheels)

**Comment by sjoptra** [comment]
I downloaded the libtorch that is here:

wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
unzip libtorch-shared-with-deps-latest.zip

Which to my understanding is what the cmake uses to run example-app
How can I check which version is it?

**Comment by malfet** [comment]
@sjoptra libtorch binary you've downloaded are for x86 MacOS, so it would not work on M1.
But if you have a PyTorch installed on your machine using `pip instal torch`, then you should be able to build the project by running:
```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=$(python -c 'import torch;print(torch.utils.cmake_prefix_path)') ..
cmake --build . --config Release
```

**Comment by sjoptra** [comment]
@malfet thanks, I go over these exact steps and I still get the error below. Any idea what could be going wrong?

[ 50%] Linking CXX executable example-app
ld: warning: directory not found for option '-L/lib/intel64'
ld: warning: directory not found for option '-L/lib/intel64_win'
ld: warning: directory not found for option '-L/lib/win-x64'
ld: unknown option: --no-as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [example-app] Error 1
make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
make: *** [all] Error 2

And for more context: when I do 
echo $DCMAKE_PREFIX_PATH 

I get
/opt/homebrew/lib/python3.11/site-packages/torch/share/cmake

**Comment by sjoptra** [comment]
@malfet @mikaylagawarecki @svenstaro 

It was most likely some path issue because I managed to run the simple cpp regression example in https://github.com/pytorch/examples/tree/main/cpp/regression)

However, when I use C++ 20 instead of 14 I get many errors
I just changed set(CMAKE_CXX_STANDARD 14) to set(CMAKE_CXX_STANDARD 20) in CMakeLists.txt

I created this issue
https://github.com/pytorch/examples/issues/1195 

Any idea?

@seemethere @malfet  @osalpekar @atalman @jbschlosser @albanD

**Comment by elSomewhere** [comment]
It could be related to this clang bug, as moving away from c++ 20 also removes the bug for me:

https://github.com/llvm/llvm-project/issues/60749

> It was most likely some path issue because I managed to run the simple cpp regression example in https://github.com/pytorch/examples/tree/main/cpp/regression)
> 
> However, when I use C++ 20 instead of 14 I get many errors I just changed set(CMAKE_CXX_STANDARD 14) to set(CMAKE_CXX_STANDARD 20) in CMakeLists.txt
> 
> for example: error: arithmetic on a pointer to an incomplete type 'c10::IValue' {return static_cast<size_type>(__end_cap() - this->__begin_);}
> 
> I created this issue for the error details: [pytorch/examples#1195](https://github.com/pytorch/examples/issues/1195)
> 
> Any idea?
> 
> @seemethere @malfet @osalpekar @atalman @jbschlosser @albanD

https://github.com/llvm/llvm-project/issues/60749

**Comment by lancerts** [comment]
I encountered a similar issue to using C++ APIs via Libtorch on **ARM** Mac. 
1 One [solution](https://stackoverflow.com/questions/65593177/how-to-build-libtorch-on-mac-arm) is to try to build libtorch from source, relevant code below followed by manual copying of files mentioned in the post.
`
% git clone -b master --recurse-submodule https://github.com/pytorch/pytorch.git
% mkdir pytorch-build
% cd pytorch-build 
% cmake -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON_EXECUTABLE:PATH=`which python3` -DCMAKE_INSTALL_PREFIX:PATH=../pytorch-install ../pytorch

% cmake --build . --target install
`

2 The other potential [solution](https://github.com/pytorch/pytorch/issues/63558). 
Solution 1 works for me after a few trials to run examples on Mac ARM.

**Comment by malfet** [comment]
@lancerts have you tried M1 libtroch binaries? (published on https://pytorch.org/get-started/locally/ )

**Comment by malfet** [comment]
With 2.2 release available, closing this issue as M1 libtorch binaries are available for both nightlies and release.
If it still does not work, please do not hesitate to open a new issue
