### ISSUE TITLE
`pip install deepspeed` fails if number of GPUs greater than a certain small number?

### ISSUE THREAD

**Issue by davidleejy** [pytorch/pytorch#110971]
### 🐛 Describe the bug

These attempts at installing fail 🥲:

Attempt 1:
```bash
pip install deepspeed --no-cache-dir
```

Attempt 2:
```bash
export CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6,7'
pip install deepspeed --no-cache-dir
```

These attempts succeed 🎉:

Attempt 3:
```bash
export CUDA_VISIBLE_DEVICES='0,1,2,3'
pip install deepspeed --no-cache-dir
```

Attempt 4:
```bash
export CUDA_VISIBLE_DEVICES=0
pip install deepspeed --no-cache-dir
```

When installation fails 🥲, the following is printed in the terminal:

```bash
Collecting deepspeed
  Downloading deepspeed-0.11.1.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 12.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      [2023-10-10 18:49:53,030] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      [2023-10-10 18:49:55,635] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      Traceback (most recent call last):
        File "/home/davidlee/anaconda3/envs/lumpyllama/lib/python3.10/site-packages/torch/cuda/__init__.py", line 260, in _lazy_init
          queued_call()
        File "/home/davidlee/anaconda3/envs/lumpyllama/lib/python3.10/site-packages/torch/cuda/__init__.py", line 145, in _check_capability
          capability = get_device_capability(d)
        File "/home/davidlee/anaconda3/envs/lumpyllama/lib/python3.10/site-packages/torch/cuda/__init__.py", line 381, in get_device_capability
          prop = get_device_properties(device)
        File "/home/davidlee/anaconda3/envs/lumpyllama/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in get_device_properties
          return _get_device_properties(device)  # type: ignore[name-defined]
      RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-29c3v_m5/deepspeed_7b78606fcc504b8795ce3e3f5bbf6990/setup.py", line 173, in <module>
          op_compatible = builder.is_compatible()
        File "/tmp/pip-install-29c3v_m5/deepspeed_7b78606fcc504b8795ce3e3f5bbf6990/op_builder/spatial_inference.py", line 31, in is_compatible
          cuda_capability = torch.cuda.get_device_properties(0).major
        File "/home/davidlee/anaconda3/envs/lumpyllama/lib/python3.10/site-packages/torch/cuda/__init__.py", line 395, in get_device_properties
          _lazy_init()  # will define _get_device_properties
        File "/home/davidlee/anaconda3/envs/lumpyllama/lib/python3.10/site-packages/torch/cuda/__init__.py", line 264, in _lazy_init
          raise DeferredCudaCallError(msg) from e
      torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch.
      
      CUDA call was originally invoked at:
      
      ['  File "<string>", line 2, in <module>\n', '  File "<pip-setuptools-caller>", line 34, in <module>\n', '  File "/tmp/pip-install-29c3v_m5/deepspeed_7b78606fcc504b8795ce3e3f5bbf6990/setup.py", line 31, in <module>\n    import torch\n', '  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n', '  File "/home/davidlee/anaconda3/envs/lumpyllama/lib/python3.10/site-packages/torch/__init__.py", line 1146, in <module>\n    _C._initExtension(manager_path())\n', '  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n', '  File "/home/davidlee/anaconda3/envs/lumpyllama/lib/python3.10/site-packages/torch/cuda/__init__.py", line 197, in <module>\n    _lazy_call(_check_capability)\n', '  File "/home/davidlee/anaconda3/envs/lumpyllama/lib/python3.10/site-packages/torch/cuda/__init__.py", line 195, in _lazy_call\n    _queued_calls.append((callable, traceback.format_stack()))\n']
      DS_BUILD_OPS=0
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  async_io: please install the libaio-dev package with apt
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
       [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
       [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.27.6
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-121-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 510.73.08
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-255
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7742 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         3391.453
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4491.60
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-15,128-143
NUMA node1 CPU(s):               16-31,144-159
NUMA node2 CPU(s):               32-47,160-175
NUMA node3 CPU(s):               48-63,176-191
NUMA node4 CPU(s):               64-79,192-207
NUMA node5 CPU(s):               80-95,208-223
NUMA node6 CPU(s):               96-111,224-239
NUMA node7 CPU(s):               112-127,240-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
I can not reproduce it on a very similar AWS system. 
Can you please share the output of `nvidia-smi` ?
And please try running something like: `python -c "import torch;print(torch._C._cuda_getDeviceCount())"`
(I suspect nvidia-smi would show HW errors with some of the GPUs you have on the system

**Comment by davidleejy** [comment]
```bash
Wed Oct 11 05:22:28 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.08    Driver Version: 510.73.08    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:07:00.0 Off |                    0 |
| N/A   42C    P0   230W / 400W |  30207MiB / 40960MiB |     94%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  Off  | 00000000:0F:00.0 Off |                    0 |
| N/A   43C    P0   172W / 400W |  25832MiB / 40960MiB |     83%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  Off  | 00000000:47:00.0 Off |                    0 |
| N/A   62C    P0   382W / 400W |  30377MiB / 40960MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  Off  | 00000000:4E:00.0 Off |                    0 |
| N/A   25C    P0    54W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM...  Off  | 00000000:87:00.0 Off |                    0 |
| N/A   36C    P0    61W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM...  Off  | 00000000:90:00.0 Off |                    0 |
| N/A   56C    P0   216W / 400W |  38021MiB / 40960MiB |     77%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM...  Off  | 00000000:B7:00.0 Off |                    0 |
| N/A   75C    P0   391W / 400W |  31893MiB / 40960MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  Off  | 00000000:BD:00.0 Off |                    0 |
| N/A   62C    P0   436W / 400W |  29960MiB / 40960MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by davidleejy** [comment]
```bash
$ python -c "import torch;print(torch._C._cuda_getDeviceCount())"
6
```

What.. wait.. this could be the bug... shouldn't there be 8 since this machine has 8 GPUS installed..🥹

**Comment by skullcrossbones** [comment]
> ```bash
> 
> Wed Oct 11 05:22:28 2023       
> 
> +-----------------------------------------------------------------------------+
> 
> | NVIDIA-SMI 510.73.08    Driver Version: 510.73.08    CUDA Version: 11.6     |
> 
> |-------------------------------+----------------------+----------------------+
> 
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> 
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> 
> |                               |                      |               MIG M. |
> 
> |===============================+======================+======================|
> 
> |   0  NVIDIA A100-SXM...  Off  | 00000000:07:00.0 Off |                    0 |
> 
> | N/A   42C    P0   230W / 400W |  30207MiB / 40960MiB |     94%      Default |
> 
> |                               |                      |             Disabled |
> 
> +-------------------------------+----------------------+----------------------+
> 
> |   1  NVIDIA A100-SXM...  Off  | 00000000:0F:00.0 Off |                    0 |
> 
> | N/A   43C    P0   172W / 400W |  25832MiB / 40960MiB |     83%      Default |
> 
> |                               |                      |             Disabled |
> 
> +-------------------------------+----------------------+----------------------+
> 
> |   2  NVIDIA A100-SXM...  Off  | 00000000:47:00.0 Off |                    0 |
> 
> | N/A   62C    P0   382W / 400W |  30377MiB / 40960MiB |     99%      Default |
> 
> |                               |                      |             Disabled |
> 
> +-------------------------------+----------------------+----------------------+
> 
> |   3  NVIDIA A100-SXM...  Off  | 00000000:4E:00.0 Off |                    0 |
> 
> | N/A   25C    P0    54W / 400W |      0MiB / 40960MiB |      0%      Default |
> 
> |                               |                      |             Disabled |
> 
> +-------------------------------+----------------------+----------------------+
> 
> |   4  NVIDIA A100-SXM...  Off  | 00000000:87:00.0 Off |                    0 |
> 
> | N/A   36C    P0    61W / 400W |      0MiB / 40960MiB |      0%      Default |
> 
> |                               |                      |             Disabled |
> 
> +-------------------------------+----------------------+----------------------+
> 
> |   5  NVIDIA A100-SXM...  Off  | 00000000:90:00.0 Off |                    0 |
> 
> | N/A   56C    P0   216W / 400W |  38021MiB / 40960MiB |     77%      Default |
> 
> |                               |                      |             Disabled |
> 
> +-------------------------------+----------------------+----------------------+
> 
> |   6  NVIDIA A100-SXM...  Off  | 00000000:B7:00.0 Off |                    0 |
> 
> | N/A   75C    P0   391W / 400W |  31893MiB / 40960MiB |    100%      Default |
> 
> |                               |                      |             Disabled |
> 
> +-------------------------------+----------------------+----------------------+
> 
> |   7  NVIDIA A100-SXM...  Off  | 00000000:BD:00.0 Off |                    0 |
> 
> | N/A   62C    P0   436W / 400W |  29960MiB / 40960MiB |    100%      Default |
> 
> |                               |                      |             Disabled |
> 
> +-------------------------------+----------------------+----------------------+
> 
>                                                                                
> 
> +-----------------------------------------------------------------------------+
> 
> | Processes:                                                                  |
> 
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> 
> |        ID   ID                                                   Usage      |
> 
> |=============================================================================|
> 
> +-----------------------------------------------------------------------------+
> 
> ```

Could you please provide the vbios? Thank you.
