### ISSUE TITLE
DISABLED test_jvp_linalg_det_singular_cpu_float32 (__main__.TestOperatorsCPU)

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#110980]
Platforms: macos

This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/functorch%2Ftest_ops.py%3A%3ATestOperatorsCPU%3A%3Atest_jvp_linalg_det_singular_cpu_float32)).

cc @albanD @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

**Comment by huydhn** [comment]
This is not yet fixed, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/53444687120b47be9af2fa0e758d3319d8be3d2c

**Comment by malfet** [comment]
@huydhn I don't think bot listens to reason, but it responds well to commits ;)

**Comment by huydhn** [comment]
I just realize that there is no rerun disabled tests job for MacOS x86 on periodic.  This is the reason why the bot wrongly considered that this was fixed.  It reruns this test only on MacOS M1, which doesn't fail.  I'll push a fix for this.

**Comment by Flamefire** [comment]
I see this test failing consistently on Linux x86 (AMD EPYC 7352 24-Core Processor and Intel(R) Xeon(R) Platinum 8470)

The results are consistently the same with the error:
```
Mismatched elements: 1 / 4 (25.0%)
Greatest absolute difference: 0.44168850779533386 at index (0, 1) (up to 1e-05 allowed)
Greatest relative difference: inf at index (0, 1) (up to 1.3e-06 allowed)
```

Printing the 4 tensors I get:
```
noncontig_primal_outs tensor([[ 1.1827e-08, -4.5393e-08],
        [ 1.3780e-09,  4.6731e-08]])
expected_primal_outs tensor([[1.5973e-08, 0.0000e+00],
        [1.9493e-09, 4.2533e-08]])
noncontig_tangent_outs tensor([[ 0.1064, -0.4417],
        [-0.3706,  0.1153]])
expected_tangent_outs tensor([[ 0.1064, -0.0000],
        [-0.3706,  0.1153]])
```

So the error doesn't seem to be isolated to MacOS
