### ISSUE TITLE
Documentation Clarification on torch.compile Example

### ISSUE THREAD

**Issue by yewentao256** [pytorch/pytorch#110917]
### 📚 The doc issue

I came across an example in the [torch.compiler documentation](https://pytorch.org/docs/main/torch.compiler_get_started.html)

```py
import torch
def fn(x, y):
    a = torch.cos(x).cuda()
    b = torch.sin(y).cuda()
    return a + b
new_fn = torch.compile(fn, backend="inductor")
input_tensor = torch.randn(10000).to(device="cuda:0")
a = new_fn(input_tensor, input_tensor)
```

The documentation mentions that *we can turn 2 reads and 2 writes into 1 read and 1 write*. However, given there are three distinct operations, I'm inclined to think there should be 4 reads (x, y, a, b) and 3 writes (a, b, a+b). Can you confirm this?

Additionally, there's a note which says:

*To run this script, you need to have at least one GPU on your machine. If you do not have a GPU, you can remove the cuda() code in the snippet below and it will run on CPU.*

However, the crucial step to ensure GPU usage is the `.to(device="cuda:0")`. Merely removing .cuda() won't make the tensor reside on the CPU. 

### Suggest a potential alternative/fix

Hence, I'd suggest updating the note to:

```note
To run this script, you need to have at least one GPU on your machine. If you do not have a GPU, you can remove the `.to(device="cuda:0")` code in the snippet below and it will run on CPU.
```

Lastly, since .cuda() in the fn function seems redundant if we're already specifying the device using .to(device="cuda:0"), consider updating the function as:

```py
import torch
def fn(x, y):
    a = torch.cos(x)
    b = torch.sin(y)
    return a + b
```

Thank you for considering these suggestions. Looking forward to your feedback!

cc @svekars @carljparker

**Comment by msaroufim** [comment]
Oh sure yeah happy to merge improvements here, feel free to add me to your PR as a reviewer

**Comment by yewentao256** [comment]
@msaroufim Done~
