### ISSUE TITLE
numpy.__config__.show() for torch

### ISSUE THREAD

**Issue by szagoruyko** [pytorch/pytorch#111]
Would be useful to have stats like BLAS, CUDA archs, compile options etc at runtime, similar to `numpy.__config__.show()`

**Comment by zou3519** [comment]
Would also be nice to build this into collect_env.py (could be a followup task to this)

**Comment by vishwakftw** [comment]
This has been included in https://github.com/pytorch/pytorch/commit/29ea08616bd10f50b31afcff077f3e8feb3d9792 by @ezyang.
