### ISSUE TITLE
[AOTInductor] 14K models: expected inputs vector size to be 1, but got 3

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#111068]
395 errors like: RuntimeError: expected inputs vector size to be 1, but got 3 (example ./generated/test_LoSealL_VideoSuperResolution.py:make_dense # pytest ./generated/test_LoSealL_VideoSuperResolution.py -k test_042)

Repro:
```
git clone https://github.com/jansel/pytorch-jit-paritybench.git
# set PYTHONPATH like the following example
export PYTHONPATH=/home/binbao/local/pytorch-jit-paritybench/paritybench:$PYTHONPATH
python main.py --compile_mode=aot_inductor -e ./generated/test_LoSealL_VideoSuperResolution.py
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by chenyang78** [comment]
I couldn't reproduce the exact error. Closing it.
