### ISSUE TITLE
[Typo] about `scaled_dot_product_attention` doc

### ISSUE THREAD

**Issue by pixeli99** [pytorch/pytorch#111023]
https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html

![image](https://github.com/pytorch/pytorch/assets/46072190/bd2f183b-4cb4-422e-9dd3-e18c981ca7bc)

There seems to be a typo here, it should be 'attn_bias.masked_fill_(attn_mask.logical_not(), float("-inf"))' ?

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by cpuhrsch** [comment]
If you take a look at the most recent documentation you'll see it's already been fixed: https://pytorch.org/docs/main/generated/torch.nn.functional.scaled_dot_product_attention.html#torch.nn.functional.scaled_dot_product_attention

```
[...]
    if attn_mask is not None:
        if attn_mask.dtype == torch.bool:
            *attn_bias.masked_fill_(attn_mask.logical_not(), float("-inf"))*
        else:
            attn_bias += attn_mask
    attn_weight = query @ key.transpose(-2, -1) * scale_factor
    attn_weight += attn_bias
[...]
```

Please reopen this issue if this does not address your concern.
