### ISSUE TITLE
TorchDispatchMode not catch mode in __torch_dispatch__

### ISSUE THREAD

**Issue by JsBlueCat** [pytorch/pytorch#111014]
### 🐛 Describe the bug

```python
import torch
from torch.utils._python_dispatch import TorchDispatchMode,_get_current_dispatch_mode

class EnableParitalMode(TorchDispatchMode):
    def __torch_dispatch__(self, func, types, args=(), kwargs=None):
        mode = _get_current_dispatch_mode()
        print("in dispatch" ,mode) # None
        func(*args, **kwargs)
    

b = torch.Tensor(1,4,8)
with EnableParitalMode():
    mode = _get_current_dispatch_mode()
    print("in outer ", mode) # EnableParitalMode
    a = torch.ones_like(b)

```

### Versions

HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    4
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         2999.999
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        108 MiB
NUMA node0 CPU(s):               0-15,64-79
NUMA node1 CPU(s):               16-31,80-95
NUMA node2 CPU(s):               32-47,96-111
NUMA node3 CPU(s):               48-63,112-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] byted-torch==2.1.0.post1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230815+cu118
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] Could not collect

cc @Chillee @ezyang @zou3519 @albanD @samdow

**Comment by albanD** [comment]
Hi,

This is expected behavior, we pop the current mode while handling it. This is to avoid doing infinite recursion when you do `func(*args, **kwargs)`.

If you need to re-enable it, you can do `with self:` within your `__torch_dispatch__` handler.

Closing as expected behavior but feel free to ask question if there is anything that is unclear / not working as described above!

**Comment by JsBlueCat** [comment]
> Hi,
> 
> This is expected behavior, we pop the current mode while handling it. This is to avoid doing infinite recursion when you do `func(*args, **kwargs)`.
> 
> If you need to re-enable it, you can do `with self:` within your `__torch_dispatch__` handler.
> 
> Closing as expected behavior but feel free to ask question if there is anything that is unclear / not working as described above!
```
import torch
from torch.utils._python_dispatch import TorchDispatchMode,_get_current_dispatch_mode

class EnableParitalMode(TorchDispatchMode):
    def __torch_dispatch__(self, func, types, args=(), kwargs=None):
        with self:
            mode = _get_current_dispatch_mode()
            print("in dispatch" ,mode) # None
            func(*args, **kwargs)
    

b = torch.Tensor(1,4,8)
with EnableParitalMode():
    mode = _get_current_dispatch_mode()
    print("in outer ", mode) # EnableParitalMode
    a = torch.ones_like(b)
```
when i use with self, it will cause recursive max depth oom 

```
  File "/usr/local/lib/python3.9/dist-packages/torch/_ops.py", line 435, in __call__
    return self._op(*args, **kwargs or {})
  File "/root/test.py", line 11, in __torch_dispatch__
    func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/_ops.py", line 435, in __call__
    return self._op(*args, **kwargs or {})
  File "/root/test.py", line 11, in __torch_dispatch__
    func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/_ops.py", line 435, in __call__
    return self._op(*args, **kwargs or {})
  File "/root/test.py", line 11, in __torch_dispatch__
    func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/_ops.py", line 435, in __call__
    return self._op(*args, **kwargs or {})
  File "/root/test.py", line 11, in __torch_dispatch__
    func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/_ops.py", line 435, in __call__
    return self._op(*args, **kwargs or {})
  File "/root/test.py", line 11, in __torch_dispatch__
    func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/_ops.py", line 435, in __call__
    return self._op(*args, **kwargs or {})
  File "/root/test.py", line 8, in __torch_dispatch__
    with self:
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/_python_dispatch.py", line 55, in __enter__
    _push_mode(self, self.__dict__.get("_dispatch_key", None))
RecursionError: maximum recursion depth exceeded while calling a Python objec
```

**Comment by albanD** [comment]
Yes as mentioned above, this is why it is disabled by default. You should never call the func with self re-enabled.
