### ISSUE TITLE
Option to disable fastpath in MHA

### ISSUE THREAD

**Issue by mrpep** [pytorch/pytorch#111070]
### 🚀 The feature, motivation and pitch

I have trained a transformer model but I'm not able to run inference with it because of fastpath errors commented here: #88806 and #97128. I would like to run the inference with the normal path but I can't find any options to disable fastpath.

### Alternatives

One option is to add a flag like
```python
torch._fastpath.config.enable=False
```
or use environment variables.

### Additional context

I could disable it by setting the following line with a non-empty string: https://github.com/pytorch/pytorch/blob/d3205f83770f83cfa315a38f4448c64670758b03/torch/nn/modules/activation.py#L1111

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Addressed by https://github.com/pytorch/pytorch/pull/112212, feel free to reopen if this does not satisfy your use-case
