### ISSUE TITLE
[Dynamo] Error in speculate_subgraph doesn't report inner user stack trace

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#111020]
### 🐛 Describe the bug

self explanatory

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @ydwu4 @wconstab @Xia-Weiwen

**Comment by zou3519** [comment]
Do you have an example?

**Comment by ezyang** [comment]
it's just this code

```
    except Unsupported as ex:
        f_name = f"{type(f).__name__}"
        if isinstance(f, UserFunctionVariable):
            f_name = f.get_name()
        msg = (
            f"speculate_subgraph: while introspecting {description}, we were unable "
            f"to trace function `{f_name}` into a single graph. This means "
            f"that Dynamo was unable to prove safety for this API and will "
            f"fall back to eager-mode PyTorch, which could lead to a slowdown."
        )
        log.warning(msg)
        log.exception(ex)
        tx.output.graph = graph_checkpoint
        tx.restore_graphstate(checkpoint)
        raise Unsupported(
            f"{msg} Scroll up for the stack trace "
            f"of the initial exception. The reason was: {ex.msg}"
        ) from ex
```

doesn't preserve the user stack trace from ex

**Comment by zou3519** [comment]
It should, if you scroll up far enough. For example, the following:
```
import torch
import torch._higher_order_ops.wrap

glob = []


def f(x):
    glob.append(x)
    return x.clone()

@torch.compile(backend='eager', fullgraph=True)
def g(x):
    return torch.ops.higher_order.wrap(f, x)

x = torch.randn(3)
g(x)
```
gives me the the following if I scroll far enough up:
<img width="786" alt="image" src="https://github.com/pytorch/pytorch/assets/5652049/6c7481f1-f7bc-41e8-a479-c21c1eec21b8">

**Comment by zou3519** [comment]
Okay, yeah, I understand now. The current error message is the following
<img width="794" alt="image" src="https://github.com/pytorch/pytorch/assets/5652049/c22735d3-4b45-412c-9e29-ec5688fe5427">

but it should really point to the `glob.append(...)` line (or be something like a nested stack trace)
