### ISSUE TITLE
Memory Leak in autograd

### ISSUE THREAD

**Issue by bunelr** [pytorch/pytorch#1111]
Here is an example as small as I could make it that triggers what I assume is a memory leak.

```python
import torch
import gc
import resource
from torch import nn
from torch.autograd import Variable

# inp = Variable(torch.Tensor(1,3), volatile=True) # This one does not have a problem
inp = Variable(torch.Tensor(1,3)) # This one does
linear_layer = nn.Linear(3, 6)

iter_idx = 0
while True:
    out = linear_layer(inp).view(-1)
    a = Variable(torch.zeros(6))

    for elt_idx, out in enumerate(out):
        a[elt_idx] = out + a[elt_idx]

    if iter_idx % 10000 == 0:
        gc.collect()
        max_mem_used = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        print("{:.2f} MB".format(max_mem_used / 1024))


    iter_idx += 1

```
The "network" used here is fairly small, a linear layer with 18 parameters. The backward pass is not even called.

If the input to the network is given as `volatile`, memory usage is stable (81.23 MB) on my machine.
If not, it quickly blows out of proportion, (after 1 min, it already uses 4GB on my machine)

This is probably not very important, I figured out how to work around this in my implementation but I figured I'd still report it.

My setup is the following (everything was run from a virtualenv, pytorch was installed today just for this):

`python --version` is `Python 3.6.0`
`pip freeze` returns
```
appdirs==1.4.3
numpy==1.12.1
olefile==0.44
packaging==16.8
Pillow==4.0.0
pyparsing==2.2.0
PyYAML==3.12
six==1.10.0
torch==0.1.10.post2
torchvision==0.1.7
```

My OS is a relatively up to date ArchLinux install. 
Same bug (not the minimal example but the original version) was also observed on my workstation which is an Ubuntu 16.04 install.

Let me know if I can provide more help to debug this.

**Edit:** I tried the same thing with a python 2.7 install and the results are exactly the same.

**Comment by ajdroid** [comment]
@bunelr What was the workaround?

**Comment by apaszke** [comment]
The ongoing refactor might have already solved that. It's in `autograd` branch and it should be functional, but there might still be other bugs. I'll later check if it's fixed there.

**Comment by bunelr** [comment]
@ajdroid 
The way I avoided the bug was to avoid the line `a[elt_idx] = out + a[elt_idx]`

In my case, the Tensor I had was sparsely populated so I could afford to just collect everything into different variables and only sum all of them at the end. That made the problem go away for me.

**Comment by bunelr** [comment]
@apaszke 
I installed from source the `autograd` branch and I can confirm that the bug is fixed on it.
Initial memory usage is only half of the initial memory usage in the master branch and it remains stable through the loops.

Looking forward to it!

**Comment by lambda-ai** [comment]
is the autograd branch merged in for 0.1.12? I see a couple of branches with "autograd" in their name, but not one simply called autograd. Also fighting with a memory leak...

**Comment by apaszke** [comment]
No, it's only in master and will be in the next release. I removed the branch after it was merged so you can temporarily install pytorch from source

**Comment by soumith** [comment]
i presume from the conversation here that i can close this issue.
