### ISSUE TITLE
[feature request] Official build for cuda 9.1?

### ISSUE THREAD

**Issue by houqp** [pytorch/pytorch#11111]
Hi pytorch team,

Looks like there is no official cuda 9.1 build for 0.4.1 anymore? We were using the official cuda 9.1 build for 0.4.0. Upgrading to 0.4.1 broke our production pipeline because `http://download.pytorch.org/whl/cu91/torch-0.4.1-cp36-cp36m-linux_x86_64.whl` returns 403.

Just wanted to check in with you before we switch to our own internal build process.

Thanks,

**Comment by soumith** [comment]
Hi @houqp.

We will maintain binary builds for
- Latest CUDA major release (9.0)
- Latest CUDA minor release (which was 9.1 at the time of release of 0.4.0, and 9.2 at the time of release of 0.4.1)
- The last major release (8.0)

Hence, we are not releasing an official build for 9.1.

**Comment by houqp** [comment]
Thanks, that's good to know :)

**Comment by edumucelli** [comment]
I was having the same issue and ended up building my own wheels with CUDA 9.1. The wheels for PyTorch 1.0, 1.1, 1.2, and 1.3 with CUDA 9.1 are in [this](https://github.com/edumucelli/build-pytorch/releases) repository if you want.
