### ISSUE TITLE
Mismatch results of index_add_ between torch.compile Inductor backend and eager mode

### ISSUE THREAD

**Issue by wuxun-zhang** [pytorch/pytorch#111133]
### 🐛 Describe the bug

I tried to write a function that an viewed input is processed by a inplace op.

```python
import torch

def transpose_inplace_index_add(x, a, index):
    y = x.permute(1, 0)
    y.index_add_(0, index, a)
    return y

x = torch.ones(3, 5)
to_be_added = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 4, 2])

ref_res = transpose_inplace_index_add(x, to_be_added, index)
print('eager_x.stride: ', x.stride())
print('eager_x: ', x)
print('eager_res.stride: ', ref_res.stride())
print('eager_res: ', ref_res)

x = torch.ones(3, 5)
compiled_fn = torch.compile(transpose_inplace_index_add)
res = compiled_fn(x, to_be_added, index)
print('inductor_x.strdides:', x.stride())
print('inductor_x: ', x)
print('inductor_res.strdides:', res.stride())
print('inductor_res: ', res)
```

By running the above test, output will be:

```
eager_x.stride:  (5, 1)
eager_x:  tensor([[ 2.,  1.,  8.,  1.,  5.],
        [ 3.,  1.,  9.,  1.,  6.],
        [ 4.,  1., 10.,  1.,  7.]])
eager_res.stride:  (1, 5)
eager_res:  tensor([[ 2.,  3.,  4.],
        [ 1.,  1.,  1.],
        [ 8.,  9., 10.],
        [ 1.,  1.,  1.],
        [ 5.,  6.,  7.]])
inductor_x.strdides: (5, 1)
inductor_x:  tensor([[ 2.,  1.,  8.,  1.,  5.],
        [ 3.,  1.,  9.,  1.,  6.],
        [ 4.,  1., 10.,  1.,  7.]])
inductor_res.strdides: (3, 1)
inductor_res:  tensor([[ 2.,  1.,  8.],
        [ 1.,  5.,  3.],
        [ 1.,  9.,  1.],
        [ 6.,  4.,  1.],
        [10.,  1.,  7.]])
```

We can see that `inductor_res` has the different strides from `eager_res` (**[3, 1]** vs. **[1, 5]**). Hence the incorrect results are generated by Inductor. By looking into the code, the output of `index_add` op is forced to generated contiguous strides [here](https://github.com/pytorch/pytorch/blob/main/torch/_refs/__init__.py#L3966) 

### Versions

Collecting environment information...
PyTorch version: 2.2.0.dev20231011+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.13 (main, Oct 13 2022, 21:15:33)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-156-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   52 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Stepping:                        6
CPU MHz:                         800.127
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5200.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.21.2
[pip3] torch==2.2.0.dev20231011+cpu
[pip3] torchaudio==2.2.0.dev20231011+cpu
[pip3] torchvision==0.15.0a0+7d2acaa
[conda] mkl                       2022.1.0           hc2b9512_224
[conda] mkl-include               2022.2.0                 pypi_0    pypi
[conda] mkl-static                2022.2.0                 pypi_0    pypi
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] torch                     2.2.0.dev20231011+cpu          pypi_0    pypi
[conda] torchaudio                2.2.0.dev20231011+cpu          pypi_0    pypi
[conda] torchvision               0.15.0a0+7d2acaa          pypi_0    pypi

cc @bdhirsh @ezyang @msaroufim @wconstab @anijain2305 @zou3519

**Comment by ezyang** [comment]
cc @Chillee

**Comment by bdhirsh** [comment]
Hmm, I think the issue is that `aten.index_add` (and friends) are a bit special: they are out-of-place ops that **always** return a contiguous tensor, even if their inputs were not contiguous. Compared to e.g. pointwise ops, which return fresh outputs with the same striding as their inputs (apparently of their first input? example below):
```
>>> x = torch.ones(4, 2)
>>> y = torch.ones(2, 4).permute(1, 0)
>>> x.stride()
(2, 1)
>>> y.stride()
(1, 4)
>>> torch.add(x, y).stride()
(2, 1)
>>> torch.add(y, x).stride()
(1, 4)
```

This patch technically fixes the issue. But I'm not sure if it's what we want?
```
diff --git a/torch/_decomp/decompositions.py b/torch/_decomp/decompositions.py
index 1edfe50cca8..aa5e0f95327 100644
--- a/torch/_decomp/decompositions.py
+++ b/torch/_decomp/decompositions.py
@@ -2269,7 +2269,7 @@ def _index_add(
     if inplace:
         return x
     else:
-        return out.squeeze(0) if zero_dim else out.contiguous()
+        return out.squeeze(0) if zero_dim else out


 @register_decomposition(aten.index_copy_)
```

The issue is that functionalization will dutifully turn the above code into something like this:
```
y = aten.permute.default(x, [1, 0])
out = torch.ops.aten.index_add.default(y, index, a)
return out
```

But `index_add` will always return a contiguous tensor, which is different from what the original (non-functionalized) program did.

So I think our options are something like:

(1) (easy but not very safe): the patch above. This causes the implementation of `aten.index_add` to diverge compared to eager when using our python dispatcher decomps, but in a way that allows it to do the right thing with functionalization

(2) (harder but safe): instead, figure out how to get functionalization to do the right thing when it encounters an out-of-place op that always returns contiguous tensors regardless of the striding of the input. I'm not actually sure how to do this though...

**Comment by Chillee** [comment]
@bdhirsh I haven't looked closely at this issue, but surely there's other operators that always return contiguous outputs? For example, sort.

**Comment by bdhirsh** [comment]
Yeah, I think this would affect all ops that behave this way. Just tested, and I think `sort` suffers from the same issue (the repro is a bit more annoying since it have an out= variant that takes in a (values, indices) tuple):
```
import torch

def f(x):
    tmp = torch.ones(2, 4, dtype=torch.int64)
    out = torch.ones(4, 2, dtype=torch.int64).permute(1, 0)
    torch.sort(x, out=(out, tmp))
    return out

x = torch.arange(8).view(2, 4)
out_ref = f(x)
out_test = torch.compile(f, backend="aot_eager")(x)
print(out_ref.stride())
print(out_test.stride())
```
prints different strides for ref vs. compile:
```
(1, 2)
(4, 1)
```

**Comment by wuxun-zhang** [comment]
@bdhirsh @Chillee Thanks for the response. We also see the similar issue for those ops running on HPU backend and are wondering if there will be a general solution.

**Comment by ezyang** [comment]
Making the decomps more accurate seems like the right thing to do.

**Comment by wuxun-zhang** [comment]
Hi @SherlockNoMad, is there any update for this issue?

**Comment by zou3519** [comment]
Seems to be fixed?

**Comment by wuxun-zhang** [comment]
Hi @zou3519, thanks for confirm. I also checked it's fixed in main branch. But did you know which changes probably fix this issue? I want to understand what happened in decomposition or Inductor. Thanks.
