### ISSUE TITLE
Some pointwise functions are not getting fused by fusion compiler

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#11118]
1) log. It is currently in the list of fusable operations, but since there's no autodiff for it, if input requires grad log is not getting fused
2) clamp  - not in the list of fusable operations, and no autodiff
3) threshold - not in the list of fusable operations, and no autodiff. Since nn.ReLU is implemented via threshold, it means that networks that use nn.ReLU cannot fuse it
4) relu (functional) is getting fused in forward, but is only half fused in backward (the comparison op is outside of fusion block), e.g. graph fuser pass gets the following graph for add-relu backward:
```
(%0 : Float(*, *)
      %1 : Float(*, *)) {
  %2 : int = prim::Constant[value=1]()
  %4 : int = prim::Constant[value=0]()
  %5 : Byte(*, *) = aten::gt(%1, %4)
  %6 : Float(*, *) = aten::type_as(%5, %1)
  %7 : Float(*, *) = aten::mul(%0, %6)
  %10 : Float(*, *) = aten::mul(%7, %2)
  return (%7, %10);
}
```
and returns the following (with gt outside of fusion group):
```
fusergraph(%0 : Float(*, *)
      %1 : Float(*, *)) {
  %2 : int = prim::Constant[value=1]()
  %4 : int = prim::Constant[value=0]()
  %5 : Byte(*, *) = aten::gt(%1, %4)
  %11 : Float(*, *), %12 : Float(*, *) = prim::FusionGroup_0[device=0](%0, %5, %1)
  return (%12, %11);
}
with prim::FusionGroup_0 = graph(%3 : Float(*, *)
      %6 : Byte(*, *)
      %7 : Float(*, *)) {
  %8 : Float(*, *) = aten::type_as(%6, %7)
  %5 : Float(*, *) = aten::mul(%3, %8)
  %1 : int = prim::Constant[value=1]()
  %2 : Float(*, *) = aten::mul(%5, %1)
  return (%2, %5);
}
```

**Comment by t-vi** [comment]
If no one else is looking at this, I might like to dip my toes into JIT. I'll report on Monday or Tuesday if I get stuck so someone with more expertise can do it.

**Comment by ngimel** [comment]
For the incomplete aten::relu fusion, the reason is that aten::gt op fell out of the special matching condition here https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/graph_fuser.cpp#L225-L239. The problem is, when I add it back, I have some "invalid context" errors in my toy example, which are likely orthogonal and have been exposed just by fused kernel being the first thing that a backward thread is running.

**Comment by t-vi** [comment]
So I'm looking at getting clamp fused, but the output type of clamp is identified as Unknown and so shouldFuse is false. I'm not quite sure where it happens: tt will not evaluate to true for clamp but will for relu in the below, but the output is defined somewhere entirely else that I haven't found yet.

https://github.com/pytorch/pytorch/blob/24eb5ad0c5388bd98f3f0ee3296ab4ad2c13bdd4/torch/csrc/jit/passes/graph_fuser.cpp#L152
