### ISSUE TITLE
nanogpt_generate: C++ compile times out, because the generated .cpp file is too large.

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#111227]
`nanogpt_generate` exists in torchbench before https://github.com/pytorch/benchmark/pull/1911,

Repro:
```
benchmarks/dynamo/torchbench.py --bfloat16 --accuracy --inference --device cuda --export-aot-inductor  --only nanogpt_generate

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by ezyang** [comment]
IIRC, we're unrolling the autoregressive generation, which is bad.

@Chillee was complaining about this in a separate context. Concretely, I propose that we should introduce a HOP that says "this is a self contained block, please compile it only once".

**Comment by desertfire** [comment]
model changed and problem does not reproduce
