### ISSUE TITLE
Test factory functions with layout=torch.strided

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#111222]
### 🚀 The feature, motivation and pitch

It'd be nice to have an OpInfo-based test that tests this. See https://github.com/pytorch/pytorch/pull/111205 and the issue that the PR resolves.

**Comment by alok1929** [comment]
Hey can I be assigned this ? Could you give me more info on how I would go about it ? It's my first issue.

**Comment by lezcano** [comment]
Sure, go for it. You can see similar tests in `test_ops.py`

**Comment by alok1929** [comment]
Hey @lezcano so I would have to write a function in test_ops.py that tests factory function using layout=torch.strided ? Please guide me through how I would use layout = torch. strided. 

I saw https://github.com/pytorch/pytorch/pull/111205, which had three different commits pushed. I didn't know which one to use as guidance.
