### ISSUE TITLE
MacOS outage (2023-10-13)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#111272]
## Current Status
Ongoing

## Error looks like
All MacOS runners are gone.

## Incident timeline (all times pacific)
1700 PST

## User impact
No runner to run MacOS jobs

## Root cause
It's unclear. I ran https://github.com/fairinternal/pytorch-gha-infra/actions/runs/6513098460 earlier in the afternoon, so it could be the trigger.  But this looks like yet another runner update from GitHub.

## Mitigation
Move MacOS job to unstable

## Prevention/followups
TBD

cc @jeanschmidt @DanilBaibak

**Comment by huydhn** [comment]
I try to run Terraform release again https://github.com/fairinternal/pytorch-gha-infra/actions/runs/6514495364/job/17695775446, but it hits AWS regional capacity issue:

```
 allocating EC2 Host: InsufficientHostCapacity: We currently do not have sufficient mac2.metal capacity in the Availability Zone you requested (us-east-1d). Our system will be working on provisioning additional capacity. You can currently get mac2.metal capacity by specifying us-east-1b, us-east-1c in your request.
```

**Comment by DanilBaibak** [comment]
The runners are back:

<img width="1278" alt="Screenshot 2023-10-14 at 16 13 44" src="https://github.com/pytorch/pytorch/assets/3964975/0f7a4a15-dd5c-4330-915e-939a65d980f2">
