### ISSUE TITLE
[dynamo] annotate `allow_in_graph` with soft constraints

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#111209]
### 🚀 The feature, motivation and pitch

Originally suggested: https://github.com/pytorch/pytorch/pull/110709/files#r1358391537

```python
@allow_in_graph(
    constraints={
        "mutates": "only self.state, and where Tensors are concerned, only add new (not remove/mutate)",
        "side-effects": "no side-effects like printing or modifying global variables",
        "return values": "must be derived from self.params (guarded) tensor metadata",
    }
)
def _init_group(self, ..):
  ..
```

The constraints cannot be enforced of course - dynamo cannot inspect the interior of the annotated function. But we are explicitly asking the user to guarantee these properties hold. 

It is still quite unsafe, but at least we know why it is unsafe, and the user might understand why something might break if they try to incorrectly modify this `@allow_in_graph` function.

---

This is stronger than the implicit contract suggested in: https://github.com/pytorch/pytorch/blob/35750bf9d134726b47451d78b731017ad27fbc8b/docs/source/torch.compiler_faq.rst#L497
> By using allow_in_graph to annotate a function, you must make sure your code meets the following requirements:
>
> - All outputs in your function only depend on the inputs and do not depend on any captured Tensors.
> - Your function is functional. That is, it does not mutate any state. This may be relaxed; we actually support functions that appear > to be functional from the outside: they may have in-place PyTorch operations, but may not mutate global state or inputs to the function.
> - Your function does not raise data-dependent errors.

```diff
- All outputs in your function only depend on the inputs and do not depend on any captured Tensors.
+ All outputs in your function only depend on the inputs or Tensor metadata and do not depend on any captured Tensor values.
```

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @bdhirsh @zou3519 @aakhundov

**Comment by aryan-py** [comment]
I would love to pick this up, this being my first issue I would love any advice

**Comment by zou3519** [comment]
I don't think we need this, plus this is BC-breaking. We improved the docstring for allow_in_graph to mention how it can be a footgun: https://pytorch.org/docs/main/generated/torch.compiler.allow_in_graph.html#torch.compiler.allow_in_graph
