### ISSUE TITLE
Running torch.cuda.is_available() before import from torch._C import *

### ISSUE THREAD

**Issue by Atcold** [pytorch/pytorch#11121]
## Issue description

Using a NFS, sometimes I find myself on machines without _Cuda_, although _PyTorch_ was installed on a _Cuda_ enabled machine. _PyTorch_ fails to load and crashes instead.

## Code example

```python
In [1]: import torch
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-23eb050c9654> in <module>()
----> 1 import torch

[...]/atcold/anaconda3/lib/python3.6/site-packages/torch/__init__.py in <module>()
     78     pass
     79
---> 80 from torch._C import *
     81
     82 __all__ += [name for name in dir(_C)

ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory
```

## System Info

- PyTorch or Caffe2: _PyTorch_
- How you installed PyTorch (conda, pip, source): `conda`, on a _Cuda_ enabled machine
- OS: _CentOS_ 7
- PyTorch version: `0.4.1`
- Python version: `3.6.6`
- CUDA/cuDNN version: `N/A` or `9.0`

**Comment by SsnL** [comment]
You can create two conda environments, one with cuda pytorh and one with cpu-only pytorch.

**Comment by Atcold** [comment]
Sure, sure, but then I would have to reinstall all packages twice?
Wouldn't be easier just to check whether cuda is available before loading those libs?

**Comment by vishwakftw** [comment]
Could you please reinstall PyTorch? This seems to be related to a recent issue which has been fixed.

**Comment by Atcold** [comment]
@vishwakftw, the issue was about different `cudnn` versions.
On some machines I do not have any `cudnn` or GPU altogether.

**Comment by vishwakftw** [comment]
Oh, sorry. I noticed the `libcudart.so.9.0` and thought the solved issue was at play.

**Comment by soumith** [comment]
@Atcold this was fixed recently. What you are seeing is indeed what @vishwakftw was pointing to. If you reinstall pytorch from conda, you'll be fine.

**Comment by Atcold** [comment]
Yeah, that was it. Now it works fine.
@soumith, you mentioned that

> `conda` changed cudatoolkit from `9.0` to `9.2` 3 days ago.

What does that have to do with a machine that may not have Cuda at all?
