### ISSUE TITLE
Improve type checking for Tensor.record_stream

### ISSUE THREAD

**Issue by hauntsaninja** [pytorch/pytorch#111268]
### 🐛 Describe the bug

If you type check the following file:
```
import torch

def foo(x: torch.Tensor):
    stream = torch.cuda.current_stream()
    x.record_stream(stream)
```
You currently get output like:
```
λ mypy x.py                                       
x.py:5: error: Argument 1 to "record_stream" of "_TensorBase" has incompatible type "torch.cuda.streams.Stream"; expected "torch._C.Stream"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

This is because the `torch._C.Stream` in the generated pyi is a class that has no nominal / inheritance-based relationship to the `Stream` found in `torch.cuda.streams`.

One "quick" fix would be to make the Stream class in `__init__.pyi.in` a Protocol. But that would be a little bit of a lie.

Instead, one could simply make `record_stream` take in a Protocol that is exactly like Stream. This would work, but the problem is `record_stream` is generated, and I'm not quite sure what changes are legal to make to native_functions.yaml

### Versions

2.1

cc @ezyang @malfet @xuzhao9 @gramster

**Comment by malfet** [comment]
@hauntsaninja can you please run `python3 -mtorch.utils.collect_env` and post its output here? (I'm interested in python and mypy versions)

**Comment by hauntsaninja** [comment]
Thanks for the quick fix! I'd missed the missing base when I looked at it since it was one up in the mro :-)
