### ISSUE TITLE
Feature Request: Add API to anneal LR and WD of optimizer

### ISSUE THREAD

**Issue by IanChen83** [pytorch/pytorch#1112]
In [PyTorch ImageNet example](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L266-L270), the approach to anneal LR is to change internal parameters, which is defined in [here](https://github.com/pytorch/pytorch/blob/master/torch/optim/optimizer.py#L28). An API to handle hyper parameter state might be better.

Possible solutions might be
1. A member function to directly change internal members
2. A annealing scheme function `(epoch) -> {lr, wd, ...}` as an argument when initializing the opimizers

cc @vincentqb

**Comment by eladhoffer** [comment]
I can to try integrate this: https://github.com/eladhoffer/convNet.pytorch/blob/master/utils.py#L116 into optim. it works with regimes either with dict like here: https://github.com/eladhoffer/convNet.pytorch/blob/master/models/resnet.py#L153 or with functions that take current epoch and returns parameters.

**Comment by soumith** [comment]
LRSchedulers reasonably handle this aspect now, and they are in the PyTorch API.
