### ISSUE TITLE
Possibly a bug: Why the default_collate in dataloader will change the type of the data?

### ISSUE THREAD

**Issue by maplewizard** [pytorch/pytorch#1113]
I have a float train data. When I send it into dataloader and get it with enumerate. I found the type of my data has been changed into torch.DoubleTensor. But I really need is my original type. I found this was caused in `torch/utils/data/dataloader.py' in the definition of the default_collate. Is this a bug? Or how could I make it keep my original datatype?

```
def default_collate(batch):
    "Puts each data field into a tensor with outer dimension batch size"
    if torch.is_tensor(batch[0]):
        return torch.cat([t.unsqueeze(0) for t in batch], 0)
    elif isinstance(batch[0], int):
        return torch.LongTensor(batch)
    elif isinstance(batch[0], float):
        return torch.DoubleTensor(batch)
    elif isinstance(batch[0], str):
        return batch

```

**Comment by soumith** [comment]
What is your original data type?

**Comment by soumith** [comment]
Python's `float` number type has Double precision, and there's no float32 in python numbers.
Hence, we are doing exactly what we should without losing precision.

If we detect that the incoming data is a Tensor, we already retain it's correct type in the section: `if torch.is_tensor(batch[0]):`

**Comment by maplewizard** [comment]
@soumith Actually, I use np.array(..., dtype = 'float32')

**Comment by apaszke** [comment]
This is expected. See [this line](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L67-L68). If you need to collate the batches in a different way you can always supply your own collate_fn.

**Comment by apaszke** [comment]
Sorry I didn't notice that the type of the array has been changed.

**Comment by soumith** [comment]
fixed in master. will be in next release.
