### ISSUE TITLE
[Feature Request] CRF in PyTorch

### ISSUE THREAD

**Issue by himkt** [pytorch/pytorch#11134]
CRF plays an important role in some NLP tasks (e.g. POS tagging, Chunking, NER)

There are some PyTorch repositories which use CRF.
- https://github.com/jiesutd/NCRFpp
- https://github.com/LiyuanLucasLiu/LM-LSTM-CRF
- https://github.com/ZhixiuYe/HSCRF-pytorch

Additionally, [PyTorch documentation](https://pytorch.org/tutorials/beginner/nlp/advanced_tutorial.html) also uses CRF.
So, I think it would be great to create `nn.CRF` officially.
What do you think about it?

cc @albanD @mruberry @jbschlosser

**Comment by soumith** [comment]
@himkt that sounds interesting, but It's hard to come up with a clean API for `nn.CRF`. Can you propose something?

**Comment by himkt** [comment]
Let me close because there are good libraries for CRF in pytorch (e.g. pytorch-crf).
