### ISSUE TITLE
Install cuda 9.0  - cudatoolkit 9.2

### ISSUE THREAD

**Issue by Bruno-Hanzen** [pytorch/pytorch#11138]
## Issue description

installing Pytorch - **cuda 9.0** with conda

"_conda install pytorch torchvision -c pytorch_"

triggers the installation of **cudatoolkit-9.2**

Conda displays the following:

"The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytorch-0.4.1              |py36_cuda9.0.176_cudnn7.1.2_1       463.8 MB  pytorch
    torchvision-0.2.1          |           py36_1         123 KB  pytorch
    cudatoolkit-9.2            |                0       351.0 MB
    ninja-1.8.2                |   py36h6bb024c_1         1.3 MB"

which, obviously, cannot work.
Workaround: manually trigger the installation of cudatoolkit-9.0 (conda install cudatoolkit==9.0)

Proposed solution: fix the conda package

I work under Ubuntu 18.04 and nVidia drivers 390.
Upgrading to higher version of nVidia drivers is an issue on my system due to secure boot.

**Comment by zou3519** [comment]
Try `conda install pytorch torchvision cuda90 -c pytorch` ?

**Comment by Bruno-Hanzen** [comment]
Richard,

thanks for the suggestion, but, as mentioned in the issue report, I  
have installed the 9.0 library manually and it works. I am not willing  
to scratch everything to test.
By the way, I don't remember all the tests I did before finding the  
workaround, but I think that I tried the one you suggest.

Quoting Richard Zou <notifications@github.com>:

> Try conda install pytorch torchvision cuda90 -c pytorch ?
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].



Links:
------
[1] https://github.com/pytorch/pytorch/issues/11138#issuecomment-417684108
[2]

**Comment by soumith** [comment]
we fixed this with newly issued binaries 3 days and 12 hours ago.
PyTorch no longer installs or depends on `cudatoolkit == 9`.

I'm surprised that your `conda` didn't install our updated binaries (you reported the issue 2 days ago). Wondering if you installed your PyTorch a bit before than 3 days, 12 hours ago -- but opened an issue 2 days ago. If that's not the case, I'll investigate further.

Thanks for reporting.

**Comment by Bruno-Hanzen** [comment]
Dear Soumith,

" Wondering if you installed your PyTorch a bit before than 3 days, 12 
hours ago -- but opened an issue 2 days ago. If that's not the case, 
I'll investigate further.": correct, I installed it a few days before 
raising the issue. As far a I am concerned, the issue can be closed.

Yours,

Bruno

Le 02-09-18 à 05:08, Soumith Chintala a écrit :
