### ISSUE TITLE
Custom Tensor Instances Do Not Work With DDP

### ISSUE THREAD

**Issue by HanGuo97** [pytorch/pytorch#111348]
### 🐛 Describe the bug

Existing DDP implementation throws an error for [`UninitializedParameter`](https://github.com/pytorch/pytorch/blob/e0e15a4ac61648cc8f63f0ab102c32e8884fb5d1/torch/nn/parallel/distributed.py#L765). This makes sense.

However, behind the scene, `isinstance(tensor, UninitializedParameter)` translates to `UninitializedParameter.__instancecheck__(tensor)`, which is implemented [here](https://github.com/pytorch/pytorch/blob/7bcf7da3a268b435777fe87c7794c382f444e86d/torch/nn/parameter.py#L8).

The aforementioned implementation returns `True` for custom Tensor instances (because of their `_is_param` attribute). I believe the intention of this implementation is to let custom Tensor instances to be compatible with `Parameter`. But this causes these custom Tensor instances to be instances of `UninitializedParameter`, and hence incompatible with DDP.

### Versions

NA

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @penguinwu

**Comment by will-cromar** [comment]
I'm running into this issue too. All `Tensor` subclass parameters are considered `UninitializedParameter`s.

`UninitializedParameter` inherits `Parameter`'s metaclass, which only looks at `_is_param` (set by [`Parameter.__new__`](https://github.com/pytorch/pytorch/blob/68ad3eb722a429db738f93c73af82f700bc89ef5/torch/nn/parameter.py#L45-L56)) to determine `isinstance`. So if your custom class is a `Parameter`, it's also an `UninitializedParameter`.

https://github.com/pytorch/pytorch/blob/68ad3eb722a429db738f93c73af82f700bc89ef5/torch/nn/parameter.py#L10-L13

`torch.Tensor` (but not subclasses) get wrapped in `Parameter`, which do not have `_is_param` set, so they are not `UninitializedParameter`.

Here's a simple case to demonstrate (tested with `torch==2.3.0+cpu`):

```python
import torch

# Normal Tensor
t = torch.nn.parameter.Parameter(torch.Tensor())
print(t)
print('UninitializedParameter?', isinstance(t, torch.nn.parameter.UninitializedParameter))
# Parameter containing:
# tensor([], requires_grad=True)
# UninitializedParameter? False

# Custom tensor
class MyTensor(torch.Tensor):
  pass

mt = torch.nn.parameter.Parameter(MyTensor())
print(mt, isinstance(mt, torch.nn.parameter.UninitializedParameter))
print('UninitializedParameter?', isinstance(mt, torch.nn.parameter.UninitializedParameter))
# Parameter(MyTensor([], requires_grad=True)) True
# UninitializedParameter? True
```

cc @qihqi @ezyang
