### ISSUE TITLE
Can't load cpp_extension because of typeError in _find_module (cpu-only+win32)

### ISSUE THREAD

**Issue by fradav** [pytorch/pytorch#11137]
## Issue description

With a fresh 0.4.1 installation of pytorch, I can't access cpp_extension: 

```
(datascience) C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools>python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch.utils.cpp_extension import BuildExtension, CppExtension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\tools\miniconda3\envs\datascience\lib\site-packages\torch\utils\cpp_extension.py", line 61, in <module>
    CUDA_HOME = _find_cuda_home()
  File "C:\tools\miniconda3\envs\datascience\lib\site-packages\torch\utils\cpp_extension.py", line 30, in _find_cuda_home
    if not os.path.exists(cuda_home):
  File "C:\tools\miniconda3\envs\datascience\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
>>>
```

## Code example

See above

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source):
- OS: Windows 10
- PyTorch version: 0.4.1
- Python version: 3.6.5
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version: 3.12.1
- Versions of any other relevant libraries:

**Comment by peterjc123** [comment]
@fradav Yes, this is fixed in master. Please refer to the changes to the function `_find_cuda_home()` in `torch/utils/cpp_extension.py`.

**Comment by SsnL** [comment]
See @peterjc123 's comment above
