### ISSUE TITLE
Trace dynamic batch size with make_fx

### ISSUE THREAD

**Issue by Tim-Salzmann** [pytorch/pytorch#111312]
Hello,

is there a way to keep the batch dimension dynamic when tracing with `make_fx` as described in the README.md.

Example

```
import torch
from functorch import make_fx
from torch.func import vmap, jacrev

model = torch.nn.Sequential(
    torch.nn.Linear(2, 512),
    torch.nn.Tanh(),
    torch.nn.Linear(512, 2),
)

trace_inp = torch.randn(1, 2)
traced_model = make_fx(vmap(jacrev(model)), tracing_mode='real')(trace_inp)

# This will work
print(traced_model(torch.randn(1, 2)))

# This will fail with: RuntimeError: shape '[1, 2]' is invalid for input of size 4
print(traced_model(torch.randn(2, 2)))

```

Switching to `tracing_mode='symbolic'` will result in `RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides`

Appreciate the help!

Best
Tim

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

**Comment by ezyang** [comment]
probably just need to add some more dynamic shapes to functorch

**Comment by zou3519** [comment]
> Real tensors showing up under FakeMode (after fixing the above two)
NOTE: The tensor passed to aten.t looks FakeTensor. Is it tripping because it is a parameter?

In order to make_fx this, we need to use functional_call on it first

**Comment by guilhermeleobas** [comment]
> 2. Real tensors showing up under FakeMode (after fixing the above two)
>     NOTE: The tensor passed to `aten.t` looks FakeTensor. Is it tripping because it is a parameter?
> 
> ```
> Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. 
> Found in aten.t.default(Parameter containing: tensor([...], size=(512, 2), requires_grad=True))
> ```

@kshitij12345, I think what is missing is to call `make_fx` with  `make_fx(..., _allow_non_fake_inputs=True)` as otherwise, the `FakeTensorMode` object would not be allowed to convert regular tensors into non-fake ones. Does this makes sense?

```python
import torch
from functorch import make_fx
from torch.func import vmap, jacrev

model = torch.nn.Sequential(
    torch.nn.Linear(2, 512),
    torch.nn.Tanh(),
    torch.nn.Linear(512, 2),
)

trace_inp = torch.randn(1, 2)
traced_model = make_fx(vmap(jacrev(model)), tracing_mode='symbolic',
                       _allow_non_fake_inputs=True)(trace_inp)

# This will work
print(traced_model(torch.randn(1, 2)))

# This will fail with: RuntimeError: shape '[1, 2]' is invalid for input of size 4
print(traced_model(torch.randn(2, 2)))
```

To which would give the same result/error as `tracing_mode='real'`

```
tensor([[[ 0.0452, -0.0294],
         [ 0.1050, -0.2903]]], grad_fn=<ViewBackward0>)
Traceback (most recent call last):
  File "/home/guilhermeleobas/git/pytorch/d.py", line 18, in <module>
    print(traced_model(torch.randn(2, 2)))
  File "/home/guilhermeleobas/git/pytorch/torch/fx/graph_module.py", line 736, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/guilhermeleobas/git/pytorch/torch/fx/graph_module.py", line 315, in __call__
    raise e
  File "/home/guilhermeleobas/git/pytorch/torch/fx/graph_module.py", line 302, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/guilhermeleobas/git/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/guilhermeleobas/git/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.0 from /home/guilhermeleobas/git/pytorch/torch/fx/experimental/proxy_tensor.py:508 in wrapped", line 9, in forward
  File "/home/guilhermeleobas/git/pytorch/torch/_ops.py", line 516, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: shape '[1, 2]' is invalid for input of size 4
```

**Comment by zou3519** [comment]
works now (with functional_call)
