### ISSUE TITLE
Sequential to support better slicing

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#1114]
```python
import torch.nn as nn

a = nn.Sequential(nn.Linear(1, 1), nn.Linear(1, 1))

a[0] # works
nn.Sequential(*a[:-1]) # blows
nn.Sequential(*list(a)[:-1]) # works
```

Would be nice in absence of [remove_module](https://github.com/pytorch/pytorch/issues/358), but probably low-priority.

**Comment by soumith** [comment]
we just wanted people to convert Sequential to List to do advanced indexing. 

Implementing all advanced indexing in Sequential seemed way to unnecessary considering how much code we'll have to add.
