### ISSUE TITLE
AOTAutograd generates wrong strides for view+inplace op

### ISSUE THREAD

**Issue by wuxun-zhang** [pytorch/pytorch#111417]
### 🐛 Describe the bug

There is strides mismatch between eager and custom compiler backend like Habana HPU which produce contiguous strides. Here is an example to demonstrate the issue.

```python
import torch

def transpose_inplace_mul(x):
    y = x.t()
    y.mul_(2)
    return y

x = torch.arange(6, dtype=torch.float32).reshape([2, 3])
ref_res = transpose_inplace_mul(x)
print('ref_cpu_x.stride: ', x.stride())
print('ref_cpu_x: ', x.cpu())
print('ref_cpu_res.stride: ', ref_res.stride())
print('ref_cpu_res: ', ref_res.cpu())

x = torch.arange(6, dtype=torch.float32).reshape([2, 3]).to(device='hpu')
compiled_fn = torch.compile(transpose_inplace_mul, backend='aot_hpu_training_backend')
res = compiled_fn(x)
print('hpu_x.strdides:', x.stride())
print('hpu_x: ', x.cpu())
print('hpu_res.strdides:', res.stride())
print('hpu_res: ', res.cpu())
```

Outputs is like below:
```
ref_cpu_x.stride:  (3, 1)
ref_cpu_x:  tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
ref_cpu_res.stride:  (1, 3)
ref_cpu_res:  tensor([[ 0.,  6.],
        [ 2.,  8.],
        [ 4., 10.]])

hpu_x.strdides: (3, 1)
hpu_x:  tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
hpu_res.strdides: (2, 1)
hpu_res:  tensor([[ 0.,  2.],
        [ 4.,  6.],
        [ 8., 10.]])
```

We can see that **hpu_res.strides** is different from the referenced **cpu_res.strides**. And hence output results is different with CPU reference result. For Habana HPU, currently it produces contiguous strides, hence there is a handling (https://github.com/pytorch/pytorch/blob/main/torch/_refs/__init__.py#L466) for non-contiguous output.
We expect AOTAutograd can also handle this. Previously in another issue thread, stride-agnostic mode was mentioned.

The generated functional FX graph as below:
```
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: f32[2, 3]):
        
        t: f32[3, 2] = torch.ops.aten.t.default(arg0_1);  arg0_1 = None
        
        mul: f32[3, 2] = torch.ops.aten.mul.Tensor(t, 2);  t = None
        t_1: f32[2, 3] = torch.ops.aten.t.default(mul);  mul = None
        t_2: f32[3, 2] = torch.ops.aten.t.default(t_1)
        return (t_1, t_2)
```

cc @ezyang @anijain2305 @chauhang @penguinwu @zou3519 @bdhirsh @msaroufim @wconstab

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gitf8b6084
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
CMake version: version 3.27.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-163-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

**Comment by wuxun-zhang** [comment]
cc @karthiknagasub

**Comment by wuxun-zhang** [comment]
It's similar with https://github.com/pytorch/pytorch/issues/111133, but this issue is more general and for more ops like elementwise unary/binary ops.

**Comment by zou3519** [comment]
It's a bit hard for us to test this since we don't have an hpu, do you  have a repro with cpu or gpu?

**Comment by zou3519** [comment]
Closing this issue because we can't repro this and there hasn't been a reply. Please feel free to reopen if this is still an issue.
