### ISSUE TITLE
BF16 Matmul not get same result on cuda and cpu

### ISSUE THREAD

**Issue by MikeChenfu** [pytorch/pytorch#111457]
### 🐛 Describe the bug

Hello, I tested matmul using torch.bfloat16 but get the different results on cpu and gpu. The greatest absolute difference is 1.0.  Appreciate it if someone has any ideas abou it.

```python
import unittest
import torch
class Test(unittest.TestCase):
    def test(self):
        print(torch.backends.cuda.matmul.allow_bf16_reduced_precision_reduction)
        torch.backends.cuda.matmul.allow_bf16_reduced_precision_reduction = False
        _dtype = torch.bfloat16 
        torch.manual_seed(0)
        # python -c "import torch; print(torch.__version__)"  : 2.0.1+cu117
        in_feature = 2048 
        output_features = [512, 2048, 4096]
        for output_feature in output_features:
            # generate data
            a = torch.randn((2048, in_feature), dtype=_dtype)
            b = torch.randn((in_feature, output_feature), dtype=_dtype)
            d = torch.randn((output_feature, in_feature), dtype=_dtype)
            res_cpu = a @ b
            res_gpu = a.to('cuda') @ b.to('cuda') 
            torch.testing.assert_close(res_cpu, res_gpu.to('cpu'), rtol=1e-3, atol=1e-1)
            res_cpu = torch.matmul(res_cpu,  d)
            res_gpu = torch.matmul(res_gpu, d.to("cuda"))
            torch.testing.assert_close(res_cpu, res_gpu.to('cpu'), rtol=1e-2, atol=1e-1)
            print("in_feature : {in_feature}, output_features:{output_features} passed")
if __name__ == '__main__':
    unittest.main()
```

```
self = <tests.bf16_test.Test testMethod=test>

    def test(self):
        print(torch.backends.cuda.matmul.allow_bf16_reduced_precision_reduction)
        torch.backends.cuda.matmul.allow_bf16_reduced_precision_reduction = False
        _dtype = torch.bfloat16
        torch.manual_seed(0)
        # python -c "import torch; print(torch.__version__)"  : 2.0.1+cu117
        in_feature = 2048
        output_features = [512, 2048, 4096]
        for output_feature in output_features:
            # generate data
            a = torch.randn((2048, in_feature), dtype=_dtype)
            b = torch.randn((in_feature, output_feature), dtype=_dtype)
            d = torch.randn((output_feature, in_feature), dtype=_dtype)
            res_cpu = a @ b
            res_gpu = a.to('cuda') @ b.to('cuda')
>           torch.testing.assert_close(res_cpu, res_gpu.to('cpu'), rtol=1e-3, atol=1e-1)
E           AssertionError: Tensor-likes are not close!
E           
E           Mismatched elements: 220 / 1048576 (0.0%)
E           Greatest absolute difference: 1.0 at index (1709, 134) (up to 0.1 allowed)
E           Greatest relative difference: 0.0078125 at index (83, 110) (up to 0.001 allowed)

tests/bf16_test.py:19: AssertionError
======================================== short test summary info ========================================
FAILED tests/bf16_test.py::Test::test - AssertionError: Tensor-likes are not close!
=========================================== 1 failed in 6.17s ==========================================
```

### Versions

PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.143.bsk.7-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: A100-SXM-80GB

Nvidia driver version: 450.191.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         3000.001
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        108 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.1+cu118
[pip3] torchvision==0.15.1+cu118
[pip3] triton==2.0.0
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchaudio                2.0.1+cu118              pypi_0    pypi
[conda] torchvision               0.15.1+cu118             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by jon-chuang** [comment]
There seems to be a bug causing insertion of 1.0s. The fact that the absolute difference is precisely 1.0 is fishy enough.

Related: https://github.com/pytorch/pytorch/issues/111484

**Comment by jon-chuang** [comment]
To my understanding, bf16 reduction flag does nothing with triton backend. For CuBLAS maybe it makes a difference... see: https://github.com/pytorch/pytorch/pull/108982

**Comment by Aidyn-A** [comment]
One interesting detail is that if I do the same thing with double (on any device) it will be an average between CPU and GPU:
```python
            res_cpu = a @ b
            res_gpu = a.to('cuda') @ b.to('cuda')
            res_double = a.double() @ b.double()
            diff = torch.abs(res_cpu - res_gpu.cpu()) >= 0.1
            print(res_cpu[diff])
            print(res_gpu[diff])
            print(res_double[diff])
```

prints:
```
tensor([  32.2500,   51.2500,   38.2500,   57.2500,  -90.5000,   59.7500,
         126.0000,   26.8750,   30.0000,   24.7500,   17.6250,  -67.5000,
          81.5000,   22.3750,  -17.8750,   67.0000,  -54.7500,  -46.2500,
         -16.8750,   34.0000,  -66.0000,   24.0000,  -26.7500,  -22.8750,
         -72.5000,  -39.2500,  -55.2500,   37.0000,   88.0000, -172.0000,
          29.2500,  -60.5000,  -46.2500,  -73.5000], dtype=torch.bfloat16)
tensor([  32.0000,   51.0000,   38.5000,   57.0000,  -91.0000,   59.5000,
         125.5000,   27.0000,   29.8750,   24.8750,   17.7500,  -67.0000,
          82.0000,   22.5000,  -18.0000,   66.5000,  -54.5000,  -46.5000,
         -17.0000,   34.2500,  -65.5000,   23.8750,  -26.8750,  -22.7500,
         -73.0000,  -39.0000,  -55.0000,   37.2500,   87.5000, -171.0000,
          29.3750,  -60.2500,  -46.5000,  -74.0000], device='cuda:0',
       dtype=torch.bfloat16)
tensor([  32.1250,   51.1250,   38.3750,   57.1250,  -90.7500,   59.6250,
         125.7500,   26.9375,   29.9375,   24.8125,   17.6875,  -67.2500,
          81.7499,   22.4375,  -17.9375,   66.7500,  -54.6250,  -46.3750,
         -16.9375,   34.1250,  -65.7500,   23.9375,  -26.8125,  -22.8125,
         -72.7500,  -39.1250,  -55.1250,   37.1250,   87.7500, -171.5000,
          29.3125,  -60.3750,  -46.3750,  -73.7500], dtype=torch.float64)
```

My brief error estimation analysis based on your example results in even larger absolute difference. So I am convinced that this is not a bug, it is just precision error.

**Comment by jon-chuang** [comment]
The same error is encountered with `torch.backends.cuda.matmul.allow_bf16_reduced_precision_reduction = True`. So I don't think its necessarily something to do with bf16 accumulation. It just seems that the CPU v.s. GPU implementations have some numerical differences. 

I'm not sure if this is to be expected.

I believe that bf16 ought to be more prone to this since it has very few bits in the fraction. I believe you would not see this if you were to normalize your matrix to be `M / max(abs(M))`

**Comment by jon-chuang** [comment]
You can see that the following passes when I normalize by the dim K:

```python
import torch
print(torch.backends.cuda.matmul.allow_bf16_reduced_precision_reduction)
torch.backends.cuda.matmul.allow_bf16_reduced_precision_reduction = True
_dtype = torch.bfloat16 
torch.manual_seed(0)
# python -c "import torch; print(torch.__version__)"  : 2.0.1+cu117
in_feature = 2048
output_features = [512, 2048, 4096]
for output_feature in output_features:
    # generate data
    a = torch.randn((512, in_feature), dtype=_dtype) / in_feature
    b = torch.randn((in_feature, output_feature), dtype=_dtype) / in_feature
    res_cpu = a @ b
    res_gpu = a.to('cuda') @ b.to('cuda') 
    diff = torch.abs(res_cpu - res_gpu.cpu()) >= 0.1
    res_double = a.double() @ b.double()
    res_double_gpu = a.to('cuda').double() @ b.to('cuda').double()

    print(res_cpu[diff])
    print(res_gpu[diff])
    print(res_double[diff])
    print(res_double_gpu[diff])

    torch.testing.assert_close(res_cpu, res_gpu.to('cpu'), rtol=1e-3, atol=1e-1)
    print("in_feature : {in_feature}, output_features:{output_features} passed")
```

So, it serves as a lesson that one ought to normalize the values when using bfloat16.

**Comment by MikeChenfu** [comment]
Thanks @jon-chuang. Appreciate your example!  Regarding the real scenario, we need to normalize `a,b` first and then bring the results back to real value by multiplying reduction dim. Does it correct?

**Comment by jon-chuang** [comment]
> we need to normalize a,b first and then bring the results back to real value by multiplying reduction dim. Does it correct?

Yes, it is one possible way. You can read about how even more constained datatypes like float8 have to scale the values to retain accuracy. 

https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/examples/fp8_primer.html

However, this doesn't get rid of the error. It's just that for a matmul or even mul op, absolute error goes up quadratically when you scale up, and relative error goes up linearly. So scaling down only keeps the errors relatively small.

**Comment by colesbury** [comment]
Closing this, as it does not sound like a bug. Please re-open if that is not the case.
