### ISSUE TITLE
[numpy interop] comparison between numpy and tensor is legal in compile but not in eager

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#111490]
### 🐛 Describe the bug

```python
import torch
import numpy as np

@torch.compile(fullgraph=True)
def fn2(x, y):
    return y > x

x, y = torch.randn(512), np.zeros(512)
print(fn2(x,y))  # Succeeds
print(y > x)  # TypeError: '>' not supported between instances of 'numpy.ndarray' and 'Tensor'
```

Not sure if a feature or a bug. Personally, I think it's a feature, but would like to confirm with @lezcano @peterbell10 if they agree

### Versions

main

**Comment by lezcano** [comment]
Yep, feature!

See https://github.com/pytorch/rfcs/blob/master/RFC-0032-numpy-support-in-dynamo.md, see in particular the paragraph "A superset of NumPy" in particular

**Comment by lezcano** [comment]
In general, mixing Tensor and ndarrays is not supported in eager, and it may work by chance on compile with some undefined semantics. People should not rely in this :D

**Comment by jon-chuang** [comment]
Hmm ok, great!
