### ISSUE TITLE
[FX Quant] operator.matmul (@ operator ) is not converted to torch.ops.quantized.matmul

### ISSUE THREAD

**Issue by poutyface** [pytorch/pytorch#111450]
### 🐛 Describe the bug

Maybe, this line? only torch.matmul is included here.
 
https://github.com/pytorch/pytorch/blob/main/torch/ao/quantization/fx/_lower_to_native_backend.py#L359

### Versions

main branch

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by andrewor14** [comment]
@jerryzh168 Is there any reason for this? Looks like `operator.add` and `operator.mul` are supported

**Comment by jerryzh168** [comment]
yeah it could be, what is `@` in fx graph?

**Comment by andrewor14** [comment]
I think `@` is a shorthand for `operator.matmul`? Should we just add support for lowering this in `_lower_to_native_backend`, just like how we lower `operator.add` and `operator.mul` today?

**Comment by jerryzh168** [comment]
> I think `@` is a shorthand for `operator.matmul`? Should we just add support for lowering this in `_lower_to_native_backend`, just like how we lower `operator.add` and `operator.mul` today?

I see, thanks. if we have a corresponding quantized matmul, we can add `operator.matmul` to backend config and lowering

**Comment by andrewor14** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/113954
