### ISSUE TITLE
When keep_inference_input_mutations=True is set, one dynamic shape test fails

### ISSUE THREAD

**Issue by oulgen** [pytorch/pytorch#111482]
### 🐛 Describe the bug

In order to get aot_eager and inductor backends to be consistent, I submitted a PR to set `keep_inference_input_mutations=True` but `dynamo/test_dynamic_shapes.py::DynamicShapesAotAutogradFallbackTests::test_call_fn_with_non_const_inputs_aot_unsafe_dynamic_shapes` started failing with
```
"RuntimeError: a leaf Variable that requires grad is being used in an in-place operation."
```

Example failure: https://hud.pytorch.org/pr/111453

@bdhirsh noted that this is probably a bug with autograd

### Versions

github master

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by bdhirsh** [comment]
This is likely a regression from https://github.com/pytorch/pytorch/pull/111011, so we should fix this.

This simplest fix would be to perform this `copy_()` under either a .detach() or no_grad(): https://github.com/pytorch/pytorch/blob/main/torch/_functorch/aot_autograd.py#L1745

**Comment by jon-chuang** [comment]
Hello @bdhirsh is this a good issue to get started on aotautograd? Might I assign myself?

**Comment by oulgen** [comment]
@bdhirsh is currently out of office but we chatted offline and performing the `copy_()` under either a `.detach()` or `no_grad():` would not actually be safe. There's a bug in aot_autograd that we need to figure out.

**Comment by bdhirsh** [comment]
I tried running the test with that flag set for the aot_eager backend locally. Closing this issue, although at some point we should probably make one of the debugging backends keep input mutations in the graph (I actually think we should keep aot_eager as is, and only update aot_eager_decomp_partition to keep input mutations in the graph - that way it's easy to use backends to bisect issues with input mutations).
