### ISSUE TITLE
DISABLED test_check_inplace_nn_CELU_mps_float32 (__main__.TestModuleMPS)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#111449]
Platforms: mac, macos

This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/test_modules.py%3A%3ATestModuleMPS%3A%3Atest_check_inplace_nn_CELU_mps_float32)).

This test has been failing in MacOS x86 for a while https://hud.pytorch.org/pytorch/pytorch/commit/973c87b320b5e7489f18b719d5b1c57a2051ae10.  The error is:

```
RuntimeError: MPS backend out of memory (MPS allocated: 0 bytes, other allocations: 0 bytes, max allowed: 1.70 GB). Tried to allocate 0 bytes on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
```

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Hmm, this is weird, we should not be running any MPS tests on GitHub Actions runners as they do not have an access to MPS hardware....
