### ISSUE TITLE
[torch.Tensor] containers `__contains__` behaviour is inconsistent with `Tensor` due to overloading `eq`

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#111542]
### 🐛 Describe the bug

Relevance: usage of tensor set `__contains__`
https://github.com/pytorch/pytorch/blob/b2b5f1377b9bd79c5cf8404ae0d7567bbd343323/torch/nn/modules/module.py#L2164

Trips up dynamo because set `__contains__` in dynamo is not shortcutted on hashes but on equality.

### Failure case: list

See:
```python
param = torch.zeros(5)
param2 = torch.zeros(5, 10)

tensor_list = [param2]
print(param in tensor_list)  # error - tried to broadcast due to equality
```
```python
param = torch.zeros(5)
param2 = torch.zeros(5)

tensor_list = [param2]
print(param in tensor_list)  # Fails
```

This returns True
```python
param = torch.zeros(5)

tensor_list = [param]
print(param in tensor_list)  # True, due to hash equality
```

This means that for the purpose of `contains` behaviour, tensor equality of values is unnecessary. Only of `id` match.

CPython implementation details:
https://github.com/python/cpython/blob/642eb8df951f2f1d4bf4d93ee568707c5bf40a96/Objects/listobject.c#L452

### Failure case: set
It gets worse: inconsistent behaviour in set.

```python
param = torch.zeros(5)
param2 = torch.zeros(5, 10)

tensor_list = set({param2})
print(param in tensor_list)   # False, as we never had to go to equality check, due to first hashing on other items
```

Note that whether we run into the broadcasting error behaviour is entirely dependent on the hashing function chosen by set. This is entirely non-deterministic and unpleasant.

CPython implementation details:
Ultimately checks equality of object just like list
https://github.com/python/cpython/blob/642eb8df951f2f1d4bf4d93ee568707c5bf40a96/Objects/setobject.c#L88

### Solution
Tensor `__contains__` behaviour ought to depend on ID match, and have nothing to do with values.

Ideally, python equality (RichEqualsBool) is not overloaded to the `torch.eq` operation. We can hopefully overload `operator.eq` without overloading `RichEqualsBool`.

The reason this is impossible is that CPython only shortcuts equality, but not inequality.

https://github.com/python/cpython/blob/642eb8df951f2f1d4bf4d93ee568707c5bf40a96/Objects/object.c#L847

Note that this issue is not unique to Pytorch, numpy has the same behaviour.

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by jon-chuang** [comment]
My preferred solution is to **stop overloading `Tensor.__eq__`**

**Comment by jon-chuang** [comment]
Old issue: https://github.com/pytorch/pytorch/issues/61303

**Comment by randolf-scholz** [comment]
Always wondered by equality is overloaded with element-wise equality. Likely for consistency, since most other operators act element-wise. However, one almost always wants `allclose` instead of `==` when comparing floats.

**Comment by ezyang** [comment]
We can't fix this because it would be BC breaking.
