### ISSUE TITLE
DISABLED test_vmapjvpall_linalg_det_singular_cpu_float32 (__main__.TestOperatorsCPU)

### ISSUE THREAD

**Issue by izaitsevfb** [pytorch/pytorch#111583]
Platforms: macos

This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/functorch%2Ftest_ops.py%3A%3ATestOperatorsCPU%3A%3Atest_vmapjvpall_linalg_det_singular_cpu_float32)).

cc @malfet @albanD

**Comment by Flamefire** [comment]
Possibly related: https://github.com/pytorch/pytorch/issues/110980

Seeing this test failing on the same Linux x86 machines where test_jvp_linalg_det_singular_cpu_float32 also fails
