### ISSUE TITLE
copy.deepcopy returns tensor with version=1

### ISSUE THREAD

**Issue by tugsbayasgalan** [pytorch/pytorch#111503]
### 🐛 Describe the bug

```
        class MyModel(torch.nn.Module):
            def __init__(self):
                super().__init__()
                self.register_buffer("buf", torch.zeros(1))
                self.w1 = torch.nn.Parameter(torch.zeros(1))
                self.w2 = torch.nn.Parameter(torch.zeros(1))

            def forward(self, x):
                self.buf.add_(1)
                return (self.w1*x*self.w2).sum() + self.buf.sum()

        model_for_eager = MyModel()
        model_for_compile = copy.deepcopy(model_for_eager)

        eager_version_counters = [buffer._version for _, buffer in model_for_eager.named_buffers()]
        compile_version_counters = [buffer._version for _, buffer in model_for_compile.named_buffers()]
        print(eager_version_counters, compile_version_counters)
```
Above snippet prints [0] and [1]. I think both of them should be [0]. 

### Versions

main 

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by bdhirsh** [comment]
hmm @soulitzer + @albanD, do you think this is (a) harmless and not worth fixing, (b) something we should fix, (c) considered BC-breaking to fix so we should leave it alone?

**Comment by soulitzer** [comment]
> hmm @soulitzer + @albanD, do you think this is (a) harmless and not worth fixing, (b) something we should fix, (c) considered BC-breaking to fix so we should leave it alone?

The returned version counter is always 1 instead of 0 because we do a new_empty + set_. Immediately doing some kind of inplace to initialize the tensor is a pretty common pattern, and things tend to only care how a version counter changes, rather than its absolute value, so it seems quite harmless to me.

@tugsbayasgalan do you have more context on how you ran into this issue?

**Comment by tugsbayasgalan** [comment]
Oh i was just trying to check some torch.compile behaviour by checking if the version counter is the same as eager result. But right off the bat, I noticed they were different even before calling torch.compile. This is not really a blocking for me.

**Comment by albanD** [comment]
In general, the absolute value of version counter should not be relied on. Only equality or not.

Also torch.compile is very likely to replace `add_(1).add_(1)` into a fused kernel that does a single inplace. So I don't expect the absolute value of the version counter to be preserved, only the "equalness".

**Comment by zou3519** [comment]
Sorry, wrong button
