### ISSUE TITLE
Prolonged network hiccup preventing retrieval of workflow job id

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#111577]
Please see https://github.com/pytorch/pytorch/pull/111483 for context

First known bad is https://hud.pytorch.org/pytorch/pytorch/commit/e0b035c220a4db2a15b53848cd16ac6416fcf323
Got fixed in https://hud.pytorch.org/pytorch/pytorch/commit/543dc757463aa0ad559c49337c98eece6a25150f?

~How is it that the second I notice it happening it gets fixed... Some quantum observation thing going on here...~

cc @ZainRizvi @kit1980 @huydhn

**Comment by huydhn** [comment]
This has been fixed a while ago, so we can close it now
