### ISSUE TITLE
[RFC] Add GradScaler on CPU

### ISSUE THREAD

**Issue by CaoE** [pytorch/pytorch#111559]
### 🚀 The feature, motivation and pitch

To enable FP16 support on CPU https://github.com/pytorch/pytorch/issues/97068, GradScaler is necessary for FP16 training to prevent grad overflows.

### Alternatives

* Step1: Add the corresponding kernels of `_amp_foreach_non_finite_check_and_unscale_` and `_amp_update_scale_kernels` on CPU
Follow the implementations of CUDA.
* Step2: Frontend API for GradScaler on CPU:
 1: Move the common logic codes of GradScaler to a file `torch/amp/grad_scaler.py`. Most parts of GradScaler can be abstracted as a base class since the algorithm of GradScaler is same on CPU and CUDA.  
 2: Add 2 derived class for CPU and CUDA to set device related config.
The design of Frontend API for GradScaler  is same as autocast.

* API usage:

```Python
# Creates a GradScaler once at the beginning of training.

# Before: only available on CUDA
# scaler = torch.cuda.amp.GradScaler()

# After: available on CUDA and CPU
# scaler = torch.cuda.amp.GradScaler()
# you can also use torch.amp.GradScaler with device setting
# scaler = torch.amp.GradScaler("cpu")
scaler = torch.cpu.amp.GradScaler()

for epoch in epochs:
    for input, target in data:
        optimizer.zero_grad()
        with torch.amp.autocast(device="cpu", enabled=True, dtype=dtype):
            output = model(input)
            loss = loss_fn(output, target)

        # Scales loss.  Calls backward() on scaled loss to create scaled gradients.
        scaler.scale(loss).backward()

        # scaler.step() first unscales gradients of the optimizer's params.
        # If gradients don't contain infs/NaNs, optimizer.step() is then called,
        # otherwise, optimizer.step() is skipped.
        scaler.step(optimizer)

        # Updates the scale for next iteration.
        scaler.update()
```

### Additional context

Related PRs：
https://github.com/pytorch/pytorch/pull/109281
https://github.com/pytorch/pytorch/pull/109993
https://github.com/pytorch/pytorch/pull/109994

This RFC depends on FP16 supports for operators https://github.com/pytorch/pytorch/issues/97068 and FP16 support of autocast on CPU https://github.com/pytorch/pytorch/issues/96093

**Comment by zeke-john** [comment]
Any update?

**Comment by CaoE** [comment]
@zeke-john https://github.com/pytorch/pytorch/pull/109281 https://github.com/pytorch/pytorch/pull/109993 https://github.com/pytorch/pytorch/pull/109994 have been merged.
