### ISSUE TITLE
[dynamo] Implement `set.__contains__` for tensors based on object identity

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#111556]
### 🚀 The feature, motivation and pitch

Workaround to https://github.com/pytorch/pytorch/issues/111544 for `set.__contains__` case

### Additional context

Related https://github.com/pytorch/pytorch/issues/111550

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by ezyang** [comment]
This one can just rely on the preexisting Tensor disjointness guards that are implicitly created
