### ISSUE TITLE
XLA Tensor creation fails on functionalization inside dynamo.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#111506]
### 🐛 Describe the bug

Minimal reproducible program:

```python
import torch
import torch_xla.core.xla_model as xm

device = xm.xla_device()

def foo():
    return torch.tensor([0.0], device=device)

compiled = torch.compile(backend="openxla")(foo)
tensor = compiled()
```

```python
  File "torch/_subclasses/functional_tensor.py", line 304, in __torch_dispatch__
    return return_and_correct_aliasing(func, args, kwargs, outs_wrapped)
  File "torch/utils/_python_dispatch.py", line 364, in return_and_correct_aliasing
    _correct_storage_aliasing(func, schema_info, args, (out,) if not isinstance(out, tuple) else out)
  File "torch/utils/_python_dispatch.py", line 251, in _correct_storage_aliasing
    alias_non_inplace_storage(args[arg_idx], outs[return_idx])
  File "torch/utils/_python_dispatch.py", line 234, in alias_non_inplace_storage
    torch.ops.aten.set_.source_Storage_storage_offset(ret, arg.untyped_storage(), ret.storage_offset(), ret.shape)
  File "torch/_ops.py", line 499, in __call__
    return self._op(*args, **kwargs or {})
torch._dynamo.exc.BackendCompilerFailed: backend='openxla' raised:
RuntimeError: Attempted to set the storage of a tensor on device "xla:0" to a storage on different device "lazy:0".  This is no longer allowed; the devices must match.

While executing %tensor : [num_users=1] = call_function[target=torch.tensor](args = ([0.0],), kwargs = {device: xla:0})
Original traceback:
  File "examples/bug-device.py", line 7, in foo
    return torch.tensor([0.0], device=device)
```

### Versions

PyTorch version: 2bf3ca1be759460cf9fbf011d96d3246001361e9 (Oct 4)
PyTorch/XLA version: c9a132484fb89bfdc9c602ada7bd8a3cec0db1aa (Oct 3)

cc @bdhirsh @ezyang

**Comment by ysiraichi** [comment]
I have investigated this problem a bit, and it seems that the items below aren't playing well together:

- `FunctionalTensorMode.__torch_dispatch__`
- `internal_new_from_data` at _torch/csrc/utils/tensor_new.cpp_

**Problem:** `internal_new_from_data` calls `tensor.to(device, ...)` while disabling the `Functionalize` dispatch key. Then, it enables that dispatch key and calls `lift_fresh`, which is captured by `FunctionalTensorMode`

- `tensor.to(device, ...)` returns an unlifted tensor: `tensor(..., device="xla:0", storage_device="lazy:0")`
- `lift_fresh(tensor)` returns the correctly lifted tensor: `tensor(..., device="xla:0", storage_device="xla:0")`
-  `FunctionalTensorMode.__torch_dispatch__` follows by calling `return_and_correct_aliasing`
    - It tries to set the storage of `tensor` (unlifted) to the storage of the result of `lift_fresh` (lifted)
    - Fails, since the their storage device differ

**Possible Solution:** add `lift_fresh` condition [here](https://github.com/pytorch/pytorch/blob/a771fde8b1c62ecf4875c77609a9fa4587084532/torch/_subclasses/functional_tensor.py#L309-L313), making it not call `return_and_correct_aliasing`

- While this works, question is whether it's correct
- That's because the unlifted tensor and the lifted one should, in theory, alias

**Comment by bdhirsh** [comment]
@ysiraichi hmm, do you know why we end up with the storage_device being `lazy:0`, instead of `xla:0`? Would it be possible to fix that?

If we can't then I think your fix sounds reasonable. The only catch is that we would need to make sure to wrap the result of `lift_fresh` into a `FunctionalTensor()`. One invariant that `FunctionalTensorMode` needs to maintain is that whenever the output of an op is a C++ `FunctionalTensorWrapper`, that result must always get wrapped in a `FunctionalTensor`.

**Comment by ysiraichi** [comment]
> do you know why we end up with the storage_device being `lazy:0`, instead of `xla:0`? Would it be possible to fix that?

AFAIU, that's due to this [`backendDeviceToAtenDevice` call](https://github.com/pytorch/xla/blob/bccbb5aaff0b998ea6a4959ba203340b68584275/torch_xla/csrc/tensor.cpp#L144) in the XLA tensor constructor. Replacing that with [the `XlaDeviceToAtenDevice` function](https://github.com/pytorch/xla/blob/bccbb5aaff0b998ea6a4959ba203340b68584275/torch_xla/csrc/aten_xla_bridge.cpp#L328) does fix this particular issue. However, we end up failing [this assertion](https://github.com/pytorch/pytorch/blob/2a40b7efcb273d1689b55763fade49263adcc788/aten/src/ATen/native/TensorShape.cpp#L416), since the storage of XLA tensors are not resizable.

The solution I proposed does not have this issue, since we are skipping the `return_and_correct_aliasing` function call altogether.

> The only catch is that we would need to make sure to wrap the result of `lift_fresh` into a `FunctionalTensor()`

Doesn't `lift_fresh` do that already? Isn't that its semantics?

-----

I do have one question, though: is my solution correct? Wouldn't skipping `return_and_correct_aliasing` make it so we miss the alias relation between the argument and return value of `lift_fresh`?

**Comment by ysiraichi** [comment]
Maybe, one way out of this is to modify the unlifted tensor storage from `lazy:0` to `xla:0` as you suggested before. However, in order to make it work, we would need 2 changes:

- In PyTorch/XLA: as [I described previously](https://github.com/pytorch/pytorch/issues/111506#issuecomment-1771514243), we have to replace [`backendDeviceToAtenDevice` call](https://github.com/pytorch/xla/blob/bccbb5aaff0b998ea6a4959ba203340b68584275/torch_xla/csrc/tensor.cpp#L144) with [`XlaDeviceToAtenDevice`](https://github.com/pytorch/xla/blob/bccbb5aaff0b998ea6a4959ba203340b68584275/torch_xla/csrc/aten_xla_bridge.cpp#L328). As far as I can see, there shouldn't be a problem doing that. This line was introduced in [this PR](https://github.com/pytorch/xla/pull/3966) for supporting `Tensor.is_alias_of`. So, I believe this change shouldn't be a problem. What do you think, @JackCaoG?
- In PyTorch core: change [this assertion](https://github.com/pytorch/pytorch/blob/2a40b7efcb273d1689b55763fade49263adcc788/aten/src/ATen/native/TensorShape.cpp#L416) to a something similar to the code below. Not sure this works, though. The idea being that if `result.sym_numel() != 0` and `result.storage().nbytes() == 0`, then we are working with fake storages. Given that, we should be able to just replace the storage of `result` to indicate aliasing relations (maybe this is too strong to guarantee!?). What do you think, @bdhirsh?

```c++
  // Remember result's storage before replacing it.
+ auto old_storage_nbytes = result.storage().nbytes();
  ...
  if (result.sym_numel() != 0) {
    TORCH_INTERNAL_ASSERT(storage);
-   TORCH_CHECK(storage.resizable(), "Trying to resize storage that is not resizable");
+   TORCH_CHECK(storage.resizable() || (old_storage_nbytes == 0 && storage.nbytes() == 0), "Trying to resize a non-zero storage that is not resizable")
+   if (storage.resizable()) {
      const auto itemsize = result.dtype().itemsize();
      c10::SymInt size_bytes = at::detail::computeStorageNbytes(
          size, stride, itemsize, std::move(storage_offset));
      storage.set_nbytes(std::move(size_bytes));
+   }
  }
```

**Comment by JackCaoG** [comment]
replace [backendDeviceToAtenDevice](https://github.com/pytorch/xla/blob/bccbb5aaff0b998ea6a4959ba203340b68584275/torch_xla/csrc/tensor.cpp#L144) to [XlaDeviceToAtenDevice](https://github.com/pytorch/xla/blob/bccbb5aaff0b998ea6a4959ba203340b68584275/torch_xla/csrc/aten_xla_bridge.cpp#L328) sgtm. I do expect all device in XLATensor constructor to be xla devices.

**Comment by ezyang** [comment]
Can you provide the full backtrace of the assertion failure (that storage is not resizable)

**Comment by ysiraichi** [comment]
Sure. Here it is! As far as I understand, we hit this error because the storage of XLA tensors are set not to be resizable at its creation. Specifically, this happens when we try to set the lifted (`lift_fresh` result) XLA tensor storage to the unlifted XLA tensor storage (input to `lift_fresh`) in order to keep aliasing relations.

<details>
<summary>Raw Error Output</summary>

```
cpu  eval  pyhpc_isoneutral_mixing
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "benchmarks/dynamo/common.py", line 2462, in warmup
    fn(model, example_inputs)
  File "torch/_dynamo/eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 549, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "torch/_dynamo/convert_frame.py", line 635, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "torch/_dynamo/convert_frame.py", line 141, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    return _compile(
  File "torch/_dynamo/convert_frame.py", line 562, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "torch/_dynamo/utils.py", line 199, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 484, in compile_inner
    out_code = transform_code_object(code, transform)
  File "torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "torch/_dynamo/convert_frame.py", line 454, in transform
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 2103, in run
    super().run()
  File "torch/_dynamo/symbolic_convert.py", line 743, in run
    and self.step()
  File "torch/_dynamo/symbolic_convert.py", line 706, in step
    getattr(self, inst.opname)(inst)
  File "torch/_dynamo/symbolic_convert.py", line 2213, in RETURN_VALUE
    self.output.compile_subgraph(
  File "torch/_dynamo/output_graph.py", line 885, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/ysiraichi/micromamba/envs/xla0/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "torch/_dynamo/output_graph.py", line 987, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "torch/_dynamo/utils.py", line 199, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/output_graph.py", line 1054, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "torch/_dynamo/output_graph.py", line 1039, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3907, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "torch/_dynamo/utils.py", line 199, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3395, in create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "torch/_functorch/aot_autograd.py", line 776, in inner
    flat_f_outs = f(*flat_f_args)
  File "torch/_functorch/aot_autograd.py", line 3512, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "torch/fx/interpreter.py", line 267, in call_function
    return target(*args, **kwargs)
  File "torch/_subclasses/functional_tensor.py", line 303, in __torch_dispatch__
    return return_and_correct_aliasing(func, args, kwargs, outs_wrapped)
  File "torch/utils/_python_dispatch.py", line 347, in return_and_correct_aliasing
    _correct_storage_aliasing(func, schema_info, args, (out,) if not isinstance(out, tuple) else out)
  File "torch/utils/_python_dispatch.py", line 234, in _correct_storage_aliasing
    alias_non_inplace_storage(args[arg_idx], outs[return_idx])
  File "torch/utils/_python_dispatch.py", line 221, in alias_non_inplace_storage
    torch.ops.aten.set_.source_Storage_storage_offset(ret, arg.untyped_storage(), ret.storage_offset(), ret.shape)
  File "torch/_ops.py", line 499, in __call__
    return self._op(*args, **kwargs or {})
torch._dynamo.exc.BackendCompilerFailed: backend='compiler_fn' raised:
RuntimeError: Trying to resize storage that is not resizable

While executing %tensor : [num_users=1] = call_function[target=torch.tensor](args = ([0.0],), kwargs = {device: xla:0})
Original traceback:
  File "benchmarks/dynamo/torchbench.py", line 508, in forward_pass
    return mod(*inputs)
  File "torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "torchbenchmark/models/pyhpc_isoneutral_mixing/__init__.py", line 96, in forward
    return isoneutral_pytorch.isoneutral_diffusion_pre(
  File "torchbenchmark/models/pyhpc_isoneutral_mixing/isoneutral_pytorch.py", line 153, in isoneutral_diffusion_pre
    torch.min(drodze, torch.tensor([0.0], device=device)) - epsln


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

</details>

**Comment by ezyang** [comment]
`set_.source_Storage_storage_offset` shouldn't trigger this error. We're not actually resizing the storage here. See if you can remove this test / make it more accurate for this case. (This would not be the first time; for example set_ increments version counter even though it doesn't actually modify data.)

**Comment by ysiraichi** [comment]
On second thoughts, is setting the storage of a lifted tensor (1) to the storage of an unlifted tensor (2) the correct thing to do? I mean: `lifted.set_(unlifted.typed_storage())` will return a `FunctionalTensorWrapper` lifted tensor with a plain `StorageImpl` as storage, instead of `FunctionalStorageImpl`.

**Comment by ezyang** [comment]
You indeed shouldn't do this

**Comment by ysiraichi** [comment]
Hmm. So, I guess, the correct thing to do here would be to skip `return_and_correct_aliasing` function when executing `lift_fresh`. What do you think? @bdhirsh @ezyang

**Comment by ezyang** [comment]
hmm, but shouldn't the argument to lift_fresh be a FunctionalTensorWrapper? In which case it would be ok to call return_and_correct_aliasing. What are you observing happening?

**Comment by ysiraichi** [comment]
> but shouldn't the argument to lift_fresh be a FunctionalTensorWrapper?

I don't know, should it? Isn't that's what `lift_fresh` supposedly does? i.e. it turns an unlifted tensor (argument) into a lifted tensor (output).

> What are you observing happening?

I'm observing `lift_fresh` being called with an unlifted (XLA) tensor as argument (because of how `internal_new_from_data` is implemented -- read more [here](https://github.com/pytorch/pytorch/issues/111506#issuecomment-1769330475)). Its output, however, is a `FunctionalTensorWrapper`.

**Comment by ezyang** [comment]
Oh you know what, you're right. OK, I think your proposed solution is good.

**Comment by ysiraichi** [comment]
@JackCaoG Since we are going to skip `return_and_correct_aliasing` for `lift_fresh`, we don't need to apply [this change](https://github.com/pytorch/pytorch/issues/111506#issuecomment-1773525184) anymore. Question: do we still want the change?

**Comment by JackCaoG** [comment]
yea I think we can still take it, if you open a pr I will get someone to review it.
