### ISSUE TITLE
Status Tracker And Summary of Support Needed: Make Dynamo Generated Artifacts Debuggable

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#111633]
Currently, dynamically translated bytecode from Dynamo can only be run as a black box. With the help of recent tools like https://github.com/thuml/depyf , it is possible to decompile bytecode into source code, and to enable debugging tools to debug those generated bytecodes.

This issue (status tracker) ducoments the progress and support needed from PyTorch side to fulfill the goal.

# General idea:

PyTorch generate bytecode (and many other artifacts) dynamically. We can decompile and dump the source code into files, let users set breakpoints, and re-run the program to hit those breakpoints.

# Main difficulty:

In essence, artifacts (transformed bytecode, compiled functions, etc.) are generated **dynamically**. We need to have a stable naming for each artifact so that users can recognize them and reuse them across runs.

# Some minor concerns:

Some function names in Dynamo are not valid (notoriously, the resume functions have `<resume in xxx>` name). We need to assign valid names for them.

# Example usage:

The main usage come from the `depyf` side. The rough idea is to set up a src directory, and dump src there for debugging.

```diff
+ import depyf
+ # set up a hook to dump src of dynamically generated artifacts
+ depyf.enable_torch_compile_debugging(dump_dir="/path/to/dumped/src")
def toy_example(a, b):
    x = a / (torch.abs(a) + 1)
    if b.sum() < 0:
        b = b * -1
    return x * b

for _ in range(100):
    toy_example(torch.randn(10), torch.randn(10))
```

The ideal result looks like this:

![image](https://github.com/pytorch/pytorch/assets/23236638/8f586170-7745-4cf6-9950-2d16fe831a46)

```[tasklist]
### Tasks
- [x] make code name of resume functions valid, finished in https://github.com/pytorch/pytorch/pull/111635 .
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by youkaichao** [comment]
cc @jansel @ezyang

**Comment by youkaichao** [comment]
I finished the debugging of transformed bytecode now. It only requires running the program once. Please see https://github.com/thuml/depyf#debug-torchcompile-with-your-favorite-debugger for details.

To support debugging resume functions and compiled subgraph functions, I will need to have hooks for them, too.

**Comment by youkaichao** [comment]
I need to disable one debug check: 

https://github.com/pytorch/pytorch/blob/57c7aa12dbf71617bd21fe7e076df8e823b5b7bb/torch/csrc/dynamo/eval_frame.c#L794

This debug check is not necessary. For resume functions, the `nlocals` is unnecessarily large.

Let's use the typical toy example:

```python
import torch

@torch.compile(backend="eager")
def toy_example(a, b):
    x = a / (torch.abs(a) + 1)
    if b.sum() < 0:
        b = b * -1
    return x * b

for _ in range(100):
    toy_example(torch.randn(10), torch.randn(10))
```

For example, resume functions have 3 local variables `('b', 'x', 'a')`, but the bytecode only uses two: `('b', 'x')`.

cc @jansel @ezyang

**Comment by youkaichao** [comment]
There is an inherent limitation for debugging: when the compiled code calls `resume` functions, that `resume` functions need to be processed by Dynamo's frame eval callbacks, but some debuggers take over the frame eval callback, so code cache are not respected.

I tested it with [debugpy](https://github.com/microsoft/debugpy/) and met the problem. Not sure how other debuggers work.

```python
def compiled_code(a, b):
    __temp_1 = __compiled_fn_0(a, b)
    x = __temp_1[0]
    if __temp_1[1]:
        # Dynamo will call compiled code for __resume_at_30_1 , but debugpy directly run the bytecode
        return __resume_at_30_1(b, x)
    return __resume_at_38_2(b, x)
```

**Comment by jansel** [comment]
I think having this as an option in depyf could be useful to some people, and sounds like it already works.  I don't think we can turn this on by default though due to the reasons mentioned here https://github.com/pytorch/pytorch/pull/111472#pullrequestreview-1688299312

One question I wonder is won't people expect to see the original source code in the debugger, not the decompiled bytecode?   My guess is it would depend on what someone is trying to do.  If someone is debugging dynamo, then decompiled makes more sense.  If someone is debugging their program, then user source code might be more useful.

**Comment by youkaichao** [comment]
> I think having this as an option in depyf could be useful to some people

Which one do you refer to?

**Comment by jansel** [comment]
> Which one do you refer to?

depyf.enable_torch_compile_debugging

**Comment by youkaichao** [comment]
The current usage looks like this:

```python
import depyf
with depyf.prepare_debug(toy_example, "./dump_src_dir"):
    for _ in range(100):
        toy_example(torch.randn(10), torch.randn(10))

with depyf.debug():
    toy_example(torch.randn(10), torch.randn(10))
```

We don't turn this on by default.

**Comment by youkaichao** [comment]
I'm surprised how little support it requires from PyTorch to achieve debugging. Now I have finished a basic version at https://github.com/thuml/depyf#debug-torchcompile-with-your-favorite-debugger . It supports debugging compiled function / resume function / compiled subgraph.

Note that currently the dumped src has ugly hash value in the file name. This is because we can only replace modified bytecode by hooks at the Dynamo compilation time, and at that time we don't know the number `code_cache_{n}`. If we can have a `setter` function for the `code` attribute:

https://github.com/pytorch/pytorch/blob/2b2b6caf8f4da5599841678967202fb9443c56e5/torch/csrc/dynamo/eval_frame.c#L337

Then we can replace modified bytecode at any time we like, and we can avoid ugly dumped src.

Is it good to **have a `setter` function for the `code` attribute**? @jansel @ezyang

**Comment by jansel** [comment]
I think you could just do:
```
code_counters = collections.Counter()
...
def bytecode_hook(old_code, new_code):
   n = code_counters[old_code]
   code_counters[old_code] += 1
   ...
```

**Comment by youkaichao** [comment]
> code_counters = collections.Counter()

That's a good idea, but might run into problems if we are doing some multi-thread or multi-processing stuff? I'm not sure though.

**Comment by jansel** [comment]
There is a lock around the tracing part of torch.compile, so only one thread can call the hook at the same time.

**Comment by youkaichao** [comment]
Ran into another problem: I want the dumped src to be `{function name}_compiled_code_{n}`, but all resume functions in one function have the same `co_name`. I might use a global counter then...

**Comment by jansel** [comment]
Can't you just change the name in the bytecode_hook?

**Comment by youkaichao** [comment]
> Can't you just change the name in the bytecode_hook?

Yes, just did it.

**Comment by youkaichao** [comment]
I'm glad to announce that the debugging functionality seems to work perfectly now, at least for the `toy_example`. I'm surprised how little support it requires from PyTorch to achieve debugging.

cc @jansel @ezyang

**Comment by youkaichao** [comment]
Do we need to announce this elsewhere? I'm pretty sure many Dynamo users would love it.

**Comment by jansel** [comment]
Great!  dev-discuss.pytorch.org might make the most sense.  You can also tag the PR with "release notes: dynamo", to be included in the release node collection process for PyTorch 2.2.

**Comment by youkaichao** [comment]
> Great! dev-discuss.pytorch.org might make the most sense.

Sure, will do.



> You can also tag the PR with "release notes: dynamo", to be included in the release node collection process for PyTorch 2.2.

Which PR do you mean? Most of the job is done in https://github.com/thuml/depyf , no PR in PyTorch for this functionality though. Maybe we can add a documentation/tutorial page for this?

**Comment by youkaichao** [comment]
Currently the debugging works for PyTorch nightly. The major support from PyTorch, on top of PyTorch 2.1, is the bytecode hook support https://github.com/pytorch/pytorch/pull/110714 . If we can get that support into PyTorch 2.1.1 at https://github.com/pytorch/pytorch/issues/110961 , then we can benefit users sooner.

cc @jansel @ezyang

**Comment by jansel** [comment]
2.1.1 is for bugfixes only, not new features.  2.2 makes the most sens.

**Comment by youkaichao** [comment]
How about https://github.com/pytorch/pytorch/issues/111633#issuecomment-1774076606 ? Is it ok to have a PR to remove that `DEBUG_CHECK`?

**Comment by jansel** [comment]
I think it is fine to remove that.

**Comment by youkaichao** [comment]
As the debugging functionality has been completed, I will close this issue.
