### ISSUE TITLE
can not use "import torch.nn.LayerNorm as Norm"

### ISSUE THREAD

**Issue by JoyceMind** [pytorch/pytorch#111655]
### 🐛 Describe the bug

Why can't I import when I want to invoke LayerNorm with the "import torch.nn.LayerNorm as Norm" statement.
![image](https://github.com/pytorch/pytorch/assets/108966996/542d592f-a0de-4b65-985a-b9f92afc950d)

### Versions

2.1.0

**Comment by kit1980** [comment]
torch.nn.LayerNorm is not a Python module.

Use `from torch.nn import LayerNorm as Norm`.
