### ISSUE TITLE
Foreach optimizers don't work with torch.set_default_dtype(torch.float64)

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#111671]
```python
import torch

torch.set_default_dtype(torch.float64)
device = "cuda"
model = torch.nn.Linear(200, 1, bias=True).to(device)
opt = torch.optim.Adam(model.parameters(),lr=0.001) 
x = torch.rand(1, 200).to(device)
model(x).sum().backward()
opt.step()
```
Error:
```
RuntimeError: Tensors of the same index must be on the same device and the same dtype except `step` tensors that can be CPU and float32 notwithstanding
```
Foreach is implicitly True because we are using cuda. Error goes away if we explicitly set foreach=False.

Versions: main

(originally reported [here](https://discuss.pytorch.org/t/tensors-of-the-same-index-must-be-on-the-same-device-and-the-same-dtype-except-step-tensors-that-can-be-cpu-and-float32-notwithstanding/190335/2))

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by jon-chuang** [comment]
Duplicate: https://github.com/pytorch/pytorch/issues/110940. Please refer to the other issue. (will try to push the fix soon)

**Comment by DavidVelazco26** [comment]
Hello, I'm having the same problem, Does someone know to fix 
RuntimeError: Tensors of the same index must be on the same device and the same dtype except `step` tensors that can be CPU and float32 notwithstanding?

**Comment by jon-chuang** [comment]
Yes, you have to change the default type to float32.

**Comment by richardk53** [comment]
> Yes, you have to change the default type to float32.

That is not a fix though :D

**Comment by jon-chuang** [comment]
It has been fixed on main.
