### ISSUE TITLE
DISABLED test_sigmoid (__main__.TestQuantizedOps)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#111692]
Platforms: mac, macos

This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/test_quantization.py%3A%3ATestQuantizedOps%3A%3Atest_sigmoid)).

This test is failing on MacOS x86 https://hud.pytorch.org/pytorch/pytorch/commit/ca7d084ff9b67675cfff0d175ea6b96fcedc4950

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @malfet @albanD

**Comment by andrewor14** [comment]
This seems related: https://github.com/pytorch/pytorch/issues/107030
