### ISSUE TITLE
[dynamo] higher-order ops do not preserve `FakeTensor` for in-place ops

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#111649]
### 🐛 Describe the bug

```python
def fn(z):
    x = z.clone()
    y = torch.vmap(torch.Tensor.acos_)(x)
    # y's fake tensor is not x's fake tensor in terms of pyobjects
    return y is x

fn_opt = torch.compile(backend="eager", fullgraph=True, dynamic=True)(fn)

z = torch.ones(4, 1)

self.assertEqual(fn(z), fn_opt(z))
```

### Solution
Not sure if this is a bug. But ideally, we should not expect x's fake tensor to be different from y's, as then it can be a method to preserve object identity throughout recursive calls to FX.

One possible way to do this might be to reuse the FakeTensor from the inputs when doing fx tracing for higher order ops.
 
However, if it is unavoidable (e.g. as a result of fx tracing requirements), another solution is simply to propagate the storage of the original fake tensor to the higher order op fake tensor.

### Versions

main

cc @eellison @zou3519 @Chillee @samdow @kshitij12345 @janeyx99 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by lezcano** [comment]
cc @zou3519
