### ISSUE TITLE
Can't export a pth model to onnx (RuntimeError: Couldn't lower all tuples)

### ISSUE THREAD

**Issue by MarouaneMja** [pytorch/pytorch#111641]
### 🐛 Describe the bug

Hello everyone, I am trying to convert a pytorch model to onnx using the library onnx in torch. The model architecture and weights are in the repository https://github.com/Sense-X/Co-DETR , I am usign the model CO-Dino with a Swin-L backbone, however when I launch the model exportation I encounter this error ```RuntimeError: Couldn't lower all tuples```.

![image](https://github.com/pytorch/pytorch/assets/59453891/62666dfd-e2ff-4ef1-a674-54e8f9ef70ea)

PS: Sorry, I can't copy poste a simple python code to reproduce the problem. 

### Versions

[pip3] numpy==1.24.3
[pip3] onnx==1.14.1
[pip3] onnxruntime==1.8.1
[pip3] onnxruntime-gpu==1.8.1
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.24.3           py38h14f4228_0  
[conda] numpy-base                1.24.3           py38h31eccc5_0  
[conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.11.0               py38_cu113    pytorch
[conda] torchvision               0.12.0               py38_cu113    pytorch

**Comment by thiagocrepaldi** [comment]
Please provide a full repro script

**Comment by shubhambhokare1** [comment]
Hi @MarouaneMja 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team

**Comment by Mohit-robo** [comment]
I encountered the same error, it was due to `DataParallel`. Simply changing `model` to `model.module` worked for me
