### ISSUE TITLE
Implementation of Lion Optimizer.

### ISSUE THREAD

**Issue by RahulVadhyar** [pytorch/pytorch#111736]
### 🚀 The feature, motivation and pitch

Lion Optimizer is becoming a great alterative to AdamW and Adam Optimizer. It is more efficient as it does not use second order moments and instead uses sign operations in order to update the weights. This saves on memory and decreases training time. In  some cases it is better than Adam and AdamW as given in the paper.
The original paper for this is : https://arxiv.org/pdf/2302.06675.pdf

The RFCS PR for this is: https://github.com/pytorch/rfcs/pull/60

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by albanD** [comment]
Hey!
I think this is already being discussed in https://github.com/pytorch/pytorch/issues/94904 let's move discussion about this one there.
