### ISSUE TITLE
Not Implemented Issue

### ISSUE THREAD

**Issue by Tanvik-VP** [pytorch/pytorch#111728]
### 🚀 The feature, motivation and pitch

NotImplementedError: The operator 'aten::_unique2' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

### Alternatives

Please add this

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Implementation for Unique has been added in https://github.com/pytorch/pytorch/pull/88532 please udpate your PyTorch version and try again. If it still does not work, please do not hesitate to create a new issue (but specify PyTorch version you are testing against)
