### ISSUE TITLE
Add regex matching to Inductor all2all collective unit tests

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#111776]
As part of https://github.com/pytorch/pytorch/pull/110195, we added support for tracing and compiling all2all collectives, specifically passing in a list of integers for `input_split_sizes` / `output_split_sizes` args in `torch.ops.c10d_functional.all_to_all_single()`. And we expect that in the Inductor generated code, we are passing symints like `i0`, `i1` to the `input_split_sizes` / `output_split_sizes` args of `all_to_all_single()`. Values of these symints are not hardcoded and instead are populated at runtime.

The above mechanism already works today. But current unit tests only check if "all_to_all_single" exists in the generated code:
```python
FileCheck() \
.check("all_to_all_single") \
.run(code)
```
while the actual generated code looks like:
```python
buf5_work = dist.all_to_all_single(buf5[0], buf5_inputs[0], output_split_sizes=[i14, i15], input_split_sizes=[i12, i13], group=buf5_pg, async_op=True)
```
(notice i14, i15, i12, i13 are the symints)

We want to update the unit test code to check that symints are indeed used in `output_split_sizes` and `input_split_sizes` args, to prevent functionality regression. We want to do something similar to:
```python
FileCheck() \
.check_regex("all_to_all_single(buf${buf_id}[0], buf${buf_id}_inputs[0], output_split_sizes=[i${symint_id_0}, i${symint_id_1}], input_split_sizes=[i${symint_id_2}, i${symint_id_3}], ") \
.run(code)
```
where the actual value of buf_id / symint_id_0 / symint_id_1 / symint_id_2 / symint_id_3 can be anything. We can likely achieve this via some sort of regular expression matching.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by dshi7** [comment]
let me try, thanks
