### ISSUE TITLE
Scalar parameter backward returns empty tensor size

### ISSUE THREAD

**Issue by dizcza** [pytorch/pytorch#11176]
## Issue description
I was going to implement some sophisticated loss function with a single scalar parameter. An [example](https://discuss.pytorch.org/t/is-scale-layer-available-in-pytorch/7954/6?u=dizcza) that worked well in pytorch v0.3.X now crashes because scalar tensors have empty size since v0.4.0.

## Code example
```
class ScaleFunc(torch.autograd.Function):

    @staticmethod
    def forward(ctx, input, scale):
        ctx.save_for_backward(input, scale)
        return input * scale

    @staticmethod
    def backward(ctx, grad_output):
        input, scale = ctx.saved_variables
        return grad_output * scale, torch.mean(grad_output * input)

class ScaleLayer(nn.Module):

    def __init__(self, init_value=1e-3):
        super().__init__()
        self.scale = nn.Parameter(torch.FloatTensor(1).fill_(init_value))

    def forward(self, input):
        return ScaleFunc.apply(input, self.scale)

scale_layer = ScaleLayer()
x = torch.randn(3,7)
y = scale_layer(x).mean()
y.backward()
```
```
Traceback (most recent call last):
  File "/home/dizcza/anaconda3/envs/embsdr_cpu/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-85-ab75bb780f4c>", line 1, in <module>
    y.backward()
  File "/home/dizcza/anaconda3/envs/embsdr_cpu/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/dizcza/anaconda3/envs/embsdr_cpu/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function ScaleFuncBackward returned an invalid gradient at index 1 - expected shape [1] but got []
```

- How you installed PyTorch: `conda install pytorch-cpu torchvision-cpu -c pytorch`
- PyTorch version: 0.4.1
- Python version: 3.6.6

**Comment by SsnL** [comment]
Yeah. Introduction of scalars unfortunately broke some existing code. But we believed that this is a necessary hit we needed to take, for the better and more sound tensor shape behavior, and avoiding unexpected behaviors for new users. The change was detailedly described in [our migration guide](https://pytorch.org/2018/04/22/0_4_0-migration-guide.html).

So, instead, you can do `self.scale = nn.Parameter(torch.full((), init_value))` and the code will run perfectly.

**Comment by krstp** [comment]
Any tip to a related issue? See comments at: https://github.com/pytorch/pytorch/issues/13404
