### ISSUE TITLE
An OOM where there should not be any OOM.

### ISSUE THREAD

**Issue by phalexo** [pytorch/pytorch#111729]
### 🐛 Describe the bug

I see similar type of errors being asked about in quite a few places, with advice given being usually useless. The suggestion below to muck around with an environment variable is similarly useless.

What is confounding to me is that memory allocation is tiny in comparison to still available space. Why is this happening?

 
Traceback (most recent call last):
  File "fine-tune.py", line 338, in <module>
    train()
  File "fine-tune.py", line 331, in train
    trainer.train()
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/transformers/trainer.py", line 1726, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/accelerate/accelerator.py", line 1280, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/accelerate/accelerator.py", line 1662, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 304, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1212, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1473, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 509, in __init__
    self.initialize_optimizer_states()
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 644, in initialize_optimizer_states
    self.optimizer.step()
  File "/home/developer/pytorch/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/developer/pytorch/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/developer/pytorch/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/developer/pytorch/torch/optim/adamw.py", line 171, in step
    adamw(
  File "/home/developer/pytorch/torch/optim/adamw.py", line 321, in adamw
    func(
  File "/home/developer/pytorch/torch/optim/adamw.py", line 564, in _multi_tensor_adamw
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 134.00 MiB (GPU 0; 11.93 GiB total capacity; 4.48 GiB already allocated; 6.69 GiB free; 4.77 GiB allowed; 4.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Versions

UBuntu 20.04
Python 3.8
Anaconda environment
Inside a docker

**Comment by malfet** [comment]
@phalexo issue as it is reported right now lacks some important information such as PyTorch version, GPU that you are using, etc (which can be easily obtained by running `python3 -m torch.utils.collect_env`. Also, if you've asked this question elsewhere, would be useful to have links to such discussion

**Comment by malfet** [comment]
Adding to triage review to discuss the need of "needs details" labels (or perhaps close such issues and encourage users to file a new one with the info needed).

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

**Comment by phalexo** [comment]
That's a bit lazy, isn't it? Either your allocation has a bug or your
reporting has a bug. The allocator is trying to allocate a few MiB when
gigabytes are available and claims it is out of memory.

You didn't bother reading anything, did you?

Also the suggestion in the error is useless, it doesn't do anything.

**Comment by phalexo** [comment]
And the moment I am at my laptop I will provide the info, I am in my car
now. That said, I followed the advice given in the error, on how to defrag
memory. It has zero effect. Maybe there is a bug in how the environment
variable is used.

I have looked around, and I as yet have not seen a single reasonable
explanation how this is supposed to work.

I set batch size to 1, cannot go any smaller than that.

**Comment by phalexo** [comment]
I have tried 0.1 to 0.5, the error persists only the numbers change. I also
flushed the cache. I don't have the code in front of me unfortunately.

**Comment by phalexo** [comment]
After the model weights get loaded 4.9GiB is used. The GPUs have 12.2GiB
each.

**Comment by albanD** [comment]
> I have tried 0.1 to 0.5, the error persists only the numbers change.

You should leave it to 1. if you are happy with the whole 12.2GB of the GPU being used by PyTorch.

In any case, looking forward to the repro.

**Comment by phalexo** [comment]
Collecting environment information...
PyTorch version: 2.0.0a0+git96ca226
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00)  [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX TITAN X
GPU 1: NVIDIA GeForce GTX TITAN X
GPU 2: NVIDIA GeForce GTX TITAN X
GPU 3: NVIDIA GeForce GTX TITAN X

Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn.so.8.7.0
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.7.0
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.7.0
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.7.0
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.7.0
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.7.0
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           62
Model name:                      Genuine Intel(R) CPU  @ 2.80GHz
Stepping:                        2
CPU MHz:                         3300.000
CPU max MHz:                     3300.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        5600.04
Virtualization:                  VT-x
L1d cache:                       512 KiB
L1i cache:                       512 KiB
L2 cache:                        4 MiB
L3 cache:                        50 MiB
NUMA node0 CPU(s):               0-7,16-23
NUMA node1 CPU(s):               8-15,24-31
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Unknown: No mitigations
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] torch==2.0.0a0+git96ca226
[pip3] torchaudio==2.0.1+cu118
[pip3] torchvision==0.15.1+cu118
[conda] magma-cuda118             2.6.1                         1    pytorch
[conda] mkl                       2023.2.0                 pypi_0    pypi
[conda] mkl-include               2023.2.0                 pypi_0    pypi
[conda] numpy                     1.24.4           py38h59b608b_0    conda-forge
[conda] torch                     2.0.0a0+git96ca226          pypi_0    pypi
[conda] torchaudio                2.0.1+cu118              pypi_0    pypi
[conda] torchvision               0.15.1+cu118             pypi_0    pypi

**Comment by phalexo** [comment]
This` is what I get when I set the process fraction to 1.0. I am happy to take any advice as to what I should set environment variables, and/or fractions, or any other variables.  The input dataset is a bunch of texts. I don't understand why Torch attempts to allocate 4GiB when I gave the entire VRAM to Torch. 

  File "/home/developer/pytorch/torch/nn/modules/module.py", line 1501, in _call_impl
    return _C._VariableFunctions.rsub(self, other)
    attention_mask = self._prepare_decoder_attention_mask(torch.cuda
.  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 818, in _prepare_decoder_attention_mask
OutOfMemoryError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 3; 11.93 GiB total capacity; 10.67 GiB already allocated; 515.38 MiB free; 11.93 GiB allowed; 10.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    expanded_attn_mask = _expand_mask(attention_mask, inputs_embeds.dtype, tgt_len=input_shape[-1]).to(
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 94, in _expand_mask
    return forward_call(*args, **kwargs)
    inverted_mask = 1.0 - expanded_mask  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward

  File "/home/developer/pytorch/torch/_tensor.py", line 40, in wrapped
    return f(*args, **kwargs)
  File "/home/developer/pytorch/torch/_tensor.py", line 848, in __rsub__
    output = old_forward(*args, **kwargs)
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 888, in forward
    return _C._VariableFunctions.rsub(self, other)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 2; 11.93 GiB total capacity; 10.67 GiB already allocated; 515.38 MiB free; 11.93 GiB allowed; 10.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    attention_mask = self._prepare_decoder_attention_mask(
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 818, in _prepare_decoder_attention_mask
    expanded_attn_mask = _expand_mask(attention_mask, inputs_embeds.dtype, tgt_len=input_shape[-1]).to(
  File "/home/developer/mambaforge/envs/FinGPT/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 94, in _expand_mask
    inverted_mask = 1.0 - expanded_mask
  File "/home/developer/pytorch/torch/_tensor.py", line 40, in wrapped
    return f(*args, **kwargs)
  File "/home/developer/pytorch/torch/_tensor.py", line 848, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 1; 11.93 GiB total capacity; 10.67 GiB already allocated; 515.38 MiB free; 11.93 GiB allowed; 10.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
