### ISSUE TITLE
[dynamo] `get_fake_value` doesn't always return fake values

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#111869]
### 🐛 Describe the bug

In particular, when you run `get_fake_value` on a `getattr_var`, it will return the real tensor. This has got to be wrong. If only because the function is named `get_fake_value`.

Related: https://github.com/pytorch/pytorch/pull/111864

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @eellison @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jon-chuang** [comment]
Well, the way that we currently use it, `get_fake_value` is not always responsible for wrapping raw tensor values, rather that is the task of `VariableBuilder.`

It seems that the previous code prior to https://github.com/pytorch/pytorch/pull/111864#issuecomment-1776266220 simply did not use `wrap_to_fake_tensor_and_record` accurately. 

Still, the fact that it is easy to make mistakes is not good.

**Comment by ezyang** [comment]
If you want to add some asserts so that you use it correctly, that would be a big help

**Comment by jon-chuang** [comment]
It may just be a matter of renaming `get_fake_value` -> `get_fake_value_unless_nn_module_attr` but that's just a bad API lol.

I think we can have `get_fake_value(allow_real=False)`

**Comment by jon-chuang** [comment]
Actually, I decided to pytree wrap into fake tensors
