### ISSUE TITLE
[aotinductor]14k models: AttributeError: 'int' object has no attribute 'device'

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#111830]
```
python main.py --compile_mode aot_inductor -e ./generated/test_chengchunhsu_EveryPixelMatters.py:FCOSDiscriminator
```

cc @ezyang @anijain2305 @chauhang @penguinwu @chenyang78 @msaroufim @bdhirsh @zou3519 @wconstab

**Comment by desertfire** [comment]
@oulgen , assign to you since you are working on it. The underlying problem is the same as the int-as-input example you created.

**Comment by oulgen** [comment]
> @oulgen , assign to you since you are working on it. The underlying problem is the same as the int-as-input example you created.

umm, where do I find main.py and `./generated/test_chengchunhsu_EveryPixelMatters.py:FCOSDiscriminator`

**Comment by desertfire** [comment]
> > @oulgen , assign to you since you are working on it. The underlying problem is the same as the int-as-input example you created.
> 
> umm, where do I find main.py and `./generated/test_chengchunhsu_EveryPixelMatters.py:FCOSDiscriminator`

It's from 14k models, https://github.com/jansel/pytorch-jit-paritybench, but you can start with your simple test case.
