### ISSUE TITLE
Overriding Kernel Registrations on XLA

### ISSUE THREAD

**Issue by Bin1024** [pytorch/pytorch#111887]
### 🐛 Describe the bug

We implemented a torch_npu plugin that uses the key XLA to register the operator.
As shown below
```
import torch
import torch_npu
```
```
[W OperatorEntry.cpp:150] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::_foreach_floor(Tensor[] tensors) -> (Tensor[])
    registered at build/aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: XLA
  previous kernel: registered at ./build/aten/src/ATen/RegisterCPU.cpp:21063
       new kernel: registered at ./torch_npu/csrc/aten/RegisterNPU.cpp:20012 (function registerKernel)
```
After running the above code, there will be a lot of WARNING logs for the operator. But the previous kernel shown is RegisterCPU, is this warning misleading. Also why does torch show that there are duplicate kernels registered on XLA, which are registered in a third party plugin. Does torch register some XLA operators?

cc @ezyang @bdhirsh 

### Versions

PyTorch version: 1.11.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 15.0.5
CMake version: version 3.24.1
Libc version: glibc-2.10

Python version: 3.7.5 (default, Oct 25 2019, 15:51:11)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-76-generic-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              72
On-line CPU(s) list: 0-71
Thread(s) per core:  2
Core(s) per socket:  18
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz
Stepping:            7
CPU MHz:             3300.004
BogoMIPS:            5200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            25344K
NUMA node0 CPU(s):   0-17,36-53
NUMA node1 CPU(s):   18-35,54-71
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==5.0.4
[pip3] numpy==1.21.6
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.11.0+cpu
[pip3] torch-npu==1.11.0.post5+gita2c727c
[pip3] torch-test-cpp-extension==0.0.0
[pip3] torchtext==0.6.0
[pip3] torchvision==0.12.0a0+9b5a3fe
[conda] mkl                       2023.0.0                 pypi_0    pypi
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] pytorch-sphinx-theme      0.0.24                   pypi_0    pypi
[conda] torch                     1.11.0+cpu               pypi_0    pypi
[conda] torch-npu                 1.11.0.post5+gita2c727c          pypi_0    pypi
[conda] torch-test-cpp-extension  0.0.0                    pypi_0    pypi
[conda] torchtext                 0.6.0                    pypi_0    pypi
[conda] torchvision               0.12.0a0+9b5a3fe          pypi_0    pypi

**Comment by ezyang** [comment]
This is surprising and not expected. However, I see your PyTorch version is very old. Does this happen on newer versions?

**Comment by Bin1024** [comment]
We registered with xla in both 2.0 and 1.11 versions and this happened. In the master version, we used the key privateuse1 and this did not happen.

**Comment by ezyang** [comment]
What happens if you build pytorch from source?

**Comment by Bin1024** [comment]
Would have the same problem.

**Comment by Bin1024** [comment]
Now, we did register twice at xla, causing duplicate warning. However, I found this warning from torch to be misleading. The previous kernel warning is not correct.

**Comment by ezyang** [comment]
oh maybe the error reporting code is just wrong then
