### ISSUE TITLE
[dynamo] Should `wrap_to_fake_tensor_and_record` be idempotent with regard to `FakeTensor`s?

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#111873]
### 🐛 Describe the bug

`wrap_to_fake_tensor_and_record` will actually wrap an existing `FakeTensor` within another layer of `FakeTensor`. What use does this have?

Shouldn't this function be idempotent - return the same `FakeTensor`, and not wrap it further? Further, shouldn't we forbid wrapping one fake tensor in another? 

Perhaps there are use cases, since one layer of fake tensor may have metadata that another would not?

Nevertheless, for the purpose of Dynamo, perhaps we should not allow nested fake tensor.

This is because nested FakeTensor could lead to weird aliasing bugs, as we are now shifting to using `FakeTensor` object identity to identify aliasing when it comes to user code in Dynamo. (See: https://github.com/pytorch/pytorch/issues/111585 https://github.com/pytorch/pytorch/pull/111196)

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @eellison @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jon-chuang** [comment]
Actually, I'm no longer sure if the method we used so far is waterproof. Perhaps using the following may be more foolproof?

https://github.com/pytorch/pytorch/blob/e62c887babea75b4966c4ec3cef292229df81076/torch/_dynamo/variables/builder.py#L1064C2-L1064C2

Nevertheless, I think this will not be sufficient for tracking intermediate values.

**Comment by jon-chuang** [comment]
Luckily, there is a util for checking if a FakeTensor is a dynamo-originated fake. In this case, we can avoid wrapping again.

https://github.com/pytorch/pytorch/blob/e62c887babea75b4966c4ec3cef292229df81076/torch/_subclasses/fake_tensor.py#L1336

**Comment by jon-chuang** [comment]
Let's canary test not re-wrapping fake if `is_our_fake` evaluates to True.

**Comment by jon-chuang** [comment]
The next question is what are the locations at which we _may_ end up wrapping fake tensors twice? It seems there is:
`VariableBuilder.wrap_tensor`

**Comment by jon-chuang** [comment]
The question that I am asking myself is - is there a more foolproof way to dedup _any_ `FakeTensor` flowing throughout Dynamo? Is there a _single source of truth_ which can simplify the reasoning process?

The answer is probably yes. Whenever we generate a new `FakeTensor`, we need to be careful to ensure we have not generated it before, by checking some sort of cache.

**Comment by ezyang** [comment]
This is the correct rule: https://github.com/pytorch/pytorch/issues/111873#issuecomment-1776317686

Where were you still confused about this?

The FakeTensorMode itself is responsible for maintaining a cache of Tensor to FakeTensor mapping

**Comment by jon-chuang** [comment]
Actually @ezyang, this function https://github.com/pytorch/pytorch/blob/e62c887babea75b4966c4ec3cef292229df81076/torch/_subclasses/fake_tensor.py#L1336 is not broad enough for our use cases. 

As you can see in https://github.com/pytorch/pytorch/pull/111954, we have to deal with both tensor subclasses whose flattened tensors and functionalized tensors whose inner tensors have been fakeified by the running instance of dynamo

**Comment by jon-chuang** [comment]
Fully fixed by https://github.com/pytorch/pytorch/pull/111954
