### ISSUE TITLE
Install torch2.1.0+cuda11.8, I get error cannot import name '_get_privateuse1_backend_name' from 'torch._C'

### ISSUE THREAD

**Issue by zte-tcb** [pytorch/pytorch#111895]
### 🐛 Describe the bug

I build a docker image, base image is nvcr.io/nvidia/pytorch:22.12-py3.   In Dockerfile,  I install python3.10 and torch 2.1.0+cuda11.8,  But I get error: cannot import name '_get_privateuse1_backend_name' from 'torch._C'

The Dockerfile is: 
```
FROM nvcr.io/nvidia/pytorch:22.12-py3
RUN apt-get update --fix-missing
RUN apt-get upgrade -y
RUN apt-get update

RUN apt-get -y remove python3.8 && apt-get -y remove --auto-remove python3.8 && apt-get purge python3.8
# Install python3.10
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install  -y python3.10 python3.10-dev
RUN ln -s -f /usr/bin/python3.10-config /usr/bin/python3-config
RUN ln -s -f /usr/bin/python3.10 /usr/bin/python3

# Install torch 
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
RUN python3.10 -m pip install --upgrade pip
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

Run the image and import torch, has error :
```
root@f013972c3e90:/workspace# python3
Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1119, in <module>
    from ._tensor import Tensor
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 12, in <module>
    import torch.utils.hooks as hooks
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/__init__.py", line 6, in <module>
    from .backend_registration import rename_privateuse1_backend, generate_methods_for_privateuse1_backend
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/backend_registration.py", line 2, in <module>
    from torch._C import _rename_privateuse1_backend, _get_privateuse1_backend_name
ImportError: cannot import name '_get_privateuse1_backend_name' from 'torch._C' (/usr/local/lib/python3.10/dist-packages/torch/_C.cpython-310-x86_64-linux-gnu.so)
```

### Versions

 Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-164-generic-x86_64-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: Quadro RTX 4000
Nvidia driver version: 515.105.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             32
On-line CPU(s) list:                0-31
Thread(s) per core:                 2
Core(s) per socket:                 8
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) Silver 4208 CPU @ 2.10GHz
Stepping:                           7
CPU MHz:                            800.081
CPU max MHz:                        3200.0000
CPU min MHz:                        800.0000
BogoMIPS:                           4200.00
Virtualization:                     VT-x
L1d cache:                          512 KiB
L1i cache:                          512 KiB
L2 cache:                           16 MiB
L3 cache:                           22 MiB
NUMA node0 CPU(s):                  0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30
NUMA node1 CPU(s):                  1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31
Vulnerability Gather data sampling: Mitigation; Microcode
Vulnerability Itlb multihit:        KVM: Mitigation: Split huge pages
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:             Mitigation; Enhanced IBRS
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Mitigation; TSX disabled
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.1.0+cu118
[pip3] torchaudio==2.1.0+cu118
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] Could not collect

cc @seemethere @malfet @osalpekar @atalman

**Comment by weitunglin** [comment]
same issue here, does anyone got a solution?

**Comment by seanexp** [comment]
[This comment](https://github.com/pytorch/pytorch/issues/24834#issuecomment-534595871) worked in my case.

**Comment by zte-tcb** [comment]
> [This comment](https://github.com/pytorch/pytorch/issues/24834#issuecomment-534595871) worked in my case.

yes, I worked. In my Dockerfile, worked with uninstall old torch.
`RUN pip3 uninstall -y torch
RUN apt-get -y remove --auto-remove python3.8 && apt-get purge python3.8
RUN rm -rf /usr/lib/python3.8 /etc/python3.8 /usr/local/lib/python3.8
`

**Comment by zte-tcb** [comment]
> [This comment](https://github.com/pytorch/pytorch/issues/24834#issuecomment-534595871) worked in my case.

thanks, i worked with uninstall old torch
```
RUN pip3 uninstall -y torch
RUN apt-get -y remove --auto-remove python3.8 && apt-get purge python3.8
RUN rm -rf /usr/lib/python3.8 /etc/python3.8 /usr/local/lib/python3.8
```

**Comment by Nardien** [comment]
I struggled with this problem for an entire day, but now I have resolved it. I use a conda environment and constantly faced this ImportError, even after removing torch from the conda environment. I finally realized that **removing conda from the system python** is crucial to resolving this issue. I hope my findings can assist others who may struggle with this error...

**Comment by jlandahl** [comment]
I've run into this exact problem as well. In my case I'm using Mamba to setup a fresh environment, but since the recommended `conda` command doesn't work (`conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`) I've used the recommended `pip`command (`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`) to install into the Mamba/Conda environment. None of the above fixes solve the problem in this case.
