### ISSUE TITLE
Custom FFT implementation returns unexpected results when using torch.compile

### ISSUE THREAD

**Issue by PeaBrane** [pytorch/pytorch#111884]
### 🐛 Describe the bug

I am trying to implement a custom radix-16 FFT function, because `torch.compile` does not yet support complex data types. The basic idea is to basically represent FFT as a series of blocked 16 x 16 matrix multiplications using `torch.einsum`, similar in spirit to the BlockFFT approach proposed in the [H3 paper](https://arxiv.org/abs/2212.14052). 

The function can run normally and the results are correct without using `torch.compile`, which I have tested by comparing the results with the results outputted by `torch.fft.fft`. However, when applying `torch.compile` to this function, this is no longer the case, and the results are completely different, although there is no runtime error.

### Error logs

assert torch.allclose(input_f, to_complex(block_dft_compiled(input)), rtol=1e-3, atol=1e-3)  # this will fail

### Minified repro

```
import torch


def complex_matrix(real, imag):
    return torch.stack((
            torch.stack((real, -imag), dim=-1),
            torch.stack((imag, real), dim=-1)
        ), dim=-2)


to_complex = lambda x: torch.complex(x[..., 0, 0], x[..., 1, 0])


def block_dft(input):    
    input_block = input.view(16, 16, -1)
    last_dim_size = input_block.shape[-1]
    
    tau = 2 * torch.pi
    range_16 = torch.arange(16, device=input.device)
    range_large = torch.arange(16 * last_dim_size, device=input.device)
    range_small = torch.arange(last_dim_size, device=input.device)
    
    dft_real = torch.cos(-(range_16.unsqueeze(-1) * range_16) / 16 * tau)
    dft_imag = torch.sin(-(range_16.unsqueeze(-1) * range_16) / 16 * tau)
    dft = complex_matrix(dft_real, dft_imag)
    
    dft_small_real = torch.cos(-(range_small.unsqueeze(-1) * range_small) / last_dim_size * tau)
    dft_small_imag = torch.sin(-(range_small.unsqueeze(-1) * range_small) / last_dim_size * tau)
    dft_small = complex_matrix(dft_small_real, dft_small_imag)
    
    twid_real = torch.cos(-(range_16.unsqueeze(-1) * range_large) / (16 * 16 * last_dim_size) * tau).reshape(16, 16, -1)
    twid_imag = torch.sin(-(range_16.unsqueeze(-1) * range_large) / (16 * 16 * last_dim_size) * tau).reshape(16, 16, -1)
    twid = complex_matrix(twid_real, twid_imag)
    
    twid_small_real = torch.cos(-(range_16.unsqueeze(-1) * range_small) / (16 * last_dim_size) * tau)
    twid_small_imag = torch.sin(-(range_16.unsqueeze(-1) * range_small) / (16 * last_dim_size) * tau)
    twid_small = complex_matrix(twid_small_real, twid_small_imag)
    
    input_block = complex_matrix(input_block, torch.zeros_like(input_block))
    
    return torch.einsum('xyzAB,xfBC,ygDE,zhFG,fyzCD,gzEF->hgfAG', 
                        input_block, 
                        dft, dft, dft_small, 
                        twid, twid_small).flatten(0, 2)


input = torch.rand(1024)
input_f = torch.fft.fft(input)

assert torch.allclose(input_f, to_complex(block_dft(input)), rtol=1e-3, atol=1e-3)  # this will pass

block_dft_compiled = torch.compile(block_dft)
assert torch.allclose(input_f, to_complex(block_dft_compiled(input)), rtol=1e-3, atol=1e-3)  # this will fail
```

### Versions

PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-83-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A30
GPU 1: NVIDIA A30

Nvidia driver version: 535.86.10
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn.so.8.8.1
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.8.1
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.8.1
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.8.1
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.8.1
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.8.1
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.8.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      48 bits physical, 48 bits virtual
CPU(s):                             64
On-line CPU(s) list:                0-63
Thread(s) per core:                 2
Core(s) per socket:                 32
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          AuthenticAMD
CPU family:                         25
Model:                              1
Model name:                         AMD EPYC 7543P 32-Core Processor
Stepping:                           1
Frequency boost:                    enabled
CPU MHz:                            1500.000
CPU max MHz:                        3737.8899
CPU min MHz:                        1500.0000
BogoMIPS:                           5600.03
Virtualization:                     AMD-V
L1d cache:                          1 MiB
L1i cache:                          1 MiB
L2 cache:                           16 MiB
L3 cache:                           256 MiB
NUMA node0 CPU(s):                  0-63
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torcheval==0.0.7
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.24.3          py310hd5efca6_0  
[conda] numpy-base                1.24.3          py310h8e6c178_0  
[conda] pytorch                   2.1.0           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torchaudio                2.1.0               py310_cu118    pytorch
[conda] torcheval                 0.0.7                    pypi_0    pypi
[conda] torchtriton               2.1.0                     py310    pytorch
[conda] torchvision               0.16.0              py310_cu118    pytorch

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @amjames @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @ColinPeppler @desertfire @msaroufim @bdhirsh @zou3519 @wconstab

**Comment by ezyang** [comment]
Can you tell us how much outside of tolerance the results are? The most common explanation is that torch.compile is running your matmuls at lower precision

**Comment by ezyang** [comment]
You could try the accuracy minifier on your example, it might be able to nail down the specific problem

**Comment by yf225** [comment]
@PeaBrane Could you try `torch.compile(..., backend="aot_eager")`? It will help us pinpoint where the issues comes from.

**Comment by zhxchen17** [comment]
backend="aot_eager" will return the same result as eager, which suggests it might be from inductor.
