### ISSUE TITLE
[dynamo] `AutogradFunctionMethodHigherOrderVariable` may not properly guard kwargs

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#111936]
### 🐛 Describe the bug

We will run `AutogradFunctionMethodHigherOrderVariable` within dynamo even though its kwargs are constant but we do not ensure that we guard on those constants.

I'm not entirely sure how to construct a scenario in which we can provide args that are constant but not guarded (or whose constant value is not guarded).

For instance, this may be some constant attribute of `nn.Module` which I don't think we currently guard... :thinking: 

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by williamwen42** [comment]
@jon-chuang are you working on this?

**Comment by jon-chuang** [comment]
Depends if we can move it into https://github.com/pytorch/pytorch/pull/111938 

@zou3519 

As you can see, these kwargs are completely unwarrantedly introduced in https://github.com/pytorch/pytorch/commit/4005152b92d521f069b442bf35067f2f2d1ff7a3#diff-d6c3a57794a9a8a79eacedc57d68ff631fe80776f8701398eb3ef349973b033b

**Comment by jon-chuang** [comment]
I guess yes. It is now being handled in https://github.com/pytorch/pytorch/pull/111938 along with the other poor handling of kwargs
