### ISSUE TITLE
[dynamo] `ExecutorchCallDelegateHigherOrderVariable` may not preserve `FakeTensor` identity

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#111917]
### 🐛 Describe the bug

`ExecutorchCallDelegateHigherOrderVariable` will attempt to retrieve the real values as inputs to the executorch module, and then deep copy fake the result into new fake values. However, it is possible that the `executorch_call_delegate` function might perform in-place ops. 

The new FakeTensors would no longer share the same identity as the input fake tensors, violating our mechanism for Dynamo trace-time aliasing detection. 

No repro as of yet, this is just speculative

Solution: manually dedup by matching the `fake <-> real <-> fake` relationship between inputs and outputs.

### Versions

main

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan

**Comment by jon-chuang** [comment]
I still don't understand why we can't just trace `Executorch` module directly within dynamo.

**Comment by angelayi** [comment]
The purpose of the `executorch_call_delegate` op is to call a delegated module as if it were a black box. We do not want to trace through this black box as it will be delegated to a specialized hardware.

**Comment by tugsbayasgalan** [comment]
executorch_call_delegate should be used on functional graph, so there shouldn't be any input mutations or aliasing inside

**Comment by jon-chuang** [comment]
Ok. Could we assert in the higher order op tracing that none of the inputs are the outputs? (we just use a set on the in/out ids to ensure disjoint)

**Comment by angelayi** [comment]
Does dynamo check for in-place aliasing? Shouldn't that be part of functionalization?

**Comment by jon-chuang** [comment]
> Does dynamo check for in-place aliasing? Shouldn't that be part of functionalization?

This is user-side code that requires info about Tensor aliasing. For instance `x is y`, `x in set({x, y})` where x, y are Tensors.

**Comment by angelayi** [comment]
I see, that makes sense, thanks for the explanation!
> Could we assert in the higher order op tracing that none of the inputs are the outputs?

This seems reasonable to me!

**Comment by tugsbayasgalan** [comment]
I feel like the input/output aliasing should fail at functionalization time. Are you using torch.export?

**Comment by jon-chuang** [comment]
> should fail at functionalization time

We need this to fail at trace time too.

> Are you using torch.export?

I'm not sure which code paths executorch typically takes. Ideally, whichever path it takes, it should not allow inputs to alias outputs, then Dynamo user-side alias tracing mechanism will be happy.

**Comment by tugsbayasgalan** [comment]
Yeah it should be torch.export. Functionalization happens at tracing time

**Comment by jon-chuang** [comment]
Hmm, so we are functionalizing the tensors before they enter dynamo, is that correct?

**Comment by jon-chuang** [comment]
Hmm, could you point me to where I can read about this code path? Where does this functionalization occur before entering the higher order op tracing etc.

**Comment by tugsbayasgalan** [comment]
> Hmm, could you point me to where I can read about this code path? Where does this functionalization occur before entering the higher order op tracing etc.

For functionalizing call_delegate: https://github.com/pytorch/executorch/blob/main/exir/delegate.py#L125

I think we can do something similar to https://github.com/pytorch/pytorch/blob/main/torch/_higher_order_ops/cond.py#L394

**Comment by jon-chuang** [comment]
@tugsbayasgalan 

> I think we can do something similar to https://github.com/pytorch/pytorch/blob/main/torch/_higher_order_ops/cond.py#L394

https://github.com/pytorch/pytorch/blob/53444687120b47be9af2fa0e758d3319d8be3d2c/torch/_higher_order_ops/cond.py#L302 

requires access to the fx graphmodule of the code body.

Why is the disjointness check proposed in https://github.com/pytorch/pytorch/pull/111960 insufficient? :thinking:

**Comment by tugsbayasgalan** [comment]
> @tugsbayasgalan
> 
> > I think we can do something similar to https://github.com/pytorch/pytorch/blob/main/torch/_higher_order_ops/cond.py#L394
> 
> https://github.com/pytorch/pytorch/blob/53444687120b47be9af2fa0e758d3319d8be3d2c/torch/_higher_order_ops/cond.py#L302
> 
> requires access to the fx graphmodule of the code body. This is unavailable for executorch as it is meant to be a black box.
> 
> Why is the disjointness check proposed in #111960 insufficient? 🤔 It's not meant to throw an error in normal settings of course, but in case something goes wrong, at least we will not silently error.

Yeah you are right. We don't have a graph module. I think it is just in terms of abstraction, this sanity code should live under functionalization. I think you can do the same thing you did in your PR under  https://github.com/pytorch/executorch/blob/main/exir/delegate.py#L125 .

**Comment by jon-chuang** [comment]
> this sanity code should live under functionalization.

Hmm, how about both? I don't think it will cost too much to check. We'll want to install the sanity check on the Dynamo side regardless - Dynamo is the one that needs the invariant of no input/output aliasing after all.

**Comment by jon-chuang** [comment]
Merge was reverted. This is still an issue.

https://github.com/pytorch/pytorch/pull/111960

**Comment by zejun-chen** [comment]
> The purpose of the `executorch_call_delegate` op is to call a delegated module as if it were a black box. We do not want to trace through this black box as it will be delegated to a specialized hardware.

Hi, @angelayi 
How to understand the black box here? Is it used to bypass the input function from the torch.compile?
I wonder how to use the `executorch_call_delegate` in code.
I search the `executorch_call_delegate`, and it looks like the API is serving for the Qualcomm CPUs.
Thank you.

**Comment by angelayi** [comment]
@zejun-chen `executorch_call_delegate` is used for a concept of "delegation" in ExecuTorch, where we delegate certain computation to a different backend than the one the ExecuTorch runtime is running on. Here's a pointer to the tutorial if you want to learn more: https://pytorch.org/executorch/stable/tutorials/export-to-executorch-tutorial.html#delegating-to-a-backend

**Comment by zejun-chen** [comment]
> @zejun-chen `executorch_call_delegate` is used for a concept of "delegation" in ExecuTorch, where we delegate certain computation to a different backend than the one the ExecuTorch runtime is running on. Here's a pointer to the tutorial if you want to learn more: https://pytorch.org/executorch/stable/tutorials/export-to-executorch-tutorial.html#delegating-to-a-backend

Thank you. Is there any example of using `executorch_call_delegate` to delegate the certain graph to a different backend?

**Comment by angelayi** [comment]
>  Is there any example of using executorch_call_delegate to delegate the certain graph to a different backend?
Yes, the tutorial delegates the graph to the dummy backend `BackendWithCompilerDemo`, but there are also more legit backends, like [XNNPACK](https://pytorch.org/executorch/stable/tutorial-xnnpack-delegate-lowering.html#lowering-a-quantized-model-to-xnnpack). You can take a look at the other tutorials in the website.
> From the tutorial, the executorch_call_delegate is compiled by Dynamo/AOTAutograd, not public API to user?
No, `executorch_call_delegate` is not a public API to the user. It will get created by calling `to_backend`.
