### ISSUE TITLE
Missing a vectorized version of TORCH_CHECK

### ISSUE THREAD

**Issue by guilhermeleobas** [pytorch/pytorch#111953]
### 🐛 Describe the bug

This is a follow-up issue of https://github.com/pytorch/pytorch/pull/108690 to keep track if a vectorized version of `TORCH_CHECK` is needed or not.

### Versions

main

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @msaroufim @wconstab @bdhirsh @zou3519 @yf225 @aakhundov

**Comment by ezyang** [comment]
... you sure you want to use TORCH_CHECK in generated kernel code?! That's a big misuse of the API lol

**Comment by peterbell10** [comment]
We already use `TORCH_CHECK` and friends in eager mode indexing kernels
https://github.com/pytorch/pytorch/blob/6fd36593910d9d8cdf05dd182a78993e76f12a80/aten/src/ATen/native/cpu/IndexKernel.cpp#L81

**Comment by zhxchen17** [comment]
Hi @guilhermeleobas Thanks for raising the issue. I'm cleaning up the old issues and wondering if you still need this feature to be added?

**Comment by peterbell10** [comment]
Vectorized cpu kernels now have indexing assertions, so this is not needed.
