### ISSUE TITLE
[feature request] PyTorch: Attention operation in NMT

### ISSUE THREAD

**Issue by xhzhao** [pytorch/pytorch#11199]
hi
we know that Attention mechanism is very popular in NMT domain, and i think it would be great to  support this operation in framework level. With this operation , we will get the following benefits:

- reuse this op and simplify the code for the NMT applications

- more easy to do performance optimization for this op.

i think this operation should support 4 types of attention: dot, general, mlp, and multi-head attention.

- dot, general, mlp is the traditional attention mechanism , see OpenNMT-py code [here](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/global_attention.py#L54)

- multi-head attention is for the Transformer, see this related issue [here](https://github.com/pytorch/pytorch/issues/10459)

i collected some reference implementation:
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/global_attention.py 
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/multi_headed_attn.py
https://github.com/pytorch/fairseq/blob/master/fairseq/models/fconv.py#L287
https://github.com/pytorch/fairseq/blob/master/fairseq/modules/multihead_attention.py#L16
https://github.com/mlperf/reference/blob/master/rnn_translator/pytorch/seq2seq/models/attention.py

i understand that there maybe some variances for the attention operation, but i think we could extract the common part and make this new op support most of its variances.

**Comment by DNGros** [comment]
Can this be closed now with #18334  or perhaps broken into separate issues for the kinds of attentions that remain that people still have need for? Most of the other attentions seem like a special case of MultiheadedAttention. Not sure if people would find it valuable to have it as a separate function....
