### ISSUE TITLE
vector loss autograd computation

### ISSUE THREAD

**Issue by twangnh** [pytorch/pytorch#111914]
### 🚀 The feature, motivation and pitch

Hi, the default torch autograd only supports scalar loss, but if we need to compute vectorized loss, e.g., losses = [loss1, loss2, ... lossn], wrt. to weights, how to achieve this function efficiently without loop? Our current workaround is looping through all loss, 

grad_vectors = []
for l in losses:
    grad = torch.autograd.grad(l, self.weight, retain_graph=True)[0]
    grad_vectors.append(grad)

cc @zou3519

**Comment by ezyang** [comment]
Use vmap with per-sample gradients. Check out https://pytorch.org/tutorials/intermediate/per_sample_grads.html

**Comment by ezyang** [comment]
nope!
