### ISSUE TITLE
torch.tanh returns wrong result on sliced tensors

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#11206]
## Issue description

`torch.tanh` seems to yield the wrong result, if the input tensor is sliced.
A `.contiguous` call seems to fix the behavior.
[Link](https://discuss.pytorch.org/t/different-behaviors-on-slices/24365) to thread in the board.

## Code example

```python
x = torch.zeros(3, 3, 1, 2)
x[:, 2, ...] = 1.
print(x[:, 2, ...])
print(torch.tanh(x[...]))
print(torch.tanh(x[:, 2, ...])) # wrong result
print(torch.tanh(x[:, 2, ...].contiguous())) # right result
```

## System Info

- OS: Ubuntu 16.04.5 LTS
- PyTorch version: 0.5.0a0+6c7fb15 (installed from source)
- Python version: 2.7
- GCC version (if compiling from source): (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- CMake version: 3.11.1

Also reported on `0.4.1` in the thread.

**Comment by SsnL** [comment]
All functions implemented in `cpu/UnaryOpsKernel.cpp` have this problem.

cc @colesbury @cpuhrsch I briefly looked and something seems wrong with `CPU_tensor_parallel_kernel_apply2`.
