### ISSUE TITLE
torch.inference_mode and tensor subclass: RuntimeError: Cannot set version_counter for inference tensor

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#112024]
### 🐛 Describe the bug

```
import torch

class T(torch.Tensor):
    def __new__(cls, elem):
        return torch.Tensor._make_wrapper_subclass(cls, elem.shape, dtype=elem.dtype)

    def __init__(self, elem):
        self.elem = elem

    @classmethod
    def __torch_dispatch__(cls, func, types, args, kwargs=None):
        if func is torch.ops.aten.detach.default:
            (self,) = args
            return cls(torch.ops.aten.detach.default(self.elem))
        raise NotImplementedError(f"{func}")
    
x = torch.randn(3)
y = T(torch.randn(3))
    
print("ok")
with torch.inference_mode():
    x.detach()
    
print("fail")
with torch.inference_mode():
    y.detach()
```

this fails with

```
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu005.nha1 ~/local/a/pytorch (63a99720)]$ python no.py
ok
fail
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/no.py", line 26, in <module>
    y.detach()
  File "/data/users/ezyang/a/pytorch/torch/_tensor.py", line 1397, in __torch_function__
    ret = func(*args, **kwargs)
RuntimeError: Cannot set version_counter for inference tensor
```

You can work around it with 

```
    @classmethod
    def __torch_dispatch__(cls, func, types, args, kwargs=None):
        if func is torch.ops.aten.detach.default:
            (self,) = args
            with torch.inference_mode(False):  # NEW!
                return cls(torch.ops.aten.detach.default(self.elem))
        raise NotImplementedError(f"{func}")
```

suggesting that the proximal cause of the problem is that when we construct T inside the torch dispatch function, it is created as an inference mode tensor, even though the semantics of detach() on a non-inference mode tensor when inference mode is enabled is to create a non-inference tensor.

Not entirely sure what the correct fix is.

cc @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @msaroufim @bdhirsh @IvanKobzarev 

### Versions

main

**Comment by ezyang** [comment]
I think the correct fix is: (1) use return_and_correct_aliasing and (2) fix that to appropriately make the output tensor inference mode or not.

We don't have an API to make an inference mode tensor not, or vice versa. So I guess we would have to add that.

**Comment by soulitzer** [comment]
> We don't have an API to make an inference mode tensor not, or vice versa. So I guess we would have to add that.

That sounds like that would work, but alternatively one could use that same API to mirror the inference mode-ness of the inner tensor when the wrapper tensor subclass is constructed.

```
with torch.inference_mode():
    x = torch.tensor(1.)
T(x) # should this be an inference tensor?
```

**Comment by ezyang** [comment]
@bdhirsh did you fix this?

**Comment by zou3519** [comment]
https://github.com/pytorch/pytorch/pull/134878 fixed something else but seems like it also fixes this by side effect. I'm not sure if it's the correct fix for this issue.

**Comment by bdhirsh** [comment]
I tested locally and https://github.com/pytorch/pytorch/pull/134878 fixes it for me
