### ISSUE TITLE
Windows 10 Build Error - caffe2_gpu

### ISSUE THREAD

**Issue by nwsterling** [pytorch/pytorch#11203]
Hello. I have been trying to build pytorch on Windows 10 Pro for about a week. I am really hitting a wall, and not sure how to proceed. I would appreciate so much any pointers that someone could give me. Here is my set of commands and output....

INPUT

set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1
REM The following two lines are needed for Python 2.7, but the support for it is very experimental.
set MSSdk=1
set FORCE_PY27_BUILD=1
REM As for CUDA 8, VS2015 Update 3 is also required to build PyTorch. Use the following two lines.
set "PREBUILD_COMMAND=%VS140COMNTOOLS%....\VC\vcvarsall.bat"
set PREBUILD_COMMAND_ARGS=x64

call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.15
python setup.py install

OUTPUT
...

C:/Development/workspaces/repos/pytorch/aten/src/ATen/native/cuda/SpectralOps.cu(288): warning : dllexport/dllimpo
rt conflict with "at::native::_fft_cufft" [C:\Development\workspaces\repos\pytorch\build\caffe2\caffe2_gpu.vcxproj]

"c:\Development\workspaces\repos\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"C:\Development\workspaces\repos\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Development\workspaces\repos\pytorch\build\caffe2\apply_test.vcxproj" (default target) (4) ->
"C:\Development\workspaces\repos\pytorch\build\caffe2\caffe2_gpu.vcxproj" (default target) (18) ->
(CustomBuild target) ->
C:/Development/workspaces/repos/pytorch/aten/src\ATen/core/ArrayRef.h(152): error : cannot use an entity undefined
in device code [C:\Development\workspaces\repos\pytorch\build\caffe2\caffe2_gpu.vcxproj]
C:/Development/workspaces/repos/pytorch/aten/src\ATen/core/ArrayRef.h(152): error : identifier "Typeinfo for ::at
::Error" is undefined in device code [C:\Development\workspaces\repos\pytorch\build\caffe2\caffe2_gpu.vcxproj]
Error : Internal Compiler error (codegen): "there was an error in verifying the lgenfe output!" [C:\Development\wo
rkspaces\repos\pytorch\build\caffe2\caffe2_gpu.vcxproj]

11950 Warning(s)
3 Error(s)
Time Elapsed 01:56:37.06

(py36) c:\Development\workspaces\repos\pytorch\build>IF ERRORLEVEL 1 exit 1
Failed to run 'tools\build_pytorch_libs.bat --use-cuda --use-nnpack caffe2 libshm_windows'

**Comment by peterjc123** [comment]
@nicksterlingtek Looks like it's a nvcc issue. I don't know much about this. If it is possible, would you please update your CUDA version to CUDA 9?

**Comment by nicksterlingtek** [comment]
Thank you @peterjc123! I am using CUDA 9.2. Maybe I should try with 9.1?

**Comment by peterjc123** [comment]
@nicksterlingtek Which VS version is being used in your build, especially when you build caffe2_gpu?

**Comment by nicksterlingtek** [comment]
Thank you peterjc123, I'm using VS2017.

**Comment by peterjc123** [comment]
@nicksterlingtek Could you clone the latest repo and try again? I didn't find any clue in the current version of `ArrayRef.h`.

**Comment by BPavol** [comment]
I encounter same problem with exact same error message. I have Windows 8.1, VS 2017 Community edition and build tools v15.8.4. I checked PyTorch repo yesterday and update all git submodules. I have CUDA 9.2 installed too.

In ArrayRef.h line 152 is used macro:
```
AT_CHECK(
        N + M <= size(),
        "ArrayRef: invalid slice, N = ",
        N,
        "; M = ",
        M,
        "; size = ",
        size());
```

So condition
```
N + M <= size()
```
isn't satisfied because of error message, but I don't know why.

**Comment by ezyang** [comment]
What if you comment out the `AT_CHECK` here?

**Comment by BPavol** [comment]
I try it but with no luck. Same error but on another line ArrayRef.h(134):
```
/// front - Get the first element.
  AT_CPP14_CONSTEXPR const T& front() const {
    AT_CHECK(!empty(), "ArrayRef: attempted to access front() of empty list");
    return Data[0];
  }
```

I trying it with commented body of macro AT_CHECK now, but i don`t think it is the right way. Compile time takes more than 9 hours on my laptop.

**Comment by peterjc123** [comment]
@BPavol You could use Ninja to accelerate CUDA build. See details [here](https://pytorch.org/docs/stable/notes/windows.html#speeding-cuda-build-for-windows). Make sure you run the commands in the "x64 Native Tools Command Prompt for VS 2017".

**Comment by gianni-rg** [comment]
@BPavol @peterjc123 I had the same issue in similar dev environment (using Cuda 9.2, VS2017 15.8.4, and Ninja for fast building), just removing AT_CPP14_CONSTEXPR don't raise the error and build complete successfully

**Comment by BPavol** [comment]
@peterjc123 @gianni-rg Thank you, it helps. But I have another error:
```
D:/backup/Dokumenty_C/Programovanie/Python/PyTorch/pytorch/build/aten/src\ATen/N
ativeFunctions.h(658): note: see previous definition of '_unique_cuda'
D:/backup/Dokumenty_C/Programovanie/Python/PyTorch/pytorch/aten/src/ATen/native/
cuda/Unique.cu(176): warning C4273: 'at::native::_unique_dim_cuda': inconsistent
 dll linkage
D:/backup/Dokumenty_C/Programovanie/Python/PyTorch/pytorch/build/aten/src\ATen/N
ativeFunctions.h(660): note: see previous definition of '_unique_dim_cuda'
ninja: build stopped: subcommand failed.
```

**Comment by peterjc123** [comment]
@BPavol The message you provided is rather useless. It doesn't contain any useful information. Please provide the full build log.

**Comment by peterjc123** [comment]
Duplicate to https://github.com/pytorch/pytorch/issues/15630.
