### ISSUE TITLE
torch.compile doesn't preserve torch.set_grad_enabled() (and possibly other APIs) side effects

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#112072]
### 🐛 Describe the bug

```py
import torch

def f(x):
    y = x.clone()
    torch.set_grad_enabled(False)
    return y.clone()

f_compiled = torch.compile(f, backend='aot_eager', fullgraph=True)

x = torch.randn(3, requires_grad=True)
y = f(x)
print(torch.is_grad_enabled())
torch.set_grad_enabled(True)
y = f_compiled(x)
print(torch.is_grad_enabled())
```
This prints (False, True). The function `f` has a side effect of disabling the current grad mode, after it has been compiled it loses this side effect.

NB: this doesn't happen under backend='eager' in backend='eager' Dynamo just runs the graph eagerly and the eager graph has a call to torch.set_grad_enabled.

It's unclear to me if this is Dynamo's responsibility (to track this as a side effect) or AOTAutograd's responsibility (to add the call to the epilogue as a part of its "functionalization").

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jon-chuang** [comment]
We should figure out how to track it in `output.side_effects`

**Comment by ezyang** [comment]
This is AOTAutograd's responsibility, because AOTAutograd needs to see the set_grad_enabled to accurately do autograd, which means it must be in the graph.

**Comment by jon-chuang** [comment]
> This is AOTAutograd's responsibility, because AOTAutograd needs to see the set_grad_enabled to accurately do autograd, which means it must be in the graph.

I think we agree it must be in the graph. 

But I think this issue is saying that we also need to track it as a side effect so that downstream eager code will benefit from the side effect.

**Comment by ezyang** [comment]
As an analogy, suppose we put a tensor mutation in the graph. Does dynamo need to track this mutation and manually reapply it? No, it's AOTAutograd's responsibility.

Dynamo and AOTAutograd have defined some contract for what is valid to put in the graph. Any side effects in the graph are no longer Dynamo's responsibility.

**Comment by jon-chuang** [comment]
Hmm, I see. Can AOTAutograd modify the compiled output to produce an eagermode epilogue? I guess the short answer is yes -  we already do this with in-place ops by introducing `copy_` epilogues.

**Comment by jon-chuang** [comment]
I'll try to tackle this, following a similar strategy to converting in-place mutation side-effects to `copy_`

**Comment by zou3519** [comment]
I agree with @ezyang's analysis. The way to look at it is that Dynamo is responsible for tracking and replaying side effects that it doesn't toss into the graph (for example, assigning to a global variable). AOTAutograd handles the things that are in the graph (copy_, and now, set_grad_enabled handling).
