### ISSUE TITLE
multiprocessing deadlocks

### ISSUE THREAD

**Issue by FuriouslyCurious** [pytorch/pytorch#1120]
I am experimenting with Soumith's imagenet example, but it is crashing or deadlocking in several ways.  I have added a bunch of "print" statements to it to figure out where it is crashing, and here is the GIST of full script: (as you can see, there are almost no significant modifications to the original code.)  All code is running on 2x NVidia Titan X 12 GB cards with 96 GB RAM. 

https://gist.github.com/FuriouslyCurious/81742b8126f07f919522a588147e6086

### Issue 1: transforms.Scale(512) fails in THCTensorMathBlas.cu:241

How to reproduce:   
1. Images are being fed with transforms.Scale(512)  or transforms.Scale(1024)  
2. Source images are 2048x2048.
3. Workers >= 1
4. Batchsize >= 2
5. Script will crash on its own in few minutes

Output
```
 python train.py -a resnet18 -j 1 -b 2 /home/FC/data/P/
=> Parsing complete...
=> creating model 'resnet18'
=> Using CUDA DataParallel
=> Starting training images loading...
=> Starting validation images loading...
=> Loss criterion and optimizer setup
=> Starting training...
=> Training Epoch 0
Traceback (most recent call last):
  File "train.py", line 299, in <module>
    main()
  File "train.py", line 140, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 177, in train
    output = model(input_var)
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 92, in forward
    outputs = self.parallel_apply(replicas, scattered, gpu_dicts)
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 102, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs)
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 50, in parallel_apply
    raise output
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 30, in _worker
    output = module(*input, **kwargs)
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/conda3/envs/idp/lib/python3.5/site-packages/torchvision-0.1.6-py3.5.egg/torchvision/models/resnet.py", line 150, in forward
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 54, in forward
    return self._backend.Linear()(input, self.weight, self.bias)
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/nn/_functions/linear.py", line 10, in forward
    output.addmm_(0, 1, input, weight.t())
RuntimeError: size mismatch at /data/users/soumith/miniconda2/conda-bld/pytorch-cuda80-0.1.10_1488757768560/work/torch/lib/THC/generic/THCTensorMathBlas.cu:241
```

### Issue 2: Multiple worker threads deadlock in index_queue.get() and waiter.acquire()

How to reproduce:   
1. Images are being fed with default crop: transforms.RandomSizedCrop(224) 
2. Source images are 2048x2048.
3. Workers > 2
4. Batchsize > 40
5. When you see GPU clock speed fall to resting MHz on NVidia-smi, script has deadlocked in waiter.acquire() and index_queue.get().  Abort the script manually.

```
python train.py -a resnet18 /home/FC/data/P
=> Parsing complete...
=> creating model 'resnet18'
=> Using CUDA DataParallel
=> Starting training images loading...
=> Starting validation images loading...
=> Loss criterion and optimizer setup
=> Starting training...
=> Training Epoch 0
^CProcess Process-4:
Process Process-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "train.py", line 299, in <module>
    main()
  File "train.py", line 140, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 168, in train
    for i, (input, target) in enumerate(train_loader):
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 168, in __next__
    idx, batch = self.data_queue.get()
  File "/conda3/envs/idp/lib/python3.5/queue.py", line 164, in get
    self.not_empty.wait()
  File "/conda3/envs/idp/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
Traceback (most recent call last):
  File "/conda3/envs/idp/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/conda3/envs/idp/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 26, in _worker_loop
    r = index_queue.get()
  File "/conda3/envs/idp/lib/python3.5/multiprocessing/queues.py", line 342, in get
    with self._rlock:
  File "/conda3/envs/idp/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/conda3/envs/idp/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/conda3/envs/idp/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 26, in _worker_loop
    r = index_queue.get()
```

### Issue 3: Single Worker thread hangs in threading.py:293 waiter.acquire()

How to reproduce:   
1. Images are being fed with NO crop or scale
2. Source images are 2048x2048.
3. Workers >= 1
4. Batchsize >= 1
5. When you see GPU clock speed fall to resting MHz on NVidia-smi, script has stalled in waiter.acquire().  Manually abort the script.

```
python train.py -a resnet152 -j 1 -b 1 /home/FC/data/P/
=> Parsing complete...
=> creating model 'resnet152'
=> Using CUDA DataParallel
=> Starting training images loading...
=> Starting validation images loading...
=> Loss criterion and optimizer setup
=> Starting training...
=> Training Epoch 0
^CTraceback (most recent call last):
  File "train.py", line 298, in <module>
    main()
  File "train.py", line 139, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 167, in train
    for i, (input, target) in enumerate(train_loader):
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 168, in __next__
    idx, batch = self.data_queue.get()
  File "/conda3/envs/idp/lib/python3.5/queue.py", line 164, in get
    self.not_empty.wait()
  File "/conda3/envs/idp/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by soumith** [comment]
thanks for the detailed issue, this really helps. We'll try to reproduce this with 2048x2048 images.

How many 2048x2048 images are in your dataset?

**Comment by FuriouslyCurious** [comment]
Hi Soumith, 

I am using a toy dataset with 3 classes and 285 training images, 100 val images.  I opened a copy in PyTorch/examples directory because I was not sure if it is a core PyTorch issue or merely an examples issue.

**Comment by soumith** [comment]
thanks. I'll treat this as a core issue. If I cant reproduce it, I'll ask for more details.

Can you post your outputs of:

print(torch.__version__)

output of the command: nvidia-smi

Thanks.

**Comment by FuriouslyCurious** [comment]
print(torch.version)
```
>>> print(torch.version)
<module 'torch.version' from '/conda3/envs/idp/lib/python3.5/site-packages/torch/version.py'>
>>> quit()
$ cat /conda3/envs/idp/lib/python3.5/site-packages/torch/version.py
__version__ = '0.1.10+ac9245a'
```

nvidia-smi output:

```
Tue Mar 28 01:14:28 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 378.13                 Driver Version: 378.13                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 0000:02:00.0     Off |                  N/A |
| 26%   45C    P8    17W / 250W |      0MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    Off  | 0000:03:00.0     Off |                  N/A |
| 23%   39C    P8    16W / 250W |      0MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I also have a Docker image of the environment if you have trouble reproducing the issue.  Thanks!

**Comment by FuriouslyCurious** [comment]
If you need a copy of my environment image: 

Pull the Docker image (11 Gigs):
`https://hub.docker.com/r/nirajvara/4dlxen/`

After running the image, activate environment by running:
`source /conda3/envs/idp/bin/activate idp `

**Comment by soumith** [comment]
thanks.

If you are running via docker, are you making sure that you have enough free shared memory by passing the flag `--ipc=host` to `nvidia-docker run`? We mention this here: https://github.com/pytorch/pytorch#docker-image

**Comment by FuriouslyCurious** [comment]
Hi Soumith,

Yes, nvidia-docker is running the image with '--ipc=host' setting on local machine, but still producing the errors above.

**Comment by ngimel** [comment]
1. If you are changing input size, you should also change corresponding model definition. Models in torchvision are for a particular input size (299x299 for inception_v3, 224x224 for everything else).
2,3 looks like either insufficient shared memory or insufficient RAM issue.

**Comment by FuriouslyCurious** [comment]
I am already experimenting with changing input sizes in Amos's DenseNet implementation.  Let me run some experiments and report back.

**Comment by FuriouslyCurious** [comment]
PS: Where are the resnet and other models stored?  I search PyTorch locations for *resnet* even *vgg* and can't find any files with those names inside PyTorch.

**Comment by vadimkantorov** [comment]
I think it's `~/.torch` by default

**Comment by soumith** [comment]
I've looked into this briefly, and @ngimel 's analysis seems correct.
Since this is not a bug, please have follow-up discussions on https://discuss.pytorch.org/

**Comment by FuriouslyCurious** [comment]
Thanks @soumith and @vadimkantorov   I cannot find model definitions on local disk under ~/.torch and a full disk search for "resnet" only shows model_zoo.py.  Any idea where can I find them by default?

**Comment by FuriouslyCurious** [comment]
For future reference: In case someone stumbles upon this issue through Google, here is a pointer on how to feed high res images to model zoo models:

https://discuss.pytorch.org/t/how-do-i-feed-higher-res-images-to-model-zoo-models/1442/2

**Comment by zym1010** [comment]
@FuriouslyCurious I wonder if you have encountered similar issues as mine (pytorch/examples#148) for your Issues 2 & 3.
