### ISSUE TITLE
csrc/api folder not found

### ISSUE THREAD

**Issue by SorinaStoian** [pytorch/pytorch#11214]
## Issue description

I tried to build pytorch on both Windows 8.1 and Windows 10, but when I tried to use csrc api(e.g #include <torch/crsc/api/nn/modules/linear.h>) I found out that csrc/api folder does not exist where pytorch is installed, even though it exists where I cloned the source code. I assume I didn't build pytorch correctly.

In order to install pytorch, I followed the steps described here: https://github.com/pytorch/pytorch and the last commit was fa5d95a00c4212381cd9ef4ee26cabad294ee8e0 when I cloned pytorch.
I set the following env variables: NO_CUDA=1 and FULL_CAFFE2=1 and I built it using an anaconda environment.

At first, I tried to run an example which computes the sum of two tensors, but I received these errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: struct at::Type & __thiscall at::TensorImpl::type(void)const " (__imp_?type@TensorImpl@at@@QBEAAUType@2@XZ)	Project1	C:\Users\user1\source\repos\Project1\Project1\Source.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "__declspec(dllimport) class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl at::print(class std::basic_ostream<char,struct std::char_traits<char> > &,struct at::Tensor const &,__int64)" (__imp_?print@at@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AAV23@ABUTensor@1@_J@Z)	Project1	C:\Users\user1\source\repos\Project1\Project1\Source.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "__declspec(dllimport) private: static struct at::UndefinedTensor at::UndefinedTensor::_singleton" (__imp_?_singleton@UndefinedTensor@at@@0U12@A)	Project1	C:\Users\user1\source\repos\Project1\Project1\Source.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "__declspec(dllimport) struct at::Tensor __cdecl at::native::tensor(class at::ArrayRef<int>,struct at::TensorOptions const &)" (__imp_?tensor@native@at@@YA?AUTensor@2@V?$ArrayRef@H@2@ABUTensorOptions@2@@Z)	Project1	C:\Users\user1\source\repos\Project1\Project1\Source.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: struct at::TensorOptions & __thiscall at::TensorOptions::dtype(enum at::ScalarType)" (__imp_?dtype@TensorOptions@at@@QAEAAU12@W4ScalarType@2@@Z)	Project1	C:\Users\user1\source\repos\Project1\Project1\Source.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __thiscall at::TensorOptions::TensorOptions(void)" (__imp_??0TensorOptions@at@@QAE@XZ)	Project1	C:\Users\user1\source\repos\Project1\Project1\Source.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: static struct at::UndefinedTensor * __cdecl at::UndefinedTensor::singleton(void)" (__imp_?singleton@UndefinedTensor@at@@SAPAU12@XZ)	Project1	C:\Users\user1\source\repos\Project1\Project1\Source.obj	1	

## Code example

#include <torch/torch.h>

int main() {

	auto a = at::tensor({ 1, 2 });
	auto b = at::tensor({ 2, 3 });
	auto c = a * b;
	std::cout << c << std::endl;

	return 0;
}

## System Info
- PyTorch or Caffe2:PyTorch
- How you installed PyTorch (conda, pip, source):source
- Build command you used (if compiling from source):python setup.py install
- OS:Windows 10 x64 and Windows 8.1 Pro x64
- PyTorch version: master(last commit was fa5d95a00c4212381cd9ef4ee26cabad294ee8e0)
- Python version:3.7.0
- CUDA/cuDNN version:None(CPU build)
- GPU models and configuration:None
- GCC version (if compiling from source):MSVC 14.11.25503
- CMake version:3.12.0
- Anaconda version: 4.5.10

**Comment by SsnL** [comment]
cc @goldsborough

**Comment by goldsborough** [comment]
Hey, thanks for reporting this. I haven't personally tried using the C++ API on Windows yet, but was planning on doing so in the next couple weeks. . In this case you may be missing an include path pointing at `torch/csrc/api/include` so that  `torch/torch.h` resolves correctly.

For building, we will soon (by end of month) provide `.zip` archives you can download that contain all relevant headers and shared libraries, which means you won't have to build PyTorch from source to use the C++ API. For now, I would recommend using `tools/build_libtorch.py` in such a manner:

```
cd pytorch
mkdir cpp-build
cd cpp-build
python ../tools/build_libtorch.py
```

This should produce a libtorch DLL that you can use. If that doesn't work, we will fix it.

This process will become a lot smoother very soon -- the C++ API isn't officially released yet so it's a bit rough right now :)

**Comment by SorinaStoian** [comment]
Hello, 

Thanks for answering on a such a short notice. 
I tried to follow the steps you recommended, but build_libtorch.py is missing. Below you can find the content of tools/ :
`
amd_build
aten_mirror.sh
autograd
build_pytorch_libs.bat
build_pytorch_libs.sh
clang_tidy.py
convert.vim
cpp_build
cwrap
docker
2,635 download_mnist.py
gen_onnx.sh
jit
nnwrap
pytorch.version
setup_helpers
shared
test_aten_install.sh
__init__.py
__pycache__
`

Are there any new changes that I should pull?
Also, I want to mention that I have a DLL named "torch.dll" and torch/torch.h is resolved correctly.

Kind regards,
Sorina

**Comment by AshwinAKannan** [comment]
> For building, we will soon (by end of month) provide `.zip` archives you can download that contain all relevant headers and shared libraries, which means you won't have to build PyTorch from source to use the C++ API.

Hello,

Here’s my simple cpp code that just loads the model. I’m trying to compile this code in Windows 7, VS 2017. I’ve downloaded libtorch and included path to libtorch/include to C++ include dirs & libtorch/lib to linker

```
#define _CRT_SECURE_NO_WARNINGS
#include "torch/script.h"
#include <iostream>
#include <memory>
#include <fstream>


#include <stdint.h>
#include <vector>

typedef unsigned char BYTE;

using namespace std;

int main(int argc, const char* argv[]) {

if (argc != 3) {
std::cerr << "usage: example-app &lt;path-to-exported-script-module&gt; &lt;path-to-bin-file&gt;\n";
return -1;

}

std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(argv[1]);
return 0;
}
```

I run into errors similar to ones mentioned above:
```

Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: __cdecl c10::IValue::~IValue(void)" (__imp_??1IValue@c10@@QEAA@XZ)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: __cdecl c10::IValue::IValue(void)" (__imp_??0IValue@c10@@QEAA@XZ)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: __cdecl c10::IValue::IValue(struct c10::IValue const &amp;)" (__imp_??0IValue@c10@@QEAA@AEBU01@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: __cdecl c10::Error::Error(struct c10::SourceLocation,class std::basic_string&lt;char,struct std::char_traits&lt;char&gt;,class std::allocator&lt;char&gt; &gt; const &amp;)" (__imp_??0Error@c10@@QEAA@USourceLocation@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: __cdecl c10::Error::Error(class c10::Error const &amp;)" (__imp_??0Error@c10@@QEAA@AEBV01@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: __cdecl at::Tensor::~Tensor(void)" (__imp_??1Tensor@at@@QEAA@XZ)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: __cdecl at::Tensor::Tensor(class at::Tensor const &amp;)" (__imp_??0Tensor@at@@QEAA@AEBV01@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: void __cdecl c10::ThreadPool::workOnTasksUntilCompleted(class c10::intrusive_ptr&lt;struct c10::ivalue::Future,struct c10::detail::intrusive_target_default_null_type&lt;struct c10::ivalue::Future&gt; &gt;)" (__imp_?workOnTasksUntilCompleted@ThreadPool@c10@@QEAAXV?$intrusive_ptr@UFuture@ivalue@c10@@U?$intrusive_target_default_null_type@UFuture@ivalue@c10@@@detail@3@@2@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: virtual __cdecl c10::Error::~Error(void)" (__imp_??1Error@c10@@UEAA@XZ)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: struct c10::IValue &amp; __cdecl c10::IValue::operator=(struct c10::IValue const &amp;)&amp; " (__imp_??4IValue@c10@@QEGAAAEAU01@AEBU01@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: struct c10::IValue &amp; __cdecl c10::IValue::operator=(struct c10::IValue &amp;&amp;)&amp; " (__imp_??4IValue@c10@@QEGAAAEAU01@$$QEAU01@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) public: class at::Tensor &amp; __cdecl at::Tensor::operator=(class at::Tensor const &amp;)&amp; " (__imp_??4Tensor@at@@QEGAAAEAV01@AEBV01@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) protected: __cdecl c10::intrusive_ptr_target::intrusive_ptr_target(void)" (__imp_??0intrusive_ptr_target@c10@@IEAA@XZ)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) protected: __cdecl c10::intrusive_ptr_target::intrusive_ptr_target(class c10::intrusive_ptr_target const &amp;)" (__imp_??0intrusive_ptr_target@c10@@IEAA@AEBV01@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) protected: __cdecl c10::intrusive_ptr_target::intrusive_ptr_target(class c10::intrusive_ptr_target &amp;&amp;)" (__imp_??0intrusive_ptr_target@c10@@IEAA@$$QEAV01@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) protected: virtual __cdecl c10::intrusive_ptr_target::~intrusive_ptr_target(void)" (__imp_??1intrusive_ptr_target@c10@@MEAA@XZ)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) protected: class c10::intrusive_ptr_target &amp; __cdecl c10::intrusive_ptr_target::operator=(class c10::intrusive_ptr_target const &amp;)" (__imp_??4intrusive_ptr_target@c10@@IEAAAEAV01@AEBV01@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) protected: class c10::intrusive_ptr_target &amp; __cdecl c10::intrusive_ptr_target::operator=(class c10::intrusive_ptr_target &amp;&amp;)" (__imp_??4intrusive_ptr_target@c10@@IEAAAEAV01@$$QEAV01@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) private: __cdecl caffe2::TypeIdentifier::TypeIdentifier(unsigned short)" (__imp_??0TypeIdentifier@caffe2@@AEAA@G@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) private: virtual void __cdecl c10::intrusive_ptr_target::release_resources(void)" (__imp_?release_resources@intrusive_ptr_target@c10@@EEAAXXZ)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) class std::shared_ptr&lt;struct torch::jit::script::Module&gt; __cdecl torch::jit::load(class std::basic_string&lt;char,struct std::char_traits&lt;char&gt;,class std::allocator&lt;char&gt; &gt; const &amp;,class c10::optional&lt;struct c10::Device&gt;)" (__imp_?load@jit@torch@@YA?AV?$shared_ptr@UModule@script@jit@torch@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@V?$optional@UDevice@c10@@@c10@@@Z)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK2001|unresolved external symbol "__declspec(dllimport) class c10::ThreadPool &amp; __cdecl c10::global_work_queue(void)" (__imp_?global_work_queue@c10@@YAAEAVThreadPool@1@XZ)|pytorch_cpp_test|D:\User\pytorch_cpp_test\pytorch_cpp_test\pytorch_cpp_test.obj|1||
|Error|LNK1120|22 unresolved externals|pytorch_cpp_test|D:\User\pytorch_cpp_test\x64\Release\pytorch_cpp_test.exe|1||
```

Any help would be greatly appreciated. Thanks in advance! :slight_smile:

**Comment by soumith** [comment]
(closing because we have been shipping libtorch binaries for a while)

**Comment by AshwinAKannan** [comment]
Sorry, I wasn't clear. I am using the libtorch binary (https://download.pytorch.org/libtorch/cu100/libtorch-win-shared-with-deps-latest.zip), yet I run into these errors. Any idea what I could be doing wrong. Thanks

**Comment by soumith** [comment]
@peterjc123 any ideas why VS2017 doesn't work?

**Comment by AshwinAKannan** [comment]
> @peterjc123 any ideas why VS2017 doesn't work?

"You will need to add the library torch.lib in the linking configuration explicitly.".. This was the solution. @peterjc123 help me out in PyTorch forums. Thanks :) This issue can be closed.

**Comment by justanhduc** [comment]
FYI, in my case, there was a linker error related to autograd symbol. I solved it by adding `torch_python.lib` to the project.
