### ISSUE TITLE
Weird memory leakage in /= division operator

### ISSUE THREAD

**Issue by MilkClouds** [pytorch/pytorch#112173]
### 🐛 Describe the bug

If I put `image_features /= image_features.norm(dim=-1, keepdim=True)`, I get a memory leak, and if I don't put it, and even if I put `image_features = image_features / image_features.norm(dim=-1, keepdim=True)` instead, I don't get a leak. I'm wondering if this is intended, if it's already been reported, and what the cause is.

Below is code that fully reproduces the memory leak.

```python
import nvidia_smi
import torch
from tqdm.auto import tqdm


def memory():
    nvidia_smi.nvmlInit()
    deviceCount = nvidia_smi.nvmlDeviceGetCount()
    freem = []
    for i in range(deviceCount):
        handle = nvidia_smi.nvmlDeviceGetHandleByIndex(i)
        info = nvidia_smi.nvmlDeviceGetMemoryInfo(handle)
        freem.append(100 * info.free / info.total)
    nvidia_smi.nvmlShutdown()
    return freem


class MyToyPytorchModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(3, 1408)
        self.to("cuda")

    def forward(self, image_features):
        reward = self.linear(image_features)
        return reward


def f():
    if getattr(f, "model", None) is None:
        f.model = MyToyPytorchModel()
    model = f.model
    inputs = torch.randn(2, 3).to("cuda")
    image_features = model(inputs)
    image_features /= image_features.norm(dim=-1, keepdim=True)  # memory leak
    # image_features = image_features / image_features.norm(dim=-1, keepdim=True) # no memory leak
    reward = (image_features[0] * image_features[1:]).sum(-1)
    return reward.detach().cpu().numpy()


with tqdm(range(10**6)) as pbar:
    for _ in pbar:
        pbar.set_postfix({"reward": f(), "memory": memory()})
```

### Versions

PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.27.2
Libc version: glibc-2.31

Python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-255
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7742 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         3209.092
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4491.44
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-15,128-143
NUMA node1 CPU(s):               16-31,144-159
NUMA node2 CPU(s):               32-47,160-175
NUMA node3 CPU(s):               48-63,176-191
NUMA node4 CPU(s):               64-79,192-207
NUMA node5 CPU(s):               80-95,208-223
NUMA node6 CPU(s):               96-111,224-239
NUMA node7 CPU(s):               112-127,240-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.1
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] numpy                     1.25.1                   pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchaudio                2.0.2                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by tringwald** [comment]
Interesting find. I can reproduce this on a fresh main build with an even shorter script:

```python3
import torch

model = torch.nn.Linear(4, 1024).cuda()

for i in range(10 ** 6):
    inputs = torch.randn(2, 4).to("cuda")
    image_features = model(inputs)
    image_features /= image_features.norm(dim=-1, keepdim=True)
```

**Comment by MilkClouds** [comment]
yes, it is. It occurs only when the tensor which is requires_grad=True being `/=` (itruediv) operated.

**Comment by tringwald** [comment]
I don't think it's related to the `/=` operator, because `+=` exhibits the same behavior. Interestingly enough, only for certain functions:

```python3
import torch

model = torch.nn.Linear(4, 1024).cuda()
leak = False

for i in range(10 ** 6):
    inputs = torch.randn(2, 4).to("cuda")
    x = model(inputs)
    if leak:
        print("\rpow", end='')
        x += torch.pow(x, 2)
    else:
        print("\rsqrt", end='')
        x += torch.sqrt(x)
```

`torch.pow` leaks memory (`torch.erf` too), but `torch.sqrt` doesn't.

**Comment by ezyang** [comment]
This is expected. When you do division, the gradient formula must retain the original input tensor. So you are continuously retaining more and more saved tensors as you repeatedly apply inplace division, because the autograd graph still needs to track these ops.

**Comment by MilkClouds** [comment]
No, I think it is not intended since it's natural to gc of python discard all unused variable. If it is intended that it preserves computation graph and gradient, non-inplace computation also should occur "memory leaking".
