### ISSUE TITLE
Neural Module Network workload in pyTorch

### ISSUE THREAD

**Issue by xhzhao** [pytorch/pytorch#1121]
@soumith Good to know that  pyTorch supports dynamic graph. Our team is working on a workload called [NMN](https://github.com/jacobandreas/nmn2) which is implemented in [ApolloCaffe](https://github.com/jacobandreas/apollocaffe). As far as i know, the NMN model need to build a new model in every iteration according to the input questions , and we think that this workload is very suitable for pyTorch to demonstrate the flexibility of the dynamic graph.

Do you guys have any schedule to implement this NMN workload in pyTorch?
Do you think there is any dependency to be resolved in pyTorch if we want to do it?
Any suggestion would be great for us.
Thanks

**Comment by soumith** [comment]
we do not plan to implement NMN in pytorch, if you want you can implement it yourself :)

We gave you all the tools in pytorch to build it, now go have fun.

> Do you think there is any dependency to be resolved in pyTorch if we want to do it?
I am not sure what you mean by dependency to be resolved.

**Comment by jekbradbury** [comment]
Here's a very well-written implementation of an NMN-based model (from Justin Johnson and FAIR) https://github.com/facebookresearch/clevr-iep

**Comment by xhzhao** [comment]
@jekbradbury Thanks very much, and good to know this new paper for VQA.

**Comment by HarshTrivedi** [comment]
Just in case someone is still looking for original NMN paper implementation in PyTorch, here is my attempt on it: https://github.com/HarshTrivedi/nmn-pytorch. I am planning to add much more documentation in following 2 weeks to reproduce the results.
