### ISSUE TITLE
~ Docathon H2 2023 ~

### ISSUE THREAD

**Issue by svekars** [pytorch/pytorch#112176]
We have a large backlog of issues that we want to address and it's a great opportunity for you to start contributing to PyTorch. We have limited this docathon to the [pytorch/pytorch](https://github.com/pytorch/pytorch) and [pytorch/tutorials](https://github.com/pytorch/tutorials) repositories, so please work on the issues from these two repositories.

**NOTE:** This issue outlines the work in the pytorch/pytorch repo. If you'd prefer to work on the PyTorch tutorials, please go to the [pytorch/tutorials Docathon issue](https://github.com/pytorch/tutorials/issues/2624).

# Date and location
**WHEN:** The docathon starts on November 1st 10 AM PST. Please do not work on tasks until then. We will continue accepting new submissions until 5 PM PST on November 12th.
**WHERE:** Virtual
**WHAT:** Issues with the docathon-h2-2023 label - will be posted on **November 1st**.

**Watch the docathon kick-off video for more details:**

[![Watch the docathon kick-off video](https://github-production-user-asset-6210df.s3.amazonaws.com/5317992/279740684-0ffc1faa-9358-426a-a23b-8563ff33a6bb.png)](https://youtu.be/IhTjsRKqjtA)

# Can everyone participate?
We encourage everyone to consider participating in the docathon but there are a few things we expect from the participants:
- You must have a GitHub account and know how to use Git and GitHub, how to submit or rebase your PR on the latest main branch, how to fork or clone the repo, how to view errors in the CI and troubleshoot. We reserve the right to reject incorrectly submitted PRs.
- You must be familiar with Python, the basics of Machine Learning, and have at least a basic knowledge of PyTorch. Familiarity with Sphinx, sphinx-gallery, and reStructuredText is a plus.
# What contributions are we looking for?
All issues for this docathon are tagged with the **docathon-h2-2023** label. Please note that contributions that address other issues won't be counted. We are primarily looking for the following contributions: 
* Docstring fixes in the [pytorch/pytorch](https://github.com/pytorch/pytorch) repo tagged with the docathon-h2-2023 label - see the list [here](https://github.com/pytorch/pytorch/issues?q=is%3Aopen+is%3Aissue+label%3Adocathon-h2-2023).
* Tutorial fixes in the [pytorch/tutorials](https://github.com/pytorch/tutorials) repo, see the Docathon issue in the pytorch/tutorials repo for details - see the list [here](https://github.com/pytorch/tutorials/issues?q=is%3Aissue+is%3Aopen+label%3Adocathon-h2-2023).

Before you start contributing make sure to read [Linux Foundation Code of Conduct](https://events.linuxfoundation.org/about/code-of-conduct/).

**NOTE:** Due to the large number of RSVPs, the tasks are provided on a first come first serve basis — please don't hoard the tasks!
# Difficulty Levels
The issues have three levels of difficulty: easy, medium, and advanced. If this is your first time contributing to PyTorch, we recommend that you start with an issue with a lower difficulty level .
# How to contribute to pytorch/pytorch?

1. Read the [PyTorch contributor wiki ](https://github.com/pytorch/pytorch/wiki)for general guidelines on how the submission process works and overall style and voice. 
2. Pick an issue that is labeled as **docathon-h2-2023** and post an **/assigntome** comment to assign the issue to yourself.  If the issue is already assigned or someone requested it to be assigned, please find another issue to work on. We ask that you assign one issue at a time - we want to give everyone a fair chance to participate. When you are done with one issue and get it approved, you can assign another one to yourself and start working on it.
3. Fork or clone the PyTorch repository to your computer. 
4. Create a branch and work on the fix, then submit your PR..

# Submit Your PR
1. Submit your PR–tagged with the issue you've picked–against the main branch. Tag the issue you are fixing and add the **docathon-h2-2023** label. For example:
   <img width="1058" alt="docathon-h2-2023-submit-issue" src="https://github.com/pytorch/pytorch/assets/5317992/d60e22f0-c332-4992-b9e4-fb071b5660d2">

3. If you have not yet, sign the Contributor License Agreement (CLA) - prompted as a check in the PR. **We can't accept any PRs without a signed CLA**.
4. Watch for any CI errors and fix as needed - all checks must pass successfully. 
5. The reviewers might provide feedback that we expect you to address.
6. When all feedback is addressed and your PR is approved - one of the reviewers will merge your PR. 
# Can I partner with someone to work on an issue?
Although most of the issues should be possible to address on your own, you may decide to partner with someone. You can find someone to work with on our Slack channel by posting a free-form request to collaborate. One individual from the group can submit a PR referring others as co-authors by specifying their GitHub usernames in the commit message like this:
```
Co-authored-by: NAME <NAME@EXAMPLE.COM>
Co-authored-by: ANOTHER-NAME <ANOTHER-NAME@EXAMPLE.COM>
 ```
Depending on the complexity of the issue, we reserve the right to decline contributions from multiple co-authors for trivial issues like fixing formatting, broken links, or very small code changes. For all issues, please, limit the number of co-authors to two. 
# Top contributors recognition
For all contributions addressing the docathon-h2-2023 issues merged to the main branch in [pytorch/pytorch](https://github.com/pytorch/pytorch) or [pytorch/tutorials](https://github.com/pytorch/tutorials) repos during the period from November 1 to November 15, 2023, you will get a special PyTorch GitHub badge. The issues will be released on the first day of the docathon. The top contributors will receive additional recognition and will be featured in a PyTorch social media announcement.

# Questions?
You can post your questions here.

cc @carljparker

**Comment by moghadas76** [comment]
All of the issues have been taken!!! @svekars

**Comment by svekars** [comment]
> All of the issues have been taken!!! @svekars

@moghadas76 I just created a few more to work on. Feel free to grab one.

**Comment by psetinek** [comment]
Hi @svekars 
Are you planning to release more issues for the docathon in the next days? Currently, all the issues are already assigned:(

**Comment by Skylion007** [comment]
For people working on pydocstyle issues, I encourage using ruff to autofix as many of the issues as possible. `ruff --select RULECODE --fix path_to_file` should fix a lot of tedious issues. List of implemented pydocstyle rules and autofixes can be found here: https://docs.astral.sh/ruff/rules/#pydocstyle-d
