### ISSUE TITLE
What has to be done to add a Operation

### ISSUE THREAD

**Issue by sparkecho** [pytorch/pytorch#11212]
Hi there, when I was viewing source code. I found this comment:
https://github.com/pytorch/pytorch/blob/0d5e4a2c66816e42d084f23ee94575357460cdf8/aten/src/ATen/function_wrapper.py#L2

But I can't find any document in this project explains it nor can't find any resource has similar tittle on the internet. Only https://pytorch.org/docs/stable/notes/extending.html has a relativity of it.

Where can I found the content or what should this line correct to?
Thanks a lot.

**Comment by zou3519** [comment]
It's right here:
https://github.com/pytorch/pytorch/blob/0d5e4a2c66816e42d084f23ee94575357460cdf8/aten/src/ATen/function_wrapper.py#L34

**Comment by sparkecho** [comment]
@zou3519  Thank you so much, it's my mistake that ignored the occurrence in the same file. Out of extinct I tried to find it in other place.
