### ISSUE TITLE
Trilinear gradient does not match bilinear on bfloat16

### ISSUE THREAD

**Issue by PeterL1n** [pytorch/pytorch#112299]
### 🐛 Describe the bug

Trilinear (1, 2, 2) should be equivalent to bilinear (2, 2), but the gradients differs on bfloat16

```python
import torch

dtype = torch.bfloat16

a = torch.randn([1, 3, 1, 2, 2], device="cuda", dtype=dtype, requires_grad=True)
b = a.detach()[:, :, 0].clone().requires_grad_(True)

c = torch.nn.functional.interpolate(a, scale_factor=(1, 2, 2), mode="trilinear")
d = torch.nn.functional.interpolate(b, scale_factor=2, mode="bilinear")

torch.nn.functional.mse_loss(c, torch.zeros_like(c)).backward()
torch.nn.functional.mse_loss(d, torch.zeros_like(d)).backward()

print((a.grad[:, :, 0] - b.grad))
```

Result:
```
tensor([[[[ 0.0000,  0.0005],
          [-0.0002,  0.0000]],

         [[ 0.0000,  0.0000],
          [ 0.0005,  0.0000]],

         [[ 0.0000,  0.0000],
          [ 0.0000, -0.0010]]]], device='cuda:0', dtype=torch.bfloat16)
```

There is no issue on float32 and float16, only bfloat16 has issue. Tested on A100 GPU

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.4.56.bsk.11-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB

Nvidia driver version: 470.129.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         3600.014
BogoMIPS:                        5999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] byted-torch==2.1.0.post0
[pip3] byted-torch-monitor==0.0.1
[pip3] numpy==1.26.1
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0+cu121
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] Could not collect

**Comment by Chillee** [comment]
This seems expected. Bfloat16 only has 8-bits of mantissa, which means that around 1, the next biggest value it can represent is `1.0078`.

You can test this by doing
```
x = torch.randn(200, dtype=torch.float16)
(x - x.to(torch.bfloat16)).abs().max()
>>> tensor(0.0059, device='cuda:0')
```

So the errors you're seeing seem totally expected :)

**Comment by zou3519** [comment]
Closing as expected behavior
