### ISSUE TITLE
[ONNX] Expose the graph module in torch.onnx ExportOutput

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#112218]
### 🚀 The feature, motivation and pitch

It is usually useful to look at the fx graph when exploring the exported ONNX result. It would be nice to expose the graph module in `torch.onnx.dynamo_export` ExportOutput like the `ExportedProgram` does.

cc @BowenBao @thiagocrepaldi

**Comment by MaanavD** [comment]
@justinchuby is this closed with #113581 ?

**Comment by justinchuby** [comment]
> @justinchuby is this closed with #113581 ?

Unfortunately not. The PR was closed w/o being merged.

**Comment by thiagocrepaldi** [comment]
My understanding from discussion at #113581 is that the SARIF option is enough to get the graph module
