### ISSUE TITLE
[dynamo] we do not instantiate guards for ambient autocast mode

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#112260]
### 🐛 Describe the bug

This might be ok-ish if all code is compiled, but for eager code in the graph module this may break. Similar to https://github.com/pytorch/pytorch/issues/112072

https://github.com/pytorch/pytorch/blob/63c089b09de42fff67f7ad7ae410669ae0880e1f/torch/csrc/dynamo/guards.cpp#L434

### Solutions
This needs to be guarded.

### Notes
- unlike: grad mode, which is 
    - guarded
    - an in-graph mutation that needs to be turned into a side-effect
- the situation here is reversed - ambient autocast is
    - not guarded
    - in-graph autocast ctx is at least in theory guaranteed to be localized to the graph (exits within the lifetime of the graph)

May be part of the root cause for https://github.com/pytorch/pytorch/issues/112164

This is particularly problematic for FSDP because there is autocast-dependent eager code in FSDP hooks to my understanding (to make decisions about activation/gradient comm dtype/compression).

### Additional Details

That any in-graph autocast exits within the lifetime of the graph should be verified:
1. enforce that autocast manager always exits within the traced graph, or 
2. we need to handle side-effects as we intend to do for `set_grad_enabled` (as there is a mutating API - `set_autocast_enabled` etc)

### Repro
```python
weights = torch.randn(10, 10, device="cuda")

def mod(x):
    return torch.mm(x, weights)

opt_inductor = torch.compile(mod, backend="inductor")
opt_eager = torch.compile(mod, backend="eager")
x = torch.randn(1, 10, device="cuda")

with torch.autocast('cuda', torch.float16):
    ref = mod(x)
    res = opt_inductor(x)
    res_eager = opt_eager(x)

print(ref.dtype, res.dtype, res_eager.dtype)  # float16, float16, float16

with torch.autocast('cuda', torch.bfloat16):  # No recompilation
    ref = mod(x)
    res = opt_inductor(x)
    res_eager = opt_eager(x)

print(ref.dtype, res.dtype, res_eager.dtype)  # bfloat16, float16, bfloat16
```

### Versions

main

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @bdhirsh @zou3519 @aakhundov wrt https://github.com/pytorch/pytorch/pull/103024

**Comment by jon-chuang** [comment]
Generally we need much better testing for torch.compile + set_grad / autocast.

**Comment by jon-chuang** [comment]
Dynamo IMO incorrectly constant folds 
```
torch.get_autocast_gpu_dtype,
torch.is_autocast_cache_enabled,
torch.is_autocast_cpu_enabled,
torch.is_autocast_enabled,
```
even though none of these values are guarded.

**Comment by jon-chuang** [comment]
@ezyang @voznesenskym @Chillee could you guys advise on whether it would be preferred to:
1. recompile if the ambient autocast mode changes
2. do not recompile, and restore the ambient autocast when recompiling (due to other guard failure) similar to for compile configs https://github.com/pytorch/pytorch/issues/110682

I really can't say; both look quite reasonable to me, but 2. is more consistent with https://github.com/pytorch/pytorch/issues/110682

**Comment by jon-chuang** [comment]
> torch.get_autocast_gpu_dtype,
torch.is_autocast_cache_enabled,
torch.is_autocast_cpu_enabled,
torch.is_autocast_enabled,

> Dynamo IMO incorrectly constant folds
> 
> ```
> torch.get_autocast_gpu_dtype,
> torch.is_autocast_cache_enabled,
> torch.is_autocast_cpu_enabled,
> torch.is_autocast_enabled,
> ```
> 
> even though none of these values are guarded.
> 
> We _can_ constant fold these, but they need to be guarded.

Actually, none of these should be constant folded. They should take the real value that is live at that point in the dynamo program.

**Comment by williamwen42** [comment]
Still repros
