### ISSUE TITLE
[dynamo] standard_test() is buggy

### ISSUE THREAD

**Issue by int3** [pytorch/pytorch#112230]
I noticed this while trying to add types to `torch/_dynamo/testing.py`. This line always throws an error due to the call being passed the wrong number of arguments:

https://github.com/pytorch/pytorch/blob/94e90c199c6abb188d1d86244621b9e94e43598c/torch/_dynamo/testing.py#L255

However, fixing that causes tests to fail, because this line was previously never executed:

https://github.com/pytorch/pytorch/blob/94e90c199c6abb188d1d86244621b9e94e43598c/torch/_dynamo/testing.py#L258

I'm not sure whether the test failures are bogus.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by williamwen42** [comment]
Test failures are bogus - a lot of tests in `test_functions.py` fail because the number of ops dynamo outputs is now different than what `fx.symbolic_trace` outputs, and this seems to be ok. I'm going to remove this part of `standard_test`.

cc @jansel
