### ISSUE TITLE
PyTorch is shipped with different versions on NCCL

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#112285]
### 🐛 Describe the bug

I.e. if PyTorch is installed from PyPI, it is shipped with NCCL-2.18.1, but if installed from download.pytorch.org, then version would be 2.18.5:
```
$  pip uninstall torch; pip install torch
$ python -c "import torch;print(torch.__version__, torch.cuda.nccl.version())"
2.1.0+cu121 (2, 18, 1)
$ pip uninstall torch; pip install torch --index-url https://download.pytorch.org/whl/cu118
python -c "import torch;print(torch.__version__, torch.cuda.nccl.version())"
2.1.0+cu118 (2, 18, 5)
```

And with nightlies it's even worth, as large wheels are compiled against 2.19.13, but small wheels are linked against same 2.18.1....

### Versions

2.1.0 / nightly

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @osalpekar @atalman

**Comment by malfet** [comment]
The technical challenge is that building small wheels is somewhat ugly:
  - CI/large wheels are build using `third_party/nccl` submodule
  - PyPI wheels are build against NCCL installed in `/usr/local/cuda` folder by https://github.com/pytorch/builder/blob/c5e331c0858e37fedc047707466161dfe0cadff6/common/install_cuda.sh#L69 ) and then linked using version specified in https://github.com/pytorch/pytorch/blob/ca2106e871efac9b6213c40d4f862d33813b7418/.github/scripts/generate_binary_build_matrix.py#L37

**Comment by atalman** [comment]
Looks like we can't move to 2.18.5 in small wheels since its not available https://pypi.org/project/nvidia-nccl-cu11/#history
Should we drop this issue from 2.1.1 milestones ?

**Comment by atalman** [comment]
Fixed by https://github.com/pytorch/builder/pull/1670
Validated using validation framework:
https://github.com/pytorch/builder/actions/runs/7463216572/job/20307417863#step:11:5182
and
https://github.com/pytorch/builder/actions/runs/7463216572/job/20307407032#step:11:4856

**Comment by atalman** [comment]
closing this issue - cherry-picked to release branch

**Comment by atalman** [comment]
Vlidated on final rc:
```
python -c "import torch; print(torch.__version__); print(torch.cuda.nccl.version())"
2.2.0+cu121
(2, 19, 3)
```
