### ISSUE TITLE
[dynamo] dead code - TracingContext.global_state

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#112316]
### 🐛 Describe the bug

As far as I can tell, while we go to great lengths to set and restore this CheckpointableGraphState, we never actually use it for anything nowadays, rather we rely on `GlobalStateGuard` state.

### Versions

Main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jon-chuang** [comment]
Actually it seems that `TracingContext` is used in at least one place - aotautograd when calling the `bw_compiler`. I'm just not clear if dynamo's output graph's is used for the TLS tracing context of aotautograd.

https://github.com/pytorch/pytorch/blob/919c9b713e65aa1489123259a0ce7e79322d4d9d/torch/_functorch/aot_autograd.py#L4046

**Comment by williamwen42** [comment]
What is the dead code you're referring to? `TracingContext` is used in a number of places, such as `output_graph.py`. There's also no field `global_state` in `TracingContext`.

**Comment by jon-chuang** [comment]
Yes, this is mistaken. TracingContext is used for many things, global_context is now used by https://github.com/pytorch/pytorch/pull/112396
