### ISSUE TITLE
Why is flake8 F821 disabled

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#112371]
Flake8 F821 "undefined name" is one of the most useful flake8 rules (see recent https://github.com/pytorch/pytorch/pull/112336 as an example).

Yet the rule is disabled:
https://github.com/pytorch/pytorch/blob/bbd5b935e49a54578ac88cb23ca962ab896a8c7a/.flake8#L10
https://github.com/pytorch/pytorch/blob/bbd5b935e49a54578ac88cb23ca962ab896a8c7a/pyproject.toml#L43

I think the rule needs to be at least selectively enabled. There are currently multiple actual issues in the codebase that can be caught by this rules.

**Comment by Skylion007** [comment]
My understanding is that it's mostly because of star imports and we never got around to enabling it. Feel free to enable it and fix the issues, happy to review any PRs from it.

**Comment by kit1980** [comment]
@Skylion007 star imports are actually covered by another rule, F405 "may be undefined, or defined from star imports".

**Comment by seemethere** [comment]
This has actually been disabled ever since we started using `flake8`, context: https://github.com/pytorch/pytorch/pull/866

**Comment by maya-undefined** [comment]
I started work on this. Having some issues with the local unit test failing. Will advise.
