### ISSUE TITLE
`set` of enums produces a graph break (no repro)

### ISSUE THREAD

**Issue by akihironitta** [pytorch/pytorch#112338]
### Error logs

```
Graph Count: 14
Graph Break Count: 13
Op Count: 18
Break Reasons:
  Break Reason 1:
    Reason: Sets with <class 'torch._dynamo.variables.constant.EnumVariable'> NYI
    User Stack:
      <FrameSummary file /home/akihiro/work/github.com/path/to/file.py, line 420 in func1
      <FrameSummary file /home/akihiro/work/github.com/path/to/file.py, line 157 in func2
  Break Reason 2:
    ...
```

### Minified repro

**I somehow cannot reproduce the graph break with this simple script**, but our code basically looks like this:

```python
import torch
from enum import Enum

class MyEnum(Enum):
    A = "a"
    B = "b"
    C = "c"

class SomeModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.my_enum = MyEnum.A
        self.linear = torch.nn.Linear(1, 1)

    def forward(self, x) -> torch.Tensor:
        if self.my_enum not in {MyEnum.A, MyEnum.B}:
            return x
        return self.linear(x)

x = torch.randn(1, 1)
model = SomeModel()
explain = torch._dynamo.explain(model)(x)
print(explain)
```

In our codebase, replacing the set of enums with a tuple of enums has resolved the graph break:

```diff
-        if self.my_enum in {SomeEnum.A, SomeEnum.B}:
+        if self.my_enum in (SomeEnum.A, SomeEnum.B):
```

> [!Note]
> I will try to provide a repro as soon as I can, but it'd be great if you could also help me produce the graph break!

### Versions

Collecting environment information...
PyTorch version: 2.2.0.dev20231028+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-1031-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         2499.998
BogoMIPS:                        4999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        4 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] mypy-boto3-s3==1.26.62
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.1.0
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.2.0.dev20231028+cu118
[pip3] torch_geometric==2.4.0
[pip3] torch-scatter==2.1.2
[pip3] torchdata==0.7.0
[pip3] torchmetrics==0.11.4
[pip3] torchtext==0.16.0
[pip3] triton==2.1.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-lightning         2.1.0                    pypi_0    pypi
[conda] pytorch-triton            2.1.0+6e4932cda8          pypi_0    pypi
[conda] torch                     2.2.0.dev20231028+cu118          pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torch-scatter             2.1.2                    pypi_0    pypi
[conda] torchdata                 0.7.0                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchtext                 0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @bdhirsh @zou3519 @aakhundov

**Comment by zou3519** [comment]
was fixed
