### ISSUE TITLE
In the func Tensor.to, how can I make privateuse lazy init

### ISSUE THREAD

**Issue by huihoaan** [pytorch/pytorch#112369]
### 🐛 Describe the bug

I’m using privateuse1 to add our backend. My customer find the following code is working in cuda, but not working in my backend.
Use `Tensor.to()` with device message which not has a index, for example "cuda". 
```
import torch
tensor_a  = torch.rand(2).to("cuda")
```
Privateuse1 uses the same logic but fails.
```
import torch
# assumption my device is privateuseone
import torch_privateuseone

tensor_a  = torch.rand(2).to("privateuseone")
```
Above code will fail with `impl->getDevice()` because of the lack of lazy_init for the privateuseone device.
https://github.com/pytorch/pytorch/blob/bbd5b935e49a54578ac88cb23ca962ab896a8c7a/aten/src/ATen/native/TensorConversions.cpp#L210-L216
cuda will init in `THPVariable_to`
https://github.com/pytorch/pytorch/blob/bbd5b935e49a54578ac88cb23ca962ab896a8c7a/tools/autograd/templates/python_variable_methods.cpp#L958-L980

Where I can add `privateuseone_init` is in my own `to_impl` after Dispatcher, but by then it was too late.  Any advice for this case?

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git7bcf7da
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (aarch64)
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.27

Python version: 3.8.17 (default, Jul  5 2023, 20:40:03)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-29-generic-aarch64-with-glibc2.26
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              192
On-line CPU(s) list: 0-191
Thread(s) per core:  1
Core(s) per socket:  48
Socket(s):           4
NUMA node(s):        4
Vendor ID:           0x48
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            24576K
NUMA node0 CPU(s):   0-47
NUMA node1 CPU(s):   48-95
NUMA node2 CPU(s):   96-143
NUMA node3 CPU(s):   144-191
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==2.1.0a0+git7bcf7da
[pip3] torch-npu==2.1.0+gitf565f75
[pip3] torchair==0.1
[pip3] torchvision==0.15.2
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] torch                     2.1.0a0+git7bcf7da          pypi_0    pypi
[conda] torch-npu                 2.1.0+gitf565f75          pypi_0    pypi
[conda] torchair                  0.1                      pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

**Comment by zou3519** [comment]
Is it possible to change PyTorch internals to always lazyinit privateuse1?

**Comment by ezyang** [comment]
The most straightforward fix is to generalize `cuda_lazy_init` into something that allows all devices to register some sort of lazy initialization. There may be a lot of changes needed but it should be mechanical. I'll accept PRs that do it.

**Comment by huihoaan** [comment]
> The most straightforward fix is to generalize `cuda_lazy_init` into something that allows all devices to register some sort of lazy initialization. There may be a lot of changes needed but it should be mechanical. I'll accept PRs that do it.

Thank you for your suggestion. My team will discuss how to modify it. And  submit a PR as soon aspossible.
