### ISSUE TITLE
Conversion of Caffe2 pbtxt

### ISSUE THREAD

**Issue by ram1897** [pytorch/pytorch#11235]
## Issue description
Is there a possibility of converting the "pbtxt" files to ".pb" fiiles.
For example in tensorflow we can achieve this (source : https://github.com/irfansharif/tensorflow/blob/master/converter.py)

**Comment by houseroad** [comment]
You can manually create a NetDef in memory, and merge the pbtxt to the empty NetDef. Similar logic as in `converter.py` you mentioned.
