### ISSUE TITLE
Requesting to add a section to the Installing C++ Distributions of PyTorch documentation for Apple M1/M2 Processors

### ISSUE THREAD

**Issue by lmnzx** [pytorch/pytorch#112339]
### 📚 The doc issue

If someone is trying to use the C++ library with the Apple M1/M2 Processor then they have to compile pytorch from the source and use `arm64` as a target. This should be mentioned in the  Installing C++ Distributions of PyTorch.

### Suggest a potential alternative/fix

A simple instruction for compiling can be added to the docs.

Something like:
```bash
git clone -b main --recurse-submodule https://github.com/pytorch/pytorch.git
mkdir pytorch-build-arm64
cd pytorch-build-arm64
cmake -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=11.00 -DUSE_MKLDNN=OFF -DUSE_QNNPACK=OFF -DUSE_PYTORCH_QNNPACK=OFF -DBUILD_TEST=OFF -DUSE_NNPACK=OFF -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON_EXECUTABLE:PATH=/opt/homebrew/bin/python3 -DCMAKE_INSTALL_PREFIX:PATH=../pytorch-install ../pytorch
cmake --build . --target install
```
NOTE: change the paths according to your system, i am using the python installed by homebrew. You will also need to install the required dependencies like `PyYAML` and `typing-extensions`.

This will build pytorch for the `arm64` platform. It will also create another directory in the base folder called `pytorch-install`

Now, in your `example-app` you have to link to the `pytorch-install` dir
```bash
cmake -DCMAKE_PREFIX_PATH=/Path/to/this/folder/pytorch-install/...
```

cc @seemethere @malfet @osalpekar @atalman @svekars @carljparker @jbschlosser @albanD @snadampal

**Comment by malfet** [comment]
Thank you for the suggestion. I think I we should just switch libtorch builds from x86 to M1, as majority of the users are looking for that one. Or provide two binaries.

On the other hand, please note, that one can build C++ application using PyTorch wheel, which is currently available for both x86 and M1, by running something like:
``` shell
$ cmake -DCMAKE_PREFIX_PATH=`python3 -c 'import torch;print(torch.utils.cmake_prefix_path)'` ..
```
See  https://pytorch.org/cppdocs/installing.html for more details

**Comment by malfet** [comment]
Similar issues: https://github.com/pytorch/pytorch/issues/104502

**Comment by lmnzx** [comment]
I tried to build it with PyTorch wheel but it failed.
```
-- The C compiler identification is AppleClang 15.0.0.15000040
-- The CXX compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```
but there is no error when using pytorch compiled by myself. I think self-compilation is the way to go for now, I will try to make an universal executable by combining the arm64 and x86 executable. 

This issue can be a helpful resource: #63558

**Comment by malfet** [comment]
As now both Intel and Apple Silicon lib torch binaries are published on http://pytorch.org/get-started/locally/ closing this one as completed
