### ISSUE TITLE
KINETO_USE_DAEMON not work

### ISSUE THREAD

**Issue by w0x7c00** [pytorch/pytorch#112389]
# Description
When I set the env  `KINETO_USE_DAEMON=1`.
A cupti error `CUPTI_ERROR_MULTIPLE_SUBSCRIBERS_NOT_SUPPORTED` will be reported when I import torch in python interpreter.

# Shell Stdout

4029780fc904(@:):test# export KINETO_USE_DAEMON=1
4029780fc904(@:):test# python3

Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import torch
INFO:2023-10-30 20:57:45 14:14 init.cpp:121] Registering daemon config loader
WARNING:2023-10-30 20:57:45 14:14 init.cpp:155] function cbapi->getCuptiStatus() failed with error CUPTI_ERROR_MULTIPLE_SUBSCRIBERS_NOT_SUPPORTED (39)
WARNING:2023-10-30 20:57:45 14:14 init.cpp:156] CUPTI initialization failed - CUDA profiler activities will be missing
INFO:2023-10-30 20:57:45 14:14 init.cpp:158] If you see CUPTI_ERROR_INSUFFICIENT_PRIVILEGES, refer to https://developer.nvidia.com/nvidia-development-tools-solutions-err-nvgpuctrperm-cupti
\>>> print(torch.version.cuda)
12.1
\>>> print(torch.__version__)
2.1.0+cu121

# My Test Environment

pytorch: 2.1.0+cu121
cuda toolkit and cuda driver: 12.1

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-SXM2-32GB            Off| 00000000:00:0B.0 Off |                    0 |
| N/A   41C    P0               43W / 300W|      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2-32GB            Off| 00000000:00:0D.0 Off |                    0 |
| N/A   40C    P0               42W / 300W|      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2-32GB            Off| 00000000:00:0E.0 Off |                    0 |
| N/A   41C    P0               43W / 300W|      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2-32GB            Off| 00000000:00:0F.0 Off |                    0 |
| N/A   40C    P0               42W / 300W|      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2-32GB            Off| 00000000:00:10.0 Off |                    0 |
| N/A   43C    P0               44W / 300W|      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2-32GB            Off| 00000000:00:1B.0 Off |                    0 |
| N/A   39C    P0               43W / 300W|      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by w0x7c00** [comment]
Finally, I change my pytorch download source to pip official source(https://pypi.org/simple). It works. But the package download from pytorch source(https://download.pytorch.org/whl/torch/) doesn`t works. Why?

**Comment by JingshuXia** [comment]
We've encountered the similar issue where KINETO_USE_DAEMON=1 only works with the pytorch downloaded from pypi but throws Segementation Fault for the pytorch source. We are testing with torch 2.0.1+cu118 from pytorch source. 

Here is a snapshot of the native stacktraces:
<img width="1312" alt="Screen Shot 2023-12-05 at 4 13 55 PM" src="https://github.com/pytorch/pytorch/assets/406665/6ea606c2-d8f2-4225-8015-a4b1cd70bc1c">

Same failure if passed in KINETO_USE_DAEMON=0. Seems it just checks if the environment variable is set without parsing its value. 

Any insights on the difference between the two sources that could possibly lead to the failure?

**Comment by briancoutinho** [comment]
@JingshuXia thanks for reporting this. 
Looking at the stack trace it seems like CUPTI library is not available in the environment, and we are not able to dynamically link into it. A few things to look into.
1. Quick check to confirm this is not a APPLE or WINDOWS environment as these are not supported.
2. The error is showing up from `libtorch_cpu.so`. Is the torch program enabling CUDA and are you using GPU and CUDA ?running `torch.cuda.is_available()` to confirm it. 
3. If this is CPU build only we are debugging a known issue where CPU only torch is not working correctly with KINETO_USE_DAEMON (https://github.com/facebookincubator/dynolog/issues/208)
4. Can you try a simple profiler run (unset KINETO_USE_DAEMON) shown [here](https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html). Do you still see an abort in that case?

> KINETO_USE_DAEMON=0. Seems it just checks if the environment variable is set without parsing its value.

This is true its just looking for env to be set not really reading its value. We can update that.
If you want to exclude it, unset KINETO_USE_DAEMON should hopefully help.

**Comment by briancoutinho** [comment]
@JingshuXia @w0x7c00  can you share what are the exact commands you use for PyPi vs directly using wheel
> Finally, I change my pytorch download source to pip official source(https://pypi.org/simple). It works. But the package download from pytorch source(https://download.pytorch.org/whl/torch/) doesn`t works. Why?

PyPi command, and direct download from wheel?

I am using this from official pytorch documentation
'pip3 install torch torchvision torchaudio'

**Comment by briancoutinho** [comment]
Working on two WIP fixes
https://github.com/pytorch/kineto/pull/861 (have to land this first)
https://github.com/pytorch/pytorch/pull/118320

**Comment by JingshuXia** [comment]
Hi @briancoutinho 
This is our environment setting: 
OS: Ubuntu 22.04.3 LTS(jammy): GNU/Linux 5.15.0-1040-aws x86_64
cuda driver: 535.129.03
cuda: 11.8
cudnn: 8.9.3.28
nccl and nccl-dev: 2.15.5
instance type: p4 (nvidia A100)
We confirmed that we used cuda while running the pytorch job, it's not a CPU only job.

**Comment by briancoutinho** [comment]
I could not use torch 2.0.1 (seeing an error shown below) but tried 2.2.0. It turns out this is working, and I could not repro the issue. My system has CUDA 12.0 but I did tried the cu118. 

Tried the command but get this error -
```(pytorch_pypi) [bcoutinho@devgpu038.ftw6 ~/local/pytorch (kineto_daemon_cpu)]$ pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
ERROR: Could not find a version that satisfies the requirement torch==2.0.1 (from versions: 2.2.0+cu118)
ERROR: No matching distribution found for torch==2.0.1
```

Used “pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118” This works 
``` Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Downloading https://download.pytorch.org/whl/cu118/torch-2.2.0%2Bcu118-cp312-cp312-linux_x86_64.whl (811.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 811.6/811.6 MB 12.1 MB/s eta 0:00:00
``` 
Tested out an application by setting KIENTO_USE_DAEMON=1 in the environment. It registers with dynolog and collects traces.
``` pytorch_pypi) [bcoutinho@devgpu038.ftw6 ~/fbsource/fbcode (ee6d84de9)]$ python3 dynolog/scripts/pytorch/linear_model_example.py
INFO:2024-02-06 16:37:55 3613679:3613679 init.cpp:121] Registering daemon config loader
cuda:0
99 673.72900390625
10099 8.817169189453125
20099 8.817169189453125
30099 8.817169189453125
40099 8.817169189453125
50099 8.817169189453125
60099 8.817169189453125
STAGE:2024-02-06 16:38:30 3613679:3621483 CuptiActivityProfiler.cpp:979] Completed Stage: Warm Up
STAGE:2024-02-06 16:38:30 3613679:3621483 CuptiActivityProfiler.cpp:1027] Completed Stage: Collection
STAGE:2024-02-06 16:38:32 3613679:3621483 CuptiActivityProfiler.cpp:1050] Completed Stage: Post Processing
70099
```

Here is my environment based on running `pip3 list`
``` (pytorch_pypi) [bcoutinho@devgpu038.ftw6 ~/fbsource/fbcode (ee6d84de9)]$ pip3 list
Package                  Version
------------------------ -----------
filelock                 3.9.0
fsspec                   2023.4.0
Jinja2                   3.1.2
MarkupSafe               2.1.3
mpmath                   1.3.0
networkx                 3.2.1
nvidia-cublas-cu11       11.11.3.6
nvidia-cuda-cupti-cu11   11.8.87
nvidia-cuda-nvrtc-cu11   11.8.89
nvidia-cuda-runtime-cu11 11.8.89
nvidia-cudnn-cu11        8.7.0.84
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.3.0.86
nvidia-cusolver-cu11     11.4.1.48
nvidia-cusparse-cu11     11.7.5.86
nvidia-nccl-cu11         2.19.3
nvidia-nvtx-cu11         11.8.86
pip                      24.0
setuptools               69.0.3
sympy                    1.12
torch                    2.2.0+cu118
torchaudio               2.2.0+cu118
torchvision              0.1.6
typing_extensions        4.8.0
wheel                    0.42.0
```
 Hmm. 
 - How about trying installing ‘nvidia-cuda-cupti-cu11 ‘ with pip3 just to check. 
 - Also just to make sure we use the same program can you check with [linear_model.py](https://github.com/facebookincubator/dynolog/blob/main/scripts/pytorch/linear_model_example.py)
  
  I’ll ask internally how these wheel’s are built which could help.

**Comment by briancoutinho** [comment]
Added a fix, let's wait for it to make it to nightly @JingshuXia , @w0x7c00 
Set KINETO_DAEMON_INIT_DELAY_S=5 or whatever short delay you can use

**Comment by briancoutinho** [comment]
@JingshuXia , @w0x7c00  does this work? If so I'll add it to docs

**Comment by JingshuXia** [comment]
Hi @briancoutinho, sorry for the late reponse. Setting KINETO_DAEMON_INIT_DELAY_S=1 works for us! Thanks for the fix!

**Comment by hi20240217** [comment]
> Hi @briancoutinho, sorry for the late reponse. Setting KINETO_DAEMON_INIT_DELAY_S=1 works for us! Thanks for the fix!

External init callback must run in same thread as registerClient
