### ISSUE TITLE
Serious bug with torch.distributions.utils.broadcast_all

### ISSUE THREAD

**Issue by gbohner** [pytorch/pytorch#11242]
## Issue description

A serious bug with  ```torch.distributions.utils.broadcast_all```

https://github.com/pytorch/pytorch/blob/v0.4.1/torch/distributions/utils.py#L49

## Code example

```torch.log(torch.distributions.utils.broadcast_all(torch.ones(1,4), torch.zeros(3,1,4))[0])```

Expected output would be an array of zeros with dimensions (3,1,4). Actual output is the correct size, but (surprisingly consistently produced) garbage:
```
tensor([[[   0.0000,    0.0000,    0.0000,    0.0000]],

        [[ -99.8132,      -inf,  -99.1045,      -inf]],

        [[-103.2789,  -93.2846,       nan,  -93.2846]]])
```

Note that if broadcast_all needs to broadcast every dimension, the bug doesn't occur, it seems to be dealing with singleton dimensions badly.

Therefore
```torch.log(torch.distributions.utils.broadcast_all(torch.ones(1,4), torch.zeros(3,2,4))[0])```
produces the expected all zeros array.

The bug is definitely with broadcast_all, as it happens for other operators, not just torch.log()

## System Info
```
conda list torch
pytorch                   0.4.1           py37_cuda8.0.61_cudnn7.1.2_1  [cuda80]  pytorch
torchvision               0.2.1                    py37_1    pytorch
```

**Comment by SsnL** [comment]
Sorry about the bug. Fixed on master with @zou3519 's new `broadcast_tensors`!
