### ISSUE TITLE
Accessing .grad in a backward hook in compiled_autograd does not work, is always none. 

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#112446]
### 🐛 Describe the bug

Accessing .grad in a backward hook in compiled_autograd does not work, is always none. 

### Versions

a7a0955790b6b91c3d4f22a6f98412276fe4964c

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by jansel** [comment]
When we construct fake tensors, we may need to examine the .grad of all the inputs and turn those into fake tensors too...

**Comment by voznesenskym** [comment]
> When we construct fake tensors, we may need to examine the .grad of all the inputs and turn those into fake tensors too...

They should already be fake where I spot checked, iirc, this is a dynamo bug in handling `.grad`, but unclear. I am going to look at this tomorrow morning.

**Comment by voznesenskym** [comment]
```
def hook(t):
    t.grad.mul_(5)

x = torch.ones([2, 2], requires_grad=True)
y = torch.ones([2, 2], requires_grad=True)
x.register_post_accumulate_grad_hook(hook)

def fn(x, y):
    return x + y

out = fn(x, y)
x.backward(torch.ones([2, 2]))
print(x.grad)

with compiled_autograd.enable(torch.compile(backend="inductor", fullgraph=True)):
    out = fn(x, y)
    x.backward(torch.ones([2, 2]))
```

commenting out that middle part  

```
out = fn(x, y)
x.backward(torch.ones([2, 2]))
print(x.grad)
```

Causes it to fail... 
```
torch._dynamo.exc.InternalTorchDynamoError: 'NoneType' object has no attribute 'mul_'
```
For some reason, the arg, aka, the grad is None.

I'm still investigating. Avenues I've tried so far, and exhausted:

(1) new_grad setting not getting hit [Wrong]

```
if (!grad.defined()) {
      grad = new_grad;
    }
 ```
 Debunked with prints
  
(2) accumulate_grad_ should be functional [Wrong]

The call in the graph looks like this `accumulate_grad_ = torch.ops.inductor.accumulate_grad_.default(getitem_1, getitem)` but the registered schema doesn't actually register itself as mutating (t), so I thought, oh, maybe this is the culprit?

It's not - I wrote a functional version and taught accumulated_grad to use the return of the op downstream in dynamo, no change

(3) dynamo builtins are written incorrectly for handing grad [Wrong]

I rewrote the `.grad` code to not do all the weird grapharg stuff, and instead use a proxy from the tensor to access `.grad` tensor as its own proxy.

Still the same error, no change.

(4) The fake tensor .grad is not set [Wrong]

Disproven by setting breakpoints in where we handle post_acc_grad_hook, and we can see that the fake tensor has the right values.

(5) The runtime invocation of accumulated_grad_ is doing the wrong thing w/r/t mutating input tensor to set the grad. Graph is correct, but runtime op behavior is wrong? [Investigating now]

**Comment by voznesenskym** [comment]
This is a combination of functionalization issues, due to FunctionalTensor not holding .grad, and dynamo .grad handling.

Working on a PR that covers all cases, running into other bugs as I go.

**Comment by voznesenskym** [comment]
Actually - functionalization works fine, and if we don't violate the invariant of all-grads-get-lifted, it all works. However, we are forced to violate the invariant (incorrectly) because example_value for .grad is None. This is because at initial trace time capture of the tensor on which we access .grad, when example_value is stored on the grapharg, there is no grad. However, running accumulate_grad populates grad. This means that now, the real state of the tensor w/r/t fields/properties (in this case, grad, but really could be anything) is out of sync. This means that anytime you reach into grapharg.example to get the original raw tensor value (very sus) you are accessing a potentially stale value. The right thing to do is to do what we do in our more complex lifting code, and access the real value via the frame state using a source.

**Comment by voznesenskym** [comment]
Faithfully mirroring behavior with a c++ op is a PITA. The right call is to probably author the entirety of accumulate_grad_ in python and trace that. This is non trivial.
