### ISSUE TITLE
Disable pytorch.org/api ?

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#1124]
Sometims `pytorch.org/api/0.1.4` or 0.1.3 would come up in Google search instead of `pytorch.org/docs` creating confusion.

I hope PyTorch won't go OpenCV's path with many outdated version of documentation still online on official website and coming up in Google :) (docs of 2.4.11 and 3.0-beta still come up often, when the latest release is 3.2)

**Comment by apaszke** [comment]
We need to add versioning to the docs, but we can only allow indexing of the `master` or `latest_release` version.

**Comment by soumith** [comment]
removed old api docs via https://github.com/pytorch/pytorch.github.io/commit/862f334f0ac3706ef26c607bf02d2c1bf606211e
