### ISSUE TITLE
storage._share_fd_cpu_() in multiprocessing/reductions.py reports 'can not allocate memory (12)'

### ISSUE THREAD

**Issue by windless0530** [pytorch/pytorch#112470]
### 🐛 Describe the bug

I am migrating my project from PyTorch 1.8 to 1.13.

```
# Copyright (c) OpenMMLab. All rights reserved.
from mmdet.apis import train_detector
from mmseg.apis import train_segmentor
import torch

def train_model(model, dataset, cfg, distributed=False, validate=False, timestamp=None, meta=None):
    """A function wrapper for launching model training according to cfg.

    Because we need different eval_hook in runner. Should be deprecated in the
    future.
    """
    cfg.device = 'cuda'
    if cfg.model.type in ['EncoderDecoder3D']:
        train_segmentor(model, dataset, cfg, distributed=distributed, validate=validate, timestamp=timestamp, meta=meta)
    else:
        # The training entrance of this issue
        train_detector(model, dataset, cfg, distributed=distributed, validate=validate, timestamp=timestamp, meta=meta)
```

While at the beggining of the training, the following error occured:

```
Traceback (most recent call last):
  File "/work/lidar_perception/./tools/train.py", line 487, in <module>
    main()
  File "/work/lidar_perception/./tools/train.py", line 478, in main
    train_model(model,
  File "/work/lidar_perception/mmdet3d/apis/train.py", line 17, in train_model
    train_detector(model, dataset, cfg, distributed=distributed, validate=validate, timestamp=timestamp, meta=meta)
  File "/opt/conda/lib/python3.9/site-packages/mmdet/apis/train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1034, in __init__
    w.start()
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/conda/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/conda/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/conda/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/conda/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 375, in reduce_storage
    fd, size = storage._share_fd_cpu_()
RuntimeError: unable to mmap 1764 bytes from file </torch_12505_20520068_62802>: Cannot allocate memory (12)
```

Here are some detailed information:

1. Everything was fine under PyTorch 1.8
2. The training was run inside docker container, with GPU of A100 × 4
3. By adding log in multiprocessing/reductions.py, I found that until the error message occured,  `storage._share_fd_cpu()` had been called over 60000+ times, and the accumulated `storage.size()` was about 37M.
4. By running `ulimit -a` I found the file descriptor limit was about 1M, and by running `df /dev/shm` I found the size of shared memory was about 100G.
5. By observing result shown in `top` command, I found the memory usage was no more than about 40% before the error occured.
6. The training dataset was composed by one set of data repeated 3 times. If I use only one copy, or just repeat a partial part, the error would not occur. I am not sure whether the error was caused by the size of the dataset or the data duplication. See the following image for details.

![image](https://github.com/pytorch/pytorch/assets/4645959/b84dcc6a-4c20-41eb-a809-3115629cf351)

Could anyone give me advice on how to further explore on this issue?

Thank you.

### Versions

PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-110-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB

Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              56
On-line CPU(s) list: 0-55
Thread(s) per core:  2
Core(s) per socket:  28
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz
Stepping:            6
CPU MHz:             2300.038
BogoMIPS:            4600.07
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            55296K
NUMA node0 CPU(s):   0-55
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid md_clear arch_capabilities

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] flake8==4.0.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.4
[pip3] onnx==1.13.0
[pip3] onnxruntime==1.13.1
[pip3] onnxruntime-extensions==0.9.0
[pip3] torch==1.13.0
[pip3] torch-tb-profiler==0.2.0
[pip3] torchtext==0.14.0
[pip3] torchvision==0.14.0
[conda] blas                      1.0                         mkl
[conda] efficientnet-pytorch      0.7.1                    pypi_0    pypi
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] pytorch                   1.13.0          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-cuda              11.6                 h867d48c_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-tb-profiler         0.2.0                    pypi_0    pypi
[conda] torchtext                 0.14.0                     py39    pytorch
[conda] torchvision               0.14.0               py39_cu116    pytorch

**Comment by windless0530** [comment]
After searching over and over, I finally found the solution: setting the kernel parameter `vm.max_map_count` to a larger one, e.g.

`sysctl -w vm.max_map_count=1048576`

**Comment by YjZhang-sudo** [comment]
Thank you, your answer solved my problem perfectly!

**Comment by josephcappadona** [comment]
> After searching over and over, I finally found the solution: setting the kernel parameter `vm.max_map_count` to a larger one, e.g.
> 
> `sysctl -w vm.max_map_count=1048576`

Just wanted to add this this fixed the issue for me as well.
```
concurrent.futures.process._RemoteTraceback:                                                                                                              
'''                                                                                                                                                       
Traceback (most recent call last):                                                                                                                        
  File "/home/jcappadona/.miniforge3/lib/python3.10/concurrent/futures/process.py", line 392, in wait_result_broken_or_wakeup                             
    result_item = result_reader.recv()                                                                                                                    
  File "/home/jcappadona/.miniforge3/lib/python3.10/multiprocessing/connection.py", line 251, in recv                                                     
    return _ForkingPickler.loads(buf.getbuffer())                                                                                                         
  File "/home/jcappadona/.miniforge3/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 360, in rebuild_storage_fd                   
    storage = cls._new_shared_fd_cpu(fd, size)                                                                                                            
RuntimeError: unable to mmap 4 bytes from file <filename not specified>: Cannot allocate memory (12)                                                      
'''                                                                                                                                                       
                                                                                                                                                          
The above exception was the direct cause of the following exception:                                                                                      
...
...                                                                         
Traceback (most recent call last):                                                                                                                          
  File "/home/jcappadona/...", line 278, in <listcomp>                                          
    results = [future.result() for future in futures]                                                                                                     
  File "/home/jcappadona/.miniforge3/lib/python3.10/concurrent/futures/_base.py", line 451, in result                                                     
    return self.__get_result()                                                                                                                            
  File "/home/jcappadona/.miniforge3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
