### ISSUE TITLE
Fix docstring errors in pixelshuffle.py, sparse.py, rnn.py, pooling.py, upsampling.py

### ISSUE THREAD

**Issue by svekars** [pytorch/pytorch#112599]
Please fix the following issues. To test locally, run: 
 ```
pydocstyle path-to-file --count
```
Run this command before and after fixing the errors. This command prints out the number of errors at the end of the output. Paste the output to your PR description with the number before and after. 
- **File**: `torch/nn/modules/pixelshuffle.py`, **Entity**: `PixelShuffle`, **Line**: 9, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/pixelshuffle.py`, **Entity**: `PixelShuffle`, **Line**: 9, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/pixelshuffle.py`, **Entity**: `PixelShuffle`, **Line**: 9, **Description**: First line should end with a period (not '`')
- **File**: `torch/nn/modules/pixelshuffle.py`, **Entity**: `PixelUnshuffle`, **Line**: 61, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/pixelshuffle.py`, **Entity**: `PixelUnshuffle`, **Line**: 61, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/pixelshuffle.py`, **Entity**: `PixelUnshuffle`, **Line**: 61, **Description**: First line should end with a period (not 's')
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `MaxPool1d`, **Line**: 39, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `MaxPool1d`, **Line**: 39, **Description**: First line should end with a period (not 't')
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `MaxPool2d`, **Line**: 98, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `MaxPool2d`, **Line**: 98, **Description**: First line should end with a period (not 't')
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `MaxPool3d`, **Line**: 172, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `MaxPool3d`, **Line**: 172, **Description**: First line should end with a period (not 't')
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `AvgPool1d`, **Line**: 498, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `AvgPool1d`, **Line**: 498, **Description**: First line should end with a period (not 'l')
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `AvgPool2d`, **Line**: 565, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `AvgPool2d`, **Line**: 565, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `AvgPool2d`, **Line**: 565, **Description**: First line should end with a period (not 't')
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `AvgPool3d`, **Line**: 644, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `AvgPool3d`, **Line**: 644, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `AvgPool3d`, **Line**: 644, **Description**: First line should end with a period (not 't')
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `FractionalMaxPool2d`, **Line**: 736, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `FractionalMaxPool3d`, **Line**: 806, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `LPPool1d`, **Line**: 894, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `LPPool1d`, **Line**: 894, **Description**: First line should end with a period (not 't')
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `LPPool2d`, **Line**: 936, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/pooling.py`, **Entity**: `LPPool2d`, **Line**: 936, **Description**: First line should end with a period (not 't')
- **File**: `torch/nn/modules/sparse.py`, **Entity**: `Embedding`, **Line**: 14, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/sparse.py`, **Entity**: `from_pretrained`, **Line**: 184, **Description**: First line should be in imperative mood (perhaps 'Create', not 'Creates')
- **File**: `torch/nn/modules/sparse.py`, **Entity**: `EmbeddingBag`, **Line**: 227, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/sparse.py`, **Entity**: `EmbeddingBag`, **Line**: 227, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/sparse.py`, **Entity**: `EmbeddingBag`, **Line**: 227, **Description**: First line should end with a period (not 'e')
- **File**: `torch/nn/modules/sparse.py`, **Entity**: `from_pretrained`, **Line**: 413, **Description**: First line should be in imperative mood (perhaps 'Create', not 'Creates')
- **File**: `torch/nn/modules/rnn.py`, **Entity**: `flatten_parameters`, **Line**: 149, **Description**: First line should be in imperative mood (perhaps 'Reset', not 'Resets')
- **File**: `torch/nn/modules/rnn.py`, **Entity**: `RNN`, **Line**: 345, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/rnn.py`, **Entity**: `RNN`, **Line**: 345, **Description**: First line should end with a period (not 'n')
- **File**: `torch/nn/modules/rnn.py`, **Entity**: `LSTM`, **Line**: 565, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/rnn.py`, **Entity**: `LSTM`, **Line**: 565, **Description**: First line should end with a period (not 't')
- **File**: `torch/nn/modules/rnn.py`, **Entity**: `GRU`, **Line**: 852, **Description**: 1 blank line required between summary line and description (found 2)
- **File**: `torch/nn/modules/rnn.py`, **Entity**: `RNNCell`, **Line**: 1110, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/rnn.py`, **Entity**: `GRUCell`, **Line**: 1297, **Description**: First line should end with a period (not 'l')
- **File**: `torch/nn/modules/upsampling.py`, **Entity**: `Upsample`, **Line**: 12, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/upsampling.py`, **Entity**: `UpsamplingNearest2d`, **Line**: 175, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/upsampling.py`, **Entity**: `UpsamplingNearest2d`, **Line**: 175, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/upsampling.py`, **Entity**: `UpsamplingNearest2d`, **Line**: 175, **Description**: First line should end with a period (not 't')
- **File**: `torch/nn/modules/upsampling.py`, **Entity**: `UpsamplingBilinear2d`, **Line**: 220, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/modules/upsampling.py`, **Entity**: `UpsamplingBilinear2d`, **Line**: 220, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/modules/upsampling.py`, **Entity**: `UpsamplingBilinear2d`, **Line**: 220, **Description**: First line should end with a period (not 't')

cc @carljparker

**Comment by zabboud** [comment]
Note - I will submit one PR per file - to avoid having a long period of inactivity.

**Comment by svekars** [comment]
@zabboud actually - can you please submit all in one PR.
