### ISSUE TITLE
Bug Report No Version Of Pytorch for cuda 12.3

### ISSUE THREAD

**Issue by tomas122727** [pytorch/pytorch#112500]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

since updating both my gpu driver and cuda to cuda 12.3 pytorch isnt detecting my gpu and is complaing that cuda is not availible and that i dont have supported gpu when it was working just fine my gpu is a rtx 3060 yes with cuda support

## Code example

torch.is.availible()

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS: windows 10
- PyTorch version: latest available
- Python version:
- CUDA/cuDNN version: latest
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries: cuda toolkit 12.3

**Comment by tomas122727** [comment]
torch returns that no cuda gpu is availible when it was working fine before ?

**Comment by malfet** [comment]
Do you mind opening another issue and fill in necessary details, namely:
- Your OS
- How do you install PyTorch (pip/conda/build from source)
- Output of `python3 -mtorch.utils.collect_env`

But from the look of it, it sounds like a local system setup problem, perhaps https://discuss.pytorch.org/ is a more appropriate place to ask such questions?

**Comment by sascharo** [comment]
Does PyTorch work with CUDA 12.3? Isn't 12.1 the last version supported?

**Comment by tomas122727** [comment]
py torch only has 12.1 support ?

**Comment by tomas122727** [comment]
Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.1.0+cu118
[pip3] torchaudio==2.1.0+cu118
[pip3] torchvision==0.16.0+cu118
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h6b88ed4_46358
[conda] mkl-service               2.4.0           py311h2bbff1b_1
[conda] mkl_fft                   1.3.8           py311h2bbff1b_0
[conda] mkl_random                1.2.4           py311h59b6b97_0
[conda] numpy                     1.26.1                   pypi_0    pypi
[conda] numpy-base                1.26.0          py311hd01c5d8_0
[conda] pytorch                   2.1.1           py3.11_cuda11.8_cudnn8_0    pytorch
[conda] pytorch-cuda              11.8                 h24eeafa_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torchaudio                2.1.1                    pypi_0    pypi
[conda] torchvision               0.16.1                   pypi_0    pypi

**Comment by tomas122727** [comment]
note i downgraded to cuda 11.8

**Comment by tomas122727** [comment]
but still things arent recognized no matter how i installed pytorch via conda or pip it still compains

**Comment by sascharo** [comment]
> py torch only has 12.1 support ?

[https://discuss.pytorch.org/t/question-i-have-a-question-about-installing-pytorch/191829/2](https://discuss.pytorch.org/t/question-i-have-a-question-about-installing-pytorch/191829/2)

> PyTorch is compatible with CUDA 12.3 and will use your locally installed CUDA toolkit for source builds. The binaries ship with their own CUDA dependencies, won’t use your local CUDA toolkit, and only a properly installed NVIDIA driver is needed.

**Comment by jobyclash2** [comment]
i have same issue

**Comment by boyXiong** [comment]
i have same issue,  don't use gpu to work

**Comment by thinkhp** [comment]
Instead of using `conda install ...`, try using `pip install torch torchvision torchaudio`. It works for me.
My environment: WSL with Ubuntu, CUDA 12.3, Python 3.10.

**Comment by sascharo** [comment]
> Instead of using `conda install ...`, try using `pip install torch torchvision torchaudio`. It works for me.
> My environment: WSL with Ubuntu, CUDA 12.3, Python 3.10.

That's good for you. It didn't work for me with WSL2 Ubuntu 22.04.2. I could only get it to work with CUDA 12.1 (driver version 531.14). With driver versions that came with CUDA 12.3, PyTorch didn't recognize the CUDA device.

**Comment by sascharo** [comment]
> Instead of using `conda install ...`, try using `pip install torch torchvision torchaudio`. It works for me.
> My environment: WSL with Ubuntu, CUDA 12.3, Python 3.10.

That's good for you. It didn't work for me with WSL2 Ubuntu 22.04.2. I could only get it to work with CUDA 12.1 (driver version 531.14). With driver versions that came with CUDA 12.3, PyTorch didn't recignize the CUDA device.

**Comment by philippwulff** [comment]
> Instead of using `conda install ...`, try using `pip install torch torchvision torchaudio`. It works for me.
> My environment: WSL with Ubuntu, CUDA 12.3, Python 3.10.

This worked in my case with WSL2 Ubuntu 22.04.2 and Python 3.10 and CUDA 12.3.

**Comment by sfmqrb** [comment]
same issue

**Comment by JuergenDi** [comment]
> > Instead of using `conda install ...`, try using `pip install torch torchvision torchaudio`. It works for me.
> > My environment: WSL with Ubuntu, CUDA 12.3, Python 3.10.
> 
Torch (stable 2.1.1) with CUDA 12.3 does not work neither with 'pip install..' nor with 'conda install..'
I am using Ubuntu 22.04.3 LTS (5.15.0-91-generic), Python 3.12.0, CUDA Version: 12.3 (Driver Version: 545.23.08)

**Comment by munnificent** [comment]
with Python version 3.12 and CUDA 12.3, the Preview (Nightly) version of PyTorch works

**Comment by EmmaWebGH** [comment]
Same issue, CUDA 12.3 but anaconda prompt says 
`No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3'`

And here it says 11.8????
https://pytorch.org/get-started/locally/
Is that page out of date?
Do I specifically need 12.1 or will everything that wants 12.1 use 12.3? As it seems not but replies above all say yes.

**Comment by Antsthebul** [comment]
Just commenting for others. This was wat worked for me
System: Ubuntu 20.04
Python: 3.9
GPU version: 12.3
Driver Version 545.23.08
Cuda Toolkit: 10.1

Simply running `pip install torch torchvision torchaudio` worked for me

**Comment by sambar1729** [comment]
anyone have a command line for installing pytorch with cuda12.3? still facing the problem. this page only has 12.1 (and 12.4 is crossed out) https://pytorch.org/get-started/locally/

**Comment by kawaii2020** [comment]
Same issue here, need pytorch for cuda 12.3
