### ISSUE TITLE
Fix docstring errors in reductions.py, spawn.py, pool.py, parameter.py, cpp.py, grad.py, __init__.py, profiler.py, queue.py, graph.py

### ISSUE THREAD

**Issue by svekars** [pytorch/pytorch#112595]
Please fix the following issues. To test locally, run: 
 ```
pydocstyle path-to-file --count
```
Run this command before and after fixing the errors. This command prints out the number of errors at the end of the output. Paste the output to your PR description with the number before and after. 
- **File**: `torch/autograd/profiler.py`, **Entity**: `profile`, **Line**: 86, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `profile`, **Line**: 86, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `self_cpu_time_total`, **Line**: 356, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `self_cpu_time_total`, **Line**: 356, **Description**: No whitespaces allowed surrounding docstring text
- **File**: `torch/autograd/profiler.py`, **Entity**: `self_cpu_time_total`, **Line**: 356, **Description**: First line should end with a period (not 'f')
- **File**: `torch/autograd/profiler.py`, **Entity**: `record_function`, **Line**: 498, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `record_function`, **Line**: 498, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `record_function`, **Line**: 498, **Description**: First line should end with a period (not 'f')
- **File**: `torch/autograd/profiler.py`, **Entity**: `_call_end_callbacks_on_future`, **Line**: 563, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `_call_end_callbacks_on_future`, **Line**: 563, **Description**: First line should end with a period (not 'c')
- **File**: `torch/autograd/profiler.py`, **Entity**: `emit_itt`, **Line**: 604, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `emit_nvtx`, **Line**: 671, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `load_nvprof`, **Line**: 788, **Description**: First line should be in imperative mood (perhaps 'Open', not 'Opens')
- **File**: `torch/autograd/profiler.py`, **Entity**: `EnforceUnique`, **Line**: 797, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `KinetoStepTracker`, **Line**: 872, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `KinetoStepTracker`, **Line**: 872, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/autograd/profiler.py`, **Entity**: `increment_step`, **Line**: 920, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/autograd/graph.py`, **Entity**: `name`, **Line**: 23, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/autograd/graph.py`, **Entity**: `metadata`, **Line**: 43, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/autograd/graph.py`, **Entity**: `register_hook`, **Line**: 52, **Description**: First line should be in imperative mood (perhaps 'Register', not 'Registers')
- **File**: `torch/autograd/graph.py`, **Entity**: `register_prehook`, **Line**: 90, **Description**: First line should be in imperative mood (perhaps 'Register', not 'Registers')
- **File**: `torch/autograd/graph.py`, **Entity**: `increment_version`, **Line**: 133, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/autograd/graph.py`, **Entity**: `increment_version`, **Line**: 133, **Description**: First line should end with a period (not 'd')
- **File**: `torch/autograd/graph.py`, **Entity**: `increment_version`, **Line**: 133, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/autograd/graph.py`, **Entity**: `saved_tensors_hooks`, **Line**: 148, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/autograd/graph.py`, **Entity**: `save_on_cpu`, **Line**: 220, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/autograd/graph.py`, **Entity**: `save_on_cpu`, **Line**: 220, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/autograd/graph.py`, **Entity**: `save_on_cpu`, **Line**: 220, **Description**: First line should end with a period (not 'e')
- **File**: `torch/autograd/graph.py`, **Entity**: `register_multi_grad_hook`, **Line**: 317, **Description**: First line should be in imperative mood (perhaps 'Register', not 'Registers')
- **File**: `torch/autograd/graph.py`, **Entity**: `allow_mutation_on_saved_tensors`, **Line**: 527, **Description**: First line should end with a period (not 'd')
- **File**: `torch/multiprocessing/pool.py`, **Entity**: `Pool`, **Line**: 17, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/multiprocessing/pool.py`, **Entity**: `Pool`, **Line**: 17, **Description**: Multi-line docstring closing quotes should be on a separate line
- **File**: `torch/multiprocessing/pool.py`, **Entity**: `_repopulate_pool`, **Line**: 28, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/multiprocessing/pool.py`, **Entity**: `_repopulate_pool`, **Line**: 28, **Description**: First line should end with a period (not ',')
- **File**: `torch/multiprocessing/queue.py`, **Entity**: `ConnectionWrapper`, **Line**: 8, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/multiprocessing/queue.py`, **Entity**: `ConnectionWrapper`, **Line**: 8, **Description**: Multi-line docstring closing quotes should be on a separate line
- **File**: `torch/multiprocessing/queue.py`, **Entity**: `ConnectionWrapper`, **Line**: 8, **Description**: First line should end with a period (not 'o')
- **File**: `torch/multiprocessing/reductions.py`, **Entity**: `StorageWeakRef`, **Line**: 23, **Description**: Multi-line docstring closing quotes should be on a separate line
- **File**: `torch/multiprocessing/reductions.py`, **Entity**: `SharedCache`, **Line**: 59, **Description**: First line should end with a period (not 'f')
- **File**: `torch/multiprocessing/spawn.py`, **Entity**: `ProcessRaisedException`, **Line**: 26, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/multiprocessing/spawn.py`, **Entity**: `ProcessRaisedException`, **Line**: 26, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/multiprocessing/spawn.py`, **Entity**: `ProcessRaisedException`, **Line**: 26, **Description**: First line should end with a period (not 'n')
- **File**: `torch/multiprocessing/spawn.py`, **Entity**: `ProcessExitedException`, **Line**: 40, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/multiprocessing/spawn.py`, **Entity**: `ProcessExitedException`, **Line**: 40, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/multiprocessing/spawn.py`, **Entity**: `ProcessExitedException`, **Line**: 40, **Description**: First line should end with a period (not 'l')
- **File**: `torch/multiprocessing/spawn.py`, **Entity**: `join`, **Line**: 92, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/multiprocessing/spawn.py`, **Entity**: `join`, **Line**: 92, **Description**: First line should be in imperative mood (perhaps 'Try', not 'Tries')
- **File**: `torch/multiprocessing/__init__.py`, **Entity**: ``, **Line**: 1, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/multiprocessing/__init__.py`, **Entity**: ``, **Line**: 1, **Description**: First line should end with a period (not '`')
- **File**: `torch/multiprocessing/__init__.py`, **Entity**: `set_sharing_strategy`, **Line**: 51, **Description**: First line should be in imperative mood (perhaps 'Set', not 'Sets')
- **File**: `torch/multiprocessing/__init__.py`, **Entity**: `get_sharing_strategy`, **Line**: 63, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/multiprocessing/__init__.py`, **Entity**: `get_all_sharing_strategies`, **Line**: 68, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/nn/__init__.py`, **Entity**: `factory_kwargs`, **Line**: 14, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/__init__.py`, **Entity**: `factory_kwargs`, **Line**: 14, **Description**: First line should end with a period (not 'd')
- **File**: `torch/nn/cpp.py`, **Entity**: `OrderedDictWrapper`, **Line**: 7, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/cpp.py`, **Entity**: `OrderedDictWrapper`, **Line**: 7, **Description**: First line should end with a period (not 'e')
- **File**: `torch/nn/cpp.py`, **Entity**: `ModuleWrapper`, **Line**: 50, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/cpp.py`, **Entity**: `ModuleWrapper`, **Line**: 50, **Description**: First line should end with a period (not 'd')
- **File**: `torch/nn/grad.py`, **Entity**: ``, **Line**: 1, **Description**: First line should end with a period (not 'e')
- **File**: `torch/nn/grad.py`, **Entity**: `conv1d_input`, **Line**: 8, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/grad.py`, **Entity**: `conv1d_input`, **Line**: 8, **Description**: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
- **File**: `torch/nn/grad.py`, **Entity**: `conv1d_weight`, **Line**: 40, **Description**: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
- **File**: `torch/nn/grad.py`, **Entity**: `conv2d_input`, **Line**: 71, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/grad.py`, **Entity**: `conv2d_input`, **Line**: 71, **Description**: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
- **File**: `torch/nn/grad.py`, **Entity**: `conv2d_weight`, **Line**: 103, **Description**: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
- **File**: `torch/nn/grad.py`, **Entity**: `conv3d_input`, **Line**: 134, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/grad.py`, **Entity**: `conv3d_input`, **Line**: 134, **Description**: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
- **File**: `torch/nn/grad.py`, **Entity**: `conv3d_weight`, **Line**: 166, **Description**: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
- **File**: `torch/nn/parameter.py`, **Entity**: `Parameter`, **Line**: 14, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/parameter.py`, **Entity**: `materialize`, **Line**: 105, **Description**: 1 blank line required between summary line and description (found 0)

cc @carljparker

**Comment by awaelchli** [comment]
I'm happy to help out here if you haven't already started @IvanLauLinTiong :)

**Comment by IvanLauLinTiong** [comment]
Hi @awaelchli I'm actually in the midway of fixing this and would open PR soon. Anyways thanks for helping :)

**Comment by awaelchli** [comment]
Great job @IvanLauLinTiong!
