### ISSUE TITLE
when convert to onnx ,the jit will merge th outputs, it results to we can't distinguish  what the outputs represents

### ISSUE THREAD

**Issue by cqray1990** [pytorch/pytorch#112556]
### 🐛 Describe the bug

when convert to onnx ,the jit will merge th outputs, it results to we can't distinguish  what the outputs represents

### Versions

when convert to onnx ,the jit will merge th outputs, it results to we can't distinguish  what the outputs represents

            outs.append(self.inner(*trace_inputs))
            if self._return_inputs_states:
                inputs_states[0] = (inputs_states[0], trace_inputs)
            out_vars, _ = _flatten(outs)

here _flatten meger multi outputs as one , in my model, outs have four outputs,but after _flatten , it changes to 3002,it merge the behind two outputs

**Comment by thiagocrepaldi** [comment]
closing as there is no full repro
