### ISSUE TITLE
Inductor cpp wrapper: clean up the hard-coded schema for fusion OPs

### ISSUE THREAD

**Issue by chunyuan-w** [pytorch/pytorch#112552]
### 🐛 Describe the bug

Inductor cpp wrapper uses hard-coded `cpp_op_schema` for fusion OPs including:
- [ ] MKLPackedLinear
- [ ] LinearUnary
- [ ] LinearBinary
- [ ] ConvolutionUnary
- [ ] ConvolutionBinary
- [ ] ConvolutionBinaryInplace
- [ ] ConvolutionTransposeUnary
- [ ] QConvPointWisePT2E
- [ ] QConvPointWiseBinaryPT2E
- [ ] QLinearPointwisePT2E
- [ ] QLinearPointwiseBinaryPT2E

As suggested in https://github.com/pytorch/pytorch/pull/112373#discussion_r1377667369, we need to clean up these hard-coded strings and add a general way to create the `cpp_op_schema` for these OPs.

### Versions

PyTorch version: 2.2.0a0+git17eaa44

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @wconstab

**Comment by zhxchen17** [comment]
Hi @chunyuan-w I'm cleaning up old issues and wondering did you resolve this? If it's not resolved do you plan to work on it recently? Thanks :)

**Comment by chunyuan-w** [comment]
> Hi @chunyuan-w I'm cleaning up old issues and wondering did you resolve this? If it's not resolved do you plan to work on it recently? Thanks :)

Hi @zhxchen17, it's not fixed yet. I tried to inherit directly from the `FallbackKernel` to simplify the schema match but meet an assertion error `AssertionError: Empty array is not supported in C` and still more time to investigate it.

**Comment by chunyuan-w** [comment]
I saw the comment from @desertfire here https://github.com/pytorch/pytorch/pull/135318#issuecomment-2406288476 that the plan is to remove all the non-ABI-compatible codegen logic. With this plan, we should be safe to directly remove these hard-coded schemas since they're for non-ABI-compaible mode only.
