### ISSUE TITLE
[Dynamo] Custom backend receives non FakeTensor example inputs

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#112506]
### 🐛 Describe the bug

Example code:

```python
from typing import List
import torch
from torch import _dynamo as torchdynamo
def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    print("my_compiler() called with FX graph:")
    print([x.__class__ for x in example_inputs])
    gm.graph.print_tabular()
    return gm.forward  # return a python callable

@torch.compile(backend=my_compiler)
def toy_example(a, b):
    x = a / (torch.abs(a) + 1)
    b = b * -1
    y = x * b
    z = y.sum()
    z.backward()
for _ in range(100):
    input = torch.randn(10, requires_grad=True), torch.randn(10, requires_grad=True)
    toy_example(*input)
```

### Versions

PyTorch version: 2.2.0.dev20231030
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==2.1.0.dev20230824
[pip3] torchaudio==2.1.0.dev20230824
[pip3] torchvision==0.16.0.dev20230824
[conda] numpy                     1.26.0          py310h3b2db8e_0    defaults
[conda] numpy-base                1.26.0          py310ha9811e2_0    defaults
[conda] pytorch                   2.2.0.dev20231030        py3.10_0    pytorch-nightly
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     2.1.0.dev20230824          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230824          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230824          pypi_0    pypi

**Comment by youkaichao** [comment]
cc @jon-chuang

**Comment by jon-chuang** [comment]
The discussion is about whether this is valid, given that we were promised FakeTensors (albeit a while ago): https://dev-discuss.pytorch.org/t/example-inputs-to-compilers-are-now-fake-tensors/990

I'm now investigating if shipping off the `FakeTensor`s of the graphargs if available is ok.

**Comment by jon-chuang** [comment]
I think we eventually want to assert that all GraphArgs have fake_value if `isinstance(arg.example, torch.Tensor)

**Comment by jon-chuang** [comment]
Actually, @youkaichao, see: https://github.com/pytorch/pytorch/pull/99320. Basically, that post is no longer valid, as, somewhat predictably, some backends ended up wanting access to the real tensor.

I think @ezyang is not in office, hence he has not been responding.

Anyway, if you need fake tensors, you can convert the real tensors into fake tensors in your backend. You can see how to do it from the existing fake mode here.

https://github.com/pytorch/pytorch/blob/a1c56df1f0c569e842bfcd365b417a907237330b/torch/_guards.py#L779

**Comment by youkaichao** [comment]
That makes sense. Thanks. I left a note on the post https://dev-discuss.pytorch.org/t/example-inputs-to-compilers-are-now-fake-tensors/990/7 .

**Comment by RaulPPelaez** [comment]
Does this mean we no longer have to write meta registrations for custom C++ Autograd extensions?
