### ISSUE TITLE
[inductor][cpu] detectron2 fasterrcnn accuracy failure

### ISSUE THREAD

**Issue by WeizhuoZhang-intel** [pytorch/pytorch#112566]
<p>new_failures in 2023-10-29</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>suite</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>detectron2_fasterrcnn_r_101_dc5</td>
      <td>X</td>
      <td>&#10003</td>
      <td>torchbench</td>
      <td>detectron2_fasterrcnn_r_101_dc5, [2023-10-30 22:38:14 498] torch._dynamo.convert_frame: [WARNING] to diagnose recompilation issues  set env variable TORCHDYNAMO_REPORT_GUARD_FAILURES=1 and also see https://pytorch.org/docs/master/compile/troubleshooting.html.</td>
    </tr>
    <tr>
      <td>detectron2_fasterrcnn_r_101_fpn</td>
      <td>X</td>
      <td>&#10003</td>
      <td>torchbench</td>
      <td>detectron2_fasterrcnn_r_101_fpn, [2023-10-30 22:38:14 498] torch._dynamo.convert_frame: [WARNING] to diagnose recompilation issues  set env variable TORCHDYNAMO_REPORT_GUARD_FAILURES=1 and also see https://pytorch.org/docs/master/compile/troubleshooting.html.</td>
    </tr>
    <tr>
      <td>detectron2_fasterrcnn_r_50_c4</td>
      <td>X</td>
      <td>&#10003</td>
      <td>torchbench</td>
      <td>detectron2_fasterrcnn_r_50_c4, [2023-10-30 22:38:14 498] torch._dynamo.convert_frame: [WARNING] to diagnose recompilation issues  set env variable TORCHDYNAMO_REPORT_GUARD_FAILURES=1 and also see https://pytorch.org/docs/master/compile/troubleshooting.html.</td>
    </tr>
    <tr>
      <td>detectron2_fasterrcnn_r_50_dc5</td>
      <td>X</td>
      <td>&#10003</td>
      <td>torchbench</td>
      <td>detectron2_fasterrcnn_r_50_dc5, [2023-10-30 22:38:14 498] torch._dynamo.convert_frame: [WARNING] to diagnose recompilation issues  set env variable TORCHDYNAMO_REPORT_GUARD_FAILURES=1 and also see https://pytorch.org/docs/master/compile/troubleshooting.html.</td>
    </tr>
    <tr>
      <td>detectron2_fasterrcnn_r_50_fpn</td>
      <td>X</td>
      <td>&#10003</td>
      <td>torchbench</td>
      <td>detectron2_fasterrcnn_r_50_fpn, [2023-10-30 22:38:14 498] torch._dynamo.convert_frame: [WARNING] to diagnose recompilation issues  set env variable TORCHDYNAMO_REPORT_GUARD_FAILURES=1 and also see https://pytorch.org/docs/master/compile/troubleshooting.html.</td>
    </tr>
  </tbody>
</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>0a16ad0</td>
      <td>f5088d2</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>7617d3f5</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td>ede4309</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td>45e4b8c</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td>4ac707a</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td>d76d92c</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>e6efc29</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info(nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>7617d3f5</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+gite6efc29</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.16.0a0+8636bf3</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+142d029</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+475b6ae</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+eb9bf61</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
    </tr>
  </tbody>
</table><p>image: docker pull ccr-registry.caas.intel.com/pytorch/pt_inductor:2023_10_30_aws</p>

<p>Repro</p>
<a href=https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh>
  inductor_single_run.sh </a>
<code>
bash inductor_single_run.sh single inference accuracy torchbench detectron2_fasterrcnn_r_101_dc5 float32 first static default 0
</code>

<p><a href="https://github.com/pytorch/pytorch/commit/e38347f490ae14bf96913a19e7dab9b5e752c276">
  Suspected guilty commit </a></p>

[torchbench-detectron2_fasterrcnn_r_101_dc5-inference-float32-static-default-accuracy-single-crash_guilty_commit.log](https://github.com/pytorch/pytorch/files/13425761/torchbench-detectron2_fasterrcnn_r_101_dc5-inference-float32-static-default-accuracy-single-crash_guilty_commit.log)

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by davidberard98** [comment]
@WeizhuoZhang-intel "the suspected guilty commit" points to this issue, can you update it if you know the cause?

**Comment by chuanqi129** [comment]
Suspected guilty commit: e38347f490ae14bf96913a19e7dab9b5e752c276
[torchbench-detectron2_fasterrcnn_r_101_dc5-inference-float32-static-default-accuracy-single-crash_guilty_commit.log](https://github.com/pytorch/pytorch/files/13425761/torchbench-detectron2_fasterrcnn_r_101_dc5-inference-float32-static-default-accuracy-single-crash_guilty_commit.log)

**Comment by Le-Zheng** [comment]
@Chillee we found commit: e38347f490ae14bf96913a19e7dab9b5e752c276 cause this issue. Could you please take a look on this issue?

**Comment by leslie-fang-intel** [comment]
@Chillee Could you help to take a look of this issue?

**Comment by leslie-fang-intel** [comment]
@Chillee Could you help to take a look of this issue?

**Comment by penguinwu** [comment]
@Le-Zheng  -- Are the tests still failing on the latest trunk?

**Comment by leslie-fang-intel** [comment]
> @Le-Zheng -- Are the tests still failing on the latest trunk?

@chuanqi129 @zxd1997066 could you help to check the latest test report?

**Comment by chuanqi129** [comment]
Double checked the latest test report, the issue has been fixed
