### ISSUE TITLE
Show warning when compiling the optimizer and grads are going to be copied to cudagraph-owned memory

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#112548]
### 🚀 The feature, motivation and pitch

Currently when cudagraphing the optimizer in isolation, it's possible that the grads are not from an upstream cudagraph. The solution in this case is to mark the grads as static using the `mark_static_address` API.   Inductor will generate a copy for each grad in this case, catastrophically impacting perf, so we should print a warning in this case. 

cc @mcarilli @ezyang @eellison @peterbell10 @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @wconstab

**Comment by zhxchen17** [comment]
Hi @mlazos and I'm cleaning up old issues and wondering whether this issue has been resolved, or do you plan to work on this recently? Thanks :)

**Comment by mlazos** [comment]
Yeah I do plan to work on this
