### ISSUE TITLE
Raise AttributeError in Module.__getattr__ ?

### ISSUE THREAD

**Issue by elanmart** [pytorch/pytorch#1126]
Hi, 

Is there a reason why `Module.__getattr__` calls `object.__getattr__` and doesn't raise `AttributeError`?
It would improve readability of error messages. Currently, when users makes a typo and tries to call 
`model.cdua()` instead of `model.cuda()`, a rather unhelpful message appears:

```python
.../torch/nn/modules/module.py in __getattr__(self, name)
    235             if name in modules:
    236                 return modules[name]
--> 237         return object.__getattr__(self, name)
    238 
    239     def __setattr__(self, name, value):

AttributeError: type object 'object' has no attribute '__getattr__'
```

So perhaps it would be nice to just call 
```python
raise AttributeError("'Module' object has no attribute '{name}'".format(name=name))
```

ref
https://github.com/pytorch/pytorch/blob/3eab8a71e279cad0326f4bfb47e3d7ad1d67b816/torch/nn/modules/module.py#L237

**Comment by apaszke** [comment]
It's a bug. We should redirect the `__getattr__` to the superclass and let it raise the error, but apparently `object` doesn't support it.

**Comment by KelleyYin** [comment]
![11](https://user-images.githubusercontent.com/30852232/30656142-a2b3dae6-9e65-11e7-8613-97ba7c38351e.png)
how to solve this problem?  why this error could be caused?
looking forward to reply!    thanks!
