### ISSUE TITLE
DISABLED test_resnet18_cpu (__main__.BenchmarkFusionCpuTest)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#112615]
Platforms: mac, macos

This test was disabled because it is failing on main branch ([recent examples](https://hud.pytorch.org/failure?name=periodic%20%2F%20macos-12-py3-x86-64%20%2F%20test%20(default%2C%203%2C%204%2C%20macos-12)&jobName=macos-12-py3-x86-64%20%2F%20test%20(default%2C%203%2C%204%2C%20macos-12)&failureCaptures=%5B%22inductor%2Ftest_benchmark_fusion.py%3A%3ABenchmarkFusionCpuTest%3A%3Atest_resnet18_cpu%22%5D)).

This new test starts failing in MacOS x86 trunk, for example https://hud.pytorch.org/pytorch/pytorch/commit/748c1a1d81400cbb067c0e15c3769e137cce57f4.  This is introduced by https://github.com/pytorch/pytorch/pull/112450.

cc @malfet @albanD @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by leslie-fang-intel** [comment]
Test PyTorch Master: 3c9076f070fab5b27eae3b7846755c98b7c97a1a
```
python -m pytest test_benchmark_fusion.py -k test_resnet18
```
It passes on my local system.
Hi @huydhn @eellison, any thing we need to do to close this issue?

**Comment by leslie-fang-intel** [comment]
I will close this due to reasons mentioned above. @huydhn feel free to reopen if any further questions.
