### ISSUE TITLE
Fix docstring errors in default_hooks.py, optimizer_overlap.py, checkpoint_wrapper.py, copy.py, benchmark_ddp_rpc.py, utils.py, dependency.py, phony.py, pipeline.py, checkpoint.py, worker.py, batchnorm.py, quantization.py

### ISSUE THREAD

**Issue by svekars** [pytorch/pytorch#112645]
Please fix the following issues. To test locally, run: 
 ```
pydocstyle path-to-file --count
```
Run this command before and after fixing the errors. This command prints out the number of errors at the end of the output. Paste the output to your PR description with the number before and after. 
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `ActivationWrapper`, **Line**: 22, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `named_parameters`, **Line**: 58, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `named_parameters`, **Line**: 58, **Description**: First line should end with a period (not 'd')
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `named_parameters`, **Line**: 58, **Description**: First line should be in imperative mood (perhaps 'Override', not 'Overrides')
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `named_parameters`, **Line**: 58, **Description**: First line should not be the function's "signature"
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `_post_state_dict_hook`, **Line**: 72, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `_post_state_dict_hook`, **Line**: 72, **Description**: First line should end with a period (not 's')
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `_post_state_dict_hook`, **Line**: 72, **Description**: First line should not be the function's "signature"
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `_pre_load_state_dict_hook`, **Line**: 90, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `_pre_load_state_dict_hook`, **Line**: 90, **Description**: First line should end with a period (not '`')
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `CheckpointWrapper`, **Line**: 109, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `CheckpointWrapper`, **Line**: 109, **Description**: First line should end with a period (not 's')
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `offload_wrapper`, **Line**: 173, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `offload_wrapper`, **Line**: 173, **Description**: First line should end with a period (not 'd')
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `offload_wrapper`, **Line**: 173, **Description**: First line should be in imperative mood; try rephrasing (found 'A')
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `checkpoint_wrapper`, **Line**: 200, **Description**: No blank lines allowed after function docstring (found 1)
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `checkpoint_wrapper`, **Line**: 200, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `checkpoint_wrapper`, **Line**: 200, **Description**: First line should end with a period (not 'd')
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `checkpoint_wrapper`, **Line**: 200, **Description**: First line should be in imperative mood; try rephrasing (found 'A')
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `apply_activation_checkpointing`, **Line**: 252, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `apply_activation_checkpointing`, **Line**: 252, **Description**: First line should end with a period (not 'd')
- **File**: `torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py`, **Entity**: `apply_activation_checkpointing`, **Line**: 252, **Description**: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
- **File**: `torch/distributed/algorithms/_optimizer_overlap/optimizer_overlap.py`, **Entity**: `__init__`, **Line**: 36, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_optimizer_overlap/optimizer_overlap.py`, **Entity**: `__init__`, **Line**: 36, **Description**: First line should end with a period (not 'o')
- **File**: `torch/distributed/algorithms/_optimizer_overlap/optimizer_overlap.py`, **Entity**: `__init__`, **Line**: 36, **Description**: First word of the first line should be properly capitalized ('Overlappedoptimizer', not 'OverlappedOptimizer')
- **File**: `torch/distributed/algorithms/_optimizer_overlap/optimizer_overlap.py`, **Entity**: `register_ddp`, **Line**: 43, **Description**: First line should be in imperative mood (perhaps 'Register', not 'Registers')
- **File**: `torch/distributed/algorithms/_optimizer_overlap/optimizer_overlap.py`, **Entity**: `register_fsdp`, **Line**: 49, **Description**: First line should be in imperative mood (perhaps 'Register', not 'Registers')
- **File**: `torch/distributed/algorithms/_optimizer_overlap/optimizer_overlap.py`, **Entity**: `_as_overlapped_optim`, **Line**: 76, **Description**: One-line docstring should fit on one line with quotes (found 3)
- **File**: `torch/distributed/algorithms/_optimizer_overlap/optimizer_overlap.py`, **Entity**: `_as_overlapped_optim`, **Line**: 76, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `DefaultState`, **Line**: 7, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `DefaultState`, **Line**: 7, **Description**: First line should end with a period (not 'm')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `LowPrecisionState`, **Line**: 44, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `LowPrecisionState`, **Line**: 44, **Description**: First line should end with a period (not 'n')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `_decompress`, **Line**: 69, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `_decompress`, **Line**: 69, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `allreduce_hook`, **Line**: 79, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `allreduce_hook`, **Line**: 79, **Description**: First line should end with a period (not 'm')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `allreduce_hook`, **Line**: 79, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `reduce_scatter_hook`, **Line**: 98, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `reduce_scatter_hook`, **Line**: 98, **Description**: First line should end with a period (not 'r')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `reduce_scatter_hook`, **Line**: 98, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `fp16_compress_hook`, **Line**: 131, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `fp16_compress_hook`, **Line**: 131, **Description**: First line should end with a period (not 'n')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `fp16_compress_hook`, **Line**: 131, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `bf16_compress_hook`, **Line**: 148, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `bf16_compress_hook`, **Line**: 148, **Description**: First line should end with a period (not 'n')
- **File**: `torch/distributed/algorithms/_comm_hooks/default_hooks.py`, **Entity**: `bf16_compress_hook`, **Line**: 148, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/distributed/algorithms/_quantization/quantization.py`, **Entity**: `DQuantType`, **Line**: 13, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/distributed/algorithms/_quantization/quantization.py`, **Entity**: `DQuantType`, **Line**: 13, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_quantization/quantization.py`, **Entity**: `auto_quantize`, **Line**: 90, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/algorithms/_quantization/quantization.py`, **Entity**: `auto_quantize`, **Line**: 90, **Description**: First line should end with a period (not 'd')
- **File**: `torch/distributed/algorithms/_quantization/quantization.py`, **Entity**: `auto_quantize`, **Line**: 90, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `HybridModel`, **Line**: 34, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `HybridModel`, **Line**: 34, **Description**: Docstring is under-indented
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `HybridModel`, **Line**: 34, **Description**: First line should end with a period (not 'n')
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `_run_trainer`, **Line**: 119, **Description**: No blank lines allowed after function docstring (found 1)
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `_run_trainer`, **Line**: 119, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `_run_trainer`, **Line**: 119, **Description**: Docstring is under-indented
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `_run_trainer`, **Line**: 119, **Description**: First line should end with a period (not 'e')
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `run_worker`, **Line**: 201, **Description**: No blank lines allowed after function docstring (found 1)
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `run_worker`, **Line**: 201, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `run_worker`, **Line**: 201, **Description**: Docstring is under-indented
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `run_worker`, **Line**: 201, **Description**: First line should end with a period (not 'n')
- **File**: `torch/distributed/benchmarks/benchmark_ddp_rpc.py`, **Entity**: `run_worker`, **Line**: 201, **Description**: First line should be in imperative mood; try rephrasing (found 'A')
- **File**: `torch/distributed/pipeline/sync/batchnorm.py`, **Entity**: `DeferredBatchNorm`, **Line**: 24, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/batchnorm.py`, **Entity**: `DeferredBatchNorm`, **Line**: 24, **Description**: First line should end with a period (not 'g')
- **File**: `torch/distributed/pipeline/sync/batchnorm.py`, **Entity**: `_commit`, **Line**: 73, **Description**: First line should be in imperative mood (perhaps 'Update', not 'Updates')
- **File**: `torch/distributed/pipeline/sync/batchnorm.py`, **Entity**: `convert_deferred_batch_norm`, **Line**: 136, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/batchnorm.py`, **Entity**: `convert_deferred_batch_norm`, **Line**: 136, **Description**: First line should end with a period (not 'g')
- **File**: `torch/distributed/pipeline/sync/batchnorm.py`, **Entity**: `convert_deferred_batch_norm`, **Line**: 136, **Description**: First line should be in imperative mood (perhaps 'Convert', not 'Converts')
- **File**: `torch/distributed/pipeline/sync/copy.py`, **Entity**: ``, **Line**: 7, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/copy.py`, **Entity**: ``, **Line**: 7, **Description**: First line should end with a period (not 'y')
- **File**: `torch/distributed/pipeline/sync/dependency.py`, **Entity**: `join`, **Line**: 40, **Description**: First line should be in imperative mood (perhaps 'Merge', not 'Merges')
- **File**: `torch/distributed/pipeline/sync/phony.py`, **Entity**: `get_phony`, **Line**: 22, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/phony.py`, **Entity**: `get_phony`, **Line**: 22, **Description**: First line should end with a period (not 'e')
- **File**: `torch/distributed/pipeline/sync/phony.py`, **Entity**: `get_phony`, **Line**: 22, **Description**: First line should be in imperative mood (perhaps 'Get', not 'Gets')
- **File**: `torch/distributed/pipeline/sync/pipeline.py`, **Entity**: `_clock_cycles`, **Line**: 65, **Description**: First line should be in imperative mood (perhaps 'Generate', not 'Generates')
- **File**: `torch/distributed/pipeline/sync/pipeline.py`, **Entity**: `run`, **Line**: 102, **Description**: First line should be in imperative mood (perhaps 'Run', not 'Runs')
- **File**: `torch/distributed/pipeline/sync/pipeline.py`, **Entity**: `fence`, **Line**: 123, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/pipeline.py`, **Entity**: `fence`, **Line**: 123, **Description**: First line should end with a period (not 's')
- **File**: `torch/distributed/pipeline/sync/pipeline.py`, **Entity**: `fence`, **Line**: 123, **Description**: First line should be in imperative mood (perhaps 'Copy', not 'Copies')
- **File**: `torch/distributed/pipeline/sync/pipeline.py`, **Entity**: `compute`, **Line**: 148, **Description**: First line should be in imperative mood (perhaps 'Run', not 'Runs')
- **File**: `torch/distributed/pipeline/sync/utils.py`, **Entity**: `partition_model`, **Line**: 10, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/utils.py`, **Entity**: `partition_model`, **Line**: 10, **Description**: First line should end with a period (not 's')
- **File**: `torch/distributed/pipeline/sync/worker.py`, **Entity**: `worker`, **Line**: 70, **Description**: First line should be in imperative mood; try rephrasing (found 'The')
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `checkpoint`, **Line**: 71, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `checkpoint`, **Line**: 71, **Description**: First line should end with a period (not 'e')
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `checkpoint`, **Line**: 71, **Description**: First line should be in imperative mood (perhaps 'Make', not 'Makes')
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `checkpoint`, **Line**: 97, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `recompute`, **Line**: 115, **Description**: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `enable_checkpointing`, **Line**: 139, **Description**: First line should be in imperative mood (perhaps 'Make', not 'Makes')
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `enable_recomputing`, **Line**: 150, **Description**: First line should be in imperative mood (perhaps 'Make', not 'Makes')
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `is_recomputing`, **Line**: 170, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `is_recomputing`, **Line**: 170, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `Context`, **Line**: 194, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `Context`, **Line**: 194, **Description**: First line should end with a period (not 'd')
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `save_rng_states`, **Line**: 211, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `save_rng_states`, **Line**: 211, **Description**: First line should end with a period (not 'r')
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `restore_rng_states`, **Line**: 230, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/pipeline/sync/checkpoint.py`, **Entity**: `restore_rng_states`, **Line**: 230, **Description**: First line should end with a period (not 's')

cc @carljparker

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are working on this issue, assign it to yourself and send a PR ASAP.

**Comment by ash-01xor** [comment]
/assigntome

Yep working on it will send a PR by today.
