### ISSUE TITLE
Fix docstring errors in zero_redundancy_optimizer.py

### ISSUE THREAD

**Issue by svekars** [pytorch/pytorch#112642]
Please fix the following issues. To test locally, run: 
 ```
pydocstyle path-to-file --count
```
Run this command before and after fixing the errors. This command prints out the number of errors at the end of the output. Paste the output to your PR description with the number before and after. 
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_recursive_copy_to_device`, **Line**: 33, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_recursive_copy_to_device`, **Line**: 33, **Description**: First line should end with a period (not 'f')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_is_trainable`, **Line**: 63, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_is_trainable`, **Line**: 63, **Description**: First line should end with a period (not 'o')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_is_trainable`, **Line**: 63, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_broadcast_object`, **Line**: 76, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_broadcast_object`, **Line**: 76, **Description**: First line should end with a period (not 'm')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `main_hook`, **Line**: 123, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `main_hook`, **Line**: 123, **Description**: First line should end with a period (not 'f')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `main_hook`, **Line**: 123, **Description**: First line should be in imperative mood (perhaps 'Perform', not 'Performs')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_DDPBucketAssignment`, **Line**: 131, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_DDPBucketAssignment`, **Line**: 131, **Description**: First line should end with a period (not ',')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_OverlapStatus`, **Line**: 167, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_OverlapStatus`, **Line**: 167, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_OverlapStatus`, **Line**: 167, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_OverlapInfo`, **Line**: 186, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_OverlapInfo`, **Line**: 186, **Description**: First line should end with a period (not '`')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `wait_for_broadcasts`, **Line**: 253, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `wait_for_broadcasts`, **Line**: 253, **Description**: First line should end with a period (not 'l')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `wait_for_broadcasts`, **Line**: 253, **Description**: First line should be in imperative mood (perhaps 'Wait', not 'Waits')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `clear_per_iter_info`, **Line**: 266, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `clear_per_iter_info`, **Line**: 266, **Description**: First line should end with a period (not 'd')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `clear_per_iter_info`, **Line**: 266, **Description**: First line should be in imperative mood (perhaps 'Clear', not 'Clears')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `ZeroRedundancyOptimizer`, **Line**: 276, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `ZeroRedundancyOptimizer`, **Line**: 276, **Description**: First line should end with a period (not 'r')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_clear_cache`, **Line**: 442, **Description**: One-line docstring should fit on one line with quotes (found 3)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_clear_cache`, **Line**: 442, **Description**: First line should be in imperative mood (perhaps 'Clear', not 'Clears')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `consolidate_state_dict`, **Line**: 499, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `consolidate_state_dict`, **Line**: 499, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_verify_params_per_rank`, **Line**: 584, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_verify_params_per_rank`, **Line**: 584, **Description**: First line should end with a period (not ',')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_verify_params_per_rank`, **Line**: 584, **Description**: First line should be in imperative mood (perhaps 'Verify', not 'Verifies')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_partition_param_group`, **Line**: 616, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_partition_param_group`, **Line**: 616, **Description**: First line should end with a period (not 'o')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_param_to_rank`, **Line**: 709, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_param_to_rank`, **Line**: 709, **Description**: First line should end with a period (not 'k')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_param_to_index`, **Line**: 722, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_param_to_index`, **Line**: 722, **Description**: First line should end with a period (not 'l')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_index_to_param`, **Line**: 738, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_index_to_param`, **Line**: 738, **Description**: First line should end with a period (not 'e')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_broadcast_params_from_rank`, **Line**: 749, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_broadcast_params_from_rank`, **Line**: 749, **Description**: First line should end with a period (not 'r')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_sync_params`, **Line**: 798, **Description**: First line should be in imperative mood (perhaps 'Sync', not 'Syncs')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_device_to_params_per_rank`, **Line**: 816, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_device_to_params_per_rank`, **Line**: 816, **Description**: First line should end with a period (not 'r')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_min_index`, **Line**: 859, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_min_index`, **Line**: 859, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_min_index`, **Line**: 859, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_assign_bucket_subset_to_rank`, **Line**: 887, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_assign_bucket_subset_to_rank`, **Line**: 887, **Description**: First line should end with a period (not 'a')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_assign_bucket_subset_to_rank`, **Line**: 887, **Description**: First line should be in imperative mood (perhaps 'Assign', not 'Assigns')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_bucket_assignments_per_rank`, **Line**: 921, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_bucket_assignments_per_rank`, **Line**: 921, **Description**: First line should end with a period (not 's')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_local_step`, **Line**: 1018, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_local_step`, **Line**: 1018, **Description**: First line should end with a period (not 's')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_local_step`, **Line**: 1018, **Description**: First line should be in imperative mood (perhaps 'Perform', not 'Performs')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `step`, **Line**: 1092, **Description**: First line should be in imperative mood (perhaps 'Perform', not 'Performs')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `join_hook`, **Line**: 1119, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `join_hook`, **Line**: 1119, **Description**: First line should end with a period (not 'y')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `join_hook`, **Line**: 1119, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `load_state_dict`, **Line**: 1145, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `load_state_dict`, **Line**: 1145, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `state_dict`, **Line**: 1184, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_sync_param_groups`, **Line**: 1252, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_sync_param_groups`, **Line**: 1252, **Description**: First line should end with a period (not 'e')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_sync_param_groups`, **Line**: 1252, **Description**: First line should be in imperative mood (perhaps 'Sync', not 'Syncs')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_build_param_buckets`, **Line**: 1275, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_build_param_buckets`, **Line**: 1275, **Description**: First line should end with a period (not 'o')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_build_param_buckets`, **Line**: 1275, **Description**: First line should be in imperative mood (perhaps 'Build', not 'Builds')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_build_ddp_param_buckets`, **Line**: 1335, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_build_ddp_param_buckets`, **Line**: 1335, **Description**: First line should end with a period (not 'e')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_verify_and_init_params`, **Line**: 1377, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_verify_and_init_params`, **Line**: 1377, **Description**: First line should end with a period (not '`')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_verify_and_init_params`, **Line**: 1377, **Description**: First line should be in imperative mood (perhaps 'Verify', not 'Verifies')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_verify_same_dense_param_type`, **Line**: 1434, **Description**: First line should be in imperative mood (perhaps 'Verify', not 'Verifies')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_is_trainable_mask`, **Line**: 1465, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_is_trainable_mask`, **Line**: 1465, **Description**: First line should end with a period (not 'e')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_is_trainable_mask`, **Line**: 1465, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_init_local_optimizer`, **Line**: 1472, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_init_local_optimizer`, **Line**: 1472, **Description**: First line should end with a period (not 'f')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_init_local_optimizer`, **Line**: 1472, **Description**: First line should be in imperative mood (perhaps 'Initialize', not 'Initializes')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_init_zero_for_overlap`, **Line**: 1546, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_init_zero_for_overlap`, **Line**: 1546, **Description**: First line should end with a period (not 'e')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_init_zero_for_overlap`, **Line**: 1546, **Description**: First line should be in imperative mood (perhaps 'Perform', not 'Performs')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_assigned_rank`, **Line**: 1561, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_assigned_rank`, **Line**: 1561, **Description**: First line should end with a period (not '`')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_assigned_rank`, **Line**: 1561, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_check_overlap_initialized`, **Line**: 1577, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_check_overlap_initialized`, **Line**: 1577, **Description**: First line should end with a period (not 'e')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_check_overlap_initialized`, **Line**: 1577, **Description**: First line should be in imperative mood (perhaps 'Check', not 'Checks')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_optimizer_constructor`, **Line**: 1598, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_optimizer_constructor`, **Line**: 1598, **Description**: First line should end with a period (not 'y')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_optimizer_constructor`, **Line**: 1598, **Description**: First line should be in imperative mood (perhaps 'Return', not 'Returns')
- **File**: `torch/distributed/optim/zero_redundancy_optimizer.py`, **Entity**: `_get_optimizer_constructor`, **Line**: 1598, **Description**: No blank lines allowed between a section header and its content ('Returns')

cc @carljparker

**Comment by spzala** [comment]
WIP
