### ISSUE TITLE
[dynamo] direct invocation of bound method introduces graph break

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#112670]
```
import torch

class MethodProvider:
    def some_method(self, x):
        return x + x

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.bound_method = MethodProvider().some_method
    
    def forward(self, x):
        return self.bound_method(x)

torch.export.export(MyModule(), (torch.rand(2, 3),))
```
produces
```
Unsupported: call_function UserDefinedObjectVariable(some_method) [TensorVariable()] {}
```

We should be inlining into this, but it looks like our builder case for methods is restricted to nn.Module only: https://github.com/pytorch/pytorch/blob/00d6d2f66bb23e9ab2b810a98c179ec2f217ec5c/torch/_dynamo/variables/builder.py#L768-L782

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by andrewlee302** [comment]
@tugsbayasgalan recently shared this discussion and the context to me. To help me understand it better, I put a snippet here:
```
import torch

class MethodProvider:
    def some_method(self, x):
        return x + x

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.bound_method = MethodProvider().some_method
    
    def forward(self, x):
        return self.bound_method(x)

# torch.export.export(MyModule(), (torch.rand(2, 3),))

from torch.fx.experimental.proxy_tensor import make_fx
gm = make_fx(MyModule())(torch.randn(4, 4))
print(gm.graph)
```

`make_fx` successfully parses the code but current export fails, which demonstrates the parse logic of current `export` could be relaxed, to cover more cases that can be safely parsed. Feel free to correct me.

**Comment by tugsbayasgalan** [comment]
@andrewlee302 Yes. That is what we are looking for (non-strict export mode). Just one gotcha is that, we are not supposed to use make_fx directly in export because export contract requires the graph we produce to be functional (no side effects). For example, if you trace:
```python
def f(x):
      y = x + 2 
      y.add_(2)
      return x + y
```
make_fx would produce:
```
graph():
      y = call_function(torch.ops.aten.add)(x, 2)
      y1 = call_function(torch.ops.aten.add_)(y, 2) -> this is not functional
      return y1 + x
```
aot_export_module would produce:
```
graph():
      y = call_function(torch.ops.aten.add)(x, 2)
      y1 = call_function(torch.ops.aten.add)(y, 2) -> this is functional
      return y1 + x
```
Your goal is to make:
```
def export(callable, non_strict):
      if non_strict: 
           return aot_export_module(callable) 
 ```

**Comment by zhxchen17** [comment]
This seems to be resolved on main branch already. Today I did a local test and the repro can be exported successfully.
