### ISSUE TITLE
'aten::unique_consecutive' to ONNX opset version 14 is not supported

### ISSUE THREAD

**Issue by MaiZhiHao** [pytorch/pytorch#112718]
### 🐛 Describe the bug

        if past_keys is not None:
            past_keys = past_keys.unique_consecutive(dim=2) # unique_consecutive is not supported by ONNX ..
            past_values = past_values.unique_consecutive(dim=2)
            print("the shape after unique",past_keys.shape,past_values.shape)

### Versions

    When I run torch.onnx.export .
I found unique_consecutive is not supported on Onnx .
#1 Can we use another API to instead of unique_consecutive  ?
#2 Can we support unique_consecutive  on ONNX ?

raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::unique_consecutive' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

**Comment by MaiZhiHao** [comment]
with torch.no_grad():
        torch.onnx.export(lm_model,
                            args=inputs,
                            do_constant_folding=False,
                            f=r'1102_has_past_lm.onnx', export_params=True, opset_version=18,
                            input_names=['sequence','condition_tensors1','condition_tensors2',
                                         'past_keys','past_values','past_offsets',],
                            output_names=['all_logits','new_past_keys','new_past_values','past_offsets2'],
                            verbose=True)


Traceback (most recent call last):
  File "C:\work\20230825\debug\test_audio_craft.py", line 83, in <module>
    torch.onnx.export(lm_model,
  File "C:\Users\MaiZhiHao\anaconda3\envs\py39\lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "C:\Users\MaiZhiHao\anaconda3\envs\py39\lib\site-packages\torch\onnx\utils.py", line 1608, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\MaiZhiHao\anaconda3\envs\py39\lib\site-packages\torch\onnx\utils.py", line 1139, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\MaiZhiHao\anaconda3\envs\py39\lib\site-packages\torch\onnx\utils.py", line 677, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\MaiZhiHao\anaconda3\envs\py39\lib\site-packages\torch\onnx\utils.py", line 1962, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::unique_consecutive' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

**Comment by justinchuby** [comment]
It is possible to implement a custom symbolic function with the ONNX `Unique` operator by setting `sorted=0`. 

Consider implementing a symbolic function

https://github.com/pytorch/pytorch/blob/b4ce5011379e62876218aff43646221106892196/aten/src/ATen/native/native_functions.yaml#L6159

```python
def unique_consecutive(g, self, return_inverse, return_counts, dim):
    ...
   # Implementation by calling g.op("Unique", ...)

# Register custom symbolic function
torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::unique_consecutive",
    symbolic_fn=unique_consecutive,
    opset_version=14,
)
```

**Comment by justinchuby** [comment]
OK it only removes consecutive duplicate values. It's different than what ONNX Unique does

**Comment by justinchuby** [comment]
cc @BowenBao
