### ISSUE TITLE
PT2: don't always require inputs to be aligned

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#112771]
### 🚀 The feature, motivation and pitch

If you have an input that's very large and which is a view that's not 16-byte aligned, the input will get copied in each invocation.

We should make it possible to not require alignment. To do this, we need to:
* guard on storage_offset in dynamo
* inductor compile_fx / graph : record the alignment info, ensure that the alignment info generates the right kind of guards
* inductor scheduler / codegen : check alignment info, don't assume that all inputs are aligned.
* config : figure out a good way to configure this behavior; should it be default? should it only matter for inputs to matmuls? should we align only small tensors?

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @wconstab

**Comment by jon-chuang** [comment]
Hmm, could you post a small repro for what you mean?

**Comment by zhxchen17** [comment]
Hi @davidberard98 I saw you landed a PR recently referencing this issue. Do you think this issue is resolved now?
