### ISSUE TITLE
Pad a list of tensors

### ISSUE THREAD

**Issue by ZeweiChu** [pytorch/pytorch#1128]
Taking in a list of tensors, can we have a function to pad them? This is a useful feature to process sequences of different lengths and process mini batches. 

I think the documentation of pad_packed_sequence and torch.nn.utils.rnn.pack_padded_sequence are a little confusing http://pytorch.org/docs/nn.html?highlight=pad_packed#torch.nn.utils.rnn.pad_packed_sequence maybe adding some examples could help the explanation.

**Comment by yuhaozhang** [comment]
I will second this request. This will be particularly useful for NLP researchers.

In addition, what is the most efficient way to pad a 1D tensor in Pytorch, apart from manually concatenating a zero tensor to it? The built-in `torch.nn.functional.pad()` function does not seem to work for 1D tensors.

**Comment by szagoruyko** [comment]
@yuhaozhang F.pad() works for 1D tensors if you add an extra dimension

**Comment by yuhaozhang** [comment]
@szagoruyko Thanks. Maybe I am wrong, but the source code (`http://pytorch.org/docs/_modules/torch/nn/functional.html#pad`) seems a bit confusing. The documentation of the function says "Currently only 2D and 3D padding supported", while the implementation suggests that "Only 4D and 5D padding is supported for now".

**Comment by chenzhekl** [comment]
@yuhaozhang The padding function you described may be different from what is needed by @ZeweiChu . `F.pad()` is used for padding an image or a 3D volume. 2D padding means it pads the four borders of a 2D image, and 3D padding pads the extra front and back besides the four borders. The description of the function is correct. If you look closely, the requirement of the dimension is on the `pad` tensor rather than the input.

In NLP, if it is needed to pad sequences of different lengths, `pack_padded_sequence` and `pack_padded_sequence` may be better choice. The release note of `v0.1.10` is definitely a good example.

**Comment by Spider101** [comment]
@yuhaozhang To accomplish two dimensional padding, you need an input tensor with 4 axes and similarly for three dimensional padding, you need an input tensor with 6 axes. That is my interpretation of the source code, I may be mistaken.

**Comment by neverfox** [comment]
@szagoruyko For example:

```
import torch.nn.functional as F

input = Variable(torch.rand(1, 1, 10)) # 1D (N, C, L)
input_2d = input.unsqueeze(2) # add a fake height
F.pad(input_2d, (2, 0, 0, 0)).view(1, 1, -1) # left padding (and remove height)
F.pad(input_2d, (0, 2, 0, 0)).view(1, 1, -1) # right padding (and remove height)
```

**Comment by Yevgnen** [comment]
Have we had an example in Sep 2017?

**Comment by soumith** [comment]
as of last week, `F.pad` now supports all dimensional Tensors, 1D, 2D, 3D, etc.

**Comment by hhsecond** [comment]
@apaszke I would love to work on this feature if this hasn't started yet. Do you have a preferred approach?
I was thinking if we have a function `fill_with_zeros` or something that takes list of different length lists, seq_length and dtype and returns a tensor of mentioned type with mentioned length made either by truncation or by padding with zero

**Comment by apaszke** [comment]
@hhsecond Yes, that would be great! I think it should be in `torch.nn.utils.rnn` and be named `pad_sequence`. It should get three arguments: a list of sequences (Tensors) sorted by length in decreasing order, a list of their lengths, and `batch_first` boolean. It's similar to `pack_padded_sequence`, except that the first argument would be a list of Variables instead of a single Variable.

It would also be useful to add `pack_sequence` which would be like `pack_padded_sequence(pad_sequence(input, lengths), lengths)`, but more efficient (no need to have the padded intermediate).

**Comment by hhsecond** [comment]
@apaszke Sounds perfect, one quick question though. Wouldn't it be good if the function accepts a list of python lists (and desired sequence length as argument) where each list can be of varying length where if it only accepts tensors, the user has to convert each sentence to a tensor (assuming each sentence is of different length) separately before passing that to the `pad_sequence`. Perhaps, we can make it accept list or numpy array or tensor? something like
`pad_sequence(inputs, sequence_length, lengths)`

The `pack_sequence` sounds helpful, will do that as well.

**Comment by apaszke** [comment]
It can accept a list of lists, but it definitely should also accept a list of Variables

**Comment by hhsecond** [comment]
I guess [this](https://github.com/pytorch/pytorch/issues/3584) is a good idea to implement inside `pad_sequence` or `pack_sequence, any thoughts?

**Comment by hhsecond** [comment]
@apaszke Do have a decision on sorting as mentioned in the issue 3584? Do I need to handle that in the `pad_sequence` function? And I was having second thoughts about the acceptable dimensions? What all should be accepted.
- batch `x` seq_len `x` feature_len (batch will be 1 in most cases)
- seq_len `x` batch `x` feature_len (batch will be 1 in most cases)
- seq_len `x` feature_len
- more than 3 dimensions

Is this feature going in 0.3 release?

**Comment by apaszke** [comment]
Yes, handling that in `pad_sequence` would be good. I'm not sure what's the issue with the dimensions that should be accepted. I think the whole point is to accept Variables of arbitrary trailing dimensions, and concatenate them along a new one in such a way that they are padded with 0s if too small.

**Comment by apaszke** [comment]
If you implement it fairly quickly, we might still backport it to 0.3

**Comment by hhsecond** [comment]
@apaszke I'll try to make it into 0.3. 
The problem with dimensions is, in the case of 2 or more dimensional Variables, user could pass
- batch `x` seq_len (batch dim would be 1 mostly and we'll concatenating on zeroth dim)
- seq_len `x` feature_len (where user ignored batch dim, we'll be stacking on zeroth or 1st dimension depends on batch_first)
But how could we understand which dimension has variable length sequence. I can analyse the input and fetch this info or I can ask user to pass the dimension that needs padding?

**Comment by apaszke** [comment]
There's no way to tell if the batch dim is included. Since in most cases you'll want to concatenate the sentence to actually form a batch, I think defaulting to stacking makes sense

**Comment by hhsecond** [comment]
@apaszke I have made the PR #3875 with `pad_sequence` and `pack_sequence` but without internal sorting. As discussed in #3584, we will need to keep the track of original order. Perhaps we could return the order to the user and user has to pass that when he calls `pad_pack_sequence` to get the sequence in that order back. 

Another possible RNN utility: Like `pack_padded_sequence` and `pad_packed_sequence`, I was thinking about `unpack_sequence` that inverse the `pack_sequence` I have written now, this also could accept the actual order and returns the unpacked sequence in given order, any thoughts?

**Comment by apaszke** [comment]
I'm fine with `unpack_sequence`. Ordering is problematic, so let's stay away from it for now

**Comment by Diego999** [comment]
@hhsecond Maybe the answer is obvious but I cannot figure out why we could not give the desirable length for padding instead of sorting the tensor in decreasing length order. Maybe I have a bias from NLP ...

**Comment by Deepayan137** [comment]
@Diego999  @hhsecond  I also have the same question. Giving the desirable length of padding would make the task much simpler.

**Comment by Diego999** [comment]
@Deepayan137 Happy to not be the only one. By there way, my question is also related to pack_padded_sequence

**Comment by Deepayan137** [comment]
@Diego999  @hhsecond I was also wondering why do we need to first pad the seq to equal length manually and then pass it to pack_padded func to generate this PackedSequence object.
https://github.com/pytorch/pytorch/releases/tag/v0.1.10
Any Idea on this?

**Comment by Diego999** [comment]
@Deepayan137 Now there is this new function in master http://pytorch.org/docs/master/nn.html#torch.nn.utils.rnn.pad_sequence which will do the job for you. But as before, the list should be ordered by decreasing length

**Comment by Deepayan137** [comment]
``` bash
>>> from torch.nn.utils.rnn import pad_sequence
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'pad_sequence'
``` 
I have the latest version of pytorch
``` bash
print(torch.__version__)
0.3.1.post2
```
Any suggestion? What version are you using?

**Comment by Diego999** [comment]
@Deepayan137 the function is available only on master. You have to build from source

**Comment by Deepayan137** [comment]
Okay thanks a lot Diegio999 :+1:

**Comment by Diego999** [comment]
@Deepayan137  to answer the original question: https://discuss.pytorch.org/t/why-lengths-should-be-given-in-sorted-order-in-pack-padded-sequence/3540

**Comment by jshin49** [comment]
Is it possible to pack a padded 4d tensor for multi-turn dialog scenario?

(B x T x L x D)
