### ISSUE TITLE
UNSTABLE trunk / macos-12-py3-arm64-mps / test (mps)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#112832]
This starts failing in trunk with a missing package, the root cause is unclear, so I reopen this issue to keep trunk sane while investigate https://hud.pytorch.org/pytorch/pytorch/commit/53fff56ab8fead5b8829367730363c13e206975b

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Ok, grabbing for myself

**Comment by huydhn** [comment]
Fixed by https://github.com/pytorch/test-infra/pull/4697
