### ISSUE TITLE
"The repository '@pip_deps' could not be resolved" for Bazel builds

### ISSUE THREAD

**Issue by vymao** [pytorch/pytorch#112802]
### 🐛 Describe the bug

I am trying to build a project that uses torch as an external dependency using Bazel. Right now, it seems like I keep getting the following error when running bazel build: 

```
ERROR: Skipping '//main:main': error loading package 'main': Unable to find package for @pip_deps//:requirements.bzl: The repository '@pip_deps' could not be resolved: Repository '@pip_deps' is not defined.
WARNING: Target pattern parsing failed.
ERROR: error loading package 'main': Unable to find package for @pip_deps//:requirements.bzl: The repository '@pip_deps' could not be resolved: Repository '@pip_deps' is not defined.
INFO: Elapsed time: 1.598s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

I think it is being [defined in the WORKSPACE file](https://github.com/pytorch/pytorch/blob/v2.1.1-rc4/WORKSPACE#L214-L222), so I'm not sure of a fix here.

### Versions

[v2.1.1-rc4](https://github.com/pytorch/pytorch/blob/v2.1.1-rc4/WORKSPACE)

**Comment by malfet** [comment]
Thank you for filing the issue, but it feels like a question one should ask on https://dev-discuss.pytorch.org/ 

To the best of my knowledge, bazel configs are sensitive to the version of runtime, so perhaps you should use the same as one used in CI
