### ISSUE TITLE
[dynamo] nit - add `@torch.autocast` function decoration to the testing path

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#112848]
### 🚀 The feature, motivation and pitch

While I tested that this works, it should be on the testing path. We only test context manager usage e.g. `with torch.autocast`

### Alternatives

Not tested and not known when it breaks

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by SMateen21** [comment]
Hi, I'd like to try this as my first issue, could you please explain the issue further to me so I get a good idea on what's going on?

**Comment by jon-chuang** [comment]
You can try to add it to test/dynamo/test_ctx_manager.py, see more examples for decorator ctx managers there

**Comment by kmehant** [comment]
@jon-chuang There seems to be a test written (https://github.com/hyperfraise/pytorch/commit/bc3412c2f1df43efbd164760bd8744710ccb4ac9#diff-240053445b221ea2175c15d4c37f139adae373040cd0a686a621cadb62df0e4fR671) Are we still looking at expanding the existing test cases that use context manager with decorator as well? if yes, let me know, I wish to raise a PR.

**Comment by zhxchen17** [comment]
Hi @jon-chuang I'm cleaning up the old issues and it seems that we already have autocast decorator tested in dynamo today. I will close this for now and feel free to reopen this if you want. Thanks for raising the issue.
