### ISSUE TITLE
Cannot compile resnet18 using make_fx

### ISSUE THREAD

**Issue by yw-furiosa** [pytorch/pytorch#112821]
### 🐛 Describe the bug

When I try to compile resnet18 model from torchvision with my custom backend (only do make_fx), I got an error.
```python
import torch
import torchvision
from torch.fx.experimental.proxy_tensor import make_fx
from torch._dynamo.backends.common import aot_autograd

def backend(gm, inputs):
    return make_fx(gm, tracing_mode="fake", _allow_non_fake_inputs=True)(*inputs)
backend=aot_autograd(fw_compiler=backend)

m = torchvision.models.resnet18()
m = torch.compile(m, backend=backend, dynamic=False)
x = m(torch.randn(1, 3, 224, 224))
```

### Error logs

[2023-11-03 10:15:43,083] [0/0] torch.fx.experimental.symbolic_shapes: [WARNING] Failing guard allocated at:
[2023-11-03 10:15:43,083] [0/0] torch.fx.experimental.symbolic_shapes: [WARNING]
Traceback (most recent call last):
  File "/root/pytorch2.1/resnet.py", line 12, in <module>
    x = m(torch.randn(1, 3, 224, 224))
  File "/root/pytorch2.1/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/pytorch2.1/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/pytorch2.1/torch/_dynamo/eval_frame.py", line 410, in _fn
    return fn(*args, **kwargs)
  File "/root/pytorch2.1/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/pytorch2.1/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/pytorch2.1/torch/_dynamo/eval_frame.py", line 558, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/root/pytorch2.1/torch/_dynamo/convert_frame.py", line 690, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/root/pytorch2.1/torch/_dynamo/convert_frame.py", line 148, in _fn
    return fn(*args, **kwargs)
  File "/root/pytorch2.1/torch/_dynamo/convert_frame.py", line 406, in _convert_frame_assert
    return _compile(
  File "/root/pytorch2.1/torch/_dynamo/convert_frame.py", line 614, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/root/pytorch2.1/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/root/pytorch2.1/torch/_dynamo/convert_frame.py", line 594, in compile_inner
    check_fn = CheckFunctionManager(
  File "/root/pytorch2.1/torch/_dynamo/guards.py", line 982, in __init__
    guard.create(builder)
  File "/root/pytorch2.1/torch/_guards.py", line 244, in create
    return self.create_fn(builder, self)
  File "/root/pytorch2.1/torch/_dynamo/guards.py", line 641, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/root/pytorch2.1/torch/fx/experimental/symbolic_shapes.py", line 2627, in produce_guards
    issue_guard(guard)
  File "/root/pytorch2.1/torch/fx/experimental/symbolic_shapes.py", line 2594, in issue_guard
    guard_expr = ShapeGuardPrinter(symbol_to_source, source_ref, self.var_to_sources).doprint(expr)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/sympy/printing/printer.py", line 292, in doprint
    return self._str(self._print(expr))
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/sympy/printing/str.py", line 778, in _print_Relational
    return '%s %s %s' % (self.parenthesize(expr.lhs, precedence(expr)),
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/sympy/printing/str.py", line 38, in parenthesize
    return self._print(item)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/sympy/printing/str.py", line 57, in _print_Add
    t = self._print(term)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/root/pytorch2.1/torch/fx/experimental/symbolic_shapes.py", line 831, in _print_Symbol
    assert self.symbol_to_source.get(expr), (
AssertionError: s7 (could be from ['input122.size()[2]', 'input122.size()[3]']) not in {s7: [], s2: []}.  If this assert is failing, it could be due to the issue described in https://github.com/pytorch/pytorch/pull/90665

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

### Versions

Collecting environment information...
PyTorch version: 2.2.0a0+git2b2b6ca
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-72-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          192
On-line CPU(s) list:             0-191
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       4
NUMA node(s):                    4
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6348H CPU @ 2.30GHz
Stepping:                        11
CPU MHz:                         1000.000
CPU max MHz:                     4200.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       3 MiB
L2 cache:                        96 MiB
L3 cache:                        132 MiB
NUMA node0 CPU(s):               0-23,96-119
NUMA node1 CPU(s):               24-47,120-143
NUMA node2 CPU(s):               48-71,144-167
NUMA node3 CPU(s):               72-95,168-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.1
[pip3] optree==0.9.2
[pip3] torch==2.2.0a0+git3203988
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] mkl                       2023.1.0         h213fc3f_46343
[conda] mkl-include               2023.1.0         h06a4308_46343
[conda] numpy                     1.26.1                   pypi_0    pypi
[conda] optree                    0.9.2                    pypi_0    pypi
[conda] torch                     2.2.0a0+git3203988           dev_0    <develop>
[conda] torchvision               0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by ezyang** [comment]
Use `aot_autograd` combinator in torch._dynamo.backends.common to do the make_fx, instead of doing it manually yourself.

**Comment by ezyang** [comment]
Oh, I see you do have an aot_autograd combinator. Why do you feel you need to make_fx the graph again? You already have a GraphModule with all the nodes in it.

It is possible to setup retracing but you need to reuse the implicit ShapeEnv from the original Dynamo trace or you will have problems.

**Comment by yw-furiosa** [comment]
As far as I know, aot_autograd run make_fx with real mode, right? I wanted to try make_fx with fake mode. Thanks!

**Comment by ezyang** [comment]
AOT autograd runs make fx in fake mode!

**Comment by AleksKnezevic** [comment]
@ezyang you mention `It is possible to setup retracing but you need to reuse the implicit ShapeEnv from the original Dynamo trace or you will have problems.`
How would I go about doing that?

**Comment by ezyang** [comment]
There's a detect fake mode mechanism which we use to propagate fake modes, that's the ticket.

**Comment by ttrouwen-dmatrix** [comment]
@ezyang It seems it tries to do this automatically if you retrace using `torch.export.export` but it fails. Could you elaborate on how to propagate fake modes?

My use case is using TorchMLIR's `use_make_fx` functionality (which uses `make_fx` and `torch.export.export`) from within a Dynamo backend. Currently stumbling upon the following error:

`AssertionError: fake mode (<torch._subclasses.fake_tensor.FakeTensorMode object at 0x7f1b14124730>) from tracing context 0 doesn't match mode (<torch._subclasses.fake_tensor.FakeTensorMode object at 0x7f1af7f56a70>) from fake tensor input 0`

**Comment by ezyang** [comment]
It's probably best if you open a new issue specifically for this problem.

It's hard to say what the problem is without looking at use_make_fx, but naively I wouldn't use torch.export.export recursively from inside a Dynamo backend, it is redoing a bunch of stuff you have already done by virtue of being a Dynamo backend. Instead, I would use AOTAutograd to normalize the graph into FX ops of aten operators, and then do my backend from there.
