### ISSUE TITLE
Export + assume_constant_result does not work for top-level annotated function

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#112919]
### 🐛 Describe the bug

```
x = torch.ones([2, 2], requires_grad=True)
y = torch.ones([2, 2], requires_grad=True)
z = torch.ones([2, 2], requires_grad=True)

def helper_fn(x, y, z):
    return x * y * z

out = torch._dynamo.export(helper_fn)(x, y, z)
print(out.graph_module)

@torch._dynamo.assume_constant_result
def helper_fn2(x, y, z):
    return x * y * z

out = torch._dynamo.export(helper_fn2)(x, y, z)
print(out.graph_module)

def helper_fn3(x, y, z):
    return helper_fn2(x, y, z)

out = torch._dynamo.export(helper_fn3)(x, y, z)
print(out.graph_module)

def helper_fn4(x, y, z):
    return helper_fn2(x, y, z) * x

out = torch._dynamo.export(helper_fn4)(x, y, z)
```
Without nesting, the func is exported instead of being turned into a constant result/constant graph.

With nesting that works. Last graph is:
```
def forward(self, x, y, z):
    arg0, arg1, arg2, = fx_pytree.tree_flatten_spec(([x, y, z], {}), self._in_spec)
    l_x_ = arg0
    helper_fn2 = self.helper_fn2
    mul = helper_fn2 * l_x_;  helper_fn2 = l_x_ = None
    return pytree.tree_unflatten([mul], self._out_spec)
```

the compiler hint from the decorator does not seem to compose well with export when its applied to the same func as the export target.

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by abdulasiraj** [comment]
Hi @voznesenskym,

**Comment by WennnO** [comment]
Can I work on this problem? I'd like to attempt to resolve this.

**Comment by rithikp06** [comment]
Wennno are you still working on this? If not I’d like to take this on

**Comment by zhxchen17** [comment]
I think supporting this will be little confusing to people who fail at exporting and want to try their luck with assume_constant_result on toplevel...

Also dynamo._export is not a public API, so maybe we could open a separate issue if there's absolute need for this.
