### ISSUE TITLE
Support cast of single-element tensors to numbers

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#1129]
```python
t = torch.LongTensor([1])
n = long(t) # currently throws
```

It reads a bit better than `t[0]` and makes intent clear that the tensor must alway contain only one element. I think in practice it means overriding `__int__`, `__long__`, `__float__`, etc.

It would be useful for returns of `max(dim)` over a one-dimensional tensor. 

NumPy supports this as well.

**Comment by elanmart** [comment]
Would it be possible to add this feature to Variable and Tensor, or this should be done within #1433?
I guess [the changes](https://github.com/elanmart/pytorch/commit/f26f650e11204ce2e460a726a48ff8a095a85751)
would not be that big, and `float(loss.mean())` seems nicer than `loss.mean().data[0]`

**Comment by apaszke** [comment]
Does numpy allow for that?

**Comment by elanmart** [comment]
Yup 

```python
>>> import numpy as np
>>> zero_dim = np.array(3)
>>> scalar = np.float(3)
>>> single_elem = np.array([[[3]]])
>>> float(zero_dim), float(scalar), float(single_elem)
(3.0, 3.0, 3.0)
>>> empty = np.array([], dtype=np.float32)
>>> float(empty)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: only length-1 arrays can be converted to Python scalars

```

**Comment by apaszke** [comment]
Ok, let's add it then

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/3355
