### ISSUE TITLE
 No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package

### ISSUE THREAD

**Issue by HongLouyemeng** [pytorch/pytorch#112958]
### 🐛 Describe the bug

when I use ** python3 setup.py develop** to run a distributed demo, It get this error
**1.module 'torch.distributed' has no attribute 'init_process_group'
2.No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package**
When I re-run  **sudo python3 setup.py develop**  to be able to import torch.nn, but torch.distributed keeps giving me an error!
### Versions

Collecting environment information...
PyTorch version: 2.2.0a0+git9af3f98
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.9)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.9.10 (main, Jan 15 2022, 11:48:04)  [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-13.4.1-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz

Versions of relevant libraries:
[pip3] functorch==0.2.1
[pip3] gpytorch==1.9.0
[pip3] numpy==1.22.4
[pip3] pytorch3d==0.7.0
[pip3] torch==2.2.0a0+git9af3f98
[pip3] torch-geometric==2.0.4
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.12
[pip3] torchaudio==2.1.0
[pip3] torchvision==0.16.0
[conda] Could not collect

**Comment by HongLouyemeng** [comment]
sudo time env MACOSX_DEPLOYMENT_TARGET=14.1 CC=clang CXX=clang++ BUILD_CAFFE2_OPS=0 USE_CUDA=0 USE_MKLDNN=0 USE_DISTRIBUTED=1 python3 setup.py develop

**Comment by jbcoe** [comment]
Thanks for posting this, this saved me a bunch of time.
