### ISSUE TITLE
Add support for Flash Attention for AMD/ROCm

### ISSUE THREAD

**Issue by chauhang** [pytorch/pytorch#112997]
### 🚀 The feature, motivation and pitch

Enable support for Flash Attention Memory Efficient and SDPA kernels for AMD GPUs. 

At present using these gives below warning with latest nightlies (torch==2.2.0.dev20231105+rocm5.6, pytorch-triton-rocm==2.1.0+34f8189eae): 

> model.py:187: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ../aten/src/ATen/native/transformers/hip/sdp_utils.cpp:253.)
  y = F.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0)
model.py:187: UserWarning: 1Torch was not compiled with memory efficient attention. (Triggered internally at ../aten/src/ATen/native/transformers/hip/sdp_utils.cpp:291.)
  y = F.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0)
  
ROCm already has an implementation of Tri's FA here: https://github.com/ROCmSoftwarePlatform/flash-attention/tree/flash_attention_for_rocm2#amd-gpurocm-support

### Alternatives

User's have to manually install the ROCm version of FA and use that in their code, vs using the native PyTorch APIs. 

### Additional context

The ROCM build currently has the FA related flags turned off by default: https://github.com/pytorch/pytorch/blob/main/CMakeLists.txt#L741-L750

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by hongxiayang** [comment]
We are working on it internally. We will update upstream after that.

**Comment by chauhang** [comment]
Support added to PyTorch 2.2.0 release

**Comment by chauhang** [comment]
@jeffdaily @malfet Are the torch nightlies for rocm getting built with the correct flags for SDPA support? I am still getting this error with the latest `torch==2.4.0.dev20240323+rocm6.0`

**Comment by xinyazhang** [comment]
> Are the torch nightlies for rocm getting built with the correct flags for SDPA support? I am still getting this error with the latest `torch==2.4.0.dev20240323+rocm6.0`

Hi @chauhang , If you're referring to memory efficient attention this is expected. This PR only adds Flash Attention to PyTorch and we are working on Memory efficient attention support now.

**Comment by jithunnair-amd** [comment]
@chauhang Since this issue is regarding FA support for ROCm in nightlies, and PR https://github.com/pytorch/pytorch/pull/121561 has been reverted, I'm reopening this issue.

**Comment by jinsong-mao** [comment]
@xinyazhang @jithunnair-amd Hi the default flash_attention backward is  using the kernel from aotriton  bwd_kernel_dk_dv now, https://github.com/ROCm/aotriton/blob/6035fb4aa021d39a18adce883e059d5b99a8192c/v2python/rules/flash/bwd_kernel_dk_dv.py#L7. it's very low efficiency, any optimization configuration or usage should us do to improve the performance?

**Comment by maxall41** [comment]
@xinyazhang Any updates on implementing memory efficient attention?

**Comment by xinyazhang** [comment]
> @xinyazhang Any updates on implementing memory efficient attention?

ME and FA are fundamentally the same algorithm but providing different feature sets and on ROCm they are both implemented in AOTrition. The support is already included in PyTorch 2.4 https://github.com/pytorch/pytorch/pull/124885

**Comment by xinyazhang** [comment]
> it's very low efficiency, any optimization configuration or usage should us do to improve the performance?

AOTriton 0.7.1 https://github.com/ROCm/aotriton/releases/tag/0.7.1b made some improvements to the bwd kernel, which is ABI compatible (and only compatible) with AOTriton 0.7b and can be used as drop-in replacement for *official* PyTorch 2.5 wheel.

**Comment by hongxiayang** [comment]
close it as this is supported now
