### ISSUE TITLE
ONNX converts scalar to Tensor, doesn't works with torch.nn.functional.max_pool1d()

### ISSUE THREAD

**Issue by thlinh** [pytorch/pytorch#11296]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

I have a model including a character/word embedder implemented in PyTorch., which uses torch.nn.functional.max_pool1d() function. When trying to convert the model to ONXX (using torch.onxx.export() ), it generates error (during the 1st phase when the model is run with an input to generate the graph) like this:

    x5 = F.max_pool1d(x4, x4.size(2)).squeeze()
  File "/home/py3env/lib/python3.5/site-packages/torch/nn/functional.py", line 385, in max_pool1d
    ret = torch.max_pool1d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
TypeError: max_pool1d_with_indices(): argument 'kernel_size' (position 2) must be tuple of ints, not Tensor

I have checked, and the problem is with "x4.size(2)". When running my model in Python, the result is a scalar, which is OK for max_pool1d. But when torch.onxx.export() runs my model, x4.size(2) is a tensor 
(type torch.LongTensor) and max_pool1d cannot process it.

Could you help to fix it? Many thanks in advance!
 
## Code example
x4 = self.char_conv(x3).squeeze(2)                  # x4.type() returns 'torch.cuda.FloatTensor', 
                                                                        # x4.size() returns torch.Size([1200, 100, 15])
x5 = F.max_pool1d(x4, x4.size(2)).squeeze()

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 7.5.17
GPU models and configuration: GPU 0: Tesla K40c
Nvidia driver version: 396.51
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.1.1
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.1.4
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] pip 18.0 
[conda] Could not collect

**Comment by YuhoChen** [comment]
i have bug ,too

**Comment by estmit** [comment]
Running into this same issue as well. Can someone take a look at this?

**Comment by houseroad** [comment]
@spandantiwari could you try to the following solution:

pool_size = int(x4.size(2))
x5 = F.max_pool1d(x4, pool_size).squeeze()

**Comment by estmit** [comment]
@houseroad 

Works for me (model gets exported) but I get the following warning:

`TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!`

**Comment by houseroad** [comment]
if you want to do the global max_pool, you can try adaptive_max_pool. Otherwise, ONNX assume that pool size can be determined statically.

**Comment by estmit** [comment]
@houseroad 

Thank you!

The error message `argument 'kernel_size' (position 2) must be tuple of ints, not Tensor` was a little misleading as it implied that we should be passing in a tuple of ints, not just an int. Perhaps the docstring for MaxPool1d can be updated to reflect that kernal_size can be an int or a tuple (just like the docstring for MaxUnpool1d)?

**Comment by estmit** [comment]
@houseroad if I run `onnx.checker.check_model()` it says `onnx.onnx_cpp2py_export.checker.ValidationError: Attribute 'strides' is expected to have field 'ints'`

**Comment by L-M-Sherlock** [comment]
@houseroad 

Thanks!

I met the same problem. It costed me 4 hours 😂. Your solution saved me.

**Comment by Nrohlable** [comment]
I'm not able to resolve the same issue in my case:

line_10 --> x = F.avg_pool2d(x, kernel_size=(1, V))
line_11 --> c = x.size(1)
line_12 --> t = x.size(2)
 line_13--> x = x.view((N, M, c, t)).mean(dim=1).view((N, c, t))

Currently it throws error on line_13 saying the same thing i.e, 
TypeError: avg_pool1d(): argument 'kernel_size' must be tuple of ints, not Tensor

I have tried various approaches such as : int(x.size(1)) , giving int values to N,M,c,t .. but nothing seems to be working in order to resolve this issue. It would be really appreciative of anyone giving any inputs around it.
Thanks

**Comment by garymm** [comment]
@thlinh or others is this still an issue with latest PyTorch nightly?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.

**Comment by ROAD2018** [comment]
you can try like this:   
   x5 = F.max_pool1d(x4, x4.size(2)).squeeze()   ->  x5 = F.max_pool1d(x4, (x4.size(2),)).squeeze()
this can fix this problem "TypeError: max_pool1d_with_indices(): argument 'kernel_size' (position 2) must be tuple of ints, not Tensor"
