### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by labor00** [pytorch/pytorch#11309]
I got this error when trying to build pytorch from master
```bash
In file included from ../caffe2/core/logging.h:27:0,
                 from ../caffe2/core/types.h:9,
                 from ../caffe2/utils/math.h:17,
                 from ../caffe2/utils/math_cpu.cc:14:
../caffe2/utils/math_cpu.cc: In function ‘void caffe2::math::GemmEx(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, T, const T*, int, const T*, int, T, T*, int, Context*) [with T = float; Context = caffe2::CPUContext; Engine = caffe2::DefaultEngine]’:
../caffe2/core/logging_is_not_google_glog.h:93:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
     ::caffe2::MessageLogger((char*)__FILE__, __LINE__, n).stream()
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../caffe2/utils/math_cpu.cc:177:11: note: in expansion of macro ‘LOG’
           LOG(FATAL) << "Unexpected CBLAS_TRANSPOSE for trans_B";
           ^
../caffe2/utils/math_cpu.cc:180:5: note: here
     case CblasTrans: {
     ^~~~
In file included from ../caffe2/core/logging.h:27:0,
                 from ../caffe2/core/types.h:9,
                 from ../caffe2/utils/math.h:17,
                 from ../caffe2/utils/math_cpu.cc:14:
../caffe2/core/logging_is_not_google_glog.h:93:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
     ::caffe2::MessageLogger((char*)__FILE__, __LINE__, n).stream()
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../caffe2/utils/math_cpu.cc:200:11: note: in expansion of macro ‘LOG’
           LOG(FATAL) << "Unexpected CBLAS_TRANSPOSE for trans_B";
           ^
../caffe2/utils/math_cpu.cc:203:5: note: here
     default:
     ^~~~~~~
[1184/1525] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_logit_op.cu.o
FAILED: caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_loss_op.cu.o 
cd /home/disk0/.pytorch/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators && /usr/bin/cmake -E make_directory /home/disk0/.pytorch/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/disk0/.pytorch/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators/./caffe2_gpu_generated_loss_op.cu.o -D generated_cubin_file:STRING=/home/disk0/.pytorch/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators/./caffe2_gpu_generated_loss_op.cu.o.cubin.txt -P /home/disk0/.pytorch/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_loss_op.cu.o.Release.cmake
/home/disk0/.pytorch/pytorch/caffe2/operators/utility_ops.h: In member function ‘bool caffe2::WeightedSumOp<Context>::DoRunWithType()’:
/home/disk0/.pytorch/pytorch/caffe2/operators/utility_ops.h:328:55: error: cannot call member function ‘int caffe2::OperatorBase::InputSize() const’ without object
     const int input_size = InputSize();
                        ~~~~~~~~~~~~~~~~               ^ 
CMake Error at caffe2_gpu_generated_loss_op.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/disk0/.pytorch/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators/./caffe2_gpu_generated_loss_op.cu.o


[1191/1525] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_multi_class_accuracy_op.cu.o
ninja: build stopped: subcommand failed.
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 libshm gloo c10d THD'
```
Since for some time building pytorch also means to build   caffe2 is there any easy way to control where the the caffe2 installation look for libraries? For instance  I had to update the system version of the Eigen library instead of using -DCMAKE_DISABLE_FIND_PACKAGE_Eigen3 to force the build system to use the version in the third_party folder.

thanks

Collecting environment information...
PyTorch version: 68c2e014cbb
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Fedora release 28 (Twenty Eight)
GCC version: (GCC) 7.3.0
CMake version: version 3.11.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 396.45
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/lib64/libcudnn.so.7.2.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

**Comment by orionr** [comment]
@labor00, sorry you're having issues building - we'll try and help. First question - are you building with setup.py? For example:

```
python setup.py install  # or python setup.py build_deps develop
```

or are you using CMake directly? Generally we should have -DUSE_SYSTEM_EIGEN_INSTALL=OFF as the default, so you will use the third_party/ version.

I'm not sure why `InputSize()` isn't callable in that location... we do have CentOS builds in CI, so I'm not sure why you'd have this issue on Fedora.

cc @Yangqing and @pjh5 just in case they've seen this.

**Comment by labor00** [comment]
Hello. I have tried  to build the pytorch package using `python setup.py install` and also  `python setup.py build develop`. Both versions of the command results in the same error.
I was using using the setup.py option to build the pytorch package. However when building caffe2 I usually use the cmake option. My question really was how to pass cmake flags  when using python setup.py since now both packages are built together.

**Comment by orionr** [comment]
We currently only support some flags down from setup.py into CMake but we're looking to expose more. This will be selective, though.

You can modify https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.sh#L288 locally to pass whatever flags you need.

If you require something that isn't currently supported from setup.py please let us know and thanks.

**Comment by soumith** [comment]
closing based on @orionr 's comment
