### ISSUE TITLE
[export] Dynamo export lifting attrs as inputs

### ISSUE THREAD

**Issue by angelayi** [pytorch/pytorch#113041]
### 🐛 Describe the bug

I ran into an issue with exporting where dynamo lifts an attribute as an input to the graph when tracing.
Specifically, this seems to happen on attributes of `UnspecializedNNModuleVariable`, which in the case of export, I think currently only occurs on `nn.Sequential` modules that have hooks registered [(code pointer)](https://github.com/pytorch/pytorch/blob/3f62531191362587897a992958c007480498be44/torch/_dynamo/variables/nn_module.py#L263).

A couple of questions:
* Should dynamo export be lifting these attributes? I understand that after AOTAutograd these attributes should be lifted, but should this also happen in the dynamo layer? 
* If dynamo export is allowed to lift these attributes then export will need to do some reordering to maintain spec, as attributes should appear before inputs in the graph. Or is it dynamo export's intention to make these user inputs? But the user input case doesn't make too much sense to me.
* I think dynamo export should just place these as `get_attr` nodes in the graph, like any other attribute of an `nn.Module`. But maybe it's not possible right now due to how the code is structured.

Repro:
```python
import torch
from torch.export import export

class TestModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.a = torch.tensor(1.0)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return x + self.a

def forward_hook(
    module: torch.nn.Module, inputs, output
) -> torch.Tensor:
    return 2 * output

seq = torch.nn.Sequential(TestModule()).eval()
seq.b = torch.tensor(2)
handle = seq.register_forward_hook(forward_hook)

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.seq = seq

    def forward(self, x):
        return self.seq(x) + self.seq.b

inp = (torch.randn(2, 8),)
ep = export(M(), inp)  # This errors because dynamo adds an extra input
```

Dynamo produced graph:
```
graph():
    %l_x_ : torch.Tensor [num_users=1] = placeholder[target=L_x_]
    %l_self_seq_b : torch.Tensor [num_users=1] = placeholder[target=L_self_seq_b]
    %l__self___seq_0_a : [num_users=1] = get_attr[target=L__self___seq_0_a]
    %result : [num_users=1] = call_function[target=operator.add](args = (%l_x_, %l__self___seq_0_a), kwargs = {})
    %result_1 : [num_users=1] = call_function[target=operator.mul](args = (2, %result), kwargs = {})
    %add_1 : [num_users=1] = call_function[target=operator.add](args = (%result_1, %l_self_seq_b), kwargs = {})
    return (add_1,)
```

Source of the input added: 
```
AttrSource(base=NotNNModuleSource(base=NNModuleSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='seq'))), member='b')
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @suo @ydwu4

**Comment by yanboliang** [comment]
```UnspecializedNNModuleVariable``` is a subclass of ```UserDefinedObjectVariable```, so it's not a typical ```nn.Module```. I don't think export can support it well.
