### ISSUE TITLE
Automatically run "lintrunner -a" when needed and create review comments with autofixes

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#113079]
It would be cool if we automatically run "lintrunner -a" when needed and create a review comment with the resulting suggestions, so the PR author can just accept them.

**Comment by malfet** [comment]
We already post a comment, don't we? 
Testing it on https://github.com/pytorch/pytorch/pull/113699/files

**Comment by kit1980** [comment]
I mean review suggestion comments for autofixes.

See this PR https://github.com/pytorch/pytorch/pull/113723
It has autofixable lint issues, that can be fixed by running "lintrunner -a".
But we could have a system that creates a review for the PR with the suggested chnages, so the PR author can simply accept in the UI.

**Comment by kit1980** [comment]
And https://github.com/pytorch/pytorch/pull/113723 doesn't even have the annotations as https://github.com/pytorch/pytorch/pull/113699 has, probably because it's flake8 and ruff and not mypy?

**Comment by clee2000** [comment]
This was implemented by @PaliC in https://github.com/pytorch/pytorch/pull/136239 and can be enabled by adding `ciflow/autoformat` label to a PR (https://github.com/pytorch/pytorch/pull/138263)
