### ISSUE TITLE
Behavior Discrepancy Between Eager Mode and Optimized Mode for torch.abs with transposed out

### ISSUE THREAD

**Issue by GwiHwan-Go** [pytorch/pytorch#113010]
### 🐛 Describe the bug

Inconsistent results are observed between eager execution and compiled execution using torch.compile for the torch.abs function when the out value is given with torch.t

minimal repro 
```python 
import torch

def forward(x, y):          
  return torch.abs(input=x, out=torch.t(input=y))

x = torch.rand([9, 10], dtype=torch.float32)
y = torch.rand([10, 9], dtype=torch.float32)

# Run in eager mode
eager = forward(x, y)

# Run in compiled mode
compiled = torch.compile(forward, mode='default')(x, y)

# Check if both results are close
result_close = torch.allclose(eager.to('cpu'), compiled.to('cpu'), rtol=1e-3, atol=1e-3, equal_nan=True)
print(f"Are the results close? {result_close}")
```
Expected Behavior:
The result of torch.abs when run in eager mode should be identical to the result when run in the optimized mode generated by torch.compile.

Actual Behavior:
The comparison indicates the results are not the same (assuming result_close prints False), which suggests that the behavior of torch.abs with an out parameter is different between the two execution modes.

### Versions

PyTorch version: 2.2.0.dev20231023+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-86-generic-x86_64-with-glibc2.35

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ZailiWang** [comment]
By specifying `out` in `torch.abs()`, `y` is changed to `x.t` after the eager mode call.

**Comment by GwiHwan-Go** [comment]
That means that it is intended behavior? if it is, feel free to close the issue!

**Comment by wconstab** [comment]
IMO this is a valid bug. I changed the example to use smaller tensors of size (2,3) and (3,2) for brevity, and printed the eager and compiled results.  I also reinitialize x and y before executing the compiled version just in case the mutated Y from eager is affecting compile.
```
x = torch.tensor([[0, 1, 2], [-3, -4, -5]], dtype=torch.float32)
y = torch.rand([3, 2], dtype=torch.float32)
eager out tensor([[0., 1., 2.],
        [3., 4., 5.]]), y tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])
compiled out tensor([[0., 3., 1.],
        [4., 2., 5.]]), y tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])
```

I also confirmed that in the eager case, it's doing what i'd expect: Y's data is modified, by abs(out=), but it is done via a transposed view.  The return value from abs in eager has the expected (transposed) shape.

The compiled result has the right data and the right shape, but the wrong stride.

`compiled.as_strided(eager.shape, eager.stride())` gives a tensor that matches the eager return value.

**Comment by bdhirsh** [comment]
Confirmed that this also repros with `backend="aot_eager"`

One thing to point out is that dynamo today tries to graph break when it sees out= ops that mutate graph inputs, and it's not graph breaking here (probably because the out= tensor is not directly a graph input, but an alias).

So we should probably either fix this bug, or figure out a more robust way to graph break on the out= op.

**Comment by bdhirsh** [comment]
This looks like a functionalization + striding issue. Min repro:
```
import torch

def f(x, y):
    return torch.abs(x, out=y.T)

x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[1, 2], [3, 4]])
x2 = x.clone()
y2 = y.clone()
print(f(x, y).stride())
print(torch.func.functionalize(f)(x2, y2).stride())
```
prints:
```
(1, 2)
(2, 1)
```

Functionalization returned the "correct" result, but with wrong strides: the output in eager mode was a transposed tensor, but the output with functionalization is contiguous.

**Comment by bdhirsh** [comment]
I think this comes down to the fact that:

(1) `aten.abs(inp, out=out_tensor)` can return a non-contiguous tensor (if out_tensor was not contiguous)
(2) functionalization translates this to `aten.abs(inp)`, which always returns a contiguous tensor

And I think our options are:
(1) try to fix this (I'd need to think more about how to make this work)
(2) graph break on it

2 feels like a relatively simple unblock: when dynamo sees an out= op, it graph breaks if the out= argument is not contiguous. cc @ezyang on if the graph breaks sounds reasonable to you?

**Comment by ezyang** [comment]
Defo graph break first, ask questions later

**Comment by ezyang** [comment]
I feel this is not too hard to fix in functionalization land. We have the "stride matches the original" invariant, right? So I would propose adding a fixup restrider call that fixes things up. But this reminds me of the convo we had a while ago about what to do if you had a tensor view that was discontiguous, and I don't remember how we resolved this @bdhirsh

**Comment by voznesenskym** [comment]
@bdhirsh 

short-term: graph break on out= w/ non-contig
long-term: teach functionalization about non-contig preservation? (rare)
