### ISSUE TITLE
load_state_dict() does not load exact value

### ISSUE THREAD

**Issue by zxj-c** [pytorch/pytorch#113072]
### 🐛 Describe the bug

<img width="868" alt="Screenshot 2023-11-06 at 4 06 21 PM" src="https://github.com/pytorch/pytorch/assets/143853024/0ab4663d-db20-4d5a-85d8-2354888a72a3">

### Versions

NA

**Comment by colesbury** [comment]
This is not a bug. The default tensor type is float32, which cannot represent 72114982 precisely. If you wish to represent 72114982 exactly, use a different data type, like torch.int32, torch.int64, or torch.float64.

To be clear, this has nothing to do with `load_state_dict()` or `state_dict()`. It's fundamental to the data type.

Please see https://en.wikipedia.org/wiki/Single-precision_floating-point_format
