### ISSUE TITLE
Inconsistent Behavior Between Eager Execution and Compiled Execution for adaptive_avg_pool1d and argmax

### ISSUE THREAD

**Issue by GwiHwan-Go** [pytorch/pytorch#113013]
### 🐛 Describe the bug

The behavior of a simple sequence of operations involving `torch.adaptive_avg_pool1d` followed by `torch.argmax` appears to be inconsistent when executed eagerly compared to its optimized version using `torch.compile`.

Given that both torch.adaptive_avg_pool1d and torch.argmax are commonly-used APIs, and the arguments passed are not edge cases but rather standard use-cases, I guess this discrepancy could be considered critical.

### To Reproduce

```python
import torch

def forward(x):        
    x = torch.adaptive_avg_pool1d(input=x, output_size=2)
    x = torch.argmax(input=x)
    return x

x = torch.rand([3, 3, 3], dtype=torch.float64)

# Eager execution
eager = forward(x)

# Compiled execution
comp = torch.compile(forward, mode='max-autotune-no-cudagraphs', fullgraph=True, dynamic=True)(x)

# Comparing the results
print(torch.allclose(eager.to('cpu'), comp.to('cpu'), rtol=1e-3, atol=1e-3, equal_nan=True))
```

### Versions

PyTorch version: 2.2.0.dev20231023+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-86-generic-x86_64-with-glibc2.35

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler

**Comment by davidberard98** [comment]
I can repro on cuda, so I think this might be an inductor issue in general, not necessarily cpu inductor.
