### ISSUE TITLE
Mismatching behaviour of tensor assignment "a.data = b" between torch.compile and eager execution

### ISSUE THREAD

**Issue by Cztery** [pytorch/pytorch#113030]
### 🐛 Describe the bug

Since Pytorch 2.1, execution of functions with "a.data = b" tensor assignment produces different results than eager execution. 
In PT2.0 eager and compile and PT2.1 eager mode, tensorA = tensorB is treated like tensorA = torch.clone(tensorB), whereas in compile since PT2.1, it executes like it was tensorA = tensorB.view(-1).

Here's a code snippet confirming this behavior:
```python
import torch

print("input tensors a, b:")
a = torch.rand([6])
a1 = torch.clone(a)
print(a)
b = torch.rand([6])
b1 = torch.clone(b)
print(b)

def func(x,y):
  x.data = y
  y.data = torch.zeros(0)
  return x

f_compiled = torch.compile(func)
f_compiled(a,b)
print("\n a, b after compile run:")
print(a)
print(b)

func(a1,b1)
print("\n a, b after eager run:")
print(a1)
print(b1) 
```
PT2.1 and 2.2 result:

```python
input tensors a, b:
tensor([0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665])
tensor([0.1366, 0.1025, 0.1841, 0.7264, 0.3153, 0.6871])

a, b after compile run:
tensor([])
tensor([])

a, b after eager run:
tensor([0.1366, 0.1025, 0.1841, 0.7264, 0.3153, 0.6871])
tensor([])
```
PT2.0 result:

```python
input tensors a, b:
tensor([0.1951, 0.3202, 0.4022, 0.1943, 0.7430, 0.9812])
tensor([0.1001, 0.1426, 0.0979, 0.7146, 0.9821, 0.6137])

a, b after compile run:
tensor([0.1001, 0.1426, 0.0979, 0.7146, 0.9821, 0.6137])
tensor([])

a, b after eager run:
tensor([0.1001, 0.1426, 0.0979, 0.7146, 0.9821, 0.6137])
tensor([]) 
```
Execution results do not differ between used devices (CPU and HPU).

### Versions

PyTorch version: 2.2.0.dev20231106+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
CPU family:                      6
Model:                           140
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        1
BogoMIPS:                        3609.59
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512vbmi umip avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect flush_l1d arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       192 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        5 MiB (4 instances)
L3 cache:                        12 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.2.0.dev20231106+cpu
[pip3] torchaudio==2.2.0.dev20231106+cpu
[pip3] torchvision==0.17.0.dev20231106+cpu
[pip3] triton==2.0.0
[conda] Could not collect

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by jon-chuang** [comment]
@eellison is this due to https://github.com/pytorch/pytorch/pull/106092?

**Comment by jon-chuang** [comment]
Probably related to `set_`: https://github.com/pytorch/pytorch/issues/110843, https://github.com/pytorch/pytorch/issues/110780, https://github.com/pytorch/pytorch/issues/97500, https://github.com/pytorch/pytorch/issues/110842

**Comment by jon-chuang** [comment]
It seems that the attribute mutation is not being shipped into AOTAutograd.

When we do `x.data = y`, somehow:
1. y gets removed as a GraphArg
2. The mutation to x gets treated as a mutation to y, and it never captured in the graph.

**Comment by jon-chuang** [comment]
I think solving this is actually fairly simple. We just need to graph break on `x.data = y`. That's because this aliasing information cannot be possibly captured in the graph.

**Comment by voznesenskym** [comment]
or https://github.com/pytorch/pytorch/pull/113080/files :)

**Comment by Cztery** [comment]
What's the status of this issue, is it planned to be fixed in the upcoming releases?

**Comment by mlazos** [comment]
This is fixed on the nightly, so should be fixed in the upcoming release.
