### ISSUE TITLE
AOTInductor data dependents error when using max().item()

### ISSUE THREAD

**Issue by imzhuhl** [pytorch/pytorch#113002]
### 🐛 Describe the bug

reproduce code:
```python
import torch
from torch import nn

class PaddingNet(nn.Module):
    def __init__(self):
        super(PaddingNet, self).__init__()

    def forward(self, lengths):
        max_seq_len = lengths.max().item()
        row_vector = torch.arange(0, max_seq_len, 1)
        matrix = torch.unsqueeze(lengths, dim=-1)
        mask = row_vector < matrix
        mask = mask.type(torch.float32)
        mask_3d_btd = mask[:, :, None]
        return mask_3d_btd

model = PaddingNet()
lengths = torch.tensor([5, 4, 4, 4], dtype=torch.int32)
with torch.no_grad():
    so_path, exported = torch._export.aot_compile(model, (lengths, ))
```

Error message:
```python
Traceback (most recent call last):
  File "/root/alibaba/xcode-ml/pytorch/torch/_dynamo/utils.py", line 1478, in run_node
    return node.target(*args, **kwargs)
  File "/root/alibaba/xcode-ml/pytorch/torch/fx/experimental/symbolic_shapes.py", line 1023, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/root/alibaba/xcode-ml/pytorch/torch/fx/experimental/recording.py", line 250, in wrapper
    return event.run(self)
  File "/root/alibaba/xcode-ml/pytorch/torch/fx/experimental/recording.py", line 151, in run
    return self.f(*args, **kwargs)
  File "/root/alibaba/xcode-ml/pytorch/torch/fx/experimental/symbolic_shapes.py", line 4025, in evaluate_expr
    concrete_val = self.size_hint(orig_expr)
  File "/root/alibaba/xcode-ml/pytorch/torch/fx/experimental/symbolic_shapes.py", line 3818, in size_hint
    raise self._make_data_dependent_error(result_expr, expr)
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent (and thus we do not know the true value.)  The expression we were trying to evaluate is Eq(i0, 9223372036854775807) (unhinted: Eq(i0, 9223372036854775807)).  Scroll up to see where each of these data-dependent accesses originally occurred.
```

### Versions

```bash
Collecting environment information...
PyTorch version: 2.2.0a0+gite74b762
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Alibaba Cloud Linux release 3 (Soaring Falcon)  (aarch64)
GCC version: (GCC) 10.2.1 20200825 (Alibaba 10.2.1-3.5 2.32)
Clang version: Could not collect
CMake version: version 3.27.6
Libc version: glibc-2.32

Python version: 3.10.13 (main, Sep 11 2023, 13:18:45) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.134-15.al8.aarch64-aarch64-with-glibc2.32
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
架构：           aarch64
字节序：         Little Endian
CPU:             64
在线 CPU 列表：  0-63
每个核的线程数： 1
每个座的核数：   64
座：             1
NUMA 节点：      1
厂商 ID：        ARM
BIOS Vendor ID:  Alibaba Cloud
型号：           0
型号名称：       Neoverse-N2
BIOS Model name: virt-rhel7.6.0
步进：           r0p0
CPU MHz：        3000.000
CPU 最大 MHz：   3000.0000
CPU 最小 MHz：   3000.0000
BogoMIPS：       100.00
L1d 缓存：       64K
L1i 缓存：       64K
L2 缓存：        1024K
L3 缓存：        65536K
NUMA 节点0 CPU： 0-63
标记：           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs sb dcpodp sve2 sveaes svepmull svebitperm svesha3 svesm4 flagm2 frint svei8mm svebf16 i8mm bf16 dgh

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] onnxruntime==1.16.1
[pip3] pytorch-wpe==0.0.1
[pip3] rotary-embedding-torch==0.3.2
[pip3] torch==2.2.0a0+gite74b762
[pip3] torch-complex==0.4.3
[pip3] torchaudio==2.2.0a0
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.3.2                    pypi_0    pypi
[conda] torch                     2.2.0a0+gite74b762           dev_0    <develop>
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torchaudio                2.2.0a0                   dev_0    <develop>
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @wconstab

**Comment by angelayi** [comment]
Hello! The reason why the error occurs is because export is unable to determine the value of `max_seq_len`, and is failing when trying to check that the shapes used for slicing `mask` is within the bounds of [0, int_max]. We can solve this by adding a constraint on the value of `max_seq_len`. Something like the following:

```python
class PaddingNet(nn.Module):
    def __init__(self):
        super(PaddingNet, self).__init__()

    def forward(self, lengths):
        max_seq_len = lengths.max().item()
        torch._constrain_as_size(max_seq_len, max=5)  # <-- I set this as max=5, but you can set it to a higher known value
        row_vector = torch.arange(0, max_seq_len, 1)
        matrix = torch.unsqueeze(lengths, dim=-1)
        mask = row_vector < matrix
        mask = mask.type(torch.float32)
        mask_3d_btd = mask[:, :, None]
        return mask_3d_btd

model = PaddingNet()
lengths = torch.tensor([5, 4, 4, 4], dtype=torch.int32)
with torch.no_grad():
    exported_program = torch._export.export(model, (lengths,))
```

Now if you export using `torch._export.export`, you get the following graph:
```
graph():
    %arg0_1 : [num_users=2] = placeholder[target=arg0_1]
    %max_1 : [num_users=1] = call_function[target=torch.ops.aten.max.default](args = (%arg0_1,), kwargs = {})
    %_local_scalar_dense : [num_users=4] = call_function[target=torch.ops.aten._local_scalar_dense.default](args = (%max_1,), kwargs = {})
    %ge : [num_users=1] = call_function[target=operator.ge](args = (%_local_scalar_dense, 0), kwargs = {})
    %scalar_tensor : [num_users=1] = call_function[target=torch.ops.aten.scalar_tensor.default](args = (%ge,), kwargs = {})
    %_assert_async : [num_users=0] = call_function[target=torch.ops.aten._assert_async.msg](args = (%scalar_tensor, _local_scalar_dense is outside of inline constraint [0, 5].), kwargs = {})
    %le : [num_users=1] = call_function[target=operator.le](args = (%_local_scalar_dense, 5), kwargs = {})
    %scalar_tensor_1 : [num_users=1] = call_function[target=torch.ops.aten.scalar_tensor.default](args = (%le,), kwargs = {})
    %_assert_async_1 : [num_users=0] = call_function[target=torch.ops.aten._assert_async.msg](args = (%scalar_tensor_1, _local_scalar_dense is outside of inline constraint [0, 5].), kwargs = {})
    %sym_constrain_range_for_size : [num_users=0] = call_function[target=torch.ops.aten.sym_constrain_range_for_size.default](args = (%_local_scalar_dense,), kwargs = {max: 5})
    %arange : [num_users=1] = call_function[target=torch.ops.aten.arange.start_step](args = (0, %_local_scalar_dense), kwargs = {device: cpu, pin_memory: False})
    %unsqueeze : [num_users=1] = call_function[target=torch.ops.aten.unsqueeze.default](args = (%arg0_1, -1), kwargs = {})
    %lt : [num_users=1] = call_function[target=torch.ops.aten.lt.Tensor](args = (%arange, %unsqueeze), kwargs = {})
    %_to_copy : [num_users=1] = call_function[target=torch.ops.aten._to_copy.default](args = (%lt,), kwargs = {dtype: torch.float32})
    %slice_1 : [num_users=1] = call_function[target=torch.ops.aten.slice.Tensor](args = (%_to_copy, 0, 0, 9223372036854775807), kwargs = {})
    %slice_2 : [num_users=1] = call_function[target=torch.ops.aten.slice.Tensor](args = (%slice_1, 1, 0, 9223372036854775807), kwargs = {})
    %unsqueeze_1 : [num_users=1] = call_function[target=torch.ops.aten.unsqueeze.default](args = (%slice_2, 2), kwargs = {})
    return (unsqueeze_1,)
```

However, there are still some errors with the internals of `torch._export.aot_compile`. Running the inductor decompositions seems to cause another `GuardOnDataDependentSymNode` error (although running core ATen decomps seems to work fine).

Further down the line, `torch.ops.aten.sym_constrain_range_for_size.default` isn't implemented in inductor yet, so inductor will also fail because there is no kernel implement yet.

**Comment by ezyang** [comment]
Try inserting `torch._check_is_size(max_seq_len)` after the item call

**Comment by imzhuhl** [comment]
> Try inserting `torch._check_is_size(max_seq_len)` after the item call

GuardOnDataDependentSymNode error still occurs. 

This error caused by `mask[:, :, None]` of python. The direct reason seems to be that it cannot determine Eq(i[x], 9223372036854775807) == False when run_node with `getitem`.
_check_is_size do not give upper limit, maybe that's why it would go wrong. _constrain_as_size give a max value, but still wrong, so I think there's a problem with range info.
According to this idea, with using _constrain_as_size, the error occurs in `fn`:
```python
pytorch/torch/fx/_symbolic_trace.py(821)trace()
-> (self.create_arg(fn(*args)),),
# .....
/root/alibaba/xcode-ml/pytorch/torch/_functorch/aot_autograd.py(4552)functional_call()
-> out = Interpreter(mod).run(*args[params_len:], **kwargs)
```
It calls run_node with _constrain_as_size, and go into a seris of `__torch_dispatch__` methods, FunctionalTensorMode, ProxyTorchDispatchMode, then go into proxy_call:
```python
# proxy_call
r = maybe_handle_decomp(proxy_mode, func, args, kwargs)
if r is not NotImplemented:
    return r

# decomposition.py
@register_decomposition([aten.sym_constrain_range_for_size.default])
def sym_constrain_range_for_size(symbol, *, min=None, max=None):
    return
```
sym_constrain_range_for_size return none, then porxy call will return directly. So we no longer go into FakeTensorMode's `__torch_dispatch__`，therefore sym_constrain_range_for_size in meta registrations will not be called, we don't record shape_env.var_to_range information, this results in an error when executing getitem node because the range information is wrong.

A simple modification would allow the process to continue, then there is a inductor problem mentioned by @angelayi:
> Further down the line, torch.ops.aten.sym_constrain_range_for_size.default isn't implemented in inductor yet, so inductor will also fail because there is no kernel implement yet.

Actually, I'm not sure `torch.ops.aten.sym_constrain_range_for_size.default` should be in the last fx graph. And I want to hear your opinions on how to solve this. 

Also, I want to ask another small question, I don't understand how we get into ProxyTorchDispatchMode's `__torch_dispatch__` after FunctionalTensorMode's `__torch_dispatch__`

**Comment by imzhuhl** [comment]
Hi @ezyang @angelayi , I have added a fix and now it works under inductor and aot inductor. 
I would be very grateful if I could get your suggestions.

**Comment by deahhh** [comment]
> Hi @ezyang @angelayi , I have added a fix and now it works under inductor and aot inductor. I would be very grateful if I could get your suggestions.

I'm facing the same problem, would you share the solution with me, I'd appreciate it!

**Comment by ezyang** [comment]
@imzhuhl submitted a PR but it got lost in the weeds https://github.com/pytorch/pytorch/pull/115544 We should revisit it

**Comment by ezyang** [comment]
Bumping priority based on activity

**Comment by deahhh** [comment]
> Bumping priority based on activity

Thanks!

Would the problem bypassed with custom ops? How?
I am coding for two models and deploying them with executorch. 
It suppose only one model in the program, so I am trying to combine them.
Then, output from first as index of common input, to slice it as the second model input, blocked!

Everything is caused by `It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent`.

I have tried with custom ops, got
`torch._dynamo.exc.TorchRuntimeError: Failed running call_function my_ops.cropT.default(*(FakeTensor(..., size=(36,)), FakeTensor(..., size=(2, 2), dtype=torch.int32)), **{}):
maximum recursion depth exceeded in comparison`

**Comment by ezyang** [comment]
@deahhh I'd recommend filing a separate issue for your problem, in case it is actually slightly different and there is an easier resolution. In particular, @imzhuhl's problem was specific to Inductor, but given that you are exporting to executorch, there's a decent chance you aren't actually hitting inductor at all.

**Comment by ezyang** [comment]
Also, check out https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit#heading=h.44gwi83jepaj

**Comment by imzhuhl** [comment]
> Also, check out https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit#heading=h.44gwi83jepaj

@ezyang After reading the doc, and testing some cases on nightly version, I find that my problem has been partially resolved, thanks to the set_replacement. 
I still encounter some erroneous cases. I plan to submit a new issue first and see if it can be resolved.

**Comment by ezyang** [comment]
This version of the model

```
import torch
from torch import nn

class PaddingNet(nn.Module):
    def __init__(self):
        super(PaddingNet, self).__init__()

    def forward(self, lengths):
        max_seq_len = lengths.max().item()
        torch._check(max_seq_len < 40000)
        row_vector = torch.arange(0, max_seq_len, 1)
        matrix = torch.unsqueeze(lengths, dim=-1)
        mask = row_vector < matrix
        mask = mask.type(torch.float32)
        mask_3d_btd = mask[:, :, None]
        return mask_3d_btd

model = PaddingNet()
lengths = torch.tensor([5, 4, 4, 4], dtype=torch.int32)
with torch.no_grad():
    so_path, exported = torch._export.aot_compile(model, (lengths, ))
```

plus https://github.com/pytorch/pytorch/pull/122370 gets me to

```
  File "/data/users/ezyang/b/pytorch/torch/_inductor/graph.py", line 999, in run_node
    result = ir.ExternKernel.require_stride_order(result, stride_order)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/ir.py", line 3968, in require_stride_order
    ) and x.get_layout().is_stride_ordered(order):
  File "/data/users/ezyang/b/pytorch/torch/_inductor/ir.py", line 2556, in is_stride_ordered
    stride_ordered[order[i]] = V.graph.sizevars.size_hint(stride[i])
  File "/data/users/ezyang/b/pytorch/torch/_inductor/sizevars.py", line 431, in size_hint
    return int(out)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.10/site-packages/sympy/core/expr.py", line 320, in __int__
    raise TypeError("Cannot convert symbols to int")
TypeError: Cannot convert symbols to int
```

which looks the same as https://github.com/pytorch/pytorch/issues/120548

**Comment by imzhuhl** [comment]
@ezyang The model plus #122370 and #122298 seems to solve this error.
Also, I try this #122372 (change to `max = sys.maxsize - 1` in symbolic_shape.py) plus #122298, and remove `torch._check(max_seq_len < 40000)` in model, and seems avoid this error.
