### ISSUE TITLE
onnx export model with maxpool has incorrect shape

### ISSUE THREAD

**Issue by liqunfu** [pytorch/pytorch#113074]
### 🐛 Describe the bug

ONNX exporter with Maxpool produce incorrect output shape
[MaxPool should be corrected and documented properly](https://github.com/onnx/onnx/issues/5711)

### Versions

NA

**Comment by titaiwangms** [comment]
Related #113115

**Comment by titaiwangms** [comment]
https://github.com/pytorch/pytorch/pull/106270
