### ISSUE TITLE
Is there any function in pytorch that can visualize the function calling relationship and the calling relationship of the dynamic link library?

### ISSUE THREAD

**Issue by wynneyin** [pytorch/pytorch#113145]
### 🚀 The feature, motivation and pitch

Is there any function in pytorch that can visualize the function calling relationship and the calling relationship of the dynamic link library?

**Comment by wynneyin** [comment]
I use torchviz  but it not run. 
![image](https://github.com/pytorch/pytorch/assets/87656520/b769fa30-0f65-457f-b1e9-1ad051533674)

**Comment by wynneyin** [comment]
the notimpl block is my cutsomfunc

**Comment by malfet** [comment]
Please use https://dev-discuss.pytorch.org/ to ask general questions about PyTorch.
One can trace ATen operator calls using profiler, but if question is just general about any C++ application, then perhaps [CallGrind](https://valgrind.org/docs/manual/cl-manual.html) is the answer
