### ISSUE TITLE
[dynamo] self-assigning operation causes `TensorVariable` to lose `mutable_local`, thus causing its attribute mutations to be untracked

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#113160]
### 🐛 Describe the bug

Repro incoming

### Versions

main

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @bdhirsh @zou3519 @aakhundov

**Comment by jon-chuang** [comment]
The reason is that methods like `iadd` currently are not aware that they are actually assigning to the same `TensorVariable`. They create a new one. And this new one is untracked. 

However, isn't that bad?

**Comment by voznesenskym** [comment]
> The reason is that methods like `iadd` currently are not aware that they are actually assigning to the same `TensorVariable`. They create a new one. And this new one is untracked.
> 
> However, isn't that bad?

The solution here is to just replace_all, and make sure that mutable_local stays correct. This seems relatively easy to fix.

Alternatively, wait for the mutable VT work to land, and this will make it easier.

**Comment by jon-chuang** [comment]
@voznesenskym in https://github.com/pytorch/pytorch/pull/113171 I propagate `mutable_local` to the downstream `VariableTracker`. However, I guess `replace_all` is more correct?

**Comment by jon-chuang** [comment]
Actually, I think we don't actually need to `replace_all`. We can just  return `arg[0]`. Lol. 

`replace_all` is fine too but it's more complicated and needs more code to work (we need to explicitly propagate source, mutable locals, and also prove that we are not actually mutating something originating outside the scope for HOPs)

**Comment by jon-chuang** [comment]
Hmm, this works for other ops, but not for `__imatmul__`. In particular, we are not guaranteed that the original tensor is indeed the tensor that is assigned.

In particular, I think `iadd` desugars to `add_` but `imatmul` does not.

**Comment by mlazos** [comment]
Closing as this is no longer an issue

```py
import torch
import operator

op = operator.iadd

@torch.compile()
def func(x, y):
    op(x, torch.ones(2, 2))
    x.z = y
    op(x, torch.ones(2, 2))
    return x

out = func(torch.ones(2, 2), torch.ones(2, 2))
print(out)
print(out.z)
```
```
>> tensor([[3., 3.],
        [3., 3.]])
tensor([[1., 1.],
        [1., 1.]])
```
