### ISSUE TITLE
get_unbacked_symbol_defs in inductor uses a set and iterates over it

### ISSUE THREAD

**Issue by oulgen** [pytorch/pytorch#113130]
### 🐛 Describe the bug

Iteration over set is non-deteriministic, so we should either swap to list or sort them. Plain sorting results in
```
TypeError: cannot determine truth value of Relational
```

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by ezyang** [comment]
Oops. Let's turn it into a dict
