### ISSUE TITLE
einops.rearrange breaks make_fx

### ISSUE THREAD

**Issue by gpetters94** [pytorch/pytorch#113121]
I'm having issues with `make_fx` symbolic tracing with the `rearrange` function from `einops`. Here's a stripped down reproducer:
```
import torch
from functorch import make_fx
from einops import rearrange

# torch.fx.wrap('rearrange')

class B(torch.nn.Module):
    def forward(self, x):
        x = rearrange(x, 'b c h w -> b (h w) c').contiguous()
        return x

b = B()
tensor = torch.zeros([2, 2, 3, 2])

b2 = make_fx(
    b,
    decomposition_table={},
    # tracing_mode="symbolic",
    _allow_non_fake_inputs=True,
    _allow_fake_constant=False,
)(tensor)

b3 = make_fx(
    b,
    decomposition_table={},
    tracing_mode="symbolic",
    _allow_non_fake_inputs=True,
    _allow_fake_constant=False,
)(tensor)
```
b2 works fine, but b3 crashes with [this backtrace](https://gist.github.com/gpetters94/f2afc38cd2416e6479073999f1ec731e). I've tried running torch_fx's symbolic tracing directly, and that fails with the same error unless you uncomment the `torch.fx.wrap` line. `make_fx` doesn't work either way.

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv

**Comment by ezyang** [comment]
does this happen with pytorch nightly and einops main

**Comment by ezyang** [comment]
Confirmed that this no longer happens with einops main
