### ISSUE TITLE
Allow passing `(<name>, <module>)` tuples to `nn.Sequential`

### ISSUE THREAD

**Issue by Yura52** [pytorch/pytorch#113152]
### 🚀 The feature, motivation and pitch

*(I am ready to implement this feature)*

Currently, creating a `nn.Sequential` with named modules requires one more import and two more indentations compared to the version without names:

```
# Without names.
model = nn.Sequential(
   hello_module,
   world_module,
)
```
```
# With names.
from collections import OrderedDict

model = nn.Sequential(
    OrderedDict(
        [
            ('hello', hello_module),
            ('world', world_module),
        ]
    )
)
```

Given how frequently this construction occurs in practice, I propose improving its ergonomics by allowing the following:

```
# With names.
model = nn.Sequential(
    ('hello', hello_module),
    ('world', world_module),
)
```

The new constructor should raise an exception if there are duplicated names among the provided tuples.

### Additional context

There is also https://github.com/pytorch/pytorch/issues/84751. However:
- The linked issue seems to have a significantly wider scope.
- This is something I am not sure about, but I'll mention this just in case: the proposed version has a pretty simple semantics which is "order of tuples == order of modules". With the `dict`-based version, technically, it is also true, but it may be slightly less intuitive given a long history of `dict` being unordered (and similar collections being unordered in other languages).

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Thanks for the issue, `torch.nn.Sequential` is not intended to be a fully featured system. If one needs features that go beyond that of `torch.nn.Sequential` one can use a `torch.nn.Module`. Closing as we will not be adding this feature.
