### ISSUE TITLE
Request to add system requirements to doc

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#113124]
### 📚 The doc issue

It seems like libtorch has raised its base GLIBC version to 2.29, and no system requirements found in doc.
Request to add a system requirement section in doc or installation guide, including which gcc version is recommended, which OS is required, etc.

cc @svekars @brycebortree @jbschlosser @carljparker

**Comment by ignaciobartol** [comment]
Hi, I apologize if my comment is not clear enough. I am relatively new to this area, so I will try to be as clear as possible. Please let me know if I need to clarify anything further or if something does not make sense.

I tried to replicate this problem, and it seems to be linked only to the cxx11 ABI version of LibTorch. The pre-cxx11 ABI version of libtorch compiles fine with GLIBC 2.17 and GCC 10.3.0 on Red Hat Enterprise Linux Server release 7.9 (Maipo). I used the [installation example](https://pytorch.org/cppdocs/installing.html) from the documentation.

My suggestion is to modify `pytorch/docs/cpp/source/installing.rst` by adding a few lines about the GLIBC requirements for using both versions of LibTorch.

Additionally, I was wondering if I could add a few lines in the form of a "tip" or as normal text on how to troubleshoot the problem by running the `ldd lib/libtorch.so` command from the unzip directory. This command can help on checking the dependencies of the LibTorch libraries and identify the required GLIBC version.

Let me know if this makes sense and if it would be a good idea to proceed with working on the `installing.rst` document.

Thanks!

cc @svekars

**Comment by jingxu10** [comment]
Hi @ignaciobartol , yeah, it sounds good to me. Could you raise a PR? Thank you.
