### ISSUE TITLE
[torch.compile] With dynamic_shape=True and torch.randperm operator error while dynamo tracing

### ISSUE THREAD

**Issue by sssiva81** [pytorch/pytorch#113142]
### 🐛 Describe the bug

When running torch.compile with dynamic_shape=True with torch.randperm operator getting error while the model is traced by dynamo.  The default signature expects Int but the traced input args contain SymInt leading to error.

### Error logs
```
  File "anaconda3/envs/pt_2_0_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1557, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "anaconda3/envs/pt_2_0_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1536, in run_node
    return node.target(*args, **kwargs)
  File "anaconda3/envs/pt_2_0_env/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "anaconda3/envs/pt_2_0_env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1390, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "anaconda3/envs/pt_2_0_env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1645, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "anaconda3/envs/pt_2_0_env/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 462, in constructors
    r = func(*args, **new_kwargs)
  File "anaconda3/envs/pt_2_0_env/lib/python3.10/site-packages/torch/_ops.py", line 506, in __call__
    return self._op(*args, **kwargs or {})
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method randperm of type object at 0x7fbb67921c20>(*(s0,), **{'generator': None, 'device': 'cpu'}):
when unpacking SymInt, expected int but got s0
```
### Minified repro

```
import torch
import os
import torch.nn as nn
import torch._dynamo
from typing import List
from torch._dynamo.backends.registry import register_backend
from torch._dynamo import compiled_autograd
from torch._dynamo.backends.common import aot_autograd
#import habana_frameworks.torch.core as htcore
#import habana_frameworks.torch.dynamo.compile_backend

def custom_inner_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    print("custom backend called")
    for input in example_inputs:
        print(input)
    #print(gm.graph)
    return gm.forward

@register_backend
def custom_backend(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    return aot_autograd(
            fw_compiler=custom_inner_compiler,
            bw_compiler=custom_inner_compiler,
            )(gm, example_inputs)


def test_randperm(n):
    def fn(n, g):
        return torch.randperm(n, generator=g)
    seed = 1234
    torch.manual_seed(seed)
    g = None#torch.Generator()
    fn = torch.compile(fn, dynamic=True, backend="custom_backend")
    hpu_res1 = fn(n, g)

test_randperm(10)
```

### Versions

PyTorch version: 2.2.0.dev20231106+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-163-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      43 bits physical, 48 bits virtual
CPU(s):                             12
On-line CPU(s) list:                0-11
Thread(s) per core:                 1
Core(s) per socket:                 1
Socket(s):                          12
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz
Stepping:                           0
CPU MHz:                            2194.843
BogoMIPS:                           4389.68
Virtualization:                     VT-x
Hypervisor vendor:                  VMware
Virtualization type:                full
L1d cache:                          384 KiB
L1i cache:                          384 KiB
L2 cache:                           12 MiB
L3 cache:                           429 MiB
NUMA node0 CPU(s):                  0-11
Vulnerability Gather data sampling: Unknown: Dependent on hypervisor status
Vulnerability Itlb multihit:        KVM: Mitigation: Split huge pages
Vulnerability L1tf:                 Mitigation; PTE Inversion; VMX flush not necessary, SMT disabled
Vulnerability Mds:                  Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:             Mitigation; PTI
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Retbleed:             Mitigation; IBRS
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; IBRS, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xsaves arat pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.2.0.dev20231106+cpu
[pip3] torchaudio==2.2.0.dev20231106+cpu
[pip3] torchvision==0.17.0.dev20231106+cpu
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.2.0.dev20231106+cpu          pypi_0    pypi
[conda] torchaudio                2.2.0.dev20231106+cpu          pypi_0    pypi
[conda] torchvision               0.17.0.dev20231106+cpu          pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by ezyang** [comment]
This is fixed by the diff stack at https://github.com/pytorch/pytorch/pull/113921
