### ISSUE TITLE
[dynamo] Assigning result of Tensor in-place op destroys mutation tracking

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#113271]
### 🐛 Describe the bug

The new tensor variable returned by e.g.

```python
x = x.add_(1)
```

Does not retain mutation tracking, similar to builtin in-place magic methods https://github.com/pytorch/pytorch/issues/113160

Repro incoming

### Versions

main

cc @ezyang @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @zou3519 @aakhundov

**Comment by wconstab** [comment]
ping for repro

**Comment by jon-chuang** [comment]
Repro are in the PR tests now

**Comment by mlazos** [comment]
Closed as this is fixed, see https://github.com/pytorch/pytorch/issues/113160 for an example
