### ISSUE TITLE
[dynamo / aot_autograd] AOTAutograd does not guard on input `requires_grad` setting changing for backwards

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#113290]
### 🐛 Describe the bug

Repro

```python
@torch.compile(backend="aot_eager")
def fn(x, s):
    x.requires_grad = True
    y = x * 2
    x.requires_grad = False
    z = x * 3 * s * y
    return x, y, z

x = torch.ones(3)
s = torch.ones(3, requires_grad=True)

_, y, z = fn(x, s)

x.requires_grad = True
z.sum().backward()

print(x.grad)  # Should be torch.tensor([6., 6., 6.]) via y, but got None
```

cc: @bdhirsh @ezyang 

### Versions

main

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by jon-chuang** [comment]
I think it is quite hard to guard on this. If it does change, how can we recompile it? It's not as though we can _just recompile backwards_, or can we?

If we can, we can guard on the backward's inputs. If we can't, we need to forbid mutations of `requires_grad` in between forwards an backwards.

**Comment by ezyang** [comment]
I think this is the same problem as https://docs.google.com/document/d/1kBQUNIt1tRyKSiXV-db3C4dTvLYF2fC53dxCXqk08GQ/edit#heading=h.38k8zg2mwnrq

**Comment by bdhirsh** [comment]
This now successfully prints `tensor([6., 6., 6.])` for me (likely because we now graph break on `x.requires_grad = ...` calls in dynamo). Marking as closed
