### ISSUE TITLE
PT2 improperly executes ambient saved_tensors_hooks

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#113263]
### 🐛 Describe the bug

This program:

```
import torch

def pack_hook(x):
    return x

def unpack_hook(x):
    print("unpacking")
    return x

a = torch.ones(5, requires_grad=True)
b = torch.ones(5, requires_grad=True) * 2

def f(a, b):
    return a * b

opt_f = torch.compile(backend="aot_eager")(f)

print("# eager")
with torch.autograd.graph.saved_tensors_hooks(pack_hook, unpack_hook):
    y = f(a, b)

print("# compile")
with torch.autograd.graph.saved_tensors_hooks(pack_hook, unpack_hook):
    y = opt_f(a, b)
```

prints

```
$ python st.py
# eager
# compile
unpacking
unpacking
```

This is unexpected: the unpack hook should not be called until we actually run backwards.

What is happening is that Dynamo is not testing if there are saved tensor hooks, and blindly executing AOTAutograd with whatever ambient saved tensor hooks there are.

This is the root cause of a problem with composable checkpointing that @awgu was reporting to me.

cc @gchanan @zou3519 @kadeng @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @msaroufim @bdhirsh @anijain2305 @chauhang @wconstab @voznesenskym @awgu 

### Versions

main

**Comment by ezyang** [comment]
Hmm, is your point that the saved tensor hooks can operate on the final produced AOT Autograd custom function? That does seem plausible. In that case AOTautograd should just nub it out. cc @bdhirsh

**Comment by albanD** [comment]
Given the approach we have for activation checkpointing (and this report), my feeling is that yes, we don't want the use hooks to be traced but we want them to be applied to whatever the custom Function generated by AOT saves.

**Comment by bdhirsh** [comment]
> Hmm, is your point that the saved tensor hooks can operate on the final produced AOT Autograd custom function?

For normal AOTAutograd this makes sense to me.

That made me think about the story for compiled autograd though, which seems a bit more complicated? Although I agree that no-oping the saved-tensor-hooks in AOTAutograd sounds worth doing either way.

(1) compiled autograd will end up trying to trace through the backward hooks (and potentially graph break if there was a print statement, or otherwise burn the series of ops from the unpack hook into the graph)

(2) we would then want to make sure we're guarding on the particular unpack hook in the global context at the time we compiled the backward?

**Comment by ezyang** [comment]
In compiled autograd we want to have Dynamo traced into the saved tensor hook unpacks.

**Comment by wconstab** [comment]
this is a gray-area for oncall, looks like we don't need much discussion in triage-review other than 'whos gonna do it' - so if you're gonna do it feel free to assign to yourself and mark 'triaged' otherwise ill leave it in the oncall pile

**Comment by awgu** [comment]
The particular use case that motivated me to talk to @ezyang  was `torch.distributed._composable.checkpoint`. IIUC, today, Dynamo specially handles `torch.utils.checkpoint` by tracking it as a `HigherOrderOp` to avoid AOTAutograd from tracing into the saved tensor hooks. To unblock `_composable.checkpoint`, could we do the same thing as for `torch.utils.checkpoint`?

**Comment by ezyang** [comment]
Still broken as of 0a1b3be2163ea99633f95c4927bd816eb713e9bd

**Comment by ezyang** [comment]
Upgrading priority as silent correctness problem

**Comment by zou3519** [comment]
(pr in progress)
