### ISSUE TITLE
[contextlib] `DecoratorContextManager` and hence `set_grad_enabled` behaves in an unexpected way

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#113298]
### 🐛 Describe the bug

```python
import torch

assert torch.is_grad_enabled()

@torch.set_grad_enabled(False)  # unexpectedly, this mutates the grad mode!
def inner_func(x):
    return x.sin()

assert torch.is_grad_enabled()  # AssertionError
```

Rather, I think that if `set_grad_enabled` were called on a function after initialization, it needs to reset to its exit state, prior to becoming a decorator ctx manager.

### Versions

main

cc: @yanboliang 

cc @ezyang @gchanan @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by jon-chuang** [comment]
@ezyang I don't think there's a BC-breaking concern here right? I think the current behaviour is a bug.

**Comment by ezyang** [comment]
Yeah, I think we shoudl just fix it. Send the PR.
