### ISSUE TITLE
`inference_mode` documentation is incorrect

### ISSUE THREAD

**Issue by rfejgin** [pytorch/pytorch#113211]
### 📚 The doc issue

https://pytorch.org/docs/stable/generated/torch.inference_mode.html

At the end of the example code, we have this:

```
>>> @torch.inference_mode
... def doubler(x):
...     return x * 2
>>> out = doubler(x)
>>> out.requires_grad
False
```

However, `@torch.inference_mode` doesn't work as is, it seems that it needs to be `@torch.inference_mode()` (with the parenthesis).

Executing the code as in the example gives:
```
>>> doubler(x)
<function torch.context_decorator.<locals>.decorate_context>
```

**Comment by ezyang** [comment]
send us a PR? Thanks!

**Comment by tringwald** [comment]
I can reproduce this on `2.0.0` but not anymore on `2.1.0` or latest nightly builds. Seems to be fixed already.
