### ISSUE TITLE
[linear-algebra][discussion][proposal] Move linear algebra functions to torch.linalg, at::native::linalg

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#11325]
I believe we have quite a few linear algebra centric operations excluding the most commonly used ones (`matmul`, `mm`, `mv`, etc.) such as:
- `ger`
- `qr` / `ormqr` / `orgqr` / `geqrf`
- `gesv` / `gels` / `btrifact` (and its variants)
- `triu` / `tril`
- `eig` / `symeig`
- `svd`
- `inverse` / `pinverse`
- `matrix_rank`
- `det` / `logdet` / `slogdet`

I think it would be nice to organize them as `torch.linalg` analogous to `numpy.linalg`. This would prevent cluttering of the `torch` module while importing `torch`. Also, it would be nice to have these organized in a specific namespace within `ATen` (as `at::native::linalg` for example).

Some issues might include BC-breaking ones, but if we are looking towards 1.0, I think this might ensure a cleaner API.

Please let me know your thoughts about this.

**Comment by soumith** [comment]
It's principally correct, but usably worse.
`torch.linalg.svd(x)` is way more verbose.

If the problem we want to address is discovery, we should have a `Linear Algebra` section in the docs organizing all these together for reference, similar to how we organize the `torch.nn` section.

**Comment by vishwakftw** [comment]
Won't `methods` mitigate the verbosity issue?

Reg documentation: I do agree that we require a section dedicated to Linear Algebra in the documentation, perhaps like `torch.utils` / `torch.nn`.

**Comment by soumith** [comment]
by `methods`, do you mean `x.svd()` or `x.linalg.svd()`?

We should break down `torch.Tensor` documentation into sections.
Once we click on `torch.Tensor`, it should expand into categories like `torch.nn`

<img width="297" alt="screen shot 2018-09-06 at 11 49 18 pm" src="https://user-images.githubusercontent.com/1310570/45197476-83d85500-b22f-11e8-9309-d2e2978803b7.png">

<img width="301" alt="screen shot 2018-09-06 at 11 49 04 pm" src="https://user-images.githubusercontent.com/1310570/45197481-95b9f800-b22f-11e8-8c74-458c3608ba8a.png">

**Comment by vishwakftw** [comment]
I meant `x.svd()` (motivated by `native_functions.yaml`).

I thought `torch.Tensor` documented these `methods`. Are you suggesting
partitioning these methods into multiple classes?

**Comment by soumith** [comment]
`torch.Tensor` does document these methods, but there isn't a formal organization (or a side-bar).
I'm saying that if we want to improve discoverability, we probably want to do either of those.
However, that will break the alphabetical-orderness of the current method list

**Comment by t-vi** [comment]
I must admit I don't fully buy the idea, and it starts with "excluding the most commonly used ones". I always need to remember which is which when using numpy.
