### ISSUE TITLE
pytorch on Windows build failed.

### ISSUE THREAD

**Issue by xuhancn** [pytorch/pytorch#113265]
### 🐛 Describe the bug

[3508/6057] Building CXX object confu-deps\XNNPACK\CMakeFiles\jit.dir\src\jit\assembler.cc.obj
FAILED: confu-deps/XNNPACK/CMakeFiles/jit.dir/src/jit/assembler.cc.obj
C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DNOMINMAX -DXNN_ENABLE_ARM_BF16=0 -DXNN_ENABLE_ARM_DOTPROD=1 -DXNN_ENABLE_ARM_FP16_SCALAR=1 -DXNN_ENABLE_ARM_FP16_VECTOR=0 -DXNN_ENABLE_ASSEMBLY=1 -DXNN_ENABLE_GEMM_M_SPECIALIZATION=1 -DXNN_ENABLE_JIT=0 -DXNN_ENABLE_MEMOPT=1 -DXNN_ENABLE_SPARSE=1 -DXNN_LOG_LEVEL=0 -Drestrict="" -ID:\xuhan\build_pytorch\pytorch\third_party\XNNPACK\include -ID:\xuhan\build_pytorch\pytorch\third_party\XNNPACK\src -ID:\xuhan\build_pytorch\pytorch\third_party\pthreadpool\include -external:I D:\xuhan\build_pytorch\pytorch\third_party\protobuf\src -external:I C:\ProgramData\Anaconda3\envs\build_pytorch\Library\include -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /bigobj /FS /utf-8 -DUSE_PTHREADPOOL /O2 /Ob2 /DNDEBUG /bigobj -MD -DMKL_HAS_SBGEMM /wd4146 /bigobj /O1 /showIncludes /Foconfu-deps\XNNPACK\CMakeFiles\jit.dir\src\jit\assembler.cc.obj /Fdconfu-deps\XNNPACK\CMakeFiles\jit.dir\ /FS -c D:\xuhan\build_pytorch\pytorch\third_party\XNNPACK\src\jit\assembler.cc
cl : Command line warning D9025 : overriding '/O2' with '/O1'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xkeycheck.h(55): fatal error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "bool". Enable warning C4005 to find the forbidden define.

--------------------
I meet build issue also, how is pytorch daily build can works?

### Versions

(build_pytorch) D:\xuhan\build_pytorch\pytorch>python setup.py install
Building wheel torch-2.2.0a0+gitf296364
-- Building version 2.2.0a0+gitf296364
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:\xuhan\build_pytorch\pytorch\torch -DCMAKE_PREFIX_PATH=C:\ProgramData\Anaconda3\envs\build_pytorch\Lib\site-packages -DNUMPY_INCLUDE_DIR=C:\ProgramData\Anaconda3\envs\build_pytorch\Lib\site-packages\numpy\core\include -DPYTHON_EXECUTABLE=C:\ProgramData\Anaconda3\envs\build_pytorch\python.exe -DPYTHON_INCLUDE_DIR=C:\ProgramData\Anaconda3\envs\build_pytorch\Include -DPYTHON_LIBRARY=C:\ProgramData\Anaconda3\envs\build_pytorch/libs/python311.lib -DTORCH_BUILD_VERSION=2.2.0a0+gitf296364 -DUSE_NUMPY=True D:\xuhan\build_pytorch\pytorch
-- The CXX compiler identification is MSVC 19.29.30152.0
-- The C compiler identification is MSVC 19.29.30152.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Not forcing any particular BLAS to be found
CMake Warning at CMakeLists.txt:378 (message):
  TensorPipe cannot be used on Windows.  Set it to OFF

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by malfet** [comment]
To the best of my knowledge, we build PyTorch Windows package without distributed support, so we should probably switch flag to OFF by default, PR is coming

**Comment by xuhancn** [comment]
I have updated MSVC and pull the latest main branch, the issue is gone.
Failed version:
> Building wheel torch-2.2.0a0+gitf296364
> -- The CXX compiler identification is MSVC 19.29.30152.0
> -- The C compiler identification is MSVC 19.29.30152.0

Success version:
> Building wheel torch-2.2.0a0+git15b61d6
> -- The CXX compiler identification is MSVC 19.29.30152.0
> -- The C compiler identification is MSVC 19.29.30152.0

**Comment by malfet** [comment]
Success and failed version show the same version of visual studio, and there does not seem to be any significant build system changes between https://github.com/pytorch/pytorch/compare/f2963642c24ff2d8b516557e346b26b9bdabf03d...15b61d6c1aa88632d7db0192713cc8e19862c94d that could have explained the failure.

**Comment by xuhancn** [comment]
> Success and failed version show the same version of visual studio, and there does not seem to be any significant build system changes between [f296364...15b61d6](https://github.com/pytorch/pytorch/compare/f2963642c24ff2d8b516557e346b26b9bdabf03d...15b61d6c1aa88632d7db0192713cc8e19862c94d) that could have explained the failure.

I checked it and found it seems only works on "base" conda env. Anyway, it works now.
