### ISSUE TITLE
error while installing pytorch in macOS M1 from source

### ISSUE THREAD

**Issue by lusifer021** [pytorch/pytorch#113330]
### 🐛 Describe the bug

I followed the steps to install pytorch from source written here [https://github.com/pytorch/pytorch#from-source](link) in macOS.

Steps I followed:
1. Created a conda enviroment
2. `conda install cmake ninja`
3. `git clone --recursive https://github.com/pytorch/pytorch `
`cd pytorch`
`git submodule sync`
`git submodule update --init --recursive`
4. `pip install -r requirements.txt`
5. `conda install pkg-config libuv`
6. `python3 setup.py develop`

But when I run the last command `python3 setup.py develop` it throws an error:

``` 
Building wheel torch-2.2.0a0+gitb3ad29e
dyld[8200]: Library not loaded: @rpath/librhash.0.dylib
  Referenced from: <39E92F07-1A2A-395C-89BF-CE060F8A99DD> /opt/miniconda3/envs/pytorch_dev1/bin/cmake
  Reason: tried: '/opt/miniconda3/envs/pytorch_dev1/bin/../lib/librhash.0.dylib' (no such file), '/opt/miniconda3/envs/pytorch_dev1/bin/../lib/librhash.0.dylib' (no such file), '/usr/local/lib/librhash.0.dylib' (no such file), '/usr/lib/librhash.0.dylib' (no such file, not in dyld cache)
Traceback (most recent call last):
  File "/Users/mrinmoymahato/Coding/pytorch_dev/pytorch/setup.py", line 342, in <module>
    cmake = CMake()
            ^^^^^^^
  File "/Users/mrinmoymahato/Coding/pytorch_dev/pytorch/tools/setup_helpers/cmake.py", line 40, in __init__
    self._cmake_command = CMake._get_cmake_command()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrinmoymahato/Coding/pytorch_dev/pytorch/tools/setup_helpers/cmake.py", line 60, in _get_cmake_command
    cmake_version = CMake._get_version(which("cmake"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrinmoymahato/Coding/pytorch_dev/pytorch/tools/setup_helpers/cmake.py", line 86, in _get_version
    for line in check_output([cmd, "--version"]).decode("utf-8").split("\n"):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pytorch_dev1/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pytorch_dev1/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/miniconda3/envs/pytorch_dev1/bin/cmake', '--version']' died with <Signals.SIGABRT: 6>. 
```

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.0 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.0-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M1

Versions of relevant libraries:
[pip3] No relevant packages
[conda] No relevant packages

cc @malfet @seemethere @albanD

**Comment by malfet** [comment]
Didn't know we have `module: m1` now. Perhaps we should call it MacOSArm or Apple Silicon (as M1 is old news already)

**Comment by malfet** [comment]
Judging from 
```
Building wheel torch-2.2.0a0+gitb3ad29e
dyld[8200]: Library not loaded: @rpath/librhash.0.dylib
  Referenced from: <39E92F07-1A2A-395C-89BF-CE060F8A99DD> /opt/miniconda3/envs/pytorch_dev1/bin/cmake
  Reason: tried: '/opt/miniconda3/envs/pytorch_dev1/bin/../lib/librhash.0.dylib' (no such file), '/opt/miniconda3/envs/pytorch_dev1/bin/../lib/librhash.0.dylib' (no such file), '/usr/local/lib/librhash.0.dylib' (no such file), '/usr/lib/librhash.0.dylib' (no such file, not in dyld cache)
```
it does not look like a PyTorch problem, but rather cmake that you've installed on your system can not be executed as is.
