### ISSUE TITLE
Triton bug when inductor workers are launced with spawn

### ISSUE THREAD

**Issue by ErnestChan** [pytorch/pytorch#113301]
### 🐛 Describe the bug

On PT2.1, compiling triton code that has `tl.device_assert` with inductor workers started with `spawn` raises this error:
```
    tl.device_assert((0 <= tmp22) & (tmp22 < 12), "index out of bounds: 0 <= tmp22 < 12")
                                                  ^
AttributeError("'NoneType' object has no attribute 'f_code'")
```

The error comes from [this line](https://github.com/openai/triton/blob/main/python/triton/language/core.py#L1689) in the Triton repo:
```
file_name = frame.f_back.f_code.co_filename
```

This errors because for spawned processes the first stack frame is 
```
  File "<string>", line 1, in <module>
  ```
  which is a module with no `__name__`. When `tl.device_assert` runs it iterates up to the first frame where `frame.f_back` is None, so `frame.f_back.f_code` throws an error.

Here's a snippet that should reproduce the error. There is a grid_sample in there because it generates triton code that has `tl.device_assert`:
```python
import os
import tempfile

import torch
import torch.nn as nn
from torch.nn.functional import grid_sample
import torch._inductor.config
from torch._inductor.codecache import AsyncCompile


class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 3, 1)

    def forward(self, input, grid):
        input = self.conv(input)
        # grid_sample results in generated triton code with device_assert, which causes the issue
        sampled = grid_sample(input, grid, align_corners=False)
        return sampled.sum()


if __name__ == "__main__":
    # Make sure we have a fresh cache dir
    cache_dir = tempfile.mkdtemp()
    os.environ["TRITON_CACHE_DIR"] = os.path.join(cache_dir, "triton")

    # Launch workers with spawn. Make sure to set TORCHINDUCTOR_COMPILE_THREADS=1 before
    # running the script so inductor workers aren't already started
    torch._inductor.config.worker_start_method = "spawn"
    torch._inductor.config.compile_threads = 2
    AsyncCompile.warm_pool()

    input = torch.rand((4, 3, 12, 12)).to(device="cuda")
    grid = (torch.rand((4, 3, 3, 2)) - 0.5).to(device="cuda")
    model = Model().to("cuda")
    model = torch.compile(model, mode="default")
    loss = model(input, grid)
    loss.backward()
```

To make sure inductor workers are started with `spawn` please run this with:
```
TORCHINDUCTOR_COMPILE_THREADS=1 python repro.py
```

I think the fix should actually be in the Triton repo but putting the issue here because its related to how torch.compile uses Triton. Happy to put up a fix.
It would be nice to add a test for this too.

### Versions

Ran on Ubuntu 20.04 LTS, Nvidia A100, using Pytorch 2.1.0 built from source.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by ErnestChan** [comment]
This should fix the issue: https://github.com/openai/triton/pull/2631

**Comment by wconstab** [comment]
@ErnestChan since you're already submitting a patch to triton, i'm assigning this PT issue to you too for tracking purposes.  Can you follow up to verify the fix and close this issue, or else if it needs further work you don't plan on doing feel free to kick it back to the oncall?

**Comment by ErnestChan** [comment]
sounds good

**Comment by ErnestChan** [comment]
Triton PR patch was merged
