### ISSUE TITLE
Unexpected datatypes in exported ONNX ops Less, Greater, Neg

### ISSUE THREAD

**Issue by spandantiwari** [pytorch/pytorch#11339]
I am seeing this issue in PyTorch-exported ONNX models where some of the exported ops, such as `Less`, `Greater`, and `Neg`, have unsupported datatypes for input and output tensors.  

As an example, consider the op `torch.lt`, which gets exported as ONNX op `Less`. The inputs to this `torch.lt` op could be tensors of integer type. When that’s the case the exported ONNX op `Less` has input argument as tensor of integer type, e.g. `tensor(int32)`. But integer tensors are not valid inputs as per the [ONNX spec]( https://github.com/onnx/onnx/blob/master/docs/Operators.md#Less), and therefore the ONNX op is having trouble loading in other runtimes. Additionally, on the output side, the exported `Less` op has the type `tensor(uint8)`, which is also not consistent with the ONNX spec which specifies it to be `tensor(bool)`.

I see similar issues in the export of other ONNX ops such as `Greater`, `Neg` (there could be others).

I am working with source build from master that is a couple of days old.

I can submit a PR for this issue. As a start we could insert `Cast` node on the input side during export. The output side may require a bit of a deeper fix where the `Node` that is created for the `Graph` object itself has the right type. But I haven’t been able to pinpoint where exactly that happens in code. Any pointers/help would be very helpful.

**Comment by houseroad** [comment]
First step: 1) Add the int32 and int64 to `Less` and `Greater` to ONNX
Then, we will fix the output problem

**Comment by houseroad** [comment]
First step https://github.com/onnx/onnx/pull/1390

**Comment by spandantiwari** [comment]
@houseroad - now that the first step is done, I am looking to fix the output issue. Is my understanding correct that this may have to be fixed during `Node`  instance creation (C++ side) when the `Graph` is being created. Some pointers on this will help get started on a fix.

**Comment by houseroad** [comment]
The problem is already solved.
