### ISSUE TITLE
MultivariateNormal and potrf is slow on gpu and seems to have some memory leak

### ISSUE THREAD

**Issue by koszpe** [pytorch/pytorch#11333]
## Issue description

When I initialize a [MultivariateNormal](https://github.com/pytorch/pytorch/blob/bb7d1837bc164b06e1d0826a20a8f7e8338a44e3/torch/distributions/multivariate_normal.py#L76) object with a covariance matrix provided with batch dimension too, it is very slow on GPU, and it is always slower on GPU then on CPU. 
It even seems to leak the memory with or without the batch dimension and both on CPU and GPU, but with different intensity (check n parameter in code example).
One more strange thing: It uses more CPU RAM when running on GPU.

Digging a bit deeper, I experienced the same with the Tensor's potrf function, so probably this is the root cause.

## Code example

```
import resource
import torch
from torch.distributions.multivariate_normal import MultivariateNormal
import gc
import time

def gpu(item, use_GPU=True):
    if use_GPU:
        return item.cuda()
    else:
        return item

def test_multivariate(loc_mat, cov_mat):
    standard_normal_dist = MultivariateNormal(loc=loc_mat,
                                              covariance_matrix=cov_mat)

def test_potrf(loc_mat, cov_mat):
    n = cov_mat.size(-1)
    [m.potrf(upper=False) for m in cov_mat.reshape(-1, n, n)]

def loop(fn_ref, n=10, size=10000, use_GPU=True, covariance_with_batch_dim=True, print_n=1):
    cov_mat = gpu(torch.zeros((2, 2)) + torch.eye(2), use_GPU)
    if covariance_with_batch_dim:
        cov_mat = cov_mat.unsqueeze(0).repeat(size, 1, 1)
    loc_mat = gpu(torch.zeros((size, 2)), use_GPU)

    for i in range(n):
        gc.collect()
        fn_ref(loc_mat, cov_mat)
        if i % print_n == 0:
            print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)


if __name__ == '__main__':

    n = 10
    fn_ref = test_multivariate
    use_GPU = True
    covariance_with_batch_dim = True
    print_n = n / 10

    print("test_fn: ", fn_ref.__name__)
    print("n: ", n)
    print("use_GPU: ", use_GPU)
    print("covariance_with_batch_dim: ", covariance_with_batch_dim, "\n")

    start = time.time()

    loop(fn_ref=fn_ref, use_GPU=use_GPU, covariance_with_batch_dim=covariance_with_batch_dim, n=n, print_n=print_n)

    print("\ntime: ", (time.time() - start) / n)
```
## Outputs

Testing MultivariateNormal

```
test_fn:  test_multivariate
n:  5
use_GPU:  False
covariance_with_batch_dim:  True 

118808
119200
119552
119908
120268

time:  0.08764233589172363
```

```
test_fn:  test_multivariate
n:  5
use_GPU:  True
covariance_with_batch_dim:  True 

1477808
1479680
1479996
1480312
1480684

time:  27.707138347625733
```

```
test_fn:  test_multivariate
n:  5000
use_GPU:  False
covariance_with_batch_dim:  False 

107904
107904
109436
109436
109700

time:  0.008288921689987183
```

```
test_fn:  test_multivariate
n:  50
use_GPU:  True
covariance_with_batch_dim:  False 

1467364
1468676
1468676
1468680
1468680

time:  0.037353959083557126
```

Testing potrf

```
test_fn:  test_potrf
n:  5
use_GPU:  False
covariance_with_batch_dim:  True 

116984
117300
117672
118032
118380

time:  0.06480374336242675
```

```
test_fn:  test_potrf
n:  5
use_GPU:  True
covariance_with_batch_dim:  True 

1476688
1477008
1477320
1477916
1478168

time:  26.757283926010132
```

```
test_fn:  test_potrf
n:  50000
use_GPU:  False
covariance_with_batch_dim:  False 

108420
109720
109984
110248
110512

time:  0.008067794122695923
```

```
test_fn:  test_potrf
n:  5
use_GPU:  True
covariance_with_batch_dim:  False 

1468760
1469664
1469680
1469680
1469680

time:  0.2711141109466553
```

## System Info
Collecting environment information...
PyTorch version: 0.5.0a0+e9ad743
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 396.54
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] magma-cuda91              2.3.0                         1    pytorch
[conda] torch                     0.5.0a0+e9ad743           <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchnet                  0.0.4                     <pip>
[conda] torchvision               0.2.1                     <pip>

Pytorch is used in docker container
pip version:
pip 18.0 from /opt/conda/lib/python3.6/site-packages/pip (python 3.6)

**Comment by t-vi** [comment]
I think batch potrf #11796 may favourably change the performance on GPU.

**Comment by vishwakftw** [comment]
I could not reproduce the memory leak using `1.0.0.dev20181119`. @koszpe could you please retry this test with the nightly version? Also, batched Cholesky is available now which is extremely faster than looping, so there's no need of loops to compute the Cholesky factors of a batch of positive definite matrix.

**Comment by koszpe** [comment]
I checked it, there is no memory leak with the MultivariateNormal, neither with the torch.cholesky. I used 1.0.0.dev20181130 for testing. The potrf still have the issue, but it's not a problem anymore, if we use torch.cholesky instead.

**Comment by vishwakftw** [comment]
Thank you for checking @koszpe . Could you close the issue since it is now resolved?

**Comment by koszpe** [comment]
Thanks for the fix

**Comment by danielcrane** [comment]
@koszpe Sorry to revive an old issue, but do you remember if you ever fixed initialising the distribution being so much slower on GPU than CPU? 

I'm also having similar issues, and reported it here: https://github.com/pytorch/pytorch/issues/23780

**Comment by koszpe** [comment]
@danielcrane Sorry for the late answer. No, I only had to initialize the distribution once at initialization phase, so it wasn't a real problem for me.
