### ISSUE TITLE
ValueError: Unknown CUDA arch (8.9) or GPU not supported

### ISSUE THREAD

**Issue by geniecity** [pytorch/pytorch#113418]
### 🐛 Describe the bug

"Hello, I am currently encountering an error during the installation process of Detectron2.
pip install -e .
414, in _get_cuda_arch_flags
raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (8.9) or GPU not supported
[end of output]

Note: This error originates from a subprocess, and is likely not a problem with pip.

This is the error that occurred. My computer's GPU is an RTX 4080, and I entered the following when installing Detectron2: conda install pytorch==1.6 torchvision cudatoolkit=10.1 -c pytorch

How can I resolve this error?"

### Versions

python version = 3.7

Detectron2: conda install pytorch==1.6 torchvision cudatoolkit=10.1 -c pytorch

**Comment by soulitzer** [comment]
Issues are for bug reports and feature requests only, please refer to the forum here https://discuss.pytorch.org/c/autograd/7 for questions please.
