### ISSUE TITLE
A tutorial for introducing the third-party malloc library to improve pytorch memory performance on Windows feature

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#113429]
### 📚 The doc issue

The tutorial is to introduce the new feature implemented by https://github.com/pytorch/pytorch/issues/102534 to accelerate performance on windows

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @fritzo @neerajprad @alicanb @nikitaved

**Comment by svekars** [comment]
Do you want to add it as a tutorial to the pytorch/tutorials repo instead?

**Comment by jingxu10** [comment]
We may not have enough time to meet the Docathon this time, due to performance number review. We will push a PR for this tutorial article later on.
