### ISSUE TITLE
Getting log for pytorch models

### ISSUE THREAD

**Issue by akote123** [pytorch/pytorch#113434]
Hi,
   I would like know how we can generate log in pytorch that is in tenosrflow we have option of setting TF_CPP_MAX_VLOG_LEVEL flag.Do we have any options like this in pytorch.

Thanks

**Comment by soulitzer** [comment]
You can use `TORCH_LOGS="<options>" python blah.py` though that is mostly used for torch compile currently.
Please use the https://discuss.pytorch.org/c/autograd/7 forums for questions, issues are for bugs and feature requests.
