### ISSUE TITLE
Quantization Model Support

### ISSUE THREAD

**Issue by suexu1025** [pytorch/pytorch#11348]
Hello,
I was working on quantization problems. Is wondering if caffe2 8 bit runtime would be supported in the future?

**Comment by soumith** [comment]
we are planning this feature into PyTorch. It wont be part of initial 1.0 release, but will be part of subsequent release.

**Comment by suexu1025** [comment]
Can you give a rough estimate of its timeline, should we expect it by end of this year or 2019?

Thanks!

**Comment by soumith** [comment]
good question. I'll get back to you on a committed timeline.

**Comment by bhack** [comment]
Is it a dup of https://github.com/pytorch/pytorch/issues/7553?

**Comment by soumith** [comment]
this feature is planned for 1.1, we will have a proposal listed out soon.

**Comment by matejaputic** [comment]
@soumith Is there a public-visible issue associated with the quantization development effort? Where can we find the proposal? Reeally need this for my dissertation ... 🙏

**Comment by zhyj3038** [comment]
need a tutorials for quantization too!!

**Comment by karanchahal** [comment]
@matejaputic there's a quantisation proposal somewhere in the pytorch issues. It has a lot of info.

**Comment by ezyang** [comment]
The main issue is #18318

**Comment by banderlog** [comment]
As far as I was able to understand while I was wondering in crossreferences: there is no implemented working solution but it is under priority development.


#18318 points to https://github.com/pytorch/pytorch/wiki/torch_quantization_design_proposal

Also #18318 mentioned in different project issues https://github.com/williamFalcon/pytorch-lightning/issues/76, from where I was able to get to #24076 

Also there is dev's answer on forum: https://discuss.pytorch.org/t/quantization-as-pytorch-script-graph-manipulation/53567/2

>We are actively working on something very similar to your proposal, soon to be released!

**Comment by gottbrath** [comment]
Note that we have a notebook with a preview tutorial on eager mode post training quantization over in https://github.com/pytorch/pytorch/issues/18318 ... please check it out and leave feedback.
