### ISSUE TITLE
[doc] scale parameter notation for torch.Tensor.cauchy_ is misleading

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#113426]
### 📚 The doc issue

Scale parameter notation currently used for torch.Tensor.cauchy_ is misleading.
Sigma (σ) is usually used to denote square root of variance. Variance is undefined in Cauchy distribution.
Replace sigma (σ) with gamma (γ).

Background: https://github.com/pytorch/pytorch/pull/37984#discussion_r1059551749

cc @fritzo @neerajprad @alicanb @nikitaved @svekars @carljparker

Implemented by https://github.com/pytorch/pytorch/pull/113178

**Comment by mingxzhao** [comment]
Seems like this issue is already fixed by @min-jean-cho in #113178 . If any other change is needed please let me know.
