### ISSUE TITLE
Should `_native_batch_norm_legit_functional` be in native_functions.yaml?

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#113483]
`_native_batch_norm_legit_functional` is listed under `_native_batch_norm_legit`, and both are introduced by https://github.com/pytorch/pytorch/pull/88697. They share the same function signature, but `_native_batch_norm_legit_functional` is only invoked by Functionalization. Is there a next plan for the op, or should it go into native_functions.yaml as an independent op?

NOTE: https://github.com/pytorch/pytorch/blob/7ccca60927cdccde63d6a1d40480950f24e9877a/aten/src/ATen/native/native_functions.yaml#L4234-L4241

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by cpuhrsch** [comment]
@titaiwangms - As indicated by the leading underscore this is a private function. How has this come to your attention?
