### ISSUE TITLE
Remove approvals when reverting a pr

### ISSUE THREAD

**Issue by PaliC** [pytorch/pytorch#113453]
### When a PR is reverted, remove approvals as well.

When a PR is reverted, we should also remove approvals as well.

Otherwise, we can end up with adverse cases where the pr author just remerges a broken PR and breaks things again.

Example: https://github.com/pytorch/pytorch/pull/112278

cc @ZainRizvi @kit1980 @huydhn @clee2000

**Comment by kit1980** [comment]
I'm not sure I agree. Why not just require a new PR then, as we say in the documentation?
cc @malfet

**Comment by malfet** [comment]
I agree with @kit1980 : it's not just a technical change, but requires some  sort of an ack from PyTorch dev community. To follow the same logic, reviews should be invalidated if changes are pushed to the PR after it has been approved, but we are not doing that. If this is the case, how revert is any different?

**Comment by albanD** [comment]
I think re-reviews on revert and on new push in the PR should be required for users who don't have write access to the repo.

**Comment by malfet** [comment]
Agree with the above approach. @PaliC do you mind proposing the PR to implement that?

**Comment by PaliC** [comment]
Closed by https://github.com/pytorch/test-infra/pull/4782
