### ISSUE TITLE
[doc] clarify the range of sampled rv for torch.tensor.exponential_

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#113428]
### 📚 The doc issue

Range of sampled random variable needs to be clarified for torch.tensor.exponential_ whose supported interval is (0, inf) is different from [0, inf] of exponential distribution.

Background: https://github.com/pytorch/pytorch/pull/37984#discussion_r1059527457, https://github.com/pytorch/pytorch/issues/48841#issuecomment-1530439039, https://github.com/pytorch/pytorch/pull/91673#discussion_r1069955813

cc @fritzo @neerajprad @alicanb @nikitaved @svekars @carljparker

Implemented by https://github.com/pytorch/pytorch/pull/113195

**Comment by min-jean-cho** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/113195.
