### ISSUE TITLE
[doc] two diff meanings of rv generated by torch.tensor.geometric_ and torch.distributions.geometric.Geometric

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#113427]
### 📚 The doc issue

The meaning of random variables generated by torch.tensor.geometric_ and torch.distributions.geometric.Geometric are different, and they are defined by two different PMFs.
Inform the user, so the user can choose their desired one.

Background: https://github.com/pytorch/pytorch/pull/37984#issuecomment-630336511

cc @fritzo @neerajprad @alicanb @nikitaved @svekars @carljparker

Implemented by https://github.com/pytorch/pytorch/pull/113183

**Comment by min-jean-cho** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/113183.
