### ISSUE TITLE
[doc] torch.tensor.geometric_, torch.tensor.uniform_ fix PMF vs PDF

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#113425]
### 📚 The doc issue

Geometric distribution is discrete, fix to PMF (probability mass function)
Continuous uniform distribution is continuous, fix to PDF (probability density function)

Implemented by https://github.com/pytorch/pytorch/pull/113109

cc @fritzo @neerajprad @alicanb @nikitaved @svekars @carljparker

**Comment by min-jean-cho** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/113109.
