### ISSUE TITLE
Implement pass-through `state_dict` and `load_state_dict` for dynamo `OptimizedModule`

### ISSUE THREAD

**Issue by awaelchli** [pytorch/pytorch#113422]
### 🚀 The feature, motivation and pitch

I propose that we implement `.state_dict()` and `.load_state_dict()` in [OptimizedModule](https://github.com/pytorch/pytorch/blob/c7e12c7427eef5a3e212371b386fcc6b31e944c5/torch/_dynamo/eval_frame.py#L168) in such a way that they bypass the wrapper and return/load the state from the inner `_orig_mod` module. 

Motivation:
- User might accidentally save the state dict of a compiled model into their checkpoint, only to find out later they can't load because the keys don't match
- The torch-compiled module may be wrapped by FSDP, DDP, etc. This would make it cumbersome for the user to save a checkpoint while also removing these keys or unwrapping the model. 

The sketch of the implementation:

```py
class OptimizedModule(torch.nn.Module):
    ...
    
    def state_dict(self, *args, **kwargs):
        return self._orig_mod.state_dict(*args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        # TODO: add some backward-compatibility code here
        return self._orig_mod.load_state_dict(*args, **kwargs)

```

With this implementation, we can effortlessly load the state-dict of a regular nn.Module into a torch-compiled module and vice versa!

### Alternatives

Keep as is.

### Additional context

This would probably also close/fix #94575
I am happy to send a PR for this.

cc @mruberry @mikaylagawarecki @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by awgu** [comment]
Just some passing thoughts:

Since `state_dict` does not recursively call the `state_dict` of submodules, this approach does not work if a submodule is compiled into an `OptimizedModule`. This creates a divergence between the state dicts constructed when the root is `OptimizedModule` vs not. We previously handled this situation using state dict hooks, but we have learned the hard way that they are difficult to compose and get right.

cc: @fegin @wz337 for more context on the challenges around this kind of approach

**Comment by awaelchli** [comment]
@awgu I see state_dict gets called on submodules here: https://github.com/pytorch/pytorch/blob/cb48f7855adb9dcefb6855c2ef99aa5a26b16e86/torch/nn/modules/module.py#L1892-L1894
So I think even if there are compiled submodules, it would still retrieve the state dict correctly. Perhaps you meant that `load_state_dict()` is not called recursively on submodules? In this case, I think the approach would still work, because what it is trying to fix is really just the access of keys at the root module.

**Comment by awgu** [comment]
@awaelchli Good catch! That is my bad -- I misremembered and meant `load_state_dict`, and your point makes sense.

**Comment by awaelchli** [comment]
@awgu Great, thanks! I've opened a PR and so far I haven't discovered any bad edge cases.

**Comment by awaelchli** [comment]
What do you think about the approach in my PR? I've tested different ways the module can be saved and loaded https://github.com/pytorch/pytorch/pull/113423, and the rest of the CI also seems to be ok with the change. I appreciate the feedback :)
