### ISSUE TITLE
Cpuinfo crashes on AWS lambda aarch64

### ISSUE THREAD

**Issue by michal-sankot** [pytorch/pytorch#113568]
Pytorch crashes when run on AWS lambda with aarch64 (arm) architecture.

It used to be patched by https://github.com/pytorch/pytorch/pull/16107 in Pytorch 1.x but it no longer works in 2.x

```
Error in cpuinfo: failed to parse the list of possible processors in /sys/devices/system/cpu/possible
Error in cpuinfo: failed to parse the list of present processors in /sys/devices/system/cpu/present
Error in cpuinfo: failed to parse both lists of possible and present processors
```
Issue is reported on cpuinfo repo too https://github.com/pytorch/cpuinfo/issues/143, but got no solution yet.

### Versions

 PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (aarch64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.26

Python version: 3.9.18 (main, Oct 20 2023, 09:55:31)  [GCC 7.3.1 20180712 (Red Hat 7.3.1-17)] (64-bit runtime)
Python platform: Linux-4.14.255-327-266.539.amzn2.aarch64-aarch64-with-glibc2.26
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory

Versions of relevant libraries:
[pip3] No relevant packages
[conda] Could not collect

cc @seemethere @malfet @osalpekar @atalman @snadampal

**Comment by michal-sankot** [comment]
@snadampal there isn't afaik. But I can create one. It should be basically just starting pytorch on AWS lambda with arm architecture.

**Comment by malfet** [comment]
@michal-sankot can you repro it outside of lambda somehow? (I'm asking from perspective of CI, as we've been running this code on AWS runners for a while and it seems to be working fine)

**Comment by tringwald** [comment]
I just checked `torch==2.1.0` on a normal EC2 ARM instance. It seems to work fine there. I guess that in the Lambda runtime environment `/sys` is not mounted, which is why `cpuinfo` complains.

**Comment by malfet** [comment]
@tringwald is it documented somewhere that `/sys` is not accessible from lambdas? Let me try to propose a small fix

**Comment by malfet** [comment]
Ok, perhaps I misunderstand what `crashes` means, but if `/sys` is not accessible, PyTorch works, though prints an annoying warning:
```
$ python3 -c "import torch;print(torch.rand(3, 3,))"; echo $?
Error in cpuinfo: failed to parse the list of possible processors in /sys/devices/system/cpu/possible
Error in cpuinfo: failed to parse the list of present processors in /sys/devices/system/cpu/present
Error in cpuinfo: failed to parse both lists of possible and present processors
tensor([[0.4759, 0.7866, 0.9695],
        [0.0245, 0.8755, 0.1609],
        [0.9656, 0.3225, 0.3899]])
0

```
Do you have a concrete example of the crash?

**Comment by malfet** [comment]
Hmm, ok, I see the crash if one is calls `set_num_threads()`:
```
$ python3 -c "import torch;torch.set_num_threads(1)"; echo $?
Error in cpuinfo: failed to parse the list of possible processors in /sys/devices/system/cpu/possible
Error in cpuinfo: failed to parse the list of present processors in /sys/devices/system/cpu/present
Error in cpuinfo: failed to parse both lists of possible and present processors
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at ThreadPool.cc:44] cpuinfo_initialize(). cpuinfo initialization failed
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x50 (0xffff85c33660 in /home/ubuntu/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::ThrowEnforceNotMet(char const*, int, char const*, char const*, void const*) + 0x50 (0xffff85c33800 in /home/ubuntu/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x2e04e58 (0xffff88aa3e58 in /home/ubuntu/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x2e07b04 (0xffff88aa6b04 in /home/ubuntu/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #4: at::set_num_threads(int) + 0x2c (0xffff8698188c in /home/ubuntu/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x5ced1c (0xffff8deebd1c in /home/ubuntu/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: python3() [0x55f094]
<omitting python frames>
frame #10: python3() [0x64eac0]
frame #11: python3() [0x64eb8c]
frame #16: __libc_start_main + 0xe8 (0xffff8f3f4e10 in /lib/aarch64-linux-gnu/libc.so.6)
frame #17: python3() [0x59bb68]

Aborted (core dumped)
```

**Comment by malfet** [comment]
Ok, so I think there are 2 (3) problems here:
 - `THPModule_setNumThreads` should capture exceptions
 - One should probably explicitly call `cpuinfo_initilize` ahead of time and ignore the errors
 - And may on cpuinfo on ARM platform should continue initialization rather rather than error out if `/sys` is not available

**Comment by snadampal** [comment]
with the latest nightly torch version `2.2.0.dev20231120` I'm able to run pytorch on AWS lambda with `arm64` architecture.
thanks @malfet for the fix: https://github.com/pytorch/pytorch/commit/310e3060b7e4d0c76149aadad4519c7abed8c2a7

I have used the `public.ecr.aws/lambda/python:3.11` base image and installed torch nightly wheel. 
and this is the lambda function I have tested:
```
import sys
import torch
def handler(event, context):
    print(torch.__version__, torch.__config__.show())
    torch.set_num_threads(8)
    a=torch.rand(100, 100, 100); b=torch.rand(100,100, 100)
    for i in range(10):
        torch.bmm(a,b).sum()

    return torch.__version__
```

**Comment by malfet** [comment]
Thank you for checking, will cherry-pick the changes in upcoming 2.1.2 release (and may be tweak logic in `cpu_info` later)

**Comment by huydhn** [comment]
Confirm that this is fixed on 2.1.1 final RC `pip install --pre torch==2.1.2 --index-url https://download.pytorch.org/whl/test` on Linux aarch64 instance.

```
$ chmod 500 /sys
$ python -c 'import torch; torch.set_num_threads(8)'
Error in cpuinfo: failed to parse the list of possible processors in /sys/devices/system/cpu/possible
Error in cpuinfo: failed to parse the list of present processors in /sys/devices/system/cpu/present
Error in cpuinfo: failed to parse both lists of possible and present processors
[W ThreadPool.cc:48] cpuinfo initialization failed
```

**Comment by StanislavMakhrov** [comment]
Problem is reproduces on pytorch 2.2.2

**Comment by jsteinberg-rbi** [comment]
still for 2.5.1. there's supposedly a hack fix for it [here](https://github.com/DiscreteTom/onnx-on-aws-lambda-arm64/tree/main) but I haven't had luck with it. first off the sys filesystem on lambda is RO and controlled by AWS naturally and actually none of the /sys/devices/, /sys/devices/system or /sys/devices/system/cpu directories even exist so I don't get how the author's code works in the first place, but I'm also using a custom ubuntu docker image although I don't understand why that would matter.
