### ISSUE TITLE
P0: Integrate distributed logger with TORCH_LOGS, make sure upper level library can't override distributed LOG level.

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#113544]
Integrate torch distributed logging with TORCH_LOGS, by using a exclusive `distributed` artifact

*Option 1*
'distributed' component covers all of distributed logs (at least python ones)

*Option 2*
use subcomponents (ddp, fsdp, c10d, ...) instead of one major component

*Option 3*
can we do both? I don't know if the infra supports this  (distributed is a parent, ddp, fsdp are children, can be configured separately)

Note: logs from C++ components for distributed also need to be addressed, an i'm not sure if the current TORCH_LOGS infra provides a way to unify those.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @fduwjj @wz337 @tianyu-l @wconstab @yf225 @kiukchung @lucasllc @d4l3k

**Comment by wconstab** [comment]
current state of TORCH_LOGS for distributed is 
 * `ddp_graphs` is an artifact logger that prints out stuff from DDPOptimizer
 * `dynamo` logger prints a little more stuff from DDPOptimizer (needs to be rationalized)
 * `distributed` component exists but i'm not sure how much it's used

**Comment by fegin** [comment]
I prefer option 2. It can be extremely noisy if we only have one nob for all the components.

**Comment by wconstab** [comment]
agree option 1 is too noisy.

I  think option 3 is actually easy to do.  does that change your mind?  https://github.com/pytorch/pytorch/pull/114376

**Comment by wanchaol** [comment]
> I think option 3 is actually easy to do. does that change your mind? #114376

I would vote for option 3 too, logging should also be "multi-level IR" which is easy to debug different components if we only want to see the logs from those components.

> distributed -- parent component
> ptd_ddp - child component

Thanks for the proposals! I like the structured proposal, I wondering if TORCH_LOGS have some parsing capability so that the naming are more aligned, could we do something like this:
> TORCH_LOGS="dist" -> parent componet
> TORCH_LOGS="dist:ddp" -> child component

**Comment by wconstab** [comment]
> I wondering if TORCH_LOGS have some parsing capability

not currently; in fact there is not even a concept of parent-child inside TORCH_LOGS.  Instead, its just that TORCH_LOGS components get defined against a list of python module fqn's, which lets you make components act like parent-child in some sense.  In reality, `distributed` and `ptd_fsdp` would be peers not parent-child, and `ptd_fsdp` would just include a more specific set of fqns.

**Comment by wanchaol** [comment]
Got it, yeah this make sense!

> In reality, `distributed` and `ptd_fsdp` would be peers not parent-child

would like to clarify more on this: I thought ptd_fsdp would strictly be a child under `distributed`? because the folder `torch.distributed.fsdp` lives under `torch.distributed`?

**Comment by wconstab** [comment]
> would like to clarify more on this: I thought ptd_fsdp would strictly be a child under distributed? because the folder torch.distributed.fsdp lives under torch.distributed?

Yes, functionally they would be parent-child, but literally (in the sense of our logging registrations) they would be peers.  In other words, the logging registration builds a flat list not a tree.  But because each item specifies its own set of fqns, you can build arbitrary trees out of it.

**Comment by wanchaol** [comment]
This should be done already by @wconstab and @fduwjj
