### ISSUE TITLE
[dynamo] Be stricter about lifetime of dynamo metadata and graph

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#113516]
### 🚀 The feature, motivation and pitch

As identified in https://github.com/pytorch/pytorch/pull/113374/files#r1390216114, certain metadata created and consumed by dynamo is needlessly propagated to downstream compilers. 

For hygeine sake, let's remove it.

### Alternatives

NIL

### Additional context

NIL

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by yf225** [comment]
Do you have examples of the needless metadata? (the https://github.com/pytorch/pytorch/pull/113374/files#r1390216114 link jumps to your PR but I couldn't find direct reference to that)

**Comment by jon-chuang** [comment]
[They are here](https://github.com/pytorch/pytorch/pull/113374#discussion_r1390216114)
