### ISSUE TITLE
`torch._dynamo.config.suppress_errors` may not be properly reset

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#113606]
In the test suite, the default behavior is that `suppress_errors=True` so that even if any tests don't cleanly graph break, this should not lead to a test failure. 

This default behavior is set here: https://github.com/pytorch/pytorch/blob/ff82dcd8fa3571d48b64176ee2befe68db9d0dcc/torch/testing/_internal/common_utils.py#L1257

However, there are also places in the code that unset this flag

https://github.com/pytorch/pytorch/blob/fd209543d5dfced3146d64df3af6361fc61fb74a/torch/_inductor/lowering.py#L1677-L1684 does this.

If tests trigger this logic, but do not properly reset the flag, that can potentially lead to flaky tests. See: https://github.com/pytorch/pytorch/issues/110288#issuecomment-1789364941
            

cc @mruberry @ZainRizvi @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by anijain2305** [comment]
This is not valid anymore as we have better PyTorch-TorchDynamo testing.
