### ISSUE TITLE
inductor/test_aot_inductor.py gets segfault but test ultimately passes

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#113691]
ex https://ossci-raw-job-status.s3.amazonaws.com/log/18679099381, search for `got exit code -11`
The process had a non zero segfault, but I can't find any tests that actually failed.

I think the last time this happened there was some kineto failure unrelated to the test?

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by malfet** [comment]
We have a lots of test which launch subprocess that can segfault, but we are testing sort of recovery mechanism. I wonder if this is one of those...

**Comment by clee2000** [comment]
I thought that too, but I'm a bit suspicious about how the launched subprocess's exit code gets propagated to the parent test and then also the overall test running process

**Comment by huydhn** [comment]
AI: Double check if this still happens, and decide to close it or to move it to cold storage accordingly

**Comment by clee2000** [comment]
The failure is now surfaced after #115775 and the failing tests are disabled.  I believe the inductor team is looking into this, closing as the devx side is done.
