### ISSUE TITLE
Implement Variable Tracker for Dataclasses

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#113670]
# Summary

When trying to compile w/ full graph on a model that uses dataclasses I am getting:
``` Python
    proxy_kwargs = {key: arg.as_proxy() for key, arg in kwargs.items()}
  File "/home/drisspg/meta/pytorch/torch/_dynamo/variables/base.py", line 274, in as_proxy
    raise NotImplementedError(str(self))
NotImplementedError: UserDefinedObjectVariable(ScaledMMConfig)
```

I am running into a lack of variable tracker coverage for dataclasses.

This issue is to track adding support for this

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @aakhundov

**Comment by mlazos** [comment]
I went through some examples on creating dataclasses like the following:
```py
import torch
import dataclasses

@dataclasses.dataclass
class Base:
    x: int = 15.0
    y: int = 0


@torch.compile(fullgraph=True)
def fn(x, d):
    z = Base(15, 0)
    z.x += 2
    x.x += 1

    return x.x * d * z.x

x = Base(15, 0)

fn(x, torch.ones(2, 2))
```

This is supported by dynamo today, so a smaller repro is preferable. I will close for now since dataclasses appear to be supported but feel free to reopen with a smaller repro/update.

**Comment by drisspg** [comment]
For context I think the problem was that I was using dataclases as inputs to the Autograd HOP and speculate subgraph was throwing up lol
