### ISSUE TITLE
RoCm support loop unrolling for `at::native::gpu_kernel_multiple_outputs`

### ISSUE THREAD

**Issue by fxmarty** [pytorch/pytorch#113773]
### 🚀 The feature, motivation and pitch

Hi, compiling https://github.com/fxmarty/flash-attention-rocm/blob/rotary-rocm/csrc/rotary/rotary_cda.cu for RoCm, I am getting quite a few `/usr/local/lib/python3.10/dist-packages/torch/include/ATen/native/hip/Loops.cuh:271:17: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]` warnings.

Full log:
```
/opt/rocm-5.7.0/bin/hipcc -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/lib/python3.10/dist-packages/torch/include/THH -I/opt/rocm-5.7.0/include -I/usr/include/python3.10 -c rotary_cda.hip -o build/temp.linux-x86_64-3.10/rotary_cda.o -fPIC -D__HIP_PLATFORM_AMD__=1 -DUSE_ROCM=1 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=rotary_emb -D_GLIBCXX_USE_CXX11_ABI=0 --offload-arch=gfx90a -fno-gpu-rdc -std=c++17
In file included from rotary_cda.hip:8:
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/native/hip/Loops.cuh:271:17: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
__global__ void unrolled_elementwise_kernel_for_multi_outputs(int N, func_t f, array_t data, inp_calc_t ic, out_calc_t oc) {
```

I am not sure whether those are important performance-wise, but `nvcc` does not show these warnings - so I guess in this specific case loop unrolling is performed on NVIDIA GPUs but not AMD ones.

Using this kernel instead with non-unrolled loops is for me actually slower than a manual implementation https://github.com/fxmarty/text-generation-inference/blob/ea8438a5a0bbe376a0cbadc1b3ea593235ba4e92/server/text_generation_server/utils/layers.py#L571-L583.

Thank you!

### Alternatives

ignore the warning

### Additional context

`torch==2.2.0.dev20231030+rocm5.7`
`hipcc==5.7.31921-d1770ee1b`

using the following base container
```
FROM rocm/dev-ubuntu-22.04:5.7

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    python3.10 \
    python3.10-dev \
    python3-pip \
    git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1 && \
    python -m pip install -U pip

RUN pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.7
```

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by pruthvistony** [comment]
cc @hongxiayang

**Comment by naromero77amd** [comment]
Our compiler team is aware of the issue and is tracking this internally. Since the unrolling limitation is more general and not necessarily specific to PyTorch, we will plan to close this issue soon.

**Comment by naromero77amd** [comment]
Spoke with @fxmarty . He was OK with closing since AMD is tracking this internally.
