### ISSUE TITLE
add exception handler for DataLoader when reading a damaged image file

### ISSUE THREAD

**Issue by nicklhy** [pytorch/pytorch#1137]
Currently, the data loader just crashes if `dataset.__getitem__(index)` failed (i.e. when reading a damaged image file). Is it possible to add an exception handler for it?
In training phase, I usually just want to skip this error and replace it with another sample.

**Comment by lanpa** [comment]
If the data is not growing during training phase, I would treat this as a data cleanup task before training.

However, you can override the default `__gettiem__()` as follows:

```python
import torchvision.datasets as dset
class ImageFolderEX(dset.ImageFolder):
    def __getitem__(self, index):
        path, label = self.imgs[index]
        try:
            img = self.loader(os.path.join(self.root, path))
        except:
            pass #your handling code
        return [img, label]
```

**Comment by nicklhy** [comment]
@lanpa , I am currently working on a large video dataset and it is almost impossible to check every frame of every video in advance. Thus, I have to handle the exceptions on-the-fly.
I have tried your suggested method and add an extra flag variable to control if we should skip these exceptions or just keep the original way. It works exactly what I want. Thank you.

**Comment by Wakeupbuddy** [comment]
@nicklhy when you skip an exception, what  __getitem__() will return in this call?  Could you elaborate your serror handling olution a little more? Thanks!

**Comment by nicklhy** [comment]
@Wakeupbuddy , As I mentioned above, I use a flag variable, say skip_flag, to control if I want to skip the errors. If skip_flag is False, I would simply raise an exception. If skip_flag is True, then I would randomly return another sample(i.e. __getitem__(np.random.randint(0, n))).
This method works well in train phase since it usually doesn't matter that you replace __getitem__(i) with __getitem__(j). But if you need to handle errors in test phase, it could be a little bit more complicate. You need to write you own dataloader class.

**Comment by fmassa** [comment]
No need to write another dataloader. Just return None on exception, and modify the `collate_fn` from the dataloader (which is an argument) so that it filters out None elements.

**Comment by nicklhy** [comment]
@Wakeupbuddy , for test phase, @fmassa 's idea is much better. You do not need to rewrite an absolutely new dataloader class.

**Comment by tsvetiko** [comment]
1. Return `None` in your `__getitem__` function if your image is corrupted

```   
    def __getitem__(self, img_path):
        try:
            img = load_img(img_path)
        except:
            return None
        return [img, label]
```

2. Filter the `None` values in the `collate_fn`

```
def collate_fn(batch):
    batch = list(filter(lambda x: x is not None, batch))
    return torch.utils.data.dataloader.default_collate(batch)
```

3. Pass the `collate_fn` to the `DataLoader`

```
train_loader = DataLoader(train_dataset, collate_fn=collate_fn, **kwargs)
test_loader = DataLoader(test_dataset, collate_fn=collate_fn, **kwargs)
```

**Comment by Marcelo5444** [comment]
This will erase the data sample with the None value or the whole batch of data?

**Comment by Sentient07** [comment]
Hi @fmassa ,

I am training Faster-RCNN on video data and I attempted to filter out absurd frames by returning None and pruning using `collate_fn` similar to  @tsvetiko 's suggestion. However, I face errors while iterating the `DataLoader` for none values,

```
    train_one_epoch(model, optimizer, data_loader, device, epoch, print_freq=200)
  File "/udd/rsundara/Code/fpnfrcnn_det/vision/engine.py", line 26, in train_one_epoch
    for images, targets in metric_logger.log_every(data_loader, print_freq, header):
ValueError: not enough values to unpack (expected 2, got 0)
```

Could someone please help me? thanks!

**Comment by Martin36** [comment]
> Follow these steps in order to handle corrupted images:
> 
> 1. Return `None` in the `__getitem__()` if the image is corrupted
> 
> ```
> def __getitem__(self, idx):
>     try:
>         img, label = load_img(idx)
>     except:
>         return None
>     return [img, label]
> ```
> 
> 1. Filter the `None` values in the `collate_fn()`
> 
> ```
> def collate_fn(batch):
>     batch = list(filter(lambda x: x is not None, batch))
>     return torch.utils.data.dataloader.default_collate(batch)
> ```
> 
> 1. Pass the `collate_fn()` to the `DataLoader()`
> 
> ```
> train_loader = DataLoader(train_dataset, collate_fn=collate_fn, **kwargs)
> test_loader = DataLoader(test_dataset, collate_fn=collate_fn, **kwargs)
> ```

How would you handle batches where all the values are `None`, since that would pass an empty list to `default_collate()`?

For large batches this may not be a problem, but for small batches it could happen.

**Comment by ShunLu91** [comment]
> > Follow these steps in order to handle corrupted images:
> > 
> > 1. Return `None` in the `__getitem__()` if the image is corrupted
> > 
> > ```
> > def __getitem__(self, idx):
> >     try:
> >         img, label = load_img(idx)
> >     except:
> >         return None
> >     return [img, label]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Filter the `None` values in the `collate_fn()`
> > 
> > ```
> > def collate_fn(batch):
> >     batch = list(filter(lambda x: x is not None, batch))
> >     return torch.utils.data.dataloader.default_collate(batch)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Pass the `collate_fn()` to the `DataLoader()`
> > 
> > ```
> > train_loader = DataLoader(train_dataset, collate_fn=collate_fn, **kwargs)
> > test_loader = DataLoader(test_dataset, collate_fn=collate_fn, **kwargs)
> > ```
> 
> How would you handle batches where all the values are `None`, since that would pass an empty list to `default_collate()`?
> 
> For large batches this may not be a problem, but for small batches it could happen.

This link provides a 'better option' may be helpful with your problem but I haven't figure out how to include dataset in the collate_fn scope.

**Comment by ShunLu91** [comment]
> > Follow these steps in order to handle corrupted images:
> > 
> > 1. Return `None` in the `__getitem__()` if the image is corrupted
> > 
> > ```
> > def __getitem__(self, idx):
> >     try:
> >         img, label = load_img(idx)
> >     except:
> >         return None
> >     return [img, label]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Filter the `None` values in the `collate_fn()`
> > 
> > ```
> > def collate_fn(batch):
> >     batch = list(filter(lambda x: x is not None, batch))
> >     return torch.utils.data.dataloader.default_collate(batch)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Pass the `collate_fn()` to the `DataLoader()`
> > 
> > ```
> > train_loader = DataLoader(train_dataset, collate_fn=collate_fn, **kwargs)
> > test_loader = DataLoader(test_dataset, collate_fn=collate_fn, **kwargs)
> > ```
> 
> How would you handle batches where all the values are `None`, since that would pass an empty list to `default_collate()`?
> 
> For large batches this may not be a problem, but for small batches it could happen.

This [link](https://stackoverflow.com/questions/57815001/pytorch-collate-fn-reject-sample-and-yield-another) provides a 'better option' may be helpful with your problem but I haven't figure out how to include dataset in the collate_fn scope.

**Comment by ctr26** [comment]
> collate_fn=collate_fn

What would the equivalent be for a batch_size of 1?

**Comment by urimerhav** [comment]
Not sure why this thread was closed. Being able to not have your entire training run shut down over a single bad samples is a common use case. I'd add also that a timeout functionality would be useful. If a worker fails to deliver a sample in x seconds, we might want to drop it and move on to the next one. 

In real life applications scanning over every single example and validating it is often infeasible. This would make a great addition.

**Comment by theoYe** [comment]
> Follow these steps in order to handle corrupted images:
> 
> 1. Return `None` in the `__getitem__()` if the image is corrupted
> 
> ```
> def __getitem__(self, idx):
>     try:
>         img, label = load_img(idx)
>     except:
>         return None
>     return [img, label]
> ```
> 
> 1. Filter the `None` values in the `collate_fn()`
> 
> ```
> def collate_fn(batch):
>     batch = list(filter(lambda x: x is not None, batch))
>     return torch.utils.data.dataloader.default_collate(batch)
> ```
> 
> 1. Pass the `collate_fn()` to the `DataLoader()`
> 
> ```
> train_loader = DataLoader(train_dataset, collate_fn=collate_fn, **kwargs)
> test_loader = DataLoader(test_dataset, collate_fn=collate_fn, **kwargs)
> ```



> Follow these steps in order to handle corrupted images:
> 
> 1. Return `None` in the `__getitem__()` if the image is corrupted
> 
> ```
> def __getitem__(self, idx):
>     try:
>         img, label = load_img(idx)
>     except:
>         return None
>     return [img, label]
> ```
> 
> 1. Filter the `None` values in the `collate_fn()`
> 
> ```
> def collate_fn(batch):
>     batch = list(filter(lambda x: x is not None, batch))
>     return torch.utils.data.dataloader.default_collate(batch)
> ```
> 
> 1. Pass the `collate_fn()` to the `DataLoader()`
> 
> ```
> train_loader = DataLoader(train_dataset, collate_fn=collate_fn, **kwargs)
> test_loader = DataLoader(test_dataset, collate_fn=collate_fn, **kwargs)
> ```

I read some codes of pytorch , here is a full version of __getitem__, but notice that if all the batch images are crupted and passed, a empty list will be returned in the collate_fn which could produce an "list index out of range" error since pytorch have to fetch batch[0] for later operation.

```python
class ImageFolderEX(dset.ImageFolder):
    def __getitem__(self, index):
        path, target = self.samples[index]
        try:
            sample = self.loader(path)
        except:
            return None
        if self.transform is not None:
            sample = self.transform(sample)
        if self.target_transform is not None:
            target = self.target_transform(target)
        return sample, target
```

**Comment by theoYe** [comment]
> > Follow these steps in order to handle corrupted images:
> > 
> > 1. Return `None` in the `__getitem__()` if the image is corrupted
> > 
> > ```
> > def __getitem__(self, idx):
> >     try:
> >         img, label = load_img(idx)
> >     except:
> >         return None
> >     return [img, label]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Filter the `None` values in the `collate_fn()`
> > 
> > ```
> > def collate_fn(batch):
> >     batch = list(filter(lambda x: x is not None, batch))
> >     return torch.utils.data.dataloader.default_collate(batch)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Pass the `collate_fn()` to the `DataLoader()`
> > 
> > ```
> > train_loader = DataLoader(train_dataset, collate_fn=collate_fn, **kwargs)
> > test_loader = DataLoader(test_dataset, collate_fn=collate_fn, **kwargs)
> > ```
> 
> I read some codes of pytorch , here is a full version of `__getitem__`, but notice that if all the batch images are crupted and passed, a empty list will be returned in the collate_fn function which could produce an "list index out of range" error since pytorch have to fetch batch[0] for later operation.
> 
> ```python
> class ImageFolderEX( torchvision.datasets.ImageFolder):
>     def __getitem__(self, index):
>         path, target = self.samples[index]
>         try:
>             sample = self.loader(path)
>         except:
>             return None
>         if self.transform is not None:
>             sample = self.transform(sample)
>         if self.target_transform is not None:
>             target = self.target_transform(target)
>         return sample, target
> ```

**Comment by linminhtoo** [comment]
> > Follow these steps in order to handle corrupted images:
> > 
> > 1. Return `None` in the `__getitem__()` if the image is corrupted
> > 
> > ```
> > def __getitem__(self, idx):
> >     try:
> >         img, label = load_img(idx)
> >     except:
> >         return None
> >     return [img, label]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Filter the `None` values in the `collate_fn()`
> > 
> > ```
> > def collate_fn(batch):
> >     batch = list(filter(lambda x: x is not None, batch))
> >     return torch.utils.data.dataloader.default_collate(batch)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Pass the `collate_fn()` to the `DataLoader()`
> > 
> > ```
> > train_loader = DataLoader(train_dataset, collate_fn=collate_fn, **kwargs)
> > test_loader = DataLoader(test_dataset, collate_fn=collate_fn, **kwargs)
> > ```
> 
> How would you handle batches where all the values are `None`, since that would pass an empty list to `default_collate()`?
> 
> For large batches this may not be a problem, but for small batches it could happen.

have you tried returning None from the `collate_fn` ? then, in your training loop, you can check `if batch is None`, and don't do any forward pass, for example 
'''
if batch is None:
    continue
else:
    preds = model(batch)
'''

**Comment by jonatelintelo** [comment]
> continue

The issue here is that batch[0] will still throw an error when you want to loop over batch in the loader. The result is.

for batch in dataloader: 
IndexError: list index out of range on batch[0]

**Comment by juliawilkins** [comment]
@Martin36 https://github.com/pytorch/pytorch/issues/1137#issuecomment-880452870, did you ever find a solution for handling this with small batches where the entire batch could end up as none?

**Comment by Martin36** [comment]
> @Martin36 [#1137 (comment)](https://github.com/pytorch/pytorch/issues/1137#issuecomment-880452870), did you ever find a solution for handling this with small batches where the entire batch could end up as none?

@juliawilkins Unfortunately I do not remember if I did
