### ISSUE TITLE
Wrongly formatted string in profiler_util.py

### ISSUE THREAD

**Issue by naupa** [pytorch/pytorch#113756]
### 🐛 Describe the bug

The string in line https://github.com/pytorch/pytorch/blob/c3918c18b5f7b98ef83f9022062a9f1990e3324d/torch/autograd/profiler_util.py#L256
introduces too many brackets '{}' resulting in an not correctly formatted output string.

```python
print('"args": {{}}}}, ')
```

outputs
```
"args": {{}}}},
```

The correct expected output is:

```
"args": {}},
```

A possible bugfix is just:

```python
print('"args": {}}, ')
```
which outputs the expected result.

Notes
---------

* A git blame on https://github.com/pytorch/pytorch/blob/main/torch/autograd/profiler_util.py#L256 revealed that the code in pytorch 2.0.0 was ok, 2.10 is affected.
* We found the problem because profiling crashed since this mentioned string could not be interpreted as valid json.

### Versions

python collect_env.py
--2023-11-15 13:39:08--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21850 (21K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py                                   100%[=======================================================================================================>]  21.34K  --.-KB/s    in 0.007s  

2023-11-15 13:39:16 (3.19 MB/s) - ‘collect_env.py’ saved [21850/21850]

Collecting environment information...
PyTorch version: 2.1.0.post300
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 12 (bookworm) (x86_64)
GCC version: (Debian 12.2.0-14) 12.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.36

Python version: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
CPU family:                      6
Model:                           158
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        10
BogoMIPS:                        5184.02
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves flush_l1d arch_capabilities
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        1.5 MiB (6 instances)
L3 cache:                        12 MiB (1 instance)
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Unknown: Dependent on hypervisor status
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-mutable==1.2.0
[pip3] mypy==1.7.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] pytorch-lightning==2.1.0
[pip3] torch==2.1.0.post300
[pip3] torch-demand-ops==0.0.0
[pip3] torch-tb-profiler==0.4.1
[pip3] torchmetrics==1.2.0
[conda] Could not collect

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by malfet** [comment]
Oh, I see, it is caused by https://github.com/pytorch/pytorch/pull/107519/files#diff-25291b895a9131f22bf0d5c77ad3403629990bbe9c410256f571f26ce126f461

@Skylion007 this looks like a `ruff` bug, as `'"args": {{}}}}, '.format()` should have been replaced with `'"args": {}}, '

Fix is coming

**Comment by davidberard98** [comment]
looks like this code path is only used when kineto is not available, which is not the case in CI. will put up a PR with a test.
