### ISSUE TITLE
Cannot cast tensor to numpy array inside vmap due to "Access data pointer of tensor that doesn't have storage"

### ISSUE THREAD

**Issue by bensarthou** [pytorch/pytorch#113751]
### 🐛 Describe the bug

While trying to vectorize a function (working only on numpy array due to other dependencies) accross batch with vmap, I was unable to cast the input tensor of the function into numpy array, raising the following error

> Traceback (most recent call last):
>   File "[YOUR PYTHON SCRIPT]", line 63, in <module>
>     vmap_func(a)
>   File "[ENVPATH]\lib\site-packages\torch\_functorch\vmap.py", line 434, in wrapped
>     return _flat_vmap(
>   File "[ENVPATH]\lib\site-packages\torch\_functorch\vmap.py", line 39, in fn
>     return f(*args, **kwargs)
>   File "[ENVPATH]\lib\site-packages\torch\_functorch\vmap.py", line 619, in _flat_vmap
>     batched_outputs = func(*batched_inputs, **kwargs)
>   File "[YOUR PYTHON SCRIPT]", line 57, in func
>     a_np = tensor.numpy()
> RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
> 

The following code reproduces the error: 

```
from torch import vmap

a = torch.zeros((2, 10,10,10))

def func(tensor):
    a_np = tensor.numpy()
    # Here could be some code only available on numpy array ...
    return torch.from_numpy(a_np)

vmap_func = vmap(func)
vmap_func(a)

```

I've seen this error in other issues  ( #96041 for example) but the issue here doesnt seem to be related to the same problem

I don't know if it's an expected behaviour (maybe the way vmap dataflow works), but if it's not the case, I hope this issue can help some people

### Versions

PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000

Nvidia driver version: 528.24
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2195
DeviceID=CPU0
Family=179
L2CacheSize=24576
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2195
Name=Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz
ProcessorType=3
Revision=21767

Architecture=9
CurrentClockSpeed=2195
DeviceID=CPU1
Family=179
L2CacheSize=24576
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2195
Name=Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz
ProcessorType=3
Revision=21767

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.1+cu117
[pip3] torchaudio==2.0.2+cu117
[pip3] torchvision==0.15.2+cu117
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.0.1+cu117              pypi_0    pypi
[conda] torchaudio                2.0.2+cu117              pypi_0    pypi
[conda] torchvision               0.15.2+cu117             pypi_0    pypi

cc @mruberry @rgommers @zou3519

**Comment by Chillee** [comment]
Yeah this is expected behavior - vmap only works on PyTorch operators. The underlying mechanism is essentially intercepting each PyTorch operation and translating it to the "batched" version.

i.e. `vmap(torch.dot)(A, B)` => `torch.mm(A, B)`

For perhaps obvious reasons, we cannot do the same interception on arbitrary third-party code (including numpy arrays).

Depending on the use case, perhaps the numpy to torch translation layer could suffice? cc: @lezcano

**Comment by bensarthou** [comment]
Thanks all of you for the response ! 
I'm glad to see there is a workaround, unfortunately torch.compile seems unavailable on Windows at the moment (referencing #90768 ), I have the following error when trying your code
```
Traceback (most recent call last):
  File "[PYTHON SCRIPT]", line 35, in <module>
    def BatchVesselness_v(tensor):
  File "[ENV]\lib\site-packages\torch\__init__.py", line 1441, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
  File "[ENV]\lib\site-packages\torch\_dynamo\eval_frame.py", line 413, in optimize
    check_if_dynamo_supported()
  File "[ENV]\lib\site-packages\torch\_dynamo\eval_frame.py", line 375, in check_if_dynamo_supported
    raise RuntimeError("Windows not yet supported for torch.compile")
RuntimeError: Windows not yet supported for torch.compile
```
I've looked at several other related issues and there don't seem to have any solution while torch.compile isn't supported on Windows; I'll be sure to monitor the other issue and try this as soon as Windows support is added ! 

Thanks again for the quick response

**Comment by lezcano** [comment]
We can do a similar thing in eager mode using an internal API we have to implement the above (see below).
But note that this API *is internal and is not stable, so avoid using it in any production code*

```python
import torch
from torch.func import vmap

a = torch.randn((2,10))
b = torch.randn((2,20))

def np_convolve(x, y):
    import torch._numpy as np
    x, y = np.asarray(x), np.asarray(y)
    # Here could be some code only available on numpy array ...
    z = np.convolve(x, y)
    return z.tensor

def vmap_convolve(x, y):
    return vmap(np_convolve)(x,y)

def poormans_vmap(x, y):
    import numpy as np
    x, y = x.numpy(), y.numpy()
    result = [np.convolve(x1, y1) for x1, y1 in zip(x, y)]
    z = np.stack(result)
    return torch.from_numpy(z)

torch.testing.assert_close(vmap_convolve(a, b), poormans_vmap(a, b))
```

**Comment by lezcano** [comment]
for this to work you should use either the  nightly or wait for the release of 2.2

**Comment by lezcano** [comment]
Closing this issue as expected behaviour. We leave an alternative using `torch.compile` at https://github.com/pytorch/pytorch/issues/113751#issuecomment-1813213001

**Comment by harsanyidani** [comment]
> for this to work you should use either the nightly or wait for the release of 2.2

So in your example you were using nightly?

**Comment by lezcano** [comment]
compiled from source, but yeah, same thing

**Comment by harsanyidani** [comment]
Thanks!
