### ISSUE TITLE
Add option to turn off Caffe2 build

### ISSUE THREAD

**Issue by themightyoarfish** [pytorch/pytorch#11371]
It would be really helpful if all Caffe2 features could be disabled, since that would massively reduce compile time. There is a `FULL_CAFFE2` environment variable, but nothing changes if I set it to `0`.

**Comment by ngimel** [comment]
Closing, there are env variables to disable C2 build.

**Comment by benjha** [comment]
Hi @ngimel,

What's the env. variable to disable caffe2 build ?

Thanks

**Comment by mzimmerm** [comment]
@ngimel , @benjha I would also like to know how to disable caffe2 build. It is trying to build it even with both CAFFE2 related variables set to 0, and caffe2 is both taking a long time and then failing my builds. I do not know what to do except disabling it.
