### ISSUE TITLE
[export] Export warnings as no-ops

### ISSUE THREAD

**Issue by angelayi** [pytorch/pytorch#113792]
### 🐛 Describe the bug

```
import torch
import warnings

def f(x):
    warnings.warn("moo")
    return x + x

ep = torch.export.export(f, (torch.ones(1, 3),))
```

Results in:
```
Traceback (most recent call last):
  ...
  File "/data/users/angelayi/pytorch/torch/_dynamo/symbolic_convert.py", line 1209, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/angelayi/pytorch/torch/_dynamo/symbolic_convert.py", line 650, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/angelayi/pytorch/torch/_dynamo/variables/user_defined.py", line 394, in call_function
    return self.call_method(tx, "__call__", args, kwargs)
  File "/data/users/angelayi/pytorch/torch/_dynamo/variables/user_defined.py", line 306, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/data/users/angelayi/pytorch/torch/_dynamo/variables/base.py", line 317, in call_method
    raise unimplemented(f"call_method {self} {name} {args} {kwargs}")
  File "/data/users/angelayi/pytorch/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(warn) __call__ [ConstantVariable(str)] {}
```

Proposal is to trace this warning into a no-op.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @yanboliang 

### Versions

master

**Comment by yanboliang** [comment]
We don't have ATen level ops to represent loggings, so I think it's fine to wrap them as no-ops to avoid graph breaks. But I think we should print out a warning message to let users aware of this. cc @jansel @ezyang

**Comment by ezyang** [comment]
dupe of https://github.com/pytorch/pytorch/issues/93739

**Comment by yanboliang** [comment]
@ezyang I understand the pros and cons of wrapping them as no-ops or reorder them, do you think we can have a config (e.g., ```prints_warning_as_no_op=False```) for users to mitigate these graph breaks? This config can be False by default.

**Comment by ezyang** [comment]
I don't think it is too much work to fix this properly, let's decide what we want to do and just do it one go.

**Comment by angelayi** [comment]
@ezyang so is ok to decide that we will wrap these print/warning/log library functions as a no-op? For export cases we can just ignore these functions, and for torch.compile cases we reorder it to after the graph?

**Comment by anijain2305** [comment]
Any update on this?

**Comment by angelayi** [comment]
This is done!
