### ISSUE TITLE
[FSDP] Raise error when applying FSDP to `nn.ModuleList` or `nn.ModuleDict`

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#113794]
FSDP relies on `nn.Module.forward()` to all-gather and free parameters. If an `nn.ModuleList` or `nn.ModuleDict` is wrapped with FSDP, then it will not run its all-gather logic since `forward()` is not called. This leads to an annoying debugging experience to find that the parameters were not all-gathered. Since the current design does not support this, we should raise an error at construction time.

cc @zhaojuanmao @mrshenli @rohan-varma @fegin @penguinwu

**Comment by garrett361** [comment]
Is this still an issue? And do I understand correctly that it is only a problem if you organize your layers into `{ModuleList, ModuleDict}` containers _and_ you also want the FSDP units to be slices of these containers?

Not seeing an issue with wrapping entire `{ModuleList, ModuleDict}` containers inside a single FSDP unit, but would like to know if that's also the case, thank you!

**Comment by awgu** [comment]
This is still an issue. I am surprised that you are not seeing a problem with wrapping the entire `ModuleList` or entire `ModuleDict` for the reason mentioned in the original issue description.

I wonder how your parameters are getting all-gathered then 🤔

**Comment by awgu** [comment]
@garrett361 Is it possible that you are wrapping the entire `ModuleList` _but also_ wrapping each individual element in the `ModuleList`?

**Comment by garrett361** [comment]
Ah, I believe I misunderstood the original issue.  I thought you were saying there was an issue if `FSDP` wraps any module which has any `{ModuleList, ModuleDict}` submodules, but I now see that the problem is likely with directly wrapping a `{ModuleList, ModuleDict}` instance alone.

I wasn't seeing an issue with a wrapping policy like `ModuleWrapPolicy([Block])` where
```python
class Block(nn.Module):
    def __init__(self, ...):
        self.layers = nn.ModuleList([...])
        ....
```
But I believe I see correctly that `ModuleWrapPolicy([nn.ModuleList])` would be problematic. Correct?

**Comment by awgu** [comment]
@garrett361 Your understanding is correct! Since the `Block.forward()` runs, wrapping `Block` will all-gather (and free) the parameters correctly.

**Comment by awgu** [comment]
will close this since we added a warning (choosing not to error in case of BC issues)
