### ISSUE TITLE
RandomResizedCrop: error nll_loss2d_forward_kernel 

### ISSUE THREAD

**Issue by aenoca** [pytorch/pytorch#113704]
### 🐛 Describe the bug

I am running a semantic segmentation pipeline with torch. When I use the RandomResizedCrop transform I get the error 

/opt/conda/conda-bld/pytorch_1695392035891/work/aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [17,0,0], thread: [706,0,0] Assertion t >= 0 && t < n_classes failed.

saying that the error comes from

total_train_loss += loss.item()

The code I use 

utils.py
`import os
import torch
import torch.nn.functional as F
from PIL import Image
from torch.utils.data import DataLoader, random_split, Dataset
import torchvision.transforms.v2 as transforms
import matplotlib.pyplot as plt
import yaml

class SegmentationDataset(Dataset):
    def __init__(self, image_folder, label_folder, test=False):
        # self.root_dir = root_dir
        self.image_folder = image_folder
        self.label_folder = label_folder

        if test:
            self.common_transform = transforms.Compose([transforms.PILToTensor()])
        else:
            self.common_transform = transforms.Compose(
                [
                    transforms.RandomResizedCrop((518, 518), scale=(0.5, 2.0), ratio=(0.75, 1.3333333333333333)),
                    transforms.RandomHorizontalFlip(),
                ]
            )

        self.image_transform = transforms.Compose(
            [
                transforms.ToTensor(),
                # transforms.Normalize(
                #     mean=[127.5, 127.5, 127.5], std=[127.5, 127.5, 127.5]
                # ),
                transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
                # transforms.RandomApply([transforms.ColorJitter(brightness=0.5, contrast=0.5, saturation=0.5, hue=0.1)], p = 0.8),
            ]
        )

        self.label_transform = transforms.Compose([transforms.PILToTensor(), transforms.ToDtype(torch.long)])

        self.size = 252

        # List all image and label file paths
        self.image_paths = sorted(os.listdir(os.path.join(image_folder)))
        self.label_paths = sorted(os.listdir(os.path.join(label_folder)))

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image_name = os.path.join(
            self.image_folder, self.image_paths[idx]
        )
        label_name = os.path.join(
            self.label_folder, self.label_paths[idx]
        )

        image = Image.open(image_name).convert("RGB")
        label = Image.open(label_name)  # .convert("L")

        image, label = self.common_transform(image, label)
        
        # image = image.float()

        # label = label.squeeze(0).long()
        image = self.image_transform(image)
        label = self.label_transform(label).squeeze(0)
        # print(image.shape, label.shape)
        # print(image.dtype, label.dtype)
        # print(label.unique())

        # print(image.shape, label.shape)

        return image, label

def get_dataloaders(batch_size, train_im, train_lab, val_im, val_lab, test=False, num_workers=8):
    # image_folder_name = "images"
    # label_folder_name = "annotations"

    # train_root_folder = os.path.join(root_data_folder, "train")
    # val_root_folder = os.path.join(root_data_folder, "val")

    train_dataset = SegmentationDataset(
        train_im, train_lab
    )
    val_dataset = SegmentationDataset(
        val_im, val_lab, test=test
    )

    # Create data loaders for train and validation sets
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        pin_memory=True,
        num_workers=num_workers,
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        pin_memory=True,
        num_workers=num_workers,
    )

    return train_loader, val_loader

def deprecated_get_dataloaders(
    root_data_folder,
    image_folder_name,
    label_folder_name,
    batch_size,
    train_ratio=0.8,
    num_workers=8,
):
    dataset = SegmentationDataset(
        root_data_folder, image_folder_name, label_folder_name
    )

    # # Calculate the number of samples for train and validation split
    total_samples = len(dataset)
    train_size = int(train_ratio * total_samples)
    val_size = total_samples - train_size

    # Split the dataset into train and validation sets
    train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

    # Create data loaders for train and validation sets
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        pin_memory=True,
        num_workers=num_workers,
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        pin_memory=True,
        num_workers=num_workers,
    )

    return train_loader, val_loader

def compute_accuracy(
    num_classes,
    dataloader,
    model,
    device,
    miou=True,
    return_loss=False,
    criterion=None,
    rescale=1.0,
    augment=False
):
    model.eval()
    correct = 0
    total = 0
    loss = 0
    intersections = torch.zeros(num_classes)
    unions = torch.zeros(num_classes)
    IoUs = torch.zeros(num_classes)
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            labels = labels.to(device)
            outputs = model(inputs, augment=augment)
            # print(outputs.shape)
            _, predicted = torch.max(F.softmax(outputs, dim=1), dim=1)
            total += labels.shape[0] * labels.shape[1] * labels.shape[2]
            correct += (predicted == labels).sum().item()
            if return_loss:
                loss += criterion(outputs, labels).item()

            if miou:
                for class_ix in range(num_classes):
                    mask_pred = predicted == class_ix
                    mask_label = labels == class_ix

                    intersection = (mask_pred & mask_label).sum().item()
                    union = (mask_pred | mask_label).sum().item()

                    intersections[class_ix] += intersection
                    unions[class_ix] += union

        if miou:
            IoUs = intersections / unions * 100

    accuracy = 100 * correct / total

    returns = [accuracy]
    if return_loss:
        returns = returns + [loss / rescale]

    if miou:
        returns = returns + [IoUs.nanmean().item(), IoUs]

    return returns

def plot_results(output_path, results_json):

    # output a plot of training and validation accuracies, as well as training and validation losses

    plt.figure(figsize=(10, 10))
    plt.subplot(3, 1, 1)
    plt.plot(
        results_json["train"]["acc"].keys(),
        results_json["train"]["acc"].values(),
        label="Training Accuracy",
    )
    plt.plot(
        results_json["val"]["acc"].keys(),
        results_json["val"]["acc"].values(),
        label="Validation Accuracy",
    )
    plt.legend()
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy (%)")
    plt.title("Training and Validation Accuracies")

    plt.subplot(3, 1, 2)
    plt.plot(
        results_json["train"]["loss"].keys(),
        results_json["train"]["loss"].values(),
        label="Training Loss",
    )
    plt.plot(
        results_json["val"]["loss"].keys(),
        results_json["val"]["loss"].values(),
        label="Validation Loss",
    )
    plt.legend()
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Training and Validation Losses")

    plt.subplot(3, 1, 3)
    plt.plot(
        results_json["train"]["mIoU"].keys(),
        results_json["train"]["mIoU"].values(),
        label="Training mIoU",
    )
    plt.plot(
        results_json["val"]["mIoU"].keys(),
        results_json["val"]["mIoU"].values(),
        label="Validation mIoU",
    )
    plt.legend()
    plt.xlabel("Epoch")
    plt.ylabel("mIoU (%)")
    plt.title("Training and Validation mIoUs")
    plt.savefig(os.path.join(output_path, "acc_and_losses.png"))

def plot_IoUs(output_path, results_json):

    num_classes = len(results_json["train"]["IoUs"][1])
    plt.figure(figsize=(20, 30))

    for class_ix in range(num_classes):
        plt.subplot(6, 4, class_ix + 1)
        plt.plot(
            results_json["train"]["IoUs"].keys(),
            [x[class_ix] for x in results_json["train"]["IoUs"].values()],
            label="Training IoU",
        )
        plt.plot(
            results_json["val"]["IoUs"].keys(),
            [x[class_ix] for x in results_json["val"]["IoUs"].values()],
            label="Validation IoU",
        )
        plt.legend()
        plt.xlabel("Epoch")
        plt.ylabel("IoU (%)")
        plt.title("IoU for class {}".format(class_ix))

    plt.savefig(os.path.join(output_path, "IoUs.png"))

def plot_layers(output_path):
    # compare the accuracies and MIOUs of the different layers

    layer_name = "layer_"
    layers = 13

    mIoUs = []
    accs = []

    for layer in range(layers):
        results_json = yaml.load(
            open(
                os.path.join(
                    output_path, layer_name + "{:02d}".format(layer), "results.yaml"
                ),
                "r",
            ),
            Loader=yaml.FullLoader,
        )

        mIoU = results_json["val"]["mIoU"][25]
        acc = results_json["val"]["acc"][25]

        mIoUs.append(mIoU)
        accs.append(acc)

    plt.figure(figsize=(10, 10))
    plt.subplot(2, 1, 1)
    plt.plot(mIoUs)
    plt.xlabel("Layer")
    plt.ylabel("mIoU (%)")
    plt.title("mIoUs of the different layers")
    plt.grid()

    plt.subplot(2, 1, 2)
    plt.plot(accs)
    plt.xlabel("Layer")
    plt.ylabel("Accuracy (%)")
    plt.title("Accuracies of the different layers")
    plt.grid()
    plt.savefig(os.path.join(output_path, "accs_and_losses_across_layers.png"))

#
# python utils.py plot --output_path outputs/layer_08 --results_json outputs/layer_08/results.yaml
# python utils.py plot_layers --output_path outputs
# python utils.py plot_IoUs --output_path outputs/layer_08 --results_json outputs/layer_08/results.yaml

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "function",
        help="which function to execute",
        choices=["plot", "plot_layers", "plot_IoUs"],
    )
    parser.add_argument("--output_path", help="output path for the results")
    parser.add_argument(
        "--results_json", help="path to the results json file", default="results.yaml"
    )

    args = parser.parse_args()

    if args.function == "plot":
        results_json = yaml.load(open(args.results_json, "r"), Loader=yaml.FullLoader)
        plot_results(args.output_path, results_json)
    elif args.function == "plot_layers":
        plot_layers(args.output_path)
    elif args.function == "plot_IoUs":
        results_json = yaml.load(open(args.results_json, "r"), Loader=yaml.FullLoader)
        plot_IoUs(args.output_path, results_json)
`

train.py
`import torch
from utils import get_dataloaders, compute_accuracy
from model import DinoV2FullStack
import torch.nn.functional as F
import os
import yaml
from tqdm import tqdm
import wandb

from configs.equal_real_sim import *

# Define the device
device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")

# Get the dataloaders
train_loader, val_loader = get_dataloaders(batch_size, train_im=train_im, train_lab=train_lab, val_im=val_im, val_lab=val_lab, test=False, num_workers=num_workers)

_, test_loader = get_dataloaders(batch_size, train_im=train_im, train_lab=train_lab, val_im=val_im, val_lab=val_lab, test=True, num_workers=num_workers)

# layers = range(0, 13)
layers = [-1]

hyperparameters = {"num classes": num_classes, "batch size": batch_size, "learning rate": lr, "num epochs": num_epochs, "train frequency": train_frequency, "val frequency": val_frequency, "weights": weights, "config": config} 

wandb.init(project="probing-vision-transformers", name = run_name, config=hyperparameters)

for layer in tqdm(layers, desc="Layer"):
    run_name = "layer_{:02d}".format(layer)
    output_path = os.path.join(output_folder, run_name)
    os.makedirs(output_path, exist_ok=True)

    # Get model
    config["layer_output"] = layer
    model = DinoV2FullStack(config)

    # Move the model to the device
    model.to(device)
    
    weights = torch.tensor(weights, device=device)
    criterion = torch.nn.CrossEntropyLoss(weight=weights, ignore_index=255)

    # Define the optimizer
    # optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=0.9, weight_decay=0.0005)
    scheduler = torch.optim.lr_scheduler.PolynomialLR(optimizer, 20, power=0.9, )

    # Train the model
    results_json = {
        "train": {"acc": {}, "loss": {}, "mIoU": {}, "IoUs": {}},
        "val": {"acc": {}, "loss": {}, "mIoU": {}, "IoUs": {}},
        "test": {"acc": 0, "mIoU": 0, "IoUs": []},
    }

    results_file = "results.json"

    for epoch in tqdm(range(num_epochs), desc="Epoch"):
        # Train
        model.train()
        total_train_loss = 0
        for i, (inputs, labels) in tqdm(
            enumerate(train_loader), desc="Batch", leave=False
        ):
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            total_train_loss += lossitem()

        scheduler.step()

        results_json["train"]["loss"][epoch + 1] = total_train_loss

        if epoch % train_frequency == 0:
            accuracy, mIoU, IoUs = compute_accuracy(
                config["output_dim"],
                train_loader,
                model,
                device,
                rescale=0.8,
                miou=True,
            )
            results_json["train"]["acc"][epoch + 1] = accuracy
            results_json["train"]["mIoU"][epoch + 1] = mIoU
            results_json["train"]["IoUs"][epoch + 1] = IoUs.cpu().numpy().tolist()
            wandb.log({"train accuracy": accuracy, "train mIoU": mIoU, "train loss": total_train_loss})

        # Evaluate
        if epoch % val_frequency == 0:
            accuracy, loss3, mIoU, IoUs = compute_accuracy(
                config["output_dim"],
                val_loader,
                model,
                device,
                miou=True,
                return_loss=True,
                criterion=criterion,
                rescale=0.2,
            )

            results_json["val"]["acc"][epoch + 1] = accuracy
            results_json["val"]["loss"][epoch + 1] = loss3
            results_json["val"]["mIoU"][epoch + 1] = mIoU
            results_json["val"]["IoUs"][epoch + 1] = IoUs.cpu().numpy().tolist()
            wandb.log({"val accuracy": accuracy, "val mIoU": mIoU, "val loss": loss3})

        wandb.log({"epoch": epoch})

        # save the progress results to a yaml file
        with open(os.path.join(output_path, "results.yaml"), "w") as f:
            yaml.dump(results_json, f)

    # Save the model
    torch.save(model.state_dict(), os.path.join(output_path, "model.pt"))
`

### Versions

Collecting environment information...
PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              1
Core(s) per socket:              24
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           183
Model name:                      13th Gen Intel(R) Core(TM) i9-13900K
Stepping:                        1
CPU MHz:                         3000.000
CPU max MHz:                     5800.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5990.40
Virtualization:                  VT-x
L1d cache:                       576 KiB
L1i cache:                       384 KiB
L2 cache:                        24 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] torch==2.1.0
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h213fc3f_46343  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.8           py311h5eee18b_0  
[conda] mkl_random                1.2.4           py311hdb19cb5_0  
[conda] numpy                     1.26.0          py311h08b1b3b_0  
[conda] numpy-base                1.26.0          py311hf175353_0  
[conda] pytorch                   2.1.0           py3.11_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchtriton               2.1.0                     py311    pytorch
[conda] torchvision               0.16.0                   pypi_0    pypi

cc @ptrblck

**Comment by janeyx99** [comment]
Hello, could you condense this into a smaller reproduction to drill down into the problem?

**Comment by aenoca** [comment]
Actually, I just figured out what was going wrong. By default, the Resize (and RandomResizedCrop) utilize bilinear interpolation, which modified the (integer) labels in a irreversible way. Specifying the NEAREST interpolation method solved this.
