### ISSUE TITLE
Unsupported builtin operators for torch.export.export

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#113778]
### 🐛 Describe the bug

Several built-in operators commonly supported and leveraged by ONNX is not supported by ` torch.export.export`

The repro:
```python
import math
import operator
import torch


def func(x, y):
    # TODO: add boolean tests when SymBool is supported
    # to infer types
    return (
        torch.tensor([operator.add(x.item(), y.item())]),
        torch.tensor([operator.sub(x.item(), y.item())]),
        torch.tensor([operator.mul(x.item(), y.item())]),
        torch.tensor([operator.truediv(x.item(), y.item())]),
        torch.tensor([operator.floordiv(x.item(), y.item())]),
        torch.tensor([operator.pow(x.item(), y.item())]),
        torch.tensor([operator.abs(x.item())]),
        torch.tensor([operator.neg(x.item())]),
        torch.tensor([math.ceil(x.item())]),
        torch.tensor([math.floor(x.item())]),
    )

x = torch.randn(1, dtype=torch.float32)
y = torch.randn(1, dtype=torch.float32)

ep = torch.export.export(func, args=(x, y))
print(ep.graph_module.print_readable())
```

The error:
```bash
[2023-11-15 17:46:10,377] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/opt/onnxruntime/build/Linux/RelWithDebInfo/onnxruntime/capi/onnxruntime_validation.py:114: UserWarning: WARNING: failed to get cudart_version from onnxruntime build info.
  warnings.warn("WARNING: failed to get cudart_version from onnxruntime build info.")
Traceback (most recent call last):
  File "/opt/pytorch/test_builtin.py", line 25, in <module>
    ep = torch.export.export(func, args=(x, y))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/export/__init__.py", line 449, in export
    return export__RC__(
           ^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_export/__init__.py", line 257, in export__RC__
    return _export(
           ^^^^^^^^
  File "/opt/pytorch/torch/_export/__init__.py", line 801, in _export
    exported_program = ExportedProgram(
                       ^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/export/exported_program.py", line 126, in __init__
    self.verifier().check(self)
  File "/opt/pytorch/torch/_export/verifier.py", line 121, in check
    self._check_graph_module(ep.graph_module)
  File "/opt/pytorch/torch/_export/verifier.py", line 179, in _check_graph_module
    _check_valid_op(node.target)
  File "/opt/pytorch/torch/_export/verifier.py", line 151, in _check_valid_op
    raise SpecViolationError(
torch._export.verifier.SpecViolationError: Operator '<built-in function pow>' is not an allowed operator type: (<class 'torch._ops.OpOverload'>, <class 'torch._ops.HigherOrderOperator'>)
Valid builtin ops: [<built-in function getitem>, <built-in function add>, <built-in function mul>, <built-in function sub>, <built-in function truediv>, <built-in function ge>, <built-in function le>, <built-in function gt>, <built-in function lt>, <built-in function eq>, <built-in function ne>, <built-in function floordiv>, <built-in function mod>, <built-in function and_>, <built-in function or_>, <built-in function not_>]
```

### Versions

main

cc @ezyang @gchanan @zou3519 @kadeng @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by zhxchen17** [comment]
should be fixed by #113982

**Comment by titaiwangms** [comment]
https://hud.pytorch.org/pr/114762

```
2023-11-29T16:27:56.4907052Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/fx/interpreter.py", line 195, in run_node
2023-11-29T16:27:56.4907250Z     return getattr(self, n.op)(n.target, args, kwargs)
2023-11-29T16:27:56.4907881Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_export/pass_base.py", line 208, in call_function
2023-11-29T16:27:56.4908166Z     raise ExportPassBaseError(f"Unsupported target type: {target}")
2023-11-29T16:27:56.4908674Z torch._export.pass_base.ExportPassBaseError: Unsupported target type: <built-in function ceil>
2023-11-29T16:27:56.4908681Z 
2023-11-29T16:27:56.4909205Z While executing %ceil : [num_users=1] = call_function[target=math.ceil](args = (%_local_scalar_dense_14,), kwargs = {})
2023-11-29T16:27:56.4909323Z Original traceback:
2023-11-29T16:27:56.4909587Z   File "onnx/test_fx_to_onnx_with_onnxruntime.py", line 155, in func
2023-11-29T16:27:56.4909740Z     torch.tensor([math.ceil(x.item())]),
```

**Comment by zhxchen17** [comment]
> https://hud.pytorch.org/pr/114762
> 
> ```
> 2023-11-29T16:27:56.4907052Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/fx/interpreter.py", line 195, in run_node
> 2023-11-29T16:27:56.4907250Z     return getattr(self, n.op)(n.target, args, kwargs)
> 2023-11-29T16:27:56.4907881Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_export/pass_base.py", line 208, in call_function
> 2023-11-29T16:27:56.4908166Z     raise ExportPassBaseError(f"Unsupported target type: {target}")
> 2023-11-29T16:27:56.4908674Z torch._export.pass_base.ExportPassBaseError: Unsupported target type: <built-in function ceil>
> 2023-11-29T16:27:56.4908681Z 
> 2023-11-29T16:27:56.4909205Z While executing %ceil : [num_users=1] = call_function[target=math.ceil](args = (%_local_scalar_dense_14,), kwargs = {})
> 2023-11-29T16:27:56.4909323Z Original traceback:
> 2023-11-29T16:27:56.4909587Z   File "onnx/test_fx_to_onnx_with_onnxruntime.py", line 155, in func
> 2023-11-29T16:27:56.4909740Z     torch.tensor([math.ceil(x.item())]),
> ```

This seems a similar but separate issue from the OP. @titaiwangms mind sharing the repro here?

**Comment by thiagocrepaldi** [comment]
> > https://hud.pytorch.org/pr/114762
> > ```
> > 2023-11-29T16:27:56.4907052Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/fx/interpreter.py", line 195, in run_node
> > 2023-11-29T16:27:56.4907250Z     return getattr(self, n.op)(n.target, args, kwargs)
> > 2023-11-29T16:27:56.4907881Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_export/pass_base.py", line 208, in call_function
> > 2023-11-29T16:27:56.4908166Z     raise ExportPassBaseError(f"Unsupported target type: {target}")
> > 2023-11-29T16:27:56.4908674Z torch._export.pass_base.ExportPassBaseError: Unsupported target type: <built-in function ceil>
> > 2023-11-29T16:27:56.4908681Z 
> > 2023-11-29T16:27:56.4909205Z While executing %ceil : [num_users=1] = call_function[target=math.ceil](args = (%_local_scalar_dense_14,), kwargs = {})
> > 2023-11-29T16:27:56.4909323Z Original traceback:
> > 2023-11-29T16:27:56.4909587Z   File "onnx/test_fx_to_onnx_with_onnxruntime.py", line 155, in func
> > 2023-11-29T16:27:56.4909740Z     torch.tensor([math.ceil(x.item())]),
> > ```
> 
> This seems a similar but separate issue from the OP. @titaiwangms mind sharing the repro here?

https://github.com/pytorch/pytorch/blob/main/test/onnx/test_fx_to_onnx_with_onnxruntime.py#L152-L177

**Comment by thiagocrepaldi** [comment]
This was fixed on main
