### ISSUE TITLE
[cusparseLt] CUDA error: internal error when calling `cusparseLtStructuredDescriptorInit`

### ISSUE THREAD

**Issue by danthe3rd** [pytorch/pytorch#113776]
### 🐛 Describe the bug

When calling into cuSparseLt function from different threads, we can get this error. Notably this happens in the BW pass.
I have a small repro code - if the BW pass runs on the main thread, the error does not show up.

Repro code:
```python
import torch
b, ft = 1024, 1024
class Linear(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x: torch.Tensor, W: torch.Tensor, B: torch.Tensor):  # type: ignore[override]
        print(f"fw")
        ctx.wcsplt = torch.ops.aten._cslt_compress(W)
        ctx.wcspltT = torch.ops.aten._cslt_compress(W.t().contiguous())
        ctx.save_for_backward(x)
        return torch.ops.aten._cslt_sparse_mm(ctx.wcsplt, dense_B=x.t(), bias=B, transpose_result=True)
    @staticmethod
    def backward(ctx, grad_out: torch.Tensor):  # type: ignore[override]
        print("bw")
        x = ctx.saved_tensors[0]
        return (
            # dx
            torch.ops.aten._cslt_sparse_mm(ctx.wcsplt, grad_out.t(), transpose_result=True),
            # dw
            x.t() @ grad_out,
            # db
            None
        )
x = torch.randn([b, ft], device="cuda", dtype=torch.float16, requires_grad=True)
W = torch.randn([ft, ft], device="cuda", dtype=torch.float16, requires_grad=True)
B = torch.randn([ft], device="cuda", dtype=torch.float16, requires_grad=True)
class Ctx:
    def save_for_backward(self, *x):
        self.saved_tensors = x
print("running bw on same thread")
ctx = Ctx()
out = Linear.forward(ctx, x, W, B)
assert out.shape == (b, ft)
Linear.backward(ctx, out)
print("running bw on different thread")
out = Linear.apply(x, W, B)
out.backward(out)
```

This error goes away if we make those 2 variables `thread_local`:
https://github.com/pytorch/pytorch/blob/50101d59bacaf28fe5db1d84d09d7ff7c774c5ff/aten/src/ATen/native/sparse/cuda/cuSPARSELtOps.cpp#L21-L22

But I'm not sure if it's the right solution.

### Versions

```
Collecting environment information...
PyTorch version: 2.2.0.dev20231112+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.27.5
Libc version: glibc-2.31

Python version: 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1045-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.2.91
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             96
On-line CPU(s) list:                0-95
Thread(s) per core:                 2
Core(s) per socket:                 24
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                           7
CPU MHz:                            3000.006
BogoMIPS:                           6000.01
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          1.5 MiB
L1i cache:                          1.5 MiB
L2 cache:                           48 MiB
L3 cache:                           71.5 MiB
NUMA node0 CPU(s):                  0-23,48-71
NUMA node1 CPU(s):                  24-47,72-95
Vulnerability Gather data sampling: Unknown: Dependent on hypervisor status
Vulnerability Itlb multihit:        KVM: Mitigation: VMX unsupported
Vulnerability L1tf:                 Mitigation; PTE Inversion
Vulnerability Mds:                  Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:             Mitigation; PTI
Vulnerability Mmio stale data:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec store bypass:    Vulnerable
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] mypy==1.7.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.2
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.2.0.dev20231112+cu121
[pip3] torchaudio==2.2.0.dev20231112+cu121
[pip3] torchvision==0.17.0.dev20231112+cu121
[pip3] triton-nightly==2.1.0.dev20231014192330
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+6e4932cda8          pypi_0    pypi
[conda] torch                     2.2.0.dev20231112+cu121          pypi_0    pypi
[conda] torchaudio                2.2.0.dev20231112+cu121          pypi_0    pypi
[conda] torchvision               0.17.0.dev20231112+cu121          pypi_0    pypi
[conda] triton-nightly            2.1.0.dev20231014192330          pypi_0    pypi
```

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @ptrblck

**Comment by eqy** [comment]
I just asked the cuSparse team and they said that each thread should have its own handle, so it seems that your fix is correct.

**Comment by jcaip** [comment]
thread_local is definitely the right fix here

but @danthe3rd I can't seem to reproduce this on my machine. Just double checking, what error do you see when you run your repro example?

When I run your code I see this, with no errors:
```
running bw on same thread
fw
bw
running bw on different thread
fw
bw
```

**Comment by danthe3rd** [comment]
@jcaip I get this error:
```
running bw on same thread
fw
bw
running bw on different thread
fw
bw
Traceback (most recent call last):
  File "/fsx-xformers/user/xformers/r.py", line 36, in <module>
    out.backward(out)
  File "/opt/dlami/nvme/slurm_tmpdir/3742406/env/lib/python3.10/site-packages/torch/_tensor.py", line 503, in backward
    torch.autograd.backward(
  File "/opt/dlami/nvme/slurm_tmpdir/3742406/env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/dlami/nvme/slurm_tmpdir/3742406/env/lib/python3.10/site-packages/torch/autograd/function.py", line 289, in apply
    return user_fn(self, *args)
  File "/fsx-xformers/user/xformers/r.py", line 17, in backward
    torch.ops.aten._cslt_sparse_mm(ctx.wcsplt, grad_out.t(), transpose_result=True),
  File "/opt/dlami/nvme/slurm_tmpdir/3742406/env/lib/python3.10/site-packages/torch/_ops.py", line 753, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: internal error when calling `cusparseLtStructuredDescriptorInit( &handle, &sparse_input_descriptor, m, k, k, 16, input_type, CUSPARSE_ORDER_ROW, CUSPARSELT_SPARSITY_50_PERCENT)`
```

**Comment by RanchiZhao** [comment]
is  this code demo available on rtx4090? I found that:
```
running bw on same thread
fw
Traceback (most recent call last):
  File "/home/zyq/test_1204.py", line 31, in <module>
    out = Linear.forward(ctx, x, W, B)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zyq/test_1204.py", line 7, in forward
    ctx.wcsplt = torch.ops.aten._cslt_compress(W)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zyq/anaconda3/envs/cu120/lib/python3.11/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cuSPARSELT not supported on your machine.
```

**Comment by silence1024** [comment]
> is this code demo available on rtx4090? I found that:
> 
> ```
> running bw on same thread
> fw
> Traceback (most recent call last):
>   File "/home/zyq/test_1204.py", line 31, in <module>
>     out = Linear.forward(ctx, x, W, B)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zyq/test_1204.py", line 7, in forward
>     ctx.wcsplt = torch.ops.aten._cslt_compress(W)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zyq/anaconda3/envs/cu120/lib/python3.11/site-packages/torch/_ops.py", line 692, in __call__
>     return self._op(*args, **kwargs or {})
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: cuSPARSELT not supported on your machine.
> ```

I also have this issue.
When I was running:
>>> import torch
>>> from torch.sparse import to_sparse_semi_structured
>>> A = torch.Tensor([0, 0, 1, 1]).tile((128, 32)).half().cuda()
>>> A_sparse = to_sparse_semi_structured(A)

/opt/anaconda3/envs/sm_sparse/lib/python3.8/site-packages/torch/sparse/semi_structured.py:86: UserWarning: The PyTorch API of SparseSemiStructuredTensor is in prototype stage and will change in the near future. Please open a Github issue for features requests and see our documentation on the torch.sparse module for further information about the project.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/sm_sparse/lib/python3.8/site-packages/torch/sparse/semi_structured.py", line 434, in to_sparse_semi_structured
    return SparseSemiStructuredTensor(original_tensor, original_shape=original_tensor.shape, transposed=transposed)
  File "/opt/anaconda3/envs/sm_sparse/lib/python3.8/site-packages/torch/sparse/semi_structured.py", line 212, in __init__
    compressed_tensor = torch._cslt_compress(original_tensor)
RuntimeError: cuSPARSELT not supported on your machine.

GPU: 4 NVIDIA A100 80GB PCIe
Relevant Library version:
- cuda: 12.1
- python: 3.8.18
- torch 2.1.1 
- cuSPARSELt: 0.5.0

**Comment by RanchiZhao** [comment]
> @RanchiZhao what version of pytorch are you using? This is a different error, which occurs when pytorch is not compiled with cusparselt. You need to either compile pytorch from source following the instructions [here](https://github.com/pytorch/pytorch/issues/110168) or to use the pytorch nightlies instead你使用什么版本的pytorch？这是一个不同的错误，当 pytorch 不是使用 cusparselt 编译时会发生。您需要按照此处的说明从源代码编译 pytorch 或使用 pytorch nightlies
> 
> ```
> pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
> ```

that is cool, i will try this

**Comment by RanchiZhao** [comment]
Hi there, to use cusparseLt 0.5.0 in PyTorch, are the following requirements very needed?

1. CUDA version 12.1 or later.
2. using the command:` pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121`.

Also, are there any specific tutorials or guides available for getting started with cusparseLt 0.5.0 in PyTorch?

**Comment by RanchiZhao** [comment]
in the https://docs.nvidia.com/cuda/cusparselt/getting_started.html
i find that:
[CUDA 12.0 toolkit (or above)](https://developer.nvidia.com/cuda-downloads) is needed, however, when i do
`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118`
and run your code demo, it works.
so maybe what i am using is not the cusparseLt 0.5.0?

**Comment by jcaip** [comment]
@RanchiZhao Let's consolidate this conversation over in #115077 (or open a new issue) as that is more in line with the issue you are facing. For a tutorial on using semi-structured sparsity please see: https://pytorch.org/tutorials/prototype/semi_structured_sparse.html

You should not have to deal with the private aten ops _cslt_compress and _cslt_sparse_mm directly, but use the tensor subclass mentioned in the tutorial, which supports both CUTLASS and cuSPASRELt backends.
