### ISSUE TITLE
lintrunner init stoppedd working with Python 3.8

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#113864]
### 🐛 Describe the bug

Python 3.8 is still supported as per the README, but `lintrunner init` stopped working. It fails with a
```
ERROR: Ignored the following versions that require a different python version: 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 1.26.0rc1 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python <3.13,>=3.9; 1.26.2 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement numpy==1.26.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0rc1, 1.23.0rc2, 1.23.0rc3, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0rc1, 1.24.0rc2, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4)
ERROR: No matching distribution found for numpy==1.26.0
```

This seems to be caused by https://github.com/pytorch/pytorch/pull/113562. cc @albanD @malfet 

### Versions

master

**Comment by albanD** [comment]
Ho thanks for the report.
That is very unfortunate as there is no version of numpy that is support by both 3.8 and 3.12. So we have to give up one of these configs from the linter point of view.

To be as forward facing as possible I would suggest dropping 3.8.
But if people have a strong opinion about keep 3.8 longer and disabling linter on 3.12 that can also work.

**Comment by albanD** [comment]
But that removes most of the benefit of lintrunner as differently pinned version might lint differently.
I would argue that we should just drop 3.8 since it's going to be removed in a couple month anyways.
Adding this as a topic for triage discussion.

**Comment by malfet** [comment]
> But that removes most of the benefit of lintrunner as differently pinned version might lint differently.
There is a small risk of that, but in theory as we do not use advanced features of numpy 1.24 and 1.26 should not affect the lint results (except for the bug you've discovered and reported)
> I would argue that we should just drop 3.8 since it's going to be removed in a couple month anyways.

According to https://endoflife.date/python there is almost a year of support

**Comment by albanD** [comment]
But according to https://github.com/pytorch/pytorch/blob/main/RELEASE.md#python we could have dropped it in April 2023

**Comment by lezcano** [comment]
Note that there is also this issue with NumPy and lintrunner at the moment which makes working on `torch.compie(numpy)` quite annoying: https://github.com/pytorch/pytorch/issues/113863
