### ISSUE TITLE
Minor typo in `torch.jit._script.py`

### ISSUE THREAD

**Issue by ichxorya** [pytorch/pytorch#113866]
[Link](https://github.com/pytorch/pytorch/blob/f9bf104c641adb64e079ac29695a75c37212236b/torch/jit/_script.py#L747)
```
See :func:`torch.jit.save <torch.jit.save>` witch accepts a file-like object.
```
`witch` should be changed to `which`.

**Comment by ichxorya** [comment]
That should fix the problem. But should I just close this issue on my own, or should I wait for the devs?

**Comment by janeyx99** [comment]
The PR can link to this issue so that when the PR is merged and closed, this issue will auto-close.
