### ISSUE TITLE
DDPOptimizer and Inductor output stride mismatch issue

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#113812]
### 🐛 Describe the bug

When `torch._inductor.config.keep_output_stride=True` (default value), we do preserve the strides of end-user-visible Dynamo graph output.

However, DDPOptimizer then splits the Dynamo graph into smaller subgraphs, and calls Inductor compile on each of the subgraphs. DDPOptimizer's design expects the ‘output’ of those smaller subgraphs to have their strides be preserved as well, but Inductor doesn't have a contract to preserve them, hence causing stride mismatch error e.g. in https://github.com/pytorch/pytorch/issues/113740, https://github.com/pytorch/pytorch/issues/107362 and also OSS dist benchmarks.

One solution (suggested by Elias) is to let DDPOptimizer not do graph-splitting and compilation until during the first execution with real tensors, so that we can guarantee that the actual strides produced by Inductor-compiled subgraph output is propagated downstream.

We should also have a unit test that repros the issue and verify that this solution fixes it.

Related issue: https://github.com/pytorch/pytorch/issues/107362#issuecomment-1684434426

cc. @wconstab @eellison 

### Versions

-

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by yf225** [comment]
I just found that this issue is first reported by @shunting314 : https://github.com/pytorch/pytorch/issues/102591, we should use his example to repro.

**Comment by jon-chuang** [comment]
> Inductor doesn't have a contract to preserve them,

I don't understand why not. Why can't we force `torch._inductor.config.keep_output_stride=True` to be True when compiling the subgraphs? Could you give a more illustrative example that demonstrates the problem, or a repro with some informative output graphs?

**Comment by eellison** [comment]
@jon-chuang adding extra stride constraints to intermediaries is a pessimizaiton because it interferes with inductor's own layout optimizations and could incur extra copies. we would like to avoid it if possible

**Comment by ezyang** [comment]
I mean, I think it's a good stopgap for this bug if we can't actually fix DDPoptimizer to handle this case

**Comment by jon-chuang** [comment]
I also don't understand, since the backend compiler is called sequentially, why inductor cannot simply propagate the strides information using FakeTensors

In other words, why should there be a strides mismatch between the FakeTensors and real tensors?

**Comment by jon-chuang** [comment]
In other words, if Inductor intends to change the output strides information, we ought to be able to track/guard on this somehow, and propagate this information to FakeTensor. Else, how can we even compile a graph with graph breaks sequentially using inductor?

**Comment by jon-chuang** [comment]
In other words, from what I gather, allowing inductor to output strides in real tensor that does not match fake tensor means that we _cause unnecessary recompilation on graph breaks_.

It just seems to be a lot simpler for inductor to just tell Dynamo that the FakeTensors' strides need to be updated. Meaning to say, a backend compiler can request to modify the output FakeTensors' metas directly.

**Comment by jon-chuang** [comment]
Another thing that worries me is - if backend can modify output strides, then won't AOTAutograd's backward also be affected? But I guess it also guards on output strides.

**Comment by jon-chuang** [comment]
Anyway, there you have your solution. If you really want to have strides information from execution with real tensors, just transform each subgraph into a dynamo code object, and guard on each of them.

**Comment by jon-chuang** [comment]
Here is my plan for how to do it:
1. Instead of running backend compiler if there are graph splits, DDPOptimizer will simply return the pure-python graph module, with inserted graph breaks
2. We will _not_ mark the resultant GraphModule with `disable`. This allows it to be retraced. We will _also_ mark the resultant graph modules with `___ddp_split_module` attribute. This means that when the `DDPOptimizer.compile_fn` sees this graph module, it will not try to bucket it futher.

**Comment by jon-chuang** [comment]
As for whether this will have bad interaction with https://github.com/pytorch/pytorch/pull/113374, my gut feel is that they are orthogonal.

**Comment by jon-chuang** [comment]
> Here is my plan for how to do it:

The problem with this strategy is that currently, it is not possible for Dynamo to directly trace through an `fx.GraphModule`

**Comment by jon-chuang** [comment]
The way we can get around this is to have an "express path" config that when dynamo encounters an `fx.GraphModule`, it will directly call the backend compiler on it, and guard only on the input metas and ambient state.

More generally, I see this as a compatibility issue - converting to and from python land and `fx.GraphModule` land, which I think is nice to fix partially.

**Comment by ezyang** [comment]
I'm not sure what you're concretely proposing here. My meta heuristic here is, since we're getting rid of DDPOptimizer, I only want short fixes.

**Comment by jon-chuang** [comment]
Yes, I think I'm abandoning tracing fx.GraphModule. It seems possible to have an easy fix which is to return a `GraphModule` that lazily calls the backend compiler as each submodule is evaluated.

**Comment by jon-chuang** [comment]
The problem with lazily calling the compiler is that it is hard to guarantee that the lazy compilation can take place under the exact same conditions under which the original compilation would have taken place.

**Comment by wconstab** [comment]
> The problem with lazily calling the compiler is that it is hard to guarantee that the lazy compilation can take place under the exact same conditions under which the original compilation would have taken place.

actually, do we care?  IMO it was a subtly inconsistent thing that we previously did an eager compilation for DDP submodules when other programs without DDP would have lazily compiled.

but apart from the theoretical concern of making the compilation happen a bit later (when admittedly the world may have changed relative to the previous point)- are there specific things you'd worry about?

**Comment by jon-chuang** [comment]
> but apart from the theoretical concern of making the compilation happen a bit later (when admittedly the world may have changed relative to the previous point)- are there specific things you'd worry about?

It's just a theoretical concern at this point. Generally, it's better to have stronger guarantees about compile consistency (see e.g. https://github.com/pytorch/pytorch/issues/110682).

To my understanding, backend config _ought_ to already be stored directly inside of the `compiler_fn`. But I'm just hinting that we need to be cautious here.

But you're right in saying that lazily compiling the splits does make the compile conditions _more similar_ to if it were compiled normally by dynamo, not less.
