### ISSUE TITLE
PyTorch breaks with gcc in same environment (anaconda)

### ISSUE THREAD

**Issue by mdevl** [pytorch/pytorch#11383]
## Issue description

I have PyTorch in a virtual anaconda environment (Python 3.6) and want to install a different python package (fenics) that brings along gcc version 4.8.5. This breaks Pytorch, and any attempt to import torch henceforth in Python yields

`import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/opt/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
ImportError: /home/user/opt/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/../../../../libgomp.so.1: version GOMP_4.0 not found (required by /home/user/opt/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libcaffe2.so)`

Similarly, if I create a new environment and install first gcc=4.8.5 and subsequently PyTorch, I will get the same import error. I.e., **PyTorch breaks due to different gcc version in the same virtual environment.**

The issue seems to be libgomp.so.1 and libstdc++.so.6 in the virtual environment - if I manually replace them with the original files from PyTorch, the issue disappears. But it breaks the other package (fenics) that depends on gcc=4.8.5

How does one solve this issue? Can I tell PyTorch to use different libraries? I'd highly appreciate any help on this matter. Thanks!

I've attached a strace on the import command, in case that is relevant.
[strace.txt](https://github.com/pytorch/pytorch/files/2361788/strace.txt)

## Code

% Install pytorch - works!
conda create -n pytorch python=3.6
source activate pytorch
conda install pytorch torchvision -c pytorch
% Install gcc - breaks PyTorch
conda install gcc=4.8.5
% Alternatively, install fenics - brings along gcc 4.8.5-7
conda install -c conda-forge fenics
% breaks as well

## System Info
Ubuntu 16.04 (same result on Ubuntu 18.04 in VM)
Default (system) compiler: GCC 5.4.0
collect_env.py script fails, obviously

**Comment by ngimel** [comment]
closing due to age
