### ISSUE TITLE
cannot backprop a cnn when intermediate output has size larger than 2**31

### ISSUE THREAD

**Issue by h3jia** [pytorch/pytorch#113833]
### 🐛 Describe the bug

This might be related to a few previous issues like #43476, #51871. I find that when my modified ResNet has the size of any of its intermediate layers to be larger than 2**31 (max value of int32), which can happen if you have 100 batch size, 200 channels, 512*512 images, it may raise an error when you try to backprop your loss.

See below for a minimal example to reproduce the issue, although you may want to run it on a large memory GPU, otherwise you'll first get the GPU out of memory error before this int32 error.

I checked that with 80GB A100 the GPU memory is not the real issue; the restriction of int32 unnecessarily limits the application of CNN to high resolution images. Please consider use int64 instead; I suppose it just needs a switch of data type that will not deteriorate the performance.

```python
import numpy as np
import torch
import torch.nn as nn

x = torch.rand(100, 50, 512, 512).cuda()
c = nn.Conv2d(50, 200, kernel_size=1).cuda()
r = nn.ReLU().cuda()

loss = torch.sum(r(c(x)))
print(loss)
loss.backward() # this is fine though

loss = torch.prod(r(c(x)))
print(loss)
loss.backward() # this line gives you the error
```

The last line leads to the following error,

```
>>> loss.backward()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: nonzero is not supported for tensors with more than INT_MAX elements,   file a support request
```

FYI, below is the actual error message I got from a real world example, which I believe has the same origin as the minimal toy example above.

```
Traceback (most recent call last):
  File "/home/hejia/lss-dev/00-wl/04/01-train-0-10k.py", line 266, in <module>
    foo = nqe.train_1d(qnet[i_dim], device='cuda', train_loader=train_loader, valid_loader=valid_loader,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hejia/nqe/nqe/train.py", line 283, in train_1d
    loss_now.backward()
  File "/home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: integer out of range
```

### Versions

(hejia@della-5) [hejia@della-l07g3 ~]$ python collect_env.py 
Collecting environment information...
PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Springdale Linux release 8.8 (Modena) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.28

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-477.27.1.el8_8.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB
Nvidia driver version: 535.104.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
OS: Springdale Linux release 8.8 (Modena) (x86_64)
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              48
On-line CPU(s) list: 0-47
Thread(s) per core:  1
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               1
Model name:          AMD EPYC 7413 24-Core Processor
Stepping:            1
CPU MHz:             2650.000
CPU max MHz:         3630.8101
CPU min MHz:         1500.0000
BogoMIPS:            5290.31
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-23
NUMA node1 CPU(s):   24-47
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpui
d extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw 
ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx 
smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin brs arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean 
flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca
Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] torch==2.1.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.16.1
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.8           py311h5eee18b_0  
[conda] mkl_random                1.2.4           py311hdb19cb5_0  
[conda] numpy                     1.26.0          py311h08b1b3b_0  
[conda] numpy-base                1.26.0          py311hf175353_0  
[conda] pytorch                   2.1.1           py3.11_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchtriton               2.1.0                     py311    pytorch
[conda] torchvision               0.16.1              py311_cu121    pytorch

cc @ptrblck

**Comment by drisspg** [comment]
Could you run the realworld example with 

`TORCH_SHOW_CPP_STACKTRACES=1` env variable set, and paste the output?

**Comment by h3jia** [comment]
@drisspg 

```
Traceback (most recent call last):
  File "/home/hejia/lss-dev/00-wl/04/01-train-0-10k-debug-0.py", line 266, in <module>
    foo = nqe.train_1d(qnet[i_dim], device='cuda', train_loader=train_loader, valid_loader=valid_loader,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hejia/nqe/nqe/train.py", line 283, in train_1d
    loss_now.backward()
  File "/home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: integer out of range
Exception raised from safe_downcast at /opt/conda/conda-bld/pytorch_1699449201450/work/aten/src/ATen/native/Pool.h:41 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x1543d9fe2617 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x68 (0x1543d9f9da56 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x127db33 (0x1543db34ab33 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: at::native::structured_avg_pool2d_backward_out_cuda::impl(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, bool, c10::optional<long>, at::Tens
or const&) + 0x2845 (0x1543db34fab5 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x2e1bbb9 (0x1543dcee8bb9 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x2e1bc60 (0x1543dcee8c60 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #6: at::_ops::avg_pool2d_backward::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, bool, c10::optional<long>) + 0
x125 (0x154417065815 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x3f6f52e (0x154418bee52e in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x3f6fdd1 (0x154418beedd1 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #9: at::_ops::avg_pool2d_backward::call(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, bool, c10::optional<long>) + 0x1f4 (0x1544170e7394 in /ho
me/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #10: torch::autograd::generated::AvgPool2DBackward0::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x1d5 (0x154418831ce5 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-pack
ages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x4858a2b (0x1544194d7a2b in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #12: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 
0xe8d (0x1544194d0ced in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #13: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x698 (0x1544194d2048 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/libtor
ch_cpu.so)
frame #14: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x96 (0x1544194c8d76 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch
/lib/libtorch_cpu.so)
frame #15: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x5c (0x1544213bea4c in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-
packages/torch/lib/libtorch_python.so)
frame #16: <unknown function> + 0xdbbf4 (0x1544274acbf4 in /home/hejia/.conda/envs/hejia@della-5/lib/python3.11/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #17: <unknown function> + 0x81ca (0x154473a5d1ca in /lib64/libpthread.so.0)
frame #18: clone + 0x43 (0x154472f3fe73 in /lib64/libc.so.6)
```

**Comment by eqy** [comment]
Some layers still lack 64-bit indexing support which would produce the error(s) you have reported. However, because the error messages look different between your minimal reproducer and the real-world example you have, I would expect the fixes for them to be in different places even if the root-causes are very similar. I'll take a look at the limitation in `structured_avg_pool2d_backward_out_cuda`.

**Comment by eqy** [comment]
Here's a minimal reproducer for the second error message:
```
import torch

a = torch.randn(128, 256, 256, 256, dtype=torch.half, device='cuda', requires_grad=True)
m = torch.nn.AvgPool2d(2)
o = m(a)
o.sum().backward()
```

**Comment by chuanli11** [comment]
Here is another minimal reproducer 

```
import torch
from torch import nn
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

in_channels = 514
out_channels = 1
kernel_size = 3
stride = 1
padding = 1

input_tensor = torch.ones(1, in_channels, 2048, 2048).cuda().half()
model = nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding).cuda().half()

output = model(input_tensor)
```

Gave

```
RuntimeError: CUDA error: an illegal memory access was encountered
```

Change `in_channels` to `512` avoided the error (used ~50 GB VRAM out of 80GB).

**Comment by eqy** [comment]
@chuanli11 That looks like a separate issue as it is an IMA that is in a convolution. Could you open a separate issue for that please?

**Comment by chuanli11** [comment]
> @chuanli11 That looks like a separate issue as it is an IMA that is in a convolution. Could you open a separate issue for that please?

Hey, just saw this. A new ticket [117736](https://github.com/pytorch/pytorch/issues/117736) is created for this. Thanks.
