### ISSUE TITLE
How to  re-use torch.compile results in different python processes?

### ISSUE THREAD

**Issue by flishwang** [pytorch/pytorch#113933]
### 🚀 The feature, motivation and pitch

I'm trying to compile my custom vision transformer-based model. The compiled version is indeed faster than the traditional one.

However, as scaled_dot_product_attention does not support dynamic shapes, the program compiles the transformer block for every input size. Thus, the TEST program takes ~15-20 minutes to compile the model and then processes hundreds to thousends pictures, which is ~10 times slower than the eager mode.

I wonder if there's some api to save the intermediate states, so that when I run the same code again, I can reuse the compilation results in /tmp/torchinductor_$user and skip the boring compilation stage? 

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @wconstab @aakhundov

**Comment by ezyang** [comment]
Do you mind running your program with `TORCH_LOGS=dynamic` and posting the logs here? Thanks!

**Comment by jon-chuang** [comment]
>  in different python processes

How many processes are we talking about?

**Comment by flishwang** [comment]
> > in different python processes
> 
> How many processes are we talking about?

Sorry I seemed to describe it ambiguously. I didn't mean any multi-processing stuffs. I was wondering about the possibility of re-using compiler/inductor cache from ANOTHER process, or program, if the code involved keeping unchanged. Currently pytorch would re-compile the codes if you quit python and re-run it a minute or an hour later.

**Comment by jon-chuang** [comment]
As of now it's basically impossible. The compiled artifact lifetimes are tied to python objects. Your best bet might be torch.export?

**Comment by flishwang** [comment]
> Do you mind running your program with `TORCH_LOGS=dynamic` and posting the logs here? Thanks!

Sure!
In the zip file:
convit2.py is the source code for the model I used.

log-test.out is the running logs with TORCH_LOGS=dynamic and @torch.compile upon SwinTransformerBlock.forward at L:468.

log-test2.out is the running logs with TORCH_LOGS=all and @torch.compile(dynamic=False) upon SwinTransformerBlock.forward at L:468. Only this setting may pass the compile process both for train and inference, though the compile time is really long.

log-test3.out and log-test4.out is the running logs with TORCH_LOGS=all and @torch.compile upon either Data2VecConViT2.forward_encoder or upon *Layer.forward. Both dynamic=True and dynamic=None result in compiling errors.

[logs.zip](https://github.com/pytorch/pytorch/files/13401841/logs.zip)

**Comment by ezyang** [comment]
I am actually not sure why you concluded the problem is sdpa specific, I don't see anything in the logs that indicates this. In log-test.out I do see a few specializations

```
[rank0]:[2023-11-19 00:33:36,849] [3/1] torch.fx.experimental.symbolic_shapes: [INFO] eval Eq(s0, 128) [guard added] at project/models/common.py:21 in <resume in forward> (_meta_registrations.py:1813 in meta_mm)
[rank0]:[2023-11-19 00:33:39,720] [3/3] torch.fx.experimental.symbolic_shapes: [INFO] eval Eq(s0, 64) [guard added] at nn/modules/conv.py:456 in _conv_forward (_subclasses/fake_tensor.py:677 in conv)

s0 here is x.size(1), though I'm not sure exactly what this parameter is (surely it is not channels? Maybe it is?!)

Another thing I notice is that there are a lot of graph breaks. It might be worth trying to get rid of some of them.

In any case, your original feature request seems valid. It's probably something we'll be working on soon.

**Comment by jon-chuang** [comment]
Wait a minute, don't we have TORCHINDUCTOR_CACHE_DIR?

**Comment by jon-chuang** [comment]
See also: https://github.com/pytorch/pytorch/issues/113287

It is reported that these only slightly mitigate compilation cost, but it is not enough. Actually, I'm interested in contributing to this. I believe that persistent code reuse could be really valuable. But there are many tiers to this.
1. Guard-level
2. Generated fx <-> backend compiler
3. Backend-level

Each presents its own challenges. Backend-level seems to be partly implemented.

**Comment by flishwang** [comment]
> I am actually not sure why you concluded the problem is sdpa specific, I don't see anything in the logs that indicates this. In log-test.out I do see a few specializations
> 
> ```
> [rank0]:[2023-11-19 00:33:36,849] [3/1] torch.fx.experimental.symbolic_shapes: [INFO] eval Eq(s0, 128) [guard added] at project/models/common.py:21 in <resume in forward> (_meta_registrations.py:1813 in meta_mm)
> [rank0]:[2023-11-19 00:33:39,720] [3/3] torch.fx.experimental.symbolic_shapes: [INFO] eval Eq(s0, 64) [guard added] at nn/modules/conv.py:456 in _conv_forward (_subclasses/fake_tensor.py:677 in conv)
> ```
> 
> s0 here is x.size(1), though I'm not sure exactly what this parameter is (surely it is not channels? Maybe it is?!)
> 
> Another thing I notice is that there are a lot of graph breaks. It might be worth trying to get rid of some of them.
> 
> In any case, your original feature request seems valid. It's probably something we'll be working on soon.

Thanks for your timely reply!
The following logs (L3148-L3168 in log-test.out) indicate the problem is related to the sdpa function.
I also tried to compile the different part of the WindowAttention block, and the program crashes as long as the sdpa is involved into a torch.compile(dynamic=True) decorator.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/torch/fx/graph_module.py", line 274, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.508", line 73, in forward
    scaled_dot_product_attention = torch._C._nn.scaled_dot_product_attention(type_as_1, type_as_2, type_as_4, attn_mask = type_as_3, dropout_p = 0.0);  type_as_1 = type_as_2 = type_as_4 = type_as_3 = None
RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides

Call using an FX-traced Module, line 73 of the traced Module's generated forward function:
    type_as_4 = getitem_1.type_as(type_as_1);  getitem_1 = None
    scaled_dot_product_attention = torch._C._nn.scaled_dot_product_attention(type_as_1, type_as_2, type_as_4, attn_mask = type_as_3, dropout_p = 0.0);  type_as_1 = type_as_2 = type_as_4 = type_as_3 = None

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```
I knew that there are a lot of graph breaks in my program, and I have done my best to get rid of them and failed. This was mainly because that torch.compile seems to be incompatible with torch.utils.checkpoint (see log-test3.out/log-test4.out). As the training process depends highly on the checkpoint trick to save GPU memory, I cannot remove them and have to compile the graphs seperately in each checkpoint block. That's why there are so many fx graphs.

**Comment by voznesenskym** [comment]
https://github.com/pytorch/pytorch/pull/114499 for an example - I am still iterating, but the test example works. Still very trivial, still a lot of directional changes to make. One major gap in that PR, is that the flag in the config will 100% not ship, we want to collapse the two worlds.

**Comment by bhack** [comment]
@ezyang Is currently the cache still process specific? It cannot be recycled in a new python process same code right?

**Comment by ezyang** [comment]
We're working on this. The inductor cache works right now and can be used cross process. An AOTAutograd cache is in progress. @Chillee is also trying to get us to spend some resources on a non-cache, more explicit interface as well.

**Comment by Mohamed-Dhouib** [comment]
Hello @ezyang , using the latest version of Python, when I run a training session using `torch.compile` with `mode="max-autotune-no-cudagraphs"` and then rerun another session after the first one is finished, the model does not recompile, which is quite practical. However, when I run a training session from another terminal or like a day later, it does recompile. Is there any way to avoid this?

**Comment by ezyang** [comment]
By default the file system cache products are put in /tmp, and I guess you are getting a tmp cleaner. Change it with TORCHINDUCTOR_CACHE_DIR. Read more at https://pytorch.org/tutorials/recipes/torch_compile_caching_tutorial.html

**Comment by Mohamed-Dhouib** [comment]
Great thanks !

**Comment by apresence** [comment]
FWIW,  it looks like the folks over at [Parler-TTS](https://github.com/huggingface/parler-tts) figured out how to get SDPA working with torch.compile() via [PR#89](https://github.com/huggingface/parler-tts/pull/89).

Looking at the code, it may be as simple as calling .contiguous() on the input_ids?
```
# NOTE: SDPA with memory-efficient backend is currently (torch==2.1.2) bugged when using non-contiguous inputs and a custom attn_mask,
# but we are fine here as `_shape` do call `.contiguous()`. Reference: https://github.com/pytorch/pytorch/issues/112577
...
"input_ids": input_ids.contiguous(), # `contiguous()` needed for compilation use cases
```

Thanks!

> ### 🚀 The feature, motivation and pitch
> I'm trying to compile my custom vision transformer-based model. The compiled version is indeed faster than the traditional one.
> 
> However, as scaled_dot_product_attention does not support dynamic shapes, the program compiles the transformer block for every input size. Thus, the TEST program takes ~15-20 minutes to compile the model and then processes hundreds to thousends pictures, which is ~10 times slower than the eager mode.
> 
> I wonder if there's some api to save the intermediate states, so that when I run the same code again, I can reuse the compilation results in /tmp/torchinductor_$user and skip the boring compilation stage?
> 
> ### Alternatives
> _No response_
> 
> ### Additional context
> _No response_
> 
> cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @wconstab @aakhundov
