### ISSUE TITLE
torch.compile introduces runtime dependency on setuptools or packaging

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#113940]
### 🐛 Describe the bug

```python
# main.py
import torch

@torch.compile()
def fn():
    pass
```

```bash
❯ python -VV
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32) 
[GCC 12.3.0]
❯ python -Werror main.py
[...]
ModuleNotFoundError: No module named 'packaging.version'
[...]
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

As seen above, I don't have `packaging` installed in my env and `pkg_resources` is deprecated. Not only that, but starting with Python 3.12, `setuptools` (which supplies `pkg_resources`) will no longer be installed as part of a [`venv`](https://docs.python.org/3/whatsnew/3.12.html). Meaning, users of that will see errors when trying to use `torch.compile`.

The underlying issue, i.e. the non-declared dependency, was already reported in #71280 and highlighted again in https://github.com/pytorch/pytorch/pull/71902#issuecomment-1036250128 but never addressed.

`torch.compile` hits this because it crawls torch modules at startup:

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/_dynamo/allowed_functions.py#L155-L158

And with that it for example hits

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/__init__.py#L35

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/torch_version.py#L89

That by itself would not cause the dependency issue to show up, because we only lazy load either of the packages (#71345). However, during the crawling we also check each obj we find whether it is part of a special case list 

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/_dynamo/allowed_functions.py#L225-L233

and that in turn materializes the version

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/torch_version.py#L86-L87

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/torch_version.py#L75-L77

ultimately triggering the traceback above.

I think we should do one of two things:

1. Add a runtime dependency on `packaging`, i.e. have another go at #113023.
2. Vendor the relevant parts of `packaging.version` as was proposed in https://github.com/pytorch/pytorch/pull/71902#issuecomment-1036250128

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @malfet @rgommers @vfdev-5 @hauntsaninja

### Versions

2.2.0.dev20231116+cpu

**Comment by pmeier** [comment]
#112882 added a `packaging` dependency for Windows.

**Comment by ezyang** [comment]
Let's just vendor it

**Comment by albanD** [comment]
Why do we prefer to vendor vs take a runtime dependency here?

**Comment by pmeier** [comment]
My vote is out for adding a dependency, but no strong opinion.


@malfet

> I remember folks complained about import times of the entire packaging package. But if this no longer a concern, then we can just depend on it

The complain was about using `pkg_resources`. Using `packaging` solved this issue in https://github.com/pytorch/pytorch/pull/71902#issue-1115837766.
