### ISSUE TITLE
Increase input parameter consistency between SGD optimizer and other optimizers

### ISSUE THREAD

**Issue by GdoongMathew** [pytorch/pytorch#114089]
### 🚀 The feature, motivation and pitch

I'm working on dynamically switching optimizer in a training script for testing their training effects on my model. However, since SGD has no default value to its lr, I'll have to manually set its default lr like the following script
```python
param_gps = [{"params": ..., "lr": 1e-3}, {"params": ..., "lr": 1e-4}]
for optim_str in ["torch.optim.SGD", "torch.optim.Adam", "torch.optim.AdamW"]
    optim_class = import_class(optim_str )
    kwargs = {"params": param_gps}
    if optim_str == "SGD":
        kwargs["lr"] = 1e-3
    optim_instance = optim_class(**kwargs)
    ...
```

In most other optimizers, their lr input parameter was given a default value, whereas SGD was not.
I think it will be better to set a default lr value to 0.001 in SGD so that all optimizers' input signatures can be more alike.

My suggestion is to remove its default as required, and change it to something like 1e-3.
```python
class SGD(Optimizer):
    def __init__(self, params, lr=1e-3, momentum=0, dampening=0,
                 weight_decay=0, nesterov=False, *, maximize: bool = False, foreach: Optional[bool] = None,
                 differentiable: bool = False):
        if lr < 0.0:
            raise ValueError(f"Invalid learning rate: {lr}")
```

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by janeyx99** [comment]
I believe the reason we hadn't given it a default is because there's no "silver bullet" lr that works with every model, and so lr scheduling and hyperparameterization are big concepts.

That said, I agree it would be nice to have a default mainly for consistency across our optimizers. But which value? Looking across our tutorials, I think any value of 1e-3, 5e-3, and 1e-2 would be reasonable. Do you have a reason for proposing 1e-3?

**Comment by janeyx99** [comment]
In any case, we would accept a PR making this change and modifying testing appropriately. I am okay with 1e-3 as the value we go with.

**Comment by GdoongMathew** [comment]
I just think 1e-3 is not a bad choice to start with, from my experiences and tutorials on the internet, like this [one](https://pytorch.org/tutorials/beginner/basics/optimization_tutorial.html).
Then I'll start working on this, Thanks.
