### ISSUE TITLE
New Optimizer 

### ISSUE THREAD

**Issue by Musa-Sina-Ertugrul** [pytorch/pytorch#114064]
### 🚀 The feature, motivation and pitch

Me and my team will research a new optimizer. Can we use PyTorch Optimizer Class? If it works we can gladly contribute our work to the repo. The research will be pursued for a year.

### Additional context

Like every research, we can fail

_No response_

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by enesduran** [comment]
I think you should be able to do it as it is an opensource project. Just check the license to make sure

**Comment by Musa-Sina-Ertugrul** [comment]
I checked so I wanted to ask

**Comment by jbschlosser** [comment]
Hey @Musa-Sina-Ertugrul, feel free to use the Optimizer class for your research. Most likely we will suggest maintaining your final optimizer code in a separate OSS repo based on PyTorch, as we are generally very conservative on accepted new optimizers / modules to PyTorch Core.

**Comment by Musa-Sina-Ertugrul** [comment]
Thanks 😄
