### ISSUE TITLE
Automatically report the user stacktrace of a guard that caused recompilation

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#114015]
### 🐛 Describe the bug

TORCH_LOGS=recompiles will report to you which guard failed which caused a recompilation. But where did that guard come from? We actually typically do know, but we don't retain it to the guard. We should!

### Versions

main

**Comment by jon-chuang** [comment]
I think inline comment and printing the guard "part" with the inline comment ought to be fine?
