### ISSUE TITLE
[pt2] Make error message clearer for torch.compile when running on windows

### ISSUE THREAD

**Issue by angelayi** [pytorch/pytorch#114005]
### 🚀 The feature, motivation and pitch

Request from users (TensorRT team) for a better error message when running torch.compile on windows. 

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by angelayi** [comment]
Oh, I think this should be fixed with https://github.com/pytorch/pytorch/pull/111313. cc @narendasan @gs-olive

**Comment by narendasan** [comment]
Seems like that PR has stalled, any idea what the blocker was?

**Comment by narendasan** [comment]
> Hello; could you please clarify what is the current "error message" and what is the expectation for new message?
> 
> We would like to kindly request more context regarding the scenario for this error message to reproduce.

Just for context, torch on windows reports that dynamo is not supported where it seems like the limitation is inductor (triton). This block clean workflows for backends other than inductor (like torch-tensorrt)

**Comment by ezyang** [comment]
@gs-olive if this is true, I think it would be reasonable to move the Windows test into the inductor backend so people can work with Dynamo on windows

**Comment by gs-olive** [comment]
It does seem to be the case, with the exception of [these tests](https://hud.pytorch.org/pytorch/pytorch/pull/115969?sha=98b61f39d675d5ad1f5994eb9b53957ef2535d16) that fail when enabling Dynamo on Windows, which appear to be mostly export + CPU related.

**Comment by masnesral** [comment]
> Oh, I think this should be fixed with https://github.com/pytorch/pytorch/pull/111313

@angelayi, looks like that PR was completed. Do you think we can close this issue?
