### ISSUE TITLE
[dynamo] Cacheing issue with nopython

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#114059]
### 🐛 Describe the bug

Dynamo will incorrectly fallback on compiled objects with graph breaks for the object produced by compiling with `fullgraph=True/nopython=True`

```python
# We clearly have 2 graphs
def fn(x):
    x = x + 2
    torch._dynamo.graph_break()
    return x + 1

opt_fn = torch._dynamo.optimize(backend="eager")(fn)
nopython_fn = torch._dynamo.optimize(backend="eager", nopython=True)(fn)

try:
    nopython_fn(torch.zeros(1))
except Exception:
    print("failed to run")

print(opt_fn(torch.zeros(1)))
print(nopython_fn(torch.zeros(1)))
```

Also a repro:
```python

def fn(x):
    x = x + 2
    torch._dynamo.graph_break()
    return x + 1

opt_fn = torch.compile(fn, backend="eager")
nopython_fn = torch.compile(fn, backend="eager", fullgraph=True)

try:
    nopython_fn(torch.zeros(1))
except Exception:
    print("failed to run")

print(opt_fn(torch.zeros(1)))
print(nopython_fn(torch.zeros(1)))
```

Not a repro:

```python
def fn(x):
    x = x + 2
    torch._dynamo.graph_break()
    return x + 1

opt_fn = torch._dynamo.optimize(backend="eager")(fn)
nopython_fn = torch.compile(fn, backend="eager", fullgraph=True)

try:
    nopython_fn(torch.zeros(1))
except Exception:
    print("failed to run")

print(opt_fn(torch.zeros(1)))
print(nopython_fn(torch.zeros(1)))
``` 

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jon-chuang** [comment]
I think we need to guard on `nopython`? @ezyang @voznesenskym

**Comment by ezyang** [comment]
I guess it's a little more subtle than that, because if I have a fullgraph cache entry from a non fullgraph run, it should still satisfy the fullgraph

**Comment by jon-chuang** [comment]
I think this part is simple - if the compiled object's context has nopython we set a strict global flag via context manager. Strict flag will then cause cache miss. Conversely, no ambient strict flag will cause cache hit on either case.

```python
assert not global.nopython or entry.nopython == True
```

**Comment by jon-chuang** [comment]
Actually, maybe it is simpler than that - we can lazily guard on nopython _iff_ there is a graph break.

**Comment by jon-chuang** [comment]
Hmm, but actually I think nopython is stricter than that, even if there are no graph breaks, it cannot have any python code at all? :thinking:

**Comment by ezyang** [comment]
Nah, it just means there shouldn't be graph breaks
