### ISSUE TITLE
inconsistency in torch.mm on GPU and CPU

### ISSUE THREAD

**Issue by beanduan22** [pytorch/pytorch#114087]
### 🐛 Describe the bug

```python
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import os
import torch.nn.functional as F
gpu_device = torch.device("cuda")
cpu_device = torch.device("cpu")
class PreprocessAndCalculateModel(nn.Module):
    def init(self):
        super().init()
    def forward(self, x):
        out = torch.mm(x, x, out=x)
        return out

real_inputs = torch.randn(32,32)
model = PreprocessAndCalculateModel()
x = real_inputs
output_gpu = model.to(gpu_device)(real_inputs.cuda())
output_cpu = model.to(cpu_device)(real_inputs.cpu())
print(output_gpu)
print(output_cpu)
```

### Versions
```
tensor([[  3.2931,  -8.6685,  -6.2575,  ...,  -3.4744,   2.6226, -11.3901],
        [ -0.5287,  -1.5858,  -1.7094,  ...,  -2.5426,   1.5429,  -2.2449],
        [ -1.9473,  -2.1211,   1.3305,  ...,  -3.6599,  -5.3107,   1.3138],
        ...,
        [  4.6994,  -2.7434,   6.9632,  ...,   3.1337,   0.8468,   7.6368],
        [ -0.7506,   3.4822,  -1.5265,  ...,   5.1816,   2.3886,  -0.5142],
        [ -1.6813,  -0.4619,  -3.2844,  ...,   3.0092,  -3.0827,  -8.0445]],
       device='cuda:0')
tensor([[   3.2931,   -8.6685,   -6.2575,  ...,   -3.4744,    2.6226,
          -11.3901],
        [  -0.5287,   -1.5858,   -1.7094,  ...,   -2.5426,    1.5429,
           -2.2449],
        [  -1.9473,   -2.1211,    1.3305,  ...,   -3.6599,   -5.3107,
            1.3138],
        ...,
        [  25.8082,  -88.4026,  -68.5409,  ...,  -37.9862,   52.1288,
         -177.4709],
        [  53.8154,  -62.1652,  -38.7421,  ...,  -17.3279,   57.9864,
         -191.8189],
        [   4.3106,  -57.1305,   36.5368,  ...,   -7.0021,  -38.0642,
           22.5374]])
False
```

**Comment by ZailiWang** [comment]
by calling `torch.mm(x,x,out=x)` the input has been changed before the 2nd cpu calling.

**Comment by beanduan22** [comment]
> by calling `torch.mm(x,x,out=x)` the input has been changed before the 2nd cpu calling.

you can try x = torch.randn(2,2), the result is  same on GPU and CPU

**Comment by ptrblck** [comment]
> you can try x = torch.randn(2,2), the result is same on GPU and CPU

It's not. The code works fine if you remove the `out=x` usage as @ZailiWang explained.

**Comment by beanduan22** [comment]
> > you can try x = torch.randn(2,2), the result is same on GPU and CPU
> 
> The code works fine if you remove the `out=x` usage as @ZailiWang explained.

I am wondering why the results depends on the input size, the input size = (2,2) can generate same result, but the input size=(32,32) can not.

**Comment by malfet** [comment]
Hmm, what GPU are you running this one on? A100+ If this is the case, one needs to disable tf32 support to get results identical to the ones on CPU

**Comment by ptrblck** [comment]
> A100+ If this is the case, one needs to disable tf32 support to get results identical to the ones on CPU

TF32 is disabled by default for `matmul`s and enabled for cuDNN, which is not used here.

**Comment by malfet** [comment]
Ok, looks like `torch.mm` is place broken for CPU:
```
$ python3 -c "import torch;x=torch.arange(9, dtype=torch.float32, device='cpu').reshape(3,3);print(torch.mm(x, x, out=x))"
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

```

**Comment by malfet** [comment]
Closing as duplicate https://github.com/pytorch/pytorch/issues/114350 (please note that in-place matmul behavior is undefined, we probably should error out)
