### ISSUE TITLE
Issue with hoy/autotune/lanucher branch

### ISSUE THREAD

**Issue by ratan-prasad** [pytorch/pytorch#114130]
### 🐛 Describe the bug

It is not a bug per say, but a issue we are facing. We see that a new branch has been added with name "hoy/autotune/lanucher".
We have forked the pytorch repository and our internal automation of fetching the latest code is broken due to above branch name.

Error fetching 'amd/ec/ZenDNN_PyTorch.git':
From https://github.com/pytorch/pytorch
...
error: 'refs/heads/hoy' exists; cannot create 'refs/heads/hoy/autotune/lanucher'
! [new branch]      hoy/autotune/lanucher -> hoy/autotune/lanucher  (unable to update local ref)
...
error: some local refs could not be updated; try running  'git remote prune origin' to remove any old, conflicting branches
Can you please let me know what could be the reason?

cc @seemethere @malfet @pytorch/pytorch-dev-infra

### Versions

Latest main branch

**Comment by malfet** [comment]
Reminds me of https://github.com/pytorch/pytorch/issues/106544

**Comment by malfet** [comment]
@ratan-prasad Hmm, where do you see `hoy` branch?
```
 % git fetch -p; git branch -a|grep hoy
From https://github.com/pytorch/pytorch
 + b19b08e1606...f875027713d Update-test-distribute -> origin/Update-test-distribute  (forced update)
 * [new branch]              update-test-distribute -> origin/update-test-distribute
  remotes/origin/hoy-reduction-outer
  remotes/origin/hoy-revert
  remotes/origin/hoy-update-wheel
  remotes/origin/hoy/autofdo/xblock
  remotes/origin/hoy/autotune/lanucher
  remotes/origin/hoy/autotune/nreg
  remotes/origin/hoy/autotune/numwarps
```

**Comment by malfet** [comment]
Closing as nothing seems wrong with the repro. But please do not hesitate to open a new issue if clean checkout of PyTorch fails for you.

**Comment by ratan-prasad** [comment]
Hi @malfet the branch name giving issue is: "hoy/autotune/lanucher". Not able to find 'refs/heads/hoy. I am seeing this message. maybe i can try it:
error: some local refs could not be updated; try running  'git remote prune origin' to remove any old, conflicting branches

**Comment by malfet** [comment]
@ratan-prasad if you persist repo checkout in your CI, then as advised you need to run `git remote prune origin`
