### ISSUE TITLE
Consider adding y/x -> y * 1/x optimization for `_foreach_div_.ScalarList` and other div Scalar overloads

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#114165]
`_foreach_div_.ScalarList` is not bitwise equal to a for loop of `div_.Scalar` due to the following optimization added in https://github.com/pytorch/pytorch/pull/29428: in a div op, we'd prefer `Tensor * (1/Scalar)` over `Tensor / Scalar`. This is because computing multiplication is faster than computing division. This optimization is observable for when there is a lot of math going on for the same memory (like in normalization). Otherwise, the speedup may not be observable between div and mul when most of what's happening is reading and storing memory, in which case the performance is bandwidth bound. 

To be clear, _**one should not rely on bitwise equality between foreach ops and their single-tensor equivalents**_, since foreach is an optimization that may take its own shortcuts. That said, it may be interesting considering the following so I made a tracker:

- [ ] Add this optimization for `_foreach_div_.Scalar` as it should be trivial to reroute to `_foreach_mul_.Scalar`.
- [ ] Reroute `_foreach_div_.Tensor` to `_foreach_mul_.Scalar` directly when the ScalarTensor is on CPU (currently it routes to `_foreach_mul_.Scalar`)
- [ ] Would this be considered an optimization still for `_foreach_div_.ScalarList`? Is there a fast way to invert scalars in CUDA so we could avoid adding a forloop of reciprocals on the CPU side?

## Code example

The code that causes a discrepancy between _foreach_div and normal div_: 
https://github.com/pytorch/pytorch/blob/aeb5fd52c74b1c673e8565b9593cbdd5ed6f04f2/aten/src/ATen/native/cuda/BinaryDivTrueKernel.cu#L35-L49

## Interesting context

This discrepancy is the only reason default `Adam` and `Adam(foreach=False)` differ. Otherwise the two optimizers would be bitwise equivalent. cc @vincentqb @jbschlosser @albanD @crcrpar @mcarilli @awgu 

cc @crcrpar @ngimel

**Comment by ngimel** [comment]
For the last item, I think it's still best to have a loop on the cpu
