### ISSUE TITLE
[Feature request]: Add Log-Uniform distribution to sample very small values

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#11412]
Suppose we want to sample very small positive values, say in the range `[1e-6, 5e-2]`, this is very unstable by using uniform distribution. However, it can be alleviated by using log-uniform distribution, i.e. `exp(U[log(a), log(b)])`.

**Comment by upriser7** [comment]
@soumith I'd be happy to work on this if no else is

**Comment by fritzo** [comment]
This is simple to implement via `TransformedDistribution`
```py
import torch.distributions as dist
class LogUniform(dist.TransformedDistribution):
    def __init__(self, lb, ub):
        super(LogUniform, self).__init__(dist.Uniform(lb.log(), ub.log()),
                                         dist.ExpTransform())
```
Thus it seems to me it's not worth adding this to torch.distributions.
