### ISSUE TITLE
Typo in example of torch.linalg.solve_triangular

### ISSUE THREAD

**Issue by DemoAuguste** [pytorch/pytorch#114113]
### 📚 The doc issue

link: https://pytorch.org/docs/stable/generated/torch.linalg.solve_triangular.html

the variable b in the given example should be upper case.
![image](https://github.com/pytorch/pytorch/assets/21033607/007a4def-a864-4a3e-8f40-c36b1423734c)
 

### Suggest a potential alternative/fix

change b to upper case.

cc @svekars @carljparker @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano

**Comment by jbschlosser** [comment]
Sure, we'd accept a PR fixing the typo.

**Comment by lezcano** [comment]
@kit1980 @Skylion007  don't we have a lintert that can catch these?
