### ISSUE TITLE
torch.vmap doesn't compose with torch.cond

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#114136]
```py
import torch
img = torch.rand(3, 10, 10)

def maybe_add_cond(img):
    return torch.cond(
        pred=torch.rand(1) < .5,
        true_fn=lambda img: img + 10,
        false_fn=lambda img: img,
        operands=(img,)
    )

torch.vmap(maybe_add_cond, randomness="different")(img)
```

Might need a bit of design to figure out what the right thing to do here is. cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @Chillee @samdow @kshitij12345 @janeyx99 @ydwu4 @voznesenskym @NicolasHug

**Comment by zou3519** [comment]
It's possible this will just work after we teach torch.compile how to turn a BatchedTensor into a fake BatchedTensor.

**Comment by ezyang** [comment]
Isn't this the thing where you do a dynamic split into the true/false tensors, run the separate compute on each of them, and the reinterleave them together? You can also try to compiler pass transforming the inside pieces into torch.where but that may not work if there are memory accesses involved
