### ISSUE TITLE
funccol collectives rewrite in dynamo does not work w/ kwargs

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#114179]
### 🐛 Describe the bug

parent: https://github.com/pytorch/pytorch/issues/114286

This is a silly bug - when we rewrite all_gather_into_tensor into all_gather_tensor_inplace, we just straight line unpack args from old->new. This is fine, unless we use kwargs, which in this case, subtly mismatch between the two impls (output vs output_tensor).

ex:
```
dist.all_gather_into_tensor(
                output_tensor=flat_tensor, input_tensor=input_flat_tensor_shard, group=group
            )
```
vs            
```
dist.all_gather_into_tensor(
                flat_tensor, input_flat_tensor_shard, group=group
            )
```

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by rabroldan** [comment]
Hi there can I take this issue? I wanted to ask if im getting it right, so we renamed  all_gather_tensor to  all_gather_tensor_inplace and basically kept the functionality.  So we want it to work when we use kwargs?

```
dist.all_gather_into_tensor(
                flat_tensor, input_flat_tensor_shard, group=group
            )
```

**Comment by voznesenskym** [comment]
> Hi there can I take this issue? I wanted to ask if im getting it right, so we renamed all_gather_tensor to all_gather_tensor_inplace and basically kept the functionality. So we want it to work when we use kwargs?
> 
> ```
> dist.all_gather_into_tensor(
>                 flat_tensor, input_flat_tensor_shard, group=group
>             )
> ```

Yea :) we do the renaming dynamically in dynamo in `CollectiveFunctionRewriteVariable` - 

Check out:
```
def _traceable_collective_remaps():
    # We can't rely on importing from distributed, since it's not always built
    if torch.distributed.is_available():
        from torch.distributed._functional_collectives import (
            traceable_collective_remaps,
        )

        return traceable_collective_remaps
    return {}
```
The problem is where we go to invoke it:

`return self.replacement_var.call_function(tx, args, kwargs)`

Will mismatch because kwarg names are not the same across functions.

The simplest solution here is to (1) line up the names across functions (2) add a test to safeguard that those signatures stay the same (3) add a dynamo test to cover this case

**Comment by rabroldan** [comment]
Alright sounds good ill try to work on it

**Comment by rabroldan** [comment]
Im still working on it will send a PR soon

**Comment by rabroldan** [comment]
Hi there can I ask something. i was looking at the code and was curious are you guys expriencing the same issue with 

reduce_scatter_tensor(input, op, scatter_dim, group, tag)
