### ISSUE TITLE
Error on cuda.LongTensor which is sent via multiprocessing.Queue

### ISSUE THREAD

**Issue by kintaat** [pytorch/pytorch#11422]
I was trying to send multiple tensors in tuple via `multiprocessing.Queue` to anther process. However when I access to a cuda LongTensor, I get this error
```
RuntimeError: Attempt to access Storage having data type Float as data type Long
```
## Code example
```
import torch
import torch.multiprocessing as mp
import time

def producer(queue):
    while True:
        a = torch.ones(2,2).float().cuda()
        idx = torch.LongTensor([[0, 0], [0, 1]]).cuda()
        queue.put((a, idx))

def consumer(queue):
    while True:
        a, idx = queue.get()
        print(idx.type())
        print(idx)

if __name__ == '__main__':
    mp.set_start_method('spawn')

    queue = mp.Queue()

    p = mp.Process(target=producer, args=(queue,))
    c = mp.Process(target=consumer, args=(queue,))
    p.start()
    c.start()
    
    time.sleep(10)

    p.join()
    c.join()
```
Output:
```
torch.cuda.LongTensor
Process Process-2:
Traceback (most recent call last):
  File "***/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "***/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "queue_test.py", line 15, in consumer
    print(idx)
  File "***/lib/python3.5/site-packages/torch/tensor.py", line 57, in __repr__
    return torch._tensor_str._str(self)
  File "***/lib/python3.5/site-packages/torch/_tensor_str.py", line 256, in _str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "***/lib/python3.5/site-packages/torch/_tensor_str.py", line 76, in __init__
    copy = torch.empty(tensor.size(), dtype=torch.long).copy_(tensor).view(tensor.nelement())
RuntimeError: Attempt to access Storage having data type Float as data type Long
```

## System Info
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 14.04.5 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
CMake version: version 3.11.0

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 375.66
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6.0.21
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.13.3)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] torch                     0.4.1                     <pip>
[conda] torchvision               0.2.1                     <pip>

**Comment by bobflame** [comment]
same issue.

**Comment by ashaw596** [comment]
This doesn't occur in the 1.0 current preview I think.

**Comment by ailzhang** [comment]
I got a different error on master, will take a look later today. 
```
 λ ~ python 11422.py
Process Process-2:
Traceback (most recent call last):
  File "/private/home/ailzhang/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/private/home/ailzhang/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/private/home/ailzhang/11422.py", line 13, in consumer
    a, idx = queue.get()
  File "/private/home/ailzhang/miniconda3/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/scratch/pytorch/torch/multiprocessing/reductions.py", line 96, in rebuild_cuda_tensor
    t = torch._utils._rebuild_tensor(storage, tensor_offset, tensor_size, tensor_stride)
  File "/scratch/pytorch/torch/_utils.py", line 94, in _rebuild_tensor
    return tensor_class().set_(storage, storage_offset, size, stride)
RuntimeError: Expected object of data type 4 but got data type 6 for argument #2 'source'
```

**Comment by DavidJanz** [comment]
Have same issue as kintaat on 0.4.1 and same issue as alizhang on master

**Comment by ailzhang** [comment]
I think I figured out the problem.  Suppose we have long and float tensor a & b to put into shared memory, but a & b actually share the same memory handle. From the note we put the largest memory region in shared memory once [Here](https://github.com/pytorch/pytorch/blob/master/torch/multiprocessing/reductions.py#L93).  However this casted the memory region to be the same class which is the same as whatever you put into the queue first. And when we try to rebuild the second tensor, it complains about the wrong type of storage. 
I can't think of a good solution right away, need to discuss with @ezyang for it.

**Comment by tudorsabin** [comment]
> Have same issue as kintaat on 0.4.1 and same issue as alizhang on master

I have this too, on the same version, will try to create another conda environment to check if the nightly build has this issue.

**Comment by ailzhang** [comment]
FYI after discussed with @ezyang , this repro script does reveal a bug in torch.multiprocessing. However it's missing some sync point to pass. 
The correct usage/repro should be : 
```
import torch
import torch.multiprocessing as mp
import time

def producer(queue, event):
    while True:
        for _ in range(10):
            a = torch.ones(2,2).float().cuda()
            idx = torch.ByteTensor([[0, 0], [0, 1]]).cuda()

            queue.put(a)
            queue.put(idx)
            event.wait()
            event.clear()
        time.sleep(1000)
        return

def consumer(queue, event):
    while True:
        for _ in range(10):
            idx = queue.get()
            temp = queue.get()
            print("CONSUMER ", idx)
            print("CONSUMER ", temp)
            del idx
            del temp
            event.set()


if __name__ == '__main__':
    mp.set_start_method('spawn')

    queue = mp.Queue()
    queue2 = mp.Queue()

    event = mp.Event()
    p = mp.Process(target=producer, args=(queue, event))
    c = mp.Process(target=consumer, args=(queue, event))
    p.start()
    c.start()

    time.sleep(10)

    p.join()
    c.join()
```
Note that we added mp.event so that `a` and `idx` don't go out of scope (destroyed) before consumer get to them.

**Comment by ezyang** [comment]
One could make the case that this is really bad user experience. I certainly would. A simple improvement we could do is associate allocations with epochs, so that we don't confuse a reallocation of the same address the second time around. A more robust improvement might be to make cuda IPC shared ownership across processes, but we'd need to build out some fairly sophisticated machinery for distributed refcounting, which might not be worth it.

**Comment by hyperfraise** [comment]
This si the output of the correct usage mentionned above :

**Comment by hyperfraise** [comment]
I downgraded to the stable release of 1.0 and it works :s

**Comment by ailzhang** [comment]
@hyperfraise I just pulled the latest master and the script still runs fine. How did you install the nightly btw?

**Comment by hyperfraise** [comment]
By the time I used these options on the install command generator on pytorch.org

Preview (Nightly)
Linux
Pip
Python 3.7
10.0

But it does work on master today, so I'm guessing some of you guys were intentionnally fixing it by the time.

**Comment by taomo** [comment]
> > Have same issue as kintaat on 0.4.1 and same issue as alizhang on master
> 
> I have this too, on the same version, will try to create another conda environment to check if the nightly build has this issue.
> 
> Nighlty reports this for the same code:
> "RuntimeError: Cowardly refusing to serialize non-leaf tensor which requires_grad, since autograd does not support crossing process boundaries. If you just want to transfer the data, call detach() on the tensor before serializing (e.g., putting it on the queue)."
> 
> Much more understandable mesage, and funny too.
> At least I can work around this now.

I have the same issue,
ubuntu 18
python 3.6
cuda 9.2
pytorch 1.4
If I use cpu ,NO ERROR.
If I use gpu:
RuntimeError: Cowardly refusing to serialize non-leaf tensor which requires_grad, since autograd does not support crossing process boundaries.  If you just want to transfer the data, call detach() on the tensor before serializing (e.g., putting it on the queue).
anyone can help me. Thank you very much.
