### ISSUE TITLE
torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(FrozenDict) __contains__ [ConstantVariable(str)] {}

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#114202]
### 🐛 Describe the bug

Found in https://github.com/huggingface/diffusers/issues/4731

### Versions

Not sure if still present on main

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @bdhirsh @zou3519 @aakhundov

**Comment by anijain2305** [comment]
This the frozenDict link - https://github.com/google/flax/blob/main/flax/core/frozen_dict.py

**Comment by yanboliang** [comment]
This is not valid issue anymore, Dynamo can inline ````FrozenDict.__contains__``` properly and no graph break.
