### ISSUE TITLE
Tracing per-param sharding FSDP

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#114286]
### 🐛 Describe the bug

I hacked through a prototype that does this, there are a few major gaps, which I will file issues for.

This is what the model looks like:

https://www.internalfb.com/phabricator/paste/view/P887535790

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @wanchaol @fduwjj @wz337 @kiukchung @d4l3k @lucasllc @tianyu-l

**Comment by anijain2305** [comment]
Closing this issue. @yf225 Please open a new tracker with the current issues.

**Comment by anijain2305** [comment]
Reopening - did not realize this was a tracker itself.

**Comment by yf225** [comment]
Tracing per-param sharding FSDP by itself is done (unit test: https://github.com/pytorch/pytorch/blob/544f950d14e8ce4da0e592d9a3faac349e718151/test/distributed/_composable/fsdp/test_fully_shard_compile.py#L408), closing this issue.
