### ISSUE TITLE
Tracing per-param sharding FSDP: Tensor keys in dicts over-rely on `specialized_value`, potentially soundness bug

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#114291]
### 🐛 Describe the bug

parent: https://github.com/pytorch/pytorch/issues/114286

`specialized_value` is detected upfront, and if a key does not have it, we can't use it as a key. `specialized_value` is weirdly opinionated about parameters, and weirdly opinionated about initial example value instead of tracking the value as it goes through trace.

```
should_specialize = options.pop("should_specialize", False)
        if is_parameter or should_specialize:
            specialized_value = initial_example_value
```

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @kiukchung @lucasllc @d4l3k

**Comment by masnesral** [comment]
@yf225 I'm helping scrub old issues this week. This one hasn't had any action for a while; is it still relevant?

**Comment by yf225** [comment]
Not seeing this issue anymore, I think we can close it for now.
