### ISSUE TITLE
Tracing per-param sharding FSDP: Dynamo tracing weakrefs

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#114288]
### 🐛 Describe the bug

Parent task:  https://github.com/pytorch/pytorch/issues/114286

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by awgu** [comment]
I removed weakref from the implementation, so weakref handling can be separate.

**Comment by anijain2305** [comment]
Dynamo can support weakref tracing now. Closing for now. But feel free to reopen.
