### ISSUE TITLE
Align on the minimum supported Linux version (CentOS 7 is EOL in july 2024)

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#114287]
Align on the minimum supported Linux version (CentOS 7 is EOL in july 2024)

CUDA 13 will not support CentOS 7. 

Are we moving to RH Enterprise 8 or 9 ? Need to be established. 
Target ETA for 2.4 or 2.5 PyTorch release

cc @malfet @ptrblck

**Comment by vlad-penkin** [comment]
@atalman,

CentOS 7 has reached EOL on June 30, 2024. What are the current plans for CentOS 7 support in the PyTorch 2.5 release?

cc: @malfet @ptrblck
