### ISSUE TITLE
Tracing per-param sharding FSDP: Streams, Stream reconstruction 

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#114289]
### 🐛 Describe the bug

parent task https://github.com/pytorch/pytorch/issues/114288

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @kiukchung @lucasllc @d4l3k

**Comment by masnesral** [comment]
[issue scrubbing] @anijain2305 I can't figure out what this issue entails with just a title. Do you happen to have any context?

**Comment by yf225** [comment]
We choose to ignore user-specified streams in FSDP2 when tracing through it (and instead rely on Inductor passes to re-achieve compute-comm overlap). We can close this issue.
