### ISSUE TITLE
Tracing per-param sharding FSDP: RemovableHandle -> RemovableHandleVariable 

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#114290]
### 🐛 Describe the bug

Parent: https://github.com/pytorch/pytorch/issues/114286

One problem we have is that we can make RemovableHandleVariable just fine, but we don't do a good job of handling it if we found one made outside of the compile region. Should be pretty easy to do. 

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @kiukchung @lucasllc @d4l3k @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
Just out of curiosity, what is the link with autograd here?

**Comment by masnesral** [comment]
[issue scrubbing] @yf225, is this still relevant?

**Comment by yf225** [comment]
It's not currently blocking Traceable FSDP2 and I think we can close it.
