### ISSUE TITLE
caffe2 build failed at 82%

### ISSUE THREAD

**Issue by jaggernaut07** [pytorch/pytorch#11436]
[ 86%] Built target gloo_test_cuda
/home/shreyas/dens/pytorch/third_party/gloo/gloo/test/send_recv_test.cc: In lambda function:
/home/shreyas/dens/pytorch/third_party/gloo/gloo/test/send_recv_test.cc:158:9: error: ‘sort’ is not a member of ‘std’
         std::sort(output.begin(), output.end());
         ^
In file included from /usr/include/gtest/gtest-param-test.h:193:0,
                 from /usr/include/gtest/gtest.h:62,
                 from /home/shreyas/dens/pytorch/third_party/gloo/gloo/test/base_test.h:12,
                 from /home/shreyas/dens/pytorch/third_party/gloo/gloo/test/broadcast_test.cc:15:
/usr/include/gtest/internal/gtest-param-util-generated.h: In instantiation of ‘testing::internal::ValueArray1<T1>::operator testing::internal::ParamGenerator<T>() const [with T = long unsigned int; T1 = int]’:
/usr/include/gtest/internal/gtest-param-util-generated.h:4894:47:   required from ‘testing::internal::CartesianProductHolder4<Generator1, Generator2, Generator3, Generator4>::operator testing::internal::ParamGenerator<std::tuple<T1, T2, T3, T4> >() const [with T1 = int; T2 = int; T3 = long unsigned int; T4 = std::function<std::unique_ptr<gloo::Algorithm>(std::shared_ptr<gloo::Context>&, std::vector<float*>, long unsigned int, int, int)>; Generator1 = testing::internal::ValueArray1<int>; Generator2 = testing::internal::ValueArray1<int>; Generator3 = testing::internal::ValueArray1<int>; Generator4 = testing::internal::ValueArray1<std::function<std::unique_ptr<gloo::Algorithm>(std::shared_ptr<gloo::Context>&, std::vector<float*>, long unsigned int, int, int)> >]’
/home/shreyas/dens/pytorch/third_party/gloo/gloo/test/broadcast_test.cc:114:1:   required from here
/usr/include/gtest/internal/gtest-param-util-generated.h:82:70: error: could not convert ‘testing::ValuesIn(ForwardIterator, ForwardIterator) [with ForwardIterator = const int*; typename testing::internal::IteratorTraits<Iterator>::value_type = int](((&((const testing::internal::ValueArray1<int>*)this)->testing::internal::ValueArray1<int>::v1_) + 4u))’ from ‘testing::internal::ParamGenerator<int>’ to ‘testing::internal::ParamGenerator<long unsigned int>’
   operator ParamGenerator<T>() const { return ValuesIn(&v1_, &v1_ + 1); }
                                                                      ^
gloo/test/CMakeFiles/gloo_test.dir/build.make:230: recipe for target 'gloo/test/CMakeFiles/gloo_test.dir/send_recv_test.cc.o' failed
make[2]: *** [gloo/test/CMakeFiles/gloo_test.dir/send_recv_test.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
gloo/test/CMakeFiles/gloo_test.dir/build.make:158: recipe for target 'gloo/test/CMakeFiles/gloo_test.dir/broadcast_test.cc.o' failed
make[2]: *** [gloo/test/CMakeFiles/gloo_test.dir/broadcast_test.cc.o] Error 1
CMakeFiles/Makefile2:327: recipe for target 'gloo/test/CMakeFiles/gloo_test.dir/all' failed
make[1]: *** [gloo/test/CMakeFiles/gloo_test.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 libshm gloo c10d THD'
 ****

**I am on an ubuntu anaconda 2.7 python environment. CUDA 8.0 CUDNN 6.0 i7 gtx1080**

**Comment by cdluminate** [comment]
Missing the `algorithm` header? http://www.cplusplus.com/reference/algorithm/sort/

**Comment by soumith** [comment]
@jaggernaut07 `NO_TEST=1` environment flag before building will fix this.

**Comment by jaggernaut07** [comment]
Thanks for the help. But I got myself the docker image and got things done.
