### ISSUE TITLE
[AOTAutograd] Incorrect CSE aliasing while `requires_grad` meta differs

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#114344]
### 🐛 Describe the bug

As mentioned in https://github.com/pytorch/pytorch/issues/114338#issuecomment-1822267439, ViewAndMutationMeta is correct, but likley graph splitting messes up the aliasing information.

```python
def fn(x):
    with torch.no_grad():
        out = x + 1
    out2 = x + 1  # if not for differing meta, this can (and would) benefit from CSE
    # out2 = x + 2  # no error with this
    return out, out2

opt_fn = torch.compile(fn, backend="aot_eager")

inp = torch.ones(10, requires_grad=True)
opt_inp = torch.ones(10, requires_grad=True)

with torch.enable_grad():
    res = fn(inp)
    opt_res = opt_fn(opt_inp)

    assert all(id(a) != id(b) for a, b in zip(res, res[1:]))
    assert all(id(a) != id(b) for a, b in zip(opt_res, opt_res[1:]))  # fails

    assert all(res.requires_grad == ref for res, ref in zip(res, (False, True))) 
    assert all(res.requires_grad == opt.requires_grad for res, opt in zip(res, opt_res))   # also fails
```

It is a question for me whether one really can apply CSE regardless though. If a user decides to mutate one of the outputs but not the other, it'll be wrong.

### Versions

main

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @wconstab

**Comment by jon-chuang** [comment]
I think this has something to do with partitioning the graph, let me investigate. Graph splitting may not be meta aware and hence falsely alias. Or, it could simply be one of the passes (aliasing, deduping) that is occurring while splitting the graph.

**Comment by jon-chuang** [comment]
May have something to do with https://github.com/pytorch/pytorch/blob/bbdd9b059fa06404701f0d39abaae75ebab5d27f/torch/_functorch/aot_autograd.py#L800?

**Comment by ezyang** [comment]
@bdhirsh this just looks like a straight up bug (I also don't think it's CSE related?)

**Comment by bdhirsh** [comment]
Tested locally, it looks like https://github.com/pytorch/pytorch/pull/115294 fixes this problem too. That PR is in CI hell though, I need to come back to it and fix the broken tests.

**Comment by zou3519** [comment]
Still broken
