### ISSUE TITLE
Incorrect line in description of torch.frombuffer() method

### ISSUE THREAD

**Issue by mg104** [pytorch/pytorch#114345]
### 📚 The doc issue

As per the documentation on `frombuffer` method of `torch`:
```
torch.frombuffer(buffer, *, dtype, count=-1, offset=0, requires_grad=False) → [Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)
```
As per the documentation, either of the following conditions should be true:

```
1. count is a positive non-zero number, and the total number of bytes in the buffer is less than offset plus count times the size (in bytes) of [dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype).

2. count is negative, and the length (number of bytes) of the buffer subtracted by the offset is a multiple of the size (in bytes) of [dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype).
```

In condition number 1, it seems that it is wrongly written that `total number of bytes in the buffer is less than offset plus count times the size (in bytes) of dtype`. This should be changed to say that `total number of bytes in the buffer is **more** than offset plus count times the size (in bytes) of dtype`, so that when we read the buffer, there is ample data to read taking into account the `(offset + count) * dtype`, and we don't accidentally end up reading memory slots dedicated to something else than the buffer.

cc @svekars @carljparker @albanD

**Comment by albanD** [comment]
Thanks for the report, feel free to send a PR to fix the typo, thanks!

**Comment by mg104** [comment]
Hi, thanks for your reply. I would love to submit a PR. Please allow me some time though...Thanks

**Comment by mdevino** [comment]
Hello, I see this issue has been inactive and the type is still present in the [documentation](https://pytorch.org/docs/stable/generated/torch.frombuffer.html).
@mg104 Are you still working or this, or can I fix the typo?

**Comment by mdevino** [comment]
Hi @albanD. Since I've got no reply from the issue author, can I go ahead and submit a PR for this?

**Comment by albanD** [comment]
Sounds good!
