### ISSUE TITLE
When cuda graph captures multi-stream function, allocations are not serviced from the correct pool

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#114320]
Repro:
```
import torch
print(torch.__version__)

torch.cuda.empty_cache()
x=torch.randn(10240000, device="cuda")
y=torch.rand_like(x)
g=torch.cuda.CUDAGraph()
s0 = torch.cuda.Stream()
s1 = torch.cuda.Stream()
s0.wait_stream(torch.cuda.current_stream())
with torch.cuda.stream(s0):
  g.capture_begin()
  z = x+y
  with torch.cuda.stream(s1):
    s1.wait_stream(s0)
    w = z+y
  s0.wait_stream(s1)
  g.capture_end()
segments = torch.cuda.memory_snapshot()
for s in segments:
  print("POOL ID", s["segment_pool_id"], s["active_size"], s["total_size"], s["stream"])
```
produces
```
2.1.0+cu118
POOL ID (0, 0) 41943040 41943040 94099410458288 # w, not from pool, bug!
POOL ID (1, 0) 41943040 41943040 94099410421936 # z, from pool, ok
POOL ID (0, 0) 41943040 41943040 0 # x or y
POOL ID (0, 0) 1024 2097152 94099410421936 # something or other rng state related for graphs
POOL ID (0, 0) 41943040 41943040 0 # x or y
```
This is due to #96542 which changed the logic to determine if current allocation should be served from the pool. After #96542 only allocations happening on the original stream of the pool capture will be served from the pool. 
cc @mcarilli @ezyang @zdevito

**Comment by zdevito** [comment]
Even before the patch, we only call `cudaStreamBeginCapture` on the current stream when we start capturing. My assumption is that means that we only capture on that stream. Is that wrong?

**Comment by zdevito** [comment]
> When an event is recorded in a stream that is in capture mode, it results in a captured event. A captured event represents a set of nodes in a capture graph.

> When a captured event is waited on by a stream, it places the stream in capture mode if it is not already, and the next item in the stream will have additional dependencies on the nodes in the captured event. The two streams are then being captured to the same capture graph.

I guess cudaStreamBeginCapture actually means, begin capture on this stream. If there are waits that happen between this stream and others, they become capturing as well.  We do other management of pools related to the stream it is on. Maybe we should change it to `std::function<void()> beginAllocateToPool(std::function<std::optional<mempoolId()>> callback)`, where `callback` just decides where to place the allocation, and the function it returns uninstalls the callback. That would let CUDAGraphs do its own accounting for where to put things and it can query the streams there.

**Comment by ngimel** [comment]
I think (asked in slack to confirm) that `cudaStreamGetCaptureInfo` used previously correctly tracks if capture switches to another stream (as the quote from your previous comment implies), so (again, I think), previous logic was correct.
