### ISSUE TITLE
Support builtin round in torch.compile with dynamic shapes

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#114310]
### 🚀 The feature, motivation and pitch

Per title. This is listed under "Not Supported **Yet**" (emphasis mine) in the [documentation](https://pytorch.org/docs/main/generated/exportdb/index.html#not-supported-yet).

### Alternatives

Use the `math.floor(x + 0.5) == round(x)` workaround

### Additional context

In TorchVision we are using `round` in multiple places. Being forced to use the workaround above to avoid graph breaks will lower our code quality.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by ezyang** [comment]
This should also be relatively easy to fix

**Comment by ezyang** [comment]
Oh actually it's coming back to me now... round is kind of annoying because we don't know if you're rounding up or down...

**Comment by lezcano** [comment]
the math.floor trick from the OP should make implementing this reasonably straightforward
