### ISSUE TITLE
[PT2] Compile Cold Start - Async JIT compile with Eager fallback

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#114346]
### 🚀 The feature, motivation and pitch

Not sure if this has been discussed before, but this mitigates the cold start problem (though may not work for e.g. DDP which also want graph splitting)

Motivation: https://github.com/pytorch/pytorch/issues/114206

As opposed to cacheing, one can also rely on eager fallback until compiled artifact is installed and ready. Unfortunately, this is hard to achieve without a major refactor that queues up compilation jobs on different ~~threads~~ processes. If we lived in a multithreaded world, this would still be feasible. But python is still single threaded. (Though, do per-subinterpreter GIL available in 3.12 help with this?)

Thankfully, it would be feasible to do this if one actually had implemented Dynamo tracing cache / AOTAutograd cacheing. One then just runs an equivalent job on background process, while falling back on eager. Then, we periodically check the cache, and we can then recover a full compiled artifact from the cache in minimal time.

Other pathways to achieving this async JIT may also exist.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by ezyang** [comment]
We are fairly negative about this because of the nondeterminism it can introduce (at some unpredictable later iteration point, your numerics suddenly change. Sounds like fun debugging.)

**Comment by jon-chuang** [comment]
> at some unpredictable later iteration point, your numerics suddenly change

Why wouldn't this be guarded upon? If there is a guard failure, one can then fallback on eager.

**Comment by ezyang** [comment]
The point is that at some point in the future, when the async compile finished, the guard would no longer fail, and then your numerics would silently change

**Comment by jon-chuang** [comment]
Are you saying discrepancies between eager and compiled?

**Comment by ezyang** [comment]
yep

**Comment by isidentical** [comment]
This is something that would be really awesome for serverless ML inference scene where machines scale up and down, and with each machine already spending a decent amount of time (~1 to 10 seconds) loading the models from scratch; holding off the inference until compilations complete for various batch sizes is basically a no-go until the demand is extremely high. Which causes us to leave performance on the table. 

I do understand why it being not really fond of, but for use cases where we don't have a pre determined set of inference servers and any model can be run at any time, at least tracing in the background while providing eager answers and then using that trace generating a compiled version of the module would be a perfect match!

**Comment by jon-chuang** [comment]
@isidentical I have a solution that does not involve changing how torch does tracing, we can chat offline about it.

**Comment by ezyang** [comment]
The better fix for this situation is to not repeatedly recompile the same model on every scale up, this is on the roadmap for the next year.

**Comment by masnesral** [comment]
[issue scrubbing] @ezyang based on your comments, sounds like we should close this?
