### ISSUE TITLE
element_wise mean loss doesn't work in 0.4.1

### ISSUE THREAD

**Issue by ericwang385** [pytorch/pytorch#11437]
when using MSELoss in 0.4.1
finds that 
`tensor(2323865.5000, device='cuda:0', grad_fn=<SumBackward0>)`
the value of the loss is extremely large also the grad_fn=SumBackward
which should be grad_fn=MeanBackward after element_wise mean
<img width="808" alt="2018-09-10 12 29 22" src="https://user-images.githubusercontent.com/24954432/45266737-5c34f700-b492-11e8-9144-4be5913fcdbc.png">
where get_enum returns a number rather than a string 'elementwise_mean'
<img width="551" alt="2018-09-10 12 42 48" src="https://user-images.githubusercontent.com/24954432/45266857-87204a80-b494-11e8-90a4-87212d4b262d.png">
<img width="652" alt="2018-09-10 12 08 32" src="https://user-images.githubusercontent.com/24954432/45266751-930b0d00-b492-11e8-922e-27a7784f30e1.png">
then bug occurs when _pointwise_loss try to compare reduction with 'elementwise_mean'
seeing that this bug already solved in the master branch
<img width="802" alt="2018-09-10 12 08 15" src="https://user-images.githubusercontent.com/24954432/45266778-0745b080-b493-11e8-9777-d653eb9c59cd.png">

I was wondering if you guys can cherry pick this fix to the stable 0.4.1 branch, or gives us another stable version like 0.4.2 or something

**Comment by SsnL** [comment]
Even if this is cherry picked, new binaries would need to be built and released, and it would make most sense to bump the version number in that case. So we will just fold this in the next release.
