### ISSUE TITLE
[inductor][cpu]pyhpc_equation_of_state performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#114489]
pyhpc_equation_of_state single thread performance regression in 2023-11-15
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>shape</th>
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>static</td>
      <td>pyhpc_equation_of_state</td>
      <td>1</td>
      <td>14.52048</td>
      <td>0.000068334</td>
      <td>0.000992242480319999</td>
      <td>1</td>
      <td>19.168862</td>
      <td>0.000059365</td>
      <td>0.00113795949263</td>
      <td>0.76</td>
      <td>1.15</td>
      <td>0.87</td>
    </tr>
    <tr>
      <td>dynamic</td>
      <td>pyhpc_equation_of_state</td>
      <td>1</td>
      <td>12.973086</td>
      <td>0.0000785899999999999</td>
      <td>0.00101955482874</td>
      <td>1</td>
      <td>18.825686</td>
      <td>0.000061129</td>
      <td>0.001150795359494</td>
      <td>0.69</td>
      <td>1.13</td>
      <td>0.78</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">

SW | Nightly   commit | Main   commit
-- | -- | --
Pytorch | a5a4048 | 6f44090
Torchbench | / | 7617d3f5
torchaudio | 475b6ae | ede4309
torchtext | 142d029 | 45e4b8c
torchvision | 8636bf3 | 4ac707a
torchdata | eb9bf61 | d76d92c
dynamo_benchmarks | e6efc29 | /

</body>

</html>

Repro:

[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)

bash inductor_single_run.sh single inference performance torchbench pyhpc_equation_of_state float32 first static/dynamic default

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/7fb09b804b8e5ce3209ba9f7707ec5f3c1c11681

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by zxd1997066** [comment]
cc @WeizhuoZhang-intel @chuanqi129

**Comment by Le-Zheng** [comment]
Hi @bdhirsh we found commit https://github.com/pytorch/pytorch/commit/7fb09b804b8e5ce3209ba9f7707ec5f3c1c11681 cause the performance regression issue. Could you please help to take a look?

**Comment by leslie-fang-intel** [comment]
Hi @bdhirsh, could you kindly help to take a look?

**Comment by leslie-fang-intel** [comment]
From the latest FP32 Single Thread Static test report: https://github.com/pytorch/pytorch/issues/93531#issuecomment-2146026243
```
|     pyhpc_equation_of_state     |    1    | 22.286412 |
```

From the latest FP32 Single Thread Dynamic test report: https://github.com/pytorch/pytorch/issues/93531#issuecomment-2146030562

```
|     pyhpc_equation_of_state     |    1    | 21.986923 |
```
