### ISSUE TITLE
[inductor][cpu]fbnetc_100 AMP single thread performance regression 

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#114472]
fbnetc_100 AMP single thread performance regression in 2023-11-19
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>fbnetc_100</td>
      <td>1</td>
      <td>0.251723</td>
      <td>0.071660478</td>
      <td>0.0180385905035939</td>
      <td>9.2784</td>
      <td>1</td>
      <td>3.905198</td>
      <td>0.004782675</td>
      <td>0.01867729284465</td>
      <td>11.2002</td>
      <td>0.06</td>
      <td>1.04</td>
      <td>0.07</td>
      <td>1.21</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>6f045ad</td>
      <td>8705396</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>7617d3f5</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>e6efc29</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>ffbbebb9</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+git85ee879</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.16.0a0+8636bf3</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+142d029</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+475b6ae</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+eb9bf61</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
    </tr>
  </tbody>
</table><p>image: docker pull ccr-registry.caas.intel.com/pytorch/pt_inductor:2023_11_19_static_default_local</p>

Repro

[inductor_single_run.sh ](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
`bash inductor_single_run.sh single inference performance timm_models fbnetc_100 amp first static default 0`

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/ca5f6f7af36cbc55284e65018fbda1c5653f32b1

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by zxd1997066** [comment]
cc @WeizhuoZhang-intel @chuanqi129

**Comment by Le-Zheng** [comment]
@malfet we found commit https://github.com/pytorch/pytorch/commit/ca5f6f7af36cbc55284e65018fbda1c5653f32b1 cause the performance regression issue. Could you please help to take a look?

**Comment by leslie-fang-intel** [comment]
https://github.com/pytorch/pytorch/commit/ca5f6f7af36cbc55284e65018fbda1c5653f32b1 is not even cpu related. @chuanqi129 @zxd1997066 are we sure that's the right guilty commit?

**Comment by zxd1997066** [comment]
[timm_models-fbnetc_100-inference-amp-static-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13455846/timm_models-fbnetc_100-inference-amp-static-default-performance-single-drop_guilty_commit.log)
attached the bisect search log

**Comment by jgong5** [comment]
@zxd1997066 Can we confirm the regression manually about the guilty commit?

**Comment by chuanqi129** [comment]
> [timm_models-fbnetc_100-inference-amp-static-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13455846/timm_models-fbnetc_100-inference-amp-static-default-performance-single-drop_guilty_commit.log) attached the bisect search log

According to this git bisect search log, the original perf drop issue is too large, and we use 1.1 as the perf_ratio condition, so may it caused the search went into a wrong path. We have relaunched the guilty search with a bigger perf_ratio as criteria, will update results later.

**Comment by jgong5** [comment]
Assign to @chuanqi129 to confirm the guilty commit first.

**Comment by malfet** [comment]
> we found commit [ca5f6f7](https://github.com/pytorch/pytorch/commit/ca5f6f7af36cbc55284e65018fbda1c5653f32b1) cause the performance regression issue. Could you please help to take a look?

@Le-Zheng are you running tests on MacOS? If not, I'm 100% certain that Linux-x86 binary should be identical as the one produced from the commit before.

**Comment by chuanqi129** [comment]
I have enlarge the threshold to re-searched the guilty commit for this issue, add the result is 2971bdd6fcca08530a340ae03a752ce614d4c758, which same with https://github.com/pytorch/pytorch/issues/114468. Attached new search log 
[timm_models-fbnetc_100-inference-amp-static-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13460987/timm_models-fbnetc_100-inference-amp-static-default-performance-single-drop_guilty_commit.log)

I think we can close this one, and track this issue into #114468. 

cc: @malfet @jgong5 @leslie-fang-intel @Le-Zheng @zxd1997066

**Comment by leslie-fang-intel** [comment]
Thanks Chuanqi, let's also track it in https://github.com/pytorch/pytorch/issues/114468. Please help to update the new issues description and your summary.
