### ISSUE TITLE
CUDA error: an illegal memory access was encountered for specific tensor size and on V100

### ISSUE THREAD

**Issue by alreadytaikeune** [pytorch/pytorch#114463]
### 🐛 Describe the bug

Consider the following code snippet:
```python
import torch
batch_size=191
kernel_size=1
data = torch.randn([batch_size, 3072, 299], dtype=torch.float, requires_grad=True).to("cuda:0")
net = torch.nn.Conv1d(3072, 3072, kernel_size=kernel_size, padding=0, stride=1, dilation=1, groups=1).to("cuda:0")
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()
```

This sometimes causes a `CUDA error: an illegal memory access was encountered` depending on the GPU used and the batch_size and kernel_size parameters. For all my tests I use the same docker image with the same cuda and cudnn installations.

- torch 1.12+cu116, P100 GPU, driver 535.104.12: No issue whatsoever, never
- torch 1.12+cu116, V100 GPU, driver 460.32.03: Illegal memory
- torch 1.12+cu116, V100 GPU, driver 460.32.03, batch_size=192: No error
- torch 1.12+cu116, V100 GPU, driver 460.32.03, batch_size=191, kernel_size=2: No error
- torch 1.12+cu116, V100 GPU, driver 535.104.12: Illegal memory
- torch 1.12+cu116, V100 GPU, driver 535.104.12, batch_size=192: No error
- torch 1.12+cu116, V100 GPU, driver 535.104.12, batch_size=191, kernel_size=2: No error
- torch 2.1, V100 GPU, driver 535.104.12: No error whatsoever

So it seems like there’s an issue that’s specific to V100 when torch is older than version 2 (probably related to a difference in cuda)

### Versions

I tested with multiple versions, see the description.

cc @csarofeen @ptrblck @xwang233

**Comment by malfet** [comment]
Thank you for reporting, this is indeed interesting (can you please include cuda version torch-2.1 was build with? Or the one from PyPI was used?  
In any case, it feels like GPU architecture + CuDNN version is at fault (there was an old issue but I can not find it right now)

So closing the issue as everything works fine right now. Please do not hesitate to open a new one if you discover a problem with PyTorch-2.1

**Comment by alreadytaikeune** [comment]
Hi, thank you for looking into this. It was the default version installed from the registry so `2.1.1+cu121`.
