### ISSUE TITLE
batch_size to be true, but got false

### ISSUE THREAD

**Issue by toshiouchi** [pytorch/pytorch#114459]
### 🐛 Describe the bug

MultiheadAttention under model.eval() and with torch.no_grad() 

code:

self.self_att = nn.MultiheadAttention(n_state, n_head, batch_first = True)

target_att, _ = self.self_att(x, x, x, attn_mask=mask1)

error:
RuntimeError: Expected attn_mask->sizes()[0] == batch_size to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

### Versions

Collecting environment information...
PyTorch version: 1.12.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.25.1-msvc1
Libc version: N/A

Python version: 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3000
DeviceID=CPU0
Family=205
L2CacheSize=1536
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3000
Name=Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ignite==0.4.10
[pip3] pytorch-lightning==1.7.7
[pip3] torch==1.12.0
[pip3] torchaudio==2.0.2
[pip3] torchinfo==1.7.1
[pip3] torchmetrics==0.10.0
[pip3] torchsummaryX==1.3.0
[pip3] torchvision==0.15.2
[pip3] torchviz==0.0.2
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-ignite            0.4.10                   pypi_0    pypi
[conda] pytorch-lightning         1.7.7                    pypi_0    pypi
[conda] torch                     1.12.0                   pypi_0    pypi
[conda] torchaudio                2.0.2                    pypi_0    pypi
[conda] torchinfo                 1.7.1                    pypi_0    pypi
[conda] torchmetrics              0.10.0                   pypi_0    pypi
[conda] torchsummaryx             1.3.0                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by malfet** [comment]
Does it reproduces if PyTorch-2.1 is used? (1.12 is somewhat old and lots of issues might have been solved already)

**Comment by toshiouchi** [comment]
Thanks, malfet. i upgrade pytorch from 1.12 to 2.1.1.  An error disappeared.

**Comment by toshiouchi** [comment]
An error disappeared, so i close.
