### ISSUE TITLE
[inductor][cpu]cspdarknet53 and tf_mixnet_l AMP single thread performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#114473]
cspdarknet53 and tf_mixnet_l AMP single thread performance regression in 2023-11-19
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>cspdarknet53</td>
      <td>1</td>
      <td>1.413691</td>
      <td>0.0568025939999999</td>
      <td>0.0803013159144539</td>
      <td>22.3313369999999</td>
      <td>1</td>
      <td>4.23474</td>
      <td>0.0200536859999999</td>
      <td>0.08492214625164</td>
      <td>29.545329</td>
      <td>0.33</td>
      <td>1.06</td>
      <td>0.35</td>
      <td>1.32</td>
    </tr>
    <tr>
      <td>tf_mixnet_l</td>
      <td>1</td>
      <td>0.533202</td>
      <td>0.075387925</td>
      <td>0.04019699238585</td>
      <td>66.916105</td>
      <td>1</td>
      <td>1.764381</td>
      <td>0.022205099</td>
      <td>0.039178254778719</td>
      <td>88.468904</td>
      <td>0.3</td>
      <td>0.97</td>
      <td>0.29</td>
      <td>1.32</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>6f045ad</td>
      <td>8705396</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>7617d3f5</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>e6efc29</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>ffbbebb9</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+git85ee879</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.16.0a0+8636bf3</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+142d029</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+475b6ae</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+eb9bf61</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
    </tr>
  </tbody>
</table><p>image: docker pull ccr-registry.caas.intel.com/pytorch/pt_inductor:2023_11_19_static_default_local</p>

Repro

[inductor_single_run.sh ](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
`bash inductor_single_run.sh single inference performance timm_models cspdarknet53/tf_mixnet_l amp first static default 0`

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/1d9a7f9e438a6e01cab0e8447e12c6efc59c7710

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by zxd1997066** [comment]
cc @WeizhuoZhang-intel @chuanqi129

**Comment by Le-Zheng** [comment]
Hi @mlazos we found commit https://github.com/pytorch/pytorch/commit/1d9a7f9e438a6e01cab0e8447e12c6efc59c7710 cause the performance regression issue. Could you please help to take a look?

**Comment by leslie-fang-intel** [comment]
@mlazos could you help to take a look of this issue?

**Comment by leslie-fang-intel** [comment]
Hi @mlazos, could you kindly help to take a look?

**Comment by leslie-fang-intel** [comment]
From the latest report: https://github.com/pytorch/pytorch/issues/93531#issuecomment-2146146604

AMP single core single thread test case:
```
|          cspdarknet53           | 1  | 4.592903 |
|           tf_mixnet_l           | 1  | 2.391051 |
```
