### ISSUE TITLE
[inductor][cpu]swin_base_patch4_window7_224 AMP single thread performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#114488]
swin_base_patch4_window7_224 AMP single thread performance regression in 2023-11-19
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>swin_base_patch4_window7_224</td>
      <td>1</td>
      <td>1.242732</td>
      <td>0.114789509</td>
      <td>0.142652596098588</td>
      <td>62.26799</td>
      <td>1</td>
      <td>1.432922</td>
      <td>0.10091167</td>
      <td>0.14459855199974</td>
      <td>70.679807</td>
      <td>0.87</td>
      <td>1.01</td>
      <td>0.88</td>
      <td>1.14</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>6f045ad</td>
      <td>8705396</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>7617d3f5</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>e6efc29</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>ffbbebb9</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+git85ee879</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.16.0a0+8636bf3</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+142d029</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+475b6ae</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+eb9bf61</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
    </tr>
  </tbody>
</table><p>image: docker pull ccr-registry.caas.intel.com/pytorch/pt_inductor:2023_11_19_static_default_local</p>

Repro

[inductor_single_run.sh ](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
`bash inductor_single_run.sh single inference performance timm_models swin_base_patch4_window7_224 amp first static default 0`

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/a1c56df1f0c569e842bfcd365b417a907237330b

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by zxd1997066** [comment]
cc @WeizhuoZhang-intel @chuanqi129

**Comment by Le-Zheng** [comment]
Hi @jgong5 we found commit https://github.com/pytorch/pytorch/commit/a1c56df1f0c569e842bfcd365b417a907237330b cause the performance regression issue. Could you please help to take a look?

**Comment by jiayisunx** [comment]
Jiong's PR solves this performance regression issue.
