### ISSUE TITLE
torch.compile + subclasses: input is duplicate of another input

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#114401]
This is a tracker issue for https://github.com/pytorch/pytorch/blob/main/torch/_functorch/aot_autograd.py#L2829

cc @Chillee @ezyang @zou3519 @albanD @samdow @msaroufim @wconstab @anijain2305

**Comment by zou3519** [comment]
@bdhirsh is this still relevant? The link doesn't go anywhere

**Comment by bdhirsh** [comment]
This actually works, now that we moved input dedupping logic from AOTDispatcher into dynamo (which will automatically handle subclass inputs)
