### ISSUE TITLE
The behavior of Using different device in Autocast context 

### ISSUE THREAD

**Issue by FFFrog** [pytorch/pytorch#114458]
### 🐛 Describe the bug

Just like the code below, does this usage make sense?

```Python
a = torch.randn(3, 3) # CPU
with torch.cuda.amp.autocast(): # CUDA
    c = torch.mm(a, a)
```

```Python
Output:
torch.float32
```

I found several usages similar to the above in some tests, as follows:

https://github.com/pytorch/pytorch/blob/01366efcc9d2e6f42d2783a8436a5357895140f4/test/test_ops.py#L2065-L2069

It should fail when the context is `torch.cuda.amp.autocast`, but the reason why this test succeeds is here

https://github.com/pytorch/pytorch/blob/01366efcc9d2e6f42d2783a8436a5357895140f4/test/test_ops.py#L2165-L2169

The device in line 2165 is `cuda:0`, then the context was chosed to `torch.cpu.amp.autocast`, but the inputs and parameters are in `cuda`.

### Versions

Collecting environment information...
PyTorch version: 2.2.0a0+git0a33cf9
Is debug build: True
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: 15.0.5
CMake version: version 3.27.0
Libc version: glibc-2.35

Python version: 3.9.16 (main, May 15 2023, 23:46:34)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-73-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.128
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Tesla P4
GPU 1: Tesla P4

Nvidia driver version: 535.86.10
cuDNN version: Probably one of the following:
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn.so.8.9.4
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.4
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.4
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.4
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.4
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.4
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   42 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       2
Stepping:                        1
BogoMIPS:                        4599.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        2 MiB (8 instances)
L3 cache:                        90 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown

Versions of relevant libraries:
[pip3] botorch==0.8.5
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-coding==1.3.3
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] gpytorch==1.10
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] onnx==1.14.0
[pip3] onnxruntime-gpu==1.15.1
[pip3] onnxscript==0.1.0.dev20231109
[pip3] optree==0.9.1
[pip3] pytorch-lightning==2.0.6
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==2.2.0a0+git0a33cf9
[pip3] torchmetrics==1.0.1
[pip3] torchmultimodal-nightly==2023.7.31
[pip3] torchrl==0.1.1
[pip3] torchvision==0.16.0
[pip3] torchx==0.5.0
[pip3] triton==2.0.0.post1
[conda] botorch                   0.8.5                    pypi_0    pypi
[conda] gpytorch                  1.10                     pypi_0    pypi
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] optree                    0.9.1                    pypi_0    pypi
[conda] pytorch-lightning         2.0.6                    pypi_0    pypi
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     2.2.0a0+git0a33cf9          pypi_0    pypi
[conda] torchmetrics              1.0.1                    pypi_0    pypi
[conda] torchmultimodal-nightly   2023.7.31                pypi_0    pypi
[conda] torchrl                   0.1.1                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi
[conda] torchx                    0.5.0                    pypi_0    pypi
[conda] triton                    2.0.0.post1              pypi_0    pypi

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by jon-chuang** [comment]
No, it doesn't make sense. Do you want to contribute a fix? I would prefer if you added a bunch of asserts about type of the args, to ensure that the right thing is happening.

**Comment by FFFrog** [comment]
> No, it doesn't make sense. Do you want to contribute a fix? I would prefer if you added a bunch of asserts about type of the args, to ensure that the right thing is happening.

Sure, I will fix it, thank you for your comments.
