### ISSUE TITLE
[inductor][cpu]llama fp32 dynamic single thread performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#114494]
### 🐛 Describe the bug

llama fp32 dynamic single thread performance regression in 2023-11-12
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>llama</td>
      <td>1</td>
      <td>0.077641</td>
      <td>0.416671735</td>
      <td>0.032350810177135</td>
      <td>1</td>
      <td>0.315078</td>
      <td>0.102211727</td>
      <td>0.032204666519706</td>
      <td>0.25</td>
      <td>1</td>
      <td>0.25</td>
    </tr>
  </tbody>

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">

SW | Nightly   commit | Main   commit
-- | -- | --
Pytorch | 63a5a14 | ef49f61
Torchbench | / | 7617d3f5
torchaudio | 475b6ae | ede4309
torchtext | 142d029 | 45e4b8c
torchvision | 8636bf3 | 4ac707a
torchdata | eb9bf61 | d76d92c
dynamo_benchmarks | e6efc29 | /

</body>

</html>

Repro:

[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)

bash inductor_single_run.sh single inference performance torchbench llama float32 first dynamic default

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/1a361e4e9ff1a8dadd72c7301441cfb83d687f24

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by zxd1997066** [comment]
cc @WeizhuoZhang-intel @chuanqi129

**Comment by Le-Zheng** [comment]
@peterbell10 we found commit https://github.com/pytorch/pytorch/commit/1a361e4e9ff1a8dadd72c7301441cfb83d687f24 cause the performance regression issue. Could you please help to take a look?

**Comment by zxd1997066** [comment]
[torchbench-llama-inference-float32-dynamic-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13455991/torchbench-llama-inference-float32-dynamic-default-performance-single-drop_guilty_commit.log)
attached the bisect search log

**Comment by leslie-fang-intel** [comment]
duplicated issue as: https://github.com/pytorch/pytorch/issues/109874
