### ISSUE TITLE
__torch_dispatch__ + compile: extra guards

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#114405]
We don't actually create any additional guards for subclasses today. That would make code like this silently wrong:
```
import torch
import torch.utils._pytree as pytree
from torch.utils._python_dispatch import return_and_correct_aliasing

class SubclassTensor(torch.Tensor):
    @staticmethod
    def __new__(cls, a, constant):
        shape = a.shape
        kwargs = {}
        kwargs["strides"] = a.stride()
        kwargs["storage_offset"] = a.storage_offset()
        kwargs["device"] = a.device
        kwargs["layout"] = a.layout
        kwargs["requires_grad"] = a.requires_grad
        kwargs["dtype"] = a.dtype
        out = torch.Tensor._make_wrapper_subclass(cls, shape, **kwargs)
        return out

    def __init__(self, a, constant):
        self.a = a
        self.constant = constant

    def __repr__(self):
        a_repr = repr(self.a)
        return f"SubclassTensor({a_repr})"

    def __tensor_flatten__(self):
        return ["a"], (self.constant,)

    @staticmethod
    def __tensor_unflatten__(inner_tensors, meta):
        constant = meta[0]
        a = inner_tensors["a"]
        return SubclassTensor(a, constant)

    @classmethod
    def __torch_dispatch__(cls, func, types, args, kwargs):
        if kwargs is None:
            kwargs = {}
        biggest_constant = max([x.constant for x in pytree.tree_flatten(args)[0] if isinstance(x, SubclassTensor)])
        args_a = pytree.tree_map(lambda x: x.a if isinstance(x, SubclassTensor) else x, args)
        kwargs_a = pytree.tree_map(lambda x: x.a if isinstance(x, SubclassTensor) else x, kwargs)
        out_a = func(*args_a, **kwargs_a)
        out = pytree.tree_map(lambda x: SubclassTensor(x, biggest_constant) if isinstance(x, torch.Tensor) else x, out_a)

        if func == torch.ops.aten.mul.Tensor:
            out = out + out.constant

        return return_and_correct_aliasing(func, args, kwargs, out)



def f(x):
    return x * x

x = SubclassTensor(torch.ones(2), 3)
out = f(x)

# Different metadata on the subclass should cause a recompile
x2 = SubclassTensor(torch.ones(2), 4)
# ERROR: we should recompile here, instead of reusing the graph
out2 = f(x2)
# prints SubclassTensor(tensor([4., 4.]))
# should print SubclassTensor(tensor([5., 5.]))
print(out2)
```

A more real example is for DTensor (cc @ezyang @gchanan @zou3519 @kadeng @Chillee @albanD @samdow @msaroufim @wconstab @anijain2305 @wanchaol): in distributed inference, if we have graph inputs that are DTensors, we should guard on the DTensor metadata (the sharding spec) to make sure that we recompile if a user tries to run the same model with differently-sharded DTensors.

**Comment by jon-chuang** [comment]
Hmm, how can we canonicalize on the metadata? Would it be based on `unflatten`? I think this is easy.

Let me add it, we can add DTensor to the testing path.

**Comment by jon-chuang** [comment]
Hmm, there is a complication here. Not all `__tensor_unflatten__` ctx are constants. In particular, they might be symints (e.g. `NestedTensor['ragged_size']`)

**Comment by jon-chuang** [comment]
I've decided to ignore guarding on nestedtensor ctx/meta. Explained in incoming PR.

**Comment by jbschlosser** [comment]
Hey @jon-chuang, I've addressed this more extensively by removing the need to store `ragged_size` in the `ctx` for `NestedTensor`. My PR #114311 also adds guards for subclass `ctx`.

**Comment by bdhirsh** [comment]
@jon-chuang putting you as the owner since you have a PR out to guard on metadata already - I'm on the hook for reviewing it soon

**Comment by xmfan** [comment]
from triage reivew: maybe we can have a loud error if guards take a long time to add

**Comment by bdhirsh** [comment]
Also from composability: one problem is that any default guard we add risks being very slow (we have to default to python object equality), which will be a problem for DTensor. In the limit, we can ask the subclass to make their metadata representable in terms of cheap C++ guards. But in the short term, we can add a new dunder method that subclasses can optionally implement to define their own way to guard.

Also - I'm unassigning myself from this issue due to bandwidth. It's on my radar if nobody else is able to take it some time in the next few months.

**Comment by zou3519** [comment]
For some more context, I asked bdhirsh exactly what the plan was here. The response was:
- have dynamo run attrs, metadata = x.__tensor_flatten__() on each subclass grapharg that it sees, and add equality guards for the metadata
- these full equality guards might be slow/inflexible so we can also add some kind of __guard_metadata__ dunder method that subclasses can override to provide their own guard imlementation for their metadata

**Comment by mlazos** [comment]
FYI for anyone who needs this - I should have a PR out for this in the next couple, debugging it now.
