### ISSUE TITLE
Pytorch 0.1.11 on Linux x64, CUDA 8.0, Conda doesn't load

### ISSUE THREAD

**Issue by stepelu** [pytorch/pytorch#1144]
I having the following issue on import:

```
Traceback (most recent call last):
  File "./xxx", line 14, in <module>
    import torch
  File "/home/speluchetti/conda3/envs/py3env/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /home/speluchetti/conda3/envs/py3env/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PySlice_AdjustIndices
```

System info:

```
python -V
Python 3.6.0 :: Continuum Analytics, Inc.

conda -V
conda 4.3.11

uname -a
Linux xxx 4.4.0-67-generic #88-Ubuntu SMP Wed Mar 8 16:34:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

CUDA Driver Version: 375.39

pytorch: 0.1.11-py36_3cu80 soumith [cuda80]
```

I think this is the same issue mentioned here:
http://stackoverflow.com/questions/43104252/undefined-symbol-pyslice-adjustindices-when-importing-pytorch

**Comment by soumith** [comment]
this should now be fixed if you reinstall from conda using the same command.

**Comment by stepelu** [comment]
```
The following NEW packages will be INSTALLED:

    pytorch:     0.1.11-py360_4cu80 soumith [cuda80]
    torchvision: 0.1.8-py36_2       soumith

The following packages will be DOWNGRADED due to dependency conflicts:

    python:      3.6.1-0                    --> 3.6.0-0
```

I confirm it works now, I guess downgrading is the intended behavior.

**Comment by soumith** [comment]
i will fix the downgrading issue as well tomorrow. In python 3.6, sadly 3.6.0 and 3.6.1 aren't binary compatible. I am having to build separate binaries for 3.6.0 and 3.6.1

**Comment by stepelu** [comment]
I understand, thank you for your prompt fix!

**Comment by njsmith** [comment]
FYI, binaries built on 3.6.0 will work on all versions of 3.6.x.

This is the upstream bug: https://bugs.python.org/issue29943
