### ISSUE TITLE
Current master doesn't link against nvToolsExt

### ISSUE THREAD

**Issue by leomao** [pytorch/pytorch#11447]
## Issue description

I compile source from master with cuda 9.2.
`import torch` yields `undefined symbol: nvtxMarkA` error.
This symbol is used in `libtorch.so` (check via `nm -D lib/libtorch.so`)

It seems to be related to https://github.com/pytorch/pytorch/blob/560d6efd3a02a4314c6c506d6a977b1d875bc03c/torch/CMakeLists.txt#L338

After changing `CUDA_LIBRARIES` to `TORCH_CUDA_LIBRARIES`, `libtorch.so` is correctly linked against nvToolsExt and `import torch` works.

## System Info
- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source):
```
CC=gcc-7 \
CXX=g++-7 \
MAGMA_HOME=/opt/magma \                                                        
USE_CUDA=1 \                                                                   
CUDA_HOME=/opt/cuda \                                                          
USE_CUDNN=1 \                                                                  
CUDNN_LIB_DIR=/opt/cuda/lib64 \                                                
CUDNN_INCLUDE_DIR=/opt/cuda/include \                                          
NCCL_LIB_DIR=/opt/cuda/lib64 \                                                 
NCCL_INCLUDE_DIR=/opt/cuda/include \                                           
TORCH_NVCC_FLAGS="-Xfatbin -compress-all -D__CUDA_NO_HALF_OPERATORS__" \
python setup.py build
```
- OS: Arch Linux
- PyTorch version: master (560d6efd3a)
- Python version: 3.7
- CUDA/cuDNN version: 9.2.148 / 7.2.1
- GPU models and configuration: (Not relevant)
- GCC version (if compiling from source): 7.3.1
- CMake version: 3.12.1
- Versions of any other relevant libraries:
  - Intel MKL 2018.3.222
  - MAGMA 2.4

**Comment by soumith** [comment]
cc: @anderspapitto based on blame. We need to fix this before release.

**Comment by leomao** [comment]
Hi,
I have compiled the current master 76070fe7 and verified that the libraries are linked correctly.
Close this issue.

**Comment by deeponcology** [comment]
Hello, 
It seems there is a hardcoded path. When using CUDA 10.1 with the latest version of TorchLib on windows, I get the following exception. 

> Make Error in CMakeLists.txt:
  Imported target "torch" includes non-existent path

    "C:/Program Files/NVIDIA Corporation/NvToolsExt/include"

Thanks,
