### ISSUE TITLE
Missing packaging dependency in torch 2.1.x

### ISSUE THREAD

**Issue by sachahu1** [pytorch/pytorch#114591]
### 🐛 Describe the bug

Hi,
[torch.utils.tensorboard requires "packaging"](https://github.com/pytorch/pytorch/blob/fa1ccc34c4f65756bc50c3e3ab135c88b175b18c/torch/utils/tensorboard/__init__.py#L2C1-L3C1) to be installed but that dependency is [missing on torch 2.1.x](https://github.com/pytorch/pytorch/blob/v2.1.2-rc1/requirements.txt).

Here's some example code:
```python
from torch.utils.tensorboard import SummaryWriter
```

The links above point to a RC version of 2.1.2 but this is also the case for 2.1.1. Would it be possible to make a patch release to add the dependency?

### Versions

Python version: 3.9.16 (main, Dec  7 2022, 10:16:11)  [Clang 14.0.0 (clang-140[0.0.29.202](http://0.0.29.202/)
)] (64-bit runtime)
Python platform: macOS-13.6.1-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i5-7287U CPU @ 3.30GHz

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.1.1
[pip3] torchvision==0.16.1
[conda] Could not collect

**Comment by sachahu1** [comment]
Worth mentioning that the change is already on main so should just be missing a release.

**Comment by malfet** [comment]
@sachahu1 is this a new dependency (that tensorboard have added) or was it always missing?
Please note, that in main this was already reverted in favor of just vendoring `packaging.Version` class, see https://github.com/pytorch/pytorch/pull/114108

**Comment by sachahu1** [comment]
@malfet This looks like it's a torch dependency and is used to check the tensorboard package version. If `packaging` isn't going to be added to the torch dependencies then the code should probably be fixed to remove the missing dependency. 

Does seem like using `packaging.Version` for this use-case might be overkill if it isn't used elsewhere? I think removing the dependency from the code might be the preferred option.
