### ISSUE TITLE
Cant import caffe2.python

### ISSUE THREAD

**Issue by Sem-Kulish** [pytorch/pytorch#11453]
Hi, 
Is it still possible to build whl package with only Caffe2 without pytorch?
In installation [docs](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile) of caffe2 written that only thing that I need to build it is call python setup.py with FULL_CAFFE2=1 flag.
But according to [this](https://github.com/pytorch/pytorch/commit/802d21c8f4502b2ea6ff866bcaf5fef38c026546) commit, possibility of building caffe2 is deprecated or am I wrong? 

@oxygenxo, this will interest you :)

**Comment by ezyang** [comment]
It is deprecated. However, the Caffe2 mobile build still builds without (most) of PyTorch, and may be of interest.

**Comment by oxygenxo** [comment]
Hi @ezyang , thanks for the answer!
May be we just don't know something. We used to compile caffe2 with pytorch and onnx backends and got 3 separate wheels. Do you want to say that now pytorch wheel should include caffe2 as well? We're trying to build it on Ubuntu 16.04 without CUDA.

**Comment by soumith** [comment]
@oxygenxo yes. there is only a single wheel that includes pytorch bits and caffe2 bits

**Comment by Sem-Kulish** [comment]
@soumith thanks! But we currently have issue after installing pytorch. If I will try to import caffe2.python raises exception
```>>> from caffe2.python import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "path_to_lib/pytorch/caffe2/python/__init__.py", line 2, in <module>
   from caffe2.proto import caffe2_pb2
ImportError: cannot import name 'caffe2_pb2'```


Is it bug or documentation is outdated?

**Comment by orionr** [comment]
Hi @Sem-Kulish - thank you for the report! We should have a fix at https://github.com/pytorch/pytorch/pull/11517. Please verify this fixes your issue if you are able. Thanks.

**Comment by ezyang** [comment]
We haven't actually moved, we were testing it out. There's some residual CircleCI jobs hanging around but you can ignore them.
