### ISSUE TITLE
[BE / AOTAutograd] AOTAutograd should be refactored into smaller files with clear responsibilities

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#114548]
### 🚀 The feature, motivation and pitch

It has 5000+ loc with no reasonable organization about which part does what. It needs to be organized into e.g.
- analysis
- traced_function_transforms
- runtime_wrappers
- optimizations
- schemas (I.e. dataclasses, types)
- api
- utils
- functionalization
- dispatch

@bdhirsh @ezyang 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by jon-chuang** [comment]
Detailed list
### Analysis

### Tracing Wrappers / Source transformations
fn_prepped_for_autograd
create_functionalized_fn

### Logging utils
track_graph_compiling

### Dispatch
aot_dispatch_base/_graph
aot_dispatch_autograd/_graph

### functionalization
assert_functional_graph

**Comment by jon-chuang** [comment]
Migration plan:
1. Migrate initially to _aot_autograd subfolder
2. Migrate incrementally starting with subcomponents with the least code movement
3. When migration is complete, delete aotautograd.py and replace with folder aotautograd with init.py

**Comment by bdhirsh** [comment]
@jon-chuang a refactor for readability was a long time coming, thanks for trying to take it on :)

Before I read the PR's more closely - are they all purely code motion? Or are there any that are either:

(1) non-trivial rewriting of any components
(2) functionality changes

From a quick glance I see a lot of failing CI, so just wanted to double check

**Comment by jon-chuang** [comment]
The failing CI is from broken trunk. The top few layers of the stack I'll fix now.

**Comment by bdhirsh** [comment]
> There would mainly be a BC-breaking concern, but if you don't think these are too contentious, I'm also happy to just leave it in, and undo the renaming in a PR if it breaks some internal code etc.

Yep - I think the stack will probably be safer if you're able to arrange it so that there are no function renames (and you re-import everything into `aot_autograd.py` so the imports stay the same) in most of the stack, and have a final PR that removes the extra imports + does the renames (so we can land that with a bit more care)

**Comment by jon-chuang** [comment]
Sounds good, let me go that conservative route, will update here once done.

**Comment by jon-chuang** [comment]
Ready now @bdhirsh

**Comment by bdhirsh** [comment]
Closing since the relevant PR landed
