### ISSUE TITLE
Build LibTorch for Windows ARM64

### ISSUE THREAD

**Issue by kalaskarsanket** [pytorch/pytorch#114566]
Build LibTorch for Windows ARM64 on VS2022. The current focus is to produce builds through both APL and OpenBLAS. We want to accomplish below task in this ticket - 
1) Assess current status with APL
2) Create local build 
3) Create and run test (Test folder in PyTorch)

**Comment by malfet** [comment]
Sorry, what is APL?

**Comment by Blackhex** [comment]
@malfet  [Arm Performance Libraries](https://developer.arm.com/Tools%20and%20Software/Arm%20Performance%20Libraries)

**Comment by iremyux** [comment]
Closing this issue since we have a stable Libtorch build with APL and currently working on tests on Pytorch side. - related issues are created on our project backlog (PyTorch on Windows) as draft.

**Comment by ukc-work** [comment]
Is there any pre-compiled binaries available for libtorch for arm64-windows ? Or is there an option to build it natively from source code ?
