### ISSUE TITLE
Issues about the 1x1 conv in PyTorch

### ISSUE THREAD

**Issue by LiuXiangrui** [pytorch/pytorch#114549]
### 🐛 Describe the bug

Dear developer, I'm having trouble with PyTorch's 1x1 convolution. 

When I use PyTorch to build a 1x1 convolution and then use a for loop to iterate through all elements of the tensor, the result is different from the result generated directly using the forward method. Can you provide some insights?

Here is the test code:
```python
import torch
import torch.nn as nn
torch.backends.cudnn.deterministic = True

device = 'cuda'
M = 192
B = 3
H = 36
W = 48
a = torch.randn(B, 4 * M, H, W).to(device)

entropy_parameters = nn.Conv2d(in_channels=M * 4, out_channels=M * 2, kernel_size=1, stride=1, padding=0).to(device).eval()

b = entropy_parameters(a)  # direct forward

c = torch.zeros_like(b)  # for loop
for k in range(B):
    for h in range(H):
        for w in range(W):
            c[k:k + 1, :, h:h + 1, w:w + 1] = entropy_parameters(a[k:k + 1, :, h:h + 1, w:w + 1])

d = (b - c == 0).all()
error = b - c
g = torch.allclose(b, c)
print(d)
print(g)
```
And then I got the results like that:
```
tensor(False, device='cuda:0')
False
```

I'm so confused about the result because the direct forward and loop processing should be identical for the 1x1 convolution layer. I would like to ask for your help to provide me with some insights about this issue. Thanks a lot.

### Versions

Collecting environment information...
PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 专业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.28.0-rc4
Libc version: N/A

Python version: 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 531.14
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:

Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] pytorch-msssim==1.0.0
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchvision==0.16.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h6b88ed4_46357  
[conda] mkl-service               2.4.0           py311h2bbff1b_1  
[conda] mkl_fft                   1.3.8           py311h2bbff1b_0  
[conda] mkl_random                1.2.4           py311h59b6b97_0  
[conda] numpy                     1.26.0          py311hdab7c0b_0  
[conda] numpy-base                1.26.0          py311hd01c5d8_0  
[conda] pytorch                   2.1.0           py3.11_cuda12.1_cudnn8_0    pytorch
[conda] pytorch-cuda              12.1                 hde6ce7c_5    pytorch
[conda] pytorch-msssim            1.0.0                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.1.0                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @csarofeen @ptrblck @xwang233

**Comment by tringwald** [comment]
For me, the largest difference between `b` and `c` was `~3e-6`. Small errors like that are expected when dealing with floating point math.

**Comment by malfet** [comment]
Good old [TensorFloat](https://blogs.nvidia.com/blog/tensorfloat-32-precision-format/). Adding `torch.backends.cudnn.allow_tf32 = False` to your example, it will return True.

Also, please note, that even with tf32 enabled, the difference should be relatively small (though higher than full fp32 tolerance threshold)

P.S. In general, those kinds of questions should be discussed in https://discuss.pytorch.org/
