### ISSUE TITLE
[profiling] CUDA memory viz does not compose with `torch.compile`

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#114535]
### 🚀 The feature, motivation and pitch

https://pytorch.org/docs/stable/torch_cuda_memory.html is useful to understand memory allocations and their origin

However, it gives a blank result when used with `torch.compile`

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by anupambhatnagar** [comment]
@jon-chuang Can you please provide a repro for this issue?

**Comment by aaronenyeshi** [comment]
Closing as not reproducible.
