### ISSUE TITLE
Raise `torch._dynamo.config.accumulated_cache_size_limit` higher, or potentially just remove it altogether.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#114511]
### 🚀 The feature, motivation and pitch

We used to only have `cache_size_limit`, which basically says "given that we are compiling a frame, how many times are we willing to recompile it". One tricky thing about this is that it actually intermixed two different situations.

1. Unique callstack

```
mods = [MyMod() for _ in range(64)]
for mod in mods:
    x = torch.compile(mod)(x)
```

and 

2. identical callstack

```
for inp in [torch.randn(shape) for shape in range(64)]
    torch.compile(mod)(x)
```

In the first case, we presumably are willing to pay the cost of compiling each individual model (even though there's 64 of them). In the second case, we should probably give up.

This used to be set to `64`, which was a balance between not breaking situation 1 and not having too many excessive recompiles in situation 2. This was not perfect, and we would periodically have cases where `64` was too low for situation 1.

However, we recently-ish, we separated these two into `cache_size_limit (default of 8)` and `accumulated_cache_size_limit (default of 64)`. However, now that these two concepts are separated, I'm having a hard time imagining when we should ever stop recompiling for situation 1. Should we just raise it to a very high number? Or alternately, just remove it?

cc: @anijain2305 @voznesenskym @ezyang @jansel 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by Chillee** [comment]
See https://github.com/pytorch/pytorch/pull/114512

**Comment by jon-chuang** [comment]
In the former case, I guess user may try to compile submodules of a very deep model and then call them in sequence. But why not just compile the entire module?

**Comment by Chillee** [comment]
@jon-chuang There's a variety of reasons - perhaps they want to reduce compile time, perhaps they have something in the middle that causes graph breaks, etc.

But my main point is that in that case, they pretty much always want all submodules to be compiled.

**Comment by ezyang** [comment]
I think it is fine to make it very high. I think the accumulated limit is mostly useful as an alarm when something horribly wrong has happened and we are compiling way more things than you expected.

**Comment by anijain2305** [comment]
We can raise the `accumulated_cache_size_limit` to 128. As Ed mentioned, this limit is just a safeguard mechanism to prevent from really horrible recompilations.
