### ISSUE TITLE
Building v.0.4.1 from source

### ISSUE THREAD

**Issue by mkielak** [pytorch/pytorch#11454]
Hi,
I want to use pytorch with K10 gpus (sm30). To do that I need to compile it with sm30 support. I already compiled pytorch 0.5.0a and it's working but I've written some code that is working with 0.4.1 (other graphic card) and not working on 0.5.0a. Where can I find 0.4.1 source?

I cloned pytroch repo and ran
`git checkout v0.4.1`
build docker image but in python console I get
`>>> import torch`
`>>> print(torch.__version__)`
`0.5.0a0+a24163a`
I opened setup.py and version in this file equals 0.5.0a0+a24163a
I did the same with downloading 0.4.1 and 0.4.0 source from https://github.com/pytorch/pytorch/releases but just after download I opened setup.py and version is 0.5.0.
So which version did I build? 0.5.0 or 0.4.1?

**Comment by SsnL** [comment]
0.4.1 see https://github.com/pytorch/pytorch/issues/9926
