### ISSUE TITLE
_foreach_supported_types is a list type while it is used for `in` check of _default_to_fused_or_foreach method in optimizer.py

### ISSUE THREAD

**Issue by bruceSz** [pytorch/pytorch#114502]
### 🐛 Describe the bug

in optimizer.py:
under method _default_to_fused_or_foreach: 
`
_foreach_supported_types = [torch.Tensor, torch.nn.parameter.Parameter]
...

fused = use_fused and all(
        p is None or (type(p) in _foreach_supported_types and
                      p.device.type in fused_supported_devices and
                      torch.is_floating_point(p)) for p in params
    )
    foreach = not fused and all(
        p is None or (type(p) in _foreach_supported_types and
                      p.device.type in foreach_supported_devices) for p in params
    )
`
object `_foreach_supported_types ` is a two element list while it is mainly used for existence check.
Maybe change it to Set type will be more appropriate, as it should be faster in theory(should not be too much faster, for 2 elements size)
test code on my dev env.
'
import torch

def obj_in_check():
    l = [torch.Tensor, torch.nn.parameter.Parameter]
    s = set(l)

    list_time = timeit.timeit(lambda: torch.nn.parameter.Parameter in l, number=10000)
    print(f"List time: {list_time}")

    set_time = timeit.timeit(lambda: torch.nn.parameter.Parameter in s, number=10000)
    print(f"Set time: {set_time}")

    times = list_time / set_time

    print("List's execution time is {} times compared to that of set".format(times))
' 

results:
‘
List time: 0.0009401770075783134
Set time: 0.0008739969925954938
List's execution time is 1.0757211014951962 times compared to that of set
’

### Versions

branch: main 
commits: c4a22d6918b

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by janeyx99** [comment]
I'm going to close this issue due to minorness, but feel free to reopen if this has more significant impact than anticipated.
