### ISSUE TITLE
[gradcheck] RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by marvinfriede** [pytorch/pytorch#114536]
### 🐛 Describe the bug

I am testing gradients with `torch.autograd.gradcheck.gradcheck`. If I am setting the default device to my GPU with `torch.set_default_tensor_type("torch.cuda.FloatTensor")`, I get a device mismatch. The error only occurs in fast mode, not in slow mode. The problem comes from:

https://github.com/pytorch/pytorch/blob/0f5e24bda9450a89ba56d2fdd471f56d97fe4546/torch/autograd/gradcheck.py#L1785-L1787

It seems like the `Generator` is not given a device and uses the CPU. Similar issues also identified the `Generator` as the problem and solved it by simply passing "cuda" (e.g. [here](https://discuss.pytorch.org/t/distributedsampler-runtimeerror-expected-a-cuda-device-type-for-generator-but-found-cpu/103594)).

In gradcheck.py, however, one cannot access the generator, and it is also explicitly named "g_cpu". Is gradcheck in fast mode not meant to be run on GPU? Did I miss anything?

### Versions

I am running version 1.12.1, but since the offending piece of code is still the same in the current main branch, it should still be an issue.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by tringwald** [comment]
`torch.set_default_tensor_type` seems to now be deprecated in `torch==2.1.0`. With `torch.set_default_dtype()` and `torch.set_default_device()` I don't have any problems using `gradcheck()`. Do you have a small reproducer that causes the problem for you?

**Comment by marvinfriede** [comment]
The following fails for me, for 1.12.1 **and** 2.1.1.

```python
import torch
from torch.autograd.gradcheck import gradcheck

torch.set_default_tensor_type("torch.cuda.FloatTensor") # <2.0.0
# torch.set_default_device("cuda") # >2.0.0


x = torch.randn(3, dtype=torch.double, requires_grad=True)

def func(inp):
  return inp ** 2.0

assert gradcheck(func, x, fast_mode=True)
```

It works if I specify the device in the tensor.


<details>

<summary>Error trace for 2.1.1</summary>

```
/opt/miniforge3/envs/torch-latest/lib/python3.11/site-packages/torch/autograd/gradcheck.py:2051: in gradcheck
    return _gradcheck_helper(**args)
/opt/miniforge3/envs/torch-latest/lib/python3.11/site-packages/torch/autograd/gradcheck.py:2080: in _gradcheck_helper
    _gradcheck_real_imag(
/opt/miniforge3/envs/torch-latest/lib/python3.11/site-packages/torch/autograd/gradcheck.py:1482: in _gradcheck_real_imag
    gradcheck_fn(
/opt/miniforge3/envs/torch-latest/lib/python3.11/site-packages/torch/autograd/gradcheck.py:1863: in _fast_gradcheck
    all_v, all_u, all_u_dense = _make_vectors(
/opt/miniforge3/envs/torch-latest/lib/python3.11/site-packages/torch/autograd/gradcheck.py:1786: in _make_vectors
    ur = _vec_from_tensor(inp, g_cpu, True)
/opt/miniforge3/envs/torch-latest/lib/python3.11/site-packages/torch/autograd/gradcheck.py:1685: in _vec_from_tensor
    vec = torch.rand(x.numel(), generator=generator).to(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <torch.utils._device.DeviceContext object at 0x148b4b9b8510>, func = <built-in method rand of type object at 0x148bc2005aa0>, types = ()
args = (96,), kwargs = {'device': device(type='cuda'), 'generator': <torch._C.Generator object at 0x148b41a32010>}

    def __torch_function__(self, func, types, args=(), kwargs=None):
        kwargs = kwargs or {}
        if func in _device_constructors() and kwargs.get('device') is None:
            kwargs['device'] = self.device
>       return func(*args, **kwargs)
E       RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
```
</details>

**Comment by soulitzer** [comment]
> In gradcheck.py, however, one cannot access the generator, and it is also explicitly named "g_cpu". Is gradcheck in fast mode not meant to be run on GPU? Did I miss anything?

We always first use a cpu generator and then create random tensor on cpu, then use `.to` to move it to the correct device.
