### ISSUE TITLE
the work can be done but error : what(): Should never been called.

### ISSUE THREAD

**Issue by freshduer** [pytorch/pytorch#114576]
### 🐛 Describe the bug

pytorch: py2.1.0-cu12.2
when testing 'task=image_detection:models=faster_rcnn_R_50:forward_only_set=false:train_batchsizes=1:val_batchsizes=1:num_batches=10:data_name=imagenet:data_dir=/data2/coco_reduced' 'test_id=test_id:single=yes:single_set=100:ratio_control=no:ratio_control_set=0:data_storage=json'

### Versions

pytorch: py2.1.0-cu12.2
when testing 'task=image_detection:models=faster_rcnn_R_50:forward_only_set=false:train_batchsizes=1:val_batchsizes=1:num_batches=10:data_name=imagenet:data_dir=/data2/coco_reduced' 'test_id=test_id:single=yes:single_set=100:ratio_control=no:ratio_control_set=0:data_storage=json'

![image](https://github.com/pytorch/pytorch/assets/72605280/8ab7173d-4ed1-432a-9dcc-b7f88fc36efb)

![image](https://github.com/pytorch/pytorch/assets/72605280/6913982f-6d73-4856-9e42-6eabf492da44)

the intializer is destory..
<img width="563" alt="image" src="https://github.com/pytorch/pytorch/assets/72605280/948cb861-5eb4-4794-aaf6-66d95667ef3c">

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @ptrblck

**Comment by malfet** [comment]
Does it reproduces all the time? Can you share the link to the exact script that you are running?
@wconstab please loop me in when this is discussed

**Comment by freshduer** [comment]
this error is not due to pytorch
