### ISSUE TITLE
Upsampling modules deprecated

### ISSUE THREAD

**Issue by FrankZijlstra** [pytorch/pytorch#11452]
All Upsampling modules in torch/nn/modules/upsampling.py are listed as deprecated with the following message "nn.Upsampling is deprecated. Use nn.functional.interpolate instead.". This means there is currently no way to include upsampling in a Sequential model without getting a deprecation warning. For this reason, I think the Upsample module should not be deprecated. However, it could be renamed to Interpolate to be consistent with the changes in the functional API.

**Comment by SsnL** [comment]
cc @ailzhang
