### ISSUE TITLE
[export] AssertionError: expected FunctionType found method <bound method QuantLinearConvBase.quantized_forward of <class '__main__.QuantConv2d'>>

### ISSUE THREAD

**Issue by peri044** [pytorch/pytorch#114635]
### 🐛 Describe the bug

We have a tool which replaces conv layers (and potentially others) with their quantized variants. In the example, we convert a conv2d module into a QuantConv2d with the module.forward function changed to a custom forward function. However, with torch.export.export, I'm facing the following error 
```
result = BuiltinVariable(getattr).call_function(
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 636, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 1167, in call_getattr
    return obj.var_getattr(tx, name).clone(source=source)
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_dynamo/variables/user_defined.py", line 484, in var_getattr
    return variables.UserMethodVariable(func, self, source=source)
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_dynamo/variables/base.py", line 121, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 255, in __init__
    super().__init__(fn=fn, **kwargs)
  File "/home/dperi/.pyenv/versions/3.10.4/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 103, in __init__
    assert isinstance(
AssertionError: expected FunctionType found method <bound method QuantLinearConvBase.quantized_forward of <class '__main__.QuantConv2d'>>
```

To reproduce : 
```py
import torch
import types
import torch.nn as nn

class _QuantModuleBase:
    @classmethod
    def convert(cls, module):
        assert not hasattr(
            module, "_original_forward"
        ), "module already has an _original_forward attribute! module forward cannot be patched."
        module._original_forward = module.forward
        module.forward = types.MethodType(cls.quantized_forward, module)
        return module

class QuantLinearConvBase(_QuantModuleBase, nn.Module):
    """Base class for quantized linear modules like conv2d.
    """

    default_quant_desc_input = 1

    def __init__(self, *args, quant_desc_input=None, quant_desc_weight=None, **kwargs):
        """Initialize the module with its original __init__ and patch its forward."""
        super().__init__(*args, **kwargs)
        self.convert(self, quant_desc_input, quant_desc_weight)

    @classmethod
    def quantized_forward(cls, self, input, *args, **kwargs):
        """Quantize the input and weight before calling the original forward method."""
        output = self._original_forward(2.0*input, *args, **kwargs)

        return output

    @classmethod
    def convert(cls, module, quant_desc_input=None, quant_desc_weight=None):
        """Patch the module's forward method to quantize the input and weight."""
        module = super().convert(module)

        return module


class QuantConv2d(QuantLinearConvBase, torch.nn.Conv2d):
    """Quantized 2D convolution."""

    default_quant_desc_weight = 1


class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = torch.nn.Conv2d(3, 16, 3, stride=1, bias=True)

    def forward(self, x):
        out1 = self.conv(x)
        return out1

model = MyModule().eval().cuda()
QUANT_MODULE_MAPPING = {torch.nn.Conv2d: QuantConv2d.convert}
for name, module in model.named_children():
    if type(module) == torch.nn.Conv2d:
        setattr(model, name, QUANT_MODULE_MAPPING[type(module)](module))

x = torch.randn((1, 3, 32, 32), dtype=torch.float32).cuda()
exp_program = torch.export.export(model, (x,))
print("done")
```
cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @wconstab @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @Xia-Weiwen @leslie-fang-intel
### Versions

[pip3] mypy==1.5.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] onnx==1.14.1
[pip3] onnxruntime==1.16.3
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.2.0.dev20231127+cu121
[pip3] torch-tensorrt==2.2.0.dev0+7ad927248
[pip3] torchprofile==0.0.4
[pip3] torchvision==0.17.0.dev20231127+cu121
[pip3] triton==2.1.0

**Comment by peri044** [comment]
Hello @tugsbayasgalan Thanks for your response. Torchscript is not an option for us unfortunately. We are writing our own quantization toolkit in Pytorch (not direct usage of PT2 quantization workflow). As an example, we are replacing the general `nn.Conv2d` module with a `QuantConv2d` module. `QuantConv2d` is similar to `nn.Conv2d` except we change the forward function (to perform additional operation on input). However, torch dynamo does seem to have a problem with 
```
module._original_forward = module.forward
module.forward = types.MethodType(cls.quantized_forward, module)
```
Any recommendations on how to do this ? 
Here's a related issue that I found : https://github.com/Lightning-AI/pytorch-lightning/issues/16395. But I couldn't deduce the proper fix from the comments.

**Comment by peri044** [comment]
@tugsbayasgalan  Any update on this issue ? Thanks !!

**Comment by angelayi** [comment]
A smaller repro: 

```
import torch
import types

class Patch(torch.nn.Module):
    @classmethod
    def patch(cls, self, input, *args, **kwargs):
        m = torch.nn.Conv2d(3, 16, 3, stride=1, bias=True).eval()
        return m(2.0 * input, *args, **kwargs)

m = torch.nn.Module()
m.forward = types.MethodType(Patch.patch, m)

x = torch.randn((1, 3, 32, 32), dtype=torch.float32)
m(x)
exp_program = torch.export.export(m, (x,))
```

**Comment by avikchaudhuri** [comment]
To be clear, replacing the export call in your repro with `torch.compile(m)(x)` fails with the same error.

**Comment by angelayi** [comment]
Chatted with some dynamo folks and it seems like patching a function with a class method is not supported by dynamo. Not sure if I can explain this clearly, but dynamo expects the patched method to be a method that can be unfurled into a function through `method.__func__`. However in this case, we have a classmethod that is being patched as a method. So when we unfurl the patched method, it still is a method, and we need to unfurl again to make it a function. However, directly unfurling it twice might not be correct because the original class is not being tracked by dynamo.

Would it be possible to rewrite the code so that you're not using a classmethod? A staticmethod should work:

```
import torch
import types

conv = torch.nn.Conv2d(3, 16, 3, stride=1, bias=True).eval()
class Patch(torch.nn.Module):
    @staticmethod
    def patch(self, input, *args, **kwargs):
        return conv(2.0 * input, *args, **kwargs)

m = torch.nn.Module()
m.forward = types.MethodType(Patch.patch, m)

x = torch.randn((1, 3, 32, 32), dtype=torch.float32)
m(x)
exp_program = torch.export.export(m, (x,))
```

**Comment by masnesral** [comment]
@anijain2305 I'm trying to perform oncall duties this week, so marking this as hi-pri since I see a "must fix" label. I'm also adding "triaged", but could you please replace with the triage review label if this should be discussed there?

**Comment by anijain2305** [comment]
This seems to work now. I added this test case

~~~
import torch
import types

conv = torch.nn.Conv2d(3, 16, 3, stride=1, bias=True).eval()
class Patch(torch.nn.Module):
    @staticmethod
    def patch(self, input, *args, **kwargs):
        return conv(2.0 * input, *args, **kwargs)

m = torch.nn.Module()
m.forward = types.MethodType(Patch.patch, m)

x = torch.randn((1, 3, 32, 32), dtype=torch.float32)
ref = m(x)

opt_m = torch.compile(m, backend="eager", fullgraph=True)
res = opt_m(x)

torch.testing.assert_allclose(ref, res)
~~~

Removing high-prio and assigning back to @angelayi for final confirmation.
