### ISSUE TITLE
Typo in SCALED_DOT_PRODUCT_ATTENTION document?

### ISSUE THREAD

**Issue by yuzhenmao** [pytorch/pytorch#114619]
### 🐛 Describe the bug

In https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html

Shouldn't the third line be `attn_bias.masked_fill_(attn_mask.logical_not(), float("-inf"))`?
<img width="632" alt="Screenshot 2023-11-27 at 2 37 15 PM" src="https://github.com/pytorch/pytorch/assets/57878927/027aff51-0fa2-494f-9fbc-819780c25bd9">

### Versions

```
[pip3] numpy==1.25.2
[pip3] numpy-groupies==0.10.2
[pip3] pytorch-lightning==2.0.9
[pip3] torch==2.1.0
[pip3] torch-geometric==2.3.1
[pip3] torchaudio==2.1.0
[pip3] torchdata==0.7.0
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.16.0
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] mkl                       2024.0.0                 pypi_0    pypi
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] numpy-groupies            0.10.2                   pypi_0    pypi
[conda] pytorch-lightning         2.0.9.post0              pypi_0    pypi
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] torch-geometric           2.3.1                    pypi_0    pypi
[conda] torchaudio                2.1.0                    pypi_0    pypi
[conda] torchmetrics              1.2.0                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
```

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
This is already fixed [on main](https://pytorch.org/docs/main/generated/torch.nn.functional.scaled_dot_product_attention.html#torch-nn-functional-scaled-dot-product-attention) and will be visible in the stable docs in the next release
