### ISSUE TITLE
Undefined reference to ATen, c10 during Rust linking?

### ISSUE THREAD

**Issue by EricLBuehler** [pytorch/pytorch#114640]
### 🐛 Describe the bug

Hello everybody,

I am developing [candle-vllm](https://github.com/EricLBuehler/candle-vllm) for Rust. During linking of the project, I get the following error:
```
/home/ubuntu/.local/lib/python3.8/site-packages/torch/include/ATen/ops/ones.h:36: undefined reference to `at::_ops::ones::call(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)'
```
The full error is very long, but essentially consists of the above repeated with slight variations. Please find the `paged_attention` branch, and run `cargo run` after following `install.txt` to reproduce the issue. 

Is this a bug with `pytorch` (probably not?) or do I have something misconfigured on my system? Please note that I was able to reproduce the error on a clean instance.

Thanks!

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA RTX A6000
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   40 bits physical, 48 bits virtual
CPU(s):                          14
On-line CPU(s) list:             0-13
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       14
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC-Rome Processor
Stepping:                        0
CPU MHz:                         2500.023
BogoMIPS:                        5000.04
L1d cache:                       448 KiB
L1i cache:                       448 KiB
L2 cache:                        7 MiB
L3 cache:                        224 MiB
NUMA node0 CPU(s):               0-13
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT disabled
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr wbnoinvd arat umip rdpid arch_capabilities

Versions of relevant libraries:
[pip3] flake8==3.7.9
[pip3] numpy==1.23.4
[pip3] torch==2.1.0+cu118
[pip3] torchaudio==2.1.0+cu118
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] Could not collect

cc @jbschlosser

**Comment by EricLBuehler** [comment]
Here is my nvcc information:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```

And a link to the Rust install:
https://www.rust-lang.org/tools/install

**Comment by malfet** [comment]
Can you provide some sort of a minimal example of how you are trying to integrate PyTorch with Rust? (I assume on libtorch level)
I suspect the error comes from the build flag of sorts, (i.e. you either linking using C++14 convention instead of C++17 or build pre-cxx11 library ABI with CXX11-ABI compatible runtime)

**Comment by EricLBuehler** [comment]
This is exactly the problem. The linking with tch-rs (one of my deps) is the only contact candle-vllm (Rust) has with Pytorch. Would you recommend raising an issue on tch-rs?

**Comment by EricLBuehler** [comment]
Fixed by updating LD_LIBRARY_PATH, according to the tch-rs README.
