### ISSUE TITLE
weight_norm not working in bf16

### ISSUE THREAD

**Issue by qasfb** [pytorch/pytorch#114746]
### 🐛 Describe the bug

```python

import torch
import torch.nn as nn
linear = nn.Linear(32, 64).to(dtype=torch.bfloat16, device="cuda")
torch.nn.utils.parametrizations.weight_norm(linear)
linear.weight

-> RuntimeError: "weight_norm_fwd_first_dim_kernel" not implemented for 'BFloat16'
```

Possibly relevant PR: https://github.com/pytorch/pytorch/pull/108206

### Versions

Nov 28 Nightly

**Comment by qasfb** [comment]
By the way, what is _weight_norm doing exactly ? I can't reproduce its outputs using eager code

**Comment by lezcano** [comment]
Not sure what you mean by eager code. That code you wrote is eagerly executed

**Comment by qasfb** [comment]
Sorry i meant:

how do i reproduce weight norm results by hand ?

```python
from torch import _weight_norm
weight_g = torch.randn(64,1)
weight_v = torch.randn(64,32)

weight_ref = _weight_norm(weight_v, weight_g, -1)

weight = weight_v * (weight_g / weight_v.norm(p=2, dim=-1, keepdim=True))

weight.allclose(weight_ref) -> False

```

What is the right formula to the the same result in `weight` ? That could be an immediate workaround to do bf16, as the issue was open for a few months now...

**Comment by lezcano** [comment]
Feel free to use that workaround for now in your code.

The right fix in core goes along the lines of https://github.com/pytorch/pytorch/pull/108206. That PR is quite close to being done. If you feel comfortable fixing the few things that are left in that PR, feel free to submit a new PR addressing the comments that were left there. Otherwise @mikaylagawarecki may probably pick it up

**Comment by qasfb** [comment]
My question was: what is the workaround ?

**Comment by lezcano** [comment]
It'd be to do something similar to what you have mentioned using the newer API for parametrisations. See `SpectralNorm` as an example:
https://pytorch.org/docs/stable/_modules/torch/nn/utils/parametrizations.html#spectral_norm

**Comment by qasfb** [comment]
Do you have the equivalent pytorch code snippet to the C function ?

**Comment by qasfb** [comment]
ok i think i got it:
`_weight_norm(v, g, self.dim) == v * (g / torch.norm_except_dim(v, dim=self.dim))`

**Comment by cageyoko** [comment]
> _weight_norm

Yes, it's a solve method. 
I changed the file "torch/nn/utils/parametrizations.py" by this method to solve my problem, thanks!

**Comment by lezcano** [comment]
Note that this was fixed in https://github.com/pytorch/pytorch/pull/114785, so upgrading to 2.3 should also solve the issue.
