### ISSUE TITLE
FakeTensorMode not preserved within torch.export.ExportedProgram.run_decompositions

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#114711]
### 🐛 Describe the bug

Context: After https://github.com/pytorch/pytorch/pull/114009, `aot_export_module` accepts inputs/model already fakefied by user.

However, when one tries to decompose the fake model with `run_decompositions`, we get an error with a mismtached fake tensor mode

```python
import torch
import transformers
from torch._subclasses import fake_tensor
    
config = transformers.T5Config(
    vocab_size=8096, d_model=64, num_layers=2, num_heads=2
)
batch, seq = 4, 256

def create_args():
    return tuple()

def create_kwargs():
    input_ids = torch.randint(0, config.vocab_size, (batch, seq))
    attention_mask = torch.ones((batch, seq), dtype=torch.bool)
    decoder_input_ids = torch.randint(0, config.vocab_size, (batch, seq))
    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "decoder_input_ids": decoder_input_ids,
    }

def create_model():
    return transformers.T5Model(config).eval()

fake_mode = fake_tensor.FakeTensorMode()

with fake_mode:
    fake_args = create_args()
    fake_kwargs = create_kwargs()
    fake_model = create_model()

    fake_model = torch.export.export(
        fake_model, args=fake_args, kwargs=fake_kwargs
    )

    # AssertionError: fake mode (<torch._subclasses.fake_tensor.FakeTensorMode object at 0x7fe1f6bf45d0>)
    #   from active fake mode 0 doesn't match mode
    #   (<torch._subclasses.fake_tensor.FakeTensorMode object at 0x7fe1e920fc90>) from fake tensor input 0
    model = fake_model.run_decompositions()
```

ideally, `run_decompositions` should also preserve the user fake mode

### Versions

main

cc @eellison @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by thiagocrepaldi** [comment]
@ydwu4 FYI

**Comment by angelayi** [comment]
Hmm, I think we might need to add something like [this](https://github.com/pytorch/pytorch/blob/a26d747615fd146eac877f10db560a14233b3140/torch/_export/__init__.py#L644) to run_decompositions()

**Comment by thiagocrepaldi** [comment]
That was my workaround (aka call `run_decompositions` outside a fake mode context), but I was unsure whether that was the right thing to do

If it is, I can push a PR now
