### ISSUE TITLE
torch.cuda.amp.common.amp_definitely_not_available() failed and needs to raise RuntimeError

### ISSUE THREAD

**Issue by GuWei007** [pytorch/pytorch#114740]
### 🚀 The feature, motivation and pitch

"Our device manufacturer integrated PyTorch using the privateuse1 method, and our customer accidentally used torch.cuda.amp.autocast for model training. The torch.cuda.amp.common.amp_definitely_not_available() function failed to execute on our third-party device, triggering the warning message: User provided device_type of 'cuda', but CUDA is not available. Disabling. We suggest changing this warning to raise a RuntimeError instead, so that our customers can be promptly notified when AMP mode is not working."

### Alternatives

https://github.com/pytorch/pytorch/blob/main/torch/amp/autocast_mode.py#L250
warnings.warn(
                "User provided device_type of 'cuda', but CUDA is not available. Disabling"
            )

changes to
raise RuntimeError(
                "User provided device_type of 'cuda', but CUDA is not available. Disabling"
            )

### Additional context

https://github.com/pytorch/pytorch/blob/main/torch/amp/autocast_mode.py#L250

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by GuWei007** [comment]
"I have submitted a pull request. Could you please help me with the review?"

https://github.com/pytorch/pytorch/pull/114950

**Comment by malfet** [comment]
This is a bit of old story of AMP needs to be redesigned to be vendor agnostic...

**Comment by GuWei007** [comment]
> This is a bit of old story of AMP needs to be redesigned to be vendor agnostic. One can already turn warning in to exception(using warningfilters), can they? So feel free to add to the initialization logic to your backend if you don't want to miss those warnings next time.

okay
