### ISSUE TITLE
I want to upgrade my PyTorch

### ISSUE THREAD

**Issue by NJTechMXY** [pytorch/pytorch#114744]
### 🐛 Describe the bug

I met some problem.
### Versions

I want to upgrade my PyTorch version from 1.9.0 with CUDA 11.1 to 1.12.0.
 How can I do that? 
My CUDA version is 11.6

**Comment by garyyaoresearch** [comment]
pip install torch==1.12.0+cu116

**Comment by malfet** [comment]
Please use https://discuss.pytorch.org/ to ask questions on how to use PyTorch
But if you discover an issue, please do not hesitate to open a new issue
