### ISSUE TITLE
Error -3 while decompressing data: invalid block type

### ISSUE THREAD

**Issue by Akado2009** [pytorch/pytorch#11482]
## Issue description
I got the problem when I tried to download MNIST dataset. Tested twice: with pytorch installed using pip and pytorch compiled from source.
## Code example

```
dataset = datasets.MNIST(
        './data',
        train=True,
        download=True,
        transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307, ), (0.3081, ))
        ]))
```

## System Info

PyTorch version: 0.3.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.12.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by ngimel** [comment]
Closing due to age
