### ISSUE TITLE
[inductor][cpu] few models show performance regression on CPP Wrapper

### ISSUE THREAD

**Issue by WeizhuoZhang-intel** [pytorch/pytorch#114875]
### 🐛 Describe the bug

Some model shows performance regression on same guilty commit

**Performance table**

| model                          | suite       | new_bs | new_speedup | new_eager | new_inductor | old_bs | old_speedup | old_eager | old_inductor | old_inductor / new_inductor |
|--------------------------------|-------------|--------|-------------|-----------|--------------|--------|-------------|-----------|--------------|-----------------------------|
| lcnet_050                      | timm        | 128    | 2.970531    | 0.045096  | 0.015181     | 128    | 3.423834    | 0.044697  | 0.013055     | 0.859929                    |
| DebertaV2ForQuestionAnswering  | huggingface | 1      | 1.001918    | 0.334691  | 0.334051     | 1      | 1.342519    | 0.326062  | 0.242874     | 0.727056                    |
| MobileBertForQuestionAnswering | huggingface | 128    | 1.543972    | 0.430431  | 0.278781     | 128    | 1.724334    | 0.367654  | 0.213215     | 0.764812                    |
| mnasnet1_0                     | torchbench  | 32     | 2.384225    | 0.039592  | 0.016606     | 32     | 2.757133    | 0.037479  | 0.013593     | 0.818603                    |
| mobilenet_v2                   | torchbench  | 16     | 2.477216    | 0.025584  | 0.010328     | 16     | 2.64812     | 0.02242   | 0.008466     | 0.819788                    |
| mobilenet_v3_large             | torchbench  | 32     | 2.550008    | 0.038077  | 0.014932     | 32     | 2.934538    | 0.036924  | 0.012583     | 0.842642                    |
| shufflenet_v2_x1_0             | torchbench  | 64     | 2.088285    | 0.040407  | 0.01935      | 64     | 2.061695    | 0.0342    | 0.016589     | 0.857307                    |
| squeezenet1_1                  | torchbench  | 16     | 2.596436    | 0.017121  | 0.006594     | 16     | 2.908283    | 0.015944  | 0.005482     | 0.831381                    |

### Versions

**SW info**
SW | Nightly commit | Main commit
-- | -- | --
Pytorch | df0c1b3 |  
Torchbench | / | 94126be6
torchaudio | db62484 |  
torchtext | b0ebddc |  
torchvision | 893b4ab |  
torchdata | 11bb5b8 |  
dynamo_benchmarks | nightly | /

**Reference SW info (nightly)**
SW | Nightly commit | Main commit
-- | -- | --
Pytorch | f90c2af|  
Torchbench | / | ffbbebb9
torchaudio | 475b6ae|  
torchtext | 142d029|  
torchvision | 8636bf3|  
torchdata | eb9bf61|  
dynamo_benchmarks | 0200b11 | /

image: docker pull ccr-registry.caas.intel.com/pytorch/pt_inductor:2023_11_29_aws

Repro

[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
```shell
# lcnet_050
bash inductor_single_run.sh multiple inference performance torchbench lcnet_050 float32 first static cpp 0
```

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/84975339bd3fa6819469f38a696791edc2da54d6 

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by WeizhuoZhang-intel** [comment]
cc @zxd1997066 @chuanqi129

**Comment by chunyuan-w** [comment]
Should have been fixed by https://github.com/pytorch/pytorch/pull/114741
