### ISSUE TITLE
Strange memory increase during inference/evaluation

### ISSUE THREAD

**Issue by BitCalSaul** [pytorch/pytorch#114881]
### 🐛 Describe the bug

I found the similar issue https://github.com/pytorch/pytorch/issues/4932, but it didn't help.
I did the train() and eval() in the same epoch. I found a strange memory increase during eval(), but I used torch.no_grad() and eval(). The code and GPU performance are listed below.
<img width="1425" alt="image" src="https://github.com/pytorch/pytorch/assets/142638691/4455d17d-7941-4209-875b-1b6925160cdb">
```
for epoch in range(start_epoch, args.epochs):
        # setting
        if args.distributed:
            data_loader_train.sampler.set_epoch(epoch)
        # train
        batch_loss = []
        model.train()
        start_time = time.time()
        total_step = len(data_loader_train)
        for ii, (src, tgt) in enumerate(data_loader_train):
            # print(src.shape,tgt.shape)
            src = src.to(device)
            tgt = tgt.to(device)
            outputs = model(src, tgt)
            optimizer.zero_grad()
            # nb cross entropy require input as (N,Class_num, d...) and target (N, d...)
            loss = criterion(outputs.permute(0, 2, 1), tgt)
            loss.backward()
            optimizer.step()
            batch_loss.append(loss.item())
        torch.cuda.empty_cache()
        continue_training = evaluate(args, model, data_loader_val,epoch, num_epochs, num_bad_epochs,best_loss, device, criterion)
```
```
@torch.no_grad()
def evaluate(args, model, data_loader_val,epoch, num_epochs, num_bad_epochs,best_loss, device, criterion):
    model.eval()
    test_loss = 0
    for src, tgt in data_loader_val:
        src = src.to(device)
        tgt = tgt.to(device)
        # bug in the third batch, once the output is done, the VRAM changed from 4G to 8G
        outputs = model(src, tgt)
        loss = criterion(outputs.permute(0, 2, 1), tgt)
        test_loss += loss.item()
    avg_test_loss = test_loss / len(data_loader_val)
    print(f'Epoch {epoch+1}/{num_epochs}, Test Loss: {avg_test_loss}')
    # nb early stopping is implemented
    if avg_test_loss < args.loss_threshold:
        print(f"Test loss {avg_test_loss} is below the threshold {args.loss_threshold}.")
        print("Early stopping triggered due to reaching loss threshold.")
        return False
    if avg_test_loss < best_loss:
        best_loss = avg_test_loss
        num_bad_epochs = 0
    else:
        num_bad_epochs += 1
    if num_bad_epochs >= args.patience:
        print("Early stopping triggered")
        return False
    return True
```

### Versions

Collecting environment information...
PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.23

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 1080 Ti
GPU 3: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 535.113.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
Stepping:              2
CPU MHz:               3589.829
CPU max MHz:           3700.0000
CPU min MHz:           1200.0000
BogoMIPS:              6996.45
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear flush_l1d

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.1.0
[pip3] torchaudio==0.8.0
[pip3] torchvision==0.16.1
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0            py38h5eee18b_1  
[conda] mkl_fft                   1.3.8            py38h5eee18b_0  
[conda] mkl_random                1.2.4            py38hdb19cb5_0  
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] numpy-base                1.24.3           py38h060ed82_1  
[conda] pytorch                   2.1.1           py3.8_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] torchaudio                0.8.0                    pypi_0    pypi
[conda] torchtriton               2.1.0                      py38    pytorch
[conda] torchvision               0.9.0                    pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by mikaylagawarecki** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
