### ISSUE TITLE
CUDA graph doesn't update tensor on replay

### ISSUE THREAD

**Issue by sujoysaraswati** [pytorch/pytorch#114844]
### 🐛 Describe the bug

CUDA graph results in wrong value after replay for the following example. The test case expects the "x" tensor in the model to be updated with the first linear output, but graph replay doesn't update it.

```
import torch
import os

class Model(torch.nn.Module):
    def __init__(self, inp_size, out_size, inner_size):
        super(Model, self).__init__()
        self.Linear1 = torch.nn.Linear(inp_size, inner_size)
        self.Linear2 = torch.nn.Linear(inner_size, out_size)
        self.x = None

    def forward(self, inp):
        res = self.Linear1(inp)
        self.x = res
        return self.Linear2(res)

N, D_in, H, D_out, inner = 2, 2, 2, 2, 4
model = Model(D_in, H, inner).to("cuda")
input = torch.ones(N, D_in, device='cuda')
out = model(input)

g = torch.cuda.CUDAGraph()
with torch.cuda.graph(g):
  out = model(input)

input2 = torch.ones(N, D_in, device='cuda').add_(10)
# Keep some intermediate value in model.x
model.x = torch.Tensor([[100, 100, 100, 100],[200, 200, 200, 200]])

# Incorrect behavior
input.copy_(input2)
g.replay()
print(f"Incorrect model.x = {model.x}")

# Expected behavior
out = model(input2)
print(f"Expected model.x = {model.x}")
```

The result from the above code -
```
Incorrect model.x = tensor([[100., 100., 100., 100.],
        [200., 200., 200., 200.]])
Expected model.x = tensor([[-10.6180,  -0.6991,  -4.5837,   8.1134],
        [-10.6180,  -0.6991,  -4.5837,   8.1134]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
```
Is this because CUDA graph cannot capture the CPU side "self.x = res" execution and there is no replay for this step? Since this silently gives a wrong value, is there anyway for CUDA graph to detect it?

### Versions

PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.7
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.120+-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.00GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        3
BogoMIPS:                        4000.30
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        1 MiB (1 instance)
L3 cache:                        38.5 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.1.0+cu118
[pip3] torchaudio==2.1.0+cu118
[pip3] torchdata==0.7.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.16.0
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] Could not collect

cc @mcarilli @ezyang @eellison @peterbell10 @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by ezyang** [comment]
Yes, exactly. There's not really a good way to detect this either under the API you are using: CUDAGraph would have to somehow detect all attribute modifications happening in Python.

What you should do instead is use Dynamo + CUDA graphs, which is in fact able to detect all these modifications and will faithfully replay them. cc @eellison

**Comment by Abhishekghosh1998** [comment]
> What you should do instead is use Dynamo + CUDA graphs, which is in fact able to detect all these modifications and will faithfully replay them

@ezyang I tried to follow your comment and tried out `torch.compile` on the code the OP shared. But unfortunately, I wasn't able to make `torch.compile` detect the attribute modification happening in Python. :( 

My Code:
```python
import torch
import os

class Model(torch.nn.Module):
    def __init__(self, inp_size, out_size, inner_size):
        super(Model, self).__init__()
        self.Linear1 = torch.nn.Linear(inp_size, inner_size)
        self.Linear2 = torch.nn.Linear(inner_size, out_size)
        self.x = None

    def forward(self, inp):
        res = self.Linear1(inp)
        self.x = res
        return self.Linear2(res)

N, D_in, H, D_out, inner = 2, 2, 2, 2, 4
model = Model(D_in, H, inner).to("cuda")
input = torch.ones(N, D_in, device='cuda')
compiled_model = torch.compile(model, mode="reduce-overhead")


input2 = torch.ones(N, D_in, device='cuda').add_(10)
# Keep some intermediate value in model.x
model.x = torch.Tensor([[100, 100, 100, 100],[200, 200, 200, 200]])

# Expected behavior
out = model(input2)
print(f"Expected model.x = {model.x}")

# Keep some intermediate value in compiled_model.x
compiled_model.x = torch.Tensor([[100, 100, 100, 100],[200, 200, 200, 200]])

# the first run warms up each graph, which does things like CuBlas or Triton benchmarking
out = compiled_model(input2)
print(f"Incorrect compiled_model.x = {compiled_model.x}")

# The second run does a CUDA Graph recording, and replays it
out = compiled_model(input2)
print(f"Incorrect compiled_model.x = {compiled_model.x}")

# Finally we hit the optimized, CUDA Graph replay path
out = compiled_model(input2)
print(f"Incorrect compiled_model.x = {compiled_model.x}")
```

To which I get the following output:
```
Expected model.x = tensor([[  2.2505,   3.3132, -12.2887,  -7.0492],
        [  2.2505,   3.3132, -12.2887,  -7.0492]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
Incorrect compiled_model.x = tensor([[100., 100., 100., 100.],
        [200., 200., 200., 200.]])
Incorrect compiled_model.x = tensor([[100., 100., 100., 100.],
        [200., 200., 200., 200.]])
Incorrect compiled_model.x = tensor([[100., 100., 100., 100.],
        [200., 200., 200., 200.]])
/home/abhishek/.local/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py:2069: UserWarning: Unable to hit fast path of CUDAGraphs because of pending, uninvoked backwards. Consider running with torch.no_grad() or using torch.compiler.cudagraph_mark_step_begin() before each model invocation
  warnings.warn(
```
torch version '2.2.1+cu121'
Where am I going wrong?
