### ISSUE TITLE
Add support for torch.cat on nested_tensor

### ISSUE THREAD

**Issue by marinscalbert-coder** [pytorch/pytorch#114876]
### 🚀 The feature, motivation and pitch

I would need to concatenate nested tensors like the following example:

```python
import torch

nested_a = torch.nested.nested_tensor([
    torch.randn(2, 5),
    torch.randn(3, 5)])

nested_b = torch.nested.nested_tensor([
    torch.randn(3, 5),
    torch.randn(4, 5)])

# Concatenate nested_a and nested_b should result
# in a nested_tensor with shape [(5, 5), (7, 5)]
nested_ab = torch.cat(
    [nested_a, nested_b], dim=0)
```
   
 Since the `torch.cat` operation is not supported on nested tensors, such operation triggered an error. I think it would be a useful feature for the `torch.nested` library.

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @soulitzer

**Comment by mikaylagawarecki** [comment]
Does this work for you on the latest nightly? I was unable to reproduce this on `main`
