### ISSUE TITLE
Sparse CSC | CSR | Tensor Serialization Load Issue

### ISSUE THREAD

**Issue by jdenhof** [pytorch/pytorch#114877]
### 🐛 Describe the bug

**Successes**
The sparse_csc_tensor is successfully created and correctly computes the sum. 

**Failures**
The following runtime error is thrown when calling torch.load on the serialized sparse_csc_tensor

```python
ccol_indices = torch.Tensor([1, 0, 0, 2], device=DEVICE).to(torch.int)
row_indices = torch.Tensor([0, 1, 2, 2], device=DEVICE).to(torch.int)
values = torch.Tensor([1.0, 2.0, 3.0, 4.0], device=DEVICE)
size = (3, 3)

result = torch.sparse_csr_tensor(ccol_indices, row_indices, values, size=size, device=DEVICE)
print("Sum: ", result.sum())
torch.save(result, './test.pt')

torch.load('./test.pt')
```
**output:**
Sum:  tensor(10.)
torch._validate_sparse_compressed_tensor_args(
RuntimeError: `ccol_indices[..., 0] == 0` is not satisfied.

### Versions

PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.27.4
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 08:50:36)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.1.1
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h8e150cf_43559  
[conda] mkl-service               2.4.0            py39h6c40b1e_1  
[conda] mkl_fft                   1.3.6            py39h07fba90_1  
[conda] mkl_random                1.2.2            py39h07fba90_1  
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] numpy-base                1.25.2           py39ha186be2_0  
[conda] torch                     2.0.0                    pypi_0    pypi

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @mruberry @mikaylagawarecki

**Comment by malfet** [comment]
This kind of expected behavior, as crow_indices should be ascending and start with zero.
If one adds `check_invariants=True` to the `torch.sparse_csr_tensor`, one would encounter the same error.

**Comment by pearu** [comment]
Perhaps you meant to have:
```python
row_indices = torch.Tensor([1, 0, 0, 2], device=DEVICE).to(torch.int)
ccol_indices = torch.Tensor([0, 1, 2, 2], device=DEVICE).to(torch.int)
```
?

Anyway, the issue can be closed because the reported failure is due to incorrect user input.

**Comment by jdenhof** [comment]
@pearu Out of curiosity, if that is the case how come the sum can be correctly computed, is this because it only has to sum within the values tensor?

**Comment by pearu** [comment]
> @pearu Out of curiosity, if that is the case how come the sum can be correctly computed, is this because it only has to sum within the values tensor?

@jdenhof sum does not need to use indices data at all. Notice that `csc.sum()` is equal to `csc.values().sum()`.
