### ISSUE TITLE
[torch.compile] Using torch.amp.autocast as decorator caused graph breaks

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#114818]
### 🐛 Describe the bug

Reported by Meta internal teams, cc @jackiexu1992.

Repro:
```
import torch


def autocast_func_forward(orig_fwd):
    @torch.amp.autocast(device_type="cuda", dtype=torch.bfloat16)
    def new_fwd(*args, **kwargs):
        return orig_fwd(*args, **kwargs)

    return new_fwd

class BasicModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = torch.nn.Linear(10, 10)
        self.linear1.forward = autocast_func_forward(self.linear1.forward)

    def forward(self, x):
        return self.linear1(x)


x = torch.rand(10, 10)
m = BasicModule()
opt_m = torch.compile(backend="eager")(m)
res = opt_m(x)
print(res)
```

Error:
```
torch._dynamo.exc.Unsupported: 'inline in skipfiles: autocast_func_forward.<locals>.new_fwd | decorate_autocast /home/ybliang/local/pytorch/torch/amp/autocast_mode.py, skipped according skipfiles.SKIP_DIRS'
```

### Versions

N/A

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by yanboliang** [comment]
This is because of autocast decorator returning a function which is on a skip file.

https://github.com/pytorch/pytorch/blob/34ea0a2bdc7d17f5ca0e895590159e5fd36fffa0/torch/amp/autocast_mode.py#L12-L19

**Comment by jon-chuang** [comment]
Related: https://github.com/pytorch/pytorch/issues/112848

I think `torch.autocast` works?

**Comment by yanboliang** [comment]
> I think torch.autocast works?

Unfortunately it doesn't work, actually ```torch.autocast``` is alias of ```torch.amp.autocast_mode.autocast```. The root cause of this issue is we can't inline that ```autocast_decorator``` function well. I'm working on a resolution now.
