### ISSUE TITLE
torch.onnx.export to support opset 20. 

### ISSUE THREAD

**Issue by liqunfu** [pytorch/pytorch#114801]
### 🚀 The feature, motivation and pitch

onnx.export only support onnx opset up to version 18. There have been many updates and new operators added since version 18 in ONNX as required from real use cases. For example: https://github.com/pytorch/pytorch/issues/100790
New dynamo export is in progress. It does not run on Windows. Existing users may already have torch.onnx.export in place and have difficulty migrating to dynamo export.  
 

### Alternatives

None.

register custom op is not a solution. If one calls torch.onnx.export with version=20, it will fail for many reasons due to amount of op changes since version 18.

One may be able to export to version 18 with customer ops and then use version converter to convert the exported model to version 20. There are likely unexpected errors in the path as well.

**Comment by daikankan** [comment]
any update?

**Comment by thiagocrepaldi** [comment]
There is no plan to support opset 19 or 20 for `torch.onnx.export`

**Comment by tianlinzx** [comment]
> liqunfu

[liqunfu](https://github.com/liqunfu) already submitted a PR to support this feature ，will this PR be accepted ？
@thiagocrepaldi @liqunfu

**Comment by thiagocrepaldi** [comment]
> > liqunfu
> 
> [liqunfu](https://github.com/liqunfu) already submitted a PR to support this feature ，will this PR be accepted ？ @thiagocrepaldi @liqunfu

We are discussing the required changes internally and once it is working, it can be merged

**Comment by tianlinzx** [comment]
Which pytorch release will include this feature ? @thiagocrepaldi

**Comment by thiagocrepaldi** [comment]
> Which pytorch release will include this feature ? @thiagocrepaldi

The PR that adds support for opset 20 was already merge into main branch. you can test it on a nightly build
The code will be on officially available the next PyTorch release 

On this commit, `aten:grid_sampler` and `aten::affine_grid_generator` will be supported

**Comment by XhqGlorry11** [comment]
> There is no plan to support opset 19 or 20 for `torch.onnx.export`

@thiagocrepaldi how to convert onnx model with opset 20?

**Comment by ykk648** [comment]
> > There is no plan to support opset 19 or 20 for `torch.onnx.export`
> 
> @thiagocrepaldi how to convert onnx model with opset 20?

torch2.4.0 already support opset 20 :)
