### ISSUE TITLE
Addition of Sparse CSC and Dense Tensors Triggers Internal Assertion Failure

### ISSUE THREAD

**Issue by jdenhof** [pytorch/pytorch#114807]
### 🐛 Describe the bug

```python
X = torch.randn(2, 2).to_sparse_csc() 
Y = torch.randn(2, 2)
X + Y
```
Traceback (most recent call last):
  File "/Users/jaggerdenhof/Workspaces/gvsu-workspace/autoencoder/Model/example.py", line 57, in <module>
    X + Y
RuntimeError: at::sparse_csr::is_sparse_compressed(other) 
INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/SparseCsrTensorUtils.h":329, 
please report a bug to PyTorch. 

### Versions

PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.27.4
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 08:50:36)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.1.1
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h8e150cf_43559  
[conda] mkl-service               2.4.0            py39h6c40b1e_1  
[conda] mkl_fft                   1.3.6            py39h07fba90_1  
[conda] mkl_random                1.2.2            py39h07fba90_1  
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] numpy-base                1.25.2           py39ha186be2_0  
[conda] torch                     2.0.0                    pypi_0    pypi

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by cpuhrsch** [comment]
The addition of COO and dense is dense. I think we can follow the same convention for CSR/CSC and dense.

**Comment by amjames** [comment]
Two bugs involved here. 

First, sparse compressed add for dense/sparse requires that the lhs is the dense argument, if that condition is not met it always falls into the sparse-sparse path. #115432 addresses this. 

Second, the underlying algorithm for dense + sparse_csr is not generic on the compressed dimension of the sparse argument #115433 fixes this adding support for `csc`.
