### ISSUE TITLE
[inductor] `torch.var` unexpectedly returns NaN values on A16 and A2 

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#114903]
### 🐛 Describe the bug

Compiling a minimal module that only does `torch.var` produces code that unexpectedly yields NaN values when executed on A16 and A2. Interestingly, the issue doesn't seem to reproduce on all SM 8.6 devices (such as A40).

```
import torch

import torch._dynamo as dynamo

torch._dynamo.config.repro_after="aot"

class Model(torch.nn.Module):
    def forward(self, x):
        return torch.var(x)

model = Model()

def test_backend_error():
    x = torch.rand((10, 3, 352, 352), dtype=torch.float16, device='cuda')
    y = model(x)
    assert not torch.isnan(y)

compiled_test_backend_error = torch.compile(test_backend_error, backend="inductor")
compiled_test_backend_error()
```

### Versions

Tested on a fresh (as of a few hours ago) source build.

cc @ptrblck @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by Chillee** [comment]
Is the generated Triton code identical on those devices? It's possible this is a Triton bug.

**Comment by eqy** [comment]
I'm not sure where is best to inspect the Triton code, but I'm seeing that the pre/post-fusion IR is different.
[a2ir_post_fusion.txt](https://github.com/pytorch/pytorch/files/13519274/a2ir_post_fusion.txt)
[a2ir_pre_fusion.txt](https://github.com/pytorch/pytorch/files/13519275/a2ir_pre_fusion.tx
[a40ir_post_fusion.txt](https://github.com/pytorch/pytorch/files/13519278/a40ir_post_fusion.txt)
[a40ir_pre_fusion.txt](https://github.com/pytorch/pytorch/files/13519279/a40ir_pre_fusion.txt)
t)

**Comment by Chillee** [comment]
Easiest way is to look at `output_code.py`, or what gets output by `TORCH_LOGS="output_code"`.

**Comment by shunting314** [comment]
Couldn't repro on A100 either.

Agree with @Chillee  that we should look at the compiled code. What's pretty good is that the compiled code is directly runnable. Running the compiled code (wrapper or kernel) should help us identify if this is an issue in inductor or triton

**Comment by eqy** [comment]
A40 vs. A2 comparison (so far it is only known to reproduce on A2 and A16) via `TORCH_LOGS='output_code'`

[A2output.txt](https://github.com/pytorch/pytorch/files/13553883/A2output.txt)
[A40output.txt](https://github.com/pytorch/pytorch/files/13553884/A40output.txt)

**Comment by eqy** [comment]
Closing as https://github.com/pytorch/pytorch/pull/115181 has been merged, thanks @peterbell10

**Comment by peterbell10** [comment]
Actually #115181 hasn't merged yet
