### ISSUE TITLE
[dynamo] missing support for function `object.__setattr__(obj, name, value)`

### ISSUE THREAD

**Issue by XuehaiPan** [pytorch/pytorch#114964]
### 🐛 Describe the bug

Reference: https://github.com/pytorch/pytorch/pull/114946#discussion_r1412410403

- https://github.com/pytorch/pytorch/pull/114946#discussion_r1412410403

Dynamo does not support `object.__setattr__(obj, name, value)` yet.

For all frozen dataclasses, the assignment statement in `__init__` are `object.__setattr__(obj, name, value)` rather than `obj.<name> = value`.

https://github.com/python/cpython/blob/05a370abd6cdfe4b54be60b3b911f3a441026bb2/Lib/dataclasses.py#L477-L486

```python
def _field_assign(frozen, name, value, self_name):
    # If we're a frozen class, then assign to our fields in __init__
    # via object.__setattr__.  Otherwise, just use a simple
    # assignment.
    #
    # self_name is what "self" is called in this function: don't
    # hard-code "self", since that might be a field name.
    if frozen:
        return f'__dataclass_builtins_object__.__setattr__({self_name},{name!r},{value})'
    return f'{self_name}.{name}={value}'
```

The error:

```text
torch._dynamo.exc.Unsupported: call_method BuiltinVariable(object) __setattr__ [UserDefinedObjectVariable(TreeSpec), ConstantVariable(str), ConstantVariable(int)] {}
```

A minimal script to reproduce:

```python
import dataclasses

import torch


@dataclasses.dataclass
class A:
    a: int


def fn() -> None:
    a = A(1)
    object.__setattr__(a, "a", 2)


comp_out = torch._dynamo.optimize(nopython=True)(fn)()
```

### Versions

main branch

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by shunting314** [comment]
https://github.com/pytorch/pytorch/issues/114966 is also about supporting dataclass in dynamo
