### ISSUE TITLE
[MPS] `nn.Linear` crashes if invoked for 5D tensors with assertion `New volume: xxx should match old volume: xxx'

### ISSUE THREAD

**Issue by chenmingxiang110** [pytorch/pytorch#114942]
### 🐛 Describe the bug

The complete code to reproduce the error:

```python
import numpy as np

import torch
import torchvision
import torch.nn as nn
import torch.optim as optim

class Model(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(*[
            nn.Conv2d(64, 512, 1, stride=1, padding=0, groups=1),
        ])
        self.post = nn.Linear(8, 16)
        return
    
    def forward(self, xs):
        hs = self.net(xs)
        hs = hs.reshape([xs.shape[0], -1, 64, 64, 64]).transpose(1,4)
        hs = self.post(hs)
        return hs

device = "mps"

my_model = Model().to(device)
optimizer = optim.AdamW(my_model.parameters(), lr=1e-4)

batch_size = 2
target = torch.rand(batch_size, 64, 64, 64, 16).to(device)
xs = torch.rand(batch_size, 64, 64, 64).to(device)

pred = my_model(xs)
loss = torch.mean(target - pred)

optimizer.zero_grad()
loss.backward()
optimizer.step()

print(loss.item())
```

The output is as follows:
```
/AppleInternal/Library/BuildRoots/d9889869-120b-11ee-b796-7a03568b17ac/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSNDArray/Kernels/MPSNDArrayIdentity.mm:795: failed assertion `New volume: 4194304 should match old volume: 8388608 [reshapeWithCommandBuffer] MPSNDArrayIdentity.'
zsh: abort      python test.py
```

But if the 'device' is changed to 'cpu', the script can be run with no bug reported.

### Versions

PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.5.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.3
Libc version: N/A

Python version: 3.9.16 (main, Mar  8 2023, 04:29:44)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] onnxruntime==1.15.1
[pip3] open-clip-torch==2.18.0
[pip3] perlin-numpy==0.0.0
[pip3] pytorch-lightning==1.4.2
[pip3] pytorch-wavelets==1.3.0
[pip3] pytorch3d==0.7.4
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchmetrics==0.6.0
[pip3] torchvision==0.16.0
[pip3] torchviz==0.0.2
[conda] _pytorch_select           0.1                       cpu_0
[conda] blas                      1.0                         mkl
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] libmklml                  2019.0.5                      0
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py39h9ed2024_0
[conda] mkl_fft                   1.3.0            py39ha059aab_0
[conda] mkl_random                1.0.2            py39h16bde0e_0
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] open-clip-torch           2.18.0                   pypi_0    pypi
[conda] perlin-numpy              0.0.0                    pypi_0    pypi
[conda] pytorch-lightning         1.4.2                    pypi_0    pypi
[conda] pytorch-wavelets          1.3.0                    pypi_0    pypi
[conda] pytorch3d                 0.7.4                    pypi_0    pypi
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] torchaudio                2.1.0                    pypi_0    pypi
[conda] torchmetrics              0.6.0                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by garyyaoresearch** [comment]
Hey, I failed to reproduce this issue. Nothing crashed with that script. 
Pytorch Nightly + M2.
Possibly Apple sided issue as opposed to PyTorch side?

**Comment by chenmingxiang110** [comment]
> Hey, I failed to reproduce this issue. Nothing crashed with that script. Pytorch Nightly + M2. Possibly Apple sided issue as opposed to PyTorch side?
> 
> One difference in system configuration: My platform: 'macOS-12.5-arm64-arm-64bit' Your platform: 'macOS-10.16-x86_64-i386-64bit' Possibly issue due some irregularity with either your OS or Python version (or both) being Intel supporting?

I reinstalled the environment with
```
CONDA_SUBDIR=osx-arm64 conda create -n py310 python=3.10
```
and the environment is
```
PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.5.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.3
Libc version: N/A

Python version: 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.5.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] torch==2.1.1
[pip3] torchaudio==2.1.1
[pip3] torchvision==0.16.1
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] torch                     2.1.1                    pypi_0    pypi
[conda] torchaudio                2.1.1                    pypi_0    pypi
[conda] torchvision               0.16.1                   pypi_0    pypi
```
and still I am getting the same error.

**Comment by chenmingxiang110** [comment]
> > > Hey, I failed to reproduce this issue. Nothing crashed with that script. Pytorch Nightly + M2. Possibly Apple sided issue as opposed to PyTorch side?
> > > One difference in system configuration: My platform: 'macOS-12.5-arm64-arm-64bit' Your platform: 'macOS-10.16-x86_64-i386-64bit' Possibly issue due some irregularity with either your OS or Python version (or both) being Intel supporting?
> > 
> > 
> > I reinstalled the environment with
> > ```
> > CONDA_SUBDIR=osx-arm64 conda create -n py310 python=3.10
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and the environment is
> > ```
> > PyTorch version: 2.1.1
> > Is debug build: False
> > CUDA used to build PyTorch: None
> > ROCM used to build PyTorch: N/A
> > 
> > OS: macOS 13.5.1 (arm64)
> > GCC version: Could not collect
> > Clang version: 14.0.3 (clang-1403.0.22.14.1)
> > CMake version: version 3.26.3
> > Libc version: N/A
> > 
> > Python version: 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] (64-bit runtime)
> > Python platform: macOS-13.5.1-arm64-arm-64bit
> > Is CUDA available: False
> > CUDA runtime version: No CUDA
> > CUDA_MODULE_LOADING set to: N/A
> > GPU models and configuration: No CUDA
> > Nvidia driver version: No CUDA
> > cuDNN version: No CUDA
> > HIP runtime version: N/A
> > MIOpen runtime version: N/A
> > Is XNNPACK available: True
> > 
> > CPU:
> > Apple M2 Max
> > 
> > Versions of relevant libraries:
> > [pip3] numpy==1.26.2
> > [pip3] torch==2.1.1
> > [pip3] torchaudio==2.1.1
> > [pip3] torchvision==0.16.1
> > [conda] numpy                     1.26.2                   pypi_0    pypi
> > [conda] torch                     2.1.1                    pypi_0    pypi
> > [conda] torchaudio                2.1.1                    pypi_0    pypi
> > [conda] torchvision               0.16.1                   pypi_0    pypi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and still I am getting the same error.
> 
> PyTorch version: 2.2.0a0+gita076a74 Is debug build: False CUDA used to build PyTorch: None ROCM used to build PyTorch: N/A
> 
> OS: macOS 12.5 (arm64) GCC version: Could not collect Clang version: 14.0.0 (clang-1400.0.29.202) CMake version: version 3.26.4 Libc version: N/A
> 
> Python version: 3.12.0 | packaged by Anaconda, Inc. | (main, Oct 2 2023, 12:22:05) [Clang 14.0.6 ] (64-bit runtime) Python platform: macOS-12.5-arm64-arm-64bit Is CUDA available: False CUDA runtime version: No CUDA CUDA_MODULE_LOADING set to: N/A GPU models and configuration: No CUDA Nvidia driver version: No CUDA cuDNN version: No CUDA HIP runtime version: N/A MIOpen runtime version: N/A Is XNNPACK available: True
> 
> CPU: Apple M2
> 
> Versions of relevant libraries: [pip3] numpy==1.26.2 [pip3] optree==0.10.0 [pip3] torch==2.2.0a0+gita076a74 [conda] numpy 1.26.2 pypi_0 pypi [conda] optree 0.10.0 pypi_0 pypi [conda] torch 2.2.0a0+gita076a74 dev_0

OK, so maybe it's not the Python platform's problem. I think it is possibly because of the version of python and torch? I will try out using python 3.12 and torch nightly.

**Comment by chenmingxiang110** [comment]
@garyyaoresearch Hey I have tested on the latest torch-nightly version (torch-2.3.0.dev20240117) and python 3.12, but the problem still appears. I also tested it on my colleagues' device (M1 pro not Max) and the result is the same. Could you please try it on a different device?

PyTorch version: 2.3.0.dev20240117
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.2.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.26.3
Libc version: N/A

Python version: 3.12.0 | packaged by Anaconda, Inc. | (main, Oct  2 2023, 12:22:05) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] torch==2.3.0.dev20240117
[pip3] torchaudio==2.2.0.dev20240117
[pip3] torchvision==0.18.0.dev20240117
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] torch                     2.3.0.dev20240117          pypi_0    pypi
[conda] torchaudio                2.2.0.dev20240117          pypi_0    pypi
[conda] torchvision               0.18.0.dev20240117          pypi_0    pypi

**Comment by malfet** [comment]
And my favorite one line reproducers:
```
% python -c "import torch; x=torch.rand(2, 1, 2, 1, 2, device='mps', requires_grad=True); post=torch.nn.Linear(2, 4).to('mps');y=post(x);y.sum().backward()"
/AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSNDArray/Kernels/MPSNDArrayIdentity.mm:813: failed assertion `New volume: 8 should match old volume: 16 [reshapeWithCommandBuffer] MPSNDArrayIdentity.'

```

**Comment by malfet** [comment]
Following fixes the crash, PR is coming
```diff
diff --git a/aten/src/ATen/native/mps/operations/Linear.mm b/aten/src/ATen/native/mps/operations/Linear.mm
index 4e556189b0f..2b780c18ce6 100644
--- a/aten/src/ATen/native/mps/operations/Linear.mm
+++ b/aten/src/ATen/native/mps/operations/Linear.mm
@@ -159,15 +159,23 @@ static Tensor _mps_linear_backward_input(IntArrayRef input_size, const Tensor& g
   @autoreleasepool {
     string key = "mps_linear_backward_input" + getTensorsStringKey({grad_output, weight_reshaped});
     auto cachedGraph = LookUpOrCreateCachedGraph<CachedGraph>(key, [&](auto* mpsGraph, auto* newCachedGraph) {
-      MPSGraphTensor* weightTensor = mpsGraphRankedPlaceHolder(mpsGraph, weight_reshaped);
-      MPSGraphTensor* gradOutputTensor = mpsGraphRankedPlaceHolder(mpsGraph, grad_output);
-
-      MPSGraphTensor* outputTensor = [mpsGraph matrixMultiplicationWithPrimaryTensor:gradOutputTensor
-                                                                     secondaryTensor:weightTensor
-                                                                                name:nil];
+     newCachedGraph->weightTensor_ = mpsGraphRankedPlaceHolder(mpsGraph, weight_reshaped);
+     newCachedGraph->gradOutputTensor_ = mpsGraphRankedPlaceHolder(mpsGraph, grad_output);
+
+      // MPS matrixMultiplication crashes for 5D+ tensors, see https://github.com/pytorch/pytorch/issues/114942
+      bool needReshape = grad_output.dim() > 4;
+      auto gradOutputTensor = needReshape ? [mpsGraph flatten2DTensor:newCachedGraph->gradOutputTensor_
+                                                                 axis:-1
+                                                                 name:nil]
+                                          : newCachedGraph->gradOutputTensor_;
+
+      auto outputTensor = [mpsGraph matrixMultiplicationWithPrimaryTensor:gradOutputTensor
+                                                          secondaryTensor:newCachedGraph->weightTensor_
+                                                                     name:nil];
+      if (needReshape) {
+        outputTensor = [mpsGraph reshapeTensor:outputTensor withShape:getMPSShape(output) name:nil];
+      }
 
-      newCachedGraph->weightTensor_ = weightTensor;
-      newCachedGraph->gradOutputTensor_ = gradOutputTensor;
       newCachedGraph->outputTensor_ = outputTensor;
     });
```

**Comment by chenmingxiang110** [comment]
@malfet You are awesome!
