### ISSUE TITLE
[PT2.1][torch.compile] empty shape in tracing

### ISSUE THREAD

**Issue by syheliel** [pytorch/pytorch#114936]
### 🐛 Describe the bug

`torch.compile(backend=toy_backend, dynamic=True)(model)` can't trace the shape on 3DRESET correctly. Some tensor have empty shape `[]`

colab reproduce: https://colab.research.google.com/drive/1Xn_OPAD_ixkDx0scSsxaXAdmdZU_9f1A?usp=sharing

### Minified repro

```
!pip uninstall -y torch pytorchvision
!pip3 install --pre torch --extra-index-url https://download.pytorch.org/whl/nightly/cpu
!pip3 install pytorchvideo
import torch
from torch._inductor.decomposition import decompositions as inductor_decomp
from torch._functorch.aot_autograd import aot_autograd_decompositions

import urllib.request
from pytorchvideo.data.encoded_video import EncodedVideo

from torchvision.transforms import Compose, Lambda
from torchvision.transforms._transforms_video import (
    CenterCropVideo,
    NormalizeVideo,
)
from pytorchvideo.transforms import (
    ApplyTransformToKey,
    ShortSideScale,
    UniformTemporalSubsample,
)

def prepare_input():
    device = "cpu"
    side_size = 256
    mean = [0.45, 0.45, 0.45]
    std = [0.225, 0.225, 0.225]
    crop_size = 256
    num_frames = 8
    sampling_rate = 8
    frames_per_second = 30

    # Note that this transform is specific to the slow_R50 model.
    transform = ApplyTransformToKey(
        key="video",
        transform=Compose(
            [
                UniformTemporalSubsample(num_frames),
                Lambda(lambda x: x / 255.0),
                NormalizeVideo(mean, std),
                ShortSideScale(size=side_size),
                CenterCropVideo(crop_size=(crop_size, crop_size)),
            ]
        ),
    )

    # The duration of the input clip is also specific to the model.
    clip_duration = (num_frames * sampling_rate) / frames_per_second
    url_link = (
        "https://dl.fbaipublicfiles.com/pytorchvideo/projects/archery.mp4"
    )
    video_path = "archery.mp4"

    urllib.request.urlretrieve(url_link, video_path)

    # The start_sec should correspond to where the action occurs in the video
    start_sec = 0
    end_sec = start_sec + clip_duration

    # Initialize an EncodedVideo helper class and load the video
    video = EncodedVideo.from_path(video_path)

    # Load the desired clip
    video_data = video.get_clip(start_sec=start_sec, end_sec=end_sec)

    # Apply a transform to normalize the video input
    video_data = transform(video_data)

    # Move the inputs to the desired device
    inputs = video_data["video"]
    inputs = inputs.to(device)
    return inputs[None, ...]

model = torch.hub.load(
    "facebookresearch/pytorchvideo", "slow_r50", pretrained=True
)


input = prepare_input()
import torch.fx
def my_compiler(gm: torch.fx.GraphModule, example_inputs):
    for node in gm.graph.nodes:
        node : torch.fx.Node 
        # print(node.op)
        if node.op == 'placeholder':
            print(node.meta)
    return gm.forward  # return a python callable

output = model(input)

# %%
from torch._decomp import core_aten_decompositions
import torch._functorch
from torch._functorch.aot_autograd import aot_module_simplified
from torch.fx import GraphModule
decomp = core_aten_decompositions()
def toy_backend(gm:GraphModule, sample_inputs:torch.Tensor):
    def my_compiler(gm:GraphModule, sample_inputs:torch.Tensor):
        print("Decomposed fx Graph in Aten IR:")
        for input in sample_inputs:
            assert(input.size != [])
        gm.print_readable()
        return gm
    return aot_module_simplified(gm, sample_inputs, fw_compiler= my_compiler)
torch._dynamo.reset()
fn = torch.compile(backend=toy_backend, dynamic=True)(model)
fn(input)
```

### Versions

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21840  100 21840    0     0   121k      0 --:--:-- --:--:-- --:--:--  121k
Collecting environment information...
PyTorch version: 2.2.0.dev20231130+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.7
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.120+-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4399.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        55 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorchvideo==0.1.5
[pip3] torch==2.2.0.dev20231130+cpu
[pip3] torchaudio==2.1.0+cu118
[pip3] torchdata==0.7.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.16.0
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] Could not collect

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by shunting314** [comment]
I tried 'inductor' backend and it works. Also the assertion happens in your toy backend. Close since I think it's not a issue inside PT2. Feel free to reopen for more discussion.

**Comment by syheliel** [comment]
@shunting314 Thanks for your time! But I can still reproduce the error in [colab](https://colab.research.google.com/drive/1Xn_OPAD_ixkDx0scSsxaXAdmdZU_9f1A?usp=sharing) today. The torch version that I'm using is
```
pytorchvideo                     0.1.5
torch                            2.2.0.dev20231201+cpu
torchaudio                       2.1.0+cu118
torchdata                        0.7.0
torchsummary                     1.5.1
torchtext                        0.16.0
torchvision                      0.16.0+cu118
```
Would you have a look?

**Comment by shunting314** [comment]
@syheliel  did you use 'inductor' backend or your own customized backend?
