### ISSUE TITLE
[CI] Lintrunner takes 60+ min

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#114913]
### 🐛 Describe the bug

See https://github.com/pytorch/pytorch/actions/runs/7052942128/job/19199060568?pr=114883  which is running for nearly 2 hours now
When sshed into it I see 
```
$ ps axf
  PID TTY      STAT   TIME COMMAND
 8318 pts/2    Ss     0:00 bash
 8574 pts/2    R+     0:00  \_ ps axf
    8 pts/1    Ss+    0:00 bash /exec
 3900 pts/1    Sl+    0:07  \_ lintrunner --force-color --all-files --tee-json=lint.json
 3998 pts/1    Sl+    0:00      \_ python3 tools/linter/adapters/clangtidy_linter.py --binary=.lintbin/clang-tidy --build_dir=./build -- @/tmp/.tmpnytM6k
 8294 pts/1    R+    83:57          \_ /pytorch/pytorch/.lintbin/clang-tidy -p=/pytorch/pytorch/build --extra-arg -I/usr/lib/llvm-11/include/openmp --extra-arg -I/opt/conda/envs/py_3.9/include/python3.9 -
```
and the actual command is
```
$ python -c "print(' '.join(open('/proc/8294/cmdline').read().split('\0')))"
/pytorch/pytorch/.lintbin/clang-tidy -p=/pytorch/pytorch/build --extra-arg -I/usr/lib/llvm-11/include/openmp --extra-arg -I/opt/conda/envs/py_3.9/include/python3.9 --extra-arg -I/pytorch/pytorch/third_party/pybind11/include --extra-arg -I/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11 --extra-arg -I/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11 --extra-arg -I/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/backward --extra-arg -I/usr/lib/llvm-14/lib/clang/14.0.0/include --extra-arg -I/usr/local/include --extra-arg -I/usr/include/x86_64-linux-gnu --extra-arg -I/usr/include /pytorch/pytorch/torch/csrc/utils/nested.cpp
```

Which takes less than min to finish:
```
$ time /pytorch/pytorch/.lintbin/clang-tidy -p=/pytorch/pytorch/build --extra-arg -I/usr/lib/llvm-11/include/openmp --extra-arg -I/opt/conda/envs/py_3.9/include/python3.9 --extra-arg -I/pytorch/pytorch/third_party/pybind11/include --extra-arg -I/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11 --extra-arg -I/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11 --extra-arg -I/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/backward --extra-arg -I/usr/lib/llvm-14/lib/clang/14.0.0/include --extra-arg -I/usr/local/include --extra-arg -I/usr/include/x86_64-linux-gnu --extra-arg -I/usr/include /pytorch/pytorch/torch/csrc/utils/nested.cpp 
13787 warnings generated.
Suppressed 13906 warnings (13787 in non-user code, 119 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.

real	0m59.745s
user	0m58.875s
sys	0m0.868s

```

### Versions

CI

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @pytorch/pytorch-dev-infra

**Comment by kit1980** [comment]
This is a continuation of https://github.com/pytorch/pytorch/issues/111709 as clang-tidy scope keep increasing.

**Comment by Skylion007** [comment]
Yeah we may want to break it out into it's own manual stage etc. so that we can still fail fast for simpler errors like lint errors. The fact you have to wait for clang-tidy to finish before seeing any output is rather annoying. Alternatively, we need to start doing caching for clang-tidy to resolve this.

**Comment by malfet** [comment]
> This is a continuation of #111709 as clang-tidy scope keeps increasing.

No, this is quite different: in this case I think clang-tidy hits a deadlock

**Comment by huydhn** [comment]
I add high priority label here if no one objects as lint job starts timing out a lot and that can be seen in trunk now, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/a85df9eb0b35ed8c03e7db3c3cee01c2180fa3ed

**Comment by malfet** [comment]
@huydhn let's try tentatively updating to a more recent clang-tidy and see if this will help

**Comment by Skylion007** [comment]
FYI when updating you may need to remove some newly added checks from the glob. Particularly some "modernize" ones.

**Comment by malfet** [comment]
Ok, here is the 17.0.6 change, but looks like build is a bit skewed:
```
diff --git a/tools/linter/adapters/s3_init_config.json b/tools/linter/adapters/s3_init_config.json
index 85e2402061d..f0c45383233 100644
--- a/tools/linter/adapters/s3_init_config.json
+++ b/tools/linter/adapters/s3_init_config.json
@@ -26,8 +26,8 @@
             "hash": "4ed664cf50bb9fddec2d4170b3d7bbe0135dc5648acbd620b61c8d25a5a2fdb7"
         },
         "Linux": {
-            "download_url": "https://oss-clang-format.s3.us-east-2.amazonaws.com/linux64/15.0.6/clang-tidy",
-            "hash": "8defeb3a2698caca60251f9d682bc08374f1a37eec77d515533affdd03f93add"
+            "download_url": "https://oss-clang-format.s3.us-east-2.amazonaws.com/linux64/17.0.6/clang-tidy",
+            "hash": "f9fdda92ef15078abe5b1a5e33e057212721de4deb645fc99573e6084c5ab968"
         }
     },
     "actionlint": {
```

**Comment by huydhn** [comment]
lintrunner is now back to normal after the mitigation https://github.com/pytorch/pytorch/pull/115124 and takes ~35m on CI https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=lintrunner

Upgrading clang-tidy version is still something we want to do though because it's mentioned on https://github.com/pytorch/pytorch/pull/115124#issuecomment-1848590662 that the issue might have been fixed in the latter releases (17.x)

**Comment by huydhn** [comment]
Given some of the recent tweak we have to separate clang-tidy and the rest https://github.com/pytorch/pytorch/pull/119575, I'm incline to close this one.  We can create a new issue to upgrade clang-tidy version, but that should be tracked separately.  Let me create a new issue for that and close this one.
