### ISSUE TITLE
[dynamo] dynamo does not support dataclasses with `frozen=True`

### ISSUE THREAD

**Issue by XuehaiPan** [pytorch/pytorch#114966]
### 🐛 Describe the bug

Reference: https://github.com/pytorch/pytorch/pull/114946#discussion_r1412413180

- https://github.com/pytorch/pytorch/pull/114946#discussion_r1412413180

A minimal script to reproduce:

```python
import dataclasses

import torch


@dataclasses.dataclass(frozen=True)
class A:
    a: int


def fn() -> None:
    a = A(1)


comp_out = torch._dynamo.optimize(nopython=True)(fn)()
```

The error for statement `a = A(1)`:

```text
torch._dynamo.exc.Unsupported: call_function UserDefinedClassVariable() [ConstantVariable(int)] {}
```

Everything works fine if I remove `frozen=True` from the `@dataclass` decorator.

Maybe also related:

- pytorch/pytorch#114964

### Versions

main branch

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by shunting314** [comment]
Other related issues regarding supporting dataclasses in dynamo:
https://github.com/pytorch/pytorch/issues/114964
