### ISSUE TITLE
Make https://download.pytorch.org/whl/rocm5.6 explorable

### ISSUE THREAD

**Issue by fxmarty** [pytorch/pytorch#115073]
### 🚀 The feature, motivation and pitch

Hi, https://download.pytorch.org/whl/cu118 is explorable but https://download.pytorch.org/whl/rocm5.6 is not (AccessDenied). It would be great to be able to explore ROCm wheels in the same fashion as on PyPI index.

Thank you!

### Alternatives

/

### Additional context

/

cc @seemethere @malfet @osalpekar @atalman @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by malfet** [comment]
It is explorable/PEP-503 compliant, just missing a redirect (I.e. one can explore https://download.pytorch.org/whl/rocm5.6/ )

Let me quickly put a fix in place

**Comment by malfet** [comment]
Done. For posterity, updated the redirect function to https://github.com/pytorch/test-infra/commit/813ccdb88add77180933da02eadeed210d7666f0
