### ISSUE TITLE
Why torch.cuda.comm.broadcast(tensor, devices) choose to ignore devices[0] if tensor is already on GPU

### ISSUE THREAD

**Issue by nicklhy** [pytorch/pytorch#1150]
Why torch.cuda.comm.broadcast(tensor, devices) choose to ignore devices[0] if tensor is already on GPU(line 22-25 in [torch/cuda/comm.py](https://github.com/pytorch/pytorch/blob/master/torch/cuda/comm.py))? A simple test script below shows how this function may produce different results.

```
import torch

def test1():
    x = torch.Tensor(10, 10)
    x_gpus = torch.cuda.comm.broadcast(x, [2, 3])
    print([t.get_device() for t in x_gpus])

def test2():
    x = torch.Tensor(10, 10).cuda()
    x_gpus = torch.cuda.comm.broadcast(x, [2, 3])
    print([t.get_device() for t in x_gpus])

if __name__ == '__main__':
    test1() # -> [2, 3]
    test2() # -> [0, 3]
```

My model training code could crash for this if I choose to run it on a different device than gpu0. You can refer the details in [here](https://discuss.pytorch.org/t/tensors-are-on-different-gpus/1450/4?u=nicklhy).

cc @ngimel

**Comment by albanD** [comment]
Hi,

In the doc of the function ([here](https://github.com/pytorch/pytorch/blob/master/torch/cuda/comm.py#L14)) it says: `Note that it should be like (src, dst1, dst2, ...)` for the list of devices that you give. So it assumes that either the tensor is on cpu and it sends to all device or that the first device that you give him is the one where your tensor is currently in.

Maybe it would be worth raising a proper error message when this supposition is not met?

**Comment by nicklhy** [comment]
Thank you @albanD .
The current implementation works exactly as the doc but I am just wondering the reason behind that.
Because of this design, a simple and clean multi-gpu code like `nn.DataParallel(resnet, device_ids=[1, 2, 3]).cuda()` could crash when executing the forward function(as discussed [here](https://discuss.pytorch.org/t/tensors-are-on-different-gpus/1450)). In order to solve this problem, I have to change every xx.cuda() to xx.cuda(device=gpus[0]) in the training function like below (which looks rather ugly).

```
# net = torch.nn.DataParallel(net, device_ids=gpus).cuda()
net = torch.nn.DataParallel(net, device_ids=gpus).cuda(device_id=gpus[0])
# ...
# loss_criterion = torch.nn.CrossEntropyLoss().cuda()
loss_criterion = torch.nn.CrossEntropyLoss().cuda(device_id=gpus[0])
# ...
# input = input.cuda()
input = input.cuda(device=gpus[0])
# target = target.cuda()
target = target.cuda(device=gpus[0])
```

**Comment by albanD** [comment]
A simple solution for this would be to set the current device to the first element so that everything is created on the right device with `torch.cuda.set_device(gpus[0])`.
That being said I agree that the behaviour of this function may be changed to:
* If the tensor is cpu, just send it to all specified gpus
* If the tensor is on one of the specified gpus, send it to the others
* If the tensor is on gpu but none of the specified one, send it to all specified gpus.
I am not sure how to do that for an list of gpus that is an Iterable though.

We should check with @apaszke but if he agrees with this change, a PR would be welcomed :)

**Comment by nicklhy** [comment]
@albanD , will there be any problems if we simply return a list of tensors which are distributed exactly as the device_ids argument? I think this could be more straightforward than the current one.
