### ISSUE TITLE
undefined reference to `caffe2::ClipTransformRGB'

### ISSUE THREAD

**Issue by githubgsq** [pytorch/pytorch#11509]
hi ,all:
when I compile caffe2, an error appears:
/home/caffe2/framework/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::ClipTransformRGB
the function is defined in './caffe2/video/video_io.h', I also add include_directories() in CMakeLists.txt file, but no effect.
what should I do please?
Thanks.

**Comment by h5713091** [comment]
Same problem. Workaround is to add CAFFE2_API to ClipTransformRGB, ClipTransformOpticalFlow, DecodeMultipleClipsFromVideo functions, but not sure is it really good.

**Comment by githubgsq** [comment]
I set USE_FFMPEG=OFF and the error disappeared.
