### ISSUE TITLE
Does pytorch implement SpatialUpSamplingBilinear layer?

### ISSUE THREAD

**Issue by fengshikun** [pytorch/pytorch#1151]
Hi, I want to load a model trained by torch, which contains the layer "nn.SpatialUpSamplingBilinear", the convert code is simple as blow:

```
import torch
from torch.utils.serialization import load_lua
model = load_lua('model.net')
```

it will generate the exception:
```
T7ReaderException: don't know how to deserialize Lua class nn.SpatialUpSamplingBilinear. If you want to ignore this error and load this object as a dict, specify unknown_classes=True in reader's constructor
```

And I find the ```class torch.nn.UpsamplingBilinear2d``` in pytorch,  does it function like the layer ```nn.SpatialUpSamplingBilinear```?

**Comment by soumith** [comment]
http://pytorch.org/docs/nn.html#upsamplingbilinear2d
