### ISSUE TITLE
[cusparseLt] Unexpectedly High Acceleration Ratio with cusparseLt in PyTorch

### ISSUE THREAD

**Issue by RanchiZhao** [pytorch/pytorch#115154]
### 🐛 Describe the bug

# Description:
I've encountered an issue regarding the acceleration ratio when using cusparseLt for sparse matrix multiplication in PyTorch. Specifically, while executing the following code snippet, I observed a significant acceleration ratio that seems unusual for a simple matrix multiplication task.
# Minimal Reproducible Example:

```python
import torch
import torch.nn.functional as F
torch.manual_seed(0)
torch.cuda.manual_seed(0)

class Linear(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x: torch.Tensor, W: torch.Tensor, B: torch.Tensor):
        ctx.wcsplt = torch.ops.aten._cslt_compress(W)
        ctx.wcspltT = torch.ops.aten._cslt_compress(W.t().contiguous())
        ctx.save_for_backward(x)
        return torch.ops.aten._cslt_sparse_mm(ctx.wcsplt, dense_B=x.t(), bias=B, transpose_result=True)

    @staticmethod
    def backward(ctx, grad_out: torch.Tensor):
        x = ctx.saved_tensors[0]
        return (
            torch.ops.aten._cslt_sparse_mm(ctx.wcsplt, grad_out.t(), transpose_result=True),
            x.t() @ grad_out,
            None
        )

m, k, n = 16384, 4096, 512
stride = 512
a = torch.randn([m, k], device="cuda", dtype=torch.float16, requires_grad=True)
W = torch.randn([n, k], device="cuda", dtype=torch.float16, requires_grad=True)
B = torch.zeros([n], device="cuda", dtype=torch.float16, requires_grad=True)
W_pruned = W.clone()
for i in range(n):
    for j in range(k//stride):
        W_pruned[i][j*stride:j*stride+stride] *= torch.tensor([1, 0, 1, 0] * (stride // 4), device=W.device)

# Timing dense operation
start_time_dense = torch.cuda.Event(enable_timing=True)
end_time_dense = torch.cuda.Event(enable_timing=True)
start_time_dense.record()
out_dense = F.linear(a, W_pruned, B)
end_time_dense.record()
torch.cuda.synchronize()
time_cost_dense = start_time_dense.elapsed_time(end_time_dense)

# Timing sparse operation
start_time_sparse = torch.cuda.Event(enable_timing=True)
end_time_sparse = torch.cuda.Event(enable_timing=True)
start_time_sparse.record()
out_sparse = Linear.apply(a, W_pruned, B)
end_time_sparse.record()
torch.cuda.synchronize()
time_cost_sparse = start_time_sparse.elapsed_time(end_time_sparse)

print("Dense time:", time_cost_dense, "Sparse time:", time_cost_sparse, "Ratio:", time_cost_dense / time_cost_sparse)
assert torch.allclose(out_sparse, out_dense, atol=1e-3), "The outputs of the sparse and dense operations are not close enough."
```
# Observed Results:
The output timings for the dense and sparse operations were 981.0020141601562 ms and 64.95184326171875 ms, respectively, resulting in an acceleration ratio of approximately 15.10352847427716.

# Expected Behavior:
I am uncertain if a 15x acceleration ratio is expected for a simple matrix multiplication task. The observed acceleration seems unusually high, and I am wondering if there could be an underlying issue with the implementation or measurement method.

### Versions

PyTorch version: 2.2.0.dev20231204+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-48-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.0.76
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090
GPU 2: NVIDIA GeForce RTX 4090
GPU 3: NVIDIA GeForce RTX 4090
GPU 4: NVIDIA GeForce RTX 4090
GPU 5: NVIDIA GeForce RTX 4090
GPU 6: NVIDIA GeForce RTX 4090
GPU 7: NVIDIA GeForce RTX 4090

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   52 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz
Stepping:                        6
CPU MHz:                         800.000
BogoMIPS:                        5200.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp_epp avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] numpydoc==1.5.0
[pip3] pytorch-triton==2.1.0+bcad9dabe1
[pip3] torch==2.2.0.dev20231204+cu118
[pip3] torchaudio==2.2.0.dev20231204+cu118
[pip3] torchvision==0.17.0.dev20231204+cu118
[pip3] triton==2.1.0
[conda] _anaconda_depends         2023.09             py311_mkl_1    defaults
[conda] blas                      1.0                         mkl    defaults
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46343    defaults
[conda] mkl-service               2.4.0           py311h5eee18b_1    defaults
[conda] mkl_fft                   1.3.8           py311h5eee18b_0    defaults
[conda] mkl_random                1.2.4           py311hdb19cb5_0    defaults
[conda] numpy                     1.24.3          py311h08b1b3b_1    defaults
[conda] numpy-base                1.24.3          py311hf175353_1    defaults
[conda] numpydoc                  1.5.0           py311h06a4308_0    defaults
[conda] pytorch-cuda              11.8                 h7e8668a_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-triton            2.1.0+bcad9dabe1          pypi_0    pypi
[conda] torch                     2.2.0.dev20231204+cu118          pypi_0    pypi
[conda] torchaudio                2.2.0.dev20231204+cu118          pypi_0    pypi
[conda] torchtriton               2.1.0                     py311    pytorch
[conda] torchvision               0.17.0.dev20231204+cu118          pypi_0    pypi

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by RanchiZhao** [comment]
this is quite interesting and hard to find the bug, so i use a more seemingly correct code demo:
```python
import torch
from torch.sparse import to_sparse_semi_structured, SparseSemiStructuredTensor
from torch.utils.benchmark import Timer
SparseSemiStructuredTensor._FORCE_CUTLASS = False
import numpy as np
torch.manual_seed(114)
torch.cuda.manual_seed(114)

# mask Linear weight to be 2:4 sparse
mask = torch.Tensor([0, 0, 1, 1]).tile((3072, 2560)).cuda().bool()
linear = torch.nn.Linear(10240, 3072).half().cuda().eval()
linear.weight = torch.nn.Parameter((mask * linear.weight * 128).to(torch.int8), requires_grad=False)
# bias = torch.randint(low=0, high=10, size=(3072,), dtype=torch.int32).cuda()
bias = torch.randn(3072, dtype=torch.int32).cuda()

x = (torch.rand(3072, 10240).half() * 127).cuda().to(torch.int8)
print("x: ",x)
print("linear.weight: ",linear.weight)
with torch.inference_mode():
    x_ = x.to(torch.float16)
    weight_ = linear.weight.to(torch.float16)
    bias_ = bias.to(torch.float16)
    dense_output = torch.nn.functional.linear(x_, weight_, bias_)
    dense_output_int8 = torch.from_numpy(np.clip(dense_output.cpu().numpy(), -128, 127)).type(torch.int8).cuda()

    dense_t = Timer(stmt="torch.nn.functional.linear(x, weight, bias)",
                    globals={"x": x_, "weight": weight_, "bias": bias_}).blocked_autorange().median * 1e3
    
    # accelerate via SparseSemiStructuredTensor
    linear.weight_int8 = torch.nn.Parameter(to_sparse_semi_structured(linear.weight), requires_grad=False)
    sparse_output_int8 = torch.nn.functional.linear(x, linear.weight_int8, bias)
    sparse_t_int8 = Timer(stmt="torch.nn.functional.linear(x, weight, bias)",
                    globals={"x": x, "weight": linear.weight_int8, "bias": bias}).blocked_autorange().median * 1e3

    weight_ = torch.nn.Parameter(to_sparse_semi_structured(weight_), requires_grad=False)
    sparse_output_fp16 = torch.nn.functional.linear(x_, weight_, bias_)
    sparse_output_fp16_int8 = torch.from_numpy(np.clip(sparse_output_fp16.cpu().numpy(), -128, 127)).type(torch.int8).cuda()
    sparse_t_fp16 = Timer(stmt="torch.nn.functional.linear(x, weight, bias)",
                    globals={"x": x_, "weight": weight_, "bias": bias_}).blocked_autorange().median * 1e3
    print("dense: ", dense_output_int8)
    print("sparse_int8: ", sparse_output_int8)
    print("sparse_fp16: ", sparse_output_fp16_int8)
    
    difference = torch.abs(sparse_output_int8 - dense_output_int8)

    difference_threshold = 1
    mismatched_positions = torch.nonzero(difference > difference_threshold)

    for position in mismatched_positions:
        pos = tuple(position.tolist())
        sparse_val = sparse_output_int8[pos]
        dense_val = dense_output_int8[pos]
        print(f"Mismatch at position {pos}: sparse={sparse_val}, dense={dense_val}")


    assert torch.allclose(sparse_output_int8, dense_output_int8, atol=2)
    assert torch.allclose(sparse_output_fp16_int8, dense_output_int8, atol=2)
    assert torch.allclose(sparse_output_int8, sparse_output_fp16_int8, atol=0)
    print(f"Sparse_fp16: {sparse_t_fp16:.3f}ms Sparse_int8: {sparse_t_int8:.3f}ms | Speedup: {(sparse_t_fp16 / sparse_t_int8):.3f}x")
    print(f"Dense: {dense_t:.3f}ms Sparse_int8: {sparse_t_int8:.3f}ms | Speedup: {(dense_t / sparse_t_int8):.3f}x")
    print(f"Dense: {dense_t:.3f}ms Sparse_fp16: {sparse_t_fp16:.3f}ms | Speedup: {(dense_t / sparse_t_fp16):.3f}x")
```

and the result here is much more reasonable:
Sparse_fp16: 0.745ms Sparse_int8: 0.229ms | Speedup: 3.263x
Dense: 1.214ms Sparse_int8: 0.229ms | Speedup: 5.313x
Dense: 1.214ms Sparse_fp16: 0.745ms | Speedup: 1.628x
however, the precision of the results is confusing, as you can see here, i need to make atol=2 to pass the code.
```
    assert torch.allclose(sparse_output_int8, dense_output_int8, atol=2)
    assert torch.allclose(sparse_output_fp16_int8, dense_output_int8, atol=2)
    assert torch.allclose(sparse_output_int8, sparse_output_fp16_int8, atol=0)
```
while anthor thing is that, when i make: `bias = torch.randint(low=0, high=10, size=(3072,), dtype=torch.int32).cuda()`,
the miscorrection of precision in result will become larger.

**Comment by RanchiZhao** [comment]
> while anthor thing is that, when i make: bias = torch.randint(low=0, high=10, size=(3072,), dtype=torch.int32).cuda(),

this is because when i do `sparse_output_int8 = torch.nn.functional.linear(x, linear.weight_int8, bias)`
it seems that the bias is not computed in. But for `sparse_output_fp16 = torch.nn.functional.linear(x_, weight_, bias_)`, it works well.

**Comment by alexsamardzic** [comment]
As mentioned [here](https://github.com/pytorch/pytorch/issues/115077#issuecomment-1845040995), data types of argument of linear operator have to match to what underlying cuSPARSELt/CUTLASS library expects.  Again, from what I can see in the code, cuSPARSELt doesn't check for datatype of bias tensor, but in this case it should probably stay `int8` instead.

**Comment by jcaip** [comment]
@RanchiZhao can you try with bias=float32? I think actually bias for cuSPARSELt should always be float, even if the inputs are int8. (Unfortunately this behavior is not documented so no way to know for certain 😠  ) 

But I have an old benchmark script: https://github.com/pytorch/pytorch/blob/cc8f6f56dc8b948896a84f87a56c2298de1288d9/benchmarks/sparse/benchmark_semi_structured_sparsity.py#L51

Here that you can see - in this I only convert weight to int8 and it passed correctness checks with atol=1e-3. From our old benchmarks we see the following timings: Note that this was done with a RC version of cuSPARSELt v0.4.0 so depending on what cuSPARSELt version you are doing you may see different results. We see comparable results for fp16 but for int8, you're results are noticeably faster. 

![image](https://github.com/pytorch/pytorch/assets/8041643/85104358-5331-4724-84f1-4fdca8788963)

Actually, I think Charlie found that blocked_autorange is a terrible way to benchmark these kerenls, can you try using this snippet of code for benchmarking instead:

```
            timer = benchmark.Timer(
                stmt="model(**batch)", globals={"model": model, "batch": batch}
            )
            p50 = timer.timeit(n_iter).median
```

We should change this in the tutorials too, would be happy to accept a PR. 

Your 15x initial speedup is likely due to a combination `requires_grad=True` and cache locality, as @alexsamardzic referred to, as you test dense first and then sparse. We don't support setting grad for semi-structured sparse tensors currently, we should probably throw an error on this
