### ISSUE TITLE
onnx convert issue

### ISSUE THREAD

**Issue by ShuangLiu1992** [pytorch/pytorch#11521]
when converting model to onnx format, .view function with dynamic shape (-1) will be turned into the following. some inference library cannot handle reshape like this and expect the shape to be specified by the reshape layer instead of using a dynamic input.
%15 : Dynamic = onnx::Constant[value=  -1  320 [ CPULongTensor{2} ]](), scope: Net
%16 : Float(64, 320) = onnx::Reshape(%14, %15), scope: Net

code example:

```
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.softmax(x, dim=1)

x = Variable(torch.randn(x.shape, requires_grad=True))

# Export the model
torch_out = torch.onnx.export(model,
                              x.to(device), 
                              "../data/mnist.bin",
                              export_params=True,
                              input_names=["input"], 
                              output_names=["output"],
                              verbose = True)
```

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by spandantiwari** [comment]
@ShuangLiu1992 - the Reshape op with shape as input is supported by ONNX spec. It was added to the ONNX spec a while back. 

One option could be to export to an older opset. Also, if you see anything not supported by the ONNX spec, please feel free to reopen this issue.
