### ISSUE TITLE
Update torch.sparse doc page

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#11524]
after #11232 is done

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @brianjo @mruberry @aocsa

**Comment by weiyangfb** [comment]
is this gonna fix https://github.com/pytorch/pytorch/issues/1303 altogether?

**Comment by SsnL** [comment]
I'm just planning to document basic autograd functionality introduced in #11232

**Comment by mruberry** [comment]
Closing this due to age, unless you'd still like to keep this around, @SsnL?
