### ISSUE TITLE
Segmentation fault on torch.nn.functional.embedding when element in ids is zero and params are empty

### ISSUE THREAD

**Issue by drewshark** [pytorch/pytorch#115239]
### 🐛 Describe the bug

Here is the code to reproduce:

```
import numpy as np
import torch
params = torch.tensor(np.random.rand(4,0), dtype=torch.half)
ids = torch.tensor([[0,51,81]])
# tensor([], size=(4, 0), dtype=torch.float16) tensor([[ 0, 51, 81]])
max_norm = -0.8705713102734194
res = torch.nn.functional.embedding(ids, params, max_norm=max_norm)
```

### Versions

[pip3] numpy==1.23.5
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchvision==0.16.0
[pip3] triton==2.0.0
[conda] blas 1.0 mkl
[conda] cudatoolkit 11.3.1 h2bc3f7f_2
[conda] ffmpeg 4.3 hf484d3e_0 pytorch
[conda] libjpeg-turbo 2.0.0 h9bf148f_0 pytorch
[conda] mkl 2021.4.0 h06a4308_640
[conda] mkl-service 2.4.0 py39h7f8727e_0
[conda] mkl_fft 1.3.1 py39hd3c417c_0
[conda] mkl_random 1.2.2 py39h51133e4_0
[conda] numpy 1.23.5 py39h14f4228_0
[conda] numpy-base 1.23.5 py39h31eccc5_0
[conda] pytorch 2.1.0 py3.9_cpu_0 pytorch
[conda] pytorch-mutex 1.0 cpu pytorch
[conda] torch 2.0.0 pypi_0 pypi
[conda] torchaudio 2.1.0 py39_cpu pytorch
[conda] torchvision 0.16.0 py39_cpu pytorch
[conda] triton 2.0.0 pypi_0 pypi

**Comment by jgong5** [comment]
PyTorch reports the reasonable error message indicating index out of range:
`IndexError: select(): index 51 out of range for tensor of size [4, 0] at dimension 0`

The behavior is expected. I'm closing the issue. Please reopen if you don't think it is correct.

**Comment by drewshark** [comment]
Hi @jgong5 ,

I tried on torch 2.1.0 and torch 2.1.1 and the issue still exists (i.e., a segmentation fault with no error message). I also tried on colab: https://colab.research.google.com/drive/13qB5MuEj6rXC3FUKSfAzRuOfzRO34YCB?usp=sharing. In colab, when executing this code, the system will directly crash and restart.

May I know which pytorch version you are running?

**Comment by malfet** [comment]
@jgong5 not sure why you've closed the issue as indeed it causes the crash...

**Comment by malfet** [comment]
This was fixed by https://github.com/pytorch/pytorch/pull/115183 which is picked to be included in 2.1.2 and 2.2.0 (I assume?)

**Comment by jgong5** [comment]
> @jgong5 not sure why you've closed the issue as indeed it causes the crash...

I used the mainline to verify the problem and got the reasonable error message. I guess it was with your fix so didn't repro the problem.

**Comment by malfet** [comment]
> I used the mainline to verify the problem and got the reasonable error message. I guess it was with your fix so didn't repro the problem.

When validating against latest build, please mention either a nightly build version or commit sha you've run the tests against.
