### ISSUE TITLE
[CLEANUP] variants should always be specified in Declarations.cwrap

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#11536]
It doesn't seem to be specified in a couple of places, requiring this: https://github.com/pytorch/pytorch/blob/af06c99e00180030c2e6178b4535fea409e992a4/aten/src/ATen/preprocess_declarations.py#L225-L226

CC @ezyang

**Comment by jbschlosser** [comment]
Closing since Declarations.cwrap no longer exists.
