### ISSUE TITLE
[inductor][cpu]MobileBertForQuestionAnswering accuracy crash and some models performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#115343]
### 🐛 Describe the bug

MobileBertForQuestionAnswering accuracy crash:
```
loading model: 0it [00:01, ?it/s]cpu  eval  MobileBertForQuestionAnswering     

[2023-12-04 03:23:41,289] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: split
[2023-12-04 03:23:41,290] [0/0] torch._inductor.fx_passes.split_cat: [WARNING] example value absent for node: cat
terminate called after throwing an instance of 'c10::Error'
  what():  index out of bounds: 0 <= tmp17 < 30522L
Exception raised from operator() at /tmp/tmprucskl_y/mi/cmijwettd2gvfsbuy3xlz7owb3idjrliykkdxrp5qglhsvg27kzd.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x7f1a08e41b0e in /workspace/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x7d (0x7f1a08decbe9 in /workspace/pytorch/torch/lib/libc10.so)
frame #2: <unknown function> + 0x16a2 (0x7f19e86816a2 in /tmp/tmprucskl_y/mi/cmijwettd2gvfsbuy3xlz7owb3idjrliykkdxrp5qglhsvg27kzd.so)
frame #3: GOMP_parallel + 0x84 (0x7f1a1ebb2674 in /opt/conda/bin/..//lib/libiomp5.so)
frame #4: kernel + 0x68 (0x7f19e8681c48 in /tmp/tmprucskl_y/mi/cmijwettd2gvfsbuy3xlz7owb3idjrliykkdxrp5qglhsvg27kzd.so)
frame #5: <unknown function> + 0xa052 (0x7f1a1ccc4052 in /opt/conda/lib/python3.8/lib-dynload/../../libffi.so.8)
frame #6: <unknown function> + 0x8925 (0x7f1a1ccc2925 in /opt/conda/lib/python3.8/lib-dynload/../../libffi.so.8)
frame #7: ffi_call + 0xde (0x7f1a1ccc306e in /opt/conda/lib/python3.8/lib-dynload/../../libffi.so.8)
frame #8: _ctypes_callproc + 0x31f (0x7f1a1ccde4af in /opt/conda/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x9013 (0x7f1a1ccd4013 in /opt/conda/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so)
frame #10: _PyObject_MakeTpCall + 0x3bb (0x4e0e1b in /opt/conda/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x490f (0x4dca1f in /opt/conda/bin/python)
frame #12: _PyFunction_Vectorcall + 0x106 (0x4e81a6 in /opt/conda/bin/python)
frame #13: _PyEval_EvalFrameDefault + 0x49b1 (0x4dcac1 in /opt/conda/bin/python)
frame #14: _PyObject_FastCallDict + 0x148 (0x4e0498 in /opt/conda/bin/python)
frame #15: /opt/conda/bin/python() [0x5a83b9]
frame #16: _PyObject_MakeTpCall + 0x3bb (0x4e0e1b in /opt/conda/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x490f (0x4dca1f in /opt/conda/bin/python)
frame #18: _PyObject_FastCallDict + 0x148 (0x4e0498 in /opt/conda/bin/python)
frame #19: _PyObject_Call_Prepend + 0x60 (0x4f1ef0 in /opt/conda/bin/python)
frame #20: /opt/conda/bin/python() [0x5ab487]
frame #21: _PyObject_MakeTpCall + 0x3bb (0x4e0e1b in /opt/conda/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x490f (0x4dca1f in /opt/conda/bin/python)
frame #23: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #24: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /opt/conda/bin/python)
frame #26: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #27: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /opt/conda/bin/python)
frame #29: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #30: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x1153 (0x4d9263 in /opt/conda/bin/python)
frame #32: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #33: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #34: PyObject_Call + 0x24a (0x4f75ca in /opt/conda/bin/python)
frame #35: _PyEval_EvalFrameDefault + 0x2073 (0x4da183 in /opt/conda/bin/python)
frame #36: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #37: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #38: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /opt/conda/bin/python)
frame #39: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #40: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #41: PyObject_Call + 0x24a (0x4f75ca in /opt/conda/bin/python)
frame #42: _PyEval_EvalFrameDefault + 0x2073 (0x4da183 in /opt/conda/bin/python)
frame #43: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #44: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #45: PyObject_Call + 0x24a (0x4f75ca in /opt/conda/bin/python)
frame #46: _PyEval_EvalFrameDefault + 0x2073 (0x4da183 in /opt/conda/bin/python)
frame #47: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #48: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #49: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /opt/conda/bin/python)
frame #50: <unknown function> + 0x7b53a8 (0x7f1a14ddd3a8 in /workspace/pytorch/torch/lib/libtorch_python.so)
frame #51: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #52: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #53: /opt/conda/bin/python() [0x4f5154]
frame #54: PyObject_Call + 0x24a (0x4f75ca in /opt/conda/bin/python)
frame #55: _PyEval_EvalFrameDefault + 0x2073 (0x4da183 in /opt/conda/bin/python)
frame #56: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #57: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #58: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /opt/conda/bin/python)
frame #59: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #60: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)
frame #61: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /opt/conda/bin/python)
frame #62: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /opt/conda/bin/python)
frame #63: _PyFunction_Vectorcall + 0x19c (0x4e823c in /opt/conda/bin/python)

Run failed with return code:  -6
Output:  None
Error:  None
```
Performance regression:
Note: multi threads secnario for models above first *, single thread for models between two *
<p>static_fp32_perf_regression in 2023-12-03</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>pytorch_unet</td>
      <td>1</td>
      <td>0.819096</td>
      <td>0.337740575</td>
      <td>0.27664195402020003</td>
      <td>20.604943</td>
      <td>1</td>
      <td>1.14885</td>
      <td>0.241027771</td>
      <td>0.27690475471334997</td>
      <td>19.949984</td>
      <td>0.71</td>
      <td>1.0</td>
      <td>0.71</td>
      <td>0.97</td>
    </tr>
    <tr>
      <td>ghostnet_100</td>
      <td>128</td>
      <td>2.317894</td>
      <td>0.082793786</td>
      <td>0.191907219806684</td>
      <td>54.944445</td>
      <td>128</td>
      <td>2.599708</td>
      <td>0.073038088</td>
      <td>0.189877701678304</td>
      <td>54.785735</td>
      <td>0.89</td>
      <td>0.99</td>
      <td>0.88</td>
      <td>1.0</td>
    </tr>
    <tr>
      <td>rexnet_100</td>
      <td>128</td>
      <td>2.710228</td>
      <td>0.125230034</td>
      <td>0.33940194458775197</td>
      <td>60.796492</td>
      <td>128</td>
      <td>3.185582</td>
      <td>0.106163788</td>
      <td>0.338193452104616</td>
      <td>58.853034</td>
      <td>0.85</td>
      <td>1.0</td>
      <td>0.85</td>
      <td>0.97</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>pytorch_unet</td>
      <td>1</td>
      <td>0.863325</td>
      <td>5.86597044</td>
      <td>5.0642389301129995</td>
      <td>24.351937</td>
      <td>1</td>
      <td>1.010426</td>
      <td>4.995934186</td>
      <td>5.048021795823237</td>
      <td>20.053311</td>
      <td>0.85</td>
      <td>1.0</td>
      <td>0.85</td>
      <td>0.82</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>

</table><p>dynamic_fp32_perf_regression in 2023-12-03</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>pytorch_unet</td>
      <td>1</td>
      <td>0.822237</td>
      <td>0.331318559</td>
      <td>0.272422377996483</td>
      <td>20.694409</td>
      <td>1</td>
      <td>1.174303</td>
      <td>0.232050434</td>
      <td>0.272497520797502</td>
      <td>20.032846</td>
      <td>0.7</td>
      <td>1.0</td>
      <td>0.7</td>
      <td>0.97</td>
    </tr>
    <tr>
      <td>ghostnet_100</td>
      <td>128</td>
      <td>2.275558</td>
      <td>0.08282059800000001</td>
      <td>0.18846307434368403</td>
      <td>56.994647</td>
      <td>128</td>
      <td>2.572816</td>
      <td>0.07256759</td>
      <td>0.18670305663344</td>
      <td>56.773169</td>
      <td>0.88</td>
      <td>0.99</td>
      <td>0.88</td>
      <td>1.0</td>
    </tr>
    <tr>
      <td>tf_mixnet_l</td>
      <td>128</td>
      <td>1.609034</td>
      <td>0.40305641400000003</td>
      <td>0.6485314740440761</td>
      <td>107.791961</td>
      <td>128</td>
      <td>1.814695</td>
      <td>0.356659563</td>
      <td>0.647228325678285</td>
      <td>105.663995</td>
      <td>0.89</td>
      <td>1.0</td>
      <td>0.88</td>
      <td>0.98</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>pytorch_unet</td>
      <td>1</td>
      <td>0.865978</td>
      <td>5.827983287</td>
      <td>5.046905310909686</td>
      <td>24.306351</td>
      <td>1</td>
      <td>1.051327</td>
      <td>4.802921251</td>
      <td>5.049440790050077</td>
      <td>18.957621</td>
      <td>0.82</td>
      <td>1.0</td>
      <td>0.82</td>
      <td>0.78</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>

</table><p>static fp32 cpp wrapper performance regression in 2023-12-03</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>pytorch_unet</td>
      <td>1</td>
      <td>0.830754</td>
      <td>0.32651801599999997</td>
      <td>0.271256147864064</td>
      <td>15.81132</td>
      <td>1</td>
      <td>1.207526</td>
      <td>0.221430736</td>
      <td>0.267383370919136</td>
      <td>15.22189</td>
      <td>0.69</td>
      <td>0.99</td>
      <td>0.68</td>
      <td>0.96</td>
    </tr>
    <tr>
      <td>rexnet_100</td>
      <td>128</td>
      <td>2.829799</td>
      <td>0.119897264</td>
      <td>0.339285157769936</td>
      <td>27.874995</td>
      <td>128</td>
      <td>3.173716</td>
      <td>0.105871542</td>
      <td>0.33600620679007204</td>
      <td>25.544353</td>
      <td>0.89</td>
      <td>0.99</td>
      <td>0.88</td>
      <td>0.92</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>pytorch_unet</td>
      <td>1</td>
      <td>0.866215</td>
      <td>5.791156176</td>
      <td>5.01638634699384</td>
      <td>19.442348</td>
      <td>1</td>
      <td>1.046234</td>
      <td>4.82437859</td>
      <td>5.047428909730061</td>
      <td>14.605576</td>
      <td>0.83</td>
      <td>1.01</td>
      <td>0.83</td>
      <td>0.75</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>

</table><p>dynamic_fp32_cppwrapper_performance regression in 2023-12-03</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>pytorch_unet</td>
      <td>1</td>
      <td>0.823691</td>
      <td>0.330448337</td>
      <td>0.27218732115186695</td>
      <td>15.712016</td>
      <td>1</td>
      <td>1.203345</td>
      <td>0.226223875</td>
      <td>0.27222536886187504</td>
      <td>15.240562</td>
      <td>0.68</td>
      <td>1.0</td>
      <td>0.68</td>
      <td>0.97</td>
    </tr>
    <tr>
      <td>tf_mixnet_l</td>
      <td>128</td>
      <td>1.651379</td>
      <td>0.394505804</td>
      <td>0.6514786001037159</td>
      <td>86.787893</td>
      <td>128</td>
      <td>1.846383</td>
      <td>0.351347003</td>
      <td>0.648721133440149</td>
      <td>85.687468</td>
      <td>0.89</td>
      <td>1.0</td>
      <td>0.89</td>
      <td>0.99</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>pytorch_unet</td>
      <td>1</td>
      <td>0.857412</td>
      <td>5.891143518</td>
      <td>5.0511371460554155</td>
      <td>19.807222</td>
      <td>1</td>
      <td>1.057272</td>
      <td>4.773578356</td>
      <td>5.046970735604832</td>
      <td>14.722023</td>
      <td>0.81</td>
      <td>1.0</td>
      <td>0.81</td>
      <td>0.74</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>6fc9d89</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>db62484</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>c1e2095</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>94126be6</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+gitdf0c1b3</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.17.0a0+893b4ab</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.1.1+db62484</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>

Repro

[inductor_single_run.sh ](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple/single inference performance torchbench/huggingface/timm_models model float32 first static/dynamic default/cpp 0
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/3d47b92dfbe19362fb6e98f142b2c79b9db7645c
[torchbench-pytorch_unet-inference-float32-static-cpp-performance-multiple-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13600740/torchbench-pytorch_unet-inference-float32-static-cpp-performance-multiple-drop_guilty_commit.log)

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by chuanqi129** [comment]
Seems the commit PR #114520 has been reverted. Let's wait the PR re-land.

**Comment by leslie-fang-intel** [comment]
Check latest Master: cd47e335d1939a2c7f72cd06fb50cfbf0dd20be6, `MobileBertForQuestionAnswering` passes performance run with default and cppwrapper without crash
```
numactl -C 56-111 --membind=1 python benchmarks/dynamo/huggingface.py --performance --float32 -dcpu -n50 --no-skip --dashboard --only MobileBertForQuestionAnswering --inference --freezing --timeout 9000 --backend=inductor --output=./test.csv

numactl -C 56-111 --membind=1 python benchmarks/dynamo/huggingface.py --performance --float32 -dcpu -n50 --no-skip --dashboard --only MobileBertForQuestionAnswering --inference --cpp-wrapper --freezing --timeout 9000 --backend=inductor --output=./test.csv
```
