### ISSUE TITLE
[inductor][cpu]rexnet100 dynamic FP32 multiple threads performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#115346]
### 🐛 Describe the bug

<p>dynamic_FP32_multiple_perf_regression in 2023-12-03</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>rexnet_100</td>
      <td>128</td>
      <td>2.637637</td>
      <td>0.127494719</td>
      <td>0.336284788139003</td>
      <td>63.194334</td>
      <td>128</td>
      <td>3.043876</td>
      <td>0.110155835</td>
      <td>0.33530070241646</td>
      <td>61.086464</td>
      <td>0.87</td>
      <td>1</td>
      <td>0.86</td>
      <td>0.97</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>6fc9d89</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>db62484</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>c1e2095</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>

</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>94126be6</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+gitdf0c1b3</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.17.0a0+893b4ab</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.1.1+db62484</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>

Repro
[inductor_single_run.sh ](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
`bash inductor_single_run.sh multiple/single inference performance timm_models rexnet100 float32 first dynamic default 0`
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/afbaa0c1650cf15100fb5dc579ceeba24fb8665a
[timm_models-rexnet_100-inference-float32-dynamic-default-performance-multiple-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13601179/timm_models-rexnet_100-inference-float32-dynamic-default-performance-multiple-drop_guilty_commit.log)

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @WeizhuoZhang-intel @chuanqi129

**Comment by Xia-Weiwen** [comment]
The oneDNN update caused the issues. They have been reported to oneDNN team.

**Comment by Xia-Weiwen** [comment]
For the issue https://github.com/pytorch/pytorch/issues/115823, we found oneDNN matmul perf regression. Will need their fix.

**Comment by leslie-fang-intel** [comment]
Waiting for fixing of hf_T5_generate in oneDNN.

**Comment by chuanqi129** [comment]
Fixed PR https://github.com/pytorch/pytorch/pull/120767 has been landed
