### ISSUE TITLE
`torch.set_default_device` does not affect `torch._C._get_default_device`

### ISSUE THREAD

**Issue by tringwald** [pytorch/pytorch#115333]
### 🐛 Describe the bug

See title. With `torch.set_default_tensor_type`, the default device is switched normally. However, that function is deprecated now and its replacement `torch.set_default_device` doesn't affect `torch._C._get_default_device`.

```python3
>>> import torch
torch.>>> torch.__version__
'2.1.1'
>>> torch._C._get_default_device()
'cpu'
>>> torch.set_default_device('cuda')
>>> torch._C._get_default_device()
'cpu'
>>> torch.set_default_tensor_type(torch.cuda.FloatTensor)
>>> torch._C._get_default_device()
'cuda'
```

### Versions

torch==`2.1.1` and also latest `main`

cc @albanD

**Comment by albanD** [comment]
This is expected AFAIK _get_default_device() has to do with the default tensor type and not the default device (contrary to what the name suggests). 
But that API is private, do you actually need it?

We can definitely add a `torch.get_default_device()` that will properly work with `torch.set_default_device()` and `with torch.device()` context manager if you need it.

**Comment by tringwald** [comment]
I personally don't need it, but if we have `torch.set_default_device`, we should probably also offer `torch.get_default_device` publicly. I've seen people do some workarounds like `torch.ones(0).device` to get the default device instead, which is rather cumbersome.

**Comment by albanD** [comment]
Sounds good to me.
