### ISSUE TITLE
Deterministic decomp for `replication_pad_1d/3d`

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#115395]
#111590 added a decomp for `replication_pad_2d` that gets called on CUDA tensors when deterministic mode is turned on, in order to make the backward function deterministic. However, the implementation should be modified to support any number of dimensions so that `replication_pad_1d` and `replication_pad_3d` can use it as well, since they are still nondeterministic for CUDA backward

cc @mruberry

**Comment by isuruf** [comment]
https://github.com/pytorch/pytorch/pull/115113 should partially fix this.
