### ISSUE TITLE
NotImplementedError: Cannot access storage of SparseCsrTensorImpl

### ISSUE THREAD

**Issue by jdenhof** [pytorch/pytorch#115330]
### 🐛 Describe the bug

I have an IterableDataset that is being passed in the data loader. The Dataset yields a sparse_csr_tensor. This is what is currently Exception being thrown. I have a duplicate MapDataset that is identical in logic to the IterableDataset but instead returns the in __getitem__ of course. I have set pin_memory to false and get the same issue. I can include more of my code if needed if there is reason to believe this is my own implementation issue. Everything is being ran on one GPU.

```python
 train_data = DataLoader(
        train_set,
        worker_init_fn=worker_init_fn,
        num_workers=world_size,
        shuffle=False,
        pin_memory=True, # pin_memory_device not set so default is cpu 
        prefetch_factor=1,
        persistent_workers=True,
    )

Traceback (most recent call last):
  File "/home/denhofja/D-MMVAE/src/main.py", line 160, in <module>
    main(args, world_size=world_size)
  File "/home/denhofja/D-MMVAE/src/main.py", line 152, in main
    trainer.train(args.total_epochs)
  File "/home/denhofja/D-MMVAE/src/Trainer.py", line 48, in train
    self._run_epoch(epoch)
  File "/home/denhofja/D-MMVAE/src/Trainer.py", line 55, in _run_epoch
    for source in self._loader:
  File "/cm/shared/venv/python/3.9.18/ml-python39/lib64/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/cm/shared/venv/python/3.9.18/ml-python39/lib64/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/cm/shared/venv/python/3.9.18/ml-python39/lib64/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/cm/shared/venv/python/3.9.18/ml-python39/lib64/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
NotImplementedError: Caught NotImplementedError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/cm/shared/venv/python/3.9.18/ml-python39/lib64/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/cm/shared/venv/python/3.9.18/ml-python39/lib64/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 42, in fetch
    return self.collate_fn(data)
  File "/cm/shared/venv/python/3.9.18/ml-python39/lib64/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/cm/shared/venv/python/3.9.18/ml-python39/lib64/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/cm/shared/venv/python/3.9.18/ml-python39/lib64/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in collate_tensor_fn
    storage = elem._typed_storage()._new_shared(numel, device=elem.device)
  File "/cm/shared/venv/python/3.9.18/ml-python39/lib64/python3.9/site-packages/torch/_tensor.py", line 242, in _typed_storage
    untyped_storage = self.untyped_storage()
NotImplementedError: Cannot access storage of SparseCsrTensorImpl
```

### Versions

PyTorch version: 2.1.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux 9.2 (Plow) (x86_64)
GCC version: (GCC) 11.2.0
Clang version: Could not collect
CMake version: version 3.26.5
Libc version: glibc-2.34

Python version: 3.9.18 (main, Sep  7 2023, 00:00:00)  [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (64-bit runtime)
Python platform: Linux-5.14.0-284.18.1.el9_2.x86_64-x86_64-with-glibc2.34
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              1
Core(s) per socket:              12
Socket(s):                       2
Stepping:                        7
CPU max MHz:                     3700.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        5400.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
L1d cache:                       768 KiB (24 instances)
L1i cache:                       768 KiB (24 instances)
L2 cache:                        24 MiB (24 instances)
L3 cache:                        38.5 MiB (2 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0,4,8,12,16,20
NUMA node1 CPU(s):               1,5,9,13,17,21
NUMA node2 CPU(s):               2,6,10,14,18,22
NUMA node3 CPU(s):               3,7,11,15,19,23
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] torch==2.1.1+cu118
[pip3] torchaudio==2.1.1+cu118
[pip3] torchvision==0.16.1+cu118
[pip3] triton==2.1.0
[conda] Could not collect

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip @SsnL @VitalyFedyunin @ejguan @dzhulgakov

**Comment by cpuhrsch** [comment]
@jdenhof - I think this might be fixed in the nightlies and thus next release. Do you mind trying this with a recent nightly? Thank you.

**Comment by jdenhof** [comment]
@cpuhrsch - I ran it across torch==2.2.0dev20231208+cu121. Findings: I ran into a different error where I did not set the batch_size in the data loader which defaults to 1 which means the following would always execute:
```python
if batch_size is not None and batch_sampler is None:
            # auto_collation without custom batch_sampler
            batch_sampler = BatchSampler(sampler, batch_size, drop_last)
```

Since the batch_sampler is defined the auto_collate is set to true. It would be nice to have a better indication that batch_size needs to be set to None to prevent auto_collition but I recognize this is expected behavior from the DataLoader, however I now receive a NotImplementedError: Caught NotImplementedError in pin memory thread for device 0. with the same stack trace as before. When I set pin_memory to false it works as expected.

**Comment by cpuhrsch** [comment]
Hm, interesting. Can you share more context so we can try to run this on our end?

**Comment by jdenhof** [comment]
This is the repo that throws the error. https://github.com/jdenhof/D-MMVAE/tree/local

NotImplementedError: Caught NotImplementedError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/home/denhofja/D-MMVAE/.venv/lib64/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 36, in do_one_step
    data = pin_memory(data, device)
  File "/home/denhofja/D-MMVAE/.venv/lib64/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 57, in pin_memory
    return data.pin_memory(device)
NotImplementedError: Could not run 'aten::_pin_memory' with arguments from the 'SparseCsrCUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_pin_memory' is only available for these backends: [CUDA, Meta, NestedTensorCPU, NestedTensorCUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CUDA: registered at aten/src/ATen/RegisterCUDA.cpp:44411 [kernel]
Meta: registered at ../aten/src/ATen/core/MetaFallbackKernel.cpp:23 [backend fallback]
NestedTensorCPU: registered at aten/src/ATen/RegisterNestedTensorCPU.cpp:775 [kernel]
NestedTensorCUDA: registered at aten/src/ATen/RegisterNestedTensorCUDA.cpp:931 [kernel]
BackendSelect: registered at aten/src/ATen/RegisterBackendSelect.cpp:807 [kernel]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:154 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ../aten/src/ATen/functorch/DynamicLayer.cpp:498 [backend fallback]
Functionalize: registered at ../aten/src/ATen/FunctionalizeFallbackKernel.cpp:324 [backend fallback]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ../aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ../aten/src/ATen/native/NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ../aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradHIP: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradMPS: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradIPU: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradXPU: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradVE: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradLazy: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradMTIA: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradMeta: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_0.cpp:17339 [autograd kernel]
Tracer: registered at ../torch/csrc/autograd/generated/TraceType_0.cpp:16968 [kernel]
AutocastCPU: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:378 [backend fallback]
AutocastCUDA: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:244 [backend fallback]
FuncTorchBatched: registered at ../aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:720 [backend fallback]
BatchedNestedTensor: registered at ../aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:746 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ../aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ../aten/src/ATen/LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ../aten/src/ATen/functorch/TensorWrapper.cpp:203 [backend fallback]
PythonTLSSnapshot: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:162 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ../aten/src/ATen/functorch/DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:166 [backend fallback]
PythonDispatcher: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:158 [backend fallback]


Above is more context behind the error exception. However to give more context behind my problem, I have a dataset of 100 chunks of (275000, 60000) 98% sparse csr_matrices. In order to simulate random access I have a process running to load and shuffle the chunks in random order per epoch and then get the chunk from the queue when needed and splice the chunk to form batches to return in my iterator. I feel like I am abusing the functionality of the data loader by doing this but it's the only way I can think of having the chunks needed in memory without loading the chunk every iteration. 

I am aware this is out of the scope of the actual bug but if you have any suggestions they would be greatly appreciated.  

I will put together a minimal reproducible example below.

**Comment by jdenhof** [comment]
Ran with the following:     torchrun  --standalone --nproc_per_node=1 main.py 
```python
import torch
import os

if __name__ == "__main__":
    from torch.distributed import init_process_group, destroy_process_group
    init_process_group(backend="nccl") # DDP Setup

    if not torch.cuda.is_available():
        devices = "cpu"
    else:
        devices = [f"cuda:{i}" for i in range(torch.cuda.device_count())]
    assert(devices is not None and devices == "cpu" or len(devices) > 0)
    print(f"Main running with device(s): {devices}")

    from torch.utils.data import IterableDataset
    class SparseDataset(IterableDataset):
        def __iter__(self):
            for _ in range(32):
                yield torch.rand(1, 256).to_sparse_csr()

    from torch import nn
    model = nn.Sequential(nn.Linear(256, 128), nn.Linear(128, 32))

    optimizer = torch.optim.Adam(model.parameters()) # TODO: Use distributed optimizer

    from torch.utils.data import DataLoader
    loader = DataLoader(
        SparseDataset(),
        num_workers=2,
        batch_size=None,
        shuffle=False,
        pin_memory=True, # pin_memory_device not set so default is cpu 
        prefetch_factor=2,
        persistent_workers=True,
    )

    local_rank = int(os.environ["LOCAL_RANK"])
    from torch.nn.parallel import DistributedDataParallel
    model = DistributedDataParallel(model.to(local_rank), device_ids=[local_rank])
    for _ in range(2):
        for source in loader:
            source = source.to(local_rank)
            optimizer.zero_grad()
            output, mean, logvar = model(source)
            recon_loss = torch.nn.CrossEntropyLoss()(output, source.to_dense())
            kld = -0.5 * torch.sum(1 + logvar - mean.pow(2) - logvar.exp())
            loss = recon_loss + kld
            loss.backward()
            optimizer.step()

    destroy_process_group()
    print("DONE")
    ```

**Comment by pearu** [comment]
Here is a simple reproducer:
```python
import torch
from torch.utils.data import IterableDataset
from torch.utils.data import DataLoader

class SparseDataset(IterableDataset):
    def __iter__(self):
        yield torch.rand(1, 16).to_sparse_csr()

loader = DataLoader(
    SparseDataset(),
    batch_size=None,
    pin_memory=True
)

for source in loader:
    source
```
that results in
```
NotImplementedError: Could not run 'aten::_pin_memory' with arguments from the 'SparseCsrCUDA' backend
```

A prototype of the fix is:
```
$ git diff
diff --git a/torch/utils/data/_utils/pin_memory.py b/torch/utils/data/_utils/pin_memory.py
index f94342a6401..053856df494 100644
--- a/torch/utils/data/_utils/pin_memory.py
+++ b/torch/utils/data/_utils/pin_memory.py
@@ -54,6 +54,11 @@ def _pin_memory_loop(in_queue, out_queue, device_id, done_event, device):
 
 def pin_memory(data, device=None):
     if isinstance(data, torch.Tensor):
+        if data.layout is torch.sparse_csr:
+            compressed_indices = data.crow_indices().pin_memory(device)
+            plain_indices = data.col_indices().pin_memory(device)
+            values = data.values().pin_memory(device)
+            return torch.sparse_compressed_tensor(compressed_indices, plain_indices, values, data.shape, layout=data.layout)
         return data.pin_memory(device)
     elif isinstance(data, (str, bytes)):
         return data
```

**Comment by marcus-r-kelly** [comment]
I am also running into this issue

**Comment by jdenhof** [comment]
@pearu Any update on pin_memory support for sparse tensors?
