### ISSUE TITLE
[inductor][cpu]pytorch_CycleGAN_and_pix2pix and basic_gnn_gcn FP32 cpp_wrapper performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#115345]
### 🐛 Describe the bug

<p>static_FP32_cpp_wrapper_multiple_perf_regression in 2023-12-03</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>pytorch_CycleGAN_and_pix2pix</td>
      <td>1</td>
      <td>0.969578</td>
      <td>0.038750373000000005</td>
      <td>0.03757150915259401</td>
      <td>15.380082</td>
      <td>1</td>
      <td>1.107261</td>
      <td>0.034535583</td>
      <td>0.038239904168163</td>
      <td>15.215291</td>
      <td>0.88</td>
      <td>1.02</td>
      <td>0.89</td>
      <td>0.99</td>
    </tr>
  </tbody>

</table><p>dynamic_FP32_cpp_wrapper_single in 2023-12-03</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>basic_gnn_gcn</td>
      <td>1</td>
      <td>1.329611</td>
      <td>0.07655149400000001</td>
      <td>0.10178370848883403</td>
      <td>35.626225</td>
      <td>1</td>
      <td>1.47995</td>
      <td>0.068214428</td>
      <td>0.1009539427186</td>
      <td>35.184321</td>
      <td>0.9</td>
      <td>0.99</td>
      <td>0.89</td>
      <td>0.99</td>
    </tr>
    <tr>
      <td>pytorch_CycleGAN_and_pix2pix</td>
      <td>1</td>
      <td>0.961535</td>
      <td>0.753522143</td>
      <td>0.724537913769505</td>
      <td>15.200484</td>
      <td>1</td>
      <td>1.105849</td>
      <td>0.673667241</td>
      <td>0.744974244792609</td>
      <td>14.698882</td>
      <td>0.87</td>
      <td>1.03</td>
      <td>0.89</td>
      <td>0.97</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>6fc9d89</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>db62484</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>c1e2095</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>94126be6</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+gitdf0c1b3</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.17.0a0+893b4ab</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.1.1+db62484</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>

Repro
[inductor_single_run.sh ](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple/single inference performance torchbench model float32 first static/dynamic cpp 0
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/0de67e7949b899a90911f7249d5ccece34e46211
[torchbench-pytorch_CycleGAN_and_pix2pix-inference-float32-dynamic-cpp-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13600884/torchbench-pytorch_CycleGAN_and_pix2pix-inference-float32-dynamic-cpp-performance-single-drop_guilty_commit.log)

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @WeizhuoZhang-intel @chuanqi129

**Comment by chunyuan-w** [comment]
@chuanqi129 will help double confirm the guilty commit of this issue.

**Comment by zxd1997066** [comment]
After double check, the suspected guilty is commit: https://github.com/pytorch/pytorch/commit/Suspected guilty commit: https://github.com/pytorch/pytorch/commit/0de67e7949b899a90911f7249d5ccece34e46211
[torchbench-pytorch_CycleGAN_and_pix2pix-inference-float32-static-cpp-performance-multiple-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13722206/torchbench-pytorch_CycleGAN_and_pix2pix-inference-float32-static-cpp-performance-multiple-drop_guilty_commit.log)

**Comment by chunyuan-w** [comment]
https://github.com/pytorch/pytorch/commit/0de67e7949b899a90911f7249d5ccece34e46211 is an accuracy fix which has potential perf impact. @Valentine233 could you please help confirm if this perf degradation is as expected?

**Comment by Valentine233** [comment]
> [0de67e7](https://github.com/pytorch/pytorch/commit/0de67e7949b899a90911f7249d5ccece34e46211) is an accuracy fix which has potential perf impact. @Valentine233 could you please help confirm if this perf degradation is as expected?

I've checked and the perf regression is as expected.
