### ISSUE TITLE
Large negative indexing on an empty tensor result in segmentation fault

### ISSUE THREAD

**Issue by drewshark** [pytorch/pytorch#115415]
### 🐛 Describe the bug

Here is the code to reproduce, the pytorch version I am using is: 2.1.0+cu118.

```
import torch
tensor = torch.tensor([], dtype=torch.float32)
index = -9223372036854775808
tensor[index]
```

### Versions

[pip3] numpy==1.23.5
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchvision==0.16.0
[pip3] triton==2.0.0
[conda] blas 1.0 mkl
[conda] cudatoolkit 11.3.1 h2bc3f7f_2
[conda] ffmpeg 4.3 hf484d3e_0 pytorch
[conda] libjpeg-turbo 2.0.0 h9bf148f_0 pytorch
[conda] mkl 2021.4.0 h06a4308_640
[conda] mkl-service 2.4.0 py39h7f8727e_0
[conda] mkl_fft 1.3.1 py39hd3c417c_0
[conda] mkl_random 1.2.2 py39h51133e4_0
[conda] numpy 1.23.5 py39h14f4228_0
[conda] numpy-base 1.23.5 py39h31eccc5_0
[conda] pytorch 2.1.0 py3.9_cpu_0 pytorch
[conda] pytorch-mutex 1.0 cpu pytorch
[conda] torch 2.0.0 pypi_0 pypi
[conda] torchaudio 2.1.0 py39_cpu pytorch
[conda] torchvision 0.16.0 py39_cpu pytorch
[conda] triton 2.0.0 pypi_0 pypi

cc @albanD @ezyang

**Comment by colesbury** [comment]
Thanks for the bug report. I can reproduce the issue. It's limited to `-9223372036854775808`, which is `-2**63` (`INT64_MIN`).

cc @albanD, seems like it would be worth fixing.

**Comment by albanD** [comment]
It is being picked up as a symint for some reason...

**Comment by tringwald** [comment]
> It is being picked up as a symint for some reason...

Constructing a `TensorIndex` from an `int64_t` seems to make it a `SymInt´:

https://github.com/pytorch/pytorch/blob/fb199479624735c09e5a42073b0377a76e24f05b/aten/src/ATen/TensorIndexing.h#L129

and then the pointer logic for getting the `SymNodeImpl` doesn't work out anymore as it assumes the upper bits are reserved and the index in this case is large enough to actually use those bits.
https://github.com/pytorch/pytorch/blob/fb199479624735c09e5a42073b0377a76e24f05b/c10/core/SymInt.h#L269-L277

**Comment by albanD** [comment]
I though this would nicely error out... @ezyang would know what is the latest here.

**Comment by tringwald** [comment]
Seems like my previous post was only partially correct. Here's what actually happens:

- We create a `SymInt` with value `-9223372036854775808` (`-INT64_MAX`)
- We negate that during some check in `applySelect()`
- `-(-9223372036854775808)` would be `+9223372036854775808` which overflows INT64 by 1 right back to `-9223372036854775808`
- Now comes the fun part:

```cpp
#include <iostream>
#include <bitset>
using namespace std;
int main() {
  static constexpr int64_t MAX_UNREPRESENTABLE_INT =  -1LL & static_cast<int64_t>(~(1ULL << 62));
  __int64_t a = -9223372036854775808LL;
  cout << a << endl; 
  cout << -a << endl; 
  cout << MAX_UNREPRESENTABLE_INT << endl; 

  cout << (a > MAX_UNREPRESENTABLE_INT) << endl;  // 0
  cout << ((-a) > MAX_UNREPRESENTABLE_INT) << endl;  // 1  <-- what?
  auto b = -a; 
  cout << (b > MAX_UNREPRESENTABLE_INT) << endl;  // 0  <-- but with the intermediate variable it's false?

  cout << bitset<64>(a) << endl;
  cout << bitset<64>(-a) << endl; 
  cout << bitset<64>(MAX_UNREPRESENTABLE_INT) << endl;
  return 0;
}
```
```
-9223372036854775808
-9223372036854775808
-4611686018427387905
0
1
0
1000000000000000000000000000000000000000000000000000000000000000
1000000000000000000000000000000000000000000000000000000000000000
1011111111111111111111111111111111111111111111111111111111111111
```

Apparently the compiler does some questionable optimization there? Eventually, this will trick our `is_heap_allocated()` test and we later interpret the `int64` as a pointer which will of course segfault.

Maybe we should error out when trying to negate `-INT64_MAX` (or generally when some op would overflow)?

**Comment by albanD** [comment]
I think the issue boils down to the following compiler warning:
```
<source>:7:18: warning: integer constant is so large that it is unsigned
    7 |   __int64_t a = -9223372036854775808LL;
```
And then UB ensues.

Running with godbolt in O3 is pretty showing: https://godbolt.org/z/TGqne5dj6  gcc returns a hardcoded 1 while clang returns a hardcoded 0.

**Comment by tringwald** [comment]
Not sure if the warning has anything to do with it. When replacing the literal definition with `numeric_limits`, the warning goes away but the behavior stays the same. Again, `clang` is correct either way.

```python3
#include <iostream>
#include <bitset>
#include <limits>
using namespace std;
int main() {
  static constexpr int64_t MAX_UNREPRESENTABLE_INT =  -1LL & static_cast<int64_t>(~(1ULL << 62));
  int64_t a = numeric_limits<int64_t>::min();
  cout << a << endl; 
  cout << -a << endl; 
  cout << MAX_UNREPRESENTABLE_INT << endl; 

  cout << (a > MAX_UNREPRESENTABLE_INT) << endl;  // 0
  cout << ((-a) > MAX_UNREPRESENTABLE_INT) << endl;  // 1  <-- what?
  auto b = -a; 
  cout << (b > MAX_UNREPRESENTABLE_INT) << endl;  // 0  <-- but with the intermediate variable it's false?

  cout << bitset<64>(a) << endl;
  cout << bitset<64>(-a) << endl; 
  cout << bitset<64>(MAX_UNREPRESENTABLE_INT) << endl;
  return 0;
}
```

I guess we have two options here:
- Fix the symptom by treating the compiler bug
- Throw an error when an overflow would occur in `SymInt` math. This should probably not be a problem, as reasonable `SymInts` never become this large.

**Comment by albanD** [comment]
Are you sure? https://godbolt.org/z/PxrrrvdnW
clang with -O0 returns 0 while clang with -O3 return 1 with the numerics limit.

**Comment by tringwald** [comment]
Interestingly enough, without `static constexpr`, `clang` is wrong starting with `-O1` while `gcc` is correct even with `-O3`. Maybe it is indeed just UB.

**Comment by albanD** [comment]
Ho ok, found it: -a is not representable in the int64_t so the result is just implementation-defined.
"
3 If the destination type is signed, the value is unchanged if it can be represented in the destination type (and
bit-field width); otherwise, the value is implementation-defined.
"

So the question is: where is the code that computes the `-a` in this case? This one should do proper checking.

**Comment by tringwald** [comment]
> So the question is: where is the code that computes the `-a` in this case? This one should do proper checking.

This here is the code for negation (operator-):
https://github.com/pytorch/pytorch/blob/5f41fc761952fab148881eb869e86b82d67cbb35/c10/core/SymInt.cpp#L135-L141

But I assume that all ops that can overflow are affected by this.

**Comment by albanD** [comment]
That one is just for SymInt and because of how SymInt work, the `operator-` there will never try to negate INT64_MIN.

**Comment by malfet** [comment]
```python
>>> x=-9223372036854775808
>>> x.bit_length()
64
```
So we should have errored out much earlier, as it can not be converted to long long... Let me see why frontend does not catch it

**Comment by albanD** [comment]
It can be converted to long long, it is exactly INT64_MIN.

**Comment by tringwald** [comment]
I've put up a draft PR that fixes the specific problem in this issue, but not really the underlying problem of `SymInts` being able to overflow. `SymInts` implement all basic arithmetic operators, so I guess all of them could potentially overflow?

**Comment by malfet** [comment]
Looking into a bit longer, I think right thing to do, rather than limit int_min or throw an exception avoid operation that causes overflow in indexing, considering that range check should not require an overflow operation, i.e. `x[-1] == x[0]`, `x[-128] == x[127]` and  `x[int64_min] == x[int64_max]`

**Comment by malfet** [comment]
So, following fixes problem with indexing:
```cpp
diff --git a/aten/src/ATen/TensorIndexing.h b/aten/src/ATen/TensorIndexing.h
index 6f5fd03a958..e3a0127313c 100644
--- a/aten/src/ATen/TensorIndexing.h
+++ b/aten/src/ATen/TensorIndexing.h
@@ -247,7 +247,7 @@ static inline Tensor applySelect(
 
     auto size = (*self_sizes)[dim];
     TORCH_CHECK_INDEX(
-        size >= -index && size > index,
+        size > -1 - index && size > index,
         "index ",
         index,
         " is out of bounds for dimension ",
```
But there still remains a problem of `sym_ge` crashing when comparing `-MIN_INT` and 0

**Comment by tringwald** [comment]
> But there still remains a problem of `sym_ge` crashing when comparing `-MIN_INT` and 0, i.e. following should not crash:
> 
> ```c++
>  const auto i = SymInt(INT64_MIN);
>   auto b =  0 < -i;
> ```

W.r.t. `INT64_MIN` and `-MIN_INT`, are you referring to 
- `numeric_limits<int64_t>::min()` or 
- `-numeric_limits<int64_t>::max()` (note the minus and max)? 
 
Because `-numeric_limits<int64_t>::min()` does not fit into a `int64_t` and would overflow (=UB, see first few comments in this issue).

**Comment by malfet** [comment]
I think I finally got what is wrong with the generated assembly:
```
   0x7ffff7f2f490 <+115>: movq   %rax, %rdx
    0x7ffff7f2f493 <+118>: negq   %rdx
    0x7ffff7f2f496 <+121>: movq   %rdx, (%rbp)
    0x7ffff7f2f49a <+125>: movabsq $0x4000000000000000, %rdx ; imm = 0x4000000000000000 
    0x7ffff7f2f4a4 <+135>: cmpq   %rdx, %rax
    0x7ffff7f2f4a7 <+138>: jle    0x7ffff7f2f520            ; <+259> at SymInt.cpp:141:1
```
`negq %rfx` correspond to unary minus from
https://github.com/pytorch/pytorch/blob/b6d0d0819ae6099b2d659d03892e1e19c17e912b/c10/core/SymInt.cpp#L137
And `cmpq   %rdx, 0x4000000000000000` are following combined
https://github.com/pytorch/pytorch/blob/b6d0d0819ae6099b2d659d03892e1e19c17e912b/c10/core/SymInt.h#L171-L176
and 
https://github.com/pytorch/pytorch/blob/b6d0d0819ae6099b2d659d03892e1e19c17e912b/c10/core/SymInt.h#L247-L249

What is missing here, is that `negq` sets a cary flag, which affects the results of next `cmp`

**Comment by malfet** [comment]
> > But there still remains a problem of `sym_ge` crashing when comparing `-MIN_INT` and 0, i.e. following should not crash:
> > ```c++
> >  const auto i = SymInt(INT64_MIN);
> >   auto b =  0 < -i;
> > ```
> 
> W.r.t. `INT64_MIN` and `-MIN_INT`, are you referring to
> 
> * `numeric_limits<int64_t>::min()` or
> * `-numeric_limits<int64_t>::max()` (note the minus and max)?
> 

`numeric_limits<int64_t>::min()` as due to the UB in `operator-` it results in SymInt with `data_` equal to `0x8000000000000000`, which is later interpreted(and dereferenced) as `nullptr`

**Comment by tringwald** [comment]
Thanks for looking at the assembly. Your findings are consistent with my results here https://github.com/pytorch/pytorch/issues/115415#issuecomment-1848732980. So that should explain the behavior then.

The question is if we should even continue after experiencing such an overflow. There are some invariants that just don't hold anymore and we will end up with strange behavior, which most code doesn't guard against. E.g. your example above:

```cpp
#include <limits>
#include <iostream>

int main() {
  int64_t res = 0;
  bool did_overflow = __builtin_sub_overflow(0, std::numeric_limits<int64_t>::min(), &res);
  std::cout << res << std::endl;
  std::cout << did_overflow << std::endl;
  return 0;
}
```
```
-9223372036854775808
1
```

Negating `-9223372036854775808` would yield `-9223372036854775808`, i.e. `x == -x`.

**Comment by malfet** [comment]
@tringwald that's a very philosophical question. IMO SymInt should mimic the behavior of non-symbolic ints, which is quite consistent across integer types (8-bit, 16-bit, 32-bit, 64-bit) and architecture `-int_min` == `int_min`, and this is what I'm trying to preserve in https://github.com/pytorch/pytorch/pull/116160
