### ISSUE TITLE
torch.device("cuda") and torch.device("cuda:0") are not equal

### ISSUE THREAD

**Issue by lokesh-vr-17773** [pytorch/pytorch#115405]
### 🐛 Describe the bug

Even though `torch.device("cuda")` and `torch.device("cuda:0")` refer to the same device, `torch.device("cuda") == torch.device("cuda:0")` gives `False`. 

### Versions

torch - 2.0.0+cu117

cc @albanD

**Comment by malfet** [comment]
Technically they are not equal, as their indices are different:
```python
>>> import torch
>>> print(torch.device("cuda").index)
None
>>> print(torch.device("cuda:0").index)
0
```

So fix is simple, but unsure if it is desireable to set it to 0 by default

**Comment by albanD** [comment]
> if no index is passed with the device, by default, device 0 will be used

I don't think that it is true. It will use whichever device is set as the current device.

**Comment by lokesh-vr-17773** [comment]
> I don't think that it is true. It will use whichever device is set as the current device.

Thanks for explaining. Then `torch.device` should at least check for the current device if no device index is given.
For example
```python
with torch.cuda.device(4):
   print(torch.device("cuda") == torch.device("cuda:4))   # Should print True since current device is cuda:4

print(torch.device("cuda") == torch.device("cuda:0"))    # Should print True since current device is cuda:0
```
