### ISSUE TITLE
`python -c "import torch;print(torch.nn.GELU()(torch.rand(2)))"` crashes on aarch64

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#115482]
### 🐛 Describe the bug

OpenDNN-3.3.2 update (made by https://github.com/pytorch/pytorch/pull/112700 ) reintroduced regression reported in https://github.com/pytorch/pytorch/issues/111695 and fixed by https://github.com/pytorch/builder/commit/c5e331c0858e37fedc047707466161dfe0cadff6

One line reproducer (must be run on Apple silicon Mac or AWS lambda environment when `/sys` is not accessible):
```
 % docker run --rm -it python:3.11.4 bash -c "pip install torch==2.2.0 --index-url https://download.pytorch.org/whl/test/cpu; python -c 'import torch;print(torch.nn.GELU()(torch.rand(2)))'"
...
/usr/local/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
bad err=11 in Xbyak::Error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/activation.py", line 682, in forward
    return F.gelu(input, approximate=self.approximate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: internal error
```

### Versions

2.2.0 RC1, nightly

cc @ezyang @gchanan @zou3519 @kadeng @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal

**Comment by malfet** [comment]
Following is a workaround for an issue:
```
% python -c 'import torch;torch.backends.mkldnn.enabled=False;print(torch.nn.GELU()(torch.rand(2)))'
```

**Comment by snadampal** [comment]
I have put this [PR](https://github.com/oneapi-src/oneDNN/pull/1773) on oneDNN to fix this issue, but have tested only on aarch64 Linux (AWS c7g)  not on Mac. and also tested only this failing scenario, the PR needs close review and testing on Mac and other scenarios.

**Comment by snadampal** [comment]
issue is fixed and the reproducer is working fine with the nightly wheels.

**Comment by malfet** [comment]
We have a workaround, but it has not been fixed yet been fixed in oneDNN, was it?

**Comment by snadampal** [comment]
Hi @malfet, we decided not to merge the fix directly into oneDNN, didn't we? your fix in [xbyak](https://github.com/fujitsu/xbyak_aarch64/pull/96) will be part of the next oneDNN release.

**Comment by atalman** [comment]
HI @malfet why do we want to include this as cherry pick for 2.2.2 ? I believe this is already included https://github.com/pytorch/builder/pull/1649 in 2.2.0 release

**Comment by malfet** [comment]
@atalman sorry, wrong milestone, I've reopened it to make sure that fix has been propagated to next oneDNN release and we can get rid of the [patch](https://github.com/pytorch/builder/blob/3dd5f849424349ee6c979d609ae19024e0cb2e6c/mkldnn_fix/fix-xbyak-failure.patch#L1) in the builder repo
