### ISSUE TITLE
the operator 'aten::unflatten' to ONNX opset version 14

### ISSUE THREAD

**Issue by AjayXue** [pytorch/pytorch#115414]
### 🚀 The feature, motivation and pitch

When I export clip models, it had a prompt that “Exporting the operator 'aten::unflatten' to ONNX opset version 14 is not supported.  Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.” May I ask if this operator is due to my export error or is ONNX currently not supporting this operator conversion? Thank you.

**Comment by justinchuby** [comment]
It is supported: https://github.com/pytorch/pytorch/blob/a267d6735051a4714fa2ac1c163315b650118744/torch/onnx/symbolic_opset13.py#L485. Please ensure you are using the latest PyTorch version.
