### ISSUE TITLE
Tensor.new_empty type annotation does not accept SymInt

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#115456]
<img width="929" alt="image" src="https://github.com/pytorch/pytorch/assets/5652049/b9732b6d-9126-4d59-8319-d79c9ad14674">

It accepts List[SymInt], but the second annotation should be `*sizes: Union[_int, SymInt]`

cc @ezyang @malfet @xuzhao9 @gramster @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by yushangdi** [comment]
@zou3519 I think this is already fixed by https://github.com/pytorch/pytorch/pull/128648?

**Comment by zou3519** [comment]
Yes, you're right
