### ISSUE TITLE
`torch.mm()` cuSPARSELt/CUTLASS back-end produce result of different dtypes for `int8` inputs in case of an input being `SparseSemiStructuredTensor`

### ISSUE THREAD

**Issue by alexsamardzic** [pytorch/pytorch#115420]
(As discussed here: #115077.)

For cuSPARSELt back-end of `SparseSemiStructuredTensor`, the result is either `int8` or `float16`, with support for `int32` coming here: #110499.

For CUTLASS back-end, the result in `int32`.

The `int8` inputs are not supported on GPU for dense tensors MM.  For CPU, the result is `int8`.  

Tensor cores, that are actually doing calculation for both cuSPARSELt and CUTLASS back-ends, produce `int32` result for `int8` inputs (see [here](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#warp-level-matrix-instructions-sparse-mma)).

We should probably unify behavior somehow.

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip

**Comment by cpuhrsch** [comment]
@jcaip - What do you think?

**Comment by jcaip** [comment]
We can disable mm for CUTLASS but keep the cuSPARSELt version and add `out_dtype` support for int32 for CUTLASS and fp16 for cuSPARSELt. Do you have an example of adding this for int_mm?

Then we can add in torch.int32 / bfloat16 with cusparselt v0.5.1 and then float16/bfloat16 with CUTLASS fused dequant (https://github.com/NVIDIA/cutlass/pull/1189), as well as turning on int8 mm default behavior.

**Comment by alexsamardzic** [comment]
I think I can force CUTLASS to produce `int8` result right now (I mean: before above mentioned PR merged), if we agree to match dense result datatype.  So I guess we can have that as default, and then support the specifics through `out_dtype`.

**Comment by cpuhrsch** [comment]
@jcaip https://github.com/pytorch/pytorch/pull/107664 and https://github.com/pytorch/pytorch/pull/108059 added it for int_mm. 

@alexsamardzic - I'm not sure about a use case for producing int8. I think it's ok to throw an exception for now and just say that it's not supported.

**Comment by alexsamardzic** [comment]
Fixed by #116519.

**Comment by RanchiZhao** [comment]
Hi！I want to know if cuSparseLt/cutlass currently supports acceleration for 2:4 sparse model inference with int8 type？thx

**Comment by RanchiZhao** [comment]
> Hi！I want to know if cuSparseLt/cutlass currently supports acceleration for 2:4 sparse model inference with int8 type？thxHi！我想知道cuSparseLt/cutlass目前是否支持int8类型的2:4稀疏模型推理加速？thx

like a GPTQ model or a AWQ model? because in this blog: https://developer.nvidia.com/blog/structured-sparsity-in-the-nvidia-ampere-architecture-and-applications-in-search-engines/
I found a pipeline called 'Sparse-QAT', but i'm not sure the sparse tensor core is available for int8, and i have no idea how this is related with PTQ methods, cuz PTQ needs dequantize
