### ISSUE TITLE
Need process/automation to ensure that fixes selected for the previous patch release are to be included in next major release

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#115469]
### 🐛 Describe the bug

For example https://github.com/pytorch/pytorch/pull/115183 was picked into `release/2.1`, but is missing right now from `release/2.2` which creates an opportunity for weird behavior diversion between two releases

### Versions

2.1.2, 2.2.0-RC1

**Comment by atalman** [comment]
I see this use case applies only to second patch release. We need a process when new cherry-pick is offered to second patch release, it should be considered automatically for next minor release.

**Comment by atalman** [comment]
We need to do:
For second patch release 2.2.2
https://github.com/pytorch/pytorch/commits/release/2.2/
https://github.com/pytorch/pytorch/milestone/43

Try to identify all the cherry-picks that are missing in release 2.3:
https://github.com/pytorch/pytorch/commits/release/2.3/

Some of them should already be part of release/2.3 branch. But some may need to be added.

**Comment by juliagmt-google** [comment]
> Latest commands to use:
> 
> ```
> python analytics/github_analyze.py --repo-path ~/local/pytorch --remote upstream --branch release/2.2 --milestone-id 43 --missing-in-branch
> ```
> 
> Output:
> 
> ```
> len(main_commits)=3653
> len(release_commits)=75
> URL;Title;Status
> https://github.com/pytorch/pytorch/issues/120999;[v2.2.2] Release Tracker;open
> https://github.com/pytorch/pytorch/issues/120547;F.conv1d fails with `RuntimeError: cannot create std::vector larger than max_size()` after transpose of input tensor;closed
> ```
> 
> What this command does is look at this issue: https://github.com/pytorch/pytorch/milestone/43 All the open and closed PR's and issues And tries to match issues in milestones with cherry-picks from branch here: https://github.com/pytorch/pytorch/commits/release/2.2/ If it finds missing in branch it prints the message with the PR or issue

Does it show 2 PRs that are present in release/2.2 but NOT in orig/release/2.2? If so, how to verify those 2 PRs are NOT present in the branch on github?

**Comment by juliagmt-google** [comment]
@kiukchung

**Comment by atalman** [comment]
Closing this issue since its addressed
