### ISSUE TITLE
[CI] Should test_public_bindings be included in CI by default?

### ISSUE THREAD

**Issue by wz337** [pytorch/pytorch#115594]
Currently, `test_public_bindings` seems only run when `ciflow/trunk` tag is added to the PR. 

My thought is that the tests under `test_public_bindings` are important (failure is landing blocking) yet cheap to run so it seems reasonable for it to be included in CI by default, instead of only running when the `ciflow/trunk` tag is added.

So the proposal is to include test_public_bindings in CI by default. 

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
We already running `test_public_bindings` on PRs, but not MacOS tests.

**Comment by PaliC** [comment]
Proposed solution: 

- [ ] when a review is created, pytorchbot should apply ciflow/trunk 
- [ ] in merge rules, trunk jobs should be considered mandatory

**Comment by malfet** [comment]
Has been done a while back, please reopen or create a new issues if this is not the case
