### ISSUE TITLE
NotImplementedError: The operator 'aten::index_fill_.int_Scalar' is not currently implemented for the MPS device.

### ISSUE THREAD

**Issue by mysoundenough** [pytorch/pytorch#115527]
Error while using LabelSmoothing form transformer_utils for label smoothing
- OS:macOS 13.5
- PyTorch version:2.0.1
- Python version: 3.9.17

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by mysoundenough** [comment]
This problem has been solved in torch==2.1.1

**Comment by malfet** [comment]
Closing as indeed it has been implemented in 2.1
