### ISSUE TITLE
TensorOptions should not read default options at construction/factory time (the ones_like()/to() problem)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#11559]
Consider the following PyTorch code:

```
y = torch.ones_like(x, dtype=torch.float64)
```

If x is a CUDA float tensor, what do you expect y to be? I'd expect a CUDA double tensor.

OK, how about this C++?

```
auto y = at::ones_like(x, at::dtype(at::kDouble));
```

Seems like a nearly line-by-line translation, right? WRONG. By default, the C++ code produces a **CPU** double tensor. This is because `at::dtype()` constructs a default `TensorOptions` using the nullary constructor, which consults the TensorOptions TLS to determine what the default, e.g., device should be. Which is CPU by default. So you the above C++ code is effectively equivalent to:

```
auto y = at::ones_like(x, at::device(at::kCPU).dtype(at::kDouble));
```

which obviously gives you a CPU tensor.

Here's how we should fix it:

1. Make all fields of `TensorOptions` optional.
2. The default constructor of `TensorOptions` leaves all fields `nullopt`.
3. A getter for a field in `TensorOptions` for a nullopt field consults the default TLS to determine what value to provide. We also add opt accessors which return, e.g., `at::optional<Device>`. (Alternate plan: introduce another type, `TensorType`, which is what `TensorOptions` is today; e.g., all fields are non-optional). (Variation on the plan: the TLS accessors live out-of-line of TensorOptions, since TLS is not supported in the mobile build.)
4. Replace the three overloads of `to(ScalarType)` and `to(Backend, ScalarType)` with `to(TensorOptions)`
5. Methods for which reasonable defaults exists (e.g., `ones_like` and `to`) don't use TLS ever; instead, they default to the local default that makes sense (e.g., the tensor to make ones "like", or the tensor you're converting from).

**Comment by gchanan** [comment]
The problem is actually a bit worse than you describe:

`
auto y = at::ones_like(x, at::dtype(at::kDouble));
`
at least indicates that the second argument is a `TensorOptions`, you can also do:
`
auto y = at::ones_like(x, at::kDouble);
`
because of implicit constructors, which looks exactly like:
`
at::ones_like(y).to(at::kDouble)
`
but as mentioned, the behavior is different.

**Comment by ezyang** [comment]
This is fixed now.
