### ISSUE TITLE
distributed debugger tutorial/documentation

### ISSUE THREAD

**Issue by HongLouyemeng** [pytorch/pytorch#115517]
### 🚀 The feature, motivation and pitch

1.There are very few articles on torch distributed debug, and there are still different issues on different systems. An official guidance document is needed to provide standards
2.Currently torch distributed deep learning is becoming more and more important, distributed hybrid debug pytorch distributed source code is a very helpful tool

### Alternatives

1.[macos lldb](https://github.com/pytorch/pytorch/issues/115476)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @svekars @carljparker

**Comment by wconstab** [comment]
@HongLouyemeng there is a recent PR by @ezyang to add a helper for debugging distributed programs

https://github.com/pytorch/pytorch/pull/113775/files

I agree we can better document this.  I'll open a new topic on discuss.pytorch.org and submit an example to our docs site

**Comment by wconstab** [comment]
https://discuss.pytorch.org/t/how-to-debug-pytorch-distributed/193575

**Comment by wconstab** [comment]
https://github.com/pytorch/pytorch/pull/115656

**Comment by wconstab** [comment]
sorry i just realized the `distributed.breakpoint` util is broken - filed https://github.com/pytorch/pytorch/issues/115685 to track, will fix asap

**Comment by HongLouyemeng** [comment]
Thanks for taking the time to write the docs
