### ISSUE TITLE
[ERROR] when i run test_replay_record.py

### ISSUE THREAD

**Issue by Mrwhite132613** [pytorch/pytorch#115518]
### 🐛 Describe the bug

when i run test_replay_record.py, i get the same error as the pr #106287 and #112678，it shows:
`FAILED [0.0126s] test/dynamo/test_replay_record.py::ReplayRecordTests::test_fn_call_args - AssertionError: no logs of level ERROR or higher triggered on torch._dynamo
FAILED [0.0277s] test/dynamo/test_replay_record.py::ReplayRecordTests::test_local_module - AssertionError: no logs of level ERROR or higher triggered on torch._dynamo
FAILED [0.0234s] test/dynamo/test_replay_record.py::ReplayRecordTests::test_nonlocal_fn_call - AssertionError: no logs of level ERROR or higher triggered on torch._dynamo
FAILED [0.0202s] test/dynamo/test_replay_record.py::ReplayRecordTests::test_nonlocal_module_class - AssertionError: no logs of level ERROR or higher triggered on torch._dynamo
FAILED [0.0238s] test/dynamo/test_replay_record.py::ReplayRecordTests::test_nonlocal_module_fn_call - AssertionError: no logs of level ERROR or higher triggered on torch._dynamo
FAILED [0.0234s] test/dynamo/test_replay_record.py::ReplayRecordTests::test_successful_inline - AssertionError: no logs of level ERROR or higher triggered on torch._dynamo
FAILED [0.0173s] test/dynamo/test_replay_record.py::ReplayRecordTests::test_unsuccessful_inline - AssertionError: no logs of level ERROR or higher triggered on torch._dynam`

is this testcase not maintained, or how to run it correctly?

### Versions

python 3.8 
pytorch 2.1 release

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

**Comment by Mrwhite132613** [comment]
please，please@chillee

**Comment by ezyang** [comment]
cc @mlazos
