### ISSUE TITLE
torch.onnx is not support baichuan_7b 'aten::unflatten' operator

### ISSUE THREAD

**Issue by wangyige1** [pytorch/pytorch#115538]
### 🚀 The feature, motivation and pitch

torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::unflatten' to ONNX opset version 11 is not supported.

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
