### ISSUE TITLE
DeviceGuard is weirdly CUDA-specific

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#11561]
```
  /// Sets the device to the given one.
  void set_index(int32_t index) {
    if (index == -1) {
      return;
    }
    AT_ASSERT(index >= 0);
    if (original_index_ == -1) {
      int32_t previous_index = -123;
      detail::DynamicCUDAInterface::get_device(&previous_index);
      original_index_ = previous_index;
      if (index != original_index_) {
        detail::DynamicCUDAInterface::set_device(index);
      }
    } else {
      detail::DynamicCUDAInterface::set_device(index);
    }
    last_index_ = index;
  }
```

Like, don't claim to be device independent, and then call a CUDA thing under the hood.

**Comment by gchanan** [comment]
IMO we should just take an at::optional<Device> everywhere (that may be a fair amount of work because a lot of code probably uses integers).

**Comment by apaszke** [comment]
@gchanan isn't `at::optional<T>` implicitly constructible from `T`?

**Comment by gchanan** [comment]
Sorry, I meant to write at::optional<Device>.

**Comment by gchanan** [comment]
Oh, it cuts off the parameter if you don't quote it lol.  I meant `at::optional<Device>`.

**Comment by ezyang** [comment]
This is fixed.
