### ISSUE TITLE
Installing via pip does not install numpy and leads to a warning when importing torch

### ISSUE THREAD

**Issue by jedreky** [pytorch/pytorch#115638]
### 🐛 Describe the bug

I start with a fresh venv (Python 3.11.6) and do `pip install torch`. This leads to a situation where importing torch leads to a UserWarning, I'm not sure if this is expected, but to me as a user it feels a bit counterintuitive.

### Versions

```
python --version
Python 3.11.6
```

```
pip freeze
filelock==3.13.1
fsspec==2023.12.2
Jinja2==3.1.2
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.2.1
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
sympy==1.12
torch==2.1.1
triton==2.1.0
typing_extensions==4.9.0
```

```
python -c "import torch"
xxx/venv/lib64/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
```

cc @ezyang @gchanan @zou3519 @kadeng @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @rgommers @bhosmer @cpuhrsch @erichan1 @drisspg

**Comment by soulitzer** [comment]
The warning seems to go away if the `_generate_square_subsequent_mask` function is commented out. Maybe there is logic there that we should not run at import time?

**Comment by albanD** [comment]
Numpy is an optional dependency so it is expected that it is not installed by default.
We should not warn by default when PyTorch is imported though indeed
