### ISSUE TITLE
Optimize `cudnn_convolution_out` to Reduce Unnecessary Memory Allocation and Copy

### ISSUE THREAD

**Issue by yewentao256** [pytorch/pytorch#115611]
### 🚀 The feature, motivation and pitch

In `build/aten/src/ATen/CompositeViewCopyKernels.cpp`

```c++
at::Tensor & cudnn_convolution_out(const at::Tensor & self, const at::Tensor & weight, at::IntArrayRef padding, at::IntArrayRef stride, at::IntArrayRef dilation, int64_t groups, bool benchmark, bool deterministic, bool allow_tf32, at::Tensor & out) {
  auto tmp_output = at::_ops::cudnn_convolution::call(self, weight, padding, stride, dilation, groups, benchmark, deterministic, allow_tf32);
    resize_out_helper(out, tmp_output);
  copy_arg(out, tmp_output);
  return out;
}
```

Currently, it internally uses `cudnn_convolution` that allocates a temporary output tensor, even when an output tensor is already provided, causing extra memory allocation and data copying. Functions like `cudnn_batch_norm_backward_out`, `cudnn_affine_grid_generator_backward_out` have the same behaviour.

Shall we directly compute the convolution results into the provided output tensor out, avoiding the creation of a temporary tensor and the subsequent copy operation?

Reducing memory overhead and unnecessary data movements should enhance performance, particularly in large-scale and performance-sensitive applications.

cc @csarofeen @ptrblck @xwang233 @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by albanD** [comment]
Hey!

I think the reason for this is: you should not be using these kernels (they are automatically generated for consistency only).
So the performance of these kernels doesn't really matter and that's why they are the way they are.

Do you actually need to call this op directly?
If not, I would say not worth fixing since no one uses this op directly.

**Comment by yewentao256** [comment]
Yes, using `cudnn_convolution_out` is quite beneficial for us. Given the output tensor's memory is pre-allocated for each call, directly computing into this tensor can reduce both a memory allocation and a copy operation, thereby boosting performance. Furthermore, addressing this issue aligns with the intended semantics of the `out` function.

**Comment by albanD** [comment]
Do you have more details about your use case?
The caching allocator is fast enough that allocating memory should never be a problem.
Also these operators don't support autograd so you're using them only for inference?

**Comment by yewentao256** [comment]
https://github.com/DeepLink-org/DIOPI/blob/0fadb51b6dc11d14195f6cd193f0e7c92dc490ab/impl/torch/functions/functions.cpp#L199

We have separated the forward and backward processes of convolution to ensure that they can be exclusively utilized for inference in certain cases.

Additionally, we've implemented preallocation of the tensor each time the forward function is invoked. This is why we aim to employ the out function to eliminate additional empty and copy operations. 

Furthermore, in my opinion, while employing a caching allocator can make the empty operation efficient, does copying remain time-intensive, especially with larger tensors?

**Comment by albanD** [comment]
> Furthermore, in my opinion, while employing a caching allocator can make the empty operation efficient, does copying remain time-intensive, especially with larger tensors?

Yes it does.

Thanks for sharing the code pointer. These ops where definitely not intended for that purpose!

We would accept a PR implementing a proper kernel for this op.
To do so you can remove the setting in native_functions.yaml that generates this dummy implementation (`autogen: cudnn_convolution.out`)
And add a new entry for it with a proper implementation

**Comment by albanD** [comment]
cc @jbschlosser if this op is going to get deprecated/removed, maybe we don't want to go down that path though?

**Comment by jbschlosser** [comment]
That's right, the recommended approach now is to utilize the `convolution()` op and let backend selection pick cuDNN when it's available. There should be a `convolution.out` variant that will work for your purposes @yewentao256 (although it will be subject to the same performance issue until we provide a proper kernel for it)

**Comment by yewentao256** [comment]
Thanks for replying! @jbschlosser @albanD 

> That's right, the recommended approach now is to utilize the `convolution()` op and let backend selection pick cuDNN when it's available. 

However, we've found that using the `cudnn_convolution` operation directly might be more efficient. In our tests, each invocation of `convolution()` ultimately dispatches to `cudnn_convolution`. For instance, when training the **yolov5** model, the speed increased from 0.341455 s / iter to 0.33409 s / iter after this optimization. We've tested this adjustment on over 30 models and it appears not to affect precision. 

Therefore, would it be better to have a dedicated `cudnn_convolution_out` operation for direct use?

**Comment by yewentao256** [comment]
And it seems that other ops like `foreach_xx` have the same problem:

```c++
// build/aten/src/ATen/CompositeViewCopyKernels.cpp
void _foreach_add_List_out(at::TensorList self, at::TensorList other, const at::Scalar & alpha, at::TensorList out) {
  auto tmp_output = at::_ops::_foreach_add_List::call(self, other, alpha);
    resize_out_helper(out, tmp_output);
  copy_arg(out, tmp_output);
}
``` 

<img width="1343" alt="企业微信截图_b5a9ada7-24a5-45bd-b677-340450909ec1" src="https://github.com/pytorch/pytorch/assets/44945378/decb4751-47e2-44b4-b298-18f703c17c76">


Is there any way to solve all of these problems together? @albanD @jbschlosser

**Comment by albanD** [comment]
The problem is that all of these are generated when we don't have a out kernel implemented: https://github.com/pytorch/pytorch/blob/dfc898ede43370506d38a568688b176985b61930/torchgen/native_function_generation.py#L579
So we can only use the out of place variant that exists and thus we have to do the later copy.

Again, we would accept contributions adding these out variants and make the out-of-place call into this out variant so we still only have one low level kernel for all APIs.

> However, we've found that using the cudnn_convolution operation directly might be more efficient. 

The backend selection code should be very fast. I would be surprised if we couldn''t make it such that the difference is unnoticeable.

**Comment by yewentao256** [comment]
@albanD  Please have a look: https://github.com/pytorch/pytorch/pull/116759

**Comment by yewentao256** [comment]
> And it seems that other ops like `foreach_xx` have the same problem:

I am wondering would you accept a PR that adds the `foreach` out variants? @albanD

**Comment by albanD** [comment]
Thanks for the clean PR for convolution.
For the foreach variant, in principle, we would be happy to accept a PR but there is a risk that this one is going to be more involved since we have no out variant manual kernel for foreach ops. This means that our current codegen system might require being updated for that.

**Comment by yewentao256** [comment]
Close this issue as completed.
