### ISSUE TITLE
[MPS] NotImplementedError in `empty_mps` seems to be the opposite

### ISSUE THREAD

**Issue by watarungurunnn** [pytorch/pytorch#115625]
### 🐛 Describe the bug

I found the below code in `pytorch/aten/src/ATen/mps/EmptyTensor.cpp`, but I believe that this assertion is doing the opposite operation. Could someone check this?
```
TORCH_CHECK_NOT_IMPLEMENTED(
        layout_or_default(layout_opt) == Layout::Strided,
        "strided tensors not supported yet");
```

### Versions

PyTorch version: 2.2.0a0+git453d509
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.5.2 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.9.18 (main, Sep 11 2023, 08:25:10)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.5.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.7.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.10.0
[pip3] torch==2.2.0a0+git453d509
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.10.0                   pypi_0    pypi
[conda] torch                     2.2.0a0+git453d509           dev_0    <develop>
[conda] torchfix                  0.2.0                    pypi_0    pypi

cc @svekars @carljparker @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by albanD** [comment]
Ho yes the error message is not correct. Only strided layout is supported.
