### ISSUE TITLE
Dynamo'ing Rprop, RMSprop, and Adadelta misses incrementing step due to skipping _init_group

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#115679]
### 🐛 Describe the bug

Currently the step update for Rprop, RMSprop and Adadelta occurs in _init_group, which gets skipped in dynamo. This means that running torch.compile on these optimizers will correctly update the parameters but not the step.

_init_group is currently disabled in dynamo today due to slow tracing over loops. However, it seems like a bug that _init_group is skipped entirely in execution too.

And yes, moving the step update to the actual `step` function would technically "solve" this issue, but I do not believe it is the right fix. We should still run _init_group before step even after dynamo'ing. cc @vincentqb @jbschlosser @albanD @crcrpar @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @mlazos

### Error logs

```
(pytorch-3.10) [janeyx@devgpu023.odn1 ~/local/pytorch (e9184613)]$ python playground.py
expected in eager:
step 1
step 2
step 3
step 3
step 4
step 5
what actually happens after dynamo:
step 1
step 1
step 1
step 1
step 2
step 3
```

You may be curious why the steps suddenly start incrementing after a bit. That is because recompilation due to the .grad fields becoming all None causes dynamo to run again, which will correctly call `_init_group`.

### Minified repro

```
import torch
def training_loop():
    input = torch.tensor(
        [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
    ).reshape(3, 2)

    model = torch.nn.Sequential(
        torch.nn.Linear(2, 3),
        torch.nn.Sigmoid(),
        torch.nn.Linear(3, 1),
        torch.nn.Sigmoid(),
    )

    params = list(model.parameters())
    optimizer = torch.optim.Rprop(params)

    for i in range(6):
        optimizer.zero_grad()
        # Test that step behaves as expected (a no-op) when grads are set to None
        if i != 3:
            output = model(input)
            loss = output.sum()
            loss.backward()

        optimizer.step()
        print("step", optimizer.state[params[0]]["step"])

compiled_training_loop = torch._dynamo.optimize("eager")(training_loop)

print("expected in eager:")
training_loop()

print("what actually happens after dynamo:")
compiled_training_loop()
```

### Versions

on main

**Comment by janeyx99** [comment]
Once we fix this issue, we should reenable the tests I'm disabling in https://github.com/pytorch/pytorch/pull/115680 after adding more coverage.

**Comment by lezcano** [comment]
@jon-chuang

**Comment by jon-chuang** [comment]
>  However, it seems like a bug that _init_group is skipped entirely in execution too.

This is by design, so the step updates needs to be moved into the actual traced `step` function outside of `init_group`

**Comment by jon-chuang** [comment]
The other thing that needs to be fixed is that `step` needs to be turned into tensors at initialization: https://github.com/pytorch/pytorch/pull/111008#discussion_r1354957480

**Comment by janeyx99** [comment]
While I agree a short term fix could be to move `step` to the traced `step` function, this would not resolve the overall issue. I believe the design of tracing `_init_group` only once is problematic, as we shouldn't trade off correctness for performance. For example, the current `_init_group` will only initialize state when p.grad is not None. p.grad will change values over different iterations, so the first _init_group is NOT guaranteed to work as a one-time deal. 

But even before we dive into the specifics, users can put whatever they want in their own `_init_group()`, and so the current path is unsound already.

**Comment by mlazos** [comment]
> While I agree a short term fix could be to move `step` to the traced `step` function, this would not resolve the overall issue. I believe the design of tracing `_init_group` only once is problematic, as we shouldn't trade off correctness for performance. For example, the current `_init_group` will only initialize state when p.grad is not None. p.grad will change values over different iterations, so the first _init_group is NOT guaranteed to work as a one-time deal.
> 
> But even before we dive into the specifics, users can put whatever they want in their own `_init_group()`, and so the current path is unsound already.

We will recompile if the grads are set to `None`. 

For the user-defined _init_group, @jon-chuang pointed this out previously and had a proposal here: 
https://github.com/pytorch/pytorch/issues/111331

Alternatively, we can opt-in the builtin optimizers for this special handling and not handle it unless a user runs into issues and wants to opt-in.

**Comment by janeyx99** [comment]
I agree the user-defined  opt-in`_init_group` would be safer, but I'm curious about what exactly we're trading off correctness with by not tracing through `_init_group`. Is there a time bound that is worth not being correct? I'd prefer to close the holes where users can run into obscure issues, as that greatly detriments UX.

Also, if recompilations are occurring all the time, is it worth the cut in trace time? Doesn't recompilation require retracing anyway? We could go and try to patch around safety and correctness, but I am not convinced these patches are better than just tracing through and then slimming down compile time after. Overall, my take would be to prioritize correctness first, and then optimize for performance after.

**Comment by mlazos** [comment]
This is just a compile-time optimization. The workflow I'm proposing is in most cases users don't know or care about this, and it should work. Then if someone implements a new optimizer, with their own _init_group, by default we would trace, if their trace time is unacceptable, they can ensure their _init_group meets the no side effects criteria, and opt-in to this handling. 

Recompilations are not occurring all the time, in most cases, grads will be populated after the forward/backward pass has run, so we will run the same compiled step(). This matches the behavior of eager, where often `_init_group` is a no-op, which is where this optimization came from.

**Comment by jon-chuang** [comment]
I think we guard on `constant_match` for the step changing though. However, since the step is not outside of `_init_group`, it never runs and never triggers guard.


https://github.com/pytorch/pytorch/blob/b062ea38039234c80404a8f5f4d5a93c4cb9832d/torch/_dynamo/variables/optimizer.py#L142

@janeyx99 fwiw I think moving into step is still a good stopgap solution, as dynamo is still slow at tracing for loops.

**Comment by janeyx99** [comment]
I think @mlazos actually tried enabling tracing through `_init_group` yesterday and it's not as slow anymore!

**Comment by janeyx99** [comment]
Since there are still references to this issue on main, we should keep these issues open until those references are either removed or replaced. Do you plan to have a PR enabling the test skips in common_optimizers.py?
