### ISSUE TITLE
xfail_if_model_type_is_exportedprogram and xfail_if_model_type_is_not_exportedprogram don't catch unexpected success

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#115747]
### 🐛 Describe the bug

Internally, https://github.com/pytorch/pytorch/blob/4307ccde99fbec3afcd7cbee1a0c2db0070187cc/test/onnx/pytorch_test_common.py#L367 and https://github.com/pytorch/pytorch/blob/4307ccde99fbec3afcd7cbee1a0c2db0070187cc/test/onnx/pytorch_test_common.py#L343 use `pytest.xfail` which does not seem to execute the model and/or if they do, they don't raise when the model unexpectedly succeeds.

As a consequence, tests that are fixed but whose xfail are not removed will not be detected by the CI

### Versions

pytorch main

**Comment by thiagocrepaldi** [comment]
https://github.com/pytorch/pytorch/pull/117425 fixes this, right?

**Comment by titaiwangms** [comment]
https://github.com/pytorch/pytorch/pull/117592
