### ISSUE TITLE
torch.compile silently producing wrong output when mutating attributes/buffers

### ISSUE THREAD

**Issue by tomatillos** [pytorch/pytorch#115774]
### 🐛 Describe the bug

Error when compiling a function that mutates an attribute or buffer - seems to reference the buffer as it was during tracing rather than an updated ones. If you comment out `torch.compile` the function behaves as expected. Errors in all the backends I tried (think it's a problem at dynamo level)

Insidious bug as it's silent, probably worth throwing an error here!

```
import torch

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.cache = torch.tensor([0,0])

    @torch.compile(backend="eager")
    def forward(self, x, pos):
        self.cache[pos] = x
        return self.cache

model = Model()

print(model(torch.tensor([2]), torch.tensor([0])))
# resetting cache/buffer
model.cache = torch.tensor([0,0])
# expect [0, 1], but get [2, 1]
print(model(torch.tensor([1]),torch.tensor([1])))
```

### Versions

latest nightly, present in last major releases as well.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by anijain2305** [comment]
Setting `torch._dynamo.config.guard_nn_modules = True` passes. This is another instance of not guarding on nn modules biting us - https://github.com/pytorch/pytorch/issues/100061

Closing as duplicate.
