### ISSUE TITLE
Some Inductor tests fail with `exact_dtype=True`

### ISSUE THREAD

**Issue by peterbell10** [pytorch/pytorch#115742]
In #115676 I discovered that `check_model` doesn't check the output dtype when run with `reference_as_float=True`. Two tests now require `exact_dtype=False`, suggesting the decomposition or lowerings need to be fixed:
- [x] `CPUReproTest.test_embedding_vec_bf16`
https://github.com/pytorch/pytorch/blob/a124fc0824b0f1de9449a740cb1280e7f083ade0/test/inductor/test_cpu_repro.py#L2712
- [x] `Cpu/CudaTests.test_div8`
https://github.com/pytorch/pytorch/blob/a124fc0824b0f1de9449a740cb1280e7f083ade0/test/inductor/test_torchinductor.py#L1642

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler

**Comment by lezcano** [comment]
@vfdev-5 should we close this one?
