### ISSUE TITLE
[feature request] 3d grid sample function

### ISSUE THREAD

**Issue by nwschurink** [pytorch/pytorch#11573]
For my project I would like to implement a 3D spatial transformer into my network. For this to work, I would need to interpolate to a 3D grid.

Ofcourse it's possible to write a custom function in python (sorry, at the moment no C language for me yet) and I am currently working on this, however if it were relatively simple to implement in C why dont you add this (ND) functionality to the core? Especially for the medical imaging domain, where images are always 3D, these kind of functions are needed.

Would love to hear your thoughts on it!

**Comment by soumith** [comment]
grid sample allows 3D already since `0.4.1`. See https://github.com/pytorch/pytorch/pull/5453 for reference

**Comment by nwschurink** [comment]
Ah excuse me, I must have looked at the wrong version of the pytorch docs.
