### ISSUE TITLE
Critical error after importing caffe2.python 

### ISSUE THREAD

**Issue by Sem-Kulish** [pytorch/pytorch#11570]
Hi, after merge of [fix](https://github.com/pytorch/pytorch/pull/11517) for [#11453](https://github.com/pytorch/pytorch/issues/11453) new exception raises 

```
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
CRITICAL:root:Cannot load caffe2.python. Error: No module named 'caffe2.python.caffe2_pybind11_state'

```

@oxygenxo

**Comment by ezyang** [comment]
How did you install PyTorch (install or develop) and what was your CWD when you ran the import?

cc @orionr

**Comment by orionr** [comment]
@ezyang is right. Please put full info around how you installed, what the build output was, where you were when you ran python, etc. The more details the better.

**Comment by Sem-Kulish** [comment]
@orionr 
In docker container (where I am trying to build) installed this packages:
```
        build-essential 
        cmake 
        git 
        libgoogle-glog-dev 
        libgtest-dev 
        libiomp-dev 
        libleveldb-dev 
        liblmdb-dev 
        libopenmpi-dev 
        libsnappy-dev 
        libprotobuf-dev 
        openmpi-bin 
        openmpi-doc 
        protobuf-compiler 
        libgflags-dev 
        python3-dev 
        python3-pip 
        python3-setuptools 
        python3-wheel 
        python3-yaml
```
I am cloning pytorch repo and run next command 
```
CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DUSE_CUDA=OFF -DUSE_OPENCV=OFF" python3 setup.py build bdist_wheel
```
There was CMake warning that confuses a little bit cause pibind11 in third_parties 
```
CMake Warning at cmake/Dependencies.cmake:412 (find_package):
  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:169 (include)

pybind11 config not found. Fallback to legacy find.
CMake Warning at cmake/Dependencies.cmake:447 (message):
```

So, I continued build and have critical error in python after importing  `from caffe2.python import core`

After that I tried to built pybind (from srcs) and this warning did not show again
But crit error after `from caffe2.python import core` still reproduce 

Build logs attached 
[log_build_no_pybind_prebuild](https://github.com/pytorch/pytorch/files/2378405/log_no_pybind.log)
[log_with__pybind_prebuild](https://github.com/pytorch/pytorch/files/2378406/log_with_pybind.log)

**Comment by orionr** [comment]
You shouldn't need to install pybind11, since (as you guessed) we'll use pybind11 under third_party. I've  put up a pull request to improve that messaging and I'd recommend removing it.

After that can you try running the command below and see if you get the same errors?

```
NO_CUDA=1 python3 setup.py install
```

or, to build a develop version

```
NO_CUDA=1 python3 setup.py build_deps develop
```

It's possible passing the CMake args directly rather than through environment variables is affecting the way our tools/build_pytorch_libs.sh is managing things.

**Comment by Sem-Kulish** [comment]
Great,  `NO_CUDA=1 python3 setup.py build_deps develop
` works and only throws warning about gpu support as expected.
