### ISSUE TITLE
Warning in autograd init regarding to aten::reshape

### ISSUE THREAD

**Issue by mfatih7** [pytorch/pytorch#115816]
### 🐛 Describe the bug

Hello

I have a training loop running without any errors or warnings on GPUs using Pytorch 2.0.1.
When I try to modify my learning loop to run on TPUs I get the error https://github.com/pytorch/xla/issues/6002

Pytorch XLA developers @JackCaoG solved the problem.
But after the problem is solved I get the warning below.

/home/mfatih/env3_8/lib/python3.8/site-packages/torch/autograd/__init__.py:266: UserWarning: aten::reshape: an autograd kernel was not registered to the Autograd key(s) but we are trying to backprop through it. This may lead to silently incorrect behavior. This behavior is deprecated and will be removed in a future version of PyTorch. If your operator is differentiable, please ensure you have registered an autograd kernel to the correct Autograd key (e.g. DispatchKey::Autograd, DispatchKey::CompositeImplicitAutograd). If your operator is not differentiable, or to squash this warning and use the previous behavior, please register torch::CppFunction::makeFallthrough() to DispatchKey::Autograd. (Triggered internally at ../torch/csrc/autograd/autograd_not_implemented_fallback.cpp:63.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

Pytorch XLA developers told me that the warning is related to Pytorch, not Pytorch-XLA.
Is this warning an indication of the wrong backward computations?

You can regenerate the error using the public [repo](https://github.com/mfatih7/FeatureMatchingDebugSingle_TPUcore).

Please change the working directory on [line](https://github.com/mfatih7/FeatureMatchingDebugSingle_TPUcore/blob/main/17_featureMatching/config.py#L22) in the config file.

Run the [run_train_1_1_TPU_single.py](https://github.com/mfatih7/FeatureMatchingDebugSingle_TPUcore/blob/main/17_featureMatching/run_train_1_1_TPU_single.py) for debugging. After a successful short train and val cycle we get the warning.

The warning occurs in operations placed in the functions in [loss_functions.py](https://github.com/mfatih7/FeatureMatchingDebugSingle_TPUcore/blob/main/17_featureMatching/loss_module/loss_functions.py) during backward pass.

### Versions

Here is my environment

PyTorch version: 2.2.0.dev20231213+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-1027-gcp-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) CPU @ 2.00GHz
Stepping:                        3
CPU MHz:                         2000.186
BogoMIPS:                        4000.37
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        77 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.2.0.dev20231213+cpu
[pip3] torch-xla==2.2.0+git5577dd7
[pip3] torchaudio==2.2.0.dev20231213+cpu
[pip3] torchmetrics==1.2.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.18.0.dev20231213+cpu
[conda] Could not collect

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @bdhirsh

**Comment by JackCaoG** [comment]
@bdhirsh From the log it seems like it suggese XLA need to manually register the backward for reshape which is a bit weird. This is the first time I see this error, if you can shed some light on this issue that would be great!

**Comment by albanD** [comment]
Hey!
@zou3519 added this warning recently as a set of more testing to ensure custom ops are properly registered.
This is expected to trigger if you register a backend kernel (XLA key) but no autograd imple (AutogradXLA) for a given op.

Since reshape() cannot have an autograd formula (it is sometimes a view and sometimes not), then you should register your kernel as a CompositeImplicitAutograd kernel (this will properly register onto AutogradXLA and remove this warning)

**Comment by JackCaoG** [comment]
Thanks @albanD ! This make sense! I have a follow up question, we registered reshape and reshape symint in https://github.com/pytorch/xla/blob/master/codegen/xla_native_functions.yaml#L374 and https://github.com/pytorch/xla/blob/master/codegen/xla_native_functions.yaml#L408. This file will then get codegen into `RegisterXLA.h/cpp` and `ResigisterAutogradXLA.h/cpp`. What's the correct way of marking `reshape` to be `CompositeImplicitAutograd`?

**Comment by albanD** [comment]
Ho I'm not familiar with how your codegen works...
But in principles, I guess you want to do the same as NestedTensor here which uses `CompositeImplicitAutogradNestedTensor` for the dispatch key in native_functions.yaml. @bdhirsh do you have more context on this by any chance?

**Comment by JackCaoG** [comment]
Haha this is actually added by you @bdhirsh in https://github.com/pytorch/xla/commit/e49df835e90305704610544c065bf8cea6e694cd#diff-7848c3ab18524ec52fa41576c226549cb7307d5efcaa6344251d31cac0feacea for functionization. 

Do you think we still need this trick for functionization?

**Comment by bdhirsh** [comment]
😛 

Yes - I think we should be able to remove it. Do you mind trying that? That should just run the existing `reshape_symint` kernel defined [here](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/TensorShape.cpp#L1627). And that should be identical to the current behavior, since the "registration" for reshape in XLA just calls back into ATen ([code](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp#L3599))

**Comment by JackCaoG** [comment]
I merged https://github.com/pytorch/xla/pull/6230, let's wait and see if tmr's nightly will resolve this issue.

**Comment by mfatih7** [comment]
Thank you.

I will test it and give feedback.
Till now, I have run my experiments with the warning.
Do I need to rerun the experiments?

**Comment by mfatih7** [comment]
OK, with the recent nighly versions of Pytorch and Pytorch-XLA
I do not observe the warning anymore while running my experiments.

Thank you.

Should I rerun the experiments that were run with past Pytorch versions throwing the warning?
Does this update only remove the warning or does it also change the calculations that I ran with the previous Pytorch versions?
Can I rely on my previous experiments?

**Comment by mfatih7** [comment]
Hello @JackCaoG 

I am using nightly without any problem.
What should I do? Wait for new update?

**Comment by JackCaoG** [comment]
if you don't see any regression in performance, you can likely just keep using today's nightly. I am not even sure if that warning has any real impact on the model yet.

**Comment by mfatih7** [comment]
Thank you for the answer

Reverting https://github.com/pytorch/xla/issues/6002 will cause problem for me.
But reverting https://github.com/pytorch/xla/pull/6230 will only regenerate the warning.

In my experiments, till now, I have not observed any difference with or without the warning.
But I am not 100% sure.

I'm looking forward to any more information you can give me.

**Comment by nom** [comment]
Seeing the same error. Any solutions? @JackCaoG

**Comment by JackCaoG** [comment]
Yea I need to find someone to look into this issue. It seems like removing the reshape lowering will introduce a regression in performance.

**Comment by markusheimerl** [comment]
I am facing the same issue, I don't even have a "reshape" call in my code anywhere.
https://github.com/ratisbonrobotics/xformer/blob/main/lxformer_tpu/lxformer_train_tpu.py

**Comment by JackCaoG** [comment]
reopened https://github.com/pytorch/xla/pull/6618, will try to fix this before the 2.3 release branch cut.

**Comment by JackCaoG** [comment]
@wonjoolee95 will lead the investigation on the regression that blocks merging https://github.com/pytorch/xla/pull/6618. Regression only happens in dynamo so my guess is it has something to do with functionization pass..

**Comment by wonjoolee95** [comment]
Running through a small example with `torch.reshape` on HEAD and on https://github.com/pytorch/xla/pull/6618, the snippet HLOo generated for `reshape` in both cases are:
```
HloModule IrToHlo.4, entry_computation_layout={(f32[4]{0})->(f32[2,2]{1,0})}

ENTRY %IrToHlo.4 (p0.1: f32[4]) -> (f32[2,2]) {
  %p0.1 = f32[4]{0} parameter(0)
  %reshape.2 = f32[2,2]{1,0} reshape(f32[4]{0} %p0.1)
  ROOT %tuple.3 = (f32[2,2]{1,0}) tuple(f32[2,2]{1,0} %reshape.2)
}
```
Now will try to experiment with functionalizaton explicitly on/off to see if there are some unexpected decompositions.

**Comment by eyclk** [comment]
I am also experiencing the same problem. I have also seen significant reduction in the learning capabilities of my model. My model has more than 80% accuracy when I trained it in another device without xla. However, it's accuracy has been reduced to less than 10% when I trained on a GCP TPU VM with pytorch-xla. It is also visible loss values of consecutive epochs during training. Here is a portion of the output including the error message:

`{'loss': 0.0288, 'grad_norm': 0.26168572902679443, 'learning_rate': 4.1665278934221486e-05, 'epoch': 6.0}      
{'eval_loss': 0.02541203238070011, 'eval_runtime': 5.4579, 'eval_samples_per_second': 615.621, 'eval_steps_per_second': 19.238, 'epoch': 6.0}                                                                                 
 20%|█████████████▍                                                     | 2502/12510 [28:36<1:08:07,  2.45it/s/home/ege_cite_pred/miniconda3/envs/ege/lib/python3.8/site-packages/torch/autograd/__init__.py:266: UserWarning: aten::reshape: an autograd kernel was not registered to the Autograd key(s) but we are trying to backprop through it. This may lead to silently incorrect behavior. This behavior is deprecated and will be removed in a future version of PyTorch. If your operator is differentiable, please ensure you have registered an autograd kernel to the correct Autograd key (e.g. DispatchKey::Autograd, DispatchKey::CompositeImplicitAutograd). If your operator is not differentiable, or to squash this warning and use the previous behavior, please register torch::CppFunction::makeFallthrough() to DispatchKey::Autograd. (Triggered internally at ../torch/csrc/autograd/autograd_not_implemented_fallback.cpp:63.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
{'loss': 0.0289, 'grad_norm': 0.2719034254550934, 'learning_rate': 3.992922564529559e-05, 'epoch': 7.0}        
{'eval_loss': 0.02541203238070011, 'eval_runtime': 5.4422, 'eval_samples_per_second': 617.398, 'eval_steps_per_second': 19.294, 'epoch': 7.0}                                                                                 
 23%|███████████████▋                                                   | 2919/12510 [31:44<1:05:13,  2.45it/s/home/ege_cite_pred/miniconda3/envs/ege/lib/python3.8/site-packages/torch/autograd/__init__.py:266: UserWarning: aten::reshape: an autograd kernel was not registered to the Autograd key(s) but we are trying to backprop through it. This may lead to silently incorrect behavior. This behavior is deprecated and will be removed in a future version of PyTorch. If your operator is differentiable, please ensure you have registered an autograd kernel to the correct Autograd key (e.g. DispatchKey::Autograd, DispatchKey::CompositeImplicitAutograd). If your operator is not differentiable, or to squash this warning and use the previous behavior, please register torch::CppFunction::makeFallthrough() to DispatchKey::Autograd. (Triggered internally at ../torch/csrc/autograd/autograd_not_implemented_fallback.cpp:63.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
{'loss': 0.0288, 'grad_norm': 0.242997944355011, 'learning_rate': 3.8193172356369694e-05, 'epoch': 8.0}        
{'eval_loss': 0.02541203238070011, 'eval_runtime': 5.4432, 'eval_samples_per_second': 617.286, 'eval_steps_per_second': 19.29, 'epoch': 8.0} `

I am also receiving this error message at every epoch. Is it possible to register CompositeImplicitAutograd key to autograd kernel like the error message says? If someone could provide me instructions of registering this key, I could try to see if this fixes the error or at least the reduction of the performance. I don't have enough experience in this area yet. So, I couldn't find a way of registering the autograd key.

**Comment by wonjoolee95** [comment]
Hey @eyclk, thanks for reporting the issue. Just to confirm, the warning messages in the original issue should not have an impact in the performance. We tried to remove this warning message and merged https://github.com/pytorch/xla/pull/6230, which caused a performance regression (which is now reverted in head). Which nightlies did you observe the performance regression in your case?

**Comment by wonjoolee95** [comment]
Running a quick experiment on resnet18, the performance is more or so similar with HEAD and reshape op removed. With HEAD, timing some runs of the resnet18 dynamo unit test:
```
[WONJOO]: time elapsed: 9.129651308059692 seconds
[WONJOO]: time elapsed: 8.280561447143555 seconds
[WONJOO]: time elapsed: 8.603920698165894 seconds
```
And timing some runs of the resnet18 dynamo unit test with `reshape` removed:
```
[WONJOO]: time elapsed: 8.229429483413696 seconds
[WONJOO]: time elapsed: 8.387555837631226 seconds
[WONJOO]: time elapsed: 9.10478949546814 seconds
```
Before we continue further with the investigation, @JackCaoG and I discussed that if simply registering this kernel to both the AutogradXLA and XLA dispatch keys would remove the warning message, we might just do that.. though I'm not too familiar this. @bdhirsh, do you know how can we register the kernel?

**Comment by eyclk** [comment]
Hello @wonjoolee95. This message seems to slightly reduced the performance of my model unlike others. I am not absolutely sure about this but I made some additional observations that lead me to believe that. I have tried the same model on a GPU without XLA. It has somewhat higher performance compared to TPU VM with Pytorch_XLA. 

However, my main problem is the reduction of learning capabilities after training. This error message reduced my result metrics after training from ~80% to ~20% under the same conditions.

Also, my output for each epoch shows the same eval_loss value. My other experiments on a GPU had the same eval loss value on epoch 1. It seems the model (with TPU XLA) is learning only for the first epoch and fails to properly backprop. Thus, it keeps repeating the first epoch again and again. Although I am not sure about this, it is the only explanation I could come up.

I am not sure which nightly version I am using. However, I know that I downloaded this library on February 29th using this command: "pip install torch~=2.2.0 torch_xla[tpu]~=2.2.0 -f https://storage.googleapis.com/libtpu-releases/index.html"

**Comment by wonjoolee95** [comment]
Hey @eyclk, I wonder if that's a different issue -- could you open a separate issue in PyTorch/XLA?

Since Brian is OOO, @albanD, do you have any idea on the kernel registration mentioned in https://github.com/pytorch/pytorch/issues/115816#issuecomment-1977753240?

**Comment by albanD** [comment]
From the warning, you are hitting the AutogradXLA key since the fallback at that key is triggering this warning.
So the problem is that your differentiable reshape implementation should be registered at that key.

If you say above that "ResigisterAutogradXLA.h/cpp." gets generated then I would check if reshare is there. If it is, I would double check that this file is properly included in your binary and properly registers the kernels.
You can also check `str(torch._C._dispatch_dump_table("aten::reshape"))` to see all the kernels registered for that op and from where

**Comment by wonjoolee95** [comment]
Hey @albanD, thanks for the pointers! I tried to register the `reshape` op to `RegisterAutogradXLA.h` with https://github.com/pytorch/xla/pull/6752. With this PR, I could see it get registered:
```
at::Tensor wrapper_AutogradXLA__reshape(const at::Tensor & self, c10::SymIntArrayRef shape) {
    // No device check
  // DeviceGuard omitted
  return torch_xla::XLANativeFunctions::reshape(self, C10_AS_INTARRAYREF_SLOW(shape));
}
...
    m.impl("reshape",
    TORCH_FN(wrapper_AutogradXLA__reshape));
```
However, now I'm getting the error:
```
RuntimeError: !at::functionalization::impl::isFunctionalTensor(t) INTERNAL ASSERT FAILED at "/home/wonjoo/pytorch/aten/src/ATen/FunctionalTensorWrapper.cpp":766, please report a bug to PyTorch. The composite op functionalization fallback expects its inputs all not to be functional tensors
```
I assume something is wrong with our new lowering, which is just a redispatch to functionalization -- https://github.com/pytorch/xla/pull/6752/files#diff-5e65c3c1d847191cb691d1874732e971f09fa1aad7a980a555c3b0504a5b6470L3662. However, this seems to be what we're doing for some of similar ops -- https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp#L3489. Maybe I'm just confused here lol, do you see anything obvious that is wrong? Thanks for the help, again!
