### ISSUE TITLE
Issue while tracing `one_hot` op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [pytorch/pytorch#115817]
### 🐛 Describe the bug

While tracing the [`one_hot`](https://pytorch.org/docs/stable/generated/torch.nn.functional.one_hot.html) using make_fx, it throws the following error:
```
RuntimeError: It appears that you're trying to get value out of a tracing tensor with aten._local_scalar_dense.default - erroring out! It's likely that this is caused by data-dependent control flow or similar.  It may be possible to trace this with dynamic shapes; try setting tracing_mode='symbolic' in your make_fx call.
```
To reproduce the error, run the following code:
```
import torch
from torch.fx.experimental.proxy_tensor import make_fx

class OneHot(torch.nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, input):
        return torch.nn.functional.one_hot(input, num_classes=5)

onehot = OneHot()
input = torch.arange(0, 5)
fx_g = make_fx(onehot)(input)
```

### Versions

Collecting environment information...
PyTorch version: 2.2.0.dev20231212+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.11.5 (main, Aug 25 2023, 13:19:50) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.2.0-1013-gcp-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             96
On-line CPU(s) list:                0-95
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) CPU @ 2.00GHz
CPU family:                         6
Model:                              85
Thread(s) per core:                 2
Core(s) per socket:                 24
Socket(s):                          2
Stepping:                           3
BogoMIPS:                           4000.35
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          1.5 MiB (48 instances)
L1i cache:                          1.5 MiB (48 instances)
L2 cache:                           48 MiB (48 instances)
L3 cache:                           77 MiB (2 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-23,48-71
NUMA node1 CPU(s):                  24-47,72-95
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Mitigation; PTE Inversion
Vulnerability Mds:                  Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:             Mitigation; PTI
Vulnerability Mmio stale data:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:             Mitigation; IBRS
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Mitigation; Clear CPU buffers; SMT Host state unknown

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0rc1
[pip3] pytorch-lightning==2.1.2
[pip3] torch==2.2.0.dev20231212+cpu
[pip3] torchmetrics==1.1.2
[pip3] torchvision==0.18.0.dev20231212+cpu
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305 @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv

**Comment by vivekkhandelwal1** [comment]
@Chillee, can you please take a look at this issue?

**Comment by vivekkhandelwal1** [comment]
@Chillee @davidberard98 @jansel Can you please take a look at this issue?

**Comment by voznesenskym** [comment]
Does it work w/ compile?

**Comment by vivekkhandelwal1** [comment]
> import torch
> from torch.fx.experimental.proxy_tensor import make_fx
> 
> class OneHot(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>     
>     def forward(self, input):
>         return torch.nn.functional.one_hot(input, num_classes=5)
> 
> onehot = OneHot()
> input = torch.arange(0, 5)
> fx_g = make_fx(onehot)(input)

@voznesenskym, it gives the same error with `torch.compile`.

**Comment by vivekkhandelwal1** [comment]
Hi all, it's been a week since I reported this issue. I'm still blocked on this. Can you please let me know who's the best person to look at this?

**Comment by HaoLiuHust** [comment]
same problem, any one knows the workaround?

**Comment by jansel** [comment]
As a workaround you can use:
```
def one_hot(tensor, num_classes):
    index = torch.arange(0, num_classes, device=tensor.device)
    return (
        tensor.view([*tensor.shape, 1]) == index.view([1] * tensor.ndim + [num_classes])
    ).to(torch.int64)
```
as a replacement for `torch.nn.functional.one_hot` that traces without issue.

**Comment by vivekkhandelwal1** [comment]
Thanks @jansel!
