### ISSUE TITLE
DISABLED test_scaled_dot_product_attention_cuda (__main__.CudaTests)

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#115897]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](http://torch-ci.com/failure/inductor%2Ftest_torchinductor.py%3A%3ACudaTests%3A%3Atest_scaled_dot_product_attention_cuda)).

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by cpuhrsch** [comment]
@drisspg - There's a bunch of these

**Comment by drisspg** [comment]
Yeah the flash_pr for ROCM has been reverted which is the cause of these failures

**Comment by malfet** [comment]
Closing as change has been reverted
