### ISSUE TITLE
Enable mostly-complete import-following for MYPYINDUCTOR

### ISSUE THREAD

**Issue by int3** [pytorch/pytorch#115805]
In particular, let's delete these `follow_imports=skip` lines in mypy-inductor.ini:

https://github.com/pytorch/pytorch/blob/ef01e78fd989c0e8a3fb817a9988a185b71d9084/mypy-inductor.ini#L53-L59

https://github.com/pytorch/pytorch/blob/ef01e78fd989c0e8a3fb817a9988a185b71d9084/mypy-inductor.ini#L64-L70

This will cause `follow_imports` to default to the value set at the top of the file:

https://github.com/pytorch/pytorch/blob/ef01e78fd989c0e8a3fb817a9988a185b71d9084/mypy-inductor.ini#L11

There are a few strategies for breaking this task down. First, you can enable importing of specific files in the module by adding an overriding config setting:

```
[mypy-torch._dynamo.variables.base]
follow_imports = silent
```

Another angle of attack is temporarily turning on `follow_imports=normal` for those modules, which will show any type errors that mypy has detected in them:

```
[mypy-torch.backends.*]
follow_imports = normal
```

These may point to wrong type signatures that then cause downstream errors when imported into inductor modules.

cc @ezyang @gchanan @zou3519 @kadeng @malfet @xuzhao9 @gramster @msaroufim @bdhirsh @anijain2305

**Comment by ColinPeppler** [comment]
PR for deleting [mypy-torch.backends.*] -- https://github.com/pytorch/pytorch/pull/116311

**Comment by zou3519** [comment]
There's some squiggly code in Dynamo because it's a bit difficult to exercise all the branches. Fixing all the typing issues would help.

**Comment by ezyang** [comment]
This is done.

**Comment by int3** [comment]
For context to future readers, this was done mostly via type ignores, and there are a lot of them that still have to be cleaned up in those modules mentioned above.
