### ISSUE TITLE
[inductor][cpu] cpp/default wrapper static/dynamic models performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#115827]
### 🐛 Describe the bug

<p>cpp wrapper dynamic perf regression in 2023-12-10</p><table border="1" class="dataframe table">
Note: multi threads secnario for models above first *, single thread for models between two *
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>basic_gnn_edgecnn</td>
      <td>1.0</td>
      <td>1.153136</td>
      <td>0.026080508</td>
      <td>0.030074372673087997</td>
      <td>10.511165</td>
      <td>1</td>
      <td>1.412077</td>
      <td>0.020654378999999997</td>
      <td>0.029165573535182995</td>
      <td>10.480688</td>
      <td>0.82</td>
      <td>0.97</td>
      <td>0.79</td>
      <td>1.0</td>
    </tr>
    <tr>
      <td>phlippe_densenet</td>
      <td>128.0</td>
      <td>1.266031</td>
      <td>0.032716634999999994</td>
      <td>0.04142027412568499</td>
      <td>24.234041</td>
      <td>128</td>
      <td>2.090897</td>
      <td>0.01917598</td>
      <td>0.04009499905406</td>
      <td>24.788668</td>
      <td>0.61</td>
      <td>0.97</td>
      <td>0.59</td>
      <td>1.02</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>basic_gnn_edgecnn</td>
      <td>1.0</td>
      <td>0.728792</td>
      <td>0.44303632</td>
      <td>0.32288132572544</td>
      <td>11.245185</td>
      <td>1</td>
      <td>1.398682</td>
      <td>0.231268594</td>
      <td>0.323471219593108</td>
      <td>10.179844</td>
      <td>0.52</td>
      <td>1.0</td>
      <td>0.52</td>
      <td>0.91</td>
    </tr>
    <tr>
      <td>phlippe_densenet</td>
      <td>1.0</td>
      <td>0.734558</td>
      <td>0.006644771000000001</td>
      <td>0.0048809696962180005</td>
      <td>21.478526</td>
      <td>1</td>
      <td>1.783654</td>
      <td>0.00270333</td>
      <td>0.00482180536782</td>
      <td>22.45328</td>
      <td>0.41</td>
      <td>0.99</td>
      <td>0.41</td>
      <td>1.05</td>
    </tr>
    <tr>
      <td>dpn107</td>
      <td>1.0</td>
      <td>1.025812</td>
      <td>0.303678612</td>
      <td>0.311517164332944</td>
      <td>46.058145</td>
      <td>1</td>
      <td>1.214006</td>
      <td>0.257941989</td>
      <td>0.31314312229793395</td>
      <td>50.101759</td>
      <td>0.84</td>
      <td>1.01</td>
      <td>0.85</td>
      <td>1.09</td>
    </tr>
    <tr>
      <td>mixnet_l</td>
      <td>1.0</td>
      <td>0.768408</td>
      <td>0.047755254999999996</td>
      <td>0.03669551998404</td>
      <td>61.689027</td>
      <td>1</td>
      <td>1.285747</td>
      <td>0.028545031999999998</td>
      <td>0.036701689258904</td>
      <td>70.545549</td>
      <td>0.6</td>
      <td>1.0</td>
      <td>0.6</td>
      <td>1.14</td>
    </tr>
    <tr>
      <td>tf_mixnet_l</td>
      <td>1.0</td>
      <td>0.866044</td>
      <td>0.044746979000000006</td>
      <td>0.038752852681076005</td>
      <td>66.621348</td>
      <td>1</td>
      <td>1.44899</td>
      <td>0.026826379</td>
      <td>0.03887115490721</td>
      <td>75.937673</td>
      <td>0.6</td>
      <td>1.0</td>
      <td>0.6</td>
      <td>1.14</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>

</table><p>cpp wrapper static perf regression in 2023-12-10</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>basic_gnn_edgecnn</td>
      <td>1.0</td>
      <td>1.174265</td>
      <td>0.02649495</td>
      <td>0.031112092461749997</td>
      <td>10.504328</td>
      <td>1</td>
      <td>1.558073</td>
      <td>0.017143692999999998</td>
      <td>0.026711125183588997</td>
      <td>10.541625</td>
      <td>0.75</td>
      <td>0.86</td>
      <td>0.65</td>
      <td>1.0</td>
    </tr>
    <tr>
      <td>phlippe_densenet</td>
      <td>128.0</td>
      <td>1.288095</td>
      <td>0.032035274</td>
      <td>0.04126447626303</td>
      <td>21.64901</td>
      <td>128</td>
      <td>2.178804</td>
      <td>0.018174119000000002</td>
      <td>0.039597843173676005</td>
      <td>22.522214</td>
      <td>0.59</td>
      <td>0.96</td>
      <td>0.57</td>
      <td>1.04</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>basic_gnn_edgecnn</td>
      <td>1.0</td>
      <td>0.722478</td>
      <td>0.444041428</td>
      <td>0.320810162818584</td>
      <td>11.244087</td>
      <td>1</td>
      <td>1.397451</td>
      <td>0.22696192099999998</td>
      <td>0.31716816346337096</td>
      <td>10.11365</td>
      <td>0.52</td>
      <td>0.99</td>
      <td>0.51</td>
      <td>0.9</td>
    </tr>
    <tr>
      <td>phlippe_densenet</td>
      <td>1.0</td>
      <td>0.728483</td>
      <td>0.006608327</td>
      <td>0.004814053877941</td>
      <td>21.471807</td>
      <td>1</td>
      <td>1.799365</td>
      <td>0.002654146</td>
      <td>0.0047757774172900004</td>
      <td>22.364572</td>
      <td>0.4</td>
      <td>0.99</td>
      <td>0.4</td>
      <td>1.04</td>
    </tr>
    <tr>
      <td>dpn107</td>
      <td>1.0</td>
      <td>1.02857</td>
      <td>0.30321032600000003</td>
      <td>0.31187304501382</td>
      <td>46.053792</td>
      <td>1</td>
      <td>1.203746</td>
      <td>0.256560207</td>
      <td>0.308833322935422</td>
      <td>49.773259</td>
      <td>0.85</td>
      <td>0.99</td>
      <td>0.85</td>
      <td>1.08</td>
    </tr>
    <tr>
      <td>mixnet_l</td>
      <td>1.0</td>
      <td>0.762973</td>
      <td>0.047681216</td>
      <td>0.036379480415167996</td>
      <td>61.465656</td>
      <td>1</td>
      <td>1.266598</td>
      <td>0.027587063000000002</td>
      <td>0.034941718821673996</td>
      <td>69.414338</td>
      <td>0.6</td>
      <td>0.96</td>
      <td>0.58</td>
      <td>1.13</td>
    </tr>
    <tr>
      <td>tf_mixnet_l</td>
      <td>1.0</td>
      <td>0.867573</td>
      <td>0.044670536</td>
      <td>0.038754950929128</td>
      <td>66.186837</td>
      <td>1</td>
      <td>1.433762</td>
      <td>0.026163665000000003</td>
      <td>0.03751246865773</td>
      <td>75.724072</td>
      <td>0.61</td>
      <td>0.97</td>
      <td>0.59</td>
      <td>1.14</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>

</table><p>default wrapper fp32 dynamic shape perf regression in 2023-12-12</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>basic_gnn_edgecnn</td>
      <td>1.0</td>
      <td>1.183021</td>
      <td>0.025200153</td>
      <td>0.029812310202213</td>
      <td>9.311819</td>
      <td>1</td>
      <td>1.461733</td>
      <td>0.019813834</td>
      <td>0.028962535014321996</td>
      <td>9.366742</td>
      <td>0.81</td>
      <td>0.97</td>
      <td>0.79</td>
      <td>1.01</td>
    </tr>
    <tr>
      <td>cm3leon_generate</td>
      <td>1.0</td>
      <td>0.520835</td>
      <td>3.751758428</td>
      <td>1.95404710084738</td>
      <td>312.554097</td>
      <td>1</td>
      <td>0.608255</td>
      <td>3.1966759259999997</td>
      <td>1.9443941153691298</td>
      <td>349.783647</td>
      <td>0.86</td>
      <td>1.0</td>
      <td>0.85</td>
      <td>1.12</td>
    </tr>
    <tr>
      <td>phlippe_densenet</td>
      <td>128.0</td>
      <td>1.193387</td>
      <td>0.034047513</td>
      <td>0.040631859396531</td>
      <td>43.525584</td>
      <td>128</td>
      <td>1.922596</td>
      <td>0.020909179000000003</td>
      <td>0.040199903908684005</td>
      <td>44.000734</td>
      <td>0.62</td>
      <td>0.99</td>
      <td>0.61</td>
      <td>1.01</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>basic_gnn_edgecnn</td>
      <td>1.0</td>
      <td>0.72673</td>
      <td>0.44741206099999997</td>
      <td>0.32514776709052995</td>
      <td>9.96963</td>
      <td>1</td>
      <td>1.394394</td>
      <td>0.231838244</td>
      <td>0.323273856404136</td>
      <td>8.940581</td>
      <td>0.52</td>
      <td>0.99</td>
      <td>0.52</td>
      <td>0.9</td>
    </tr>
    <tr>
      <td>phlippe_densenet</td>
      <td>1.0</td>
      <td>0.662465</td>
      <td>0.0073142120000000005</td>
      <td>0.00484540945258</td>
      <td>40.647095</td>
      <td>1</td>
      <td>1.34803</td>
      <td>0.003587731</td>
      <td>0.00483636901993</td>
      <td>41.098402</td>
      <td>0.49</td>
      <td>1.0</td>
      <td>0.49</td>
      <td>1.01</td>
    </tr>
    <tr>
      <td>dpn107</td>
      <td>1.0</td>
      <td>1.01738</td>
      <td>0.307479412</td>
      <td>0.31282340418056</td>
      <td>58.462545</td>
      <td>1</td>
      <td>1.181493</td>
      <td>0.26492231099999997</td>
      <td>0.31300385599032293</td>
      <td>63.608867</td>
      <td>0.86</td>
      <td>1.0</td>
      <td>0.86</td>
      <td>1.09</td>
    </tr>
    <tr>
      <td>mixnet_l</td>
      <td>1.0</td>
      <td>0.700862</td>
      <td>0.05101012</td>
      <td>0.03575105472344</td>
      <td>65.457103</td>
      <td>1</td>
      <td>1.147621</td>
      <td>0.031892148</td>
      <td>0.036600098779908004</td>
      <td>70.431558</td>
      <td>0.61</td>
      <td>1.02</td>
      <td>0.63</td>
      <td>1.08</td>
    </tr>
    <tr>
      <td>tf_mixnet_l</td>
      <td>1.0</td>
      <td>0.806504</td>
      <td>0.048309134999999996</td>
      <td>0.03896151061404</td>
      <td>79.998338</td>
      <td>1</td>
      <td>1.268461</td>
      <td>0.030327074</td>
      <td>0.038468710613114</td>
      <td>84.866033</td>
      <td>0.64</td>
      <td>0.99</td>
      <td>0.63</td>
      <td>1.06</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>5da0a5d</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>6518fa9</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>e12d200</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+git6fc9d89</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.17.0a0+c1e2095</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.1.1+db62484</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>

Repro
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single/multiple inference performance torchbench/huggingface/timm_models model float32 first static/dynamic cpp/default 0
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/0ee1e469cb28c43d63542c03b7efff50b71198a0
[timm_models-dpn107-inference-float32-dynamic-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13674572/timm_models-dpn107-inference-float32-dynamic-default-performance-single-drop_guilty_commit.log)
cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @WeizhuoZhang-intel @chuanqi129

**Comment by jiayisunx** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/116313
