### ISSUE TITLE
[inductor][cpu] XLNetLMHeadModel amp single threads performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#115823]
<p>XLNetLMHeadModel amp single threads performance regression in 2023-12-07</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>XLNetLMHeadModel</td>
      <td>1</td>
      <td>1.563593</td>
      <td>1.3945756200000001</td>
      <td>2.18054867740266</td>
      <td>44.566111</td>
      <td>1</td>
      <td>1.646664</td>
      <td>1.218400873</td>
      <td>2.006296855137672</td>
      <td>43.879981</td>
      <td>0.95</td>
      <td>0.92</td>
      <td>0.87</td>
      <td>0.98</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>742864d</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>7617d3f5</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>e6efc29</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>7617d3f5</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+git56a830e</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.16.0a0+8636bf3</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+142d029</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+475b6ae</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+eb9bf61</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>e6efc29</td>
    </tr>
  </tbody>

Repro
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single inference performance huggingface XLNetLMHeadModel amp first static default 0
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/afbaa0c1650cf15100fb5dc579ceeba24fb8665a
[huggingface-XLNetLMHeadModel-inference-amp-static-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13674064/huggingface-XLNetLMHeadModel-inference-amp-static-default-performance-single-drop_guilty_commit.log)
cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @WeizhuoZhang-intel @chuanqi129

**Comment by chunyuan-w** [comment]
@zxd1997066 to help double-confirm the guilty commit

**Comment by zxd1997066** [comment]
After double check, the suspected guilty commit is https://github.com/pytorch/pytorch/commit/afbaa0c1650cf15100fb5dc579ceeba24fb8665a
[huggingface-XLNetLMHeadModel-inference-amp-static-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13722178/huggingface-XLNetLMHeadModel-inference-amp-static-default-performance-single-drop_guilty_commit.log)

**Comment by Xia-Weiwen** [comment]
Hi @zxd1997066 Could you provide the onednn verbose log v3.1.1 vs v3.3.2 of one iteration? Thanks!

**Comment by chuanqi129** [comment]
track the issue in #115346 , close this one

**Comment by Xia-Weiwen** [comment]
We found perf regression of oneDNN matmul primitive. We have contact oneDNN team and need their fix.
