### ISSUE TITLE
docker image with -ipc=host option

### ISSUE THREAD

**Issue by vditya** [pytorch/pytorch#1158]
Can you please clarify why you need -ipc=host instead of just specifying -shm-size at nvidia-docker run command? Purpose of -ipc=host is to place container on host IPC namespace and since all processes are within container namespace, should -shm-size not be enough? Thanks

**Comment by ngimel** [comment]
--shm-size would also be enough, but you'd need to set shared memory size that's enough for your workload. --ipc=host sets shared memory to the same value it has on bare metal.
