### ISSUE TITLE
AttributeError: module 'torch.cpu' has no attribute 'current_device' when loading checkpoints

### ISSUE THREAD

**Issue by gouchangjiang** [pytorch/pytorch#115815]
### 🐛 Describe the bug

```
optim_state = load_sharded_optimizer_state_dict(
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torch/distributed/checkpoint/optimizer.py", line 295, in load_sharded_optimizer_state_dict
    _alloc_tensor(value.properties, value.size, dp_pg_device_type), sharding_spec
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torch/distributed/checkpoint/optimizer.py", line 109, in _alloc_tensor
    device=cast(torch.device, _get_device_module(device_type).current_device()),
AttributeError: module 'torch.cpu' has no attribute 'current_device'
```

It happens when running the example of saving distributed checkpoints of FSDP models. The [example](https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/examples/fsdp_checkpoint_example.py) is provided by PyTorch. It disappears if I set `dist.init_process_group("cuda:nccl", rank=rank, world_size=world_size)`

### Versions

pytorch version 2.1.0

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by fegin** [comment]
cc., @LucasLLC Can you take a look of this issue?

**Comment by wz337** [comment]
Hey @gouchangjiang. There is a fix in PT, but it is not included in 2.1. You can try nightly for now, and release/2.2 should have the fix. 

https://github.com/pytorch/pytorch/blob/release/2.2/torch/cpu/__init__.py#L17

**Comment by wconstab** [comment]
shall we close the issue then? (Please confirm fixed on nightly)

**Comment by gouchangjiang** [comment]
Thank you all. I tested with the pytorch nightly, the problem is solved.
