### ISSUE TITLE
info: version 2.1.2 does not build against cuSPARSELt 0.5.2

### ISSUE THREAD

**Issue by peutch** [pytorch/pytorch#115987]
### 🚀 The feature, motivation and pitch

Hi,

This was found after updating libcusparselt-dev using the NVIDIA Ubuntu repository: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/.

In particular its release note (https://docs.nvidia.com/cuda/cusparselt/release_notes.html#cusparselt-v0-5-2) says:

CUSPARSE_COMPUTE_16F, CUSPARSE_COMPUTE_TF32, CUSPARSE_COMPUTE_TF32_FAST enumerators have been removed for the cusparseComputeType enumerator and replaced with CUSPARSE_COMPUTE_32F to better express the accuracy of the computation at tensor core level.

Regards,
Patrice

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip

**Comment by jcaip** [comment]
Hey @peutch thanks for flagging, we have a PR: https://github.com/pytorch/pytorch/pull/115988 that should fix this.

**Comment by peutch** [comment]
Hi @jcaip, many thanks! I will try this soon.

**Comment by jcaip** [comment]
closing as #115988 has merged
