### ISSUE TITLE
Can't run autocast on XLA, if PyTorch was compiled with CUDA support.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#115900]
### 🐛 Describe the bug

The following program doesn't execute successfully:

```python
import torch_xla.core.xla_model as xm
from torch.amp import autocast

with autocast("cuda", dtype=torch.bfloat16):
    x = torch.tensor([5.], device=xm.xla_device())
```

```python
Traceback (most recent call last):
  File "examples/autocast.py", line 5, in <module>
    with autocast("cuda", dtype=torch.bfloat16):
  File "torch/amp/autocast_mode.py", line 306, in __init__
    raise RuntimeError(
RuntimeError: Current CUDA Device does not support bfloat16. Please switch dtype to float16.
```

However, the following runs fine:

```python
>>> a = torch.rand(5, 5, dtype=torch.bfloat16, device="cuda")
>>> a @ a
tensor([...], device='cuda:0', dtype=torch.bfloat16)
```

This error is popping out on PyTorch/XLA CI: https://github.com/pytorch/xla/issues/6085. 
**Problem:** PyTorch and XLA have different implementations for `is_bf16_supported`.

- [PyTorch](https://github.com/pytorch/pytorch/blob/5477120ebfe73ececead8d80607535c543302666/torch/cuda/__init__.py#L144): tests CUDA version + compute capability
- [PyTorch/XLA](https://github.com/pytorch/xla/blob/e500129ab431ee744cd3d5658d52dffa3343fa7d/torch_xla/runtime.py#L92C13-L92C13): tests the creation of a tensor

### Versions

- GPU: RTX 2060
- PyTorch: a93b9ee9d8fb931c86a613ce235e5d8acaf48011
- PyTorch/XLA: bf5edb3938245b0d125f222b2a07ac0835a90081

cc @bdhirsh

**Comment by ysiraichi** [comment]
One possible solution: if all checks for `is_bf16_supported` fail on PyTorch, we should also check for tensor creation, similar to how PyTorch/XLA checks it.

**Comment by ysiraichi** [comment]
cc @JackCaoG @miladm @lezcano

**Comment by JackCaoG** [comment]
@yeounoh FYI
