### ISSUE TITLE
build on macos fails on no matching function for call to 'xnn_setup_fully_connected_nc_qs8'

### ISSUE THREAD

**Issue by drmatthewclark** [pytorch/pytorch#115930]
### 🐛 Describe the bug

build with 
python setup.py build develop  >  build.log 2>&1 
fails with errors 
[build.log](https://github.com/pytorch/pytorch/files/13686939/build.log)

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.1.2 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: version 3.28.0
Libc version: N/A

Python version: 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ] (64-bit runtime)
Python platform: macOS-14.1.2-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] optree==0.10.0
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] optree                    0.10.0                   pypi_0    pypi

cc @malfet @seemethere @albanD

**Comment by malfet** [comment]
Try running `git submodule update` (looks like your XNN pack is out of date) or do a clean build

**Comment by drmatthewclark** [comment]
yes that simple "git submodule update" worked;  the build then completed.  I had run git clone, then git pull to get updates.
