### ISSUE TITLE
build error    error: unknown type name 'PROTOBUF_NAMESPACE_OPEN'

### ISSUE THREAD

**Issue by drmatthewclark** [pytorch/pytorch#115980]
### 🐛 Describe the bug

[build.log](https://github.com/pytorch/pytorch/files/13692016/build.log)

### Versions

build fails

**Comment by drmatthewclark** [comment]
configuration error.

**Comment by anggara-kaskus** [comment]
hi! how did you fix it?

**Comment by matthew-ability** [comment]
I restarted the build from a clean environment, newly downloading all of the dependencies.
