### ISSUE TITLE
Adam eager dynamic model failures

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#115968]
### 🐛 Describe the bug

When running our benchmarks with eager Adam, one model from the dynamic suite fail: hf_T5, 
note it doesn't fail on the static benchmarks

Running the full suite on the branch mlazos/adam-eager commit: ec93f143327a8d6c7562440a94349639e1163c74 repros the issue. If we're concerned I can update with a smaller repro.

[dashboard link](https://hud.pytorch.org/benchmark/dynamic/inductor_with_cudagraphs?startTime=Sat,%2009%20Dec%202023%2000:10:24%20GMT&stopTime=Sat,%2016%20Dec%202023%2000:10:24%20GMT&granularity=hour&mode=training&dtype=amp&lBranch=mlazos/adam-eager&lCommit=ec93f143327a8d6c7562440a94349639e1163c74&rBranch=main&rCommit=af925a56a195cc095c589af687513cdc22caf33a)

### Versions

Repros on nightly main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by mlazos** [comment]
It just went from pass -> undefined, I couldn't find a log with the error, I'll run locally and get a message.

**Comment by masnesral** [comment]
@mlazos is this still an issue? Looks like hf_T5 for dynamic is passing on the dashboard?

**Comment by mlazos** [comment]
I think we can close, I don't have time to find additional details on this
