### ISSUE TITLE
poisson_nll_loss wrong sign when reduction="none"

### ISSUE THREAD

**Issue by dsteinberg** [pytorch/pytorch#115904]
### 🐛 Describe the bug

`torch.nn.functional.poisson_nll_loss` has the wrong sign when reduction="none".

```python
import torch
from torch.distributions import Poisson
n = 10000
r = 10

poisson = Poisson(rate=r)
y = poisson.sample(sample_shape=(n,))

nll = torch.nn.functional.poisson_nll_loss(r * torch.ones(n), y, reduction="none")
mnll = torch.nn.functional.poisson_nll_loss(r * torch.ones(n), y, reduction="mean")
assert torch.allclose(mnll, nll.mean())
```
assertion fails with wrong sign.

### Versions

PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.2 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.0
Libc version: N/A

Python version: 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] (64-bit runtime)
Python platform: macOS-14.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] botorch==0.9.5
[pip3] flake8==6.1.0
[pip3] gpytorch==1.11
[pip3] mypy==1.7.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.2
[pip3] torch==2.1.1
[pip3] torcheval==0.0.7
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @malfet

**Comment by mikaylagawarecki** [comment]
Hey, I was unable to reproduce this on `main` with your script, could you try upgrading to the latest version of pytorch?

If the issue still persists, perhaps this is a macos only issue

**Comment by dsteinberg** [comment]
Thanks for looking into this @mikaylagawarecki!
I upgraded from PyTorch 2.1.1 to 2.1.2 and this does not seem to be an issue anymore.
