### ISSUE TITLE
Why __torch_dispatch__ behavior is different between privateuse1 and cpu.

### ISSUE THREAD

**Issue by Bin1024** [pytorch/pytorch#116005]
## Issue description
We tested the __torch_dispatch__ of the operator at privateuse1(npu) and found a strange phenomenon. For example, for the matmul operator, both privateuse1 and cpu call the mm operator. Why the privateuse1 side prints the torch_dispatch only for matmul and the cpu prints the small operator mm.

We have re-adapted matmul in the third party plugin npu and registered it under privateuse1. Our adapted code also calls the aten::mm operator. Why does torch_dispatch not capture the call on the plugin side.
We will execute the following code on the plugin side, same as cpu.Our namespace is different from cpu。
`
    at::Tensor output =  has_out ? at::_unsafe_view(at::mm_out(out, t1, t2), output_size) : at::_unsafe_view(t1.mm(t2), output_size);
`
Does __torch_dispatch__  have any restrictions on the plugin side?
Can you give me some advice and help? @ezyang @albanD 

## Code example
This is my test code.

```
class LoggingMode(TorchDispatchMode):
    def __init__(self):
        return super().__init__()
    def __torch_dispatch__(self, func, types, args=(), kwargs=None):
        print(f"{func.__module__} {func.__name__}")
        return func(*args, **kwargs)

x = torch.randn(4, 128, 512).to(device)
l = torch.nn.Linear(512, 136, bias=False).to(device)

with LoggingMode():
    y = l(x) 
```

The cpu result

```
torch._ops.aten t.default
torch._ops.aten view.default
torch._ops.aten mm.default
torch._ops.aten _unsafe_view.default
```

The privateuse1(npu) result
```
torch._ops.aten t.default
torch._ops.aten matmul.default
```

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version: 2.1
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

cc @Chillee @ezyang @zou3519 @albanD @samdow

**Comment by albanD** [comment]
Hey

To solve these, you can look into details at native_function.yaml and the dispatch table for each operator (`print(torch._C._dispatch_dump("aten::matmul"))`).

But in general, if the ops is done through the dispatcher (at:: or dispatcher call), it will hit the torch_dispatch handler as long as one of the inputs is a subclass.
Note that calling things like `at::native` or direct calls into the backend will bypass the dispatcher and thus bypass the torch_dispatch handler.

**Comment by Bin1024** [comment]
Thank you for your reply. I noticed that matmul operator is registered at native_function.yaml on CompositeImplicitAutograd. And our third party device which did the re-adaptation is registered on privateuse1. For the method torch_dispatch , if the key privateuse1 is distributed, it will print matmul directly and not print the distribution of the matmul call mm operator again. Is this the reason?

**Comment by FFFrog** [comment]
> Thank you for your reply.
> 
> I noticed that matmul operator is registered at native_function.yaml on CompositeImplicitAutograd. And our third party device which did the re-adaptation is registered on privateuse1. For the method torch_dispatch , if the key privateuse1 is distributed, it will print matmul directly and not print the distribution of the matmul call mm operator and other small operators again.
> 
> Is this the reason?

Yes, you are right.

The ops registered directly to the key have the highest priority, you can refer to [this](https://github.com/pytorch/pytorch/blob/2a440348958b3f0a2b09458bd76fe5959b371c0c/aten/src/ATen/core/dispatch/OperatorEntry.cpp#L261), so, the linear op in CompositeImplicitAutograd consisting of other small ops will be called, but for npu, the linear op may be called directly.

The call stack is as follow:

```C++
[call] op=[aten::linear], key=[PythonTLSSnapshot]
  [redispatchBoxed] op=[aten::linear], key=[AutogradCPU] -> linear in CompositeImplicitAutograd which have higher priority than Autograd
   [call] op=[aten::t], key=[PythonTLSSnapshot]
    [redispatchBoxed] op=[aten::t], key=[AutogradCPU]
     [redispatch] op=[aten::t], key=[ADInplaceOrView]
      [redispatch] op=[aten::t], key=[Python] -> torch._ops.aten t.default
       [callBoxed] op=[aten::t], key=[CPU]
        [call] op=[aten::transpose.int], key=[CPU]
         [call] op=[aten::as_strided], key=[CPU]
   [call] op=[aten::matmul], key=[PythonTLSSnapshot]
    [redispatchBoxed] op=[aten::matmul], key=[AutogradCPU]
     [call] op=[aten::reshape], key=[PythonTLSSnapshot]
      [redispatchBoxed] op=[aten::reshape], key=[AutogradCPU]
       [call] op=[aten::view], key=[PythonTLSSnapshot]
        [redispatchBoxed] op=[aten::view], key=[AutogradCPU]
         [redispatch] op=[aten::view], key=[ADInplaceOrView]
          [redispatch] op=[aten::view], key=[Python] -> torch._ops.aten view.default
           [callBoxed] op=[aten::view], key=[CPU]
     [call] op=[aten::mm], key=[PythonTLSSnapshot]
      [redispatchBoxed] op=[aten::mm], key=[AutogradCPU]
       [redispatch] op=[aten::mm], key=[Python] -> torch._ops.aten mm.default
        [callBoxed] op=[aten::mm], key=[CPU]
         [call] op=[aten::resolve_conj], key=[CPU]
         [call] op=[aten::resolve_conj], key=[CPU]
     [call] op=[aten::_unsafe_view], key=[PythonTLSSnapshot]
      [redispatchBoxed] op=[aten::_unsafe_view], key=[AutogradCPU]
       [redispatch] op=[aten::_unsafe_view], key=[Python] -> torch._ops.aten _unsafe_view.default
        [callBoxed] op=[aten::_unsafe_view], key=[CPU]
```

**Comment by Bin1024** [comment]
> > Thank you for your reply.
> > I noticed that matmul operator is registered at native_function.yaml on CompositeImplicitAutograd. And our third party device which did the re-adaptation is registered on privateuse1. For the method torch_dispatch , if the key privateuse1 is distributed, it will print matmul directly and not print the distribution of the matmul call mm operator and other small operators again.
> > Is this the reason?
> 
> Yes, you are right.
> 
> The ops registered directly to the key have the highest priority, you can refer to [this](https://github.com/pytorch/pytorch/blob/2a440348958b3f0a2b09458bd76fe5959b371c0c/aten/src/ATen/core/dispatch/OperatorEntry.cpp#L261), so, for cpu, the linear op in CompositeImplicitAutograd consisting of other small ops will be called, but for npu, the linear op may be called directly.
> 
> The call stack is as follow:
> 
> ```c++
> [call] op=[aten::linear], key=[PythonTLSSnapshot]
>   [redispatchBoxed] op=[aten::linear], key=[AutogradCPU] -> linear in CompositeImplicitAutograd which have higher priority than Autograd
>    [call] op=[aten::t], key=[PythonTLSSnapshot]
>     [redispatchBoxed] op=[aten::t], key=[AutogradCPU]
>      [redispatch] op=[aten::t], key=[ADInplaceOrView]
>       [redispatch] op=[aten::t], key=[Python] -> torch._ops.aten t.default
>        [callBoxed] op=[aten::t], key=[CPU]
>         [call] op=[aten::transpose.int], key=[CPU]
>          [call] op=[aten::as_strided], key=[CPU]
>    [call] op=[aten::matmul], key=[PythonTLSSnapshot]
>     [redispatchBoxed] op=[aten::matmul], key=[AutogradCPU]
>      [call] op=[aten::reshape], key=[PythonTLSSnapshot]
>       [redispatchBoxed] op=[aten::reshape], key=[AutogradCPU]
>        [call] op=[aten::view], key=[PythonTLSSnapshot]
>         [redispatchBoxed] op=[aten::view], key=[AutogradCPU]
>          [redispatch] op=[aten::view], key=[ADInplaceOrView]
>           [redispatch] op=[aten::view], key=[Python] -> torch._ops.aten view.default
>            [callBoxed] op=[aten::view], key=[CPU]
>      [call] op=[aten::mm], key=[PythonTLSSnapshot]
>       [redispatchBoxed] op=[aten::mm], key=[AutogradCPU]
>        [redispatch] op=[aten::mm], key=[Python] -> torch._ops.aten mm.default
>         [callBoxed] op=[aten::mm], key=[CPU]
>          [call] op=[aten::resolve_conj], key=[CPU]
>          [call] op=[aten::resolve_conj], key=[CPU]
>      [call] op=[aten::_unsafe_view], key=[PythonTLSSnapshot]
>       [redispatchBoxed] op=[aten::_unsafe_view], key=[AutogradCPU]
>        [redispatch] op=[aten::_unsafe_view], key=[Python] -> torch._ops.aten _unsafe_view.default
>         [callBoxed] op=[aten::_unsafe_view], key=[CPU]
> ```

I understand. Thanks.

**Comment by Bin1024** [comment]
I understand. Thanks.

**Comment by Bin1024** [comment]
> ```c++
> [Python] 
> ```

@FFFrog I have a question. Could you tell me how this call stack is printed out?

**Comment by Bin1024** [comment]
> > Thank you for your reply.
> > I noticed that matmul operator is registered at native_function.yaml on CompositeImplicitAutograd. And our third party device which did the re-adaptation is registered on privateuse1. For the method torch_dispatch , if the key privateuse1 is distributed, it will print matmul directly and not print the distribution of the matmul call mm operator and other small operators again.
> > Is this the reason?
> 
> Yes, you are right.
> 
> The ops registered directly to the key have the highest priority, you can refer to [this](https://github.com/pytorch/pytorch/blob/2a440348958b3f0a2b09458bd76fe5959b371c0c/aten/src/ATen/core/dispatch/OperatorEntry.cpp#L261), so, for cpu, the linear op in CompositeImplicitAutograd consisting of other small ops will be called, but for npu, the linear op may be called directly.
> 
> The call stack is as follow:
> 
> ```c++
> [call] op=[aten::linear], key=[PythonTLSSnapshot]
>   [redispatchBoxed] op=[aten::linear], key=[AutogradCPU] -> linear in CompositeImplicitAutograd which have higher priority than Autograd
>    [call] op=[aten::t], key=[PythonTLSSnapshot]
>     [redispatchBoxed] op=[aten::t], key=[AutogradCPU]
>      [redispatch] op=[aten::t], key=[ADInplaceOrView]
>       [redispatch] op=[aten::t], key=[Python] -> torch._ops.aten t.default
>        [callBoxed] op=[aten::t], key=[CPU]
>         [call] op=[aten::transpose.int], key=[CPU]
>          [call] op=[aten::as_strided], key=[CPU]
>    [call] op=[aten::matmul], key=[PythonTLSSnapshot]
>     [redispatchBoxed] op=[aten::matmul], key=[AutogradCPU]
>      [call] op=[aten::reshape], key=[PythonTLSSnapshot]
>       [redispatchBoxed] op=[aten::reshape], key=[AutogradCPU]
>        [call] op=[aten::view], key=[PythonTLSSnapshot]
>         [redispatchBoxed] op=[aten::view], key=[AutogradCPU]
>          [redispatch] op=[aten::view], key=[ADInplaceOrView]
>           [redispatch] op=[aten::view], key=[Python] -> torch._ops.aten view.default
>            [callBoxed] op=[aten::view], key=[CPU]
>      [call] op=[aten::mm], key=[PythonTLSSnapshot]
>       [redispatchBoxed] op=[aten::mm], key=[AutogradCPU]
>        [redispatch] op=[aten::mm], key=[Python] -> torch._ops.aten mm.default
>         [callBoxed] op=[aten::mm], key=[CPU]
>          [call] op=[aten::resolve_conj], key=[CPU]
>          [call] op=[aten::resolve_conj], key=[CPU]
>      [call] op=[aten::_unsafe_view], key=[PythonTLSSnapshot]
>       [redispatchBoxed] op=[aten::_unsafe_view], key=[AutogradCPU]
>        [redispatch] op=[aten::_unsafe_view], key=[Python] -> torch._ops.aten _unsafe_view.default
>         [callBoxed] op=[aten::_unsafe_view], key=[CPU]
> ```
@FFFrog I have a question. Could you tell me how this call stack is printed out?

**Comment by FFFrog** [comment]
> > > Thank you for your reply.
> > > I noticed that matmul operator is registered at native_function.yaml on CompositeImplicitAutograd. And our third party device which did the re-adaptation is registered on privateuse1. For the method torch_dispatch , if the key privateuse1 is distributed, it will print matmul directly and not print the distribution of the matmul call mm operator and other small operators again.
> > > Is this the reason?
> > 
> > 
> > Yes, you are right.
> > The ops registered directly to the key have the highest priority, you can refer to [this](https://github.com/pytorch/pytorch/blob/2a440348958b3f0a2b09458bd76fe5959b371c0c/aten/src/ATen/core/dispatch/OperatorEntry.cpp#L261), so, for cpu, the linear op in CompositeImplicitAutograd consisting of other small ops will be called, but for npu, the linear op may be called directly.
> > The call stack is as follow:
> > ```c++
> > [call] op=[aten::linear], key=[PythonTLSSnapshot]
> >   [redispatchBoxed] op=[aten::linear], key=[AutogradCPU] -> linear in CompositeImplicitAutograd which have higher priority than Autograd
> >    [call] op=[aten::t], key=[PythonTLSSnapshot]
> >     [redispatchBoxed] op=[aten::t], key=[AutogradCPU]
> >      [redispatch] op=[aten::t], key=[ADInplaceOrView]
> >       [redispatch] op=[aten::t], key=[Python] -> torch._ops.aten t.default
> >        [callBoxed] op=[aten::t], key=[CPU]
> >         [call] op=[aten::transpose.int], key=[CPU]
> >          [call] op=[aten::as_strided], key=[CPU]
> >    [call] op=[aten::matmul], key=[PythonTLSSnapshot]
> >     [redispatchBoxed] op=[aten::matmul], key=[AutogradCPU]
> >      [call] op=[aten::reshape], key=[PythonTLSSnapshot]
> >       [redispatchBoxed] op=[aten::reshape], key=[AutogradCPU]
> >        [call] op=[aten::view], key=[PythonTLSSnapshot]
> >         [redispatchBoxed] op=[aten::view], key=[AutogradCPU]
> >          [redispatch] op=[aten::view], key=[ADInplaceOrView]
> >           [redispatch] op=[aten::view], key=[Python] -> torch._ops.aten view.default
> >            [callBoxed] op=[aten::view], key=[CPU]
> >      [call] op=[aten::mm], key=[PythonTLSSnapshot]
> >       [redispatchBoxed] op=[aten::mm], key=[AutogradCPU]
> >        [redispatch] op=[aten::mm], key=[Python] -> torch._ops.aten mm.default
> >         [callBoxed] op=[aten::mm], key=[CPU]
> >          [call] op=[aten::resolve_conj], key=[CPU]
> >          [call] op=[aten::resolve_conj], key=[CPU]
> >      [call] op=[aten::_unsafe_view], key=[PythonTLSSnapshot]
> >       [redispatchBoxed] op=[aten::_unsafe_view], key=[AutogradCPU]
> >        [redispatch] op=[aten::_unsafe_view], key=[Python] -> torch._ops.aten _unsafe_view.default
> >         [callBoxed] op=[aten::_unsafe_view], key=[CPU]
> > ```
> 
> @FFFrog I have a question. Could you tell me how this call stack is printed out?

First, compile the PyTorch with DEBUG, then export TORCH_SHOW_DISPATCH_TRACE=1.
