### ISSUE TITLE
Implement `is_leaf` for tree_map

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#116068]
I notice that jax's tree_map has an [is_leaf parameter](https://jax.readthedocs.io/en/latest/_autosummary/jax.tree_util.tree_map.html) which would come in handy for something I'm currently doing. Would be nice to get it implemented in our pytree utils.

cc @zou3519 @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by FFFrog** [comment]
Resolved by https://github.com/pytorch/pytorch/pull/116419#event-11434819436
