### ISSUE TITLE
torch.compile (dynamo) holds on to tensors, even if no frame is compiled

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#116143]
### 🐛 Describe the bug

    def test_static_address_finalizer(self):
        def inner(y):
            y

        inner = torch._dynamo.optimize("eager")(inner)

        p_ref = None

        x = torch.randn((10, 10), device="cuda:0")
        inner(x)

        p_ref = weakref.ref(x)
        self.assertTrue(p_ref() is not None)
        del x
        gc.collect()
        self.assertTrue(p_ref() is None)
        
This fails - removing the compile line makes it pass

### Versions

main

cc @ezyang @gchanan @zou3519 @kadeng @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

**Comment by awgu** [comment]
FWIW, when I run this on commit 39f16c221e03242516d08bf8c12dabd327d33646 from Tue Nov 28 18:32:05 2023 +0000, this seems to pass:
```
import gc
import weakref

import torch

def test_static_address_finalizer():
    def inner(y):
        y

    inner = torch._dynamo.optimize("eager")(inner)

    p_ref = None

    x = torch.randn((10, 10), device="cuda:0")
    inner(x)

    p_ref = weakref.ref(x)
    assert p_ref() is not None
    del x
    gc.collect()
    assert p_ref() is None
    print("Success!")

test_static_address_finalizer()
```

**Comment by voznesenskym** [comment]
https://github.com/pytorch/pytorch/pull/116169

**Comment by voznesenskym** [comment]
> FWIW, when I run this on commit [39f16c2](https://github.com/pytorch/pytorch/commit/39f16c221e03242516d08bf8c12dabd327d33646) from Tue Nov 28 18:32:05 2023 +0000, this seems to pass:
> 
> ```
> import gc
> import weakref
> 
> import torch
> 
> def test_static_address_finalizer():
>     def inner(y):
>         y
> 
>     inner = torch._dynamo.optimize("eager")(inner)
> 
>     p_ref = None
> 
>     x = torch.randn((10, 10), device="cuda:0")
>     inner(x)
> 
>     p_ref = weakref.ref(x)
>     assert p_ref() is not None
>     del x
>     gc.collect()
>     assert p_ref() is None
>     print("Success!")
> 
> test_static_address_finalizer()
> ```

The gc collect should be commented out, sorry
