### ISSUE TITLE
torch.nn.Transformer.generate_square_subsequent_mask gives nans instead of zeros when running on mps

### ISSUE THREAD

**Issue by gailweiss** [pytorch/pytorch#116170]
### 🐛 Describe the bug

`generate_square_subsequent_mask` has different behaviour on mac when using mps vs cpu, and I think the mps behaviour is the unexpected one. 

Simple example below: you would expect `a`, `b`, and `c` to differ only by devices, but `b` has nans which `a` and `c` don't. Also, moving `a` to the mps device doesnt generate something identical to `b`.

I assume this is a bug, not urgent but probably wants a fix (for now I am using `c` instead of `b` as my workaround).

```
>>> import torch
>>> a = torch.nn.Transformer.generate_square_subsequent_mask(3)
>>> b = torch.nn.Transformer.generate_square_subsequent_mask(3,device='mps')
>>> c = a.to(device='mps')
>>> a
tensor([[0., -inf, -inf],
        [0., 0., -inf],
        [0., 0., 0.]])
>>> b
tensor([[nan, -inf, -inf],
        [nan, nan, -inf],
        [nan, nan, nan]], device='mps:0')
>>> c
tensor([[0., -inf, -inf],
        [0., 0., -inf],
        [0., 0., 0.]], device='mps:0')
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.6 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.6-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] pytorch-lightning==2.0.3
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.16.0
[conda] numpy                     1.26.0          py311he598dae_0  
[conda] numpy-base                1.26.0          py311hfbfe69c_0  
[conda] pytorch                   2.1.0                  py3.11_0    pytorch
[conda] pytorch-lightning         2.0.3           py311hca03da5_0  
[conda] torchaudio                2.1.0                 py311_cpu    pytorch
[conda] torchmetrics              0.11.4          py311hb6e6a13_1  
[conda] torchvision               0.16.0                py311_cpu    pytorch

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by spzala** [comment]
I could reproduce the issue. After some debugging, I found that the underlying problem here is with `torch.triu` - same as discussed in more details in this issue https://github.com/pytorch/pytorch/issues/100005

**Comment by hvaara** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/128575.

On nightly
```python
import torch
a = torch.nn.Transformer.generate_square_subsequent_mask(3)
b = torch.nn.Transformer.generate_square_subsequent_mask(3,device='mps')
c = a.to(device='mps')
a == b.to('cpu')
```
yields
```
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
```

xref #128429

**Comment by hvaara** [comment]
Current test cases are probably sufficient (ref https://github.com/pytorch/pytorch/issues/100005#issuecomment-2322060071)

Closing this, but please reopen if there are items left to address.

@pytorchbot close
