### ISSUE TITLE
ONNX importing

### ISSUE THREAD

**Issue by linzhiqiu** [pytorch/pytorch#11627]
Has anyone tried to write a parser to import an ONNX file as a PyTorch Module?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by garymm** [comment]
Nobody is working on this AFAIK. If you'd like to start it, I suggest you communicate with people in the ONNX community via Slack or attending a meeting: https://onnx.ai/
