### ISSUE TITLE
random_ not working on cuda

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#1162]
The first line is working, the second one, on GPU, returns an error

```python
torch.FloatTensor(3, 4).random_(2)
torch.FloatTensor(3, 4).cuda().random_(2)
```

```
AttributeError: 'FloatTensor' object has no attribute 'random_'
```

**Comment by albanD** [comment]
It is expected as this function is not implemented in cuda.

**Comment by soumith** [comment]
duplicate of https://github.com/pytorch/pytorch/issues/712
