### ISSUE TITLE
torch.compile(fullgraph=True): can't pass lambdas to hooks? 

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#116220]
```py
import torch
v = torch.tensor([0., 0., 0.], requires_grad=True)

@torch.compile(backend="aot_eager", fullgraph=True)
def f(v):
    lr = 0.01
    #    simulate a simple SGD update
    h = v.register_hook(lambda p: p.add_(p.grad, alpha=-lr))
    
    return v.clone(), h

print(v)
k, h = f(v)
v.backward(torch.tensor([1., 2., 3.]))
print(v)
```
raises `Unsupported: Unexpected callable type passed to register_hook`

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @bdhirsh @aakhundov

**Comment by masnesral** [comment]
I believe this is fixed. I get the same (new) error with and without torch.compile:
`TypeError: add_(): argument 'other' (position 1) must be Tensor, not NoneType`

But if I change to: 
`h = v.register_hook(lambda p: p.add_(p, alpha=-lr))`

The script runs fine without an `Unexpected callable type passed to register_hook`
