### ISSUE TITLE
Trunk is very red, let's pause everything except fixing it

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#116273]
**MERGE BLOCKING** 

## Current Status
Multiple failing workflows with different errors and reasons

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
https://github.com/pytorch/pytorch/pull/115188 got reverted, but it's PRs on top of the stack wasn't

## Mitigation
Reverted https://github.com/pytorch/pytorch/pull/115210

## Prevention/followups
*How do we prevent issues like this in the future?*

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Remove `ci:sev` as issue is mitigated, but adding `triage review` to talk about it a bit

**Comment by malfet** [comment]
Quick discussion points:
 - We should either restrict who can do reverts (author + oncall + module maintainers)
 - Expect that reverts should not be done at the end of ones workday and one should keep an eye on the trunk health 30 min after revert have happened.
