### ISSUE TITLE
Incorrect results for SVD when computed in multiple CUDA envs using 1.13.0+cu116 (windows11),  or torch 2.1.0+cu118 (Ubuntu20.04) ...

### ISSUE THREAD

**Issue by XiaoXiao-Woo** [pytorch/pytorch#116394]
### 🐛 Describe the bug

```python
import numpy as np
import torch
print(torch.__version__)
A = np.array([[0.7944, 0.6003], [0.6003, 0.6311]])
U, S, V = np.linalg.svd(A)
print("numpy: U: ")
print(U)
print(U@np.diag(S)@V)


U, S, V = torch.svd(torch.from_numpy(A))
print("torch_cpu U: ")
print(U)
print(U@torch.diag(S)@V)


U, S, V = torch.svd(torch.from_numpy(A).cuda())
print("torch_cuda U: ")
print(U)
print(U@torch.diag(S)@V)
```

![image](https://github.com/pytorch/pytorch/assets/15083102/9813ba8a-1e5d-4def-bbc3-23ee8940989d)

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: 11.0.0
CMake version: version 3.22.0-rc1
Libc version: N/A

Python version: 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: 11.6.55
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Ti Laptop GPU
Nvidia driver version: 536.67
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:










Revision=20480

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] onnxruntime-gpu==1.11.0
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.13.0+cu116
[pip3] torchaudio==0.12.1+cu116
[pip3] torchmin==0.0.2
[pip3] torchvision==0.13.1+cu116
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     1.13.0+cu116             pypi_0    pypi
[conda] torchaudio                0.12.1+cu116             pypi_0    pypi
[conda] torchmin                  0.0.2                     dev_0    <develop>
[conda] torchvision               0.13.1+cu116             pypi_0    pypi
```

**Comment by lezcano** [comment]
You are missing to transpose the `V` when computing the product. Using `torch.linalg.svd` which returns `V^H` you get the correct results.

**Comment by XiaoXiao-Woo** [comment]
> You are missing to transpose the `V` when computing the product. Using `torch.linalg.svd` which returns `V^H` you get the correct results.

It is not because I use the A as symmetric matrix， where Vh=Vh.T.

**Comment by lezcano** [comment]
If A is symmetric you get that `U = V`, in other words, you can compute the svd via the `eigh` decomposition.
The only matrices that are orthogonal and symmetric are matrices that have 1's and -1's as eigenvalues. That's too restrictive to ask for an SVD decompostiion.

**Comment by XiaoXiao-Woo** [comment]
> If A is symmetric you get that , in other words, you can compute the svd via the decomposition. The only matrices that are orthogonal and symmetric are matrices that have 1's and -1's as eigenvalues. That's too restrictive to ask for an SVD decompostiion.`U = V``eigh`

Please see results computed in pytorch cpu, that's no problem. I doubt that the it is the cusolver issue.

**Comment by lezcano** [comment]
Even more, the U and the V are not uniquely determined. You can multiply any of their columns by -1 (both that of U and V) and you'll get a valid singular vector. As such, it does not make sense to expect U or V to be symmetric, as it's a concept that is not well defined on them.

Take your code and compute `U @ diag(S) @ V.mH` and you'll see that you get the correct result. Even better, use `torch.linalg.svd` as `torch.svd` is slower and has been deprecated in the docs for about two years.

**Comment by XiaoXiao-Woo** [comment]
Thanks for your advice.  Results become correct when using the torch.linalg.svd.

**Comment by XiaoXiao-Woo** [comment]
@lezcano. hi, I have another problem: it is necessary for me to determine the signs of U or Vh for a two-order matrix. In my work, projection requires absolute signs instead of multiplying any -1. Signs of U or Vh in the torch_cpu are suitable. So, do you have any suggestions to help me?

**Comment by lezcano** [comment]
Please post this sort of questions in the forums: https://discuss.pytorch.org/
