### ISSUE TITLE
RuntimeError with load_sp_model("m_user.model")

### ISSUE THREAD

**Issue by km5ar** [pytorch/pytorch#116340]
### 📚 The doc issue

I'm trying to run the code from: https://pytorch.org/text/stable/data_functional.html

```
from torchtext.data.functional import load_sp_model

sp_model = load_sp_model("m_user.model")
sp_model = load_sp_model(open("m_user.model", 'rb'))

```

pytorch version: 2.1.2

but getting a RuntimeError
<img width="802" alt="iShot2023-12-22_17 58 30" src="https://github.com/pytorch/pytorch/assets/54015474/6c8df7b9-eeb8-47b5-8d36-3bafc7f2b82b">

**Comment by jbschlosser** [comment]
Hi, thanks for reporting this! Do you mind opening an issue on the https://github.com/pytorch/text repo? Closing the issue here in favor of that.
