### ISSUE TITLE
`.contiguous()` doesn't work with one non-singleton dimension

### ISSUE THREAD

**Issue by sfc-gh-mturski** [pytorch/pytorch#116333]
### 🐛 Describe the bug

When I call `.contiguous()` on a tensor with one non-singleton dimension, it doesn't change stride, for instance:
```
>> import torch
>> torch.tensor([[0, 1]]).transpose(1, 0).contiguous().stride()
(1, 2)
```
Because of that `scaled_dot_product_attention` with fast attention/memory efficient attention doesn't work (as it expects `.stride()[-] == 1` for all of the input tensors, but I believe `contiguous()`should be fixed, not `scaled_dot_product_attention`.

### Versions

Problem occurs both on Linux and MacOS. I've reproduced it on releases `2.0.1` and `2.1.2`.

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.2 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 (main, Mar  1 2023, 12:20:14) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] flake8==4.0.1
[pip3] flake8-2020==1.6.1
[pip3] flake8-absolute-import==1.0.0.1
[pip3] flake8-assertive==1.3.0
[pip3] flake8-bandit==3.0.0
[pip3] flake8-black==0.3.6
[pip3] flake8-bugbear==21.4.3
[pip3] flake8-builtins==1.5.3
[pip3] flake8-codeclimate==0.3.0
[pip3] flake8-cognitive-complexity==0.1.0
[pip3] flake8-comprehensions==3.10.1
[pip3] flake8-docstrings==1.6.0
[pip3] flake8-eradicate==1.3.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-fixme==1.1.1
[pip3] flake8-gl-codeclimate==0.1.6
[pip3] flake8-isort==4.2.0
[pip3] flake8-mutable==1.2.0
[pip3] flake8-plugin-utils==1.3.2
[pip3] flake8-polyfill==1.0.2
[pip3] flake8-print==4.0.1
[pip3] flake8-pytest-style==1.4.4
[pip3] flake8-quotes==3.2.0
[pip3] flake8-requirements==1.4.0
[pip3] flake8-simplify==0.14.6
[pip3] flake8-tuple==0.4.1
[pip3] flake8-use-fstring==1.4
[pip3] mypy==0.982
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] numpydoc==1.5.0
[pip3] pytorch-lightning==1.7.7
[pip3] torch==2.0.1
[pip3] torch-tb-profiler==0.4.3
[pip3] torchdata==0.6.1
[pip3] torchmetrics==0.10.3
[pip3] torchvision==0.15.2
[conda] numpy                     1.23.5          py310hb93e574_0
[conda] numpy-base                1.23.5          py310haf87e8b_0
[conda] numpydoc                  1.5.0           py310hca03da5_0
[conda] pytorch-lightning         1.7.7                    pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchdata                 0.6.1                    pypi_0    pypi
[conda] torchmetrics              0.10.3                   pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

cc @ezyang @gchanan @zou3519 @kadeng @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by LamForest** [comment]
I can reproduce this bug. Is anyone looking into this issue? If not, I'll take a look.

**Comment by LamForest** [comment]
```python
b = torch.tensor([[0, 1]]).transpose(1, 0)
b.is_contiguous() #True
```
Although b.stride() is (2,1), b.is_contiguous() returns True because of singleton dimension. Therefore, b.contiguous() returns directly, doing nothing. In my opinion, it is an expected behaviour not a bug. 


Can you please give a minimal reproducible test for scaled_dot_product_attention?  @sfc-gh-mturski

**Comment by sfc-gh-mturski** [comment]
Thank you for the response!

In my opinion it's a bug because documentations says:
> torch.contiguous_format: Tensor is or will be allocated in dense non-overlapping memory. Strides represented by **values in decreasing order**.

and `.contiguous(memory_format=torch.contiguous_format)` doesn't act as described:
``` python
import torch
a = torch.tensor([[0, 1]]).transpose(1, 0).contiguous(memory_format=torch.contiguous_format).stride()
print(a)  # (1, 2)
```
At least documentation should be updated.


Minimal reproducible example for scaled_dot_product_attention:
```python
import torch
from torch.nn.functional import scaled_dot_product_attention

query = torch.tensor([[[[1, 2]]]], dtype=torch.float32)
query = query.transpose(-1, -2)
key = torch.tensor([[[[1]]]], dtype=torch.float32)
value = torch.tensor([[[[1]]]], dtype=torch.float32)

with torch.backends.cuda.sdp_kernel(enable_math=True, enable_flash=False, enable_mem_efficient=False):
    scaled_dot_product_attention(query, key, value)  # Works just fine

with torch.backends.cuda.sdp_kernel(enable_math=False, enable_flash=True, enable_mem_efficient=True):
    scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
```
```
/Users/mturski/Projects/tilt-lm/scripts/contigious.py:13: UserWarning: Flash attention kernel not used because: (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/transformers/sdp_utils_cpp.cpp:101.)
  scaled_dot_product_attention(query, key, value)
/Users/mturski/Projects/tilt-lm/scripts/contigious.py:13: UserWarning: Both fused kernels require the last dimension of the input to have stride 1. Got Query.stride(-1): 2, Key.stride(-1): 1, Value.stride(-1): 1 instead. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/transformers/sdp_utils_cpp.h:412.)
  scaled_dot_product_attention(query, key, value)
Traceback (most recent call last):
  File "/Users/mturski/anaconda3/envs/tilt-lm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/mturski/anaconda3/envs/tilt-lm/lib/python3.10/site-packages/torch/backends/cuda/__init__.py", line 290, in sdp_kernel
    yield {}
  File "/Users/mturski/Projects/tilt-lm/scripts/contigious.py", line 13, in <module>
    scaled_dot_product_attention(query, key, value)
RuntimeError: No available kernel.  Aborting execution.
```

**Comment by LamForest** [comment]
@sfc-gh-mturski  Hi~ First of all, I do not know the reason why you disable math kernel. It is a fallback kernel for  scaled_dot_product_attention. 

---

For your problem, I think there are 2 possible ways to fix this:
1. refine the behavior of is_contiguous() on singleton dimension:
torch.tensor([[0, 1]]).transpose(1, 0).is_contiguous() should be False not True.

2. relax the constraint of flash attention.

Does anyone else have any thoughts on this?

**Comment by ezyang** [comment]
Flash attention should just relax its constraint, IMO.

**Comment by sfc-gh-mturski** [comment]
@LamForest I use `scaled_dot_product_attention` to benefit from better performance of flash attention. In one of my tests I disabled fallback to flash attention to verify if flash attention is called, and as shown above it isn't. As you asked, I provided minimal reproducible example of faulty behaviour (so that's not my original code, it's just a minimal reproducible example).

**Comment by drisspg** [comment]
There are a few things going on here, I think the most important is that flash_attention kernel does not support a trailing (head_dimension) of size not a multiple of 8. The way that this is supported today is by padding the last dimension to the nearest multiple of one of the supported size, in this case 8.

The problem is that this padding is happening after we check that you can run flash-attention since there are other checks besides just the trailing dimension stride.  I think that the best solution here would be to update the check to not run if the last dim is of size==1.

A quicker workaround would be to to do the manual "contigufication"

```Python
new_a = torch.empty(a.shape).copy_(a)
```

**Comment by sfc-gh-wjaskowski** [comment]
And what about the documentation of `contiguous`? As @sfc-gh-mturski  mentioned, the following statement is still false, in general. 

> torch.contiguous_format: Tensor is or will be allocated in dense non-overlapping memory. Strides are represented by values in **decreasing order.**

**Comment by abdulfatir** [comment]
@drisspg looks like this was only fixed for the flash attention kernel but this is also an issue for the memory-efficient kernel. 

```py
import torch
from torch.nn.functional import scaled_dot_product_attention

query = torch.tensor([[[[1, 2]]]], dtype=torch.float32)
query = query.transpose(-1, -2).to("cuda")
key = torch.tensor([[[[1]]]], dtype=torch.float32).to("cuda")
value = torch.tensor([[[[1]]]], dtype=torch.float32).to("cuda")

with torch.backends.cuda.sdp_kernel(
    enable_math=True, enable_flash=False, enable_mem_efficient=False
):
    scaled_dot_product_attention(query, key, value)  # Works just fine

with torch.backends.cuda.sdp_kernel(
    enable_math=False, enable_flash=False, enable_mem_efficient=True
):
    scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
```

```
/tmp/ipykernel_1052029/3955578338.py:17: UserWarning: Memory efficient kernel not used because: (Triggered internally at ../aten/src/ATen/native/transformers/cuda/sdp_utils.cpp:415.)
  scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
/tmp/ipykernel_1052029/3955578338.py:17: UserWarning: Both fused kernels require the last dimension of the input to have stride 1. Got Query.stride(-1): 2, Key.stride(-1): 1, Value.stride(-1): 1 instead. (Triggered internally at ../aten/src/ATen/native/transformers/sdp_utils_cpp.h:423.)
  scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below

RuntimeError                              Traceback (most recent call last)
Cell In[13], line 17
     12     scaled_dot_product_attention(query, key, value)  # Works just fine
     14 with torch.backends.cuda.sdp_kernel(
     15     enable_math=False, enable_flash=False, enable_mem_efficient=True
     16 ):
---> 17     scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
```
