### ISSUE TITLE
RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'/time_proj/Mul' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:540 void onnxruntime::BroadcastIterator::Init(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 2 by 160

### ISSUE THREAD

**Issue by siddharth062022** [pytorch/pytorch#116386]
### 🐛 Describe the bug

RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'/time_proj/Mul' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:540 void onnxruntime::BroadcastIterator::Init(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 2 by 160

### Versions

torch                            2.1.2
onnx                             1.15.0
onnxruntime                      1.16.3

**Comment by jbschlosser** [comment]
Hey @siddharth062022, if possible could you please provide a small example that reproduces the error you're seeing? It's very difficult to debug or provide a fix without this.

**Comment by siddharth062022** [comment]
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("echarlaix/stable-diffusion-v1-5-inc-int8-dynamic").to("cpu")

# for reducing memory consumption get all components from pipeline independently
text_encoder = pipe.text_encoder
text_encoder.eval()
unet = pipe.unet
unet.eval()
vae = pipe.vae
vae.eval()

conf = pipe.scheduler.config

del pipe

try to export as onnx 
import numpy as np


UNET_ONNX_PATH = sd2_1_model_dir / 'unet/unet.onnx'
UNET_OV_PATH = UNET_ONNX_PATH.parents[1] / 'unet.xml'


def convert_unet_onnx(unet:torch.nn.Module, onnx_path:Path, num_channels:int = 4, width:int = 1, height:int = 1):
    """
    Convert Unet model to ONNX, then IR format.
    Function accepts pipeline, prepares example inputs for ONNX conversion via torch.export,
    Parameters:
        unet (torch.nn.Module): UNet PyTorch model
        onnx_path (Path): File for storing onnx model
        num_channels (int, optional, 4): number of input channels
        width (int, optional, 64): input width
        height (int, optional, 64): input height
    Returns:
        None
    """
    if not onnx_path.exists():
        # prepare inputs
        encoder_hidden_state = torch.ones((2, 77, 1024))
        latents_shape = (2, num_channels, width, height)
        latents = torch.randn(latents_shape)
        t = torch.from_numpy(np.array(1, dtype=np.float32))

        # model size > 2Gb, it will be represented as onnx with external data files, we will store it in separated directory for avoid a lot of files in current directory
        onnx_path.parent.mkdir(exist_ok=True, parents=True)
        unet.eval()

        with torch.no_grad():
            torch.onnx.export(
                unet,
                (latents, t, encoder_hidden_state),
                str(onnx_path),
                input_names=['latent_model_input', 't', 'encoder_hidden_states'],
                output_names=['out_sample'],
                #use_external_data_format=True,

                #onnx_shape_inference=False,

            )
        print('U-Net successfully converted to ONNX')


if not UNET_OV_PATH.exists():
    convert_unet_onnx(unet, UNET_ONNX_PATH, width=96, height=96)
    #del unet
    gc.collect()
    !mo --input_model $UNET_ONNX_PATH --output_dir $sd2_1_model_dir
    print('U-Net successfully converted to IR')
else:
    #del unet
    print(f"U-Net will be loaded from {UNET_OV_PATH}")
gc.collect();


then try to qunatize the unet but 
import gc
import onnx
import torch
import numpy as np
import onnxruntime
from onnxruntime.quantization import quantize_static, CalibrationDataReader, QuantType, CalibrationMethod, QuantFormat


# Define a custom CalibrationDataReader class
class UNetDataReader(CalibrationDataReader):
    def __init__(self, model_path: str):
        self.model_path = model_path
        self.input_names = None
        self.enum_data = None
        self.load_model()
        self.generate_calibration_data()

    def load_model(self):
        # Load the ONNX model and get the input tensor names
        #session = onnxruntime.InferenceSession(self.model_path, providers=['CPUExecutionProvider'])
        #self.input_names = [input.name for input in session.get_inputs()]
        sess_opt = onnxruntime.SessionOptions()
        sess_opt.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_BASIC
        session = onnxruntime.InferenceSession(self.model_path, sess_options=sess_opt, providers=['CPUExecutionProvider'])
        self.input_names = [input.name for input in session.get_inputs()]



    def generate_calibration_data(self):
        # Generate random NHWC data for calibration with the correct input names
        self.calibration_data = {
            #'latent_model_input': torch.randn(2, 4, 96, 96).numpy().astype(np.float32),  # Change to float32
            #'t': np.array([1], dtype=np.float32),  # Change to float32
            #'encoder_hidden_states': np.random.rand(2, 77, 1024).astype(np.float32),  # Change to float32
            'latent_model_input': torch.randn(2, 4, 96, 96,).numpy().astype(np.float32),  # Change to float32
            't': np.array([2], dtype=np.float32),  # Change to float32
            'encoder_hidden_states': np.random.rand(2, 77, 1024).astype(np.float32),  # Change to float32
        }

        self.datasize = len(self.calibration_data)

    def get_next(self):
        if self.enum_data is None:
            self.enum_data = iter([self.calibration_data])
        return next(self.enum_data, None)

    def rewind(self):
        self.enum_data = None

# Define paths for the input and quantized models
model_path = '/content/sd2.1/unet/unet.onnx'
#model_path = '/content/unet_fp16.onnx'
#model_path = '/content/sd2.12/unet1/unet.onnx'
quantized_model_path = '/content/unetint8/unet.onnx'

# Create a calibration data reader
data_reader = UNetDataReader(model_path)
gc.collect()
# Perform static quantization
quantize_static(
    model_input=model_path,
    model_output=quantized_model_path,
    calibration_data_reader=data_reader,
    activation_type=QuantType.QInt8,
    weight_type=QuantType.QInt8,
    use_external_data_format=True,
    calibrate_method=CalibrationMethod.MinMax,
    quant_format=QuantFormat.QDQ,



)
gc.collect()

RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'/time_proj/Mul' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:540 void onnxruntime::BroadcastIterator::Init(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 2 by 160

**Comment by siddharth062022** [comment]
i am try to qunatize unet2dconditional model

**Comment by justinchuby** [comment]
Please consider trying the new dynamo exporter (`torch.onnx.dynamo_export`) to see if it succeeds. Be sure to use the latest PyTorch and ONNX versions: https://pytorch.org/docs/stable/onnx_dynamo.html

**Comment by siddharth062022** [comment]
OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues[](url)

**Comment by siddharth062022** [comment]
nothing see in sarif viewer when i load the file.

**Comment by justinchuby** [comment]
So you have the full error stack?

**Comment by siddharth062022** [comment]
when i use torch.onnx.export or torch.onnx._export no error but in dynmo_export getting error

**Comment by justinchuby** [comment]
Please provide the full error messages with code stack to help diagnose the issue

**Comment by siddharth062022** [comment]
RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'/time_proj/Mul' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:540 void onnxruntime::BroadcastIterator::Init(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 2 by 160 #116386
i have tried to qunatization in onnx after importing file from pytorch but getting this type of issue code is available above after some one suggest me to use dynmo function to export then still getting issue if you want i can give you .ipynb file and requirements file to fix this issue.

**Comment by siddharth062022** [comment]
OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues when i use dynmo.export this issue gets

**Comment by siddharth062022** [comment]
[unet.TXT](https://github.com/pytorch/pytorch/files/13807607/unet.TXT)
[requirements.txt](https://github.com/pytorch/pytorch/files/13807611/requirements.txt)

**Comment by justinchuby** [comment]
> OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues when i use dynmo.export this issue gets

There should be more output than this. Can you provide the full stack of error messages?

**Comment by siddharth062022** [comment]
{
 "runs":[
  {
   "tool":{
    "driver":{
     "name":"torch.onnx.dynamo_export",
     "contents":[
      "localizedData",
      "nonLocalizedData"
     ],
     "language":"en-US",
     "rules":[],
     "version":"2.1.0+cu121"
    }
   },
   "language":"en-US",
   "newlineSequences":[
    "\r\n",
    "\n"
   ],
   "results":[]
  }
 ],
 "version":"2.1.0",
 "schemaUri":"https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/schemas/sarif-schema-2.1.0.json"
}

**Comment by justinchuby** [comment]
This is an empty file.

**Comment by siddharth062022** [comment]
Yes get an empty file That's why I am saying

**Comment by siddharth062022** [comment]
I give the unet.text and requirements file if you run the code and may figure out where the problem is.

**Comment by siddharth062022** [comment]
@justinchuby  can you send me your email so I can send you the code and try to solve the problem?

**Comment by siddharth062022** [comment]
I have solved this problem myself. If any have this issue massage me.

**Comment by 1215thebqtic** [comment]
> I have solved this problem myself. If any have this issue massage me.

Can I know how do you solve this problem? I have a similar problem.

**Comment by siddharth062022** [comment]
@1215thebqtic you have to check the opset version onnx version or onnx runtime version 
https://onnxruntime.ai/docs/reference/compatibility.html Check the version of onnx and onnx runtime and install a particular version then solve it.

**Comment by KossBoii** [comment]
@siddharth062022 I also face kinda similar issue when I'm trying to export the MultiConditionUnet to onnx. Can you elaborate the solution a bit more?
`onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/down_blocks.0/char.0/transformer_blocks.0/Add_1' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 224 by 784`

**Comment by siddharth062022** [comment]
It is a version control issue so you have to choose correct onnx version which support onnxruntime version and opset above I shared a link where you can check.

**Comment by KossBoii** [comment]
> It is a version control issue so you have to choose correct onnx version which support onnxruntime version and opset above I shared a link where you can check.

What opset, onnx version, onnxruntime did you end up using?
