### ISSUE TITLE
type_as not working on Variable

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#1163]
Reported by Arthur Szlam

**Comment by apaszke** [comment]
`type` seems to be ok, but `type_as` appears to be not implemented

**Comment by soumith** [comment]
`type` exists, but has the following issue:

```
a = Variable(...)
a.type(torch.FloatTensor) # doesn't work
a.type(Variable(torch.FloatTensor.new())) # works
```

That's the broken case.
