### ISSUE TITLE
`gpt2-medium` on `mps` device: Ok with 1023 input tokens. Wrong with 1024 input tokens.

### ISSUE THREAD

**Issue by trianxy** [pytorch/pytorch#116331]
### 🐛 Describe the bug

When running inference and the following 3 conditions are met

1. use transformers' `gpt2-medium` model
2. use `mps` backend on a Macbook M1
3. use input_ids shape `(1, 1024)` (i.e. batch size `1` and maximum context length)

then I get wrong output. Interestingly, this problem does NOT appear if any of the above conditions is not fulfilled.

To better illustrate this, I am adding some code below which shows that the predictions of the first few tokens (which should NOT change, no matter if we input 1023 or 1024 tokens) change when using `gpt2-medium`.

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

def run(architecture: str, context_length: int, batch_size) -> None:
    model = AutoModelForCausalLM.from_pretrained(architecture)
    model = model.eval().to("mps")

    input_ids = torch.zeros((batch_size, context_length), dtype=torch.int64)
    input_ids = input_ids.to(model.device)

    with torch.inference_mode():
        output = model(input_ids)

    print(f"Model predictions for first few tokens for {input_ids.shape=}:")
    for pos in range(3):
        token_id = torch.argmax(output.logits[0, pos]).item()
        logit = output.logits[0, pos, token_id].item()
        print(f" {pos}: {token_id=:>4} ({logit=:>9.2f})")

# BASELINE
run("gpt2-medium", context_length=1023, batch_size=1)  
# Model predictions for first few tokens for input_ids.shape=torch.Size([1, 1023]):
# 0: token_id= 198 (logit=   -46.95)
# 1: token_id= 198 (logit=   -43.56)
# 2: token_id=   0 (logit=   -20.67)

# CORRECT PREDICTIONS (SAME LIKE BEFORE)
run("gpt2-medium", context_length=1024, batch_size=2)
# Model predictions for first few tokens for input_ids.shape=torch.Size([2, 1024]):
#  0: token_id= 198 (logit=   -46.95)
#  1: token_id= 198 (logit=   -43.56)
#  2: token_id=   0 (logit=   -20.67)

# WRONG PREDICTIONS (DIFFERENT THAN BEFORE)
run("gpt2-medium", context_length=1024, batch_size=1)
# Model predictions for first few tokens for input_ids.shape=torch.Size([1, 1024]):
# 0: token_id=16706 (logit=   -25.97)
# 1: token_id= 198 (logit=   -46.95)
# 2: token_id= 198 (logit=   -51.52)
```

Any insights into how we could fix that problem and whether this could also appear in other situations/models?

### Versions

Collecting environment information...
PyTorch version: 2.1.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.2.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-14.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.1.2
[pip3] torchinfo==1.8.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kadeng @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by tringwald** [comment]
I can partially reproduce this on an M1 Mac Mini, although my results are different:
```
Model predictions for first few tokens for input_ids.shape=torch.Size([1, 1023]):
 0: token_id= 198 (logit=   -46.95)
 1: token_id= 198 (logit=   -43.56)
 2: token_id=   0 (logit=   -20.67)
Model predictions for first few tokens for input_ids.shape=torch.Size([2, 1024]):
 0: token_id=40517 (logit=     2.19)
 1: token_id=28467 (logit=     1.49)
 2: token_id=33392 (logit=     1.81)
Model predictions for first few tokens for input_ids.shape=torch.Size([1, 1024]):
 0: token_id=16706 (logit=   -25.97)
 1: token_id= 198 (logit=   -46.95)
 2: token_id= 198 (logit=   -51.52)
```

I was able to fix the last setup by modifying the [`Conv1D` layer](https://huggingface.co/transformers/v4.8.2/_modules/transformers/modeling_utils.html) of `transformers`, 

```python3
# Replace this
# x = torch.addmm(self.bias, x.view(-1, x.size(-1)), self.weight)
# with:
x = x.view(-1, x.size(-1)) @ self.weight + self.bias
```

but there is some other underlying issue that needs further investigation.

**Comment by malfet** [comment]
Interesting. I remember I've seen an issue that MPSes torch.mm produces wrong results for some matrix sizes, but can't find one right now...

**Comment by malfet** [comment]
This is downright wrong and causes all this weirdness (and as  https://github.com/pytorch/pytorch/pull/77462 suggests that eliminated it for `mm` and `bmm`) not needed:
https://github.com/pytorch/pytorch/blob/de4d48df34c0e8bcd03d96bcdfd12e263e9889ff/aten/src/ATen/native/mps/operations/LinearAlgebra.mm#L85-L90
