### ISSUE TITLE
Batched Sparse Matrix - Batched Sparse Matrix multiplication

### ISSUE THREAD

**Issue by iminfine** [pytorch/pytorch#116364]
### 🚀 The feature, motivation and pitch

I am currently engaged in the development of a novel cross-attention mechanism for transformers. In this context, consider the shape of q and k as (b, n, l, d), where b represents the batch number, n denotes the head number, l signifies the sequence length, and d stands for the feature dimensions.

The code mechanism employed to compute attention involves the application of the F.relu activation function to both q and k, followed by reshaping operations. Specifically, it can be expressed as follows:

F.relu(q).reshape(b, n * l, d) @ F.relu(k).reshape(b, n * l, d)

However, the reshape operation results in the multiplication of two large matrices, incurring a substantial GPU memory cost. This presents a notable drawback in terms of computational efficiency and resource utilization.

The aforementioned attention function can be conceptualized as the multiplication between two sparse matrices, considering the involvement of the ReLU function. To address the memory issue, I am seeking to leverage the Batched Sparse Matrix - Batched Sparse Matrix multiplication feature. This enhancement would optimize the computation and alleviate the strain on GPU memory, making the implementation more efficient and scalable.

```[tasklist]
### Tasks
```

**Comment by jbschlosser** [comment]
Hi @iminfine, thanks for the request! I'll point you to what I believe is a duplicate #72065, but feel free to reopen if your needs aren't covered by the discussion in that thread. Thanks!
