### ISSUE TITLE
NotImplementedError: The operator 'aten::_fft_r2c' is not currently implemented for the MPS device.

### ISSUE THREAD

**Issue by pradeepkr1003** [pytorch/pytorch#116392]
+1 

NotImplementedError: The operator 'aten::_fft_r2c' is not currently implemented for the MPS device.

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by malfet** [comment]
Closing as duplicate of https://github.com/pytorch/pytorch/issues/78044 will try to push change soon
