### ISSUE TITLE
TransformerEncoderLayer raise `AttributeError: 'NoneType' object has no attribute 'device'` when `bias=False, batch_first=True`

### ISSUE THREAD

**Issue by xbanke** [pytorch/pytorch#116385]
### 🐛 Describe the bug

```py
import torch


batch_size = 32
seqlen = 20
d_model = 64
nhead = 4

encoder_layer = torch.nn.TransformerEncoderLayer(d_model, nhead, bias=False, batch_first=True).eval()
x = torch.randn(batch_size, seqlen, d_model)

y = encoder_layer(x)  # AttributeError: 'NoneType' object has no attribute 'device'
```

### Versions

PyTorch version: 2.1.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          40
On-line CPU(s) list:             0-39
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       5
Stepping:                        1
BogoMIPS:                        4799.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm rdseed adx smap xsaveopt arat
Hypervisor vendor:               VMware
Virtualization type:             full
L1d cache:                       160 KiB (5 instances)
L1i cache:                       160 KiB (5 instances)
L2 cache:                        1.3 MiB (5 instances)
L3 cache:                        125 MiB (5 instances)
NUMA node(s):                    3
NUMA node0 CPU(s):               0-15
NUMA node1 CPU(s):               16-31
NUMA node2 CPU(s):               32-39
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown

Versions of relevant libraries:
[pip3] mypy==1.5.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-tabnet==4.1.0
[pip3] torch==2.1.0+cpu
[pip3] torchaudio==2.1.0+cpu
[pip3] torchsort==0.1.9
[pip3] torchvision==0.16.0+cpu
[pip3] torchviz==0.0.2
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] pytorch-tabnet            4.1.0                    pypi_0    pypi
[conda] torch                     2.1.0+cpu                pypi_0    pypi
[conda] torchaudio                2.1.0+cpu                pypi_0    pypi
[conda] torchsort                 0.1.9                    pypi_0    pypi
[conda] torchvision               0.16.0+cpu               pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @ezyang @gchanan @zou3519 @kadeng @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by willtryagain** [comment]
```
tensor_args = (
              src,
              self.self_attn.in_proj_weight,
              self.self_attn.in_proj_bias,
              self.self_attn.out_proj.weight,
              self.self_attn.out_proj.bias,
              self.norm1.weight,
              self.norm1.bias,
              self.norm2.weight,
              self.norm2.bias,
              self.linear1.weight,
              self.linear1.bias,
              self.linear2.weight,
              self.linear2.bias,
          )

```
tensor args also includes the bias variables so while evaluating, `(x.device.type in _supported_device_type) for x in tensor_args`
it is checking device even for the bias variables which are None in your case. It can be fixed by modifying tensor_args based on bias.

**Comment by mingfeima** [comment]
@Valentine233 could you please take a look at this one ?

**Comment by jbschlosser** [comment]
cc @mikaylagawarecki won't it be nice when the fastpath is gone :)

**Comment by Valentine233** [comment]
> ```
> tensor_args = (
>               src,
>               self.self_attn.in_proj_weight,
>               self.self_attn.in_proj_bias,
>               self.self_attn.out_proj.weight,
>               self.self_attn.out_proj.bias,
>               self.norm1.weight,
>               self.norm1.bias,
>               self.norm2.weight,
>               self.norm2.bias,
>               self.linear1.weight,
>               self.linear1.bias,
>               self.linear2.weight,
>               self.linear2.bias,
>           )
> ```
> 
> [tensor args](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/transformer.py#L659) also includes the bias variables so while evaluating, `(x.device.type in _supported_device_type) for x in tensor_args` it is checking device even for the bias variables which are None in your case. It can be fixed by modifying tensor_args based on bias.

Agree. We should check the 6 bias in `tensor_args` and remove bias which equals to `None`. It's an issue existing for both CUDA and CPU.

**Comment by willtryagain** [comment]
should I submit PR for this?

**Comment by mikaylagawarecki** [comment]
@willtryagain Assigning to myself as I intend to submit a fix for this today (as this is a duplicate of https://github.com/pytorch/pytorch/issues/116546 which is marked high priority), feel free to take a look at the [issues marked actionable](https://github.com/pytorch/pytorch/issues?q=is%3Aopen+is%3Aissue+label%3Aactionable) if you would like to contribute
