### ISSUE TITLE
Tensor.type does not support torch.privateuseone.DtyeTensor

### ISSUE THREAD

**Issue by huihoaan** [pytorch/pytorch#116410]
### 🐛 Describe the bug

torch can create a new tensor by using `tensor.type()` with `tensor.cuda.DtyeTensor`, for example:
```
import torch
t = torch.rand(2, 3).cuda()
r = t.type(torch.cuda.FloatTensor)
```
However, when using `privateuse1`, I will get the following error: `ValueError: invalid type: 'torch.privateuseone.DtypeTensor'`:
```
import torch
t = torch.rand(2, 3).privateuseone()
r = t.type(torch.privateuseone.FloatTensor)
```

The function that needs to be fixed is `options_from_string` which called in `THPVariable_type`:
https://github.com/pytorch/pytorch/blob/3c9076f070fab5b27eae3b7846755c98b7c97a1a/torch/csrc/utils/tensor_types.cpp#L78-L81

I found that torch.backend.DtyeTensor will deprecated. So, I want to know when it's really deprecated. If it still takes some time, can I fix if for Privateuse1 first and discard `torch.backend.DtyeTensor` together later?

### Versions

PyTorch version: 2.1.0
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (aarch64)
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.27

Python version: 3.8.17 (default, Jul  5 2023, 20:40:03)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-29-generic-aarch64-with-glibc2.26
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              192
On-line CPU(s) list: 0-191
Thread(s) per core:  1
Core(s) per socket:  48
Socket(s):           4
NUMA node(s):        4
Vendor ID:           0x48
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            24576K
NUMA node0 CPU(s):   0-47
NUMA node1 CPU(s):   48-95
NUMA node2 CPU(s):   96-143
NUMA node3 CPU(s):   144-191
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.6.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] optree==0.9.1
[pip3] torch==2.1.0
[pip3] torch-npu==2.1.0
[pip3] torchair==0.1
[pip3] torchvision==0.15.2
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] optree                    0.9.1                    pypi_0    pypi
[conda] torch                     2.1.0a0+git7bcf7da          pypi_0    pypi
[conda] torch-npu                 2.1.0+gite2920a1          pypi_0    pypi
[conda] torchair                  0.1                      pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

cc @bdhirsh

**Comment by jbschlosser** [comment]
Added triage review for labeling

**Comment by janeyx99** [comment]
Thank you @huihoaan for digging into this!

We recommend users move away from `torch.backend.DtypeTensor` as there are many other better alternatives to achieving similar functionality even though we haven't yet deleted the API. Thus, we will likely **not** accept changes for the deprecated API.

**Comment by janeyx99** [comment]
Closing this issue given previous comment, but if other needs arise that haven't been addressed, please feel to reopen!

**Comment by janeyx99** [comment]
Oh yes: to my knowledge, there are no current plans to actually remove the DTypeTensor API. We are not accepting new features on it and recommend people to not keep using it.
