### ISSUE TITLE
torch.onnx.export has inconsistent results when exported on torch1.8 and torch1.12

### ISSUE THREAD

**Issue by loganxiayan** [pytorch/pytorch#116497]
### 🐛 Describe the bug

I used 2240 and 448 images to forward on yolov5, and then combined two forward together to get a new model with six Detect. When exporting this model as onnx, I got different results when using torch.onnx.export in torch1.8 and torch1.12. What should I make the exported results consistent.
![1 8](https://github.com/pytorch/pytorch/assets/68056907/4112ae21-b397-4ded-92b8-b12f7ea1fa0d)
![1 12](https://github.com/pytorch/pytorch/assets/68056907/4b5a3d40-5fbb-4862-936f-b661f76dae13)

### Versions

torch1.8
torch1.12

**Comment by albanD** [comment]
Hi,

Both these versions are very old. Do you have any issue with the latest 2.2 version?

**Comment by loganxiayan** [comment]
> Hi,
> 
> Both these versions are very old. Do you have any issue with the latest 2.2 version?

Yeah，I tried using version 2.2, and the result is similar to version 1.2

**Comment by loganxiayan** [comment]
> Hi,
> 
> Both these versions are very old. Do you have any issue with the latest 2.2 version?

Yeah, I tried the latest 2.2 version, but the result is similar to the 1.12 version.

**Comment by justinchuby** [comment]
The graph on the bottom seems to be a more simplified version. Which graph is the expected one?

**Comment by loganxiayan** [comment]
> The graph on the bottom seems to be a more simplified version. Which graph is the expected one?
The top is the 1.8 version result and the bottom is the 1.12 version result. I expect to get the top graph for 1.8 version.

**Comment by loganxiayan** [comment]
> The graph on the bottom seems to be a more simplified version. Which graph is the expected one?

The top is the 1.8 version result and the bottom is the 1.12 version result. I expect to get the top graph for 1.8 version.

**Comment by justinchuby** [comment]
Thanks - Looks like the result is expected then. The bottom graph seems to be a more simplified graph. We cannot guarantee the graphs to stay the same across different PyTorch versions.

**Comment by loganxiayan** [comment]
> Thanks - Looks like the result is expected then. The bottom graph seems to be a more simplified graph. We cannot guarantee the graphs to stay the same across different PyTorch versions.

Yeah, the two results have similar structures, but there are many identity nodes in the bottom graph. The more trouble is that the bottom results (torch1.12) show parse failed to onnx when converted to tensorrt format.

**Comment by justinchuby** [comment]
cc @bowenbao case for identity removal

**Comment by justinchuby** [comment]
@loganxiayan if the ONNX models are valid, it may be a good idea to raise an issue against the tensorrt project.

**Comment by loganxiayan** [comment]
> @loganxiayan if the ONNX models are valid, it may be a good idea to raise an issue against the tensorrt project.

Thanks

**Comment by thiagocrepaldi** [comment]
Could you provide a repro script? and the backtrace for the latest pytorch version (2.1), if any? 
As mentioned above, the graph representations may change over time either to fix bugs or for performance reasons. There is no guarantee the same graph will be preserved across pytorch releases. 

If you see an incorrect pattern (instead of different then previous releases) in latest pytorch, let us know and we can look into it

**Comment by thiagocrepaldi** [comment]
Closing as we don't support compatibility between pytorch/onnx versions.

Please reopen this if the latest pytorch version isn't numerically accurate
