### ISSUE TITLE
[dynamo] missing support for itertools.chain.from_iterable

### ISSUE THREAD

**Issue by Skylion007** [pytorch/pytorch#116463]
### 🐛 Describe the bug

```python
import itertools
import torch

def fn() -> None:
    a = list(range(1, 3))
    b = list(range(3, 6))
    c = [a, b]
    d = itertools.chain.from_iterable(c)
    return d


comp = torch._dynamo.optimize(nopython=True)(fn)()
```

While itertools.chain is properly implemented in dynamo, itertools.chain.from_iterable is not. It should be pretty trivial to implement and a good first issue. The only concern is how to properly add it to the itertools dynamo shim as it's a nested class function on the itertools.chain function. We should support this as it's a slightly uncommon way to call arguably the most common itertools utility (itertools.chain).

### Versions

master

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by vortex73** [comment]
I would like to take this up. Please elaborate since i'm pretty new to the codebase

**Comment by Abdulrahman-Adel** [comment]
Hi @Skylion007, I'd like to work on it.

**Comment by Skylion007** [comment]
The other itertools functions for dynamo are defined here, but I am not sure what the best way to add this is here because it's technically a function on itertools.chain https://github.com/pytorch/pytorch/blob/97891b184c12763f335fbe1ff63fab843edafab5/torch/_dynamo/variables/iter.py#L15 Thoughts @jbschlosser ?

**Comment by hgl71964** [comment]
Hi, I have submitted a PR to fix this bug. Essentially, a handler is added at variables/builtin.py so that itertools.chain.from_iterable can be properly handled. I also added a test in test_function.py to test it.

**Comment by hgl71964** [comment]
Apologies, my previous PR has a unsigned CLA commit, thus failing check. I have open a new one now
