### ISSUE TITLE
although i have a gpu, i get torch.__version__ = "2.1.0" instead of torch.__version__="2.1.0+cu118"

### ISSUE THREAD

**Issue by mustafaemre2** [pytorch/pytorch#116408]
### 🐛 Describe the bug

although i have a gpu, i get torch.__version__ = "2.1.0" instead of torch.__version__="2.1.0+cu118"
What is the reason?

### Versions

although i have a gpu, i get torch.__version__ = "2.1.0" instead of torch.__version__="2.1.0+cu118"
What is the reason?

**Comment by jbschlosser** [comment]
You may have built torch without CUDA support for one reason or another (perhaps CUDA wasn't installed in the usual place?). I'll refer you to the [PyTorch forums](https://discuss.pytorch.org/) for more help with environment-related issues like this. Note that the issues here are reserved for problems within PyTorch itself.
