### ISSUE TITLE
Performance (speed) regression from 0.4.0 to 0.4.1

### ISSUE THREAD

**Issue by blester125** [pytorch/pytorch#11647]
## Issue description

I have a fairly optimized cnn-blstm-crf tagger [here](https://github.com/dpressel/baseline/blob/master/python/baseline/pytorch/tagger/model.py) with the crf defined [here](https://github.com/dpressel/baseline/blob/f0204432076c166ce3d6672705826f33aec95dbe/python/baseline/pytorch/torchy.py#L669).

On pytorch `0.4.0` using cuda `9.0` and cudnn `7102` I can run a single epoch of the conll 2003 NER task in 21.41 +/- 0.28

When the only thing I change is the version of pytorch to `0.4.1` (the current conda install) a single epoch now takes  27.99 +/-  0.26

These models are run on gpu.

From the pytorch forums I was told to post here https://discuss.pytorch.org/t/large-preformance-regression-on-0-4-1/25037

## Code example

Please try to provide a minimal example to repro the bug.

Assuming pytorch is installed

```
git clone https://github.com/blester125/baseline.git
cd baseline
git checkout speed-test
cd python
./install_dev.sh baseline no-test
echo "{}" > mead/config/mead-settings.json
mead-train --config config/conll-bio.json
```

### 0.4.0

Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070 with Max-Q Design
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0-cudnn-7/lib64/libcudnn.so
/usr/local/cuda-9.0-cudnn-7/lib64/libcudnn.so.7
/usr/local/cuda-9.0-cudnn-7/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0-cudnn-7/lib64/libcudnn.so.7.1.2
/usr/local/cuda-9.0-cudnn-7/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0/lib64/libcudnn.so.7.1.2
/usr/local/cuda-9.0/lib64/libcudnn.so.7.2.1
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] torch (0.4.0)
[pip] torchfile (0.1.0)
[pip] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0            py36hdf912b8_0  
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch

### 0.4.1
Collecting environment information...
PyTorch version: 0.4.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070 with Max-Q Design
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0-cudnn-7/lib64/libcudnn.so
/usr/local/cuda-9.0-cudnn-7/lib64/libcudnn.so.7
/usr/local/cuda-9.0-cudnn-7/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0-cudnn-7/lib64/libcudnn.so.7.1.2
/usr/local/cuda-9.0-cudnn-7/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0/lib64/libcudnn.so.7.1.2
/usr/local/cuda-9.0/lib64/libcudnn.so.7.2.1
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] torch (0.4.1.post2)
[pip] torchfile (0.1.0)
[pip] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    pytorch
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by SsnL** [comment]
Thanks for the detailed report Brian!

**Comment by weiyangfb** [comment]
@blester125 I am trying to repro this issue via the example you provided, but ran into an error lol would you like to take a look?
```
>>> mead-train --config config/conll-bio.json --time
Task: [tagger]
Traceback (most recent call last):
  File "/home/weiyang/anaconda2/bin/mead-train", line 11, in <module>
    load_entry_point('deep-baseline', 'console_scripts', 'mead-train')()
  File "/home/weiyang/baseline/python/mead/trainer.py", line 27, in main
    task = mead.Task.get_task_specific(task_name, args.logging, args.settings)
  File "/home/weiyang/baseline/python/mead/tasks.py", line 69, in get_task_specific
    config = Task.TASK_REGISTRY[task](logging_config, mead_config)
  File "/home/weiyang/baseline/python/mead/tasks.py", line 304, in __init__
    super(TaggerTask, self).__init__(logging_config, mead_settings_config, **kwargs)
  File "/home/weiyang/baseline/python/mead/tasks.py", line 34, in __init__
    raise Exception("Expected either a mead settings file or a JSON object")
Exception: Expected either a mead settings file or a JSON object
################
```

**Comment by blester125** [comment]
My bad, some stuff got swapped out. This should be the steps to run it, I'll update the issue too. (These 
assume that pytorch is already installed)
```
git clone https://github.com/blester125/baseline.git
cd baseline
git checkout speed-test
cd python
./install_dev.sh baseline no-test
echo "{}" > mead/config/mead-settings.json
mead-train --config config/conll-bio.json
```

This should both print timing information to stdout and also to a file called timing-{pid}.log

**Comment by weiyangfb** [comment]
@blester125 Thanks! It is running fine now :)

**Comment by blester125** [comment]
Thanks for looking into it. Impressed by the thoroughness and quick fix.

**Comment by gpleiss** [comment]
Advanced indexing also had a perf hit on CPU as well:

```bash
======= pytorch (0.4.1) =======
23.6 µs ± 46.8 ns per loop (mean ± std. dev. of 100 runs, 10000 loops each)

======= pytorch-nightly =======
54.6 µs ± 323 ns per loop (mean ± std. dev. of 100 runs, 10000 loops each)
```

**Comment by fmassa** [comment]
@gpleiss yes, this is in part due to the wrapping of negative indices I think.
@colesbury is working on a PR that will completely revamp advanced indexing, and should bring the performance back to what it was (or even faster in some cases)

**Comment by SsnL** [comment]
cc @weiyangfb on advanced indexing slow down

**Comment by weiyangfb** [comment]
probably good to re-time again after this PR lands: https://github.com/pytorch/pytorch/pull/13420

**Comment by weiyangfb** [comment]
closing this since #13420 landed

**Comment by gpleiss** [comment]
Awesome!!! Can't wait to test this out. Thanks so much, all!
