### ISSUE TITLE
RuntimeError: attempting to assign a gradient with dtype 'c10::BFloat16' to a tensor with dtype 'float'. Please ensure that the gradient and the tensor have the same dtype

### ISSUE THREAD

**Issue by gouchangjiang** [pytorch/pytorch#116409]
### 🐛 Describe the bug

When using FSDP with the sharding strategy SHARD_GRAD_OP, and gradient accumulation, this problem arises. It only happens with torch version 2.1.0. With the newest torch version, it disappears. It seems that you forgot to apply this [PR](https://github.com/pytorch/pytorch/pull/108823).  A related issue [here](https://github.com/pytorch/pytorch/issues/111317). @voznesenskym 

### Versions

torch==2.1.0+cu118

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by awgu** [comment]
Is the suggestion to cherry-pick https://github.com/pytorch/pytorch/pull/108823 onto 2.1?

**Comment by gouchangjiang** [comment]
Yes, exactly. Thanks.

Andrew Gu ***@***.***> 于2023年12月27日周三 00:13写道：

**Comment by jbschlosser** [comment]
Adding triage review to discuss cherry pick

**Comment by jbschlosser** [comment]
Since this is fixed on the main branch, I'm going to close this. At this point, it's sadly too late to cherry pick onto the older 2.1 release.
