### ISSUE TITLE
Convert onnx failed with interrupted by signal 8:SIGFPE

### ISSUE THREAD

**Issue by MichaelH717** [pytorch/pytorch#116415]
### 🐛 Describe the bug

hello, when i convert my model to onnx, only this bug report:
>>Process finished with exit code 136 (interrupted by signal 8:SIGFPE)
I use gdb to debug and find something like this:
![floating_point_exception](https://github.com/pytorch/pytorch/assets/75190093/9e5cb4e0-f96f-43ae-baac-e8bde5074d9d)

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.28.1
Libc version: glibc-2.31

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4080
Nvidia driver version: 525.60.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              1
Core(s) per socket:              24
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           183
Model name:                      13th Gen Intel(R) Core(TM) i9-13900KF
Stepping:                        1
CPU MHz:                         1226.896
CPU max MHz:                     4300.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5990.40
Virtualization:                  VT-x
L1d cache:                       576 KiB
L1i cache:                       384 KiB
L2 cache:                        24 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0            py38h5eee18b_1  
[conda] mkl_fft                   1.3.6            py38h417a72b_1  
[conda] mkl_random                1.2.2            py38h417a72b_1  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-base                1.24.3           py38h060ed82_1  
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchaudio                2.0.2                py38_cu118    pytorch
[conda] torchvision               0.15.2               py38_cu118    pytorch

**Comment by justinchuby** [comment]
Please include a script to reproduce the error. I would also be sure to use the latest version of PyTorch. Thanks!

**Comment by MichaelH717** [comment]
> Please include a script to reproduce the error. I would also be sure to use the latest version of PyTorch. Thanks!

Thanks a lot, I just solved this bug by add some asseertion

**Comment by dannyfriar** [comment]
I have a similar issue with a torch ONNX export, what assertion did you add @MichaelH717?

**Comment by MichaelH717** [comment]
> I have a similar issue with a torch ONNX export, what assertion did you add @MichaelH717?
 I just use traceback lib to get the traceback of my code, and then check the onnx graph to find the bug.

**Comment by My-captain** [comment]
> > I have a similar issue with a torch ONNX export, what assertion did you add @MichaelH717?
> > I just use traceback lib to get the traceback of my code, and then check the onnx graph to find the bug.

Could you provide more details about how to get the traceback of my code?
In my code, the exception (Process finished with exit code 136 (interrupted by signal 8:SIGFPE)) can`t be catch by python try.
