### ISSUE TITLE
UnboundLocalError: local variable 'torch' referenced before assignment

### ISSUE THREAD

**Issue by clemente0731** [pytorch/pytorch#116405]
### 🐛 Describe the bug

```
import torch

def aa():
    print("==== here is aa ====")
    print(torch)


def bb():
    print("==== here is bb ====")
    print(torch)
    import torch.profiler

aa()
bb()
```

here is aa
<module 'torch' from '/root/miniconda/envs/python38_torch201_cuda/lib/python3.8/site-packages/torch/__init__.py'>
here is bb
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    bb()
  File "test.py", line 10, in bb
    print(torch)
UnboundLocalError: local variable 'torch' referenced before assignment

### Versions

```
import torch

def aa():
    print("==== here is aa ====")
    print(torch)


def bb():
    print("==== here is bb ====")
    print(torch)
    import torch.profiler

aa()
bb()
```

here is aa
<module 'torch' from '/root/miniconda/envs/python38_torch201_cuda/lib/python3.8/site-packages/torch/__init__.py'>
here is bb
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    bb()
  File "test.py", line 10, in bb
    print(torch)
UnboundLocalError: local variable 'torch' referenced before assignment

**Comment by isuruf** [comment]
This is normal behaviour in python and is not specific to pytorch. When `import torch.profiler` is run, torch is imported into the local context and the interpreter assumes `print(torch)` is for the local variable. To avoid this, do,

```

**Comment by jbschlosser** [comment]
Closing as expected behavior.
