### ISSUE TITLE
Dynamo'd optimizer does not handle closure correctly

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#116494]
### 🐛 Describe the bug

My suspicion is that we do not re-enable grad mode for the closure when calling it from within step. Due to this, there is a disparity between eager and dynamo for optimizers with closures that depend on grads getting modified, which...according to https://github.com/pytorch/pytorch/issues/38006, account for all cases where closures are used.

Disclaimer: There is an ongoing issue (https://github.com/pytorch/pytorch/issues/38006) that requires looking into where the example I provide below is potentially abusing the closure (I modify the .grad field of the params within the closure), which the docs say should not happen, but empirical evidence points 100% otherwise. Regardless, we probably want to either ban closures (and error when we notice one) or actually call them correctly.

### Error logs

```
(pytorch-3.10) [janeyx@devgpu023.odn1 ~/local/pytorch (d186986c)]$ python playground2.py 
before compiled loop: param=tensor([[0.6176, 0.6603, 0.8097],
        [0.8297, 0.5115, 0.0299]], device='cuda:0', requires_grad=True)
after compiled loop: param=tensor([[0.6176, 0.6603, 0.8097],
        [0.8297, 0.5115, 0.0299]], device='cuda:0', requires_grad=True)
before eager loop: param_c=tensor([[0.6176, 0.6603, 0.8097],
        [0.8297, 0.5115, 0.0299]], device='cuda:0', requires_grad=True)
after eager loop: param_c=tensor([[0.6166, 0.6593, 0.8087],
        [0.8287, 0.5105, 0.0289]], device='cuda:0', requires_grad=True)
```

### Minified repro

```
import torch

param = torch.rand(2, 3, dtype=torch.float32, device='cuda', requires_grad=True)
param_c = param.clone().detach().requires_grad_(True)

def closure():
    param.grad = torch.ones_like(param) * 2
    return param.grad

def closure_c():
    param_c.grad = torch.ones_like(param_c) * 2
    return param_c.grad

optimizer = torch.optim.AdamW([param])
optimizer_c = torch.optim.AdamW([param_c])

def loop(opt, c):
    opt.step(c)

compiled_loop = torch._dynamo.optimize("eager")(loop)

print(f"before compiled loop: {param=}")
compiled_loop(optimizer, closure)
print(f"after compiled loop: {param=}")

print(f"before eager loop: {param_c=}")
loop(optimizer_c, closure_c)
print(f"after eager loop: {param_c=}")
```

### Versions

on main

cc @ezyang @gchanan @zou3519 @kadeng @vincentqb @jbschlosser @albanD @crcrpar @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @mlazos

**Comment by janeyx99** [comment]
@mlazos Are you planning on a PR to try re-enabling the skips due to this issue in common_optimizers.py?

**Comment by mlazos** [comment]
Yup, I can submit a PR rn

**Comment by janeyx99** [comment]
Since there are still references to this issue on main, we should keep these issues open until those references are either removed or replaced. Let's wait til #121912 lands before fulling closing this one.
