### ISSUE TITLE
CI fails due to missing lxml for Python-3.9

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#116550]
**MERGE BLOCKING** 

## Current Status
*mitigated*.

## Error looks like
`Calculate docker image` step fails with 
```
       import pkg_resources
      Building lxml version 5.0.0.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]
```

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
Missing lxml pin and missing pyton-3.9 binaries on PyPI, see https://bugs.launchpad.net/lxml/+bug/2047720

## Mitigation
Pinned lxml dependency to 4.9.4 in https://github.com/pytorch/pytorch/pull/116549

## Prevention/followups
We should pin **ALL** dependencies

cc @seemethere @pytorch/pytorch-dev-infra

**Comment by pruthvistony** [comment]
https://pypi.org/project/lxml/5.0.0/#files is updated with 
- [lxml-5.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl](https://files.pythonhosted.org/packages/06/05/98b42bba3914553e004469587ab350c3202ebb68829247f21e6d99beb976/lxml-5.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl)
- [lxml-5.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl](https://files.pythonhosted.org/packages/fa/fc/8a0ec56b14e8b1e8ef68a665558223aabf03f4b929eb323de6f2f52ac6cd/lxml-5.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl)

**Comment by malfet** [comment]
@pruthvistony yes they are, but we probably should still keep pinned dependency (even though update to 5.0.0)

**Comment by pruthvistony** [comment]
> @pruthvistony yes they are, but we probably should still keep pinned dependency (even though update to 5.0.0)

yup, probably better. :)

**Comment by huydhn** [comment]
This has been mitigated, resolving the sev.
