### ISSUE TITLE
FSDP.optim_state_dict_to_load consumes a lot of memory

### ISSUE THREAD

**Issue by dchen496** [pytorch/pytorch#116553]
### 🐛 Describe the bug

Hello,

We've been using FSDP with DTensors and sharded checkpointing. We've noticed that `FSDP.optim_state_dict_to_load` seems to consume memory proportional to the unsharded model size rather than the sharded size.

The culprit seems to be this slicing operation, which retains the storage of the full tensor in optim_state. Once FSDP.load_state_dict is called these tensors and their storage goes away, but temporarily the memory usage can be much higher than expected.

https://github.com/pytorch/pytorch/blob/97891b184c12763f335fbe1ff63fab843edafab5/torch/distributed/fsdp/_optim_utils.py#L406C9-L406C9

Our workaround for now has just been to add `.clone()` at the end of that line. 

### Versions

We use a slightly patched version of v2.1.1, but the issue still appears to exist on `main`.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by awgu** [comment]
This makes sense to me. @fegin could you double check this too when you get the chance?

**Comment by awgu** [comment]
The fix just landed.
