### ISSUE TITLE
Linux runners occasionally dies with out-of-disk space, often during distributed tests

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#116510]
### 🐛 Describe the bug

See https://github.com/pytorch/pytorch/actions/runs/7348976508/job/20008916443 for example. 
When logged into one I've noticed 100+Gb of coredumps in test folder

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra @ZainRizvi @kit1980 @huydhn @clee2000

**Comment by malfet** [comment]
Looks like it often happens because distributed tests validate recovery from crashes that can drain disk space
Possible solutions:
 - If coredumps are not useful, stop generating them
 - Increase disk space for such runners

**Comment by seemethere** [comment]
Partially resolved here with https://github.com/pytorch/pytorch/pull/116514

This PR should make it so that anything running a linux test will have an upper limit of 1GB

**Comment by huydhn** [comment]
> Looks like it often happens because distributed tests validate recovery from crashes that can drain disk space

I disabled coredumps on CI when rerunning disabled tests or when `keep-going` label is used https://github.com/pytorch/pytorch/blob/main/.ci/pytorch/test.sh#L61-L76.  May be this is an additional case that this could be done, i.e. turning off core dump for distributed tests that check crash recovery?

**Comment by albanD** [comment]
I don't think I've never looked at them either. Disabling by default sounds good to me.

**Comment by malfet** [comment]
I think coredumps are disable for now, so we can close the issue
