### ISSUE TITLE
Deterministic Not Work in nn.Conv2d when dtype=torch.float32

### ISSUE THREAD

**Issue by Magicalyz** [pytorch/pytorch#116501]
I created 2 input tensor with shape [2, 3, 224, 224] for conv2d layer and the outputs are different from the output when input tensors are batched in dim=0. 
This only occurs when dtype=torch.float32, and go well when dtype=torch.bfloat16.
Below is my test code.
```
import torch
torch.manual_seed(0)
torch.use_deterministic_algorithms(True)
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True

a = torch.rand(2, 3, 224, 224, dtype=torch.float32).cuda()
b = torch.rand(2, 3, 224, 224, dtype=torch.float32).cuda()
c = torch.cat([a, b])
conv = torch.nn.Conv2d(in_channels=3, out_channels=1408, kernel_size=(14,14), stride=(14,14)).to(dtype=torch.float32).cuda()
output0 = conv(a)
output1 = conv(b)
output01 = conv(c)
print(torch.allclose(a, c[:2]))
print(torch.allclose(b, c[2:]))
print(torch.allclose(output0, output01[:2]))
print(torch.allclose(output1, output01[2:]))
# output:
#     True
#     True
#     False
#     False

a = torch.rand(2, 3, 224, 224, dtype=torch.bfloat16).cuda()
b = torch.rand(2, 3, 224, 224, dtype=torch.bfloat16).cuda()
c = torch.cat([a, b])
conv = torch.nn.Conv2d(in_channels=3, out_channels=1408, kernel_size=(14,14), stride=(14,14)).to(dtype=torch.bfloat16).cuda()
output0 = conv(a)
output1 = conv(b)
output01 = conv(c)
print(torch.allclose(a, c[:2]))
print(torch.allclose(b, c[2:]))
print(torch.allclose(output0, output01[:2]))
print(torch.allclose(output1, output01[2:]))
# output:
#     True
#     True
#     True
#     True
```

### Versions

PyTorch version: 2.1.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.4.143.bsk.7-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: A100-SXM4-80GB
GPU 1: A100-SXM4-80GB
GPU 2: A100-SXM4-80GB
GPU 3: A100-SXM4-80GB
GPU 4: A100-SXM4-80GB
GPU 5: A100-SXM4-80GB
GPU 6: A100-SXM4-80GB
GPU 7: A100-SXM4-80GB

Nvidia driver version: 450.216.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         3000.000
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        108 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] byted-torch==2.1.0.post1
[pip3] byted-torch-monitor==0.0.1
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0+cu117
[pip3] torchaudio==2.1.0+cu117
[pip3] torchlibrosa==0.1.0
[pip3] torchvision==0.16.0+cu117
[pip3] triton==2.1.0
[conda] Could not collect

**Comment by albanD** [comment]
Hi,

What you're describing is not determinism but batching. It is indeed expected to be different, see https://pytorch.org/docs/stable/notes/numerical_accuracy.html#batched-computations-or-slice-computations for more details.
