### ISSUE TITLE
TransformerEncoderLayer forward() crashes for bias=False during evaluation

### ISSUE THREAD

**Issue by pallgeuer** [pytorch/pytorch#116546]
I am using `TransformerEncoder`/`TransformerEncoderLayer` in my model and was able to train it fine. Now I'm trying to do inference and the code is crashing with:
```
...
  File "/home/allgeuer/anaconda3/envs/ovod/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 387, in forward
    output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)
  File "/home/allgeuer/anaconda3/envs/ovod/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/allgeuer/anaconda3/envs/ovod/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/allgeuer/anaconda3/envs/ovod/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 669, in forward
    elif not all((x.device.type in _supported_device_type) for x in tensor_args):
  File "/home/allgeuer/anaconda3/envs/ovod/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 669, in <genexpr>
    elif not all((x.device.type in _supported_device_type) for x in tensor_args):
AttributeError: 'NoneType' object has no attribute 'device'
```
I am using `bias=False` when constructing my `TransformerEncoderLayer`, so all bias parameters within the layer (see `nn.Linear` and `nn.LayerNorm` implementations) are naturally `None`. I have PyTorch 2.1.2 from conda, but even looking at the latest source code shows there is clearly an issue:
https://github.com/pytorch/pytorch/blob/de4d48df34c0e8bcd03d96bcdfd12e263e9889ff/torch/nn/modules/transformer.py#L658-L710

`tensor_args` contains the bias parameters, and hence includes `None`'s, but L680 invokes `x.device.type` for all `x` in `tensor_args`, producing the observed crash. I assume this is not intended.

The questions in that case are:
* Can `torch._transformer_encoder_layer_fwd()` (called right after in L689) deal with `None` bias parameters? If so, then L680 and L683 need to be protected against `None`'s I presume. If not, `None in tensor_args` would have to in its own right be a reason `why_not_sparsity_fast_path`?
* How can people like me with the current version of PyTorch work around the issue while waiting for a fix, and be able to actually inference our `bias=False` models?

Update: Potentially a similar issue?
https://github.com/pytorch/pytorch/blob/de4d48df34c0e8bcd03d96bcdfd12e263e9889ff/torch/nn/modules/transformer.py#L382

cc @ezyang @gchanan @zou3519 @kadeng @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by ezyang** [comment]
Looks legit to me.

**Comment by pallgeuer** [comment]
Legit as in it's indeed a problem like I think, or legit as in the code is fine somehow as it is?

**Comment by mikaylagawarecki** [comment]
Thanks for the report @pallgeuer. This is a real issue and is also discussed in https://github.com/pytorch/pytorch/issues/116385, closing this to redirect the discussion there. I intend to submit a fix for this today
