### ISSUE TITLE
When I try to call torch.linalg.eigvals using an acceleration device other than cuda, an error message is displayed. Maybe it needs to be adapted.

### ISSUE THREAD

**Issue by beiwei37d** [pytorch/pytorch#116504]
### 🚀 The feature, motivation and pitch

When I tried to call torch.linalg.eigvals with another acceleration device, I found that an error was reported. After preliminary location, it is found that when complex_out is used to construct a complex number, some input tensors are on the device and some are on the CPU. 
```
if (values.is_complex()) {
      values = at::complex_out(values, real_values, imag_values); //values is on the device,but real_values and imag_values are on the CPU
} else {
      TORCH_CHECK(false, "torch.linalg.eig: imaginary part of eigenvalues is non-zero, can't safely cast eigenvalues to non-complex dtype.")
 }
```

Finally, I found the root cause,pytorch\aten\src\ATen\native\BatchLinearAlgebra.cpp:
```
  // because MAGMA's GEEV takes CPU inputs and returns CPU outputs
  // 'values' tensor that is on GPU device can't be used directly
  values_tmp_needed |= values.is_cuda(); //Look, it only checks if the acceleration device is cuda.
  ...
  if (values_tmp_needed) { 
    Tensor values_tmp = at::empty({0}, options.dtype(values_type));
    std::tie(values_tmp, std::ignore) = linalg_eig_out_info(input, values_tmp, vectors, infos, /*compute_eigenvectors=*/false);
    at::native::resize_output(values, values_tmp.sizes());
    values.copy_(values_tmp);
  } else { // use 'values' storage directly
    std::tie(values, std::ignore) = linalg_eig_out_info(input, values, vectors, infos, /*compute_eigenvectors=*/false);
  }
```
 In linalg_eig_out, temporary variables are set when the device is determined to be a CUDA device, and temporary variables on the CPU are used as input. However, when other acceleration devices are used, the corresponding judgment is not performed. The input is still the tensor on the device.  I would appreciate it if the community would consider compatibility with other devices in response to this issue!

### Alternatives

Maybe you can determine whether values and vectors are on the CPU. If values and vectors are not on the CPU, set temporary variables on the CPU as subsequent input.

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano

**Comment by lezcano** [comment]
Can you provide a small repro of the issue?

**Comment by lezcano** [comment]
And thank you for the detailed analysis :) With a repro, we should be able to act on this one quickly

**Comment by beiwei37d** [comment]
> 你能提供一个问题的小重现吗？

I printed some key logs, and the results were as follows: cuda results on the left and npu results on the right. Through the information in the green box, I found that they took different branches that led to the final error.

**Comment by beiwei37d** [comment]
> Can you provide a small repro of the issue?

Here's my code
```
//-----cuda-----
import torch
data=torch.tensor([[0.8988, 0.6839, 0.7658],[0.9149, 0.3993, 0.1100],[0.2541, 0.4333, 0.4451]]).cuda()
result=torch.linalg.eigvals(data)
print(result)
```
```
// ------another device------
import torch,torch_npu
data=torch.tensor([[0.8988, 0.6839, 0.7658],[0.9149, 0.3993, 0.1100],[0.2541, 0.4333, 0.4451]]).npu()
result=torch.linalg.eigvals(data)
print(result)
```

I printed some key logs, and the results were as follows: the cuda results above and the npu results below. Through the printed information, I found that they took different branches, leading to the final error.
```
// ------cuda------
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 3090 cuda:0
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 3127 cuda:0
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 3129 cpu
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2863 cpu
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2866 cpu
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2886 cpu
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2891 cpu
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2910 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2912 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2939 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2941 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2958 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2960 
cpu cpu cpu
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2963 cpu
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2968 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 3133 cuda:0
tensor([ 2.7716e+38+infj,  2.7716e+38-infj,
        -3.3970e+38+7.6663e+37j, -3.3970e+38-7.6663e+37j,
         2.1110e+38+0.0000e+00j,  4.1383e+37+1.6028e+38j,
         4.1383e+37-1.6028e+38j], device='cuda:0')
``` 

```
// ------another device------
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 3136 linalg_eigvals
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 3143 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 3081 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 3124 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2858 
npu:0
npu:0
npu:0
npu:0
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2913 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2915 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2942 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2944 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2961 
/home/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp 2963 
npu:0 cpu cpu
Traceback (most recent call last):
  File "/home/test.py", line 3, in <module>
    torch.linalg.eigvals(a.npu())
RuntimeError: only npu tensor is supported
```
By the line numbers, I found that the two took different branches (which was mentioned in the description before here).
 By printing the device where the tensor is located, I found the direct cause of the error. The input tensor is not on the same device.
```
//-----cuda-----
cpu cpu cpu
//-----another device-----
npu:0 cpu cpu
```

**Comment by lezcano** [comment]
Ah, I see what you mean.

So, just to be sure here. Does `torch_npu` implement an API equivalent to MAGMA's here? Meaning, MAGMA has a particularly annoying API for this function, where it expects some tensors to be on GPU and some to be on CPU. It also returns batches of Fortran-strided matrices. Does `torch_npu` implement all this? And does it hook all this to the dynamic dispatching PyTorch does at
https://github.com/pytorch/pytorch/blob/95a86ed9ca107329151e0dc172386d50dd3471c6/aten/src/ATen/native/BatchLinearAlgebra.cpp#L2928
?

If that is the case, then your proposal makes complete sense. Feel free to send the patch proposed in the OP.

**Comment by beiwei37d** [comment]
In normal cases, other acceleration devices should go through the same branch as the CUDA, that is, the if branch. In this way, all tensors can be moved to the CPU for execution, avoiding the problem that tensors are not in the same device.
https://github.com/pytorch/pytorch/blob/95a86ed9ca107329151e0dc172386d50dd3471c6/aten/src/ATen/native/BatchLinearAlgebra.cpp#L3094-L3101

It may be possible to use privateuse1 so that values_tmp_neededed is true when other acceleration devices are used. I've tried and found this to be feasible, but not sure if it conforms to community norms.
https://github.com/pytorch/pytorch/blob/95a86ed9ca107329151e0dc172386d50dd3471c6/aten/src/ATen/native/BatchLinearAlgebra.cpp#L3083
change to
`
values_tmp_needed |= (values.is_cuda() || values.device().is_privateuseone());
`

**Comment by lezcano** [comment]
My point here is that this is a limitation of MAGMA. For example, the cuSolver API always takes all inputs in CUDA. There is no reason to expect other APIs to ask for some inputs to be on CPU. That is why I ask, does the NPU implementation of GEEV also ask for some of the inputs to live on CPU?

**Comment by beiwei37d** [comment]
Oh, I see what you mean. I found that the npu device I currently use also needs to run on the cpu, but I'm not so sure if other acceleration devices will do the same.

**Comment by lezcano** [comment]
Just out of curiosity, do you happen to have the relevant npu docs at hand?

At any rate, the proposal makes sense to me. You can do something like `values_tmp_not_needed &= values.is_cpu()` and adjust the rest of the code accordingly. We would accept a PR implementing this fix.

**Comment by beiwei37d** [comment]
Unfortunately, it's not particularly detailed, but there's a warning when it's executed, telling me it's going to be executed on the CPU.
Thank you very much for your modification suggestions, and I'll submit a pr later.
