### ISSUE TITLE
Improve the bot logic that cleans up closed stack PR branch

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#116631]
We have internal logic in `facebook-github-bot` that periodically cleaned up stack PR branch when the it is closed, i.e. https://github.com/pytorch/pytorch/pull/116229.  That works fine, but one of the pain point is that the branch is deleted too soon. 

* If the PR is reverted and the branch has been deleted, it cannot be re-opened to reland.
* A stacked PR is owned by the author of the stack, so a deleted branch couldn't be restored by others (to be confirmed)

The potential fix here is to move the logic to OSS bot and increase the amount of waiting time between when the PR is closed and the branch is cleaned up.

cc @ZainRizvi @kit1980 @clee2000 @PaliC @jeanschmidt @malfet

**Comment by clee2000** [comment]
The job was moved to OSS in https://github.com/pytorch/pytorch/pull/117079.  The internal job was disabled and corresponding code deleted in D53442166

Leaving this open because there's a bug in how the magic string to keep the branch open indefinitely

**Comment by clee2000** [comment]
Bug mentioned in previous comment fixed by https://github.com/pytorch/pytorch/pull/119399
