### ISSUE TITLE
How to install pytorch on

### ISSUE THREAD

**Issue by Joseph513shen** [pytorch/pytorch#116687]

**Comment by Joseph513shen** [comment]
my jetson nano :
python3.8(i need a python>=3.7);
jetpack 5
cuda 10.2
 i need a torch>=1.6

can't find it in:    https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048
so i have no choice but compile it from source,oh no ,it's complex to me!!pls help

**Comment by cpuhrsch** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
