### ISSUE TITLE
`test_modules.py` does not test for half precision or complex types

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#116626]
### 🐛 Describe the bug

The way it's written right now, it only tests float32 and float64, even though accelerator (and sometimes CPU) implementation exists for half precision types

### Versions

CI

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Ok, looks like there is a way to override this ones, but still there seems to be dtypes where implementation exists, but is not tested, for example:
```
% python ../test/test_modules.py --discover-tests|grep CrossEntropyLoss_mps
...
TestModuleMPS.test_repr_nn_CrossEntropyLoss_mps_float32
TestModuleMPS.test_repr_nn_CrossEntropyLoss_mps_float64
```

**Comment by mikaylagawarecki** [comment]
You are right, most of the ModuleInfos in common_modules.py default to `torch.testing._internal.common_dtypes.floating_types()` which is `torch.float32` and `torch.float64`, but other dtypes should be tested as well, assigning to myself to fix this

**Comment by mikaylagawarecki** [comment]
Reopening as the PR only added Half testing for MPS but did not fully address this issue
