### ISSUE TITLE
DTensor tensor subwrapper not be handle with apex

### ISSUE THREAD

**Issue by JsBlueCat** [pytorch/pytorch#116683]
### 🐛 Describe the bug

first in apex kernel, the kernel is registered as torch recommand way.
use setup.py codegen static register function to support custom op
``` python
CUDAExtension(
            name="fused_layer_norm_cuda",
            sources=["csrc/layer_norm_cuda.cpp", "csrc/layer_norm_cuda_kernel.cu"],
            extra_compile_args={
                "cxx": ["-O3"] + version_dependent_macros,
                "nvcc": ["-maxrregcount=50", "-O3", "--use_fast_math"] + version_dependent_macros,
            },
        )
```
will in torch.distributed._tensor.DTensor it was a  torch.Tensor._make_wrapper_subclass. but when send the dtensor to the registed apex kernel

```python
def forward(ctx, input, weight, bias, normalized_shape, eps, memory_efficient):
        global fused_layer_norm_cuda
        if fused_layer_norm_cuda is None:
            fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
        ctx.normalized_shape = normalized_shape
        ctx.eps = eps
        ctx.memory_efficient = memory_efficient
        input_ = input.contiguous()
        weight_ = weight.contiguous()
        bias_ = bias.contiguous()
        print(input_.data)
        print(id(input_.data))
        print(id(input_._local_tensor.data))
        output, mean, invvar = fused_layer_norm_cuda.forward_affine(
            input_, ctx.normalized_shape, weight_, bias_, ctx.eps
        )
        if ctx.memory_efficient:
            ctx.save_for_backward(output, weight_, bias_, None, invvar)
        else:
            ctx.save_for_backward(input_, weight_, bias_, mean, invvar)
        return output
```

i found that the input_ type is DTensor, and the data and id(data) also have some value
but it throws out the error

```
File "/root/cery.69/apex/apex/normalization/fused_layer_norm.py", line 44, in forward
    output, mean, invvar = fused_layer_norm_cuda.forward_affine(
RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
```

i think the tensor's data_ptr is wrong

```
(Pdb) input_.data_ptr()
0
(Pdb) input._local_tensor.data_ptr()
140438210084864
```

the wrapper tensor's data_ptr is nullptr, but we need it to be like it's wrapper tensor, named DTensor._local_tensor ? 

i am trying to solve this problem, i wolud like set the data_ptr function can be set by python.  and in python constructor, we will set a python capture function to return its' wrappered tensor's storage just like
```python
wrapper_class = torch._C.make_wrappered_class()
wrapper_class.set_data_ptr_py_func( lambda: T: return T._local_tensor.data_ptr() ) 
```
just use this fallback to python to given the chance for user to set the data_ptr() to support wrappered class in some cuda 
kernel?

### Versions

b/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         2999.915
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        108 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] mypy==1.7.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] optree==0.9.2
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.3.0a0+git6e1ba79
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] Could not collect

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by albanD** [comment]
Hi!

Could you share how you register your kernel in apex please?
The root cause of your issue is most likely that it is not registered the right way to fully support subclass and torch.compile.

**Comment by JsBlueCat** [comment]
> Hi!
> 
> Could you share how you register your kernel in apex please? The root cause of your issue is most likely that it is not registered the right way to fully support subclass and torch.compile.
i change the way the apex build kernel by 
```
TORCH_LIBRARY(fused_layer_norm_cuda, m){
    m.def("forward_affine", &layer_norm_affine);
}
```
i am sure that the op is registed in torch.ops， by using the ```torch.ops.load_library()```

**Comment by wanchaol** [comment]
> 
> i change the way the apex build kernel by add
> 
> ```
> TORCH_LIBRARY(fused_layer_norm_cuda, m){
>     m.def("forward_affine", &layer_norm_affine);
> }
> ```

Oh so you registered the apex kernel using the PyTorch way in your custom build? The current [Apex](https://github.com/NVIDIA/apex/blob/master/csrc/layer_norm_cuda.cpp#L453) is using plain pybind11 to bind to python without going through PyTorch dispatcher, this make different PyTorch systems does not work correctly, cc @albanD if this is what you were thinking.

If you already bind with torch_library, another option you can try to enable DTensor support is to add an DTensor operator implementation for forward/backward.. that's a bit more involved though

**Comment by JsBlueCat** [comment]
> > i change the way the apex build kernel by add
> > ```
> > TORCH_LIBRARY(fused_layer_norm_cuda, m){
> >     m.def("forward_affine", &layer_norm_affine);
> > }
> > ```
> 
> Oh so you registered the apex kernel using the PyTorch way in your custom build? The current [Apex](https://github.com/NVIDIA/apex/blob/master/csrc/layer_norm_cuda.cpp#L453) is using plain pybind11 to bind to python without going through PyTorch dispatcher, this make different PyTorch systems does not work correctly, cc @albanD if this is what you were thinking.
> 
> If you already bind with torch_library, another option you can try to enable DTensor support is to add an DTensor operator implementation for forward/backward.. that's a bit more involved though

yes，i change the way the kernel register, and remove python abi which the apex build.

i think make DTensor work in forward/backward in kernel is really nice idea. so i add the data_ptr to handle it

**Comment by albanD** [comment]
The way you want to register your kernel to get this to work smoothly is:
- Register your autograd implementation at the Autograd dispatch key
- Register your backend kernel to the appropriate backend key CPU/CUDA/etc

cc @zou3519 what is the latest tutorial for this?

**Comment by zou3519** [comment]
See https://docs.google.com/document/d/1W--T6wz8IY8fOI0Vm8BF44PdBgs283QvpelJZWieQWQ/edit#heading=h.pnrqcv6bkfn3

**Comment by JsBlueCat** [comment]
okey, get it. when you want to pass the custom op to pt2 (dynamo or not ).  
then the dispatch key must be set to autograd dispatch then the dispatch will go throught __torch_dispatch__.  
so wrapper class will be remove wrapper and do compute, but that will cause a large overhead to handle args and kwargs. 

if we can go through the kernel by DTensor and set the right Propagation placement when kernel have done there will be no overhead, and in kernel, the distribute info will also be maintain. so i think passing the DTensor to kernel, have a bit more performance than do __torch_dispatch__  (remove wrapper + local_kernel. + add wrapper)
