### ISSUE TITLE
Disalow -expt-relaxed-constexpr

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#116628]
### 🐛 Describe the bug

Disalow calling CPU functions from GPU

```
fbcode/caffe2/c10/util/Half.h(380): warning #20013-D: calling a constexpr __host__ function("imag") from a __host__ __device__ function("complex") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
```

This was the reason why https://github.com/pytorch/pytorch/pull/114001 got reverted due to the internal build failures

### Versions

main

cc @malfet @seemethere @ptrblck

**Comment by malfet** [comment]
Actually, after reading the doc, I wonder if we should do it other way around, and enable `-relaxed-constexpr` internally (we already do for ATen, but not for c10d)
