### ISSUE TITLE
RuntimeError: "eye" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by nick008a** [pytorch/pytorch#116609]
### 🐛 Describe the bug
```
import torch
torch.set_default_dtype(torch.bfloat16)
torch.eye(c)
```

### Versions

torch 2.1

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by malfet** [comment]
There are no good policy on what OPs should be supported vs which are not. But sure, adding BFloat16 for eye sounds reasonable

**Comment by malfet** [comment]
@nick008a it is already available on CUDA, isn't it?
```
$ python3 -c "import torch;print(torch.eye(3, dtype=torch.bfloat16, device='cuda'), torch.__version__)"
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0', dtype=torch.bfloat16) 2.1.1+cu121
```
