### ISSUE TITLE
NameError: name 'long' is not defined

### ISSUE THREAD

**Issue by KeithYin** [pytorch/pytorch#1166]
An error occurs when using `torchvision.utils.make_grid()`.And the error message is .
```
Traceback (most recent call last):
  File "/home/keith/PycharmProjects/JData/test.py", line 42, in <module>
    res = make_grid(imgs)
  File "/home/keith/.virtualenvs/pp/lib/python3.5/site-packages/torchvision/utils.py", line 28, in make_grid
    size = torch.Size(torch.Size([long(numImages)]) + tensorlist[0].size())
NameError: name 'long' is not defined
```
Then , i was trying to figure out why this happed  and i found in [stackoverflow](http://stackoverflow.com/questions/14904814/nameerror-global-name-long-is-not-defined) where a people say `In Python 3.x, use int instead of long.` Is it a solution for this problem?

**Comment by chenzhekl** [comment]
In Python3, if the integer is within the range of int32 or int64 (depending on how you compiled the Python binary), it is the same as `int` in Python2. Once it exceeds the range of machine-native integers, it will be automatically converted to what is equal to `long` in Python2. The process is completely transparent, thus it is safe to just use `int(numImages)` in Python3.

**Comment by KeithYin** [comment]
@chenzhekl  i am sorry, maybe i didn't make it clear, i modified the comment.
 when i changed the`torchvision.utils` source code `long` to `int`, my code run correctly.

**Comment by apaszke** [comment]
Fixed in pytorch/vision@de5dcb9. In the future please report `torchvision` related bugs in its repository, not in the core one. Thanks!

**Comment by dthboyd** [comment]
when i changed thetorchvision.utils source code long to int

how?

**Comment by SoloSquadd** [comment]
for x in range(int(jum)):
NameError: name 'jum' is not defined
