### ISSUE TITLE
import torch 

### ISSUE THREAD

**Issue by PioyPioy** [pytorch/pytorch#116613]
What do I need to fix?

```
C:\Users\Inc_J\Downloads>whisper "TOOL.mp3"
Traceback (most recent call last):
  File "c:\users\inc_j\appdata\local\programs\python\python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\inc_j\appdata\local\programs\python\python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Inc_J\AppData\Local\Programs\Python\Python310\Scripts\whisper.exe\__main__.py", line 4, in <module>
  File "c:\users\inc_j\appdata\local\programs\python\python310\lib\site-packages\whisper\__init__.py", line 8, in <module>
    import torch
  File "c:\users\inc_j\appdata\local\programs\python\python310\lib\site-packages\torch\__init__.py", line 1120, in <module>
    from .storage import _StorageBase, TypedStorage, _LegacyStorage, UntypedStorage, _warn_typed_storage_removal
  File "c:\users\inc_j\appdata\local\programs\python\python310\lib\site-packages\torch\storage.py", line 310, in <module>
    class UntypedStorage(torch._C.StorageBase, _StorageBase):
TypeError: 'torch._C._TensorMeta' object is not iterable
```

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by malfet** [comment]
Please provide some details on how you've installed PyTorch (and/or run `python3 -mtorch.utils.collect_env` and post output here)

Also, have you tried asking the question on https://discuss.pytorch.org/

**Comment by PioyPioy** [comment]
Thanks for quick response.

C:\Users\Inc_J\OneDrive\Desktop\whisper>python3 -mtorch.utils.collect_env
Collecting environment information...
PyTorch version: 2.1.2+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
Nvidia driver version: 546.33
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2304
DeviceID=CPU0
Family=198
L2CacheSize=10240
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2304
Name=11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] torch==2.1.2
[conda] Could not collect

**Comment by malfet** [comment]
@PioyPioy looks like you have two versions of python installed on your system: python-3.11 and python-3.10
And I still have no clue how you've installed PyTorch, so I can not really help you with anything
Can you please try the instructions from https://pytorch.org/get-started/locally/ and if installation fails file a new issue or start discussion on the forum.

**Comment by PioyPioy** [comment]
Solved. Thanks everyone
