### ISSUE TITLE
Compilation Error with AVX-512, No Such Instruction: `vpdpbusd`

### ISSUE THREAD

**Issue by yewentao256** [pytorch/pytorch#116600]
### 🐛 Describe the bug

I am encountering a compilation error while building PyTorch from source.

```bash
/mnt/cache/share/platform/dep/gcc-10.2/bin/gcc -DFXDIV_USE_INLINE_ASSEMBLY=0 -DXNN_ENABLE_ARM_BF16=0 -DXNN_ENABLE_ARM_DOTPROD=1 -DXNN_ENABLE_ARM_FP16_SCALAR=1 -DXNN_ENABLE_ARM_FP16_VECTOR=1 -DXNN_ENABLE_ARM_I8MM=0 -DXNN_ENABLE_ASSEMBLY=1 -DXNN_ENABLE_AVXVNNI=0 -DXNN_ENABLE_CPUINFO=1 -DXNN_ENABLE_DWCONV_MULTIPASS=0 -DXNN_ENABLE_GEMM_M_SPECIALIZATION=1 -DXNN_ENABLE_JIT=0 -DXNN_ENABLE_MEMOPT=1 -DXNN_ENABLE_RISCV_VECTOR=1 -DXNN_ENABLE_SPARSE=1 -I/mnt/lustre/yewentao/pytorch/third_party/XNNPACK/src -I/mnt/lustre/yewentao/pytorch/third_party/pthreadpool/include -I/mnt/lustre/yewentao/pytorch/third_party/FXdiv/include -I/mnt/lustre/yewentao/pytorch/third_party/FP16/include -isystem /mnt/lustre/yewentao/pytorch/third_party/protobuf/src -isystem /mnt/lustre/yewentao/pytorch/third_party/gemmlowp -isystem /mnt/lustre/yewentao/pytorch/third_party/neon2sse -g -std=c99 -fPIC -Wno-psabi -pthread  -mavx512f -mavx512cd -mavx512bw -mavx512dq -mavx512vl -mavx512vnni -MD -MT confu-deps/XNNPACK/CMakeFiles/microkernels-all.dir/src/qs8-gemm/gen/qs8-gemm-5x16c4-minmax-fp32-avx512vnni-prfm.c.o -MF confu-deps/XNNPACK/CMakeFiles/microkernels-all.dir/src/qs8-gemm/gen/qs8-gemm-5x16c4-minmax-fp32-avx512vnni-prfm.c.o.d -o confu-deps/XNNPACK/CMakeFiles/microkernels-all.dir/src/qs8-gemm/gen/qs8-gemm-5x16c4-minmax-fp32-avx512vnni-prfm.c.o -c /mnt/lustre/yewentao/pytorch/third_party/XNNPACK/src/qs8-gemm/gen/qs8-gemm-5x16c4-minmax-fp32-avx512vnni-prfm.c
/tmp/ccWVNDbE.s: Assembler messages:
/tmp/ccWVNDbE.s:665: Error: no such instruction: `vpdpbusd %zmm2,%zmm1,%zmm0'
/tmp/ccWVNDbE.s:682: Error: no such instruction: `vpdpbusd %zmm2,%zmm1,%zmm0'
/tmp/ccWVNDbE.s:699: Error: no such instruction: `vpdpbusd %zmm2,%zmm1,%zmm0'
/tmp/ccWVNDbE.s:716: Error: no such instruction: `vpdpbusd %zmm2,%zmm1,%zmm0'
/tmp/ccWVNDbE.s:733: Error: no such instruction: `vpdpbusd %zmm2,%zmm1,%zmm0'
```

Given that the hardware and compiler should support AVX-512 instructions, I'm puzzled as to why this error is occurring. I would appreciate any insights or suggestions on how to troubleshoot and resolve this issue.

### Versions

Pytorch git commit:

```bash
commit 8173d98c575034916f1513ba6d1afa7b19352fe5
Author: Jerry Zhang <jerryzh168@gmail.com>
Date:   Thu Dec 28 09:59:06 2023 -0800
```

Compile command: 

```bash
DEBUG=1 python setup.py develop
```

Here is the information I tried to fetch: (`python collect_env.py` can not run since the PyTorch is not installed)
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.17

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-693.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 525.85.12
cuDNN version: /usr/local/cuda-9.0/lib64/libcudnn.so.7.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 48
On-line CPU(s) list: 0-47
Thread(s) per core: 2
Core(s) per socket: 12
Socket(s): 2
NUMA node(s): 2
Vendor ID: GenuineIntel
CPU family: 6
Model: 85
Model name: Intel(R) Xeon(R) Gold 6146 CPU @ 3.20GHz
Stepping: 4
CPU MHz: 3200.000
BogoMIPS: 6400.00
Virtualization: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 1024K
L3 cache: 25344K
NUMA node0 CPU(s): 0-11,24-35
NUMA node1 CPU(s): 12-23,36-47
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts

**Comment by KimBioInfoStudio** [comment]
https://www.felixcloutier.com/x86/vpdpbusd

**Comment by lezcano** [comment]
It looks like it's building with  `-mavx512vnni`, but your processor does not support the AVX512vnni extension. Note that this error happens when building XNNPACK (https://github.com/google/XNNPACK), so it's likely that the error does is coming from XNNPACK itself. Would you mind opening an issue in their repo?

**Comment by lezcano** [comment]
As a side note, note that you can avoid building `XNNPACK` if you don't intend to use quantisation by using the flag `USE_XNNPACK=0`. You can have a look at some useful flags we use at Quansight to build PyTorch at https://github.com/Quansight/torch-build/blob/main/torch-common.sh

**Comment by mingfeima** [comment]
@jingxu10 could you please help track this issue ?

**Comment by yewentao256** [comment]
> but your processor does not support the AVX512vnni extension.

Yes, I think this is the main reason why I can't compile the XNNPACK, thanks a lot! @lezcano

**Comment by yewentao256** [comment]
> Would you mind opening an issue in their repo?

https://github.com/google/XNNPACK/issues/5892

I've opened one issue in XNNPACK's repository, thanks again for your help!

**Comment by alankelly** [comment]
> but your processor does not support the AVX512vnni extension.

Compilation does not depend on your processor. On x86, XNNPack is compiled for all variants and and the optimal is selected at runtime based on your hardware. This is a compilation error.

**Comment by yewentao256** [comment]
@alankelly  Thanks for reply.

However, is GCC 10.2 too old to compile XNNPack? If it is, could you please advise on which version would be suitable for compilation? I haven't been able to find any specific GCC version requirements in XNNPack's documentation

**Comment by UsmanAfzaal** [comment]
I am facing a similar issue while trying to build it.

gcc: error: unrecognized command line option ‘-mavx512vnni’; did you mean ‘-mavx5124vnniw’?

**Comment by lezcano** [comment]
The minimum gcc version required to compile PyTorch ATM is gcc9

**Comment by alankelly** [comment]
I think it's your assembler which is misbehaving, Can you please paste the output of `as --version`?

**Comment by yewentao256** [comment]
> Can you please paste the output of `as --version`?

```bash
gcc --version
gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```



> Did you build gcc yourself?

Yes, so is this the main reason for the compilation error?

**Comment by alankelly** [comment]
Your gcc version is fine, but the assembler version on CentOS 7 is too old so does not recognise vnni instructions. You would also have to build your own as version > 2.29. Current version is 2.41.

**Comment by yewentao256** [comment]
Got it, thanks~ @alankelly
