### ISSUE TITLE
Seq2Seq Model Training on MacBook Pro M3 MAX with MPS Results in NaN Loss

### ISSUE THREAD

**Issue by snrazavi** [pytorch/pytorch#116601]
#### Description:
I am encountering an issue while training a Seq2Seq model for English-to-French translation using the Multi30K dataset. The model has been successfully trained on a Windows system with an RTX 3080 GPU, and it also works correctly on a MacBook Pro M3 MAX when using the CPU. However, when I attempt to utilize MPS (Metal Performance Shaders) for faster training on the MacBook Pro, I encounter a problem where the loss value turns into NaN after a few batches in the first epoch.

#### Steps to Reproduce:
1. Train the Seq2Seq model on a Windows system with an RTX 3080 GPU (successful training, no issues).
2. Train the same model on a MacBook Pro M3 MAX using the CPU (successful training, no issues).
3. Train the model on the MacBook Pro M3 MAX using MPS for faster training.
- The training starts normally, processing a few batches successfully.
- After a few batches in the first epoch, the loss value turns NaN.

#### Expected Behavior:
The model should train without the loss value turning into NaN, similar to how it successfully trains on the Windows GPU and the MacBook Pro CPU.

#### Actual Behavior:
When training with MPS on the MacBook Pro M3 MAX, the loss value becomes NaN after a few batches in the first epoch.

```python
if torch.backends.mps.is_available():
    device = torch.device('mps')
```

### Versions

PyTorch version: 2.1.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.2.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] (64-bit runtime)
Python platform: macOS-14.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.2
[pip3] torch==2.1.2
[pip3] torchaudio==2.1.2
[pip3] torchdata==0.7.1
[pip3] torchtext==0.16.2
[pip3] torchvision==0.16.2
[conda] No relevant packages

cc @ezyang @gchanan @zou3519 @kadeng @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by stadbern** [comment]
Hello,
similar problem here using code running with CUDA, but producing NaNs when using MPS backend.

CPU : M3 pro
pytorch                   2.3.0.dev20231228
torchaudio                2.2.0.dev20231228
torchvision               0.18.0.dev20231228
accelerate                0.25.0

**Comment by kulinseth** [comment]
@snrazavi , thanks for reporting the issue. Can you point to the code snippet you are using to repro this issue ?

**Comment by snrazavi** [comment]
Certainly! I developed it independently for educational purposes. While it's not publicly available, I'm open to sharing it with you privately. Please let me know the best way to send it to you or if there are specific aspects of the code you're particularly interested in. Looking forward to collaborating!

**Comment by malfet** [comment]
> Certainly! I developed it independently for educational purposes. While it's not publicly available, I'm open to sharing it with you privately. 

Hmm, I thought you are using something like https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html

And does @stadbern have access to the same codebase or something else?

Accessing non-publicly is somewhat problematic, as lots of people here are working for a commercial company and that would likely entail some lengthly approval process. Perhaps you can spend time narrowing down the training loop to a smaller example?

**Comment by snrazavi** [comment]
@sidsrinivasan Thanks for the reply. I will try to run the code and keep you posted.

As the error during training occurs when calling model forward method, I think it might be useful to share only the code for the model. Please notice again that the same code runs without any changes on both cpu and cuda and not only that, the translation results are good.

Here is the sample output for your reference: Please note that how the loss value becomes "nan" after 6th batch

Training 01:   0%|          | 0/454 [00:00<?, ?it/s]2024-01-06 01:41:17 EncDecTrainer [DEBUG] 
Batch 0 loss: 8.766
Training 01:   0%|          | 1/454 [00:00<05:42,  1.32it/s, loss=8.77]2024-01-06 01:41:18 EncDecTrainer [DEBUG] 
Batch 1 loss: 8.418
Training 01:   0%|          | 2/454 [00:01<03:38,  2.07it/s, loss=8.42]2024-01-06 01:41:18 EncDecTrainer [DEBUG] 
Batch 2 loss: 8.163
Training 01:   1%|          | 3/454 [00:01<02:54,  2.58it/s, loss=8.16]2024-01-06 01:41:18 EncDecTrainer [DEBUG] 
Batch 3 loss: 7.662
Training 01:   1%|          | 4/454 [00:01<02:53,  2.59it/s, loss=7.66]2024-01-06 01:41:19 EncDecTrainer [DEBUG] 
Batch 4 loss: 7.531
Training 01:   1%|          | 5/454 [00:02<02:45,  2.72it/s, loss=7.53]2024-01-06 01:41:19 EncDecTrainer [DEBUG] 
Batch 5 loss: 7.277
Training 01:   1%|▏         | 6/454 [00:02<02:27,  3.03it/s, loss=7.28]2024-01-06 01:41:19 EncDecTrainer [DEBUG] 
Batch 6 loss: 7.718
Training 01:   2%|▏         | 7/454 [00:02<02:14,  3.33it/s, loss=7.72]2024-01-06 01:41:19 EncDecTrainer [DEBUG] 
Batch 7 loss: nan
Training 01:   2%|▏         | 8/454 [00:02<02:08,  3.46it/s, loss=nan] 2024-01-06 01:41:20 EncDecTrainer [DEBUG] 
Batch 8 loss: nan
Training 01:   2%|▏         | 9/454 [00:03<02:08,  3.46it/s, loss=nan]2024-01-06 01:41:20 EncDecTrainer [DEBUG] 
Batch 9 loss: nan
Training 01:   2%|▏         | 10/454 [00:03<02:08,  3.47it/s, loss=nan]2024-01-06 01:41:20 EncDecTrainer [DEBUG] 
Batch 10 loss: nan
Training 01:   2%|▏         | 11/454 [00:03<02:22,  3.11it/s, loss=nan]2024-01-06 01:41:21 EncDecTrainer [DEBUG] 
Batch 11 loss: nan


And here is the model implementation: (I have removed all comments to make code shorter). please let me know if you need the training code as well.

```python
class Encoder(nn.Module):
    def __init__(self, input_dim, emb_dim, enc_hid_dim, dec_hid_dim, dropout):
        super().__init__()
        
        self.embedding = nn.Embedding(input_dim, emb_dim)
        self.rnn = nn.GRU(emb_dim, enc_hid_dim, bidirectional = True)
        self.fc = nn.Linear(enc_hid_dim * 2, dec_hid_dim)
        self.dropout = nn.Dropout(dropout)
        
    def forward(self, src):        
        embedded = self.dropout(self.embedding(src))        
        outputs, hidden = self.rnn(embedded)
        hidden = torch.tanh(self.fc(torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim = 1)))        
        return outputs, hidden
    

class Attention(nn.Module):
    def __init__(self, enc_hid_dim, dec_hid_dim):
        super().__init__()
        
        self.attn = nn.Linear((enc_hid_dim * 2) + dec_hid_dim, dec_hid_dim)
        self.v = nn.Linear(dec_hid_dim, 1, bias = False)
        
    def forward(self, hidden, encoder_outputs):
        batch_size = encoder_outputs.shape[1]
        src_len = encoder_outputs.shape[0]
        hidden = hidden.unsqueeze(1).repeat(1, src_len, 1)
        encoder_outputs = encoder_outputs.permute(1, 0, 2)
        energy = torch.tanh(self.attn(torch.cat((hidden, encoder_outputs), dim = 2))) 
        attention = self.v(energy).squeeze(2)
        return F.softmax(attention, dim=1)
    

class Decoder(nn.Module):
    def __init__(self, output_dim, emb_dim, enc_hid_dim, dec_hid_dim, dropout, attention):
        super().__init__()

        self.output_dim = output_dim
        self.attention = attention
        
        self.embedding = nn.Embedding(output_dim, emb_dim)
        self.rnn = nn.GRU((enc_hid_dim * 2) + emb_dim, dec_hid_dim)
        self.fc_out = nn.Linear((enc_hid_dim * 2) + dec_hid_dim + emb_dim, output_dim)
        self.dropout = nn.Dropout(dropout)
        
    def forward(self, input, hidden, encoder_outputs):
        input = input.unsqueeze(0)
        embedded = self.dropout(self.embedding(input))
        a = self.attention(hidden, encoder_outputs)
        a = a.unsqueeze(1)
        encoder_outputs = encoder_outputs.permute(1, 0, 2)
        weighted = torch.bmm(a, encoder_outputs)
        weighted = weighted.permute(1, 0, 2)
        rnn_input = torch.cat((embedded, weighted), dim = 2)
        output, hidden = self.rnn(rnn_input, hidden.unsqueeze(0))
        # assert (output == hidden).all()
        embedded = embedded.squeeze(0)
        output = output.squeeze(0)
        weighted = weighted.squeeze(0)
        prediction = self.fc_out(torch.cat((output, weighted, embedded), dim = 1))
        return prediction, hidden.squeeze(0)
    

class Seq2Seq(nn.Module):
    def __init__(self, encoder, decoder, device):
        super().__init__()
        
        self.encoder = encoder
        self.decoder = decoder
        self.device = device
        
    def forward(self, src, trg, teacher_forcing_ratio = 0.5):
        src = src.permute(1, 0)
        trg = trg.permute(1, 0)
        
        batch_size = src.shape[1]
        trg_len = trg.shape[0]
        trg_vocab_size = self.decoder.output_dim
        outputs = torch.zeros(trg_len, batch_size, trg_vocab_size).to(self.device)
       encoder_outputs, hidden = self.encoder(src)
                
        input = trg[0, :]
        for t in range(1, trg_len):
            output, hidden = self.decoder(input, hidden, encoder_outputs)
            outputs[t] = output
            teacher_force = random.random() < teacher_forcing_ratio
            top_one = output.argmax(1) 
            input = trg[t] if random.random() < teacher_forcing_ratio else top_one

        return outputs
```

**Comment by snrazavi** [comment]
@stadbern  I have more than enough memory (48 Gig of URAM), so the issue is definitely not 'out of memory'.

**Comment by malfet** [comment]
Interesting, I can reproduce it on the 2.1.2 release, but not on the latest nightly, trying 2.2.0 release candidate now

**Comment by malfet** [comment]
@snrazavi can you please confirm that your use-case works on 2.2.0 release candidate? 
Removing high-pri for now as looks like all usecases are fixed

**Comment by snrazavi** [comment]
@malfet Sure, I will try 2.2.0 release and keep you posted asap.

**Comment by kulinseth** [comment]
cc @jhavukainen , can you please check if this works for you ?

**Comment by jan-engelmann** [comment]
Same problem here:
https://discourse.scverse.org/t/macbook-m1-m2-mps-acceleration-with-scvi/2075

It occured for me with torch 2.2.0 on mps aswell

**Comment by moshesimon** [comment]
https://github.com/sktime/pytorch-forecasting/pull/1725

might have something to do with this
