### ISSUE TITLE
Cannot resize_as_ to a tensor with a different dtype

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#11665]
```
>>> torch.randn(3).resize_as_(torch.ones(2, dtype=torch.uint8))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected object of scalar type Float but got scalar type Byte for argument #2 'the_template'

```

This doesn't make much sense. We should relax `checked_tensor_unwrap` for `resize_as_`.

**Comment by vadimkantorov** [comment]
I'll close older https://github.com/pytorch/pytorch/issues/5049 in favor of this issue.

**Comment by saeedseyyedi** [comment]
I have the same issue getting this error message, did you find any solution?

**Comment by SsnL** [comment]
@saeedseyyedi Hmm so if you are using `resize_` or `resize_as_` in a user code, you are probably doing something wrong. Look into `reshape`.

**Comment by SsnL** [comment]
fixed in https://github.com/pytorch/pytorch/pull/23027 by @VitalyFedyunin
