### ISSUE TITLE
TorchInductor should preserve eager layouts for user-defined kernels

### ISSUE THREAD

**Issue by parthmannan** [pytorch/pytorch#116715]
### 🐛 Describe the bug

The backward pass generated by TorchInductor does not follow expected behavior with channels_last memory format. The input to the backward pass (tangents_1 below) is not sent with channels_last format.

Here's the `output_code.py` call function for the backward pass
```
def call(args):
    primals_1, gt, tangents_1 = args
    args.clear()
    assert_size_stride(primals_1, (1, 320, 128, 128), (5242880, 1, 40960, 320))
    assert_size_stride(gt, (1, 320, 128, 128), (5242880, 1, 40960, 320))
    assert_size_stride(tangents_1, (1, 320, 128, 128), (5242880, 16384, 128, 1))
    with torch.cuda._DeviceGuard(0):
        torch.cuda.set_device(0)
        buf0 = empty((1, 320, 128, 128), device='cuda', dtype=torch.float32)
        # Source Nodes: [out], Original ATen: [aten.gelu, aten.gelu_backward, aten.native_dropout_backward]
        stream0 = get_raw_stream(0)
        triton_poi_fused_gelu_gelu_backward_native_dropout_backward_0.run(tangents_1, gt, primals_1, buf0, 320, 16384, grid=grid(320, 16384), stream=stream0)
        del gt
        del primals_1
        del tangents_1
        return (buf0, )
```
Here's also a reproducible script for this

```
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.fx.experimental.proxy_tensor import make_fx
import torch.nn.init as init
from torch import Tensor
from torch.nn.parameter import Parameter

class Block(nn.Module):
    def __init__(
        self,
    ):
        super().__init__()

        self.in_layers = nn.Sequential(
            nn.Dropout(p=0.1),
        )
        
    def forward(self, x):
        out = F.gelu(x)
        out = self.in_layers(out)

        return out

model = Block()
model = model.to("cuda").to(memory_format=torch.channels_last)

net = torch.compile(model, fullgraph=True)

num_batch = 20
profile_batch = 15

for i in range(num_batch):

    input_t = torch.randn([1, 320, 128, 128], dtype=torch.float32, device='cuda', requires_grad=True)
    input_t = input_t.to(memory_format=torch.channels_last)

    target_t = torch.ones_like(input_t)

    if i == profile_batch:
        torch.cuda.cudart().cudaProfilerStart()
    
    out = net(input_t)
    out.backward(target_t)

    if i == profile_batch:
        torch.cuda.cudart().cudaProfilerStop()
```

### Versions

PyTorch version: 2.3.0a0+git95a86ed                                                                                                                                                           

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by lezcano** [comment]
Just to make sure I understand, this is a performance issue, but not a correctness issue, is it?

ccing @vfdev-5, although he's on PTO until next week

**Comment by parthmannan** [comment]
@lezcano This is a correctness issue for me unfortunately. I have a custom kernel that expects tensors in channels_last layout that I am trying to register with Inductor. While the kernel gets registered correctly, it does not receive the correct input and fails to run.
It works fine without `torch.compile` however

**Comment by lezcano** [comment]
You might want to use a helper function like
https://github.com/pytorch/pytorch/blob/91bbcf8c718ff245ec85e33874dc4c1a1a28c4f3/torch/_inductor/lowering.py#L2018-L2022
These are used in ExternKernels (templates) that have particular stride requirements.

**Comment by parthmannan** [comment]
Aah I see. The helper function should fix things for me then. How do I use this `require_channels_last` function? For example, in the above reproducible script, where would this be called? Thanks!

**Comment by lezcano** [comment]
You need to call it at the lowering level, whenever you are lowering your function to the inductor IR, which I suppose you are doing as an ExternKernel.

**Comment by lezcano** [comment]
Here's a more up to date manual: https://dev-discuss.pytorch.org/t/guide-getting-c-custom-ops-to-work-with-torch-compile/
Alas, I don't think we currently support ops that just work for some strides and not others.
cc @zou3519

**Comment by parthmannan** [comment]
Oh I see :(
Hopefully this serves as a feature request as well.

**Comment by lezcano** [comment]
Let's wait for Richard's response. If we can indeed not do this, we can turn this issue into an feature request, yep.

**Comment by zou3519** [comment]
custom ops are supposed to handle inputs with all strides gracefully. For this particular op, it sounds like you want to add a check that the inputs are channels last. A workaround is for the op to coerce its inputs to channels last before pass it into the kernel.

I'm not sure if having an API to ask inductor to force inputs to an op into channels-last format is something we want. Deferring to the inductor folks on this.

**Comment by lezcano** [comment]
We already have that internally, I think it would make sense to expose it.  cc @jansel

**Comment by ezyang** [comment]
The main benefit to letting inductor know is that it could prevent an unnecessary copy, if inductor can choose to output the tensor to the "right" format directly. But @parthmannan it's at least possible to try the easy version by just slapping a `contiguous(

**Comment by jansel** [comment]
You should be able to fix this by adding your kernel to the `need_fixed_layout` list:
https://github.com/pytorch/pytorch/blob/4b74bb6c3428c111bf0c823aa6db1fa58fcf82c2/torch/_inductor/graph.py#L923-L926

Which will force inductor to match eager layouts.

Perhaps we should do this automatically for user-defined kernels.

**Comment by parthmannan** [comment]
Thanks a lot for the excellent suggestions here folks.
`need_fixed_layout` looks very useful. @jansel Is this exposed and modifiable to the user model code or requires source code changes?
If not, forcing my kernel inputs to the right memory_format could be an option if the performance doesn't take a big hit.

**Comment by jansel** [comment]
There is not currently an API to modify it.

**Comment by zou3519** [comment]
Agree that we should have `need_fixed_layout` as the default for custom ops (or at least attempt to), because they are generally specialized to a specific layout.

@jansel what do you think of one of the following API ideas?
- Today, operators can have tags on them. We can add a `need_fixed_layout` tag; if an operator has this tag then inductor will process it as such.
- Some registration API from inductor, e.g. torch._inductor.require_fixed_layout(op)

**Comment by jansel** [comment]
I like the idea of moving `need_fixed_layout` to a tag.

If we make all custom ops (not in ops.aten.*) have a fixed layout then I don't think we need a registration API.

**Comment by jamesjwu** [comment]
With https://github.com/pytorch/pytorch/pull/117298, you can now add the tag torch._C.Tag.needs_fixed_stride_order to your custom op to make inductor preserve eager mode stride order when passing arguments to your custom operation. See the example in the test here: https://github.com/pytorch/pytorch/pull/117298/files#diff-809c39aeafb3acc92289f42a63e670a8719d4ce5627d5f88820142d80edf8d2aR8095-R8101
