### ISSUE TITLE
ignore cudnn when compiling pytorch with cudnn in PATH: "~/cudnn"

### ISSUE THREAD

**Issue by brisker** [pytorch/pytorch#1167]
ignore cudnn when compiling pytorch with cudnn in path: `~/cudnn`, how to compile with cudnn if my cudnn has to be in PATH:   `~/cudnn`  for some reason?  I have already `~/cudnn` in my bashrc  PATH

**Comment by apaszke** [comment]
Assuming that the library is in `~/cudnn/lib64/libcudnn.so`, headers are in `~/cudnn/include/cudnn.h`, and the `~` expands to `/home/brisker` (you need to verify these yourself), you can build pytorch like this:
```
export CUDNN_LIB_DIR=/home/brisker/cudnn/lib64
export CUDNN_INCLUDE_DIR=/home/brisker/cudnn/include
python setup.py install
```

In the future please ask questions [in the forums](discuss.pytorch.org). We're using GitHub issues for bug reports and feature requests only.

**Comment by brisker** [comment]
@apaszke  Thanks for reply so quickly!
