### ISSUE TITLE
capture_pre_autograd_graph does not capture descriptive node names (from module source code) 

### ISSUE THREAD

**Issue by rvijayc** [pytorch/pytorch#116719]
### 🐛 Describe the bug

I am using the workflow described in [PYTORCH 2.0 EXPORT POST TRAINING STATIC QUANTIZATION](https://pytorch.org/tutorials/prototype/pt2e_quant_ptq_static.html) to quantize and export a model to my own backend.

I am noticing the following difference between `capture_pre_autograd_graph` and `torch.export` - `capture_pre_autograd_graph` doesn't capture descriptive node names from the original module source code while `torch.export` does capture this information. The following is a minimal example that illustrates this:

```python
import torch
import torch.nn as nn
from torch._export import capture_pre_autograd_graph

# author a model.
class MLPNet(nn.Module):
    def __init__(self):
        super(MLPNet, self).__init__()
        self.fc1 = nn.Linear(64, 64)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(64, 32)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(32, 16)
        self.relu3 = nn.ReLU()
        self.fc4 = nn.Linear(16, 8)
        self.relu4 = nn.ReLU()
        
    def forward(self, x):
        layer1 = self.relu1(self.fc1(x))
        layer2 = self.relu2(self.fc2(layer1))
        layer3 = self.relu3(self.fc3(layer2))
        y      = self.relu4(self.fc4(layer3))
        return y
    
    def name(self):
        return "MLP"

model = MLPNet().eval()

# generate a uniform distribution of data.
n_batches = 100
x_in = torch.distributions.uniform.Uniform(-1, 1).sample([n_batches, 64, 64])

# export the module (this will annotate the graph with node names such as
# "fc1_weight", "fc1_bias", ...)
m_export = torch.export.export(model, (x_in[0,:],))
print('---------------')
print('torch.export():')
print('---------------')
m_export.module().graph.print_tabular()
print()

# this won't do any annotations and going forward with quantization will lose
# node annotations.
m_pre = capture_pre_autograd_graph(model, (x_in[0,:],))
print('-----------------------------')
print('capture_pre_autograd_graph():')
print('-----------------------------')
m_pre.graph.print_tabular()
```

A snipped output is provided below:

```
---------------
torch.export():
---------------
opcode         name        target              args                     kwargs
-------------  ----------  ------------------  -----------------------  --------
get_attr       fc1_weight  fc1_weight          ()                       {}
get_attr       fc1_bias    fc1_bias            ()                       {}
get_attr       fc4_weight  fc4_weight          ()                       {}
[ ... ]
get_attr       fc4_bias    fc4_bias            ()                       {}
placeholder    arg8_1      arg8_1              ()                       {}
call_function  t           aten.t.default      (fc1_weight,)            {}
call_function  addmm       aten.addmm.default  (fc1_bias, arg8_1, t)    {}
call_function  relu        aten.relu.default   (addmm,)                 {}
call_function  t_1         aten.t.default      (fc2_weight,)            {}
[ ... ]

-----------------------------
capture_pre_autograd_graph():
-----------------------------
opcode         name              target               args                                          kwargs
-------------  ----------------  -------------------  --------------------------------------------  --------
placeholder    arg0_1            arg0                 ()                                            {}
get_attr       _param_constant0  _param_constant0     ()                                            {}
get_attr       _param_constant1  _param_constant1     ()                                            {}
call_function  linear            aten.linear.default  (arg0_1, _param_constant0, _param_constant1)  {}
call_function  relu              aten.relu.default    (linear,)                                     {}
get_attr       _param_constant2  _param_constant2     ()                                            {}
[ ...]
```

It would be desirable to preserve descriptive names such as "fc1_weight", "fc1_bias" etc., in the exported model which can be used further downstream to aid in debugging the model on a HW target. As such, the names in the graph are `_param_constant0`, `_param_constant1` etc., which aren't very useful.

I have a couple of questions:

- Is there a way to change this behavior in `capture_pre_autograd_graph` to match the information level captured via `torch.export.export`?
- In `torch.export.export` would it be possible to capture the name the input variable (here, it is `x`) instead of `arg8_1` (which cannot be traced back to `x`.

### Versions

PyTorch version: 2.2.0a0+gitb4ce501
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: SUSE Linux Enterprise Server 12 SP5 (x86_64)
GCC version: (GCC) 8.2.0
Clang version: 4.0.0 (tags/RELEASE_401/final)
CMake version: version 3.26.4
Libc version: glibc-2.22

Versions of relevant libraries:
[pip3] executorch==0.1.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] onnx==1.14.0
[pip3] onnxruntime==1.15.1
[pip3] torch==2.2.0a0+gitb4ce501
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by angelayi** [comment]
> Is there a way to change this behavior in capture_pre_autograd_graph to match the information level captured via torch.export.export?

Yes, it's possible to match the information, but `capture_pre_autograd_graph` is just at temporary API. I would suggest trying out `torch.export._trace._export(model, (x_in[0,:],), pre_dispatch=True).module()` which is something we recently introduced which should produce a similar result as `capture_pre_autograd_graph`. Going forward, we expect to have `torch.export.export` return the result of `torch.export._trace._export(..., pre_dispatch=True)`, and to replace uses of `capture_pre_autograd_graph` with `torch.export.export`.

> In torch.export.export would it be possible to capture the name the input variable (here, it is x) instead of arg8_1 (which cannot be traced back to x.

I ran your code locally, and I seem to get `l_x_` instead of `arg8_1`.

```
graph():
    %fc1_weight : [num_users=1] = get_attr[target=fc1_weight]
    %fc1_bias : [num_users=1] = get_attr[target=fc1_bias]
    %fc2_weight : [num_users=1] = get_attr[target=fc2_weight]
    %fc2_bias : [num_users=1] = get_attr[target=fc2_bias]
    %fc3_weight : [num_users=1] = get_attr[target=fc3_weight]
    %fc3_bias : [num_users=1] = get_attr[target=fc3_bias]
    %fc4_weight : [num_users=1] = get_attr[target=fc4_weight]
    %fc4_bias : [num_users=1] = get_attr[target=fc4_bias]
    %l_x_ : [num_users=1] = placeholder[target=l_x_]
    %linear : [num_users=1] = call_function[target=torch.ops.aten.linear.default](args = (%l_x_, %fc1_weight, %fc1_bias), kwargs = {})
    %relu : [num_users=1] = call_function[target=torch.ops.aten.relu.default](args = (%linear,), kwargs = {})
    %linear_1 : [num_users=1] = call_function[target=torch.ops.aten.linear.default](args = (%relu, %fc2_weight, %fc2_bias), kwargs = {})
    %relu_1 : [num_users=1] = call_function[target=torch.ops.aten.relu.default](args = (%linear_1,), kwargs = {})
    %linear_2 : [num_users=1] = call_function[target=torch.ops.aten.linear.default](args = (%relu_1, %fc3_weight, %fc3_bias), kwargs = {})
    %relu_2 : [num_users=1] = call_function[target=torch.ops.aten.relu.default](args = (%linear_2,), kwargs = {})
    %linear_3 : [num_users=1] = call_function[target=torch.ops.aten.linear.default](args = (%relu_2, %fc4_weight, %fc4_bias), kwargs = {})
    %relu_3 : [num_users=1] = call_function[target=torch.ops.aten.relu.default](args = (%linear_3,), kwargs = {})
    return (relu_3,)
```

**Comment by rvijayc** [comment]
To confirm, after I upgraded to the latest version of PyTorch (2.3.0a0+gite3ca734), I am able to confirm both behaviors reported by Angela. Thanks for the help!
