### ISSUE TITLE
[dtensor][compile] assertion on placements causing trouble with torch.compile

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#116712]
See https://github.com/pytorch/pytorch/pull/116573

The underlying problem is that the DTensor is a plain TensorVariable in dynamo but TensorVariable does not give getattr(placements) a correctly desugared PlacementVariable.

One fix is that DTensor extend TensorVariable to DTensorVariable and desugar the DTensor logic inside.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @ezyang @anijain2305 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @rohan-varma @msaroufim @bdhirsh @zou3519 @aakhundov

**Comment by wconstab** [comment]
@yanboliang is this on your radar? not sure if this has come up in any of your debug efforts

**Comment by yanboliang** [comment]
It looks the current ```TensorVariable.var_getattr``` doesn't work well if it's a ```DTensor```. I think we support getting generic attribute already, probably hit some bugs when handling ```DTensor```. Do you have a repro? I can take a look.

**Comment by yanboliang** [comment]
Looking at this issue further, I think this root cause is when we are trying get generic attribute, we only access ```torch.Tensor``` rather than the subclass:
https://github.com/pytorch/pytorch/blob/ad75d9e2caba61566ade77471ca29934bca80391/torch/_dynamo/variables/tensor.py#L285

I can send a PR to fix this.

**Comment by masnesral** [comment]
@yanboliang I'm helping with old issue scrubbing this week. Do you still plan to work on this?
