### ISSUE TITLE
Add sdpa choice for  DeviceType::PrivateUse1

### ISSUE THREAD

**Issue by GuWei007** [pytorch/pytorch#116854]
### 🚀 The feature, motivation and pitch

We extend pytorch use DeviceType::PrivateUse1, currently we plan to support sdpa, please add sdpa choice for  DeviceType::PrivateUse1

https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/transformers/attention.cpp#L635

`if (query_.device().type() == DeviceType::CUDA
      || query_.device().type() == DeviceType::CPU
      || query_.device().type() == DeviceType::HIP){
    choice_int = _fused_sdp_choice_stub(query_.device().type(),
      query_, key, value, attn_mask_, dropout_p, is_causal, scale);
  }
`

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by drisspg** [comment]
which op would you like to support that this is blocking? All of the different sdpa native ops or just math?

That being said I think that this makes sense and we can do this but would like to learn a little more context
