### ISSUE TITLE
public_address was not set, DistributedDataParallel

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#11681]
Running with ``--nproc_per_node=1`` instead of ``--nproc_per_node=2``, I get this error...

## Issue description

```
$ python3 -m torch.distributed.launch --nproc_per_node=1 --master_port=1234 abcd.py
Traceback (most recent call last):
  File "abcd.py", line 9, in <module>
    torch.distributed.init_process_group(backend='nccl')
  File "/home/michaelp/.local/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
    group_name, rank)
RuntimeError: public_address was not set in config at /pytorch/torch/lib/THD/process_group/General.cpp:17
```

## Code example

```
import argparse
import torch

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--local_rank", type=int)
    args = parser.parse_args()

    torch.distributed.init_process_group(backend='nccl')
```

## System Info

Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB
GPU 2: Tesla P100-PCIE-16GB
GPU 3: Tesla P100-PCIE-16GB

Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.3

**Comment by ezyang** [comment]
Can reproduce this on HEAD with `torch.distributed.deprecated.init_process_group(backend='nccl')`

**Comment by mruberry** [comment]
Closed due to lack of response. Please reopen if you're still seeing this issue.
