### ISSUE TITLE
Add more documentation for fp8 types

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#116878]
### 📚 The doc issue

Once Ed's pr : https://github.com/pytorch/pytorch/pull/116804 lands we should add documentation on the supported fp8 types

cc @yanbing-j @vkuzo @albanD @kadeng

**Comment by Lymah123** [comment]
Hi @drisspg .
I'm working on this already.  I will soon submit PR for it.

**Comment by Lymah123** [comment]
> Hi @drisspg . I'm working on this already. I will soon submit PR for it.

@yanbing-j, @vkuzo , @albanD and @kadeng .

**Comment by Lymah123** [comment]
> > Hi @drisspg . I'm working on this already. I will soon submit PR for it.
> 
> @yanbing-j, @vkuzo , @albanD and @kadeng .

Can you explain more on this issue?

**Comment by albanD** [comment]
The goal here is to explain in detail what we expect to support and not support via the raw fp8_* dtypes in core and what is expected to be done through the float8_experimental repo

**Comment by vkuzo** [comment]
This should be done with https://github.com/pytorch/pytorch/pull/117375

@Lymah123 we had to take care of this internally, hope you understand
