### ISSUE TITLE
[PROFILER] Using microseconds on duration/timestamp will result in loss of precision

### ISSUE THREAD

**Issue by fwenguang** [pytorch/pytorch#116830]
### 🐛 Describe the bug

In PyTorch and Kineto, duration/timestamp are obtained(https://github.com/pytorch/kineto/blob/main/libkineto/src/CuptiActivity.h#L41, https://github.com/pytorch/pytorch/blob/main/torch/csrc/autograd/profiler_kineto.cpp#L776) using microseconds. When converting from nanoseconds to microseconds, there can be a loss of precision. This can lead to significant loss in cases where a large number of events are captured. Is it possible to use nanoseconds? I think nanoseconds is better.

### Versions

latest

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by sraikund16** [comment]
Added profiler implmentation here https://github.com/pytorch/pytorch/pull/123650
