### ISSUE TITLE
[export] Cannot perform inference if the ExportedProgram has weighted layers and custom ops

### ISSUE THREAD

**Issue by peri044** [pytorch/pytorch#116831]
### 🐛 Describe the bug

1) The graph has a conv node in pytorch and a TensorRT node. The conv node has weight and bias lifted as placeholders. Hence we are seeing this runtime error of mismatch in the number of inputs. 

Error message: 
```py
_check_input_constraints_for_graph(
  File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/_export/utils.py", line 48, in _check_input_constraints_for_graph
    check(
  File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/_export/utils.py", line 40, in check
    raise RuntimeError(msg)
RuntimeError: Unexpected number of inputs (expected 3, got 1)
```

2) If we unlift these parameters (i.e `conv_weight` and `conv_bias` are registered as `get_attr` nodes), there's a different error `GraphModule does not contain attribute conv_weight`
Reason: 
This is because - syntax error occurs in [_create_graph_module_for_export](https://github.com/pytorch/pytorch/blob/main/torch/_export/exported_program.py#L57) and hence the resulting `gm` does not have these attributes. 

Steps to reproduce: 
Install the nightly version of Torch-TRT 
```
pip install --pre torch-tensorrt  --extra-index-url https://download.pytorch.org/whl/nightly/cu121
```

Run the following script to reproduce the error 
```py
import torch
import torch_tensorrt
import unittest

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = torch.nn.Conv2d(3, 16, 3, stride=1, bias=True)
        self.relu = torch.nn.ReLU()

    def forward(self, x):
        conv = self.conv(x)
        relu = self.relu(conv)
        mul = relu * 0.5
        return mul

input = torch.randn((1, 3, 224, 224), dtype=torch.float).to("cuda")
model = MyModule().eval().cuda()

compile_spec = {
        "inputs": [
            torch_tensorrt.Input(
                input.shape, dtype=torch.float, format=torch.contiguous_format
            )
        ],
        "ir": "dynamo",
        "min_block_size": 1,
        "torch_executed_ops": {"torch.ops.aten.convolution.default"},
    }

exp_program = torch_tensorrt.dynamo.trace(model, **compile_spec)
trt_gm = torch_tensorrt.dynamo.compile(exp_program, **compile_spec)
trt_exp_program = torch_tensorrt.dynamo.export(trt_gm, [input], ir="exported_program")

torch.export.save(trt_exp_program, "/tmp/trt.ep")
deser_trt_exp_program = torch.export.load("/tmp/trt.ep")
outputs_pyt = model(input)
outputs_trt = trt_exp_program(input)
```

### Versions

[pip3] mypy==1.8.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.3
[pip3] pytorch-triton==2.2.0+e28a256d71
[pip3] torch==2.3.0.dev20240103+cu121
[pip3] torch-tensorrt==2.2.0.dev20240104+cu121
[pip3] torchvision==0.18.0.dev20240103+cu121

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by angelayi** [comment]
I'm having trouble installing/importing tensorrt so I will first ask some initial questions:

> The graph has a conv node in pytorch and a TensorRT node. The conv node has weight and bias lifted as placeholders. Hence we are seeing this runtime error of mismatch in the number of inputs.

Do you mind providing some more information (ex. more of the stacktrace, a printout of the graph before/after you partition to TRT)? It's not clear to me where the error is happening. I suspect that the graph signature is missing information.

> If we unlift these parameters (i.e conv_weight and conv_bias are registered as get_attr nodes), there's a different error GraphModule does not contain attribute conv_weight

The syntax error in [_create_graph_module_for_export](https://github.com/pytorch/pytorch/blob/main/torch/_export/exported_program.py#L57) is expected because of the ICudaEngine object in the graph. But the root should contain the necessary information...will try to dig into this.

**Comment by angelayi** [comment]
> 1. Since they are lifted and registered as placeholders, the graph is expecting 3 inputs to be provided during inference and hence results in the error

Are you using the graph module directly or using the exported program? The exported program will store the value for conv_weight and conv_bias, so maybe you're accidentally tossing those values. 

> 2. If I don't lift them, creation of exported program fails due to the second issue mentioned in the bug description.

This should have a different graph compared to the unlifted one right? Your printout looks like the attrs are lifted, so I assume that's a printout of the graph for #1. 

> Does pip install tensorrt work for you

pip install works, but when I import it, I get the following :/ : 
```
ImportError: /home/angelayi/.conda/envs/pytorch10/lib/python3.10/site-packages/torch_tensorrt/lib/libtorchtrt.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs
```

**Comment by narendasan** [comment]
Are you pip installing tensorrt or torch-tensorrt?

**Comment by angelayi** [comment]
I installed the torch-tensorrt nightlies, and tensorrt:
```
tensorrt                 8.6.1.post1
torch                    2.3.0.dev20240109+cu121
torch-tensorrt           2.2.0.dev20240105+cu121
```
