### ISSUE TITLE
Better unittest isolation for global state

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#116978]
## Context

I've been working on getting the Dynamo tests to reset the Dynamo state before and after each unittest, otherwise, the state from one test affects subsequent tests, leading to unexpected behavior.

However, Dynamo is not the only place where we have global state. We've ran into situations in the past where changing e.g. the global default dtype in one test had a downstream effect on other tests.

Can we make unittests better by better isolating them somehow?

## Pitch

Some ideas:
- One naive way to do this is to run each test in its own process, but this is probably not feasible due to the amount of overhead it adds to each test.
- Another idea is to have some centralized place where "all pytorch state" is kept and reset this state before and after each test runs.
- Linters for abuse of APIs that modify global state? For example, instead of using torch.set_default_dtype, we should use a context-manager version (if we have one) so it's clear the global state gets cleaned up. This would still require us to identify all of the APIs that do modify global state and put them somewhere.

cc @ZainRizvi @kit1980 @huydhn @clee2000 @janeyx99, @jbschlosser, @pytorch/pytorch-dev-infra for ideas

**Comment by clee2000** [comment]
Here's another tracking issue for tests that modify global state and cause other tests to fail https://github.com/pytorch/pytorch/issues/110295 for additional things to look out for.

The overhead for running each test in its own process is around 2s per test

**Comment by PaliC** [comment]
Closed in favor of tracking this through https://github.com/pytorch/pytorch/issues/110295
