### ISSUE TITLE
make install error,python setup.py install error

### ISSUE THREAD

**Issue by DetectionIIT** [pytorch/pytorch#11690]
when performing "make install", error is produced. I use cuda8,cudnn6,gcc5.4.0
please tell me the whether GCC version is correct or not,and how to solve this error.
the path is blow:
export LD_LIBRARY_PATH=/usr/lib:/usr/lib/x86_64-linux-gnu

[ 97%] Linking CXX executable ../bin/db_throughput
CMakeFiles/db_throughput.dir/db_throughput.cc.o: In function `_GLOBAL__sub_I_db_throughput.cc':
db_throughput.cc:(.text.startup+0xde): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
db_throughput.cc:(.text.startup+0x1a3): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
../lib/libcaffe2.so: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
../lib/libcaffe2.so: undefined reference to `google::SetUsageMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libcaffe2.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
/disk1/g201708021059/gg/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/db_throughput] Error 1
make[1]: *** [binaries/CMakeFiles/db_throughput.dir/all] Error 2
make: *** [all] Error 2

when  I according to website with new method and got the error blew:
python setup.py install

[ 87%] Linking CXX executable ../bin/integer_divider_test
/usr/bin/ld: warning: libmklml_intel.so, needed by //disk1/g201708021059/anaconda3/envs/py27-3/lib/libmkldnn.so.0, not found (try using -rpath or -rpath-link)
//disk1/g201708021059/anaconda3/envs/py27-3/lib/libmkldnn.so.0: undefined reference to `cblas_gemm_s8u8s32'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/integer_divider_test] Error 1
make[1]: *** [caffe2/CMakeFiles/integer_divider_test.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn caffe2 libshm gloo THD c10d'

If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by zou3519** [comment]
What are you trying to install?

**Comment by emmra** [comment]
As you say, in the pytorch file




| |
郭伟
邮箱：guowei3158@126.com
|

签名由 网易邮箱大师 定制

On 09/18/2018 01:46, Richard Zou wrote:

What are you trying to install?

**Comment by emmra** [comment]
with "python setup.py install“ to install pytorch

**Comment by pjh5** [comment]
Try installing gflags. It looks like you have leveldb on your system, which requires gflags. Or you can turn leveldb off here https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L86 .

**Comment by mruberry** [comment]
Closing due to age. @DetectionIIT if this issue is still occurring please file a new issue for us to review.
