### ISSUE TITLE
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (version 3.7.4.3 fails, 4.9 works)

### ISSUE THREAD

**Issue by alex77g2** [pytorch/pytorch#116945]
### 🐛 Describe the bug
There seems to be an (easy solvable) dependency issue when installing torch 2 on python 3.9.

pip3 install torch # fine (no warnings/conflicts or errors)

import torch # fails : ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/usr/lib/python3/dist-packages/typing_extensions.py)

pip3 install typing_extensions --upgrade # solves it  (version 3.7.4.3 to 4.9)

Expectation: dependencies should be checked during pip install
```
host:~/solver1$ python3 mnistBenchmark.py -e 1
Traceback (most recent call last):
  File "/home/mi/solver1/mnistBenchmark.py", line 5, in <module>
    import torch
  File "/home/mi/.local/lib/python3.9/site-packages/torch/__init__.py", line 1429, in <module>
    from torch import optim as optim
  File "/home/mi/.local/lib/python3.9/site-packages/torch/optim/__init__.py", line 8, in <module>
    from .adadelta import Adadelta
  File "/home/mi/.local/lib/python3.9/site-packages/torch/optim/adadelta.py", line 4, in <module>
    from .optimizer import (Optimizer, _use_grad_for_differentiable, _default_to_fused_or_foreach,
  File "/home/mi/.local/lib/python3.9/site-packages/torch/optim/optimizer.py", line 23, in <module>
    from typing_extensions import ParamSpec, Self, TypeAlias
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/usr/lib/python3/dist-packages/typing_extensions.py)
host:~/solver1$ pip3 install typing_extensions
Requirement already satisfied: typing_extensions in /usr/lib/python3/dist-packages (3.7.4.3)
host:~/solver1$ pip3 install typing_extensions --upgrade
Requirement already satisfied: typing_extensions in /usr/lib/python3/dist-packages (3.7.4.3)
Collecting typing_extensions
  Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Installing collected packages: typing-extensions
Successfully installed typing-extensions-4.9.0
host:~/solver1$ python3 mnistBenchmark.py --help
# works fine now
```

### Versions

Linux hostname 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
torch in /home/mi/.local/lib/python3.9/site-packages (2.1.2)
python 3.9  # I know its old, but thats not the point here.

**Comment by Skylion007** [comment]
So we may need to bump our minimum version of typing_extension it seems like.

**Comment by Skylion007** [comment]
Wait, this is already violating the latest requirements: https://github.com/pytorch/pytorch/blob/4b74bb6c3428c111bf0c823aa6db1fa58fcf82c2/requirements.txt#L11 it requires 4.8 as a minimum now for typing_extension.

**Comment by alex77g2** [comment]
Thanks
