### ISSUE TITLE
`serialized_state_dict.json` is a Zip file with `.json` extension

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#116949]
### 🐛 Describe the bug

Following [torch.export](https://pytorch.org/docs/stable/export.html) documentation, the resulting `.pt2` file contains a Zip file with incorrect `.json` extension.

More generally, really large nested Zip files might become problematic for tooling. Is there some context or would it be possible to store  `serialized_exported_program.json` in a single regular `torch.load` container along with/without the `state_dict`?

@voznesenskym @angelayi @zhxchen17

### Versions

PyTorch version: 2.1.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.2.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.1
Libc version: N/A

Python version: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] (64-bit runtime)
Python platform: macOS-14.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2

Versions of relevant libraries:
[pip3] executorch==0.1.2
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.3
[pip3] onnx==1.15.0
[pip3] onnx2json==2.0.4
[pip3] onnxruntime==1.15.0
[pip3] onnxscript==0.1.0.dev20231004
[pip3] torch==2.1.2
[pip3] torchaudio==2.1.2
[pip3] torchdata==0.7.0
[pip3] torchtext==0.16.0
[pip3] torchvision==0.16.2
[conda] Could not collect

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by zhxchen17** [comment]
I took a look at https://github.com/lutzroeder/netron. Sorry it's the first time I knew this project but it looks really cool :) 

I think there might be two issues here:

1. I guess for your purpose, it's better to get a format which only contains the computation graph without state dict?

2. Currently our zip file contains the graph (as json), the state dict (as json), the constants (as json), and a version file:
```
 extracting: serialized_exported_program.json
 extracting: serialized_state_dict.json
 extracting: serialized_constants.json
 extracting: version
```
The serialized_state_dict file indeed looks wrong in the sense that it's not conforming to JSON standard. I guess this is what you mean by "incorrect json extension"? IMO we should fix it so that it doesn't use JSON.

**Comment by lutzroeder** [comment]
@zhxchen17 exactly, it's two questions:

2. `serialized_state_dict.json` should be called `serialized_state_dict.zip` or `serialized_state_dict.pt`?

1. Netron loads weight files as well so no preferences. The question is that conceptually serializing a Zip inside a Zip is problematic. For example, 80 GB weights stored in a Zip file inside another Zip file might lead to complex patterns of holding onto large streams inside of other streams or makes it impossible to decode at the right granularity in memory. Zip streams might be compressed. Would it make sense to discuss a design that uses a single Zip container, for example by injecting the `serialized_exported_program.json` file into the `torch.load` container used for `state_dict`. For example, TorchScript stores the program entirely in a single Zip file that is the `torch.load` container.
