### ISSUE TITLE
enable privateuseone to perform multiple streams backwards

### ISSUE THREAD

**Issue by garfield1997** [pytorch/pytorch#116957]
### 🚀 The feature, motivation and pitch

My team is working on adding custom backend for pytorch, and would like multiple streams backwards to be possible on privateuseone backend.  
Specifically, part of the code in the autograd engine was hardcoded into CUDA without considering other accelerators similar to CUDA, resulting in other custom backends being unable to use multi-stream training.
For example, 
https://github.com/pytorch/pytorch/blob/main/torch/csrc/autograd/engine.cpp#L1524  
```
void GraphTask::stash_current_streams() {
  const auto guard = c10::impl::VirtualGuardImpl{c10::DeviceType::CUDA};
  auto num_gpus = guard.deviceCount();
  caller_current_streams_.resize(num_gpus);
  if (num_gpus > 0) {
    for (c10::DeviceIndex idx = 0; idx < num_gpus; idx++) { 
```  
https://github.com/pytorch/pytorch/blob/main/torch/csrc/autograd/engine.cpp#L716  
``` 
if (!leaf_streams.empty()) {
    for (const auto& leaf_stream : leaf_streams) {
      // stash_current_streams() stashed streams for all device IDs that already
      // had a CUDA context before the GraphTask executed. For inactive devices,
      // it stashed a c10::nullopt. I don't expect GraphTask's backward pass ran
      // leaf nodes on any new devices, so the stashed streams should be enough.
      // If leaf_stream.device_index() happens to be for a new device,
      // operator* on the c10::nullopt should throw an error.
      const auto caller_current_stream =
          // NOLINTNEXTLINE(bugprone-unchecked-optional-access)
          *caller_current_streams_[leaf_stream.device_index()];

      if (caller_current_stream != leaf_stream) {
        auto event = c10::Event{c10::DeviceType::CUDA};
```
Of course, the above two code snippets are just for illustration.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @bdhirsh

**Comment by garfield1997** [comment]
@ezyang @albanD @soulitzer

**Comment by ezyang** [comment]
Sure seems reasonable. Send a patch?

**Comment by garfield1997** [comment]
Ok, I will work on it.
