### ISSUE TITLE
Feature Request: Automatically Cast to torch tensor

### ISSUE THREAD

**Issue by petered** [pytorch/pytorch#11695]
Numpy automatically casts inputs to ndarrays when doing operations on them.  For example:
 ```
>>> np.sum([1, 2])
3
>>> np.sqrt(9)
3.0
```
Pytorch fails instead:
```
>>> torch.sum([1, 2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sum(): argument 'input' (position 1) must be Tensor, not list
>>> torch.sqrt(9)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sqrt(): argument 'input' (position 1) must be Tensor, not int
```

It would be nice for Pytorch to do type-casting internally like numpy does.

cc @mruberry @rgommers @heitorschueroff

**Comment by bhushan23** [comment]
This is very useful and intutive use case.
We should support this.

**Comment by ezyang** [comment]
Some thoughts:
* It seems reasonable
* Adding this support will make the Python bindings somewhat more complex, but it shouldn't result in a performance slowdown. This feature must be implemented in C++.
* It's not clear if adding this will cause some overloads to become ambiguous (because you can't tell the difference between an IntArrayRef and a Tensor anymore), this would have to be investigated

@umanwizard, I think you can make the final call here, but the triage meeting thinks that this feature would be OK to accept.

**Comment by umanwizard** [comment]
@ezyang I agree with your assessment

**Comment by gchanan** [comment]
One additional piece of information that I think needs to be captured:

this makes it very easy to get slow behavior and to not understand why.  This is the same reason we don't support automatically converting cuda tensors to numpy tensors.

For example:
```
my_python_list = [ something_really_big]
torch.fn0(my_python_list)
torch.fn1(my_python_list)
torch.fn2(my_python_list)
```

This means each time I have to do a copying conversion.

**Comment by umanwizard** [comment]
Oh, I didn't read the issue carefully enough, I thought it was only requesting it for cases like `torch.sqrt(9.0)`.

Accepting arbitrary python lists and silently converting them is indeed a different thing... I'm not convinced the value outweighs the drawbacks of silent copying.

**Comment by rgommers** [comment]
I really wish NumPy was less forgiving, it's an endless source of issues. There's something to say for accepting Python `int` and `float` for convenience, but lists/tuples are very questionable already, and anything beyond that is definitely not a good idea.

**Comment by mruberry** [comment]
I agree with @rgommers, and if we follow the thinking in https://github.com/pytorch/pytorch/issues/31558 this approach may be an antipattern as it will prevent some device types from maximizing their performance.

**Comment by mruberry** [comment]
Closing this in favor of the more recent and general https://github.com/pytorch/pytorch/issues/46138.
