### ISSUE TITLE
Compile failed when add a new DispatcherKey to torch.

### ISSUE THREAD

**Issue by huihoaan** [pytorch/pytorch#116970]
### 🐛 Describe the bug

I want to add DispatcherKey for `SparseCsrPrivateUse1` for PrivateUse1. Everything is ok expect compiling our code(compile torch is ok). The error:
![image](https://github.com/pytorch/pytorch/assets/37650440/20412f87-eca8-41e6-bb14-0a0af045980b)

The error message show that `DispatchKeySet(DispatchKey::AutogradMeta)` (which AutogradMeta is 128) is overflow, because of adding a new DispatcherKey  before it. But in the code 
https://github.com/pytorch/pytorch/blob/ad507789d12e3f757a43f35cd66e7aea6124140d/c10/core/DispatchKey.h#L620-L626
DispatchKey will be cast to uint8, which won't overflow. So I don't know how fix it.
By the way, the pr:https://github.com/pytorch/pytorch/pull/116969. And my linux is aarch64, and gcc is 7.5.0.

### Versions

PyTorch version: 2.3.0a0+git29c8686
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (aarch64)
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.23.1
Libc version: glibc-2.27

Python version: 3.8.17 (default, Jul  5 2023, 20:40:03)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-29-generic-aarch64-with-glibc2.26
CPU:
Architecture:        aarch64

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] numpy==1.23.4
[pip3] torch==2.3.0a0+git29c8686
[pip3] torchair==0.1
[pip3] torchvision==0.16.0

cc @bdhirsh @ezyang @msaroufim @wconstab @anijain2305 @zou3519

**Comment by bdhirsh** [comment]
Hey @huihoaan - you'll have to turn `SparseCSR` into a "per-backend-functionality key", similar to the current handling for the `Sparse` key (there's been an existing todo for it here: https://github.com/pytorch/pytorch/blob/ad507789d12e3f757a43f35cd66e7aea6124140d/c10/core/DispatchKey.h#L220)

I'm not going to have bandwidth to make the change, but if you can make it and get tests passing them I'm happy to review it. the `DispatchKey::Sparse` key is already set up this way, so you can grep the codebase for how `DispatchKey::Sparse` is used to see how to make the change: https://github.com/pytorch/pytorch/blob/ad507789d12e3f757a43f35cd66e7aea6124140d/c10/core/DispatchKey.h#L217
