### ISSUE TITLE
How to adapt to `at::scaled_dot_product_attention`'s routing logic for a third-party cuda-like device?

### ISSUE THREAD

**Issue by drslark** [pytorch/pytorch#116922]
https://github.com/pytorch/pytorch/blob/f24bba1624a8bb5c920833b18fc6162db084ca09/aten/src/ATen/native/transformers/attention.cpp#L635-L642

Now, I am adapting `at::scaled_dot_product_attention` to a specific type of cuda-like device and encounters a problem.
In `at::scaled_dot_product_attention`, it will choose a path between `at::_scaled_dot_product_flash_attention`, `at::_scaled_dot_product_efficient_attention` and `at::_scaled_dot_product_attention_math` for `cpu`, `cuda` and `romc` in the routing codes.
But for another cuda-like device, the routing codes will always go into the `at::_scaled_dot_product_attention_math` path.

If I have implemented all these three paths for my cuda-like device, how can I change these routing codes to fully support `at::scaled_dot_product_attention`?
Should I write a new `at::scaled_dot_product_attention` only for my cuda-like device, or just change some codes in the current torch repository?
I need some suggestions, thank you!

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by jbschlosser** [comment]
cc @drisspg for best practices here

**Comment by drisspg** [comment]
This seems pretty related to this issue: https://github.com/pytorch/pytorch/issues/116854#issuecomment-1881575407

Are you using the the PrivateUse1 dispatch key to define the registrations for your device?

**Comment by drslark** [comment]
> This seems pretty related to this issue: [#116854 (comment)](https://github.com/pytorch/pytorch/issues/116854#issuecomment-1881575407)
> 
> Are you using the the PrivateUse1 dispatch key to define the registrations for your device?

Yes, in my case, my cuda-like device uses `PrivateUse1` as dispatch key.
But as i know, `PrivateUse1` may represents other device in other case.
So, I think it is impossible to come up with a routing logic for `PrivateUse1`.

**Comment by drslark** [comment]
> After speaking with @albanD it seems like the best action would be to just override the top level composite implicit function for your backend.
> 
> Description of how to do this in c++ can be found here: https://pytorch.org/tutorials/advanced/dispatcher.html
> 
> or in python: https://github.com/pytorch/pytorch/blob/main/torch/library.py has some good description of the workflow

Do you mean i should write a top-level `at::scaled_dot_product_attention` with my custom routing logic and override the raw one?

**Comment by drisspg** [comment]
@drslark yup exactly you can do this by registering to both the PrivateUse1 and AutogradPrivateUse1 keys
