### ISSUE TITLE
rror message: The operator 'aten::slow_conv3d_forward' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

### ISSUE THREAD

**Issue by NiharJani2002** [pytorch/pytorch#117027]
### 🐛 Describe the bug

rror message: The operator 'aten::slow_conv3d_forward' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

### Versions

Pytorch 2.1.1 

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by malfet** [comment]
Conv3d was added by https://github.com/pytorch/pytorch/pull/114183
Please try latest nightly and if still does not work, please do not hesitate to open a new issue

**Comment by n1ckfg** [comment]
I still get the same error about missing aten::slow_conv3d_forward using the latest nightly.
