### ISSUE TITLE
Add `is_leaf` argument in tree_map

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#117035]
tree_map from Jax has an `is_leaf` argument: a callable that identifies whether or not a node is a leaf.

That would be pretty handy for #112441: we could avoid patching pytree altoghether and just rely on a custom identification of `tensordict` as leaves when needed.

https://github.com/pytorch/pytorch/blob/db79ceb110f6646523019a59bbd7b838f43d4a86/torch/utils/_pytree.py#L703C1-L735C1

cc @zou3519 @XuehaiPan

**Comment by zou3519** [comment]
Resolved by https://github.com/pytorch/pytorch/pull/116419#event-11434819436
