### ISSUE TITLE
Auto-applying labels if one-or-more Labels are applied?

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#117051]
For the PT2 oncall, we have labels that are sublabels of each other. For example, the "module: aotdispatch" label is a sub-label of "module: pt2-dispatcher". It would cool if if someone labels an issue as "module: aotdispatch", a bot comes along and automatically labels it as "module: pt2-dispatcher" (and "oncall: pt2").

cc @ZainRizvi @kit1980 @huydhn @clee2000 @pytorch/pytorch-dev-infra -- any ideas on how to go about doing this?

**Comment by huydhn** [comment]
For complex labeling logic, we have https://github.com/pytorch/test-infra/blob/main/torchci/lib/bot/autoLabelBot.ts to implement them.  One way to implement this IMO is to define the relationship among these labels on https://github.com/pytorch/pytorch/blob/main/.github/pytorch-probot.yml.  The bot can then read the file and attach necessary labels accordingly.

**Comment by malfet** [comment]
I also want to remove `not user facing` if any other topic labels is applied

**Comment by zou3519** [comment]
Proposal:
1. we have some dictionary that represents a hierarchical label structure. For example:
```
{
    "oncall: pt2": ["module: dynamo", "module: pt2-dispatcher", "module: inductor"]
    "module: pt2-dispatcher": ["module: custom operators", "module: aotdispatch", ...]
}
``` 
2. logic that consumes this dictionary and determines which labels to apply.

@huydhn was the suggestion to toss the dictionary-like hting into pytorch-probot.yml?

**Comment by zou3519** [comment]
Also, un-assigning because I don't think either of us are actively working on this at the moment.

**Comment by albanD** [comment]
@huydhn what is the state of creating this fancier labeling system? Should we do it by hand for the ones we need now and migrate once the relationship system is implemented?

**Comment by clee2000** [comment]
Done in https://github.com/pytorch/pytorch/pull/125042, feel free to add rules in the file added by this pr.  Only "any" and "all" are supported right now.   

The topic not user facing is a bit more difficult, made a specific issue just for that https://github.com/pytorch/test-infra/issues/5144 so I don't get confused every time I see the title
