### ISSUE TITLE
 `pytest test/dynamo/test_ctx_manager.py -v -k "test_autocast_graph_break_method"` fails locally

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#117000]
On Python 3.11, this test appears to fail locally. However, running this test with python (instead of pytest) causes it to pass.

Error message looks something like the following.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @williamwen42 maybe since you've seen the code when adding python 3.11 support?

https://gist.github.com/zou3519/79803132545dffd45241d4a2d52036d4

cc @ezyang @gchanan @kadeng @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by zou3519** [comment]
Well, this isn't difficult to fix, but the real question is why CI isn't catching it...

**Comment by zou3519** [comment]
hi-pri because tests are erroneously passing in CI which can lead to other issues.

**Comment by zou3519** [comment]
Figured out the root case, will open a separate issue for it.

**Comment by malfet** [comment]
Great issue number by the way, will be removing triage review as you've added it to this one

**Comment by anijain2305** [comment]
@zou3519 Can this be closed? THe test passes on main
