### ISSUE TITLE
Torch leaks dlpack tensors that have a nullptr `data` pointer.

### ISSUE THREAD

**Issue by hawkinsp** [pytorch/pytorch#117058]
### 🐛 Describe the bug

If a DLPack is passed to torch from an external system whose `data` pointer is nullptr, torch never calls the deleter of that DLPack, leaking the DLPack metadata.

This is a legal and reasonable thing to do, e.g., for an array with no elements.

From inspecting the code, this looks like an instance of a common C++ bug where `std::unique_ptr` will not call its deleter if the underlying data pointer is nullptr, which it is in this case.

https://github.com/pytorch/pytorch/blob/29ae4f22bfb35610d2e21a300f810699e093ccb1/c10/core/Allocator.h#L195

### Versions

2.1.2

cc @ezyang @gchanan @zou3519 @kadeng

**Comment by janeyx99** [comment]
tentatively hipri for mem leak

**Comment by malfet** [comment]
Well, considering we aren't actively testing dlpack it's probably fine, but we will accept PR that fixes it

**Comment by ezyang** [comment]
Oh yeah, we actually manually worked around this by reimplement unique ptr as c10/util/UniqueVoidPtr.h for our internal tensor struct. But we forgot to do this for InefficientStdFunctionContext oops. Can you send us a fix for it? Thanks!

**Comment by TaiPhamD** [comment]
It looks like this PR: https://github.com/pytorch/pytorch/pull/117418 has already resolved this issue. Is this issue still valid?

**Comment by rgommers** [comment]
This was fixed by gh-117418 indeed, so let's close this issue. Thanks all!
