### ISSUE TITLE
pytest rewrites assertion, causing Dynamo under pytest to be different from Dynamo under unittest

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#117004]
Repro:
```
# fails
pytest test/dynamo/test_ctx_manager.py -v -k "test_autocast_graph_break_method"
# succeeds
python test/dynamo/test_ctx_manager.py -v -k "test_autocast_graph_break_method"
```

What's going on is:
- [Pytest rewrites assertions](https://docs.pytest.org/en/7.1.x/how-to/assert.html#:~:text=Rewritten%20assert%20statements%20put%20introspection,modules%20will%20not%20be%20rewritten.)
- [Dynamo rewrites assertions](https://github.com/pytorch/pytorch/blob/33d90cfd16991bc5339cd47ee4ed085d830b4c5a/torch/_dynamo/symbolic_convert.py#L246-L266)
- pytest rewriting assertions cause the dynamo code to go down a different codepath, which has some incorrect code in it.

To make things consistent, we can run pytest using `--assert=plain`. Maybe we already do this in CI, since I don't see the above test failing in CI despite using pytest...

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Yes, I've been asking for a while to stop using `assert` in tests, but instead rely on `self.assertTrue`

Adding `triage review` as I'm not sure where to put it: in "module: ci" or "oncall: pt2"

**Comment by ezyang** [comment]
No, we shouldn't stop using assert in tests. Turning off pytest assert rewriting is clearly the right thing to do. It has also bitten us other times in the past.

**Comment by malfet** [comment]
@ezyang correct me if I'm wrong, but disabling asserts completely by passing `-OO` option to cpython is a legitimate thing to do, but imo tests should still yield expected results if such option is used.

**Comment by ezyang** [comment]
Since we're in the business of processing python programs as inputs, our test programs often validly have 'assert' inside them (as in, the input to our compiler is a python program with assert in it)

**Comment by clee2000** [comment]
> pytest only rewrites test modules directly discovered by its test collection process, so asserts in supporting modules which are not themselves test modules will not be rewritten.

and

> Disable rewriting for a specific module by adding the string PYTEST_DONT_REWRITE to its docstring.

From https://pytest.org/en/7.4.x/how-to/assert.html#disabling-assert-rewriting

In CI we usually call the test file (`python test_ops.py`), which then calls run_test which then calls pytest.main, so the test module is already imported as `__main__`, so pytest does not import the test module itself and relies on the already imported module. (https://github.com/pytorch/pytorch/pull/95844)

However, calling `pytest test_ops.py` will rely on pytest to import the module, resulting in asserts being rewritten.

If you want to never rewrite assertions, you can add --assert=plain to pytest.ini or include PYTEST_DONT_REWRITE somewhere in the file.

**Comment by zou3519** [comment]
The main problem we're running into with this is inconsistency: pytest vs unittest locally is different, pytest locally vs CI is different. A possible end state here is to offer a default pytest.ini file locally that has --assert=plain so that everyone is consistent.

**Comment by clee2000** [comment]
Yes sorry I mean you can either commit a change to pytest.ini for assert=plain or you can commit a change for the magic string
