### ISSUE TITLE
Dynamo - autograd.Function w/ custom user defined methods does not work

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#117071]
https://github.com/alxndrTL/mamba.py/pull/1

Fails during HOP speculation, should just treat these as any user defined methods on a user defined object, esp if staticmethod.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @ydwu4

**Comment by zou3519** [comment]
afaict this works now
