### ISSUE TITLE
cache_entries empty after torch.compile() ?

### ISSUE THREAD

**Issue by mobicham** [pytorch/pytorch#117045]
I have a function that I compile via `@torch.compile()`. My main goal is to cache the generated code so I can re-use it later because the compilation can be quite slow. 

Following the documentation, I did the following:
```python
import torch, logging 
torch._dynamo.output_graph = True
#torch._dynamo.output_code = True #-> module 'torch._dynamo' has no attribute 'output_code'
torch._inductor.config.trace.enabled = True

#Compile and run with some tensors ...

from torch._dynamo.eval_frame import _debug_get_cache_entry_list
cache_entries = _debug_get_cache_entry_list(my_fct_compiled._torchdynamo_orig_callable.__code__)
guard, code = cache_entries[0] #error because cache_entries is empty!
```
During the compilation I see the logs and the locations of the generated code but when I use `_debug_get_cache_entry_list` it seems that it's referring to the original function not the compiled one. 

Could that be because compilation is done via the decorator? In that case, what would be the right way to recover the generated code that I can call directly. The output code in `output_code.py` doesn't seem to have the same arguments/shapes as the original function. 

Thank you in advance!

### Versions

PyTorch version: 2.3.0.dev20231221+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY

Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] pytorch-triton==2.2.0+e28a256d71
[pip3] torch==2.3.0.dev20231221+cu121
[pip3] torchaudio==2.2.0.dev20231221+cu121
[pip3] torchvision==0.18.0.dev20231221+cu121
[pip3] triton==2.1.0
[conda] Could not collect

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by ezyang** [comment]
@anijain2305 for this one, but this API isn't really intended to be public haha

@oulgen on caching

**Comment by youkaichao** [comment]
You definitely need to show your example code. Sometimes it is difficult to find the specific function `torch.compile` optimizes, for example when you call `mod.compile()`.

I recommend using the [depyf](https://github.com/thuml/depyf) tool. Please `pip install git+https://github.com/thuml/depyf.git`, and wrap your code under `depyf.prepare_debug("/path/to/the/log")`, then you can see which function `torch.compile` optimizes under `/path/to/the/log/full_code_for_xxx.py`.

**Comment by mobicham** [comment]
Thank you for your answers! 
@jansel please find the code below.

To give you more context, this is the function I would like to cache (for different GPU architectures, etc.): https://github.com/mobiusml/hqq/blob/master/hqq/core/quantize.py#L351 . It is a dequantization + matmul step. The `torch.compile()` step seems to only compile the `dequantization()` function, which is fine. Ideally the goal is to be able to cache the compiled code so the user doesn't have to wait for the compilation every time they start a Python session, because this can take a long time on older GPUs / with larger matrices to the point where some people are reporting the program getting completely frozen (couldn't reproduce that though). The idea is basically when the backend is set to PYTORCH_COMPILE in the library, there will be some logic that checks the GPU architecture and loads the right pre-cached torch.compile generated code instead of compiling on the fly.  My secondary goal is to use the generated code as a starting point and try to improve it.

```python
!pip install hqq #Install the library 

hf_auth    = None #HuggingFace token
cache_path = ''   #cache directory to store data

#Chose a model
model_id  = "meta-llama/Llama-2-7b-hf" 

#HQQ Quantize
######################################################################################
from hqq.engine.hf import HQQModelForCausalLM, AutoTokenizer
model     = HQQModelForCausalLM.from_pretrained(model_id, use_auth_token=hf_auth, cache_dir=cache_path)
tokenizer = AutoTokenizer.from_pretrained(model_id,       use_auth_token=hf_auth, cache_dir=cache_path) 

#Quantize
from hqq.core.quantize import *
quant_config = BaseQuantizeConfig(nbits=4, group_size=128, quant_scale=False, quant_zero=False)
model.quantize_model(quant_config=quant_config)
HQQLinear.set_backend(HQQBackend.PYTORCH_COMPILE)
model.eval();
################################################################################################

#Debug
import torch, logging 
from torch import _dynamo as torchdynamo
###############################################

#With depyf 
def main():
	for _ in range(100):
		with torch.no_grad():
			out = model(torch.ones((1, 1024), dtype=torch.int32, device='cuda'))
	del out 
	cleanup()

if __name__ == "__main__":
	import depyf
	with depyf.prepare_debug("./dump_src_dir"):
		main()

###############################################
#Torch compile debug coded previously 
torch._dynamo.output_graph = True
torch._inductor.config.trace.enabled = True

#Compile and run 
for i in range(100):
	with torch.no_grad():
		out = model(torch.ones((1, 1024), dtype=torch.int32, device='cuda'))
del out 
cleanup()

#Grab functions
fct = model.model.layers[-1].self_attn.v_proj.forward
#fct = model.model.layers[-1].mlp.down_proj.forward

print(fct._torchdynamo_orig_callable.__code__)

from torch._dynamo.eval_frame import _debug_get_cache_entry_list
cache_entries = _debug_get_cache_entry_list(fct._torchdynamo_orig_callable.__code__)
guard, code = cache_entries[0]
```

@youkaichao thanks! I have tried it. It's not that obvious to re-use. It has generated 64 `full_code_for_dequantize_x.py` functions, all of them contain the original Pytorch code except  `full_code_for_dequantize_64.py`  which looks different. But it points to `__compiled_fn_194()`, then I check the files `__compiled_fn_194*.py` and there are 3 versions and it's not really clear how to import them in `full_code_for_dequantize_64.py` . Do you have by any chance a walk-through example that shows how to call the generated code directly ?

**Comment by youkaichao** [comment]
Well, please take a look at the code https://github.com/mobiusml/hqq/blob/master/hqq/core/quantize.py . It does not add `torch.compile` for `forward`. The functions being compiled are `forward_pytorch_compile` and `matmul_compile`. You are trying to find cache entries in the wrong place.

The reason why you see many `full_code_for_dequantize_xxx.py`, might be because this function `dequantize` caused graph break. So it is implicitly `torch.compile`'ed.

There should be some public method to save and reuse the compiled cache, and you shouldn't save cache this way. @jansel should know how to save and reuse the compiled cache in a better way 😉

**Comment by mobicham** [comment]
@youkaichao when you set the backend to PYTORCH_COMPILE, it replaces `forward` with  `forward_pytorch_compile`. The function `matmul_compile` is used with another backend option called PYTORCH_BACKPROP_COMPILE (I wrote the code for the whole library). So It does compile the right functions and `forward` is clearly pointing to `forward_pytorch_compile`, that's how it was able to generate the code.  

Great, looking forward to @jansel 's answer!

**Comment by youkaichao** [comment]
If I understand correctly, your situation looks like the following:

```python
import torch

class MyMod(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(10, 10)

    @torch.compile(backend="eager")
    def real_forward(self, x):
        yield self.linear(x) # returning a generator will fail torch.compile

    @classmethod
    def switch_forward(cls):
        cls.forward = cls.real_forward

model = MyMod()
model.switch_forward()
inputs = torch.randn(10, 10)
model(inputs)

from torch._dynamo.eval_frame import _debug_get_cache_entry_list

print(_debug_get_cache_entry_list(model.forward._torchdynamo_orig_callable.__code__))
```

You get an empty cache entry list because your function cannot be compiled. In this example, if we replace `yield self.linear(x)` with `return self.linear(x)`, everything works.

In your problem, the case is that your [`dequantize`](https://github.com/mobiusml/hqq/blob/5d1a8e12fc29dad11e42aa390341ac0be09d94ab/hqq/core/quantize.py#L314-L329
) function is too difficult to compile:

```python
	def dequantize(self):
		assert self.ready, "model was not quantized"
		W_q, meta = self.W_q, self.meta

		del_keys = []
		if(meta['quant_scale']):
			meta['scale'] = Quantizer.dequantize(meta['scale_q'], meta['meta_scale']); del_keys.append('scale')
		if(meta['quant_zero']):
			meta['zero']  = Quantizer.dequantize(meta['zero_q'],  meta['meta_zero']);  del_keys.append('zero')

		W_est = Quantizer.dequantize(W_q, meta)

		#Cleanup
		for key in del_keys: del meta[key]
		return W_est
```

`torch.compile` will try many times to compile it, so you see many `full_code_for_dequantize_xxx.py`. However, it still fails to compile in the end. So you get an empty list. You will need to refactor this function so that `toch.compile` works better for it.

To be clear, **these are discussions about fragile internal details that you should not depend on in general. It would be very difficult to collect all the compiled functions and cache entries in this way.**

**Comment by mobicham** [comment]
@youkaichao there's no problem with `torch.compile()` doing its job here: 
- it is generating **faster** code for `dequantize()` on different GPUs. The prediction time is about 50-70% faster with compilation. Nothing else in the model is compiled, only that part I mentioned.  
- I can clearly see the Triton kernels generated and readable version makes sense. It generates code for 3 different matrix shapes which is consistent with the model architecture.

The only issue is how to re-use that compiled code. The compiled function is calling something somewhere, the question is how to access that and how to save/load it.

**Comment by youkaichao** [comment]
@mobicham can you try to print the cache entries for all the layers? You are just printing one layer via `model.model.layers[-1].self_attn.v_proj.forward`. Chances are some layers can be compiled while some cannot.

**Comment by mobicham** [comment]
@youkaichao I run it on all the layers that are supposed to use it and all of them gives empty `cache_entries`: 

```python
hf_auth    = None #HuggingFace token
cache_path = ''   #cache directory to store data

#Chose a model
model_id  = "meta-llama/Llama-2-7b-hf" 
#HQQ Quantize
######################################################################################
from hqq.engine.hf import HQQModelForCausalLM, AutoTokenizer
model     = HQQModelForCausalLM.from_pretrained(model_id, use_auth_token=hf_auth, cache_dir=cache_path)
tokenizer = AutoTokenizer.from_pretrained(model_id,       use_auth_token=hf_auth, cache_dir=cache_path) 

from hqq.core.quantize import *
quant_config = BaseQuantizeConfig(nbits=4, group_size=128, quant_scale=False, quant_zero=False)
################################################################################################

#Quantize
model.quantize_model(quant_config=quant_config)
HQQLinear.set_backend(HQQBackend.PYTORCH_COMPILE)
model.eval();

#Debug
import torch, logging 
from torch import _dynamo as torchdynamo

#Torch compile  debug
torch._dynamo.output_graph = True
torch._inductor.config.trace.enabled = True

#Compile and run 
for i in range(100):
	with torch.no_grad():
		out = model(torch.ones((1, 1024), dtype=torch.int32, device='cuda'))
del out 
cleanup()

from torch._dynamo.eval_frame import _debug_get_cache_entry_list

def get_cache_entry_code(layer):
	fct = layer.forward
	cache_entries = _debug_get_cache_entry_list(fct._torchdynamo_orig_callable.__code__)
	if(len(cache_entries)>0):
		print(layer.name, len(cache_entries))
		guard, code = cache_entries[0]

for i in range(len(model.model.layers)):
	get_cache_entry_code(model.model.layers[i].self_attn.q_proj)
	get_cache_entry_code(model.model.layers[i].self_attn.k_proj)
	get_cache_entry_code(model.model.layers[i].self_attn.v_proj)
	get_cache_entry_code(model.model.layers[i].self_attn.o_proj)

	get_cache_entry_code(model.model.layers[i].mlp.gate_proj)
	get_cache_entry_code(model.model.layers[i].mlp.up_proj)
	get_cache_entry_code(model.model.layers[i].mlp.down_proj)

#Nothing is printed here, means cache_entries is empty for all the layers

print_forward_fct = lambda layer: print(layer.forward)
for i in range(len(model.model.layers)):
	print_forward_fct(model.model.layers[i].self_attn.q_proj)
	print_forward_fct(model.model.layers[i].self_attn.k_proj)
	print_forward_fct(model.model.layers[i].self_attn.v_proj)
	print_forward_fct(model.model.layers[i].self_attn.o_proj)

	print_forward_fct(model.model.layers[i].mlp.gate_proj)
	print_forward_fct(model.model.layers[i].mlp.up_proj)
	print_forward_fct(model.model.layers[i].mlp.down_proj)

#-> All of them point to <bound method HQQLinear.forward_pytorch_compile of HQQLinear()>
```

On the Titan RTX, the prediction time without compilation is ~0.40 sec/iter and with compilation is ~0.254 (+58%), the speed-up is not noise, torch compile is def doing its job. The Triton kernels are found in my tmp folder `/tmp/torchinductor_hicham/`, here's of them that seems to correspond to down_proj like layers 
[cx2scmoam6lqfomdwopsuosdl2ls4nnym776oywksg77yz6fczes.zip](https://github.com/pytorch/pytorch/files/13890596/cx2scmoam6lqfomdwopsuosdl2ls4nnym776oywksg77yz6fczes.zip) . You can see in the Triton kernels it's doing bitwise & and shifts, which are the right ops used in the dequantization step.

**Comment by youkaichao** [comment]
What is the `cleanup` code?

**Comment by mobicham** [comment]
It's `torch.cuda.empty(); gc.collect()`. The output is the same without it

**Comment by youkaichao** [comment]
Chances are some variables are freed in `cleanup`, and the guarded code becomes invalid, and the cache entries are cleared.

Please check this code:

```python
import torch

class MyMod(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(10, 10)

    @torch.compile(backend="eager")
    def forward(self, x):
        return self.linear(x)

from torch._dynamo.eval_frame import _debug_get_cache_entry_list

for i in range(30):
  model = MyMod()
  inputs = torch.randn(10, 10)
  model(inputs)
  print(_debug_get_cache_entry_list(model.forward._torchdynamo_orig_callable.__code__))
```

The first several iterations print something, but later when some models are freed, the cache entry becomes empty. Here are my outputs:

```
[<torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1364c1440>]
[<torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861020>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1364c1440>]
[<torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169860d80>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861020>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1364c1440>]
[<torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861110>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169860d80>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861020>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1364c1440>]
[<torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1699c41e0>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861110>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169860d80>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861020>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1364c1440>]
[<torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169860f60>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1699c41e0>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861110>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169860d80>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861020>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1364c1440>]
[<torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861080>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169860f60>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1699c41e0>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861110>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169860d80>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861020>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1364c1440>]
[<torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169a86040>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861080>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169860f60>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1699c41e0>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861110>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169860d80>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x169861020>, <torch._C.dynamo.eval_frame.CacheEntryWrapper object at 0x1364c1440>]
[2024-01-11 01:06:11,276] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (8)
[2024-01-11 01:06:11,276] torch._dynamo.convert_frame: [WARNING]    function: 'forward' (file.py:8)
[2024-01-11 01:06:11,276] torch._dynamo.convert_frame: [WARNING]    last reason: ___guarded_code.valid
[2024-01-11 01:06:11,276] torch._dynamo.convert_frame: [WARNING] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[2024-01-11 01:06:11,276] torch._dynamo.convert_frame: [WARNING] To diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
```

**Comment by ezyang** [comment]
Well, if the problem is y'all can't find the right code object the entries are on, just run with TORCH_LOGS=+dynamo and pay attention to what frame Dynamo actually starts compiling on.

**Comment by masnesral** [comment]
I'm going through old issues. @mobicham is there anything left to do here? Comments seem to arrive that everything is working fine, you just wanted more details about where compiled artifacts are placed in the cache (on disk)? If so, does enabling the logging suggested in the last comment suffice?

**Comment by mobicham** [comment]
@masnesral Thank you for following up, I will close this issue for now.
