### ISSUE TITLE
IndexError from torch._dynamo.export when using module with 2 convolutions

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#117033]
### 🐛 Describe the bug

I have an IndexError on some machines observed in test_module_partitioner_functional_conv_relu_conv

It can be reproduced with this code:
```python
import torch

class FunctionalConv2d(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.stride = (1, 1)
        self.padding = (0, 0)
        self.dilation = (1, 1)
        self.groups = 1

    def forward(self, x, weight, bias):
        return torch.nn.functional.conv2d(x, weight, bias, self.stride, self.padding, self.dilation, self.groups)

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = FunctionalConv2d()
        self.conv2 = FunctionalConv2d()

    def forward(self, x, weight, bias):
        x = self.conv1(x, weight, bias)
        x = torch.nn.functional.relu(x)
        x = self.conv2(x, weight, bias)
        return x

inputs = (torch.randn(1, 3, 5, 5), torch.randn(3, 3, 3, 3), torch.rand(3))
gm, _ = torch._dynamo.export(M(), aten_graph=True)(*inputs)
```

The output is this:
```
[2024-01-09 14:02:01,425] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard 4*s0**3 - 4*s0**2 + s0 > 2147483647 == False, this could result in accuracy problems
[2024-01-09 14:02:01,428] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard s0**3 > 2147483647 == False, this could result in accuracy problems
[2024-01-09 14:02:01,486] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard s0 > 2147483647 == False, this could result in accuracy problems
Traceback (most recent call last):
  File "/home/s3248973/test_fx_failure.py", line 34, in <module>
    gm, _ = torch._dynamo.export(M(), aten_graph=True)(*inputs)
  File "/torch/_dynamo/eval_frame.py", line 1150, in inner
    dim_constraints.solve()
  File "/torch/fx/experimental/symbolic_shapes.py", line 1860, in solve
    self._dynamic_results.add(self._dcp.doprint(arg))
  File "/sympy/printing/printer.py", line 292, in doprint
    return self._str(self._print(expr))
  File "/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/torch/fx/experimental/symbolic_shapes.py", line 1582, in _print_Relational
    self.parenthesize(expr.rhs, precedence(expr))
  File "/sympy/printing/str.py", line 39, in parenthesize
    return self._print(item)
  File "/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/sympy/printing/str.py", line 787, in _print_ComplexRootOf
    return "CRootOf(%s, %d)" % (self._print_Add(expr.expr,  order='lex'),
  File "/sympy/printing/str.py", line 58, in _print_Add
    t = self._print(term)
  File "/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/sympy/printing/str.py", line 368, in _print_Mul
    a_str = [self.parenthesize(x, prec, strict=False) for x in a]
  File "/sympy/printing/str.py", line 368, in <listcomp>
    a_str = [self.parenthesize(x, prec, strict=False) for x in a]
  File "/sympy/printing/str.py", line 39, in parenthesize
    return self._print(item)
  File "/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/sympy/printing/str.py", line 670, in _print_Pow
    return '%s**%s' % (self.parenthesize(expr.base, PREC, strict=False), e)
  File "/sympy/printing/str.py", line 39, in parenthesize
    return self._print(item)
  File "/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/torch/fx/experimental/symbolic_shapes.py", line 1576, in _print_Symbol
    return self.print_source(self.symbol_to_source[expr][0])
IndexError: list index out of range
```

Strangely the issue happens only on one system. I traced it and found that when it is working only "s0" is used as `expr` in the failing line while when it fails it also is `x`.   
Checking the `dim_constraints.solve` method I found `self._univariate_inequalities = {s0: {s0 <= 3, s0 >= 2}}` where it works but `{s0: {4*s0**3 - 4*s0**2 + s0 <= 2147483647, s0 >= 2, s0**3 <= 2147483647, s0 <= 2147483647}}` on the failing system.

The solution in line 1856 of `symbolic_shapes.py` is then `(2 <= s0) & (s0 <= 3)` vs `(2 <= s0) & (s0 <= CRootOf(4*x**3 - 4*x**2 + x - 2147483647, 0))` which explains where the `x` is coming from.

Using the logger in `symbolic_shapes.py` I observed a difference: 
```
- [INFO] eval s0 <= 3 [guard added] at ome/s3248973/test_fx_failure.py:12 in forward (_subclasses/fake_tensor.py:677 in conv)
+[INFO] eval -s0 + s1 + 1 >= 0 [guard added] at ome/s3248973/test_fx_failure.py:12 in forward (_refs/__init__.py:4483 in new_empty)
```

which later leads to: 
```
- [DEBUG] eval 4*s0**3 - 4*s0**2 + s0 > 2147483647 == False [statically known]
+ [INFO] eval 4*s0**3 - 4*s0**2 + s0 <= 2147483647 [guard added] (_subclasses/fake_tensor.py:677 in conv)
```

So it looks like for the broken system a real tensor instead of a FakeTensor is used leading to failure to deduce `s0 <= 3` and instead introducing some `s1` such that it later fails to solve the complex inequality.

I can't find a reason for this and am hoping for some insight from the devs. Maybe this issue is known already?

The source on the machines is exactly the same, only the architecture is different (x86 Saphire Rapids vs POWER9)

### Versions

PyTorch version: 2.1.2
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux Server release 7.6 (Maipo) (ppc64le)
GCC version: (GCC) 11.3.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.17

CPU:
Architektur:                     ppc64le
Byte-Reihenfolge:                Little Endian
CPU(s):                          176
Liste der Online-CPU(s):         0-175
Modellname:                      POWER9, altivec supported
Modell:                          2.2 (pvr 004e 1202)
Thread(s) pro Kern:              4
Kern(e) pro Sockel:              22
Sockel:                          2
Übertaktung:                     aktiviert
Skalierung der CPU(s):           100%
Maximale Taktfrequenz der CPU:   3800,0000
Minimale Taktfrequenz der CPU:   2300,0000
L1d Cache:                       1,4 MiB (44 Instanzen)
L1i Cache:                       1,4 MiB (44 Instanzen)
L2 Cache:                        12 MiB (24 Instanzen)
L3 Cache:                        240 MiB (24 Instanzen)
NUMA-Knoten:                     8
NUMA-Knoten0 CPU(s):             0-87
NUMA-Knoten8 CPU(s):             88-175
NUMA-Knoten250 CPU(s):           
NUMA-Knoten251 CPU(s):           
NUMA-Knoten252 CPU(s):           
NUMA-Knoten253 CPU(s):           
NUMA-Knoten254 CPU(s):           
NUMA-Knoten255 CPU(s):           
Schwachstelle Meltdown:          Mitigation; RFI Flush, L1D private per thread
Schwachstelle Spec store bypass: Mitigation; Kernel entry/exit barrier (eieio)
Schwachstelle Spectre v1:        Mitigation; __user pointer sanitization, ori31 speculation barrier enabled
Schwachstelle Spectre v2:        Mitigation; Indirect branch serialisation (kernel only)

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==2.1.2
[conda] Could not collect

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by angelayi** [comment]
Hmm, I can't seem to reproduce this locally... on main and on torch version 2.1.2. Can you try on a nightly:
```
pip install --force-reinstall --pre torch=="2.3.0.dev20240108" -i https://download.pytorch.org/whl/nightly/cpu
```

**Comment by Flamefire** [comment]
This does not work as the failure is on PPC where PyTorch needs to be compiled from source. The working machine is an x86 which I guess is the same as yours

I can do some more digging but would need to know what you'd need. Using a debugger (debugpy) doesn't work as dynamo fails the tracing with a debugger attached. And I can't find where "s0 <= 3" or "-s0 + s1 + 1 >= 0" originates from. Using exceptions to get stacktraces when those values are generated/used (in `_log_guard`) might influence dynamo so I don't get a reasonable trace. The latest hint I have is https://github.com/pytorch/pytorch/blob/b6962208b85d35634294f6c620f6daf732f323b3/torch/_subclasses/fake_tensor.py#L853 which is entered on both and might return different results depending on the arch

**Comment by ezyang** [comment]
cc @avikchaudhuri ig

**Comment by Flamefire** [comment]
I just debugged further into the last hint I had and indeed:
- "s0 <= 3" is produced inside `params.use_mkldnn`:  [`at::symint::size<T>(weight, -2) > 3`](https://github.com/pytorch/pytorch/blob/20f394f10a389bcf13485929be8862f98ad4b322/aten/src/ATen/native/Convolution.cpp#L532C51-L532C87)
- Disabling MKLDNN "s0 < 17" is produced inside `params.use_nnpack` by [`at::symint::size<T>(weight, 2) < 17`](https://github.com/pytorch/pytorch/blob/20f394f10a389bcf13485929be8862f98ad4b322/aten/src/ATen/native/Convolution.cpp#L550)
- Disabling both (on PPC neither MKLDNN nor NNPACK are available and get disabled during configure) the error can be reproduced in x86, i.e. `USE_MKLDNN=0 USE_NNPACK=0 pip install .` when building from source

However knowing now how the sympy constraints are created, this example code reproduces the issue on a standard torch 2.1.2 installation:

```
import torch

class FunctionalConv2d(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.stride = (1, 1)
        self.padding = (0, 0)
        self.dilation = (1, 1)
        self.groups = 1

    def forward(self, x, weight, bias):
        return torch.nn.functional.conv2d(
            x,
            weight,
            bias,
            self.stride,
            self.padding,
            self.dilation,
            self.groups)

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = FunctionalConv2d()
        self.conv2 = FunctionalConv2d()

    def forward(self, x, weight, bias):
        x = self.conv1(x, weight, bias)
        x = torch.nn.functional.relu(x)
        x = self.conv2(x, weight, bias)
        return x

dtype = torch.float64  # Disable XNNPACK
inputs = (torch.randn(1, 3, 5, 5, dtype=dtype), torch.randn(3, 3, 3, 3, dtype=dtype), torch.rand(3, dtype=dtype))
with torch.backends.mkldnn.flags(False): # Disable MKLDNN
    gm, _ = torch._dynamo.export(M(), aten_graph=True)(*inputs)
```

**Comment by ezyang** [comment]
When I run your latest repro on a recent nightly build, I get

```
$ python wn.py
[2024-01-10 06:45:08,665] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Eq(-s0 + s1 + 1, -1) == False, this could result in accuracy problems
[2024-01-10 06:45:08,676] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Ne(s0**2 - 2*s0*s1 - 2*s0 + s1**2 + 2*s1 + 1, 1) == True, this could result in accuracy problems
[2024-01-10 06:45:08,691] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard 4*s0**3 - 4*s0**2*s1 - 8*s0**2 + s0*s1**2 + 4*s0*s1 + 4*s0 > 1 == True, this could result in accuracy problems
[2024-01-10 06:45:08,697] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Eq(-2*s0 + s1 + 2, -1) == False, this could result in accuracy problems
[2024-01-10 06:45:08,712] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Ne(4*s0**2 - 4*s0*s1 - 8*s0 + s1**2 + 4*s1 + 4, 1) == False, this could result in accuracy problems
[2024-01-10 06:45:08,719] torch.fx.experimental.symbolic_shapes: [WARNING] Ignored guard Ne(-2*s0 + s1 + 2, 1) == False, this could result in accuracy problems
```

Is this the error output or something differetn?

**Comment by ezyang** [comment]
Oh, this PR could matter because it affects when we insert guards. Contiguity calculation will typically trigger guards, so if it's lazy, then you might be able to avoid guarding at all if you don't poke it at all in the end.

We probably can come up with a repro that involves just manually feeding the guards into shape env and then produce guards.

**Comment by Flamefire** [comment]
I'm concerned about the correctness and reliability. From what I understand the `s0 <= 3` or even `s0 < 17` makes it resolve `4*s0**3 - 4*s0**2 + s0 > 2147483647 == False` "statically" and without that former guard that fails and ends up in the "univariate inequalities".   
This had me trying a workaround: Replacing https://github.com/pytorch/pytorch/blob/20f394f10a389bcf13485929be8862f98ad4b322/aten/src/ATen/native/Convolution.cpp#L557 by `return (at::symint::size<T>(weight, 2) < 17) && (at::symint::size<T>(weight, 3) < 17) && false;` works.    
But I guess having a sufficiently large kernel/weight (i.e. greater than 3 for MKLDNN or 17 for NNPACK) will produce a guard of `s0 >= 17` which again will not trivially resolve the inequation which sounds quite fragile.

Now I'm not sure why `self.print_source(self.symbol_to_source[expr][0])` is used at this point trying to convert the `x` from `CRootOf(4*x**3 - 4*x**2 + x - 2147483647, 0)` into "something" while that is seemingly `sympy.abc.x` so that seems to be a bug. Not only that: sympy is seemingly able to resolve that root so it should be able to reduce `(s0 <= CRootOf(4*x**3 - 4*x**2 + x - 2147483647, 0)` but is inhibited by that bug from getting to that point. I just ran `CRootOf(4*x**3 - 4*x**2 + x - 2147483647, 0).evalf(3)` which yielded "813" and `(s0 <= CRootOf(4*x**3 - 4*x**2 + x - 2147483647, 0)` is indeed reduced to `s0 <= 813` by sympy

So:
> We probably can come up with a repro that involves just manually feeding the guards into shape env and then produce guards.

sounds like a good idea to test and ultimately fix this issue and prevents it reappearing  in other situations.

**Comment by avikchaudhuri** [comment]
> Most notable change for me is Ne(s0**3 - 2*s0**2*s1 - 2*s0**2 + s0*s1**2 + 2*s0*s1 + s0, 0) to Ne(s0**2 - 2*s0*s1 - 2*s0 + s1**2 + 2*s1 + 1, 0)

Hmm, given `s0 != 0` these are morally equivalent.

**Comment by avikchaudhuri** [comment]
Regardless of which guards are emitted, the issue here seems to be that a solution returned by sympy's `reduce_inequalities` is not guaranteed to be well-formed, i.e., may contain unknown symbols (e.g., `x` here). So the fix should be to check this and gracefully fail (which should then cause a fall back to the existing failure case, which effectively emits the original expression instead of the solution).

I'll try to test for this directly by provoking `sympy` to emit `CRoot(...)`.
