### ISSUE TITLE
float8 ops on cpu broken in inductor

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#117119]
### 🐛 Describe the bug

If we have some code with device=cpu which uses float8, such as below, things are broken in inductor codegen:

```
def foo(x):                       
    x = x.to(torch.float8_e4m3fn) 
    return x                      
                                  
foo = torch.compile(foo)          
x = torch.randn(2, 2)             
x = foo(x)                        
print(x)                          
```

logs: https://gist.github.com/vkuzo/ae434bfe8a48c083e74377c313263a90 

can we fall back to eager mode on cpu?

### Versions

```
>>> torch.__version__
'2.2.0a0+git967863d'
```

**Comment by vkuzo** [comment]
cc @int3 , @ipiszy

**Comment by zhuhaozhe** [comment]
Enabled FP8 cast on CPU backendhttps://github.com/pytorch/pytorch/pull/117737

**Comment by zhuhaozhe** [comment]
Closed as https://github.com/pytorch/pytorch/pull/117737 merged. Feel free to re-open if there are still some issues.
