### ISSUE TITLE
If error is raised from generated Inductor Python file, should print full contents of file

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#117142]
### 🐛 Describe the bug

Working on https://fb.workplace.com/groups/1075192433118967/posts/1361376654500542 I see this error log:

```
  File "/tmp/torchinductor_nobody/rm/crmjicqcxalbf3t2imcizgvhz5p62a7ewxqwdbjddvfgfsjgz6g2.py", line 296, in call
    assert_size_stride(primals_3, (((((s4 // 21)*(s4 // (s4 // 21))) + ((s4 // 21)*(s5 // (s5 // 120)))) // 141), 2*((((s4 // 21)*(s4 // (s4 // 21))) + ((s4 // 21)*(s5 // (s5 // 120)))) // ((((s4 // 21)*(s4 // (s4 // 21))) + ((s4 // 21)*(s5 // (s5 // 120)))) // 141)), 256), (512*((((s4 // 21)*(s4 // (s4 // 21))) + ((s4 // 21)*(s5 // (s5 // 120)))) // ((((s4 // 21)*(s4 // (s4 // 21))) + ((s4 // 21)*(s5 // (s5 // 120)))) // 141)), 256, 1))
NameError: name 's4' is not defined
```

I would sure love to know what the contents of this file are! It's too bad they were lost. We should dump the file to log when we see an error was raised.

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by Chillee** [comment]
Is the file actually lost? at least locally, I'm usually able to print it out. Perhaps this is something unique to meta infra?

**Comment by ezyang** [comment]
This is a Meta infra thing, where the logs are on some remote host and there isn't an obvious way to ssh into the host that it failed on.

**Comment by eellison** [comment]
This is possible for some of our assertions. In this case, it's a python error so I don't know how we would print the whole file

**Comment by ezyang** [comment]
use torch_trace dedicated logs now
