### ISSUE TITLE
_IncompatibleKeys returned from nn.Module.load_state_dict

### ISSUE THREAD

**Issue by EricLBuehler** [pytorch/pytorch#117258]
Hello all,

While loading multiple adapters with `peft`, I get an `_IncompatibleKeys` object with many `missing_keys`, but no `incompatible_keys`. I have raised an issue on `peft` here: huggingface/peft#1323. However, the answer that I got was that:
> The _IncompatibleKeys comes up because of [this line](https://github.com/huggingface/peft/blob/6451cbd70c187dc7baeadeed701851ac7bdd6ec2/src/peft/utils/save_and_load.py#L211) in set_peft_model_state_dict :

> `load_result = model.load_state_dict(peft_model_state_dict, strict=False)`
> Here, peft_model_state_dict is the state dict containing our new adapter weights (and ONLY the new adapter weights). Internally, PEFT > will rename the state dict entries to use the new adapter name adapter2. So in my case, it looks like:

> `['base_model.model.transformer.h.0.attn.c_attn.lora_A.adapter2.weight', 'base_model.model.transformer.h.0.attn.c_attn.lora_B.adapter2.weight', ......]`
> When you call load_adapter, a new adapter is initialized first using add_adapter [here](https://github.com/huggingface/peft/blob/6451cbd70c187dc7baeadeed701851ac7bdd6ec2/src/peft/peft_model.py#L687). Next, when > we load the state dict for the new adapter using model.load_state_dict, PyTorch finds that all the entries for the new adapter are present, but the entries for the base model and the old adapter are not present. Hence you get a _IncompatibleKeys load result with a long list of missing keys (and no unexpected keys).

This means that the issue was cased by PyTorch not finding the keys for the base model and old adapter in the new state dict, which contains only entries for the new adapter's state dict. Therefore, it reports that there are missing keys. However, I note that the `missing_keys` attribute contains entries from both adapters. This means that the `missing_keys` are not simply the entries not in the new state dict.

Is this expected behavior? It appears that the parameters are actually loaded into the state dict, so is this warning superfluous?

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
From [the thread on the other issue](https://github.com/huggingface/peft/issues/1323#issuecomment-1887551886), it seems like some transformations are happening on the `peft` end that are causing this and this is not a PyTorch issue. 

> Here, peft_model_state_dict is the state dict containing our new adapter weights (and ONLY the new adapter weights). Internally, PEFT will rename the state dict entries to use the new adapter name adapter2. So in my case, it looks like:
'base_model.model.transformer.h.0.attn.c_attn.lora_A.adapter2.weight', 'base_model.model.transformer.h.0.attn.c_attn.lora_B.adapter2.weight', .......
When you call load_adapter, a new adapter is initialized first using add_adapter [here](https://github.com/huggingface/peft/blob/6451cbd70c187dc7baeadeed701851ac7bdd6ec2/src/peft/peft_model.py#L687). Next, when we load the state dict for the new adapter using model.load_state_dict, PyTorch finds that all the entries for the new adapter are present, but the entries for the base model and the old adapter are not present. Hence you get a _IncompatibleKeys load result with a long list of missing keys (and no unexpected keys).

Closing as complete, but feel free to reopen if you still feel that this is a PyTorch issue :)
