### ISSUE TITLE
AOTInductor support ABI stable item() call

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#117271]
### 🐛 Describe the bug

The current implementation looks like

```
    def codegen_dynamic_scalar(self, node):
        from .cpp import DTYPE_TO_ATEN

        (data,) = (t.codegen_reference() for t in node.inputs)
        if node.is_bool:
            self.writeline(f"bool {node.sym} = {data}.item() ? 1 : 0;")
        else:
            convert_type = DTYPE_TO_ATEN[node.inputs[0].get_dtype()].replace(
                "at::k", "to"
            )
            self.writeline(f"auto {node.sym} = {data}.item().{convert_type}();")
```

but this does not work for the ABI stable variant, where (at minimum) RAIITensorHandle doesn't have an item() method.

This is blocking landing https://github.com/pytorch/pytorch/pull/114148

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by desertfire** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/117989
