### ISSUE TITLE
AWS Key not found breaking tests

### ISSUE THREAD

**Issue by alinpahontu2912** [pytorch/pytorch#117257]
Seems like a bunch of tests started failing today.  I think the problem is some expired AWS key, but am not sure who can change it.
![Image](https://github.com/pytorch/pytorch/assets/56953855/a3fa90f4-7351-496f-a1c4-3b0c52ae3df9)

![Image](https://github.com/pytorch/pytorch/assets/56953855/56763b92-8a0f-4b87-8f0d-8822b6bcc098)

@malfet @peterjc123 

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
This is expected as we are in the progress of revoking all the AWS credentials to replace them with OIDC.  This is a high priority issue on our end, so please bear with us in the next few days.

**Comment by malfet** [comment]
Nightlies are green again, closing
<img width="1036" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/71a98e3f-f046-4638-8dcf-c2324380dd87">
