### ISSUE TITLE
torch.compile: full_backward_pre_hook induces a graph break

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#117266]
```
import torch
import torch.nn as nn

layer = nn.Linear(3, 3, bias=False)
layer.weight = nn.Parameter(torch.eye(3, dtype=torch.float))

def hook(module, grad_output):
    return tuple(go * 2 for go in grad_output)

@torch.compile(backend="eager", fullgraph=True)
def f(x):
    y = layer(x)
    return y

layer.register_full_backward_pre_hook(hook)
x = torch.randn(3, requires_grad=True)
y = f(x)
y.sum().backward()
print(x.grad)
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by wconstab** [comment]
what's the expected behavior? if we didn't graph-break on this, would we attach the hook to the autograd.function properly, or would we drop the hook?

**Comment by zou3519** [comment]
This seems supported now via compiled autograd
