### ISSUE TITLE
Number of arguments in scaled_dot_product_attention

### ISSUE THREAD

**Issue by iSach** [pytorch/pytorch#117240]
### 🐛 Describe the bug

In the documentation, `torch.nn.functional.scaled_dot_product_attention` has [7 parameters](https://pytorch.org/docs/main/generated/torch.nn.functional.scaled_dot_product_attention.html#torch.nn.functional.scaled_dot_product_attention), 3 of which are positional.

However, when running the following code:
```python
x = torch.randn(8, 16, 256)

# Works fine, returns Tensor of shape [8,16,256]
torch.nn.functional.scaled_dot_product_attention(x,x,x,attn_mask=None,dropout_p=0.0,is_causal=False,scale=None)
# Triggers a TypeError
torch.nn.functional.scaled_dot_product_attention(x,x,x,None,0.0,False,None)
```
The first call works fine, but the second call triggers this:
```
TypeError: scaled_dot_product_attention() takes from 3 to 6 positional arguments but 7 were given
```

Not naming the named arguments, even with the same values, results in this error. Am I missing a detail about Python? 

This error happens on both the stable version 2.1 and on the latest nightly version 2.3.0 (result of collect_env). This happens on both macOS and Linux.

### Versions

```
PyTorch version: 2.3.0.dev20240110
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1.2 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: version 3.28.1
Libc version: N/A

Python version: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:53:08)  [Clang 15.0.7 ] (64-bit runtime)
Python platform: macOS-14.1.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] configmypy==0.1.0
[pip3] functorch==1.13.1
[pip3] msgpack-numpy==0.4.8
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] pytorch-wavelets==1.3.0
[pip3] tensorly-torch==0.4.0
[pip3] torch==2.3.0.dev20240110
[pip3] torch-fidelity==0.3.0
[pip3] torch-harmonics==0.6.2
[pip3] torchaudio==2.2.0.dev20240110
[pip3] torchmetrics==0.11.4
[pip3] torchtyping==0.1.4
[pip3] torchvision==0.18.0.dev20240110
[conda] functorch                 1.13.1                   pypi_0    pypi
[conda] libopenvino-pytorch-frontend 2023.2.0             h965bd2d_0    conda-forge
[conda] msgpack-numpy             0.4.8                    pypi_0    pypi
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] numpy-base                1.26.3           py39ha9811e2_0  
[conda] pytorch                   2.3.0.dev20240110         py3.9_0    pytorch-nightly
[conda] pytorch-wavelets          1.3.0                    pypi_0    pypi
[conda] tensorly-torch            0.4.0                    pypi_0    pypi
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-harmonics           0.6.2                    pypi_0    pypi
[conda] torchaudio                2.2.0.dev20240110        py39_cpu    pytorch-nightly
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchtyping               0.1.4                    pypi_0    pypi
[conda] torchvision               0.18.0.dev20240110        py39_cpu    pytorch-nightly
```

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki @albanD

**Comment by drisspg** [comment]
So everyone of the args except the last, `scale` is positional. The first 3 have no default values and the second 3 have default values. I can see how this might be confusing.

Let me think of think of how the docs can be updated to better reflect this

**Comment by iSach** [comment]
Is there a particular reason for scale to be keyword-only? I think this is confusing in the documentation because it is not mentioned. I was not really aware of that in Python and found out in between.If you think there is no need to change, feel free to close this issue!Le 24 janv. 2024 à 22:10, Driss Guessous ***@***.***> a écrit :﻿
So everyone of the args except the last, scale is positional. The first 3 have no default values and the second 3 have default values. I can see how this might be confusing.
Let me think of think of how the docs can be updated to better reflect this

**Comment by drisspg** [comment]
The reason for keyword-only is somewhat historical since this argument was added after the initial creation, I think this is a good issue and we should update the docs
