### ISSUE TITLE
Make cuda graphs skipped messages more informative

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#117281]
### 🐛 Describe the bug

In https://fb.workplace.com/groups/1075192433118967/posts/1361398451165029/ we have an example where a user is wondering why cuda graphs is skipped. All it says is "skipped due to mutated inputs". What inputs were mutated? Where did this mutation come from? There is no way to easily tell. We clearly have this info, let's actually print it.

cc @mcarilli @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @eellis

### Versions

main

**Comment by eellison** [comment]
For this particular issue, we first need to add stack_traces to the generated `copy_` nodes.
