### ISSUE TITLE
The ‘reduce’ operation will allocate memory for a 0-element tensor and the initial value in memory is set to 0.

### ISSUE THREAD

**Issue by Lanezzz** [pytorch/pytorch#117222]
### 🐛 Describe the bug

```
# python source code 
import torch
a = torch.randn(2,2,0,3)
print(a)
b = torch.sum(a, dim=2, keepdim=True)
print(b)
```
```
# error results
# a
tensor([], size=(2, 2, 0, 3))
# b
tensor([[[[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]]]])
# Shouldn't 'b' be an empty tensor?
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0a0+git063c60e
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.17

Python version: 3.8.8 (default, Apr 13 2021, 19:58:26)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                256
On-line CPU(s) list:   0-255
Thread(s) per core:    2
Core(s) per socket:    64
座：                 2
NUMA 节点：         2
厂商 ID：           AuthenticAMD
CPU 系列：          23
型号：              49
型号名称：        AMD EPYC 7H12 64-Core Processor
步进：              0
CPU MHz：             1500.000
CPU max MHz:           2600.0000
CPU min MHz:           1500.0000
BogoMIPS：            5199.85
虚拟化：           AMD-V
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           512K
L3 缓存：           16384K
NUMA 节点0 CPU：    0-63,128-191
NUMA 节点1 CPU：    64-127,192-255
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht sy                                                                                                                                                                scall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclm                                                                                                                                                                ulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_le                                                                                                                                                                gacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 c                                                                                                                                                                dp_l3 hw_pstate sme retpoline_amd ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflusho                                                                                                                                                                pt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbr                                                                                                                                                                v svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip ove                                                                                                                                                                rflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.0a0+git120e5e3
[pip3] torch-tb-profiler==0.1.0b3
[pip3] torchvision==0.15.1a0+42759b1
[conda] mkl                       2022.1.0           hc2b9512_224    http://jfrog.tecorigin.net/artifactory/api/conda/tecotp-v                                                                                                                                                                ir_conda
[conda] mkl-include               2023.1.0         h06a4308_46343    http://jfrog.tecorigin.net/artifactory/api/conda/tecotp-v                                                                                                                                                                ir_conda
[conda] numpy                     1.24.3           py38hf838250_0    http://jfrog.tecorigin.net/artifactory/api/conda/tecotp-v                                                                                                                                                                ir_conda
[conda] numpy-base                1.24.3           py38h1e6e340_0    http://jfrog.tecorigin.net/artifactory/api/conda/tecotp-v                                                                                                                                                                ir_conda
[conda] torch                     2.0.0a0+git120e5e3           dev_0    <develop>
[conda] torch-tb-profiler         0.1.0b3                   dev_0    <develop>
[conda] torchvision               0.15.1a0+42759b1          pypi_0    pypi

**Comment by colesbury** [comment]
This is expected behavior. You can define the sum of an empty tensor a variety of ways (like 0, or error). PyTorch chooses to define it as `0`. This matches Python and NumPy's behaviors. For example, `torch.tensor([]).sum() => 0`, not an empty tensor.

Extending this to multiple dimensions means that the dimensions you sum over have result size 1 (if keepdims=True)
