### ISSUE TITLE
can pytorch dataparallel scatter less batch size for the master gpu card?

### ISSUE THREAD

**Issue by mingminzhen** [pytorch/pytorch#11730]
For some task like segmentation, the label and loss computation will need some larger memory than general task, which leads to large memory consumption for mater gpu card. 
How can I set the master card (gpu:0) less batch size than other slave gpu cards?
For example, batchsize(5) and gpus(2) will lead to scatter results (3, 2) for 0,1 cards;
batchsize(5) and gpus(3) will lead to scatter results (2,2,1) for 0,1,2 cards.
Is it possible to get the results (2,3) and (1,2,2) for the scatter results?
And how?

**Comment by SsnL** [comment]
You can move the label and loss computation inside your model and parallelize those to different GPUs as well.

**Comment by mingminzhen** [comment]
@SsnL Is there any example for that?

**Comment by SsnL** [comment]
Not really, but it should be very straightforward to do that. You can just move it in the `forward()` definition and return the loss. DataParallel will gather the losses to main GPU, and you can do backward on that loss on main GPU.
