### ISSUE TITLE
Eliminate compile time ranges for a simpler analysis

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#117361]
### 🐛 Describe the bug

This emerged while I was working on https://github.com/pytorch/pytorch/issues/117268

Today, the way we represent that something is size-like is by maintaining a parallel compile time value range which is more refined than the runtime value range: typically, a size-like integer will be `[2, inf]` at compile time but `[0, inf]` at runtime. We this value range, we can make inferences; for example, we can conclude that `i0 != 0`, `i0 * 12 != 0`, `i0 != 1`, which are important queries we must be able to answer when constructing tensors and testing for broadcasting, the most common situations where `expect_true` cannot be directly used.

However, is not sound. Suppose I have a size-like x `x in [2, inf]`. Then `2 - x in [-inf, 0]`, and so if I separately assert that `2 - x >= 0`, then I immediately have proved that `2 - x == 0` and `x == 2`. But really, I wanted x to vary between 0, 1 and 2 and directly specializing on this quantity is wrong; I would have much rather kept `2 - x` around and give more imprecise answers to queries on it.

There's also an orthogonal problem. Say I have two size like integers x and y, and I assert `x + y == 30`. Technically, I can substitute away y such that `y = 30 - x`. But if I do this, using value ranges only, I will forget that y is size-like, because `x in [2, inf]`, but post substitution we can only infer `y in [-inf, 28]`. This problem applies to value ranges in general, but the most important value range we typically have to deal with is the size-like value range.

# Proposal

Instead of using the value range, I propose the following:

1. Instead of maintaining a separate compile time value range, we simply have a set of expressions which are considered size-like
2. We never do substitutions on size-like symbols except if the substituted expression is obviously size like (actually, we can just use value ranges to figure this out: the resulting bound post substitution must be `[2, inf]` or better)
3. In cases where we perform a conditional on expressions that may contain unbacked symbols, but the two branches are valid (we can't use expect_true because we know one side of the branch will error), we instead designate one side of the branch as the "generic" branch. For example, if I have a conditional that tests whether or not numel is zero, the non-zero case is the generic branch, as we expect it to generalize for the zero case. Instead of raising a guard on data dependent error, if we can't figure out that the zero branch is applicable, we just go down the generic branch.

The feasibility of this proposal is predicated on whether or not it is possible to perform step (3) on all of the important control flow in C++. I think it should be possible, because we DO know that `[2, inf]` is enough to discharge all of these situations, so we basically just have to find all the spots it is discharging and make them go the same way in each case.

### Versions

main

**Comment by ezyang** [comment]
cc @tugsbayasgalan

**Comment by lezcano** [comment]
>typically, a size-like integer will be [2, inf] at compile time but [0, inf] at runtime

Why can a size-like be [0, inf] at runtime? Shouldn't it be specialised? Or are you talking specifically here about export?

I think the proposed solution still has too many edge-cases. Wouldn't it be feasible to simply have a flag that controls whether a bound on a size-like object is `[2, inf]` and `[0, inf]`? Export could use the latter one, `torch.compile` the former one. Then size-like symbols would not be special, and doing bijective transformations like `y = 3 - x` would never be an issue when it comes to the range analysis.

**Comment by eellison** [comment]
Compile time ranges is useful for our own analysis and externally: see, our pass to optimize indexing, https://github.com/pytorch/pytorch/issues/115137, and recent discussion on how to run triton kernels which we don't have example inputs for. 

The bad refinement you're mentioning is a symptom of the a runtime range of `[0, inf]` but a compile time range of `[2, inf]` which is the root of the unsoundness. 

Throwing out a few ideas:

- What about introducing a poison value 0 in value range analysis, similar to `nan` or `undef` which will remain even as we run propagation.
- I know this is a maybe not a priority but have we done an ablation on how exactly the guards on `== 1` are introduced or what happens if we don't introduce them ? I have a suspicion that most of the guards have to do with either broadcasting or determining strides. I still think it's possible that if we were to rewrite some of this logic with custom helpers we might be avoid adding the guards. We could try things like just running metas with `[1, ...]` and `[n, ...]` and post factor doing analysis to see that outcome is the same in order to drop guards. I don't think this confusion is going to clear up anytime soon. See, this recent example: https://github.com/pytorch/pytorch/issues/115137#issuecomment-1897131241.

**Comment by ezyang** [comment]
> Why can a size-like be [0, inf] at runtime? Shouldn't it be specialised? Or are you talking specifically here about export?

There's more backstory about it at https://pytorch-dev-podcast.simplecast.com/episodes/unbacked-symints (I added an AI generated transcript if you want to skim) but the short answer is that if I have an unbacked symint (that is, an integer which I don't know the value of at compile time) and I cannot assume that it is not equal to zero or one, PyTorch will immediately choke because if you use it in any nontrivial way like to construct a tensor, we will poke at it when we are trying to find out if the tensor is empty, or if it's contiguous, or any other number of special cases regarding 0/1. However, it turns out that a graph that works for all sizes >= 2, usually works for size = 1/0 as well, and so for export's sake as well as eagers, we've chosen to unsoundly assume that size-like integers are never 0/1 for the purpose of compile time analysis.

> Export could use the latter one, torch.compile the former one

Won't work, the refined range is load bearing for dealing with data-dependent sizes like the output of item() and nonzero()

> Compile time ranges is useful for our own analysis and externally: see, our pass to optimize indexing, https://github.com/pytorch/pytorch/issues/115137, and recent discussion on how to run triton kernels which we don't have example inputs for.

Sorry, to clarify, I would propose that when we do our own analysis at compile time, we exclusively use what we currently refer to as the "runtime range". I'm not proposing we eliminate this analysis entirely.

> What about introducing a poison value 0 in value range analysis, similar to nan or undef which will remain even as we run propagation.

I have no idea how this would work. Typically the way a poison value works is that it propagates itself as compute happens. But if we poison the lower range of all of our size-like integers, the end effect is that we are left with an upper bound analysis only (no lower bound analysis). This seems dramatically less useful than the value ranges we have right now, where we can bracket lower bounds.

> I know this is a maybe not a priority but have we done an ablation on how exactly the guards on == 1 are introduced or what happens if we don't introduce them ? I have a suspicion that most of the guards have to do with either broadcasting or determining strides. I still think it's possible that if we were to rewrite some of this logic with custom helpers we might be avoid adding the guards. We could try things like just running metas with [1, ...] and [n, ...] and afterwards doing analysis to see that outcome is the same in order to drop guards. I don't think this confusion is going to clear up anytime soon.

I mean, this is what I did (almost exactly) a year ago before we settled for unsound 0/1 specialization. Sample PRs like https://github.com/pytorch/pytorch/pull/92234

The conclusion was that for ResNet, it was almost, kind of feasible to dodge all the bullets by making enough pre-computed quantities in tensor constructor lazy. But people didn't like it, and it was definitely going to be a whackamole game. To be fair, the current situation with unbacked symints has also been whackamole, but we at least don't have to worry about 0/1 cases.

**Comment by eellison** [comment]
> I mean, this is what I did (almost exactly) a year ago before we settled for unsound 0/1 specialization. Sample PRs like https://github.com/pytorch/pytorch/pull/92234

This is the rewriting logic to avoid guards part.. I'm still not sure if something like:  `running metas with [1, ...] and [n, ...] and afterwards doing analysis to see that outcome is the same in order to drop guards` is feasible.

**Comment by eellison** [comment]
> I mean, this is what I did (almost exactly) a year ago before we settled for unsound 0/1 specialization. Sample PRs like https://github.com/pytorch/pytorch/pull/92234

This is the rewrite some of the guard logic part but not trying to run a meta with both symint of n>=2 and n=1 and afterwards resolve if we can remove guards.. 

>  This seems dramatically less useful than the value ranges we have right now, where we can bracket lower bounds.

How often is the lower bound of symints even used ? For most of the optimizations I can think of the upper bound is the relevant quantity here. And it's incorrect to use the lower bounds right now in the case of 0, 1. This would just be for the input or unbacked symints and intermediary quantities propagated from them could have more refined lower bounds.

**Comment by ezyang** [comment]
> I'm still not sure if something like: running metas with [1, ...] and [n, ...] and afterwards doing analysis to see that outcome is the same in order to drop guards is feasible.

I mean, what exactly do you mean by this? There are logistical problems everywhere with the obvious applications of this approach:

**Exponential blowup.** Suppose that you have N unbacked SymInts. To exhaustively test that the outcome is the same in all cases, it is necessary to do exponentially many trials (for every combination of is 1 / not 1). This is required to discover problems of the following class:

```
if i0 != 1:
  if i1 == 1:
    if i2 != 1:
      assert False
```

Without setting this exact combination of 1 / not 1, we cannot discover that one branch raises an exception.

Contrast this with my proposal, where we (soundly) fail immediately on the first conditional, saying that we do not know if i0 is 1 or not. In situations where the `i0 == 1` branch is an optimization (e.g., just assume we don't know if the tensor is contiguous) / can be conservatively assumed not to hold (e.g., just assume that broadcasting won't occur here), we would have some way of the user annotating the branch saying "trust me, pick this side of the conditional if you don't know which way to go."

**What "outcome" is the same?** In the limit, whether or not the outcome is the same is down to whether or not we generate the same code at the Inductor level. But to actually do this would necessitate running the entirety of the compilation stack multiple times, just to finally say it's the same. Which, chances are, it's not (all of the errors we are currently grinding through with regards to inductor and unbacked SymInts are all examples of cases where they would not be the same.) Even if you try something simpler, like the ATen decomposition is the same, you still have to run Dynamo/AOTAutograd all the way to completion before you can do this comparison.

Like, you can't "only" run the meta to do this analysis, all that tells you is that the shapes are the same, it doesn't tell you that the semantics are the same!

> How often is the lower bound of symints even used ? For most of the optimizations I can think of the upper bound is the relevant quantity here. And it's incorrect to use the lower bounds right now in the case of 0, 1. This would just be for the input or unbacked symints and intermediary quantities propagated from them could have more refined lower bounds.

Well, I mean, it's extremely important to know that a symint is not negative lol. Ditto with knowing that a symint is not 0 or 1. As for higher lower bounds, I suspect it is most useful in situations where you are doing things like downsampling/resnet style blocks, where the higher lower bound is necessary to let you show that you don't zero out the size later. IDK, maybe @avikchaudhuri knows better off the top of his head.

Without a lower bound, an expression like `100 - s0` (which can arise when solving for equations like `s0 + s1 == 100`) has no useful bound at all. IDK, seems like a bad idea. @nunoplopes maybe for more thoughts.

**Comment by eellison** [comment]
> symint is not negative lol 

If it's a symint that comes from a tensor shape you can keep the bound at 0 without doing any difficult analysis no?

**Comment by ezyang** [comment]
If I have s0 is a size-like integer, to infer that `s0 - 2` is a size-like integer, I must give `s0` a lower bound of 2, or I need some other way of figuring out that this expression is size-like.

**Comment by eellison** [comment]
> Suppose that you have N unbacked SymInts

I think this is a very uncommon case, and potentially we could fallback here to the unsound current approach and warn.

**Comment by nunoplopes** [comment]
BTW, instead of unsoundly assuming that some int != 0 and int != 1, can't we move those things to the frame guard?
Call it optimistic compilation. If it holds for the 99% of the cases, great, we've optimized the program correctly and it's all fine. If not, well, you're likely going to get an error from PyTorch anyway, so we fallback to the slow mode.

**Comment by ezyang** [comment]
> I think this is a very uncommon case, and potentially we could fallback here to the unsound current approach and warn.

On the contrary, it is very common! In KJT use case, there is an unbacked SymInt per feature on the KJT, and typically hundreds of features.

> BTW, instead of unsoundly assuming that some int != 0 and int != 1, can't we move those things to the frame guard?
Call it optimistic compilation. If it holds for the 99% of the cases, great, we've optimized the program correctly and it's all fine. If not, well, you're likely going to get an error from PyTorch anyway, so we fallback to the slow mode.

This is what we do for non-data dependent. The problem with data dependent is we would need to somehow do the bailout midway through graph execution, but by then it is often too late (because you've already done a bunch of operations at this point, possibly destructively!)

**Comment by eellison** [comment]
> On the contrary, it is very common! In KJT use case, there is an unbacked SymInt per feature on the KJT, and typically hundreds of features.

How many are used in a single operator ?

**Comment by ezyang** [comment]
If you do something like cat, hundreds of unbacked symints can be involved in one operation.
