### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled 

### ISSUE THREAD

**Issue by Shreyanshjainnn** [pytorch/pytorch#117358]
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
 
i have been getting this error when i try to generate image in fooocus 
i don't have nivida gpu but with google collab i could use the fooocus but not in its fullest so what can i do could anyone help??

**Comment by malfet** [comment]
Please use https://discuss.pytorch.org/ to ask questions about PyTorch 
PyTorch works with CUDA on Colab, if this is not the case for you, please open a new issue with the link to colab notebook that fails
