### ISSUE TITLE
scaled_dot_product_attention behave differently from xformers

### ISSUE THREAD

**Issue by ZoeHaydn** [pytorch/pytorch#117354]
### 🐛 Describe the bug

official torch 2.1.2+cu121 for linux on pip is not compiled with USE_FLASH_ATTENTION 

When I try to use device = ‘cuda’ I have this error:

RuntimeError: No available kernel.  Aborting execution.
### Versions

official torch  2.1.2+cu121  for linux

cc @seemethere @malfet @osalpekar @atalman @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by malfet** [comment]
Please run `python -mtorch.utils.collect_env` and post output here or just tell which GPU are you trying to run it on

**Comment by drisspg** [comment]
Can you also post the warning messages?

**Comment by drisspg** [comment]
I'm going to close this issue. The warning messages says to use the fused kernels inputs need to be 4d. There is some work in expanding this to be the case but as for right now the resolution is to call "unsqueeze" to create a singleton dimension. I also think that it's not an issue that SDPA is different than Xformers.
