### ISSUE TITLE
Add options for activation function in LSTM and GRU

### ISSUE THREAD

**Issue by chenzhekl** [pytorch/pytorch#1173]
Sometimes it is useful to disable the activation or use a different activation function than `tanh`. For example, when implementing this [paper](https://arxiv.org/abs/1506.04878), it is needed to disable output non-linearity. Similar options are provided in [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/LSTMCell).

**Comment by khaledvic** [comment]
@chenzhekl have you found a simple way to do this?

**Comment by chenzhekl** [comment]
No, I finally re-implemented them from scratch.

**Comment by khaledvic** [comment]
I'm struggling to find an implementation that uses fast Cudnn kernal to replace torch.nn.GRU or LSTM

**Comment by linjian93** [comment]
@khaledvic have you solved it finally?

**Comment by louisabraham** [comment]
Hi, I would like this feature, too!

**Comment by artix41** [comment]
I also need that feature (for [this paper](https://arxiv.org/pdf/1706.04008.pdf))

**Comment by gchanan** [comment]
we use a fused implementation of the current activations, so we can't support this (without an advanced compiler) without a significant performance reduction.  While we plan to use a compiler, much of the community has moved on to transformers, so we think freezing the current API makes the most sense.

**Comment by shamoons** [comment]
Can transformers be used for seq2seq?

**Comment by ahmed-fau** [comment]
> we use a fused implementation of the current activations, so we can't support this (without an advanced compiler) without a significant performance reduction. While we plan to use a compiler, much of the community has moved on to transformers, so we think freezing the current API makes the most sense.

I think RNNs (especially GRUs) are still the common choice to build efficient sequence models for edge devices. It would be pretty good if there is any future plan to enable this. 

Many thanks for your efforts!
