### ISSUE TITLE
-ffast-math leads to different results in torchinductor generated code

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#117346]
### 🐛 Describe the bug

`inductor/test_torchinductor_dynamic_shapes.py -k test_round_correctness`  may fail while `inductor/test_torchinductor.py -k test_round_correctness` works which is due to rounding of halfway cases, e.g. `-8.5` which should be rounded to nearest even (i.e. "-8") but could be rounded to `-9` because `-ffast-math` enables `-funsafe-math-optimizations` and `-fno-rounding-math ` which is described as
> This flag assumes that the rounding mode is round to nearest. 

And indeed on e.g. POWER I was able to reproduce this based on the code torchinductor produces:
```cpp
#include <iostream>
#include <cmath>
#include <vector>

using T = double;

extern "C" void kernel(const T* in_ptr0,
                       T* out_ptr0,
                       const long ks0)
{
    {
        #pragma GCC ivdep
        for(long i0=static_cast<long>(0L); i0<static_cast<long>(ks0); i0+=static_cast<long>(1L))
        {
            auto tmp0 = in_ptr0[static_cast<long>(i0)];
            auto tmp1 = std::nearbyint(tmp0);
            out_ptr0[static_cast<long>(i0)] = tmp1;
        }
    }
}


int main()
{
    std::vector<T> in(16, -8.5);
    decltype(in) out(in.size());
    kernel(in.data(), out.data(), in.size());
    for(const auto t: out)
        std::cout << t << ", ";
    std::cout << '\n';
}
```

Compiling this with `g++ -O3 -ffast-math  -mcpu=native` on PPC yields a series of "-9"s while omitting `--ffast-math` yields all `-8`.

I'm wondering what the correct approach about this should be:
1. Workaround in the test to pass `-fno-unsafe-math-optimizations` to the compiler to fix the affected test
2. Unconditionally pass that option on e.g. PPC (and potentially other affected platforms)

### Versions

PyTorch 2.1.2

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by ezyang** [comment]
Here is a spicy take: what if we just don't compile with ffast-math LOL

**Comment by msaroufim** [comment]
If fast math was always correct we'd just call it math

**Comment by Flamefire** [comment]
FWIW: I created a patch that disables the unsafe math optimizations in the tests via a decorator: https://github.com/easybuilders/easybuild-easyconfigs/blob/f346ffda44e960bde61c00771a7d8197b5cb242b/easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2_fix-test_torchinductor-rounding.patch

It seems that mostly the rounding behavior is affected especially as that leads to absolute differences of "1.0" where other optimizations are less likely to yield such high diffs. Especially as the test(s) are made to trigger those halfway cases.

Of course removing `-ffast-math` is an option but not sure what the performance impact would be and if those inaccuracies matter in real models **IF** they are at least consistent.

**Comment by Valentine233** [comment]
@Flamefire The flag `funsafe-math-optimizations` was already removed by https://github.com/pytorch/pytorch/pull/113347. I recognized that your PyTorch version was 2.1.2. Could please try with the latest PyTorch?

**Comment by Flamefire** [comment]
> @Flamefire The flag `funsafe-math-optimizations` was already disabled by #113347. I recognized that your PyTorch version was 2.1.2. Could please try with the latest PyTorch?

It just isn't in a released PyTorch version where the latest currently is 2.1.2. Haven't tested the nightly builds but checking the PR I'm sure that will work as it is basically the same as the patch I used.

**Comment by Valentine233** [comment]
Sure, I would close the issue as solved with the nightly branch. Feel free to reopen if any problem.
