### ISSUE TITLE
[DCP]Torch FSDP dedups empty tensors and spuriously emits warnings

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#117392]
### 🐛 Describe the bug

When using FSDP with small tensors on high GPU counts, torch will have empty tensors on some ranks. For example, `[1024x16]` tensor on 32 GPUs will have an empty tensor on the last 16 ranks. 

When checkpointing, Torch will emit warnings saying it is deduping tensors (all the empty tensors are deduped). Torch should not emit warning for this case. Torch should also shard on largest dim.

### Versions

Torch 2.1.2 and Torch nightly

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by awgu** [comment]
@mvpatel2000 is this model or optimizer state dict? (or both?)

> Torch should also shard on largest dim.

If I am understanding your suggestion correctly, I think this is hard 😢 Our sharded state dicts use `DTensor`, and under that paradigm, FSDP is dim-0 sharding. cc: @wanchaol

**Comment by mvpatel2000** [comment]
> @mvpatel2000 is this model or optimizer state dict? (or both?)

Both!

> > Torch should also shard on largest dim.
> 
> If I am understanding your suggestion correctly, I think this is hard 😢 Our sharded state dicts use `DTensor`, and under that paradigm, FSDP is dim-0 sharding. cc: @wanchaol

Got it. I think this is more of a minor optimization that doesn't matter a ton.

More broadly it would be nice if FSDP had fewer assumptions on # of dims in DTensor for FSDP and instead did something like grab first sharding dim, but that's a side note :P

**Comment by wanchaol** [comment]
@fegin @wz337 @LucasLLC is this a bug in DCP? for sharded DTensor case where ranks > shards, there shouldn't be some dedup logic?

**Comment by wz337** [comment]
> @fegin @wz337 @LucasLLC is this a bug in DCP? for sharded DTensor case where ranks > shards, there shouldn't be some dedup logic?

I think we still do write the WriteItem for the empty DTensor in the current design. Let me try a minimal repro and a fix afterwards.

**Comment by LucasLLC** [comment]
Wrt to the `duplicate keys` warning, I believe this is currently set at info. 

https://github.com/pytorch/pytorch/blob/d0fc268918236d8a56cc0ad82ace001160281a17/torch/distributed/checkpoint/_dedup_tensors.py#L46

I agree this log is messy though, and it would be removed in this PR: https://github.com/pytorch/pytorch/pull/116469 

Additionally, I believe it's expected behavior that any `WriteItem` is de-duplicated based on the state dict key, so it makes sense to me that this log is being generated.

@malfet would you happen to have the emitted warning handy?

cc @fegin @wz337

**Comment by mvpatel2000** [comment]
@LucasLLC  just to confirm, you are saying that line will be removed in a PR soon?

**Comment by mvpatel2000** [comment]
@LucasLLC  actually I think this log line is useful, but it would nice to skip empty tensors (eg I shard a tensor that is [8] across 16 GPUs so it is size 0 on ranks 9-15). I'm not sure how to do this though -- happy to open a PR with some guidance

**Comment by LucasLLC** [comment]
I believe this log was removed when we opted for load balancing Tensors. Please re-open issue if this still exists
