### ISSUE TITLE
ValueError: torch.cuda.is_available() should be True but is False

### ISSUE THREAD

**Issue by awolter27** [pytorch/pytorch#117303]
### 🐛 Describe the bug

I'm trying to train a custom model using kohya. I have been running into the same error for over 1 week now. I've attached photos of my error message as well as some information about my computer and the applications on it. Any help would be much appreciated!!!

error message:

![error message](https://github.com/pytorch/pytorch/assets/123532540/d211bd5b-1919-4d24-8b9b-12dd0d9f2c5f)

nvcc --version:

![nvcc --version](https://github.com/pytorch/pytorch/assets/123532540/f91b9f92-eb4f-483b-84ed-b2614bf5b138)

nvidia-smi:

![nvidia-smi](https://github.com/pytorch/pytorch/assets/123532540/938f8b65-0ff8-46d6-9be0-5f336a039f92)

python -m torch.utils.collect_env:

![python -m torch utils collect_env](https://github.com/pytorch/pytorch/assets/123532540/29d428c2-594c-4bdd-8b49-f0930ca0eb26)

### Versions

I must be doing this wrong. 

D:\Kohya\kohya_ss>python collect_env.py
python: can't open file 'D:\\Kohya\\kohya_ss\\collect_env.py': [Errno 2] No such file or directory

cc @seemethere @malfet @osalpekar @atalman @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by malfet** [comment]
Thank you for opening the issue, but from what I see it does not sound like a PyTorch problem, but rather an issue with your local setup, where you are running collect_env in default environment, but SDXL is installed into virtual environment that might not have CUDA accelerated PyTorch installed at all.

Please use https://discuss.pytorch.org/ to ask questions/seek help on how PyTorch can be used, but if you believe you've run in a situation, where it does not work as expected, do not hesitate to open a new issue.

**Comment by awolter27** [comment]
@tringwald I am in kohya_ss -> venv -> Scripts, but I'm not quite sure what you're asking. I don't see any files that say pytorch, torch, or CUDA. I will look into this! 

@malfet I appreciate your help. I will ask my question in another forum.
