### ISSUE TITLE
Add privateuseone flags for c10::EventFlag

### ISSUE THREAD

**Issue by chentianyi16** [pytorch/pytorch#117341]
### 🚀 The feature, motivation and pitch

My team is working on adding a custom backend for pytorch and would like to add privateuseone flags (PRIVATEUSEONE_DEFAULT and PRIVATEUSEONE_DISABLE_TIMING) in c10::EventFlag.

I noticed that current flags (https://github.com/pytorch/pytorch/blob/main/c10/core/impl/DeviceGuardImplInterface.h#L32) like BACKEND_DEFAULT and PYTORCH_DEFAULT can only ensure default usage but cannot control whether to disable timing or not. This can make it difficult for a custom backend to create a non-default event on the C++ front end PyTorch.

**Comment by ezyang** [comment]
Instead of adding PRIVATEUSEONE_DISABLE_TIMING, would adding PYTORCH_DISABLE_TIMING (and BACKEND_DISABLE_TIMING, maybe?) help?

**Comment by chentianyi16** [comment]
Thank you for the reply. Yes, adding flags like PYTORCH_DISABLE_TIMING and BACKEND_DISABLE_TIMING helps. And I am a little bit confused about the flags in c10::EventFlag, the following code block is the one-to-one mapping done by CUDA:
`switch (flag) {
      case EventFlag::PYTORCH_DEFAULT:
      case EventFlag::CUDA_EVENT_DISABLE_TIMING:
        cuda_flag = cudaEventDisableTiming;
        break;
      case EventFlag::BACKEND_DEFAULT:
      case EventFlag::CUDA_EVENT_DEFAULT:
        cuda_flag = cudaEventDefault;
        break;
      default:
        TORCH_CHECK(false, "CUDA event received unknown flag");
    }
`
Seems CUDA_EVENT_DISABLE_TIMING and CUDA_EVENT_DEFAULT are redundant. Are the 2 flags added just to make it look clearer for cuda users?

**Comment by ezyang** [comment]
I'm not sure. I'd suggest blaming git history and asking the original author / checking the PR

**Comment by chentianyi16** [comment]
I've checked the PR [https://github.com/pytorch/pytorch/pull/23424](url) and I found that the purpose of using flags like CUDA_EVENT_DISABLE_TIMING is to dispatch to the appropriate backend. Therefore, seems adding flags like PRIVATEUSEONE_DISABLE_TIMING is more in line with the logic of c10::Event when it was created.

**Comment by ezyang** [comment]
cc @albanD

**Comment by albanD** [comment]
Sorry for the delay here.
The CUDA and HIP -specific flags are not used anywhere. I think we should, as Ed suggested, just use the generic PYTORCH_DEFAULT and BACKEND_DEFAULT and remove all the other flags from this enum. Would you be able to do that?

**Comment by chentianyi16** [comment]
Sure, I'll remove the CUDA and HIP -specific flags in my PR
