### ISSUE TITLE
DISABLED test_lazy_init (__main__.TestCuda)

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#117430]
Platforms: rocm

This test was disabled because it is failing on [ROCm6.0 CI upgrade PR](https://github.com/pytorch/pytorch/pull/116270) eg.: https://hud.pytorch.org/pr/pytorch/pytorch/116270#20399217880

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
ROCm 6.0 CI migration not complete yet.  Reopening.

**Comment by jeffdaily** [comment]
ROCm 6.0 CI migration not complete yet. Reopening.
