### ISSUE TITLE
Autotuning for foreach codegen

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#117447]
### 🚀 The feature, motivation and pitch

Currently we don't apply autotuning to foreach codegen, but this is a good opportunity to get perf wins across our benchmark suite. There are cases where models with many small tensors are able to be executed faster by hand-fused kernels, this should allow the foreach codegen to be more competitive with hand fused kernels.

cc @crcrpar @mcarilli @janeyx99 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @vincentqb @jbschlosser @albanD

**Comment by mlazos** [comment]
Should be completed by https://github.com/pytorch/pytorch/pull/124969

**Comment by jataylo** [comment]
@mlazos seems that foreach kernels still may not be autotuning by default?
```
# combo_kernel autotuning options: 0 - disable, 1 - enable except for foreach,
# 2 - enable for all
combo_kernels_autotune = 1
```
