### ISSUE TITLE
Easy mypy with daemon / incremental checking with lintrunner

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#117438]
### 🐛 Describe the bug

lintrunner will never run mypy with daemon so I find in practice that it is the slowest part of lint when I run it. However, mypy supports incremental / daemon mode, which is a lot faster to recheck files. Make an easy way to use it this way.

For daemon to work, need 

### Versions

main

cc @malfet @xuzhao9 @gramster @seemethere @pytorch/pytorch-dev-infra

**Comment by ezyang** [comment]
cc @suo

**Comment by Skylion007** [comment]
> For daemon to work, need

@ezyang Did you mean to finish typing stuff out here?

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/117048

**Comment by huydhn** [comment]
I'm resolve this issue after https://github.com/pytorch/pytorch/pull/118475 to use dmypy
