### ISSUE TITLE
[Caffe2] Problem with copying CUDA tensor to CPU tensor

### ISSUE THREAD

**Issue by ShahriarSS** [pytorch/pytorch#11746]
Hi. I was working on a previous Caffe2 C++ code that I wrote that worked before but now it just keeps crashing. I wrote a simple code to see if it works but it did not. The problem is copying CUDA tensor to CPU tensor I think. Here is the code:

```c++
#include <caffe2/core/context_gpu.h>
#include <caffe2/core/init.h>
#include <caffe2/core/tensor.h>
#include <iostream>

using namespace std;

int main()
{
	caffe2::GlobalInit();
	auto C = new caffe2::CUDAContext();

	caffe2::TensorCUDA T({100 * 100}, std::vector<float>(100 * 100, 1), C);
	caffe2::TensorCPU T1(T);

	const auto &D = T1.data<float>();
	std::vector<float> data(D, D + T1.size());

	cout << data << endl;

	return 0;
}
```

There are not much examples for Caffe2 with C++ but from what I could gather I think this code should work. 

My operating system is fedora. My graphics card is GTX 1050 and the version of CUDA installed is 9.2. I compiled Caffe2 from source with GCC 7.3 and I set CUDA_HOST_COMPILER to GCC 6.4.

I run the above code with:
optirun ./program

**Comment by ezyang** [comment]
Yes, the problem is that `caffe2::TensorCPU` no longer does what you think it does.  You need to do something like `caffe2::Tensor T1(T, caffe2::CPU);` to initiate a copy to CPU.

CC @jerryzh168 maybe we should just delete the `TensorCPU` and `TensorCUDA` aliases; they are a bug farm.

**Comment by jerryzh168** [comment]
@ezyang These are there since we still have a few codemod that's not done, e.g. Get<TensorCPU> -> Get<Tensor>(CPU).

But for the code above, shouldn't the default constructor of Tensor be deleted?

**Comment by ShahriarSS** [comment]
Well thank you it solved this problem.

**Comment by ezyang** [comment]
@jerryzh168 Can't do it for PyTorch, we heavily rely on Tensors being copyable (with pointer semantics). For example, people regularly write `Tensor x = y;`
