### ISSUE TITLE
PyTorch forward-mode AD fails when returning non-differentiable outputs

### ISSUE THREAD

**Issue by wjakob** [pytorch/pytorch#117491]
### 🐛 Describe the bug

I am currently implementing a custom function (`torch.autograd.Function`) that passes auxiliary state besides differentiable tensors.

This well-supported in backward/reverse-mode AD: one simply returns `None` from `Function.backward` for each non-differentiable input.

For `Function.jvp`, one would expect the same to hold for non-differentiable outputs. Indeed, the documentation says

> Each argument is the gradient w.r.t the given input, and each returned value should be the gradient w.r.t. the corresponding output. If an output is not a Tensor or the function is not differentiable with respect to that output, you can just pass None as a gradient for that input [sic., I think it should say "output" here]. 

Anyways, this is not how it works at the moment. The following simple test below fails with
```
Traceback (most recent call last):
  File "/Users/wjakob/test.py", line 32, in <module>
    _, dual_output = fn(dual_input)
                     ^^^^^^^^^^^^^^
  File "/Users/wjakob/pytorch/torch/autograd/function.py", line 562, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: bad_optional_access
```

Reproducer:
```python
import torch
import torch.autograd.forward_ad as fwAD

bug = True

class Add1(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        if not bug:
            return x + 1
        else:
            return object(), x + 1

    @staticmethod
    def jvp(ctx, gx):
        if not bug:
            return gx
        else:
            return None, gx

fn = Add1.apply

primal  = torch.tensor([1,2,3], dtype=torch.float, requires_grad=True)
tangent = torch.tensor([4,5,6], dtype=torch.float)

with fwAD.dual_level():
    dual_input = fwAD.make_dual(primal, tangent)

    if not bug:
        dual_output = fn(dual_input)
    else:
        _, dual_output = fn(dual_input)

    jvp = fwAD.unpack_dual(dual_output).tangent
    print(dual_input)
    print(dual_output)
    print(jvp)
```

You can set `bug=False` to remove the non-differentiable return value, in which case everything works fine.

The culprit is the following code in `pytorch/torch/csrc/autograd/custom_function.cpp` around line 132:

```cpp
  for (const auto i : c10::irange(num_outputs)) {
    const auto& out =
        outputs[i].has_value() ? outputs[i].value() : at::Tensor();
    auto out_tensor_impl = raw_outputs[i].value().unsafeGetTensorImpl();
    bool is_differentiable =
        (non_differentiable.count(out_tensor_impl) == 0 &&
         isDifferentiableType(raw_outputs[i].value().scalar_type()));
```

In particular, `raw_outputs[i].value()` fails since this `std::option<>` entry has no value (curiously, the line above has a special case and assigns an `at::Tensor`). Also, curiously, there is an internal assertion checking `raw_outputs[i].has_value()` but that check doesn't happen until some lines below when the access has already been performed.

I am not sufficiently steeped in the nuances relating  `raw_outputs[i]` and ` outputs[i]` to give a definite suggestion. However, it seems to me that this whole loop iteration should simply be skipped if return value `i` isn't differentiable.

### Versions

```Collecting environment information...
PyTorch version: 2.3.0a0+git003c900
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.6.2 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.1
Libc version: N/A

Python version: 3.12.1 (main, Dec  8 2023, 18:57:37) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.6.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] torch==2.3.0a0+git003c900
[conda] Could not collect```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by ezyang** [comment]
cc @albanD
