### ISSUE TITLE
[distributions]: Creating `Categorical` is 100x slower than `Normal`

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#11747]
In RL, we often need to create a distribution over actions at each time step during rollout by using the policy network to select actions. It seems now creating `Categorical` distribution is much slower than `Normal` distribution during rollout. 

## Toy code:

```python
from time import time
import torch
import torch.nn.functional as F
from torch.distributions import Categorical, Normal


t = time()
for _ in range(100):
    probs = F.softmax(torch.randn(1, 32), -1)
    dist = Categorical(probs)
t1 = time() - t
print(t1)

t = time()
for _ in range(100):
    mu = torch.randn(1, 32)
    std = torch.randn(1, 32)
    dist = Normal(mu, std)
t2 = time() - t
print(t2)

print(t1/t2)
```
gives 
```
0.5241701602935791
0.002852201461791992
183.77739697400318
```
which almost 180x slower for `Categorical`. 

By tracing back to the code, it turns out the slow part is contributed by [this line](https://github.com/pytorch/pytorch/blob/master/torch/distributions/categorical.py#L50), another toy code to show this

```python
t = time()
for _ in range(100):
    p = F.softmax(torch.randn(1, 32), -1)
    p = p/p.sum(-1, keepdim=True)
print(time() - t)
```
gives
```
0.4742550849914551
```

## System Info

PyTorch: 0.4.1

**Comment by t-vi** [comment]
So I ran your script and get <3, I think this should be OK. Please do reopen if you think otherwise.
