### ISSUE TITLE
代码运行错误

### ISSUE THREAD

**Issue by Liiiiaictx** [pytorch/pytorch#117462]
运行代码出现AttributeError: module 'torch.backends' has no attribute 'mps'这个错误，该怎么解决？

**Comment by malfet** [comment]
Please use http://discuss.pytorch.org/ to ask general question how PyTorch can be used

(According to google translate issue body says "AttributeError: module 'torch.backends' has no attribute 'mps' occurs when running the code. How to solve it?")
