### ISSUE TITLE
Frequent "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#117403]
Possibly related to the keep-going label, because that's all I use nowadays.

I've noticed an uptick in ""!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"" error messages in CI. E.g. 
![image](https://github.com/pytorch/pytorch/assets/5652049/a1805df3-b77e-47a6-891f-cd4e1d0e0f30)
Example logs: https://github.com/pytorch/pytorch/actions/runs/7506557433/job/20438701304

Is it just me, or is it the keep-going label, or is it CI right now? cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
For context, "KeyboardInterrupt" is a misnomer, what it actually means is that job hits the time limit... (and looks like ONNX jobs are on edge right now)

**Comment by huydhn** [comment]
Yeah, this is the error when the test shard takes longer than 30m and times out.  Agree that the error looks a bit weird if you don't have the context.  It matches the following log classifier rule https://github.com/pytorch/test-infra/blob/main/aws/lambda/log-classifier/ruleset.toml#L183-L185.  May be we can print out something more user friendly and match that instead.

cc @clee2000

**Comment by malfet** [comment]
Ok, though it's not the shard timeout (which is 4 hours), but rather individual test times out. (I wonder if this is because slow job classifier does not work)

**Comment by huydhn** [comment]
> Ok, though it's not the shard timeout (which is 4 hours), but rather individual test times out. (I wonder if this is because slow job classifier does not work)

I need to explain it clearer.  What you think is correct, mean the test file shard that we implement, i.e. 30m is the timeout value of running one test file shard like `onnx/test_fx_op_consistency 4/6`.  It's not the job timeout, which is 4h

**Comment by clee2000** [comment]
after #116319 onnx started testing a lot more (takes ~3x longer) and test times failed to update 2 days in a row.  I fixed the job earlier today and kicked the job to update the test times just now, the test times I see now look accurate.  I'm not sure why it's not retrying, the practical time limit is actually 90min, my guess is that the 5 second wait time for pytest to finish after getting the keyboard interrupt is not long enough, I'll try to debug that but it's hard to repro

**Comment by huydhn** [comment]
This is fixed by https://github.com/pytorch/pytorch/pull/117865.
