### ISSUE TITLE
[Caffe2]I don't know whether GPU support is right,No handlers could be found for logger "caffe2.python.net_drawer"

### ISSUE THREAD

**Issue by celticssssss** [pytorch/pytorch#11754]
## Issue description
I install Caffe2 based on the website:
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile

After command 'sudo make install -j20' is finished, i type:
cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"

Then, the result is 'Sucess'.

After that, i want to know whether GPU support is right ,i type command:
python caffe2/python/operator_test/activation_ops_test.py

Then, theresult is :

![1537185720 1](https://user-images.githubusercontent.com/35193543/45622006-2953ba00-bab5-11e8-8b64-5e1c392aa7c3.jpg)

And my system info is 
![1537185997 1](https://user-images.githubusercontent.com/35193543/45622055-50aa8700-bab5-11e8-8c41-0a9f6de90425.jpg)

please help me. thanks

**Comment by pjh5** [comment]
That is just a warning, not an error. net_drawer is only used for visualization purposes. If you want to get net_drawer working, then install it's needed dependencies https://github.com/pytorch/pytorch/blob/master/caffe2/python/net_drawer.py#L21 .

**Comment by celticssssss** [comment]
fine I install the dependencies by this code 

sudo apt install python-pydot python-pydot-ng graphviz

and it say this
caffe@admin1:~/pytorch$ python caffe2/python/operator_test/activation_ops_test.py
/usr/local/lib/python2.7/dist-packages/caffe2/python/hypothesis_test_util.py:75: HypothesisDeprecationWarning: 
The min_satisfying_examples setting has been deprecated and disabled, due to
overlap with the filter_too_much healthcheck and poor interaction with the
max_examples setting.

  verbosity=hypothesis.Verbosity.verbose))
/usr/local/lib/python2.7/dist-packages/caffe2/python/hypothesis_test_util.py:84: HypothesisDeprecationWarning: 
The min_satisfying_examples setting has been deprecated and disabled, due to
overlap with the filter_too_much healthcheck and poor interaction with the
max_examples setting.

  verbosity=hypothesis.Verbosity.verbose))
/usr/local/lib/python2.7/dist-packages/caffe2/python/hypothesis_test_util.py:92: HypothesisDeprecationWarning: 
The min_satisfying_examples setting has been deprecated and disabled, due to
overlap with the filter_too_much healthcheck and poor interaction with the
max_examples setting.

  verbosity=hypothesis.Verbosity.verbose))

![1537586334 1](https://user-images.githubusercontent.com/35193543/45912771-514a7100-be59-11e8-8f82-861ded847230.jpg)

I don't know what is mean ...

**Comment by pjh5** [comment]
@celticssssss these are also just warnings
