### ISSUE TITLE
Pytorch build from source fails [Windows] (error C2039: 'aligned_alloc': is not a member of '`global namespace'')

### ISSUE THREAD

**Issue by lancerts** [pytorch/pytorch#117589]
Pytorch build from source fails [Windows], seems to be a different issue than the fix https://github.com/pytorch/pytorch/pull/117497.

Environment:
1. vs2022
2. cuda 12.1
3.  /MSVC/14.38.33130

Steps followed:
https://github.com/pytorch/pytorch/wiki/Best-Practices-to-Edit-and-Compile-Pytorch-Source-Code-On-Windows

error:

third_party\pocketfft\pocketfft_hdronly.h(156): error C2039: 'aligned_alloc': is not a member of '`global namespace''

<img width="650" alt="1705448507(1)" src="https://github.com/pytorch/pytorch/assets/7495155/274c7ffb-c35b-4006-82b8-3cb01463647e">

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by malfet** [comment]
Hmm, looks like you've skipped the part about installing MKL on your system, as pocketfft is only used when MKL is not available (and I don't think anyone ever tried building PyTorch with pocketfft on Windows)

**Comment by malfet** [comment]
Though one should probably update PocketFFT to include https://github.com/mreineck/pocketfft/issues/5 (PR is coming)

**Comment by lancerts** [comment]
Thanks for the quick suggestion.

**Comment by lancerts** [comment]
Can confirm with MKL installed, the error goes away~

**Comment by Manamama** [comment]
still happens AD 2025, on Termux. this does not help: `cmake .. \
  -DCMAKE_BUILD_TYPE=Release \
  -DINTERN_BUILD_MOBILE=ON \
  -DUSE_CUDA=OFF \
  -DUSE_ROCM=OFF \
  -DUSE_VULKAN=OFF \
  -DUSE_XPU=OFF \
  -DBUILD_PYTHON=OFF \
  -DBUILD_TEST=OFF \
  -DBUILD_BINARY=OFF \
  -DBUILD_SHARED_LIBS=ON \
  -DUSE_FBGEMM=OFF \
  -DUSE_OPENMP=ON \
  -DUSE_MKLDNN=ON \
  -DUSE_NUMPY=ON `
