### ISSUE TITLE
Does yolov5 support deployment on ARM platforms? Currently

### ISSUE THREAD

**Issue by qiyuefun** [pytorch/pytorch#117533]
### 🐛 Describe the bug

Great god, I need your help. The situation is as follows. Currently, YOLOv5 is being trained on the Ubuntu system Torch 2.0.1 Torchvision 0.15.2, and CUDA 117 version to convert the model best. pt to YOLOv5 Torchscript. I want to deploy it to the ARM platform. Is this idea feasible? Is it supported? If so, where can I download and compile using Libtorch

### Versions

Great god, I need your help. The situation is as follows. Currently, YOLOv5 is being trained on the Ubuntu system Torch 2.0.1 Torchvision 0.15.2, and CUDA 117 version to convert the model best. pt to YOLOv5 Torchscript. I want to deploy it to the ARM platform. Is this idea feasible? Is it supported? If so, where can I download and compile using Libtorch

cc @jbschlosser @malfet @snadampal

**Comment by malfet** [comment]
This sounds like something that should be discussed on http://discuss.pytorch.org
We do not build individual libtorch ARM binaries, but one can always build it from source or extract lib torch.so from the .whl file.

**Comment by qiyuefun** [comment]
Thank you for your reply. I'll give it a try
