### ISSUE TITLE
[rocm] Enable faster load of fused-sgd

### ISSUE THREAD

**Issue by crcrpar** [pytorch/pytorch#117599]
Currently it's turned off to avoid the hang of test_cuda 

              I don't have an explanation yet, but since the kernel had two potential paths (`use_faster_load_store`), I used a preprocessor #ifdef for rocm to force the other path.  This worked.  So there was something wrong with using the faster load store path.  This is my diff that worked for ROCm

```diff
diff --git a/aten/src/ATen/native/cuda/FusedSgdKernel.cu b/aten/src/ATen/native/cuda/FusedSgdKernel.cu
index a00b47ff79..0c52ee5783 100644
--- a/aten/src/ATen/native/cuda/FusedSgdKernel.cu
+++ b/aten/src/ATen/native/cuda/FusedSgdKernel.cu
@@ -87,6 +87,7 @@ struct FusedSgdMathFunctor {
         init_args<depth>(args, tl, chunk_idx, chunk_size, tensor_loc)};
     n -= chunk_idx * chunk_size;

+#ifndef USE_ROCM
     const auto use_faster_load_store =
         (n % kILP == 0) && (chunk_size % kILP == 0) && all_aligned;
     if (use_faster_load_store) {
@@ -116,7 +117,9 @@ struct FusedSgdMathFunctor {
           load_store(args[2], r_args[2], i_start, 0);
         }
       }
-    } else {
+    } else
+#endif
+    {
       for (auto i_start = 0; i_start < n && i_start < chunk_size;
            i_start += blockDim.x * kILP) {
         load_args<depth>(r_args, args, i_start, chunk_size, n);
```

_Originally posted by @jeffdaily in https://github.com/pytorch/pytorch/issues/116585#issuecomment-1887886009_
            

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by petrex** [comment]
@crcrpar Any particular unit tests we can use to validate the feature?
