### ISSUE TITLE
Error when compiling on a Mac (10.11.6)

### ISSUE THREAD

**Issue by abeschneider** [pytorch/pytorch#1175]
Got error:

```
.../pytorch/torch/csrc/allocators.h:4:10: fatal error: 
      'type_traits' file not found
#include <type_traits>
         ^
In file included from torch/csrc/Size.cpp:4:
In file included from .../pytorch/torch/csrc/THP.h:37:
.../pytorch/torch/csrc/allocators.h:4:10: fatal error: 
      'type_traits' file not found
#include <type_traits>
```

Was able to fix this by adding `-stdlib=libc++` to `extra_compile_args` in `setup.py`:

```Python
extra_compile_args = ['-std=c++11', '-Wno-write-strings', '-stdlib=libc++']
```

**Comment by soumith** [comment]
this is not the correct fix. as we mention in our readme, you have to set

export MACOSX_DEPLOYMENT_TARGET=10.9 # if OSX

**Comment by abeschneider** [comment]
Ah, okay. That makes sense. It hadn't occurred to because usually when I do an update I don't need to set the environmental variable and when I follow the instructions for installation I wouldn't see that error. Also, I am avoiding setting it in my `.bashrc` since (at least for me) it seems to have to change with my OS, and thus it seems like a dangerous thing to do.

Would it make sense to add a check in `setup.py` if you are an on Mac and the variable is not set? I'm happy to submit a PR for this.

Thanks!

**Comment by soumith** [comment]
this only applies on OSX and anaconda installs, so adding it to setup.py doesn't make sense here.
you could alias a bash command if you'd like:
alias pytorchsetup='MACOSX_DEPLOYMENT_TARGET=10.9 python setup.py install`
