### ISSUE TITLE
[ONNX] transformers version on CI is outdated

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#117660]
Currently, the transformers version on ONNX CI is still 4.32.1, while the released one is 4.36.2. There are lots of Config/Modeling changes that the outdated tests potentially make our guarding less robust, and it also increases the difficulty of developing/maintaining transformers related models of conversion. The version should be bumped.

**Comment by titaiwangms** [comment]
cc @BowenBao @thiagocrepaldi @wschin

**Comment by thiagocrepaldi** [comment]
That is a good point. this is where we pin it https://github.com/pytorch/pytorch/blob/da6abaeeacedc872ada6577fa1dd0c6c8024188a/.ci/docker/common/install_onnx.sh#L29

**Comment by thiagocrepaldi** [comment]
ps: when the issue is opened from onnx to onnx, and thus don't need Meta's triaging the issue, we can also add the `triaged` label :)

**Comment by titaiwangms** [comment]
Should we just update it, or we want to discuss for another approach?
