### ISSUE TITLE
ops.reduction is required to return multiple values which is weird

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#117676]
### 🐛 Describe the bug

As best as I can tell, nearly every op which can be virtualized on ops returns a single, opaque value, EXCEPT reduction

```
    def reduction(
        self, dtype, src_dtype, reduction_type, value
    ) -> Union[tuple[str, ...], str]:
        line = self.parent_handler.reduction(dtype, src_dtype, reduction_type, value)
        num_values = reduction_num_outputs(reduction_type)
        varnames = [f"tmp{next(self.var_counter)}" for _ in range(num_values)]
        self.output.writeline(f"{','.join(varnames)} = {line}")
        return tuple(varnames) if num_values > 1 else varnames[0]
```

and this is relied upon at WelfordReduction

```
    def store_reduction(self, output_name, indexer, vars, reduction_vars):
        values = ops.reduction(
            self.dtype,
            self.src_dtype,
            self.reduction_type,
            self.inner_fn(vars, reduction_vars),
        )
        value = values[self.output_index]
        return ops.store_reduction(output_name, indexer(vars), value)
```

Is the special case for reduction truly required? Is there truly no other way to do it?

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @jansel @peterbell10 

### Versions

main

**Comment by peterbell10** [comment]
For `reduction_type="welford_combine"` we take `value` as a tuple of IR values `mean, m2, weight` and simultaneously reduce over all 3 quantities resulting in the new `mean, m2, weight` values. This is a single combined operation, that can't be split into 3 separate reductions. 

I guess we could work around the problem by passing `output_index` to `ops.reduction`, but in my view this obfuscates the fact that there is only a single reduction operation and we expect it to be fused together into a single reduction.

Another option might be to have the tuple itself be an IR value and have an `ops.getitem` that extracts the output value, but that would just be a tuple in disguise and would still need special handling in most ops handlers.

**Comment by ezyang** [comment]
Blast, alright, I guess multi-return is just going to be like this.
