### ISSUE TITLE
dynamo + autograd.Function: dynamo doesn't model multiple `ctx.save_for_backward` calls.

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#117652]
This repro fails, but passes in eager:
```
import torch

class MyFunc(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, y):
        ctx.save_for_backward(x)
        ctx.save_for_backward(x, y)
        return x * y

    @staticmethod
    def backward(ctx, out_grad):
        x, y = ctx.saved_tensors
        return out_grad * x, out_grad * y

def f(x, y):
    return MyFunc.apply(x, y)

x = torch.ones(2, requires_grad=True)
y = torch.ones(2, requires_grad=True)
out = f(x, y)
```

It fails with:
```
  File "/data/users/hirsheybar/b/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in run
    and self.step()
  File "/data/users/hirsheybar/b/pytorch/torch/_dynamo/symbolic_convert.py", line 744, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/hirsheybar/b/pytorch/torch/_dynamo/symbolic_convert.py", line 1501, in UNPACK_SEQUENCE
    assert len(val) == inst.argval
AssertionError:

from user code:
   File "/data/users/hirsheybar/b/pytorch/tmp.py", line 17, in f
    return MyFunc.apply(x, y)
  File "/data/users/hirsheybar/b/pytorch/torch/_dynamo/variables/misc.py", line 306, in trampoline_autograd_bwd
    return fn_cls.backward(*args, **kwargs)
  File "/data/users/hirsheybar/b/pytorch/tmp.py", line 12, in backward
    x, y = ctx.saved_tensors
```

The bug: in eager mode, if you run `ctx.save_for_backward()` multiple times, I believe the autograd engine will discard your previous calls and only save the last call. Currently, it looks like dynamo appends multiple `save_for_backward` calls into the same list: https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/misc.py#L521

The fix is hopefully simple: instead of appending, overwrite the old list to recover the behavior from eager.

cc @ezyang @msaroufim @wconstab @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by twumasipennoh** [comment]
@bdhirsh is this issue still ongoing? I would like to take it

**Comment by zou3519** [comment]
We just need to merge https://github.com/pytorch/pytorch/pull/117667

**Comment by twumasipennoh** [comment]
So are you saying that I can take it after #11766 is merged? Or that this issue is already handled in #11766?
