### ISSUE TITLE
ATen operation list missing aten.sum

### ISSUE THREAD

**Issue by anieto-groq** [pytorch/pytorch#117637]
### 📚 The doc issue

The list of ATen operations at https://pytorch.org/docs/main/torch.compiler_ir.html has `aten.sum.dim_IntList`, but is missing `aten.sum`.

cc @SherlockNoMad @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by ydwu4** [comment]
@SherlockNoMad maybe we can have a discussion tmr?

**Comment by zhxchen17** [comment]
@ydwu4 any update :)

**Comment by SherlockNoMad** [comment]
`aten.sum(x)` can be decomposed into `aten.sum.dim_IntList(x, dim=[])`, so aten.sum doesn't need to be a core aten op.

**Comment by zhxchen17** [comment]
closing this since we can already decompose aten::sum
