### ISSUE TITLE
[Dynamo] Better support DTensor

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#117670]
### 🐛 Describe the bug

Meta internal use case is going to compile a model with multiple DTensor functions, which Dynamo doesn't support very well.
* [DTensor] torch._dynamo.exc.Unsupported: call_method DeviceMeshVariable() size [ConstantVariable(int)] {}: 
* [DTensor] if device_mesh.get_coordinate() is None, Unsupported: DeviceMeshVariable() get_coordinate [] {}: [P1038156868]
* [DTensor] if requires_grad != local_tensor.requires_grad, Unsupported: 'skip function TensorBase._make_wrapper_subclass in file Builtin _make_wrapper_subclass': 
* [DTensor]: mesh_dim_size = mesh.size(idx): call_method DeviceMeshVariable() size [ConstantVariable(int)] {}: 
* [DTensor]: torch._dynamo.exc.Unsupported: 'skip function warn in file Builtin warn'', filename is None': [P1038205479]
* [DTensor]: Unsupported: call_method PlacementVariable() is_partial in DTensor.redistribute: [P1042145847]
* [DTensor]: Unsupported: call_method PlacementVariable() is_replicate [] {} in _FromTorchTensor.forward:

### Versions

N/A

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by bdhirsh** [comment]
cc @wanchaol 🙂

**Comment by anijain2305** [comment]
Closing this as we have more defined workstream for DTensor.
