### ISSUE TITLE
UNSTABLE rocm / linux-focal-rocm5.7-py3.8 / test (default)

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#117642]
## Reason
This job seems to have been broken for a while, in the meantime new issues got introduced.

```
RuntimeError: CUDA driver API confirmed a leak in __main__.TestCompileTransformsCUDA.test_compile_vmap_hessian_cuda! Caching allocator allocated memory was 2048 and is now reported as 3072 on device 0. CUDA driver allocated memory was 364380160 and is now 385351680.
```

This job recently have been re-enabled after marked as unstable on https://github.com/pytorch/pytorch/issues/115312 

Logs example: https://github.com/pytorch/pytorch/actions/runs/7553025920/job/20563934659

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by jeffdaily** [comment]
@jeanschmidt Our CI is unstable due to the mem leak check?  Is it providing a bad signal for PRs or the trunk?

**Comment by jeanschmidt** [comment]
@jeffdaily yes :)
