### ISSUE TITLE
Missing examples for auto-disabled tests

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#117649]
See  https://github.com/pytorch/pytorch/issues/117638

![image](https://github.com/pytorch/pytorch/assets/5652049/ddfc751f-eaac-49e1-9890-70316ef657d7)

Clicking on "recent examples" goes to https://hud.pytorch.org/flakytest?name=test_ind&suite=TestIsnan, which fails to load:
![image](https://github.com/pytorch/pytorch/assets/5652049/93151f9a-0684-4b63-91cb-dd0e11077974)

Clicking on "most recent trunk [workflow logs](https://github.com/pytorch/pytorch/runs/20562637130)." goes to trunk, which shows that the test passed.

I would have hoped that "recent examples" gets me to a testx-like UI where I can click on past failures and then read their logs.

cc @ZainRizvi @kit1980 @huydhn @clee2000 @pytorch/pytorch-dev-infra

**Comment by zou3519** [comment]
A suggestion is: how difficult is to grep for the test failure, copy +/- 50 lines above and below it, and then just paste it into the issue once? Reading through logs is difficult because the logs are really big and one needs to actually get to PyTorch HUD's logviewer (instead of GitHub actions logviewer) for a better experience.

**Comment by clee2000** [comment]
I think this is a subset of https://github.com/pytorch/pytorch/issues/118015 that's mostly fixed by https://github.com/pytorch/test-infra/pull/4902.  Closing this in favor of the other one so it's all in one place
