### ISSUE TITLE
[c10d] Refactor ProcessGroupNCCL to use single device

### ISSUE THREAD

**Issue by kwen2501** [pytorch/pytorch#117756]
### 🚀 The feature, motivation and pitch

After removing the `*_multigpu` python APIs, we can now refactor cpp code in ProcessGroupNCCL to make it simpler.

Without changing the Backend API signature yet, we can do so by simply taking the tensor or device out once we get into a function:
```
auto tensor = tensors[0];
auto device = devices[0];
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by wconstab** [comment]
would like to discuss this one more, also considering if we want to support multi-thread DDP in 8-gpu host again in the future.

**Comment by kwen2501** [comment]
It seems orthogonal to me. In this RFC, single device means single device per thread, not per process.

**Comment by kwen2501** [comment]
Closing via https://github.com/pytorch/pytorch/pull/119099 and https://github.com/pytorch/pytorch/pull/119421
