### ISSUE TITLE
Deterministic max pooling in cudnn v6

### ISSUE THREAD

**Issue by supakjk** [pytorch/pytorch#1177]
According to http://developer.download.nvidia.com/compute/machine-learning/cudnn/secure/v6/prod/Doc/cuDNN_v6.0_ReleaseNotes.pdf?autho=1491203214_38b05e2597e10fefeea6c2b7598c70ee&file=cuDNN_v6.0_ReleaseNotes.pdf , cudnn v6 supports deterministic max pooling.

It would be great if PyTorch can also choose max pooling to be deterministic when using cudnn.

**Comment by ngimel** [comment]
Pytorch does not use cudnn for max pooling. Max pooling algo that pytorch uses is always deterministic.
