### ISSUE TITLE
UserWarning: ONNX export unsqueeze with negative axis -1 might cause the onnx model to be incorrect. 

### ISSUE THREAD

**Issue by SpadgerBoy** [pytorch/pytorch#117753]
UserWarning: ONNX export unsqueeze with negative axis -1 might cause the onnx model to be incorrect. Negative axis is not supported in ONNX. Axis is converted to 1 based on input shape at export time. Passing an tensor of different rank in execution will be incorrect.
  "Passing an tensor of different rank in execution will be incorrect.")

I encountered this issue when exporting the pytorch model as an onnx model. It seems that the unsqueeze (-1) operation is not supported in onnx. After my tracking, it seems that the unsqueeze (-1) operation is in the function scatter_add_. But due to the absence of the function scatter_ add_, I'm not sure if the unsqueeze (-1) operation was used in function scatte_add_。I don’t know how to modify the Python code. What should I do.

**Comment by justinchuby** [comment]
That looks like a warning you may be able to ignore, if the exported model is correct.

**Comment by thiagocrepaldi** [comment]
Hi @SpadgerBoy, as Justin pointed out, this is just a warning; many times the model just works for your scenario/input.

If the exported model doesn't behave as expected, raise a bug with a executable repro and we can see if that particular scenario can be fixed or maybe we can suggest a change to your model to avoid the issue altogether.

We can only help you if we get a repro :)
