### ISSUE TITLE
[inductor][cpu]cait_m36_384 fp32 static shape default wrapper single thread performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#117743]
### 🐛 Describe the bug

<table border="1" role="table">
  <thead>
    <tr>
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
    <tr>
      <td>cait_m36_384</td>
      <td>1</td>
      <td>0.845182</td>
      <td>4.210067068</td>
      <td>3.5582729046663757</td>
      <td>96.197948</td>
      <td>1</td>
      <td>0.97062</td>
      <td>3.666166209</td>
      <td>3.55845424577958</td>
      <td>93.097843</td>
      <td>0.87</td>
      <td>1.0</td>
      <td>0.87</td>
      <td>0.97</td>
    </tr>

</table><p dir="auto">SW info</p><table border="1" role="table">
  <thead>
    <tr>
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td><a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/pytorch/pytorch/commit/ea7e22973572b5fcf43ea05897c2cf56ace392da/hovercard" href="https://github.com/pytorch/pytorch/commit/ea7e22973572b5fcf43ea05897c2cf56ace392da"><tt>ea7e229</tt></a></td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>770d5cf7</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>dc83b38</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>c11d758</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>58366ab</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td><a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/pytorch/pytorch/commit/1d231d1be03e66c1e3c929dd1d743f0358951d7d/hovercard" href="https://github.com/pytorch/pytorch/commit/1d231d1be03e66c1e3c929dd1d743f0358951d7d"><tt>1d231d1</tt></a></td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td><a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/pytorch/pytorch/commit/f228c8b8cac3db634516c7101dee077cbaa026ab/hovercard" href="https://github.com/pytorch/pytorch/commit/f228c8b8cac3db634516c7101dee077cbaa026ab"><tt>f228c8b</tt></a></td>
      <td>/</td>
    </tr>
  </tbody>
</table>

Repro:
bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) single inference performance timm_models cait_m36_384 float32 first static default 0
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/39130c74339ede608a375b94041771468d2fdcdd
[timm_models-cait_m36_384-inference-float32-static-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13975341/timm_models-cait_m36_384-inference-float32-static-default-performance-single-drop_guilty_commit.log)
cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @WeizhuoZhang-intel @chuanqi129

**Comment by Valentine233** [comment]
Checked that the issue seems the same root cause as https://github.com/pytorch/pytorch/issues/108754. With the fix https://github.com/pytorch/pytorch/commit/8820dda943ac471933d0d8cc4b640c78181c2a86, perf has been back. Could you please double check for the commit? @zxd1997066

**Comment by zxd1997066** [comment]
checked the following 4 commit on c6i.16xlarge instance, the issue seems still exists.
**guilty commit 39130c7:**
0.852x
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
cpu,cait_m36_384,1,0.852403,4110.096988,70.032401,0.963041,656.391782,681.582182,1341,1,0,0

**commit before guilty commit d0b725e:**
0.963x
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
cpu,cait_m36_384,1,0.963269,3650.876328,66.156018,0.962042,656.004710,681.887744,1341,1,0,0

**8820dda:**
0.857x
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
cpu,cait_m36_384,1,0.856990,4093.782706,95.840805,0.959102,656.160768,684.140954,1341,1,0,0

**latest commit 5a2ff3f:**
0.856x
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,cait_m36_384,1,0.856163,4091.410660,67.249668,0.952648,632.599757,664.043520,1341,1,0,0,0,0

**Comment by Valentine233** [comment]
Thanks @zxd1997066. I have reproduced the same results with the environment you provided.

The guilty commit https://github.com/pytorch/pytorch/commit/39130c74339ede608a375b94041771468d2fdcdd replaced `remove_extra_clones` with `remove_noop_ops` in `post_grad.py`, resulting in many additional `clones`.

Before:
`aten::copy_        11.83%       21.387s        11.83%       21.393s       3.146ms          6800
`
After:
`aten::copy_        20.20%       41.421s        20.20%       41.426s       1.164ms         35600
`

I tried to revert this change and the speedup came back to 0.964x.

**Comment by Valentine233** [comment]
With `remove_noop_ops`, the additional `reinterpret_tensors` create clones. Actually, `remove_extra_clones` does clones in CPP kernels. `remove_noop_ops` uses the same pointer for input and output, while `remove_extra_clones` uses two different pointers.  **The main reason for regression is that the CPP vector tiling is not applicable after the change.** The accuracy are both fine with `remove_extra_clones` or `remove_noop_ops`.

Here is an example:

`remove_noop_ops`
```
cpp_fused_add_4 = async_compile.cpp('''
#include <ATen/record_function.h>
#include "/tmp/torchinductor_root/ib/cibrnuq56cxamjj4krp4zpjvsirbmlolpbnmomodzyd46huzhdw7.h"
extern "C" void kernel(float* in_out_ptr0,
                       const float* in_ptr0)
{
    RECORD_FUNCTION("graph_0_cpp_fused_add_4", c10::ArrayRef<c10::IValue>({}));
    {
        #pragma GCC ivdep
        for(long i0=static_cast<long>(0L); i0<static_cast<long>(331776L); i0+=static_cast<long>(1L))
        {
            for(long i1=static_cast<long>(0L); i1<static_cast<long>(16L); i1+=static_cast<long>(16L))
            {
                auto tmp0 = at::vec::Vectorized<float>::loadu(in_out_ptr0 + static_cast<long>(i1 + (16L*i0)));
                auto tmp1 = at::vec::Vectorized<float>::loadu(in_ptr0 + static_cast<long>(i1));
                auto tmp2 = tmp0 + tmp1;
                tmp2.store(in_out_ptr0 + static_cast<long>(i1 + (16L*i0)));
            }
        }
    }
}
''')

del buf14
buf16 = reinterpret_tensor(buf15, (1, 576, 576, 16), (5308416, 9216, 16, 1)); del buf15 # reuse
cpp_fused_add_4(c_void_p(buf16.data_ptr()), c_void_p(_frozen_param87.data_ptr()))
```

`remove_extra_clones`
```
cpp_fused_clone_4 = async_compile.cpp('''
#include <ATen/record_function.h>
#include "/tmp/torchinductor_root/ib/cibrnuq56cxamjj4krp4zpjvsirbmlolpbnmomodzyd46huzhdw7.h"
extern "C" void kernel(const float* in_ptr0,
                       const float* in_ptr1,
                       float* out_ptr0)
{
    RECORD_FUNCTION("graph_0_cpp_fused_clone_4", c10::ArrayRef<c10::IValue>({}));
    {
        #pragma GCC ivdep
        for(long i0=static_cast<long>(0L); i0<static_cast<long>(16L); i0+=static_cast<long>(16L))
        {
            #pragma GCC ivdep
            for(long i1=static_cast<long>(0L); i1<static_cast<long>(331776L); i1+=static_cast<long>(16L))
            {
                float tmp0[16*16] __attribute__ ((aligned (16)));
                at::vec::transpose_mxn<float,16,16>(in_ptr0 + static_cast<long>(i0 + (16L*i1)), static_cast<long>(16L), tmp0, 16);
                for (long i0_inner = 0; i0_inner < 16; i0_inner++)
                {
                    auto tmp1 = at::vec::Vectorized<float>::loadu(tmp0 + static_cast<long>(16L*i0_inner));
                    auto tmp2 = at::vec::Vectorized<float>(static_cast<float>(in_ptr1[static_cast<long>(i0 + i0_inner)]));
                    auto tmp3 = tmp1 + tmp2;
                    tmp3.store(out_ptr0 + static_cast<long>(i1 + (331776L*i0) + (331776L*i0_inner)));
                }
            }
        }
    }
}
''')

buf16 = buf14; del buf14  # reuse
cpp_fused_clone_4(c_void_p(buf15.data_ptr()), c_void_p(_frozen_param87.data_ptr()), c_void_p(buf16.data_ptr()))
```

**Comment by masnesral** [comment]
This is assigned so adding the triaged label to remove it from our list of un-triaged

**Comment by leslie-fang-intel** [comment]
Also cc @Chillee, since the suspected commit which causes the regression points to https://github.com/pytorch/pytorch/commit/39130c74339ede608a375b94041771468d2fdcdd

**Comment by Valentine233** [comment]
【Update 2.20】

> Figure out why the removing of clone in FX graph would cause layout change.

### Buffer

Remove_extra_clones (Before regression)
```
buf16 ComputedBuffer(name=None, layout=FlexibleLayout('cpu', torch.float32, size=[1, 16, 576, 576], stride=[5308416, 331776, 576, 1]), data=Pointwise(
  'cpu',
  torch.float32,
  def inner_fn(index):
      _, i1, i2, i3 = index
      tmp0 = ops.load(buf15, i1 + 16 * i3 + 9216 * i2)
      tmp1 = ops.load(_frozen_param87, i1)
      tmp2 = tmp0 + tmp1
      return tmp2
  ,
  ranges=[1, 16, 576, 576],
  origin_node=expand_2,
  origins={clone_3}
))
```

Remove_noop_ops (After regression)
```
buf16 ComputedBuffer(name=None, layout=FlexibleLayout('cpu', torch.float32, size=[1, 576, 576, 16], stride=[5308416, 9216, 16, 1]), data=Pointwise(
  'cpu',
  torch.float32,
  def inner_fn(index):
      _, i1, i2, i3 = index
      tmp0 = ops.load(buf15, i3 + 16 * i2 + 9216 * i1)
      tmp1 = ops.load(_frozen_param87, i3)
      tmp2 = tmp0 + tmp1
      return tmp2
  ,
  ranges=[1, 576, 576, 16],
  origin_node=add_4,
  origins={add_4}
))
```

We could see that the removing of `clone_3` changes the origins of `buf16` and also its layout. When there is no `clone3`, `view_11` (the first input of `bmm1`) inherits the layout of `add_4` because `permute/expand/reshape` are all view changes. However, `clone3` does not make a view change. So `view_11` inherits the layout of `permute_9`, the input of `clone3`.


### TODO

As the root cause is found, we need to fix this problem for the next step. We should let the `bmm` input buffer know the ideal layout and change the layout to it before go into `bmm`.
