### ISSUE TITLE
[inductor][cpu]some models fp32 static shape default wrapper single thread performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#117740]
### 🐛 Describe the bug

Performance regression in 2023-09-03:
<table border="1" role="table">
  <thead>
    <tr>
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>basic_gnn_gcn</td>
      <td>1</td>
      <td>1.453264</td>
      <td>0.07012852100000001</td>
      <td>0.10191525494254401</td>
      <td>16.308482</td>
      <td>1</td>
      <td>4.18351</td>
      <td>0.024277587</td>
      <td>0.10156552799037</td>
      <td>12.917972</td>
      <td>0.35</td>
      <td>1.0</td>
      <td>0.35</td>
      <td>0.79</td>
    </tr>
    <tr>
      <td>basic_gnn_gin</td>
      <td>1</td>
      <td>1.102929</td>
      <td>0.053309631</td>
      <td>0.058796738009199004</td>
      <td>16.217177</td>
      <td>1</td>
      <td>3.911906</td>
      <td>0.016065617</td>
      <td>0.06284718353600201</td>
      <td>12.840029</td>
      <td>0.28</td>
      <td>1.07</td>
      <td>0.3</td>
      <td>0.79</td>
    </tr>
    <tr>
      <td>basic_gnn_sage</td>
      <td>1</td>
      <td>1.069263</td>
      <td>0.055456228</td>
      <td>0.059297292719964007</td>
      <td>14.707836</td>
      <td>1</td>
      <td>3.680068</td>
      <td>0.016367606</td>
      <td>0.060233903077207995</td>
      <td>11.36611</td>
      <td>0.29</td>
      <td>1.02</td>
      <td>0.3</td>
      <td>0.77</td>
    </tr>
  </tbody>

</table><p dir="auto">SW info</p><table border="1" role="table">
  <thead>
    <tr>
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td><a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/pytorch/pytorch/commit/ea7e22973572b5fcf43ea05897c2cf56ace392da/hovercard" href="https://github.com/pytorch/pytorch/commit/ea7e22973572b5fcf43ea05897c2cf56ace392da"><tt>ea7e229</tt></a></td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>770d5cf7</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>dc83b38</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>c11d758</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>58366ab</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td><a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/pytorch/pytorch/commit/1d231d1be03e66c1e3c929dd1d743f0358951d7d/hovercard" href="https://github.com/pytorch/pytorch/commit/1d231d1be03e66c1e3c929dd1d743f0358951d7d"><tt>1d231d1</tt></a></td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td><a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/pytorch/pytorch/commit/f228c8b8cac3db634516c7101dee077cbaa026ab/hovercard" href="https://github.com/pytorch/pytorch/commit/f228c8b8cac3db634516c7101dee077cbaa026ab"><tt>f228c8b</tt></a></td>
      <td>/</td>
    </tr>
  </tbody>
</table>

Repro:
bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) single inference performance torchbench model float32 first static default 0
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/cbf7c918837cce5b46a972a27c74b5dd1a4acc3e
[torchbench-basic_gnn_sage-inference-float32-static-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13975023/torchbench-basic_gnn_sage-inference-float32-static-default-performance-single-drop_guilty_commit.log)
cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @WeizhuoZhang-intel @chuanqi129

**Comment by leslie-fang-intel** [comment]
As @XiaobingSuper described in the PR: https://github.com/pytorch/pytorch/pull/108220. Avoid using `atomic_add` will fix the performance regression of multi thread cases for these 3 models: `basic_gnn_gcn`, `basic_gnn_gin` and `basic_gnn_sage`.

**Comment by leslie-fang-intel** [comment]
Need to check threads number and dynamic thread number config.

**Comment by leslie-fang-intel** [comment]
Close this issue as https://github.com/pytorch/pytorch/pull/118278 merged.
