### ISSUE TITLE
[inductor][cpu]mixnet_l amp multiple threads static shape default wrapper performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#117727]
### 🐛 Describe the bug

<p>mixnet_l amp multiple threads static shape default wrapper performance regression</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>mixnet_l</td>
      <td>128</td>
      <td>1.371298</td>
      <td>0.16417044</td>
      <td>0.22512659603111998</td>
      <td>60.864277</td>
      <td>128.0</td>
      <td>1.55607</td>
      <td>0.14557603</td>
      <td>0.2265264930021</td>
      <td>58.178619</td>
      <td>0.88</td>
      <td>1.01</td>
      <td>0.89</td>
      <td>0.96</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>24569d3</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ff42d907</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>b2d9c3e</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>a00a72b</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.3.0a0+git2f05263</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.18.0a0+f52fd33</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+258169e</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>2f05263</td>
    </tr>
  </tbody>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference performance timm_modles mixnet_l amp first static default
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/6c624aad377723bde32026c8ddd58a3091c9efc4
[timm_models-mixnet_l-inference-amp-static-default-performance-multiple-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13971938/timm_models-mixnet_l-inference-amp-static-default-performance-multiple-drop_guilty_commit.log)
cc @WeizhuoZhang-intel @chuanqi129

**Comment by chuanqi129** [comment]
Hi @Valentine233 please help to double check this regression model

**Comment by Valentine233** [comment]
I've checked the validation results of https://github.com/pytorch/pytorch/pull/116318.

Mixnet_l did not have a regression:
<img width="1240" alt="image" src="https://github.com/pytorch/pytorch/assets/23010269/5379a28d-d008-41c5-bf30-8994c352819b">

In addition, is there any other model regressions caused by this commit?

**Comment by zxd1997066** [comment]
let me use baremetal instance to have a double check.
no other regression caused by this commit.

**Comment by zxd1997066** [comment]
With baremetal instance, the suspected guilty commit is https://github.com/pytorch/pytorch/commit/9f57cf502fba060285f0a6cab7516066fee40d8f, the same as https://github.com/pytorch/pytorch/issues/117644, close this issue.
