### ISSUE TITLE
llama_v2_7b_16h stopped working with torch.jit.trace

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#117752]
### 🐛 Describe the bug

We've noticed this behavior on torchbench using torchscript as backend on PyTorch main branch.
As we didn't identify the offending PR, my concern is if that regression was merged into PyTorch 2.2 or not.

I am still working on a local repro, but it should be something similar to

```python
import torch
import transformers
from transformers import LlamaConfig

kwargs = {}
device = "cpu"
max_length = 512
batch_size = 1
config = LlamaConfig(num_hidden_layers=16)
model = transformers.AutoModelForCausalLM.from_config(config, **kwargs).to(device)

eval_context = torch.randint(0, config.vocab_size, (batch_size, max_length)).to(device)
example_inputs = {'input_ids': eval_context, }
model.eval()

module = torch.jit.trace(model, example_kwarg_inputs=example_inputs)
```

The error is 

```bash
Attention using SDPA can not be traced with torch.jit.trace when no attention_mask is provided. To solve this issue, please either load your model with the argument attn_implementation="eager" or pass an attention_mask input when tracing the model.
```

Unfortunately I didn't repro locally and that is all that is informed by torchbench report. The last time we are sure the model was exporting with torch.jit.trace was around 12/16, when we locally executed torchbench

https://github.com/pytorch/benchmark/pull/2121 is a proposal (not tested) for working this around, but we still need to understand 

### Versions

pytorch main

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by malfet** [comment]
I assume it's one of the transformers changes, which no longer correctly decompose...

**Comment by malfet** [comment]
We should probably should just propose a ternary to transformer to use older path...

**Comment by thiagocrepaldi** [comment]
> We should probably should just propose a ternary to transformer to use older path...

Have you discussed that with HF folks? Is there an issue we can track?

I was wondering whether https://github.com/pytorch/benchmark/pull/2121 could be a fix on our end

**Comment by kunal-vaishnavi** [comment]
Issues related to SDPA have been raised three times in ONNX Runtime already.

1. https://github.com/microsoft/onnxruntime/pull/19015#discussion_r1442432173
2. https://github.com/microsoft/onnxruntime/issues/19051
3. https://github.com/microsoft/onnxruntime/issues/19040

It was [fixed here](https://github.com/microsoft/onnxruntime/pull/19200) for LLaMA, but similar issues will likely be raised for other models. It would be helpful if the eager attention implementation is traced by default during the export of Hugging Face models.

**Comment by thiagocrepaldi** [comment]
> > We should probably should just propose a ternary to transformer to use older path...
> 
> Have you discussed that with HF folks? Is there an issue we can track?
> 
> I was wondering whether [pytorch/benchmark#2121](https://github.com/pytorch/benchmark/pull/2121) could be a fix on our end

@malfet @kit1980 gentle ping

**Comment by BowenBao** [comment]
related discussion https://github.com/huggingface/transformers/issues/28610

**Comment by thiagocrepaldi** [comment]
> We should probably should just propose a ternary to transformer to use older path...

Bowen proposed this change: https://github.com/huggingface/transformers/pull/28823

**Comment by BowenBao** [comment]
A more proper fix will be done in part of https://github.com/huggingface/transformers/pull/27931

**Comment by thiagocrepaldi** [comment]
https://github.com/huggingface/transformers/pull/27931 has been merged this morning. We can close this one now
