### ISSUE TITLE
Foreach Infinity Norm Support

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#117803]
### 🚀 The feature, motivation and pitch

Currently we don't have an eager op for foreach infinity norm. 
We have L1 and L2 implemented here: https://github.com/pytorch/pytorch-canary/commit/237bed148a585ff75b1a8d4801d64f49714d6089#diff-d11ea193df3e88b33bbb36334bb325f36630ad7c2486057068c58f633a79d1c1

It may be possible to implement this without an eager version since L1 and L2 are already supported and we can just implement a decomp that decomposes this op into foreach_maximum(foreach_abs(x, y)). This depends on how okay we are with compiled supporting some ops that aren't available in eager.

The driving use case is in the shampoo optimizer we see many infinity norm kernels: 
[internal profile](https://www.internalfb.com/intern/perfdoctor/trace_view?filepath=tree%2Ftraces%2Fdynocli%2Ff514531715-TrainingApplication%2F0%2Frank-0.Dec_20_19_04_46.4143.pt.trace.json.gz&bucket=pyper_traces)

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @mcarilli @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler who I discussed this briefly with

**Comment by janeyx99** [comment]
Yea, we should do this for eager too

**Comment by mlazos** [comment]
@janeyx99 will you take this on? when do you think you can start on it if so

**Comment by janeyx99** [comment]
This is currently not on my roadmap in the next month, though I may get to it after that. I'm happy to review a PR for it though.
