### ISSUE TITLE
Communication Computation Overlap issue with TransformerEngine + FSDP

### ISSUE THREAD

**Issue by denizokt** [pytorch/pytorch#117897]
### 🐛 Describe the bug

I am training a large multi-node transformer model with Pytorch FSDP, and am running into some issues while using TransformerEngine. I'm not sure if this is a Pytorch issue or a TransformerEngine issue, but any advice would be very appreciated. I will also cross-post on TransformerEngine!

While using FSDP and TransformerEngine, I noticed that the communication/computation overlap is very poor. Looking at the traces, it seems that the TransformerEngine LayerNorm is actually waiting for the FSDP allGather in the forward pass:
<img width="916" alt="Screenshot 2024-01-19 at 6 52 11 PM" src="https://github.com/pytorch/pytorch/assets/1954448/ffc5bc5c-0661-460f-96e0-b30d40380bea">

If I use custom torch linear and layernorm layers, the overlap is much better:
<img width="518" alt="Screenshot 2024-01-19 at 6 53 26 PM" src="https://github.com/pytorch/pytorch/assets/1954448/28df6b02-8278-4803-ad28-59f448a26329">

In terms of iteration time too, the torch linear + layernorm significantly outperforms the TransformerEngine layer. When the computation per FSDP group increases (say, if I bundle multiple layers into a single FSDP unit) this problem gets a lot worse.

Thank you very much for your time!

### Versions

Collecting environment information...
PyTorch version: 2.1.2
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.28.1
Libc version: glibc-2.31

Python version: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 12.3.107
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

**Comment by denizokt** [comment]
Some more information on this:

The flow events suggest that the FSDP allGather is just waiting due to rate limiting, which is fine and I assume is intended behavior. The weirdness comes from the fact that the LayerNorm from two layers ago is waiting for the allGather for the current layer to finish.
<img width="478" alt="Screenshot 2024-01-19 at 7 23 32 PM" src="https://github.com/pytorch/pytorch/assets/1954448/6b2dcf34-c6a0-458d-a0ed-a65d72ab28ad">

Would @awgu have insight into this? (So sorry to tag on a Friday night. No rush to answer.) Although maybe it really is more of a TransformerEngine issue.

**Comment by denizokt** [comment]
Yes it is actually

**Comment by awgu** [comment]
I think that that might be the issue. Cooperative kernels require full GPU SM occupancy, so for a NCCL all-gather that requires something like 2 SMs, the cooperative kernel will wait for the all-gather to finish in order to get the full occupancy.

This might be something to ask the TransformerEngine team about or at least loop them in.

**Comment by denizokt** [comment]
Ahh thank you so much. Okay I will follow up on the TransformerEngine post.
