### ISSUE TITLE
Flaky tests bot should not mark issue as "triaged"

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#117846]
Flaky test bot seems to be marking issues with "oncall: pt2" and "triaged", which bypasses the pt2 triage oncall. Can we get it to not mark issues as "triaged" so that our oncall can take a look?

Example: https://github.com/pytorch/pytorch/issues/109268

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Hmm, this is an easy fix, but why not? It should only leave out triaged if test module owner is unknown, isn't it? Or you are thinking about high-pri issues?

**Comment by zou3519** [comment]
The PT2 oncall's role is to triage the issue. Marking the issue as "triaged" removes it from the triage queue for the PT2 oncall.
1) The issues aren't labeled correctly. The PT2 oncall's responsibility is to apply sub-labels to the issue so that it goes to the correct owners. 
2) Priority. We generally mark all silent correctness issues as hi-pri. Many of these flaky tests show silent correctness issues, but the flaky-test bot doesn't know that.

**Comment by malfet** [comment]
Should be fixed by https://github.com/pytorch/test-infra/pull/4898
