### ISSUE TITLE
CI test repro command should be relative to either the root or test folder

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#117850]
![image](https://github.com/pytorch/pytorch/assets/5652049/68a0b044-99d3-487a-a351-7b79affd4648)

This saves the trouble of someone needing to find out where the test is.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @mruberry @ZainRizvi

**Comment by cpuhrsch** [comment]
@zou3519 - I'll let you add the appropriate labels (if there are any missing). I added "test" and "testing".

**Comment by zou3519** [comment]
I've noticed the path thing actually working, so my guess is that the test path is based off of what folder you're currently cd'ed into, and the test runner just cd's all the way in before running the test.

**Comment by huydhn** [comment]
`test/run_test.py` should be the one responsible for cd-ing into the correct directory I think.
