### ISSUE TITLE
Make **inplace_buffer_mutations** configurable in `torch.export.unflatten`

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#117893]
The backends (at least ONNX) relies on Functionalization to remove all in-place ops. However, in 

https://github.com/pytorch/pytorch/blob/3c1498d117e70efd57c02947f711985231f0845f/torch/export/unflatten.py#L274-L295

The UnflattenedModule reverses the change. It would be super helpful if `_inplace_buffer_mutations` is configurable.

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by suo** [comment]
Would be happy to review a PR that adds a defaulted flag here!

**Comment by titaiwangms** [comment]
Hi @suo,

ONNX wanted to leverage on `torch.export.unflatten` to keep module hierachy for our users. But it seems UnflattenedModule only to guarantee on eager mode (I guess that's why it is not inheriting from torch.fx.GraphModule.), and I am not what ONNX been requested deviates the original idea of this API. Maybe there is another tool that is more suitable to our demands?
