### ISSUE TITLE
Dynamo tests in CI flaky with "NameError: name '___module_torch_140438948430768' is not defined"

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#117851]
Some sample logs:
https://github.com/pytorch/pytorch/issues/117788
```
==================================== RERUNS ====================================
__________________________ TestStats.test_mean_values __________________________
Traceback (most recent call last):
  File "torch_np/numpy_tests/core/test_multiarray.py", line 4655, in test_mean_values
    res = _mean(mat, axis=axis) * mat.shape[axis]
  File "torch_np/numpy_tests/core/test_multiarray.py", line 4496, in _mean
    def _mean(a, **args):
NameError: name '___module_torch_140438948430768' is not defined

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test_multiarray.py -k test_mean_values

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```
https://github.com/pytorch/pytorch/issues/117715
```
_____________________________ TestTile.test_basic ______________________________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/torch_np/numpy_tests/lib/test_shape_base_.py", line 807, in test_basic
    def test_basic(self):
  File "/var/lib/jenkins/workspace/test/torch_np/numpy_tests/lib/test_shape_base_.py", line 810, in resume_in_test_basic_at_810
    assert_equal(tile(a, 2), [0, 1, 2, 0, 1, 2])
NameError: name '___module_torch_140001844595824' is not defined

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/torch_np/numpy_tests/lib/test_shape_base_.py -k test_basic

```

I'm not able to repro this locally. The name sounds like a guard?

cc @mruberry @ZainRizvi @ezyang @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by zou3519** [comment]
I wonder if the object is getting gc'ed in the middle of Dynamo lol

**Comment by zou3519** [comment]
Observations:
- Dynamo creates a new global, `__module_torch_12345678`
- The lifetime of this global is tied to the lifetime of the frame that needed to use it
- When Dynamo compiles another frame, and `__module_torch_12345678` exists already, then it reuses it.
- However, `__module_torch_12345678`'s creating frame can be deleted while the other frames still need `__module_torch_12345678`, leading to the name not found error.

Questions:
- Why is Dynamo creating a new global instead of reusing `torch`?
- How do the frames actually use `__module_torch_12345678`? Is it a part of the code Dynamo generates for each frame?

**Comment by ezyang** [comment]
Is this the CleanupHook thing? But we're supposed to assert that the global does not already exist:

```
@dataclasses.dataclass
class CleanupHook:
    """Remove a global variable when hook is called"""

    scope: Dict[str, Any]
    name: str

    def __call__(self, *args):
        CleanupManager.count -= 1
        del self.scope[self.name]

    @staticmethod
    def create(scope, name, val):
        assert name not in scope
        CleanupManager.count += 1
        scope[name] = val
        return CleanupHook(scope, name)
```

**Comment by ezyang** [comment]
Oh oops

```
    def create_load_python_module(self, mod, push_null) -> Instruction:
        """
        Generate a LOAD_GLOBAL instruction to fetch a given python module.
        """
        global_scope = self.tx.output.global_scope
        name = re.sub(r"^.*[.]", "", mod.__name__)
        if global_scope.get(name, None) is mod:
            return self.create_load_global(name, push_null, add=True)
        mangled_name = f"___module_{name}_{id(mod)}"
        if mangled_name not in global_scope:
            self.tx.output.install_global(mangled_name, mod)
        return self.create_load_global(mangled_name, push_null, add=True)
```

**Comment by ezyang** [comment]
It seems to me like we should just create distinct globals for each compiled frame (removing the "if mangled_name not in global_scope". Need some way of having a per-compile unique identifier, idk if we've already got one. Shouldn't be too hard to fix.

**Comment by zou3519** [comment]
Per-frame-globals seems like a better option if ultimately we want deleting a compiled function to free memory (it doesn't today -- the user needs to call torch.dynamo.reset() to free)
