### ISSUE TITLE
Support full graph compilation of single tensor (foreach=False) Adamax

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#117836]
### 🚀 The feature, motivation and pitch

Currently https://github.com/pytorch/pytorch/pull/117835 adds support for tracing and fully fusing foreach Adamax. For completeness we should also do a similar refactor of the single tensor optimizer to enable tracing and compilation.

Check https://github.com/pytorch/pytorch/blob/mlazos/compiled-adamax/test/inductor/test_compiled_optimizers.py for the other test implementations. https://github.com/pytorch/pytorch/blob/1bc2f2466b0f0340d60748b83a6bbdd8b3723473/test/inductor/test_compiled_optimizers.py#L67 needs to be set the correct value and the tests should pass after the refactor is completed.

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jennyluciav** [comment]
Can I work on this?

**Comment by mlazos** [comment]
> Can I work on this please?

Yes, let me know if you need help.

**Comment by janeyx99** [comment]
@jennyluciav I'm also happy to help! This change is p important so we'd like a change for this sooner rather than later. Do you have a timeline for when you'd get a PR out for this?
