### ISSUE TITLE
Tensor flattening on broadcast doesn't handle heterogeneous types

### ISSUE THREAD

**Issue by kartynnik** [pytorch/pytorch#1179]
In e.g. a `DataParallel` scenario, when not all the parameters/buffers are of the same type, the following code:
https://github.com/pytorch/pytorch/commit/65b66264d49d153060b820e1f33919038b7978b6#commitcomment-21617027
leads to the type coalescence which is not always desired (e.g. if the first tensor is a `LongTensor` and the rest are `FloatTensor`s, we get back a bunch of rounded `LongTensor`s instead).

**Comment by soumith** [comment]
fixed in master. will be in next release.
