### ISSUE TITLE
Sparse Scipy matrices are not accepted in autograd.Function parameters, but dense ones are.

### ISSUE THREAD

**Issue by matthieuheitz** [pytorch/pytorch#11797]
## Issue description

It seems that sparse scipy matrices create errors when transmitted as parameters of a custom autograd.Function, whereas dense scipy (numpy) matrices don't.
I don't know if this is on purpose or not...
If it should be supported, then I think it is a bug.
If you won't support it, then it would be nice to have a clearer and consistent (across sparse formats) message to explain that scipy sparse matrices are not supported.
For CSR and LIL formats, the infinite recursion happens in the function https://github.com/pytorch/pytorch/blob/91b6458e2d0dba935da2cc7c2cdc6d7907bc3f48/torch/autograd/gradcheck.py#L36

## Code example

```
import torch
import scipy.sparse.linalg
from torch.autograd import gradcheck

class MyCustomFunction(torch.autograd.Function):

    @staticmethod
    def forward(ctx, A, b):
        ctx.intermediate = (A,b)
        return torch.tensor(A.dot(b.detach().numpy()))

    @staticmethod
    def backward(ctx, grad_output):
        # Not implemented
        return None, grad_output

N = 250
A = 2*scipy.eye(N)                  # gradcheck works, but it returns false because the backward is not implemented.
# A = 2*scipy.sparse.eye(N).todia()   # gradcheck gives error "'dia_matrix' object is not subscriptable"
# A = 2*scipy.sparse.eye(N).tocoo()   # gradcheck gives error "'coo_matrix' object is not subscriptable"
# A = 2*scipy.sparse.eye(N).tocsr()   # gradcheck gives error "RecursionError: maximum recursion depth exceeded while calling a Python object".
# A = 2*scipy.sparse.eye(N).tolil()   # gradcheck gives error "RecursionError: maximum recursion depth exceeded in comparison".
x = torch.ones(N, dtype=torch.float64, requires_grad=True)
input = (A,x)
test = gradcheck(MyCustomFunction.apply, input, eps=1e-6, atol=1e-4)
print(test)
```

## System Info

PyTorch version: 0.5.0a0+bdbbcf0                                                
Is debug build: No                                                              
CUDA used to build PyTorch: 8.0.44                                              
                                                                                
OS: Ubuntu 16.04.5 LTS                                                          
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609                    
CMake version: version 3.11.1                                                   
                                                                                
Python version: 3.6                                                             
Is CUDA available: Yes                                                          
CUDA runtime version: 7.5.17                                                    
GPU models and configuration: GPU 0: Quadro M2000                               
Nvidia driver version: 384.130                                                  
cuDNN version: Probably one of the following:                                   
/usr/local/MATLAB/R2016b/bin/glnxa64/libcudnn.so.4.0.7                          
/usr/local/MATLAB/R2017a/bin/glnxa64/libcudnn.so.5.1.5                          
                                                                                
Versions of relevant libraries:                                                 
[pip3] numpy (1.14.5)                                                           
[pip3] numpydoc (0.7.0)                                                         
[pip3] torch (0.5.0a0+bdbbcf0)                                                  
[conda] magma-cuda80              2.3.0                         1    pytorch    
[conda] torch                     0.5.0a0+bdbbcf0           <pip>               

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @mruberry @rgommers @heitorschueroff @aocsa

**Comment by matthieuheitz** [comment]
After having modified the code to ignore sparse matrices, like below, it still works for dense matrices and not for sparse ones, but at least the error message is consistent for all formats of sparse matrices : I get the error "RuntimeError: all inputs have to be Tensors, but got csr_matrix", and the last part of the message changes according to the format. Of course my edit is not acceptable, but maybe you could add a condition in those 2 functions, that if the object is neither a Tensor, neither an Iterable, then you treat it just like if it was a non-gradient-requiring tensor ?

It would be great to be able to pass any non-Pytorch object in those arguments, as long as we don't require or return a gradient for it.

```
def make_jacobian(input, num_out):
    if scipy.sparse.isspmatrix(input):  # Added
        return None                                # Added
    elif isinstance(input, torch.Tensor): # Replaced if by elif
        if not input.is_floating_point():
            return None
        if not input.requires_grad:
            return None
        return torch.zeros(input.nelement(), num_out, dtype=input.dtype)
    elif isinstance(input, Iterable):
        jacobians = list(filter(
            lambda x: x is not None, (make_jacobian(elem, num_out) for elem in input)))
        if not jacobians:
            return None
        return type(input)(jacobians)
    else:
        return None

import scipy.sparse   # Added

def iter_tensors(x, only_requiring_grad=False):
    if scipy.sparse.isspmatrix(x):  # Added
        yield x                                 # Added
    elif isinstance(x, torch.Tensor):   # Replaced if by elif
        if x.requires_grad or not only_requiring_grad:
            yield x
    elif isinstance(x, Iterable):
        for elem in x:
            for result in iter_tensors(elem, only_requiring_grad):
                yield result
```

**Comment by zou3519** [comment]
afaik we don't support non-pytorch objects as arguments to autograd Functions. The fact that we support numpy arrays is because those are upcasted to tensors.

For this, we should probably guard against non-pytorch objects as inputs to autograd Functions.

cc @apaszke

**Comment by matthieuheitz** [comment]
Okay, thanks !
I guess I should wait for PyTorch 1.0 to come out, and hopefully the sparse tensor support will be complete.

**Comment by albanD** [comment]
I am going to close this as outdated as we moved to a new style of custom Function since this issue was open and we now properly support non Tensor type and don't try to unpack them.

The infinite recurse though comes from the gradcheck code I think and might still happen. But here, the gradcheck expects *only* Tensors are input and so should not be given such objects.
The reason why this recursion happens is because the sparse arrays are sequences and so we traverse them looking for Tensors (like we traverse list/dict), but the problem here is that these arrays, when traversed, always return a sequence, leading to the infinite recursion.
If you still encounter this issue and it is a problem for you, please open a new issue with a code sample and we can find a way to fix this (or at least get a nice error message) in gradcheck.
