### ISSUE TITLE
DTensor does not work with empty tensors

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#118043]
### 🐛 Describe the bug

In https://github.com/pytorch/pytorch/pull/117223 I've added empty test to `torch.mm(torch.empty(4, 0), torch.empty(0, 3))` is the same as calling `torch.zeroes(4, 3)`, which caused DTensor opinfo test to fail with 
```
% python3 -mpytest test_dtensor_ops.py -s -k test_dtensor_op_db_mm
....
Traceback (most recent call last):
  File "/home/nshulga/git/pytorch/pytorch/test/distributed/_tensor/test_dtensor_ops.py", line 650, in run_dtensor_crossref
    dtensor_rs = func(*dtensor_args, **dtensor_kwargs)
  File "/home/nshulga/git/pytorch/pytorch/torch/distributed/_tensor/api.py", line 289, in __torch_dispatch__
    return DTensor._op_dispatcher.dispatch(
  File "/home/nshulga/git/pytorch/pytorch/torch/distributed/_tensor/dispatch.py", line 113, in dispatch
    self.sharding_propagator.propagate(op_info)
  File "/home/nshulga/git/pytorch/pytorch/torch/distributed/_tensor/sharding_prop.py", line 164, in propagate
    output_sharding = self.propagate_op_sharding(op_info.schema)
  File "/home/nshulga/git/pytorch/pytorch/torch/distributed/_tensor/sharding_prop.py", line 216, in propagate_op_sharding_non_cached
    output_strategy = self._select_strategy(op_strategy)
  File "/home/nshulga/git/pytorch/pytorch/torch/distributed/_tensor/sharding_prop.py", line 394, in _select_strategy
    return strategy.strategies[strategy_costs.index(min(strategy_costs))]
ValueError: min() arg is an empty sequence
```

For folks with internal access, see also [T175295456](https://www.internalfb.com/intern/tasks/?t=175295456) 

Not sure if this is something that is important to support for DTensor usecases, but filing issue all the same

Another fun fact, looks like none of those tests are run in OSS CI (though there are no good reason why they shouldn't), but probably the CPU part of it is skipped due to:
https://github.com/pytorch/pytorch/blob/a27a6e8cf123cf9517ccada63e249f73ab981845/test/distributed/_tensor/test_dtensor_ops.py#L707-L710

### Versions

Nightly

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by wanchaol** [comment]
Yeah we were experiencing issues with cuda tests in CI, so the cuda test got disabled in CI. And later because CPU tests are timeout CPU test also got disabled. Let's try to re-enable this in the CI @XilunWu

**Comment by XilunWu** [comment]
@wanchaol It is strange that I added a unit test for empty tensor case in  #117726  and it successfully reproduced the error. But in github CI this test reports that there's no issue.

**Comment by XilunWu** [comment]
#118132 shall close this issue. Thx @malfet for capturing this!!

**Comment by XilunWu** [comment]
> Yeah we were experiencing issues with cuda tests in CI, so the cuda test got disabled in CI. And later because CPU tests are timeout CPU test also got disabled. Let's try to re-enable this in the CI @XilunWu

We can discuss how to re-enable the CPU `test_dtensor_ops`. #118132 re-enabled the [add]mm tests.

**Comment by XilunWu** [comment]
#118134 re-enable `test_dtensor_ops ` in CPU CI

**Comment by malfet** [comment]
Ok, looks like tests are running now, closing
