### ISSUE TITLE
Torch distributed checkpoint loading broken on nightly

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#118081]
### 🐛 Describe the bug

We are unable to load sharded checkpoints moving from 01/10 nightly to 01/20 nightly. We are trying to move up our pin to include the dtensor + broadcast fix and hitting some kind of regression.
As best as I can tell, we call
```
from torch.distributed import checkpoint as dist_cp
dist_cp.load(
  state_dict=state_dict,
  storage_reader=storage_reader,
  planner=load_planner,
)
```
and the state_dict is not actually read / updated. I have confirmed everything works fine on 01/10 nightly

### Versions

Torch nightly 01/20

cc @ezyang @gchanan @zou3519 @kadeng @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by fegin** [comment]
@mvpatel2000 Is this FSDP optimizer state_dict load or the model state_dict? We found a bug in DTensor that can cause optimizer state_dict loading failed.

**Comment by LucasLLC** [comment]
If it's helpful, this should be fixed once the following PR is merged  https://github.com/pytorch/pytorch/pull/117799

**Comment by mvpatel2000** [comment]
> @mvpatel2000 Is this FSDP optimizer state_dict load or the model state_dict? We found a bug in DTensor that can cause optimizer state_dict loading failed.

@fegin I am seeing this for everything in the state_dict. As a concrete example, we store a timestamp object which tracks epcoh/batch/sample/token counts when resuming a checkpoint, see definition [here](https://github.com/mosaicml/composer/blob/4a53dfeb043ed4e26bec7740fb1711e540ebe5a4/composer/core/time.py#L391). 

This loads correctly on torch 1/10 but fails to load correctly on 1/20 and stays with the default values in the state dict object I pass into `load_state_dict`.

**Comment by fegin** [comment]
@mvpatel2000 I could not reproduce this issue as the unittests show the load can still work correctly. From the history, there are only 4 PRs after 1/10. 2 are typing and code cleanup without logic change. The last PR is the CPU offload PR you submitted. The only one left is the Meta tensor initialization. You can comment out https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/default_planner.py#L166 to see if it is the root cause. 

cc., @wz337

**Comment by mvpatel2000** [comment]
This seems to no longer be an issue. I can't seem to figure out what caused this 🤔. I would assume user error on my part, sorry!
