### ISSUE TITLE
Regarding the export of the torch_geometric module as onnx, the inference results of onnx are inconsistent with the original model

### ISSUE THREAD

**Issue by SpadgerBoy** [pytorch/pytorch#118099]
```
import torch
from torch import Tensor
import torch.nn as nn
import torch.nn.functional as F
from torch_sparse import SparseTensor, matmul
from torch_geometric.nn.conv import MessagePassing

class GINConv(MessagePassing):

    def __init__(self, nn:Callable, eps: float=0., train_eps: bool=False,
                 activation="softplus", **kwargs):
        super(GINConv, self).__init__(aggr='add', **kwargs)
        self.nn = nn    # MLP
        self.initial_eps = eps
       ......

    def forward(self, x: Union[Tensor, OptPairTensor], edge_index: Adj,
                edge_attr: OptTensor=None, size: Size=None) -> Tensor:
       
        out = self.propagate(edge_index, x=x, edge_attr=edge_attr, size=size)

       ......  
    
    def message(self, x_j: Tensor, edge_attr: Tensor) -> Tensor:

       .......
    
    def __repr__(self):
        ......

```

As shown in the above code, after exporting the module as onnx, the inference result of the model is inconsistent with the original model. I don't know if it's because some operators in the 'pyg' package don't support exporting as onnx. The specific code line that caused the problem is: out=self. propagate (edgeIndex, x=x, edgeAttr=edgeAttr, size=size)

**Comment by thiagocrepaldi** [comment]
Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

Provide a full repro script for debugging, otherwise it is hard to help
