### ISSUE TITLE
[DCP] Automatically detect whether to use FileSystemWriter/FileSystemReader or FsspecWriter/FsspecReader

### ISSUE THREAD

**Issue by fegin** [pytorch/pytorch#118036]
### 🚀 The feature, motivation and pitch

The new APIs `dcp.save()` and `dcp.load()` should automatically detect whether to use  FileSystemWriter/FileSystemReader or FsspecWriter/FsspecReader. In most cases, this is a better interface as users do not have to create StorageWriter and StorageReader.

- [ ] Finish https://github.com/pytorch/pytorch/issues/118033
- [ ] Write an API to detect whether to use FsspecWriter/FsspecReader.
- [ ] Update the documentation and tutorial of `dcp.save()` and `dcp.load()`.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by LucasLLC** [comment]
Just want to add support for this, I think this is ideal UX
