### ISSUE TITLE
Rename DistBackend -> Backend

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#11803]
The "Dist" in "DistBackend" still is repetitive IMO. Usually this will be used as:

```python
import torch.distributed as dist
dist.DistBackend.GLOO
```

We should rename s/DistBackend/Backend/. Since it is part of the distributed package, it is clear that backend implies the distributed backend. The class was only recently introduced so I'm sure there are no external users yet. Pre-1.0 is the time to make this mod. This is not directly related to this change. 

cc @SsnL @teng-li @apaszke

**Comment by SsnL** [comment]
I can add this to #11715 . Should I do it?

**Comment by pietern** [comment]
Let's do it separately, as that one is all ready to go.
