### ISSUE TITLE
[feature request] Savable data loader/iterator

### ISSUE THREAD

**Issue by w-hc** [pytorch/pytorch#11813]
For large jobs with long epochs, it is necessary to checkpoint during the middle of an epoch, especially in a shared cluster setting with job time limit. It would be nice to be able to start at exactly where the training stopped and continue sampling for data afterwards. 

I can see that directly trying to checkpoint dataloader involves lots of problems that's tied to saving the underlying dataset, etc. It's not a maintainable solution. 

A compromise could be to save and retrieve the information as to which indices have already been sampled, and use those as part of the dataloder constructor, so that when the new iterator starts it avoids sampling the consumed data points. 

I have searched through the forums for a few Q&As and it seems there is no clean solution.

**Comment by w-hc** [comment]
Well I decided to go with a sample workaround using a stateful sampler that can be saved itself.
```Python
import numpy as np
import torch.utils.data.sampler as TorchSampler

# the initial permutation is preserved across restarts


class StatefulSampler(TorchSampler.Sampler):
    # vanilla list is orders of magnitude faster for indexing
    # while np.array/torch.Tensor is 3x more storage efficient
    def __init__(self, data_source, use_random=True):
        self.use_random = use_random
        self.dset = data_source
        self._init_indices()

    def _init_indices(self):
        indices = None
        if self.use_random:
            indices = np.random.permutation(len(self.dset))
        else:
            indices = range(len(self.dset))
        self.indices = list(indices)
        self.iter_counter = 0

    def __len__(self):
        return len(self.dset)

    def __iter__(self):
        return self

    def __next__(self):
        if self.iter_counter == len(self.indices):
            self._init_indices()
            raise StopIteration()
        else:
            elem = self.indices[self.iter_counter]
            self.iter_counter += 1
            return elem

    def load_state_dict(self, state_dict):
        self.indices = list(state_dict['indices'])
        self.iter_counter = state_dict['iter_counter']

    def state_dict(self):
        return {
            'indices': np.array(self.indices),
            'iter_counter': self.iter_counter
        }

```

**Comment by vadimkantorov** [comment]
I've also encountered a need for `state_dict` protocol for Samplers. I think it's a valid feature request for core PyTorch.

**Comment by arbellea** [comment]
@w-hc 
Your solution looks very useful! Could you post a short code snippet of how to use it?
Thanks

**Comment by w-hc** [comment]
@arbellea 
There is no clean solution at the moment, esp given the added complexity of DDP training. 
I have not been using it myself either.

**Comment by matthijsvk** [comment]
I'd be very interested in this. I think it would help a lot with proper reproducibility.
It's also very useful for things like [Lottery Ticket Hypothesis ](https://arxiv.org/pdf/1803.03635.pdf)
