### ISSUE TITLE
Docker upload silently fails and forces never ending CI rebuilds

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#118164]
### 🐛 Describe the bug

See https://github.com/pytorch/pytorch/actions/runs/7631831857/job/20790685545#step:5:18095
```
+ '[!' docker manifest inspect 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-cuda12.1-cudnn8-py3-gcc9:827079c96b1c6bf0402fafcf70ae746d84c8784a
```

But job is green, but image is not uploaded, which causes docker rebuild for all subsequent CI jobs as well as CI failures on ROCm and tutorials

For example https://github.com/pytorch/pytorch/actions/runs/7632515306/job/20795482150 has spent an hour building docker image on A100 machine rather than running a test
### Versions

CI

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
It's my mistake with a redundant extra square brackets, the fix is ready at https://github.com/pytorch/test-infra/pull/4904

**Comment by malfet** [comment]
Let's see if this will help preventing those in the future: https://github.com/pytorch/test-infra/pull/4906
