### ISSUE TITLE
Better build error with cudnn version mismatch

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#118193]
I had cudnn 8.0.5. building pytorch led to the following error: https://gist.github.com/zou3519/c4f2fe8a2db900883cbafb866eb34fce . The cudnn version was too old; I am told we support a minimum of 8.5 now. We should raise a more understandable error message.

It seems relatively frequent that cudnn_frontend causes us to drop support for an older version of cudnn

cc @malfet @seemethere @csarofeen @ptrblck @xwang233

**Comment by drisspg** [comment]
At least for my the best option I found was maybe doing some shenanigans here: https://github.com/pytorch/pytorch/blob/main/cmake/Modules_CUDA_fix/FindCUDNN.cmake

``` Shell
readlink -f /usr/lib64/libcudnn.so
/usr/lib64/libcudnn.so.8.9.6
```
and then using a regex to get the version to grab the version and check that its greater than 8.5, that being said this is brittle and sucks so there has gotta be a better way/ more standard way*

**Comment by malfet** [comment]
@drisspg if I'm not mistaken, we already extract the version from the cudnn header (or are we doing it for cublas)

**Comment by drisspg** [comment]
Ohh you are totally right, for some reason I thought this was grabbing the cudnn_frontend version

**Comment by malfet** [comment]
Wrote a short PR that checks that CuDNN version is newer than 8.5
