### ISSUE TITLE
[HOO][torch.compile] Contexts and passing forward node meta to backward node

### ISSUE THREAD

**Issue by kbadz-pl** [pytorch/pytorch#118181]
### 🚀 The feature, motivation and pitch

Hello,
I have implemented some feature that allows to wrap "contexts" of operations using Higher Order Ops. It basically implements wrap-example-like HOO and variable with some minor differences, namely one causing all ops generated within an HOO to have access to a stack of HOO's that wrapped it, effectively allowing to feed nodes with additional metadata specified by the user and passing this data through functionalization of FWD graph within aot_autograd.

For example, you can consider this pseudocode:

```
def some_subcode_part1(in1, in2, hint):
    tmp1 = in1 * in2 #node A
    tmp2 = in1 / in2 #node B

    return tmp1, tmp2

def some_subcode_part2(tmp1, tmp2, hint):
    out1 = tmp1 + tmp2 #node C
    out2 = tmp1 - tmp2 #node D

    return out1, out2

def some_code(in1, in2, hint):
    tmp1, tmp2 = torch.ops.higher_order.hinted_context(some_subcode_part1, in1, torch.max(in2), hint='{"mode": "1"}')
    out1, out2 = torch.ops.higher_order.hinted_context(some_subcode_part2, tmp1, tmp2, hint='{"mode": "2"}')
    
    return out1, out2

_(...somewhere within torch.compiled model...)_
out1, out2 = torch.ops.higher_order.hinted_context(some_code, out, x, hint='{"tune": "True"}')
```
Feature I have implemented causes nodes A and B to have meta of {tune: True, mode:1} and nodes C and D to have meta of {tune: True, mode:2} as visible in FX graph provided to user fw_compiler. This meta creation happens during creation of joint graph to be precise.

Now, I'd like to extend this feature so that it will also pass this metadata to backward graph created by autograd (BWD nodes should take this metadata from corresponding FWD nodes they were created from). Could you recommend the best approach here to pass it?

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @ydwu4

**Comment by ydwu4** [comment]
For the hinted_context higher order op, does it implement the DispatchKey.Autograd  key? In the implementation of DispatchKey.Autograd, we can get the backward graph based on forward graph and we could just attach the meta data of forward to backward if the meta data is per-sub-graph.

**Comment by kbadz-pl** [comment]
@ydwu4 

In terms of what it implements or not, it is same as torch.ops.higher_order.wrap, the only real difference is __call__ function which tracks Interpreter loops with hint context managers:
![image](https://github.com/pytorch/pytorch/assets/122799060/36272e66-cf2a-4334-84b9-586288aed267)
where gmod.meta["hint"] is set from kwargs during creation of my HOO Variable.

BTW, in the meantime I managed to do some progress on my original issue. So, at the point where we get joint graph in the AOTAutograd, I use node sequence number (+some tweaks to account for operations that do not create autograd nodes and cause seq_nr duplicates) to map between FWD and BWD nodes and to propagate this specific meta information from annotated FWD nodes to corresponding BWD nodes. I have a feeling this might not be the cleanest solution but it works for simple examples as of now and I continue to research possible issues and good direction for that.

**Going back to your proposal** - by implementing DispatchKey.Autograd, do you mean wrapping the HOO with Autograd override? Wouldn't that result in user needing to define backward code on his own for each specific computation subgraph? My goal was to allow user to specify arbitrary forward function, just pass the inputs and let it work automagically. If you mean something else, could you elaborate or point me to some examples?

**Comment by ydwu4** [comment]
I see. I mean something like map, where we implement the DispatchKey.Autograd key manually [here](https://github.com/pytorch/pytorch/blob/main/torch/_higher_order_ops/map.py#L313C1-L318C20) and we create a backward graph from forward graph so it's also automagic from user's perspective.

Back to your specific case, I think you are in the right direction. My proposal may not be suitable for your case since it seems you want aot_autograd to trace into the subgraph of hinted_context instead of preserving the higher order op in the graph after aot_autograd. seq_nr is the right metadata AFAIK.

**Comment by kbadz-pl** [comment]
@ydwu4 I have added draft PR that shows the implementation and usage of the feature. Feel free to check if this is something that could be valuable.

**Comment by kbadz-pl** [comment]
Closing this ticket as it is no longer closely tied with the linked PR. New ticket will be created that explains the feature better.
