### ISSUE TITLE
Incomplete documentation for `torch.randn` on complex dtypes

### ISSUE THREAD

**Issue by mariusarvinte** [pytorch/pytorch#118269]
### 📚 The doc issue

https://pytorch.org/docs/stable/generated/torch.randn.html does not clearly specify behavior on complex data types `torch.complex64` and `torch.complex128`. 

The current notation $\textrm{out}_{i} \sim \mathcal{N} (0, 1)$ may lead to users thinking that both the real and imaginary parts are sampled from a unit Gaussian, but in fact they are each i.i.d. sampled from $\mathcal{N} (0, 1/2)$, leading to the complex signal being (correctly, for a large class of applications) sampled from the complex random normal distribution.

The following basic snippet validates this:

```
import torch

x = torch.randn(1000, 1000, dtype=torch.complex64)
print('Complex signal power using native complex: ', torch.var(x))
print('Real part signal power using native complex: ', torch.var(torch.real(x)))
print('Imag part signal power using native complex: ', torch.var(torch.imag(x)))
```

It will produce:
```
Complex signal power using native complex:  tensor(0.9998)
Real part signal power using native complex:  tensor(0.5005)
Imag part signal power using native complex:  tensor(0.4993)
```

The same holds for `torch.complex128`.

### Suggest a potential alternative/fix

The documentation for `torch.randn` could be updated to include something similar to the following clarifications:

- For complex `dtype`, the tensor is i.i.d. sampled from a complex normal distribution with zero mean and unit variance as: $\textrm{out}_{i} \sim \mathcal{CN} (0, 1) $

- $\mathcal{CN}$ is the standard notation for the complex normal distribution (https://en.wikipedia.org/wiki/Complex_normal_distribution).

cc @svekars @brycebortree @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by ezyang** [comment]
Thanks for the well researched issue report. Do you think you could send us the doc PR?
