### ISSUE TITLE
Memory layout discrepancy of semi-structured sparsity output.

### ISSUE THREAD

**Issue by mleonowicz** [pytorch/pytorch#118282]
## Issue description

I followed the example for semi-structured sparsity and ran benchmarks that can be found here: https://pytorch.org/tutorials/prototype/semi_structured_sparse.html#requirements.

I did see a `2.212x` speedup, but my question is about memory layout. When printing `stride()` of `dense_output` and `sparse_output` tensors the results are different. What causes this discrepancy?

## Code example

To see the results use slightly modified example:

```python
import torch
from torch.sparse import to_sparse_semi_structured, SparseSemiStructuredTensor
from torch.utils.benchmark import Timer
SparseSemiStructuredTensor._FORCE_CUTLASS = True

# mask Linear weight to be 2:4 sparse
mask = torch.Tensor([0, 0, 1, 1]).tile((3072, 2560)).cuda().bool()
linear = torch.nn.Linear(10240, 3072).half().cuda().eval()
linear.weight = torch.nn.Parameter(mask * linear.weight)

x = torch.rand(3072, 10240).half().cuda()

with torch.inference_mode():
    dense_output = linear(x)
    dense_t = Timer(stmt="linear(x)",
                    globals={"linear": linear,
                             "x": x}).blocked_autorange().median * 1e3

    # accelerate via SparseSemiStructuredTensor
    linear.weight = torch.nn.Parameter(to_sparse_semi_structured(linear.weight))

    sparse_output = linear(x)
    sparse_t = Timer(stmt="linear(x)",
                    globals={"linear": linear,
                             "x": x}).blocked_autorange().median * 1e3

    # tensor strides
    # dense_output stride: (3072, 1)
    print(f'dense_output stride: {dense_output.stride()}')
    # sparse_output stride: (1, 3072)
    print(f'sparse_output stride: {sparse_output.stride()}')

    # sparse and dense matmul are numerically equivalent
    assert torch.allclose(sparse_output, dense_output, atol=1e-3)
    print(f"Dense: {dense_t:.3f}ms Sparse: {sparse_t:.3f}ms | Speedup: {(dense_t / sparse_t):.3f}x")
```

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip

**Comment by jbschlosser** [comment]
cc @jcaip insight on this?

**Comment by alexsamardzic** [comment]
For semi-structured sparsity, at the moment there are two "back-ends": cuSPARSELt and CUTLASS (these are two low-level libraries that could be used to peform multiplication between sparse semi-structured and dense tensors on NVIDIA GPUs tensor cores); i.e. there are two different implementations in PyTorch for `linear()` and other operators supporting sparse semi-structured tensors.  In the code you posted, CUTLASS back-end is selected through `SparseSemiStructuredTensor._FORCE_CUTLASS = True` statement.  CUTLASS only supports having sparse semi-structured tensor as first operand of the multiplication.  For input tensor `X` and weight tensor `W`, the linear operator should calculate `X @ W.T`, but in our case `W` is sparse-structured so the calculation is actually performed as `(W @ X.T).T`.  The difference in strides that you've noticed comes from the last transpose.

**Comment by jcaip** [comment]
Yes that's right, if you are using the nightlies you can use the cuSPARSELt backend with `SparseSemiStructuredTensor._FORCE_CUTLASS = False` and `SparseSemiStructuredTensor._FUSE_TRANSPOSE = True`, which should return a `sparse_output` that has the same memory layout as `dense_output` (The strides should be the same).

**Comment by jbschlosser** [comment]
Thanks @alexsamardzic / @jcaip :) Closing as not an issue within PyTorch. If further discussion is needed, please open a thread on the [PyTorch forums](https://discuss.pytorch.org/).
