### ISSUE TITLE
[DCP] Utils and APIs to convert a torch.save and vice versa

### ISSUE THREAD

**Issue by fegin** [pytorch/pytorch#118207]
### 🚀 The feature, motivation and pitch

While we encourage users to use DCP for distributed checkpointing, users may want to publish the checkpoints with the same format as `torch.save()`. This will allow OSS community to use the checkpoints easily. Similarly, users may want to convert the existing model checkpoints from torch.save() format to DCP format.

TODO:

- [ ] An API to read from an existing torch.save() file and convert it to a state_dict with DCP Metadata.
- [ ] An StorageReader to use the previous API to do the conversion. We can combine this item with the previous one.
- [ ] An util to use the previous two items to do torch.save -> DCP conversion.
- [ ] An API to read from an existing DCP checkpoint and convert it to a state_dict.
- [ ] An utils to use the previous one to do DCP -> torch.save conversion.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by wconstab** [comment]
can we tag partners using DCP to get feedback on the proposal?

**Comment by fegin** [comment]
PyTorch 2.3 has the feature.
