### ISSUE TITLE
torch.cond branches validation is a bit too extreme

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#118221]
```py
import torch

def f(x):
    return torch.cond(x > 0, torch.sin, torch.cos, (x,))

x = torch.tensor(1)
f(x)
```
raises: `AssertionError: <class 'torch._dynamo.variables.torch.TorchInGraphFunctionVariable'>`

The thing passed to cond just has to be a callable. Maybe we can relax the check? @ydwu4 

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @ydwu4

**Comment by ydwu4** [comment]
Yeah, sounds good! This looks nicer.

**Comment by zou3519** [comment]
Was fixed
