### ISSUE TITLE
[Feature request] correct semantics on tensors with zero elements

### ISSUE THREAD

**Issue by nikhilmishra000** [pytorch/pytorch#11825]
In numpy, you can do something like `np.zeros((0, 5))` and get a 2d array with shape(0, 5), even though the number of elements is zero. These semantics are very convenient when concatenating/stacking/indexing with this array.

However, any zero-element tensors in pytorch get automatically flattened to 1d with shape(0,). Can pytorch better mimic numpy behavior?

**Comment by SsnL** [comment]
Great idea. We think so too, so we already implemented proper empty tensor support on master. :)
