### ISSUE TITLE
streams x torch.compile: stream is treated as None sometimes

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#118204]
```py
import torch

def fn(x):
    s = torch.cuda.Stream()
    x = torch.mul(x, 5)
    x = torch.add(x, 2)

    print("foo")

    tcs = torch.cuda.stream(s)
    current_stream = torch.cuda.current_stream()
    s.wait_stream(current_stream)

    with tcs:
        x = torch.relu(x)

    current_stream.wait_stream(s)
    x = torch.add(x, 1)
    x = torch.cos(x)
    return x

x = torch.randn((2, 2), device="cuda")
ref = fn(x)
opt_fn = torch.compile(fn, backend="eager")
res = opt_fn(x)
```
Gives:
"AttributeError: 'NoneType' object has no attribute 'wait_stream'"

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @bdhirsh @aakhundov

**Comment by spzala** [comment]
@zou3519 I think this has been fixed by your PR :) and I also verified it with the main branch (2.4.0a0+gitbf834d3) We should close the issue if you agree. Thanks!

**Comment by zou3519** [comment]
the repro succeeds for me now
