### ISSUE TITLE
DTensor + compile error's during backward when output is non-contiguous

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#118219]
This was extracted from a larger internal repro. My smaller repro is below (I had it inside of `test_dtensor_compile.py` to handle DTensor initialization):
```
    def test_dynamo_dtensor_AAA(self):
        mesh = DeviceMesh(self.device_type, torch.arange(self.world_size))

        # test passing in DTensor as inputs/outputs and run some tensor computation
        def fn(x, y, z):
            tmp = x.permute(0, 2, 1).contiguous()
            out = torch._C._nn.linear(tmp, y, z)
            return out.permute(0, 2, 1)

        x = DTensor.from_local(torch.randn(4, 32, 4, requires_grad=True), mesh, [Shard(0)], run_check=False)
        y = DTensor.from_local(torch.randn(4, 32, requires_grad=True), mesh, [Shard(0)], run_check=False)
        z = DTensor.from_local(torch.randn(4, requires_grad=True), mesh, [Shard(0)], run_check=False)
        ref = fn(x, y, z)

        opt_fn = torch.compile(fn, backend="aot_eager", fullgraph=True)
        res = opt_fn(x, y, z)
        self.assertEqual(res, ref)
```

This fails while tracing out the backward, with:
```
    return _reshape_view_helper(a, *shape, allow_copy=False)
  File "/data/users/hirsheybar/d/pytorch/torch/_refs/__init__.py", line 3643, in _reshape_view_helper
    raise ValueError(msg)
torch._dynamo.exc.BackendCompilerFailed: backend='aot_eager' raised:
ValueError: Cannot view a tensor with shape torch.Size([4, 4, 8]) and strides (32, 1, 4) as a tensor with shape (16, 8)!
```

There are a few interesting things on:

(1) When the output of a forward graph is not contiguous, we force the corresponding tangents to be contiguous so we can trace them properly

(2) this mismatch is coming from a `reshape()` call in the backward. I tried running the same test with `TwoTensor` and could not repro - it looks like with `TwoTensor`, we recognize in the backward that the `reshape()` requires a clone, but in this test DTensor, the strides are different between the outer DTensor and the inner tensor, so DTensor thinks that a clone is not necessary.

cc @ezyang @gchanan @zou3519 @kadeng @Chillee @albanD @samdow @msaroufim @anijain2305 @chauhang

**Comment by bdhirsh** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/118669

**Comment by masnesral** [comment]
@bdhirsh I'm going through the high-pri tasks that "haven't been updated in a month". Looks like https://github.com/pytorch/pytorch/pull/118669 is closed. Is this issue fixed perhaps?
