### ISSUE TITLE
Inductor sizevars wrapper assignment DCE hazard

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#118385]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/1405155842844877/posts/7944646722229057

In wrapper.py, we only generate assignments for symbolic variables that are free:

```
        # Assign all symbolic shapes needed to local variables
        needed = V.graph.sizevars.free_symbols()
```

Where free is defined as

```
    def free_symbols(self) -> Set[sympy.Symbol]:
        return set(self.var_to_val.keys()) - set(self.replacements.keys())
```

This means that if we refine a symint like `s0 = s1 - 5`, we will no longer generate an assignment for s0.

This leads to a hazard: it may be possible for there to still be an occurrence of s0 in the program (for example, we may have discovered this replacement very late during Inductor compilation), and if during code generation we do not appropriately call `V.graph.sizevars.simplify` on the computation, we can still end up with a reference to s0, which we have DCE'd.

How to fix? The obvious choices:

* Arrange so that during codegen it is guaranteed that you simplify sizevars before printing them. This is tricky, because printing the sizevar directly will typically work and only fail in obscure situations. So we need some way of making sure people don't do it wrong
* Unconditionally generate assignments for all sizevars, even if we think they are dead

### Versions

main

cc @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

**Comment by ezyang** [comment]
Tentatively, my plan is to rename all the shape variables so that you blow up in an obvious way if you fail to use a special "codegen sympy expressions" function

**Comment by ezyang** [comment]
After discussion in the Inductor weekly, we're just going to unconditionally generate all of the symbol bindings

**Comment by ezyang** [comment]
Internal workaround https://www.internalfb.com/diff/D53134840

**Comment by eellison** [comment]
@ezyang you had a number of Prs around sizevars assignment. Is this still an issue / are you working on it? Could you attach a repro?

**Comment by ezyang** [comment]
This is still not fixed, and all of our repros are from complicated internal models. However, it is not necessary to have a repro: it is clear from code inspection that this edge case should potentially occur, so we should just fix it so it cannot.
