### ISSUE TITLE
We shouldn't allow ghfirst merges of PRs that have been imported internally

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#118310]
This was disallowed in the past, but seems to be allowed now. It seems to be a footgun. 

e.g. we merged https://github.com/pytorch/pytorch/pull/118035 via ghfirst, which has a meta-internal diff associated with it, without actually closing the internal diff.

cc @ZainRizvi @kit1980 @huydhn @clee2000 @pytorch/pytorch-dev-infra

**Comment by kit1980** [comment]
I believe this was always allowed.
What's the exact problem?
I often import PRs to verify that internal CI passes.
The internal diff will be eventually landed by the internal PyTorch release oncall.

**Comment by kit1980** [comment]
What we do check (and if not, it's a bug) - that there are internal-only changes in addition to the open source changes.
If this case landing from GitHub is not allowed.

**Comment by kit1980** [comment]
OK, with https://github.com/pytorch/pytorch/pull/118035 it looks like the diff was modified after the PR was landed.
I'd say this is a very corner case.

**Comment by zou3519** [comment]
> What we do check (and if not, it's a bug) - that there are internal-only changes in addition to the open source changes. If this case landing from GitHub is not allowed.

My bad, I think my experience has been that the PR is not mergeable because of this.

In https://github.com/pytorch/pytorch/pull/118035 we ran into a situation where after we merged the PR, OpenSourceBot updated the internal diff, which led to internal test failures. Those internal failures require internal-only changes.

At that point, we didn't know how to proceed. The usual way to handle this is to just go the co-dev workflow, so I reverted the OSS PR.

**Comment by zou3519** [comment]
Feel free to close this as a corner case if we don't want to do anything about it. NB: I usually import PRs with `ghimport --no-link`, which avoids linking the PR with an internal diff, so I can see the internal signal without ghfirst telling me that "the internal and OSS diffs are out of sync so the PR can't be merged"

**Comment by huydhn** [comment]
Agree with @kit1980 that this is expected.  As a GH first project, there is no reason why people are not allowed to land their PRs if they only touch OSS files.  May be you remember the case when we couldn't reverted the PR because it was associated with an internal diff.  But now reverting is working.

On the other hand, the owners could also create an internal forward fix diff on of [D52977644](https://www.internalfb.com/diff/D52977644) if the fix is straight forward and land them together as a stack themselves.

**Comment by malfet** [comment]
If PR was imported from OSS into Meta, or exported from Meta, but does not contain any non-public changes it is mergeable via mergebot (but internal system should prevent one from landing DIFFs associated via closed PRs unless they are coming thru the Diff-Train)
