### ISSUE TITLE
Download only on 1 replica with HSDP

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#118327]
### 🚀 The feature, motivation and pitch

To minimize bandwidth usage for loading checkpoints, I would like to download on only 1 replica and broadcast to other replicas.

I can sort of do this by calling `distributed.checkpoint.load(...)` with a process group from the first replica, and then I would like to broadcast this state_dict to all of the replicas. So far, I try to do this by pulling out the replicate process group from the device mesh and calling `dist.broadcast_object_list`, but I later hit an error when doing the HSDP reduction

```
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2126, in _train_loop
    total_loss_dict = self._train_batch(use_grad_scaling)
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2309, in _train_batch
    optimizer.step(closure=lambda loss_dict=total_loss_dict, **kwargs: self._train_microbatches(
  File "/usr/lib/python3/dist-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/optim/optimizer.py", line 391, in wrapper
    out = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/llmfoundry/optim/lion.py", line 80, in step
    loss = closure()
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2309, in <lambda>
    optimizer.step(closure=lambda loss_dict=total_loss_dict, **kwargs: self._train_microbatches(
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2412, in _train_microbatches
    microbatch_loss_dict = self._train_microbatch(use_grad_scaling, current_batch_size, is_final_microbatch)
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2541, in _train_microbatch
    microbatch_loss.backward(create_graph=self._backwards_create_graph)
  File "/usr/lib/python3/dist-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/usr/lib/python3/dist-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/usr/lib/python3/dist-packages/torch/autograd/graph.py", line 690, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/lib/python3/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_runtime_utils.py", line 782, in _post_backward_hook
    _reduce_grad(state, handle)
  File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/_runtime_utils.py", line 872, in _reduce_grad
    dist.all_reduce(new_sharded_grad, group=state._inter_node_pg)
  File "/usr/lib/python3/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py", line 2093, in all_reduce
    work = group.allreduce([tensor], opts)
torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '1', but store->get('1') got error: Socket Timeout
Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:563 (most recent call first):
```

Is there a reason broadcasting like this:
```
state_dict_list = [state_dict['state']]
dist.broadcast_object_list(state_dict_list, src=0)
state_dict['state'] = state_dict_list[0]
```
would mess up the device mesh? 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by fegin** [comment]
@mvpatel2000 Not related to the broadcasting question. But for the downloading one replicate statement, is that because you need to download the files to the local disks before performing the DCP.load()? If you directly let DCP.load() to load from the remote storage, DCP should only read the data needed for the rank. Of course the storage block size may affect the actual reading size, but the overall reading size should be much less than downloading the full copy for all the machines.

**Comment by LucasLLC** [comment]
Hey @mvpatel2000, unfortunately I believe what you're trying to do won't work since copying nccl process groups (held in device mesh) breaks usage. I believe you could accomplish what you're trying to do by implementing a custom planner - https://github.com/pytorch/pytorch/blob/3011a4406feae44662738f4e95843861fc0d6745/torch/distributed/checkpoint/planner.py#L263 .

**Comment by mvpatel2000** [comment]
> But for the downloading one replicate statement, is that because you need to download the files to the local disks before performing the DCP.load()?

Yep, we are only downloading the shards needed for a particular rank. But, because we use HSDP and have many replicas, this stacks up :( 

> Hey @mvpatel2000, unfortunately I believe what you're trying to do won't work since copying nccl process groups (held in device mesh) breaks usage. I believe you could accomplish what you're trying to do by implementing a custom planner -

Got it, thanks! I managed to hack something like this where I send the raw bytes of the shard files over to other replicas using the PGs in the device mesh (see below PR to our training library). I originally was doing the loaded `state_dict`, but I switched to raw shard files. Given it seems like you think this is the recommended way, I will close this issue. 

https://github.com/mosaicml/composer/pull/2914/files#diff-a3a2bbee8dce2cadf682b9794c08dafc45e53c1623b7bf6c0c31aab512b8339aR481

**Comment by mvpatel2000** [comment]
> If you directly let DCP.load() to load from the remote storage, DCP should only read the data needed for the rank
@fegin  I have a related question -- when I save on say 32 ranks and load on 32 ranks, I observe all ranks require the 0th shard. This seems to be because of `optimizer.param_groups`. Is this expected?

```
2024-01-28 01:33:22,143: rank40[125][MainThread]: DEBUG: composer.utils.checkpoint: Loading plan item: ReadItem(type=<LoadItemType.BYTE_IO: 2>, dest_index=MetadataIndex(fqn='state.optimizers.DecoupledLionW.param_groups', offset=None, index=None), dest_offsets=torch.Size([0]), storage_index=MetadataIndex(fqn='state.optimizers.DecoupledLionW.param_groups', offset=None, index=None), storage_offsets=torch.Size([0]), lengths=torch.Size([0]))
```

**Comment by wconstab** [comment]
Crazy idea, but do network file systems support seek robustly? Could we support HSDP loading by having each replica read a microshard worth of bytes out of a shard file, and then all gather to materialize through whole shard on all replicas?

**Comment by mvpatel2000** [comment]
@wconstab could you emulate this by replacing the replicate dimension with a shard dim on save? It wouldn't be perfect for elastic cases..

It does seem some blob storages have this ar least 🤯 

https://stackoverflow.com/questions/36436057/s3-how-to-do-a-partial-read-seek-without-downloading-the-complete-file

**Comment by wconstab** [comment]
Yea, that way should also be possible with the limitation you pointed out.

**Comment by mvpatel2000** [comment]
> > If you directly let DCP.load() to load from the remote storage, DCP should only read the data needed for the rank
> 
> @fegin I have a related question -- when I save on say 32 ranks and load on 32 ranks, I observe all ranks require the 0th shard. This seems to be because of `optimizer.param_groups`. Is this expected?
> 
> ```
> 2024-01-28 01:33:22,143: rank40[125][MainThread]: DEBUG: composer.utils.checkpoint: Loading plan item: ReadItem(type=<LoadItemType.BYTE_IO: 2>, dest_index=MetadataIndex(fqn='state.optimizers.DecoupledLionW.param_groups', offset=None, index=None), dest_offsets=torch.Size([0]), storage_index=MetadataIndex(fqn='state.optimizers.DecoupledLionW.param_groups', offset=None, index=None), storage_offsets=torch.Size([0]), lengths=torch.Size([0]))
> ```

Bumping this question @fegin  or maybe @wz337
