### ISSUE TITLE
assertEqualOnRank does not assure the right result when random ops is used with MTPG

### ISSUE THREAD

**Issue by XilunWu** [pytorch/pytorch#118371]
### 🐛 Describe the bug

Symptom: `distributed/_tensor/test_pointwise_ops.py::DistElementwiseOpsTest::test_mul_out` occasionally fails
CI link: https://github.com/pytorch/pytorch/runs/20867866755

Symptom: `distributed/_tensor/test_pointwise_ops.py::DistElementwiseOpsTest::test_dropout_errors` occasionally fails
CI link: https://github.com/pytorch/pytorch/runs/20867751656

### Versions

built from source

cc @wanchaol

**Comment by XilunWu** [comment]
wrong CI signal. close the issue.

**Comment by wconstab** [comment]
Can you add more detail about what signal was wrong?
