### ISSUE TITLE
dist.gather_object does not correctly compute rank in coordinator check

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#118337]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/blob/8c167f9fc3c97a4adb7d8353b7ee6dee4d17bdd2/torch/distributed/distributed_c10d.py#L2440

This line should pass in the group so that it gets the rank in the group instead of the global rank. Otherwise, check's for `is_coordinator` in sharded checkpoint loading will fail.

### Versions

Nightly

cc @ezyang @gchanan @zou3519 @kadeng @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by wconstab** [comment]
this looks like a more widespread issue. (other apis in distributed_c10d.py use get_rank without passing in group). we should fix them all and add a test

**Comment by wconstab** [comment]
ok so the proposed fix is actually not right, afaiu. I am guessing you ran into confusing docs (as i did, when writing the test which clarified my understanding of the current behavior).  See my proposed doc updates and lets go from there.

**Comment by mvpatel2000** [comment]
> ok so the proposed fix is actually not right, afaiu. I am guessing you ran into confusing docs (as i did, when writing the test which clarified my understanding of the current behavior). See my proposed doc updates and lets go from there.

This is very helpful! 

So, should call for `load` use the first rank in the specified PG instead of relying on default?
https://github.com/pytorch/pytorch/blob/8c167f9fc3c97a4adb7d8353b7ee6dee4d17bdd2/torch/distributed/checkpoint/state_dict_loader.py#L41-L49

**Comment by b-chu** [comment]
Same for checkpoint saving
https://github.com/pytorch/pytorch/blame/1bf9ddf130a15abc7cbbe905baf138fb1477b9fe/torch/distributed/checkpoint/state_dict_saver.py#L251

**Comment by wconstab** [comment]
sorry not sure if i understood the latest questions. What's the current issue you're facing (or is this closed?)

**Comment by mvpatel2000** [comment]
> sorry not sure if i understood the latest questions. What's the current issue you're facing (or is this closed?)

@wconstab No longer a bug, feel free to close this issue. However, I do have a feature request (can be reopened as separate issue if you prefer or I can edit this one's top message) -- the `coordinator_rank` argument from public functions (eg distributed save/load calls) should be removed and Torch should pull the first rank from the specified process group (or the default process group if none is specified).

I'm not sure there's any reason a user cares about this implementation detail (though I may be missing a scenario), and it's a bit confusing to specify along with process group.

**Comment by wconstab** [comment]
ok, how about you file a new issue for that request and tag @LucasLLC @fegin @wz337. Thanks!
