### ISSUE TITLE
TCPStore() RuntimeError: unmatched '}' in format string

### ISSUE THREAD

**Issue by jx06T** [pytorch/pytorch#118378]
### 🐛 Describe the bug

I'm experiencing a similar issue with PyTorch's distributed TCPStore. When running the following Python code:

‘’‘
import torch.distributed as dist
from datetime import timedelta
store = dist.TCPStore("127.0.0.1", 0, 1, True, timedelta(seconds=30))
store.add("first_key", 1)
‘’‘

I encounter the same error message:

‘’‘
Traceback (most recent call last):
  File "path/to/their/file.py", line 5, in <module>
    store = dist.TCPStore("127.0.0.1", 0, 1, True, timedelta(seconds=30))
RuntimeError: unmatched '}' in format string
‘’‘

I can't pinpoint the problem. If anyone has insights or solutions, I would greatly appreciate the help. Thank you!

_Originally posted by @jx06T in https://github.com/pytorch/pytorch/issues/109374#issuecomment-1910413252_
But I didn't find a solution in that Issue
            

### Versions

PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: 17.0.6 (https://github.com/llvm/llvm-project.git 6009708b4367171ccdbf4b5905cb6a803753fe18)
CMake version: version 3.27.7
Libc version: N/A

Python version: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Ti Laptop GPU
Nvidia driver version: 551.23
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudnn_ops_infer64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2300
DeviceID=CPU0
Family=198
L2CacheSize=11776
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2300
Name=12th Gen Intel(R) Core(TM) i7-12700H
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] onnxruntime==1.16.3
[pip3] pytorch-lightning==2.1.3
[pip3] pytorch-wpe==0.0.1
[pip3] torch==2.0.0+cu118
[pip3] torch-complex==0.4.3
[pip3] torchaudio==2.0.1+cu118
[pip3] torchmetrics==1.3.0.post0
[pip3] torchvision==0.15.1+cu118
[conda] Could not collect

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by tringwald** [comment]
I can't reproduce this on Linux and given https://github.com/pytorch/pytorch/issues/100185, this seems to be a Windows-only issue. Can you try again with a more recent `torch` version and see if the issue persists?

**Comment by jx06T** [comment]
I appreciate your prompt response.

I've attempted to update to the latest version of torch using the command ‘pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118’ , but I'm still encountering the same issue.

Thank you again for your reply, and I hope to receive further assistance.

**Comment by tringwald** [comment]
Unfortunately, I also could not reproduce the issue on Windows with Python 3.11 and torch 2.1.2. The only problem I encountered was that "127.0.0.1" did not work while "localhost" did.
If that does not fix the problem for you, you could try running again with debug logs turned on and report the output back. This should work in powershell:
```powershell
$env:TORCH_DISTRIBUTED_DEBUG="DETAIL"
$env:TORCH_CPP_LOG_LEVEL="0"
python -c 'import torch; print(torch.__version__); import torch.distributed as dist;from datetime import timedelta;store = dist.TCPStore("127.0.0.1", 0, 1, True, timedelta(seconds=30));store.add("first_key", 1);'
```
