### ISSUE TITLE
Why torch.mm of torch2 is slower than torch1?

### ISSUE THREAD

**Issue by TXacs** [pytorch/pytorch#118349]
### 🐛 Describe the bug

I conducted performance tests on `torch.mm` using both PyTorch2 and PyTorch, and observed that the execution was notably slow.

GPU: NVIDIA 3090 24GB
MEMORY: 128GB

```python
import torch
import time

a = torch.randn(1000, 1000).cuda()
b = torch.randn(1000, 1000).cuda()

ops = torch.mm

# warm up
for i in range(100):
    ops(a,b)

# record time
start_time = time.time()
for i in range(100000):
    ops(a,b)
end_time = time.time()

elapsed_time = end_time - start_time

print("torch.mm cost time is ：", elapsed_time, "sec")
```

results:

```bash
# torch 1.10.0
torch.mm cost time is ：7.71114706993103 sec

# torch 2.1.2
torch.mm cost time is ：13.037514448165894 sec
```

Anybody has the same problem?

### Versions

# torch env
Collecting environment information...
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-84-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

[pip3] numpy==1.19.5
[pip3] torch==1.10.0+cu113
[pip3] torchvision==0.11.1+cu113
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.10.0+cu113             pypi_0    pypi
[conda] torchvision               0.11.1+cu113             pypi_0    pypi

# torch2 env
Collecting environment information...
PyTorch version: 2.1.2+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.27

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-84-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

[pip3] numpy==1.24.2
[pip3] torch==2.1.2+cu118
[pip3] torchaudio==2.1.2
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.1.2+cu118              pypi_0    pypi
[conda] torchaudio                2.1.2                    pypi_0    pypi
[conda] torchvision               0.16.2                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by TXacs** [comment]
collect_env.py results:


> maybe it's because the defaults on using tf32 for matmul have changed between 1.10 and 2.0...

Thanks apply. How do I confirm this difference or how do I eliminate this difference ? It's significantly impacting my model training.

**Comment by tringwald** [comment]
You need to set `torch.backends.cuda.matmul.allow_tf32 = True` in `torch >= 1.12` to allow for TF32 tensor core calculations.

**Comment by TXacs** [comment]
> You need to set `torch.backends.cuda.matmul.allow_tf32 = True` in `torch >= 1.12` to allow for TF32 tensor core calculations.

Thanks a lot. It solved my problem. 😊
