### ISSUE TITLE
_snapshot function in torch/cuda/memory.py does not use its "device" argument

### ISSUE THREAD

**Issue by 27359794** [pytorch/pytorch#118376]
### 🐛 Describe the bug

I think the `_snapshot` function defined [here](https://github.com/pytorch/pytorch/blob/main/torch/cuda/memory.py#L731) should do something with its param (or not accept a param). 

### Versions

It's in the latest `main`, and also in release 2.1.

cc @albanD

**Comment by albanD** [comment]
Hi,

Thanks for pointing it out.
This is a private function (as it starts with _) so we don't provide any guarantee about what it does or not.
