### ISSUE TITLE
Dynamo x autograd.Function: graph breaks on non-{Tensor, symnode, constant} inputs

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#118395]
```
import torch

class MulY(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, ys):
        ctx.save_for_backward(ys[0])
        return x * ys[0]

    @staticmethod
    def backward(ctx, grad_out):
        ys, = ctx.saved_tensors 
        return grad_out * ys

@torch.compile(backend="eager", fullgraph=True)
def f(x, ys):
    return MulY.apply(x, ys)

x = torch.tensor(2., requires_grad=True)
ys = [torch.tensor(2.)]
expected = MulY.apply(x, ys)
out = f(x, ys)
assert torch.allclose(out, expected)
```

We should be able to support this with fullgraph=True
We should be able to do something like manually_set_inputs=False for autograd.Function HOP tracing.

cc @ezyang @gchanan @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

**Comment by oulgen** [comment]
@zou3519 could this be a good ramp up task for my team?

**Comment by yanboliang** [comment]
@oulgen Feel free to assign this to your team. The original goal of this series of task was to help me hardening the skipfiles + allowed_function refactor work. I'd expect to use these tasks to check if my refactor cover the major requirements from PT developers.

**Comment by zou3519** [comment]
Bumping the priority due to some internal feature requests. The fix is something like changing the autograd.Function HOP's [`set_subgraph_inputs` property](https://github.com/pytorch/pytorch/blob/6a3b47ec8fc66f0183bc4b9e7278f48181800ea0/torch/_dynamo/variables/higher_order_ops.py#L328) and then figuring out some bookkeeping (all Tensor inputs to the autograd.Function previously still need to be inputs to the autograd.Function HOP)

**Comment by yf225** [comment]
It's needed for full-graph compile FSDP2 as well: in FSDP2 we pass user-defined object into custom autograd function: https://github.com/pytorch/pytorch/blob/56dd7603da0d9f8b7f7439cf2091a1fd306983f5/torch/distributed/_composable/fsdp/_fsdp_param_group.py#L520
