### ISSUE TITLE
memory leak in cudnn bidirectional RNN with cudnn 6

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#1183]
See this for more context:
https://discuss.pytorch.org/t/tracking-down-a-suspected-memory-leak/1130/30?u=smth

@ngimel has reproduced it

cc @csarofeen @ptrblck @xwang233

**Comment by ngimel** [comment]
It's a cudnn problem, Thomas has reproduced it with cudnn alone. We are looking into it.

**Comment by igormq** [comment]
Is there any update?

**Comment by soumith** [comment]
@ngimel do you know if this was fixed in cudnn7?

**Comment by Stonesjtu** [comment]
Any update on that? This bug prevents pytorch from training on extremely big data. (disable CUDNN backend slows training speed)

**Comment by ngimel** [comment]
@Stonesjtu what's your cudnn version, cuda version and driver version?

**Comment by Stonesjtu** [comment]
cudnn6 and cuda8 driver 390.30 on 1080Ti. The leak appears only in the training step, so I'm wondering if the backward of RNN is the culprit.

**Comment by isofun** [comment]
Is this problem fixed? I also have it with cudnn7102/pytorch0.4.0.

**Comment by zou3519** [comment]
Maybe @ngimel or @mruberry would know?

**Comment by mruberry** [comment]
@csarofeen is the person to ask.

**Comment by csarofeen** [comment]
@isofun this should be fixed with cuDNN 7.2 and later. Please update pytorch/cuDNN so you have a newer version. I've checked versions back to 7.5 and cannot reproduce a leak. I believe we can close this.
