### ISSUE TITLE
Rocm6  (deps?) or 6.0.1? not sure

### ISSUE THREAD

**Issue by terryrankine** [pytorch/pytorch#118457]
### 🐛 Describe the bug

I have the rocm 6.0 ubuntu 22.04 packages installed.
`/opt/rocm-6.0.1/lib/`

The seem to have different links to the ones you have compiled torch against.

I had to create - 
``` cd /opt/rocm-6.0.1/lib/
sudo ln -s libhipsparse.so libhipsparse.so.0  
sudo ln -s libhipblas.so.2 libhipblas.so.1
```

### Versions

NIGHTLY rocm6 version.
`https://download.pytorch.org/whl/nightly/rocm6.0/torch-2.3.0.dev20240126%2Brocm6.0-cp310-cp310-linux_x86_64.whl`

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by hongxiayang** [comment]
@terryrankine Since the wheels already contain the ROCm 6.0.0, you don't need to install ROCm 6.0.1 on your machine. 
Basically, the ROCm versions should be the same. otherwise, don't install ROCm yourself and let the wheel install ROCm for you.

**Comment by hongxiayang** [comment]
@terryrankine Suggestion is given, and we will close this. Thank you for creating the issue.
