### ISSUE TITLE
[dynamo][higher order ops] make_fx causes torch.cond to be recompiled

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#118445]
### 🐛 Describe the bug

~~~
import torch
from functorch.experimental.control_flow import UnsupportedAliasMutationException, cond
from torch.fx.experimental.proxy_tensor import make_fx
import unittest

a = torch.ones(2, 3)
b = torch.ones(2, 3) + 1

def true_fn(x):
    return x + a

def false_fn(x):
    return x + b

def foo(x):
    return cond(x.shape[0] == 4, true_fn, false_fn, [x])


# expected branches takes [x, a, b] as input
inp = torch.randn(2, 3)

foo(inp)

with unittest.mock.patch("torch._dynamo.config.error_on_recompile", True):
    gm = make_fx(foo)(inp)
    gm(inp)
 ~~~

The recompilation reasoning does not print anything here. I looked into more details and the tensor dispatch keys had been modified.

Is the recompilation expected?

### Versions

N/A

cc @ezyang @msaroufim @bdhirsh @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @ydwu4

**Comment by anijain2305** [comment]
cc @ydwu4

**Comment by ydwu4** [comment]
This particular re-compilation is expected: when we make_fx(cond)(inp), inputs are wrapped as ProxyTensor and FakeTensor, while for a eager call `gm(inp)`, the inputs are normal tensors, so this triggers a re-compilation and it's expected.

In fact, when we call multiple gm(inp), we can see only one re-compile happens:
```
gm = make_fx(foo)(inp)
for _ in range(10):
    gm(inp)
``` 
For the above example, only 1 re-compilation happens: the TORCH_LOGS=recompiles log:
```
(pytorch-3.10) ~/local/pytorch$ TORCH_LOGS=recompiles python test.py 
[2024-01-29 14:28:57,201] torch._dynamo.guards.__recompiles: [DEBUG] Recompiling function inner in /home/yidi/local/pytorch/torch/_dynamo/external_utils.py:23
[2024-01-29 14:28:57,201] torch._dynamo.guards.__recompiles: [DEBUG]     triggered by the following guard failure(s):
[2024-01-29 14:28:57,201] torch._dynamo.guards.__recompiles: [DEBUG] 
```
