### ISSUE TITLE
[Nested Tensor] Support NT construction inside PT2 graph

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#118446]
### 🚀 The feature, motivation and pitch

Repro:

```python
import torch
from torch.nested._internal.nested_tensor import ViewNestedFromBuffer, buffer_from_jagged

def fn(values, offsets):
    # return values.cos().sin()
    return ViewNestedFromBuffer.apply(values.cos(), offsets).sin()

fn_c = torch.compile(fn, backend="aot_eager")
# values = torch.rand((12, 8), requires_grad=True)
values = torch.rand((12, 8))
offsets = torch.tensor([0, 1, 2, 5, 8, 9, 12])
lengths = torch.tensor([1, 1, 3, 3, 1, 3])

nt = ViewNestedFromBuffer.apply(values, offsets)
fn_c(values, offsets)
```

* [ ] ViewNestedFromBuffer hits skipfiles #118334
* [ ] Dynamic shapes doesn't really work with this, if any part of the `values` tensor has dynamic shapes in the non-batch dimensions:
  * If `values` is dynamic, then when we construct `self._strides = (ragged_size * stride[self._ragged_idx - 1], *stride)`: `stride` is `values.stride()`; if `stride[self._ragged_idx - 1]` is symbolic, then `ragged_size * stride[..]` is a multiplication of a singleton symbolic symint and a normal python symbolic symint; this is not supported.
* [ ] Symbolic strides don't work correctly
  * `__tensor_unflatten__` needs `values` to be symbolic in order to identify that we can update the `_tensor_symint_registry`. When a NT is an input, we know about dynamism properties because of `mark_dynamic` in the NT constructor. However, when the NT is constructed inside, we don't know about those dynamism properties until after we trace through (and we probably need to check trace order etc. to make sure the dynamism is marked at a point early enough...)
    * Why do we actually need these to be symbolic to do the jaggedness stuff?
  * Suggestion from Jeffrey and Joel: let's just use values instead of offsets, and construct the symbolic int stuff before tracing starts
    * I think we'll still hit the same issue, we need values to be partially dynamic.

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @soulitzer @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by davidberard98** [comment]
@jbschlosser what I meant was, whether we can do this: https://github.com/pytorch/pytorch/pull/118577 (still waiting on CI to see if anything fails...)

**Comment by IvanKobzarev** [comment]
Doing issue scrapping. The repro does not fail, closing.
