### ISSUE TITLE
load weights on Multi-GPU

### ISSUE THREAD

**Issue by Bonsen** [pytorch/pytorch#11849]
I train on one-gpu, and then use save_checkpoint.
Now I train on multi-gpu, and I want to load the weights.

checkpoint = torch.load(check_path)
net.load_state_dict(checkpoint['state_dict'])

It seems doesn't work for me.

**Comment by w-hc** [comment]
First, load your model before nn.dataparallel is applied.
dataparallel encapsulates the model and so the state dictionary may not match exactly. 

In addition, given that device mappings change all the time on cluster, and that there is occasional need to load model under CPU setting for minor tests, I always load with torch.load(map_location='cpu'), before doing load_state_dict. A little bit of extra loading and transfer time in exchange for safety might be a good trade-off.

**Comment by Bonsen** [comment]
@w-hc Thanks.

**Comment by zou3519** [comment]
Resolved
