### ISSUE TITLE
Support `torch.distributed.checkpoint.save/load` when torch dist is not initialized.

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#118554]
### 🚀 The feature, motivation and pitch

The latest torch supports a wonderful unified interface with `torch.distributed.checkpoint.save` and `torch.distributed.checkpoint.load` which makes life so much easier. 

However, it still requires special casing the 1 GPU scenario where dist is not initialized. For example, `dist_cp.save` calls `_gather_state_dict` which requires dist to be initialized. 

There's a lot of nice wrapping in other parts of the code, e.g. the load planner, which helps the code run even when dist is not initialized and no-op the dist ops. It would be great if PyTorch could support these ops without dist initialized and add a unit test for it. 

Example failure: https://github.com/mosaicml/composer/actions/runs/7442570746/job/20246194223

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by wz337** [comment]
@mvpatel2000 Could I ask you what version of PyTorch you have experienced this from? 
We had a fix for this in December (https://github.com/pytorch/pytorch/pull/115660) so it's not in stable build, but let me know if you still see issues in latest nightly.

**Comment by wz337** [comment]
cc @LucasLLC

**Comment by LucasLLC** [comment]
@mvpatel2000 , is the ask here that we automatically set `no_dist=True` if world size is 1?

**Comment by mvpatel2000** [comment]
> @mvpatel2000 , is the ask here that we automatically set `no_dist=True` if world size is 1?

Yes, I think so! I thought it was already set automatically -- definitely explains the issue here 😓. 

If dist is not initialized, I think this should automatically be `no_dist=True`?

**Comment by fegin** [comment]
I really want to dump `no_dist`. Is there a case where dist is initialized but people still want to use `no_dist=True`? cc., @wz337

**Comment by mvpatel2000** [comment]
@LucasLLC @fegin 

Apologies -- I double checked the trace, and I realized this error is actually coming from `from torch.distributed.checkpoint.state_dict import get_model_state_dict` and is not on the load side. I don't think this function has any way of specifying `no_dist=True`.

**Comment by fegin** [comment]
I see. In such a case, we should just disable `get_model_state_dict` and `get_optimizer_state_dict` import if dist is disabled.

**Comment by mvpatel2000** [comment]
> I see. In such a case, we should just disable `get_model_state_dict` and `get_optimizer_state_dict` import if dist is disabled.

It would be nice if those functions did work and provided a unified interface for checkpointing and did work if dist was disabled. I say this as someone who doesn't understand how hard it is :P so feel free to say no if it is very challenging

**Comment by wconstab** [comment]
so @mvpatel2000 wants some of the functionality to work even when dist is not initialized. 

i'm not sure why import is failing.  (this is not a build that has no distributed built in, its a distributed-capable build where we haven't initialized distributed yet, right?)

@mvpatel2000 can you re-summarize your ask (which feature you want to use without initializing dist, and elaborate on what you want to be unified about the interface?  (e.g. do you want `get_model_state_dict` to be the same fn you call for 1-gpu or multi-gpu cases? -- sounds reasonable imo)

**Comment by mvpatel2000** [comment]
> i'm not sure why import is failing. (this is not a build that has no distributed built in, its a distributed-capable build where we haven't initialized distributed yet, right?)

Import is fine, error is that it tries to get default PG which does not exist, see this [comment](https://github.com/pytorch/pytorch/issues/118554#issuecomment-1915378794).

> @mvpatel2000 can you re-summarize your ask (which feature you want to use without initializing dist, and elaborate on what you want to be unified about the interface? (e.g. do you want `get_model_state_dict` to be the same fn you call for 1-gpu or multi-gpu cases? -- sounds reasonable imo)

Yep, I would like to use `get/set_model_state_dict` and `get/set_optimizer_state_dict` as a unified interface in both the 1-GPU and multi-gpu case.

I'm not sure what this entails -- maybe an if statement check around dist initialized and going to `mode.get/set_state_dict` and `optimizer.get/load_state_dict` is sufficient... but you all are the experts :)

**Comment by LucasLLC** [comment]
@mvpatel2000 sorry for the delay on this one, this should be solved in https://github.com/pytorch/pytorch/pull/119332 :) Hopefully we can merge that one soon

**Comment by wconstab** [comment]
will close for now, pls reopen if not resolved!

**Comment by mvpatel2000** [comment]
Looks like the PR Lucas linked was closed in favor of another PR that's still open. But given it looks like it's going to be worked on and merged, good with me to close :)
