### ISSUE TITLE
Unexpected instruction types specified for 'sub' on TIMM seresnext26d_32x4d model

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#118589]
### 🐛 Describe the bug

repro:
```
docker run -it --rm --gpus all python:3.10 bash

pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121 
# ^^^ installs https://download.pytorch.org/whl/nightly/cu121/torch-2.3.0.dev20240129%2Bcu121-cp310-cp310-linux_x86_64.whl

git clone https://github.com/huggingface/pytorch-image-models.git
cd pytorch-image-models
git checkout 88889de923149533593482879a564e7f7e0dabbd

$ python -u benchmark.py --bench train --model seresnext26d_32x4d --img-size 224 -b 128 --torchcompile --no-retry
Benchmarking in float32 precision. NCHW layout. torchscript disabled
Model seresnext26d_32x4d created, param count: 16809512
Running train benchmark on seresnext26d_32x4d for 40 steps w/ input size (3, 224, 224) and batch size 128.
ERROR: "Internal Triton PTX codegen error:
ptxas /tmp/tmp2_dkp4d4.ptx, line 120; error   : Unexpected instruction types specified for 'sub'
ptxas fatal   : Ptx assembly aborted due to errors
" while running benchmark.
--result
{
    "model": "seresnext26d_32x4d",
    "error": "Internal Triton PTX codegen error: \nptxas /tmp/tmp2_dkp4d4.ptx, line 120; error   : Unexpected instruction types specified for 'sub'\nptxas fatal   : Ptx assembly aborted due to errors\n"
}
```

### Error logs

```
Internal Triton PTX codegen error:
ptxas /tmp/tmp2_dkp4d4.ptx, line 120; error   : Unexpected instruction types specified for 'sub'
ptxas fatal   : Ptx assembly aborted due to errors
```

### Minified repro

https://gist.github.com/xwang233/030c9139c5038723af8c0778fe354c20

### Versions

```
H100
PyTorch version: 2.3.0.dev20240129+cu121

[pip3] numpy==1.24.1
[pip3] pytorch-triton==3.0.0+901819d2b6
[pip3] torch==2.3.0.dev20240129+cu121
[pip3] torchaudio==2.2.0.dev20240129+cu121
[pip3] torchvision==0.18.0.dev20240129+cu121
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @ptrblck

**Comment by eellison** [comment]
I couldn't repro with an a100. cc @shunting314 @desertfire do either of you have h100 handy and mind taking a look ?

**Comment by shunting314** [comment]
I tried the minified repro on h100 but can not repro as well. Here is the log I get: https://gist.github.com/shunting314/e41077b11d2bd1d2aca2dafa9f89b326

**Comment by shunting314** [comment]
I tried the original command on my h100 as well and it still does not repro:
```
(pytorch) [shunting@devgpu002.lla3 ~/ws/pytorch-image-models (newpin)]$ time python -u benchmark.py --bench train --model seresnext26d_32x4d --img-size 224 -b 128 --torchcompile --no-retry
/home/shunting/ws/vision/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/shunting/ws/vision/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Benchmarking in float32 precision. NCHW layout. torchscript disabled
Model seresnext26d_32x4d created, param count: 16809512
Running train benchmark on seresnext26d_32x4d for 40 steps w/ input size (3, 224, 224) and batch size 128.
Train [8/40]. 1986.10 samples/sec. 64.448 ms/step.
Train [16/40]. 1990.08 samples/sec. 64.319 ms/step.
Train [24/40]. 1989.72 samples/sec. 64.331 ms/step.
Train [32/40]. 1990.48 samples/sec. 64.306 ms/step.
Train [40/40]. 1988.83 samples/sec. 64.359 ms/step.
Train benchmark of seresnext26d_32x4d done. 1970.62 samples/sec, 64.36 ms/sample
--result
{
    "model": "seresnext26d_32x4d",
    "train_samples_per_sec": 1970.62,
    "train_step_time": 64.359,
    "train_batch_size": 128,
    "train_img_size": 224,
    "param_count": 16.81
}

real    0m56.220s
user    1m4.066s
sys     0m14.379s
```

It's very likely that the issue has already been fixed on trunk.

**Comment by xwang233** [comment]
I'm still able to reproduce this on today's nightly https://download.pytorch.org/whl/nightly/cu121/torch-2.3.0.dev20240131%2Bcu121-cp310-cp310-linux_x86_64.whl on H100.

@shunting314 Thanks for the comments. Did you try the python docker container as well?

**Comment by shunting314** [comment]
@xwang233  I didn't enter the docker container since I don't have a proper dev environment to run docker.

**Comment by tinglvv** [comment]
able to reproduce the error with installing the tonight's nightly wheel in a docker container, and running inductor self tests:

```torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/tmp3s5n3vh6.ptx, line 273; error   : Unexpected instruction types specified for 'sub'
ptxas /tmp/tmp3s5n3vh6.ptx, line 318; error   : Unexpected instruction types specified for 'sub'
ptxas /tmp/tmp3s5n3vh6.ptx, line 363; error   : Unexpected instruction types specified for 'sub'
ptxas /tmp/tmp3s5n3vh6.ptx, line 408; error   : Unexpected instruction types specified for 'sub'
ptxas /tmp/tmp3s5n3vh6.ptx, line 453; error   : Unexpected instruction types specified for 'sub'
ptxas fatal   : Ptx assembly aborted due to errors


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


To execute this test, run the following from the base repo dir:
     python test/inductor/test_torchinductor_dynamic_shapes.py -k test_roll_dynamic_shapes_cuda
```

also see the same error in `test/inductor/test_torchinductor.py -k test_repeat_cuda` `test/inductor/test_torchinductor.py -k test_roll_cuda` `test/inductor/test_torchinductor_codegen_dynamic_shapes.py -k test_roll_dynamic_shapes_cuda`

**Comment by xwang233** [comment]
The TIMM model passed on `torch 2.2.0+cuda12.1, triton==2.2.0`, but still failed in nightly `torch==2.3.0.dev20240213+cu121, pytorch-triton==3.0.0+901819d2b6`.

It's on H100.

**Comment by shunting314** [comment]
@xwang233 / @tinglvv is there any way that you can repro the issue without docker? My guess is this may be cause be some specific version of triton/ ptxas used in your environment.

**Comment by eellison** [comment]
cc @malfet

**Comment by Aidyn-A** [comment]
> @xwang233 / @tinglvv is there any way that you can repro the issue without docker? My guess is this may be cause be some specific version of triton/ ptxas used in your environment.

No, it is not caused by the specific version of triton/ ptxas. You can reproduce it by just pip-installing the nightly PyTorch+CUDA 12.1 wheel and run any test that @tinglvv and @xwang233 reported on **H100**.

**Comment by Aidyn-A** [comment]
IMO https://github.com/openai/triton/issues/2662 is related as downgrading to `triton==2.2.0` fixes the tests.

**Comment by bertmaher** [comment]
This issue appears to be caused by LLVM having an invalid sub.s16x2 instruction defined: https://github.com/llvm/llvm-project/blob/815644b4dd882ade2e5649d4f97c3dd6f7aea200/llvm/lib/Target/NVPTX/NVPTXInstrInfo.td#L841.  I'll put up a patch to llvm to fix this, although it also strikes me as strange that add.s16x2 exists and sub.s16x2 does not, so I'm asking around to see if that's intentional

**Comment by bertmaher** [comment]
This has been fixed in llvm: https://github.com/llvm/llvm-project/commit/20895965b2ed1bd037c64430dba98245ffa1232b.  We'll get the fix once triton bumps its llvm version and pytorch bumps its triton version :-D

I'll leave this issue open for now and try to remember to close it once the requisite version bumps go in

**Comment by bhack** [comment]
Any news on this?

**Comment by bhack** [comment]
Probably this pin update is enough https://github.com/pytorch/pytorch/pull/124429

**Comment by xwang233** [comment]
verified that it's fixed in the latest nightly
