### ISSUE TITLE
`test_scatter_bf16_cuda` fails on V100

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#118581]
### 🐛 Describe the bug

While running inductor CI on V100,  I've found that above-mentioned test fails with unsupported PTX instructions:
```
% python3 inductor/test_torchinductor.py -v -k test_scatter_bf16_cuda
...
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/compile-ptx-src-f5ac42, line 48; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-f5ac42, line 48; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-f5ac42, line 52; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-f5ac42, line 52; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas fatal   : Ptx assembly aborted due to errors
```

### Versions

2.2, nightly

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler

**Comment by eellison** [comment]
@malfet, still working on this ?

**Comment by anijain2305** [comment]
Comments from triage meeting
* V100 has limited support for bfloat16. Since Triton uses more advanced intrinsics, should we fallback?
* Conclusion - fallback only for a few ops - like scatter.

**Comment by masnesral** [comment]
We're doing the weekly check-in on hi-pri issues that haven't been updated in a month. @malfet, any update?

**Comment by malfet** [comment]
This sounds like a duplicate of https://github.com/pytorch/pytorch/issues/118122

**Comment by malfet** [comment]
Closing, were fixed by skipping compile on Volta's for bf16 dtype

**Comment by atalman** [comment]
Validated in Colab:
```
2.4.0+cu121 _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40) True
/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py:1607: UserWarning: Tesla T4 does not support bfloat16 compilation natively, skipping
  warnings.warn(
tensor([[1., 0., 0., 1., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]], device='cuda:0', dtype=torch.bfloat16)
```

**Comment by steveepreston** [comment]
> `UserWarning: Tesla T4 does not support bfloat16 compilation natively, skipping`

same error
