### ISSUE TITLE
DISABLED test_find_mutations (__main__.MutationTests)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#118585]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22dynamo%2Ftest_triton_kernels.py%3A%3AMutationTests%3A%3Atest_find_mutations%22%5D)).

PR #117300 seems to have broken rocm ci.  CC @oulgen @jansel

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by oulgen** [comment]
Ah we need `@skipIfRocm` on this test. @jeffdaily I will prepare a PR.

**Comment by oulgen** [comment]
https://github.com/pytorch/pytorch/pull/118588 will fix this
