### ISSUE TITLE
[dynamo][recompilation] test_set_get_descriptor

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#118563]
### 🐛 Describe the bug

Get this PR - https://github.com/pytorch/pytorch/pull/118448

Run pytest -vs test/dynamo/test_dynamic_shapes.py::DynamicShapesMiscTests::test_getset_descriptor_dynamic_shapes - 

It recompiles because the id(torch.Tensor.shape.__get__) changes invocation to invocation (idk why).

### Versions

NA

cc @ezyang @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @bdhirsh @zou3519 @aakhundov

**Comment by ezyang** [comment]
It's probably because the getter function is being regenerated on the fly.  We could probably fix the C bindings to not do that
