### ISSUE TITLE
 build Pytorch from source: "-DCMAKE_MAKE_PROGRAM=" + ninja_dir TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by sghazimi** [pytorch/pytorch#118534]
### 🐛 Describe the bug

I'm getting the following error when trying to install pytorch from source:

module load gcc/11.2.0 rocm/5.5.1
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git submodule sync; git submodule update --init --recursive
pip3 install -r requirements.txt
python3 tools/amd_build/build_amd.py
python3 setup.py develop | tee build_log
[build_log.txt](https://github.com/pytorch/pytorch/files/14086778/build_log.txt)

I've attached the full log to the ticket. Here is where the failure occurs. 
```
[ 21%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/objectivec/objectivec_enum.cc.o
writing triton.egg-info/PKG-INFO
[ 21%] Building CXX object third_party/ideep/mkl-dnn/src/cpu/x64/CMakeFiles/dnnl_cpu_x64.dir/jit_avx512_core_bf16_dw_conv_kernel.cpp.o
writing dependency_links to triton.egg-info/dependency_links.txt
writing requirements to triton.egg-info/requires.txt
writing top-level names to triton.egg-info/top_level.txt
writing manifest file 'triton.egg-info/SOURCES.txt'
reading manifest file 'triton.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'triton.egg-info/SOURCES.txt'
running build_ext
[ 21%] Building C object confu-deps/XNNPACK/CMakeFiles/microkernels-all.dir/src/f32-vbinary/gen/f32-vsqrdiff-scalar-u2.c.o
Traceback (most recent call last):
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/src/python/setup.py", line 317, in <module>
    setup(
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/build/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/src/python/setup.py", line 240, in run
    self.build_extension(ext)
  File "/lustre/user/sghazimi/pytorch/pytorch/build/oort/src/python/setup.py", line 260, in build_extension
    "-DCMAKE_MAKE_PROGRAM=" + ninja_dir,  # Pass explicit path to ninja otherwise cmake may cache a temporary path
TypeError: can only concatenate str (not "NoneType") to str
[ 21%] Building C object confu-deps/XNNPACK/CMakeFiles/microkernels-all.dir/src/f32-vbinary/gen/f32-vsqrdiff-scalar-u4.c.o
[ 21%] Building C object confu-deps/XNNPACK/CMakeFiles/microkernels-all.dir/src/f32-vbinary/gen/f32-vsqrdiff-scalar-u8.c.o
[ 22%] Building C object confu-deps/XNNPACK/CMakeFiles/microkernels-all.dir/src/f32-vbinary/gen/f32-vsqrdiffc-scalar-u1.c.o
[ 22%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/objectivec/objectivec_enum_field.cc.o
[ 22%] Building CXX object third_party/ideep/mkl-dnn/src/cpu/x64/CMakeFiles/dnnl_cpu_x64.dir/jit_avx512_core_fp16cvt.cpp.o
gmake[5]: *** [CMakeFiles/oort_venv_triton.dir/build.make:70: CMakeFiles/oort_venv_triton] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:114: CMakeFiles/oort_venv_triton.dir/all] Error 2
gmake[3]: *** [Makefile:136: all] Error 2
gmake[2]: *** [CMakeFiles/oort_external.dir/build.make:86: /lustre/user/sghazimi/pytorch/pytorch/torch/src/oort_external-stamp/oort_external-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:1956: CMakeFiles/oort_external.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 22%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/objectivec/objectivec_extension.cc.o
[ 22%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/objectivec/objectivec_field.cc.o
```

Please let me know if you have any idea how to get around this error. 

### Versions

Collecting environment information...
PyTorch version: 2.3.0.dev20240111+rocm5.6
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.6.31061-8c743ae5d

OS: SUSE Linux Enterprise Server 15 SP4 (x86_64)
GCC version: (GCC) 11.2.0 20210728 (HPE)
Clang version: Could not collect
CMake version: version 3.24.2
Libc version: glibc-2.31

Python version: 3.10.10 (main, Apr 14 2023, 19:14:32) [GCC 9.3.0 20200312 (Cray Inc.)] (64-bit runtime)
Python platform: Linux-5.14.21-150400.24.46_12.0.83-cray_shasta_c-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI250X (gfx90a:sramecc+:xnack-)
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.6.31061
MIOpen runtime version: 2.20.0
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7A53 64-Core Processor
CPU family:                      25
Model:                           48
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       1
Stepping:                        1
Frequency boost:                 enabled
CPU max MHz:                     2000.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        3992.80
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       2 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        32 MiB (64 instances)
L3 cache:                        256 MiB (8 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-15,64-79
NUMA node1 CPU(s):               16-31,80-95
NUMA node2 CPU(s):               32-47,96-111
NUMA node3 CPU(s):               48-63,112-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] optree==0.10.0
[pip3] pytorch-triton-rocm==2.2.0+dafe145982
[pip3] torch==2.3.0.dev20240111+rocm5.6
[pip3] torchaudio==2.2.0.dev20240129+rocm5.6
[pip3] torchvision==0.18.0.dev20240129+rocm5.6
[conda] Could not collect

cc @malfet @seemethere @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by hongxiayang** [comment]
if not, please run "conda install cmake ninja"

**Comment by hongxiayang** [comment]
@sghazimi Glad to know it worked for you. The ninja step is necessary.
If you don't want to run this step, you can use a docker image which already installed ninja for you. For example: `rocm/pytorch:latest-base` can be used to build pytorch from source on ROCm platform.

Please feel free to close this issue.
