### ISSUE TITLE
[Bug] Cannot save models using ExportedProgram if the model has weighted layers

### ISSUE THREAD

**Issue by johnzlli** [pytorch/pytorch#118621]
##  Bug Description

When trying to export compiled model, If there are weighted layers in the graph, loading the model via ExportedProgram and running inference fails as the weights and inputs are on different device.

## To Reproduce

example code
```python
import torch

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = torch.nn.Linear(100, 10)

    def forward(self, x):
        return torch.nn.functional.relu(self.lin(x))

model = MyModule().eval().cuda()
x = torch.randn(8, 100).cuda()
opt_model = torch.compile(model)
exp = torch.export.export(opt_model, (x,))
torch.export.save(exp, "model.ep")
new_model = torch.export.load("model.ep")
new_model(x)
```

Error message:
```
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0!
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g. 1.0): 2.0
 - OS (e.g., Linux): linux
 - Python version: 3.10
 - CUDA version: 11.8

## Additional context
Related pytorch issue: https://github.com/pytorch/TensorRT/issues/2341
It seems that https://github.com/pytorch/pytorch/issues/114000 has been fixed. However the MR https://github.com/pytorch/pytorch/pull/114695 was closed. So the bug is still active.

### Versions

![image](https://github.com/pytorch/pytorch/assets/38726413/a95bba8b-3330-409c-b615-5525b305938a)

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by angelayi** [comment]
https://github.com/pytorch/pytorch/pull/114695's fix should be in PyTorch version 2.2 which will be releasing soon, or you can use the nightlies.
