### ISSUE TITLE
HSDP + TP Support with DTensor

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#118639]
### 🚀 The feature, motivation and pitch

Currently, Torch does not support HSDP + TP with DTensor. I have it running fine with some monkeypatches, but I need some guidance on the best way to upstream these changes.

PRs:
- https://github.com/pytorch/pytorch/pull/112435
- https://github.com/pytorch/pytorch/pull/118620
- https://github.com/pytorch/pytorch/pull/119064
- https://github.com/pytorch/pytorch/pull/118638
- https://github.com/pytorch/pytorch/pull/119481

With the above open PRs, I'm able to run things smoothly. However, I still hit issues with checkpointing. The crux of the issue is related to supporting 3D device meshes. 

Currently, `_chunk_dtensor` needs remove this:
https://github.com/pytorch/pytorch/blob/2327879fb6fe3836a9be0bca18e6442d07c04900/torch/distributed/tensor/parallel/fsdp.py#L236
Additionally, the following code:
https://github.com/pytorch/pytorch/blob/2327879fb6fe3836a9be0bca18e6442d07c04900/torch/distributed/tensor/parallel/fsdp.py#L275
breaks for 3D meshes with HSDP as the first dimension should stay as replicate due to HSDP. See our monkeypatch here:
https://github.com/mosaicml/composer/blob/f8749567c0919697bbfecb3d3babd1b933327957/composer/trainer/mosaic_fsdp_utils.py#L863-L865

Is there a better way to do the last step?

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by mvpatel2000** [comment]
```
def get_Nd_submesh(device_mesh: DeviceMesh,
                   mesh_dim_names: List[str]) -> DeviceMesh:
    # Modified from torch code. TODO: upstream
    # swap the current dim to the last dim then reshape to flatten out other
    # dims, so we can just extract the list of ranks which contains cur_rank.
    mesh_dims = [
        device_mesh.mesh_dim_names.index(mesh_dim_name)  # type: ignore
        for mesh_dim_name in mesh_dim_names
    ]
    cur_rank = device_mesh.get_rank()
    mesh = device_mesh.mesh
    all_mesh_dims = list(range(mesh.ndim))
    for mesh_dim in mesh_dims:
        # remove not pop b/c we want the value of the ind removed not it's position in the list
        # because this list dynamically changes.
        all_mesh_dims.remove(mesh_dim)

    mesh_sizes = [device_mesh.mesh.size(mesh_dim) for mesh_dim in mesh_dims]

    pg_ranks_by_dim = device_mesh.mesh.permute(*all_mesh_dims,
                                               *mesh_dims).reshape(
                                                   -1, *mesh_sizes)

    for mesh_nd in pg_ranks_by_dim:
        if cur_rank in mesh_nd:
            sub_mesh = DeviceMesh(
                device_mesh.device_type,
                mesh_nd,
                mesh_dim_names=mesh_dim_names,  # type: ignore
                _init_process_groups=False,
            )
            res_sub_mesh = sub_mesh

    res_sub_mesh._dim_group_infos = [  # type: ignore
        device_mesh._dim_group_infos[mesh_dim]
        for mesh_dim in mesh_dims  # type: ignore
    ]
    # Assign the current DeviceMesh as the parent of the child DeviceMesh.
    from torch.distributed.device_mesh import _mesh_resources

    _mesh_resources.child_to_parent_mapping[
        res_sub_mesh] = device_mesh  # type: ignore
    return res_sub_mesh  # type: ignore
```

@wz337  I would also like to add a general submesh function. Can we just replace the existing one?

**Comment by wz337** [comment]
Looping @wanchaol 

> ```
> def get_Nd_submesh(device_mesh: DeviceMesh,
>                    mesh_dim_names: List[str]) -> DeviceMesh:
>     # Modified from torch code. TODO: upstream
>     # swap the current dim to the last dim then reshape to flatten out other
>     # dims, so we can just extract the list of ranks which contains cur_rank.
>     mesh_dims = [
>         device_mesh.mesh_dim_names.index(mesh_dim_name)  # type: ignore
>         for mesh_dim_name in mesh_dim_names
>     ]
>     cur_rank = device_mesh.get_rank()
>     mesh = device_mesh.mesh
>     all_mesh_dims = list(range(mesh.ndim))
>     for mesh_dim in mesh_dims:
>         # remove not pop b/c we want the value of the ind removed not it's position in the list
>         # because this list dynamically changes.
>         all_mesh_dims.remove(mesh_dim)
> 
>     mesh_sizes = [device_mesh.mesh.size(mesh_dim) for mesh_dim in mesh_dims]
> 
>     pg_ranks_by_dim = device_mesh.mesh.permute(*all_mesh_dims,
>                                                *mesh_dims).reshape(
>                                                    -1, *mesh_sizes)
> 
>     for mesh_nd in pg_ranks_by_dim:
>         if cur_rank in mesh_nd:
>             sub_mesh = DeviceMesh(
>                 device_mesh.device_type,
>                 mesh_nd,
>                 mesh_dim_names=mesh_dim_names,  # type: ignore
>                 _init_process_groups=False,
>             )
>             res_sub_mesh = sub_mesh
> 
>     res_sub_mesh._dim_group_infos = [  # type: ignore
>         device_mesh._dim_group_infos[mesh_dim]
>         for mesh_dim in mesh_dims  # type: ignore
>     ]
>     # Assign the current DeviceMesh as the parent of the child DeviceMesh.
>     from torch.distributed.device_mesh import _mesh_resources
> 
>     _mesh_resources.child_to_parent_mapping[
>         res_sub_mesh] = device_mesh  # type: ignore
>     return res_sub_mesh  # type: ignore
> ```
> 
> @wz337 I would also like to add a general submesh function. Can we just replace the existing one?

Looping @wanchaol on this one since we have discussed about the UX for allowing > 1D slicing. 
We probably don't want to remove the current 1D slicing, since it has been rolled out and users are already using it, but we can add a new API to allow >1D slicing. Wdyt?

**Comment by wanchaol** [comment]
> Looping @wanchaol on this one since we have discussed about the UX for allowing > 1D slicing.
We probably don't want to remove the current 1D slicing, since it has been rolled out and users are already using it, but we can add a new API to allow >1D slicing. Wdyt?

I actually don't like a separate API for this, it's similar to 1D slicing so we shouldn't introduce an additional API. IMO this should just be added to the existing `create_child_mesh` logic when calling `device_mesh.__getitem__`

**Comment by wz337** [comment]
> > Looping @wanchaol on this one since we have discussed about the UX for allowing > 1D slicing.
> > We probably don't want to remove the current 1D slicing, since it has been rolled out and users are already using it, but we can add a new API to allow >1D slicing. Wdyt?
> 
> I actually don't like a separate API for this, it's similar to 1D slicing so we shouldn't introduce an additional API. IMO this should just be added to the existing `create_child_mesh` logic when calling `device_mesh.__getitem__`

Makes sense. The question is more about the UX, how we are allowing the user to provide the mesh_dim_name or names to slice. 
In this case, we would want __getitem__ to take in a str or a tuple of strings to support 1D and nD, right?

**Comment by chauhang** [comment]
@mvpatel2000 Please check this wiki for details for writing and running tests: https://github.com/pytorch/pytorch/wiki/Running-and-writing-tests

**Comment by wz337** [comment]
> @wz337 @wconstab we also probably want to add a unit test for this case. I'm unfortunately not familiar enough with the pytorch testing setup to add it... could someone from the torch team handle it?
> 
> All the PRs for features have been landed to support this besides creating / slicing N-D meshes which @wz337 is driving but the testing setup is still missing :(

Hey, @mvpatel2000. I think for your use case your should be able to easily reuse this DTensor Testbase for the 2D stuff. For DTensorTestbase, it would create the pg for you behind the scene so you can directly do things you need to do with distributed. Here is a good example: 

https://github.com/humingxue/pytorch/blob/main/test/distributed/_tensor/test_device_mesh.py#L69

Let me know if anything is not clear.
