### ISSUE TITLE
[Pytorch-ONNX Conversion] Unexpected Additional Input Arguments after Converting PyTorch Model to ONNX Format

### ISSUE THREAD

**Issue by zjc664656505** [pytorch/pytorch#118714]
### 🐛 Describe the bug

After converting a specific PyTorch model to ONNX format, I observed that the ONNX model requires additional input arguments (onnx::Unsqueeze_2, onnx::Unsqueeze_3) that were not part of the original PyTorch model inputs. This issue leads to inference failures since these additional inputs were not anticipated and are not provided during the inference stage.

The original Pytorch Model Inputs are (reshape_47, size_170). After model conversion, it becomes (reshape_47, size_170, onnx::Unsqueeze_2, onnx::Unsqueeze_3)

![image](https://github.com/pytorch/pytorch/assets/45058866/6c883be9-fd15-4805-863d-d9327138a495)

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.3
Libc version: N/A

Python version: 3.10.11 (main, Apr 20 2023, 13:59:00) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] onnx==1.14.0
[pip3] onnxruntime==1.16.1
[pip3] onnxruntime-extensions==0.8.0
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2023.1.0         h59209a4_43558  
[conda] mkl-service               2.4.0           py310h6c40b1e_1  
[conda] mkl_fft                   1.3.6           py310h3ea8b11_1  
[conda] mkl_random                1.2.2           py310h3ea8b11_1  
[conda] numpy                     1.24.3          py310h827a554_1  
[conda] numpy-base                1.24.3          py310ha186be2_1  
[conda] pytorch                   2.0.1                  py3.10_0    pytorch
[conda] torchaudio                2.0.2                 py310_cpu    pytorch
[conda] torchvision               0.15.2                py310_cpu    pytorch

**Comment by thiagocrepaldi** [comment]
PLease provide a full repro script and reopen this issue if it is still relevant
