### ISSUE TITLE
inductor error when output graph is alias of a synced collective

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#118759]
Extracted a repro from an internal model:
```
+    def test_inductor_wait_followed_by_view(self):
+        mesh = DeviceMesh(self.device_type, torch.arange(self.world_size))
+
+        # pass in tensor as inputs/outputs, create DTensor and run redistribute
+        # (allgather collective) inside the fn
+        def fn(x_dt):
+            out = x_dt.redistribute(mesh, [Replicate()])
+            return out.view(-1)
+
+        x = torch.ones(4, 4)
+        x_dt = DTensor.from_local(x, mesh, [Shard(0)], run_check=False)
+        opt_fn = torch.compile(fn, backend="inductor", fullgraph=True)
+        res = opt_fn(x_dt)
```

The (relevant) generated code looks like this:
```
        # collective out buffer buf0
        buf1_pg = c10d._find_or_create_pg_by_ranks_and_tag('ptd:0', [0, 1], 2)
        buf1_inputs = [arg0_1]
        buf1 = [buf0]
        buf1_work = dist.all_gather_into_tensor(buf1[0], buf1_inputs[0], async_op=True, group=buf1_pg)
        fun_col_impl._register_tensor_work(buf1, buf1_work)
        del arg0_1
        buf2 = buf1[0]
        del buf1
        buf2 = _wait_tensor(buf2)
        return (reinterpret_tensor(buf3, (32, ), (1, ), 0), )
```

Where the code fails at runtime because `buf3` doesn't exist.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @ezyang @msaroufim @anijain2305 @zou3519

**Comment by bdhirsh** [comment]
**Investigation**
A few things that I noticed after some investigation:

(1) The `Wait` inductor IR node has `self.get_name() == buf3`, (which is why `buf3` shows up as part of the output)

(2) Today, this normally works because inductor tries to generate a line that looks like `buf3 = buf2` with the `ReuseLine` [here](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/ir.py#L6841)

(3) That `ReuseLine` get's DCE'd during memory planning [here](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/codegen/wrapper.py#L745). Why? the `ReuseLine` we generate has `ReuseLine.node.name == 'buf2'`, but `V.graph.get_output_names() == ['buf3']`, so we think it's dead code.

(4) I compared this case to what inductor does when we just return `out` directly (instead of a `view`). Interestingly, we get very different code, where the returned buffer is `buf2` instead of `buf3` (even though the `Wait` IR node still has `Wait.get_name() == 'buf3'`):
```
       buf1_work = dist.all_gather_into_tensor(buf1[0], buf1_inputs[0], async_op=True, group=buf1_pg)
        fun_col_impl._register_tensor_work(buf1, buf1_work)
        del arg0_1
        buf2 = buf1[0]
        del buf1
        buf2 = _wait_tensor(buf2)
        buf3 = buf2;  # reuse
        return (buf2, )
```

Why is `buf2` getting returned? Current logic:

(4a) inductor sometimes adds logic to directly `as_strided()` graph outputs, to ensure that they have the expected strides that users requested ([code](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/graph.py#L918))

(4b) If that output IR node in question is a view / has an `AliasedLayout`, , inductor generates the as_strided code off of its base ([here](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/ir.py#L3810))

(4c): the `Wait` IR node is always set up to have an `AliasedLayout` ([code](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/ir.py#L6848))


**Tentative Plan**
It seems like there's tension between the fact that `_wait_tensor()` is fundamentally an side-effecting operation (wait for data to arrive), but inductor codegen expects every IR node to output a new buffer.

`_wait_tensor()` already returns the input tensor inplace today though, so it seems acceptable to generate this code:
```
# _wait_tensor(self) returns self directly, so this is the same as syncing + running `buf3 = buf2`
buf3 = _wait_tensor(buf2); del buf2

# All future operations (views, inputs to other ops, etc) should use buf3, not buf2
```

In order to ensure that we don't buf2 at all later, I'm also severing the "alias" relationship between the input and output of `wait()` (we can just pretend it's a functional op)

PR coming soon, but I'm interested in thoughts from inductor folks on if this seems like a reasonable strategy!

**Comment by bdhirsh** [comment]
Potential fix: https://github.com/pytorch/pytorch/pull/118802

**Comment by zou3519** [comment]
@bdhirsh is this issue still relevant? It looks like you had a fix? https://github.com/pytorch/pytorch/pull/118802

**Comment by bdhirsh** [comment]
I forget exactly which PR fixed this, but it no longer repros for me. Closing
