### ISSUE TITLE
24 Dynamo test are failing with "expected FunctionType found builtin_function_or_method <built-in method _make_subclass of torch._C._TensorMeta object at 0xDEADBEEF".

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#118790]
24 Dynamo test are failing with "expected FunctionType found builtin_function_or_method <built-in method _make_subclass of torch._C._TensorMeta object at 0xDEADBEEF".

## Repro

`PYTORCH_TEST_WITH_DYNAMO=1 pytest test_serialization.py -v -k test_tensor_subclass_deepcopy`

You will need to remove the skip or expectedFailure before running the repro command.
This may be just removing a line in
[dynamo_test_failures.py](https://github.com/pytorch/pytorch/blob/main/torch/testing/_internal/dynamo_test_failures.py)

## Failing tests

Here's a comprehensive list of tests that fail (as of this issue) with the above message:
<details>
<summary>Click me</summary>
```
test_serialization.py::TestSubclassSerialization.test_tensor_subclass_deepcopy
test_serialization.py::TestSubclassSerialization.test_tensor_subclass_getstate_overwrite
test_serialization.py::TestSubclassSerialization.test_tensor_subclass_wrapper_serialization
profiler/test_profiler_tree.py::TestProfilerTree.test_profiler_experimental_tree_with_stack_and_torch_dispatch
test_autograd.py::TestAutogradForwardMode.test_make_dual_torch_dispatch
test_quantization.py::TestBitsCPU.test_subclass_cpu
test_python_dispatch.py::TestPythonDispatch.test_data_ptr_respects_numel_slow_path
test_python_dispatch.py::TestPythonDispatch.test_dim_slowpath
test_python_dispatch.py::TestPythonDispatch.test_dispatch_super_call
test_python_dispatch.py::TestPythonDispatch.test_dispatch_super_call_list_arg
test_python_dispatch.py::TestPythonDispatch.test_dispatch_super_dont_autograd
test_python_dispatch.py::TestPythonDispatch.test_exception_handling
test_python_dispatch.py::TestPythonDispatch.test_fancy_strides
test_python_dispatch.py::TestPythonDispatch.test_invalid_ret
test_python_dispatch.py::TestPythonDispatch.test_is_contiguous_slow_path
test_python_dispatch.py::TestPythonDispatch.test_layout_slow_path
test_python_dispatch.py::TestPythonDispatch.test_list_ret
test_python_dispatch.py::TestPythonDispatch.test_mode_with_make_subclass
test_python_dispatch.py::TestPythonDispatch.test_multiple_ops_subclass
test_python_dispatch.py::TestPythonDispatch.test_sizes_slow_path
test_python_dispatch.py::TestPythonDispatch.test_strides_slow_path
test_python_dispatch.py::TestPythonDispatch.test_subclass_autograd_device_check
test_python_dispatch.py::TestPythonDispatch.test_subclass_priority
test_python_dispatch.py::TestPythonDispatch.test_torch_dispatch_mode_subclass_priority
```
</details>

cc @ezyang @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by laithsakka** [comment]
The repo can simplified to :
```
 wrapped_tensor = torch.ones(2)
 r = torch.Tensor._make_subclass(TestWrapperSubclass)
```

**Comment by laithsakka** [comment]
this can simplified to 
```
        wrapped_tensor = torch.ones(2)
        r = torch.Tensor._make_subclass(TestWrapperSubclass, wrapped_tensor.to('meta'))
```

note that the bellow does not fail:
```
        wrapped_tensor = torch.ones(2)
        r = torch.Tensor._make_subclass(TestWrapperSubclass, wrapped_tensor)
```

**Comment by laithsakka** [comment]
The problem is actually can be further simplified to 
```
        wrapped_tensor = torch.ones(2)
        y = wrapped_tensor.to('meta')
        ```

**Comment by laithsakka** [comment]
I identified that revering the changes added in this diff fix the issue
https://github.com/pytorch/pytorch/pull/104689
Namely commenting out those lines

```
 # # In case of dtype promotion, faketensor converted into tensor.
    # # Need to convert into faketensor if input was a faketensor.
    # if dtype_converted:
    #     x = wrap_output_with_input_device_(x, common_device)
 ```

**Comment by laithsakka** [comment]
Looks like that removing that part fixed it, I do not see any failures in the PR above but instead I see 5 unexpected passes.

**Comment by laithsakka** [comment]
Another way to do if we want to be safe is 
```
    # In case of dtype promotion, faketensor converted could be converted into tensor.
    # Need to convert into faketensor if input was a faketensor.
    currentIsFake = isinstance(x, torch._subclasses.FakeTensor)
    if inputIsFake and not currentIsFake:
        # there is no test case the triggers this right now shall we keep it?
        x = wrap_output_with_input_device_(x, common_device)
  ```

**Comment by laithsakka** [comment]
I will change it to assertion for now because it sounds to me that changing dtype or device type on a fake tensor should not make it not fake?
and if so the error would be in the conversion
```
   if device is None and dtype is None and memory_format is None:
        return x.clone()
    dtype_converted = False
    common_device = device_hint(x)
    inputIsFake = isinstance(x, torch._subclasses.FakeTensor)

    if device is not None and device != x.device:
        # avoid conversions on cpu
        if dtype is not None and device.type == "cpu":
            x = torch._prims.convert_element_type(x, dtype)
            dtype_converted = True
        x = torch._prims.device_put(x, device)

    if dtype is not None and not dtype_converted:
        x = torch._prims.convert_element_type(x, dtype)
        dtype_converted = True

    currentIsFake = isinstance(x, torch._subclasses.FakeTensor)
    if inputIsFake:
        assert currentIsFake
 ```

**Comment by laithsakka** [comment]
another issue I am seeing is that a function which is annotated to except t Tensor input complains when it receives 
a tensor subclass, I feel the appropriated fix here is the following:

def is_batchedtensor(tensor: Tensor) -> bool: ...
change to :
def is_batchedtensor(tensor: Type[Tensor]) -> bool: ...

but i will seperate this change into its own PR

**Comment by jerrychenhf** [comment]
@laithsakka I found that the following case will show the case that the input was originally fake tensor and output has become non fake:

```
import torch
def fn(a):
 b = a.t()
 b.mul_(1.0)
 return b

x = torch.arange(6).reshape([2, 3]).to('cpu')

print("x ", x.cpu())

compiled_fn = torch.compile(fn)
y = compiled_fn(x)

print("y ", y.cpu())
```
When add some print before and after convert element type, it prints out:
```
_to_copy start: FakeTensor(..., device='meta', size=(3, 2), dtype=torch.int64)
converted: tensor(..., device='meta', size=(3, 2))
_to_copy start: FakeTensor(..., size=(3, 2))
converted: FakeTensor(..., size=(3, 2), dtype=torch.int64)
_to_copy start: FakeTensor(..., size=(3, 2))
converted: FakeTensor(..., size=(3, 2), dtype=torch.int64)
```

So there are cases that the Faketensor becomes  tensor and is not reserved.  Shall we add wrap_output_with_input_device_  back for such cases?
I noticed that you mentioned one possible solution that make sure _convert_element_type_meta reserve the fakeness instead. I checked the code and convert_element_type change will be very impactful and will be more risky.

I saw you previous have the code that check the input and current type as the fakeness and call wrap_output_with_input_device only necessary. But this solution was not used finally. Is there any special reason for that?
