### ISSUE TITLE
Pytorch 2.2 regression

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#118865]
### 🐛 Describe the bug

I had a regression just upgrading the pytorch docker image from 2.1.2 to 2.2.0. I was testing compiling some model forward of:
https://github.com/yoxu515/aot-benchmark/tree/paot

Some of these are failing the compilation where instead it was working 2.1.2 other are compiling fine but the weights are exploding after some steps with the same code/configuration when instead it was training fine with 2.1.2.

What I've compiled
https://github.com/yoxu515/aot-benchmark/blob/paot/networks/layers/attention.py#L22-L126

https://github.com/yoxu515/aot-benchmark/blob/paot/networks/layers/transformer.py#L274-L334

https://github.com/yoxu515/aot-benchmark/blob/paot/networks/encoders/swin/swin_transformer.py#L684-L716

https://github.com/yoxu515/aot-benchmark/blob/paot/networks/decoders/fpn.py#L103-L129

Other then specific regression I think in general this a quite interesting model to stress test the compiler so I hope you can add it in your regular CI/compiler test suite.

 

### Versions

Official PyTorch Docker image `pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime`

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by eellison** [comment]
Would you please post a specific regression with a repro ?

**Comment by bhack** [comment]
Just to specify a single regression you can use the official Pytorch image specified in the ticket and check and see that compiling this `forward` method:
https://github.com/yoxu515/aot-benchmark/blob/paot/networks/layers/transformer.py#L29-L131C24

it is compiling without probleme up to pytorch 2.1.2 and then failing with pytorch 2.2.0 image with:

```    assert_size_stride(permute_10, (1, s2, s0), (0, 1, 2916))
AssertionError: expected size 11664==11664, stride 5832==2916 at dim=2
```

**Comment by eellison** [comment]
It's for easier to fix with if you have a specific set of instructions that will reproduce the error instead of a link to model. See: https://pytorch.org/docs/master/compile/troubleshooting.html for details on how to submit a repro. You can run with `TORCHDYNAMO_REPRO_AFTER="aot"` and a repro will get generated.

**Comment by bhack** [comment]
It was a model interesting in general to stress test the compiler this was the main point.
Just to go on the explicit regression. 
If I run the generated minifier I got:
```
raise RuntimeError("Input graph did not fail the tester")
RuntimeError: Input graph did not fail the tester
````

**Comment by eellison** [comment]
That's unfortunate the minifier isn't working. Still, can you please give a specific set of repro instructions for the failure ? That would be more helpful. Here is an example an of issue that had a repro instructions so I was immediately able to test it out: https://github.com/pytorch/pytorch/issues/118589

**Comment by bhack** [comment]
Ok let's start with the compile failure regression introduced with 2.2.0 and then we will try to understand how we can debug the other regression. And then the other failure. 

```Dockerfile
FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-devel as builder
ENV GPU_ARCH="75 80 86"
RUN apt-get update && apt-get install -y --no-install-recommends \
   git \
   g++ \
   && rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN pip install ninja
RUN git clone --depth 1 https://github.com/ClementPinard/Pytorch-Correlation-extension.git \
   && cd Pytorch-Correlation-extension \
   && python3 setup.py bdist_wheel

FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime
COPY --from=builder /src/Pytorch-Correlation-extension/dist/*.whl /tmp/
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
   g++ \
   git \
   tk \
   && rm -rf /var/lib/apt/lists/*
RUN python -m pip install --upgrade  opencv-python-headless tensorboard  /tmp/*.whl
````

Build this Dockerfile image

Then start a GPU container using the produced image and execute these commands
```bash
sudo apt-get update && apt-get install wget unzip
git clone -b compiler_test  --depth 1  https://github.com/bhack/aot-benchmark.git
cd aot-benchmark/
cd datasets
wget https://data.vision.ee.ethz.ch/csergi/share/davis/DAVIS-2017-trainval-480p.zip
unzip DAVIS-2017-trainval-480p.zip 
cd ..
TORCHDYNAMO_REPRO_AFTER="aot" python tools/train.py --amp --exp_name compiler_test --config ms_swinb_yd  --gpu_num 1 --batch_size=1
```

**Comment by eellison** [comment]
This is a distributed failure with size stride, seems likely to be related to https://github.com/pytorch/pytorch/issues/113812. You could try running with either `TORCHINDUCTOR_KEEP_OUTPUT_STRIDE=0 `, `torch._dynamo.optimize_ddp_lazy_compile = True`, or `torch._dynamo.optimize_ddp = False`

**Comment by bhack** [comment]
`torch._dynamo.optimize_ddp = False`

Still 
```python
 assert_size_stride(permute_10, (1, s2, s0), (0, 1, 841))
AssertionError: expected size 3364==3364, stride 1682==841 at dim=2
```

`TORCHINDUCTOR_KEEP_OUTPUT_STRIDE=0`

```python 
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
AssertionError: Detected that you are running DDP with torch.compile, along with these two flags:
- torch._dynamo.config.optimize_ddp = True
- torch._inductor.config.keep_output_stride = False
```
`torch._dynamo.optimize_ddp_lazy_compile = True`

```python
    assert_size_stride(permute_10, (1, s2, s0), (0, 1, 841))
AssertionError: expected size 3364==3364, stride 1682==841 at dim=2
```

**Comment by bhack** [comment]
Also let me know how we want to progress with the other forward compile regression pytorch 2.2.0 regression as they are more complex to be debugged cause they compile but the train diverge after few  N steps vs the same fcompiled forwards with pytorch 2.1.0

**Comment by bhack** [comment]
@bdhirsh Minfier failed again and
```    
assert_size_stride(permute_10, (1, s2, s0), (0, 1, 841))
AssertionError: expected size 3364==3364, stride 1682==841 at dim=2
```

**Comment by bhack** [comment]
@bdhirsh Also I have a list of other failing fowards on the same repo/model how we want to proceed? Can you adopt the model to stress test the compiler or we need to go ahead ticket by ticket?

**Comment by masnesral** [comment]
Adding "triaged" since this is assigned.

**Comment by yf225** [comment]
@bhack Does this still repro on PyTorch nightly build? A combination of https://github.com/pytorch/pytorch/pull/120523 and https://github.com/pytorch/pytorch/pull/120727 should fix the strides issue.

**Comment by bhack** [comment]
@yf225 We have the full reproducibility at https://github.com/pytorch/pytorch/issues/118865#issuecomment-1924745100

But I have not started a new training session again so if you want you can quickly re-run it on nightly
