### ISSUE TITLE
recompiling a model on a subclass then on a plain tensor causes malformed guards

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#118896]
Smaller repro generated off of an internal repro. Example:
```
+    def test_torch_dispatch_subclass_guard_recompile(self):
+        from torch.testing._internal.two_tensor import TwoTensor
+        x = torch.ones(2, 2)
+        x_two = TwoTensor(x.clone(), x.clone())
+
+        def fn(w):
+            return torch.add(w, 1.0)
+
+        fn_opt = compile_full_eager(fn)
+
+        res_exp = fn(x_two)
+        res_act = fn_opt(x_two)
+        self.assertEqual(res_exp, res_act)
+
+        # recompile!
+        res_exp = fn(x)
+        res_act = fn_opt(x)
+        self.assertEqual(res_exp, res_act)
```

Fn is run here twice, once with a TwoTensor, then with a plain tensor. We expect dynamo guards to fail and cause a recompile. However, running this errors with:
```
  File "/data/users/hirsheybar/b/pytorch/torch/_dynamo/eval_frame.py", line 452, in _fn
    return fn(*args, **kwargs)
  File "<string>", line 10, in guard
AttributeError: 'Tensor' object has no attribute 'a'
```

cc @ezyang @msaroufim @albanD @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by bdhirsh** [comment]
We likely just need to add an `isinstance(x, TwoTensor)` guard. Since today, we generate additional TENSOR_CHECK guards on the inner tensors of `x`, but we need to know that x is ctually a subclass first.

**Comment by bdhirsh** [comment]
This is enough to fix it for me - although I'm not sure whether guarding on the type-id of the subclass is ok:
```
diff --git a/torch/_dynamo/guards.py b/torch/_dynamo/guards.py
index 4415d6e40a9..226cca8216f 100644
--- a/torch/_dynamo/guards.py
+++ b/torch/_dynamo/guards.py
@@ -29,6 +29,7 @@ except ModuleNotFoundError:
 import torch
 import torch.utils._device
+from torch.utils._python_dispatch import is_traceable_wrapper_subclass
 from torch._dynamo.source import (
     is_from_local_source,
     TensorProperty,
@@ -749,6 +750,11 @@ class GuardBuilder(GuardBuilderBase):
             static, reason = tensor_always_has_static_shape(
                 value, is_tensor=True, guard_source=guard.source
             )
+            type_id = id(type(value))
+            if is_traceable_wrapper_subclass(value):
+                 code.append(
+                     f"(id(type({tensor_name})) == {type_id})"
+                 )
             if not static:
                 if hasattr(value, "_dynamo_dynamic_indices"):
                     code.append(
```

**Comment by yanboliang** [comment]
@bdhirsh I'm looking at this issue today, it seems you are adding type_match guards on tensor subclasses, but how about the attribute of the tensor subclass object? I think you skipped the guards of ```L['w'].a``` and ```L['w'].b``` in the example, I think it would cause correctness issue.

**Comment by yanboliang** [comment]
This is the guards with your fix:
```
[2024-02-02 12:54:41,611] [0/1] torch._dynamo.guards.__guards: [DEBUG] GUARDS:
[2024-02-02 12:54:41,611] [0/1] torch._dynamo.guards.__guards: [DEBUG] hasattr(L['w'], '_dynamo_dynamic_indices') == False           # return torch.add(w, 1.0)  # ata/users/ybliang/pytorch/test/dynamo/test_functions.py:1608 in fn
[2024-02-02 12:54:41,611] [0/1] torch._dynamo.guards.__guards: [DEBUG] utils_device.CURRENT_DEVICE == None                           # _dynamo/output_graph.py:388 in init_ambient_guards
[2024-02-02 12:54:41,612] [0/1] torch._dynamo.guards.__guards: [DEBUG] ___check_current_backend(139659830503568)                     # _dynamo/output_graph.py:394 in init_ambient_guards
[2024-02-02 12:54:41,612] [0/1] torch._dynamo.guards.__guards: [DEBUG] check_tensor(L['w'], Tensor, DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), torch.float32, device=None, requires_grad=False, size=[2, 2], stride=[2, 1])  # return torch.add(w, 1.0)  # ata/users/ybliang/pytorch/test/dynamo/test_functions.py:1608 in fn

```

**Comment by anijain2305** [comment]
> This is enough to fix it for me - although I'm not sure whether guarding on the type-id of the subclass is ok:
> 
> ```
> diff --git a/torch/_dynamo/guards.py b/torch/_dynamo/guards.py
> index 4415d6e40a9..226cca8216f 100644
> --- a/torch/_dynamo/guards.py
> +++ b/torch/_dynamo/guards.py
> @@ -29,6 +29,7 @@ except ModuleNotFoundError:
>  import torch
>  import torch.utils._device
> +from torch.utils._python_dispatch import is_traceable_wrapper_subclass
>  from torch._dynamo.source import (
>      is_from_local_source,
>      TensorProperty,
> @@ -749,6 +750,11 @@ class GuardBuilder(GuardBuilderBase):
>              static, reason = tensor_always_has_static_shape(
>                  value, is_tensor=True, guard_source=guard.source
>              )
> +            type_id = id(type(value))
> +            if is_traceable_wrapper_subclass(value):
> +                 code.append(
> +                     f"(id(type({tensor_name})) == {type_id})"
> +                 )
>              if not static:
>                  if hasattr(value, "_dynamo_dynamic_indices"):
>                      code.append(
> ```

Talked offline with @Yanbo. TYPE_MATCH is right. This is conceptually what we want (proper place to put it is somewhere else). We should also skip the TENSOR_MATCH guard for the TwoTensor otherwise we will always recompile.

**Comment by yanboliang** [comment]
#119110 should fix this.
