### ISSUE TITLE
torch._dynamo.exc.TorchRuntimeError: Failed running call_function of torch.sparse_coo_tensor

### ISSUE THREAD

**Issue by CaoE** [pytorch/pytorch#118856]
### 🐛 Describe the bug

The failure is found by PR of https://github.com/pytorch/pytorch/pull/109994.  
Test case: https://github.com/pytorch/pytorch/actions/runs/7735116136/job/21090675760?pr=109994
Dynamo fails in the test case in test_torch.py even using simple code as bellow:
`torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method sparse_coo_tensor of type object at 0x7f105afdb9a0>(*(FakeTensor(..., size=(2, 3), dtype=torch.int64), FakeTensor(..., size=(3,)), (2, 3)), **{'device': 'cpu', 'dtype': torch.float32}): The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory`

```
@onlyNativeDeviceTypes
@dtypes(torch.float)
def test_grad_scaling_unscale_sparse(self, device, dtype):
    device = torch.device(device)
    i = torch.tensor([[0, 1, 1],
                      [2, 0, 2]], device=device, dtype=torch.int64)
    v = torch.tensor([16., 32., 64.], device=device, dtype=torch.float)
    s = torch.sparse_coo_tensor(i, v, torch.Size([2, 3]), device=device, dtype=dtype)
```

While move the codes from the test case, it can be successfully executed.
```
import torch
def compile_test():
    device = torch.device("cpu")
    i = torch.tensor([[0, 1, 1],
                        [2, 0, 2]], device=device, dtype=torch.int64)
    v = torch.tensor([16., 32., 64.], device=device, dtype=torch.float)
    s = torch.sparse_coo_tensor(i, v, torch.Size([2, 3]), device=device, dtype=torch.float)

my_fn = torch.torch._dynamo.optimize("eager", nopython=False)(compile_test)

my_fn()
```

### Versions

PyTorch version: 2.3.0a0+giteba4bd6
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 8.5.2111 (x86_64)
GCC version: (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
Clang version: 16.0.0 (Red Hat 16.0.0-2.module_el8+405+25122a8c)
CMake version: version 3.21.4
Libc version: glibc-2.28

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.16.0-rc1-intel-next-00543-g5867b0a2a125-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] flake8==3.8.2
[pip3] flake8-bugbear==20.1.4
[pip3] flake8-coding==1.3.3
[pip3] flake8-comprehensions==3.3.0
[pip3] flake8-executable==2.0.4
[pip3] flake8-pyi==20.5.0
[pip3] intel-extension-for-pytorch==2.3.0+gitf441a35
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.22.4
[pip3] onnx==1.14.1
[pip3] onnxruntime==1.15.1
[pip3] onnxscript==0.1.0.dev20230830
[pip3] torch==2.3.0a0+git249411e
[pip3] torchmultimodal==0.1.0b0
[pip3] torchvision==0.18.0a0+315f315
[pip3] triton==2.1.0
[conda] intel-extension-for-pytorch 2.3.0+gitf441a35           dev_0    <develop>
[conda] mkl-include               2023.1.0                 pypi_0    pypi
[conda] mkl-static                2023.1.0                 pypi_0    pypi
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     2.3.0a0+git249411e           dev_0    <develop>
[conda] torchmultimodal           0.1.0b0                   dev_0    <develop>
[conda] torchvision               0.18.0a0+315f315           dev_0    <develop>
[conda] triton                    2.1.0                    pypi_0    pypi

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by IvanKobzarev** [comment]
Doing issue scrapping, original repro passes, closing.
