### ISSUE TITLE
macOS runners

### ISSUE THREAD

**Issue by johnnynunez** [pytorch/pytorch#118864]
### 🚀 The feature, motivation and pitch

![image](https://github.com/pytorch/pytorch/assets/22727137/c2cb4d92-dab5-45d8-839c-7cade2b9be42)
new macos arm runner with github actions

cc @seemethere @malfet @pytorch/pytorch-dev-infra @albanD

**Comment by seemethere** [comment]
Hey @johnnynunez! We actually do already utilize Apple Silicon runners while testing things for PyTorch and also utilize Github's hosted runners to do this as well.

Thanks for the interest here!
