### ISSUE TITLE
CUDA 9.1 is not compatible with std::tuple from GCC version >= 6.

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#11886]
Any work around?
The video card on my laptop is GTX980M, which seems ONLY supported by Cuda9.1 ... I cannot upgrade to Cuda 9.2 .

1. However, when I tried 
```
python setup.py build
```

I got the following ERROR messages:

> CMake Error at cmake/public/cuda.cmake:313 (message):
>   CUDA 9.1 is not compatible with std::tuple from GCC version >= 6.  Please
>   upgrade to CUDA 9.2 or use the following option to use another version (for
>   example):
> 
>     -DCUDA_HOST_COMPILER=/usr/bin/gcc-5

```


2. Then, I tried

```
$ python setup.py build -DCUDA_HOST_COMPILER=/usr/bin/gcc-5
```

and got the following ERROR messages:

> WARNING: MKL-DNN is not compiled with Intel MKL small library
> Convolution performance might be suboptimal
> Refer https://github.com/01org/mkl-dnn for detail info
> Building wheel torch-1.0.0a0+e80d1d2
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 
> error: option -D not recognized



What can I do???


Cheers

**Comment by peterjc123** [comment]
Would you please try `export CUDA_HOST_COMPILER='/usr/bin/gcc-5'` and then `python setup.py build`? (After https://github.com/pytorch/pytorch/pull/11880 is merged, we should use `export CUDAHOSTCXX='/usr/bin/gcc-5' instead.`)

**Comment by SsnL** [comment]
@peterjc123  :) Could you update the above message too in #11880?

**Comment by sclarkson** [comment]
Driver 396.54 and 410.57 both support the GTX980M and support CUDA 9.2

**Comment by jiapei100** [comment]
@sclarkson 

Using Driver 410.57 and Cuda 10.0 now... Everything seems to work fine... Thank you ...

**Comment by yinxiaochuan** [comment]
Please update the warning signal. In the current version (1.1), it still outputs the CUDA_HOST_COMPILER=/usr/bin/gcc-5.

**Comment by peterjc123** [comment]
Okay, I'm on this.

**Comment by liubamboo** [comment]
I have the same bug. Anybody can help? 
I run command below:
git clone --recursive -b v1.0.1 https://github.com/pytorch/pytorch
cd pytorch && mkdir build && cd build
python ../tools/build_libtorch.py

And a bug appears:
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "7.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found CUDNN: /usr/local/cuda/include  
-- Found cuDNN: v7.5.1  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so.7)
CMake Error at cmake/public/cuda.cmake:330 (message):
  CUDA 9.0 is not compatible with std::tuple from GCC version >= 6.  Please
  upgrade to CUDA 9.2 or use the following option to use another version (for
  example):

    -DCUDA_HOST_COMPILER=/usr/bin/gcc-5

Call Stack (most recent call first):
  cmake/Dependencies.cmake:656 (include)
  CMakeLists.txt:201 (include)


-- Configuring incomplete, errors occurred!
See also "/home/n609/install/libtorch/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/n609/install/libtorch/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "../tools/build_libtorch.py", line 30, in <module>
    subprocess.check_call(command, universal_newlines=True, env=my_env)
  File "/home/n609/install/Anaconda/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/n609/install/libtorch/pytorch/tools/build_pytorch_libs.sh', '--use-cuda', '--use-nnpack', '--use-mkldnn', '--use-qnnpack', 'caffe2']' returned non-zero exit status 1.
(base) n609@n609-MS-7885:~/install/libtorch/pytorch/build$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

my environment is ubuntu 18, cuda 9.0, gcc 5.5.

**Comment by peterjc123** [comment]
@liubamboo What do you mean? The warning itself is real and I think it's pretty self-explanatory.
```
CMake Error at cmake/public/cuda.cmake:330 (message):
CUDA 9.0 is not compatible with std::tuple from GCC version >= 6. Please
upgrade to CUDA 9.2 or set the following environment variable to use another version (for example):
export CUDAHOSTCXX='/usr/bin/gcc-5
```
