### ISSUE TITLE
Make sure RAdam + Adamax are well tested in dynamo/test_optimizers.py 

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#118885]
### 🐛 Describe the bug

We've recently enabled Adamax/RAdam foreach-only compilation (see #117912), but that PR forgot to enable the RAdam tests `in dynamo/test_optimizers.py`. And currently, due to Adamax only supporting `foreach` when compiling, the single tensor Adamax does not pass the test.

We should:
1. Clarify what dynamo/test_optimizers.py should be testing. If it is supposed to test that running dynamo over our optimizers should be equivalent functionally to eager, we should rewrite the test to assert equality in params after a step. If we're simply trying to not error while tracing, then that is a different goal.
2. Make sure everything that should be tested is tested. If we are making sure that tracing doesn't error on optimizers, this should work for all configs of all optimizers. We should improve coverage to meet this.
3. If improving coverage yields test failures, we should fix them/track them in issues.

### Versions

on main

cc @vincentqb @jbschlosser @albanD @crcrpar @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @mlazos

**Comment by mlazos** [comment]
Yeah I think I'll just remove these tests, test_compiled_optimizers.py handles all of the testing that we need.

**Comment by janeyx99** [comment]
We've discussed a bit offline. We should still have tests that makes sure that every config (even when disabled in dynamo) will not error when torch.compile()'d. e.g., tracing our current core optimizer configs should not fail (though it doesn't have to be fullgraph capturable). Examples of this would be SparseAdam, single tensor RAdam today, etc.

These tests don't have to live in the same form as these dynamo tests but should exist somewhere.

**Comment by mlazos** [comment]
I removed these in https://github.com/pytorch/pytorch/pull/120257, with the additional tests added in https://github.com/pytorch/pytorch/pull/118919 we're good now.
