### ISSUE TITLE
torch.tensors in torch.multiprocessing

### ISSUE THREAD

**Issue by TomasVaskevicius** [pytorch/pytorch#11899]
## Issue description
The following code involving torch.multiprocessing.Pool does not work for torch.tensor
data type, while works for python numbers.

## Code example
```
import torch
import torch.multiprocessing as mp

def worker(arg):
    return [torch.tensor(1) for i in range(100)]

if __name__ == "__main__":
    pool = mp.Pool(1)
    out = pool.map(worker, [() for i in range(10)])
    pool.close()
    pool.join()
```

The above code can yields:
```
OSError: [Errno 24] Too many open files
```
which is strange, since we are launching only 10 jobs using one process at a time.

Changing the worker function to:
```
def worker(arg):
    return [1 for i in range(100)]
```
executes correctly.

## System Info
Ubuntu 16.04.01 LTS
Python version: 3.6
[conda] pytorch                   0.4.0            py36hd73e86b_0    anaconda

```
$ ulimit -n
1024
```

**Comment by weiyangfb** [comment]
Have you tried the solution of this similar issue: https://github.com/pytorch/pytorch/issues/11201

**Comment by TomasVaskevicius** [comment]
Thank you, changing sharing strategy to file system worked!
