### ISSUE TITLE
getting an error while using dataloder for making batches in cnn

### ISSUE THREAD

**Issue by adityak2920** [pytorch/pytorch#11892]
CODE where error is and xtrain and ytrain are numpy array before this and cnns and other code is working fine
![screen shot 2018-09-20 at 8 59 22 pm](https://user-images.githubusercontent.com/35501699/45829923-98314d00-bd19-11e8-84c8-c79bf62a036b.png)

error for the code before this so if anyone can help please

![screen shot 2018-09-20 at 9 00 02 pm](https://user-images.githubusercontent.com/35501699/45830062-ee05f500-bd19-11e8-8b4f-e9a9e0a0af47.png)

**Comment by SsnL** [comment]
You are using dataloader very wrongly. You need a `Dataset` object. Read the [docs](https://pytorch.org/docs/stable/data.html) or see some [examples](https://pytorch.org/tutorials/).
