### ISSUE TITLE
Why use reflection in nn.Module?

### ISSUE THREAD

**Issue by Yugnaynehc** [pytorch/pytorch#1189]
Hello everyone! When I read the source code of Pytorch in [module.py](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L260), I have a simple question :
why use 
`
modules = self.__dict__.get('_modules')
`
rather than
`
modules = self._modules 
`

What is the reason to make this choice? Thank you very much!

**Comment by apaszke** [comment]
Because getattr is called when objects are copied/deserialized and _modules might not have been set yet.

**Comment by apaszke** [comment]
You can try changing that and a couple of tests will start failing

**Comment by Yugnaynehc** [comment]
@apaszke got it! Thanks a lot!
