### ISSUE TITLE
'Output size is too small' 

### ISSUE THREAD

**Issue by VigneshSrinivasan10** [pytorch/pytorch#1190]
Hi, 

Newbie to pytorch here! I am using the code form `examples/imagenet` using `inception_v3` model, 

        python inception_torch.py -a inception_v3 -b 1

I am getting this error message: 

        RuntimeError: 'Given input size: (128 x 3 x 3). Calculated output size: (768 x -1 x -1). Output size is too small at /py/conda-bld/pytorch_1490977962696/work/torch/lib/THCUNN/generic/SpatialConvolutionMM.cu:47'

Did not notice this error with `vgg16` model. 

Any directions on to solve it will be very helpful. 
Thanks in advance!

**Comment by fmassa** [comment]
This question is better suited for https://discuss.pytorch.org/
Just for information, Inception expects [`299x299` images](https://github.com/pytorch/vision/blob/master/torchvision/models/inception.py#L76), while all other models expect `224x224`.
