### ISSUE TITLE
[feature request] ability to nest ParameterList

### ISSUE THREAD

**Issue by CharlesJQuarra** [pytorch/pytorch#11901]
In some cases, it is more convenient to arrange some parameters as 2d or 3d arrays rather than 1D list. One could solve it by computing a Nd to 1D offset array, but this could be avoided if the `nn.ParameterList` objects could be nested

Example:

```
class someModule(nn.Module):
  def __init__(self, x, y):
     params = []
     for ix in range(x):
       param_row = []
       for iy in range(y):
         param_row.append( nn.Parameter(torch.randn(1)))
       params.append( nn.ParameterList(param_row))
    param_array = nn.ParameterList(params)
```

**Comment by miguelvr** [comment]
I really don't see how this can be useful... Can you give an example?

**Comment by CharlesJQuarra** [comment]
you can get normal nested lists by putting a bunch of ParameterLists into a ModuleList

**Comment by USTClj** [comment]
@CharlesJQuarra Hi, have you figured it out? I want to use 2-D Modulelist, can we do it like this:

In the __inin__() of a module class, I want to pack and register some conv layers like this:

```
self.outs = nn.ModuleList(
            [nn.ModuleList([Conv(inp_dim + j * increase, oup_dim, 1, relu=False, bn=False) for j in range(5)]) for i in
             range(nstack)])
```
then in the forward() method, I want to use the conv layers in the nested module list.
`preds_instack.append(self.outs[i][j](features_instack[j]))`
