### ISSUE TITLE
Please rename package pytorch to stay consistent with entire python world

### ISSUE THREAD

**Issue by radiantone** [pytorch/pytorch#11907]
Hi,
 Like many, I installed pytorch, which says it is installing the package 'pytorch' and yet it is called 'torch' when you attempt to import it from python.

This cuts against the standard practices of the entire python world. Please remedy.

thanks!

**Comment by Evpok** [comment]
While I agree with the principle, pytorch is by no mean the only offender (scikit-learn come to mind) and that kind of changes would break a lot of code.
Then again, maybe such breakage would be manageable within the context of 1.0 migration.

**Comment by radiantone** [comment]
Yes. Scikit with it's annoying and unnecessary hyphens is also an issue.

**Comment by soumith** [comment]
in `pypi`, which is the standard practice in the python world, we call it `torch` (`pip install torch`), but in `conda`, which is a multi-language repo, we call it `pytorch`.

It's unlikely that we will change this.
