### ISSUE TITLE
`sdpa_kernel` context manager has wrong annotation and input sanitizing

### ISSUE THREAD

**Issue by tringwald** [pytorch/pytorch#119133]
### 🐛 Describe the bug

`sdpa_kernel` context manager's `backend` param has type annotation `List[SDPBackend]` while the doc string says `Union[List[SDPBackend], SDPBackend]`. 
The assert would also allow `None` which conflicts with the type hint, but does not allow a single `SDPBackend` which conflicts with the assertion warning text and the doc string.
As `None` can pass the assertion, `set(None)` would then throw an error, as `None` is not iterable.

https://github.com/pytorch/pytorch/blob/ffae20e5941dcae505b21fa3a7370ac01371df0c/torch/nn/attention/__init__.py#L59-L76

### Versions

main

cc @svekars @brycebortree

**Comment by ajbrent** [comment]
Cool if I take a swing at this?

**Comment by tringwald** [comment]
> Cool if I take a swing at this?

Sure! Let me know if you need any help in case this is your first contribution.
