### ISSUE TITLE
[feature request] Implement __cuda_array_interface__ for numba compatibility.

### ISSUE THREAD

**Issue by asford** [pytorch/pytorch#11914]
## Issue description

`numba` provides generic support for jit-optimized operations over tensor data structures, with support for cpu and cuda based operations. This is an _ideal_ match for accelerating pytorch operations. Numba has proposed a standardized ["`__cuda_array_interface__`"](http://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html), inspired by the numpy [`__array_interface__`](https://docs.scipy.org/doc/numpy/reference/arrays.interface.html) standard, to provide interop between cuda-based tensors.

Implementation of this standard would dramatically ease PyTorch/Numba integration. This can be enabled via a monkey-patch of the current `torch.Tensor` type, however PyTorch should provide an implementation.

## Code example

```python
import torch


def torch_cuda_array_interface(tensor):
    """__cuda_array_interface__ getter implementation for torch.Tensor."""

    if not tensor.device.type == "cuda":
        # raise AttributeError for non-cuda tensors, so that
        # hasattr(cpu_tensor, "__cuda_array_interface__") is False.
        raise AttributeError("Tensor is not on cuda device: %r" % tensor.device)

    if tensor.requires_grad:
        # RuntimeError, matching existing tensor.__array__() behavior.
        raise RuntimeError(
            "Can't get __cuda_array_interface__ on Variable that requires grad. "
            "Use var.detach().__cuda_array_interface__ instead."
        )

    typestr = {
        torch.float16: "f2",
        torch.float32: "f4",
        torch.float64: "f8",
        torch.uint8: "u1",
        torch.int8: "i1",
        torch.int16: "i2",
        torch.int32: "i4",
        torch.int64: "i8",
    }[tensor.dtype]

    itemsize = tensor.storage().element_size()

    shape = tensor.shape
    strides = tuple(s * itemsize for s in tensor.stride())
    data = (tensor.data_ptr(), False)

    return dict(typestr=typestr, shape=shape, strides=strides, data=data, version=0)


torch.Tensor.__cuda_array_interface__ = property(torch_cuda_array_interface)
```

**Comment by ezyang** [comment]
Seems like a reasonable thing to do. CC me if you submit a patch.

**Comment by dandelin** [comment]
I've been using numba's cuda_array_interface to implement c++-free ROI align function. (https://github.com/dandelin/Wildfire/blob/master/wildfire/optimized_ops/roi_align/roi_align.py) AND it works great for me.

The code was adapted from this issue's snippet (https://github.com/numba/numba/issues/3192).

`cuda.select_device(tensor.get_device())`
I just added this single line of code to make it work on multiple GPUs. (since tensor.data_ptr() used in cuda_array_interface dict dose not provide which device it's pointing.)

**Comment by asford** [comment]
@t-vi This interface is used by numba to create a pointer of the underlying data along with a a python-level reference to the owning object (the `torch.Tensor` in this case). Please correct me if I'm mistaken, but this should properly handle ownership/lifetime.

**Comment by asford** [comment]
@dandelin 

I've found that the easiest way to handle multi-device scenarios is to use device context managers to ensure numba operations are dispatched onto the proper device. The cuda api is used to resolve a valid pointer on the current device for the data pointer, which will raise an API error if there's an invalid cross-device reference.

Eg:

```python
import pytest
import numba
import torch

def test_multi_device_interconversion():
    # Both torch/numba default to device 0 and can interop freely
    cudat = torch.arange(10, device="cuda")
    assert cudat.device.index == 0
    assert numba.as_cuda_array(cudat)

    # Tensors on non-default device raise api error if converted
    cudat = torch.arange(10, device=torch.device("cuda", 1))
    with pytest.raises(numba.cuda.driver.CudaAPIError):
        numba.as_cuda_array(cudat)

    # but can be converted when switching to the device's context
    with numba.cuda.devices.gpus[cudat.device.index]:
        assert numba.as_cuda_array(cudat)
```

**Comment by ezyang** [comment]
This is landed.
