### ISSUE TITLE
[dynamo] Support __iter__ on customized object

### ISSUE THREAD

**Issue by ydwu4** [pytorch/pytorch#119198]
### 🚀 The feature, motivation and pitch

For code like the following:
```python
import torch
class Mod():
    def __init__(self):
        self.a = [torch.randn(2, 2), torch.randn(2, 2)]
    def __iter__(self):
        return iter(self.a)

def f():
    mod = Mod()
    ret = []
    for x in mod:
        ret.append(x + 1)
    return ret

torch.compile(f, backend="eager", fullgraph=True, dynamic=True)()
```
We currently have a graph break like this:
```
torch._dynamo.exc.Unsupported: call_function BuiltinVariable(iter) [UserDefinedObjectVariable(Mod)] {}
```
It would be great if we could remove the graph break.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by eellison** [comment]
cc @anijain2305 potentail `dynamo-must-fix` ?

**Comment by ezyang** [comment]
Customized iteration also affects torchrec library.
