### ISSUE TITLE
[inductor][cpu]tnt_s_patch16_224 and functorch_dp_cifar10 fP32 static default wrapper performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#119178]
### 🐛 Describe the bug

This issue is separated from https://github.com/pytorch/pytorch/issues/104952, verified with TORCHINDUCTOR_FREEZING=0

</table><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>tnt_s_patch16_224</td>
      <td>1</td>
      <td>1.173545</td>
      <td>0.094649226</td>
      <td>0.111075126</td>
      <td>1</td>
      <td>1.367958</td>
      <td>0.081854891</td>
      <td>0.111974053</td>
      <td>0.86</td>
      <td>1.01</td>
    </tr>
    <tr>
      <td>functorch_dp_cifar10</td>
      <td>64</td>
      <td>0.622732</td>
      <td>0.009190167</td>
      <td>0.005723011</td>
      <td>64</td>
      <td>1.008348</td>
      <td>0.005596095</td>
      <td>0.005642811</td>
      <td>0.62</td>
      <td>0.99</td>
    </tr>
</tbody>

</table>

The good  results come from 2023-07-06 nightly: https://github.com/pytorch/pytorch/commit/13763f58ad86fadf49ef7960d1836318e6480d36
The bad results come from 2024-01-29 nightly: https://github.com/pytorch/pytorch/commit/890d8e66925ff7bb1b765087ad921ebc1bdebf48

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>890d8e6</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ff42d907</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>b2d9c3e</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>315f315</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0790338</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
tnt_s_patch16_224: bash inductor_single_run.sh single inference performance timm_models tnt_s_patch16_224 float32 first static default 0 off
functorch_dp_cifar10: bash inductor_single_run.sh multiple inference performance torchbench functorch_dp_cifar10 float32 first static default 0 off
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/7e098f95593240d45d28f040ff53f268ad3d9a93
[timm_models-tnt_s_patch16_224-inference-float32-static-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/14162640/timm_models-tnt_s_patch16_224-inference-float32-static-default-performance-single-drop_guilty_commit.log)
cc @WeizhuoZhang-intel @chuanqi129

**Comment by jgong5** [comment]
I'm not sure if this was caused by the fact that https://github.com/pytorch/pytorch/pull/102486/files#diff-e384e0d2829ef483854a45c4f422979d1a2ca28495c7bc06e91eabc67c61a470R101 only added avx2 intrinsics but not avx512. The test ran with avx512, right?

**Comment by peterbell10** [comment]
That sounds plausible but I don't have a system with avx512 to test on.

**Comment by jgong5** [comment]
> That sounds plausible but I don't have a system with avx512 to test on.

I also asked @jiayisunx to take a look.

**Comment by leslie-fang-intel** [comment]
@CaoE has a PR to enable AVX512 path.

**Comment by CaoE** [comment]
https://github.com/pytorch/pytorch/pull/125147

**Comment by leslie-fang-intel** [comment]
@zxd1997066 please help to confirm the fix.

**Comment by zxd1997066** [comment]
The regression is fixed in latest report.
