### ISSUE TITLE
No module named 'caffe2' when using `add_scalar` with string

### ISSUE THREAD

**Issue by vincentqb** [pytorch/pytorch#119195]
### 🐛 Describe the bug

When invoking `add_scalar` with a string, an error similar to https://github.com/pytorch/pytorch/issues/24175 occurs. Since one most likely should use `add_text` instead, an error message suggesting this may be easier to debug.

```python
In [1]: from torch.utils.tensorboard import SummaryWriter

In [2]: with SummaryWriter() as writer:
   ...:     writer.add_text("test0", "a")
   ...:     writer.add_scalar("test1", 0)
   ...:     writer.add_scalar("test2", "b")
   ...: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 4
      2 writer.add_text("test0", "a")
      3 writer.add_scalar("test1", 0)
----> 4 writer.add_scalar("test2", "b")

File /opt/homebrew/anaconda3/envs/torch/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py:389, in SummaryWriter.add_scalar(self, tag, scalar_value, global_step, walltime, new_style, double_precision)
    387 torch._C._log_api_usage_once("tensorboard.logging.add_scalar")
    388 if self._check_caffe2_blob(scalar_value):
--> 389     from caffe2.python import workspace
    391     scalar_value = workspace.FetchBlob(scalar_value)
    393 summary = scalar(
    394     tag, scalar_value, new_style=new_style, double_precision=double_precision
    395 )

ModuleNotFoundError: No module named 'caffe2'
```

### Versions

```
Collecting environment information...
PyTorch version: 2.2.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.3 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==2.2.0
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.2.0                    pypi_0    pypi
```

cc @robieta @chaekit @aaronenyeshi @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise @nbcsm @gaoteng-git @tiffzhaofb

**Comment by malfet** [comment]
That's a blast from the past. I don't think there is an active contributor to TensorBoard, but we would accept the patch to that fixes it (by not relying on caffe2 primitives in PyTorch)

**Comment by TamirCohen** [comment]
Do we need to support Caffe2 blobs? The TensorBoard documentation indicates that it is supported https://github.com/pytorch/pytorch/blob/1e4b408b025958fe581f0f1c3345c4a01ba2238c/docs/source/tensorboard.rst?plain=1#L11

It appears that the exception is raised because the following line https://github.com/pytorch/pytorch/blob/1e4b408b025958fe581f0f1c3345c4a01ba2238c/torch/utils/tensorboard/writer.py#L388 assumes that the string argument is related to Caffe2 blobs.

If we should no longer support it, I can remove the Caffe2 blobs logic. However, if we intend to support it, perhaps we can consider adding it as a dependency to PyTorch?
