### ISSUE TITLE
0-dim input tensor fails with `ArrayRef: invalid index Index` in `nn.Linear`

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#119161]
### 🐛 Describe the bug

Reported in the discussion board: https://discuss.pytorch.org/t/pytorch-arrayref-invalid-index-problem-with-linear-nn/196625
Reproduced in the nightly with a minimal code snippet:
```python
model = nn.Linear(1, 1)
x = torch.randn(1)

print(x.shape)
# torch.Size([1])

# works
out = model(x)
print(out.shape)
# torch.Size([1])

# fails
x = torch.randn(1).squeeze()
print(x.shape)
# torch.Size([])

out = model(x)
# RuntimeError: ArrayRef: invalid index Index = 18446744073709551615; Length = 0
```

### Versions

`torch==2.3.0.dev20240202+cu121`

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @malfet

**Comment by tringwald** [comment]
Seems to be related to the bias access, with `nn.Linear(1, 1, bias=False)`, I get the correct error:
```
RuntimeError: both arguments to matmul need to be at least 1D, but they are 0D and 2D
```
