### ISSUE TITLE
In `_scaled_mm`, `scale_result` not changing result tensor at all

### ISSUE THREAD

**Issue by snarayan21** [pytorch/pytorch#119135]
### 🐛 Describe the bug

Hi, I'm just trying out the new FP8 datatypes and I'm trying to multiply two `fp8_e4m3fn` matrices and scale the result using the `_scaled_mm` call. However, changing the `scale_result` argument does nothing to change the result. I expect the result to be multiplied by `scale_result`, and after reading through the implementations, I'm confused why this is not working. I'm running on H100s so this new datatype is supported. Would greatly appreciate help here, thanks!

Sample repro code:

```
x = torch.randn((16,16)).cuda().to(torch.float8_e4m3fn)
y = torch.randn((16,16)).cuda().to(torch.float8_e4m3fn)

z1, _ = torch._scaled_mm(x, y.t(), bias=None, out_dtype=torch.bfloat16,
    scale_a=torch.tensor([1.0]).cuda(),
    scale_b=torch.tensor([1.0]).cuda(),
    scale_result=torch.tensor([1.0]).cuda())

z2, _ = torch._scaled_mm(x, y.t(), bias=None, out_dtype=torch.bfloat16,
    scale_a=torch.tensor([1.0]).cuda(),
    scale_b=torch.tensor([1.0]).cuda(),
    scale_result=torch.tensor([40.0]).cuda()) # scaling up result 40x

assert torch.equal(z1, z2) # This runs without error since z1 and z2 are equal, when they should not be.
```

### Versions

```
[pip3] numpy==1.24.1
[pip3] onnx==1.14.0
[pip3] onnxruntime==1.15.1
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-triton==2.2.0+e28a256d71
[pip3] torch==2.3.0.dev20240110+cu121
[pip3] torch-optimizer==0.3.0
[pip3] torchmetrics==1.0.3
[pip3] torchvision==0.18.0.dev20240110+cu121
[pip3] triton==2.2.0
[pip3] triton_pre_mlir==2.0.0
[conda] Could not collect
```

cc @yanbing-j @vkuzo @albanD @kadeng

**Comment by tringwald** [comment]
This seems to be intended behavior. `_scaled_mm` only applies `scale_result` if the output tensor is of `float8` type.

**Comment by snarayan21** [comment]
@tringwald Sorry for the late response -- I'd want the `scale_result` to apply to the output regardless of the dtype. Is that possible?

Additionally, for better fp8 matmul support in general, I've also filed another somewhat related [issue](https://github.com/pytorch/pytorch/issues/123761).
