### ISSUE TITLE
Can torch use make_storage_impl to replace c10::make_intrusive<c10::StorageImpl>

### ISSUE THREAD

**Issue by CLiqing** [pytorch/pytorch#119146]
### 🚀 The feature, motivation and pitch

Same question to https://github.com/pytorch/pytorch/pull/118459 but api is ``new_qtensor``.
I'm thinking if we can use ``make_storage_impl`` to replace ``c10::make_intrusive<c10::StorageImpl>`` in everywhere?
Compare to ``c10::make_intrusive<c10::StorageImpl>``, ``make_storage_impl`` is more general and allows ``PrivateUse1`` backend to use its registered StorageImpl.

https://github.com/pytorch/pytorch/blob/bb6eba189f92790f278f1ee2840f3786da02acaa/torch/csrc/Storage.cpp#L315
https://github.com/pytorch/pytorch/blob/bb6eba189f92790f278f1ee2840f3786da02acaa/torch/csrc/Storage.cpp#L350-L356

So what about moving ``make_storage_impl`` to ``c10\core\StorageImpl.h`` and replace c10::make_intrusive<c10::StorageImpl> in relative apis?

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

**Comment by CLiqing** [comment]
@ezyang, same question to https://github.com/pytorch/pytorch/pull/118459, what do you think?

**Comment by ezyang** [comment]
They don't seem directly compatible so it doesn't seem like you'd be able to use it everywhere.
