### ISSUE TITLE
Pytorch failed to build with C2065 C1083 on windows with MSVC ARM64EC Target

### ISSUE THREAD

**Issue by spacelg** [pytorch/pytorch#119156]
### 🐛 Describe the bug

Environment:
VS 2022 + Windows Server 2022 Datacenter

Pytorch failed to build with C2065 C1083 on windows with MSVC ARM64EC Target. It can reproduce on latest commit on main branch. Could you please help look at this issue? Thanks in advance.

1. git clone https://github.com/pytorch/pytorch C:\gitP\pytorch\pytorch
2. git submodule update --init --recursive
3. Open a VS2022 x64 command && cd C:\gitP\pytorch\pytorch && mkdir build_amd64ec && cd build_amd64ec
4. pip3 install typing_extensions pyyaml
5. set _CL_=/Zc:lambda
6. cmake -G "Visual Studio 17 2022" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DUSE_CUDA=OFF ..
7. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release Torch.sln /t:Rebuild

Expected behavior:
Build pass.

Actual behavior:
Failed to build.

Error Message:
82>C:\gitP\pytorch\pytorch\third_party\cpuinfo\src\arm\windows\init-by-logical-sys-info.c(309,2): error C2065: 'cpuinfo_uarchs': undeclared identifier [C:\gitP\pytorch\pytorch\build_arm64ec\confu-deps\cpuinfo\cpuinfo_internals.vcxproj]
......
115>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'C:\gitP\pytorch\pytorch\build_arm64ec\CMakeFiles\efe7d47b1eda733aa21c220a64e5e359\torch.pb.cc.rule;C:\gitP\pytorch\pytorch\build_arm64ec\CMakeFiles\efe7d47b1eda733aa21c220a64e5e359\caffe2.pb.cc.rule;C:\gitP\pytorch\pytorch\caffe2\proto\CMakeLists.txt' exited with code -1073741819. [C:\gitP\pytorch\pytorch\build_arm64ec\caffe2\proto\Caffe2_PROTO.vcxproj]
......
103>C:\gitP\pytorch\pytorch\third_party\XNNPACK\src\f16-vbinary\gen\f16-vadd-minmax-fp16arith-u1.c(13,10): error C1083: Cannot open include file: 'arm_fp16.h': No such file or directory (C:\repos\msvc\src\vctools\Compiler\CxxFE\sl\p1\c\p0prepro.c:2002) [C:\gitP\pytorch\pytorch\build_arm64ec\confu-deps\XNNPACK\microkernels-all.vcxproj]
...

### Versions

[build_arm64ec.log](https://github.com/pytorch/pytorch/files/14159775/build_arm64ec.log)

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by alinpahontu2912** [comment]
Hey @spacelg, what is the status of this issue ? Did you also run **git submodule sync** and installed the requirements from **requriements.txt** file ? Also, currently there is no official support for PyTorch for Windows on Arm.

**Comment by alinpahontu2912** [comment]
Hey @spacelg, we are currently working on building pytorch for windows on arm. I am closing this issue and advise you to keep looking at this one: https://github.com/pytorch/pytorch/issues/106956 to receive updates.
