### ISSUE TITLE
Dynamo does not support user-defined objects that define custom __new__

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119203]
### 🐛 Describe the bug

```
import torch            
import abc          
                
class A:        
    def __new__(cls, x):
        y = super().__new__(cls)
        y.y = 2 
        return y
    def __init__(self, x):
        self.x = x  
                    
@torch.compile(backend="eager")
def f(y, z):
    a = A(y)
    return a.x + a.y
        
f(torch.randn(4), torch.randn(4))
```

We are not sure if this actually matters or not but this came up with @IvanKobzarev when trying to minimize an actual torchrec problem.

### Versions

main

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @anijain2305 @msaroufim @bdhirsh @zou3519 @aakhundov

**Comment by ezyang** [comment]
This is related to having Dynamo implement the full accurate Python model see https://docs.google.com/document/d/1Kz02jiA45dGPDBnY9Xd3Z5S864evbMv75E_CZPOehJU/edit#heading=h.jwgb4cgkl2bi

**Comment by anijain2305** [comment]
I have seen this graph break for a couple of user empathy day models and also vLLM (though vLLM case is a metaclass, so might be more complicated). Fixing this graph break should help many models. 

Assigning to me for now.
