### ISSUE TITLE
Failed to torch.save in a jupyter notebook

### ISSUE THREAD

**Issue by robbine** [pytorch/pytorch#11922]
This problem occurs after several epochs of training. At the end of each epoch I used torch.save to persist a model.  I checked disk capacity, it shouldn't be a problem. 
Here is the code snippet which probably caused the jupyter kernel dead.
`        if self._serialization_dir is not None:
            model_path = os.path.join(self._serialization_dir, "model_state_epoch_{}.th".format(epoch))
            model_state = self._model.state_dict()
            torch.save(model_state, model_path) # **This line caused the kernel died**.
`
Here I listed all the models and I find that size of 'model_state_epoch_7.th' is only 12K which is much smaller compared with previous models.
-rw-r--r-- 1 root root  45M Sep 20 18:46 model_state_epoch_4.th
-rw-r--r-- 1 root root  45M Sep 20 18:58 model_state_epoch_5.th
-rw-r--r-- 1 root root  45M Sep 20 19:11 model_state_epoch_6.th
-rw-r--r-- 1 root root  12K Sep 21 10:28 model_state_epoch_7.th
I tried to remove the last corrupted model file and recover training. It fails at the same point again and again.
Any ideas ?

**Comment by robbine** [comment]
I tried to remove the last corrupted model file and recover training. It fails at the same point again and again.

**Comment by robbine** [comment]
I tried to run on my macbook and everything seems OK.  It's was slow, using gpu the speed is boosted by almost 15x times faster, but they only provide notebook for me to access their gpu resources.

**Comment by t-vi** [comment]
I would expect something on stdout/stderr which Jupyter indeed swallows.
You could try redirecting stdout and stderr to a file using this: https://stackoverflow.com/a/41301870

**Comment by zou3519** [comment]
Please try @t-vi's suggestion!
