### ISSUE TITLE
meta device model .to(cuda) should give an error suggesting .to_empty

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#119293]
meta initialization would logically follow a flow like 

```
with device('meta')
 m = Model()

...

m.to(real_device)
```

This fails with `NotImplementedError: Cannot copy out of meta tensor; no data!` which sounds pretty discouraging (user is on the wrong track using meta in this way).

However, if we are able to suggest using `.to_empty()` api in this error, it would help steer people to the working path.
cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @alband

**Comment by albanD** [comment]
Thanks for sharing this.
I do think that we can indeed detect that this particular error is being raised in `Module.to()` and suggest the user should use `.to_empty()` instead to materialize into un-initialized data.
