### ISSUE TITLE
Non-strict export does not support tolist: RuntimeError: .tolist() is not supported for tensor subclasses, got FunctionalTensor

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119210]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/894363187646754/posts/1863773624039034/

```
import torch.export
import torch.nn

class M(torch.nn.Module):
    def forward(self, x):
        a, b = x.tolist()
        return x + a + b

torch.export.export(M(), [torch.tensor([1.0, 2.0])], {}, strict=False)
```

Easy fix, just manually add a tolist implementation on FunctionalTensor.

### Versions

main

cc @bdhirsh @msaroufim @anijain2305 @zou3519 @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by abdelfattahmohand** [comment]
I'm a first timer, I want to work on this

**Comment by masnesral** [comment]
adding "triaged" since this is assigned

**Comment by zhxchen17** [comment]
@tugsbayasgalan do you still intend to work on this?
