### ISSUE TITLE
Remove `coordinator_rank` from public fns in distributed checkpointing, e.g. `load`

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#119205]
### 🚀 The feature, motivation and pitch

The coordinator_rank argument from public functions (eg distributed save/load calls) should be removed and Torch should pull the first rank from the specified process group (or the default process group if none is specified). This simplifies the user process and avoids confusing deadlock errors.

I'm not sure there's any reason a user cares about this implementation detail (though I may be missing a scenario), and it's a bit confusing to specify along with process group.

From: https://github.com/pytorch/pytorch/issues/118337. Moved to new issue as requested by @wconstab 

@LucasLLC @fegin @wz337 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by LucasLLC** [comment]
Thanks for the suggestion @mvpatel2000 , we're taking this into consideration and will respond with more details asap.

**Comment by wz337** [comment]
> I agree with @mvpatel2000 . Since the `coordinator_rank` is only passed to `_Distwrapper`, and then also 'cast' to a bool for downstream calls, I think it has limited usability to begin with. Users which really need this level of granularity can probably pass it directly to a custom planner, as is being done here - https://github.com/pytorch/pytorch/pull/119335/files#diff-2a4c8fe2eb5bd4b61d5b5aa4d5e7b641be90c5b4d4b903d162da98e97b7fd986R93 .
> 
> Proposing we deprecate the parameter and include this issue in the PR in case there are scenarios we are missing.
> 
> Unless of course this is already a big use case. Tagging @wz337 and @fegin in case they are aware of such use cases.

I don't believe there is any big downstream use case so no objection for what @mvpatel2000 proposed.

**Comment by fegin** [comment]
I want to get rid of `coordinator_rank` as well. We have too many tuning options, which are not necessary for the end-users.

**Comment by LucasLLC** [comment]
Removed in https://github.com/pytorch/pytorch/pull/121317 :) Thanks @mvpatel2000 for the suggestion!

**Comment by fegin** [comment]
The issue is fixed. The old APIs are being deprecated so we don't change the API signatures. The new APIs don't have this argument after https://github.com/pytorch/pytorch/pull/121317.
