### ISSUE TITLE
“bucket.future_work->wait()” in reducer.cpp  can not  trigger  “(*ncclEndEvents_)[i].block(currentStream); ” in ProcessGroupNCCL.cpp，the current stream does not properly wait for a stream executing NCCL

### ISSUE THREAD

**Issue by taozhiwei** [pytorch/pytorch#119266]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L2565
```c++
for (const auto i : c10::irange(devices.size())) {
    at::cuda::CUDAStream& ncclStream = ncclStreams[i];
    if (!coalescing_state_) {
      (*work->ncclEndEvents_)[i].record(ncclStream);
    }
    work->ncclComms_[i] = ncclComms[i];
  }
```
https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/reducer.cpp#L1605
```c++
    bucket.future_work->wait();
    auto future_result = comm_hook_ == nullptr
```
https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/default_comm_hooks.cpp
```c++
c10::intrusive_ptr<c10::ivalue::Future> AllReduceCommHook::runHook(
    GradBucket& bucket) {
  std::vector<at::Tensor> tensors = {bucket.getBufferRef()};
  // Apply the division first to avoid overflow, especially for FP16.
  tensors[0] /= state_->getSize();
  return state_->allreduce(tensors)->getFuture();
}
```
“bucket.future_work->wait()”  can not  trigger  “(*ncclEndEvents_)[i].block(currentStream),the current stream does not properly wait for a stream executing NCCL. I guess due to the fast execution of NCCL, this error was not triggered.

In addition, then FP16CompressCommHook's then did not wait for allreduce to finish executing, so it immediately executed convert.

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by wanchaol** [comment]
Thanks for submitting the issue and the fixes!
