### ISSUE TITLE
Add a binding for Storage resizable

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119233]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/1405155842844877/posts/7973507386009657/

StorageImpl has this field

```
  bool resizable_;
```

but there is no way to access it from Python. Make it accessible under a method named resizable() for both TypedStorage and UntypedStorage.

### Versions

main

cc @albanD

**Comment by ezyang** [comment]
A unit test is potentially

```
import torch

x = torch.randn(5)
print(x.storage().resizable())  # True
x.numpy()
print(x.storage().resizable())  # False
```

**Comment by ezyang** [comment]
For extra credit, add logging when resizable flips from True to False. I'm not convinced we actually should do this, because TBH the original user code that had this problem is sus.

**Comment by hkmatsumoto** [comment]
Working on this to get my feet wet for contributing to PyTorch.

**Comment by hkmatsumoto** [comment]
Hi, I managed to get this binding working and want to write some test code, however, the potential unit test won't work because `ndarray` doesn't have the `storage()` method.
Can you teach me a way to create tensors with unresizable storage?

**Comment by ezyang** [comment]
oops, I typoed, example is fixed now
