### ISSUE TITLE
Tutorial for custom env with complex shapes

### ISSUE THREAD

**Issue by svnv-svsv-jm** [pytorch/pytorch#119278]
### 🚀 The feature, motivation and pitch

I am totally unable to create a `EnvBase` subclass, where the `*_spec` attribute have complex shapes.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by drisspg** [comment]
Can you add some more context I am not even sure what label to triage this with

**Comment by soulitzer** [comment]
Going to close this for now, feel free to reopen with more context

**Comment by svnv-svsv-jm** [comment]
Added a more specific quesiton. Let me know if it is more clear now. Whatever the answer may be, I believe this is not clear from the tutorials. If so, it'd be nice to add the explanation there. Otherwise, sorry for opening this.

**Comment by soulitzer** [comment]
Thanks for the additional context. The TorchRL repo https://github.com/pytorch/rl is probably a better place for this since these seem to be TorchRL concepts.

**Comment by svnv-svsv-jm** [comment]
Yes, you're right. Just realized I am in the wrong PyTorch repo! :) Going to manually move this there.
