### ISSUE TITLE
Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset is not supported

### ISSUE THREAD

**Issue by jose-rincon** [pytorch/pytorch#119232]
### 🐛 Describe the bug

While using the torch.onnx.export function, I encountered an issue exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 16. Despite trying opset versions 8 to 20, the problem persists.

I kindly seek your guidance on resolving this matter. Any insights or suggestions regarding the compatibility of this operator with different ONNX opset versions would be greatly appreciated.

Thank you for your time and assistance.

### Versions

PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.28.1
Libc version: glibc-2.31

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.10.0-26-cloud-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89

**Comment by thiagocrepaldi** [comment]
The aforementioned oeprators are not supproted by torch.onnx.export and we don't plan to support them


Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
