### ISSUE TITLE
Promote torch.tensor(scalar) behavior to torch.scalar_tensor(scalar).

### ISSUE THREAD

**Issue by zhxchen17** [pytorch/pytorch#119240]
### 🚀 The feature, motivation and pitch

Today if we export the following model which has a tensor(scalar) call:
```
class Top(torch.nn.Module):
    def forward(self, x):
        return x + torch.tensor(1)
```
the resulting graph looks like the following:
```
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, _lifted_tensor_constant0: "i64[]", l_x_: "i64[]"):
            lift_fresh_copy: "i64[]" = torch.ops.aten.lift_fresh_copy.default(_lifted_tensor_constant0);  _lifted_tensor_constant0 = None
            add: "i64[]" = torch.ops.aten.add.Tensor(l_x_, lift_fresh_copy);  l_x_ = lift_fresh_copy = None
            return (add,)
```
Ideally in export, we want to provide the invariant that exported program's state dict keys are identical to those from the exported eager module, i.e. no new buffers are introduced in export process. Hence currently we cannot do anything except rejecting any program containing torch.tensor in forward during export.

One option to deal with this would be making torch.tensor(scalar) somehow leverage on the existing torch.scalar_tensor() call, so that for scalars, we will capture the tensor constructor as the op `torch.ops.aten.scalar_tensor.default` and therefore we don't export a program with extra buffer attached instead.

I don't have a lot of knowledge about torch.tensor, so I'm not sure if this is something doable.

### Alternatives

Alternatively, export needs to ask people to rewrite every callsite of their torch.tensor(scalar) to torch.scalar_tensor() which is slightly annoying and confuses people because there isn't much difference at syntax level, and also because torch.tensor(scalar) is a more common and intuitive there than undocumented torch.scalar_tensor.

Another thing we can ask people to do is calling register_buffer on the torch.nn.Module, but I think it's not the most natural way to express the intent of inplace constructing a scalar tensor.

cc @avikchaudhuri @gmagogsfm @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by zhxchen17** [comment]
cc @suo

**Comment by suo** [comment]
> Ideally in export, we want to provide the invariant that exported program's state dict keys are identical to those from the exported eager module, i.e. no new buffers are introduced in export process. Hence currently we cannot do anything except rejecting any program containing torch.tensor in forward during export.

We don't reject this right now, right? We just preserve these as non-buffer constants and feed them in

**Comment by zhxchen17** [comment]
> > Ideally in export, we want to provide the invariant that exported program's state dict keys are identical to those from the exported eager module, i.e. no new buffers are introduced in export process. Hence currently we cannot do anything except rejecting any program containing torch.tensor in forward during export.
> 
> We don't reject this right now, right? We just preserve these as non-buffer constants and feed them in

yeah we don't reject them right now. I'm proposing to reject them, BUT it seems it's not practical at all. I can close this.
