### ISSUE TITLE
Indentation in new docs

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#11930]
## Issue description

Argument descriptions for various functions seem to be abnormally indented.

![image](https://user-images.githubusercontent.com/23639302/45868044-7039fc00-bda2-11e8-9ace-5bdb5547cd5e.png)
![image](https://user-images.githubusercontent.com/23639302/45868083-8942ad00-bda2-11e8-92c1-60121e3902d8.png)

More instances can be found here too: https://pytorch.org/docs/master/torch.html

Browser: Firefox 61.0.1 , Ubuntu 18.04

**Comment by OmegaNJU** [comment]
Emmm, I think old version docs is more recognizable than new docs. Just my personal opinion:)

**Comment by vishwakftw** [comment]
Closing in favour of https://github.com/pytorch/pytorch/issues/11968
