### ISSUE TITLE
Exposing MKL kernel using torch cpp extension

### ISSUE THREAD

**Issue by maktukmak** [pytorch/pytorch#119394]
### 🐛 Describe the bug

I need to expose MKL 8-bit GEMMs as a custom kernel. I use pytorch cpp extension to do that. Although the kernel works in cpp level, I can't link and run it on the pytorch level. There seems to be a missing linking while using torch cpp extension. 

I attach the kernel cpp code and setup.py.  Pip compiles and installs successfully so linking should work at compile time. However, when I import the custom kernel, I get the following error:

```ImportError: /media/MERCURY/mehmet/anaconda3/envs/hf_quanto_cpu/lib/python3.10/site-packages/cpu_ops.cpython-310-x86_64-linux-gnu.so: undefined symbol: cblas_gemm_s8u8s32```

Kernel code:
```
#include <vector>
#include <torch/extension.h>
#include "mkl.h"


torch::Tensor& _int_mm_out_cpu(const torch::Tensor& self, const torch::Tensor& mat2, torch::Tensor& result) {
    // NOTE: cuBLAS is currently broken for some combination of transposed inputs.
    TORCH_CHECK(self.dim() == 2, "Expected self to be of dimension 2 but got ", self.dim());
    TORCH_CHECK(mat2.dim() == 2, "Expected mat2 to be of dimension 2 but got ", mat2.dim());
    TORCH_CHECK(self.size(0) > 16, "self.size(0) needs to be greater than 16, but got ", self.size(0));
    TORCH_CHECK(self.size(1) > 0 && self.size(1) % 8 == 0, "self.size(1) needs to be greater than 0 and a multiple of 8, but got ", self.size(1));
    TORCH_CHECK(self.size(1) == mat2.size(0), "self.size(1) needs to match mat2.size(0) but got ", self.size(1), " and ", mat2.size(0));
    TORCH_CHECK(mat2.size(1) > 0 && mat2.size(1) % 8 == 0, "mat2.size(1) needs to be greater than 0 and a multiple of 8, but got ", mat2.size(1));

    TORCH_CHECK(result.dtype() == at::kInt, "Expected result dtype to be of type kInt but got ", result.dtype());
    TORCH_CHECK(result.size(0) == self.size(0), "Expected result.size(0) to be ", self.size(0), " but got ", result.size(0));
    TORCH_CHECK(result.size(1) == mat2.size(1), "Expected result.size(1) to be ", mat2.size(1), " but got ", result.size(1));

    TORCH_CHECK(result.dim() == 2, "Expected result to be of dimension 2 but got ", result.dim());

    TORCH_CHECK(result.is_contiguous(), "Expected result to be contiguous.");

    MKL_INT         m=self.size(0), n=mat2.size(0), k=self.size(1);
    MKL_INT         lda=self.size(1), ldb=mat2.size(1), ldc=result.size(1);
    float           alpha=1.0f, beta=0.0f;

    const MKL_INT8 ao = 0;
    const MKL_INT8 bo = 0;
    MKL_INT32 co = 0;
    CBLAS_OFFSET    offsetc=CblasFixOffset;

    cblas_gemm_s8u8s32(CblasRowMajor, CblasNoTrans, CblasNoTrans, offsetc,
                      m, n, k, alpha, self.data_ptr<int8_t>(), lda, ao, mat2.data_ptr<uint8_t>(), ldb, bo, beta, result.data_ptr<int32_t>(), ldc, &co);

  return result;
}


torch::Tensor _int_mm_cpu(const torch::Tensor& self, const torch::Tensor& mat2) {
  torch::Tensor result = torch::empty({self.size(0), mat2.size(1)}, self.options().dtype(torch::kInt));
  return _int_mm_out_cpu(self, mat2, result);
}


PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("_int_mm", &_int_mm_cpu, "_int_mm");
}

```

setup.py:
```
from setuptools import setup, find_packages
from torch.utils.cpp_extension import BuildExtension, CppExtension, include_paths
import torch

import os
from typing import List, Set

ext_modules = []
cpu_extension = CppExtension(
   name='cpu_ops',
   sources=['/library/cpu/cpu_mm.cpp'],
    )
ext_modules.append(cpu_extension)


setup(
    name="kernel_test",
    packages=find_packages(),
    include_package_data=True,
    ext_modules=ext_modules,
    cmdclass={
        'build_ext': BuildExtension
    },
    zip_safe=False,
)
```
It is not clear to me how to link mkl lib at runtime. I already updated LD_LIBRARY_PATH to include mkl lib directories. But no success.

### Versions

Collecting environment information...
PyTorch version: 2.2.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.10 (x86_64)
GCC version: (Ubuntu 8.4.0-4ubuntu1) 8.4.0
Clang version: Could not collect
CMake version: version 3.20.3
Libc version: glibc-2.32

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.32
Is CUDA available: False
CUDA runtime version: 12.2.91
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB
GPU 2: Tesla V100-PCIE-32GB
GPU 3: Tesla V100-PCIE-32GB
GPU 4: Tesla V100-PCIE-32GB
GPU 5: Tesla V100-PCIE-32GB
GPU 6: Tesla V100-PCIE-32GB
GPU 7: Tesla V100-PCIE-32GB

Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8260M CPU @ 2.40GHz
Stepping:                        7
CPU MHz:                         2400.000
CPU max MHz:                     3900.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4800.00
Virtualization:                  VT-x
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==2.2.0+cpu
[pip3] torchaudio==2.2.0+cpu
[pip3] torchvision==0.17.0+cpu
[conda] mkl                       2024.0.0                 pypi_0    pypi
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.2.0+cpu                pypi_0    pypi
[conda] torchaudio                2.2.0+cpu                pypi_0    pypi
[conda] torchvision               0.17.0+cpu               pypi_0    pypi

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by drisspg** [comment]
I think this would be a better to post on dev discuss: https://dev-discuss.pytorch.org/

**Comment by cpuhrsch** [comment]
@maktukmak - We could also expose this as a [CPU backend for _int_mm](https://github.com/pytorch/pytorch/blob/7ec6ac89e84f3927430cd3182ae2ccc7ee6a5531/aten/src/ATen/native/native_functions.yaml#L4074-L4080). Could you share a bit more of your use case here? Thank you.

**Comment by maktukmak** [comment]
@cpuhrsch, that would be great. That was actually what I was trying to do. _int_mm does not support the CPU backend currently, so I was trying to add the kernel myself as a workaround. How will we add _int_mm for CPU backend? Is there any ongoing work?

**Comment by mingfeima** [comment]
Agreed with @cpuhrsch, add cpu support for `_int_mm` would be best option.

@maktukmak  About the linkage error, I used to do something similar and you can double check the cython .so links to `libtorch_cpu.so` which links to mkl .so, as below:
```
(lowe) mingfeim@aia-sdp-spr-116462:~/mkl_gemm/build/lib.linux-x86_64-cpython-310$ ldd cpu_ops.cpython-310-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007fff0d3bd000)
        libc10.so => not found
        libtorch_cpu.so => not found
        libtorch_python.so => not found
        libstdc++.so.6 => /home/mingfeim/anaconda3/envs/lowe/lib/libstdc++.so.6 (0x00007ff6e859a000)
        libgcc_s.so.1 => /home/mingfeim/anaconda3/envs/lowe/lib/libgcc_s.so.1 (0x00007ff6e857e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff6e8355000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff6e826e000)
```

```
(lowe) mingfeim@aia-sdp-spr-116462:~/anaconda3/envs/lowe/lib/python3.10/site-packages/torch/lib$ ldd libtorch_cpu.so
        linux-vdso.so.1 (0x00007ffd19ff4000)
        libc10.so => /home/mingfeim/anaconda3/envs/lowe/lib/python3.10/site-packages/torch/lib/./libc10.so (0x00007f98b6a9e000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f98b6a8f000)
        libgcc_s.so.1 => /home/mingfeim/anaconda3/envs/lowe/lib/python3.10/site-packages/torch/lib/./../../../../libgcc_s.so.1 (0x00007f98b6a75000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f98b6a70000)
        libmkl_intel_lp64.so => /home/mingfeim/anaconda3/envs/lowe/lib/python3.10/site-packages/torch/lib/./../../../../libmkl_intel_lp64.so (0x00007f98b577e000)
        libmkl_gnu_thread.so => /home/mingfeim/anaconda3/envs/lowe/lib/python3.10/site-packages/torch/lib/./../../../../libmkl_gnu_thread.so (0x00007f98b3afe000)
        libmkl_core.so => /home/mingfeim/anaconda3/envs/lowe/lib/python3.10/site-packages/torch/lib/./../../../../libmkl_core.so (0x00007f98af62c000)
```

I tried your example, it works fine on my environment :)
```
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import cpu_ops
>>> a = torch.randn(32, 16).to(dtype=torch.int8)
>>> b = torch.randn(16, 16).to(dtype=torch.uint8)
>>> c = cpu_ops._int_mm(a, b)
>>> print(c.sum())
tensor(-21215)

```
