### ISSUE TITLE
torch.cumulative_trapezoid is inconsistent with scipy_cumulative_trapezoid behavior with scipy 1.12.0 changes

### ISSUE THREAD

**Issue by nWEIdia** [pytorch/pytorch#119391]
### 🐛 Describe the bug

Background: Scipy 1.12.0 has added [this assertion](https://github.com/scipy/scipy/commit/fb42116c91e2ff45207350ea19eef0de017fdc64#diff-2ff88b8913ad74b9ea3fe1fe02d6d49164855189168b767076af2e94206c3a2cR493) check.
This makes the test cases in [test_binary_ufuncs.py]( https://github.com/pytorch/pytorch/blob/main/test/test_binary_ufuncs.py#L3854 ) fail the assertion. i.e. when y=[] and the shape is (0,2), scipy will now raise ValueError ("At least one point is required along `axis`.") and fail. 

Currently [pytorch's scipy](https://github.com/pytorch/pytorch/blob/3b417934127920391bc745404f2ac49d3f0db16e/.ci/docker/requirements-ci.txt#L231-L233) is not dependent on 1.12.0 yet. But if scipy version gets updated, tests would fail with the err_msg listed in [this PR](https://github.com/pytorch/pytorch/pull/119326).

### Versions

main branch + scipy 1.12.0

**Comment by nWEIdia** [comment]
We are wondering should we merge https://github.com/pytorch/pytorch/pull/119326 (just to get CI green) or should we wait for pytorch to align with scipy behavior. Please advise, thanks! 

cc @ptrblck @eqy

**Comment by kurtamohler** [comment]
I'm not sure what the rationale was for `scipy.cumulative_trapezoid` to no longer support zero-length inputs. I looked through the PR and there did not seem to be a discussion about that specifically, as far as I saw.

In general, supporting zero-length inputs to operations is preferable to not supporting them. So I would think that until we have some good reason why `torch.cumulative_trapezoid` should error in this case, it should not be updated to align with scipy in this case.

In my opinion, updating the CI test to pass when scipy==1.12.0 (like what is proposed in #119326) is the right way to go

**Comment by kurtamohler** [comment]
My question on the scipy PR was answered [here](https://github.com/scipy/scipy/pull/19709#issuecomment-1939432695). I'm not sure whether or not we would want to follow suit with this change.

cc @ezyang @albanD

**Comment by albanD** [comment]
Yes the suggestion you have on the PR sounds good to me.

**Comment by nWEIdia** [comment]
https://github.com/pytorch/pytorch/pull/121541 closes this issue. Thanks @Aidyn-A !
