### ISSUE TITLE
[dynamic shapes] Symbolic guards with float values 

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#119338]
### 🐛 Describe the bug

Repro - Get this PR - https://github.com/pytorch/pytorch/pull/118448

Run `PYTORCH_TEST_WITH_DYNAMO=1 TORCH_LOGS="dynamic" pytest test/test_nn.py::TestNNDeviceTypeCPU::test_affine_2d_rotateRandom_cpu`

The failing guard is 

```
eval Eq(1.0/(0.5*s0 - 0.5), 0.666666666666667) [guard added] at test/test_nn.py:7426 in _buildEquivalentAffineTransforms2d (_numpy/_util.py:178 in _try_convert_to_tensor)
```

List of tests failing

* `PYTORCH_TEST_WITH_DYNAMO=1 pytest test/test_nn.py::TestNNDeviceTypeCPU::test_affine_3d_rotateRandom_cpu`
* 

### Versions

NA

cc @ezyang @msaroufim @bdhirsh @zou3519

**Comment by ezyang** [comment]
![image](https://github.com/pytorch/pytorch/assets/13564/e566f255-0811-4df7-b89a-79842bb18c98)

**Comment by lezcano** [comment]
I wrote a few asserts at some point checking that all the quantities passed to value ranges are rational
https://github.com/pytorch/pytorch/blob/d85631b721268448bf4791c595b2ca08fd65bf06/torch/fx/experimental/symbolic_shapes.py#L696-L702
We can use that to avoid this sort of cases in other parts of the codebase

**Comment by lezcano** [comment]
If that float is a hardcoded number we could always do a transformation to see if the norm is less than a few times the epsilon for the type.

**Comment by ezyang** [comment]
Related https://github.com/pytorch/pytorch/issues/107277

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/126905 should have helped here, though maybe there's a weensy bit of follow through we have to do

**Comment by anijain2305** [comment]
95% of skips in the guard validation PR are from this. Maybe worth doing a quick check if it's an easy follow up?

**Comment by ezyang** [comment]
Oh this is funny... I think we're not printing enough digits precision LOL
