### ISSUE TITLE
torch.multinomial performance issue when replacement=False

### ISSUE THREAD

**Issue by bfreskura** [pytorch/pytorch#11931]
## Issue description

`torch.multinomial` becomes very slow if the `replacement=False` and the `num_samples` is relatively large. 

## Code example
```
import torch
weights = torch.randn(10000000, dtype=torch.float32).clamp(0.01, 1)

n_small = 100
n_big = 100000

# Works
sample_1 = torch.multinomial(weights, n_small, replacement=True)
print("Sampled 1")

# Works
sample_2 = torch.multinomial(weights, n_big, replacement=True)
print("Sampled 2")

# Works, but much slower
sample_3 = torch.multinomial(weights, n_small, replacement=False)
print("Sampled 3")

# I think it works, but it takes so long that it is unusable
sample_4 = torch.multinomial(weights, n_big, replacement=False)
print("Sampled 4")
```

## System Info
```
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 390.59
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @VitalyFedyunin @ngimel @mruberry

**Comment by t-vi** [comment]
This is expected as the non-repeating actually makes sampling a serial process. While there is room for optimization relative to the current way of doing things, I don't think you can this to get much better when you have many samples.

**Comment by bfreskura** [comment]
Numpy function `choice` works normally for large inputs and large samples:
`x = np.random.choice(1000000, 100000, replace=False)`

Isn't this the same as `torch.multinomial`?

**Comment by t-vi** [comment]
Not quire, it's more like
`a = numpy.random.choice(1_000_000, 100_000, replace=False, p=probs)`
but you're absolutely right, we are unreasonably slow there.
Thank you for reporting and insisting!

**Comment by t-vi** [comment]
So what numpy does is approximately:
```
current_dist = dist
samples = []
while len(samples) < n_desired_samples:
   raw_samples = draw n_good_samples-n_desired_samples with replacement from current_dist
   new_good = "arg_unique"(raw_samples)
   current_dist[raw_samples] = 0
   samples += new_good
```
so it will attempt (but fail) to get all samples, but will be much more efficient than sampling only one at a time and renormalizing the pdf after each sample.
I'll implement this, but I can't promise to get it done before 1.0.

**Comment by Walstruzz** [comment]
PyTorch 1.2.0
It's still very slow...

**Comment by cpuhrsch** [comment]
@t-vi - I'm assigning you to this just because you commented on it earlier, but I'm also assigning myself to keep track of it. Let me know how you think we should do this.

**Comment by jacobkimmel** [comment]
I'll add a bump to this -- I love the `Multinomial` API, but sampling is much slower than a comparable call to `numpy`.

Given a set of parameters `p` with `p.shape[0] == 20000`, `torch.distributions.Multinomial(10000, probs=p).sample()` takes 100 seconds longer than `np.random.multinomial(10000, pvals=p)` using the latest `torch==1.4`.

**Comment by RobertoLat** [comment]
I also bumped into this issue. 

I solved using algorithm A of this [paper](https://utopia.duth.gr/~pefraimi/research/data/2007EncOfAlg.pdf)

`p = torch.from_numpy(np.random.rand(1_000_000))`
`want = 1000`

The following line took 1.5s on my laptop (CPU)

`a = torch.multinomial(p, want, replacement=False)`

while the following two should be equivalent and only took 53ms

`rand = torch.empty_like(p).uniform_()`
`a = (rand.log()/p).topk(k=want).indices`

**Comment by ngimel** [comment]
Thanks for reporting. Couple questions to people on this thread
1) Are you more interested in CPU or GPU performance?
2) What's the typical shape[1] of the `input` parameter (i.e. do you want to sample from a single distribution, in which case shape[1] is 1, or are you sampling from multiple distributions?
Thank you!

**Comment by ngimel** [comment]
Bumping priority based on user activity.

**Comment by RobertoLat** [comment]
I am sampling from a classifier. So the first dimension is the batch which for me is anything between 100 and 2000.

**Comment by ngimel** [comment]
@jacobkimmel, both `numpy.random.multinomial` and `torch.distributions.Multinomial` are doing sampling with `replacement=True`, so your issue is different from this one. Please open a separate issue for this.

**Comment by t-vi** [comment]
@RobertoLat Awesome method, I was completely unaware! I'll implement this.

Curiously, I haven't really found where the paper proves the crucial Theorem 1 (maybe it was more trivial to the authors than to me), so here is a small proof I came up with:
![image](https://user-images.githubusercontent.com/20787943/81481086-d0a6d700-922d-11ea-8ae7-e9e4f9ac7a53.png)

**Comment by ezyang** [comment]
FYI @ngimel has made a very minor improvement to the performance of multinomial in #38046 but it shouldn't be considered to fix this issue

**Comment by ngimel** [comment]
@t-vi was actually going to implement `replacement=False` fix, reassigning him. 
@t-vi feel free to unassign yourself if you decide you don't want to do it after all.

**Comment by kshitij12345** [comment]
Closing the issue as https://github.com/pytorch/pytorch/pull/39636 was merged.
Feel free to re-open in case I missed anything. :)
