### ISSUE TITLE
Expression canonicalization results in unintuitive expressions for users

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119467]
### 🐛 Describe the bug

The two that I've seen recently are `-u0 < 0` (why didn't you just say `u0 > 0`) and `Eq(-u0 + u1, 0)` (why didn't you just say `Eq(u1, u0)`. I'm not sure who is responsible for canonicalizing the expressions this way, might be sympy. Maybe we should just have a peephole pretty printer to do simple rewrites for clarity.

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @lezcano 

### Versions

main

**Comment by lezcano** [comment]
That's me lol

One of the steps just pushes all the symbols to one side and canonicalises the le into a ge and stuff like that.

https://github.com/pytorch/pytorch/blob/896cf9d1ce3dec70fc33bf08fe21fa30ab4ff77c/torch/fx/experimental/symbolic_shapes.py#L200-L206

Do you want to move them back to a "nice and pretty readable format" afterwards?

**Comment by ezyang** [comment]
It's OK to internally represent in canonical form, we just need to uncanonicalize it when reporting to users, I think.
