### ISSUE TITLE
Unbound local in inductor with inplace foreach and views

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#119436]
### 🐛 Describe the bug

If calling an inplace foreach op with multiple views in the first input list, inductor generates bad code.

https://gist.github.com/mlazos/805db83680cc74542f9bcf0afe7a0d78

### Versions

nightly 884b6d2a675756091ae7c19b49f0aec1a8931955

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by jansel** [comment]
I think you need to call `V.kernel.cse.invalidate()` between each kernel.
