### ISSUE TITLE
Issue running squeezeLLM quantization of LLama-2-7B on VLLM

### ISSUE THREAD

**Issue by JulianneKnott** [pytorch/pytorch#119494]
### 🐛 Describe the bug

`RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED at "/tmp/pip-build-env-tq9d4ekf/overlay/lib/python3.11/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h":25, please report a bug to PyTorch.`

I am reporting this error here because it asked me to. I am trying to test llama-2 quantized with [squeezellm](https://github.com/SqueezeAILab/SqueezeLLM) using [vllm](https://github.com/vllm-project/vllm). I've attached the code to reproduce.
[bug_repro.txt](https://github.com/pytorch/pytorch/files/14215436/bug_repro.txt)

### Versions

Collecting environment information...
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.24.4
Libc version: glibc-2.35

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-1103-azure-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100 80GB PCIe
Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          96
On-line CPU(s) list:             0-95
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7V13 64-Core Processor
CPU family:                      25
Model:                           1
Thread(s) per core:              1
Core(s) per socket:              48
Socket(s):                       2
Stepping:                        1
BogoMIPS:                        4890.89
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core invpcid_single vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat umip vaes vpclmulqdq rdpid
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       3 MiB (96 instances)
L1i cache:                       3 MiB (96 instances)
L2 cache:                        48 MiB (96 instances)
L3 cache:                        384 MiB (12 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-23
NUMA node1 CPU(s):               24-47
NUMA node2 CPU(s):               48-71
NUMA node3 CPU(s):               72-95
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.1.2
[pip3] triton==2.1.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.1.2                    pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @ptrblck

**Comment by tringwald** [comment]
Thank you for your bug report. Unfortunately, I cannot reproduce the issue with the given code on my A10 instance (output below). Maybe the problem is related to the local Python setup or the specific hardware in use. 

<details>

```
config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 554/554 [00:00<00:00, 4.31MB/s]
WARNING 02-09 12:50:59 config.py:177] squeezellm quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 02-09 12:50:59 llm_engine.py:72] Initializing an LLM engine with config: model='squeeze-ai-lab/sq-llama-2-7b-w4-s0', tokenizer='squeeze-ai-lab/sq-llama-2-7b-w4-s0', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=squeezellm, enforce_eager=False, kv_cache_dtype=auto, seed=0)
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 727/727 [00:00<00:00, 9.77MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 33.2MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 411/411 [00:00<00:00, 5.53MB/s]
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
generation_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 132/132 [00:00<00:00, 1.74MB/s]
quant_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 18.0/18.0 [00:00<00:00, 249kB/s]
INFO 02-09 12:51:01 weight_utils.py:164] Using model weights format ['*.pt']
sq-llama-2-7b-w4-s0.pt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4.37G/4.37G [01:25<00:00, 51.4MB/s]
INFO 02-09 12:52:41 llm_engine.py:322] # GPU blocks: 1966, # CPU blocks: 512
INFO 02-09 12:52:42 model_runner.py:632] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 02-09 12:52:42 model_runner.py:636] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 02-09 12:53:08 model_runner.py:698] Graph capturing finished in 25 secs.
Processed prompts:   0%|                                                                                                              | 0/1024 [00:00<?, ?it/s]Processed prompts: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 1024/1024 [37:48<00:00,  2.22s/it]
Total elasped time for 1024 samples: 2268.65 seconds; 2.22 seconds per sample.
```

</details>

**Comment by albanD** [comment]
Thanks for reporting this.
It does look like this cannot repro so this might be due to the way the SqueezeLLM is using PyTorch constructs. Did you try reporting this issue to them directly?

**Comment by JulianneKnott** [comment]
Thanks for the update! This is not a huge blocker for us. I only reported it to you all because the error message asked me to 🙂. I will report it to SqueezeLLM since it appears to be an issue on their end.

Julianne
________________________________

**Comment by albanD** [comment]
Thanks a lot.
I'll be closing this since there doesn't seem to be a way to move forward on our end.
Feel free to re-open this issue or a new one if the SqueezeLLM reports that the issue might be on our end.

**Comment by JulianneKnott** [comment]
[like]  Julianne Knott reacted to your message:
________________________________
