### ISSUE TITLE
torch::autograd::validate_outputs needs to use guard oblivious test

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119476]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/6829516587176185/posts/6829560007171843/

The is_same_shape call doesn't use size oblivious / expect true so it will choke if there are unbacked SymInts involved.

You can work around it with something like this:

```
diff --git a/fbcode/caffe2/torch/csrc/autograd/engine.cpp b/fbcode/caffe2/torch/csrc/autograd/engine.cpp
--- a/fbcode/caffe2/torch/csrc/autograd/engine.cpp
+++ b/fbcode/caffe2/torch/csrc/autograd/engine.cpp
@@ -847,14 +847,7 @@
       continue;
     }
 
-    if (!metadata.is_same_shape(grad)) {
-      if (metadata.is_expandable_to_shape(grad)) {
-        grad = metadata.reduce_grad(grad);
-      } else {
-        const auto message = metadata.incompatible_shape_error_message(i, grad);
-        TORCH_CHECK(false, format_error(message.str()));
-      }
-    }
+    grad = metadata.reduce_grad(grad);
 
     bool input_is_complex =
         isComplexType(c10::typeMetaToScalarType(metadata.options().dtype()));
```

Error looks something like:

```
It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent (and thus we do not know the true value.)  The expression we were trying to evaluate is Eq(i2 + i3, i4 + i5) (unhinted: Eq(i2 + i3, i4 + i5)).  Scroll up to see where each of these data-dependent accesses originally occurred.
```

Note that it looks like maybe i4 and i5 are reallocations of i2 and i3, but these reallocations were actually done in user code (not in the framework) because they are repeatedly tolist()'ing the same tensor.

### Versions

main

cc @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @msaroufim @bdhirsh @anijain2305

**Comment by albanD** [comment]
That would mena we loose the error message and call one extra aten op unconditionally for each Node we run in the backward though?

**Comment by ezyang** [comment]
Minimal repro:

```
import torch
import torch._dynamo

torch._dynamo.config.capture_scalar_outputs = True

class SillyCat(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x0, x1, i):
        ctx.save_for_backward(i)
        return torch.cat([x0, x1])
    
    @staticmethod
    def backward(ctx, grad_out):
        i, = ctx.saved_tensors
        i0, i1 = i.tolist()
        g_x0, g_x1 = grad_out.split([i0, i1])
        return g_x0, g_x1, None

@torch.compile(fullgraph=True)
def f(x, i):
    i0, i1 = i.tolist()
    x0, x1 = x.split([i0, i1])
    return SillyCat.apply(x0, x1, i)

f(torch.randn(9, requires_grad=True), torch.tensor([3, 6]))
```

**Comment by ezyang** [comment]
@albanD I don't want to do the proposed fix as is. I think there is a way I can write is_same_shape very carefully to make it work.

**Comment by albanD** [comment]
Ho yeah maybe the nested Tensor checks there make this bad?
Is the raw `grad.sym_sizes().equals(shape_as_dim_vector())` (where shape_as_dim_vector() are SymInts from the forward) ok>

**Comment by ezyang** [comment]
No, this one is not OK lol
