### ISSUE TITLE
Typo (or joke?) in the Contribution Guide

### ISSUE THREAD

**Issue by mdevino** [pytorch/pytorch#119427]
### 📚 The doc issue

There is a typo on the [Contribution Guide](https://pytorch.org/docs/stable/community/contribution_guide.html), in the Frequently Asked Questions.

It says:

> CI tests failed, what does it mean? Maybe your PR is based off a broken main bracnh?

Is that mean to be a joke (broken branch), or an actual typo?

If it is meant to be a joke, please ignore this issue.

### Suggest a potential alternative/fix

I will be submitting a PR with the fix for the typo.

**Comment by kit1980** [comment]
A typo for sure. I've force-merged your PR, thanks!
