### ISSUE TITLE
Bad error message for aten::_local_scalar_dense on meta tensor

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119588]
### 🐛 Describe the bug

```
NotImplementedError: aten::_local_scalar_dense: attempted to run this operator with Meta tensors, but there was no abstract impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add an abstract impl.Please see the following doc for next steps: https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU/edit
```

This error message is bad because you can't actually define an abstract impl for this (or any other data dependent) operator.

cc @malfet @eellison @bdhirsh @msaroufim @anijain2305 @zou3519 @chauhang 

### Versions

main

**Comment by shogohida** [comment]
Hi, I'm interested in taking this issue. Should I change this message to a particular one?

https://github.com/pytorch/pytorch/blob/ee3a7bdc2d0966ab788e48e640879fcf4cd1c69e/aten/src/ATen/core/MetaFallbackKernel.cpp#L15-L20

**Comment by ezyang** [comment]
Yeah, registering a meta for this operator specifically with a different error message SGTM

**Comment by Saadelkouari** [comment]
I'm interested in doing my first contrib solving this issue, based on @ezyang guidance, should I add in [`torch/_meta_registrations.py`](https://github.com/pytorch/pytorch/blob/87f651c7e7197f7d45a205bca680444a8985d373/torch/_meta_registrations.py):
```python
@register_meta(aten._local_scalar_dense)
def meta_local_scalar_dense(self:Tensor):
    torch._check(
        not self.is_meta,
        lambda: "aten::_local_scalar_dense operator cannot be called on meta tensors.",
    )
    return torch.empty_like(self)
```

**Comment by zou3519** [comment]
try something like "aten::_local_scalar_dense operator (aka Tensor.item()) cannot be called on meta tensors."

Also, @ezyang -- how did you run into this? torch.compile on Tensor.item() gives a graph break

**Comment by ezyang** [comment]
Just `torch.randn(1, device='meta').item()` lol
