### ISSUE TITLE
Potential re-tracing of CUDA graphs due to spurious SymInt inputs

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119579]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/1075192433118967/posts/1377556259549248

We don't know if this is necessarily the root cause of the problem, but @Yuzhen11 described to me a potential sequence of events that seem to me could occur, so I'm recording it here.

We currently support dynamic shapes + cuda graphs by re-recording the cuda graph for each concrete size we see. Every integer input is incorporated as part of the integer key:

```
    fn_cache: Dict[Tuple[int, ...], Callable[..., Any]] = {}

    # Detect int inputs: we need to index on these
    int_key = [i for i, v in enumerate(inputs) if isinstance(v, int)]
    get_ints: Any = operator.itemgetter(*int_key) if int_key else lambda _: None
```

@Yuzhen11 said that for the particular case above, there is an int input that is varying from run to run, BUT this input appears to be dead. We are supposed to prune dead SymInts, but maybe it isn't quite working. In any case, if you have a useless input, it WILL impede cuda graphs from being able to run in this case. So we should check if this is actually the case / make sure we are properly pruning dead symint inputs (previously, I believed this was mostly harmless, but it doesn't seem to be here).

cc @mcarilli @msaroufim @bdhirsh @anijain2305 @zou3519 @eellison 

### Versions

main

**Comment by ezyang** [comment]
Some evidence from internal suggests that the dependence is actually real (so not spurious)

**Comment by eellison** [comment]
> Some evidence from internal suggests that the dependence is actually real (so not spurious)

Should we close this ?
