### ISSUE TITLE
12 Dynamo test failing with with Can't construct an AttrSource without a valid base 

### ISSUE THREAD

**Issue by laithsakka** [pytorch/pytorch#119580]
### 🐛 Describe the bug

initial look shows that we call  for the function call 
     dispatch_torch_function(tx, self, args, kwargs)
     
  ```
     out_attn_bias = scaled_dot_product_attention(query, key, value, attn_mask=attn_bias, dropout_p=0.0)
 ```
 the arg attn_bias satisfy has_torch_function(arg)
but arg source is None and arg base is None . 

arg.call_torch_function()->get_torch_fn()->build_torch_function_fn 
 ```
    if not source:
        return VariableBuilder(
            tx,
            AttrSource(AttrSource(source, "__torch_function__"), "__func__"),
        )(value.__torch_function__.__func__)
    else:
        return SourcelessBuilder()(tx, value.__torch_function__.__func__)
```
fail because base and source are none. 
all the tests failing:

```
"TestAttnMasksCPU.test_is_causal_equals_upper_left_shape0_cpu",  # Can't construct an AttrSource without a valid base source
    "TestAttnMasksCPU.test_is_causal_equals_upper_left_shape1_cpu",  # Can't construct an AttrSource without a valid base source
    "TestAttnMasksCPU.test_is_causal_equals_upper_left_shape2_cpu",  # Can't construct an AttrSource without a valid base source
    "TestAttnMasksCPU.test_is_causal_equals_upper_left_shape3_cpu",  # Can't construct an AttrSource without a valid base source
    "TestAttnMasksCPU.test_is_causal_equals_upper_left_shape0_cuda",  # Can't construct an AttrSource without a valid base source
    "TestAttnMasksCPU.test_is_causal_equals_upper_left_shape1_cuda",  # Can't construct an AttrSource without a valid base source
    "TestAttnMasksCPU.test_is_causal_equals_upper_left_shape2_cuda",  # Can't construct an AttrSource without a valid base source
    "TestAttnMasksCPU.test_is_causal_equals_upper_left_shape3_cuda",  # Can't construct an AttrSource without a valid base source
    "TestAttnBiasCPU.test_is_causal_equals_upper_left_shape2_cpu",  # Can't construct an AttrSource without a valid base source
    "TestAttnBiasCPU.test_is_causal_equals_upper_left_shape3_cpu",  # Can't construct an AttrSource without a valid base source
    "TestAttnBiasCPU.test_is_causal_equals_upper_left_shape1_cpu",  # Can't construct an AttrSource without a valid base source
    "TestAttnBiasCPU.test_is_causal_equals_upper_left_shape0_cpu",  # Can't construct an AttrSource without a valid base source
```

### Versions

NA

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by zou3519** [comment]
cc @mlazos for torch_function

**Comment by mlazos** [comment]
Hi, are these the tests that we are dynamo'ing?

**Comment by laithsakka** [comment]
this is where the source and base get lost
```
 var = tx.output.side_effects.track_object_new(
                self.source,
                self.value,
                variables.UnspecializedNNModuleVariable
                if issubclass(self.value, torch.nn.Module)
                else UserDefinedObjectVariable,
                {},
         ```

**Comment by laithsakka** [comment]
> _is_causal_equals_u

yes

**Comment by laithsakka** [comment]
this where the var with no source and base is created. 
     elif (
            inspect.getattr_static(self.value, "__new__", None) in (object.__new__,)
            and SideEffects.cls_supports_mutation_side_effects(self.value)
            and self.source
        ):
            var = tx.output.side_effects.track_object_new(
                self.source,
                self.value,
                variables.UnspecializedNNModuleVariable
                if issubclass(self.value, torch.nn.Module)
                else UserDefinedObjectVariable,
                {},
            )

**Comment by laithsakka** [comment]
FYI, you want to be on top of https://github.com/pytorch/pytorch/pull/119435 to repo with the tests above

**Comment by laithsakka** [comment]
@mlazos so I just changed the code bellow to do what the comment says its doing and it worked lol
```
    all_args = pytree.arg_tree_leaves(*args, **kwargs)
    overloaded_args = _get_overloaded_args(
        [arg for arg in all_args if has_torch_function(arg)],
        _get_subclass_type,
    )
 ```
 
 ```
     """Gathers all args that are TensorWithTFOverrideVariable and dispatches based on the ordering in _get_overloaded_args"""

    all_args = pytree.arg_tree_leaves(*args, **kwargs)
    overloaded_args = _get_overloaded_args(
        [arg for arg in all_args if isinstance(arg, TensorWithTFOverrideVariable)],
        _get_subclass_type,
    )
 ````
 
 basically instead of calling  has_torch_function(arg) doing isinstance(arg, TensorWithTFOverrideVariable)
 
 note the implementation of has_torch
 ```
     """Gathers all args that are TensorWithTFOverrideVariable and dispatches based on the ordering in _get_overloaded_args"""

 def has_torch_function(vt: "torch._dynamo.variables.base.VariableTracker") -> bool:
    from torch._dynamo.variables import UserDefinedObjectVariable
    from torch._dynamo.variables.torch_function import TensorWithTFOverrideVariable

    return isinstance(vt, TensorWithTFOverrideVariable) or (
        isinstance(vt, UserDefinedObjectVariable)
        and hasattr(vt.value, "__torch_function__")
    )
```

**Comment by laithsakka** [comment]
will put a pr for testing but tbh idk what the heck this code is doing lol it would be nice to get an intro @mlazos

**Comment by laithsakka** [comment]
Looking at the function below sounds that if ever  not source is True, 

Then AttrSource will fail since it takes source as base and there i assertion that base should not be None!
 
 if not source:
       return VariableBuilder(
           tx,
           AttrSource(AttrSource(source, "__torch_function__"), "__func__"),
       )(value.__torch_function__.__func__)
   else:
       return SourcelessBuilder()(tx, value.__torch_function__.__func__)

**Comment by laithsakka** [comment]
sounds like the problem is 
1) 
We create a sourceless variable here we we create object for a class
```
   var = tx.output.side_effects.track_object_new(
                self.source,
                self.value,
                variables.UnspecializedNNModuleVariable
                if issubclass(self.value, torch.nn.Module)
                else UserDefinedObjectVariable,
                {},
            )
    ```
    
2) Then we do not handle sourceless node correctly in the code shared above in the previous comment.
 
General questions do  we not want UserDefinedObjectVariable to have a source , but then are we sure we can have correct guards installed?I see the code that install the guards is defined in the source objects in guard_source.
