### ISSUE TITLE
Export of bitwise_right_shift to ONNX needed for llama2-7b 8-bit quantized pytorch model

### ISSUE THREAD

**Issue by daveliddell** [pytorch/pytorch#119621]
### 🚀 The feature, motivation and pitch

We are attempting to export a quantized llama model (from HuggingFace) to ONNX but are running into an unsupported op error for bitwise_right_shift:

`torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::bitwise_right_shift' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.`

Would you please consider adding support for exporting this op to onnx?  Sample python to reproduce below.  Thanks!

### Additional context
```

import sys, argparse
import torch
import torch.nn as nn
import transformers
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    GPTQConfig,
)

modelname = "TheBloke/Llama-2-7B-GPTQ"
kwargs = {
    "torch_dtype": torch.float32,
    "trust_remote_code": True,
}
quantization_config = GPTQConfig(bits=8, disable_exllama=True)
kwargs["quantization_config"] = quantization_config
kwargs["device_map"] = "cpu"
model = AutoModelForCausalLM.from_pretrained(
    modelname, low_cpu_mem_usage=True, attn_implementation="eager", **kwargs
)
# model.output_hidden_states = False
tokenizer = AutoTokenizer.from_pretrained(modelname)
prompt = "What is nature of our existence?"
encoding = tokenizer(prompt, return_tensors="pt")
test_input = encoding["input_ids"].cpu()
test_output = model.generate(
    test_input,
    do_sample=True,
    top_k=50,
    max_length=100,
    top_p=0.95,
    temperature=1.0,
)[0]
# forward_out = model.forward(test_input)
print("Prompt:", prompt)
print("Response:", tokenizer.decode(test_output))
print("Input:", test_input)
print("Output:", test_output)
onnx_name = "model.onnx"
onnx_program = torch.onnx.export(model, test_input, onnx_name, export_params=True)
```

**Comment by kumardeepakamd** [comment]
Is there any workaround for getting int8 ONNX model for llama2? Also, wanted to know approximate timeframe for resolution of this issue.

**Comment by thiagocrepaldi** [comment]
bitwise_right_shift is not supproted by torch.onxn.export and it is not planned to be

Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html) We do export llama v2 to onnx using the new exporter :)
