### ISSUE TITLE
Inconsistent error message about tensors on different devices, when one tensor is a scalar

### ISSUE THREAD

**Issue by chrisyeh96** [pytorch/pytorch#119609]
### 🐛 Describe the bug

I ran into this odd behavior in PyTorch where it _sometimes_ doesn't complain about two tensors being on different devices if one of them is a scalar tensor (_i.e._, has shape `()`). Is this behavior expected? If so, is it documented anywhere?

```python
# two scalars
torch.ones(()) + torch.ones(()).cuda()  # OK
torch.ones(()).cuda() + torch.ones(())  # OK

# one scalar (CPU), one vector (GPU)
torch.ones(()) + torch.ones(1).cuda()  # OK
torch.ones(1).cuda() + torch.ones(())  # OK

# one scalar (GPU), one vector (CPU)
torch.ones(()).cuda() + torch.ones(1)  # fails
torch.ones(1) + torch.ones(()).cuda()  # fails
```

Only the last two lines raise a RuntimeError:

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

### Versions

PyTorch 2.1.0

cc @svekars @brycebortree @albanD @malfet

**Comment by albanD** [comment]
Hey!

Thanks for opening this issue.
Yes this behavior is expected. Only scalar Tensor (ndim==0) are automatically moved to cuda automatically (as this can always be done efficiently). Any non-Scalar Tensor will not be moved indeed.
Also the asymmetry is because we only allow scalar moving from CPU -> Device.

**Comment by albanD** [comment]
We have some details on dtype but not sure about the state of device.

**Comment by chrisyeh96** [comment]
Yeah, I didn't see any mention of the automatic device movement of scalar tensors on that page. Perhaps the `torch.device` section on that same page would be an appropriate place to document this behavior.

**Comment by albanD** [comment]
Yep that sounds good to me!
