### ISSUE TITLE
`RuntimeError: undefined Tensor` when calling loss.backward() with cuda on OSX 10.13.6

### ISSUE THREAD

**Issue by zkaden** [pytorch/pytorch#11964]
## Issue description

`RuntimeError: undefined Tensor` when calling `loss.backward()` with CUDA on OSX 10.13.6. The code runs successfully on cpu on OSX and also runs successfully on linux with CUDA. CUDA version is 9.2 and cuDNN version is 7.2

The traceback is:

> Traceback (most recent call last):
>   File "main.py", line 129, in <module>
>     action_mode=args.action_mode)
>   File "main.py", line 17, in main
>     action_mode=action_mode)
>   File "/path/to/file/learner_lstm.py", line 32, in train
>     loss.backward()
>   File "/Users/Zack/Envs/gpu/lib/python3.6/site-packages/torch/tensor.py", line 96, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/Users/Zack/Envs/gpu/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: undefined Tensor
> 

## Code example

`import torch`
`import torch.nn as nn`
`from torch import optim`

`class LSTM(nn.Module):`
&nbsp;&nbsp;&nbsp;&nbsp;`def __init__(self, embed_dim=10):`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`super(LSTM, self).__init__()`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.embed_dim = embed_dim`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.lstm = nn.LSTMCell(1, self.embed_dim)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`if torch.cuda.is_available():`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.cuda()`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.dtype = torch.cuda.FloatTensor`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`else:`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.dtype = torch.FloatTensor`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.init_memory()`

&nbsp;&nbsp;&nbsp;&nbsp;`def init_memory(self):`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.init_hidden()`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.init_cell()`

&nbsp;&nbsp;&nbsp;&nbsp;`def init_hidden(self):`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.hidden = torch.zeros(1, self.embed_dim).type(self.dtype)`

&nbsp;&nbsp;&nbsp;&nbsp;`def init_cell(self):`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.cell = torch.zeros(1, self.embed_dim).type(self.dtype)`

&nbsp;&nbsp;&nbsp;&nbsp;`def forward(self, movie_rating):`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.hidden, self.cell = self.lstm(`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`movie_rating, (self.hidden, self.cell)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`return self.hidden, self.cell`

`model = LSTM()`
`loss_function = nn.MSELoss()`
`optimizer = optim.Adam(model.parameters())`

`for i in range(1000000):`
&nbsp;&nbsp;&nbsp;&nbsp;`for j in range(6):`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`hidden, cell = model.forward(torch.Tensor([[3]]).type(model.dtype))`
&nbsp;&nbsp;&nbsp;&nbsp;`loss = loss_function(cell, torch.Tensor([[0,1,2,3,4,5,6,7,8,9]]).type(model.dtype))`
&nbsp;&nbsp;&nbsp;&nbsp;`loss.backward()`
&nbsp;&nbsp;&nbsp;&nbsp;`self.optimizer.step()`

## System Info

PyTorch version: 0.5.0a0+802380a
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda/lib/libcudnn.7.dylib
/usr/local/cuda/lib/libcudnn.dylib
/usr/local/cuda/lib/libcudnn_static.a
 -- cuDNN

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by zkaden** [comment]
Issue fixed by downgrading to v0.4.1. Leaving open since it's still a bug on v0.5.0

**Comment by SsnL** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/11872. It should work now if you pull again :)
