### ISSUE TITLE
If dynamic shapes runtime CUDA graphs never quiesces, should loudly warn / easy to diagnose

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119640]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/1075192433118967/posts/1377556259549248/

We support dynamic shapes and CUDA graphs together, by CUDA graphing every distinct size we observe at runtime. In some cases, this process will never quiesce; e.g., if you range from 1-10000, that is far too many CUDA graphs. We should have some limit and refuse to keep tracing CUDA graphs if we hit this limit; it should also be easier to diagnose if this is what is happening.

### Versions

main

cc @gchanan @zou3519 @kadeng @mcarilli @eellison @peterbell10 @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by vadimkantorov** [comment]
I think this is very important to somehow explain to the users... So that the user can actually do some padding to multiples of some shape to limit the shape set

**Comment by vadimkantorov** [comment]
@ezyang In practice to benefit from CUDA graphs and very variable sequence sizes, does it mean, we should pad them somehow to a fixed number of input shapes? (Somehow decaying back to static shapes then).

I wonder if there would be a way to express this somehow. As this is the most common usecase

**Comment by vadimkantorov** [comment]
E.g for var seqlen put to 4096 there might be many more dynamic shapes than 50 different shapes... so maybe worth to have some recommended recipes for this usecase (maybe via some NestedTensor support + pad of the NestedTensor underlying storage / block size?): maybe for this typical usecase dynamic shapes are not actually practical :( or will lead to cuda graphs always recompiling or disabled
