### ISSUE TITLE
operator 'aten::std_mean.correction'

### ISSUE THREAD

**Issue by rao-arimilli** [pytorch/pytorch#119663]
### 🚀 The feature, motivation and pitch

My apologies if this has already been reported!

Running openai/whisper-large-v2 on Macbook M3 Max, when device is set to mps 
the following NotImplementedError is shown
NotImplementedError: The operator 'aten::std_mean.correction' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

Would very much appreciate if this feature can be prioritised or a work around is available.

### Additional context

prediction = pipe(sample, batch_size=8, return_timestamps="word")["chunks"]
File ~/anaconda3/lib/python3.11/site-packages/transformers/pipelines/automatic_speech_recognition.py:272, in AutomaticSpeechRecognitionPipeline.__call__(self, inputs, **kwargs)
    225 def __call__(
    226     self,
    227     inputs: Union[np.ndarray, bytes, str],
    228     **kwargs,
    229 ):
    230     """
    231     Transcribe the audio sequence(s) given as inputs to text. See the [`AutomaticSpeechRecognitionPipeline`]
    232     documentation for more information.
   (...)
    270                     `"".join(chunk["text"] for chunk in output["chunks"])`.
    271     """
--> 272     return super().__call__(inputs, **kwargs)

File ~/anaconda3/lib/python3.11/site-packages/transformers/pipelines/base.py:1113, in Pipeline.__call__(self, inputs, num_workers, batch_size, *args, **kwargs)
   1111     return self.iterate(inputs, preprocess_params, forward_params, postprocess_params)
   1112 elif self.framework == "pt" and isinstance(self, ChunkPipeline):
-> 1113     return next(
   1114         iter(
   1115             self.get_iterator(
   1116                 [inputs], num_workers, batch_size, preprocess_params, forward_params, postprocess_params
   1117             )
   1118         )
   1119     )
   1120 else:
   1121     return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)

File ~/anaconda3/lib/python3.11/site-packages/transformers/pipelines/pt_utils.py:124, in PipelineIterator.__next__(self)
    121     return self.loader_batch_item()
    123 # We're out of items within a batch
--> 124 item = next(self.iterator)
    125 processed = self.infer(item, **self.params)
    126 # We now have a batch of "inferred things".

File ~/anaconda3/lib/python3.11/site-packages/transformers/pipelines/pt_utils.py:266, in PipelinePackIterator.__next__(self)
    263             return accumulator
    265 while not is_last:
--> 266     processed = self.infer(next(self.iterator), **self.params)
    267     if self.loader_batch_size is not None:
    268         if isinstance(processed, torch.Tensor):

File ~/anaconda3/lib/python3.11/site-packages/transformers/pipelines/base.py:1027, in Pipeline.forward(self, model_inputs, **forward_params)
   1025     with inference_context():
   1026         model_inputs = self._ensure_tensor_on_device(model_inputs, device=self.device)
-> 1027         model_outputs = self._forward(model_inputs, **forward_params)
   1028         model_outputs = self._ensure_tensor_on_device(model_outputs, device=torch.device("cpu"))
   1029 else:

File ~/anaconda3/lib/python3.11/site-packages/transformers/pipelines/automatic_speech_recognition.py:447, in AutomaticSpeechRecognitionPipeline._forward(self, model_inputs, return_timestamps, generate_kwargs)
    442 # we need to pass `processed.get("attention_mask")` here since audio encoder
    443 # attention mask  length is different from expected text decoder `encoder_attention_mask` length
    444 # `generate` magic to create the mask automatically won't work, we basically need to help
    445 # it here.
    446 attention_mask = model_inputs.pop("attention_mask", None)
--> 447 tokens = self.model.generate(
    448     encoder_outputs=encoder(inputs, attention_mask=attention_mask),
    449     attention_mask=attention_mask,
    450     **generate_kwargs,
    451 )
    452 if return_timestamps == "word" and self.type == "seq2seq_whisper":
    453     out = {"tokens": tokens["sequences"], "token_timestamps": tokens["token_timestamps"]}

File ~/anaconda3/lib/python3.11/site-packages/transformers/models/whisper/modeling_whisper.py:1767, in WhisperForConditionalGeneration.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, return_timestamps, task, language, is_multilingual, prompt_ids, return_token_timestamps, **kwargs)
   1756 outputs = super().generate(
   1757     inputs,
   1758     generation_config,
   (...)
   1763     **kwargs,
   1764 )
   1766 if return_token_timestamps and hasattr(generation_config, "alignment_heads"):
-> 1767     outputs["token_timestamps"] = self._extract_token_timestamps(outputs, generation_config.alignment_heads)
   1769 return outputs

File ~/anaconda3/lib/python3.11/site-packages/transformers/models/whisper/modeling_whisper.py:1819, in WhisperForConditionalGeneration._extract_token_timestamps(self, generate_outputs, alignment_heads, time_precision)
   1816 weights = weights.permute([1, 0, 2, 3])
   1818 # Normalize and smoothen the weights.
-> 1819 std, mean = torch.std_mean(weights, dim=-2, keepdim=True, unbiased=False)
   1820 weights = (weights - mean) / std
   1821 weights = _median_filter(weights, self.config.median_filter_width)

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by tringwald** [comment]
This should probably be added to @albanD 's [MPS op coverage list](https://github.com/pytorch/pytorch/issues/77764).

**Comment by malfet** [comment]
Can somebody tell me what's the different between `torch.std` and `torch.std_mean`?

**Comment by malfet** [comment]
Sometime ago I've added https://github.com/pytorch/pytorch/blob/c2a835d71023359d3fcf3657298413f2c36f93ed/torch/backends/mps/__init__.py#L53

So one can very easily add the same decomp for std_mean, but I wonder if doing it in C would be a tad faster. 

PR is coming

**Comment by malfet** [comment]
@rao-arimilli by the way, which version of whisper are you using? As for me it complains that sparse is not supported on MPS

**Comment by rao-arimilli** [comment]
> @rao-arimilli by the way, which version of whisper are you using? As for me it complains that sparse is not supported on MPS
> 
> Ok, I've removed `.to_sparse()` but can't reproduce missing std_mean

using openai/whisper-large-v2

**Comment by malfet** [comment]
@rao-arimilli what version of PyTorch and Whipser are you on?
