### ISSUE TITLE
How to deal with mypy checking fx_node.args[i].meta?

### ISSUE THREAD

**Issue by ColinPeppler** [pytorch/pytorch#119604]
# Issue
It's common in Inductor FX passes to do something like this
```
node: torch.fx.Node = ...
arg1: torch.fx.Argument = node.args[0]
arg2: torch.fx.Argument = node.args[1]
a, b = arg1.meta, arg2.meta
# do something with a & b
```

However, mypy will call this out ([see](https://mypy.readthedocs.io/en/stable/error_code_list.html#check-that-attribute-exists-in-each-union-item-union-attr)). It's checking that each attribute (i.e. `meta`) exists in each of the type listed for [fx.node.Argument](https://github.com/pytorch/pytorch/blob/a7f82b7d628eb2b966bc53e593dcf32049b2b10e/torch/fx/node.py#L26-L34).
```
Item ... of "tuple[Any, ...] | list[Any] | dict[str, Any] | slice | range | Node | str | int | float | bool | complex | dtype | Tensor | device | memory_format | layout | OpOverload | None" has no attribute "meta"  [union-attr]
```

# Workarounds
1. Do some runtime checks to assure mypy that it's okay. For eg:
    - `isinstance(arg1, torch.fx.Node)`
    - `if hasattr(arg1, 'meta):`
2. Slap on a # type: ignore[union-attr]
3. Surface a `node.args` getter method in fx/node.py. Illustrated in code below.
```
def get_arg(arg_type: Type[T], i: int) -> T:
  assert(isinstance(self.args[i], arg_type))
  return self.args[i]
```

# Thoughts
At the moment, (2), the slap on approach, seems to be present in quite a few places. Here's two examples ([1](https://github.com/pytorch/pytorch/pull/119085/files#diff-800bd8ca3e84db0b1988eb1c289bbe892b2acfcd013c2ff04117ce9bd5615480L346), [2](https://github.com/pytorch/pytorch/pull/119422/files#diff-118f7e6a8110f30c6894a530eea254b6cff4338add31d83825365b6cac47bdc5R368-R374)).
```
$ grep -P -rn "meta.* # type: ignore\[union-attr\]" torch/_inductor | wc -l
22
```

I think we could follow (1) everytime we want to call `node.args[0].meta` or handle this at a level lower like (3) surfacing a getter method. Or maybe there's a 4th option?

**Comment by ezyang** [comment]
There are two main things that come to mind.

First, the FX meta dict was intended to be open extension point to let people put whatever they want in it. So in some sense it is fundamentally untypeable. We could change out mind on this and say, well, this is a TypedDict and it had these fields and you are obligated to abide by it. We would specially canonize the fields we use in PT2.

A more flexible approach that allows for different users to have different meta is to have a custom casting function that refines the type of meta. You would call this function with meta, optionally it would do some runtime sanity checks, and the return result is a TypedDict. This would be more wordy but hopefully not too more wordy.

**Comment by ColinPeppler** [comment]
Whoops I should clarify. The primary issue is that `torch.fx.node.Argument` is a large union type, and we're trying to retrieve the `meta` attribute from it. That triggers mypy to check each member type for `meta`. A lot of the member types (e.g. str, torch.Tensor, slice) don't have `meta`, in fact, probably `torch.fx.Node` is the only one with `meta`. Thinking about this more, it makes sense to just run explicit runtime checks (i.e. `isinstance(arg, torch.fx.Node)`.

I think `meta` dict being fundamentally untypeable is another issue (and maybe not so much an issue after all).

Closing since I think my issue is now resolved :)
