### ISSUE TITLE
12 Dynamo test are failing with "cannot set WRITEABLE flag to True of this array".

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#119787]
12 Dynamo test are failing with "cannot set WRITEABLE flag to True of this array".

## Repro

`PYTORCH_TEST_WITH_DYNAMO=1 pytest nn/test_init.py -v -k test_xavier_uniform`

You will need to remove the skip or expectedFailure before running the repro command.
This may be just removing a line in
[dynamo_test_failures.py](https://github.com/pytorch/pytorch/blob/main/torch/testing/_internal/dynamo_test_failures.py)

## Failing tests

Here's a comprehensive list of tests that fail (as of this issue) with the above message:
<details>
<summary>Click me</summary>
```
nn/test_init.py::TestNNInit.test_xavier_uniform
test_torch.py::TestTorchDeviceTypeCPU.test_exponential_kstest_cpu_bfloat16
test_torch.py::TestTorchDeviceTypeCPU.test_exponential_kstest_cpu_float16
test_torch.py::TestTorchDeviceTypeCPU.test_exponential_kstest_cpu_float32
test_torch.py::TestTorchDeviceTypeCPU.test_exponential_kstest_cpu_float64
test_torch.py::TestTorchDeviceTypeCPU.test_normal_kstest_cpu_float16
test_torch.py::TestTorchDeviceTypeCPU.test_normal_kstest_cpu_float32
test_torch.py::TestTorchDeviceTypeCPU.test_normal_kstest_cpu_float64
test_torch.py::TestTorchDeviceTypeCPU.test_uniform_kstest_cpu_bfloat16
test_torch.py::TestTorchDeviceTypeCPU.test_uniform_kstest_cpu_float16
test_torch.py::TestTorchDeviceTypeCPU.test_uniform_kstest_cpu_float32
test_torch.py::TestTorchDeviceTypeCPU.test_uniform_kstest_cpu_float64
```

cc @mruberry @rgommers @ezyang @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by malfet** [comment]
Tentatively grabbing for myself

**Comment by malfet** [comment]
Ok, it happens when one tries to make ndarray writable when it returned from nd.iter
