### ISSUE TITLE
Build fails to find lapack

### ISSUE THREAD

**Issue by yurivict** [pytorch/pytorch#119754]
### 🐛 Describe the bug

When we attempt to build with USE_LAPACK=1 configure fails to find lapack:
```
-- Cannot find a library with LAPACK API. Not using LAPACK.
```

Blas is found but lapack isn't.

The library named ```liblapack.so``` is installed by lapack-3.12.0_2:
```
$ pkg which  /usr/local/lib/liblapack.so
/usr/local/lib/liblapack.so was installed by package lapack-3.12.0_2
```

FreeBSD 14.0
PyTorch is being built in the ports framework.

### Versions

2.1.2

**Comment by jbschlosser** [comment]
Hey @yurivict, this sounds like it may be an environment issue. I'd encourage you to post on the [PyTorch forums](https://discuss.pytorch.org/), as you'll have more luck there. Note that the issues here are reserved for issues within PyTorch itself. Closing for now but feel free to reopen if the discussion in the forums indicates a PyTorch bug.
