### ISSUE TITLE
Make `_pytree.tree_leaves` an iterator

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#119768]
### 🚀 The feature, motivation and pitch

It happened to me a couple of times that I wanted to gather an attribute of a leaf of a pytree like the first `n` dimensions or the device, when I knew that this attribute was shared between all the leaves (for instance because the input is itself the result of a pytree.tree_map call).

Currently, `tree_leaves` makes the full list of the leaves and returns it. An iterator would be useful in the above cases, e.g.
```python
for leaf in pytree.tree_leaves(my_pytree):
    return leaf.device
```
in the case where I want to know the device.

### Additional context

cc @zou3519

**Comment by zou3519** [comment]
seems reasonable to me, what say you @XuehaiPan?

**Comment by XuehaiPan** [comment]
Maybe we could add a new API `tree_leaves_iter` or `tree_iter` (similar to function `_pytree._tree_leaves_helper`):

```python
def tree_leaves_iter(
    tree: PyTree[T],
    is_leaf: Optional[Callable[[T], bool]] = None,
) -> Iterable[T]:
    ...

def tree_leaves(
    tree: PyTree[T],
    is_leaf: Optional[Callable[[T], bool]] = None,
) -> List[T]:
    return list(tree_leaves_iter(tree, is_leaf=is_leaf))
```

Then you can get the first leaf via:

```python
first_leaf = next(tree_leaves_iter(tree), None)
```
