### ISSUE TITLE
SDPA Pattern Match for hf-GPT2

### ISSUE THREAD

**Issue by sanchitintel** [pytorch/pytorch#119760]
### 🚀 The feature, motivation and pitch

[GPT-2 SDPA](https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt2/modeling_gpt2.py#L182-L220) pattern is not currently being matched by [Inductor pattern-matcher](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/fx_passes/fuse_attention.py). I tried adding a corresponding pattern but it looks like `l__mod___transformer_h_0_attn_bias[(slice(None, None, None), slice(None, None, None), slice(0, 256, None), slice(None, 256, None))]` is hindering its matching. Please suggest a way to match this pattern. Thanks!

#### Command to run hf-GPT2 with TorchBench
```
python benchmarks/dynamo/torchbench.py --performance --inference --inductor --float32 -dcpu --only hf_GPT2 --freezing
```

#### The portion of the graph corresponding to the SDPA pattern I'm trying to match, so that it can be replaced with a custom fusion -

```
    view_3 = getitem.view((1, 256, 12, 64));  getitem = None
    permute = view_3.permute(0, 2, 1, 3);  view_3 = None
    view_4 = getitem_1.view((1, 256, 12, 64));  getitem_1 = None
    permute_1 = view_4.permute(0, 2, 1, 3);  view_4 = None
    view_5 = getitem_2.view((1, 256, 12, 64));  getitem_2 = None
    permute_2 = view_5.permute(0, 2, 1, 3);  view_5 = None
    transpose = permute_1.transpose(-1, -2)
    matmul = torch.matmul(permute, transpose);  permute = transpose = None
    full = torch.full([], 8.0, dtype = torch.float32, device = device(type='cpu'))
    truediv = matmul / full;  matmul = full = None
    l__mod___transformer_h_0_attn_bias = self.L__mod___transformer_h_0_attn_bias
    getitem_3 = l__mod___transformer_h_0_attn_bias[(slice(None, None, None), slice(None, None, None), slice(0, 256, None), slice(None, 256, None))];  l__mod___transformer_h_0_attn_bias = None
    full_1 = torch.full([], -3.4028234663852886e+38, dtype = torch.float32)
    to = full_1.to(device(type='cpu'));  full_1 = None
    to_1 = truediv.to(torch.float32);  truediv = None
    where = torch.where(getitem_3, to_1, to);  getitem_3 = to_1 = to = None
    softmax = torch.nn.functional.softmax(where, dim = -1);  where = None
    type_1 = softmax.type(torch.float32);  softmax = None
    l__mod___transformer_h_0_attn_attn_dropout = self.L__mod___transformer_h_0_attn_attn_dropout(type_1);  type_1 = None
    matmul_1 = torch.matmul(l__mod___transformer_h_0_attn_attn_dropout, permute_2);  l__mod___transformer_h_0_attn_attn_dropout = None
    permute_3 = matmul_1.permute(0, 2, 1, 3);  matmul_1 = None
    contiguous = permute_3.contiguous();  permute_3 = None
    view_6 = contiguous.view((1, 256, 768));  contiguous = None
```

#### The pattern I'm trying to match -

```
[query]    [key]
     \    /
permute  permute
      \  /
  MatMul [scale]
      \   /
       Div    
[mask] | [mask value]
    \  |  /           
     Where         [value]
       |             /
   Softmax     permute
        \          /
     dropout  transpose      
     /      \    /
[output 2]   MatMul
               |
           permute
               |
        contiguous
               |
          [output 1]

```

### Alternatives

Please suggest an alternative to add a new SDPA pattern corresponding to GPT2's MHA pattern, so that it can be replaced with a custom fusion on CPU. Thanks!

### Additional context

https://github.com/pytorch/pytorch/pull/97741 added a way to replace attention patterns with fused ops before post-grad passes.

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by eellison** [comment]
The first thing we do in freezing is run joint graph passes which include SDPA : https://github.com/pytorch/pytorch/blob/main/torch/_inductor/compile_fx.py#L1023. 

 I don't think this is a freezing issue. We are not matching this particular SDPA for other reasons.

**Comment by eellison** [comment]
Confirmed does not match without freezing either. @sanchitintel the patterns are not applied at that level of the IR. They are applied on the joint graph.

**Comment by sanchitintel** [comment]
Hi @eellison, thanks for your help!

Please advise if the GPT2 MHA pattern would be more amenable to matching in some custom pattern-matching pass after freezing, or if there's some way to match it (after adding its corresponding pattern in `torch/_inductor/fx_passes/fuse_attention.py`) in joint graph passes as well. Thank you!

BTW, I noticed that the SDPA pattern-matcher is not matching some other custom patterns as well.
For example, I [tried adding the MHA pattern of `BERT_pytorch` (which is used by TorchBench)](https://github.com/pytorch/pytorch/compare/main...sanchitintel:pytorch:sanchitj/sdpa_pattern_example), just to verify if it matches itself (by setting a breakpoint in its bogus replacement and running the following python script), but it did not match :

```python
import torch

def BERT_pytorch_mha_pattern(query, key, value, attn_mask, inv_scale_factor, dropout_p):
    q = query.permute(0, 2, 1, 3)
    k = key.permute(0, 2, 1, 3)
    v = value.permute(0, 2, 1, 3)
    scores = torch.matmul(q, k.transpose(-2, -1)).div(inv_scale_factor)
    fill_value = torch.full((), -float(1000000000.0), dtype=query.dtype, device=query.device)
    scores = scores.masked_fill(attn_mask == 0, fill_value)   
    return torch.nn.functional.dropout(
        scores.softmax(dim=-1), dropout_p
    ).matmul(v)

with torch.no_grad():
    q = torch.randn(2, 256, 12, 64)
    k = torch.randn(2, 256, 12, 64)
    v = torch.randn(2, 256, 12, 64)
    BERT_pytorch_mha_model = torch.compile(BERT_pytorch_mha_pattern, fullgraph=True, options={"freezing": True})
    BERT_pytorch_mha_model(q, k, v, torch.rand(2, 12, 256, 256).to(torch.bool), torch.full((),8.0), 0)
    BERT_pytorch_mha_model(q, k, v, torch.rand(2, 12, 256, 256).to(torch.bool), torch.full((),8.0), 0)
```

Could you please advise how I could modify it to make it match with itself? That'd help me develop an intuition regarding pattern-matching. Thanks again!

**Comment by sanchitintel** [comment]
Hi @eellison, the above `BERT_pytorch` pattern actually matched the SDPA pattern while running that workload. I added details in #119911.
It looks like my test script above somehow works differently from SDPA pattern-matching UTs, so I should've used those UTs instead.
I'll try matching the GPT2 SDPA pattern as well & will try replacing it with a custom fusion. If I'd succeed, then I'd update this ticket & close this issue. Thanks!

**Comment by sanchitintel** [comment]
Hi @eellison @jansel,

I tried matching the [hf_GPT2 SDPA pattern](https://github.com/pytorch/pytorch/compare/main...sanchitintel:pytorch:gpt2_sdpa_pattern?expand=1) again (so that I could replace it with a custom fusion for CPU), but its matching failed.

Please correct me if I'm wrong, as that'd help me understand how pattern-matching works - I think that the following differences between the serialized pattern & the graph of `hf_GPT2` at runtime should not have mattered during matching (i.e. the lines that I commented with a leading `#` character correspond to nodes that would have been outside the subgraph of the pattern I tried adding in [`torch/_inductor/fx_passes/fuse_attention.py`](https://github.com/sanchitintel/pytorch/blob/82a42958af18d502ceb69e525f6545de0cde3e10/torch/_inductor/fx_passes/fuse_attention.py#L451-L465), which should have matched the [serialized pattern](https://github.com/sanchitintel/pytorch/blob/82a42958af18d502ceb69e525f6545de0cde3e10/torch/_inductor/fx_passes/serialized_patterns/_sfdp_pattern_18.py#L106-L134). -

<img width="1861" alt="image" src="https://github.com/pytorch/pytorch/assets/90872293/5fbfc6bf-8240-4fb8-9081-9e58914369d3">

Thank you!

**Comment by sanchitintel** [comment]
Sorry for the inconvenience! I was able to match the pattern by fixing a bug in it (`where` invocation was incorrect - the order of arguments had been swapped), and by having multiple outputs (also outputting `key` & `value`), since the `hf_GPT2` TorchBench workload also returns it.
