### ISSUE TITLE
Dynamo doesn't properly guard on classes when used to construct intermediates

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#119715]
### 🐛 Describe the bug

Basically we don't guard that T is the class that we expect. We track the mutation on it and generate code to set `x` properly but I think we miss the case where the scope is the current script. 

```
import torch

class T:
    def __init__(self, x):
        self.x = x

@torch.compile()
def fn(x):
    o = T(5)
    return o, x + 1

fn(torch.ones(1, 1))
T = 5
fn(torch.ones(1, 1))
```
Traceback (most recent call last):
  File "/opt/dlami/nvme/mlazos/test/t.py", line 17, in <module>
    fn(torch.ones(1, 1))
  File "/opt/dlami/nvme/mlazos/pytorch/torch/_dynamo/eval_frame.py", line 454, in _fn
    return fn(*args, **kwargs)
  File "/opt/dlami/nvme/mlazos/test/t.py", line 9, in fn
    @torch.compile()
TypeError: object.__new__(X): X is not a type object (int)

### Versions

663dd5d0066664c29e2ecede7ec70bcf71e25133

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

**Comment by jbschlosser** [comment]
Do we want to guard on the exact type? I could see some value from duck typing in guards, as long as we avoid errors like the above.

**Comment by mlazos** [comment]
Basically what's happening is we instantiate `T` in our bytecode and we need to make sure it's the same type as when we traced. We can either guard to ensure it is, or stash `T` and use the stashed version vs the one stored in the global name `T`.

**Comment by masnesral** [comment]
@mlazos is it appropriate for me to mark this as hi-pri (I'm oncall this week)

**Comment by mlazos** [comment]
@masnesral yeah we can make it high pri because it's a crash
