### ISSUE TITLE
Check the type of grad given to backward and assigned to .grad

### ISSUE THREAD

**Issue by woofie56** [pytorch/pytorch#1198]
The following works : 

```
import numpy as np
import torch
from torch.autograd import Variable

x = torch.from_numpy(np.array([1.,2.,3.]))
x = Variable(x, requires_grad=True)
y = x * 2
gradients = torch.FloatTensor([1, 1, 1])
y.backward(gradients)
```
However the following yields an error (notice I have `y = x * x` instead of `y = x * 2`) : 

```
import numpy as np
import torch
from torch.autograd import Variable

x = torch.from_numpy(np.array([1.,2.,3.]))
x = Variable(x, requires_grad=True)
y = x * x
gradients = torch.FloatTensor([1, 1, 1])
y.backward(gradients)
```
saying : 

```
TypeError: mul received an invalid combination of arguments - got (torch.DoubleTensor), but expected one of:
 * (float value)
 * (torch.FloatTensor other)

```
This can be fixed by using `x = torch.from_numpy(np.array([1.,2.,3.],dtype=np.float32))` instead of `x = torch.from_numpy(np.array([1.,2.,3.]))`. But why does the first example not require this change, whereas the second example requires it?

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by apaszke** [comment]
You're mixing up the types and in the first case the assigned gradient will be a `FloatTensor` instead of a `DoubleTensor`, so once you try to accumulate it into `x` it will likely blow up. But it's worth adding checks to raise errors earlier.

**Comment by albanD** [comment]
Not a problem on master anymore. The gradients are double in both cases (I guess type promotion saves the day here).
Please re-open if you see other similar issue.
