### ISSUE TITLE
FLOP Counter utility seems incorrect for ConvTranspose2d backward

### ISSUE THREAD

**Issue by ErnestChan** [pytorch/pytorch#119806]
### 🐛 Describe the bug

The flop counter utility at https://github.com/pytorch/pytorch/blob/release/2.1/torch/utils/flop_counter.py
is very useful. Thanks @Chillee for adding it. However, the flops calculation for Conv Transpose backward seems to wildly overestimate the flops.

Example script I ran on H100:
```python
import time
import torch
from torch.utils.flop_counter import FlopCounterMode


if __name__ == "__main__":
    x = torch.rand(6, 192, 30, 96, device="cuda")
    model = torch.nn.ConvTranspose2d(192, 384, (2, 2), stride=2).to("cuda")

    with FlopCounterMode(model):
        start = time.time()
        for i in range(500):
            out = model(x)
            out.sum().backward()

        torch.cuda.synchronize()
        print(f"Elapsed: {time.time() - start}")
```

The output is:
```
Elapsed: 0.5621950626373291
Module                                FLOP    % Total
----------------------------  ------------  ---------
ConvTranspose2d               3677792.061T  25050.00%
 - aten.convolution              1276.568T      8.69%
 - aten.convolution_backward  3676515.493T  25041.31%
 ```
Which implies the loop had 3,677,792.061T / 0.562 =  6,544,113 TFLOPs / s, which is much higher than the peak FLOPs /s on an H100 GPU.

### Versions

Pytorch 2.1

cc @albanD

**Comment by Chillee** [comment]
There were actually 2 bugs here. One with the backwards formula of transposed convs, and one with the hierarchy not being properly cleared in a certain edge case (that's pretty common).

However, I believe I did solve it properly this time (https://github.com/pytorch/pytorch/pull/119874), and as a bonus, I have a pretty nifty implementation of the backwards convolution using only forwards convolution ops: https://github.com/pytorch/pytorch/pull/119874/files#diff-0ad9664f84f6fa5581dc539d83eded5d7c827491f6d2f43943898da16a14f6baR137

**Comment by ErnestChan** [comment]
Thanks, excited to try the new version!
