### ISSUE TITLE
[feature request]Please go back to the old theme

### ISSUE THREAD

**Issue by noeagles** [pytorch/pytorch#11986]
The new theme of docs and tutorials is very confusing and makes it extreme difficult to read on a PC monitor. At very least please allow users to switch theme as they mat prefer.

**Comment by hfutzzw** [comment]
actually, the background and foreground is so confused, and I feel hard to read in such a theme.

**Comment by zou3519** [comment]
Please comment your support / feedback in #11968. Closing this issue because it is a duplicate.
