### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator aten::pixel_shuffle

### ISSUE THREAD

**Issue by phalexo** [pytorch/pytorch#11981]
Ubuntu 14.04, CUDA 9.2, CUDNN 7.1.4, Python 3.6, PyTorch 1.0

Trying out exporting to Caffe2 https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html

>>> x.shape
torch.Size([64, 1, 224, 224])
>>> torch_out = torch.onnx._export(torch_model,             # model being run
...                                x,                       # model input (or a tuple for multiple inputs)
...                                "super_resolution.onnx", # where to save the model (can be a file or file-like object)
...                                export_params=True)      # store the trained

/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator pixel_shuffle because torch.onnx.symbolic.pixel_shuffle does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/onnx/__init__.py", line 22, in _export
    return utils._export(*args, **kwargs)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py", line 286, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::pixel_shuffle

Defined at:
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/pixelshuffle.py(40): forward
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py(465): _slow_forward
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py(475): __call__
/home/developer/examples-pytorch/super_resolution/model.py(23): forward
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py(465): _slow_forward
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py(475): __call__
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/jit/__init__.py(146): forward
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py(477): __call__
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/jit/__init__.py(115): get_trace_graph
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py(191): _trace_and_get_graph_from_model
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py(223): _model_to_graph
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py(280): _export
/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/onnx/__init__.py(22): _export
<stdin>(4): <module>

Graph we tried to export:
graph(%0 : Float(64, 1, 224, 224)
      %1 : Float(64, 1, 5, 5)
      %2 : Float(64)
      %3 : Float(64, 64, 3, 3)
      %4 : Float(64)
      %5 : Float(32, 64, 3, 3)
      %6 : Float(32)
      %7 : Float(9, 32, 3, 3)
      %8 : Float(9)) {
  %9 : Float(64, 64, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[2, 2, 2, 2], strides=[1, 1]](%0, %1, %2), scope: Net/Conv2d[conv1]
  %10 : Float(64, 64, 224, 224) = onnx::Relu(%9), scope: Net/ReLU[relu]
  %11 : Float(64, 64, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%10, %3, %4), scope: Net/Conv2d[conv2]
  %12 : Float(64, 64, 224, 224) = onnx::Relu(%11), scope: Net/ReLU[relu]
  %13 : Float(64, 32, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%12, %5, %6), scope: Net/Conv2d[conv3]
  %14 : Float(64, 32, 224, 224) = onnx::Relu(%13), scope: Net/ReLU[relu]
  %15 : Float(64, 9, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%14, %7, %8), scope: Net/Conv2d[conv4]
  %16 : Long() = onnx::Constant[value={3}]()
  %17 : Float(64, 1, 672, 672) = aten::pixel_shuffle(%15, %16), scope: Net/PixelShuffle[pixel_shuffle]
  return (%17);
}

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by arogowie-intel** [comment]
Having same issue.

**Comment by mali-nuist** [comment]
same problem

**Comment by mali-nuist** [comment]
> I am having the exact same issue.
> **Platform**: `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04`
> PyTorch compiled from master using the provided Dockerfile script.
> ONNX and ONNX-Caffe2 installed via conda
> `conda install -c ezyang onnx onnx-caffe2`
> 
> ```
> >> conda list
> ...
> onnx                      0.2.1            py36h7954c55_1    ezyang
> onnx-caffe2               0.2.1            py36h71a8c3b_1    ezyang
> ...
> torch                     1.0.0a0+21ed7e5           <pip>
> torchvision               0.2.1                     <pip>
> ```
> **Error**
> `UserWarning: ONNX export failed on ATen operator pixel_shuffle because torch.onnx.symbolic.pixel_shuffle does not exist`
> 
> **Log output**
> 
> ```
> # python super_resolution_with_caffe2.py                                 
> Downloading: "https://s3.amazonaws.com/pytorch/test_data/export/superres_epoch100-44c6958e.pth" to /root/.torch/models/superres_epoch100-44c6958e.pth
> 100%|##################################################################| 239691/239691 [00:00<00:00, 347694.80it/s]
> /opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator pixel_shuffle because torch.onnx.symbolic.pixel_shuffle does not exist
>   .format(op_name, op_name))
> Traceback (most recent call last):
>   File "super_resolution_with_caffe2.py", line 116, in <module>
>     export_params=True)      # store the trained parameter weights inside the model file
>   File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 22, in _export
>     return utils._export(*args, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 286, in _export
>     proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
> RuntimeError: ONNX export failed: Couldn't export operator aten::pixel_shuffle
> 
> Defined at:
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/pixelshuffle.py(40): forward
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(465): _slow_forward
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(475): __call__
> super_resolution_with_caffe2.py(63): forward
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(465): _slow_forward
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(475): __call__
> /opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py(146): forward
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(477): __call__
> /opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py(115): get_trace_graph
> /opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py(191): _trace_and_get_graph_from_model
> /opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py(223): _model_to_graph
> /opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py(280): _export
> /opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py(22): _export
> super_resolution_with_caffe2.py(116): <module>
> 
> 
> Graph we tried to export:
> graph(%0 : Float(1, 1, 224, 224)
>       %1 : Float(64, 1, 5, 5)
>       %2 : Float(64)
>       %3 : Float(64, 64, 3, 3)
>       %4 : Float(64)
>       %5 : Float(32, 64, 3, 3)
>       %6 : Float(32)
>       %7 : Float(9, 32, 3, 3)
>       %8 : Float(9)) {
>   %9 : Float(1, 64, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[2, 2, 2, 2], strides=[1, 1]](%0, %1, %2), scope: SuperResolutionNet/Conv2d[conv1]
>   %10 : Float(1, 64, 224, 224) = onnx::Relu(%9), scope: SuperResolutionNet/ReLU[relu]
>   %11 : Float(1, 64, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%10, %3, %4), scope: SuperResolutionNet/Conv2d[conv2]
>   %12 : Float(1, 64, 224, 224) = onnx::Relu(%11), scope: SuperResolutionNet/ReLU[relu]
>   %13 : Float(1, 32, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%12, %5, %6), scope: SuperResolutionNet/Conv2d[conv3]
>   %14 : Float(1, 32, 224, 224) = onnx::Relu(%13), scope: SuperResolutionNet/ReLU[relu]
>   %15 : Float(1, 9, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%14, %7, %8), scope: SuperResolutionNet/Conv2d[conv4]
>   %16 : Long() = onnx::Constant[value={3}]()
>   %17 : Float(1, 1, 672, 672) = aten::pixel_shuffle(%15, %16), scope: SuperResolutionNet/PixelShuffle[pixel_shuffle]
>   return (%17);
> }
> ```

same problem

**Comment by spandantiwari** [comment]
@phalexo @mali-nuist - We have support for pixel shuffle since opset 11 (https://github.com/pytorch/pytorch/blob/ee4ce8e9d9a439b9a87fcfa6abdcb0f7f3f62b11/torch/onnx/symbolic_opset11.py#L155). I'd recommend trying with the latest version of PyTorch. Feel free to reopen this item if there's any issue.
