### ISSUE TITLE
PGNCCL: some ProfilingTitle strings are unsafe and corruption prone

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#119808]
lines like this 
`c10::str("nccl:send ", rank_, "->", dstRank).c_str());`
pass a pointer to immediately free'd memory.  Downstream usage such as flightrecorder can end up copying a garbage string. This has led to corrupted (unparsable) data in FlightRecorder logs.

if you got a FlightRecorder log containing a `profiling_name` field with garbage unparsable data, you can work around it using https://www.internalfb.com/phabricator/paste/view/P1183952447 cc @zdevito 

cc @shuqiangzhang

**Comment by shuqiangzhang** [comment]
guess entry could just store a copy std::string

**Comment by wconstab** [comment]
as a nice to have, we might also create strings up front once as constants when possible.  (i guess that's not possible if including 'rank' in the send though)
