### ISSUE TITLE
There is a performance drop because we have not yet implemented the batching rule for aten::lu_unpack

### ISSUE THREAD

**Issue by RodrigoIbata** [pytorch/pytorch#119998]
### 🚀 The feature, motivation and pitch

Please add batching rules for LU matrix decomposition. This functionality is extremely useful, and vmap with functional_call  is the only way to implement certain accurate second-order optimizers in an efficient way.
The performance gain would be large and facilitate physics modelling problems.

### Alternatives

I have tried torch.linalg.lu as a potential workaround, but the batching rule is also not implemented yet.

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano @zou3519

**Comment by lezcano** [comment]
cc @guilhermeleobas for a few more simpler batching rules.
