### ISSUE TITLE
Unable to do backward for customized operators

### ISSUE THREAD

**Issue by leslie-fang-intel** [pytorch/pytorch#119957]
### 🐛 Describe the bug
In https://github.com/pytorch/pytorch/blob/main/torch/ao/quantization/fx/_decomposed.py, we provide some customized operators for quantization. We may need to add more like fake quant operators. However, we found this operator can do backward in eager mode but failed with `torch.compile`.

### Error logs

Error log is: `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

### Minified repro

- PyTorch (which has the customized operator defined to do test): Based on PyTorch Master: 6620176da73ab0e39ff50d6067dfde91aa4b7351 and apply the patch [61bfda0d7eaf9238d07e7fd4535011d93b004e9f](https://github.com/leslie-fang-intel/pytorch/commit/61bfda0d7eaf9238d07e7fd4535011d93b004e9f)
- Example code: https://gist.github.com/leslie-fang-intel/3bda9113afa59fbee42b1cce35f22091

### Versions

```
Collecting environment information...
PyTorch version: 2.3.0a0+git6620176
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.17

Python version: 3.9.10 (main, Mar  2 2022, 12:02:00)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-4.19.5-1.el7.elrepo.x86_64-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    1
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel Genuine CPU
Stepping:              10
CPU MHz:               1344.204
CPU max MHz:           2900.0000
CPU min MHz:           1200.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27
NUMA node1 CPU(s):     28-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-coding==1.3.3
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] intel-extension-for-pytorch==2.3.0+gitb24f2f4
[pip3] mypy==1.8.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] torch==2.3.0a0+git9201d73
[pip3] torchao==0.0.3
[pip3] torchvision==0.16.0a0+370134
[pip3] triton==2.0.0
[conda] mkl                       2023.0.0            intel_25398    intel
[conda] mkl-include               2023.0.0            intel_25398    intel
[conda] mkl-include               2023.0.0                  <pip>
[conda] mkl-service               2.4.0           py39h3605609_14    intel
[conda] mkl-static                2023.0.0                  <pip>
[conda] mkl_fft                   1.3.1           py39hcab1719_22    intel
[conda] mkl_random                1.2.2           py39hbf47bc3_22    intel
[conda] mkl_umath                 0.1.1           py39hf66a691_32    intel
[conda] numpy                     1.26.0                    <pip>
[conda] numpy                     1.22.3           py39hf0956d0_5    intel
[conda] numpy-base                1.22.3           py39h45c9ace_5    intel
[conda] torchvision               0.16.0a0+370134           <pip>
[conda] triton                    2.0.0                     <pip>

```

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by leslie-fang-intel** [comment]
Hi @eellison, @jerryzh168 told me you may be familiar with it. Could you kindly help on this issue?

**Comment by eellison** [comment]
For custom ops - @zou3519 is probably best person. But would it be possible for you to provide repro here ?

**Comment by leslie-fang-intel** [comment]
> For custom ops - @zou3519 is probably best person. But would it be possible for you to provide repro here ?

Thanks and here are the repro:

- PyTorch (which has the customized operator defined to do test): Based on PyTorch Master: https://github.com/pytorch/pytorch/commit/6620176da73ab0e39ff50d6067dfde91aa4b7351 and apply the patch [61bfda0d7eaf9238d07e7fd4535011d93b004e9f](https://github.com/leslie-fang-intel/pytorch/commit/61bfda0d7eaf9238d07e7fd4535011d93b004e9f)

- Example code: https://gist.github.com/leslie-fang-intel/3bda9113afa59fbee42b1cce35f22091

**Comment by zou3519** [comment]
Your op "quantized_decomposed.test_backward" does not have a backward formula. Here's an example of how to add one: https://gist.github.com/zou3519/213808aae9e6972941fe4790f21ead3f. This is not really a bug or a feature request, so I'll close this issue if you agree.

**Comment by leslie-fang-intel** [comment]
Thanks for the comment. I will take a try with your suggestions.

**Comment by leslie-fang-intel** [comment]
Thanks for the suggestions @zou3519. After trying your example code, it works now.
* PyTorch: https://github.com/leslie-fang-intel/pytorch/commit/eef83b74c6bd84cec535739f059657c81d1a0961
* Example Code: https://gist.github.com/leslie-fang-intel/3bda9113afa59fbee42b1cce35f22091
