### ISSUE TITLE
hi ,could you help 

### ISSUE THREAD

**Issue by jackylee1** [pytorch/pytorch#11990]
i simply pull the image with nvidia-docker run --rm -ti --ipc=host pytorch/pytorch:latest
on my mac ,the version is 10.13.6 and with the Intel HD Graphics 6000
i want to build pytorch with cuda support.but it failed with following error 
Step 4/12 : RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  &&      chmod +x ~/miniconda.sh &&      ~/miniconda.sh -b -p /opt/conda &&      rm ~/miniconda.sh &&      /opt/conda/bin/conda install -y python=$PYTHON_VERSION numpy pyyaml scipy ipython mkl mkl-include cython typing &&      /opt/conda/bin/conda install -y -c pytorch magma-cuda90 &&      /opt/conda/bin/conda clean -ya
 ---> Running in 82dbab749b36
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0curl: (6) Could not resolve host: repo.continuum.io
The command '/bin/sh -c curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  &&      chmod +x ~/miniconda.sh &&      ~/miniconda.sh -b -p /opt/conda &&      rm ~/miniconda.sh &&      /opt/conda/bin/conda install -y python=$PYTHON_VERSION numpy pyyaml scipy ipython mkl mkl-include cython typing &&      /opt/conda/bin/conda install -y -c pytorch magma-cuda90 &&      /opt/conda/bin/conda clean -ya' returned a non-zero code: 6

**Comment by zou3519** [comment]
Could you please use the issue template and provide some additional context?

It looks like you can't get  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
