### ISSUE TITLE
Complicated guards probably are being repeatedly issued

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119917]
### 🐛 Describe the bug

@lezcano @avikchaudhuri and I were reading the symbolic shapes code and it occurred to us that if you have a complex evaluate_expr call which doesn't successfully maybe_guard_eq handled, it is possible we will add the guard every time you guard on it.

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by masnesral** [comment]
@ezyang should we discuss at the next triage review?

**Comment by ezyang** [comment]
nah, we know what's going on, just have to do it
