### ISSUE TITLE
Consecutive 1-d tensor indices are not supported.

### ISSUE THREAD

**Issue by arko-sarkar** [pytorch/pytorch#119993]
### 🐛 Describe the bug

```
torch.onnx.export(
        torch_model,  # model being run
        dummy_input,  # model input (or a tuple for multiple inputs)
        "legacy_model_dynamic_axes_bsz_4.onnx",  
        opset_version=16,  # the ONNX version to export the model to
        verbose=True,
        do_constant_folding=True,
        input_names=["input_0", "input_1", "input_2", "input_3", "input_4", "input_5", "input_6", "input_7"],
        output_names=["output"],
        dynamic_axes={
            "input_0": {0:'batch'},
            "input_1": {0:'batch'},
            "input_2": {0:'batch'},
            "input_3": {0:'batch'},
            "input_4": {0:'batch'},
            "input_5": {0:'batch'},
            "input_6": {0:'batch'},
            "input_7": {0:'batch'},
        },
    )
```

Export of model to ONNX causes gives error.
return torch._C._jit_onnx_convert_pattern_from_subblock(block, node, env)
RuntimeError: Only consecutive 1-d tensor indices are supported in exporting aten::index_put to ONNX.Check https://pytorch.org/docs/stable/onnx.html#indexing for details

If I set operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, then onnx gets generated but fails in tensorrt compilation for op_type : "Aten" index_put_

### Versions

pytorch build 2.2.0

**Comment by thiagocrepaldi** [comment]
Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

Without a full repro, we can't work on it
