### ISSUE TITLE
`searchsorted` confusing default arguments

### ISSUE THREAD

**Issue by mattbarrett98** [pytorch/pytorch#119999]
### 📚 The doc issue

The docs for `torch.searchsorted` https://pytorch.org/docs/stable/generated/torch.searchsorted.html show a default argument of `side='left'`. They also state that `It will error if side is set to “left” while this is True` ("this" being `right`). 

However, something like this `torch.searchsorted(x, x, right=True)` will work, even though in this case `right=True` and `side` has its default value `left`. So shouldn't this fail, or am I missing something?

cc @svekars @brycebortree

**Comment by malfet** [comment]
Thank you for reporting, function signature for side should be `Optional[str] = None`
Fix is coming
