### ISSUE TITLE
[Documentation enhancement]: bold font for better readability for left panel

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#11994]
For current [documentation](https://pytorch.org/docs/master/nn.html), the font on the left panel is quite shallow and a bit hard to read. It might be nice to make it darker to improve the readability.

**Comment by vishwakftw** [comment]
Duplicate of https://github.com/pytorch/pytorch/issues/11968 .

**Comment by zou3519** [comment]
Closing because duplicate, please feel free to comment in that thread @zuoxingdong
