### ISSUE TITLE
ImportError: No module named future.utils

### ISSUE THREAD

**Issue by alsrgv** [pytorch/pytorch#11995]
Commit https://github.com/pytorch/pytorch/commit/c22dcc266ff29e71f5d0d2ddacb9362ddef062d7 introduced a dependency on the package `future`. Since the `torch` package does not declare a dependency on `future`, this error happens.

```
# python
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch.utils.cpp_extension import include_paths
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/cpp_extension.py", line 13, in <module>
    from future.utils import raise_from
ImportError: No module named future.utils
>>>
```

**Comment by alsrgv** [comment]
cc @goldsborough @soumith

**Comment by goldsborough** [comment]
We have `future` in our `requirements.txt`: https://github.com/pytorch/pytorch/blob/master/requirements.txt#L1
It came as a requirement for caffe2. It generally seems useful to have, but I can also work around it if we feel we shouldn't be using it. @soumith

**Comment by alsrgv** [comment]
That's odd.  It's not getting installed as part of `pip install torch`. Quick repro:

```
$ docker run -it --network=host debian:jessie
# apt update -qq
# apt install -y python2.7 python2.7-dev python-pip python-requests
# pip install -U pip
# /usr/local/bin/pip install torch_nightly -v -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
# /usr/local/bin/pip freeze | grep future
```

**Comment by alsrgv** [comment]
Do you guys think this can be resolved before the 1.0 release?

**Comment by soumith** [comment]
@alsrgv yes we'll resolve this before the 1.0 final release. @goldsborough will close this soon.

**Comment by alsrgv** [comment]
@soumith, @goldsborough, excellent, thanks!

**Comment by daudakhtar** [comment]
sudo pip install future
          or
easy_install future
