### ISSUE TITLE
[Installation]: add `latest` whl file in `view-source:https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#12005]
In the [pip file of nightly installation](https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html), it would be very convenient to add a `latest` wheel file, so it is easy to keep some script file (e.g. for CI) without changing. 
i.e. `https://download.pytorch.org/whl/nightly/cpu/torch_nightly-latest-cp37-cp37m-linux_x86_64.whl`

**Comment by pjh5** [comment]
You can use pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html for the latest version.
