### ISSUE TITLE
[Caffe2] installing without root 

### ISSUE THREAD

**Issue by AyeshaNirma** [pytorch/pytorch#12008]
Guys, I was wondering if it is possible to install caffe2 without root permission or anyone has done it ?

**Comment by bddppq** [comment]
Yes if you install caffe2 to non-system location then you normally don't need root:
1. If you install through setup.py, do it inside a python virtualenv or conda virtualenv
2. If you install through cmake, add `-DCMAKE_INSTALL_PREFIX=your/custom/path` flag to cmake
