### ISSUE TITLE
DISABLED test_timeout_dumps_on_stuck_ranks (__main__.NCCLTraceTestTimeoutDumpOnStuckRanks)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#120034]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22distributed%2Ftest_c10d_nccl.py%3A%3ANCCLTraceTestTimeoutDumpOnStuckRanks%3A%3Atest_timeout_dumps_on_stuck_ranks%22%5D)).

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by hongxiayang** [comment]
close as this is fixed by @jeffdaily

**Comment by atalman** [comment]
Failing on Trunk: distributed/test_c10d_nccl.py::NCCLTraceTestTimeoutDumpOnStuckRanks::test_timeout_dumps_on_stuck_ranks [GH job link](https://github.com/pytorch/pytorch/actions/runs/10102378389/job/27939971470) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/709ddf7a9dcfa1268848b72f6f56b55afa6728d6)
