### ISSUE TITLE
UNSTABLE periodic / linux-focal-rocm6.0-py3.8 / test (distributed)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#120032]
Same as https://github.com/pytorch/pytorch/issues/119908

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
@huydhn would it be possible to have wildcards in unstable job tasks instead of creating 3 tasks to mark rocm unstable?

**Comment by jeffdaily** [comment]
And in a few hours I'll be creating more issues to DISABLE, one for each workflow.

**Comment by jeffdaily** [comment]
No timeouts observed on ROCm runners since network upgrade.  However, a number of tests are observed failing.  Will remain open until tests stabilize.

**Comment by jeffdaily** [comment]
Finally skipped enough tests with DISABLED issues to get periodic distributed tests back to passing.
