### ISSUE TITLE
pytorch installation ubuntu?

### ISSUE THREAD

**Issue by sarmad05** [pytorch/pytorch#12009]
Hi all, 
I am trying to setup fastai in my ubuntu operating system. I am all ok with other things like cuda 9.0, cudnn 7.** and anaconda. When i try to run "conda env update" it start updating packages required for fastai to run. But there was a problem download and extracting pytorch due to my unstable internet connection. Then i have downloaded the same exact version from different internet connection and trying to install it manually in anaconda pkgs. I have copy the pytorch into anaconda/pkgs folder and extract it there manually. But whenever i try to create the environment in anaconda it again start downloading the pytorch which is already extracted in the pkgs folder.
Kindly help me to resolve this issue. 
I am using pytorch 0.30, cuda 9.0 and cudnn 7.3. Ubuntu 16.04

**Comment by zou3519** [comment]
Try a pip installation maybe. See https://pytorch.org/ for more details

**Comment by bhushan23** [comment]
You can't just rely of extracting package in the respective conda folder, need to make entries is respective pth file. Refer to this answer on stackoverflow https://stackoverflow.com/questions/37006114/anaconda-permanently-include-external-packages-like-in-pythonpath
