### ISSUE TITLE
Building from source on windows 10 - 67000 warnings and 12 link errors - 6 mpi and 6 other

### ISSUE THREAD

**Issue by terrylyons** [pytorch/pytorch#12001]
Hi, the information you supply, and I followed for building in windows, install anaconda,  and various packages, as per your web site, and then used the short script you suggested. 

For me at least, although it takes 5 hours!! it finally fails - the error part is pasted below. I had already tweaked the script on your web page as I use cuda 9.0 and the compiler refused to find the toolset for 2017 if I had the 2015 path identified in the environmental variable as you suggest in your script fragment (perhaps you should have an if statement somewhere?). The machine is a heavily loaded development laptop with a k2100m gpu. As this only has compute 3.0 I need to build pytorch. Anyway, I have AVX2 etc. so it is a good thing to do. 

The laptop has mpi and Boost finds it when I build boost. It has the full intel compilers, All recent versions of visual studio,  mkl etc. Happy to tell more but maybe it is obvious to you what the issues are.

I am using python setup.py install from the base distribution of anaconda and python 3.6
(I would prefer to say python -m pip wheel xxxx if that were possible). 

I would much prefer to not use anaconda but I am because you say so.

Thanks !

Terry

"C:\temp\build_torch\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"C:\temp\build_torch\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\temp\build_torch\pytorch\build\caffe2\AlgorithmsTest.vcxproj" (default target) (4) ->
"C:\temp\build_torch\pytorch\build\caffe2\caffe2_gpu.vcxproj" (default target) (21) ->
(Link target) ->
  mpi_ops_gpu.obj : error LNK2019: unresolved external symbol MPI_Comm_size referenced in function "public: static void
 __cdecl caffe2::TypeMeta::_Ctor<class caffe2::MPICommonWorldWrapper>(void *,unsigned __int64)" (??$_Ctor@VMPICommonWor
ldWrapper@caffe2@@@TypeMeta@caffe2@@SAXPEAX_K@Z) [C:\temp\build_torch\pytorch\build\caffe2\caffe2_gpu.vcxproj]
  mpi_ops_gpu.obj : error LNK2019: unresolved external symbol MPI_Comm_rank referenced in function "public: static void
 __cdecl caffe2::TypeMeta::_Ctor<class caffe2::MPICommonWorldWrapper>(void *,unsigned __int64)" (??$_Ctor@VMPICommonWor
ldWrapper@caffe2@@@TypeMeta@caffe2@@SAXPEAX_K@Z) [C:\temp\build_torch\pytorch\build\caffe2\caffe2_gpu.vcxproj]
  mpi_ops_gpu.obj : error LNK2019: unresolved external symbol MPI_Comm_split referenced in function "public: static voi
d __cdecl caffe2::TypeMeta::_Ctor<class caffe2::MPICommonWorldWrapper>(void *,unsigned __int64)" (??$_Ctor@VMPICommonWo
rldWrapper@caffe2@@@TypeMeta@caffe2@@SAXPEAX_K@Z) [C:\temp\build_torch\pytorch\build\caffe2\caffe2_gpu.vcxproj]
  mpi_ops_gpu.obj : error LNK2019: unresolved external symbol MPI_Comm_free referenced in function "public: static void
 __cdecl caffe2::TypeMeta::_Dtor<class caffe2::MPICommonWorldWrapper>(void *,unsigned __int64)" (??$_Dtor@VMPICommonWor
ldWrapper@caffe2@@@TypeMeta@caffe2@@SAXPEAX_K@Z) [C:\temp\build_torch\pytorch\build\caffe2\caffe2_gpu.vcxproj]
  mpi_ops_gpu.obj : error LNK2019: unresolved external symbol MPI_Finalized referenced in function "public: static void
 __cdecl caffe2::TypeMeta::_Dtor<class caffe2::MPICommonWorldWrapper>(void *,unsigned __int64)" (??$_Dtor@VMPICommonWor
ldWrapper@caffe2@@@TypeMeta@caffe2@@SAXPEAX_K@Z) [C:\temp\build_torch\pytorch\build\caffe2\caffe2_gpu.vcxproj]
  C:\temp\build_torch\pytorch\build\bin\Release\caffe2_gpu.dll : fatal error LNK1120: 5 unresolved externals [C:\temp\b
uild_torch\pytorch\build\caffe2\caffe2_gpu.vcxproj]

"C:\temp\build_torch\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"C:\temp\build_torch\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\temp\build_torch\pytorch\build\caffe2\caffe2_pybind11_state.vcxproj" (default target) (52) ->
  pybind_state.obj : error LNK2019: unresolved external symbol "public: __cdecl onnx_torch::ValueInfoProto::ValueInfoPr
oto(void)" (??0ValueInfoProto@onnx_torch@@QEAA@XZ) referenced in function "public: static void __cdecl std::_Default_al
locator_traits<class std::allocator<struct std::_List_node<struct std::pair<class std::basic_string<char,struct std::ch
ar_traits<char>,class std::allocator<char> > const ,class onnx_torch::ValueInfoProto>,void *> > >::construct<struct std
::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class onnx_torch:
:ValueInfoProto>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class onnx_tor
ch::ValueInfoProto>(class std::allocator<struct std::_List_node<struct std::pair<class std::basic_string<char,struct st
d::char_traits<char>,class std::allocator<char> > const ,class onnx_torch::ValueInfoProto>,void *> > &,struct std::pair
<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class onnx_torch::Value
InfoProto> * const,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&,class onn
x_torch::ValueInfoProto &&)" (??$construct@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VV
alueInfoProto@onnx_torch@@@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@VValueInfoProto@onnx_torch@@
@?$_Default_allocator_traits@V?$allocator@U?$_List_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator
@D@2@@std@@VValueInfoProto@onnx_torch@@@std@@PEAX@std@@@std@@@std@@SAXAEAV?$allocator@U?$_List_node@U?$pair@$$CBV?$basi
c_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValueInfoProto@onnx_torch@@@std@@PEAX@std@@@1@QEAU?$pair@$$CBV?
$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValueInfoProto@onnx_torch@@@1@$$QEAV?$basic_string@DU?$cha
r_traits@D@std@@V?$allocator@D@2@@1@$$QEAVValueInfoProto@onnx_torch@@@Z) [C:\temp\build_torch\pytorch\build\caffe2\caff
e2_pybind11_state.vcxproj]
  pybind_state.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl onnx_torch::ValueInfoProto::~Va
lueInfoProto(void)" (??1ValueInfoProto@onnx_torch@@UEAA@XZ) referenced in function "int `public: static void __cdecl st
d::_Default_allocator_traits<class std::allocator<struct std::_List_node<struct std::pair<class std::basic_string<char,
struct std::char_traits<char>,class std::allocator<char> > const ,class onnx_torch::ValueInfoProto>,void *> > >::constr
uct<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,cla
ss onnx_torch::ValueInfoProto>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,
class onnx_torch::ValueInfoProto>(class _Default_allocator_traits<class std::allocator<struct std::_List_node<struct st
d::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class onnx_torch
::ValueInfoProto>,void *> > >::allocator<struct std::_List_node<struct std::pair<class std::basic_string<char,struct st
d::char_traits<char>,class std::allocator<char> > const ,class onnx_torch::ValueInfoProto>,void *> > &,struct _Default_
allocator_traits<class std::allocator<struct std::_List_node<struct std::pair<class std::basic_string<char,struct std::
char_traits<char>,class std::allocator<char> > const ,class onnx_torch::ValueInfoProto>,void *> > >::pair<class std::ba
sic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class onnx_torch::ValueInfoProto> * c
onst,class _Default_allocator_traits<class std::allocator<struct std::_List_node<struct std::pair<class std::basic_stri
ng<char,struct std::char_traits<char>,class std::allocator<char> > const ,class onnx_torch::ValueInfoProto>,void *> > >
::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&,class onnx_torch::ValueInfoProto &&)'
::`1'::dtor$2" (?dtor$2@?0???$construct@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValu
eInfoProto@onnx_torch@@@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@VValueInfoProto@onnx_torch@@@?$
_Default_allocator_traits@V?$allocator@U?$_List_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@
2@@std@@VValueInfoProto@onnx_torch@@@std@@PEAX@std@@@std@@@std@@SAXAEAV?$allocator@U?$_List_node@U?$pair@$$CBV?$basic_s
tring@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValueInfoProto@onnx_torch@@@std@@PEAX@std@@@1@QEAU?$pair@$$CBV?$ba
sic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValueInfoProto@onnx_torch@@@1@$$QEAV?$basic_string@DU?$char_t
raits@D@std@@V?$allocator@D@2@@1@$$QEAVValueInfoProto@onnx_torch@@@Z@4HA) [C:\temp\build_torch\pytorch\build\caffe2\caf
fe2_pybind11_state.vcxproj]
  pybind_state.obj : error LNK2019: unresolved external symbol "private: void __cdecl onnx_torch::ValueInfoProto::Inter
nalSwap(class onnx_torch::ValueInfoProto *)" (?InternalSwap@ValueInfoProto@onnx_torch@@AEAAXPEAV12@@Z) referenced in fu
nction "public: static void __cdecl std::_Default_allocator_traits<class std::allocator<struct std::_List_node<struct s
td::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class onnx_torc
h::ValueInfoProto>,void *> > >::construct<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,c
lass std::allocator<char> > const ,class onnx_torch::ValueInfoProto>,class std::basic_string<char,struct std::char_trai
ts<char>,class std::allocator<char> >,class onnx_torch::ValueInfoProto>(class std::allocator<struct std::_List_node<str
uct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class onnx
_torch::ValueInfoProto>,void *> > &,struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class s
td::allocator<char> > const ,class onnx_torch::ValueInfoProto> * const,class std::basic_string<char,struct std::char_tr
aits<char>,class std::allocator<char> > &&,class onnx_torch::ValueInfoProto &&)" (??$construct@U?$pair@$$CBV?$basic_str
ing@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValueInfoProto@onnx_torch@@@std@@V?$basic_string@DU?$char_traits@D@s
td@@V?$allocator@D@2@@2@VValueInfoProto@onnx_torch@@@?$_Default_allocator_traits@V?$allocator@U?$_List_node@U?$pair@$$C
BV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValueInfoProto@onnx_torch@@@std@@PEAX@std@@@std@@@std@@
SAXAEAV?$allocator@U?$_List_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValueInfoPr
oto@onnx_torch@@@std@@PEAX@std@@@1@QEAU?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValueI
nfoProto@onnx_torch@@@1@$$QEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@1@$$QEAVValueInfoProto@onnx_torch
@@@Z) [C:\temp\build_torch\pytorch\build\caffe2\caffe2_pybind11_state.vcxproj]
  pybind_state.obj : error LNK2019: unresolved external symbol "public: __cdecl onnx_torch::TensorProto::TensorProto(vo
id)" (??0TensorProto@onnx_torch@@QEAA@XZ) referenced in function "public: class pybind11::bytes __cdecl <lambda_8cbd6b5
3171a514b158d11af40318c6b>::operator()(class caffe2::onnx::Caffe2Backend &,class pybind11::bytes const &,class std::bas
ic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<lambda_8cbd6b53171a514b1
58d11af40318c6b>@@QEBA?AVbytes@pybind11@@AEAVCaffe2Backend@onnx@caffe2@@AEBV12@AEBV?$basic_string@DU?$char_traits@D@std
@@V?$allocator@D@2@@std@@@Z) [C:\temp\build_torch\pytorch\build\caffe2\caffe2_pybind11_state.vcxproj]
  pybind_state.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl onnx_torch::TensorProto::~Tenso
rProto(void)" (??1TensorProto@onnx_torch@@UEAA@XZ) referenced in function "public: class pybind11::bytes __cdecl <lambd
a_8cbd6b53171a514b158d11af40318c6b>::operator()(class caffe2::onnx::Caffe2Backend &,class pybind11::bytes const &,class
 std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<lambda_8cbd6b53
171a514b158d11af40318c6b>@@QEBA?AVbytes@pybind11@@AEAVCaffe2Backend@onnx@caffe2@@AEBV12@AEBV?$basic_string@DU?$char_tra
its@D@std@@V?$allocator@D@2@@std@@@Z) [C:\temp\build_torch\pytorch\build\caffe2\caffe2_pybind11_state.vcxproj]
  pybind_state.obj : error LNK2019: unresolved external symbol "const onnx_torch::ValueInfoProto::`vftable'" (??_7Value
InfoProto@onnx_torch@@6B@) referenced in function "public: static void __cdecl std::_Default_allocator_traits<class std
::allocator<struct std::_List_node<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class st
d::allocator<char> > const ,class onnx_torch::ValueInfoProto>,void *> > >::construct<struct std::pair<class std::basic_
string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class onnx_torch::ValueInfoProto>,class s
td::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class onnx_torch::ValueInfoProto>(clas
s std::allocator<struct std::_List_node<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,cla
ss std::allocator<char> > const ,class onnx_torch::ValueInfoProto>,void *> > &,struct std::pair<class std::basic_string
<char,struct std::char_traits<char>,class std::allocator<char> > const ,class onnx_torch::ValueInfoProto> * const,class
 std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&,class onnx_torch::ValueInfoProto
&&)" (??$construct@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValueInfoProto@onnx_torch
@@@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@VValueInfoProto@onnx_torch@@@?$_Default_allocator_tr
aits@V?$allocator@U?$_List_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VValueInfoPro
to@onnx_torch@@@std@@PEAX@std@@@std@@@std@@SAXAEAV?$allocator@U?$_List_node@U?$pair@$$CBV?$basic_string@DU?$char_traits
@D@std@@V?$allocator@D@2@@std@@VValueInfoProto@onnx_torch@@@std@@PEAX@std@@@1@QEAU?$pair@$$CBV?$basic_string@DU?$char_t
raits@D@std@@V?$allocator@D@2@@std@@VValueInfoProto@onnx_torch@@@1@$$QEAV?$basic_string@DU?$char_traits@D@std@@V?$alloc
ator@D@2@@1@$$QEAVValueInfoProto@onnx_torch@@@Z) [C:\temp\build_torch\pytorch\build\caffe2\caffe2_pybind11_state.vcxpro
j]

    67156 Warning(s)
    12 Error(s)

Time Elapsed 05:30:12.49

(base) C:\temp\build_torch\pytorch\build>IF ERRORLEVEL 1 exit 1
Failed to run 'tools\build_pytorch_libs.bat --use-cuda --use-nnpack caffe2 libshm_windows'

**Comment by peterjc123** [comment]
@terrylyons Sorry, you cannot build PyTorch with MPI currently. Please turn that off by setting `USE_DISTRIBUTED` or `USE_MPI` to `OFF` and try again.

**Comment by terrylyons** [comment]
Thanks, what is the syntax for this? Do I set env variables in the script or add it to the line
python setup.py install
Or manually edit some cmake file?

It seems that cmake found my mpi configuration on my machine and used it without asking me; if your build system engages with it by default but cannot support it I suppose this is a small bug.

Cross platform mpi would be a great extension though.

Terry

On 24 Sep 2018, at 04:45, peterjc123 <notifications@github.com<mailto:notifications@github.com>> wrote:


@terrylyons<https://github.com/terrylyons> Sorry, you cannot build PyTorch with MPI currently. Please turn that off by setting USE_DISTRIBUTED or USE_MPI to OFF and try again.

**Comment by peterjc123** [comment]
Try adding the below lines in somewhere near L185-192 in `tools/build_pytorch_libs.bat`:
```cmd
                  -DUSE_MPI=OFF ^
                  -DUSE_DISTRIBUTED=OFF ^
```
If it works on your side, then I'll submit a PR on this. Anyway, thanks for your report.

**Comment by davidbrownellMS** [comment]
@peterjc123 Another data point: I set the flags as described, rebuilt, and am running into the same linker errors.

**Comment by terrylyons** [comment]
I have run the amended script as per your directions (thanks), and I still get errors, many errors, but they seem to be around onx and misparsing \i in the cmake leading to the modules not being built and the link ultimately failing.  But one in particular near the end in console.txt is very interesting – there is a complaint on the error message stream
warning: no library file corresponding to 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0\lib/x64\cudnn.lib' found (skipping)
however it is there:

C:\temp\build_torch>dir "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib\x64\cudnn.lib"
Volume in drive C has no label.
Volume Serial Number is 0C92-5FF4

Directory of C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib\x64

17/11/2017  04:51            41,814 cudnn.lib
               1 File(s)         41,814 bytes
               0 Dir(s)  114,585,493,504 bytes free

Other errors also suggest there is a mis-parsing of slashes that are sometimes one way round and sometimes the other. (This error can be seen in the longer output as well). I am afraid I do not have time to analyse the errors right now but enclose the full build logs as they may well be helpful.

The output of collect_env.py is:

Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Pro
GCC version: (x86_64-posix-sjlj, built by strawberryperl.com project) 4.8.3
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Quadro K2100M
Nvidia driver version: 385.54
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by orionr** [comment]
@terrylyons your best bet is to run things as close to the Jenkins CI builds as you possibly can. That means running 

```
./.jenkins/pytorch/win-build.sh
```
An example of this passing (with logs) is https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-build/22650/console

Maybe check to see what's different between your logs and those above?

Also cc @mingzhe09088 since I thought he might have fixed the `/` vs `\` issue, but not sure.

**Comment by ezyang** [comment]
Since this is three years old I'm going to speculatively close this; if there are still troubles building Windows from source in master we'd love to hear about it.
