### ISSUE TITLE
[Dynamo] Graph break remapping in-place max all-reduce to functional

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#120082]
For repros, run via:
```
torchrun --standalone --nproc_per_node=2 <script_name.py>
```

### Case 1: No `group` Specified

```
import torch
import torch._dynamo.testing
import torch.distributed as dist


def tensor_to_amax(x: torch.Tensor):
    amax = torch.max(torch.abs(x))
    dist.all_reduce(amax, op=dist.ReduceOp.MAX)
    return amax


if __name__ == "__main__":
    dist.init_process_group(backend="nccl")
    rank = dist.get_rank()
    torch.cuda.set_device(rank)
    cnt = torch._dynamo.testing.CompileCounterWithBackend("aot_eager")
    x = torch.ones((1,), device="cuda") * (rank + 1)
    amax = torch.compile(tensor_to_amax, backend=cnt)(x)
    assert amax.item() == dist.get_world_size(), f"[Rank {rank}] amax: {amax.item()}"
    print(f"[Rank {rank}] frame count: {cnt.frame_count}")
```

Dynamo graph breaks on `dist.all_reduce()` due to:
```
Invalid type for group, must be one of List, Processgroup, DeviceMesh or (DeviceMesh, int).'
```

### Case 2: `group` specified
Suppose we pass the default group explicitly to work around the above issue.
```
import torch
import torch._dynamo.testing
import torch.distributed as dist


def tensor_to_amax(x: torch.Tensor):
    amax = torch.max(torch.abs(x))
    dist.all_reduce(amax, op=dist.ReduceOp.MAX, group=dist.distributed_c10d._get_default_group())
    return amax


if __name__ == "__main__":
    dist.init_process_group(backend="nccl")
    rank = dist.get_rank()
    torch.cuda.set_device(rank)
    cnt = torch._dynamo.testing.CompileCounterWithBackend("aot_eager")
    x = torch.ones((1,), device="cuda") * (rank + 1)
    amax = torch.compile(tensor_to_amax, backend=cnt)(x)
    assert amax.item() == dist.get_world_size(), f"[Rank {rank}] amax: {amax.item()}"
    print(f"[Rank {rank}] frame count: {cnt.frame_count}")
```

Dynamo graph breaks on `dist.all_reduce()` due to:
```
NotImplementedError: UserDefinedObjectVariable(RedOpType)
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by awgu** [comment]
There are a few issues it seems:
- We must pass in a `RANKS_TYPE` as `group`, but that does not include `None`, which is commonly how people call collectives over the default group.
- The remapping does not convert `c10d.ReduceOp` correctly to `str`. Interestingly, the functional collectives implementation remaps `str` back to `c10d.ReduceOp`. Either way, this is why Dynamo errors on `op=ReduceOp.MAX`.

cc: @yifuwang  Since you are refactoring the funcols, I wonder if we should hold off on this issue.

**Comment by yifuwang** [comment]
Hey @awgu, thanks for checking with me. I think (and I hope) the issue is orthogonal to native funcol migration.

I can take this up if no one's looking at it yet.

**Comment by awgu** [comment]
@yifuwang Sounds good! I do not think anyone is looking at it.

**Comment by awgu** [comment]
Resolved in https://github.com/pytorch/pytorch/pull/121043, https://github.com/pytorch/pytorch/pull/120181
