### ISSUE TITLE
Install only caffe2 

### ISSUE THREAD

**Issue by bendidi** [pytorch/pytorch#12015]
## Issue description

Hello i'm trying to install caffe2 using the docs from [here](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile) , but I noticed it compiles both caffe2 and pytorch, how can I only install caffe2 ?

## Code example
i'm building from source using the commands 
```bash
git clone https://github.com/pytorch/pytorch.git && cd pytorch
git submodule update --init --recursive
NO_NNPACK=1 NO_TEST=1 NO_CUDA=1 python3.6 setup.py install
```
## System Info

Running on docker : 

```docker
FROM lambci/lambda-base:build

ENV PATH=/var/lang/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib \
    AWS_EXECUTION_ENV=AWS_Lambda_python3.6 \
    PYTHONPATH=/var/runtime \
    PKG_CONFIG_PATH=/var/lang/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig

RUN rm -rf /var/runtime /var/lang && \
  curl https://lambci.s3.amazonaws.com/fs/python3.6.tgz | tar -xz -C / && \
  sed -i '/^prefix=/c\prefix=/var/lang' /var/lang/lib/pkgconfig/python-3.6.pc && \
  curl https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tar.xz | tar -xJ && \
  cd Python-3.6.1 && \
  LIBS="$LIBS -lutil -lrt" ./configure --prefix=/var/lang && \
  make -j$(getconf _NPROCESSORS_ONLN) libinstall inclinstall && \
  cd .. && \
  rm -rf Python-3.6.1
````

- PyTorch or Caffe2: Caffe2
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): `NO_NNPACK=1 NO_TEST=1 NO_CUDA=1 python3.6 setup.py install`
- OS: amazonlinux
- PyTorch version:  commit `8601b33c079545bcd45b37983d2ec355b2215960`
- Python version: 3.6
- CUDA/cuDNN version: None
- GPU models and configuration: None
- GCC version (if compiling from source): 4.8.3
- CMake version: 3.12.0
- Versions of any other relevant libraries: protobuf == 3.1.0

**Comment by soumith** [comment]
it is no longer possible to only install CAFFE2.

**Comment by cwRonaldinho** [comment]
> it is no longer possible to only install CAFFE2.

@soumith   why?

**Comment by bendidi** [comment]
@cwRonaldinho it's possible if you build using `cmake` and `make install`

**Comment by angelos-c** [comment]
@bendidi how would I go about this? (just caffe2 via `cmake` and `make install`)

thanks
