### ISSUE TITLE
RuntimeError: !check_has_torch_dispatch(obj) INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by hejianle** [pytorch/pytorch#120170]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Code example
 r = torch.Tensor._make_wrapper_subclass(
            cls,
            elem.size(),
            strides=elem.stride(),
            storage_offset=elem.storage_offset(),
            dtype=elem.dtype,
            layout=elem.layout,
            device=device or (elem.device if elem.device.type != 'meta' else torch.device('cpu')),
            requires_grad=requires_grad)    

RuntimeError: !check_has_torch_dispatch(obj) INTERNAL ASSERT FAILED at "../torch/csrc/autograd/python_variable.cpp":1962, please report a bug to PyTorch. While HermeticPyObject was enabled, we attempted to create a tensor subclass with __torch_dispatch__.  This violates the invariant that operations in HermeticPyObject have equivalent C++ implementations. If your operator registered from Python operator registration isn't doing anything strange, there may be an internal PyTorch bug involving not appropriately disabling TorchDispatchMode before executing Python op registration.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS:Ubuntu 20.04.4 LTS (x86_64)
- PyTorch version: 2.2.0+cu121
- Python version:  3.9.12
- CUDA/cuDNN version: 12.2.91/9.0.0
- GCC version (if compiling from source): 9.4.0
- CMake version: 
- Versions of any other relevant libraries:

cc @ezyang @msaroufim @albanD

**Comment by soulitzer** [comment]
You are probably running into this because you are returning a tensor subclass from a custom op. Closing because this should no longer error after https://github.com/pytorch/pytorch/pull/116996 (unless you are using multipy). You might want to try again on the latest nightly.

**Comment by wxthu** [comment]
I meet this error when I executed **transformed_wte**, how can I solve it

env setup:
```
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-113-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
```
