### ISSUE TITLE
Improved utilities for module swapping

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/pytorch#120103]
### 🚀 The feature, motivation and pitch
By module swapping here we are referring to `m.mod = new_mod`

@drisspg suggested the addition of a post order traversal utility to aid module swapping such as the one [here](https://github.com/pytorch-labs/float8_experimental/blob/956195bbc3983594308e7ccd64bab204c457a7a8/float8_experimental/float8_linear_utils.py#L122-L136)

For example, if we want to swap all layers that satisfy a certain condition with another layer, this means that child modules would be swapped before parent modules.

Without careful handling, parent modules might "lose" the child modules that need to be swapped.

cc @albanD @mruberry @jbschlosser @walterddr, @awgu

**Comment by mikaylagawarecki** [comment]
### Discussion notes:

Do we have a current API that would already help with module swapping?
- Maybe `module.apply`?

Would the swapping API be an API that takes in layer name to swap or some sort of callable policy that defines whether to swap a layer?

Do many users want to traverse in a post-order manner for their use cases? 
- Perhaps attaching hooks(?)
- For swapping Linears post order traversal is not needed, but this may be relevant when the parent contains a child that has the same module type
          - `Sequential` with `Pipeline[Sequential]` might be an example of a case where parent module contains itself
          - If we swap children before swapping the parent, won't the child be gone after we swap the parent, unless we do proper handling in the swapping function (@drisspg might try to see whether he can write this with `m.apply(fn)` if he has time)

**Comment by drisspg** [comment]
My worked example of seeing if this can be done with .apply instead of a custom func:

Alban mentioned that is unlikely the swap functions should be blindly setting `._modules` from previous mod to new mod. In practice the module that is replacing the old will know what "children" are important and these children will be passed to the constructor and handled there. 

I think the we can close this issue and instead this can be accomplished with a carefully crafted Apply 
```Python

import torch
import torch.nn as nn
import copy
from rich import print as rprint
from typing import Type, Optional, List, Callable

def module_swap(
    module: nn.Module,
    constructor: Callable,
    skip_fqn_list: Optional[List[str]] = None,
) -> nn.Module:
    """
    Replaces all instances of ``torch.nn.Linear`` in ``module`` with instances
    of ``module_cls`` (either ``Float8Linear`` or ``Float8DynamicLinear``).

    Args:
        module (torch.nn.Module): Module to modify.
        module_cls (Union[Type[Float8Linear], Type[Float8DynamicLinear]]): Float8 linear class for the swap.
        emulate (bool, optional): Whether to emulate the fp8 matmul logic in fp32.
        skip_fqn_list (List[str], optional): If specified, a list of module FQNs to skip.
            Linear submodules of these skipped modules will also be skipped.
    """
    module_names_to_skip = set(skip_fqn_list or [])
    if isinstance(module, nn.Linear):
        if len(list(module.children())) > 0:
            raise AssertionError(
                f"Does not support a root nn.Linear with children: {module}"
            )
        return constructor(module)

    # Mark all modules to skip as visited
    root_module = module
    visited_modules = {root_module}
    for module_name, module in root_module.named_modules():
        if module_name in module_names_to_skip:
            visited_modules.add(module)

    # Run a post-order traversal to swap linears
    def post_order_traversal(
        module: nn.Module, module_name: str, parent_module: Optional[nn.Module]
    ):
        nonlocal visited_modules
        for child_module_name, child_module in module.named_children():
            if child_module not in visited_modules:
                visited_modules.add(child_module)
                post_order_traversal(child_module, child_module_name, module)
        if isinstance(module, nn.Linear):
            assert (
                parent_module is not None
            ), f"Linear root module should return early: {module}"
            setattr(parent_module, module_name, constructor(module))

    post_order_traversal(root_module, "", None)
    # Without this explicit `del`, this set only gets deleted upon an explicit
    # garbage collection (not from when its refcount hits zero)
    del visited_modules
    return root_module

my_module = nn.Sequential(
    nn.Linear(16, 32, bias=True), nn.ReLU(), nn.Linear(32, 16, bias=True)
).to("cuda")

setattr(my_module[-1], "sneaky_linear", nn.Linear(16, 16, bias=True))


class SuperLinear(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return 1



rprint(my_module)

test_module_1 = copy.deepcopy(my_module)
test_module_2 = copy.deepcopy(my_module)


def swapper1(module: nn.Module):
    mod = SuperLinear()
    mod._modules = module._modules
    return mod
module_swap(test_module_1, swapper1)
rprint(test_module_1)



def swapper2(mod: nn.Module):
    for name, module in mod.named_children():
        if isinstance(module, nn.Linear):
            new_mod = SuperLinear(module.children())
            new_mod._modules = module._modules
            setattr(mod, name, new_mod)

test_module_2.apply(swapper2)
rprint(test_module_2)
```
