### ISSUE TITLE
Cuda 12.2 compitible pytorch

### ISSUE THREAD

**Issue by harsh123-baba** [pytorch/pytorch#120187]
### 🚀 The feature, motivation and pitch

Currently we have support till CUDA12.1, kindly try to implement it ASAP.

cc @ptrblck

**Comment by ptrblck** [comment]
PyTorch source builds support all currently released CUDA 12.x versions. We are targeting a future CUDA release for the binaries.

**Comment by m1kebz** [comment]
For Info: I was just looking up NVidia Jetpack release info. It seems Jetpack6.0 in production release is slated next month (Mar'24). Its release calls for Python 3.10, o/s based on Ubuntu 22.04, and comes with CUDA 12.2. So I would expect many people would appreciate a binary for 12.2
