### ISSUE TITLE
Dynamo support dataclasses with default_factory=list

### ISSUE THREAD

**Issue by IvanKobzarev** [pytorch/pytorch#120108]
### 🚀 The feature, motivation and pitch

Dynamo does not support dataclasses with default_factory list.

(Setting empty lists for object creation helps)

### Additional context

Was mentioned in https://github.com/pytorch/pytorch/issues/101918

Made a separate issue to point this in the code.

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @bdhirsh @zou3519 @aakhundov

**Comment by masnesral** [comment]
@ezyang , I assume this is definitely worth doing, but not hi-pri ATM?

**Comment by anijain2305** [comment]
Marking it as dynamo-must-fix. It's not high priority.

**Comment by mlazos** [comment]
@ydwu4 mind if I take this?

**Comment by ydwu4** [comment]
Sure, please go ahead!
