### ISSUE TITLE
[MPS] pytorch.mps.profiler os_signposts not labelled

### ISSUE THREAD

**Issue by igm503** [pytorch/pytorch#120162]
### 🐛 Describe the bug

When I try to profile a model running on the MPS device, I can see PyTorchMPS data in XCode's Instruments application, but all of the intervals are labelled with '<*private*>' instead of with an op name, so it's impossible to tell how long each op takes. 

<img width="1728" alt="Screenshot 2024-02-17 at 2 36 35 PM" src="https://github.com/pytorch/pytorch/assets/109993208/8c160ae8-7ad8-4e9e-9ba0-868843ac19a1">

minimal example:
```
import os

import torchvision.models as models
import torch
from tqdm import tqdm


print(os.getpid())

model = models.resnet18().to('mps')
inputs = torch.randn(5, 3, 224, 224).to('mps')

with torch.mps.profiler.profile(mode="interval", wait_until_completed=False):
    for i in tqdm(range(1000)):
        output = model(inputs)
```
1. Run script
2. Set process target in Instruments using the printed PID
3. Record

### Versions

PyTorch version: 2.2.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.3.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.27.3
Libc version: N/A

Python version: 3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 09:45:58) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.0
[pip3] torchvision==0.17.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.0                    pypi_0    pypi
[conda] torchvision               0.17.0                   pypi_0    pypi

cc @ezyang @anjali411 @dylanbespalko @mruberry @lezcano @nikitaved @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by malfet** [comment]
I suspect it some sort of MacOS security setting, which does not allow one to collect sensitive information by attaching to the process, but one should be able to do it by launching the process in instruments.
I.e. I've defined my target as python executable process and passed name of the script and working directory as arguments:
<img width="559" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/fb59a119-57a1-4681-b247-c2c58561eb30">
After than I was able to collect the signpost events:
<img width="848" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/53a8f73e-18e0-46ec-96e8-9b6aefd9ea61">

**Comment by igm503** [comment]
@malfet That worked! Thanks!

**Comment by janboeye** [comment]
hi, @igm503
I used your script, but the instrument didn't capture any events. Is there any preparation needed beforehand? PyTorch version is 2.3, and macOS version is 14.2.

Thanks

**Comment by janboeye** [comment]
hi, @igm503 
How can you resolve to show private data?

Thanks

**Comment by igm503** [comment]
@janboeye 
Following Malfet's instructions worked:

1. After you start an Instruments session, near the top left of the window, click on the process that instruments is set to record, and then select "choose target"
2. (That should open an explorer window allowing you to select executables to profile--this is the picture in Malfet's post)
3. Find the python executable you want to use (if you're using an environment manager, like conda, make sure to select the python executable for the environment with the pytorch package you're interested in). 
--for example, I'm using conda, and the pytorch version I wanted to use is in my "pytorch" env, so the python executable I selected was at /opt/homebrew/caskroom/miniforge/base/envs/pytorch/bin/python3. To figure out where yours is, look at the output of "which python" or "which python3" in a terminal session configured to run your script.
4. Once you've selected the correct python executable, enter the path to the script you want to profile in the "arguments" textbox near the bottom of the process selection window.
5. Confirm your selection by clicking "choose"
6. Run the profiler (make sure to include the os_signpost instrument, but it seems like you know how to do that already)

**Comment by janboeye** [comment]
@igm503 Thank you for so detailed instruction. It worked
