### ISSUE TITLE
Conformance test suite for torch.compile backends

### ISSUE THREAD

**Issue by mvafin** [pytorch/pytorch#120197]
### 🚀 The feature, motivation and pitch

It would be nice to have a conformance test suite so that `torch.compile` backend developers could run it on their backends to verify what ops are correctly supported. Some corner cases of operators usage may not be correctly covered by backend developers and tests can discover such bugs.
It can cover [Core operations set](https://pytorch.org/docs/stable/torch.compiler_ir.html#core-aten-ir) and also can help test frameworks that would support models obtained from `torch.export`.

If such tests already exist, could you point me where I can find them?

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by Chillee** [comment]
We have a set of benchmark suites set up in `benchmarks/dynamo`, particularly the torchbench, huggingface, and timm ones.

You can run it as `python benchmarks/dynamo/huggingface.py --inductor --training --bfloat16 --performance`
