### ISSUE TITLE
onnx_export line.93 error on custom train data set

### ISSUE THREAD

**Issue by GirishPawar1999** [pytorch/pytorch#120154]
### 🐛 Describe the bug

I have trained the mobilenetssdv2 model for 5000 images dataset, the traing has been completed have choose the best pth file.
When trying to convert to the onn_export it shows the following error

BOARD: JETSON ORION NANO

'''
python3 onnx_export.py --model-dir=models/GFC_TOP2
Namespace(batch_size=1, input='', labels='labels.txt', model_dir='models/GFC_TOP2', net='ssd-mobilenet', output='', resolution=300)
=> running on device cuda:0
=> found best checkpoint with loss 1.4820616446841848 (models/GFC_TOP2/mb1-ssd-Epoch-9-Loss-1.4820616446841848.pth)
=> creating network:  ssd-mobilenet
=> num classes:       3
=> resolution:        300x300
=> loading checkpoint:  models/GFC_TOP2/mb1-ssd-Epoch-9-Loss-1.4820616446841848.pth
Traceback (most recent call last):
  File "onnx_export.py", line 93, in <module>
    net.load(args.input)
  File "/home/kvar/jetson-inference/python/training/detection/ssd/vision/ssd/ssd.py", line 149, in load
    self.load_state_dict(torch.load(model, map_location=lambda storage, loc: storage))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SSD:
	size mismatch for classification_headers.0.weight: copying a param with shape torch.Size([24, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([18, 512, 3, 3]).
	size mismatch for classification_headers.0.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for classification_headers.1.weight: copying a param with shape torch.Size([24, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([18, 1024, 3, 3]).
	size mismatch for classification_headers.1.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for classification_headers.2.weight: copying a param with shape torch.Size([24, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([18, 512, 3, 3]).
	size mismatch for classification_headers.2.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for classification_headers.3.weight: copying a param with shape torch.Size([24, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([18, 256, 3, 3]).
	size mismatch for classification_headers.3.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for classification_headers.4.weight: copying a param with shape torch.Size([24, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([18, 256, 3, 3]).
	size mismatch for classification_headers.4.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for classification_headers.5.weight: copying a param with shape torch.Size([24, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([18, 256, 3, 3]).
	size mismatch for classification_headers.5.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
'''

please do help me as i am new to custom training datasets

### Versions

na

cc @malfet @snadampal

**Comment by thiagocrepaldi** [comment]
@GirishPawar1999 please provide a repro if this is issue still relevant for you
