### ISSUE TITLE
next_power_of_2 in codegen_kernel

### ISSUE THREAD

**Issue by wangjiangben-hw** [pytorch/pytorch#120152]
### 🚀 The feature, motivation and pitch

In https://github.com/pytorch/pytorch/blob/main/torch/_inductor/codegen/triton.py#L2643，using triton's next_power_of_2

The only difference between the two functions(https://github.com/pytorch/pytorch/blob/main/torch/_inductor/utils.py#L225 and https://github.com/openai/triton/blob/main/python/triton/__init__.py#L59) is the handling of 2 * * 32

This is the only place in the code repository where next_power_of_2 is used in this way -- from triton import next_power_of_2, which is somewhat confusing. Why don't we enhance the function in utils and add a switch to allow support for 2 * * 32, reducing dependency on triton packages while enhancing understandable semantics.

**Comment by jansel** [comment]
The only reason 2**32 isn't handled is this was the old behavior of Triton (which we copied).  It would be fine to just modify the inductor version to always handle 64bit.
