### ISSUE TITLE
Torch compile does not work on python 3.12

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#120233]
### 🐛 Describe the bug

Currently torch, as of 2.2.0 does not support torch compile with python 3.12

See following PR for example: https://github.com/pytorch/pytorch/pull/117853

1. We need to be able to use python 3.12 with torch.compile feature. 
2. Include triton with Linux 3.12 wheel 
3. Enable Python 3.12 and torch.compile CI testsing

cc: @albanD @malfet 

### Versions

2.2.0

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by SysuJayce** [comment]
Hi @albanD , is there a timeline for PT to support `torch.compile()` on py3.12?

**Comment by albanD** [comment]
cc @williamwen42 ?

**Comment by albanD** [comment]
Next release means 2.4 here.

**Comment by Astolsko** [comment]
so which version of python and pytorch will enable me to use `torch.compile`?

**Comment by malfet** [comment]
> You can use torch compile on any version between 3.8 and 3.11 as of right now.

Provided you are running it on Linux or MacOS. If you are on Windows, they no luck, no matter what the version of Python you are using

**Comment by williamwen42** [comment]
Dynamo is now supported in Python 3.12 (minus a few bugs) - but it looks like triton is not bundled when installing from binary.

**Comment by rubenweitzman** [comment]
Hi @williamwen42 , still getting the error RuntimeError: Dynamo is not supported on Python 3.12+ with latest version of pytorch 2.2.2. What am i supposed to do to use torch.compile() ? 

Here are the packages and versions in my conda env
`#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
aiohttp                   3.9.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
blas                      1.0                         mkl  
brotli-python             1.0.9           py312h6a678d5_7  
bzip2                     1.0.8                h5eee18b_5  
ca-certificates           2024.3.11            h06a4308_0  
certifi                   2024.2.2        py312h06a4308_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cuda-cudart               12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.4.127                      0    nvidia
cuda-runtime              12.1.0                        0    nvidia
cudatoolkit               11.8.0               h6a678d5_0  
datasets                  2.18.0                   pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
expat                     2.5.0                h6a678d5_0  
fairscale                 0.4.6                    pypi_0    pypi
faiss-gpu                 1.8.0           py3.12_h4c7d538_0_cuda12.1.1    pytorch
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.13.1          py312h06a4308_0  
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.2.0                 pypi_0    pypi
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
grpcio                    1.62.1                   pypi_0    pypi
huggingface-hub           0.22.2                   pypi_0    pypi
idna                      3.4             py312h06a4308_0  
intel-openmp              2023.1.0         hdb19cb5_46306  
jinja2                    3.1.3           py312h06a4308_0  
jpeg                      9e                   h5eee18b_1  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libcublas                 12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufile                 1.9.1.3                       0    nvidia
libcurand                 10.3.5.147                    0    nvidia
libcusolver               11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libdeflate                1.17                 h5eee18b_1  
libfaiss                  1.8.0           h046e95b_0_cuda12.1.1    pytorch
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.4                h5eee18b_0  
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libnpp                    12.0.2.50                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjpeg                 12.1.1.14                     0    nvidia
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                h6a678d5_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libwebp-base              1.3.2                h5eee18b_0  
llvm-openmp               14.0.6               h9e868ea_0  
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.6                      pypi_0    pypi
markupsafe                2.1.3           py312h5eee18b_0  
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0           py312h5eee18b_1  
mkl_fft                   1.3.8           py312h5eee18b_0  
mkl_random                1.2.4           py312hdb19cb5_0  
mpmath                    1.3.0           py312h06a4308_0  
multidict                 6.0.5                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.1             py312h06a4308_0  
numpy                     1.26.4          py312hc5e2394_0  
numpy-base                1.26.4          py312h0da6c21_0  
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   3.0.13               h7f8727e_0  
packaging                 23.2            py312h06a4308_0  
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.2.0          py312h5eee18b_0  
pip                       23.3.1          py312h06a4308_0  
protobuf                  5.26.1                   pypi_0    pypi
pyarrow                   15.0.2                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pysocks                   1.7.1           py312h06a4308_0  
python                    3.12.2               h996f2a0_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch                   2.2.2           py3.12_cuda12.1_cudnn8.9.2_0    pytorch
pytorch-cuda              12.1                 ha16c6d3_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1           py312h5eee18b_0  
readline                  8.2                  h5eee18b_0  
regex                     2023.12.25               pypi_0    pypi
requests                  2.31.0          py312h06a4308_1  
rouge                     1.0.1                    pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
scipy                     1.13.0                   pypi_0    pypi
setuptools                68.2.2          py312h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
sympy                     1.12            py312h06a4308_0  
tbb                       2021.8.0             hdb19cb5_0  
tensorboard               2.16.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.15.2                   pypi_0    pypi
torchaudio                2.2.2               py312_cu121    pytorch
torchvision               0.17.2              py312_cu121    pytorch
tqdm                      4.66.2                   pypi_0    pypi
transformers              4.39.3                   pypi_0    pypi
typing_extensions         4.9.0           py312h06a4308_1  
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.1.0           py312h06a4308_1  
werkzeug                  3.0.2                    pypi_0    pypi
wget                      3.2                      pypi_0    pypi
wheel                     0.41.2          py312h06a4308_0  
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.6                h5eee18b_0  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.9.4                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0  `

**Comment by williamwen42** [comment]
@rubenweitzman you should use the nightly binary or build from source.

**Comment by rubenweitzman** [comment]
Thanks! now getting error ImportError: cannot import name 'triton_key' from 'triton.compiler.compiler after installing triton (tried triton version 2.3.0 and 2.3.0)

**Comment by williamwen42** [comment]
You'll need to also install a newer version of triton - try installing from source (we're trying to update the triton pin here: https://github.com/pytorch/pytorch/pull/123077).

**Comment by SysuJayce** [comment]
FYI:  
Pytorch 2.3.0 with python3.12 still raise this error `RuntimeError: Dynamo is not supported on Python 3.12+`.

**Comment by rwightman** [comment]
conda is installing Python 3.12 by default in new envs on several machines I train & test with so this is now requiring force downgraade of python when creating new envs `python=3.11` ... 

I realize keeping this support up to date is probably trickier than it looks, but as I use dynamo more and more, the lag between PyTorch support and new python versions becoming defaults is becoming more noticeable.

The last python 3.10 -> 3.11 transition didn't stand out as much because torch.compile was relatively new and I wasn't using it all the time, no longer.

**Comment by williamwen42** [comment]
To clarify: `torch.compile` support for Python 3.12 will NOT be backported to PyTorch 2.2.x or 2.3.x. 3.12 support is currently available in the PyTorch nightly binary and WILL be included in the 2.4 release.

**Comment by orionr** [comment]
FYI to @mergennachin and @dbort here! Thank you

**Comment by williamwen42** [comment]
@atalman update on 3.12: inductor 3.12 CI is up and the current pinned triton build passes that CI, so it doesn't seem we need to further cherry-pick triton to get it working for 3.12.

**Comment by shivanimall** [comment]
still receiving the same error: `RuntimeError: Dynamo is not supported on Python 3.12+`

**Comment by dbort** [comment]
@shivanimall since this issue is pretty old, could you please open a new bug with details about your environment?

**Comment by zouharvi** [comment]
Had `RuntimeError: Dynamo is not supported on Python 3.12+` on torch-2.3.0 but not when upgraded to torch 2.6.0. Thanks!
