### ISSUE TITLE
Update pytorch.Trainer iterations correctly

### ISSUE THREAD

**Issue by komarov-k** [pytorch/pytorch#1202]
In pytorch.Trainer.train, the last line should be ```self.iterations = i``` instead of ```self.iterations += i```. The iterations should go from 1 to N during first epoch, then N+1 to 2N in second epoch, and so on. Currently, ```self.iterations``` is updated with progressively increasing values at the end of each epoch. For illustration purposes, consider the following two code snippets:

```python
data = [1, 2, 3]
iterations = 3
epochs = 3
for _ in range(0, epochs):
    for i, item in enumerate(items, iterations + 1):
        print i
    iterations += i
```

Output:
```
1
2
3
4
5
6
10
11
12
```

```python
data = [1, 2, 3]
iterations = 3
epochs = 3
for _ in range(0, epochs):
    for i, item in enumerate(items, iterations + 1):
        print i
    iterations = i
```

Output:

```
1
2
3
4
5
6
7
8
9
```

Here the first snippet shows the bug that is currently present in Trainer, while the second one shows how to fix it.

**Comment by apaszke** [comment]
Trainer is an undocumented part of the API that will be removed soon. We won't be fixing any problems with it. I'd recommend you to switch to [tnt](https://github.com/pytorch/tnt). Thanks!
