### ISSUE TITLE
[jit] Slicing a tensor list always creates a tensor that requires_grad

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#12024]
Repro:
```
import torch
x = torch.randn(3)
y = torch.randn(4)
@torch.jit.script
def fn(x, y):
    lst = [x, y]
    return lst[1]

fn(x, y)
fn.graph_for(x, y)

# Output
graph(%x : Float(*)
      %y : Float(*)) {
  %2 : int = prim::Constant[value=1]()
  %lst : Dynamic[] = prim::ListConstruct(%x, %y)
  %4 : Dynamic = aten::select(%lst, %2)
  return (%4);
}
```

DynamicType's requires_grad field is always set to True...

**Comment by apaszke** [comment]
Which is fine. `requires_grad` that's set on types in the JIT is an overapproximation. You should be able to safely return a `nullptr` from the derivative of `aten::select`. Is that not the case?

**Comment by apaszke** [comment]
An alternative would be to improve the requires_grad propagation, but it's not like we can depend on it working in all possible cases.

**Comment by zou3519** [comment]
The real problem is that in the following code:
```
import torch

x = torch.randn(3, 3)

def fn(x):
    return x[[0, 1], [1, 0]]

traced = torch.jit.trace(fn, x)
traced(x)
traced.graph_for(x)

graph(%0 : Float(*, *)) {
  %17 : Dynamic[] = prim::Constant[value=[<Tensors>]]()
  %12 : Dynamic = aten::index(%0, %17)
  return (%12);
}
```
Each "Tensor" is actually a DynamicType and so `%17` requires_grad, which causes a crash in autodiff if I allow single-node differential subgraphs (so only the prim::Constant is in the differential subgraph)

**Comment by zdevito** [comment]
closing issue as it is likely no longer valid, reopen if not true.
