### ISSUE TITLE
Custom devices need to be supported for distributed checkpoint

### ISSUE THREAD

**Issue by ChuBoning** [pytorch/pytorch#120200]
### 🚀 The feature, motivation and pitch

Currently https://github.com/pytorch/pytorch/blob/637cf4a3f2cfdd364005681636ca885bdc4d5887/torch/distributed/checkpoint/filesystem.py#L266 only supports cuda devices.I'm going to add custom devices support.
pls

### Additional context

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by soulitzer** [comment]
cc @albanD
