### ISSUE TITLE
DCP saving support for per-rank tensors

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#120356]
### 🐛 Describe the bug

Hi!

I'm trying to use distributed checkpoint (DCP) for efficient saving of sharded-like tensors. I expected this to work

```python
import os
import torch.cuda
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.distributed.checkpoint import save

def work(rank):
    os.environ["MASTER_ADDR"] = "127.0.0.1"
    os.environ["MASTER_PORT"] = "1234"
    dist.init_process_group("nccl", world_size=2, rank=rank)
    torch.cuda.set_device(rank)
    device = torch.device("cuda", rank)

    t = torch.tensor([0, 1] if rank == 0 else [2, 3], device=device)
    state = {"weight": t}
    save(state, checkpoint_id="repro_ckpt")

    if rank == 0:
        print("__0_0.distcp", torch.load("repro_ckpt/__0_0.distcp"))  # [0, 1]
        print("__1_0.distcp", torch.load("repro_ckpt/__1_0.distcp"))  # [2, 3]

def run():
    mp.spawn(work, nprocs=2)

if __name__ == "__main__":
    run()
```

However, **`__1_0.distcp` is empty so loading fails**.

After some debugging, it seems to be caused by the deduplication step in https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/_dedup_save_plans.py.

Where

```python
[
    SavePlan(
        items=[
            WriteItem(
                index=MetadataIndex(fqn='weight', offset=torch.Size([0]), index=None),
                type=<WriteItemType.TENSOR: 1>,
                tensor_data=TensorWriteData(
                    chunk=ChunkStorageMetadata(offsets=torch.Size([0]), sizes=torch.Size([2])),
                    properties=TensorProperties(dtype=torch.int64, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False),
                    size=torch.Size([2])
                )
            )
        ],
        storage_data=None,
        planner_data={'weight': ('weight',)}
    ),
    SavePlan(
        items=[
            WriteItem(
                index=MetadataIndex(fqn='weight', offset=torch.Size([0]), index=None),
                type=<WriteItemType.TENSOR: 1>,
                tensor_data=TensorWriteData(
                    chunk=ChunkStorageMetadata(offsets=torch.Size([0]), sizes=torch.Size([2])),
                    properties=TensorProperties(dtype=torch.int64, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False),
                    size=torch.Size([2])
                )
            )
        ],
        storage_data=None,
        planner_data={'weight': ('weight',)}
    )
]
```

is condensed into

```python
[
    SavePlan(
        items=[
            WriteItem(
                index=MetadataIndex(fqn='weight', offset=torch.Size([0]), index=0),
                type=<WriteItemType.TENSOR: 1>,
                tensor_data=TensorWriteData(
                    chunk=ChunkStorageMetadata(offsets=torch.Size([0]), sizes=torch.Size([2])),
                    properties=TensorProperties(dtype=torch.int64, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False),
                    size=torch.Size([2])
                )
            )
        ],
        storage_data=None,
        planner_data={'weight': ('weight',)}
    ),
    SavePlan(items=[], storage_data=None, planner_data={'weight': ('weight',)})
]
```

This happens at https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/state_dict_saver.py#L261

Is this a bug? Or is `DCP.save` not intended to be used this way?

I noticed that this works with ordinary FSDP but there the item types are `ShardedTensor`s that properly represent the chunk sizes and offsets across ranks.

Happy to work on this if given some guidance.

### Versions

Current `main`

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

**Comment by carmocca** [comment]
I found one "workaround" which is to prefix the state with the rank:

```python
state = {f"{rank}.weight": t}
```

However, during `DCP.load()`, the following warning appears:

```python
/home/carlos/nightly-env/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_loader.py:144: UserWarning: Detected mismatched keys in state dict after all gather! This behavior is unsupported and may cause errors may cause errors.
```

The warning can be avoided by passing `no_dist=True`. I guess this is okay because there are no `ShardedTensor`/`DTensor` to reconstruct?

**Comment by XilunWu** [comment]
route to @fegin

**Comment by fegin** [comment]
@carmocca DCP will treat all the tensors as replicated, meaning that it will only save one copy. If you are going to have a distributed tensor, consider to use DTensor. DCP understands DTensor and will save the content correctly.

**Comment by carmocca** [comment]
Thanks for the reply. I can get it to work with

```python
device_mesh = init_device_mesh("cuda", (2,))
placements = [Shard(0) for _ in range(device_mesh.ndim)]
t = DTensor.from_local(t, device_mesh, placements)
```

Do you think DCP could take care of this in the future to relax the assumption that all tensors are replicated?

**Comment by wz337** [comment]
> Thanks for the reply. I can get it to work with
> 
> ```python
> from torch.distributed._tensor import DTensor, Shard
> from torch.distributed.device_mesh import init_device_mesh
> 
> device_mesh = init_device_mesh("cuda", (2,))
> placements = [Shard(0) for _ in range(device_mesh.ndim)]
> t = DTensor.from_local(t, device_mesh, placements)
> ```
> 
> Do you think DCP could take care of this in the future to relax the assumption that all tensors are replicated?

Unfortunately, we will not be able to relax this assumption. If we have a tensor with the same key across ranks, since we don't do cross-rank check, which is expensive, we will have to assume the tensor is replicated across ranks. Otherwise, we will not have enough information to determine what is replicated and what is not.

In SPMD style, tensors with the same key(fqn) should be the same across all ranks. If a tensor is distributed across different ranks and has different local shards, it has to use DTensor for checkpoint. 
In MPMD style, tensors on different ranks should have different keys.
