### ISSUE TITLE
installing pytorch + pytorch-nightly breaks things

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#12031]
Things break when you install pytorch-nightly in the conda env which already had pytorch installed. Must use fresh conda env for nightly

```
conda create -n test -y
source activate test
conda install -c pytorch  pytorch-nightly -y
python -c "import torch; print(torch.version.__version__)" #=> 1.0.0.dev20180921

conda install -c pytorch  pytorch -y
python -c "import torch; print(torch.version.__version__)"  #=> 0.4.1

conda install -c pytorch  pytorch-nightly -y
python -c "import torch; print(torch.version.__version__)"  #=> 0.4.1, expected 1.0.0.dev20180921

conda list
pytorch                   0.4.1           py37_cuda0.0_cudnn0.0_1    pytorch
pytorch-nightly           1.0.0.dev20180921         py3.7_0    pytorch

conda uninstall pytorch -y
conda install -c pytorch  pytorch-nightly -y
python -c "import torch; print(torch.version.__version__)"  #=> AttributeError: module 'torch' has no attribute 'version'

```

**Comment by zou3519** [comment]
Does python -c "import torch; print(torch.__version__)" work?

**Comment by yaroslavvb** [comment]
Nope, you get `AttributeError: module 'torch' has no attribute 'version'`

Seems Conda is  confused that pytorch and pytorch-nightly have different names, but they are both pytorch. The solution is to use --force flag when trying to change from pytorch to pytorch-nightly and vica versa

conda install -c pytorch pytorch -y --force
conda install -c pytorch pytorch-nightly -y --force
