### ISSUE TITLE
Exporting the operator 'aten::smooth_l1_loss' to ONNX opset version 14 is not supported

### ISSUE THREAD

**Issue by ykim836** [pytorch/pytorch#120326]
### 🐛 Describe the bug

From this link, https://pytorch.org/docs/stable/onnx_torchscript_supported_aten_ops.html
I realized exporting the operator 'aten::smooth_l1_loss' to ONNX is not supported yet. 
Could you let me know the estimate date to get updated? or Could you give any idea to solve this error? 

Thank you for your time and assistance.

```python
import torch
import torchvision
from torchvision.models.detection import ssd300_vgg16, SSD300_VGG16_Weights
import io
import onnx

model = torchvision.models.detection.ssd300_vgg16(weights=SSD300_VGG16_Weights.DEFAULT)
device = "cuda:0"
pt_model = model.to(device)

batch_size, channel, input_size_h, input_size_w = 64, 3, 300, 300
images = torch.randn(batch_size, channel, input_size_h, input_size_w, device=device)

num_boxes = 5
targets = []
for _ in range(batch_size):
    boxes = torch.rand(num_boxes, 4, device=device) * 300
    boxes[:, 2:] += boxes[:, :2]
    target = {
        'boxes': boxes,
        'labels': torch.randint(1, 91, (num_boxes,), device=device)
    }
    targets.append(target)

model_inputs = (images, targets)
input_names = ["input", "targets"]
output_names = ["output"]
dynamic_axes = {"input": {0: "batch_size"}, "output": {0: "batch_size"}}

f = io.BytesIO()
torch.onnx.export(
    pt_model,
    model_inputs,
    f,
    input_names=input_names,
    output_names=output_names,
    opset_version=18,
    do_constant_folding=False,
    training=torch.onnx.TrainingMode.TRAINING,
    dynamic_axes=dynamic_axes,
    export_params=True,
    keep_initializers_as_inputs=False,
)

onnx_model = onnx.load_model_from_string(f.getvalue())
```

### Versions

onnxruntime-training 1.16.0
onnx 1.14.1
torchvision 0.15.2
torch 2.0.1

**Comment by thiagocrepaldi** [comment]
Hello @ykim836, indeed `aten::smooth_l1_loss` is not supported and we don't have plans to add it ourselves as `torch.onnx.export` is being deprecated in favor of `torch.onnx.dynamo_export`.

You can contribute this operator following steps on our [documentation](https://pytorch.org/docs/stable/onnx_torchscript.html#adding-support-for-operators) and we would be more than happy to review and merge it!

**Comment by ykim836** [comment]
I see. Thanks for sharing the documentation! I will try to develop my own operator then!
