### ISSUE TITLE
[dtensor] aten._scaled_dot_product_flash_attention.default

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#120333]
cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by awgu** [comment]
I renamed it to make it clear this is relating to DTensor to avoid any confusion 😅
