### ISSUE TITLE
batch_size of pack_padded_sequence

### ISSUE THREAD

**Issue by RangoHU** [pytorch/pytorch#1203]
Hello, I have a question about the bacth_size of a PackedSequence. The toy code is as follow:

Code:
x = Variable(torch.randn(10, 20, 30))
lens = [10, 10, 10, 10, 10, 10, 10, 3, 2, 1]
x = pack_padded_sequence(x, lens, batch_first=True)
print x

Output:
'''
PackedSequence(data=Variable containing:
 1.0801  0.3946  0.4798  ...  -1.1052  0.7187  0.7739
 1.2224  0.5616  0.4438  ...   0.4786 -0.0984  0.7566
 2.2416 -1.2815  0.0442  ...   1.1248  1.1361  1.1236
          ...             ⋱             ...          
-0.4377  0.6860 -0.7715  ...  -0.7121 -1.7311  0.7555
 0.6080 -1.5501 -1.0429  ...   2.4519 -0.1884 -0.0611
 1.4053  0.1409 -1.5822  ...  -0.2042 -1.4964 -0.0310
[torch.FloatTensor of size 76x30]
, batch_sizes=[10, 9, 8, 7, 7, 7, 7, 7, 7, 7])
'''
The question is how come the batch_size is [10, 9, 8, 7, 7, 7, 7, 7, 7, 7] instead of [10, 10, 10, 10, 10, 10, 10, 3, 2, 1]?

Thanks!

**Comment by soumith** [comment]
https://discuss.pytorch.org
