### ISSUE TITLE
(Question) Source compile error: -fPIC unsupported option on Windows with clang compiler

### ISSUE THREAD

**Issue by Stehsaer** [pytorch/pytorch#120306]
## Issue description
Trying to compile libtorch with clang compiler 17, x86_64-pc-windows-msvc
Errors reported: 
```
clang++: error: unsupported option '-fPIC' for target 'x86_64-pc-windows-msvc'
```
How can I fix it?

Here's the output file
[log.txt](https://github.com/pytorch/pytorch/files/14358123/log.txt)

##### Additional info
Modified `third_party\cpuinfo\src\cpuinfo\utils.h`, added `#include <intrin.h>"` to let the compiler find the intrinsic function `_BitScanReverse`

## System Info
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 专业版
GCC version: (x86_64-win32-seh-rev1, Built by MinGW-Builds project) 13.2.0
Clang version: 17.0.6
CMake version: version 3.28.0-rc1
Libc version: N/A

Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: 12.3.107
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4060 Laptop GPU
Nvidia driver version: 551.23
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2400
DeviceID=CPU0
Family=198
L2CacheSize=9728
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2400
Name=13th Gen Intel(R) Core(TM) i7-13620H
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchvision==0.15.2+cu118
[conda] Could not collect

- PyTorch or Caffe2: Libtorch actually
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source): `"C:\Program Files\CMake\bin\cmake.EXE" --build d:/pytorch-v2.2.0/build --config Release --target all`
- OS: Windows 11 Professional
- GPU models and configuration: Nvidia RTX 4060 Laptop
- GCC version (if compiling from source): error during compiling, using clang17
- CMake version: 3.28
- Versions of any other relevant libraries: None

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by Stehsaer** [comment]
BTW, I'm intending to compile libtorch with CPU support only on Windows using clang or gcc so that I can also compile my torch-based project with clang or gcc.

**Comment by alinpahontu2912** [comment]
Hey @Stehsaer,  the official compiler used to build pytorch and libtorch is msvc, so we recommend using this one instead.
