### ISSUE TITLE
Inconsistent Behavior in Tensor Slice Mean Calculation and Comparison with `torch.allclose()`

### ISSUE THREAD

**Issue by nasyxx** [pytorch/pytorch#120404]
### 🐛 Describe the bug

I encountered an unexpected behavior when computing the mean of different slices of a tensor and comparing them using `torch.allclose()`. Despite `torch.allclose()` returning `True`, indicating that the slices are numerically close within the function's tolerance levels, subtracting these slices' means shows non-zero differences, which is unexpected.

### To Reproduce

1. Run the following code snippet:

```python
import torch

device = "cpu"
loop = 10
scale = 123456000
rows = 10
left = 3
right = 3
columns = left + right

for i in range(loop):
    values = scale * torch.randn(
        (rows, columns), dtype=torch.float32, device=device
    )
    d = torch.allclose(values[:, :columns].mean(0)[:left], values[:, :left].mean(0))
    print(d, values[:, :columns].mean(0)[:left] - values[:, :left].mean(0))
```

```
#output
True tensor([-2., -2., -8.])
True tensor([-4.0000, -0.5000,  0.5000])
True tensor([ 4., -4.,  0.])
True tensor([8., 0., 2.])
True tensor([2., 4., 2.])
True tensor([2., 0., 0.])
True tensor([ 2.,  0., -2.])
True tensor([ 5.,  0., -4.])
True tensor([ 1.7500,  0.0000, -2.7500])
True tensor([0., 0., 4.])
```

Observe that `torch.allclose()` consistently returns True, yet the differences between the means of the slices show non-zero values.

If we use numpy

```python
import numpy as np

device = "cpu"
loop = 10
scale = 123456000
rows = 10
left = 3
right = 3
columns = left + right

for i in range(loop):
    values = scale * np.random.randn(
        rows, columns
    ).astype(np.float32)
    d = np.allclose(values[:, :columns].mean(0)[:left], values[:, :left].mean(0))
    print(d, values[:, :columns].mean(0)[:left] - values[:, :left].mean(0))
```

```
# output
True [0. 0. 0.]
True [0. 0. 0.]
True [0. 0. 0.]
True [0. 0. 0.]
True [0. 0. 0.]
True [0. 0. 0.]
True [0. 0. 0.]
True [0. 0. 0.]
True [0. 0. 0.]
True [0. 0. 0.]
```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.3 (arm64)
GCC version: (MacPorts gcc-devel 12-20221229_0+stdlib_flag) 13.0.0 20221229 (experimental)
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.24.4
Libc version: N/A

Python version: 3.11.7 (main, Jan  7 2024, 23:23:46) [Clang 16.0.3 ] (64-bit runtime)
Python platform: macOS-14.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==2.1.2
[pip3] torchinfo==1.8.0
[pip3] torchmetrics==1.3.0.post0
[pip3] torchvision==0.16.2
[conda] Could not collect
```

**Comment by albanD** [comment]
I'm afraid this is expected behavior: https://pytorch.org/docs/stable/notes/numerical_accuracy.html#batched-computations-or-slice-computations

The difference you see are very very small relative to the numbers you're considering (hence the fact that allclose is True).
Keep in mind that fp32 only has 7 digits of precision, so given your scale, anything at the scale of 1 is "garbage".

You should use fp64 if you expect this kind of precision.

The fact that numpy is close is most likely more due to chance and different parallelization strategies for numpy compared to PyTorch. Not something you should rely on.

**Comment by nasyxx** [comment]
> I'm afraid this is expected behavior: [pytorch.org/docs/stable/notes/numerical_accuracy.html#batched-computations-or-slice-computations](https://pytorch.org/docs/stable/notes/numerical_accuracy.html#batched-computations-or-slice-computations)

Thank you!

> The difference you see are very very small relative to the numbers you're considering (hence the fact that allclose is True). Keep in mind that fp32 only has 7 digits of precision, so given your scale, anything at the scale of 1 is "garbage".

Indeed, I scale before mean just to make the result more obvious.
