### ISSUE TITLE
Handling for negative indices in indrect_indexing can hurt perf

### ISSUE THREAD

**Issue by shunting314** [pytorch/pytorch#120452]
### 🐛 Describe the bug

Check the 8th kernel in https://github.com/pytorch/pytorch/issues/120423 . Kernel gist: https://gist.github.com/shunting314/ecd6d4525cf1ff635f0671a2065a39b1 . 

The kernel took 139us. NCU report that the kernel is neither membw or compute bound..

```
    WRN   This kernel exhibits low compute throughput and memory bandwidth utilization relative to the peak performance                                                         of this device. Achieved compute throughput and/or memory bandwidth below 60.0% of peak typically indicate
          latency issues. Look at Scheduler Statistics and Warp State Statistics for potential reasons.
```

Each thread uses 98 registers. So there is a register pressure.

If I manually remove all the code that handles negative index in the kernel: https://gist.github.com/shunting314/660945ddb26a779d37791e4272532e41 . The latency is improved to 88us due to reducing the register usage to 32 per thread!  (I don't know why this results such large reduction of register usage though).

Probably we should skip the handling for negative indices if it's safe.

### Versions

..

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by ezyang** [comment]
CC @eellison maybe value ranges can figure it out

**Comment by eellison** [comment]
it's doable but we'd need to propagate ranges between forward and backward. we should also b reducing dtype to int32 on saved indices.
