### ISSUE TITLE
torch._export.aot_compile doesnt preserve buffer mutations

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#120424]
repro:
```python
import torch

class Mod(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("buf", torch.arange(100, device='cuda') * 2)
    def forward(self, x):
        self.buf.mul_(2)
        return x + self.buf

x = torch.ones(100, device='cuda')
m = Mod()
# generated triton code mutates the buffer
out = torch.compile(m)(x)
# generated triton code does NOT mutate the buffer
so = torch._export.aot_compile(m, (x,))
```

If you run with `TORCH_LOGS="aot,output_code"`, you will see that the generated triton code in the aot_compile case does not actually mutate the input buffer.

cc @ezyang @msaroufim @anijain2305 @zou3519 @chauhang @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @desertfire @chenyang78

**Comment by bdhirsh** [comment]
I found that there were a few issues:

(1) The aot_compile() logic first runs `aot_export_module` to get an exported graph, and then tries to "unlift" the program into a GraphModule that properly has input mutations. It looks like this isn't properly preserving the `copy_` nodes in the graph today

(2) After fixing this, I still doin't see buffer mutations in the generated triton. It looks like in the aot_compile flow, the graph that we hand to `fx_compile_inner` does **not** have buffers lifted to graph inputs, and instead has them as attributes directly on the graph module, which inductor might need extra handling for:

This is the graph sent to the inference compiler in the example above:
```
graph():
    %l__self___buf : [num_users=2] = get_attr[target=L__self___buf]
    %arg1_1 : [num_users=1] = placeholder[target=arg1_1]
    %mul : [num_users=2] = call_function[target=torch.ops.aten.mul.Tensor](args = (%l__self___buf, 2), kwargs = {})
    %add : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%arg1_1, %mul), kwargs = {})
    %copy__default : [num_users=0] = call_function[target=torch.ops.aten.copy_.default](args = (%l__self___buf, %mul), kwargs = {})
    return (add,)
```

**Comment by jansel** [comment]
@desertfire what is the story on mutations in AOTInductor?  Is this something we are trying to support?
