### ISSUE TITLE
onnx export unsupported

### ISSUE THREAD

**Issue by JeeinOh** [pytorch/pytorch#120477]
### 🚀 The feature, motivation and pitch

This error message indicates that the PyTorch model you are trying to export to ONNX format is using an adaptive_avg_pool2d operation with output sizes that are not factors of the input size. The ONNX exporter currently does not support such configurations.

I appreciate it anyone who can handle this.

==========

Traceback (most recent call last):
  File "/home/jeein/Fp_match/torch2onnx/torch2onnx_afr.py", line 323, in <module>
    torch.onnx.export(model,dummy_img, config_vars['model_onnx'], 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeein/miniconda3/envs/fp/lib/python3.11/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/home/jeein/miniconda3/envs/fp/lib/python3.11/site-packages/torch/onnx/utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "/home/jeein/miniconda3/envs/fp/lib/python3.11/site-packages/torch/onnx/utils.py", line 1139, in _model_to_graph
    graph = _optimize_graph(
            ^^^^^^^^^^^^^^^^
  File "/home/jeein/miniconda3/envs/fp/lib/python3.11/site-packages/torch/onnx/utils.py", line 677, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeein/miniconda3/envs/fp/lib/python3.11/site-packages/torch/onnx/utils.py", line 1940, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeein/miniconda3/envs/fp/lib/python3.11/site-packages/torch/onnx/symbolic_helper.py", line 395, in wrapper
    return fn(g, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeein/miniconda3/envs/fp/lib/python3.11/site-packages/torch/onnx/symbolic_opset9.py", line 1900, in symbolic_fn
    return symbolic_helper._unimplemented(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeein/miniconda3/envs/fp/lib/python3.11/site-packages/torch/onnx/symbolic_helper.py", line 612, in _unimplemented
    _onnx_unsupported(f"{op}, {msg}", value)
  File "/home/jeein/miniconda3/envs/fp/lib/python3.11/site-packages/torch/onnx/symbolic_helper.py", line 623, in _onnx_unsupported
    raise errors.SymbolicValueError(
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of operator adaptive_avg_pool2d, output size that are not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues  [Caused by the value '518 defined in (%518 : Long(2, strides=[1], device=cpu) = onnx::Constant[value= 7  7 [ CPULongType{2} ]]()
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Constant'.] 

Inputs:
        Empty
Outputs:
        #0: 518 defined in (%518 : Long(2, strides=[1], device=cpu) = onnx::Constant[value= 7  7 [ CPULongType{2} ]]()
    )  (type 'Tensor')

====  my environment
pytorch                   2.1.1           py3.11_cuda11.8_cudnn8.7.0_0

**Comment by MaanavD** [comment]
Hi @JeeinOh , have you tried using our new `torch.onnx.dynamo_export` api for this? Please use that and ping me if you have any errors :)

**Comment by JeeinOh** [comment]
Hi @MaanavD,  thank you for your help. 
However, I'm having trouble finding examples of how to use it. how do I try the api, `torch.onnx.dynamo_export` ?  
I installed onnxscript, torchdynamo  under python 3.10.14, torch 2.2.2.

**Comment by JeeinOh** [comment]
> Hi @MaanavD, thank you for your help. However, I'm having trouble finding examples of how to use it. how do I try the api, `torch.onnx.dynamo_export` ? I installed onnxscript, torchdynamo under python 3.10.14, torch 2.2.2.

This is my current state .. 


`AttributeError                            Traceback (most recent call last)
Cell In[19], line 36
     31 dummy_img = torch.randint(0, 2, (1, 3, 512, 512), dtype=torch.float32)  # [0,2) 구간의 정수 랜덤 생성. 즉 0과 1로 이루어진 랜덤매트릭스
     32 print("dummy_data:", dummy_img.shape, dummy_img.dtype)
---> 36 torch.onnx.dynamo_export(model,dummy_img, f"./model_onnx/{model_name}.onnx" , #config_vars['model_onnx'], 
     37     export_params=True, 
     38     opset_version=16, 
     39     verbose=False,
     40     output_names = ['output'])
     42 print('*** Convert PTH file into ONNX : Complete')
     43 print(path_onnx)

File ~/miniconda3/envs/onnxtest/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py:1423, in dynamo_export(model, export_options, *model_args, **model_kwargs)
   1417     resolved_export_options = (
   1418         export_options
   1419         if isinstance(export_options, ResolvedExportOptions)
   1420         else ResolvedExportOptions(export_options, model=model)
   1421     )
   1422 else:
-> 1423     resolved_export_options = ResolvedExportOptions(ExportOptions(), model=model)
   1425 _assert_dependencies(resolved_export_options)
   1427 try:

File ~/miniconda3/envs/onnxtest/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py:364, in ResolvedExportOptions.__init__(self, options, model)
    358 @_beartype.beartype
    359 def __init__(
    360     self,
    361     options: Union[ExportOptions, "ResolvedExportOptions"],
    362     model: Optional[Union[torch.nn.Module, Callable, torch_export.ExportedProgram]] = None,  # type: ignore[name-defined]
    363 ):
--> 364     from torch.onnx._internal.fx import (  # TODO: Prevent circular dep
    365         diagnostics,
    366         dynamo_graph_extractor,
    367         torch_export_graph_extractor,
    368     )
    370     if isinstance(options, ResolvedExportOptions):
    371         self.dynamic_shapes = options.dynamic_shapes

File ~/miniconda3/envs/onnxtest/lib/python3.10/site-packages/torch/onnx/_internal/fx/diagnostics.py:10
      6 import logging
      8 from typing import Any, Optional
---> 10 import onnxscript  # type: ignore[import]
     11 from onnxscript.function_libs.torch_lib import graph_building  # type: ignore[import]
     13 import torch

File ~/miniconda3/envs/onnxtest/lib/python3.10/site-packages/onnxscript/__init__.py:7
      1 # -------------------------------------------------------------------------
      2 # Copyright (c) Microsoft Corporation. All rights reserved.
      3 # Licensed under the MIT License.
      4 # --------------------------------------------------------------------------
      5 import importlib.metadata
----> 7 from .backend.onnx_export import export2python as proto2python
      8 from .main import export_onnx_lib, graph, script
     10 # isort: off

File ~/miniconda3/envs/onnxtest/lib/python3.10/site-packages/onnxscript/backend/onnx_export.py:14
     11 from onnx import FunctionProto, GraphProto, ModelProto, TensorProto, ValueInfoProto
     12 from onnx.helper import make_node
---> 14 import onnxscript.onnx_types
     15 import onnxscript.type_annotation
     17 _SINGLE_INDENT = "    "

File ~/miniconda3/envs/onnxtest/lib/python3.10/site-packages/onnxscript/onnx_types.py:177
    173 class BFLOAT16(TensorType, dtype=onnx.TensorProto.BFLOAT16):
    174     pass
--> 177 class FLOAT8E4M3FN(TensorType, dtype=onnx.TensorProto.FLOAT8E4M3FN):
    178     pass
    181 class FLOAT8E4M3FNUZ(TensorType, dtype=onnx.TensorProto.FLOAT8E4M3FNUZ):

AttributeError: FLOAT8E4M3FN`

**Comment by MaanavD** [comment]
Hey @JeeinOh , the syntax is slightly different! Here are docs: 

https://pytorch.org/docs/stable/onnx_dynamo.html

In short, you want to write something along the lines of `onnx_program = torch.onnx.dynamo_export(model, tensor_x)` instead of your current call: `torch.onnx.dynamo_export(model,dummy_img, f"./model_onnx/{model_name}.onnx" , #config_vars['model_onnx'],`

and then you can run `onnx_program.save(f"./model_onnx/{model_name}.onnx")`

Let me know how that goes! If not, please attach a full repro script and we can continue helping from there :)

**Comment by thiagocrepaldi** [comment]
Closing as there is no repro nor response from op

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
