### ISSUE TITLE
Caching the Stable FeatureMaps

### ISSUE THREAD

**Issue by irfanbykara** [pytorch/pytorch#120495]
### 🚀 The feature, motivation and pitch

When doing transfer learning, most of the time we are freezing the feature extraction part of the network and just training the added layers. (Mostly fully connected) I was wondering if there is any cache mechanism to store the feature map of each input only once, instead of doing forward pass in each epoch in vain. If there is no such mechanism, it is not as efficient as it should be. Regards,

**Comment by drisspg** [comment]
Hey @irfanbykara  I think that the dev-discuss forums is a better place to post this: https://dev-discuss.pytorch.org/

I will close this for now
