### ISSUE TITLE
ReduceLROnPlateau.get_last_lr() mentioned in docs doesn't exist

### ISSUE THREAD

**Issue by till2** [pytorch/pytorch#120555]
### 📚 The doc issue

The ReduceLROnPlateau learning rate scheduler doesn't have the `get_last_lr()` nor the `print_lr` functions that are mentioned in its documentation page.

Referred docs:
https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.ReduceLROnPlateau.html#torch.optim.lr_scheduler.ReduceLROnPlateau.get_last_lr

Simple example:

```py
import torch
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau

def loss_function():
    # Dummy loss calculation
    return torch.ones(1, requires_grad=True)

model = torch.nn.Linear(10, 2)
optimizer = optim.SGD(model.parameters(), lr=0.1)
scheduler = ReduceLROnPlateau(optimizer, 'min', patience=3)

# Dummy training loop
for epoch in range(10):
    for _ in range(100):
        optimizer.zero_grad()
        loss = loss_function()
        loss.backward()
        optimizer.step()
    
    validation_loss = loss_function().item()
    scheduler.step(validation_loss)
    
    print(scheduler.get_last_lr()) # <<< function doesn't exist
    # works: print(optimizer.param_groups[0]['lr'])
```
```txt
>>> AttributeError: 'ReduceLROnPlateau' object has no attribute 'get_last_lr'
```

### Suggest a potential alternative/fix

The function should either be supported or removed from the docs.
For consistency, it would be best if it is supported as mentioned in the docs, for other schedulers (e.g. OneCycleLR) `scheduler.get_last_lr()` works.

**Comment by rambadi** [comment]
It works on my env. Coud be Pytorch version issue?
