### ISSUE TITLE
The release 2.2.1 is missing the source tarball

### ISSUE THREAD

**Issue by yurivict** [pytorch/pytorch#120515]
### 🐛 Describe the bug

The 2.2.0 tarball exists: http://distcache.FreeBSD.org/ports-distfiles/pytorch/pytorch-v2.2.0.tar.gz
but the 2.2.1 tarball is missing: http://distcache.FreeBSD.org/ports-distfiles/pytorch/pytorch-v2.2.1.tar.gz

The FreeBSD port uses these release tarballs to fetch sources including git submodules.

Could you please add http://distcache.FreeBSD.org/ports-distfiles/pytorch/pytorch-v2.2.1.tar.gz ?

Thank you,
Yuri

### Versions

2.2.1

cc @seemethere @malfet @osalpekar @atalman

**Comment by tringwald** [comment]
The `.tar.gz` file was added roughly 1 hour ago according to https://github.com/pytorch/pytorch/releases

**Comment by yurivict** [comment]
Thank you.
