### ISSUE TITLE
torch.nanmean() documentation does not mention that input has to be float or complex type

### ISSUE THREAD

**Issue by rambadi** [pytorch/pytorch#120570]
### 📚 The doc issue

>>> torch.tensor([1,2,3]).nanmean()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: nanmean(): expected input to have floating point or complex dtype but got Long

### Suggest a potential alternative/fix

Update documentation to mention that torch.nanmean() only accepts float or complex type.

cc @svekars @brycebortree

**Comment by janeyx99** [comment]
Hi, nans only make sense in the context of floats, so it would be better to clarify this in general nan docs versus in the `nanmean` op.
