### ISSUE TITLE
Pytorch support for Linux with Apple Silicon

### ISSUE THREAD

**Issue by BillyMazotti** [pytorch/pytorch#120557]
### 🚀 The feature, motivation and pitch

I am working on robotics projects that need Linux OS and a GPU, and my setup is Mac M1 with Ubuntu 22.04 running via VMWare Fusion. I would like to use my host machine's GPU device on my virtual machine. I created a similar post almost a year ago for a more specific problem[ #97188](https://github.com/pytorch/pytorch/issues/97188).

### Alternatives

I have little to no idea what I'm doing but here's what I've tried so far.

Trying to install the Stable (2.2.1) + Mac + Conda + Python + Default Pytorch package on my Ubuntu VM using `conda install pytorch::pytorch torchvision torchaudio -c pytorch` was unsuccessful with the following output
```
PackagesNotFoundError: The following packages are not available from current channels:

  - torchaudio
  - pytorch::pytorch
```

Based on [pytorch-aarch64](https://github.com/KumaTea/pytorch-aarch64?tab=readme-ov-file), I tried installing a aarch64 specific Pytorch build on my Ubuntu VM using `conda install -c kumatea pytorch`, however mps appears to still be unavailable
```
>>> import torch
>>> print(torch.backends.mps.is_available())
False
```

### Additional context

I've tried to look into if VMware is the problem and all my problems would be resolved if I just flashed Ubuntu on my Macbook, (a solution I that would not be the most appealing).

I recently created the discuss.pytorch.org post, [Does Pytorch Support Linux with Apple Silicon?](https://discuss.pytorch.org/t/does-pytorch-support-linux-with-apple-silicon/197626) where I used OpenGL to see if VMware is the reason for mps's unavailability. Irregardless, I'm left with the same question as the post:

1. Does there exist a Linux + arm64/aarch64 with M1 Pytorch build? (the primary question of this post)
2. Is VMware’s 3D acceleration actually permitting GPU passthrough?

Below is a screenshot of the discuss.pytorch.org quote:
![image](https://github.com/pytorch/pytorch/assets/96280520/c905b71a-28f6-4fba-9789-25e1c0258593)

Any thoughts/suggestions/etc would be greatly appreciated.

cc @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
Thank you for raising the issue. I'm going to close this issue, as it feels like main ask here is very similar to https://github.com/pytorch/pytorch/issues/81224 as MPS is MacOS specific feature and to the best of my knowledge there are no straightforward way to make it accessible from Linux VM. Please note that Linux AARCH64 wheels has been available for a while(see  https://pypi.org/project/torch/2.2.1/#files  for example) 
If you need conda packages for Linux aarch64, please do not hesitate to open a separate issue.

> Is VMware’s 3D acceleration actually permitting GPU passthrough?

I don't know answer to that question, but even if it did, MPS will not work, as it does not use OpenGL but rather Metal shaders which are only available on Mac platform. And "Compatibility Profile" in OpenGL often means that compute shaders will actually be executed on CPU
