### ISSUE TITLE
Ban or change behavior of TensorVariable.size

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#120568]
### 🐛 Describe the bug

Recent bug https://github.com/pytorch/pytorch/issues/120482 was due to someone directly accessing TensorVariable.size; fixed in https://github.com/pytorch/pytorch/pull/120567. But this field is None when the tensor has dynamic shapes. This is a dynamic shapes footgun. Either ban this, or change this to query size off of the fake tensor (and be willing to return SymInts).

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @aakhundov

**Comment by ezyang** [comment]
cc @yanboliang @eellison who were involved in https://github.com/pytorch/pytorch/pull/108182 which introduced the bug in this particular case

**Comment by Skylion007** [comment]
@ezyang Sounds like the fix would be a good backport candidate too?

**Comment by ezyang** [comment]
sure. i forgot how exactly the backport process works lol

**Comment by Skylion007** [comment]
@ezyang Just cherry pick a PR against the release branch. Then when the github tracking issue is made soon, just provide a link to the main and cherry pick PR. See the issue tracking for 2.2.1 for an example: https://github.com/pytorch/pytorch/issues/119295
