### ISSUE TITLE
Support re-inplacing for auto_functionalized

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#120509]
See https://github.com/pytorch/pytorch/issues/120441#issuecomment-1961550554.

Today, we turn mutable custom ops into functional variants via functionalization. This happens automatically via the auto_functionalized HOP. We don't end up replacing the functional variant with the original mutable custom op in Inductor, which leads to performance slowdowns.

cc @ezyang @msaroufim @bdhirsh @anijain2305

**Comment by desertfire** [comment]
@zou3519 , should we close this with https://github.com/pytorch/pytorch/pull/120829 landed?

**Comment by zou3519** [comment]
Yup, thanks for catching this.
