### ISSUE TITLE
[DTensor] Layer norm forward and backward incur collective for some shapes/shard dims

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#120542]
`CommDebugMode` was silently ignoring functional collectives in its `__torch_dispatch__`, so using it to check for collectives was always showing 0 collectives.

Avoiding the silent ignore (https://github.com/pytorch/pytorch/pull/118769), we see an extra collective (e.g. all-gather in layer norm forward) for some shapes and shard dimensions (but not all).

cc @wanchaol @XilunWu @tianyu-l

**Comment by wanchaol** [comment]
should be fixed by https://github.com/pytorch/pytorch/pull/121294
