### ISSUE TITLE
2 Dynamo test are failing with "invalid syntax (<unknown".

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#120647]
2 Dynamo test are failing with "invalid syntax (<unknown".

## Repro

`PYTORCH_TEST_WITH_DYNAMO=1 pytest test_quantization.py -v -k test_quantization_doc_fx`

You will need to remove the skip or expectedFailure before running the repro command.
This may be deleting a file in https://github.com/pytorch/pytorch/tree/main/test/dynamo_skips or https://github.com/pytorch/pytorch/tree/main/test/dynamo_expected_failures 

## Failing tests

Here's a comprehensive list of tests that fail (as of this issue) with the above message:
<details>
<summary>Click me</summary>
```
test_quantization.py::TestQuantizationDocs.test_quantization_doc_fx
test_quantization.py::TestQuantizationDocs.test_quantization_doc_qat
```
</details>

cc @ezyang @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by malfet** [comment]
Minimal reproducer:
```python
import torch

@torch.compile()
def foo(x, y):
    code = compile(y, "foo", "exec")
    exec(y)
    return x

print(foo(torch.rand(3), "print('Hello World')"))
```
