### ISSUE TITLE
6 Dynamo test are failing with "Failed running call_function <function tensor at 0xDEADBEEF".

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#120645]
6 Dynamo test are failing with "Failed running call_function <function tensor at 0xDEADBEEF".

## Repro

`PYTORCH_TEST_WITH_DYNAMO=1 pytest test_tensor_creation_ops.py -v -k test_cartesian_prod_cpu`

You will need to remove the skip or expectedFailure before running the repro command.
This may be deleting a file in https://github.com/pytorch/pytorch/tree/main/test/dynamo_skips or https://github.com/pytorch/pytorch/tree/main/test/dynamo_expected_failures 

## Failing tests

Here's a comprehensive list of tests that fail (as of this issue) with the above message:
<details>
<summary>Click me</summary>
```
test_tensor_creation_ops.py::TestTensorCreationCPU.test_cartesian_prod_cpu
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_qat_conv_bn_bias_derived_qspec
test_quantization.py::TestQuantizePT2E.test_derived_qspec
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_qat_conv_bn_bias_derived_qspec
functorch/test_eager_transforms.py::TestExamplesCorrectnessCPU.test_maml_regression_mechanism_functional_call_cpu
functorch/test_eager_transforms.py::TestExamplesCorrectnessCPU.test_maml_regression_mechanism_make_functional_cpu
```
</details>

cc @ezyang @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by ColinPeppler** [comment]
wip PR, waiting on CI tests to clear then will add details

https://github.com/pytorch/pytorch/pull/120872
