### ISSUE TITLE
[Dynamo] Inconsistent code with and without TYPE_CHECKING

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#120699]
### 🐛 Describe the bug

In https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/eval_frame.py , there is a code snippet:

```python
if TYPE_CHECKING:
    from torch._C._dynamo.eval_frame import (  # noqa: F401
        reset_code,
        set_eval_frame,
        set_guard_error_hook,
        skip_code,
        unsupported,
    )
else:
    for name in dir(torch._C._dynamo.eval_frame):
        if name.startswith("__"):
            continue
        globals()[name] = getattr(torch._C._dynamo.eval_frame, name)
```

There are two problems with this code snippet:

- Imported names are not the same: with `TYPE_CHECKING`, we import `reset_code/set_eval_frame/set_guard_error_hook/skip_code/unsupported`, but without `TYPE_CHECKING`, we would additionally import `_CacheEntry/_ExtraState/_debug_get_cache_entry_list`.
- Misleading code: with `TYPE_CHECKING`, it seems we can use `from torch._C._dynamo.eval_frame import set_eval_frame`. However, the code is in fact illegal, as `torch._C._dynamo` is not a package.

Maybe we can modify the code under `TYPE_CHECKING` to avoid these problems, such as `reset_code = torch._C._dynamo.eval_frame.reset_code`.

Would like to hear opinions from @jansel @ezyang and so on. If it is doable, I can submit a corresponding PR to fix it.

### Versions

2.3.0.dev20240226

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by youkaichao** [comment]
Plus: we also need to change the filter condition from `if name.startswith("__"):` to `if name.startswith("_"):` . This way, the names imported with and without `TYPE_CHECKING` would be consistent.

**Comment by jansel** [comment]
You can add more things to the TYPE_CHECKING list.

TYPE_CHECKING is only set when running lints with mypy.  PyTorch won't actually run or work with it enabled.  There are many places where it causes real functions to be replaced with fake functions that do nothing but have the right type signature.

**Comment by jansel** [comment]
Maybe we can just delete the `for name in dir(torch._C._dynamo.eval_frame)` loop and use a fixed set of imports.

**Comment by Skylion007** [comment]
We probably should look into enabling some of TCH ruff rules in PyTorch. I haven't gotten around it because I'm worried about imports that have side-effects, but it should let us move more things to TYPE_CHECKING etc.

**Comment by ezyang** [comment]
I'm with jansel, let's just enumerate the imports lol
