### ISSUE TITLE
[inductor] Difference between using `mode="reduce-overhead"` and directly recording the CUDAGraph for `mode="default"`

### ISSUE THREAD

**Issue by gs-olive** [pytorch/pytorch#120733]
## Issue description
If I call `torch.compile(model, mode="reduce-overhead")` versus use with `torch.cuda.graph(self.graph, pool=memory_pool): compiled_model(*inputs)` to record the kernels invoked by `mode="default"`, should I expect a difference in performance?

Additionally, CUDAGraphs with `mode="reduce-overhead"` seems to not allow mutated inputs, whereas `torch.cuda.graph` allows these to be recorded. Is this a limitation of the reduce-overhead mode, and are there any workarounds, for instance if there is a custom in-place-only kernel in the graph?

https://github.com/pytorch/pytorch/blob/f36e00b8cef66153ee210dc0781674bebfad4448/torch/_inductor/cudagraph_utils.py#L48-L50

## Code example

```python
import torch
import torchvision.models as models

model = models.resnet18(pretrained=True).eval().cuda().half()
inputs = [torch.rand((1, 3, 224, 224), dtype=torch.half).cuda()]

"""
Method 1
"""
reduce_overhead = torch.compile(model, mode="reduce-overhead")
reduce_overhead(*inputs)


"""
Method 2
"""
default = torch.compile(model, mode="default")
out = default(*inputs)

graph = torch.cuda.CUDAGraph()
with torch.cuda.graph(graph):
    out = default(*inputs)

graph.replay()
```

## System Info
```
torch==2.3.0.dev20240222+cu121
```

cc @mcarilli @ezyang @eellison @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

**Comment by desertfire** [comment]
cc @eellison

**Comment by eellison** [comment]
Some differences:

torch.cuda.Graph works over opaque python invocation. You might capture unsafe behavior such as unsupported operators or behavior which doesn't generalize to a specific trace. It won't support control flow and doesn't share memory across separate captures.

torch.compile intergration will do those things, but with the caveat that sometimes we bail out on cudagraphing a model if we deem it unsaf.e
