### ISSUE TITLE
On cuda 10: THCAtomics.cuh(100): error: cannot overload functions distinguished by return type alone

### ISSUE THREAD

**Issue by svenstaro** [pytorch/pytorch#12075]
## Issue description

Hello, I'm the maintainer of pytorch in Arch Linux. I'm trying to get it to build against cuda 10. It's currently blocking the move to cuda 10 so I'd like  to get this to build somehow.

Compiling pytorch 0.4.1 against cuda 10 fails with this shortened log:

```
/build/python-pytorch/src/pytorch-0.4.1-py2-cuda/aten/src/THC/THCAtomics.cuh(100): error: cannot overload functions distinguished by return type alone

/build/python-pytorch/src/pytorch-0.4.1-py2-cuda/aten/src/THC/THCAtomics.cuh(123): error: return value type does not match the function type

2 errors detected in the compilation of "/tmp/tmpxft_00001e9d_00000000-4_THCTensorIndex.cpp4.ii".
CMake Error at caffe2_gpu_generated_THCTensorIndex.cu.o.Release.cmake:279 (message):
  Error generating file
  /build/python-pytorch/src/pytorch-0.4.1-py2-cuda/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCTensorIndex.cu.o

make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/build.make:156: caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorIndex.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:968: caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 nanopb libshm gloo THD c10d'
```

## My build invocation

I'm building 0.4.1 release commit `a24163a`.

This is what I'm currently using to build this. You should be able to reproduce it using this.

    cd "$srcdir/${_pkgname}-${pkgver}-py2-cuda"
    CC=gcc-7 \
    CXX=g++-7 \
    WITH_CUDA=1 \
    CUDA_HOME=/opt/cuda \
    WITH_CUDNN=1 \
    CUDNN_LIB_DIR=/opt/cuda/lib64 \
    CUDNN_INCLUDE_DIR=/opt/cuda/include \
    python2 setup.py build

## System Info
Not applicable because I'm building in a clean chroot that has nothing to do with my system.

- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): see above
- OS: Arch Linux 
- PyTorch version: 0.4.1 commit a24163a
- Python version: 2.7/3.7 both fail
- CUDA/cuDNN version: 10.0/7.3.0
- GPU models and configuration: doesn't matter
- GCC version (if compiling from source): 7.3.1+20180814
- CMake version: 3.12.2
- Versions of any other relevant libraries: request them if you need any specifics

**Comment by t-vi** [comment]
I don't think you get CUDA10 compatibility without moving from 0.4.1. The master branch should build with cuda 10 thanks to fixes like #12017 .

**Comment by svenstaro** [comment]
Perhaps the changes could be backported. Alternatively a release based in current master could be made. Any idea on the timeframe on that?

**Comment by t-vi** [comment]
You should definitely backport that.
Regarding releases, [next week, we'll all know more.](https://pytorch.fbreg.com/schedule)

**Comment by jiecxy** [comment]
I got this same error too.
How can I fixed this? Thx
