### ISSUE TITLE
[RFC] python 3.8 builds / test deprecation

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#120718]
### 🚀 The feature, motivation and pitch

After addition of Python 3.12 to CI and nightly :
https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=3.12

We want to start process for deprecation of Python 3.8 from Pytorch CI and nightly builds. 

For versions of Python that we support we follow the [NEP 29 policy](https://numpy.org/neps/nep-0029-deprecation_policy.html), which was originally drafted by numpy:
- All minor versions of Python released 42 months prior to the project, and at minimum the two latest minor versions.
- All minor versions of numpy released in the 24 months prior to the project, and at minimum the last three minor versions.
For each minor version, we support all non-bugfix path versions if any otherwise only the latest bugfix path version
For past Python releases dates follow this [link](https://endoflife.date/python). 

Please note that this particular deprecation process has been followed by our team for more than a year now and it’s specified in the Pytorch[ Release document](https://github.com/pytorch/pytorch/blob/main/RELEASE.md#python).

I see 2 approaches for deprecation:

1. Go ahead deprecate Python 3.8 nightly before 3/11, release branch cut for 2.3 release:
https://dev-discuss.pytorch.org/t/pytorch-release-2-3-0-call-for-features/1872

2. Announce deprecation during release 2.3 and deprecate for release 2.4. This is more conservative but perhaps better approach to give everyone time to adjust the workflows and switch existing jobs that use Python 3.8 to 3.9 or 3.10

cc @malfet @seemethere @pytorch/pytorch-dev-infra @albanD @ezyang

**Comment by atalman** [comment]
Approach 2 seems best: 
Announce deprecation during release 2.3 and deprecate for release 2.4. This is more conservative but perhaps better approach to give everyone time to adjust the workflows and switch existing jobs that use Python 3.8 to 3.9 or 3.10

Hence timeline for deprecation will be:
Start Deprecation 3.8 from CI in end of April 2024
Complete deprecation by end of May 2024 by removing 3.8 builts from pytorch nightly

**Comment by albanD** [comment]
From offline discussion: please update our general policy to mention that we will always do this "deprecation" for one release before dropping a CPython version.

**Comment by malfet** [comment]
IMO we should make the deprecation if and only if we achieve feature parity between newest and latest Python versions. Right now python-3.12 lacks torch.compile support, and if adding it  is not planned for 2.4 branch cut, then deprecation would probably be the wrong move

**Comment by atalman** [comment]
For reference here is the torch compile issue: https://github.com/pytorch/pytorch/issues/120233

**Comment by atalman** [comment]
pypi download stats for last 3 month see:
https://cloud.google.com/blog/topics/developers-practitioners/analyzing-python-package-downloads-bigquery

| Python | Count |
-- | --
3.8 | 13928578 |
3.9 |  9435245 |
3.10 | 17352293 |  
3.11 |   5975606 |  
3.12 | 1585867 |

**Comment by atalman** [comment]
Given high download count for Python 3.8. I propose to deprecate it for EOL.
Python 3.8 EOL is 2024-10. Release 2.5 projected date is also 2024-10: https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-cadence

Hence suggestion is to announce deprecation for PyTorch 2.4 release. Deprecate it for 2.5 release.
