### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator aten::std

### ISSUE THREAD

**Issue by wangyunxiaa** [pytorch/pytorch#12084]
hello,
I want to convert torch-model to onnx, I can transfrom the "alex-net" which is downloaded from network, but i have an error like
"/home/yunxiawang/anaconda2/envs/py3onnxsource/lib/python3.6/site-packages/torch/onnx/utils.py:447: UserWarning: ONNX export failed on ATen operator std because torch.onnx.symbolic.std does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "torch2onnx.py", line 31, in <module>
    output = torch_onnx.export(lang_model, dummy_input, "vpmodel.onnx", export_params=False, verbose=False)
  File "/home/yunxiawang/anaconda2/envs/py3onnxsource/lib/python3.6/site-packages/torch/onnx/__init__.py", line 26, in export
    return utils.export(*args, **kwargs)
  File "/home/yunxiawang/anaconda2/envs/py3onnxsource/lib/python3.6/site-packages/torch/onnx/utils.py", line 94, in export
    operator_export_type=operator_export_type)
  File "/home/yunxiawang/anaconda2/envs/py3onnxsource/lib/python3.6/site-packages/torch/onnx/utils.py", line 234, in _export
    proto, export_map = graph.export([], _onnx_opset_version, False, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::std" 
when i try to transfrom my own model
my environment is: cpu  python=3.6,torch=0.4.1(pip install)
I have found the question,because i have used "torch.std" in my net, maybe it is not supported by onnx1.3.0

**Comment by vimalthilak** [comment]
Any update on whether torch.std() is supported for conversion to ONNX?

**Comment by garymm** [comment]
I believe this was fixed by https://github.com/pytorch/pytorch/pull/22310

If not please open a new issue with code that can be used to reproduce.
