### ISSUE TITLE
[feature request] API to change loc and scale to cuda tensor in torch.distributions.Normal

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#12082]
## Issue description
When I use some functions in Distribution with CUDA tensors, it will fail.
```
m = torch.distributions.Normal(0, 1)
>>> m.cdf(torch.tensor(.5, device='cuda'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qbx2/anaconda3/lib/python3.6/site-packages/torch/distributions/normal.py", line 72, in cdf
    return 0.5 * (1 + torch.erf((value - self.loc) * self.scale.reciprocal() / math.sqrt(2)))
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #3 'other'
```

I think it is helpful if there is to() or cuda() to move internal variables to wanted device.

I temporarily solved the problem by
```
>>> m.loc = m.loc.to('cuda')
>>> m.scale = m.scale.to('cuda')
>>> m.cdf(torch.tensor(.5, device='cuda'))
tensor(0.6915, device='cuda:0')
```
It would be easy to add the function, how do you think?

## System Info
- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source):
- OS: Ubuntu 18.04 LTS
- PyTorch version: a24163a95edb193ff7b06e98cd69bf7cfd4c0d2f (I've checked the source in master though)
- Python version: 3.6.5+
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by vishwakftw** [comment]
cc: @fritzo I believe this related to https://github.com/pytorch/pytorch/issues/7795 .

**Comment by qbx2** [comment]
Oh, yeah. Closing by duplication. Thanks.
