### ISSUE TITLE
Where to specify CMAKE_INSTALL_PREFIX ?

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#12081]
Hi, I'm using the command `NO_TEST=1 USE_MKLDNN=1 FULL_CAFFE2=1 python setup.py build`
to build **pytorch**, but where to specify **CMAKE_INSTALL_PREFIX** ?

Without specifying **CMAKE_INSTALL_PREFIX**, **CMAKE_INSTALL_PREFIX** will be **./torch/lib/tmp_install** by default, which is NOT what I expected. I'm expecting the built file to be installed under **/usr/local** ...

Any suggestions please?

Pei

**Comment by soumith** [comment]
if you use `python setup.py ` it will use python conventions, and will build a python package. Hence it wont be built or installed in /usr/local
