### ISSUE TITLE
No module named future

### ISSUE THREAD

**Issue by mingminzhen** [pytorch/pytorch#12088]
I try to use the torch_nightly version (https://download.pytorch.org/whl/nightly/cu92/torch_nightly-1.0.0.dev20180925-cp36-cp36m-linux_x86_64.whl). When i try the cpp__extension, the error occurs.

The code:
```
from torch.utils.cpp_extension import BuildExtension, CUDAExtension
```
error is
```
ModuleNotFoundError: No module named 'future'

```

**Comment by vishwakftw** [comment]
Related to https://github.com/pytorch/pytorch/issues/11995

**Comment by vishwakftw** [comment]
Could you try now? A patch has been sent in that fixes the problem.

**Comment by zou3519** [comment]
Closing based on @vishwakftw's comments. Please feel free to reopen if it is not resolved, @mingminzhen
