### ISSUE TITLE
Inconsistent Behavior of torch.clamp with NaN Values on MPS Device

### ISSUE THREAD

**Issue by JingangQu** [pytorch/pytorch#120899]
### 🐛 Describe the bug

I have encountered an issue with the torch.clamp function in PyTorch when it is used on tensors that reside on the Metal Performance Shaders (MPS) device. Specifically, the function behaves differently with NaN values on tensors across different devices (mps vs. cpu/cuda). This inconsistency can lead to unexpected results when working with NaN values on MPS devices.

When using torch.clamp on a tensor with NaN values on an MPS device, If both min and max parameters are set, the function replaces NaN values with the min value. If only one of min and max parameters are set, the function replaces NaN values with the min value. If only one of the min and max parameters is set, the function replaces NaN values with the specified min or max parameter.

This behavior is inconsistent with how torch.clamp operates on the same tensor when it is on a CPU device, where NaN values remain unchanged.

```python
import torch

t_mps = torch.tensor([torch.nan, 1, 2], device="mps")
print(torch.clamp(t_mps, min=-100, max=100))
# tensor([-100.,    1.,    2.], device='mps:0')
print(torch.clamp(t_mps, min=-100))
# tensor([-100.,    1.,    2.], device='mps:0')
print(torch.clamp(t_mps, max=100))
# tensor([100.,   1.,   2.], device='mps:0')

t_cpu = torch.tensor([torch.nan, 1, 2], device="cpu")
print(torch.clamp(t_cpu, min=-100, max=100))
# tensor([nan, 1., 2.])
print(torch.clamp(t_cpu, min=-100))
# tensor([nan, 1., 2.])
print(torch.clamp(t_cpu, max=100))
# tensor([nan, 1., 2.])
```

Expected Behavior:
The behavior of torch.clamp should be consistent across different devices. When dealing with NaN values, torch.clamp should not replace NaN values.

### Versions

PyTorch version: 2.2.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.3.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:35:41)  [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.1
[pip3] torchaudio==2.2.1
[pip3] torchvision==0.17.1
[conda] numpy                     1.26.4           py39h7aa2656_0    conda-forge
[conda] pytorch                   2.2.1                   py3.9_0    pytorch
[conda] torchaudio                2.2.1                  py39_cpu    pytorch
[conda] torchvision               0.17.1                 py39_cpu    pytorch

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by JingangQu** [comment]
Interestingly, the following code works.

```python
t_mps = torch.tensor([torch.nan, 1, 2], device="mps")
t_mps[t_mps < -100] = -100
t_mps[t_mps > 100] = 100
print(t_mps)
# tensor([nan, 1., 2.], device='mps:0')
```

**Comment by atalman** [comment]
Validated with 2.3.0
```
tensor([nan, 1., 2.], device='mps:0')
tensor([nan, 1., 2.], device='mps:0')
tensor([nan, 1., 2.], device='mps:0')
tensor([nan, 1., 2.])
tensor([nan, 1., 2.])
tensor([nan, 1., 2.])
```
