### ISSUE TITLE
DISABLED test_dispatch_symbolic_meta_outplace_all_strides_nn_functional_scaled_dot_product_attention_cuda_float32 (__main__.TestMetaCUDA)

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#120921]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22test_meta.py%3A%3ATestMetaCUDA%3A%3Atest_dispatch_symbolic_meta_outplace_all_strides_nn_functional_scaled_dot_product_attention_cuda_float32%22%5D)).

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
Broken by https://github.com/pytorch/pytorch/pull/120682?

**Comment by davidberard98** [comment]
gonna leave it open for a bit to keep CI green
