### ISSUE TITLE
autograd_inlining flag to torch.onnx.export patch does not work in torch 2.0.1

### ISSUE THREAD

**Issue by sheetalarkadam** [pytorch/pytorch#120924]
### 🐛 Describe the bug

Regression to #104067 
I am trying to apply  it as a patch to pytorch 2.0.1 but it fails to apply with the following error message
error: patch failed: torch/onnx/_globals.py:29
error: torch/onnx/_globals.py: patch does not apply

Steps used to apply patch:
```
git clone  https://github.com/pytorch/pytorch.git
git checkout v2.0.1
git apply autograd_inling.patch
```

The PR #104067 was merged in torch 2.1.0
Patch file: [autograd_inling.patch](https://github.com/pytorch/pytorch/files/14451865/autograd_inling.patch)

The files in the PR do not exist before pytorch 1.12.0
### Versions

pytorch 2.0.1
cuda 11.7, 11.8

**Comment by thiagocrepaldi** [comment]
let me see if i can fix the patch for you

**Comment by thiagocrepaldi** [comment]
[0001-autograd_inling_new.patch.patch](https://github.com/pytorch/pytorch/files/14485104/0001-autograd_inling_new.patch.patch)
Can you try this patch instead?

**Comment by sheetalarkadam** [comment]
I was able to build the image with this patch. Thanks!
