### ISSUE TITLE
DISABLED test_dispatch_meta_outplace_nn_functional_scaled_dot_product_attention_cuda_float32 (__main__.TestMetaCUDA)

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#120922]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22test_meta.py%3A%3ATestMetaCUDA%3A%3Atest_dispatch_meta_outplace_nn_functional_scaled_dot_product_attention_cuda_float32%22%5D)).

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
Another one broken by https://github.com/pytorch/pytorch/pull/120682 ?  Can we revert?  @davidberard98

**Comment by davidberard98** [comment]
@jeffdaily AFAIK these are the only two tests that are broken, which I manually disabled. By broken, I mean that they are marked as "expecting failure" for CUDA, but don't fail on ROCM.

Do you think it's okay to leave the as DISABLED for a bit while I investigate? AFAIK, it's expected that these tests will fail but also not a problem if they pass. I'm going to try to understand the reason for the pass and then either update the xfails or mark them as skipped
