### ISSUE TITLE
[ONNX] `test_fx_op_consistency.py` some cases success without running

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#120918]
Found in ops: nn.functional.instance_norm from https://github.com/pytorch/pytorch/pull/120866

**Comment by BowenBao** [comment]
Very likely because of this

https://github.com/titaiwangms/pytorch/blob/0505fb21c9f157a1274c79ecb7f95cd9d80c3e85/test/onnx/test_fx_op_consistency.py#L1790-L1794

https://github.com/titaiwangms/pytorch/blob/0505fb21c9f157a1274c79ecb7f95cd9d80c3e85/test/onnx/test_fx_op_consistency.py#L1801-L1812

**Comment by titaiwangms** [comment]
> Very likely because of this
> 
> https://github.com/titaiwangms/pytorch/blob/0505fb21c9f157a1274c79ecb7f95cd9d80c3e85/test/onnx/test_fx_op_consistency.py#L1790-L1794
> 
> https://github.com/titaiwangms/pytorch/blob/0505fb21c9f157a1274c79ecb7f95cd9d80c3e85/test/onnx/test_fx_op_consistency.py#L1801-L1812

I thought these two should be categorized to xfail?
