### ISSUE TITLE
DISABLED test_dispatch_symbolic_meta_outplace_nn_functional_scaled_dot_product_attention_cuda_float32 (__main__.TestMetaCUDA)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#120940]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22test_meta.py%3A%3ATestMetaCUDA%3A%3Atest_dispatch_symbolic_meta_outplace_nn_functional_scaled_dot_product_attention_cuda_float32%22%5D)).

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by bdhirsh** [comment]
I see an unexpected success in the logs, so maybe we just need to remove the xfail for rocm? https://www.torch-ci.com/failure?failureCaptures=%5B%22test_meta.py%3A%3ATestMetaCUDA%3A%3Atest_dispatch_symbolic_meta_outplace_nn_functional_scaled_dot_product_attention_cuda_float32%22%5D
