### ISSUE TITLE
Spectral Norm doesn't appear to work on complex-valued networks

### ISSUE THREAD

**Issue by redwrasse** [pytorch/pytorch#121091]
### 🐛 Describe the bug

The spectral norm (referring to the implementation in https://github.com/pytorch/pytorch/blob/main/torch/nn/utils/parametrizations.py but applies likely to old implementation in `spectral_norm.py` as well) doesn't appear to work on complex-valued networks.

```python
import torch
import torch.nn as nn

def sanity_check_spectral_norm(dtype):
    """
    Check that the spectral norm is indeed correctly computed
    for a simple transformation diag(2., 1.). (spectral norm = 2.)
    """
    net = nn.Linear(2, 2).to(dtype)
    with torch.no_grad():
        # top singular value is 2 = spectral norm
        id = torch.diag(torch.tensor([2., 1.], dtype=dtype))
        net.weight = nn.Parameter(id)
        # weights should be rescaled by spectral norm
        torch.nn.utils.parametrizations.spectral_norm(net, n_power_iterations=400)
        # weights should now be diag(1., 0.5)
        assert torch.allclose(net.weight, torch.diag(torch.tensor([1., 0.5])))


# works for floats
sanity_check_spectral_norm(torch.float)

# doesn't work for complex-valued floats
sanity_check_spectral_norm(torch.cfloat)

```
Perhaps the implementation is not intended to support complex-valued transformations. However, the power iteration method does apply to complex numbers.

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.26.0
Libc version: N/A

Python version: 3.11.6 (main, Nov  2 2023, 04:39:40) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-12.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.7.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.10.0
[pip3] torch==2.0.0
[conda] No relevant packages

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @ezyang @anjali411 @dylanbespalko @Lezcano @nikitaved @amjames

**Comment by vadimkantorov** [comment]
A bit related: https://github.com/pytorch/pytorch/issues/12760 . Also, if the impl of spectral norm is factored out / available as a regular method, it could also be more battle-tested, even outside of the reparametrization context...

**Comment by redwrasse** [comment]
Thanks for sharing @vadimkantorov . I am all in favor of generalizing and hardening testing of the implementation, treating it as a general linear algebra tool.
