### ISSUE TITLE
Compiler warnings for `ForeachReduceOp.cu`

### ISSUE THREAD

**Issue by tringwald** [pytorch/pytorch#121077]
### 🐛 Describe the bug

When compiling `ForeachReduceOp.cu`, there are some dozen compiler warnings like this:
```
/.../aten/src/ATen/native/cuda/ForeachReduceOp.cu: In lambda function:
/.../aten/src/ATen/native/cuda/ForeachReduceOp.cu:250:3921: warning: comparison of integer 
expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} 
[-Wsign-compare]
  250 |     AT_DISPATCH_FLOATING_TYPES_AND2(
      |      

[snipped like 20 line breaks]
```

For some reason, the warnings have a lot of whitespace added (I assume because of the `AT_DISPATCH` macro) and generate multiple console windows of output. Fixing this should be quite straightforward.

### Versions

`main`

**Comment by CandidlyRed** [comment]
Hi @tringwald, I'd like to work on this. Can you assign it to me?

**Comment by tringwald** [comment]
Sure, let me know if you need any help if this is your first contribution.

**Comment by CandidlyRed** [comment]
Thanks!

**Comment by cyyever** [comment]
@tringwald I happened to notice the warnings and posted a related PR #121066

**Comment by tringwald** [comment]
> @tringwald I happened to notice the warnings and posted a related PR #121066

Thanks for putting up the PR! I guess we were both annoyed by this at the same time 😄.

**Comment by cyyever** [comment]
> > @tringwald I happened to notice the warnings and posted a related PR #121066
> 
> Thanks for putting up the PR! I guess we were both annoyed by this at the same time 😄.

I was surprised by the warnings when I checked the build log last night...

**Comment by CandidlyRed** [comment]
Sorry, I've been running through some issues trying to compile it. I would love some pointers if you could @tringwald 

It seems that neither my mac M1 nor windows computer with intel iRIS xe is Cuda compatible. Is there a way to get around this?

Sorry about this. If this issue requires a Cuda-compatible machine, I don't have one near me to run it. (Sorry I was a bit eager to try and contribute and didn't look ahead). But if it's possible, please let me know!

Thanks!

**Comment by tringwald** [comment]
> It seems that neither my mac M1 nor windows computer with intel iRIS xe is Cuda compatible. Is there a way to get around this?
> Sorry about this. If this issue requires a Cuda-compatible machine, I don't have one near me to run it. (Sorry I was a bit eager to try and contribute and didn't look ahead). But if it's possible, please let me know!

The easiest way is probably to setup a Docker container with the necessary dependencies for a CUDA build. AFAIK you don't actually need an NVIDIA GPU to build CUDA code. However, you would not be able to run it for local tests, which can be painful sometimes.

W.r.t. this issue, @cyyever did already put up a PR to fix the compiler warnings, so I'm afraid there's nothing more to do. Sorry for that!
