### ISSUE TITLE
Memory leak when attempting to turn ascii-encoded data from an hdf5 file into a torch tensor in a try-except block

### ISSUE THREAD

**Issue by KBergst** [pytorch/pytorch#121138]
### 🐛 Describe the bug

I have a number of datasets in hdf5 files which I wish to turn into torch tensors. Most are numeric data, but some are ascii-encoded strings which need further processing before being turned into tensors. I tried to handle this using a try-except block where I tried to use `from_numpy` to convert each dataset into a tensor, and when the ascii-encoded datasets threw a `TypeError` exception I'd do the processing for those. This procedure accumulates memory when repeated multiple times, eventually filling up the CPU if allowed to. I note that this only happens when the datasets are read from a hdf5 file, numpy arrays of ascii-encoded strings do not cause the same issue. I am using h5py version 3.7.0.

Example script:
```
import torch
import numpy as np
import h5py
import sys
import psutil
process = psutil.Process()
print(process.memory_info().rss/1024/1024)  # used memory in mb
outfile="testingmemleak.h5"

fill_value = "value".encode('ascii')
large_array_bad = np.full((400,2000,8), fill_value)
# write a nice file
with h5py.File(outfile, 'w') as file:
    file.create_dataset('bad', data=large_array_bad)
print(process.memory_info().rss/1024/1024)

for i in range(100):
    # read a nice file
    data_dict={}  # cleared each iteration so memory should stay constant
    with h5py.File(outfile,'r') as file:
        for label, data in file.items():
            data_dict[label] = data[()]
    print(process.memory_info().rss/1024/1024)
    tensor_data = []  # cleared each iteration so memory should stay constant
    for label, data in data_dict.items():  # try to convert to torch tensors
        try:
            tensor = torch.from_numpy(data)
            tensor_data.append(tensor)
        except TypeError:
            print("couldn't convert from numpy")
    print(process.memory_info().rss/1024/1024)
    if process.memory_info().rss/1024/1024 > 1000:
        sys.exit("Too much memory used")
```
This bug can be avoided by not using the try except block and instead doing e.g.  `if (dtype accepted by from_numpy): <convert to tensor> else: <process encoded data>`.
In my original code I was putting the tensors onto a GPU after converting them from numpy, but the memory accumulation error was still happening on the CPU.
Let me know if you need any more information. Thank you.

### Versions

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux release 8.9 (Ootpa) (ppc64le)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)
Clang version: Could not collect
CMake version: version 3.26.5
Libc version: glibc-2.28

Python version: 3.10.9 (main, Jan 11 2023, 15:16:01) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-513.11.1.el8_9.ppc64le-ppc64le-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:        ppc64le
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  4
Core(s) per socket:  16
Socket(s):           2
NUMA node(s):        6
Model:               2.3 (pvr 004e 1203)
Model name:          POWER9, altivec supported
CPU max MHz:         3800.0000
CPU min MHz:         2300.0000
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            10240K
NUMA node0 CPU(s):   0-63
NUMA node8 CPU(s):   64-127
NUMA node252 CPU(s): 
NUMA node253 CPU(s): 
NUMA node254 CPU(s): 
NUMA node255 CPU(s):

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.12.1
[pip3] torchinfo==1.8.0
[pip3] torchtext==0.13.1a0+35066f2
[pip3] torchvision==0.13.1
[conda] _pytorch_select           2.0                      cuda_2    https://opence.mit.edu/
[conda] cudatoolkit               11.4.4              h5d40d8d_10    https://opence.mit.edu/
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-base                1.23.5          py310hac71eb6_0    anaconda
[conda] pytorch                   1.12.1          cuda11.4_py310_1    https://opence.mit.edu/
[conda] pytorch-base              1.12.1          cuda11.4_py310_pb3.19_2    https://opence.mit.edu/
[conda] torch                     1.12.1                   pypi_0    pypi
[conda] torchinfo                 1.8.0              pyhd8ed1ab_0    conda-forge
[conda] torchtext                 0.13.1a0+35066f2          pypi_0    pypi
[conda] torchtext-base            0.13.1          cuda11.4_py310_1    https://opence.mit.edu/
[conda] torchvision               0.13.1                   pypi_0    pypi
[conda] torchvision-base          0.13.1          cuda11.4_py310_1    https://opence.mit.edu/
​

cc @mruberry @rgommers

**Comment by tringwald** [comment]
Thank you for your bug report. I have confirmed the leak and put up a PR fixing it.
