### ISSUE TITLE
PYBIND_MODULE is broken: error: expected constructor, destructor, or type conversion before '(' token

### ISSUE THREAD

**Issue by alsrgv** [pytorch/pytorch#12110]
The break occurred between torch_nightly-1.0.0.dev20180924-cp27-cp27mu-linux_x86_64.whl and torch_nightly-1.0.0.dev20180925-cp27-cp27mu-linux_x86_64.whl.  The error is:
```
    horovod/torch/mpi_ops_v2.cc:236:16: error: expected constructor, destructor, or type conversion before '(' token
     PYBIND11_MODULE(mpi_lib_v2, m) {
                    ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

cc @soumith

**Comment by alsrgv** [comment]
Resolved by adding `-DTORCH_API_INCLUDE_EXTENSION_H`.

**Comment by Google1234** [comment]
I wonder why add DTORCH_API_INCLUDE_EXTENSION_H works?
