### ISSUE TITLE
MPS memory leak in training

### ISSUE THREAD

**Issue by dmahurin** [pytorch/pytorch#121113]
### 🐛 Describe the bug

When using transformers Trainer on MPS hardware, after several hundred iterations, getting "MPS out of memory".

Test code and output at:
https://gist.github.com/dmahurin/fe202511a1b3314faf248d728cdb1d71

Note that when training data is of varying data lengths, the condition seems to reproduce more.

While training, MPS allocated memory seems unchanged, but MPS backend memory runs out.

### Versions

Collecting environment information...
PyTorch version: 2.3.0.dev20240122
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.2.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.3
Libc version: N/A

Python version: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] (64-bit runtime)
Python platform: macOS-14.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2

Versions of relevant libraries:
[pip3] mypy==1.7.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] onnx==1.15.0
[pip3] onnxruntime==1.16.3
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-lightning==1.9.4
[pip3] pytorch-memlab==0.3.0
[pip3] torch==2.3.0.dev20240122
[pip3] torch-mlir==20240127.1096
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==1.3.0.post0
[pip3] torchsde==0.2.6
[pip3] torchvision==0.18.0.dev20240122
[conda] Could not collect

Also:

[pip3] transformers==4.37.2

cc @ezyang @gchanan @zou3519 @kadeng @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by albertmichaelj** [comment]
I'm seeing something very similar during classification with a bert based model. If I set the padding_option to 'max_length' there is no memory leak, but if not, the memory usage skyrockets quite quickly.

**Comment by kulinseth** [comment]
Hi, I haven't dug into too much details on this.. Do you know what `padding_option=max_length` do in the transformers package ? I am curious if there is dynamic slicing going on which is causing leak somewhere.

**Comment by skotapati** [comment]
Hello, a fix for this issue will be available in a future update of MacOS

**Comment by minhquoc0712** [comment]
Hi, I’m experiencing this error on macOS 15.4.1. Memory usage increases after each iteration.
