### ISSUE TITLE
fft_fft2 support to ONNX opset version 11

### ISSUE THREAD

**Issue by amiraghabiglou** [pytorch/pytorch#121130]
### 🐛 Describe the bug

Exporting the operator 'aten::fft_fft2' to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

### Versions

Exporting the operator 'aten::fft_fft2' to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

**Comment by thiagocrepaldi** [comment]
torch.onnx.export does not support this operator and we don't have plans to support it.

Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

**Comment by EvelynCarter** [comment]
import onnx
print(onnx.__version__)
print(onnx.checker.check_version())
