### ISSUE TITLE
Intel MKL Error when sending inf to torch.linalg.eigvals

### ISSUE THREAD

**Issue by drewshark** [pytorch/pytorch#121149]
### 🐛 Describe the bug

When sending matrix with all infinity value to torch.linalg.eigvals, the program raises the segmentation fault with the Intel MKL Error

```python
import torch

A = torch.full((2, 2), torch.inf)
torch.linalg.eigvals(A)
```

```
Intel MKL ERROR: Parameter 3 was incorrect on entry to SGEBAL.
Segmentation fault (core dumped)
```

### Versions

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.1.0+cu121
[pip3] torchaudio==2.1.0+cu121
[pip3] torchdata==0.7.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.16.0
[pip3] torchvision==0.16.0+cu121
[pip3] triton==2.1.0

cc @ezyang @gchanan @zou3519 @kadeng @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano @gujinghui @PenghuiCheng @XiaobingSuper @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen

**Comment by malfet** [comment]
Edited example a bit and can confirm the crash.
It works fine using OpenBLAS/Accelerate, though error message can be improved:
```
>>> import torch
A = torch.full((2, 2), torch.inf)
A
>>> A = torch.full((2, 2), torch.inf)
>>> A
tensor([[inf, inf],
        [inf, inf]])
>>> torch.linalg.eigvals(A)
** On entry to SGEBAL, parameter number  3 had an illegal value
** On entry to SGEHRD, parameter number  2 had an illegal value
** On entry to SHSEQR, parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: false INTERNAL ASSERT FAILED at "/Users/nshulga/git/pytorch/pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp":1536, please report a bug to PyTorch. torch.linalg.eigvals: Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
```

**Comment by lezcano** [comment]
This is among the expected things that can happen. This is documented in https://pytorch.org/docs/master/notes/numerical_accuracy.html#non-finite-values. Passing non-finite values to anything in `torch.linalg` is considered UB. If you want to harden any of these functions, you should perform a is_finite check on the inputs.
