### ISSUE TITLE
Provide some way to specify custom ops that cannot be constant propped?

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#121270]
Consider the following custom op signature
```
open_file_or_something(str filename) -> Tensor
```
Today, we are free to (and almost certainly going to) constant prop this in PT2, since we treat `str`s as constant values. This is not safe, as the custom operator has a side effect (file IO) that is not captured.

Our schema language has facilities for expressing aliasing and mutation on tensors, but I don't believe it has a general way to say that a function may have arbitrary side effects.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by zou3519** [comment]
This rolls into the effect tokens work that @angelayi has been working on. In a functional IR, pass writers can constant prop as much as they want. We can prevent constant prop by threading a token through the operation.

In the use case we ran into here, the user actually wanted a TorchBind object as a return, so we will end up threading the token through after TorchBind support works. But in general we should have some other way to specify that non-TorchBind custom ops can get side effects.

**Comment by suo** [comment]
Yeah, there are two issues:
* Extending the schema language to allow people to express general side-effectfulness.
* Properly handling side-effecting custom ops by threading a token.

**Comment by IvanKobzarev** [comment]
Doing issue scrapping , closing , as effectful ops logic was landed.
