### ISSUE TITLE
Request to upgrade MKL of PyTorch

### ISSUE THREAD

**Issue by CaoE** [pytorch/pytorch#121201]
### 🚀 The feature, motivation and pitch

nightly torch is built with MKL 2022.0:
```
[Info] Running torch.compile() Float32 with default backend MKL_VERBOSE oneMKL 2022.0 Update 2 Product build 20220804 for Intel(R) 64 architecture Intel(R) Advanced Vector Extensions 512 (Intel(R) AVX-512) with Intel(R) DL Boost, bfloat16 support, Intel(R) AMX with bfloat16 and 8-bit integer support, and FP16 instructions, Lnx 0.90GHz lp64 gnu_thread
```

PyTorch with MKL >= 2024.0 supports the `mkl_gemm_f16f16f32` for flash attention. Currently, FP16 flash attention will be very slow because it can only use the fallback gemm.

### Additional context

Related PRs:
https://github.com/pytorch/pytorch/pull/118367
https://github.com/pytorch/pytorch/pull/118368

**Comment by drisspg** [comment]
Adding Triage review to to determine what is the proper label for this
