### ISSUE TITLE
Libtorch  https://download.pytorch.org/libtorch/nightly/cu121/index.html is not getting updated

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#121237]
### 🐛 Describe the bug

We do have  following:
https://download.pytorch.org/libtorch/nightly/cu121/index.html

However its outdated and does not include latest nightly builds.

Investigate use case for index.html and either delete the index.html since libtorch is not installed via pypi install or fix the URL update workflow.

### Versions

2.3 nightly

cc @seemethere @malfet @osalpekar

**Comment by malfet** [comment]
Yeah, need to add it to CI, but also fix the actual index, as it is quite broken at the moment
