### ISSUE TITLE
Accuracy mismatch with torch.compile(backend="eager") for float16

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#121238]
### 🐛 Describe the bug

For float16 (the repro passes if dtype is torch.float32), the two implementations differ tangibly when passed through dynamo when they are the same in eager. Example results shown below.

One thing to note is that if we switch the following to not pass in -1 to addcdiv, the difference is okay again.
```
    denom = exp_inf * bias_correction
    param.addcdiv_(exp_avg, denom, value=-1)
```
to
```
    denom = exp_inf * -bias_correction
    param.addcdiv_(exp_avg, denom)
```

### Error logs

```
(pytorch-3.10) [janeyx@devgpu023.odn1 ~/local/pytorch (1e63ab5f)]$ python playground2.py 
The following are the same param=tensor([[ -0.8535,   0.1125,  -0.9385],
        [ -3.8652, -59.9062,  -6.5234]], device='cuda:0', dtype=torch.float16) and pc=tensor([[ -0.8535,   0.1125,  -0.9385],
        [ -3.8652, -59.9062,  -6.5234]], device='cuda:0', dtype=torch.float16)
/home/janeyx/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/playground2.py", line 54, in <module>
    assert torch.allclose(param, pc), f"results are not the same! {param=} {pc=}"
AssertionError: results are not the same! param=tensor([[ -0.7939, -22.8125,  -4.2969],
        [ -1.7324,  -7.2891,  -4.1484]], device='cuda:0', dtype=torch.float16) pc=tensor([[ -0.7944, -22.8125,  -4.2969],
        [ -1.7314,  -7.2852,  -4.1445]], device='cuda:0', dtype=torch.float16)
```

### Minified repro

```
import torch
dtype = torch.float16

beta1 = 0.9
step_t = torch.tensor(2, dtype=dtype, device="cuda")
g_step_t = [torch.tensor(2, dtype=dtype, device="cuda")]


param = torch.rand(2, 3, dtype=dtype, device="cuda") 
pc = param.clone()
exp_inf = torch.rand(2, 3, dtype=dtype, device="cuda")
exp_inf_c = exp_inf.clone()
exp_avg = torch.rand(2, 3, dtype=dtype, device="cuda")
exp_avg_c = exp_avg.clone()

def reset():
    global beta1, step_t, g_step_t, param, pc, exp_inf, exp_inf_c, exp_avg, exp_avg_c
    beta1 = 0.9
    step_t = torch.tensor(2, dtype=dtype, device="cuda")
    g_step_t = [torch.tensor(2, dtype=dtype, device="cuda")]

    param = torch.rand(2, 3, dtype=dtype, device="cuda") 
    pc = param.clone()
    exp_inf = torch.rand(2, 3, dtype=dtype, device="cuda")
    exp_inf_c = exp_inf.clone()
    exp_avg = torch.rand(2, 3, dtype=dtype, device="cuda")
    exp_avg_c = exp_avg.clone()


def forloop_capturable():
    bias_correction = 1 - beta1 ** step_t
    denom = exp_inf * bias_correction
    param.addcdiv_(exp_avg, denom, value=-1)

def foreach_capturable():
    bias_corrections = torch._foreach_pow(beta1, g_step_t)
    # foreach_sub doesn't allow a scalar as the first arg
    torch._foreach_sub_(bias_corrections, 1)

    denom = torch._foreach_mul([exp_inf_c], bias_corrections)
    torch._foreach_addcdiv_([pc], [exp_avg_c], denom)

# these match in eager
forloop_capturable()
foreach_capturable()
assert torch.allclose(param, pc)
print(f"The following are the same {param=} and {pc=}")

reset()

# but not in compile
torch.compile(forloop_capturable, backend="eager")()
torch.compile(foreach_capturable, backend="eager")()
assert torch.allclose(param, pc), f"results are not the same! {param=} {pc=}"
```

### Versions

main

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by williamwen42** [comment]
Looks like dynamo is decomposing the `param.addcdiv_`, which gives a different result due to precision issues.

Minimal repro:
```python
import torch
dtype = torch.float16

def intermediate(step_t, exp_inf):
    tmp = 0.9 ** step_t
    tmp -= 1 
    return exp_inf * tmp

def forward1(step_t, exp_inf, param, exp_avg):
    denom = -intermediate(step_t, exp_inf)
    div = torch.div(exp_avg, denom)
    mul_1 = torch.mul(div, -1)
    param.add_(mul_1)

def forward2(step_t, exp_inf, param, exp_avg):
    denom = intermediate(step_t, exp_inf)
    param.addcdiv_(exp_avg, denom)
    
beta1 = 0.9
step_t = torch.tensor(2, dtype=dtype, device="cuda")

param1 = torch.rand(2, 3, dtype=dtype, device="cuda") 
param2 = param1.clone()
exp_inf = torch.rand(2, 3, dtype=dtype, device="cuda")
exp_avg = torch.rand(2, 3, dtype=dtype, device="cuda")

forward1(step_t, exp_inf, param1, exp_avg)
forward2(step_t, exp_inf, param2, exp_avg)

assert torch.allclose(param1, param2), f"results are not the same! {param1=} {param2=}"
```

**Comment by mlazos** [comment]
> Looks like dynamo is decomposing the `param.addcdiv_`, which gives a different result due to precision issues.
> 
> 
> 
> Minimal repro:
> 
> ```python
> 
> import torch
> 
> dtype = torch.float16
> 
> 
> 
> def intermediate(step_t, exp_inf):
> 
>     tmp = 0.9 ** step_t
> 
>     tmp -= 1 
> 
>     return exp_inf * tmp
> 
> 
> 
> def forward1(step_t, exp_inf, param, exp_avg):
> 
>     denom = -intermediate(step_t, exp_inf)
> 
>     div = torch.div(exp_avg, denom)
> 
>     mul_1 = torch.mul(div, -1)
> 
>     param.add_(mul_1)
> 
> 
> 
> def forward2(step_t, exp_inf, param, exp_avg):
> 
>     denom = intermediate(step_t, exp_inf)
> 
>     param.addcdiv_(exp_avg, denom)
> 
>     
> 
> step_t = torch.tensor(2, dtype=dtype, device="cuda")
> 
> param1 = torch.rand(2, 3, dtype=dtype, device="cuda") 
> 
> param2 = param1.clone()
> 
> exp_inf = torch.rand(2, 3, dtype=dtype, device="cuda")
> 
> exp_avg = torch.rand(2, 3, dtype=dtype, device="cuda")
> 
> 
> 
> forward1(step_t, exp_inf, param1, exp_avg)
> 
> forward2(step_t, exp_inf, param2, exp_avg)
> 
> 
> 
> assert torch.allclose(param1, param2), f"results are not the same! {param1=} {param2=}"
> 
> ```

Ah yes I remember this, this is with the eager backend so this makes more sense. Perhaps we don't decomp in dynamo if we're using the eager backend? Not sure if we want to make graphs differ based on the backend esp when it's used for debugging. We could just say this is expected now that we know the cause.

**Comment by janeyx99** [comment]
Should we track the fact that dynamo decomps for eager backend in a separate issue? I'm not sure it's expected that dynamo on the eager backend doesn't produce the same thing as just running eager.

**Comment by williamwen42** [comment]
We manually decompose here: https://github.com/pytorch/pytorch/blob/b8eef500a63e18c8594f70b9794daa4333538629/torch/_dynamo/variables/tensor.py#L872

**Comment by williamwen42** [comment]
Introduced here https://github.com/pytorch/pytorch/pull/90330 @mlazos

**Comment by mlazos** [comment]
We can't get rid of these decomps, or else we will reintroduce graph breaks in the compiled optimizers, which is catastrophic for compiled optimizer perf.

If eager backend accuracy is a concern we could bypass this decomp when using the eager backend, I don't think this is a good idea though because one of the main uses of the eager backend is to perform analysis of the graph dynamo extracts. I don't think this is unreasonable because we have a similar expectation of aot_eager (this runs our actual decomp and pattern matcher passes) which will similarly have issues like this with bfloat16 due to decomps. All in all the tradeoff I'm suggesting is graph consistency across backends over eager backend accuracy.

**Comment by janeyx99** [comment]
Ah I see, @mlazos do you remember why tracing the default addcdiv graph breaks? I agree we shouldn't deviate the behavior here when compiling for different backends, so I'm moreso asking to see if we could remove this specialization eventually.
