### ISSUE TITLE
Make 'torch._C._OutOfMemoryError' more genenral for other devices except CUDA.

### ISSUE THREAD

**Issue by PHLens** [pytorch/pytorch#121200]
### 📚 The doc issue

I've found the docs for 'torch._C._OutOfMemoryError' in 'torch/csrc/Exceptions.cpp' like the following:
```cpp
...
ASSERT_TRUE(
      THPException_OutOfMemoryError = PyErr_NewExceptionWithDoc(
          "torch.cuda.OutOfMemoryError",
          "Exception raised when CUDA is out of memory",
          PyExc_RuntimeError,
          nullptr));
  ASSERT_TRUE(
      PyModule_AddObject(
          module, "_OutOfMemoryError", THPException_OutOfMemoryError) == 0);
...
```
There are hard code for CUDA. Since more devices were added to PyTorch backend(using privateuse1) and they may need this Error too except for CUDA. I was wondering if there is any need to change this Error.(For example change the error name to "torch.OutOfMemoryError" and doc to "Exception raised when device is out of memory").
Please let me know if I should make a PR.

### Suggest a potential alternative/fix

```cpp
...
ASSERT_TRUE(
      THPException_OutOfMemoryError = PyErr_NewExceptionWithDoc(
          "torch.OutOfMemoryError",
          "Exception raised when device is out of memory",
          PyExc_RuntimeError,
          nullptr));
  ASSERT_TRUE(
      PyModule_AddObject(
          module, "_OutOfMemoryError", THPException_OutOfMemoryError) == 0);
...
```

cc @albanD

**Comment by albanD** [comment]
Thanks for the proposal.

I am not sure if we want to go all the way to make CPU errors also go through this.
I do think that we can make this an accelerator-specific concept though following the accelerator definition from https://github.com/pytorch/pytorch/blob/a427d904116b13947b538c1fac91c3f85ce52609/aten/src/ATen/DeviceAccelerator.h#L9
And then privateuse1 (and other similar backends) can and should raise this error on memory errors.

**Comment by PHLens** [comment]
@albanD yeah, that will be more consistent for all privateuse1 backend, I'll try to make a PR for this.
