### ISSUE TITLE
Please enable the autocomplete feature

### ISSUE THREAD

**Issue by ZongyueZhao** [pytorch/pytorch#12128]
## 🚀 Feature

Make it possible for the text editors to autocomplete methods, like torch.randn().

## Motivation

Intellisense is a gift to developers. We NEED it, Please.

## Pitch

I've looked up the .py files and .h files, and it seems the problem is due to that all the methods cannot be indexed are only declared in head files and implemented in the .pyd and dlls that editors can not deal with.

Can you make some changes, like re-declaring these methods in the .py files, to fix this problem?

Please correct me if I'm wrong.

**Comment by zou3519** [comment]
Are you referring to https://github.com/pytorch/pytorch/issues/7318?

**Comment by ZongyueZhao** [comment]
My bad, I’ll resubmit the request with the right format.

在 2018年9月27日，上午10:08，Richard Zou <notifications@github.com<mailto:notifications@github.com>> 写道：


Are you referring to #7318<https://github.com/pytorch/pytorch/issues/7318>?

**Comment by ZongyueZhao** [comment]
But if this isn’t about the request format, then the problem is similar to #7318. However, instead of IDEs like PyCharm, I was referring to editors like VS code or sublime. Their plugins won’t work.

Thank you.

Sincerely,
Zhao

在 2018年9月27日，上午10:08，Richard Zou <notifications@github.com<mailto:notifications@github.com>> 写道：


Are you referring to #7318<https://github.com/pytorch/pytorch/issues/7318>?

**Comment by nlgranger** [comment]
From what I read, the ongoing work to solve #7318 is going to be fairly standard (.pyi header files) and not tied specifically to pycharm. It should work for other editors too.

**Comment by andreipet** [comment]
In version 1.2.0 (for CUDA 10.0) everything is fine. Autocomplete + no more missing references.

**Comment by jerryzh168** [comment]
Looks like it's fixed, I'm going to close the issue, if it doesn't work feel free to reopen the issue: @ZongyueZhao
