### ISSUE TITLE
"g++" and "gcc" could be clang on MacOS

### ISSUE THREAD

**Issue by leventov** [pytorch/pytorch#121292]
### 🐛 Describe the bug

In my debugging of `torch.compile` not working on an old MacOS X (12.7 Monterey), I've stumbled upon the place in PyTorch which doesn't look right:

https://github.com/pytorch/pytorch/blob/099ff51d459462cccf83361f33b9a59ecf93842e/torch/_inductor/codecache.py#L919-L920

But `g++` and `gcc` mean downright clang in my Mac:
```
$ gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Apple's clang doesn't work for me anyway for reasons that are beyond me, I've had more progress with conda's clang (though still unresolved), so the code above doesn't affect me directly, but it looks like a sharp edge that might get someone into trouble with some MacOS setup.

### Versions

Collecting environment information...
PyTorch version: 2.1.2.post102
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.7 (x86_64)
GCC version: Could not collect
Clang version: 16.0.6                   <-- This is conda's clang, not Apple's.
CMake version: version 3.28.3
Libc version: N/A

Python version: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:51:20) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-12.7-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

Versions of relevant libraries:
[pip3] flake8==7.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] torch==2.1.2.post102
[conda] libblas                   3.9.0              20_osx64_mkl    conda-forge
[conda] libcblas                  3.9.0              20_osx64_mkl    conda-forge
[conda] liblapack                 3.9.0              20_osx64_mkl    conda-forge
[conda] libtorch                  2.1.2           cpu_mkl_h1b58e0f_102    conda-forge
[conda] mkl                       2023.2.0         h54c2260_50500    conda-forge
[conda] mkl-service               2.4.0           py311h5fe9819_1    conda-forge
[conda] numpy                     1.25.2          py311hc44ba51_0    conda-forge
[conda] pytorch                   2.1.2           cpu_mkl_py311h961e2af_102    conda-forge

cc @malfet @albanD @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by malfet** [comment]
Hmm, but does it work for you on a newer MacOS? I.e. what kind of error are you seeing? Also, is this an x86 Mac? Or arm one?
Can you please share a minimal reproducer and error that you are seeing?

**Comment by leventov** [comment]
I didn't try to revive Apple's "native" clang, so no updates there.

The recipe that eventually worked for me:

1. Unset all variables `CFLAGS`, `CPPFLAGS`, `CXXFLAGS`, `CPATH`, `CPPPATH`, `CXXPATH` in the local environment. some of these variables were pointing to the distributions in either `/Library/Developer/CommandLineTools/` or `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/` and this was hurting things.
2. Under conda's environment, set `CXX=x86_64-apple-darwin13.4.0-clang++` (which resolves to `/usr/local/anaconda3/envs/<my env>/bin/x86_64-apple-darwin13.4.0-clang++`
3. Set `OMP_PREFIX` to one of the many locations under the conda environment (`llvm-openmp` package installed).
4. Manually change this code:

https://github.com/pytorch/pytorch/blob/099ff51d459462cccf83361f33b9a59ecf93842e/torch/_inductor/codecache.py#L927-L931

to return True. I don't know why `get_include_and_linking_paths()` states that only Apple's Clang needs OpenMP: apparently, conda's clang needs it as well. `x86_64-apple-darwin13.4.0-clang++ --version` returns:
```
clang version 16.0.6
Target: x86_64-apple-darwin13.4.0
Thread model: posix
InstalledDir: /usr/local/anaconda3/envs/<my-env>/bin
```

**Comment by leslie-fang-intel** [comment]
PR landed, @leventov feel free to reopen if any further question.
