### ISSUE TITLE
[inductor][cpu]fp32 models performance regression in 2024-03-04 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#121376]
### 🐛 Describe the bug

fp32 models regression in 2024-03-04 nightly release.

<p>fp32 static shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>yolov3</td>
      <td>multiple</td>
      <td>8</td>
      <td>0.991369</td>
      <td>0.255836803</td>
      <td>0.253628675553307</td>
      <td>21.008619</td>
      <td>8</td>
      <td>1.591373</td>
      <td>0.156282283</td>
      <td>0.24870340554455897</td>
      <td>26.609133</td>
      <td>0.62</td>
      <td>0.98</td>
      <td>0.61</td>
      <td>1.27</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>convit_base</td>
      <td>multiple</td>
      <td>64</td>
      <td>1.269294</td>
      <td>0.8729793100000001</td>
      <td>1.10806740030714</td>
      <td>43.814319</td>
      <td>64</td>
      <td>1.540159</td>
      <td>0.7080052130000001</td>
      <td>1.0904406008488672</td>
      <td>38.130222</td>
      <td>0.82</td>
      <td>0.98</td>
      <td>0.81</td>
      <td>0.87</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>yolov3</td>
      <td>single</td>
      <td>1</td>
      <td>0.99786</td>
      <td>0.590719669</td>
      <td>0.58945552890834</td>
      <td>19.799038</td>
      <td>1</td>
      <td>1.387904</td>
      <td>0.428259948</td>
      <td>0.594383694868992</td>
      <td>24.260618</td>
      <td>0.72</td>
      <td>1.01</td>
      <td>0.72</td>
      <td>1.23</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>convit_base</td>
      <td>single</td>
      <td>1</td>
      <td>1.208036</td>
      <td>0.2238699</td>
      <td>0.2704428985164</td>
      <td>35.575396</td>
      <td>1</td>
      <td>1.372201</td>
      <td>0.196654595</td>
      <td>0.26984963191359496</td>
      <td>30.385211</td>
      <td>0.88</td>
      <td>1.0</td>
      <td>0.88</td>
      <td>0.85</td>
    </tr>
  </tbody>

</table>
<p>fp32 static shape cpp wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>convit_base</td>
      <td>multiple</td>
      <td>64.0</td>
      <td>1.284969</td>
      <td>0.844753783</td>
      <td>1.085482423787727</td>
      <td>33.745031</td>
      <td>64.0</td>
      <td>1.561684</td>
      <td>0.7009253529999999</td>
      <td>1.0946239089744518</td>
      <td>29.064628</td>
      <td>0.82</td>
      <td>1.01</td>
      <td>0.83</td>
      <td>0.86</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>convit_base</td>
      <td>single</td>
      <td>1.0</td>
      <td>1.213455</td>
      <td>0.221748512</td>
      <td>0.26908184062896</td>
      <td>30.388094</td>
      <td>1.0</td>
      <td>1.383058</td>
      <td>0.194475219</td>
      <td>0.26897050743970197</td>
      <td>25.875338</td>
      <td>0.88</td>
      <td>1.0</td>
      <td>0.88</td>
      <td>0.85</td>
    </tr>
  </tbody>

</table>
<p>fp32 dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>yolov3</td>
      <td>multiple</td>
      <td>8</td>
      <td>0.983977</td>
      <td>0.25779631399999997</td>
      <td>0.253665643660778</td>
      <td>22.344479</td>
      <td>8.0</td>
      <td>1.503107</td>
      <td>0.16544836799999998</td>
      <td>0.24868660007937599</td>
      <td>30.578669</td>
      <td>0.65</td>
      <td>0.98</td>
      <td>0.64</td>
      <td>1.37</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>yolov3</td>
      <td>single</td>
      <td>1</td>
      <td>0.997312</td>
      <td>0.592453853</td>
      <td>0.5908613370431359</td>
      <td>20.022786</td>
      <td>1.0</td>
      <td>1.37728</td>
      <td>0.428594964</td>
      <td>0.5902952720179201</td>
      <td>24.479398</td>
      <td>0.72</td>
      <td>1.0</td>
      <td>0.72</td>
      <td>1.22</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>convit_base</td>
      <td>single</td>
      <td>1</td>
      <td>1.208458</td>
      <td>0.223794506</td>
      <td>0.270446261131748</td>
      <td>35.944872</td>
      <td>1.0</td>
      <td>1.374786</td>
      <td>0.196470478</td>
      <td>0.270104862567708</td>
      <td>30.699722</td>
      <td>0.88</td>
      <td>1.0</td>
      <td>0.88</td>
      <td>0.85</td>
    </tr>
  </tbody>

</table>
<p>fp32 dynamic shape cpp wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>convit_base</td>
      <td>single</td>
      <td>1.0</td>
      <td>1.222613</td>
      <td>0.221231601</td>
      <td>0.270480631393413</td>
      <td>30.374674</td>
      <td>1.0</td>
      <td>1.379473</td>
      <td>0.194968928</td>
      <td>0.268954372014944</td>
      <td>25.781443</td>
      <td>0.89</td>
      <td>0.99</td>
      <td>0.88</td>
      <td>0.85</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>ff42d907</td>
      <td>main</td>
      <td>ff42d907</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>581fe26792849a80f04feaa7f8bdec69b7f41dd8</td>
      <td>main</td>
      <td>5c7b761f8e748fe45c8e2e29563df637ae651917</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.18.0a0+2c127da</td>
      <td>main</td>
      <td>0.18.0a0+a52607e</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.2.0a0+87aeb55</td>
      <td>main</td>
      <td>2.2.0a0+5286f9f</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh **thread** inference performance **suite** **model** float32 first static/dynamic cpp/default
[torchbench-yolov3-inference-float32-static-default-multiple-performance-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/14517683/torchbench-yolov3-inference-float32-static-default-multiple-performance-drop_guilty_commit.log)
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/8c2e569928a200893fe971e615b82a2f9ce32630
Seems the guilty commit pointed to PR is reverted, will double check in next test result.
cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @WeizhuoZhang-intel @chuanqi129

**Comment by leslie-fang-intel** [comment]
@zxd1997066 will help to check the guilty commit manually.

**Comment by zxd1997066** [comment]
checked the guilty commit

8c2e569
yolov3
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance torchbench yolov3 float32 first dynamic default
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,yolov3,8,0.983419,247.383547,11.642927,0.983975,469.234483,476.876390,200,27,2,1,0,0

convit_base
/workspace/pytorch# bash inductor_single_run.sh single inference performance timm_models convit_base float32 first dynamic default
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,convit_base,1,1.203764,225.105157,36.322175,0.777130,156.044493,200.795750,700,1,0,0,0,0

77ef9d4
yolov3
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance torchbench yolov3 float32 first dynamic default
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,yolov3,8,1.495863,163.262273,31.766438,0.962326,467.962266,486.282445,361,1,0,0,0,0

convit_base
/workspace/pytorch# bash inductor_single_run.sh single inference performance timm_models convit_base float32 first dynamic default
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,convit_base,1,1.380130,196.254372,14.203113,0.787163,139.166106,176.794419,510,1,0,0,0,0

**Comment by leslie-fang-intel** [comment]
Hi @fegin, based on the testing result from @zxd1997066, looks like https://github.com/pytorch/pytorch/commit/8c2e569928a200893fe971e615b82a2f9ce32630 has caused the regression of `yolov3` and `convit_base`. Could you help to take a look?

**Comment by zxd1997066** [comment]
based on the latest results, this issue is fixed.
