### ISSUE TITLE
Interpolate nearest

### ISSUE THREAD

**Issue by xiaozhuai** [pytorch/pytorch#121390]
### 🐛 Describe the bug

```python
mode = "nearest"
input = torch.randn(1, 1, 4, 2)
output = torch.nn.functional.interpolate(input, scale_factor=(2.05, 3.15), mode=mode)
print(input)
print(output)
```

It prints
```
tensor([[[[-0.1861,  0.7837],
          [ 1.9597,  0.5934],
          [-0.2281,  0.3509],
          [ 0.0078,  0.4952]]]])
tensor([[[[-0.1861, -0.1861, -0.1861, -0.1861,  0.7837,  0.7837],
          [-0.1861, -0.1861, -0.1861, -0.1861,  0.7837,  0.7837],
          [ 1.9597,  1.9597,  1.9597,  1.9597,  0.5934,  0.5934],
          [ 1.9597,  1.9597,  1.9597,  1.9597,  0.5934,  0.5934],
          [-0.2281, -0.2281, -0.2281, -0.2281,  0.3509,  0.3509],
          [-0.2281, -0.2281, -0.2281, -0.2281,  0.3509,  0.3509],
          [ 0.0078,  0.0078,  0.0078,  0.0078,  0.4952,  0.4952],
          [ 0.0078,  0.0078,  0.0078,  0.0078,  0.4952,  0.4952]]]])
```

1. The output should be the following if 
```cpp
float f_index = scaled_index / scale;
int i_index = min((int)floorf(f_index), out_size - 1);
```

```
tensor([[[[-0.1861 -0.1861 -0.1861 -0.1861  0.7837  0.7837],
          [-0.1861 -0.1861 -0.1861 -0.1861  0.7837  0.7837],
          [-0.1861 -0.1861 -0.1861 -0.1861  0.7837  0.7837],
          [ 1.9597  1.9597  1.9597  1.9597  0.5934  0.5934],
          [ 1.9597  1.9597  1.9597  1.9597  0.5934  0.5934],
          [-0.2281 -0.2281 -0.2281 -0.2281  0.3509  0.3509],
          [-0.2281 -0.2281 -0.2281 -0.2281  0.3509  0.3509],
          [ 0.0078  0.0078  0.0078  0.0078  0.4952  0.4952]]]])
```

2. The output should be the following if
```cpp
float f_index = (scaled_index + 0.5f) / scale - 0.5f;
int i_index = min((int)roundf(f_index), out_size - 1);
```

```
tensor([[[[-0.1861 -0.1861 -0.1861  0.7837  0.7837  0.7837],
          [-0.1861 -0.1861 -0.1861  0.7837  0.7837  0.7837],
          [ 1.9597  1.9597  1.9597  0.5934  0.5934  0.5934],
          [ 1.9597  1.9597  1.9597  0.5934  0.5934  0.5934],
          [-0.2281 -0.2281 -0.2281  0.3509  0.3509  0.3509],
          [-0.2281 -0.2281 -0.2281  0.3509  0.3509  0.3509],
          [ 0.0078  0.0078  0.0078  0.4952  0.4952  0.4952],
          [ 0.0078  0.0078  0.0078  0.4952  0.4952  0.4952]]]])
```

But the output of pytorch is different from both of the above.
I have no idea how pytorch's output is computed. 
Any one please help. Thanks very much!

Update:
---

https://github.com/pytorch/pytorch/blob/db36d21f5c43e2695fe9f6e40bf7fbec854d3ca4/aten/src/ATen/native/UpSample.h#L339-L352

It seems due to these code. 
The actual scale of rows is `2.05`, output rows is `8`, input rows is `4`.
So the scale of rows is recomputed to `2`.
Is this expected behavior？

### Versions

PyTorch version: 2.2.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.6 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.28.3
Libc version: N/A

Python version: 3.12.2 (main, Feb 20 2024, 04:30:04) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-12.6.6-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.1
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by samhu1** [comment]
take

**Comment by xiaozhuai** [comment]
Nobody here. Closed.
