### ISSUE TITLE
`torch.set_default_dtype(d)` outdated?

### ISSUE THREAD

**Issue by albertz** [pytorch/pytorch#121300]
### 📚 The doc issue

[`torch.set_default_dtype(d)`](https://pytorch.org/docs/stable/generated/torch.set_default_dtype.html#torch.set_default_dtype)

It says:

> Supports torch.float32 and torch.float64 as inputs. Other dtypes may be accepted without complaint but are not supported and are unlikely to work as expected.

I wonder, is this true, or outdated? I just tested, and it seems to behave exactly as expected:
```
In [1]: import torch

In [2]: torch.set_default_dtype(torch.float16)

In [3]: torch.zeros(())
Out[3]: tensor(0.)

In [4]: _3.dtype
Out[4]: torch.float16

In [5]: torch.set_default_dtype(torch.bfloat16)

In [6]: torch.zeros(())
Out[6]: tensor(0.)

In [7]: _6
Out[7]: tensor(0.)

In [8]: _6.dtype
Out[8]: torch.bfloat16
```

Or, if this is still true that some behavior might be unexpected, can this be clarified, what exactly will not work as expected?

### Suggest a potential alternative/fix

Update the doc to reflect the current state.

Another orthogonal thing: Maybe it could mention `torch.get_default_dtype()` as well.

**Comment by ezyang** [comment]
We're probably referring to integral types. You can send us a doc PR.
