### ISSUE TITLE
[inductor][cpu]AMP models regression and crash in 2024-03-04 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#121377]
### 🐛 Describe the bug

AMP models regression and crash in 2024-03-04 nightly release.

<p>AMP static shape default wrapper regression</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>llama</td>
      <td>multiple</td>
      <td>32</td>
      <td>1.372195</td>
      <td>0.014102689</td>
      <td>0.019351639332355</td>
      <td>19.282797</td>
      <td>32.0</td>
      <td>2.142721</td>
      <td>0.009058953000000002</td>
      <td>0.019410808831113003</td>
      <td>19.388413</td>
      <td>0.64</td>
      <td>1.0</td>
      <td>0.64</td>
      <td>1.01</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>yolov3</td>
      <td>multiple</td>
      <td>8</td>
      <td>0.975399</td>
      <td>0.09829916</td>
      <td>0.09588090236484</td>
      <td>17.287654</td>
      <td>8.0</td>
      <td>3.491892</td>
      <td>0.02860036</td>
      <td>0.09986936828111999</td>
      <td>21.98618</td>
      <td>0.28</td>
      <td>1.04</td>
      <td>0.29</td>
      <td>1.27</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>convit_base</td>
      <td>multiple</td>
      <td>64</td>
      <td>1.364183</td>
      <td>0.251519204</td>
      <td>0.34311822227033195</td>
      <td>36.793275</td>
      <td>64.0</td>
      <td>1.990777</td>
      <td>0.172512283</td>
      <td>0.343433485213891</td>
      <td>31.588458</td>
      <td>0.69</td>
      <td>1.0</td>
      <td>0.69</td>
      <td>0.86</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>llama</td>
      <td>single</td>
      <td>1</td>
      <td>0.68803</td>
      <td>0.061452501</td>
      <td>0.042281164263030004</td>
      <td>20.256173</td>
      <td>1.0</td>
      <td>3.788769</td>
      <td>0.01094602</td>
      <td>0.04147194124938</td>
      <td>19.422561</td>
      <td>0.18</td>
      <td>0.98</td>
      <td>0.18</td>
      <td>0.96</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>yolov3</td>
      <td>single</td>
      <td>1</td>
      <td>0.99071</td>
      <td>0.28245702899999997</td>
      <td>0.27983300320058996</td>
      <td>15.963345</td>
      <td>1.0</td>
      <td>3.867883</td>
      <td>0.07098655599999999</td>
      <td>0.274567693180948</td>
      <td>19.435037</td>
      <td>0.26</td>
      <td>0.98</td>
      <td>0.25</td>
      <td>1.22</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>convit_base</td>
      <td>single</td>
      <td>1</td>
      <td>1.220285</td>
      <td>0.116050149</td>
      <td>0.141614256072465</td>
      <td>29.88047</td>
      <td>1.0</td>
      <td>1.501315</td>
      <td>0.098143494</td>
      <td>0.14734429969461</td>
      <td>24.300461</td>
      <td>0.81</td>
      <td>1.04</td>
      <td>0.85</td>
      <td>0.81</td>
    </tr>
  </tbody>

</table>
<p>AMP static shape default wrapper failure</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>huggingface</td>
      <td>BlenderbotForCausalLM</td>
      <td>single</td>
      <td>√</td>
      <td>X</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>stable_diffusion_text_encoder</td>
      <td>single</td>
      <td>X</td>
      <td>√</td>
    </tr>

</table>

<p>AMP dynamic shape default wrapper regression</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>yolov3</td>
      <td>multiple</td>
      <td>8</td>
      <td>0.974551</td>
      <td>0.09871308399999999</td>
      <td>0.09620093472528399</td>
      <td>18.658825</td>
      <td>8.0</td>
      <td>2.825746</td>
      <td>0.034874982000000006</td>
      <td>0.09854784088657202</td>
      <td>26.072793</td>
      <td>0.34</td>
      <td>1.02</td>
      <td>0.35</td>
      <td>1.4</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>llama</td>
      <td>single</td>
      <td>1</td>
      <td>0.732906</td>
      <td>0.060439407</td>
      <td>0.044296404026741995</td>
      <td>20.219663</td>
      <td>1.0</td>
      <td>3.801087</td>
      <td>0.01084628</td>
      <td>0.04122765390636</td>
      <td>19.354458</td>
      <td>0.19</td>
      <td>0.93</td>
      <td>0.18</td>
      <td>0.96</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>yolov3</td>
      <td>single</td>
      <td>1</td>
      <td>0.989944</td>
      <td>0.281489406</td>
      <td>0.278658748533264</td>
      <td>15.981785</td>
      <td>1.0</td>
      <td>3.866154</td>
      <td>0.07068060400000001</td>
      <td>0.273262099877016</td>
      <td>19.418051</td>
      <td>0.26</td>
      <td>0.98</td>
      <td>0.25</td>
      <td>1.22</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>convit_base</td>
      <td>single</td>
      <td>1</td>
      <td>1.262171</td>
      <td>0.116195749</td>
      <td>0.14665890471107898</td>
      <td>29.754619</td>
      <td>1.0</td>
      <td>1.492518</td>
      <td>0.09633620799999999</td>
      <td>0.143783524491744</td>
      <td>24.215046</td>
      <td>0.85</td>
      <td>0.98</td>
      <td>0.83</td>
      <td>0.81</td>
    </tr>
  </tbody>

</table>

<p>AMP dynamic shape default wrapper failure</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>huggingface</td>
      <td>BlenderbotForCausalLM</td>
      <td>single</td>
      <td>√</td>
      <td>X</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>stable_diffusion_text_encoder</td>
      <td>single</td>
      <td>X</td>
      <td>√</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>ff42d907</td>
      <td>main</td>
      <td>ff42d907</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>581fe26792849a80f04feaa7f8bdec69b7f41dd8</td>
      <td>main</td>
      <td>5c7b761f8e748fe45c8e2e29563df637ae651917</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.18.0a0+2c127da</td>
      <td>main</td>
      <td>0.18.0a0+a52607e</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.2.0a0+87aeb55</td>
      <td>main</td>
      <td>2.2.0a0+5286f9f</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh **thread** inference performance/accuracy **suite** **model** amp first static/dynamic
regression bisect log:
[torchbench-yolov3-inference-amp-dynamic-default-multiple-performance-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/14517983/torchbench-yolov3-inference-amp-dynamic-default-multiple-performance-drop_guilty_commit.log)
failure bisect log:
[huggingface-BlenderbotForCausalLM-inference-amp-dynamic-default-single-performance-crash_guilty_commit.log](https://github.com/pytorch/pytorch/files/14517991/huggingface-BlenderbotForCausalLM-inference-amp-dynamic-default-single-performance-crash_guilty_commit.log)
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/1104e0798c8206e0226f2d68f6bb065645e6276f
cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @WeizhuoZhang-intel @chuanqi129

**Comment by leslie-fang-intel** [comment]
@zxd1997066 will help to check the guilty commit manually.

**Comment by zxd1997066** [comment]
verfied the guilty commit:
1104e07
llama
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance torchbench llama amp first static
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,llama,32,**0.999226**,19.031106,38.433693,0.927021,320.108954,345.309184,2655,5,1,1,0,0

BlenderbotForCausalLM
/workspace/pytorch# bash inductor_single_run.sh single inference performance huggingface BlenderbotForCausalLM amp first static
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2629, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 437, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/huggingface.py", line 557, in forward_pass
    with self.autocast(**self.autocast_arg):
  File "benchmarks/dynamo/huggingface.py", line 557, in torch_dynamo_resume_in_forward_pass_at_557
    with self.autocast(**self.autocast_arg):
TypeError: __call__() takes 2 positional arguments but 5 were given

ca67938
llama
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance torchbench llama amp first static
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,llama,32,**2.143268**,9.160565,7.426324,0.972145,320.196198,329.370829,531,1,0,0,0,0

BlenderbotForCausalLM
/workspace/pytorch# bash inductor_single_run.sh single inference performance huggingface BlenderbotForCausalLM amp first static
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,BlenderbotForCausalLM,1,2.482619,745.482914,30.554432,0.933324,3138.726707,3362.954854,936,1,0,0,0,0

**Comment by leslie-fang-intel** [comment]
Hi @yanboliang, based on the testing result from @zxd1997066, looks like https://github.com/pytorch/pytorch/commit/1104e0798c8206e0226f2d68f6bb065645e6276f has caused the regressions reported in this issue. Could you help to take a look?

**Comment by yanboliang** [comment]
* Is ```BlenderbotForCausalLM``` the regressed model? I run it on my end and didn't see the regression yet, but probably I'm using a different config. Can you share with me the exact command of running this model? 
* #120812 fixed a latent bug, it may cause perf difference, but I don't know if it's reasonable before I can reproduce it.

**Comment by chuanqi129** [comment]
> * Is `BlenderbotForCausalLM` the regressed model? I run it on my end and didn't see the regression yet, but probably I'm using a different config. Can you share with me the exact command of running this model?

According to this issue description, there are 2 kinds regression, one is performance regression, like `llama`, another is function crash, like `BlenderbotForCausalLM`. 

We used this [Dockerfile ](https://github.com/chuanqi129/inductor-tools/blob/main/docker/Dockerfile) to build the test env. And can use script [inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh) to reproduce the issue.

For `BlenderbotForCausalLM` functional crash with performance mode cmd under pytorch source code root dir:
`bash inductor_single_run.sh single inference performance huggingface BlenderbotForCausalLM amp first static`

For `llama` performance regression can use cmd:
`bash inductor_single_run.sh multiple inference performance torchbench llama amp first static`

@yanboliang Please try it and feel free let us know if there is any problems.

**Comment by zxd1997066** [comment]
base on the latest results, this issue is fixed.
