### ISSUE TITLE
Some issues about the new doc theme

### ISSUE THREAD

**Issue by leomao** [pytorch/pytorch#12131]
Hi, I found that there are some problems (in my opinion) of the new theme of the [documentation](https://pytorch.org/docs/master/):
- The font is too thin compared to the original one.
- The background color is too bright compared to the original one.
- It is hard to navigate across a long section (ex: `torch.nn`) without subsections in the left sidebar.
- render inline code strangely. ex:
![screenshot from 2018-09-27 14-57-34](https://user-images.githubusercontent.com/1811303/46128382-d670c400-c265-11e8-9646-1e6fd2bd1b23.png)
- The latex rendering results are strange in the sense that the font is not consistent and some formulas are just not rendered (maybe the latex syntax is not correct or KaTeX doesn't support certain features).
- Some code snippets are not rendered properly. ex: (in `torch.jit`)
![screenshot from 2018-09-27 15-10-45](https://user-images.githubusercontent.com/1811303/46128883-8f83ce00-c267-11e8-8de3-a79d05b36cef.png)

In general, I think the original theme is more readable.  Is there anything I can help or some plans to improve the readability?

BTW, latex formulas in the new tutorial is extremely small.

**Comment by fmassa** [comment]
Closing because it's a duplicate. Please @leomao feel free to comment on that thread.
