### ISSUE TITLE
INTERNAL ASSERT FAILED at torch.where

### ISSUE THREAD

**Issue by nonenone12135** [pytorch/pytorch#121397]
### 🐛 Describe the bug

It seems that the `out ` parameter of `torch.where` lacks relevant checks.

Code: 
```python
import torch

input_data = torch.randn(3, 3)
condition = torch.rand(3, 3) > 0.5
other_data = torch.ones(3, 3)
output = torch.tensor(0)

output = torch.where(condition, input_data, other_data, out=output)
```

Output:
```
RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "../aten/src/ATen/native/cpu/Loops.h":310, please report a bug to PyTorch.
```

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.2.1
[pip3] triton==2.2.0
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.2.1                    pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

cc @albanD

**Comment by malfet** [comment]
> I don't think this kind of mixed dtype is useful. A nice error sounds fine to me.

Well, CUDA does support mixed dtype, so why CPU shouldn't?

**Comment by albanD** [comment]
If you can easily do that sure.
But putting float32 into an int64 is a user error in most cases.
I'm sure there are some few cases where it is useful so I'm not saying we absolutely shouldn't do it. But I'm very happy with an error here until we have a specific ask.

**Comment by malfet** [comment]
Adding error check is easy and sensible thing to do, considering that MPS will return total garbage in that case
```python
import torch

torch.set_default_device("mps")
input_data = torch.randn(3, 3)
condition = torch.rand(3, 3) > 0.5
other_data = torch.ones(3, 3)
output = torch.tensor(0)

print(torch.where(condition, input_data, other_data, out=output))
```
