### ISSUE TITLE
.device property on layers

### ISSUE THREAD

**Issue by mittagessen** [pytorch/pytorch#12135]
## 🚀 Feature

The `.device` property should be available on layers.

## Motivation

While it is straightforward to determine on which device a tensor resides this is more complicated for layers, requiring a construction like `next(next(nn.children()).parameters()).device` in simple cases. This is a bit annoying when having to move a network temporarily onto the CPU for some operation like serialization and then moving it back to the original device.

## Pitch

Just as there is a `.device` property on tensors, there should be one on layers.

## Alternatives

Model sharding across devices might make this complicated to implement for questionable gains in user code cleanness.

**Comment by fmassa** [comment]
This has been already discussed in the past, see e.g., https://github.com/pytorch/pytorch/issues/7460
Quoting @apaszke 
> That’s not possible. Modules can hold parameters of different types on different devices, and so it’s not always possible to unambiguously determine the device.

**Comment by mittagessen** [comment]
Ah sorry for the noise, then.
