### ISSUE TITLE
CondaError: CondaHTTPError When conda install -c soumith magma-cuda80=2.1.0 

### ISSUE THREAD

**Issue by qichaotang** [pytorch/pytorch#1214]
➜  ~ conda install -c soumith magma-cuda80=2.1.0
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/qichaotang/Code_Tools/anaconda2:

The following NEW packages will be INSTALLED:

    magma-cuda80: 2.1.0-5 soumith

Proceed ([y]/n)? y

magma-cuda80-2 100% |################################| Time: 0:01:00 355.50 kB/s

CondaError: CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/soumith/linux-64/magma-cuda80-2.1.0-5.tar.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/soumith/linux-64/magma-cuda80-2.1.0-5.tar.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/soumith/linux-64/magma-cuda80-2.1.0-5.tar.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

So whether the other way can be done by installing magma-cuda80?

**Comment by soumith** [comment]
```
conda install -c soumith magma-cuda80
```

Why are you trying for a specific version?

**Comment by soumith** [comment]
are you behind a firewall? I cant reproduce this.

**Comment by Jianlou** [comment]
@soumith  I also meet the same problem. So I try to install tra.bz2 offline.
`conda install magma-cuda80-2.1.0-5.tar.bz2`
 And the error occurs like,
`CondaError: EOFError('compressed file ended before the logical end-of-stream was detected',)

CondaError: EOFError('compressed file ended before the logical end-of-stream was detected',)

CondaError: EOFError('compressed file ended before the logical end-of-stream was detected',)`

Is there any solutions?

**Comment by soumith** [comment]
what are you doing / trying to do?
The correct command is:

```
conda install magma-cuda80 -c soumith
```

**Comment by Jianlou** [comment]
When use this command `conda install magma-cuda80 -c soumith`
Following error will come up
`Proceed ([y]/n)? y

magma-cuda80-2 100% |################################| Time: 0:01:00 355.50 kB/s

CondaError: CondaHTTPError: HTTP None None for url https://conda.anaconda.org/soumith/linux-64/magma-cuda80-2.1.0-5.tar.bz2
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

`

**Comment by Jianlou** [comment]
@soumith 
When use this command,
`conda install magma-cuda80 -c soumith`

Following error will come up,
'Proceed ([y]/n)? y

magma-cuda80-2 100% |################################| Time: 0:01:00 355.50 kB/s

CondaError: CondaHTTPError: HTTP None None for url https://conda.anaconda.org/soumith/linux-64/magma-cuda80-2.1.0-5.tar.bz2
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.'

**Comment by soumith** [comment]
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.'

It looks like for some reason it is not finishing the download.

You can try to do the following:

```
conda clean
conda install -y conda
conda install -y magma-cuda80 -c soumith
```

Also, go to  https://conda.anaconda.org in your browser and see if it is blocked by your local firewall or proxy.

**Comment by bezorro** [comment]
I meet the same problem.
Observing that every time when I failed, the download percentages are different. Some time 0% and some time 24% etc.  Thus, it must be network unstable.
So I wrote a Shell script `conda install -y magma-cuda80 -c soumith` and let it repeat for thousands of times using a loop and go to bed. The next day I woke up, it is done.
That's how I solve it. Not elegant...but it do works.

**Comment by Spartanzhao** [comment]
I have the same problem, anyone know what's going on? 
conda install blast-2.6.0-boost1.61_0.tar.bz2

CondaError: EOFError('compressed file ended before the logical end-of-stream was detected',)
CondaError: EOFError('compressed file ended before the logical end-of-stream was detected',)
CondaError: EOFError('compressed file ended before the logical end-of-stream was detected',)

**Comment by SunnyWay** [comment]
@Spartanzhao you may run `conda clean --packages` first, then install packages offline.

**Comment by silverlining21** [comment]
I got stuck in the same problem, is there anyone had the problem solved elegantly..

**Comment by MENGHAH** [comment]
I use the command like :

`conda install pytorch-cpu torchvision-cpu -c pytorch`

but produce the same error like:

`CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/linux-64/pytorch-cpu-1.0.1-py3.6_cpu_2.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way `

so,what can i do to solve this problem?
