### ISSUE TITLE
Better error messages when using raw triton kernels with PyTorch features

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#121412]
e.g. using a Triton kernel with FakeTensor results in a CUDA illegal memory access: https://gist.github.com/zou3519/5a8d9872a9855ba9efeac82d516843ba

We should offer a better error message here.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @oulgen @aakhundov

**Comment by oulgen** [comment]
I just merged https://github.com/openai/triton/pull/3314 into Triton. This will allow us to add a pre run hook to provide a better error message for common cases. Will incorporate this into PT2 once triton pin update happens.

**Comment by zou3519** [comment]
There's now an error when accessing data_ptr for something that doesn't have it (like FakeTensor)
