### ISSUE TITLE
ONNX export is unnecessarily slow (O(N^2))

### ISSUE THREAD

**Issue by gustavla** [pytorch/pytorch#121422]
The ONNX export is an op-by-op translation from one IR to another (with some global clean-up passes). Algorithmically this should scale linearly with the number of nodes (O(N)). However, the current implementation scales quadratically (O(N^2)).

Recent use cases demand increasingly large N (e.g., Gen AI, split-head attention), which makes this prohibitively slow (Llama2 7B takes ~1.5h to export).

The fact that the export is slow has been mentioned before (https://github.com/pytorch/pytorch/issues/63734), but remains an issue.

I am open to contribute to the solution of this problem. To kick things off, I am attaching an in-depth analysis of the hot paths. Seeing this list, I hope that you will agree with me that this is an entirely fixable problem with fairly modest refactors.

For all of these problems, I can think of at least one solution. However, it is not always clear to me what the right solution is. I would love to hear from folks who know the code base better. Also, will contributions of this kind be welcome?

* [x] (1) **`pybind11::dict` <-> `std::unordered_map` implicit copies for `env`**
  The converter starts in Python and calls into C++ code. However, the C++ code again calls into Python code for each op. Pybind11 manages this bridge, and it allows [implicit conversion](https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#automatic-conversion) between the python data types (`pybind11:dict`) and STL datatypes (`std::unordered_map`). This implicit conversion incurs a _copy_. A dictionary that maps the torch ops to the new ONNX ops (`env`) is being passed into the op-level functions and this incurs a copy that costs O(N) for each iteration of N.
  * **Possible solution**: This is simple, build a `pybind11::dict` in the first place. I already have this prototyped and it cuts the export time down to 40% of the original.
  * #123063
    
  https://github.com/pytorch/pytorch/blob/3aa512cd72dc521ae09f5b96b8545366ca779593/torch/csrc/jit/passes/onnx.cpp#L171

* [x] (2) **Copy of debug_values**
  In `NodeToONNX` (in the `setOutputs` closure), a map of the graph’s debug names is retrieved via `auto debug_names = new_block->owningGraph()->debugNames()`. The `debugNames()` function returns a const reference, but this use of `auto` incurs a copy into a new variable (and the size is O(N)).
  * **Possible solution**: Simple: `const auto& debug_names = …`
  * #123026
  https://github.com/pytorch/pytorch/blob/3aa512cd72dc521ae09f5b96b8545366ca779593/torch/csrc/jit/passes/onnx.cpp#L296

* [x] (3) **Avoid building `vals_to_params_map`**
  Each node runs through shape inference in a separate graph that only contains the node. As part of this, `CloneNodeToGraph` is called and `params_dict` is passed in. This is a dictionary that maps names to parameter values, and it contains O(N) elements. A copy of this `params_dict` is made called `vals_to_params_map`, incurring a O(N) cost per node.
  * **Possible solution**: Pass `params_dict` directly into the closure and use directly.
  * #123025
  https://github.com/pytorch/pytorch/blob/3aa512cd72dc521ae09f5b96b8545366ca779593/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L298-L299

* [x] (4) **`processSymbolicOutput` and `exist_in_env`**
  As part of `NodeToONNX`, `processSymbolicOutput` is called, which in turns calls `setOutputs`. To handle an edge case, this function checks if one of the outputs of the newly processed node already exists in the graph (e.g., export function returned a no-op), it detects this in `NodeToONNX` and does something special with its name. The way this is looked up is to see if a node is a value of `env` (reverse look-up), which of course incurs an O(N) cost per node. More information about this in the original issue and the PR:
  * https://github.com/pytorch/pytorch/pull/67275 (issue)
  * https://github.com/pytorch/pytorch/pull/66170 (PR)
  * **Possible solution**: This is a steep prize for getting the names and details right of the no-op edge case, so this might be avoidable altogether. Worst case you can build a hash set of the values to avoid a linear-time lookup, but I have a feeling there is an even simpler solution.
  * #124909
  https://github.com/pytorch/pytorch/blob/3aa512cd72dc521ae09f5b96b8545366ca779593/torch/csrc/jit/passes/onnx.cpp#L283

* [x] (5) **`AllGraphInputsStatic`**
  As part of the shape inference in `ONNXShapeTypeInference` of a newly added node, it calls `ProcessConstantValueMap`, which in turn calls `AllGraphInputsStatic` on `n->owningGraph()`. This function iterates through all nodes in the graph to check if all inputs are static. This incurs a O(N) cost for each node.
  * **Possible solution**: The need for this seems to also be driven by an edge case and it’s worth exploring if this information is really needed. If it is needed, perhaps it can be built incrementally by knowing if the graph at N-1 was fully static and then check only the new information for each node.
  * #123028
  https://github.com/pytorch/pytorch/blob/3aa512cd72dc521ae09f5b96b8545366ca779593/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L1549

* [x] (6) **`SetGraphInputTypeReliable`**
  As part of the `ONNXShapeTypeInference` this function is called on the owning graph, which iterates all graph inputs (O(N)) and annotates them as “reliable.”
  * **Possible solution**: Not sure why this is needed, but it should be possible to guarantee that the previous N-1 graph already has this information annotated.
  * #124912
  https://github.com/pytorch/pytorch/blob/3aa512cd72dc521ae09f5b96b8545366ca779593/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L2026

* [x] (7) **Iterate `original_shape_data`**
  As part of the `ONNXShapeTypeInference` this function, `original_shape_data` (which grows with O(N)) is linearly iterated and copied to `inferred_shape_data`.
  * **Possible solution**: It doesn’t seem necessary to fully populate `inferred_shape_data` when checking the shape inference of a single node.
  * ~#123030~
  * #123027 (slipped into this PR instead)
  https://github.com/pytorch/pytorch/blob/3aa512cd72dc521ae09f5b96b8545366ca779593/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L2055

* [x] (8) **`nodes_before`**
  When adding a node in `NodeToONNX`, an unordered set `nodes_before` is built, which costs O(N). Then, all nodes in the graph are iterated (again O(N)) and compared against `nodes_before` to see which ones are new ones. The new ones finally get metadata of the original node.
  * **Possible solution**: I don’t know the code base well enough to say what is the cleanest solution. Install a hook into `g.op` to collect the new nodes? Set a global default metadata that all new nodes automatically get?
  * #123027
  https://github.com/pytorch/pytorch/blob/3aa512cd72dc521ae09f5b96b8545366ca779593/torch/csrc/jit/passes/onnx.cpp#L433

* [x] (9) **Loop over `symbol_dim_map`**
As part of `ONNXShapeTypeInference`, the following functions are called and `symbol_dim_map` is passed through all the way down: `UpdateOutputTypeByONNXProto` -> `UpdateTorchValueByOnnxValueInfo` -> `TorchTensorTypeFromONNX` -> `ONNXDimToShapeSymbol`.
This final function does a reverse-lookup incurring a O(N) cost.
  * **Possible solution**: Build and maintain a dim-to-symbol map (the reverse of the `symbol_dim_map`)? I haven’t given this one much thought.
  * #123029
  https://github.com/pytorch/pytorch/blob/3aa512cd72dc521ae09f5b96b8545366ca779593/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L100

* (10) **Pre-/post-conversion costs** (out of scope for this issue)
  With all the above changes, the time between each `NodeToONNX` becomes effectively constant. However, there are still some costs that seem to grow with O(N^2), either before or after. I haven’t analyzed this yet. I estimate Llama2 7B would already be <10m with the above changes.

Note, partial fixes can cut export time and mitigate the problem. However, to get to de facto linear time complexity, all need to be addressed.

**Comment by albanD** [comment]
@tringwald why did you tag this as "triage review"?

**Comment by tringwald** [comment]
> @tringwald why did you tag this as "triage review"?

I wasn't sure if this might also need a high prio label. It seems to be a 9x slowdown, according to the numbers above. Is there a better label to get someone to have a second look?

**Comment by albanD** [comment]
Leaving the issue without the "triaged" label means that the general triage oncall will look at it. That should be good in most cases. "triage review" is for issues that are discussed during the weekly triage meeting.

**Comment by justinchuby** [comment]
Thank you, and we appreciate the in-depth analysis! For context, we have been working on the `torch.onnx.dynamo_export` api that leverages `dynamo` from PyTorch 2 to create a new exporter. Please give it a try and see if you experience the same slow down. We expect this `api` to be the new official ONNX export api in the coming months. You may read more on https://pytorch.org/docs/stable/onnx_dynamo.html

**Comment by gustavla** [comment]
@justinchuby I'm aware of the dynamo export and look forward to it hardening and coming out of beta. From my experience so far, it is not ready to replace onnx.export. The models that motivated this analysis do not export at all with dynamo. For these reasons, I think it's worth addressing these speed issues to tide some of the bigger Gen AI use cases over. I have fixes locally that I can upstream and I'm in the process of trying it out on hundreds of models to see if there are any regressions (not all changes can 100% guarantee functional equivalence). I'm happy to start putting up PRs if there is interest in reviewing and getting them in, even though this exporter is on the way out.

**Comment by justinchuby** [comment]
PRs are always welcome and appreciated. Thanks!

**Comment by gustavla** [comment]
Update: Two have merged and I just put up the final two, which means there are PRs for all remaining 7. I accidentally put up two duplicates (mistakes in my branch names had me confused), so those are the closed ones above that didn't merge.

**Comment by justinchuby** [comment]
All approved, please check PRs and adjust/rebase. Thanks!

**Comment by gustavla** [comment]
@justinchuby Thank you for the reviews. I really appreciate it!

**Comment by justinchuby** [comment]
Feel free to lmk when any of the open PRs are ready to merge. Thanks!

**Comment by justinchuby** [comment]
@gustavla When you are done updating the PRs, feel free to use pytorchbot merge to initiate the merge process. Thanks!

**Comment by gustavla** [comment]
All PRs have landed (huge thanks to @justinchuby for reviewing and merging!), so the main loop of the onnx export should now be de facto O(N) and not O(N^2). There may still be improvements in pre/post processing passes, but that is out of scope for this issue.

Closing as complete.
