### ISSUE TITLE
Performance improvement of tensor.to(device, dtype)

### ISSUE THREAD

**Issue by Redjest** [pytorch/pytorch#121414]
### 🚀 The feature, motivation and pitch

I'm training pytorch models on full size image data. The images dtype is uint8 (a common case), one byte per pixel per channel .

Profiling and optimizing our training loop, I saw that:
```python
image.to(device="cuda").to(dtype=torch.float32)
```
Is ~4 times faster then:
```python
image.to(device="cuda", dtype=torch.float32)
```
Which was comparable to:
```python
image.to(dtype=torch.float32).to(device="cuda")
```
This result was consistent on several machines.

The fact that coping after casting is slower is not surprising as we now copy x4 bytes, but the fact `image.to(device="cuda", dtype=torch.float32)` chooses to first cast and then `cudaMemcpy` might be surprising for less technical users. The problem with `image.to(device="cuda").to(dtype=torch.float32)` is that it might require holding for a moment both the `uint8` and the `float32` arrays in the device memory, which might OOM the device even if either array would fit.

As `cudaMemcpy` and `cudaMemcpyAsync`  don't support casting on-the-fly, it requires some trick. I'm not a big CUDA engineer, but I can imagine that a CUDA kernel reading the data from a host via Unified Memory and statically casting while writing to device memory might to the job. If this is an interesting direction I can try benchmarking.

### Alternatives

To document the memory usage-performance tradeoff between `image.to(device="cuda", dtype=torch.float32)` and `image.to(device="cuda").to(dtype=torch.float32)` in the docs of the `to()` method.

### Additional context

# CUDA I/O issue demonstration
```python
import torch
from time import time
```
Let's create a tensor of 1000 images with 3 channels, 1650x880 pixels each. We will use `torch.uint8` as the data type to represent classic RGB images:
```python
images = torch.randint(0, 255, (1000, 3, 1650, 880), dtype=torch.uint8)
```
We want to convert the data type to `torch.float32` and move the tensor to the GPU. We can do it in two ways:
- Try to move the tensor to the GPU and convert in the same step.
```python
t = time()
for i in range(1000):
    img = images[i].to(device="cuda", dtype=torch.float32)
float_time = (time() - t)/1000
print(f"First method transfer time: {float_time:.2g} per image")
```
> First method transfer time: 0.0042 per image

- Move the tensor to the GPU and then convert the data type.
```python
t = time()
for i in range(1000):
    img = images[i].to(device="cuda").to(dtype=torch.float32)
int_time = (time() - t)/1000
print(f"Second method transfer time: {int_time:.2g} per image")
```
> Second method transfer time: 0.00084 per image
```python
print(f"The ratio between the two methods is {float_time/int_time:.2g}")
```
> The ratio between the two methods is 5

**Comment by albanD** [comment]
This will be fixed by https://github.com/pytorch/pytorch/pull/121341 :)

**Comment by albanD** [comment]
Fixed!

**Comment by Redjest** [comment]
> However, I don't see a good way to always minimize transfer size, for non-blocking copies we need to run conversions on gpu to preserve streaming semantics, alternative ways of achieving this are very clumsy (and users who are very perf-conscious can do explicit conversions themselves).  

I'd just consider documenting this behavior, maybe a note in the docs of 'to()'. On a training pipeline that I helped to optimize, which has large image data, but relatively small models, this little issue was 2.3x speedup of the entire training (originally 3 weeks).

**Comment by Geremia** [comment]
@Redjest Did you try `.float()`? If so, how'd that compare?

**Comment by Redjest** [comment]
> @Redjest Did you try `.float()`? If so, how'd that compare?

Running the following benchmark:
```python
t = time()
for i in range(1000):
    img = images[i].to(device="cuda").float()
bare_float_time = (time() - t)/1000
print(f"Second method transfer time: {bare_float_time:.2g} per image")
```
Returns equivalent results to `images[i].to(device="cuda").to(dtype=torch.float32)` under pytorch `2.2.1`
