### ISSUE TITLE
Running `lintrunner init` under Python3.8 got error: `No matching distribution found for torchfix==0.4.0`

### ISSUE THREAD

**Issue by LamForest** [pytorch/pytorch#121591]
## Error
`No matching distribution found for torchfix==0.4.0` under python3.8

## How to reproduce

1. Create a Python3.8 env
2. Get pytorch Source Code
3. `pip install lintrunner; lintrunner init` following https://github.com/pytorch/pytorch/wiki/lintrunner

## The cause of this bug

1. pytorch force use torchfix=0.4.0: https://github.com/pytorch/pytorch/blob/660ec3d38d9d1c8567471ae7fe5b40ae7c6d7438/.lintrunner.toml#L49

2. torchfix=4.0 support only >= python 3.9: https://github.com/pytorch-labs/torchfix/pull/20, but pytorch still supports 3.8:
<img width="922" alt="image" src="https://github.com/pytorch/pytorch/assets/17798738/dc9f774c-04b5-42f5-80c2-eff3ca5b50fa">

Maybe we should match the version.

## Full log
```
╰─ lintrunner init                                                                                                    ─╯
Warning: Could not find a lintrunner config at: '.lintrunner.private.toml'. Continuing without using configuration file.
[2024-03-10T05:14:50Z INFO lintrunner::linter] Initializing linter: 'FLAKE8'
[2024-03-10T05:14:50Z INFO lintrunner::linter] the init commands are ["python3", "tools/linter/adapters/pip_init.py", "--dry-run=0", "flake8==6.1.0", "flake8-bugbear==23.3.23", "flake8-comprehensions==3.12.0", "flake8-executable==2.1.3", "flake8-logging-format==0.9.0", "flake8-pyi==23.3.1", "flake8-simplify==0.19.3", "mccabe==0.7.0", "pycodestyle==2.11.1", "pyflakes==3.1.0", "torchfix==0.4.0"]
<MainThread:DEBUG> $ pip3 install flake8==6.1.0 flake8-bugbear==23.3.23 flake8-comprehensions==3.12.0 flake8-executable==2.1.3 flake8-logging-format==0.9.0 flake8-pyi==23.3.1 flake8-simplify==0.19.3 mccabe==0.7.0 pycodestyle==2.11.1 pyflakes==3.1.0 torchfix==0.4.0
Requirement already satisfied: flake8==6.1.0 in /root/miniconda/envs/python38_torch201_cuda/lib/python3.8/site-packages (6.1.0)
Collecting flake8-bugbear==23.3.23
  Using cached flake8_bugbear-23.3.23-py3-none-any.whl.metadata (25 kB)
Collecting flake8-comprehensions==3.12.0
  Using cached flake8_comprehensions-3.12.0-py3-none-any.whl.metadata (11 kB)
Collecting flake8-executable==2.1.3
  Using cached flake8_executable-2.1.3-py3-none-any.whl.metadata (3.4 kB)
Collecting flake8-logging-format==0.9.0
  Using cached flake8-logging-format-0.9.0.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting flake8-pyi==23.3.1
  Using cached flake8_pyi-23.3.1-py3-none-any.whl.metadata (13 kB)
Collecting flake8-simplify==0.19.3
  Using cached flake8_simplify-0.19.3-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: mccabe==0.7.0 in /root/miniconda/envs/python38_torch201_cuda/lib/python3.8/site-packages (0.7.0)
Requirement already satisfied: pycodestyle==2.11.1 in /root/miniconda/envs/python38_torch201_cuda/lib/python3.8/site-packages (2.11.1)
Requirement already satisfied: pyflakes==3.1.0 in /root/miniconda/envs/python38_torch201_cuda/lib/python3.8/site-packages (3.1.0)
ERROR: Ignored the following versions that require a different python version: 0.4.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement torchfix==0.4.0 (from versions: 0.0.1, 0.0.2, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.3.0)
ERROR: No matching distribution found for torchfix==0.4.0
<MainThread:DEBUG> took 4332ms
Traceback (most recent call last):
  File "tools/linter/adapters/pip_init.py", line 83, in <module>
    run_command(pip_args)
  File "tools/linter/adapters/pip_init.py", line 18, in run_command
    return subprocess.run(args, check=True)
  File "/root/miniconda/envs/python38_torch201_cuda/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pip3', 'install', 'flake8==6.1.0', 'flake8-bugbear==23.3.23', 'flake8-comprehensions==3.12.0', 'flake8-executable==2.1.3', 'flake8-logging-format==0.9.0', 'flake8-pyi==23.3.1', 'flake8-simplify==0.19.3', 'mccabe==0.7.0', 'pycodestyle==2.11.1', 'pyflakes==3.1.0', 'torchfix==0.4.0']' returned non-zero exit status 1.
[2024-03-10T05:14:55Z INFO lintrunner::linter] the status is ExitStatus(unix_wait_status(256))
error:        lint initializer for 'FLAKE8' failed with non-zero exit code
```

### Versions

╰─ python collect_env.py                                                                                              ─╯
Collecting environment information...
PyTorch version: 2.3.0a0+git2ccc7af
Is debug build: True
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.27.7
Libc version: glibc-2.31

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.14.0_1-0-0-48-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8350C CPU @ 2.60GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         800.000
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5200.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts avx512vbmi umip pku avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] onnx==1.15.0
[pip3] onnxruntime==1.3.0
[pip3] torch==2.3.0a0+git7df06be
[pip3] torchtext==0.4.0
[pip3] torchvision==0.15.2+cu117
[pip3] triton==2.0.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] torch                     2.3.0a0+git7df06be           dev_0    <develop>
[conda] torchtext                 0.4.0                    pypi_0    pypi
[conda] torchvision               0.15.2+cu117             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by kit1980** [comment]
TorchFix 0.4.0 only supports only Python 3.9+.
I'll look if there is an easy way to don't install TorchFix for Python 3.8, but this version on Python is going away soon anyway https://github.com/pytorch/pytorch/issues/120718.

**Comment by LamForest** [comment]
@kit1980 Sure, I need to migrate my dev to Python3.9+
