### ISSUE TITLE
[Dynamo] einsum `ConstantVariable(str: 'i').has_unpack_var_sequence(tx)` returns True

### ISSUE THREAD

**Issue by StellarrZ** [pytorch/pytorch#121551]
### 🐛 Describe the bug

While trying to handle `VariableTracker` unpack under `has_torch_function` in more generic way, [`TestEinsumOverride`](https://github.com/pytorch/pytorch/blob/5a0a964444d6be3b2762d30f5aec456060fa63c8/test/test_overrides.py#L880-L881) triggers infinite recursion. This is because `ConstantVariable(str: 'i,j->ij')` unpacks to a sequence containing `ConstantVariable(str: 'i')`, and then `ConstantVariable(str: 'i').has_unpack_var_sequence(tx)` always return `True`.

Please see Minified repro

## Failure
```
torch._dynamo.exc.InternalTorchDynamoError: maximum recursion depth exceeded while calling a Python object

from user code:
   File "test_overrides.py", line 880, in torch_dynamo_resume_in_test_wrapper_at_879
    self.assertEqual(torch.einsum('i,j->ij', x, y)._data,

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

## Debug Hints - Infinite Recursion
```
(/home/zesheng/env/py38) [zesheng@hostname~/pytorch/test (einsum_failure)]$ PYTORCH_TEST_WITH_DYNAMO=1 python -s test_overrides.py -v -k TestEinsumOverride
test_wrapper (__main__.TestEinsumOverride) ... has_torch_function       <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 5)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 5)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 4)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 4)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     True    ConstantVariable(str: 'i,j->ij')
  len(vt.unpack_var_sequence(tx) := 7
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     True    ConstantVariable(str: 'i')
  len(vt.unpack_var_sequence(tx) := 1
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     True    ConstantVariable(str: 'i')
  len(vt.unpack_var_sequence(tx) := 1
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     True    ConstantVariable(str: 'i')
  len(vt.unpack_var_sequence(tx) := 1
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     True    ConstantVariable(str: 'i')
  len(vt.unpack_var_sequence(tx) := 1
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     True    ConstantVariable(str: 'i')
  len(vt.unpack_var_sequence(tx) := 1
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     True    ConstantVariable(str: 'i')
  len(vt.unpack_var_sequence(tx) := 1
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     True    ConstantVariable(str: 'i')
  len(vt.unpack_var_sequence(tx) := 1
```

## Debug Hints - Top level only
```
(/home/zesheng/env/py38) [zesheng@hostname ~/pytorch/test (einsum_failure)]$ PYTORCH_TEST_WITH_DYNAMO=1 python -s test_overrides.py -v -k TestEinsumOverride
test_wrapper (__main__.TestEinsumOverride) ... has_torch_function       <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 5)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 5)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 4)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 4)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     True    ConstantVariable(str: 'i,j->ij')
  len(vt.unpack_var_sequence(tx) := 7
has_torch_function      <class 'torch._dynamo.variables.lazy.LazyVariableTracker'>      False   UserDefinedObjectVariable(Wrapper)
has_torch_function      <class 'torch._dynamo.variables.user_defined.UserDefinedObjectVariable'>        False   UserDefinedObjectVariable(Wrapper)
has_torch_function      <class 'torch._dynamo.variables.lazy.LazyVariableTracker'>      False   UserDefinedObjectVariable(Wrapper)
has_torch_function      <class 'torch._dynamo.variables.lazy.LazyVariableTracker'>      False   UserDefinedObjectVariable(Wrapper)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 2)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 3)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 2)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 3)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 5)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 3)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 7)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 5)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 3)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 7)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 2)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 7)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 2)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     False   ConstantVariable(int: 7)
has_torch_function      <class 'torch._dynamo.variables.constant.ConstantVariable'>     True    ConstantVariable(str: 'ik,jkl,il->ij')
  len(vt.unpack_var_sequence(tx) := 13
has_torch_function      <class 'torch._dynamo.variables.lists.ListVariable'>    True    ListVariable()
  len(vt.unpack_var_sequence(tx) := 3
has_torch_function      <class 'torch._dynamo.variables.lazy.LazyVariableTracker'>      False   UserDefinedObjectVariable(Wrapper)
has_torch_function      <class 'torch._dynamo.variables.lazy.LazyVariableTracker'>      False   UserDefinedObjectVariable(Wrapper)
has_torch_function      <class 'torch._dynamo.variables.lazy.LazyVariableTracker'>      False   UserDefinedObjectVariable(Wrapper)
```

### Minified repro

Checkout or refer to [this commit](https://github.com/StellarrZ/pytorch/commit/202c889ef5578aca64c3ba9c95f7bee085f7135b).
Mainly to make [`has_torch_function`](https://github.com/pytorch/pytorch/blob/5a0a964444d6be3b2762d30f5aec456060fa63c8/torch/_dynamo/utils.py#L2484-L2491) in `/home/zesheng/pytorch/torch/_dynamo/utils.py` be like the following segment 
```
def has_torch_function(
    vt: "torch._dynamo.variables.base.VariableTracker",
    tx: "torch._dynamo.symbolic_convert.InstructionTranslatorBase",
) -> bool:
    from torch._dynamo.variables import UserDefinedObjectVariable
    from torch._dynamo.variables.torch_function import TensorWithTFOverrideVariable

    if vt.has_unpack_var_sequence(tx):
        return any(has_torch_function(v, tx) for v in vt.unpack_var_sequence(tx))
    else:
        return isinstance(vt, TensorWithTFOverrideVariable) or (
            isinstance(vt, UserDefinedObjectVariable)
            and hasattr(vt.value, "__torch_function__")
        )
```
Run command
```
PYTORCH_TEST_WITH_DYNAMO=1 python -s test_overrides.py -v -k TestEinsumOverride
```

### Versions

# Should be irrelevant

Collecting environment information...
PyTorch version: 2.3.0a0+git5929d4e
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.34

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-0_fbk21_hardened_rc9_12630_gab30f3f5259a-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          15
On-line CPU(s) list:             0-14
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 9654 96-Core Processor
CPU family:                      25
Model:                           17
Thread(s) per core:              1
Core(s) per socket:              15
Socket(s):                       1
Stepping:                        1
BogoMIPS:                        4792.79
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 clzero xsaveerptr wbnoinvd arat npt lbrv nrip_save tsc_scale vmcb_clean pausefilter pfthreshold v_vmsave_vmload vgif avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
Virtualization:                  AMD-V
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       960 KiB (15 instances)
L1i cache:                       960 KiB (15 instances)
L2 cache:                        7.5 MiB (15 instances)
L3 cache:                        240 MiB (15 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-14
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] optree==0.10.0
[pip3] torch==2.3.0a0+git5929d4e
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-include               2023.1.0         h06a4308_46344  
[conda] mkl-service               2.4.0            py38h5eee18b_1  
[conda] mkl_fft                   1.3.8            py38h5eee18b_0  
[conda] mkl_random                1.2.4            py38hdb19cb5_0  
[conda] numpy                     1.24.3           py38hf6e8229_1  
[conda] numpy-base                1.24.3           py38h060ed82_1  
[conda] optree                    0.10.0                   pypi_0    pypi
[conda] torch                     2.3.0a0+git5929d4e           dev_0    <develop>

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by sun-jacobi** [comment]
@williamwen42 @StellarrZ  Hi, can I work on this issue?

**Comment by williamwen42** [comment]
Go for it! Please assign yourself if you are working on it.

**Comment by williamwen42** [comment]
Closing since this doesn't look like a real (i.e. existant) dynamo error - reported error is coming from a change to an interaction between `has_torch_function` and `has_unpack_var_sequence`/`unpack_var_sequence`.
