### ISSUE TITLE
reduce_on_plateau_scheduler.h missing from optim.h in libtorch ?

### ISSUE THREAD

**Issue by blegouix** [pytorch/pytorch#121593]
### 🚀 The feature, motivation and pitch

Hello,

I have been able to successfully use ReduceLROnPlateauScheduler in C++ with libtorch, but I had to include it manually:

`#include <torch/optim/schedulers/reduce_on_plateau_scheduler.h>`

Maybe you forgot to include it in the file:

`torch/csrc/api/include/torch/optim.h`

Or it is intentional ?

cc @jbschlosser @vincentqb @albanD @janeyx99 @crcrpar

**Comment by albanD** [comment]
Ho yes that looks like an oversight. Would you be able to send a PR to fix this?

**Comment by blegouix** [comment]
I sent a PR
