### ISSUE TITLE
[aarch64 linux ci] missing sccache binaries for aarch64 linux platform

### ISSUE THREAD

**Issue by snadampal** [pytorch/pytorch#121559]
### 🐛 Describe the bug

Currently pytorch CI build infrastructure maintains sccache binaries only for x86 architecture. We need the aarch64 linux binaries to speed up the aarch64 ci workflows.  Currently aarch64 linux workflow is crashing if sccache is enabled because x86 binaries are pulled.

```
sccache_epilogue' EXIT
++ [[ -n 1 ]]
++ echo 'Skipping sccache server initialization, setting environment variables'
Skipping sccache server initialization, setting environment variables
++ export SCCACHE_IDLE_TIMEOUT=0
++ SCCACHE_IDLE_TIMEOUT=0
++ export SCCACHE_ERROR_LOG=/var/lib/jenkins/sccache_error.log
++ SCCACHE_ERROR_LOG=/var/lib/jenkins/sccache_error.log
++ export RUST_LOG=sccache::server=error
++ RUST_LOG=sccache::server=error
++ sccache --zero-stats
.ci/pytorch/common-build.sh: line 47: /opt/cache/bin/sccache: cannot execute binary file: Exec format error
```

### Versions

aarch64 linux runner:
```
ami-id: ami-0b1c2e7eafac77408
instance-id: i-0fbadc66663ad3bdc
instance-type: t4g.2xlarge
system info Linux ip-10-0-42-211.ec2.internal 4.14.336-[25](https://github.com/pytorch/pytorch/actions/runs/8164152112/job/22318870156#step:4:27)6.559.amzn2.aarch64 #1 SMP Tue Feb 13 09:50:21 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

cc @malfet

**Comment by elkay** [comment]
Is this a request to be able to have aarch64 directly installable from pip without manually building? Because that's what I came here to find out about and request. It's been incredibly painful trying to work with torch + cuda on the new AWS Graviton servers. They're so much cheaper to run but it's getting to a point that the time sink to fight around torch issues is making me question the decision.

**Comment by snadampal** [comment]
Hi @elkay , this issue is specific to CI scripts where the sccache binaries are pulled from AWS S3 and currently there are no aarch64 linux binaries on this S3 bucket. However, I see that sccache python wheel already exists for aarch64 ([link](https://pypi.org/project/sccache/#files)), we will fix the CI scripts to use the right binaries.

Can you please list down the packages you see missing for torch+cuda on AWS Graviton servers? We are able to use torch (and also torch+cuda) on AWS Graviton with minimal effort.

**Comment by elkay** [comment]
> Hi @elkay , this issue is specific to CI scripts where the sccache binaries are pulled from AWS S3 and currently there are no aarch64 linux binaries on this S3 bucket. However, I see that sccache python wheel already exists for aarch64 ([link](https://pypi.org/project/sccache/#files)), we will fix the CI scripts to use the right binaries.
> 
> Can you please list down the packages you see missing for torch+cuda on AWS Graviton servers? We are able to use torch (and also torch+cuda) on AWS Graviton with minimal effort.

It's that there are no native wheels to install direct from pip for the graviton servers so I've been forced to try to compile each one that I want to use (torch and torchvision currently). I was finally able to get both to compile but I still cannot get torchvision to load with image (JPEG/PNG) support.

**Comment by elkay** [comment]
Just to follow-up, the biggest annoyance is trying to "protect" the built-from-source torch packages, as I'm trying to use stuff like text-generation-webui and it seems like all over the place things are trying to overwrite them with non-cuda versions. I've basically had to ignore any automatic setups and running of requirements directly and make sure that --no-deps is used everywhere, which makes for a painful manual install of any packages that need installing. I've had the CUDA versions overwritten one too many times and had to either start over or restore from snapshots.

**Comment by snadampal** [comment]
Hi @elkay, you could use docker container that comes with all the pre-installed packges, please refer to this article for more details.
https://medium.com/@wayne_toh/using-graviton-g5g-instances-with-nvidia-ngc-containers-16fcd9bb3062

**Comment by snadampal** [comment]
Hi @elkay PyTorch DLAMI for AWS g5g instances is available now: 
https://aws.amazon.com/releasenotes/aws-deep-learning-arm64-ami-gpu-pytorch-2-2-ubuntu-20-04/

**Comment by phs** [comment]
> We are able to use torch (and also torch+cuda) on AWS Graviton with minimal effort.

@snadampal Can you expand on what you mean by this?  I'm trying to reconcile it with elkay's experience:

> It's that there are no native torch+cuda wheels to install direct from pip for the graviton servers

..which matches my own.

Does the "minimal effort" involve privately compiling pytorch on arm from scratch?

The deep learning AMI is interesting to me, but it will involve a non-trivial effort to adopt.

**Comment by snadampal** [comment]
Hi @phs ,
I was referring to the deep learning AMI: https://aws.amazon.com/releasenotes/aws-deep-learning-arm64-ami-gpu-pytorch-2-2-ubuntu-20-04/
