### ISSUE TITLE
Make builds repeatable multiple times from same git checkout

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/pytorch#121507]
### 🐛 Describe the bug

When we build pytorch, we create temporary files in the source tree that prevent successive builds in the same checkout with `python setup.py develop` - this is not an issue for our builds which (presumably) only run once with a checkout, but can make iterating on pytorch itself hard for developers running local builds?

`make clean` does not remove these files today.  We might either create the files in build/, or give users a way to remove these files easily?  (Might be as simple as git status and remove those files?)

Examples:
```
	aten/src/ATen/UfuncCPUKernel_add.cpp.DEFAULT.cpp
	aten/src/ATen/core_generated_declarations_yaml.cmake
	aten/src/ATen/core_generated_headers.cmake
	aten/src/ATen/core_generated_sources.cmake
	aten/src/ATen/cpu_vec_generated_declarations_yaml.cmake
	aten/src/ATen/cpu_vec_generated_headers.cmake
	aten/src/ATen/cpu_vec_generated_sources.cmake
	aten/src/ATen/cuda_generated_declarations_yaml.cmake
[...]
	aten/src/ATen/native/cpu/UpSampleKernel.cpp.DEFAULT.cpp
	aten/src/ATen/native/cpu/UpSampleKernel.cpp.DEFAULT.cpp.DEFAULT.cpp
	aten/src/ATen/native/cpu/UpSampleMoreKernel.cpp.DEFAULT.cpp
[...]
	aten/src/ATen/native/quantized/cpu/kernels/QuantizedOpKernels.cpp.DEFAULT.cpp.DEFAULT.cpp
	aten/src/ATen/ops_generated_declarations_yaml.cmake
	aten/src/ATen/ops_generated_headers.cmake
	aten/src/ATen/ops_generated_sources.cmake
	c10/macros/cmake_macros.h
	caffe2/build_variables.bzl
	confu-deps/
```

### Versions

source code as of March 7, 2024.

cc @malfet @seemethere

**Comment by malfet** [comment]
Hmm, this sounds weird, as those files should indeed be created in the build folder, at least that's the case for me:
```
% find . -iname UpSampleKernel.cpp.DEFAULT.cpp
./build/aten/src/ATen/native/cpu/UpSampleKernel.cpp.DEFAULT.cpp
```

**Comment by mikekgfb** [comment]
> Hmm, this sounds weird, as those files should indeed be created in the build folder, at least that's the case for me:
> 
> ```
> % find . -iname UpSampleKernel.cpp.DEFAULT.cpp
> ./build/aten/src/ATen/native/cpu/UpSampleKernel.cpp.DEFAULT.cpp
> ```

it ended up in a weird state, but I can;' repro the exact steps.  Everything works for me now,after git status and removing all the listed files.
