### ISSUE TITLE
DISABLED test_cond_simple_abi_compatible_cuda (__main__.AOTInductorTestABICompatibleCuda)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#121512]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_aot_inductor.py%3A%3AAOTInductorTestABICompatibleCuda%3A%3Atest_cond_simple_abi_compatible_cuda%22%5D)).

Broken by https://github.com/pytorch/pytorch/pull/121120

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by aakhundov** [comment]
Closing as the forward-fix has landed in https://github.com/pytorch/pytorch/pull/121522.
