### ISSUE TITLE
RuntimeError: invalid unordered_map<K, T> key

### ISSUE THREAD

**Issue by yongxin3344520** [pytorch/pytorch#121572]
### 🐛 Describe the bug

When I export the onnx model and execute it to:
```
  Output=self. sense (context_layer)
```
Throw exception:
```
....
  File "D:\ai\miniconda\envs\pytorch2.2.1\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\yl/.cache\huggingface\modules\transformers_modules\chatglm3-6b\modeling_chatglm.py", line 448, in forward
    output = self.dense(context_layer)
  File "D:\ai\miniconda\envs\pytorch2.2.1\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ai\miniconda\envs\pytorch2.2.1\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ai\miniconda\envs\pytorch2.2.1\lib\site-packages\torch\nn\modules\module.py", line 1501, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "D:\ai\miniconda\envs\pytorch2.2.1\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ai\miniconda\envs\pytorch2.2.1\lib\site-packages\bitsandbytes\nn\modules.py", line 248, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "D:\ai\miniconda\envs\pytorch2.2.1\lib\site-packages\bitsandbytes\autograd\_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "D:\ai\miniconda\envs\pytorch2.2.1\lib\site-packages\torch\autograd\function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
RuntimeError: invalid unordered_map<K, T> key
```
When defining: 
```
self. sense=nn Linear (self. project_size, config. hiddend_size, bias=config. add_bias linear,
Device=device, * * config_to_kwargs (config)
）
```
When I debug to the line: 
```
 output=self. sense (context_layer),
```
self. sense is actually  bitsandbytes. nn. modules Linear4 bit (nn. Linear)
```

class Linear4bit(nn.Linear):
    def __init__(self, input_features, output_features, bias=True, compute_dtype=None, compress_statistics=True, quant_type='fp4',device=None):
        super().__init__(input_features, output_features, bias, device)
        self.weight = Params4bit(self.weight.data, requires_grad=False, compress_statistics=compress_statistics, quant_type=quant_type)
        self.compute_dtype = compute_dtype
        self.compute_type_is_set = False

    def set_compute_type(self, x):
        if x.dtype in [torch.float32, torch.bfloat16]:
            # the input is in a dtype that is safe to compute in, we switch
            # to this type for speed and stability
            self.compute_dtype = x.dtype
        elif x.dtype == torch.float16:
            # we take the compoute dtype passed into the layer
            if self.compute_dtype == torch.float32 and (x.numel() == x.shape[-1]):
                # single batch inference with input torch.float16 and compute_dtype float32 -> slow inference when it could be fast
                # warn the user about this
                warnings.warn(f'Input type into Linear4bit is torch.float16, but bnb_4bit_compute_type=torch.float32 (default). This will lead to slow inference.')
                warnings.filterwarnings('ignore', message='.*inference.')
            if self.compute_dtype == torch.float32 and (x.numel() != x.shape[-1]):
                warnings.warn(f'Input type into Linear4bit is torch.float16, but bnb_4bit_compute_type=torch.float32 (default). This will lead to slow inference or training speed.')
                warnings.filterwarnings('ignore', message='.*inference or training')


    def forward(self, x: torch.Tensor):
        # weights are cast automatically as Int8Params, but the bias has to be cast manually
        if self.bias is not None and self.bias.dtype != x.dtype:
            self.bias.data = self.bias.data.to(x.dtype)

        if getattr(self.weight, 'quant_state', None) is None:
            print('FP4 quantization state not initialized. Please call .cuda() or .to(device) on the LinearFP4 layer first.')
        if not self.compute_type_is_set:
            self.set_compute_type(x)
            self.compute_type_is_set = True

        inp_dtype = x.dtype
        if self.compute_dtype is not None:
            x = x.to(self.compute_dtype)

        bias = None if self.bias is None else self.bias.to(self.compute_dtype)
        out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state) 

        out = out.to(inp_dtype)

        return out
```

```
def matmul_4bit(A: tensor, B: tensor, quant_state: List, out: tensor = None, bias=None):
    assert quant_state is not None
    if A.numel() == A.shape[-1] and A.requires_grad == False:
        absmax, shape, dtype, blocksize, compressed_stats, quant_type, data_type = quant_state
        if A.shape[-1] % blocksize != 0:
            warn(f'Some matrices hidden dimension is not a multiple of {blocksize} and efficient inference kernels are not supported for these (slow). Matrix input size found: {A.shape}')
            return MatMul4Bit.apply(A, B, out, bias, quant_state)
        else:
            out = F.gemv_4bit(A, B.t(), out, state=quant_state)
            if bias is not None:
                out += bias
            return out
    else:
        return MatMul4Bit.apply(A, B, out, bias, quant_state)
```

This exception is MatMul4Bit.apply(A, B, out, bias, quant_state) ,   in file torch.autograd.function.py.apply .  Pytorch version is 2.2.1(stable) .

### Versions

os:  win10
cuda: 11.8
pytorch:  2.2.1 (stable)

====other=====

accelerate                0.27.2
aiofiles                  23.2.1
altair                    5.2.0
annotated-types           0.6.0
anyio                     4.3.0
APScheduler               3.10.4
attrs                     23.2.0
backports.zoneinfo        0.2.1
bitsandbytes              0.41.0
bitsandbytes-windows      0.37.5
blinker                   1.7.0
certifi                   2022.12.7
charset-normalizer        2.1.1
click                     8.1.7
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.1.1
cpm-kernels               1.0.11
cycler                    0.12.1
DBUtils                   3.0.3
et-xmlfile                1.1.0
exceptiongroup            1.2.0
fastapi                   0.110.0
ffmpy                     0.3.2
filelock                  3.9.0
Flask                     3.0.1
Flask-APScheduler         1.13.1
flatbuffers               24.3.7
fonttools                 4.49.0
fsspec                    2023.10.0
gradio                    4.20.1
gradio_client             0.11.0
h11                       0.14.0
httpcore                  1.0.4
httpx                     0.27.0
huggingface-hub           0.19.4
humanfriendly             10.0
idna                      3.4
importlib-metadata        7.0.1
importlib_resources       6.1.2
itsdangerous              2.1.2
Jinja2                    3.1.2
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
latex2mathml              3.77.0
Markdown                  3.5.2
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.7.5
mdtex2html                1.3.0
mdurl                     0.1.2
mpmath                    1.3.0
networkx                  3.0
numpy                     1.24.1
onnx                      1.15.0
onnxruntime-gpu           1.17.1
opencv-python             4.9.0.80
openpyxl                  3.1.2
orjson                    3.9.15
packaging                 23.2
pandas                    2.0.3
peft                      0.9.0
Pillow                    9.3.0
pip                       23.3.1
pkgutil_resolve_name      1.3.10
protobuf                  4.25.3
psutil                    5.9.8
py-cpuinfo                9.0.0
pydantic                  2.6.3
pydantic_core             2.16.3
pydub                     0.25.1
Pygments                  2.17.2
PyMySQL                   1.1.0
pyparsing                 3.1.2
pyreadline3               3.4.1
python-dateutil           2.8.2
python-multipart          0.0.9
pytz                      2023.3.post1
PyYAML                    6.0.1
referencing               0.33.0
regex                     2023.10.3
requests                  2.28.1
rich                      13.7.1
rpds-py                   0.18.0
ruff                      0.3.1
safetensors               0.4.1
scipy                     1.10.1
seaborn                   0.13.2
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                68.0.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
starlette                 0.36.3
sympy                     1.12
thop                      0.1.1.post2209072238
tokenizers                0.13.3
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.2.1+cu118
torchaudio                2.2.1+cu118
torchvision               0.17.1+cu118
tqdm                      4.66.1
transformers              4.33.0
typer                     0.9.0
typing_extensions         4.10.0
tzdata                    2023.3
tzlocal                   5.2
ultralytics               8.1.24
urllib3                   1.26.13
uvicorn                   0.27.1
websockets                11.0.3
Werkzeug                  3.0.1
wheel                     0.41.2
xlrd                      2.0.1
zipp                      3.17.0

**Comment by thiagocrepaldi** [comment]
Closing as there is no response in the last 30 days
