### ISSUE TITLE
SIGILL / ILL_ILLOPN crash when using AOT Inductor pre-compiled model (torch 2.2)

### ISSUE THREAD

**Issue by bsergean** [pytorch/pytorch#121516]
### 🐛 Describe the bug

We are getting a crash with this backtrace:

torch::inductor::AOTIModelContainerRunner::AOTIModelContainerRunner 
at::DynamicLibrary::sym 
(dso) (no symbol)
(libc) (no symbol)
(dso) -> crash

We checked the processors flags were the problem happened (it doesn't happen everywhere), and the machine were we compile has more flags (avx512xxx) than the machines where it runs.

I think our next step will be to add a wrapper around g++, that disable some avx instructions, and point CXX to it, but maybe there's a better way.

(I noticed an 'ISA' option but I'm not sure on how to use it).

```python
# config specific to codegen/cpp.py
class cpp:
    # set to torch.get_num_threads()
    threads = -1

    # Do not generate loops when the condition doesn't hold, like:
    # for(long i0=4096; i0<4096; i0+=1)
    no_redundant_loops = True

    # Assume number of threads is dynamic, don't specialize thread number.
    # Kernels don't recompile on thread number changes with this flag on.
    # For single-threaded workload, turning it on would incur a slight
    # performance degradation.
    dynamic_threads = False

    simdlen: Optional[int] = None
    min_chunk_size = 4096
    cxx = (
        None,  # download gcc12 from conda-forge if conda is installed
        # "g++-12",
        # "g++-11",
        # "g++-10",
        # "clang++",
        os.environ.get("CXX", "clang++" if sys.platform == "darwin" else "g++"),
        # "g++.par",
    )
    # Allow kernel performance profiling via PyTorch profiler
    enable_kernel_profile = False

    # enable weight prepacking to get a better performance; may lead to large memory footprint
    weight_prepack = True

    # Inject a bug into our relu implementation; useful for testing our repro
    # extraction and minification functionality.
    # Valid values: "compile_error", "runtime_error", "accuracy"
    inject_relu_bug_TESTING_ONLY: Optional[str] = None
    inject_log1p_bug_TESTING_ONLY: Optional[str] = None

    # If None, autodetect whether or not AVX512/AVX2 can be used.  Otherwise,
    # force usage as specified, without testing.
    vec_isa_ok: Optional[bool] = None
```

We could also try to hack and remove this:

```
    if sys.platform == "darwin":
        # Per https://mac.r-project.org/openmp/ right way to pass `openmp` flags to MacOS is via `-Xclang`
        # Also, `-march=native` is unrecognized option on M1
        base_flags += " -Xclang"
    else:
        if platform.machine() == "ppc64le":
            base_flags += " -mcpu=native"
        else:
            base_flags += " -march=native"
```

(-march=native)

### Versions

pytorch-2.2.0

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

**Comment by bsergean** [comment]
This is what we're doing now, little script created and we do env CXX=/path/to/fake_g++.py / we'll see soon if it works.

```
#!/usr/bin/env python3

import os, sys

if __name__ == '__main__':
    args = sys.argv[1:]

    # https://stackoverflow.com/questions/63622900/disable-all-avx-512-instructions-for-g-build
    args.append('-march=native')
    args.append('-mno-avx512f')

    cmd = 'g++ ' + ' '.join(args)
    print(cmd)
    os.system(cmd)
```

Bit of context is that this was a .dso compiled to run on a GPU (T4).

It's really a tough one, since pytorch uses cpuinfo which can detect some features at runtime maybe more protection could happen, but I think shipping binaries is tough.

Some software have long history of shipping .dso (Mozilla had this, Photoshop had plugins, gcc had this), maybe there's more that can be done.

**Comment by ezyang** [comment]
Assuming we don't package cpuinfo into aotinductor (which is probably not the best idea, since then we have to compile and maintain multiple versions of the compiled versions), this is sort of related to cross compilation problems. Will be an issue for when we want to use AOTInductor to ship precompiled binaries in a variety of situations. Maybe it is best for AOTInductor dynamic libraries to have flavors and then have the runtime switch between them.

**Comment by bsergean** [comment]
FYI the CXX hack worked for us, so we are unblocked.

**Comment by desertfire** [comment]
As @ezyang pointed out, AOTInductor doesn't really support cross-compilation. For your specific use case, do you want to add an option to `torch/_inductor/config.py` to pass in additional arch-specific options? That will work nicer than your CXX hack.

**Comment by bsergean** [comment]
Yes our hack work, but a PR to allow adding special options would be an improvement. I should be able to do that when I get a chance, but if anyone wants to beat me to it please go ahead !

ps: we have multiple invocations of AOTInductor (one on T4 gpus, one on AMD machines etc...), this is how we're supporting multiple configs.

**Comment by bsergean** [comment]
Someone from our team might work on adding that option fyi.

**Comment by desertfire** [comment]
> Someone from our team might work on adding that option fyi.

That will be awesome!
