### ISSUE TITLE
torch._int_mm on CPU

### ISSUE THREAD

**Issue by maktukmak** [pytorch/pytorch#121647]
### 🚀 The feature, motivation and pitch

Currently, `torch._int_mm` is only supported on the CUDA backend. If this op was also supported for the CPU backend, we could use it for eager mode quantization on CPU devices. For example, the HF Quanto library uses this op in their quantized linear layers, which currently only works on CUDA. I suggest dispatching gemms from onednn when torch._int_mm is called with the CPU backend.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel
```[tasklist]
### Tasks
```

**Comment by maktukmak** [comment]
@jgong5 @Xia-Weiwen Thanks, looking forward to updates.

**Comment by mingfeima** [comment]
@Xia-Weiwen  please take care of `_scaled_mm` as well!

**Comment by vadimkantorov** [comment]
Now that torch.mm supports `out_dtype` arg, should torch._int_mm be added to the frontend to be dispatched as `torch.mm(A_int8, B_int8, out_dtype=torch.int32)`?
