### ISSUE TITLE
GPU hangs after killing the program using DistributedDataparallel Model

### ISSUE THREAD

**Issue by boxwh1** [pytorch/pytorch#12166]
## 
GPU hangs after we kill training program by Ctrl+C.
The problem has occured three times when training ResNet-50 with the distributed examples forked from https://github.com/NVIDIA/apex.
When GPU hanged, we checked the status of processes.
We found there was one  process with the status of D, so we could not kill it even with "kill -9" or "kill -18".
The nvidia-smi also became not available, and we could not use GPUs.
Then we must reboot the system to use GPUs again......
Besides, since all gpus hangs, we can not get more information when the problem happens.

We found the problem is similar with https://discuss.pytorch.org/t/when-i-shut-down-the-pytorch-program-by-kill-i-encountered-the-problem-with-the-gpu/6315.

## To Reproduce
The problem happens occasionally. So we can not always reproduce it......

## Environment

[environment collection script]

 - PyTorch Version (e.g., 1.0): 0.4.1
 - OS (e.g., Linux): ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 9.0/7.1.2
 - GPU models and configuration: P100-PCIe * 8/per nodes, two nodes connected with 100G infiniband
 - Any other relevant information:

**Comment by ailzhang** [comment]
For killing the program, maybe `nvidia-smi -r` is helpful?
cc: @teng-li for the GPU hang in distributed.

**Comment by boxwh1** [comment]
> For killing the program, maybe `nvidia-smi -r` is helpful?
> cc: @teng-li for the GPU hang in distributed.

Thanks. We will try it when the problem occurs again.

**Comment by boxwh1** [comment]
> > For killing the program, maybe `nvidia-smi -r` is helpful?
> > cc: @teng-li for the GPU hang in distributed.
> 
> Thanks. We will try it when the problem occurs again.

**Comment by boxwh1** [comment]
> For killing the program, maybe `nvidia-smi -r` is helpful?
> cc: @teng-li for the GPU hang in distributed.
 We encounter the problem again.  But _nvidia-smi -r_ is not helpful.

**Comment by pietern** [comment]
When this happens again, can you post:

* Output of nvidia-smi
* Number of processes that are still hanging around
* Their process state
* Number of processes, number of data loaders
* Anything else that may be relevant

**Comment by boxwh1** [comment]
> When this happens again, can you post:
> 
> * Output of nvidia-smi
> * Number of processes that are still hanging around
> * Their process state
> * Number of processes, number of data loaders
> * Anything else that may be relevant

* Nvidia-smi has no response, not working any more.
* All process are hanging, including all workers of data loader.
* One of the processes with the status -D, and other with the status -Z or -ZL
* We use 8 processes for 8 GPUs (DistributedDataParallel model), with 4 workers of data loader for each GPU.
* We guess some processes is starving when the connection between two nodes closes. Then the processes can not be closed normally.

**Comment by pietern** [comment]
Thanks for the update.

@ngimel @mruberry Do you know what can be done to debug this further?

**Comment by mruberry** [comment]
@csarofeen @mcarilli likely know better.

**Comment by mcarilli** [comment]
Yes, the dataloader's been reworked significantly to avoid hangs on ctrl+C.  This commit (from Oct 16) is around when we stopped seeing hangs on exit:https://github.com/pytorch/pytorch/commit/034c969f3c41efef75474f08bb09d29e91a20c19#diff-724910f4a1ffa1852a02e149b181ac22
I believe 0.4.1 does not include this commit.

**Comment by pietern** [comment]
@ngimel @mcarilli Thanks for the details!

@boxwh1 With 1.0 released last week, can you give it a try and see if the problem persists?

Closing the issue. Please feel free to reopen if this is still an issue.

**Comment by xingchensong** [comment]
hi, i  meet the same issue, my solution is :
try
`ps aux|grep python` 
and then 
`kill -9 PID`
be sure that kill process **in order**

**Comment by godblessY** [comment]
> > When this happens again, can you post:
> > 
> > * Output of nvidia-smi
> > * Number of processes that are still hanging around
> > * Their process state
> > * Number of processes, number of data loaders
> > * Anything else that may be relevant
> 
> * Nvidia-smi has no response, not working any more.
> * All process are hanging, including all workers of data loader.
> * One of the processes with the status -D, and other with the status -Z or -ZL
> * We use 8 processes for 8 GPUs (DistributedDataParallel model), with 4 workers of data loader for each GPU.
> * We guess some processes is starving when the connection between two nodes closes. Then the processes can not be closed normally.
 
i got the same issue with an oom error

**Comment by zengjie617789** [comment]
> be sure that kill process **in order**

what is the order when only one script is running
