### ISSUE TITLE
Setting PYTORCH_TESTING_DEVICE_ONLY_FOR doesn't work.

### ISSUE THREAD

**Issue by yan-yhy** [pytorch/pytorch#121608]
### 🐛 Describe the bug

example:
```
class TestAssertCloseMultiDevice(TestCase):
    @deviceCountAtLeast(1)
    def test_mismatching_device(self, devices):
        for actual_device, expected_device in itertools.permutations(("cpu", *devices), 2):
            actual = torch.empty((), device=actual_device)
            expected = actual.clone().to(expected_device)
            for fn in assert_close_with_inputs(actual, expected):
                with self.assertRaisesRegex(AssertionError, "device"):
                    fn()

    @deviceCountAtLeast(1)
    def test_mismatching_device_no_check(self, devices):
        for actual_device, expected_device in itertools.permutations(("cpu", *devices), 2):
            actual = torch.rand((), device=actual_device)
            expected = actual.clone().to(expected_device)
            for fn in assert_close_with_inputs(actual, expected):
                fn(check_device=False)


instantiate_device_type_tests(TestAssertCloseMultiDevice, globals(), only_for="cuda")
```
Users want run the test cases like this example on the privateuse1 device throw setting the PYTORCH_TESTING_DEVICE_ONLY_FOR_KEY = 'privateuse1' and the PYTORCH_TESTING_DEVICE_EXCEPT_FOR = 'cuda', but it doesn't wok. Because the 'desired_device_type_test_bases' in the funtion of get_desired_device_type_test_bases is [].
I think it should be fixed like the pr:
#121578

### Versions

source code as of March 9, 2024.

**Comment by yan-yhy** [comment]
@albanD Can the environment variables PYTORCH_TESTING_DEVICE_ONLY_FOR_KEY and PYTORCH_TESTING_DEVICE_EXCEPT_FOR be used like this?

**Comment by albanD** [comment]
I'm afraid I don't know, @clee2000 might know?

**Comment by clee2000** [comment]
Isn't the reason it only instantiates CUDA tests/doesn't instantiate for privateuse1 in the case you've given because of the `only_for="cuda"`?

**Comment by yan-yhy** [comment]
> Isn't the reason it only instantiates CUDA tests/doesn't instantiate for privateuse1 in the case you've given because of the `only_for="cuda"`?

Or use like this #122182, when users want to adapt some cuda testcases on other devices.
