### ISSUE TITLE
Complexity of output_graph.py:new_var() goes through the roof

### ISSUE THREAD

**Issue by dbabokin** [pytorch/pytorch#121679]
I'm running Google's [Gemma model](https://github.com/google/gemma_pytorch) with Dynamo enabled and PyTorch spends around 9 minutes in the Dynamo (just Dynamo, excluding Inductor). When profiling I see that ~5:30min is spend in `new_var()`:
https://github.com/pytorch/pytorch/blob/fd13a56f614effec0e731750264b92ac0a448835/torch/_dynamo/output_graph.py#L708-L714

Looks like low hanging fruit for compile time reduction.

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78

**Comment by dbabokin** [comment]
With profiler disabled the savings are less. If this function is linear instead of quadratic, the savings are 85 seconds. Still worth fixing.

**Comment by anijain2305** [comment]
Thanks. I will take a look this week.

If you can share repro, that would be helpful too. I can profile Dynamo more and see where rest 3:30 min go.

**Comment by ezyang** [comment]
This logic is obviously quadratic. We don't need a repro. Just make it not quadratic.

**Comment by anijain2305** [comment]
Yeah, I can make that happen. I am asking for a repro for other parts that takes 3.5 minutes in Dynamo (which is also very high).

**Comment by dbabokin** [comment]
The repo is this one: https://github.com/google/gemma_pytorch

To enable Dynamo I'm adding `@torch.compile`  annotation to this line: https://github.com/google/gemma_pytorch/blob/acd24a81ecbb9ee3bb90771a0c517c7f6b6ce528/gemma/model.py#L455

And I'm running it with this command line:
```
> python ./scripts/run.py --ckpt=<path_to_downloaded_weights>/gemma-2b-it.ckpt --variant="2b" --prompt="Tell me a story: "
```

**Comment by anijain2305** [comment]
@dbabokin Wondering if this PR helps. And whats the new compilation time you are seeing. I dint get a chance to setup the model myself.

**Comment by dbabokin** [comment]
@anijain2305 Thank for the fix, it did help.

I was using tagged `v2.2.1` version for my experiments. Later versions (including current top of the trunk https://github.com/pytorch/pytorch/commit/6915a5be700c44381647ff132fae4d5cee36970a) do not work and crash with Dynamo on CPU with the following message:
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: RuntimeError: Tensor must have a stride divisible by 2 for all but last dimension
  target: aten.view_as_complex.default
  args[0]: TensorBox(StorageBox(
    ConcatKernel(name='buf16', layout=FixedLayout('cpu', torch.float32, size=[1, 1, 1, 128, 2], stride=(256, 1, 256, 2, 1)), inputs=[ComputedBuffer(name='buf14', layout=AliasedLayout('cpu', torch.float32, size=[1, 1, 1, 128, 1], stride=[256, 1, 256, 2, 1]), data=Pointwise(
      'cpu',
      torch.float32,
      def inner_fn(index):
          _, _, _, i3, _ = index
          tmp0 = ops.load(buf2, 2048 + i3)
          return tmp0
      ,
      ranges=[1, 1, 1, 128, 1],
      origin_node=None,
      origins={cat_2}
    )), ComputedBuffer(name='buf15', layout=AliasedLayout('cpu', torch.float32, size=[1, 1, 1, 128, 1], stride=[256, 1, 256, 2, 1]), data=Pointwise(
      'cpu',
      torch.float32,
      def inner_fn(index):
          _, _, _, i3, _ = index
          tmp0 = ops.load(buf2, 2176 + i3)
          return tmp0
      ,
      ranges=[1, 1, 1, 128, 1],
      origin_node=None,
      origins={cat_2}
    ))])
  ))
```

Notably, it's just 1 min 38 seconds till the crash for me not (way below 9 minutes that I saw earlier), I assume it's not only the fix for `new_var`, but something else as well.

**Comment by dbabokin** [comment]
@anijain2305 The error above looks like a regression to me. I don't understand the PyTorch internals well enough to pinpoint the problem. Should I create an issue for that? If you have an advice how to proceed with the investigation (other than triaging to the faulty commit), I can try investigating further.
