### ISSUE TITLE
[c10d] respect ProcessGroup(timeout) with device mesh

### ISSUE THREAD

**Issue by weifengpy** [pytorch/pytorch#121676]
### 🐛 Describe the bug

even when I set timeout or change default timeout, NCCL watchdog still timeout at 600 sec instead of custimized timeout. this makes debugging slow

### Versions

even when I set timeout or change default timeout, NCCL watchdog still timeout at 600 sec instead of custimized timeout. this makes debugging slow

**Comment by awgu** [comment]
https://github.com/pytorch/pytorch/issues/119574
https://github.com/pytorch/pytorch/issues/120847

**Comment by weifengpy** [comment]
wow. looks like it's discussed already. i might just figure out a way to patch locally for debugging purpose instead of landing something for prod

**Comment by asahni04** [comment]
any updates how to do it ?

**Comment by g-ziyan** [comment]
Having the same issue, any solutions now?
