### ISSUE TITLE
[feature request] Batched (n-1)-D to n-D matrix_diag

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#12160]
should be easy to implement with `diagonal`.

**Comment by t-vi** [comment]
I was meaning to do this a long time ago since I batchified diagonal, do you have a preference for the API?
Given the overloading of diag, we cannot just act on a 2d matrix to return a 3d item, I see two variants:
- add a `size` parameter to diag to specify the size of the target matrix
- add a new function diagonal_matrix (?).

Best regards

Thomas

**Comment by fmassa** [comment]
From the comments in https://github.com/pytorch/pytorch/issues/5198#issuecomment-425069863, it looks like TensorFlow calls it `matrix_diag`, so if we are adding a new function, it might be good to stick with a similar name.

Can we add a parameter to `diagflat` to specify which dimensions to flatten (and by default flatten all of them)? This way, the other dimensions can be considered as batch dimensions.

**Comment by chrelli** [comment]
In the meantime, TensorFlow's `matrix_diag` for a stack of vectors (batch x N) -> a stack of diagonal matrices (batch x N x N)  can be done by striding, as shown by [@SimonW here](https://discuss.pytorch.org/t/batch-of-diagonal-matrix/13560). `.as_strided` is still not documented, though: [#9886](https://github.com/pytorch/pytorch/issues/9886)

**Comment by t-vi** [comment]
I'd use diagonal instead, but yeah.

**Comment by chrelli** [comment]
Maybe I'm wrong, but doesn't diagonal return a read-only view?

**Comment by chrelli** [comment]
Sure, that would work. But something like this might save some memory, since we wouldn't have to make a huge tensor full of indices. It's an in-place, though, so maybe not totally pytorchnic:

```python
def batch_diagonal(input):
    # idea from here: https://discuss.pytorch.org/t/batch-of-diagonal-matrix/13560
    # batches a stack of vectors (batch x N) -> a stack of diagonal matrices (batch x N x N) 
    # works in  2D -> 3D, should also work in higher dimensions
    # make a zero matrix, which duplicates the last dim of input
    dims = [input.size(i) for i in torch.arange(input.dim())]
    dims.append(dims[-1])
    output = torch.zeros(dims)
    # stride across the first dimensions, add one to get the diagonal of the last dimension
    strides = [output.stride(i) for i in torch.arange(input.dim() - 1 )]
    strides.append(output.size(-1) + 1)
    # stride and copy the imput to the diagonal 
    output.as_strided(input.size(), strides ).copy_(input)
    return output    
```
