### ISSUE TITLE
onnx export GroupNorm only support input shape rank>=3, failed for input shape rank=2

### ISSUE THREAD

**Issue by luchangli03** [pytorch/pytorch#121612]
### 🐛 Describe the bug

onnx export code:
`
import torch.nn as nn
import torch.nn.init as init
import torch.onnx

class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.m = nn.GroupNorm(3, 6)

    def forward(self, x):
        x = self.m(x)
        return x

torch_model = TestNet()

x = torch.randn(20, 6, 2) # success
x = torch.randn(20, 6) # fail

output = torch_model(x)

# Export the model
torch.onnx.export(torch_model,               # model being run
                  x,                         # model input (or a tuple for multiple inputs)
                  "test_onnx.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=15,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names=['input'],   # the model's input names
                  output_names=['output'],  # the model's output names
                  )

`

error:
  File "d:\ProgramData\anaconda3\lib\site-packages\torch\onnx\symbolic_opset9.py", line 6297, in group_norm
    mul(g, norm, symbolic_helper._unsqueeze_helper(g, weight, axes)),
  File "d:\ProgramData\anaconda3\lib\site-packages\torch\onnx\symbolic_helper.py", line 849, in _unsqueeze_helper
    if _is_constant(axes_i[0]):
IndexError: list index out of range

### Versions

torch                         2.2.0+cu118

**Comment by MaanavD** [comment]
Hi @luchangli03 ,

Can you please try the `torch.onnx.dynamo_export` api to export the model instead?

**Comment by thiagocrepaldi** [comment]
Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
