### ISSUE TITLE
[c10d][nccl] job hanging with CUDA_LAUNCH_BLOCKING=1 and subgroup PG

### ISSUE THREAD

**Issue by weifengpy** [pytorch/pytorch#121788]
### 🐛 Describe the bug

``NCCL_SHM_DISABLE=1 CUDA_LAUNCH_BLOCKING=1 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=COLL torchrun --standalone --nproc_per_node=6 run_nccl_debug.py``

when tensor numel = 1064 with subgroup PG of 3 GPUs, it got stuck
when numel = 300, it is good
when subgroup is 2, 4, it's good

```
import os
import torch
import torch.distributed as dist

if __name__ == "__main__":
    dist.init_process_group(backend="nccl")
    torch.cuda.set_device(f"cuda:{int(os.environ['LOCAL_RANK'])}")
    replicate_groups = [dist.new_group([0, 2, 4]), dist.new_group([1, 3, 5])]
    output = torch.randn((1064, ), device="cuda")
    dist.all_reduce(output, group=replicate_groups[dist.get_rank() % 2])
```

### Versions

NCCL version: 2.20.5

**Comment by Aidyn-A** [comment]
Cannot reproduce the issue on V100x8 with the latest nightly. Can it be hardware specific?

**Comment by weifengpy** [comment]
thanks 

> Cannot reproduce the issue on V100x8 with the latest nightly. Can it be hardware specific?

thanks for checking. I have A100 x 8. The test is launched with 6 GPUs (partial topology). The problem seems to be me setting NCCL_SHM_DISABLE=1. It can run successfully with  NCCL_SHM_DISABLE=0

**Comment by weifengpy** [comment]
this happens on NCCL_SHM_DISABLE=1 on A100 and V100. it's good on H100. closing this for now
