### ISSUE TITLE
DISABLED test_duplicate_constant_folding_non_abi_compatible_cuda (__main__.AOTInductorTestNonABICompatibleCuda)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#121708]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_aot_inductor.py%3A%3AAOTInductorTestNonABICompatibleCuda%3A%3Atest_duplicate_constant_folding_non_abi_compatible_cuda%22%5D)).

Possibly broken by https://github.com/pytorch/pytorch/pull/121564

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by aakhundov** [comment]
Forward-fixed in https://github.com/pytorch/pytorch/pull/121750.
