### ISSUE TITLE
DISABLED test_duplicate_constant_folding_abi_compatible_cuda (__main__.AOTInductorTestABICompatibleCuda)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#121703]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_aot_inductor.py%3A%3AAOTInductorTestABICompatibleCuda%3A%3Atest_duplicate_constant_folding_abi_compatible_cuda%22%5D)).

This new test is broken on ROCm https://github.com/pytorch/pytorch/pull/121564

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @muchulee8

**Comment by aakhundov** [comment]
Forward-fixed in https://github.com/pytorch/pytorch/pull/121750.
