### ISSUE TITLE
DISABLED test_artificial_grid_cpp_wrapper (__main__.TestTritonHeuristics)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#121709]
Platforms: rocm, linux, slow

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_triton_heuristics.py%3A%3ATestTritonHeuristics%3A%3Atest_artificial_grid_cpp_wrapper%22%5D)).

Possibly broken by https://github.com/pytorch/pytorch/pull/121554

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by drisspg** [comment]
dido here @eellison

**Comment by jithunnair-amd** [comment]
Reopening because it's failing in ROCm CI on trunk
