### ISSUE TITLE
get_cudnn_version in collect_env is flaky

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#12174]
## 🐛 Bug

`get_cudnn_version` [currently only looks for `libcudnn` in `/usr/local` and `/usr/bin`](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py#L111), which sometimes fails to get the version of cudnn we have.

We should look as well in other places, maybe in `LD_LIBRARY_PATH` or `CUDNN_LIB_DIR` as well, which might give more indications of where it might be.

**Comment by Manu-shukla** [comment]
That's because LD_LIBRARY_PATH is not the only path used for lookup.

**Comment by elbaro** [comment]
In my Linux distro it's `/opt/cuda/lib64/libcudnn*` and this path is listed in `/etc/ld.so.conf.d/cudnn.conf`. `ldconfig` can find it without any environment variable.

**Comment by zou3519** [comment]
Shelling out to ldconfig sounds like a good idea

**Comment by pearu** [comment]
@fmassa PR #16859 resolved this issue and it can be closed.

**Comment by fmassa** [comment]
@pearu from a look at https://github.com/pytorch/pytorch/issues/16955, it looks like the cudnn env collection is still flaky for OSX. Could you maybe have a look at it?

**Comment by hameerabbasi** [comment]
I added a comment for what works. If you want I could open a quick PR to test.

**Comment by fmassa** [comment]
@hameerabbasi sure, please!

**Comment by pearu** [comment]
@fmassa @soumith please review PR #16968  that fixes MacOSX related issues (the lack of `ldconfig` and `nvidia-smi`)

**Comment by pearu** [comment]
@fmassa PR #16999  resolved this issue for Mac OSX as well and it can be closed.

**Comment by fmassa** [comment]
Thanks @pearu !
