### ISSUE TITLE
Typo On Torch.Sparse Page

### ISSUE THREAD

**Issue by nprisbrey** [pytorch/pytorch#121770]
### 📚 The doc issue

There is a typo on [Torch.Sparse documentation page](https://pytorch.org/docs/stable/sparse.html). The word "on" in the following snippet should be "one":

> ...to distinguish it from the Tensor instances that use some other layout, on can use...

### Suggest a potential alternative/fix

Should be: ...to distinguish it from the Tensor instances that use some other layout, **one** can use...

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip

**Comment by LamForest** [comment]
Yes, you can send a PR if you are interested
