### ISSUE TITLE
what is the match numpy verison, can not build from source 

### ISSUE THREAD

**Issue by yourmoonlight** [pytorch/pytorch#121798]
### 🐛 Describe the bug

what is the match numpy verison, can not build from source 

after run ` python3 setup.py develop` 

got this error

```
error: no member named 'elsize' in '_PyArray_Descr'
```

### Versions

OS: macOS 14.4 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.22.2
Libc version: N/A

Python version: 3.11.7 (main, Jan 16 2024, 14:42:22) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-14.4-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==2.0.0b1
[pip3] torch==2.3.0.dev20240311
[pip3] torchaudio==2.2.0.dev20240311
[pip3] torchvision==0.18.0.dev20240311
[conda] Could not collect

cc @malfet @seemethere @mruberry @rgommers

**Comment by malfet** [comment]
I don't think numpy-2.0 is out yet, but great heads up

**Comment by malfet** [comment]
Ok, I have a repro...

**Comment by rgommers** [comment]
> @rgommers do you know if new API is stable already? (Oh, I see first RC is in Feb 2024, so must be stable )

Yes, `2.0.0b1` is out and its ABI should be stable (99.9% sure); it will be officially frozen for `2.0.0rc1` in a week or so.

I'll comment on the tracking issue (gh-107302) with some more details.
