### ISSUE TITLE
AOT Inductor / Support dict[string][tensor] as the argument of the C++ AOTIModelContainerRunnerCpu::run functions (same for cuda)

### ISSUE THREAD

**Issue by bsergean** [pytorch/pytorch#121785]
### 🚀 The feature, motivation and pitch

We use this interface for our inference methods, I think it's a classic and flexible one but I'm not too versed here ...
I haven't read the python code but I wonder what it would take to support that, if it's a bad idea (beside more API surface, does it make dynamic batch size computation harder, etc...).

Apparently torch.compile does supports this, so some parts must be working.

### Alternatives

We convert our dict to vectors but this require to change models, and make it harder to adopt AOT.

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @desertfire @chenyang78

**Comment by angelayi** [comment]
Right now if you call the compiled c++ binary from the python side (through `torch._export.aot_load`) we support taking pytree inputs (like dicts) by flattening the inputs with the serialized tree spec ([code pointer](https://github.com/pytorch/pytorch/blob/8b1b61bc706154d81b04dbda9285e41a24e0505c/torch/_export/__init__.py#L394-L397)). 

To support this on the c++ side we would need to package a c++ implementation of pytree, and call it from AOTI's c++ wrapper. There exists a c++ implementation of pytree (https://github.com/metaopt/optree), which we use in [some places of pytorch](https://github.com/pytorch/pytorch/blob/8b1b61bc706154d81b04dbda9285e41a24e0505c/torch/utils/_cxx_pytree.py#L37) , but it's not within pytorch so I'm not sure if we could use it in AOTI.

cc @desertfire

**Comment by bsergean** [comment]
Thanks for the detailed explanation @angelayi.

A pytree has strong bindings to python though, doesn't it ? I was looking in [here](https://github.com/metaopt/optree/blob/main/include/treespec.h)). So it would mean we'd have to create python objects first no, while right now we can just work with pure C++ (std::vector) and C++ pytorch objects ? (and bring a python dependency in a C++ program so not great for us).

**Comment by angelayi** [comment]
Hmm yeah I guess the optree implementation might not work 😅 
Maybe there would need to be a c++ implementation of pytree that works with our serialized format so that it can work on pure c++ objects?

**Comment by bsergean** [comment]
So we figured out a way to use the list interface, this isn't really needed for us anymore.

I will close this to make the issue tracker happier.

**Comment by rdonggroq** [comment]
I think this issue should be reopened, I'd still like this feature. It would be great if there was feature parity between inductor and JIT on the C++ side.
