### ISSUE TITLE
DISABLED test_artificial_zgrid (__main__.TestTritonHeuristics)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#121732]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_triton_heuristics.py%3A%3ATestTritonHeuristics%3A%3Atest_artificial_zgrid%22%5D)).

New test failed on rocm introduced by https://github.com/pytorch/pytorch/pull/121554

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by drisspg** [comment]
cc @eellison

**Comment by eellison** [comment]
Only failing on rock. @jeffdaily  would you mind taking a look ?
