### ISSUE TITLE
Does PyTorch need to expose the header files in the aten/src/ATen/native/transformers directory to the client?

### ISSUE THREAD

**Issue by 1274085042** [pytorch/pytorch#121720]
### 🚀 The feature, motivation and pitch

Now, I am adapting at::scaled_dot_product_attention to a specific type of cuda-like device and encounters a problem.  

Firstly, since aten/src/ATen/native/transformers/sdp_utils_cpp.h is not exposed to client, I need to write a lot of repeated checking code in my select_sdp_backend
Secondly, since aten/src/ATen/native/transformers/attention.h is not exposed to client, I need to write the following code when registering _fused_sdp_choice_stub

```cpp
namespace at{
namespace native{

using fused_sdp_choice_fn = int64_t (*)(const Tensor& query_, const Tensor& key, const Tensor& value,
  const c10::optional<Tensor>& attn_mask_, double dropout_p, bool is_causal, c10::optional<double> scale);

DECLARE_DISPATCH(fused_sdp_choice_fn, _fused_sdp_choice_stub);

extern struct _fused_sdp_choice_stub _fused_sdp_choice_stub;

static RegisterPRIVATEUSE1Dispatch<struct _fused_sdp_choice_stub> 
  _fused_sdp_choice_stub__register(_fused_sdp_choice_stub,  _fused_sdp_choice);
}
}
```

The above issues arose in the context of planning to support PrivateUse1 at https://github.com/pytorch/pytorch/blob/v2.1.0/aten/src/ATen/native/transformers/attention.cpp#L674. Following the approach at https://github.com/pytorch/pytorch/issues/116922 would avoid these issues, but it requires a lot of repetitive code.   

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by bdhirsh** [comment]
From Nikita: short term, exposing headers like this seems ok. Longer term, there should be a BE project to more clearly decide what we want to expose / not expose.
