### ISSUE TITLE
`set_materialize_grads` says to only call within forward, but the examples do it in `setup_context`

### ISSUE THREAD

**Issue by ad8e** [pytorch/pytorch#121714]
### 📚 The doc issue

https://pytorch.org/docs/stable/generated/torch.autograd.function.FunctionCtx.set_materialize_grads.html
"This should be called only from inside the `forward()` method"

https://pytorch.org/docs/stable/notes/extending.html:
`ctx.set_materialize_grads(False)`

Note the first example also uses combined forward and setup_context().

### Suggest a potential alternative/fix

My guess is the second page is right and the first is wrong. I haven't checked.

cc @svekars @brycebortree @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by ad8e** [comment]
All the links under https://pytorch.org/docs/stable/autograd.html#context-method-mixins have the same warning of `should be called only from inside the forward() method".

**Comment by albanD** [comment]
Yes these doc haven't been updated when setup_context was introduced. Could you send a PR updating the doc to say "in either the setup_context() or forward() methods"
