### ISSUE TITLE
Training fails on torch.compile + device_map.

### ISSUE THREAD

**Issue by AdamLouly** [pytorch/pytorch#121873]
### 🐛 Describe the bug

I'm trying to train Mixtral MoE Model using transformers, and I'm using the device_map flag which distributes the model layers across the GPUs.

```
import torch
import transformers
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments

MODEL_ID = "mistralai/Mixtral-8x7B-v0.1"
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(MODEL_ID, device_map="auto", torch_dtype=torch.float16)

tokenizer.pad_token = "!" #Not EOS, will explain another time.\

CUTOFF_LEN = 256  #Our dataset has shot text

dataset = load_dataset("harpreetsahota/modern-to-shakesperean-translation") #Found a good small dataset for a quick test run! Thanks to the uploader!
train_data = dataset["train"] # Not using evaluation data

def generate_prompt(user_query):
    sys_msg= "Translate the given text to Shakespearean style."
    p =  "<s> [INST]" + sys_msg +"\n"+ user_query["modern"] + "[/INST]" +  user_query["shakespearean"] + "</s>"
    return p 

def tokenize(prompt):
    return tokenizer(
        prompt + tokenizer.eos_token,
        truncation=True,
        max_length=CUTOFF_LEN ,
        padding="max_length"
    )

train_data = train_data.shuffle().map(lambda x: tokenize(generate_prompt(x)), remove_columns=["modern" , "shakespearean"])
opt_model = torch.compile(model)
trainer = Trainer(
    model=opt_model,
    train_dataset=train_data,
    args=TrainingArguments(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=1,
        num_train_epochs=100,
        learning_rate=1e-4,
        logging_steps=1,
        optim="adamw_torch",
        save_strategy="epoch",
        output_dir="mixtral-moe-lora-instruct-shapeskeare",
        remove_unused_columns=False
    ),
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False)
)
model.config.use_cache = False

trainer.train()

```

I get this error:

`  File "/home/aiscuser/transformers/src/transformers/models/mixtral/modeling_mixtral.py", line 1171, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/nn/functional.py", line 2264, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper_CUDA__index_select)`

### Versions

nightly pyotch
nightly transformers

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by janeyx99** [comment]
This looks like more of a problem in transformers. I would expect the library to dispatch different calls per device in that scheme--thus, you may want to open an issue in transformers instead.

**Comment by AdamLouly** [comment]
question, does torch inductor support pipeline parallel?

**Comment by anijain2305** [comment]
No, `torch.compile` have limited support with distributed training. We are working on making it better. We don't support pipeline parallelism today OOTB.
