### ISSUE TITLE
[inductor][cpu]lennard_jones, pyhpc_equation_of_state and pyhpc_isoneutral_mixing performance regression 

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#121882]
### 🐛 Describe the bug

<p>fp32 static shape default wrapper regression in 2024-03-10</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>lennard_jones</td>
      <td>single</td>
      <td>1</td>
      <td>1.442252</td>
      <td>4.8045e-05</td>
      <td>6.929299734e-05</td>
      <td>5.983722</td>
      <td>1.0</td>
      <td>1.833953</td>
      <td>3.8604e-05</td>
      <td>7.079792161199999e-05</td>
      <td>4.163693</td>
      <td>0.79</td>
      <td>1.02</td>
      <td>0.8</td>
      <td>0.7</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>pyhpc_equation_of_state</td>
      <td>single</td>
      <td>1</td>
      <td>18.71236</td>
      <td>5.3968e-05</td>
      <td>0.00100986864448</td>
      <td>8.857691</td>
      <td>1.0</td>
      <td>23.188102</td>
      <td>4.51e-05</td>
      <td>0.0010457834002</td>
      <td>6.913662</td>
      <td>0.81</td>
      <td>1.04</td>
      <td>0.84</td>
      <td>0.78</td>
    </tr>
  </tbody>

</table>
<p>fp32 dynamic shape default wrapper regression in 2024-03-10</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>lennard_jones</td>
      <td>single</td>
      <td>1</td>
      <td>1.431658</td>
      <td>4.8693e-05</td>
      <td>6.9711722994e-05</td>
      <td>6.040358</td>
      <td>1.0</td>
      <td>1.775623</td>
      <td>3.9242e-05</td>
      <td>6.9678997766e-05</td>
      <td>4.229882</td>
      <td>0.81</td>
      <td>1.0</td>
      <td>0.81</td>
      <td>0.7</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>pyhpc_equation_of_state</td>
      <td>single</td>
      <td>1</td>
      <td>18.8031</td>
      <td>5.4025e-05</td>
      <td>0.0010158374775</td>
      <td>8.885931</td>
      <td>1.0</td>
      <td>23.240634</td>
      <td>4.4543e-05</td>
      <td>0.001035207560262</td>
      <td>6.99299</td>
      <td>0.81</td>
      <td>1.02</td>
      <td>0.82</td>
      <td>0.79</td>
    </tr>
  </tbody>

</table>
<p>fp32 static shape cpp wrapper regression in 2024-03-10</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>lennard_jones</td>
      <td>single</td>
      <td>1</td>
      <td>1.810503</td>
      <td>3.8294e-05</td>
      <td>6.9331401882e-05</td>
      <td>14.183242</td>
      <td>1.0</td>
      <td>2.379847</td>
      <td>2.8666e-05</td>
      <td>6.822069410199999e-05</td>
      <td>12.376875</td>
      <td>0.76</td>
      <td>0.98</td>
      <td>0.75</td>
      <td>0.87</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>pyhpc_equation_of_state</td>
      <td>single</td>
      <td>1</td>
      <td>23.197532</td>
      <td>4.4514e-05</td>
      <td>0.001032614939448</td>
      <td>17.09731</td>
      <td>1.0</td>
      <td>29.022945</td>
      <td>3.5698e-05</td>
      <td>0.00103606109061</td>
      <td>15.172577</td>
      <td>0.8</td>
      <td>1.0</td>
      <td>0.8</td>
      <td>0.89</td>
    </tr>
  </tbody>

</table>
<p>fp32 dynamic shape cpp wrapper regression in 2024-03-10</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>lennard_jones</td>
      <td>single</td>
      <td>1</td>
      <td>1.76331</td>
      <td>3.8149000000000004e-05</td>
      <td>6.726851319e-05</td>
      <td>14.189571</td>
      <td>1.0</td>
      <td>2.273742</td>
      <td>2.8757000000000003e-05</td>
      <td>6.5385998694e-05</td>
      <td>12.387977</td>
      <td>0.78</td>
      <td>0.97</td>
      <td>0.75</td>
      <td>0.87</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>pyhpc_equation_of_state</td>
      <td>single</td>
      <td>1</td>
      <td>22.763</td>
      <td>4.464e-05</td>
      <td>0.00101614032</td>
      <td>17.139039</td>
      <td>1.0</td>
      <td>31.649198</td>
      <td>3.4811e-05</td>
      <td>0.001101740231578</td>
      <td>15.198502</td>
      <td>0.72</td>
      <td>1.08</td>
      <td>0.78</td>
      <td>0.89</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>pyhpc_isoneutral_mixing</td>
      <td>single</td>
      <td>1</td>
      <td>47.525991</td>
      <td>5.6787e-05</td>
      <td>0.0026988584509169996</td>
      <td>20.419413</td>
      <td>1.0</td>
      <td>54.58171</td>
      <td>4.9508e-05</td>
      <td>0.0027022312986800003</td>
      <td>18.502454</td>
      <td>0.87</td>
      <td>1.0</td>
      <td>0.87</td>
      <td>0.91</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>1ef0a39e</td>
      <td>main</td>
      <td>ff42d907</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>41286f1505ffb214d386d72e4b72ebd680a4a475</td>
      <td>main</td>
      <td>581fe26792849a80f04feaa7f8bdec69b7f41dd8</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.18.0a0+2c127da</td>
      <td>main</td>
      <td>0.18.0a0+2c127da</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.2.0a0+87aeb55</td>
      <td>main</td>
      <td>2.2.0a0+87aeb55</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh **thread** inference performance torchbench **model** float32/amp first static/dynamic default/cpp
[torchbench-lennard_jones-inference-float32-static-default-single-performance-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/14595771/torchbench-lennard_jones-inference-float32-static-default-single-performance-drop_guilty_commit.log)
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/a7e93c341fe0f51c2affca106053f4bc452fbfd2
cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @WeizhuoZhang-intel @chuanqi129

**Comment by leslie-fang-intel** [comment]
May we take a look first between the difference of generated code before and after the regression @zhuhaozhe?

**Comment by zhuhaozhe** [comment]
Hi, @angelayi.
We observed some regressions after this PR https://github.com/pytorch/pytorch/pull/120296.
I have compared the generated code for `lennard_jones` but I did not find any difference.

Then I collected the chrome trace and compared them.
The `chrome_trace` indicate this model is pretty small (20us level for 1 iter) and most event under `Torch-compiled Region` are not captured.
![image](https://github.com/pytorch/pytorch/assets/54701539/f1b7c760-09b5-481f-9f1f-f205b53a13ba)

However, there is ~4us regression after this PR.
Before:
![image](https://github.com/pytorch/pytorch/assets/54701539/1e636b4d-6462-4e28-991e-ab69d7c4dc67)
After:
![image](https://github.com/pytorch/pytorch/assets/54701539/2508c757-c2c8-4337-80a4-70232c565f67)

I tried to locate the ~4us overhead and the last point I have found (with 4us regression) is https://github.com/pytorch/pytorch/blob/1f4d4d3b7836d38d936a21665e6b2ab0b39d7092/torch/csrc/dynamo/eval_frame.c#L182-L198.

I cannot see how your PR will impact here.
Do you have any insights on it? ~4 us overhead per iter while running an inductor optimized model.

**Comment by angelayi** [comment]
Hi @zhuhaozhe, sorry for the regression! I'm not exactly sure what could've caused the regression, but one thing I could see in my PR that might be impactful is that I inserted an additional check on this [line](https://github.com/pytorch/pytorch/blob/main/torch/_subclasses/functional_tensor.py#L358), which gets run on every node in the torch compiled graph. Maybe you could try commenting out this check and see if that restores the 4us? 

Or maybe detecting the functional tensor mode [here](https://github.com/pytorch/pytorch/blob/main/torch/_functorch/_aot_autograd/traced_function_transforms.py#L375-L377) is costly? Maybe you can try removing that line, and then replacing [this line](https://github.com/pytorch/pytorch/blob/main/torch/_functorch/_aot_autograd/traced_function_transforms.py#L368) with `with disable_above, FunctionalTensorMode(aot_config.pre_dispatch):`?

cc @bdhirsh if you have any ideas 😅

**Comment by zhuhaozhe** [comment]
Hi, @angelayi.
I may located the 4us overhead here:
```
--- a/torch/_functorch/_aot_autograd/runtime_wrappers.py
+++ b/torch/_functorch/_aot_autograd/runtime_wrappers.py
@@ -76,7 +76,7 @@ def create_runtime_wrapper(
 
     def runtime_wrapper(*args):
         # Pass in effect tokens (See Note [Side-Effectful Tokens in AOTAutograd])
-        args = (*[torch.tensor([])] * num_tokens, *args)
+        # args = (*[torch.tensor([])] * num_tokens, *args)
 
         if trace_joint:
             args_ = list(args)
```
Coming from `torch.tensor([])`?

After comment out: (abs latency=0.027103ms)
```
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,lennard_jones,1,1.941443,0.027103,2.771598,0.876977,40.813773,46.539162,9,1,0,0,0,0
```
Before comment out  (abs latency=0.032131ms):
```
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,lennard_jones,1,1.661396,0.032131,2.792909,0.876954,40.808038,46.533837,9,1,0,0,0,0
```

**Comment by zhuhaozhe** [comment]
I tried
```
--- a/torch/_functorch/_aot_autograd/runtime_wrappers.py
+++ b/torch/_functorch/_aot_autograd/runtime_wrappers.py
@@ -76,7 +76,8 @@ def create_runtime_wrapper(
 
     def runtime_wrapper(*args):
         # Pass in effect tokens (See Note [Side-Effectful Tokens in AOTAutograd])
-        args = (*[torch.tensor([])] * num_tokens, *args)
+        if num_tokens > 0:
+            args = (*[torch.tensor([])] * num_tokens, *args)
```
And the regression is gone.

**Comment by angelayi** [comment]
Oh interesting! thanks so much for the investigation! Feel free to send a PR :D

**Comment by zhuhaozhe** [comment]
Thanks @angelayi, this issue will be fixed by https://github.com/pytorch/pytorch/pull/122346.

**Comment by jansel** [comment]
Closing this issue as #122346 is landed.  Please reopen if not fixed.
