### ISSUE TITLE
int array declaration error

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#121814]
Repro:
Comment out https://github.com/pytorch/pytorch/blob/5498804ec2ac9aa62ba3bbf20149118142567d9b/test/inductor/test_cuda_cpp_wrapper.py#L99
, and then run
```
TORCHINDUCTOR_ABI_COMPATIBLE=1 python test/inductor/test_cuda_cpp_wrapper.py -k test_conv_backward_cuda
```

Error:
```
/tmp/torchinductor_binbao/pj/cpjolkt7x2jqlatroglzlmf3upjbogcui77evozsj5u64hvnelks.cpp: In function ‘void inductor_entry_impl(AtenTensorOpaque**, AtenTensorOpaque**)’:
/tmp/torchinductor_binbao/pj/cpjolkt7x2jqlatroglzlmf3upjbogcui77evozsj5u64hvnelks.cpp:52:31: error: expected unqualified-id before numeric constant
   52 |     auto var_0 = int_array_0, 1;
      |                               ^
```

**Comment by int3** [comment]
There are at least two issues here causing `test_conv_backward_cuda` to fail: the first one (as described above) is broken syntax emitted when we encounter an optional-of-list type. I more or less have a fix for that locally.

But there's a second issue: the `bool[3] output_mask` argument to `convolution_backward` gets converted to `int32_t**` by torchgen, but the wrapper code we are generating creates the input argument as a `int64_t**`. It looks like our wrapper codegen only expects int64_t arrays, which is clearly not true in general...

**Comment by int3** [comment]
so I think I have a fix for #2, but I'm currently stuck on trying to convert JitTypes to dtypes -- e.g. `torch.IntType.get().dtype()` gives me an assertion error. I'm trying to do this because there are already utilities for converting dtypes to C types, but not so much for JitTypes to C types directly

**Comment by int3** [comment]
torchgen itself has a mapping from JitTypes to C types, and I could hoist that mapping out into some util file I suppose, but I feel like there should be an easier way (since the cpp wrapper already contains the mappings from dtypes to C types)

**Comment by desertfire** [comment]
Are you talking about finding the correct int type here, https://github.com/pytorch/pytorch/blob/535a84c12553a6a423bb3f7f7b175ee7bf8d5464/torch/_inductor/codegen/cpp_wrapper_cpu.py#L2117 ? I think you can read that from ExternKernel.arg_properties.

**Comment by desertfire** [comment]
> > Are you talking about finding the correct int type here,
> 
> Yep!
> 
> > I think you can read that from ExternKernel.arg_properties.
> 
> Yeah `val_to_arg_str` is being called by `val_to_cpp_arg_str`, which is passed the type of the parameter from `codegen_args`, which in turn extracts it from `ExternKernel.arg_properties`. The problem here is that `arg_properties[i].get("type")` is a JitType, not a dtype.

`self.arg_properties[-1]['type'].getElementType()` gives me `bool`, which should be enough here?

**Comment by int3** [comment]
I think you're probably getting a `BoolType` and which gets stringified into "bool"...

**Comment by desertfire** [comment]
Fixed with https://github.com/pytorch/pytorch/pull/125730. A nicer way to fix is to pass arg type info into val_to_arg_str, and  https://github.com/pytorch/pytorch/issues/122048 will require doing that. I will improve the fix when working on that.
