### ISSUE TITLE
Downloading torch 2.2.1 is very slow.

### ISSUE THREAD

**Issue by yikaiMeta** [pytorch/pytorch#121841]
### 🐛 Describe the bug

I am using 'pip install' to download torch 2.2.1 to AWS EC2.
But the downloading speed is too slow. It is around 700 bytes/s, which will take 10 days to finish.
<img width="841" alt="Screenshot 2024-03-13 at 3 55 13 PM" src="https://github.com/pytorch/pytorch/assets/116014337/6ea97e19-885d-4662-b117-1a4ce839998d">

I just downloaded other libraries like usort, black. They are all fast. 

### Versions

NA

**Comment by malfet** [comment]
Can you tell a bit more about AWS EC2 instance? As I use it all the time (in `us-east-1` region) and never seen this one before

**Comment by yikaiMeta** [comment]
Hi @malfet , the instance type is t3a.micro, the region is us-west-2.  
Is it because of the instance type is 'micro'?

**Comment by yikaiMeta** [comment]
This issue is because of limitation of t3a.micro instance type. After I changed the instance type to a bigger one, the issue is resolved.
