### ISSUE TITLE
support Generator type (bernoulli_) in C shim

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#121809]
Repro:
Comment out https://github.com/pytorch/pytorch/blob/559ca13b3f3014dc36b83353effcb95a57123e96/test/inductor/test_cuda_cpp_wrapper.py#L98
, and then run
```
TORCHINDUCTOR_ABI_COMPATIBLE=1 python test/inductor/test_cuda_cpp_wrapper.py -k test_bernoulli1_cuda
```

Error:
```
Output:
/tmp/torchinductor_binbao/zc/czczm6ujwmiyiepoltgolcvsbm67smsrn6nmteusx5j6zur2lcdk.cpp: In function ‘void inductor_entry_impl(AtenTensorOpaque**, AtenTensorOpaque**)’:
/tmp/torchinductor_binbao/zc/czczm6ujwmiyiepoltgolcvsbm67smsrn6nmteusx5j6zur2lcdk.cpp:114:5: error: ‘aoti_torch_bernoulli_’ was not declared in this scope; did you mean ‘aoti_torch_bmm_out’?
  114 |     aoti_torch_bernoulli_(buf1, 0.5);
```

There are two problems here:
1. The fallback function naming needs to be fixed. In this case, it should look for `aoti_torch_cuda_bernoulli_`.
2. gen_aoti_c_shim.py currently does not generate `aoti_torch_cuda_bernoulli_` because `Generator` type is not supported yet (https://github.com/pytorch/pytorch/blob/559ca13b3f3014dc36b83353effcb95a57123e96/torchgen/gen_aoti_c_shim.py#L97), so even if 1 is fixed, the symbol will be missing.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @chenyang78

**Comment by kflu** [comment]
Thanks for the detailed description Bin! I'll have a try at this :)  @desertfire
