### ISSUE TITLE
[Cudagraph Tree] Add Support for Mutated Inputs which come from a prior cudagraph pool

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#121861]
### 🚀 The feature, motivation and pitch

In Cudagraph Trees there are three types of inputs:
1) inputs from eager. These tensors we assume will vary data_ptrs from execution to execution. Because cudagraphs freeze memory addresses, we need to [copy these inputs](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cudagraph_trees.py#L953-L956) over to a static address tensor prior to graph recording and execution
2) Parameters and buffers. These tensors we assume (and runtime-check) have the same data_ptr on every execution. We do not need to copy over their contents because the recorded memory address will be the same as the executed memory address.
3) Tensors which are [prior outputs from the cudagraph trees](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cudagraph_trees.py#L779-L784). Because the output data ptrs of a cudagraph are fixed, if we run cuda graph 1, then run cuda graph 2, the inputs which came from cuda graph 1 into 2 will have a fixed memory address. These inputs, like parameters and buffers, do not require copying over to a static address tensor. We check to make sure that these [inputs are stable at runtime](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cudagraph_trees.py#L1515-L1518), and if they're not will re-record.

If a mutation were to occur in the cuda graph on an an input from eager, the mutation would be seen in the cuda memory of the static address tensor, which is internal to cudagraphs. It would not be seen on the input from eager. Because of this, we skip cudagraph-ing when there is an input to a mutation on an eager tensor. (We could potentially replay the mutation afterwards, but that's out of scope for this issue). Mutations on parameters and buffers are fine because there is no static address tensor - the mutation in execution of cuda graph replay is seen on the parameters and buffers themselves.

This is where this issue comes in. We should avoid skipping for mutation that is on a tensor which is a prior input from cudagraph trees. There are a few complications - 
- we'll need to defer this checking until runtime, when the data_ptrs of the inputs are available. 
- if the pattern of these inputs changes such that one of the inputs is no longer an input from cudagraph trees and is mutated, we'll need to execute it without cudagraphs. 

cc @peterbell10, @shunting314

**Comment by eellison** [comment]
import torch

@torch.compile(mode="reduce-overhead")
def foo(x):
    return x + 1

@torch.compile(mode="reduce-overhead")
def mut(x):
    return x.add_(2)

for i in range(3):
    torch.compiler.cudagraph_mark_step_begin()
    inp = torch.rand([4], device="cuda")

    tmp = foo(inp)
    if i != 0:
        print(tmp.data_ptr())
    mut(tmp)

**Comment by shunting314** [comment]
For the 3rd item in the summary 
```
Tensors which are [prior inputs from the cudagraph trees](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cudagraph_trees.py#L779-L784).
```
do you mean 'Tensors which are prior **outputs** from the cudagraph trees?

**Comment by eellison** [comment]
Yes, I do, corrected!
