### ISSUE TITLE
[inductor][cpu] llava accuracy and performance crash

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#121888]
### 🐛 Describe the bug

loading model: 0it [00:00, ?it/s]
loading model: 0it [00:00, ?it/s]
cpu  eval  llava                              
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 3836, in run
    ) = runner.load_model(
  File "benchmarks/dynamo/torchbench.py", line 255, in load_model
    benchmark = benchmark_cls(
  File "/workspace/benchmark/torchbenchmark/util/model.py", line 24, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/workspace/benchmark/torchbenchmark/models/llava/__init__.py", line 11, in __init__
    super().__init__(name="llava", test=test, device=device, batch_size=batch_size, extra_args=extra_args)
  File "/workspace/benchmark/torchbenchmark/util/framework/huggingface/model_factory.py", line 98, in __init__
    config = eval(class_models[name][2])
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 957, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 671, in __getitem__
    raise KeyError(key)
KeyError: 'llava'

eager_fail_to_run

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>1ef0a39e</td>
      <td>main</td>
      <td>ff42d907</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>f11f2b0d55b1aa322f73f4bb521beaf9d4563603</td>
      <td>main</td>
      <td>581fe26792849a80f04feaa7f8bdec69b7f41dd8</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.18.0a0+2c127da</td>
      <td>main</td>
      <td>0.18.0a0+2c127da</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.2.0a0+87aeb55</td>
      <td>main</td>
      <td>2.2.0a0+87aeb55</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single inference performance/accuracy torchbench llava float32 first static
cc @WeizhuoZhang-intel @chuanqi129

**Comment by chuanqi129** [comment]
@zxd1997066 it looks like a transformer version incompatible issue, let's try to use the pined transformers version in  https://github.com/pytorch/pytorch/blob/main/.ci/docker/ci_commit_pins/huggingface.txt again

**Comment by zxd1997066** [comment]
The issue is fixed with pined transformers
