### ISSUE TITLE
torch.nn.functional.prelu output incorrect result with when weights have infinity value

### ISSUE THREAD

**Issue by maybeLee** [pytorch/pytorch#121948]
### 🐛 Describe the bug

Here is the code to show the problem:
```
import torch
input = torch.tensor(1.234)
weight = torch.tensor(np.inf)
print(input, weight)  # tensor(1.2340) tensor(inf)
out = torch.nn.functional.prelu(input,weight)
print(out)  # tensor(1.2340)
```

Based on prelu's equation (https://pytorch.org/docs/stable/generated/torch.nn.functional.prelu.html): PReLU(x)=max(0,x)+weight∗min(0,x)

The computation is: max(0, 1.234) + inf*min(0, 1.234)=1.234+inf*0, where inf*0 is indeterminant (https://mathworld.wolfram.com/Indeterminate.html).
Therefore, outputting NaN may be more appropriate indicating an indeterminant status occur.

I think the issue occurs because this code will stop calculating `weight * input` if input is larger than 0:
https://github.com/pytorch/pytorch/blob/3bc2bb678150e02bfa2552b82572d771a892d0c3/aten/src/ATen/native/cpu/Activation.cpp#L1380

Maybe it can be fixed by also running the weight*input code even when the input is larger than 0?

### Versions

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] torch==2.2.1
[pip3] triton==2.2.0
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] torch                     2.2.1                    pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by redwrasse** [comment]
I don't think this is a bug? For x > 0, prelu(x, w) = x, which appears to be the output.

**Comment by maybeLee** [comment]
Hi @redwrasse , thanks for your explanation.
I found out that the documentation also mentions prelu(x,w)=x for x >= 0. 
Therefore, I also think outputting x is an expected behavior now.
