### ISSUE TITLE
Slowdown in distributions log_prob methods

### ISSUE THREAD

**Issue by neerajprad** [pytorch/pytorch#12190]
## 🐛 Bug

One of Pyro's branches (https://github.com/uber/pyro/pull/1431) is running against PyTorch's nightly build, and we noticed that the unit test stage in CI is almost twice as slow as compared to the 0.4.0 release. Many of the slow tests turn out to be HMC tests (https://github.com/uber/pyro/issues/1421), and the slowdown seems to mostly be in the distribution's `log_prob` methods. Pasting the results below for the normal distribution, but I am seeing this for other distributions too.

## To Reproduce

**version: 0.4.0**
```python
>>> import torch
>>> import torch.distributions as dist
>>> torch.__version__
 '0.4.0'
>>> d = dist.Normal(torch.zeros(1000, 2), torch.ones(1000, 2))

>>> %timeit torch.randn(1000, 2)
16.2 µs ± 342 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

>>> %timeit [d.log_prob(torch.randn(1000, 2)) for _ in range(1000)]
45.8 ms ± 1.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

>>> %lprun -f d.log_prob [d.log_prob(torch.randn(1000, 2)) for _ in range(10000)]
Timer unit: 1e-06 s

Total time: 0.476309 s
File: /Users/npradhan/miniconda2/envs/pytorch-36/lib/python3.6/site-packages/torch/distributions/normal.py
Function: log_prob at line 62

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    62                                               def log_prob(self, value):
    63     10000       5511.0      0.6      1.2          if self._validate_args:
    64                                                       self._validate_sample(value)
    65                                                   # compute the variance
    66     10000      23427.0      2.3      4.9          var = (self.scale ** 2)
    67     10000     180867.0     18.1     38.0          log_scale = math.log(self.scale) if isinstance(self.scale, Number) else self.scale.log()
    68     10000     266504.0     26.7     56.0          return -((value - self.loc) ** 2) / (2 * var) - log_scale - math.log(math.sqrt(2 * math.pi))
```

**master (1.0.0a0+ab9a597)**
```python
>>> import torch
>>> import torch.distributions as dist
>>> torch.__version__
 '1.0.0a0+ab9a597'

>>> d = dist.Normal(torch.zeros(1000, 2), torch.ones(1000, 2))

>>> %timeit torch.randn(1000, 2)
17.8 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

>>> %timeit [d.log_prob(torch.randn(1000, 2)) for _ in range(1000)]
72.1 ms ± 1.78 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

>>> %lprun -f d.log_prob [d.log_prob(torch.randn(1000, 2)) for _ in range(10000)]
Timer unit: 1e-06 s

Total time: 0.782675 s
File: /Users/npradhan/miniconda2/envs/pytorch-master/lib/python3.6/site-packages/torch/distributions/normal.py
Function: log_prob at line 70

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    70                                               def log_prob(self, value):
    71     10000       8708.0      0.9      1.1          if self._validate_args:
    72                                                       self._validate_sample(value)
    73                                                   # compute the variance
    74     10000      46140.0      4.6      5.9          var = (self.scale ** 2)
    75     10000     135462.0     13.5     17.3          log_scale = math.log(self.scale) if isinstance(self.scale, Number) else self.scale.log()
    76     10000     592365.0     59.2     75.7          return -((value - self.loc) ** 2) / (2 * var) - log_scale - math.log(math.sqrt(2 * math.pi))
```

Note that the `log_prob` method hasn't changed, but the last line takes almost twice as long. The only thing I can think of is that the `broadcast_all` method in the constructor is now different, and the expanded instances are somehow slower. I am still investigating this.

## Environment

```
  $ python collect_env.py
Collecting environment information...
PyTorch version: 1.0.0a0+ab9a597
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.3
GCC version: Could not collect
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.15.0)
[pip] torch (1.0.0a0+ab9a597, /Users/npradhan/miniconda2/envs/pytorch-master/lib/python3.6/site-packages)
[pip] torchfile (0.1.0)
[pip] torchvision (0.2.1)
[conda] torch                     1.0.0a0+ab9a597           <pip>
[conda] torch                     0.5.0a0+2431eac           <pip>
[conda] torch                     1.0.0a0+6ff568d           <pip>
[conda] torch                     0.5.0a0+6660a12           <pip>
[conda] torch                     0.5.0a0+35d52db           <pip>
[conda] torch                     0.5.0a0+6c3792b           <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                     <pip>
```

## Additional context

I also noticed that certain functions like `torch.randn` in the nightly build are almost 2X slower than compiling the source code on my system locally. That's the reason why I am benchmarking against the local build and not the pytorch nightly build.

**Comment by neerajprad** [comment]
cc. @fritzo, @zou3519, @SsnL

**Comment by SsnL** [comment]
cc @pjh5 on nightly perf

**Comment by neerajprad** [comment]
@SsnL : Oddly, it seems that the slowdown is simply in the exponentiation operation. You can see this above too in the line profiler output `self.scale ** 2` or simply `torch.ones(1000, 2) ** 2` has slowed down by a factor of 2. It also seems that the performance degrades only for certain shapes (e.g. `torch.ones(1000, 100) ** 2` has roughly the same perf), from what I can see.

**Comment by apaszke** [comment]
cc: @cpuhrsch @colesbury (CPU kernels might be at fault here)

**Comment by neerajprad** [comment]
Are there any updates to this? Also, will this be fixed in the 1.0 release? Currently, this is a blocker for us to move to using PyTorch master (a pinned nightly build) for our CI.

**Comment by zou3519** [comment]
I'm bumping the priority on this. @neerajprad we'll take a look and get back to you.

**Comment by ailzhang** [comment]
I can confirm seeing a similar result on master & 0.4.0. And `torch.ones(1000, 2) ** 2` does look suspicious to me. Investigating...

**Comment by ahmadsalim** [comment]
I was profiling some of my own code in Pyro to detect a performance issue, and for a small example program I made to narrow things down it seems that `log_prob` is taking on average around twice as long on 1.0 compared to 0.4. This is a considerable slow down for me, since the `log_prob` method is one of the ones that is used the most during inference of my model.

Please, see the following gist for the small example: https://gist.github.com/ahmadsalim/5e98a01b5c2d77142e248ebf0fa36291 .

I have included the images showing the call time.

For 0.4.0:
![skaermbillede 2018-11-03 kl 18 37 14](https://user-images.githubusercontent.com/1647846/48000246-e7b5b780-e0d2-11e8-9f23-11163e09938a.png)

For 1.0:
![skaermbillede 2018-11-03 kl 19 01 44](https://user-images.githubusercontent.com/1647846/48000249-ea181180-e0d2-11e8-971a-bfbb966a427a.png)

**Comment by ailzhang** [comment]
Yes some of my benchmarks showed that the main slowdown in `log_prob`was in `pow` but that slowdown doesn't scale with input shapes, which might be related to some tensor overhead we added after 0.4. 
Sorry didn't have time to get back to this last week, will do this week.

**Comment by neerajprad** [comment]
@alizhang - `torch.gather` seems to be taking thrice as long. Is that related to https://github.com/pytorch/pytorch/issues/11647?

**Comment by ailzhang** [comment]
As @cpuhrsch suggested, #9320 might fix it. 
We will do some benchmark and verify. 
Hopefully this can get into the 1.0 release.

**Comment by neerajprad** [comment]
Sounds great! Looking forward to see this merge, I can help with benchmarking.

**Comment by neerajprad** [comment]
Also is https://github.com/pytorch/pytorch/pull/13420 likely to make it into 1.0?

**Comment by ailzhang** [comment]
@neerajprad  Yea if you could help check if #9320 fixes your issue, it would be super helpful. 
And yes I think 13420 is likely to be included in 1.0 as well.

**Comment by soumith** [comment]
the PR has landed on master. Can you check now if this fixes things

**Comment by neerajprad** [comment]
@soumith, @ailzhang: That's great! I built the wheels locally on OSX before and after #13420 was merged. The master before was only a bit slower which #13420 seems to have mostly fixed. I repeated the profiling that I did above and it confirmed that the two benchmarks are now much closer, which is great. Note that this is even without #9320.

That said, we are using the linux nightly wheels for our CI (pinned to Nov 27) which still appears 2-3 times slower on many tests, particularly the HMC tests. I am still trying to understand why that is the case. I will update to the Nov 28 build and see if these perf fixes address the slowdown in CI.

**Comment by soumith** [comment]
@neerajprad the fix was landed late last evening, so you might need Nov 28th builds.

**Comment by neerajprad** [comment]
I am closing this issue as the benchmark comparison between master and `0.4.0` has moved much closer since I created it, and we are seeing comparable performance in our test suite using the latest nightly build. If we observe any other perf regression, I will create more specific issues.
