### ISSUE TITLE
_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN3MPI8Datatype4FreeEv libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by beimingmaster** [pytorch/pytorch#12197]
import torch in python3.5 report error:

~/.virtualenvs/dl4cv/lib/python3.5/site-packages/torch/__init__.py in <module>()
     51 sys.setdlopenflags(_dl_flags.RTLD_GLOBAL | _dl_flags.RTLD_NOW)
     52 
---> 53 from torch._C import *
     54 
     55 __all__ += [name for name in dir(_C)

ImportError: /home/master/.virtualenvs/dl4cv/lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN3MPI8Datatype4FreeEv
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)

i see similar error have work round for conda installing, but no solution for source installing.

tks.

Environments:
 - PyTorch Version: 0.20
 - OS: Ubuntu 16.04.3 LTS
 - install from source
 - install command: python setup.py install
 - Python version: 3.5.2
 - CUDA/cuDNN version: 8.0.61
 - GPU models and configuration: 6.0.21

**Comment by beimingmaster** [comment]
> Did you install pytorch 0.2 from source? Could you try a newer version (i.e. 0.3?)

i install pytorch2.0 successful by downloading WHL file。
another project depends pytorch 0.2

**Comment by gchanan** [comment]
closing because this is for an old version.
