### ISSUE TITLE
scatter_reduce method do not support complex number multiplication on CUDA

### ISSUE THREAD

**Issue by Franklalalala** [pytorch/pytorch#121965]
### 🐛 Describe the bug

```python
import torch


device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device("cpu")


# Complex tensors
src = torch.tensor([1 + 2j, 3 - 4j, 1 + 1j], dtype=torch.cfloat, device=device)
indices = torch.tensor([0, 0, 0], device=device)

# src = torch.tensor([1 + 2j, 3 - 4j, 1 + 1j], dtype=torch.complex64)
# indices = torch.tensor([0, 0, 0])


output = src.scatter_reduce(dim=0, index=indices, src=src, reduce='prod', include_self=False)
print(output)
```

Error message:
```
Traceback (most recent call last):
  File "F:\new_develop\spatea\test\torch_scatter_complex\test.py", line 15, in <module>
    output = src.scatter_reduce(dim=0, index=indices, src=src, reduce='prod', include_self=False)
RuntimeError: "cuda_scatter_gather_base_kernel_func" not implemented for 'ComplexFloat'
```

However, this issue will not happen for CPU device. This seems related to issue [74770](https://github.com/pytorch/pytorch/issues/74770), and [test_code](https://github.com/pytorch/pytorch/blob/4cbf963894e78d1cfedffe4f829740dc99163caa/test/test_scatter_gather_ops.py#L182)

### Versions

2.0.0+cu117

cc @ptrblck @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @amjames

**Comment by ZelboK** [comment]
@janeyx99 Hi, do you mind if I take a shot at this? Seems like fun.

**Comment by janeyx99** [comment]
feel free to open a PR if you have a solution in mind!

**Comment by ZelboK** [comment]
> feel free to open a PR if you have a solution in mind!

Sorry to bug here - I'd like to work on more stuff. Could you point me towards an issue that is not being worked on and I can do on my machine? :) Mostly interested in the CUDA module but I don't mind others as well.

**Comment by janeyx99** [comment]
@ZelboK Aha :D Don't hesitate to go through the issues with label "actionable": https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aactionable

**Comment by Franklalalala** [comment]
Good job!
