### ISSUE TITLE
[DeviceMesh] get_group() docs and behavior inconsistent for mesh_dim=None

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#121984]
docs claim `mesh_dim=None` should result in returning a list of all PGs. (this is actually a convenient behavior and what I was hoping to use in this case).  
**Update:** re-read and realized the docs accurately describe what happens, which is that there is a special case for 1-D mesh.  I'd still like to discuss this as it's convenient to have a method to get a list of all the groups, even if there is only one group.

get_group() is returning a single PG rather than a list.  In this case I was running torchtrain with only DP enabled, so a 1-D mesh.  That may be a special case, but i think it should still return a list with just the DP group in it.  That way i can write something like 

```
for group in world_mesh.get_group():
   ...
```

Note: the API name is also a bit off, its weird to have an API named 'get_group' that sometimes gets 'groups'.  I'm not sure if its worth changing the behavior and adding a separate API for groups, and making get_group require mesh_dim, or just living with the awkward naming.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @yf225 @chauhang @d4l3k @rohan-varma

**Comment by wz337** [comment]
Thanks for the feedback. @wconstab 

I guess I am ok with having 1D mesh also return a list with just one element (the DP group) in it, so the return type is consistent. This might make more sense. 

As for why there is only an API, iirc, Wanchao and I have discussed about this, and our intention might be to keep fewer public APIs in DeviceMesh so we decided to not have `get_group` and `get_groups` separately. 

If this is confusing, a couple of solutions that I can think of right now is:
1. Make it into two APIs `get_group` and `get_groups`
2. Or have a new single API to return a dictionary of key being mesh_dim_name and value being the pg. So it's a bit more flexible. You can either do .items() to get the list of all groups or simply filter to get the specific PG by mesh_dim_name. 

Happy to hear feedback from a user perspective and open to discussions.

**Comment by wconstab** [comment]
i think its a little simplistic to jump from the goal of fewer public APIs to merging these into one.  Its probably not going to add much complexity to factor it into `get_group` (which never deals with lists) and `get_groups` (which never deals with mesh_dim but always returns a list).

I guess i'd vote for separate APIs, but i'd also be OK with just making get_group return a list consistently.  (I thought this might be non-preferred bc in 1-d cases someone wanted to just get the single group directly- in this case, splitting the API would preserve both)

**Comment by wz337** [comment]
I think I am convinced by @wconstab of making two separate APIs. Wdyt? @wanchaol

**Comment by wanchaol** [comment]
Yeah I think making them separate APIs sgtm, it also make the API semantic concise. A couple of things we need to be aware:
* we should make `get_group` to just return a single ProcessGroup (this is probably BC breaking behavior we need to document) even if user don't specify mesh_dim (maybe we by default return the dim 0 group or error out if it's multidim mesh and user does not specify mesh_dim)
* have a new API `get_groups` or maybe `get_all_groups`, where it does not take any arg but just return all the pgs
