### ISSUE TITLE
[JIT] Operators defined in python are not supported well

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#12206]
# The problem

There are many operators defined in python, such as `unique`, `clamp`, etc.

These operators are not supported well, for example:

```python
@torch.jit.script
def f(x):
    return torch.unique(x)
```
gives
```
Traceback (most recent call last):
  File "quicktest.py", line 3, in <module>
    @torch.jit.script
  File "/data/gaoxiang/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 639, in script
    graph = _jit_script_compile(ast, rcb)
RuntimeError: 
unknown builtin op:
@torch.jit.script
def f(x):
    return torch.unique(x)
           ~~~~~~~~~~~~ <--- HERE
```

and 

```python
@torch.jit.script
def f(x):
    return torch.clamp(x, min=0)
```

gives

```
Traceback (most recent call last):
  File "quicktest.py", line 7, in <module>
    @torch.jit.script
  File "/data/gaoxiang/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 639, in script
    graph = _jit_script_compile(ast, rcb)
RuntimeError: 
arguments for call are not valid:
  
  for operator aten::clamp(Tensor self, Scalar min, Scalar max) -> Tensor:
  argument max not provided.
  @torch.jit.script
  def f(x):
      return torch.clamp(x, min=0)
             ~~~~~~~~~~~ <--- HERE
for call at:
@torch.jit.script
def f(x):
    return torch.clamp(x, min=0)
           ~~~~~~~~~~~ <--- HERE
```

Many of these operators are just a wrapper of an ATen op, it is defined in python only because language difference such as C++ does not support kwargs, or C++ does not support a function to return different types.

# What we should do

For these ops, I suggest to add a mechanism to transform the call of these operators to its ATen form.

For example

```python
@torch.jit.script
def f(x):
    return torch.unique(x)
```

should be transformed to

```python
@torch.jit.script
def f(x):
    return torch._unique(x)[0]
```

which will be supported if https://github.com/pytorch/pytorch/pull/12203 get merged.

and

 ```python
@torch.jit.script
def f(x):
    return torch.clamp(x, min=0)
```

should be transformed into

 ```python
@torch.jit.script
def f(x):
    return torch.clamp_min(x, 0)
```

# Draft of ideas on implementation

In detail, the implementation might be something like:

In https://github.com/pytorch/pytorch/blob/master/torch/functional.py

```python
def unique(...):
    ...

def unique_jit_transform(treeview):
    # treeview is the part of AST constructed by `get_jit_ast` of this function call,
    # such as: Apply('torch.unique', {Ident('x')}, {})
    if 'in `treeview` dim is None and return_inverse is False':
        return Subscript(Apply('torch._unique', {Ident('x')}, {}), Const(0))
    ...

unique._jit_transform = unique_jit_transform
```

And in `emitSugaredExpr` in https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/compiler.cpp, `case TK_APPLY`,  when we saw that the callee is such an operator, invode its `_jit_transform` and then continue IR generation.

**Comment by zasdfgbnm** [comment]
I am not sure whether my suggested way of implementing would work/is good, so I need some discussion.

**Comment by apaszke** [comment]
The way you proposed will unfortunately give pretty bad error messages, due to the fact that there won't be any line and column numbers associated with the AST nodes you create.
