### ISSUE TITLE
[AOTI] test_dup_unbacked_sym_decl: C++ compilation error in abi_compatible mode

### ISSUE THREAD

**Issue by chenyang78** [pytorch/pytorch#122048]
### 🐛 Describe the bug

Repro:

comment out the line below:

https://github.com/pytorch/pytorch/blob/38d7d366b9f15f84b2f825c277266aa0face2280/test/inductor/test_aot_inductor.py#L2043

and run the following command:

```
$ TORCH_COMPILE_DEBUG=1 python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleCuda.test_dup_unbacked_sym_decl_abi_compatible_cuda
...
error: invalid user-d
efined conversion from ‘torch::aot_inductor::RAIIAtenTensorHandle’ to ‘int64_t’ {aka ‘long int’} [-fpermissive]                                                       
  605 |     int64_t int_array_0[] = {buf0};                                                                                                                           
      |                              ^~~~                                                                 
...
error: ‘aoti_torch_cu
da_index_Tensor’ was not declared in this scope; did you mean ‘aoti_torch_cuda_index_Tensor_out’?
  607 |     AOTI_TORCH_ERROR_CODE_CHECK(aoti_torch_cuda_index_Tensor(convert_arrayref_tensor_to_tensor(arg0_1), convert_arrayref_tensor_to_tensor(int_array_0), 1, con
vert_arrayref_tensor_to_tensor(&buf2_handle)));
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

There are two kinds of errors that we may need to fix.

### Versions

PyTorch version: 2.3.0a0+giteac4a14                                                                                                                                   
Is debug build: True                                                                                                                                                  
CUDA used to build PyTorch: 12.0                                                                                                                                      
ROCM used to build PyTorch: N/A

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @desertfire

**Comment by desertfire** [comment]
@FindHao , the problem here is `val_to_arg_str` does not take arg type as input, so at this point, https://github.com/pytorch/pytorch/blob/3183d65ac05d967384d0a93b0c1532685930d4f6/torch/_inductor/codegen/cpp_wrapper_cpu.py#L2311, it always generate an int array which is wrong. You need to consolidate [`val_to_cpp_arg_str`](https://github.com/pytorch/pytorch/blob/3183d65ac05d967384d0a93b0c1532685930d4f6/torch/_inductor/codegen/cpp_wrapper_cpu.py#L2238C9-L2238C27) and `val_to_arg_str` to use the type information properly.
