### ISSUE TITLE
[MPS] Regression from macOS 14.3 to 14.4 in PyTorch 2.2.0/2.2.1

### ISSUE THREAD

**Issue by AuroraWright** [pytorch/pytorch#122016]
### 🐛 Describe the bug

I've been using a pytorch model daily through transformers (https://github.com/kha-white/manga-ocr) and MPS. Everything was fine with latest PyTorch and latest Transformers until the Sonoma 14.4 update which made it start crashing on startup (I was running 14.3 before and am on a M1 Max mac, for reference). Since CPU mode worked fine, I also tried older versions of PyTorch and I found anything before 2.2.0 worked fine.
Bisecting it I found this commit is causing it: https://github.com/pytorch/pytorch/commit/056d6247c786f4391bc6a6f21337b009c7e9699e . I tried building latest main with that commit reverted and it's working again.

I apologize but I've not been able to pinpoint this further or to write a standalone example (since I don't really know what I'm doing here).
I've looked at what's happening from within transformers but not sure any of this can be of help:

It seems in https://github.com/huggingface/transformers/blob/main/src/transformers/generation/beam_search.py#L318 in input_ids the first member of each tensor array differs with or without that commit:

e.g.
With:
tensor([[3463342888,          2,       2312,       4080,       5063,       4885,
              3600,       5764,       5554,       4798,       1074,       3386,
              2865,       2166,       1524,       1858,       2872,       4014,
              5250,       1225,       2119,       1104,       1682,       5730,
              1482,       5578,         78],
       [3463342888,          2,       2312,       4080,       5063,       4885,
              3600,       5764,       5554,       4798,       1074,       3386,
              2865,       2166,       1524,       1858,       2872,       4014,
              5250,       1225,       2119,       1104,       1682,       5730,
              1482,       5578,        934],
       [3463342888,          2,       2312,       4080,       5063,       4885,
              3600,       5764,       5554,       4798,       1074,       3386,
              2865,       2166,       1524,       1858,       2872,       4014,
              5250,       1225,       2119,       1104,       1682,       5730,
              1482,       5578,        935],
       [3463342888,          2,       2312,       4080,       5063,       4885,
              3600,       5764,       5554,       4798,       1074,       3386,
              2865,       2166,       1524,       1858,       2872,       4014,
              5250,       1225,       2119,       1104,       1682,       5730,
              1482,       5578,         28]], device='mps:0')

Without:
tensor([[   2,    2, 2312, 4080, 5063, 4885, 3600, 5764, 5554, 4798, 1074, 3386,
        2865, 2166, 1524, 1858, 2872, 4014, 5250, 1225, 2119, 1104, 1682, 5730,
        1482, 5578,   78],
       [   2,    2, 2312, 4080, 5063, 4885, 3600, 5764, 5554, 4798, 1074, 3386,
        2865, 2166, 1524, 1858, 2872, 4014, 5250, 1225, 2119, 1104, 1682, 5730,
        1482, 5578,  934],
       [   2,    2, 2312, 4080, 5063, 4885, 3600, 5764, 5554, 4798, 1074, 3386,
        2865, 2166, 1524, 1858, 2872, 4014, 5250, 1225, 2119, 1104, 1682, 5730,
        1482, 5578,  935],
       [   2,    2, 2312, 4080, 5063, 4885, 3600, 5764, 5554, 4798, 1074, 3386,
        2865, 2166, 1524, 1858, 2872, 4014, 5250, 1225, 2119, 1104, 1682, 5730,
        1482, 5578,   21]], device='mps:0')

This difference is ultimately what causes the transformers crash.
Another weird thing I noticed was that in https://github.com/huggingface/transformers/blob/main/src/transformers/generation/beam_search.py#L366 , which in this particular case (launching "manga_ocr") evaluates to:
sent_lengths[0] = 26
this assignment only sticks if I retrieve sent_lengths[0] immediately after it's set within the loop (eg "test_var = sent_lengths[0] + 1" or also a print), doing it out of the loop doesn't work either (this fixes the crash in manga_ocr's case, though the first member of "decoded" that's returned in https://github.com/huggingface/transformers/blob/main/src/transformers/generation/beam_search.py#L408 is still some incorrect/very high value like in input_ids above).

### Versions

Collecting environment information...
PyTorch version: 2.2.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.28.3
Libc version: N/A

Python version: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] (64-bit runtime)
Python platform: macOS-14.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] onnxruntime==1.17.1
[pip3] rapidocr-onnxruntime==1.2.3
[pip3] torch==2.2.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.17.1
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kadeng @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by malfet** [comment]
Sorry, can you please be a bit more specific of what do you mean by "crashes at the startup"?
I'm on 14.4 and everything seems to be working fine at the first glance, i.e.:
```
% sw_vers;python -c "import torch;print(torch.__version__, torch.rand(3, device='mps'))"
ProductName:		macOS
ProductVersion:		14.4
BuildVersion:		23E214
2.2.0 tensor([0.7952, 0.0344, 0.0591], device='mps:0')
```

**Comment by malfet** [comment]
Ok, I think I have a minimal reproducer of the problem
```
python -c "import torch;x=torch.zeros(3, device='mps');x[1] = 1; x[2] = 3; print(x)"
tensor([0., 3., 3.], device='mps:0')

```

**Comment by malfet** [comment]
And following fixes the problem, which makes me wonder how this ever worked before:
```patch
diff --git a/aten/src/ATen/native/mps/operations/Copy.mm b/aten/src/ATen/native/mps/operations/Copy.mm
index 987c061474c..5f701650fe7 100644
--- a/aten/src/ATen/native/mps/operations/Copy.mm
+++ b/aten/src/ATen/native/mps/operations/Copy.mm
@@ -277,7 +277,7 @@ void copy_blit_mps(void* dst, const void* src, size_t size) {
   if (sameDataType) {
     uint64_t profile_id = getMPSProfiler().beginProfileCopy(sourceBuffer, destBuffer, src, dst_, src.nbytes(), true);
     // for GPU to GPU copies we only encode to stream's command buffer (no flushing)
-    stream->copy(sourceBuffer, destBuffer, src.nbytes(), src_byte_offset, dst_byte_offset, profile_id);
+    stream->copy_and_sync(sourceBuffer, destBuffer, src.nbytes(), src_byte_offset, dst_byte_offset, non_blocking, profile_id);
   } else {
     // Simulate cast to Complex on older MacOS by initializing real and imag parts
     if (dst_.is_complex() && !supportsComplex()) {
```

**Comment by lamroger** [comment]
@malfet if you don't mind explaining, what does copy_and_sync and non_blocking do vs copy? Just for learning thanks!

**Comment by malfet** [comment]
@lamroger Looking for a good vendor-neutral document on the subject but could not find one. In general, non-blocking operations, as name suggests are non-blocking, i.e. operation might still be ongoing when one returns to a function calls (see [`glFlush`](https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glFlush.xml) API description dating back to 1991 )

In practice, imagine one is running the following code:
```python 
x = torch.ones(3, device="cpu")
# At this point, `x` is filled with 1
y = torch.rand(3, device="cpu")
# At this point, `y` contains 3 randomly generated values
z = x + y
# At this point, `z` contains result of element-wise sum of `x` and `y`
print(z) # At this just prints the memory contents
```
vs
```python
x = torch.ones(3, device="mps")
# At this point, 12 bytes of GPU memory are allocated, `x.data_ptr()` points to it and command to fill this memory with ones is submitted to command queue (that might or might not execute in the background)
y = torch.rand(3, device="mps")
# Same as before, memory allocated, `y.data_ptr()` references it and command to fill it with random values has been queued and guaranteed to be executed after the first command
z = x + y
# At this point, `z` points to GPU memory, command to perform element wise sum has been issued
print(z)
# To print values, they must be copied to CPU, which triggers sync (i.e. commit and wait)
# That waits for all the previous operations to complete
```


I.e. by default GPU operations are executed asynchronously( so timing it on CPU doesn't make much sense, as it will only memory time required to reserve memory and enqueue respective commands)

**Comment by lamroger** [comment]
Thanks for the breakdown @malfet ! 

Do you have an idea of why 
```
python -c "import torch;x=torch.zeros(3, device='mps');x[1] = 1; x[2] = 3; print(x)"
tensor([0., 3., 3.], device='mps:0')
```
previously had the result of [0, 3, 3]? Seem like in any asynchronous scenario, there would be at most one 3. How'd it get two 3s?

**Comment by atalman** [comment]
validated with 2.3.0
```
python -c "import torch;x=torch.zeros(3, device='mps');x[1] = 1; x[2] = 3; print(x)"
tensor([0., 1., 3.], device='mps:0')
```
