### ISSUE TITLE
"Error when running model: TypeError: 'generator' object is not callable

### ISSUE THREAD

**Issue by thalapandi** [pytorch/pytorch#122054]
### 🐛 Describe the bug

import random
import torch
import time
import numpy as np
from torch.optim import Adam
from torch.optim.lr_scheduler import LambdaLR
from torch.nn import NLLLoss
import os
from shutil import copyfile
from torch.utils.tensorboard import SummaryWriter
from common.evaluation import Cider
# from common.data import DataLoader
from common.data.field import RawField
# from common.utils import evaluate_loss, evaluate_metrics
from common.utils.utils import setup_seed

# from common.data.field import *
# from common.data.dataset import COCODataset
from torch.utils.data import DataLoader as TorchDataLoader
# from .field import *
# from .dataset import COCODataset

class DataLoader(TorchDataLoader):
    def __init__(self, dataset, *args, **kwargs):
        super(DataLoader, self).__init__(dataset, *args, collate_fn=Dataset.collate_fn, **kwargs)

scheduler=None
args = opt
device = args.device
output = args.output
use_rl = args.use_rl

date = time.strftime("%Y-%m-%d", time.localtime())
writer = SummaryWriter(log_dir=os.path.join(output, 'tensorboard_logs', args.exp_name, date))

train_dataset, val_dataset, test_dataset = datasets

# dict_dataset_train = train_dataset.image_dictionary({'image': image_field, 'text': RawField()})

dict_dataset_val = val_dataset.image_dictionary({'image': image_field, 'text': RawField()})
dict_dataset_test = test_dataset.image_dictionary({'image': image_field, 'text': RawField()})

train_batch_size = args.batch_size // 5 if use_rl else args.batch_size
dataloader_train = DataLoader(train_dataset, batch_size=train_batch_size, shuffle=True, pin_memory=True, drop_last=False)
dataloader_val = DataLoader(val_dataset, batch_size=train_batch_size, pin_memory=True, drop_last=False)
dict_dataloader_val = DataLoader(dict_dataset_val, batch_size=train_batch_size, pin_memory=True, drop_last=False)
dict_dataloader_test = DataLoader(dict_dataset_test, batch_size=train_batch_size, pin_memory=True, drop_last=False)

for it, (images, captions) in enumerate(dataloader_train):
    print(images)
    
    
    
    
    ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-34-84b3fc2d894c>](https://localhost:8080/#) in <cell line: 55>()
     53 dict_dataloader_test = DataLoader(dict_dataset_test, batch_size=train_batch_size, pin_memory=True, drop_last=False)
     54 
---> 55 for it, (images, captions) in enumerate(dataloader_train):
     56     print(images)

2 frames
[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in __next__(self)
    629                 # TODO(https://github.com/pytorch/pytorch/issues/76750)
    630                 self._reset()  # type: ignore[call-arg]
--> 631             data = self._next_data()
    632             self._num_yielded += 1
    633             if self._dataset_kind == _DatasetKind.Iterable and \

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py](https://localhost:8080/#) in _next_data(self)
    673     def _next_data(self):
    674         index = self._next_index()  # may raise StopIteration
--> 675         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    676         if self._pin_memory:
    677             data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)

[/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py](https://localhost:8080/#) in fetch(self, possibly_batched_index)
     47         if self.auto_collation:
     48             if hasattr(self.dataset, "__getitems__") and self.dataset.__getitems__:
---> 49                 data = self.dataset.__getitems__(possibly_batched_index)
     50             else:
     51                 data = [self.dataset[idx] for idx in possibly_batched_index]

TypeError: 'generator' object is not callable

https://github.com/weimingboya/DFT/blob/main/common/data/dataset.py

### Versions

need  to resolve this issue can anyone help me to resolve the problem

**Comment by LamForest** [comment]
Hi, @thalapandi it would be helpful to format your code and wrap it with ```, easier for others to repro. See more at https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by thalapandi** [comment]
https://colab.research.google.com/drive/1xMJUmr6KhZkoglnvcpxYQTTUM1V4qeD4


this is my colab imlementating page

**Comment by bdhirsh** [comment]
Hi,

If you think this is a bug in the pytorch codebase, please include a standalone reproducible code snippet (the colab you linked requires permissions to access).

The error message looks like a user error, so I would suggest posting the question on the pytorch forum: https://discuss.pytorch.org/
