### ISSUE TITLE
how to find the source code of the torch.linalg.eigh

### ISSUE THREAD

**Issue by liweiyangv** [pytorch/pytorch#122079]
### 📚 The doc issue

what is the iteration process of the torch.linalg.eigh

**Comment by LamForest** [comment]
Are you looking for _linalg_eigh
```
# This function is exposes the `compute_v` flag, which is then used to implement `linalg.eigh` and
# `linalg.eigvalsh` as composite functions that call this one
- func: _linalg_eigh(Tensor A, str UPLO="L", bool compute_v=True) -> (Tensor eigenvalues, Tensor eigenvectors)
  structured_delegate: _linalg_eigh.eigenvalues
```

**Comment by liweiyangv** [comment]
> Are you looking for _linalg_eigh
> 
> ```
> # This function is exposes the `compute_v` flag, which is then used to implement `linalg.eigh` and
> # `linalg.eigvalsh` as composite functions that call this one
> - func: _linalg_eigh(Tensor A, str UPLO="L", bool compute_v=True) -> (Tensor eigenvalues, Tensor eigenvectors)
>   structured_delegate: _linalg_eigh.eigenvalues
> ```

Thanks for your reply, could you please give me more details about the algorithm of the eigh?

**Comment by LamForest** [comment]
@liweiyangv 
Your can find its CPU implemention at:
https://github.com/pytorch/pytorch/blob/1a58e9d357c70d781591566a555728d1f98f093d/aten/src/ATen/native/BatchLinearAlgebraKernel.cpp#L197

GPU at :
https://github.com/pytorch/pytorch/blob/1a58e9d357c70d781591566a555728d1f98f093d/aten/src/ATen/native/cuda/LinearAlgebraStubs.cpp#L93
or
https://github.com/pytorch/pytorch/blob/1a58e9d357c70d781591566a555728d1f98f093d/aten/src/ATen/native/cuda/linalg/BatchLinearAlgebra.cpp#L2079
depends on your compile options.

**Comment by bdhirsh** [comment]
@LamForest's links above look right. Github issues are mostly reserved for bugs and feature requests - for questions, feel free to post them on the forum https://discuss.pytorch.org/

**Comment by liweiyangv** [comment]
> @liweiyangv Your can find its CPU implemention at:
> 
> https://github.com/pytorch/pytorch/blob/1a58e9d357c70d781591566a555728d1f98f093d/aten/src/ATen/native/BatchLinearAlgebraKernel.cpp#L197
> 
> GPU at :
> 
> https://github.com/pytorch/pytorch/blob/1a58e9d357c70d781591566a555728d1f98f093d/aten/src/ATen/native/cuda/LinearAlgebraStubs.cpp#L93
> 
> 
> or
> https://github.com/pytorch/pytorch/blob/1a58e9d357c70d781591566a555728d1f98f093d/aten/src/ATen/native/cuda/linalg/BatchLinearAlgebra.cpp#L2079
> 
> 
> depends on your compile options.

Thanks for telling me

**Comment by liweiyangv** [comment]
> @LamForest's links above look right. Github issues are mostly reserved for bugs and feature requests - for questions, feel free to post them on the forum https://discuss.pytorch.org/

Thanks for telling me
