### ISSUE TITLE
Is it realistic to use C++ and libtorch to train models on aarch64 devices using CPUs?

### ISSUE THREAD

**Issue by Heize123456** [pytorch/pytorch#122082]
### 🚀 The feature, motivation and pitch

For example, if I freeze the network layer of Yolo and only train the fully connected layer for fine-tuning, there is only a small amount of data per training, is it realistic?
I means in the edge device with low computing power, the CPU is used to train slowly to achieve a closed data loop....?

**Comment by digantdesai** [comment]
I would imagine it might be tricky without Python runtime on device using existing PyTorch training flow on device.
