### ISSUE TITLE
[AOTI] test_repeat_output: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by chenyang78** [pytorch/pytorch#122051]
### 🐛 Describe the bug

How to repro:

comment out the line below:

https://github.com/pytorch/pytorch/blob/38d7d366b9f15f84b2f825c277266aa0face2280/test/inductor/test_aot_inductor.py#L2046

and run the following command:

```
$ TORCH_COMPILE_DEBUG=1 python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleCuda.test_repeat_output_abi_compatible_cuda
...
Segmentation fault (core dumped)
```

### Versions

PyTorch version: 2.3.0a0+giteac4a14
Is debug build: True
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @desertfire

**Comment by desertfire** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/122846
