### ISSUE TITLE
sum of a torch.Tensor return the wong result

### ISSUE THREAD

**Issue by stephane-archer** [pytorch/pytorch#12215]
the sum of a torch.tensor return me a strange result.

Why???

this is my code:
`
print(result.shape)
print(result)
print(type(result))
print(result.dtype)
print(sum(result))
mysum = 0
for i in result:
    mysum += i.item()
print("Mysum", mysum)
`

this is the output:
`
torch.Size([24512])
tensor([ 1,  1,  1,  ...,  1,  1,  1], dtype=torch.uint8)
<class 'torch.Tensor'>
torch.uint8
tensor(80, dtype=torch.uint8)
Mysum 15184
`

80 is not the same of 15184. Why I get different result? what the 80 represents?

Pytorch V0.4.0

**Comment by albanD** [comment]
Hi,

You are working with ByteTensors here. So the value cannot exceed 255. Convert your Tensor to a Long or Float type before performing the sum to get the correct value.

**Comment by zou3519** [comment]
The type gets promoted on master to LongTensor. But at any rate, @albanD is correct for your version.
