### ISSUE TITLE
PackagesNotFoundError: unable to install torchvision in anaconda prompt on windows 10

### ISSUE THREAD

**Issue by edtky** [pytorch/pytorch#12210]
`conda install torchvision -c soumith`

returns the following:

`PackagesNotFoundError: The following packages are not available from current channels: - torchvision`

**Comment by peterjc123** [comment]
pip install torchvision

**Comment by soumith** [comment]
`-c soumith` should never be used. Where did you find instructions to use that?

**Comment by jcezarms** [comment]
@soumith probably found it in one of PyPI's instructions on torchvision installation for older versions, [such as 0.1.8 here](https://pypi.org/project/torchvision/0.1.8/).

**Comment by jcezarms** [comment]
@soumith probably in one of PyPI's instructions for older versions, [such as 0.1.8 here](https://pypi.org/project/torchvision/0.1.8/). There's also [a very prominent Anaconda Cloud link](https://anaconda.org/soumith/torchvision) (that was first in the search that got me here) which also gives out `-c soumith`.

**Comment by Gaussian01** [comment]
conda install -c pytorch torchvision
