### ISSUE TITLE
[ONNX] Dispatcher does not handle list correctly when the first element is None

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#122166]
### 🐛 Describe the bug

When this dispatcher is handling inputs of type `Sequence[None | Tensor]`, it checks the type of only the first element. If the element is None it is unable to obtain the correct type:

https://github.com/pytorch/pytorch/blob/18d94d71659ee820e450c23ef1df3862396946ac/torch/onnx/_internal/fx/onnxfunction_dispatcher.py#L884

This leads to functions being selected incorrectly in the case of `aten::index`, where `[None, INT64, ...]` is dispatched to the `BOOL` overload.

cc @titaiwangms @BowenBao @fatcat-z 

### Versions

latest

**Comment by titaiwangms** [comment]
Wondering how did you find this out in torchlib? I am thinking about the case guarding the fix.
