### ISSUE TITLE
Setting x._backward_hooks to None doesn't error, doesn't clear hooks

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#12219]
## 🐛 Bug

```
import torch

y = torch.ones(5, 5, requires_grad=True)

counter = [0]
def bw_hook(grad):
    counter[0] += 1

z = y + y
test = z.register_hook(bw_hook)
print(z._backward_hooks)
z._backward_hooks = None
print(z._backward_hooks)
z.backward(torch.ones(5, 5), retain_graph=True)
print(counter)
```

this prints:

```
$ python hooky.py               
OrderedDict([(0, <function bw_hook at 0x7f2c9ab69e18>)])
None
[1]
```

## Expected behavior

I expect to either get an error, saying you can't set `_backward_hooks` to None, or for hooks to be cleared if I do this.

**Comment by ezyang** [comment]
Hmm, I read `register_hook` more carefully, and it seems that it not only puts a hook on a variable, it also calls `register_hook_dict` on the `grad_fn`, which is probably what is triggering `counter`. So maybe I just don't understand what the semantics of `register_hooks` is supposed to be...

**Comment by apaszke** [comment]
I don't understand why do you expect that something will happen if you set an internal attribute to a particular value. We might add a helper that clears the hooks, but we definitely don't need to honor the behavior you described.

**Comment by ezyang** [comment]
Going to close this as WONTFIX for now. Doesn't seem to be killing anyone.
