### ISSUE TITLE
[Dort][dynamo_onnx] Same type of nodes with multi-outputs leads to incorrect model output name

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#122150]
Discovered from dort https://github.com/microsoft/onnx-converters-private/issues/221

Example:

Observe that the first graph output is `bool[1, 2, 3] native_dropout_1`. However, it should be `bool[1, 2, 3] native_dropout_1.1`. The incorrect name overrides shape and dtype of the other value `native_dropout_1`, which is the float output of second dropout node. This leads to downstream shape inference error. 

e.g. `onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:aten_native_dropout, node name: aten_native_dropout_652): [TypeInferenceError] Inferred elem type differs from existing elem type: (10) vs (9)`

```python
import torch


class Module(torch.nn.Module):
    def forward(self, x):
        x, mx = torch.ops.aten.native_dropout(x, 0.1, True)
        y, my = torch.ops.aten.native_dropout(x, 0.1, True)
        return mx, my


eo = torch.onnx.dynamo_export(Module(), torch.rand(1, 2, 3))
import onnx

onnx.printer.to_text(eo.model_proto)

"""
...
main_graph (float[1,2,3] l_x_) => (bool[1,2,3] native_dropout_1, bool[1,2,3] native_dropout_1_1) 
   <float[1,2,3] native_dropout, float[1,2,3] native_dropout_1, float[1,2,3] l_x_, bool[1,2,3] native_dropout_1, bool[1,2,3] native_dropout_1_1>
{
   native_dropout, native_dropout_1.1 = pkg.onnxscript.torch_lib.aten_native_dropout <p: float = 0.1, train: int = 1> (l_x_)
   native_dropout_1, native_dropout_1_1 = pkg.onnxscript.torch_lib.aten_native_dropout <p: float = 0.1, train: int = 1> (native_dropout)
}
...
Graph first output:
name: "native_dropout_1"
type {
  tensor_type {
    elem_type: 9
    shape {
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 2
      }
      dim {
        dim_value: 3
      }
    }
  }
}

First node outputs
['native_dropout', 'native_dropout_1.1']
Second node outputs
['native_dropout_1', 'native_dropout_1_1']
"""

```

cc @thiagocrepaldi, @shubhambhokare1, @titaiwangms

**Comment by BowenBao** [comment]
Looking at the onnx model, the value_info for intermediate values are also wrong. Looks like there are some bugs around using debugName of torch._C.Value.

**Comment by titaiwangms** [comment]
> Looking at the onnx model, the value_info for intermediate values are also wrong. Looks like there are some bugs around using debugName of torch._C.Value.

The code is in torchscript or graph_building?

**Comment by BowenBao** [comment]
More likely in graph_building, and the serialization part (to_model_proto & to_function_proto)

**Comment by BowenBao** [comment]
Fixed by https://github.com/microsoft/onnxscript/pull/1306
