### ISSUE TITLE
split_with_sizes with unbacked SymInt results in buffers that cannot be materialized for extern calls

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#122126]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/6829516587176185/posts/8163801153646945

Repro:

```
import torch
import torch._dynamo

torch._dynamo.config.capture_scalar_outputs = True

@torch.compile()
def f(sz, x):
    s0, s1 = sz.tolist()
    r0, r1 = torch.ops.aten.split_with_sizes.default(x, [s0, s1])
    return torch.ops.aten.sort.default(r1)

N = 7312
S0 = 420
S1 = N - S0

f(torch.tensor([S0, S1]), torch.randn(N))
```

The sort here doesn't matter, just needs to be some kernel that is fallback.

Errors with

```
  File "/data/users/ezyang/b/pytorch/torch/fx/experimental/symbolic_shapes.py", line 4147, in evaluate_expr
    raise self._make_data_dependent_error(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: GuardOnDataDependentSymNode: Could not guard on data-dependent expression Eq(-Min(7312, Max(0, u0)) + Min(7312, Max(0, u0, u0 + u1)), 0) (unhinted: Eq(-Min(7312, Max(0, u0)) + Min(7312, Max(0, u0, u0 + u1)), 0)).  (Size-like symbols: u0, u1)

Potential framework code culprit (scroll up for full backtrace):
  File "/data/users/ezyang/b/pytorch/torch/_ops.py", line 600, in __call__
    return self_._op(*args, **kwargs)

For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0,u1"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

  target: aten.sort.default
  args[0]: TensorBox(
    ReinterpretView(
      StorageBox(
        InputBuffer(name='arg1_1', layout=FixedLayout('cpu', torch.float32, size=[7312], stride=[1]))
      ),
      FixedLayout('cpu', torch.float32, size=[-Min(7312, Max(0, u0)) + Min(7312, Max(u0 + u1, Max(0, u0)))], stride=[1], offset=Min(7312, Max(0, u0))),
      origins={split_with_sizes}
    )
  )
```

The problem is that is overconservatively clamping the views that are implied by split_with_sizes, and then we are no longer able to do a size-oblivious test (to be clear, this IS a size oblivious test).

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

**Comment by ezyang** [comment]
If I avoid the narrow codepath it works:

```
import torch
import torch._dynamo

torch._dynamo.config.capture_scalar_outputs = True

torch.library.define("ezyang::split_with_sizes_and_clone", "(Tensor input, SymInt[] sizes) -> Tensor[]")

def split_with_sizes_and_clone(input, sizes):
    return [t.clone() for t in torch.ops.aten.split_with_sizes.default(input, sizes)]

torch.library.impl("ezyang::split_with_sizes_and_clone", "default", split_with_sizes_and_clone)

@torch.library.impl_abstract("ezyang::split_with_sizes_and_clone")
def split_with_sizes_and_clone_abstract(input, sizes):
    # TODO: I'm lazy
    rs = torch.ops.aten.split_with_sizes.default(input, sizes)
    return [input.new_empty(r.size()) for r in rs]

@torch.compile()
def f(sz, x):
    s0, s1 = sz.tolist()
    r0, r1 = torch.ops.ezyang.split_with_sizes_and_clone.default(x, [s0, s1])
    return torch.ops.aten.sort.default(r1)

N = 7312
S0 = 420
S1 = N - S0

f(torch.tensor([S0, S1]), torch.randn(N))
```

**Comment by ezyang** [comment]
I think the right fix is to have a custom lowering for split_with_sizes in Inductor which can put tight bounds on the size in question, rather than going through successive calls to narrow which have to clamp.

**Comment by flaviotruzzi** [comment]
I am testing this to check we do get a valid graph that can be lowered, if that works then I can try implement it.

**Comment by ezyang** [comment]
cc @aakhundov

**Comment by ColinPeppler** [comment]
> rather than going through successive calls to narrow which have to clamp.

Hey @ezyang, is this the difference between going through `Tensor.clone()` vs `torch.empty_stride(sizes=sizes ...)`?

**Comment by ezyang** [comment]
Check @flaviotruzzi's PR, it is a good approach.

In my workaround, I clone the Tensors after splitting because this allows me to write a custom op without having to work out view logic. This lets me black box the inner implementation entirely, and then in my meta implementation I just give the outputs straightforward types which won't choke on subsequent code.

> now, I'm trying to understand what does "putting tight bounds on the size" mean here.

When I say x[a:b], I do not know if b is in bounds, because it is allowed to be out of bounds (say sys.maxsize) and we will just clamp it to len(x). With split_with_sizes, I end up calling `x[sizes[0]:sizes[0] + size[1]]`. However, I know that `size[0] + size[1]` is guaranteed to be in bound. Flavio's PR specifies that we should never wraparound here.

**Comment by ColinPeppler** [comment]
Thanks for the explanation. I see what you mean now. 

I also see that we have guards checking that everything is in-bounds which further proves we don't need a clamp. 
https://github.com/pytorch/pytorch/blob/e26280ad8bf6eecb0f218d69f3ec90f01617fac4/torch/_decomp/decompositions.py#L1316-L1332
