### ISSUE TITLE
[c10d] Python 3.12 support for c10d Store

### ISSUE THREAD

**Issue by XilunWu** [pytorch/pytorch#122240]
### 🚀 The feature, motivation and pitch

This is a tracker of python 3.12 support for c10d Store. We have received issues of store being early destroyed when using Python 3.12 e.g. #115977 

A better example is #116423 . The result can be reproduced locally using a built-from-source pytorch within a Python 3.12 conda env.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @rohan-varma

**Comment by Parskatt** [comment]
Can you increase the priority on this?
Also: https://github.com/pytorch/pytorch/issues/125990

**Comment by XilunWu** [comment]
@Parskatt really sorry for the delay. I expect to have bandwidth mid-June to fix this issue.

**Comment by XilunWu** [comment]
close the issue with @wconstab 's fix #128212
