### ISSUE TITLE
[inductor][cpu] maml_omniglot fp32 Dynamic shape default wrapper accuracy crashed

### ISSUE THREAD

**Issue by WeizhuoZhang-intel** [pytorch/pytorch#122285]
### 🐛 Describe the bug

new_failures in 2024-02-25
| suite | name | thread | accuracy | perf | reason(reference only)
-- | -- | -- | -- | -- | --
torchbench | maml_omniglot | multiple | X | √ | maml_omniglot, AssertionError: expected size 64==64 stride 676==1 at dim=1
torchbench | maml_omniglot | single | X | √ | maml_omniglot, AssertionError: expected size 64==64 stride 676==1 at dim=1

Error:
```
loading model: 0it [00:00, ?it/s]cpu  eval  maml_omniglot                      

skipping cudagraphs due to skipping cudagraphs due to cpu device. Found from : 
   File "benchmarks/dynamo/torchbench.py", line 350, in forward_pass
    return mod(*inputs)

ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2626, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/torchbench.py", line 348, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 892, in forward
    return compiled_fn(full_args)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/utils.py", line 79, in g
    return f(*args)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 101, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/utils.py", line 103, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 122, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1088, in wrapper
    return optimized_function(args_new)
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 825, in __call__
    return self.get_current_callable()(inputs)
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 853, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/tmpi0xi5r_c/fd/cfdr2bfakywvszeearvqvdyltpxlafqhpy7iri2miwsd2uusmngm.py", line 163, in call
    assert_size_stride(buf0, (s0, 64, 26, 26), (43264, 1, 1664, 64))
AssertionError: expected size 64==64, stride 676==1 at dim=1
Run failed with return code:  255
Output:  None
Error:  None
```

### Versions

SW info
| name | target_branch | target_commit | refer_branch | refer_commit
-- | -- | -- | -- | --
torchbench | main | ff42d907 | main | ff42d907
torch | main | 5c7b761f8e748fe45c8e2e29563df637ae651917 | main | becfda005e524f93b1efed64917a129ef6778135
torchvision | main | 0.18.0a0+a52607e | main | 0.18.0a0+a52607e
torchtext | main | 0.16.0a0+b0ebddc | main | 0.16.0a0+b0ebddc
torchaudio | main | 2.2.0a0+5286f9f | main | 2.2.0a0+5286f9f
torchdata | main | 0.7.1a0+0790338 | main | 0.7.1a0+0790338
dynamo_benchmarks | main | nightly | main | nightly

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)

```shell
bash inductor_single_run.sh single inference accuracy torchbench maml_omniglot float32 first dynamic default 0
```
`maml_omniglot` looks like a new enabled model, so we did not find the guilty commit.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @WeizhuoZhang-intel @chuanqi129 @zxd1997066

**Comment by chuanqi129** [comment]
@WeizhuoZhang-intel This model is not new models of Torchbench, previously, this model will be skipped by default. There are some change in skip logic recently.

**Previous**: benchmarks/dynamo/torchbench.py --performance --float32 -dcpu  --inference -n50 --inductor  --timeout 9000   --freezing  --no-skip --dashboard **-x maml** -x fambench_xlmr -x tacotron2 -x clip -x simple_gpt_tp_manual -x hf_Bert_large -x hf_Bert -x detectron2_maskrcnn -x sam -x nanogpt_generate --cold-start-latency

**Now**: benchmarks/dynamo/torchbench.py --performance --float32 -dcpu  --inference -n50 --inductor  --timeout 9000   --freezing  --no-skip --dashboard -x detectron2_maskrcnn -x simple_gpt_tp_manual -x hf_clip -x tacotron2 -x sam -x nanogpt_generate -x sam -x nanogpt_generate --cold-start-latency

**Comment by chuanqi129** [comment]
Also tracked in https://github.com/pytorch/pytorch/issues/120873

**Comment by leslie-fang-intel** [comment]
@chunyuan-w will double check the latest PyTorch for this issue.

**Comment by WeizhuoZhang-intel** [comment]
Hi @chunyuan-w ,
The latest report with torch commit 6f74b7607207054c1f5331183ab725640c99fe8d still has this issue.

**Comment by chunyuan-w** [comment]
> Hi @chunyuan-w , The latest report with torch commit [6f74b76](https://github.com/pytorch/pytorch/commit/6f74b7607207054c1f5331183ab725640c99fe8d) still has this issue.

Thanks for the information. 
https://github.com/pytorch/pytorch/pull/121400 is expected to fix this issue. I checked that https://github.com/pytorch/pytorch/commit/6f74b7607207054c1f5331183ab725640c99fe8d hasn't included the above fix PR yet. Let's check the status in the next regular report which will include the fix PR.

**Comment by chunyuan-w** [comment]
Fixed in the inference-float32-dynamic-default 2024_03_25 test. @WeizhuoZhang-intel could you help double-confirm and close this issue?

**Comment by WeizhuoZhang-intel** [comment]
Thanks @chunyuan-w. This issue has been verified on our 2024_03_25 report.
