### ISSUE TITLE
build main with vs2022

### ISSUE THREAD

**Issue by WangHHY19931001** [pytorch/pytorch#122282]
### 🐛 Describe the bug

pytorch\binaries\dump_operator_names.cc
need add include
#include <iostream>
pytorch\aten\src\ATen\native\vulkan\ops\Clamp.cpp
need add include 
#define _USE_MATH_DEFINES
#include <cmath>
#include <corecrt_math_defines.h>

### Versions

pytorch main

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by WangHHY19931001** [comment]
"C:\Program Files (x86)\Intel\oneAPI\setvars.bat" intel64 vs2022

cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=E:\pytorch\install_path -DCMAKE_PREFIX_PATH=E:\pytorch\install_path -DUSE_SOURCE_DEBUG_ON_MOBILE=OFF -DUSE_NUMPY=OFF -DBUILD_BINARY=ON -DBUILD_PYTHON=OFF -DUSE_DISTRIBUTED=OFF -DUSE_CUDA=OFF -DUSE_OPENCL=OFF -DUSE_VULKAN=ON -USE_VULKAN_FP16_INFERENCE=OFF -DUSE_VULKAN_RELAXED_PRECISION=OFF -DUSE_FBGEMM=OFF -DUSE_KINETO=OFF -DUSE_MIMALLOC=OFF -DUSE_TBB=ON -DUSE_SYSTEM_TBB=ON -DUSE_MKLDNN=ON -DUSE_MKL=ON -DUSE_MKLDNN_ACL=ON -DUSE_MKLDNN_CBLAS=ON -DBUILD_SHARED_LIBS=ON -DUSE_XNNPACK=OFF -DONNX_ML=OFF ..

**Comment by WangHHY19931001** [comment]
SHA-1: cbbed4637737c7125bd7a3f8a81f23de1a46a9c9

**Comment by malfet** [comment]
Not sure I'm following what you want to do here. Do you mind posting a full error message that you are running into?
Also, if you have an idea for change to fix the build issue, please do not hesitate to propose a PR

**Comment by WangHHY19931001** [comment]
pytorch\binaries\dump_operator_names.cc
need include iostream
pytorch\aten\src\ATen\native\vulkan\ops\Clamp.cpp
need include cmath and corecrt_math_defines.h

**Comment by WangHHY19931001** [comment]
> Hey @WangHHY19931001, why do you say these extra includes are necessary? Did you have problems with building from source, as it works for me without modyfing these files.

at that time use  oneapi 2024 and vs2022 old version, may be it been fix with new version build tools

**Comment by alinpahontu2912** [comment]
Hey @WangHHY19931001, I will be closing this issue. Feel free to reopen it if needed or open new ones if you find bugs or have ideas for feature requests.
