### ISSUE TITLE
AWS config change stripped public access from number of CI buckets, but no alerts were raised

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#122206]
Originally reported by  @ezyang as HUD log acess, regression end up affecting public access to almost all the buckets used by CI, most notably launch metrics.

For example, `lintrunner-noclang/linux-job` points to 
https://ossci-raw-job-status.s3.amazonaws.com/log/22458385161

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Probably following change https://github.com/pytorch-labs/pytorch-gha-infra/pull/360  stripped public read access from the bucket

**Comment by malfet** [comment]
One more victim is public access to https://ossci-metrics.s3.amazonaws.com/pytorch_labels.json

**Comment by clee2000** [comment]
The list of disabled tests is also in ossci-metrics, which is responsible for most of the linux test failures popping up.  ROCm tests are all failing due  to lack of access to gha-artifacts bucket

**Comment by jeanschmidt** [comment]
The fix is published in https://github.com/pytorch-labs/pytorch-gha-infra/pull/362

If you are experiencing issues with CI, fixes should now be live. Please trigger your job again.

**Comment by malfet** [comment]
Removing CI:SEV as it seems to be mitigated now, but would be good to have a follow up on how to prevent this in the future

**Comment by atalman** [comment]
I believe last fix for this issue was deployed here: https://github.com/pytorch-labs/pytorch-gha-infra/pull/367

**Comment by huydhn** [comment]
Sev review doc https://docs.google.com/document/d/1iXAWYtampB8i_DBaX7Nz-Lj5f3hpVUAbXKeaC5p6ZvE
