### ISSUE TITLE
result of torch.tensor(float('inf')).cuda().min() is not inf

### ISSUE THREAD

**Issue by pfrendl** [pytorch/pytorch#12233]
## 🐛 Bug

min() on cuda tensors maps inf to 340282346638528859811704183484516925440.

Tensors of arbitrary dimensions seem to display this behavior.

Because of this, there are cases where inf is not equal to itself on the gpu:
```
>>> import torch
>>> a = torch.tensor(float('inf')).cuda()
>>> a
tensor(inf, device='cuda:0')
>>> a.min()
tensor(340282346638528859811704183484516925440., device='cuda:0')
>>> a == a
tensor(1, device='cuda:0', dtype=torch.uint8)
>>> a.min() == a
tensor(0, device='cuda:0', dtype=torch.uint8)
```

Also, max() fails on -inf:
```
>>> torch.tensor(float('-inf')).cuda().max()
tensor(-340282346638528859811704183484516925440., device='cuda:0')
```

## To Reproduce
Run the following line:
`>>> torch.tensor(float('inf')).cuda().min()`
Result:
`tensor(340282346638528859811704183484516925440., device='cuda:0')`

## Expected behavior

The min() operation should result in inf, just like on the cpu:
```
>>> torch.tensor(float('inf')).min()
tensor(inf)
```

Casting back works fine:
```
>>> torch.tensor(float('inf')).cuda().cpu().min()
tensor(inf)
```

## Environment

 - PyTorch Version: 0.4.1
 - OS: Windows 10, Ubuntu 16.04
 - How you installed PyTorch: conda
 - Python version: Python 3.6.4 :: Anaconda custom (64-bit)
 - CUDA/cuDNN version: 9.2
 - GPU models and configuration: GTX 1080

**Comment by SsnL** [comment]
Thanks for report. Fixed on master!
