### ISSUE TITLE
PT2 backends="cudagraph" does not support dynamic shapes

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#122371]
### 🐛 Describe the bug

cf https://github.com/pytorch/pytorch/issues/122314

give better error message

### Versions

main

cc @mcarilli @eellison @peterbell10 @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by eellison** [comment]
Fixed now that the cudagraphs backend is switched to cudagraph trees.
