### ISSUE TITLE
cache torch.compile graphs on disk to avoid recompilation

### ISSUE THREAD

**Issue by vatsalaggarwal** [pytorch/pytorch#122395]
### 🚀 The feature, motivation and pitch

Running inference with minimal changes, but have to run torch.compile every time... especially painful in max. tuning modes.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by jansel** [comment]
cc @oulgen @Chillee @aorenste @masnesral 

This seems related to some of the compile time optimization proposals.

**Comment by Chillee** [comment]
https://github.com/pytorch/pytorch/issues/122540

I'd note that there already exists an Inductor code cache (`torch._inductor.config.fx_graph_cache`) that skips the Inductor component of compilation
