### ISSUE TITLE
DISABLED test_conversions_backend_cutlass_cuda_bfloat16 (__main__.TestSparseSemiStructuredCUDA)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#122384]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22test_sparse_semi_structured.py%3A%3ATestSparseSemiStructuredCUDA%3A%3Atest_conversions_backend_cutlass_cuda_bfloat16%22%5D)).

Guessing it might have been this PR to break ROCm: https://github.com/pytorch/pytorch/pull/121768

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by huydhn** [comment]
The change has been reverted
