### ISSUE TITLE
some official docker images has nccl error for DDP

### ISSUE THREAD

**Issue by yzbx** [pytorch/pytorch#122301]
### 🐛 Describe the bug

docker pull pytorch/pytorch:2.2.1-cuda11.8-cudnn8-devel
or 
docker pull pytorch/pytorch:2.1.2-cuda11.8-cudnn8-devel

run some training code with deepspeed, use 4 x 8 x A800 
(I test the same training code with other docker images, it works well)

## error message 

[rank21]: [E ProcessGroupNCCL.cpp:537] Some NCCL operations have failed or time out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data
NCCL version 2.19.3 
ncclRemoteERror: A call failed possibly due to a network error or a remote process exting prematurely
NET/IB : Got completion from peer 192.168.xxx.xxx<40846> with error 5, opcode 0, len 5, vendor err 249 (Recv) localGid

### Versions

# requirements.txt

```
transformers==4.37.2
tokenizers==0.15.1
sentencepiece==0.1.99
shortuuid
accelerate==0.21.0
peft
bitsandbytes
pydantic
markdown2[all]
numpy
scikit-learn==1.2.2
gradio==4.16.0
gradio_client==0.8.1
requests
httpx==0.24.0
uvicorn
fastapi
einops==0.6.1
einops-exts==0.0.4
timm==0.6.13
deepspeed==0.12.6
ninja
tensorboardX
```

## install lastest flash-attention==2.5.6
- pip install flash-attn --no-build-isolation 

## host machines 
cuda driver version: 525.105.17 
cuda version: 12.0

## training code 
https://github.com/haotian-liu/LLaVA/blob/main/scripts/finetune.sh

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

**Comment by malfet** [comment]
@yzbx can you please post docker image version where the same code works for you (I.e. I wonder if this could be due to the nccl version difference between the two)

**Comment by yzbx** [comment]
> @yzbx can you please post docker image version where the same code works for you (I.e. I wonder if this could be due to the nccl version difference between the two)

I'm sorry, the "worked" docker image before also not work when finetune now, I will check other reasons from hard devices and network, thanks for your help.

**Comment by 913871734** [comment]
> > @yzbx can you please post docker image version where the same code works for you (I.e. I wonder if this could be due to the nccl version difference between the two)
> 
> I'm sorry, the "worked" docker image before also not work when finetune now, I will check other reasons from hard devices and network, thanks for your help.

hello, I met the same question as your issue, have you found out the root reason finally?
