### ISSUE TITLE
How To Correctly Kill MultiProcesses During Multi-GPU Training

### ISSUE THREAD

**Issue by catalystfrank** [pytorch/pytorch#1223]
During the training of using github.com/pytorch/examples/imagenet/main.py, I used the following command:

    CUDA_VISIBLE_DEVICES=0,1,2,3 nohup python main.py [options] path/to/imagenetdir 1>a.log 2>a.err &

Then it starts 5 processes in the system, 1 main process appears in nvidia-smi.

Most of the Time (90% of the time) after I first kill the main process, GPU usage down to 0% so I can kill the other 4 to release GPU Mem to start a new training task. Sometimes (10% of the time), after I killed these 5 processes, the main process remained to be "python [defunct]" that cannot be killed even by sudo kill -s 9. The usage of GPU AND the GPU mem are not released.

Multi-gpu training happened at where I use the following line in my code:

    model = torch.nn.DataParallel(model).cuda()

Please give some hint on "how to correctly kill multi-gpu training pytorch process[es]."

Thanks.

**Comment by Cadene** [comment]
You should try tmux or screen.
I find it better than nohup.
Tmux is a terminal multiplexer. If you close your current terminal, the processus will keep running. You can access back with `tmux a`.
It is easier to kill a processus than nohup. You can kill it using CTRL+C.
Sometimes it happens that one processus keep running on a GPU. I simply kill it with `kill -9 pid`. It works perfectly well on my computer.

**Comment by catalystfrank** [comment]
@Cadene Thank you I will try this out.

**Comment by apaszke** [comment]
It's unfortunately how Python multiprocessing works. If close it too aggressively it leaves a lot of orphans that you have to stop yourself.

I don't know what `python [defunct]` means in `nvidia-smi`. @ngimel maybe you do? Is it another nccl feature?

**Comment by catalystfrank** [comment]
So does one have ideas about how can perform ColorAugmentation() in pytorch? Any unmerged PR or fork is OK. Thanks in advance.

**Comment by catalystfrank** [comment]
@apaszke I mean python [defunct] appeared in "ps aux"

**Comment by Spandan-Madan** [comment]
This is a big issue and pretty much everyone in my research lab is facing it currently. Any new leads on this? @apaszke Would you mind re-opening this to start some discussion on this?

Thanks!

**Comment by SsnL** [comment]
@Spandan-Madan Hey, I know we talked a bit on forum. But I still don't quite understand how this can happen. Could you post some more details? Things I am interested to know are PyTorch version used, and whether this is a single process or multiprocess training and, if the latter, whether CUDA context is created in each process. Concretely, this may include: whether distributed training is used, whehter DataLoader workers are used, whether the dataset return CUDA tensors, etc.

**Comment by elgalu** [comment]
@Spandan-Madan did you solve this problem?
