### ISSUE TITLE
There is a performance drop because we have not yet implemented the batching rule for aten::native_dropout_backward. Please file us an issue on GitHub so that we can prioritize its implementation

### ISSUE THREAD

**Issue by yedidyakfir** [pytorch/pytorch#122432]
### 🚀 The feature, motivation and pitch

I got this error

> There is a performance drop because we have not yet implemented the batching rule for aten::native_dropout_backward. Please file us an issue on GitHub so that we can prioritize its implementation

As requested, I ask you to prioritize this issue, creating a batching rule for dropout.
I am using vmap and jacrev on module with dropout layer

cc @zou3519 @Chillee @samdow @kshitij12345

**Comment by vultix** [comment]
I've also been seeing this when using the [TorchJD](https://torchjd.org/) library

**Comment by zou3519** [comment]
@guilhermeleobas want to take this one?
