### ISSUE TITLE
torch.special.erfcx outputs incorrect result for infinity value

### ISSUE THREAD

**Issue by drewshark** [pytorch/pytorch#122426]
### 🐛 Describe the bug

Given an infinity value, torch.special.erfcx is expected to output NaN since an inf * 0 occurs in the formula defined in the documentation https://pytorch.org/docs/stable/special.html#torch.special.erfcx
erfcx(x)=exp(x**2)*erfc(x) = exp(inf)*0 = inf*0 = NaN

Here is the code to reproduce:
```
import torch
import numpy as np

input = torch.tensor([np.inf], dtype=torch.float64)
part1 = torch.exp(input ** 2)  # tensor([inf], dtype=torch.float64)
part2 = torch.special.erfc(input)  # tensor([0.], dtype=torch.float64)

expected = part1 * part2  # expected result: tensor([nan], dtype=torch.float64)

actual = torch.special.erfcx(input)  # actual result: tensor([0.], dtype=torch.float64)
```

### Versions

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          64
On-line CPU(s) list:             0-63
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen Threadripper PRO 3975WX 32-Cores
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     4368.1641
CPU min MHz:                     2200.0000
BogoMIPS:                        7000.47
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es
Virtualization:                  AMD-V
L1d cache:                       1 MiB (32 instances)
L1i cache:                       1 MiB (32 instances)
L2 cache:                        16 MiB (32 instances)
L3 cache:                        128 MiB (8 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] torch==2.2.1
[pip3] triton==2.2.0
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] torch                     2.2.1                    pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

cc @mruberry @kshitij12345

**Comment by soulitzer** [comment]
I think 0 is correct. e.g.,https://www.wolframalpha.com/input?i=limit+erfcx%28x%29+as+x+approaches+infinity.
