### ISSUE TITLE
Mergebot should send a cleaner message when `[no ci]` message added to the PR commit

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#122407]
### 🐛 Describe the bug

See https://github.com/pytorch/pytorch/pull/122028 where bot says 
> The author doesn't have permissions to run the required trunk workflow since they do not have approvals, aborting merge. Please get/give approval for the workflows before merging again. If you think this is a mistake, please contact PyTorch Dev Infra.

But the actual problem is that commit (but not PR title) contains `[skipci]` decorator, see https://github.com/spzala/pytorch/commit/789ddb7f47acb317fd5ef4af45c292e7090e6e55

### Versions

CI

cc @ZainRizvi @kit1980 @huydhn @clee2000

**Comment by spzala** [comment]
Thank you for clarifying the error message and reporting @malfet !! I was puzzled on what could be wrong. I had used `[skip ci]` in the past (as it's recommended when CI not needed) without any issue so didn't think that was a problem. Thanks much again!!

**Comment by spzala** [comment]
Oh, I see why this wasn't an issue in the past because CI running didn't always required approval then :)

**Comment by malfet** [comment]
> I had used `[skip ci]` in the past (as it's recommended when CI not needed) without any issue so didn't think that was a problem. 

@spzala to give some context, `skip ci` is fine to use for pure docs changes (say to .md files), but it's important to run CI if RST files are changed, to make sure that Sphinx will render them correctly as HTML files

**Comment by spzala** [comment]
> > I had used `[skip ci]` in the past (as it's recommended when CI not needed) without any issue so didn't think that was a problem.
> 
> @spzala to give some context, `skip ci` is fine to use for pure docs changes (say to .md files), but it's important to run CI if RST files are changed, to make sure that Sphinx will render them correctly as HTML files

That's helpful. Thanks @malfet !!

**Comment by malfet** [comment]
Keeping this issue open to just discuss what the UX should be (as `skip ci` indeed make PRs unmergeable from OSS contributors)
