### ISSUE TITLE
Gemma model is failing to run with Dynamo on CPU

### ISSUE THREAD

**Issue by dbabokin** [pytorch/pytorch#122448]
### 🐛 Describe the bug

The model: https://github.com/google/gemma_pytorch
To enable Dynamo I'm adding `@torch.compile()` (assuming cpu backend) annotation to [this line](https://github.com/google/gemma_pytorch/blob/cf8658c186255379194ba5b62612321eacde1b6b/gemma/model.py#L455).

Here's how I'm running it:
```
python ./scripts/run.py --ckpt=<path_to_downloaded_weights>/gemma-2b-it.ckpt --variant="2b" --prompt="Tell me a story: "
```

It it passing with PyTorch `v2.2.1`, but fails with later versions, including top of the trunk.

### Error logs

```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: RuntimeError: Tensor must have a stride divisible by 2 for all but last dimension
  target: aten.view_as_complex.default
  args[0]: TensorBox(StorageBox(
    ConcatKernel(name='buf16', layout=FixedLayout('cpu', torch.float32, size=[1, 1, 1, 128, 2], stride=(256, 1, 256, 2, 1)), inputs=[ComputedBuffer(name='buf14', layout=AliasedLayout('cpu', torch.float32, size=[1, 1, 1, 128, 1], stride=[256, 1, 256, 2, 1]), data=Pointwise(
      'cpu',
      torch.float32,
      def inner_fn(index):
          _, _, _, i3, _ = index
          tmp0 = ops.load(buf2, 2048 + i3)
          return tmp0
      ,
      ranges=[1, 1, 1, 128, 1],
      origin_node=None,
      origins={cat_2}
    )), ComputedBuffer(name='buf15', layout=AliasedLayout('cpu', torch.float32, size=[1, 1, 1, 128, 1], stride=[256, 1, 256, 2, 1]), data=Pointwise(
      'cpu',
      torch.float32,
      def inner_fn(index):
          _, _, _, i3, _ = index
          tmp0 = ops.load(buf2, 2176 + i3)
          return tmp0
      ,
      ranges=[1, 1, 1, 128, 1],
      origin_node=None,
      origins={cat_2}
    ))])
  ))
```

### Minified repro

I failed to minify the model. I got this error running minifier:

```
Traceback (most recent call last):
  File ".../gemma_pytorch/torch_compile_debug/run_2024_03_21_15_51_16_163671-pid_59659/minifier/minifier_launcher.py", line 1885, in <module>
    mod = Repro()
          ^^^^^^^
  File ".../gemma_pytorch/torch_compile_debug/run_2024_03_21_15_51_16_163671-pid_59659/minifier/minifier_launcher.py", line 27, in __init__
    self.register_buffer('L__self___freqs_cis', torch.randint(1, size=[16384, 128], dtype=torch.complex64))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: check_random_bounds handles only integral, floating-point and boolean types
```

I assume it's not exactly what expected to the result of minifier run. But it might be related to the root cause, as it's also complains on the complex type, which is present in the original error (i.e. `aten.view_as_complex.default`).

### Versions

Collecting environment information...
PyTorch version: 2.3.0a0+git36e118b
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.3.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.28.1
Libc version: N/A

Python version: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] (64-bit runtime)
Python platform: macOS-14.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.10.0
[pip3] torch==2.4.0a0+gitd131cbc
[conda] Could not collect

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @amjames @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @desertfire

**Comment by jansel** [comment]
Possibly related to another Gemma issue: #122340

**Comment by dbabokin** [comment]
Here's reduced example:
```python
import torch
from torch import _dynamo as torchdynamo

@torchdynamo.optimize()
def reduce_example(x: torch.Tensor) -> torch.Tensor:
    """Applies the rotary embedding to the query and key tensors."""
    x_out = torch.view_as_complex(
        torch.stack(torch.chunk(x.float(), 2, dim=-1),
                    dim=-1))
    return x_out
for _ in range(100):
    reduce_example(torch.randn(1,1,1,256))
```

**Comment by dbabokin** [comment]
The stride is constructed in [make_channels_last_3d_strides_for](https://github.com/pytorch/pytorch/blob/0288fa7caeb70a6cdcd19ca97b61c06842c2eccf/torch/_prims_common/__init__.py#L1648) during lowering of `aten.cat` operator.

The function get `shape = [1, 1, 1, 128, 2]` and returns `[256, 1, 256, 2, 1]`. This seems incorrect.

**Comment by dbabokin** [comment]
What really happens, that triggered this regressions, is that PR https://github.com/pytorch/pytorch/pull/118453 disabled `poitwise_cat` on CPU, which worked correctly. So `aten.cat` is now lowered by [ir.ConcatKernel.create()](https://github.com/pytorch/pytorch/blob/66e61af467ada93998e15d505bdfa84976c4e793/torch/_inductor/ir.py#L3693), which doesn't handle this case correctly.

The logic for `ir.ConcatKernel.create()` broken, as it detects last-channel layout, while it's just continuous. And that's what triggers execution of `make_channels_last_3d_strides_for`, which actually does incorrect thing for continuous layout.

**Comment by jansel** [comment]
@dbabokin I'd expect the strides passed to `torch.view_as_complex` to be fixed by the `require_contiguous` here:
https://github.com/pytorch/pytorch/blob/26a9b05bcef33a45eb2e5d449a616e4119c5edca/torch/_inductor/lowering.py#L2040
https://github.com/pytorch/pytorch/blob/26a9b05bcef33a45eb2e5d449a616e4119c5edca/torch/_inductor/lowering.py#L1813-L1817

This will either mutate the layout of the producing op (in the case of FlexibleLayout) or introduce a copy to force contiguous strides.  

Though perhaps we should change that to be:
https://github.com/pytorch/pytorch/blob/26a9b05bcef33a45eb2e5d449a616e4119c5edca/torch/_inductor/lowering.py#L1827
Which forces the layout to match eager mode and might be more correct.

What error are you seeing with that smaller repro?

**Comment by dbabokin** [comment]
> What error are you seeing with that smaller repro?

I'm executing on macOS, so it's executed on CPU. And Dynamo crashes like this. I have exactly the same error when trying to run Google Gemma model.

```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: RuntimeError: Tensor must have a stride divisible by 2 for all but last dimension
  target: aten.view_as_complex.default
  args[0]: TensorBox(StorageBox(
    ConcatKernel(name='buf2', layout=FixedLayout('cpu', torch.float32, size=[1, 1, 1, 128, 2], stride=(256, 1, 256, 2, 1)), inputs=[ComputedBuffer(name='buf0', layout=NonOwningLayout('cpu', torch.float32, size=[1, 1, 1, 128, 1], stride=[256, 1, 256, 2, 1]), data=Pointwise(
      'cpu',
      torch.float32,
      def inner_fn(index):
          _, _, _, i3, _ = index
          tmp0 = ops.load(arg0_1, i3)
          return tmp0
      ,
      ranges=[1, 1, 1, 128, 1],
      origin_node=None,
      origins={cat}
    )), ComputedBuffer(name='buf1', layout=NonOwningLayout('cpu', torch.float32, size=[1, 1, 1, 128, 1], stride=[256, 1, 256, 2, 1]), data=Pointwise(
      'cpu',
      torch.float32,
      def inner_fn(index):
          _, _, _, i3, _ = index
          tmp0 = ops.load(arg1_1, i3)
          return tmp0
      ,
      ranges=[1, 1, 1, 128, 1],
      origin_node=None,
      origins={cat}
    ))])
  ))
```

**Comment by dbabokin** [comment]
> I'd expect the strides passed to `torch.view_as_complex` to be fixed by the `require_contiguous` here

I'm not an expert here, but the `stride=[256, 1, 256, 2, 1]` looks to me incorrect in the first place. It's not technically incorrect, as long as the size on "broken" dimension is 1 anyway (size=[1, 1, 1, 128, 1]). But the lowering seems to make assumptions that are not really correct, assuming that it's channel-last 3d layout, while it's just 5d tensor with continuous layout.

There are good chances that I misunderstand this though :)

**Comment by jansel** [comment]
The strides of the `size=1` dimensions shouldn't matter (since it is only ever multiplied by 0), though I think this is a case where the "convert to channels last" logic is too aggressive.

This PR fixes the smaller repro:
https://github.com/pytorch/pytorch/pull/123758

**Comment by dbabokin** [comment]
@jansel I checked that #123758 solves the original problem with Gemma model, not just small reproducer.

**Comment by lezcano** [comment]
Closing as https://github.com/pytorch/pytorch/pull/123758 was merged. Feel free to reopen if the problem persists.
