### ISSUE TITLE
MPS: Implement index_select() on complex value

### ISSUE THREAD

**Issue by maruel** [pytorch/pytorch#122427]
### 🐛 Describe the bug

The exception is thrown by the call here when using device "mps";

https://github.com/google/gemma_pytorch/blob/acd24a81ecbb9ee3bb90771a0c517c7f6b6ce528/gemma/model.py#L426

precompute_freqs_cis() at line 84 generates a complex via torch.polar().

This is the assert that triggers:
https://github.com/pytorch/pytorch/blob/d131cbc44f2d8bbe5b0e154480bb2ed7f789abd8/aten/src/ATen/native/mps/operations/Indexing.mm#L605
```
TORCH_CHECK(!self.is_complex(), "index_select(): Yet not supported for complex");
```

Here's a simpler repro case:
```
import torch

p = torch.polar(torch.ones_like(torch.empty(2, 3)), torch.empty(2, 3))
p.index_select(0, torch.arange(0, 2, dtype=torch.int64).to("mps"))
```

### Versions

Tested on today's nightly torch-2.4.0.dev20240321.

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @amjames @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by maruel** [comment]
As a notebook: https://github.com/maruel/ml/blob/48d8a22e1f7208c1b2e6c13fd00bc27bb97f7eaf/notebooks/gemma/issue_122427.ipynb

**Comment by malfet** [comment]
Grabbing for myself, I guess all it takes is just removing the restriction (and enabling OpInfo testing)

**Comment by maruel** [comment]
Thanks a lot @malfet!
@pengchongjin and @michaelmoynihan may be interested to hear about this.

**Comment by pengchongjin** [comment]
Nice, this helps! Look forward to the fix!

**Comment by TomasAndersonFang** [comment]
Hi @malfet,

I tested the same code on torch-2.4.0.dev20240527 but got another error. Is it a bug?

```
RuntimeError: Placeholder storage has not been allocated on MPS device!
```
