### ISSUE TITLE
'torch.nn' has no attribute 'TripletMarginLoss'

### ISSUE THREAD

**Issue by bartolsthoorn** [pytorch/pytorch#1224]
Calling
```python
triplet_loss = nn.TripletMarginLoss()
```
results in:
```
AttributeError: module 'torch.nn' has no attribute 'TripletMarginLoss'
```
even with
```python
import torch.nn as nn
```
Related PR that added introduced TripletMarginLoss: #1165 

Work-around for now is to use `F.triplet_margin_loss` directly, where `F` is `import torch.nn.functional as F`.

**Comment by apaszke** [comment]
Another workaround would be to add `from torch.nn.modules.loss import TripletMarginLoss`.

**Comment by soumith** [comment]
fixed in master. will be in next release.

**Comment by D-X-Y** [comment]
Hi, similar thing happens when I call nn.Upsample

**Comment by muhanzhang** [comment]
Hi, there is the same issue with nn.BCEWithLogitsLoss. The source file nn/modules/loss.py does not contain it.
