### ISSUE TITLE
Memory leak in python dispatcher

### ISSUE THREAD

**Issue by gbonik** [pytorch/pytorch#122417]
### 🐛 Describe the bug

Hi, the following example leaks memory, as observed by watching the infinitely growing memory use in `top` while the script is running:
```
import torch
from torch.utils._python_dispatch import TorchDispatchMode
from torch._dispatch.python import enable_python_dispatcher

class Mode(TorchDispatchMode):
    def __torch_dispatch__(self, *args, **kwargs):
        return None

with enable_python_dispatcher(), Mode():
    while True:
        torch.ones(3, 4)
```
I believe it is caused by this line in `csrc/jit/python/pybind_utils.cpp`/ `toPyObject(IValue ivalue)`:
```
return py::cast<py::object>(THPDevice_New(std::move(ivalue).toDevice()));
```
THPDevice_New() returns a fresh object with refcount of 1, and `py::cast` adds another reference, creating an imbalance. It seems that `py::cast` should be changed to `py::reinterpret_steal`. (I haven't built Torch from source and thus haven't verified this theory but I'm 99% certain from my investigation with gdb).

### Versions

I have torch==2.1.0 with Python 3.10.13. I've also reproduced it with 2.2.x, and I believe the bug is still there at the tip of main.

cc @Chillee @ezyang @zou3519 @albanD @samdow

**Comment by tringwald** [comment]
Thanks for the bug report and the detailed analysis. I can confirm that this leaks on latest `main` and that the proposed change fixes the problem.
