### ISSUE TITLE
compile: mutations under no_grad might not be included in the graph when they are on aliases

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#122436]
Simple repro (came from tracing ppFSDP work):
```
        def f(a):
            a_alias = a.view(-1)
            with torch.no_grad():
                a_alias.mul_(2)
            return a + 1
        inp = torch.ones(4, requires_grad=True)
        out = torch.compile(f)(inp)
```

Running this with `TORCH_LOGS="aot", you will se that there is not a `copy_()` in the graph - this means that it is hidden outside of the graph, and run in an opaque runtime epilogue.

This mutations should be safe to include in the graph - since it is under no_grad, no autograd metadata needs to be updated (except for the version counter of a, which AOTAutograd handles today directly).

cc @ezyang @msaroufim @anijain2305 @zou3519 @chauhang

**Comment by jansel** [comment]
@bdhirsh are you planning to look at this one?  Or could you suggest someone who could?
