### ISSUE TITLE
OSError: anaconda/envs/voice2/lib/python3.8/site-packages/torch/lib/../../../../libmkl_intel_lp64.so: undefined symbol: LAPACKE_ztgevc_work

### ISSUE THREAD

**Issue by zijiner** [pytorch/pytorch#122466]
### 🐛 Describe the bug

"I encountered an issue as titled, despite repeatedly reinstalling Torch, it still doesn't work."

### Versions

torch vision is 2.2.1

**Comment by soulitzer** [comment]
Issues are for bugs and features only. Feel to ask questions on the forums https://discuss.pytorch.org/.
