### ISSUE TITLE
Document torch.Tensor legacy constructor

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#122408]
### 🐛 Describe the bug

James March was showing me this video from Andrej https://youtu.be/PaCmpygFfXo?si=FqM0AlZdvm9gK9kK&t=4074 where he was complaining that there is no docs saying what the difference between torch.Tensor and torch.tensor is. Since we're never getting rid of torch.Tensor, it would be good documenting it and telling people not to use it.

cc @svekars @brycebortree @albanD @soumith 

### Versions

main

**Comment by Gaurav0203Shetty** [comment]
i'll do this.
