### ISSUE TITLE
[RFC] Autoload Device Extension

### ISSUE THREAD

**Issue by jgong5** [pytorch/pytorch#122468]
### 🚀 The feature, motivation and pitch

co-authors:
Intel: @jgong5 @bsochack @sujoysaraswati @gujinghui @xiaodonglin1
Huawei: @yikun @hipudding

PyTorch has been continuously expanding its support for various hardware backend devices, extending its reach to out-of-the-tree devices which are usually implemented with PyTorch extensions. However, a notable challenge arises with the current approach: users must explicitly load the these out-of-the-tree device extension to gain the new device support. This manual loading not only complicates the user experience but also introduces unnecessary cognitive overhead.

The core issue lies in the discrepancy between the handling of in-tree and out-of-tree devices. While in-tree devices seamlessly integrate into the PyTorch ecosystem, out-of-the-tree devices require additional steps for loading on top of the standard PyTorch device programming model. Our goal with this proposal is to bridge this gap, ensuring that out-of-the-tree devices are as user-friendly and seamlessly integrated as their in-tree counterparts. (Note that we only focus on the Python-based programs in the RFC. C++ applications can also be linked with the native device extensions and automatic loading is taken care of by the loader.)
Specifically, our objectives are twofold:
1. Enable users to adhere to the familiar PyTorch device programming model without the need for explicit loading or importing of device-specific extensions.
2. Facilitate effortless adoption of existing PyTorch applications with zero-code changes on out-of-the-tree devices.

## Examples
In the section, we use Intel Gaudi and Huawei Ascend, two representative out-of-the-tree devices, to demonstrate the problem with current usages and expected ones.
### Intel Gaudi
Let’s take a look at the following PyTorch program that runs on Intel Gaudi via the PyTorch HPU device key. Users need to import “[habana_frameworks.torch](https://docs.habana.ai/en/latest/PyTorch/Getting_Started_with_PyTorch_and_Gaudi/Getting_Started_with_PyTorch.html)” to load the extension support for HPU.

```python
import torch
import torchvision.models as models
import habana_frameworks.torch # <-- extra import
model = models.resnet50().eval().to(“hpu”)
input = torch.rand(128, 3, 224, 224).to(“hpu”)
output = model(input)

```
With the proposal, the additional import of “habana_frameworks.torch” is not necessary and the code follows the standard PyTorch device programming model, i.e., moving the input and model parameters to the device followed by the forward call etc.
```python
import torch
import torchvision.models as models
model = models.resnet50().eval().to(“hpu”)
input = torch.rand(128, 3, 224, 224).to(“hpu”)
output = model(input)

```
The standard way of programming brings benefit in that users even don’t have to change the code that invovles moving the tensors to the target device in applications with good device abstraction, e.g., the device name is passed as an argument to the program. This proposal allows users to use new devices without the need of changing code.
Even in some cases where the applications have hard-coded calls to CUDA runtime functions, there is also solution to automatically migrating the code to the new devices. For example, the Habana PyTorch bridge supports “[automatic GPU migration](https://docs.habana.ai/en/latest/PyTorch/PyTorch_Model_Porting/GPU_Migration_Toolkit/GPU_Migration_Toolkit.html#using-gpu-migration-toolkit)” so that the PyTorch programs written for the NVidia CUDA device doesn’t need to be changed to work with the Intel Gaudi HPU device. This is achieved by an additional import with “gpu_migration” module.

```python
import torch
import torchvision.models as models
import habana_frameworks.torch # <-- extra import
import habana_frameworks.torch.gpu_migration # <-- extra import
model = models.resnet50().eval().to(“cuda”)
input = torch.rand(128, 3, 224, 224).to(“cuda”)
output = model(input)

```
With the proposal, the device specific imports are not necessary and users can run the existing code without any code changes.
```python
import torch
import torchvision.models as models
model = models.resnet50().eval().to(“cuda”)
input = torch.rand(128, 3, 224, 224).to(“cuda”)
output = model(input)

```
### Huawei Ascend
Similar to Intel Gaudi, users need to import “[torch_npu](https://github.com/Ascend/pytorch)” to load the device extension support for Huawei Ascend. Internally, Huawei Ascend leverages the “PrivateUse1” device key and exposes the device name as “npu” to the end users. We use Ascend as an example for out-of-the-tree devices that don’t have in-tree device keys but leverage [“PrivateUse1” device key for integration](https://pytorch.org/tutorials/advanced/privateuseone.html).
```python
import torch
import torchvision.models as models
import torch_npu # <-- extra import (install npu to PrivateUse1 etc.)
model = models.resnet50().eval().to(“npu”)
input = torch.rand(128, 3, 224, 224).to(“npu”)
output = model(input)

```
With the proposal, the expected usage is similar – users don’t have to import “torch_npu” explicitly.
```python
import torch
import torchvision.models as models
model = models.resnet50().eval().to(“npu”)
input = torch.rand(128, 3, 224, 224).to(“npu”)
output = model(input)

```
The comments on the zero-code change enabling also apply to Huawei Ascend.

## Proposed Solution
We propose three options below. For the sake of simplicity, option 3 is most preferrable.
### Option 1: Module preloading
Inspired by the `LD_PRELOAD` mechanism in Unix-like operating systems, we propose to introduce a similar `TORCH_PRELOAD` environment variable to specify a list of Python modules to be loaded during the initialization of PyTorch core. The preloaded modules are specified as follows:
`TORCH_PRELOAD=module1:module2:module3...`
Take Intel Gaudi as an example, one would specify:
`TORCH_PRELOAD=habana_frameworks.torch`
or
`TORCH_PRELOAD=habana_frameworks.torch:habana_frameworks.torch.gpu_migration`
For Huawei Ascend, one would do:
`TORCH_PRELOAD=torch_npu`
For situations where configuration files are more preferred over environment variables. We can have a JSON configuration file: `torch_preload.json` like below:
`[“module1”, “module2”, “module3”]`
The module preloading is triggered in `torch/__init__.py`. The configuration file can be placed in a pre-defined place (e.g., `site-packages/torch_config/torch_preload.json`), installed by the device extensions, or overridden by users, and for `torch/__init__.py` to find.

- Pros: Intuitive for users experienced with Unix-like systems to understand and use. Allows loading multiple modules/extensions at once. Provides flexibility to users to load any desired module.
- Cons: Users can use this mechanism for other purposes than device extension loading, which might introduce confliction.

### Option 2: Device extension specific configuration
This option proposes a specialized configuration for loading the device extension via environment variable `TORCH_DEVICE_EXT` and configuration file `torch_device_extension.json`.
`TORCH_DEVICE_EXT=device_key:device_name:module1:module2:module3...`
`torch_device_extension.json`:
```json
{
  "device_key": "device_name",
  "modules": ["module1", "module2", "module3"]
}
```
The module preloading is triggered in `torch/__init__.py`. The configuration file can be placed in a pre-defined place (e.g., `site-packages/torch_config/torch_device_extension.json`), installed by the device extensions, or overridden by users, and for `torch/__init__.py` to find.

- Pros: Dedicated configuration for loading device extensions without potential confliction with other purposes like option 1.  Leave flexibility for PyTorch core to take device extension specific actions when loading the modules.
- Cons: More complex configuration compared to Option 1.

### Option 3: Load from a pre-defined module as plugin
This option proposes to use a pre-defined module, e.g., `torch_plugins_device_extension`, for loading out-of-the-tree device extensions. It leverages the python plugin mechanism: https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/#using-package-metadata.
An entrypoint is added to the PyTorch package like below:
```
[project.entry-points.'torch.plugins']
device_extension = 'torch_plugins_device_extension'
```
The module is loaded from `torch/__init__.py` as illustrated below:
```python
from importlib.metadata import entry_points
discovered_plugins = entry_points(group='torch.plugins')
for plugin in discovered_plugins:
    try:
        plugin.load()
    except IndexError:
        pass
```
This module is installed by the python package of the device vendor, e.g., `habana_frameworks` for Intel Gaudi or `torch_npu` for Huawei Ascend, to `site-packages/torch_plugins_device_extension` and the `torch_plugins_device_extension/__init__.py` import the corresponding vendor-specific device extension modules.

- Pros: Flexible import and configuration via Python. Simpler configuration and interface to PyTorch.
- Cons: Lack of flexibility for users to customize the loading process.

**Comment by jgong5** [comment]
cc @ezyang @albanD @malfet for feedbacks.

**Comment by ezyang** [comment]
I'm just not that sympathetic to "oh no, I don't want an extra import". Like, obviously they had to install your extension to get access to it in the first place, is adding one more little import really that much trouble?

If you are going to do this, I think the correct thing to use is https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/#using-package-metadata

**Comment by vadimkantorov** [comment]
There also exists `site.py` mechanism in Python which allows to add pre-imports in a separate file: https://docs.python.org/3/library/site.html, although it would probably try execute these imports before `import torch`

**Comment by jgong5** [comment]
> I'm just not that sympathetic to "oh no, I don't want an extra import". Like, obviously they had to install your extension to get access to it in the first place, is adding one more little import really that much trouble?

Thanks @ezyang for the question. An extra import does bring more trouble than the installation. Note that for advanced users, neither installation nor importing would bring them a lot of trouble. We are primarily taking care of the ordinary users or new users. The installation is a one-time deal and usually be automated with some standard installation scripts (e.g., `pip -r requirements.txt`) without the need of knowing what to install. On the other hand, importing has to be done per model code basis, would be a burden to users if not standardized.

> If you are going to do this, I think the correct thing to use is https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/#using-package-metadata

Thanks for the suggestion. Make sense. So, on top of option 3, we would add an entrypoint to the PyTorch package like below:
```toml
[project.entry-points.'torch.plugins']
device_extension = 'torch_plugins_device_extension'
```
And then, load the plugins in `torch/__init__.py` like below:
```python
from importlib.metadata import entry_points
discovered_plugins = entry_points(group='torch.plugins')
for plugin in discovered_plugins:
    try:
        plugin.load()
    except IndexError:
        pass
```
Does that match what you thought?

**Comment by jgong5** [comment]
> There also exists `site.py` mechanism in Python which allows to add pre-imports in a separate file: https://docs.python.org/3/library/site.html, although it would probably try execute these imports before `import torch`

Thanks @vadimkantorov for the suggestion. Yes, this seems to be global, which means `torch` will also be pre-imported globally too since it would be a dependency of the extensions.

**Comment by vadimkantorov** [comment]
> Thanks @vadimkantorov for the suggestion. Yes, this seems to be global, which means `torch` will also be pre-imported globally too since it would be a dependency of the extensions.

I guess, `site.py` is also somewhat for advanced users and it would also require either `import torch` in `site.py` or also some `import torchplugins` core module which would allow to do plugin lazy-registration without actually importing/initializing full torch

**Comment by ezyang** [comment]
> On the other hand, importing has to be done per model code basis, would be a burden to users if not standardized.

But they have to change their model anyway to use your new device, no?

**Comment by jgong5** [comment]
> > On the other hand, importing has to be done per model code basis, would be a burden to users if not standardized.
> 
> But they have to change their model anyway to use your new device, no?

Not always. Many model scripts are designed to be device-agnostic, e.g., the device can be passed in as an argument to the launch script without need of changing the model script. Also, the device extensions like `habana_frameworks.torch` has the GPU migration tool `habana_frameworks.torch.gpu_migration`, when imported, can act as the CUDA device. So it is possible to also autoload this migration tool with this proposal to avoid additional model code changes (see the example in the proposal for more details).

Even if the additional model changes are required to use the new device, it is harder to remember the vendor specific import than following the standard PyTorch device programming model to apply the model changes.

**Comment by awaelchli** [comment]
If this was included, it would be great if this didn't impact import times too much. Also, if I understand correctly, this would import the dependency even if I'm not going to use the device/accelerator in my PyTorch program at all?

**Comment by hipudding** [comment]
Yes, as @jgong5 said, not all model scripts need hardware adaptation. Torch can load backend plugins, which essentially gives more flexibility to hardware accelerator vendors. These vendors can decide how to patch or perform CUDA migration. The goal for these vendors is to enable acceleration without modifying any model scripts.

@awaelchli, generally speaking, different backend accelerators won't be used at the same time, so at most one hardware extension is imported, which doesn't significantly impact the import time. Moreover, when these devices/accelerators are not needed, you can use another pyenv environment or uninstall the devices/accelerators plugin, avoiding any extra imports.
and of course, lazy loading is a good choice.

**Comment by ezyang** [comment]
@albanD has been pushing on the heterogenous compute. It's not "here" yet, but it's a lot more likely than it was in the past.

**Comment by jgong5** [comment]
> @albanD has been pushing on the heterogenous compute. It's not "here" yet, but it's a lot more likely than it was in the past.

Will this direction guide towards a common device programming model that allows users to write device-agnostic code in the frontend? For example, avoid the need to hard-code device-specific functions like `torch.cuda.xyz` in the frontend code? Then, with the autoloading proposal, out-of-the-tree devices can reuse existing code as is.

**Comment by jgong5** [comment]
I have revised option 3 to incorporate @ezyang 's suggestion. Are we fine to go with option 3? @ezyang @albanD cc @soumith

**Comment by cdzhan** [comment]
I'm working on #124058, it would be really helpful if we could support autoloading.

**Comment by GuWei007** [comment]
I encountered the same problem

**Comment by brothergomez** [comment]
This is almost certainly outside of the scope of this RFC, but I have come across some similar issues when working with inductor and backends that require device extensions. 

As with the above examples the user is required to `import my_extension` before doing a `torch.compile` call which I am happy to accept as a reasonable adjustment to user code. However the code generated by inductor does _not_ include these extra imports, so will not run. E.g. the "wrapper" C++ code that inductor generates, or the Triton routines that are generated. Currently I have a workaround to adjust the generated code, but it would be nice to have something more robust.  

I believe the 3 proposed solutions would also work with the generated code created by inductor?

**Comment by ezyang** [comment]
Yes, because if your package was installed, torch would automatically have imported it on load.

**Comment by albanD** [comment]
The proposal here is definitely more scoped for eager backends infrasstructure but I see the similarity.
I think the two options I would see are:
- We need to fix inductor python code to have the appropriate imports all the time there
- Have a similar plugin-based strategy to allow inductor to auto-import these extensions

I think the best next step here would be to open an inductor specific issue so that the team there can give opinion on which one is best for them.

**Comment by jgong5** [comment]
> The proposal here is definitely more scoped for eager backends infrasstructure but I see the similarity.

Assuming that the generated code would also import torch, would the device extension be autoloaded as well? Or are we talking about something different?

**Comment by brothergomez** [comment]
> Assuming that the generated code would also import torch, would the device extension be autoloaded as well? Or are we talking about something different?

Yes, the inductor issue is out of scope for this RFC, but the solutions above with autoloading would also fix that issue as well as the `import torch` in the auto-gen'd scripts would autoload the device extension as well.

**Comment by albanD** [comment]
> Assuming that the generated code would also import torch, would the device extension be autoloaded as well? Or are we talking about something different?

It depends if the eager device extension is the same as the inductor device extension. If they are the same, then yes what we discussed here will be enough. If they are different and an extension is only an inductor extension (not an eager one), then we would need some inductor-specific resolution.

**Comment by gujinghui** [comment]
Will we cover C++ API in libtorch scenario?
If user application is going to leverage a third_party extension library only for customized kernels, Autoload should be helpful to preload the third_party library?
