### ISSUE TITLE
There is a comment error in test_transformers.py

### ISSUE THREAD

**Issue by 1274085042** [pytorch/pytorch#122594]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/blob/main/test/test_transformers.py#L1437
The comment does not match the name of test case  

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki
### Versions
torch version == main

**Comment by mikaylagawarecki** [comment]
Feel free to send a PR removing this comment or updating it appropriately
