### ISSUE TITLE
Docs list incorrect parameter name for torch.cat

### ISSUE THREAD

**Issue by wongjoel** [pytorch/pytorch#12251]
## 📚 Documentation

Torch version 0.4.0

[Documentation](
https://pytorch.org/docs/stable/torch.html?highlight=cat#torch.cat) lists signature as `torch.cat(seq, dim=0, out=None) → Tensor`
Signature is actually `torch.cat(tensors, dim=0, out=None) → Tensor`

Example REPL output:
```python
import torch
x = torch.randn(2, 3)
torch.cat(seq=[x, x, x], dim=0)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: cat() missing 1 required positional arguments: "tensors"

torch.cat(tensors=[x, x, x], dim=0)
tensor([[-0.6263,  0.2296, -1.2178],
        [ 1.0056, -1.3435,  0.2011],
        [-0.6263,  0.2296, -1.2178],
        [ 1.0056, -1.3435,  0.2011],
        [-0.6263,  0.2296, -1.2178],
        [ 1.0056, -1.3435,  0.2011]])
```

**Comment by greed2411** [comment]
+1, 0.4.1 version of pytorch works the same way as above.

[Documentaion of master branch](https://pytorch.org/docs/master/torch.html?highlight=torch%20cat#torch.cat) tells the same

https://github.com/pytorch/pytorch/blob/ecb3835387e4f5b7f8bfacc1b4d14aeaf687aecd/torch/_torch_docs.py#L741

I guess thats where it needs to be changed.

**Comment by greed2411** [comment]
@zou3519 is it okay, if I fix it in the mentioned place and send a PR?

**Comment by zou3519** [comment]
1Oh yes, feel free to send a patch @greed2411!
