### ISSUE TITLE
Feature Request: Add dilate to ConvTranspose functions

### ISSUE THREAD

**Issue by jgbos** [pytorch/pytorch#1225]
Any possibility of adding dilatation to transpose convolutions?

**Comment by soumith** [comment]
this should be possible. We could do this.

**Comment by jgbos** [comment]
Thanks.  Looking through `functional.py` it appears that you may just need to add a `dilation` parameter (currently just set to 1).  I'm sure there is some issues to address wrt the transpose though, and of course testing.

**Comment by soumith** [comment]
@ezyang an easy task for you. give it a try. Ask me if you need pointers.
