### ISSUE TITLE
FSDP `summon_full_params` not working when called with submodules

### ISSUE THREAD

**Issue by realAsma** [pytorch/pytorch#122663]
### 🐛 Describe the bug

Pytorch API documentation on FSDP  `summon_full_params` [here](https://pytorch.org/docs/stable/fsdp.html#torch.distributed.fsdp.FullyShardedDataParallel.summon_full_params) says:
"It can take a non-FSDP module and will summon full params for all contained FSDP modules as well as their children, depending on the recurse argument."

However I find that `summon_full_params` only works if called from the top-level FSDP wrapped model. `summon_full_params` on an FSDP submodule or non-FSDP submodule does not give the unsharded parameters.

Here is the code to reproduce this bug:

```
     model = nn.Sequential(
        nn.Sequential(nn.Linear(1024, 1024), nn.Linear(1024, 1024)),
        nn.Sequential(nn.Linear(1024, 1024), nn.Linear(1024, 1024)),
    ).cuda(local_rank)

    model = FSDP(model, auto_wrap_policy=ModuleWrapPolicy((nn.Sequential,)))

    with FSDP.summon_full_params(model):
        for name, parameter in model.named_parameters():
            if local_rank == 0:
                print(
                    f"parameters after summon at model level: {name}, {parameter} {parameter.shape}, {parameter.dtype}"
                )
                # Output as expected. Example output:
                # parameters after summon at model level: 1.0.bias, Parameter containing:
                # tensor([ 0.0255, -0.0242, -0.0002,  ..., -0.0274, -0.0112,  0.0277],
                # device='cuda:0', requires_grad=True) torch.Size([1024]), torch.float32

    fsdp_submodule = model._fsdp_wrapped_module[0]
    with FSDP.summon_full_params(fsdp_submodule):
        for name, parameter in fsdp_submodule.named_parameters():
            if local_rank == 0:
                print(
                    f"parameters after summon at fsdp submodule level: {name}, {parameter} {parameter.shape}, {parameter.dtype}"
                )
                # Output show unsharded parameters. output:
                # parameters after summon at fsdp submodule level: _fsdp_wrapped_module._flat_param, Parameter containing:
                # tensor([ 0.0064, -0.0256,  0.0226,  ..., -0.0021, -0.0267, -0.0056],
                # device='cuda:0', requires_grad=True) torch.Size([1049600]), torch.float32

    non_fsdp_submodule = fsdp_submodule._fsdp_wrapped_module[0]
    with FSDP.summon_full_params(non_fsdp_submodule):
        for name, parameter in non_fsdp_submodule.named_parameters():
            if local_rank == 0:
                print(
                    f"parameters after summon at non-fsdp submodule level: {name}, {parameter} {parameter.shape}, {parameter.dtype}"
                )
                # Output: Does not print anything.

```

### Versions

```
[pip3] numpy==1.26.4
[pip3] torch==2.4.0.dev20240318+cu118
[pip3] torchaudio==2.2.0.dev20240318+cu118
[pip3] torchvision==0.18.0.dev20240318+cu118
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.4.0.dev20240318+cu118          pypi_0    pypi
[conda] torchaudio                2.2.0.dev20240318+cu118          pypi_0    pypi
[conda] torchvision               0.18.0.dev20240318+cu118          pypi_0    pypi
```

cc @zhaojuanmao @mrshenli @rohan-varma @awgu @fegin @penguinwu @kwen2501 @chauhang

**Comment by awgu** [comment]
Sorry for the delay!

It looks like we incorrectly only consider root FSDP modules:
https://github.com/pytorch/pytorch/blob/2a137f7af1973092b967d1f2916227e7a2f946bf/torch/distributed/fsdp/_unshard_param_utils.py#L309
As a result, when passing in a non-root (like `fsdp_submodule`), the logic because a no-op.

The fix might be to change the logic to (1) look for root FSDP modules first and (2) if none, then check if the passed-in module is an FSDP module and use that if so. (1) handles the case where the user passes in a non-FSDP module that contains 1+ root FSDP modules, and (2) handles the case in this Github issue.

**Comment by realAsma** [comment]
> Sorry for the delay!
> 
> It looks like we incorrectly only consider root FSDP modules:
> 
> https://github.com/pytorch/pytorch/blob/2a137f7af1973092b967d1f2916227e7a2f946bf/torch/distributed/fsdp/_unshard_param_utils.py#L309
> 
> 
> As a result, when passing in a non-root (like `fsdp_submodule`), the logic because a no-op.
> The fix might be to change the logic to (1) look for root FSDP modules first and (2) if none, then check if the passed-in module is an FSDP module and use that if so. (1) handles the case where the user passes in a non-FSDP module that contains 1+ root FSDP modules, and (2) handles the case in this Github issue.

@awgu Thanks for the reply. In the proposed solution, "(1) look for root FSDP modules first", Should we look for the closest parent which is an FSDP sumodule? 

If we use the root module instead, summoning the entire parameters of the root module might cause OOM. Summoning the parameters of the closest FSDP submodule should not cause OOM.

**Comment by awgu** [comment]
I think (1) is to preserve the existing behavior and documented API. It should not affect your case if I understand correctly.

Regardless, the logic will only ever look "downward" from a module toward submodules because `nn.Module` does not offer any way to look "upward" at parent modules.

**Comment by realAsma** [comment]
> I think (1) is to preserve the existing behavior and documented API. It should not affect your case if I understand correctly.
> 
> Regardless, the logic will only ever look "downward" from a module toward submodules because `nn.Module` does not offer any way to look "upward" at parent modules.

Thank you for the clarification.  
I have 2 more questions about this fix.

**1. [This fix](https://github.com/pytorch/pytorch/issues/122663#issuecomment-2027540370) will not work for non-FSDP modules with non-root FSDP child modules, is that correct?**

According to the documentation, this case is supported (as it does not mention that the non-FSDP module should contain root FSDP child modules for `summon_full_params` to work).  Is that correct? 

**2. "the logic will only ever look "downward" from a module ":**

This make sense.  I was assuming that `summon_full_params` will work for modules which does not have an FSDP child submodule but is part of an FSDP module (For example an `nn.Linear` module with a parent FSDP module, but none of the module or its child modules are FSDP module).  

I feel the documentation is ambiguous about what to expect if the module have no FSDP submodule. Should we update the documentation clarifying this?

**Comment by awgu** [comment]
> I was assuming that summon_full_params will work for modules which does not have an FSDP child submodule but is part of an FSDP module (For example an nn.Linear module with a parent FSDP module, but none of the module or its child modules are FSDP module).

Unfortunately, I think this assumption is not true. The issue is that this FSDP implementation constructs 1 `FlatParameter` (a 1D tensor) out of all parameters in the FSDP module. As such, there is not a way to all-gather the parameters for just a submodule of an FSDP module without all-gathering _all_ parameters of that FSDP module.

IIUC, this also answers your first question about non-FSDP modules with non-root FSDP child modules. Let me know if it does not. (I totally agree that our documentation is incorrect and misleading currently.)

I was thinking maybe we should see if we can just all-gather parameters for any FSDP module in the `module.modules()` for `summon_full_params(module)`, regardless of root or non-root.

**Comment by realAsma** [comment]
> I was thinking maybe we should see if we can just all-gather parameters for any FSDP module in the `module.modules()` for `summon_full_params(module)`, regardless of root or non-root.

Thanks that makes sense.

"I was thinking maybe we should see if we can just all-gather parameters for any FSDP module in the module.modules() for summon_full_params(module), regardless of root or non-root." -> this seems to me like a nice solution. It will be great if we can have this. Thank you!
