### ISSUE TITLE
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

### ISSUE THREAD

**Issue by NiharJani2002** [pytorch/pytorch#122602]
### 🐛 Describe the bug

Code:
def nii_to_tensor(filename):
    # Load NIfTI file
    img = nibabel.load(filename)
    
    # Get the data array from the NIfTI image
    img_data = img.get_fdata()
    
    # Convert the data array to a PyTorch tensor
    tensor = torch.tensor(img_data).type(torch.float64)
    
    return tensor.to('mps')

Image of the Error:
<img width="1649" alt="image" src="https://github.com/pytorch/pytorch/assets/84491997/913a9c6a-a148-4391-b114-9f91955c862e">

### Versions

(BRATS) niharjani@Nihars-MacBook-Pro ~ % conda list

# packages in environment at /Users/niharjani/Desktop/MiniCondaInstall/miniconda3/envs/BRATS:
#
# Name                    Version                   Build  Channel
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
blas                      1.0                    openblas  
brotli-python             1.0.9           py312h313beb8_7  
bzip2                     1.0.8                h93a5062_5    conda-forge
ca-certificates           2024.3.11            hca03da5_0  
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
charset-normalizer        2.0.4              pyhd3eb1b0_0  
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
debugpy                   1.8.1           py312h20a0b95_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                hebf3989_0    conda-forge
filelock                  3.13.1          py312hca03da5_0  
freetype                  2.12.1               h1192e45_0  
fsspec                    2024.3.1                 pypi_0    pypi
hopfield-layers           1.0.2                    pypi_0    pypi
idna                      3.4             py312hca03da5_0  
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
ipykernel                 6.29.3             pyh3cd1d5f_0    conda-forge
ipython                   8.22.2             pyh707e725_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.3           py312hca03da5_0  
jpeg                      9e                   h80987f9_1  
jupyter_client            8.6.1              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py312h81bd7bf_0    conda-forge
lcms2                     2.12                 hba8e193_0  
lerc                      3.0                  hc377ac9_0  
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.17                 h80987f9_1  
libexpat                  2.6.2                hebf3989_0    conda-forge
libffi                    3.4.4                hca03da5_0  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libjpeg-turbo             2.0.0                h1a28f6b_0  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.45.2               h091b4b1_0    conda-forge
libtiff                   4.5.1                h313beb8_0  
libwebp-base              1.3.2                h80987f9_0  
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               14.0.6               hc6e5704_0  
lz4-c                     1.9.4                h313beb8_0  
markupsafe                2.1.3           py312h80987f9_0  
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mpmath                    1.3.0           py312hca03da5_0  
ncurses                   6.4.20240210         h078ce10_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.1             py312hca03da5_0  
nibabel                   5.2.1                    pypi_0    pypi
numpy                     1.26.4          py312h7f4fdc5_0  
numpy-base                1.26.4          py312he047099_0  
openjpeg                  2.3.0                h7a6adac_2  
openssl                   3.2.1                h0d3ecfb_1    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.1                    pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.2.0          py312h80987f9_0  
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
psutil                    5.9.8           py312he37b823_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1           py312hca03da5_0  
python                    3.12.2          hdf0ec26_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-graphviz           0.20.3                   pypi_0    pypi
python_abi                3.12                    4_cp312    conda-forge
pytorch                   2.4.0.dev20240320        py3.12_0    pytorch-nightly
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1           py312h80987f9_0  
pyzmq                     25.1.2          py312h1edf716_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
requests                  2.31.0          py312hca03da5_1  
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.45.2               hf2abe2d_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
sympy                     1.12            py312hca03da5_0  
tk                        8.6.13               h5083fa2_1    conda-forge
torchaudio                2.2.0.dev20240320       py312_cpu    pytorch-nightly
torchvision               0.19.0.dev20240320       py312_cpu    pytorch-nightly
torchviz                  0.0.2                    pypi_0    pypi
tornado                   6.4             py312he37b823_0    conda-forge
traitlets                 5.14.2             pyhd8ed1ab_0    conda-forge
typing_extensions         4.10.0             pyha770c72_0    conda-forge
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.1.0           py312hca03da5_1  
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_0    conda-forge
xz                        5.4.6                h80987f9_0  
yaml                      0.2.5                h1a28f6b_0  
zeromq                    4.3.5                hebf3989_1    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zstd                      1.5.5    

<img width="1715" alt="image" src="https://github.com/pytorch/pytorch/assets/84491997/38150981-2ef7-4c9d-8c4a-4261ae83dde5">

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by malfet** [comment]
Closing as an expected behavior and known limitaiton, see https://developer.apple.com/documentation/metalperformanceshaders/mpsdatatype?language=objc
