### ISSUE TITLE
Incremental build

### ISSUE THREAD

**Issue by KyleFromKitware** [pytorch/pytorch#12264]
## 🐛 Bug

In version 0.4.1, I was able to do an incremental build by doing:

```
python setup.py bdist_wheel -d some/directory/for/wheel
```

This would do the entire build once, and then if I ran it again, it would keep all of the build files and take a lot less time than the first build.

But now, running this command twice causes at least a significant portion of Pytorch to be built again on the second round.

## To Reproduce

1. Clone the latest Pytorch
2. `python setup.py bdist_wheel -d some/directory/for/wheel # Run the first build, which builds the whole package`
3. `python setup.py bdist_wheel -d some/directory/for/wheel # Run the build again, should do incremental build`

## Expected behavior

I expected Pytorch to do an incremental build the second time I ran the build command. Instead, it rebuilt all (or most) of Pytorch, taking a lot longer than I expected.

## Environment

 - PyTorch Version (e.g., 1.0): Git commit 93ecf4d7
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py bdist_wheel
 - Python version: 2.7
 - CUDA/cuDNN version: 8.0, 6.0.21
 - GPU models and configuration: GeForce GTX 1080 Ti
 - Any other relevant information:

## Additional context

We are using Pytorch as part of a superbuild, and it would be nice to have incremental builds of Pytorch again.

**Comment by soumith** [comment]
@KyleFromKitware we're trying to unscrew this, it's a side-effect of various cmake file issues that crept up into our build. Will keep you updated.

**Comment by ngimel** [comment]
closing due to age
