### ISSUE TITLE
CuDNN Attention Kernel _scaled_dot_product_cudnn_attention unable to run.

### ISSUE THREAD

**Issue by MoFHeka** [pytorch/pytorch#122695]
### 🐛 Describe the bug

```bash
>>> import torch
>>> t1=torch.randn(1,4,4096,128).to("cuda").to(torch.float16)
>>> torch._scaled_dot_product_cudnn_attention(t1, t1, t1, dropout_p=0.0, is_causal=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: mha_graph->execute(handle, variant_pack, workspace_ptr.get()).is_good() INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1711266070736/work/aten/src/ATen/native/cudnn/MHA.cpp":410, please report a bug to PyTorch.
```

### Versions

The nightly images in A100 machine.

docker pull ghcr.io/pytorch/pytorch-nightly:2.4.0.dev20240325-cuda12.1-cudnn8-devel

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by drisspg** [comment]
The CuDnn backend is not ready for use yet, it will
be exposed through the top level sdpa when it is.

**Comment by MoFHeka** [comment]
So when can we use it? Any roadmap?

**Comment by drisspg** [comment]
https://github.com/pytorch/pytorch/issues/113713

cc @eqy

**Comment by MoFHeka** [comment]
Is there any way to benchmark the forward performance? I want to do a simple end-to-end performance comparison with other attention implementations with PyTorch frontend.

**Comment by eqy** [comment]
Thanks for forwarding the failure, I'll take to look to see what cuDNN constraint was violated.
In the meantime you should be able to benchmark the forward pass with supported shapes with e.g.,
```
import torch                                                                                                                                                    [3/1789]import time

causal = False
b = 32
s = 512
count = 0
while True:
    for h, d in zip((32, 16), (64, 128)):
        q, k, v = torch.randn(b, s, h*d*3, dtype=torch.bfloat16, device='cuda', requires_grad=True).chunk(3, dim=-1)
        q = q.view(b, -1, h, d).transpose(1, 2)
        k = k.view(b, -1, h, d).transpose(1, 2)
        v = v.view(b, -1, h, d).transpose(1, 2)
        with torch.no_grad():
            for i in range(5):
                out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, is_causal=causal)
            torch.cuda.synchronize()
            t1 = time.perf_counter()
            out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, is_causal=causal)
            torch.cuda.synchronize()
            t2 = time.perf_counter()
        print(f"{(b, s, h, d)} {t2-t1}")

    if b > 1:
        b //= 2
    s *= 2
    if s > 131072:
       break

**Comment by MoFHeka** [comment]
wait a minute (1,4,4096,128) is not a available shape? Which b=1, head_num=4, seq_len=4096, head_dim=128.

**Comment by eqy** [comment]
I picked semi-arbitrary numbers in the benchmark script, feel free to experiment with your own and report back if something doesn't work; from the cuDNN docs
```
    All tensors must be either FP16 or BF16 data type.
    Contracting dimension for Q must be a multiple of 8 with maximum value 128
    Non-contracting dimension for V must be a multiple of 8 with maximum value 128.
    Contracting dimension for Q and K^T needs to have stride 1 in the layout.
    Non-contracting dimension for V needs to have stride 1 in the layout.
    The second dimension in K^T corresponding to the number of heads can be a factor of the number of heads of Q.
    The second dimension in V corresponding to the number of heads can be a factor of the number of heads of Q.

```

**Comment by MoFHeka** [comment]
@eqy I've used the latest NGC image and installed pytorch nightly, and it doesn't work. Did your test confirm that an environment variable "TORCH_CUDNN_SDPA_ENABLED=1" was added?

**Comment by MoFHeka** [comment]
@eqy I've used the latest NGC image and installed pytorch nightly, and the script you provided still doesn't work. Are you sure you added environment variables "TORCH_CUDNN_SDPA_ENABLED=1" during testing?

**Comment by eqy** [comment]
@MoFHeka the latest NGC might still be missing some fixes e.g., https://github.com/pytorch/pytorch/pull/120750
I can see the warning in my own testing, but I'm using a source build.

Basically the issue is that I'm not sure the nightlies have a version of cuDNN that is new enough (what does `torch.backends.cudnn.version()` show for you)? Whereas the source build in the containers might be too old. If it's not too involved, would you consider doing a source build in an NGC container?

**Comment by MoFHeka** [comment]
@eqy I'm not sure what are the best performance build parameters for building Nvidia pytorch? Could you please provide a build script if it is convenient? In addition, I have seen some Nvidia projects upload nightly CI images to the public cloud, and it would be great if you could provide a test image directly.

**Comment by eqy** [comment]
@MoFHeka 
the `python setup.py install` flow should get you most of the way there, the only real suggestion would be adding e.g., `TORCH_CUDA_ARCH_LIST=yourcomputecapability` to avoid building for unnecessary compute capabilities

**Comment by MoFHeka** [comment]
@eqy I have tested cudnn attention in A30 with image nvcr.io/nvidia/pytorch:24.04-py3. In common dimensions such as batch_size=1, sequence_length=4096, num_heads=64, heads_per_dim=128, it is half as slow as flash attention in the same image.
Are there any method to improve performance?

**Comment by drisspg** [comment]
I am going to close this since I don think this still relevant

**Comment by bhattronak** [comment]
```
# PyTorch's cuDNN fused-MHA SDPA backend has a known internal-assertion defect on some
# shape/attention-mask combinations (e.g. multi-image inputs), which surfaces as:
#   RuntimeError: Expected mha_graph.execute(...).is_good() to be true, but got false.
# See https://github.com/pytorch/pytorch/issues/122695 and
# https://github.com/pytorch/pytorch/issues/134001. Disable it so SDPA falls back to the
# flash-attention / memory-efficient / math backends, which remain fast and don't hit this bug.
```
torch.backends.cuda.enable_cudnn_sdp(False)

this has resolved it
