### ISSUE TITLE
Slow CUDA initialization with 1.0 Preview

### ISSUE THREAD

**Issue by denjots** [pytorch/pytorch#12275]
## 🐛 Bug

The initial call to model.cuda() takes several minutes to finish on a Quadro GV100. It seems similar to previous issues e.g. #5205. Titan X Pascal works fine - as does the GV100 when running Pytorch 0.4.1.
All installs were using miniconda environment:
conda install pytorch-nightly cuda92 -c pytorch

## Environment

PyTorch version: 1.0.0.dev20181002
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration:
GPU 0: Quadro GV100
GPU 1: TITAN X (Pascal)

Nvidia driver version: 410.57
cuDNN version: Probably one of the following:
/usr/local/cuda-7.5/lib64/libcudnn.so.5.1.10
/usr/local/cuda-7.5/lib64/libcudnn.so.5.1.3
/usr/local/cuda-7.5/lib64/libcudnn_static.a
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn_static.a

**Comment by ezyang** [comment]
Hi @denjots, a recent report at #12283 was resolved by making sure you had the correct version of magma installed in your application. Can you check if this is the case here?

**Comment by denjots** [comment]
Hi @ezyang - I don't think magma is installed - I just used the binary conda install as per quick start:
conda install pytorch-nightly cuda92 -c pytorch

It was on an "empty" miniconda so no other packages other than the pytorch dependencies were installed.

**Comment by soumith** [comment]
This is indeed a regression to our nightly building script. @pjh5 will be fixing this and closing the issue once it's fixed.

**Comment by pjh5** [comment]
The nightly builds for October 6th, with version 1.0.0.dev20181006 will have the fix, and should be uploaded by 9 a.m. PST tomorrow. I will check to make sure everything looks good then, and update here.

**Comment by pjh5** [comment]
I think the binaries for the 6th should now have the correct arch list
