### ISSUE TITLE
[Windows] Exception in Torch.Multiprocessing.Queue

### ISSUE THREAD

**Issue by sanctifier** [pytorch/pytorch#12276]
## Issue description
I want to train multiple CNN models individually on multiple GPUs installed in a single PC. Once the training is finished, the models are expected to be returned to the main thread.  

I employed torch.multiprocessing to implement this. Namely, I defined a CNN class inherited from nn.Module and the associated train(), test() methods for asynchronous calls. 

The CNN aims at MNIST dataset for test purpose.  The models and the MNIST built-in dataloaders are all initialized before torch.multiprocessing is invoked. 

Torch.multiprocessing creates Process object hooking train() and its arguments, i.e., model, GPU, dataloader and a queue of class torch.multiprocessing.Queue. 

In train(), the trained model is pushed to the queue by "queue.put(model)". 

In main(), the model is retrieved from queue by "model=queue.get()" once all training completed. 

However, the statement "model=queue.get()" triggers "AttributeError: Can't get attribute 'CNN' on <module 'ptvsd.__main__' ...>"

## Code example
    import time
    import torch 
    import torch.nn as nn
    import torchvision
    import torchvision.datasets as dsets
    import torchvision.transforms as transforms
    import torch.nn.functional as F
    import torch.multiprocessing as mp

    print(torch.__version__)
    print(torchvision.__version__)

    # MNIST Dataset
    train_dataset = dsets.MNIST(root='./Mnist_data/',                 
                                train=True,                     
                                transform=transforms.ToTensor(),
                                download=True)                  

    test_dataset = dsets.MNIST(root='./Mnist_data/',                  
                            train=False,                     
                            transform=transforms.ToTensor())

    train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                            batch_size=200, 
                                            shuffle=True)

    test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                            batch_size=200, 
                                            shuffle=False)
    # CNN Model (2 conv layer)
    class CNN(nn.Module):
        def __init__(self):
            super(CNN, self).__init__()
            self.layer1 = nn.Sequential(
                nn.Conv2d(1, 16, kernel_size=5, padding=2),
                nn.BatchNorm2d(16),
                nn.ReLU(),
                nn.MaxPool2d(2))
            self.layer2 = nn.Sequential(
                nn.Conv2d(16, 32, kernel_size=5, padding=2),
                nn.BatchNorm2d(32),
                nn.ReLU(),
                nn.MaxPool2d(2))
            self.fc = nn.Linear(7*7*32, 10)
            
        def forward(self, x):
            out = self.layer1(x)
            out = self.layer2(out)
            out = out.view(out.size(0), -1)
            out = self.fc(out)
            return out 

    assert torch.cuda.is_available()

    torch.backends.cudnn.benchmark=True

    GPU_COUNT = torch.cuda.device_count()

    GPUs = []
    for index in range(GPU_COUNT):
        GPUs.append(torch.device(f'cuda:{index}'))

    def train(model, GPU, train_loader, queue):
        num_epochs = 1    
        learning_rate = 0.01

        model.cuda(device=GPU)
        model.train()        
        # Loss and Optimizer
        criterion = nn.CrossEntropyLoss()
        optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
            
        # Train the Model
        info = '\n'
        start = time.time()     
        for epoch in range(num_epochs):
            correct = 0
            total = 0   
            for i, (images, labels) in enumerate(train_loader):                      
                # Forward + Backward + Optimize
                optimizer.zero_grad()
                outputs = model(images.cuda(device=GPU))
                loss = criterion(outputs, labels.cuda(device=GPU))
                loss.backward()
                optimizer.step()
                
                if (i+1) % 100 == 0:
                    _, predicted = torch.max(outputs.data, 1)
                    total += labels.size(0)
                    correct += (predicted.cpu() == labels).sum()
                    info = info + f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4}, ACC: {float(100*correct/total):.4}\n'
            torch.cuda.empty_cache()
            
        info = info + f'time elapsed: {time.time()-start}\n' 
        print(info)
        model.cpu()
        queue.put(model)    

    def test(model, GPU, test_loader): 
        model.cuda(device=GPU)
        # Test the Model
        correct = 0
        total = 0
        for images, labels in test_loader:  
            outputs = model(images.cuda(device=GPU))
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted.cpu() == labels).sum()  
        info = f'Test Accuracy of the model on the test images: {float(100 * correct / total):.4}'
        return info 

    # training and test
    if __name__ == "__main__":
        models = []
        for _ in range(GPU_COUNT):
            model = CNN()        
            model.cpu()
            model.share_memory()
            models.append(model)

        # parallel processing    
        start = time.time()
        processes = []
        queue = mp.Queue()
        for GPU in GPUs:
            p = mp.Process(target=train, args=(models[index], GPU, train_loader, queue))
            p.start()
            processes.append(p)
        for p in processes:
            p.join()                    
        print(f'Total Time elapsed: {int(time.time() - start)}s')

        index = 0
        while not queue.empty():
            model = queue.get()
            output = test(model, GPUs[index], test_loader)
            print(output)
            index = index + 1

Error messages:
Exception has occurred: AttributeError
Can't get attribute 'CNN' on <module 'ptvsd.__main__' from 'c:\\Users\\Administrator\\.vscode\\extensions\\ms-python.python-2018.8.0\\pythonFiles\\experimental\\ptvsd\\ptvsd\\__main__.py'>

## System Info

- PyTorch or Caffe2:  PyTorch 
- How you installed PyTorch (conda, pip, source):  "conda install pytorch cuda91"
- Build command you used (if compiling from source): 
- OS: Windows 10 Home Edition
- PyTorch version: 0.4.1
- Python version:  3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
- CUDA/cuDNN version: 9.1.85/7005
- GPU models and configuration: GPU 0 = GeForce GTX 1060
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries: torchvision (0.2.1)

**Comment by peterjc123** [comment]
@sanctifier I can't see any interaction between the code and the `ptvsd` module. How are they linked together?

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by peterjc123** [comment]
Although the above problem is not easy to solve, we can actually avoid it by combining the train and test function and return the output instead. In that way, it will work without problem.

**Comment by sanctifier** [comment]
> Although I don't have a multi-GPU server, the code fails with the following error:
> 
> ```
> Traceback (most recent call last):
>   File ".\test.py", line 137, in <module>
>     model = queue.get()
>   File "multiprocessing\queues.py", line 113, in get
>     return _ForkingPickler.loads(res)
>   File "torch\multiprocessing\reductions.py", line 167, in rebuild_storage_filename
>     storage = cls._new_shared_filename(manager, handle, size)
> RuntimeError: Couldn't open shared event: <torch_21084_2878318007_event>, error code: <2>
> ```
> 
> Looks like it is missing in sth like #5585. We only considered the transmit of the tensors but that of the models was left behind.

Thank you for your kind reply.
Now I know I mistakenly used Torch.Multiprocessing.Queue.
I will change code to return tensors rather than models, thus this is not an issue anymore.
