### ISSUE TITLE
[Windows] Does nn.DataParallel work in Pytorch 1.0?

### ISSUE THREAD

**Issue by sanctifier** [pytorch/pytorch#12277]
I have a server of motherboard ASUS WS X299 SAGE installed with 4 GPUs and Pytorch 0.4.1.

Unfortunately, this motherboard does **NOT** officially support Ubuntu. When I contacted ASUS to find a motherboard capable of 4 GPUs, intel CPU and Ubuntu, I got response "None exists" and "even if you can install Ubuntu on  ASUS WS X299 SAGE, there are no official drivers for Ubuntu".

Therefore, I installed Windows Workstation Edition instead and attempted to run a code snippet involving nn.DataParallel to fully employ multiple GPU power. However, I got an error stated that pytorch on Windows is not compiled with NCCL, then I searched NCCL document of installation and sadly found NCCL does **NOT** support Windows. 

Finally, I attempt to implement multiple models trained in multiple GPUs through torch.multiprocessing, and again, an error pops up when the models are retrieved from individual threads through torch.multiprocessing.queue. This issue is reported in [https://github.com/pytorch/pytorch/issues/12276](here).

So, did you make nn.DataParallel work in Pytorch 1.0 for multiple-GPU server of Windows OS?

Or can you tell me how to install Ubuntu in server of motherboard ASUS WS X299 SAGE? (I updated bios to the latest version and tried Ubuntu 18.04 but failed)

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by ngimel** [comment]
Closing due to age
