### ISSUE TITLE
Less error prone way of ensuring Inductor cache is disabled when doing local development on Inductor

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#122891]
### 🐛 Describe the bug

I recently spent half an hour debugging because I added a breakpoint to inductor, ran a PyTorch unit test, and scratched my head when seemingly the breakpoint wasn't being called at all. Well, the reason was because I had a warm cache and was hitting the cache entry instead.

I'm not sure what I'd suggest. It would be nice if the cache knew to automatically invalidate itself when PyTorch code itself changes, but that might be difficult to implement efficiently. A convenient way to force runs without hitting cache would help maybe.

cc @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @masnesral 

### Versions

main

**Comment by masnesral** [comment]
@ezyang we're talking about the on-disk FX graph cache, correct? If so, then we already include all .py under torch/_inductor/ in the key calculation: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/codecache.py#L493-L510. So adding a breakpoint _should_ effectively invalidate the cache. Was the breakpoint at a different path?

**Comment by ezyang** [comment]
Yeah, I think it was in torch/_inductor/utils.py or something. That's weird though. I close this for now then and reopen if I have a repro.
