### ISSUE TITLE
Takes 5 minutes to get back from .cuda()

### ISSUE THREAD

**Issue by jiaanguo** [pytorch/pytorch#12283]
## 🐛 Bug

It takes several (around 5) minutes to run `torch.tensor([0.]).cuda()` for the first time. After that, there isn't any problems calling cuda(). 

My configuration has 2 RTX 2080s in SLI and a GTX 1070. The GTX 1070 does not have any problem, while both RTX 2080s have the slow cuda() initialisation problem.

I also tested both pytorch 0.4.1 and 1.0 preview on cuda 10.0.130, driver version 410.57, the problem persists.

## To Reproduce

1. import torch
2. torch.tensor([0.]).cuda()

## Expected behavior

expect `torch.tensor([0.]).cuda()` to reply immediately after issuing.

## Environment

 - PyTorch Version (e.g., 1.0): 0.4.1, 1.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): conda install pytorch-nightly -c pytorch
 - Build command you used (if compiling from source):
 - Python version: 3.6.5
 - Nvidia driver verison: 410.57
 - CUDA/cuDNN version: 10.0.130
 - GPU models and configuration: 2 * RTX 2080 in SLI + GTX 1070
 - Any other relevant information:

**Comment by jiaanguo** [comment]
By investigating the issue using nvidia-smi.
We can see the memory allocated on GPU is growing very slowly.
1 minute after
|    0      9960      C   python                                       169MiB |
3 minute after
|    0      9960      C   python                                       487MiB |
5 minute after (finished)
|    0      9960      C   python                                       707MiB |

**Comment by jiaanguo** [comment]
Fixed my issue by building from source without `magma-cuda92`, That part doesn't update to cuda 10 which causes the problem. This issues can be closed.

**Comment by ezyang** [comment]
This is a pretty big footgun. See also #3990
