### ISSUE TITLE
Import torch causes error

### ISSUE THREAD

**Issue by wddabc** [pytorch/pytorch#1228]
This might be relevant to #691. I have installed pytorch from source on Mac OS successfully, but `import torch` causes error:
> 
>
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-c031d3dd82fc> in <module>()
> ----> 1 import torch
> 
> /Users/dqwang/Study/tools/anaconda2/lib/python2.7/site-packages/torch/__init__.pyc in <module>()
>      51 sys.setdlopenflags(_dl_flags.RTLD_GLOBAL | _dl_flags.RTLD_NOW)
>      52 
> ---> 53 from torch._C import *
>      54 
>      55 __all__ += [name for name in dir(_C)
> 
> ImportError: dlopen(/Users/dqwang/Study/tools/anaconda2/lib/python2.7/site-packages/torch/_C.so, 10): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
>   Referenced from: /Users/dqwang/Study/tools/anaconda2/lib/python2.7/site-packages/torch/_C.so
>   Expected in: flat namespace
>  in /Users/dqwang/Study/tools/anaconda2/lib/python2.7/site-packages/torch/_C.so
> 
The author of that thread got away with the issue by installing from conda package rather than source, which solved my case as well. But I have to install from the source because of I need CUDA.

**Comment by wddabc** [comment]
The problem comes from the installer picks up the wrong compiler (somehow it picks up the anaconda gcc other than AppleClang). 

Fixed by reinstalling pytorch with `CC=clang CXX=clang++ python setup.py install`. Hints takes from #532.  This should also fix #691.

**Comment by soumith** [comment]
Thanks, I've updated the "From source" instructions to reflect this here: https://github.com/pytorch/pytorch/blob/master/README.md#from-source
