### ISSUE TITLE
Not consistent results when applying linear layer over sequence vs when applying the same layer only one time-step of the sequence 

### ISSUE THREAD

**Issue by dr-costas** [pytorch/pytorch#122889]
### 🐛 Describe the bug

The results different when applying a linear layer over a sequence compared to when applying the same layer over only one time-step of the same sequence. 

You can check the simple code that reproduces the results below. 

```python
In [1]: import torch

In [2]: x = torch.rand(1, 10, 20)

In [3]: l = torch.nn.Linear(20, 5)

In [4]: x1 = l(x)

In [5]: x2 = l(x[:, -1:, :])

In [6]: x2.size()
Out[6]: torch.Size([1, 1, 5])

In [7]: x1.size()
Out[7]: torch.Size([1, 10, 5])

In [8]: x2.eq(x1[:, -1:, :]).all()
Out[8]: tensor(False)

In [9]: x3 = l(x)

In [10]: x3.eq(x1).all()
Out[10]: tensor(True)

In [11]: x3[:, -1:, :].eq(x1[:, -1:, :]).all()
Out[11]: tensor(True)

In [12]: x4 = l(x[:, -2:, :])

In [13]: x4.eq(x1[:, -2:, :]).all()
Out[13]: tensor(True)

```

### Versions

> PyTorch version: 2.1.1
> Is debug build: False
> CUDA used to build PyTorch: None
> ROCM used to build PyTorch: N/A
> 
> OS: macOS 14.4.1 (arm64)
> GCC version: Could not collect
> Clang version: 15.0.0 (clang-1500.3.9.4)
> CMake version: version 3.26.4
> Libc version: N/A
> 
> Python version: 3.9.13 (main, Jan  5 2023, 09:17:42)  [Clang 13.1.6 (clang-1316.0.21.2.5)] (64-bit runtime)
> Python platform: macOS-14.4.1-arm64-arm-64bit
> Is CUDA available: False
> CUDA runtime version: No CUDA
> CUDA_MODULE_LOADING set to: N/A
> GPU models and configuration: No CUDA
> Nvidia driver version: No CUDA
> cuDNN version: No CUDA
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> Is XNNPACK available: True
> 
> CPU:
> Apple M1 Max
> 
> Versions of relevant libraries:
> [pip3] mypy==1.5.1
> [pip3] mypy-extensions==1.0.0
> [pip3] numpy==1.26.2
> [pip3] pytorch-lightning==2.1.2
> [pip3] torch==2.1.1
> [pip3] torch-fidelity==0.3.0
> [pip3] torch-summary==1.4.5
> [pip3] torchaudio==2.1.1
> [pip3] torchmetrics==1.2.0
> [pip3] torchvision==0.16.1
> [conda] nomkl                     3.0                           0  
> [conda] numpy                     1.23.4                   pypi_0    pypi
> [conda] numpydoc                  1.4.0            py39hca03da5_0

**Comment by zou3519** [comment]
This is expected, see https://pytorch.org/docs/stable/notes/numerical_accuracy.html#batched-computations-or-slice-computations (and use torch.allclose to compare instead of .eq)
