### ISSUE TITLE
Make sure pointwise cat still applies on rotary embeddings

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#122871]
### 🚀 The feature, motivation and pitch

Run `python benchmarks/gpt_fast/benchmark.py` (comment out the experiments if you like).

Commenting out this condition improves performance by a couple of tokens/s: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/lowering.py#L1225

cc: @eellison 

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

**Comment by eellison** [comment]
We need to skip pointwise cat if there is a large variation on input shape, instead of skipping on reduction inputs.
