### ISSUE TITLE
[c10d][NCCL] _coalescing_manager does not produce proper work handle

### ISSUE THREAD

**Issue by Aidyn-A** [pytorch/pytorch#122807]
### 🐛 Describe the bug

The list of work objects (`works`) is empty:
```python
    with dist._coalescing_manager(group=pg_nccl, device=device, async_ops=True) as cm:
        dist.all_reduce(a)
        dist.all_reduce(b)
    print(len(cm.works)) # prints 0
    cm.wait()
```
In this situation `cm.wait()` becomes a no-op, which causes red-before-write issues whenever `_coalescing_manager` is used.

### Versions

PyTorch version: 2.4.0.dev20240326+cu121
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/pytorch/pull/122651
- [ ] https://github.com/pytorch/pytorch/pull/122849
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

**Comment by Aidyn-A** [comment]
#123170 does not fix main issue. Could you please try:
```
git clone https://github.com/NVIDIA/apex.git
cd apex
python setup.py develop --deprecated_fused_adam --distributed_adam --cuda_ext
python apex/contrib/test/optimizers/test_dist_adam.py -f
```
It fails with numerical mismatches because it starts to do ops before coalesced communications are over. The PR #122651 effectively fixes the issue, and all the numerical mismatches in the test are gone.
cc @kwen2501

**Comment by kwen2501** [comment]
Hi @Aidyn-A, which issue is the main issue?

I tried the program you paste with #123170 :
```
import torch
import torch.distributed as dist

dist.init_process_group(backend="nccl", timeout=timedelta(seconds=10))
rank = dist.get_rank()
device = torch.device(f"cuda:{rank}")

# Create tensors
s = 100 * 1024 * 1024
with dist._coalescing_manager(device=device, async_ops=True) as cm:
    dist.all_reduce(torch.ones(s, device=device))
    dist.all_reduce(torch.ones(s, device=device))

print(len(cm.works))
cm.wait()
torch.cuda.synchronize()
print(f"{dist.get_rank()} done")
```
The is output I got:
```
NCCL version 2.20.5+cuda12.1
1
1
1 done
0 done
```

**Comment by Aidyn-A** [comment]
The main Issue we are seeing is in apex. 

> #123170 does not fix main issue. @kwen2501, could you please try:
> 
> ```
> git clone https://github.com/NVIDIA/apex.git
> cd apex
> python setup.py develop --deprecated_fused_adam --distributed_adam --cuda_ext
> python apex/contrib/test/optimizers/test_dist_adam.py -f
> ```
> 
> It fails with numerical mismatches because it starts to do ops before coalesced communications are over. The PR #122651 effectively fixes the issue, and all the numerical mismatches in the test are gone.

**Comment by kwen2501** [comment]
In the doc string, there is the following line:
https://github.com/pytorch/pytorch/blob/64d743044dd490f13179f9d608f736a0e9331cad/torch/distributed/distributed_c10d.py#L1970-L1971

Since all_reduce has a "Fast-Path" implementation for coalescing, we previously did not expect users to set the device. But I understand why libraries (like Apex) may want to set it in general. We will think of ways to improve this UI.

**Comment by kwen2501** [comment]
I closed #123170, let's go with #122849 .
Thanks for helping me understand the problem better. And sorry about the noise!

**Comment by Aidyn-A** [comment]
Oh wow, I certainly was not expecting `ncclGroupStart()` be called two times in the row, and that NCCL would not fail. 
One more thing I noticed, Apex is doing broadcast within the coalescing manager. Broadcast does not have a "Fast-Path", why does not it throw this error: https://github.com/pytorch/pytorch/blob/1c614010860c61918825d2095f404d8103c594e2/torch/distributed/distributed_c10d.py#L2032-L2035

**Comment by kwen2501** [comment]
I think a nice goal is to not ask for a "device" and rely on it to do different things. 
I will think more about it.
