### ISSUE TITLE
Cannot install a single package for CUDA and ROCM

### ISSUE THREAD

**Issue by samfux84** [pytorch/pytorch#122880]
### 🐛 Describe the bug

Hi,

The HPC cluster of our university has both, nodes with NVIDIA GPUs and nodes with AMD GPUs (and pure CPU nodes without any GPU). Since pytorch packages provided for CUDA and ROCM are different but have the same name, we can only install one version for each Python installation.

Is there any solution to have both versions installed for the same Python installation? 

Or is there any option to have a single package that can run on CPU, NVIDIA GPUs and AMD GPUs (by detecting the GPU)? The CUDA version can for instance already detect if an NVIDIA GPU is available and will otherwise fallback to the CPU version. So the package can run either on pure CPU nodes without any GPU and also on nodes with NVIDIA GPUs.

Using venvs is not an option, as a user can only have one venv activated at a time. So if we would provide torch through a venv, users could not create their own venvs any more if they would like to use pytorch.

I guess we cannot be the only institution with this problem, so I hope there is already a solution for having both, the ROCM and CUDA version side by side or within a single Python package.

Any help is appreciated.

Best regards

Sam

### Versions

.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
It is not possible to have a single pytorch package with both NVIDIA and AMD/ROCm support.  The ROCm build performs a source-to-source translation ("hipify") before compiling the project and sits behind the same public torch APIs such as torch.cuda.  I understand that this poses a challenge in your environment.  But also consider the packaging challenges even if we had the ability to combine NVIDIA and AMD backends such as which combinations of CUDA and ROCm versions would you want bundled together?

I am confident there must be a way for these two different torch packages to coexist on your platform.  I am aware of users installing multiple different AMD GPUs into the same host, but I was not previously aware of a mixed NVIDIA and AMD GPU environment like yours.  It's not a supported use case to mix both GPU vendors as part of the same workload.

**Comment by samfux84** [comment]
@jeffdaily Thank you for your reply. I somehow expected that currently it is not possible to have both packages available within one Python installation, but hoped that there is a workaround available.

Please note that our hardware setup is not mixing Nvidia and AMD GPUs within the same server. We have servers with Nvidia GPUs and servers with AMD GPUs. So it is not about running pytorch at the same time on GPUs from different vendors. Also within a job, users are not even mixing GPU models. If a job uses multiple GPUs, they are all the same model from the same vendor. The use case would be that a user can submit a job to a node with an Nvidia GPU and then submit another independent job to a node with an AMD GPU.

A very simple solution would be if both packages (pytorch for CUDA and for ROCM) would have different package names. Then both packages could be installed within the same Python version.

I think that our current solution will be to have separate Python installations for CUDA and ROCM. This is not really desirable, as it duplicates the work of installing Python (and we plan to provide multiple versions of Python on our cluster).

Long term, it would be desirable to have a single pytorch package that checks for the GPU type and then uses the appropriate code (Nvidia GPU/ AMD GPU/ Intel or AMD CPU), so that a single installation is sufficient.

Please feel free to close this ticket.

**Comment by hongxiayang** [comment]
I am closing this ticket. Thanks for the discussion.
