### ISSUE TITLE
capi OutputArchive file size grow for cuda tensor.

### ISSUE THREAD

**Issue by Strasser-Pablo** [pytorch/pytorch#12284]
## 🐛 Bug

When saving to file the same tensor. The file size grow.

## To Reproduce

The following c++ code has the problem:

`  auto ten=torch::autograd::make_variable(at::zeros({20,20},at::kCUDA));
    for(int i=0;i<10;++i)
    {
        torch::serialize::OutputArchive OA;
        OA.write("tensor",ten);
        save_to_file(OA,std::string("Cuda")+std::to_string(i));
    }`

The size of the produced files are:
8.0K    Cuda0
28K     Cuda1
104K    Cuda2
404K    Cuda3
1.6M    Cuda4
6.3M    Cuda5
26M     Cuda6
101M    Cuda7
401M    Cuda8
1.6G    Cuda9

## Expected behavior
I expect the same behaviour than cpu:
4.0K    Cuda0
4.0K    Cuda1
4.0K    Cuda2
4.0K    Cuda3
4.0K    Cuda4
4.0K    Cuda5
4.0K    Cuda6
4.0K    Cuda7
4.0K    Cuda8
4.0K    Cuda9

## Environment

Inside a custom made container giving as result for the environment script:
Collecting environment information...
PyTorch version: 1.0.0a0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (GCC) 8.2.0
CMake version: version 3.12.0

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 396.54
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

**Comment by goldsborough** [comment]
We have reproduced the bug. We'll send a fix to master soon.

**Comment by Strasser-Pablo** [comment]
Thanks. I'm curious to see the fix. I have no idea how 4k can become 1.6G.

**Comment by zdevito** [comment]
This should be fixed by https://github.com/pytorch/pytorch/pull/12377 The bug caused the storage of the tensor to resize at 4x larger than its current size.
