### ISSUE TITLE
[inductor][cpu]DebertaV2ForQuestionAnswering AMP static shape multiple thread default wrapper regression in 2024-03-23

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#122862]
### 🐛 Describe the bug

<p>new_perf_regression in 2024-03-23</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>huggingface</td>
      <td>DebertaV2ForQuestionAnswering</td>
      <td>multiple</td>
      <td>1.0</td>
      <td>1.012825</td>
      <td>0.118098464</td>
      <td>0.11961307680080001</td>
      <td>26.196844</td>
      <td>1.0</td>
      <td>2.290567</td>
      <td>0.068807462</td>
      <td>0.157608101810954</td>
      <td>27.15124</td>
      <td>0.44</td>
      <td>1.32</td>
      <td>0.58</td>
      <td>1.04</td>
    </tr>
  </tbody>

</table>

42624bc
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance huggingface DebertaV2ForQuestionAnswering amp first static
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,DebertaV2ForQuestionAnswering,1,1.287133,95.115025,30.050526,0.930185,1250.272051,1344.110592,1088,1,0,0,0,0

e26280a
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance huggingface DebertaV2ForQuestionAnswering amp first static
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,DebertaV2ForQuestionAnswering,1,1.989292,62.880099,19.385791,0.930492,1270.559949,1365.470413,1088,1,0,0,0,0

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>d6015d42</td>
      <td>main</td>
      <td>d6015d42</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>f0d461beacded34abe196c72ec4bcdb55bf01793</td>
      <td>main</td>
      <td>5bc7f7f97760d2d485621f9f30d0316e1f2440c6</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+a0c79b3</td>
      <td>main</td>
      <td>0.18.0a0+0325175</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.2.0a0+17a7081</td>
      <td>main</td>
      <td>2.2.0a0+87aeb55</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference performance huggingface DebertaV2ForQuestionAnswering amp first static

[huggingface-DebertaV2ForQuestionAnswering-inference-amp-static-default-multiple-performance-drop_guilty_commit (1).log](https://github.com/pytorch/pytorch/files/14783477/huggingface-DebertaV2ForQuestionAnswering-inference-amp-static-default-multiple-performance-drop_guilty_commit.1.log)

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/42624bceb6856a8934a1fcacb8a621a418f1a2c3
cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @WeizhuoZhang-intel @chuanqi129

**Comment by chuanqi129** [comment]
Hi @drisspg, according to the bisect search, seems the PR #122135 introduced this performance regression issue, could you help to double check whether if it's a expected drop?

**Comment by drisspg** [comment]
This change for correctness is expected to have an impact on performance I calculated around a ~1% per sdpa call. What was the regression on and E2E model ?

**Comment by leslie-fang-intel** [comment]
> This change for correctness is expected to have an impact on performance I calculated around a ~1% per sdpa call. What was the regression on and E2E model ?

Yean it's a E2E model. @chuanqi129 may help to provide the details.

**Comment by leslie-fang-intel** [comment]
Test on my local system between commit: 42624bceb6856a8934a1fcacb8a621a418f1a2c3 and e26280ad8bf6eecb0f218d69f3ec90f01617fac4, I didn't see clean performance regression. @zxd1997066 could you help to double confirm the guilt commit.

**Comment by zxd1997066** [comment]
cannot reproduce the good performance, close the issue.
