### ISSUE TITLE
[AOTI] error: ‘bfloat16’  was not declared in this scope

### ISSUE THREAD

**Issue by chenyang78** [pytorch/pytorch#122986]
### 🐛 Describe the bug

How to repro:

comment out the line below:

https://github.com/pytorch/pytorch/blob/57a9a64e10b84fa8d932482ae9417aa3fc3fbf44/test/inductor/test_aot_inductor.py#L2315

and run the following command:

```
$ python test/inductor/test_aot_inductor.py -k test_sdpa_abi_compatible_cpu_with_stack_allocation_and_minimal_arrayref_interface
```

### Versions

PyTorch version: 2.3.0a0+git57a9a6
Is debug build: True
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @desertfire

**Comment by frank-wei** [comment]
It needs c++ support in bfloat16 for declaring dtype of ArrayRefTensor. It looks like bf16 is supported in c++23 https://en.cppreference.com/w/cpp/types/floating-point 
Since our compilation is based on c++11, I think we can skip this test?

**Comment by chenyang78** [comment]
Thanks for looking into this, @frank-wei . Wondering if we change ```dtype=torch.bfloat16``` to ```dtype=torch.float16``` in ```test_sdpa```, do we see any failure? If not, then missing bfloat16 support is the only issue, which would be handled with c++23 as you mentioned. If we still see some failure with float16, there might be some other issue. Thanks.

**Comment by desertfire** [comment]
c10/util/BFloat16.h is almost a header-only file, we should be able to use it in the generated model.so, as long as we have proper test to guard the header-only implementation of BFloat16.
