### ISSUE TITLE
[profiler] make RecordFunctionFast take inputs

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#122998]
### 🚀 The feature, motivation and pitch

RECORD_FUNCTION in C++ and ~~torch.profiler.record_function~~ (apparently torch.profiler.record_function doesn't actually support recording inputs) already support recording inputs. Let's do the same for RecordFunctionFast.

**Goal**:
Make `torch._C._RecordFunctionFast()` take two arguments instead of 1:
1. A required string for the name (already exists)
2. An optional list of inputs to the tensor.

**Details & considerations**
* See https://github.com/pytorch/pytorch/pull/107195 for the original implementation
* Look for `#define RECORD_FUNCTION` or the at::RecordFunction implementation to see how we can take inputs
* Be careful to handle python object lifetimes correctly. Probably we want the RecordFunctionFast object to own references to the list of objects, if this is a relevant consideration.

The difficult part is probably going to be accepting the PyObject* args in the CPython implementation of the bindings, and converting it into the appropriate list type (presumably std::vector<IValue>? check RecordFunction to see what type it expects).

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov

**Comment by davidberard98** [comment]
follow up task: we need to use this in torch/_inductor/triton_heuristics.py.
i.e. similar modifications to https://github.com/pytorch/pytorch/pull/106351

And also pass the filenames through.
https://github.com/pytorch/pytorch/compare/main...davidberard98:pytorch:caching-autotuner-filename?expand=1

**Comment by davidberard98** [comment]
Follow up discussion w/ @sraikund16 :

- https://github.com/pytorch/pytorch/blob/bc65c985887f6d7b24bd09ff2c273f8b4b081160/torch/csrc/autograd/init.cpp#L287 we probably want to roughly copy this
- difference: we're dealing with cpython objects instead of pybind objects

other details which are probably less complex (maybe look into these after de-risking the above issues):
- we might want to guard this conversion logic on whether we think we'll actually use the inputs

**Comment by sraikund16** [comment]
Added support for args and kwargs in https://github.com/pytorch/pytorch/pull/123208 and https://github.com/pytorch/pytorch/pull/123600
