### ISSUE TITLE
[AOTI] error: no matchin g function for call to ‘std::vector<AtenTensorOpaque*>::vector(<brace-enclosed initializer list>)

### ISSUE THREAD

**Issue by chenyang78** [pytorch/pytorch#122984]
### 🐛 Describe the bug

How to repro:

comment out the line below:

https://github.com/pytorch/pytorch/blob/57a9a64e10b84fa8d932482ae9417aa3fc3fbf44/test/inductor/test_aot_inductor.py#L2312

and run the following command:

```
$ python test/inductor/test_aot_inductor.py -k test_index_put_with_none_index_abi_compatible_cpu_with_stack_allocation_and_minimal_arrayref_interface
...
error: no matchin
g function for call to ‘std::vector<AtenTensorOpaque*>::vector(<brace-enclosed initializer list>)’
```

### Versions

PyTorch version: 2.3.0a0+git57a9a6
Is debug build: True
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @desertfire

**Comment by IvanKobzarev** [comment]
Doing issue scrapping, does not repro, closing.
