### ISSUE TITLE
torchaudio.models.Conformer incorrectly converted to onnx (only one of the axes becomes dynamic)

### ISSUE THREAD

**Issue by FominArtmind** [pytorch/pytorch#122956]
### 🐛 Describe the bug

The following code demonstrates creation of conformer model with random weights (configuration values taken from the class docs) and its convertation to onnx model (the last goes without warnings):
```
import torch
import torchaudio

input_dim = 80
conformer = torchaudio.models.Conformer(
     input_dim=input_dim,
     num_heads=4,
     ffn_dim=128,
     num_layers=4,
     depthwise_conv_kernel_size=31,
)

torch.save(conformer.eval(), "conformer.pt")

lengths = torch.Tensor([10, 20, 12])
input = torch.ones(3, 20, 80)

torch.onnx.export(conformer,
                  f="../conformer.onnx",
                  input_names=["input", "lengths"],
                  output_names=["logits", "output_lengths"],
                  args=({ "input": input, "lengths": lengths }),
                  dynamic_axes={
                    "input": { 0: "batch_count", 1: "batch_item_length" },
                    "lengths": { 0: "batch_count" },
                    "logits": { 0: "batch_count", 1: "batch_item_length" },
                    "output_lengths": { 0: "batch_count" }
                  }
                )

```

The following code uses the same data to test the resulting .pt and .onnx models (note that the lengths and input dimensions are exactly the same that in conversion example inputs for onnx.export):
```
conformer = torch.load("conformer.pt")

lengths = torch.Tensor([10, 20, 12])
input = torch.ones(3, 20, 80)

output = conformer(input, lengths)

import onnxruntime as ort
import numpy

session = ort.InferenceSession("../conformer.onnx")

ortvalue = ort.OrtValue.ortvalue_from_numpy(input.numpy())
ortvalue2 = ort.OrtValue.ortvalue_from_numpy(lengths.numpy())

input_name = session.get_inputs()[0].name
input2_name = session.get_inputs()[1].name
label_name = session.get_outputs()[0].name
label2_name = session.get_outputs()[1].name

result = session.run([label_name, label2_name], { input_name: ortvalue, input2_name: ortvalue2 })
```
At the point, onnx model works. If the first dimension (batch count) is changed:
```
lengths = torch.Tensor([10, 20, 12, 15])
input = torch.ones(4, 20, 80)

```
onnx model still works.
However, if the second axe is changed (max batch length), for example:
```
lengths = torch.Tensor([10, 25, 12])
input = torch.ones(3, 25, 80)
```
onnx model crashes with the following error:

> [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/conformer_layers.0/self_attn/Reshape_4' Status Message: D:\bld\onnxruntime_1710148767998\work\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:45 onnxruntime::ReshapeHelper::ReshapeHelper input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{25,3,80}, requested shape:{20,12,20}
> 
> Traceback (most recent call last):
>   File "H:\Projects\Other\conformer\pt-onnx-converter-conformer.py", line 64, in <module>
>     result = session.run([label_name, label2_name], { input_name: ortvalue, input2_name: ortvalue2 })
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Other\Conda\envs\torch\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
>     return self._sess.run(output_names, input_feed, run_options)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/conformer_layers.0/self_attn/Reshape_4' Status Message: D:\bld\onnxruntime_1710148767998\work\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:45 onnxruntime::ReshapeHelper::ReshapeHelper input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{25,3,80}, requested shape:{20,12,20}
> 

The same time pt model works for all the cases.

### Versions

> PyTorch version: 2.2.1
> Is debug build: False
> CUDA used to build PyTorch: 12.1
> ROCM used to build PyTorch: N/A
> 
> OS: Майкрософт Windows 10 Pro
> GCC version: Could not collect
> Clang version: Could not collect
> CMake version: version 3.28.3
> Libc version: N/A
> 
> Python version: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:42:31) [MSC v.1937 64 bit (AMD64)] (64-bit runtime)
> Python platform: Windows-10-10.0.19044-SP0
> Is CUDA available: True
> CUDA runtime version: Could not collect
> CUDA_MODULE_LOADING set to: LAZY
> GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
> Nvidia driver version: 551.61
> cuDNN version: Could not collect
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> Is XNNPACK available: True
> 
> CPU:
> Architecture=9
> CurrentClockSpeed=3593
> DeviceID=CPU0
> Family=107
> L2CacheSize=4096
> L2CacheSpeed=
> Manufacturer=AuthenticAMD
> MaxClockSpeed=3593
> Name=AMD Ryzen 7 3700X 8-Core Processor
> ProcessorType=3
> Revision=28928
> 
> Versions of relevant libraries:
> [pip3] numpy==1.26.4
> [pip3] onnx==1.15.0
> [pip3] onnxruntime==1.17.1
> [pip3] onnxscript==0.1.0.dev20240315
> [pip3] torch==2.2.1
> [pip3] torchaudio==2.2.1
> [pip3] torchvision==0.17.1
> [conda] blas 1.0 mkl
> [conda] mkl 2023.1.0 h6b88ed4_46358
> [conda] mkl-service 2.4.0 py312h2bbff1b_1
> [conda] mkl_fft 1.3.8 py312h2bbff1b_0
> [conda] mkl_random 1.2.4 py312h59b6b97_0
> [conda] numpy 1.26.4 py312hfd52020_0
> [conda] numpy-base 1.26.4 py312h4dde369_0
> [conda] pytorch 2.2.1 py3.12_cuda12.1_cudnn8_0 pytorch
> [conda] pytorch-cuda 12.1 hde6ce7c_5 pytorch
> [conda] pytorch-mutex 1.0 cuda pytorch
> [conda] torchaudio 2.2.1 pypi_0 pypi
> [conda] torchvision 0.17.1 pypi_0 pypi

**Comment by thiagocrepaldi** [comment]
Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

**Comment by FominArtmind** [comment]
@thiagocrepaldi 
I haven't found how to reopen the issue.
I've tried dynamo_export with all my models already. It doesn't work with anything and looks as complete alpha thing - it's supported only for linux, on linux it has particular requirements for python, during conversion it always returns that something is not supported.

Unfortunately, we have to use torch.onnx.export for all our models since at least with limitations they provide result.
