### ISSUE TITLE
UNSTABLE pull / linux-jammy-py3.8-gcc11 / test (docs_test)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#123068]
This looks pretty unstable in trunk atm.  Marking it as unstable to look into this next week.

cc @ezyang @gchanan @zou3519 @kadeng @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
Adding hipri due to it affecting our docs test, which verifies our code in docs are okay.

It would be good to have more details in the issue body + ccing the quantization team seems like a good next step.

**Comment by andrewor14** [comment]
I took a look and actually it doesn't seem related to quantization. There is a quantization warning for duplicate description but that's just a warning. The real failure is here:

**Comment by andrewor14** [comment]
I took a look and actually it doesn't seem related to quantization. There is a quantization warning for duplicate description but that's just a warning. The real failure is here:

```
Document: jit
-------------
/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/jit/_trace.py:918: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
	%13 : Float(4, strides=[1], requires_grad=0, device=cpu) = aten::rand(%8, %9, %10, %11, %12) # <doctest default[0]>:2:0
This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
  _check_trace(
/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/jit/_trace.py:918: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Tensor-likes are not close!

Mismatched elements: 4 / 12 (33.3%)
Greatest absolute difference: 0.6291326880455017 at index (0, 3) (up to 1e-05 allowed)
Greatest relative difference: 0.8421575571251753 at index (0, 3) (up to 1e-05 allowed)
```

**Comment by andrewor14** [comment]
Removing quantization tag for now. Please let me know if I misunderstood the issue.

Also cc @davidberard98 for jit related issues

**Comment by clee2000** [comment]
> I took a look and actually it doesn't seem related to quantization. There is a quantization warning for duplicate description but that's just a warning. The real failure is here:
> 
> ```
> Document: jit
> -------------
> /opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/jit/_trace.py:918: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
> 	%13 : Float(4, strides=[1], requires_grad=0, device=cpu) = aten::rand(%8, %9, %10, %11, %12) # <doctest default[0]>:2:0
> This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
>   _check_trace(
> /opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/jit/_trace.py:918: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
> Tensor-likes are not close!
> 
> Mismatched elements: 4 / 12 (33.3%)
> Greatest absolute difference: 0.6291326880455017 at index (0, 3) (up to 1e-05 allowed)
> Greatest relative difference: 0.8421575571251753 at index (0, 3) (up to 1e-05 allowed)
> ```

I see these lines in succeeding runs of the job as well, and we use -W to turn warnings into errors, so I'm still inclined to think this is a problem with the quantization docs
