### ISSUE TITLE
Illegal instruction (core dumped) for Cuda in 1.0.0.dev

### ISSUE THREAD

**Issue by elmarculino** [pytorch/pytorch#12300]
## 🐛 Bug

Get "Illegal instruction (core dumped)" error when trying to copy object in CUDA memory.

## To Reproduce

>>> import torch
>>> a=torch.tensor([1.,2.])
>>> a
tensor([1., 2.])
>>> a.cuda()
Illegal instruction (core dumped)

## Expected behavior

Object be copied in CUDA memory.

## Environment

PyTorch version: 1.0.0.dev20181003
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 396.54
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.2)
[pip] torch (1.0.0.dev20181003)
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch-nightly           1.0.0.dev20181003 py3.6_cuda9.2.148_cudnn7.1.4_0  [cuda92]  pytorch

## Additional context

$ conda create -y --name torch_cuda92
$ conda activate torch_cuda92
$ conda install -y -c pytorch pytorch cuda92

**Comment by elmarculino** [comment]
GDB output:

```
(gdb) run teste.py
Starting program: /home/marco/anaconda3/envs/fastai/bin/python teste.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
1.0.0.dev20181004
9.2.148
[New Thread 0x7fffae733700 (LWP 4189)]
True
GeForce GTX 1070

Thread 1 "python" received signal SIGILL, Illegal instruction.
0x00007fffb9057bc3 in at::cuda::detail::initGlobalStreamState() ()
   from /home/marco/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
(gdb)
```

**Comment by colesbury** [comment]
Based on https://discuss.pytorch.org/t/illegal-instruction-core-dumped-for-cuda-in-1-0-0-dev/26550/5, this looks like an SSE4.1 instruction executing on a CPU without SSE4.1 support.

Christian's PR, which removes the SSE compilation flags, should fix this.

https://github.com/pytorch/pytorch/pull/12109

**Comment by elmarculino** [comment]
Running without problem since 1.0.0.dev20181010 version
