### ISSUE TITLE
export onnx error

### ISSUE THREAD

**Issue by WangHHY19931001** [pytorch/pytorch#123087]
### 🐛 Describe the bug

```
torch.onnx.dynamo_export(        model,
        args,
        path,
        export_params=True,
        opset_version=11,  
        do_constant_folding=True,  
        verbose=False,
        input_names=input_names,
        output_names=output_names,
                                     )
```

torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues

### Versions

```
Collecting environment information...
PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Address sizes:       36 bits physical, 48 bits virtual
Byte Order:          Little Endian
CPU(s):              12
On-line CPU(s) list: 0-11
Vendor ID:           GenuineIntel
Model name:          12th Gen Intel(R) Core(TM) i5-12400
CPU family:          6
Model:               151
Thread(s) per core:  2
Core(s) per socket:  6
Socket(s):           1
Stepping:            5
CPU max MHz:         2500.0000
CPU min MHz:         0.0000
BogoMIPS:            5000.00
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave osxsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni umip gfni vaes vpclmulqdq rdpid ibrs ibpb stibp ssbd
Hypervisor vendor:   Windows Subsystem for Linux
Virtualization type: container

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] onnx==1.16.0
[pip3] onnxruntime==1.17.1
[pip3] onnxscript==0.1.0.dev20240401
[pip3] onnxsim==0.4.36
[pip3] torch==2.2.2
[pip3] torchaudio==2.2.2
[pip3] torchvision==0.17.2
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-service               2.4.0           py310h5eee18b_1
[conda] mkl_fft                   1.3.8           py310h5eee18b_0
[conda] mkl_random                1.2.4           py310hdb19cb5_0
[conda] numpy                     1.26.4          py310h5f9d8c6_0
[conda] numpy-base                1.26.4          py310hb5e798b_0
[conda] pytorch                   2.2.2              py3.10_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                2.2.2                 py310_cpu    pytorch
[conda] torchvision               0.17.2                py310_cpu    pytorch
```

**Comment by MaanavD** [comment]
Hi @WangHHY19931001 , can you please provide a full repro script for better help with this issue?

**Comment by WangHHY19931001** [comment]
class DataCov(nn.Module):
    def __init__(self):
        super(DataCov, self).__init__()

        self.transform = nn.Sequential(
            torchaudio.transforms.MelSpectrogram(sample_rate=48000, n_fft=1536, hop_length=768, f_min=20, f_max=20000)
        )

    def forward(self, x1):
        return self.transform(x1)


class QANet(nn.Module):
    def __init__(self, num_classes=1):
        super(QANet, self).__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(1, 128, kernel_size=(3, 3), padding=1),
            nn.GELU(),
            nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))
        )

        self.bn = nn.Sequential(
            nn.BatchNorm2d(128, eps=1e-05, momentum=0.1)
        )

        self.fc1_3_0 = nn.Sequential(
            nn.Linear(375, 375),
            nn.GELU()
        )

        self.fc1_3_1 = nn.Sequential(
            nn.Linear(375, 375),
            nn.GELU()
        )

        self.fc1_3_2 = nn.Sequential(
            nn.Linear(375, 375),
            nn.GELU()
        )

        self.fc1_3_3 = nn.Sequential(
            nn.Linear(375, 375),
            nn.GELU()
        )

        self.fc1_3_out = nn.Sequential(
            nn.Linear(375, 1),
            nn.GELU()
        )

        self.fc1_2_0 = nn.Sequential(
            nn.Linear(64, 64),
            nn.GELU()
        )

        self.fc1_2_1 = nn.Sequential(
            nn.Linear(64, 64),
            nn.GELU()
        )

        self.fc1_2_2 = nn.Sequential(
            nn.Linear(64, 64),
            nn.GELU()
        )

        self.fc1_2_3 = nn.Sequential(
            nn.Linear(64, 64),
            nn.GELU()
        )

        self.fc1_2_out = nn.Sequential(
            nn.Linear(64, 1),
            nn.GELU()
        )

        self.fc1_1_0 = nn.Sequential(
            nn.Linear(256, 256),
            nn.GELU()
        )

        self.fc1_1_1 = nn.Sequential(
            nn.Linear(256, 256),
            nn.GELU()
        )

        self.fc1_1_2 = nn.Sequential(
            nn.Linear(256, 256),
            nn.GELU()
        )

        self.fc1_1_3 = nn.Sequential(
            nn.Linear(256, 256),
            nn.GELU()
        )

        self.fc1_1_out = nn.Sequential(
            nn.Linear(256, 1),
            nn.GELU()
        )

    def forward(self, x1, x2):
        x1 = self.conv(x1)
        x1 = self.bn(x1)
        x2 = self.conv(x2)
        x2 = self.bn(x2)
        x = torch.cat((x1, x2), dim=1)
        del x1, x2
        x = self.fc1_3_0(x)
        x = self.fc1_3_1(x)
        x = self.fc1_3_2(x)
        x = self.fc1_3_3(x)
        x = self.fc1_3_out(x)
        x = x.view(x.size(0), 256, 64)
        x = self.fc1_2_0(x)
        x = self.fc1_2_1(x)
        x = self.fc1_2_2(x)
        x = self.fc1_2_3(x)
        x = self.fc1_2_out(x)
        x = x.view(x.size(0), 256)
        x = self.fc1_1_0(x)
        x = self.fc1_1_1(x)
        x = self.fc1_1_2(x)
        x = self.fc1_1_3(x)
        x = self.fc1_1_out(x)
        return x


def export_datacov_onnx(pth_path, path):
    state_dict = torch.load(pth_path, map_location='cpu')
    model = QANet().to(torch.float32)
    set_compile = True
    if set_compile:
        state_dict_fix = {}
        for k, v in state_dict.items():
            tmp_k = k[k.find(".") + 1:]
            state_dict_fix[tmp_k] = v
        model.load_state_dict(state_dict_fix, strict=True)
    else:
        model.load_state_dict(state_dict, strict=True)
    model.eval()
    model_cov = DataCov()
    model_cov.eval()
    src_wav = torch.randn((1, 1, 48000 * 12), requires_grad=True)
    dst_wav = torch.randn((1, 1, 48000 * 12), requires_grad=True)
    input_names = ["sample_data_cov", "src_data_cov"]        # 导出的ONNX模型输入节点名称
    output_names = ["ans"]      # 导出的ONNX模型输出节点名称
    x_1 = model_cov(dst_wav)
    x_2 = model_cov(src_wav)
    args = (x_1, x_2)

**Comment by phierhager** [comment]
@WangHHY19931001 You want to use the dynamo_export method, but you are using the input parameter of the old onnx.export() function. Before the error message you posted in here, there should have been something like ...got an unexpected keyword argument... because torch believes all the additional keywords you are using are inputs to the model.forward function.
