### ISSUE TITLE
[docs] nn.ChannelShuffle example code unrealistic (`randn` cannot produce integers like `15`)

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#123053]
### 📚 The doc issue

Originally reported in https://github.com/pytorch/pytorch/pull/123033#issuecomment-2028444096

---

The online docs assume any-dimension `(*, C, H, W)`, right?

Also, the code example in online docs seems incorrect as `torch.randn` should return float values around 0 (including negatives) and not integers like `15`:
![image](https://github.com/pytorch/pytorch/assets/1041752/14b5e846-6798-46f6-85a1-fefacf637591)
 

To make the example correct, maybe torch.randn should just be replaced by initting `input` by the input tensor from the example

Also, it would be great if the docs example printed the input.shape and output.shape, since it appears that ChannelsShuffle is introducing a new dimension (?): 

strange below-the-line comma:
![image](https://github.com/pytorch/pytorch/assets/1041752/71546180-01c2-415d-ad95-ac97aa15c63a)

It would be nice if somehow docs code examples were testable (maybe worth somewhere storing test "input"/"random" tensors to not depend on un-reproducible random inputs)

cc @svekars @brycebortree @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by janeyx99** [comment]
Huh I thought our docs are usually tested...maybe this one is skipped somehow.

Replacing randn with arange should do the same thing.

**Comment by vadimkantorov** [comment]
Yeah, arange should work. Curious why this doctest is not run.

Also, the below-the-line-comma and g-underscore hint on some latex typos

**Comment by albanD** [comment]
I agree that `torch.arange(1, 17, dtype=torch.float32).view(1,4,2,2)` would be the right way to generate the input here.

> Also, it would be great if the docs example printed the input.shape and output.shape, since it appears that ChannelsShuffle is introducing a new dimension (?):

No new dimension is added no.

There is an xdoctest skip for this doc btw that might be why this wasn't caught: https://github.com/pytorch/pytorch/blob/f9b2ffa7c494cd1a0481149cb4089da4b33e4b66/torch/nn/modules/channelshuffle.py#L20

**Comment by vadimkantorov** [comment]
@albanD 

> No new dimension is added no.

In this case, what does below-the-line-comma and g-underscore mean? 
![image](https://github.com/pytorch/pytorch/assets/1041752/71546180-01c2-415d-ad95-ac97aa15c63a)

The wording "divides and rearranges the channels" is extremely vague/imprecise, as there might be many completely different ways to "rearrange" the channels

**Comment by albanD** [comment]
This is just a missing space that breaks the latest rendering.
This shows the size of the objects that get shuffled before restoring the original shape as the next sentence mentions.
Feel free to send a PR cleaning up these two thing!
