### ISSUE TITLE
docs website is down 404 

### ISSUE THREAD

**Issue by Chizkiyahu** [pytorch/pytorch#123189]
### 📚 The doc issue

- [https://pytorch.org/docs/stable/index.html](https://pytorch.org/docs/stable/index.html) down - 404
- [https://pytorch.org](https://pytorch.org) is up 
![Screenshot 2024-04-02 at 20 30 56](https://github.com/pytorch/pytorch/assets/37312901/cf24ae81-44e8-4b1a-bbde-bd8c89ac1051)

**Comment by lukaemon** [comment]
Same issue here.

**Comment by hershey890** [comment]
Same. I've clone this repo with the Torch 2.1 docs to use for now https://github.com/unknownue/PyTorch.docs

This was committed with changes to the docs repo 2 hours ago, maybe it broke something? https://github.com/pytorch/pytorch/pull/122305 . I wouldn't expect some errors in .rst files to break it all but maybe Sphinx is weird. It failed a testcase for build-python_docs in build-linux-docs

**Comment by Chizkiyahu** [comment]
is looks to me that fails is here https://github.com/pytorch/pytorch/actions/runs/8515452312/job/23323343431

**Comment by Chizkiyahu** [comment]
Update is up but is not ok 

![Screenshot 2024-04-02 at 21 22 22](https://github.com/pytorch/pytorch/assets/37312901/0f2e69ee-468d-4302-89d2-953023ec0546)

**Comment by tringwald** [comment]
Looks like all the static assets are missing (HTTP 404 for most CSS/JS files).

**Comment by Chizkiyahu** [comment]
is up now
