### ISSUE TITLE
warpctc_pytorch with cpp_extension

### ISSUE THREAD

**Issue by dattx0** [pytorch/pytorch#12318]
i tried to build [warpctc_pytorch](https://github.com/SeanNaren/warp-ctc) with pytorch 1.0 (python3.5, ubuntu 16.04.5), i changed 
create_extension to cpp_extension and build successfully. But when import, an error occured

setup.py
```python
# from torch.utils.ffi import create_extension
from torch.utils.cpp_extension import CppExtension, CUDAExtension, BuildExtension
...

create_extension = CUDAExtension if enable_gpu else CppExtension

ffi = create_extension(
    name='warpctc_pytorch._warp_ctc',
    package=True,
    language='c++',
    headers=headers,
    sources=['src/binding.cpp'],
    # with_cuda=enable_gpu,
    include_dirs=include_dirs,
    library_dirs=[os.path.realpath(warp_ctc_path)],
    libraries=['warpctc'],
    extra_link_args=['-Wl,-rpath,' + os.path.realpath(warp_ctc_path)],
    extra_compile_args=extra_compile_args)
# ffi = ffi.distutils_extension()
setup(
    name="warpctc_pytorch",
    version="0.1",
    description="PyTorch wrapper for warp-ctc",
    url="https://github.com/baidu-research/warp-ctc",
    author="Jared Casper, Sean Naren",
    author_email="jared.casper@baidu.com, sean.narenthiran@digitalreasoning.com",
    license="Apache",
    packages=find_packages(),
    ext_modules=[ffi],
    cmdclass={'build_ext': BuildExtension}
)

```

```python
>>> from warpctc_pytorch import CTCLoss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/warpctc_pytorch-0.1-py3.5-linux-x86_64.egg/warpctc_pytorch/__init__.py", line 6, in <module>
    from ._warp_ctc import *
ImportError: dynamic module does not define module export function (PyInit__warp_ctc)
>>> 

```

how can i fix this error? thanks!

**Comment by goldsborough** [comment]
@dattx0 C++ extensions require exposing parts of your C++ code to Python via pybind11. The repository you link to does not seem to expose anything. See https://pytorch.org/tutorials/advanced/cpp_extension.html#binding-to-python for more details.

**Comment by dattx0** [comment]
thanks your support!

**Comment by patterson163** [comment]
@dattx0 Hello, now I'm using warp-ctc,too.Have you solved this trouble? Would you mind pasting the code?

**Comment by dattx0** [comment]
@patterson163 i use native pytorch 1.0 ctc loss and [ctcdecoder](https://github.com/githubharald/CTCDecoder) with beam search or you can use chainer's ctc like some people

**Comment by patterson163** [comment]
@dattx0 Thanks for reply.

**Comment by abuvaneswari** [comment]
@patterson163 , thanks a lot for sharing valuable info on what libraries to use for CTCLoss and CTC decode going forward in PyTorch 1.0

I tried comparing the results from CTCLoss of warp-ctc in PyTorch 0.4.0 and that of torch.nn in PyTorch 1.0 and I see the following difference. 

Am I doing anything wrong in passing the parameters? 
Do I have to reshape the tensors that I originally pass into warp-ctc's CTCLoss when I start to use torch.nn.CTCLoss?

### -------- warp-ctc, CTCLoss ------
[ds2@blipp73 ]$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import torch
>>> from warpctc_pytorch import CTCLoss
>>> ctc_loss = CTCLoss()
>>> # expected shape of seqLength x batchSize x alphabet_size
>>> probs = torch.FloatTensor([[[0.1, 0.6, 0.1, 0.1, 0.1], [0.1, 0.1, 0.6, 0.1, 0.1]]]).transpose(0, 1).contiguous()
>>> labels = torch.IntTensor([1, 2])
>>> label_sizes = torch.IntTensor([2])
>>> probs_sizes = torch.IntTensor([2])
>>> probs.requires_grad_(True)  # tells autograd to compute gradients for probs
tensor([[[ 0.1000,  0.6000,  0.1000,  0.1000,  0.1000]],

        [[ 0.1000,  0.1000,  0.6000,  0.1000,  0.1000]]])
>>> cost = ctc_loss(probs, labels, probs_sizes, label_sizes)
>>> cost.backward()
>>> cost.data
tensor([ 2.4629])


### -------- PyTorch 1.0, CTCLoss ---
[ds2pth1@blipp73 ]$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch.nn import CTCLoss
>>> #try with default reduction
>>> ctc_loss = CTCLoss() 
>>> #  seqLength x batchSize x alphabet_size
>>> probs = torch.FloatTensor([[[0.1, 0.6, 0.1, 0.1, 0.1], [0.1, 0.1, 0.6, 0.1, 0.1]]]).transpose(0, 1).contiguous()
>>> labels = torch.IntTensor([1, 2])
>>> label_sizes = torch.IntTensor([2])
>>> probs_sizes = torch.IntTensor([2])
>>> probs.requires_grad_(True)  # tells autograd to compute gradients for probs
tensor([[[0.1000, 0.6000, 0.1000, 0.1000, 0.1000]],

        [[0.1000, 0.1000, 0.6000, 0.1000, 0.1000]]], requires_grad=True)
>>> cost = ctc_loss(probs, labels, probs_sizes, label_sizes)
>>> cost.backward()
>>> cost.data
tensor(-0.6000)
>>> 
>>> # Let us try with reduction = 'none' 
>>> ctc_loss = CTCLoss(reduction='none')
>>> cost = ctc_loss(probs, labels, probs_sizes, label_sizes)
>>> cost.backward()
>>> cost.data
tensor([-1.2000])

**Comment by Leechen2014** [comment]
this link may be help you : 
https://pytorch.org/docs/0.4.1/cpp_extension.html?highlight=torch%20utils%20cpp_extension#torch-utils-cpp-extension
