### ISSUE TITLE
Followup on Google Collab issue for release 2.3

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#123296]
### 🐛 Describe the bug

We would like to followup on :
https://github.com/googlecolab/colabtools/issues/4344

For release 2.3.

On Pytorch side we would need to:
Run smoke test in colab session, make sure they pass
Recreate the colab setup in local dev environment, see if we can automate testing for colab

### Versions

2.3

cc @malfet @huydhn @PaliC @seemethere

**Comment by PaliC** [comment]
Verified the suggested fix works for torchonly smoketests on colab 
https://colab.research.google.com/drive/1Wi_Xvv1AUDU2ogfoKCIIIOsGahhiFfKo?usp=sharing
