### ISSUE TITLE
Enable v2 C shim

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#123236]
https://github.com/pytorch/pytorch/blob/15529de90144fdf8681d518483b5acbe944ad2e4/torch/_inductor/config.py#L36 needs to be enabled for fbcode

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @chenyang78

**Comment by ezyang** [comment]
Forgive me for being late to the party, but why did we need to config guard this? Shouldn't we be allowed to start calling new ABI functions as soon as they are added?

**Comment by desertfire** [comment]
> Forgive me for being late to the party, but why did we need to config guard this? Shouldn't we be allowed to start calling new ABI functions as soon as they are added?

When I first implemented this, it potentially can cause FC-breakage. But at this point, it is more a fbcode build system enablement issue, cc @frank-wei , @zoranzhao
