### ISSUE TITLE
test_autograd.TestAutograd.test_ctc_loss fails : cuda runtime error : too many resources requested

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#12324]
## 🐛 Bug
When running :  python -m unittest -q test_autograd.TestAutograd.test_ctc_loss -v
The test fails with :   RuntimeError: cuda runtime error (7) : too many resources requested for launch at /pytorch/aten/src/ATen/native/cuda/LossCTC.cu:537

If I hardcode   threads_batch = 8;   in pytorch/aten/src/ATen/native/cuda/LossCTC.cu  around line 522, the test passes.

## To Reproduce
python -m unittest -q test_autograd.TestAutograd.test_ctc_loss -v

## Expected behavior

Should pass test.

## Environment

 - PyTorch Version (e.g., 1.0): torch (1.0.0a0+b911ca9)
 - OS (e.g., Linux):  RH 7.5    ppc64le   P9
 - How you installed PyTorch (`conda`, `pip`, source):  source
 - Build command you used (if compiling from source):   python setup.py install
 - Python version:  3.6
 - CUDA/cuDNN version:  10   or  9.2   /   7.1.3
 - GPU models and configuration:   4 x Voltas
 - Any other relevant information:

**Comment by SsnL** [comment]
cc @t-vi  @ngimel should we also add a launch bound here?

**Comment by ngimel** [comment]
Yes. cc @syed-ahmed - do you already have a fix doing that? If so, can you please send a PR?

**Comment by syed-ahmed** [comment]
@ngimel Thanks for the notification. I have sent in the fix.
