### ISSUE TITLE
[CI] CPU Inductor codepath for AVX2/Default is not tested in CI

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#123224]
### 🐛 Describe the bug

For example, when https://github.com/pytorch/pytorch/pull/122503 was landed, it accidentally switched to using AVX2 only runners, which resulted in some test failing with being unable to compile a correct code, see https://hud.pytorch.org/pytorch/pytorch/pull/122503?sha=c599c89babdcd98e7048286eecd3ec27ee8e20eb

which were eventually fixed by https://github.com/pytorch/pytorch/pull/122608

But it proves that AVX2 is not tested in CI

Eager AVX2 and default dispatch are tested using https://github.com/pytorch/pytorch/blob/e3d80f2fa98d7ab02f88023d381b2e5981dd99ff/aten/src/ATen/native/DispatchStub.cpp#L16

While torch.compile SIMD selection can be controlled using
https://github.com/pytorch/pytorch/blob/e3d80f2fa98d7ab02f88023d381b2e5981dd99ff/torch/_inductor/codecache.py#L1223

but it would be ideal if the same environment variable could be used for both eager and compile

Also, it perhaps worth shifting some of the sanity testing from an integration to simple unittesting (though see https://github.com/pytorch/pytorch/issues/123219 , unittests are only good if they are run in CI)

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by jgong5** [comment]
Thanks @malfet for the pointers and suggestions. It is a good idea to unify the control of the CPU vec ISA use with `ATEN_CPU_CAPABILITY` for both eager and inductor codegen. It can be the immediate first step we can do. We have moved most of the arch-specific intrinsics-based implementation out of inductor (`cpp_prefix.h`) to the `cpu/vec` in the recent PRs (https://github.com/pytorch/pytorch/pull/119979, https://github.com/pytorch/pytorch/pull/119654). So we can test most of them via `vec_test_all` UTs. We can add more UTs to `vec_test_all` in the future on anything new or missing. From the integration tests' perspective, do you think it makes sense to also have dedicated tests to cover various `ATEN_CPU_CAPABILITY` configurations?

**Comment by leslie-fang-intel** [comment]
@CaoE will rebase to land https://github.com/pytorch/pytorch/pull/123514

**Comment by CaoE** [comment]
Close this issue since https://github.com/pytorch/pytorch/pull/123514 has been landed. If you have any questions please reopen it.
