### ISSUE TITLE
[AOTI][cpp_wrapper] test_triton_heuristics.py::test_artificial_grid_cpp_wrapper disabled

### ISSUE THREAD

**Issue by masnesral** [pytorch/pytorch#123210]
### 🐛 Describe the bug

I've disabled test_triton_heuristics.py:test_artificial_grid_cpp_wrapper because it fails regularly after removing this mistaken line: https://github.com/pytorch/pytorch/blob/main/test/inductor/test_triton_heuristics.py#L36. It may or may not be interesting to note that _sometimes_ the cache entries seem to be generated correctly despite the unit test failure because a second run of the test (with a cache hit) may succeed. (Note that https://github.com/pytorch/pytorch/pull/122661 will enforce a fresh cache for every inductor test)

### Versions

main

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

**Comment by masnesral** [comment]
cc @desertfire

**Comment by desertfire** [comment]
Rewrote as an AOTI test in https://github.com/pytorch/pytorch/pull/123235, cc @chenyang78 since you have looked into grid computation issues before.

**Comment by chenyang78** [comment]
Yes, please do. Thanks!
