### ISSUE TITLE
Add inductor level stack trace stitching

### ISSUE THREAD

**Issue by oulgen** [pytorch/pytorch#123201]
### 🚀 The feature, motivation and pitch

When the inductor generated python file is executed via inductor's main process and it crashes, the stack trace emitted only comes from the parent inductor process and it does not include the error from the generated python file. We should add support for stitching the child process stack trace into parent process.

This will help debugging some internal errors.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by ezyang** [comment]
@oulgen is this the same as https://github.com/pytorch/pytorch/issues/109610 ? (which has repro instructions)

**Comment by oulgen** [comment]
Yes, closing this one. Although the other hasn't received any action in a while, perhaps we should talk about the other one in triage review in case there are any takers.
