### ISSUE TITLE
Dynamo full graph export fails on 'print' and 'logger'

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#123288]
Repro:

```python
import torch
# from transformers.utils import logging

# logger = logging.get_logger(__name__)

import logging
logger = logging.getLogger(__name__)


def func(x):
    # NOTE: Either of these lines will cause the export to fail.
    # logger.warning_once("abc")  # HF's logger
    # logger.log("abc")
    # print("abc")
    return x + 1


torch._dynamo.export(func, torch.randn(2, 3))
"""
torch._dynamo.exc.Unsupported: builtin: print [<class 'torch._dynamo.variables.constant.ConstantVariable'>] False

from user code:
   File "repro_logging.py", line 13, in func
    print("abc")

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

----------

torch._dynamo.exc.Unsupported: 'inline in skipfiles: Logger.log | log /lib/python3.10/logging/__init__.py, skipped according trace_rules.lookup'

from user code:
   File "repro_logging.py", line 13, in func
    logger.log("abc")

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
"""
```

Is there a way for dynamo to ignore these lines? Right now we found the only solution is to change model code and manually remove these calls.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @thiagocrepaldi, @ezyang, @jansel

**Comment by angelayi** [comment]
You can create a set of logging operators for export to ignore in `dynamo.config.reorderable_logging_functions`, something like [this](https://fburl.com/mdbocpy0).

**Comment by BowenBao** [comment]
Thanks @angelayi, it seems I can get `print` to work with following change, but not `logging`, please let me know if I have not used the patch correctly.

```python
import torch
from transformers.utils import logging as hf_logging

hf_logger = hf_logging.get_logger(__name__)

import logging
logger = logging.getLogger(__name__)


def func(x):
    print("abc")  # Pass with config patch
    # NOTE: Either of these lines will cause the export to fail.
    logger.log("abc")
    hf_logger.warning_once("abc")  # HF's logger
    return x + 1


with torch._dynamo.config.patch(reorderable_logging_functions={logging.log, hf_logging.warning_once, print}):
    torch._dynamo.export(func, torch.randn(2, 3))
```
```
  File "/pytorch/torch/_dynamo/symbolic_convert.py", line 2297, in inline_call_
    result = InliningInstructionTranslator.check_inlineable(func)
  File "/pytorch/torch/_dynamo/symbolic_convert.py", line 2274, in check_inlineable
    unimplemented(
  File "/pytorch/torch/_dynamo/exc.py", line 199, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: 'inline in skipfiles: Logger.log | log /python3.10/logging/__init__.py, skipped according trace_rules.lookup'

from user code:
   File "/repro_logging.py", line 13, in func
    logger.log("abc")

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

**Comment by thiagocrepaldi** [comment]
> Ah, we can't ignore logger methods yet.. probably requires a fix to create some sort of dynamo LoggerVariable for logger subclasses?

Is there any PR for similar things that we could look at and maybe contribute it to torch?

**Comment by angelayi** [comment]
Yeah of course, that would be great!

I'm thinking you can do something like this:
- Create a `LoggerVariable` `VariableTracker` like [`HFPretrainedConfigVariable`](https://github.com/pytorch/pytorch/blob/8b83327cd50aad309fcd07d109196a65b187d3e2/torch/_dynamo/variables/dicts.py#L829) 
- Add a casing [here](https://github.com/pytorch/pytorch/blob/8b83327cd50aad309fcd07d109196a65b187d3e2/torch/_dynamo/variables/builder.py#L623-L625) where if you see something of type `Logger`, you create this `LoggerVariable`.
- And then override the `call_method` function, something like [this](https://github.com/pytorch/pytorch/blob/8b83327cd50aad309fcd07d109196a65b187d3e2/torch/_dynamo/variables/misc.py#L691) to be do something like, "if export then pass"
