### ISSUE TITLE
Documents on Safari Misalignment

### ISSUE THREAD

**Issue by hologerry** [pytorch/pytorch#123336]
### 📚 The doc issue

The parameters and the types are misaligned to the function name, as well as the code formatted text on recent latest version Dash app.
All the PyTorch documents (PyTorch, torchvision, torchtext, torchaudio) have this issue.
<img width="912" alt="image" src="https://github.com/pytorch/pytorch/assets/11660168/99a4967e-0820-4fe1-b082-664ba5c99ce8">

### Suggest a potential alternative/fix

It's maybe a CSS/styling issue, there is no such issue on Chrome.

cc @svekars @brycebortree

**Comment by Sreesruth** [comment]
hi @colesbury @hologerry @scw @svenstaro @JackDanger , what is to be done here ?, can i contribute ??

**Comment by hologerry** [comment]
Hi @Sreesruth , to be more clear, I think this is a bug. And on Chome, there is no such missalignment.
Since I am not quite familiar with CSS, I don't know how to locate this issue, but I think this is related to some styling configuration.
<img width="916" alt="image" src="https://github.com/pytorch/pytorch/assets/11660168/562cd62e-0ff4-48ff-9ec4-f0cc50ccdbce">

**Comment by Sreesruth** [comment]
> Hi @Sreesruth , to be more clear, I think this is a bug. And on Chome, there is no such missalignment. Since I am not quite familiar with CSS, I don't know how to locate this issue, but I think this is related to some styling configuration. <img alt="image" width="916" src="https://private-user-images.githubusercontent.com/11660168/321354828-562cd62e-0ff4-48ff-9ec4-f0cc50ccdbce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTI3ODAsIm5iZiI6MTcxNDkxMjQ4MCwicGF0aCI6Ii8xMTY2MDE2OC8zMjEzNTQ4MjgtNTYyY2Q2MmUtMGZmNC00OGZmLTllYzQtZjBjYzUwY2NkYmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEyMzQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMDUyZGNhODUwZTZiZTkzZjJhZjE2YzAzMjUzNzZiYTUyNzViMGE1NjViNGI4YTlhYzJjODg0OWVmOWI5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8c3a4x4vh-kIre-S3azuHEqXEIq9-wcZ3EHY3iGAzWw">

oh okay, then what is to be done to proceed further ?

**Comment by hologerry** [comment]
I think can make some changes to the document files so that the behavior can be same on both safari and chrome.

**Comment by Sreesruth** [comment]
> I think can make some changes to the document files so that the behavior can be same on both safari and chrome.

Thats great !, how can i help you ??

**Comment by hologerry** [comment]
I am not familiar with front end development(Javascript/HTML/CSS...), so maybe you can help to resolve this problem or figure out how to do so, or involve someone else to solve.
Thanks.

**Comment by Sreesruth** [comment]
> I am not familiar with front end development(Javascript/HTML/CSS...), so maybe you can help to resolve this problem or figure out how to do so, or involve someone else to solve. Thanks.

okay, i can't say that i am well versed in frontend but i will give it a try.

**Comment by hologerry** [comment]
> > I am not familiar with front end development(Javascript/HTML/CSS...), so maybe you can help to resolve this problem or figure out how to do so, or involve someone else to solve. Thanks.
> 
> 
> 
> okay, i can't say that i am well versed in frontend but i will give it a try. 

Great! thanks
