### ISSUE TITLE
Inquiry on GPU utilization of pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime image

### ISSUE THREAD

**Issue by rurusungoa** [pytorch/pytorch#123330]
### 🚀 The feature, motivation and pitch

Inquiry on GPU utilization of pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime image

When pytorch saw "cpu_mkl_py", it only used the CPU.
The runtime pytorch image provided by pytorch seems to have worked well because it contains the "py3.10_cuda11.8_cudnn8.7.0_0" version of the package.

However, I also checked the GPU device in the redhat software "openshfit", but unlike in existing python's jupyter-notebook, 
I did not configure the nvidia.com/gpu:1 device by filling in the deployment, but I brought the image of pytorch as is and checked it, 
and the GPU was found. It comes with a card.

I have questions about how that part is different, but it was resolved well.

### checking the device

When running in python, the device was also confirmed well.

  import torch
    print(torch.cuda.get_device_name(0))
   => NVIDIA GTX 6000
    print(torch.cuda.is_available())
   => True

**Comment by colesbury** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/

**Comment by rurusungoa** [comment]
Hello @colesbury 

OK! Thank you. We will proceed from the forum link you provided.

**Comment by malfet** [comment]
Closing as one should use forums to discuss those kinds of issues. Also, 1.8.1 is just too old, please try newer version of PyTorch first
