### ISSUE TITLE
MacOS nightly builds are broken

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#123343]
### 🐛 Describe the bug

See https://github.com/pytorch/pytorch/actions/runs/8550945760/job/23428905841
Very likely by [ONNX update](https://github.com/pytorch/pytorch/pull/123125)
Solution seem somewhat simple: just bump MacOS  targeted by nightly builds specified in 
https://github.com/pytorch/builder/blob/0912166e3bc328cc2a08fec1c4ae92d8a3c41314/wheel/build_wheel.sh#L127

Probably a more fundamental question, is whether or not it should be bumped right to MacOS-11(which is the fist OS to support Apple silicon) 

### Versions

nightly

cc @seemethere @osalpekar @atalman @albanD

**Comment by malfet** [comment]
Will it be fixed by https://github.com/pytorch/builder/commit/0912166e3bc328cc2a08fec1c4ae92d8a3c41314 ?

**Comment by atalman** [comment]
Here is the test https://github.com/pytorch/pytorch/actions/runs/8556119928/job/23445182673?pr=121979

**Comment by malfet** [comment]
Indeed commit to builder fixed it. Closing
