### ISSUE TITLE
PyTorch consumes an extra doubled memory when loading model weights

### ISSUE THREAD

**Issue by KaneGreen** [pytorch/pytorch#123334]
### 🐛 Describe the bug

The test code is very simple, as long as the number of parameters of the model is large enough, because this can make the surges of memory usage more obvious.
Also, I recommend storing weight files on an HDD rather than a high-speed SSD, as this can extend loading times and make memory spikes more noticeable on the pictures.

```python
# code block [1]
import torch
import torch.nn as nn
from torch.nn.utils import skip_init

# code block [2]
model_path = 'F:\\model_memory.pth'

# code block [3]
model2 =  nn.Sequential(
    skip_init(nn.Linear, 16*1024, 16*1024),
    nn.ReLU(),
    skip_init(nn.Linear, 16*1024, 16*1024),
    nn.ReLU(),
)

# code block [4]
model2.load_state_dict(torch.load(model_path))
```

The model in my code here takes up about 2GB of memory, and the Python and torch modules take up about 0.5GB.
Execute each code block in turn, and use [Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) to monitor the memory usage of the `python.exe` process. You can get the following picture:
![realcode](https://github.com/pytorch/pytorch/assets/20700283/f90c85bf-815e-4992-b531-dfd79f9b9c3b)
(I added some annotations)

As you can see, when I finish executing code block [3]. Memory usage is at the expected 2.5GB, which is good.
But when I execute the code block [4], the memory usage starts to rise rapidly, reaching about 4.5GB at the peak. It is obvious that this increment is exactly the size of the model weights. After reaching the peak for a period of time, the memory usage quickly dropped back to 2.5GB, and at the same time, vscode showed that the code block [4] was completed.

It looks like some kind of temporary variable is consuming a lot of memory instead of writing the weights directly to the memory previously allocated for the model.

In today's reality, as models become larger and larger, loading the model requires consuming twice memory of the model size, and this problem will become more and more obvious. This issue may prevent some users with limited memory capacity from using PyTorch.

Possible improvements to improve this include (but are not limited to):
(1) directly writing the read weights to the corresponding location in the model's allocated memory (2) providing a convenient API for loading weights layer by layer.

### Versions

```
PyTorch version: 2.2.1
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro for Workstations
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC v.1937 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060 SUPER
Nvidia driver version: 551.76
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3600
DeviceID=CPU0
Family=107
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3600
Name=AMD Ryzen 7 3700X 8-Core Processor
ProcessorType=3
Revision=28928

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.1
[conda] blas                      2.121                       mkl    conda-forge
[conda] blas-devel                3.9.0              21_win64_mkl    conda-forge
[conda] libblas                   3.9.0              21_win64_mkl    conda-forge
[conda] libcblas                  3.9.0              21_win64_mkl    conda-forge
[conda] liblapack                 3.9.0              21_win64_mkl    conda-forge
[conda] liblapacke                3.9.0              21_win64_mkl    conda-forge
[conda] mkl                       2024.0.0         h66d3029_49657    conda-forge
[conda] mkl-devel                 2024.0.0         h57928b3_49657    conda-forge
[conda] mkl-include               2024.0.0         h66d3029_49657    conda-forge
[conda] numpy                     1.26.4          py311h0b4df5a_0    conda-forge
[conda] pytorch                   2.2.1           py3.11_cuda12.1_cudnn8_0    pytorch
[conda] pytorch-cuda              12.1                 hde6ce7c_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
```

------
Update:
I have tried `model2.load_state_dict(torch.load(model_path, mmap=True))`, and it still used 4.5GB memory.

cc @albanD

**Comment by vadimkantorov** [comment]
Related ideas: https://github.com/pytorch/pytorch/issues/79967 - lazy tensors. and an ability to pass to torch.load some filter lambda-function or load_keys/skip_keys which can allow skipping some layers with a simple knob

Also to some extent, the new argument `torch.load(..., mmap=True)` can alleviate the problem

**Comment by KaneGreen** [comment]
> Also to some extent, the new argument `torch.load(..., mmap=True)` can alleviate the problem,

I tried loading with `mmap=True` (I forgot to mention this in the post above) and it still uses 4.5GB memory. In my opinion, `mmap=True` does not solve the problem at all and may even significantly slow down the loading speed.



> Related ideas: lazy tensors.

I don't think this has anything to do with lazy tensors. I think this is just a memory management issue in the functions related to loading the model. Improvements or solutions to this problem can be applied to any Torch tensor/model.

**Comment by mikaylagawarecki** [comment]
@KaneGreen 

Can you try the following:

```
with torch.device('meta'):
    m = YourModule()
sd = torch.load(..., mmap=True)
m.load_state_dict(sd, assign=True)
```

**Comment by KaneGreen** [comment]
> note that `skip_init` skips initialization but will still materialize the tensors.

I'm sorry, maybe I didn't express it clearly enough. My question has nothing to do with how to initialize the model.

Please look at the picture in my post. Each number in the picture corresponds to when the code block starts executing.

I'm not complaining about the memory increase between [3]~[4], because that's the weight the model should have. In other words, regardless of whether I use `skip_init` or `device='meta'`, for the model to really work, sooner or later I need the model to have real weights. Therefore this part of memory is necessary.

What I'm really complaining about in this issue is the rise and then fall after [4]. From the graph, it seems that PyTorch creates a new variable, allocates a new memory area, loads the weights here first (regardless of whether `mmap=True` is used), and then copies it from this area to the real model. weight position, and finally clean up this part of the memory space.

Think about it, let's say your computer has 32GB of memory and you are playing with a 24GB model (mainly for inference rather than training). In theory you can load this model successfully. However, the problem mentioned in this issue will cause you have to install 64GB of memory to successfully load. If you do not want use a huge and slow swap (because the memory also stores some content running the operating system, Python runtime, etc., 48GB There won’t be enough memory). That expensive 64GB of memory is idle when not running models, which is not a good investment.

**Comment by mikaylagawarecki** [comment]
Would you be willing to check whether you see the same behavior with the meta device and `load_state_dict(assign=True)` in the snippet above?

**Comment by KaneGreen** [comment]
@mikaylagawarecki This saves the memory. But not all.
 
I found some modes loading weight like `model.load_state_dict(torch.load(model_path))`, these work.
and others like `model.load_state_dict(torch.load(model_path)['model_state_dict'])`, these don't work.

**Comment by KaneGreen** [comment]
I need some time.
I didn't noticed the difference between `model.load_state_dict(torch.load(model_path))` and `model.load_state_dict(torch.load(model_path)['model_state_dict'])`. I need to learn more about the `load_state_dict` and `load` API.

**Comment by KaneGreen** [comment]
@mikaylagawarecki I've tried `torch.device('meta')` and `assign=True`, but without `mmap=True`, this works well.
Thanks for your help. 👍
