### ISSUE TITLE
`@functools.wraps` graph breaks in many cases where we should be able to handle it

### ISSUE THREAD

**Issue by guilhermeleobas** [pytorch/pytorch#123365]
### 🐛 Describe the bug

Currently, PyTorch crashes if two functions annotated with `@functools.wraps(func)` are composed together. As an example, when adding support for `torch.func.hessian` in https://github.com/pytorch/pytorch/pull/121410, `wraps` is conditionally used  in `jacrev/jacfwd` if dynamo is not compiling:

* `torch.func.eager_transforms.jacfwd`:
https://github.com/pytorch/pytorch/blob/98e5238ad8b23d62f52549c88ee39f7cbacb46d8/torch/_functorch/eager_transforms.py#L697-L703

* `torch.func.eager_transforms.jacrev`:
https://github.com/pytorch/pytorch/blob/98e5238ad8b23d62f52549c88ee39f7cbacb46d8/torch/_functorch/eager_transforms.py#L1223-L1226

This is because Dynamo treats some of those variables internally as `NestedUserFunctionVariable` and tries to reconstruct it in `SkipFunctionsVariable::call_function`
https://github.com/pytorch/pytorch/blob/98e5238ad8b23d62f52549c88ee39f7cbacb46d8/torch/_dynamo/variables/functions.py#L615-L622

The current approach works but at some point one should revert this and fix the issue, as this same bug appeared in other tests as well: https://github.com/pytorch/pytorch/pull/123357

### Versions

PyTorch main branch

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @zou3519 @ydwu4

**Comment by zou3519** [comment]
The root cause of this is that Dynamo has problems with functools.wraps. It's independent from the HOP mechanism.

**Comment by zou3519** [comment]
@guilhermeleobas do you remember the test case for this? We did some work on functools.partial that may have fixed the problem

**Comment by zou3519** [comment]
Doesn't seem to work yet: https://github.com/pytorch/pytorch/pull/127302
