### ISSUE TITLE
Slow DataLoader in new version when num_workers>0 / objects in collate_fn slow down batching

### ISSUE THREAD

**Issue by yermandy** [pytorch/pytorch#123439]
Hello, I experience slow data loading while using DataLoader in recent pytorch versions. Here is the code:

``` python
from time import perf_counter

import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

torch.random.manual_seed(0)


class Dataset:
    def __init__(self, size: int):
        self.data = torch.rand(size, 2).numpy()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, i):
        d = self.data[i]
        return {"feature": d[0], "target": d[1]}


SIZE = 1024 * 100
BATCH_SIZE = 1024

dataset = Dataset(size=SIZE)

times = []

for workers in range(0, 23, 1):
    loader = DataLoader(dataset=dataset, batch_size=BATCH_SIZE, num_workers=workers)

    t = perf_counter()
    for x in loader:
        continue
    t = perf_counter() - t
    times.append((workers, t))
    print(f"workers={workers}: {t:.2f}s")
```

--- 

In 
```
python                    3.12.2
pytorch                   2.2.2
```

I am getting
```
workers=0: 0.16s
workers=1: 0.70s
workers=2: 0.55s
workers=3: 0.47s
workers=4: 0.44s
workers=5: 0.44s
workers=6: 0.46s
workers=7: 0.47s
workers=8: 0.49s
workers=9: 0.48s
workers=10: 0.51s
workers=11: 0.51s
workers=12: 0.51s
workers=13: 0.57s
workers=14: 0.56s
workers=15: 0.56s
workers=16: 0.67s
workers=17: 0.58s
workers=18: 0.61s
workers=19: 0.67s
workers=20: 0.67s
workers=21: 0.67s
workers=22: 0.65s
```

--- 

In 
```
python                    3.9.0
pytorch                   1.11.0
```

I am getting 

```
workers=0: 0.13s
workers=1: 0.33s
workers=2: 0.19s
workers=3: 0.15s
workers=4: 0.17s
workers=5: 0.16s
workers=6: 0.18s
workers=7: 0.22s
workers=8: 0.16s
workers=9: 0.25s
workers=10: 0.21s
workers=11: 0.22s
workers=12: 0.24s
workers=13: 0.25s
workers=14: 0.25s
workers=15: 0.34s
workers=16: 0.33s
workers=17: 0.32s
workers=18: 0.26s
workers=19: 0.29s
workers=20: 0.28s
workers=21: 0.31s
workers=22: 0.31s
```

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.4
Libc version: glibc-2.35

Python version: 3.9.0 (default, Nov 15 2020, 14:28:56)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-101-generic-x86_64-with-glibc2.35

---

PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.0
Libc version: glibc-2.35

Python version: 3.12.2 | packaged by Anaconda, Inc. | (main, Feb 27 2024, 17:35:02) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-101-generic-x86_64-with-glibc2.35

cc @SsnL @VitalyFedyunin @ejguan @dzhulgakov

**Comment by yermandy** [comment]
The problem is more pronounced when using `self.data  = torch.rand(size, 2).numpy()`. I guess it might have something to do with `collate_fn`? 

When running with `self.data  =  torch.rand(size, 2)`, I am getting somewhat expected results but still much slower than the previous version

**pytorch v.2.2.2**

```
workers=0: 0.74s
workers=1: 1.30s
workers=2: 0.85s
workers=3: 0.78s
workers=4: 0.74s
workers=5: 0.74s
workers=6: 0.72s
workers=7: 0.65s
workers=8: 0.65s
workers=9: 0.61s
workers=10: 0.64s
workers=11: 0.63s
workers=12: 0.70s
workers=13: 0.64s
workers=14: 0.69s
workers=15: 0.68s
workers=16: 0.77s
workers=17: 0.69s
workers=18: 0.68s
workers=19: 0.71s
workers=20: 0.76s
workers=21: 0.69s
workers=22: 0.76s
```

---

**pytorch v.1.11.0**

```
workers=0: 0.58s
workers=1: 0.70s
workers=2: 0.44s
workers=3: 0.35s
workers=4: 0.43s
workers=5: 0.39s
workers=6: 0.34s
workers=7: 0.27s
workers=8: 0.25s
workers=9: 0.29s
workers=10: 0.32s
workers=11: 0.30s
workers=12: 0.30s
workers=13: 0.41s
workers=14: 0.41s
workers=15: 0.28s
workers=16: 0.34s
workers=17: 0.33s
workers=18: 0.39s
workers=19: 0.37s
workers=20: 0.46s
workers=21: 0.41s
workers=22: 0.42s
```

**Comment by tringwald** [comment]
I can confirm that `2.2.2` seems to be consistently slower. Additionally, the `.numpy()` version was always faster by a very large margin.

**Comment by yermandy** [comment]
pytorch v.2.0.1 still performs better than v.2.2.2

Firstly, workers help. Secondly, data loading from numpy performs much faster than torch or numpy of version v.2.2.2

**Comment by yermandy** [comment]
Here is the code for testing:
``` python
from time import perf_counter

import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

torch.random.manual_seed(0)


class Dataset:
    def __init__(self, size: int, numpy: bool):
        self.data = torch.rand(size, 2)
        if numpy:
            self.data = self.data.numpy()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, i):
        d = self.data[i]
        return {"feature": d[0], "target": d[1]}


SIZE = 1024 * 100
BATCH_SIZE = 1024

for numpy in [True, False]:
    dataset = Dataset(size=SIZE, numpy=numpy)

    times = []

    print("-" * 20 + f"\n{numpy=}\n")

    for workers in range(0, 23, 1):
        loader = DataLoader(dataset=dataset, batch_size=BATCH_SIZE, num_workers=workers)

        t = perf_counter()
        for x in loader:
            continue
        t = perf_counter() - t
        times.append((workers, t))
        print(f"workers={workers}: {t:.2f}s")
```

**Comment by yermandy** [comment]
And my results are:

**pytorch v.2.2.2**
```
--------------------
numpy=True

workers=0: 0.13s
workers=2: 0.47s
workers=4: 0.46s
workers=6: 0.46s
workers=8: 0.50s
workers=10: 0.56s
workers=12: 0.58s
--------------------
numpy=False

workers=0: 0.77s
workers=2: 0.83s
workers=4: 0.75s
workers=6: 0.70s
workers=8: 0.62s
workers=10: 0.72s
workers=12: 0.70s
```

**pytorch v.2.0.1**
```
--------------------
numpy=True

workers=0: 0.14s
workers=2: 0.17s
workers=4: 0.17s
workers=6: 0.16s
workers=8: 0.23s
workers=10: 0.26s
workers=12: 0.27s
--------------------
numpy=False

workers=0: 0.73s
workers=2: 0.60s
workers=4: 0.52s
workers=6: 0.30s
workers=8: 0.30s
workers=10: 0.34s
workers=12: 0.39s
```

**Comment by yermandy** [comment]
Can someone look at the issue? These performance drops because of the slow loading in later versions are killing me

<img width="1502" alt="Screenshot 2024-04-05 at 13 30 01" src="https://github.com/pytorch/pytorch/assets/39454881/3e7323d4-fc3e-41c1-8ee9-34051c514205">

**Comment by yermandy** [comment]
I found another weird behavior: when I want to construct a batch using `collate_fn` and transfer an instance of some non-trivial object, I get huge lags, example:


``` python
    def __getitem__(self, i):
        d = self.data[i]
        object = Target(np.zeros((100, 100, 3)), np.zeros((0, 4)), classes=np.zeros(0))
        return {
            "feature": d[0],
            "target": d[1],
            "object": object,
        }

    @staticmethod
    def collate_fn(batch):
        # remove object from batch
        [x.pop("object", None) for x in batch] # comment or uncomment
        return batch
```

**pytorch v.2.2.2**
When I use `[x.pop("object", None) for x in batch]`, I am getting

```
--------------------
numpy=True

workers=0: 0.53s
workers=2: 0.46s
workers=4: 0.39s
workers=6: 0.37s
workers=8: 0.42s
workers=10: 0.47s
workers=12: 0.47s
--------------------
numpy=False

workers=0: 0.63s
workers=2: 1.11s
workers=4: 0.95s
workers=6: 0.92s
workers=8: 0.80s
workers=10: 0.82s
workers=12: 0.90s
```

When I comment `[x.pop("object", None) for x in batch]`, I am getting:

```
--------------------
numpy=True

workers=0: 0.58s
workers=2: 9.58s
workers=4: 9.82s
workers=6: 9.95s
workers=8: 9.77s
workers=10: 10.03s
workers=12: 9.87s
--------------------
numpy=False

workers=0: 0.56s
workers=2: 11.20s
workers=4: 11.32s
workers=6: 11.18s
workers=8: 11.10s
workers=10: 11.36s
workers=12: 12.24s
```

**Comment by yermandy** [comment]
So, I can clearly see that something is happening under the hood to object instances after `collate_fn` is executed. Can someone explain what is going on and how to overcome this? I would like to make a batch of objects in addition to tensors

``` python
from time import perf_counter

import numpy as np
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

torch.random.manual_seed(0)


class SomeObject:
    def __init__(
        self,
    ):
        self.data_torch = torch.rand(100000).numpy()


class Dataset:
    def __init__(self, size: int, numpy: bool):
        self.data = torch.rand(size, 2)
        self.object = [SomeObject() for _ in range(size)]
        if numpy:
            self.data = self.data.numpy()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, i):
        d = self.data[i]
        return {
            "feature": d[0],
            "target": d[1],
            "object": self.object[i],
        }

    @staticmethod
    def collate_fn(batch, remove_object):
        if remove_object:
            [x.pop("object", None) for x in batch]
        return batch


SIZE = 1024 * 10
BATCH_SIZE = 2048

print(f"\ntorch version: {torch.__version__}")

for remove_object in [True, False]:
    for pin_memory in [False, True]:
        for numpy in [True]:
            dataset = Dataset(size=SIZE, numpy=numpy)

            times = []

            print("\n" + "-" * 20 + f"\n{numpy=} {pin_memory=} {remove_object=}\n")

            for workers in range(0, 13, 2):
                loader = DataLoader(
                    dataset=dataset,
                    batch_size=BATCH_SIZE,
                    num_workers=workers,
                    collate_fn=lambda batch: Dataset.collate_fn(batch, remove_object),
                    pin_memory=pin_memory,
                )

                t = perf_counter()
                for x in loader:
                    continue
                t = perf_counter() - t
                times.append((workers, t))
                print(f"workers={workers}: {t:.2f}s")
```

Results:
```
torch version: 2.2.2

--------------------
numpy=True pin_memory=False remove_object=True

workers=0: 0.01s
workers=2: 0.27s
workers=4: 0.39s
workers=6: 0.50s
workers=8: 0.65s
workers=10: 0.76s
workers=12: 0.89s

--------------------
numpy=True pin_memory=True remove_object=True

workers=0: 0.79s
workers=2: 0.50s
workers=4: 0.72s
workers=6: 0.93s
workers=8: 1.12s
workers=10: 1.34s
workers=12: 1.56s

--------------------
numpy=True pin_memory=False remove_object=False

workers=0: 0.01s
workers=2: 6.97s
workers=4: 7.26s
workers=6: 7.33s
workers=8: 7.58s
workers=10: 7.73s
workers=12: 7.93s

--------------------
numpy=True pin_memory=True remove_object=False

workers=0: 0.04s
workers=2: 5.87s
workers=4: 6.37s
workers=6: 6.82s
workers=8: 7.47s
workers=10: 8.07s
workers=12: 8.52s
```

**Comment by tringwald** [comment]
I'd assume that arbitrary Python objects do have to be pickled and unpickled when using multiple processes, which can be rather expensive in the general case.

**Comment by yermandy** [comment]
@tringwald, that is a pity. Sometimes user may want to send information in a structured way, especially when sending lots of different attributes which will be needed in a training loop. Sending them separately is rather an ugly solution IMHO. Any idea how to overcome this?

**Comment by tringwald** [comment]
Can you try if this works out for you?

```python3
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')

class SomeObject:
    def __init__(
            self,
    ):
        self.data_torch = torch.empty(100000)
        self.data_torch.share_memory_()
```

**Comment by yermandy** [comment]
@tringwald wow, thank you! It works much better for this dummy example as well as in my work project where object has multiple attributes. This is already a huge improvement. I wonder if this logic will be somehow chaged in future pytorch versions. What are the downsides of this approach?

**Comment by tringwald** [comment]
From what I can see in the code, `sharing_strategy = 'file_system'` is already the default on MacOS and Windows. I don't know if there are any plans to make this the default on Linux, too.

**Comment by yermandy** [comment]
> I'd assume that arbitrary Python objects do have to be pickled and unpickled when using multiple processes, which can be rather expensive in the general case.

I think I finally understand what is going on here. To send data from multiple threads (e.g. when num_workers > 0), we need to pickle (convert Python object to bytes) objects in every thread and send them to the main process. The pipeline goes as such: 

1. `__get_item__` (in non-main thread)
2. `collate_fn(batch)` → returns **post-processed batch**  (in non-main thread)
3. pickling **post-processed batch**  → returns **bytes**  (in non-main thread)
4. sending **bytes** to the main thread
5. unpickling bytes → returns **post-processed batch** (on main thread)
6. getting batch using e.g. `next(item(loader))` (on main thread)

The main problem lies in steps number (3) and (5), where the main idea is to send the object to the main thread.  What I found out is that pickling and unpickling Tensor objects is a very costly operation compared to pickling and unpickling numpy arrays. 

For instance, if my **post-processed batch** will contain an array of [object_1, object_2, ..., object_N] and each object_i has a Tensor object as an attribute, it will be much more expensive to perform steps (3) and (5) than if the attribute has a numpy array type. 

The first solution is: make sure that step (2) (`collate_fn(batch)`) does not contain `torch.Tensor` object but `np.ndarray` and convert `torch.Tensor` → `np.ndarray` after step (6)

**Comment by aldakata** [comment]
How can this issue be closed? Maybe an example/documentation post would be the way to go

**Comment by ManUtdMoon** [comment]
> > I'd assume that arbitrary Python objects do have to be pickled and unpickled when using multiple processes, which can be rather expensive in the general case.
> 
> 
> 
> I think I finally understand what is going on here. To send data from multiple threads (e.g. when num_workers > 0), we need to pickle (convert Python object to bytes) objects in every thread and send them to the main process. The pipeline goes as such: 
> 
> 
> 
> 1. `__get_item__` (in non-main thread)
> 
> 2. `collate_fn(batch)` → returns **post-processed batch**  (in non-main thread)
> 
> 3. pickling **post-processed batch**  → returns **bytes**  (in non-main thread)
> 
> 4. sending **bytes** to the main thread
> 
> 5. unpickling bytes → returns **post-processed batch** (on main thread)
> 
> 6. getting batch using e.g. `next(item(loader))` (on main thread)
> 
> 
> 
> The main problem lies in steps number (3) and (5), where the main idea is to send the object to the main thread.  What I found out is that pickling and unpickling Tensor objects is a very costly operation compared to pickling and unpickling numpy arrays. 
> 
> 
> 
> For instance, if my **post-processed batch** will contain an array of [object_1, object_2, ..., object_N] and each object_i has a Tensor object as an attribute, it will be much more expensive to perform steps (3) and (5) than if the attribute has a numpy array type. 
> 
> 
> 
> The first solution is: make sure that step (2) (`collate_fn(batch)`) does not contain `torch.Tensor` object but `np.ndarray` and convert `torch.Tensor` → `np.ndarray` after step (6)

Hi,
Thanks for your examples and advice! But I am a bit confused that why we need to convert `torch.Tensor` → `np.ndarray` after step (6). I think that a batch of Tensor is what we need? If we turn everything into np.array, where should we convert batch back to tensor?
