### ISSUE TITLE
API to annotate regions in the memory snapshot tool's Active Memory Timeline

### ISSUE THREAD

**Issue by xmfan** [pytorch/pytorch#123408]
### 🚀 The feature, motivation and pitch

The CUDA memory snapshot tool has been fantastic for deep diving into the memory usage of my program. But I find myself often lost in where a certain allocation is happening in the snapshot.

Allocations from Python aren't that of a problem since we have the stack trace by default (still you need to have good intuition on which allocation's stack trace to look at). But the user experience to dive into C++ allocations isn't great:
1. No stack trace unless you build from source with REL_WITH_DEB_INFO=1
2. Very long symbolication time with REL_WITH_DEB_INFO=1, even simple programs are hanging after finishing execution for 20 minutes on devgpu

A quick workaround I've been using is to create memory markers by allocating huge chunks of memory and deallocating them immediately. This shows up as spikes in the timeline and helps me identify which part of the stack I'm in. It would be great if we could have a built-in visual helper for something like this in https://pytorch.org/memory_viz.
<img width="1586" alt="image" src="https://github.com/pytorch/pytorch/assets/9547562/4c164908-6644-41ce-a0d6-0847fb259596">

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by aaronenyeshi** [comment]
We are looking into adding user defined annotations, however running into some CI failures. More details here: https://github.com/pytorch/pytorch/pull/124179

**Comment by xmfan** [comment]
will there be a python API?

**Comment by sraikund16** [comment]
It looks like https://github.com/pytorch/pytorch/pull/129072/files#diff-673455c92ce1e6c65b0d106b067cf3882f91cd7d30d4f74ee4f6f60ceb6e0db3R971 added annotations by adding a callback when a RecordFunction in the profiler is used. Is this sufficient for your usecase?
