### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator Scatter

### ISSUE THREAD

**Issue by uhvardhan** [pytorch/pytorch#12346]
## ❓ Questions and Help

I am trying to export a pretrained pytorch model (pth model) to onnx format first. I get the above runtime error.
`Traceback (most recent call last):
  File "/tmp/pycharm_project_896/utils/pytorch2onnx.py", line 15, in <module>
    torch.onnx.export(model.module, dummy_input, "/neutrino/models/pretrained/huawei/model.onnx")
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/__init__.py", line 75, in export
    _export(model, args, f, export_params, verbose, training)
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/__init__.py", line 131, in _export
    proto = trace.export(list(model.state_dict().values()), _onnx_opset_version)
RuntimeError: ONNX export failed: Couldn't export Python operator Scatter

Graph we tried to export:
graph(%1 : Float(1, 3, 224, 224)
      %2 : Float(4, 3, 7, 7)
      %3 : Float(4)
      %4 : Float(4)
      %5 : Float(4)
      %6 : Float(4)
      %7 : Float(4, 4, 3, 3)
      %8 : Float(4)
      %9 : Float(4)
      %10 : Float(4)
      %11 : Float(4)
      %12 : Float(4, 4, 3, 3)
      %13 : Float(4)
      %14 : Float(4)
      %15 : Float(4)
      %16 : Float(4)
      %17 : Float(6, 4, 3, 3)
      %18 : Float(6)
      %19 : Float(6)
      %20 : Float(6)
      %21 : Float(6)
      %22 : Float(6, 6, 3, 3)
      %23 : Float(6)
      %24 : Float(6)
      %25 : Float(6)
      %26 : Float(6)
      %27 : Float(6, 4, 1, 1)
      %28 : Float(6)
      %29 : Float(6)
      %30 : Float(6)
      %31 : Float(6)
      %32 : Float(98, 6, 3, 3)
      %33 : Float(98)
      %34 : Float(98)
      %35 : Float(98)
      %36 : Float(98)
      %37 : Float(98, 98, 3, 3)
      %38 : Float(98)
      %39 : Float(98)
      %40 : Float(98)
      %41 : Float(98)
      %42 : Float(98, 6, 1, 1)
      %43 : Float(98)
      %44 : Float(98)
      %45 : Float(98)
      %46 : Float(98)
      %47 : Float(160, 98, 3, 3)
      %48 : Float(160)
      %49 : Float(160)
      %50 : Float(160)
      %51 : Float(160)
      %52 : Float(160, 160, 3, 3)
      %53 : Float(160)
      %54 : Float(160)
      %55 : Float(160)
      %56 : Float(160)
      %57 : Float(160, 98, 1, 1)
      %58 : Float(160)
      %59 : Float(160)
      %60 : Float(160)
      %61 : Float(160)
      %62 : Float(16, 160)
      %63 : Float(16)) {
  %65 : Float(1, 3, 224, 224), %66 : Handle = ^Scatter([0], None, 0)(%1), uses = [[%68.i0], []], scope: DataParallel;
  %68 : Float(1, 4, 112, 112) = Conv[kernel_shape=[7, 7], strides=[2, 2], pads=[3, 3, 3, 3], dilations=[1, 1], group=1](%65, %2), uses = [%69.i0], scope: DataParallel/ResNet[module]/Conv2d[conv1];
  %70 : Float(1, 4, 112, 112) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%68, %3, %4, %5, %6), uses = [[%71.i0]], scope: DataParallel/ResNet[module]/BatchNorm2d[bn1];
  %71 : Float(1, 4, 112, 112) = Relu(%70), uses = [%72.i0], scope: DataParallel/ResNet[module]/ReLU[relu];
  %72 : Float(1, 4, 56, 56) = MaxPool[kernel_shape=[3, 3], pads=[1, 1], strides=[2, 2]](%71), uses = [%74.i0, %82.i1], scope: DataParallel/ResNet[module]/MaxPool2d[maxpool];
  %74 : Float(1, 4, 56, 56) = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%72, %7), uses = [%75.i0], scope: DataParallel/ResNet[module]/Sequential[layer1]/BasicBlock[0]/Conv2d[conv1];
  %76 : Float(1, 4, 56, 56) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%74, %8, %9, %10, %11), uses = [[%77.i0]], scope: DataParallel/ResNet[module]/Sequential[layer1]/BasicBlock[0]/BatchNorm2d[bn1];
  %77 : Float(1, 4, 56, 56) = Relu(%76), uses = [%79.i0], scope: DataParallel/ResNet[module]/Sequential[layer1]/BasicBlock[0]/ReLU[relu];
  %79 : Float(1, 4, 56, 56) = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%77, %12), uses = [%80.i0], scope: DataParallel/ResNet[module]/Sequential[layer1]/BasicBlock[0]/Conv2d[conv2];
  %81 : Float(1, 4, 56, 56) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%79, %13, %14, %15, %16), uses = [[%82.i0]], scope: DataParallel/ResNet[module]/Sequential[layer1]/BasicBlock[0]/BatchNorm2d[bn2];
  %82 : Float(1, 4, 56, 56) = Add(%81, %72), uses = [%83.i0], scope: DataParallel/ResNet[module]/Sequential[layer1]/BasicBlock[0];
  %83 : Float(1, 4, 56, 56) = Relu(%82), uses = [%85.i0, %94.i0], scope: DataParallel/ResNet[module]/Sequential[layer1]/BasicBlock[0]/ReLU[relu];
  %85 : Float(1, 6, 28, 28) = Conv[kernel_shape=[3, 3], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%83, %17), uses = [%86.i0], scope: DataParallel/ResNet[module]/Sequential[layer2]/BasicBlock[0]/Conv2d[conv1];
  %87 : Float(1, 6, 28, 28) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%85, %18, %19, %20, %21), uses = [[%88.i0]], scope: DataParallel/ResNet[module]/Sequential[layer2]/BasicBlock[0]/BatchNorm2d[bn1];
  %88 : Float(1, 6, 28, 28) = Relu(%87), uses = [%90.i0], scope: DataParallel/ResNet[module]/Sequential[layer2]/BasicBlock[0]/ReLU[relu];
  %90 : Float(1, 6, 28, 28) = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%88, %22), uses = [%91.i0], scope: DataParallel/ResNet[module]/Sequential[layer2]/BasicBlock[0]/Conv2d[conv2];
  %92 : Float(1, 6, 28, 28) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%90, %23, %24, %25, %26), uses = [[%97.i0]], scope: DataParallel/ResNet[module]/Sequential[layer2]/BasicBlock[0]/BatchNorm2d[bn2];
  %94 : Float(1, 6, 28, 28) = Conv[kernel_shape=[1, 1], strides=[2, 2], pads=[0, 0, 0, 0], dilations=[1, 1], group=1](%83, %27), uses = [%95.i0], scope: DataParallel/ResNet[module]/Sequential[layer2]/BasicBlock[0]/Sequential[downsample]/Conv2d[0];
  %96 : Float(1, 6, 28, 28) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%94, %28, %29, %30, %31), uses = [[%97.i1]], scope: DataParallel/ResNet[module]/Sequential[layer2]/BasicBlock[0]/Sequential[downsample]/BatchNorm2d[1];
  %97 : Float(1, 6, 28, 28) = Add(%92, %96), uses = [%98.i0], scope: DataParallel/ResNet[module]/Sequential[layer2]/BasicBlock[0];
  %98 : Float(1, 6, 28, 28) = Relu(%97), uses = [%100.i0, %109.i0], scope: DataParallel/ResNet[module]/Sequential[layer2]/BasicBlock[0]/ReLU[relu];
  %100 : Float(1, 98, 14, 14) = Conv[kernel_shape=[3, 3], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%98, %32), uses = [%101.i0], scope: DataParallel/ResNet[module]/Sequential[layer3]/BasicBlock[0]/Conv2d[conv1];
  %102 : Float(1, 98, 14, 14) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%100, %33, %34, %35, %36), uses = [[%103.i0]], scope: DataParallel/ResNet[module]/Sequential[layer3]/BasicBlock[0]/BatchNorm2d[bn1];
  %103 : Float(1, 98, 14, 14) = Relu(%102), uses = [%105.i0], scope: DataParallel/ResNet[module]/Sequential[layer3]/BasicBlock[0]/ReLU[relu];
  %105 : Float(1, 98, 14, 14) = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%103, %37), uses = [%106.i0], scope: DataParallel/ResNet[module]/Sequential[layer3]/BasicBlock[0]/Conv2d[conv2];
  %107 : Float(1, 98, 14, 14) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%105, %38, %39, %40, %41), uses = [[%112.i0]], scope: DataParallel/ResNet[module]/Sequential[layer3]/BasicBlock[0]/BatchNorm2d[bn2];
  %109 : Float(1, 98, 14, 14) = Conv[kernel_shape=[1, 1], strides=[2, 2], pads=[0, 0, 0, 0], dilations=[1, 1], group=1](%98, %42), uses = [%110.i0], scope: DataParallel/ResNet[module]/Sequential[layer3]/BasicBlock[0]/Sequential[downsample]/Conv2d[0];
  %111 : Float(1, 98, 14, 14) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%109, %43, %44, %45, %46), uses = [[%112.i1]], scope: DataParallel/ResNet[module]/Sequential[layer3]/BasicBlock[0]/Sequential[downsample]/BatchNorm2d[1];
  %112 : Float(1, 98, 14, 14) = Add(%107, %111), uses = [%113.i0], scope: DataParallel/ResNet[module]/Sequential[layer3]/BasicBlock[0];
  %113 : Float(1, 98, 14, 14) = Relu(%112), uses = [%115.i0, %124.i0], scope: DataParallel/ResNet[module]/Sequential[layer3]/BasicBlock[0]/ReLU[relu];
  %115 : Float(1, 160, 7, 7) = Conv[kernel_shape=[3, 3], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%113, %47), uses = [%116.i0], scope: DataParallel/ResNet[module]/Sequential[layer4]/BasicBlock[0]/Conv2d[conv1];
  %117 : Float(1, 160, 7, 7) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%115, %48, %49, %50, %51), uses = [[%118.i0]], scope: DataParallel/ResNet[module]/Sequential[layer4]/BasicBlock[0]/BatchNorm2d[bn1];
  %118 : Float(1, 160, 7, 7) = Relu(%117), uses = [%120.i0], scope: DataParallel/ResNet[module]/Sequential[layer4]/BasicBlock[0]/ReLU[relu];
  %120 : Float(1, 160, 7, 7) = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%118, %52), uses = [%121.i0], scope: DataParallel/ResNet[module]/Sequential[layer4]/BasicBlock[0]/Conv2d[conv2];
  %122 : Float(1, 160, 7, 7) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%120, %53, %54, %55, %56), uses = [[%127.i0]], scope: DataParallel/ResNet[module]/Sequential[layer4]/BasicBlock[0]/BatchNorm2d[bn2];
  %124 : Float(1, 160, 7, 7) = Conv[kernel_shape=[1, 1], strides=[2, 2], pads=[0, 0, 0, 0], dilations=[1, 1], group=1](%113, %57), uses = [%125.i0], scope: DataParallel/ResNet[module]/Sequential[layer4]/BasicBlock[0]/Sequential[downsample]/Conv2d[0];
  %126 : Float(1, 160, 7, 7) = BatchNormalization[is_test=1, epsilon=1e-05, momentum=0.9, consumed_inputs=[0, 0, 0, 1, 1]](%124, %58, %59, %60, %61), uses = [[%127.i1]], scope: DataParallel/ResNet[module]/Sequential[layer4]/BasicBlock[0]/Sequential[downsample]/BatchNorm2d[1];
  %127 : Float(1, 160, 7, 7) = Add(%122, %126), uses = [%128.i0], scope: DataParallel/ResNet[module]/Sequential[layer4]/BasicBlock[0];
  %128 : Float(1, 160, 7, 7) = Relu(%127), uses = [%129.i0], scope: DataParallel/ResNet[module]/Sequential[layer4]/BasicBlock[0]/ReLU[relu];
  %129 : Float(1, 160, 1, 1) = AveragePool[kernel_shape=[7, 7], pads=[0, 0], strides=[1, 1]](%128), uses = [%130.i0], scope: DataParallel/ResNet[module]/AvgPool2d[avgpool];
  %130 : Float(1, 160) = Reshape[shape=[1, -1]](%129), uses = [%133.i0], scope: DataParallel/ResNet[module];
  %133 : Float(1, 16) = Gemm[alpha=1, beta=1, broadcast=1, transB=1](%130, %62, %63), uses = [%0.i0], scope: DataParallel/ResNet[module]/Linear[fc];
  return (%133);
}`

Thanks in advance.

**Comment by bhack** [comment]
@zou3519 The same appen for JIT can you add the JIT label.
@uhvardhan See https://github.com/pytorch/pytorch/issues/5315

**Comment by ngimel** [comment]
Closing due to age
