### ISSUE TITLE
Compiling optimizers with closure argument

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#123479]
### 🚀 The feature, motivation and pitch

Today we don't compile the optimizer if a closure is present and fall back to eager. The main reason for this is that a graph break in the top level optimizer step call will not allow dynamo to properly initialize the optimizer (since it will no longer interpret that frame). I'm publishing this issue to track if this feature is desirable for users.

Ex.
```py
import torch     
weight = Parameter(torch.randn((10, 5, 2), device=device, dtype=dtype)[..., 0])
bias = Parameter(torch.randn((10, 2), device=device, dtype=dtype)[..., 0])
input = torch.randn(5, device=device, dtype=dtype)

optimizer = torch.optim.Adam([weight, bias], **optim_input.kwargs)
schedulers = [s(optimizer) for s in (schedulers_constructor if schedulers_constructor else [])]

def closure():
    optimizer.zero_grad()
    loss = (weight.mv(input) + bias).pow(2).sum()
    loss.backward()
    return loss

optim.step(closure)
```

The current workaround is to call the closure outside of the optimizer like so:
Ex.
```py
import torch     
weight = Parameter(torch.randn((10, 5, 2), device=device, dtype=dtype)[..., 0])
bias = Parameter(torch.randn((10, 2), device=device, dtype=dtype)[..., 0])
input = torch.randn(5, device=device, dtype=dtype)

optimizer = torch.optim.Adam([weight, bias], **optim_input.kwargs)
schedulers = [s(optimizer) for s in (schedulers_constructor if schedulers_constructor else [])]

def closure():
    optimizer.zero_grad()
    loss = (weight.mv(input) + bias).pow(2).sum()
    loss.backward()
    return loss

closure()
optim.step()
```

If compiling with closure would be helpful to you please comment below with your use case.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @janeyx99

**Comment by ezyang** [comment]
I'm not sure how people are going to find this issue lol

**Comment by mlazos** [comment]
> I'm not sure how people are going to find this issue lol

What do you mean? I originally referenced this in our code in an abandoned PR. However I ended up handling this instead of falling back in a new linked PR so this will get closed soon.
