### ISSUE TITLE
DISABLED test_fuse_attention_all_patterns_serialized (__main__.TestPatternMatcher)

### ISSUE THREAD

**Issue by pruthvistony** [pytorch/pytorch#123418]
Platforms: CUDA and ROCm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_pattern_matcher.py%3A%3ATestPatternMatcher%3A%3Atest_fuse_attention_all_patterns_serialized%22%5D)).

**Comment by huydhn** [comment]
I have reverted the change responsible for this in https://hud.pytorch.org/pytorch/pytorch/commit/16cb5d48dd9b03944b9245fb5d96b05ea7c9c37a, so let's try to close this issues
