### ISSUE TITLE
Inductor: expected scalar type Long but found Float for int literal

### ISSUE THREAD

**Issue by d4l3k** [pytorch/pytorch#123471]
### 🐛 Describe the bug

Inductor seems to be casting the literal `2` to be a float when the operator takes in a SymInt. There's no errors with the `aot_eager` backend.

Stack trace:
```py
  File "/tmp/torchinductor_tristanr/a4/ca46jvrf7rkkpgzx2zsnetelaseo34prvwgyuh7fu6gzgmthtgqf.py", line 108, in call
    buf4 = torch.ops._c10d_functional.all_to_all_single.default(2, buf1, buf2, buf3, '0')
  File "/home/tristanr/pytorch/torch/_ops.py", line 610, in __call__
    return self_._op(*args, **kwargs)
RuntimeError: expected scalar type Long but found Float
```

Generated .py file:
```py
    buf4 = torch.ops._c10d_functional.all_to_all_single.default(2, buf1, buf2, buf3, '0')
```

Operator signature
```cpp
  m.def(
      "all_to_all_single("
      "SymInt output_size,"
      "Tensor input, "
      "Tensor output_split_sizes, "
      "Tensor input_split_sizes, "
      "str group_name) -> Tensor",
      torch::dispatch(
          c10::DispatchKey::CompositeExplicitAutograd, ::all_to_all_single),
      {at::Tag::pt2_compliant_tag});
```

Full logs and generated file: https://gist.github.com/d4l3k/ec722441367394d86bf0279ef3eb0900
PR: with backend changed to inductor https://github.com/pytorch/pytorch/pull/123420/files

### Versions

Collecting environment information...
PyTorch version: 2.4.0a0+gite95ffde
Is debug build: True
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.34

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-0_fbk12_hardened_11583_g0bef9520ca2b-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100
GPU 1: NVIDIA H100
GPU 2: NVIDIA H100
GPU 3: NVIDIA H100

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          184
On-line CPU(s) list:             0-183
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 9654 96-Core Processor
CPU family:                      25
Model:                           17
Thread(s) per core:              1
Core(s) per socket:              184
Socket(s):                       1
Stepping:                        1
BogoMIPS:                        4792.79
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 clzero xsaveerptr wbnoinvd arat npt lbrv nrip_save tsc_scale vmcb_clean pausefilter pfthreshold v_vmsave_vmload vgif avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
Virtualization:                  AMD-V
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       11.5 MiB (184 instances)
L1i cache:                       11.5 MiB (184 instances)
L2 cache:                        92 MiB (184 instances)
L3 cache:                        2.9 GiB (184 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-183
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-coding==1.3.3
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.8.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.10.0
[pip3] pytorch-triton==3.0.0+a9bc1a3647
[pip3] torch==2.4.0a0+gite95ffde
[conda] blas                      1.0                         mkl  
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-include               2023.2.0            intel_49495    intel
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl-static                2023.2.0            intel_49495    intel
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.10.0                   pypi_0    pypi
[conda] pytorch-triton            3.0.0+a9bc1a3647          pypi_0    pypi
[conda] torch                     2.4.0a0+gite95ffde           dev_0    <develop>
[conda] torchfix                  0.4.0                    pypi_0    pypi

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

**Comment by shunting314** [comment]
Do you have a minimal repro?

**Comment by d4l3k** [comment]
@shunting314 nope, switched to a different approach https://github.com/pytorch/pytorch/pull/123599

**Comment by IvanKobzarev** [comment]
Hi @d4l3k, doing issue scrapping,  do you know if this is still an issue or do you get a repro?

**Comment by d4l3k** [comment]
@IvanKobzarev not working on this piece anymore -- ended up working around the issue via a different approach so not sure if the underlying issue ever got fixed.

**Comment by IvanKobzarev** [comment]
Repro 
```
python test/distributed/test_functional_api.py -k test_all_to_all_single
```
with "inductor" backend passes now. Closing.
