### ISSUE TITLE
[inductor][cpu]PT2E and QAT quantization regression in 2024-03-31 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#123448]
### 🐛 Describe the bug

PT2E and QAT quantization regression in 2024-03-31 nightly release
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/zengxian/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/zengxian/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link=blue vlink=purple>

model_name | PT2E_new | PT2E_old
-- | -- | --
densenet121 | 534.6600164 | 1217.14198
mobilenet_v2 | 4760.843136 | 5860.936014
mobilenet_v3_large | 3652.993057 | 5596.587481
squeezenet1_1 | 7583.483788 | 9030.394544

</body>

</html>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/zengxian/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/zengxian/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link=blue vlink=purple>

model_name | QAT_new | QAT_old
-- | -- | --
densenet121 | 535.9700177 | 1234.085813
mobilenet_v2 | 5058.754669 | 6045.72933
squeezenet1_1 | 7979.238023 | 9213.892967
mobilenet_v3_large-eval_throughput | 4231.302988 | 6811.576935
shufflenet_v2_x1_0-eval_throughput | 5354.989357 | 6619.653679

</body>

</html>

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>4af23dd</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ee35d764</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>ea437b3</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>2c4665f</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0790338</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>ee35d764</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.4.0a0+git384cbf2</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.19.0a0+a0c79b3</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+17a7081</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

Repro:
```
git clone -b chuanqiw/inductor_quant https://github.com/pytorch/benchmark.git
cd benchmark
pip install --no-deps -r requirements.txt
pip install --no-cache Jinja2==3.1.2 markupsafe==2.0.1 beartype==0.15.0 && pip install mpmath==1.3.0
python install.py --continue_on_fail
export LD_PRELOAD=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib/libiomp5.so:${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib/libjemalloc.so
export MALLOC_CONF="oversize_threshold:1,background_thread:true,metadata_thp:auto,dirty_decay_ms:-1,muzzy_decay_ms:-1"
#PT2E
TORCHINDUCTOR_FREEZING=1 python run_benchmark.py cpu -m ${models} --torchdynamo inductor --quantize --launcher --launcher-args="--throughput-mode" -b 128 --metrics throughputs
mv .userbenchmark/cpu ptq
cat ptq/metric* # to see the results
#QAT
TORCHINDUCTOR_FREEZING=1 python run_benchmark.py cpu -m ${models} --torchdynamo inductor --quantize --is_qat --launcher --launcher-args="--throughput-mode" -b 128 --metrics throughputs
mv .userbenchmark/cpu qat
cat qat/metric* # to see the results
```
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/6f4ed57b8aaa980169f8ed7f6219afd808487bc5
[torchbench-densenet121-inference-ptq-performance-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/14887092/torchbench-densenet121-inference-ptq-performance-drop_guilty_commit.log)
cc @WeizhuoZhang-intel @chuanqi129

**Comment by leslie-fang-intel** [comment]
I will take a look of this issue, cc @jgong5

**Comment by jgong5** [comment]
> I will take a look of this issue, cc @jgong5

Maybe missing some intrinsics specialization.

**Comment by leslie-fang-intel** [comment]
Hi @zxd1997066, the fix for this issue has been landed. Please help to verify,

**Comment by zxd1997066** [comment]
the issue is fixed.
