### ISSUE TITLE
[bug] Tensor.numpy() should return np.ndarray not Any

### ISSUE THREAD

**Issue by haarisr** [pytorch/pytorch#123494]
https://github.com/pytorch/pytorch/blob/3e8c64a637254b56dfcd8f5ddb3ffd201eed54d5/tools/pyi/gen_pyi.py#L1121

cc @ezyang @malfet @xuzhao9 @gramster

**Comment by malfet** [comment]
@FFFrog sounds like you want to propose a patch?

**Comment by FFFrog** [comment]
> pytorch#123494

Thank you for your advices, i have submitted a commit to fix it, please take a look at it, thank you.
