### ISSUE TITLE
Perf regress across all benchmark suits when cudagraphs is disabled due to triton pin bump

### ISSUE THREAD

**Issue by shunting314** [pytorch/pytorch#123597]
### 🐛 Describe the bug

When bumping triton from old pin (989adb9a29496c22a36ef82ca69cad5dad536b9c), to new pin (45fff310c891f5a92d55445adf8cc9d29df5841e) here https://github.com/pytorch/pytorch/pull/123077 . We found there are perf regression cross all benchmarks suites when cudagraphs is diabled.
- TB -6%
- HF -3%
- TIMM -3%

Dashboard [link](https://hud.pytorch.org/benchmark/compilers?startTime=Mon%2C%2001%20Apr%202024%2022%3A17%3A11%20GMT&stopTime=Mon%2C%2008%20Apr%202024%2022%3A17%3A11%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/shunting314/126/head&lCommit=749bd493418f1acc6c966b908576b09c41aa12ca&rBranch=main&rCommit=6f7dd2f84a4237b31eac29054b86a5284ef6cb6b)

### Versions

.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by shunting314** [comment]
Here the 146 triton commits between the bin bump in case it's helpful: https://gist.github.com/shunting314/3a623915f34cfe6080ff4405d42bbf80

**Comment by bertmaher** [comment]
#123806 (which also includes a Triton change, https://github.com/bertmaher/triton/tree/8831cd88203067ebe070ede75f88897571811d09)  is a hack that shows the root cause of this regression.  I'm working on making this a proper fix.

**Comment by bertmaher** [comment]
For reference, https://github.com/pytorch/pytorch/pull/123694 is the test diff that confirms https://github.com/openai/triton/pull/3492 as the cause of the regression.  It is kind of frightening how sensitive to launch latency torchbench is.
