### ISSUE TITLE
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'quantized::batch_norm2d' to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues

### ISSUE THREAD

**Issue by Manningchan** [pytorch/pytorch#123546]
### 🐛 Describe the bug

i used qat training and translate pth to onnx,but exist this error

### Versions

[pip3] numpy==1.22.0
[pip3] onnx==1.15.0
[pip3] onnxruntime==1.16.3
[pip3] onnxsim==0.4.35
[pip3] torch==1.13.1+cu117
[pip3] torch-multi-head-attention==0.15.1
[pip3] torchaudio==0.13.1+cu117
[pip3] torchvision==0.14.1+cu117
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46343  
[conda] mkl-service               2.4.0            py38h5eee18b_1  
[conda] mkl_fft                   1.3.8            py38h5eee18b_0  
[conda] mkl_random                1.2.4            py38hdb19cb5_0  
[conda] numpy                     1.22.0                   pypi_0    pypi
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torch                     1.13.1+cu117             pypi_0    pypi
[conda] torch-multi-head-attention 0.15.1                   pypi_0    pypi
[conda] torchaudio                0.13.1+cu117             pypi_0    pypi
[conda] torchvision               0.14.1+cu117             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by Manningchan** [comment]
i test opset version 11-16, still wrong

**Comment by thiagocrepaldi** [comment]
please reopen this issue when a full repro script is available

**Comment by Tianyun-Xuan** [comment]
I have alos met with this error
I used torch.quantization to quantify my model and then i wish to export pytorch model to onnx

Traceback (most recent call last):
  File "/home/workspace/point-cloud-de-noising/src/orin/train.py", line 60, in <module>
    quantized_test()
  File "/home/workspace/point-cloud-de-noising/src/orin/train.py", line 23, in quantized_test
    torch.onnx.export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1612, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1138, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 677, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1966, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'quantized::batch_norm2d' to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

**Comment by DaveAlsina** [comment]
Same issue here "Exporting the operator 'quantized::batch_norm2d' to ONNX opset **version 17** is not supported."

**Comment by vishalkumardas** [comment]
Same issue 
`UnsupportedOperatorError: Exporting the operator 'quantized::batch_norm2d' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
`

**Comment by AnnaTrainingG** [comment]
@vishalkumardas hi， did you solved this issue ?

**Comment by vishalkumardas** [comment]
> @vishalkumardas hi， did you solved this issue ?

Not yet, I had to go with different quantization approach
