### ISSUE TITLE
RuntimeError: "erfinv_cuda" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by PommesPeter** [pytorch/pytorch#123553]
### 🐛 Describe the bug

I am using the open_clip library `create_model_and_transforms` functionality, which called from `timm` library.

When enabling BFloat16, I get the following error:
```
  File "<...>/anaconda3/envs/<...>/lib/python3.10/site-packages/timm/models/convnext.py", line 427, in _init_weights
    named_apply(fn=fn, module=child_module, name=child_name, depth_first=depth_first, include_root=True)
  File "<...>/anaconda3/envs/<...>/lib/python3.10/site-packages/timm/models/_manipulate.py", line 36, in named_apply
    trunc_normal_(module.weight, std=.02)
  File "<...>/anaconda3/envs/<...>/lib/python3.10/site-packages/timm/layers/weight_init.py", line 67, in trunc_normal_
    fn(module=module, name=name)
  File "<...>/anaconda3/envs/<...>/lib/python3.10/site-packages/timm/models/convnext.py", line 427, in _init_weights
    trunc_normal_(module.weight, std=.02)
  File "<...>/anaconda3/envs/<...>/lib/python3.10/site-packages/timm/layers/weight_init.py", line 67, in trunc_normal_
    return _trunc_normal_(tensor, mean, std, a, b)
  File "<...>/anaconda3/envs/<...>/lib/python3.10/site-packages/timm/layers/weight_init.py", line 32, in _trunc_normal_
    return _trunc_normal_(tensor, mean, std, a, b)
  File "<...>/anaconda3/envs/<...>/lib/python3.10/site-packages/timm/layers/weight_init.py", line 32, in _trunc_normal_
    tensor.erfinv_()
RuntimeError: "erfinv_cuda" not implemented for 'BFloat16
```

### Versions

CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.8.89

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] open-clip-torch==2.24.0
[pip3] torch==2.1.1
[pip3] torchaudio==2.1.1
[pip3] torchvision==0.16.1
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.26.4          py310h5f9d8c6_0  
[conda] numpy-base                1.26.4          py310hb5e798b_0  
[conda] open-clip-torch           2.24.0                   pypi_0    pypi
[conda] pytorch                   2.1.1           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.1.1               py310_cu118    pytorch
[conda] torchtriton               2.1.0                     py310    pytorch
[conda] torchvision               0.16.1              py310_cu118    pytorch
```[tasklist]
### Tasks
```

cc @ptrblck

**Comment by malfet** [comment]
FYI this function is implemented on CPU for both half and bfloat16

**Comment by albanD** [comment]
Hey!

I think the general idea from the older issue is that this is not precise enough to be able to do this computation. In your model, you most likely want to upcast to float32 to be safe before doing this.
More generally, you can also use amp to get these up/down cast done automatically based on existing rules.

That being said, if you know that bf16 precision is enough for your use case and you need this implementation, feel free to send a PR for it!

**Comment by PommesPeter** [comment]
> Hey!
> 
> I think the general idea from the older issue is that this is not precise enough to be able to do this computation. In your model, you most likely want to upcast to float32 to be safe before doing this. More generally, you can also use amp to get these up/down cast done automatically based on existing rules.
> 
> That being said, if you know that bf16 precision is enough for your use case and you need this implementation, feel free to send a PR for it!

okay, thanks for your advice. I will do it in my model for training.
