### ISSUE TITLE
torch._fused_adamw_( RuntimeError: params, grads, exp_avgs, and exp_avg_sqs must have same dtype, device, and layout

### ISSUE THREAD

**Issue by npuichigo** [pytorch/pytorch#123557]
### 🐛 Describe the bug

```
torch._fused_adamw_(
RuntimeError: params, grads, exp_avgs, and exp_avg_sqs must have same dtype, device, and layout
```

### Versions

2.2.1

**Comment by awgu** [comment]
Could you provide a repro?

**Comment by drisspg** [comment]
I am going to close this for lack of detail, please feel free to re-open with the requested info. We have templates for opening bug reports, if in the future you can follow that template that will help us to help you
