### ISSUE TITLE
`load_state_dict()` fails to handle unexpected keys whose prefix matches a valid key

### ISSUE THREAD

**Issue by RyanJDick** [pytorch/pytorch#123510]
### 🐛 Describe the bug

If a state dict contains a valid key (e.g. `"fc1.weight"`) and an unexpected key that starts with the valid key (e.g. `"fc1.weight.bad_key"`), then `load_state_dict()` does not handle this in the way that I'd expect.

Code to reproduce:
```python
import torch

class SimpleModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = torch.nn.Linear(5, 10)

    def forward(self, x):
        return self.fc1(x)


def try_load_state_dict(model: SimpleModel, state_dict: dict[str, torch.Tensor], strict: bool):
    print(f"state_dict.keys(): {state_dict.keys()}")
    print(f"strict={strict}")

    print(f"Calling load_state_dict()...")
    try:
        load_result = model.load_state_dict(state_dict, strict=strict)
        print(f"load_result.missing_keys: {load_result.missing_keys}")
        print(f"load_result.unexpected_keys: {load_result.unexpected_keys}")
    except Exception as e:
        print(f"Raised exception: {e}")

def main():
    simple_model = SimpleModel()

    print("Initialized SimpleModel.")
    print(f"simple_model.state_dict().keys(): {simple_model.state_dict().keys()}")
    
    print("\nCase 1: Correct state_dict, strict=True")
    print("-----")
    state_dict = simple_model.state_dict()
    try_load_state_dict(simple_model, state_dict, strict=True)

    print("\nCase 2: state_dict with 'fc1.bad_key', strict=False")
    print("-----")
    state_dict = simple_model.state_dict()
    state_dict["fc1.bad_key"] = torch.randn(5, 10)
    try_load_state_dict(simple_model, state_dict, strict=False)

    print("\nCase 3: state_dict with 'fc1.bad_key', strict=True")
    print("-----")
    state_dict = simple_model.state_dict()
    state_dict["fc1.bad_key"] = torch.randn(5, 10)
    try_load_state_dict(simple_model, state_dict, strict=True)

    print("\nCase 4: state_dict with 'fc1.weight.bad_suffix', strict=False")
    print("-----")
    state_dict = simple_model.state_dict()
    state_dict["fc1.weight.bad_suffix"] = torch.randn(5, 10)
    try_load_state_dict(simple_model, state_dict, strict=False)

    print("\nCase 5: state_dict with 'fc1.weight.bad_suffix', strict=True")
    print("-----")
    state_dict = simple_model.state_dict()
    state_dict["fc1.weight.bad_suffix"] = torch.randn(5, 10)
    try_load_state_dict(simple_model, state_dict, strict=True)


if __name__ == "__main__":
    main()
```

This code produces the following output:
```bash
Initialized SimpleModel.
simple_model.state_dict().keys(): odict_keys(['fc1.weight', 'fc1.bias'])

Case 1: Correct state_dict, strict=True
-----
state_dict.keys(): odict_keys(['fc1.weight', 'fc1.bias'])
strict=True
Calling load_state_dict()...
load_result.missing_keys: []
load_result.unexpected_keys: []

Case 2: state_dict with 'fc1.bad_key', strict=False
-----
state_dict.keys(): odict_keys(['fc1.weight', 'fc1.bias', 'fc1.bad_key'])
strict=False
Calling load_state_dict()...
load_result.missing_keys: []
load_result.unexpected_keys: ['fc1.bad_key']

Case 3: state_dict with 'fc1.bad_key', strict=True
-----
state_dict.keys(): odict_keys(['fc1.weight', 'fc1.bias', 'fc1.bad_key'])
strict=True
Calling load_state_dict()...
Raised exception: Error(s) in loading state_dict for SimpleModel:
        Unexpected key(s) in state_dict: "fc1.bad_key". 

Case 4: state_dict with 'fc1.weight.bad_suffix', strict=False
-----
state_dict.keys(): odict_keys(['fc1.weight', 'fc1.bias', 'fc1.weight.bad_suffix'])
strict=False
Calling load_state_dict()...
load_result.missing_keys: []
load_result.unexpected_keys: []

Case 5: state_dict with 'fc1.weight.bad_suffix', strict=True
-----
state_dict.keys(): odict_keys(['fc1.weight', 'fc1.bias', 'fc1.weight.bad_suffix'])
strict=True
Calling load_state_dict()...
load_result.missing_keys: []
load_result.unexpected_keys: []
```

Results:
- Case 1: Correct
- Case 2: Correct
- Case 3: Correct
- Case 4: I'd expect this to return `unexpected_keys = ['fc1.weight.bad_suffix']`.
- Case 5: I'd expect this to raise an exception.

### Versions

Collecting environment information...
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.5
Libc version: glibc-2.35

Python version: 3.10.12 (main, Aug 30 2023, 09:22:39) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-82-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.128
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 535.86.10
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      43 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             12
On-line CPU(s) list:                0-11
Vendor ID:                          AuthenticAMD
Model name:                         AMD Ryzen 5 3600 6-Core Processor
CPU family:                         23
Model:                              113
Thread(s) per core:                 2
Core(s) per socket:                 6
Socket(s):                          1
Stepping:                           0
Frequency boost:                    enabled
CPU max MHz:                        3600.0000
CPU min MHz:                        2200.0000
BogoMIPS:                           7186.84
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es
Virtualization:                     AMD-V
L1d cache:                          192 KiB (6 instances)
L1i cache:                          192 KiB (6 instances)
L2 cache:                           3 MiB (6 instances)
L3 cache:                           32 MiB (2 instances)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-11
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] clip-anytorch==2.5.2
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] torch==2.1.2
[pip3] torchdiffeq==0.2.3
[pip3] torchsde==0.2.5
[pip3] torchvision==0.15.2
[pip3] triton==2.1.0
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
I was able to reproduce this,

The issue seems to be that the mechanism for `strict=True` is as such:


https://github.com/pytorch/pytorch/blob/9a661636e347da47c293972b73f357025abdb0e4/torch/nn/modules/module.py#L2095-L2101

So, for example, for `fc1.weight.bad_suffix`, after the split, `input_name` that is checked for `if input_name not in self._modules and input_name not in local_state: ` becomes `weight`

This differs from the [behavior promised in the documentation](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.load_state_dict) indeed

> If strict is True, then the keys of [state_dict](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.state_dict) must exactly match the keys returned by this module’s [state_dict()](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.state_dict) function.

Marking needs research to understand the historical context for `input_name = input_name.split('.', 1)[0]`, but otherwise this seems like a bug that is actionable to fix indeed

**Comment by mikaylagawarecki** [comment]
Marking as `actionable` to send a fix for this
