### ISSUE TITLE
Quantization Aware Training with 4-bit quantization

### ISSUE THREAD

**Issue by mxjyst** [pytorch/pytorch#123524]
### 🚀 The feature, motivation and pitch

I use the following code to create qat model. I didn't find a way to set the fake quantized op to 4-bit dtype.
```
model=create_model(args)
model.qconfig = torch.ao.quantization.get_default_qat_qconfig('fbgemm')
model = torch.ao.quantization.prepare_qat(model.train())
```
I want to know is there any way to conduct 4-bit qat?

**Comment by drisspg** [comment]
I am going to close this issue, this would be a better issue for: https://github.com/pytorch-labs/ao
And for some reason I cant directly transfer
