### ISSUE TITLE
[inductor][cpu]basic_gnn_gcn AMP static/dynamic shape default/cpp wrapper single thread performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#123502]
### 🐛 Describe the bug

<p>AMP static shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_gcn</td>
      <td>single</td>
      <td>1</td>
      <td>2.840742</td>
      <td>0.02862003</td>
      <td>0.08130212126226001</td>
      <td>8.595758</td>
      <td>1</td>
      <td>3.233373</td>
      <td>0.025129724</td>
      <td>0.08125377107905199</td>
      <td>8.340146</td>
      <td>0.88</td>
      <td>1.0</td>
      <td>0.88</td>
      <td>0.97</td>
    </tr>
  </tbody>

</table>

<p>AMP dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_gcn</td>
      <td>single</td>
      <td>1</td>
      <td>2.856395</td>
      <td>0.028604007</td>
      <td>0.081704342574765</td>
      <td>8.626275</td>
      <td>1</td>
      <td>3.252178</td>
      <td>0.025021263999999998</td>
      <td>0.08137360431299198</td>
      <td>8.333838</td>
      <td>0.88</td>
      <td>1.0</td>
      <td>0.87</td>
      <td>0.97</td>
    </tr>
  </tbody>

</table>

<p>AMP dynamic shape CPP wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_gcn</td>
      <td>single</td>
      <td>1</td>
      <td>2.854889</td>
      <td>0.028386648</td>
      <td>0.081040729122072</td>
      <td>50.862871</td>
      <td>1</td>
      <td>3.263137</td>
      <td>0.024769257</td>
      <td>0.080825478979209</td>
      <td>50.52748</td>
      <td>0.87</td>
      <td>1.0</td>
      <td>0.87</td>
      <td>0.99</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>d6015d42</td>
      <td>main</td>
      <td>d6015d42</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>35c493f2cf9b623bfdc7e6b34dc1cb39690a7919</td>
      <td>main</td>
      <td>f0d461beacded34abe196c72ec4bcdb55bf01793</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+2c4665f</td>
      <td>main</td>
      <td>0.19.0a0+a0c79b3</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.2.0a0+ea437b3</td>
      <td>main</td>
      <td>2.2.0a0+17a7081</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single inference performance torchbench basic_gnn_gcn amp first static/dynamic default/cpp
[torchbench-basic_gnn_gcn-inference-amp-static-cpp-single-performance-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/14893819/torchbench-basic_gnn_gcn-inference-amp-static-cpp-single-performance-drop_guilty_commit.log)
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/49121603ab2d9070b1b6182a90f01a15afe5b6fe
cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @WeizhuoZhang-intel @chuanqi129

**Comment by zhuhaozhe** [comment]
The only difference brought by https://github.com/pytorch/pytorch/commit/49121603ab2d9070b1b6182a90f01a15afe5b6fe is more kernel are vectorized.
Vec kernel: https://gist.github.com/zhuhaozhe/d99974f84d78f76f393fbeec7ee3b03e
Scalar kernel: https://gist.github.com/zhuhaozhe/408469f904e644fa2ea6c3c5ac013453.
Performance analyze WIP

**Comment by zhuhaozhe** [comment]
Looks there is additional load/store in vec kernel
```
# scaler kernel
auto tmp3 = tmp2 ? tmp1 : tmp0;
TORCH_CHECK((0 <= tmp3) & (tmp3 < 10000L), "index out of bounds: 0 <= tmp3 < 10000L")
auto tmp4 = out_ptr0[static_cast<long>(tmp3)];  
```
-> becomes to 
```
# vec kernel
auto tmp7 = decltype(tmp3)::blendv(tmp0, tmp3, tmp6.template cast<int64_t,2>());
TORCH_CHECK((at::vec::VecMask<int64_t,2>((at::vec::VectorizedN<int64_t,2>(0) <= tmp7) & (tmp7 < at::vec::VectorizedN<int64_t,2>(10000L)))).all_masked(), "index out of bounds: 0 <= tmp7 < 10000L")
auto tmp8 =
[&]
{
    __at_align__ std::array<int64_t, 16> tmpbuf;
    tmp7.store(tmpbuf.data());
    return tmpbuf;
}
()
;
auto tmp9 =
[&]
{
    __at_align__ std::array<float, 16> tmpbuf;
    #pragma GCC unroll 16
    for (long x0_inner = 0; x0_inner < 16; x0_inner++)
    {
        tmpbuf[x0_inner] = out_ptr0[static_cast<long>(tmp8[x0_inner])];
    }
    return at::vec::Vectorized<float>::loadu(tmpbuf.data());
}
()
;
```

**Comment by zhuhaozhe** [comment]
> There is additional **load/store** in vec kernel
> 
> ```
> # scaler kernel
> auto tmp3 = tmp2 ? tmp1 : tmp0;
> TORCH_CHECK((0 <= tmp3) & (tmp3 < 10000L), "index out of bounds: 0 <= tmp3 < 10000L")
> auto tmp4 = out_ptr0[static_cast<long>(tmp3)];  
> ```
> 
> -> becomes to
> 
> ```
> # vec kernel, store tmp7 to tmp8 and load tmp8 as tmp9
> auto tmp7 = decltype(tmp3)::blendv(tmp0, tmp3, tmp6.template cast<int64_t,2>());
> TORCH_CHECK((at::vec::VecMask<int64_t,2>((at::vec::VectorizedN<int64_t,2>(0) <= tmp7) & (tmp7 < at::vec::VectorizedN<int64_t,2>(10000L)))).all_masked(), "index out of bounds: 0 <= tmp7 < 10000L")
> auto tmp8 =
> [&]
> {
>     __at_align__ std::array<int64_t, 16> tmpbuf;
>     tmp7.store(tmpbuf.data());
>     return tmpbuf;
> }
> ()
> ;
> auto tmp9 =
> [&]
> {
>     __at_align__ std::array<float, 16> tmpbuf;
>     #pragma GCC unroll 16
>     for (long x0_inner = 0; x0_inner < 16; x0_inner++)
>     {
>         tmpbuf[x0_inner] = out_ptr0[static_cast<long>(tmp8[x0_inner])];
>     }
>     return at::vec::Vectorized<float>::loadu(tmpbuf.data());
> }
> ()
> ;
> ```

I tried to avoid generate `tmp8` but the performance is still not recovered. So it is not the correct root cause.

Latest finding is the vec kernel generated redundant code
https://gist.github.com/zhuhaozhe/d99974f84d78f76f393fbeec7ee3b03e#file-vec-py-L68-L76
https://gist.github.com/zhuhaozhe/d99974f84d78f76f393fbeec7ee3b03e#file-vec-py-L96-L104
```
            auto tmp8 =
            [&]
            {
                __at_align__ std::array<int64_t, 16> tmpbuf;
                tmp7.store(tmpbuf.data());
                return tmpbuf;
            }
            ()
            ;
// also store tmp7 here
            auto tmp16 =
            [&]
            {
                __at_align__ std::array<int64_t, 16> tmpbuf;
                tmp7.store(tmpbuf.data());
                return tmpbuf;
            }
            ()
            ;
```

This is due to the `cse.cache` are not cloned during `swap buffer`.
https://github.com/pytorch/pytorch/pull/124597/files.

I am not sure whether we should or should not clone the cse.cache so I create this [PR](https://github.com/pytorch/pytorch/pull/124597) to see the CI status.
