### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#123560]
### 🐛 Describe the bug

Wrapping this with `@torch_compile` this function it is going to fail.
https://github.com/hkchengrex/Cutie/blob/main/cutie/model/cutie.py#L96

Without the wrapper it is working correctly.

The problem is the compile evaluation of amp disabled section that is going to mix float and half.

If I change all `with torch.cuda.amp.autocast(enabled=False):` subsections to `True` it is going to compile:
https://github.com/search?q=repo%3Ahkchengrex%2FCutie+amp.autocast&type=code

Just a perf warning:
```python
UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 256, 1, 1], strides() = [256, 1, 256, 256]
bucket_view.sizes() = [1, 256, 1, 1], strides() = [256, 1, 1, 1] 
```

### Error logs

```python
  File "/short-term/tmp/torchinductor_root/ju/cjuclawq3bek6xwgqfbifplqqh66q7f65dl5xiuhx4qlipoedine.py", line 1493, in call
    buf3 = aten.convolution_backward.default(buf0, relu_2, convert_element_type_15, [256], [1, 1], [1, 1], [1, 1], False, [0, 0], 1, [True, True, False])
  File "/opt/conda/lib/python3.10/site-packages/torch/_ops.py", line 610, in __call__
    return self_._op(*args, **kwargs)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same
```

### Versions

pytorch nightly

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by shunting314** [comment]
Can you create a standalone minimal repro?

**Comment by bhack** [comment]
Minimize a model it is a lot of work every time on every compiler error. Is there any quick alternative to support bug reporting?

**Comment by bhack** [comment]
Without the minimization it is reproducible with the mentioned compile decorator  and https://github.com/hkchengrex/Cutie/blob/main/docs%2FTRAINING.md

**Comment by shunting314** [comment]
From triage review: we should improve logging so the issue creator don't need to always provide a minimal repro

**Comment by bhack** [comment]
> From triage review: we should improve logging so the issue creator don't need to always provide a minimal repro

It would be very useful as I am often exploring compiler failures with nightly  on well known third party networks and so it is too much work scaling on compile reports if it always requires  full code isolation/minimization.

**Comment by IvanKobzarev** [comment]
Hi @bhack , doing issue scrapping, is this issue is still relevant or we can close it?

**Comment by bhack** [comment]
We could close in the meantime as I am not strictly on the project with nightlies to confirm it or not again.
