### ISSUE TITLE
The PRELU formula issue

### ISSUE THREAD

**Issue by ArtIntAI** [pytorch/pytorch#123554]
### 📚 The doc issue

https://pytorch.org/docs/stable/generated/torch.nn.PReLU.html#prelu
The doc shows that the prelu formula is: y = x >=0 ? x : a*x  (1)
but according to the paper "Delving Deep into Rectifiers:Surpassing Human-Level Performance on ImageNet Classification",
the formula is: y = x >0 ? x : a*x (2)
There are big difference when a is special number such as NaN or INF and x is 0, according to the formula (1), y = 0,
but according to the formula (2), y = NaN

### Suggest a potential alternative/fix

Change the doc's formula to "y = x >0 ? x : a*x"

**Comment by ezyang** [comment]
Can you send us a patch for it?
