### ISSUE TITLE
affine_grid function doesn't check the data type of theta

### ISSUE THREAD

**Issue by Steve-Tod** [pytorch/pytorch#12362]
## 🐛 Bug

I was trying to use torch.nn.functional.affine_grid() to generate grid and grid_sample() to warp a image. However, if I use the identical affine matrix, I can't get the right output, which should be the same as the input.

## To Reproduce

1. let theta be the identical affine matrix
2. warp affine with affine_grid and grid_sample
3. display the image

```python
import torch
import matplotlib.pyplot as plt

img = plt.imread("lena.jpeg")
img = img[110:120, 110:120]
img = img.reshape(1,10,10,3)
img_tensor = torch.from_numpy(img)
img_tensor = img_tensor.permute(0, 3, 1, 2)

theta = torch.tensor([[1, 0, 0], [0, 1, 0]])
theta = theta.view(1, 2, 3)

grid = torch.nn.functional.affine_grid(theta, img_tensor.size())
out = torch.nn.functional.grid_sample(img_tensor.float(), grid.float())

out_img = out.permute(0, 2, 3, 1).data.numpy()
out_img = out_img.reshape(10, 10, 3)
plt.imshow(out_img.astype(int))
plt.show()
```

## Expected behavior

The output should be the same as the input.

## Environment

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] pytorch                   0.4.1           py36_cuda0.0_cudnn0.0_1    pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

## Additional context

After I debug step by step, I found these codes in vision.py, form line 43 to 52:

```python
base_grid = theta.new(N, H, W, 3) # base_grid has the same data type as theta
linear_points = torch.linspace(-1, 1, W) if W > 1 else torch.Tensor([-1])
base_grid[:, :, :, 0] = torch.ger(torch.ones(H), linear_points).expand_as(base_grid[:, :, :, 0])
linear_points = torch.linspace(-1, 1, H) if H > 1 else torch.Tensor([-1])
base_grid[:, :, :, 1] = torch.ger(linear_points, torch.ones(W)).expand_as(base_grid[:, :, :, 1])
base_grid[:, :, :, 2] = 1
ctx.base_grid = base_grid
grid = torch.bmm(base_grid.view(N, H * W, 3), theta.transpose(1, 2))
grid = grid.view(N, H, W, 2)
return grid
```

Since affine_grid doesn't check the data type of theta, when I use identical affine matrix, the data type of theta is int, so is the base_grid. Finally, there are only 1, -1 and 0 in base_grid and grid. That's why the problem happens. After I use theta.float() rather than theta, everything works well.

**Comment by ezyang** [comment]
Thanks. CC @SsnL

**Comment by jbschlosser** [comment]
This was fixed in https://github.com/pytorch/pytorch/pull/24929.
