### ISSUE TITLE
OptimizedModule should call _orig_mod's load_state_dict()/state_dict() methods.

### ISSUE THREAD

**Issue by torshie** [pytorch/pytorch#123625]
### 🐛 Describe the bug

If a module has overridden load_state_dict()/state_dict(), the corresponding compiled module may not work. I'm currently use a workaround like the following:

```python
def my_load(self, state_dict, strict=True):
    self._orig_mod.load_state_dict(state_dict, strict)

model = torch.compile(model)
model.__class__.load_state_dict = my_load
```

### Error logs

```text
Traceback (most recent call last):
  File "mod.py", line 20, in <module>
    compiled.load_state_dict(sd)
  File "/Users/dengyao/miniconda3/envs/torch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for OptimizedModule:
	Missing key(s) in state_dict: "_orig_mod.linear.weight", "_orig_mod.linear.bias".
```

### Minified repro

```python
import torch


class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(3, 5)

    def state_dict(self):
        return {}

    def load_state_dict(self, state_dict):
        pass


module = M()
sd = module.state_dict()

compiled = torch.compile(module)
compiled.load_state_dict(sd)
```

### Versions

torch 2.2.1

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by albanD** [comment]
Hey!
Have you tried using the load_state_dict hooks (https://pytorch.org/docs/main/generated/torch.nn.Module.html#torch.nn.Module.register_load_state_dict_post_hook) to change the behavior there without having to override the load_state_dict method?

**Comment by torshie** [comment]
It probably could be done with those hooks, just not trivial though.

The module is from a third-party, so I just injected a method instead of analyzing their source code ;)

**Comment by albanD** [comment]
That's exactly what the hooks allow you to do: inject code just before or just after without touching their code!

**Comment by anijain2305** [comment]
@torshie Closing this bug as Alban suggestion should work. But please feel free to reopen.

**Comment by StrongerXi** [comment]
@torshie you can also use `module.compile()`
```python
module = M()
sd = module.state_dict()

module.compile()
module.load_state_dict(sd)
```


Or load the state dict first, then compile the module.
```python
module = M()
sd = module.state_dict()

module.load_state_dict(sd)
compiled = torch.compile(module)
```
