### ISSUE TITLE
DISABLED test_logaddexp_cpu_complex128 (__main__.TestBinaryUfuncsCPU)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#123655]
Platforms: linux

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22test_binary_ufuncs.py%3A%3ATestBinaryUfuncsCPU%3A%3Atest_logaddexp_cpu_complex128%22%5D)).

This starts failing after https://github.com/pytorch/pytorch/pull/123595, but it's not clear if they are related.

**Comment by malfet** [comment]
Thank you for revert, though I'm not entirely sure how/why those two can be related..

**Comment by malfet** [comment]
Ok, actual cause for the failure was unpinned scipy and not sure if 1.13 is broken or just something is wrong with it
