### ISSUE TITLE
Warning can not be disabled ? 

### ISSUE THREAD

**Issue by lucasjinreal** [pytorch/pytorch#123626]
/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(

This warning logs every single step.

I have set use_reeentrant not work. 

And I set disable this warning still not work.

torch.set_warn_always(False)

How hard it is?

cc @soulitzer

**Comment by maldevide** [comment]
agree, this is awful

**Comment by ezyang** [comment]
Can you follow the instructions at https://stackoverflow.com/a/22376126/23845 to get a full stack trace for the warning and put it here?

**Comment by lucasjinreal** [comment]
Is's just the checkpoint warning, the line I posted there.

Any further information should provided?

**Comment by soulitzer** [comment]
Do you have a self-contained snippet that can be used to reproduce this issue?

The warning is raised as follows:
```
    if use_reentrant is None:
        warnings.warn(
          ...
        )
        use_reentrant = True
  ```
so it is not clear to me why passing use_reentrant would not solve the issue. 

Are you calling checkpoint directly with `torch.utils.checkpoint.checkpoint` or through another API?
