### ISSUE TITLE
Segmentation fault on running tutorial

### ISSUE THREAD

**Issue by FatEvilCat** [pytorch/pytorch#12376]
Sorry,I am the beginner of the pytorch and python.
So, when I downloaded the code of "Tutorials > Deep Learning with PyTorch: A 60 Minute Blitz > Training a Classifier ".

I use Ubuntu 1604 ,so I suppose to open the terminal then type

$ python ./cifar10_tutorial.py
Files already downloaded and verified
Files already downloaded and verified
segmentation fault (core dumped)

Did I do something wrong? And how to run this code successfully.

THANKS!

**Comment by soumith** [comment]
Hi there, please use our issue template. We need to know a lot of details, such as: "how did you install PyTorch, what are the system details, etc."
Please open a new issue with the issue template and we will get you the help you need.
