### ISSUE TITLE
Cannot process/load 2.3 produced aot-inductor shared library file with 2.4-dev

### ISSUE THREAD

**Issue by bsergean** [pytorch/pytorch#123745]
### 🐛 Describe the bug

We are compiling with the compatible option, in 2.3.

```
os.environ["TORCHINDUCTOR_ABI_COMPATIBLE"] = "1"
```

However when we load that with a dev snapshot of 2.4, we get this error. To me this is not expected, if I understand the design of aot inductor (compile once, and rely on the ABI compatibility in future versions of pytorch, to make sure they can load 'old' files. Or did something break/changed drastically in 2.4 ? 

```
Error in dlopen: foo.so: undefined symbol: _ZN5torch12aot_inductor31tensor_handle_to_tensor_pointerEP16AtenTensorOpaque
Exception raised from DynamicLibrary at ../aten/src/ATen/DynamicLibrary.cpp:36 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x72924e086177 in /path/_deps/pytorch-src/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10d8324 (0x7292376d8324 in /path/_deps/pytorch-src/torch/lib/libtorch_cpu.so)
frame #2: torch::inductor::AOTIModelContainerRunner::AOTIModelContainerRunner(std::string const&, unsigned long, std::string const&, std::string const&) + 0xbd (0x72923b7d39cd in /path/build/_deps/pytorch-src/torch/lib/libtorch_cpu.so)
```

This is what this symbol is:
```
$ c++filt 
_ZN5torch12aot_inductor31tensor_handle_to_tensor_pointerEP16AtenTensorOpaque
torch::aot_inductor::tensor_handle_to_tensor_pointer(AtenTensorOpaque*)
```

### Versions

2.3 + 2.4 ... sorry a bit complicated but everything is in the title.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @desertfire @chenyang78

**Comment by bsergean** [comment]
cc @desertfire

**Comment by desertfire** [comment]
Yes, ABI-compatible is a feature we are working to offer, but it is still being actively developed. For your specific case, looks like the symbol should be there. Do you have an easy way to repro?

**Comment by bsergean** [comment]
We're gonna try to build a repro, we're putting this in production (works great with 2.2), and this error was with a real model (using the rc of pytorch-2.3), but will try to get back to you.
Maybe it was user error ... I hope we aren't wasting anyone's time.

**Comment by desertfire** [comment]
I think the breakage may be real, because I changed that function to be "inline" https://github.com/pytorch/pytorch/blob/016ca546aa833b2a337e556dfb0b759f2b759a25/torch/csrc/inductor/aoti_torch/utils.h#L27. If recompilation solves your problem, that's great. Again, we don't make a strict backward compatibility guarantee at this point.

**Comment by bsergean** [comment]
Yes this is what someone on our team said, that a function became inline.

And yes I was not expecting that strong guarantee yet, but at least we want this to go in the right direction.

What do you mean by recompilation ? Recompile libtorch (or the aot file) ? We are using pre-compiled binaries actually.

**Comment by ezyang** [comment]
I think we should be treating this as a bug, and figure out why this slipped past us. Bin expressed to me that it wasn't expected that these symbols should show up at all in the binaries at all.

**Comment by desertfire** [comment]
By recompilation, I meant recompiling the model using 2.4.

I downloaded 2.3 and tried it on a small example locally, if I compile with `TORCHINDUCTOR_ABI_COMPATIBLE=1`, the generated model.so does not have a reference to `torch::aot_inductor::tensor_handle_to_tensor_pointer`, while compiling with `TORCHINDUCTOR_ABI_COMPATIBLE=0` does contain a reference. Can you double check if you model was compiled with `TORCHINDUCTOR_ABI_COMPATIBLE=1`?

**Comment by desertfire** [comment]
@bsergean , any update?

**Comment by bsergean** [comment]
Sorry about that, not yet. We ran into another problem which is more annoying to us. For now we settled on 2.2 (non abi-compatible) for our first iteration.

**Comment by rapplovin** [comment]
Hi @desertfire ,  just did some tests again and found that it works for a simple model we have.  But I encountered some error when we set the flag and compile our big model.  I have put the error in this [gist](https://gist.github.com/rapplovin/cede6bd763826e9e4a9cdfe8d4576592) 
```
/tmp/aot/tvnq02dx-m20pzm29-2/c3fta47qkafzgcrpnj5aywsozgrxysvfdenahqutuq64f2iphrgn.cpp:8874:34: error: invalid user-defined conversion from ‘torch::aot_inductor::RAIIAtenTensorHandle’ to ‘int64_t’ {aka ‘long int’} [-fpermissive]
 8874 |     int64_t int_array_23[] = {0, buf896};
      |                                  ^~~~~~
In
```
BTW, we used to set the flag in code using os.environ["TORCHINDUCTOR_ABI_COMPATIBLE"] = "1" and it somehow did not have effect and that was the reason we had that ABI issue.

**Comment by desertfire** [comment]
> Hi @desertfire , just did some tests again and found that it works for a simple model we have. But I encountered some error when we set the flag and compile our big model. I have put the error in this [gist](https://gist.github.com/rapplovin/cede6bd763826e9e4a9cdfe8d4576592)
> 
> ```
> /tmp/aot/tvnq02dx-m20pzm29-2/c3fta47qkafzgcrpnj5aywsozgrxysvfdenahqutuq64f2iphrgn.cpp:8874:34: error: invalid user-defined conversion from ‘torch::aot_inductor::RAIIAtenTensorHandle’ to ‘int64_t’ {aka ‘long int’} [-fpermissive]
>  8874 |     int64_t int_array_23[] = {0, buf896};
>       |                                  ^~~~~~
> In
> ```
> 
> BTW, we used to set the flag in code using os.environ["TORCHINDUCTOR_ABI_COMPATIBLE"] = "1" and it somehow did not have effect and that was the reason we had that ABI issue.

The problem should have been resolved in the nightly, although I am hitting an export issue when using the default batch size 1, 
```
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (batch)! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of batch = L['x'].size()[0] in the specified range batch <= 1024 are valid because batch was inferred to be a constant (1).
  - Not all values of batch = L['y'].size()[0] in the specified range batch <= 1024 are valid because batch was inferred to be a constant (1).
  ```
Using a non-1 batch size would work, cc @angelayi , @zhxchen17

**Comment by rapplovin** [comment]
Hi @desertfire, want to ask a question about how to setup the dynamic dimension when compiling the model.  Our model is defined as 
```
def inference(self, batch: List[torch.Tensor]):
```
And some tensor may be shape of (batch_size, 0), I found that 
This will compile but will error out with different batch size during inference. 
```
dynamic_shapes={
                    "batch": [[batch_dim] for _ in example_inputs]
                },  
```
Also tried 
```
dynamic_shapes= {"batch": [{0:batch_dim} for _ in example_inputs]},
```

but it will give the following error 
```
File "/home/user/.pyenv/versions/3.11.6/envs/aot_pytorch_2.3_abi_compatible/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.6/envs/aot_pytorch_2.3_abi_compatible/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 634, in compile_inner
    check_fn = CheckFunctionManager(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.6/envs/aot_pytorch_2.3_abi_compatible/lib/python3.11/site-packages/torch/_dynamo/guards.py", line 1048, in __init__
    guard.create(builder)
  File "/home/user/.pyenv/versions/3.11.6/envs/aot_pytorch_2.3_abi_compatible/lib/python3.11/site-packages/torch/_guards.py", line 249, in create
    return self.create_fn(builder, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.6/envs/aot_pytorch_2.3_abi_compatible/lib/python3.11/site-packages/torch/_dynamo/guards.py", line 705, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.6/envs/aot_pytorch_2.3_abi_compatible/lib/python3.11/site-packages/torch/fx/experimental/symbolic_shapes.py", line 2949, in produce_guards
    f"{src2.name()} = {expr2.subs(self.var_to_val)}"
                       ^^^^^^^^^^
AttributeError: 'int' object has no attribute 'subs'
```

**Comment by ezyang** [comment]
Are you able to post TORCH_LOGS=dynamic logs from the exportin gprocess?

**Comment by rapplovin** [comment]
Thanks @ezyang for the tip, the log seems reasonable except that the min batch size is 2 instead 1 that was set
```
W0421 17:46:30.437000 127419376249920 torch/_logging/_internal.py:402] [0/0] Using TORCH_LOGS environment variable for log settings, ignoring call to set_logs
I0421 17:46:33.004000 127419376249920 torch/fx/experimental/symbolic_shapes.py:2724] [0/0] create_symbol s0 = 261 for L['batch'][0].size()[0] [2, 4096] (_dynamo/variables/builder.py:1881 in <lambda>)
I0421 17:46:33.054000 127419376249920 torch/fx/experimental/symbolic_shapes.py:2724] [0/0] create_symbol s1 = 261 for L['batch'][1].size()[0] [2, 4096] (_dynamo/variables/builder.py:1881 in <lambda>)
I0421 17:46:33.095000 127419376249920 torch/fx/experimental/symbolic_shapes.py:2724] [0/0] create_symbol s2 = 261 for L['batch'][2].size()[0] [2, 4096] (_dynamo/variables/builder.py:1881 in <lambda>)
I0421 17:46:50.472000 127419376249920 torch/fx/experimental/symbolic_shapes.py:3809] [0/0] set_replacement s1 = s0 (solve_backed) ValueRanges(lower=2, upper=4096, is_bool=False)
I0421 17:46:50.474000 127419376249920 torch/fx/experimental/symbolic_shapes.py:4035] [0/0] eval Eq(s1, s0) [guard added] at model.py:782 in batch_processing (_prims/__init__.py:1917 in _cat_meta)
I0421 17:46:50.482000 127419376249920 torch/fx/experimental/symbolic_shapes.py:3809] [0/0] set_replacement s1 = s0 (find) ValueRanges(lower=2, upper=4096, is_bool=False)
I0421 17:46:56.144000 127419376249920 torch/fx/experimental/symbolic_shapes.py:2806] [0/0] produce_guards
I0421 17:46:56.166000 127419376249920 torch/fx/experimental/symbolic_shapes.py:3809] [0/0] set_replacement s2 = s0 (solve_backed) ValueRanges(lower=2, upper=4096, is_bool=False)
I0421 17:46:56.167000 127419376249920 torch/fx/experimental/symbolic_shapes.py:4035] [0/0] eval Eq(s0, s2) [guard added] (_dynamo/guards.py:705 in SHAPE_ENV)
I0421 17:46:56.174000 127419376249920 torch/fx/experimental/symbolic_shapes.py:3809] [0/0] set_replacement s1 = s0 (find) ValueRanges(lower=2, upper=4096, is_bool=False)
I0421 17:46:56.181000 127419376249920 torch/fx/experimental/symbolic_shapes.py:3809] [0/0] set_replacement s2 = s0 (find) ValueRanges(lower=2, upper=4096, is_bool=False)
```

Now I feel that the batch size actually is not the issue.  I have found one particular list of test tensors that will fail the validation ( compare with JIT model),  how ever,  if i create a random list of tensors with the same shapes or with different batch sizes (which is used in the AOT compile), it will pass the  verification. Does the value of the tensors make a difference?

**Comment by ezyang** [comment]
It seems more likely that slight numeric changes from the compilation process are causing you to fail the accuracy test. One way to see if this is the case is to do some testing without AOTInductor: compile and run the entire model with Inductor directly in Python and see if you also see that divergence. If there is divergence in regular torch.compile, you can also ablate backends to see who is causing the difference.
