### ISSUE TITLE
test_distributed_spawn always using shared init file method

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#123733]
In CI, test_distributed_spawn is run with an environment variable called INIT_METHOD, https://github.com/pytorch/pytorch/blob/b287dbbc249010c2249bc1af44ff4f97916d3df2/test/run_test.py#L747 but It gets overwritten later by https://github.com/pytorch/pytorch/blob/b287dbbc249010c2249bc1af44ff4f97916d3df2/torch/testing/_internal/common_distributed.py#L496 since the test case always calls this function with the init_method as none regardless of the env var https://github.com/pytorch/pytorch/blob/b287dbbc249010c2249bc1af44ff4f97916d3df2/torch/testing/_internal/distributed/distributed_test.py#L552.  

Should the test actually be run with the `env://` init method or should the testing for this method be removed?

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

**Comment by H-Huang** [comment]
I think the default is `INIT_METHOD` is `env://` anyways so we can just try to remove it? In most of distributed tests we are using filestore, but i think there may be some cases where we dont use files

**Comment by H-Huang** [comment]
closed by https://github.com/pytorch/pytorch/pull/128079
