### ISSUE TITLE
Bad Inputs to GPU CrossEntropyLoss puts CUDA into a dirty state

### ISSUE THREAD

**Issue by Erotemic** [pytorch/pytorch#12372]
## 🐛 Bug

On the GPU, if you pass CrossEntropyLoss a label id that is larger than the number of columns in the the network predictions, it results in an uncaught C++ error, which seems to bork the internal torch state. All further operations results in a RuntimeError. Note that the problem does not exist on the CPU side. 

Also, I've only tested on torch 0.4.1, its possible this was fixed in 1.0, but I haven't checked. However, I did do a quick search and AFAIK this bug has not yet been reported. 

## To Reproduce

```python
import torch
criterion = torch.nn.CrossEntropyLoss(reduction='none')

# Setup dummy data
bsize = 16
num_classes = 5
# Dummy groundtruth labels
labels = torch.randint(num_classes, (bsize,)).long()
# Dummy network class probability predictions
probs = torch.rand(bsize, num_classes)

# Computing the loss here works correctly
loss = criterion(probs, labels)

#---------
# Expected behavior on the CPU
#---------
# Error case, where a target class id is greater than probs.shape[0]
labels[0] = num_classes + 1
loss = criterion(probs, labels)
# The previous line correctly threw a Python error, but we can still recover
# and execute more logic.
probs + 3


#---------
# Unexpected behavior on the GPU
#---------
# But when we move to the GPU bad things happen
xpu = torch.device(0)
probs = probs.to(xpu)
labels = labels.to(xpu)

loss = criterion(probs, labels)

# I would expect the previous line to throw a Python error, but instead we get
# a message written to stdout:
#
# /pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [0,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.


# And now the device seems to be in a dirty state. Any further attempt
# to execute code results in RuntimeErrors.
probs + 3
# RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:21
```

## Expected behavior

The GPU version should raise: `RuntimeError: Target 6 out of bounds at `

## Environment
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 390.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by SsnL** [comment]
Yes, and it is expected because it is a CUDA device assert. Unfortunately you can't recover from a device assert because of CUDA limitations. This is out of hand.
