### ISSUE TITLE
.requires_grad_(True) doesn't work with torch.compile

### ISSUE THREAD

**Issue by juuso-oskari** [pytorch/pytorch#123713]
### 🐛 Describe the bug

I'm trying to change .requires_grad status inside the function that gets compiled, but it doesn't work. Without compiling it works. Here's the code that reproduces the problem: 

```
import torch
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.activation = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.activation(x)
        x = self.fc2(x)
        return x
    

def task(model_1, model_2, input, target_output):
    # Forward pass
    with torch.no_grad():
        intermediate_output = model_1(input)
    intermediate_output.requires_grad_()
    print(intermediate_output.requires_grad) # prints false if doing task = torch.compile(task), true if not
    output = model_2(intermediate_output)
    loss_fn = nn.MSELoss()
    loss = loss_fn(output, target_data)
    return loss


# Subsequent modules test
input_size = 1 # xy location
hidden_size = 32
output_size = 1 # rgb 

model_1 = SimpleNN(input_size, hidden_size, output_size)
model_2 = SimpleNN(input_size, hidden_size, output_size)

# Creating random input and target tensors
torch.manual_seed(42)  # For reproducibility
N = 100  # Batch size
input_data = torch.randn(N, input_size)
target_data = torch.randn(N, output_size)

task = torch.compile(task)

for i in range(100):
    loss = task(model_1, model_2, input_data, target_data)
    loss.backward()
```
 
    
    
This problem has been discussed in https://discuss.pytorch.org/t/requires-grad-true-doesnt-work/199601/3.
    

### Versions

Heres the versions I'm running:

Python version: 3.8.18

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.8
[pip3] numpy==1.24.2
[pip3] pytorch-msssim==1.0.0
[pip3] torch==2.0.1+cu117
[pip3] torch-efficient-distloss==0.1.3
[pip3] torch-ema==0.3
[pip3] torch-fidelity==0.3.0
[pip3] torch-tb-profiler==0.4.3
[pip3] torchmetrics==1.0.1
[pip3] torchtyping==0.1.4
[pip3] torchvision==0.15.2+cu117
[pip3] torchviz==0.0.2
[pip3] triton==2.0.0
[conda] pytorch-msssim            1.0.0                    pypi_0    pypi
[conda] torch                     2.0.1+cu117              pypi_0    pypi
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchtyping               0.1.4                    pypi_0    pypi
[conda] torchvision               0.15.2+cu117             pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by ezyang** [comment]
This is a known limitation of AOTAutograd. @bdhirsh does the recent ppFSDP stuff cover this case?

**Comment by bdhirsh** [comment]
no (sadly) - the ppFSDP stuff doesn't involve mutating the `requires_grad` field.

**Comment by bdhirsh** [comment]
Although @juuso-oskari have you tried on a nightly? This doesn't repro for me (it prints `True` correctly).

We actually graph break on `x.requires_grad_()` today

**Comment by juuso-oskari** [comment]
Thanks @bdhirsh, it works with the nightly build. Closing
