### ISSUE TITLE
tlparse: aot_compile doesn't setup compile ids

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#123759]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/6829516587176185/posts/7079346225526552/

In this tlparse: https://interncache-all.fbcdn.net/manifold/tlparse_reports/tree/logs/.tmpzjqkXZ/index.html we don't have compile ids for any of the build stuff:

<img width="795" alt="image" src="https://github.com/pytorch/pytorch/assets/13564/d9d19cbf-445a-4cee-bf31-7bd99eba1568">

This probably because aot_compile is exfiltrating the graph out and then compiling it outside of the dynamo callback.

cc @msaroufim @bdhirsh @anijain2305 @chauhang @jamesjwu 

### Versions

main

**Comment by IvanKobzarev** [comment]
Hi @ezyang, doing issue scrapping, is this issue still relevant or can be closed?

**Comment by ezyang** [comment]
It is still broken.

```
import torch

def f(x):
    return x + 2

torch._export.aot_compile(f, (torch.randn(3),))
```

run with

```
rm -rf /tmp/r && TORCH_TRACE=/tmp/r python rep.py
```

and you get

<img width="1170" alt="image" src="https://github.com/user-attachments/assets/088b31cd-a609-4398-b4d6-dbd7003303a5">

https://interncache-all.fbcdn.net/manifold/tlparse_reports/tree/logs/.tmp77Kc6C/index.html

**Comment by bdhirsh** [comment]
In the normal compile flow, it looks like `trace_structured()` gets the current compile id by setting some global state that dynamo has set (`torch._guards.CompileContext.current_trace_id()`): https://github.com/pytorch/pytorch/blob/main/torch/_logging/_internal.py#L1167C29-L1167C76

This info is not populated under aot_compile, because `aot_compile` operatoes in two steps:

Step 1: Run `torch._dynamo.export` to get out a (dynamo-level) GraphModule: https://github.com/pytorch/pytorch/blob/main/torch/export/_trace.py#L564

Step 2: Run `inductor.aot_compile` on that GraphModule (which will retrace the graph to generate an ATen graph / inductor output): https://github.com/pytorch/pytorch/blob/main/torch/_export/__init__.py#L338

So we probably need some way of plumbing the dynamo compile ids from step 1 into step 2. One option might be to have `torch._dynamo.export` return the compile id info, so export can manually set it during 2? (although idk if anybody usages this API externally)

**Comment by bdhirsh** [comment]
Separately, we are also probably not going to get a good tlparse today during non-strict export. I'm guessing that `aot_compile` also has a way of going through non-strict although I'm not sure.

**Comment by ezyang** [comment]
https://fb.workplace.com/groups/257735836456307/permalink/770747065155179/ relevant

**Comment by ezyang** [comment]
let me share the comment here: for the public

# tlparse for export workflows

tlparse is ubiquitously used for analyzing usage of torch.compile for eager mode workflows. It is sometimes used for also analyzing export workflows, but you are apt to get a tlparse that looks like this:

![image](https://github.com/user-attachments/assets/942b2a4e-cd1d-4af0-991a-c3898a9b04b9)

The root cause of this problem is that there is no "compile context" for steps in an export pipeline, compared with PT2 eager. In PT2 eager, when I trigger compilation (either from Dynamo, or backwards trigger in AOTAutograd), I setup a compile context with a compile id that I use to identify where log products come from. However, export doesn't mandate a particular pipeline/high level framework for doing transforms: after you do torch.export.export, you get an ExportedProgram and you can do whatever you want with it. The "whatever you want" with it doesn't have any compile context associated with it, so tlparse says its all unknown.

I had a discussion with Angela Yi yesterday about what to do about this. Here is the new model we came up with. Intuitively, there are "stages" of export processing that are associated calls to high level API functions that we control, like aot_compile. Each of these high level API functions should be responsible for setting up a context that describes the stage in question. For example, when you call aot_compile, it will setup a context saying "this is an aot_compile stage" and all the internal logging we do there will be associated with this stage.

How ought we relate these stages together? In eager, the compile ids are ordered chronologically and we also have a stack trie saying how their stack traces relate together in the entire program. For export, we think a more data oriented relationship makes sense. Imagine I have an export pipeline that looks like this (this example is contrived so as to show the essential properties of what I want):

```
ep = torch.export.export(mod)
print(aot_compile(ep, ...))
print(serialize(ep, ...))
ep2 = run_pass1(ep)
ep3 = run_pass2(ep2)
...
```

I want to visualize the data flow of exported programs through the various stages of export, like this:

![image](https://github.com/user-attachments/assets/3779a26b-5451-4235-8e25-a381b2684fc0)

What does this mean for export internals? I need three things:

1. I need a new instrumentation API that sets up an export stage context, which structured logs put into logs and tlparse can understand in lieu of compile id.
2. I need all of export's high level APIs (e.g., torch.export, aot_compile, etc) to setup this stage context so that their internals get attributed correctly.
3. I need exported program to maintain some strong notion of identity (maybe just a globally unique counter that increments) so that I can say "this export stage took in EP 123 as its argument"
