### ISSUE TITLE
Bug in torch.distributions.Beta

### ISSUE THREAD

**Issue by kulalexey** [pytorch/pytorch#12373]
## 🐛 Bug

For some alpha and beta parameters Beta distribution generates wrong samples (and sometime crash kernel)

## To Reproduce

Following code generate samples with wrong distribution (cpu only). Sometimes generate 'nan's. Sometimes kernel die.
```
distr = torch.distributions.Beta(torch.tensor([1], dtype=torch.float32, device=torch.device('cpu')), torch.tensor([1], dtype=torch.float32, device=torch.device('cpu')))
data = distr.sample((100,))
```

alpha=beta=1e-2 generates samples with wrong distribution on both cpu and gpu.

Following code often crash kernel:
```
distr = torch.distributions.Beta(torch.tensor([72], dtype=torch.float32, device=torch.device('cpu')), torch.tensor([15], dtype=torch.float32, device=torch.device('cpu')))
data = distr.sample((1000000,))
```

jupyter notebook with demonstration: https://gist.github.com/kulalexey/c12fea55a22a553ec8f2de7d369dae0f#file-beta-bug-ipynb

## Expected behavior
For example for alpha=beta=1 distribution is a straight line

## Environment

 - PyTorch Version (e.g., 1.0): 0.4.1
 - OS (e.g., Linux): Windows-10-10.0.17134-SP0
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): install compiled binaries
 - Python version: 3.6.1
 - CUDA/cuDNN version: 9.0 / 7005
 - GPU models and configuration: Titan V
 - Any other relevant information:

**Comment by samedii** [comment]
I only get this error if the parameters are tensors. It does not appear if I get the number from the tensor first. I thought this might be helpful in debugging

```
# incorrect results
alpha = torch.tensor([0.8453])
beta = torch.tensor([2.3126])
prob = torch.distributions.beta.Beta(
    alpha,
    beta
).rsample((100,))
print(prob)

# correct results
alpha = torch.tensor([0.8453])
beta = torch.tensor([2.3126])
prob = torch.distributions.beta.Beta(
    alpha.item(),
    beta.item()
).rsample((100,))
print(prob)
```

**Comment by samedii** [comment]
After looking a bit more and from my limited understanding of the framework it seems quite likely that `torch._standard_gamma()` is not behaving properly when views are involved. This would affect the Gamma distribution as well

Cloning immediately after expanding also "resolves" the issue:

```
def rsample(self, sample_shape=()):
    shape = self._extended_shape(sample_shape)
    # this clone has no effect
    # self.concentration = self.concentration.clone()
    print(self.concentration)
    print(shape)
    concentration = self.concentration.expand(shape)
    # this clone "resolves" the issue
    concentration = concentration.clone()

    if isinstance(concentration, torch.Tensor):
        return _Dirichlet.apply(concentration)
    return _dirichlet_sample_nograd(concentration)
```

**Comment by samedii** [comment]
I tried going into the ATen code and trying to figure this out but it is little steep for me. I would hope that the issue lies in the in-place operation `torch._standard_gamma()` rather than `Tensor.expand()` since that might be a larger problem

The code below is enough to recreate the problem:
```
concentration = torch.tensor([[2.3126, 0.8453]]).expand([2, 1, 2])
print(torch._standard_gamma(concentration))
print(torch._standard_gamma(concentration.clone()))

# tensor([[[7.1208e-01, 3.6902e-01]],
#         [[1.1755e-38, 1.1755e-38]]])
# tensor([[[1.4383, 0.5455]],
#         [[3.3665, 0.1593]]])
```
Note that the problem only occurs when there is at least one dimension with length 1

@fritzo Do you have any good ideas? I can try to assist but this dive is quickly becoming quite deep for an amateur in the inner workings of pytorch

**Comment by weiyangfb** [comment]
According to @alicanb, this should have been fixed in current master:
```
>>> c = torch.tensor([[2.3126, 0.8453]]).expand([2, 1, 2])
>>> print(torch._standard_gamma(c))
tensor([[[1.0952, 3.2572]],

        [[6.3712, 0.3182]]])

>>> print(torch._standard_gamma(c.clone()))
tensor([[[4.5180, 0.2300]],

        [[1.1852, 0.7473]]])
```

**Comment by soumith** [comment]
closing based on the last 2 comments. If that's not the case, do reopen.

**Comment by trdavidson** [comment]
> https://github.com/pytorch/pytorch/issues/12373#issue-367261213

The behavior for values of a = b = 1e-2 is still very much wrong. Does not appear to matter if one uses tensors or float values.

![screen shot 2019-01-04 at 5 52 08 pm](https://user-images.githubusercontent.com/7077018/50699925-81550300-1049-11e9-994d-30823bc84b39.png)

**Comment by fritzo** [comment]
@trdavidson cold you open a separate issue about numerical instability of Beta? Your observation is unrelated to this issue, which concerns expanded tensors.

**Comment by trdavidson** [comment]
@fritzo - done: https://github.com/pytorch/pytorch/issues/15738#issue-396007087
