### ISSUE TITLE
The speed of loading data is very slow when use python 3.6

### ISSUE THREAD

**Issue by larryhancock** [pytorch/pytorch#1237]
When I try to run dcgan from pytorch/examples, I selected the cifar 10 dataset. It took very long time to load cifar 10 into gpu memory while cifar 10 is relatively small dataset compared with dataset like imagenet or lsun. After switch to python 3.5, the data loading process finishes quickly.

**Comment by soumith** [comment]
it's likely that the first time you ran the example, the cifar10 dataset was being downloaded.
And when you subsequently ran it with py3.5, it didn't have to redownload it.
If you switch back to py3.6, it should be fast.

**Comment by larryhancock** [comment]
Thanks, I'm sure that before I ran the example, the dataset has been already successfully downloaded. Firstly, I thought there may be something wrong with my hard disk drive, then I switched into another drive, the problem remains.

**Comment by Cadene** [comment]
@larryhancock do you have the same version installed for py3.5 and py3.6 ?
You should try to reinstall.

One month ago I had the same problem. I was using pytorch CUDA 7.5 with a CUDA 8.0 setup.

**Comment by larryhancock** [comment]
@Cadene I try to rerun the example on another machine with py3.6 and pytorch, and this time there is no problem. Something is wrong with the machine I previously used. Thanks.
