### ISSUE TITLE
Validate cheerry-picks for release 2.3

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#123734]
Validate that Following issues are resolved

- [x] https://github.com/pytorch/pytorch/issues/123225 - @atalman 
- [x] https://github.com/pytorch/pytorch/issues/107302 - @PaliC 
- [x] https://github.com/pytorch/pytorch/issues/122705 - @huydhn 
- [x] https://github.com/pytorch/pytorch/issues/123296
- [x] https://github.com/pytorch/pytorch/issues/122016 @atalman 
- [x] https://github.com/pytorch/pytorch/issues/120211 - @PaliC 
- [x] https://github.com/pytorch/pytorch/issues/120406 - @atalman 
- [x] https://github.com/pytorch/pytorch/issues/115482 - @atalman 
- [x] https://github.com/pytorch/pytorch/issues/122056 - @atalman
- [ ] https://github.com/pytorch/pytorch/pull/121561
- [x] https://github.com/pytorch/pytorch/pull/122000 - (@atalman contacted Thiago Crepaldi on slack to validate the fix)
- [x] https://github.com/pytorch/pytorch/pull/121381 @atalman
- [x] https://github.com/pytorch/pytorch/pull/121731 - @atalman
- [x] https://github.com/pytorch/pytorch/issues/114602

**Comment by supernovae** [comment]
👀
