### ISSUE TITLE
impl_abstract should error out if someone passes a function to `m.def(`

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#123741]
It doesn't seem to, but I remember we do something similar for Meta impls and CompositeImplicitAutograd kernels

**Comment by yushangdi** [comment]
@zou3519 Do you mean something like below should error out with `We should not register a meta kernel directly to the operator....`?

```python

m = torch.library.Library("mylib", "FRAGMENT")
def foo_impl(x: torch.Tensor) -> torch.Tensor:
    return x.sin()

m.define("foo(Tensor x) -> Tensor")

@torch.library.register_fake("mylib::foo")
def _(x: torch.Tensor) -> torch.Tensor:
    return x.new_empty(x.shape)
```

**Comment by zou3519** [comment]
Yes. It sounds like we fixed it sometime in the last couple of months
