### ISSUE TITLE
`defaultdict` recompilations

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#123894]
### 🐛 Describe the bug

We have exceed recompilation default limit  decorating `torch.compile` this `def`:
https://github.com/hkchengrex/Cutie/blob/main/cutie/model/losses.py#L62

### Error logs
last reason: L['num_objects'][1] == 1
_No response_

### Versions

pytorch-nightly

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by soulitzer** [comment]
Do you have more information about this issue?

**Comment by bhack** [comment]
It is the classical message related to have more then `8` recompilation. This model has other compile issue at:
https://github.com/pytorch/pytorch/issues/123560

So what could support the reproducibility? As it could be hard to isolate/minimize every function.

**Comment by IvanKobzarev** [comment]
Hi @bhack , doing issue scrapping , is this issue still relevant or it was fixed?
Do you have a minimal repro?

**Comment by bhack** [comment]
I don't know after 5 months I am not on the same code to retry a new nightly. If you want you can close it.
