### ISSUE TITLE
Minimal example of incorrect MPS-related indexing

### ISSUE THREAD

**Issue by manifoldhiker** [pytorch/pytorch#123836]
### 🐛 Describe the bug

Writing to `cpu` tensor with `mps` values gives incorrect unexpected results 🐛 .

```python
import torch

M = torch.zeros(3,3, device='cpu')

M[1,1] = torch.tensor([3.], device='mps')
M[-1,-1] = torch.tensor([-3.], device='mps')
M[0,1] = torch.tensor([32.], device='mps')

print(M)

"""
tensor([[32.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])
"""
```

The same code works correctly with T4 in colab.

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] lovely-numpy==0.2.9
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] onnxruntime==1.16.0
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[conda] lovely-numpy              0.2.9                    pypi_0    pypi
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by manifoldhiker** [comment]
May be related to https://github.com/pytorch/pytorch/issues/122233

**Comment by malfet** [comment]
Is there a reason you have to use pytorch-2.0 release? 
This works fine for me in 2.2 release:
```
% cat bug-123836.py 
import torch

M = torch.zeros(3,3, device='cpu')

M[1,1] = torch.tensor([3.], device='mps')
M[-1,-1] = torch.tensor([-3.], device='mps')
M[0,1] = torch.tensor([32.], device='mps')

print(torch.__version__, M)
% python bug-123836.py 
2.2.1 tensor([[ 0., 32.,  0.],
        [ 0.,  3.,  0.],
        [ 0.,  0., -3.]])
```
