### ISSUE TITLE
reparameterization should use swap_tensors for tensor subclasses

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#123859]
as titled, we should use `swap_tensors` for reparameterization when using tensor subclasses, currently it's using `original.set_` which would not work for tensor subclass https://github.com/pytorch/pytorch/blob/main/torch/nn/utils/parametrize.py#L160

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Thanks for reporting this, this sounds reasonable indeed, assigning to myself. Out of curiousity, what is the use case for reparametrizations with tensor subclassses?

**Comment by wanchaol** [comment]
> Thanks for reporting this, this sounds reasonable indeed, assigning to myself. Out of curiousity, what is the use case for reparametrizations with tensor subclassses?

It's currently an exploration that I want to see how it could work together with DTensor, and I'm trying to understand how reparameterization works, then I hit this ;)

**Comment by mikaylagawarecki** [comment]
Got it!

fyi: I looked into making this change this morning, it seems that with parametrizations there are specific cases (e.g. when using nested parametrizations or `transfer_parametrizations_and_params`) where the `use_count` of the `THPVariable->cdata` for the tensor is 2, which causes `swap_tensors` to fail here 

https://github.com/pytorch/pytorch/blob/07e0faf3ef2ae10952011d034124d11a7a70c3da/torch/csrc/Module.cpp#L370-L377

Will need further investigation to see whether this is something we can fix in the implementation with more careful handling
