### ISSUE TITLE
[inductor][cpu]pyhpc_turbulent_kinetic_energy AMP multithread static/dynamic shape default/cpp wrapper performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#123801]
### 🐛 Describe the bug

<p>AMP static shape default wrapper </p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>pyhpc_turbulent_kinetic_energy</td>
      <td>multiple</td>
      <td>1048576.0</td>
      <td>0.681654</td>
      <td>0.059579171</td>
      <td>0.040612380228834</td>
      <td>19.111897</td>
      <td>1048576</td>
      <td>1.192818</td>
      <td>0.033925531999999994</td>
      <td>0.04046698522917599</td>
      <td>18.545272</td>
      <td>0.57</td>
      <td>1.0</td>
      <td>0.57</td>
      <td>0.97</td>
    </tr>

</table>

<p>AMP static shape cpp wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>pyhpc_turbulent_kinetic_energy</td>
      <td>multiple</td>
      <td>1048576.0</td>
      <td>0.660574</td>
      <td>0.059667036</td>
      <td>0.039414492638664</td>
      <td>26.560842</td>
      <td>1048576</td>
      <td>1.15076</td>
      <td>0.033984127999999995</td>
      <td>0.03910757513727999</td>
      <td>25.897208</td>
      <td>0.57</td>
      <td>0.99</td>
      <td>0.57</td>
      <td>0.98</td>
    </tr>

</table>

<p>AMP dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>pyhpc_turbulent_kinetic_energy</td>
      <td>multiple</td>
      <td>1048576.0</td>
      <td>0.653917</td>
      <td>0.05925169</td>
      <td>0.03874568736973</td>
      <td>19.05224</td>
      <td>1048576</td>
      <td>1.187297</td>
      <td>0.031205777</td>
      <td>0.037050525414769005</td>
      <td>17.053175</td>
      <td>0.55</td>
      <td>0.96</td>
      <td>0.53</td>
      <td>0.9</td>
    </tr>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>d6015d42</td>
      <td>main</td>
      <td>d6015d42</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>bb04f3f66a5b92f0bed3712689f57774f00db349</td>
      <td>main</td>
      <td>781e8d2201c1e2aaeccbbc7b7b13f9322b481bc9</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+2c4665f</td>
      <td>main</td>
      <td>0.19.0a0+2c4665f</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.2.0a0+ea437b3</td>
      <td>main</td>
      <td>2.2.0a0+ea437b3</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference performance torchbench pyhpc_turbulent_kinetic_energy amp first static/dynamic default/cpp
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/bac2a39aee11a2d052baefef2cdbfb9db446afe7
[torchbench-pyhpc_turbulent_kinetic_energy-inference-amp-dynamic-default-multiple-performance-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/14940461/torchbench-pyhpc_turbulent_kinetic_energy-inference-amp-dynamic-default-multiple-performance-drop_guilty_commit.log)
cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @WeizhuoZhang-intel @chuanqi129

**Comment by leslie-fang-intel** [comment]
Thanks for reporting the issue will take a look soon.

**Comment by leslie-fang-intel** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/123899

**Comment by leslie-fang-intel** [comment]
@zxd1997066 please help to verify.

**Comment by zxd1997066** [comment]
In the latest report, the regression issue is fixed.
