### ISSUE TITLE
Change model size or load weights will cause multiprocessing deadlock

### ISSUE THREAD

**Issue by xtzd** [pytorch/pytorch#123828]
### 🐛 Describe the bug

Change model size or load weights will cause multiprocessing deadlock. But WHY? Below are one case.
```
import multiprocessing
import torch 
import torch.nn as nn 
 
# Change the hidden from 128 to 6 will erase the stuck?
strange_hidden = 128

lstm = nn.LSTM(input_size=2, hidden_size=strange_hidden, num_layers=1, batch_first=True)
torch.save(lstm.state_dict(),"./plain.pt") 

def run(inputs): 
    model = nn.LSTM(input_size=2, hidden_size=strange_hidden, num_layers=1, batch_first=True)
    model.load_state_dict(torch.load("./plain.pt")) 
    x=model(inputs) 
    return x 

state=torch.rand(1,1,2) 
print("CHECKPOINT 0 PASS")

# Comment the line below will erase the stuck
lstm.load_state_dict(torch.load("./plain.pt"))
# Comment the line above will erase the stuck
# What is weird, if I change the strange hidden_size from 128 to 6, it would never stuck!


x = lstm(state)
print(x[0].shape)
print("CHECKPOINT 1 PASS")

pool = multiprocessing.Pool(5)
for i in range(5):
    pool.apply_async(func=run,args=(state,))
pool.close()
pool.join()
print("CHECKPOINT 2 PASS")
```

Strange bug or I made some mistake? I tried on muliple pytorch version, it is still the same. And it is noticed the number 90 is special? Set hidden size below 90 will erase the deadlock.

### Versions

PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-163-generic-x86_64-with-glibc2.17

CPU:
Architecture:                       x86_64

Versions of relevant libraries:
[pip3] botorch==0.6.2
[pip3] gpytorch==1.10
[pip3] lion-pytorch==0.1.2
[pip3] numpy==1.22.4
[pip3] onnx==1.12.0
[pip3] onnxconverter-common==1.9.0
[pip3] pytorch-tabnet==3.1.1
[pip3] torch==1.12.1+cu116
[pip3] torchaudio==0.12.1+cu116
[pip3] torchsort==0.1.9
[pip3] torchvision==0.13.1+cu116
[conda] botorch                   0.6.2                    pypi_0    pypi
[conda] gpytorch                  1.10                     pypi_0    pypi
[conda] lion-pytorch              0.1.2                    pypi_0    pypi
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch-tabnet            3.1.1                    pypi_0    pypi
[conda] torch                     1.12.1+cu116             pypi_0    pypi
[conda] torchaudio                0.12.1+cu116             pypi_0    pypi
[conda] torchsort                 0.1.9                    pypi_0    pypi
[conda] torchvision               0.13.1+cu116             pypi_0    pypi

cc @VitalyFedyunin @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by xtzd** [comment]
Also tried using PyTorch version: 2.2.2+cpu ，nothing has been changed. But using Windows OS, it seems to be different, the stuck never happens. So it only occurs when using Linux OS. Maybe it's about subprocess forking methods?

**Comment by mikaylagawarecki** [comment]
I'm not able to produce on `main`

**Comment by xtzd** [comment]
> I'm not able to produce on `main`

Did you try it on Linux？It would not be stuck on Windows.

**Comment by albanD** [comment]
I'm afraid this is another instance of https://github.com/pytorch/pytorch/issues/17199 

You can avoid this issue by doing `torch.set_num_threads(1)` in the main script and set it back to the appropriate value that you want inside the run() function for each child.

**Comment by xtzd** [comment]
> I'm afraid this is another instance of #17199
> 
> You can avoid this issue by doing `torch.set_num_threads(1)` in the main script and set it back to the appropriate value that you want inside the run() function for each child.

Thank you very much for the reminder. That post #17199 is indeed highly relevant to this issue.
**torch.set_num_threads(1)** does solve the problem！And it is another brother case of #89693 , a special case of that #17199 ！The issue seems to be related to calling **load_state_dict**   in main process.

**Comment by albanD** [comment]
Anything triggering OMP initialization in the main process will lead to this. In your case, the call to `copy_()` within `load_state_dict` is most likely the culprit indeed.

Closing this one as duplicate. We should discuss in the other issue if we have ideas on how to improve detection!

**Comment by xtzd** [comment]
> Anything triggering OMP initialization in the main process will lead to this. In your case, the call to `copy_()` within `load_state_dict` is most likely the culprit indeed.
> 
> Closing this one as duplicate. We should discuss in the other issue if we have ideas on how to improve detection!

Thanks for closing as duplicate and leading to the other issue!
BTW, the copy_() method might be the reason, but it still cannot explain why when the model size shrinks to be smaller, the culprit disappear.

**Comment by albanD** [comment]
This is because we trigger multithreaded copy (and thus OMP) when doing the copy_() only if there is enough work to be done so that it is worth to use multiple threads.
This indeed leads to even more confusion as different Tensor size will lead to different behavior :(
