### ISSUE TITLE
maybe_evaluate_static performance problem with unbacked SymInts

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#123964]
### 🐛 Describe the bug

This subs call is apparently very expensive

```
            for e in itertools.chain(self.guards, self.deferred_runtime_asserts.get(s, ())):
                e = e.expr
                if compute_hint:
                    e = canonicalize_bool_expr(e.xreplace(self.var_to_val))
                add_expr(e)
                # Other relational expressions this expression implies
                if isinstance(e, sympy.Eq):
                    add_expr(sympy.Le(e.lhs, e.rhs))
                    add_expr(sympy.Ge(e.lhs, e.rhs))
                elif isinstance(e, sympy.Lt):
                    add_expr(sympy.Le(e.lhs, e.rhs))
                    add_expr(sympy.Ne(e.lhs, e.rhs))

            # NB: this helps us deal with And/Or connectives
            expr = expr.subs(subst)  # THIS ONE!!!
```

<img width="923" alt="image" src="https://github.com/pytorch/pytorch/assets/13564/e47e789f-a919-4c41-be78-a92cc34440d5">

One potential reason this is expensive is because the size of subst grows according to the number of deferred runtime asserts. So if we keep adding new deferred runtime asserts, subst gets bigger and bigger, leading to quadratic runtime.

cc @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @lezcano @avikchaudhuri 

### Versions

main

**Comment by laithsakka** [comment]
<img width="1076" alt="Screenshot 2024-04-12 at 12 59 35 PM" src="https://github.com/pytorch/pytorch/assets/13970752/8f314913-7c50-456a-8336-6f651b49e70b">
looks like _aresame is taking too long specifically

**Comment by IvanKobzarev** [comment]
Repro:
```
        def fn(ti: torch.Tensor, tv: torch.Tensor):
            l = ti.tolist()
            [torch._check_is_size(i) for i in l]
            sum = 0
            for i in l:
                torch._check(i < tv.size(0))
                sum += tv[i].item()
            return sum

        torch._dynamo.config.capture_scalar_outputs = True
        torch._dynamo.config.capture_dynamic_output_shape_ops = True

        ti = torch.arange(1000, dtype=torch.int32)
        tv = torch.ones(1000, dtype=torch.int32)

        torch.compile(fn, backend="eager", dynamic=True, fullgraph=True)(ti, tv)
  ```

**Comment by lezcano** [comment]
I was going to cache it on changes of the ShapeEnv, but I haven't done that yet. Feel free to put up a PR, or I'll do that in a week's time once I'm back.

**Comment by lezcano** [comment]
Also, note that for deferred asserts, we just pull those that are part of the formula, so the quadratic growth shouldn't be such unless you have a formula with many unbacked symbols.

**Comment by laithsakka** [comment]
40% of the time in _check_is_size.
to generate a strobe light profile one can run 
TORCH_COMPILE_SL_PROFILE=TRUE  buck2 run @mode/opt @mode/inplace   //torchrec/distributed/tests:test_pt2_train

**Comment by ezyang** [comment]
This repro is similar to Ivan's and also has problems:

```
import torch
import torch._dynamo.config

torch._dynamo.config.capture_scalar_outputs = True

@torch.compile(fullgraph=True)
def f(a, b):
    xs = b.tolist()
    for x in xs:
        torch._check_is_size(x)
        torch._check(x <= 20)
    return a.split(xs)

N = 2

splits = torch.randint(10, (N,))
sz = splits.sum().item()
            
f(torch.randn(sz), splits)
```

**Comment by IvanKobzarev** [comment]
https://github.com/pytorch/pytorch/pull/124208

**Comment by IvanKobzarev** [comment]
assert in check_is_size triggers heavy symbolic compute - skip for now

https://github.com/pytorch/pytorch/pull/124209

**Comment by IvanKobzarev** [comment]
sympy Expr equality uses hash() , can be avoided if to compare by expr name for us

https://github.com/pytorch/pytorch/pull/124211

**Comment by IvanKobzarev** [comment]
https://github.com/pytorch/pytorch/pull/124217

**Comment by zou3519** [comment]
@IvanKobzarev are you still working on this?

**Comment by IvanKobzarev** [comment]
> @IvanKobzarev are you still working on this?

No. But we definitely need this, for torch rec EBC num_features=1500.

**Comment by shazqadeer** [comment]
@IvanKobzarev: I started looking at this issue because it is still open despite the landing of several PRs by your to address it. Possibly due to a bunch of refactoring, I can't even locate the offending code that is listed in the original issue description by @ezyang. Please provide me an update on the status and a potential starting point for further investigation.

**Comment by IvanKobzarev** [comment]
@shazqadeer 
Yes, this compilation time issue is still unsolved.
The easiest starting point is to use torchrec test, that you used for views improvements.
But to use Variable Batch scenario (ConverToVariableBatch.True) and set num_features=300 Test time I expect to be about 5-10 minutes. Ideally the goal is to reduce that time, that num_features=1500 could fit in 15 mins (1000 was 50 mins compilation for me a month ago ). 

To get strobelight profiling - there is an env variable in my script, that starts from strobelight - it should enable strobelight profiling to get flame graphs. 

I will put the links tomorrow.

**Comment by ezyang** [comment]
> This repro is similar to Ivan's and also has problems:
> 
> 
> 
> ```
> 
> import torch
> 
> import torch._dynamo.config
> 
> 
> 
> torch._dynamo.config.capture_scalar_outputs = True
> 
> 
> 
> @torch.compile(fullgraph=True)
> 
> def f(a, b):
> 
>     xs = b.tolist()
> 
>     for x in xs:
> 
>         torch._check_is_size(x)
> 
>         torch._check(x <= 20)
> 
>     return a.split(xs)
> 
> 
> 
> N = 2
> 
> 
> 
> splits = torch.randint(10, (N,))
> 
> sz = splits.sum().item()
> 
>             
> 
> f(torch.randn(sz), splits)
> 
> ```

There's also a repro here
