### ISSUE TITLE
Make TRITON_INTERPRET=1 work with inductor generated kernels

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#123956]
### 🚀 The feature, motivation and pitch

If you try to run TRITON_INTERPRET=1 with inductor generated kernels you'll get an exception:

```
  File "/data/users/eellison/pytorch/torch/_inductor/triton_heuristics.py", line 365, in _precompile_config
    binary = triton.compile(*compile_args, **compile_kwargs)
  File "/home/eellison/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/triton/compiler/compiler.py", line 231, in compile
    key = f"{triton_key()}-{src.hash()}-{backend.hash()}-{options.hash()}-{str(sorted(get_env_vars().items()))}"
  File "/home/eellison/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/triton/compiler/compiler.py", line 106, in hash
    key = f"{self.fn.cache_key}-{self.attrs.hash()}-{sorted_sig}-{sorted_constants}"
```

It would be nice for debugging to add compatibility. 

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

**Comment by IvanKobzarev** [comment]
Hi @eellison , doing issue scrapping,
I tried  `TRITON_INTERPRET=1 python test/inductor/test_torchinductor.py -k test_avg`  and it does not fail.
Am I right that this issue was fixed and can be closed? Or it is still relevant?

**Comment by eellison** [comment]
It's still relevant. You may have not used on a devserver with gpu or something.

**Comment by eellison** [comment]
done !
