### ISSUE TITLE
Remove the warning in the LazyModuleMixin constructor

### ISSUE THREAD

**Issue by foxik** [pytorch/pytorch#123928]
### 🚀 The feature, motivation and pitch

Hi,

I propose to remove the warning in the `LazyModuleMixin` constructor:
https://github.com/pytorch/pytorch/blob/7fc3aa5f8168414b9bfbcf59df0e33450d96c424/torch/nn/modules/lazy.py#L176-L182

The warning says the lazy modules are a new feature and under heavy development; but that warning has been there for three and half years (d38a71d579dc2f03d7) and for the past  3 years -- looking at https://github.com/pytorch/pytorch/commits/main/torch/nn/modules/lazy.py -- the only changes were to docs or types (the newest change modifying code is b3fda95fe79bdb49)

Therefore, I feel like formally accepting the current design would be the best way to proceed.

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Feel free to send a PR removing this warning
