### ISSUE TITLE
Onnx dynamo does not export with torch._VF

### ISSUE THREAD

**Issue by doloresgarcia** [pytorch/pytorch#123939]
### 🐛 Describe the bug

Torch onnx dynamo does not export the model and raises unsupported at custom torch._VF function

### Error logs

`torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(einsum) __call__ [ConstantVariable(str), TupleVariable()] {'path': ListVariable()}`
`torch.onnx.OnnxExporterError: Failed to export the model to ONNX`
when using 
` torch._VF.einsum(equation, operands, path=path)  # type: ignore[attr-defined]`

### Versions

ython3: can't open file 'collect_env.py': [Errno 2] No such file or directory
Package                       Version             Editable project location
----------------------------- ------------------- -------------------------------------------------------
absl-py                       2.1.0
aiohttp                       3.9.4
aiosignal                     1.3.1
alabaster                     0.7.13
alembic                       1.13.1
annotated-types               0.6.0
antlr4-python3-runtime        4.9.3
anyio                         4.3.0
appdirs                       1.4.4
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
astroid                       2.13.5
asttokens                     2.4.1
async-lru                     2.0.4
async-timeout                 4.0.3
attrs                         23.2.0
autopep8                      2.0.4
awkward                       2.5.2
awkward-cpp                   28
awkward0                      0.15.5
axial-positional-embedding    0.2.1
Babel                         2.14.0
backcall                      0.2.0
beautifulsoup4                4.12.3
black                         22.8.0
bleach                        6.1.0
blosc2                        2.0.0
cachetools                    5.3.3
celluloid                     0.2.0
certifi                       2024.2.2
cffi                          1.16.0
chardet                       5.2.0
charset-normalizer            3.3.2
click                         8.0.4
clifford                      1.4.0
cliffordlayers                0.1.3.dev7+g74799cf
Send2Trash                    1.8.3
sentry-sdk                    1.32.0
setproctitle                  1.3.3
setuptools                    45.2.0
six                           1.16.0
smmap                         5.0.1
sniffio                       1.3.1
snowballstemmer               2.2.0
soupsieve                     2.5
sparse                        0.15.1
Sphinx                        7.1.2
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.46
sqlparse                      0.4.4
stack-data                    0.6.3
sympy                         1.12
tables                        3.8.0
tabulate                      0.9.0
tenacity                      8.2.3
tensorboard                   2.14.0
tensorboard-data-server       0.7.2
tensorboardX                  2.6.2.2
terminado                     0.18.1
threadpoolctl                 3.4.0
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.12.4
torch                         2.2.1
torch-cluster                 1.6.3
torch-ema                     0.3
torch_geometric               2.5.2
torch-scatter                 2.1.2
torch-sparse                  0.6.18
torch-spline-conv             1.2.2
torchaudio                    2.0.2
torchdata                     0.7.1
torchist                      0.2.2
torchmetrics                  1.3.2
torchvision                   0.17.1
tornado                       6.4
tqdm                          4.66.2
traitlets                     5.14.2
trimesh                       4.3.0
triton                        2.2.0
typer                         0.9.0
types-python-dateutil         2.9.0.20240316
types-tqdm                    4.66.0.20240106
typing_extensions             4.8.0
uproot                        5.3.3
uri-template                  1.3.0
urllib3                       2.2.1
vector                        1.3.1
vtk                           9.3.0
wandb                         0.15.12
wcwidth                       0.2.13
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.7.0
Werkzeug                      3.0.2
wheel                         0.34.2
widgetsnbextension            4.0.10
wrapt                         1.16.0
xenon                         0.9.0
xformers                      0.0.25
xxhash                        3.4.1
yacs                          0.1.8
yarl                          1.9.4
zipp                          3.18.1

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by justinchuby** [comment]
Do you know how einsum is used in the source? Could you share a snippet of it, as well as the code you used to export the model?

**Comment by IvanKobzarev** [comment]
Hi @doloresgarcia , doing issue scrapping, is this issue is still relevant?
Do you have a minified repro for it?

**Comment by IvanKobzarev** [comment]
Closing issue as 2 weeks without reply, feel free to repoen if this is still relevant.
