### ISSUE TITLE
on MPS, torch.embedding, Linear and others raise: RuntimeError: Placeholder storage has not been allocated on MPS device!

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/pytorch#123995]
### 🐛 Describe the bug

When running torch/chat, get "RuntimeError: Placeholder storage has not been allocated on MPS device!" (Works on other devices)

Repro Runs on pytorch ci @ https://github.com/pytorch/torchat/actions/runs/8670228545/job/23777955027?pr=162#step:9:85

        python generate.py --device mps --quant '{"embedding" : {"bitwidth": 8,\
 "group_size": 0}}' --checkpoint-path ${MODEL_PATH} --temperature 0 > ./output_\
eager
        cat ./output_eager
        python generate.py --device mps --quant '{"embedding" : {"bitwidth": 8,\
 "group_size": 8}}' --checkpoint-path ${MODEL_PATH} --temperature 0 > ./output_\
eager
        cat ./output_eager

https://github.com/pytorch/torchat/actions/runs/8670427606/job/23778418238?pr=162

    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/model.py", line 237, in forward
      h = x + self.attention(self.attention_norm(x), freqs_cis, mask, input_pos)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/model.py", line 299, in forward
      q = self.wq(x)
          ^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ec2-user/runner/_work/torchat/torchat/pytorch/torchat/quantize.py", line 486, in forward
      return F.linear(input, weight.to(dtype=input.dtype)) * self.scales
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^!
  
Also @ .github/workflows/ test-mps.yml in github.com/pytorch/torchat repo

### Versions

pytorch CI runner

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by malfet** [comment]
Can't reproduce this behavior, which hints that the problem is with the framework rather than with the op.
Working example:
```
% python3 -c "import torch;input=torch.rand(32, 32, device='mps');weight=torch.randint(-100, 100, (32, 32), dtype=torch.int8, device='mps');print(torch.nn.functional.linear(input, weight.to(dtype=input.dtype)))"
tensor([[-128.1944, -364.2294, -170.1153,  ...,   85.7090,  436.7084,
         -110.2555],
        [ 143.7325, -205.7133,  -53.5193,  ...,  160.2552,  457.7839,
          128.9414],
        [ 117.7807,  -88.7376,  234.1173,  ...,  122.3472,  237.0916,
           43.8516],
        ...,
        [ 190.6975, -291.7898, -196.6228,  ..., -179.1696,  449.8826,
          181.7411],
        [ 141.3238, -119.3400,   81.3521,  ...,  233.8064,  266.0544,
           93.9335],
        [  74.6703, -370.1714,  -55.6378,  ...,  153.2570,  502.8348,
           71.8237]], device='mps:0')
```
Example where exactly this error is printed
```
% python3 -c "import torch;input=torch.rand(32, 32, device='mps');weight=torch.randint(-100, 100, (32, 32), dtype=torch.int8);print(torch.nn.functional.linear(input, weight.to(dtype=input.dtype)))" 
RuntimeError: Placeholder storage has not been allocated on MPS device!
```

Grabbing for myself to print better error message

**Comment by jiyzhang** [comment]
Here is my test result: 
1. env
`sw_vers;python -c "import torch;print(torch.__version__, torch.rand(3, device='mps'))"
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
2.3.1 tensor([0.6535, 0.7202, 0.2196], device='mps:0')`

2. For the `input` and `weight`, if they are on the same device, it works as normal
1) both on CPU
`import torch

input=torch.rand(32, 32)
assert input.device.type == "cpu"

weight=torch.randint(-100, 100, (32, 32), dtype=torch.int8)
assert weight.device.type == "cpu"

print(torch.nn.functional.linear(input, weight.to(dtype=input.dtype)))`

2) both on MPS
`
import torch

input=torch.rand(32, 32, device='mps')
assert input.device.type == "mps"
weight=torch.randint(-100, 100, (32, 32), dtype=torch.int8, device='mps')
assert weight.device.type == "mps"

print(torch.nn.functional.linear(input, weight.to(dtype=input.dtype)))
`

3. The Runtime Error "Placeholder storage has not been allocated on MPS device!" occurred while `input` and `weight` are on different device

`
import torch

input=torch.rand(32, 32, device='mps')
assert input.device.type == "mps"
weight=torch.randint(-100, 100, (32, 32), dtype=torch.int8)
assert weight.device.type == "cpu"

print(torch.nn.functional.linear(input, weight.to(dtype=input.dtype)))

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[112], [line 8](vscode-notebook-cell:?execution_count=112&line=8)
      [5](vscode-notebook-cell:?execution_count=112&line=5) weight=torch.randint(-100, 100, (32, 32), dtype=torch.int8)
      [6](vscode-notebook-cell:?execution_count=112&line=6) assert weight.device.type == "cpu"
----> [8](vscode-notebook-cell:?execution_count=112&line=8) print(torch.nn.functional.linear(input, weight.to(dtype=input.dtype)))

RuntimeError: Placeholder storage has not been allocated on MPS device!
`

4. I didn't encounter this issue on macOS 14.3.

**Comment by MonolithFoundation** [comment]
Got simillar issue:

miniforge3/lib/python3.9/site-packages/torch/nn/functional.py", line 2264, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Placeholder storage has not been allocated on MPS device!
