### ISSUE TITLE
Improve CircleCI configuration

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#12396]
- [x] Reduce copy-pasta, make things more DRY.
- [x] Try to fix Caffe2 flaky tests in order to get rid of intermediate Docker image push. (See issue: https://github.com/pytorch/pytorch/issues/12395) (One solution I am exploring is to have CircleCI run our jobs on a new AMI that matches our Jenkins AMI more closely.)
- [ ] Show CircleCI master and PR statuses on https://ezyang.github.io/pytorch-ci-hud/
- [x] Right now the Docker image push flow is "create a new image" -> "test against master" -> "push to ECR" -> "update DockerVersion.groovy". But once all Linux jobs are removed from Jenkins, we might want to do "create a new image" -> "push to ECR" -> "open PR to test against master" -> "merge new image version number into master config.yml". For the ECR clean up job in Jenkins, we will let it check the newest version number from PyTorch repo and do the clean up accordingly.
- [ ] Move Docker image build process to CircleCI entirely.

For more details, see https://github.com/pytorch/pytorch/pull/12389#issuecomment-427491549.

**Comment by ngimel** [comment]
Closing due to age
