### ISSUE TITLE
Caffe2 flaky tests on CircleCI

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#12395]
When running on CircleCI, different tests are found to be flaky in different test environments. Here are the details:

-------------------------------------

### Test environment

**Host OS on CircleCI**: Ubuntu 14.04 (kernel: 3.13.0-151-generic) → Tests are flaky
(As comparison, on Jenkins we use Ubuntu 16.04 (kernel: 4.4.0-1062-aws) → Tests are stable)

**OS in Docker container**: Ubuntu 14.04 (kernel: 4.4.0-1062-aws)

**How are we sharing the build products from build stage to test stage?**
Build products are all in the intermediate Docker image which is shared from build stage to test stage.

### Flaky tests

1. TestFcOperator.test_fc
    1. caffe2_py2_gcc4_8_ubuntu14_04_test, https://circleci.com/gh/pytorch/pytorch/40627
2. TestCRFOp.test_crf_gradient
    1. caffe2_py2_gcc4_8_ubuntu14_04_test, https://circleci.com/gh/pytorch/pytorch/40508
3. TestReduceOps.test_reduce_min
    1. caffe2_py2_gcc4_8_ubuntu14_04_test, https://circleci.com/gh/pytorch/pytorch/40506
4. TestReduceFrontSum.test_col2im_gradients
    1. caffe2_py2_gcc4_8_ubuntu14_04_test, https://circleci.com/gh/pytorch/pytorch/40771
5. TestLayerNormOp.test_layer_norm_op
    1. caffe2_py2_gcc4_8_ubuntu14_04_test, https://circleci.com/gh/pytorch/pytorch/40507
    2. caffe2_py2_gcc4_8_ubuntu14_04_test, https://circleci.com/gh/pytorch/pytorch/40972
6. TestLayerNormOp.test_layer_norm_grad_op
    1. caffe2_py2_gcc4_8_ubuntu14_04_test, https://circleci.com/gh/pytorch/pytorch/41306
7. RecurrentNetworkTest.test_sum_mul
    1. caffe2_py2_gcc4_8_ubuntu14_04_test, https://circleci.com/gh/pytorch/pytorch/41027
8. TestAdagrad.test_row_wise_sparse_adagrad
    1. caffe2_py2_gcc4_8_ubuntu14_04_test, https://circleci.com/gh/pytorch/pytorch/41227

---------------------------

### Test environment

**Host OS on CircleCI**: Ubuntu 14.04 (kernel: 3.13.0-151-generic)  → Tests are flaky
(As comparison, on Jenkins we use Ubuntu 16.04 (kernel: 4.4.0-1062-aws) → Tests are stable)

**OS in Docker container**: Ubuntu 16.04 (kernel: 4.4.0-1062-aws)

**How are we sharing the build products from build stage to test stage?**
Build products are **copied** from build stage to test stage, without sharing the intermediate Docker image.

### Flaky tests

1. GRUCellTest.test_gru_unit_op
    1. caffe2_py2_cuda9_1_cudnn7_ubuntu16_04_test, https://circleci.com/gh/pytorch/pytorch/39963
2. TestLayerNormOp.test_layer_norm_grad_op
    1. caffe2_py2_cuda8_0_cudnn6_ubuntu16_04_test, https://circleci.com/gh/pytorch/pytorch/39939
3. TestGlu.test_glu_old
    1. caffe2_py2_cuda8_0_cudnn6_ubuntu16_04_test, https://circleci.com/gh/pytorch/pytorch/40017 
    2. caffe2_py2_cuda9_1_cudnn7_ubuntu16_04_test, https://circleci.com/gh/pytorch/pytorch/39980
4. TestConvolution.test_conv_separate_stride_pad_gradients
    1. caffe2_py2_cuda9_1_cudnn7_ubuntu16_04_test, https://circleci.com/gh/pytorch/pytorch/39989
5. TestReduceFrontSum.test_col2im_gradients
    1. caffe2_py2_cuda8_0_cudnn6_ubuntu16_04_test, https://circleci.com/gh/pytorch/pytorch/39979
6. TestGroupConvolution.test_group_convolution
    1. caffe2_py2_cuda9_0_cudnn7_ubuntu16_04_test, https://circleci.com/gh/pytorch/pytorch/39978

**Comment by ezyang** [comment]
Another case of GRUCellTest.test_gru_unit_op https://circleci.com/gh/pytorch/pytorch/95041?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by anderspapitto** [comment]
We have code that purports to pin hypothesis to an old version, but it doesn't actually work. pip outsmarts us and re-installs the newer version. 

relevant code is

```
        # Hotfix, use hypothesis 3.44.6 on Ubuntu 14.04
        # See comments on https://github.com/HypothesisWorks/hypothesis-python/commit/eadd62e467d6cee6216e71b391951ec25b4f5830
        if [[ "$BUILD_ENVIRONMENT" == *ubuntu14.04* ]]; then
          sudo pip uninstall -y hypothesis
          # "pip install hypothesis==3.44.6" from official server is unreliable on CircleCI, so we host a copy on S3 instead
          sudo pip install attrs -f https://s3.amazonaws.com/ossci-linux/wheels/attrs-18.1.0-py2.py3-none-any.whl
          sudo pip install coverage -f https://s3.amazonaws.com/ossci-linux/wheels/coverage-4.5.1-cp36-cp36m-macosx_10_12_x86_64.whl
          sudo pip install hypothesis -f https://s3.amazonaws.com/ossci-linux/wheels/hypothesis-3.44.6-py3-none-any.whl
        fi
```

and the relevant bit of logs is

```
Oct 24 03:54:38 ++ sudo pip install hypothesis -f https://s3.amazonaws.com/ossci-linux/wheels/hypothesis-3.44.6-py3-none-any.whl
Oct 24 03:54:39 The directory '/var/lib/jenkins/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Oct 24 03:54:39 The directory '/var/lib/jenkins/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Oct 24 03:54:39 Looking in links: https://s3.amazonaws.com/ossci-linux/wheels/hypothesis-3.44.6-py3-none-any.whl
Oct 24 03:54:39 Requirement already satisfied: hypothesis in /usr/local/lib/python2.7/dist-packages (3.76.0)
```

**Comment by yf225** [comment]
Need to confirm by removing `IN_CIRCLECI_FLAKY_ENV` from code base and observing no flakiness from previously flaky tests.
