### ISSUE TITLE
Change signature of set_flush_denormal

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#12399]
Currently, set_flush_denormal has the signature in C++:

```
bool set_flush_denormal(bool on)
```

(The Python types are the same)

The signature is a bit confusing because both the parameter and return type are bool, and it's easy to ignore the returned value.

We should change the return type to `void` and issue a warning (perhaps using `AT_WARN`) when the CPU doesn't support flushing denormals.

**Comment by adityashrm21** [comment]
Can you elaborate a little more on this? I see

**Comment by adityashrm21** [comment]
Can you elaborate a little more on this? I see two files with the code:
1. FlushDenormal.cpp
2. FlushDenormal.h

Where do you want the warning to be exactly?
Thanks!
