### ISSUE TITLE
nn.functional.interpolate very slow for fp16 (half) precision inputs

### ISSUE THREAD

**Issue by tstandley** [pytorch/pytorch#12409]
## 🐛 Bug

nn.funcitonal.interpolate runs several times slower for fp16 inputs. 
## To Reproduce

1. Run a neural network that has interpolation (up-sampling) under fp16. Note the slowness.
2. Convert the values to floats, run the same interpolation, then convert back to half. Note that it's less slow.
3. The network still suffers from the overhead of converting from half to float. 

## Expected behavior

The same or better performance when using fp16.

## Environment

Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN V
GPU 1: TITAN V

Nvidia driver version: 396.54
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py37_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
[conda] torchvision               0.2.1                    py37_1    pytorch

**Comment by SsnL** [comment]
On GPU?

**Comment by fmassa** [comment]
@SsnL probably, I'm not sure we support any more than copy for CPU float16 tensors

**Comment by tstandley** [comment]
Yes. On GPU.

**Comment by ohlr** [comment]
Is there any progress on this?

**Comment by fmassa** [comment]
Yes, interpolate performance is being improved for fp16, see https://github.com/pytorch/pytorch/pull/21694 and https://github.com/pytorch/pytorch/pull/21879

**Comment by fmassa** [comment]
btw, @ngimel is this is an issue now or can we close this?

**Comment by ngimel** [comment]
@fmassa, No, this is no longer an issue after the PRs that you've mentioned. @tstandley please reopen if it still reproduced in nightlies.
