### ISSUE TITLE
[torchbench] sam_fast model has memory leak due to PR#121313

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/pytorch#124081]
### 🐛 Describe the bug

See https://github.com/pytorch/benchmark/issues/2231
sam_fast model has CUDA memleak because of https://github.com/pytorch/pytorch/pull/121313, or commit https://github.com/pytorch/pytorch/commit/4044e93a51e

To reproduce:
1. Clone torchbench repo, and run `python install.py`
2. Run the following command
```
python test.py -k sam_fast
```

### Versions

Pytorch nightly

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by masnesral** [comment]
@aorenste, looks like you authored that PR. Do you mind having a look?

**Comment by aorenste** [comment]
> @aorenste, looks like you authored that PR. Do you mind having a look?

Already looking - didn't realize I hadn't assigned this to myself yet.
