### ISSUE TITLE
Compilation Error in release/1.7 due to Missing Definition for OneCycleLR in lr_scheduler.pyi

### ISSUE THREAD

**Issue by davidfrz** [pytorch/pytorch#124049]
### 🐛 Describe the bug

When using the **_release/1.7 branch_**, I encountered an error during the compilation process. 
The error appears to arise from the specific content about OneCycleLR defined in torch/optim/lr_scheduler.py, 
[https://github.com/pytorch/pytorch/blob/release/1.7/torch/optim/lr_scheduler.py](url)
`class OneCycleLR(_LRScheduler):`
yet there is a missing definition for OneCycleLR in torch/optim/lr_scheduler.pyi. 
[https://github.com/pytorch/pytorch/blob/release/1.7/torch/optim/lr_scheduler.pyi](url)
It seems that the .pyi stub file does not reflect the definitions in the actual .py file, leading to discrepancies that cause the compilation to fail. 

And tag around 1.7.x is also missing the "OneCycleLR" in pyi

### Versions

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 460.39
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py39he8ac12f_0  
[conda] mkl_fft                   1.3.0            py39h54f3939_0  
[conda] mkl_random                1.0.2            py39h63df603_0  
[conda] numpy                     1.19.2           py39h89c1606_0  
[conda] numpy-base                1.19.2           py39h2ae0177_0  
[conda] torch                     1.7.1              pypi_0    pypi
[conda] torchaudio                0.7.2                    pypi_0    pypi
[conda] torchvision               0.8.2            pypi_0    pypi

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by soulitzer** [comment]
Does this error still occur on the latest version of PyTorch?

**Comment by albanD** [comment]
FYI typing is definitely a WIP and was pretty bad at the time.
Also we do not backport fix so there is generally no plan to fix older versions.

**Comment by davidfrz** [comment]
> Does this error still occur on the latest version of PyTorch?

No，I found only in 1.7.x

**Comment by soulitzer** [comment]
I see, thanks. I will close this issue as @albanD mentions, there's no plan to fix older versions. 
btw I wonder if there is a reason you cannot use a later version of PyTorch?

**Comment by davidfrz** [comment]
> I see, thanks. I will close this issue as @albanD mentions, there's no plan to fix older versions. btw I wonder if there is a reason you cannot use a later version of PyTorch?

lol   cause so many 'old project' in my lab, any they do not support later version of pytorch, emmmm ,acturally, do not support later version of cuda...
