### ISSUE TITLE
Fakeifying a non-leaf subclass where inner tensor is noncontiguous incorrectly produces contiguous tensor.

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#124090]
Minified repro from internal:
```
    def test_dtensor_tensor_is_not_autograd_leaf_but_local_is_noncontiguous(self):

        # Temporarily ignore setUp(), and use rank3 graphs during tracing
        dist.destroy_process_group()
        fake_store = FakeStore()
        dist.init_process_group(
            "fake", store=fake_store, rank=3, world_size=2
        )
        mesh = DeviceMesh(self.device_type, [1, 3])

        x = torch.randn(10, 257, 160, requires_grad=True)
        x_dt = DTensor.from_local(x, mesh, [_Partial()], run_check=False, shape=(10, 257, 160), stride=(41120, 160, 1))
        tmp_dt = x_dt.redistribute(mesh, (Shard(1),))

        from torch._subclasses import FakeTensorMode
        m = FakeTensorMode()
        tmp_dt_fake = m.from_tensor(tmp_dt)
        self.assertEqual(tmp_dt.shape, tmp_dt_fake.shape)
        self.assertEqual(tmp_dt.stride(), tmp_dt_fake.stride())
        self.assertEqual(tmp_dt._local_tensor.shape, tmp_dt_fake._local_tensor.shape)
        # This assert **fails**
        # tmp_dt._local_tensor is not contiguous, but tmp_dt_fake._local_tensor advertises as contiguous
        self.assertEqual(tmp_dt._local_tensor.stride(), tmp_dt_fake._local_tensor.stride())
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @anijain2305 @chauhang

**Comment by bdhirsh** [comment]
hi-pri for internal + potential correctness issue (although internally this manifests as an inductor stride assert.

It looks like we end up with a contiguous tensor because:

(1) Fakeification runs `clone()` when it sees that it needs to produce a non-autograd-leaf [here](https://github.com/pytorch/pytorch/blob/main/torch/_subclasses/meta_utils.py#L1210)
(2) That dispatches a clone() to the subclass's inner tensors, which faithfully clone the inner tensor (which might be arbitrarily strided, and cloning will not replicate the strides)

**Comment by ezyang** [comment]
I am general in favor of adding private APIs to bash properties in, as long as we work out the safety conditions carefully. Arguably, I should have done this when I originally added fakeification, but instead I jumped through a lot of hoops to figure out how to make things work using existing APIs only.

**Comment by ezyang** [comment]
also cc @albanD @soulitzer @jbschlosser

**Comment by albanD** [comment]
I can't think of something that would go horribly wrong if we have a private function  (could be public tbh) like `torch.autograd.graph.forbid_in_autograd(t)` that will change t from being a leaf (t.grad_fn/grad_accumulator == None) to a non-leaf that will error out in backward (t.grad_fn == ErrorNode).

**Comment by bdhirsh** [comment]
Yeah, I think an error node seems reasonably. I can test it out and see if it makes CI unhappy

**Comment by albanD** [comment]
Note that the error node already exists: https://github.com/pytorch/pytorch/blob/5a735ece6b46248b6bb224bae4d0d7df24a335f0/torch/csrc/autograd/functions/basic_ops.h#L15
Your code is really a python binding to c++ code that properly set the grad_fn to make_shared<Error>. You can look for other use of Error
