### ISSUE TITLE
FSDP RuntimeError Output 0 of ViewBackward0 is a view and its base or another view of its base has been modified inplace.

### ISSUE THREAD

**Issue by yuxin212** [pytorch/pytorch#124017]
### 🐛 Describe the bug

When using FSDP to train a transformer model, I encountered the same error mentioned in #79605. But I did not find a solution or workaround for this error. 

### Steps to reproduce the error:
1. Go to [here](https://github.com/yuxin212/ProphetNet-FSDP/tree/master/AR-diffusion-FSDP), run the following command:

```bash
sbatch run_sbatch_train.sh
```

2. The following is the output of the Traceback: 

```python
Traceback (most recent call last):
  File "/home/<username>/ProphetNet-FSDP/AR-diffusion-FSDP/train_utils/trainer_main.py", line 138, in main
    ).run_loop()
      ^^^^^^^^^^
  File "/home/<username>/ProphetNet-FSDP/AR-diffusion-FSDP/train_utils/trainer.py", line 188, in run_loop
    self.forward_backward(batch)
  File "/home/<username>/ProphetNet-FSDP/AR-diffusion-FSDP/train_utils/trainer.py", line 253, in forward_backward
    losses = self.diffusion.training_losses(self.model, batch, t)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<username>/ProphetNet-FSDP/AR-diffusion-FSDP/model_utils/gaussian_diffusion.py", line 269, in training_losses
    return self.training_losses_s2s(model, input_text, t, is_dev=is_dev)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<username>/ProphetNet-FSDP/AR-diffusion-FSDP/model_utils/gaussian_diffusion.py", line 1564, in training_losses_s2s
    x_start_mean = model.module.get_embeds(q_input_ids)  # because of DDP
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<username>/ProphetNet-FSDP/AR-diffusion-FSDP/model_utils/diffusion_lm.py", line 140, in get_embeds
    return self.word_embedding(input_ids) * self.embed_scale
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<username>/test-fsdp/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<username>/test-fsdp/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<username>/test-fsdp/lib/python3.11/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/home/<username>/test-fsdp/lib/python3.11/site-packages/torch/nn/functional.py", line 2237, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Output 0 of ViewBackward0 is a view and its base or another view of its base has been modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
```

3. The model architecture with FSDP wrapping can be found [here](https://gist.github.com/yuxin212/19c0e5cb0802fe515e743a8fde7c1a51)

### Expected Output
No error and run the model. 

### Versions

The `collect_env.py` was run on the login node which does not have GPU. I submit the job to nodes with 2 A100 GPUs. 

Collecting environment information...
PyTorch version: 2.2.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux release 8.9 (Ootpa) (x86_64)
GCC version: (GCC) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              40
On-line CPU(s) list: 0-39
Thread(s) per core:  1
Core(s) per socket:  20
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
Stepping:            4
CPU MHz:             3700.000
CPU max MHz:         3700.0000
CPU min MHz:         1000.0000
BogoMIPS:            4800.00
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            28160K
NUMA node0 CPU(s):   0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38
NUMA node1 CPU(s):   1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.2
[pip3] torchvision==0.17.2
[pip3] triton==2.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.2                    pypi_0    pypi
[conda] torchvision               0.17.2                   pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

**Comment by yuxin212** [comment]
@awgu Thank you for your comment. I am not really sure if they are wrapped in the same FSDP module. You can find the model architecture after FSDP wrapping [here](https://gist.github.com/yuxin212/19c0e5cb0802fe515e743a8fde7c1a51). You can see the whole model is the `_fsdp_wrapped_module`, and transformer layers are also the `_fsdp_wrapped_module` because I used the `transformer_auto_wrap_policy`. 

If this file does not indicate if they are wrapped in the same FSDP module, please let me know how I can find out.

**Comment by awgu** [comment]
I have not had the chance to try to run your script, but if you want to check for shared parameters, you can run this before you wrap with FSDP:
```
param_to_param_name: Dict[nn.Parameter, str] = {}
for param_name, param in model.named_parameters(remove_duplicate=False):
    if param in param_to_param_name:
        print(f"{param_name} is shared with {param_to_param_name[param]}")
    else:
        param_to_param_name[param] = param_name
```

Then, we can visually inspect the wrapping which you provided to know if the shared parameters violate the constraint.

**Comment by awgu** [comment]
Or actually, taking another look, I have another suspicion. The issue might be coming from:
```
model.module.get_embeds(q_input_ids)
```

FSDP only knows to all-gather the parameters when you run the FSDP module's forward. Here, you are wrapping each transformer layer with FSDP plus the root module with FSDP. This should mean that the embedding is assigned to the root FSDP module, so you must run `self.model(...)` (i.e. `self.model.forward`) in order to trigger the all-gather for the `tok_embeddings`.

**Comment by yuxin212** [comment]
The following is the output from the for loop:

```
lm_head.weight is shared with word_embedding.weight
```

I need some time to rewrite part of the code to put `model.module.get_embeds(q_input_ids)` into the forward call to see if getting rid of this can avoid the error.

**Comment by yuxin212** [comment]
Okay. I found a solution. I only wrapped the transformer layers, that is `BertLayer` and `BasicTransformerBlock`, instead of the whole model plus the transformer layers. And the error disappeared! Thank you @awgu for the help!

**Comment by awgu** [comment]
@yuxin212 If you do not wrap the whole model, I think you may not have any overlap of communication/computation 🤔 

In particular, we need a parent module of the transformer layers in order to share data structures across them for overlap 😢 .

**Comment by yuxin212** [comment]
I am curious if I wrap the `ModuleList` level which contains these transformers, will this still be an issue?

**Comment by awgu** [comment]
yes :(

since `ModuleList` does not implement `forward`, we should actually never wrap `ModuleList` with FSDP since then it would never run the all-gather

**Comment by yuxin212** [comment]
Ahh I see. 

Does this issue affect performance or efficiency?

**Comment by yuxin212** [comment]
If I write a `nn.Module` class with a forward call for these transformer layers, and I wrap this class with FSDP, will this still be an issue?

**Comment by yuxin212** [comment]
I found this note:

> Attempting to run the forward pass of a submodule that is contained in an FSDP instance is not supported and will result in errors. This is because the submodule’s parameters will be sharded, but it itself is not an FSDP instance, so its forward pass will not all-gather the full parameters appropriately. This could potentially happen when attempting to run only the encoder of a encoder-decoder model, and the encoder is not wrapped in its own FSDP instance. To resolve this, please wrap the submodule in its own FSDP unit.

Since my model will call `word_embedding` and `lm_head` independently, can I just wrap these two linear layers with FSDP within the whole wrapped model?

**Comment by awgu** [comment]
> Does this issue affect performance or efficiency?

Wrapping `nn.ModuleList` affects correctness :/
Since parameters are not all-gathered, you would see an error (probably a shape mismatch).

> If I write a nn.Module class with a forward call for these transformer layers, and I wrap this class with FSDP, will this avoid the not all-gather issue?

I think so.

> Since my model will call word_embedding and lm_head independently, can I just wrap these two linear layers with FSDP within the whole wrapped model?

As long as if you wrap a module with FSDP, that module is used via running its `forward`, then you should be fine!

**Comment by yuxin212** [comment]
Thank you so much! I will close this issue for now

**Comment by AArchLichKing** [comment]
> Okay. I found a solution. I only wrapped the transformer layers, that is `BertLayer` and `BasicTransformerBlock`, instead of the whole model plus the transformer layers. And the error disappeared! Thank you [@awgu](https://github.com/awgu) for the help!

Hi Yuxin, I met exactly the same bug as yours. I have tried to add BertModel to the _transformer_wrap_cls_, but this bug is still there. In code, the embedding and lm_head are out side of the BasicTransformerBlock. And the class for the model is PretrainedModel. Could you please provide some suggestions on these? How did you wrap the entire model? 

Thank you very much in advance!

**Comment by yuxin212** [comment]
@AArchLichKing If you are using huggingface's trainer class, I would suggest you to enable fsdp in the trainingarguments.
