### ISSUE TITLE
[Profiler] NCCL collectives text garbled and times reported in ns

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#124102]
After rebasing to today's (4/15) `viable/strict`, profiler traces are showing some overlapping garbled text on the NCCL collective, and the collective time is now reported in nanoseconds (previously should have been milliseconds). Was there some kind of regression?

Example:
<img width="1019" alt="Screenshot 2024-04-15 at 4 31 49 PM" src="https://github.com/pytorch/pytorch/assets/31054793/ff141a2c-60ea-4fdd-9b9a-09a5fe857ac9">

Version: main

cc @robieta @chaekit @aaronenyeshi @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise

**Comment by sraikund16** [comment]
@awgu did you use `dyno gputrace` to collect these logs? A patch was put in yesterday to fix this: https://github.com/pytorch/pytorch/pull/124080

**Comment by sraikund16** [comment]
It is possible that this issue is related to https://github.com/pytorch/kineto/issues/887

**Comment by awgu** [comment]
Even after rebasing, I am still seeing both garbled text in the profile and the collective timing in ns.

**Comment by aaronenyeshi** [comment]
> Even after rebasing, I am still seeing both garbled text in the profile and the collective timing in ns.

@awgu , sorry can you please cherry-pick https://github.com/pytorch/pytorch/pull/124737, it should contain the fix in recent kineto submodule update.
