### ISSUE TITLE
Check for negative values in BCECriterion

### ISSUE THREAD

**Issue by seangal** [pytorch/pytorch#1241]
I have noticed that in [THNN/BCECriterion.c](https://github.com/pytorch/pytorch/blob/master/torch/lib/THNN/generic/BCECriterion.c#L21) there is no assert for negative values, resulting in possible NaN loss and gradients.
I think it will be easier for developers to see their program crash (or catch the exception) with a message indicating that their values are negative instead of searching for the problem of their NaN loss.

**Comment by alykhantejani** [comment]
@soumith I think this can be closed as was fixed in https://github.com/pytorch/pytorch/commit/662faf7c413b8d393c2f096d1071360e0900b227#diff-c3b8bdc7f8e44ecbcbf14e7bd59957d8
