### ISSUE TITLE
Coordinate descent tuning on large tensors(?) results in illegal memory access

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#124251]
### 🐛 Describe the bug

```
import torch
from torch import nn
import torch.nn.functional as F
import torch._inductor.config as config
config.coordinate_descent_tuning = True

def bench(f, name=None, iters=1000, warmup=5, display=True, profile=False):
    import time
    from triton.testing import do_bench

    for _ in range(warmup):
        f()
    if profile:
        with torch.profiler.profile() as prof:
            f()
        prof.export_chrome_trace(f"{name if name is not None else 'trace'}.json")

    us_per_iter = do_bench(lambda: f())*1000

    if name is None:
        res = us_per_iter
    else:
        res= f"{name}: {us_per_iter:.3f}us"

    if display:
        print(res)
    return res

def count_bandwidth(f, inp):
    out = f()
    mem_bytes = inp.numel() * inp.dtype.itemsize + out.numel() * out.dtype.itemsize
    us = bench(f, display=False)
    print((1e6/us) * mem_bytes / 1e9)

with torch.no_grad():
    for D in range(8192, 8192*11+1, 8192): #256
        inp = torch.randn(2048*32, D, dtype=torch.bfloat16, device='cuda')
        mod = nn.LayerNorm([D], dtype=torch.bfloat16, device='cuda')

        print(D)
        count_bandwidth(lambda: mod(inp), inp)

        torch._dynamo.reset()
        comp_mod = torch.compile(mod, dynamic=False)
        count_bandwidth(lambda: comp_mod(inp), inp)

        torch._dynamo.reset()
        comp_mod = torch.compile(mod, dynamic=False)
        count_bandwidth(lambda: comp_mod(inp), inp)
```

When run, this non-deterministically results in a `RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered` for me

cc: @shunting314 

### Versions

N/A

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by shunting314** [comment]
yea, reproed

**Comment by shunting314** [comment]
Ok, I added some temporarily code in inductor to force 
```
{"XBLOCK": 1, "RBLOCK": 16384}, num_stages=1, num_warps=32
```
for a single kernel: https://gist.github.com/shunting314/703299c162aa99d8616f9cbb9d0dc481 

It can repro the issue. Should be a triton issue.

I'll try to come up a even simpler repro that does not goes thru autotuner.

**Comment by shunting314** [comment]
Here it is: https://gist.github.com/shunting314/c0c0a78d86df1a1f86609d5f107f20d7 

@htyu  @manman-ren This triton kernel fail with illegal memory access error. Reducing RBLOCK (e.g. halve it) make it pass. Wondering if it triggers any bug in triton

**Comment by htyu** [comment]
I can take it look.

**Comment by shunting314** [comment]
I simplified the LayerNorm kernel to a basically a copy kernel: https://gist.github.com/shunting314/4afcf8e3adb21d300328ea8389808a08 


The issue can still be reproed. Taking a further looks, I think we miss a rmask here. This is probably an inductor codegen issue.

**Comment by shunting314** [comment]
Or more specifically, it's a coordinate descent tuner issue, since codegen assume there is a max RBLOCK and don't emit rmask if rnumel is multiple of this max RBLOCK. But CDT breaks that assumption. I'll come up with a PR to fix. 

@htyu  false alarm :)
