### ISSUE TITLE
[feature request] Add option for only computing the singular values of a matrix

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#12420]
## 🚀 Feature
I would like to propose the addition of an option to the current SVD implementation analogous to `compute_uv` in NumPy's SVD which will compute the singular values of a the matrix only.

## Pitch

```python
>>> torch.svd(a, compute_uv=False)
<tensor containing singular values>
>>> torch.svd(a, compute_uv=True)
<3-tuple standard output>
```

Methods that depend only on singular values such as `matrix_rank` and `nuclear_norm` will benefit from this addition.

**Comment by vishwakftw** [comment]
I'll take this up.

**Comment by zou3519** [comment]
@vishwakftw what you have now should be fine. I left a comment there
