### ISSUE TITLE
MPS backend incorrect tensor slicing results 

### ISSUE THREAD

**Issue by TimFelixBeyer** [pytorch/pytorch#124206]
### 🐛 Describe the bug

When using MPS, setting non-max values to zero as is commonly done in top-k sampling doesn't work correctly.
(The top-k operation is not strictly necessary, just indexing with an mps tensor results in the same behavior).

```python
import torch

t = torch.rand((1, 2,))
print(t)
v, _ = torch.topk(t, 1)
t[t < v[:, [-1]]] = -float('Inf')
print(t)  # the lower logit is correctly set to -inf

t = torch.rand((1, 2,)).to('mps')
print(t)
v, _ = torch.topk(t, 1)
t[t < v[:, [-1]]] = -float('Inf')
print(t)  # the lower logit has been replaced with the value of `v` instead
```

### Versions

Collecting environment information...
PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-quotes==3.3.2
[pip3] mypy==1.5.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.8
[pip3] torch==2.2.2
[pip3] torchmetrics==1.1.1
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-lightning         2.0.8                    pypi_0    pypi
[conda] torch                     2.2.2                    pypi_0    pypi
[conda] torchmetrics              1.1.1                    pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by DenisVieriu97** [comment]
@TimFelixBeyer I am not able to reproduce this issue. In your test I see that the tensor passed in to CPU and MPS are different, so this could be a point of failure (input data is different). 
 I've attached below a test if you could please let me know if this passes or fails for you:

```
import torch

for _ in range(1000):
    t = torch.rand((1, 2,))
    t_mps = t.detach().clone().to("mps")

    v, _ = torch.topk(t, 1)
    v_mps, _ = torch.topk(t_mps, 1)

    t[t < v[:, [-1]]] = -float('Inf')
    t_mps[t_mps < v_mps[:, [-1]]] = -float('Inf')

    torch.testing.assert_close(t, t_mps.cpu())

print("Verified successfully")
```

If you are using your test, please use the same input for both CPU and MPS so we can compare:
```
import torch

t = torch.rand((1, 2,))
t_mps = t.detach().clone()
print(t)
v, _ = torch.topk(t, 1)
t[t < v[:, [-1]]] = -float('Inf')
print(t)  # the lower logit is correctly set to -inf

t = t_mps
print(t)
v, _ = torch.topk(t, 1)
t[t < v[:, [-1]]] = -float('Inf')
print(t)  # the lower logit has been replaced with the value of `v` instead
```

**Comment by TimFelixBeyer** [comment]
I tried your snipped and it fails on my M2 Pro MBP:


```python3
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    torch.testing.assert_close(t, t_mps.cpu())
  File "/Users/tim/miniconda3/envs/thesis/lib/python3.11/site-packages/torch/testing/_comparison.py", line 1520, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 2 (50.0%)
Greatest absolute difference: inf at index (0, 0) (up to 1e-05 allowed)
Greatest relative difference: inf at index (0, 0) (up to 1.3e-06 allowed)
```

**Comment by DenisVieriu97** [comment]
Thanks @TimFelixBeyer for trying the updated script!
I've noticed the difference on my system, I am running with latest torch nightly (`torch 2.4.0.dev20240410`). With torch 2.2.2 I am seeing the issue as well. Could you please try latest torch nightly and let me know if you still see this issue?
```
 pip3 install --upgrade --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
```

**Comment by TimFelixBeyer** [comment]
It seems to work correctly on the newest nightly (torch-2.4.0.dev20240419), thank you!
