### ISSUE TITLE
the derivative for 'pow' is not implemented

### ISSUE THREAD

**Issue by DriesSmit** [pytorch/pytorch#12426]
## 🚀 Feature
When I try to use autograd through the torch.pow function, I get the following error: RuntimeError: the derivative for pow is not implemented. I am using 'e' as the base of the power. 

Would It be possible to implement this functionality for 'e' or maybe direct me to an existing way to do this for the special case when the base is the natural number 'e'? I am using pow to implement my own version of the logsumexp function so that I don't need to create a 3D matrix first and then use the current torch.logsumexp function to collapse it back to a 2D matrix.

Thank you.

**Comment by DriesSmit** [comment]
I see that torch.exp solves this problem. Thank you.

**Comment by fmassa** [comment]
Could you show what is the snippet that is giving you this error? To the best of my knowledge, `torch.pow` should be differentiable.

**Comment by DriesSmit** [comment]
The line looks as follows: torch.pow(np.e, log_data). Using torch.exp fixed the problem.
I got the following message when using torch.pow:

Traceback (most recent call last):
  File "/../TestPyTorch.py", line 135, in <module>
    loss.backward()
  File "/home/dries/.local/lib/python3.5/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/dries/.local/lib/python3.5/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: the derivative for pow is not implemented

**Comment by fmassa** [comment]
Thanks for the report.

This is weird. If we do
```python
np.e ** log_data
```
it works fine for backpropagation, but not with `torch.pow`.

Indeed, internally the `**` points to `torch._C._TensorBase.pow`, while `torch.pow` points to `_VariableFunctions.pow`, and it looks like the `torch.pow` version is missing something.

This is something that should be fixed. I'm reopening the issue.

**Comment by t-vi** [comment]
Interestingly, this only happens for a non-tensor base.

**Comment by DriesSmit** [comment]
Thank you.

**Comment by t-vi** [comment]
So for non-tensor base, it falls back to the TH/THC-originated function pow (which is there as `pow` in addition to the native `pow`). That doesn't have a derivative. I'll try just adding the derivative first.
