### ISSUE TITLE
macOS 10.13 got error "Found no NVIDIA driver" when testing torch.cuda.current_device()

### ISSUE THREAD

**Issue by LeoZDong** [pytorch/pytorch#12438]
I am using on mid-2014 MacBook Pro model with NVIDIA GeForce 750M (dual GPU with Intel Iris Pro as well). After successfully installing pytorch with CUDA from source, I cannot get pytorch to recognize my GPU... Here is the complete error message: 

`torch.cuda.current_device()
Traceback (most recent call last):

  File "<ipython-input-9-3380d2c12118>", line 1, in <module>
    torch.cuda.current_device()

  File "/Users/Leo/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 341, in current_device
    _lazy_init()

  File "/Users/Leo/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    _check_driver()

  File "/Users/Leo/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx`

I tried to go on http://www.nvidia.com/Download/index.aspx but it does not have a driver for Mac (I think Mac installs GPU drivers automatically). I checked the CUDA panel and I have the CUDA driver 410.130 and the GPU driver 355.11.10.10.40.102, both of which are the latest.

![image](https://user-images.githubusercontent.com/22690720/46585238-3d4b6580-ca3c-11e8-8523-f5eb4e4ff97f.png)

Does this have anything to do with the fact that my computer has two graphics cards? Thank you in advance for the help!!

**Comment by zou3519** [comment]
What does `torch.cuda.is_available()` say?

**Comment by LeoAppleseed** [comment]
It says False...

**Comment by LeoAppleseed** [comment]
> What does `torch.cuda.is_available()` say?
It says False

**Comment by LeoAppleseed** [comment]
> What does `torch.cuda.is_available()` say?

It says False.

**Comment by LeoAppleseed** [comment]
If I do `torch.cuda.device(0)` it does return something like `<torch.cuda.device at 0x18d769320>`

I don't know if that means anything useful at all.

**Comment by LeoZDong** [comment]
Issue haven't resolved yet... Any comments?

**Comment by soumith** [comment]
@LeoZDong PyTorch tries to start CUDA library, and CUDA library fails with this error. It's unclear why this happens on Mac (on Linux I have some more visibility).
Do you have any luck running the examples that come with CUDA (when you installed it)?

**Comment by stan3** [comment]
355.11.10.10.40.102 looks like drivers that came with MacOS.  You'll need newer ones from Nvidia, e.g. as listed on http://www.macvidcards.com/drivers.html.

**Comment by ngimel** [comment]
Closing due to age
