### ISSUE TITLE
Dropout isn't working with fp16 on 1.0.0.dev20181006

### ISSUE THREAD

**Issue by RicCu** [pytorch/pytorch#12431]
## 🐛 Bug

Using dropout with either cpu or cuda HalfTensor throws an error:

RuntimeError: bernoulli_ is not implemented for type torch.HalfTensor

or 

RuntimeError: "bernoulli_scalar_cuda_" not implemented for 'torch.cuda.HalfTensor'

This wasn't the case for version 0.4.1

## To Reproduce

1. Apply dropout (1d, 2d, 3d) on a fp16 input, either cpu or cuda.

```
x = torch.ones(1, 1, 3, 3).half()

print(F.dropout2d(x)) # Works on v0.4.1
print(F.dropout2d(x.cuda())) # Works on v0.4.1
```

## Expected behavior

The code above works on PyTorch version 0.4.1, but it fails on version 1.0.0.dev20181006 with the error:
RuntimeError: bernoulli_ is not implemented for type torch.HalfTensor
RuntimeError: "bernoulli_scalar_cuda_" not implemented for 'torch.cuda.HalfTensor'
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.0.0.dev20181006                                                                   
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 410.48
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/lib64/libcudnn.so
/usr/local/cuda-10.0/lib64/libcudnn.so.7
/usr/local/cuda-10.0/lib64/libcudnn.so.7.3.1
/usr/local/cuda-10.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch-ignite            0.1.0                     <pip>
[conda] pytorch-nightly           1.0.0.dev20181006 py3.7_cuda9.2.148_cudnn7.1.4_0  [cuda92]  pytorch
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

## Additional context

I found this bug after using PyTorch 1.0-rc1 with a script using the FP16 optimizer from [Apex](https://github.com/NVIDIA/apex). The script works fine if I revert back to 0.4.1.

**Comment by vishwakftw** [comment]
cc: @SsnL who ported Bernoulli sampling to ATen.

**Comment by ankitvb** [comment]
We're also seeing this same error on Volta with PyTorch1.0
