### ISSUE TITLE
torch.compile: could not reconstruct view by re-applying a ViewMeta sequence

### ISSUE THREAD

**Issue by Xia-Weiwen** [pytorch/pytorch#124382]
### 🐛 Describe the bug

I got the following error when running a `torch.compile`'ed function:
`W0418 04:04:09.562000 140622378160704 torch/_functorch/_aot_autograd/functional_utils.py:240] [__aot_joint_graph] could not reconstruct view by re-applying a ViewMeta sequence. This error is possibly caused by dynamic shapes. Fallbacking to reconstruction using as_strided. Error message: /home/weiwen/pytorch-fork/build/aten/src/ATen/RegisterCPU.cpp:13111: SymIntArrayRef expected to contain only concrete integers`

This is a regression. This error is caused by commit https://github.com/pytorch/pytorch/commit/e4c887fbf6fcc9b1864d10b3ab18294e5edebdfc. Before this commit, there is no error messages. With such errors, the program is still able to run but becomes much slower than before. In the real case, the program runs 7x slower than before.

Expected behavior: No error messages and it has the same behavior as before this commit.

Reproducer:
```python
import torch


@torch.compile(dynamic=True)
def func(A: torch.Tensor, threshold=0.0):
    cols = A.shape[-1]
    if len(A.shape) == 3:
        rows = A.shape[0] * A.shape[1]
    else:
        assert A.dim() == 2, f"Input tensor should be 2d or 3d but got {A.dim()}d"
        rows = A.shape[0]
    A = A.reshape(rows, cols)

    if threshold == 0.0:
        outlier_indices = None
        outlier_coord = None
        outlier_rows = None
        outlier_cols = None
        outlier_values = None
    else:
        outlier_indices = torch.abs(A) >= threshold
        outlier_coord = outlier_indices.nonzero()
        outlier_rows = outlier_coord[:, 0]
        outlier_cols = outlier_coord[:, 1]
        outlier_values = A[outlier_indices]

    return outlier_indices, outlier_coord, outlier_rows, outlier_cols, outlier_values


print('1')
A = torch.randn(2048, 2048) * 3
func(A)
print('2')
A = torch.randn(8192, 2048) * 3
func(A)
print('3')
A = torch.randn(2048, 8192) * 3
func(A)

print('4')
A = torch.randn(2048, 2048) * 3
func(A, threshold=3)
print('5')
A = torch.randn(8192, 2048) * 3
func(A, threshold=3)
print('6')
A = torch.randn(2048, 8192) * 3
func(A, threshold=3)

for i in range(10):
    print('run', i)
    bs = pow(2, i)
    A = torch.randn(bs, 2, 2048) * 3
    func(A, threshold=3)
print('ok')
```
Please note that this producer is a simplified version of the real case.

### Versions

PyTorch version: 2.4.0a0+git236b0d1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (conda-forge gcc 12.3.0-3) 12.3.0
Clang version: Could not collect
CMake version: version 3.28.1
Libc version: glibc-2.28

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.16.0-x86_64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              240
On-line CPU(s) list: 0-239
Thread(s) per core:  2
Core(s) per socket:  60
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               143
Model name:          Intel(R) Xeon(R) Platinum 8490H
Stepping:            8
CPU MHz:             1900.000
CPU max MHz:         3500.0000
CPU min MHz:         800.0000
BogoMIPS:            3800.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            2048K
L3 cache:            115200K
NUMA node0 CPU(s):   0-59,120-179
NUMA node1 CPU(s):   60-119,180-239
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr avx512_fp16 amx_tile flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==3.8.2
[pip3] flake8-bugbear==20.1.4
[pip3] flake8-coding==1.3.3
[pip3] flake8-comprehensions==3.3.0
[pip3] flake8-executable==2.0.4
[pip3] flake8-pyi==20.5.0
[pip3] lion-pytorch==0.1.4
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.2
[pip3] optree==0.10.0
[pip3] torch==2.4.0a0+gite4c887f
[pip3] torchao==0.1
[pip3] triton==2.3.0
[conda] lion-pytorch              0.1.4                    pypi_0    pypi
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-include               2023.2.0                 pypi_0    pypi
[conda] mkl-static                2023.2.0                 pypi_0    pypi
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] optree                    0.10.0                   pypi_0    pypi
[conda] torch                     2.4.0a0+gite4c887f           dev_0    <develop>
[conda] torchao                   0.1                       dev_0    <develop>
[conda] triton                    2.3.0                    pypi_0    pypi

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by Xia-Weiwen** [comment]
CC @jiqing-feng

**Comment by ysiraichi** [comment]
That's just a warning. You should be able to run even with that warning. The exception being raised does cause some runtime overhead, but it shouldn't be much slower. How slower does it get? What does the runtime looks like?

As far as I can see, you are not doing anything computation-heavy, so that may be the reason you are observing runtime difference.

**Comment by Xia-Weiwen** [comment]
The producer is a simplified version of the real case, just to trigger the error. In the real case, the function does computation. This function is called thousands of times when running the real case. The error message is printed to console every time this function is called. The program runs 7x slower than before. And it becomes even slower with larger scale of models and data.

**Comment by ysiraichi** [comment]
Could you try running with 435db051d08c8a358ce43cc05670ac552e3d40c3 and e4c887fbf6fcc9b1864d10b3ab18294e5edebdfc, and report their running times? @bdhirsh Maybe we can bail out before actually trying to apply the `ViewMeta` sequence by checking whether we are running on dynamic shapes. What do you think?

**Comment by ysiraichi** [comment]
Apparently this also affected some models perf internally. Fix: https://github.com/pytorch/pytorch/pull/124488

**Comment by bdhirsh** [comment]
Yep the warn was too noisy (fix linked above)
