### ISSUE TITLE
mypy.ini isn't valid

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#124341]
running `mypy` gives `mypy: can't read file 'test/test_type_info.py`

Upon further investigation, mypy.ini seems malformed, we're missing commas: https://github.com/pytorch/pytorch/blob/64f6ddf12c11738c3f4b1ed01cf4f699541496bf/mypy.ini#L41-L42

fixing this leads to some more issues.

Could this be related to https://github.com/pytorch/pytorch/issues/123465?

cc @ezyang @malfet @xuzhao9 @gramster @ZainRizvi @kit1980 @huydhn @clee2000

**Comment by ezyang** [comment]
One thing to note is that we don't run mypy directly anymore, we only use dmypy, and there are some differences which are material.

**Comment by DeinAlptraum** [comment]
Closed via #133097
