### ISSUE TITLE
/tools/setup_helpers/cudnn.py rejects valid CUDNN_LIB_DIR if libcudnn is symlink

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#12437]
## 🐛 Bug

On my mac, _setup.py_ manages to find the CUDNN library and dir on its own,
but then rejects the locations because of some logic added in January: [#4597](https://github.com/pytorch/pytorch/pull/4597)

`        real_cudnn_library = os.path.realpath(CUDNN_LIBRARY)`
`       real_cudnn_lib_dir = os.path.realpath(CUDNN_LIB_DIR)`
`       assert os.path.dirname(real_cudnn_library) == real_cudnn_lib_dir, (`
`          'cudnn library and lib_dir must agree')`

The located dir is a real path, with a symlink for the library itself:
_/usr/local/cuda/lib
/usr/local/cuda/lib/libcudnn.7.dylib@ -> /Developer/NVIDIA/CUDA-9.2/lib/libcudnn.7.dylib_

comparing real paths of dir and library don't match up.
it's easy to work around by setting CUDNN.. vars before running setup,
but maybe could safely add an additional or clause on the assert to allow for a situation like the above.

something like:
`os.path.dirname(CUDNN_LIBRARY) == os.path.normpath(CUDNN_LIB_DIR)`
or if real paths are the way to go:
`real_cudnn_library == 
 os.path.realpath(os.path.join(CUDNN_LIB_DIR,os.path.basename(CUDNN_LIBRARY)))`

cc @malfet @seemethere @walterddr @csarofeen @ptrblck @xwang233

**Comment by malfet** [comment]
Logic to detect CUDNN location has long been moved from setup_helpers to standard `FindLibrary` CMake routines, which handle symlinks fine. Closing, but please do not hesitate to file a new one if issue still manifests in latest pytorch
