### ISSUE TITLE
Verbose log: [__aot_joint_graph] could not reconstruct view by re-applying a ViewMeta sequence. 

### ISSUE THREAD

**Issue by fegin** [pytorch/pytorch#124499]
### 🐛 Describe the bug

When running an internal MNIST_AUTOENCODER_TNT example model, we see this log every step. While this does not seem to affect the correctness and performance, this log is confusing and should not be a warning if it does not cause issues.

### Error logs

[rank0]:W0418 14:15:21.825000 140208555134976 torch/_functorch/_aot_autograd/functional_utils.py:240] [__aot_joint_graph] could not reconstruct view by re-applying a ViewMeta sequence. This error is possibly caused by dynamic shapes. Fallbacking to reconstruction using as_strided. Error message: buck-out/v2/gen/fbcode/3ce39ffdd8faa9f1/caffe2/__gen_aten__/out/RegisterCUDA.cpp:17303: SymIntArrayRef expected to contain only concrete integers

### Versions

nightly

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by bdhirsh** [comment]
This was added by the recent view-replay changes in https://github.com/pytorch/pytorch/pull/121007

Changing it to info as part of this forward fix: https://github.com/pytorch/pytorch/pull/124488

**Comment by bhack** [comment]
@bdhirsh Can you connect also this ticket to the PR so that it will be closed?
