### ISSUE TITLE
(libtorch) Schema not found for node aten::expand

### ISSUE THREAD

**Issue by neggert** [pytorch/pytorch#12445]
## 🐛 Bug

I'm just getting started with libtorch, but the few models from torchvision I'm trying to run are throwing an exception. Even following the instructions at https://pytorch.org/tutorials/advanced/cpp_export.html gives the exception.

```
libc++abi.dylib: terminating with uncaught exception of type torch::jit::script::ErrorReport:
Schema not found for node. File a bug report.
Node: %709 : Dynamic = aten::expand(%122, %707, %708)

Input types:Float(*), int[], int
candidates were:
  aten::expand(Tensor self, int[] size, *, bool implicit=<default>) -> Tensor
.

[1]    21624 abort      ./example-app ../model.pt
```

## To Reproduce

1. Follow the instructions at https://pytorch.org/tutorials/advanced/cpp_export.html
1. Run the compiled program on the traced torchvision resnet18 or alexnet model (haven't tested other models)

## Expected behavior

The program doesn't throw any exceptions

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.0.dev20180929
 - OS (e.g., Linux): Mac OSX 10.13.6
 - How you installed PyTorch (`conda`, `pip`, source): conda / downloaded and extracted libtorch zip.
 - Python version: 3.7
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: CMake 3.12.2
```
$ clang -v
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by atulkum** [comment]
+1

**Comment by YunYang1994** [comment]
+1

**Comment by zdevito** [comment]
We think this issue is occuring because the version of PyTorch installed to generate the model is not the same as the version of `libtorch.so` being used to run it. Can you try downing a new nightly pytorch (`conda install pytorch-nightly -c pytorch`) and the same nightly's libtorch.s? (https://download.pytorch.org/libtorch/nightly/cpu/libtorch-macos-latest.zip). 

When we release the stable version of 1.0 we will be adding version checks for models to make the errors more understandable. But the preview release doesn't do this.

**Comment by atulkum** [comment]
```conda install pytorch-nightly -c pytorch``` fix the problem for me.

**Comment by YunYang1994** [comment]
@neggert hi, how did you sovle it?

**Comment by neggert** [comment]
@YunYang1994 You need to make sure the pytorch nightly you use to export the model is the same as the the libtorch you're building against. This is complicated by the fact that the name of the pytorch nightly in conda has changed from `pytorch-nightly` to `pytorch-nightly-cpu`, so installing `pytorch-nightly` gets you an old version.

So in summary: on the same day, do `conda install pytorch-nightly-cpu -c pytorch` and download libtorch from https://download.pytorch.org/libtorch/nightly/cpu/libtorch-macos-latest.zip

**Comment by YunYang1994** [comment]
@neggert  Thank you, I've run it on the Linux system, downloading libtorch from 
 https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip

**Comment by zdevito** [comment]
Looks like this has been fixed, closing.
