### ISSUE TITLE
Request for Implementation of 'aten::isin.Tensor_Tensor_out' Operation on MPS Device

### ISSUE THREAD

**Issue by prempacematic** [pytorch/pytorch#124518]
### 🐛 Describe the bug

Description:

I encountered an issue while running a script on my Apple Mac using PyTorch, where the operation 'aten::isin.Tensor_Tensor_out' is not currently implemented for the MPS (Managed Private Server) device. This results in a NotImplementedError, causing the script to fail.

Issue Impact:

Error Description: The error message indicates that the operation 'aten::isin.Tensor_Tensor_out' is not supported on the MPS device.
Impact: This issue prevents users from utilizing the MPS device efficiently, especially on Apple Mac systems, where MPS is commonly used for GPU resource management.
Performance Impact: Users are forced to fallback to using the CPU, resulting in slower performance and increased computational overhead.
Request:

I kindly request the implementation of the 'aten::isin.Tensor_Tensor_out' operation for the MPS device in PyTorch. By adding support for this operation on MPS, users can benefit from improved performance and efficiency, particularly on Apple Mac systems.

Temporary Workaround:

As a temporary workaround, users can set the environment variable PYTORCH_ENABLE_MPS_FALLBACK=1 to use the CPU as a fallback for the unsupported operation. However, this solution may lead to decreased performance and is not ideal for long-term usage.

Additional Information:

Environment: Apple Mac system
PyTorch Version: 2.2.2
Reproducibility: The issue can be reproduced consistently on Apple Mac systems.
Thank you for considering this request. If further information or clarification is needed, please let me know.

### Versions

Collecting environment information...
PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1 (arm64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.29.2
Libc version: N/A

Python version: 3.11.7 (main, Dec 15 2023, 12:09:56) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy==1.8.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] numpydoc==1.5.0
[pip3] torch==2.2.2
[pip3] torchvision==0.17.2
[conda] numpy                     1.26.4          py311he598dae_0  
[conda] numpy-base                1.26.4          py311hfbfe69c_0  
[conda] numpydoc                  1.5.0           py311hca03da5_0  
[conda] pytorch                   2.2.2                  py3.11_0    pytorch
[conda] torch                     2.2.2                    pypi_0    pypi
[conda] torchvision               0.17.2                py311_cpu    pytorch

cc @ezyang @gchanan @zou3519 @kadeng @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by prempacematic** [comment]
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[15], line 1
----> 1 print(get_response(prompt))

Cell In[13], line 3, in get_response(prompt)
      1 def get_response(prompt):
----> 3   sequences = pipeline(prompt,
      4       do_sample=True,
      5       return_full_text=False,
      6       top_k=10,
      7       num_return_sequences=1,
      8       eos_token_id=tokenizer.eos_token_id,
      9       max_length=1000,
     10       truncation=True,
     11   )
     13   return sequences[0]['generated_text']

File /opt/anaconda3/lib/python3.11/site-packages/transformers/pipelines/text_generation.py:240, in TextGenerationPipeline.__call__(self, text_inputs, **kwargs)
    238         return super().__call__(chats, **kwargs)
    239 else:
--> 240     return super().__call__(text_inputs, **kwargs)

File /opt/anaconda3/lib/python3.11/site-packages/transformers/pipelines/base.py:1242, in Pipeline.__call__(self, inputs, num_workers, batch_size, *args, **kwargs)
   1234     return next(
   1235         iter(
   1236             self.get_iterator(
   (...)
   1239         )
   1240     )
   1241 else:
-> 1242     return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)

File /opt/anaconda3/lib/python3.11/site-packages/transformers/pipelines/base.py:1249, in Pipeline.run_single(self, inputs, preprocess_params, forward_params, postprocess_params)
   1247 def run_single(self, inputs, preprocess_params, forward_params, postprocess_params):
   1248     model_inputs = self.preprocess(inputs, **preprocess_params)
-> 1249     model_outputs = self.forward(model_inputs, **forward_params)
   1250     outputs = self.postprocess(model_outputs, **postprocess_params)
   1251     return outputs

File /opt/anaconda3/lib/python3.11/site-packages/transformers/pipelines/base.py:1149, in Pipeline.forward(self, model_inputs, **forward_params)
   1147     with inference_context():
   1148         model_inputs = self._ensure_tensor_on_device(model_inputs, device=self.device)
-> 1149         model_outputs = self._forward(model_inputs, **forward_params)
   1150         model_outputs = self._ensure_tensor_on_device(model_outputs, device=torch.device("cpu"))
   1151 else:

File /opt/anaconda3/lib/python3.11/site-packages/transformers/pipelines/text_generation.py:327, in TextGenerationPipeline._forward(self, model_inputs, **generate_kwargs)
    324         generate_kwargs["min_length"] += prefix_length
    326 # BS x SL
--> 327 generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
    328 out_b = generated_sequence.shape[0]
    329 if self.framework == "pt":

File /opt/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File /opt/anaconda3/lib/python3.11/site-packages/transformers/generation/utils.py:1622, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
   1614     input_ids, model_kwargs = self._expand_inputs_for_generation(
   1615         input_ids=input_ids,
   1616         expand_size=generation_config.num_return_sequences,
   1617         is_encoder_decoder=self.config.is_encoder_decoder,
   1618         **model_kwargs,
   1619     )
   1621     # 13. run sample
-> 1622     result = self._sample(
   1623         input_ids,
   1624         logits_processor=prepared_logits_processor,
   1625         logits_warper=logits_warper,
   1626         stopping_criteria=prepared_stopping_criteria,
   1627         pad_token_id=generation_config.pad_token_id,
   1628         output_scores=generation_config.output_scores,
   1629         output_logits=generation_config.output_logits,
   1630         return_dict_in_generate=generation_config.return_dict_in_generate,
   1631         synced_gpus=synced_gpus,
   1632         streamer=streamer,
   1633         **model_kwargs,
   1634     )
   1636 elif generation_mode == GenerationMode.BEAM_SEARCH:
   1637     # 11. prepare beam search scorer
   1638     beam_scorer = BeamSearchScorer(
   1639         batch_size=batch_size,
   1640         num_beams=generation_config.num_beams,
   (...)
   1645         max_length=generation_config.max_length,
   1646     )

File /opt/anaconda3/lib/python3.11/site-packages/transformers/generation/utils.py:2847, in GenerationMixin._sample(self, input_ids, logits_processor, stopping_criteria, logits_warper, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, output_logits, return_dict_in_generate, synced_gpus, streamer, **model_kwargs)
   2840         streamer.put(next_tokens.cpu())
   2841     model_kwargs = self._update_model_kwargs_for_generation(
   2842         outputs,
   2843         model_kwargs,
   2844         is_encoder_decoder=self.config.is_encoder_decoder,
   2845     )
-> 2847     unfinished_sequences = unfinished_sequences & ~stopping_criteria(input_ids, scores)
   2848     this_peer_finished = unfinished_sequences.max() == 0
   2850 if streamer is not None:

File /opt/anaconda3/lib/python3.11/site-packages/transformers/generation/stopping_criteria.py:158, in StoppingCriteriaList.__call__(self, input_ids, scores, **kwargs)
    156 is_done = torch.full((input_ids.shape[0],), False, device=input_ids.device)
    157 for criteria in self:
--> 158     is_done = is_done | criteria(input_ids, scores, **kwargs)
    159 return is_done

File /opt/anaconda3/lib/python3.11/site-packages/transformers/generation/stopping_criteria.py:149, in EosTokenCriteria.__call__(self, input_ids, scores, **kwargs)
    147 @add_start_docstrings(STOPPING_CRITERIA_INPUTS_DOCSTRING)
    148 def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, **kwargs) -> torch.BoolTensor:
--> 149     is_done = torch.isin(input_ids[:, -1], self.eos_token_id.to(input_ids.device))
    150     return is_done

NotImplementedError: The operator 'aten::isin.Tensor_Tensor_out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.  this issue occured 

i am running below code 

def get_response(prompt):

  sequences = pipeline(prompt,
      do_sample=True,
      return_full_text=False,
      top_k=10,
      num_return_sequences=1,
      eos_token_id=tokenizer.eos_token_id,
      max_length=1000,
      truncation=True,
  )

  return sequences[0]['generated_text']

prompt = '''

<s>[INST] <<SYS>>
You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.
Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content.
Please ensure that your responses are socially unbiased and positive in nature.
If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct.
If you don't know the answer to a question, please don't share false information.
<</SYS>>
I liked friends and money heist. Recommend me the similar shows to watch.
[/INST]
'''

while printing the response print(get_response(prompt)) error showing.

**Comment by datancoffee** [comment]
Get the same issue when trying to run LLAMA-3 locally on my Mac.
Had to do export PYTORCH_ENABLE_MPS_FALLBACK=1 and it solved the problem, but would be nice to fix the issue

**Comment by xxxAleksandrxxx** [comment]
Got the same on Mac M1

**Comment by agnosticlines** [comment]
Yeah, one of the latest transformers commits uses `isin` which isn't supported by the backend: https://github.com/huggingface/transformers/pull/29459

**Comment by progoney** [comment]
encounter this when run insanely-fast-whisper. please hurry.

**Comment by jhavukainen** [comment]
This should be solved now as https://github.com/pytorch/pytorch/pull/124896 got merged so I'm closing the issue. Please try out the nightly build to see if this issue is solved for you.

**Comment by pmane** [comment]
encounter this when run insanely-fast-whisper. Used nightly built but did not fix the issue

**Comment by pmane** [comment]
> encounter this when run insanely-fast-whisper. please hurry.

Did you manage to fix using nightly build ?
