### ISSUE TITLE
make_graphed_callables fails when Module or function does not contain parameters

### ISSUE THREAD

**Issue by jeffwillette** [pytorch/pytorch#124582]
### 🐛 Describe the bug

make_graphed_callables fails with the following error when creating a static graph for a function which does not contain parameters. It seems like `make_graphed_callables` is still useful for the case when there are no parameters involved and one wishes to create a static graph of a parameterless function.

### Error logs

```
Traceback (most recent call last):
  File "/c2/repo/models/mgc_bug.py", line 24, in <module>
    func = torch.cuda.make_graphed_callables(func, (args,))
  File "/c2/user/anaconda3/envs/env/lib/python3.10/site-packages/torch/cuda/graphs.py", line 318, in make_graphed_callables
    grad_inputs = torch.autograd.grad(
  File "/c2/user/anaconda3/envs/env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 411, in grad
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
ValueError: grad requires non-empty inputs.
```

### Minified repro

In this repro

```
import torch
from torch import nn


def func(x):
    return torch.gather(x, 0, torch.tensor(0, device=x.device))


class Model(nn.Module):

    def forward(self, x):
        return torch.gather(x, 0, torch.tensor(0, device=x.device))


if __name__ == "__main__":
    args = torch.randn(1, requires_grad=False).cuda()
    model = Model().cuda()

    # model and func fail with the same error
    model = torch.cuda.make_graphed_callables(model, (args, ))
    func = torch.cuda.make_graphed_callables(func, (args, ))
```

### Versions

Collecting environment information...
PyTorch version: 2.2.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-131-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 9.1.85
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti
GPU 4: NVIDIA GeForce RTX 2080 Ti
GPU 5: NVIDIA GeForce RTX 2080 Ti
GPU 6: NVIDIA GeForce RTX 2080 Ti
GPU 7: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 470.141.03
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              20
On-line CPU(s) list: 0-19
Thread(s) per core:  2
Core(s) per socket:  10
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
Stepping:            7
CPU MHz:             1000.115
CPU max MHz:         3200.0000
CPU min MHz:         1000.0000
BogoMIPS:            4800.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            14080K
NUMA node0 CPU(s):   0-19
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] performer-pytorch==1.1.4
[pip3] pytorch-lightning==2.2.1
[pip3] reformer-pytorch==1.4.4
[pip3] torch==2.2.1
[pip3] torchaudio==2.2.1
[pip3] torchmetrics==1.3.1
[pip3] torchvision==0.17.1
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.26.4          py310h5f9d8c6_0  
[conda] numpy-base                1.26.4          py310hb5e798b_0  
[conda] performer-pytorch         1.1.4                    pypi_0    pypi
[conda] pytorch                   2.2.1           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-lightning         2.2.1              pyhd8ed1ab_0    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] reformer-pytorch          1.4.4                    pypi_0    pypi
[conda] torchaudio                2.2.1               py310_cu118    pytorch
[conda] torchmetrics              1.3.1                    pypi_0    pypi
[conda] torchvision               0.17.1              py310_cu118    pytorch
[conda] triton                    2.1.0                    pypi_0    pypi

cc @mcarilli @ezyang @eellison @peterbell10 @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by xrq-phys** [comment]
Same issue encountered. Is there any possible workarounds?

**Comment by jeffwillette** [comment]
the `make_graphed_callables` fucntion is relatively lightweight, so I copied the source and modified it myself to not depend on parameters.

I ended up writing my own cuda kernel instead of using this function so I no longer have the code, but I remember it was an easy fix. I could work on a PR if needed, but I would liketo verify with the Pytorch team if it is a valid problem that needs to be fixed. Maybe they made it that way on purpose.

**Comment by jeffwillette** [comment]
You just have to check here to make sure there are parameters that require grad before calling backward. https://github.com/pytorch/pytorch/blob/main/torch/cuda/graphs.py#L322

**Comment by ezyang** [comment]
Yes, is valid! Please send us the PR

**Comment by jeffwillette** [comment]
@ezyang I submitted a PR, can you take a look at it if you have a chance?
