### ISSUE TITLE
FlexAttention failing with Triton error in case with double indirect load

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#124571]
### 🐛 Describe the bug

https://pastebin.com/yv4jRwVv

Upon running this code, I get a
```
python: /data/users/chilli/triton_source/lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp:397: bool collectOpsToPipeline(mlir::scf::ForOp, llvm::MapVector<mlir::Operation*, {anonymous}::PipelineOpInfo>&, int, bool&): Assertion `!isa<tt::LoadOp>(iter->first)' failed.
```

The code is coming from this test in this PR: https://github.com/pytorch/pytorch/pull/124444/files#diff-3c0cafed3daa35a27737b54c2c54948c17288834865b3f71600a7f63e8e0a0f9R239

cc: @htyu @manman-ren

### Versions

N/A

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by manman-ren** [comment]
@chenyang78 Did you conform that with PR3517, this will be fixed? If not, I can try to confirm it.

**Comment by Chillee** [comment]
For posterity, @chenyang78 confirmed that on a new commit this is fixed.

**Comment by chenyang78** [comment]
> @chenyang78 Did you conform that with PR3517, this will be fixed? If not, I can try to confirm it.

Yes, I confirmed that the issue was fixed.

**Comment by IvanKobzarev** [comment]
Doing issue scrapping, closing according to comment the issue was fixed.
