### ISSUE TITLE
Add option to `torch.load(mmap=True)` to do `MAP_SHARED` rather than `MAP_PRIVATE`

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/pytorch#124528]
### 🚀 The feature, motivation and pitch

Currently `torch.load(mmap=True)` calls `mmap(2)` with `MAP_PRIVATE`, this ensures that changes to the loaded checkpoint are not written back to the file.

As suggested by @albanD there might be a way to do postprocessing on checkpoints in CPU RAM-constrained environments if we  pass `MAP_SHARED` instead 

This would just involve passing `shared=True` to `UntypedStorage.from_file`

cc @mruberry

**Comment by colinacassidy** [comment]
Can we claim this task? Looking at getting into contributing to this project and this seems like a good first task. Should have a PR up in a day or so.

**Comment by mikaylagawarecki** [comment]
Hey @colinacassidy, thanks for your interest. Unfortunately I plan to pick this one up :( You could check out the [actionable label](https://github.com/pytorch/pytorch/labels/actionable) for a list of issues open to be picked up!

**Comment by albanD** [comment]
I am not a fan of adding an extra argument to load() just for this. So maybe a torch.serialization.default_mmap_visibility would be the best API? Not sure if there are other settings of the mmap call we could expose the same way that might be useful?
