### ISSUE TITLE
custom ops should have needs_fixed_stride_order by default

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#124647]
And we should make sure there is a way for the user to opt-out of it (maybe another tag?)

cc @ezyang @gchanan @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by bdhirsh** [comment]
new tag bikeshedding: `Tag.supports_arbitrary_layout` / `Tag.supports_arbitrary_stride`?

**Comment by zou3519** [comment]
going to unassign myself for a little bit, I am not getting to this in the next month.

**Comment by yf225** [comment]
@zou3519 Curious do we need to find a new owner for this issue? (or is it still high-pri?)

**Comment by zou3519** [comment]
Still hi-pri. No need to find a new owner. I'm slowly moving towards it.

**Comment by bdhirsh** [comment]
@zou3519 fixed!
