### ISSUE TITLE
Dynamic shapes not traced correctly in torch.onnx.dynamo_export()

### ISSUE THREAD

**Issue by doloresgarcia** [pytorch/pytorch#124625]
### 🐛 Describe the bug

Hi all, 

I try to use my model with dynamic inputs (as it is a GNN) [MODEL](https://drive.google.com/file/d/1pV8S_cEVbQQLT7aS6LEJikAX5zKKoWmz/view?usp=sharing)
I can export and run inference on the same shape but not on a different shape:
```

ort_session = ort.InferenceSession(
    "model_multivector_10.onnx",
    # providers=["CPUExecutionProvider"],
    sess_options=so,
)
input_data = torch.randn((30, 1, 16))

# it works with this option
# input_data = torch.randn((10, 1, 16))
def to_numpy(tensor):
    return (
        tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()
    )
# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(input_data)}
ort_outs = ort_session.run(None, ort_inputs)

```
Is there anyway to pass the shape through the model in pytorch dynamo?

This happens even when the model only has this layer:
`torch.einsum("y x a, a i j, ... x j -> ... y i", W, basis, input)`

### Versions

onnxruntime 1.17.3
onnx 1.16.0
0.1.0.dev20240422
pytorch 2.2.1 cu121

cc @ezyang

**Comment by ezyang** [comment]
I'm not super familiar with the ONNX export mechanism, but torch.export needs you to explicitly specify what inputs you want to be dynamic.

**Comment by doloresgarcia** [comment]
In the torch dynamo documentation it is included in the `ExportOptions`, which I used in the export. https://pytorch.org/docs/stable/onnx_dynamo.html

**Comment by doloresgarcia** [comment]
it seems like it can't keep the shape when the einsum has multiple inputs but it works with dynamic shapes if it is split as:
`c2 = torch.einsum("y x a, a i j ->  y x i j ", coeffs, basis)
    a2 = torch.einsum("y x i j , l x j -> l y i", c2, x)`
