### ISSUE TITLE
Caffe2 usage of cuDNN RNNv6 API blocks upgrade to cuDNN v9+

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#124790]
### 🐛 Describe the bug

cuDNN RNNv6 API support was dropped in v9+. PyTorch itself has been migrated to the RNNv8 API in #115719, #120277, but Caffe2 has not been migrated and this currently results in build breakages when attempting to upgrade cuDNN to v9+ e.g., https://github.com/pytorch/pytorch/pull/123475

The two immediate possible solutions are:
1. drop Caffe2 from the breaking open source build(s) (currently just seems to be a single bazel build)
2. remove the RNN operators from Caffe2

A third option of porting Caffe2 to RNNv8 is technically possible, but seems wasteful when considering e.g., #122527 

CC @atalman @malfet 

### Versions

Current upstream

cc @malfet @seemethere @csarofeen @ptrblck @xwang233 @ezyang @gchanan @mikaylagawarecki

**Comment by drisspg** [comment]
I was having a discussion with Alban about all the open issues we have. Alban said that anything marked Caffe2 can be closed. If that is not the case feel free to re-open

**Comment by eqy** [comment]
Somehow we upgraded to v9+ without there being problems so I'm fine with closing
