### ISSUE TITLE
Compile doesn't guard on user NN module attribute

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#124717]
### 🐛 Describe the bug

TorchTune relies on mutating user NN module's attribute to decide whether to e.g. apply LoRA technique. The usage pattern looks like this:

```python
import contextlib
import torch

class TestModuleWithAdapter(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.disabled = False

    def forward(self, x):
        out = x * x
        if self.disabled:
            return out
        out = out + 1
        return out


@contextlib.contextmanager
def disable_adapter(mod):
    mod.disabled = True
    try:
        yield
    finally:
        mod.disabled = False


mod = TestModuleWithAdapter()
mod = torch.compile(mod)
x = torch.randn(4, 4)
out_enable = mod(x)
with disable_adapter(mod):
    out_disable = mod(x)
assert torch.allclose(out_enable, x * x + 1)
assert torch.allclose(out_disable, x * x)   # <-- fails
```

User expects that by wrapping second `mod(x)` call with `with disable_adapter(mod):`, the `if self.disabled:` branch in TestModuleWithAdapter.forward takes effect. But currently we don't detect that an attribute of the compiled module is mutated and thus recompile is not triggered. This causes mismatch in behavior between eager and compile mode.

(Corresponding issue on TorchTune repo: https://github.com/pytorch/torchtune/issues/721)

### Versions

PyTorch nightly

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78

**Comment by yf225** [comment]
Tagging this issue as high-priority, because it's a common usage pattern in TorchTune.

**Comment by jbschlosser** [comment]
Related: #111785, #120958 

`torch._dynamo.config.guard_nn_modules=True` can be used to workaround this, with a perf penalty.

**Comment by BenjaminBossan** [comment]
> `torch._dynamo.config.guard_nn_modules=True` can be used to workaround this, with a perf penalty.

I tried this but no success, exactly the same error occurs as before. Do I need a specific PyTorch branch to use this feature? I tested on v2.3.0.

**Comment by anijain2305** [comment]
`torch._dynamo.config.guard_nn_modules=True` does work for the example above. @yf225 please turn on this flag for torchtune. I am trying to turn it on by default. Timeline is by end of May.

@BenjaminBossan I think you have a different repro. Can you please open an issue with your repro?

**Comment by BenjaminBossan** [comment]
> I think you have a different repro

No, I use the exact same snippet as posted at the top and still get the exact same outputs and thus assertion error. I use PyTorch `2.3.0+cu121` and I add the snippet at the top, directly under the `torch` import. Am I doing something wrong?

**Comment by anijain2305** [comment]
This works now on main (and nightly). Please feel to reopen if you still see the issue.
