### ISSUE TITLE
ARM libtorch links to libomp but libomp is no longer bundled

### ISSUE THREAD

**Issue by hugary1995** [pytorch/pytorch#124732]
### 🐛 Describe the bug

We have an application based on libtorch (currently using torch==2.2.1) which stops building on apple silicon starting yesterday. `otool -L libtorch_cpu.dylib` shows that `libomp.dylib` should be on the rpath.

I have two questions here:
1. Is the ARM libtorch actually using openmp?
2. Should we bundle libomp together with libtorch if the answer to 1 is yes?

For now, I can tell my users to install the x86 version of homebrew and run `brew install libomp`. But that feels suboptimal.

### Versions

I checked both libtorch 2.2.1 and 2.2.2 downloaded from the official link:
https://download.pytorch.org/libtorch/cpu/libtorch-macos-arm64-2.2.1.zip
https://download.pytorch.org/libtorch/cpu/libtorch-macos-arm64-2.2.2.zip

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @malfet @osalpekar @atalman @jbschlosser @albanD

**Comment by hugary1995** [comment]
The libtorch that comes with the conda package doesn't have this issue, on the other hand.

I did 
```
conda install pytorch::pytorch -c pytorch
```
and the `libtorch_cpy.dylib` there doesn't link against `libomp.dylib`

**Comment by hugary1995** [comment]
@malfet  Thanks for the info. I am more concerned about the linking issue, as that prevents users from using my app. The bottom line is that libtorch (for ARM) downloaded from the official website is unusable at the moment on ARM machines without a system libomp.

**Comment by malfet** [comment]
Fixed by https://github.com/pytorch/builder/commit/4414fc69945b2eb918a4f3bfd87563f03498f3c4
