### ISSUE TITLE
c10d build depends on non-standard OpenMPI header mpi-ext.h

### ISSUE THREAD

**Issue by sparticlesteve** [pytorch/pytorch#12471]
## 🐛 Bug

The file torch/lib/c10d/ProcessGroupMPI.cpp includes this header which as far as I can tell is specific to OpenMPI:
```
#include <mpi-ext.h> // Needed for CUDA-aware check
```
So this won't build with other MPI implementations, including Cray MPICH which we use at NERSC.
I was able to work around it with the following change:
https://github.com/pytorch/pytorch/commit/a59d94749b535e2e278036d89ae8904de18bd0b9
but maybe it also/instead needs a check on `#if defined (OPEN_MPI)`, and/or an alternate include or implementation when not using OpenMPI.

## To Reproduce

I'm building pytorch from source on our systems, so the instructions won't be trivial. I can provide more details if asked but I hope the above description speaks for itself.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0rc1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): will provide on request
 - Python version: 3.6.6

**Comment by pietern** [comment]
This header was gated in #13083 and @teng-li verified with a manual MPICH build.

Closing this one and we'll deal with the issue you mentioned on Slack separately.

**Comment by teng-li** [comment]
Yep, this is fixed
