### ISSUE TITLE
`torch.autocast` produces confusing error message when passing `torch.device`

### ISSUE THREAD

**Issue by rachitk** [pytorch/pytorch#124738]
### 🐛 Describe the bug

When using `torch.autocast`, the device argument does not accept instances of `torch.device` (as expected from the documentation). The fact that it errors is expected, as the documentation states that this is unsupported, but the error message produced is not informative/confusing.

```python
import torch

device = torch.device('cuda') # or 'cpu'

# Note that we should have passed device.type here, so the fact that this errors isn't itself a bug.
with torch.autocast(device_type=device):
    pass
```

This code block will return:

```RuntimeError: User specified an unsupported autocast device_type 'cuda'``` (or `'cpu'` if used above)

which is fairly uninformative/confusing, given that 'cuda' is actually an allowed `device_type`. 

Suggestion: perhaps print the type of the `device_type` if it isn't already a string (or complain about the type instead of the `str` representation)? If needed, I can submit a simple PR to do this.

The error arises from this line which just prints the `str` representation of the passed argument: https://github.com/pytorch/pytorch/blob/47330ca13321a42d4f1e75f091e17183227ae073/torch/amp/autocast_mode.py#L241

### Versions

```
Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.2
[pip3] torch_geometric==2.5.2
[pip3] torchaudio==2.2.2
[pip3] torchvision==0.17.2
[pip3] triton==2.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.2                    pypi_0    pypi
[conda] torch-geometric           2.5.2                    pypi_0    pypi
[conda] torchaudio                2.2.2                    pypi_0    pypi
[conda] torchvision               0.17.2                   pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi
```

(Note that I didn't include my system details since this is system-invariant, but let me know if you do want those).

cc @svekars @brycebortree @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by soulitzer** [comment]
Thanks for the report. We would accept a PR to fix this.

**Comment by rachitk** [comment]
Thanks for the feedback/validation - it looks like someone has already submitted a PR that would theoretically fix the issue, so I'll defer to that PR rather than make a new one.

**Comment by mrgransky** [comment]
Instead of directly passing device to device_type, access the device type string from the device object:with 
```
torch.amp.autocast(device_type=device.type):  # Use device.type to get the string
   pass
```
