### ISSUE TITLE
torch_dispatch has unfaithful behavior w.r.t. wrapped numbers

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#124731]
Test case:
```py
import torch
import torch
import torch.autograd.forward_ad as fwAD

def f(x):
    return 4312491 * x

device = "cpu"

with torch._subclasses.fake_tensor.FakeTensorMode():
    with fwAD.dual_level():
        x = torch.randn(3, device=device)
        y = torch.ones_like(x)
        dual = fwAD.make_dual(x, y)
        f(dual)
```

- 4312491 turns into a Tensor that is a wrapped number
- without FakeTensorMode, the call to mul will eventually call alias on the wrapped number which will return something
- with FakeTensorMode, we dispatch to alias in Python. The wrapped number becomes a Python int. And `aten.alias(int)` raises a TypeError.

Some options:
- audit all possible sites where this can happen and fix them (it might just be forward-mode AD + ops that do is wrapped number (the arithmetic ops))
- do something more systematic

cc @ezyang @gchanan @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by zou3519** [comment]
Hi-pri because this breaks a common case with the functorch x PT2 interaction (jvp with mul + numbers)

**Comment by masnesral** [comment]
From internal triage meeting: Richard still planning to look at this.

**Comment by guilhermeleobas** [comment]
I think this was fixed in https://github.com/pytorch/pytorch/pull/124774

**Comment by zou3519** [comment]
closing as fixed
