### ISSUE TITLE
installing pytorch via Conda will also install torch from pip?!

### ISSUE THREAD

**Issue by ghost** [pytorch/pytorch#12470]
Hi there,
When installing pytorch via conda
```
conda install -n test -c pytorch pytorch torchvision
```
It shows in the exported environment.yml that it installed both pytorch and torchvision via conda, but also shows in the bottom that it installed `torch==0.4.1` under `pip`, why is that?

I only want the packages via Conda, not pip. any help

**Comment by MrOCR** [comment]
name: test
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bokeh=0.13.0=py36_0
.
.
.
  - pytorch=0.4.1=py36ha74772b_0
  - setuptools=40.4.3=py36_0
  - torchvision=0.2.1=py36_0
.
.
.
  - pip:
    - msgpack==0.5.6
    - torch==0.4.1

**Comment by MrOCR** [comment]
@apaszke @ezyang @gchanan @colesbury @goldsborough

**Comment by mengxr** [comment]
Is it because the conda package name `pytorch` is different from the python package name `torch`?

**Comment by ngimel** [comment]
closing due to age
