### ISSUE TITLE
[inductor][cpu]LoweringException: AttributeError: 'NoneType' object has no attribute 'get_origin_node' in 2024-04-20 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#124844]
### 🐛 Describe the bug

<p>AMP dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>botnet26t_256</td>
      <td>multiple</td>
      <td>X</td>
      <td>N/A</td>
      <td>botnet26t_256, LoweringException: AttributeError: 'NoneType' object has no attribute 'get_origin_node'</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>cait_m36_384</td>
      <td>multiple</td>
      <td>X</td>
      <td>N/A</td>
      <td>cait_m36_384, LoweringException: AttributeError: 'NoneType' object has no attribute 'get_origin_node'</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>eca_botnext26ts_256</td>
      <td>multiple</td>
      <td>X</td>
      <td>N/A</td>
      <td>eca_botnext26ts_256, LoweringException: AttributeError: 'NoneType' object has no attribute 'get_origin_node'</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>eca_halonext26ts</td>
      <td>multiple</td>
      <td>X</td>
      <td>N/A</td>
      <td>eca_halonext26ts, LoweringException: AttributeError: 'NoneType' object has no attribute 'get_origin_node'</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>sebotnet33ts_256</td>
      <td>multiple</td>
      <td>X</td>
      <td>N/A</td>
      <td>sebotnet33ts_256, LoweringException: AttributeError: 'NoneType' object has no attribute 'get_origin_node'</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>d6015d42</td>
      <td>main</td>
      <td>d6015d42</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>bad8d25881d850eaf0b326f6ce5c78305e38c001</td>
      <td>main</td>
      <td>88a71594933b2464d9d8b6b3533c5a945a4ac2ff</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+2c4665f</td>
      <td>main</td>
      <td>0.19.0a0+2c4665f</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.2.0a0+ea437b3</td>
      <td>main</td>
      <td>2.2.0a0+ea437b3</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh thread inference accuracy/performance suite model amp first dynamic
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/78f3b99a94659d1d14e28f6271e123cc48dcef71
[timm_models-eca_halonext26ts-inference-amp-dynamic-default-multiple-accuracy-crash_guilty_commit.log](https://github.com/pytorch/pytorch/files/15096000/timm_models-eca_halonext26ts-inference-amp-dynamic-default-multiple-accuracy-crash_guilty_commit.log)
cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @WeizhuoZhang-intel @chuanqi129

**Comment by jiayisunx** [comment]
This issue cannot be reproduced with the latest PyTorch, @zxd1997066 please try again with the latest PyTorch.

**Comment by zxd1997066** [comment]
The issue is fixed in the latest report.
