### ISSUE TITLE
Compiled autograd doesn't support reading attribute from autograd context if the attribute is created in eager forward

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#124827]
Repro:
```python
import torch
from torch._dynamo import compiled_autograd

class CommOpGradientScaling(torch.autograd.Function):
    @staticmethod
    def forward(
        ctx, input_tensor, scale_gradient_factor
    ) -> torch.Tensor:
        ctx.scale_gradient_factor = scale_gradient_factor
        return input_tensor

    @staticmethod
    def backward(
        ctx, grad_output
    ):
        grad_output.mul_(ctx.scale_gradient_factor)
        return grad_output, None


class Net(torch.nn.Module):
    def __init__(self, checkpoint=False):
        super().__init__()
        self.fc1 = torch.nn.Linear(4, 4)

    def forward(self, x):
        x = CommOpGradientScaling.apply(x, 0.5)
        return self.fc1(x)


model = Net()
# model = torch.compile(model)
input = torch.randn([1, 4], requires_grad=True)

def compiler_fn(gm):
    return torch.compile(gm, backend="aot_eager", fullgraph=True)

with compiled_autograd.enable(compiler_fn):
    loss = model(input).sum()
    loss.backward()
```

The above code as-is will throw error:
```
  File "/data/users/willfeng/pytorch_yf225/torch/fx/proxy.py", line 298, in create_arg
    raise NotImplementedError(f"argument of type: {type(a)}")
torch._dynamo.exc.InternalTorchDynamoError: argument of type: <class 'type'>

from user code:
   File "<eval_with_key>.0", line 23, in forward
    call_backward = torch__dynamo_external_utils_call_backward(getitem_6, (), mm);  getitem_6 = mm = None
  File "/data/users/willfeng/pytorch_yf225/torch/_dynamo/external_utils.py", line 78, in call_backward
    grads = backward_fn(FakeContext(saved_tensors), *args)
  File "/data/users/willfeng/pytorch_yf225/test/test_ca_custom_autograd_func.py", line 16, in backward
    grad_output.mul_(ctx.scale_gradient_factor)
```
If we print out what `a` is in `raise NotImplementedError(f"argument of type: {type(a)}")`, we can see it's a `NO_SUCH_SUBOBJ`. And then printing more info from `NO_SUCH_SUBOBJ` creation site will tell us that it's because we are trying to look for the `scale_gradient_factor` attribute in the `torch._dynamo.external_utils.FakeContext` object and failed at doing so.

Compare this with compiled forward (uncomment `model = torch.compile(model)`), and we will see that only eager forward has this problem.

This is currently a blocker for enabling compiled autograd and compiled DDP on Ads models.

cc. @xmfan @fegin

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by xmfan** [comment]
To unblock, add `_compiled_autograd_should_lift = False`  to the autograd.Function you want to allowlist. This will let compiled autograd trace through it, and will give incorrect results when it is unsafe to trace e.g. global mutations.

```python
class CommOpGradientScaling(torch.autograd.Function):
    _compiled_autograd_should_lift = False
```

**Comment by majian4work** [comment]
hi @xmfan 
I have enable compiled forward + aot bwd + compiled autograd, I see a self-defined autograd.Function sometimes inlined, sometime not inlined, and the grad is wrong.
does `_compiled_autograd_should_lift` can help for this?
or any option to disable inline autograd.Function?

**Comment by xmfan** [comment]
@majian4work Only the CompiledFunctionBackward (autograd.Function backward traced by AOT) will be inlined in the compiled autograd graph, other autograd.Function are inlined later in the dynamo graph. _compiled_autograd_should_lift is just a fast path because we know the AOT backward is safe to inline directly, without Dynamo's bytecode analysis.

If you have a grad correctness issue, could you file an issue and share a repro? I can take a look at it

**Comment by majian4work** [comment]
hi @xmfan ， thanks for your response.
I have created a mini repo in https://github.com/pytorch/pytorch/issues/129963, and found the root cause, it's not related to compiled_autograd, just a bug in tracing autograd.Function.
