### ISSUE TITLE
Add privateuse1 check on capturable optimizer

### ISSUE THREAD

**Issue by accelerate321** [pytorch/pytorch#124830]
### 🚀 The feature, motivation and pitch

We develop a tool similar to CUDAGraph on our own custom device (using dispatch key PrivateUse1), but capturable optimizer hardcode cuda like below:
```
# If compiling, the compiler will handle cudagraph checks, see note [torch.compile x capturable]
        if not torch._utils.is_compiling() and capturable:
            assert (param.is_cuda and step_t.is_cuda) or (
                param.is_xla and step_t.is_xla
            ), "If capturable=True, params and state_steps must be CUDA or XLA tensors."
```

Can I add privateuse1 check in these checks, or any other more general solutions?

```[tasklist]
### Tasks
```

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by albanD** [comment]
Yes, I think we want to have `param.device == step_t.device`.
Will let @janeyx99 confirm it's fine with her.

**Comment by janeyx99** [comment]
yes, agreed with alban—we could even be stricter and force that device is in a set of capturable_supported_devices but that might not be necessary.

**Comment by accelerate321** [comment]
Thanks, I submit a PR  and change to `param.device == step_t.device`. @albanD @janeyx99
