### ISSUE TITLE
Caffe2: Couldn't determine version from header: Change Dir:

### ISSUE THREAD

**Issue by YunYang1994** [pytorch/pytorch#12480]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by weiyangfb** [comment]
@YunYang1994 could you provide more info on your issue?
