### ISSUE TITLE
How to catch NCCL collective timeout in Python

### ISSUE THREAD

**Issue by gkroiz** [pytorch/pytorch#124887]
## Issue description
Currently, there are several error handling modes ([link](https://github.com/pytorch/pytorch/blob/bc117898f18e8a698b00823f57c19b2d874b93ba/torch/csrc/distributed/c10d/ProcessGroupNCCL.hpp#L114-L126)) for when NCCL collectives timeout. These error handling modes can be set via `TORCH_NCCL_ASYNC_ERROR_HANDLING`/`NCCL_ASYNC_ERROR_HANDLING`. My current observation on single/multi-host CUDA environments using NCCL distributed backend is that when a timeout exception is raised at the C++ level (when `TORCH_NCCL_ASYNC_ERROR_HANDLING=1`), this exception propagates through a few try/catch blocks, but eventually is left unhandled, resulting in the Python processes terminating via SIGABRT/SEGFAULT.

Question: Is it possible without many any modifications to torch to catch the error raised at the C++ level within my Python torch script?

Based on digging around, I don't think it is possible (open to any suggestions). I've done some experimentation to the PyTorch source code locally by adding some logic based on [Python docs](https://docs.python.org/3.10/extending/extending.html#intermezzo-errors-and-exceptions) to [ProcessGroupNCCL.cpp](https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp) such that the exception can be caught in Python. However, `#include <Python.h>` in  [ProcessGroupNCCL.cpp](https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp) results in `fatal error: Python.h: No such file or directory` when building torch from source. 

Question: Are there explicit reasons why I shouldn't add python to NCCL logic?

## Code example
TODO if needed

## System Info
TODO if needed

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

**Comment by gkroiz** [comment]
cc @voznesenskym and @awgu

**Comment by malfet** [comment]
To be frank this sounds like an topic that should be discussed in https://discuss.pytorch.org as I don't see why this is an issue

On the other hand, if NCCL raises an unhandled exception it is a bug, that should be fixed on the PyTorch side

**Comment by gkroiz** [comment]
> To be frank this sounds like an topic that should be discussed in https://discuss.pytorch.org/ as I don't see why this is an issue.

I can continue this topic in https://discuss.pytorch.org.

> If NCCL raises an unhandled exception it is a bug, that should be fixed on the PyTorch side

I want to clarify that NCCL isn't raising an unhandled exception, but rather the raised exceptions in https://github.com/pytorch/pytorch/blob/b8b04b26fbf160874f7f1a9db61e49801fd4fcbe/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1426-L1448 are never caught at the C++ level.

**Comment by kwen2501** [comment]
It is hard to catch NCCL timeouts or async errors on the python side before those happens asynchronously on a C++ side service thread provided by pytorch (called watchdog) as compared to the main thread on the python side.
