### ISSUE TITLE
ShapeEnv canonicalization is still over-aggressive

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#124855]
### 🐛 Describe the bug

I was inspecting some deferred runtime assert code and I noticed this:

```
    mul_1 = -1 * _local_scalar_dense_1
    le_3 = mul_1 <= 0;  mul_1 = None
    _assert_scalar_default_5 = torch.ops.aten._assert_scalar.default(le_3, "Runtime assertion failed for expression -u1 <= 0 on node 'le_3'\\nMore context: %mul_1 : [num_users=1] = call_function[target=operator.mul](args = (-1, %_local_scalar_dense_1), kwargs = {})\\n%le_3 : [num_users=0] = call_function[target=operator.le](args = (%mul_1, 0), kwargs = {})");  le_3 = None
```

The canonicalization is causing two problems:

* We end up with a more verbose FX graph, because we have to have a separate FX node for the negation. This adds up.
* We end up with a less good runtime error message, since the canonicalized expr is printed

Maybe we can store the un-canonicalized along with canonicalized in RuntimeAssert, and then use the uncanonical for this stuff.

cc @msaroufim @bdhirsh @anijain2305 @chauhang @lezcano 

### Versions

main

**Comment by lezcano** [comment]
Or cache the canonicalize function and simply call it whenever you need it, but pass the uncanonicalized expression around.

**Comment by IvanKobzarev** [comment]
Hi @ezyang , doing issue scrapping , is this issue still relevant or it was fixed and can be closed?
