### ISSUE TITLE
Providing a way to ignore "size checking" during backward for manually defined autograd.Function

### ISSUE THREAD

**Issue by phizaz** [pytorch/pytorch#12489]
## 🚀 Feature
Providing a way to ignore "size checking" during backward for manually defined `autograd.Function`.

## Motivation
I'm trying to implement a straight-through gradient estimator for a categorical distribution sampling.

Let's say that I have `P(x)` from which I sample `x`. I implement an `autograd.Function` for this process using straight-through estimator. 

In my scenario, I need to feed this `x` to an embedding function to get its vector representation.

Note: the `F.embedding` doesn't support gradient through `x` (of course), I need to also implement an `autograd.Function` for this as well. 

Here is the problem:

The input of the my embedding function is of shape `(batch,)` because `x` is just a list of ints. But its gradients aren't. Thanks to the straight through estimator, input of shape `(batch,)` could have gradients of other shape like `(batch, 10)` where 10 is the number of embeddings.

When I tried to implement so, Pytorch cried at me saying:

```
~/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     88     Variable._execution_engine.run_backward(
     89         tensors, grad_tensors, retain_graph, create_graph,
---> 90         allow_unreachable=True)  # allow_unreachable flag
     91 
     92 

RuntimeError: Function EmbeddingBackward returned an invalid gradient at index 0 - got [32, 10] but expected shape compatible with [32]
```
I interpret this message to be of some kind of size checking mechanism of the autograd. Is it a good idea to provide a way to switch this off? 

## Pitch
I know that size checking is a good feature. I don't know where to put this switch off button at.

## Alternatives
I could think of an alternative: 

Use one-hot encoding rather than a list of ints. This way I ensure that the shape will be preserved. Using one-hot is not a deal breaker though, I will go with this for a moment.

## Additional context
Pytorch version: 1.0.0.dev20181002

**Comment by apaszke** [comment]
Why would you want to pass gradients of different sizes like that? They generally break our invariants and are not guaranteed to even produce correct results if you try to pass them to other builtin autograd functions.

**Comment by phizaz** [comment]
@apaszke It sure breaks in most cases. But in my case, I have two of my own implementations of `autograd.Function` and I make sure that these two work together. 

| | P(x) | sampling | embedding(x)
| --- | --- | --- | --- |
| output shape | (n_batch, n_class) | (n_batch,) | (n_batch, n_emb) 
| grad shape | (n_batch, n_class) | straight through (n_batch, n_class) | (n_batch, n_emb)

**Comment by colesbury** [comment]
My gut reaction is that I don't like the idea of disabling the shape checks, because it breaks composition. The two functions will only work together, not with other autograd functions that obey standard behavior.

Can you combine the two functions? For example, the combined function could do sampling and call embedding(x) in the forward pass and compute embedding_backward, and the straight-through estimation in the backward pass. Would this work? There may be some challenges in the implementation, because I'm not sure we expose embedding_backward to Python.

**Comment by phizaz** [comment]
@colesbury I agree. I actually had tried to combine the operations, and it should work in most cases. I would say that there still some edge case that you cannot fuse the operations.

By the way, I already have my way out namely using one-hot encoding.

**Comment by ngimel** [comment]
Closing due to age
