### ISSUE TITLE
nn.functional.ELU output differs on MPS vs CPU if input is noncontiguous

### ISSUE THREAD

**Issue by damian0815** [pytorch/pytorch#124834]
### 🐛 Describe the bug

As per title - passing a non-contiguous tensor to `ELU` produces significantly different output on MPS and CPU. 

To reproduce:
```python
import torch
import torch.nn.functional as F
elu_input = torch.randn((1,1024,500))
alpha = float(1)
inplace = False
#print(F.elu(elu_input.to('cpu'), alpha, inplace))
#print(F.elu(elu_input.to('mps'), alpha, inplace))
print("contiguous:", elu_input.is_contiguous(), 
      ", all close:", torch.allclose(
    F.elu(elu_input.to('cpu'), alpha, inplace).cpu(),
    F.elu(elu_input.to('mps'), alpha, inplace).cpu(),
    rtol=1e-3, atol=1e-6)
)
print("")

elu_input_noncontiguous = elu_input.transpose(1, 2)
#print(F.elu(elu_input.to('cpu'), alpha, inplace))
#print(F.elu(elu_input.to('mps'), alpha, inplace))
print("contiguous:", elu_input_noncontiguous.is_contiguous(), 
      ", all close:", torch.allclose(
    F.elu(elu_input_noncontiguous.to('cpu'), alpha, inplace).cpu(),
    F.elu(elu_input_noncontiguous.to('mps'), alpha, inplace).cpu(),
    rtol=1e-3, atol=1e-6)
)
print("non-contiguous delta:", F.elu(elu_input_noncontiguous.to('cpu'), alpha, inplace).cpu() - 
    F.elu(elu_input_noncontiguous.to('mps'), alpha, inplace).cpu())
```

output: 
```
contiguous: True , all close: True

contiguous: False , all close: False
non-contiguous delta: tensor([[[ 5.9605e-08, -1.3394e+00, -8.0720e-01,  ...,  2.9639e-01,
           1.1317e-01,  1.2085e+00],
         [ 1.5183e+00,  5.9583e-01, -7.3344e-01,  ...,  1.7048e+00,
          -7.0464e-02, -1.5319e+00],
         [ 4.0359e-01, -3.5619e-01, -1.1294e-01,  ..., -8.9350e-01,
          -8.2647e-01,  1.7533e+00],
         ...,
         [-2.8854e-01,  9.3723e-01, -1.8684e+00,  ...,  1.1178e-01,
           1.5136e+00, -3.7568e-01],
         [-8.5926e-01, -1.0285e+00,  1.4309e+00,  ...,  1.7862e-01,
          -1.2812e+00,  2.0760e-01],
         [ 9.9825e-01,  1.3000e+00, -7.3440e-01,  ...,  1.4518e+00,
          -1.7251e+00,  0.0000e+00]]])
```

Issue is present on torch 2.2.2 and 2.4.0.dev20240423 (I didn't test any other versions).

### Versions

Collecting environment information...
PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: version 3.27.5
Libc version: N/A

Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:48:25)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.2
[pip3] torchaudio==2.2.2
[pip3] torchmetrics==1.3.2
[pip3] torchvision==0.17.2
[conda] numpy                     1.25.2                   pypi_0    pypi

cc @ezyang @gchanan @zou3519 @kadeng @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by skotapati** [comment]
We've confirmed this issue still repros on the latest nightly and have identified a fix, will link the PR once it's up
