### ISSUE TITLE
Torch nightly wheels no longer include `torchgen` YAML files

### ISSUE THREAD

**Issue by antoniojkim** [pytorch/pytorch#124941]
### 🐛 Describe the bug

It used to be the case that `native_functions.yaml` and `tags.yaml` were exported as part of `torchgen`. For example, even as of the recently released `torch==2.3.0`, searching for `yaml` files in the installed package directory shows
```bash
$ pip3 install --no-deps --force-reinstall torch==2.3.0 --index-url https://download.pytorch.org/whl/cpu
$ fd -e yaml . torch_2.3.0/lib/
torch_2.3.0/lib/python3.8/site-packages/torch/_export/serde/schema.yaml
torch_2.3.0/lib/python3.8/site-packages/torchgen/packaged/ATen/native/native_functions.yaml
torch_2.3.0/lib/python3.8/site-packages/torchgen/packaged/ATen/native/tags.yaml
torch_2.3.0/lib/python3.8/site-packages/torchgen/packaged/autograd/deprecated.yaml
torch_2.3.0/lib/python3.8/site-packages/torchgen/packaged/autograd/derivatives.yaml
```
But in the latest nightly `torch==2.4.0.dev20240425`, these `yaml` files don't appear to exist
```bash
$ pip3 install --no-deps --force-reinstall --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
$ fd -e yaml . torch_nightly/lib/
torch_nightly/lib/python3.8/site-packages/torch/_export/serde/schema.yaml
torch_nightly/lib/python3.8/site-packages/torchgen/packaged/autograd/deprecated.yaml
torch_nightly/lib/python3.8/site-packages/torchgen/packaged/autograd/derivatives.yaml
```
despite the fact that they are still meant to be exported as per
https://github.com/pytorch/pytorch/blob/87079f5e91be657743cfc6df74b519b68a8b0205/setup.py#L434-L438

### Versions

irrelevant

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
Grabbing for myself to investigate what has happened...

**Comment by malfet** [comment]
Hmm, I wonder if this is platform specific, as I can see the file in Mac binaries:
```
% curl -OL https://download.pytorch.org/whl/nightly/cpu/torch-2.4.0.dev20240420-cp39-none-macosx_11_0_arm64.whl
% unzip -t torch-2.4.0.dev20240420-cp39-none-macosx_11_0_arm64.whl|grep yaml
    testing: torch/_export/serde/schema.yaml   OK
    testing: torchgen/yaml_utils.py   OK
    testing: torchgen/packaged/ATen/native/native_functions.yaml   OK
    testing: torchgen/packaged/ATen/native/tags.yaml   OK
    testing: torchgen/packaged/autograd/deprecated.yaml   OK
    testing: torchgen/packaged/autograd/derivatives.yaml   OK

```

**Comment by malfet** [comment]
And removing 2.3.1 milestone, as 2.3 is not affected (even judging by this report) is it?

**Comment by malfet** [comment]
Ok, regression happened between Apr 21st and Apr 22nd and the only change that touched setup.py on that day was https://github.com/pytorch/pytorch/pull/119257
