### ISSUE TITLE
Dataloader crashes with FileNotFoundError randomly when num_workers>0 on Ubuntu 22.04

### ISSUE THREAD

**Issue by TomHeaven** [pytorch/pytorch#124903]
### 🐛 Describe the bug

I recently updated my system from Ubuntu 18.04 to Ubuntu 22.04. All pytorch programs works perfectly on Ubuntu 18.04 previously now run into the following error randomly (usually 1 to 5 minutes after the program started)  when the dataloader is initialized with num_workers > 0.

Bug Stack Trace:
```
Traceback (most recent call last):
  File "/home/tomheaven/实验/AP-BSN/train.py", line 42, in <module>
    main()
  File "/home/tomheaven/实验/AP-BSN/train.py", line 38, in main
    trainer.train()
  File "/home/tomheaven/实验/AP-BSN/src/trainer/base.py", line 81, in train
    self._run_epoch()
  File "/home/tomheaven/实验/AP-BSN/src/trainer/base.py", line 245, in _run_epoch
    self._run_step()
  File "/home/tomheaven/实验/AP-BSN/src/trainer/base.py", line 269, in _run_step
    data[key] = next(self.train_dataloader_iter[key])
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.19/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.19/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.19/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1294, in _get_data
    success, data = self._try_get_data()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.19/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.19/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.19/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 355, in rebuild_storage_fd
    fd = df.detach()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.19/lib/python3.9/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.19/lib/python3.9/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.19/lib/python3.9/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.19/lib/python3.9/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

The error will not be met when I set num_workers=0.

This is the code about dataloader:

```python
 dataloader[key] = DataLoader(dataset=dataset, batch_size=batch_size, shuffle=shuffle, num_workers=num_workers, pin_memory=False)
```

Things the I have tried：
1. Using different start method 'fork' or 'spawn' for multiprocessing. The error persists.
2. Using parameter `persistent_workers=True` in dataloader initialization. The parameter delayed the error but cannot prevent it.
3. Using different python versions. Both python 3.9.19 and 3.10.12 are tried. The error persists.
4. Different Pytorch versions: pytorch 2.1 and 2.0 ared tried. The error persists.

Maybe a clear reinstallation of Ubuntu 22.04 will fix it. I still wonder what else can I do before I perform a system reinstallation.

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-2ubuntu1~18.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.25.2
Libc version: glibc-2.35

Python version: 3.9.19 (main, Mar 19 2024, 16:08:27)  [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA Graphics Device

Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
架构：                           x86_64
CPU 运行模式：                   32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
字节序：                         Little Endian
CPU:                             16
在线 CPU 列表：                  0-15
厂商 ID：                        GenuineIntel
型号名称：                       11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
CPU 系列：                       6
型号：                           167
每个核的线程数：                 2
每个座的核数：                   8
座：                             1
步进：                           1
CPU 最大 MHz：                   5300.0000
CPU 最小 MHz：                   800.0000
BogoMIPS：                       7008.00
标记：                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap avx512ifma clflushopt intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear flush_l1d arch_capabilities
虚拟化：                         VT-x
L1d 缓存：                       384 KiB (8 instances)
L1i 缓存：                       256 KiB (8 instances)
L2 缓存：                        4 MiB (8 instances)
L3 缓存：                        16 MiB (1 instance)
NUMA 节点：                      1
NUMA 节点0 CPU：                 0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==2.1.3
[pip3] torch==2.1.0+cu118
[pip3] torchaudio==2.1.0+cu118
[pip3] torchmetrics==1.3.0.post0
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] Could not collect

cc @SsnL @VitalyFedyunin @ejguan @dzhulgakov

**Comment by tringwald** [comment]
Might be related to [this bug in CPython](https://github.com/python/cpython/issues/94765). Can you provide a short, self-contained repro that triggers the bug?

**Comment by TomHeaven** [comment]
@tringwald  Thanks for the reply. I found that issue but there is no working solution. Therefore, I spend a few hours backuping up data, formatting the system disk partition, and reinstalling Ubuntu 22.04.4 with CUDA 12.2 and Pytorch 2.3.  Now dataloader works perfectly again. So the cause of the bug is not in Pytorch.
