### ISSUE TITLE
Windows build with CUDNN

### ISSUE THREAD

**Issue by fmder** [pytorch/pytorch#12495]
The build script for windows ``tool/buid_pytorch_libs.bat`` explicitely sets USE_CUDNN=OFF. Shouldn't this be set USE_CUDNN=%USE_CUDNN%?

**Comment by peterjc123** [comment]
cc: @orionr

**Comment by fmder** [comment]
For what it's worth, I get the same linking error than the build system plus some case expression not constant errors.
