### ISSUE TITLE
Support torch.distributed.checkpoint.state_dict.get_model_state_dict/set_model_state_dict when torch dist is not initialized

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#124942]
### 🚀 The feature, motivation and pitch

The latest torch supports a wonderful unified interface with torch.distributed.checkpoint.get_model_state_dict and torch.distributed.checkpoint.set_model_state_dict which makes life so much easier for advanced parallelism use cases.

However, it still requires special casing the 1 GPU scenario where dist is not initialized. For example, `get_model_state_dict` calls `_get_default_group` which requires dist to be initialized.

It would be nice if these APIs gracefully fell back when dist was not initialized. 

The same is true for `get/set_optimizer_state_dict`.

This follows up on https://github.com/pytorch/pytorch/issues/118554, specifically https://github.com/pytorch/pytorch/issues/118554#issuecomment-1922974701

CC: @wconstab @LucasLLC @fegin 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @LucasLLC

**Comment by fegin** [comment]
According to the UT from https://github.com/pytorch/pytorch/pull/127385, this seems to be supported already. @mvpatel2000 can you confirm the use case? Is it `torch.distributed.is_initialized() == False` or `torch.distributed.is_available() == False`. The later is the case where `torch.distributed` is not built at all, which definitely requires more change to distributed state_dict.

**Comment by mvpatel2000** [comment]
> The later is the case where `torch.distributed` is not built at all, which definitely requires more change to distributed state_dict.

The use case is the former, where distributed is not initialized. Here is a link to the failure I am seeing: https://github.com/pytorch/pytorch/issues/118554#issuecomment-1915378794

```
/__w/composer/composer/composer/core/state.py:910: in get_model_and_optimizer_state_dict
    model_state_dict, optim_state_dict = get_state_dict(
/usr/lib/python3/dist-packages/torch/distributed/checkpoint/state_dict.py:729: in get_state_dict
    model_state_dict = _get_model_state_dict(model, info)
/usr/lib/python3/dist-packages/torch/distributed/checkpoint/state_dict.py:381: in _get_model_state_dict
    return _gather_state_dict(
/usr/lib/python3/dist-packages/torch/distributed/checkpoint/_state_dict_utils.py:176: in _gather_state_dict
    return _iterate_state_dict(
/usr/lib/python3/dist-packages/torch/distributed/checkpoint/_state_dict_utils.py:71: in _iterate_state_dict
    ret = {
/usr/lib/python3/dist-packages/torch/distributed/checkpoint/_state_dict_utils.py:72: in <dictcomp>
    key: _iterate_state_dict(
/usr/lib/python3/dist-packages/torch/distributed/checkpoint/_state_dict_utils.py:101: in _iterate_state_dict
    if not ranks_only or dist.get_rank(pg) in ranks_only:
/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py:1625: in get_rank
    default_pg = _get_default_group()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def _get_default_group() -> ProcessGroup:
        """Get the default process group created by init_process_group."""
        if not is_initialized():
>           raise ValueError(
                "Default process group has not been initialized, "
                "please make sure to call init_process_group."
            )
E           ValueError: Default process group has not been initialized, please make sure to call init_process_group.

/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py:985: ValueError
```

Does that help? I'm happy to provide more info if useful

**Comment by fegin** [comment]
uh, I see, this is when `full_state_dict` option is True. Let me fix this in the PR.
