### ISSUE TITLE
[RFC] Support reinplaceble ops for custom ops in Inductor

### ISSUE THREAD

**Issue by jgong5** [pytorch/pytorch#124933]
### 🚀 The feature, motivation and pitch

Currently, the inductor backend in PyTorch supports the reinplace optimization for a fixed list of ops in the reinplace fx pass (`torch/_inductor/fx_passes/reinplace.py`). However, for custom inplace ops that are functionalized into out-of-place ops using `copy_`, they cannot be reinplaced, which impacts performance. To address this, we propose adding a configuration option to the `torch.compile` inductor backend that allows users to specify the mapping between out-of-place ops and their inplace counterparts. This would enable the reinplace pass to support the reinplace optimization for these custom ops as well, potentially improving performance.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @zou3519

**Comment by zou3519** [comment]
If you use an in-place custom op with PT2, we will auto-functionalize it. Inductor will later re-inplace it. Do you have an example for what you're doing?

**Comment by jgong5** [comment]
> If you use an in-place custom op with PT2, we will auto-functionalize it. Inductor will later re-inplace it. Do you have an example for what you're doing?

As an example, we are adding a custom allreduce aten op in deepspeed with both out-of-place and in-place variants. The functionalization works well but it is not re-inplaced. Are you saying that the reinplacing should happen? I noticed that only a pre-defined list of ops are reinplaceable in `torch/_inductor/fx_passes/reinplace.py` which doesn't cover user-defined ops. Or did I miss anything here?

**Comment by Chillee** [comment]
@jgong5 Custom ops with inplace variants are wrapped with `torch.ops.higher_order.auto_functionalized`, which is reinplaced.

**Comment by zou3519** [comment]
To clarify:
- if you use an inplace operator directly, it will get functionalized and re-inplaced automatically.
- if you define separate out-of-place operator and in-place operators, there is no way today to say "these two are linked together; inductor should re-inplace the operator".

This issue sounds like it is for the latter

**Comment by zou3519** [comment]
I'm going to be out for ~3 weeks, but here's my take:
- there should be a torch.library API for "linking" functional operators with their in-place variants
- inductor should pull from this table when doing re-inplacing
- you want to check the linking in torch.library.opcheck.

**Comment by jgong5** [comment]
Thanks @Chillee and @zou3519 for the pointers.

> To clarify:
> 
> * if you use an inplace operator directly, it will get functionalized and re-inplaced automatically.
> * if you define separate out-of-place operator and in-place operators, there is no way today to say "these two are linked together; inductor should re-inplace the functional operator with the in-place operator".
> 
> This issue sounds like it is for the latter

In fact, we only need to capture the inplace operator directly. But we got problems if we only implement the inplace version. We got the following error with the inplace operator returning a tensor and a graph break after we avoid it returning anything. We were expecting it can be reinplaced. Is it expected?
```
[rank1]: torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[rank1]: RuntimeError: Found a custom (non-ATen) operator whose output has alias annotations: deepspeed::inference_all_reduce_(Tensor(a!) self) -> Tensor(a!). We only support functionalizi
ng operators whose outputs do not have alias annotations (e.g. 'Tensor(a)' is a Tensor with an alias annotation whereas 'Tensor' is a Tensor without. The '(a)' is the alias annotation). Th
e alias annotation specifies that the output Tensor shares storage with an input that has the same annotation. Please check if (1) the output needs to be an output (if not, don't return it
), (2) if the output doesn't share storage with any inputs, then delete the alias annotation. (3) if the output indeed shares storage with an input, then add a .clone() before returning it
to prevent storage sharing and then delete the alias annotation. Otherwise, please file an issue on GitHub.
 
[rank1]: While executing %inference_all_reduce_ : [num_users=0] = call_function[target=torch.ops.deepspeed.inference_all_reduce_](args = (%l_input_,), kwargs = {})
[rank1]: Original traceback:
[rank1]:   File "/home/gma/Tensor-Parallel-PyTorch/test_allreduce_jit_trace.py", line 32, in forward
[rank1]:     deepspeed.comm.inference_all_reduce(input)
[rank1]:   File "/home/gma/DeepSpeed/deepspeed/comm/comm.py", line 117, in log_wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/home/gma/DeepSpeed/deepspeed/comm/comm.py", line 508, in inference_all_reduce
[rank1]:     return cdb.inference_all_reduce(tensor, op, group)
[rank1]:   File "/home/gma/DeepSpeed/deepspeed/comm/torch.py", line 159, in inference_all_reduce
[rank1]:     return torch.ops.deepspeed.inference_all_reduce_(tensor)
```

**Comment by zou3519** [comment]
@jgong5 -- we don't support in-place ops that return the tensor being modified in-place. One needs to rewrite the deepspeed custom op to look like `deepspeed::inference_all_reduce_(Tensor(a!) self) -> ()`. That's what the error message is saying.

**Comment by jgong5** [comment]
> @jgong5 -- we don't support in-place ops that return the tensor being modified in-place. One needs to rewrite the deepspeed custom op to look like `deepspeed::inference_all_reduce_(Tensor(a!) self) -> ()`. That's what the error message is saying.

Yes, we tried but got graph breaks..

**Comment by jgong5** [comment]
@zou3519 Apology for the late reply. Below is the error log (op registered as `m.def("inference_all_reduce_noreturn(Tensor self) -> ()");`). Are you able to get some clue on it? I can share the repro but a bit complex since it depends on DeepSpeed. 

```
[rank0]:   File "/home/gma/miniforge3/envs/dscpustock/lib/python3.11/site-packages/torch/_dyna
mo/variables/builtin.py", line 1291, in call_getattr                                          
[rank0]:     member = obj.value.__dict__[name]                                                
[rank0]:              ~~~~~~~~~~~~~~~~~~^^^^^^                                                
[rank0]: torch._dynamo.exc.InternalTorchDynamoError: inference_all_reduce_noreturn            
[rank0]: from user code:                                                                      
[rank0]:    File "/home/gma/allreduce_graph/test_allreduce.py", line 30, in forward           
[rank0]:     deepspeed.comm.inference_all_reduce_noreturn(input)            
```

**Comment by zou3519** [comment]
If you mutate the `self` tensor, the schema should look like the following:

`m.def("inference_all_reduce_noreturn(Tensor(a!) self) -> ()");` 

A repro would help us debug if that does not work.

**Comment by delock** [comment]
> If you mutate the `self` tensor, the schema should look like the following:
> 
> `m.def("inference_all_reduce_noreturn(Tensor(a!) self) -> ()");`
> 
> A repro would help us debug if that does not work.
I tried this variant but get some error as:
```
[rank1]: torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[rank1]: TypeError: AutoFunctionalized.__call__() got multiple values for argument 'self'

[rank1]: While executing %inference_all_reduce_noreturn : [num_users=0] = call_function[target=torch.ops.deepspeed.inference_all_reduce_noreturn](args = (%l_input_,), kwargs = {})
[rank1]: Original traceback:
[rank1]:   File "/home/gma/allreduce_graph/test_allreduce.py", line 30, in forward
[rank1]:     deepspeed.comm.inference_all_reduce(input)
[rank1]:   File "/home/gma/DeepSpeed/deepspeed/comm/comm.py", line 117, in log_wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/home/gma/DeepSpeed/deepspeed/comm/comm.py", line 508, in inference_all_reduce
[rank1]:     return cdb.inference_all_reduce(tensor, op, group)
[rank1]:   File "/home/gma/DeepSpeed/deepspeed/comm/torch.py", line 159, in inference_all_reduce
[rank1]:     torch.ops.deepspeed.inference_all_reduce_noreturn(tensor)
```

I'll post repo steps.

**Comment by delock** [comment]
To reproduce:
* Checkout and install https://github.com/delock/DeepSpeedSYCLSupport/tree/gma/inference_all_reduce_in_graph_noreturn
* Checkout https://github.com/delock/allreduce_graph, this is the test case
* Go to allreduce_graph/ and execute `run.sh`

Last few lines of error is like this:
```
[rank1]: While executing %inference_all_reduce_noreturn : [num_users=0] = call_function[target=torch.ops.deepspeed.inference_a
ll_reduce_noreturn](args = (%l_input_,), kwargs = {})                                                                         
[rank1]: Original traceback:                                                                                                  
[rank1]:   File "/home/gma/allreduce_graph/test_allreduce.py", line 30, in forward                                            
[rank1]:     deepspeed.comm.inference_all_reduce(input)                                                                       
[rank1]:   File "/home/gma/DeepSpeed/deepspeed/comm/comm.py", line 117, in log_wrapper                                        
[rank1]:     return func(*args, **kwargs)                                                                                     
[rank1]:   File "/home/gma/DeepSpeed/deepspeed/comm/comm.py", line 508, in inference_all_reduce                               
[rank1]:     return cdb.inference_all_reduce(tensor, op, group)                                                               
[rank1]:   File "/home/gma/DeepSpeed/deepspeed/comm/torch.py", line 159, in inference_all_reduce                              
[rank1]:     torch.ops.deepspeed.inference_all_reduce_noreturn(tensor)                                                        
                                                                                                                              
                                                                                                                              
[rank1]: Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information                                              
                                                                                                                              
                                                                                                                              
[rank1]: You can suppress this exception and fall back to eager by setting:                                                   
[rank1]:     import torch._dynamo                                                                                             
[rank1]:     torch._dynamo.config.suppress_errors = True                                                                      
```
The line for schema
https://github.com/delock/DeepSpeedSYCLSupport/blob/gma/inference_all_reduce_in_graph_noreturn/csrc/cpu/comm/shm_interface.cpp#L133

**Comment by zou3519** [comment]
Repro:
```
import torch

@torch.library.custom_op("mylib::foo", mutates_args={"self"})
def foo(self: torch.Tensor) -> None:
    self.sin_()

x = torch.randn(3)

@torch.compile(backend="inductor", fullgraph=True)
def f(x):
    foo(x)

f(x)
```

Fix is probably to rename `self` to something a little more obscure, and also to improve the error message if there is a name collision
