### ISSUE TITLE
2.3.0 not backward compatible with torchdata

### ISSUE THREAD

**Issue by npuichigo** [pytorch/pytorch#124907]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/commit/f42818321b5694c5be76f16173c7ac9223ec8ae3 fixing not included in 2.3.0 release

### Versions

pytorch 2.3.0

cc @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
Thank you for reporting. Will probably cherry-pick the change into 2.3.1, but please note, that per https://github.com/pytorch/data/blob/main/README.md#torchdata-see-note-below-on-current-status torchdata has not been actively maintained, so if one needs to use torchdata they probably have to stick to older PyTorch versions

**Comment by npuichigo** [comment]
@malfet So is here any further plan to replace torchdata?

**Comment by mfbalin** [comment]
> Thank you for reporting. Will probably cherry-pick the change into 2.3.1, but please note, that per https://github.com/pytorch/data/blob/main/README.md#torchdata-see-note-below-on-current-status torchdata has not been actively maintained, so if one needs to use torchdata they probably have to stick to older PyTorch versions

Is this commit going to be cherry picked for 2.3.1?

**Comment by atalman** [comment]
Closing this since https://github.com/pytorch/pytorch/pull/122616 fixes it in nightly and cherry-pick submitted for 2.3.1

**Comment by atalman** [comment]
Validated with 2.3.1:
```
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch, torchdata
>>> print(torch.__version__)
2.3.1
>>> print(torchdata.__version__)
0.7.1
>>> 
```
