### ISSUE TITLE
Give the possibly to get back normal `Tensor`s as `MaskedTensor` gradients

### ISSUE THREAD

**Issue by nowtryz** [pytorch/pytorch#124964]
### 🚀 The feature, motivation and pitch

I am working on a project that requires to manipulate a lot of masks and some math should only be applied on the masked values as part of a loss function. `MaskedTensor` comes ideal in this situation but is not supported by all functions in the backward pass.

For instance, let's say we want to perform a sliding window:
```pycon
>>> import torch
>>> from torch.masked import as_masked_tensor
>>> t = torch.randn(3, 3, requires_grad=True).unfold(1, 2, 1)
>>> m = as_masked_tensor(t, torch.ones(t.shape, dtype=torch.bool))
.../torch/masked/maskedtensor/core.py:156: UserWarning: The PyTorch API of MaskedTensors is in prototype stage and will change in the near future. Please open a Github issue for features requests and see our documentation on the torch.masked module for further information about the project.
  warnings.warn(("The PyTorch API of MaskedTensors is in prototype stage "
.../torch/masked/maskedtensor/core.py:161: UserWarning: It is not recommended to create a MaskedTensor with a tensor that requires_grad. To avoid this, you can use data.clone().detach()
  warnings.warn("It is not recommended to create a MaskedTensor with a tensor that requires_grad. "
>>> m.sum().backward()
.../torch/masked/maskedtensor/core.py:299: UserWarning: unfold_backward is not implemented in __torch_dispatch__ for MaskedTensor.
If you would like this operator to be supported, please file an issue for a feature request at https://github.com/pytorch/maskedtensor/issues with a minimal reproducible code snippet.
In the case that the semantics for the operator are not trivial, it would be appreciated to also include a proposal for the semantics.
  warnings.warn(msg)
Traceback (most recent call last):
  File ".../torch/_tensor.py", line 513, in backward
    return handle_torch_function(
  File "...s/torch/overrides.py", line 1621, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File ".../torch/masked/maskedtensor/core.py", line 274, in __torch_function__
    ret = func(*args, **kwargs)
  File ".../torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File ".../torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
TypeError: Multiple dispatch failed for 'torch._ops.aten.unfold_backward.default'; all __torch_dispatch__ handlers returned NotImplemented:
  - tensor subclass <class 'torch.masked.maskedtensor.core.MaskedTensor'>
For more information, try re-running with TORCH_LOGS=not_implemented
```

In my case, I'd don't really care about the mask in the backward pass and would be happy with a 0 gradient. Hence, would it be possible to allow to chose betwen keeping a `MaskedTensor` or filling the masked gradients with 0?

This feature could be a change in `maskedtensor/core.py` and `maskedtensor/creation.py` like `keep_masked_gradient=True`
https://github.com/pytorch/pytorch/blob/87079f5e91be657743cfc6df74b519b68a8b0205/torch/masked/maskedtensor/core.py#L220-L233

```diff
--- /torch/masked/maskedtensor/core.py
@@ -221 +221 @@
-    def _from_values(data, mask):
+    def _from_values(data, mask, keep_masked_gradient=True):
@@ -227,229 +227,232 @@
         @staticmethod 
         def backward(ctx, grad_output):
-             return grad_output, None
+             if keep_masked_gradient:
+                 return grad_output, None
+             else:
+                 return grad_output._masked_data.masked_fill(~grad_output.get_mask(), 0), None 
```

### Alternatives

At the moment, I have an `as_masked_tensor` overload filling missing gradient with 0s in the backward pass:

```python
def as_masked_tensor(data, mask):
    """
    Overload original `torch.masked.as_masked_tensor` to convert masked tensors back to normal tensors in the backward
    pass. Filling missing gradients with 0.
    """
    class Constructor(torch.autograd.Function):
        @staticmethod
        def forward(ctx, data, mask):  # noqa
            return MaskedTensor(data, mask)

        @staticmethod
        def backward(ctx, grad_output):  # noqa
            return grad_output._masked_data.masked_fill(~grad_output.get_mask(), 0), None 

    result = Constructor.apply(data, mask)
    return result
```

cc @ezyang @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by mikaylagawarecki** [comment]
cc @cpuhrsch

**Comment by albanD** [comment]
This is an interesting question. I'm not sure we want to add such option as that would actually change the semantic of the MaskedTensor (which is the whole reason we use it over sparse!).

Your as_masked_tensor is definitely the right workaround if you want a separate semantic here.


You can also add support for any op that you need using this: https://github.com/pytorch/pytorch/blob/6b54f9d3e1b30cf270bf17ab47291a470edeac42/torch/masked/maskedtensor/_ops_refs.py#L219
For your particular case, if you are happy with non-masked semantic, it should be pretty easy to materialize the Tensor with zeros and call func() again to do the original computation.

**Comment by nowtryz** [comment]
Ok, I'll try adding some operators, it doesn't seem so difficult. I just have to understand how the masked tests work.

For my project I'll probably keep my as_masked_tensor  as I think keeping a masked tensor through the rest of my pipeline may causes issues
