### ISSUE TITLE
PyTorch Distributed Load Updates or Returns `state_dict`

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#125096]
### 🚀 The feature, motivation and pitch

Torch distributed checkpoint `load_state_dict` (https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/state_dict_loader.py#L20)
updates the passed in `state_dict` (and returns it). This function is deprecated in torch 2.3 in favor of `load` (https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/state_dict_loader.py#L48) which neither returns nor updates the passed in `state_dict`. Instead, it only calls `load_state_dict` on Stateful elements in the specified `state_dict`. 

Unfortunately, this new API is greatly limiting. For example, in [Composer's](https://github.com/mosaicml/composer) state_dict passed for checkpointing, we also store various RNG tensors in a dict for determinism. In order to use the new API, we have to rewrap everything in a Stateful class, which is a somewhat pointless abstraction. Instead, we prefer to receive a loaded `state_dict` and then manually call `load_state_dict` on appropriate subitems. 

Can we modify `load` to update the passed in `state_dict`? This would entail adding:
```
state_dict[key] = statetful_sd[key]
```
after https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/state_dict_loader.py#L172-L177

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @LucasLLC

**Comment by fegin** [comment]
@LucasLLC Any thought about this request?

**Comment by LucasLLC** [comment]
Sorry for the delay! Taking a look

**Comment by mvpatel2000** [comment]
> @mvpatel2000 this makes a lot of sense to me. Would you like to submit a PR or should I?

@LucasLLC if you can submit a PR that would be awesome :)

**Comment by mihir-db** [comment]
@LucasLLC bumping this if possible -- id love to include in torch 2.3.1 since `load_state_dict` is deprecated

**Comment by fegin** [comment]
It's unclear to me if this ask fit the cherry-pick requirement as this is not a major bug fix.

**Comment by dasoto** [comment]
I've been using _load_state_dict_from_keys to recover the rest of keys that are not the model. Not sure why this implementation have this kind of limitations
