### ISSUE TITLE
CUDA memory summary in FSDP all_gather causes excessive noise.

### ISSUE THREAD

**Issue by cbalioglu** [pytorch/pytorch#125025]
### 🐛 Describe the bug

~~In PyTorch 2.2 and later, even when the distributed debug level is not set explicitly,~~ these lines in FSDP's [_optim_utils.py](https://github.com/pytorch/pytorch/blob/main/torch/distributed/fsdp/_optim_utils.py#L1511) and [_debug_utils.py](https://github.com/pytorch/pytorch/blob/main/torch/distributed/fsdp/_debug_utils.py#L60) cause excessive noise in log outputs; especially for large model training. Any reason why they are logged at the `logging.WARNING` level and not `logging.DEBUG`?

### Versions

PyTorch 2.2, PyTorch 2.3

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

**Comment by fegin** [comment]
We can change it to debug, if that cause issues.

**Comment by cbalioglu** [comment]
@fegin I think it makes sense to change them to debug. They are not "warnings", so it is a bit misleading to report them so.

**Comment by fegin** [comment]
@cbalioglu Changing the logging level to debug does not make sense to me as these are already guarded with distributed logging level. For the profiling result, it is only on when the distributed logging level is DETAIL. https://github.com/pytorch/pytorch/pull/126362 changes the level to info.

**Comment by awgu** [comment]
@xlim1996 This should only affect the logging, not any of the base functionality. Is that your concern?
