### ISSUE TITLE
How can i train my model with torchrun on multiple GPUs but without DDP?

### ISSUE THREAD

**Issue by kakaxi-liu** [pytorch/pytorch#125012]
## Issue description

I want use command "torchrun" to train my model on multiple GPU, but I need to set data parallel=1 in order to use sequence parallel. What should I do?

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

**Comment by wconstab** [comment]
This is probably something you could post on pytorch-discuss instead of as a GitHub issue. Also, when you post there you could help by proving more info about what you are doing - model code, etc.
