### ISSUE TITLE
TOR901 lint is too aggressive

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#125050]
https://hud.pytorch.org/pr/pytorch/pytorch/124872#24274836004 gives the following:

<img width="1256" alt="image" src="https://github.com/pytorch/pytorch/assets/5652049/8ba7ab8f-5be6-487c-9089-dde3c0018b91">

We should only tell people to use torch.library._scoped_library in PyTorch tests (i.e. under the test/* folder). This usage of the torch.library API in the snippet (i.e. using torch.library torch/distributed/_tensor/_collective_utils.py) is allowed.

cc @kit1980

**Comment by kit1980** [comment]
This should resolve it: https://github.com/pytorch/pytorch/pull/125082

But actually I've realized as it's an internal-only TorchFix rule, TorchFix can probably look at the file name and ignore if not /test. But this will require some work, as usually for TorchFix rules file name is not a part of the rule input.
