### ISSUE TITLE
[C++/pytorch] data loading and working with complex data structures with the C++ frontend

### ISSUE THREAD

**Issue by zeryx** [pytorch/pytorch#12506]
Hey folks! I have a question about data manipulation with the C++ frontend. I'm aware that it's right now in alpha, however, I was wondering what the ideal pathway would be for data ingestion in an online, production-ready environment.

For example, in python I could easily use numpy and PIL to load an image into a ndarray, and convert that directly into a torch tensor.

```python
img = Image.open(filename)
 img = np.asarray(img)
img = torch.from_numpy(np.asarray(img))
```

What would the equivalent of the above look like using the C++ frontend? I was thinking that you would probably want to use openCV, but I'm unclear as to how to migrate a openCV `Mat` representation to something that the C++ frontend could ingest easily.

Thanks so much for all your hard work, I'm always amazed by what the pytorch team has been able to accomplish, and this 1.0 release is shaping up to be a great one.

**Comment by soumith** [comment]
you could load the image using OpenCV, and then get the loaded cv::Mat as a Tensor.

cc: @goldsborough who had some example code lying around to show torch::from_blob(cv::mat)

**Comment by zeryx** [comment]
I've discovered through finding a snippet via the forums that allow for image loading via openCV directly (wooh!), I'm still a bit unclear how to extract data _from_ an at::tensor into a blob form compatible with opencv for rendering, or serializing as an image, but baby steps...

https://gist.github.com/zeryx/526dbc05479e166ca7d512a670e6b82d

**Comment by goldsborough** [comment]
Hi @zeryx! This should be pretty smooth with our API. You already did a pretty good job with the loading part. This is how I would write it:

```cpp
at::Tensor tensor_image = torch::from_blob(image.data, {1, 3, image.rows, image.cols}, at::kByte);
tensor_image = tensor_image.to(at::kFloat);
```

Here, I assume that `image.data` is 8-bit byte values. The `to(at::kFloat)` will convert the 8-bit values into 32-bit floating points just as if you wrote `static_cast<float>(b)` where `b` is a byte -- just in case that wasn't clear. If `image.data` is already floats, you can just write `at::kFloat` in place of `at::kByte` and skip the conversion of course. What's __super important__ to know is that `from_blob` does not take ownership of the data! It only interprets the data as a tensor, but doesn't store the data itself. It's easy to fix this if you want to, by calling `.clone()` on the tensor, since that will incur a copy of the data such that the resulting tensor will indeed own its data (which means the original `cv::Mat` can be destroyed and the cloned tensor will live on).

On the other side, it's actually easier. You can use `tensor.data<T>()` to access a tensor's underlying data through a `T*`. For example, `tensor_image.data<float>()` would give you a `float*`. If you want a more raw `void*` because you're dumping the raw data somewhere else, there's also a `data_ptr()` method that gives you a raw byte pointer.

Let me know if this helps.

**Comment by goldsborough** [comment]
For reference, this is the C++ extension I had in my slides at the devcon:

```
#include <opencv2/opencv.hpp>
#include <torch/extension.h>

at::Tensor compute(at::Tensor x, at::Tensor w) {
  cv::Mat input(x.size(0), x.size(1), CV_32FC1, x.data<float>());
  cv::Mat warp(3, 3, CV_32FC1, w.data<float>());

  cv::Mat output;
  cv::warpPerspective(input, output, warp, {64, 64});

  return torch::from_blob(output.ptr<float>(), {64, 64}).clone();
}
```

I think the order in which you want to convert is inverted, but maybe it's useful :)

**Comment by zeryx** [comment]
Thanks for the help there @goldsborough! Very interesting point about tensor ownership - I assumed it was a consumer, but that would be counter to many pytorch principles wrt tensors heh.  

On the output end, say I pass in a `cv::Mat` like what I did above, and perform some kind of operation to the tensor. If I wanted to get access to that tensor and use it to render as an RGB image, would I interact with that `cv::Mat` I used to load & process the input image in the first place since the blob was never cloned? Or is there another process here to convert the `at::Tensor` back into something I could pass to openCV to save or view the output as an image?

**Comment by nicolone** [comment]
You have to split the interleaved bgr channels inside the `cv::Mat` to match the dimensions expected by the tensor:
```
    cv::Mat image = cv::imread("example.jpg");
    // std::cout << image << std::endl;

    //we have to split the interleaved channels
    cv::Mat bgr[3]; // destination array
    cv::split(image, bgr);
    cv::Mat channelsConcatenated;
    vconcat(bgr[0], bgr[1], channelsConcatenated);
    vconcat(channelsConcatenated, bgr[2], channelsConcatenated);
   
    cv::Mat channelsConcatenatedFloat;
    channelsConcatenated.convertTo(channelsConcatenatedFloat, CV_32FC3);

    std::vector<int64_t> dims{1, static_cast<int64_t>(image.channels()),
                              static_cast<int64_t>(image.rows),
                              static_cast<int64_t>(image.cols)};

    at::TensorOptions options(at::kFloat);
    at::Tensor tensor_image =
        torch::from_blob(channelsConcatenated.data, at::IntList(dims), options);
    // std::cout << tensor_image << std::endl;

    // Execute the model and turn its output into a tensor.
    auto output = module->forward({tensor_image}).toTensor();
```

**Comment by bhack** [comment]
It could be interesting to see also an example where we have the input already on the GPU memory like with https://github.com/NVIDIA/DALI/issues/92

**Comment by bhack** [comment]
See also https://github.com/NVIDIA/DALI/pull/240#issuecomment-432565492 and the thread from https://github.com/NVIDIA/DALI/pull/247#issuecomment-433423196. Currently all the samples are from pytorch python API

**Comment by bhack** [comment]
There was also an evaluation for Dali in https://github.com/pytorch/vision/issues/608

**Comment by bhack** [comment]
Now we have also a stride parameter https://github.com/pytorch/pytorch/issues/13898

**Comment by bhack** [comment]
@goldsborough You are suggesting directly `torch::from_blob(image.data, {1, 3, image.rows, image.cols}, at::kByte);` but is it required to re-arrange chanell as in the @nicolone example?

**Comment by nicolone** [comment]
The rearrange is only necessary to comply with a numpy image but it is no
general requirement for the conversion to a tensor. You should be aware of
how you expect the different color channels to end up in the tensor. OpenCV
represents images as BGR bytes with stride = tensor(height, width, BGR) while
numpy represents color images as (RGB, height, width). The final dimensions
of (1,3,width, height) in the example code suggest that a conversion to a
numpy image is intended.

>

**Comment by bhack** [comment]
@nicolone So se it seems mainly that if the model was trained, as in 90% of cases, from a "standard" pytorch python pipeline at inference you need to arrange the cv::Mat as you have suggested for c++ inference right?

**Comment by bhack** [comment]
Also could the fresh stride parameter  require only the RGB BGR channel reordering step?

**Comment by nicolone** [comment]
I assumed the OpenCV image (at least the float one) to be continuous, so
there was no need for adding strides. In general you have to take them into
account and they can be computed with the help of the cv::Mat step. You
can't skip the other steps though, because they are due to the order of the
dimensions.

**Comment by bhack** [comment]
So cause in majority of the CPU cases that Mat could be continuous In the case you want to inference on a GPU model from a CPU Mat probably it is better to load `torch::from_blob(image.data, {1, image.rows, image.cols, 3}, at::kByte);` then move to cuda and make a permute and float conversion on the GPU tensor. 
For the BGR to Rgb I don't know if in the pipeline it will be faster to make a preliminar Cvtcolor on CPU before `from_blob` or also this could be moved to an ATen op on the Cuda Tensor.

**Comment by bhack** [comment]
@goldsborough How we can be sure with the C++ API that the data is CPU ready when we execute  `cv::Mat output(sizes, CV_32FC1, new_tensor.data<float>())`?

**Comment by Con-Mi** [comment]
Hey, 

I submitted an issue that I encountered when I was using the C++ api.
I was unable to reproduce the same results when I run a python version of my trained model 
against a model that I load in C++ with the api. More details on how to reproduce this issue I have submitted on the link:
https://github.com/pytorch/pytorch/issues/14273

**Comment by Maslino** [comment]
> You have to split the interleaved bgr channels inside the `cv::Mat` to match the dimensions expected by the tensor:
> 
> ```
>     cv::Mat image = cv::imread("example.jpg", cv::IMREAD_COLOR);
>     // std::cout << image << std::endl;
> 
>     //we have to split the interleaved channels
>     cv::Mat bgr[3]; // destination array
>     cv::split(image, bgr);
>     cv::Mat channelsConcatenated;
>     vconcat(bgr[0], bgr[1], channelsConcatenated);
>     vconcat(channelsConcatenated, bgr[2], channelsConcatenated);
>    
>     cv::Mat channelsConcatenatedFloat;
>     channelsConcatenated.convertTo(channelsConcatenatedFloat, CV_32FC3);
> 
>     std::vector<int64_t> dims{1, static_cast<int64_t>(image.channels()),
>                               static_cast<int64_t>(image.rows),
>                               static_cast<int64_t>(image.cols)};
> 
>     at::TensorOptions options(at::kFloat);
>     at::Tensor tensor_image =
>         torch::from_blob(channelsConcatenated.data, at::IntList(dims), options);
>     // std::cout << tensor_image << std::endl;
> 
>     // Execute the model and turn its output into a tensor.
>     auto output = module->forward({tensor_image}).toTensor();
> ```

this line:
```
torch::from_blob(channelsConcatenated.data, at::IntList(dims), options);
```
should be
```
torch::from_blob(channelsConcatenatedFloat.data, at::IntList(dims), options);
```

**Comment by Msabih** [comment]
> For reference, this is the C++ extension I had in my slides at the devcon:
> 
> ```
> #include <opencv2/opencv.hpp>
> #include <torch/extension.h>
> 
> at::Tensor compute(at::Tensor x, at::Tensor w) {
>   cv::Mat input(x.size(0), x.size(1), CV_32FC1, x.data<float>());
>   cv::Mat warp(3, 3, CV_32FC1, w.data<float>());
> 
>   cv::Mat output;
>   cv::warpPerspective(input, output, warp, {64, 64});
> 
>   return torch::from_blob(output.ptr<float>(), {64, 64}).clone();
> }
> ```
> 
> I think the order in which you want to convert is inverted, but maybe it's useful :)

This is a great example. Is it possible to pass GPU pointer to the tensor and use cv::cuda::GpuMat and cv::cuda::warpPerspective  so that the data remains on GPU ?

**Comment by Coderx7** [comment]
Thanks a lot everyone, this issue is really a great source of information for libtorch! 
I'm having a bit of an issue here. the input image type ic 8CU3 . and its converted into the tensor like this : 
```cpp
at::Tensor tensor_image = torch::from_blob(img.data, { img.rows, img.cols, 3 }, at::kByte);
tensor_image = tensor_image.to(at::kFloat);
```
and now I want to get back the iamge and visualize it : 
```cpp
cv::Mat output_mat(cv::Size{ width, height }, CV_32FC3, tensor.data_ptr<float>());
```
but this is not right! so I tried this : 
```cpp
tensor = tensor.toType(at::kInt);
cv::Mat output_mat(cv::Size{ width, height }, CV_8UC3, tensor.data_ptr<int>());
```
which again doesnt work as the image is not displayed correctly
What should I do? 
(The documentation/tutorials for libtorch is nearly non existant, the amount of information that recides here alone, is more than the whole official documentation for libtorch! when it comes to dealing with images and networks feedings!)

**Comment by CoinCheung** [comment]
> For reference, this is the C++ extension I had in my slides at the devcon:
> 
> ```
> #include <opencv2/opencv.hpp>
> #include <torch/extension.h>
> 
> at::Tensor compute(at::Tensor x, at::Tensor w) {
>   cv::Mat input(x.size(0), x.size(1), CV_32FC1, x.data<float>());
>   cv::Mat warp(3, 3, CV_32FC1, w.data<float>());
> 
>   cv::Mat output;
>   cv::warpPerspective(input, output, warp, {64, 64});
> 
>   return torch::from_blob(output.ptr<float>(), {64, 64}).clone();
> }
> ```
> 
> I think the order in which you want to convert is inverted, but maybe it's useful :)

Hi,

I use the setup.py method to compile the extension, and I met the message of `opencv2/opencv.hpp: No such file or directory`, would you please tell me how should I configure the `setup.py` to use third-party libraries ?
