### ISSUE TITLE
weird torch.diag behavior on variable

### ISSUE THREAD

**Issue by ncullen93** [pytorch/pytorch#1250]
Does torch.diag work on variables without calling .data ? I'm getting weird behavior:

```
x = Variable(torch.ones((5,5)))
print(torch.diag(x)) # prints diag
print(torch.diag(x,2)) # still prints middle diag
print(torch.diag(x.data, 2)) # prints correct diag
```

Seems like a bug to me, since other ops work fine on variables. At the least it's confusing. If so, Point me in the right direction and I'll certainly try fixing it :)

**Comment by soumith** [comment]
The bug is here: https://github.com/pytorch/pytorch/blob/master/torch/autograd/_functions/linalg.py#L13

It needs to call: `return input.diag(self.diagonal_idx)` and similarly in the backward it has to call `return grad_output.diag(self.diagonal_idx)`

**Comment by ncullen93** [comment]
i submitted a PR but if you want to handle it another way feel free. thanks for the help.
