### ISSUE TITLE
404 on torch.inference_mode doc page

### ISSUE THREAD

**Issue by alat-rights** [pytorch/pytorch#125059]
### 📚 The doc issue

The page for [torch.autograd.grad_mode.inference_mode](https://pytorch.org/docs/stable/generated/torch.autograd.grad_mode.inference_mode.html) is still up

However, the page for [torch.inference_mode](https://pytorch.org/docs/stable/generated/torch.inference_mode.html) is down, leaving a dead link on Google and my bookmarks :'( .

![image](https://github.com/pytorch/pytorch/assets/54920181/f5b5c753-52eb-406b-97e6-98ab23a22fe5)

### Suggest a potential alternative/fix

Restore the page for [torch.inference_mode](https://pytorch.org/docs/stable/generated/torch.inference_mode.html)

cc @svekars @brycebortree @ezyang @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
This is expected, since this is the same function aliased on different namespaces, we de-duplicated all of them.
If you look for inference_mode, everything should point to the still exiting page and nothing should point you to a 404!

Or is there a way to reach that 404 through some link in the doc page?

**Comment by alat-rights** [comment]
I see!

No, I didn't get there from an internal link.

I got to the page via the top Google result for "pytorch inference mode".

I think it's a little unfortunate that the top result on both Google and DDG for inference_mode is currently a dead link, but obviously if it's costly to maintain the page then that makes sense :)

**Comment by albanD** [comment]
Ho I can see!
cc @svekars did we properly run the script to update indexing on google after the 2.3 release?

**Comment by soulitzer** [comment]
Top Google result for "pytorch inference mode" seems correct now. Closing as expected.
