### ISSUE TITLE
Broken Docker Image on dockerhub

### ISSUE THREAD

**Issue by lharri73** [pytorch/pytorch#125094]
### 🐛 Describe the bug

It appears that the docker image on [dockerhub](https://hub.docker.com/r/pytorch/pytorch/tags) for 2.3.0 cuda11.8 & cuda12.1, both runtime and devel are all malformed. 
1. They target arm64 instead of amd64 like all previous images
2. The copy from `/opt/conda` only copied ~300Mb where it normaly copies several Gb. 

### Versions

N/A. Image will not run. 

cc @ezyang @gchanan @zou3519 @kadeng

**Comment by malfet** [comment]
Hmm, indeed it is the case:
```
$ docker run --rm -it pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime bash
Unable to find image 'pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime' locally
2.3.0-cuda12.1-cudnn8-runtime: Pulling from pytorch/pytorch
Digest: sha256:cc14d1be87739710ca4e14c344e5d336b4dafde40df1a02cc5ac5c265301868c
Status: Downloaded newer image for pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime

WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested

exec /usr/bin/bash: no such file or directory
```

@atalman can you please fix it ASAP and let's try to figure out later how it happened?

**Comment by janvdp** [comment]
Hi @lharri73, as a temporary workaround I'm using: "ghcr.io/pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime" 

Maybe it helps...

**Comment by atalman** [comment]
@janvdp, @malfet  the images in ghcr.io and pytorch/pytorch should be exactly the same here is the log:

```
pytorch/pytorch           2.3.0-cuda11.8-cudnn8-runtime   3578e171db9e   4 days ago     1.18GB
ghcr.io/pytorch/pytorch   2.3.0-cuda11.8-cudnn8-runtime   3578e171db9e   4 days ago     1.18GB
ghcr.io/pytorch/pytorch   2.3.0-cuda11.8-cudnn8-devel     d0edb1392485   4 days ago     9.05GB
pytorch/pytorch           2.3.0-cuda11.8-cudnn8-devel     d0edb1392485   4 days ago     9.05GB
ghcr.io/pytorch/pytorch   2.3.0-cuda12.1-cudnn8-runtime   994d45086c44   4 days ago     1.18GB
pytorch/pytorch           2.3.0-cuda12.1-cudnn8-runtime   994d45086c44   4 days ago     1.18GB
pytorch/pytorch           2.3.0-cuda12.1-cudnn8-devel     c270f91fbe3e   4 days ago     9.24GB
ghcr.io/pytorch/pytorch   2.3.0-cuda12.1-cudnn8-devel     c270f91fbe3e   4 days ago     9.24GB
```

Here is the validation workflow for these images:
https://github.com/pytorch/builder/actions/runs/8821461020/job/24217375234#step:11:57

Please note failure you see in the validation workflow is caused by this issue, still open:
https://github.com/pytorch/pytorch/issues/116696

**Comment by atalman** [comment]
Amd64 images uploaded:

<img width="1296" alt="Screenshot 2024-04-29 at 11 21 32 AM" src="https://github.com/pytorch/pytorch/assets/7563158/0e7ee14d-5523-4213-b88a-001e76b0269c">

**Comment by malfet** [comment]
@atalman just curious, what's inside 2.3.0-cuda11.8-cudnn8-runtime arm64 image?

**Comment by atalman** [comment]
@malfet Looks like this is an error. arm 64 images should only be: ``ghcr.io/pytorch/pytorch:2.3.0-runtime``
