### ISSUE TITLE
multithreaded autograd backward doesn't respect autocast dtype context manager

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#125186]
Repro below. It looks like even though `dtype=torch.bfloat16` is specified in the autocast context manager, the intermediates in the backward are getting cast down to `torch.float16` before matmul is invoked in the backward.

One way to tell from running the repro is to look at the profiler output. When multithreading is disabled, I see the following kernel name in the profile:
```
void cutlass::Kernel<cutlass_75_wmma_tensorop_bf16_s161616gemm_bf16_32x32_32x1_nt_align1>(cutlass_75_wmma_tensorop_bf16_s161616gemm_bf16_32x32_32x1_nt_align1::Params)
```

When I enable autograd multithreading:
```
void cutlass::Kernel<cutlass_75_wmma_tensorop_s161616gemm_f16_16x16_128x1_nt_align1>(cutlass_75_wmma_tensorop_s161616gemm_f16_16x16_128x1_nt_align1::Params)
```

The second kernel runs much faster, but is probably the wrong one to use because the inputs are incorrectly in float16 when they should be in bfloat16.

Two datapoints:
(1) The behavior changes when autograd multithreading is disabled
(2) the default dtype used for cuda amp is `float16`, stashed in a threadlocal: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/autocast_mode.cpp#L56

Given those two points, it seems likely that when autograd spawns threads, we aren't properly copying over the threadlocal AMP state from the spawned thread?

```
import torch
from torch.profiler import profile, record_function, ProfilerActivity

m, n, k = 13, 2, 20569856


ENABLE_MULTITHREAD_AUTOGRAD = True


x = torch.rand(k, m, device="cuda")
model = torch.nn.Linear(m, n).to("cuda")

with torch.cuda.amp.autocast(enabled=True, dtype=torch.bfloat16), torch.autograd.set_multithreading_enabled(ENABLE_MULTITHREAD_AUTOGRAD):
    model = torch.nn.Linear(m, n).to("cuda")
    x = torch.rand(k, m, device="cuda")
    out = model(x)
    out_sum = out.sum()
    with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as prof:
        out_sum.backward()
    prof.export_chrome_trace("trace/trace_singlethread.json")
```

cc @ezyang @gchanan @zou3519 @kadeng @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by soulitzer** [comment]
> Given those two points, it seems likely that when autograd spawns threads, we aren't properly copying over the threadlocal AMP state from the spawned thread?

Yup - today the engine automatically replicates TLS state managed by ThreadLocalState() onto the spawned threads. We should have autocast dtype state to also be managed this way.

**Comment by bdhirsh** [comment]
tentatively marking hi-pri since running at a different precision from the user asked for seems bad
