### ISSUE TITLE
Pytorch running on macosx-14.xlarge reports MPS is available when it is not. 

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/pytorch#125197]
### 🐛 Describe the bug

CI fails after checking whether MPS is available (macos-14.xlarge says it is, but it's apparently not), and then tries to load a model - https://github.com/pytorch/torchchat/actions/runs/8856790631/job/24323484380?pr=515

xref: https://github.com/pytorch/torchchat/pull/515

### Versions

This version, in this very repo.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @albanD @kulinseth @DenisVieriu97 @jhavukainen

**Comment by mikekgfb** [comment]
x-ref: https://github.com/pytorch/torchchat/issues/516

**Comment by albanD** [comment]
Can you please share error messages and/or details on how to reproduce this? All the links here point to a private repo.

**Comment by malfet** [comment]
Unassigning myself

**Comment by albanD** [comment]
I see you added module CI, is that because our CI runs on virtual machines?

**Comment by seemethere** [comment]
Going to close this. This is an implementation detail of GitHub hosted runner that we've notified them of and is not a bug in PyTorch.
