### ISSUE TITLE
doc link failure of `torch.compile`

### ISSUE THREAD

**Issue by shaoyuyoung** [pytorch/pytorch#125123]
### 📚 The doc issue

In document: [https://pytorch.org/docs/stable/generated/torch.compile.html#torch.compile](https://pytorch.org/docs/stable/generated/torch.compile.html#torch.compile)
The below link is missing [https://pytorch.org/docs/main/compile/custom-backends.html](https://pytorch.org/docs/main/compile/custom-backends.html)

![image](https://github.com/pytorch/pytorch/assets/100203773/585bdbff-a2fe-41fd-b58d-c3ad7b7a5ba5)

**Comment by shaoyuyoung** [comment]
Maybe this is the right link: [https://pytorch.org/docs/stable/torch.compiler_custom_backends.html](https://pytorch.org/docs/stable/torch.compiler_custom_backends.html)

**Comment by ycaglar** [comment]
> ### 📚 The doc issue
> In document: https://pytorch.org/docs/stable/generated/torch.compile.html#torch.compile The below link is missing https://pytorch.org/docs/main/compile/custom-backends.html
> 
> ![image](https://private-user-images.githubusercontent.com/100203773/326261046-585bdbff-a2fe-41fd-b58d-c3ad7b7a5ba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNDM0MTEsIm5iZiI6MTcxNDM0MzExMSwicGF0aCI6Ii8xMDAyMDM3NzMvMzI2MjYxMDQ2LTU4NWJkYmZmLWEyZmUtNDFmZC1iNThkLWMzYWQ3YjdhNWJhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQyMjI1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2EyZWVlZDI1YTk5OGYxMmZiYjFlMGQ3YzE5MWJhNmRhOWMyN2M0YzI3MzgyMzJlZDBlMWZiZWMzMWE1YzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p54YMJXJVE2BDQ3PUW19HB7bW1M5G6PL5JSWtnctueA)
> 
> ### Suggest a potential alternative/fix
> _No response_

Appears to be a duplicate of #119272

**Comment by shaoyuyoung** [comment]
Sorry for this :(

Got it now
