### ISSUE TITLE
Can't load on rank 0 only with `set_optimizer_state_dict`

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#125177]
### 🐛 Describe the bug

To avoid CPU OOMs, our training library only loads monolithic checkpoints on rank 0 and broadcasts to all other ranks (as PyTorch checkpointing supports). When migrating to the new distributed APIs, 
```
                set_optimizer_state_dict(
                    model=self.model,
                    optimizers=optimizer,
                    optim_state_dict=optim_state_dict,
                    options=StateDictOptions(
                        full_state_dict=self.fsdp_state_dict_type == 'full',
                        strict=strict,
                        cpu_offload=True,
                    ),
                )
```
we hit an error with this approach in the below function:
https://github.com/pytorch/pytorch/blob/ae13c7e593c1032fa3f96f4aa1b3379547a3a9f3/torch/distributed/checkpoint/state_dict.py#L582
In our code, `optim_state_dict` is only non-None on rank-0 as `rank0only` is set to True in PyTorch code. 

Currently, I need to do:
```
optim_state_dict = MagicMock() if optim_state_dict is None else optim_state_dict
```
which is unideal. I think the split function should just not be run if the context manager is rank0only, but I am not sure here

### Versions

Pytorch 2.3

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @LucasLLC

**Comment by fegin** [comment]
@mvpatel2000 Curious, how many nodes/ranks are you using? Also, is the state_dict/optimizer state_dict DTensor based?

**Comment by mvpatel2000** [comment]
> @mvpatel2000 Curious, how many nodes/ranks are you using? Also, is the state_dict/optimizer state_dict DTensor based? I'm also implement the broadcasting feature at this moment. But it will only support DTensor based state_dict/optimizer state_dict.

This is for multiple GPUs (2 is sufficient). 

We currently unit test this with ShardedTensors (as this is the default unless a device mesh is passed in), but I believe it's fine if it's only DTensor

**Comment by fegin** [comment]
@mvpatel2000 I'll close the issue. Feel free to repoen the issue if you need more help.
