### ISSUE TITLE
RuntimeError: Exporting the operator fft_rfftn to ONNX opset version 11 is not supported.

### ISSUE THREAD

**Issue by wchuan163** [pytorch/pytorch#125296]
### 🚀 The feature, motivation and pitch

how to support fft_rfftn  export to ONNX

**Comment by thiagocrepaldi** [comment]
Please provide a full repro script for debug.

For `torch.onnx.export` we are not activelly adding new operators/features as the API is in maintenance mode.

Feel free to try the latest ONNX exporter through `torch.onnx.dynamo_export`
