### ISSUE TITLE
"torch.mm received an invalid combination of arguments"

### ISSUE THREAD

**Issue by outlace** [pytorch/pytorch#1252]
I get this error:
`TypeError: torch.mm received an invalid combination of arguments - got (torch.FloatTensor, Variable), but expected one of:
 * (torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (torch.FloatTensor source, torch.FloatTensor mat2)
`
when matrix multiplying a raw Tensor with a Variable (which is a Tensor). Both are of type FloatTensor. I don't understand, I thought variables should do everything a tensor can do since it's just a thin wrapper.

**Comment by albanD** [comment]
They can, but a function takes either Tensors or Variables as input but not a mix of them.
You should wrap your tensor into a Variable before using it.
