### ISSUE TITLE
I have installed pytorch from source, then how to install caffe2?

### ISSUE THREAD

**Issue by lilichu** [pytorch/pytorch#12522]
I install pytorch from source:
```
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
python setup.py install
```
I try to use caffe2, then I run:
`cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"`
It print False
I find if I install caffe2, I should run:
```
git clone https://github.com/pytorch/pytorch.git && cd pytorch
git submodule update --init --recursive
python setup.py install
```
But it is similiar to pytorch. I have run `python setup.py install` when I install pytorch. What should I do?

**Comment by EricLi404** [comment]
Hello, I also encountered this problem, how did you solve it？  tkx

**Comment by lilichu** [comment]
@EricLi404  I thinkl that caffe2 is also installed when I install pytorch.
I run 
`cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"`
it return Success.
