### ISSUE TITLE
torch.inference_mode documentation not availble 

### ISSUE THREAD

**Issue by MostHumble** [pytorch/pytorch#125216]
### 📚 The doc issue

I can't seem to find the documentation for inference_mode, it used to be : https://pytorch.org/docs/stable/generated/torch.inference_mode.html
but it's not accessible anymore.

cc @svekars @brycebortree

**Comment by cpuhrsch** [comment]
Marked this for triage review to discuss inference_mode vs. nograd and the right module label for this.

**Comment by soulitzer** [comment]
Related https://github.com/pytorch/pytorch/issues/125059

**Comment by jbschlosser** [comment]
Closing as duplicate.
