### ISSUE TITLE
Investigate Error "f capturable=True, params and state_steps must be CUDA or XLA tensors" when nn module inlining enabled. 

### ISSUE THREAD

**Issue by laithsakka** [pytorch/pytorch#125393]
REPO:
enable nn module inlinining then run
TORCHDYNAMO_INLINE_INBUILT_NN_MODULES=1 PYTORCH_TEST_WITH_DYNAMO=1 python test/test_quantization.py -k test_qat_embeddingbag_linear

PYTORCH_TEST_WITH_DYNAMO=1 TORCHDYNAMO_INLINE_INBUILT_NN_MODULES=1 python test/test_quantization.py  -k test_resnet_base

nine total failures with this message, check: https://hud.pytorch.org/pr/125354
cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @vincentqb @janeyx99 @crcrpar @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by laithsakka** [comment]
when running in isolate those tests pass!
<img width="1027" alt="Screenshot 2024-05-02 at 8 18 53 AM" src="https://github.com/pytorch/pytorch/assets/13970752/2e9c3265-3e31-4666-b68e-9d8f5711365e">
<img width="1048" alt="Screenshot 2024-05-02 at 8 18 57 AM" src="https://github.com/pytorch/pytorch/assets/13970752/40998d28-8997-4146-977b-c050997ec8f6">

**Comment by laithsakka** [comment]
note: those only fails when dynamo is enabled on the test

**Comment by janeyx99** [comment]
What is module inlining? 

This looks like an optimizer error that happens when capturable is flipped on but the state is not ready to be captured.

**Comment by laithsakka** [comment]
I had offline chat with @mlazos  he is already working on this or something very close to this, he said he will take over

**Comment by laithsakka** [comment]
@mlazos  @anijain2305  this is fixed with recent Lazos changes

**Comment by laithsakka** [comment]
fixed by https://github.com/pytorch/pytorch/pull/125826
