### ISSUE TITLE
Run mkldnn matmul in SPR for bf32

### ISSUE THREAD

**Issue by akote123** [pytorch/pytorch#125386]
In torch 2.3.0, With Reference to https://github.com/pytorch/pytorch/commit/0ae952db76e5da1ebfbcaff39897a5b42606e67b, want to mkldnn bf32 matmul in sapphire rapids but the default path is mkl. How I can enable this in SPR?

cc: @zhuhaozhe , @jgong5 

Thank you

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal @frank-wei

**Comment by jgong5** [comment]
> In torch 2.3.0, With Reference to [0ae952d](https://github.com/pytorch/pytorch/commit/0ae952db76e5da1ebfbcaff39897a5b42606e67b), want to mkldnn bf32 matmul in sapphire rapids but the default path is mkl. How I can enable this in SPR?

After you do `torch.set_float32_matmul_precision("medium")`, the mkldnn path will be used for float32 matmul computed with bf16.

**Comment by leslie-fang-intel** [comment]
I think this issue should be addressed per the above comment
