### ISSUE TITLE
Memory usage increasing after first batch (possibly not freeing some potentially free memory)

### ISSUE THREAD

**Issue by MatthiasKohl** [pytorch/pytorch#1253]
This may be related to issue #1184 but I believe there is something else to it:
I am working on version `v0.1.11`, using micro batches: split mini-batches into smaller batches and calculate/backprop loss in each micro batch, accumulating it over the mini batch. I noticed multiple times that my code goes out of memory after several micro batches. This seems strange to me as each micro batch should require the same amount of memory. Maybe there is something I don't fully understand here, so if anyone can explain it to me, I'd be happy !

Anyway, I tried to look into it a bit and attached is the smallest code snippet I came up with demonstrating my problem (around 100 lines).
Essentially, I am training a network on images, using micro-batches to reduce memory. However, after the first (and sometimes second) micro-batch, the memory usage increases and then stays the same after further micro-batches.

When using a functional approach for the mini and micro batches, the memory usage does not increase the same way, so I don't believe that this has to do with the fact that there may be 'lazy' memory freeing involved (freeing only when necessary).

[torch_memory.zip](https://github.com/pytorch/pytorch/files/919384/torch_memory.zip)

**Comment by MatthiasKohl** [comment]
Also, is there a utility to see which tensor requires how much memory on GPU and if it can be free'd etc ? That would be really useful to investigate this kind of issue in the future. The actual code I want to debug here is much more complex and I have no idea which part requires how much memory, to know what I could do to optimize memory usage...

**Comment by apaszke** [comment]
It's not related, unless you keep holding on to Variables you won't ever need again (it's better to only save their `.data` once they're not needed). There's no such utility right now. Can you please paste your code into a gist instead of attaching a zip?

**Comment by soumith** [comment]
gist of his code https://gist.github.com/d5710d24833f6369663438e977b6ff40

**Comment by MatthiasKohl** [comment]
Thanks for creating the gist. and of course, the input images can be easily replaced by random tensors of shape `(3, 224, 224)` if you don't have a directory of images available. I created a new gist for this, if it's easier for you: https://gist.github.com/MatthiasKohl/45163b8c13c52c495d8c25dc7d22016f

**Comment by MatthiasKohl** [comment]
I've looked into this a bit further and first found that simply running my (larger) code in an iPython kernel rather than directly using Python, the memory usage is quite different. So I assume that the garbage collection (or tracking memory allocations) are different in iPython vs Python. Unfortunately, I cannot easily demonstrate this because the smaller code I posted does not behave differently in Python vs iPython.

I then simply used `gc.collect()` at the end of each micro-batch and my memory consumption dropped significantly (at least 4x) in a way that I don't go out of memory anymore. This is surprising to me since I assumed that any non-referenced Variable/Tensor should be overwritten sooner or later, so `gc.collect()` shouldn't have any impact. Anyway, if I find a more concise example of this behaviour, I will update you.

**Comment by apaszke** [comment]
I looked into it and it seems all good to me. Your new gist uses 651MB in the first version and 642MB in the second. The increased memory usage comes from the the way Python uses scopes -- all iterations run in the global one, so when you compute the second one `loss`, `out`, etc. are still alive until they're overwritten, thus increasing the peak memory usage. If you add `del out, loss, train_in, labels_in` after `loss.backward()` the memory usage will go down to 642MB. In the second case, the variables go out of scope once the function returns, so the memory is freed before the second iteration starts.
