### ISSUE TITLE
Changing the state of the Dataset without re-instantiating the DataLoader

### ISSUE THREAD

**Issue by DavideA** [pytorch/pytorch#12536]
Hi,
I'd like an enlightment on a problem I'm facing with DataLoaders.
The issue is that - everything else fixed (random seeds included) - I get different training behaviors if I use nb_workers=0 or nb_workers>0.

After a few trials, I suspect the reason could be the way I change the state of a Dataset. Basically, instead of using different DataLoaders for training and validation, I use one instance only and I change the state of the underlying Dataset. Here's an example on MNIST:

```
class MNIST(Dataset):

    def __init__(self):

        super(MNIST, self).__init__()

        self.train_dataset = datasets.MNIST(self.path, train=True, download=True, transform=None)
        self.val_dataset = datasets.MNIST(self.path, train=False, download=True, transform=None)
        self.cur_dataset = None

        # Initialize currents
        self.cur_len = None

    def train(self):
        self.cur_dataset = self.train_dataset
        self.cur_len = len(self.train_dataset)

    def val(self):
        self.cur_dataset = self.val_dataset
        self.cur_len = len(self.val_dataset)

    def __len__(self):
        return self.cur_len

    def __getitem__(self, i):
       return self.cur_dataset[i]
```

and then use `dataloader.dataset.train()` and `dataloader.dataset.val()` to switch between the two modes. Is this a bad choice?
(The code above is not the actual code I'm using, it's just an example)

I'm using pytorch 0.4.0

Thanks,
D

**Comment by DavideA** [comment]
So this scheme does work with 0 workers, right?

**Comment by SsnL** [comment]
Or use the shared data structures like `mp.Array`.

**Comment by ngimel** [comment]
Closing due to age
