### ISSUE TITLE
Eigen version has two overload for __hadd with CUDA >= 9.0 and CUDA_ARCH >= 6.0

### ISSUE THREAD

**Issue by fmder** [pytorch/pytorch#12545]
When build on Windows with CUDA 9.2 and a cuda arch > 6.0. The current submodule version has a bug with ``__hadd`` having two potential overloads as stated here: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1526

Commit eigenteam/eigen-git-mirror@f59336cee358f92b959de6a0daf07c4ab2318022 fixes this.

**Comment by fmder** [comment]
Unfortunately, commit eigenteam/eigen-git-mirror@f59336c is not in the 3.3 branch. To build, I had to fetch and cherry-pick the commit.

**Comment by vishwakftw** [comment]
Are you still facing issues after the fix?

**Comment by fmder** [comment]
I just built successfully! Thanks
