### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NiharJani2002** [pytorch/pytorch#125442]
### 🐛 Describe the bug

Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error: 
	(null)
	Internal Error (0000000e:Internal Error)
	<AGXG13XFamilyCommandBuffer: 0x3601ec380>
    label = <none> 
    device = <AGXG13XDevice: 0x11f3b5400>
        name = Apple M1 Pro 
    commandQueue = <AGXG13XFamilyCommandQueue: 0x11f3b8800>
        label = <none> 
        device = <AGXG13XDevice: 0x11f3b5400>
            name = Apple M1 Pro 
    retainedReferences = 1

### Versions

<img width="777" alt="image" src="https://github.com/pytorch/pytorch/assets/84491997/df9a8543-dca1-4b6b-bf2d-29ec5b831fe0">

**Comment by drisspg** [comment]
There is not enough detail in this issue
