### ISSUE TITLE
dynamo_export fails for for NVIDIA NeMo framework classes decorated with wrapt package

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#125462]
### 🐛 Describe the bug

dynamo_export fails for NVIDIA NeMo framework classes decorated with wrapt package (and their forward method is replaced with FunctionWrapper object (https://wrapt.readthedocs.io/en/master/index.html). 
The error looks like this: 
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/builtin.py", line 1547, in call_getattr
    return obj.var_getattr(tx, name)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/nn_module.py", line 246, in var_getattr
    unimplemented(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/exc.py", line 212, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: class property - AudioToMelSpectrogramPreprocessor FunctionWrapper

Here is a short repro: 
```
import torch
from nemo.core.classes import typecheck

from nemo.collections.asr.models import EncDecCTCModelBPE

model = EncDecCTCModelBPE.from_pretrained(model_name="stt_en_conformer_ctc_small")

model.to(device="cpu").freeze()
model = model.eval()

example_input = model.input_module.input_example(max_batch=2)

typecheck.set_typecheck_enabled(enabled=False)
options = torch.onnx.ExportOptions(dynamic_shapes=True)

with torch.no_grad():
    _ = torch.onnx.dynamo_export(model,
                                 *example_input,
                                 export_options=options)


### Versions

This error is still in PyTorch nightly build.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by borisfom** [comment]
NeMo toolkit can be installed like this: 
pip install --extra-index-url https://pypi.ngc.nvidia.com nemo_toolkit[all]

**Comment by borisfom** [comment]
Note: I was able to work around this issue by calling torch.export.export(strict=False) first - but that route has its own issues I filed. 
I think there either should be a similar 'strict' parameter to dynamo_export, or it should always be non-strict.

**Comment by borisfom** [comment]
@titaiwangms : any news on this?

**Comment by titaiwangms** [comment]
Hi @borisfom, this error breaks at dynamo level. For this case, we usually suggest users to try torch.export.export first (This is also our next step that migrates torch.export.export in to onnx.dynamo_export), because without dynamo captures FX graph, we don't have graph to convert to onnx, and as you suggested, there is another issue with that route. I would wait for dynamo/export team to support FunctionWrapper.

**Comment by borisfom** [comment]
Thanks for the update!

**Comment by justinchuby** [comment]
Closing this. If the dynamo issue persists, I would open another one against torch.export.
