### ISSUE TITLE
Function request: np.corrcoef

### ISSUE THREAD

**Issue by ncullen93** [pytorch/pytorch#1254]
Update: the scipy.stats.pearsonr part of this issue is now tracked in https://github.com/pytorch/pytorch/issues/50333. This issue is for implementing np.corrcoef.

**ORIGINAL ISSUE BELOW**

Hey all,

I implemented bare bones versions of `np.corrcoef` and `scipy.stats.pearsonr`. These are two functions I use all the time, so I often have to convert back and forth to numpy for this. It'd be nice to have these incorporated, although I only see the need for the forward pass.

Clearly, they need to be in a more suitable format (inheriting from Function?) and need some tests, so any advice & code review there is appreciated. The functions are found below and in this [gist](https://gist.github.com/ncullen93/58e71c4303b89e420bd8e0b0aa54bf48)

```python
def pearsonr(x, y):
    """
    Mimics `scipy.stats.pearsonr`

    Arguments
    ---------
    x : 1D torch.Tensor
    y : 1D torch.Tensor

    Returns
    -------
    r_val : float
        pearsonr correlation coefficient between x and y
    
    Scipy docs ref:
        https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html
    
    Scipy code ref:
        https://github.com/scipy/scipy/blob/v0.19.0/scipy/stats/stats.py#L2975-L3033
    Example:
        >>> x = np.random.randn(100)
        >>> y = np.random.randn(100)
        >>> sp_corr = scipy.stats.pearsonr(x, y)[0]
        >>> th_corr = pearsonr(torch.from_numpy(x), torch.from_numpy(y))
        >>> np.allclose(sp_corr, th_corr)
    """
    mean_x = torch.mean(x)
    mean_y = torch.mean(y)
    xm = x.sub(mean_x)
    ym = y.sub(mean_y)
    r_num = xm.dot(ym)
    r_den = torch.norm(xm, 2) * torch.norm(ym, 2)
    r_val = r_num / r_den
    return r_val

def corrcoef(x):
    """
    Mimics `np.corrcoef`

    Arguments
    ---------
    x : 2D torch.Tensor
    
    Returns
    -------
    c : torch.Tensor
        if x.size() = (5, 100), then return val will be of size (5,5)

    Numpy docs ref:
        https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html
    Numpy code ref: 
        https://github.com/numpy/numpy/blob/v1.12.0/numpy/lib/function_base.py#L2933-L3013

    Example:
        >>> x = np.random.randn(5,120)
        # result is a (5,5) matrix of correlations between rows
        >>> np_corr = np.corrcoef(x)
        >>> th_corr = corrcoef(torch.from_numpy(x))
        >>> np.allclose(np_corr, th_corr.numpy())
        # [out]: True
    """
    # calculate covariance matrix of rows
    mean_x = torch.mean(x, 1)
    xm = x.sub(mean_x.expand_as(x))
    c = xm.mm(xm.t())
    c = c / (x.size(1) - 1)

    # normalize covariance matrix
    d = torch.diag(c)
    stddev = torch.pow(d, 0.5)
    c = c.div(stddev.expand_as(c))
    c = c.div(stddev.expand_as(c).t())

    # clamp between -1 and 1
    # probably not necessary but numpy does it
    c = torch.clamp(c, -1.0, 1.0)

    return c
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry @rgommers @heitorschueroff

**Comment by szagoruyko** [comment]
looks like you can add these to torch.nn.functional, along with gradcheck tests.

**Comment by internetvandingen** [comment]
The corresponding feature branch was never merged, could this feature still be added?
@vishwakftw

**Comment by mruberry** [comment]
We would accept a PR adding torch.corrcoef modeled after NumPy's np.corrcoef. 

I filed a separate issue for the scipy.stats.pearsonr request here: https://github.com/pytorch/pytorch/issues/50333. Slightly editing this issue to just track torch.corrcoef.

**Comment by mruberry** [comment]
Bumping priority based on emotes.

**Comment by gchanan** [comment]
> looks like you can add these to torch.nn.functional, along with gradcheck tests.

Note we aren't going to do this, but will put in the torch. package.

**Comment by zakajd** [comment]
For anyone interested in Spearman's rank correlation coefficient and finding this issue, here is working code for 1-D vectors.
Result is identical with `scipy.stats.spearmanr`

```python
def _get_ranks(x: torch.Tensor) -> torch.Tensor:
    tmp = x.argsort()
    ranks = torch.zeros_like(tmp)
    ranks[tmp] = torch.arange(len(x))
    return ranks

def spearman_correlation(x: torch.Tensor, y: torch.Tensor):
    """Compute correlation between 2 1-D vectors
    Args:
        x: Shape (N, )
        y: Shape (N, )
    """
    x_rank = _get_ranks(x)
    y_rank = _get_ranks(y)
    
    n = x.size(0)
    upper = 6 * torch.sum((x_rank - y_rank).pow(2))
    down = n * (n ** 2 - 1.0)
    return 1.0 - (upper / down)
```

**Comment by morawi** [comment]
> For anyone interested in Spearman's rank correlation coefficient and finding this issue, here is working code for 1-D vectors.
> Result is identical with `scipy.stats.spearmanr`
> 
> ```python
> def _get_ranks(x: torch.Tensor) -> torch.Tensor:
>     tmp = x.argsort()
>     ranks = torch.zeros_like(tmp)
>     ranks[tmp] = torch.arange(len(x))
>     return ranks
> 
> def spearman_correlation(x: torch.Tensor, y: torch.Tensor):
>     """Compute correlation between 2 1-D vectors
>     Args:
>         x: Shape (N, )
>         y: Shape (N, )
>     """
>     x_rank = _get_ranks(x)
>     y_rank = _get_ranks(y)
>     
>     n = x.size(0)
>     upper = 6 * torch.sum((x_rank - y_rank).pow(2))
>     down = n * (n ** 2 - 1.0)
>     return 1.0 - (upper / down)
> ```

Does not accord ... see this:
```
a = np.array([0, 0, 0, 1, 1, 1, 1])
b = np.arange(7)

print('SpearmanR SCIPY: ', stats.pearsonr(a, b))
print('SpearmanR Torch like ', spearman_correlation(torch.tensor(a, dtype=torch.float32),
                                                    torch.tensor(b, dtype=torch.float32)) )

SpearmanR SCIPY:  (0.8660254037844386, 0.011724811003954649)
SpearmanR Torch like  tensor(1.)
```

**Comment by morawi** [comment]
Anyone who bumps here, [AudTorch](https://pypi.org/project/audtorch/) has it. 
```

import torch
from scipy import stats
import numpy as np
import audtorch

a = np.array([0, 0, 0, 1, 1, 1, 1])
b = np.arange(7)
a_torch = torch.tensor(a, dtype=torch.float32)
b_torch = torch.tensor(b, dtype=torch.float32)

audtorch_pearson = audtorch.metrics.functional.pearsonr(a_torch, b_torch, batch_first=True)
print('SpearmanR SCIPY: ', stats.pearsonr(a, b))
print('SpearmanR AudTorch', audtorch_pearson)

SpearmanR SCIPY:  (0.8660254037844386, 0.011724811003954649)
SpearmanR AudTorch tensor([0.8660])

```
Yet,  `AudTorch` does not report the p-value (0.011 above).

**Comment by TonyYaoMSU** [comment]
> Spearman

In your code, you are using pearsonr instead of spearmanr
