### ISSUE TITLE
Allow sm90a in TORCH_CUDA_ARCH_LIST

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#125413]
# Summary

This PR: https://github.com/pytorch/pytorch/pull/125204 requires building for architecture sm90a and not sm90.
I set this via '9.0.a' and yet this is still building for sm90.

cc @malfet @seemethere @ptrblck @msaroufim

**Comment by Aidyn-A** [comment]
@youkaichao added a regex parser for 9.0.a in #123243, were you able to build it with sm90a?

**Comment by drisspg** [comment]
Is the syntax ` TORCH_CUDA_ARCH_LIST="9.0a"`? This is what I tried locally which wasnt working

**Comment by youkaichao** [comment]
My code change will avoid the error, but not sure if the argument passing to nvcc is right:

>     if(arch_name MATCHES "^([0-9]\\.[0-9]a?(\\([0-9]\\.[0-9]\\))?)$")
>       set(arch_bin ${CMAKE_MATCH_1})
>       set(arch_ptx ${arch_bin})

**Comment by drisspg** [comment]
Ill take a look

**Comment by drisspg** [comment]
https://github.com/pytorch/pytorch/pull/125523
