### ISSUE TITLE
[RFC] Removing Nervana GPU

### ISSUE THREAD

**Issue by mratsim** [pytorch/pytorch#12540]
NervanaGPU is currently included as a [third-party module](https://github.com/pytorch/pytorch/tree/c2a57d082d36f30f32d5c4cc7147ab57ce2c3097/third_party). However the repository is not under active development anymore and has not been modified since 3 years ago.

Checking the commit that added it, it was [this one](https://github.com/pytorch/pytorch/commit/9201cdd029aa820ebc92c71bd4f6d4105163ca80) for the optimized GEMM kernel that was developed at Nervana.

There are 2 kernels of interest in Nervana's work:

### Nervana GEMM

While Nervana GEMM is extremely tuned for Maxwell Architecture, but with Volta and Turing, GPUs are now offering Tensor Cores that are much faster. I expect that Nvidia tuned their GEMM implementation since then.

Alternatives:
- CuBLAS
- [Nervana Maxas](https://github.com/NervanaSystems/maxas) which isolated the GEMM kernel and is a much smaller library than the full NervanaGPU, so it's probably possible to clone and maintain it.
- Honorary mention: [Nvidia Cutlass](https://github.com/NVIDIA/cutlass), which achieves 90% speed of CuBLAS and supports Tensor cores without assembly.
- Nvidia's TensorRT for inference.

### Nervana convolution kernel

(If used, but i don't think it is)

The main appeal is the winograd kernel [discussed extensively here](https://github.com/soumith/convnet-benchmarks/issues/93) but it's [not even in NervanaGPU repo but in Neon repo.](https://github.com/NervanaSystems/nervanagpu/issues/25#issuecomment-203168418).
Furthermore it has been integrated into CuDNN with torch NCHW layout instead of Neon's CHWN layout and convolution was probably one of Nvidia focus in the past 2 years.

### Conclusion

Should the benchmarks show that alternatives to Nervana achieves the same speed on current GPU for a wide range of input size (as tensor cores are currently very restrictive), I think NervanaGPU code should be dropped to save on code, maintenance, dependencies and build options.

**Comment by soumith** [comment]
this should definitely be deleted. Would you mind sending a PR for it? If not we can route it to one of the core devs
