### ISSUE TITLE
add nvidia driver version to environment collection script

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#12555]
https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py currently misses collecting nvidia driver version.
Would be useful to have that.

**Comment by vishwakftw** [comment]
It seems to be there here https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py#L254 .

Are you expecting something else?

**Comment by soumith** [comment]
nevermind, my bad.
