### ISSUE TITLE
`Dockerfile` should set the `syntax` directive to v1

### ISSUE THREAD

**Issue by polarathene** [pytorch/pytorch#125526]
### 🚀 The feature, motivation and pitch

The project `Dockerfile` should be updated to use `syntax=docker/dockerfile:1` which has been available since Dec 2018 and still endorsed as best practice officially by Dockers docs in 2024.

https://github.com/pytorch/pytorch/blob/bfd5bb0c44dfaef36961eaa67008df4d6134199d/Dockerfile#L1

### Alternatives

Leave as-is, but it's already been 5 years and BuildKit is default since Docker v23 (Feb 2023).

### Additional context

This is a minor change, effectively housekeeping but still worth migrating away from the current experimental tag IMO.

For reference, I [proposed this change via PR](https://github.com/pytorch/pytorch/pull/125525#issue-2278644416) with linked resources to justify the change confidently to maintainers. Unfortunately PyTorch has a CLA signing process that I'm not motivated to proceed with, so an existing contributor or maintainer will need to take that PR/commit and apply it themselves.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by SandishKumarHN** [comment]
@polarathene would you mind I take the PR, test and commit to the repo ?

**Comment by polarathene** [comment]
@SandishKumarHN no problem, go for it! I appreciate it :)
