### ISSUE TITLE
Unable to pip install pytorch-0.4.0

### ISSUE THREAD

**Issue by twmht** [pytorch/pytorch#12559]
I can only install 0.4.1 by the following

```
pip install http://download.pytorch.org/whl/cu92/torch-0.4.1-cp27-cp27mu-linux_x86_64.whl
```

but I want to downgrade to 0.4.0, so I tried

```
pip install http://download.pytorch.org/whl/cu92/torch-0.4.0-cp27-cp27mu-linux_x86_64.whl
```

but it gave me 403 forbidden,

any idea?

**Comment by soumith** [comment]
We dont ship 0.4.0 with CUDA 9.2. You can pick a link for 0.4.0 here: https://pytorch.org/get-started/previous-versions/

**Comment by suresh96458** [comment]
I want to install 0.4.0 with cuda10 but i am unable to find the right wheel file can you add the link to the appropriate wheel file?

**Comment by hontarenkoYana** [comment]
> I want to install 0.4.0 with cuda10 but i am unable to find the right wheel file can you add the link to the appropriate wheel file?

Did you find solution for this problem?

**Comment by tamireiny** [comment]
I also would like to install pytorch 0.4.0, for windows 10, 64 bit, python 2.7, cuda 10.1
Any solution?
