### ISSUE TITLE
linux aarch64: CI: test_mkldnn started failing with oneDNN3.4+ACL24.04 version upgrade

### ISSUE THREAD

**Issue by snadampal** [pytorch/pytorch#125548]
### 🐛 Describe the bug

`test_mkldnn` started failing with the oneDNN and ACL version upgrades. Assertion is coming from ACL, `src/core/NEON/kernels/NEReverseKernel.cpp` but not sure if the issue is with ACL kernel or due to incorrect tensor being passed from oneDNN or the above framework.

working nightly: `2.4.0.dev20240430` --> this is with oneDNN 3.3.6 + ACL 23.08
failing nightly: `2.4.0.dev20240502` --> this is with oneDNN 3.4 + ACL 24.04

How to reproduce
`python test/run_test.py --include test_mkldnn --verbose`

Error log:
```
est_mkldnn.py::TestMkldnnCPU::test_conv_transpose1d_cpu terminate called recursively
terminate called after throwing an instance of 'std::runtime_error'
Fatal Python error: Aborted

  what():  in run_reverse src/core/NEON/kernels/NEReverseKernel.cpp:109: the values of the axis tensor must be within [-rank, rank-1].
Current thread 0x0000f55a1cd50420terminate called recursively
PASSED [3.3639s]                                                                                                                                                                           [ 25%]
test_mkldnn_fusion.py::TestMkldnnFusion::test_conv_unary_fusion_nnc Got exit code -6 (SIGIOT)
Stopping at first consistent failure
The following tests failed consistently: ['test/test_mkldnn.py::TestMkldnnCPU::test_conv_transpose1d_cpu']
test_mkldnn 1/1 failed!
test_mkldnn 1/1 failed!
```

### Versions

Platform: aarch64 linux
OS: Ubuntu 22.04

working nightly: `2.4.0.dev20240430` --> this is with oneDNN 3.3.6 + ACL 23.08
failing nightly: `2.4.0.dev20240502` --> this is with oneDNN 3.4 + ACL 24.04

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @malfet

**Comment by malfet** [comment]
I propose we roll back the charge until fix is known, as it will affect 2.4 users, wouldn't it?

**Comment by snadampal** [comment]
Hi @malfet , what are the timelines for 2.4? My first attempt is to fix the failures within this week, if not possible, I agree with you that we will have to roll back the change.

**Comment by Xia-Weiwen** [comment]
cc @Guobing-Chen  @vpirogov

**Comment by atalman** [comment]
Hi @snadampal Timeline for 2.4 is posted here: https://dev-discuss.pytorch.org/t/pytorch-release-2-4-0-call-for-features/2051 
```
M1: Call for features (5/2/2024)
M2: All PRs landed in PyTorch repo / Feature Submission Closed (6/7/24) - DEADLINE
M3.1: Release branch cut (6/10/24)
M3.2: Release first RC1 Binary for PyTorch Core (6/11/24)
M3.3: Domain libraries cut RC Branch (6/13/24)
M4: Release branch finalized, Announce final launch date, Feature classifications published (week of 7/1/24)
M5: External-Facing Content Finalized (7/19/24)
M6: Release Day (7/24/24)
```
I agree we should revert oneDNN change if we can't fix this issue within few days

**Comment by atalman** [comment]
@malfet @snadampal here is the PR that should trigger aarch64 CI on all mkldnn changes: https://github.com/pytorch/pytorch/pull/125599/files

**Comment by Xia-Weiwen** [comment]
Hi @snadampal. I saw you said "not sure if the issue is with ACL kernel or due to incorrect tensor being passed from oneDNN or the above framework." So, the root cause is yet to be found and we are not sure the fix will be in oneDNN or PyTorch itself. Is that correct?

**Comment by snadampal** [comment]
I have root-caused the issue to axis tensor values being passed incorrect to ACL. The checks have been added newly in ACL 23.11 to meet TFLite compliance, as part of this https://review.mlplatform.org/c/ml/ComputeLibrary/+/10335 commit on ComputeLibrary.
If I relax the bounds check for this tensor, `test_mkldnn` tests are passing. next I'm trying to understand how strict the checks should be and why is it different for PyTorch.

https://github.com/ARM-software/ComputeLibrary/blob/main/src/core/NEON/kernels/NEReverseKernel.cpp#L109
```
template <typename T>
void run_reverse(
    const Window &window, const ITensor *input, const ITensor *axis, ITensor *output, bool use_inverted_axis)
{
    unsigned int axis_bit = 0;
    const int    rank     = input->info()->num_dimensions();

    for (unsigned int i = 0; i < axis->info()->dimension(0); ++i)
    {
        int axis_i = *(reinterpret_cast<const int *>(axis->buffer()) + i);

        // The values of axis tensor must be between [-rank, rank-1].
        if ((axis_i < -rank) || (axis_i >= rank))
        {
            ARM_COMPUTE_ERROR("the values of the axis tensor must be within [-rank, rank-1].");
        }
```

**Comment by Xia-Weiwen** [comment]
@snadampal So, you are trying to modify the test case? And after that, we can land PR #122472 as is?

**Comment by snadampal** [comment]
Hi @Xia-Weiwen , checking on the test case and also ACL front, will keep you posted. yes, we need to reland the oneDNN3.4 PR as soon this issue is addressed.

**Comment by snadampal** [comment]
Hi @Xia-Weiwen , David from Arm has raised this onednn PR https://github.com/oneapi-src/oneDNN/pull/1903 to fix the issue. Here is the same PR for rls-v3.4 branch: https://github.com/oneapi-src/oneDNN/pull/1904.  David is running few more integration tests, meanwhile Could you please review it? 
I have updated the linux-aarch64 CI for ACL version before you land the oneDNN module update PR, so that we can run the CI successfully.

**Comment by Xia-Weiwen** [comment]
@snadampal Thanks for the update. I saw both PR's were approved.

**Comment by snadampal** [comment]
yes @Xia-Weiwen , all the PRs are ready. I see this is the sequence for the next steps
1. merge https://github.com/oneapi-src/oneDNN/pull/1904
2. tag oneDNN3.4.2
3. ideep update for the new oneDNN tag
4. PyTorch ideep submodule update to new commit
Whenever you're ready with step#4, please let me know, I will request Andrey, Nikita to merge linux-aarch64 CI /CD PRs for ACL version update.

cc: @atalman , @malfet

**Comment by vpirogov** [comment]
The fix is released in oneDNN [v3.4.2](https://github.com/oneapi-src/oneDNN/releases/tag/v3.4.2).

**Comment by Xia-Weiwen** [comment]
Hi @snadampal I have updated the PR #122472. Please take a look. Since v3.4.2 contains many changes to v3.4.1, we will need to rerun validation on CPU.

**Comment by snadampal** [comment]
thanks @vpirogov  and @Xia-Weiwen, Will run some sanity tests.

**Comment by snadampal** [comment]
thanks everyone, all the required PRs are merged and CI tests are passing now.
