### ISSUE TITLE
Support loading with map_location on xpu backend

### ISSUE THREAD

**Issue by dvrogozh** [pytorch/pytorch#125529]
In relevance to ongoing effort to support XPU backend (#114723). Today's (e10b2ba357f7998edaec5a181352c02ae503ccb9) PyTorch XPU path does not support loading with `map_location='xpu'`. Can be reproduced with:
```
$ cat test.py
import tempfile
import torch

print('torch.__version__: ' + torch.__version__)
print('torch.xpu.is_available(): ' + str(torch.xpu.is_available()))

with tempfile.NamedTemporaryFile() as f:
    x = torch.rand(2)
    print('x.device: ' + str(x.device))
    torch.save(x, f)

    f.seek(0)
    x2 = torch.load(f, map_location="xpu")
    print('x2.device: ' + str(x2.device))
```
Will produce (on the Linux system with Intel GPU):
```
$ python3 test.py
torch.__version__: 2.4.0a0+gite10b2ba
torch.xpu.is_available(): True
x.device: cpu
Traceback (most recent call last):
  File "/home/dvrogozh/git/test.py", line 13, in <module>
    x2 = torch.load(f, map_location="xpu")
  File "/home/dvrogozh/git/pytorch/torch/serialization.py", line 1071, in load
    return _load(opened_zipfile,
  File "/home/dvrogozh/git/pytorch/torch/serialization.py", line 1492, in _load
    result = unpickler.load()
  File "/home/dvrogozh/git/pytorch/torch/serialization.py", line 1462, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/dvrogozh/git/pytorch/torch/serialization.py", line 1436, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/dvrogozh/git/pytorch/torch/serialization.py", line 1359, in restore_location
    return default_restore_location(storage, map_location)
  File "/home/dvrogozh/git/pytorch/torch/serialization.py", line 435, in default_restore_location
    raise RuntimeError("don't know how to restore data location of "
RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with xpu)
```

cc @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @albanD

**Comment by dvrogozh** [comment]
I've tried to implement this feature - see PR #125530.

**Comment by albanD** [comment]
Thanks for the request.
That sounds fair to me but we should really implement this in a way that is making the code more generic, not adding more if-statements along.

btw @guangyey should we add you to the cc list for module: xpu in https://github.com/pytorch/pytorch/issues/24422 to make sure you get cc-ed on these issues? Or should I add someone else in cc there?

**Comment by dvrogozh** [comment]
> That sounds fair to me but we should really implement this in a way that is making the code more generic, not adding more if-statements along.

I will gladly make changes to the PR #125530 I've posted if there is a consensus between maintainers on the direction. Please, start reviewing the PR and add notes on what you would like to see changed.

**Comment by guangyey** [comment]
> Thanks for the request. That sounds fair to me but we should really implement this in a way that is making the code more generic, not adding more if-statements along.
> 
> btw @guangyey should we add you to the cc list for module: xpu in #24422 to make sure you get cc-ed on these issues? Or should I add someone else in cc there?

Thanks, @albanD could you help add @gujinghui @EikanWang @fengyuan14, and @guangyey to cc list for `module: xpu`.
