### ISSUE TITLE
Compile failed on tag v1.0rc1

### ISSUE THREAD

**Issue by LoSealL** [pytorch/pytorch#12558]
## 🐛 Bug

Failed with error:
>pytorch/aten/src/ATen/native/sparse/cuda/SparseCUDATensorMath.cu(366): error: identifier "copy_sparse_to_sparse_" is undefined
[ 65%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_accuracy_op.cu.o
1 error detected in the compilation of "/tmp/tmpxft_00000215_00000000-6_SparseCUDATensorMath.cpp1.ii".
CMake Error at caffe2_gpu_generated_SparseCUDATensorMath.cu.o.Release.cmake:279 (message):
  Error generating file
  pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/sparse/cuda/./caffe2_gpu_generated_SparseCUDATensorMath.cu.o

>caffe2/CMakeFiles/caffe2_gpu.dir/build.make:1246: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/sparse/cuda/caffe2_gpu_generated_SparseCUDATensorMath.cu.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/sparse/cuda/caffe2_gpu_generated_SparseCUDATensorMath.cu.o] Error 1

>CMakeFiles/Makefile2:3690: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 libshm gloo c10d THD'

## To Reproduce

1. git ck v1.0rc1 && git submodule update
1. python setup.py install
1. wait and see...

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0rc1
 - OS (e.g., Linux): ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.6.5
 - CUDA/cuDNN version: 9.0/7.1
 - GPU models and configuration: TITAN-X
 - Any other relevant information:

**Comment by SsnL** [comment]
did you clean your previous build?

**Comment by PeterHuang2015** [comment]
I could not even see v1.0rc branch on Github currently.

**Comment by LoSealL** [comment]
@PeterHuang2015 Are you sure? [RC1](https://github.com/pytorch/pytorch/tree/v1.0rc1)

**Comment by LoSealL** [comment]
@SsnL Do I need to uninstall previouly installed pytorch package?

**Comment by SsnL** [comment]
Yes. Do pip uninstall twice, and also `python setup.py clean`

**Comment by PeterHuang2015** [comment]
> @PeterHuang2015 Are you sure? [RC1](https://github.com/pytorch/pytorch/tree/v1.0rc1)

Thx, I only looked at branches, not tags, thx for the lesson~

BTW, is there any way to compile pytorch without caffe2? `python setup.py install` is easy to use but one may get lost if it failed to compile.

**Comment by LoSealL** [comment]
@SsnL Alright, that works, thank you!

**Comment by PeterHuang2015** [comment]
@SsnL Hi Tongzhou, out of curiosity, could u pls explain why the trick works? The build process may reuse some legacy components by mistake or there are other causations? Thx!(sorry for posting in the close issue)

**Comment by ezyang** [comment]
Yes, it's probably picking up a header/library from the old install.
