### ISSUE TITLE
MAX-Autotune Compilation Time Regression Due To Added MM Configs

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#125687]
### 🐛 Describe the bug

With https://github.com/pytorch/pytorch/pull/125000 we went from 12 -> 29 mm configs. @henryhu6 saw a 5% speedup on a diffusion model, and there were other nice speedups such as 9% on SAM inference. This led to the following training and inference speedups and compilation time changes.

Training:

Comp time:

![image](https://github.com/pytorch/pytorch/assets/11477974/fa383229-f42c-4d91-98ef-944a709dad39)

Perf:

![image](https://github.com/pytorch/pytorch/assets/11477974/3b233d6f-092f-4898-b544-ae1994473ca9)

Inference:

Comp time:

![image](https://github.com/pytorch/pytorch/assets/11477974/e2063de4-2198-4caa-a86b-35c70e15ed25)

Perf:

![image](https://github.com/pytorch/pytorch/assets/11477974/00149337-ff55-4dd3-a577-dba8688a36e5)

We do parallelize mm compilation. However it is done with threading currently. It might be aided with additional processes, although for internal use that would be pending https://github.com/pytorch/pytorch/pull/124682/. 

In the future maybe we'll have better cost models or other mechanisms to speed up mm config choice but they dont exist currently. Maybe this is motivation for tiered max-autotune, similar to -02, -03 ? 

In any case filing this for discussion.

### Versions

master

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by nmacchioni** [comment]
I personally think we need to be more selective with the templates we pick for max-autotune-gemm. Autotuning can already take quite long depending on the workload, I feel like making this even longer is not the way to be heading.

**Comment by eellison** [comment]
While this could be further improved, it is at least partially addressed now since I pruned the set of configs. Training time for HF now at 213 seconds, it was at 222 seconds.
