### ISSUE TITLE
Duplicate gloo in thirdparty and caffe2/contrib/gloo

### ISSUE THREAD

**Issue by PeterHuang2015** [pytorch/pytorch#12560]
## 🐛 Failed compiling of the current master branch

So, which gloo should we use? The one in caffe2 seems being incomplete while there's another one in thridparty folder.

## To Reproduce
1. Build from source
1. Current master branch
1. CUDA 10
1. Ubuntu 16.04

## Expected behavior

[ 76%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/contrib/gloo/allreduce_ops_gpu.cc.o

## Additional context
```
header file not found
pytorch/caffe2/contrib/gloo/allreduce_ops_gpu.cc:6:39: fatal error: gloo/cuda_allreduce_bcube.h
```

**Comment by soumith** [comment]
the files in `contrib/gloo/` are bindings for gloo, not the actual gloo library itself.

**Comment by PeterHuang2015** [comment]
> the files in `contrib/gloo/` are bindings for gloo, not the actual gloo library itself.

Thx soumith!
