### ISSUE TITLE
Declarations.yaml cleanup

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#12562]
Based on notes from @ezyang, @zdevito and @gchanan.

We'd like Declarations.yaml to be the single, externally visible API that all consumers, both internal and external, go through. Up until now, it has been designed under the assumption that only internal consumers make use of it, and that we can refactor these consumers when we wish to change Declarations.yaml. However, we have quickly gotten into a state where even our internal consumers are unmaintainable. This issue tracks a list of changes we'd like to apply to Declarations.yaml.

Meta-principle: the metadata for a type primarily consists of the type string (e.g., `f(Tensor x, Tensor y) -> Tensor`). However, there may be some other metadata.

- [x] Stop hard-coding the list of arguments that `TensorOptions` expands into. Instead, the list of kwargs a TensorOptions expands into should be specified only once and used everywhere.
- [ ] De-C++-ify our type syntax. This means no more putting `Tensor &` in an input type (so basically, drop `type` and use `dynamic_type` only). Our type system should be C++/Python-agnostic. To determine if something has a reference or not, should be determined if the parameter in question is an input or output parameter, which should be part of the type string.
- [x] Add optional to the type syntax. @wanchaol is working on this
- [ ] Replace `method_of` with a simple list of `method` and/or `function`.
- [x] Eliminate `python_default_init` entirely; once optional is supported, any arguments which have "complex" default values can simply specify the argument as optional, and then let the kernel compute the default argument itself
- [x] Unify `default_init` and `init`. We think we have two only because TH and native had different paths, accidentally.
- [x] Augment type strings with alias sets, perhaps with exclamation marks. This could be used to remove `output` annotations. This will be handled by the JIT team.
- [x] Eliminate `is_type_dispatched`. @gchanan is working on this
- [ ] Eliminate `buffers`. These would be replaced as outputs of "inner" native functions, which are the actual differentiable functions. Blocked on adding named outputs.
- [x] Add named outputs, ala `f(Tensor x) -> (Tensor out, Tensor buf)`. This helps the clarity of defining derivatives for multi-return functions.
- [ ] Eliminate `method_prefix_derived`, since we have eliminated most broadcasting from Type
- [ ] Eliminate `mode`
- [ ] Eliminate `inplace`, instead inferring it from the name of a function. Put this inference function in one place and make everyone use it.
- [ ] Eliminate `device_guard`, no one actually needs it anymore

**Comment by t-vi** [comment]
> Replace method_of with a simple list of method and/or function.
This means eventually all of THNN ends up in torch, as it's ported to native?

Also, is there something to be done about operators? Declarations.yaml doesn't seem to contain anything on them (e.g. __mul__ in Python).

**Comment by ezyang** [comment]
Yeah. Actually, a good first step is to just codegen out all of the wrapping code from native to THNN, but still use the native mechanism to generate the operators.

Re `__mul__`, I don't actually know exactly how this works. But I guess if it's not in Declarations.yaml, we must be binding it by hand Python-side. I don't think we have plans to change this, but maybe we should?

**Comment by ezyang** [comment]
I just now updated this ticket with all the refactorings that have been carried out, based eyeballing Declarations.yaml. So we're in pretty good shape. The biggest one is expunging C++ from `type` and co. cc @cpuhrsch is that happening at some point?

**Comment by gchanan** [comment]
@ezyang that's not planned to happen.  The latest view of this (based on discussions between myself and @zdevito) is that the cost/benefit of doing that kind of conversion is too high.  Instead, we should view `Declarations.yaml` as being what drives generation of `VariableType` and everything else should ideally be driven by schemas.

**Comment by ngimel** [comment]
Closing due to age
