### ISSUE TITLE
Error adding tensor and scalar tensor

### ISSUE THREAD

**Issue by outlace** [pytorch/pytorch#1256]
In numpy I can do something like this:
IN:     x = np.array([[1,2,3,4]]) 
IN:     y = np.array([[1]])
IN:     x + y
OUT: array([[2, 3, 4, 5]])

In PyTorch I try doing something similar using torch.add and it complains the tensors are of inconsistent size. It would be nice if it could just infer that a 1x1 Tensor should be treated as a scalar and added to each element in the (non-scalar) Tensor.

**Comment by apaszke** [comment]
It's on the roadmap (see #491). For now, you can do `x + y.expand_as(x)`

**Comment by krstp** [comment]
Any tip to a related issue? See comments at: https://github.com/pytorch/pytorch/issues/13404
