### ISSUE TITLE
Does Torch Script support GPU inference?

### ISSUE THREAD

**Issue by junjin8433** [pytorch/pytorch#12563]
### When using the new featured torch script vis tracing (torch.jit.trace), I found that no matter where the model was, it will be loaded onto the CPU. Thus, I'm wondering whether the gpu inference is supported, if yes, how can I put the loaded model onto GPU?

I found the 'DANGER' in the description of torch.jit.load, which says: 

![image](https://user-images.githubusercontent.com/15881885/46796051-3abf7780-cd7e-11e8-93ec-fc59a65fc759.png)

**Comment by soumith** [comment]
After you load the trace, you can call `.cuda()` on it, and then it'll run on GPU

**Comment by soumith** [comment]
@bhack it's not, but a `::to` is being added in https://github.com/pytorch/pytorch/pull/12710 which will enable it for C++ interfaces.
