### ISSUE TITLE
aten.sort inductor support

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#125633]
### 🚀 The feature, motivation and pitch

Triton supports sort. We should lower to it in inductor, especially because it is used as part of jagged tensors. 

Repro here: https://gist.github.com/eellison/c6489319a217d7e18b98e8b238dd8f44

Current, unfused aten.sort codegen: https://gist.github.com/eellison/36f0c3e6025360315dd67932461ff11b

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by tgalkovskyi** [comment]
Note that while sort is available in triton, it has version that omits indices from the output (and thus only returns sorted values): https://github.com/openai/triton/blob/bb7ef1508fc67f07a0b40bc5dc5d8ec41f916197/python/triton/language/standard.py#L369

while the argsort variant has been proposed but not added yet to triton: https://github.com/openai/triton/issues/3698#issuecomment-2067681396
