### ISSUE TITLE
tensor to numpy?

### ISSUE THREAD

**Issue by lilichu** [pytorch/pytorch#12566]
hi!
the tensor contains `device`, how to transfer tensor to numpy(not contains device)??
```
tensor([-0.1186, -0.0981, -0.0003, -0.0473,  0.0426, -0.0932,  0.1017, -0.0646,
        -0.0661,  0.0430], device='cuda:0'))]

```

**Comment by albanD** [comment]
Hi,

Please use the [forum](https://discuss.pytorch.org/) to ask questions, github issues are for bug/feature only.

Numpy only support cpu, so send the tensor to the cpu with `.cpu()` then call `.numpy()` on it to get a numpy array.

**Comment by lilichu** [comment]
thanks！
