### ISSUE TITLE
Printing: mismatch result with numpy in pytorch 0.4

### ISSUE THREAD

**Issue by mravanelli** [pytorch/pytorch#12578]
I noticed a weird behavior when using torch.linspace.  Please take a look into the following code, where I compare the output of pytorch and numpy for different number of steps:

```python
import torch
import numpy as np
import sys

mult_factor=0.00002


# Torch
print('11 steps')
n_ = torch.linspace(-5.0, 5.0,steps=11)* mult_factor
print(n_)

n_ = np.linspace(-5.0, 5.0,11)* mult_factor
print(n_)
print('.....')

print('12 steps')
n_ = torch.linspace(-5.0, 5.0,steps=12)* mult_factor
print(n_)

n_ = np.linspace(-5.0, 5.0,12)* mult_factor
print(n_)
print('.....')

print('13 steps')
n_ = torch.linspace(-5.0, 5.0,steps=13)* mult_factor
print(n_)

n_ = np.linspace(-5.0, 5.0,13)* mult_factor
print(n_)
print('.....')


print('14 steps')
n_ = torch.linspace(-5.0, 5.0,steps=14)* mult_factor
print(n_)

n_ = np.linspace(-5.0, 5.0,14)* mult_factor
print(n_)
```
If I run the code above I have the following output:
```
11 steps
tensor([-0.0001, -0.0001, -0.0001, -0.0000, -0.0000,  0.0000,  0.0000,  0.0000,
         0.0001,  0.0001,  0.0001])
[-1.e-04 -8.e-05 -6.e-05 -4.e-05 -2.e-05  0.e+00  2.e-05  4.e-05  6.e-05
  8.e-05  1.e-04]
.....
12 steps
tensor([-1.0000e-04, -8.1818e-05, -6.3636e-05, -4.5455e-05, -2.7273e-05,
        -9.0909e-06,  9.0909e-06,  2.7273e-05,  4.5455e-05,  6.3636e-05,
         8.1818e-05,  1.0000e-04])
[-1.00000000e-04 -8.18181818e-05 -6.36363636e-05 -4.54545455e-05
 -2.72727273e-05 -9.09090909e-06  9.09090909e-06  2.72727273e-05
  4.54545455e-05  6.36363636e-05  8.18181818e-05  1.00000000e-04]
.....
13 steps
tensor([-0.0001, -0.0001, -0.0001, -0.0000, -0.0000, -0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0001,  0.0001,  0.0001])
[-1.00000000e-04 -8.33333333e-05 -6.66666667e-05 -5.00000000e-05
 -3.33333333e-05 -1.66666667e-05  0.00000000e+00  1.66666667e-05
  3.33333333e-05  5.00000000e-05  6.66666667e-05  8.33333333e-05
  1.00000000e-04]
.....
14 steps
tensor([-1.0000e-04, -8.4615e-05, -6.9231e-05, -5.3846e-05, -3.8462e-05,
        -2.3077e-05, -7.6923e-06,  7.6923e-06,  2.3077e-05,  3.8462e-05,
         5.3846e-05,  6.9231e-05,  8.4615e-05,  1.0000e-04])
[-1.00000000e-04 -8.46153846e-05 -6.92307692e-05 -5.38461538e-05
 -3.84615385e-05 -2.30769231e-05 -7.69230769e-06  7.69230769e-06
  2.30769231e-05  3.84615385e-05  5.38461538e-05  6.92307692e-05
  8.46153846e-05  1.00000000e-04]
```
Curiously, when I set an even "step" everything seems to work, if I set an odd number of step it seems there is a lack of resolution.  Note that this doesn't happen in numpy. Moreover, I tried with pytorch 0.3 and the issue doesn't arise.  I  noticed the same behavior with torch.range and torch.arange. 

What could be the problem?

**Comment by ezyang** [comment]
It sounds like Numpy is internally using a double precision accumulator, whereas we are not. As a workaround, if you pass `dtype=torch.float64` and then cast to float, it should have the correct resolution.

If someone submits a PR for this, tag me and I'll review it.

**Comment by mravanelli** [comment]
This doesn't seem to solve the issue. The real problem is that  we apparently have a different resolution depending on the number of steps (even steps=no problems, odd_steps=problem). It looks like the presence of "0.0" mess up something. This doesn't happen with the previous version of pytorch (0.3). Are you able to reproduce the error from the code posted above?

**Comment by ailzhang** [comment]
I can repro this on master. Will take a look.

**Comment by mravanelli** [comment]
I see, interesting. It should be something related to the new version of
pytorch. With pytorch 0.3 everything was ok to me...

**Comment by vishwakftw** [comment]
I just found out that this is a printing issue: setting `torch.set_printoptions(precision=8)` prints the right values.

**Comment by ailzhang** [comment]
@vishwakftw yes you are right. Actually this is the same issue as #9395 that our print logic doesn't full match numpy behavior. I talked to @li-roy and will merge these two issues with a fix.
