### ISSUE TITLE
Support third-party devices emit an range for each autograd operator

### ISSUE THREAD

**Issue by 1274085042** [pytorch/pytorch#125752]
### 🚀 The feature, motivation and pitch

 In this PR https://github.com/pytorch/pytorch/pull/101554, a `privateuse1Stubs` register has been added, which allows third-party devices to register a `ProfilerStubs` to enable the emit functionality. We need to support the emit functionality for third-party devices in the profiler_kineto.cpp::enableProfiler(...) function. The following modifications are required:  

1. Add `PRIVATEUSE1` to the `ProfilerState` and `ActiveProfilerType` structures
2. Add privateuse1_observer.h and privateuse1_observer.cpp in the torch/csrc/profiler/standalone directory. The main logic is to add a `pushPRIVATEUSE1CallbacksStub` registrar, which can be used to register `pushXXXCallbacks` of third-party devices.

**My code snippet**  
torch/csrc/autograd/profiler_kineto.cpp
```cpp
void enableProfiler(
    const torch::profiler::impl::ProfilerConfig& config,
    const std::set<torch::profiler::impl::ActivityType>& activities,
    const std::unordered_set<at::RecordScope>& scopes) {
  const auto has_cpu = activities.count(ActivityType::CPU);
  TORCH_CHECK(
      KinetoThreadLocalState::get(/*global=*/config.global()) == nullptr,
      "Profiler is already enabled",
      (config.global() ? "." : " on this thread."));

  if (config.state == ProfilerState::NVTX) {
    torch::profiler::impl::pushNVTXCallbacks(config, scopes);
    return;
  } else if (config.state == ProfilerState::ITT) {
    torch::profiler::impl::pushITTCallbacks(config, scopes);
    return;
  } else if (config.state == ProfilerState::PRIVATEUSE1) {
    torch::profiler::impl::pushPRIVATEUSE1CallbacksStub(
        c10::kPrivateUse1, config, scopes);
    return;
  }
... ...
```

cc @aaronenyeshi  @soulitzer

**Comment by divyanshk** [comment]
@1274085042 Reading some code in the codebase, can you point me to the repos where `REGISTER_PRIVATEUSE1_OBSERVER` is called ? Trying to better understand the use-cases and adoption of `ProfilerState::PRIVATEUSE1`. Thanks.
