### ISSUE TITLE
KINETO_USE_DAEMON causing issues

### ISSUE THREAD

**Issue by gjit-juniper** [pytorch/pytorch#125705]
Hi All,

I am trying to run a simple Kineto profiling program (given in https://github.com/facebookincubator/dynolog/blob/main/scripts/pytorch/linear_model_example.py) and collect traces of the same, however, I am facing the following error whenever I use the flag KINETO_USE_DAEMON=1:

> RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.
> ERROR:2024-05-07 11:12:14 3080034:3080125 FabricManager.h:134] Error when sync_send(): Bad file descriptor
> ERROR:2024-05-07 11:12:14 3080034:3080125 IpcFabricConfigClient.cpp:170] Failed to send config type=3 to dyno: IPC sync_send fail

I do not face this error if I do not use the flag. I have a conda environment with PyTorch 2.4.0 and my CUDA Toolkit is 12.2. My system has a single GPU and I have attached the relevant contents of collect_env.py below:

- PyTorch or Caffe2: PyTorch version: 
**_2.4.0a0+git5a15cbf
Is debug build: False
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A_**
- How you installed PyTorch (conda, pip, source): **_Source_**
- Build command you used (if compiling from source): 
- OS: **_Ubuntu 22.04.4 LTS (x86_64)_**
- Python version: **_3.12.1 | packaged by Anaconda, Inc._** 
- CUDA/cuDNN version: 
**_CUDA used to build PyTorch: 12.2
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY_**
- GPU models and configuration:
**_GPU 0: NVIDIA RTX A6000
Nvidia driver version: 535.171.04_**
- GCC version (if compiling from source): **_[GCC 11.2.0]_**
- CMake version: **_version 3.26.4_**

Has anyone faced such an issue before? Any help would be greatly appreciated.

cc @robieta @chaekit @aaronenyeshi @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise

**Comment by staugust** [comment]
@gjit-juniper  I see an environment variable which can delay the execution time of `libkineto_init`. 

Maybe you can use `KINETO_DAEMON_INIT_DELAY_S=3 KINETO_USE_DAEMON=1 python xxx.py` to test whether nightly built torch supports on-demand profiling.
