### ISSUE TITLE
CUDA nightly docker actually includes CPU build of torch

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#125879]
### 🐛 Describe the bug

```python
 File "/opt/conda/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1077, in CUDAExtension
 library_dirs += library_paths(cuda=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1204, in library_paths
if (not os.path.exists(_join_cuda_home(lib_dir)) and
                            ^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2417, in _join_cuda_home
     raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

### Versions

pytorch-nightly

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim

**Comment by bhack** [comment]
`torch.cuda._is_compiled()` return `false` on pytorch nightly docker image.

/cc @atalman

**Comment by bhack** [comment]
`docker run --rm -it ghcr.io/pytorch/pytorch-nightly:2.4.0.dev20240509-cuda12.4-cudnn8-devel python -c "import torch ; print(torch.cuda._is_compiled())"`

`False`

**Comment by malfet** [comment]
@atalman can you please check what is going on here?

**Comment by bhack** [comment]
Same problem for CUDA `12.1` `2.4.0.dev20240514-cuda12.1-cudnn8-devel`

**Comment by bhack** [comment]
We need to reopen this ticket at also today image has the same problem:

`docker run --rm -it ghcr.io/pytorch/pytorch-nightly:2.4.0.dev20240515-cuda12.4-cudnn8-devel python -c "import torch ; print(torch.cuda._is_compiled())"`

```
False
````

**Comment by bhack** [comment]
cuda `12.1` is ok instead.

**Comment by bhack** [comment]
We have regressed again also on `12.1`:
`docker run --rm -it ghcr.io/pytorch/pytorch-nightly:2.4.0.dev20240531-cuda12.1-cudnn8-devel python -c "import torch ; print(torch.cuda._is_compiled())"`

`False`

I think without regular testing this with the CI it will be always out of control.

**Comment by atalman** [comment]
@bhack you right, our nightly not very stable for docker, I do see an issue here: https://github.com/pytorch/pytorch/actions/runs/9314625747/job/25670242262#step:12:6821
For some reason cpu version is getting installed rather the GPU one. If you want to consume more stable version, use release.

We would need to add test step on top the docker image building

**Comment by bhack** [comment]
Yes but I cannot use release images in this specific  context as I am regularly submitting compiler issues for a devel/testing env. So  for the rapid evolution of the compiler activities in the repo here I need to regularly follow nightly and quickly go back on broken days
Releases are too distant to regularly interact with the compiler team.

**Comment by bhack** [comment]
Also is it not the same dockerfile receipt of stable releases? 
Cause in this case it is better to strictly monitor it as proposed at:

https://github.com/pytorch/builder/issues/1432

**Comment by bhack** [comment]
It seems fixed with `06/01` but we need to wait tomorrow nightly container. In any case cause the instabilities I think that https://github.com/pytorch/builder/issues/1432 is required.
```bash
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytorch-2.4.0.dev20240601  |py3.11_cuda12.1_cudnn8.9.2_0        1.39 GB  pytorch-nightly
    pytorch-mutex-1.0          |             cuda           3 KB  pytorch-nightly
    torchaudio-2.2.0.dev20240601|      py311_cu121         6.4 MB  pytorch-nightly
    torchtriton-3.0.0+45fff310c8|            py311       250.5 MB  pytorch-nightly
    torchvision-0.19.0.dev20240601|      py311_cu121         8.7 MB  pytorch-nightly
    ------------------------------------------------------------
                                           Total:        1.65 GB

The following NEW packages will be INSTALLED:

  torchtriton        pytorch-nightly/linux-64::torchtriton-3.0.0+45fff310c8-py311 

The following packages will be UPDATED:

  pytorch                    2.4.0.dev20240531-py3.11_cpu_0 --> 2.4.0.dev20240601-py3.11_cuda12.1_cudnn8.9.2_0 
  pytorch-mutex                                     1.0-cpu --> 1.0-cuda 
  torchaudio                    2.2.0.dev20240531-py311_cpu --> 2.2.0.dev20240601-py311_cu121 
  torchvision                  0.19.0.dev20240531-py311_cpu --> 0.19.0.dev20240601-py311_cu121 
```

**Comment by bhack** [comment]
Both `docker run --rm -it ghcr.io/pytorch/pytorch-nightly:2.4.0.dev20240602-cuda12.1-cudnn8-runtime  python -c "import torch ; print(torch.cuda._is_compiled())"`

and `docker run --rm -it ghcr.io/pytorch/pytorch-nightly:2.4.0.dev20240602-cuda12.4-cudnn8-runtime  python -c "import torch ; print(torch.cuda._is_compiled())"`

Are ok today.

We could temp close this and focus on  https://github.com/pytorch/builder/issues/1432

**Comment by atalman** [comment]
@bhack agree. I think we need add a call to https://github.com/pytorch/builder/blob/main/.github/workflows/validate_docker_images.yml from pytorch/pytorch after building docker image

**Comment by malfet** [comment]
@atalman can you please add an explanation whether https://github.com/pytorch/pytorch/pull/125887 actually fixed the problem and we regressed again or it never was a proper fix? It would be good to find/mention PRs that caused this regression in the first

**Comment by atalman** [comment]
hi @malfet yes I can confirm that Pr above resolved this error:
https://github.com/pytorch/pytorch/actions/runs/9028906001/job/24810252269#step:11:7905
Its installing 
```
#17 196.6     pytorch-2.4.0.dev20240509  |py3.11_cuda12.1_cudnn8.9.2_0        1.39 GB  pytorch-nightly
```

**Comment by atalman** [comment]
Issues with 12.4, where caused by torchvision conda failures: https://github.com/pytorch/vision/actions/runs/9051068165/job/24867156724

**Comment by bhack** [comment]
But that PR merged 05/10 why it broken on 05/31?

**Comment by atalman** [comment]
@bhack Basically there few issues:
1. For docker build to be successful we would need pytorch, vision and audio to succeed:
pytorch: https://hud2.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=linux-binary-conda
vision: https://hud2.pytorch.org/hud/pytorch/vision/nightly/1?per_page=50&name_filter=Build%20Linux%20Conda
audio: https://hud2.pytorch.org/hud/pytorch/audio/nightly/1?per_page=50&name_filter=Build%20Linux%20Conda
In nightly sometimes we see failures in some jobs, hence single failure to build vision cuda 12.1 for python 3.11 will cause the 
cpu images to be installed rather then cuda.

2. On dev20240531 issu was sequencing the builds torchvision build started before torch build have been completed:
https://github.com/pytorch/vision/actions/runs/9317515686/job/25647988673#step:11:144
During vision build of dev20240531 we picked pytorch from the day before 
```
  pytorch:           2.4.0.dev20240530-py3.11_cuda12.1_cudnn8.9.2_0 pytorch-nightly
```
This package was later removed from conda and replaced by   ``pytorch:  2.4.0.dev20240531`` hence to improve the stability of these nightly docker build we need to implement proper sequencing of pytorch and domain. Will be working on this during H2 of 2024

**Comment by bhack** [comment]
Yes I understand this is going to require a stronger pipeline.

**Comment by atalman** [comment]
To mitigate the issue, will look into possibility of keeping pytorch in anaconda for last 2 builds rather then last day build only.

**Comment by bhack** [comment]
As a temporary workaround it could be also nicer to not push these nightly at all in the registry as it will be a bit confusing to have a new pushed nightly image with an old nightly wheel.

**Comment by bhack** [comment]
It happening again today:
```
The following packages will be UPDATED:

  pytorch            2.4.0.dev20240602-py3.11_cuda12.4_cud~ --> 2.4.0.dev20240604-py3.11_cpu_0 
  torchaudio                  2.2.0.dev20240602-py311_cu124 --> 2.2.0.dev20240604-py311_cpu 
  torchvision                0.19.0.dev20240602-py311_cu124 --> 0.19.0.dev20240604-py311_cpu 
  ```

**Comment by bhack** [comment]
Also today conda is upgrading on CPU but pip is ok.

**Comment by atalman** [comment]
@bhack Nightly CI - validation is added to Docker images : https://hud2.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=Build%20Official%20Docker

Will work now on keeping 2 days conda builds - this should mitigate installing of cpu binaries rather then cuda

**Comment by bhack** [comment]
It is quite strange that pip upgrade over codna is always ok. I've tested an upgrade every day in the last 5/6 nightlies.

**Comment by bhack** [comment]
It is quite strange that pip upgrade over codna is always ok. I've tested an upgrade every day in the last 5/6 nightlies.

**Comment by bhack** [comment]
Do you prefer to have a separate ticket for conda nightly?
As also today we have
```bash
The following packages will be UPDATED:

  pytorch            2.4.0.dev20240604-py3.11_cuda12.4_cud~ --> 2.4.0.dev20240610-py3.11_cpu_0 
  torchaudio                  2.2.0.dev20240605-py311_cu124 --> 2.4.0.dev20240610-py311_cpu 
  torchvision                0.19.0.dev20240605-py311_cu124 --> 0.19.0.dev20240610-py311_cpu 

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main/linux-64::certifi-2024.6.2-~ --> conda-forge/noarch::certifi-2024.6.2-pyhd8ed1ab_0 

The following packages will be DOWNGRADED:

  pytorch-mutex                                    1.0-cuda --> 1.0-cpu 
```

**Comment by atalman** [comment]
@bhack yes pip is always ok since we are not pruning download.pytorch.org. Having 2 nightly builds for conda should resolve the issue of installing cpu instead of gpu image. However it may install previous nightly build rather then current one. But this is the case with pip builds as well

**Comment by bhack** [comment]
Ok thanks. Do you know if the conda layer is invalidated without a new release?
Cause there is the risk to download another 5GB layer from the registry without a new release inside just tracking the nightly images.

**Comment by bhack** [comment]
@atalman Something is broken again. I cannot compile a pytorch custom op on today devel image `ghcr.io/pytorch/pytorch-nightly:2.5.0.dev20240613-cuda12.4-cudnn9-devel`


`docker run --rm -it ghcr.io/pytorch/pytorch-nightly:2.5.0.dev20240613-cuda12.4-cudnn9-devel   python -c "import torch ; print(torch.cuda._is_compiled())"`

```python
==========
== CUDA ==
==========

CUDA Version 12.4.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

False
```

**Comment by malfet** [comment]
@atalman do we have any testing for the docker builds?

**Comment by bhack** [comment]
I think we have these https://hud2.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=Build%20Official%20Docker

But have we created a dependency on this to push or not the images to the artifact registry?

**Comment by bhack** [comment]
Also it seems that we are not coordinated between the wheel and the docker build and push to the artifact. It seems that 06/13 image has the 06/12 cpu wheel.

As I've added this layer to the last nightly image
```Dockerfile
RUN conda install -y pytorch torchvision torchaudio pytorc...
```
And the proposal is to ugprade from 06/12 to 06/13 on 06/13 images.

```Docker
#11 [builder 5/6] RUN conda install -y pytorch torchvision torchaudio pytorc...
#11 1.922 Channels:
#11 1.922  - pytorch-nightly
#11 1.922  - nvidia
#11 1.922  - defaults
#11 1.922 Platform: linux-64
#11 1.922 Collecting package metadata (repodata.json): ...working... done
#11 5.638 Solving environment: ...working... done
#11 220.9 
#11 220.9 ## Package Plan ##
#11 220.9 
#11 220.9   environment location: /opt/conda
#11 220.9 
#11 220.9   added / updated specs:
#11 220.9     - pytorch
#11 220.9     - pytorch-cuda=12.4
#11 220.9     - torchaudio
#11 220.9     - torchvision
#11 220.9 
#11 220.9 
#11 220.9 The following packages will be downloaded:
#11 220.9 
#11 220.9     package                    |            build
#11 220.9     ---------------------------|-----------------
#11 220.9     pytorch-2.5.0.dev20240613  |py3.11_cuda12.4_cudnn9.1.0_0        1.34 GB  pytorch-nightly
#11 220.9     pytorch-mutex-1.0          |             cuda           3 KB  pytorch-nightly
#11 220.9     torchaudio-2.4.0.dev20240613|      py311_cu124         6.3 MB  pytorch-nightly
#11 220.9     torchtriton-3.0.0+45fff310c8|            py311       250.6 MB  pytorch-nightly
#11 220.9     torchvision-0.19.0.dev20240613|      py311_cu124         8.7 MB  pytorch-nightly
#11 220.9     ------------------------------------------------------------
#11 220.9                                            Total:        1.60 GB
#11 220.9 
#11 220.9 The following NEW packages will be INSTALLED:
#11 220.9 
#11 220.9   torchtriton        pytorch-nightly/linux-64::torchtriton-3.0.0+45fff310c8-py311 
#11 220.9 
#11 220.9 The following packages will be UPDATED:
#11 220.9 
#11 220.9   pytorch                    2.4.0.dev20240612-py3.11_cpu_0 --> 2.5.0.dev20240613-py3.11_cuda12.4_cudnn9.1.0_0 
#11 220.9   pytorch-mutex                                     1.0-cpu --> 1.0-cuda 
#11 220.9   torchaudio                    2.4.0.dev20240612-py311_cpu --> 2.4.0.dev20240613-py311_cu124 
#11 220.9   torchvision                  0.19.0.dev20240612-py311_cpu --> 0.19.0.dev20240613-py311_cu124 
#11 220.9 
```

**Comment by atalman** [comment]
This PR: https://github.com/pytorch/test-infra/pull/5332 should mitigate the issue with conda nightly CPU install. By keeping 2 torch versions at all time.

Next will look into adding smoke tests before push

**Comment by bhack** [comment]
But it seems we had a valid GPU wheel for conda as you can see in my extra layer log. Why didn't we have that in the image?

**Comment by atalman** [comment]
@bhack the workflow is initiated at the same time as all other bulds, on push to nightly:
https://github.com/pytorch/pytorch/blob/main/.github/workflows/docker-release.yml#L13
Hence its taking previous nightly build.

We should perhaps run it on schedule when we are on nightly branch. Let me post a PR for that.

**Comment by bhack** [comment]
Can we create a dependency between these jobs?

**Comment by atalman** [comment]
Yes this is what our intent is. Ultimately we want workflow like this
```torch->vision/audio->validations/docker builds```

**Comment by atalman** [comment]
hi @bhack let me know if you see this issue still. Looks like adding conda fallback and adding test before push to ghcr.io helped to improve this situation:

<img width="1276" alt="Screenshot 2024-06-27 at 1 39 24 PM" src="https://github.com/pytorch/pytorch/assets/7563158/80d76af8-a258-483b-947b-10dfb8e5e707">

**Comment by bhack** [comment]
Thanks, I could have a bit of bandwidth to test this again next week.

**Comment by atalman** [comment]
@bhack Thank you for closing this. Please note: we switched from conda to pip in this workflow. Here is the PR that does the switch: https://github.com/pytorch/pytorch/pull/134274
Please let me know if you see issue on your end because of this.
