### ISSUE TITLE
[ONNX] export.export + dynamo_export fail on GLU because decompositions are not run

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#125894]
### 🐛 Describe the bug

Here's a simple repro. 
Legacy onnx.export works.
Both dynamo_export and export.export + dynamo_export fail:

```
import torch

model = torch.nn.GLU().eval().cuda()
sample_input = (torch.randn(8, 4).cuda(),)

# This works fine                                                                                                           
torch.onnx.export(model, sample_input, "glu_legacy.onnx")

model = torch.export.export(model, sample_input)

# This line has to be uncommented as well for dynamo_export to succeed                                                      
# Otherwise, the following error is produced by dynamo_export:                                                              
# torch.onnx._internal.diagnostics.infra.context.RuntimeErrorWithDiagnostic: Unsupported FX nodes: {'call_function': ['aten\
.glu.default']}.                                                                                                            

# model = model.run_decompositions()                                                                                        

options = torch.onnx.ExportOptions(dynamic_shapes=True)

out = torch.onnx.dynamo_export(model,
                               *sample_input,
                               export_options=options
                               )
out.save("glu.onnx")


### Versions

PyTorch nightly 05/09

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by borisfom** [comment]
Note the same issue arises if dynamo_export is run directly on the original module.
I understand the default for export() to not run decompositions.  
But, if dynamo_export() receives Module, not FX as input - there has to be at least an option to enforce running decompositions as part of the process - otherwise it’s guaranteed to fail on any network that has GLU or other modules that need decomposition.

**Comment by titaiwangms** [comment]
This is a missing op in torchlib.

@justinchuby @fatcat-z Could you help with this?
We can reference on torchscript exporter code:
https://github.com/pytorch/pytorch/blob/796dff7147e491ecc13ee66c6ca49ce00d965509/torch/onnx/symbolic_opset18.py#L110-L119

**Comment by justinchuby** [comment]
Just confirming, is there a decomp in PyTorch for glu? When we receive the nn.Module there is a step to run decomp.

**Comment by titaiwangms** [comment]
This error message should be raised after decomposition in both ExportedProgram and nn.Module, so I think no.

**Comment by justinchuby** [comment]
I see. Looks like there's additional decomposition we don't run then? We need to look deeper.

**Comment by titaiwangms** [comment]
Sorry I changed the title back. There is a bug in decomposition we need to look into.

**Comment by titaiwangms** [comment]
#126486 for missing op

**Comment by titaiwangms** [comment]
https://github.com/pytorch/pytorch/blob/8bb7a2f46da40569589197bf1ae730ccbba6bddf/torch/_decomp/__init__.py#L13-L20

Different table is used:
https://github.com/pytorch/pytorch/blob/8bb7a2f46da40569589197bf1ae730ccbba6bddf/torch/export/exported_program.py#L550-L551

https://github.com/pytorch/pytorch/blob/337830f6574057b5e04a7f2c0aa671a575058add/torch/onnx/_internal/fx/decomposition_table.py#L103
