### ISSUE TITLE
[inline-inbuilt-nn-modules] dynamo recompiles identical layers when they have (identical) hooks

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#125836]
With the new `TORCHDYNAMO_INLINE_INBUILT_NN_MODULES=1` env var, it is now possible to create a model that includes a list of (identical) layers, compile each layer separately, and only actually need to compile once.

However: we are still forced to recompile each layer if the layers have any hooks registered to them, even if we happen to have registered the exact same hook to each layer. `register_pre_forward_hook()` (and related API's) work by creating a unique id for every hook which we key on in the hooks dictionary ([code](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py#L1499)). Dynamo guards on this key, which ends up being unique per layer, even if each layer is re-using the same hook fn.

Running the code below recompiles each layer with these guard failures:
```
DEBUG: Recompiling function inner in /data/users/hirsheybar/a_pytorch/torch/_dynamo/external_utils.py:34
    triggered by the following guard failure(s):
    - list(L['fn']._forward_pre_hooks.keys())[0] == 7
    - list(L['fn']._forward_pre_hooks.keys())[0] == 6
    - list(L['fn']._forward_pre_hooks.keys())[0] == 5
    - list(L['fn']._forward_pre_hooks.keys())[0] == 4
    - list(L['fn']._forward_pre_hooks.keys())[0] == 3
    - list(L['fn']._forward_pre_hooks.keys())[0] == 2
    - list(L['fn']._forward_pre_hooks.keys())[0] == 1
    - list(L['fn']._forward_pre_hooks.keys())[0] == 0
```

I'm not sure how easy this is to fix without changing how the hook registration works in eager mode: but one idea is that in theory, even though each layer has a unique set of keys in their hook dict, we can still:

(1) If we sort the dict by the relative order of its keys
(2) guard on the identities of the hook functions themselves, in that sorted order (can we easily access the raw fn that was registered from the hook dict?)

repro:
```
import torch

def fw_hook(inp):
    return tuple([inp[0] + 1])

class Mod(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList()
        for i in range(10):
            layer = torch.nn.Linear(16, 16)
            layer.register_forward_pre_hook(lambda _, inp: fw_hook(inp))
            layer = torch.compile(layer, backend='aot_eager')
            self.layers.append(layer)

    def forward(self, x):
        for l in self.layers:
            x = l(x)
        return x

m = Mod()
x = torch.ones(16, 16, requires_grad=True)
out =m(x)
```

This repro uses a custom lambda (which probably gets a unique python id for each registration) - this is what DTensor does, but one option would be to require DTensor (and anyone who wants no recompiles per layer) to only pass static functions into the register_hook_* API's.

cc @ezyang @msaroufim @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by bdhirsh** [comment]
cc @anijain2305

**Comment by anijain2305** [comment]
This happens because of how `RemovableHandle` works

https://github.com/pytorch/pytorch/blob/b42cfcabc4e7216c5941ebab19c5000e5ecea4eb/torch/utils/hooks.py#L25 increments the `id` on every time its called.

For global hooks, it makes sense. For local hooks (forward_hooks, forward_pre_hooks) for dynamo, this causes a recompilation problem. Even if different instances of nn module register same forward_hook, their `_forward_hooks` dict will have different keys because of how `RemovableHandle` works. Dynamo guards on the keys, and therefore recompiles. 

I don't think there is an easy/elegant way in Dynamo to not recompile.

Does it make sense to refactor the `nn/module.py` so that it `handle.id`s start from 0 for local hooks?

@ezyang @bdhirsh @wanchaol

**Comment by wanchaol** [comment]
@ezyang @albanD Would it make sense to use local id for module instance hooks (i.e. module_forward_pre_hook and module_forward_hook), and use global id for the nn.Module global hooks (i.e. register_full_*_hook)?

**Comment by bdhirsh** [comment]
I talked with @albanD around this question (should we try to change either eager mode or dynamo to avoid specializing on these id's?). A few points that came up:

- we probably can't change the existing eager API because it is user facing: when a user registers a hook, they get back a handle with a unique int (that in theory they can do something with)
- "specialize guard handling for hooks" does feel kind of against the grain of what "inlining nn modules" is supposed to be doing: inlining nn modules implies we are not special-casing nn modules (we are just inlining them as plain functions). Avoiding recompiling on hooks would require dynamo to have special knowledge of how hook registration works in nn modules. Dynamo would need to e.g. properly model all of the other semantics of hook registration, and if the user manages to specialize on their hook registration handle in some way in their hook, dynamo would still need to properly guard there. I'm curious what @anijain2305 thinks though.

For torchtitan specifically, one alternative to explore would be: aggressively try to get AOT warm caching working for the torchtitan use case. That way, since in theory we expect every layer to result in the same graph, we would only need to deal with the overhead of dynamo re-running on each layer (which should be cheap although we'll need to measure it), and not the rest of the compile stack.

cc @jamesjwu if you have any thoughts. In terms of "things that do not yet work in the warm cache for the torchtitan use case: the main one that I can think of is that torchtitan's module hooks will end up putting DTensor constructors into the graph (and potentially float8 too). That would require, at least:

(1) AOT warm cache support for subclass constructors in the graph

(2) improving the subclass constructor support in dynamo enough that we can remove the `allow_in_graph` code on the constructors in `Float8` (@mlazos was going to take a look at this)

**Comment by mlazos** [comment]
Yes I will look at (2)

While it's important to be as general as possible I don't think it's too much of a stretch to specialize guard handling for hooks if there aren't other options. We handle NN module parameters and buffers in a special way in dynamo already so there is some precedent.
