### ISSUE TITLE
unsqueeze_copy doesn't seem to respect dynamic shapes

### ISSUE THREAD

**Issue by angelayi** [pytorch/pytorch#125853]
### 🐛 Describe the bug

It seems like `aten.unsqueeze_copy` specializes on the shape:

```python
from torch._subclasses.fake_tensor import FakeTensorMode 
from torch.fx.experimental.symbolic_shapes import (
    ShapeEnv, DimDynamic, StatelessSymbolicContext
)

shape_env = ShapeEnv()
t1 = torch.ones(2, 2, 768)
with FakeTensorMode(shape_env=shape_env) as fake_mode:
    t = fake_mode.from_tensor(
        t1,
        symbolic_context=StatelessSymbolicContext(
            dynamic_sizes=[DimDynamic.DYNAMIC, DimDynamic.STATIC, DimDynamic.STATIC],
        )
    )
print(t)  # FakeTensor(..., size=(s0, 2, 768))
print(torch.ops.aten.unsqueeze(t, 1))  # FakeTensor(..., size=(s0, 1, 2, 768))
print(torch.ops.aten.unsqueeze_copy(t, 1))  # FakeTensor(..., size=(2, 1, 2, 768))
```
cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @tarun292 @larryliu0820 

### Versions

main

**Comment by malfet** [comment]
@ezyang I've asked this question in the past, but guess never got a rely: should dynamic shapes go into oncall pt2 or not

**Comment by ezyang** [comment]
yes please

**Comment by ezyang** [comment]
This typically means that unsqueeze_copy is forcing a specialization. This can be confirmed with TORCH_LOGS=dynamic. https://docs.google.com/document/d/1GgvOe7C8_NVOMLOCwDaYV1mXXyHMXY7ExoewHqooxrs/edit#heading=h.fh8zzonyw8ng says how to resolve.

**Comment by avikchaudhuri** [comment]
At the risk of speculating, maybe due to this line? https://github.com/pytorch/pytorch/blob/59f2e716ccb84f359e3170b3e95e839e7446df0d/torch/_meta_registrations.py#L387

@angelayi do you have the logs handy?
