### ISSUE TITLE
PyTorch ONNX Tests are Outdated.

### ISSUE THREAD

**Issue by ArmenAg** [pytorch/pytorch#12586]
In short, the pytorch ONNX tests are outdated and need to be updated to the new API.

For example in this [file](https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_caffe2.py), we are still using Variable.

Or [here](https://github.com/pytorch/pytorch/blob/master/test/onnx/model_defs/mnist.py) we use log_softmax without an explicit `dim=1` argument.

I can work on this if permitted.

**Comment by soumith** [comment]
@ArmenAg yes, go ahead. cc: @houseroad
