### ISSUE TITLE
Cub submodule still pointing to a deprecated repo

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#125981]
### 🐛 Describe the bug

CUB submodule is pointing to a deprecated repo.
Can we point to https://github.com/NVIDIA/cccl/ ?

### Versions

Main

cc @ptrblck @msaroufim

**Comment by ptrblck** [comment]
`third_party/cub` isn't used in newer CUDA builds anymore and could be removed.
The last time I suggested this and discussed with @malfet we agreed to keep it alive for "older" CUDA builds, but I'm not sure if any of these releases is still supported.

**Comment by bhack** [comment]
We have a connected PR. CI seems fine.

**Comment by shink** [comment]
fixed by #126540,
