### ISSUE TITLE
Compile/Lowering `nonzero`

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#126003]
### 🚀 The feature, motivation and pitch

With the current  `INT_MAX` limit we have with cuda `nonzero`:
https://github.com/pytorch/pytorch/pull/125850
~Outdated CUB submodule https://github.com/pytorch/pytorch/issues/125981~
Upstream pending:
https://github.com/NVIDIA/cccl/issues/1422

Can we in the meantime lowering `nonzero` with Triton `where` and `sum`?

/cc @ezyang @lezcano 

https://github.com/pytorch/pytorch/blob/a174c536f8f32b41da9efa647e364196423468a5/torch/_inductor/lowering.py#L2186-L2187

**Comment by ezyang** [comment]
I'm pretty unconvinced that we actually will bother with native PT2 compilation support for nonzero
