### ISSUE TITLE
Error when using torch.zeros

### ISSUE THREAD

**Issue by DongShuaike** [pytorch/pytorch#12606]
## 🐛 Bug

Program gets a `Segmentation fault` when the parameter setting of `torch.zeros` function is very large and the second parameter being a `tensor` instead of an `integer`.
## To Reproduce

1. `seq_length = torch.LongTensor(range(895))`
1. `torch.zeros((69137, seq_length.max(), 13))`
1. `Segmentation Fault`

## Expected behavior
If I do the following 
```
import torch
torch.zeros((69137, torch.LongTensor([895]).max(), 13))
```
An error of ` TypeError: an integer is required` will be shown, indicating we should change `torch.LongTensor([895])` to `torch.LongTensor([895]).numpy()`.
If I do the following
```
torch.zeros((69137, torch.LongTensor([1]).max(), 13))
```
No error will be produced.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Collecting environment information...
- PyTorch version: 0.4.1.post2
- Is debug build: No
- CUDA used to build PyTorch: 9.0.176

- OS: Debian GNU/Linux 9.4 (stretch)
- GCC version: (Debian 4.9.2-10+deb8u1) 4.9.2
- CMake version: version 3.9.4

Python version: 2.7
- Is CUDA available: Yes
- CUDA runtime version: Could not collect
- GPU models and configuration: 
- GPU 0: GeForce GTX 1080 Ti
- GPU 1: GeForce GTX 1080 Ti

- Nvidia driver version: 387.26
- cuDNN version: Probably one of the following:
- /usr/local/cuda-8.0/lib64/libcudnn.so.6
- /usr/local/cuda-9.0/lib64/libcudnn.so
- /usr/local/cuda-9.0/lib64/libcudnn.so.7
- /usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
- /usr/local/cuda-9.0/lib64/libcudnn.so.7.1.2
- /usr/local/cuda-9.0/lib64/libcudnn_static.a
- /usr/local/cuda-9.1/lib64/libcudnn.so
- /usr/local/cuda-9.1/lib64/libcudnn.so.7
- /usr/local/cuda-9.1/lib64/libcudnn.so.7.1.2
- /usr/local/cuda-9.1/lib64/libcudnn_static.a

Versions of relevant libraries:
- [pip] Could not collect
- [conda] magma-cuda90              2.3.0                         1    pytorch
- [conda] pytorch                   0.4.1           py27__9.0.176_7.1.2_2    pytorch
- [conda] torch                     0.4.0a0+964707e           <pip>
- [conda] torch                     0.4.0a0+92a0f78           <pip>
- [conda] torchfile                 0.1.0                     <pip>
- [conda] torchnet                  0.0.2                     <pip>
- [conda] torchvision               0.2.0                     <pip>
- [conda] torchvision               0.2.1                    py27_1    pytorch

**Comment by mhubii** [comment]
Hey there, torch.max() returns a tensor, not an integer.

**Comment by zou3519** [comment]
I can't reproduce this on master

**Comment by mhubii** [comment]
Its not an error, its a misuse of a function.
