### ISSUE TITLE
Remove `out` parameter from functions in PyTorch to simplify the functions and the documentation

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#126016]
### 🚀 The feature, motivation and pitch

In PyTorch, there is `out` parameter in many functions like [matmul()](https://pytorch.org/docs/stable/generated/torch.matmul.html), [rand()](https://pytorch.org/docs/stable/generated/torch.rand.html), [arrange()](https://pytorch.org/docs/stable/generated/torch.arange.html).

For example, I find the pros of `matmul()` with `out` parameter is that the result is displayed with one line of code different from `matmul()` without `out` parameter which are two lines of code using [IPython](https://ipython.org/), [Jupyter Notebook](https://jupyter.org/), [Google Colab](https://colab.research.google.com/), etc as shown below: 

```python
import torch

tensor1 = torch.tensor([0, 1, 2])
tensor2 = torch.tensor([3, 4, 5])
new_tensor = torch.tensor(0)

# One line of code
torch.matmul(input=tensor1, other=tensor2, out=new_tensor) # tensor(14)

# Two lines of code
new_tensor = torch.matmul(input=tensor1, other=tensor2)
new_tensor # tensor(14)
```

###  About `out` parameter of functions in PyTorch:

Pros: 
1. Less lines of code.

Cons:
1. People will write either of 2 ways(with or without `out` parameter) so it breaks the consistency of how people write code so such a code is less readable, less efficient and less productive which is seriously bad.
2. It makes PyTorch documentation complicated (I mean **It is not simple because of `out` parameter.**). 

So, I think `out` parameter has more disadvantages than advantages so `out` parameter should be removed to simplify the functions and the documentation.

**Comment by ezyang** [comment]
For BC reasons we are not going to do this
