### ISSUE TITLE
caffe2  GetMutableTensor

### ISSUE THREAD

**Issue by mhubii** [pytorch/pytorch#12607]
## 🐛 Bug

Can someone reproduce this error? What am I doing wrong?

```
*** Aborted at 1539351838 (unix time) try "date -d @1539351838" if you are using GNU date ***
PC: @           0x404525 at::StorageImpl::capacity()
*** SIGSEGV (@0x40) received by PID 29800 (TID 0x7f16d8d6e880) from PID 64; stack trace: ***
    @     0x7f16d5a754b0 (unknown)
    @           0x404525 at::StorageImpl::capacity()
    @           0x404946 at::Storage::capacity()
    @           0x407311 _ZN2at10TensorImpl6ResizeIJNS_8ArrayRefIlEEEEEvDpT_
    @           0x40563c caffe2::Tensor::ResizeLike()
    @           0x4033ce main
    @     0x7f16d5a60830 __libc_start_main
    @           0x402fe9 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)
```

## To Reproduce

in your cmake:

```
cmake_minimum_required(VERSION 3.11 FATAL_ERROR)
set(CMAKE_CXX_STANDARD 11)

find_library(CAFFE2_LIB caffe2)
find_package(Protobuf REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main ${CAFFE2_LIB} ${PROTOBUF_LIBRARIES})
```

in your main:

```
#include <caffe2/core/init.h>
#include <caffe2/core/tensor.h>
#include <caffe2/core/workspace.h>

using namespace std;
using namespace caffe2;

int main(int argc, char** argv) {

	caffe2::GlobalInit(&argc, &argv);

	// Tensor.
	vector<int64_t> dims({10});
	vector<float> values(10, 1);

	Tensor tensor(dims, CPU);
	tensor.ShareExternalPointer(values.data());

	// Workspace.
	Workspace workspace;

	Tensor* data = workspace.CreateBlob("data")->GetMutable<Tensor>();
	data->ResizeLike(tensor); // doesn't work
	
	google::protobuf::ShutdownProtobufLibrary();
	
	return 0;
}
```

## Environment

```
PyTorch version: 0.3.0b0+af3964a
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.11.4

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1050
Nvidia driver version: 396.54
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

**Comment by mhubii** [comment]
Linking against glog, and explicitly using BlobGetMutableTensor(Blob* blob, DeviceType device_type) did the job for me. But I think that it should as presented above. Changes to the CMakeLists.txt and the main.cpp are:

cmake:

´´´
cmake_minimum_required(VERSION 3.11 FATAL_ERROR)
set(CMAKE_CXX_STANDARD 11)

find_library(CAFFE2_LIB caffe2)
find_package(Protobuf 3 REQUIRED)
find_library(GLOG_LIB glog) # MODIFIED

add_executable(main main.cpp)
target_link_libraries(main ${CAFFE2_LIB} ${PROTOBUF_LIBRARIES} ${GLOG_LIB}) # MODIFIED
´´´

main:

´´´
#include <caffe2/core/init.h>
#include <caffe2/core/tensor.h>
#include <caffe2/core/workspace.h>

using namespace std;
using namespace caffe2;

int main(int argc, char** argv) {

	caffe2::GlobalInit(&argc, &argv);

	// Tensor.
	vector<int64_t> dims({10});
	vector<float> values(10, 1);

	Tensor tensor(dims, CPU);
	tensor.ShareExternalPointer(values.data());

	// Workspace.
	Workspace workspace;

	//Tensor* data = workspace.CreateBlob("data")->GetMutable<TensorCPU>(); // Doesn't work for me.
	Tensor* data = BlobGetMutableTensor(workspace.CreateBlob("data"), CPU); // MODIFIED
	data->ResizeLike(tensor); // doesn't work

	
	google::protobuf::ShutdownProtobufLibrary();
	
	return 0;
}
´´´

**Comment by ezyang** [comment]
Yes, this first program is an incorrect use of the API. Actually, we are currently in the progress of changing the Caffe2 API so that it is harder to make this mistake. But we will not fix this particular problem; instead, we will be evolving the Caffe2 API to resemble more the PyTorch C++ API.

I'm happy to leave this issue open for you until the loose edge is filed away, or feel free to close it if you think it is not relevant.

CC @jerryzh168

**Comment by mhubii** [comment]
Well thanks for the fast response, and thanks for the great work you guys are doing. The problem here might then be that the most viewed cpp tutorial for caffe2 https://github.com/leonardvandriel/caffe2_cpp_tutorial uses exactly these function calls. I'll close the issue and stick to the pytorch cpp api for now.

**Comment by rilesdg3** [comment]
I changed the [intro part of that tutorial](https://github.com/leonardvandriel/caffe2_cpp_tutorial/blob/master/src/caffe2/binaries/intro.cc) to reflect the changes that have been made since that one was done
https://github.com/rilesdg3/caffe2-Tutorial/blob/master/intro.cc

I wish I would have found this page a couple weeks ago, It took me a long time to figure this out

**Comment by jerryzh168** [comment]
@rilesdg3 actually there are lots of changes on the way because we are merging the caffe2 and pytorch backend, please feel free to open an issue in https://github.com/pytorch/pytorch/issues when you have questions.
