### ISSUE TITLE
CUDA is not working!

### ISSUE THREAD

**Issue by Smellycod** [pytorch/pytorch#126020]
### 📚 The doc issue

![image](https://github.com/pytorch/pytorch/assets/169583522/4567fe1b-7639-4885-8c60-e0c93860f3ed)
![image](https://github.com/pytorch/pytorch/assets/169583522/b483a6b8-dfed-44c3-9016-67d7e47c7ecb)
And I still get error in pycharm: AssertionError: Torch not compiled with CUDA enabled

May be someone could help me solve this problem, I've been trying to solve for days. torch was installed with pip, python version is 3.12

cc @ptrblck @msaroufim

**Comment by thotho19** [comment]
you must downgrade your Nvidia Cuda tool kit to "12.1" otherwise you must build the PyTorch from the source

**Comment by Smellycod** [comment]
> you must downgrade your Nvidia Cuda tool kit to "12.1" otherwise you must build the PyTorch from the source

Thank you for the quick response, unfortunately, it didn't help, version 12.4 was deleted, version 12.1 installed, computer rebooted but the problem is still there

**Comment by ezyang** [comment]
https://discuss.pytorch.org/ is a better forum for this
