### ISSUE TITLE
Memory Leak in torch.load()

### ISSUE THREAD

**Issue by mireiaplanas** [pytorch/pytorch#126159]
### 🐛 Describe the bug

I've discovered a memory leak in torch.load() when loading a saved tensor. Despite explicitly deleting the loaded object and invoking garbage collection, the memory usage does not decrease as expected.

Below is a minimal reproducible example to demonstrate the issue.

```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import torch
import gc

def create_and_save_image():
    image = torch.randn(30, 384, 384)
    ckpt = {"image": image}
    torch.save(ckpt, "test_image.pt")

@profile
def load_and_del():
    ckpt = torch.load("test_image.pt")
    del ckpt
    gc.collect()

if __name__ == '__main__':
    create_and_save_image()
    load_and_del()
```

**Steps to Reproduce:**

python3 -m memory_profiler mem_leak.py

Observe the memory usage before and after loading and deleting the tensor.

**Expected Behavior:**

The memory usage should increase when torch.load() is called and decrease after the object is deleted and garbage collection is invoked.

**Observed Behavior:**

The memory usage increases when torch.load() is called, but does not decrease after deleting the object and calling gc.collect(), indicating a memory leak. Here’s the output of the memory profiler:
![Screenshot from 2024-05-14 11-42-34](https://github.com/pytorch/pytorch/assets/153609086/65b9b554-52c4-4ff2-b6f8-85a6534102b1)

Related issue: https://github.com/pytorch/pytorch/issues/102334

### Versions

PyTorch version: 2.3.0

Python version: 3.8.5

OS: Linux

CUDA version: 12.0

GPU: NVIDIA GeForce RTX A6000 (48 Gb)

cc @mruberry @mikaylagawarecki @msaroufim

**Comment by malfet** [comment]
I'm not sure how tool you are referencing here works, but there are few problems with the approach that you've taken:
 - Calling any Python (or PyTorch) function can increase app memory usage, as lots of functions are doing some lazy initialization (I guess first call to `torch.load` initializes some sort of internal pickle state in addition to other global state changes)
 - `gc.collect` is not guaranteed to collect all the references 
 - I'm not sure if tool takes into account some caching that PyTorch is doing

Running something like:
```python
for i in range(1_000_000):
  load_and_del()
```
and observing memory utilization by the process would be a better mechanism of detecting a leak of sorts

P.S. If one changes image tensor size from 30x384x384 to 384x384x384, then this profile tool shows following stats, which indeed confirms that first call to `torch.load` would do some lazy importing, but data and metadata associated with the tensor is getting deleted when tensor is freed:
```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    11  366.094 MiB  366.094 MiB           1   @profile
    12                                         def load_and_del():
    13  582.441 MiB  216.348 MiB           1       ckpt = torch.load("test_image.pt")
    14  366.691 MiB -215.750 MiB           1       del ckpt
    15  366.691 MiB    0.000 MiB           1       gc.collect()
```

Closing this one for now, but if you'll find more proof that PyTorch leaks memory during the load, please do not hesitate to comment here or open a new issue

```
