### ISSUE TITLE
About the nested tensor's support for dtype/device transform

### ISSUE THREAD

**Issue by floatingCatty** [pytorch/pytorch#126145]
### 🚀 The feature, motivation and pitch

I was using torch-nested tensor type to perform sampling of irregular shapes of tensors. However, I find that the type and device transform is not straightforward using nested tensors. The to(), .cuda() or float(), double() operations seem not supported in nested tensors. I would like to ask for such support for these behaviours.

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @soulitzer

**Comment by jbschlosser** [comment]
Hey @floatingCatty, thanks for the request! Which version of PyTorch are you using? I believe the functions you mentioned are all supported.

As a side note, I suggest using nested tensors with the jagged layout (AKA NJTs) as utilized in this [tutorial](https://pytorch.org/tutorials/prototype/nestedtensor.html#why-nested-tensor) if possible. Operator support for these is much better than for the older, strided layout of nested tensors. Further, NJTs are usable within torch.compile.

```python
# note the layout setting here
nt = torch.nested.nested_tensor(..., layout=torch.jagged)
nt.float()
```

**Comment by floatingCatty** [comment]
@jbschlosser Hello, I am currently using torch 1.13.0
![image](https://github.com/pytorch/pytorch/assets/64253517/9e9a2613-eaac-4207-bbea-b5265e061a29)
It would raise this error when I call .double() to a nested tensor:
![image](https://github.com/pytorch/pytorch/assets/64253517/1c35b563-ab90-4eff-9b87-c2e9e357bf97)
I tried using NJTS as you mentioned, but it does not seem to support the torch of my version. Maybe I need to upgrade to the latest version?

Thanks a lot for your help!

**Comment by jbschlosser** [comment]
> I tried using NJTS as you mentioned, but it does not seem to support the torch of my version. Maybe I need to upgrade to the latest version?

@floatingCatty Yes that's right, your version of torch predates a lot of nested tensor support as well as NJTs themselves. I'd recommend upgrading if possible to get access to these features.
