### ISSUE TITLE
[inductor] cpp codegen using already deleted header

### ISSUE THREAD

**Issue by xmfan** [pytorch/pytorch#126128]
### 🐛 Describe the bug

Inductor seems to be using a header filename generated from a previous test run, but temporary directories are cleared between tests.

Issue boils down to the fresh_inductor_cache wrapper not cleaning up properly once exited
```python
import torch
from torch._inductor.utils import fresh_inductor_cache

def fn():
    x = torch.randn(1, 10)
    y = torch.randn(10, 1)
    return torch.mm(x, y).sum()

def fn2():
    x = torch.randn(10, 100)
    y = torch.randn(100, 10)
    return torch.mm(x, y).sum()

with fresh_inductor_cache():
    torch.compile(fn)()

torch.compile(fn2)()
```

makes compiled autograd flaky tests: `TORCHINDUCTOR_COMPILE_THREADS=1 pytest test/inductor/test_compiled_autograd.py -k 'test_torch_compile or test_access_saved_tensor_twice_without_recomputation_works'`

### Versions

main

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by jgong5** [comment]
The header file about `cpp_prefix.h` and is named after its hash. It should be generated before compiling the generated cpp code. Things are being tested with other UTs in `test_torchinductor.py` and `test_cpu_repro.py`. Is it `test_compile_autograd.py` specific?

**Comment by xmfan** [comment]
I only have a repro with test_compiled_autograd.py, do you have a code pointer to where we generate the header name?

**Comment by xmfan** [comment]
@jgong5 found a smaller repro

```
import torch
from torch._inductor.utils import fresh_inductor_cache

def fn():
    x = torch.randn(1, 10)
    y = torch.randn(10, 1)
    return torch.mm(x, y).sum()

def fn2():
    x = torch.randn(10, 100)
    y = torch.randn(100, 10)
    return torch.mm(x, y).sum()

with fresh_inductor_cache():
    torch.compile(fn)()

torch.compile(fn2)()
```
