### ISSUE TITLE
[PT2E Quantization] PT2E geneartes scalar scales and zero_point for per channel quantizatoin

### ISSUE THREAD

**Issue by lsy323** [pytorch/pytorch#126189]
### 🐛 Describe the bug

PT2E generates `quantize_per_channel` with scalar `scales` and `zero_point`. In this case, it will be the `per-tensor` quantization instead of `per-channel`. [torch quantize_per_channel op](https://github.com/pytorch/pytorch/blob/db3b38202b2e55c013fdd728bf7707f2d48a5660/torch/ao/quantization/fx/_decomposed.py#L448-L455) also specifies the `scale` is `a list of scale quantization parameter for
       affine quantization, one per channel`. (Same for zero_point) So this looks to be unexpected behavior.

It can be reproduced with the following codes:
```
import torch
import torchvision
from torch._export import capture_pre_autograd_graph
from torch.ao.quantization.quantize_pt2e import convert_pt2e, prepare_pt2e
from torch.ao.quantization.quantizer.xnnpack_quantizer import (
    XNNPACKQuantizer, get_symmetric_quantization_config)

args = (torch.randn(1, 3, 224, 224),)
m = torchvision.models.resnet18().eval()
m = capture_pre_autograd_graph(m, args)

# Step 2: Insert observers or fake quantize modules
quantizer = XNNPACKQuantizer().set_global(
    get_symmetric_quantization_config(is_per_channel=True))
m = prepare_pt2e(m, quantizer)

# Step 3: Quantize the model
m = convert_pt2e(m, fold_quantize=False)

# Export
exported = torch.export.export(m, args)
print(exported)
```
We can see `torch.ops.quantized_decomposed.quantize_per_channel.default` is taking scaler `scales` and `zero_point`
```
def forward(self, ...b_conv1_scale_0: "f32[1]", b_conv1_zero_point_0: "i64[1]",)
    quantize_per_channel: "i8[64, 3, 7, 7]" = torch.ops.quantized_decomposed.quantize_per_channel.default(p_conv1_weight, b_conv1_scale_0, b_conv1_zero_point_0, 0, -127, 127, torch.int8);  p_conv1_weight = None
```

Thanks for the help!

cc @jerryzh168 @andrewor14 @qihqi @sdasgup3 @paulinesho

### Versions

[pip3] torch==2.4.0a0+gitf25c7c9
[pip3] torchvision==0.19.0a0+947ae1d

**Comment by lsy323** [comment]
As @paulinesho pointed out, need to run the example inputs through captured graph between `prepare_pt2e ` and `convert_pt2e` so that the scale and zero_point for per-channel quant are not scalar anymore.

But this step is missing in the doc of https://pytorch.org/tutorials/prototype/pt2e_quant_ptq.html, maybe it should be added?

Also the `quantize_per_channel` is for weight, which doesn't need running through calibration dataset. Is it expected to run the graph even for weight-only quant?

**Comment by andrewor14** [comment]
Hi @lsy323, yes we expect users to run the graph even for weight-only quant, exactly for the reason you mentioned. Our observers derive the shapes of the input values from calibration, which involves calling the model on example inputs. In the tutorial you linked we refer to this in the comment "calibration omitted". I think this is expected behavior if the user doesn't calibrate.

**Comment by lsy323** [comment]
> Hi @lsy323, yes we expect users to run the graph even for weight-only quant, exactly for the reason you mentioned. Our observers derive the shapes of the input values from calibration, which involves calling the model on example inputs. In the tutorial you linked we refer to this in the comment "calibration omitted". I think this is expected behavior if the user doesn't calibrate.

I see, thanks for clarifying @andrewor14 !
