### ISSUE TITLE
Does sccache work for rocm builds?

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#126111]
ROCm builds average 1.5+ hrs but the sccache stats claim that there were 0 cache misses

Is sccache used?  Are the stats correct and it just takes a long time even with it?  

Just trying to figure out how to reduce TTS for some jobs

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by jithunnair-amd** [comment]
@clee2000 https://github.com/pytorch/pytorch/pull/127012 moved the AOTriton build to the CI base docker image step, thus reducing ROCm build job durations to around 20mins (from 1.5+hrs).
