### ISSUE TITLE
Numba support should be included in nightly tests.

### ISSUE THREAD

**Issue by asford** [pytorch/pytorch#12614]
_Follow-up from #11984._

Pytorch nightly tests should install numba and execute the __cuda_array_interface__  based integration tests.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by pjh5** [comment]
Which environments should this run on? Nightly builds are currently on Darwin cpu and Linux cpu + CUDA 8.0, 9.0, 9.2 for Python 2.7, 3.5, 3.6, 3.7

**Comment by asford** [comment]
Would it be possible to make this part of the standard Linux+CUDA suite? The feature should be compatible with cuda 8.0+ and python 2.7, 3.5+.

**Comment by pjh5** [comment]
On both soumith/manylinux-cuda80 and soumith/manylinux-cuda90 a simple pip install of numba has a strange issue:

`nvidia-docker run -it soumith/manylinux-cuda80 /bin/bash`
```
export PATH=/opt/python/cp27-cp27mu/bin:$PATH
pip install numpy numba
python
```
```
Python 2.7.15 (default, Jul 24 2018, 05:08:02)
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba.cuda as cuda
>>> cuda.detect()
Found 2 CUDA devices
id 0            Quadro GP100                              [SUPPORTED]
                      compute capability: 6.0
                           pci device id: 0
                              pci bus id: 129
id 1            Quadro GP100                              [SUPPORTED]
                      compute capability: 6.0
                           pci device id: 0
                              pci bus id: 130
Summary:
        2/2 devices are supported
True
>>> cuda.is_available()
False
```
I get the same result for python 3.6. Do you happen to know what causes this or should I post an issue to numba?

**Comment by asford** [comment]
This appears to be an issue with how numba is picking up the cuda installation on the image. I've been able to resolve it by explicitly providing the [path to the NVVM library via numba-specific env vars](https://numba.pydata.org/numba-doc/dev/user/installing.html#installing-using-pip-on-x86-x86-64-platforms).

```
+fordas@fela:/scratch/USERS/fordas/workspace$ nvidia-docker run -it soumith/manylinux-cuda80 /bin/bash
[root@f0ac885cb355 /]# export PATH=/opt/python/cp27-cp27mu/bin:$PATH
[root@f0ac885cb355 /]# pip install numba
Collecting numba
    [...]
Installing collected packages: enum34, llvmlite, funcsigs, six, singledispatch, numpy, numba
Successfully installed enum34-1.1.6 funcsigs-1.0.2 llvmlite-0.25.0 numba-0.40.1 numpy-1.15.2 singledispatch-3.4.0.3 six-1.11.0
```
```
[root@f0ac885cb355 /]# export NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so
[root@f0ac885cb355 /]# python -c 'import numba.cuda; numba.cuda.detect(); print "numba.cuda.is_available: %s" % numba.cuda.is_available()'
Found 2 CUDA devices
id 0    Tesla V100-PCIE-32GB                              [SUPPORTED]
                      compute capability: 7.0
                           pci device id: 0
                              pci bus id: 94
id 1    Tesla V100-PCIE-32GB                              [SUPPORTED]
                      compute capability: 7.0
                           pci device id: 0
                              pci bus id: 134
Summary:
        2/2 devices are supported
numba.cuda.is_available: True
```

I'm not familiar with your nightly infrastructure, but does it run within a conda environment? If so it _may_ be simpler to just install [`numba` & `cudatoolkit` via conda](https://numba.pydata.org/numba-doc/dev/user/installing.html#installing-using-conda-on-x86-x86-64-power-platforms).

**Comment by malfet** [comment]
It's been enabled for a while now
