### ISSUE TITLE
using pytorch 0.4 using cuda show grad was None

### ISSUE THREAD

**Issue by liuwenjie1995** [pytorch/pytorch#12627]
## 🐛 Bug

when i use cuda grad , it shows grad was None 
## To Reproduce

Steps to reproduce the `behavior:`

1.cuda 9.1
2.torch 0.4

```
import torch
from torch import nn,optim
import torch.nn.functional as F

inputs = torch.Tensor(torch.randn(3, 5))
targets = torch.Tensor([1, 2, 3]).long()
inputs.requires_grad = True

inputs, targets = inputs.cuda(),targets.cuda()

Net = nn.Sequential(
    nn.Linear(5, 5),
    nn.Softmax()
).cuda()

out = Net(inputs[0])
Net.train()
optimizer = optim.Adam(Net.parameters(), lr=0.001)
loss_fn = nn.NLLLoss()
for i in range(3):

    optimizer.zero_grad()

    loss = loss_fn(out.view(1, 5), targets[0].view(1))
    loss.backward(retain_graph=True)
    print(inputs.grad)
    optimizer.step()
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

**Comment by albanD** [comment]
Hi,

Please use the [forum](https://discuss.pytorch.org/) to ask this kind of questions.
In particular this as already been answered [here](https://discuss.pytorch.org/t/tensor-grad-none-for-tensors-on-gpu/24838) in the forum: when you cann `.cuda()`, you get a new tensor that is not a leaf tensor and thus it's `.grad` field will not be populated.
