### ISSUE TITLE
torch.chunk returns Tuple, not List

### ISSUE THREAD

**Issue by Daniel-Chin** [pytorch/pytorch#126278]
### 📚 The doc issue

Both  
- the documentation at https://pytorch.org/docs/stable/generated/torch.chunk.html as of V2.3 and
- the type annotation in line 736 of torch/_C/_VariableFunctions.pyi 

claim that the return type of `torch.chunk` is `List[Tensor]`, whereas in reality it is `Tuple[Tensor]` according to  
- The "Example" section on that exact [documentation page](https://pytorch.org/docs/stable/generated/torch.chunk.html) and 
- local testing with pytorch 2.1.0. 

### Suggest a potential alternative/fix

Fix the doc and the annotations. 

cc @ezyang @malfet @xuzhao9 @gramster

**Comment by cpuhrsch** [comment]
Marked for triage review to discuss what we want to do here

**Comment by drisspg** [comment]
Although the the typed named is a tensorlist in return values for this type are always tuples in python. This is actionable and we want to update the signature in pyi to reflect that this always returns a tuple
