### ISSUE TITLE
Pytorch 1.0 installation in WIndows fails with error

### ISSUE THREAD

**Issue by sheikmohdimran** [pytorch/pytorch#12626]
## 🐛 Bug

While installing from source on windows, build fails with the error

## To Reproduce

Install pytorch from source as per below steps. 

cd  ~\Desktop
git clone --recursive https://github.com/pytorch/pytorch
cd  ~\Desktop\pytorch
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1
set "PREBUILD_COMMAND=%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
set PREBUILD_COMMAND_ARGS=x64

call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
python setup.py install

Error message as below.
"C:\Users\<username>\Desktop\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"C:\Users\<username>\Desktop\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\<username>\Desktop\pytorch\build\caffe2\AlgorithmsTest.vcxproj" (default target) (4) ->
"C:\Users\<username>\Desktop\pytorch\build\caffe2\caffe2_gpu.vcxproj" (default target) (22) ->
(CustomBuild target) ->
  c:\users\<username>\desktop\pytorch\third_party\eigen\eigen\src/Core/arch/CUDA/Half.h(212): error : more than one instance of overloaded function "__hadd" matches the argument list: [C:\Users\<username>\Desktop\pytorch
\build\caffe2\caffe2_gpu.vcxproj]

## Expected behavior
Build to complete properly

## Environment
Windows

```
Collecting environment information...
PyTorch version: 1.0.0a0+0f9807e
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Pro
GCC version: (Rev5, Built by MSYS2 project) 5.3.0
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 397.93
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda90                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py36_cuda90_cudnn7he774522_1    pytorch
[conda] torch                     1.0.0a0+0f9807e           <pip>
[conda] torchtext                 0.2.3                     <pip>
[conda] torchvision               0.2.0                     <pip>
[conda] torchvision-nightly       0.2.1                     <pip>
```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): given above
 - Python version:3.6.6
 - CUDA/cuDNN version:9.0
 - GPU models and configuration:GTX 1080
 - Any other relevant information: N/A

## Additional context

To fix the error and ensure that the compile is successful,  Modify the following lines in (where pytorch git source is cloned)
~\Desktop\pytorch\third_party\eigen\Eigen\src\Core\arch\CUDA\Half.h

EIGEN_STRONG_INLINE __device__ half operator + (const half& a, const half& b) {
  return __hadd(::__half(a), ::__half(b));
//  return __hadd(a, b);
}
EIGEN_STRONG_INLINE __device__ half operator * (const half& a, const half& b) {
  return __hmul(a, b);
}
EIGEN_STRONG_INLINE __device__ half operator - (const half& a, const half& b) {
  return __hsub(a, b);
}
EIGEN_STRONG_INLINE __device__ half operator / (const half& a, const half& b) {
  return __hdiv(a, b);
//  float num = __half2float(a);
//  float denom = __half2float(b);
//  return __float2half(num / denom);
}

**Comment by IlyaOvodov** [comment]
Very strange. I have tha same issue:
.... "C:\Users<username>\Desktop\pytorch\build\caffe2\caffe2_gpu.vcxproj" (default target) (22) ->
(CustomBuild target) ->
c:\users<username>\desktop\pytorch\third_party\eigen\eigen\src/Core/arch/CUDA/Half.h(212): error : more than one instance of overloaded function "__hadd" matches the argument list:  ....

But I have no file pytorch\third_party\eigen\Eigen\src\Core\arch\CUDA\Half.h
Where is Half.h in pytorch_ovod\third_party\eigen\Eigen\src\Core\arch\GPU, but it already has patch you've mentioned applyed. And it is in lines 274..293. Line 212 there is "namespace std {"

**Comment by zion302** [comment]
i had the similar problem, but different error.  it seems the error occurred when building 'torch._C' extension:
`
C:\MinGW64\mingw64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:/CUDA/v9.0\include -ID:\tmp\pytorch -ID:\tmp\pytorch\torch\lib/tmp_install/include -ID:\tmp\pytorch\torch\lib/tmp_install/include/TH -ID:\tmp\pytorch\torch\lib/tmp_install/include/THNN -ID:\tmp\pytorch\torch\lib/tmp_install/include/ATen -ID:\tmp\pytorch\third_party/pybind11/include -ID:\tmp\pytorch\torch\csrc -Ibuild/third_party -ID:\Programs\Anaconda3\lib\site-packages\numpy\core\include "-IC:/Program Files/NVIDIA Corporation/NvToolsExt/include" -IC:/CUDA/v9.0\include -ID:\tmp\pytorch\torch\lib/tmp_install/include/THCUNN -ID:\Programs\Anaconda3\include -ID:\Programs\Anaconda3\include -c torch/csrc/DataLoader.cpp -o build\temp.win-amd64-3.6\Release\torch\csrc\dataloader.o -D_THP_CORE -DONNX_NAMESPACE=onnx_torch /MD /Z7 /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 -DUSE_NUMPY -DUSE_CUDA -DCUDA_LIB_PATH=C:/CUDA/v9.0/lib/x64/ -DUSE_CUDNN
gcc: error: /MD: No such file or directory
gcc: error: /Z7: No such file or directory
gcc: error: /EHa: No such file or directory
gcc: error: /DNOMINMAX: No such file or directory
gcc: error: /wd4267: No such file or directory
gcc: error: /wd4251: No such file or directory
gcc: error: /wd4522: No such file or directory
gcc: error: /wd4522: No such file or directory
gcc: error: /wd4838: No such file or directory
gcc: error: /wd4305: No such file or directory
gcc: error: /wd4244: No such file or directory
gcc: error: /wd4190: No such file or directory
gcc: error: /wd4101: No such file or directory
gcc: error: /wd4996: No such file or directory
gcc: error: /wd4275: No such file or directory
error: command 'C:\\MinGW64\\mingw64\\bin\\gcc.exe' failed with exit status 1
`

it is surprised to me that gcc was called to compile it. while i checked CI build log, it used VC (cl and link):

`building 'torch._C' extension
creating build\temp.win-amd64-3.7
creating build\temp.win-amd64-3.7\Release
creating build\temp.win-amd64-3.7\Release\torch
creating build\temp.win-amd64-3.7\Release\torch\csrc
[1/1] "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\cl.exe" /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Jenkins\Miniconda3\lib\site-packages\numpy\core\include -IC:\Jenkins\Miniconda3\include -IC:\Jenkins\Miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /EHsc /Tptorch/csrc/stub.cpp /Fobuild\temp.win-amd64-3.7\Release\torch/csrc/stub.obj -D_THP_CORE -DONNX_NAMESPACE=onnx_torch /MD /Z7 /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 -DUSE_NUMPY
cl : Command line warning D9025 : overriding '/MT' with '/MD'
cl : Command line warning D9025 : overriding '/EHs' with '/EHa'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build\torch\lib /LIBPATH:C:\Jenkins\Miniconda3\libs /LIBPATH:C:\Jenkins\Miniconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /LIBPATH:C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build\mkl\lib /LIBPATH:LIB shm.lib /EXPORT:PyInit__C build\temp.win-amd64-3.7\Release\torch/csrc/stub.obj /OUT:build\lib.win-amd64-3.7\torch\_C.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\torch/csrc\_C.cp37-win_amd64.lib /NODEFAULTLIB:LIBCMT.LIB C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build\torch\lib\caffe2.lib C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build\torch\lib\c10.lib C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build\torch\lib\torch_python.lib 
   Creating library build\temp.win-amd64-3.7\Release\torch/csrc\_C.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\torch/csrc\_C.cp37-win_amd64.exp
Generating code
Finished generating code
building 'caffe2.python.caffe2_pybind11_state' extension
ninja: no work to do.
copying build/temp.win-amd64-3.7/Release/torch/csrc/_C.cp37-win_amd64.lib -> build/lib.win-amd64-3.7/torch/lib/_C.lib
running install_lib
creating C:\Jenkins\Miniconda3\Lib\site-packages\caffe2` 

i tried both cuda90.bat scripts provided by [here](https://github.com/peterjc123/pytorch-scripts), and the [official instruction](https://github.com/pytorch/pytorch#from-source), had the same problem.
Anyone got idea what might have caused that? thanks.

**Comment by evgeniikozlov** [comment]
> it is surprised to me that gcc was called to compile it. while i checked CI build log, it used VC (cl and link):

Had the same problem, solved by adding `--compiler=msvc` to `python setup.py build` call

**Comment by yf225** [comment]
It seems that the issue has been resolved. I am closing it.
