### ISSUE TITLE
Give non-differentiable output None grad in Python autograd fn

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#12631]
https://github.com/pytorch/pytorch/blob/0c6ab0e8f43ded4a67b444f3b4c08673409ef6ca/torch/autograd/function.py#L53-L54
This is currently a lie. They somehow get all zero grad in backward. And somehow we rely on this behavior at
https://github.com/pytorch/pytorch/blob/0c6ab0e8f43ded4a67b444f3b4c08673409ef6ca/torch/nn/parallel/_functions.py#L31-L43

**Comment by gchanan** [comment]
ya, we changed this at some point because backwards functions were too difficult to write.  We should update the comment.

**Comment by SsnL** [comment]
closed by #17891
