### ISSUE TITLE
Improve discoverability of meta function registration in documentation

### ISSUE THREAD

**Issue by david20571015** [pytorch/pytorch#126337]
### 📚 The doc issue

While working with `torch._foreach_pow_` in #125440, I encountered an error in the CI:

```
NotImplementedError: aten::_foreach_pow_.Scalar: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered.
You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add a fake impl.
Please see the following doc for next steps: https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU/edit
```

After reading the Google doc, I still don't know how to fix it because I'm not familiar with the PyTorch C++ backend. Finally, the reviewer told me that I need to add an overload in torch/_meta_registrations.py. I think it is a little difficult for python contributors to find this solely. (I searched for _meta_registrations in vscode and found pytorch/docs/source/torch.compiler_dynamic_shapes.rst, which led me to [The dynamic shapes manual](https://docs.google.com/document/d/1GgvOe7C8_NVOMLOCwDaYV1mXXyHMXY7ExoewHqooxrs/edit#heading=h.meijpmvqfmpe). The document instructed me to register a meta function, but there is no example provided, I had to figure out what other functions in torch/_meta_registrations.py do before registering the one I need.)

### Suggest a potential alternative/fix

Include a clear reference or FQA about using the python functions in pt2.

cc @svekars @brycebortree @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @zou3519

**Comment by xmfan** [comment]
cc @rzou

**Comment by ezyang** [comment]
I guess the problem is we don't have a dedicated doc for adding meta functions to PyTorch core

**Comment by ezyang** [comment]
I edited the custom op doc to have a little more information, not sure if this is enough in your opinion.

**Comment by david20571015** [comment]
> I edited the custom op doc to have a little more information, not sure if this is enough in your opinion.

Do you mean this?
![image](https://github.com/pytorch/pytorch/assets/51911434/46d206a0-b65a-4df5-911c-16e0ca737bd8)

Thanks for this, it provides better information.
