### ISSUE TITLE
Pytorch C++: How to divide Tensor by a Tensor with gradient?

### ISSUE THREAD

**Issue by slaweku** [pytorch/pytorch#12637]
Hi, 
I am trying to port my Python code to C++ frontend, and got stuck on a following issue:
I am trying to divide a "normal" tensor obtained by
Tensor input1_t = at::native::from_blob(input_vect.data(),{INPUT_SIZE});
by a Tensor with gradient, derived by some simple formulas from a parameter of the model 
Now I want to calculate
            Tensor lev_t=levels_tVect[i][0];  //scalar with gradient
            Tensor input11_t=input1_t/lev_t;
and it dies on the second line with
libc++abi.dylib: terminating with uncaught exception of type at::Error: copy_from does not support automatic differentiation; use copy_ instead (_s_copy_from at /Users/administrator/nightlies/2018_10_08/wheel_build_dirs/libtorch_2.7/pytorch/torch/csrc/autograd/generated/VariableType.cpp:431)
frame #0: at::CPUFloatType::s_copy_(at::Tensor&, at::Tensor const&, bool) const + 288 (0x101365880 in libcaffe2.dylib)
frame #1: at::TypeDefault::copy_(at::Tensor&, at::Tensor const&, bool) const + 363 (0x10148aecb in libcaffe2.dylib)
frame #2: at::TypeDefault::copy(at::Tensor const&, bool, at::optional<at::Device>) const + 627 (0x10148b333 in libcaffe2.dylib)
frame #3: at::TensorIterator::compute_common_type() + 907 (0x1012bcb3b in libcaffe2.dylib)
frame #4: at::TensorIterator::Builder::build() + 63 (0x1012bfb1f in libcaffe2.dylib)
frame #5: at::TensorIterator::binary_op(at::Tensor&, at::Tensor const&, at::Tensor const&) + 436 (0x1012bf984 in libcaffe2.dylib)
frame #6: at::native::div_out(at::Tensor&, at::Tensor const&, at::Tensor const&) + 140 (0x1011b663c in libcaffe2.dylib)
frame #7: at::native::div(at::Tensor const&, at::Tensor const&) + 34 (0x1011b6d62 in libcaffe2.dylib)
frame #8: at::TypeDefault::div(at::Tensor const&, at::Tensor const&) const + 111 (0x1014cd5cf in libcaffe2.dylib)
frame #9: at::Tensor::div(at::Tensor const&) const + 82 (0x1000681b2 in ctorch1)
frame #10: at::operator/(at::Tensor const&, at::Tensor const&) + 36 (0x10005a274 in ctorch1)
frame #11: main + 51199 (0x100041c4f in ctorch1)
frame #12: start + 1 (0x7fff718bd015 in libdyld.dylib)

Regards,
Slawek

**Comment by goldsborough** [comment]
Hi! The fix should be simple. Replace
```cpp
at::Tensor input1_t = at::native::from_blob(input_vect.data(),{INPUT_SIZE});
```

with 

```cpp
Tensor input1_t = torch::from_blob(input_vect.data(),{INPUT_SIZE});
```

Using `torch::` instead of `at::` for creating a tensor will give you a variable instead of a non-gradient recording tensor.

In general, you should never have to use `at::native`. If you are including `torch/torch.h`, you can in fact use `torch::` instead of `at::` for everything and you won't ever run into any problems. We export everything from `at::` into the `torch::` namespace. For example:

```cpp
torch::Tensor x = torch::randn({3, 4});
auto y = torch::relu(x);
```

Let me know if you have questions or run into any other issues.

**Comment by soumith** [comment]
closing based on Peter's comments

**Comment by slaweku** [comment]
Thank you very much, the problem is gone.
