### ISSUE TITLE
Prune old branches when browsing the grad graph

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#12635]
Consider [this simple script](https://gist.github.com/kyunghyuncho/5fb9991ce1233f909051854a84b7148e).

Even though the work done at every iteration (including `torch.autograd.grad`) seems constant, it shows some noticeable slow downs after a number of iterations. This is because `torch.autograd.grad` needs to browse the whole graph built so far, because we don't have any ways of proving that some branches have no effect on `M`. We might want to consider having some "approximate timestamps" that would let us prune the search if we discover that we're in a part of the graph that provably has been constructed before this value has even been materialized.

**Comment by ArmenAg** [comment]
This is a very interesting example. I'd love to work on this problem. @apaszke I'm semi-familiar with how PyTorch implements autograd, any pointers with where I should be looking?

**Comment by kyunghyuncho** [comment]
@apaszke i think the approximate timestamp idea is fascinating. i think it may even be useful for other purposes such as debugging, when many packages are loaded and used on a common set of variables and computations.

**Comment by egrefen** [comment]
I think we are seeing similar issues in `higher`, e.g.: https://github.com/facebookresearch/higher/issues/20.
