### ISSUE TITLE
Add `str` type to `device` parameter of `torch.cuda.get_device_name()` on the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#126400]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.cuda.get_device_name.html) explains `device` parameter but it doesn't have `str` type as shown below:

> device ([torch.device](https://pytorch.org/docs/stable/tensor_attributes.html#torch.device) or [int](https://docs.python.org/3/library/functions.html#int), optional) – device for which to return the name. This function is a no-op if this argument is a negative integer. It uses the current device, given by [current_device()](https://pytorch.org/docs/stable/generated/torch.cuda.current_device.html#torch.cuda.current_device), if [device](https://pytorch.org/docs/stable/generated/torch.cuda.device.html#torch.cuda.device) is None (default).

Actually, `device` parameter with `str` type works as shown below:

```python
import torch

torch.cuda.get_device_name(device='cuda:0') # Tesla T4
```

### Suggest a potential alternative/fix

[The doc](https://pytorch.org/docs/stable/generated/torch.cuda.get_device_name.html) should also say `str` type as shown below:

> device ([torch.device](https://pytorch.org/docs/stable/tensor_attributes.html#torch.device), [int](https://docs.python.org/3/library/functions.html#int) or `str`, optional) – device for which to return ...

cc @ptrblck @msaroufim @albanD

**Comment by shink** [comment]
this case works because the string you passed in will be used to create an `torch.device` object, so I think it's unnecessary to update the doc and any suggestions are welcome

https://github.com/pytorch/pytorch/blob/6c503f1dbbf9ef1bf99f19f0048c287f419df600/c10/core/Device.h#L41-L46

**Comment by albanD** [comment]
Yes updating the doc sounds good.
If you need typing, you can use https://github.com/pytorch/pytorch/blob/2f53747ec6157f8a4169cd01355ea91979b3dc40/torch/types.py#L39
