### ISSUE TITLE
Installing PyTorch on armv7l

### ISSUE THREAD

**Issue by manoharvhr** [pytorch/pytorch#12644]
Hi,

I am trying to install PyTorch v0.4.1 on the PYNQ Z1 Board (amrv7l 32-bit Architecture).

Python version: 3.6.5
GCC version: 7.3

Install flags: 
export NO_CUDA=1
export NO_DISTRIBUTED=1

Build Command:
python3 setup.py build

### build log attached
[buildlogFor41Python36 (1).txt](https://github.com/pytorch/pytorch/files/2478299/buildlogFor41Python36.1.txt)

### CMakeError.log attached
[CMakeError.log](https://github.com/pytorch/pytorch/files/2478303/CMakeError.log)

**Comment by manoharvhr** [comment]
Hi, 

Yes it works now. You have to set the number of jobs to 1

**Comment by jstran97** [comment]
Sorry for posting on a closed thread, but if possible, can you please elaborate on the process you took? I am working on a school project and have exhausted most avenues on how to install PyTorch on a PYNQ Z1 board. 

Python version on PYNQ Z1:  3.6.5
Pip version:  9.0.1

Thank you

**Comment by manoharvhr** [comment]
How long do you have?

**Comment by jstran97** [comment]
We have until around April 2020, but this is the first step of the project and we've been stuck on it ever since June.

Our PYNQ Z1 currently has the version 2.4 image, which has the NumPy and the SciPy libraries included in it.

**Comment by manoharvhr** [comment]
I have actually developed a framework for developers to use hardware accelerators with pytorch as my Thesis project. I will soon be having a git page and paper supporting it.

**Comment by jstran97** [comment]
Thank you so much for taking your time to read and reply to our posts! We really appreciate it! We'll be looking forward to its release!

**Comment by manoharvhr** [comment]
No problem! I was at your stage in my project so I know how frustrating it is to not find resources on PYNQ. I will reply to this thread once I have published.

**Comment by manoharvhr** [comment]
Hi @jstran97, I believe what you are looking for can now be found [here](https://github.com/manoharvhr/PYNQ-Torch).

Goodluck!

**Comment by jstran97** [comment]
@manoharvhr Thank you so much for keeping us up to date with your project and its release! We're so glad that you decided to contact us upon doing so! We're also greatly in your debt!
