### ISSUE TITLE
[ONNX] dynamo_export always uses external ONNX weights if the argument is ExportedProgram, even for small models

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#126479]
### 🐛 Describe the bug

dynamo_export always uses external ONNX weights if the argument is ExportedProgram.
dynamo_export never  uses external ONNX weights if the argument is Module - I filed separate issue for that.
This behavior is inconsistent with what onnx.export() had and forces users to calculate memory requirements themselves and branch on that.

### Versions

Pytorch nightly 05/14/24

**Comment by borisfom** [comment]
This may be acceptable behavior if https://github.com/pytorch/pytorch/issues/126269 were fixed. Then user could always call dynamo_export(exported_program.module()) which would be the same behavior as onnx.export in terms of external weights.

**Comment by titaiwangms** [comment]
cc @justinchuby @shubhambhokare1 @xadupre 
We should discuss about this.

**Comment by titaiwangms** [comment]
> cc @justinchuby @shubhambhokare1 @xadupre We should discuss about this.

We can leverage on "unlifting" in ExportedProgram.

**Comment by borisfom** [comment]
@titaiwangms : any news on this?

**Comment by titaiwangms** [comment]
Hi @borisfom,

Yes, we have a series of refactors ongoing, and the ultimate goal is to migrate torch.export.export into dynamo_export. The external weights would become initializers most likely at the time.

**Comment by borisfom** [comment]
@titaiwangms : any timeline on that? The main problem with the external format ONNX produced by dynamo_export is that it's neither runnable with ONNXRuntime nor consumable by TensorRT.

**Comment by justinchuby** [comment]
> @titaiwangms : any timeline on that? The main problem with the external format ONNX produced by dynamo_export is that it's neither runnable with ONNXRuntime nor consumable by TensorRT.

This will be part of the exporter improvement we do this month
