### ISSUE TITLE
error: ImportError: /anaconda3/lib/python3.6/site-packages/torch/lib/libTHC.so.1: cannot read file data

### ISSUE THREAD

**Issue by mohammad-py** [pytorch/pytorch#1264]
Hi
I have upgarde my pytorch version to 0.1.11 with: `conda update pytorch torchvision -c soumith`. and with this command `conda list | grep pytorch` verified the new version upgarding. But when I want to import torch package, I receive this error:

> Traceback (most recent call last):
>   File "YOLO_demo_v3_offline.py", line 1, in <module>
>     import torch
>   File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
>     from torch._C import *
> ImportError: /home/mohammad/anaconda3/lib/python3.6/site-packages/torch/lib/libTHC.so.1: cannot read file data

So What should if do then?

**Comment by soumith** [comment]
hi mohammad.
do you have free space on your computer?
Maybe try:
```
conda clean
conda uninstall pytorch
conda install pytorch torchvision -c soumith
```

**Comment by mohammad-py** [comment]
Actually I have lots of free space on my computer. 
I will try these command and give feedback to you!

**Comment by mohammad-py** [comment]
@soumith `conda clean gives me an error`

> ArgumentError: One of {--lock, --tarballs, --index-cache, --packages, --source-cache, --all} required

**Comment by mohammad-py** [comment]
@soumith Hi again soumith, I did above code but it gives me same error:

> >>> import torch
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
>     from torch._C import *
> ImportError: /home/mohammad/anaconda3/lib/python3.6/site-packages/torch/lib/libTHC.so.1: cannot read file data

**Comment by soumith** [comment]
he solved this by first uninstalling and then reinstalling
