### ISSUE TITLE
2D TP+FSDP with device mesh

### ISSUE THREAD

**Issue by ad8e** [pytorch/pytorch#126548]
### 📚 The doc issue

At https://pytorch.org/docs/stable/fsdp.html, there is an undocumented argument `device_mesh`. This is necessary for DTensor TP, as TP support was added for `device_mesh` but not for `process_group`. Attempting to use `process_group` produces the following error: `RuntimeError: Attempted to call resize_() on an invalid python storage.`

### Suggest a potential alternative/fix

Document `device_mesh`. For `process_group`, mention that it will not work with Tensor Parallel.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

**Comment by wz337** [comment]
Thanks for reporting the issue. We will submit a PR to fix this soon.
