### ISSUE TITLE
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.

### ISSUE THREAD

**Issue by ZJDATY** [pytorch/pytorch#126507]
### 🐛 Describe the bug

```
python
import torch
```
**### log**
![image](https://github.com/pytorch/pytorch/assets/29767049/9eb5b6a5-ea72-4dba-acc1-28066973c8ca)

```
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
```

I have installed this vc-resist.x64.exe. And there was no such warning before.I don't know what I've done recently that caused this warning to appear.I am using the Conda environment, and the pytorch installed in my other virtual environment did not show this warning.I searched for similar errors and tested them according to their methods.
https://github.com/pytorch/pytorch/issues/65214

```
where msvcp140.dll
where vcruntime140.dll
where vcruntime140_1.dll
```
Output:
```
(yolov-8) D:\pyworkspaces\deeplabv3-plus-pytorch>where msvcp140.dll
D:\ProgramData\Anaconda3\envs\yolov-8\msvcp140.dll
D:\ProgramData\Anaconda3\envs\yolov-8\Library\bin\msvcp140.dll
C:\Windows\System32\msvcp140.dll
D:\ProgramData\Anaconda3\msvcp140.dll
D:\ProgramData\Anaconda3\Library\bin\msvcp140.dll
D:\Program Files\JetBrains\PyCharm 2022.3.1\bin\msvcp140.dll

(yolov-8) D:\pyworkspaces\deeplabv3-plus-pytorch>where vcruntime140.dll
D:\ProgramData\Anaconda3\envs\yolov-8\vcruntime140.dll
D:\ProgramData\Anaconda3\envs\yolov-8\Library\bin\vcruntime140.dll
C:\Windows\System32\vcruntime140.dll
D:\ProgramData\Anaconda3\vcruntime140.dll
D:\ProgramData\Anaconda3\Library\bin\vcruntime140.dll

(yolov-8) D:\pyworkspaces\deeplabv3-plus-pytorch>where vcruntime140_1.dll
D:\ProgramData\Anaconda3\envs\yolov-8\vcruntime140_1.dll
D:\ProgramData\Anaconda3\envs\yolov-8\Library\bin\vcruntime140_1.dll
C:\Windows\System32\vcruntime140_1.dll
D:\ProgramData\Anaconda3\vcruntime140_1.dll
D:\ProgramData\Anaconda3\Library\bin\vcruntime140_1.dll
```

I have tried several solutions, including reinstalling the VS runtime software prompted, reinstalling different versions of Torch, and restarting the computer many times.

### Versions

```
(yolov-8) D:\pyworkspaces\deeplabv3-plus-pytorch>python collect_env.py
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.27.1
Libc version: N/A

Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: GRID RTX8000-24Q
Nvidia driver version: 474.44
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3600
DeviceID=CPU0
Family=1
L2CacheSize=
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3600
Name=Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz
ProcessorType=3
Revision=21767

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] onnx==1.13.1
[pip3] onnx-simplifier==0.4.26
[pip3] onnxconverter-common==1.14.0
[pip3] onnxruntime==1.14.1
[pip3] onnxsim==0.4.35
[pip3] torch==2.0.1+cu118
[pip3] torch-tb-profiler==0.4.3
[pip3] torchaudio==2.0.2+cu118
[pip3] torchvision==0.15.2+cu118
[conda] mkl                       2021.4.0                 pypi_0    pypi
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.0.1+cu118              pypi_0    pypi
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchaudio                2.0.2+cu118              pypi_0    pypi
[conda] torchvision               0.15.2+cu118             pypi_0    pypi

```

cc @seemethere @malfet @osalpekar @atalman @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by mikaylagawarecki** [comment]
Seems related to https://github.com/pytorch/pytorch/issues/65214

**Comment by ZJDATY** [comment]
> Seems related to #65214

I feel like I've encountered the same problem, but its problem hasn't been resolved either.I want to know what are the criteria for judging this warning? Has an error occurred?

**Comment by alinpahontu2912** [comment]
Hey @ZJDATY, what is the status of this issue?  Have you tried updating the pytorch version to the latest one, is it still happening, as I can not reproduce this?

**Comment by ZJDATY** [comment]
> Hey @ZJDATY, what is the status of this issue? Have you tried updating the pytorch version to the latest one, is it still happening, as I can not reproduce this?

I don't know how this problem came about, but it still exists. I just need to configure a new conda environment. The problem still exists in old virtual environment.

**Comment by iremyux** [comment]
Hello @ZJDATY , the warning that you see comes from here: https://github.com/pytorch/pytorch/blob/main/torch/__init__.py#L221-L233 . 
We've experienced the same problem on Windows Arm64 and prepared a PR: https://github.com/pytorch/pytorch/pull/139746

As we were unable to reproduce it on x64 and due to inactivity, I'm closing this issue. 

Please feel free to open new issues if you encounter a problem or have a feature request.
