### ISSUE TITLE
With extremely large input 1D convolution manages memory unexpectedly

### ISSUE THREAD

**Issue by olyaromanyuk** [pytorch/pytorch#12651]
## 🐛 Bug

For extremely large inputs ( approximately 5\*100,000,000) the training process behaves very differently for different but very close input sizes. For size 5\*97,825,587 and smaller training runs ok for more than 10 epochs, for the size 5\*97,825,588 and larger training fails during the second epoch with RuntimeError: CUDA error: out of memory

## To Reproduce
```
import torch
import torch.nn as nn
import torch.optim as optim

torch.cuda.set_device(1)

sequence_length = 97825587
print(sequence_length)

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv1d(in_channels=5, out_channels=1, kernel_size=sequence_length, stride=10)

    def forward(self, x):
        x = self.conv1(x)
        x = torch.sigmoid(x)
        return x

model = Net().cuda()

optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = torch.nn.BCELoss()

data = torch.normal(torch.zeros(1, 5, sequence_length), torch.ones(1, 5, sequence_length))
data = data.cuda()
label = torch.ones(1, 1, 1)
label = label.cuda()

for epoch in range(10):
    output = model(data)
    print(output.shape)

    loss = criterion(output, label)

    optimizer.zero_grad()
    loss.backward()

    optimizer.step()


    event = 'Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(epoch, 1 * len(data),
                                                                     1,
                                                                     100. * 1 / 1,
                                                                     float(loss) / 1)
    print(event)

```

1. Run the code with `sequence_length = 97825587` and `sequence_length = 97825588`

## Expected behavior

Fail during the second epoch doesn't look right, if the input is too large the training should fail during the first epoch. 
I was monitoring the memory usage, the training with smaller input used 12199Mb, with a bit larger input first epoch was finished with 11640Mb used and during backpropagation in the second epoch, the error was encountered.
I think some small memory leak is unlikely if it was the case the training with a bit smaller input would run out of memory during one of the epochs.
I assume that the cause is likely somewhere in the implementation of convolution. The convolution I use in the code is equivalent to a linear layer, it calculates the same output and has the same number of parameters, but I could not find the same behaviour with linear layer

## Environment

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X
GPU 2: GeForce GTX TITAN X
GPU 3: GeForce GTX TITAN X

Nvidia driver version: 390.87
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

The issue is not unique for version 0.4, I've tested it with 2018/10/15 nightly build, the exact input size where behavior changes moved, but the issue is still there. 

## Additional context

I've designed the code above to understand the memory usage of convolutional layers, here are links to my questions at Pytorch Forums and StackOverflow, maybe you will find something useful there
- https://discuss.pytorch.org/t/with-extremely-large-input-1d-convolution-uses-memory-inefficiently/27066
- https://stackoverflow.com/questions/52762173/pytorch-convolutional-network-memory-usage-details

I think, that this issue is related to what is described here
- https://discuss.pytorch.org/t/how-to-free-gpu-memory-and-delete-memory-allocated-variables/20856

**Comment by SsnL** [comment]
The memory usage is decided by cuDNN so we don't know what magic it does inside.
