### ISSUE TITLE
DCP sees 1/2 of the expected size of each tensor in 3D parallel

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#126595]
Quite possibly this is a bug in the 3d parallel implementation itself, but i'm trying to debug why i see this warning, and subsequently fail with `ValueError: Failed to validate global plan`:

`torch/distributed/checkpoint/default_planner.py:495]  key:model.layers.0.attention.wq.weight invalid fill tensor-volume:  65536 chunks-volume: 32768`

The repro is on the 8gpu CI for https://github.com/pytorch/torchtitan/pull/344.  ([log link](https://productionresultssa15.blob.core.windows.net/actions-results/b043f4bd-a018-438f-a8c7-72e551205b49/workflow-job-run-9a8e0ff0-767a-58e1-2be7-161de24c199d/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-05-18T00%3A19%3A22Z&sig=RWrv5WDsnTJlJVuxthT4kCk8d9kNROB9xsNXLto1W%2FA%3D&sp=r&spr=https&sr=b&st=2024-05-18T00%3A09%3A17Z&sv=2021-12-02))

The same warning issues for every weight in the model.  For the remainder i'll focus on just one, `model.layers.0.attention.wq.weight`

DCP sees the shape of wq.weight as [256, 256], which is the correct full shape of the wq.weight per the model code.

some debugging..
```
p key
[rank0]:(Pdb) [rank0]:'model.layers.0.attention.wq.weight'

p value
[rank0]:(Pdb) [rank0]:TensorStorageMetadata(properties=TensorProperties(dtype=torch.float32, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False), size=torch.Size([256, 256]), chunks=[ChunkStorageMetadata(offsets=torch.Size([0, 0]), sizes=torch.Size([64, 256])), ChunkStorageMetadata(offsets=torch.Size([64, 0]), sizes=torch.Size([64, 256]))])
```

It looks like DCP only sees 2 chunks of size 64.  I'm wondering if sharding for both fsdp and TP are happening on the same dim and one of those shardings is being ignored here?

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @yf225 @chauhang @d4l3k @LucasLLC

**Comment by fegin** [comment]
What are the `model.layers.0.attention.wq.weight._spec` on all the ranks that have this weight when saving the model?

**Comment by wconstab** [comment]
`model.layers.0.attention.wq.weight._spec` prints out on rank 0, 1, 2, 3 as 
`Spec((Shard(dim=0), Shard(dim=0)) on (256, 256))`.  (ranks 4-7 don't have this param).

**Comment by fegin** [comment]
https://github.com/pytorch/pytorch/pull/127071 will fix the issue.
