### ISSUE TITLE
Ansys Rocky: cuda error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by virat-0527** [pytorch/pytorch#126675]
### 🐛 Describe the bug

I am running simulations with DEM and SPH particles in Ansys Rocky 2024. The simulations I am trying to run is in NVIDIA RTX 4090, but it is generating error after sometime. I tried to run the simulation in CPU and it works.
The error generated is "cuda error: an illegal memory access was encountered, code = 700
file: K:\rocky20\source\c++\rocky20\sph\sph_search.cu: line 1575"

Could you help me out with this?

### Versions

I am running simulations with DEM and SPH particles in Ansys Rocky 2024. The simulations I am trying to run is in NVIDIA RTX 4090, but it is generating error after sometime. I tried to run the simulation in CPU and it works.
The error generated is "cuda error: an illegal memory access was encountered, code = 700
file: K:\rocky20\source\c++\rocky20\sph\sph_search.cu: line 1575"

Could you help me out with this?

**Comment by jbschlosser** [comment]
Hey @virat-0527, I suggest posting on the [PyTorch forums](https://discuss.pytorch.org/), as you're more likely to receive assistance there. Note that the issues here are reserved for problems within PyTorch itself. Closing for now but feel free to reopen if a bug is identified within PyTorch through forum discussion.
