### ISSUE TITLE
saved_tensors_hooks auto delete custom attributes

### ISSUE THREAD

**Issue by godweiyang** [pytorch/pytorch#126676]
### 🐛 Describe the bug

I have a custom attribute defined in the saved tensors. But after unpacking, the attribute is deleted by the hook. How can I obtain the attribute?

```python
import torch

class f(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, w):
        y = x @ w
        ctx.save_for_backward(x, w)
        return y

    def backward(ctx, grad_output):
        x, w = ctx.saved_tensors
        print(hasattr(x, "aaa"))  # the custom attribute is deleted
        return grad_output @ w.t(), x.t() @ grad_output

def pack_hook(tensor):
    tensor.aaa = 1
    return tensor
        
def unpack_hook(tensor):
    print(tensor.aaa)  # the custom attribute still exists before unpack returns
    return tensor

x = torch.randn(100, 200).bfloat16().cuda().requires_grad_()
w = torch.randn(200, 300).bfloat16().cuda().requires_grad_()
with torch.autograd.graph.saved_tensors_hooks(pack_hook, unpack_hook):
    y = f.apply(x, w).sum()
    y.backward()
```

The result is:
```
1
1
False
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230815+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.4.143.bsk.7-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB
GPU 2: NVIDIA A800-SXM4-80GB
GPU 3: NVIDIA A800-SXM4-80GB
GPU 4: NVIDIA A800-SXM4-80GB
GPU 5: NVIDIA A800-SXM4-80GB
GPU 6: NVIDIA A800-SXM4-80GB
GPU 7: NVIDIA A800-SXM4-80GB

Nvidia driver version: 470.214
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          120
On-line CPU(s) list:             0-119
Thread(s) per core:              2
Core(s) per socket:              30
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         2294.608
BogoMIPS:                        4589.21
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       2.8 MiB
L1i cache:                       1.9 MiB
L2 cache:                        75 MiB
L3 cache:                        108 MiB
NUMA node0 CPU(s):               0-59
NUMA node1 CPU(s):               60-119
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid md_clear arch_capabilities

Versions of relevant libraries:
[pip3] byted-torch==2.1.0.dev20230815
[pip3] byted-torch-monitor==0.0.1
[pip3] numpy==1.24.4
[pip3] onnx==1.14.1
[pip3] qtorch==0.3.0
[pip3] torch==2.1.0.dev20230815+cu121
[pip3] torchaudio==2.1.0.dev20230815+cu121
[pip3] torchlibrosa==0.1.0
[pip3] torchvision==0.16.0.dev20230815+cu121
[conda] Could not collect

cc @ezyang @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by natureLanguageQing** [comment]
在您的代码中，当您使用 `ctx.save_for_backward` 时，它内部会复制张量，因此当您在 `backward` 方法中通过 `ctx.saved_tensors` 获取这些张量时，您实际上得到的是这些张量的副本。在副本上添加的任何自定义属性或修改都不会被保留。
为了在反向传播过程中保留自定义属性，您应该在上下文对象 `ctx` 中保存这些属性，然后在 `backward` 方法中从上下文对象中检索它们。以下是修改后的代码：
```python
import torch
class f(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, w):
        y = x @ w
        ctx.save_for_backward(x, w)
        ctx.x_attr = getattr(x, "aaa", None)  # 保存 x 的自定义属性
        ctx.w_attr = getattr(w, "aaa", None)  # 保存 w 的自定义属性
        return y
    @staticmethod
    def backward(ctx, grad_output):
        x, w = ctx.saved_tensors
        x.aaa = ctx.x_attr  # 在 x 上恢复自定义属性
        w.aaa = ctx.w_attr  # 在 w 上恢复自定义属性
        print(hasattr(x, "aaa"))  # 现在 x 的自定义属性存在
        return grad_output @ w.t(), x.t() @ grad_output
def pack_hook(tensor):
    tensor.aaa = 1
    return tensor
        
def unpack_hook(tensor):
    print(tensor.aaa)  # 在解包返回之前，自定义属性仍然存在
    return tensor
x = torch.randn(100, 200).bfloat16().cuda().requires_grad_()
w = torch.randn(200, 300).bfloat16().cuda().requires_grad_()
with torch.autograd.graph.saved_tensors_hooks(pack_hook, unpack_hook):
    y = f.apply(x, w).sum()
    y.backward()
```
在这个修改后的版本中，我们在正向传播期间将 `x` 和 `w` 的自定义属性 `aaa` 保存在上下文对象 `ctx` 中。然后在反向传播期间，我们在使用这些张量之前将属性恢复到这些张量上。这样，自定义属性在整个反向传播过程中都得到了保留。

**Comment by albanD** [comment]
@soulitzer I guess there is a detach() or something there that makes the two not the same Tensor object. Do you think we could remove it?

**Comment by soulitzer** [comment]
I'm not sure we can remove it. When we smash the autograd metadata (e.g. grad_fn) back onto whatever was returned by the unpack hook, we may not want to do that in-place - if the user observes that grad_fn of their tensor changes it may be unexpected.

**Comment by albanD** [comment]
Ok!
Sounds like expected behavior then and a subclass should be used if you need a property that is preserved?
Alternatively, if you want a property being preserved accross different views of the same data, you can add your attribute to the `tensor.untyped_storage()`.

**Comment by soulitzer** [comment]
Closing as it is expected behavior.

**Comment by Sakura-gh** [comment]
meet the same problem:
log in `unpack_hook()`: 
```
weight: shape = torch.Size([4096, 2048]), attrs=dict_keys(['tensor_model_parallel', 'partition_dim', 'partition_stride', 'allreduce', 'grad_added_to_main_grad', 'main_grad']), requires_grad=True
```

log after `input, weight = ctx.saved_tensors`:
```
weight: shape = torch.Size([4096, 2048]), attrs = dict_keys([]), requires_grad=False
```

so the weight `requires_grad` attr will change?

**Comment by soulitzer** [comment]
Yes, that is correct. The requires_grad-ness should be preserved from whatever is originally saved for backward. The requires_grad-ness of what is returned from unpack_hook is ignored.
