### ISSUE TITLE
Libtorch build for ROCM error: “aten/src/THH” not exist

### ISSUE THREAD

**Issue by Fovini** [pytorch/pytorch#126640]
## Issue description

I want to build libtorch for rocm from source and followed the instructions from here:[Building libtorch using CMake](https://github.com/pytorch/pytorch/blob/main/docs/libtorch.rst). It occured this error:

```
CMake Error at aten/CMakeLists.txt:82 (add_subdirectory):
  add_subdirectory given source "src/THH" which is not an existing directory.
ROCm is enabled.

```
Directory “pytorch/aten/src/THH” does’t exist but it should be. According to pytorch/aten/CMakeLists.txt:

```
if(USE_ROCM)
  # TODO: AT_HIP_ENABLED (change this once we represent HIP as HIP in
  # ATen proper)
  set(AT_CUDA_ENABLED 1)
  add_subdirectory(src/THH)
  message("ROCm is enabled.")
elseif(USE_CUDA)
  set(AT_CUDA_ENABLED 1)
  add_subdirectory(src/THC)
```
If build for cuda, there exists the directory “pytorch/aten/src/THC”, but for rocm, the corresponding directory “THH” does not exist. I‘ve searched several versions pytorch source code, none of them have this directory.
So can someone tell me where can get this lost directory? Or have I missed something to install? I would appreciate for your help with this problem.

- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): 
`cmake -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON_EXECUTABLE:PATH=`which python3` -D CMAKE_PREFIX_PATH=/opt/rocm-6.1.0 -DCMAKE_INSTALL_PREFIX:PATH=../pytorch-install ../pytorch`
- OS: Fedora 37 6.5.12-100.fc37.x86_64
- PyTorch version: 2.3
- Python version: 3.11.6
- ROCM version: 6.1.0
- GCC version (if compiling from source): 12.3.1
- CMake version: 3.27.7

cc @malfet @seemethere @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
Looks like the doc you followed doesn't have the ROCm caveat for building from source, and that is you need to generate some of the sources before running the build.  There is an extra step of converting the CUDA sources into HIP sources.

```
# hipify sources
python tools/amd_build/build_amd.py
```

**Comment by hongxiayang** [comment]
Thanks for @Fovini reporting the issue and thanks  for @jeffdaily for the tips. Sounds like we should do an exercise of building libtorch from source successfully, and then update the documentation for ROCm.

**Comment by naromero77amd** [comment]
Go ahead and assign this one to me.

**Comment by naromero77amd** [comment]
@hongxiayang I think it would be sufficient to just add a small section to the documentation here:
https://github.com/pytorch/pytorch/blob/main/docs/libtorch.rst

That says:

> If you're compiling for AMD ROCm then first run this command:

```
# Only run this if you're compiling for ROCm
python tools/amd_build/build_amd.py
```

The language is taken from here:
https://github.com/pytorch/pytorch/tree/main?tab=readme-ov-file#install-pytorch

Let me know if this is sufficient or if more is needed.

**Comment by hongxiayang** [comment]
@naromero77amd Thanks for looking at this. I agree with your assessment. Please go ahead to create a PR and be sure it addresses the two ways of building libtorch.
