### ISSUE TITLE
"Either `torch.float32` or `torch.float64`" should be removed from the doc of `d` parameter of `torch.set_default_dtype()`

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#126647]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.set_default_device.html) explains `d` parameter but it only says **Either `torch.float32` or `torch.float64`** as shown below:

> d ([torch.dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype)) – the floating point dtype to make the default. Either torch.float32 or torch.float64.

Actually, `d` parameter with `torch.float16`, `torch.half`, `torch.bfloat16`, `torch.float` or `torch.double` type also works as shown below:

```python
import torch

torch.set_default_dtype(d=torch.float16)
torch.set_default_dtype(d=torch.half)
torch.get_default_dtype()
# torch.float16

torch.set_default_dtype(d=torch.bfloat16)
torch.get_default_dtype()
# torch.bfloat16

torch.set_default_dtype(d=torch.float32)
torch.set_default_dtype(d=torch.float)
torch.get_default_dtype()
# torch.float32

torch.set_default_dtype(d=torch.float64)
torch.set_default_dtype(d=torch.double)
torch.get_default_dtype()
# torch.float64
```

### Suggest a potential alternative/fix

So, `Either torch.float32 or torch.float64` should be removed from [the doc](https://pytorch.org/docs/stable/generated/torch.set_default_device.html) should say `int` type as shown below:

> d ([torch.dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype)) – the floating point dtype to make the default. 

cc @svekars @brycebortree @albanD

**Comment by LukaMarinkic** [comment]
I see what you mean. I will change it and then make a pull request. I think that this has a good chanche of geting  merged into the real thing

**Comment by jbschlosser** [comment]
Sure, we'd accept a PR for tweaking the docs to match what's actually supported.
