### ISSUE TITLE
The significant difference between the results of torch.reciprocal running on cpu and gpu

### ISSUE THREAD

**Issue by PhyllisJi** [pytorch/pytorch#126664]
### 🐛 Describe the bug

The model implementation code:
```python
class Model_zkanmC_TOhQwN6RFzwJmIiFKCxETHvht(nn.Module):
    def __init__(self):
        super(Model_zkanmC_TOhQwN6RFzwJmIiFKCxETHvht, self).__init__()
        self.conv1_mutated = torch.nn.ConvTranspose2d(in_channels=1, out_channels=6, kernel_size=[5, 5], stride=[1, 1], padding=[0, 0], output_padding=[0, 0], dilation=[1, 1], groups=1, bias=True)
        self.relu1 = torch.nn.ReLU()
        self.pool1_mutated = torch.nn.MaxPool2d(kernel_size=[2, 2], stride=[1, 2], padding=[0, 0], dilation=1, ceil_mode=False)
        self.conv2_mutated = torch.nn.Conv2d(in_channels=6, out_channels=16, kernel_size=[5, 5], stride=[8, 8], padding=[0, 0], dilation=[1, 1], groups=1, bias=True)
        self.relu2 = torch.nn.ReLU()
        self.pool2 = torch.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=1, ceil_mode=False)
        self.flatten = torch.nn.Flatten()
        self.linear1 = torch.nn.Linear(in_features=32, out_features=120)
        self.relu3_mutated = torch.reciprocal
        self.linear2 = torch.nn.Linear(in_features=120, out_features=84)
        self.tail_flatten = torch.nn.Flatten()
        self.tail_fc = torch.nn.Linear(in_features=84, out_features=10)
 def forward(self, input):
        conv1_output = self.conv1_mutated(input)
        relu1_output = self.relu1(conv1_output)
        maxpool1_output = self.pool1_mutated(relu1_output)
        conv2_output = self.conv2_mutated(maxpool1_output)
        relu2_output = self.relu2(conv2_output)
        maxpool2_output = self.pool2(relu2_output)
        flatten_output = self.flatten(maxpool2_output)
        fc1_output = self.linear1(flatten_output)
        relu3_output = self.relu3_mutated(fc1_output)
        fc2_output = self.linear2(relu3_output)
        tail_flatten_output = self.tail_flatten(fc2_output)
        tail_fc_output = self.tail_fc(tail_flatten_output)
        tail_fc_output = tail_fc_output
        return tail_fc_output
```
The Chebyshev distances between the outputs of related layers:
```
distances between linear1 outputs (The input of torch.reciprocal):  0.0001780986785888672 
difference positision ：[[856  35]] value: [(-0.3083343, -0.3085124)]
distances between reciprocal outputs：1054469.875
difference positision ：[[20 93]] value: [(1070818.0, 16348.122)]
```

### Versions

Collecting environment information...
PyTorch version: 2.2.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.19.0-14-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Ti
Nvidia driver version: 535.98
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          72
On-line CPU(s) list:             0-71
Thread(s) per core:              2
Core(s) per socket:              18
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:                        1
CPU MHz:                         1878.204
CPU max MHz:                     3000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4599.86
Virtualization:                  VT-x
L1d cache:                       1.1 MiB
L1i cache:                       1.1 MiB
L2 cache:                        9 MiB
L3 cache:                        90 MiB
NUMA node0 CPU(s):               0-17,36-53
NUMA node1 CPU(s):               18-35,54-71
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] onnx==1.16.0
[pip3] torch==2.2.0
[pip3] triton==2.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.0                    pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

**Comment by drisspg** [comment]
This issue as posted is not possible to debug. An ideal repro would be one that lets someone run something like `python repro.py` and reproduce the numerical issue. Since you dont provide inputs that is not possible. As well full models dumps are very difficult to debug. Typically if you could do some work to isolate where in the model that difference is occurring that would greatly aid someone on pytorch to debug. I am going to close this issue for lack of detail. Feel free to reopen with more detail, otherwise this might be a better post for dev discuss:

https://dev-discuss.pytorch.org/

**Comment by PhyllisJi** [comment]
> This issue as posted is not possible to debug. An ideal repro would be one that lets someone run something like `python repro.py` and reproduce the numerical issue. Since you dont provide inputs that is not possible. As well full models dumps are very difficult to debug. Typically if you could do some work to isolate where in the model that difference is occurring that would greatly aid someone on pytorch to debug. I am going to close this issue for lack of detail. Feel free to reopen with more detail, otherwise this might be a better post for dev discuss:
> 
> https://dev-discuss.pytorch.org/

I've simplified the code and provided inputs and comparison results that you can reproduce in a few easy steps.  https://github.com/PhyllisJi/MoCoDiff_Bug/blob/torch-%23126664/README.md
