### ISSUE TITLE
The `complex` type of a 0D tensor with `aminmax()` and `dim=0` or `dim=-1` works

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#126742]
### 🐛 Describe the bug

The `complex` type of a 0D tensor with [aminmax()](https://pytorch.org/docs/stable/generated/torch.aminmax.html) gets the error as shown below:

```python
import torch

my_tensor = torch.tensor(7.+5.j)

torch.aminmax(input=my_tensor) # RuntimeError: "aminmax_cpu" not implemented for 'ComplexFloat'
```

But the `complex` type of a 0D tensor with `aminmax()` and `dim=0` or `dim=-1` works as shown below:

```python
import torch

my_tensor = torch.tensor(7.+5.j)

torch.aminmax(input=my_tensor, dim=0)
torch.aminmax(input=my_tensor, dim=-1)
# torch.return_types.aminmax(
# min=tensor(7.+5.j),
# max=tensor(7.+5.j))
```

### Versions

```python
import torch

torch.__version__ # 2.2.1+cu121
```

**Comment by cyyever** [comment]
There is not order defined for complex numbers mathematically so that I would consider the dim case as a bug.

**Comment by janeyx99** [comment]
Yes, like @cyyever said, ordering isn't defined for these dtypes, so this is not unexpected.

Similar to other related issues with topk, argmin, etc, we would accept a PR that errors out for this op even on empty, single element tensors if dtype are complex or boolean types.

**Comment by ajbrent** [comment]
Seems like aminmax supports bools generally. This matches NumPy's treatment of min and max.
