### ISSUE TITLE
Third party LICENSE collection error when build wheel package 

### ISSUE THREAD

**Issue by xiaoran007** [pytorch/pytorch#126769]
### 🐛 Describe the bug

When build wheel package use

```shell
python setup.py bdist_wheel
```

The third party LICENSE collection may not work, for example the LICENSE file in path

```shell
opentelemetry-cpp/tools/vcpkg/ports/sigslot
```

can not be identified by the identify_license() function in third_party/build_bundled.py.

```shell
License
The sigslot library has been placed in the public domain. This means that you are free to use it however you like.

The author takes no responsibility or liability of any kind for any use that you may make of this library.

If you screw up, it's your fault.

If the library screws up, you got it for free, so you should have tested it better - it's still your responsibility.
```

The contains in this LICENSE file can not be identified by any key words defined in identify_license() function.

### Versions

tag: v2.1.0
os: ubuntu 20.04

cc @malfet @seemethere

**Comment by malfet** [comment]
Tentatively assigning to @c-p-i-o , who added the dependency in https://github.com/pytorch/pytorch/pull/122999

@ezyang just curios, is it used for anything yet? If not, then perhaps revert?

P.S. I wonder how it works with the nightly builds though?

**Comment by xiaoran007** [comment]
I found this issue when building directly whl on my ubuntu machine (without using docker), or maybe I need to use docker (follow the  ci script) to build it?
And if I set "Unknown license" as return value rather than value error, it works.
```python
        if 'ApacheLicense' in txt:
            # Hmm, do we need to check the text?
            return 'Apache-2.0'
        .
        .
        .
        elif all([squeeze(m) in txt.lower() for m in bsd3_src_txt]):
            return 'BSD-Source-Code'
        elif any([squeeze(m) in txt.lower() for m in mit_txt]):
            return 'MIT'
        else:
            # A license may not be on this list, but is still a valid license.
            raise ValueError('unknown license')
```

**Comment by c-p-i-o** [comment]
We did attempt to fix this in `build_bundled.py` script (https://github.com/pytorch/pytorch/blob/main/third_party/build_bundled.py#L117)
Is this fix not working?

**Comment by c-p-i-o** [comment]
> Tentatively assigning to @c-p-i-o , who added the dependency in #122999
> 
> @ezyang just curios, is it used for anything yet? If not, then perhaps revert?

We are waiting for some higher level abstractions for metrics to land. Once landed, for the OSS community, we plan on implementing those higher level abstractions via OTEL. 


> P.S. I wonder how it works with the nightly builds though?

Works on nightly because of (https://github.com/pytorch/pytorch/blob/main/third_party/build_bundled.py#L117)

**Comment by c-p-i-o** [comment]
@xiaoran007 FWIW, the issue didn't repro for me on `main`.

```
python setup.py bdist_wheel
...
adding license file 'LICENSE'
adding license file 'NOTICE'
...
adding 'torch-2.4.0a0+gitc5d83bc.dist-info/LICENSE'
adding 'torch-2.4.0a0+gitc5d83bc.dist-info/METADATA'
adding 'torch-2.4.0a0+gitc5d83bc.dist-info/NOTICE'
adding 'torch-2.4.0a0+gitc5d83bc.dist-info/WHEEL'
adding 'torch-2.4.0a0+gitc5d83bc.dist-info/entry_points.txt'

```

**Comment by xiaoran007** [comment]
Yes, when I checkout to tag v2.1.0, the files are untracked:
```shell
HEAD detached at v2.1.0
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        third_party/cpp-httplib/
        third_party/opentelemetry-cpp/
```
And I tried removing them and rebuilding the whl package now. It may takes a bit of time.

**Comment by xiaoran007** [comment]
> And I tried removing them and rebuilding the whl package now. It may takes a bit of time.

It works, thank you very much!

**Comment by c-p-i-o** [comment]
Thanks @xiaoran007!
I'm closing this issue for now - but re-open it if you run into any further issues.

**Comment by abalib** [comment]
> Yes, when I checkout to tag v2.1.0, the files are untracked:
> 
> ```shell
> HEAD detached at v2.1.0
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
>         third_party/cpp-httplib/
>         third_party/opentelemetry-cpp/
> ```
> 
> And I tried removing them and rebuilding the whl package now. It may takes a bit of time.

`rm -rf third_party/opentelemetry-cpp` after checking out the older tag builds.

**Comment by atalman** [comment]
Validated with 2.4:
```
024-07-09T16:55:55.7784566Z Copying torch.egg-info to build/bdist.linux-x86_64/wheel/torch-2.4.0+cu118-py3.9.egg-info
2024-07-09T16:55:55.7816182Z running install_scripts
2024-07-09T16:55:55.8448235Z adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
2024-07-09T16:55:55.8448910Z adding license file "NOTICE" (matched pattern "NOTICE*")
2024-07-09T16:55:55.8480003Z creating build/bdist.linux-x86_64/wheel/torch-2.4.0+cu118.dist-info/WHEEL
2024-07-09T16:55:55.8481246Z creating '/tmp/wheelhouse118/torch-2.4.0+cu118-cp39-cp39-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
2024-07-09T16:55:55.8652133Z adding 'functorch/_C.cpython-39-x86_64-linux-gnu.so'
2024-07-09T16:55:55.8657626Z adding 'functorch/__init__.py'
2024-07-09T16:55:55.8659457Z adding 'functorch/_src/__init__.py'
2024-07-09T16:55:55.8661390Z adding 'functorch/_src/aot_autograd/__init__.py'
2024-07-09T16:55:55.8662921Z adding 'functorch/_src/eager_transforms/__init__.py'
2024-07-09T16:55:55.8664457Z adding 'functorch/_src/make_functional/__init__.py
```
