### ISSUE TITLE
[RFC] Enable PyTorch XPU on Native Windows on Intel GPUs

### ISSUE THREAD

**Issue by min-jean-cho** [pytorch/pytorch#126719]
### 🚀 The feature, motivation and pitch

This RFC proposes to enable PyTorch XPU on Native Windows on Intel GPUs, following [[RFC] Intel GPU Upstreaming #114723](https://github.com/pytorch/pytorch/issues/114723) and [[RFC] Building system for SYCL and limited number of SYCL kernels for ATen fallbacks of TorchInductor #114835](https://github.com/pytorch/pytorch/issues/114835) which integrated building system of SYCL kernels for ATen XPU ops on Intel GPUs for Linux with a focus on torch.compile mode. This RFC outlines enabling PyTorch XPU on Intel GPUs for Native Windows. In this RFC, Windows refers specifically to Native Windows. 

<img width="400" alt="PyTorch_XPU_Windows" src="https://github.com/pytorch/pytorch/assets/93151422/ff6f49f4-96f1-4016-bc91-4a468081a9eb">

**1. [Stage 0] Required Windows specific changes in PyTorch**
PyTorch XPU on Windows on Intel GPU will be enabled progressively in stages. Stage 0 will focus on the PyTorch XPU source build on Windows. The first step requires building SYCL kernels for ATen XPU ops on Windows. Currently, `USE_XPU` is hardcoded to support Linux only. SYCL and SYCL runtime abstracts the underlying backend, thus the building system of SYCL kernels on Windows is the same as on Linux, following [[RFC] Building system for SYCL and limited number of SYCL kernels for ATen fallbacks of TorchInductor #114835](https://github.com/pytorch/pytorch/issues/114835). The only major difference is the compatible host compiler – MSVC on Windows vs. GCC on Linux. Note that the host compilation with MSVC aligns with the existing PyTorch Windows build. And the same SYCL implementations for ATen XPU ops is used on Windows and Linux. Thus, the required changes to build PyTorch XPU on Windows is minimal.

**1.1 Windows specific build changes in PyTorch:**
- Host compiler: **MSVC on Windows** vs. GCC on Linux
Handle appropriate MVSC vs. GCC compiler flags.
Note that the host compilation with MSVC aligns with the existing PyTorch Windows build. 
- SYCL compiler driver: **icx on Windows** vs. icpx on Linux
oneDNN GPU library is built using icx/icpx SYCL compiler driver for SYCL runtime.
Reference: https://oneapi-src.github.io/oneDNN/dev_guide_build.html#id1

Validation of PyTorch XPU on Windows on Intel GPU will be enabled progressively in stages. In Stage 0, a subset of XPU UTs will be internally validated on Intel Client GPU with Intel Core Ultra processors (Code Name: Meteor Lake) on Windows. In Stage 1, CI/CD will be added for Intel Client GPU with Intel Core Ultra processors (Code Name: Meteor Lake) on Windows with XPU UT scope as applicable to Windows on Intel Client GPU.

**1.2 Internal validation on Windows:**
- Hardware: Intel Client GPU with Intel Core Ultra processors (Code Name: Meteor Lake)
- OS: Windows 11
- XPU UT scope: pytorch/third-party/torch-xpu-ops/examples/*

**2. Motivation**
In the merge of AI on your PC (AI PC), Windows becomes an integral part for PyTorch on Intel GPUs, especially on Intel Client GPUs. Laptops with Intel Core Ultra processors (Code Name: Meteor Lake) combines CPU, GPU, and NPU to accelerate on AI PC. AI PC has a significant implication. For example, consider running LLMs entirely locally on your PC. This implies full privacy bound to your local PC at all levels of the AI stack from the bottom at GPU driver to the top at LLMs inference. Windows is an integral part of AI PCs which are natively Windows-based with built-in Intel Client GPU.

**3. Target**
- Goal: PyTorch XPU on Native Windows on Intel GPUs 
While enabling PyTorch XPU on Windows is generic to all Intel GPUs, from the AI PC use case perspective, Intel Client GPU will be the primary targeted hardware on Windows. 
- Eager mode and torch.compile mode
In Stage 0, PyTorch XPU on Windows will target limited eager mode only as Triton is not supported on Windows yet. Eventually, both eager mode and torch.compile mode will be fully supported. 
- CI/CD
In Stage 0, a subset of XPU UTs will be internally validated on Intel Client GPU with Intel Core Ultra processors (Code Name: Meteor Lake) on Windows. In Stage 1, CI/CD will be added for Intel Client GPU with Intel Core Ultra processors (Code Name: Meteor Lake) on Windows with XPU UT scope as applicable to Windows on Intel Client GPU.

**4. Requirements**
4.1. Hardware: Intel GPU
4.2. Software:
- OS: PyTorch XPU will support the same Windows distributions as PyTorch
Stage 0 will target the latest and most popular usage, Windows 11. 
- intel-gpu-pytorch-dev (SYCL compiler, oneMKL)
intel-gpu-pytorch-dev is a bundle of PyTorch dependencies to enable Intel GPUs.
- Visual Studio Build Tools 2022 (MSVC compiler)
Target the latest version of MSVC 2022.

**5. Build**
Enable heterogeneous compilation of SYCL program with separate compilation process using host and device compilers. Host compilation with host compiler. Device compilation with device compiler.  
Reference: https://www.intel.com/content/www/us/en/docs/oneapi-fpga-add-on/developer-guide/2024-1/separating-device-and-host-code-compilation.html

- Host compiler: **MSVC (Windows)** vs. GCC (Linux)
- Device compiler: **SYCL Compiler (Windows & Linux)**

Note that the host compilation with MSVC aligns with the existing PyTorch Windows build. 

Integrated by [[RFC] Building system for SYCL and limited number of SYCL kernels for ATen fallbacks of TorchInductor #114835](https://github.com/pytorch/pytorch/issues/114835), the build flow of SYCL kernels for ATen XPU ops is the same on Windows and Linux:

<img width="350" alt="PyTorch_XPU_Build_Flow" src="https://github.com/pytorch/pytorch/assets/93151422/867b818b-37d5-4e9e-8b79-80592a6ad071">

1. Heterogenous source compilation. Host compilation with host compiler. Device compilation with SYCL Compiler. Creates object file that contains host and device code.
`icx -fsycl -fsycl-targets= spir64,spir64_gen -fsycl-host-compiler=cl kernel.cpp -o kernel.obj`
2. Device link. Fully links device code. Creates the final device object for GPU that can be linked with linker of MSVC toolchain or GNU toolchain.
`icx -fsycl -fsycl-targets= spir64,spir64_gen -fsycl-link -Xsycl-target-backend "-device ats-m150" kernel.obj -o device.obj`
3. Host-only source compilation with host compiler. Creates host object.
`cl /c host.cpp /Fo:host.obj`
4. Final link. Link objects with linker of MSVC toolchain or GNU toolchain. 
`link.exe /DLL host.obj kernel.obj device.obj /OUT:libxxx.dll`

**6. Windows vs. Linux** 
Here, we share some background on difference between Windows vs. Linux on Intel GPU. SYCL and SYCL runtime abstracts the underlying backend. Thus, at the PyTorch stack level, above SYCL runtime, the difference between Windows vs. Linux doesn’t show up besides the obvious difference in the compatible host compiler (MSVC on Windows vs. GCC on Linux). And the same SYCL implementations for ATen XPU ops is used on Windows and Linux. However, below SYCL runtime, the implementations of Intel Graphics Driver components (User Mode Driver (UMD), Kernel Mode Driver (KMD)) on Windows and Linux are completely different, driven by each OS kernel. SYCL and SYCL runtime allows the backend to be abstracted, thus PyTorch XPU is OS-agnostic at the PyTorch stack level, above SYCL runtime.

**7. Task**
Stage 0
- Enable PyTorch XPU source build on Windows on Intel GPU for limited eager mode only. https://github.com/pytorch/pytorch/pull/126725
- A subset of XPU UTs internally validated on Intel Client GPU with Intel Core Ultra processors (Code Name: Meteor Lake) on Windows. 

Stage 1
- CI/CD for Intel Client GPU with Intel Core Ultra processors (Code Name: Meteor Lake) on Windows with XPU UT scope as applicable to Windows on Intel Client GPU.

Stage 2
- Enable missing ATen XPU ops to fully support eager mode. (Currently, missing ATen XPU ops fallback to ATen CPU ops. CPU fallback is costly on client CPU, and host <-> device data movement is costly in general).  
- Enable torch.compile on Windows for Intel GPU. 
- Enable low-bit precision (e.g., INT4, INT8) quantization to unblock memory limitation of Intel Client GPUs to support LLMs (e.g., Intel ARC A770 GPU has 16GB GPU memory which is not enough to run Llama3 8B half-precision (e.g., FP16) inference).

We will refine and expand tasks progressively. Note that some tasks under Stage 2 are not Windows specific. But from the AI PC use case perspective, they have high impact on Windows on Intel Client GPU.  

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by Vipitis** [comment]
You specifically mention

> Hardware: Intel Client GPU with Intel Core Ultra processors (Code Name: Meteor Lake)

Does this mean just the tile GPU for the MTL SoC ist he initial focus? 

At what stage will you include the "ats-150m" target? Since a lot of Windows users will be on Alchemist dGPU.

**Comment by pengzhao-intel** [comment]
> You specifically mention
> 
> > Hardware: Intel Client GPU with Intel Core Ultra processors (Code Name: Meteor Lake)
> 
> Does this mean just the tile GPU for the MTL SoC is the initial focus?
> 
> At what stage will you include the "ats-150m" target? Since a lot of Windows users will be on Alchemist dGPU.

Thanks for comments. Meter Lake is just a testing HW. After native windows support is enabled, it works for Alchemist dGPU as well.

**Comment by EikanWang** [comment]
@min-jean-cho , the RFC has been concluded. Right? If so, pls. help close this RFC.
