### ISSUE TITLE
using pykan i met this error.

### ISSUE THREAD

**Issue by danjdowling** [pytorch/pytorch#126782]
### 🐛 Describe the bug

RuntimeError: false INTERNAL ASSERT FAILED at "C:\b\abs_6fueooay2f\croot\pytorch-select_1707342446212\work\aten\src\ATen\native\BatchLinearAlgebra.cpp":1540, please report a bug to PyTorch. torch.linalg.lstsq: (Batch element 0): Argument 6 has illegal value. Most certainly there is a bug in the implementation calling the backend library..

### Versions

RuntimeError: false INTERNAL ASSERT FAILED at "C:\b\abs_6fueooay2f\croot\pytorch-select_1707342446212\work\aten\src\ATen\native\BatchLinearAlgebra.cpp":1540, please report a bug to PyTorch. torch.linalg.lstsq: (Batch element 0): Argument 6 has illegal value. Most certainly there is a bug in the implementation calling the backend library..

i get this error running this code 
model.train(dataset, opt = "LBFGS", steps = 50);

i have followed this process with my own data. And at the last line, i meet the PyTorch error outlined
https://github.com/KindXiaoming/pykan/blob/master/hellokan.ipynb

Thanks

**Comment by janeyx99** [comment]
This is likely a pykan issue; you'd get better help by opening an issue there!

Please reopen if this is truly a pytorch issue.
