### ISSUE TITLE
When testing the scalar version, test_torchinductor.py will fail

### ISSUE THREAD

**Issue by CaoE** [pytorch/pytorch#126763]
### 🐛 Describe the bug

When testing the scalar version, test_eager_aoti_cache_hit, test_eager_aoti_with_scalar, and test_torch_compile_override_registration will fail on CPU: 

- test_eager_aoti_cache_hit :

RuntimeError: aot_compile_function.ptr() != nullptr && aot_compile_function.ptr() != Py_None INTERNAL ASSERT FAILED at "torch/csrc/inductor/aoti_eager/kernel_holder.cpp":492, please report a bug to PyTorch. Failed to import - torch._inductor.utils.aoti_compile_with_persistent_cache.
https://github.com/pytorch/pytorch/actions/runs/9155726251/job/25169583661.

- test_eager_aoti_with_scalar:

RuntimeError: Error in dlopen: /tmp/tmp_g2gv5bn/aoti_eager/aten/cpu/lib/c45k6o4iha4bbbscgaq7t2fd6caoqtits2gxv7jnufcgenkvpvl6/c7yfkon2pnnmjco3zdy2o4fxugxmbhp5cek6awoqjvw4evd2yfvc.so: undefined symbol: aoti_torch_grad_mode_set_enabled

- test_torch_compile_override_registration:

RuntimeError: Error in dlopen: /tmp/tmpeknyiu96/aoti_eager/aten/cpu/lib/cfxk7bi2gpbwr67c6rau3ov3bo7itog5j55l25ook4ijmhck2kci/cawbojjuna6scr3mmx4rv64o4o2cmw5zp4n5itwtvwhv2truvm5j.so: undefined symbol: aoti_torch_grad_mode_set_enabled

### Minified repro

Run `python test/inductor/test_torchinductor.py -k CpuTests.test_eager_aoti_cache_hit_cpu`,  `python test/inductor/test_torchinductor.py -k CpuTests.test_torch_compile_override_registration_cpu`, or 
`python test/inductor/test_torchinductor.py -k CpuTests.test_eager_aoti_with_scalar_cpu` with torch._inductor.config.cpp.simdlen=0.

### Versions

pytorch nighly 0516.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @desertfire @chenyang78

**Comment by EikanWang** [comment]
I'm working on the issue.

**Comment by EikanWang** [comment]
@desertfire , The root cause is the produced library does not link any torch library because the vec ISA is invalid and then it cannot run into another path without linking libtorch and libtorch_cpu.

https://github.com/pytorch/pytorch/blob/main/torch/_inductor/codecache.py#L1637-L1642
