### ISSUE TITLE
Long queue times due to changes in scale up infra

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#126895]
<img width="846" alt="image" src="https://github.com/pytorch/pytorch/assets/44682903/b6c2e4af-443c-4958-a2aa-5a172e1752ab">

<img width="855" alt="image" src="https://github.com/pytorch/pytorch/assets/44682903/f2a9e3a2-dfe5-4508-876f-db69035d3886">

## Current Status
ongoing
*Status could be: preemptive, ongoing, mitigated, closed. Also tell people if they need to take action to fix it (i.e. rebase)*.

## Error looks like
Jobs taking long time to start due to waiting for a runner
*Provide some way users can tell that this SEV is causing their issue.*

## Incident timeline (all times pacific)
7:20 Terraform Release was applied https://github.com/pytorch-labs/pytorch-gha-infra/actions/runs/9192813922/job/25283153324 with Node 20 upgrade
8:00am queue times start increasing
10:15am Nikita notices 50 min wait time for linux.2xlarge
11:10am Roll back node from 20 to 16 https://github.com/pytorch-labs/pytorch-gha-infra/pull/395 https://github.com/pytorch/test-infra/commit/c7790ef323c8f22e672cf92efcd6757c178957c4
@jeanschmidt locally rolled back to node 14?

*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by jeanschmidt** [comment]
Root issue seems mitigated by now, waiting for the systems to catch up, monitoring in the meantime to make sure everything recovers.

**Comment by clee2000** [comment]
Queue times look pretty normal now
<img width="855" alt="image" src="https://github.com/pytorch/pytorch/assets/44682903/76f7802c-119e-49e0-acfa-24022ef88027">
Will close in an hour unless anyone says otherwise
