### ISSUE TITLE
[BE] wrap deprecated function/class with `typing_extensions.deprecated` for better IDE integration

### ISSUE THREAD

**Issue by XuehaiPan** [pytorch/pytorch#126888]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

Provide a short description.

Currently, we use `warnings.warn("deprecation message", DeprecationWarning)` to warn users of functionality deprecation and pending removals.

Python 3.13 adds a new API [`warnings.deprecated`](https://docs.python.org/zh-cn/3.13/library/warnings.html#warnings.deprecated) for deprecation indication. This feature has better static type checker support. When a deprecated object is imported or called, the code will ~~be struck out~~ in the IDE.

[`warnings.deprecated`](https://docs.python.org/zh-cn/3.13/library/warnings.html#warnings.deprecated) is backported in `typing-extensions` 4.5.0 ([typing_extensions.deprecated](https://typing-extensions.readthedocs.io/en/latest/#typing_extensions.deprecated)), which is already one of our dependency.

https://github.com/pytorch/pytorch/blob/3e826c477aba0a0cf9bea4131cee57aac21c1c14/requirements.txt#L11

Screenshot to illustrate the IDE integration with ~~strick out annotation~~.

<img width="1026" alt="image" src="https://github.com/pytorch/pytorch/assets/16078332/9445111f-670d-4339-96fc-3985ce3889bf">

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

```python
from typing_extensions import deprecated


@deprecated(
    "Function `deprecated_func` is deprecated and will be removed in a future release. Use `new_func` instead."
)
def deprecated_func():
    return "deprecated_func"


def new_func():
    return "new_func"


@deprecated(
    "Class `DeprecatedClass` is deprecated and will be removed in a future release. Use `NewClass` instead."
)
class DeprecatedClass:
    pass


class InheritedDeprecatedClass(DeprecatedClass):
    pass


class NewClass:
    pass


class Foo:
    @deprecated("Method `Foo.bar` is deprecated and will be removed in a future release.")
    def bar(self):
        print("Hello, world!")


if __name__ == "__main__":
    print(deprecated_func())
    print(new_func())
    instance = DeprecatedClass()
```

cc @ezyang @malfet @xuzhao9 @gramster

**Comment by ezyang** [comment]
ok sgtm
