### ISSUE TITLE
[JIT] Moving Module to CUDA in C++

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#12686]
Is it supported to move `torch::jit::script::Module` in CUDA?
If not can you document in a section of Readme/Docs?

See also  
https://discuss.pytorch.org/t/moving-model-to-cuda-in-c/26786/

**Comment by bhack** [comment]
We can close this when https://github.com/pytorch/pytorch/pull/12710 will be merged. /cc @soumith @goldsborough Probably you could add some more info to https://github.com/pytorch/tutorials/blob/master/advanced_source/cpp_export.rst

**Comment by goldsborough** [comment]
Hi! We noticed that there was no easy way to do this at the moment. When https://github.com/pytorch/pytorch/pull/12710 lands I will update the docs to mention this.

**Comment by bhack** [comment]
It will work also with cudnn? I was tracing a run and I don't see cudnn calls.

**Comment by soumith** [comment]
@bhack yes. The CuDNN calls are inside particular operators, and not leaf nodes in our IR

**Comment by bhack** [comment]
@soumith Thanks Probably it is more related to the debug symbols cause Nvidia profilers still gives false positive warnings  related to the absence of cudnn calls. It could be useful if we could enable in the nightly. See https://github.com/pytorch/pytorch/issues/12448#issuecomment-431458808

**Comment by bhack** [comment]
I close this. Tutorial topics are in https://github.com/pytorch/tutorials/issues/352
