### ISSUE TITLE
Tensor computation error on MPS backend

### ISSUE THREAD

**Issue by Caz-T** [pytorch/pytorch#126919]
### 🐛 Describe the bug

When using fancy indices to modify elements in a tensor **on a MPS backend**, some elements are incorrectly updated:
```
x = torch.tensor([[1, 2, 2],
                  [1, 2, 3]])
x_mps = x.clone().to('mps')
x_mps[x_mps == 2] = -1
print(x_mps)  
```

This would produce 
```
tensor([[-1,  2, -1],
        [ 1, -1,  3]], device='mps:0')
```
where `x[0, 1]` should be updated to $-1$, but in the given output, it remains $2$.

When on a CPU or CUDA device, the behaviour is as expected:
```
x = torch.tensor([[1, 2, 2],
                  [1, 2, 3]])
x_cpu = x.clone().to('cpu')
x_cuda = x.clone().to('cuda')
x_cpu[x_cpu == 2] = -1
x_cuda[x_cuda == 2] = -1
print(x_cpu)  
print(x_cuda)
```

This would produce
```
tensor([[ 1, -1, -1],
        [ 1, -1,  3]])
tensor([[ 1, -1, -1],
        [ 1, -1,  3]], device='cuda:0')
```
just as expected. 

All specific values above don't seem to make a difference. But the following code runs correctly:

```
x = torch.tensor([[2, 2],
                  [2, 3]])
x_mps = x.clone().to('mps')
x_mps[x_mps == 2] = -1
print(x_mps)  
```
This produces 
```
tensor([[-1, -1],
        [-1,  3]], device='mps:0')
```
as expected.

### Versions

PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.3
Libc version: N/A

Python version: 3.9.18 (main, Sep 11 2023, 08:38:23)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] torch==2.2.2
[pip3] torchdata==0.7.1
[pip3] torchtext==0.17.2
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.2                    pypi_0    pypi
[conda] torchdata                 0.7.1                    pypi_0    pypi
[conda] torchtext                 0.17.2                   pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by shink** [comment]
Thanks for reporting. I noticed you are using torch2.2.2, could you please try again on the nightly version? I've tried this case and the result is as expected.

```bash
pip install --pre --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly
```

**Comment by Caz-T** [comment]
Having no luck with that. I tried again on torch 2.2.0.dev20231010, and the first snippet now produces
```
tensor([[-1,  2, -1],
        [ 1, -1,  3]], device='mps:0')
```
which is still incorrect.

**Comment by Caz-T** [comment]
It seems like the bug happens when the index part is on MPS devices. 

```
import torch
print(torch.__version__)

x = torch.tensor([[1, 2, 2],
                  [1, 2, 3]])
x_cpu = x.clone().to('cpu')
x_mps = x.clone().to('mps')
x_cpu[x_mps == 2] = -1
print(x_cpu)
x_mps[x_mps == 2] = -1
print(x_mps)
```

This now produces 
```
2.2.0.dev20231010
tensor([[-1,  2, -1],
        [ 1, -1,  3]])
tensor([[-1,  2, -1],
        [ 1, -1,  3]], device='mps:0')
```
Both tensors are incorrect.

**Comment by qqaatw** [comment]
Suspect it has something to do with synchronization, can you add this line before `print`?

```python
torch.mps.synchronize()
```

**Comment by Caz-T** [comment]
> Suspect it has something to do with synchronization, can you add this line before `print`?
> 
> ```python
> torch.mps.synchronize()
> ```

I tried adding these lines but still, the output is not consistent. 

```
import torch
print(torch.__version__)

x = torch.tensor([[1, 2, 2],
                  [1, 2, 3]])
x_cpu = x.clone().to('cpu')
x_mps = x.clone().to('mps')

x_cpu[x_cpu == 2] = -1
torch.mps.synchronize()
print(x_cpu)

x_cpu = x.clone().to('cpu')
x_cpu[x_mps == 2] = -1
torch.mps.synchronize()
print(x_cpu)

x_cpu = x.clone().to('cpu')
x_mps[x_cpu == 2] = -1
torch.mps.synchronize()
print(x_mps)

x_mps = x.clone().to('mps')
x_mps[x_mps == 2] = -1
torch.mps.synchronize()
print(x_mps)
```

This produces

```
2.2.2
tensor([[ 1, -1, -1],
        [ 1, -1,  3]])
tensor([[-1,  2, -1],
        [ 1, -1,  3]])
tensor([[ 1, -1, -1],
        [ 1, -1,  3]], device='mps:0')
tensor([[-1,  2, -1],
        [ 1, -1,  3]], device='mps:0')
```

**Comment by qqaatw** [comment]
I see. I looks like a regression since I couldn't reproduce it on macOS 12.

**Comment by kulinseth** [comment]
@Caz-T , On torch nightly i am unable to reproduce this issue:


```
MPS:  tensor([[ 1, -1, -1],
        [ 1, -1,  3]], device='mps:0')
CPU:  tensor([[ 1, -1, -1],
        [ 1, -1,  3]])
```

**Comment by kulinseth** [comment]
Tried on Torch 2.3 version and I couldn't repro it either:

```
MPS:  tensor([[ 1, -1, -1],
        [ 1, -1,  3]], device='mps:0')
CPU:  tensor([[ 1, -1, -1],
        [ 1, -1,  3]])
```

Can you try and see if it works at your end ? Please re-open if its still an issue.
