### ISSUE TITLE
UNSTABLE inductor / linux-jammy-cpu-py3.8-gcc11-inductor / test (inductor_torchbench_cpu_smoketest_perf)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#126993]
Flakily resulting in performance regressions on various models

https://hud.pytorch.org/hud/pytorch/pytorch/b36e390b6c1f4a1a2239ad1e857a2ffd12f49e43/1?per_page=100

I've seen:
hf_T5_generate
https://github.com/pytorch/pytorch/actions/runs/9212435048/job/25344669736
https://github.com/pytorch/pytorch/actions/runs/9212478228/job/25344846892
https://github.com/pytorch/pytorch/actions/runs/9212375708/job/25344507271
hf_GPT2
https://github.com/pytorch/pytorch/actions/runs/9205209228/job/25321260061
timm_efficientnet
https://github.com/pytorch/pytorch/actions/runs/9204141570/job/25317679586

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by chuanqi129** [comment]
@zxd1997066 could you please help to double check this issue?

**Comment by kit1980** [comment]
Reopening as there is a huge queue for linux.24xl.spr-metal

**Comment by chuanqi129** [comment]
Hi @kit1980 , there is PR to enlarge the max runner number https://github.com/pytorch/test-infra/pull/5372. Does it help to reduce the queue for linux.24xl.spr-metal?

**Comment by chuanqi129** [comment]
And I can't understand that, we just have one inductor test use `linux.24xl.spr-metal` for now in https://github.com/pytorch/pytorch/blob/b019f38fdd97957f0e5923961ea7cf5b63c0761b/.github/workflows/inductor.yml#L185. Why we have huge queue for it? @kit1980 could you please help to double check it?

**Comment by kit1980** [comment]
>  Why we have huge queue for it? @kit1980 could you please help to double check it?

The queue because there were zero linux.24xl.spr-metal machines.

**Comment by chuanqi129** [comment]
Thanks @kit1980 for the update. Do we know why there is no linux.24xl.spr-metal runner? cc: @jeanschmidt

**Comment by huydhn** [comment]
This doesn't look unstable anymore, so I'm close the issue.
