### ISSUE TITLE
Backward hook for conv layers without bias

### ISSUE THREAD

**Issue by longcw** [pytorch/pytorch#1269]
I write a backward hook for a convolutional layer without bias. `grad_input` consists of three gradients and the latest one for bias is `None` in the latest master branch. 
It will raise `TypeError: expected Variable, but hook returned 'NoneType'` if the function returns three variables but the latest is `None` just like `grad_input`, 
or raise `RuntimeError: backward hook 'backward_hook' has returned an incorrect number of gradients (got 2, but expected 3)` if the function omits the gradient of bias.

The latest release v0.1.11 only gives two grads in `grad_input` and works fine in this case. Is this a new bug of the master branch?

**Comment by rohitghosh** [comment]
Any update on this  @apaszke ? Couldn't think of any way to overcome this - even if I pass a Variable with zeros  (of same size as no of filters in conv layer) in place of grad_input[2] ( the gradient w.r.t bias) it results in segmentation fault.

**Comment by apaszke** [comment]
No updates yet, will fix soon

**Comment by rohitghosh** [comment]
Adam: Any chance you could work on this issue in the meantime? Any idea how long would it take - any help I can do?

**Comment by apaszke** [comment]
No I didn't have time to look into it. If you want to work on this, I think that [`torch/csrc/autograd/python_hook.cpp`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/python_hook.cpp#L149-L153) is the only file you need to modify.
