### ISSUE TITLE
(libtorch) segmentation fault on CentOS

### ISSUE THREAD

**Issue by Yuyiqi1992** [pytorch/pytorch#12705]
## 🐛 Bug

I followed the  instructions at https://pytorch.org/tutorials/advanced/cpp_export.html to use libtorch on CentOS, and an exception (segmentation fault) is thrown out when I'm trying to run, but there is no problem on Ubuntu. Then I used valgrind to check the memory on CentOS, the results as follows:

`==434== Command: ./example-app ../model.pt`
`==434== ok`
`==434== Invalid read of size 8`
`==434==    at 0x434A6A: std::_Hashtable<std::string, std::pair<std::string const, unsigned long>, std::allocator<std::pair<std::string const, unsigned long> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node(unsigned long, std::string const&, unsigned long) const (in /icooper/dev/playphone_c/build/example-app)`

`==434==    by 0x4339D9: std::_Hashtable<std::string, std::pair<std::string const, unsigned long>, std::allocator<std::pair<std::string const, unsigned long> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_node(unsigned long, std::string const&, unsigned long) const (in /icooper/dev/playphone_c/build/example-app)`

`==434==    by 0x433A4F: std::_Hashtable<std::string, std::pair<std::string const, unsigned long>, std::allocator<std::pair<std::string const, unsigned long> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find(std::string const&) const (in /icooper/dev/playphone_c/build/example-app)`

`==434==    by 0x4320D2: std::unordered_map<std::string, unsigned long, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, unsigned long> > >::find(std::string const&) const (in /icooper/dev/playphone_c/build/example-app)`

`==434==    by 0x42FBA8: torch::detail::OrderedDict<std::string, std::unique_ptr<torch::jit::script::Method, std::default_delete<torch::jit::script::Method> > >::find(std::string const&) const (in /icooper/dev/playphone_c/build/example-app)`

`==434==    by 0x42D575: torch::detail::OrderedDict<std::string, std::unique_ptr<torch::jit::script::Method, std::default_delete<torch::jit::script::Method> > >::get(std::string const&) const (in /icooper/dev/playphone_c/build/example-app)`

`==434==    by 0x42B117: torch::jit::script::Module::get_method(std::string const&) const (in /icooper/dev/playphone_c/build/example-app)`

`==434==    by 0x42B035: torch::jit::script::Module::forward(std::vector<torch::jit::IValue, std::allocator<torch::jit::IValue> >) (in /icooper/dev/playphone_c/build/example-app)`

`==434==    by 0x426BBC: main (in /icooper/dev/playphone_c/build/example-app)`
`==434==  Address 0x56feade8 is not stack'd, malloc'd or (recently) free'd`
`==434== Process terminating with default action of signal 11 (SIGSEGV): dumping core`
`==434==  Access not within mapped region at address 0x56FEADE8`

## To Reproduce

1. Follow the instructions at https://pytorch.org/tutorials/advanced/cpp_export.html
2. Run the compiled program on the traced torchvision resnet18

## Expected behavior
The program doesn't throw any exceptions

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.0.dev20181007
 - OS (e.g., Linux): CentOS 7.5.1804
 - How you installed PyTorch (`conda`, `pip`, source): conda / downloaded and extracted libtorch zip
 - Python version: 3.6
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: cmake 3.11.1,  GNU 4.8.5,  glibc 2.20

**Comment by iwtw** [comment]
I can reproduce this issue on my machine too.
# Environment

- PyTorch , libtorch(cpu version) Version 1.0.0.dev20181017
- OS: Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)
- How you installed PyTorch (conda, pip, source): conda / downloaded and extracted libtorch zip
- Python version: 3.6
- CUDA/cuDNN version: None
- GPU models and configuration: None
- Any other relevant information: cmake 3.12.3 , GNU 4.8.5

**Comment by Yuyiqi1992** [comment]
I have solved this problem. Please upgrade GNU 4.8.5 to 5.4.0, it's working on my machine. Thank you @iwtw , you reminded me to do this. Because I have tested on Ubuntu 16.04 before, there is no problem and the GNU version is 5.4.0 .

**Comment by kev123456** [comment]
There are still segmentation fault on CentOS after I upgrade GNU 4.8.5 to 5.4.0

**Comment by Yuyiqi1992** [comment]
@kev123456 , please check up the GNU version when you cmake, maybe it still used GNU 4.8.5.
