### ISSUE TITLE
Fail to mix nn.BatchNorm with user defined BatchNorm

### ISSUE THREAD

**Issue by XingangPan** [pytorch/pytorch#12701]
## 🐛Fail to mix nn.BatchNorm with user defined BatchNorm

When using nn.BatchNorm2d and a user defined BatchNorm2d in a module, the following error occurs during backpropagation: 
"RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation"
This might be caused by the inplace update of "running_mean" and "running_var" in the user defined BatchNorm. However, these two Tensors has to be updated via inplace operation.
Strangely, the above error does not occur if there is no nn.BatchNorm2d or if nn.DataParallel is not used.

## To Reproduce

This is a simple code to reproduce the error:

```Shell
import torch
import torch.nn as nn

class BatchNorm2d(nn.Module):
    def __init__(self, num_features, eps=1e-5, momentum=0.9):
        super(BatchNorm2d, self).__init__()
        self.eps = eps
        self.momentum = momentum
        self.register_buffer('running_mean', torch.zeros(num_features, 1))
        self.register_buffer('running_var', torch.ones(num_features, 1))

    def forward(self, x):
        N, C, H, W = x.size()
        x = torch.transpose(x, 0, 1).contiguous()
        x = x.view(C, N * H * W)
        if self.training:
            mean_b = x.mean(1, keepdim=True)
            var_b = x.var(1, keepdim=True)
            self.running_mean.mul_(self.momentum)
            self.running_mean.add_((1 - self.momentum) * mean_b.detach())
            self.running_var.mul_(self.momentum)
            self.running_var.add_((1 - self.momentum) * var_b.detach())
        else:
            mean_b = self.running_mean
            var_b = self.running_var
        x_bn = (x - mean_b) / (var_b + self.eps).sqrt()
        out = x_bn.view(C, N, H, W)
        return torch.transpose(out, 0, 1).contiguous()

model = nn.Sequential(
    nn.BatchNorm2d(4),
    BatchNorm2d(4))
model = torch.nn.DataParallel(model).cuda()

input = torch.rand(16,4,4,4).cuda()
label = torch.rand(16,4,4,4).cuda()
output = model(input)
criterion = nn.L1Loss()
loss = criterion(output, label)
loss.backward()
```

## Expected behavior

Hope that this error could be fixed.

## Environment

PyTorch version: 0.4.0a0+1ab248d
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 384.98
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] torch (0.4.0a0+1ab248d)
[pip] torchvision (0.2.0)
[conda] pytorch                   0.4.0a0+1ab248d py36_cuda8.0.61_cudnn7.0.5_0    ostrokach-forge
[conda] torchvision               0.2.0            py36h17b6947_1    pytorch

**Comment by t-vi** [comment]
This runs fine for recent versions of PyTorch, so I it would help to update from `PyTorch version: 0.4.0a0+1ab248d`.

**Comment by XingangPan** [comment]
@t-vi Thanks. FYI, the problem also exists in PyTorch version: 0.4.1. I'll update my pytorch to a recent version.

**Comment by SsnL** [comment]
BTW, you are making running_mean and running_var require grad here by using `mean` and `var` (computed from input, and requires grad because input requires grad in this case). So I would suggest putting the running_* updates in a no_grad block.

**Comment by XingangPan** [comment]
@t-vi @SsnL I have updated pytorch to version 1.0.0a0+0521c47, and have put the running_* updates in a no_grad block as below:
```Shell
        with torch.no_grad():
            self.running_mean.mul_(self.momentum)
            self.running_mean.add_((1 - self.momentum) * mean_b)
            self.running_var.mul_(self.momentum)
            self.running_var.add_((1 - self.momentum) * var_b)
```
However, the error still exists:
```Shell
Traceback (most recent call last):
  File "bugExample2.py", line 43, in <module>
    loss.backward()
  File "/mnt/lustre/panxingang/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/lustre/panxingang/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```
My environment is:
```Shell
PyTorch version: 1.0.0a0+0521c47
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 384.98
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.4
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.0)
[pip] numpydoc (0.7.0)
[pip] torch (1.0.0a0+0521c47)
[conda] torch                     1.0.0a0+0521c47           <pip>
```

**Comment by t-vi** [comment]
I'd recommend to post a self-contained script that shows the errors on the forum. I literally pasted your script into my python3 and it worked. Maybe the inplace upgrade is elsewhere? On the forums there are quite a few people who will have experience debugging similar things.
