### ISSUE TITLE
Add Ability to Skip Hipification When Building CUDA Extension

### ISSUE THREAD

**Issue by FurtherAI** [pytorch/pytorch#127015]
### 🚀 The feature, motivation and pitch

The problem is simple, say I have a CUDA/HIP extension that I am trying to build for pytorch. Using a `CUDAExtension` will always hipify your code. This is extremely annoying in some cases since it replaces things like `std::max` with `::max` which then don't compile. There are other times you may want to hipify the code yourself and not have pytorch mess with it. But, there doesn't seem to be a way to get pytorch not to change things.

Proposal: add an argument to CUDAExtension that allows all or select files to skip the hipification process. 

cc @malfet @zou3519 @ptrblck @msaroufim @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
What is your environment like?  CUDAExtension will unconditionally import the hipify-related modules, but running hipify is protected by `IS_HIP_EXTENSION = True if ((ROCM_HOME is not None) and (torch.version.hip is not None)) else False`.

**Comment by FurtherAI** [comment]
I should make it more clear this is for when you're trying to build a HIP extension (it's just that you use the CUDAExtension class, or at least I couldn't find a HIPExtension class). So `IS_HIP_EXTENSION` should be true.

**Comment by jeffdaily** [comment]
Thanks for clarifying.  We want the user experience when building a HIP PyTorch extension to be as smooth as possible, minimizing the need for code changes.  That's why we don't require users to explicitly hipify their code, but instead do it automatically when using CUDAExtension and a HIP pytorch build is detected.

It seems in your case one or more of your source files will be used by both the host compiler (gcc?) and the device compiler (hip-clang or hipcc).  To get the source file to be compatible with hip-clang we remove the std:: prefix.  hip-clang does not claim to support every function in the C++ standard template library, and some of the support comes from using these functions from the global namespace instead of the std:: namespace.

Is there some way of refactoring your code such that there is a clear separation?

If your source file is a header file and you do not want it to be hipified automatically, try reducing the list of files you pass to CUDAExtension.  It should only hipify the files you explicitly specify.

**Comment by hongxiayang** [comment]
@FurtherAI Please let us know whether the suggestion by @jeffdaily works for you or not? 
If not, can you post your example code here so we can better support you?

**Comment by FurtherAI** [comment]
@jeffdaily I'm expecting all source files to be compiled with hipcc. I believe your suggestion doesn't work then, since if you reduce the files passed to the CUDA extension so that they are not hipified, they wouldn't be compiled and linked?

I see the importance of changing to the global namespace. In my case, I noticed `std::min` and `std::max` were functional with `hipcc` and wanted to keep them, since the global namespace versions function differently or otherwise weren't working.

Here's an example, though it might be clear already:
```c++
#pragma once
#include <hip/hip_runtime.h>

template <int val1, int val2>
struct dummy {
    static constexpr int val = std::min({8, val1, val2});
};
```
With the important part of `setup.py` as 
```python
ext_modules.append(
        CUDAExtension(
            name="pkg",
            sources=["csrc/file.cuh", "etc"],
            extra_compile_args={
                "cxx": ["-O3", "-std=c++17"],
                "nvcc":
                    [
                        "-O3",
                        "-std=c++17",
                        "other compiler args"
                    ],
            },
            include_dirs=[Path(this_dir) / "csrc"]
        )
    )
```

I am confident that `std::min()` can handle this when compiled by `hipcc` and I'd like to use the `CUDAExtension` so my file will be compiled and linked as part of the extension. The CUDAExtension will unfortunately HIPIFY my file to `::min()` which will no longer work. I'd like to be able to tell the extension to not HIPIFY at all or to skip this file, but to do the rest of the build process. 

I am sure there are other scenarios where you might want to skip the hipification process and it should be pretty simple to add.

**Comment by naromero77amd** [comment]
@FurtherAI A couple of ideas for your consideration:
1. If you want to globally modify the behavior of hipify wrt ``std::main, std::max, etc.`` in your local install, you can modify those mappings by modifying the cuda_to_hip_mappings: ``/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py``   Search for `MATH_TRANSPILATIONS`
2. If there are files that you want to skip hipification altogether, you can skip hipifying those files by including **only** the files you want hipified in the argument of `extra_files`:
https://github.com/pytorch/pytorch/blob/efec302dd0e2d767b53b25cc53278fab5ac4ba82/torch/utils/cpp_extension.py#L1132-L1141
3. If neither of these options align with your needs, we would be open to a PR contribution should you want to add this functionality. If this is something that you are interested in pursuing, I recommend starting with a draft PR with a description of your use cases and proposed changes before actually writing any code.
