### ISSUE TITLE
dynamo doesn't support `__torch_function__` on non-tensor classes

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#127174]
### 🐛 Describe the bug

Extending pytorch with tensor-like classes isn't supported by Dynamo. Additionally, the error message is not very informative for users who don't know much about dynamo.

(I guess this is known and on someone's roadmap, I'm opening an issue to keep track of this for tensordict integration)

To reproduce:
```python
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
import functools
from typing import Callable, Any

import torch

HANDLED_FUNCTIONS = {}

class MyClass:
    def __init__(self, foo):
        self.foo = foo

    @classmethod
    def __torch_function__(
        cls,
        func: Callable,
        types: tuple[type, ...],
        args: tuple[Any, ...] = (),
        kwargs: dict[str, Any] | None = None,
    ) -> Callable:

        if kwargs is None:
            kwargs = {}
        if func not in HANDLED_FUNCTIONS or not all(
            issubclass(t, (torch.Tensor, MyClass)) for t in types
        ):
            return NotImplemented
        return HANDLED_FUNCTIONS[func](*args, **kwargs)

    def __repr__(self):
        return "MyClass({})".format(self.foo)

def implements_for(torch_function: Callable) -> Callable[[Callable], Callable]:
    """Register a torch function override for TensorDict."""

    @functools.wraps(torch_function)
    def decorator(func: Callable) -> Callable:
        HANDLED_FUNCTIONS[torch_function] = func
        return func

    return decorator


@implements_for(torch.stack)
def _stack(input, dim=0, *, out=None):
    return MyClass(sum([x.foo for x in input]))

v0 = MyClass(1)
v1 = MyClass(1)
print(torch.stack([v0, v1]))

@torch.compile(fullgraph=True)
def func(v0, v1):
    return torch.stack([v0, v1])

print(func(v0, v1))
```
The last call fails with 
```
  File "/Users/vmoens/venv/rl/lib/python3.11/site-packages/torch/_dynamo/variables/base.py", line 253, in as_proxy
    raise NotImplementedError(str(self))
NotImplementedError: UserDefinedObjectVariable(MyClass)

[...]
  File "/Users/vmoens/venv/rl/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 215, in unimplemented
    raise Unsupported(msg) from from_exc
torch._dynamo.exc.Unsupported: call_function args: ListVariable(length=2) 

from user code:
   File "/Users/vmoens/Library/Application Support/JetBrains/PyCharm2023.3/scratches/compile_mini_errors.py", line 57, in func
    return torch.stack([v0, v1])

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

### Versions

nightly

cc @hameerabbasi @rgommers @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @zou3519

**Comment by ezyang** [comment]
cc @mlazos but doing a reasonably faithful torch function Dynamo integration still needs a *lot* of work

**Comment by mlazos** [comment]
@vmoens Your example should be supported with the existing infra - can you add your class to https://github.com/pytorch/pytorch/blob/9cc0d56fdc4be3873582aa23e49b051aa27a6d2d/torch/_dynamo/config.py#L132 and lmk if there are issues?

I can add a proper error message that suggests this.

**Comment by mlazos** [comment]
I published https://github.com/pytorch/pytorch/pull/127496, there will still be a graph break since we don't support generators today (cc @anijain2305) but if you add a list comprehension to the `all` call you can remove the graph break. I can look into supporting generators.

**Comment by vmoens** [comment]
> there will still be a graph break since we don't support generators today

That's ok, it's something I can work around ;) 
Thanks for the fix!
