### ISSUE TITLE
Segmentation fault when importing `sklearn.model_selection`

### ISSUE THREAD

**Issue by naji-s** [pytorch/pytorch#127192]
### 🐛 Describe the bug

The following will lead to a segmentation fault. Note that the import of sklearn.model_selection is crucial for the segmentation fault. This is potentially related to #121101
```python
import sklearn.model_selection

import torch
class MultiLayerPerceptron(torch.nn.Module):
    def __init__(self, dim):
        super(MultiLayerPerceptron, self).__init__()

        self.input_dim = dim

        self.l1 = torch.nn.Linear(dim, 300, bias=False)
        self.b1 = torch.nn.BatchNorm1d(300)

    def forward(self, x):
        x = x.view(-1, self.input_dim)
        h = self.l1(x)
        h = self.b1(h)
        return h
    
if __name__ == '__main__':
    model = MultiLayerPerceptron(5)
    
    import torch
    X = torch.randn([1,300, 5]).to('cpu')
    print(model(X)) 

```

### Versions

Collecting environment information...
PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.3.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.1
Libc version: N/A

Python version: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:25:12) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] gpytorch==1.11
[pip3] numpy==1.26.4
[pip3] torch==2.2.2
[pip3] torchinfo==1.8.0
[pip3] torchvision==0.17.2
[pip3] torchviz==0.0.2
[conda] gpytorch                  1.11               pyhd8ed1ab_0    conda-forge
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.2                    pypi_0    pypi
[conda] torchinfo                 1.8.0                    pypi_0    pypi
[conda] torchvision               0.17.2                   pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @seemethere @malfet @osalpekar @atalman @albanD

**Comment by malfet** [comment]
Can you please share a version of sklearn you are using(and whether it was installed from PyPI or Conda), as I can not repro the failure with sklearn 1.4.2 installed from PyPI
