### ISSUE TITLE
pytorch support cuda10.0 or not [Compilation passed for macOS10.13.6 + cuda10.0, link phase failed]

### ISSUE THREAD

**Issue by llv22** [pytorch/pytorch#12712]
## 🚀 Feature
If pytorch support cuda10.0 for GPU

## Motivation

As Nivida release cuda10.0, pytorch build meet with following error:

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Volumes/llv23/git_projects/machine_learning/pytorch/torch/lib/tmp_install/lib/libcaffe2_gpu.dylib (for architecture x86_64) option "-add_rpath /usr/local/cuda/lib" would duplicate path, file already has LC_RPATH for: /usr/local/cuda/lib

Can we enable pytorch with cuda10.0?

## Current Status (Or trial result)

I trigger building in macOS 10.13.6 with cuda10.0, and found the building is successfully finished. all relevant objects are generated. However, during the link phase, the duplicate objects lead to the final install/bdist_wheel failure.

Personally guessing, shouldn't be a very big deal to solve with. Maybe I'm wrong.

**Comment by heitorschueroff** [comment]
Closing as we support CUDA 10.0 now.
