### ISSUE TITLE
pyyaml dependency error on Mac with source installation

### ISSUE THREAD

**Issue by j-youssef** [pytorch/pytorch#127158]
### 🐛 Describe the bug

On Mac, with source installation, the develop setup step generates a pyyaml dependency error. Below is the command and error. As shown, the dependency is already satisfied.

`% python3 setup.py develop`       
Building wheel torch-2.4.0a0+gitcc9a341
-- Building version 2.4.0a0+gitcc9a341
Traceback (most recent call last):
  File "<...>setup.py", line 493, in check_pydep
    importlib.import_module(importname)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yaml'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<...>setup.py", line 1435, in <module>
    main()
  File "<...>setup.py", line 1132, in main
    build_deps()
  File "<...>setup.py", line 439, in build_deps
    check_pydep("yaml", "pyyaml")
  File "<...>setup.py", line 495, in check_pydep
    raise RuntimeError(
RuntimeError: Missing build dependency: Unable to import yaml.
Please install it via conda install pyyaml or pip install pyyaml
`% pip install pyyaml`
Requirement already satisfied: pyyaml in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (6.0.1)

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.3
Libc version: N/A

Python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[conda] numpy                     1.26.4          py311he598dae_0  
[conda] numpy-base                1.26.4          py311hfbfe69c_0  
[conda] numpydoc                  1.5.0           py311hca03da5_0  

cc @malfet @seemethere

**Comment by malfet** [comment]
Please note that you are running Python3.12 (based on `/opt/homebrew/Cellar/python@3.12/3.12.3/`), but your `pip` command aliases to 3.11 `Requirement already satisfied: pyyaml in /Library/Frameworks/Python.framework/Versions/3.11`

Python-3.12 runtime can not see packages installed into 3.11 and vice versa. One way to fix the problem is make sure PATH points to the right pip or run `pip install` as `python3 -mpip install pyyaml`

**Comment by Baiyuetribe** [comment]
same issue. fixed by `brew uninstall python3`
