### ISSUE TITLE
Error when import torch

### ISSUE THREAD

**Issue by ShijianXu** [pytorch/pytorch#12711]
Hi,

I have an error when import torch.

System: win10
install: conda
My python is: Python 3.6.3 :: Anaconda custom (64-bit)
I install pytorch via "conda install pytorch-cpu -c pytorch", and I didn't install torchvision at that time. At first, it all works fine. Then, today I found that I didn't install torchvision when I tried the codes in pytorch documents, so I install torchvision via "pip install torchvision".
After that, all kinds of errors occurred. Even when I uninstalled torchvision(pip uninstall torchvision), I still got the error:
`Traceback (most recent call last):
  File "E:\cs231n\pytorch_learn.py", line 1, in <module>
    import torch
  File "D:\Software\Anaconda\lib\site-packages\torch\__init__.py", line 80, in <module>
    from torch._C import *
ImportError: DLL load failed: 页面文件太小，无法完成操作`
And all the codes that can run before installing torchvision can't run now.

Can anyone help me? Thank you very much.

**Comment by mhubii** [comment]
Try to `pip uninstall torchvision`. Then, run `pip3 install torchvision`. You may have mixed up 2 different python versions.

**Comment by ShijianXu** [comment]
yes, I have uninstalled torchvision `pip uninstall torchvision`. The problem is that the codes that can run well before I installing torchvision all can't run now. If I `import torch`, the error will occur.

**Comment by mhubii** [comment]
Could be related to this #4518 issue.

**Comment by ShijianXu** [comment]
Thank you for your help.
Well, I think I have occurred an interesting problem and I have to say everything clearly. 
At first, I was trying the code in Pytorch tutorial, which is "Training a classifier". I followed the instruction, and I found that I didn't install torchvision, so I installed torchvision via `pip install torchvision`. I have a python installed on the system and a python contained in Anaconda. I think I have mixed them here. Whatever, torchvision is installed and I successfully downloaded CIFAR10 dataset. But latter, I occured `RuntimeError: freeze_support()`, just as [#5858](https://github.com/pytorch/pytorch/issues/5858) described. I think this error consumed my memory. Because, after that, I found that the error I described above come up. Just now, when I was browsing websites, chrome can't open webpages, it crashed and told me no enough memory. I restared my computer, and this error `Traceback (most recent call last): File "E:\cs231n\pytorch_learn.py", line 1, in <module> import torch File "D:\Software\Anaconda\lib\site-packages\torch\__init__.py", line 80, in <module> from torch._C import * ImportError: DLL load failed: 页面文件太小，无法完成操作` disappeared. It's weird.

**Comment by ShijianXu** [comment]
It's weird but I can run my former codes now.

**Comment by mhubii** [comment]
I think that multiprocessing is still an open issue on the windows support. Code has to be wrapped inside 
```python
if __name__ == "__main__":
    
    # Code goes in here.
```

**Comment by ShijianXu** [comment]
Yes, I realized it. Thanks a lot.

**Comment by Yatharth08** [comment]
import torch

RuntimeError: method 'detach' already has a docstring

**Comment by vakul-singh** [comment]
try pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-win_amd64.whl

**Comment by bright1993ff66** [comment]
I also encountered the same DDL error. I fix it by:

1. upgrading from python 3.5.0 to python 3.6.6. 
2. upgrading numpy

Hope this could help~

**Comment by GowravTata** [comment]
I am using Windows 10 OS, 
Python Version - 3.7
CUDA - 10.2
Installed Method -  " conda install pytorch torchvision cudatoolkit=10.2 -c pytorch " 
It was successfully installed, when trying to import throws up an error as  -    No module named 'torch'
I checked the  package list (!pip list ) it is present

**Comment by saimazansari** [comment]
> I am using Windows 10 OS,
> Python Version - 3.7
> CUDA - 10.2
> Installed Method - " conda install pytorch torchvision cudatoolkit=10.2 -c pytorch "
> It was successfully installed, when trying to import throws up an error as - No module named 'torch'
> I checked the package list (!pip list ) it is present

Thank you. It worked for me
