### ISSUE TITLE
optimizer.step() in word_language_model example

### ISSUE THREAD

**Issue by reachablesa** [pytorch/pytorch#1271]
Hi, 

In the word_language_model example, I could not see optimizer.step() function is used. How it is possible to update rnn/lstm weight matrices without calling it? Most probably I am missing something but I would appreaciate if one can explain what I am misssing.

Thanks.

**Comment by spro** [comment]
The weights are being updated "by hand" instead of using an optimizer here https://github.com/pytorch/examples/blob/master/word_language_model/main.py#L141

**Comment by reachablesa** [comment]
Thanks!

**Comment by soumith** [comment]
future questions go here: https://discuss.pytorch.org
