### ISSUE TITLE
Tensor slicing reducing dimensionality of tensor 

### ISSUE THREAD

**Issue by rachelglenn** [pytorch/pytorch#127236]
### 🐛 Describe the bug

I have a tensor x of size: batch, channel, height, width, and two values. I am trying to slice the tensor modify the tensor and put it back into x.

b, c, h, w, two = x.shape
for i in range(c):
                real_image = torch.zeros((b, h, w, 1))
                imag_image = torch.zeros((b, h, w, 1))
                real_image[:,:,:,:] = x[:, i, :, :, 0]
                imag_image[:,:,:,:]  = x[:, i, :, :, 1]
I get the error: 

real_image[:,:,:,:] = x[:, i, :, :, 0]
RuntimeError: The expanded size of the tensor (1) must match the existing size (430) at non-singleton dimension 3.  Target sizes: [1, 256, 256, 1].  Tensor sizes: [256, 256]

I think that when I slice x, it is reducing my dimensions from [1, 256,256, 1] to [256,256]. Why would it do that?

### Versions

I don't think this matters on the pytorch version.

**Comment by soulitzer** [comment]
It is doing that because an index is no longer required to index into that dimension. If you'd like to keep the dimension, you can use `t.unsqueeze(i)`.

Btw, issues are for bug reports and feature requests only, for questions please visit the forum https://discuss.pytorch.org/.
