### ISSUE TITLE
CLA required despite being existing contributor

### ISSUE THREAD

**Issue by OverLordGoldDragon** [pytorch/pytorch#127272]
### 📚 The doc issue

https://pytorch.org/blog/a-contributor-license-agreement-for-pytorch/

> PyTorch’s BSD license is **not** changing. There is no impact to PyTorch users. CLAs will only be required for new contributions to the project. For past contributions, no action is necessary. Everything else stays the same, whether it’s IP ownership, workflows, contributor roles or anything else that you’ve come to expect from PyTorch.

I'm an existing contributor, why am I required to sign?

https://github.com/pytorch/pytorch/pull/126506

**Comment by soulitzer** [comment]
Thanks for the PR! I think the quote is just saying that no action is necessary for changes that have already been committed.

> For past contributions, no action is necessary.

Any external contributors need to sign the CLA to submit any new changes, even if they have contributed to repo before.

> Moving forward, all contributors to projects under the PyTorch GitHub organization will need to sign a CLA to merge their contributions.

**Comment by OverLordGoldDragon** [comment]
I see, contribut**ions**, not contribut**ors**.
