### ISSUE TITLE
Add Tensor.nbytes() / `Tensor.itemsize()`

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#12728]
## 🚀 Feature
Add `nbytes` and `itemsize` methods to Tensor. It has the same semantics as https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.nbytes.html and https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.itemsize.html (though, in keeping with PyTorch style, it is a function call, not a property).

## Motivation

The primary motivation is that caffe2::Tensor has these two methods, it's used somewhat frequently in the Caffe2 codebase, and it seems like a generally useful thing to have around.

## Alternatives

* Don't add them, and make users do the computation themselves. This might be a little annoying to do, because if we don't have `itemsize()` the user has to compute it themselves from the dtype.

**Comment by colesbury** [comment]
Seem useful. I think `itemsize` is equivalent to the existing [`element_size()`](https://pytorch.org/docs/stable/tensors.html?highlight=element_size#torch.Tensor.element_size). 

I like matching NumPy names, even at the cost of some duplicate functionality. I think it's usually good to keep NumPy properties as properties in PyTorch (e.g. `shape`, `dtype`), even if it means that the C++ code can't exactly match the Python code.

**Comment by apaszke** [comment]
Yes, please make them properties. We already have `t.shape`.

**Comment by ezyang** [comment]
I'm probably not going to actually finish this task.

**Comment by fedden** [comment]
I'd like to add these properties as a first contribution to pytorch. Can anyone advise if they are still desired? Thanks

**Comment by ezyang** [comment]
@fedden yes, we still would like it!

**Comment by mathemage** [comment]
> @fedden yes, we still would like it!

Hi @ezyang !
Is this issue still desired? I'm looking for a good first issue to work on. Thanks!

**Comment by Feliren88** [comment]
Hey, I am keen to work on this as first timer in open source.

**Comment by praneethratna** [comment]
@mruberry Is this issue still available? If yes Could you please give me an heads up of what needs to be implemented, I`ll start working on it

**Comment by mruberry** [comment]
I think this issue is still valid (you can check by seeing if itemsize and nbytes are available after building PyTorch) and the issue is to implement these two methods. The best way to understand how to do this is to read the contributor's guide, the README in ATen/src/ATen/native, and look at other PRs adding operators.

**Comment by JohnNesbit** [comment]
I looked and this issue is still valid in 1.9.0. I will start working on it so long as there are no objections from someone currently working on it.

**Comment by vadimkantorov** [comment]
What will it do for quantized types? Is there 4bit or 2bit quantised dtypes?

I propose to also add some property specifying item width in bits (for future support of low-width types such as 1-bit https://github.com/pytorch/pytorch/issues/32867). As far as I know it does not exist in NumPy, but would be useful for these low-width cases.

Should I create a separate issue for this discussion?

**Comment by JohnNesbit** [comment]
It will follow whatever tensor.element_size() returns. Itemsize will specify item width in bits. I will change my pull to make these properties instead of functions.

**Comment by vadimkantorov** [comment]
In NumPy itemsize specifies item width in bytes: [`ndarray.itemsize: Length of one array element in bytes.`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.itemsize.html), so the bits-property should have a different name...

**Comment by JohnNesbit** [comment]
There is no such thing as a 2-bit quantized tensor dtype in pytorch in the stable release https://pytorch.org/docs/stable/tensors.html. I am not aware of a pytorch tensor dtype of less than one byte in information, so Itemsize returns 1 for a 4bit quantized. I misspoke when I said it returns item width in bits, it returns item byte width.

**Comment by vadimkantorov** [comment]
About 4-bit dtype: https://github.com/pytorch/pytorch/pull/44574
