### ISSUE TITLE
Passing a scalar Tensor inside tuple size can cause segfaults sometimes (PyTorch 0.4.1)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#12724]
@jwieting reported that they had a segfault in PyTorch, and they fixed it by making the following code change:

```
torch.zeros((n2, torch.max(all_g1_lengths)).long()
// to
torch.zeros((n2, torch.max(all_g1_lengths).item())).long() 
```

I checked and tensors are still accepted as arguments on master:

```
>>> torch.zeros((2, torch.tensor(3)))
tensor([[0., 0., 0.],
        [0., 0., 0.]])
```

But maybe there is some funny business going here? Worth a closer look, perhaps.

We don't have a small repro, it was some training job that failed on the fourth epoch.

**Comment by colesbury** [comment]
@jamesr66a fixed this in https://github.com/pytorch/pytorch/pull/12738
