### ISSUE TITLE
SpectralNorm in eval doesn't connect grad to weight_orig

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#12737]

**Comment by vadimkantorov** [comment]
Given many very tricky bugs in spectral norm (should be easily implementable on the first glance, but in fact no): https://github.com/pytorch/pytorch/issues?q=is%3Aissue+spectral+norm+is%3Aclosed , do you have any thoughts on an abstraction for this sort of thing that reliably: https://github.com/pytorch/pytorch/issues/7313 ?

**Comment by SsnL** [comment]
@vadimkantorov yes yes yes @t-vi and I have been talking about this lately. Maybe sometime we will resurrect the CalculatedParam idea, when we have free time.

**Comment by crcrpar** [comment]
Dose abstraction mean something like these https://github.com/NVIDIA/apex/tree/master/apex/reparameterization?

**Comment by crcrpar** [comment]
thanks.

Yes, it looks far more sophisticated.

**Comment by SsnL** [comment]
Yes. I agree with @vadimkantorov . The apex solution is a nice wrapper, but still the same approach structurally.

**Comment by SsnL** [comment]
Oh my. I just realized that DP + SN in eval is still broken because the same randomly initialized weight matrix is never overwritten in base module, and it is still used! Anyways, I will fix it.

**Comment by SsnL** [comment]
fixed
