### ISSUE TITLE
Dynamo should prune non-live captured variables 

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#127350]
```py
import torch
@torch.compile(backend="eager", fullgraph=True)
def f(x):
   y = x.clone()
   def g():
      return y + 1
   return g()

g = f(torch.randn(4))
```
running the above with TORCH_LOGS=+graph_code gives the following graph:
```
def forward(self, L_x_: "f32[4]"):
    l_x_ = L_x_
    y: "f32[4]" = l_x_.clone();  l_x_ = None
    add: "f32[4]" = y + 1
    return (y, add)
```
Dynamo doesn't need to return y because it is not accessible from the outside of the compiled function. The reason why it does is:
- every time Dynamo captures a Tensor, it writes a new side effect
- If any Tensor participates in a live side effect, then Dynamo must return it as an output of the graph
- This side effect never gets pruned, so Dynamo returns it as an output of the graph

This is potentially a performance issue for models that do a lot of capturing of variables

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by zou3519** [comment]
I guess I'm signed up (https://github.com/pytorch/pytorch/pull/128028)

**Comment by zou3519** [comment]
No, there are cases to this:
- https://github.com/pytorch/pytorch/pull/128028
- https://github.com/pytorch/pytorch/pull/127998

I don't understand why they're different. We fixed one of them.

**Comment by zou3519** [comment]
I think we're good on this.

**Comment by StrongerXi** [comment]
I'm able to repro this on 274883083d, seems related to what I chased down in #124653? @zou3519

**Comment by zou3519** [comment]
mm yeah there were two issues and we only fixed one of them

**Comment by zou3519** [comment]
The above script still repros for me

**Comment by StrongerXi** [comment]
I'll take this too, should be the same as #124653.
