### ISSUE TITLE
torch.compile (inductor) bug random signed number generation

### ISSUE THREAD

**Issue by hgreving2304** [pytorch/pytorch#127310]
### 🐛 Describe the bug

```python
import torch

def foo():
  a = torch.randint(-1, 0, (1, 1, 1), device="cpu", dtype=torch.int64)
  res_cpu = torch.bitwise_right_shift(a, 31)
  print("cpu is" , res_cpu)

compiled_foo = torch.compile(foo)
compiled_foo()
```

..gives me `cpu is tensor([[[8589934591]]])`, which looks like a logical shift to me. Upon further inspection looking at the C-code using TORCH_COMPILE_DEBUG=1, it looks like the generated `randint64_cpu` function returns uint64_t, and the C-kernel is using auto (`auto tmp2 = randint64_cpu(tmp0, tmp1, -1, 0); `). torch.int64 is signed, but the result is arithmetic shift of a positive number, but should be signed negative.

### Versions

Versions of relevant libraries:
[pip3] flake8==3.9.2
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] torch==2.1.2+c5a5e17537.a083e14bb5c685a176ae5b9f4cb2485c42740ab4.build.gcc930
[pip3] torchaudio==2.1.2
[pip3] torchtext==0.6.0
[pip3] torchvision==0.16.2+382c6195.a083e14bb5c685a176ae5b9f4cb2485c42740ab4.gcc930
[conda] mkl                       2023.1.0         h84fe81f_48680    conda-forge
[conda] mkl-include               2023.1.0         h84fe81f_48680    conda-forge
[conda] numpy                     1.23.5          py311h7d28db0_0    conda-forge
[conda] torch                     2.1.2+c5a5e17537.a083e14bb5c685a176ae5b9f4cb2485c42740ab4.build.gcc930          pypi_0    pypi
[conda] torchaudio                2.1.2                    pypi_0    pypi
[conda] torchtext                 0.6.0                    pypi_0    pypi
[conda] torchvision               0.16.2+382c6195.a083e14bb5c685a176ae5b9f4cb2485c42740ab4.gcc930          pypi_0    pypi

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by leslie-fang-intel** [comment]
Hi @hgreving2304, thanks for reporting the issue. Will take a look.

**Comment by hgreving2304** [comment]
I don't have access right now to the latest version, I can try it out later at home. In the meantime, you could also check whether the emitted C-code correctly shifts a signed vs. an unsigned number in the latest version and whether there was an explicit fix.

**Comment by leslie-fang-intel** [comment]
Here are the generated code, `randint64_cpu` returns type of `int64` and we use it to do the bit shift.
```
cpp_fused_bitwise_right_shift_0 = async_compile.cpp_pybinding(['int64_t*'], '''
#include "/tmp/torchinductor_leslie/sk/cskh5dx62fglpphcrl6723dnmowdabouerrzy3dmqcngbxwfa7bv.h"
extern "C" void kernel(int64_t* in_out_ptr0)
{
    {
        auto tmp0 = in_out_ptr0[static_cast<long>(0L)];
        auto tmp1 = static_cast<int32_t>(0);
        auto tmp2 = static_cast<int64_t>(-1);
        auto tmp3 = static_cast<int64_t>(0);
        auto tmp4 = randint64_cpu(tmp0, tmp1, tmp2, tmp3);
        auto tmp5 = static_cast<int64_t>(31);
        auto tmp6 = decltype(tmp4)(tmp4 >> tmp5);
        in_out_ptr0[static_cast<long>(0L)] = tmp6;
    }
}
''')
```

**Comment by hgreving2304** [comment]
Just tried, with the latest version from Ubuntu I am getting a signed shift, fwiw that's fine. I recommend verifying that there was an explicit fix, thanks..

**Comment by leslie-fang-intel** [comment]
Hi @hgreving2304, I am going to close this ticket since the UT has added in PyTorch Main. Feel free to reopen if any further discussion.
