### ISSUE TITLE
Loading Old Checkpoints with DTensor

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#127351]
### 🐛 Describe the bug

When loading old checkpoints saved with ShardedTensor, I am unable to switch to DTensor from old torch versions (2.0.1) as I encounter the following error.
```
/composer/composer/core/state.py:1498: in load_state_dict
    self.load_model_state(
/composer/composer/core/state.py:1346: in load_model_state
    set_model_state_dict(
/composer/composer/trainer/_patch_pytorch.py:393: in set_model_state_dict
    return _load_model_state_dict(model, model_state_dict, info)
/usr/lib/python3/dist-packages/torch/distributed/checkpoint/state_dict.py:428: in _load_model_state_dict
    _state_dict_fn(model, "load_state_dict")(
/usr/lib/python3/dist-packages/torch/nn/modules/module.py:2175: in load_state_dict
    load(self, state_dict)
/usr/lib/python3/dist-packages/torch/nn/modules/module.py:2163: in load
    load(child, child_state_dict, child_prefix)  # noqa: F821
/usr/lib/python3/dist-packages/torch/nn/modules/module.py:2163: in load
    load(child, child_state_dict, child_prefix)  # noqa: F821
/usr/lib/python3/dist-packages/torch/nn/modules/module.py:2163: in load
    load(child, child_state_dict, child_prefix)  # noqa: F821
/usr/lib/python3/dist-packages/torch/nn/modules/module.py:2157: in load
    module._load_from_state_dict(
/usr/lib/python3/dist-packages/torch/nn/modules/module.py:2012: in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
/usr/lib/python3/dist-packages/torch/nn/modules/module.py:72: in __call__
    return self.hook(module, *args, **kwargs)
/usr/lib/python3/dist-packages/torch/utils/_contextlib.py:115: in decorate_context
    return func(*args, **kwargs)
/usr/lib/python3/dist-packages/torch/distributed/fsdp/_state_dict_utils.py:848: in _pre_load_state_dict_hook
    _pre_load_state_dict_hook_fn[fsdp_state._state_dict_type](
/usr/lib/python3/dist-packages/torch/distributed/fsdp/_state_dict_utils.py:673: in _sharded_pre_load_state_dict_hook
    local_tensor = _ext_all_gather_dtensor(
/usr/lib/python3/dist-packages/torch/distributed/fsdp/_fsdp_extensions.py:179: in _ext_all_gather_dtensor
    return all_gather_dtensor_fn(tensor, parent_mesh)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

tensor = ShardedTensor(ShardedTensorMetadata(shards_metadata=[ShardMetadata(shard_offsets=[0, 0], shard_sizes=[16, 32], placeme...pe=torch.float32, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False)))
parent_mesh = None

    def _all_gather_dtensor(
        tensor: DTensor,
        parent_mesh: Optional[DeviceMesh],
    ) -> torch.Tensor:
        """
        All gather a DTensor in its sharded dimension and return the local tensor.
        """
        assert parent_mesh is None
    
>       placements = list(copy.deepcopy(tensor.placements))
E       AttributeError: 'ShardedTensor' object has no attribute 'placements'

/usr/lib/python3/dist-packages/torch/distributed/fsdp/_shard_utils.py:118: AttributeError
```

Is it expected that old sharded checkpoints can be loaded when using DTensor? Is there a recommended path to upgrade old checkpoints?

### Versions

Torch 2.3

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @LucasLLC

**Comment by awgu** [comment]
cc: @fegin @wz337 @LucasLLC

**Comment by fegin** [comment]
@mvpatel2000 Is `model_state_dict` that is fed to `set_model_state_dict` loaded from DCP? If not, then you are loading a `state_dict` that is saved with ShardedTensor and loaded (without conversion) to a FSDP that is initialized with DTensor. You will need some conversion first, which is generally done in DCP.

If `model_state_dict` is loaded from DCP, then we need to debug why the conversion does not happen.

**Comment by mvpatel2000** [comment]
> If `model_state_dict` is loaded from DCP, then we need to debug why the conversion does not happen.
@fegin yes we are loading from DCP. Here is snippet:

```
dist_cp.load_state_dict(
    state_dict=state_dict,
    storage_reader=storage_reader,
    planner=None,
    process_group=process_group,
)
```

**Comment by fegin** [comment]
Can you check if `state_dict` contains `ShardedTensor` before being passed into `load_state_dict`?

**Comment by mvpatel2000** [comment]
@fegin  Yes it has ShardedTensors in it.


Loaded state dict {'state': {'model': OrderedDict([('module.0.weight', ShardedTensor(ShardedTensorMetadata(shards_metadata=[ShardMetadata(shard_offsets=[0, 0], shard_sizes=[16, 32], placement=rank:0/cuda:0), ShardMetadata(shard_offsets=[16, 0], shard_sizes=[16, 32], placement=rank:1/cuda:1)], size=torch.Size([32, 32]), tensor_properties=TensorProperties(dtype=torch.float32, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False)))), ('module.0.bias', ShardedTensor(ShardedTensorMetadata(shards_metadata=[ShardMetadata(shard_offsets=[0], shard_sizes=[16], placement=rank:0/cuda:0), ShardMetadata(shard_offsets=[16], shard_sizes=[16], placement=rank:1/cuda:1)], size=torch.Size([32]), tensor_properties=TensorProperties(dtype=torch.float32, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False)))), ('module.2.weight', ShardedTensor(ShardedTensorMetadata(shards_metadata=[ShardMetadata(shard_offsets=[0, 0], shard_sizes=[4, 32], placement=rank:0/cuda:0), ShardMetadata(shard_offsets=[4, 0], shard_sizes=[4, 32], placement=rank:1/cuda:1)], size=torch.Size([8, 32]), tensor_properties=TensorProperties(dtype=torch.float32, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False))))]), 'optimizers': {'Adam': {'state': {'module.0.weight': {'exp_avg': ShardedTensor(ShardedTensorMetadata(shards_metadata=[ShardMetadata(shard_offsets=[0, 0], shard_sizes=[16, 32], placement=rank:0/cpu), ShardMetadata(shard_offsets=[16, 0], shard_sizes=[16, 32], placement=rank:1/cpu)], size=torch.Size([32, 32]), tensor_properties=TensorProperties(dtype=torch.float32, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False))), 'exp_avg_sq': ShardedTensor(ShardedTensorMetadata(shards_metadata=[ShardMetadata(shard_offsets=[0, 0], shard_sizes=[16, 32], placement=rank:0/cpu), ShardMetadata(shard_offsets=[16, 0], shard_sizes=[16, 32], placement=rank:1/cpu)], size=torch.Size([32, 32]), tensor_properties=TensorProperties(dtype=torch.float32, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False))), 'step': tensor(2.)}, 'module.0.bias': {'exp_avg': ShardedTensor(ShardedTensorMetadata(shards_metadata=[ShardMetadata(shard_offsets=[0], shard_sizes=[16], placement=rank:0/cpu), ShardMetadata(shard_offsets=[16], shard_sizes=[16], placement=rank:1/cpu)], size=torch.Size([32]), tensor_properties=TensorProperties(dtype=torch.float32, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False))), 'exp_avg_sq': ShardedTensor(ShardedTensorMetadata(shards_metadata=[ShardMetadata(shard_offsets=[0], shard_sizes=[16], placement=rank:0/cpu), ShardMetadata(shard_offsets=[16], shard_sizes=[16], placement=rank:1/cpu)], size=torch.Size([32]), tensor_properties=TensorProperties(dtype=torch.float32, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False))), ...

**Comment by fegin** [comment]
No, I meant to print `state_dict` before `load_state_dict`. But I think the answer will be the same given that `load_state_dict` is doing in-place. So the issue is where you get `state_dict`. It should be from the the model you are going to load. 

```
state_dict = model.state_dict()
dcp_cp.load_state_dict(state_dict, ...)
model.load_state_dict(state_dict)
```

So if `state_dict` has ShardedTensor that means the FSDP `model` is configured to have ShardedTensor not DTensor. Then that should not cause errors. If you want to load into DTensor, then `state_dict` should also contain DTensor.

**Comment by mvpatel2000** [comment]
@fegin  apologies, I have verified it was actually going down another code path and not using DCP. I believe we use this path for legacy sharded checkpoints (non-elastic). I will dig further on my end -- I assume the right solution is to reroute these to DCP.

**Comment by fegin** [comment]
@mvpatel2000 Thanks for the update. I'll close the issue for now. Feel free to reopen the issue if you still see the problem.
