### ISSUE TITLE
[While_loop] How to use layer like `torch.nn.BatchNorm2d` with while_loop?

### ISSUE THREAD

**Issue by ManfeiBai** [pytorch/pytorch#127320]
### 🐛 Describe the bug

Hi, I'm trying to support `while_loop` with `DispatchKey.XLA`;

when I try linear and MNIST with torch, code would be dispatched to `DispatchKey.CompositeExplicitAutograd` to use pure python while, and finish;

my local example code for MNIST:
```python
import torch
from torch._higher_order_ops.while_loop import while_loop
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

def test_while_loop_tpu_MNIST_inside_loop(self):

    torch.set_grad_enabled(False)

    n_epochs = 3
    batch_size_train = 8
    batch_size_test = 10
    learning_rate = 0.01
    momentum = 0.5
    log_interval = 10
    random_seed = 1
    torch.backends.cudnn.enabled = False
    torch.manual_seed(random_seed)

    class MNIST(torch.nn.Module):
      def __init__(self):
        super().__init__()
        self.conv1 = torch.nn.Conv2d(1, 10, kernel_size=5, stride=1, padding=2)
        self.bn1 = torch.nn.BatchNorm2d(10)
        self.conv2 = torch.nn.Conv2d(10, 20, kernel_size=5)
        self.bn2 = torch.nn.BatchNorm2d(20)
        self.fc1 = torch.nn.Linear(500, 50)
        self.fc2 = torch.nn.Linear(50, 10)

      def forward(self, iteri, x, y):
        def cond_fn(iteri, x, y):
          return iteri > 0

        def body_fn(iteri, x, y):
          y = F.relu(F.max_pool2d(self.conv1(x), 2))
          y = self.bn1(y) # torch.while_loop's body_fn might be modifying the input!
          y = F.relu(F.max_pool2d(self.conv2(y), 2))
          y = self.bn2(y)
          y = torch.flatten(y, 1)
          y = F.relu(self.fc1(y))
          y = self.fc2(y)

          return iteri - 1, x.clone(), F.log_softmax(y, dim=1)

        return while_loop(cond_fn, body_fn, (iteri, x, y))

      def forward_compare(self, iteri, x, y):
        y = F.relu(F.max_pool2d(self.conv1(x), 2))
        y = self.bn1(y) # torch.while_loop's body_fn might be modifying the input!
        y = F.relu(F.max_pool2d(self.conv2(y), 2))
        y = self.bn2(y)
        y = torch.flatten(y, 1)
        y = F.relu(self.fc1(y))
        y = self.fc2(y)
        return iteri - 1, x.clone(), F.log_softmax(y, dim=1)

    mnist = MNIST()
    bs=16
    l_in_0 = torch.randn(bs, 1, 28, 28, dtype=torch.float32)
    l_out = torch.randn(bs, 10, dtype=torch.float32)
    iteri = torch.tensor(3, dtype=torch.int64)
    _, _, res = mnist(iteri, l_in_0, l_out)

    # === expected result for one iteration to be compared since body_fn defined use the same input in each iteration ===
    _, _, expected_res = mnist.forward_compare(iteri, l_in_0, l_out)
    self.assertTrue(torch.all(torch.eq(res, expected_res)))
```

---

for code with `DispatchKey.XLA` and `torch.nn.BatchNorm2d`, it would stoped/failed at `[_has_potential_branch_input_mutation](https://github.com/pytorch/pytorch/blob/d6e3e89804c4063827ea21ffcd3d865e5fe365d9/torch/_higher_order_ops/while_loop.py#L250C16-L250C52)` check with ERROR:
```
torch._higher_order_ops.utils.UnsupportedAliasMutationException: torch.while_loop's body_fn might be modifying the input!
```

do we have example for model with layer like `torch.nn.BatchNorm2d` which `_has_potential_branch_input_mutation` is true, and without using pure while loop?

my local code with `DispatchKey.XLA` and `torch.nn.BatchNorm2d`:
```
import torch
import torch_xla
import torch_xla.experimental.fori_loop
from torch_xla.experimental.fori_loop import fori_loop
from torch._higher_order_ops.while_loop import while_loop
import torch_xla.core.xla_model as xm
import torch_xla.core.xla_builder as xb
import torch_xla.utils.utils as xu
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

def test_while_loop_tpu_MNIST_inside_loop_without_BN(self):
    xm.mark_step()
    device = xm.xla_device()
    torch.set_grad_enabled(False)

    n_epochs = 3
    batch_size_train = 8
    batch_size_test = 10
    learning_rate = 0.01
    momentum = 0.5
    log_interval = 10
    random_seed = 1
    torch.backends.cudnn.enabled = False
    torch.manual_seed(random_seed)

    class MNIST(torch.nn.Module):
      def __init__(self):
        super().__init__()
        self.conv1 = torch.nn.Conv2d(1, 10, kernel_size=5, stride=1, padding=2)
        self.bn1 = torch.nn.BatchNorm2d(10)
        self.conv2 = torch.nn.Conv2d(10, 20, kernel_size=5)
        self.bn2 = torch.nn.BatchNorm2d(20)
        self.fc1 = torch.nn.Linear(500, 50)
        self.fc2 = torch.nn.Linear(50, 10)

      def forward(self, iteri, x, y):
        def cond_fn(iteri, x, y):
          return iteri > 0

        def body_fn(iteri, x, y):
          # y = self.bn1(F.relu(F.max_pool2d(self.conv1(x), 2)))
          # y = self.bn2(F.relu(F.max_pool2d(self.conv2(y), 2)))

          y = F.relu(F.max_pool2d(self.conv1(x), 2))
          y = self.bn1(y) # torch.while_loop's body_fn might be modifying the input!
          y = F.relu(F.max_pool2d(self.conv2(y), 2))
          y = self.bn2(y)
          y = torch.flatten(y, 1)
          y = F.relu(self.fc1(y))
          y = self.fc2(y)

          return iteri - 1, x.clone(), F.log_softmax(y, dim=1)

        return while_loop(cond_fn, body_fn, (iteri, x, y))

      def forward_compare(self, iteri, x, y):
        y = F.relu(F.max_pool2d(self.conv1(x), 2))
        y = self.bn1(y) # torch.while_loop's body_fn might be modifying the input!
        y = F.relu(F.max_pool2d(self.conv2(y), 2))
        y = self.bn2(y)
        y = torch.flatten(y, 1)
        y = F.relu(self.fc1(y))
        y = self.fc2(y)
        return iteri - 1, x.clone(), F.log_softmax(y, dim=1)


    mnist = MNIST()
    for name, param in mnist.named_parameters():
      print("name: ", name, "'s param size: ", param.size())
      # print("param size: ", param.size())

    mnist.to(device)
    bs=16
    l_in_0 = torch.randn(bs, 1, 28, 28, dtype=torch.float32, device=device)
    l_out = torch.randn(bs, 10, dtype=torch.float32, device=device)
    iteri = torch.tensor(3, dtype=torch.int64, device=device)
    _, _, res = mnist(iteri, l_in_0, l_out)
    print("res: ", res)

    # === expected result for one iteration to be compared since body_fn defined use the same input in each iteration ===
    _, _, expected_res = mnist.forward_compare(iteri, l_in_0, l_out)
    print("expected_res: ", expected_res)
    self.assertTrue(torch.all(torch.eq(res, expected_res)))
```

### Versions

--2024-05-28 18:34:01--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22068 (22K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py                      100%[==================================================================>]  21.55K  --.-KB/s    in 0.002s  

2024-05-28 18:34:01 (12.8 MB/s) - ‘collect_env.py’ saved [22068/22068]

Collecting environment information...
PyTorch version: 2.4.0a0+git08c260b
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.31

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-1022-gcp-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          240
On-line CPU(s) list:             0-239
Thread(s) per core:              2
Core(s) per socket:              60
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7B12
Stepping:                        0
CPU MHz:                         2249.998
BogoMIPS:                        4499.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       3.8 MiB
L1i cache:                       3.8 MiB
L2 cache:                        60 MiB
L3 cache:                        480 MiB
NUMA node0 CPU(s):               0-59,120-179
NUMA node1 CPU(s):               60-119,180-239
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save umip rdpid

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.11.0
[pip3] torch==2.4.0a0+git08c260b
[pip3] torch_xla==2.4.0+gitbae0ea2
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] torch                     2.4.0a0+git08c260b           dev_0    <develop>
[conda] torch-xla                 2.4.0+gitbae0ea2           dev_0    <develop>

cc @bdhirsh @ezyang @msaroufim @anijain2305 @chauhang @zou3519 @ydwu4

**Comment by JackCaoG** [comment]
cc @angelayi @ydwu4

**Comment by ManfeiBai** [comment]
thanks, above MNIST test code passed with `self.bn1 = torch.nn.BatchNorm2d(10, affine=False, track_running_stats=False)` by disabled learnable parameters

**Comment by ManfeiBai** [comment]
thanks, above MNIST test code for Dispatchkey.XLA passed with `self.bn1 = torch.nn.BatchNorm2d(10, affine=False, track_running_stats=False)` by disable learnable parameters

**Comment by ydwu4** [comment]
For a batch norm mod, its states are lifted as inputs to the body_fn and we create a `torch.ops.aten._native_batch_norm_legit_functional.default` in functionalization pass. This operator is non-mutating and can pass the mutating input check. We can check by exporting the model:
```python
ep = torch.export.export(mnist, (iteri, l_in_0, l_out))
ep.module().print_readable()
```

But seems that F.batch_norm is turned into a different operator in your case. Can you show what operator the batch norm is turned into?

**Comment by ManfeiBai** [comment]
yes, sure,

with code `self.bn1 = torch.nn.BatchNorm2d(10)`: [code](https://gist.github.com/ManfeiBai/ca4813ba63823845fb87516e916f538b), failed and print: https://gist.github.com/ManfeiBai/c4672daa3ce35e7f5e2e1b1c6303561d

with code `self.bn1 = torch.nn.BatchNorm2d(10, affine=False, track_running_stats=False)`: [code](https://gist.github.com/ManfeiBai/ad2134d9e6aabf9b6b6f43dba9e0f725), passed and print: https://gist.github.com/ManfeiBai/0583b2b084a5cc276536718dce3571be

**Comment by ManfeiBai** [comment]
btw, @ydwu4, do we expect `torch.nn.BatchNorm2d` is non-mutating when we use `while_loop`?

And iiuc, for mutating ops, `while_loop` would call pure python while loop? or we suggest user to use `scan` for mutating ops?

**Comment by ydwu4** [comment]
> does these args are learnable args mentioned

Yeah, they're learnable in training. Is the mnist demo for inference only? If it's only for inference, setting  `affine=False, track_running_stats=False` is the proper approach to unblock since while_loop doesn't support training yet. 

Generally speaking, if there isn't a functionalization key, while_loop goes [here](https://github.com/pytorch/pytorch/blob/main/torch/_higher_order_ops/while_loop.py#L146). All mutating ops are allowed.  

But in your case, I think there's a `functionalize` transformation invoked somewhere in the stack, which triggers the functionalization key implementation of while_loop. For mutating ops, if they're mutating the inputs, i.e. producing side effect, while_loop will detect these mutating ops in functionalization key thus causing the error because by definition a function that's functionalized shouldn't have side-effects.

**Comment by ManfeiBai** [comment]
> Is the mnist demo for inference only?
yes, this mnist demo is for inference only

> Can you try self.bn2 = torch.nn.BatchNorm2d(20).eval()? 
yeah, sure, tested and passed locally too

Thanks for the detailed info, Yidi, I would use `affine=False, track_running_stats=False` to set batch_norm layer to be non-mutating in this inference test case for now

cc @JackCaoG

**Comment by ydwu4** [comment]
Close it for now. Feel free to re-open it when needed!
