### ISSUE TITLE
address TODO: model is somehow not being freed when z3 is available

### ISSUE THREAD

**Issue by laithsakka** [pytorch/pytorch#127444]
# TODO model is somehow not being freed when z3 is available
 repo:
   
1) remove 
 if not config.inline_inbuilt_nn_modules:
        # TODO model is somehow not being freed when z3 is available
        unittest.expectedFailure(
            DynamicShapesMiscTests.test_parameter_free_dynamic_shapes  # noqa: F821
        )

2) run 
python test/dynamo/test_dynamic_shapes.py -k test_parameter_free_dynamic_shapes

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by ezyang** [comment]
iirc, the z3 code holds onto some tensors as part of the metadata it has, and that could cause this sort of problem. I'd just manually disable TV on this test.

**Comment by laithsakka** [comment]
@ezyang  shall i close the issue?

**Comment by ezyang** [comment]
oh I see, we did disable it. Well, idk, if someone wants to investigate I guess they can

**Comment by anijain2305** [comment]
This could be because with inlining Dynamo does not need need any pointers to the inbuilt modules. Closing because this is an improvement.
