### ISSUE TITLE
## AttributeError: type object 'torch._C._VariableFunctions' has no attribute 'lstm'

### ISSUE THREAD

**Issue by terminator9487** [pytorch/pytorch#12745]
Hi, all.
        I used the Pytorch to build the MLP model before, and I was trying to realize the LSTM with this code on my own data. However, the  following error was occurred. It seems that it doesn't exit the attribute ._C._VariableFunctions. 
![screenshot from 2018-10-17 12-19-03](https://user-images.githubusercontent.com/13758812/47060103-2c061400-d207-11e8-88c7-52202492ba20.png)

 Does anyone have any clue for this problem? Thanks for your help in advance.

Best regards
Irving

**Comment by soumith** [comment]
please follow the issue template. Reopen an issue with a code reproduction to get to this error message.
