### ISSUE TITLE
Ensure the Python custom ops tutorial actually runs in PyTorch 2.4

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#127443]
We're releasing it and disabling it before PyTorch 2.4 so that we can point users to something instead of 404-ing

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by ezyang** [comment]
@zou3519 should we have a custom ops label

**Comment by zou3519** [comment]
We do, you just can't search it easily

**Comment by zou3519** [comment]
Merged in https://github.com/pytorch/tutorials/pull/2953
