### ISSUE TITLE
UNSTABLE inductor / cuda12.1-py3.10-gcc9-sm86 / test (dynamic_inductor_timm)

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#127438]
### 🐛 Describe the bug

CI Failure:

https://github.com/pytorch/pytorch/actions/runs/9289357491/job/25565005217

### Versions

2.4.0

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
Job doesn't look unstable anymore
