### ISSUE TITLE
Fix torch._dynamo.exc.Unsupported: call_method GetAttrVariable(UnspecializedNNModuleVariable(CheckpointWrapper), __dict__) __contains__ [ConstantVariable()] {}

### ISSUE THREAD

**Issue by laithsakka** [pytorch/pytorch#127416]
repo:

 TORCHDYNAMO_INLINE_INBUILT_NN_MODULES=1 pytest ActivationCheckpointingViaTagsTests.test_distributed_utils_checkpoint_wrapper  ### 

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by laithsakka** [comment]
This will be fixed with @anijain2305  work on inlining get_attr. 
This is the only failure in /test/dynamo/test_activation_checkpointing.py

**Comment by anijain2305** [comment]
Fixed on main
