### ISSUE TITLE
Upgrade MacOS runner to 14

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#127490]
This is a preemptive non-blocking SEV to cover the upgrade of our m1 runner from MacOS 13 to 14.  During the rollout, there might be queue, so we will keep track of the process here.

* May 29th, 1800: Start rolling out to half the fleet https://github.com/pytorch-labs/pytorch-gha-infra/actions/runs/9295148421
  * The first attempt fails because we hit the max capacity of macOS hardware on the region https://github.com/pytorch-labs/pytorch-gha-infra/actions/runs/9295148421/attempts/1 , retrying, might need to manually release some MacOS 13 instances
* May 30th: Attempt to restore MacOS trunk sanity https://github.com/pytorch/pytorch/issues/127542#issuecomment-2140849231
* May 30th: https://github.com/pytorch/pytorch/pull/127582 to update the rest of PyTorch CI/CD to macOS 14
* May 31st, 10:30: Start rolling out to all the fleet https://github.com/pytorch-labs/pytorch-gha-infra/actions/runs/9322093010
* May 31st: 15:00: Need to do several round of tearing down and scaling up, but the whole fleet is on macos 14 now
* May 31st:  https://github.com/pytorch/pytorch/pull/127582 has been landed, but there is a build failure on 14 https://hud.pytorch.org/pytorch/pytorch/commit/57baae9c9b43fd31199dedd3f0fd5ed67faf5769 due to the deprecation of https://en.cppreference.com/w/cpp/header/codecvt
  * Need a forward fix in https://github.com/pytorch/pytorch/pull/127659

**Comment by DanilBaibak** [comment]
Resolved the issue. All runners are set up and ready. We currently have around 49 `macos-m1-13` runners and 52 `macos-m1-14` runners.

**Comment by huydhn** [comment]
This is done, there is a remaining failed periodic iOS build on ` macos-14-xlarge`, but that's from GitHub, so we can easily switch back to ` macos-13-xlarge` if needed, but let me take a closer look for a forward fix next week.
