### ISSUE TITLE
NCCL error in: /var/lib/jenkins/workspace/torch/lib/c10d/../c10d/NCCLUtils.hpp:29, unhandled cuda error

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#12744]
Flaky c10d test:

```
Oct 16 02:07:00 test_broadcast_ops (__main__.ProcessGroupNCCLTest) ... terminate called after throwing an instance of 'std::runtime_error'
Oct 16 02:07:00   what():  NCCL error in: /var/lib/jenkins/workspace/torch/lib/c10d/../c10d/NCCLUtils.hpp:29, unhandled cuda error
Oct 16 02:07:00 Traceback (most recent call last):
Oct 16 02:07:00   File "test/run_test.py", line 393, in <module>
Oct 16 02:07:00     main()
Oct 16 02:07:00   File "test/run_test.py", line 385, in main
Oct 16 02:07:00     raise RuntimeError(message)
Oct 16 02:07:00 RuntimeError: test_c10d failed! Received signal: SIGIOT
```

log https://circleci.com/gh/pytorch/pytorch/67056?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pietern** [comment]
Argh... @ezyang For the new Circle setup do we run 1 test suite per machine? I.e. is there any chance of interference between test suites when running CUDA related tests?

**Comment by ezyang** [comment]
cc @yf225

**Comment by yf225** [comment]
@pietern Yes we run 1 test suite per VM like the old Jenkins setup.

**Comment by teng-li** [comment]
@ezyang  is this still happening

**Comment by teng-li** [comment]
Let's close it for now since now we build NCCL from source

**Comment by Lyken17** [comment]
Hi, after upgrading to pytorch 1.0, I get similar errors when launching distributed training
`RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/../c10d/NCCLUtils.hpp:39, invalid argument`
```bash
python main.py -a resnet50 --lr 0.01 --dist-url 'tcp://127.0.0.1:12345' \
    --dist-backend 'nccl' --multiprocessing-distributed /ssd/dataset/imagenet --rank 0
```

**Comment by teng-li** [comment]
@Lyken17  You forgot to put the argument `--world-size`, this needs to be set for the program to work. Try it and let us know?

**Comment by Lyken17** [comment]
@teng-li Woo, it works after adding `--world-size`. Thanks for the useful tip!
