### ISSUE TITLE
SDPA memory efficient and flash attention kernels don't work with singleton dimensions

### ISSUE THREAD

**Issue by abdulfatir** [pytorch/pytorch#127523]
### 🐛 Describe the bug

```py
import torch
from torch.nn.functional import scaled_dot_product_attention

query = torch.tensor([[[[1, 2]]]], dtype=torch.float32)
query = query.transpose(-1, -2).to("cuda")
key = torch.tensor([[[[1]]]], dtype=torch.float32).to("cuda")
value = torch.tensor([[[[1]]]], dtype=torch.float32).to("cuda")

with torch.backends.cuda.sdp_kernel(
    enable_math=True, enable_flash=False, enable_mem_efficient=False
):
    scaled_dot_product_attention(query, key, value)  # Works fine

with torch.backends.cuda.sdp_kernel(
    enable_math=False, enable_flash=False, enable_mem_efficient=True
):
    scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
```

#### Stacktrace
```
/home/ansarnd/.conda/envs/sdpa-test/lib/python3.10/site-packages/torch/backends/cuda/__init__.py:342: FutureWarning: torch.backends.cuda.sdp_kernel() is deprecated. In the future, this context manager will be removed. Please see, torch.nn.attention.sdpa_kernel() for the new context manager, with updated signature.
  warnings.warn(
/home/ansarnd/repos/flan-ts/sdpa.py:17: UserWarning: Memory efficient kernel not used because: (Triggered internally at ../aten/src/ATen/native/transformers/cuda/sdp_utils.cpp:607.)
  scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
/home/ansarnd/repos/flan-ts/sdpa.py:17: UserWarning: Mem efficient attention requires last dimension of inputs to be divisible by 4. Got Query.size(-1): 1, Key.size(-1): 1, Value.size(-1): 1 instead. (Triggered internally at ../aten/src/ATen/native/transformers/cuda/sdp_utils.cpp:142.)
  scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
/home/ansarnd/repos/flan-ts/sdpa.py:17: UserWarning: Flash attention kernel not used because: (Triggered internally at ../aten/src/ATen/native/transformers/cuda/sdp_utils.cpp:609.)
  scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
/home/ansarnd/repos/flan-ts/sdpa.py:17: UserWarning: Flash attention has been runtime disabled. (Triggered internally at ../aten/src/ATen/native/transformers/sdp_utils_cpp.h:483.)
  scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
/home/ansarnd/repos/flan-ts/sdpa.py:17: UserWarning: CuDNN attention kernel not used because: (Triggered internally at ../aten/src/ATen/native/transformers/cuda/sdp_utils.cpp:611.)
  scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
/home/ansarnd/repos/flan-ts/sdpa.py:17: UserWarning: The CuDNN backend needs to be enabled by setting the enviornment variable`TORCH_CUDNN_SDPA_ENABLED=1` (Triggered internally at ../aten/src/ATen/native/transformers/cuda/sdp_utils.cpp:409.)
  scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
Traceback (most recent call last):
  File "/home/ansarnd/repos/flan-ts/sdpa.py", line 17, in <module>
    scaled_dot_product_attention(query, key, value)  # Fails, stacktrace below
RuntimeError: No available kernel. Aborting execution.
```

**Note**: Even `.contiguous()` does not work in this case. This issue also exists for the SDPA kernel.

### Versions

PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1033-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 525.85.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         2999.998
BogoMIPS:                        5999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.3.0
[pip3] triton==2.3.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by abdulfatir** [comment]
Related issue: https://github.com/pytorch/pytorch/issues/116333

**Comment by drisspg** [comment]
This issue is a little different, we dont currently do the last dim padding automatically, maybe we should.. however this should work for you


```Python
import torch
from torch.nn.functional import scaled_dot_product_attention
from torch.nn.attention import sdpa_kernel, SDPBackend


query = torch.tensor([[[[1, 2]]]], dtype=torch.float32)
query = query.transpose(-1, -2).to("cuda")
key = torch.tensor([[[[1]]]], dtype=torch.float32).to("cuda")
value = torch.tensor([[[[1]]]], dtype=torch.float32).to("cuda")


with sdpa_kernel(SDPBackend.MATH):
    out_unpadded = scaled_dot_product_attention(query, key, value)  # Works fine

q_padding_amount = 4 - query.size(-1)
kv_padding_amount = 4 - key.size(-1)
query_padded = torch.nn.functional.pad(query, (0, q_padding_amount))
key_padded = torch.nn.functional.pad(key, (0, kv_padding_amount))
value_padded = torch.nn.functional.pad(value, (0, kv_padding_amount))

with sdpa_kernel(SDPBackend.EFFICIENT_ATTENTION):
    out_padded = scaled_dot_product_attention(query_padded, key_padded, value_padded)  # Fails, stacktrace below

out_sliced = out_unpadded[..., : query.size(-1)]

torch.testing.assert_close(out_unpadded, out_sliced)
```

**Comment by abdulfatir** [comment]
Thanks @drisspg! 

Sorry, I may have mixed something up while reading the other issue. Here's the actual problem I am facing. It relates to tensors not having stride 1 in the last dimension which does not get fixed with `.contiguous()`.

```py
import torch

query = torch.ones(2, 16, 1, 64, device="cuda:0")
key = torch.ones(2, 16, 1, 64, device="cuda:0")
values = torch.ones(2, 16, 1, 64, device="cuda:0")
attn_mask = torch.ones(1, 1, 16, device="cuda:0")
attn_mask = attn_mask.permute([2, 0, 1]).unsqueeze(0).contiguous()

with torch.backends.cuda.sdp_kernel(
            enable_math=False, enable_flash=False, enable_mem_efficient=True
        ): # works when you set enable_math=True
    torch.nn.functional.scaled_dot_product_attention(
        query,
        key,
        values,
        attn_mask=attn_mask,
    )
```

I am facing this issue when adding SDPA support to T5 models in `transformers`: https://github.com/huggingface/transformers/pull/30375#issuecomment-2074706941

**Comment by abdulfatir** [comment]
@drisspg any update on this?

**Comment by abdulfatir** [comment]
@drisspg any thoughts on the issue above?

**Comment by drisspg** [comment]
A workaround:
``` Python
import torch
from torch.nn.attention import SDPBackend, sdpa_kernel

query = torch.ones(2, 16, 1, 64, device="cuda:0")
key = torch.ones(2, 16, 1, 64, device="cuda:0")
values = torch.ones(2, 16, 1, 64, device="cuda:0")
attn_mask = torch.ones(1, 1, 16, device="cuda:0")
attn_mask = attn_mask.permute([2, 0, 1]).unsqueeze(0)

if attn_mask.stride(-1) != 1:
    attn_mask = torch.empty_like(attn_mask, memory_format=torch.contiguous_format).copy_(attn_mask)
    
with sdpa_kernel(SDPBackend.EFFICIENT_ATTENTION) as context: # works when you set enable_math=True
    torch.nn.functional.scaled_dot_product_attention(
        query,
        key,
        values,
        attn_mask=attn_mask,
    )

```

The reason why we dont enable this by default is because this can cause an unexpected memory spike depending on the size of the attn mask, so in this case we came to the conclusion that it is better for users to do this explicitly

**Comment by abdulfatir** [comment]
Got it, thanks!

**Comment by pengzhangzhi** [comment]
> A workaround:
> 
> ```python
> import torch
> from torch.nn.attention import SDPBackend, sdpa_kernel
> 
> query = torch.ones(2, 16, 1, 64, device="cuda:0")
> key = torch.ones(2, 16, 1, 64, device="cuda:0")
> values = torch.ones(2, 16, 1, 64, device="cuda:0")
> attn_mask = torch.ones(1, 1, 16, device="cuda:0")
> attn_mask = attn_mask.permute([2, 0, 1]).unsqueeze(0)
> 
> if attn_mask.stride(-1) != 1:
>     attn_mask = torch.empty_like(attn_mask, memory_format=torch.contiguous_format).copy_(attn_mask)
>     
> with sdpa_kernel(SDPBackend.EFFICIENT_ATTENTION) as context: # works when you set enable_math=True
>     torch.nn.functional.scaled_dot_product_attention(
>         query,
>         key,
>         values,
>         attn_mask=attn_mask,
>     )
> ```
> 
> The reason why we dont enable this by default is because this can cause an unexpected memory spike depending on the size of the attn mask, so in this case we came to the conclusion that it is better for users to do this explicitly

I tested the solution, it works but not for flash attention?

```
import torch
from torch.nn.attention import SDPBackend, sdpa_kernel

query = torch.ones(2, 16, 1, 64, device="cuda:0")
key = torch.ones(2, 16, 1, 64, device="cuda:0")
values = torch.ones(2, 16, 1, 64, device="cuda:0")
attn_mask = torch.ones(1, 1, 16, device="cuda:0")
attn_mask = attn_mask.permute([2, 0, 1]).unsqueeze(0)
print(f'query.shape: {query.shape}')
print(f'key.shape: {key.shape}')
print(f'values.shape: {values.shape}')
print(f'attn_mask.shape: {attn_mask.shape}')
if attn_mask.stride(-1) != 1:
    attn_mask = torch.empty_like(attn_mask, memory_format=torch.contiguous_format).copy_(attn_mask)
    
with sdpa_kernel(SDPBackend.FLASH_ATTENTION) as context: # works when you set enable_math=True
    torch.nn.functional.scaled_dot_product_attention(
        query,
        key,
        values,
        attn_mask=attn_mask,
    )

```

the error:
```
 UserWarning: CuDNN attention has been runtime disabled. (Triggered internally at ../aten/src/ATen/native/transformers/cuda/sdp_utils.cpp:533.)
  torch.nn.functional.scaled_dot_product_attention(
Traceback (most recent call last):
  File "/home/mila/a/alexander.tong/esm-efficient/b.py", line 17, in <module>
    torch.nn.functional.scaled_dot_product_attention(
RuntimeError: No available kernel. Aborting execution.
```

**Comment by drisspg** [comment]
Flash attention does not support masking
