### ISSUE TITLE
error when installing. no module 'tools'.

### ISSUE THREAD

**Issue by jb110** [pytorch/pytorch#12759]
## Issue description

I have downloaded the files. I have changed the current directory to the folder. when I run python setup.py install it says there is no module named tools. 

## Code example

Traceback <most recent call last>:
  File "setup.py", line 143, in <module>
    from tools.setup_helpers.env import check_env_flag, check_negative_env_flag
ModuleNotFoundError: No module names 'tools'

**Comment by soumith** [comment]
Please use the Bug Report template and reopen the issue. We need to know a lot more about your environment (OS, python version etc.) that the Bug Report template will give us.
