### ISSUE TITLE
Autograd isn’t functioning when networks’s parameters are taken from other networks

### ISSUE THREAD

**Issue by JoyChopra1298** [pytorch/pytorch#12756]
I have 3 networks with same architecture - A, B & C
The weights of C are set as convex combination of weights of A & B as shown below

```
for a_param, b_param, c_param in zip(a.parameters(), b.parameters(),
                                               c.parameters()):
    c_param.data = weight * a_param + (1 - weight) * b_param
```
On doing forward pass through C and using backward as shown below, gradients for A & B aren’t being calculated.
```
y = c.forward(x)
optimiser.zero_grad()
y.backward()
optimiser.step()
```
Can anyone tell which step is blocking the gradient flow?

EDIT -
Seems like parameters() is the problem; directly accessing the _modules and _parameters allows gradient calculation for A & B
```
c._modules['linear_layers'][0]._parameters['weight'] = weight * a._modules['linear_layers'][0]._parameters['weight'] + (1-weight) * b._modules['linear_layers'][0]._parameters['weight']

```

**Comment by albanD** [comment]
Please do not post the same question in multiple places it creates a lot of noise for people trying to answer the questions.
For future readers, the corresponding forum post with the answer is [here](https://discuss.pytorch.org/t/autograd-isnt-functioning-when-networkss-parameters-are-taken-from-other-networks/27424).

**Comment by JoyChopra1298** [comment]
@albanD I dont think that's the correct solution

**Comment by albanD** [comment]
In [this](https://discuss.pytorch.org/t/autograd-isnt-functioning-when-networkss-parameters-are-taken-from-other-networks/27424/2) answer, it explains that the fact that you use `.data` when doing `c_param.data = xxx` means that you don't tract history and thus gradients won't flow back to the original parameters.

**Comment by JoyChopra1298** [comment]
I tried as c.data and that wasn't even updating the parameters of C.
Can you at least answer how to do what I want?

**Comment by albanD** [comment]
Let's continue this discussion on the forum.
