### ISSUE TITLE
[RFC] Load and register rendezvous backends dynamically as plugins at runtime

### ISSUE THREAD

**Issue by Kaivalya1997** [pytorch/pytorch#127519]
### 🚀 The feature, motivation and pitch

**OVERVIEW AND MOTIVATION FOR PROPOSED FEATURE**

Currently in torchrun rendezvous, there are only two rendezvous backends supported out of the box: `C10d` and `Etcd (--etcd and --etcd-v2)`.
We propose a feature that lets the users choose general purpose databases such as MongoDB, Redis or Postgres that are available with HA configured across various CSPs as rendezvous backends. This can be achieved by adding a feature in pytorch for dynamically loading the module extensions as out of tree plugins for the rendezvous backend from a filesystem path and registering them as handlers with rendezvous.

#### AUTHORING NEW PLUGIN
Any new plugin will be a python package exposing entry-points. For example, the structure of redis plugin is as follows:

```
plugin_root
|_ pyproject.toml
|_ src
   |_ redis
      |_ __init__.py
      |_ redis_store.py
      |_ redis_backend.py
```

The contents of the `pyproject.toml` should indicate that this is exposes a torchrun entry-point by mentioning the group name `torchrun.plugins`. The `pyproject.toml` for redis plugin would be as follows:

```
[project]
name = "redis"
version = "0.0.1"

[project.entry-points.'torchrun.plugins']
redis = 'redis'
```

The `src/redis/__init__.py` file would contain functions that return the plugin name and plugin handler. The contents of `__init__.py` for redis would be as follows:

```
def getPluginHandler():
    def _create_redis_handler(params: RendezvousParameters):
        from redis_rendezvous_backend import create_backend
        backend, store = create_backend(params)
        return create_handler(store, backend, params)
    return _create_redis_handler
```

The files `redis_store` and `redis_backend` contain the implementation of [Store](https://github.com/pytorch/pytorch/blob/41189b0da4f793d506c3964d70ea2fe16f06daf6/torch/_C/_distributed_c10d.pyi#L171) and [RendezvousBackend](https://github.com/pytorch/pytorch/blob/e782918b8eeffc465acff40f0c55c8d80bc20ce2/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py#L61) respectively.

#### USER EXPERIENCE
Before using the plugin for the first time, the user has to install the plugin packages. For example, the published packages can be installed using `pip3 install <plugin-name>` and the plugin is in local file systemcan be installed using `pip3 install -e <plugin-location>`.

Once installed, the new backend can be used in torchrun as follows:

```
torchrun --rdzv-backend=redis --rdzv-endpoint=redis-container:6379 --nnodes=3 --nproc-per-node=1 --max-restarts=3 --rdzv-id=1 test.py
```

#### PROPOSED CHANGES AND IMPLEMENTATION APPROACH

We have [_register_default_handlers()](https://github.com/pytorch/pytorch/blob/276b5238ef4f371a718243c0515c8dd2a11957b9/torch/distributed/elastic/rendezvous/registry.py#L46) that registers the in-tree rendezvous handlers static, etcd, etcdv2 and c10d. 

In line with `_register_default_handlers()`, we propose a new function `_register_plugin_handlers()` that would read the entry-points and registers the handlers. The rough implementation of `_register_plugin_handlers()` would be as follows:

```
def _register_plugin_handlers() -> None:
    discovered_plugins = entry_points(group='torchrun.plugins')    

    for plugin in discovered_plugins:
        mod = discovered_plugins[plugin.name].load()
        handler = mod.getPluginHandler()
        handler_registry.register(plugin.name,handler)

```

The proposed function `register_plugin_handlers()` would be called from `torch/distributed/elastic/rendezvous/__init__.py`.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

**Comment by kwen2501** [comment]
The overall proposal looks good to me. I will let @kurman @d4l3k comment on the feasibility and/or detailed planning (in particular, what API definition would work best for torchrun and the plugins).

Minor comment re the UX:

The "plugin dir" concept seems to imply that the users may have multiple plugins, such as `plugin_dir/redis`, `plugin_dir/mongodb`, etc. In reality, would a single user have multiple plugins? If the user has only one plugin, would the UI below look a little more straightforward:
```
torchrun --rdzv-backend=/path/to/plugin_name.py ...
```
Then we can use importlib to dynamically load the module from the source file, e.g.: https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly

**Comment by d4l3k** [comment]
I'm not a huge fan of the `PLUGINS_DIRECTORY` environment variable. Can we instead use the existing python entrypoints mechanism that's used by torchx, fsspec, etc?

**Comment by sathyanarays** [comment]
@d4l3k , could you please provide examples from the code base that use the entrypoints so that we can adapt them?

**Comment by sathyanarays** [comment]
@kwen2501 @d4l3k We have modified the proposal to accommodate your suggestions. Please let us know thoughts.

**Comment by d4l3k** [comment]
LGTM :)

On the format I would probably prefer using the existing `handler` terminology instead of `plugins`. We can also specify the function directly from entrypoints rather than the module

I'm thinking something like:

```
[project.entry-points.'torchrun.handlers']
redis = 'my_redis:create_redis_handler'
```

PR is welcome

**Comment by sathyanarays** [comment]
We have raised the PR for the out-of-tree handler loading. We have a handler implemented for Redis. What would be the right place to contribute the out-of-tree handler implementations? Can we add the redis handler as part of this repo?

cc: @d4l3k @eqy
