### ISSUE TITLE
pytorch source code folder doesn't contain submodule of cereal.

### ISSUE THREAD

**Issue by s0nghuiming** [pytorch/pytorch#12752]
## 🐛 Bug
@ current master HEAD: commit dc07102b17915f21170fae9a9d52c6f2d59726ca

I found the source code cloned from github/pytorch/pytorch doesn't contain submodule of cereal.

From .gitmodule file the submodule cereal can be found its definition.
...
[submodule "third_party/cereal"]
	path = third_party/cereal
	url = https://github.com/USCiLab/cereal

But in source folder I cloned with recursive option, there is no cereal.

## To Reproduce

1. git clone --recursive https://github.com/pytorch/pytorch
2. cd pytorch; git submodule | grep cereal
3. cat .gitmodule | grep cereal

## Expected behavior

Cereal can be found both at step 2 and step 3.

### 
commit dc07102b17915f21170fae9a9d52c6f2d59726ca
Author: Yinghai Lu <yinghai@fb.com>
Date:   Tue Oct 16 17:23:20 2018 -0700

    Check dim size preventively when doing shape inference for BatchMatMul (#12691)

    Summary:
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/12691

    We check input(0) but not input(1) in BatchMatMul. This may result in a protobuf exception which won't be caught by up

    Reviewed By: bddppq, houseroad, BIT-silence

    Differential Revision: D10391130

    fbshipit-source-id: daf8dcd8fcf9629a0626edad660dff54dd9aeae3

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/12666
