### ISSUE TITLE
cusparseMatDescr_t *" is incompa tible with parameter of type "cusparseMatDescr_t"

### ISSUE THREAD

**Issue by jiangzhengkai** [pytorch/pytorch#12757]
Hi, i am build pytorch from source, and meet this bug.
The detail message is as following:
![image](https://user-images.githubusercontent.com/19780166/47074181-73eb6200-d22c-11e8-859c-5765201fd6c7.png)
![image](https://user-images.githubusercontent.com/19780166/47074200-7fd72400-d22c-11e8-9383-214588d7fea4.png)
I don't know how to fix.
I use cuda-9.2, cudnn7, TITAN Vgpu

**Comment by zou3519** [comment]
Please use our bug report template so we can get more information about your problem
