### ISSUE TITLE
JIT: elementwise 'and' is treated as an op on booleans

### ISSUE THREAD

**Issue by pfrendl** [pytorch/pytorch#12769]
## 🐛 Bug

The JIT script compiler does not support the `&` operator, so `a & b` fails. 

In torch/jit/frontend.py, the following definition exists:
 boolop_map = {
        ast.And: 'and',
        ast.Or: 'or',
    }

I tried `a and b`, but this makes the compiler fail, maybe because it can't differentiate tensors from boolean variables at compile time?

## To Reproduce

Minimal failing example with error messages attached:

```
import torch


'''
torch.jit.frontend.NotSupportedError: unsupported binary operator: BitAnd
@torch.jit.script
def fun1(a, b):
	return a & b# RuntimeError: expected a boolean expression for condition but found Tensor, to use a tensor in a boolean expression, explicitly cast it with `bool()`
         ~~~ <--- HERE
'''
@torch.jit.script
def fun1(a, b):
	return a & b


'''
RuntimeError: 
expected a boolean expression for condition but found Tensor, to use a tensor in a boolean expression, explicitly cast it with `bool()`:
@torch.jit.script
def fun2(a, b):
	return a and b
        ~ <--- HERE
'''
@torch.jit.script
def fun2(a, b):
	return a and b


if __name__ == '__main__':
	a = torch.ByteTensor([0])
	b = torch.ByteTensor([1])
	fun1(a, b)
	fun2(a, b)
```

## Expected behavior

I should be able to apply the bitwise and binary operation to two ByteTensors (in case their shapes are compatible).

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.0.dev20181015
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip3
 - Python version: 3.5.2
 - CUDA/cuDNN version: 9.2/7104
 - GPU models and configuration: GTX 1080 Ti x 2

**Comment by eellison** [comment]
As a temporary work-around, you can use:

@torch.jit.script
def fun2(a, b):
	return a.__and__(b)

**Comment by zdevito** [comment]
This has been fixed
