### ISSUE TITLE
Strange clamp assert error when building on Fedora 40/gcc 14 in IndexKernel.hip

### ISSUE THREAD

**Issue by lamikr** [pytorch/pytorch#127666]
### 🐛 Describe the bug

I am building the pytorch with same steps than on Fedora 39 and Ubuntu 23.10 on Fedora 40 for AMD.
In other systems it works ok, but on Fedora 40 I get of assert error.

The code causing problem is following from IndexKernel.cu/IndexKernel.hip

```
void index_put_kernel_quantized_cuda(TensorIterator& iter, const IntArrayRef index_size, const IntArrayRef index_stride, const bool accumulate, const double scale, const int zero_point) {
  TORCH_CHECK(!accumulate, "index_put does not support accumulate=true");
  AT_DISPATCH_QINT_AND_SUB_BYTE_TYPES(iter.dtype(), "index_put", [&] {
    constexpr int64_t qmin = std::numeric_limits<typename scalar_t::underlying>::min();
    constexpr int64_t qmax = std::numeric_limits<typename scalar_t::underlying>::max();
    const float inv_scale = 1.0f / static_cast<float>(scale);

    gpu_index_kernel(iter, index_size, index_stride, [inv_scale, zero_point, qmin, qmax]C10_DEVICE(char* const out_data, const char* const in_data, const int64_t offset) {
      int64_t qvalue = static_cast<int64_t>(zero_point + nearbyintf(*(float*)in_data * inv_scale));
      qvalue = std::clamp(qvalue, qmin, qmax);
      *(scalar_t*)(out_data + offset) = static_cast<scalar_t>(qvalue);
    });
  });
}

```

I get away from the error if I change that to following that uses min and max, but I think I should somehow also handle the nan and inf value checks? And of course it would be nice to understood the root cause. Any idea how to check the qmin, qmax and qvalue values at build time to debug further?

```
void index_put_kernel_quantized_cuda(TensorIterator& iter, const IntArrayRef index_size, const IntArrayRef index_stride, const bool accumulate, const double scale, const int zero_point) {
  TORCH_CHECK(!accumulate, "index_put does not support accumulate=true");
  AT_DISPATCH_QINT_AND_SUB_BYTE_TYPES(iter.dtype(), "index_put", [&] {
    constexpr int64_t qmin = std::numeric_limits<typename scalar_t::underlying>::min();
    constexpr int64_t qmax = std::numeric_limits<typename scalar_t::underlying>::max();
    const float inv_scale = 1.0f / static_cast<float>(scale);

    gpu_index_kernel(iter, index_size, index_stride, [inv_scale, zero_point, qmin, qmax]C10_DEVICE(char* const out_data, const char* const in_data, const int64_t offset) {
      int64_t qvalue = static_cast<int64_t>(zero_point + nearbyintf(*(float*)in_data * inv_scale));
      int64_t new_max = std::max<int64_t>(qmin, qvalue);
      qvalue = std::min<int64_t>(qmax, new_max);
      //qvalue = std::clamp(qvalue, qmin, qmax);
      *(scalar_t*)(out_data + offset) = static_cast<scalar_t>(qvalue);
    });
  });
}



```

### Error logs

In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/algorithm:61:
/usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_algo.h:3625:7: error: reference to __host__ function '__glibcxx_assert_fail' in __host__ __device__ function
 3625 |       __glibcxx_assert(!(__hi < __lo));
      |       ^
/usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/x86_64-redhat-linux/bits/c++config.h:2453:7: note: expanded from macro '__glibcxx_assert'
 2453 |         std::__glibcxx_assert_fail();                                   \
      |              ^
pytorch/aten/src/ATen/native/hip/IndexKernel.hip:254:21: note: called by 'operator()'
  254 |       qvalue = std::clamp(qvalue, qmin, qmax);
      |                     ^
pytorch/aten/src/ATen/native/hip/IndexKernel.hip:101:5: note: called by 'operator()'
  101 |     f(out_data, in_data, offset);
      |     ^
pytorch/aten/src/ATen/native/hip/IndexKernel.hip:36:7: note: called by 'index_elementwise_kernel<128, 4, (lambda at pytorch/aten/src/ATen/native/hip/IndexKernel.hip:85:62)>'
   36 |       f(idx);
      |       ^
/usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/x86_64-redhat-linux/bits/c++config.h:2446:3: note: '__glibcxx_assert_fail' declared here
 2446 |   __glibcxx_assert_fail()
      |   ^
1 warning and 5 errors generated when compiling for gfx1035.
CMake Error at torch_hip_generated_IndexKernel.hip.o.cmake:200 (message):
  Error generating file
pytorch/build/caffe2/CMakeFiles/torch_hip.d

### Versions

pytorch 2.3.0
fedora 40
hipcc 6.1.1

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by gel-crabs** [comment]
This also occurs on Arch with GCC 14.
