### ISSUE TITLE
RFC: Distinguish between const T* and T* in C++ API for pointer access

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#12765]
This is a request for comment. It does **not** indicate that we plan to do this; it's just to get the temperature of the community on this issue.

## 🚀 Feature

Presently, in the C++ API, we have the following methods for accessing data pointers on tensors:

```
template <typename T> T* data();
void* data_ptr();
```

These methods always return a non-const pointer. The proposal is to make it possible to get a const pointer from Tensor. There are two variants to this proposal:

1. Add a `const_data()` method for the `const T*` variation.
2. Make `data()` return a `const T*`, and add `mutable_data` which gives the non-const version

## Discussion

Why am I bringing this up?

- I'm trying to line up the Caffe2 tensor API with the PyTorch API, and Caffe2's data() method historical returned a const pointer. So we have to make a decision, either to make Caffe2's non-const, or to make PyTorch's const.
- It is more const-correct, c.f. https://isocpp.org/wiki/faq/const-correctness

Variation (2) is BC-breaking and probably will break any code that uses `data()` directly to mutate user data, both internal and external code.

CC @goldsborough @dzhulgakov

**Comment by colesbury** [comment]
This adds more API surface without any improvement in functionality. `T*` can always be used in a place that accepts `const T*` and the const-ness of a Tensor smart pointer doesn't imply immutability.

For comparison STL smart pointers only define `T* get()` (not a `const T*` variant)

https://en.cppreference.com/w/cpp/memory/unique_ptr/get
https://en.cppreference.com/w/cpp/memory/shared_ptr/get

**Comment by cbreak-black** [comment]
Typically, C++ containers that represent a value (as opposed to representing a pointer to a value such as unique_ptr) have transitive const correctness. They provide a `T const * data() const` and a `T * data()` overload. The only reason to explicitly add a const_data() overload is to make it easier to force constness (but that doesn't add much, casting can easily be used to do that as well). The only reason to not add a non-const data() but instead a mutable_data would be to encourage explicitness about mutability.

https://en.cppreference.com/w/cpp/container/vector/data

**Comment by ezyang** [comment]
Resolution is that we won't do this.
