### ISSUE TITLE
Add line number to ` _warn_capture_scalar_outputs():`

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#127667]
### 🚀 The feature, motivation and pitch

Right now we just see 
<img width="937" alt="image" src="https://github.com/pytorch/pytorch/assets/6355099/0b5d88fd-6497-4570-9856-9d138183ab8e">
so this is pretty hard to fix.

cc: @anijain2305 

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by anijain2305** [comment]
Repro instructions

~~~
import torch

def fn(x, y):
    return y * x.item()

x = torch.randn(1)
y = torch.randn(10)

opt_fn = torch.compile(fn, backend="eager")
opt_fn(x, y)

~~~

Logging
~~~
W0730 15:45:56.100000 1298400 torch/_dynamo/variables/tensor.py:751] [0/0] Graph break from `Tensor.item()`, consider setting:
W0730 15:45:56.100000 1298400 torch/_dynamo/variables/tensor.py:751] [0/0]     torch._dynamo.config.capture_scalar_outputs = True
W0730 15:45:56.100000 1298400 torch/_dynamo/variables/tensor.py:751] [0/0] or:
W0730 15:45:56.100000 1298400 torch/_dynamo/variables/tensor.py:751] [0/0]     env TORCHDYNAMO_CAPTURE_SCALAR_OUTPUTS=1
W0730 15:45:56.100000 1298400 torch/_dynamo/variables/tensor.py:751] [0/0] to include these operations in the captured graph.
W0730 15:45:56.100000 1298400 torch/_dynamo/variables/tensor.py:751] [0/0]
~~~


The ask here is to append the source code information, basically pointing to line `return y * x.item()`. This will help PyTorch user to change the code if applicable.
