### ISSUE TITLE
UNSTABLE inductor / cuda12.4-py3.10-gcc9-sm86 / test (dynamic_inductor_timm)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#127680]
Same as https://github.com/pytorch/pytorch/issues/127438, but on CUDA 12.4

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by nWEIdia** [comment]
Would https://github.com/pytorch/pytorch/pull/127672 bring it back to stable? Is there a flaky state between unstable and stable? If so, I believe this workloads fall to flaky if this PR can be merged.

**Comment by Skylion007** [comment]
@nWEIdia See here how thresholds can be adjusted: https://github.com/pytorch/pytorch/pull/127664

**Comment by huydhn** [comment]
The job doesn't look unstable anymore
