### ISSUE TITLE
torch.max wrong output

### ISSUE THREAD

**Issue by E1eMenta** [pytorch/pytorch#12779]
## To Reproduce

```
is_bigger = torch.Tensor([[ 1, 1, 1, 1, 1, 1, 1, 1, 1], [ 0, 0, 1, 1, 1, 1, 1, 1, 1], [ 0, 0, 0, 0, 1, 1, 1, 1, 1], [ 0, 0, 0, 0, 0, 0, 1, 1, 1], [ 0, 0, 0, 0, 0, 0, 1, 1, 1]])
is_bigger = is_bigger.cuda()
_, indices = torch.max(is_bigger, dim=1)
indices
```

Output:
tensor([0, 8, 8, 8, 8], device='cuda:0')

 - PyTorch Version: '0.4.1'
 - OS: ubuntu 16.04
 - How you installed PyTorch: pip install torch
 - Python version: 3.6.5
 - CUDA/cuDNN version: 9.0/7
 - GPU models and configuration: 1080ti

**Comment by albanD** [comment]
Hi,

That is a correct output no? It returns the index of a maximum value for each row.

**Comment by E1eMenta** [comment]
> Hi,
> 
> That is a correct output no? It returns the index of a maximum value for each row.

Yes, but output without "is_bigger = is_bigger.cuda()" is tensor([0, 2, 4, 6, 6])

**Comment by albanD** [comment]
Both are valid argmax values. I don't think there are any guaranty on which index is choosen when multiple values are the same.

**Comment by soumith** [comment]
as alban said, both are "correct answer".

**Comment by E1eMenta** [comment]
Ok, thanks.
But the difference in results on cpu and gpu can cause a lot of difficulties. Especially in such a basic function.
