### ISSUE TITLE
is there a way to change a list of Variable(FloatTensor) to a giant new Variable(FloatTensor)?

### ISSUE THREAD

**Issue by andyang** [pytorch/pytorch#1277]
Here is the code and error message:
```python
a=Variable(torch.FloatTensor([1]))
b=a
c=[a,b]
Variable(c)
```
Error:RuntimeError: Variable data has to be a tensor, but got list

```python
c=[a.data,b.data]
torch.FloatTensor(c)
```
Error:TypeError: 'FloatTensor' object does not support indexing

**Comment by apaszke** [comment]
You're looking for `torch.cat` or `torch.stack`. 

Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
