### ISSUE TITLE
Embedding max_norm option slow with CUDA

### ISSUE THREAD

**Issue by TimDettmers** [pytorch/pytorch#1278]
If I use `torch.nn.Embedding` with `max_norm=1` and `norm_type=2` then embedding word indices is slow, consuming 95% of computation in my example (FB15k). If I renormalize embedding matrices manually after each mini-batch update via `self.emb_e.weight.data.renorm_(2, 0, 1)` then the renormalization is 20 times faster.

I am using pytorch 0.1.10. I understand that changes have been made in 0.1.11 but from the change log I only see changes that affected the correctness of computation and not computation speed.

**Comment by cgosse** [comment]
I just ran into this using a build of the latest master

**Comment by soumith** [comment]
I'm going to have someone take this one. @cgosse @TimDettmers what Embedding sizes were you guys using?

**Comment by soumith** [comment]
Full parameters to the Embedding constructor would be helpful.

**Comment by TimDettmers** [comment]
I am not sure anymore. I prototyped a model, but quickly abandoned it and I cannot find the code anymore. I think I used:
```
  torch.nn.Embedding(num_entities, 128, padding_idx=0, max_norm=1, norm_type=2)
  torch.nn.Embedding(num_relations, 128, padding_idx=0, max_norm=1, norm_type=2)
```
Where `num_entities` is around 15k to 40k and `num_relations` between 20 and 500.

**Comment by cgosse** [comment]
I too removed that code since it wasn't working for me, but embedding dimensionality was 32

**Comment by cgosse** [comment]
perhaps related, is there any way to specify the datatype of the embeddings e.g. half floats?

**Comment by soumith** [comment]
master now has a much faster implementation of this, thanks to @squidgetx !
