### ISSUE TITLE
Inductor lowering ignores auto_functionalized custom op

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#127821]
(reported by @yf225)

### 🐛 Describe the bug

During the Inductor lowering process, downstream op X is not recognizing that its input tensor was mutated by an auto_functionalize'd op, and instead X just uses the pre-mutation version of the input tensor.

Repro:
```python
import torch
from torch._decomp import register_decomposition

lib = torch.library.Library("fsdp_test", "DEF")

lib.define("chunk_cat_(Tensor(a!) ret, Tensor[] tensors, int dim, int num_chunks) -> ()")

@torch.library.impl(lib, "chunk_cat_", "Meta")
def chunk_cat_(ret, tensors, dim, num_chunks):
    torch._chunk_cat(
        tensors, dim, num_chunks, out=ret
    )

@torch.library.impl(lib, "chunk_cat_", "CUDA")
def chunk_cat_(ret, tensors, dim, num_chunks):
    torch._chunk_cat(tensors, dim, num_chunks, out=ret)


def f(x, y, z):
    full_default_3: "f32[2, 524544]" = torch.ops.aten.full.default([2, 524544], 1.0, dtype = torch.float32, layout = torch.strided, device = "cuda", pin_memory = False)
    chunk_cat_default_1 = torch.ops.fsdp_test.chunk_cat_.default(full_default_3, [x, y, z], 0, 2)
    mul_out = torch.mul(full_default_3, full_default_3)
    sum_out = mul_out.sum()
    return sum_out


if __name__ == "__main__":
    x = torch.randn([1024, 512], device="cuda")
    y = torch.randn([512], device="cuda")
    z = torch.randn([1024, 512], device="cuda")
    eager_out = f(x, y, z)

    compiled_aot_eager_f = torch.compile(f, backend="aot_eager", fullgraph=True)
    compiled_aot_eager_out = compiled_aot_eager_f(x, y, z)
    assert torch.allclose(eager_out, compiled_aot_eager_out), f"eager_out: {eager_out}, compiled_aot_eager_out: {compiled_aot_eager_out}"   # passes

    compiled_inductor_f = torch.compile(f, backend="inductor", fullgraph=True)
    compiled_inductor_out = compiled_inductor_f(x, y, z)
    assert torch.allclose(eager_out, compiled_inductor_out), f"eager_out: {eager_out}, compiled_inductor_out: {compiled_inductor_out}"  # fails
```

Inductor generated code is:
```python
def call(args):
    arg0_1, arg1_1, arg2_1 = args
    args.clear()
    assert_size_stride(arg0_1, (1024, 512), (512, 1))
    assert_size_stride(arg1_1, (512, ), (1, ))
    assert_size_stride(arg2_1, (1024, 512), (512, 1))
    with torch.cuda._DeviceGuard(0):
        torch.cuda.set_device(0)
        buf0 = empty_strided_cuda((2, 524544), (524544, 1), torch.float32)
        # Source Nodes: [full_default_3], Original ATen: [aten.full]
        stream0 = get_raw_stream(0)
        triton_poi_fused_full_0.run(buf0, 1049088, grid=grid(1049088), stream=stream0)
        # Source Nodes: [full_default_3], Original ATen: [aten.full]
        buf1 = torch.ops.fsdp_test.chunk_cat_.default(buf0, [arg0_1, arg1_1, arg2_1], 0, 2)
        del arg0_1
        del arg1_1
        del arg2_1
        buf3 = empty_strided_cuda((129, ), (1, ), torch.float32)
        # Source Nodes: [full_default_3, mul_out, sum_out], Original ATen: [aten.full, aten.mul, aten.sum]
        triton_red_fused_full_mul_sum_1.run(buf3, 129, 8133, grid=grid(129), stream=stream0)
        del buf0
        buf4 = empty_strided_cuda((), (), torch.float32)
        # Source Nodes: [full_default_3, mul_out, sum_out], Original ATen: [aten.full, aten.mul, aten.sum]
        triton_per_fused_full_mul_sum_2.run(buf3, buf4, 1, 129, grid=grid(1), stream=stream0)
        del buf3
    return (buf4, )
```
Notice neither buf0 or buf1 (mutated tensor by chunk_cat_) is used downstream, which deviates from eager semantics.

Interestingly, @bdhirsh found that if we comment out the `decompose_auto_functionalized()` pass in https://github.com/pytorch/pytorch/blob/05fa05cbae55bcae330c01d5e26cf86d05e307e6/torch/_inductor/fx_passes/post_grad.py#L125, then this passes. @zou3519 commented that this can work, but auto_functionalized will clone all the mutated inputs, so it is not performant. Richard commented that Inductor is supposed to re-inplace it and remove the unnecessary clones, and that's what decompose_auto_functionalized is for.

@zou3519 confirmed that it's indeed a recent regression.

### Versions

nightly

cc @ezyang @gchanan @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by zou3519** [comment]
cc @Chillee -- did we do any work recently to how inductor handles mutations?

**Comment by Chillee** [comment]
@zou3519 We did, although it should be semantics preserving. https://github.com/pytorch/pytorch/pull/127151

It's possible I got something wrong though...

**Comment by zou3519** [comment]
let me test before that commit

**Comment by zou3519** [comment]
Bisected to https://github.com/pytorch/pytorch/pull/126986

**Comment by zou3519** [comment]
I think I know what is happening, but I don't know how to fix it.

We have a custom op that mutates one of its inputs (say, "x") and has needs_fixed_stride_order=True. If inductor cannot prove that the strides of `x` match the desired stride order, then it creates a new buffer "buf0" which is a clone of `x`. Then, it runs the in-place operation on `buf0`, and therefore `x` never gets mutated.

Some thoughts:
- if inductor cannot prove the strides match, then yes it should clone the tensor and then copy_ the result back to the original Tensor.
- inductor should be able to prove that the strides match in this particular case. `x` is some Pointwise IR Node (that was created via an aten.full_like), but there is no stride order on the Pointwise IR Node. How does inductor ultimately determine strides for this?

cc @eellison, @Chillee if you folks have thoughts

**Comment by zou3519** [comment]
Another thought: the custom op is always the only user of the input it mutates (the re-inplacing pass guarantees this; if it is not the only input then it is not safe to re-inplace). In order to produce a Tensor of the correct strides, we could codegen a permute call instead of create a new Tensor

**Comment by eellison** [comment]
> if inductor cannot prove the strides match, then yes it should clone the tensor. Then, it should copy_ the result back to the original Tensor (it doesn't do this today)
inductor should be able to prove that the strides match in this particular case. x is some Pointwise IR Node (that was created via an aten.full_like), but there is no stride order on the Pointwise IR Node. How does inductor ultimately determine strides for this?

Yea I agree with both of these.

**Comment by zou3519** [comment]
I reverted the PR but will need to land it eventually, going to close this for now since problem was mitigated.

**Comment by ezyang** [comment]
It seems Inductor should try harder to get things in the right stride lol
