### ISSUE TITLE
Missing build for 2.3.0 macosx x86_64

### ISSUE THREAD

**Issue by pbudzyns** [pytorch/pytorch#127870]
### 🐛 Describe the bug

While running on Mac with x86_64 CPU 

```
pip install torch==2.3.0
ERROR: Could not find a version that satisfies the requirement torch==2.3.0 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.3.0
```

Also no build seems to exist in the index https://download.pytorch.org/whl/torch/

### Versions

n / a

**Comment by albanD** [comment]
Hey!
I'm afraid this is expected behavior. See https://dev-discuss.pytorch.org/t/pytorch-macos-x86-builds-deprecation-starting-january-2024/1690 for discussion on macosx x86 deprecation process.

**Comment by pbudzyns** [comment]
Hey, thanks for your answer. That's making pytorch quite exclusive. Would be great to have this information on the installation page.
