### ISSUE TITLE
Document the torch.jit.frontend.get_default_args function

### ISSUE THREAD

**Issue by svekars** [pytorch/pytorch#127896]
Document the `torch.jit.frontend.get_default_args` function located in [https://github.com/pytorch/pytorch/blob/main/torch/jit/frontend.py#L595](https://github.com/pytorch/pytorch/blob/main/torch/jit/frontend.py#L595).
Follow the [Docstring Guidelines](https://github.com/pytorch/pytorch/wiki/Docstring-Guidelines).

cc @brycebortree

**Comment by malfet** [comment]
Just want to highlight, that we are not publishing docs for `torch.jit.frontend` anywhere
