### ISSUE TITLE
Document the torch.serialization.default_restore_location function

### ISSUE THREAD

**Issue by svekars** [pytorch/pytorch#127887]
Document the `torch.serialization.default_restore_location` function located in [https://github.com/pytorch/pytorch/blob/main/torch/serialization.py#L430](https://github.com/pytorch/pytorch/blob/main/torch/serialization.py#L430).
Follow the [Docstring Guidelines](https://github.com/pytorch/pytorch/wiki/Docstring-Guidelines).

cc @brycebortree

**Comment by afrittoli** [comment]
Permalink to the function to document: https://github.com/pytorch/pytorch/blob/c97e3ebb96d7457075b019b94411e8c2d058e68b/torch/serialization.py#L392
