### ISSUE TITLE
xpu: aten::nll_loss2d_* not implemented for XPU backend affecting Huggingface examples

### ISSUE THREAD

**Issue by dvrogozh** [pytorch/pytorch#127937]
These `nil_loss2d_*` ops are not currently implemented for XPU backend and are not marked for "explicit" CPU fallback. This means that running model with any of these ops will fail at runtime by default (with not implemented error) and will require to set `PYTORCH_DEBUG_XPU_FALLBACK=1`.

- [ ] `aten::nll_loss2d_backward`, https://github.com/intel/torch-xpu-ops/pull/530
- [ ] `aten::nll_loss2d_forward`, https://github.com/intel/torch-xpu-ops/pull/530

This issue affects XPU enabling for Huggingface - https://github.com/huggingface/transformers/issues/31237#issuecomment-2148067845. See table in this comment for the list of affected examples and models.

Reported to torch-xpu-ops: https://github.com/intel/torch-xpu-ops/issues/372

CC: @gujinghui @EikanWang @fengyuan14 @guangyey @jgong5

cc @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by EikanWang** [comment]
Regarding these operations, we will implement them to catch up with PT2.5.

**Comment by dvrogozh** [comment]
Done with #131015 merged.
