### ISSUE TITLE
xpu: support torch.xpu.<memory> ops (memory_allocated, max_memory_allocated, etc.)

### ISSUE THREAD

**Issue by dvrogozh** [pytorch/pytorch#127929]
The following `torch.xpu` ops are missing (were available for IPEX):

- [ ] `torch.xpu.memory_allocated()`
- [ ] `torch.xpu.max_memory_allocated()`
- [ ] `torch.xpu.reset_peak_memory_stats()`

These operations are used for example on Huggingface side:
* https://github.com/huggingface/transformers/blob/fd3238b4b0e1af4fae4a293cbfd1251ead40cd29/src/transformers/trainer_utils.py#L55
* https://github.com/huggingface/transformers/blob/fd3238b4b0e1af4fae4a293cbfd1251ead40cd29/src/transformers/trainer_utils.py#L60
* https://github.com/huggingface/transformers/blob/fd3238b4b0e1af4fae4a293cbfd1251ead40cd29/src/transformers/trainer_utils.py#L539

This issue affects XPU enabling for Huggingface - https://github.com/huggingface/transformers/issues/31237#issuecomment-2148067845.

CC: @gujinghui @EikanWang @fengyuan14 @guangyey @jgong5

cc @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by EikanWang** [comment]
@guangyey , Let's prioritize these runtime APIs and catch up with PT2.5

**Comment by gujinghui** [comment]
Some of them are depending on SYCL support. @guangyey  Am I right?

**Comment by EikanWang** [comment]
> Some of them are depending on SYCL support. @guangyey Am I right?

If yes, have we submitted requirements to compiler team?

**Comment by guangyey** [comment]
> Some of them are depending on SYCL support. @guangyey Am I right?

These three APIs don't depend on SYCL. They only collect the statistics of memory allocated by PyTorch.

**Comment by EikanWang** [comment]
Sounds good. @guangyey , so please prioritize these interfaces' implementation as they are used by HF.
