### ISSUE TITLE
xpu: set of unimplemented ops affect huggingface examples performance

### ISSUE THREAD

**Issue by dvrogozh** [pytorch/pytorch#127941]
This issue affects XPU enabling for Huggingface - https://github.com/huggingface/transformers/issues/31237#issuecomment-2148067845. See table in this comment for the list of affected examples and models.

The following ops are marked by XPU backend for CPU fallback (`PYTORCH_DEBUG_XPU_FALLBACK=1` is not needed) and affect performance:

- [x] `aten::_cdist_forward`, https://github.com/intel/torch-xpu-ops/pull/382
- [x] `aten::addcdiv.out`, https://github.com/intel/torch-xpu-ops/pull/486
- [x] `aten::addcmul.out`, https://github.com/intel/torch-xpu-ops/pull/418
- [x] `aten::all.all_out`, https://github.com/intel/torch-xpu-ops/pull/368
- [x] `aten::floor.out`, https://github.com/intel/torch-xpu-ops/pull/533
- [x] `aten::grid_sampler_2d_backward`, https://github.com/intel/torch-xpu-ops/pull/396
- [x] `aten::lerp.Scalar_out`, https://github.com/intel/torch-xpu-ops/pull/449
- [x] `aten::linalg_vector_norm.out`, https://github.com/intel/torch-xpu-ops/pull/460
- [ ] `aten::linspace.out`, https://github.com/intel/torch-xpu-ops/pull/850
- [x] `aten::native_batch_norm`, https://github.com/intel/torch-xpu-ops/pull/356
- [x] `aten::native_group_norm_backward`, https://github.com/intel/torch-xpu-ops/pull/393
- [x] `aten::max_pool2d_with_indices.out`, https://github.com/intel/torch-xpu-ops/pull/472
- [x] `aten::prod.int_out`, https://github.com/intel/torch-xpu-ops/pull/615
- [x] `aten::roll`, https://github.com/intel/torch-xpu-ops/pull/437
- [x] `aten::sgn.out`, https://github.com/intel/torch-xpu-ops/pull/212
- [x] `aten::sigmoid.out`, https://github.com/intel/torch-xpu-ops/pull/218
- [x] `aten::sigmoid_backward.grad_input`, https://github.com/intel/torch-xpu-ops/pull/218
- [x] `aten::silu.out`, https://github.com/intel/torch-xpu-ops/pull/389
- [x] `aten::topk.values`, https://github.com/intel/torch-xpu-ops/pull/547
- [x] `aten::upsample_bilinear2d.out`, https://github.com/intel/torch-xpu-ops/pull/422
- [x] `aten::upsample_bilinear2d_backward.grad_input`, https://github.com/intel/torch-xpu-ops/pull/422
- [x] `aten::upsample_nearest2d.out`, https://github.com/intel/torch-xpu-ops/pull/373

**Note:** there is a lag between merging PRs to torch-xpu-ops and code availability for PyTorch especially now with preparation to 2.4 when torch-xpu-ops is tracked for 2.4 branch instead of main. Thus, to make sure to try out latest implemented ops you might need to switch to torch-xpu-ops main manually.

CC: @gujinghui @EikanWang @fengyuan14 @guangyey @jgong5

cc @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by EikanWang** [comment]
Regarding these operations, we will implement them to catch up with PT2.5

**Comment by dvrogozh** [comment]
After merging of https://github.com/pytorch/pytorch/pull/129353, the following ops remain not implemented/not available in pytorch:

- [ ] `aten::_cdist_forward`, https://github.com/intel/torch-xpu-ops/pull/382
- [ ] `aten::addcdiv.out`, https://github.com/intel/torch-xpu-ops/pull/486
- [ ] `aten::floor.out`, https://github.com/intel/torch-xpu-ops/pull/533
- [ ] `aten::linspace.out`
- [ ] `aten::sgn.out`, https://github.com/intel/torch-xpu-ops/pull/212
- [ ] `aten::topk.values`

**Comment by dvrogozh** [comment]
With merging of #131015, `aten::addcdiv.out` is available in pytorch. Not yet available:
- [ ] `aten::floor.out`, https://github.com/intel/torch-xpu-ops/pull/533
- [ ] `aten::linspace.out`
- [ ] `aten::prod.int_out`
- [ ] `aten::topk.values`, https://github.com/intel/torch-xpu-ops/pull/547

**Comment by dvrogozh** [comment]
With merging of #131643, `aten::floor.out` and  `aten::topk.values` are available in pytorch. Following 2 are still in progress:
- [ ] `aten::linspace.out`
- [ ] `aten::prod.int_out`, https://github.com/intel/torch-xpu-ops/pull/615

**Comment by dvrogozh** [comment]
`aten::prod.int_out` is available after merge of https://github.com/pytorch/pytorch/pull/133850. Only `aten::linspace.out` remains not implemented:
- [ ] `aten::linspace.out`

**Comment by dvrogozh** [comment]
`aten::linspace.out` is available at least from https://github.com/pytorch/pytorch/commit/d08dbd0436637a04098151b0e03c69dcdab3f44e targeting availability in PT 2.6.
