### ISSUE TITLE
Document the torch.cuda.cudart function

### ISSUE THREAD

**Issue by svekars** [pytorch/pytorch#127908]
Document the `torch.cuda.cudart` function located in [https://github.com/pytorch/pytorch/blob/main/torch/cuda/__init__.py#L318](https://github.com/pytorch/pytorch/blob/main/torch/cuda/__init__.py#L318).
Follow the [Docstring Guidelines](https://github.com/pytorch/pytorch/wiki/Docstring-Guidelines).

cc @brycebortree

**Comment by ignaciobartol** [comment]
\assigntome
