### ISSUE TITLE
recent torchinductor changes seems to break torchao CI

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#127924]
### 🐛 Describe the bug

see: https://github.com/pytorch/ao/actions/runs/9367512416/job/25795245248

and see https://github.com/pytorch/ao/pull/301 (only the pytorch nightly test fails)

Repro: 
1. install most recent torch nightly version
2. (with https://github.com/pytorch/ao/tree/main) test/integration/test_integration.py -k test_autoquant_one_input_21_cuda

### Versions

pytorch nightly

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by desertfire** [comment]
I verified it reproduces with pytorch commit e216df48c8dc0ec7a4b3d279444259b13f674257 .
