### ISSUE TITLE
Document the torch.utils.data.datapipes.utils.decoder.basichandlers function

### ISSUE THREAD

**Issue by svekars** [pytorch/pytorch#127912]
Document the `torch.utils.data.datapipes.utils.decoder.basichandlers` function located in [https://github.com/pytorch/pytorch/blob/main/torch/utils/data/datapipes/utils/decoder.py#L31](https://github.com/pytorch/pytorch/blob/main/torch/utils/data/datapipes/utils/decoder.py#L31).
Follow the [Docstring Guidelines](https://github.com/pytorch/pytorch/wiki/Docstring-Guidelines).

cc @brycebortree

**Comment by arunppsg** [comment]
I have a question: unlike other `torch.utils` submodules, `torch.utils.datapipes` does not appear in web-documentation. Should it be added?
