### ISSUE TITLE
[Feature Request] torch.nn.Flatten(start_dim=1, end_dim=-1)

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#12796]
## 🚀 Feature

`torch.nn.Flatten(start_dim=1, end_dim=-1)` basically just convert the input as `input.flatten(start_dim, end_dim)`

## Motivation

Let's think that we have code

```python
import torch

a = torch.rand(1024, 100)

model = torch.nn.Sequential(
    torch.nn.Linear(100, 50),
    torch.nn.ReLU(),
    torch.nn.Linear(50, 1),
)

print(model(a).shape)
```
The shape would be `torch.Size([1024, 1])`, but sometimes it would be more convenient to have a shape `torch.Size([1024])` instead. If we had `torch.nn.Flatten`, we can simply do:

```python
import torch

a = torch.rand(1024, 100)

model = torch.nn.Sequential(
    torch.nn.Linear(100, 50),
    torch.nn.ReLU(),
    torch.nn.Linear(50, 1),
    torch.nn.Flatten(start_dim=0)
)

print(model(a).shape)
```

Also, if we want to do a CNN that has fully connected layers following conv layers, `torch.nn.Flatten` would also be useful:

```python
import torch

a = torch.rand(1024, 3, 100, 100)

model = torch.nn.Sequential(
    torch.nn.Conv2d(3, 10, 3),
    torch.nn.ReLU(),
    torch.nn.Conv2d(10, 5, 3),
    torch.nn.ReLU(),
    torch.nn.Flatten(),
    torch.nn.Linear(46080, 50),
    torch.nn.ReLU(),
    torch.nn.Linear(50, 1),
)

print(model(a).shape)
```

## Additional context

If the pytorch team think this is a good feature, I will do the PR.

See also: https://www.tensorflow.org/api_docs/python/tf/layers/Flatten

**Comment by zou3519** [comment]
Sequential is very limited and not the way to go. You should try to write your own module.
