### ISSUE TITLE
No such thing as xlocale.h

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#12809]
## 🐛 Bug

xlocale.h isn't a thing on recent linux:
https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27

This has been added by #12739, which refers to windows in the commit message, but adds the xlocale.h in the non-windows part of the new ifdef.
Is the ifdef else part (that xlocale.h) needed? @zdevito 

## To Reproduce

Build current master on a system with glibc 2.27 (e.g. debian unstable).

```
In file included from ../torch/csrc/jit/script/tree.h:7:0,
                 from ../torch/csrc/jit/script/error_report.h:3,
                 from ../torch/csrc/jit/script/compiler.h:7,
                 from ../torch/csrc/jit/graph_executor.cpp:35:
../torch/csrc/jit/script/lexer.h:11:21: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>
                     ^
compilation terminated.
```

Of course, I'd be happy to submit a patch removing it, but not if someone else needs it. (Then one should probably check at configuration.)

**Comment by t-vi** [comment]
As far as I can tell, [locale.h has been in glibc forever](https://sourceware.org/git/?p=glibc.git;a=blob;f=locale/locale.h;hb=643e9936eb83f4c7431072ab60a207de35d382f1#l123), maybe we can just import locale.h unconditionally?

**Comment by vishwakftw** [comment]
#12838 should’ve fixed this issue.
