### ISSUE TITLE
[User Empathy Day 2] non-deterministic recompiles for ChatTTS model

### ISSUE THREAD

**Issue by shunting314** [pytorch/pytorch#128074]
### 🐛 Describe the bug

Doing inference with ChatTTS model (https://huggingface.co/2Noise/ChatTTS) will trigger non-deterministic recompiles.

E.g., for the first 5 texts we do inference in the testing script (https://gist.github.com/shunting314/a904ad991a9893c0a7f3c6e190f7437e ), if no re-compile happens, we get around 2x speed up. But when recompiles happens, end2end latency is slower than eager.

When recomiples happens, here is the log for the failed guards: https://gist.github.com/shunting314/e4dbcaed70d743b059343b629fe1b568

The recompilation is quite non-deterministic. I've seen the following happens
- no recompile
- the first input triggers recompile
- the third and fourth input triggers recompile

### Error logs

.

### Versions

.

cc @ezyang @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim

**Comment by anijain2305** [comment]
Some update on this

* No non-determinism in recompilations now.
* A lot of changes made in, which is causing more recompiles. Some of them could be removed by latest HF work. I opened an issue to encourage authors to revisit compile support - https://github.com/2noise/ChatTTS/issues/748
