### ISSUE TITLE
[dynamo] DAC: 'AudioSignal' object has no attribute 'sample_rate'

### ISSUE THREAD

**Issue by pianpwk** [pytorch/pytorch#128065]
### 🐛 Describe the bug

Running the compress/decompress stage of [DAC](https://github.com/descriptinc/descript-audio-codec) leads to several errors `'AudioSignal' object has no attribute 'sample_rate'`. Here AudioSignal is a custom class storing a mixture of tensor data (e.g. audio_data) and other numerical attributes, including sample_rate (integer).

### Error logs

```
Traceback (most recent call last):
  File "/data/users/pianpwk/pytorch/descript-audio-codec/test-dac.py", line 45, in <module>
    x = _compress(signal)
  File "/data/users/pianpwk/pytorch/torch/_dynamo/eval_frame.py", line 432, in _fn
    return fn(*args, **kwargs)
  File "/data/users/pianpwk/pytorch/descript-audio-codec/test-dac.py", line 43, in _compress
    return model.compress(signal)
  File "/data/users/pianpwk/pytorch/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/users/pianpwk/pytorch/descript-audio-codec/dac/model/base.py", line 159, in compress
    self.eval()
  File "/data/users/pianpwk/pytorch/descript-audio-codec/dac/model/base.py", line 163, in torch_dynamo_resume_in_compress_at_159
    audio_signal = audio_signal.clone()
  File "/home/pianpwk/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/audiotools/core/audio_signal.py", line 641, in clone
    clone = type(self)(
  File "/home/pianpwk/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/audiotools/core/audio_signal.py", line 122, in __init__
    def __init__(
  File "/home/pianpwk/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/audiotools/core/audio_signal.py", line 1066, in stft_params
    default_win_len = int(2 ** (np.ceil(np.log2(0.032 * self.sample_rate))))
AttributeError: 'AudioSignal' object has no attribute 'sample_rate'
```

### Minified repro

```
# built from source: https://github.com/descriptinc/descript-audio-codec/tree/main
import dac
import torch
from audiotools import AudioSignal

# Download a model
model_path = dac.utils.download(model_type="44khz")
model = dac.DAC.load(model_path)
model.to('cuda')

# Load audio signal file
# 4ch.wav is located here: https://www.mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Samples/SoundCardAttrition/4ch.wav
signal = AudioSignal('4ch.wav')
signal._audio_data = signal._audio_data[:, :1, :]
# Encode audio signal as one long file
# (may run out of GPU memory on long files)
signal.to(model.device)

@torch.compile
def _compress(signal):
    return model.compress(signal)
x = _compress(signal)

# Decompress it back to an AudioSignal
@torch.compile
def _decompress(x):
    return model.decompress(x)
y = _decompress(x)
```

### Versions

Collecting environment information...
PyTorch version: 2.4.0a0+git21144ce
Is debug build: False
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.34

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-0_fbk21_hardened_12633_g4db063a1bcb5-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100
GPU 1: NVIDIA H100
GPU 2: NVIDIA H100
GPU 3: NVIDIA H100

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.8.0
/usr/lib64/libcudnn.so.9.1.0
/usr/lib64/libcudnn_adv.so.9.1.0
/usr/lib64/libcudnn_adv_infer.so.8.8.0
/usr/lib64/libcudnn_adv_train.so.8.8.0
/usr/lib64/libcudnn_cnn.so.9.1.0
/usr/lib64/libcudnn_cnn_infer.so.8.8.0
/usr/lib64/libcudnn_cnn_train.so.8.8.0
/usr/lib64/libcudnn_engines_precompiled.so.9.1.0
/usr/lib64/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/lib64/libcudnn_graph.so.9.1.0
/usr/lib64/libcudnn_heuristic.so.9.1.0
/usr/lib64/libcudnn_ops.so.9.1.0
/usr/lib64/libcudnn_ops_infer.so.8.8.0
/usr/lib64/libcudnn_ops_train.so.8.8.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          184
On-line CPU(s) list:             0-183
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 9654 96-Core Processor
CPU family:                      25
Model:                           17
Thread(s) per core:              1
Core(s) per socket:              184
Socket(s):                       1
Stepping:                        1
BogoMIPS:                        4792.79
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 clzero xsaveerptr wbnoinvd arat npt lbrv nrip_save tsc_scale vmcb_clean pausefilter pfthreshold v_vmsave_vmload vgif avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
Virtualization:                  AMD-V
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       11.5 MiB (184 instances)
L1i cache:                       11.5 MiB (184 instances)
L2 cache:                        92 MiB (184 instances)
L3 cache:                        2.9 GiB (184 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-183
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy==1.9.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] onnx==1.16.1
[pip3] onnxscript==0.1.0.dev20240530
[pip3] open-clip-torch==2.24.0
[pip3] optree==0.11.0
[pip3] pytorch-lightning==2.0.7
[pip3] pytorch-triton==3.0.0+45fff310c8
[pip3] torch==2.3.0
[pip3] torch-stoi==0.2.1
[pip3] torchaudio==2.2.0a0+1980f8a
[pip3] torchdiffeq==0.2.4
[pip3] torchmetrics==1.4.0.post0
[pip3] torchsde==0.2.6
[pip3] torchvision==0.19.0a0+a8a9f2d
[conda] blas                      1.0                         mkl  
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-include               2023.1.0         h06a4308_46344  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.26.4          py310h5f9d8c6_0  
[conda] numpy-base                1.26.4          py310hb5e798b_0  
[conda] open-clip-torch           2.24.0                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] pytorch-lightning         2.0.7                    pypi_0    pypi
[conda] pytorch-triton            3.0.0+45fff310c8          pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] torch-stoi                0.2.1                    pypi_0    pypi
[conda] torchaudio                2.2.0a0+1980f8a           dev_0    <develop>
[conda] torchdiffeq               0.2.4                    pypi_0    pypi
[conda] torchmetrics              1.4.0.post0              pypi_0    pypi
[conda] torchsde                  0.2.6                    pypi_0    pypi
[conda] torchvision               0.19.0a0+a8a9f2d           dev_0    <develop>

cc @ezyang @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim

**Comment by anijain2305** [comment]
This does not repro on main. The compile annotation above is sub-optimal. I moved `torch.compile` to a more torch-y function `encode` - https://github.com/descriptinc/descript-audio-codec/blob/main/dac/model/dac.py#L209. With this wrapping, `torch.compile` worked OOTB.
