### ISSUE TITLE
Verify that guards are well formed before concluding that Dynamo complication has succeeded

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#128090]
### 🐛 Describe the bug

Let's say for some reason you have some guard code that is misimplemented and it's calling a function that doesn't exist. Will Dynamo compilation fail? No. Instead, this will happen:

```
W0605 17:24:08.994000 140266518349376 torch/_dynamo/convert_frame.py:744] [4/8] torch._dynamo hit config.cache_size_limit (8)
W0605 17:24:08.994000 140266518349376 torch/_dynamo/convert_frame.py:744] [4/8]    function: 'forward' ([redacted]:149)
W0605 17:24:08.994000 140266518349376 torch/_dynamo/convert_frame.py:744] [4/8]    last reason: name 'Trunc' is not defined
W0605 17:24:08.994000 140266518349376 torch/_dynamo/convert_frame.py:744] [4/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
```

This is dumb. If we're generating malformed guard code, I definitely don't want to find out about it because I hit my cache size limit. Just fail the entire compile process early.

@hyuen and co ran into this, but I've also seen it in a few other cases too

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by Aashishthakur10** [comment]
Can you share some sample code to recreate this?

**Comment by anijain2305** [comment]
We can run the guards once with the locals of the frame we just compiled before Dynamo calls compilation a success. I did try to do that at the beginning of this year but there were lots of issues - https://github.com/pytorch/pytorch/pull/118448
