### ISSUE TITLE
PyTorch was compiled without NumPy support

### ISSUE THREAD

**Issue by zacwellmer** [pytorch/pytorch#12807]
I have followed the instructions to install from source but it appears pytorch is not being compiled with Numpy support.

This will reproduce the error
```python
import torch
import numpy as np
a = np.array([1.0])
b = torch.from_numpy(a)
```

The error received is
```
RuntimeError: PyTorch was compiled without NumPy support
```

I'm running on version 1.0.0a0+cffeb03

**Comment by vishwakftw** [comment]
Can you show the output of the build?

**Comment by mratsim** [comment]
`export USE_NUMPY=ON` before running the build script?

**Comment by vishwakftw** [comment]
USE_NUMPY is set internally. Can you provide system info and the build log?

**Comment by zacwellmer** [comment]
I just retried this again today after removing all my conda packages and didn't experience any issues. I was previously trying to follow some of the cpu acceleration instructions from fastai and I'm guessing this caused some issues.
