### ISSUE TITLE
Map with multiple arguments not supported in Dynamo and causes graph breaks

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#128072]
### 🐛 Describe the bug

```
import torch
torch.set_default_device('cuda')

def f(a, b):
    return (a[0] * b[0] + a[1] * b[1])

x = [torch.randn(5) for _ in range(3)]
y = [torch.randn(5) for _ in range(3)]
torch.compile(lambda x, y: map(f, x, y), fullgraph=True)(x, y)
```

```
torch._dynamo.exc.Unsupported: invalid handler args <bound method BuiltinVariable.call_map of BuiltinVariable()> [UserFunctionVariable(), ListVariable(length=3), ListVariable(length=3)] {}
```

### Versions

N/A

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @amjames @bdhirsh

**Comment by Aashishthakur10** [comment]
It looks like `call_map` is built to only support a single argument. I'll work on modifying it to handle multiple arguments.

**Comment by Aashishthakur10** [comment]
@janeyx99 @ezyang @soulitzer What would be a good place to add tests for this? `test/dynamo` is dense, so I am not quite sure.

**Comment by williamwen42** [comment]
@Aashishthakur10 you can put this in `test/dynamo/test_repros.py`

**Comment by zou3519** [comment]
raising priority due to additional internal ask: https://fb.workplace.com/groups/1075192433118967/permalink/1156442982239031/
