### ISSUE TITLE
Multi-GPU forward pass fails if first GPU id is not 0

### ISSUE THREAD

**Issue by achaiah** [pytorch/pytorch#1280]
I can specify multiple GPU IDs and train a network using them just fine. However, when it comes time to run a validation dataset through the trained network, pytorch throws an error when using a list of GPU IDs unless the GPU ID list starts with id 0.

Here's a sample function that will cause an error:

```
def visualize_model(model=None, num_images=5, use_gpu=False, gpu_ids=[0]):
    print("Using GPU: " + str(gpu_ids[0]))
    for i, data in enumerate(dset_loaders['val']):
        inputs, labels = data
        if use_gpu:
            inputs, labels = Variable(inputs.cuda(device=gpu_ids[0])), Variable(labels.cuda(device=gpu_ids[0]))
        else:
            inputs, labels = Variable(inputs), Variable(labels)

        outputs = model(inputs)      # ERROR HERE!
        _, preds = torch.max(outputs.data, 1)

        plt.figure()
        imshow(inputs.cpu().data[0])
        plt.title('pred: {}'.format(dset_classes[labels.data[0]]))
        plt.show()

        if i == num_images - 1:
            break
 ```

If I train the network using `gpu_ids = [0,1,2]` the function above executes with no problem.  However, if I train the network using `gpu_ids = [1,2,3]` it will throw an error.

**Comment by kuangliu** [comment]
try `CUDA_VISIBLE_DEVICES=1,2,3 python train.py`

**Comment by achaiah** [comment]
When I try that I get an error:
`RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:84`

**Comment by soumith** [comment]
you dont have 4 GPUs, looks like it. 

```
CUDA_VISIBLE_DEVICES=1,2,3 python train.py
```
This means it will try to use GPU2, 3, 4
Change this appropriately depending on the number of GPUs you have.
You can check number of GPUs with the command `nvidia-smi`

**Comment by achaiah** [comment]
Hmm I most certainly do have four GPUs, as the network trains on GPUs 1,2,3 just fine (per my original post).  The error has to do with something in the torch/pytorch pipeline assuming the wrong GPU when trying to load validation data (unless I misunderstand how to load the data onto GPU1, which the method above is supposed to demonstrate).

`RuntimeError: all tensors must be on devices[0]`

To wit:
```
$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:02:00.0     Off |                  N/A |
| 24%   32C    P8    12W / 180W |    320MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 0000:03:00.0     Off |                  N/A |
| 24%   36C    P8    12W / 180W |    119MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    Off  | 0000:81:00.0     Off |                  N/A |
| 24%   36C    P8    13W / 180W |    119MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    Off  | 0000:82:00.0     Off |                  N/A |
| 24%   35C    P8    12W / 180W |    119MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by albanD** [comment]
If you use @kuangliu suggestion of using `CUDA_VISIBLE_DEVICES=1,2,3` you need to set `gpu_ids = [0,1,2]` because what the env variable is going to do is make sure that if you ask for device 0, you get 1, if you ask for 1, you get 2 etc...

In your case, if you say you training code works but not your validation, you may want to check what are the difference between them if you don't want to go with the `CUDA_VISIBLE_DEVICES` solution.
In particular, make sure that you set the `use_gpu` argument and everything else in the same way.

**Comment by soumith** [comment]
okay so conclusion is:
`gpu_ids = [0,1,2]`.
Then do:
```
CUDA_VISIBLE_DEVICES="1,2,3" python train.py
```

**Comment by achaiah** [comment]
Ah... wow that's so confusing!  Yes, I can confirm that this works.  Wonder if there's any way to make it more obvious.

**Comment by albanD** [comment]
If you want to get funky, you can actually do `CUDA_VISIBLE_DEVICES=3,1,2` and asking for 0 will get you device 3, asking for 1 will get you device 1 and asking for device 2 will get you device 2.
This may be a bit confusing at first but it is actually quite powerful !

**Comment by achaiah** [comment]
Yeah I get that now that it's been highlighted, however, I bet anyone trying to learn the nuances of this will be confused for a while as well.  For my own enlightenment, what would be the reason where you might want to care whether your tensors live on GPU 3 vs GPU 1 if you're intending to use all of the GPUs anyway?

**Comment by albanD** [comment]
The `CUDA_VISIBLE_DEVICES` is provided by nvidia and impact the nvidia driver directly (pytorch is not responsible for that at all). So even though in our case we usually only use it to mask out GPUs, some other application need this finer control.

**Comment by achaiah** [comment]
So if you're simply indexing within the CUDA_VISIBLE_DEVICES list when specifying device in pytorch why not match the NVIDIA GPU id rather than the index within the CUDA_VISIBLE_DEVICES list?

**Comment by albanD** [comment]
We don't really have access to that, the nvidia driver is doing this conversion.
Undoing this conversion done in the nvidia driver in pytorch would be super confusing for anyone knowing what `CUDA_VISIBLE_DEVICES` is doing. And google search would fail you if you get any problem because the behaviour in pytorch would sudently become different from everything else.

**Comment by achaiah** [comment]
Ok that makes sense, thanks for the clarification!

**Comment by edgarriba** [comment]
@albanD I have noticed similar problems when specifying the device ids. Whatever combination is chosen, it always requires device with id 0.

**Comment by albanD** [comment]
@edgarriba I'm not sure to understand. If your observation is that whatever you put in `CUDA_VISIBLE_DEVICES`, indexing in pytorch always start at 0 and then grow one by one, that is not a problem, that is the expected behavior. [This](http://acceleware.com/blog/cudavisibledevices-masking-gpus) may clarify things.

**Comment by edgarriba** [comment]
what I'm saying is that when I specify the device ids (one or more) it needs to appear device 0, otherwise it always fails. Incrementing the `CUDA_VISIBLE_DEVICES` indexes doesn't solve the problem.

**Comment by WeaponShaw** [comment]
@edgarriba hi, did you resolve this problem ?

**Comment by wenwei202** [comment]
What if I train a model in a machine with 4 gpus using gpu 2 and 3, and then want to evaluate on a new machine with only one gpu? Why the gpu placement during training matters for the testing? This is tricky and inflexible.

**Comment by MarvinTeichmann** [comment]
For people coming from google, looking for a **fix/workaround**:

If you want to do a forward pass on devices=[1, 3], you need to manually move your model to device `1`. You can do that by calling `mymodel.cuda(1)'. 

Also note, that pytorch *loves* to move parameters back to device 0. So if the error persists, double check that the relevant model parameters are still on device 0 at execution time. 

@soumith and @albanD: Can you reopen this? There are legit reasons why a user might want to not perform a computation on device 0. As an example I have a model which consists of a CNN as well as a very memory intensive RNN. I like to run the CNN on devices [0,1] and the RNN on devices [2,3]. Making this work was very clumsy. On the other hand I do not see much reason why you need to restrict broadcasting to a very specific source device.

**Comment by apaszke** [comment]
@MarvinTeichmann that's a bug, it should be possible to do this. Can you please create a new issue and post a small script we could use to reproduce the problem (e.g. use a simplified network with dummy data)?

**Comment by MarvinTeichmann** [comment]
@apaszke Could you just reopen this? I am currently lacking the time to write a detailed issue report. 

This post is where people currently landing when they google the error. And the details provided by OP post are enough to reproduce the bug.

**Comment by apaszke** [comment]
I can't run the script posted in the original issue, because it's not self contained. The issue is likely that your model is not on the first device, as it should be, and that's what the error says.
