### ISSUE TITLE
Linear is not deterministic even using deterministic algorithms and cpu

### ISSUE THREAD

**Issue by michaelshekasta** [pytorch/pytorch#128062]
### 🐛 Describe the bug

import torch
torch.use_deterministic_algorithms(True)
a = torch.rand(2,3)
linear = torch.nn.Linear(3,3, bias=False)
torch.equal(linear(a)[0, :], linear(a[0, :])) # false

### Versions

[pip3] numpy==1.26.4
[pip3] torch==2.3.0
[pip3] torchvision==0.18.0
[pip3] triton==2.3.0

cc @mruberry @kurtamohler

**Comment by michaelshekasta** [comment]
I think that there is a problem with the enviroment

**Comment by janeyx99** [comment]
This does not repro for me on linux:
<img width="387" alt="image" src="https://github.com/pytorch/pytorch/assets/31798555/0d032ff4-e703-4452-94ed-b1876f35e019">

**Comment by michaelshekasta** [comment]
@janeyx99 Thank you for your prompt response! After testing the code, I observed that it occasionally returns True and sometimes False. To further investigate this behaviour, I executed the following code snippet:


torch.use_deterministic_algorithms(True)
for i in tqdm(range(2, 1000)):
    a = torch.rand(i+1, i)
    b = torch.rand(i, i)
    if not torch.equal((a @ b)[0:1, :], (a[0:1, :]) @ b):
        print(i)
        break
`

In my environment, the code prints 16.

**Comment by michaelshekasta** [comment]
@janeyx99 running on [colab](https://colab.research.google.com/drive/1meL1TbhYlZgNTxgqFpstJh4kRXRfWOc8?usp=sharing).

**Comment by kurtamohler** [comment]
@michaelshekasta, while the two expressions `(a @ b)[0:1, :]` and `(a[0:1, :]) @ b` are mathematically identical, they cannot be guaranteed to produce the same result because summations may occur in a different order. The same goes for the two expressions `linear(a)[0, :]` and `linear(a[0, :])`.

`torch.use_deterministic_algorithms` is only meant to provide determinism for two calls to the exact same operation given the exact same numerical arguments.

**Comment by kurtamohler** [comment]
Yes. With `linear(a)` and `linear(a[0, :])`, you are giving two different inputs, so `torch.use_deterministic_algorithms` cannot guarantee that they give the same results.

**Comment by michaelshekasta** [comment]
@kurtamohler does pytorch has a documentation how does the Linear work? I mean why does it not the same result?

**Comment by kurtamohler** [comment]
The documentation for `Linear` doesn't explain this.

A general fact about floating point numbers is that when two of them are added together, the result has a small amount of error that depends on the difference between the two numbers. So if a set of floating point numbers is summed in two different orders, the errors can accumulate differently and give two slightly different summation results.

Any operator in PyTorch that sums elements of a tensor together may perform the summation in a different order depending on the size of the input. There are multiple possible reasons for this (like performance)--it depends on the implementation of the operator.

With `torch.use_deterministic_algorithms`, we can guarantee that a given operator will perform summations in the same order each time that it is given the same exact input. But we don't (and probably can't) enforce the same order of summation for two different inputs of different sizes

**Comment by michaelshekasta** [comment]
@kurtamohler 
Thank you for responses!!! You're truly incredible!

**Comment by kurtamohler** [comment]
Happy to help!

Closing this, since different inputs are expected to give different results
