### ISSUE TITLE
`CUDNN_STATUS_BAD_PARAM` reported during traced model execution

### ISSUE THREAD

**Issue by jatentaki** [pytorch/pytorch#12817]
## 🐛 Bug

I have a model which behaves correctly "as it is" and during tracing, but the traced one fails during convolution. The backtrace is as follows:
```
Traceback (most recent call last):
  File "/cvlabdata2/home/tyszkiew/miniconda3/envs/se3use/lib/python3.6/site-packages/torch_localize-0.0.1-py3.6.egg/torch_localize/localize.py", line 14, in wrapped
    return method(self, *args, **kwargs)
  File "unet.py", line 274, in forward
    y = self.conv1(y)
  File "/cvlabdata2/home/tyszkiew/miniconda3/envs/se3use/lib/python3.6/site-packages/torch/nn/modules/module.py", line 475, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/cvlabdata2/home/tyszkiew/miniconda3/envs/se3use/lib/python3.6/site-packages/torch/nn/modules/module.py", line 465, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/cvlabdata2/home/tyszkiew/miniconda3/envs/se3use/lib/python3.6/site-packages/se3cnn-0.0.0-py3.6.egg/se3cnn/batchnorm.py", line 274, in forward
    return torch.nn.functional.conv3d(input, kernel, bias=bias, **self.kwargs)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
```
During tracing `self.kwargs` is consistently empty so this is surprising. I still believe this is my programming error, but the runtime error definitely could be more telling (what kind of `BAD_PARAM`?).
## To Reproduce

Unfortunately I couldn't boil the offending code down to a reasonable size, but it is pretty clear that there is just missing error handling hook which would translate the `cuDNN` runtime errors into something more human-digestible.

## Environment

PyTorch version: 1.0.0.dev20181015
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 390.87
cuDNN version: Probably one of the following:
/usr/local/MATLAB/R2018a/bin/glnxa64/libcudnn.so.7.0.3

Versions of relevant libraries:
[pip] numpy (1.15.2)
[pip] torch (1.0.0.dev20181015)
[pip] torch-localize (0.0.1)
[pip] torchvision (0.2.1)
[conda] pytorch-nightly           1.0.0.dev20181015 py3.6_cuda9.0.176_cudnn7.1.2_0    pytorch
[conda] torchvision               0.2.1                     <pip>

cc @csarofeen @ptrblck @xwang233 @gmagogsfm

**Comment by jatentaki** [comment]
Sorry for taking so long. Here it is:

```python
import torch

class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        self.conv1 = torch.nn.Conv1d(5, 10, 4)
        self.conv2 = torch.nn.Conv1d(10, 5, 3)

    def forward(self, x):
        y = self.conv1(x)
        y = self.conv2(y)

        return y

m = Model().cuda()
good = torch.randn((1, 5, 10)).cuda()
small = torch.randn((1, 5, 5)).cuda()

traced = torch.jit.trace(m, good)

traced(small)
```

in this case, it's just that the `bad` input is too short for the 2nd convolution to work with (due to no padding).

**Comment by ptrblck** [comment]
> in this case, it's just that the small input is too short for the 2nd convolution to work with (due to no padding).

In the current releases (cudnn7.6.5 and cudnn8.0.5) and a source build I get a proper error message and no cudnn failure:
```python
RuntimeError: Calculated padded input size per channel: (2). Kernel size: (3). Kernel size can't be greater than actual input size
```

**Comment by gmagogsfm** [comment]
This looks like a bug (incorrect input size) in repro code, instead of a `trace` issue. Closing.
