### ISSUE TITLE
[Bug] The cuDNN version is too old!

### ISSUE THREAD

**Issue by MoConWu** [pytorch/pytorch#128207]
### 🐛 Describe the bug

When I set:
```shell
set TORCH_CUDNN_SDPA_ENABLED=1
```
and run a Python code:
```python
with sdpa_kernel([SDPBackend.CUDNN_ATTENTION]):
    scaled_dot_product_attention(...)
    ...
```
I got a bug:
```shell
cuDNN Frontend error: s_kv not a multiple of 64 with dropout enabled is not supported with cudnn version below 9.0.0
```

you can test with code:
```python
import torch
print("cuDNN version:", torch.backends.cudnn.version())

# will show: cuDNN version: 8907
```

### Versions

```
PyTorch version: 2.4.0.dev20240606
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 企业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.30.0-rc1
Libc version: N/A

Python version: 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 12.4.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 552.12
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin\cudnn_ops64_9.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2100
DeviceID=CPU0
Family=198
L2CacheSize=12288
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2100
Name=12th Gen Intel(R) Core(TM) i7-12700
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.4.0.dev20240606
[pip3] torchaudio==2.2.0.dev20240606
[pip3] torchvision==0.19.0.dev20240606
[conda] blas                      1.0                         mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
[conda] mkl                       2023.1.0         h6b88ed4_46358
[conda] mkl-service               2.4.0           py312h2bbff1b_1
[conda] mkl_fft                   1.3.8           py312h2bbff1b_0
[conda] mkl_random                1.2.4           py312h59b6b97_0
[conda] numpy                     1.26.4          py312hfd52020_0
[conda] numpy-base                1.26.4          py312h4dde369_0
[conda] pytorch                   2.4.0.dev20240606 py3.12_cuda12.4_cudnn8_0    pytorch-nightly
[conda] pytorch-cuda              12.4                 h3fd98bf_6    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                2.2.0.dev20240606          pypi_0    pypi
[conda] torchvision               0.19.0.dev20240606          pypi_0    pypi
```

Preview (Nightly)

```shell
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch-nightly -c nvidia
```

![image](https://github.com/pytorch/pytorch/assets/33497338/decac94b-f564-434c-b1b1-459da6efc9fb)

cc @csarofeen @ptrblck @xwang233 @msaroufim

**Comment by rezadnayeri** [comment]
I have the same exact error, the cuDNN version: 8907 comes with the latest CUDA, so I have the same. Any advise? thanks

**Comment by rezadnayeri** [comment]
a little update, the followings helped me resolve that error, however, I still get a different error:
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer, padding=True, pad_to_multiple_of=64)
    dataloader = DataLoader(predict_dataset, batch_size=per_device_eval_batch_size, collate_fn=data_collator, num_workers=num_workers_cpu)
    
    
    NEW error:
    RuntimeError: cuDNN Frontend error: [cudnn_frontend] Error: No execution plans built successfully.
I0607 21:59:08.615000 140557512122368 torch/_dynamo/utils.py:320] TorchDynamo compilation metrics:
I0607 21:59:08.615000 140557512122368 torch/_dynamo/utils.py:320] Function, Runtimes (s)

**Comment by bdhirsh** [comment]
cc @drisspg ?

**Comment by Panchovix** [comment]
On Windows, getting the same issue. Testing specifically on SD A1111 webui.

```
Traceback (most recent call last):
      File "G:\Stable difussion\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\txt2img.py", line 109, in txt2img
        processed = processing.process_images(p)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\processing.py", line 847, in process_images
        res = process_images_inner(p)
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 59, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\processing.py", line 984, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\processing.py", line 1342, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 218, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\sd_samplers_common.py", line 272, in launch_sampling
        return func()
               ^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 218, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 244, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\sd_models_xl.py", line 43, in apply_model
        return self.model(x, t, cond)
               ^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 22, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
                                                                     ^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 34, in __call__
        return self.__sub_func(self.__orig_func, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\sd_hijack_unet.py", line 50, in apply_model
        result = orig_func(self, x_noisy.to(devices.dtype_unet), t.to(devices.dtype_unet), cond, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\wrappers.py", line 28, in forward
        return self.diffusion_model(
               ^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\sd_unet.py", line 91, in UNetModel_forward
        return original_forward(self, x, timesteps, context, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 993, in forward
        h = module(h, emb, context)
            ^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 100, in forward
        x = layer(x, context)
            ^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\repositories\generative-models\sgm\modules\attention.py", line 627, in forward
        x = block(x, context=context[i])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\repositories\generative-models\sgm\modules\attention.py", line 459, in forward
        return checkpoint(
               ^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\util.py", line 167, in checkpoint
        return func(*inputs)
               ^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\repositories\generative-models\sgm\modules\attention.py", line 467, in _forward
        self.attn1(
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "G:\Stable difussion\stable-diffusion-webui\modules\sd_hijack_optimizations.py", line 535, in scaled_dot_product_attention_forward
        hidden_states = torch.nn.functional.scaled_dot_product_attention(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    RuntimeError: cuDNN Frontend error: s_kv not a multiple of 64 with dropout enabled is not supported with cudnn version below 9.0.0
````

**Comment by ptrblck** [comment]
Update PyTorch to the latest nightly binary shipping with cuDN==9.1.0.70 and it'll work:
```python
import torch
import torch.nn.functional as F
from torch.profiler import profile, record_function, ProfilerActivity

# Optionally use the context manager to ensure one of the fused kernels is run
query = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda")
key = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda")
value = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda")


with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True) as prof:
    with torch.nn.attention.sdpa_kernel([torch.backends.cuda.SDPBackend.CUDNN_ATTENTION]):
        out = F.scaled_dot_product_attention(query,key,value)
print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10))
# -------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
#                                                    Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls  
# -------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
#                      aten::scaled_dot_product_attention         0.36%       1.198ms       100.00%     337.316ms     337.316ms       0.000us         0.00%      32.736us      32.736us             1  
#               aten::_scaled_dot_product_cudnn_attention        99.13%     334.405ms        99.64%     336.118ms     336.118ms      32.736us       100.00%      32.736us      32.736us             1  
# cudnn_generated_fort_native_sdpa_sm80_knob_6_128x64x...         0.00%       0.000us         0.00%       0.000us       0.000us      30.592us        93.45%      30.592us      30.592us             1  
# ...
```

**Comment by rezadnayeri** [comment]
@ptrblck 
thank you for the response!
can you please elaborate how to install latest nightly pytorch?
here is how I have been using the code, do I need any update? 

from torch.nn.attention import SDPBackend, sdpa_kernel
with sdpa_kernel(SDPBackend.FLASH_ATTENTION):
       outputs = model(**inputs)

**Comment by Panchovix** [comment]
> Update PyTorch to the latest nightly binary shipping with cuDN==9.1.0.70 and it'll work:
> 
> ```python
> import torch
> import torch.nn.functional as F
> from torch.profiler import profile, record_function, ProfilerActivity
> 
> # Optionally use the context manager to ensure one of the fused kernels is run
> query = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda")
> key = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda")
> value = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda")
> 
> 
> with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True) as prof:
>     with torch.nn.attention.sdpa_kernel([torch.backends.cuda.SDPBackend.CUDNN_ATTENTION]):
>         out = F.scaled_dot_product_attention(query,key,value)
> print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10))
> # -------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
> #                                                    Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls  
> # -------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
> #                      aten::scaled_dot_product_attention         0.36%       1.198ms       100.00%     337.316ms     337.316ms       0.000us         0.00%      32.736us      32.736us             1  
> #               aten::_scaled_dot_product_cudnn_attention        99.13%     334.405ms        99.64%     336.118ms     336.118ms      32.736us       100.00%      32.736us      32.736us             1  
> # cudnn_generated_fort_native_sdpa_sm80_knob_6_128x64x...         0.00%       0.000us         0.00%       0.000us       0.000us      30.592us        93.45%      30.592us      30.592us             1  
> # ...
> ```

I tried that code and it works, but even then, I still get `cuDNN Frontend error: s_kv not a multiple of 64 with dropout enabled is not supported with cudnn version below 9.0.0` when using other programs, and when doing

```
import torch
print("cuDNN version:", torch.backends.cudnn.version())
```

I get

`cuDNN version: 8907`

(venv) PS G:\Stable difussion\stable-diffusion-webui> py .\testcudann.py
G:\Stable difussion\stable-diffusion-webui\testcudann.py:13: UserWarning: 1Torch was not compiled with flash attenti  out = F.scaled_dot_product_attention(query,key,value)
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:686.)
  out = F.scaled_dot_product_attention(query,key,value)
---------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                         Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls
---------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
           aten::scaled_dot_product_attention         0.03%      75.100us       100.00%     231.314ms     231.314ms      66.000us         0.03%     231.311ms     231.311ms             1
    aten::_scaled_dot_product_cudnn_attention        99.88%     231.045ms        99.97%     231.239ms     231.239ms     230.904ms        99.82%     231.245ms     231.245ms             1
                                  aten::empty         0.07%     173.400us         0.07%     173.400us      86.700us     339.000us         0.15%     339.000us     169.500us             2
                          aten::empty_strided         0.01%      20.600us         0.01%      20.600us      20.600us       2.000us         0.00%       2.000us       2.000us             1
---------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 231.314ms
Self CUDA time total: 231.311ms

```
(venv) PS G:\Stable difussion\stable-diffusion-webui> py
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print("cuDNN version:", torch.backends.cudnn.version())
cuDNN version: 8907
>>>
(venv) PS G:\Stable difussion\stable-diffusion-webui> py .\test2cudnn.py
cuDNN version: 8907
(venv) PS G:\Stable difussion\stable-diffusion-webui>
```

Installed nightly torch from today, June 11 of 2024.

**Comment by eqy** [comment]
Please note that cuDNN attention is not yet supported on Windows as we have not upgraded to cuDNN v9 there yet, we'll revisit once we get the cuDNN v9 upgrade done on Windows.

**Comment by Panchovix** [comment]
Tried from nightly torch from today (2.5.0) and now it seems to work fine.

```
Collecting environment information...
PyTorch version: 2.5.0.dev20240614+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.28.0-rc5
Libc version: N/A

Python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: 12.5.40
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 555.99
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin\cudnn_ops64_9.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=4201
DeviceID=CPU0
Family=107
L2CacheSize=8192
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=4201
Name=AMD Ryzen 7 7800X3D 8-Core Processor
ProcessorType=3
Revision=24834

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] onnx==1.16.1
[pip3] onnxruntime-gpu==1.18.0
[pip3] open-clip-torch==2.20.0
[pip3] optree==0.11.0
[pip3] pytorch-lightning==1.9.4
[pip3] torch==2.5.0.dev20240614+cu124
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==1.4.0.post0
[pip3] torchsde==0.2.6
[pip3] torchvision==0.19.0.dev20240614+cu124
[pip3] triton==3.0.0
[conda] No relevant packages
```

CUDNN seems to be still on 8907 though.

**Comment by MoConWu** [comment]
> Tried from nightly torch from today (2.5.0) and now it seems to work fine.
> 
> ```
> Collecting environment information...
> PyTorch version: 2.5.0.dev20240614+cu124
> Is debug build: False
> CUDA used to build PyTorch: 12.4
> ROCM used to build PyTorch: N/A
> 
> OS: Microsoft Windows 11 Pro
> GCC version: Could not collect
> Clang version: Could not collect
> CMake version: version 3.28.0-rc5
> Libc version: N/A
> 
> Python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] (64-bit runtime)
> Python platform: Windows-11-10.0.22631-SP0
> Is CUDA available: True
> CUDA runtime version: 12.5.40
> CUDA_MODULE_LOADING set to: LAZY
> GPU models and configuration:
> GPU 0: NVIDIA GeForce RTX 4090
> GPU 1: NVIDIA GeForce RTX 4090
> GPU 2: NVIDIA GeForce RTX 3090
> 
> Nvidia driver version: 555.99
> cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin\cudnn_ops64_9.dll
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> Is XNNPACK available: True
> 
> CPU:
> Architecture=9
> CurrentClockSpeed=4201
> DeviceID=CPU0
> Family=107
> L2CacheSize=8192
> L2CacheSpeed=
> Manufacturer=AuthenticAMD
> MaxClockSpeed=4201
> Name=AMD Ryzen 7 7800X3D 8-Core Processor
> ProcessorType=3
> Revision=24834
> 
> Versions of relevant libraries:
> [pip3] numpy==1.26.2
> [pip3] onnx==1.16.1
> [pip3] onnxruntime-gpu==1.18.0
> [pip3] open-clip-torch==2.20.0
> [pip3] optree==0.11.0
> [pip3] pytorch-lightning==1.9.4
> [pip3] torch==2.5.0.dev20240614+cu124
> [pip3] torchdiffeq==0.2.3
> [pip3] torchmetrics==1.4.0.post0
> [pip3] torchsde==0.2.6
> [pip3] torchvision==0.19.0.dev20240614+cu124
> [pip3] triton==3.0.0
> [conda] No relevant packages
> ```
> 
> CUDNN seems to be still on 8907 though.

On the official website, the preview version is currently only up to 12.4. Is version 12.5 too high? Perhaps there will be more bugs that have not been fixed.

**Comment by MoConWu** [comment]
> Tried from nightly torch from today (2.5.0) and now it seems to work fine.
> 
> ```
> Collecting environment information...
> PyTorch version: 2.5.0.dev20240614+cu124
> Is debug build: False
> CUDA used to build PyTorch: 12.4
> ROCM used to build PyTorch: N/A
> 
> OS: Microsoft Windows 11 Pro
> GCC version: Could not collect
> Clang version: Could not collect
> CMake version: version 3.28.0-rc5
> Libc version: N/A
> 
> Python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] (64-bit runtime)
> Python platform: Windows-11-10.0.22631-SP0
> Is CUDA available: True
> CUDA runtime version: 12.5.40
> CUDA_MODULE_LOADING set to: LAZY
> GPU models and configuration:
> GPU 0: NVIDIA GeForce RTX 4090
> GPU 1: NVIDIA GeForce RTX 4090
> GPU 2: NVIDIA GeForce RTX 3090
> 
> Nvidia driver version: 555.99
> cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin\cudnn_ops64_9.dll
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> Is XNNPACK available: True
> 
> CPU:
> Architecture=9
> CurrentClockSpeed=4201
> DeviceID=CPU0
> Family=107
> L2CacheSize=8192
> L2CacheSpeed=
> Manufacturer=AuthenticAMD
> MaxClockSpeed=4201
> Name=AMD Ryzen 7 7800X3D 8-Core Processor
> ProcessorType=3
> Revision=24834
> 
> Versions of relevant libraries:
> [pip3] numpy==1.26.2
> [pip3] onnx==1.16.1
> [pip3] onnxruntime-gpu==1.18.0
> [pip3] open-clip-torch==2.20.0
> [pip3] optree==0.11.0
> [pip3] pytorch-lightning==1.9.4
> [pip3] torch==2.5.0.dev20240614+cu124
> [pip3] torchdiffeq==0.2.3
> [pip3] torchmetrics==1.4.0.post0
> [pip3] torchsde==0.2.6
> [pip3] torchvision==0.19.0.dev20240614+cu124
> [pip3] triton==3.0.0
> [conda] No relevant packages
> ```
> 
> CUDNN seems to be still on 8907 though.

I downloaded pytorch 2.5.0, but the problem still persists.

**Comment by eqy** [comment]
Unfortunately it looks like the cuDNN version on Windows might still be too old...

**Comment by Panchovix** [comment]
Tried today (torch 2.5.0 from 28th June) and it seems cudnn is now updated on windows

`cuDNN version: 90100`

**Comment by MoConWu** [comment]
Thanks, I try it and work very well, I think we can close this issule.
