### ISSUE TITLE
Address performance regression from "Get rid of most usages of Type.tensor".

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#12827]
@apaszke found that this commit (https://github.com/pytorch/pytorch/commit/117885128073c9c2b32f4b33c6c79df3895b7071) is a major culprit in the ~6% perf regression we've seen on here: https://apaszke.github.io/pytorch-perf-hud/.

The above commit makes a bunch of changes, most of which are probably not relevant.  In particular the commit message mentions:
```
1) Most usages are replaced by at::empty.
2) native_tensor has its namespace function removed
3) Type.tensor(sizes, strides) becomes at::empty_strided(sizes, strides).
```

2) is certainly not relevant.

1) or 3) may be, it's likely that the dispatch is slower for `at::empty(...)` or `at::empty_strided(...)` than `Type.tensor(...)`.  This most of the time shouldn't matter, but it's likely one or more places we changed are along some hot path.  Luckily the changes are pretty much self contained, so it should be possible to find the culprit by just reverting the changes basically file-by-file.

Once the culprit is addressed, we should figure out why the specific function call is slower than Type.tensor.  Is this all TensorOptions overhead?  e.g. before:
`Type.tensor(size)` would be dispatched directly, whereas now the pattern is:
`at::empty(size, Type.options())` -> native::empty(size, Type.options())` -> Type.tensor(size)`

Is creating options slow?  Is passing options slow?  Is looking up Type from options slow?

Note also that this has further changed in master.  In particular:
1) TensorOptions is now smaller, so should pass faster (I think this was changed after this commit)
2) at::empty now uses backend-specific dispatch instead of dispatching back through Type.

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang @VitalyFedyunin @ngimel

**Comment by ezyang** [comment]
I'm going to stick my neck out here and say this issue is obsolete, given that it is old. The perf is real, but the particular commit probably isn't too enlightening to try specifically working against.
