### ISSUE TITLE
torch.cumprod will silently cast the output data type to int64

### ISSUE THREAD

**Issue by maybeLee** [pytorch/pytorch#128294]
### 🐛 Describe the bug

Torch.cumprod will silently cast the output data type to torch.int64 regardless of the actual input's dtype.
It would be better if these APIs can keep the output's dtype to be consistent with the input's dtype, or this silent casting could be explicit in the documentation.

``` Python
import numpy as np
np.random.seed(1234)
import torch

input = torch.tensor(np.random.randint(-50, 50, (1,1,4,3)), dtype=torch.uint8)
dim = 2
out = torch.cumprod(input, dim)
print(f'Torch result:')
print(out)
print(f'This is incorrect, because the results is casted (unexpectedly) to {out.dtype}:')
print(f'If specified output dtype to be input dtype (uint8), the result is correct:')
print(f'torch.cumprod(input, dim, dtype=input.dtype): {torch.cumprod(input, dim, dtype=input.dtype)}')
```

output:
``` Shell
Torch result:
tensor([[[[       253,         33,        244],
          [       759,        858,      56120],
          [    167739,     218790,   12851480],
          [  38915448,   51634440, 3200018520]]]])
This is incorrect, because the results is casted (unexpectedly) to torch.int64:
If specified output dtype to be input dtype (uint8), the result is correct:
torch.cumprod(input, dim, dtype=input.dtype): tensor([[[[253,  33, 244],
          [247,  90,  56],
          [ 59, 166,  24],
          [120,   8,  88]]]], dtype=torch.uint8)
```

### Versions

[pip3] numpy==1.26.4
[pip3] optree==0.11.0
[pip3] torch==2.3.0
[pip3] triton==2.3.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi

cc @albanD

**Comment by vadimkantorov** [comment]
Maybe related: https://github.com/pytorch/pytorch/issues/55366 . Currently reduction functions, but also cumprod apparently, do upcast from uint8 to int64/int32 and materialize an excessively large temp tensor

**Comment by bdhirsh** [comment]
triage review to discuss if this is a docs issue or a bug in the impl

**Comment by vadimkantorov** [comment]
I think it's that many ops upcast uint8 inputs to int64 before proceeding... probably both the case for sum and cumprod...

**Comment by mikaylagawarecki** [comment]
This seems to be expected behavior as reduction operations upcast integer types to int64, marking actionable to verify and document this

**Comment by vadimkantorov** [comment]
My view is that while it is the current behavior and should be documented as such, in the future avoiding upcast it is a nice memory-saving and memory-bandwidth-saving optimization (especially when upcast is materialized). Hopefully with more Triton/jiterator support, shorter-width dtype support without a materialized upcast can be done painlessly in the future. 

Besides that, sometimes directly specifying out-dtype is useful (especially when the outer model is not torch.compile-d yet) and even acc/compute dtype as well (for instance, a user might want to have bf16 inputs be (unmaterialized) upcast and fp32-accumulated, but then still written out as bf16)

**Comment by albanD** [comment]
Note that torch.prod already has a dtype argument to control the output dtype: https://pytorch.org/docs/stable/generated/torch.prod.html#torch.prod
I think we would accept adding the same argument to cumprod (and cumsum, etc)

**Comment by zeshengzong** [comment]
Hi, seems `dtype` already supported by `torch.cumprod` and `torch.cumsum`, and this issue may closed.

![image](https://github.com/user-attachments/assets/29d27b03-1cb9-4eff-a7cf-123d470e6540)

![image](https://github.com/user-attachments/assets/243e8fb0-f550-45b5-816d-4b1945d3ca33)

**Comment by maybeLee** [comment]
Thanks, I am closing the issue.
