### ISSUE TITLE
Why does the size of state_dict decrease a lot when I move the parameters to the CPU? What information was lost?

### ISSUE THREAD

**Issue by JWargrave** [pytorch/pytorch#128219]
### 🐛 Describe the bug

`./ip_adapter_weight.bin` is the weight file saved during training using the code below:
```python
    def save_ip_adapter_weight(self,weight_save_path):
        assert self.use_ip_adapter
        filtered_attn_processors={k:self.unet.attn_processors[k] for k in self.unet.attn_processors if isinstance(self.unet.attn_processors[k],torch.nn.Module)}
        ip_layers=torch.nn.ModuleList(filtered_attn_processors.values())
        torch.save(ip_layers.state_dict(),weight_save_path)
```

The size of `./ip_adapter_weight.bin` is `1.6G`, the following code outputs `1.6G	./ip_adapter_weight.bin`.
```shell
!du -sh ./ip_adapter_weight.bin
```

The device of saved parameters is `cuda:0`. I load `./ip_adapter_weight.bin` with `torch.load` and move all the parameters to `cpu` and save the parameters again to `./temp_state_dict_to_cpu.bin`. The code is as follows:
```python
state_dict_save_during_training=torch.load('./ip_adapter_weight.bin') # load weight saved during training
state_dict_to_cpu={k:state_dict_save_during_training[k].cpu() for k in state_dict_save_during_training.keys()} # move to cpu
torch.save(state_dict_to_cpu,'./temp_state_dict_to_cpu.bin') # save cpu weight
```

Then I find that the size of `./temp_state_dict_to_cpu.bin` is `98M`, the following code outputs `98M	./temp_state_dict_to_cpu.bin`
```shell
!du -sh ./temp_state_dict_to_cpu.bin
```

`98M` is much smaller than `1.6G`. I thinks it is really strange. I load `./ip_adapter_weight.bin` and `./temp_state_dict_to_cpu.bin` again and check some of their properties using the following code:
```python
state_dict_save_during_training=torch.load('./ip_adapter_weight.bin')
state_dict_to_cpu=torch.load('./temp_state_dict_to_cpu.bin')
assert len(state_dict_save_during_training.keys())==len(state_dict_to_cpu.keys())
for k1,k2 in zip(state_dict_save_during_training.keys(),state_dict_to_cpu.keys()):
    assert k1==k2
    
    assert torch.equal(state_dict_save_during_training[k1],state_dict_to_cpu[k2].cuda())
    assert torch.equal(state_dict_save_during_training[k1].cpu(),state_dict_to_cpu[k2])
    
    assert state_dict_save_during_training[k1].grad is None
    assert state_dict_to_cpu[k2].grad is None
    
    assert state_dict_save_during_training[k1].requires_grad is False
    assert state_dict_to_cpu[k2].requires_grad is False
    
    assert state_dict_save_during_training[k1].dtype is torch.float16
    assert state_dict_to_cpu[k2].dtype is torch.float16

```

The above code works fine. This means that both state_dicts have the same dtype `float16` and do not have gradients. And all parameters are equal.

I thinks it is so strange! What information was lost from `1.6G` to `98M`??!! Is it a BUG?!

Is there any difference between using `./ip_adapter_weight.bin` or `./temp_state_dict_to_cpu.bin` for testing and training?

`./ip_adapter_weight.bin` and `./temp_state_dict_to_cpu.bin` can be downloaded from [google drive](https://drive.google.com/drive/folders/1gZi2Egi3sRhxKhNtNUUz6voPbhdm34p8?usp=sharing)

### Versions

Collecting environment information...
PyTorch version: 2.2.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB
GPU 2: NVIDIA A800-SXM4-80GB
GPU 3: NVIDIA A800-SXM4-80GB
GPU 4: NVIDIA A800-SXM4-80GB
GPU 5: NVIDIA A800-SXM4-80GB
GPU 6: NVIDIA A800-SXM4-80GB
GPU 7: NVIDIA A800-SXM4-80GB

Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         897.738
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5200.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] onnx==1.15.0
[pip3] onnxruntime==1.17.1
[pip3] torch==2.2.0+cu121
[pip3] torchaudio==2.2.0+cu121
[pip3] torchvision==0.17.0+cu121
[pip3] triton==2.2.0
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.2.0+cu121              pypi_0    pypi
[conda] torchaudio                2.2.0+cu121              pypi_0    pypi
[conda] torchvision               0.17.0+cu121             pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by tringwald** [comment]
Are the tensors you are saving views of a bigger tensor? In that case, `torch` will save the whole tensor. You can avoid that by calling `.clone()` on all tensor views before saving.

**Comment by JWargrave** [comment]
> Are the tensors you are saving views of a bigger tensor? In that case, `torch` will save the whole tensor. You can avoid that by calling `.clone()` on all tensor views before saving.

Yes. `state_dict_save_during_training ` contains 64 parameters and I have tried to save every parameter to a bin file with the code below:
```python
for k, v in state_dict_save_during_training.items():
    torch.save(v, f'./gpu_{k}.bin')
    torch.save(v.cpu(), f'./cpu_{k}.bin')
```

Every `gpu_{k}.bin` has a size of `1.6G` and `cpu_{k}.bin` is much smaller. I want to know is there any difference in using `gpu_{k}.bin` or `cpu_{k}.bin` for testing and subsequent training?

**Comment by tringwald** [comment]
There should not be any difference in the tensor's data, you'll just discard some metadata (like the tensor's CUDA device) by using `cpu_{k].bin`. As I said above, you can also try to call `.clone()` instead of `.cpu()` and see if that fixes the problem.

**Comment by JWargrave** [comment]
> There should not be any difference in the tensor's data, you'll just discard some metadata (like the tensor's CUDA device) by using `cpu_{k].bin`. As I said above, you can also try to call `.clone()` instead of `.cpu()` and see if that fixes the problem.

I tried `.clone()`
```python
state_dict_save_during_training=torch.load('./ip_adapter_weight.bin') # load weight saved during training
state_dict_to_cpu={k:state_dict_save_during_training[k].clone() for k in state_dict_save_during_training.keys()} # clone
torch.save(state_dict_to_cpu,'./temp_state_dict_cloned.bin') # save cloned weight
```

The resulting `temp_state_dict_cloned.bin` is `98M`. Thanks! But I am still surprised that metadata is so large!

**Comment by tringwald** [comment]
It's not metadata, your saved tensors seem to be views into a bigger tensor.

```python3
x = torch.ones(1000**3)
y = x[:5]  # y is a view of the first 5 entries of x
```

Calling `torch.save(y, ...)` will still save the `x` tensor.

**Comment by JWargrave** [comment]
> It's not metadata, your saved tensors seem to be views into a bigger tensor.
> 
> ```python
> x = torch.ones(1000**3)
> y = x[:5]  # y is a view of the first 5 entries of x
> ```
> 
> Calling `torch.save(y, ...)` will still save the `x` tensor.

Thank you very much, I understand!
