### ISSUE TITLE
The weight update results of torch.nn.BatchNorm1d on different hardware are inconsistent

### ISSUE THREAD

**Issue by PhyllisJi** [pytorch/pytorch#128285]
### 🐛 Describe the bug

We used GPU and CPU respectively to train the model, only a single forward and back propagation, and the weight updates were inconsistent.
```python
import torch
import torch.nn as nn
import numpy as np
from torch import optim
import os
import torch.nn.functional as F


class Model_Gh8lMCGxHLli_0NjVOnFISjc2dkuC9Mz(nn.Module):
    def __init__(self):
        super(Model_Gh8lMCGxHLli_0NjVOnFISjc2dkuC9Mz, self).__init__()
        self.conv1_mutated = torch.nn.ConvTranspose1d(in_channels=3, out_channels=64, kernel_size=[1], stride=[1], padding=[0], output_padding=[0], dilation=[1], groups=1, bias=True)
        self.bn1 = torch.nn.BatchNorm1d(num_features=64, eps=1e-05, momentum=0.9)
        self.relu1 = torch.nn.ReLU()
        self.conv2_mutated = torch.nn.Conv1d(in_channels=64, out_channels=64, kernel_size=[1], stride=[1], padding=[0], dilation=[1], groups=1, bias=True)
        self.bn2 = torch.nn.BatchNorm1d(num_features=64, eps=1e-05, momentum=0.9)
        self.relu2_mutated = torch.nn.AdaptiveAvgPool1d(output_size=1)
        self.conv3_mutated = torch.nn.Conv1d(in_channels=64, out_channels=64, kernel_size=[1], stride=[1], padding=[0], dilation=[1], groups=1, bias=True)
        self.bn3 = torch.nn.BatchNorm1d(num_features=64, eps=1e-05, momentum=0.9)
        self.relu3 = torch.nn.ReLU()
        self.conv4_mutated = torch.nn.Conv1d(in_channels=64, out_channels=128, kernel_size=[1], stride=[1], padding=[1], dilation=[1], groups=1, bias=True)
        self.bn4 = torch.nn.BatchNorm1d(num_features=128, eps=1e-05, momentum=0.9)
        self.relu4_mutated = torch.erf
        self.conv5_mutated = torch.nn.ConvTranspose1d(in_channels=128, out_channels=1024, kernel_size=[1], stride=[1], padding=[0], output_padding=[0], dilation=[1], groups=1, bias=True)
        self.bn5 = torch.nn.BatchNorm1d(num_features=1024, eps=1e-05, momentum=0.9)
        self.relu5 = torch.nn.ReLU()
        self.globalpool = torch.nn.AdaptiveMaxPool1d(output_size=1)
        self.flatten = torch.nn.Flatten()
        self.linear1 = torch.nn.Linear(in_features=1024, out_features=512)
        self.bn6 = torch.nn.BatchNorm1d(num_features=512, eps=1e-05, momentum=0.9)
        self.relu6 = torch.nn.ReLU()
        self.tail_flatten = torch.nn.Flatten()
        self.tail_fc = torch.nn.Linear(in_features=512, out_features=10)

    def forward(self, x):
        x = self.conv1_mutated(x)
        x = self.bn1(x)
        x = self.relu1(x)
        x = self.conv2_mutated(x)
        x = self.bn2(x)
        x = self.relu2_mutated(x)
        x = self.conv3_mutated(x)
        x = self.bn3(x)
        x = self.relu3(x)
        x = self.conv4_mutated(x)
        x = self.bn4(x)
        x = self.relu4_mutated(x)
        x = self.conv5_mutated(x)
        x = self.bn5(x)
        x = self.relu5(x)
        x = self.globalpool(x)
        x = self.flatten(x)
        x = self.linear1(x)
        x = self.bn6(x)
        x = self.relu6(x)
        tail_flatten_output = self.tail_flatten(x)
        tail_fc_output = self.tail_fc(tail_flatten_output)

        tail_fc_output = tail_fc_output
        return tail_fc_output

```

### grad_diff between torch cpu and gpu

```
conv1_mutated.weight
0.054493383
conv1_mutated.bias
5.5010105e-08
# bn1-torch.nn.BatchNorm1d
bn1.weight
0.11135915
bn1.bias
0.09993172
conv2_mutated.weight
0.04085891
conv2_mutated.bias
0.00016388169
bn2.weight
0.052734636
bn2.bias
9.678304e-06
conv3_mutated.weight
0.04560852
conv3_mutated.bias
1.1920929e-06
bn3.weight
0.030974608
bn3.bias
0.029964829
conv4_mutated.weight
0.021974621
conv4_mutated.bias
1.7881393e-07
bn4.weight
0.026008025
bn4.bias
0.001900834
conv5_mutated.weight
0.016805578
conv5_mutated.bias
2.561137e-08
bn5.weight
0.017251626
bn5.bias
0.0034310077
linear1.weight
0.019508496
linear1.bias
1.5832484e-07
bn6.weight
0.00020761788
bn6.bias
0.013012487
tail_fc.weight
0.00012109056
tail_fc.bias
4.3287873e-06
```

### Steps to Reproduction

```bash
git clone -b torch-issue-batchnorm1d https://github.com/PhyllisJi/MoCoDiff_Bug.git
cd MoCoDiff_Bug/
cd pytorch_bug/
python ./cmp_output_torch.py
```

### Versions

PyTorch version: 2.2.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.0-20-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 535.98
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8260M CPU @ 2.30GHz
Stepping:                        5
CPU MHz:                         2453.203
CPU max MHz:                     3900.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        66 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] onnx==1.16.0
[pip3] torch==2.2.0
[pip3] triton==2.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.0                    pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

**Comment by ZhaoqiongZ** [comment]
Hi @PhyllisJi , I tried with 2.4.0.dev20240526+cu118 and not reproducible
here is what I got:

```
conv1_mutated.weight
3.1925738e-06
conv1_mutated.bias
5.509591e-08
bn1.weight
8.106232e-06
bn1.bias
1.758337e-05
conv2_mutated.weight
3.2205135e-06
conv2_mutated.bias
0.000114182476
bn2.weight
7.212162e-06
bn2.bias
1.000613e-05
conv3_mutated.weight
4.3958426e-06
conv3_mutated.bias
2.1457672e-06
bn3.weight
2.1976884e-06
bn3.bias
1.821667e-06
conv4_mutated.weight
1.5348196e-06
conv4_mutated.bias
1.937151e-07
bn4.weight
1.3131648e-06
bn4.bias
1.7601997e-07
conv5_mutated.weight
7.171184e-07
conv5_mutated.bias
4.0512532e-08
bn5.weight
1.1497177e-06
bn5.bias
3.5203993e-07
linear1.weight
4.172325e-07
linear1.bias
2.719462e-07
bn6.weight
3.3900142e-07
bn6.bias
1.1175871e-08
tail_fc.weight
3.4831464e-07
tail_fc.bias
2.2351742e-08
```

**Comment by colesbury** [comment]
Please see https://pytorch.org/docs/stable/notes/numerical_accuracy.html
