### ISSUE TITLE
Wrong result for Inplace tensor update on transpose for some devices with torch 2.3.0

### ISSUE THREAD

**Issue by jerrychenhf** [pytorch/pytorch#128202]
### 🐛 Describe the bug

I am using HPU device for testing, the following code shows the incorrect result on PyTorch 2.3.0. While it was correct for PyTorch 2.2.2
```
import torch
import habana_frameworks.torch.core as htcore

def fn(a):
 b = a.t()
 b.mul_(1.0)
 return b   

x = torch.arange(6).reshape([2, 3]).to('hpu')

print("x ", x.cpu())

compiled_fn = torch.compile(fn, backend="hpu_backend")        
y = compiled_fn(x)

print("y ", y.cpu())
```

Actual results (Wrong):
```
x tensor([[0, 1, 2],
[3, 4, 5]])
y tensor([[0, 1],
[2, 3],
[4, 5]])
```

Expected results:
```
x tensor([[0, 1, 2],
[3, 4, 5]])
y tensor([[0, 3],
[1, 4],
[2, 5]])
```

### Versions

Python version:
```
Python version: 3.10
PyTorch version: 2.3.0
Device used: HPU
```

cc @ezyang @bdhirsh @anijain2305 @chauhang @zou3519

**Comment by jerrychenhf** [comment]
This problem is related a few changes.

https://github.com/pytorch/pytorch/pull/104689 has a fix in 2.1.0 for ["Inplace tensor update on transpose"](https://github.com/pytorch/pytorch/issues/103650) problem for HPU or other devices that doens't have support on non contiguous output.But this PR cause some issues in part of the code calling wrap_output_with_input_device_. 

https://github.com/pytorch/pytorch/pull/119868 reverted part of the code of https://github.com/pytorch/pytorch/pull/104689 to fix the new issues in 2.3.0. So the original issue in https://github.com/pytorch/pytorch/issues/103650 reopens in 2.3.0

**Comment by jerrychenhf** [comment]
There are cases that a Faketensor is not reserve its fakeness when calling into convert_element_type.
If the Faketensor is a "meta" device Faketensor, it will call only to _convert_element_type_meta function which returns a torch.empty_strided(shape, strides, dtype=dtype, device=device).

This case is showing by the following code run on CPU too:
```
import torch

def fn(a):
 b = a.t()
 b.mul_(1.0)
 return b

x = torch.arange(6).reshape([2, 3]).to('cpu')

print("x ", x.cpu())

compiled_fn = torch.compile(fn)
y = compiled_fn(x)

print("y ", y.cpu())
```

I read through the discussions in https://github.com/pytorch/pytorch/pull/119868. There were a few proposals.

Is there any problem of the initial proposal of "checking the input and current type as the fakeness and call wrap_output_with_input_device only necessary"? 
I think convert_element_type_meta is much more impactful if we want to give convert_element_type_meta the semantics of preserving fakeness. Please suggest.

@ezyang @laithsakka

**Comment by eellison** [comment]
Cross-posting comment, but the example you gave doesn't run in eager: https://github.com/pytorch/pytorch/pull/128206#issuecomment-2166432130

**Comment by jerrychenhf** [comment]
Updated the CPU example that can run both on compile mode and eager mode (Note only compile mode shows the problem):
```
import torch

def fn(a):
 b = a.t()
 b.mul_(1.0)
 return b

x = torch.arange(6).reshape([2, 3]).bfloat16()

print("x ", x.cpu())

compiled_fn = torch.compile(fn)
y = compiled_fn(x)

print("y ", y.cpu())
```

**Comment by zou3519** [comment]
I can't repro this on main

**Comment by jerrychenhf** [comment]
@eelison Per discussion in https://github.com/pytorch/pytorch/pull/128206 with Edward, 

_"certainly if we reimplement all the pointwise rules directly in fake tensor, we can ensure we never decay to meta (since we're always operating on fake tensors) and then you would be guaranteed to have accurate device info. It does sound a bit duplicatey. But it definitely will work."_

We may still a fix in PyTorch to "reimplement all the pointwise rules directly in fake tensor", am I right on this?

**Comment by jerrychenhf** [comment]
@zou3519 
> I can't repro this on main
The issue is not showing for CPU and GPU device. It is related to non contiguous support handling for some specific devices like HPU.
For CPU, we could only see the behavior that there is a calling path in FakeTensor _dispatch_impl which the real device is not available.

**Comment by jerrychenhf** [comment]
Since PT 2.4 has a improvement of reconstructing a view on another base in AOT autograd (https://github.com/pytorch/pytorch/pull/121007) The noncontiguous outputs handling  for some specific device is no longer needed. (https://github.com/pytorch/pytorch/pull/104689)

And so this is no longer needed in PT 2.4 and upwards.
