### ISSUE TITLE
Compilation time for dynamic shapes for gpt-fast prefill regressed significantly.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#128398]
### 🐛 Describe the bug

```
diff --git a/benchmarks/gpt_fast/benchmark.py b/benchmarks/gpt_fast/benchmark.py
index 6e335ee3129..818319de1c1 100644
--- a/benchmarks/gpt_fast/benchmark.py
+++ b/benchmarks/gpt_fast/benchmark.py
@@ -97,10 +97,10 @@ DEFAULT_OUTPUT_FILE = "gpt_fast_benchmark.csv"
 all_experiments = {
     # A list of GPT models: LlaMa, Mixtral, etc.
     run_llama2_7b_bf16,
-    run_llama2_7b_int8,
-    run_mixtral_8x7b_int8,
+    # run_llama2_7b_int8,
+    # run_mixtral_8x7b_int8,
     # A list of micro-benchmarks.
-    run_multi_layer_norm,
+    # run_multi_layer_norm,
 }
 
 
diff --git a/benchmarks/gpt_fast/generate.py b/benchmarks/gpt_fast/generate.py
index a4e4b06c79d..bad84d0e458 100644
--- a/benchmarks/gpt_fast/generate.py
+++ b/benchmarks/gpt_fast/generate.py
@@ -62,7 +62,7 @@ def sample(logits, temperature: float = 1.0, top_k: Optional[int] = None):
     return idx_next, probs
 
 
-@torch.compile(fullgraph=True)
+@torch.compile(fullgraph=True, dynamic=True)
 def prefill(
     model: torch.nn.Module, x: torch.Tensor, input_pos: torch.Tensor, **sampling_kwargs
 ) -> torch.Tensor:
```

It takes 40 minutes+ to compile!
<img width="1005" alt="image" src="https://github.com/pytorch/pytorch/assets/6355099/923416d3-5253-467e-9922-d32c717e4193">

After looking at some profile results, Ed pointed me to this PR: https://github.com/pytorch/pytorch/pull/123342

cc: @ezyang @lezcano 

### Versions

N/A

cc @ezyang @bdhirsh @anijain2305 @chauhang

**Comment by lezcano** [comment]
Do you have any profile or so that points to that PR as the culprit?

**Comment by Chillee** [comment]
@lezcano yeah I reverted it and the compile time drops a lot. You can replicate it by patching the diff and running `python benchmarks/gpt_fast/benchmark.py`.

I also have this [SVG](https://cdn.fbsbx.com/v/t59.2708-21/447993100_476605274784631_4821499387708740775_n.svg/t.svg?_nc_cat=111&ccb=1-7&_nc_sid=2b0e22&_nc_ohc=klFC6QWKFkEQ7kNvgHWWcfA&_nc_ht=cdn.fbsbx.com&oh=03_Q7cD1QE-kIiEWgY2Glcc2WMZW1dE5fNxXFNbf26t56YcqJDt9w&oe=6669DF41&dl=1), hopefully the link works. But you can see we spend 65% of the time in `get_implications`.

![image](https://github.com/pytorch/pytorch/assets/6355099/f85c87f8-3cdd-4a89-8bb4-54e23fc6465a)

**Comment by retonym** [comment]
> @lezcano yeah I reverted it and the compile time drops a lot. You can replicate it by patching the diff and running `python benchmarks/gpt_fast/benchmark.py`.
> 
> I also have this [SVG](https://cdn.fbsbx.com/v/t59.2708-21/447993100_476605274784631_4821499387708740775_n.svg/t.svg?_nc_cat=111&ccb=1-7&_nc_sid=2b0e22&_nc_ohc=klFC6QWKFkEQ7kNvgHWWcfA&_nc_ht=cdn.fbsbx.com&oh=03_Q7cD1QE-kIiEWgY2Glcc2WMZW1dE5fNxXFNbf26t56YcqJDt9w&oe=6669DF41&dl=1), hopefully the link works. But you can see we spend 65% of the time in `get_implications`.
> 
> ![image](https://private-user-images.githubusercontent.com/6355099/338502655-f85c87f8-3cdd-4a89-8bb4-54e23fc6465a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1ODkzMTYsIm5iZiI6MTcxODU4OTAxNiwicGF0aCI6Ii82MzU1MDk5LzMzODUwMjY1NS1mODVjODdmOC0zY2RkLTRhODktOGJiNC01NGUyM2ZjNjQ2NWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDE1MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI3NDNlZjVkM2FjNjYzMGYxM2YwYmQ4NTYyMWFmNDY3NjVmZjlhYWZmMGY4NWQ1YThlZTI2MzdkZGVlN2ExMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8NBGsPR0AVdD07V6QPbclwN-iFIO7kgjVteYOLwntVw)

Hi @Chillee , may I ask what profiling tool you are using here. It looks intuitive and effective. Thanks.

**Comment by Chillee** [comment]
In PyTorch you can use it through TORCH_COMPILE_CPROFILE=1. Underneath, it uses cprofile and gprof2dot.

**Comment by retonym** [comment]
Thanks @Chillee , cool tool！
