### ISSUE TITLE
DTensor key word args to PrepareModuleInput not handled correctly

### ISSUE THREAD

**Issue by schinmayee** [pytorch/pytorch#128365]
Key word args to PrepareModuleInput can be DTensors, which are not handled correctly here.

https://github.com/pytorch/pytorch/blob/739aa224ec1aa8777cbeb215f6f668ab10d86803/torch/distributed/tensor/parallel/style.py#L438

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

**Comment by wanchaol** [comment]
Hey @schinmayee thanks for the report! This could be fixed easily, I'll submit a patch soon
