### ISSUE TITLE
torch.export gives segmentation fault

### ISSUE THREAD

**Issue by apbose** [pytorch/pytorch#128462]
### 🐛 Describe the bug

```
import torch
from torch.export import export
shape_or_input = [2,3]
class TestModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        shape_or_input[0] = x.shape[0]
        return torch.ops.aten.empty.memory_format(
            shape_or_input,
            dtype=torch.float32,
        )

inputs = [torch.randint(1, 3, shape_or_input, dtype=torch.int32)]
print(inputs)
empty_model = TestModule()

mod = export(empty_model, tuple(inputs))
out = mod.module()
```
The above works fine in torch 2.3.1 but fails in the torch2.4 nightly version (eg: torch2.4.0.dev20240611+cu121). Would anyone have an idea where I am going wrong?

### Versions

torch2.4.0.dev20240611+cu121
Please note this is on python3.8. Using the wheel- 
pip install https://download.pytorch.org/whl/nightly/cu121/torch-2.4.0.dev20240609%2Bcu121-cp38-cp38-linux_x86_64.whl --index-url https://download.pytorch.org/whl/nightly/cu121/torch
cc @ezyang @bdhirsh @anijain2305 @chauhang

**Comment by eellison** [comment]
This no longer repros for me on master. Please re-open if you rebase and still experience issue.
