### ISSUE TITLE
Negative numbers in the "Self CPU" column in pytorch's profiler

### ISSUE THREAD

**Issue by YItofive** [pytorch/pytorch#128479]
### 🐛 Describe the bug

When using pytorch's profiler tool to view the performance of cpu op execution, negative numbers were observed in the performance data table of the dump, which only appeared in the "Self CPU %" and "Self CPU" columns.

```python
import unittest
import torch
import torch.nn as nn
import torch.nn.functional as F

class MNIST(nn.Module):
    def __init__(self, num_classes):
        super(MNIST, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.bn1 = nn.BatchNorm2d(10)

    def forward(self, x):
        x = F.leaky_relu(self.bn1(self.conv1(x)))
        x = F.max_pool2d(x, 2)
        return x

class MnistTest(unittest.TestCase):
    def test_inference(self):
        torch.manual_seed(1 << 30)
        num_classes = 1
        cpu_model = MNIST(num_classes)
        batch_size = 32
        # Inference Test
        test_nums = 2
        cpu_model.eval()
        with torch.no_grad():
            with torch.autograd.profiler.profile() as prof:
                for t in range(test_nums):
                    cpu_images = torch.randn(
                        (batch_size, 1, 28, 28), dtype=torch.float32)
                    # CPU forward
                    cpu_outs = cpu_model(cpu_images)

            print(prof.table(sort_by="count", row_limit=-1))
            prof.export_chrome_trace('./1.json')

if __name__ == '__main__':
    unittest.main()
```

Multiple tries will give you the negative performance data like this.
Two of the "aten::batch_norm" have negative numbers in them.

```
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                             Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------

                aten::as_strided_         0.07%       9.000us         0.07%       9.000us       9.000us             1
                    aten::resize_         0.02%       3.000us         0.02%       3.000us       3.000us             1
                 aten::batch_norm        -0.60%     -76.000us         0.75%      95.000us      95.000us             1
     aten::_batch_norm_impl_index         0.70%      89.000us         0.71%      90.000us      90.000us             1
                      aten::empty         0.01%       1.000us         0.01%       1.000us       1.000us             1

                    aten::resize_         0.00%       0.000us         0.00%       0.000us       0.000us             1
                 aten::batch_norm        -0.13%     -16.000us         0.16%      20.000us      20.000us             1
     aten::_batch_norm_impl_index         0.15%      19.000us         0.15%      19.000us      19.000us             1
                      aten::empty         0.00%       0.000us         0.00%       0.000us       0.000us             1

    aten::max_pool2d_with_indices         1.10%     140.000us         1.10%     140.000us     140.000us             1
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
```

### Versions

Collecting environment information...
PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 9.0.0 (tags/RELEASE_900/final)
CMake version: version 3.22.1
Libc version: glibc-2.27

Python version: 3.8.12 (default, Jan 15 2022, 18:39:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-131-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Stepping:            13
CPU MHz:             4157.539
CPU max MHz:         4900.0000
CPU min MHz:         800.0000
BogoMIPS:            7200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            12288K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] onnx==1.10.0
[pip3] onnxruntime==1.9.0
[pip3] torch==2.3.1
[pip3] torchaudio==2.1.0+cpu
[pip3] torchvision==0.16.0+cpu
[pip3] triton==2.3.1
[conda] Could not collect

cc @robieta @chaekit @aaronenyeshi @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise

**Comment by YItofive** [comment]
From the code analysis, the algorithm used in calculating the duration of the SELF CPU has a loophole, which will treat the children of a certain parant's child node as the direct children of the current node as well, leading to the calculation of the calculation by subtracting some more hours, thus resulting in a negative value.

The source functions are as follows：（pytorch/torch/autograd/profiler_util.py）

    ```
def _populate_cpu_children(self):
        。。。。。。。。
        for thread_id, thread_events in threads:
            thread_events_ = sorted(
                thread_events,
                key=lambda event: [event.time_range.start, -event.time_range.end],
            )
            current_events: List[FunctionEvent] = []
            cur_end = 0
            for event in thread_events_:
                while len(current_events) > 0:
                    parent = current_events[-1]
                    if (
                        event.time_range.start >= parent.time_range.end
                        or event.time_range.end > parent.time_range.end
                    ):
                        # this can't be a parent
                        current_events.pop()
                    else:
                        parent.append_cpu_child(event)
                        assert (
                            event.cpu_parent is None
                        ), f"There is already a CPU parent event for {event.key}"
                        event.set_cpu_parent(parent)
                        break

                current_events.append(event)
```
Is it possible to optimize the implementation of this function or other function implementations to avoid this situation

**Comment by sraikund16** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/129554
