### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by xavierhou** [pytorch/pytorch#12857]
## To Reproduce

input the following lines ....

Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> c = torch.nn.Conv2d(16, 16, kernel_size=3)
>>> torch.nn.init.kaiming_normal_(c.weight)
Illegal instruction (core dumped)

## Expected behavior

the program process correctly, no error happens.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux):  Ubuntu 16.04 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): python setpy.py install
 - Python version:
 - CUDA/cuDNN version:  CUDA: 9.0/cuDNN: 7.0
 - GPU models and configuration:  V100
 - Any other relevant information: Vitual CPUs

## Additional context

I complied pytorch 1.0 from source on a virtual machine with 16 CPUs. 
Find an error descripted above, please help to figure out what happened. 
Many Thanks!

**Comment by H-Huang** [comment]
Sorry we missed this, closing due to stale issue. Please reopen a new issue if you see this error in a recent version
