### ISSUE TITLE
NotImplementedError: Could not run 'quantized::linear' with arguments from the 'CPU' backend. 'quantized::linear' is only available for these backends: [QuantizedCPU, QuantizedCUDA, BackendSelect, Python,....]

### ISSUE THREAD

**Issue by yangyyt** [pytorch/pytorch#128578]
### 🐛 Describe the bug

After QAT training, the following error is reported for inference:
NotImplementedError: Could not run 'quantized::linear' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'quantized::linear' is only available for these backends: [QuantizedCPU, QuantizedCUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

training code set:
model.modulexx.ar_predict_layer.qconfig = torch.ao.quantization.get_default_qat_qconfig('x86') [and set quant and dequant]
model_quant = torch.ao.quantization.prepare_qat(model, inplace=True)
model.train()
....
save: torch.save(torch.ao.quantization.convert(model.cpu().eval(), inplace=False).state_dict(), filename)

inference code set:
state_dict = torch.load(filename)
model.ar_predict_layer.qconfig = torch.ao.quantization.get_default_qat_qconfig('x86')
model_fp32_prepared = torch.quantization.prepare_qat(model_ar, inplace=True)
model_int8 = torch.quantization.convert(model_fp32_prepared.eval(), inplace=False)
model_int8.load_state_dict(state_dict['model'])
model_ar = model_int8
model_ar.eval()

### Versions

torch_version: 2.1.2+cu121
python:3.10

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @msaroufim

**Comment by Xia-Weiwen** [comment]
Hi @yangyyt The problem you met was that the quantized model expected quantized tensors as inputs but it got non-quantized inputs. It's probably because you didn't insert `QuantStub` and `DeQuantStub` correctly in the model. You may refer to this [tutorial](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html) for more details and examples.

**Comment by khadyasr** [comment]
> ### 🐛 Describe the bug
> After QAT training, the following error is reported for inference: NotImplementedError: Could not run 'quantized::linear' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'quantized::linear' is only available for these backends: [QuantizedCPU, QuantizedCUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].
> 
> training code set: model.modulexx.ar_predict_layer.qconfig = torch.ao.quantization.get_default_qat_qconfig('x86') [and set quant and dequant] model_quant = torch.ao.quantization.prepare_qat(model, inplace=True) model.train() .... save: torch.save(torch.ao.quantization.convert(model.cpu().eval(), inplace=False).state_dict(), filename)
> 
> inference code set: state_dict = torch.load(filename) model.ar_predict_layer.qconfig = torch.ao.quantization.get_default_qat_qconfig('x86') model_fp32_prepared = torch.quantization.prepare_qat(model_ar, inplace=True) model_int8 = torch.quantization.convert(model_fp32_prepared.eval(), inplace=False) model_int8.load_state_dict(state_dict['model']) model_ar = model_int8 model_ar.eval()
> 
> ### Versions
> torch_version: 2.1.2+cu121 python:3.10
> 
> cc [@jerryzh168](https://github.com/jerryzh168) [@jianyuh](https://github.com/jianyuh) [@raghuramank100](https://github.com/raghuramank100) [@jamesr66a](https://github.com/jamesr66a) [@vkuzo](https://github.com/vkuzo) [@jgong5](https://github.com/jgong5) [@Xia-Weiwen](https://github.com/Xia-Weiwen) [@leslie-fang-intel](https://github.com/leslie-fang-intel) [@msaroufim](https://github.com/msaroufim)

I am facing the same using when applying quantization to the wav2vec2 model, do you finally solve the issue

**Comment by wululu66** [comment]
> > ### 🐛 描述错误
> > QAT 训练后，会报告以下错误以进行推理：NotImplementedError：无法使用来自“CPU”后端的参数运行“quantized：：linear”。这可能是因为此后端不存在 Operator，或者在选择性/自定义构建过程中被省略（如果使用自定义构建）。如果您是在移动设备上使用 PyTorch 的 Facebook 员工，请访问 https://fburl.com/ptmfixes 了解可能的解决方案。'quantized：：linear' 仅适用于以下后端：[QuantizedCPU， QuantizedCUDA， BackendSelect， Python， FuncTorchDynamicLayerBackMode， Functionalize， Named， Conjugate， Negative， ZeroTensor， ADInplaceOrView， AutogradOther， AutogradCPU， AutogradCUDA， AutogradXLA， AutogradMPS， AutogradXPU， AutogradHPU， AutogradLazy， AutogradMeta， Tracer， AutocastCPU， AutocastCUDA， FuncTorchBatched， FuncTorchVmapMode， Batched， VmapMode， FuncTorchGradWrapper， PythonTLSSnapshot，FuncTorchDynamicLayerFrontMode、PreDispatch、PythonDispatcher 的 FrontMode。
> > 训练代码集：model.modulexx.ar_predict_layer.qconfig = torch.ao.quantization.get_default_qat_qconfig（'x86'） [并设置 quant 和 dequant] model_quant = torch.ao.quantization.prepare_qat（model， inplace=True） model.train（） ....保存： torch.save（torch.ao.quantization.convert（model.cpu（）.eval（）， inplace=False）.state_dict（）， filename）
> > 推理代码集： state_dict = torch.load（filename） model.ar_predict_layer.qconfig = torch.ao.quantization.get_default_qat_qconfig（'x86'） model_fp32_prepared = torch.quantization.prepare_qat（model_ar， inplace=True） model_int8 = torch.quantization.convert（model_fp32_prepared.eval（）， inplace=False） model_int8.load_state_dict（state_dict['model']） model_ar = model_int8 model_ar.eval（）
> > ### 版本
> > torch_version：2.1.2+cu121 python：3.10
> > cc [@jerryzh168](https://github.com/jerryzh168) [@jianyuh](https://github.com/jianyuh) [@raghuramank100 @jamesr66a](https://github.com/raghuramank100)  [@vkuzo](https://github.com/vkuzo) [@jgong5 @Xia-Weiwen](https://github.com/Xia-Weiwen) [@leslie-方-英特尔](https://github.com/leslie-fang-intel)[@msaroufim](https://github.com/msaroufim)
> 
> 我在将量化应用于 wav2vec2 模型时面临同样的问题，你最终解决了这个问题吗

您好我也遇到了同样的问题请问你解决了吗

**Comment by jerryzh168** [comment]
the quantization stack using `quantized::linear_prepack` (eager mode quantization, fx graph mode quantization) are all deprecated btw: https://docs.pytorch.org/docs/stable/quantization.html, please move to pt2e flow that's linked above by Weiwen.
