### ISSUE TITLE
post grad batch linear fusion performs unsafe optimization when inlining nn modules

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#128569]
### 🐛 Describe the bug

``` TORCHDYNAMO_INLINE_INBUILT_NN_MODULES=1 python test/inductor/test_group_batch_fusion.py -k test_batch_linear_post_grad_fusion```

When inlining nn modules the batch linear fusion performs an unsafe transformation causing the following error https://www.internalfb.com/phabricator/paste/view/P1411079955

### Versions

5d8c7f39d46699d8f8e92512309ea3499a29c08a

cc @ezyang @anijain2305 @chauhang

**Comment by mlazos** [comment]
cc @bdhirsh

**Comment by eellison** [comment]
@bdhirsh you had a pr around this - not sure if exactly same one bug assigning to you, feel free to unassign

**Comment by mlazos** [comment]
> @bdhirsh you had a pr around this - not sure if exactly same one bug assigning to you, feel free to unassign

Yeah it's the same bug
