### ISSUE TITLE
[inductor][cpu]hf_BigBird AMP multiple thread static/dynamic shape default/CPP wrapper performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#128513]
### 🐛 Describe the bug

<p>hf_BigBird AMP multiple thread dynamic shape default wrapper performance regression</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>hf_BigBird</td>
      <td>multiple</td>
      <td>1.0</td>
      <td>0.930308</td>
      <td>0.109184741</td>
      <td>0.101575438030228</td>
      <td>70.336838</td>
      <td>1</td>
      <td>1.072436</td>
      <td>0.09113455999999999</td>
      <td>0.09773598298815998</td>
      <td>68.87344</td>
      <td>0.87</td>
      <td>0.96</td>
      <td>0.83</td>
      <td>0.98</td>
    </tr>
  </tbody>

</table>

3964a3ec7351fb51460351d8914e562817d8cd72
```
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance torchbench hf_BigBird amp first dynamic default
Testing with dynamic shapes.
Testing with freezing on.
multi-threads testing....
loading model: 0it [00:00, ?it/s]Input ids are automatically padded from 819 to 832 to be a multiple of `config.block_size`: 64
loading model: 0it [00:02, ?it/s]
cpu  eval  hf_BigBird
running benchmark: 100%|███████████████████████████████████████████████████████████| 50/50 [00:10<00:00,  4.69it/s]
0.908x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,hf_BigBird,1,0.908421,111.481460,71.164231,0.934827,278.479667,297.894298,3033,80,61,6,0,0,66
```
31c3fa6cf57cdea99f2da1bd106c7bfaff2dd0bd
```
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance torchbench hf_BigBird amp first dynamic default
Testing with dynamic shapes.
Testing with freezing on.
multi-threads testing....
loading model: 0it [00:00, ?it/s]Input ids are automatically padded from 819 to 832 to be a multiple of `config.block_size`: 64
loading model: 0it [00:02, ?it/s]
cpu  eval  hf_BigBird
running benchmark: 100%|███████████████████████████████████████████████████████████| 50/50 [00:09<00:00,  5.26it/s]
1.062x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,hf_BigBird,1,1.062049,91.970568,53.181309,0.935239,278.471885,297.754624,3033,80,61,6,0,0,66
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>d6015d42</td>
      <td>main</td>
      <td>d6015d42</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>df43d5843edd9abd95d2c039670bce51375d9c06</td>
      <td>main</td>
      <td>c19ad112f65ab88af3eeb319dda0675c076b0b67</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.4.0a0+b829e93</td>
      <td>main</td>
      <td>2.2.0a0+1980f8a</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference performance torchbench hf_BigBird amp first dynamic default
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/3964a3ec7351fb51460351d8914e562817d8cd72
[torchbench-hf_BigBird-inference-amp-dynamic-default-multiple-performance-drop_guilty_commit.log](https://github.com/user-attachments/files/15807485/torchbench-hf_BigBird-inference-amp-dynamic-default-multiple-performance-drop_guilty_commit.log)
cc @ezyang @anijain2305 @chauhang @WeizhuoZhang-intel @chuanqi129

**Comment by zxd1997066** [comment]
Hi @ezyang  , according to the bisect search log and test results, the PR https://github.com/pytorch/pytorch/pull/126905 may introduce this AMP performance regression issue on CPU, could you please help to double check it?

**Comment by ezyang** [comment]
If you have the run ready to go, a TORCH_TRACE log of before and after would be very helpful

**Comment by ezyang** [comment]
.

**Comment by leslie-fang-intel** [comment]
Hi @ezyang, thanks for looking into this issue. Capture the log with `TORCH_LOGS="+schedule,+inductor,+output_code"`. Please let me know if any other log needed.

- Before regression: https://gist.github.com/leslie-fang-intel/00563f35f7edd91369073672e79b1961#file-before_regression-log
- After regression: https://gist.github.com/leslie-fang-intel/00563f35f7edd91369073672e79b1961#file-after_regression-log

**Comment by ezyang** [comment]
I would much prefer a TORCH_TRACE log, thanks

**Comment by leslie-fang-intel** [comment]
Sure, @ezyang 

- Here are the torch_Trace before regression: https://gist.github.com/leslie-fang-intel/193bb1ec096e619ff441484f94a0e2a3#file-before-regression-log

- After regression: https://gist.github.com/leslie-fang-intel/193bb1ec096e619ff441484f94a0e2a3#file-after-regression-log

**Comment by ezyang** [comment]
tlparse before: https://ezyang.github.io/tlparse_reports/issue128513-before/index.html
tlparse after: https://ezyang.github.io/tlparse_reports/issue128513-after/index.html

**Comment by ezyang** [comment]
The substantive change appears to be in the compilation of 15/0 (and other recompiles; btw, it looks like frame 15 is recompiling because the NN module id is changing, consider following the advice at https://docs.google.com/document/d/1y5CRfMLdwEoF1nTk9q8qEu1mgMUuUtvhklPKJ2emLU8/edit#heading=h.rcby0pkxe7qy )

Here is a sample before/after: https://ezyang.github.io/tlparse_reports/issue128513-before/15_0_0/inductor_output_code_cecdqikc3lwv5y75e7wzb3gq44icgnosa6jeiosotravjk6kd573_70.html https://ezyang.github.io/tlparse_reports/issue128513-after/15_0_0/inductor_output_code_c6icdm2jkh5xkxrgpyz2vtbd5oehca45dznneh7n63f3sirkkptn_70.html

Before, we have:

```
                    auto tmp0 = out_ptr12[static_cast<long>((33L*x0) + (33L*(c10::div_floor_integer((x2 + (64L*x1)), 135168L))) + (c10::div_floor_integer((x2 + (64L*x1)), 4096L)))];
                    auto tmp13 = out_ptr12[static_cast<long>(30L + (33L*x0) + (33L*(c10::div_floor_integer((122880L + x2 + (64L*x1)), 135168L))) + (c10::div_floor_integer((x2 + (64L*x1)), 4096L)))];
                    auto tmp1 = (13L*x0) + (26L*(c10::div_floor_integer((x2 + (64L*x1)), 135168L)));
```

After, we have:

```
                    auto tmp0 = out_ptr12[static_cast<long>((33L*(c10::div_floor_integer((x2 + (64L*x1) + (135168L*x0)), 135168L))) + (c10::div_floor_integer((x2 + (64L*x1)), 4096L)))];
                    auto tmp13 = out_ptr12[static_cast<long>((33L*(c10::div_floor_integer((122880L + x2 + (64L*x1) + (135168L*x0)), 135168L))) + (c10::div_floor_integer((122880L + x2 + (64L*x1)), 4096L)))];
                    auto tmp1 = 13L*(c10::div_floor_integer(((33L*(c10::div_floor_integer((x2 + (64L*x1) + (135168L*x0)), 135168L))) + (c10::div_floor_integer((x2 + (64L*x1)), 4096L))), 33L));
```

**Comment by ezyang** [comment]
Note, on main, thanks to inline NN modules, there is only one frame https://interncache-all.fbcdn.net/manifold/tlparse_reports/tree/logs/.tmpynxxgQ/18_0_0/inductor_output_code_c6h3i3je7vcbrmppa2lyz7qn5rcsshhjxa4ngdt5du7jpabpxop5_61.html

**Comment by ezyang** [comment]
On main, I get a speedup > 1: 1.121093 when I benchmark it myself. Additionally, the relevant generated code looks good: https://gist.github.com/ezyang/f59f52a1e5cfafe842bd5589656af7da

Please check if this is still a regression.

**Comment by leslie-fang-intel** [comment]
Hi @zxd1997066, could you help to check the performance data with latest main as comment above?

**Comment by zxd1997066** [comment]
Yes, the regression is fixed according to the latest report.
