### ISSUE TITLE
Be able to dynamically disable a kernel for a custom op

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#128621]
Useful for when custom ops have a default implementation vs a backend implementation. Sometimes we want to disable the backend implementation for testing/benchmarking purposes.

**Comment by yushangdi** [comment]
@zou3519 Maybe something like this?

```python
@custom_op("mylib::f", mutates_args=())
def f(x: Tensor) -> Tensor:
    return torch.zeros(1)

print(f(torch.randn(1))) # tensor([0.])

@f.register_kernel("cpu")
def _(x):
    return torch.ones(1)

print(f(torch.randn(1))). # tensor([1.])

f.disable("cpu")
print(f(0)) # tensor([0.])
```

**Comment by zou3519** [comment]
@dacorvo, going back to the your use case: do you want to be able to re-enable the kernel? If so, we want something more like f.enable_kernel("cpu", enabled=True/False)

**Comment by dacorvo** [comment]
@zou3519 Yes it should be something temporary. Using a context manager would be great: this is exactly how I had manually implemented it (only it was not so fine-grained but more like disabling a whole library).

**Comment by yushangdi** [comment]
> @zou3519 Yes it should be something temporary. Using a context manager would be great: this is exactly how I had manually implemented it (only it was not so fine-grained but more like disabling a whole library).

@dacorvo It's added now by https://github.com/pytorch/pytorch/pull/130190 :)

**Comment by dacorvo** [comment]
Thank you very much ! I really like the design of the custom ops by the way: very elegant and concise.
