### ISSUE TITLE
cuda12.1-py3.10-gcc9-sm80 / test (inductor_torchbench_smoketest_perf, 1, 1, linux.gcp.a100) has long queue times

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#128627]
This job seems to have long queue times. Example (3 hours)

<img width="1260" alt="image" src="https://github.com/pytorch/pytorch/assets/5652049/abae1ea5-447b-4007-bc4d-5bdc58f3f40b">

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
From what I see, this change https://hud.pytorch.org/hud/pytorch/pytorch/03467b3fed2fe395cb547b64e2d2bb268dc10cfd/1?per_page=50&name_filter=A100 doubles the amount of time from 20+ to 40+ minutes.  This, together https://github.com/pytorch/pytorch/blob/main/.github/workflows/inductor-cu124.yml and maybe an increase number of PR with `ciflow/inductor`, is contributing to the long queue.

**Comment by clee2000** [comment]
I am going to close this for now since Huy moved it to periodic.  Please re open if you see long queues again
