### ISSUE TITLE
2.6.0 Released a second time on the same version breaking production customers

### ISSUE THREAD

**Issue by skier233** [pytorch/pytorch#128653]
### 🐛 Describe the bug

I have production paying customers using pytorch instantiated in conda environments using a conda environment file such as:
name: ai_model_server
```
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch=2.3.0
  - torchvision=0.18.0
  - pytorch-cuda=12.1
```
It seems that a new "release" was made to pytorch 2.3.0 on top of an already existing release of 2.3.0 in conda. This "new" version of 2.3.0 seems to be incompatible with torchvision 0.18.0 which led to my customers getting errors after installing or upgrading their conda environment:
`RuntimeError: operator torchvision::nms does not exist
`

Writing new versions over top of existing releases seems like an antipattern to me as if I specify a specific version of pytorch, general software versioning dictates that a user who installed 2.3.0 2 years ago versus a user that installed 2.3.0 2 minutes ago should have the same software that works the same way.

For now I'm now scrambling to get a patch out to all my customers that updates their environment file to use pytorch=2.3.1 and torchvision=0.18.1.

Is there a way to ensure that this type of issue does not occur in the future?

### Versions

pytorch 2.6.0
torchvision 0.18.0

**Comment by manbehindthemadness** [comment]
Same problem here, upgrade scripts nuked my nVidia Orin AGX/NX deploys.

**Comment by atalman** [comment]
hi @skier233 : 2.6.0 Released a second time. Do you want to say 2.3.0 ?
The latest release version of pytorch on conda is 2.3.1:
https://anaconda.org/pytorch/pytorch/files?version=2.3.1

**Comment by manbehindthemadness** [comment]
I think you are correct, there is a versioning typo going on.

Furthermore, I resolved my issue by removing my hand compiled libraries and replacing them with the NVIDIA wheels located here: https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048

This is only a solution for my specific platform and environment. I suspect that the origin of this issue might be a change in the build procedure or versioning that hasn't made it into the documentation just yet. I would suggest (humbly) that the correct torchvision (and perhaps torchaudio) commits be added to the PyTorch submodules so they can just be crunched all at once so the versioning and what have you solves itself

**Comment by skier233** [comment]
> hi @skier233 : 2.6.0 Released a second time. Do you want to say 2.3.0 ? The latest release version of pytorch on conda is 2.3.1: https://anaconda.org/pytorch/pytorch/files?version=2.3.1
> 
> Here are our validation scripts for torch 2.3.1, torchvision : 0.18.1 https://github.com/pytorch/builder/actions/runs/9368729544/job/25798547076#step:12:6236

Yes 2.3.0. Made a typo in the post but everything is still relevant from the post. Updated to be more clear.

**Comment by atalman** [comment]
closing this since description is not accurate:
Release 2.3.0 binaries have all same dates: 
https://anaconda.org/pytorch/pytorch/files?version=2.3.0

Mon Apr 8 23:48:25 2024 - Tue Apr 9 03:48:12 2024 
This corresponds to the date when final RC was build: https://dev-discuss.pytorch.org/t/pytorch-release-2-3-0-final-rc-is-available/1995
