### ISSUE TITLE
Link https://pytorch.org/docs/stable/nn.html#torch.nn.EmbeddingBag may not exist anymore

### ISSUE THREAD

**Issue by raybellwaves** [pytorch/pytorch#128774]
### 📚 The doc issue

In https://pytorch.org/docs/stable/generated/torch.ao.nn.quantized.EmbeddingBag.html it says "please see https://pytorch.org/docs/stable/nn.html#torch.nn.EmbeddingBag for documentation".

https://pytorch.org/docs/stable/nn.html#torch.nn.EmbeddingBag  may not exist anymore as it opens to https://pytorch.org/docs/stable/nn.html.

Happy to make a PR to fix this.

### Suggest a potential alternative/fix

Remove that snippet?

Find the updated link?

cc @svekars @brycebortree

**Comment by malfet** [comment]
Yeah, it should point to https://pytorch.org/docs/stable/generated/torch.nn.EmbeddingBag.html
