### ISSUE TITLE
Missing support for deterministic algorithm for torch.float8_e4m3fn and torch.float8_e5m2

### ISSUE THREAD

**Issue by NicoleMayer** [pytorch/pytorch#128733]
### 🐛 Describe the bug

The current implementation of PyTorch does not support deterministic algorithms for the fp8_e4m3 and fp8_e3m4 formats.

```
>>> import torch
>>> torch.__version__
'2.4.0a0+git65aa16f'
>>> torch.use_deterministic_algorithms(True)
>>> a = torch.rand(64, dtype=torch.bfloat16)
>>> a.to(torch.float8_e4m3fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "fill_empty_deterministic_" not implemented for 'Float8_e4m3fn'
>>> a.to(torch.float8_e5m2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "fill_empty_deterministic_" not implemented for 'Float8_e5m2'
```

### Versions

Collecting environment information...
PyTorch version: 2.4.0a0+git3174e6c
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.34

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-0_fbk12_zion_11583_g0bef9520ca2b-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100
GPU 1: NVIDIA H100
GPU 2: NVIDIA H100
GPU 3: NVIDIA H100
GPU 4: NVIDIA H100
GPU 5: NVIDIA H100
GPU 6: NVIDIA H100
GPU 7: NVIDIA H100

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          384
On-line CPU(s) list:             0-383
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 9654 96-Core Processor
CPU family:                      25
Model:                           17
Thread(s) per core:              2
Core(s) per socket:              96
Socket(s):                       2
Stepping:                        1
Frequency boost:                 enabled
CPU(s) scaling MHz:              100%
CPU max MHz:                     2400.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4792.45
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d
Virtualization:                  AMD-V
L1d cache:                       6 MiB (192 instances)
L1i cache:                       6 MiB (192 instances)
L2 cache:                        192 MiB (192 instances)
L3 cache:                        768 MiB (24 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-95,192-287
NUMA node1 CPU(s):               96-191,288-383
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable, IBPB: conditional, IBRS_FW, STIBP: always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] optree==0.11.0
[pip3] torch==2.4.0a0+git3174e6c
[pip3] torchao==0.3.0
[pip3] triton==2.2.0
[pip3] triton-nightly==3.0.0.post20240424212437
[conda] blas                      1.0                         mkl    anaconda
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-include               2023.1.0         h06a4308_46344  
[conda] mkl-service               2.4.0           py310h5eee18b_1    anaconda
[conda] mkl_fft                   1.3.8           py310h5eee18b_0    anaconda
[conda] mkl_random                1.2.4           py310hdb19cb5_0    anaconda
[conda] numpy                     1.26.0          py310h5f9d8c6_0    anaconda
[conda] numpy-base                1.26.0          py310hb5e798b_0    anaconda
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] torch                     2.4.0a0+git3174e6c          pypi_0    pypi
[conda] torchao                   0.3.0                    pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi
[conda] triton-nightly            3.0.0.post20240424212437          pypi_0    pypi

cc @yanbing-j @vkuzo @albanD @kadeng

**Comment by malfet** [comment]
Let me grab this one, unless @vkuzo is already working on it

**Comment by vkuzo** [comment]
finalizing the PR now, sorry, needed this urgently

**Comment by vkuzo** [comment]
https://github.com/pytorch/pytorch/pull/128744
