### ISSUE TITLE
_foreach_vector_norm

### ISSUE THREAD

**Issue by ad8e** [pytorch/pytorch#128738]
### 🚀 The feature, motivation and pitch

This is useful for Karras's "forced weight normalization", from [EDM2](https://arxiv.org/abs/2312.02696).

![edm2](https://github.com/pytorch/pytorch/assets/19739817/3f0b7339-b050-4ed2-bb05-340b309beb25)

With some minor linear algebra, we avoid doing the double-normalization in the forward, and instead handle these considerations in the optimizer. So the user gets param-scaled LRs, as in AdamWScale. This is somewhat faster than what Karras does.

The name is up to you, whether it's `_foreach_vector_norm` or `_foreach_rmsnorm` or `_foreach_2norm` or something else. I only care about the 2-norm, which is the default `linalg.vector_norm` behavior. Also, the in-place version is not useful to me, only the return-value version.

My optimizer seems to result in more TFLOPS than PyTorch AdamW despite doing more work, for the likely reason that I only need 1 param group instead of 3. (I haven't checked carefully though.)

### Alternatives

I currently write:
```
current_norms = [torch.linalg.vector_norm(p) for p in params]
```
With the new feature, I would write:
```
current_norms = torch._foreach_vector_norm(params)
```

cc @crcrpar @mcarilli @janeyx99

**Comment by awgu** [comment]
`_foreach_norm`?

**Comment by ad8e** [comment]
You're right, I didn't spot that.
