### ISSUE TITLE
torch.jit.OrderedParameterDict object has no attribute 'copy', when call nn.DataParallel.replicate 

### ISSUE THREAD

**Issue by unlimblue** [pytorch/pytorch#12875]
## To Reproduce

1. prepare a ScriptModule instance
2. use nn.Dataparallel with it on multi-gpus env
3. get AttributeError: 'OrderedParameterDict' object has no attribute 'copy'

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Ubuntu 18
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6
 - CUDA/cuDNN version: 9.0

## Additional context

```
# nn/parallel/replicate.py line 21
    modules = list(network.modules())
    module_copies = [[] for device in devices]
    module_indices = {}

    for i, module in enumerate(modules):
        module_indices[module] = i
        for j in range(num_replicas):
            replica = module.__new__(type(module))
            replica.__dict__ = module.__dict__.copy()
            **replica._parameters = replica._parameters.copy()**
            replica._buffers = replica._buffers.copy()
            replica._modules = replica._modules.copy()
            module_copies[j].append(replica)
```

**Comment by zdevito** [comment]
We now have jit-specific code for module replication in data parallel so this should be fixed. If it isn't please reopen the issue.
