### ISSUE TITLE
torch.nn.functional works incorrectly with backward() for non-scalars

### ISSUE THREAD

**Issue by olyaromanyuk** [pytorch/pytorch#12871]
## 🐛 Bug

Trying to calculate gradients with respect to input for a simple network that processes batches. Backpropagation crashes with RuntimeError: output and gradOutput have different number of elements: output[3 x 1] has 3 elements, while gradOutput[1 x 1] has 1 elements at /pytorch/aten/src/THCUNN/generic/Sigmoid.cu:22.
Same backpropagation without sigmoid as a last step in the network works ok.

## To Reproduce

Here is a minimal example:
```
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

    def forward(self,x):
        y = torch.sum(x, dim=1)
        y = torch.sum(y, dim=1, keepdim=True)
        print(y)
        y=F.sigmoid(y)
        return y


model = Model()
model.cuda()

x = Variable(torch.zeros(3, 5, 10), requires_grad=True)
x_cuda = x.cuda()
print(x)

y = model(x_cuda)

print(y.shape)
print(y)
y.backward(torch.cuda.FloatTensor([[1]]))

print(x.grad.shape)
print(x.grad)
```

1. Run the code above. Execution ends with the following error:
```
Traceback (most recent call last):
  File "/home/olha/experiments/non_scalar_gradients.py", line 33, in <module>
    y.backward(torch.cuda.FloatTensor([[1]]))
  File "/home/olha/.local/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/olha/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: output and gradOutput have different number of elements: output[3 x 1] has 3 elements, while gradOutput[1 x 1] has 1 elements at /pytorch/aten/src/THCUNN/generic/Sigmoid.cu:22
```
2.  Run the same code, but comment out the line y=F.sigmoid(y). Code runs ok, gradients are correct.

## Environment
 - PyTorch Version 0.4.0
 - Ubuntu 18.04
 - How you installed PyTorch - pip
 - Python version 3.6
 - CUDA 9.2/cuDNN 7.3 

## Additional context

In the code I use sigmoid, but the issue is not limited to it. I've tried tanh with the same results.

**Comment by zou3519** [comment]
Try `y.backward(torch.ones_like(y))`

**Comment by lawpdas** [comment]
Have you solved this problem?

**Comment by zou3519** [comment]
.backward(..) should not broadcast. You need to pass in a tensor (gradOutput) of the correct shape.
