### ISSUE TITLE
UNSTABLE inductor-cu124 / cuda12.4-py3.10-gcc9-sm86 / test (inductor_torchbench)

### ISSUE THREAD

**Issue by PaliC** [pytorch/pytorch#128851]
Numpy 2.0 update is causing this test to fail
Context: https://github.com/pytorch/pytorch/issues/128845

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by huydhn** [comment]
This doesn't look unstable anymore, so I'm closing this
