### ISSUE TITLE
UNSTABLE inductor-cu124 / cuda12.4-py3.10-gcc9-sm86 / test (aot_inductor_torchbench)

### ISSUE THREAD

**Issue by PaliC** [pytorch/pytorch#128849]
Numpy 2.0 update is causing this test to fail
Context: https://github.com/pytorch/pytorch/issues/128845

cc @seemethere @malfet @pytorch/pytorch-dev-infra @desertfire @chenyang78

**Comment by huydhn** [comment]
This doesn't look unstable anymore, so I'm closing this
