### ISSUE TITLE
inductor_torchbench_perf jobs are broken due to numpy 2.0 update

### ISSUE THREAD

**Issue by PaliC** [pytorch/pytorch#128845]
## Current Status
*Status could be: ongoing

## Error looks like
Torch Bench testing is broken with errors that look like https://github.com/pytorch/pytorch/actions/runs/9534138639/job/26278709111

## Incident timeline (all times pacific)
Inductor CI has been broken since 5:41 PM PT on June 14, 2024.
It was detected the next day and root caused the morning on June 17th.

## User impact
The affected inductor ci jobs (those related to torchbench perf) shall be marked as unstable until this issue is mitigated.

## Root cause
We suspect it's due to the numpy 2.0 update. (https://numpy.org/devdocs/release/2.0.0-notes.html) 

## Mitigation
Ongoing

Current plan is for [eellison](https://github.com/eellison) to pin numpy for torchbench workflows

## Prevention/followups
TBD

**Comment by xuzhao9** [comment]
This can be fixed by the following PRs:

PyTorch PR: https://github.com/pytorch/pytorch/pull/128879
TorchBench PR: https://github.com/pytorch/benchmark/pull/2311

**Comment by huydhn** [comment]
I'll close those unstable issue once trunk recovers
