### ISSUE TITLE
Segmentation fault when summing uint8 tensor

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#12887]
Hi. I'm using PyTorch 0.5.0a0+09896d1

This code:

```python
size = 3*1000*1000*1000
a = torch.LongTensor(size).random_(2)
(a == a).sum()
```
is returning me a "Segmentation fault". If instead I do `(a.numpy() == a.numpy()).sum()`, it works. Also, the problem does not occur with `size = 1000*1000*1000`.

EDIT: a more efficient way to reproduce the bug:
```python
size = 3*1000*1000*1000
a = torch.ByteTensor(size).random_(2)
(a == 0).sum()
```

**Comment by alexcaveny** [comment]
I would guess it has less to do with the operation and more to do with the size of the tensor. 

On my machine `a.size()` causes an overflow error stating `OverflowError: Python int too large to convert to C long`, but `a.numpy().shape` works correctly. I still get the overflow error when using different tensor types. Using `ByteTensor` to define `a` only uses ~3GB of memory compared to ~22GB, but still throws the same error. And if I set `size=1000*1000*1000`, then `a.size()` starts working again for both `ByteTensor` and `LongTensor`.

**Comment by glample** [comment]
@HKervadec even though `a` is a `int64` tensor, `a == a` becomes a `uint8` tensor, so my title is correct.

To give a bit of context, I typically store a dataset of concatenated sentences in a single vector `a`, then I compute the number of unknown words by doing: `(a == UNK_IDX).sum()`. I currently do: `(a.numpy() == UNK_IDX).sum()` to avoid the issue, but the error shouldn't be there in PyTorch.

**Comment by zou3519** [comment]
I can't reproduce this on master.

**Comment by davidmascharka** [comment]
@zou3519 it may not crash on the machine you're running on (it doesn't on mine either) but the sum on a `tensor` eats almost an order of magnitude more memory than the sum on a NumPy array:

``` python
import torch
a = torch.empty(3 * 1000**3, dtype=torch.uint8).byte()
(a == 0).sum()
```

eats 25 GB of memory while

``` python
import torch
a = torch.empty(3 * 1000**3, dtype=torch.uint8).byte()
(a.numpy() == 0).sum()
```

takes only 3 GB.

**Comment by mruberry** [comment]
This issue and the increase memory usage seem to be resolved on recent builds of PyTorch. If you're still seeing either issue with PyTorch 1.7 or later please open a new issue.
