### ISSUE TITLE
Performance impact of pre-division.

### ISSUE THREAD

**Issue by erhoo82** [pytorch/pytorch#128918]
https://github.com/pytorch/pytorch/blob/9e8443b56f5a83877803be3ba43f7941841904c9/torch/distributed/fsdp/_runtime_utils.py#L841

Is the pre-gradient division needed for a numerical reason?
Since pre-division is done before sharding, the op cost is quite expensive.

**Comment by ad8e** [comment]
I'm surprised it's expensive, but this is useful to keep the floating point numbers within a good range. For example: if the grad scale is 1, and world size is 64, then you divide by 8 before reducing, then reduce, then divide by 8 again, so the min and max scales are 1/8 and 8.

**Comment by erhoo82** [comment]
I see. Then, what about doing only the pre-division?

Also, can we add an option to do `average-reduction` than `sum-reduction` in the reduce-scatter, so we can avoid having a separate division op on the un-sharded grad tensor?

**Comment by awgu** [comment]
The splitting of division into pre and post is mainly needed for fp16. For FSDP2, we do not do this anymore, and indeed it is more efficient.

**Comment by erhoo82** [comment]
Thanks, @awgu for the info.
May I ask the rough timeline for having FSDP2 in the upstream?

**Comment by awgu** [comment]
FSDP2 is already in the `pytorch` repo right now as `torch.distributed._composable.fsdp.fully_shard`. For example, we are using it in torchtitan (https://github.com/pytorch/torchtitan, https://github.com/pytorch/torchtitan/blob/main/docs/fsdp.md).

**Comment by erhoo82** [comment]
Yes, I thought `torchtitan` is a research repo. So, is FSPD2 will continuously be supported via `torchtitan` or is there a plan to migrate to `torch` main repo?

**Comment by awgu** [comment]
Sorry for the confusion @erhoo82 . The actual code of FSDP2 is in the `pytorch` main repo. We just call it from `torchtitan`. There are no FSDP2 features that are only existing in `torchtitan`; the code is all in `pytorch` repo.

**Comment by erhoo82** [comment]
I see. So, `torch.distributed._composable.fsdp.fully_shard` is the FSDP2 API?
I was confused as `torchtitan` is a separate repo.

**Comment by awgu** [comment]
> I see. So, torch.distributed._composable.fsdp.fully_shard is the FSDP2 API?

Yes, that is correct!
