### ISSUE TITLE
Spurious "socket cannot be initialized" error messages

### ISSUE THREAD

**Issue by mwlon** [pytorch/pytorch#128998]
### 🐛 Describe the bug

When using nodes connected by IPv6, training proceeds correctly, but emits these misleading messages at log level error:

`2024-05-22 06:25:20.552227-04:00 Error From <host>: [W socket.cpp:436] [c10d] The server socket cannot be initialized on [::]:22010 (errno: 97 - Address family not supported by protocol).`

There's no good way I know of to filter these out, since they come from C++, and I don't want to ignore error messages.

The logic causing this is in [socket.cpp](https://github.com/pytorch/pytorch/blob/77830d509fcae41be37f5b3a2fa05faabc778e29/torch/csrc/distributed/c10d/socket.cpp#L579): we try all possible addresses returned by `getaddrinfo`, logging errors if any of them fail, but returning true if any of them succeed. I think the fix is simple: just move the error message into the failure case of `tryListen(int family)` instead.

### Versions

2.3.1 (and earlier)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

**Comment by Robertwahl** [comment]
I know C++ and network sockets so I'd start on this bug.

**Comment by mwlon** [comment]
@Robertwahl I'm a little bit confused by your response - the problem here is not the formatting of the IP address, but the fact that we give an error message at all. If we are using `AF_UNSPEC`, then it makes sense it'll try different addresses until one works, and we shouldn't give error messages until we know they all fail. I believe it's trying IPv4, failing, trying IPv6, and then succeeding.

Specifically I think we should replace [this line](https://github.com/pytorch/pytorch/blob/77830d509fcae41be37f5b3a2fa05faabc778e29/torch/csrc/distributed/c10d/socket.cpp#L593) with [an error message here](https://github.com/pytorch/pytorch/blob/77830d509fcae41be37f5b3a2fa05faabc778e29/torch/csrc/distributed/c10d/socket.cpp#L585).

That said, I'm not very familiar with the Linux calls here. Does this make sense?

**Comment by wconstab** [comment]
One other point is that the log code is written as C10_DEBUG() so it is intended to not show up for users unless they turn on debug logging. However I see it printing as 'W' (warning) log level in your paste, which suggests something is wrong with our logging macro.  I'd like to first see if we can fix that and otherwise we can consider your suggestion of not logging until true failure.

**Comment by wconstab** [comment]
Oh yea- I looked at L580 instead of the line that actually prints your warning.  Maybe we should change that recordError to a debug print and add a new error if all attempts fail?

**Comment by mwlon** [comment]
That sounds good to me.

**Comment by mwlon** [comment]
@Robertwahl will you be working on this, or am I expected to make a PR?

**Comment by Robertwahl** [comment]
Yes, I'm sorry it's taking longer

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mwlon** [comment]
I'll make a PR for this

**Comment by mwlon** [comment]
@Robertwahl @wconstab @albanD I've had the PR out for 2 months, and I've pinged the assigned people multiple times. Could you please get someone to review? It's quite simple.

**Comment by wconstab** [comment]
looks like someone beat me to it. ping again if you have any issues landing

**Comment by mwlon** [comment]
@Robertwahl @wconstab @albanD could I get this merged please?

**Comment by fduwjj** [comment]
I checked your PR, after all CI finished, it should be merged @mwlon
