### ISSUE TITLE
Inquiry Regarding PyTorch Data Mirroring and Proxy Services

### ISSUE THREAD

**Issue by 89ao** [pytorch/pytorch#128940]
### 🚀 The feature, motivation and pitch

Dear PyTorch Team,

I trust this message finds you well.

We'd like to set a pytorch public mirror here in china aims to enhancing the accessibility and speed of technical resources for the developer community. We are considering offering a mirror and proxy service for the PyTorch datasets hosted at https://download.pytorch.org/whl/ to improve network performance for users.

We understand the importance of quick and reliable access to PyTorch's extensive machine learning resources, and we believe that by providing a mirror and proxy service, we can significantly reduce latency and offer a more robust experience for users in our region.

Here are the key points we would like to discuss with you:

1. How can I get the permission to mirror the content found at the aforementioned URL.
2. Any technical requirements or guidelines you may have for parties mirroring PyTorch data.Such as advice of how to sync the whole repository( for example rsync?).
3. How can we stay updated of PyTorch informations and updates.

Our goal is to provide this service free of charge to the opensource users. We are more than willing to adhere to any terms of service or usage policies that you may have in place.

We are looking forward to the possibility of collaborating with the PyTorch team to ensure that our services are in line with your goals and expectations.

Please let us know if this is something that is feasible and what steps we need to take to move forward. Your guidance and support would be greatly appreciated.

Thank you for considering our request. We eagerly await your response.

Best regards,

motor

cc @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
download.pytorch.org is backed by CloudFront, which to the best of my knowledge is available in China, see https://docs.amazonaws.cn/en_us/aws/latest/userguide/cloudfront.html

**Comment by ptrblck** [comment]
Also double-post from [here](https://discuss.pytorch.org/t/inquiry-regarding-pytorch-data-mirroring-and-proxy-services/204837/2?u=ptrblck) raising security concerns.

**Comment by 89ao** [comment]
Thanks a lot @malfet and @ptrblck !
Our expectation here is only to provide services externally in a way of regular synchronization or accessing proxies, so there will be no modifications. Refer to other repositories https://mirrors.cloud.tencent.com/. According to the message from malfet, does it mean that users in mainland China can directly use the domain name of pytorch https://download.pytorch.org/ to enjoy the acceleration brought by CDN?

**Comment by malfet** [comment]
@89ao download.pytorch.org is backed by `s3://pytorch` bucket which should be publicly accessible by anyone with Amazon account
