### ISSUE TITLE
[Dynamo x torch_function] methods on torch_function objects require id_match guards, causing recompiles

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#128964]
```py
import torch

class NJT:
    def __repr__(self):
        return f"NJT(shape={self.shape})"

    def __init__(self, values, offsets):
        self._values = values
        self._offsets = offsets

    def sin(self):
        return torch.sin(self)

    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}
        if func == torch.sin:
            self = args[0]
            return NJT(func(self._values), self._offsets)
        if func == torch.mul:
            x, y = args
            assert isinstance(x, NJT) and isinstance(y, NJT)
            return NJT(torch.mul(x._values, y._values), x._offsets)
        raise AssertionError("not implemented")

values1 = torch.randn(10, 3, 4, requires_grad=True)
values2 = torch.randn(10, 3, 4, requires_grad=True)
values3 = torch.randn(10, 3, 4, requires_grad=True)
values4 = torch.randn(10, 3, 4, requires_grad=True)
offsets = torch.tensor([0, 3, 10])
njt1 = NJT(values1, offsets)
njt2 = NJT(values2, offsets)
njt3 = NJT(values1, offsets)
njt4 = NJT(values2, offsets)

@torch.compile(backend="eager", fullgraph=True)
def f(x):
    return x.sin()

res = f(njt1)
res = f(njt2)
```

TORCH_LOGS=recompiles with the above shows a recompile due to the object id being different:
```
V0618 11:17:37.070879 8524823232 torch/_dynamo/guards.py:2598] [0/1] [__recompiles] Recompiling function f in /Users/rzou/pt/dev/foo.py:37
V0618 11:17:37.070879 8524823232 torch/_dynamo/guards.py:2598] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0618 11:17:37.070879 8524823232 torch/_dynamo/guards.py:2598] [0/1] [__recompiles]     - ___check_obj_id(L['x'], 4335972256)              
```

From some simple debugging it looks like this guard gets generated only if we call a method on the torch_function object. It makes sense that we would need to guard on the object (esp if the method changes from run-to-run), but maybe we should instead guard on the id of the methods called.

cc @ezyang @anijain2305 @chauhang @mlazos

**Comment by zou3519** [comment]
Debugging this some more, I think we're just installing the source wrong:

https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/torch_function.py#L91

the source shouldn't be var.source, it should be "type(var)"

**Comment by mlazos** [comment]
> Debugging this some more, I think we're just installing the source wrong:
> 
> [`main`/torch/_dynamo/variables/torch_function.py#L91](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/torch_function.py?rgh-link-date=2024-06-18T17%3A56%3A30Z#L91)
> 
> the source shouldn't be var.source, it should be "type(var)"

Yeah you're right! it should be `.__class__` or any correct source there is fine, want to submit a PR? I can if needed.

**Comment by zou3519** [comment]
Yeah I got it, thanks for confirming
