### ISSUE TITLE
[Dynamo] Maybe we shouldn't attempt to recursively compile inside of a frame if the frame hit cache limit

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#128954]
### 🐛 Describe the bug

Let's suppose you have a program structured like this:

```
def f(x):
  x = g1(x)
  x = g2(x)
  return g3(x)
```

Let's say we torch.compile f, and it is fully compileable, but for some reason, we are overspecializing and so every subsequent iteration to f generates a new compiled program.

What will happen in this case is we will hit the cache limit for f (OK), then we will stop compiling f (OK) and then we will start attempting to individually compile g1/g2/g3 (?!!?!?)

There are a few reasons why I think this is a suspicious thing to do:

1. This can result in compile time that scales with stack size and cache limit. Suppose the specialization point is deeply nested in a chain f-g-h-... We will compile f 8 times, g 8 times, h 8 times, and so forth, because each subsequent "smaller" frame still  has the specialization problem and is forcing recompilation. So we ultimately end up with SIZE STACK * CACHE SIZE recompiles
2. The inner recompiles greatly pollute the resulting stack traces; we may hit different Dynamo bugs when compiling the smaller pieces, it's easy to get distracted by mounds of compilation logs from the inner frames when the compilation of f is what we really care about.

So... maybe when a frame hits the recompilation limit, we should just recursively disable Dynamo when we fall back into eager. Thoughts?

### Versions

main

cc @gchanan @zou3519 @kadeng @msaroufim @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78

**Comment by anijain2305** [comment]
An emphatic +1 from me. 

Anytime I see recompilation issues, this distraction always causes problems. As you said, this inflates the compilation numbers so much that sometimes the compilation does not even finish. Seeing something similar in https://github.com/pytorch/pytorch/issues/121989

**Comment by masnesral** [comment]
Maybe not hi-pri, but marking for discussion

**Comment by jansel** [comment]
Yeah, doesn't seem like the current behavior is desirable.

**Comment by ezyang** [comment]
What's tricky about fixing this is you still have to modify the bytecode when you hit the cache limit: you need to disable on entry and reenable on exit. Probably the easiest is to just insert a little shim function that does this bit (no bytecode surgery needed, just eval it) and then calls into the real function (which has the original bytecode as is).

**Comment by ezyang** [comment]
Another occurrence of this: https://fb.workplace.com/groups/1075192433118967/posts/1480158559289017/

**Comment by ezyang** [comment]
Some more nuance from https://fb.workplace.com/groups/1075192433118967/permalink/1480158559289017/

The root cause of the issue is that bfloat16 not being supported causes us to skip compiling a graph entirely:

```
def _check_triton_bf16_support(graph: GraphLowering) -> None:
    def warn_and_skip(device) -> None:
        from torch._dynamo.exc import SkipFrame

        device_props = torch.cuda.get_device_properties(device)
        warnings.warn(
            f"{device_props.name} does not support bfloat16 compilation natively, skipping"
        )
        raise SkipFrame("BF16 is not supported")
```

But when we skip, we don't turn off Dynamo for recursive frames. So we're going to still try to compile the inside. Bad!

**Comment by williamwen42** [comment]
Fixed by https://github.com/pytorch/pytorch/issues/128954
