### ISSUE TITLE
Memory consumption of conv3d grows too quickly with certain input shapes.

### ISSUE THREAD

**Issue by baoleai** [pytorch/pytorch#128947]
### 🐛 Describe the bug

Memory consumption of conv3d grows too quickly with certain input shapes. 
For example like following, when tested on an 80G A100, with an input x of shape [1, 256, 4, 1090, 1922], the peak memory usage is only 17G. However, when x's shape is [1, 256, 5, 1090, 1922], it results in an out-of-memory (OOM) error directly:
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 161.37 GiB.`

test example:
```
import torch
from torch import nn

torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True

conv = nn.Conv3d(256, 64, kernel_size=(3, 3, 3), stride=(1, 1, 1)).to('cuda:0')

x = torch.rand([1, 256, 4, 1090, 1922], dtype=torch.float32).to('cuda:0')
# OOM when setting dim2 larger than 4.
# x = torch.rand([1, 256, 6, 1090, 1922], dtype=torch.float32).to('cuda:0')

torch.cuda.synchronize()
print(f"allocated: {torch.cuda.memory_allocated() / (1024**3)}, peak: {torch.cuda.max_memory_allocated() / (1024**3)}")
out = conv(x)
print(out.shape)
torch.cuda.synchronize()
print(f"allocated: {torch.cuda.memory_allocated() / (1024**3)}, peak: {torch.cuda.max_memory_allocated() / (1024**3)}")

# allocated: 7.993362903594971, peak: 7.993362903594971
# torch.Size([1, 64, 2, 1088, 1920])
# allocated: 8.98945665359497, peak: 16.98281955718994
```

### Versions

PyTorch version: 2.3.0
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-2ubuntu1~20.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.31

Python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 12.1.105

Nvidia driver version: 535.129.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0

cc @msaroufim @ptrblck

**Comment by tringwald** [comment]
I can reproduce the OOM problem as a result of a 161GB allocation. I guess `torch` uses a naive implementation here as the batch size is 1, can you try again with batch size 2 and see if the problem persists?

Even more worrying is that `benchmark = True; deterministic = False` with `dim2 = 4` yields:
```
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by baoleai** [comment]
When I set the batch_size to 2, I observed a similar phenomenon. Additionally, when setting benchmark = True; deterministic = False, a CUDA illegal memory access error occurred.

**Comment by huanpengchu** [comment]
I have the same question

**Comment by baoleai** [comment]
Maybe this is related to https://github.com/pytorch/pytorch/issues/22496#issuecomment-509433398,  'cudnn does not support tensors with more than 2^31 elements'. We have to split the input to satisfy constraints. @ngimel

**Comment by huanpengchu** [comment]
> Maybe this is similar to [#22496 (comment)](https://github.com/pytorch/pytorch/issues/22496#issuecomment-509433398), 'cudnn does not support tensors with more than 2^31 elements'. We have to split the input to satisfy constraints. @ngimel

do you solve this problem? can you give me a suggestion (I have the same oom error). 

`self.conv2(input_parallel[0,:,:120,:360])
*** torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 162.61 GiB. GPU`

**Comment by baoleai** [comment]
Hi, @huanpengchu, have you checked the total number of elements in your input/output tensors? If they indeed surpass the 2^31 threshold, a rapid solution would be to partition your input into smaller segments, each with fewer than 2^31 elements.
