### ISSUE TITLE
test_pstrf is fallacious

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#12908]
`test_pstrf` tests pstrf on positive definite matrices instead of testing on positive semi definite matrices. This caused us to not catch errors like #12435 .

The culprit is this segment of code:
https://github.com/pytorch/pytorch/blob/master/test/test_torch.py#L5379-L5381

Removing this segment produces errors about the input matrix being rank deficient. Rank deficiency for a real symmetric matrix is when at least one of the eigenvalues is zero. This scenario is plausible for positive semi definite matrices by definition.

cc: @zou3519

**Comment by SsnL** [comment]
lol the code segment says `add a small number to the diagonal to make the matrix numerically positive semidefinite`

**Comment by vishwakftw** [comment]
Should we not remove `pstrf` then?

**Comment by vishwakftw** [comment]
Any thoughts about this @SsnL @zou3519 ?

**Comment by zou3519** [comment]
I still don't understand the math behind this (linear algebra was a long time ago) but I'll sit down and do some reading today

**Comment by zou3519** [comment]
I'm confused -- cholesky decomposition is defined to work on positive definite matrices for the definitions I looked up. What does pstrf do, then?

**Comment by SsnL** [comment]
@zou3519 For PSD matrices, the diagonal can contain zeros. See p5 of http://eprints.ma.man.ac.uk/1199/1/covered/MIMS_ep2008_116.pdf

> What should be the result of the cholesky decomposition of [0]?

Just [[0]], I think.

**Comment by zou3519** [comment]
Got it, thank you for that article @SsnL. Let me try to feed some other positive semidefinite matrices through pstrf...

**Comment by vishwakftw** [comment]
Also to add to @SsnL's point that PSD matrices need not have a unique Cholesky decomposition. A simple example is:
[0, 0; 0, 1] = [0, 0; 1, 0] x [0, 1; 0, 0] = [0, 0; 0, 1] x [0, 0; 0, 1]

**Comment by vishwakftw** [comment]
@zou3519 @SsnL thoughts about this?

**Comment by vishwakftw** [comment]
https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.LAPACK.pstrf! suggests that `pstrf` works only on symmetric positive-definite matrices, for which we already have `potrf` (now `cholesky`). To avoid this redundancy, I think the method should be removed.

Please let me know what you think. @SsnL @zou3519

**Comment by zou3519** [comment]
The julia docs suggests that the difference between `potrf` and `pstrf` is that `pstrf` does pivoted cholesky decomposition. If I am understanding this correctly, "pivoting" is a different strategy for computing the decomposition, but it sounds like `pstrf` in PyTorch just doesn't work?

**Comment by vishwakftw** [comment]
Yes, pivoting is a different strategy of obtaining the decomposition. We don’t provide the pivot information anyways, so the API is just the same as potrf - as far as PyTorch is concerned and is buggy too.

**Comment by zou3519** [comment]
Yes, let's go for it (removing pstrf) because it doesn't work and potrf provides the functionality. We should still keep some bits of pstrf aroudn and add a runtime error just in case there are users who use it (our hypothesis is that there are none) so they know to switch to `potrf` and can complain to us if they have opinions

**Comment by vishwakftw** [comment]
I'll send in a PR with a deprecated warning for `pstrf` and wait for the next release. After that, we'll remove it.

If you think we should just remove it, and just keep a hollow `pstrf` function which basically raises a `RuntimeError` when used, that's fine by me too.

**Comment by zou3519** [comment]
Yes, the deprecated warning sounds fine to me, thank you @vishwakftw !

**Comment by vishwakftw** [comment]
Closed by https://github.com/pytorch/pytorch/commit/6dfecc7e01842bb7e5024794fdce94480de7bb3a
