### ISSUE TITLE
torch.nn.L1Loss works incorrectly in certain situations

### ISSUE THREAD

**Issue by LiekkasY** [pytorch/pytorch#12901]
## 🐛 Bug

torch.nn.L1Loss()'s parameter *reduction* doesn't work if b = net(a).
```
b = net(a)
l = torch.nn.L1Loss(reduction='elementwise_mean')
l(a, b) # wrong, it's summation 

```

## To Reproduce

```
import torch
import torch.nn as nn

datadim = 33


class BugNet(nn.Module):
    def __init__(self):
        super(BugNet, self).__init__()
        self.output = nn.Linear(datadim, datadim)

    def forward(self, x):
        return self.output(x)


a = torch.ones((4, 33))
bug = BugNet()
b = bug(a)

loss_fn1 = nn.L1Loss(reduction='sum')
loss_fn2 = nn.L1Loss(reduction='elementwise_mean')
elementwise_mean_loss = lambda x, x_out: torch.mean(torch.abs(x-x_out.view_as(x)))

print(loss_fn1(a, b))  # 127.6617, True
print(loss_fn2(a, b))  # 127.6617, False
print(loss_fn2(b, a))  # 0.9671, True
print(elementwise_mean_loss(a, b))  # 0.9671, True
```

## Outputs

```
tensor(127.6617, grad_fn=<SumBackward0>)
tensor(127.6617, grad_fn=<SumBackward0>)
tensor(0.9671, grad_fn=<L1LossBackward>)
tensor(0.9671, grad_fn=<MeanBackward1>)
```

## Environment

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Debian GNU/Linux 9.5 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: Could not collect

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 396.44
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/lib64/libcudnn.so.7.2.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] intel-numpy (1.15.1)
[pip] numpy (1.15.1)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] Could not collect

## Additional context
I have checked the source. In  F.l1_loss(), it use 
`reduction = _Reduction.get_enum(reduction)`
to convert reduction to an integer. However, it calls _pointwise_loss(), 
which assumes that reduction is still a str.
`return torch.mean(d) if reduction == 'elementwise_mean' else torch.sum(d)  # In _pointwise_loss()`
That's the reason of this bug.

**Comment by justinkterry** [comment]
Hey, can you please give a better explanation of this bug? I know it's legitimate because you showed it to me and Chen, but your explanation isn't one the maintainers are going to be able to look at and say "alright, I know what I need to fix." I'll give you extra credit for finding this, remind me during office hours.

**Comment by justinkterry** [comment]
I just sat down and looked at the code, and this only impacts an old version of pytorch man

**Comment by LiekkasY** [comment]
> I just sat down and looked at the code, and this only impacts an old version of pytorch man

What do you mean by old version? I'm using v0.4.1 (latest stable release).

**Comment by LiekkasY** [comment]
> Hey, can you please give a better explanation of this bug? I know it's legitimate because you showed it to me and Chen, but your explanation isn't one the maintainers are going to be able to look at and say "alright, I know what I need to fix." I'll give you extra credit for finding this, remind me during office hours.

I've posted an explanation.

**Comment by wandering007** [comment]
> > I just sat down and looked at the code, and this only impacts an old version of pytorch man
> 
> What do you mean by old version? I'm using v0.4.1 (latest stable release).

It has been fixed via https://github.com/pytorch/pytorch/pull/10018.

**Comment by wandering007** [comment]
> > I just sat down and looked at the code, and this only impacts an old version of pytorch man
> 
> What do you mean by old version? I'm using v0.4.1 (latest stable release).

It has been fixed via https://github.com/pytorch/pytorch/pull/10018.

**Comment by wandering007** [comment]
> > I just sat down and looked at the code, and this only impacts an old version of pytorch man
> 
> What do you mean by old version? I'm using v0.4.1 (latest stable release).

It has been fixed via https://github.com/pytorch/pytorch/issues/12901

**Comment by zou3519** [comment]
This bug has been fixed on master.
