### ISSUE TITLE
How to compile PyTorch from source with custom CMake options?

### ISSUE THREAD

**Issue by Amir-Arsalan** [pytorch/pytorch#12918]
I want to compile PyTorch with custom CMake flags/options. However, it looks like `setup.py` doesn't read any of the environmental variables for those options while compilation. More specifically, I am trying to set the options for _Python site-packages_ and Python includes. I wonder how I can set these options before compilation and without manually changing the `CMakesLists.txt`?

**Comment by soumith** [comment]
as mentioned elsewhere, change the cmake invocation in `build_pytorch_libs.sh` manually.

**Comment by jinfagang** [comment]
Same question here, how to set ONNX python support in setup.py?

**Comment by denfromufa** [comment]
@soumith the build_pytorch_libs.sh is now build_pytorch_libs.py and has lots of warnings about cmake. So how do we add cmake arguments now?

**Comment by soumith** [comment]
@xuhdev would know

**Comment by xuhdev** [comment]
@denfromufa Which CMake options are you trying to add? For those starting with `CMAKE_`, `BUILD_`, or `USE_`, you can simply pass them as environmental variables. See the comments:

https://github.com/pytorch/pytorch/blob/c8ca70e39d0efc9dd008b78fdd5ca089ab965746/tools/setup_helpers/cmake.py#L251-L255

**Comment by denfromufa** [comment]
All I needed was this option j1, which we already found:

https://github.com/pytorch/pytorch/issues/31438#issuecomment-575336231

But thank you for this note in case I need to work with cmake again.

BTW, j1 is an argument to cmake, not sure if it is possible to pass it via
env. variable.

**Comment by denfromufa** [comment]
PR to address the docs: https://github.com/pytorch/pytorch/pull/32319
