### ISSUE TITLE
How to customize a new operator ubder the pre-built caffe2？

### ISSUE THREAD

**Issue by xielele** [pytorch/pytorch#12912]
I install the pre-built caffe2 with this command:
conda install pytorch-nightly cuda80 -c pytorch
The caffe2 and Detectron were installed successfully and I can run the baseline configs. However, I dont konw how to customize a new operator for Detectron as I use the pre-built version of caffe2. I also followed the instructions in FAQ and it only worked when I installed the caffe2 built from source.

**Comment by orionr** [comment]
HI @xielele  - if you're talking about a Detectron operator, I'd recommend posting your question to https://github.com/facebookresearch/Detectron/. There are ways to register a new operator even with a pre-built Caffe2 and the documentation over there should explain it.
