### ISSUE TITLE
nn.Linear outputs differ on the same input tensor #129029 answer does not match

### ISSUE THREAD

**Issue by jianlingl** [pytorch/pytorch#129111]
_Originally posted by @jianlingl in #https://github.com/pytorch/pytorch/issues/129029#issue-2361146672

The issue might not be due to the possible link: https://pytorch.org/docs/stable/notes/numerical_accuracy.html#batched-computations-or-slice-computations, and the situation is more serious than expected.

1. The batch calculation values have issues in the second linear layer but are accurate in the first one.
2. I verified that x1_fc2 and x2_fc2 are exactly the same on the GPU, but there are differences on the CPU. This causes the model to perform differently on different devices.
3. The numerical differences are actually quite large. For example, 

```
x1_fc2[0, 5].item(), x2_fc2[0, 5].item()
(0.027112668380141258, 0.02711271122097969)
```

**Comment by zou3519** [comment]
changing the code to use torch.assertclose instead of (==) results in the code passing. This is just https://pytorch.org/docs/stable/notes/numerical_accuracy.html#batched-computations-or-slice-computations

**Comment by malfet** [comment]
Closing as indeed it is an expected behavior (CPU and GPU are not guaranteed to produce the same results and changing batch sizes can produce a slightly different results)
