### ISSUE TITLE
[docs] links to html docs could benefit from scrollTo or similar

### ISSUE THREAD

**Issue by svenevs** [pytorch/pytorch#12915]
## 📚 Documentation

Visit the following link for `torch.nn.Module`: https://pytorch.org/docs/master/nn.html#torch.nn.Module

After the page finalizes loading it'll jump a little too far, blocking the actual `class torch.nn.Module` underneath the navbar.  This is a `bootstrap` specific thing, I'm sure the authors of the beautiful new bootstrap based theme know the best way to fix it.  You can detect `#anchor.text` or whatever, but you basically just want to scroll a little bit -- specifically by the size of the navbar -- so that when you click on a docs link the leading `class XXX` isn't hidden by the navbar.

It's definitely not urgent, but it can get a little confusing :wink:

I love the new docs btw, they're beautiful!

**Comment by soumith** [comment]
https://github.com/pytorch/pytorch_sphinx_theme/pull/28 will fix the issue. Should be merged soon.

**Comment by svenevs** [comment]
Fixing issue was merged, closing this for the record :slightly_smiling_face:
