### ISSUE TITLE
Example usage for `convert_conv3d_weight_memory_format` does not work anymore

### ISSUE THREAD

**Issue by tringwald** [pytorch/pytorch#129158]
### 📚 The doc issue

The code example for http://pytorch.org/docs/stable/generated/torch.nn.utils.convert_conv3d_weight_memory_format.html does not work anymore.

```
RuntimeError: required rank 4 tensor to use channels_last format
```

### Suggest a potential alternative/fix

`torch.channels_last` should probably be `torch.channels_last_3d` instead.

cc @svekars @brycebortree

**Comment by nsnod** [comment]
Hello there! Could I take on this issue?

**Comment by nsnod** [comment]
Is something that needs fixing? I would love to contribute! First timer :)

**Comment by theprashasst** [comment]
.take

**Comment by tringwald** [comment]
> Is this something that needs fixing? I would love to contribute! First timer :)

Sure, let me know if you need help.

**Comment by gagan-bhullar-tech** [comment]
can i take this as my first contribution.
