### ISSUE TITLE
The function name `SGD()` should be `GD()` if it's still (classic) GD,

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#129190]
### 🚀 The feature, motivation and pitch

I read the discussion of [Is the SGD in Pytorch a real SGD?](https://discuss.pytorch.org/t/is-the-sgd-in-pytorch-a-real-sgd/9714) and [How SGD works in pytorch](https://discuss.pytorch.org/t/how-sgd-works-in-pytorch/8060) so if the [SGD()](https://pytorch.org/docs/stable/generated/torch.optim.SGD.html) in PyTorch is still (classic) GD, the function name should be `GD()`.

**Comment by lezcano** [comment]
SGD is performed on any minibatch size sampled from the dataset. GD would be if you use the whole dataset in each iteration.

At any rate, this function is too well established, with hundreds of thousands of uses throughout github, so we would not be able to change its name (nor I think we should).

Let's continue the discussion in the forum post.
