### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by euler16** [pytorch/pytorch#1292]
The code given here http://pytorch.org/tutorials/beginner/pytorch_with_examples.html has some indentation errors. I want to begin with contributing to open source, please tell me the steps to correct the docs.

**Comment by soumith** [comment]
the first step to contributing to open source (and you'll get used to this), figure out the steps yourself :)
on a lighter vein, open an issue on https://github.com/pytorch/tutorials and edit the files there, and send a PR on that repo. @chsasank will review it and merge it.
