### ISSUE TITLE
Move Memory Allocation for Autotuning out of the critical path

### ISSUE THREAD

**Issue by shunting314** [pytorch/pytorch#129258]
### 🐛 Describe the bug

When working on https://github.com/pytorch/pytorch/pull/129043#discussion_r1648329821 we found the memory saving is
 much larger then expected for llm.c (expect 6GB saving but actually saves about 15GB). It turns out that there the baseline uses more memory then expected due to autotuning happening for the first iteration. 

<img width="942" alt="Screenshot 2024-06-21 at 11 56 29 AM" src="https://github.com/pytorch/pytorch/assets/52589240/9840e1b9-5dba-406f-a465-50684af2a0aa">

The kernel does mutation, so autotuning needs to allocate a clone. Although this specific case has been fixed by the mentioned PR since we convert Scatter to a Pointwise, the general problem still exists.

I think one solution is, we do all those mutation kernels's autotuning right after we codegen the wrapper. This is a good time to do autotuning since we have not started allocating memory for activation/gradient/optimizer state etc. 

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @jansel @Chillee @eellison 

### Versions

.

cc @ezyang @anijain2305 @chauhang

**Comment by Chillee** [comment]
@shunting314 But for the backwards pass, right after we codegen the wrapper aren't we at the peak memory location?

**Comment by shunting314** [comment]
> But for the backwards pass, right after we codegen the wrapper aren't we at the peak memory location?

Good point. We probably also need to 'eagerly' generated the backward graph. If we generate the bwd wrapper before we run the fwd graph, we can still avoid increasing peak memory due to autotuning.

**Comment by bdhirsh** [comment]
One thing I'm worried about is that there are some reasons it might be a good thing to delay backward compilation until runtime.

The big example is when we have tangents that are subclasses, and we need to wait until runtime backward to know their proper metadata so we can get a correct backward graph. This doesn't exist today, but I was hoping to find some time to work on it in H2.

I'd be curious what @Chillee thinks - just to throw out alternatives, what do you think of something like cloning the inputs to the kernel onto cpu, and directly copying them from cpu back into the inputs (without needing extra cuda memory?). I'm not sure if there are other cases where inductor compilation needs extra memory though.

**Comment by eellison** [comment]
Maybe the simplest short term fix is to copy input to cpu if we cloning it would increase high water memory mark.

Note, would need: https://github.com/pytorch/pytorch/issues/129496 to calculate this

**Comment by ezyang** [comment]
Also, it's easy to end up in situations where you already have a lot of memory allocated and then you are compiling a new region (e.g., compiled autograd), so it's good to figure how to make sure the compiler in general doesn't use more CUDA memory.

**Comment by eellison** [comment]
Also, this particular mutating kernel (scatter_) is idempotent so we don't really even need to clone

**Comment by eellison** [comment]
For some more pointers:

in codegen, we annotate the generated triton kernel with "mutated_arg_names": https://github.com/pytorch/pytorch/blob/1cae60a87e5bdda8bcf55724a862eeed98a9747e/torch/_inductor/codegen/triton.py#L2582

Those are then read in the runtime autotuner: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/runtime/triton_heuristics.py#L677

We'd also want to annotate the generated triton kernel with something like "clone_to_cpu" in cases where clones increase peak memory.

**Comment by eellison** [comment]
Fixedw ith https://github.com/pytorch/pytorch/pull/136701
