### ISSUE TITLE
DISABLED test_comprehensive_nn_functional_huber_loss_cuda_float16 (__main__.TestInductorOpInfoCUDA)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#129238]
Platforms: linux

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_torchinductor_opinfo.py%3A%3ATestInductorOpInfoCUDA%3A%3Atest_comprehensive_nn_functional_huber_loss_cuda_float16%22%5D)).

It starts to fail in trunk, but the root cause is not clear.  I attempt to revert the commit where the failure first starts to occur, but it doesn't help https://github.com/pytorch/pytorch/pull/129013#issuecomment-2182217164

cc @ezyang @anijain2305 @chauhang

**Comment by isuruf** [comment]
The cause is probably https://github.com/pytorch/pytorch/pull/128343

**Comment by isuruf** [comment]
https://github.com/pytorch/pytorch/pull/129245 should disable this test for all samples and run only one sample
