### ISSUE TITLE
(Refactor) Change default nonlinearity and bound calculation in kaiming_uniform_ & kaiming_normal_ and change kaiming_uniform call in reset_parameters in conv.py & linear.py to avoid sqrt(5) confusion (and maybe change numerical bound val in kaiming_uniform_ and numerical std val in kaiming_normal?) 

### ISSUE THREAD

**Issue by rk7697** [pytorch/pytorch#129302]
### 🚀 The feature, motivation and pitch

During weight initialization in [torch/nn/modules/linear.py](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/linear.py) and torch/nn/modules/conv.py in reset_parameters,[ init.kaiming_uniform_ is called with a=sqrt(5)](https://github.com/pytorch/pytorch/blob/9ffdbb5d128e9bb05db0ab8df224275c802751cb/torch/nn/modules/linear.py#L110) because kaiming_uniform_ uses default nonlinearity as 'leaky_relu', and calculate_gain [branches an if statement](https://github.com/pytorch/pytorch/blob/9ffdbb5d128e9bb05db0ab8df224275c802751cb/torch/nn/init.py#L113) for (nonlinearity == 'leaky_relu' and if param (which is the value a being passed) is type float or int) which returns gain = sqrt(2/1+(sqrt(5))^2)=sqrt(1/3), and finally kaiming_uniform_ sets bound= sqrt(3) * std = sqrt(3) * gain/sqrt(fan) = 1/sqrt(fan). 

I think this would be easier to understand if kaiming_uniform_ (and kaiming_normal) set the default nonlinearity to 'linear' so that calculate_gain immediately returns 1. Then remove this branched if statement in calculate_gain. Then in kaiming_uniform remove the sqrt(3) from [the equation setting bound=sqrt(3)*std](https://github.com/pytorch/pytorch/blob/9ffdbb5d128e9bb05db0ab8df224275c802751cb/torch/nn/init.py#L458) to just have bound=std. Then remove the a=sqrt(5) in the [call of init.kaiming_uniform(self.weight, a=sqrt(5))](https://github.com/pytorch/pytorch/blob/9ffdbb5d128e9bb05db0ab8df224275c802751cb/torch/nn/modules/linear.py#L110) in the reset_parameter method during weight initialization in torch/nn/modules/linear.py and torch/nn/modules/conv.py (and maybe multiple others? Not sure, sorry). Documentation would have to be updated accordingly. I thought this would be simpler because 'linear' seems like a simpler nonlinearity default and an extra sub case calculation and an additional scaling factor would not be needed.

However, if nonlinearity is set to 'linear' by default in kaiming_normal, then since kaiming_normal does not use bound or the equation bound=sqrt(3)*std, and instead passes std = gain/sqrt(fan) into torch.normal, gain by default would now be 1 instead of sqrt(1/3). Since this new std would be sqrt(3) times the old std, I would like to consider an additional different question.

Sorry, I apologize for raising a pure question in an issue, but if I'm not mistaken, why is bound ultimately being set to 1/sqrt(fan) in kaiming_uniform and why is std being set to 1/sqrt(3 * fan)) in kaiming_normal (if using the same template call kaiming_normal(weight,a=sqrt(5)) as kaiming_uniform during weight initialization)? For weight initialization, I thought he initialization suggests a normal distribution with variance 2/fan_size. If a symmetric uniform distribution is used with bound=1/sqrt(fan_size), then from the variance formula for a uniform distribution, I think the variance will be ((1/sqrt(fan_size))^2)/3 = 1/(3*fan_size)) instead of 2/sqrt(fan_size)). Wouldn't the variance be accumulating factors of 1/6 for each layer through the forward (or backward) pass instead of remaining constant? 

I would be very curious for anyone's thoughts. I'd like to start a PR for this but I'm not sure if a code refactor would be desired or if the initial variances in weight initialization would want to have to be reconsidered. Thx :]

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by albanD** [comment]
THanks for your issue and detailed discussion.
I'm afraid I won't have any very satisfying answer for you: these values where added 6 years ago and mostly inherrited from Torch7 (luaTorch) so so are almost 10 years old and very hard to change because it could silently break many users model to do so.

So our general recommendation has been that, unless it is not working for you, you should initialize your Module with the right method using torch.nn.init.* functionality to get exactly the behavior you're looking for.

**Comment by rk7697** [comment]
Ah I see, thx for this info

**Comment by albanD** [comment]
Closing the issue as non-actionable.
Feel free to re-open if you think there is something we can do to improve the situation that wouldn't break Backward Compatibility for our users.
