### ISSUE TITLE
torch.Tensor.register_hook() source link does not work

### ISSUE THREAD

**Issue by davidtweedle** [pytorch/pytorch#129332]
### 📚 The doc issue

In the documentation for [torch.Tensor.register_hook()](https://pytorch.org/docs/stable/generated/torch.Tensor.register_hook.html#torch.Tensor.register_hook), click on [[source]](https://pytorch.org/docs/stable/_modules/torch/_tensor.html#Tensor.register_hook).
I expect to be directed to the source code for torch.Tensor.register_hook() but instead I get a 404.

**Comment by awgu** [comment]
Also filed in https://github.com/pytorch/pytorch/issues/76510
