### ISSUE TITLE
`start` and `step` of `arange()` should be optional on the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#129333]
### 📚 The doc issue

[arange()](https://pytorch.org/docs/stable/generated/torch.arange.html) with only `end` argument works as shown below:

```python
import torch

torch.arange(5)
torch.arange(end=5)
# tensor([0, 1, 2, 3, 4])
```

So, `start` and `step` should be optional on [the doc](https://pytorch.org/docs/stable/generated/torch.arange.html) as shown below:

> - `start` (*Number*, *optional*) – the starting value for the set of points. Default: 0.
>- `end` (*Number*) – the ending value for the set of points
> - `step` (*Number*, *optional*) – the gap between each pair of adjacent points. Default: 1.

cc @svekars @brycebortree @gchanan @mruberry

**Comment by janeyx99** [comment]
This seems properly conveyed by the fact that the `start` and `step` arguments have defaults.
