### ISSUE TITLE
torch.compile can supports load_state_dict

### ISSUE THREAD

**Issue by songh11** [pytorch/pytorch#129362]
### 🐛 Describe the bug

I want to use torch.compile on the init model, and then reload the model. But I used load_state_dict not come into effect. But the weights have been updated. 
But it works when I update the weights manually. I don't know why. Can you help me.

### Minified repro

You can comment line24~line28, and this will run successfully

```python
import torch

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = torch.nn.Linear(5, 5)

    def forward(self, x):
        return self.lin(x)

mod = MyModule().cuda()
mod.forward = torch.compile(mod.forward, fullgraph=True)
input = torch.ones(1, 5).cuda()
with torch.no_grad():
    print('origin output: ', mod(input))

state_dict = mod.state_dict()
torch.save(state_dict, "test_weight.pth")
mod.lin.weight.data.fill_(0)
mod.lin.bias.data.fill_(0)
with torch.no_grad():
    print('init output: ', mod(input))

# This approach will fail 
state_dict = torch.load('test_weight.pth')
mod.load_state_dict(state_dict, assign=True)
with torch.no_grad():
    print('reload output: ', mod(input))

# This approach will success
state_dict = torch.load('test_weight.pth')
mod.lin.weight.data = state_dict['lin.weight']
mod.lin.bias.data = state_dict['lin.bias']
with torch.no_grad():
    print('reload output 2: ', mod(input))
``` 

### Versions

Collecting environment information...
PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.252-0504252-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA RTX A5000
Nvidia driver version: 535.104.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      40 bits physical, 48 bits virtual
CPU(s):                             16
On-line CPU(s) list:                0-15
Thread(s) per core:                 1
Core(s) per socket:                 16
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          AuthenticAMD
CPU family:                         23
Model:                              1
Model name:                         AMD EPYC Processor (with IBPB)
Stepping:                           2
CPU MHz:                            3099.998
BogoMIPS:                           6199.99
Virtualization:                     AMD-V
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          512 KiB
L1i cache:                          1 MiB
L2 cache:                           8 MiB
L3 cache:                           16 MiB
NUMA node0 CPU(s):                  0-15
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr virt_ssbd arat npt nrip_save arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.3.1
[pip3] torchaudio==2.3.1
[pip3] torchsde==0.2.6
[pip3] torchvision==0.18.1
[pip3] triton==2.3.1
[conda] Could not collect

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by masnesral** [comment]
Note: Looks like it works with backend="eager", and also works with inductor when assign=False.

**Comment by songh11** [comment]
> Note: Looks like it works with backend="eager", and also works with inductor when assign=False.

Thanks for your response 😃 , it can work when assign=False. But I don't understand what the difference with assign=False, What will torch.compile change on state_dict? 🤔️

**Comment by awgu** [comment]
If I had to guess, the compiled artifact probably has references to the original parameter tensors (they are not passed as inputs to the compiled graph). If you use `assign=False`, `load_state_dict` will copy the state dict's parameters into the model's original parameters. If you use `assign=True`, `load_state_dict` will use `setattr`, so the original parameters still have the original values.

**Comment by mlazos** [comment]
@awgu you're correct, we don't guard on the internals of NN modules. Turning on inlining of builtin NN modules should solve this problem, because the parameters will be inputs to the graph.

cc @anijain2305

**Comment by mlazos** [comment]
This should be resolved with https://github.com/pytorch/pytorch/pull/132053
