### ISSUE TITLE
`repeat_interleave()` without `repeats` argument and `input` keyword works

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#129322]
### 🐛 Describe the bug

`repeats` argument of `repeat_interleave()` is required according to [the doc](https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html) as shown below:

```python
import torch

my_tensor = torch.tensor([3, 5, 1])

torch.repeat_interleave(input=my_tensor, repeats=3)
my_tensor.repeat_interleave(repeats=3)
# tensor([3, 3, 3, 5, 5, 5, 1, 1, 1])
```

So, `repeat_interleave()` without `repeats` argument gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([3, 5, 1])

torch.repeat_interleave(input=my_tensor) # Error
```

> TypeError: repeat_interleave() missing 1 required positional arguments: "repeats"

But `repeat_interleave()` without `repeats` argument and `input` keyword works as shown below:

```python
import torch

my_tensor = torch.tensor([3, 5, 1])

torch.repeat_interleave(my_tensor)
# tensor([0, 0, 0, 1, 1, 1, 1, 1, 2])
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by jbschlosser** [comment]
From the docs, if a single positional arg is passed, it is considered to be `repeats`: `torch.repeat_interleave(repeats, *) → Tensor`.
`input` without `repeats` is not supported.

Closing as expected behavior.
