### ISSUE TITLE
Adding noise to gradients does not perform correctly

### ISSUE THREAD

**Issue by HagaiAstrin** [pytorch/pytorch#129354]
### 🐛 Describe the bug

I'm using a bert model and I wanted to apply differential privacy.
For that I tried to add noise to the gradients.
The problem comes from this line:
```param.grad += torch.tensor(np.random.normal(0, 0, size=param.grad.shape), device=param.grad.device)```
When removing this line, the model performs well, but if I run the model with this line, 
the model gives results that doesn't make any sense.

For this code sample, the mean and the standard deviation are 0 - which means that I'm adding 0 noise, so my gradients shouldn't be changed.

Unfortunately, I'm unable to share the full code, but I believe the error should be easy to reproduce. 
```
optimizer = torch.optim.AdamW(bert_model.parameters(), lr=learning_rate)
bert_model.train()

for epoch in range(epochs):
    for batch in train_loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        outputs = bert_model(input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()

        # Clipping gradients
        torch.nn.utils.clip_grad_norm_(bert_model.parameters(), clip_norm)

        # Adding differential privacy noise to gradients
        for param in bert_model.parameters():
            if param.grad is not None:
                param.grad += torch.tensor(np.random.normal(0, 0, size=param.grad.shape), device=param.grad.device) 

        optimizer.step()
        progress_bar.update(1)
```
For some sanity check, changing the problematic line to:
``` 
noise_tensor = torch.zeros_like(param.grad, device=param.grad.device)
param.grad += noise_tensor
```
does not affect the model performance (as expected).

An interesting thing occured when I changed the problematic line to:
```param.grad = param.grad + torch.tensor(np.random.normal(0, 0, size=param.grad.shape), device=param.grad.device)```

I get the following error:
```
{
	"name": "RuntimeError",
	"message": "attempting to assign a gradient with dtype 'double' to a tensor with dtype 'float'. Please ensure that the gradient and the tensor have the same dtype",
	"stack": "---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[10], line 26
     24 for param in bert_model.parameters():
     25     if param.grad is not None:
---> 26         param.grad = param.grad + torch.tensor(np.random.normal(0, 0, size=param.grad.shape), device=param.grad.device) 
     28 optimizer.step()
     29 progress_bar.update(1)

RuntimeError: attempting to assign a gradient with dtype 'double' to a tensor with dtype 'float'. Please ensure that the gradient and the tensor have the same dtype"
}
```

As I mentioned before,
```param.grad += torch.tensor(np.random.normal(0, 0, size=param.grad.shape), device=param.grad.device)```
does run without errors, so I suspect there is some kind of hidden casting that affect the gradients.

### Versions

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.11.0
[pip3] torch==2.3.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi

cc @ezyang @albanD @gqchen @pearu @nikitaved @soulitzer @Varal7

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

For your particular question this is because the numpy Tensor is double precision and not float as we would expect.
You can change the dtype there or use torch.rand for randomness which will create a floating point number by default
