### ISSUE TITLE
DISABLED test_module_to_empty_cuda_float32 (__main__.TestNNDeviceTypeCUDA)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#129491]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22test_nn.py%3A%3ATestNNDeviceTypeCUDA%3A%3Atest_module_to_empty_cuda_float32%22%5D)).

No idea why this is suddenly failing.  Doesn't seem to correlate with any landed PRs.  The test itself was landed 4 months ago by https://github.com/pytorch/pytorch/commit/b51b27922b38385c007d886b0e5e7c29f2ba1074.

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by huydhn** [comment]
I have tried to revert one commit https://github.com/pytorch/pytorch/pull/129239, let me close this one and see if trunk recovers
