### ISSUE TITLE
[compilation error] PyTorch compilation failed on macOS

### ISSUE THREAD

**Issue by yushangdi** [pytorch/pytorch#129404]
### 🐛 Describe the bug

Running `python setup.py develop` gives the following error

/Users/shangdiy/Desktop/pytorch/aten/src/ATen/cpu/Utils.cpp:37:34: error: use of undeclared identifier 'cpuinfo_has_x86_amx_tile'; did you mean 'cpuinfo_has_x86_mmx_plus'?
  return cpuinfo_initialize() && cpuinfo_has_x86_amx_tile();
                                 ^~~~~~~~~~~~~~~~~~~~~~~~
                                 cpuinfo_has_x86_mmx_plus
/Users/shangdiy/Desktop/pytorch/third_party/cpuinfo/include/cpuinfo.h:894:20: note: 'cpuinfo_has_x86_mmx_plus' declared here
static inline bool cpuinfo_has_x86_mmx_plus(void) {
                   ^
1 error generated.
[10/1136] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/detail/MPSHooksInterface.cpp.o
ninja: build stopped: subcommand failed.

It might be due to this PR: https://github.com/pytorch/pytorch/pull/127195#issuecomment-2187187975 

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 14:46:42) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M2

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.11.0
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] torchfix                  0.4.0                    pypi_0    pypi

**Comment by Shan19900305** [comment]
Hi, function cpuinfo_has_x86_amx_tile is write in cpu_info, which is a third_party repository. Maybe you need to update submodules for last pytorch build.

**Comment by yushangdi** [comment]
thanks!
