### ISSUE TITLE
[jit][trace] non-argument tensors with requires_grad=True are traced as constants

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#12946]
## 🐛 Bug

non-argument tensors with requires_grad=True are traced as constants

## To Reproduce
```
import torch
x = torch.randn(3, requires_grad=True)
def f(inp):
    return (x + inp).sum()

tf = torch.jit.trace(f, (torch.randn(1),))
f(torch.randn(1))
# expected output: tensor(-1.2899, grad_fn=<SumBackward0>) result requires grad

tf(torch.randn(1))
# got output: tensor(-3.6019), result does not require grad!
```
## Expected behavior

The output should have requires_grad=True so that one can backprop through it

## Environment
PT master

Reported by @SsnL

**Comment by SsnL** [comment]
Thanks :)

**Comment by zdevito** [comment]
I don't think we want you to allow gradient to flow through constant nodes, it would break the autodiff.cpp badly. A warning or an error would be appropriate here. It should say that all requires_grad=True tensors need to be inputs to the trace.

**Comment by zou3519** [comment]
the conclusion was that this is hard support and we should throw a warning or error when this occurs to alert our users about the change in semantics

**Comment by ezyang** [comment]
Errors now.

```
>>> tf = torch.jit.trace(f, (torch.randn(1),))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/ezyang/pytorch-tmp2/torch/jit/_trace.py", line 780, in trace
    traced = torch._C._create_function_from_trace(
  File "<stdin>", line 2, in f
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
Tensor:
-0.6102
-0.7205
 0.1871
[ torch.FloatTensor{3} ]
```
