### ISSUE TITLE
Enable multiprocess sharing for `nn.Module`s that have meta tensors

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#129436]
### 🚀 The feature, motivation and pitch

In TorchRL, there are a couple `nn.Module`s that contain a set of other submodules, where one of the submodules has `device='meta'`, and the rest are on a real device. I don't exactly know the details, but it looks like TorchRL uses the meta submodule to facilitate vmapping across the submodules that are on real devices.

The problem is that since PyTorch doesn't allow meta tensors to be shared between processes, an error is raised if the user tries to share them between processes, as shown in https://github.com/pytorch/rl/issues/2180.

I suppose there might be at least two slightly different possible solutions:

1. Enable `Tensor(..., device='meta')` to be shared
2. Just enable sharing `nn.Module`s that contain meta tensors, by avoiding trying to share a tensor if it is on the meta device

cc @VitalyFedyunin @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @ezyang @eellison @bdhirsh @vmoens

**Comment by kurtamohler** [comment]
I'm not sure which of the two solutions I mentioned is best, or if there are any other solutions.

I can submit a PR after a decision is made

**Comment by vmoens** [comment]
To me the problem boils down to enabling tensors with `"meta"` device to be reduced.

There are 3 places where I think a patch could be written:
 - patch the python [`UntypedStorage._share_filename_cpu_`](https://github.com/pytorch/pytorch/blob/8bfd9e98154b83fc6bb0d4407e103d0eb65331ae/torch/storage.py#L1216-L1218)
 - patch the C++ version [`THPStorage_shareFilename`](https://github.com/pytorch/pytorch/blob/8bfd9e98154b83fc6bb0d4407e103d0eb65331ae/torch/csrc/StorageSharing.cpp#L94)
 - patch [reduce_storage](https://github.com/pytorch/pytorch/blob/8bfd9e98154b83fc6bb0d4407e103d0eb65331ae/torch/multiprocessing/reductions.py#L550)

I think reduce_storage is a viable option: we can check the device and if it’s meta we have a custom recipe where we deconstruct it in metadata only (mainly dtype and shape)

Going down the c++ road seems an overkill for this patch but I may be missing the bigger picture!

**Comment by albanD** [comment]
Sending the meta Tensor over the wire would be indeed simple as we just have to ignore the storage. I think we can do that either in a similar way as we handle cuda Tensors or at the storage level by being a no-op.

I guess that, just like other Tensors, metadatas are not actually shared and "resizing" these Tensors is not allowed so there is no concern with having a "fake" sharing here?
