### ISSUE TITLE
How to Convert pytorch qat model to tensorrt

### ISSUE THREAD

**Issue by AnnaTrainingG** [pytorch/pytorch#129542]
I find that the converted qat model in pytorch can't use GPU Kernel, But I don't find the function or ways to convert to tensorrt. How to Convert pytorch qat model to tensorrt?

**Comment by jbschlosser** [comment]
Hey @AnnaTrainingG, I encourage you to ask a question like this on the [PyTorch forums](https://discuss.pytorch.org/), as you're more likely to receive assistance there. Note that the issues here are reserved for problems within PyTorch itself. Closing but feel free to reopen with more detail if discussion on the forums indicates a PyTorch bug, thanks!
