### ISSUE TITLE
installation error in OS X 10.11 with cuda8

### ISSUE THREAD

**Issue by diccooo** [pytorch/pytorch#1295]
the error message is

> [1%] Linking CXX shared library libTHC.dylib
> Undefined symbols for architecture x86_64:
>   "_cusparseCreate", referenced from:
>       _THCState_reserveDeviceSparseHandles in THCGeneral.c.o
>   "_cusparseDestroy", referenced from:
>       _THCudaShutdown in THCGeneral.c.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [libTHC.1.dylib] Error 1
> make[1]: *** [CMakeFiles/THC.dir/all] Error 2
> make: *** [all] Error 2

what could I do with it?

**Comment by diccooo** [comment]
could someone help me ? thanks!

**Comment by ngimel** [comment]
Looks like you don't have libcusparse or have a wrong version of it.

**Comment by soumith** [comment]
i think  this is a CMake issue recently introduced. THC/CMakeLists.txt needs to always link against cusparse now, rather than only when Magma is around:

https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/CMakeLists.txt#L228

This issue was introduced in the CUDA sparse PR

**Comment by yyaodong** [comment]
Soumith, thanks for the information. I met the same problem. Is there a solution yet?

**Comment by yyaodong** [comment]
@diccooo I actually find this works: add one line in the THC/CMakeLists.txt: 
`  TARGET_LINK_LIBRARIES(THC ${CUDA_cusparse_LIBRARY} )`

**Comment by soumith** [comment]
this should now be fixed in master

**Comment by diccooo** [comment]
it works for me..thanks a lot!
