### ISSUE TITLE
[TensorDict - compile] zip not supported by dynamo

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#129660]
### 🐛 Describe the bug

The [following code block](https://github.com/pytorch/tensordict/blob/b5cb40aaeb824ac632c0a2f178430105513525d1/tensordict/tensorclass.py#L595-L603) does not work because dynamo complains about zip
```

  File "/Users/vmoens/venv/rl/lib/python3.11/site-packages/torch/_dynamo/variables/base.py", line 320, in call_method
    unimplemented(f"call_method {self} {name} {args} {kwargs}")
  File "/Users/vmoens/venv/rl/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 221, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_method GetAttrVariable(UserDefinedObjectVariable(MyClass), __dataclass_fields__) items [] {}

...

======================================================================= short test summary info =======================================================================
FAILED test/test_compile.py::TestTC::test_tc_arithmetic - torch._dynamo.exc.Unsupported: builtin: zip [<class 'torch._dynamo.variables.lists.TupleVariable'>, <class 'torch._dynamo.variables.misc.GetAttrVariable'>] False
```

### Versions

PyTorch version: 2.5.0.dev20240627
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.3
Libc version: N/A

Python version: 3.11.7 (v3.11.7:fa7a6f2303, Dec 4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] mujoco-torch==0.1.0
[pip3] numpy==1.26.4
[pip3] optree==0.11.0
[pip3] torch==2.5.0.dev20240627
[pip3] torchao==0.1
[pip3] torchaudio==2.4.0.dev20240627
[pip3] torchrl==0.4.0+7c0a7c8
[pip3] torchtext==0.18.0
[pip3] torchvision==0.20.0.dev20240627
[conda] Could not collect

cc @ezyang @anijain2305 @chauhang @penguinwu

**Comment by ignaciobartol** [comment]
Hello, how can I replicate this error? Currently I forked tensordict, switched to the branch [compile_compat](https://github.com/pytorch/tensordict/tree/compile-compat) and running `python test/test_compile.py` but the only error I am getting is the following one:

```bash
AssertionError: 

from user code:
   File "/Users/ignaciobartol/docathon/tensordict/test/test_compile.py", line 198, in add_self
    return td + td
  File "/Users/ignaciobartol/docathon/tensordict/tensordict/tensorclass.py", line 1026, in wrapped_func
    result = getattr(td, funcname)(*args, **kwargs)
  File "/Users/ignaciobartol/docathon/tensordict/tensordict/base.py", line 6503, in __add__
    return self.add(other)
  File "/Users/ignaciobartol/docathon/tensordict/tensordict/base.py", line 7022, in add
    other_val = other._values_list(True, True, sorting_keys=keys)
  File "/Users/ignaciobartol/docathon/tensordict/tensordict/tensorclass.py", line 1026, in wrapped_func
    result = getattr(td, funcname)(*args, **kwargs)
  File "/Users/ignaciobartol/docathon/tensordict/tensordict/utils.py", line 1129, in newfun
    return fun(_self, *args, **kwargs)
  File "/Users/ignaciobartol/docathon/tensordict/tensordict/base.py", line 4708, in _values_list
    return [source[key] for key in sorting_keys]

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

============================================================ short test summary info =============================================================
FAILED test/test_compile.py::TestTC::test_tc_arithmetic_other_tc - AssertionError: 

```

which is in `def test_tc_arithmetic_other_tc(self)` but I am not getting any error in `def test_tc_arithmetic(self)`.

**Comment by anijain2305** [comment]
@vmoens I think this should be solved by https://github.com/pytorch/pytorch/pull/130169

I wrote a small testcase from the code pointer you shared, and it passes. Can you please confirm this on TensorDict? Assigning to you for now, but please assign me back if the issue still persists.

**Comment by anijain2305** [comment]
It works. Closing.
