### ISSUE TITLE
Support dlpack for device privateuseone 

### ISSUE THREAD

**Issue by lixin-sxty** [pytorch/pytorch#129652]
### 🚀 The feature, motivation and pitch

Currently, dlpack-related functions in PyTorch like _getDLDevice()_ do not include device privateuseone, so custom backend users can not support dlpack on some non-CUDA devices. Could you support this feature in the future? I appreciate any information.

cc @bdhirsh @NmomoN @mengpenghui @fwenguang @cdzhan @1274085042 @PHLens

**Comment by bdhirsh** [comment]
cc @albanD

**Comment by albanD** [comment]
Making this code call into the PrivateUse1HooksInterface such that it can be implemented by each privateuse1 backend sounds like a good idea yes! We would accept a PR adding that hook to core for sure!
