### ISSUE TITLE
Failed to compute shorthash for libnvrtc.so

### ISSUE THREAD

**Issue by judicaelclair** [pytorch/pytorch#129777]
With latest `main`, I get  warning 
```
CMake Warning at [..]/torch/share/cmake/Caffe2/public/cuda.cmake:150 (message):
  Failed to compute shorthash for libnvrtc.so
```
I believe this bug was introduced by 479ce5e2f4f100d480c4b8fe4109de7460b2f00b as cmake now attempts to use the `Python::Interpreter` target, which cannot be resolved within an `execute_process` context. Should be reverted back to:
```
  if("${Python_EXECUTABLE}" STREQUAL "")
    set(_python_exe "python3")
  else()
    set(_python_exe "${Python_EXECUTABLE}")
  endif()
  execute_process(
      COMMAND "${_python_exe}" -c
```
Alternatively, the python executable path should be manually extracted from `Python::Interpreter`.

### Versions

Torch version db4c7bb7fc2f253ec39b6e40968f65609a4222a9

cc @malfet @seemethere

**Comment by malfet** [comment]
@judicaelclair does it happen when you are building extensions, right?

**Comment by malfet** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/130651 but if the problem reappears, please do not hesitate to comment here or open a new issue.

**Comment by Fr4nk1inCs** [comment]
Getting the same warning with torch-2.5.1.

The `_retval` in https://github.com/pytorch/pytorch/blob/a8d6afb511a69687bbb2b7e88a3cf67917e1697e/cmake/public/cuda.cmake#L133-L138 is `no such file or directory`. But running the same python commands successfully output the hash digest.

**Comment by zhanwenchen** [comment]
@malfet @xuhancn The issue wasn't due to `CUDA_NVRTC_LIB` not existing, but `Python::Interpreter` not existing. Here are my debug outputs by printing:


```console
# cuda.cmake
if(CUDA_NVRTC_LIB AND NOT CUDA_NVRTC_SHORTHASH)
  find_package(Python COMPONENTS Interpreter REQUIRED)
  execute_process(
    COMMAND ${Python_EXECUTABLE} -c
    # "import hashlib;hash=hashlib.sha256();print(f'CUDA_NVRTC_LIB=${CUDA_NVRTC_LIB}')"
    "import hashlib;hash=hashlib.sha256();hash.update(open('${CUDA_NVRTC_LIB}','rb').read());print(hash.hexdigest()[:8])"
    RESULT_VARIABLE _retval
    OUTPUT_VARIABLE CUDA_NVRTC_SHORTHASH)
  message(STATUS "Python_EXECUTABLE=(${Python_EXECUTABLE}); Python_INTERPRETER=(${Python_INTERPRETER}); _retval=${_retval}. CUDA_NVRTC_LIB=${CUDA_NVRTC_LIB}")

  if(NOT _retval EQUAL 0)
.......

# output:
  -- Python_EXECUTABLE=(/miniconda3/bin/python); Python_INTERPRETER=(); _retval=0. CUDA_NVRTC_LIB=/usr/local/cuda-12.6/lib64/libnvrtc.so
```
