### ISSUE TITLE
UNSTABLE pull / before-test / llm-retrieval

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#129717]
The jobs fail with Unexpected HTTP response: 429 (Too Many Requests) when downloading miniconda: https://hud.pytorch.org/pytorch/pytorch/commit/67416a2996349a2339328cac0f7e54c7d3b3c1d9#26785521099

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Closing as job was removed by https://github.com/pytorch/pytorch/pull/129722
