### ISSUE TITLE
aot_compile unintuitive error with make_fx graphs

### ISSUE THREAD

**Issue by yushangdi** [pytorch/pytorch#129719]
### 🐛 Describe the bug

The code below gives error

```python
import torch
import os
from torch.fx.experimental.proxy_tensor import make_fx

class M(torch.nn.Module):
    def forward(self, x, y):
        return x+ y

inp = torch.rand(1)
inp2 = torch.rand(1)
args = (inp, inp2)

gm = make_fx(M(), tracing_mode="symbolic")(inp, inp2)
print(gm)
so = torch._inductor.aot_compile(gm, args)
```

```
<lambda>()



def forward(self, arg0_1, arg1_1):
    add = torch.ops.aten.add.Tensor(arg0_1, arg1_1);  arg0_1 = arg1_1 = None
    return add
    
# To see more debug info, please use `graph_module.print_readable()`
Traceback (most recent call last):
  File "/home/shangdiy/pytorch/../test.py", line 36, in <module>
    so = torch._inductor.aot_compile(gm, args)
  File "/home/shangdiy/pytorch/torch/_inductor/__init__.py", line 105, in aot_compile
    return compile_fx_aot(
  File "/home/shangdiy/pytorch/torch/_inductor/compile_fx.py", line 1191, in compile_fx_aot
    assert os.path.exists(
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not function
```

The code below runs fine:

```python
gm = torch.export.export(M(), args).module()
print(gm)
so = torch._inductor.aot_compile(gm, args)
```

### Versions

Collecting environment information...
PyTorch version: 2.5.0a0+gite47603a
Is debug build: True
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.34

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.12.0-0_fbk16_zion_7661_geb00762ce6d2-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PG509-200
GPU 1: NVIDIA A100-PG509-200
GPU 2: NVIDIA A100-PG509-200
GPU 3: NVIDIA A100-PG509-200
GPU 4: NVIDIA A100-PG509-200
GPU 5: NVIDIA A100-PG509-200
GPU 6: NVIDIA A100-PG509-200
GPU 7: NVIDIA A100-PG509-200

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          192
On-line CPU(s) list:             0-191
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8339HC CPU @ 1.80GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       4
Stepping:                        11
Frequency boost:                 enabled
CPU(s) scaling MHz:              100%
CPU max MHz:                     1801.0000
CPU min MHz:                     800.0000
BogoMIPS:                        3600.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       3 MiB (96 instances)
L1i cache:                       3 MiB (96 instances)
L2 cache:                        96 MiB (96 instances)
L3 cache:                        132 MiB (4 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-23,96-119
NUMA node1 CPU(s):               24-47,120-143
NUMA node2 CPU(s):               48-71,144-167
NUMA node3 CPU(s):               72-95,168-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.11.0
[pip3] torch==2.5.0a0+gitd8618d1
[pip3] triton==2.3.1
[pip3] triton-nightly==3.0.0.post20240622150414
[conda] blas                      1.0                         mkl  
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-include               2023.1.0         h06a4308_46344  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] torch                     2.5.0a0+gitd8618d1           dev_0    <develop>
[conda] torchfix                  0.4.0                    pypi_0    pypi
[conda] triton                    2.3.1                    pypi_0    pypi
[conda] triton-nightly            3.0.0.post20240622150414          pypi_0    pypi

cc @desertfire @chenyang78 @penguinwu

**Comment by yushangdi** [comment]
@angelayi 's observation about the bug source:

make_fx is returning a slightly invalid graph. Inductor wants all the graphs to return tuple outputs, but make_fx returns the output directly.

graph from make_fx:
```
graph():
    %arg0_1 : [num_users=1] = placeholder[target=arg0_1]
    %add : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%arg0_1, %arg0_1), kwargs = {})
    return add
```

graph from export
```
graph():
    %x : [num_users=1] = placeholder[target=x]
    %add : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%x, %x), kwargs = {})
    return (add,)
```

and since the output is not a tuple, inductor has a pass [here](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/compile_fx.py#L1353-L1358) to make the graph return a tuple. probably, aot inductor doesn’t work well with this pass.

We might want to check the graph before aot_compile and error for the users with a valid error message.

**Comment by awayzjj** [comment]
@angelayi @yushangdi Hi, I would love to contribute! Could you please assign this task to me?

I want to confirm that the task is to check if the graph return tuple at the beginning of `aot_compile`
https://github.com/pytorch/pytorch/blob/999eec8deab9c54343730fedcfefad8fe2932e6d/torch/_inductor/__init__.py#L32-L52

using the function similar with  `graph_returns_tuple`
https://github.com/pytorch/pytorch/blob/999eec8deab9c54343730fedcfefad8fe2932e6d/torch/_inductor/compile_fx.py#L1581-L1596

and error for the users with a valid error message if the function return False?

**Comment by angelayi** [comment]
Yup, that's correct! Thanks so much!
