### ISSUE TITLE
self-driving car

### ISSUE THREAD

**Issue by 1716775457damn** [pytorch/pytorch#129745]
### 🚀 The feature, motivation and pitch

I want to use mmdetection3d point cloud classification as one of the factor for my self-driving car ,whereas,from my point of view the biggest promlem is the degree of precision in realtime using,for instance self-driving acr

**Comment by ashok2216-A** [comment]
Can I help you

**Comment by malfet** [comment]
Please use issues to report bugs/feature requests against PyTorch and use https://discuss.pytorch.org/ to ask generic question. Closing this one, as question about mmdetection3rd are unrelated to core PyTorch
