### ISSUE TITLE
torchvision install error

### ISSUE THREAD

**Issue by Lordores** [pytorch/pytorch#12981]
Sorry to trouble you, but I get some error when I start pytorch
I set 
- PyTorch Build —— Stable
- Your OS——Windows
- Package——Conda
- Language——Python 3.6
- CUDA——8.0

It shows 
Run this Command:
`conda install pytorch cuda80 -c `pytorch`
`pip3` install torchvision`

The first command is alright, shows  # All requested packages already installed. And I can import torch.
But the second command shows:
```
Requirement already satisfied: torchvision in c:\program files (x86)\python36-32\lib\site-packages (0.2.1)
Requirement already satisfied: numpy in c:\program files (x86)\python36-32\lib\site-packages (from torchvision) (1.13.3)
Collecting torch (from torchvision)
  Using cached https://files.pythonhosted.org/packages/5f/e9/bac4204fe9cb1a002ec6140b47f51affda1655379fe302a1caef421f9846/torch-0.1.2.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\qiucy\AppData\Local\Temp\pip-install-xstv3999\torch\setup.py", line 11, in <module>
        raise RuntimeError(README)
    RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

    Please follow the instructions at http://pytorch.org/ to install with miniconda instead.


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\qiucy\AppData\Local\Temp\pip-install-xstv3999\torch\
```
I have tried use `pip install torchvision`, and shows the same message. 
I find 
`Requirement already satisfied: torchvision in c:\program files (x86)\python36-32\lib\site-packages (0.2.1)` 
 in the error message,But
```
import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torchvision'
```

**Comment by Lordores** [comment]
> Neither your pip nor pip3 point to the one that pytorch was installed in.

Means my pip or pip3 and pytorch install in different environment？ 《= I am sure they are in the same environment. And my pip also use python3.6
`E:\mypro\ESPCN-master>pip --version
pip 18.1 from c:\program files (x86)\python36-32\lib\site-packages\pip (python 3.6)`
> Please consider using absolute path for certain pip.

**Comment by peterjc123** [comment]
You can do the following in CMD to install torchvision very quickly. However, I'd suggest that you clean your environment a little bit.
```cmd
:: Detect where your python is
where python.exe
where conda.exe
:: The example output for the last two commands: (Only first line)
:: C:\Anaconda2\python.exe
:: C:\Anaconda2\Scripts\conda.exe

:: Use the pip that lives with conda
"C:\Anaconda2\Scripts\pip.exe" -install torchvision

:: To clean your environment, adjust your environmental variable PATH and 
:: make sure the output (first line) of the first two commands point to the same environment.

```

**Comment by Lordores** [comment]
thanks a lot
