### ISSUE TITLE
`device` is displayed differently with or without `print()` on the IPython based editors like Jupyter notebook or Colab

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#129814]
### 🐛 Describe the bug

[device](https://pytorch.org/docs/stable/tensor_attributes.html#torch.device) is displayed differently with or without [print()](https://docs.python.org/3/library/functions.html#print) on the [IPython](https://ipython.org/) based editors like [Jupyter notebook](https://jupyter.org/) or [Colab](https://colab.research.google.com/) as shown below:

```python
import torch

my_tensor = torch.tensor([0, 1, 2], device='cpu')

# With `print()`
print(my_tensor.device) # cpu

# Without `print()`
my_tensor.device # device(type='cpu')

my_tensor = torch.tensor([0, 1, 2], device='cuda:0')

# With `print()`
print(my_tensor.device) # cuda:0

# Without `print()`
my_tensor.device # device(type='cuda', index=0)
```

In addition, [dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch-dtype) is displayed normally with or without `print()` as shown below:

```python
import torch

my_tensor = torch.tensor([0, 1, 2], dtype=torch.int32)

# With `print()`
print(my_tensor.dtype) # torch.int32

# Without `print()`
my_tensor.dtype # torch.int32
```

### Versions

```python
import torch

torch.__version__ # 2.3.0
```

**Comment by malfet** [comment]
@hyperkai why do you think this is a bug? And please use https://discuss.pytorch.org to ask general question about why PyTorch is doing X vs Y and use issues to file bugs/feature requests.

`torch.device` has both `__str__` and `__repr__` methods defined, while dtype is not.
```
% python3 -c "import torch; d=torch.device('cuda:15'); print(str(d), repr(d))"
cuda:15 device(type='cuda', index=15)
```
See https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr for more details why those functions can return different values.

But I guess `torch.dtype` is not. If you wish to add `__str__` method to torch.dtype, please either open an issue arguing why it is needed or propose a PR
