### ISSUE TITLE
NVIDIA runners have a blacklog of 2000+ jobs

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#129880]
## Current Status
*Status could be:  ongoing*.
See 
<img width="756" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/f3cf22b7-63a8-4651-bc8d-3a8821afea72">

## Error looks like
One can not get any signal from CI, merge jobs will likely to timeout

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*
11:45AM PST Root-caused to a missing AmazonLinux 2 kernel headers

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Number of jobs in queue grew to 3000k at 11:12AM PST

**Comment by malfet** [comment]
Jumped into i-0558734ae8b7cdf9c  to see what is going on

**Comment by seemethere** [comment]
Perhaps running a trap to set the status of the runner on AWS would be beneficial here, we can also do this with a label

**Comment by malfet** [comment]
Number of jobs in the queue dropped down to 1999 and queue time down to 6h

**Comment by awayzjj** [comment]
@malfet  HI, I wonder if we could merge PR now?

**Comment by malfet** [comment]
@awayzjj what PR are you referring to? But yes, you can, this was never a merge blocking SEV

**Comment by awayzjj** [comment]
@malfet Got it! Thank you. My PR is https://github.com/pytorch/pytorch/pull/129839 it wat timeout 9 hours ago.

**Comment by clee2000** [comment]
cc @jeanschmidt I remember seeing a PR for adding logging or other monitoring to user-data.sh to see if setting up the runner succeeded, does that resolve [Eli's comment ](https://github.com/pytorch/pytorch/issues/129880#issuecomment-2200873262)?

**Comment by malfet** [comment]
Removing high priority, as issue has been mitigated, but I'm curious of Cold Storage is the right classification for this one

@jeanschmidt I believe we have the alert for runners failing to spin up right now, don't we? If so, I think this one can be closed

**Comment by jeanschmidt** [comment]
sure we do have monitoring and alerts set up for this, so I am closing this as for now.
