### ISSUE TITLE
How does pytorch implement the warp function?

### ISSUE THREAD

**Issue by changshuangzhao** [pytorch/pytorch#12982]
Hello！

For example, in the Cascade Residual Learning：A Two-stage Convolutional Neural Network for Stereo Matching, the first network takes as input the stereo pair I_L and I_R and produces the initial disparity d1 (of the left image). We then warp the right Image I_R according to disparity d1 and obtain a synthesized left image.

Looking forward to your good news！！

**Comment by zou3519** [comment]
What exactly is the "warp" function?

**Comment by zou3519** [comment]
Closing due to not enough information.
