### ISSUE TITLE
Initialisation docs should mention that `weight` matrices are transposed 

### ISSUE THREAD

**Issue by sradc** [pytorch/pytorch#129834]
### 📚 The doc issue

The docs do not mention that weight matrices are assumed to be initialised as: `w.shape = [fan_out, fan_in]`, because Pytorch linear layers do: `h = x @ w.T + b`

Many people initialising weights themselves would do: `w.shape = [fan_in, fan_out]` and `h = x @ w + b`; leading to subtle bugs — unless they compare the variance of the weight matrix with the variance of the Pytorch linear layers, and look into the source code, they may not catch that the `[fan_in, fan_out]` used by the initialization function is not what they expect.

### Suggest a potential alternative/fix

The initialisation functions should clearly state that this is the case.

--- 

### Relevant links / examples of confusion caused

- https://stackoverflow.com/questions/53462493/shape-of-pytorch-model-parameter-is-inconsistent-with-how-its-defined-in-the-mo/
- https://stackoverflow.com/questions/53465608/pytorch-shape-of-nn-linear-weights
- https://github.com/pytorch/pytorch/issues/2159

cc @svekars @brycebortree @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by malfet** [comment]
It looks like it's clearly documented in https://pytorch.org/docs/stable/generated/torch.nn.Linear.html#torch.nn.Linear
> Applies a linear transformation to the incoming data: 
> $𝑦 = 𝑥 𝐴^𝑇+𝑏$

But if you have a suggestion how it could be further improved, please do not hesitate to write a PR

**Comment by sradc** [comment]
Hey @malfet; although it's documented in the linear layer, it's not documented in the initialisation functions. I've created an MR with the kind of note I think would be helpful: https://github.com/pytorch/pytorch/pull/130122
