### ISSUE TITLE
Constructors of CUDA tensors are slow when given iterables

### ISSUE THREAD

**Issue by John-Jumper** [pytorch/pytorch#1299]
The creation time for creating a GPU FloatTensor with a numpy array is much slower than creating a CPU FloatTensor then transferring with `.cuda()`; it also depends very strongly on the number of dimensions.  I know now that I should be using `torch.from_numpy(x).cuda()`, but the performance cliff going from CPU to GPU FloatTensor's was very surprising.

The following program demonstrates the issue:
```
import numpy as np
import torch
import torch.cuda as cu
import contextlib
import time

# Timing helper with CUDA synchonization
@contextlib.contextmanager
def timing(name):
    cu.synchronize()
    start_time = time.time()
    yield
    cu.synchronize()
    end_time = time.time()
    print '{} {:6.3f} seconds'.format(name, end_time-start_time)

for shape in [(128**3,), (128,128**2), (128,128,128), (32,32,32,64)]:
    print 'shape {}, {:.1f} MB'.format(shape, np.zeros(shape).nbytes/1024.**2)

    with timing('from_numpy sent to GPU     '): torch.from_numpy (np.zeros(shape)).cuda()
    with timing('CPU constructor            '): torch.FloatTensor(np.zeros(shape))
    with timing('CPU constructor sent to GPU'): torch.FloatTensor(np.zeros(shape)).cuda()
    with timing('GPU constructor            '): cu.   FloatTensor(np.zeros(shape))
    print
```

I get the following output:
```
shape (2097152,), 16.0 MB
from_numpy sent to GPU       0.003 seconds
CPU constructor              0.065 seconds
CPU constructor sent to GPU  0.066 seconds
GPU constructor              0.065 seconds

shape (128, 16384), 16.0 MB
from_numpy sent to GPU       0.004 seconds
CPU constructor              0.066 seconds
CPU constructor sent to GPU  0.068 seconds
GPU constructor              0.183 seconds

shape (128, 128, 128), 16.0 MB
from_numpy sent to GPU       0.004 seconds
CPU constructor              0.069 seconds
CPU constructor sent to GPU  0.070 seconds
GPU constructor             16.038 seconds

shape (32, 32, 32, 64), 16.0 MB
from_numpy sent to GPU       0.004 seconds
CPU constructor              0.072 seconds
CPU constructor sent to GPU  0.073 seconds
GPU constructor             32.051 seconds
```

Notice the large time required to call the GPU tensor `__init__` (fourth line) when using 3 or 4 dimensions.  All of the arrays have to same number of elements.  Independently, I was unable to initialize a GPU FloatTensor using an numpy array of dtype `float32` due to a type error.  This seems like an odd limitation, and the CPU FloatTensor has no such limitation.

I am using PyTorch 0.1.11+9150e33 compiled from source on Ubuntu 16.04.2 with CUDA 8.0 and Python 2.7.12.  I have a Intel Core i5-4670 and NVIDIA GTX 1080 Ti.

**Comment by apaszke** [comment]
This is expected because the numpy arrays have `dtype=float64`. Because of this:
1. `torch.from_numpy(x).cuda()` will create a `torch.DoubleTensor` without any memory copy, and will then send it to the GPU (very fast)
2. `torch.FloatTensor(x)` will **treat the numpy array as a regular Python iterable (e.g. a list)** and will read elements one by one, initializing the memory.
3. `torch.FloatTensor(x).cuda()` same as 2.
4. This really seems like a bug, but I'd say that it's a low priority one. You shouldn't be doing that anyway.

**Comment by John-Jumper** [comment]
Normally, I would use `dtype=float32`, but that is an error when constructing `cuda.FloatTensor`.  The 4th timing was the big surprise; all of the other ones are mainly to show that nothing else too weird is happening.  

I agree this is a low priority issue, but I might suggest just calling `PyArray_FromAny`, possibly with `NPY_ARRAY_ENSURECOPY`, when you receive an arbitrary Python object in the constructor.  That should be very fast when the iterable is already a numpy array.

```
In [1]: import torch.cuda

In [2]: import numpy as np

In [3]: torch.cuda.FloatTensor(np.zeros(10, dtype=np.float64))
Out[3]: 

 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
[torch.cuda.FloatTensor of size 10 (GPU 0)]

In [4]: torch.cuda.FloatTensor(np.zeros(10, dtype=np.float32))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-f0aeef8e6446> in <module>()
----> 1 torch.cuda.FloatTensor(np.zeros(10, dtype=np.float32))

RuntimeError: tried to construct a tensor from a float sequence, but found an item of type numpy.float32 at index (0)
```

**Comment by melspectrum007** [comment]
The same problem happened to me, and it was solved when I re-install pytorch from pytorch source code.

**Comment by SsnL** [comment]
Seems to be fixed :)
