### ISSUE TITLE
MacOS queue is 1+ hour long

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#129957]
Companion issue to https://github.com/pytorch/pytorch/issues/129880
Mac runner queues never reached the length of NVIDIA runners queue, but we only have 25 macos-stable runners at the moment instead of 70, which will likely lead to the queueing during the day
<img width="761" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/94015288-361d-4b73-840e-debc942e0a9c">

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Q to the people on the review: how sensitive you are to the queue times?

**Comment by zou3519** [comment]
> Q to the people on the review: how sensitive you are to the queue times?

Answer from triage review: not very, linux-cuda is more important and as long as queue times don't make time to signal go ridiculous

**Comment by clee2000** [comment]
Closing as the mac queue has gone down and I'm not sure what the desired AI is here.  Please re open if you want to add
