### ISSUE TITLE
How to get stream operators in custom backend compiler ?

### ISSUE THREAD

**Issue by wbigat2** [pytorch/pytorch#129949]
### 🐛 Describe the bug

Hi, when I use a custom backend, I find that the fx graph that custom compiler gets does not have the stream related operations.

Then I found that the fx graph dropped those stream operations after aot_module_simplified.
So, I want to know how can we get a fx graph that contains stream-related operations, when using aot_module_simplified and custom compiler?

cc @ezyang @anijain2305 @chauhang @penguinwu @zou3519 @ptrblck @msaroufim 

Here is my test script. 

```
import torch
import torch.nn as nn
class Layer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        stream2 = torch.cuda.Stream()
        with torch.cuda.stream(stream2):
            z = x + 1
        y = x - 1
        return y + z

mm = Layer()
x=torch.randn([4]).cuda()

from torch._functorch.aot_autograd import aot_module_simplified
def toy_backend(gm, sample_inputs):
    return gm
def aot_toy_backend(gm, sample_inputs):
    return aot_module_simplified(gm, sample_inputs, fw_compiler=toy_backend)

mmc = torch.compile(mm, backend=aot_toy_backend)
yc= mmc(x)
```

 When I use aot_toy_backend backend, no stream related ops in gx graph.

### Versions

pytorch 2.3.0

**Comment by ezyang** [comment]
cc @yf225

**Comment by wbigat2** [comment]
> cc @yf225

Can you give me some guidance or advice on this issue? Thank you very much.  @yf225

**Comment by wbigat2** [comment]
Close this issue and continue the discussion in the new issue,  https://github.com/pytorch/pytorch/issues/130137
