### ISSUE TITLE
LayoutLMForMaskedLM generates NaN in Max-autotune mode with cuda-graph enabled

### ISSUE THREAD

**Issue by shunting314** [pytorch/pytorch#130000]
### 🐛 Describe the bug

Running the model for training with cuda-graphs enables
```
TORCHINDUCTOR_MAX_AUTOTUNE=1 time python benchmarks/dynamo/huggingface.py --accuracy --no-translation-validation --training --amp --backend inductor --device cuda --only LayoutLMForMaskedLM
```
we get error
```
RMSE (res-fp64): nan, (ref-fp64): 0.00240 and shape=torch.Size([768]). res.dtype: torch.float32, multiplier: 3.000000, tol: 0.010000
```

Note that the torch.compile generated tensor contains NaN. But if we disable cudagraphs, the test pass

```
TORCHINDUCTOR_MAX_AUTOTUNE=1 time python benchmarks/dynamo/huggingface.py --accuracy --no-translation-validation --training --amp --backend inductor --device cuda --only LayoutLMForMaskedLM --disable-cudagraphs
```

cc @mcarilli @ezyang @eellison @penguinwu @anijain2305 @chauhang for cudagraphs

### Versions

.

**Comment by eellison** [comment]
I couldn't repro this, cc @BoyuanFeng can you ?

**Comment by shunting314** [comment]
Interesting. It fails quite stably on the dashboard and my local run. Here is the log from my local run: https://gist.github.com/shunting314/609eb9d6b60a84379f8c3b743a82d38a 

One thing I found is, for some of the matmuls my log pick different triton configs compared to yours. E.g. for the first matmul, my log picks 
```
  triton_mm_130 0.0209 ms 100.0% ACC_TYPE='tl.float32', ALLOW_TF32=False, BLOCK_K=64, BLOCK_M=128, BLOCK_N=128, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, num
_stages=3, num_warps=4
```
while your log picks
```
  triton_mm_131 0.0128 ms 100.0% ACC_TYPE='tl.float32', ALLOW_TF32=False, BLOCK_K=64, BLOCK_M=128, BLOCK_N=128, B_PROLOGUE_CAST_TYPE=None, EVEN_K=True, GROUP_M=8, num_stages=5, num_warps=8
```
Note that num_stages and num_warps are different.


FWIW, my triton commit is quite old:
```
commit 45fff310c891f5a92d55445adf8cc9d29df5841e 
Author: Lei Zhang <antiagainst@gmail.com>
Date:   Sat Mar 30 12:03:43 2024 -0700
```
I'll also try the pined version

**Comment by shunting314** [comment]
Using pinned triton, I can still repro the issue. @BoyuanFeng @eellison  maybe check if you are using pinned version for other libraries like transformer

**Comment by eellison** [comment]
I checked out the pinned transformers and pinned triton and it still passed. Additionally `LayoutLMForMaskedLM` passes with cudagraphs (no max autotune) on the nightly.
