### ISSUE TITLE
There is an error in the description of torch.Tensor.scatter_（） in the document

### ISSUE THREAD

**Issue by sealoongleft** [pytorch/pytorch#130024]
### 📚 The doc issue

The problematic website is：https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_.html#torch.Tensor.scatter_

error description screenshot：
![image](https://github.com/pytorch/pytorch/assets/48373656/8da676b4-0239-436e-a02c-af6edc7bf490)
finding：After my actual testing, I found that it is not arbitrary assignment, but using the last value.
validation code as follows：
![image](https://github.com/pytorch/pytorch/assets/48373656/7e89f82a-07d3-4814-94cc-a931635c937c)
When the src [i][j] is [0][0] and [1][0], r will have two values at [0][0], which are 1 and 4, respectively. However, no matter how the program is run, r will always take a value of 4 at [0][0].

### Suggest a potential alternative/fix

Suggest deleting this description or rewriting it.
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by zou3519** [comment]
We say that it is arbitrary because the behavior is undefined -- anything is reasonable

**Comment by sealoongleft** [comment]
I thought I found a documentation error. What a shame. But thank you for your prompt reply

**Comment by malfet** [comment]
Closing, as it works as document: non-deterministic does not mean that selected element will be different every time, but rather than we make no guarantee about the pattern for different devices, shapes or different PyTorch version

**Comment by sealoongleft** [comment]
ok，thansk a lot for your support.
