### ISSUE TITLE
Windows nightly Wheel and Libtorch builds are broken Jul 3, 2024

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#130034]
### 🐛 Describe the bug

Following nightly  failure:
https://github.com/pytorch/pytorch/actions/runs/9773735196/job/26980503170

```
------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :     12267     12267         0         0         0         0
   Files :     86211     86211         0         0         0         0
   Bytes :   1.452 g   1.452 g         0         0         0         0
   Times :   0:02:44   0:02:28                       0:00:00   0:00:15


   Speed :            10468373 Bytes/sec.
   Speed :             599.005 MegaBytes/min.
   Ended : Wednesday, July 3, 2024 8:13:21 AM

CMake is required to compile PyTorch on Windows
Error: Process completed with exit code 1.
```

One of the commit caused the failure:
https://github.com/pytorch/pytorch/commit/6d35c780e0030a45113d4d8b4534dc39d9e2cff6

### Versions

2.5.0 nightly

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @malfet @osalpekar @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Hmm, I don't think so, as error comes from the builder repo: https://github.com/pytorch/builder/blob/809994ae1a24e5129bea4a2733e6c0aa9dc06437/windows/internal/check_deps.bat#L14

**Comment by atalman** [comment]
Looks like culprit maybe https://github.com/pytorch/pytorch/pull/129851

**Comment by malfet** [comment]
Kicked a re-run of https://github.com/pytorch/pytorch/actions/runs/9740083172/job/26876496550 (as https://github.com/pytorch/pytorch/actions/runs/9740083172/job/27002827238 ) to see if culprit is PyTorch or builder change

**Comment by malfet** [comment]
Also, libtorch builds on trunk started to fail https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=libtorch suggests that something have changes between 6 and 7PM PST yesterday, last passing commit: https://hud.pytorch.org/pytorch/pytorch/actions/runs/9769847920/job/26970059014 first failing commit https://hud.pytorch.org/pytorch/pytorch/actions/runs/9770464986/job/26972271966

**Comment by atalman** [comment]
On failure I do see:
```
 50 73.8M   50 37.5M    0     0   303M      0 --:--:-- --:--:-- --:--:--  307M
100 73.8M  100 73.8M    0     0   347M      0 --:--:-- --:--:-- --:--:--  350M
Collecting package metadata (current_repodata.json): ...working... failed

UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

So its related to this PR: https://github.com/pytorch/builder/commit/eebc2f0526382153b42e4b4779971a18732baa86

**Comment by atalman** [comment]
Testing proposed fix here: https://github.com/pytorch/pytorch/pull/130035
