### ISSUE TITLE
Model training time increase more than 10x in some case

### ISSUE THREAD

**Issue by s1030512149** [pytorch/pytorch#130022]
### 🐛 Describe the bug

Code:
```
import torch
para =torch.Tensor(initial_para)
x,y  = torch.tensor(x),torch.relu(torch.tensor(y))
para.requires_grad = True
loss = torch.nn.MSELoss()
optimizer = torch.optim.Adam([para], lr=lr)
for i in `range(max_iter):`
    y_fit = multi_gaussian(x,para)
    l = loss(y_fit,y)
    try:
        if torch.isnan(l) or torch.isinf(l) :
            print("l is nan or inf")
            break
        l.backward()
        optimizer.step()
        optimizer.zero_grad()
    except:
        break
def multi_gaussian(x, params):
    y = torch.zeros_like(x)
    for i in range(0, params.shape[0], 3):
        g = gaussian(x, params[i], params[i + 1], params[i + 2])
        if torch.any(torch.isnan(g)) or torch.any(torch.isinf(g)):
            continue
        y = y + g
    return y
def gaussian(x,center,amp,variance, offset = None):
    return amp*torch.exp(-(x-center)**2/(variance ))
```
Hi, im using pytorch to fit gaussian mixture model. It works perfect via directly run main.py. My data had length of 1024, and it only took less than 0.1 s to fit the model. However, a strange issue occurred when I using PythonNet package in CSharp.  After the python environment was initialized, the main.py was also successfully runned. But the time for model fit increased to nearly 1.8 s, 18 times slower than previous condition.
While i used another fit methed named scipy.optimize.curve_fit method, it tooks almost the same time (0.03 s) as run main.py directly or by CSharp code call. I was so confused by the difference, and I want to know if there is way to solve the problem.

(By the way, im coding my program in net4.8 framework, i cant using torchsharp in Csharp which need net6.0).

Thank a lot!

### Versions

PyTorch version: 2.3.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 家庭中文版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.29.0-rc3
Libc version: N/A

Python version: 3.10.14 | packaged by Anaconda, Inc. | (main, Mar 21 2024, 16:20:14) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: False
CUDA runtime version: 12.4.99
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4060 Laptop GPU
Nvidia driver version: 556.12
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2516
DeviceID=CPU0
Family=107
L2CacheSize=8192
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3801
Name=AMD Ryzen 7 8845H w/ Radeon 780M Graphics
ProcessorType=3
Revision=29954

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.3.0
[pip3] torchaudio==2.3.0
[pip3] torchvision==0.18.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0                 pypi_0    pypi
[conda] mkl-service               2.4.0           py310h2bbff1b_1
[conda] mkl_fft                   1.3.8           py310h2bbff1b_0
[conda] mkl_random                1.2.4           py310h59b6b97_0
[conda] numpy                     1.26.4          py310h055cbcc_0
[conda] numpy-base                1.26.4          py310h65a83cf_0
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] torchaudio                2.3.0                    pypi_0    pypi
[conda] torchvision               0.18.0                   pypi_0    pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by malfet** [comment]
It feels like you need to file an issue against https://github.com/dotnet/TorchSharp
