### ISSUE TITLE
`torch.backends.cuda.sdp_kernel(enable_flash=True)` causes graph breaks

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#130098]
### 🐛 Describe the bug

```
import torch

@torch.compile(fullgraph=True)
def f(q, k, v):
    q = torch.cos(q)
    with torch.backends.cuda.sdp_kernel(enable_flash=True):
        return F.scaled_dot_product_attention(q, k, v)

f(*[torch.randn(1,8,1024,64, dtype=torch.float16) for _ in range(3)])
```

cc: @drisspg @yanboliang 

### Versions

N/A

cc @ezyang @anijain2305 @chauhang @penguinwu

**Comment by drisspg** [comment]
I think I reported this a while ago 

Also use the non deprecated one

**Comment by Chillee** [comment]
Why is it still listed here: https://pytorch.org/docs/main/generated/torch.nn.functional.scaled_dot_product_attention.html#torch-nn-functional-scaled-dot-product-attention

**Comment by vadimkantorov** [comment]
would 
```python
with torch.backends.cuda.sdpa_kernel(backends=[SDPBackend.MATH]):
    F.sdpa(...)
```

be traceable by torch.compile?

I think it would be much better if these backend settings could be passed directly to `F.sdpa(...)`

As sometimes numerics change during passing from MATH to FA, keeping sdpa kernel exposed to outer config is a must, so if it then breaks torch.compile, this is a deal breaker :(

**Comment by anijain2305** [comment]
cc @williamwen42

**Comment by williamwen42** [comment]
Added sdpa_kernel tracing support in https://github.com/pytorch/pytorch/pull/135404. Will close this since sdp_kernel is now deprecated.
