### ISSUE TITLE
Checkout action fails due to incompatible GLIBC

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#130041]
## Current Status
*mitigated*.

## Error looks like
```
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/ec2-user/actions-runner/_work/pytorch/pytorch/test-infra/.github/actions/teardown-linux'. Did you forget to run actions/checkout before running your local action?
```
Which is caused by the error during the checkout step
```
/home/ec2-user/actions-runner/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/ec2-user/actions-runner/externals/node20/bin/node)
```

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
GitHub runner update and our infra stuck on insecure AL2

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Workaround so far is to define `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true` enfironment variable to use node-16 temporarily

**Comment by clee2000** [comment]
I'm going to close this since the sev was mitigated and preventing this in the future falls under https://github.com/pytorch/pytorch/issues/122115 (upgrading the AMI)
