### ISSUE TITLE
`amax()` with an empty 1D tensor still gets error even if setting `dim=0` to it

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130187]
### 🐛 Describe the bug

[amax()](https://pytorch.org/docs/stable/generated/torch.amax.html) with an empty 1D tensor gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.amax(input=my_tensor) # Error
```

> RuntimeError: amax(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

So, I set `dim=0` to `amax()` following the error message above but it still gets other error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.amax(input=my_tensor, dim=0) # Error
```

> IndexError: amax(): Expected reduction dim 0 to have non-zero size.

In addition, `amax()` with an empty 2D or 3D  tensor also gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.amax(input=my_tensor) # Error

my_tensor = torch.tensor([[[]]])

torch.amax(input=my_tensor) # Error
```

> RuntimeError: amax(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

But setting `dim=0` to `amax()` following the error message above works properly as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.amax(input=my_tensor, dim=0)
# tensor([])

my_tensor = torch.tensor([[[]]])

torch.amax(input=my_tensor, dim=0)
# tensor([], size=(1, 0))
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by albanD** [comment]
This all look like expected behavior to me.
Feel free to re-open with details on what you think is not correct.
