### ISSUE TITLE
MPS backend out of memory

### ISSUE THREAD

**Issue by Antonio-Moura-Coutinho** [pytorch/pytorch#130112]
### 🐛 Describe the bug

I am training a model and this error appears I have already did  export PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
and still happening ...

### Error logs

 return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: MPS backend out of memory (MPS allocated: 5.50 GB, other allocations: 14.76 GB, max allowed: 20.40 GB). Tried to allocate 147.24 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

### Versions

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23357  100 23357    0     0  22924      0  0:00:01  0:00:01 --:--:-- 22944
(venv) amc@MacBook-Pro-de-Antonio ESC_Fine_Tunning % python3 collect_env.py
Collecting environment information...
PyTorch version: 2.3.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.6
Libc version: N/A

Python version: 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.3.1
[pip3] torchaudio==2.3.1
[pip3] torchvision==0.18.1
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen @ezyang @anijain2305 @chauhang @penguinwu

**Comment by albanD** [comment]
Hi,

What is your question here? This is expected behavior if you're trying to use more memory than is available.

**Comment by essington62** [comment]
I am having the same problem. running python 3.12.2, pytorch 2.5.1, model microsoft/Phi-3-mini-4k-instruct. 
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# Defina o ID do modelo
#id_model = "gpt2"  # Ou outro modelo de sua escolha, como "distilgpt2" para uma versão menor
id_model = "microsoft/Phi-3-mini-4k-instruct"

# Verifique se o backend MPS está disponível e defina o dispositivo
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
print(f"Usando dispositivo: {device}")

# Carregue o modelo e mova-o para o dispositivo MPS
model = AutoModelForCausalLM.from_pretrained(
    id_model,
    torch_dtype=torch.float32  # Usando float32 para compatibilidade com MPS
).to(device)

# Carregue o tokenizer para o modelo
tokenizer = AutoTokenizer.from_pretrained(id_model)

# Exemplo de uso: geração de texto
prompt = "Explique o que é computação quântica"
inputs = tokenizer(prompt, return_tensors="pt").to(device)

# Geração de texto
output = model.generate(**inputs, max_length=150)
print(tokenizer.decode(output[0], skip_special_tokens=True))
RuntimeError: MPS backend out of memory (MPS allocated: 36.23 GB, other allocations: 2.00 MB, max allowed: 36.27 GB)

The curious thing is that it runs on the CPU in 1:19 minute, s.o. sonoma 4.6.1

**Comment by malfet** [comment]
@essington62 do you mind filing a separate issue? Or start a discussion on https://discuss.pytorch.org. On CPU one has infinite amount of memory, but on GPU memory is limited to physical memory, so may be model indeed needs more than 32Gb to operate.

**Comment by essington62** [comment]
Hi Malfet,
thanks for your attention, I will do this. The point is I have tried many other small models and had the same problem, I was afraid that could be a problem. I will move for the discussion hub
regards
