### ISSUE TITLE
`torch.compile` graph breaks on `TorchFunctionMode`

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#130104]
### 🚀 The feature, motivation and pitch

^

It would be nice if we could enable `TorchFunctionMode` within a compiled region without graph breaks.

cc: @zou3519 @yanboliang 

cc @ezyang @albanD @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @zou3519 @bdhirsh

**Comment by zou3519** [comment]
What kind of TorchFunctionMode do you want to use? IIRC there was a discussion with TorchDispatchMode in that it's unclear what the semantics should be, so the author of the mode needs to help out with declaring the semantics.

**Comment by ezyang** [comment]
@anijain2305 @mlazos this is the issue I was mentioning in our 1:1 Animesh, for the torch function Dynamo rollup

**Comment by Chillee** [comment]
@zou3519 In this case I want to compile this function: https://github.com/pytorch/pytorch/blob/3d56673b24073235eb3beff3f8cf1a88a91ba459/torch/nn/attention/_flex_attention.py#L260

**Comment by mlazos** [comment]
https://github.com/pytorch/pytorch/pull/137121
