### ISSUE TITLE
UNSTABLE trunk / win-vs2019-cpu-py3 / test (default)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#130257]
Test decomp failing with `test_decomp 2/12 failed! Unsupported signal: 2` on windows.  I am marking this as unstable because I want to keep running test_decomp but it is also blocking viable strict update.

Ex https://github.com/pytorch/pytorch/actions/runs/9842354758/job/27173266481

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
https://github.com/pytorch/pytorch/pull/130260 has been landed, so let's close this

**Comment by atalman** [comment]
cpp/quantized_test 1/1 failed: [GH job link](https://github.com/pytorch/pytorch/actions/runs/12091277930/job/33722382573) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/2f72635a5ccac026348b7cd0c4072e7d50a263da)

**Comment by atalman** [comment]
Should be resolved. Reverted https://github.com/pytorch/pytorch/pull/141794
