### ISSUE TITLE
Docs for sparse tensors

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#1303]
We've got sparse tensors and operations on them, but no docs for them. Something like `docs/source/tensors.rst` but for SparseTensor would be a good start.

**Comment by apaszke** [comment]
I wouldn't like to hurry writing docs for sparse tensors. They're still a WIP, and the API is dynamically evolving (e.g. #1302)

**Comment by fmassa** [comment]
What's the status of torch.sparse`? Should we be documenting it, or is it going to go away somehow?
