### ISSUE TITLE
Can't run `test_public_bindings.py` locally

### ISSUE THREAD

**Issue by yushangdi** [pytorch/pytorch#130371]
### 🐛 Describe the bug

I'm running `python test/test_public_bindings.py` locally on the viable/strict branch, and got the error below.

`test_public_bindings.py: error: the following arguments are required: -e/--example` However, if I add `-e` flag, it says there's no `-e` flag. 

```
/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/pkgutil.py:92: DeprecationWarning: `torch.distributed._shard.checkpoint` will be deprecated, use `torch.distributed.checkpoint` instead
  __import__(info.name)
/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/pkgutil.py:92: DeprecationWarning: `torch.distributed._sharded_tensor` will be deprecated, use `torch.distributed._shard.sharded_tensor` instead
  __import__(info.name)
/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/pkgutil.py:92: DeprecationWarning: `torch.distributed._sharding_spec` will be deprecated, use `torch.distributed._shard.sharding_spec` instead
  __import__(info.name)
/home/shangdiy/pytorch/torch/distributed/algorithms/_optimizer_overlap/optimizer_overlap.py:12: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import as_functional_optim
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:326: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/importlib/__init__.py:126: DeprecationWarning: `torch._functorch.pytree_hacks` is deprecated and will be removed in a future release. Please `use torch.utils._pytree` instead.
  return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/coremltools/_deps/__init__.py:47: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return _StrictVersion(version)
WARNING:root:scikit-learn version 1.4.2 is not supported. Minimum required version: 0.17. Maximum required version: 0.19.2. Disabling scikit-learn conversion API.
/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/coremltools/converters/mil/frontend/torch/ops.py:130: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  _np.bool: 11,
/home/shangdiy/pytorch/test/test_public_bindings.py:520: FutureWarning: `torch.distributed.reduce_op` is deprecated, please use `torch.distributed.ReduceOp` instead
  isinstance(obj, (Callable, torch.dtype)) or inspect.isclass(obj)
/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/inspect.py:197: FutureWarning: `torch.distributed.reduce_op` is deprecated, please use `torch.distributed.ReduceOp` instead
  return isinstance(object, type)
usage: test_public_bindings.py [-h] -e EXAMPLE
test_public_bindings.py: error: the following arguments are required: -e/--example
E/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/coremltools/converters/mil/frontend/torch/ops.py:130: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  _np.bool: 11,
usage: test_public_bindings.py [-h] -e EXAMPLE
test_public_bindings.py: error: the following arguments are required: -e/--example
E..
======================================================================
ERROR: test_correct_module_names (__main__.TestPublicBindings)
An API is considered public, if  its  `__module__` starts with `torch.`
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shangdiy/pytorch/torch/testing/_internal/common_utils.py", line 2739, in wrapper
    method(*args, **kwargs)
  File "/home/shangdiy/pytorch/torch/testing/_internal/common_utils.py", line 1363, in wrapper
    fn(*args, **kwargs)
  File "/home/shangdiy/pytorch/test/test_public_bindings.py", line 628, in test_correct_module_names
    test_module(modname)
  File "/home/shangdiy/pytorch/test/test_public_bindings.py", line 505, in test_module
    mod = importlib.import_module(modname)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/shangdiy/pytorch/torch/distributed/_tensor/examples/comm_mode_features_example.py", line 10, in <module>
    from torch.distributed._tensor.examples.comm_mode_features_example_argparser import args
  File "/home/shangdiy/pytorch/torch/distributed/_tensor/examples/comm_mode_features_example_argparser.py", line 18, in <module>
    example = parser.parse_args().example
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/argparse.py", line 1833, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/argparse.py", line 1866, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/argparse.py", line 2107, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/argparse.py", line 2594, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/argparse.py", line 2581, in exit
    _sys.exit(status)
SystemExit: 2

======================================================================
ERROR: test_modules_can_be_imported (__main__.TestPublicBindings)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shangdiy/pytorch/torch/testing/_internal/common_utils.py", line 2739, in wrapper
    method(*args, **kwargs)
  File "/home/shangdiy/pytorch/torch/testing/_internal/common_utils.py", line 1363, in wrapper
    fn(*args, **kwargs)
  File "/home/shangdiy/pytorch/test/test_public_bindings.py", line 316, in test_modules_can_be_imported
    importlib.import_module(modname)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/shangdiy/pytorch/torch/distributed/_tensor/examples/comm_mode_features_example.py", line 10, in <module>
    from torch.distributed._tensor.examples.comm_mode_features_example_argparser import args
  File "/home/shangdiy/pytorch/torch/distributed/_tensor/examples/comm_mode_features_example_argparser.py", line 18, in <module>
    example = parser.parse_args().example
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/argparse.py", line 1833, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/argparse.py", line 1866, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/argparse.py", line 2107, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/argparse.py", line 2594, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/home/shangdiy/.conda/envs/pytorch-3.10/lib/python3.10/argparse.py", line 2581, in exit
    _sys.exit(status)
SystemExit: 2

----------------------------------------------------------------------
Ran 4 tests in 9.274s

FAILED (errors=2)
```

### Versions

Collecting environment information...
PyTorch version: 2.5.0a0+gitc5647dd
Is debug build: True
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.34

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.12.0-0_fbk16_zion_7661_geb00762ce6d2-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PG509-200
GPU 1: NVIDIA A100-PG509-200
GPU 2: NVIDIA A100-PG509-200
GPU 3: NVIDIA A100-PG509-200
GPU 4: NVIDIA A100-PG509-200
GPU 5: NVIDIA A100-PG509-200
GPU 6: NVIDIA A100-PG509-200
GPU 7: NVIDIA A100-PG509-200

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          192
On-line CPU(s) list:             0-191
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8339HC CPU @ 1.80GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       4
Stepping:                        11
Frequency boost:                 enabled
CPU(s) scaling MHz:              100%
CPU max MHz:                     1801.0000
CPU min MHz:                     800.0000
BogoMIPS:                        3600.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       3 MiB (96 instances)
L1i cache:                       3 MiB (96 instances)
L2 cache:                        96 MiB (96 instances)
L3 cache:                        132 MiB (4 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-23,96-119
NUMA node1 CPU(s):               24-47,120-143
NUMA node2 CPU(s):               48-71,144-167
NUMA node3 CPU(s):               72-95,168-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.11.0
[pip3] pytorch_sphinx_theme==0.0.24
[pip3] torch==2.5.0a0+gitd741fe9
[pip3] triton==2.3.1
[pip3] triton-nightly==3.0.0.post20240622150414
[conda] blas                      1.0                         mkl  
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-include               2023.1.0         h06a4308_46344  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     2.5.0a0+gitd741fe9           dev_0    <develop>
[conda] torchfix                  0.4.0                    pypi_0    pypi
[conda] triton                    2.3.1                    pypi_0    pypi
[conda] triton-nightly            3.0.0.post20240622150414          pypi_0    pypi

cc @albanD @ZainRizvi @kit1980 @huydhn @clee2000

**Comment by janeyx99** [comment]
cc @albanD

**Comment by albanD** [comment]
Can you confirm this was fixed by https://github.com/pytorch/pytorch/pull/130497 please ?

**Comment by yushangdi** [comment]
> python test/test_public_bindings.py

yes, it is fixed now. Thanks!!
