### ISSUE TITLE
Add Exponential Moving Average module wrapper in PyTorch

### ISSUE THREAD

**Issue by sidijju** [pytorch/pytorch#130361]
### 🚀 The feature, motivation and pitch

Current state of the art research frequently uses exponential moving average and approaches like it to smooth model weight updates during treaining. In pytorch, this functionality is not yet implemented as a separate module. 

### Alternatives

Currently, there is an EMA Handler in Ignite but it doesn't fit in well with traditional training loops. 

There is also an existing pip library that essentially implements most of the functionality (ema-pytorch). The suggestion here would be to collaborate with the author to implement that feature directly into the main Pytorch library. 

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by vadimkantorov** [comment]
Some related discussion: https://github.com/pytorch/pytorch/issues/71683

**Comment by mikaylagawarecki** [comment]
Might this be what you are looking for https://pytorch.org/docs/stable/optim.html#weight-averaging-swa-and-ema
