### ISSUE TITLE
parameter's type is wrong

### ISSUE THREAD

**Issue by MuyuXiaoxiang** [pytorch/pytorch#13036]
## 🐛 Bug

When I run the function _find_cuda_home() in cpp_extension.py on my Windows 10 os, the cuda_home is a list, however the parameter of the function os.path.exists(cuda_home) must be string, it will make it wrong.

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):0.4.1
 - OS (e.g., Linux):windows 10
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:3.6.3
 - CUDA/cuDNN version:8.0
 - GPU models and configuration:GTX 1060
 - Any other relevant information:

**Comment by zou3519** [comment]
We fixed this in master: https://github.com/pytorch/pytorch/commit/cc5b47ff476a1dac88fac637ca90bb805b06000c. Thank you for your issue @MuyuXiaoxiang
