### ISSUE TITLE
`low`, `high` and `size` argument of `randint()` with 0D or more D tensors work against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130421]
### 🐛 Describe the bug

Against what [the doc](https://pytorch.org/docs/stable/generated/torch.randint.html) of `randint()`, `low`, `high` and `size` argument with 0D or more D tensors work as shown below:

> - low ([int](https://docs.python.org/3/library/functions.html#int), optional) – Lowest integer to be drawn from the distribution. Default: 0.
> - high ([int](https://docs.python.org/3/library/functions.html#int)) – One above the highest integer to be drawn from the distribution.
> - size ([tuple](https://docs.python.org/3/library/stdtypes.html#tuple)) – a tuple defining the shape of the output tensor.

```python
torch.randint(low=torch.tensor(-5),
              high=torch.tensor([5]),
              size=(torch.tensor([[3]]),
              torch.tensor([[[2]]])))
# tensor([[-2, 3],
#         [-4, 4],
#         [2, 1]])
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by janeyx99** [comment]
See https://github.com/pytorch/pytorch/issues/130063#issuecomment-2207452274
