### ISSUE TITLE
Applying torch.cumsum does not recover the original vector after torch.diff

### ISSUE THREAD

**Issue by rteehas** [pytorch/pytorch#130447]
### 🐛 Describe the bug

I noticed an issue while working with `torch.diff` and `torch.cumsum`. I would 
```python
import torch
tmp = torch.randn(512, 768)

tmp_delta = torch.diff(tmp, dim=0, prepend=torch.zeros(1,768)) #prepend zeros so that the first entry is preserved

cumsum_delta = torch.cumsum(tmp_delta, dim=0)

print(torch.allclose(tmp, cumsum_delta))# False, but should be true
print(tmp == cumsum_delta)
```

After the final print statement, I get:
```
tensor([[ True,  True,  True,  ...,  True,  True,  True],
        [False,  True, False,  ...,  True,  True,  True],
        [ True, False, False,  ...,  True,  True,  True],
        ...,
        [False,  True, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]])
```

The difference between `tmp` and `cumsum_delta` is:
```
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 1.4901e-08,  4.4703e-08,  0.0000e+00,  ...,  5.9605e-08,
          1.1921e-07,  0.0000e+00],
        [ 1.4901e-08,  5.9605e-08,  0.0000e+00,  ...,  6.3330e-08,
          1.4901e-07,  1.1921e-07],
        ...,
        [-8.3447e-07,  4.7684e-07, -5.9605e-07,  ...,  4.1723e-07,
          8.3447e-07, -2.9802e-07],
        [-7.1526e-07,  4.7684e-07, -5.9605e-07,  ...,  4.1723e-07,
          8.6427e-07, -2.3842e-07],
        [-8.3447e-07,  4.6566e-07, -6.5565e-07,  ...,  4.1723e-07,
          8.4937e-07, -3.5763e-07]])
```

I would expect, however, to get the original `tmp` tensor.

### Versions

PyTorch version: 2.2.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.14.0-284.40.1.el9_2.x86_64-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             48
On-line CPU(s) list:                0-47
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz
CPU family:                         6
Model:                              85
Thread(s) per core:                 1
Core(s) per socket:                 24
Socket(s):                          2
Stepping:                           7
CPU max MHz:                        3900.0000
CPU min MHz:                        1200.0000
BogoMIPS:                           5800.00
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          1.5 MiB (48 instances)
L1i cache:                          1.5 MiB (48 instances)
L2 cache:                           48 MiB (48 instances)
L3 cache:                           71.5 MiB (2 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-23
NUMA node1 CPU(s):                  24-47
Vulnerability Gather data sampling: Mitigation; Microcode
Vulnerability Itlb multihit:        KVM: Mitigation: VMX disabled
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Retbleed:             Mitigation; Enhanced IBRS
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] kmeans-pytorch==0.3
[pip3] numpy==1.26.4
[pip3] pytorch-lightning==2.2.5
[pip3] torch==2.2.1
[pip3] torchaudio==2.2.1
[pip3] torchmetrics==1.4.0.post0
[pip3] torchvision==0.17.1
[pip3] triton==2.2.0
[pip3] vector_quantize_pytorch==1.14.1
[conda] blas                      1.0                         mkl  
[conda] faiss-cpu                 1.8.0           py3.11_h9d89a2e_0_cpu    pytorch
[conda] kmeans-pytorch            0.3                      pypi_0    pypi
[conda] libfaiss                  1.8.0            hf65b397_0_cpu    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.8           py311h5eee18b_0  
[conda] mkl_random                1.2.4           py311hdb19cb5_0  
[conda] numpy                     1.26.4          py311h08b1b3b_0  
[conda] numpy-base                1.26.4          py311hf175353_0  
[conda] pytorch-lightning         2.2.5                    pypi_0    pypi
[conda] torch                     2.2.1                    pypi_0    pypi
[conda] torchaudio                2.2.1                    pypi_0    pypi
[conda] torchmetrics              1.4.0.post0              pypi_0    pypi
[conda] torchvision               0.17.1                   pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi
[conda] vector-quantize-pytorch   1.14.1                   pypi_0    pypi

**Comment by jbschlosser** [comment]
Note that the differences are quite small. It is generally expected that operations do not execute with 100% precision (see docs on numerical accuracy [here](https://pytorch.org/docs/stable/notes/numerical_accuracy.html)). 

Adjusting the tolerances for `torch.allclose()`:
```python
print(torch.allclose(tmp, cumsum_delta, atol=1e-5, rtol=1e-5))  # True
```

Closing as expected behavior.
