### ISSUE TITLE
torch.library.custom_op with mutated inputs can have silent incorrectness under torch.compile

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#130487]
torch.library.custom_op applies needs_fixed_stride_order which can lead to silent incorrectness: https://github.com/pytorch/pytorch/issues/128084

cc @ezyang @gchanan @kadeng @msaroufim @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by FindHao** [comment]
@eellison says it is related to https://github.com/pytorch/pytorch/issues/130394#issuecomment-2223043133 . Working on it now.

**Comment by malfet** [comment]
@zou3519 is there a fix for this problem? Or should one remove 2.4.1 tag?

**Comment by FindHao** [comment]
> @zou3519 is there a fix for this problem? Or should one remove 2.4.1 tag?

I'm working on its blocker now. [130956](https://github.com/pytorch/pytorch/pull/130956) There are three related issues and they are supposed to be fixed in the following weeks. Maybe we can remove this 2.4.1 tag.

**Comment by zou3519** [comment]
@malfet there's a fast short-term fix we can apply here; I'm debating whether or not to apply it or punt the fix for 2.5

**Comment by zou3519** [comment]
Merged #133888 for 2.4.1

**Comment by masnesral** [comment]
Update from @zou3519 at triage meeting: this is still in progress.

**Comment by zou3519** [comment]
I fixed this one
