### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

### ISSUE THREAD

**Issue by PierrunoYT** [pytorch/pytorch#130597]
### 🐛 Describe the bug

Issue:

(venv) C:\Users\pierr\Enhancer>python creative_upscaler.py
C:\Users\pierr\Enhancer\venv\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\pierr\Enhancer\venv\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\pierr\Enhancer\venv\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\Users\pierr\Enhancer\creative_upscaler.py", line 6, in <module>
    from realesrgan import RealESRGANer
  File "C:\Users\pierr\Enhancer\venv\Lib\site-packages\realesrgan\__init__.py", line 2, in <module>
    from .archs import *
  File "C:\Users\pierr\Enhancer\venv\Lib\site-packages\realesrgan\archs\__init__.py", line 2, in <module>
    from basicsr.utils import scandir
  File "C:\Users\pierr\Enhancer\venv\Lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "C:\Users\pierr\Enhancer\venv\Lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pierr\Enhancer\venv\Lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "C:\Users\pierr\Enhancer\venv\Lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

Code:

import torch
import numpy as np
from diffusers import DiffusionPipeline
from PIL import Image
import os
from realesrgan import RealESRGANer
from basicsr.archs.rrdbnet_arch import RRDBNet
import argparse
import torchvision.transforms.functional as TF

def load_sdxl():
    base = DiffusionPipeline.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0", 
        torch_dtype=torch.float16, 
        variant="fp16", 
        use_safetensors=True
    )
    base.to("cuda")
    return base

def load_realesrgan_upscaler():
    model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=23, num_grow_ch=32, scale=4)
    upscaler = RealESRGANer(scale=4, model_path='https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth', model=model, tile=0, tile_pad=10, pre_pad=0, half=True)
    return upscaler

def creative_upscale(sdxl_base, realesrgan_upscaler, image_path, output_path):
    input_img = Image.open(image_path).convert("RGB")
    input_tensor = TF.to_tensor(input_img).unsqueeze(0)
    enhanced_image = sdxl_base(
        prompt="enhance details, improve quality",
        image=input_tensor,
        strength=0.3,
        num_inference_steps=50,
    ).images[0]
    enhanced_image_np = TF.to_pil_image(enhanced_image)
    enhanced_image_np = np.array(enhanced_image_np)
    upscaled_image, _ = realesrgan_upscaler.enhance(enhanced_image_np)
    final_image = Image.fromarray(upscaled_image)
    final_image.save(output_path)
    print(f"Enhanced and upscaled image saved to {output_path}")

def process_images(sdxl_base, realesrgan_upscaler, input_path, output_path):
    if os.path.isfile(input_path):
        creative_upscale(sdxl_base, realesrgan_upscaler, input_path, output_path)
    elif os.path.isdir(input_path):
        os.makedirs(output_path, exist_ok=True)
        for filename in os.listdir(input_path):
            if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif')):
                input_file = os.path.join(input_path, filename)
                output_file = os.path.join(output_path, f"enhanced_{filename}")
                creative_upscale(sdxl_base, realesrgan_upscaler, input_file, output_file)
    else:
        print(f"Error: {input_path} is not a valid file or directory")

if __name__ == "__main__":
    input_path = input("Enter the path to input image or directory: ")
    output_path = input("Enter the path to output image or directory: ")

    sdxl_base = load_sdxl()
    realesrgan_upscaler = load_realesrgan_upscaler()
    process_images(sdxl_base, realesrgan_upscaler, input_path, output_path)

### Versions

-

**Comment by jbschlosser** [comment]
Hey @PierrunoYT, this looks like it may be an environment or usage issue related to torchvision? I suggest asking for help on the [PyTorch forums](https://dev-discuss.pytorch.org/), as you're more likely to receive assistance there. Note that the issues here are related to bugs within PyTorch itself. Closing for now but feel free to open a more specific issue on the torchvision repo if forum discussion indicates a bug there.
