### ISSUE TITLE
`contextlib.contextmanager` is not supported in dynamo

### ISSUE THREAD

**Issue by guilhermeleobas** [pytorch/pytorch#130559]
### 🐛 Describe the bug

`contextlib.contextmanager` is skipped by default in dynamo. Recently, https://github.com/pytorch/pytorch/pull/129091 added support for more complex context managers in `GenericContextWrappingVariable`. The same could be adapted to support `contextlib.contextmanager`.

```python
import torch
import contextlib

@contextlib.contextmanager
def g(x):
    try:
        yield x.sin()
    finally:
        pass

@torch.compile(fullgraph=True)
def fn(x):
    with g(x) as y:
        z = y + 1
    return z

x = torch.randn(2, 3)
fn(x)

# torch._dynamo.exc.Unsupported: 'skip function g in file /micromamba/envs/pytorch/lib/python3.11/contextlib.py'
```

### Versions

main

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by zou3519** [comment]
Lol I think removing contextlib from the skiplist fixes this
