### ISSUE TITLE
New UserWarning about CompositeImplicitAutograd when defining Custom Ops

### ISSUE THREAD

**Issue by rvijayc** [pytorch/pytorch#130588]
### 🐛 Describe the bug

I am not sure if this is a bug or not, but I am getting a lot of new warnings after I upgraded to latest PyTorch and Executorch baselines (2.5.0.dev20240618+cpu).  I am trying to understand if I am doing something wrong, or if these warnings are unexpected.

Below is a simple example to reproduce the warning. I've defined a custom op using the examples in torch.library documentation (https://pytorch.org/docs/stable/library.html) as reference. The warning comes when I use torch.export with a module that uses custom ops.

```python
import torch
import torch.library
import torch.nn as nn
import torch.nn.functional as F

# --- Define a custom Op using torch.library --- #
lib = torch.library.Library("example", "DEF")
lib.define("custom_op(Tensor x) -> Tensor")

def custom_op(x: torch.Tensor):
    return x

def custom_op_fake(x: torch.Tensor):
    return x

lib.impl("custom_op", custom_op, "CPU")  
torch.library.register_fake("example::custom_op", custom_op_fake)

# --- Create a Model with the custom Op ---

# 1 input with multiple (debug outputs).
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(64, 32)
        self.fc2 = nn.Linear(32, 16)
        
    def forward(self, x):
        y_fc1 = F.relu(self.fc1(x))
        y = F.relu(self.fc2(y_fc1))
        return torch.ops.example.custom_op(y)

if __name__ == "__main__":

    # generate a uniform distribution of data.
    n_mini_batches = 10
    x_in = torch.distributions.uniform.Uniform(-1, 1).sample([n_mini_batches, 8, 64])

    # PRIME 1xN (debug)
    X = (x_in[1,:],)

    # export the model.
    m_export = torch.export.export(MLP().eval(), X).module()
```

This prints the following warning -

```
/opt/conda/envs/executorch/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:362: UserWarning: At pre-dispatch tracing, we will assume that any custom op that is marked with CompositeImplicitAutograd and functional are safe to not decompose. We found example.custom_op.default to be one such op.
  warnings.warn(
```

I am not clear on what this means (and what I am doing wrong) as I am not doing any training (just converting a `nn.Module` into its FX graph representatation) , and hence Autograd should not be relevant here. My goal is to simply use FX and op transformations to implement a inference deployment workflow (similar to what Executorch does).

How can I modify this example to make this warning go away? Appreciate any help!

### Versions

Collecting environment information...
PyTorch version: 2.5.0.dev20240618+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: 11.0.1-2
CMake version: version 3.30.0
Libc version: glibc-2.31

Python version: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-4.12.14-122.144-default-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] executorch==0.4.0a0+3fb7083
[pip3] numpy==1.26.4
[pip3] onnx==1.16.1
[pip3] torch==2.5.0.dev20240618+cpu
[pip3] torchaudio==2.4.0.dev20240618+cpu
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0.dev20240618+cpu
[conda] executorch                0.4.0a0+3fb7083          pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.5.0.dev20240618+cpu          pypi_0    pypi
[conda] torchaudio                2.4.0.dev20240618+cpu          pypi_0    pypi
[conda] torchsr                   1.0.4                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20240618+cpu          pypi_0    pypi

cc @ezyang @anijain2305 @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by zou3519** [comment]
The warning is wrong, you can ignore it

**Comment by rvijayc** [comment]
> But also, your custom op is not a valid custom op (we do not allow returning the inputs directly from a custom op): use torch.library.opcheck to test it

Thanks for pointer. Fixed the above example using `torch.clone` which passed `opcheck`.
