### ISSUE TITLE
Dynamo set impl. does not support `intersection(...)` method

### ISSUE THREAD

**Issue by guilhermeleobas** [pytorch/pytorch#130557]
### 🐛 Describe the bug

Reproducer

```python
import torch

@torch.compile(fullgraph=True)
def fn(x):
    a = set(['a', 'b'])
    b = set(['a', 'c'])
    return a.intersection(b)


x = torch.randn(2, 3)
fn(x)
```

From the codebase, set implementation also lacks of the following methods:

- [x] add
- [x] pop
- [x] isdisjoint
- [x] update
- [ ] issubset
- [ ] issuperset
- [ ] union
- [ ] intersection
- [ ] difference
- [ ] symmetric_difference
- [ ] copy
- [ ] update
- [ ] intersection_update
- [ ] difference_update
- [ ] symmetric_difference_update
- [ ] remove
- [ ] discard
- [ ] clear

### Versions

main

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by Zawa-ll** [comment]
Hi! I am interested in this ticket, please assign to me! Changes is on its way!

**Comment by anijain2305** [comment]
Use polyfill to implement intersect, similar to https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/polyfill.py#L59-L63

**Comment by bt2513** [comment]
Hi everyone! I am really interested in contributing to this issue. Can I be assigned to it if no one is already working on it? :)

**Comment by vadimkantorov** [comment]
Also related on dynamo support for set methods:
- https://github.com/pytorch/pytorch/issues/153476
- https://github.com/pytorch/pytorch/issues/153476
