### ISSUE TITLE
Question about TF32 support on ROCm

### ISSUE THREAD

**Issue by zhaohm14** [pytorch/pytorch#130600]
Why isn't TF32 supported on ROCm, despite recent AMD GPUs supporting it according to the official documentation?
https://pytorch.org/docs/stable/notes/hip.html#tensorfloat-32-tf32-on-rocm

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @zasdfgbnm @ptrblck

**Comment by hongxiayang** [comment]
hi, @zhaohm14 : Can you share some insights regarding what your use case is that you want to use this feature?

**Comment by zhaohm14** [comment]
Hi, thanks for your reply!

I am currently working on training models with MI300X, a part of AMD's latest MI300 series GPUs (CDNA 3), which support TF32 precision and claim a 4x speedup over FP32 as per the documentation here: 
https://www.amd.com/en/products/accelerators/instinct/mi300/mi300x.html
https://rocm.docs.amd.com/en/latest/conceptual/gpu-arch/mi300.html
I'm eager to leverage TF32 in my project due to these advantages.

Here's the code snippet I used to test the performance:
```python
# ---------- Matrix TF32 ----------
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
torch.set_float32_matmul_precision('high')

a = torch.randn(10000, 10000, device='cuda', dtype=torch.float32)
b = torch.randn(10000, 10000, device='cuda', dtype=torch.float32)

_ = torch.matmul(a, b)
torch.cuda.synchronize()

start_tf32 = time.time()
for _ in range(100):
    output_tf32 = torch.matmul(a, b)
torch.cuda.synchronize()
end_tf32 = time.time()
time_tf32 = end_tf32 - start_tf32
print(f"Matrix TF32 time: {time_tf32:.6f} seconds")

# ---------- Matrix FP32 ----------
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.allow_tf32 = False
torch.set_float32_matmul_precision('highest')

a = torch.randn(10000, 10000, device='cuda', dtype=torch.float32)
b = torch.randn(10000, 10000, device='cuda', dtype=torch.float32)

_ = torch.matmul(a, b)
torch.cuda.synchronize()

start_fp32 = time.time()
for _ in range(100):
    output_fp32 = torch.matmul(a, b)
torch.cuda.synchronize()
end_fp32 = time.time()
time_fp32 = end_fp32 - start_fp32
print(f"Matrix FP32 time: {time_fp32:.6f} seconds")

# ---------- Vector FP32 ----------
a = torch.randn(10000000, device='cuda', dtype=torch.float32)
b = torch.randn(10000000, device='cuda', dtype=torch.float32)

_ = torch.dot(a, b)
torch.cuda.synchronize()

start_fp32 = time.time()
for _ in range(100000):
    output_fp32 = torch.dot(a, b)
torch.cuda.synchronize()
end_fp32 = time.time()
time_fp32 = end_fp32 - start_fp32
print(f"Vector FP32 time: {time_fp32:.6f} seconds")

# ---------- Vector TF32 ----------
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
torch.set_float32_matmul_precision('high')

a = torch.randn(10000000, device='cuda', dtype=torch.float32)
b = torch.randn(10000000, device='cuda', dtype=torch.float32)

_ = torch.dot(a, b)
torch.cuda.synchronize()

start_tf32 = time.time()
for _ in range(100000):
    output_tf32 = torch.dot(a, b)
torch.cuda.synchronize()
end_tf32 = time.time()
time_tf32 = end_tf32 - start_tf32
print(f"Vector TF32 time: {time_tf32:.6f} seconds")
```
I observed no significant differences in performance between TF32 and FP32. I found documentation suggesting TF32 might not be supported on ROCm (https://pytorch.org/docs/stable/notes/hip.html#tensorfloat-32-tf32-on-rocm). Could you confirm whether this is the case? Or is there any wrong with my implementation?

Thanks a lot!

**Comment by hongxiayang** [comment]
@zhaohm14 Thank you for experimenting this. As the hip.html documentation suggested, the stable TF32 support is not integrated with PyTorch yet. Please keep use the other options before this is available.

**Comment by zhaohm14** [comment]
Got it. Are there any plans for the implementation of TF32 in ROCm?

**Comment by hongxiayang** [comment]
Sorry, no timeline is available.

**Comment by kavanase** [comment]
Hi! I wanted to check if there was any update on this? It would be really great if we could use TF32 with ROCM.

**Comment by jeffdaily** [comment]
TF32 is currently available for the MI300 platform via hipblaslt since #144145 was merged.  It requires setting an env var `HIPBLASLT_ALLOW_TF32=1` in addition to the usual `torch.backends.cuda.matmul.allow_tf32 = True`.

**Comment by zhaohm14** [comment]
> TF32 is currently available for the MI300 platform via hipblaslt since [#144145](https://github.com/pytorch/pytorch/pull/144145) was merged. It requires setting an env var `HIPBLASLT_ALLOW_TF32=1` in addition to the usual `torch.backends.cuda.matmul.allow_tf32 = True`.

Great to hear that! Will it be officially supported in torch 2.7 or 2.8?

**Comment by jeffdaily** [comment]
PR #144145 and subsequent #144797 are both part of release/2.7 branch.
