### ISSUE TITLE
Internal uses of `torch.cuda.amp.autocast` raise FutureWarnings

### ISSUE THREAD

**Issue by awaelchli** [pytorch/pytorch#130659]
### 🐛 Describe the bug

PyTorch 2.4 deprecated the use of `torch.cuda.amp.autocast` in favor of `torch.amp.autocast("cuda", ...)`, but this change has missed updating internal uses in PyTorch. For example in DP here:
https://github.com/pytorch/pytorch/blob/3710a7962261f26bf9ad8b768229582bf9f00c94/torch/nn/parallel/parallel_apply.py#L92-L93

```py
import torch

model = torch.nn.Linear(10, 10).cuda()
model = torch.nn.DataParallel(model, device_ids=[0, 1])
output = model(torch.randn(20, 10).cuda())
```
Produces:
```
/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/linear.py:117: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at ../aten/src/ATen/cuda/CublasHandlePool.cpp:135.)
  return F.linear(input, self.weight, self.bias)
```

Since these are caused internally, the user will see the warning but not be able to do anything with it. 

If desired, I can send a PR with a fix for this :)

### Versions

PyTorch version: 2.4.0+cu121

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by albanD** [comment]
cc @guangyey could you please help fix this?

**Comment by guangyey** [comment]
> cc @guangyey could you please help fix this?
I see @awaelchli already filed a PR https://github.com/pytorch/pytorch/pull/130660 to fix this. I give a comment to fix the lint.

**Comment by function2-llx** [comment]
Also found a usage of `torch.cpu.amp.autocast` [here](https://github.com/pytorch/pytorch/blob/v2.4.0/torch/utils/checkpoint.py#L1399) in PyTorch 2.4.

**Comment by guangyey** [comment]
@function2-llx Let me fix it today.

**Comment by guangyey** [comment]
@function2-llx I see this fix targets release 2.4.1 refer to [this comment](https://github.com/pytorch/pytorch/issues/128436#issuecomment-2229068672)
By the way, I fix the other deprecation warning in #132207

**Comment by naga24** [comment]
> Also found a usage of `torch.cpu.amp.autocast` [here](https://github.com/pytorch/pytorch/blob/v2.4.0/torch/utils/checkpoint.py#L1399) in PyTorch 2.4.
> 
> What's worse, the warning for this line produces everytime during `backward` when using `checkpoint`, not only the first time.

You can downgrade to torch==2.3.1 and torchvision==0.18.1, warning stops coming

**Comment by guangyey** [comment]
@function2-llx, you can try the way @naga24 mentioned or get the fix in the upcoming 2.4.1 release.

**Comment by function2-llx** [comment]
Thanks for the suggestions! 
There is also a workaround that disables the warning by passing arguments to the interpreter, something like this will work: `python -W ignore::FutureWarning:torch.utils.checkpoint:1399`.

**Comment by tgilbert09** [comment]
Also found in [engine.py](https://github.com/pytorch/vision/blob/main/references/detection/engine.py), line 30. This FutureWarning appears on the tutorial website [TorchVision Object Detection Finetuning Tutorial](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html#codecell16). Also mentioned in pytorch/tutorials#3007.

**Comment by kit1980** [comment]
Validated with torch==2.4.1 RC.

FYI the original repro modified to run on a single GPU machine:
```
import torch

model = torch.nn.Linear(10, 10).cuda()
model = torch.nn.DataParallel(model, device_ids=[0, 0])
output = model(torch.randn(20, 10).cuda())

```

**Comment by Sola-AIGithub** [comment]
Hello, there. I check the model dtype then use 「with torch.autocast("cuda", torch.float32):」 instead 「with torch.cuda.amp.autocast(autocast):」 it works and no Future Warning, FYI.

p.s.torch.__version__ == 2.4.1 , yolov5 model
