### ISSUE TITLE
Internal uses of `torch.load` are missing `weights_only` and raise FutureWarning

### ISSUE THREAD

**Issue by awaelchli** [pytorch/pytorch#130658]
### 🐛 Describe the bug

The PyTorch code base contains several uses of `torch.load` internally, but not all of them set `weights_only`, which in PyTorch 2.4 raises a FutureWarning. Since these are internal, the user would see the warning but have no way of acting on it. PyTorch should set `weights_only` in all of it's internal uses. 

Some examples (but there are more if you search the code base):
https://github.com/pytorch/pytorch/blob/f44739cf42e22a569bd1bdb0c113f8a069c17a41/torch/distributed/checkpoint/format_utils.py#L87
https://github.com/pytorch/pytorch/blob/f44739cf42e22a569bd1bdb0c113f8a069c17a41/torch/distributed/optim/zero_redundancy_optimizer.py#L111

There was a PR recently that resolved one of these important cases:
https://github.com/pytorch/pytorch/issues/130242

These warnings will show up in PyTorch 2.4. 
This surfaced in our test suite (PyTorch Lightning) since we have configured them to fail if FutureWarning is raised. 

If desired, I can send a PR to fix this.

### Versions

torch=2.4.0

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @LucasLLC

**Comment by malfet** [comment]
This should have an `oncall: distributed` associated with it. And yes, this is probably the price one has to pay for planning BC changes

**Comment by LucasLLC** [comment]
Pr would be great @awaelchli ! I can help review for checkpoint/format_utils, but likely will need some extra eyes on the optim change.

**Comment by awaelchli** [comment]
Thanks @LucasLLC, I put the PR up already: #130663 😃

**Comment by LucasLLC** [comment]
@awaelchli stamped! Please close if this resolves the issue
