### ISSUE TITLE
Place `torch.nn.Module.__init__` in a differently-named method

### ISSUE THREAD

**Issue by jakelevi1996** [pytorch/pytorch#130632]
### 🚀 The feature, motivation and pitch

Subclasses of `torch.nn.Module` require calling `super().__init__()` at the start of the `__init__` method. Suppose I have a `torch.nn.Module` subclass called `A`, and I want to create a subclass `B` of `A` which inherits some methods from `A` but has a different `__init__` method (which doesn't call `A.__init__`):

```python
import torch

class A(torch.nn.Module):
    def __init__(self):
        super().__init__()
        print("A")

    def method(self):
        pass

class B(A):
    def __init__(self):
        super().__init__()
        print("B")

A()
# >>> A
B()
# >>> A
# >>> B
```

I had to call `super().__init__()` in `B.__init__` in order to catch `torch.nn.Module.__init__`, but this required calling `A.__init__`, which I didn't want to do.

### Solution

A solution to this problem would be if `__init__` in `torch.nn.Module` was renamed to something like `_torch_module_init`. That way, `B.__init__` could call `self._torch_module_init()` instead of `super().__init__()`, which sets the appropriate `torch.nn.Module` attributes while avoiding `A.__init__`:

```python
import torch

class A(torch.nn.Module):
    def __init__(self):
        self._torch_module_init()
        print("A")

    def method(self):
        pass

class B(A):
    def __init__(self):
        self._torch_module_init()
        print("B")

A()
# >>> A
B()
# >>> B
```

For backward compatibility, `torch.nn.Module.__init__` could simply call `torch.nn.Module._torch_module_init`, so existing `torch.nn.Module` subclasses which call `super().__init__()` still work, but `__init__` can still be flexibly overridden by subclasses.

### Alternatives

An alternative solution would be if `A` places its initialisation code in a separate method called EG `_A_init`, which can then be overridden by `B` (while avoiding the initialisation code for `A`, which is what I wanted), but in practise (IE a more complex example than shown below) this requires more boilerplate and feels more clunky/less intuitive:

```python
import torch

class A(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self._A_init()

    def _A_init(self):
        print("A")

    def method(self):
        pass

class B(A):
    def _A_init(self):
        print("B")

A()
# >>> A
B()
# >>> B
```

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by albanD** [comment]
Would it work to just call `torch.nn.Module.__init__` directly?

**Comment by jakelevi1996** [comment]
I think it would, although I thought this was "not Pythonic"

**Comment by albanD** [comment]
I'm not sure calling `self._torch_module_init()` to trigger `Module.__init__()` is much more pythonic?

**Comment by jakelevi1996** [comment]
Just to clarify, you're saying option `C` is more Pythonic than option `B` in the examples below? I suppose it's a matter of opinion, but I would say `B` is more Pythonic. Calling a method inherited from a parent class as `self.<method>()` is common practise, but calling `<class>.<method>(self)` is not something I see in normal Python code.

```python
import torch

class A(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.x = torch.nn.Parameter(torch.zeros(10))

class B(torch.nn.Module):
    def __init__(self):
        self._torch_module_init()
        self.x = torch.nn.Parameter(torch.zeros(10))

class C(torch.nn.Module):
    def __init__(self):
        torch.nn.Module.__init__(self)
        self.x = torch.nn.Parameter(torch.zeros(10))
```

**Comment by jakelevi1996** [comment]
A fourth option would be to have a function in the `torch.nn` module called EG `init_module` which accepts an instance of `torch.nn.Module`, EG:

```python
class D(torch.nn.Module):
    def __init__(self):
        torch.nn.init_module(self)
        self.x = torch.nn.Parameter(torch.zeros(10))
```
