### ISSUE TITLE
torch.autograd.Function does not support kwarg-only kwargs for vmap

### ISSUE THREAD

**Issue by yushangdi** [pytorch/pytorch#130653]
### 🐛 Describe the bug

The code below errors

```python
import torch
from torch import Tensor
from torch.library import custom_op
import numpy as np


def to_numpy(tensor):
    return tensor.cpu().numpy()

class NumpySort(torch.autograd.Function):
    @staticmethod
    def forward(x, dim, /, k=1):
        device = x.device
        x = to_numpy(x)
        ind = np.argsort(x, axis=dim)
        ind_inv = np.argsort(ind, axis=dim)
        result = np.take_along_axis(x, ind, axis=dim)
        return (
            torch.tensor(result, device=device),
            torch.tensor(ind, device=device),
            torch.tensor(ind_inv, device=device),
        )

    @staticmethod
    def setup_context(ctx, inputs, output):
        pass

    @staticmethod
    def vmap(info, in_dims, x, dim, /, k):
        x_bdim, _ = in_dims

        x = x.movedim(x_bdim, 0)
        dim = dim if dim >= 0 else dim + x.dim() - 1
        result = NumpySort.apply(x, dim + 1)

        return NumpySort.apply(x, dim + 1), (0, 0, 0)

def numpy_sort(x, dim=-1):
    result, _, _ = NumpySort.apply(x, dim, k=3)
    return result

x = torch.randn(2, 3)
result = torch.vmap(numpy_sort)(x)
```

Traceback (most recent call last):
  File "/data/users/shangdiy/pytorch/../test.py", line 43, in <module>
    result = torch.vmap(numpy_sort)(x)
  File "/data/users/shangdiy/pytorch/torch/_functorch/apis.py", line 201, in wrapped
    return vmap_impl(
  File "/data/users/shangdiy/pytorch/torch/_functorch/vmap.py", line 331, in vmap_impl
    return _flat_vmap(
  File "/data/users/shangdiy/pytorch/torch/_functorch/vmap.py", line 48, in fn
    return f(*args, **kwargs)
  File "/data/users/shangdiy/pytorch/torch/_functorch/vmap.py", line 480, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
  File "/data/users/shangdiy/pytorch/../test.py", line 39, in numpy_sort
    result, _, _ = NumpySort.apply(x, dim, k=3)
  File "/data/users/shangdiy/pytorch/torch/autograd/function.py", line 584, in apply
    return custom_function_call(cls, *args, **kwargs)
  File "/data/users/shangdiy/pytorch/torch/_functorch/autograd_function.py", line 49, in __call__
    return super().__call__(autograd_function, *args, **kwargs)
  File "/data/users/shangdiy/pytorch/torch/_ops.py", line 381, in __call__
    return wrapper()
  File "/data/users/shangdiy/pytorch/torch/_dynamo/eval_frame.py", line 602, in _fn
    return fn(*args, **kwargs)
  File "/data/users/shangdiy/pytorch/torch/_ops.py", line 377, in wrapper
    return self_.dispatch(
  File "/data/users/shangdiy/pytorch/torch/_ops.py", line 301, in dispatch
    return dispatch_functorch(self_, args, kwargs)
  File "/data/users/shangdiy/pytorch/torch/_functorch/pyfunctorch.py", line 293, in dispatch_functorch
    return interpreter.process(op, args, kwargs)
  File "/data/users/shangdiy/pytorch/torch/_functorch/pyfunctorch.py", line 129, in process
    return kernel(self, *args, **kwargs)
TypeError: custom_function_call_vmap() got an unexpected keyword argument 'k'

### Versions

Collecting environment information...
PyTorch version: 2.5.0a0+gitae73489
Is debug build: False
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.34

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-0_fbk12_hardened_11583_g0bef9520ca2b-x86_64-with-glibc2.34
Is CUDA available: False
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: NVIDIA A100-PG509-200
GPU 1: NVIDIA A100-PG509-200
GPU 2: NVIDIA A100-PG509-200
GPU 3: NVIDIA A100-PG509-200
GPU 4: NVIDIA A100-PG509-200
GPU 5: NVIDIA A100-PG509-200
GPU 6: NVIDIA A100-PG509-200
GPU 7: NVIDIA A100-PG509-200

Nvidia driver version: 535.154.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          172
On-line CPU(s) list:             0-171
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8339HC CPU @ 1.80GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              1
Core(s) per socket:              172
Socket(s):                       1
Stepping:                        11
BogoMIPS:                        3591.73
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 arat umip pku ospke avx512_vnni md_clear arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       5.4 MiB (172 instances)
L1i cache:                       5.4 MiB (172 instances)
L2 cache:                        688 MiB (172 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-171
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.11.0
[pip3] torch==2.5.0a0+gitd2208a4
[conda] blas                      1.0                         mkl  
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-include               2023.1.0         h06a4308_46344  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] torch                     2.5.0a0+gitd2208a4           dev_0    <develop>
[conda] torchfix                  0.4.0                    pypi_0    pypi

cc @ezyang @albanD @gqchen @pearu @nikitaved @soulitzer @Varal7 @zou3519

**Comment by yushangdi** [comment]
@zou3519 Do you know if this is expected? I see that the kwargs are included as part of `operands` instead of kwargs.

**Comment by zou3519** [comment]
This was not intended, we should be able to relax it to at least supporting non-Tensor kwarg-only kwargs
