### ISSUE TITLE
Encountering HIP OOM error for the baddbmm operator when auto-tune is enabled

### ISSUE THREAD

**Issue by leitian** [pytorch/pytorch#130727]
### 🐛 Describe the bug

When using the below environment variables to enable the auto-tune mode for the baddbmm operator (with input tensors with certain strides) on AMD GPUs:

`PYTORCH_TUNABLEOP_ENABLED=1 PYTORCH_TUNABLEOP_TUNING=1 PYTORCH_TUNABLEOP_FILENAME="hipblas_tuning.csv" PYTORCH_TUNABLEOP_MAX_TUNING_DURATION_MS=30 PYTORCH_TUNABLEOP_MAX_WARMUP_DURATION_MS=30 HIP_FORCE_DEV_KERNARG=1 PYTORCH_TUNABLEOP_VERBOSE=1`

The program will encounter HIP OOM error. A mini repo is in the below:

```
import torch

def main() -> None:
    gpu_device = torch.device("cuda")

    input_tensor = torch.rand(
        (1920, 1, 100),
        device=gpu_device,
        dtype=torch.bfloat16,
    )
    input_tensor = torch.as_strided(
        input_tensor, size=(1920, 1, 100), stride=(100, 100, 1)
    )
    batch1_tensor = torch.rand(
        (1920, 256, 512),
        device=gpu_device,
        dtype=torch.bfloat16,
    )
    batch1_tensor = torch.as_strided(
        batch1_tensor, size=(1920, 256, 512), stride=(512, 983040, 1)
    )
    batch2_tensor = torch.rand(
        (1920, 512, 100),
        device=gpu_device,
        dtype=torch.bfloat16,
    )
    batch2_tensor = torch.as_strided(
        batch2_tensor, size=(1920, 512, 100), stride=(51200, 100, 1)
    )

    for _ in range(100):
        _ = torch.baddbmm(input_tensor, batch1_tensor, batch2_tensor)


if __name__ == "__main__":
    main()
```

The below is the example error message:
```
_ = torch.baddbmm(input_tensor, batch1_tensor, batch2_tensor)
  torch.OutOfMemoryError: HIP out of memory. Tried to allocate 900.00 GiB. GPU 0 has a total capacity of 191.98 GiB of which 186.38 GiB is free. Of the allocated memory 1.02 GiB is allocated by PyTorch, and 1.63 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Versions

pytorch 2.5.0

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by xw285cornell** [comment]
cc. @jeffdaily

**Comment by jeffdaily** [comment]
Looks like yet another problem with buffer rotation feature.  Previously I had a fix for the buffers being too small, and for this present issue the buffers are too large.  Turning on full verbose shows this message before the OOM.

```bash
Rotating buffer 8 MiB. Needed Size: 921881 MiB. Needed number of param copies: 1
```

**Comment by jeffdaily** [comment]
Fix is ready #130800 .

**Comment by jeffdaily** [comment]
> @leitian this stride seems incorrect? Wouldn't it cause OOB access?
> 
> ```
>     batch1_tensor = torch.as_strided(
>         batch1_tensor, size=(1920, 256, 512), stride=(512, 983040, 1)
>     )
> ```

@xw285cornell maybe you can also comment if the above is valid?

**Comment by leitian** [comment]
@jeffdaily, don't know why. But the shape and stride information is automatically extracted from the GPU trace.
