### ISSUE TITLE
[inline-inbuilt-nn-modules] Unlimited recompiles because the nn.Module is going out of scope

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#130776]
### 🐛 Describe the bug

~~~
import torch

class Mod1(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = torch.nn.Linear(5, 5)

    def forward(self, x):
        return self.lin(x)

def fn(x, mod):
    return mod(x)

opt_mod = torch.compile(fn, backend="eager")
for i in range(100):
    opt_mod(torch.randn(5, 5), Mod1())
~~~

This keeps on recompiling, even though our cache size limit is 8.

The reason is that `Mod1()` is ephemeral. As soon as it dies, the Dynamo cache entry gets invalidated and deleted. So, at the end of each for loop iteration, the cache size is effectively zero.

This can be solved by turning on `torch._dynamo.config.inline_inbuilt_nn_modules`. If we can't wait for that flag, we might need to disable the optimization that eagerly deletes the cache line.

### Versions

NA

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @amjames

**Comment by anijain2305** [comment]
High priority because it will take atleast a few weeks to turn on inlining inbuilt nn modules to True in internal.

**Comment by rajveer43** [comment]
can I work on it?
