### ISSUE TITLE
Regression (autograd branch): can't sort Variable

### ISSUE THREAD

**Issue by bermanmaxim** [pytorch/pytorch#1307]
Hello, I'm working with the autograd branch, torch version `'0.1.11+1c174d2'`, and face the following error:
```
>>> import torch
>>> a = torch.autograd.Variable(torch.rand(5))
>>> torch.sort(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/torch/autograd/variable.py", line 462, in sort
    return Sort(dim, descending)(self)
TypeError: forward() takes at least 2 arguments (1 given)
```
Sorting works on Tensors; sorting Variable worked on the last release...

**Comment by bermanmaxim** [comment]
A possible workaround is to sort the variable data and apply the resulting permutation to the variable.

**Comment by apaszke** [comment]
Should be fixed now. Thanks for the report!

**Comment by bermanmaxim** [comment]
You're welcome, thanks... I didn't see a commit yet though. I suppose it'll come soon ;)

**Comment by apaszke** [comment]
It's squashed into the older changes. You need to reset your local copy of the branch to the one from origin (I force pushed).
