### ISSUE TITLE
Increase (4x+) in build times 

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#130744]
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
ongoing

## Error looks like
sm86 builds time out, long TTS, build jobs take a long time

## Incident timeline (all times pacific)
* Thurs July 11 5:30 pm - 7ce5b5767ca9a4111a643f74ddab0ccb8c5e0dc9 https://github.com/pytorch/pytorch/actions/runs/9900474057/job/27351327965 Job build time dramatically increases 40 min -> 1.7 hr, sccache stats in log show 200+ cache write errors
* 10:06 am ff25dfca5a60452fca5465d31f6e5740cd074d02 sm86 build returns to 40 min
* Another increase to 1.3 hrs at some point
* Fri 11:31 - 43b98fa5218e89cdeb03a74823bac0a88c56f322 1.3hr -> 4+ hr (times out)
* Tentative fix https://github.com/pytorch/test-infra/pull/5428

## User impact
See section on what the error looks like

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment]
I suspect it might be associated with AmazonLinux 2023 migraiton, which moved from IDMSv1 to IDMSv2, and sccache credentials were feteched using IDMSv1

**Comment by clee2000** [comment]
Fix seems to have worked, some of the cpu build times are back down to <30 min and I logged onto one of the cuda jobs with the new runner to see what the stats are and there were few to no write errors

https://hud.pytorch.org/hud/pytorch/pytorch/27322355dec024fb8aad93fed4c09cae3ad708b0/1?per_page=100

**Comment by clee2000** [comment]
The most recent sm86 build job took 40 min. Closing

https://hud.pytorch.org/hud/pytorch/pytorch/ac3e2cb64a995fa172e99e56c94249de3d817844/1?per_page=100

**Comment by clee2000** [comment]
Questions of note from chat + oncall meeting:
* Would testing in canary helped catch this?  Probably not because canary + pytorch use different paths -> canary has its own cache which is probably not filled 

AIs for follow up, as discussed during today's oncall meeting, to be reviewed further in next week's meeting:
* Better monitoring for increases in build time (ideally also test time but build was what was impacted here)
* Better rollout plan for amazonlinux 2023 AMI migration (ex make a new label that uses the new AMI and duplicating jobs to run on that while leaving the old label + original jobs the same)

**Comment by clee2000** [comment]
AI: check that sccache can write to bucket and error if not

**Comment by malfet** [comment]
> AI: check that sccache can write to bucket and error if not

Weird thing about sccache is that it does not use libaws, but rather relies on some rust implementation (TODO: find the link)
