### ISSUE TITLE
CircleCI "master" commits are inconsistent

### ISSUE THREAD

**Issue by anderspapitto** [pytorch/pytorch#13073]
## 🐛 Bug

Our CircleCI setup chooses a commit of "master" to merge with per job, when the job runs, so this is not consistent across the tests of a single PR. We should find a way to make this be consistent again.

**Comment by anderspapitto** [comment]
cc @yf225 @ezyang

**Comment by yf225** [comment]
Solved by https://github.com/pytorch/pytorch/pull/13074.
