### ISSUE TITLE
xpu: huggingface generation pipelines are missing xpu aten ops causing perf impact

### ISSUE THREAD

**Issue by dvrogozh** [pytorch/pytorch#130795]
The following aten ops are not implemented for xpu running huggingface generation pipelines:

- [x] `aten::exponential_`, https://github.com/intel/torch-xpu-ops/pull/527
- [x] `aten::isin.Tensor_Tensor_out`, https://github.com/intel/torch-xpu-ops/pull/548
- [x] `aten::multinomial`, https://github.com/intel/torch-xpu-ops/pull/520
- [x] `aten::topk.values`, https://github.com/intel/torch-xpu-ops/pull/547

Found running examples from:
* https://huggingface.co/mosaicml/mpt-7b
* https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct
* https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct

CC: @gujinghui @EikanWang @fengyuan14 @guangyey @jgong5

cc @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by jingxu10** [comment]
all merged
