### ISSUE TITLE
[dynamo] map in dynamo doesn't return an iterable

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#130750]
`call_map` in `builtin.py` currently returns a `TupleVariable`: https://github.com/pytorch/pytorch/blob/00d71b3e865a6a2d27c9d7a273764390548cf0b8/torch/_dynamo/variables/builtin.py#L1476

This is different than what `map` actually returns:
```python
import torch

def f(a):
    return a[0] * a[1]

x = [torch.randn(5) for _ in range(3)]

def g(x):
    return map(f, x)

print(torch.compile(g, fullgraph=True, backend="eager")(x))
print(g(x))
```

Output:
```
(tensor(-0.5240), tensor(-1.2015), tensor(1.1588))
<map object at 0x7f9b90beb610>
```

Incorrect tracing can lead to incorrect behavior:
```python
def h(x):
    if isinstance(map(f, x), tuple):
        return 1
    return 0

print(torch.compile(h, fullgraph=True, backend="eager")(x))
print(h(x))
```

Output:
```
1
0
```

We could fix this by using a new `MapVariable` tracker that codegens a map object.

Discovered when working on https://github.com/pytorch/pytorch/pull/130748.

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by williamwen42** [comment]
Another issue: when dynamo traces through `map`, we immediately evaluate each element, which may not be correct, e.g.

```python
import torch
import itertools

l = []
def g(a):
    l.append(a)
    return a + 1

def f(x):
    m = map(g, x)
    lst = list(itertools.islice(m, 5))
    return len(l)

inp = [i for i in range(10)]
print(f(inp))

inp = [i for i in range(10)]
print(torch.compile(f, backend="eager", fullgraph=True)(inp))
```

Output:
```
5
10
```

**Comment by Aashishthakur10** [comment]
I would like to take a look at this

**Comment by williamwen42** [comment]
@Aashishthakur10 I actually already started to look into this.
