### ISSUE TITLE
 torch._export.aot_compile reports an error when compiling the model after int8 quantization

### ISSUE THREAD

**Issue by sujuyu** [pytorch/pytorch#130822]
### 🐛 Describe the bug

There are many nn.Linear layers in my model. I use Intel's x86 backend to quantify them. The code refers to Intel's official tutorial. [intel link](https://www.intel.com/content/www/us/en/developer/articles/technical/accelerate-pytorch-int8-inf-with-new-x86-backend.html)
```python
import torch
from torch.ao.quantization import get_default_qconfig_mapping, QConfig, QConfigMapping
from torch.quantization.quantize_fx import prepare_fx, convert_fx
from torchvision import models

from fx_user_model_fp32.user_model import user_model
from export_dynamicLib_func import DataProcesser, ValifyDynamicLib
from torch.ao.quantization.observer import (
    default_observer, 
    default_weight_observer,
    MovingAveragePerChannelMinMaxObserver,
)

def create_custom_qconfig_mapping():
    # 创建默认的 qconfig
    qconfig = QConfig(activation=default_observer, weight=default_weight_observer)
    # 创建 QConfigMapping 并设置为只对 nn.Linear 进行量化
    qconfig_mapping = QConfigMapping().set_object_type(torch.nn.Linear, qconfig)
    return qconfig_mapping


qconfig_mapping = create_custom_qconfig_mapping()

# model_fp32 = MyModel().eval()
model_fp32 = user_model().eval().to('cpu')
_, inputs_list = DataProcesser.read_inputs_dict(device="cpu")
prepared_model = prepare_fx(model_fp32, qconfig_mapping, example_inputs=tuple(inputs_list))

# Calibration
# calibration_data_loader = ...
# for x in calibration_data_loader:
#     x = calibration_data_loader()
#     prepared_model(x)

# Convert to quantized model
quantized_model = convert_fx(prepared_model)

_, inputs_list = DataProcesser.read_inputs_dict(device="cpu")
y = quantized_model(*inputs_list)
```
Quantization is successful, and the quantization and inverse quantization operators are indeed inserted before and after nn.Linear
```python
    %user_model_attention_layers_0_proj_k_linear : [num_users=2] = call_module[target=user_model.attention_layers.0.proj_k.linear](args = (%quantize_per_tensor,), kwargs = {})
    %dequantize_2 : [num_users=1] = call_method[target=dequantize](args = (%user_model_attention_layers_0_proj_k_linear,), kwargs = {})
    %user_model_attention_layers_0_proj_v_linear : [num_users=2] = call_module[target=user_model.attention_layers.0.proj_v.linear](args = (%quantize_per_tensor,), kwargs = {})
    %dequantize_3 : [num_users=1] = call_method[target=dequantize](args = (%user_model_attention_layers_0_proj_v_linear,), kwargs = {})
    %getattr_5 : [num_users=2] = call_function[target=builtins.getattr](args = (%user_model_attention_layers_0_proj_q_linear, shape), kwargs = {})
    %getitem_3 : [num_users=1] = call_function[target=operator.getitem](args = (%getattr_5, 1), kwargs = {})
```

Then I try to do AOT compilation:
```python
import os
from int8_quantization import Int8Quantization
dynamicLib_path = torch._export.aot_compile(
    quantized_model,
    args = tuple(inputs_list),
    dynamic_shapes = Int8Quantization._get_dynamic_shapes(inputs_list),
    options={
            "aot_inductor.output_path": os.path.join('dynamicLib', "quantized_x86_model_cpu_fp32.so"), 
            "max_autotune": True
            },
)
```
there is a error:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
File [/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py:1878](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py:1878), in FakeTensorMode._dispatch_impl(self, func, types, args, kwargs)
   [1877](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py:1877)     with in_kernel_invocation_manager(self):
-> [1878](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py:1878)         r = func(*args, **kwargs)
   [1879](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py:1879) except NotImplementedError as not_implemented_error:

File [/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_ops.py:727](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_ops.py:727), in OpOverload.__call__(self_, *args, **kwargs)
    [724](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_ops.py:724) def __call__(self_, *args, **kwargs):  # noqa: B902
    [725](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_ops.py:725)     # use `self_` to avoid naming collide with aten ops arguments that
    [726](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_ops.py:726)     # are named "self". This way, all the aten ops can be called by kwargs.
--> [727](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_ops.py:727)     return self_._op(*args, **kwargs)

NotImplementedError: aten::quantize_per_tensor.tensor_qparams: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add a fake impl. Please see the following for next steps:  https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html

During handling of the above exception, another exception occurred:

UnsupportedOperatorException              Traceback (most recent call last)
File [/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_dynamo/utils.py:1939](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_dynamo/utils.py:1939), in run_node(tracer, node, args, kwargs, nnmodule)
   [1938](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_dynamo/utils.py:1938) if op == "call_function":
-> [1939](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_dynamo/utils.py:1939)     return node.target(*args, **kwargs)
   [1940](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/_dynamo/utils.py:1940) elif op == "call_method":

File [/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/utils/_stats.py:21](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/utils/_stats.py:21), in count.<locals>.wrapper(*args, **kwargs)
     [20](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22766563746f725f726563616c6c5f4131305f636f6e7461696e6572227d.vscode-resource.vscode-cdn.net/home/admin/zy429782/miniforge3/envs/torch_preview_cu121/lib/python3.10/site-packages/torch/utils/_stats.py:20) simple_call_counter[fn.__qualname__] = simple_call_counter[fn.__qualname__] + 1
...
   File "<eval_with_key>.5", line 57, in forward
    quantize_per_tensor = torch.quantize_per_tensor(getitem_2, user_model_attention_layers_0_proj_q_linear_input_scale_0, user_model_attention_layers_0_proj_q_linear_input_zero_point_0, torch.quint8);  user_model_attention_layers_0_proj_q_linear_input_scale_0 = user_model_attention_layers_0_proj_q_linear_input_zero_point_0 = None

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```
There is a similar question on issue, but it has been closed: [issue link](https://github.com/pytorch/pytorch/issues/93430)

I use the preview torch == 2.5.0, 
Is there any way for inductor to support Intel quantization operator?

### Error logs

![image](https://github.com/user-attachments/assets/3f059e77-187a-4345-9a8c-c149dad07f03)

NotImplementedError: aten::quantize_per_tensor.tensor_qparams: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add a fake impl. Please see the following for next steps:  https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html

### Versions

Collecting environment information...
PyTorch version: 2.5.0.dev20240715
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Alibaba Group Enterprise Linux Server 7.2 (Paladin) (x86_64)
GCC version: (GCC) 10.2.1 20200825 (Alibaba 10.2.1-3 2.17)
Clang version: 13.0.1 (Alibaba 13.0.1-2.fix20240307155812.alios7 77024452014c2872fa1c55b8456488fcbf309dcc)
CMake version: Could not collect
Libc version: glibc-2.32

Python version: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-4.19.91-009.ali4000.alios7.x86_64-x86_64-with-glibc2.32
Is CUDA available: True
CUDA runtime version: 12.3.52
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn.so.8.9.5
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.5
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.5
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.5
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.5
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.5
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
Stepping:              6
CPU MHz:               2900.000
CPU max MHz:           3500.0000
CPU min MHz:           800.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              49152K
NUMA node0 CPU(s):     0-31,64-95
NUMA node1 CPU(s):     32-63,96-127
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==2.0.0
[pip3] torch==2.5.0.dev20240715
[pip3] torchaudio==2.4.0.dev20240715
[pip3] torchvision==0.20.0.dev20240715
[pip3] triton==3.0.0
[conda] blas                      1.0                         mkl    conda-forge
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] libopenvino-pytorch-frontend 2024.2.0             he02047a_1    conda-forge
[conda] mkl                       2022.1.0           hc2b9512_224  
[conda] numpy                     2.0.0           py310h515e003_0    conda-forge
[conda] pytorch                   2.5.0.dev20240715 py3.10_cuda12.1_cudnn9.1.0_0    pytorch-nightly
[conda] pytorch-cuda              12.1                 ha16c6d3_6    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                2.4.0.dev20240715     py310_cu121    pytorch-nightly
[conda] torchtriton               3.0.0+dedb7bdf33           py310    pytorch-nightly
[conda] torchvision               0.20.0.dev20240715     py310_cu121    pytorch-nightly

cc @ezyang @anijain2305 @chauhang @penguinwu @desertfire @chenyang78

**Comment by desertfire** [comment]
@chunyuan-w, can you help to take a look since it is related to Intel quantization?

**Comment by chunyuan-w** [comment]
> @chunyuan-w, can you help to take a look since it is related to Intel quantization?

Adding @leslie-fang-intel for the quantization related part

**Comment by leslie-fang-intel** [comment]
Hi @sujuyu, the fx path quantization is based on `QuantizedTensor` implementation and not supported with Inductor. Could you take a try of PT2E Quantization, here is the tutorial https://pytorch.org/tutorials/prototype/pt2e_quant_x86_inductor.html?highlight=x86 for your reference, you may need to change the compilation part with AOT compilation.

**Comment by sujuyu** [comment]
> Hi @sujuyu, the fx path quantization is based on `QuantizedTensor` implementation and not supported with Inductor. Could you take a try of PT2E Quantization, here is the tutorial https://pytorch.org/tutorials/prototype/pt2e_quant_x86_inductor.html?highlight=x86 for your reference, you may need to change the compilation part with AOT compilation.

Thank you very much for your reply, it is of great help to me, a beginner in torch quantization.

**Comment by leslie-fang-intel** [comment]
> Finally, I can get a quantized model with q-dq nodes inserted before and after torch.ops.aten.linear, but how should I send this model to onednn or other backends for execution? There seems to be no introductory tutorial for this in pytorch.

It's also in the tutorial, 
```
with torch.no_grad():
   optimized_model = torch.compile(converted_model)
```
and running your script with environment variable as 
```
TORCHINDUCTOR_FREEZING=1 python example_x86inductorquantizer_pytorch_2_1.py
```
It will lower the model into Inductor and for linear it will be executed with oneDNN backend.

> For example, maybe we can merge the dq->linear->q nodes into onednn.qlinear_pointwise nodes.

Exactly.

For AOT complication, chunyuan can provide more details of API. It might be slightly different.

**Comment by sujuyu** [comment]
@chunyuan-w 

> > Finally, I can get a quantized model with q-dq nodes inserted before and after torch.ops.aten.linear, but how should I send this model to onednn or other backends for execution? There seems to be no introductory tutorial for this in pytorch.
> 
> It's also in the tutorial,
> 
> ```
> with torch.no_grad():
>    optimized_model = torch.compile(converted_model)
>    optimized_model(*example)  # Need to run under the torch.no_grad
> ```
> 
> and running your script with environment variable as
> 
> ```
> TORCHINDUCTOR_FREEZING=1 python example_x86inductorquantizer_pytorch_2_1.py
> ```
> 
> It will lower the model into Inductor and for linear it will be executed with oneDNN backend.
> 
> > For example, maybe we can merge the dq->linear->q nodes into onednn.qlinear_pointwise nodes.
> 
> Exactly.
> 
> For AOT complication, chunyuan can provide more details of API. It might be slightly different.

I've identified the issue: after invoking 
```python
optimized_model = torch.compile(quantized_model)
```
 it's essential to execute 
```
optimized_model(*example_inputs) 
```
for the changes to take effect. Running this in my Python environment, I observed that the float32 model on CPU consumes 108ms, whereas the quantized model utilizing OneDNN takes only 37ms—truly remarkable performance, and I'm deeply grateful for your assistance.

 @chunyuan-w However, when attempting to compile the quantized model into a dynamic library using torch._export.aot_compile,:
```python
with torch.no_grad():
        optimized_model = torch.compile(quantized_model)
        optimized_model(*inputs_list)
        dynamicLib_path = torch._export.aot_compile(
            optimized_model,
            args = tuple(inputs_list),
            dynamic_shapes = dynamic_shapes,
            options={
                    "aot_inductor.output_path": os.path.join('dynamicLib', "quantized_model_cpu_fp32.so"), 
                    "max_autotune": True
                    },
        )
```
I've encountered two hurdles. 
Firstly, there seems to be no support for the dynamic_shapes parameter.  I print the optimized_model.code, get the forward func like below:
```python
def forward(self, context_columns, item_clk_seq, item_clk_seq_length, label, query_columns, query_seq, query_seq_length, target_atten_query, user_columns):
    arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, = fx_pytree.tree_flatten_spec(([context_columns, item_clk_seq, item_clk_seq_length, label, query_columns, query_seq, query_seq_length, target_atten_query, user_columns], {}), self._in_spec)
...........
```
Obviously there are 9 inputs, so I specify that the first dimension of each input is variable:
```bash
  File "/home/admin/zy429782/miniforge3/envs/torch231_cuda121/lib/python3.8/site-packages/torch/export/dynamic_shapes.py", line 577, in tree_zip
    raise UserError(
torch._dynamo.exc.UserError: Expected {'context_columns': {0: <class '__main__.batch'>}, 'item_clk_seq': {0: <class '__main__.batch'>}, 'item_clk_seq_length': {0: <class '__main__.batch'>}, 'label': {0: <class '__main__.batch'>}, 'query_columns': {0: <class '__main__.batch'>}, 'query_seq': {0: <class '__main__.batch'>}, 'query_seq_length': {0: <class '__main__.batch'>}, 'target_atten_query': {0: <class '__main__.batch'>}, 'user_columns': {0: <class '__main__.batch'>}} to have 1 items
```
Why it only need 1 items?
 To solve this problem I can only choose a fixed batchsize

Secondly, upon loading the dynamically compiled library using torch._export.aot_load and benchmarking, I noticed that the float32 CPU model requires 39.5ms, whereas the quantized model demands 43.8ms, indicating that the OneDNN optimizations aren't being incorporated into the dynamic library. I'm curious if the AOT compilation currently supports the export of quantized models. Could you shed some light on this? @chunyuan-w

**Comment by leslie-fang-intel** [comment]
> for the changes to take effect. Running this in my Python environment, I observed that the float32 model on CPU consumes 108ms, whereas the quantized model utilizing OneDNN takes only 37ms—truly remarkable performance, and I'm deeply grateful for your assistance.

Nice!

**Comment by sujuyu** [comment]
> > for the changes to take effect. Running this in my Python environment, I observed that the float32 model on CPU consumes 108ms, whereas the quantized model utilizing OneDNN takes only 37ms—truly remarkable performance, and I'm deeply grateful for your assistance.
> 
> Nice!

May I humbly ask for your assistance with one more inquiry? I believe it would be highly valuable to integrate OneDNN quantization with AOT compilation. If successful, I intend to contribute by also authoring a public document detailing the process.

**Comment by sujuyu** [comment]
> > for the changes to take effect. Running this in my Python environment, I observed that the float32 model on CPU consumes 108ms, whereas the quantized model utilizing OneDNN takes only 37ms—truly remarkable performance, and I'm deeply grateful for your assistance.
> 
> Nice!

May I humbly ask for your assistance with one more inquiry? I believe it would be highly valuable to integrate OneDNN quantization with AOT compilation. If successful, I intend to contribute by also authoring a public document detailing the process.

Now I get the optimized_model quantized to onednn：
```python
with torch.no_grad():
        # Optional: using the C++ wrapper instead of default Python wrapper
        optimized_model = torch.compile(quantized_model)
        optimized_model(*inputs_list)
```
I think as long as I can obtain the graph in which the torch.ops.aten.linear operator is replaced by onednn.qlinear_pointwise, and then perform aot_compile on this graph, I can get the quantized dynamic library.

but the graph of optimized_model is like below（use print(optimized_model.graph)）:
```python
    %dequantize_per_tensor_default_20 : [num_users=1] = call_function[target=torch.ops.quantized_decomposed.dequantize_per_tensor.default](args = (%quantize_per_tensor_default_20, 0.0061807106249034405, 2, 0, 255, torch.uint8), kwargs = {})
    %main_logits_layer_scale_0 : [num_users=1] = get_attr[target=main_logits_layer_scale_0]
    %main_logits_layer_zero_point_0 : [num_users=1] = get_attr[target=main_logits_layer_zero_point_0]
    %_frozen_param25 : [num_users=1] = get_attr[target=_frozen_param25]
    %dequantize_per_channel_default_25 : [num_users=1] = call_function[target=torch.ops.quantized_decomposed.dequantize_per_channel.default](args = (%_frozen_param25, %main_logits_layer_scale_0, %main_logits_layer_zero_point_0, 0, -128, 127, torch.int8), kwargs = {})
    %linear_25 : [num_users=1] = call_function[target=torch.ops.aten.linear.default](args = (%dequantize_per_tensor_default_17, %dequantize_per_channel_default_25), kwargs = {})
    %bias_logits_layer_scale_0 : [num_users=1] = get_attr[target=bias_logits_layer_scale_0]
    %bias_logits_layer_zero_point_0 : [num_users=1] = get_attr[target=bias_logits_layer_zero_point_0]
    %_frozen_param26 : [num_users=1] = get_attr[target=_frozen_param26]
```

Obviously, linear_25 is still performed on float32. may I get the graph what is it composed of onednn op?

**Comment by leslie-fang-intel** [comment]
I am not sure about the dynamic library you talked about here. But I guess the AOT compilation should work with PT2E quantization flow, let's wait for @chunyuan-w to take a look of AOT Compilation failure?

**Comment by sujuyu** [comment]
> I am not sure about the dynamic library you talked about here. But I guess the AOT compilation should work with PT2E quantization flow, let's wait for @chunyuan-w to take a look of AOT Compilation failure?

Thank you so much! You're the most dedicated open-source developer I've come across. Words can't adequately express my gratitude. Once I navigate this model deployment pipeline successfully, I'll definitely endeavor to write a tutorial, perhaps a simple 'toy' one, to share my experience and pay it forward.🌹

**Comment by chunyuan-w** [comment]
> Secondly, upon loading the dynamically compiled library using torch._export.aot_load and benchmarking, I noticed that the float32 CPU model requires 39.5ms, whereas the quantized model demands 43.8ms, indicating that the OneDNN optimizations aren't being incorporated into the dynamic library.

Hi @sujuyu, here's the AOTInductor tutorial link: https://pytorch.org/docs/main/torch.compiler_aot_inductor.html for your reference.

In the code snippet you provided, it seems you passed the `optimized_model` (which already has `torch.compile` invoked) to `aot_compile`, while for AOTInductor, you don't need to call `torch.compile`. The `torch._export.aot_compile` API will do the model compilation for you and it will then generate a `.so` of this compiled model.

Here's a small test code I ran locally, you could run the below python file with `TORCHINDUCTOR_FREEZING=1 python test.py`

The `test.py` file:
```py
import os
import torch
from torch.ao.quantization.quantize_pt2e import prepare_pt2e, convert_pt2e
import torch.ao.quantization.quantizer.x86_inductor_quantizer as xiq
from torch.ao.quantization.quantizer.x86_inductor_quantizer import X86InductorQuantizer
from torch._export import capture_pre_autograd_graph

class M(torch.nn.Module):
    def __init__(self, bias):
        super().__init__()
        self.linear = torch.nn.Linear(10, 30, bias)

    def forward(self, x):
        return self.linear(x)

model = M(bias=True)
model = model.eval()

x = torch.randn(56, 10)
example_inputs = (x,)

with torch.no_grad():
    exported_model = capture_pre_autograd_graph(
        model,
        example_inputs
    )

quantizer = X86InductorQuantizer()
quantizer.set_global(xiq.get_default_x86_inductor_quantization_config())    

prepared_model = prepare_pt2e(exported_model, quantizer)
prepared_model(*example_inputs)

converted_model = convert_pt2e(prepared_model)

with torch.no_grad():
    so_path = torch._export.aot_compile(
        converted_model,
        example_inputs,
        options={"aot_inductor.output_path": os.path.join(os.getcwd(), "model.so")},
    )
```

I checked the generated code and it has the quantized linear OP in it (you could dump it by setting this ENV `export TORCH_LOGS="+output_code"`) so the OneDNN optimizations of the quantization OP should have already been included in this .so.
```log
auto buf1 = op_qlinear_pointwise.call(buf0, x_scale, x_zp, _frozen_param0, L__self___linear_scale_0, L__self___linear_zero_point_0_0, L__self___linear_bias, 1.0, 0L, at::kFloat, "none", {std::nullopt}, "");
```

Could you try the above way on your model and see if it helps?

**Comment by sujuyu** [comment]
> chunyuan-w
The quantization of linear layers using oneDNN indeed took effect, albeit possibly due to the nature of the model itself. Under the condition where both versions were compiled into dynamic libraries, a speed improvement of 13% was observed.

Thanks to both authors @chunyuan-w @leslie-fang-intel for helping out with my basic quantization questions. I feel bad for taking up your time, but I really appreciate it. I've written up a joy tutorial based on our issue discussion here. 
[Speed Up PyTorch Model Inference on CPU with Intel OneDNN Integration](https://github.com/sujuyu/ZhangYu-s-Blog/tree/main/torch_onednn_quantization)
Hopefully, it'll help someone else in the same boat.
