### ISSUE TITLE
`size()` type for `size` argument of `normal()` works against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130881]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.normal.html) of `normal()` doesn't say [size()](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) type for `size` argument as shown below:

> - size ([int](https://docs.python.org/3/library/functions.html#int)...) – a sequence of integers defining the shape of the output tensor.

But, `size()` type for `size` argument of `normal()` works against the doc as shown below:

```python
import torch

my_tensor = torch.tensor([8, 3, 6])

my_tensor.size()
# torch.Size([3])

torch.normal(mean=1., std=4., size=my_tensor.size())
# tensor([ 2.0851, -4.0917,  3.0108])
```

**Comment by malfet** [comment]
- Python is a duct-typed language, and `torch.Size` behaves like sequence
- `isinstance(torch.Size(), tuple)` returns true
Therefore closing, since it works as documented.
