### ISSUE TITLE
`size()` type for `size` argument of `rand()/randn()/randint()` works against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130872]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.rand.html) of `rand()` doesn't say [size()](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) type for `size` argument as shown below:

> size ([int](https://docs.python.org/3/library/functions.html#int)...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.

But, `size()` type for `size` argument of `rand()` works against the doc as shown below:

```python
import torch

my_tensor = torch.tensor([8, 3, 6])

my_tensor.size()
# torch.Size([3])

torch.rand(size=my_tensor.size())
# tensor([0.8406, 0.9713, 0.5725])
```

**Comment by malfet** [comment]
- Python is a duct-typed language, and `torch.Size` behaves like sequence
- `isinstance(torch.Size(), tuple)` returns true
So closing, as working as expected
