### ISSUE TITLE
`size()` type for `size` argument of `ones()` works against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130885]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.ones.html) of `ones()` doesn't say [size()](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) type for `size` argument as shown below:

> size ([int](https://docs.python.org/3/library/functions.html#int)...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.

But, `size()` type for `size` argument of `ones()` works against the doc as shown below:

```python
import torch

my_tensor = torch.tensor([8, 3, 6])

my_tensor.size()
# torch.Size([3])

torch.ones(size=my_tensor.size())
# tensor([1., 1., 1.])
```

**Comment by malfet** [comment]
Please stop creating separate issues for the same behavior you want to report.
Closing, as `torch.Size` is a sequence of integers, moreover `isinstance(torch.Size(), tuple)` returns true, so works as expected
