### ISSUE TITLE
Convert Co-DETR to ONNX Format 

### ISSUE THREAD

**Issue by brim1754** [pytorch/pytorch#130828]
### 🚀 The feature, motivation and pitch

When converting the Co-DETR model to ONNX format using mmdeploy, I encounter an issue in torch/jit/_trace.py:  
File "torch/jit/_trace.py", line 124, in wrapper
    out_vars, _ = _flatten(outs) 
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: DetDataSample

The problem arises because the DetDataSample type is not supported by _flatten, which only handles tuples, lists, and Variables.

Issue Location: torch/jit/_trace.py, line 124
Error Message: RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: DetDataSample
Context: This issue occurs while trying to export the Co-DETR model to ONNX format using mmdeploy.

Desired Feature 

Support for custom data types like DetDataSample in the PyTorch JIT compilation pipeline. Specifically:

    Extend _flatten Functionality: Modify the _flatten function to handle custom types such as DetDataSample by implementing custom serialization and deserialization routines.
    Enhanced Data Handling: Allow the JIT to process complex objects that are not natively supported, providing a mechanism for custom data type integration.

### Alternatives

Manual Data Transformation: Currently, one approach is to manually convert DetDataSample into a list or tuple of tensors before passing it to _flatten. However, this approach is cumbersome and does not address the root issue of JIT's limited data type support.

Custom Wrapper Functions: Implement wrapper functions that transform DetDataSample into a supported format before passing it to the JIT functions. This workaround involves additional code and does not provide a universal solution.

### Additional context

    Model: Co-DETR
    Tool: mmdeploy for converting to ONNX format

**Comment by justinchuby** [comment]
We probably won’t get to this anytime soon. I recommend testing if torch.export.export supports this case, as we are offering a conversion route going from ExportedProgram to ONNX. Contributions welcomed.

**Comment by brim1754** [comment]
> We probably won’t get to this anytime soon. I recommend testing if torch.export.export supports this case, as we are offering a conversion route going from ExportedProgram to ONNX. Contributions welcomed.

Thank you for your response, I found a temporary solution to overcome this. I shared it in MR for people who will encounter the same issue.
