### ISSUE TITLE
`size()` type for `size` argument of `empty_strided()` works against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130900]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.empty_strided.html) of `empty_strided()` doesn't say [size()](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) type for `size` argument as shown below:

> - size ([tuple](https://docs.python.org/3/library/stdtypes.html#tuple) of [int](https://docs.python.org/3/library/functions.html#int)) – the shape of the output tensor

But, `size()` type for `size` argument of `empty_strided()` works against the doc as shown below:

```python
import torch

my_tensor = torch.tensor([8, 3, 6])

my_tensor.size()
# torch.Size([3])

torch.empty_strided(size=my_tensor.size(), stride=(0,))
# tensor([-6.9564e-29, -6.9564e-29, -6.9564e-29])
```

**Comment by malfet** [comment]
Please STOP creating separate issues for the same behavior you want to report.
Closing, as `isinstance(torch.Size(), tuple)` returns true, so `torch.Size` should be accepted according to the documentation.
