### ISSUE TITLE
Adam optimizer initializer useless if condition, torch v2.3.0

### ISSUE THREAD

**Issue by EGanji** [pytorch/pytorch#130980]
### 🐛 Describe the bug

There is a logical problem in Adam optimizer implementation.
It appeared when I tried to use lr as a tensor. 
1. If `lr` is a float, the second `if-condition` will not run,
2. If `lr` is a tensor, the code raises an error from the first `if-condition` and never checks the second one.

In summary, no matter what, the second condition does nothing.
One possible fix is to add `if instance(lr, float) and not 0.0 <= lr` instead.

```
class Adam(Optimizer):
    def __init__(self,
                 params: ParamsT,
                 lr: Union[float, Tensor] = 1e-3,
                 betas: Tuple[float, float] = (0.9, 0.999),
                 eps: float = 1e-8,
                 weight_decay: float = 0,
                 amsgrad: bool = False,
                 *,
                 foreach: Optional[bool] = None,
                 maximize: bool = False,
                 capturable: bool = False,
                 differentiable: bool = False,
                 fused: Optional[bool] = None):
        if not 0.0 <= lr:
            raise ValueError(f"Invalid learning rate: {lr}")
        if isinstance(lr, Tensor) and foreach and not capturable:
            raise ValueError("lr as a Tensor is not supported for capturable=False and foreach=True")
```
This is the output of the code:

![Screenshot 2024-07-17 at 4 15 10 PM](https://github.com/user-attachments/assets/727001de-acb8-4241-9f6b-18c9240a223a)

### Versions

The command above did not work on my machine. However, this is the info:
`Adam optimizer initializer, torch v2.3.0, python 3.11 on macOSX (Sonoma 14.5).`

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by qqaatw** [comment]
LR is expected to be an 1-element tensor. But I agree the error message of the first condition is not ideal for your case.
