### ISSUE TITLE
`size()` type for `shape` argument of `reshape()` works against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130901]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.randn.html) of `reshape()` doesn't say [size()](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) type for `shape` argument as shown below:

> - shape ([tuple](https://docs.python.org/3/library/stdtypes.html#tuple) of [int](https://docs.python.org/3/library/functions.html#int)) – the new shape

But, `size()` type for `shape` argument of `reshape()` works against the doc as shown below:

```python
import torch

my_tensor = torch.tensor([0, 1, 2])

my_tensor.size()
# torch.Size([3])

torch.reshape(input=my_tensor, shape=torch.tensor([8, 3, 6]).size())
# tensor([0, 1, 2])
```

**Comment by malfet** [comment]
Please STOP creating separate issues for the same behavior you want to report.
Closing, as `isinstance(torch.Size(), tuple)` returns true, so `torch.Size` should be accepted according to the documentation.
