### ISSUE TITLE
xpu backend build fails if cloned directory is named python-x.y

### ISSUE THREAD

**Issue by dvrogozh** [pytorch/pytorch#130999]
If pytorch is cloned into the specifically named output directory - `python-x.y`, then XPU backend build will fail with the error below. Naming cloned directory in such a way might be a natural choice if someone wants to build the release. Issue can be reproduced on both latest master (https://github.com/pytorch/pytorch/commit/fc3dbcd1c3bc4ed90f2d6ec67fc66f1d2e283a31) and on head of 2.4 release branch (https://github.com/pytorch/pytorch/commit/d990dada86a8ad94882b5c23e859b88c0c255bda). Repro steps:
1. Setup environment following https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpus.html
2. Setup pytorch virtual environment:
```
python3 -m venv ~/pytorch.env
. ~/pytorch.env/bin/activate
```
3. Clone pytorch in this way:
```
git clone https://github.com/pytorch/pytorch.git pytorch-2.4
```
4. Build:
```
_GLIBCXX_USE_CXX11_ABI=1 USE_XPU=1 python3 setup.py develop
```

You will see this error:
```
FAILED: xpu_mkldnn_proj-prefix/src/xpu_mkldnn_proj-stamp/xpu_mkldnn_proj-configure /home/dvrogozh/tmp/pytorch-2.4/build/xpu_mkldnn_proj-prefix/src/xpu_mkldnn_proj-stamp/xpu_mkldnn_proj-configure
cd /home/dvrogozh/tmp/pytorch-2.4/build/xpu_mkldnn_proj-prefix/src/xpu_mkldnn_proj-build && /usr/bin/cmake -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DDNNL_GPU_RUNTIME=SYCL -DDNNL_CPU_RUNTIME=THREADPOOL -DDNNL_BUILD_TESTS=OFF -DDNNL_BUILD_EXAMPLES=OFF -DONEDNN_BUILD_GRAPH=OFF -DDNNL_LIBRARY_TYPE=STATIC -DDNNL_DPCPP_HOST_COMPILER=g++ -G Ninja -GNinja /home/dvrogozh/tmp/pytorch-2.4/third_party/ideep/mkl-dnn && /usr/bin/cmake -E touch /home/dvrogozh/tmp/pytorch-2.4/build/xpu_mkldnn_proj-prefix/src/xpu_mkldnn_proj-stamp/xpu_mkldnn_proj-configure
-- DNNL_TARGET_ARCH: X64
-- DNNL_LIBRARY_NAME: dnnl
-- Host compiler: /usr/bin/g++
-- Host compiler kind: GNU
-- Host compiler version: 2.4
CMake Error at cmake/host_compiler_id.cmake:100 (message):
  The minimum version of GNU host compiler is 7.4.
Call Stack (most recent call first):
  cmake/SYCL.cmake:22 (include)
  CMakeLists.txt:118 (include)


-- Configuring incomplete, errors occurred!
```

CC: @gujinghui @EikanWang @fengyuan14 @guangyey @jgong5 

cc @malfet @seemethere @bdhirsh

**Comment by fengyuan14** [comment]
Looks XPU irrelevant? Could you build with `USE_XPU=0`?

**Comment by dvrogozh** [comment]
> Looks XPU irrelevant? Could you build with USE_XPU=0?

It's XPU specific. I can build fine with `USE_XPU=0` and it fails to build with `USE_XPU=1`.

**Comment by guangyey** [comment]
Thanks  @dvrogozh 
This is a oneDNN cmake bug. I will info oneDNN team to fix it.

**Comment by guangyey** [comment]
oneDNN team has fixed this issue. This issue will be solved by upgrading oneDNN.
A workaround solution is removing `2.4` from the clone folder name `pytorch-2.4`

**Comment by dvrogozh** [comment]
> oneDNN team has fixed this issue. This issue will be solved by upgrading oneDNN.

Ok... but oneDNN is open source project... Can we review PR with the fix, please?

**Comment by vpirogov** [comment]
> Ok... but oneDNN is open source project... Can we review PR with the fix, please?

Sure! The fix is available in oneDNN [v3.4.4](https://github.com/oneapi-src/oneDNN/releases/tag/v3.4.4) patch release. Relevant commit is https://github.com/oneapi-src/oneDNN/commit/fcaa1b44110280919674c801f4c063f5651b5760. We'll also have it included into upcoming oneDNN v3.5.2 this week.

**Comment by vpirogov** [comment]
oneDNN [v3.5.2](https://github.com/oneapi-src/oneDNN/releases/tag/v3.5.2) is out.

**Comment by guangyey** [comment]
oneDNN has been upgraded to 3.5.3, see https://github.com/pytorch/pytorch/pull/131620
So, I think this issue has been resolved.

**Comment by EikanWang** [comment]
@guangyey , I think we can close it.

**Comment by guangyey** [comment]
Closed as it is resolved.
