### ISSUE TITLE
Cannot construct torch::nn::Module on Windows

### ISSUE THREAD

**Issue by benbellick** [pytorch/pytorch#130951]
### 🐛 Describe the bug

I recently opened #130874, but I wanted to open this as well as I believe it to be more fundamental.

[Following along this tutorial](https://pytorch.org/tutorials/advanced/cpp_frontend.html), I tried to construct a model in C++-land as follows:
```C++
#include <torch/script.h>
#include <torch/torch.h>
#include <iostream>

struct Net : torch::nn::Module {
  Net(int64_t N, int64_t M)
      : linear(register_module("linear", torch::nn::Linear(N, M))) {
    another_bias = register_parameter("b", torch::randn(M));
  }
  torch::Tensor forward(torch::Tensor input) {
    return linear(input) + another_bias;
  }
  torch::nn::Linear linear;
  torch::Tensor another_bias;
};
//src/main.cpp
int main(int argc, char* argv[]) {
    std::cout << "Constructing net..." << std::endl;
    Net net(4, 5);
    std::string f = "net.pt";
    std::cout << "Saving model..." << std::endl;
    torch::save(net, f);
    std::cout << "Loading model..." << std::endl;
    torch::jit::load(f);
    std::cout << "Loaded model!!!" << std::endl;
    return 0;
}
```

I'm linking with the most recent version of `libtorch`, which you can see here in my CMakeLists.txt

```Cmake
cmake_minimum_required(VERSION 3.27)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
project(example VERSION 1.0
  DESCRIPTION "C++ wrapper around example project"
  LANGUAGES CXX)

include(FindOpenMP)

## Download libtorch

if (WIN32)
  set(LIBTORCH_URL https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-2.3.1%2Bcpu.zip)
elseif(APPLE)
  set(LIBTORCH_URL https://download.pytorch.org/libtorch/cpu/libtorch-macos-arm64-2.3.1.zip)  
elseif(LINUX)
  set(LIBTORCH_URL https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.3.1%2Bcpu.zip)
else()
  message(FATAL_ERROR "Unhandled OS")
endif()
    
file(DOWNLOAD ${LIBTORCH_URL} torch.zip SHOW_PROGRESS)
file(ARCHIVE_EXTRACT INPUT torch.zip DESTINATION lib)

## Setup external deps

list(APPEND CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}/lib/libtorch")
find_package(Torch REQUIRED)
include_directories(${CMAKE_BINARY_DIR}/lib/libtorch/include)
include_directories(${CMAKE_BINARY_DIR}/lib/libtorch/include/torch/csrc/api/include)


## example CLI

add_executable(example-cli src/main.cpp)
target_include_directories(example-cli PUBLIC include)
target_link_libraries(example-cli PRIVATE torch)
if(OpenMP_CXX_FOUND)
    target_link_libraries(example-cli PUBLIC OpenMP::OpenMP_CXX)
endif()
set_property(TARGET example-cli PROPERTY CXX_STANDARD 17)


if (MSVC)
  file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")
  add_custom_command(TARGET example-cli
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
    ${TORCH_DLLS}
    $<TARGET_FILE_DIR:example-cli>)
endif (MSVC)
```

But when I run my script, the construction of the net (`Net net(4,5)`) causes a segmentation fault:
```
$ ./Debug/example-cli.exe
Constructing net...
Segmentation fault
```

### Versions

PyTorch version: 2.3.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.30.0
Libc version: N/A

Python version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070
Nvidia driver version: 536.23
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3700
DeviceID=CPU0
Family=107
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3700
Name=AMD Ryzen 7 2700X Eight-Core Processor
ProcessorType=3
Revision=2050

Versions of relevant libraries:
[pip3] numpy==2.0.0
[pip3] torch==2.3.1
[pip3] torchvision==0.18.1
[conda] Could not collect

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @jbschlosser @albanD @mruberry @walterddr @mikaylagawarecki

**Comment by ZailiWang** [comment]
Hi @xuhancn would you please take a look?

**Comment by mantaionut** [comment]
@benbellick do you have an issue when doing the release build too?
On Windows you need to match your PyTorch configuration with your project.
So if you want to make a debug build you also need to use PyTorch debug.

**Comment by benbellick** [comment]
Ah that is a good catch! Thanks! This was my first time developing on Windows and so I didn't understand the difference. Maybe it could be useful to others to add it to the documentation so no one else gets tripped up by it? 

It also didn't quite resolve my issue, but did cause a new error to come up, which is a good sign:
```
INTEL MKL ERROR: The specified module could not be found. mkl_def.1.dll.
Intel MKL FATAL ERROR: Cannot load mkl_def.1.dll.
```

At the very least, this gives me a new lead. Thanks again!

**Comment by mantaionut** [comment]
@benbellick kind reminder to close this issue if there are no other issues.

**Comment by kalaskarsanket** [comment]
@benbellick closing the issue as discussed in last comments. 
@mantaionut
