### ISSUE TITLE
Compiled DDP + TP unit test fails with `SymNodeVariable() is not a constant`

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#130978]
### 🐛 Describe the bug

Repro:
`pytest -rA test/distributed/_composable/test_replicate_with_compiler.py::DDP_TP_Test::test_ddp_tp`

Error:
```
  File "/data/users/willfeng/pytorch_top/torch/_dynamo/variables/base.py", line 210, in as_python_constant
    raise NotImplementedError(f"{self} is not a constant")
torch._dynamo.exc.InternalTorchDynamoError: SymNodeVariable() is not a constant

from user code:
   File "/data/users/willfeng/pytorch_top/torch/distributed/tensor/parallel/_data_parallel_utils.py", line 34, in _unflatten_tensor
    result = DTensor.from_local(
```

Full error log: https://gist.github.com/yf225/c3827ecdb2915c19f14ffa5be2ca9761

cc. @bdhirsh @fegin 

### Versions

nightly

cc @ezyang @anijain2305 @chauhang @penguinwu @wanchaol @XilunWu @d4l3k

**Comment by ezyang** [comment]
see my comment on other thread

**Comment by yf225** [comment]
Ed's comment: https://github.com/pytorch/pytorch/issues/127797#issuecomment-2234943079

**Comment by bdhirsh** [comment]
Let me know if you want any help with this one

**Comment by yf225** [comment]
Another instance: https://www.internalfb.com/phabricator/paste/view/P1556733675, this time failing within compiled FSDP2. cc. @bdhirsh wonder is it still the same root cause?

**Comment by yf225** [comment]
TODO: use `proxy_args_kwargs()` for the SymNode
