### ISSUE TITLE
`size()` type for `dims` argument of `tile()` works against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130902]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.tile.html) of `tile()` doesn't say [size()](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) type for `dims` argument as shown below:

> - dims ([tuple](https://docs.python.org/3/library/stdtypes.html#tuple)) – the number of repetitions per dimension.

But, `size()` type for `dims` argument of `tile()` works against the doc as shown below:

```python
import torch

my_tensor = torch.tensor([0, 1, 2])

my_tensor.size()
# torch.Size([3])

torch.tile(input=my_tensor, dims=torch.tensor([[8, 3], [6, 4]]).size())
# tensor([[0, 1, 2, 0, 1, 2],
#         [0, 1, 2, 0, 1, 2]])
```

cc @svekars @brycebortree

**Comment by malfet** [comment]
Please stop creating separate issues for the same behavior you want to report.
Closing, as `torch.Size` is a sequence of integers, moreover `isinstance(torch.Size(), tuple)` returns true, so works as expected
