### ISSUE TITLE
CMakeLists does not seem to have the options PYTHON_PACKAGES_PATH and PYTHON_LIBRARY

### ISSUE THREAD

**Issue by Amir-Arsalan** [pytorch/pytorch#13103]
- PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): Ubuntu 16.04 LTS
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python3.6 setup.py install
 - Python version: 3.6
 - CUDA/cuDNN version: 9.0

I am trying to compile PyTorch for Python 3.6. Since I am using Ubuntu 16 I had to follow [these instructions](https://askubuntu.com/a/865569/262267) to install Python 3.6. After that, when tried to compile PyTorch with Python 3.6 (`python3.6 setup.py install`) I noticed that the paths for `PYTHON_PACKAGES_PATH` and `PYTHON_LIBRARY` are not printed correctly while generating the make files. Here's what is printed:

```
...
--     Python version      : 3.6.7
--     Python executable   : /usr/bin/python3.6
--     Pythonlibs version  : 3.6.7
--     Python library      : /usr/lib/python3.6
--     Python includes     : /usr/include/python3.6m
--     Python site-packages: lib/python3/dist-packages
...
```

However `lib/python3/dist-packages` belongs to Python 3.5 and `/usr/lib/python3.6` does not even exist on my machine. I tried to set these two options manually by changing `tools/build_pytorch_libs.sh` and added the two lines below as lines 252 and 253 in build_pytorch_libs.sh as of [this commit](https://github.com/pytorch/pytorch/tree/6995b84d45c512b570c290e4a9ba6c28a8977a67):

```
-DPYTHON_LIBRARY=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so \
-DPYTHON_PACKAGES_PATH=/usr/local/lib/python3.6/dist-packages \
```

However, during building I noticed that the paths are still incorrect. Then I did `cmake .. -LA` and noticed that the CMakeLists.txt does not even contain options for settings those paths. Here's what `cmake .. -LA` shows for setting Python-related paths:

```
PYTHON_ENUM_SOURCE_DIR:STRING=/pytorch/third_party/python-enum
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.6
PYTHON_LIBRARY_DEBUG:FILEPATH=PYTHON_LIBRARY_DEBUG-NOTFOUND
PYTHON_LIB_REL_PATH:STRING=lib/python3/dist-packages
PYTHON_PEACHPY_SOURCE_DIR:STRING=/pytorch/third_party/python-peachpy
PYTHON_SIX_SOURCE_DIR:STRING=/pytorch/third_party/python-six
```

 Could you please fix this?

**Comment by BIGBALLON** [comment]
Hi, @Amir-Arsalan

you may need to use cmake with
``-DPYTHON_EXECUTABLE``
``-DPYTHON_LIBRARY``
``-DPYTHON_INCLUDE_DIR``

for example , use the following cmd:

```
cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python3.5m \
-DPYTHON_LIBRARY=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5m.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.5m
```

**Comment by Amir-Arsalan** [comment]
@BIGBALLON Have you tried this before? Are you sure just adding `-DPYTHON_EXECUTABLE` will fix the issue?

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/12569
