### ISSUE TITLE
No CUDA runtime is found

### ISSUE THREAD

**Issue by Ly-Lynn** [pytorch/pytorch#131047]
### 🐛 Describe the bug

I am trying to download detectron2 and the setup.py file got bug 
![image](https://github.com/user-attachments/assets/509c3ab2-6caf-4c1a-92d9-81cbd604a823)
I tried running the setup.py file, and this line of code showed problem
![image](https://github.com/user-attachments/assets/1cb2de82-489c-4ecb-891e-0e76238605b1)
why is there CUDA_HOME, but still no CUDA runtime is found? I believe this is the issue.

### Versions

![image](https://github.com/user-attachments/assets/6177de55-f9dc-4f76-be27-680ed28a2543)

cc @seemethere @malfet @osalpekar @atalman @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by seemethere** [comment]
Hello! We don't currently support this version of PyTorch anymore. Does this still occur with the latest version, pytorch 2.3?
