### ISSUE TITLE
torch 2.4 doesn't work with on-demand profiling:  faild with  RuntimeError : Cannot initialize CUDA without ATenA_cuda library. 

### ISSUE THREAD

**Issue by staugust** [pytorch/pytorch#131020]
### 🐛 Describe the bug

Here's the whole output of python process: 

```
INFO:2024-07-18 07:28:12 142935:142935 init.cpp:131] Registering daemon config loader, cpuOnly =  1
INFO:2024-07-18 07:28:12 142935:142935 CuptiActivityProfiler.cpp:233] CUDA versions. CUPTI: 18; Runtime: 12010; Driver: 12010
INFO:2024-07-18 07:28:12 142935:142935 DaemonConfigLoader.cpp:63] Setting communication fabric enabled = 1
INFO:2024-07-18 07:28:12 142935:142938 DaemonConfigLoader.cpp:63] Setting communication fabric enabled = 1
INFO:2024-07-18 07:28:12 142935:142935 IpcFabricConfigClient.cpp:88] Setting up IPC Fabric at endpoint: dynoconfigclient7795b432-5a1e-4773-9e9d-e8e9908d638b status = initialized
INFO:2024-07-18 07:28:12 142935:142935 DaemonConfigLoader.cpp:63] Setting communication fabric enabled = 1
INFO:2024-07-18 07:28:12 142935:142938 DaemonConfigLoader.cpp:63] Setting communication fabric enabled = 1INFO:2024-07-18 07:28:12 142935:142935 DaemonConfigLoader.cpp:27] Reading base config
WARNING:2024-07-18 07:28:12 142935:142935 IpcFabricConfigClient.cpp:147] Missing IPC Fabric implementation for getLibkinetoBaseConfig

/root/miniconda3/envs/torch240/lib/python3.8/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
Collecting environment information...
Traceback (most recent call last):
  File "collect_env.py", line 651, in <module>
    main()
  File "collect_env.py", line 634, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 629, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 489, in get_env_info
    cuda_module_loading=get_cuda_module_loading_config(),
  File "collect_env.py", line 423, in get_cuda_module_loading_config
    torch.cuda.init()
  File "/root/miniconda3/envs/torch240/lib/python3.8/site-packages/torch/cuda/__init__.py", line 281, in init
    _lazy_init()
  File "/root/miniconda3/envs/torch240/lib/python3.8/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.
ERROR:2024-07-18 07:28:17 142935:142938 FabricManager.h:134] Error when sync_send(): Bad file descriptor
ERROR:2024-07-18 07:28:17 142935:142938 IpcFabricConfigClient.cpp:175] Failed to send config type=3 to dyno: IPC sync_send fail
```

Steps to build an environment: 
```sh
conda create -n test python=3.8
pip install https://download.pytorch.org/whl/test/cu121/torch-2.4.0%2Bcu121-cp38-cp38-linux_x86_64.whl 

export KINETO_USE_DAEMON=1
python collect_env.py
```

`collect_env.py` is a copy of https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py 

### Versions

Collecting environment information...
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.8.19 (default, Mar 20 2024, 19:58:24)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.9.151-015.ali3000.alios7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Tesla T4
GPU 1: Tesla T4

Nvidia driver version: 470.82.01
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.9.0
/usr/lib64/libcudnn_adv_infer.so.8.9.0
/usr/lib64/libcudnn_adv_train.so.8.9.0
/usr/lib64/libcudnn_cnn_infer.so.8.9.0
/usr/lib64/libcudnn_cnn_train.so.8.9.0
/usr/lib64/libcudnn_ops_infer.so.8.9.0
/usr/lib64/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                104
On-line CPU(s) list:   0-103
Thread(s) per core:    2
Core(s) per socket:    26
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
Stepping:              7
CPU MHz:               3199.920
CPU max MHz:           3800.0000
CPU min MHz:           1200.0000
BogoMIPS:              5000.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0-103
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single cdp_l3 ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.4.0+cu121
[pip3] triton==3.0.0
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] torch                     2.4.0+cu121              pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi

cc @robieta @chaekit @aaronenyeshi @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise

**Comment by staugust** [comment]
cc @sraikund16  , please add labels for this issue, thanks.

**Comment by briancoutinho** [comment]
Hi @staugust  to fix this error you can add delay to the kineto init using this env var

KINETO_DAEMON_INIT_DELAY_S=3

Let me know if this works. 
I need to update the docs to ask people to use this work around

**Comment by briancoutinho** [comment]
@staugust this should be fine IMo because we are delaying init by sending the init onto a different temporary thread.

PS: updating the doc
https://github.com/facebookincubator/dynolog/pull/272
