### ISSUE TITLE
THD with Gloo and USE_CUDA=OFF is bitrotted

### ISSUE THREAD

**Issue by anderspapitto** [pytorch/pytorch#13101]
note that the call to THDGetCudaState at https://github.com/pytorch/pytorch/blob/master/torch/lib/THD/base/data_channels/GlooCache.hpp#L369 isn't guarded by USE_CUDA. The only reason that works is because somewhere along the line we stopped ever compiling the Gloo bits of THD when USE_CUDA=OFF. This was revealed during work on https://github.com/pytorch/pytorch/pull/12775.

**Comment by soumith** [comment]
i'm going to close this as a `wontfix`, as THD is already deprecated
