### ISSUE TITLE
[inductor] MultiKernel doesn't compose with AOTInductor

### ISSUE THREAD

**Issue by peterbell10** [pytorch/pytorch#131035]
When the aot inductor tests are run with multi kernel enabled, `test_cond_non_tensor_predicates_dynamic_True_abi_compatible_cuda` is failing with the following [error](https://github.com/pytorch/pytorch/actions/runs/9981539355/job/27586877518#step:20:2152):
```
     return V.graph.multi_kernel_to_choice[multi_kernel_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'multi_kernel_0'
```

It looks like the choices are being recorded, but the identity of `V.graph` has changed between `record_choice` and `lookup_choice`, and so the recorded choices aren't available on the second codegen pass.

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @shunting314

**Comment by desertfire** [comment]
Resolved by https://github.com/pytorch/pytorch/pull/142333
