### ISSUE TITLE
Create the pages which explain `torch.nan` and `torch.inf` in the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#131040]
### 📚 The doc issue

I can use `torch.nan` and `torch.inf` as shown below but I cannot find the pages which explain `torch.nan` and `torch.inf` in [the doc](https://pytorch.org/docs/stable/index.html):

```python
import torch

torch.nan, torch.inf
# (nan, inf)
```

### Suggest a potential alternative/fix

So, the pages which explain `torch.nan` and `torch.inf` should be created in the doc.

cc @albanD

**Comment by ezyang** [comment]
They're aliases for math.nan/inf, fwiw

**Comment by DongyuXu77** [comment]
I could help to add the description of two functions in the doc

**Comment by AndrewH72** [comment]
Hi @hyperkai!
I was wondering if I could get this task assigned to me? Thanks!

**Comment by tngshung** [comment]
@hyperkai Hello, does this issue still need to be addressed? If so, can I fix it? Thank you.
