### ISSUE TITLE
[export] Is there a way to set all axes in all inputs to dynamic?

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#131045]
Is there a way to call torch.export.export() and set all axes in all inputs to dynamic, the same we can do with torch._dynamo.export()?

cc @ezyang @anijain2305 @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by angelayi** [comment]
No, as typically specifying which dimension is dynamic should be something the user is actively aware of.

But, if you really want this feature, like in the case where you are building a framework and you don't know which user inputs are dynamic, you could pytree.tree_map_only over all the tensors and construct a `dynamic_shapes` tuple that marks everything as dynamic. However, this might error if there are shapes in the input that are related to other shapes in the input (e.g. some dimensions are equal, or one dimension is a multiple of another dimension). In that case, you can use [`refine_dynamic_shapes_from_suggested_fixes`](https://github.com/pytorch/pytorch/blob/d4a79d4a7c746068d25fe5cf9333495561f4ce1f/torch/export/dynamic_shapes.py#L945) to automatically determine that for you.

**Comment by justinchuby** [comment]
Thanks for your advice. I will try that!

**Comment by justinchuby** [comment]
Implemented in https://github.com/pytorch/pytorch/pull/134976
