### ISSUE TITLE
When tensors/modules are assigned to a device they are assigned to several

### ISSUE THREAD

**Issue by lferraz** [pytorch/pytorch#13119]
## 🐛 Bug

I have 2 GPU. When I send a tensor/module to the device 1 a process is also created in the device 0.

Code to reproduce the error:
import torch
a = torch.FloatTensor(3,3)
d = torch.device('cuda:1')
a.to(d)

The output of nvidia-dmi with the 2 processes
+------------------------------------------------------ -------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                            |
|-------------------------------+----------------------+-------------+
|   0  GeForce GTX TIT...  Off  | 00000000:00:06.0 Off |                  N/A |
+-------------------------------+----------------------+----------+
|   1  GeForce GTX 980 Ti  Off  | 00000000:00:07.0 Off |                  N/A |
+-------------------------------+----------------------+----------+                                                                               
+--------------------------------------------------------------------+
| Processes:                                                                      GPU Memory      |
|  GPU       PID   Type   Process name                             Usage                  |
|=========================== =======================|
|    0     15327      C   /home/luis/anaconda3/bin/python              354MiB |
|    1     15327      C   /home/luis/anaconda3/bin/python              346MiB |
+---------------------------------------------------------------------+

 - PyTorch Version (e.g., 1.0): 0.4.1 and 1.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.6.5
 - CUDA/cuDNN version: 
 - GPU models and configuration: 980 Ti and 1080 Ti
 - Any other relevant information:

**Comment by ezyang** [comment]
Related: #3477

**Comment by leo-mao** [comment]
Similar here.
with GPU configuration:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
| 34%   67C    P0    66W / 250W |    962MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 20%   41C    P8    16W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```
Software configuration installed with *conda*
```
- python=3.6.2
- pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
```
OS:
`Linux 4.15.0-36-generic #39-Ubuntu SMP x86_64 GNU/Linux`

**Comment by zou3519** [comment]
I cannot reproduce this on master. This may be fixed, please feel free to reopen if not.
