### ISSUE TITLE
custom ops don't reinplace when mutated arg is a view of a graph input

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#131192]
```py
import torch
from torch import Tensor # E: invalid syntax  [syntax]

@torch.library.custom_op("mylib::foo", mutates_args={"x"})
def foo(x: Tensor) -> None:
    x.sin_()

@torch.compile(fullgraph=True)
def f(x):
    x0 = x[0]
    foo(x0)

x = torch.randn(2)
f(x)
"""
# produces the following
def call(args):
    arg0_1, = args
    args.clear()
    assert_size_stride(arg0_1, (2, ), (1, ))
    buf0 = empty_strided_cpu((1, ), (1, ), torch.float32)
    cpp_fused_0(arg0_1, buf0)
    # Source Nodes: [], Original ATen: []
    torch.ops.mylib.foo.default(reinterpret_tensor(buf0, (), (), 0))
    cpp_fused_1(buf0, arg0_1)
    del arg0_1
    return ()
"""
```
changing the "foo" to x0.sin_() does lead to inductor reinplacing the code:
```
def call(args):
    arg0_1, = args
    args.clear()
    assert_size_stride(arg0_1, (2, ), (1, ))
    cpp_fused_sin_0(arg0_1, arg0_1)
    del arg0_1
    return ()
```

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @kadeng @muchulee8 @amjames @aakhundov @coconutruben @bdhirsh @ezyang @anijain2305 @yf225 @ColinPeppler @desertfire

**Comment by zou3519** [comment]
We need to pattern match on the functional op followed by a {view}_scatter operation. There might be more cases for view + mutation

**Comment by laithsakka** [comment]
This paste the more complicated versions where actually two views access two different distinct portions of the tensor
https://www.internalfb.com/phabricator/paste/view/P1485541137

**Comment by ezyang** [comment]
@yf225 since we are allowing limited amounts of mutation, this might be a good use case for that capability as well.

**Comment by laithsakka** [comment]
I will start looking at this sometime this week, I think as a start I will try to support basic subscript [x] views. and build on top of that.

**Comment by leslie-fang-intel** [comment]
Attached another case we met in vLLM: https://gist.github.com/leslie-fang-intel/d62da8d11192e0565ad3e3739f1bdd19#file-test_failed-py

**Comment by laithsakka** [comment]
this is resolved

**Comment by laithsakka** [comment]
@leslie-fang-intel  to use the functionalization you need the flag TORCHDYNAMO_AUTO_FUNCTIONALIZED_V2
and be on top of https://github.com/pytorch/pytorch/pull/135141 for inference

**Comment by zou3519** [comment]
@laithsakka , let's keep this open until we flip the config flag for this to be on by default

**Comment by laithsakka** [comment]
shipped
