### ISSUE TITLE
UserWarning: ONNX export failed on RNN/GRU/LSTM because batch_first not supported warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")

### ISSUE THREAD

**Issue by wangyunxiaa** [pytorch/pytorch#13110]
Hello,
 I want to convert a pre-trained  pytorch model to onnx,but when i do the convert,
`torch.onnx.export(lang_model, (dummy_input1, dummy_input2), "lmmodel.onnx", verbose=True, input_names=input_names, output_names=output_names)`
I have an error about LSTM layer:
`Traceback (most recent call last): File "torch2onnx.py", line 82,  in <module> torch.onnx.export(lang_model, (dummy_input1,  dummy_input2), "lmmodel.onnx", verbose=True, input_names=input_names,  output_names=output_names) File  "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/torch/onnx/__init__.py",  line 27, in export return utils.export(*args, **kwargs) File  "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/torch/onnx/utils.py",  line 104, in export operator_export_type=operator_export_type) File  "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/torch/onnx/utils.py",  line 286, in _export proto, export_map = graph.export(params,  _onnx_opset_version, defer_weight_export, operator_export_type)  RuntimeError: ONNX export failed: Couldn't export operator aten::lstm`
The LSTM layer is set batch_first=True when do training stage, does onnx  support the layer of LSTM, what should i do to support it? 
Thanks~

**Comment by wyessen** [comment]
Bump? Has been more than six months, I'm now hitting this issue too.

**Comment by wyessen** [comment]
Ok, this should probably be closed. The latest dev version does not have that issue.

**Comment by basque21** [comment]
I'm having this problem also... any solution apart from retraining with `batch_first = False` ?

**Comment by wyessen** [comment]
> I'm having this problem also... any solution apart from retraining with `batch_first = False` ?

@basque21 Update to the latest version - pull and compile.

**Comment by RyanHuangNLP** [comment]
@wyessen Does pytorch 1.2.0 not fix this issue?
