### ISSUE TITLE
Question about cuda grad

### ISSUE THREAD

**Issue by nchuCV** [pytorch/pytorch#13113]
`import torch
a = torch.tensor([1.,2.,3.],requires_grad = True)
a = a.cuda()
b = a** 2
c = b.mean(0
c.backward()
print(a.grad)
`
None
why 'a.grad' print 'None'?
but,
`import torch
a = torch.tensor([1.,2.,3.])
a = a.cuda()
a.requires_grad = True
b = a** 2
c = b.mean(0
c.backward()
print(a.grad)`
tensor([0.6667,1.3333,2.0000],device = 'cuda:0')

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
