### ISSUE TITLE
why grad is disappear when put data to cuda?

### ISSUE THREAD

**Issue by ericyan71** [pytorch/pytorch#13112]
hello, I write a simple small test to test grad, I found a strange behavor, in test1, I use Tensor in cpu, then I can get grad, but if I put them to gpu, the grad is gone, here is my test code:

```python
import torch
device = torch.device('cuda')
    
def test1():
    a = torch.tensor([1,2,3], dtype=torch.float32, requires_grad=True)
    b = a**2
    c = torch.mean(b)
    c.backward()
    print(a.grad)
```
`the result is: tensor([0.6667, 1.3333, 2.0000])`

```python    
def test2():
    a = torch.tensor([1,2,3], dtype=torch.float32, requires_grad=True).to(device)
    b = a**2
    c = torch.mean(b)
    c.backward()
    print(a.grad)
```
`the result is : None`

I don't understand why they are different, thanks.

**Comment by albanD** [comment]
Hi,

Please use the [forum](https://discuss.pytorch.org/) to ask questions. Github issues are for bug or new features only.

Your question has been answered [here](https://discuss.pytorch.org/t/strange-behavior-of-variable-cuda-and-variable-grad/1642). `Variable`s don't exist anymore, but it is exactly the same problem.
