### ISSUE TITLE
[caffe2] Improve build_android experience

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#13116]
## 🚀 Feature

It would be nice to make it easier to build android libraries for caffe2.

## Motivation

I recently built the AICamera example with recent android studio. The result and steps are here:

https://github.com/t-vi/AICamera/

## Pitch

Based on the feedback I got on the first day after mentioning this on the PyTorch slack, there are more people who have been trying this and had less success, even though I'd think they're pretty good with PyTorch in general.

- To facilitate android x86 building, add a switch to disable AVX independent of detection.
  (Or make it work on android, but I guess android x86 is debugging mostly anyway.)
- Make the build output path include the architecture.
- Default to clang to adapt to what android seems to be doing toolchain-wise.
- Add some instructions to build and copy the libs + includes.

## Alternatives

- Keep it a secret black art and find a business model helping people on a case by case basis.
- Build libtorch for android and use that.

## Additional context

The other changes in my fork might be the basis for a PR for the AICamera repo and an update to the tutorial once this is merged.

Needless to say, I would submit the PR.

**Comment by rivergold** [comment]
+1

**Comment by t-vi** [comment]
It also works on linux/bash if you put it all on one line, not sure why your OSX doesn't like it.

**Comment by 425172555** [comment]
Please tell me why
Building protoc
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/tcl/pytorch/build_host_protoc/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_7ec42/fast"
    /usr/bin/make -f CMakeFiles/cmTC_7ec42.dir/build.make CMakeFiles/cmTC_7ec42.dir/build
    make[1]: 进入目录“/home/tcl/pytorch/build_host_protoc/build/CMakeFiles/CMakeTmp”
    Building C object CMakeFiles/cmTC_7ec42.dir/testCCompiler.c.o
    /usr/bin/cc   -fembed-bitcode    -o CMakeFiles/cmTC_7ec42.dir/testCCompiler.c.o   -c /home/tcl/pytorch/build_host_protoc/build/CMakeFiles/CMakeTmp/testCCompiler.c
    cc: error: unrecognized command line option ‘-fembed-bitcode’
    CMakeFiles/cmTC_7ec42.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_7ec42.dir/testCCompiler.c.o' failed
    make[1]: *** [CMakeFiles/cmTC_7ec42.dir/testCCompiler.c.o] Error 1
    make[1]: 离开目录“/home/tcl/pytorch/build_host_protoc/build/CMakeFiles/CMakeTmp”
    Makefile:126: recipe for target 'cmTC_7ec42/fast' failed
    make: *** [cmTC_7ec42/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)


-- Configuring incomplete, errors occurred!
See also "/home/tcl/pytorch/build_host_protoc/build/CMakeFiles/CMakeOutput.log".
See also "/home/tcl/pytorch/build_host_protoc/build/CMakeFiles/CMakeError.log".

**Comment by soumith** [comment]
Fixed on master via @ljk53 's PRs
