### ISSUE TITLE
Support for Tensor.repeat() operator in onnx

### ISSUE THREAD

**Issue by tomahawk810** [pytorch/pytorch#13127]
## 🚀 Feature

It seems that Tensor.repeat() is not in the list of operators supported by the ONNX exporter.
It would be great to add it.

## Motivation

I use TensorboardX to visualize models' computational graphs. It uses the ONNX exporter and I can't visualize the graphs of models using Tensor.repeat().

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by garymm** [comment]
Should be fixed by #43430 or maybe even earlier.
