### ISSUE TITLE
Failing to export ONNX when `GroupNorm` input shape = 2

### ISSUE THREAD

**Issue by martintmv-git** [pytorch/pytorch#131279]
### 🐛 Describe the bug

When the Group Normalization (GN) layer is applied to two-dimensional inputs, the export2ONNX function fails, resulting in an error. Is this expected behaviour or a bug?

To reproduce the issue:

```
import torch
import torch.nn as nn

class GNModel(nn.Module):
    def __init__(self):
        super(GNModel, self).__init__()
        num_groups = 8
        num_channels = 32
        self.gn = nn.GroupNorm(num_groups=num_groups, num_channels=num_channels)

    def forward(self, x):
        x = self.gn(x)
        return x 

model = GNModel()
x = torch.randn(256, 32)

torch.onnx.export(
    model, x, 'gn_model.onnx',
    input_names=['input'],
    output_names=['output'],
)
```

Traceback (most recent call last):
  File "/home/tmv/miniforge/lib/python3.11/site-packages/torch/onnx/symbolic_opset9.py", line 6018, in group_norm
    mul(g, norm, symbolic_helper._unsqueeze_helper(g, weight, axes)),
  File "/home/tmv/miniforge/lib/python3.11/site-packages/torch/onnx/symbolic_helper.py", line 844, in _unsqueeze_helper
    if _is_constant(axes_i[0]):
IndexError: list index out of range

### Question
Does the input tensor `x` with a shape of `(256, 32)` match the expected shape for `GroupNorm`, or it expects at least three dimensions (e.g., for 2D inputs: `(batch_size, num_channels, height, width)`)? If yes, should I just reshape `x` to have an extra dimension?

### Versions

- PyTorch version: 2.1.0+cu117
- Is debug build: False
- CUDA version used for PyTorch: 11.7
- ROCM used to build PyTorch: N/A

**Comment by justinchuby** [comment]
You can use 

```diff
 torch.onnx.export(
+    model, (x,), 'gn_model.onnx',
     input_names=['input'],
     output_names=['output'],
+    dynamo=True
 )
```

to leverage the new dynamo export path.
