### ISSUE TITLE
RuntimeError: The size of tensor a (8) must match the size of tensor b (2744) at non-singleton dimension 1

### ISSUE THREAD

**Issue by Amir9663** [pytorch/pytorch#131297]
Hello everybody,

I have this error in the line:
("embeddings = x + self.position_embeddings"):
Error:
RuntimeError: The size of tensor a (8) must match the size of tensor b (2744) at non-singleton dimension 1

Can anyone help me fix it? Thanks in advance.

Snippet code:
class Channel_Embeddings(nn.Module):
    """Construct the embeddings from patch, position embeddings."""
    def __init__(self, config, patchsize, img_size, in_channels):
        super().__init__()
        img_size = (img_size, img_size, img_size)  # Assuming img_size is scalar, for 3D, it should be a tuple
        patch_size = (patchsize, patchsize, patchsize)
        n_patches = (img_size[0] // patch_size[0]) * (img_size[1] // patch_size[1]) * (img_size[2] // patch_size[2])

        self.patch_embeddings = nn.Conv3d(in_channels=in_channels,
                                          out_channels=in_channels,
                                          kernel_size=1,
                                          stride=patch_size)
        self.position_embeddings = nn.Parameter(torch.zeros(1, n_patches, in_channels))
        self.dropout = Dropout(config.transformer["embeddings_dropout_rate"])

    def forward(self, x):
        if x is None:
            return None
        x = self.patch_embeddings(x)  # (B, hidden, D', H', W')
        x = x.flatten(2)  # (B, hidden, D'*H'*W')
        x = x.transpose(-1, -2)  # (B, n_patches, hidden)
        embeddings = x + self.position_embeddings
        embeddings = self.dropout(embeddings)
        return embeddings

**Comment by tringwald** [comment]
This issue tracker is for bug reports and feature requests only. Please use the [discussion board](https://discuss.pytorch.org/) for general questions.
