### ISSUE TITLE
size of DTensor

### ISSUE THREAD

**Issue by kaiyuyue** [pytorch/pytorch#131342]
```python
# torchrun --standalone --nnodes=1 --nproc-per-node=4 {THIS SCRIPT}.py

import os
import torch
import torch.distributed as dist
from torch.distributed._tensor import init_device_mesh, Shard, distribute_tensor

mesh = init_device_mesh("cuda", (int(os.environ["WORLD_SIZE"]),))
xx = torch.randn(100000, 88)
xd = distribute_tensor(xx, mesh, [Shard(dim=0)])

if dist.get_rank() == 0:
    print(torch.__version__)
print("rank:", dist.get_rank(), xx.shape, xd.shape, xd._local_tensor.shape)
```

The output is
```bash
2.3.1  # torch.__version__
rank: 0 torch.Size([100000, 88]) torch.Size([100000, 88]) torch.Size([25000, 88])
rank: 1 torch.Size([100000, 88]) torch.Size([100000, 88]) torch.Size([25000, 88])
rank: 2 torch.Size([100000, 88]) torch.Size([100000, 88]) torch.Size([25000, 88])
rank: 3 torch.Size([100000, 88]) torch.Size([100000, 88]) torch.Size([25000, 88])
```

I am not sure this is a bug or not. But after sharding the tensor `xx` to the DTensor `xd`, the naive torch.Size of `xd` is still the same as before. 

Now if I want to get the real size of `xd`, I need to get the `_local_tensor` out of DTensor Wrapper. 

If I miss sth. important, please correct me because I think that the `DTensor.shape` should be intuitive and directly output the size of `__local_tensor`. 

### Versions

```python
torch.__version__ = 2.3.1
```

**Comment by awgu** [comment]
This is expected/by design. `DTensor.shape` or `DTensor.size()` will return the global shape (without sharding), and like you said, you can check `DTensor.to_local().shape` for the physical local shape.

@wanchaol can add more here, but I think the reason `DTensor.shape` returns the global shape is because it is supposed to allow you to program multiple devices (in a device mesh) as if you are programming a single device (like GSPMD).

**Comment by kaiyuyue** [comment]
Thanks very much. It makes sense. So it is about `global_shape` and `local_shape` of the DTensor. 

When I first checked the my implementation with fsdp, I thought my sharding didn't work out due to the incorrect expected size. Then figured it out by looking at the source code. So hope it would be helpful to have a section on shape in the `torch.distributed._tensor` readme. Thanks.
