### ISSUE TITLE
How to create a custom op which can be compile by dynamo inductor?

### ISSUE THREAD

**Issue by MoFHeka** [pytorch/pytorch#131313]
### 📚 The doc issue

https://pytorch.org/tutorials/advanced/cpp_extension.html

### Suggest a potential alternative/fix

A descriptive explanation and a simple example are required.

cc @svekars @brycebortree @ezyang @anijain2305 @chauhang @penguinwu

**Comment by malfet** [comment]
Have you considered creating an issue against tutorials page. Short answer: it must be decomposable in python to other ops

**Comment by desertfire** [comment]
@zou3519

**Comment by zou3519** [comment]
See https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html#custom-ops-landing-page
