### ISSUE TITLE
torch._dynamo.list_backends does not list entrypoint-defined backends

### ISSUE THREAD

**Issue by tehbone** [pytorch/pytorch#131360]
### 🐛 Describe the bug

torch.compile backends that are registered via entrypoints are not listed in `torch._dynamo.list_backends` until they have been looked up via an explicit call `torch._dynamo.lookup_backend()` or implicitly through use in `torch.compile()`.

### Versions

All Pytorch releases including 2.3.

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by desertfire** [comment]
@anijain2305
