### ISSUE TITLE
split CI jobs to reduce latency

### ISSUE THREAD

**Issue by anderspapitto** [pytorch/pytorch#13139]
we had this set up for jenkins, but we lost it while moving to CircleCI. We had jobs split in half. I'd like to see us go even more granular, maybe targeting 20 minute chunks.

see related code at https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/test.sh#L174-L183

cc @yf225

**Comment by zou3519** [comment]
Closing due to age.
