### ISSUE TITLE
Unexpected Behavior with torch.mean and torch.sum on Empty Dimensions

### ISSUE THREAD

**Issue by xnming** [pytorch/pytorch#131457]
**Description:**

Given an `N`-dimensional tensor `T`, if one of its dimensions (say `i`) has a size of 0, applying `torch.mean` or `torch.sum` over dimension `i` returns a tensor with size 1 on dimension `i`. 

**Example:**

```python
import torch

T = torch.empty(3, 0, 4)
result_mean = torch.mean(T, dim=1, keepdim=True)
result_sum = torch.sum(T, dim=1, keepdim=True)

print(result_mean.shape)  # Expected: torch.Size([3, 0, 4]), Actual: torch.Size([3, 1, 4]) and filled with NaN
print(result_sum.shape)   # Expected: torch.Size([3, 0, 4]), Actual: torch.Size([3, 1, 4]) and filled with 0
```

**Issue:**

Is this the expected behavior for these functions? It might be more intuitive if the output tensor retained the same shape as the input tensor when the dimension being reduced has size 0.

**Proposed Change:**

Consider modifying `torch.mean` and `torch.sum` to return a tensor with the same shape as the input tensor when the reduction dimension has size 0.

### Versions

PyTorch version: 2.3.0a0+git63d5e92
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-6.5.0-44-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla K40c
GPU 1: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 470.256.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

**Comment by albanD** [comment]
> Is this the expected behavior for these functions?

Yes I think it is the expected behavior. Reduction function always return one element for the dimension being reduced over.

**Comment by xnming** [comment]
> > Is this the expected behavior for these functions?
> 
> Yes I think it is the expected behavior. Reduction function always return one element for the dimension being reduced over.

I see. Thank you for your reply.
