### ISSUE TITLE
Use conda official channel's MKL-DNN?

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#13153]
The official version channel's `conda install mkl-dnn` seems to work, but the README suggests `conda install -c mingfeima mkldnn`. Should it be changed?

**Comment by vadimkantorov** [comment]
Is mkl-dnn needed as a binary package at this point?

It seems that `ideep` submodule includes `mkl-dnn` as source, so maybe it's compiled from source anyway?

**Comment by soumith** [comment]
no longer relevant

**Comment by vadimkantorov** [comment]
@soumith why no longer relevant? the mingfeima's channel is still in official README. is the conda's mkl-dnn a bad build?
