### ISSUE TITLE
torch.compile F.max_pool2d backwards segfault

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#131659]
@bdhirsh and I minimized the repro in https://github.com/pytorch/pytorch/issues/100075 to this.
```py
import torch
torch.use_deterministic_algorithms(True)

# torch.manual_seed(42)
device = 'cpu'

x = torch.randn(10, 3, 224, 224, device=device, requires_grad=True)

def compute_grad(x): # E: Function is missing a type annotation  [no-untyped-def]
    loss = torch.nn.functional.max_pool2d(x, kernel_size=3, stride=2, padding=1).sum()
    return torch.autograd.grad(loss, x)

result, = compute_grad(x)
compile32, = torch.compile(compute_grad, backend="aot_eager_decomp_partition")(x)
assert torch.allclose(compile32, result)
```
This segfaults with backend=aot_eager_decomp_partition but does not segfault with backend=inductor.

Our best hypothesis is that `_low_memory_max_pool2d_offsets_to_indices`'s implementation is wrong. https://github.com/pytorch/pytorch/blob/4c7f22dee25649cd895bc382192d29f39e482215/torch/_inductor/inductor_prims.py#L121-L124

In particular, the int8 input has negative values, which we then convert to an int64 tensor with negative values, which then gets passed in as the indices for max_pool2d_backward, which likely causes the segfault. 

The implementation of _low_memory_max_pool2d_offsets_to_indices is probably not supposd to be tensor.to because it has a non-trivial lowering: https://github.com/pytorch/pytorch/blob/4c7f22dee25649cd895bc382192d29f39e482215/torch/_inductor/lowering.py#L3787

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by zou3519** [comment]
@amjames @eellison do you have thoughts?

**Comment by eellison** [comment]
Not sure why cpu is segfaulting - we should probably skip decomp in this case anyway. On cuda we do get a mismatch:

```
Mismatched elements: 238148 / 1505280 (15.8%)
Greatest absolute difference: 4.0 at index (0, 0, 1, 3) (up to 1e-05 allowed)
Greatest relative difference: 1.0 at index (0, 0, 0, 131) (up to 0.0001 allowed)
```

cc - @amjames are you able to look into this?

**Comment by isuruf** [comment]
aten implementations for both  `_low_memory_max_pool2d_with_offsets` and `_low_memory_max_pool2d_offsets_to_indices` are wrong. I can send a PR to fix them, but as @eellison said, it's better to skip the decomposition.

**Comment by eellison** [comment]
```
import torch
device = 'cuda'

with torch._dynamo.utils.preserve_rng_state():
    x = torch.randn(10, 3, 224, 224, device=device, requires_grad=True)

with torch._dynamo.utils.preserve_rng_state():
    y = torch.randn(10, 3, 224, 224, device=device, requires_grad=True)


def compute_grad(x): # E: Function is missing a type annotation  [no-untyped-def]
    loss = torch.nn.functional.max_pool2d(x, kernel_size=3, stride=2, padding=1).sum()
    return torch.autograd.grad(loss, x)

y = x.clone()
result, = compute_grad(y)
compile32, = torch.compile(compute_grad)(x)
assert torch.allclose(compile32, result)
```

cc @isuruf - also failing with torch.compile

**Comment by isuruf** [comment]
@eellison, that snippet works fine for me.

**Comment by eellison** [comment]
yea, nevermind, works for me too, had some local changes

**Comment by isuruf** [comment]
With https://github.com/pytorch/pytorch/pull/131717, the original segfault is not there, but the assert still fails.

**Comment by isuruf** [comment]
Had a bug in #131717. The assert now passes with #131717.

**Comment by isuruf** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/131717
