### ISSUE TITLE
[inductor][cpu] QAT performance regression in 2024-07-20 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#131664]
### 🐛 Describe the bug

QAT performance regression

</head>

model_name | qat_new | qat_old | qat   ratio(new/old)
-- | -- | -- | --
densenet121-eval_throughput | 1106.510585 | 2197.991088 | 0.5
mnasnet1_0-eval_throughput | 878.0463009 | 14132.7193 | 0.06
mobilenet_v2-eval_throughput | 1094.392304 | 11398.63801 | 0.1
mobilenet_v3_large-eval_throughput | 1119.224976 | 12323.26414 | 0.09
resnet152-eval_throughput | 453.1583943 | 1246.244283 | 0.36
resnet18-eval_throughput | 2362.056259 | 7637.353512 | 0.31
resnet50-eval_throughput | 880.6299685 | 3229.824709 | 0.27
resnext50_32x4d-eval_throughput | 780.6061791 | 2649.804747 | 0.29
shufflenet_v2_x1_0-eval_throughput | 1724.044718 | 10193.92094 | 0.17

</body>

### Versions

  <p></p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Branch</th>
      <th>Target commit</th>
      <th>Refer commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>nightly</td>
      <td>571ca81</td>
      <td>c02ee0c</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>chuanqiw/inductor_quant</td>
      <td>ee35d764</td>
      <td>ee35d764</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>nightly</td>
      <td>69b2a0a</td>
      <td>69b2a0a</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>nightly</td>
      <td>b0ebddc</td>
      <td>b0ebddc</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>nightly</td>
      <td>d23a6e1</td>
      <td>d23a6e1</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>nightly</td>
      <td>11bb5b8</td>
      <td>11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>fea73cb</td>
      <td>fea73cb</td>
    </tr>
  </tbody>

</table>

Repro:
```
git clone -b chuanqiw/inductor_quant https://github.com/pytorch/benchmark.git
cd benchmark
pip install --no-deps -r requirements.txt
pip install --no-cache Jinja2==3.1.2 markupsafe==2.0.1 beartype==0.15.0 && pip install mpmath==1.3.0
python install.py --continue_on_fail
export LD_PRELOAD=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib/libiomp5.so:${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib/libjemalloc.so
export MALLOC_CONF="oversize_threshold:1,background_thread:true,metadata_thp:auto,dirty_decay_ms:-1,muzzy_decay_ms:-1"
#QAT
TORCHINDUCTOR_FREEZING=1 python run_benchmark.py cpu -m resnet50 --torchdynamo inductor --quantize --is_qat --launcher --launcher-args="--throughput-mode" -b 128 --metrics throughputs
mv .userbenchmark/cpu qat
cat qat/metric* # to see the results
```

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/27ded035455000f7e677cec7dd701cf1c0660418
[torchbench-resnet50-qat-performance-drop_guilty_commit.log](https://github.com/user-attachments/files/16364478/torchbench-resnet50-qat-performance-drop_guilty_commit.log)

cc @ezyang @chauhang @penguinwu @WeizhuoZhang-intel @chuanqi129

**Comment by leslie-fang-intel** [comment]
https://github.com/pytorch/pytorch/pull/131651 should fix this issue. Let's wait for the landing of this PR.

**Comment by zxd1997066** [comment]
The issue is fixed in the latest report.
