### ISSUE TITLE
Segmentation fault (core dumped) in C++ API for centos

### ISSUE THREAD

**Issue by joy-yjl** [pytorch/pytorch#13163]
When I use C++ API do "auto out_tensor = module->forward(inputs).toTensor();"
there is "Segmentation fault (core dumped)"

but when I use python API do the same thing .It is successful.
when I use C++ API in Ubuntu . It is successful.

I use C++ API in centos. It is unsuccessful.

**Comment by fmassa** [comment]
I think your GCC version is < 4.9 in Centos, which is ABI-incompatible with PyTorch, see https://github.com/pytorch/pytorch/issues/6987

Could you try updating your GCC to be 4.9 or higher, following instructions from https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6 for example?

**Comment by joy-yjl** [comment]
> 我认为你的GCC版本在Centos中是<4.9，与PyTorch不兼容，见[＃6987](https://github.com/pytorch/pytorch/issues/6987)
> 
> 您可以按照[https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6的](https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6)说明尝试将GCC更新为4.9或更高版本吗？

You solved my problem, thank you!
