### ISSUE TITLE
[freezing][fuse_conv_bn][inductor-cpu] fuse_conv_bn is not triggered with inlining of inbuilt modules

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#131693]
### 🐛 Describe the bug

Repro

~~~
torch._dynamo.config.inline_inbuilt_nn_modules=False
taskset -c 0-47 python benchmarks/dynamo/torchbench.py --inference --performance --amp -dcpu -n50 --only mobilenet_v2 --dynamic-shapes --dynamic-batch-only --freezing --timeout 9000 --inductor
~~~

~~~
torch._dynamo.config.inline_inbuilt_nn_modules=True
taskset -c 0-47 python benchmarks/dynamo/torchbench.py --inference --performance --amp -dcpu -n50 --only mobilenet_v2 --dynamic-shapes --dynamic-batch-only --freezing --timeout 9000 --inductor
~~~

On my machine, the speedup goes from 2.4x to 0.7x. This is because the `fuse_conv_bn` pass does not pattern match for torch.conv2d + F.batch_norm. It currently assumes that Conv2D will always be a nn.Module. With inlining of inbuilt nn modules, this assumption is no longer true. 

Skipping mobilenet_v2 for now - https://github.com/pytorch/pytorch/pull/131694

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire 

cc @ezyang @chauhang @penguinwu

**Comment by anijain2305** [comment]
cc @eellison @mlazos

**Comment by leslie-fang-intel** [comment]
Hi @anijain2305, will take a look of this issue soon.

**Comment by jiayisunx** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/133968.
