### ISSUE TITLE
HUD link test command is wrong

### ISSUE THREAD

**Issue by andrewor14** [pytorch/pytorch#131657]
If I click the link icon on the HUD page:

<img width="231" alt="Screenshot 2024-07-24 at 11 12 01 AM" src="https://github.com/user-attachments/assets/8bd51aa7-82b8-4235-9a43-d2f75c82db35">

I get the wrong test command:
```
python test_modules.py.py -k test_modules.py::TestModuleCPU::test_save_load_nn_BatchNorm1d_train_mode_cpu_float32
```

The right command should be:
```
python test_modules.py -k TestModuleCPU.test_save_load_nn_BatchNorm1d_train_mode_cpu_float32
```

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by andrewor14** [comment]
cc @clee2000

**Comment by clee2000** [comment]
Is it ok if I switch it to pytest instead?
