### ISSUE TITLE
No PyTorch Build Distribution for Intel Macs (OSX64) in Latest Release

### ISSUE THREAD

**Issue by scott-huberty** [pytorch/pytorch#131766]
### 🐛 Describe the bug

It appears that a build distribution for Intel Macs (OSX64) hasn't been released for PyTorch 2.4 yet ([PyPI](https://pypi.org/project/torch/#files), [Conda](https://anaconda.org/pytorch/pytorch))

You can confirm this by running the following on an Intel Mac:

```bash
pip install torch==2.4
```

or 

```bash
conda install pytorch==2.4
```

Which results in:
 
```
ERROR: Could not find a version that satisfies the requirement torch==2.4 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.4
```

Does PyTorch plan to release a build distribution for intel macs, or will only ARM64 be supported moving forward?

### Versions

N/A

**Comment by malfet** [comment]
Yes, this is expected, see https://dev-discuss.pytorch.org/t/pytorch-macos-x86-builds-deprecation-starting-january-2024/1690 and release notes for https://github.com/pytorch/pytorch/releases/tag/v2.2.0

There are no plans to continue automated builds for x86 Macs, but one should be able to build PyTorch from source on those machines, and if it does not work, please do not hesitate to submit a PR or at least create an issue highlighting the compilation problems
