### ISSUE TITLE
`._scatter(...)` gives different results in CPU vs GPU environment

### ISSUE THREAD

**Issue by XinweiHe** [pytorch/pytorch#131740]
### 🐛 Describe the bug

```
(Pdb) y
tensor([[ 0, -1],
        [ 0, -1],
        [ 1, -1],
        [-1, -1],
        [ 0,  1]])
(Pdb) one_hot = torch.zeros(5, 3, device=y.device, dtype=torch.float)
(Pdb) one_hot
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
 (Pdb) valid_mask
tensor([[ True, False],
        [ True, False],
        [ True, False],
        [False, False],
        [ True,  True]])
(Pdb) 
one_hot.scatter_(1, y * valid_mask, valid_mask.float())
```
In GPU environment, we have
```
(Pdb)             one_hot.scatter_(1, y * valid_mask, valid_mask.float())
tensor([[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.],
        [1., 1., 0.]])
```

In CPU environment, we have
```
(Pdb)             one_hot.scatter_(1, y * valid_mask, valid_mask.float())
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.],
        [1., 1., 0.]])
```

### Versions

This is the CPU environment.

Collecting environment information...
PyTorch version: 2.3.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-1031-aws-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 535.183.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         2499.994
BogoMIPS:                        4999.98
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        8 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] mypy-boto3-s3==1.34.65
[pip3] numpy==1.23.5
[pip3] pytorch_frame==0.2.3
[pip3] pytorch-lightning==2.2.1
[pip3] torch==2.3.0+cpu
[pip3] torch-geometric==2.6.0
[pip3] torch_scatter==2.1.2+pt23cpu
[pip3] torchdata==0.7.0
[pip3] torchmetrics==1.3.2
[pip3] torchtext==0.18.0
[pip3] triton==2.3.0
[conda] No relevant packages

cc @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by alex-jw-brooks** [comment]
I was able to reproduce the issue. Are you planning to contribute a fix for this @XinweiHe? if you aren't, I'd be happy to try 😄

**Comment by XinweiHe** [comment]
@alex-jw-brooks  I do not have the bandwidth for this at the moment. If you have time for help, that would be great!

**Comment by alex-jw-brooks** [comment]
Great! I'll take a look then 😄

**Comment by mingfeima** [comment]
@yanbing-j please help debug this one!

**Comment by XinweiHe** [comment]
By the way, I end up bypassing this error by replacing `_scatter` with `scatter_add_`.

**Comment by yanbing-j** [comment]
@XinweiHe This is similar with https://github.com/pytorch/pytorch/issues/114085, which is explained in https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_.html#torch.Tensor.scatter_. The index in your reproducer is not unique, the behavior is non-deterministic. It depends on which value from src is picked. The inconsistency in torch.Tensor.scatter between CPU and GPU is expected.

You can use `scatter_reduce` or `scatter_add` instead.

**Comment by yanbing-j** [comment]
Will close this issue, because the inconsistency in torch.Tensor.scatter between CPU and GPU is expected.
