### ISSUE TITLE
The CPU Only option has disappeared from the command in the Windows > PiP package.

### ISSUE THREAD

**Issue by cpprhtn** [pytorch/pytorch#131731]
### 📚 The doc issue

Where is the `--index-url https://download.pytorch.org/whl/cpu ` command in the Stable (2.4.0) > Windows > Pip > Pyhton > CPU path?

The cpu version of torch does not go back to the command 'pip3 install torchvision torchchaudio' created now.

### Suggest a potential alternative/fix

recommand prefix:
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu`

**Comment by malfet** [comment]
Not sure what's the ask here? Are you not getting CPU 2.4.0 version when running `pip3 install torch` on Windows?

**Comment by cpprhtn** [comment]
It is difficult to reproduce the log at the time by finding it on the computer of other team members of the company.

However, when installing pytorch, the installation targeting cpu had to be specified with --index-url https://download.pytorch.org/whl/cpu to be solved.

referenced the Windows > cpu install command on that [link.](https://pytorch.org/get-started/previous-versions/)

**Comment by cpprhtn** [comment]
I just got some .dll file error in the cpu version (which doesn't have much data when I googling) and it was successful when I put the --index option in a few attempts.


I must have mistaken something. Thank you for your answer.
@malfet  and @atalman 

I will close this issue.
