### ISSUE TITLE
Adaptive max pool2d backward cuda does not have deterministic implementation. 

### ISSUE THREAD

**Issue by zeobec** [pytorch/pytorch#131746]
### 🚀 The feature, motivation and pitch

![IMG_3420](https://github.com/user-attachments/assets/9f17a948-460e-43dd-bef8-1f2c137e57b5)
during training YOLOv8 with attention module, CBAM,  i received this warning during the training. can anyone help me with this

**Comment by janeyx99** [comment]
Looks to be a duplicate of https://github.com/pytorch/pytorch/issues/131972

**Comment by zeobec** [comment]
> Looks to be a duplicate of #131972

Thanks for the response! However, seems like I am a bit lost about the solution.

**Comment by janeyx99** [comment]
There’s no current solution yet—but we should consolidate discussion in one place!
