### ISSUE TITLE
write a better test that checks that cuda is lazy-loaded

### ISSUE THREAD

**Issue by anderspapitto** [pytorch/pytorch#13180]
currently if you break this functionality, the only CI error that you get is that `make html` breaks in the one configuration that tests the documentation build

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @ngimel

**Comment by yf225** [comment]
Note to self: add a `Build with CUDA -> Test on CPU machine` CI configuration.

**Comment by zou3519** [comment]
Maybe we have something like this now? cc @malfet @seemethere

**Comment by malfet** [comment]
Yes, we have _on CPI test, that run GPU binaries on cpu only hosts
