### ISSUE TITLE
MPS backend breaking on llama 3.1 8B on Macbook M3

### ISSUE THREAD

**Issue by yliapis** [pytorch/pytorch#131865]
### 🐛 Describe the bug

python code being run under the hood:

```python

_TORCH_DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using torch device: {_TORCH_DEVICE}")


@functools.cache
def _build_llama_pipeline():
    pipeline = transformers.pipeline(
        "text-generation",
        model="meta-llama/Meta-Llama-3.1-8B-Instruct",
        device=_TORCH_DEVICE,
    )
    return pipeline

...
messages = [
        {"role": "system", "content": prompt},
    ]
pipe = _build_llama_pipeline()
result = pipe(messages, max_new_tokens=200)
```

I am getting the following error:
```bash
/AppleInternal/Library/BuildRoots/d615290d-668b-11ee-9734-0697ca55970a/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:761: failed assertion `[MPSNDArray initWithDevice:descriptor:] Error: total bytes of NDArray > 2**32'
```

This is a device issue, the same code runs fine on the cpu. I am installing torch via `poetry add 'transformers[torch]'`

Related issues I've found on this topic (without a clear solution):
https://github.com/pytorch/pytorch/issues/78247
https://github.com/pytorch/pytorch/issues/78492

### Versions

Collecting environment information...
PyTorch version: 2.4.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.4 (main, Jul 13 2024, 01:18:59) [Clang 15.0.0 (clang-1500.1.0.2.5)] (64-bit runtime)
Python platform: macOS-14.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] mypy==1.11.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==2.0.1
[pip3] torch==2.4.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by jhavukainen** [comment]
Hi @yliapis! Thanks for reporting this! The 2**32 byte limitation is currently a hard set limitation on MPSNDArray side and currently we should try to circumvent this on the PyTorch backend side by checking if the computation truly needs to happen with a  > 2**32 byte array and if so, tile it into smaller subarrays. For that to happen I would need a code snippet I am able to run as is to reproduce the error and follow the stack the which op is causing this.

@yliapis would you be able to extend the code snippet a little bit so that it can be run by anyone to reproduce the error you are seeing? Currently it's missing some parts.

**Comment by malfet** [comment]
> Hi @yliapis! Thanks for reporting this! The `2**32` byte limitation is currently a hard set limitation on MPSNDArray side and currently we should try to circumvent this on the PyTorch backend side by checking if the computation truly needs to happen with a > `2**32` byte array and if so, tile it into smaller subarrays. For that to happen I would need a code snippet I am able to run as is to reproduce the error and follow the stack the which op is causing this.

Hmm, I thought this is no longer the case in Ventura, i.e. I can allocate 4+Gb array and we even test it in CI, see https://github.com/pytorch/pytorch/blob/9440a4824dee84ddbdd56437e4f022bbbe0eaa6f/test/test_mps.py#L7153-L7160

**Comment by kulinseth** [comment]
@malfet , this is not to do with 4GB allocation issue, but rather operation on Large tensors which require indexing beyond 4GB boundaries in the kernel.

**Comment by jhavukainen** [comment]
Yeah sorry my bad on not being explicit in the initial message. Indeed it is the feature of MPS kernel indexing taking happening in 32-bits.

Once I get a permission to look at the licensed model I'll check if we could tile the problematic computation into pieces that are not going over the indexing limit.

**Comment by yliapis** [comment]
> Hi @yliapis! Thanks for reporting this! The `2**32` byte limitation is currently a hard set limitation on MPSNDArray side and currently we should try to circumvent this on the PyTorch backend side by checking if the computation truly needs to happen with a > `2**32` byte array and if so, tile it into smaller subarrays. For that to happen I would need a code snippet I am able to run as is to reproduce the error and follow the stack the which op is causing this.
> 
> @yliapis would you be able to extend the code snippet a little bit so that it can be run by anyone to reproduce the error you are seeing? Currently it's missing some parts.

@jhavukainen the prompt contains PII, so I'd rather not share, but I can say that this prompt that caused the issue was about 95k characters long. I did not get the same error testing with a prompt around 100 characters.

I put together the following script that reproduces the error on my machine with no external dependencies outside of transformers and torch:

```python
import torch
import transformers

if not torch.backends.mps.is_available():
    raise RuntimeError(
        "Please enable MPS on your machine. See https://pytorch.org/docs/stable/backends.html#torch-multiprocessing-mp"
    )
_TORCH_DEVICE = "mps"

pipeline = transformers.pipeline(
    "text-generation",
    model="meta-llama/Meta-Llama-3.1-8B-Instruct",
    device=_TORCH_DEVICE,
)

needle = "needle"
hay = "hay"  # 3 + 1 chars per element

target_num_tokens_approximate = 20_000
haystack = [hay] * target_num_tokens_approximate
test_index = 42
haystack[test_index] = needle
haystack_list = list(haystack)
prompt = f"""
Please return the index of the needle in the haystack as an integer.
Return only the integer number index.
<BEGIN HAYSTACK>
{" ".join(haystack_list)}
<END HAYSTACK>
"""

messages = [
    {"role": "system", "content": prompt},
]
result = pipeline(
    messages,
    max_new_tokens=200,
)
messages = result[0]["generated_text"]
completion = messages[-1]["content"]

print("successful inference")
print(f"completion: {completion}")
print(f"test_index: {test_index}")

```

**Comment by jhavukainen** [comment]
@yliapis Totally understandable. Thanks for the stand alone repro script that should be all we need to nail this down. However I still need to wait for people higher up to sign agreements before I can load the LLaMA v3.1 8B weights. But once they do I'll get to fixing this.

**Comment by jhavukainen** [comment]
Ok I have the model to look at. From the trace I can see that the offending operation is batch matmul and here's a minimal repro case for the issue using the shapes encountered in the script posted by @yliapis:

`import torch
device='mps'
a = torch.randn([32, 20064, 128], dtype=torch.float32,device=device)
b = torch.randn([32, 128, 20064], dtype=torch.float32, device=device)
res = torch.bmm(a, b)
`
I'll start looking what can be done about the op.

**Comment by jhavukainen** [comment]
Ok I can confirm that I'm able to run the model without issues after adding a workaround that breaks the batch matmul above into smaller batches that are able to run within the MPS boundaries. I'll need to do some more cleanup to make it slightly more optimal but I aim to get a PR up for it tomorrow.

**Comment by jhavukainen** [comment]
@yliapis  I started PR #133430 that should solve the issue you are seeing by splitting up the problematic batch matmul to a more manageable size. With this change I am able to run the code snippet you provided to reproduce the error and get a reasonable looking printout of 

```
successful inference
completion: To find the index of the needle in the haystack, we can use the `index()` method in Python. However, this method returns the index of the first occurrence of the specified value. If the needle is not found, it raises a `ValueError`.

Here is a Python function to find the index of the needle in the haystack:

```python
def find_needle(haystack):
    """
    Find the index of the needle in the haystack.

    Args:
    haystack (str): The string to search in.

    Returns:
    int: The index of the needle if found, -1 otherwise.
    """
    try:
        # Use the index() method to find the index of the needle
        index = haystack.index('needle')
        return index
    except ValueError:
        # If the needle is not found, return -1
        return -1

haystack = """
hay hay hay hay hay hay hay hay hay hay hay hay hay hay hay hay hay hay
test_index: 42
```

Feel free to try out the PR if you are building pytorch locally, and let us know if solves the issue. Or you can wait for us to get the change reviewed and merged and try out the nightly release once it has landed. I'll update here once the change lands and is available in a nightly wheel.
