### ISSUE TITLE
UNSTABLE inductor-rocm / rocm6.1-py3.8-inductor / test (inductor)

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#131823]
Failing on trunk
https://github.com/pytorch/pytorch/actions/runs/10088296623/job/27894443775

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by naromero77amd** [comment]
Inductor-rocm jobs are running fine at the moment. Closing this stale issue.
