### ISSUE TITLE
[FSDP2] root moduel parameters keeps unsharded after forward before backward

### ISSUE THREAD

**Issue by weifengpy** [pytorch/pytorch#131965]
### 📚 The doc issue

this question comes up from torchtune. after forward before backward, root module parameters are unsharded. want to confirm if this is by design. I know it's performant to keep root unsharded because they will be used in backward immeidately. but want to confirm

TLDR repo
```
loss = model(inp).sum()
assert not isinstance(model.tok_embeddings.weight, DTensor)
loss.backward()
assert isinstance(model.tok_embeddings.weight, DTensor)
```

full repro
```
import logging
import os
from typing import Callable, Optional, Tuple

import torch
import torch.distributed as dist
import torch.nn as nn
from torch.distributed.fsdp.wrap import ModuleWrapPolicy
from torch.distributed.checkpoint import state_dict as ptd_state_dict
from torch.distributed._composable.fsdp import fully_shard
from torch.testing._internal.distributed._tensor.common_dtensor import (
    ModelArgs,
    Transformer,
    TransformerBlock,
)
import pdb
import sys
from torch.distributed._tensor import DTensor


def main():
    dist.init_process_group(backend="nccl")
    gpu_id = int(os.environ["LOCAL_RANK"])
    device = f"cuda:{gpu_id}"
    torch.cuda.set_device(device)
    torch.manual_seed(0)
    vocab_size = 1024
    max_seq_len = 64
    model_args = ModelArgs(
        n_layers=3,
        n_heads=4,
        vocab_size=vocab_size,
        max_seq_len=max_seq_len,
        dropout_p=0,
    )
    model = Transformer(model_args)
    for layer in model.layers:
        fully_shard(layer)
    fully_shard(model)
    inp = torch.randint(
        low=0,
        high=vocab_size,
        size=(2, max_seq_len),
        device="cuda",
    )
    loss = model(inp).sum()
    assert not isinstance(model.tok_embeddings.weight, DTensor)
    loss.backward()
    assert isinstance(model.tok_embeddings.weight, DTensor)
    

if __name__ == "__main__":
    main()
```

**Comment by awgu** [comment]
This is by design.

**Comment by awgu** [comment]
If people find this kind of implicit behavior confusing, we could put the burden on the user to pass `reshard_after_forward=False` to the root module. I would be okay with that.

For now, the user can call `root_module.reshard()` if they want to shard the root module after forward.

**Comment by weifengpy** [comment]
> If people find this kind of implicit behavior confusing, we could put the burden on the user to pass `reshard_after_forward=False` to the root module. I would be okay with that.
> 
> For now, the user can call `root_module.reshard()` if they want to shard the root module after forward.

thanks. confirmed with torchtune that they only ask this for understanding purpose
