### ISSUE TITLE
[inductor-cpu] Support dynamic shapes for test test_quantized_linear_amx

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#131929]
Repro

```
pytest -vs test/inductor/test_cpu_select_algorithm.py::TestSelectAlgorithmDynamicShapesCPU::test_quantized_linear_amx_dynamic_shapes_batch_size_16_in_features_4_out_features_64_bias_True_cpu
```

This test fails with `torch._dynamo.config.inline_inbuilt_nn_modules=True`

I debugged and found that `use_cpp_packed_gemm_template` returns False here because of 

![image](https://github.com/user-attachments/assets/ac5ec982-4744-49f7-abff-caf93fa8ccda)

I think for k, we can probably check if either k1 or k2 are integers and just use the either integer as k. 

I am skipping the test for now to land the inlining flag.

UPDATE - I added a couple of more skip in https://github.com/pytorch/pytorch/pull/131948  and I think its because of the same reason as above

```
pytest test/inductor/test_cpu_select_algorithm.py::TestSelectAlgorithmDynamicShapesCPU::test_quantized_linear_with_pointwise_dynamic_shapes_batch_size_32_in_features_128_out_features_64_bias_False_input_3d_True_epilogue_relu_cpu_float32
```

cc @ezyang @chauhang @penguinwu

**Comment by anijain2305** [comment]
cc @jgong5 @leslie-fang-intel

**Comment by leslie-fang-intel** [comment]
Hi @anijain2305, the behavior that we generate k1 as symbolic size after turning on `inline_inbuilt_nn_modules` looks strange to me.
Shouldn't we add the guard in dynamo that `k1 equals to k2`. And since k2 is the size of weight in linear, it should be a constant and we should specialize the `k1 == k2 == some contant`?

**Comment by jgong5** [comment]
@anijain2305 I wonder why k1 is symbolic while k2 is static with module inlining while both of them are static without. Is there any issue in the upper stack of the code?

**Comment by leslie-fang-intel** [comment]
> @anijain2305 I wonder why k1 is symbolic while k2 is static with module inlining while both of them are static without. Is there any issue in the upper stack of the code?

Replied and discuss in https://github.com/pytorch/pytorch/pull/131968#issuecomment-2254956135

**Comment by anijain2305** [comment]
Looking into it. Give me a few hours.

**Comment by anijain2305** [comment]
This is happening because quantization introduces module buffers and `dynamic` flag makes `buffers` dynamic. This was not seen in `bfloat16` because there are no `buffers` in bfloat16 case, only parameters, which are considered static for the `dynamic` flag. Looking more into how to bridge the gap.

**Comment by anijain2305** [comment]
https://github.com/pytorch/pytorch/pull/132098 should help here. Need more testing though.

**Comment by leslie-fang-intel** [comment]
Thanks @anijain2305, I am going to close https://github.com/pytorch/pytorch/pull/131968 then.

**Comment by leslie-fang-intel** [comment]
Close it as corresponding PR landed.
