### ISSUE TITLE
Non-deterministic behavior in pytorch even with seeds set

### ISSUE THREAD

**Issue by altosaar** [pytorch/pytorch#13197]
## To Reproduce

1. `git clone https://github.com/altosaar/pytorch-non-determinism`
2. `cd pytorch-non-determinisim`
3. `python test_moons.py`

I get similar non-deterministic output on cpu (mac, linux) and gpu (tesla p100, linux):

```
$ python test_moons.py 
step: 0	loss: inf
	valid_loss: nan
Traceback ...

$ python test_moons.py 
step: 0	loss: 2.04
	valid_loss: 2.0884687901
Traceback (most recent call last):
```

## Expected behavior

Deterministic behavior. I set numpy and torch seeds, and the cudnn options mentioned at https://pytorch.org/docs/master/notes/randomness.html

## Environment

```
$ python collect_env.py
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Springdale Linux release 7.5 (Verona)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 410.48
cuDNN version: Probably one of the following:
/usr/local/cudnn/cuda-9.2/7.1.4/lib64/libcudnn.so.7.1.4

Versions of relevant libraries:
[pip] numpy (1.14.6)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py36_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch
```

**Comment by abaisero** [comment]
I can't speak about achieving determinism on GPU, but on CPU you also have to ensure that only one thread is being used, to avoid the accumulation of numerical errors resulting from performing the same operations in a slightly different order.  You can use `torch.set_num_threads(1)` for this.

**Comment by altosaar** [comment]
Thanks @abaisero and @t-vi - installing the nightly build fixes the determinism issue.

It seems like the issue was in 0.4.1 (the CUDA seeding couldn't have been the problem because it is non-deterministic on 0.4.1 on cpu and gpu).

**Comment by altosaar** [comment]
Reopening this–I misspoke. The issue still happens (I just didn't test it enough). Still getting nans sometimes; whereas most of the time the code works.

Confirmed the bug is still there on the latest pytorch, `1.0.0.dev20181118`.

Any ideas on how to debug this?

**Comment by altosaar** [comment]
Figured it out–classic mistake of using torch.Tensor instead of torch.zeros :)

**Comment by shreyassaxena** [comment]
Hi @altosaar 
I am also struggling with something similar, can you elaborate a bit more about the classic mistake: of using torch.Tensor vs torch.zeros. I am not sure why one would give you NaN's in the middle of your run.

**Comment by altosaar** [comment]
@shreyassaxena - if you use torch.Tensor it is instantiated from memory locations that may not be zero. torch.zeros explicitly sets the memory to zero.
