### ISSUE TITLE
[Inductor] CPU perf test needs to be updated

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#132097]
Previously, CPU Inductor perf test on CI instances were done without VecISA specified. https://github.com/pytorch/pytorch/pull/131812 fixed that, but that also means some of the existing perf smoke tests need to updated, see https://github.com/pytorch/pytorch/blob/8fe2bf212dc5e01b15cbe728958f940873230d64/.ci/pytorch/test.sh#L715 .

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames

**Comment by chuanqi129** [comment]
Hi @zxd1997066 please help to follow it
