### ISSUE TITLE
MultiLabelSoftMarginLoss Documentation Error?

### ISSUE THREAD

**Issue by varunagrawal** [pytorch/pytorch#1320]
In the documentation for the `MutliLabelSoftMarginLoss` criterion, the equation is given as
```
loss(x, y) = - sum_i (y[i] log( exp(x[i]) / (1 + exp(x[i])))
                      + (1-y[i]) log(1/(1+exp(x[i])))) / x:nElement()
```

But as per the implementation, the criterion is calling the `binary_cross_entropy` criterion after applying the sigmoid function to the input which would result in:

```
loss(x, y) = - sum_i ( y[i] * log(1 / 1+exp(-x[i])) 
                       + (1-y[i]) * log(exp(-x[i]) / 1 + exp(-x)) )
```

Should I go ahead and correct this?

**Comment by soumith** [comment]
yes. Please go ahead and correct this, and thanks for spotting it :)
