### ISSUE TITLE
Memory Efficient Attention on ROCm results in image corruption on the diffusers SD3 pipeline

### ISSUE THREAD

**Issue by owainkenwayucl** [pytorch/pytorch#132004]
### 🐛 Describe the bug

_(I'm happy to report this over on the diffusers repo, but I suspect it's actually a bug in the ROCm build of Pytorch 2.4.0 as you will see)_

Since Pytorch 2.4.0, I found that the HuggingFace Diffusers Stable Diffusion 3 pipeline was producing corrupted images on AMD accelerators I had access to (a weird grid pattern over the first image, followed by gibberish for subsequent images.

Example code:

```python
import torch
from diffusers import StableDiffusion3Pipeline

pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers",torch_dtype=torch.float16)
pipe = pipe.to("cuda")

generator = torch.Generator("cuda")
generator.manual_seed(123456)

image1 = pipe(
    "A cat holding a sign that says hello world",
    negative_prompt="",
    num_inference_steps=32,
    guidance_scale=7.0,
    generator=generator
).images[0]
image2 = pipe(
    "A cat holding a sign that says hello world",
    negative_prompt="",
    num_inference_steps=32,
    guidance_scale=7.0,
    generator=generator
).images[0]
image1
```
![pt24_1](https://github.com/user-attachments/assets/6c6f3ae9-b178-4894-88f4-72b88b0472b0)

```python
image2
```

![pt24_2](https://github.com/user-attachments/assets/23d01c0a-898c-4ce6-bbe0-f1b16a696507)

Generating further images from the pipeline generates more gibberish.  I have reproduced this on AMD Mi300x, AMD Mi250 and AMD Mi210.

On experimentation I have determined that this is due to the addition of memory efficient attention in the ROCm build of PyTorch 2.4.0 because disabling this `torch.backends.cuda.enable_mem_efficient_sdp(False)` produces "correct" images.

![pt24_1_nomemeffatt](https://github.com/user-attachments/assets/7d427829-6850-4170-a323-4c480f73f646)
![pt24_2_nomemeffatt](https://github.com/user-attachments/assets/93fab7a9-8f10-4cdb-8f17-c3267abf3f4b)

This problem **does not** occur on:

1. Pytorch 2.3.1 for ROCm (which does not have memory efficient attention compiled in, as per the warning it prints).
2. Pytorch 2.4.0 on Nvidia GPUs (tested A100)

### Versions

On the Mi250 box (I no longer have access to the Mi300x system, which was running AlmaLinux 9.4 with the latest install of ROCm 6):

```
Collecting environment information...
PyTorch version: 2.4.0+rocm6.0
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 6.0.32830-d62f6a171

OS: Rocky Linux release 8.9 (Green Obsidian) (x86_64)
GCC version: (GCC) 15.0.0 20240724 (experimental)
Clang version: Could not collect
CMake version: version 3.26.5
Libc version: glibc-2.28

Python version: 3.11.7 (main, Jan 16 2024, 03:27:23) [GCC 10.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-513.24.1.el8_9.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI250X/MI250 (gfx90a:sramecc+:xnack-)
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 6.0.32830
MIOpen runtime version: 3.0.0
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  1
Core(s) per socket:  64
Socket(s):           2
NUMA node(s):        8
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               1
Model name:          AMD EPYC 7763 64-Core Processor
Stepping:            1
CPU MHz:             2450.000
CPU max MHz:         3529.0520
CPU min MHz:         1500.0000
BogoMIPS:            4900.05
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-15
NUMA node1 CPU(s):   16-31
NUMA node2 CPU(s):   32-47
NUMA node3 CPU(s):   48-63
NUMA node4 CPU(s):   64-79
NUMA node5 CPU(s):   80-95
NUMA node6 CPU(s):   96-111
NUMA node7 CPU(s):   112-127
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin brs arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] pytorch-triton-rocm==3.0.0
[pip3] torch==2.4.0+rocm6.0
[pip3] torchaudio==2.4.0+rocm6.0
[pip3] torchvision==0.19.0+rocm6.0
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by janeyx99** [comment]
cc @drisspg

**Comment by drisspg** [comment]
@jeffdaily

**Comment by jithunnair-amd** [comment]
@drisspg @janeyx99 We are actively looking into this issue. We will try to see if we can get this fixed in Pyorch 2.4.1

**Comment by xinyazhang** [comment]
@owainkenwayucl as a temporary workaround, can you disable the memory efficient attention and use flash attention for these workloads? On MI200/300 they are calling the same GPU kernel (which means the root cause of this problem is in the memory efficient backend the kernel is invoked incorrectly).

**Comment by xinyazhang** [comment]
@owainkenwayucl  okay the root cause is located, see the related PR for the fix.

**Comment by owainkenwayucl** [comment]
Sure - thanks :)

**Comment by jithunnair-amd** [comment]
I'm reopening this so the user can confirm if the issue is fixed when pytorch2.4.1 wheels are released

**Comment by FurkanGozukara** [comment]
there is also huge speed difference between windows vs linux when training FLUX with identical setup on identical GPU

https://github.com/pytorch/pytorch/issues/131958#issuecomment-2313963735

**Comment by jithunnair-amd** [comment]
I was able to verify that ROCm2.4.1 final RC wheels work as expected with the testcase in this issue.
`pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/test/rocm6.1`

image1.jpg:
![image1](https://github.com/user-attachments/assets/472a07fd-62f6-4d5f-9472-14a9234933f0)

image2.jpg:
![image2](https://github.com/user-attachments/assets/954f99e0-8d6c-4f97-a1c8-df5e13525724)

**Comment by owainkenwayucl** [comment]
Sorry, I'm trying to test this but amd_smi is installed in a weird way on the cluster I'm testing on and I'm struggling to get it to work (it's now required by PyTorch 2.4.1).

**Comment by owainkenwayucl** [comment]
(see my comment here https://github.com/ROCm/amdsmi/issues/50#issuecomment-2331131165)

**Comment by owainkenwayucl** [comment]
Ok, I've fixed the amd_smi issue and confirm that with Pytorch 2.4.1 the issue I reported here is fixed. So closing.

Thanks for fixing this so quickly, everyone!
