### ISSUE TITLE
All-reduce followed by division does not correctly divide data

### ISSUE THREAD

**Issue by Edenzzzz** [pytorch/pytorch#132027]
### 🐛 Describe the bug

When sharing weights between two layer of a model (such as tying input and output embeddings in a transformer model), an all-reduce sum followed by averaging by world_size doesn't average the weights. Dividing the .data works.
For example, you can run the following script:
```
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import os
def init_process_group(rank=0, world_size=1):
    dist.init_process_group(backend='nccl', rank=rank, world_size=world_size)

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList(torch.nn.Linear(1, 1, bias=False) for _ in range(2))
        # init with ones 
        for layer in self.layers:
            torch.nn.init.ones_(layer.weight)
        self.layers[0].weight = self.layers[-1].weight
        
def run_test(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'  # or the IP of the master node
    os.environ['MASTER_PORT'] = '8125'       # make sure this port is free
    init_process_group(rank, world_size)
    torch.manual_seed(rank)
    model = Model().to(f"cuda:{rank}")
    
    if dist.get_rank() == 0:
        print(f"Before all-reduce:")
    dist.barrier()
    for idx, layer in enumerate(model.layers):
        print(f"Rank: {rank}, Layer: {idx}, Weight: {layer.weight.item()}, data_ptr: {layer.weight.data_ptr()}")
    
    # all reduce weights
    for name, param in model.named_parameters():
        dist.all_reduce(param, op=dist.ReduceOp.SUM)
        # NOTE: dividing .data works correctly
        # param.data = param.data / world_size
        param = param / world_size
        print(name, param.item(), param.data_ptr())
        
    if dist.get_rank() == 0:
        print(f"After all-reduce:")
    dist.barrier()
    for idx, layer in enumerate(model.layers):
        print(f"Rank: {rank}, Layer: {idx}, Weight: {layer.weight.item()}, data_ptr: {layer.weight.data_ptr()}")

if __name__ == "__main__":
    world_size = 2
    mp.spawn(run_test, args=(world_size,), nprocs=world_size, join=True)
```

### Versions

PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.19 (main, May  6 2024, 19:43:03)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-144-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H800
GPU 1: NVIDIA H800
GPU 2: NVIDIA H800
GPU 3: NVIDIA H800
GPU 4: NVIDIA H800
GPU 5: NVIDIA H800
GPU 6: NVIDIA H800
GPU 7: NVIDIA H800

Nvidia driver version: 550.54.15
cuDNN version: Probably one of the following:
/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   52 bits physical, 57 bits virtual
CPU(s):                          192
On-line CPU(s) list:             0-191
Thread(s) per core:              2
Core(s) per socket:              48
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           143
Model name:                      Intel(R) Xeon(R) Platinum 8468
Stepping:                        8
CPU MHz:                         803.531
CPU max MHz:                     3800.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4200.00
Virtualization:                  VT-x
L1d cache:                       4.5 MiB
L1i cache:                       3 MiB
L2 cache:                        192 MiB
L3 cache:                        210 MiB
NUMA node0 CPU(s):               0-47,96-143
NUMA node1 CPU(s):               48-95,144-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid cldemote movdiri movdir64b md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] galore-torch==1.0
[pip3] numpy==1.25.2
[pip3] pytorch-lightning==1.6.5
[pip3] tensorboard-pytorch==0.7.1
[pip3] torch==2.1.1
[pip3] torch-tb-profiler==0.4.3
[pip3] torchaudio==2.1.1
[pip3] torchmetrics==1.4.0.post0
[pip3] torchvision==0.16.1
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] galore-torch              1.0                      pypi_0    pypi
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.8            py39h5eee18b_0  
[conda] mkl_random                1.2.4            py39hdb19cb5_0  
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] numpy-base                1.26.4           py39hb5e798b_0  
[conda] pytorch                   2.1.1           py3.9_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-lightning         1.6.5                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] tensorboard-pytorch       0.7.1                    pypi_0    pypi
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchaudio                2.1.1                py39_cu121    pytorch
[conda] torchmetrics              1.4.0.post0              pypi_0    pypi
[conda] torchtriton               2.1.0                      py39    pytorch
[conda] torchvision               0.16.1               py39_cu121    pytorch
[conda] triton                    2.2.0                    pypi_0    pypi

**Comment by awgu** [comment]
`param = param / world_size` creates a new tensor object for the left-hand-side `param` compared to the right-hand side `param`, but this new left-hand-side `param` is never registered back to the module.

In other words, you are doing something like `new_param = param / world_size` but then throwing away the result of `new_param`.

**Comment by Edenzzzz** [comment]
Oh can't believe I missed this. Closing now
