### ISSUE TITLE
Fix the rest of pyi annotations in torch/_C/_distributed_c10d.pyi

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#132054]
### 🐛 Describe the bug

Example fix PR for NCCL: https://github.com/pytorch/pytorch/pull/130957

Update the annotations by going to torch/csrc/distributed/c10d/init.cpp finding the binding for the class in question and making sure they match. If the property is read write, there is no need to do separate @property annotations, just represent it as a plain field. At minimum ProcessGroupGloo.Options needs to be updated, but there may be others.

I am happy to review PRs that fix this, tag me on them.

### Versions

main

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @malfet @xuzhao9 @gramster

**Comment by ishon19** [comment]
Hey @ezyang, thanks and linked the PR above to fix the issue, please let me know if you've got any feedback! :)
