### ISSUE TITLE
torch.nn.utils.rnn.pack_padded_sequence not working in multi-GPU environments

### ISSUE THREAD

**Issue by sailordiary** [pytorch/pytorch#13214]
## 🐛 Bug

torch.nn.utils.rnn.pack_padded_sequence not working properly

## To Reproduce

```
    # lens is a Python list which contains the lengths of each sample in decreasing order
    def forward(self, x, lens):
        x_lens = torch.tensor(lens, dtype=torch.int64, device=torch.device('cpu'))
        print (x_lens, x_lens.size(), x_lens.type())
        x_packed = torch.nn.utils.rnn.pack_padded_sequence(x, x_lens, batch_first=True)
        out, _ = self.lstm(x_packed)
        out = torch.nn.utils.rnn.pad_packed_sequence(out, batch_first=True)
        out = self.fc(out)

        return out
```

## Expected behavior

Above is an excerpt from a longer program, which upon running gives the error message "'lengths' argument should be a 1D CPU int64 tensor" ([link](https://github.com/pytorch/pytorch/blob/4d62eef505770f1c866fa2205a5a05ab47865dda/aten/src/ATen/native/PackedSequence.cpp#L9) to source).

However, when I print the tensor, it clearly shows up as a torch.LongTensor on the CPU. As you can see, I have tried everything I can to ensure that this is the case, but the problem persists. Does this have anything with the recent C++ porting?

Here is the output:

```
 tensor([228, 228, 214, 212, 209, 208, 207, 203, 202, 200, 198, 197, 187, 187,
        182, 178, 175, 175, 174, 173, 173, 172, 169, 167, 162, 161, 161, 160,
        158, 157, 157, 157, 156, 155, 154, 152, 152, 152, 151, 151, 151, 150,
        149, 149, 148, 147, 146, 145, 145, 145, 141, 140, 140, 140, 138, 137,
        136, 135, 134, 134, 134, 134, 132, 131, 130, 130, 129, 129, 128, 128,
        127, 125, 123, 123, 122, 121, 121, 120, 120, 118, 117, 116, 116, 110,
        110, 106, 104, 102, 100, 100,  97,  97,  96,  95,  92,  91,  87,  85,
         82,  82], device='cpu') torch.Size([100]) torch.LongTensor
Traceback (most recent call last):
  File "main_CTC.py", line 320, in <module>
    main()
  ... (_omitted_)
  File "/home/sailordiary/tools/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call
__
    result = self.forward(*input, **kwargs)
  File "/home/sailordiary/code/******/ctc.py", line 174, in forward
    x = self.lstm(x, x_lens)
  File "/home/sailordiary/tools/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call
__
    result = self.forward(*input, **kwargs)
  File "/home/sailordiary/code/******/ctc.py", line 121, in forward
    x_packed = torch.nn.utils.rnn.pack_padded_sequence(x, x_lens, batch_first=True)
  File "/home/sailordiary/tools/anaconda3/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 148, in pack_padded
_sequence
    return PackedSequence(torch._C._VariableFunctions._pack_padded_sequence(input, lengths, batch_first))
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor
```

## Environment

PyTorch version: 1.0.0.dev20181027
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.3.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 384.130
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda80                    1.0                  h205658b_0    pytorch
[conda] magma-cuda80              2.3.0                         1    pytorch
[conda] pytorch-ignite            0.1.0                     <pip>
[conda] pytorch-nightly           1.0.0.dev20181027 py3.6_cuda8.0.61_cudnn7.1.2_0  [cuda80]  pytorch
[conda] torchfile                 0.1.0                     <pip>

## Additional context

None.

**Comment by zou3519** [comment]
We tried and couldn't reproduce this. Could you give us a smaller snippet that would help us get to this error message?

**Comment by sailordiary** [comment]
@zou3519 After trying to create a MWE, I think I found the cause of the problem.
```
# Run this program with CUDA_VISIBLE_DEVICES=0,1
class LSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers):
        super(LSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, bidirectional=True)

    def forward(self, x, lens):
        self.lstm.flatten_parameters()
        lens = torch.tensor(lens, dtype=torch.int64, device=torch.device('cpu'))
        x = torch.nn.utils.rnn.pack_padded_sequence(x, lens, batch_first=True)
        out, _ = self.lstm(x)
        out = torch.nn.utils.rnn.pad_packed_sequence(out, batch_first=True)

        return out


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.lstm = LSTM(512, 512, 3)

    def forward(self, x, x_lens):
        x = self.lstm(x, x_lens)
        return x

def train(model):
    inputs = torch.randn(64, 245, 512).cuda() # (B, T, C)
    lens = list(range(64, 0, -1))
    outputs = model(inputs, lens)
    
model = Net()
model = nn.DataParallel(model)
model = model.cuda()
train(model)
```
This time, after simplification, it gives a very illuminating error message:
> RuntimeError: Expected `len(lengths)` to be equal to batch_size, but got 64 (batch_size=32)

I had incorrectly assumed that the `lens` parameter will be automatically distributed but apparently it won't. I also tried inputting a CPU LongTensor outside the model definition (i. e. `lens = torch.LongTensor(list(range(64, 0, -1)))`) but it doesn't work either. What should I do to make this work in a multi-GPU environment?

P. S. It is still not clear why my original program displays a different message (RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor), though. The gists of the programs are indentical. I will let you know if I do find out.

**Comment by soumith** [comment]
@sailordiary you should use nn.DistributedDataParallel for such cases, much cleaner and more efficient. See https://pytorch.org/docs/stable/distributed.html#launch-utility for how to use that instead of DataParallel

**Comment by jeffquach** [comment]
@soumith I followed the instructions in the link you provided above using @sailordiary 's script and I am still getting the same error message

```
Traceback (most recent call last):
  File "slerp.py", line 40, in <module>
    train(model)
  File "slerp.py", line 34, in train
    outputs = model(inputs, lens)
  File "/home/jeff/.pyenv/versions/pytorch_tut/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jeff/.pyenv/versions/pytorch_tut/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 216, in forward
    outputs = self.parallel_apply(self._module_copies[:len(inputs)], inputs, kwargs)
  File "/home/jeff/.pyenv/versions/pytorch_tut/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 223, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/jeff/.pyenv/versions/pytorch_tut/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "/home/jeff/.pyenv/versions/pytorch_tut/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "/home/jeff/.pyenv/versions/pytorch_tut/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "slerp.py", line 28, in forward
    x = self.lstm(x, x_lens)
  File "/home/jeff/.pyenv/versions/pytorch_tut/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "slerp.py", line 15, in forward
    x = torch.nn.utils.rnn.pack_padded_sequence(x, lens, batch_first=True)
  File "/home/jeff/.pyenv/versions/pytorch_tut/lib/python3.6/site-packages/torch/onnx/__init__.py", line 57, in wrapper
    return fn(*args, **kwargs)
  File "/home/jeff/.pyenv/versions/pytorch_tut/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 124, in pack_padded_sequence
    data, batch_sizes = PackPadded.apply(input, lengths, batch_first)
  File "/home/jeff/.pyenv/versions/pytorch_tut/lib/python3.6/site-packages/torch/nn/_functions/packing.py", line 25, in forward
    "{} (batch_size={}).".format(len(lengths), batch_size))
ValueError: Expected `len(lengths)` to be equal to batch_size, but got 64 (batch_size=32).
```

I modified these lines:

```
model = Net()
torch.distributed.init_process_group(backend="nccl")
model = model.cuda()
model = nn.parallel.DistributedDataParallel(model)
train(model)
```

This is the command I ran:

`python -m torch.distributed.launch slerp.py --nproc_per_node=2`

Is there something that I am doing wrong?

**Comment by ngimel** [comment]
You need to pass 'device_ids` argument when you are wrapping your model in `DistributedDataParallel` so that each process is using only one GPU, as described in @soumith's link (Important notices, item 4).

**Comment by sailordiary** [comment]
@jeffquach I think the idea is to do DistributedParallel with 1 GPU per process at a reduced batch size, so that the inputs needn't be split anymore.

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org. Yes, DistributedDataParallel is supposed to speed up training, please post an example where it does not on the forums.

**Comment by sailordiary** [comment]
Closing this issue for now.

**Comment by aurooj** [comment]
> @ngimel @sailordiary Thanks for the tips, I got it working! I'm just wondering, isn't DistributedDataParallel supposed to cut down training time when I use it? I did a quick bench mark using 2 GPUs vs 1 and the training time was about the same. I am using a GTX 1070 TI and a GTX 1070

@jeffquach Can you share your working code if possible, so that we could see how the code structure looks like?

**Comment by duhaijun** [comment]
@jeffquach l got the same problem and l solved it. The problem may be you do not make all inputs to gpu!!! 
For example, if G(image, caption, length), the inputs of image ,caption and length all need to gpu.
hope it can help you

**Comment by dimalik** [comment]
Might not be the cleanest approach but you could compute the sequence lengths within the `train` function (untested but should work)

``` python
lengths = []
for elem in x:
    lengths.append(np.count_nonzero(elem.detach().cpu(), axis=0))

torch.nn.utils.rnn.pack_padded_sequence(x, lengths, batch_first=True)
```
