### ISSUE TITLE
[CUDA][Inductor][Pooling] `test_comprehensive_nn_functional_max_pool2d_cuda` appears broken on H100

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#132199]
### 🐛 Describe the bug

`python test/inductor/test_torchinductor_opinfo.py -k TestInductorOpInfoCUDA.test_comprehensive_nn_functional_max_pool2d_cuda` on sm90 (H100)
Visible after #129106 which seems to be introducing some additional tests. Fails on sm90, but not sm80/sm86. Since the reference kernel is unchanged between the two (IIUC it would be implemented in `DilatedMaxPool2d.cu`), could this be a codegen failure?

### Versions

visible after #129106

cc @ptrblck @msaroufim @mikaylagawarecki @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

CC @nWEIdia @tinglvv

**Comment by isuruf** [comment]
Same as https://github.com/pytorch/pytorch/issues/131072 ?

**Comment by eqy** [comment]
Sorry, closing as dupe, completely forgot about the previous issue thanks @isuruf
