### ISSUE TITLE
 GPL-3.0 license detected in a third_party file

### ISSUE THREAD

**Issue by tcnguyen** [pytorch/pytorch#132151]
## Issue description

Our scanner has detected the GPL-3.0 in a file used by torch on this path: 

`third_party/kineto/libkineto/third_party/dynolog/third_party/cpr/test/LICENSE. `

From reviewing this internally, it seems that the GPL-3.0 is incompatible with the BSD-3 license that applies to torch as a whole; our compliance standards do not allow us to use GPL licenses in this manner. Could you consider removing the file if it is not used?

Torch version: 2.2.2

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @robieta @chaekit @aaronenyeshi @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise

**Comment by Aidyn-A** [comment]
According to https://github.com/libcpr/cpr/pull/648:

> [Mongoose](https://github.com/cesanta/mongoose) is provided under [GPLv2](https://github.com/cesanta/mongoose/blob/master/LICENSE) and is only consumed (linked against) by the tests.
So all tests are now under GPLv3, while everything else is still under MIT.
This should only matter in case you are linking against tests directly.
Everything else stays the same.

**Comment by aaronenyeshi** [comment]
Hi @tcnguyen , Kineto has a dependency on dynolog for their ipcfabric implementation. However, we probably don't need dynolog's third_party libraries like cpr. Adding @briancoutinho , who may be able to help remove the dependency on cpr/test/LICENSE in dynolog.

**Comment by aaronenyeshi** [comment]
I also recommend opening an issue in the dynolog repo: https://github.com/facebookincubator/dynolog/issues

**Comment by jamesjordan522** [comment]
> I also recommend opening an issue in the dynolog repo: https://github.com/facebookincubator/dynolog/issues

Reported: https://github.com/facebookincubator/dynolog/issues/278

**Comment by jamesjordan522** [comment]
Further research showed, that dynolog uses
```
add_subdirectory(third_party/cpr)
target_link_libraries(dynolog_lib PUBLIC cpr::cpr)
```
in its `CMakeLists.txt`

In cpr's `CMakeLists.txt`  the `CPR_BUILD_TESTS` flag is set to `OFF` by default.

Consequently, the cpr's test seem not to be linked in PyTorch, hence the GPL license in cpr's test folder seems to be no issue. Can anyone confirm this?
