### ISSUE TITLE
RuntimeError: CuDNN error: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by shiyinw** [pytorch/pytorch#13219]
I am running Stanford CS231n demo code on Tesla P40 AWS.

```
import copy
gpu_dtype = torch.cuda.FloatTensor

fixed_model_gpu = copy.deepcopy(fixed_model_base).type(gpu_dtype)

x_gpu = torch.randn(64, 3, 32, 32).type(gpu_dtype)
x_var_gpu = Variable(x.type(gpu_dtype)) # Construct a PyTorch Variable out of your input data
ans = fixed_model_gpu(x_var_gpu)        # Feed it through the model! 

# Check to make sure what comes out of your model
# is the right dimensionality... this should be True
# if you've done everything correctly
np.array_equal(np.array(ans.size()), np.array([64, 10]))
```

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-26-6c4deb3bc2c2> in <module>
      6 x_gpu = torch.randn(64, 3, 32, 32).type(gpu_dtype)
      7 x_var_gpu = Variable(x.type(gpu_dtype)) # Construct a PyTorch Variable out of your input data
----> 8 ans = fixed_model_gpu(x_var_gpu)        # Feed it through the model!
      9 
     10 # Check to make sure what comes out of your model

~/.local/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/.local/lib/python3.5/site-packages/torch/nn/modules/container.py in forward(self, input)
     89     def forward(self, input):
     90         for module in self._modules.values():
---> 91             input = module(input)
     92         return input
     93 

~/.local/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py in forward(self, input)
    299     def forward(self, input):
    300         return F.conv2d(input, self.weight, self.bias, self.stride,
--> 301                         self.padding, self.dilation, self.groups)
    302 
    303 

RuntimeError: CuDNN error: CUDNN_STATUS_MAPPING_ERROR

**Comment by zou3519** [comment]
Can you rerun with `CUDA_LAUNCH_BLOCKING=1` and report what the error is then?

**Comment by shiyinw** [comment]
I found that it is because my CUDA version is too old for Pytorch.

**Comment by yaolugithub** [comment]
@shiyinw 
Hi, my CUDA version is 8.0 and other information is  RTX 2080TI ,pytorch 0.4.0.
It also occurred this problem. What about your CUDA version?
