### ISSUE TITLE
[DOC] fix `mkl-static` install channel issue.

### ISSUE THREAD

**Issue by xuhancn** [pytorch/pytorch#132103]
### 📚 The doc issue

We have fixed `mkl-static` install channel issue: https://github.com/pytorch/pytorch/pull/130026, But still need to fix release branches:
[Release/2.4](https://github.com/pytorch/pytorch/tree/release/2.4?tab=readme-ov-file#install-dependencies)  and [Release/2.3](https://github.com/pytorch/pytorch/tree/release/2.3?tab=readme-ov-file#install-dependencies)

I submitted this issue for tracking.

### Suggest a potential alternative/fix

Cherry-pick: https://github.com/pytorch/pytorch/pull/130026 to `release/2.4` and fix `release/2.3` :https://github.com/pytorch/pytorch/pull/131853

cc @svekars @brycebortree

**Comment by malfet** [comment]
Closing, as I don't think we need a separate issue for cherry-pick. Please create a cherry-pick PR and reference it in a comment to https://github.com/pytorch/pytorch/issues/132400
