### ISSUE TITLE
Is there a non-inplace version of nn.Tanh()

### ISSUE THREAD

**Issue by zhanghang1989** [pytorch/pytorch#1321]
When I add nn.Tanh() to the last layer of a generative model, I got the error during the training `RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation`.
Is there a `inplace=False` option for nn.Tanh(). Thanks!

**Comment by apaszke** [comment]
`nn.Tanh` always works out-of-place. It must be an error somewhere else

**Comment by zhanghang1989** [comment]
Hi, thanks for following up. It happens during the `loss.backward`. The error disappears if removing this layer.

**Comment by asif07hossain** [comment]
x11[:,:,0:int(w_f/2),0:int(h_f/2)]= x11[:,:,0:int(w_f/2),0:int(h_f/2)]*xx1[0]

suppose x11 is a auto grad variable. Now my issue is, when i am running the code it say:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

but if i do x11=x11*xx1[0], then no error things go correctly
