### ISSUE TITLE
Nightly windows wheels build failure Jul 31. 2024

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#132295]
### 🐛 Describe the bug

Workflows:
https://github.com/pytorch/pytorch/actions/runs/10176038847/job/28170193676

Issue:
```
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\setup.py", line 236, in <module>
    import setuptools.command.build_ext
ModuleNotFoundError: No module named 'setuptools'
```

Looks like pip was updated on conda-forge from https://anaconda.org/conda-forge/pip/files?version=24.0 to https://anaconda.org/conda-forge/pip/files?version=24.1.2

And no longer has as requirement:
python >=3.7, setuptools, wheel

Possible solution add setuptools as dependency

### Versions

2.5.0

**Comment by isuruf** [comment]
Discussion at https://github.com/conda-forge/pip-feedstock/issues/124
