### ISSUE TITLE
Inductor autotuner time_taken_ns is not accurate

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#132242]
### 🐛 Describe the bug

Today, it specifically only measures the time it took to run the kernel being autotuned.  But when we cache hit, we reduce the number of configs we ask Triton to test, which reduces the amount of time we spent compiling. The cost of compilation is substantial as can be seen at:

<img width="1292" alt="image" src="https://github.com/user-attachments/assets/c7ff3e08-29cf-49f6-b5c5-5436ce66b2ef">

I discovered this when looking at https://fburl.com/scuba/pt2_remote_cache/i1hzdpkc and noticing that the amount of time saved was way too low for what I was observing was the cost of autotuning in log lines.

I'm not entirely sure how to fix this. We have some weird inversion of control with Triton, where once we have determined what configs we want Triton to run with, we don't get back control until we run CachingAutotuner. So there is no logical place to actually measure wall time for the entire end to end segment of code that was affected by our cache hit on configs. Should we just measure the walltime of precompile and add it on (but what if multiple autotunings were done for a single compilation?) I need some guidance from folks who are more familiar with the autotuner.

This statistic is important to be accurate, because we plan to use these timings to adjust NCCL timeout in the event of cache hit to allow for other hosts that may also be spending time autotuning because they missed.

cc @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @oulgen @bertmaher @Chillee 

### Versions

main

cc @chauhang @penguinwu

**Comment by ezyang** [comment]
cc @nmacchioni

**Comment by nmacchioni** [comment]
cc @eellison

**Comment by nmacchioni** [comment]
Am I correct in assuming that the `time_taken_ns` you're referring to is that from the coordinate descent tuning?

**Comment by ezyang** [comment]
These:

```
torch/_inductor/runtime/triton_heuristics.py:        time_taken_ns = time.time_ns() - start_time
torch/_inductor/runtime/triton_heuristics.py:            self.save_cache_hook(self.launchers[0].config, time_taken_ns)
torch/_inductor/runtime/triton_heuristics.py:        time_taken_ns = time.time_ns() - start_time
torch/_inductor/runtime/triton_heuristics.py:            self.save_cache_hook(best_config, time_taken_ns, found_by_coordesc=True)
torch/_inductor/runtime/triton_heuristics.py:        def save_cache_hook(cfg, time_taken_ns, found_by_coordesc=False):
torch/_inductor/runtime/triton_heuristics.py:                "time_taken_ms": time_taken_ns // 1000000,  # Convert from NS to MS
```

which are eventually saved in Scuba as time_saved

**Comment by nmacchioni** [comment]
Ah ok, I think I get what is going on here. So what time_taken_ns should be is the time to precompile the set of configs + the time to benchmark each of the configs, and in the case we do coord descent we also want to include that time as well (which will include a number of precompiles and benchmarks).

So if we cache hit on the autotuning we've saved all the benchmarking time for the set of configs, all the precompile time expect for the best config, and the entire coord descent time. Sounds like we need to record the precompile time per config (including those from coord descent), the benchmarking time from autotune_to_one_config, and the coord descent time seperately?

**Comment by nmacchioni** [comment]
> but what if multiple autotunings were done for a single compilation?

I'm not sure that this currently happens or could happen, but if I'm wrong this sounds like a design flaw that should be fixed.

**Comment by nmacchioni** [comment]
I assume this is for NCCL things? In that case, underestimate is bad and an overestimate (if slight) would be okay? In that case, your idea of adding the precompile time would be enough to get things working, it would be a slight overestimate because we'd be counting the precompile time of the best config as saved time even though we'd still have to precompile it but it might be good enough. Also this way saves effort of having to individually track precompile time per-config. Or, if it is feasible, we could pull from the cache the total cold compile time, then do the precompile of the best config immediately and subtract the cost?

**Comment by ezyang** [comment]
Yes, it's OK for NCCL. In fact, even a large overestimate would be OK for observability analysis too, we just have to use the number appropriately (instead of using this time saved to compute imputed time spent, we simply remove it from the non-cacheable number, which is now comparable across cache and not cache runs).

**Comment by nmacchioni** [comment]
https://github.com/pytorch/pytorch/pull/133633

**Comment by nmacchioni** [comment]
@ezyang can we close this issue

**Comment by eellison** [comment]
@nmacchioni typically we close after the fixing pr is landed
