### ISSUE TITLE
Make weak script public?

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#13221]
`weak_script` are moved to `torch/_jit_internal.py` in https://github.com/pytorch/pytorch/pull/12723
`weak_module` and `weak_script_method` are also in that file.

Should we import these 3 functions on `torch/jit/__init__.py` and export the doc for these functions, so that users can use `torch.jit.weak_script`, `torch.jit.weak_module`, and `torch.jit.weak_script_method` to create their own weak script functions and modules?

I will write PR if this feature is approved.

**Comment by zou3519** [comment]
cc @driazati

**Comment by driazati** [comment]
Their intended use is to allow us to create a standard library of JIT functions and modules (from `torch.nn` and `torch.nn.functional`). There is also a circular dependency issue (hence why they are not in `torch/jit/__init__.py`. 

For now weak script mode is not really supported outside of our internal use cases, but that may change once we port the standard library (though you can try it now with `@torch._jit_internal.weak_script`.

**Comment by driazati** [comment]
Weak script is now deleted, but this use case is supported by #20939
