### ISSUE TITLE
25+ compile tests were disabled as flaky 

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#132290]
### 🐛 Describe the bug

- https://github.com/pytorch/pytorch/issues/132274
- https://github.com/pytorch/pytorch/issues/132244
- https://github.com/pytorch/pytorch/issues/132245
- https://github.com/pytorch/pytorch/issues/132246
- https://github.com/pytorch/pytorch/issues/132247
- https://github.com/pytorch/pytorch/issues/132248
- https://github.com/pytorch/pytorch/issues/132249
- https://github.com/pytorch/pytorch/issues/132250
- https://github.com/pytorch/pytorch/issues/132251
- https://github.com/pytorch/pytorch/issues/132252
- https://github.com/pytorch/pytorch/issues/132253
- https://github.com/pytorch/pytorch/issues/132254
- https://github.com/pytorch/pytorch/issues/132255
- https://github.com/pytorch/pytorch/issues/132256
- https://github.com/pytorch/pytorch/issues/132257
- https://github.com/pytorch/pytorch/issues/132258
- https://github.com/pytorch/pytorch/issues/132259
- https://github.com/pytorch/pytorch/issues/132260
- https://github.com/pytorch/pytorch/issues/132261
- https://github.com/pytorch/pytorch/issues/132262
- https://github.com/pytorch/pytorch/issues/132264
- https://github.com/pytorch/pytorch/issues/132266
- https://github.com/pytorch/pytorch/issues/132267
- https://github.com/pytorch/pytorch/issues/132268
- https://github.com/pytorch/pytorch/issues/132271
- https://github.com/pytorch/pytorch/issues/132272
- https://github.com/pytorch/pytorch/issues/132274
- https://github.com/pytorch/pytorch/issues/132263

### Versions

CI

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu

**Comment by malfet** [comment]
Though, considering that all of them are about nested tensor, perhaps it should be part of different module. But still a high pri imo

**Comment by eellison** [comment]
cc @cpuhrsch

**Comment by jbschlosser** [comment]
Root cause: for tensors that contain other tensors in their `__dict__` (i.e. subclasses like `TwoTensor` and `NJT`), a ref cycle is formed due to Dynamo stashing copies of the `__dict__` in proxy node metas:

https://github.com/pytorch/pytorch/blob/645c1052a6ec1124b6dd53cfa1037ec638c943d0/torch/_dynamo/variables/builder.py#L1496

https://github.com/pytorch/pytorch/blob/f0da167ce55ddbbe4f0138ed0f0804008069ddad/torch/_dynamo/output_graph.py#L810

![ref_cycle](https://github.com/user-attachments/assets/46fd3fd4-29e5-4e32-a035-a3d0f7008c02)

**Comment by jbschlosser** [comment]
> It looks like failure is quite deterministic. In that case, why it's considered flaky? it works if invoked in isolation?

I've noticed some non-determinism when trying to reproduce the memory leak, and it's still a bit unclear to me why. But there's enough non-determinism that I could see it being considered flaky.

**Comment by malfet** [comment]
Another batch this morning:
- https://github.com/pytorch/pytorch/issues/132494
- https://github.com/pytorch/pytorch/issues/132495
- https://github.com/pytorch/pytorch/issues/132496
- https://github.com/pytorch/pytorch/issues/132497
- https://github.com/pytorch/pytorch/issues/132498
- https://github.com/pytorch/pytorch/issues/132499
- https://github.com/pytorch/pytorch/issues/132500
- https://github.com/pytorch/pytorch/issues/132501
- https://github.com/pytorch/pytorch/issues/132502
- https://github.com/pytorch/pytorch/issues/132503
- https://github.com/pytorch/pytorch/issues/132504
- https://github.com/pytorch/pytorch/issues/132505
- https://github.com/pytorch/pytorch/issues/132506
- https://github.com/pytorch/pytorch/issues/132507
- https://github.com/pytorch/pytorch/issues/132508
- https://github.com/pytorch/pytorch/issues/132509
- https://github.com/pytorch/pytorch/issues/132510
- https://github.com/pytorch/pytorch/issues/132511
- https://github.com/pytorch/pytorch/issues/132512
- https://github.com/pytorch/pytorch/issues/132513
- https://github.com/pytorch/pytorch/issues/132514
- https://github.com/pytorch/pytorch/issues/132515
- https://github.com/pytorch/pytorch/issues/132516
- https://github.com/pytorch/pytorch/issues/132517
- https://github.com/pytorch/pytorch/issues/132517

**Comment by malfet** [comment]
Reopening this one, but closing underlying issue to see if falkiness is gone or still there

**Comment by ezyang** [comment]
Looks like all the issues are fixed.
