### ISSUE TITLE
torch.ops.fsdp.set_ with torch.compile silently incorrect

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#132200]
```py
import torch
import torch.distributed._composable.fsdp._fsdp_param

@torch.compile(backend="aot_eager")
def f(x, l):
    z = x.sin()
    y = x + 1
    torch.ops.fsdp.set_.default(x, y)
    z2 = x.sin()
    return z, z2, l ** 2

x = torch.randn(3)
x_clone = x.clone()
l = torch.randn(3, requires_grad=True)

z, z2, _ = f(x, l)
assert torch.allclose(z2, (x_clone + 1).sin())
```

Here's what's going on:
- We don't functionalize set_. In order for this to be OK, set_ must be a "barrier" - we are not allowed to reorder operations that are after it to before it.
- AOTAutograd's partitioner applies CSE, which removes the `z2 = x.sin()` call. This breaks the previous condition, leading to silent incorrectness

cc @ezyang @gchanan @kadeng @msaroufim @zhaojuanmao @mrshenli @rohan-varma @awgu @fegin @kwen2501 @chauhang @bdhirsh @penguinwu

**Comment by zou3519** [comment]
cc @yf225 @bdhirsh

**Comment by bdhirsh** [comment]
here's a PR to avoid CSE'ing across mutations in the partitioner: https://github.com/pytorch/pytorch/pull/132243. I tried to re-use inductor's "mutation barrier" logic from the pattern matcher.

**Comment by yf225** [comment]
@bdhirsh assigning to you since you already have a PR open for this, thanks!
