### ISSUE TITLE
public API for checking local tensor type

### ISSUE THREAD

**Issue by weifengpy** [pytorch/pytorch#132358]
### 🚀 The feature, motivation and pitch

it's quite common to check local tensor type, but I have to access non-public `_local_tensor` every time. wonder if we have a public api to check type for `_local_tensor` ?

for float8, I am using `isinstance(param, DTensor) and isinstance(param._local_tensor, Float8Tensor)`
with public api, maybe I can do `isinstance(param, DTensor) and param.isinstance(Float8Tensor)` without accessing `_local_tensor`

cc @wanchaol @XilunWu @chauhang @d4l3k

**Comment by weifengpy** [comment]
cc @XilunWu @wanchaol

**Comment by awgu** [comment]
What is the concern with `isinstance(param.to_local(), Float8Tensor)`? CPU overhead?

**Comment by weifengpy** [comment]
> What is the concern with `isinstance(param.to_local(), Float8Tensor)`? CPU overhead?

looks promising! for `model.parameters()` that requires gradients, `to_local()` has overhead to handle gradients with `ToTorchTensor.apply` https://github.com/pytorch/pytorch/blob/0eea2b394732522aa15861dfeb7fb851a481fec6/torch/distributed/_tensor/api.py#L435-L439

this might be good enough for non-cpu-bound workloads

**Comment by weifengpy** [comment]
closing in favor of `to_local()`

**Comment by weifengpy** [comment]
> `to_local` is exactly defined to interact with anything about local_tensor, CPU overhead usually should not be a worry, since it's just a autograd function that does not do any other logic i.e. if we worry too much about this, we probably want to worry about EVERY autograd function defined in pytorch :)

got you. thanks for explaining this
