### ISSUE TITLE
flash attention triton kernel x pt2 silently incorrect

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#132301]
Minimal repro over at https://gist.github.com/zou3519/45a561ac45f11cd39a277e42d4282e62. Will try to minimize it more. This requires backend="inductor" to repro, but I am not sure what exactly the problem is (there's a lot of things going on here)

NB: https://github.com/pytorch/pytorch/pull/132238 doesn't fix it, but it does fix a problem that is present

cc @ezyang @gchanan @kadeng @msaroufim @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @muchulee8 @ColinPeppler @amjames @desertfire @bdhirsh @oulgen @aakhundov

**Comment by zou3519** [comment]
I found the problem. There's a line in the code that does `arg_k = k * (0.5100697232983947)`. In eager-mode PyTorch, this happens in bfloat16. In Inductor, this happens under torch.float32:
```
def triton_(in_ptr0, out_ptr0, out_ptr1, xnumel, XBLOCK : tl.constexpr):
    xnumel = 640
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), xmask)
    tmp1 = tmp0.to(tl.float32)
    tmp2 = 0.5100697232983947
    tmp3 = tmp1 * tmp2
    tl.store(out_ptr0 + (x0), tmp1, xmask)
    tl.store(out_ptr1 + (x0), tmp3, xmask)
```
so... the conclusion is that inductor is more accurate that eager-mode. The change in `arg_k` causes different numerics for the model (I verified that changing arg_k to the original value in the torch.compile'd output makes it so that there is no silent incorrectness)

**Comment by oulgen** [comment]
also @Chillee

**Comment by zou3519** [comment]
Concretely what I think is going on is:
```
import torch

def f(k): # E: Function is missing a type annotation  [no-untyped-def]
    return k * 0.5100697232983947

k = torch.randn(100, dtype=torch.float32)
# This is what eager-mode PyTorch is doing
k2 = (k.bfloat16() * 0.5100697232983947).bfloat16()

# this is what torch.compile is doing
k3 = (k * 0.5100697232983947).bfloat16()

torch.testing.assert_close(k2, k3, atol=1e-5, rtol=1e-5)
```
(the snippet I linked is irrelevant to this, tmp0 is already float32)

**Comment by zou3519** [comment]
Some offline discussion with Elias:
- It is generally a feature that Inductor may be more accurate than eager-mode 
-  https://github.com/pytorch/pytorch/pull/131595 offers a config that should be able to fix it, maybe we're missing a cast somewhere

**Comment by eellison** [comment]
Update - with casting inputs as well this is fixed. i'm going to close
