### ISSUE TITLE
is_bf_16_supported() should return False when running on CPU **NOT AN ERROR**

### ISSUE THREAD

**Issue by brando90** [pytorch/pytorch#132303]
### 🐛 Describe the bug

```
import torch
bf16 = torch.cuda.is_bf16_supported()
print(f'{bf16=}')
```

is_bf_16_supported() should return False when running on CPU **NOT AN ERROR**

### Versions

(AI4Lean) (base) miranebr@80a997333470 ~ % python collect_env.py

Collecting environment information...
PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (x86_64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.9 (main, Apr 19 2024, 11:44:45) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.2
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.2                    pypi_0    pypi

cc @ptrblck @msaroufim @albanD

**Comment by malfet** [comment]
Makes sense, PR is coming (though I wonder if I should add a test for it as well)
