### ISSUE TITLE
How to use model.pt in GPU whith C++ API

### ISSUE THREAD

**Issue by joy-yjl** [pytorch/pytorch#13245]
I wrapped a pt with Torch Script, and load it with c++ api.

I want to use it in GPU, I can do model.cuda() in python . How can I do it in C++.

**Comment by bhack** [comment]
See https://github.com/pytorch/pytorch/issues/12686#issuecomment-430321460.
Also I would know if the network weights could be loaded after `torch::jit::load()`.
/cc @goldsborough

**Comment by goldsborough** [comment]
@joy-yjl You can write `model->to(at::kCUDA)`. Does that work for you?

@bhack you mean whether you can first load the model, and then the weights after? Please elaborate.

**Comment by goldsborough** [comment]
@bhack You can always access the parameters after and make changes. E.g. use [`module->get_parameter(name)`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/module.h#L351). Generally see https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/module.h for things you can do with a module.

**Comment by bhack** [comment]
Yes I saw the header for single parameter but I meant something like the the equivalent of ```the_model.load_state_dict(torch.load(PATH))```

**Comment by joy-yjl** [comment]
> model->to(at::kCUDA)
It is work for me .thanks!

**Comment by joy-yjl** [comment]
> @joy-yjl You can write `model->to(at::kCUDA)`. Does that work for you?
> 
> @bhack you mean whether you can first load the model, and then the weights after? Please elaborate.

and when I use" torch::CUDA(torch::kFloat32).tensorFromBlob(img_float.data, {1, r, c, 3});"  is error. How I get a GPU tensor

**Comment by bhack** [comment]
@goldsborough I see only a get_parameters at https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/module.h#L368 but not a method to set again parameters at once.

**Comment by lenlen** [comment]
@goldsborough I need also this feature to set all parameters at once to avoid a loop for each parameters, to load the weights in my traced network.

**Comment by bhack** [comment]
@lenlen If you are interested I've opened a specific ticket at https://github.com/pytorch/pytorch/issues/13383

**Comment by Joshua-Cardio** [comment]
> model->to(at::kCUDA)
> It is work for me .thanks!

Hi Joy-yil, 

Could you share a little more about your setting? 

I follow the tutorials on https://pytorch.org/tutorials/advanced/cpp_export.html, and add
>  model->to(at::kCUDA)

But errors is thrown when execute the model
 I auto output = module->forward(inputs).toTensor();

Error: 
what(): Expected object of backend CPU but got backend CUDA for argument #2 'weight' 

Thanks,

**Comment by goldsborough** [comment]
@Joshua-Cardio did you move your inputs to CUDA? e.g. with `input.to(at::kCUDA)` before passing it to the model

**Comment by Joshua-Cardio** [comment]
Thanks @goldsborough.

when using 
std::vector<torch::jit::IValue> inputs;
inputs.push_back(torch::ones({1, 3, 224, 224}));
inputs.to(at::kCUDA);
an error occurs, 
'class std::vector<c10:IValue, std::allocator<c10::IValue>>' has no member named 'to'

Later I follow your guidance in https://github.com/pytorch/pytorch/issues/12506, and 
add tensor_image.to(at::kCUDA). It worked. Thanks!

**Comment by bhack** [comment]
Yes https://github.com/pytorch/pytorch/issues/12506 it really needs to be included in the tutorial.

**Comment by goldsborough** [comment]
I'll put it on my list of things to do to expand the tutorial around GPU usage and conversion from and to tensor types :)

**Comment by joy-yjl** [comment]
> I'll put it on my list of things to do to expand the tutorial around GPU usage and conversion from and to tensor types :)

when I use GPU do forward ,there is cuda error : out of memory . I find that when I test one image .It use almost 2T GPU memory . I don't know why . When I use python there is no error.

**Comment by bhack** [comment]
@goldsborough I think that the tutorial could explain also torch.no_grad in c++ and python interfaces. I think that it is a common practice with traced models but it is undocumented.

**Comment by ananth-jauntxr** [comment]
Any update on GPU usage? :)

**Comment by soumith** [comment]
@ananth-jauntxr it's in the 2nd comment of the thread

**Comment by cindycia** [comment]
> Thanks @goldsborough.
> 
> when using
> std::vectortorch::jit::IValue inputs;
> inputs.push_back(torch::ones({1, 3, 224, 224}));
> inputs.to(at::kCUDA);
> an error occurs,
> 'class std::vector<c10:IValue, std::allocatorc10::IValue>' has no member named 'to'
> 
> Later I follow your guidance in #12506, and
> add tensor_image.to(at::kCUDA). It worked. Thanks!

I got the same issue. 

Can you share with me your final solution in more details?

**Comment by Eniac-Xie** [comment]
Hi, @soumith @goldsborough how can I set gpu id in C++ code? Does cudaSetDevice() work for it?
Thank you!

**Comment by dagap** [comment]
I am a bit confused about the use of `inputs.to(at::kCUDA);`. Can I choose which GPU to use? It is very difficult to find the detailed documentation for this method, it seems.
