### ISSUE TITLE
Potential memory leak in Tensor.size()

### ISSUE THREAD

**Issue by shhshn** [pytorch/pytorch#13243]
## 🐛 Bug

Tensor.size() leaks 28 bytes of memory (similar to the previously resolved issue of #1963)

## To Reproduce

```
import torch, tracemalloc; tracemalloc.start()

def main():
    def loop(maximum):
        tmp = torch.Tensor(maximum)
        for _ in range(1000):
            sizes = tmp.size()
    snapshot1 = tracemalloc.take_snapshot()
    loop(maximum=256)
    snapshot2 = tracemalloc.take_snapshot()
    loop(maximum=257)
    snapshot3 = tracemalloc.take_snapshot()
    for line in snapshot2.compare_to(snapshot1, 'lineno')[:10]:
        print(line)
    print()
    for line in snapshot3.compare_to(snapshot2, 'lineno')[:10]:
        print(line)

if __name__ == "__main__":
    main()
```

## Expected behavior

This will give you something similar to the line below only in the second run, but this should not happen.
```
size-problem.py:8: size=27.3 KiB (+27.3 KiB), count=1000 (+1000), average=28 B
```
It can be read as a leak of 28 bytes in average.

However, it is possible that `Tensor.size()` is called, say, 2,000,000 times in an upper-stream application, which will result in a massive leak of more than a few gigabytes.

## Environment

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla M60
Nvidia driver version: 396.37
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

## Additional context

- AFAIK this happens iif no argument is given and there exists any dimension larger than 256.
- In addition, I cannot reproduce the problem using macOS.

**Comment by ezyang** [comment]
256 is the magic Python number, we probably are leaking Python numbers.

**Comment by albanD** [comment]
@ezyang [this](https://github.com/pytorch/pytorch/blob/71113c6b9e9d2ce3a063f27a8fcc3dbf0cb63489/torch/csrc/utils/python_tuples.h#L14) looks bad, it should be `i64` here I think.
`PyTuple_SET_ITEM` steals a reference but we unpack it twice here.

**Comment by apaszke** [comment]
Yep, that's most likely the culprit. @albanD can you please send a PR?

**Comment by albanD** [comment]
I can send a PR but I don't have a python install with tracemalloc at hand to test.
I should have time tomorrow to set that up if it's not more urgent.
