### ISSUE TITLE
torch.isin sometimes causes "index x is out of bounds for dimension 0 with size y" error

### ISSUE THREAD

**Issue by aleksandr-mokrov** [pytorch/pytorch#132486]
### 🐛 Describe the bug

The error is reproduced periodically when using the model [distil-whisper](https://github.com/huggingface/distil-whisper) only on pytorch 2.4.0 on Windows. It is not reproducible on Ubuntu or troch<2.4.0. 
The problem is in the line: https://github.com/huggingface/transformers/blob/main/src/transformers/generation/logits_process.py#L1836

Minimal reproducible example:
```python
import torch

a = torch.tensor([    1,     2,     7,     8,     9,    10,    14,    25,    26,    27,
           28,    29,    31,    58,    59,    60,    61,    62,    63,    90,
           91,    92,    93,   357,   366,   438,   532,   685,   705,   796,
          930,  1058,  1220,  1267,  1279,  1303,  1343,  1377,  1391,  1635,
         1782,  1875,  2162,  2361,  2488,  3467,  4008,  4211,  4600,  4808,
         5299,  5855,  6329,  7203,  9609,  9959, 10563, 10786, 11420, 11709,
        11907, 13163, 13697, 13700, 14808, 15306, 16410, 16791, 17992, 19203,
        19510, 20724, 22305, 22935, 27007, 30109, 30420, 33409, 34949, 40283,
        40493, 40549, 47282, 49146, 50257, 50357, 50358, 50359, 50360, 50361])

b = torch.arange(1, 50362)

for i in range(100):
    torch.isin(b, a)
```
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[11], line 16
     13 b = torch.arange(1, 50362)
     15 for i in range(100):
---> 16     torch.isin(b, a)

IndexError: index 48321 is out of bounds for dimension 0 with size 39433
```
It is not 100% reproducible, sometimes the error occurs once in dozens of launches, sometimes every time.

### Versions

PyTorch version: 2.4.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2995
DeviceID=CPU0
Family=198
L2CacheSize=5120
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2995
Name=11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] onnx==1.16.1
[pip3] torch==2.4.0+cpu
[conda] Could not collect

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex

**Comment by SylvainBrouwer** [comment]
I can reproduce the issue on windows with torch==2.4.0

Note that moving the tensors to CUDA fixes the issue, i.e. the following never fails:
```
import torch

a = torch.tensor([    1,     2,     7,     8,     9,    10,    14,    25,    26,    27,
           28,    29,    31,    58,    59,    60,    61,    62,    63,    90,
           91,    92,    93,   357,   366,   438,   532,   685,   705,   796,
          930,  1058,  1220,  1267,  1279,  1303,  1343,  1377,  1391,  1635,
         1782,  1875,  2162,  2361,  2488,  3467,  4008,  4211,  4600,  4808,
         5299,  5855,  6329,  7203,  9609,  9959, 10563, 10786, 11420, 11709,
        11907, 13163, 13697, 13700, 14808, 15306, 16410, 16791, 17992, 19203,
        19510, 20724, 22305, 22935, 27007, 30109, 30420, 33409, 34949, 40283,
        40493, 40549, 47282, 49146, 50257, 50357, 50358, 50359, 50360, 50361])

b = torch.arange(1, 50362)
a = a.to(device="cuda")
b = b.to(device="cuda")
for i in range(100):
    torch.isin(a, b)
```

In my case, switching to the nightly build also fixed it for CPU
```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124
```

This makes me believe that this is related to #131958

**Comment by xuhancn** [comment]
> I can reproduce the issue on windows with torch==2.4.0
> 
> Note that moving the tensors to CUDA fixes the issue, i.e. the following never fails:
> 
> ```python
> import torch
> 
> a = torch.tensor([    1,     2,     7,     8,     9,    10,    14,    25,    26,    27,
>            28,    29,    31,    58,    59,    60,    61,    62,    63,    90,
>            91,    92,    93,   357,   366,   438,   532,   685,   705,   796,
>           930,  1058,  1220,  1267,  1279,  1303,  1343,  1377,  1391,  1635,
>          1782,  1875,  2162,  2361,  2488,  3467,  4008,  4211,  4600,  4808,
>          5299,  5855,  6329,  7203,  9609,  9959, 10563, 10786, 11420, 11709,
>         11907, 13163, 13697, 13700, 14808, 15306, 16410, 16791, 17992, 19203,
>         19510, 20724, 22305, 22935, 27007, 30109, 30420, 33409, 34949, 40283,
>         40493, 40549, 47282, 49146, 50257, 50357, 50358, 50359, 50360, 50361])
> 
> b = torch.arange(1, 50362)
> a = a.to(device="cuda")
> b = b.to(device="cuda")
> for i in range(100):
>     torch.isin(a, b)
> ```
> 
> In my case, switching to the nightly build also fixed it for CPU
> 
> ```
> pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124
> ```
> 
> This makes me believe that this is related to #131958

@atalman if we can get the release/2.4.1 nightly build, and validate the issue?

**Comment by xuhancn** [comment]
> @xuhancn 2.4.1 RC builds are already available from https://download.pytorch.org/whl/test/cpu, do you mind checking if it still reproduces, and if not, close this issue as duplicate of static MKL linking?

@aleksandr-mokrov could you please validate the issue on 2.4.1 RC build?

**Comment by aleksandr-mokrov** [comment]
> > @xuhancn 2.4.1 RC builds are already available from https://download.pytorch.org/whl/test/cpu, do you mind checking if it still reproduces, and if not, close this issue as duplicate of static MKL linking?
> 
> @aleksandr-mokrov could you please validate the issue on 2.4.1 RC build?

Yes, it works! Thank you

**Comment by atalman** [comment]
Confirmed it works for final rc 2.4.1
