### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one.

### ISSUE THREAD

**Issue by asusdisciple** [pytorch/pytorch#132402]
### 🐛 Describe the bug

Here is the situation: I have two models. 
Model 1: Custom Edge Detection Model (works on its own, tested)
Model 2: Pretrained ImageClassifier (works on its own, tested)

The input from model_1 is supposed to be fed into model_2.
So I took the initialized `model_2` (weights are loaded), and appended `model_1`
with `model_2.sub_model = model_1`. 

I made an overwrite to the forward() function of `model_1` before I initialized the weights
with `model_2.forward = my_forward`.  There I call `self.sub_model.forward(x)`.

This approach already worked fine for smaller adjustments like model surgery of the last layer etc.

However now when I load `model_1` like this into my main model `model_2` I get the error:

```
RuntimeError:
Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameters which did not receive grad for rank 2: y_sob.bias, y_sob.weight, x_sob.bias, x_sob.weight, .high_threshold, .low_threshold
Parameter indices which did not receive grad for rank 2: 0 1 208 209 210 211
```
These weights belong to model_1 but I have no clue why they are not recognized. They all have `requires_grad=True`. Is there a way to make them visible to the main model? I do a lot of torch operations between convolutions etc in this model, maybe this has something to do with it?
Anyways I think this should not happen since the models works individually.

### Versions

torch 2.3.0
ubuntu 22.04
python 3.10

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by asusdisciple** [comment]
I want to add, this might be related to distributed training parallel because when I put a random tensor through the model it just works fine on one machine.

**Comment by awgu** [comment]
Is it possible to provide a repro? It might be easier to see how the model surgery is happening and how DDP is being used.

**Comment by asusdisciple** [comment]
Yes this should work, even without ddp. The problem seems to be that the grad gets lost along the way for the last tensor. I do not know if this is a bug or my mistake. My objective is just to track all the parameters like you normally would and adjust gradients. Something I noticed: When you change the output tensor to `img_th` the gradient calculation works, but not for the single parameters `low_threshold` and `high_threshold`. Settings requires_grad=True for the output tensor does not help either unfortunately. Here is the code (Just focus on the forward, you can ignore the rest):


from torch import nn
import torch
from torch.functional import F
from itertools import repeat
import collections
from torchvision.transforms import v2
def _ntuple(n):
    """Copied from PyTorch since it's not importable as an internal function

    https://github.com/pytorch/pytorch/blob/v1.10.0/torch/nn/modules/utils.py#L6
    """
    def parse(x):
        if isinstance(x, collections.abc.Iterable):
            return tuple(x)
        return tuple(repeat(x, n))

    return parse


_pair = _ntuple(2)

class MaxPool2dStaticSamePadding(nn.Module):
    """
    The real keras/tensorflow MaxPool2d with same padding
    """

    def __init__(self, *args, **kwargs):
        super().__init__()
        self.pool = nn.MaxPool2d(*args, **kwargs)
        self.stride = self.pool.stride
        self.kernel_size = self.pool.kernel_size

        if isinstance(self.stride, int):
            self.stride = [self.stride] * 2
        elif len(self.stride) == 1:
            self.stride = [self.stride[0]] * 2

        if isinstance(self.kernel_size, int):
            self.kernel_size = [self.kernel_size] * 2
        elif len(self.kernel_size) == 1:
            self.kernel_size = [self.kernel_size[0]] * 2

        # Setup internal representations
        kernel_size_ = _pair(self.kernel_size)
        dilation_ = _pair(1)
        self._reversed_padding_repeated_twice = [0, 0] * len(kernel_size_)

        # Follow the logic from ``nn._ConvNd``
        # https://github.com/pytorch/pytorch/blob/v1.10.0/torch/nn/modules/conv.py#L116
        for d, k, i in zip(dilation_, kernel_size_, range(len(kernel_size_) - 1, -1, -1)):
            total_padding = d * (k - 1)
            left_pad = total_padding // 2
            self._reversed_padding_repeated_twice[2 * i] = left_pad
            self._reversed_padding_repeated_twice[2 * i + 1] = (
                    total_padding - left_pad)

    def forward(self, x):
        """Setup padding so same spatial dimensions are returned

        All shapes (input/output) are ``(N, C, W, H)`` convention

        :param torch.Tensor imgs:
        :return torch.Tensor:
        """
        padded = F.pad(x, self._reversed_padding_repeated_twice)
        x = self.pool(padded)
        return x
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.x_sob = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(3, 3), stride=(1, 1), padding="same")
        self.y_sob = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(3, 3), stride=(1, 1), padding="same")
        self.x_sob.weight = nn.Parameter(torch.Tensor([[[[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]]]]))
        self.y_sob.weight = nn.Parameter(torch.Tensor([[[[1, 2, 1], [0, 0, 0], [-1, -2, -1]]]]))
        self.apply_thresh = MaxPool2dStaticSamePadding(kernel_size=(3, 3), stride=1)
        self.low_threshold = nn.Parameter(torch.Tensor([0.05]))
        self.high_threshold = nn.Parameter(torch.Tensor([0.15]))
        self.blur = v2.GaussianBlur(kernel_size=5, sigma=1.4)

    def non_max_suppression(self, img, D):
        # Ensure img has the shape (batch_size, 1, height, width)
        batch_size, _, height, width = img.size()

        angle = (D * 180. / torch.pi) % 180  # Normalize angles to [0, 180)

        # Create shifted versions of the image for comparison
        img_padded = torch.nn.functional.pad(img, (1, 1, 1, 1), mode='constant', value=0)

        # Direction 0 degrees
        q0 = img_padded[:, :, 1:-1, 2:]
        r0 = img_padded[:, :, 1:-1, :-2]

        # Direction 45 degrees
        q45 = img_padded[:, :, 2:, :-2]
        r45 = img_padded[:, :, :-2, 2:]

        # Direction 90 degrees
        q90 = img_padded[:, :, 2:, 1:-1]
        r90 = img_padded[:, :, :-2, 1:-1]

        # Direction 135 degrees
        q135 = img_padded[:, :, :-2, :-2]
        r135 = img_padded[:, :, 2:, 2:]

        # Create masks for angle ranges
        mask_0 = ((0 <= angle) & (angle < 22.5)) | ((157.5 <= angle) & (angle < 180))
        mask_45 = (22.5 <= angle) & (angle < 67.5)
        mask_90 = (67.5 <= angle) & (angle < 112.5)
        mask_135 = (112.5 <= angle) & (angle < 157.5)

        # Suppress non-maximum values
        Z = (mask_0 & (img >= q0) & (img >= r0)) | \
            (mask_45 & (img >= q45) & (img >= r45)) | \
            (mask_90 & (img >= q90) & (img >= r90)) | \
            (mask_135 & (img >= q135) & (img >= r135))

        # Apply the suppression result to the original image
        Z = Z * img
        Z = Z[:, :, 1:-1, 1:-1]
        return Z


    def forward(self, x):
        # Gaussian blur & sobel filter
        x = self.blur(x)
        gX = self.x_sob(x)
        gY = self.y_sob(x)

        # Calculate Magnitude and angle theta
        mag = torch.sqrt(torch.pow(gX, 2) + torch.pow(gY, 2))
        mag = ((mag / torch.max(mag)) * 255)
        theta = torch.arctan2(gY, gX)

        # Create nms representation of img
        img = self.non_max_suppression(mag, theta)

        # calculate low and high threshold
        batch_size = img.size(0)
        h_t = img.reshape(batch_size, -1).max(dim=1).values.reshape(batch_size, 1, 1, 1) * self.high_threshold
        l_t = h_t * self.low_threshold

        # accept pixels values higher than h_t, reject pixel value lower l_t, create mask
        accept_mask = (img > h_t).bool()
        reject_mask = (img < l_t).bool()

        # get values between high and low threshold
        bet_mask = ((img > l_t) & (img < h_t)).bool()

        # set all value in "img" to zero which are not True in the accept mask
        img_acc = img.masked_fill(~accept_mask, 0)

        # apply hysteresis by using max_pooling -> all pixels with neighbouring "strong" pixels get also "strong"
        img_th = self.apply_thresh(img_acc)

        # create a mask where all fields are true which fall between the thresholds
        img_b_mask = img.masked_fill(~bet_mask, 0).bool()

        # Replace all values < 0 in img_acc with the strong neighbours which are in bet_mask, else 0
        out = torch.where(img_acc > 0, img_acc, img_th.masked_fill(~img_b_mask, 0))
        out = torch.where(reject_mask, 0, out)  # Apply reject mask directly
        out = torch.where(out > 0, 255.0, 0.0).to(torch.float32)



        return out[0,0,:200,:200]

net = NeuralNetwork()
net.train()
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
print(list(net.parameters()))
loss_fn = torch.nn.CrossEntropyLoss()
out = torch.randn(3,1,224,224)
inp = torch.randn(3,1,224,224)

optimizer.zero_grad()

res = net(inp)
l = loss_fn(res, out[0,0,:200,:200])
print("LOSS:", l)
l.backward()
optimizer.step()
print(list(net.parameters()))
