### ISSUE TITLE
Add Tarball (.tar.gz) to PyPI Releases

### ISSUE THREAD

**Issue by rbebb** [pytorch/pytorch#132413]
### 🚀 The feature, motivation and pitch

I noticed that releases on PyPI don't include a tarball (.tar.gz). Is it possible to include the tarball for those that want to build from source? It's more straightforward for most users to specify a PyPI package than a git repo!

### Alternatives

Alternatively, someone could specify the git repo URL.

### Additional context

This would be especially useful starting with 2.3.0 since support ended for x86 Macs.

**Comment by malfet** [comment]
This is an interesting idea, but has a few downsides:
 - PyPI storage space is very limited and we try to minimize what is published here
 - Publishing tarball might result in a very lengthy build process for say Python-3.6, 3.7 that we also stopped publishing
 - Tarballs are already published on GitHub, for example https://github.com/pytorch/pytorch/releases/download/v2.4.0/pytorch-v2.4.0.tar.gz
Can you please elaborate what is wrong with using that one vs one from PyPI?

@atalman I remember there were an issue about publishing tarballs to download.pytorch.org? Is this already the case?

**Comment by rbebb** [comment]
To address those downsides, I have a few counterpoints:

1. You will only ever have 1 tarball per release
2. As long as a minimum Python version is set in a project's setup.py or pyproject.toml, it shouldn't attempt to build on older Python versions like 3.6 and 3.7. Also, the length of the build process is almost certainly a non-issue for those on a platform that doesn't have wheels available. They just want to be able to use PyTorch!
3. Having the wheel published on PyPI makes dependency management much easier. Instead of specifying a git repo with a _single_ version/tag or branch, you can simply specify the name of package you want along with the _range_ of versions you want to support!

**Comment by rbebb** [comment]
I do have one question for the PyTorch team though. Is PyTorch able to install from source if a user were to only install Python from the official Python website without any other developer tools installed? If that's not the case, it's likely better to not include the source distribution to avoid confusion with users.

**Comment by rbebb** [comment]
After thinking about this more, I actually don't believe this would be the best path forward. My initial thought process was that it would be great to make the source distribution available on PyPI so that users would always have easy access to the newest version of PyTorch (even if the user's platform doesn't have a wheel). However, that will likely cause more issues than it solves because it would assume that a user also has a compiler installed.

I really appreciate you taking the time to take a look at this though!

**Comment by clee2000** [comment]
Closing as this doesn't seem like the best path forward, feel free to re open if you have more comments
