### ISSUE TITLE
Make JIT less CUDA-centric

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#13254]
In a bunch of places in the JIT, we store an `int` representing a device index (where it is `-1` for CPU and otherwise represents a CUDA device). We have a perfectly good `at::Device` class which should be used instead, and prevents people from hard-coding assumptions that CPU and CUDA are the only devices.

If there are performance considerations, let me know, but at least in terms of memory footprint, `at::Device` still fits in a single 64-bit word.

**Comment by apaszke** [comment]
It has nothing to do with performance, it's just that the JIT started long before `at::Device` existed, and no one had time to refactor it.

**Comment by ArmenAg** [comment]
@zdevito I will start working on this.

**Comment by ArmenAg** [comment]
I was taking a look at this and I wanted to start of by making [ArgumentInfo and ArgumentSpec](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/argument_spec.h) use at::Device. The problem is there is a static assertion that ArgumentInfo is POD:

```
static_assert(std::is_pod<ArgumentInfo>::value,
  "ArgumentInfo is to be a POD struct");
static_assert(sizeof(ArgumentInfo) == sizeof(ArgumentInfo::plain_data_type),
  "ArgumentInfo is expected to be a 32-bit struct");
```

This assumption will be broken if we introduce `at::Device` into `ArgumentInfo`. It also seems like we need this assertion since we do:
```
  void combineHash(const ArgumentInfo &arg) {
    ArgumentInfo::plain_data_type arg_data;
    std::memcpy(&arg_data, &arg, sizeof(ArgumentInfo));
    hash_code = hash_combine(hash_code, arg_data);
  }
```
@zdevito any advice on what I should do?

**Comment by zdevito** [comment]
ArgumentSpec/ArgumentInfo is only used for specializations for Tensor types and tuples containing tensor types. You should not have to modify it to support at::Device.  Try looking at another type such as `StringType` to see what gets modified to add a type.

**Comment by ArmenAg** [comment]
Thank you @zdevito. Now I'm looking about using at::Device in [jit_type](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/jit_type.h) to allow TensorType to directly use at::Device. Is this a good first step?

**Comment by Google1234** [comment]
suffer trouble:
`libtorch/include/torch/csrc/jit/argument_spec.h(62): error: static assertion failed with "ArgumentInfo is to be a POD struct"`

**Comment by hzxie** [comment]
+1
PyTorch 1.2.0 + CUDA 9.0 (Build from Source)

**Comment by ezyang** [comment]
@Google1234 @hzxie could you please file a new issue and describe in more detail what compiler / cuda version you're building with
