### ISSUE TITLE
[DCP] Test failure in test_e2e_save_and_load.py::TestE2ESaveAndLoad::test_e2e_compile_False_model_type0

### ISSUE THREAD

**Issue by newsweet** [pytorch/pytorch#132639]
### 🐛 Describe the bug

I tried to use dcp+fsdp for training, but I got an error when executing optimizer.step(). I found the relevant unit test in pytorch[: test_e2e_save_and_load.py::TestE2ESaveAndLoad::test_e2e, ](https://github.com/pytorch/pytorch/blob/main/test/distributed/checkpoint/e2e/test_e2e_save_and_load.py#L210), and the same error was reported when running the test.

The command I used to execute the test is：
`pytest test_e2e_save_and_load.py::TestE2ESaveAndLoad::test_e2e_compile_False_model_type0`

The error stack is as follows：
`E           RuntimeError: Process 2 exited with error code 10 and exception:
E           Traceback (most recent call last):
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 657, in run_test
E               getattr(self, test_name)()
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 539, in wrapper
E               fn()
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2744, in wrapper
E               method(*args, **kwargs)
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 446, in instantiated_test
E               test(self, **param_kwargs)
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 369, in wrapper
E               func(self, *args, **kwargs)  # type: ignore[misc]
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 180, in wrapper
E               return func(*args, **kwargs)
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/distributed/checkpoint_utils.py", line 44, in wrapper
E               func(self, *args, **kwargs)
E             File "/tos/xintian/test_e2e_save_and_load.py", line 212, in test_e2e
E               self._run_e2e_test(compile, model_type)
E             File "/tos/xintian/test_e2e_save_and_load.py", line 276, in _run_e2e_test
E               dist_loss, _ = _train(dist_model, dist_optim, train_steps=1)
E             File "/tos/xintian/test_e2e_save_and_load.py", line 139, in _train
E               optim.step()
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/optimizer.py", line 483, in wrapper
E               out = func(*args, **kwargs)
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/optimizer.py", line 89, in _use_grad
E               ret = func(self, *args, **kwargs)
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/adam.py", line 226, in step
E               adam(
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/optimizer.py", line 161, in maybe_fallback
E               return func(*args, **kwargs)
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/adam.py", line 766, in adam
E               func(
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/adam.py", line 534, in _multi_tensor_adam
E               torch._foreach_lerp_(device_exp_avgs, device_grads, 1 - beta1)
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/_compile.py", line 31, in inner
E               return disable_fn(*args, **kwargs)
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
E               return fn(*args, **kwargs)
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/_tensor/api.py", line 309, in __torch_dispatch__
E               return DTensor._op_dispatcher.dispatch(
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/_tensor/_dispatch.py", line 115, in dispatch
E               op_info = self.unwrap_to_op_info(op_call, args, kwargs)
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/_tensor/_dispatch.py", line 351, in unwrap_to_op_info
E               args_schema.append(try_get_replicate_spec(arg, mesh))
E             File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/_tensor/_dispatch.py", line 332, in try_get_replicate_spec
E               raise RuntimeError(
E           RuntimeError: aten._foreach_lerp_.Scalar: got mixed torch.Tensor and DTensor, need to convert all torch.Tensor to DTensor before calling distributed operators!`

### Versions

PyTorch version: 2.4.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.29.5
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.250-2-velinux1u3-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA L20
GPU 1: NVIDIA L20
GPU 2: NVIDIA L20
GPU 3: NVIDIA L20
GPU 4: NVIDIA L20
GPU 5: NVIDIA L20
GPU 6: NVIDIA L20
GPU 7: NVIDIA L20

Nvidia driver version: 535.154.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   52 bits physical, 57 bits virtual
CPU(s):                          180
On-line CPU(s) list:             0-169
Off-line CPU(s) list:            170-179
Thread(s) per core:              1
Core(s) per socket:              45
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           143
Model name:                      Intel(R) Xeon(R) Platinum 8457C
Stepping:                        8
CPU MHz:                         2600.000
BogoMIPS:                        5200.00
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       2.1 MiB
L1i cache:                       1.4 MiB
L2 cache:                        90 MiB
L3 cache:                        97.5 MiB
NUMA node0 CPU(s):               0-89
NUMA node1 CPU(s):               90-179
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Unknown: No mitigations
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 wbnoinvd arat avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid cldemote movdiri movdir64b md_clear arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] torch==2.4.0+cu118
[pip3] torchaudio==2.2.1+cu118
[pip3] torchmetrics==1.4.0
[pip3] torchvision==0.19.0
[pip3] triton==3.0.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.4.0+cu118              pypi_0    pypi
[conda] torchaudio                2.2.1+cu118              pypi_0    pypi
[conda] torchmetrics              1.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @LucasLLC @MeetVadakkanchery @mhorowitz @pradeepfn

**Comment by newsweet** [comment]
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/63715701-1f52-432d-9308-a20b93a9d792">

**Comment by fegin** [comment]
@newsweet I tried `pytest test/distributed/checkpoint/e2e/test_e2e_save_and_load.py` command with the nightly PyTorch but could not reproduce the error. Can you try the same command?
