### ISSUE TITLE
[dynamo][vllm] Support construction of TypedDict

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#132629]
### 🐛 Describe the bug

This graph breaks right now

~~~
from typing import TypedDict, Literal
import torch


class LlavaImagePixelInputs(TypedDict):
    type: Literal["pixel_values"]
    data: torch.Tensor
    """Shape: `(batch_size, num_channels, height, width)`"""


def fn(x, y):
    obj = LlavaImagePixelInputs(int, y)
    return x * obj.y

opt_fn = torch.compile(fn, backend="eager", fullgraph=True)
opt_fn(torch.randn(4), torch.randn(4))
~~~

Stack trace
~~~
  File "/home/anijain/local/pytorch2/torch/_dynamo/symbolic_convert.py", line 557, in wrapper
    return inner_fn(self, inst)
  File "/home/anijain/local/pytorch2/torch/_dynamo/symbolic_convert.py", line 1564, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/anijain/local/pytorch2/torch/_dynamo/symbolic_convert.py", line 804, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/home/anijain/local/pytorch2/torch/_dynamo/variables/user_defined.py", line 492, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/anijain/local/pytorch2/torch/_dynamo/variables/base.py", line 308, in call_function
    unimplemented(f"call_function {self} {args} {kwargs}")
  File "/home/anijain/local/pytorch2/torch/_dynamo/exc.py", line 283, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: call_function UserDefinedClassVariable(<class '__main__.LlavaImagePixelInputs'>) [BuiltinVariable(), LazyVariableTracker()] {}

~~~

For now, we should specialized for TypedDict to unblock vllm work. In the long term, we might need Dynamo to inline into `__new__` and make it understand metaclasses to make it work generically. This seems like a hard problem for now.

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec @zou3519 @mlazos @williamwen42 @yanboliang 

### Versions

NA

**Comment by vulkomilev** [comment]
I am not sure but I think you maybe need to use something like VariableBuilder to implement that method

**Comment by bnellnm** [comment]
Just to add some context, the following vllm models all use the same `TypedDict` pattern:

- qwen2_vl.py
- paligemma.py
- llava.py
- qwen.py
- chameleon.py
- llava_onevision.py
- minicpmv.py
- llava_next_video.py
- llava_next.py
- phi3v.py
- internvl.py
- fuyu.py
- ultravox.py

lblip2.py
