### ISSUE TITLE
[inline_inbuilt_nn_modules][cudagraphs] Large regression in llama models because cudagraph is not picked up

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#132714]
Repro

```
python benchmarks/dynamo/torchbench.py --performance --inference --bfloat16 --backend inductor --device cuda --only llama
```

This is the warning

```
cuda eval  llama
skipping cudagraphs due to mutated inputs (16 instances)
running benchmark: 100%|████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 42.86it/s]
2.147x
```

If I disable the inlining flag, the speedup goes back to 8.6x.

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @mcarilli @eellison @penguinwu @chauhang @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by mlazos** [comment]
Looks like it's just the caches again - they used to be fully internal to an NN module (and constant on the graph) but are now inputs that are getting mutated. Perhaps we should just mark them as buffers? Alternatively we could search nn modules and make all tensor attributes static for cudagraphs. I don't hace a preference one way or the other.
