### ISSUE TITLE
[doc]link error in "torch.compile "

### ISSUE THREAD

**Issue by cyk2018** [pytorch/pytorch#132725]
### 📚 The doc issue

here is the [link](https://pytorch.org/docs/stable/generated/torch.compile.html), in this documentation, the link about how to register an out-of-tree custom backend is error, you can see in the picture below:
![image](https://github.com/user-attachments/assets/e778fd28-3695-4bb2-8e89-6c859df6e04c)
So I think if someone can fix that?

**Comment by shink** [comment]
duplicate of #119272 and fixed in #125865,  the link on the [Main/Unstable doc](https://pytorch.org/docs/main/generated/torch.compile.html) is rendered properly.

**Comment by cyk2018** [comment]
> duplicate of #119272 and fixed in #125865, the link on the [Main/Unstable doc](https://pytorch.org/docs/main/generated/torch.compile.html) is rendered properly.

Thanks for your reply! I will close and wait for new version.
