### ISSUE TITLE
[DTensor] possible optimization for n-d shard-to-shard redistribution

### ISSUE THREAD

**Issue by botbw** [pytorch/pytorch#132751]
### 🚀 The feature, motivation and pitch

Hey folks, I was reading pytorch DTensor code and found that DTensor doesn't optimize shard-to-shard redistribution when using n-d device mesh.

https://github.com/pytorch/pytorch/blob/da320214e66b5af0f7db8fd18a64dbb519d17b27/torch/distributed/_tensor/_redistribute.py#L103-L124

Since one reason to use DTensor is to distribute a huge tensor among devices, this optimization seems necessary to me (and I do want it in my project). I'm wondering if there is any plan to implement this.

Any related thoughts & ideas are welcomed!

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @tianyu-l

**Comment by wanchaol** [comment]
@botbw I am working on this right now https://github.com/pytorch/pytorch/pull/131210

**Comment by botbw** [comment]
> @botbw I am working on this right now #131210

@wanchaol I roughly went through this PR and it looks quite good!

From my understanding it optimizes nested sharding like `[S(0), S(0)] -> [S(0), S(1)]`.

Besides this, do you have any plan on solving `[S(0), S(1)] -> [S(1) -> S(0)]` without gathering the entire tensor? Or even more complicated cases like `[S(0), S(0), S(1)] -> [S(0), S(1), S(2)]` (let's assume 3-d tensor and 3-d device mesh)

**Comment by wanchaol** [comment]
@botbw 

For `[S(0), S(0), S(1)] -> [S(0), S(1), S(2)]`, this PR would produce two collectives in the following steps:
1. mesh dim 2: S(1) -> S(2)
2. mesh dim 1: S(0) -> S(1)
So essentially two alltoalls

for `[S(0), S(1)] -> [S(1), S(0)]`, I think this PR would produce:

1. mesh dim 1: S1 -> R
2. mesh dim 0: S0 -> S1
3. mesh dim 1: R -> S0

It would not gathering the entire tensor, only gathering one shard dimension on one mesh dim, plus a alltoall. I think for both cases they are optimal redistribution strategies with this PR. Let me know if you think there're better strategy to perform the redistribute for these two cases :)

**Comment by botbw** [comment]
> 
> For `[S(0), S(0), S(1)] -> [S(0), S(1), S(2)]`, this PR would produce two collectives in the following steps:
> 
> 1. mesh dim 2: S(1) -> S(2)
> 2. mesh dim 1: S(0) -> S(1)
>    So essentially two alltoalls
> 


@wanchaol 

Thanks for your explanation!

I did a thorough reading and better understand the implementation now, the `[S(0), S(0), S(1)] -> [S(0), S(1), S(2)]` case looks good to me.

>
> for `[S(0), S(1)] -> [S(1), S(0)]`, I think this PR would produce:
> 
> 1. mesh dim 1: S1 -> R
> 2. mesh dim 0: S0 -> S1
> 3. mesh dim 1: R -> S0
> 
> It would not gathering the entire tensor, only gathering one shard dimension on one mesh dim, plus a alltoall. I think for both cases they are optimal redistribution strategies with this PR. Let me know if you think there're better strategy to perform the redistribute for these two cases :)
>

My point is on the latter case, the previous implementation (i.e. gather first and then split) was:

1. mesh dim 1: S1 -> R (gather)
2. mesh dim 0: S0 -> R (gather)
3. mesh dim 0: R -> S1 (split)
4. mesh dim 1: R -> S0 (split)

The current implementation, in my opinion, will fuse steps 2 and 3 into a single all-to-all.

And the same for cases (the target spec is a clockwise permutation from src spec) like:
`[S(0), S(1), S(2)] -> [S(2), S(0), S(1)]`, where only the left-most mesh dim will utilize all-to-all, and gather-then-split for other mesh dims.

For me `[S(0), S(1)] -> [S(1), S(0)]` is commonly used in 2d-SPMD parallelism, and there seems to be further optimization: a plain example is to transform a 2d square-shaped tensor, only device 1 and device 3 need to exchange their local tensor, which can be implemented using p2p, but it seems quite difficult to generalize this into current design (and it might not utilize nccl collectives).

I'm wondering if you guys had any discussions regarding this. Thanks a lot！

**Comment by botbw** [comment]
hey @wanchaol any comments on this?

**Comment by wanchaol** [comment]
@botbw sorry just saw this. Yeah I thought about this before, I think from communication amount prospective p2p might be better, however there're several implication for such a p2p:

1. This p2p optimization might not be a general optimization but rather a specific case where we found that the device 2/4 does not need to participate communication, for other redistribute cases we might not have such optimization available. There could always be some similar communication pattern that could do p2p wise optimization to save some communication volume, however usually collective performs better than p2p.
2. The more core problem on such a p2p optimization is that, it requires a global pg/device_mesh that connects device 1/3, compare to the case where the 2D device mesh wouldn't connect the device 1 and device 3 directly. a global device mesh implies an additional communicator initialization (which occupies memory). For large scale training usually a 2D device mesh is used for hierarchical communication to lower the communication cost instead of a global device mesh. i.e. one advantage of 2D SPMD parallelism is to reduce the FSDP allgather latency, so the p2p optimization might not be beneficial at large scale.

Given the above reasons I didn't pursue implementing such a optimization directly in `redistribute`.  Let me know if that make sense to you :)

**Comment by botbw** [comment]
> @botbw sorry just saw this. Yeah I thought about this before, I think from communication amount prospective p2p might be better, however there're several implication for such a p2p:
> 
> 1. This p2p optimization might not be a general optimization but rather a specific case where we found that the device 2/4 does not need to participate communication, for other redistribute cases we might not have such optimization available. There could always be some similar communication pattern that could do p2p wise optimization to save some communication volume, however usually collective performs better than p2p.
> 2. The more core problem on such a p2p optimization is that, it requires a global pg/device_mesh that connects device 1/3, compare to the case where the 2D device mesh wouldn't connect the device 1 and device 3 directly. a global device mesh implies an additional communicator initialization (which occupies memory). For large scale training usually a 2D device mesh is used for hierarchical communication to lower the communication cost instead of a global device mesh. i.e. one advantage of 2D SPMD parallelism is to reduce the FSDP allgather latency, so the p2p optimization might not be beneficial at large scale.
> 
> Given the above reasons I didn't pursue implementing such a optimization directly in `redistribute`. Let me know if that make sense to you :)

@wanchaol Never mind! Thanks for the insightful explanation.

Yuh this case is a bit misleading, device 2/4 might still communicate when tensor/mesh shape is not square. 

I think this p2p still can be generalized as long as each rank knows to which peer it needs to send/recv corresponding chunk. As you said, there are always similar ways to reduce communication volume (and we can always do N-D interval intersection to find the solution).

Theoretically, I agree that collectives should perform better than p2p. However, I implemented shard-to-shard (i.e. no `Partial()` involved) transformation with `batch_isend_irecv`, and ran a simple benchmark on a single node with NV8 fully connected (but I only utilized the last 4 devices). Somehow it indicates p2p is faster in a lot of cases.

Hope this benchmark makes sense, please correct me if I missed any sync or wrongly benched it.
```python3
from time import time

import torch
import torch.distributed as dist
from torch.distributed.device_mesh import DeviceMesh
from torch.distributed._tensor import distribute_tensor
from torch.distributed._tensor.placement_types import Shard, Replicate

# my implementation for shard-to-shard transform using P2P ops
from torch.distributed._tensor._redistribute import Partition

device_mesh = DeviceMesh('cuda', torch.arange(4).reshape(2, 2))
global_tensor = torch.randn(16, 8192, 4096).cuda()
rank = dist.get_rank()
runs = 100

def bench(src_placement, tgt_placement):
    src_dtensor = distribute_tensor(global_tensor, device_mesh) # replicate from rank 0
    src_dtensor = src_dtensor.redistribute(device_mesh, src_placement)

    start_t = time()
    torch.cuda.reset_max_memory_allocated()
    torch.cuda.synchronize()
    for _ in range(runs):
        tgt_dtensor = src_dtensor.redistribute(device_mesh, tgt_placement)
    torch.cuda.synchronize()
    dist.barrier()
    rule_time = time() - start_t
    rule_mem = torch.cuda.max_memory_allocated()

    # my p2p impl
    src_partitions = Partition.from_tensor_spec(src_dtensor._spec)
    tgt_partitions = Partition.from_tensor_spec(tgt_dtensor._spec)
    send_ops, recv_ops, recv_buffer, recv_slices = Partition.gen_p2p_op(rank, src_dtensor._local_tensor, src_partitions, tgt_partitions)

    start_t = time()
    torch.cuda.reset_max_memory_allocated()
    torch.cuda.synchronize()
    for _ in range(runs):
        works = dist.batch_isend_irecv(send_ops + recv_ops)
        for work in works:
            work.wait()
        recv_buffer = Partition.fill_recv_buffer(recv_ops, recv_buffer, recv_slices)
    torch.cuda.synchronize()
    dist.barrier()
    p2p_time = time() - start_t
    p2p_mem = torch.cuda.max_memory_allocated()
    assert recv_buffer.data is not tgt_dtensor._local_tensor.data
    assert torch.allclose(recv_buffer, tgt_dtensor._local_tensor)
    if rank == 0:
        print(f"============================{src_dtensor._spec} -> {tgt_dtensor._spec}================================")
        print(f"Rule based time: {rule_time}, max memory: {rule_mem / 1024**2} MB")
        print(f"P2P based time: {p2p_time} max memory: {p2p_mem / 1024**2} MB")
        print("Is P2P better? time: " + ("✅" if p2p_time < rule_time else "❌") + " mem: " + ("✅" if p2p_mem < rule_mem else "❌"))

if __name__ == "__main__":
    # choices = [Replicate(), Shard(0), Shard(1), Shard(2)]
    # for a in choices:
    #     for b in choices:
    #         for c in choices:
    #             for d in choices:
    #                 bench([a, b], [c, d])
    # exit()

    bench([Shard(0), Shard(0)], [Replicate(), Replicate()])
    bench([Replicate(), Replicate()], [Shard(0), Shard(0)])

    bench([Shard(0), Replicate()], [Shard(1), Replicate()])
    bench([Shard(1), Replicate()], [Shard(0), Replicate()])

    bench([Shard(0), Shard(1)], [Shard(2), Shard(1)])
    bench([Shard(2), Shard(1)], [Shard(0), Shard(1)])

    bench([Shard(0), Shard(1)], [Replicate(), Replicate()])
    bench([Replicate(), Replicate()], [Shard(0), Shard(1)])

    bench([Shard(0), Shard(1)], [Shard(1), Shard(0)])
    bench([Shard(1), Shard(0)], [Shard(0), Shard(1)])

    bench([Shard(0), Shard(0)], [Shard(0), Shard(1)])
    bench([Shard(0), Shard(1)], [Shard(0), Shard(0)])

    bench([Shard(0), Shard(0)], [Shard(1), Shard(1)])
    bench([Shard(1), Shard(1)], [Shard(0), Shard(0)])

    bench([Shard(0), Shard(1)], [Shard(1), Shard(2)])
    bench([Shard(1), Shard(2)], [Shard(0), Shard(1)])

```
```
============================Spec((Shard(dim=0), Shard(dim=0)) on (16, 8192, 4096)) -> Spec((Replicate(), Replicate()) on (16, 8192, 4096))================================
Rule based time: 1.7594575881958008, max memory: 7680.0 MB
P2P based time: 2.8946661949157715 max memory: 6656.0 MB
Is P2P better? time: ❌ mem: ✅
============================Spec((Replicate(), Replicate()) on (16, 8192, 4096)) -> Spec((Shard(dim=0), Shard(dim=0)) on (16, 8192, 4096))================================
Rule based time: 0.1509406566619873, max memory: 4096.0 MB
P2P based time: 0.003701925277709961 max memory: 3072.00048828125 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=0), Replicate()) on (16, 8192, 4096)) -> Spec((Shard(dim=1), Replicate()) on (16, 8192, 4096))================================
Rule based time: 1.3267695903778076, max memory: 7168.0 MB
P2P based time: 0.6685240268707275 max memory: 5120.0 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=1), Replicate()) on (16, 8192, 4096)) -> Spec((Shard(dim=0), Replicate()) on (16, 8192, 4096))================================
Rule based time: 0.4367058277130127, max memory: 6144.0 MB
P2P based time: 0.7106375694274902 max memory: 5632.0 MB
Is P2P better? time: ❌ mem: ✅
============================Spec((Shard(dim=0), Shard(dim=1)) on (16, 8192, 4096)) -> Spec((Shard(dim=2), Shard(dim=1)) on (16, 8192, 4096))================================
Rule based time: 0.2787134647369385, max memory: 4608.0 MB
P2P based time: 0.17150497436523438 max memory: 3840.0 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=2), Shard(dim=1)) on (16, 8192, 4096)) -> Spec((Shard(dim=0), Shard(dim=1)) on (16, 8192, 4096))================================
Rule based time: 0.23536324501037598, max memory: 4096.0 MB
P2P based time: 0.19201302528381348 max memory: 3840.0 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=0), Shard(dim=1)) on (16, 8192, 4096)) -> Spec((Replicate(), Replicate()) on (16, 8192, 4096))================================
Rule based time: 2.3344297409057617, max memory: 7680.0 MB
P2P based time: 1.251439094543457 max memory: 8192.0 MB
Is P2P better? time: ✅ mem: ❌
============================Spec((Replicate(), Replicate()) on (16, 8192, 4096)) -> Spec((Shard(dim=0), Shard(dim=1)) on (16, 8192, 4096))================================
Rule based time: 0.15421271324157715, max memory: 4096.0 MB
P2P based time: 0.004026889801025391 max memory: 3072.00048828125 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=0), Shard(dim=1)) on (16, 8192, 4096)) -> Spec((Shard(dim=1), Shard(dim=0)) on (16, 8192, 4096))================================
Rule based time: 1.0097222328186035, max memory: 7168.0 MB
P2P based time: 0.3349571228027344 max memory: 3584.00048828125 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=1), Shard(dim=0)) on (16, 8192, 4096)) -> Spec((Shard(dim=0), Shard(dim=1)) on (16, 8192, 4096))================================
Rule based time: 1.2424981594085693, max memory: 6144.0 MB
P2P based time: 0.33040690422058105 max memory: 3584.00048828125 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=0), Shard(dim=0)) on (16, 8192, 4096)) -> Spec((Shard(dim=0), Shard(dim=1)) on (16, 8192, 4096))================================
Rule based time: 0.9776549339294434, max memory: 4608.0 MB
P2P based time: 0.1702404022216797 max memory: 3840.0 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=0), Shard(dim=1)) on (16, 8192, 4096)) -> Spec((Shard(dim=0), Shard(dim=0)) on (16, 8192, 4096))================================
Rule based time: 0.23426103591918945, max memory: 4096.0 MB
P2P based time: 0.19434595108032227 max memory: 3840.0 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=0), Shard(dim=0)) on (16, 8192, 4096)) -> Spec((Shard(dim=1), Shard(dim=1)) on (16, 8192, 4096))================================
Rule based time: 0.9357776641845703, max memory: 7168.0 MB
P2P based time: 0.31421899795532227 max memory: 3968.0 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=1), Shard(dim=1)) on (16, 8192, 4096)) -> Spec((Shard(dim=0), Shard(dim=0)) on (16, 8192, 4096))================================
Rule based time: 1.1839711666107178, max memory: 6144.0 MB
P2P based time: 0.3392918109893799 max memory: 3968.0 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=0), Shard(dim=1)) on (16, 8192, 4096)) -> Spec((Shard(dim=1), Shard(dim=2)) on (16, 8192, 4096))================================
Rule based time: 0.529163122177124, max memory: 5120.0 MB
P2P based time: 0.35140037536621094 max memory: 3840.0 MB
Is P2P better? time: ✅ mem: ✅
============================Spec((Shard(dim=1), Shard(dim=2)) on (16, 8192, 4096)) -> Spec((Shard(dim=0), Shard(dim=1)) on (16, 8192, 4096))================================
Rule based time: 1.1721892356872559, max memory: 6144.0 MB
P2P based time: 0.3926241397857666 max memory: 3840.0 MB
Is P2P better? time: ✅ mem: ✅

```

**Comment by wanchaol** [comment]
> Theoretically, I agree that collectives should perform better than p2p. However, I implemented shard-to-shard (i.e. no `Partial()` involved) transformation with `batch_isend_irecv`, and ran a simple benchmark on a single node with NV8 fully connected (but I only utilized the last 4 devices). Somehow it indicates p2p is faster in a lot of cases.

@botbw Thanks for conducting the experiments and sharing the data! It's a very interesting result! I am wondering if you plan to test it in a larger scale? iirc the major bottleneck of send/recv is that its poor scalability would show up when #GPUs goes beyond a certain scale, where when comparing with collective calls it performs worse.

Essentially if we could resolve these two problems mentioned above then I think we should add certain optimization paths to `redistribute` to improve its performance. If we could show the send/recv optimizations works better at larger scale, and resolve the "global" communicator downside that is needed when doing batch send/recv (compare to the hierarchical communicator)

**Comment by botbw** [comment]
> > Theoretically, I agree that collectives should perform better than p2p. However, I implemented shard-to-shard (i.e. no `Partial()` involved) transformation with `batch_isend_irecv`, and ran a simple benchmark on a single node with NV8 fully connected (but I only utilized the last 4 devices). Somehow it indicates p2p is faster in a lot of cases.
> 
> @botbw Thanks for conducting the experiments and sharing the data! It's a very interesting result! I am wondering if you plan to test it in a larger scale? iirc the major bottleneck of send/recv is that its poor scalability would show up when #GPUs goes beyond a certain scale, where when comparing with collective calls it performs worse.
> 
> Essentially if we could resolve these two problems mentioned above then I think we should add certain optimization paths to `redistribute` to improve its performance. If we could show the send/recv optimizations works better at larger scale, and resolve the "global" communicator downside that is needed when doing batch send/recv (compare to the hierarchical communicator)

@wanchaol Sure, that's also one of my concerns that 4 GPUs might not be enough to fully utilize collective communication, and I will perform this using larger clusters (but I guess 2 * 8 GPUs with NVLink and InfiniBand is to my best ability).

I'm not exactly sure how pytorch manipulate NCCL communicators and streams at low level and I might spend some time reading these.

I will open another issue if I believe P2P has better performance at larger scale (at least one 8-GPU node with NVLink), if not I'll simply update the conclusion here.

Again, thanks for your time and patience.
