### ISSUE TITLE
Inference cost more time when input shape changed

### ISSUE THREAD

**Issue by YeFeng1993** [pytorch/pytorch#132851]
### 🐛 Describe the bug

I run the resnet18 many times, when input shape is fixed，such as (1, 3, 800, 800), it cost about 2~3ms on RTX4090. But when shape changed each time, the inference cost about 10+ms.  

### Versions

pytorch2.4, cuda11.8, cudnn8.7

**Comment by mikaylagawarecki** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
