### ISSUE TITLE
[Memory] snapshot wrong with optimizer_state and gradient - 🤗 Transformers

### ISSUE THREAD

**Issue by AaronZLT** [pytorch/pytorch#132855]
### 🐛 Describe the bug

- Training GPT2-XL with 🤗 Transformers and 🤗 Accelerate
- Using _record_memory_history and _dump_snapshot for profiler

Training GPT2-XL with 🤗 Transformers, optimizer set to adamw_torch. Since we are using adamw, the memory of optimizer_state should be 2 times of gradient if fp32-training, or 6 times of gradient if fp16- or bf16-training. However, from the snapshot, the optimizer_state is always the 2 times of gradient, which is obviously impossible.

Reproduce
- model: GPT2-XL
- batch size: 4
- sequence length: 1024
- single GPU
- optimizer: adamw_torch
- bf16

```bash
accelerate launch benchmark.py --dataset alpaca --output_dir validate --logging_strategy steps --logging_steps 1 --save_strategy no --save_steps 100 --dataloader_num_workers 1 --remove_unused_columns False --do_train --ddp_find_unused_parameters False --overwrite_output_dir --profiler pytorch --profiler_warmup_step 3 --max_steps 5 --max_memory_MB 80000 --hard_padding True --save_total_limit 0 --num_train_epochs 2 --learning_rate 4e-4 --optim adamw_torch --per_device_train_batch_size 4 --source_max_len 512 --target_max_len 512
```
![Trace_gpt2-xl-dataset_alpaca-gpus1-bs4-seq1024-lr0 0004-linear---------bf16----_step_3_to_5](https://github.com/user-attachments/assets/a11e08f9-a9d9-493d-9621-b50297fdf8d9)

### Versions

PyTorch version: 2.2.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.2.91
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB
GPU 2: NVIDIA A800-SXM4-80GB
GPU 3: NVIDIA A800-SXM4-80GB
GPU 4: NVIDIA A800-SXM4-80GB
GPU 5: NVIDIA A800-SXM4-80GB
GPU 6: NVIDIA A800-SXM4-80GB
GPU 7: NVIDIA A800-SXM4-80GB

Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_engines_precompiled.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_graph.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_heuristic.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops.so.9.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              1
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz
Stepping:                        6
CPU MHz:                         3200.000
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5200.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-31
NUMA node1 CPU(s):               32-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.2
[pip3] triton==2.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.2                    pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by mikaylagawarecki** [comment]
cc @zdevito

**Comment by janeyx99** [comment]
Why should optim state take up 6 times of gradient in fp16- or bf16-training? If the optimizer was created with fp16/bf16 parameters and there's no additional logic to store copies of the params, then the optimizer being 2x the size of the params is expected.

Also I believe this may be a better question for the huggingface transformers repo https://github.com/huggingface/transformers as it is likely setup related.

**Comment by AaronZLT** [comment]
Sorry I made a mistake, the 2x size is expected.

> then the optimizer being 2x the size of the params is expected.

Closing this issue.
