### ISSUE TITLE
When does torch p2p communication use different NCCL streams?

### ISSUE THREAD

**Issue by Edenzzzz** [pytorch/pytorch#132852]
### 🐛 Describe the bug

When using point-to-point communications, it might sometimes be desirable to schedule unrelated comm calls on different streams, e.g. in the backward of Ring attention.
Based on this example(https://github.com/InternLM/InternEvo/blob/f2949df89c15e1c16b6d48412ae9f94122ef463d/internlm/model/ops/ring_flash_attn/zigzag_ring_flash_attn_with_sliding_window.py#L196), I profiled to see 3 NCCL streams for p2p comms matching `local_dkv_comm`, `local_kv_comm` and `dkv_comm`
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/248e1cd5-7aad-49d3-aaa6-2e879bdcf6c3">

However I can't reproduce this behavior elsewhere with multiple process groups.

### Versions

PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.19 (main, May  6 2024, 19:43:03)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-169-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H800
GPU 1: NVIDIA H800
GPU 2: NVIDIA H800
GPU 3: NVIDIA H800
GPU 4: NVIDIA H800
GPU 5: NVIDIA H800
GPU 6: NVIDIA H800
GPU 7: NVIDIA H800

Nvidia driver version: 550.54.15
cuDNN version: Probably one of the following:
/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      52 bits physical, 57 bits virtual
CPU(s):                             192
On-line CPU(s) list:                0-191
Thread(s) per core:                 2
Core(s) per socket:                 48
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              143
Model name:                         Intel(R) Xeon(R) Platinum 8468
Stepping:                           8
CPU MHz:                            799.999
CPU max MHz:                        3800.0000
CPU min MHz:                        800.0000
BogoMIPS:                           4200.00
Virtualization:                     VT-x
L1d cache:                          4.5 MiB
L1i cache:                          3 MiB
L2 cache:                           192 MiB
L3 cache:                           210 MiB
NUMA node0 CPU(s):                  0-47,96-143
NUMA node1 CPU(s):                  48-95,144-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid cldemote movdiri movdir64b md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] galore-torch==1.0
[pip3] numpy==1.25.2
[pip3] pytorch-lightning==1.6.5
[pip3] tensorboard-pytorch==0.7.1
[pip3] torch==2.1.0+cu118
[pip3] torch-tb-profiler==0.4.3
[pip3] torchaudio==2.1.0+cu118
[pip3] torchmetrics==1.4.0.post0
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] galore-torch              1.0                      pypi_0    pypi
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.8            py39h5eee18b_0  
[conda] mkl_random                1.2.4            py39hdb19cb5_0  
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] numpy-base                1.26.4           py39hb5e798b_0  
[conda] pytorch                   2.1.1           py3.9_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-lightning         1.6.5                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] tensorboard-pytorch       0.7.1                    pypi_0    pypi
[conda] torch                     2.1.0+cu118              pypi_0    pypi
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchaudio                2.1.0+cu118              pypi_0    pypi
[conda] torchmetrics              1.4.0.post0              pypi_0    pypi
[conda] torchtriton               2.1.0                      py39    pytorch
[conda] torchvision               0.16.0+cu118             pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by awgu** [comment]
cc: @wconstab

**Comment by wconstab** [comment]
ProcessgroupNCCL creates its own streams and uses those for communication. 

Collective operations are immortal straightforward- one stream per pg and it's used for all collectives of that PG.

P2P ops are special- a key is formed as "{src_rank}:{dst_rank}" and a different stream is used per key. So a send to rank1 would share a stream with a recv from rank1, but should be concurrent with a send to rank2. (Assuming you do all of this from one pg.

**Comment by Edenzzzz** [comment]
@wconstab Thanks for your explaination. Does that mean we can force concurrency by creating multiple process groups?
For example, I see 3 streams with the following snippet.
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/5fbff237-9602-4711-8c38-e8f4343970f0">
```
import torch
import torch.multiprocessing as mp
import torch.distributed as dist
import os
from torch.profiler import schedule, ProfilerActivity, tensorboard_trace_handler
class RingComm:
    """
    P2P communicator for double ring zigzag flash attn.
    """

    def __init__(self, process_group: dist.ProcessGroup):
        self._process_group = process_group
        self._ops = []
        self.rank = dist.get_rank(self._process_group)
        self.world_size = dist.get_world_size(self._process_group)
        self._reqs = None

        self.send_rank = (self.rank + 1) % self.world_size
        self.recv_rank = (self.rank - 1) % self.world_size

        if process_group is not None:
            self.send_rank = dist.get_global_rank(self._process_group, self.send_rank)
            self.recv_rank = dist.get_global_rank(self._process_group, self.recv_rank)
            # print(f'rank:{self.rank},send_rank:{self.send_rank},recv_rank:{self.recv_rank}')

    def send_recv(self, to_send: torch.Tensor, recv_tensor: torch.Tensor = None) -> torch.Tensor:
        if recv_tensor is None:
            res = torch.empty_like(to_send)
        else:
            res = recv_tensor

        send_op = dist.P2POp(dist.isend, to_send, self.send_rank, group=self._process_group)
        recv_op = dist.P2POp(dist.irecv, res, self.recv_rank, group=self._process_group)
        self._ops.append(send_op)
        self._ops.append(recv_op)
        return res

    def commit(self):
        if self._reqs is not None:
            raise RuntimeError("commit called twice")
        self._reqs = dist.batch_isend_irecv(self._ops)

    def wait(self):
        if self._reqs is None:
            raise RuntimeError("wait called before commit")
        for req in self._reqs:
            req.wait()
        self._reqs = None
        self._ops = []

def init_process_group(rank=0, world_size=1):
    dist.init_process_group(backend='nccl', rank=rank, world_size=world_size)
    

def run_test(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'  # or the IP of the master node
    os.environ['MASTER_PORT'] = '8125'       # make sure this port is free
    init_process_group(rank, world_size)
    bs, seqlen, head_num, head_dim = 4, 4096, 32, 128
    
    qkv = torch.randn(bs, seqlen, 3, head_num, head_dim, device=f'cuda:{rank}', requires_grad=True, dtype=torch.bfloat16)
    groups = [dist.new_group() for _ in range(3)]
    with torch.profiler.profile(
            record_shapes=True,
            with_stack=True,
            with_modules=True,
            activities=[
                ProfilerActivity.CPU,
                ProfilerActivity.CUDA,
            ],
            on_trace_ready=torch.profiler.tensorboard_trace_handler("test"),
            schedule=schedule(wait=0, warmup=1, active=3)
    ) as prof:
        for i in range(5):      
            comm1 = RingComm(groups[0])
            comm2 = RingComm(groups[1])
            comm3 = RingComm(groups[2])
            tensor1 = comm1.send_recv(qkv)
            comm1.commit()
            tensor2 = comm2.send_recv(qkv)
            comm2.commit()
            tensor3 = comm3.send_recv(qkv)
            comm3.commit()
            
            comm1.wait()
            comm2.wait()
            comm3.wait()
            prof.step()
            
if __name__ == "__main__":
    world_size = 4
    mp.spawn(run_test, args=(world_size,), nprocs=world_size, join=True)
```

**Comment by Edenzzzz** [comment]
Could you plz point to the source code for P2P stream selection?

**Comment by wconstab** [comment]
I think there may be a difference for stream selection with 'coalesced' send/recv ops.  In that case, you're asking NCCL/CUDA to internally manage concurrency - it may run the send and recv at the same time but that looks like one big operation to us.  I think you're hitting this code, so you're not using the special send/recv key.
<img width="738" alt="image" src="https://github.com/user-attachments/assets/77be631e-facb-41f7-afbf-806ad9889fe0">

You should be able to get around this by using a separate pytorch processgroup.  However, i'm not sure if you'll get the expected throughput gains.  Your best bet if you're already using batching might be to put all the ops you want to parallelize into the same batch, so nccl/cuda manages concurrency itself.

**Comment by Edenzzzz** [comment]
@wconstab Thanks for your reply. I saw a throughput gain from 1.8 ms (seralized) to 1.4 ms with 2 streams running concurrently. However, it also incurs risks of throwing `Software caused connection abort`. So indeed your suggestion is right
<img width="622" alt="image" src="https://github.com/user-attachments/assets/4e7ce6d6-f693-42bb-add9-ef4fa0c3f6e7">
