### ISSUE TITLE
Mode to build with asserts turned off

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#13281]
Right now, we always build all builds, even optimized production builds, with asserts turned on. Asserts are not free, and can affect performance (even though most of our asserts are "cheap" checks, they add up.) We should be able to build with asserts turned off. Even better: distribute ABI-compatible `libtorch.so` and `libtorch_debug.so`, the latter of which has asserts enabled.

**Comment by ngimel** [comment]
This is done
