### ISSUE TITLE
[ROCm] Do not recognize AMD gpus without container

### ISSUE THREAD

**Issue by oraluben** [pytorch/pytorch#132987]
### 🐛 Describe the bug

On host with amd gpu:

```
$ pip3 install torch --index-url https://download.pytorch.org/whl/rocm6.1
...
$ python -c 'import torch; torch._C._cuda_init()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: No HIP GPUs are available
```

on any docker image, e.g. `docker run -ti --rm --device /dev/dri --device /dev/kfd --network host --ipc host --group-add video --cap-add SYS_PTRACE --privileged --security-opt seccomp=unconfined ubuntu:22.04` on same machine

```
$ python -c 'import torch; torch._C._cuda_init()'
amdgpu.ids: No such file or directory
amdgpu.ids: No such file or directory
amdgpu.ids: No such file or directory
amdgpu.ids: No such file or directory
amdgpu.ids: No such file or directory
amdgpu.ids: No such file or directory
amdgpu.ids: No such file or directory
amdgpu.ids: No such file or directory
$ 
```

Note that it works in any docker container (not only `rocm/pytorch`), and the warning message seems to indicate that https://github.com/pytorch/builder/commit/f11c877326cebb2c0bc7aef3a78450fee5dd3bf1 is not working as expected.

### Versions

Collecting environment information...
PyTorch version: 2.4.0+rocm6.1
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 6.1.40091-a8dbc0c19

OS: Alibaba Cloud Linux release 3 (Soaring Falcon)  (x86_64)
GCC version: (GCC) 10.2.1 20200825 (Alibaba 10.2.1-3.8 2.32)
Clang version: 15.0.7 ( 15.0.7-1.0.3.al8)
CMake version: version 3.26.5
Libc version: glibc-2.32

Python version: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.134-16.3.al8.x86_64-x86_64-with-glibc2.32
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              192
On-line CPU(s) list: 0-191
Thread(s) per core:  2
Core(s) per socket:  48
Socket(s):           2
NUMA node(s):        4
Vendor ID:           GenuineIntel
CPU family:          6
Model:               207
Model name:          INTEL(R) XEON(R) PLATINUM 8575C
Stepping:            2
CPU MHz:             3193.702
CPU max MHz:         4000.0000
CPU min MHz:         800.0000
BogoMIPS:            5600.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            2048K
L3 cache:            327680K
NUMA node0 CPU(s):   0-23,96-119
NUMA node1 CPU(s):   24-47,120-143
NUMA node2 CPU(s):   48-71,144-167
NUMA node3 CPU(s):   72-95,168-191
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm uintr md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] pytorch-triton-rocm==3.0.0
[pip3] torch==2.4.0+rocm6.1
[conda] pytorch-triton-rocm       3.0.0                    pypi_0    pypi
[conda] torch                     2.4.0+rocm6.1            pypi_0    pypi

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
Does `rocminfo` work outside the container?

**Comment by oraluben** [comment]
> Does `rocminfo` work outside the container?

`rocminfo` works with sudo, and so does pytorch. Is that expected?

**Comment by hongxiayang** [comment]
If you want to install pytorch wheels (`pip3 install torch --index-url https://download.pytorch.org/whl/rocm6.1`) with a base container, can try to use `rocm/dev-ubuntu-22.04:6.1` tag instead of `ubuntu:22.04` ? That would give you the rocm installation inside the container.
