### ISSUE TITLE
[FSDP2] model.parameter() should be DTensor for replicate(fully_shard)

### ISSUE THREAD

**Issue by weifengpy** [pytorch/pytorch#132978]
### 🚀 The feature, motivation and pitch

I was adding `reset_sharded_param` to `lazy_init` but hit CI error https://github.com/pytorch/pytorch/pull/132954

`pytest -s test/distributed/_composable/fsdp/test_fully_shard_comm.py -k test_unshard_async`

I minimized repo below and it became a replicate/fully_shard question

we use DDP at root model, `replicate(model.cuda())`. Inside root model, we use FSDP2 for a submodule, `fully_shard(model.linears)`. Before the forward, we have `model.linears[0].weight` in `DTensor`. Inside root forward but before `model.linears[0].forward`,  we have `model.linears[0].weight` in `torch.Tensor` (unsharded)

that's why it errors out by calling `.unshard()` -> `lazy_init` -> `reset_sharded_param`. `reset_sharded_param` assumes it's DTensor and access `._local_tensor` but found there is no such attribute

```
class TestFullyShardUnshardMultiProcess(FSDPTest):
    @property
    def world_size(self) -> int:
        return min(torch.cuda.device_count(), 2)

    @skip_if_lt_x_gpu(2)
    def test_unshard_async(self):
        class ToyModel(nn.Module):
            def __init__(self, dim: int):
                super().__init__()
                self.linears = nn.Sequential(nn.Linear(dim, dim, bias=False), nn.Linear(dim, dim, bias=False), nn.Linear(dim, dim, bias=False))
                self.proj = nn.Linear(dim, dim, bias=False)

            def forward(self, x: torch.Tensor):
                assert isinstance(self.linears[0].weight.data, DTensor), f"{type(self.linears[0].weight.data)=}"
                y = self.linears(x)
                y = self.proj(y)
                return y

        batch_size, dim = 2, 8
        torch.manual_seed(42)
        model = ToyModel(dim)
        fully_shard(model.linears[0])
        fully_shard(model.linears[1])
        fully_shard(model.linears[2])
        fully_shard(model.linears)
        replicate(model.cuda())
        torch.manual_seed(42 + self.rank + 1)
        inp = torch.randn((batch_size, dim), device="cuda")
        self.assertTrue(isinstance(model.linears[0].weight.data, DTensor))
        model(inp).sum()
```

**Comment by awgu** [comment]
left a possible fix on the PR

**Comment by weifengpy** [comment]
reopen since it's still a quesiton of DDP(FSDP) - whether DDP should "unshard" parameters before FSDP's unshard https://github.com/pytorch/pytorch/pull/132954#discussion_r1710269190

**Comment by weifengpy** [comment]
fixed in https://github.com/pytorch/pytorch/pull/133059 credit to @awgu
