### ISSUE TITLE
Tensom.sum() is our of memory for unknown reason

### ISSUE THREAD

**Issue by vborees** [pytorch/pytorch#13296]
## 🐛 Bug

In attempt to compute confusion matrix for my classifier, I ended up with code like this:
        a1 = (self.pred_class==x[:,None])
        print(a1.shape)
        a2 = (self.y_true==x[:,None,None])
        print(a2.shape)
        a3 = a1 & a2
        print(a3.shape)
        cm = a3.sum(2)

print functions output:
         torch.Size([340, 74498])
         torch.Size([340, 1, 74498])
         torch.Size([340, 340, 74498])

however .sum(2) causing error:
         RuntimeError: $ Torch: not enough memory: you tried to allocate 64GB. Buy new RAM! at /opt/conda/conda-bld/pytorch-nightly_1540719301766/work/aten/src/TH/THGeneral.cpp:204

## To Reproduce

1. Create random tensors of size above
1. run the code above to get an Error

## Expected behavior

PyTorch version: 1.0.0.dev20181028
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Amazon Linux AMI 2018.03
GCC version: (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 396.44
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so.7.1.4
/usr/local/cuda-9.0/lib64/libcudnn_static.a
/usr/local/cuda-9.1/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.1/lib64/libcudnn_static.a
/usr/local/cuda-9.2/lib64/libcudnn.so.7.1.4
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py36_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
[conda] pytorch-nightly           1.0.0.dev20181028 py3.6_cuda9.2.148_cudnn7.1.4_0  [cuda92]  pytorch
[conda] torch                     0.3.1                     <pip>
[conda] torchtext                 0.2.3                     <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch
[conda] torchvision               0.2.1                     <pip>
[conda] torchvision-nightly       0.2.1                      py_0    fastai

**Comment by colesbury** [comment]
It would be nice to fix this, although it isn't new. Summing a ByteTensor first converts it to a LongTensor. 340*340*74498*8 bytes = 64 GB.

**Comment by vborees** [comment]
> It would be nice to fix this, although it isn't new. Summing a ByteTensor first converts it to a LongTensor. 340_340_74498*8 bytes = 64 GB.

I would be more than happy to fix it. I need some minor guidance, since I am new to c->python code. Could you point me to sum() implementation - where is the corresponding C code?

**Comment by soumith** [comment]
I think @tugrulates is adding type-promotion etc., and possibly fixing this in the process as well (not sure if this particular fix is included).

**Comment by tugrulates** [comment]
Type promotion work will formalize the type change `sum()` is currently doing on an ad-hoc basis.

For ops using TensorIterator, the casting can be pushed to inside the loop to avoid extra memory allocation. Since `sum` is using TensorIterator it will be covered with this optimization.

**Comment by ngimel** [comment]
Closing due to age
