### ISSUE TITLE
[jit] cannot print graph for traced module with parameters

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#13299]
## Hybrid 🐛 Bug or 🚀Feature Request

Cannot print graph for traced module

## To Reproduce

```python
import torch
import torch.jit

class MiniModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.p = torch.nn.Parameter(torch.randn(1))
        
    def forward(self, x):
        return self.p * x

x = torch.randn(1)

model = MiniModule()
traced_script_module = torch.jit.trace(model, x)

print(traced_script_module.graph_for(x))
```

This gives a runtime error with traceback.

## Expected behavior

Print a graph.

## Environment

Master from yesterday.

## Additional context

Apparently the graph_for does not handle the parameters of the traced module. Tracing a module without parameters works, but many modules do have parameters.

**Comment by zou3519** [comment]
Fixed by #13553
