### ISSUE TITLE
SpatialFullConvolution has no attribute 'bias' error on loading lua-torch model in pytorch using load_lua

### ISSUE THREAD

**Issue by aszenz** [pytorch/pytorch#13302]
## 🐛 Bug
Passing a .t7 lua-torch model to _torch.utils.serialization.load_lua_ gives the following error:
In _torch/legacy/nn/SpatialFullConvolution.py_
`AttributeError: 'SpatialFullConvolution' object has no attribute 'bias'`

## To Reproduce
The model I am passing is a pretrained DGAN generator with CPU weights from the following repo:
[DGAN](https://github.com/robbiebarrat/art-DCGAN)

## Expected behavior
The lua-torch model should have loaded in pytorch.

## Environment
```
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 396.44
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

**Comment by soumith** [comment]
after 0.4.1, we removed support for loading legacy lua models, and the functionality is no longer present.

Hence, we dont expect to fix this, ever.

I'll mark the issue as `wontfix` and close.

**Comment by Amir-Arsalan** [comment]
@aszenz  I would say use PyTorch 0.4.1 and use [this repo](https://github.com/clcarwin/convert_torch_to_pytorch) to convert your Lua Torch model to PyTorch model, not just the `torch.nn.legacy` model. Then use PyTorch 1.xx to do whatever with it. You can also train your converted Lua Torch models in PyTorch this way :)
