### ISSUE TITLE
Can't build pytorch with XPU support

### ISSUE THREAD

**Issue by YarShev** [pytorch/pytorch#133089]
### 🐛 Describe the bug

I am trying to build latest pytorch main with XPU support but am getting this error.

```bash
source /opt/intel/oneapi/setvars.sh
export USE_XPU=1
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git submodule sync
git submodule update --init --recursive
python setup.py develop
```

```bash
CMake Error at third_party/kineto/libkineto/src/plugin/xpupti/CMakeLists.txt:23 (find_package):
  By not providing "FindPti.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Pti", but
  CMake did not find one.

  Could not find a package configuration file provided by "Pti" with any of
  the following names:

    PtiConfig.cmake
    pti-config.cmake

  Add the installation prefix of "Pti" to CMAKE_PREFIX_PATH or set "Pti_DIR"
  to a directory containing one of the above files.  If "Pti" provides a
  separate development package or SDK, be sure it has been installed.
```

### Versions

* Top of the PyTorch main branch
* Top of the intel-xpu-backend-for-triton llvm-target branch

cc @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by YarShev** [comment]
After installing intel-pti-dev, build seems to be working. Is this expected behavior that users have to install pti beforehand?

**Comment by guangyey** [comment]
Yes, it is expected.

**Comment by YarShev** [comment]
@guangyey, should this be documented somewhere in pytorch documentation?

**Comment by guangyey** [comment]
Yes, you can refer to [this doc](https://github.com/pytorch/pytorch?tab=readme-ov-file#intel-gpu-support)

**Comment by uniartisan** [comment]
> @guangyey, should this be documented somewhere in pytorch documentation?

Hi, you can try:
```
source /opt/intel/oneapi/pytorch-gpu-dev-0.5/oneapi-vars.sh
```

This error was introduced by kineto, and I believe this command hasn't properly set up the CMake path for PTI:
source /opt/intel/oneapi/pytorch-gpu-dev-0.5/oneapi-vars.sh

**Comment by EikanWang** [comment]
Thanks for @uniartisan comments. Beyond @uniartisan 's solution, @YarShev you can source `/opt/intel/oneapi/pti/latest/env/vars.sh` as like the doc described.

https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html

**Comment by EikanWang** [comment]
@YarShev , could you check if the solutions above can address the issue?

**Comment by EikanWang** [comment]
@YarShev , I will close this issue, and please open it if the issue cannot be fixed by either @uniartisan 's suggestion or the steps described in the doc.

**Comment by BenBrock** [comment]
Is there another way to get this `pti` package other than the the APT package?  I want to compile the upstream PyTorch support on an internal Intel system where I don't have root/Docker, just the standard oneAPI packages, and I'm running into this same issue.

**Comment by ZhaoqiongZ** [comment]
Hi @BenBrock , you can have a try with latest nightly v2.6/v2.7 version.
No need to manually install pytorch-bundle and pti anymore.
The required package will be installed as dependencies while install torch.  preview get start can be found at  https://docs-preview.pytorch.org/pytorch/pytorch/143183/notes/get_start_xpu.html
