### ISSUE TITLE
Request for Mirroring PyTorch Official WHL Repository

### ISSUE THREAD

**Issue by 89ao** [pytorch/pytorch#133167]
### 🚀 The feature, motivation and pitch

As avid users and contributors to the field of machine learning, we have long admired the innovation and community spirit that PyTorch embodies.

We have observed that users from the China region often experience slow access speeds when downloading PyTorch WHL packages from the official source. To address this issue and enhance the user experience for this significant segment of the global community, we are interested in mirroring the PyTorch WHL repository at https://download.pytorch.org/whl/.

Our goal is to provide a free and open service to all internet users, with the aim of improving access speeds specifically for those located in China. We believe this initiative will not only benefit our local user base but also support the PyTorch community's global reach and accessibility.

We seek your guidance and approval on the following matters:

Mirroring Authorization: Would it be permissible for us to mirror and distribute the WHL packages available on your platform? If so, could you please outline any specific terms or conditions we need to comply with?

Synchronization Process: We are eager to understand the process of syncing with your repository, including the frequency of updates, recommended tools or methods, and any particular synchronization protocols.

Communication Channels: To ensure we are well-informed about updates and changes, we wish to establish a reliable line of communication with your team. Could you suggest the best way to maintain this ongoing dialogue?

Technical Support: We anticipate needing some level of technical support during the setup and operation of the mirror. Would it be possible to receive assistance or direction from your team?

We are excited about the prospect of collaborating with the PyTorch official team to enhance the global user experience. We are committed to aligning our efforts with the community's values and look forward to contributing to the wider PyTorch ecosystem.

Thank you for considering our request. We are open to providing any additional information and are eager for the opportunity to discuss this matter further.

cc @seemethere @malfet @osalpekar @atalman

**Comment by janeyx99** [comment]
Related: https://github.com/pytorch/pytorch/issues/128940

**Comment by 89ao** [comment]
Thanks to @qqaatw.  Unfortunately, the slow access speed to pypi.org in the Chinese region is a universal-wide issue, and as a downstream, we simply could not  explain the necessity. We can only try to find ways to accelerate it specifically, which is why this discussion has arisen.

**Comment by malfet** [comment]
I suggest to close this one as a duplicate https://github.com/pytorch/pytorch/issues/128940 and continue discussion there. download.pytorch.org is publicly accessible, so anyone is free to set up a mirror.

To answer some of the raised questions:
> Mirroring Authorization: Would it be permissible for us to mirror and distribute the WHL packages available on your platform? If so, could you please outline any specific terms or conditions we need to comply with?

Anyone can setup a mirror of PyTorch binaries per https://github.com/pytorch/pytorch/blob/8d404581fccae251a6b8c09744f9643f38ad94c9/LICENSE#L58-L60

> Synchronization Process: We are eager to understand the process of syncing with your repository, including the frequency of updates, recommended tools or methods, and any particular synchronization protocols.

Depends on whether you want to mirror just releases (which happen roughly 10 times a year, see https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-cadence)  or nightly builds (that happens every day).

As for recommended tools, I don't have a good advice, but as I've mentioned, download.pytorch.org is backed by publicly accessible s3://pytorch bucket, and I guess [`aws s3 sync`](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) could be used to sync changes to that bucket.


> Communication Channels: To ensure we are well-informed about updates and changes, we wish to establish a reliable line of communication with your team. Could you suggest the best way to maintain this ongoing dialogue?

PyTorch team reviews all incoming github issues, but there are also a Slack channel.

> Technical Support: We anticipate needing some level of technical support during the setup and operation of the mirror. Would it be possible to receive assistance or direction from your team?

There are no technical support team at PyTorch, and software we built is provided as-is, but you can ask question on https://discuss.pytorch.org/, PyTorch slack channel or via email.

**Comment by 89ao** [comment]
thanks @malfet! this [pytorch/LICENSE](https://github.com/pytorch/pytorch/blob/8d404581fccae251a6b8c09744f9643f38ad94c9/LICENSE#L58-L60) link is so helpful. 
For the record, we have currently synchronized the PyTorch packages to https://mirrors.tencent.com/pytorch-wheels/. If there is a possible infringement risk, we strongly request the responsible party to contact us through mirrors@tencent.com, and we will take care of it as soon as we receive it.

**Comment by malfet** [comment]
@89ao thank you for the link. I'm not sure who maintains https://pytorch.apachecn.org/ but I wonder if it'll be possible to reference the mirror there. And thank you for keeping PyTorch binaries accessible to users in China.

**Comment by 89ao** [comment]
@malfet Before raising the issue, I had already contacted the maintenance team of https://pytorch.apachecn.org/, but it seems that their main work is related to the translation of documents, so I did not get more help than you. Thank you very much and it is an honor to contribute to the open source community.
