### ISSUE TITLE
Nightly build includes absolute path in cmake file

### ISSUE THREAD

**Issue by kvnull** [pytorch/pytorch#13315]
## 🐛 Bug

The Caffe2Targets.cmake file included in the nightly builds includes the code (from the current version)

`set_target_properties(caffe2_gpu PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "caffe2::cudart;caffe2;caffe2::cufft;caffe2::curand;caffe2::cudnn;/usr/local/cuda/lib64/libculibos.a;caffe2::cublas"
)
`
The absolute link to /usr/local/cuda/lib64/libculibos.a probably causes some of the problems that are solved by compiling locally.

**Comment by zou3519** [comment]
cc @pjh5

**Comment by pjh5** [comment]
What are the problems that are solved by compiling locally that you are referring to? Why do you need CUDA in a different folder than /usr/local/cuda ?

**Comment by kvnull** [comment]
There were occasional problems with undefined symbols that I fixed by not using the nightly builds. It's been a long time since I looked at it.

Please don't make me explain how, in a corporate environment, you might have to work with atypical install paths. I can't reasonably submit a business case to change the location just to assess pytorch.

**Comment by angelo-martinovic** [comment]
To expand on @kvnull : we had similar issues in our company. The biggest problem is that the nightly builds are for some reason built with the non-default "-D_GLIBCXX_USE_CXX11_ABI=0". For us it is thus impossible to link against the pre-built libtorch binaries, because our software was built with the default (CXX11_ABI=1). The only solution was to build pytorch from source, making sure that flag is set to 1.

**Comment by pjh5** [comment]
@angelo-martinovic the nightly builds are built with this old compiler https://github.com/pytorch/builder/blob/master/manywheel/Dockerfile_80#L17 , which uses the old ABI. We use that compiler to try and keep the binaries as backwards compatible as possible.

**Comment by pjh5** [comment]
I looked into this a little and don't think it's a problem. Those libraries are only linked to statically, so the built binaries don't look for them when installed on your machine. Checking the ldd and objdump outputs on some built linux binaries confirms that there are no unexpected cuda libraries that need to be linked to
