### ISSUE TITLE
The doc `SELU()` shows a wrong SELU formula

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#133140]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.nn.SELU.html) of `SELU()` shows the wrong SELU formula as shown below:

![Screenshot 2024-08-10 080324](https://github.com/user-attachments/assets/d60aec2d-afc1-4d3d-a52f-80f057097bf0)

And, this is the correct SELU formula according to [the paper](https://arxiv.org/pdf/1706.02515) as shown below:

![Screenshot 2024-08-10 080114](https://github.com/user-attachments/assets/55466837-a843-43da-b5a4-21f432c17d4d)

**Comment by qqaatw** [comment]
I don't see any wrong here if the lambda is the scale above.

**Comment by hyperkai** [comment]
Sorry, the both formulas are the same. I misunderstood.
