### ISSUE TITLE
Missing pip install for `torch==2.4.0+cpu`

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#133128]
### 🐛 Describe the bug

Previously, `pip install --no-cache-dir --find-links https://download.pytorch.org/whl/torch_stable.html torch==2.3.1+cpu` worked to install CPU version explicitly. 

However, `pip install --no-cache-dir --find-links https://download.pytorch.org/whl/torch_stable.html torch==2.4.0+cpu` does not work. Are the whl files for 2.4 missing?

### Versions

N/A

**Comment by ZailiWang** [comment]
Hi, this link is deprecated since 2.4.

**Comment by nisarpro** [comment]
> Hi, this link is deprecated since 2.4. Please use the official installation guide instead.

Still it is not available for macosx x86 platform

**Comment by atalman** [comment]
Hi @mvpatel2000 and @nisarpro Please use official install commands from https://pytorch.org/get-started/locally/
For linux its:
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
```

**Comment by nisarpro** [comment]
This still installs torch 2.2.2 but not 2.4.0
    On Monday, August 19, 2024 at 10:41:25 PM GMT+5:30, Mihir Patel ***@***.***> wrote:  
 
 


Closing as resolved.

We previously used the command in original post for building dockerfiles for specific versions. I have now replaced it with:
        pip${PYTHON_VERSION} install --no-cache-dir --find-links https://download.pytorch.org/whl/torch/ \
            torch==${PYTORCH_VERSION}+${CUDA_VERSION_TAG}

**Comment by nisarpro** [comment]
This still installs torch 2.2.2 but not 2.4.0

**Comment by nisarpro** [comment]
python --version
Python 3.12.5

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
Collecting torch
Downloading https://download.pytorch.org/whl/cpu/torch-2.2.2-cp312-none-macosx_10_9_x86_64.whl (151.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.0/151.0 MB 11.3 MB/s eta 0:00:00
Successfully installed torch-2.2.2 torchaudio-2.2.2 torchvision-0.17.2

but not 2.4.0

**Comment by lvjing2** [comment]
me too

**Comment by leisongao2005** [comment]
I am also experiencing this issue on M2 Mac.

Tried using pip and conda, both can only install up to version 2.3.0

**Comment by lvjing2** [comment]
![image](https://github.com/user-attachments/assets/d0561f69-d0ce-4e43-8ff7-73acd3658cd8)
this maby be the reason, those list in `https://download.pytorch.org/whl/torch/` do not have the whl for you machine. 

for example, there is no whl for macos + intel version
