### ISSUE TITLE
jit, instantiating zero element tensor with device results in error

### ISSUE THREAD

**Issue by phi-go** [pytorch/pytorch#13312]
## To Reproduce

1. Example code:

```python
import torch

from torch.jit import script

@script
def zero_elem_tensor():
    return torch.empty([0], device=[0])


zero_elem_tensor()
```
Error:
`RuntimeError: elems.size() == 2 ASSERT FAILED at /pytorch/aten/src/ATen/core/ivalue.h:489, please report a bug to PyTorch. (to<at::Device> at /pytorch/aten/src/ATen/core/ivalue.h:489)`

## Expected behavior

Creates the tensor, as it does without jit: `torch.empty([0], device=torch.device('cuda'))`

## Environment

PyTorch version: 1.0.0.dev20181008
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Arch Linux
GCC version: (GCC) 8.2.1 20180831
CMake version: version 3.12.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 410.66
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

 - How you installed PyTorch (`conda`, `pip`, source): pipenv

## Additional context
I have little experience with jit.

**Comment by wanchaol** [comment]
Looks like you are missing a device index, code snippet like below works 

```
@script
def zero_elem_tensor():
    return torch.empty([0], device=[0, 0])
```

**Comment by zdevito** [comment]
The correct behavior here is to report an error:
```
TypeError: empty(): argument 'device' must be torch.device, not list
```

The JIT will need to add an actual Device type for these errors to be correct.

**Comment by phi-go** [comment]
@wanchaol Yes, can confirm.

@zdevito Since this change is already mentioned in another issue #13254. I'll close this issue.
