### ISSUE TITLE
RuntimeError: "fill_empty_deterministic_" not implemented for 'ComplexHalf'

### ISSUE THREAD

**Issue by gaoGyr** [pytorch/pytorch#133157]
### 🐛 Describe the bug

RuntimeError: "fill_empty_deterministic_" not implemented for 'ComplexHalf'

### Error logs

RuntimeError: "fill_empty_deterministic_" not implemented for 'ComplexHalf'

### Minified repro

RuntimeError: "fill_empty_deterministic_" not implemented for 'ComplexHalf'

### Versions

torch 2.2.1

cc @ezyang @chauhang @penguinwu

**Comment by ezyang** [comment]
This should be very easy to implement, good first issue

**Comment by zhanghaochenkaixin** [comment]
could you talk about how to solve this problem?

**Comment by ezyang** [comment]
grep for fill_empty_deterministic_ and add ComplexHalf case to the switch macro

**Comment by ywq880611** [comment]
Hi guys!

I drafted a [PR](https://github.com/pytorch/pytorch/pull/137488) and try to fix this issue, but it seems I didn't have access to add label for it, which block the CI process, I couldn't see whether it pass the CI or not, did I need a reviewer to help me add a label for it and then rerun CI process? PTAL, thanks!

**Comment by w-5932** [comment]
Hello, I'm having the same problem, how can I fix it?

**Comment by w-5932** [comment]
Hello, I'm having the same problem, how can I fix it?

**Comment by JeavanCode** [comment]
It seems to be an issue in the latest version. Beause when I tried to run the same code in early Aug 2024, it was still fine. But sorry I can not remember the torch version I was using.

**Comment by ywq880611** [comment]
> It seems to be an issue in the latest version. Beause when I tried to run the same code in early Aug 2024, it was still fine. But sorry I can not remember the torch version I was using.

I tried in my local latest built pytorch, it seems the bug is fixed, could you provide more info about the version you tried and a micro repro, thanks!
