### ISSUE TITLE
[Torch.Export] [OpenELM] Failed to Export OpenELM: "Pop from Empty List"

### ISSUE THREAD

**Issue by YifanShenSZ** [pytorch/pytorch#133252]
### 🐛 Describe the bug

When I was trying to export OpenELM
```
import torch

from transformers import AutoModelForCausalLM


torch_model = AutoModelForCausalLM.from_pretrained(
    "apple/OpenELM-270M-Instruct",
    torch_dtype=torch.float32,
    trust_remote_code=True,
    low_cpu_mem_usage=False,
    return_dict=False,
)
torch_model.eval()

example_inputs = (torch.zeros((1, 1), dtype=torch.int32),)
exported_program = torch.export.export(torch_model, example_inputs)
```
I was hit by
```
Traceback (most recent call last):
  File "export-openelm.py", line 16, in <module>
    exported_program = torch.export.export(torch_model, example_inputs)
  File ".../lib/python3.10/site-packages/torch/export/_trace.py", line 241, in _get_param_buffer_mapping
    param_buffer_table[dynamo_name] = param_lookup[id(dynamo_param)].pop()
IndexError: pop from empty list
```

### Versions

Tried both torch `2.3.0` and `2.4.0`, both fails

Transformers version is `4.38.2`

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @penguinwu

**Comment by pianpwk** [comment]
@YifanShenSZ Sorry we just got to this, the embedding weights seem to be not tracked properly, I'll look into this.

**Comment by pianpwk** [comment]
@YifanShenSZ if you're able to use non-strict mode export `export(strict=False)` I would recommend it while we work on this, non-strict seems to export successfully.

**Comment by pianpwk** [comment]
Also putting up https://github.com/pytorch/pytorch/pull/134500 to fix this
