### ISSUE TITLE
CMake Error: Failed to find nvToolsExt

### ISSUE THREAD

**Issue by efsotr** [pytorch/pytorch#133293]
### 🐛 Describe the bug

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.21)
project(ProjectName)

execute_process(
    COMMAND
    "python" "-c" "import torch; print(torch.utils.cmake_prefix_path)"
    OUTPUT_VARIABLE _PREFIX_PATH
    RESULT_VARIABLE PYTHON_ERROR_CODE
    ERROR_VARIABLE PYTHON_STDERR
    OUTPUT_STRIP_TRAILING_WHITESPACE)

list(APPEND CMAKE_PREFIX_PATH ${_PREFIX_PATH})
find_package(Torch REQUIRED)
```
After I run `cmake .`, I get 
```bash
CMake Error at ~/anaconda3/envs/glake/lib/python3.11/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:70 (message):
  Failed to find nvToolsExt
Call Stack (most recent call first):
  ~/anaconda3/envs/glake/lib/python3.11/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:87 (include)
  ~/anaconda3/envs/glake/lib/python3.11/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:13 (find_package)
```

It seems that [#109843 [Reland2] Update NVTX to NVTX3](https://github.com/pytorch/pytorch/pull/109843) or [#133297 Update cmake](https://github.com/pytorch/pytorch/pull/133297) may solve this problem. 

### Versions

PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.30.2
Libc version: glibc-2.31

Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-187-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.6.20
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40
GPU 2: NVIDIA A40
GPU 3: NVIDIA A40

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 57 bits virtual
CPU(s):                             112
On-line CPU(s) list:                0-111
Thread(s) per core:                 2
Core(s) per socket:                 28
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              106
Model name:                         Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz
Stepping:                           6
CPU MHz:                            2600.000
BogoMIPS:                           4000.00
Virtualization:                     VT-x
L1d cache:                          2.6 MiB
L1i cache:                          1.8 MiB
L2 cache:                           70 MiB
L3 cache:                           84 MiB
NUMA node0 CPU(s):                  0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110
NUMA node1 CPU(s):                  1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111
Vulnerability Gather data sampling: Mitigation; Microcode
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI Vulnerable, KVM SW loop
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==2.0.1
[pip3] torch==2.3.0
[pip3] triton==2.3.0
[conda] numpy                     2.0.1                    pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi

cc @malfet @seemethere @ptrblck @msaroufim

**Comment by xuhancn** [comment]
This issue is occured on my Windows dev also.
My cuda version is v12.6.

```cmd
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6 (found version "12.6")
-- The CUDA compiler identification is NVIDIA 12.6.20
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found CUDAToolkit: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/include (found version "12.6.20")
CMake Error at cmake/public/cuda.cmake:70 (message):
  Failed to find nvToolsExt
Call Stack (most recent call first):
  cmake/Dependencies.cmake:43 (include)
  CMakeLists.txt:857 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by cyyever** [comment]
It should work now on main since nvToolsExt has been replaced by nvtx3

**Comment by shermansiu** [comment]
So I guess this will work on PyTorch >=2.5.0 (or `main`) but not 2.4.1 and earlier, right?

I'm trying to build `vLLM` but I keep running into this issue.

**Comment by cyyever** [comment]
I'm not sure whether 2.5.0 would include the changes. It makes sense to try PyTorch main if you get into trouble.

**Comment by shermansiu** [comment]
I see. Currently, it seems like the structure in `site-packages` is different from the one in the repo root: how would I go from the structure of the code in `main` to that?
`python3.10/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:86 (include)`

I guess I would need to install from source using `main` so that it ends up in `site-packages` and then rebuild `vllm`, right?

**Comment by cyyever** [comment]
Remove the installed Pytorch and check the instructions from README.md for building from source.

**Comment by shermansiu** [comment]
Okay, thanks!

**Comment by efsotr** [comment]
I found a solution for using an older version of Torch on the Linux platform.
Add
```
find_package(CUDA REQUIRED)
find_library(NVTOOLSEXT_LIBRARY
             NAMES nvToolsExt
             PATH_SUFFIXES lib)

if (NVTOOLSEXT_LIBRARY)
    message(STATUS "Found nvToolsExt library: ${NVTOOLSEXT_LIBRARY}")
else()
    message(FATAL_ERROR "Could not find nvToolsExt library")
endif()
add_library(CUDA::nvToolsExt SHARED IMPORTED)
set_target_properties(CUDA::nvToolsExt PROPERTIES
 IMPORTED_LOCATION ${NVTOOLSEXT_LIBRARY}
)
```
before `find_package(Torch REQUIRED)`
