### ISSUE TITLE
error occur when I use torch.onnx.export to generate onnx model

### ISSUE THREAD

**Issue by ustczhouyu** [pytorch/pytorch#133220]
### 🐛 Describe the bug

When I use torch.onnx.export(net, (x1, x2, x3), onnx_path, opset_version=16, input_names=input_name, output_names=output_name) to convert .pkl model to onnx, if I use torch 2.3.1, cuda 11.8, _C_jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version) reports the following error:
**RuntimeError: minus_one_pos! = -1 INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1716905971873/work/torch/csrc/jit/passes/onnx/shape_type_inference.cpp":531, please report a bug to PyTorch.  There are no examples for shape_has_zero = true && minus_one_pos == -1.**
When I use torch 1.12 and cuda 11.6, it reports the error:
**Floating point exception (core dumped)**
However, when I use dynamic_axes, there is no error, but converting the resulting onnx to om model gives an error.
Can anyone help me to generate onnx model? I have been blocked on this issue for days, really appreciate anyone who can help me.

### Versions

When I use torch.onnx.export(net, (x1, x2, x3), onnx_path, opset_version=16, input_names=input_name, output_names=output_name) to convert .pkl model to onnx, if I use torch 2.3.1, cuda 11.8, _C_jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version) reports the following error:
**RuntimeError: minus_one_pos! = -1 INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1716905971873/work/torch/csrc/jit/passes/onnx/shape_type_inference.cpp":531, please report a bug to PyTorch.  There are no examples for shape_has_zero = true && minus_one_pos == -1.**
When I use torch 1.12 and cuda 11.6, it reports the error:
**Floating point exception (core dumped)**
However, when I use dynamic_axes, there is no error, but converting the resulting onnx to om model gives an error.
Can anyone help me to generate onnx model? I have been blocked on this issue for days, really appreciate anyone who can help me.

**Comment by per1cycle** [comment]
what model are you using?

**Comment by ustczhouyu** [comment]
> what model are you using, can you provide more details?
I use this open source model https://github.com/zzh-tech/InterpAny-Clearer and choose EMA-VFI configuration, please help me, thank you very much.

**Comment by per1cycle** [comment]
> > what model are you using, can you provide more details?
> > I use this open source model https://github.com/zzh-tech/InterpAny-Clearer and choose EMA-VFI configuration, please help me, thank you very much.

can you provide the code that reproduce the issue? :)

**Comment by ustczhouyu** [comment]
> > > what model are you using, can you provide more details?
> > > I use this open source model https://github.com/zzh-tech/InterpAny-Clearer and choose EMA-VFI configuration, please help me, thank you very much.
> 
> can you provide the code that reproduce the issue? :)

**Comment by ustczhouyu** [comment]
> > > what model are you using, can you provide more details?
> > > I use this open source model https://github.com/zzh-tech/InterpAny-Clearer and choose EMA-VFI configuration, please help me, thank you very much.
> 
> can you provide the code that reproduce the issue? :)



> > > what model are you using, can you provide more details?
> > > I use this open source model https://github.com/zzh-tech/InterpAny-Clearer and choose EMA-VFI configuration, please help me, thank you very much.
> 
> can you provide the code that reproduce the issue? :)

Thank you for your prompt reply, I have uploaded the code file here https://drive.google.com/drive/folders/1dyRX_bZ4Z0uNo4ftkL1EnuLEG9VNnHQy?usp=drive_link, the weight file is here https://drive.google.com/file/d/1mVC3gZVHibbwvDsw2Z1yuBkMjmDCZyG6/view?usp=drive_link, please download the weight file and put it in the checkpoint of the code file, then run python convert2onnx.py to convert pkl to onnx, then you will get the error I mentioned above, thank you. Looking forward to hearing good results from you.

**Comment by per1cycle** [comment]
> > > > what model are you using, can you provide more details?
> > > > I use this open source model https://github.com/zzh-tech/InterpAny-Clearer and choose EMA-VFI configuration, please help me, thank you very much.
> > 
> > 
> > can you provide the code that reproduce the issue? :)
> 
> > > > what model are you using, can you provide more details?
> > > > I use this open source model https://github.com/zzh-tech/InterpAny-Clearer and choose EMA-VFI configuration, please help me, thank you very much.
> > 
> > 
> > can you provide the code that reproduce the issue? :)
> 
> Thank you for your prompt reply, I have uploaded the code file here https://drive.google.com/drive/folders/1dyRX_bZ4Z0uNo4ftkL1EnuLEG9VNnHQy?usp=drive_link, the weight file is here https://drive.google.com/file/d/1mVC3gZVHibbwvDsw2Z1yuBkMjmDCZyG6/view?usp=drive_link, please download the weight file and put it in the checkpoint of the code file, then run python convert2onnx.py to convert pkl to onnx, then you will get the error I mentioned above, thank you. Looking forward to hearing good results from you.

pending access to the script you shared.

**Comment by titaiwangms** [comment]
Please test with torch.onnx.export(..., dynamo=True, report=True) using the latest torch-nightly. Attach the generated report if there is an error. Thanks!

**Comment by lix19937** [comment]
```py
    torch.onnx.export(model, (example_input, {}), file_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1612, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1138, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 677, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1956, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/symbolic_opset9.py", line 7152, in onnx_placeholder
    return torch._C._jit_onnx_convert_pattern_from_subblock(block, node, env)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1956, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/symbolic_opset11.py", line 311, in index_put
    values = symbolic_helper._reshape_helper(g, values, values_shape)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/symbolic_helper.py", line 1420, in _reshape_helper
    return g.op("Reshape", input, shape, allowzero_i=allowzero)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/jit_utils.py", line 87, in op
    return _add_op(self, opname, *raw_args, outputs=outputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/jit_utils.py", line 246, in _add_op
    node = _create_node(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/jit_utils.py", line 307, in _create_node
    _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
RuntimeError: minus_one_pos != -1 INTERNAL ASSERT FAILED at "../torch/csrc/jit/passes/onnx/shape_type_inference.cpp":531, please report a bug to PyTorch. There are no examples for shape_has_zero = true && minus_one_pos == -1.

```

**Comment by lix19937** [comment]
also https://discuss.pytorch.org/t/failing-to-export-the-swin-transformer-model-into-the-onnx-file/202588

**Comment by YixuanSeanZhou** [comment]
Hi @lix19937 , i wonder did you figure out a solution for this issue?
