### ISSUE TITLE
How to use libtorch in a c++11 project?

### ISSUE THREAD

**Issue by zhb0920** [pytorch/pytorch#133205]
### 🐛 Describe the bug

c++14_warning.h:32:2: 错误：#error This file requires compiler and library support for the forthcoming ISO C++ 2014 standard. This support is currently experimental, and must be enabled with the -std=c++1y or -std=gnu++1y compiler options.
 #error This file requires compiler and library support for the forthcoming \

### Versions
PyTorch version: 1.12.0a0+git664058f
OS: CentOS release 6.9 (Final) (x86_64)
GCC version: (GCC) 5.4.0
Clang version: 3.4.2 (tags/RELEASE_34/dot2-final)
CMake version: version 3.21.3
Libc version: glibc-2.10
在使用libtorch构建自己的工程时报错，我的工程是c++11(不可升级) ，有没有办法使用libtorch？

cc @svekars @brycebortree @jbschlosser @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
This is expected behavior: libtorch-1.12 requires c++14 compatible compiler, libtorch-2.2+ requires c++17 compatible compiler. 

Assigning to myself to update relevant documentaiton
