### ISSUE TITLE
Torch Profiler distributed info is not JSON serializable

### ISSUE THREAD

**Issue by anaprietonem** [pytorch/pytorch#133308]
### 🐛 Describe the bug

My code fails when trying to use torch profiler (https://github.com/pytorch/pytorch/blob/main/torch/profiler/profiler.py) to record memory traces in combination with torch distributed and Kineto, with the following error message:

![Screenshot 2024-08-13 at 10 08 55](https://github.com/user-attachments/assets/f904b20f-7a2b-4ab6-811b-757bef3c0e4f)

The function ` dist_info = self._get_distributed_info()`  returns a dictionary where one of the keys refer to 'pg_config'
```
        dist_info = {
            "backend": backend,
            "rank": dist.get_rank(),
            "world_size": dist.get_world_size(),
            "pg_count": dist.get_pg_count(),
            "pg_config": dist.distributed_c10d._get_all_pg_configs(),
        }
```

The problem is that the dictionary returned looks like:
`Distributed Info: {'backend': 'nccl', 'rank': 0, 'world_size': 1, 'pg_count': 2, 'pg_config': [{'pg_name': '0', 'pg_desc': 'default_pg', 'backend_config': 'cuda:nccl', 'pg_size': 1, 'ranks': [0]}, {'pg_name': '1', 'pg_desc': 'undefined', 'backend_config': 'cuda:nccl', 'pg_size': 1, 'ranks': [0]}], 'nccl_version': '2.21.5'}`
and hence it can't be serialised and the code fails in https://github.com/pytorch/pytorch/blob/9f17037e8ba7d98d8fbbcf40625fcad48c4c0b16/torch/profiler/profiler.py#L190
 
The error happens when there are more than 1 process groups, and then pg_config becomes a list of dictionaries.

### Versions

I am having this error with Pytorch 2.3 and 2.4 but the error does not happen when using 2.2 or lower 
And between those versions there was an update on the function
2.3 -> https://github.com/pytorch/pytorch/blob/97ff6cfd9c86c5c09d7ce775ab64ec5c99230f5d/torch/profiler/profiler.py#L279 
```
    def _get_distributed_info(self):
        import torch.distributed as dist

        if not dist.is_available() or not dist.is_initialized():
            return None

        backend = dist.get_backend()
        dist_info = {
            "backend": backend,
            "rank": dist.get_rank(),
            "world_size": dist.get_world_size(),
            "pg_count": dist.get_pg_count(),
            "pg_config": dist.distributed_c10d._get_all_pg_configs(),
        }
        if backend == "nccl":
            nccl_version = torch.cuda.nccl.version()
            dist_info["nccl_version"] = ".".join(str(v) for v in nccl_version)
        return dist_info

```
2.2.2 -> https://github.com/pytorch/pytorch/blob/39901f229520a5256505ec24782f716ee7ddc843/torch/profiler/profiler.py#L235
```
    def _get_distributed_info(self):
        import torch.distributed as dist

        if not dist.is_available() or not dist.is_initialized():
            return None

        return {
            "backend": dist.get_backend(),
            "rank": dist.get_rank(),
            "world_size": dist.get_world_size(),
        }
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @robieta @chaekit @aaronenyeshi @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise

**Comment by sraikund16** [comment]
I am not able to reproduce this issue. I have a basic test where I have a nccl and gloo process group and it runs just fine. However, it upon inspecting your error message it looks like the issue is because of an unexpected type

`Typeerror: Object of type int64 is not json serializable`

Is this a torch.int64 that you are seeing?

**Comment by sraikund16** [comment]
@anaprietonem Since I cannot reproduce this, I was wondering if you could print the type for each var in the dictionary so I can figure out how to serialize this dict.

**Comment by anaprietonem** [comment]
> @anaprietonem Since I cannot reproduce this, I was wondering if you could print the type for each var in the dictionary so I can figure out how to serialize this dict.

Sure, here are the types for each of the dict entries:
![Screenshot 2024-08-23 at 09 52 04](https://github.com/user-attachments/assets/bcab7927-e94f-45cf-b5fc-7d464467bbf3)
And then below the types for each of the dictionaries inside 'pg_config'
![Screenshot 2024-08-23 at 09 54 44](https://github.com/user-attachments/assets/208b3557-040e-4ec1-b74f-0dc032f63cad)

**Comment by sraikund16** [comment]
@anaprietonem It might be that the value in `ranks` within `pg_config` is of type int64. Can you try typing it or converting to int to get it to work?

**Comment by anaprietonem** [comment]
@sraikund16 thanks for your help. I did some further digging, and indeed in the second pg_group the rank item is `numpy.int64` and that's what causing the error
<img width="738" alt="Screenshot 2024-09-02 at 12 13 27" src="https://github.com/user-attachments/assets/b181e818-01d0-447c-84b8-059c8c19b4d6">

**Comment by sraikund16** [comment]
@anaprietonem thanks a lot for helping me with debug. This makes things a lot easier for me since I know exactly what type of int64 it is (it could have been a torch.int64). I'll have a fix soon!

**Comment by anaprietonem** [comment]
@sraikund16 Many thanks for the help and the fix! just wanted to confirm that I tested installed pytorch nightly version and it worked. I was wondering if you have any idea when the fix will be part of a stable release?

**Comment by sraikund16** [comment]
@anaprietonem Not sure about the release schedule is but it should be included in the next one
