### ISSUE TITLE
[CI] raw logs with color are unreadable

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#133330]
It seems like we added color to logs recently. Raw logs with colors aren't readable (see the following example). We added colors probably so that logs in the standard logviewer are nicer, but:
- sometimes I want to process the logs locally
- I am not sure how to get CI to show me logs in the logviewer of an older version of the PR,  and clicking through ghactions gets me to the raw log.

<img width="1336" alt="image" src="https://github.com/user-attachments/assets/57c4ef60-f1a3-4e28-8f98-cbfb4577313e">

To see this image:
- goto https://github.com/pytorch/pytorch/actions/runs/10359791019/job/28678363197?pr=133249
- click on "view raw logs" in the settings menu
- grep for "[31m"

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
@zou3519 not sure about the link you've posted, but this does not look like something GitHub or PT is generating.... Mind editing it?

**Comment by zou3519** [comment]
Updated the link

**Comment by clee2000** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/133517
