### ISSUE TITLE
Onnx export bugs and warnings

### ISSUE THREAD

**Issue by vince62s** [pytorch/pytorch#13335]
CUDA9.0 / Pytorch 1.0nightly20181030
According to Pytorch doc, "split" is a supported operator for onnx export.
Seems to trigger a runtime error (see at the very bottom)

Some other operators trigger warnings but one says to report a bug "ListUnpack"

Cheers.

/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator split because torch.onnx.symbolic.split does not exist
  .format(op_name, op_name))
/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py:539: UserWarning: ONNX export failed on primitive operator ListUnpack; please report a bug
  warnings.warn("ONNX export failed on primitive operator {}; please report a bug".format(op_name))
/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator std because torch.onnx.symbolic.std does not exist
  .format(op_name, op_name))
/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator expand_as because torch.onnx.symbolic.expand_as does not exist
  .format(op_name, op_name))
/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator masked_fill because torch.onnx.symbolic.masked_fill does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "pltrdy_trt.py", line 87, in <module>
    torch.onnx.export(model, (dummy_input, dummy_tgt, dummy_lengths ), 'model.onnx')
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py", line 286, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
**RuntimeError: ONNX export failed: Couldn't export operator aten::split**

Defined at:
**/usr/local/lib/python3.5/dist-packages/torch/tensor.py(293): split**
/nlp_data/MT/pytorchwork/Recipes/toy-enfr/onmt/modules/util_class.py(41): forward
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py(465): _slow_forward
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py(475): __call__
/nlp_data/MT/pytorchwork/Recipes/toy-enfr/onmt/modules/embeddings.py(203): forward
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py(465): _slow_forward
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py(475): __call__
/nlp_data/MT/pytorchwork/Recipes/toy-enfr/onmt/encoders/transformer.py(102): forward
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py(465): _slow_forward
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py(475): __call__
/nlp_data/MT/pytorchwork/Recipes/toy-enfr/onmt/models/model.py(44): forward
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py(465): _slow_forward
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py(475): __call__
/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py(200): forward
/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py(477): __call__
/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py(169): get_trace_graph
/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py(191): _trace_and_get_graph_from_model
/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py(223): _model_to_graph
/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py(280): _export
/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py(104): export
/usr/local/lib/python3.5/dist-packages/torch/onnx/__init__.py(27): export

**Comment by sf-wind** [comment]
@houseroad  feel free to reassign

**Comment by gcp** [comment]
This is broken in release, too. It's pretty annoying because the docs claim Split is supported, which is clearly false.

**Comment by gcp** [comment]
This does work in Nightly, so it was fixed at some point.

**Comment by gcp** [comment]
This appears to have been fixed in #15092.
