### ISSUE TITLE
Contributor pipeline ignores GitHub-co-authorship

### ISSUE THREAD

**Issue by 1ucian0** [pytorch/pytorch#133310]
### 🚀 The feature, motivation and pitch

Currently, [GitHub co-authorship](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) is ignored during the PR submission and merging process.

My experience is based on [a single datapoint :P](https://github.com/pytorch/pytorch/pull/133189), but it wasn't hard to find other examples where @pytorchbot ignores co-authors (like [here](https://github.com/pytorch/pytorch/commit/a9036e1cf800e0fc981470f01b0dfdeb6dc8b116) and [here](https://github.com/pytorch/pytorch/commit/a9036e1cf800e0fc981470f01b0dfdeb6dc8b116)).

Additionally, [@linux-foundation-easycla](https://github.com/apps/linux-foundation-easycla) also seems to ignore co-authors:  
![Screenshot](https://github.com/user-attachments/assets/4d31d30e-75e6-4d00-9c4d-e1fc1ae2da59)

### Alternatives

The first issue (i.e., @pytorchbot committing messages) might be fixable by adding two empty lines before the `Co-authored-by` field in [trymerge.py](https://github.com/pytorch/pytorch/blob/main/.github/scripts/trymerge.py). I don't have a suggestion for the CLA issue.

### Additional context

While co-authorship is a GitHub-specific thing, it is widely used around here and was even suggested for teamwork in the [H1 PyTorch Docathon](https://github.com/pytorch/pytorch/issues/127345).

Furthermore, co-authorship is great for community building. It encourages teamwork and mentorship, as well as fostering a culture of attribution.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Assigning to myself, as I've implemented Co-authorship recognition logic in the mergebot, and I think it preserves it, for example https://github.com/pytorch/pytorch/commit/1e9bedf6880f813b165e357cd62c8a7238789aad mentions Mikayla as Co-author, but I did not recognize it must be the very last line of the commit message for GitHub to render it correctly. Let me propose a fix...
