### ISSUE TITLE
[inductor][cpu] inductor_max_autotune models accuracy failure in 2024-08-10 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#133465]
### 🐛 Describe the bug

<p>fp32 static shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>huggingface</td>
      <td>DebertaV2ForQuestionAnswering</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>DebertaV2ForQuestionAnswering, fail_accuracy</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>jx_nest_base</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>jx_nest_base, fail_accuracy</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>swin_base_patch4_window7_224</td>
      <td>multiple</td>
      <td>X</td>
      <td>X</td>
      <td>swin_base_patch4_window7_224, KeyError: m_start</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>twins_pcpvt_base</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>twins_pcpvt_base, fail_accuracy</td>
    </tr>
  </tbody>

</table>

<p>fp32 dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>huggingface</td>
      <td>DebertaV2ForQuestionAnswering</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>DebertaV2ForQuestionAnswering, fail_accuracy</td>
    </tr>
  </tbody>

</table>

```
E0814 16:28:00.551836 56121 torch/_dynamo/utils.py:1541] RMSE (res-fp64): nan, (ref-fp64): 0.00000 and shape=torch.Size([8, 1000]). res.dtype: torch.float32, multiplier: 2.000000, tol: 0.001000
fail_accuracy
```

</table>

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>23512dbe</td>
      <td>main</td>
      <td>23512dbe</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>6ec4af6865dd884f984c9dbcb273ae26e3825481</td>
      <td>main</td>
      <td>1d1d074072ecb0aa6ca95e3f43221d2275e16d74</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.4.0a0+b3f6f51</td>
      <td>main</td>
      <td>2.4.0a0+69b2a0a</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>fea73cb</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob//weizhuoz/enable_max_autotune_for_guilty/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference accuracy **suite** **model** float32 first static/dynamic default 0 inductor_max_autotune
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/7911b7bfb770e71a87a007addb6de819ac911c4f
[huggingface-DebertaV2ForQuestionAnswering-inference-float32-dynamic-default-multiple-accuracy-crash_guilty_commit.log](https://github.com/user-attachments/files/16615956/huggingface-DebertaV2ForQuestionAnswering-inference-float32-dynamic-default-multiple-accuracy-crash_guilty_commit.log)
cc @ezyang @chauhang @penguinwu @WeizhuoZhang-intel @chuanqi129

**Comment by zxd1997066** [comment]
convnext_base fp32 statci shape default wrapper shows the same error msg, but I can not reproduce the pass status.
```
E0814 17:47:54.617337 58277 torch/_dynamo/utils.py:1541] RMSE (res-fp64): nan, (ref-fp64): 0.00000 and shape=torch.Size([8, 1000]). res.dtype: torch.float32, multiplier: 2.000000, tol: 0.001000
fail_accuracy
```

**Comment by chunyuan-w** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/133070 and https://github.com/pytorch/pytorch/pull/133073.

**Comment by zxd1997066** [comment]
The issue is fixed.
