### ISSUE TITLE
Can't export standard torchvision ResNet50 model into ONNX file

### ISSUE THREAD

**Issue by alexander-113116** [pytorch/pytorch#133555]
### 🐛 Describe the bug

I made very simple python script which loads torchvision ResNet50 model and tries to export to onnx file in two ways (torch.onnx.export and torch.onnx.dynamo_export)

```
import torch
import torch.onnx

import torchvision

torch_model = torchvision.models.detection.fasterrcnn_resnet50_fpn_v2( weights='DEFAULT') # doesn't work
#torch_model = torchvision.models.detection.fasterrcnn_mobilenet_v3_large_fpn()  # doesn't work
#torch_model = torchvision.models.segmentation.deeplabv3_resnet50() # works fine!
torch_model.eval()
torch_input = torch.randn(1, 3, 32, 32)

is_dynamo_export = True
if (is_dynamo_export):
    onnx_program = torch.onnx.dynamo_export(torch_model, torch_input)
    onnx_program.save("onnx_dynamo_export_ResNET50.onnx")        

is_common_export = True
if (is_common_export):
    torch.onnx.export(torch_model,               # model being run
                      torch_input,                         # model input (or a tuple for multiple inputs)
                      "onnx_export_ResNET50.onnx",   # where to save the model (can be a file or file-like object)
                      export_params=True,        # store the trained parameter weights inside the model file
                      opset_version=10,          # the ONNX version to export the model to
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names = ['input'],   # the model's input names
                      output_names = ['output'], # the model's output names
                      dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                                    'output' : {0 : 'batch_size'}})
```

The errors were appeared:

```
torch\onnx\_internal\exporter.py", line 1439, in dynamo_export
  raise OnnxExporterError(

torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF
```

```
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of Pad in opset 9. The sizes of the padding must be constant. Please try opset version 11. [Caused by the value '535 defined in (%535 : int[] = prim::ListConstruct(%405, %534, %405, %533, %405, %532), scope: torchvision.models.detection.faster_rcnn.FasterRCNN::
```

However, script works fine with some default torchvision models, I tested with:

```
torch_model = torchvision.models.segmentation.deeplabv3_resnet50()
```

But fails with 
```
torch_model = torchvision.models.detection.fasterrcnn_mobilenet_v3_large_fpn()
```

### Versions

PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Ti Laptop GPU
Nvidia driver version: 555.99
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2300
DeviceID=CPU0
Family=198
L2CacheSize=9728
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2300
Name=12th Gen Intel(R) Core(TM) i7-12650H
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] onnx==1.16.2
[pip3] onnxscript==0.1.0.dev20240802
[pip3] torch==2.3.1+cu121
[pip3] torchaudio==2.3.1+cu121
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.18.1
[conda] Could not collect

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @penguinwu

**Comment by justinchuby** [comment]
Please use a newer opset version as the error suggested. I recommend 17.

**Comment by alexander-113116** [comment]
Works! Thanks!
```
opset_version=17,          # the ONNX version to export the model to
```
Just for my understanding, what method for export more preffered `torch.onnx.export` or `torch.onnx.dynamo_export`

**Comment by justinchuby** [comment]
Please use torch.onnx.export for now. We are refreshing dynamo_export and will share more in the coming months.
