### ISSUE TITLE
guard_size_oblivious isn't being oblivious?

### ISSUE THREAD

**Issue by ColinPeppler** [pytorch/pytorch#133525]
### 🐛 Describe the bug

Although, I'm adding `guard_size_oblivious(expr)` it isn't evaluating `expr` with `size_oblivious=True`?
> evaluate_expr(Eq(u0 + 1, 1), hint=None, expect_rational=True, size_oblivious=False, forcing_spec=False

This guard will fail even with `guard_size_oblivious`:
https://github.com/pytorch/pytorch/blob/dcdb25453e0ddc6a83e0052fffc544d4d03cdffd/torch/_subclasses/fake_impls.py#L1138

What's weird is that if I make this change, then test case passes.
```
             if (
                 isinstance(op, torch.Tensor)
                 and len(op.shape) == len(final_shape)
-                and op.shape == final_shape
+                and guard_size_oblivious(op.shape[0] == final_shape[0])
             ):
```

### Error logs

```
Potential framework code culprit (scroll up for full backtrace):
  File "/data/users/colinpeppler/pytorch/torch/_subclasses/fake_impls.py", line 1142, in fast_binary_impl
    or guard_size_oblivious(op.shape == final_shape)

User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "/data/users/colinpeppler/pytorch/test/dynamo/test_export.py", line 2485, in forward
    return scalar - x
```

https://gist.github.com/ColinPeppler/037ff8efb4528123814f3b261c41fd1d

### Minified repro

```
    def test_export_colin(self):
        class MyModel(torch.nn.Module):
            def forward(self, numel, scalar):
                u0 = numel.item()
                torch._check_is_size(u0)
                x = torch.ones(u0 + 1)
                return scalar - x

        model = MyModel().eval().cuda()
        numel = torch.tensor(10)
        scalar = torch.randn(1,)
        torch.export.export(model, (numel, scalar))
```

More data if it helps

```
op.shape
> torch.Size([1])
final_shape
> (u0 + 1,)
op.shape[0]
> 1
final_shape[0]
> u0 + 1
type(final_shape[0])
> <class 'torch.SymInt'>
type(final_shape)
> <class 'tuple'>
```

### Versions

base commit: e7b870c88bc3b854a95399a96a274d2f1f908172

cc @ezyang @chauhang @penguinwu

**Comment by ezyang** [comment]
You've met a terrible fate. guard_size_oblivious doesn't work on list equality. Do `guard_size_oblivious(sym_eq(op.shape, final_shape))`
