### ISSUE TITLE
Use THCDeviceTensor in FFI

### ISSUE THREAD

**Issue by zhanghang1989** [pytorch/pytorch#1335]
I am implementing a package with cuda kernel. This used to be easy for Torch using `THCDeviceTensor` (my Torch code can be found [here](https://github.com/zhanghang1989/Deep-Encoding)). Is it possible to include "THCDeviceTensor.cuh" and "THCDeviceTensorUtils.cuh" for a [ffi package](https://github.com/pytorch/extension-ffi)?

**Comment by zhanghang1989** [comment]
It seems ffi doesn't support kernel function currently.

**Comment by apaszke** [comment]
It doesn't support them right now. A solution we currently recommend for CUDA is linking a helper library that exposes a C API and wrapping that using ffi

**Comment by zhanghang1989** [comment]
Thanks for the reply! Would FFI be supported recently?
