### ISSUE TITLE
Masked.logaddexp op is not working with onnx.dynamo_export 

### ISSUE THREAD

**Issue by tugsbayasgalan** [pytorch/pytorch#133693]
When I was auditing failures here https://github.com/pytorch/pytorch/pull/132901, i ran into an issue with following command:
```
pytest test/onnx/test_fx_op_consistency.py::TestOnnxModelOutputConsistency_opset_version_18_model_type_TorchModelType.TORCH_EXPORT_EXPORTEDPROGRAMCPU::test_output_match_masked_logaddexp_cpu_float16
```
Upon investigating, I realized the reason was https://github.com/pytorch/pytorch/blob/51e13745be7052c02913db79b268e637c32546dd/test/onnx/torch_export/test_torch_export_with_onnxruntime.py#L34

Seems to be transient error to me because my PR doesn't touch torchdynamo. Since I couldn't figure out which sample inputs cause this problem, I just skip the test.

**Comment by titaiwangms** [comment]
In `TORCH_EXPORT_EXPORTEDPROGRAM` kind of test, onnx.dynamo_export uses exported_program to be input. I guess it's reasonable that the decomp behavior change in export affects it.
