### ISSUE TITLE
PyTorch built without distributed support

### ISSUE THREAD

**Issue by forhonourlx** [pytorch/pytorch#13369]
## 🐛 Bug

Traceback (most recent call last):
  File "test_dist.py", line 4, in <module>
    dist.init_process_group(backend="nccl", init_method="file:///distributed_test", world_size=2, rank=0)
  File "C:\Anaconda\lib\site-packages\torch\distributed\__init__.py", line 73, in init_process_group
    raise RuntimeError("PyTorch built without distributed support")
RuntimeError: PyTorch built without distributed support

## Environment
 - PyTorch Version :0.4.1 py36_cuda92_cudnn7he774522_1
 - OS : Windows10
 - How you installed PyTorch: conda
 - Python version: Anaconda 3.6.7
 - CUDA/cuDNN version: 9.2
 - GPU models and configuration: GTX1080

**Comment by zou3519** [comment]
Windows doesn't have distributed support.

**Comment by lironmo** [comment]
are you planning to add support to pytroch?
