### ISSUE TITLE
Bug report on IndexError

### ISSUE THREAD

**Issue by xfanak** [pytorch/pytorch#13365]
## 🐛 Bug
Hello pytorch developers, I think I have encountered a bug on tensor index

## To Reproduce

1. I'm trying to re-combine the rows in the tensor, so I did:
a = torch.randn(m,n)
b = array(list(combinations(range(m),2)))

2. Then, a[b] shall return a rearranged tensor. As long as m >= 9, then everything is fine, however, when m is less than 9, then it returns an index error: Too many indices for a tensor of dimension 2.

##Sample code:
from numpy import array
import torch
from itertools import combinations

a =  torch.randn(8,3)
b = array(list(combinations(range(8),2)))
a[b]

## Expected behavior
a[b] should returns a 28 by 2 by 3 tensor, however, it returns an index error.
 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 0.4.1
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information:

**Comment by zou3519** [comment]
Try `a[torch.tensor(b)]`. We don't support indexing with numpy arrays.

**Comment by xfanak** [comment]
Thank you Zou. But a[b] works out fine if b = array(list(combinations(range(m),2))), m >= 9.
