### ISSUE TITLE
Why pytorch run super slow on windows server 2012?

### ISSUE THREAD

**Issue by ZQPei** [pytorch/pytorch#13372]
## Here is my question
I have a PC runs **windows server 2012 R2** system with **NVIDIA 1080ti**,
and I have all drivers installed.
CUDA 9.0
cudnn 7.3
anaconda python3.6

Now I followed the pytorch.org instructions to install pytorch
```bash
conda install pytorch -c pytorch
pip install torchvision
```
and installed pytorch successfully!

However, when i run deep learning codes , for example YOLO3, it runs rather slow !
YOLO3 code should be able to detect an image within 40ms.
**Now on windows server 2012, it runs more than 120ms per image which is three times slower than expected**.

**I also tried the same code on ubuntu16.04, and it runs within 40ms per image**.

Do any other encounted the same problem?
Maybe windows server 2012 not compatible for pytorch?
Please somebody help me out! thanks!!!

**Comment by peterjc123** [comment]
Can you show me your code, please?

**Comment by ZQPei** [comment]
> Can you show me your code, please?

Thanks for your reply !
To make things simple, I simply run the yolo3 code from [marvis/pytorch-yolo3](https://github.com/marvis/pytorch-yolo3).
The time running on several images is like:
Loading weights from yolov3.weights... Done!
data\dog.jpg: Predicted in 0.218750 seconds.
save plot results to predictions.jpg
data\eagle.jpg: Predicted in 0.203140 seconds.
save plot results to predictions.jpg
data\giraffe.jpg: Predicted in 0.211412 seconds.
save plot results to predictions.jpg
data\horses.jpg: Predicted in 0.218754 seconds.
save plot results to predictions.jpg
data\person.jpg: Predicted in 0.203153 seconds.
save plot results to predictions.jpg
data\predictions.jpg: Predicted in 0.218781 seconds.
save plot results to predictions.jpg
data\scream.jpg: Predicted in 0.198292 seconds.
save plot results to predictions.jpg

However, if i run the same code on ubuntu16.04, it's much faster!
Here is the time usage on ubuntu,  almost 4times faster than running on win server.
Loading weights from yolov3.weights... Done!
data/eagle.jpg: Predicted in 0.049110 seconds.
save plot results to predictions.jpg
data/dog.jpg: Predicted in 0.051502 seconds.
save plot results to predictions.jpg
data/predictions.jpg: Predicted in 0.050423 seconds.
save plot results to predictions.jpg
data/horses.jpg: Predicted in 0.050959 seconds.
save plot results to predictions.jpg
data/scream.jpg: Predicted in 0.048784 seconds.
save plot results to predictions.jpg
data/person.jpg: Predicted in 0.050009 seconds.
save plot results to predictions.jpg
data/giraffe.jpg: Predicted in 0.049526 seconds.
save plot results to predictions.jpg

It doesnot make any sense! Those machines are all using NVIDIA 1080ti.
Is it because pytorch cannot do well on windows server?
Can you help me out, please?

**Comment by peterjc123** [comment]
I cannot run it correctly. Could you tell me how you run this code? 
What I did:
```cmd
git clone https://github.com/marvis/pytorch-yolo3.git
cd pytorch-yolo3
:: Optionally I switched to the python3 branch
:: But still no luck
:: git checkout python3
wget https://pjreddie.com/media/files/yolov3.weights
python detect.py cfg/yolov3.cfg yolov3.weights data/dog.jpg
```
The errors I get:
```pytb
Traceback (most recent call last):
  File "detect.py", line 114, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 12, in detect
    m.load_weights(weightfile)
  File "pytorch-yolo3\darknet.py", line 334, in load_weights
    start = load_conv_bn(buf, start, model[0], model[1])
  File "pytorch-yolo3\cfg.py", line 187, in load_conv_bn
    conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3
```

**Comment by ZQPei** [comment]
> The errors I get:
> 
> ```
> Traceback (most recent call last):
>   File "detect.py", line 114, in <module>
>     detect(cfgfile, weightfile, imgfile)
>   File "detect.py", line 12, in detect
>     m.load_weights(weightfile)
>   File "pytorch-yolo3\darknet.py", line 334, in load_weights
>     start = load_conv_bn(buf, start, model[0], model[1])
>   File "pytorch-yolo3\cfg.py", line 187, in load_conv_bn
>     conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
> RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3
> ```
Thanks for helping me!

The problem is because of python and pytorch version.
You need change the code a little bit.
if you use python3, better clone its branch `python3`
```bash
git clone -b python3 https://github.com/marvis/pytorch-yolo3.git
```
if using pytorch 0.4,then open cfg.py, in line 169 and 187,  `conv_model.weight.data.copy_`
comment the original code, and replace them with
```python
conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w]).view(conv_model.weight.data.shape)); start = start + num_w
```

then it should work.

It doesnot have to be this code, i just use it to demostrate how slow i run on win server.

**Comment by peterjc123** [comment]
I've tried this code on a Windows box with Nvidia GTX 1080ti on Windows Server 2016 using PyTorch 0.4.1. It takes nearly 0.1s. I don't have a Linux box with GPU. So I can't tell exactly where the problem is. It's actually very hard to debug such a complex network because there are actually so many related things. If you could find out which atom operation (like add, addmm or mul) is generally slower, then I think that we can look into it.

**Comment by ZQPei** [comment]
>  If you could find out which atom operation (like add, addmm or mul) is generally slower, then I think that we can look into it.

I run this code on another machine with Nvidia GTX 1050ti on windows 10, and it takes 0.1s per image.
If with 1080,  it should be faster. So i think windows 10 is OK with pytorch.
How should i do the tests of those atom operations to find out which is the part that affects? 
How about just simply run each fundumental operation in thousands of times in a for loop?
Do you have any suggestions?

**Comment by sakaia** [comment]
@ZQPei  Your should profile the code. for example, https://discuss.pytorch.org/t/cuda-profiling-with-autograd-profiler-profile/13318/2
