### ISSUE TITLE
Distributed training error:  throwing an instance of 'std::system_error'

### ISSUE THREAD

**Issue by mosjoker** [pytorch/pytorch#13378]
When i trained the ResNet-18 on ImageNet with distributed module，sometimes the process ｗith rank  0 will shut down after one epoch.

pytorch-version: 0.4.1+dc854c0

I also tried training in version 1.0, but dozens of epochs still have the error. and other processes continue to train.
someone can tell me the reason?

**Comment by teng-li** [comment]
Can you provide a training repro code?

**Comment by pietern** [comment]
No response, closing the issue.
