### ISSUE TITLE
Add dynamo support to itertools.pairwise

### ISSUE THREAD

**Issue by Skylion007** [pytorch/pytorch#133766]
### 🚀 The feature, motivation and pitch

We do not have support for itertools.pairwise builtin yet. It's supported in nearly every version of Python we support now, and I suspect it will only continue to be more popular. It's also relatively easy to add via a polyfill.

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by Skylion007** [comment]
@XuehaiPan If you want to take a look at adding this pollyfill.

**Comment by XuehaiPan** [comment]
I'll have a look for this.

**Comment by yugborana** [comment]
I am looking to contribute to this issue. Would you @Skylion007 please explain more on this issue?

**Comment by mattcattb** [comment]
I would also love to contribute to this issue. What are we looking at to add itertools builtin for?

**Comment by MichaelACraig** [comment]
I'd love to contribute to this issue as well. Could you elaborate more on the issue? I'll look into this regardless and report back my findings soon.
