### ISSUE TITLE
Automatic linter fixing for PRs

### ISSUE THREAD

**Issue by nowtryz** [pytorch/pytorch#133715]
### 🚀 The feature, motivation and pitch

As described in #133619, I cannot run `lintrunner` locally on windows, which leaves a few linting errors in my code. Consequently, two of my PRs were consistently failing (#128574, #128637) due to linting.

Would it be possible to automatically fix linting issues in the PR in the spirit of [pre-commit-ci](https://github.com/marketplace/pre-commit-ci)?

### Alternatives

I considered not developing on Windows or trying to apply the lint patches manually.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
IMO it would be good to either make lintrunner make suggestions on the PR and/or having a `@pytorchbot apply-lint" command

**Comment by nowtryz** [comment]
> make lintrunner make suggestions on the PR

That would be a good starting point. Though the lint action require approval, maybe at least run the linter by default for all PRs would be sufficient.

> having a `@pytorchbot apply-lint" command

This would have definitly saved a lot of time! :+1:

**Comment by huydhn** [comment]
I think we can also suggest changes instead of applying the fix.  The benefit is that it's less intrusive and the behavior is more familiar to devs.  Also, there are some existing GHA that we can just use, i.e.  https://github.com/parkerbxyz/suggest-changes.

**Comment by clee2000** [comment]
Completed by @PaliC in https://github.com/pytorch/pytorch/pull/136239 and can be triggered by adding `ciflow/autoformat` (https://github.com/pytorch/pytorch/pull/138263)
