### ISSUE TITLE
SubsetSampler not available.

### ISSUE THREAD

**Issue by shubhamjain0594** [pytorch/pytorch#1337]
In ```torch.utils.data.sampler``` there is ```RandomSampler``` and ```SubsetRandomSampler``` but not ```SubsetSampler``` in cases you don't want random sampling from the indices. Any reasons for this? If it is just a missing feature, I can send a PR.

**Comment by soumith** [comment]
you dont need a separate SubsetSampler, just giving an interable of subset indices is sufficient.

**Comment by shubhamjain0594** [comment]
I am sorry but I don't understand it exactly. To what should we give an iterator of subset indices?

**Comment by soumith** [comment]
You are wondering if we can just have a `SubsetSequentialSampler`, like in this PR: https://github.com/pytorch/pytorch/pull/888/commits/4d4336e47a6688428241c89b2a183cb4ff3b0a15

To the sampler, you will get a subset of indices (say a list of indices) and it will sample from them.
I'm saying that you dont need a separate SubsetSampler that takes in indices and makes the data loader iterate over them, you can just give a list of indices to the Data loader are the sampler

**Comment by shubhamjain0594** [comment]
Ohh okay. Sorry I didn't realize that. Thanks for helping out.

**Comment by josh-gleason** [comment]
@soumith This doesn't seem to be true either in either pytorch 0.4.1 or 1.3.1. In both cases the following code gives an error.

    loader = DataLoader(range(10), sampler=[0,1,2])

which results in

    ValueError: sampler should be an instance of torch.utils.data.Sampler, but got sampler=[0, 1, 2]

**Comment by javierbg** [comment]
> @soumith This doesn't seem to be true either in either pytorch 0.4.1 or 1.3.1. In both cases the following code gives an error.
> 
> ```
> loader = DataLoader(range(10), sampler=[0,1,2])
> ```
> 
> which results in
> 
> ```
> ValueError: sampler should be an instance of torch.utils.data.Sampler, but got sampler=[0, 1, 2]
> ```

This is true for 1.5.0 too, it seems like `DataLoader` checks that `sampler` is an instance of `torch.utils.data.Sampler`, so the previous solution is not valid anymore.

**Comment by SsnL** [comment]
@josh-gleason @javierbg this is being relaxed in #38403
