### ISSUE TITLE
How do you convert the tensor to a float

### ISSUE THREAD

**Issue by jobbofhe** [pytorch/pytorch#13374]
## 🐛 Bug

`error: invalid cast from type 'at::Tensor' to type 'std::string {aka std::basic_string<char>}'`
When I used the libtorch C++ API to do the test, after I got the variable tensor, I needed to print out every value of the variable. The C++ forced type conversion failed! How do I convert data types?

**Comment by zou3519** [comment]
One of these two should work:
tensor.toString()
std::cout << tensor << std::endl;

**Comment by Sierkinhane** [comment]
How can i convert ‘at::Tensor’ to ‘const float*’ in libtorch? (Not convert to const char*)

**Comment by Sierkinhane** [comment]
@zou3519

**Comment by Sierkinhane** [comment]
like ->cpu_data() in caffe
Blob<float>* net_output_blob = net_->blob_by_name("net_output").get();
const float* net_output_data_begin = net_output_blob->cpu_data();

**Comment by ezyang** [comment]
`x.data<float>()` and note this only works if it's contiguous
