### ISSUE TITLE
Fuser can incorrectly fuse comparison ops at the end of fusion groups

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#13384]
Currently the fuser hopes that when it will fuse an op that has an `int8` output type, it will be followed by a `type_as` (as is the case in e.g. many ReLU implementations). However, it's not guaranteed to be the case, and since our codegen only supports `float` math, it can sometimes change the run time type of the values:

```python
import torch

def f(x, y, z):
    return ((x + y) / z) >= z

inputs = [torch.randn(2, 2, device='cuda') for _ in range(3)]
real_output = f(*inputs)
fs = torch.jit.script(f)
output = fs(*inputs)
print(fs.graph_for(*inputs))
print(output)
print(real_output)
```

This inconsistency is very unfortunate and I will need to remove it in one of my upcoming fuser refactors. We can safely make those ops fusable again once we expand the codegen to work on arbitrary scalar types.

**Comment by apaszke** [comment]
cc @ngimel @mruberry

**Comment by t-vi** [comment]
I like fusion of comparison ops and would take a stab at doing types and that if it's OK and not incompatible with your plans (@ngimel @mruberry @mcarilli @zdevito).

**Comment by mruberry** [comment]
@t-vi Working on it now. Give me a until the start of next week?
