### ISSUE TITLE
Module set_parameters

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#13383]
## 🚀 Feature

It is useful to have a set_parameters other the get_parameter in https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/module.h#L368.
See also https://github.com/pytorch/pytorch/issues/13245#issuecomment-434235980

## Motivation

There isn't a single API call to load/change all the parameters at once after torch::jit::load() like ```the_model.load_state_dict(torch.load(PATH))``` 
## Pitch

I want to have a single call after ```torch::jit::load()``` that could consume serialized parameters like ```the_model.load_state_dict(torch.load(PATH))``` 
## Alternatives

Set the parameters one by one with https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/module.h#L347

**Comment by bhack** [comment]
Of course the same interface could be useful in Python

**Comment by goldsborough** [comment]
The C++ frontend modules have a `serialize`/`deserialize` method for parameters and buffers: https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/nn/module.h#L252. We're working on unifying the TorchScript C++ modules with the C++ frontend modules, so I would say that unification is the best route for implementing this `set_parameters` feature.

**Comment by bhack** [comment]
@goldsborough Yes I understand. This it will be very useful to trace the model interdependently from the weights that you want to set from different training steps/checkpoints.

**Comment by joyliu37** [comment]
It's it possible to parse the model weight from `torch::jit::script::Module` using function `get_parameter`. If so, could you give me an example or some pointer.
I want to utilize the model trained from PyTorch and deploy it into C++ environment to utilize Halide for productivity. I thought the torchscript may be helpful.

**Comment by joyliu37** [comment]
@goldsborough Thanks for your instant reply. This solved my problem perfectly. I just figure out the parameter is saved in a `unique_ptr` .So when I call `get_parameters()`, I can only return the reference  instead of `copy`.

**Comment by goldsborough** [comment]
You can call `->clone()` to get a copy of the tensor

**Comment by joyliu37** [comment]
@goldsborough I found there is no `forward` method in a `submodule` of a loaded network in script mode . Is it true that we cannot run single layer inference in the script mode? Is there a way to transform `torch::jit::script::Module` to `torch::nn::Module`? Thanks!

**Comment by goldsborough** [comment]
I think `ScriptModule::get_modules` returns a [`NamedModule`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/module.h#L294) which has a `module` member which you can all `forward` on. Please create a separate issue if you have further questions, or reach out to us on Slack.

**Comment by ifedan** [comment]
Please kindly feel encouraged to reopen this issue, if this does not apply.
