### ISSUE TITLE
[ImportError] libtorch.so.1: undefined symbol: _ZTIN2at10TensorImplE

### ISSUE THREAD

**Issue by mychina75** [pytorch/pytorch#13380]
## 🐛 Bug

I tried to install pytorch nightly version.  but error occurred when import torch.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: /home/xxx/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch.so.1: undefined symbol: _ZTIN2at10TensorImplE

## To Reproduce
1. Install package download from https://anaconda.org/pytorch/pytorch-nightly/files
linux-64/pytorch-nightly-1.0.0.dev20181029-py3.6_cuda9.0.176_cudnn7.1.2_0.tar.bz2
2. conda install --offline pytorch-nightly-1.0.0.dev20181029-py3.6_cuda9.0.176_cudnn7.1.2_0.tar.bz2
3. $python
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: libcurand.so.9.1: cannot open shared object file: No such file or directory
4. update cuda9.0 to cuda9.1
5. $ python
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: /home/xxx/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch.so.1: undefined symbol: _ZTIN2at10TensorImplE

## Environment
 - OS (e.g., Linux): ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.6.1
 - CUDA/cuDNN version: cuda9.0.176 -> cuda9.1.85, cudnn: 7.1.2
 - GPU models and configuration: K80
 - Any other relevant information:

Thank you!

**Comment by ICEORY** [comment]
I solve this problem by upgrading cudnn from 7.1.2 to 7.1.3.

**Comment by ngimel** [comment]
Closing due to age
