### ISSUE TITLE
Docs: more details about CUDA models with multiprocessing 

### ISSUE THREAD

**Issue by Jiaming-Liu** [pytorch/pytorch#1338]
In [pytorch/docs/source/notes/cuda.rst](https://github.com/pytorch/pytorch/blob/master/docs/source/notes/cuda.rst), it is mentioned that:

> unless care is taken to meet the data handling requirements exactly, it is likely that your program will have incorrect or undefined behavior.

IMO, more details on the requirements would be helpful for this part.

**Comment by apaszke** [comment]
The most important thing are the requirements of the CUDA API. I'd discourage its use unless you know some lower level detail of CUDA IPC. The most important limitation is that if you allocate a CUDA tensor X in process A and send it to process B, then X should **never go out of scope and be freed in A** until it's used in B (NOTE: it's automatically freed upon A's exit). So it might be ok for sharing CUDA parameters across processes, but not e.g. for data loading.
