### ISSUE TITLE
the running time difference between the ATen library and pytorch ?

### ISSUE THREAD

**Issue by YunYang1994** [pytorch/pytorch#13381]
## ❓ the running time difference between the ATen library and pytorch

[ATen](https://github.com/zdevito/ATen/tree/master/aten) is a simple tensor library thats exposes the Tensor operations in [Pytorch](https://pytorch.org/) directly in C++11. I wrote some codes to compare their performance and encountered some problems .[here](https://github.com/YunYang1994/ATenTest) are my codes.

## On pytorch platform
source file [`test.py`](https://github.com/YunYang1994/ATenTest/blob/master/test.py)
```py
import numpy as np
import torch
import time
import argparse
from torch.nn import functional

parser = argparse.ArgumentParser(description="compare running time on between cpu and gpu")
parser.add_argument('N', type=int, help="the number of iterations")
parser.add_argument('device', type=int, help="1: use cuda, 0: not use")

N = parser.parse_args().N
device = "gpu" if parser.parse_args().device else "cpu"

input_data = np.ones([1,3,224,224])
input_data = input_data.astype("float32")

weight_data = np.ones([64,3,7,7])
weight_data = weight_data.astype("float32")
bn_weight = np.ones([64,])
bn_weight = bn_weight.astype("float32")

Input = torch.from_numpy(input_data)
weight = torch.from_numpy(weight_data)
weights_1 = torch.from_numpy(bn_weight)

if device == "gpu":
    Input = Input.cuda()
    weight = weight.cuda()
    weights_1 = weights_1.cuda()

start = time.time()
for i in range(N):
    tmp_tensor = functional.conv2d(Input, weight, bias=None, stride=2, padding=3, dilation=1, groups=1)
    tmp_tensor = functional.batch_norm(tmp_tensor, weights_1, weights_1, weights_1, weights_1, training=False, momentum=1.0, eps=9.99999974738e-06)
    tmp_tensor = functional.relu(tmp_tensor)
end = time.time()

print("running on %s %.4f s" %(device, end - start))
```

```bashrc
yang@yang:~/ATenTest$ python test.py 1 0 # CPU
running on cpu 0.0155 s
yang@yang:~/ATenTest$ python test.py 1 1 # GPU
running on gpu 0.0027 s
```

## On ATen library
source file [`test.cpp`](https://github.com/YunYang1994/ATenTest/blob/master/test.cpp)
```cpp
#include <iostream>
#include <vector>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>

#include <ATen/ATen.h>  // containing cuda header files (.h) !!!
using namespace at;

int main(int argc, char** argv) {

    clock_t t_start, t_end; // recording time
    double totaltime;
    int N = atof(argv[1]); // the number of iterations
    bool gpu = int(atof(argv[2]));
    std::vector<Tensor> Input(1), weights(3), tmp_tensor(1); // prepare vector for data

    if(gpu){
        std::cout << "running on gpu ";
        {Tensor buff=CUDA(kFloat).ones({1,3,224,224}); Input[0]=buff.type().copy(buff);}
        {Tensor buff=CUDA(kFloat).ones({64,3,7,7}); weights[0]=buff.type().copy(buff);}
        {Tensor buff=CUDA(kFloat).ones({64,}); weights[1]=buff.type().copy(buff);}
    }
    else{
        std::cout << "running on cpu ";
        {Tensor buff=CPU(kFloat).ones({1,3,224,224}); Input[0]=buff.type().copy(buff);}
        {Tensor buff=CPU(kFloat).ones({64,3,7,7}); weights[0]=buff.type().copy(buff);}
        {Tensor buff=CPU(kFloat).ones({64,}); weights[1]=buff.type().copy(buff);}
    }

    t_start = clock();
    for(int i=0; i<N; i++){
        tmp_tensor[0] = convolution(Input[0], weights[0], Tensor(), {{2,2}}, {{3,3}}, {{1,1}}, false, {{0,0}}, 1);
        tmp_tensor[0] = batch_norm(tmp_tensor[0], weights[1], weights[1], weights[1], weights[1], false, 1.0, 9.99999974738e-06, false);
        tmp_tensor[0] = relu(tmp_tensor[0]);
    }
    t_end = clock();

    totaltime = (double)(t_end - t_start)/CLOCKS_PER_SEC;
    std::cout << totaltime << " s" <<std::endl;
}
```

I compiled it with following command on Linux:

```bashrc
g++ -Wl,--no-as-needed -w test.cpp -o main -I ./include -L . -lATen_cuda -lATen_cpu -std=c++11
```

In the following step, I got [`main`](https://github.com/YunYang1994/ATenTest/blob/master/main) which was an executable file, and can then run it on CPU or GPU like this. 

```bashrc
yang@yang:~/ATenTest$ ./main 1 1 # on GPU (argv[1] is the iterations, argv[2] means use cuda or not
running on gpu 0.542298 s
yang@yang:~/ATenTest$ ./main 1 0 # on CPU
running on cpu 0.072884 s
```
Now let's consider trying a range of iterations on CPU or GPU plateform, the code running time difference shows in the following table.

| iterations | 1 | 10 | 100 | 1000 | 5000 | 10000 |
| ---------- | -----------| ---------- | -----------| ---------- | -----------| ---------- |
| `pytorch(CPU)`   | 0.0156 s  | 0.1062 s | 0.9916 s | 9.8697 s | 50.2868 s | 98.1801 s |
| `pytorch(GPU)`   | 0.0026 s  | 0.0031 s | 0.0082 s | 0.6314 s | 3.5506 s | 7.162 s |
| `ATen(CPU)`   | 0.071542 s  | 0.424533 s | 3.85708 s |  38.1909 s | 191.34 s | 383.295 s |
| `ATen(GPU)`   | 0.540007 s  | 0.541056 s | 0.545027 s | 1.12482 s | 4.0507 s | 7.68236 s |

As a result, the code on GPU was much more faster than on the CPU for both pytorch and ATen. And it was expectd that there was less running time difference between pytorch plateform and ATen library, but the result showed that code on ATen libaray was always much slower than on the pytorch plateform (This makes no sense, for the reason that C++ should be faster and lighter than Python)! The confusing point in my mind is

**Comment by f0k** [comment]
FWIW, your Python script only times how long it takes to schedule the operations for execution. You need to synchronize on the device before the `end = time.time()` call, e.g., with `torch.cuda.synchronize()`.

**Comment by YunYang1994** [comment]
### for pytorch (+synchronize)
```py
start = time.time()
for i in range(N):
    tmp_tensor = functional.conv2d(Input, weight, bias=None, stride=2, padding=3, dilation=1, groups=1)
    tmp_tensor = functional.batch_norm(tmp_tensor, weights_1, weights_1, weights_1, weights_1, training=False, momentum=1.0, eps=9.99999974738e-06)
    tmp_tensor = functional.relu(tmp_tensor)

torch.cuda.synchronize()
end = time.time()
```


| iterations | 1 | 10 | 100 | 1000 | 5000 | 10000 |
| ---------- | -----------| ---------- | -----------| ---------- | -----------| ---------- |
| `pytorch(GPU)`   | 0.0026 s  | 0.0031 s | 0.0082 s | 0.6314 s | 3.5506 s | 7.162 s |
| `pytorch(GPU+synchronize)`   | 0.0499 s  | 0.0587 s | 0.1411 s | 0.8223 s | 3.8552 s | 7.5512 s |
| `ATen(GPU)`   | 0.540007 s  | 0.541056 s | 0.545027 s | 1.12482 s | 4.0507 s | 7.68236 s |

@f0k , Thanks for your answer, I got what you meant!  I realized that Running code on the GPU is asynchronous. As you wish, I put a line `torch.cuda.synchronize()` before `end = time.time()`. but it seems that it does not work very much?

**Comment by pliu6** [comment]
I am facing a similar issue in a different scenario. I am trying to execute a Torch script with C++ API on GPU. The inference does not take much time, but moving data from CPU to GPU is very slow.

Does anyone have clue about how to fix the issue? Thanks!

**Comment by lizhan17** [comment]
put torch.cuda.synchronize() befoere start = time.time() also.
I am looking forward to your results.



> @f0k , Thanks for your answer, I got what you meant! I realized that Running code on the GPU was
> asynchronous. As you wished, I put a line `torch.cuda.synchronize()` before `end = time.time()`. but it seemed that it did not work very much?
> 
> ### for pytorch (+sync)
> ```python
> start = time.time()
> for i in range(N):
>     tmp_tensor = functional.conv2d(Input, weight, bias=None, stride=2, padding=3, dilation=1, groups=1)
>     tmp_tensor = functional.batch_norm(tmp_tensor, weights_1, weights_1, weights_1, weights_1, training=False, momentum=1.0, eps=9.99999974738e-06)
>     tmp_tensor = functional.relu(tmp_tensor)
> 
> torch.cuda.synchronize()
> end = time.time()
> ```
> 
> iterations	1	10	100	1000	5000	10000
> `pytorch(GPU)`	0.0026 s	0.0031 s	0.0082 s	0.6314 s	3.5506 s	7.162 s
> `pytorch(GPU+sync)`	0.0499 s	0.0587 s	0.1411 s	0.8223 s	3.8552 s	7.5512 s
> `ATen(GPU)`	0.54001 s	0.54106 s	0.54503 s	1.1248 s	4.0507 s	7.6824 s

**Comment by ezyang** [comment]
To answer your original question:

> Did pytorch do any optimization on the basis of ATen library ?

Not for the code you've listed here. So there's almost certainly something wrong with the benchmarking setup here, somewhere, since at the end of the day the PyTorch code calls the ATen code.

You didn't say how you installed PyTorch and libtorch. Another thing to check is whether or not the same CUDA kernels are being run in both cases; you can quickly check using nvprof.

Since this is not actionable by us, I'm going ahead and closing this issue. Let us know if you think there is something we should fix (e.g., libtorch install docs, for example)

**Comment by i-amgeek** [comment]
Tried to compile cpp code with -O3 flag?
