### ISSUE TITLE
Backprop through argmax

### ISSUE THREAD

**Issue by johnwlambert** [pytorch/pytorch#1339]
Hi, I need to pass input through one nn.Module, then argmax the output, and then pass that output to a second nn.Module. I want to backprop through the argmax back to the weights of the first module. 
`y_p = torch.max(y_p, 1)[1]`

That's impossible right now, though, it seems.  When I loop through the gradient of the weights of my first module (with the following code):
`	first_model.zero_grad()
	second_model.zero_grad()

	loss.backward() # retain_variables=True

	for param in second_model.parameters():
		print( 'data: ', param.data  )
		print( 'grad data: ', param.grad.data )

	for param in first_model.parameters():
		print( 'data: ', param.data  )
		print( 'grad data: ', param.grad.data )`
I get the following error, stating that those gradients can no longer be viewed/exist:

> AttributeError: "'NoneType' object has no attribute 'data'"
> /scail/scratch/group/vision/johnwl/PytorchTensorToVar_Backprop_SanityCheck.py(109)<module>()
-> main()

**Comment by apaszke** [comment]
argmax is not differentiable (and even if you try to think about it as a function differentiable almost everywhere, its derivative is always 0, so you won't get anything meaningful).
