### ISSUE TITLE
Feat: count_nonzero for bool tensors

### ISSUE THREAD

**Issue by baldassarreFe** [pytorch/pytorch#133983]
I often need to run count_nonzero on boolean tensors. The current impl does not specialize for this dtype and checks `!=0` again. 

https://github.com/pytorch/pytorch/blob/68570fca69649296489df4300f3a4f8f36683e08/aten/src/ATen/native/TensorAdvancedIndexing.cpp#L2286-L2288

Can we add a check that if the tensor is bool the comparison is skipped?

cc @msaroufim

**Comment by soulitzer** [comment]
We would review a PR to fix this
