### ISSUE TITLE
[Distributed Checkpointing][torch2.4] torch 2.4 can't load a checkpointing saved by torch2.3

### ISSUE THREAD

**Issue by bigning** [pytorch/pytorch#133923]
### 🐛 Describe the bug

[This PR](https://github.com/pytorch/pytorch/pull/125335) changed how load_planner and save_planner flatten the state dict. It broke the backward compatibility. With this PR, it can't load checkpointing that saved before this PR. it  fails here https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/default_planner.py#L319 because the metadata keys doesn't match the state_dict keys. 

### Versions

PyTorch version: 2.4.0+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB

Nvidia driver version: 535.129.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @xmfan @LucasLLC @pradeepfn

**Comment by bigning** [comment]
cc @fegin

**Comment by yifuwang** [comment]
cc @LucasLLC

**Comment by bigning** [comment]
Hey @fegin , wondering how you would fix it. Will you revert the change or keep that PR but add a patch to be able to load the old checkpointing? Asking because on our side, we need that information to decide how we monkeypatch pytorch in composer to release the torch2.4. thanks!

**Comment by fegin** [comment]
@bigning We are working on a PR to fix the BC issue. Reverting the change may also break other users and cause more issues. We are also planning to add versions to metadata so that this kind of BC issues won't happen again in the future.

**Comment by fegin** [comment]
@bigning https://github.com/pytorch/pytorch/pull/134158 is the intended solution. @pradeepfn Please check the PR.

**Comment by bigning** [comment]
Hi @fegin , looks this fix is not included in 2.4.1 ?

**Comment by fegin** [comment]
@bigning  unfortunately, when the fix was landed, the cherrypick time of 2.4.1 had already passed.
