### ISSUE TITLE
Crash When Using torch.compile with Math scaled_dot_product_attention in AMP Mode

### ISSUE THREAD

**Issue by retonym** [pytorch/pytorch#133974]
### 🐛 Describe the bug

**Summary**
When attempting to compile a math sdp operation using torch.compile in AMP mode, the script encounters a crash. This issue does not occur with a single Flash Attention operation.

**Reproducible Script**
Below is a minimal script that reproduces the crash:

```Python

from math import inf
import torch
from torch import tensor, device
import torch.fx as fx
import torch._dynamo
from torch._dynamo.testing import rand_strided
from torch._dynamo.debug_utils import run_fwd_maybe_bwd

import torch._dynamo.config
import torch._inductor.config
import torch._functorch.config
import torch.fx.experimental._config

import os
torch._inductor.config.fallback_random = True


# torch._dynamo.config.base_dir = os.environ["TORCHINDUCTOR_CACHE_DIR"]

# disable cuda sdp, before we implement it with xpu backend
torch.backends.cuda.enable_cudnn_sdp(False)
torch.backends.cuda.enable_flash_sdp(False)
torch.backends.cuda.enable_mem_efficient_sdp(False)
torch.backends.cuda.enable_math_sdp(True)



from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()



    def forward(self, L_L_self_modules_self_attn_modules_out_proj_parameters_weight_ : torch.Tensor, L_L_self_modules_self_attn_modules_out_proj_parameters_bias_ : torch.Tensor, key_states, value_states, query_states_1):
        l_l_self_modules_self_attn_modules_out_proj_parameters_weight_ = L_L_self_modules_self_attn_modules_out_proj_parameters_weight_
        l_l_self_modules_self_attn_modules_out_proj_parameters_bias_ = L_L_self_modules_self_attn_modules_out_proj_parameters_bias_
        attn_output = torch._C._nn.scaled_dot_product_attention(query_states_1, key_states, value_states, attn_mask = None, dropout_p = 0.0, is_causal = True);  query_states_1 = key_states = value_states = None
        attn_output_1 = attn_output.transpose(1, 2);  attn_output = None
        attn_output_2 = attn_output_1.reshape(1, 1024, 1024);  attn_output_1 = None
        attn_output_3 = torch._C._nn.linear(attn_output_2, l_l_self_modules_self_attn_modules_out_proj_parameters_weight_, l_l_self_modules_self_attn_modules_out_proj_parameters_bias_);  attn_output_2 = l_l_self_modules_self_attn_modules_out_proj_parameters_weight_ = l_l_self_modules_self_attn_modules_out_proj_parameters_bias_ = None
        return (attn_output_3,)


mod = Repro()

def load_args(reader):
    buf0 = reader.storage('18f6e31c9f38831ae36b922d77c4c0546a0b5bb5', 4194304, device=device(type='cuda', index=0))
    reader.tensor(buf0, (1024, 1024), requires_grad=True, is_leaf=True)  # L_L_self_modules_self_attn_modules_out_proj_parameters_weight_
    buf1 = reader.storage('1ceaf73df40e531df3bfb26b4fb7cd95fb7bff1d', 4096, device=device(type='cuda', index=0))
    reader.tensor(buf1, (1024,), requires_grad=True, is_leaf=True)  # L_L_self_modules_self_attn_modules_out_proj_parameters_bias_
    buf2 = reader.storage('9f89f5ef3ecccc9aa2d2d9ec5d6882b315806934', 2097152, device=device(type='cuda', index=0), dtype_hint=torch.float16)
    reader.tensor(buf2, (1, 16, 1024, 64), dtype=torch.float16, requires_grad=True)  # key_states
    buf3 = reader.storage('74883a0ed186fbeb2dbe8b5c549db706a634fdb0', 2097152, device=device(type='cuda', index=0), dtype_hint=torch.float16)
    reader.tensor(buf3, (1, 16, 1024, 64), dtype=torch.float16, requires_grad=True)  # value_states
    buf4 = reader.storage('a22f237f6ff537f598c9f0b2728e44c66b52a875', 2097152, device=device(type='cuda', index=0), dtype_hint=torch.float16)
    reader.tensor(buf4, (1, 16, 1024, 64), dtype=torch.float16, requires_grad=True)  # query_states_1
load_args._version = 0

if __name__ == '__main__':
    from torch._dynamo.repro.after_dynamo import run_repro
    run_repro(mod, load_args, accuracy=False, command='run',
        save_dir='/home/yunfei/code/piece/checkpoints', autocast=True, backend='inductor')

```

### Versions

Collecting environment information...
PyTorch version: 2.5.0a0+gitf1c439c
Is debug build: False
CUDA used to build PyTorch: 12.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.30.0
Libc version: glibc-2.31

Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-190-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.2.91
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB
Nvidia driver version: 535.183.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      48 bits physical, 48 bits virtual
CPU(s):                             64
On-line CPU(s) list:                0-63
Thread(s) per core:                 1
Core(s) per socket:                 64
Socket(s):                          1
NUMA node(s):                       8
Vendor ID:                          AuthenticAMD
CPU family:                         25
Model:                              1
Model name:                         AMD EPYC 7713 64-Core Processor
Stepping:                           1
Frequency boost:                    enabled
CPU MHz:                            1448.894
CPU max MHz:                        2000.0000
CPU min MHz:                        1500.0000
BogoMIPS:                           3999.52
Virtualization:                     AMD-V
L1d cache:                          2 MiB
L1i cache:                          2 MiB
L2 cache:                           32 MiB
L3 cache:                           256 MiB
NUMA node0 CPU(s):                  0-7
NUMA node1 CPU(s):                  8-15
NUMA node2 CPU(s):                  16-23
NUMA node3 CPU(s):                  24-31
NUMA node4 CPU(s):                  32-39
NUMA node5 CPU(s):                  40-47
NUMA node6 CPU(s):                  48-55
NUMA node7 CPU(s):                  56-63
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP disabled; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] bert_pytorch==0.0.1a4
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy==1.10.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] onnx==1.16.1
[pip3] optree==0.12.1
[pip3] pytorch-labs-segment-anything-fast==0.2
[pip3] pytorch-triton==3.0.0+dedb7bdf33
[pip3] torch==2.5.0a0+gitf1c439c
[pip3] torch_geometric==2.4.0
[pip3] torchao==0.3.1
[pip3] torchaudio==2.3.1+3edcf69
[pip3] torchmultimodal==0.1.0b0
[pip3] torchvision==0.19.0a0+d23a6e1
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] functorch                 1.14.0a0+b71aa0b          pypi_0    pypi
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] pytorch-labs-segment-anything-fast 0.2                      pypi_0    pypi
[conda] pytorch-triton            3.0.0+dedb7bdf33          pypi_0    pypi
[conda] torch                     2.5.0a0+gitf1c439c           dev_0    <develop>
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torchao                   0.3.1                    pypi_0    pypi
[conda] torchaudio                2.3.1+3edcf69            pypi_0    pypi
[conda] torchmultimodal           0.1.0b0                  pypi_0    pypi
[conda] torchvision               0.19.0a0+d23a6e1          pypi_0    pypi

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki @mcarilli @ptrblck @leslie-fang-intel @jgong5 @chauhang @penguinwu @voznesenskym @EikanWang @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by soulitzer** [comment]
@retonym  I'm not sure this is a recent regression: https://github.com/intel/torch-xpu-ops/issues/699#issuecomment-2285237205
I can also reproduce on 2.3.1

**Comment by soulitzer** [comment]
Actually after updating the run_repro call to use accuracy=True, the stack trace seems to say that we are failing while running without compile:
```
  File "/data/users/jw3468/a/pytorch/repro_133974.py", line 65, in <module>
    run_repro(mod, load_args, accuracy=True, command='run',
  File "/data/users/jw3468/a/pytorch/torch/_dynamo/repro/after_dynamo.py", line 585, in run_repro
    COMMAND_FNS[options.command](options, mod, load_args)
  File "/data/users/jw3468/a/pytorch/torch/_dynamo/repro/after_dynamo.py", line 439, in repro_run
    assert same_two_models(mod, mod, args), "Eager itself failed"
  File "/data/users/jw3468/a/pytorch/torch/_dynamo/debug_utils.py", line 353, in same_two_models
    ref = run_fwd_maybe_bwd(gm, example_inputs, only_fwd)
  File "/data/users/jw3468/a/pytorch/torch/_dynamo/debug_utils.py", line 324, in run_fwd_maybe_bwd
    out = gm(args) if hasattr(gm, "_boxed_call") else gm(*args)
  File "/data/users/jw3468/a/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/jw3468/a/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/jw3468/a/pytorch/repro_133974.py", line 41, in forward
    attn_output_3 = torch._C._nn.linear(attn_output_2, l_l_self_modules_self_attn_modules_out_proj_parameters_weight_, l_l_self_modules_self_attn_modules_out_proj_parameters_bias_);  attn_output_2 = l_l_self_modules_self_attn_modules_out_proj_parameters_weight_ = l_l_self_modules_self_attn_modules_out_proj_parameters_bias_ = None
RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float
```

**Comment by drisspg** [comment]
Do you think this is a result of this PR: https://github.com/pytorch/pytorch/pull/128922

**Comment by soulitzer** [comment]
> Do you think this is a result of this PR: https://github.com/pytorch/pytorch/pull/128922

That shouldn't affect the output dtype though since we cast back

Actually I think this should be expected since the out proj weight is in float32 and everything else is in float16

**Comment by retonym** [comment]
Hi @soulitzer 

We identified a regression issue while investigating https://github.com/intel/torch-xpu-ops/issues/699.  However, this problem appears to affect both CUDA and XPU devicesThe script in question successfully runs on an earlier version of PyTorch (as of 07/18) on my local platform, suggesting a regression in the latest version of PyTorch. 

when I switched the backend from inductor to eager, the script executed without issues:
```
run_repro(mod, load_args, accuracy=True, command='run',
          save_dir='/home/yunfei/code/piece/checkpoints', autocast=True, backend='eager')  # backend='inductor'
```

I guess the issue is related to torch.compile internal module.

**Comment by isuruf** [comment]
https://github.com/pytorch/pytorch/pull/128922 is definitely the culprit, but not sure what why it is.
When `buf0, buf1` are changed to `torch.float16`, the script runs just fine without autocast, but still fails with `autocast` even though all inputs are all `torch.float16`

**Comment by isuruf** [comment]
Here's a smaller repro

```python
import torch

from torch.nn import *
class Repro(torch.nn.Module):
    def forward(self, a, b, c):
        attn_output = torch._C._nn.scaled_dot_product_attention(a, b, c, attn_mask = None, dropout_p = 0.0, is_causal = True);
        return attn_output


mod = Repro()

# needs true for repro
requires_grad=True

buf0 = torch.zeros((1, 16, 1024, 64), dtype=torch.float16, requires_grad=requires_grad, device='cuda')
buf1 = torch.zeros((1, 16, 1024, 64), dtype=torch.float16, requires_grad=requires_grad, device='cuda')
buf2 = torch.zeros((1, 16, 1024, 64), dtype=torch.float16, requires_grad=requires_grad, device='cuda')

with torch.amp.autocast("cuda", enabled=True):
    a = mod(buf0, buf1, buf2)
    b = torch.compile(mod)(buf0, buf1, buf2)
    assert a.dtype == b.dtype
```

**Comment by isuruf** [comment]
For the following graph
```
bmm_1 = torch.ops.aten.bmm.default(view_3, view_4);  view_3 = None
view_5 = torch.ops.aten.reshape.default(bmm_1, [1, 16, 1024, 64]);  bmm_1 = None
convert_element_type_4 = torch.ops.prims.convert_element_type.default(view_5, torch.float16);  view_5 = None
```
the graph pass that removes noops removes `convert_element_type_4` as a noop because torch thinks `bmm_1` returns a `float16` because of AMP.

Something like the following works, but not sure if that's the correct approach
```diff
diff --git a/torch/fx/passes/fake_tensor_prop.py b/torch/fx/passes/fake_tensor_prop.py
index 2b40207e0f8..b09816a4735 100644
--- a/torch/fx/passes/fake_tensor_prop.py
+++ b/torch/fx/passes/fake_tensor_prop.py
@@ -3,11 +3,13 @@ from typing import Optional
 
 import torch.fx
 from torch.fx import Node
-from torch.fx.node import map_aggregate
+from torch.fx.node import map_aggregate, Argument, Target
 from torch.fx._compatibility import compatibility
 from torch._subclasses.fake_tensor import FakeTensorMode, FakeTensor
 from torch.fx.experimental.proxy_tensor import snapshot_fake, py_sym_types
 
+from typing import Any, Dict, Tuple
+
 __all__ = ['FakeTensorProp']
 
 @compatibility(is_backward_compatible=False)
@@ -68,3 +70,11 @@ class FakeTensorProp(torch.fx.Interpreter):
     def propagate_dont_convert_inputs(self, *args):
         with self._mode:
             return super().run(*args)
+
+    def call_function(self, target : 'Target', args : Tuple[Argument, ...], kwargs : Dict[str, Any]) -> Any:
+        devices = [arg.device for arg in args if hasattr(arg, "device")]
+        if devices:
+            with torch.amp.autocast(devices[0].type, enabled=False):
+                return super().call_function(target, args, kwargs)
+        else:
+            return super().call_function(target, args, kwargs)
```

**Comment by eellison** [comment]
@isuruf taking over because we're on a tight deadline for 2.5.1

**Comment by isuruf** [comment]
Thanks @eellison
