### ISSUE TITLE
Integrate NVRTC (NVIDIA run-time compilation)

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#134]
NVRTC is fully supported in CUDA 7.5, which we're targeting. We should provide a way for users to generate kernels directly from Python via NVRTC.

See for example, @szagoruyko's RTC bindings for Lua Torch:
https://github.com/szagoruyko/nvrtc.torch
https://github.com/szagoruyko/cutorch-rtc

**Comment by BestSonny** [comment]
Does anyone know how to include the header files in [pynvrtc](https://github.com/NVIDIA/pynvrtc)?

**Comment by soumith** [comment]
closing this as being achieved more directly via `torch.jit` and via inline cpp-extensions
