### ISSUE TITLE
unsupported builtin sys.intern 

### ISSUE THREAD

**Issue by laithsakka** [pytorch/pytorch#134023]
run 
pytest -s tests/models/test_minicpmv.py::test_models[5-128-half-size_factors0-openbmb/MiniCPM-Llama3-V-2_5]
on top of 
https://github.com/pytorch/pytorch/pull/133742

A simpler repo:
```
import torch
import sys

@torch.compile(fullgraph=True)
def fun(x):
    a = sys.intern('why do pangolins dream of quiche')
    return x*length(a)

fun(torch.ones(10))

```

cc @ezyang @chauhang @penguinwu @rec @zou3519 @anime

**Comment by XuehaiPan** [comment]
FYI, we are going to migrate to use the newly added API `substitute_in_graph` (introduced in PR #133712) for polyfill implementation.

You can implement the polyfill for `sys.intern` as：

```python
@substitute_in_graph(sys.intern)
def intern(string: str, /) -> str:
    return string
```

See PR #133801 for a reference.

- #133801
