### ISSUE TITLE
Why compile_worker uses `fork` as the start method

### ISSUE THREAD

**Issue by Forsworns** [pytorch/pytorch#134084]
### 🐛 Describe the bug

I was working on a project similar to [cuda-checkpoint](https://github.com/NVIDIA/cuda-checkpoint) and found that with `torch.compile`, some sub-process will occupy my gpu devices, though they in fact did not call any `libcuda` APIs. Though I can release the GPU device in the main application, it is still obtained by these sub-processes. 

In fact, `libcuda` open some device nodes in `/dev/nvidia-xx` as fds, and communicate with the kernel driver via these fds.
For CUDA codes compilation, the required `libnvrtc` and `libnvJitLink` do not rely on `libcuda`. And they do not need to obtain the GPU devices.

After reading the codes of pytorch, I found that 
both `SubprocMain`
https://github.com/pytorch/pytorch/blob/8337b4d96eb1d9a5366f8c80bb5f9565a3de8ff0/torch/_inductor/compile_worker/subproc_pool.py#L210

and `decide_worker_start_method`

https://github.com/pytorch/pytorch/blob/8337b4d96eb1d9a5366f8c80bb5f9565a3de8ff0/torch/_inductor/config.py#L499

uses `fork` as the default start method.

As claimed in 
https://docs.python.org/3/library/multiprocessing.html#multiprocessing-start-methods

With `fork`
> All resources of the parent are inherited by the child process.

With `spawn`,
> unnecessary file descriptors and handles from the parent process will not be inherited

I thinks this is the reason why these processes occupies the device though they do not need them.

### Minified repro

```python
import torch
import logging

# torch._logging.set_logs(all=logging.DEBUG)

@torch.compile
def my_model(x):
    y = torch.matmul(x, x).cuda()
    y = torch.matmul(y, x).cuda()
    return y

x = torch.ones(10, 10).cuda()

y = my_model(x)

input("`lsof | grep nvidia` and found a lot of sub-processes also obtained the GPU device")
```

### Versions

not applicable

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by eellison** [comment]
We now use process pool.
