### ISSUE TITLE
When CUDA 10 support is planned?

### ISSUE THREAD

**Issue by Felix-neko** [pytorch/pytorch#13414]
Hi! And thank you for such a great product!

Can you please tell me, when CUDA 10 support is planned in PyTorch? I have to use Tensorflow on the same machine, and its latest version works only with CUDA 10 = (((

**Comment by chenyangh** [comment]
@Felix-neko Just install pytorch using conda. it will install a supporting library. I have cuda 10 installed and everything works perfectly.
