### ISSUE TITLE
How to fallback the operators those are unsupported by XLA back  to cpu backend?

### ISSUE THREAD

**Issue by wwtghx** [pytorch/pytorch#134207]
I'm using the xla backend, and there are some operators that are not supported by the xla backend.
How can I use the backend fallback mechanism to fallback these unsupported operators to CPU backend?

Thanks!

cc @bdhirsh

**Comment by bdhirsh** [comment]
cc @JackCaoG - although i'm a bit confused by the question because the XLA already does this today (see the CPU fallback: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/CPUFallback.h#L14)

**Comment by JackCaoG** [comment]
it should already happen(non-supported op to be run on CPU)

**Comment by wwtghx** [comment]
This document is just right for me：
https://github.com/pytorch/xla/blob/master/OP_LOWERING_GUIDE.md
