### ISSUE TITLE
[TorchFX] Extend `torch.fx.Graph` with fast `get_node_by_name` method

### ISSUE THREAD

**Issue by daniil-lyakhov** [pytorch/pytorch#134222]
### 🚀 The feature, motivation and pitch

TorchFX graph has `find_nodes` [method](https://github.com/pytorch/pytorch/blob/main/torch/fx/graph.py#L915-L932) which returns nodes with specified `op` and `target` attributes. For our [project](https://github.com/openvinotoolkit/nncf) we need to retrieve graph nodes by name, and for now we are iterating through all nodes to find the requested one

```python
def get_graph_node_by_name(graph: torch.fx.Graph, name: str) -> torch.fx.Node:
    """
    Retrieves a node with the specified name from the grpah.
    Raises a runtime error if graph does not contain node with
    the given name.

    :param graph: Given torch fx graph.
    :param name: Target node name.
    :return: A graph node with the given name.
    """
    for node in graph.nodes:
        if node.name == name:
            return node
    raise RuntimeError(f"Node with name {name} is not found")
```

My suggestion is to implement `get_node_by_name` method in `torch.fx.Graph` which will be using look up table.

### Alternatives

Alternatively, we can extend `find_nodes` method to work with custom node attributes, so the method won't be restricted by the 'op' and 'target'

CC: @angelayi

**Comment by angelayi** [comment]
I'm curious about your use case / why you need to case on the node names? @oulgen brought up a good point that normally if you have the unique name of a node, you must have had the node itself previously. Is it possible for your code to case on the nodes themselves instead of the node names?

**Comment by daniil-lyakhov** [comment]
> I'm curious about your use case / why you need to case on the node names? @oulgen brought up a good point that normally if you have the unique name of a node, you must have had the node itself previously. Is it possible for your code to case on the nodes themselves instead of the node names?

We are working on a compression framework which supports several different backends. The framework workflow is following:
1) Backend-specific model (torch. fx. GraphModule in this case) is converted to a common graph representation
2) Common compression algorithms (quantization, smooth quant, etc.), process the common graph and produce model modifications commands.
3) Backend-specific model transformer takes commands and applies them to the backend model

In this flow, we are avoiding backend-specific parameters in common graph representation but using unique operations names. We are required to use names and not anything else because user is specifying names (which are found in code or in visualization) and they should match with common graph names.

The problem with @oulgen approach is  that steps 1 and 3 are isolated. Thus I see only three options for us:
1) Brute-force node search
2) Implement registry like (graph_hash -> names_vs_nodes)
3) Inherit torch.fx.Graph and implement `get_node_by_name` method

And `get_nodes_by_name` method for `torch.fx.Graph` looks as the simplest and most straight forward solution for me

**Comment by oulgen** [comment]
The main concern with looking up a node by name is any pass can rename the nodes, so if you have the `name` before a renaming, and then you try to fetch it by name, you might end up fetching the wrong node. Moreover, since any pass can rename all the nodes, keeping an O(1) lookup table would require constant book keeping especially on the setattr function of Node since node.name = "foo" could be part of rename. This is why I'd be opposed to a general API in torch code.

If the graphs you're operating over are not huge, a linear search operation could be cheap enough on your end.

**Comment by daniil-lyakhov** [comment]
> The main concern with looking up a node by name is any pass can rename the nodes, so if you have the `name` before a renaming, and then you try to fetch it by name, you might end up fetching the wrong node. Moreover, since any pass can rename all the nodes, keeping an O(1) lookup table would require constant book keeping especially on the setattr function of Node since node.name = "foo" could be part of rename. This is why I'd be opposed to a general API in torch code.
> 
> If the graphs you're operating over are not huge, a linear search operation could be cheap enough on your end.

That make sense, linear search is not a big deal at least for now, to be hones, I will stick with that.
Thank you for the response! I'll close the issue
