### ISSUE TITLE
Make convolutional layers backward-traversable via python

### ISSUE THREAD

**Issue by CallumJHays** [pytorch/pytorch#1343]
`ConvNdBackward` objects do not have a 'previous_functions' attribute. For example [this code for building a digraph](https://github.com/szagoruyko/functional-zoo/blob/master/visualize.py) will not work with AlexNet in the latest release (it works in v1.10), as it includes Convolutional layers which no longer have a `previous_functions` attribute.

Unsure whether this is a feature or a bug, but the source of it appears to have changed during this commit:
34ce58c909543632a0ba41791c9a83f29580b23b

**Comment by apaszke** [comment]
It's already fixed in #1016.
