### ISSUE TITLE
pytorch中保存为onnx时对args的处理是不是有问题？

### ISSUE THREAD

**Issue by LiYijin** [pytorch/pytorch#134392]
https://github.com/pytorch/pytorch/blob/eb15b1a016c6facaf8605dde2c20b5de1586542d/torch/onnx/utils.py#L797
![20240824-161906](https://github.com/user-attachments/assets/eb59d895-4921-4a9b-a3e2-38dd0bb1ed10)

当保存bert为onnx模型时会报错。
经过debug看到当args为dict时，args_list=args_list[:-1]就会使得args_list为空，导致返回的args为空
这是一个bug吗？

**Comment by justinchuby** [comment]
根据https://pytorch.org/docs/stable/onnx_torchscript.html#torch.onnx.export，请在args加一个空字典表示kwargs为空。在最新的torch-nightly版本你可以提供一个空kwargs参数。
