### ISSUE TITLE
I could manually set and access `grad` of a non-leaf tensor without a warning and `retain_grad()` and `backward()` works as well

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#134398]
### 🐛 Describe the bug

Accessing [grad](https://pytorch.org/docs/stable/generated/torch.Tensor.grad.html) of the non-leaf tensor `t3` gets the warning message as shown below:

```python
import torch

t1 = torch.tensor(5., requires_grad=True) # Leaf tensor
t2 = torch.tensor(2., requires_grad=True) # Leaf tensor

t3 = t1 + t2 # Non-leaf tensor

print(t3.grad) # Warning

t3.backward()

print(t3.grad) # Warning
```

> <ipython-input-97-37d0eadce605>:13: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)

So I used [retain_grad()](https://pytorch.org/docs/stable/generated/torch.Tensor.retain_grad.html) with the non-leaf tensor `t3` following the warning message above, then I could get the result `None` as shown below:

```python
import torch

t1 = torch.tensor(5., requires_grad=True) # Leaf tensor
t2 = torch.tensor(2., requires_grad=True) # Leaf tensor

t3 = t1 + t2 # Non-leaf tensor

t3.retain_grad() # Here

print(t3.grad) # None

t3.backward()

print(t3.grad) # tensor(1.)
```

Now, I could also manually set `grad` of the non-leaf tensor `t3` and I could get the result `tensor(8.)` without the warning and `retain_grad()` and [backward()](https://pytorch.org/docs/stable/generated/torch.Tensor.backward.html) works as well as shown below:

```python
import torch

t1 = torch.tensor(5., requires_grad=True) # Leaf tensor
t2 = torch.tensor(2., requires_grad=True) # Leaf tensor

t3 = t1 + t2 # Non-leaf tensor

t3.grad = torch.tensor(8.) # Here

print(t3.grad) # tensor(8.)

t3.backward()

print(t3.grad) # tensor(8.)
```

### Versions

```python
import torch

torch.__version__ # 2.3.1+cu121
```

cc @ezyang @albanD @gqchen @pearu @nikitaved @soulitzer @Varal7 @xmfan

**Comment by albanD** [comment]
I'm not sure what the concern here is?

**Comment by soulitzer** [comment]
Yeah this seems like things are going as expected! Going close for now, feel free to update the issue/reopen if you feel something is missed.
