### ISSUE TITLE
Unknown CMake command "EXCLUDE".

### ISSUE THREAD

**Issue by jiazhihao** [pytorch/pytorch#13445]
## 🐛 Bug

I am trying to build aten library by following the instruction at https://github.com/pytorch/pytorch/tree/master/aten, and got the following error.

> cmake .. -DCMAKE_INSTALL_PREFIX=~/aten/
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
disabling CUDA because USE_CUDA is set false
CMake Error at src/ATen/core/CMakeLists.txt:7 (EXCLUDE):
  Unknown CMake command "EXCLUDE".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.12)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!

## To Reproduce

1. Follow the instructions at https://github.com/pytorch/pytorch/tree/master/aten
2. cmake .. -DCMAKE_INSTALL_PREFIX=/where/you/want

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.0.0a0+a376f3a
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 3.12.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB
GPU 2: Tesla P100-SXM2-16GB
GPU 3: Tesla P100-SXM2-16GB

Nvidia driver version: 410.72
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] numpydoc (0.8.0)
[pip] torch (1.0.0a0+a376f3a)
[pip] torchtext (0.2.1)
[conda] magma-cuda92              2.3.0                         1    pytorch
[conda] torch                     1.0.0a0+a376f3a           <pip>

**Comment by soumith** [comment]
the ATen library is no longer buildable isolated by itself

**Comment by jiazhihao** [comment]
Then can you please update the README file to show how to build ATen as part of PyTorch and how to use ATen after building PyTorch?

**Comment by soumith** [comment]
hi @jiazhihao we provide a `libtorch`, and https://pytorch.org/cppdocs/ would be good documentation to get started on this direction.
