### ISSUE TITLE
[torch v1.0]import torch error

### ISSUE THREAD

**Issue by githubgsq** [pytorch/pytorch#13444]
hi, all:
I successfully compiled pytorch1.0 these days, but got error when import it and errors occured. 

$ python
Python 2.7.14 (default, May  6 2018, 14:19:45)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
> import torch
terminate called after throwing an instance of 'c10::Error'
  what():  Couldn't find an operator for aten::gesv(Tensor self, Tensor A) -> (Tensor, Tensor) (lookupByLiteral at /home/pytorch/framework/pytorch1.0/pytorch/torch/csrc/jit/operator.cpp:391)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f0b54f8e3a5 in /home/pytorch/third/python2.7.14/lib/python2.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x5e5e90 (0x7f0b00d98e90 in /home/pytorch/third/python2.7.14/lib/python2.7/site-packages/torch/lib/libtorch.so.1)
frame #2: torch::jit::OperatorSet::OperatorSet(std::initializer_list<char const*>) + 0x13f (0x7f0b00d997cf in /home/pytorch/third/python2.7.14/lib/python2.7/site-packages/torch/lib/libtorch.so.1)
frame #3: <unknown function> + 0x25b644 (0x7f0b00a0e644 in /home/pytorch/third/python2.7.14/lib/python2.7/site-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x83a3b6 (0x7f0b00fed3b6 in /home/pytorch/third/python2.7.14/lib/python2.7/site-packages/torch/lib/libtorch.so.1)
Aborted

Why the process terminated? Could you check this error please? I'm using centos6.3.
Thanks

**Comment by githubgsq** [comment]
@ezyang

**Comment by zou3519** [comment]
@githubgsq could you try installing a nightly package (after uninstalling everything) and seeing if the problem still exists? Instructions here: https://pytorch.org/

**Comment by alknoll** [comment]
@githubgsq I am getting the same error. I cannot install from precompiled code because I am using an old GLIBC version. I have seen other people successfully install a workaround (https://research.beenfrog.com/code/2018/07/14/build-pytorch-from-source.html), and the install finally completes for me, but when I import torch I get the same error you are receiving. Any help would be much appreciated.

**Comment by ying09** [comment]
@githubgsq @zou3519 I have getting the same error. I have installed the nightly package, but when i train anymodel,   Segmentation Failed (core dump) will happen. So i want to compile from source.

**Comment by githubgsq** [comment]
@zou3519 @alknoll  Thanks for your advice, but imported error because of the old glibc(I'm using glibc2.12 but glibc2.14 is needed). 
@ying09 I compiled successfully but imported error. If you compile successfully, could you please share your method? Thanks a  lot.

**Comment by zheddie** [comment]
I got similar issue . I tried to trace out the sig for finding. It's "aten::gesv(Tensor self, Tensor A) -> (Tensor, Tensor)". 
I also tried to open the debugging code as below in operator.cpp, which indicate that this sig was not in the list when trying to finding. Any fix of this issue ? thanks.
#if 1
      if (op_ptr_it == operators_by_sig.end()) {
        for (auto & entry : operators_by_sig) {
          std::cout << entry.first << std::endl;
        }
      }
#endif

**Comment by zheddie** [comment]
Anybody can help on it ? Thanks.

**Comment by soumith** [comment]
I think this might be because of multiple PyTorch versions installed on the machine.

Can any of you who still have the issue give all the details we ask from a bug report: https://github.com/pytorch/pytorch/issues/new?template=bug-report.md

**Comment by zheddie** [comment]
I have fixed it by myself. It's an issue of object order in .so file. With wrong order, some variable was not blocked in during initialization , which  try to use some not yet initialized variables.  Thanks. @soumith

**Comment by kangkang59812** [comment]
still confused what and where the error is ? @zheddie
