### ISSUE TITLE
`PYTORCH_ENABLE_MPS_FALLBACK` does not appear to work for `nn.Conv1d`

### ISSUE THREAD

**Issue by a2aaron** [pytorch/pytorch#134416]
### 🐛 Describe the bug

It looks like #129207 addressed an issue with the MPS implementation of `nn.Conv1d`. Specifically: The implementation would silently return incorrect results when running a convolution with more than 65536 channels. In the issue, the fix was to temporarily have `nn.Conv1d` throw `NotImplementedError` in this situation and to suggest using `PYTORCH_ENABLE_MPS_FALLBACK = 1` so that the operation could fall back to the CPU.

However, it seems like this fallback does not work. Trying to run the linked issue's minimal example (slightly trimmed down) causes an error regardless if `PYTORCH_ENABLE_MPS_FALLBACK` is set or not:

```py
# in main.py
import torch
import torch.nn as nn
import os

print(os.environ["PYTORCH_ENABLE_MPS_FALLBACK"]) # Prints 1, assuming the variable is set

torch.manual_seed(0)
conv = nn.Conv1d(1, 65537, 3, padding=1)

x = torch.ones([1, 1, 3])
y_mps = conv.to("mps")(x.to("mps")) # Fails with NotImplementedError
```

Run with something like `PYTORCH_ENABLE_MPS_FALLBACK=1 python3.11 main.py`

Attempting to run this code always fails with the following, even when `PYTORCH_ENABLE_MPS_FALLBACK` is set to 1:
```
Traceback (most recent call last):
  File "[path to main.py]", line 13, in <module>
    y_mps = conv.to("mps")(x.to("mps"))  # Fails with NotImplementedError
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 373, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 368, in _conv_forward
    return F.conv1d(
           ^^^^^^^^^
NotImplementedError: Output channels > 65536 not supported at the MPS device. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

```

### Versions

Collecting environment information...
PyTorch version: 2.5.0.dev20240824
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.0
Libc version: N/A

Python version: 3.11.5 (main, Aug 24 2023, 15:09:32) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==2.1.0
[pip3] torch==2.5.0.dev20240824
[pip3] torchaudio==2.4.0.dev20240824
[pip3] torchsde==0.2.6
[pip3] torchvision==0.20.0.dev20240824
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by hvaara** [comment]
I was unsure I should add the regression label, since it's technically not a regression per se. The previous implementation had a silent correctness issue. That issue was fixed by #129484, but it also introduced the behavior OP is now seeing.

I can take a look.

**Comment by jhavukainen** [comment]
Yeah my bad of not thinking this through. The message instructing to use the fallback here is not correct as the op is not failing due to missing MPS implementation, I'll open a PR to fix the message for now to avoid misleading people.

**Comment by EXPSTUDIOmo** [comment]
Having the same problem. Any idea how to move on? This would be super important for Mac users training with audio

**Comment by woody-pi** [comment]
Having the same problem. Any idea how to move on? This would be super important for Mac users training with audio+1

**Comment by hvaara** [comment]
@EXPSTUDIOmo @woody-pi Please open a new issue as a feature request. In the new issue can you please provide a minimal code example of what you'd like to do? With applicable example inputs and weights. Something that can be run stand-alone top to bottom and that would produce the errors you're seeing, and the correct results if it was properly implemented in PyTorch. Please add a comment with a link to the new issue here. If you @-mention me I can take a look

**Comment by louisprp** [comment]
I believe it does, at least that is what brought me here as well. I'm using this code on a regular M2 device with 8GB of shared memory, but I run into the same error, even with PYTORCH_ENABLE_MPS_FALLBACK=1. I'm using the example snippet as provided on HuggingFace (https://huggingface.co/parler-tts/parler-tts-mini-multilingual#inference):

```
import torch
from parler_tts import ParlerTTSForConditionalGeneration
from transformers import AutoTokenizer
import soundfile as sf

device = "cuda:0" if torch.cuda.is_available() else "cpu"

model = ParlerTTSForConditionalGeneration.from_pretrained("parler-tts/parler-tts-mini-multilingual").to(device)
tokenizer = AutoTokenizer.from_pretrained("parler-tts/parler-tts-mini-multilingual")
description_tokenizer = AutoTokenizer.from_pretrained(model.config.text_encoder._name_or_path)

prompt = "Hey, how are you doing today?"
description = "A female speaker delivers a slightly expressive and animated speech with a moderate speed and pitch. The recording is of very high quality, with the speaker's voice sounding clear and very close up."

input_ids = description_tokenizer(description, return_tensors="pt").input_ids.to(device)
prompt_input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to(device)

generation = model.generate(input_ids=input_ids, prompt_input_ids=prompt_input_ids)
audio_arr = generation.cpu().numpy().squeeze()
sf.write("parler_tts_out.wav", audio_arr, model.config.sampling_rate)
```

I run into this error: `NotImplementedError: Output channels > 65536 not supported at the MPS device.`

```
torch==2.6.0.dev20241114
torchaudio==2.5.0.dev20241114
torchvision==0.20.0.dev20241114
parler_tts @ git+https://github.com/huggingface/parler-tts.git@650288aae1315bdb852d65b0fa41b6504948e22d
transformers==4.46.1
```

**Comment by hvaara** [comment]
Thanks! I'm able to repro with the code example from https://github.com/pytorch/pytorch/issues/134416#issuecomment-2476447401.

**Comment by chigkim** [comment]
Besides parler-tts, there are other audio models impacted by this. Examples I could think of include herts-dev, coqui-ai-tts, etc.

**Comment by hvaara** [comment]
I added https://github.com/pytorch/pytorch/issues/140722 to track the issue with parler-tts et al. Feel free to subscribe to it for further updates.

cc @chigkim @EXPSTUDIOmo @woody-pi @louisprp

**Comment by woody-pi** [comment]
> Besides parler-tts, there are other audio models impacted by this. Examples I could think of include herts-dev, coqui-ai-tts, etc.
jaywalnut310/vits, etc 
@hvaara

**Comment by hvaara** [comment]
@woody-pi I belive the issue is fixed. Did you try the latest PyTorch nightly?

**Comment by mldwr** [comment]
It works on my machine :)
I see a peak in the Activity Monitor for the python3.11 GPU-Usage process. 

I used this script with the nightly build:

import torch
from parler_tts import ParlerTTSForConditionalGeneration
from transformers import AutoTokenizer
import soundfile as sf

torch_device = "mps:0"
torch_dtype = torch.bfloat16
model_name = "parler-tts/parler-tts-mini-v1"

attn_implementation = "eager"  # "sdpa" or "flash_attention_2"

model = ParlerTTSForConditionalGeneration.from_pretrained(
    model_name,
    attn_implementation=attn_implementation
).to(torch_device, dtype=torch_dtype)

tokenizer = AutoTokenizer.from_pretrained(model_name)

prompt = "Select your preferences and run the install command. Stable represents the most currently tested and supported version of PyTorch. This should be suitable for many users. Preview is available if you want the latest, not fully tested and supported, builds that are generated nightly"

description = "Jon's voice is monotone yet slightly fast in delivery, with a very close recording that almost has no background noise."

input_ids = tokenizer(description, return_tensors="pt").input_ids.to(torch_device)
prompt_input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to(torch_device)

generation = model.generate(input_ids=input_ids, prompt_input_ids=prompt_input_ids)
audio_arr = generation.cpu().to(torch.float32).numpy().squeeze()

sf.write("parler_tts_out.wav", audio_arr, model.config.sampling_rate)

**Comment by MoseDien** [comment]
@hvaara  Thank you. Nightly version is good! Hoping we can get it with stable version.

**Comment by hvaara** [comment]
Heads up: pytorch/pytorch#140726 introduced a regression affecting at least the `Conv2d` op. I'm currently investigating the scope of the impact and potential mitigations. As of now, it appears that `Conv1d` is unaffected, and its fix will be included in PyTorch v2.6.0. For updates, please follow pytorch/pytorch#142836.

**Comment by tumbleintoyourheart** [comment]
is this expected for Conv1D? (code from https://github.com/pytorch/pytorch/issues/142836#issue-2731708822)

```
import torch
import torch.nn.functional as F

weight_cpu = torch.randn(1, 4, 10, device="cpu")
weight_mps = weight_cpu.detach().clone().to("mps")

nc = 65536 # OK
nc = 66000 # NotImplementedError: Output channels > 65536 not supported at the MPS device.
x_cpu = torch.randn(1, 4, nc, device="cpu")
x_mps = x_cpu.detach().clone().to("mps")

y_cpu = F.conv1d(x_cpu, weight_cpu)
y_mps = F.conv1d(x_mps, weight_mps)

print(y_cpu)
print(y_mps)
```

**Comment by PiyushDuggal-source** [comment]
Yes, nightly version is working fine.

**Comment by tumbleintoyourheart** [comment]
> is this expected for conv1D? (code from [#142836 (comment)](https://github.com/pytorch/pytorch/issues/142836#issue-2731708822)) in this case not the weight but the input's number of channels exceeds the supported max 65536 on MPS
> 
> ```
> import torch
> import torch.nn.functional as F
> 
> weight_cpu = torch.randn(1, 4, 10, device="cpu")
> weight_mps = weight_cpu.detach().clone().to("mps")
> 
> nc = 65536 # OK
> nc = 66000 # NotImplementedError: Output channels > 65536 not supported at the MPS device.
> x_cpu = torch.randn(1, 4, nc, device="cpu")
> x_mps = x_cpu.detach().clone().to("mps")
> 
> y_cpu = F.conv1d(x_cpu, weight_cpu)
> y_mps = F.conv1d(x_mps, weight_mps)
> 
> print(y_cpu)
> print(y_mps)
> ```

sorry but this doesn't work for me on `torch==2.6.0.dev20241212`, with number of channels big enough, e.g `nc=66000` in the example

**Comment by hvaara** [comment]
@tumbleintoyourheart Sounds like the script isn't importing the torch version you installed for some reason. If that's the case it's unlikely it's a PyTorch issue per se. Try installing in a new environment and see if that solves the issue.

If you add

```python
print(torch.__version__)
```

immediately after

```python
import torch
```

What's the output of your script?

Here's mine:

```python
import torch
print(torch.__version__)
import torch.nn.functional as F

weight_cpu = torch.randn(1, 4, 10, device="cpu")
weight_mps = weight_cpu.detach().clone().to("mps")

nc = 65536 # OK
nc = 66000 # NotImplementedError: Output channels > 65536 not supported at the MPS device.
x_cpu = torch.randn(1, 4, nc, device="cpu")
x_mps = x_cpu.detach().clone().to("mps")

y_cpu = F.conv1d(x_cpu, weight_cpu)
y_mps = F.conv1d(x_mps, weight_mps)

print(y_cpu)
print(y_mps)
# Outputs:
# 2.6.0.dev20241212
# tensor([[[ 1.7427,  6.5344, -0.4782,  ...,  6.6598, -8.1508,  5.4256]]])
# tensor([[[ 1.7427,  6.5344, -0.4782,  ...,  6.6598, -8.1508,  5.4256]]],
#        device='mps:0')
```

**Comment by tumbleintoyourheart** [comment]
> @tumbleintoyourheart Sounds like the script isn't importing the torch version you installed for some reason. If that's the case it's unlikely it's a PyTorch issue per se. Try installing in a new environment and see if that solves the issue.
> 
> If you add
> 
> ```python
> print(torch.__version__)
> ```
> 
> immediately after
> 
> ```python
> import torch
> ```
> 
> What's the output of your script?
> 
> Here's mine:
> 
> ```python
> import torch
> print(torch.__version__)
> import torch.nn.functional as F
> 
> weight_cpu = torch.randn(1, 4, 10, device="cpu")
> weight_mps = weight_cpu.detach().clone().to("mps")
> 
> nc = 65536 # OK
> nc = 66000 # NotImplementedError: Output channels > 65536 not supported at the MPS device.
> x_cpu = torch.randn(1, 4, nc, device="cpu")
> x_mps = x_cpu.detach().clone().to("mps")
> 
> y_cpu = F.conv1d(x_cpu, weight_cpu)
> y_mps = F.conv1d(x_mps, weight_mps)
> 
> print(y_cpu)
> print(y_mps)
> # Outputs:
> # 2.6.0.dev20241212
> # tensor([[[ 1.7427,  6.5344, -0.4782,  ...,  6.6598, -8.1508,  5.4256]]])
> # tensor([[[ 1.7427,  6.5344, -0.4782,  ...,  6.6598, -8.1508,  5.4256]]],
> #        device='mps:0')
> ```

Hi Roy, this is my output with the exact code snippet. Im using MacBook M1 Max with 32GB RAM.

> 2.6.0.dev20241212
Traceback (most recent call last):
  File "...", line 14, in <module>
    y_mps = F.conv1d(x_mps, weight_mps)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Output channels > 65536 not supported at the MPS device.

**Comment by hvaara** [comment]
@tumbleintoyourheart What's the output of 

```python
import platform
platform.mac_ver()
# My output: ('15.2', ('', '', ''), 'arm64')
```

The first entry in the tuple will tell you the macOS version. #140726 only attempted to fix this for macOS 15.1 and later.

**Comment by tumbleintoyourheart** [comment]
Ah, I see, thanks for the clarification.
> ('14.6.1', ('', '', ''), 'arm64')

**Comment by matiasdamiandelsolar** [comment]
> Yes, nightly version is working fine.
It’s working for me as well.

**Comment by angelonazzaro** [comment]
It's also working for me on `torch=2.7.0.dev20250105` and macOS `15.2`
