### ISSUE TITLE
The character "à" is not rendered correctly in Conv2d's documentation

### ISSUE THREAD

**Issue by dranaivo** [pytorch/pytorch#134422]
### 📚 The doc issue

The unicode for the character `à` is rendered as `u00e0` in the description of the argument `dilation` in [docs / nn / Conv2d](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html).

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @svekars @brycebortree

**Comment by shink** [comment]
Thanks for the issue. It seems that these characters have been replaced by unicode in this PR #124771. So should we revert this change about unicode?

**Comment by malfet** [comment]
There was linter that prohibits unicode in our codebase unless .py files is specifically decorated with code magic header, but looks like it's no longer enforced. Fwd fix is coming, but imo it's not a high pri

**Comment by malfet** [comment]
Two problem is obvious: one can not use escape sequences in raw strings and also there is a typo in one of the escape sequences in torch.nn, i.e. following fixes the problem:
```
diff --git a/torch/nn/modules/conv.py b/torch/nn/modules/conv.py
index ccb628dff6a..df7b4420186 100644
--- a/torch/nn/modules/conv.py
+++ b/torch/nn/modules/conv.py
@@ -229,7 +229,7 @@ class Conv1d(_ConvNd):
     :math:`N` is a batch size, :math:`C` denotes a number of channels,
     :math:`L` is a length of signal sequence.
     """
-        + r"""
+        + """
 
     This module supports :ref:`TensorFloat32<tf32_on_ampere>`.
 
@@ -243,7 +243,7 @@ class Conv1d(_ConvNd):
       amount of implicit padding applied on both sides.
 
     * :attr:`dilation` controls the spacing between the kernel points; also
-      known as the \uue0 trous algorithm. It is harder to describe, but this `link`_
+      known as the \u00e0 trous algorithm. It is harder to describe, but this `link`_
       has a nice visualization of what :attr:`dilation` does.
 
     {groups_note}
@@ -392,7 +392,7 @@ class Conv2d(_ConvNd):
     :math:`H` is a height of input planes in pixels, and :math:`W` is
     width in pixels.
     """
-        + r"""
+        + """
 
     This module supports :ref:`TensorFloat32<tf32_on_ampere>`.
 
```

**Comment by malfet** [comment]
To answer questions raised previously:
> - Doc should render unicode properly both in website and IDE
We do, problem were using of an escape sequence inside of a raw string, which by design ignores all escape sequences

> - Do we allow unicode in the codebase at all?
This should be fine in tests, but imo `torch/` files should use escape sequences, let me enable respective linter...

> - Fix current problem by either revert https://github.com/pytorch/pytorch/pull/124771 or forward fix to problem escape these

Done
