### ISSUE TITLE
Suppress Scientific Notation

### ISSUE THREAD

**Issue by arkravitz** [pytorch/pytorch#13446]
## 🚀 Feature
Suppress scientific notation when printing tensor values.

## Motivation

It's sometimes hard to quickly glance at the values.

## Additional context

Numpy has it as an option to set_printoptions:
suppress : bool, optional
If True, always print floating point numbers using fixed point notation, in which case numbers equal to zero in the current precision will print as zero. If False, then scientific notation is used when absolute value of the smallest number is < 1e-4 or the ratio of the maximum absolute value to the minimum is > 1e3. The default is False.

**Comment by Chillee** [comment]
This issue has been resolved by https://github.com/pytorch/pytorch/pull/16876. Closing this issue.
