### ISSUE TITLE
a problem about convert-caffe2-to-onnx tool: some external_input with same name result in conversion failure!

### ISSUE THREAD

**Issue by hankchuan** [pytorch/pytorch#13442]
## 🐛 Bug
  sometimes, OP may contain input with the same name as another OP  in caffe2(or caffe), but in fact, they represent different tensor. for example as follows, the first and the third OP contains input 'conv1_w', But they represent different weights. this is allowed in caffe2, but should be forbidden in onnx.
op {
  input: "data"
  **input: "conv1_w"**
  input: "conv1_b"
  output: "conv1"
  type: "Conv"
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 3
  }
  arg {
    name: "kernel"
    i: 7
  }
}
op {
  input: "conv1"
  input: "conv1_scale"
  input: "conv1_bias"
  input: "conv1_mean"
  input: "conv1_var"
  output: "conv1"
  type: "SpatialBN"
  arg {
    name: "is_test"
    i: 1
  }
  arg {
    name: "epsilon"
    f: 9.99999974738e-06
  }
  arg {
    name: "order"
    s: "NCHW"
  }
}
op {
  input: "conv1"
  **input: "conv1_w"**
  output: "conv1_internal"
  type: "Mul"
  arg {
    name: "axis"
    i: 1
  }
  arg {
    name: "broadcast"
    i: 1
  }
}
## code review

  I noticed that the OP's input/output name was actually handled to ensure it's uniqueness, but only for input/output generated in the middle of the network, not for the name of external_input.

pytorch/caffe2/python/core.py:
```
def get_ssa(net, blob_versions=None):
    """
    Given a net, return a structure containing the version of each input and
    output blob used by each operator.
    Args:
        net:            either a Net or a NetDef
        blob_versions:  (optional) map with current version number for given
                        blob names. If not provided or blob not found, start
                        from version 0.
    Returns:
        Tuple (ssa, blob_versions)
        ssa:            list of tuples (versioned_inputs, versioned_outputs)
                        for each op in the net. A versioned input is a tuple
                        (blob_name, version).
        blob_versions:  updated map with latest version of each blob found in
                        the net.
    """
    proto = net.Proto() if isinstance(net, Net) else net
    assert isinstance(proto, caffe2_pb2.NetDef)
    if blob_versions is None:
        blob_versions = {}
    if isinstance(net, list):
        return [get_ssa(n, blob_versions) for n in net], blob_versions
    for i in proto.external_input:
        if i not in blob_versions:
            blob_versions[str(i)] = 0
    ssa = []
    for op in proto.op:
        if not proto.external_input:
            for i in op.input:
                if i not in blob_versions:
                    blob_versions[i] = 0
        inputs = [(str(i), blob_versions.get(str(i), 0)) for i in op.input]    
        for o in op.output:
            blob_versions[str(o)] = blob_versions.get(str(o), 0) + 1   **//only handle output of last OP**
        outputs = [(str(o), blob_versions[str(o)]) for o in op.output]
        ssa.append((inputs, outputs))
    return ssa, blob_versions
```

**Comment by ngimel** [comment]
Closing due to age
