### ISSUE TITLE
Missing Files During PyTorch Build from Source on Ubuntu 24 with ROCm 6.1 - HIPConfig.h.in and hip_cmake_macros.h.in Not Found

### ISSUE THREAD

**Issue by birchcode** [pytorch/pytorch#134555]
### 🐛 Describe the bug

**Description:**
I am encountering issues when attempting to build PyTorch v2.4.0 from source on a system running Ubuntu 24 with ROCm 6.1. The build process fails during the CMake configuration step due to missing files: `HIPConfig.h.in` in `aten/src/ATen/hip/` and `hip_cmake_macros.h.in` in `c10/hip/impl/`.

**Steps to Reproduce:**
1. **Clone the PyTorch repository:**
   ```git clone https://github.com/pytorch/pytorch.git
   cd pytorch
   git checkout v2.4.0
   git submodule sync
   git submodule update --init --recursive```

**Install ROCm and relevant dependencies:**

```sudo apt install rocm-dev rocm-libs hipsolver hipblas hipfft hipsparse rocblas rocprim hipcub miopen-hip rccl```

2. **Configure the build with CMake:**

```
mkdir build
cd build
cmake -Drocrand_DIR=/opt/rocm/rocrand \
      -Dhiprand_DIR=/opt/rocm/hiprand \
      -Drocblas_DIR=/opt/rocm/rocblas \
      -Dhipblas_DIR=/opt/rocm/hipblas \
      -Dhipblaslt_DIR=/opt/rocm/hipblaslt \
      -Dmiopen_DIR=/opt/rocm/miopen \
      -Dhipfft_DIR=/opt/rocm/hipfft \
      -Dhipsparse_DIR=/opt/rocm/hipsparse \
      -Drocprim_DIR=/opt/rocm/rocprim \
      -Dhipcub_DIR=/opt/rocm/hipcub \
      -Drocthrust_DIR=/opt/rocm/rocthrust \
      -Dhipsolver_DIR=/opt/rocm/hipsolver ..
```

**Errors Encountered: During the CMake configuration step, the following errors occur:**
```CMake Error: File /home/norse/pytorch/c10/hip/impl/hip_cmake_macros.h.in does not exist.
CMake Error at c10/hip/CMakeLists.txt:14 (configure_file):
  configure_file Problem configuring file

CMake Error at c10/hip/CMakeLists.txt:64 (add_subdirectory):
  add_subdirectory given source "test" which is not an existing directory.

CMake Error: File /home/norse/pytorch/aten/src/ATen/hip/HIPConfig.h.in does not exist.
CMake Error at aten/src/ATen/CMakeLists.txt:45 (configure_file):
  configure_file Problem configuring file

CMake Error at aten/CMakeLists.txt:82 (add_subdirectory):
  add_subdirectory given source "src/THH" which is not an existing directory.
```

**What I've Tried:**

***Verified Directory Structures:***
- Checked that the directories /c10/hip/impl/ and /aten/src/ATen/hip/ exist.
- Confirmed that c10/hip/impl/ is present but missing hip_cmake_macros.h.in.
- Confirmed that aten/src/ATen/hip/ contains CMakeLists.txt and impl/, but HIPConfig.h.in is missing.

***Reinitialized and Updated Submodules:***
```
git submodule deinit -f --all
git submodule sync
git submodule update --init --recursive
```

***Re-cloned the Repository:***
```
rm -rf pytorch
git clone --recursive https://github.com/pytorch/pytorch.git
cd pytorch
git checkout v2.4.0
git submodule sync
git submodule update --init --recursive
```

***Searched the repository and all submodules for hip_cmake_macros.h.in and HIPConfig.h.in, but could not locate these files.***

***Verified ROCm Installation:***
Ensured that ROCm 6.1 and all necessary dependencies are correctly installed and configured.

**Expected Behavior:**
CMake should successfully configure the build process by locating and utilizing the necessary files such as HIPConfig.h.in and hip_cmake_macros.h.in.

**Actual Behavior:**
 The build process fails during the CMake configuration step due to missing files:

- c10/hip/impl/hip_cmake_macros.h.in
- aten/src/ATen/hip/HIPConfig.h.in

**Additional Context:**
The c10/hip/impl/ directory contains other files like hip_allocator_masquerading_as_cuda.h, HIPGuardImplMasqueradingAsCUDA.cpp, etc., but the required .in files are missing.
The repository does not contain these .in files in the checked-out version v2.4.0.
These files appear to be essential for the ROCm build process, and their absence is preventing successful configuration.
It’s unclear whether these files should have been part of the v2.4.0 release or if they are generated through another mechanism.

**Request: Please provide guidance on resolving the missing file issues during the build process. Specifically:**
- Are the files HIPConfig.h.in and hip_cmake_macros.h.in missing from the repository for the v2.4.0 tag?
- Should these files be generated through another process, or are they supposed to be present in the repository?
- If they are missing, could you add them or provide instructions on how to obtain them?
- Are there any additional steps or dependencies required for building PyTorch with ROCm on Ubuntu 24 with an AMD Radeon RX 6900 XT GPU?
- Alternatively, should I be using a different branch or tag for better ROCm support?

Any assistance or clarification on this matter would be greatly appreciated. Thank you!

### Versions

**System Info:**
- **PyTorch Version:** v2.4.0
- **ROCm Version:** 6.1
- **OS:** Ubuntu 24
- **Compiler:** GCC 13.2.0
- **CMake Version:** 3.28.3
- **GPU:** AMD Radeon RX 6900 XT

Please note I cannot run collect_env.py I assume perhaps due to non avx cpu's we are running, hence the need for a custom build. 

```
export USE_AVX=0
export USE_AVX2=0
export USE_AVX512=0
export CFLAGS="-march=core2"
export CXXFLAGS="-march=core2"
export USE_CUDA=0
export USE_ROCM=1
export USE_NCCL=0
export USE_MKLDNN=0
export BUILD_TEST=0
export PATH=/opt/rocm/bin:$PATH
export HSA_PATH=/opt/rocm/hsa
export ROCM_PATH=/opt/rocm
```

cc @malfet @seemethere @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by hongxiayang** [comment]
Can you try to follow below steps for building from source for better support?

(1) get your gfx target:

Can you run 
```rocminfo|grep gfx```

This will be used in step 3

(2) get the base image
```
alias drun="sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --group-add=video --ipc=host --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --shm-size 8G "

drun rocm/pytorch:latest-base
```

(3) Inside the container, clone the repo, and then build from source 

```
git clone --recursive  https://github.com/pytorch/pytorch.git
cd pytorch
python tools/amd_build/build_amd.py
PYTORCH_ROCM_ARCH=$YOUR_GFX_TARGET_FROM_STEP1 python setup.py develop
```

**Comment by birchcode** [comment]
A few issues running setup.py @hongxiayang

I put the output and error logs on pastebin as I can't upload here for some reason:

CMakeError.log -> https://pastebin.com/8umdeeCq
CMakeOutput.log -> https://pastebin.com/4Gmucvwz

**Comment by birchcode** [comment]
Is there anything else I can do to help or any suggestions I should follow to be able to build this?

**Comment by naromero77amd** [comment]
Can you please post the output of `rocminfo` ? 

We need to clarify the CPU model. 
Intel Core2 would have been discontinued 12 years ago: https://en.wikipedia.org/wiki/Intel_Core_2

Can you give `-march=native` a try? It would be very surprising to find an x86_64 processor that does not support some level of AVX.

**Comment by naromero77amd** [comment]
There is another obstacle here.

AMD does not officially support Radeon RX 6900 XT GPU on this version of ROCm 6.1: https://rocm.docs.amd.com/projects/radeon/en/latest/

**Comment by naromero77amd** [comment]
Some additional clarification regarding support of the Radeon RX 6900 XT GPU. While this GPU card is not officially supported by AMD, the architecture (RDNA2) and the target (gfx1030) is supported by ROCm stack:
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html

It is worth a try, but there will likely be caveats w.r.t to functionality and performance.

**Comment by naromero77amd** [comment]
The original issue was about the missing HIPConfig.h.in and hip_cmake_macros.h.in. The missing step was `python tools/amd_build/build_amd.py`. If x86_64 support without AVX instructions is needed, a separate non ROCM-specific github issue should be filed against upstream PyTorch.

**Comment by birchcode** [comment]
> Can you please post the output of `rocminfo` ?

```➜  ~ rocminfo
ROCk module version 6.7.0 is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.13
Runtime Ext Version:     1.4
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3591                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            24                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    131891720(0x7dc8208) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    131891720(0x7dc8208) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    131891720(0x7dc8208) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1030                            
  Uuid:                    GPU-8411423036819531               
  Marketing Name:          AMD Radeon RX 6900 XT              
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      4096(0x1000) KB                    
    L3:                      131072(0x20000) KB                 
  Chip ID:                 29631(0x73bf)                      
  ASIC Revision:           1(0x1)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2660                               
  BDFID:                   1792                               
  Internal Node ID:        1                                  
  Compute Unit:            80                                 
  SIMDs per CU:            2                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 118                                
  SDMA engine uCode::      83                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1030         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***       ```


> We need to clarify the CPU model. Intel Core2 would have been discontinued 12 years ago: https://en.wikipedia.org/wiki/Intel_Core_2

We are running 2 x Intel X5690's @ 3.47GHz which is 12 cores / 24 threads. Surprisingly it's still a competitive machine. Unfortunately we've only got up to SSE4.2 on these westmere chips. Would be incredible if we could utilise this as I'm sure it would still be sufficient since most of the load is on the GPU?  Perhaps with Intel's https://github.com/oneapi-src/oneMKL ? This is definitely way outside my lane. I assume it would use SSE4.2 as a fallback if AVX was not available but idk.

> Can you give `-march=native` a try? It would be very surprising to find an x86_64 processor that does not support some level of AVX.

Sure. Similar issues to before: https://pastebin.com/nzbFB9Ks

Thanks for the help. Anything else we could try?

**Comment by birchcode** [comment]
> The original issue was about the missing HIPConfig.h.in and hip_cmake_macros.h.in. The missing step was `python tools/amd_build/build_amd.py`. If x86_64 support without AVX instructions is needed, a separate non ROCM-specific github issue should be filed against upstream PyTorch.

Yes, I should note we ran 

> python tools/amd_build/build_amd.py

It seems executing this and then running with -march=native was, despite a lot of warnings, was able to build

**Comment by birchcode** [comment]
Here is the complete cmake output that was able to complete:

https://pastebin.com/pG7uyans

**Comment by naromero77amd** [comment]
Correct, Westmere only supports up to SSE4.2 extensions. No AVX support unfortunately.

The official MKL download page is here:
https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl.html

You might have to download an older version of MKL for Westmere support.

I would recommend trying to build without setting all those extra environment variables. Just do:
```
PYTORCH_ROCM_ARCH=gfx1030 python setup.py develop
```

If you are still running into issues because of the AVX extensions, I strongly recommend that you file a non-ROCM issue against upstream PyTorch requesting that non-AVX x86_64 CPUs be supported.

**Comment by birchcode** [comment]
Unfortunately still issues building without all the extra variables.

I'm wondering if i could get away with using the last rocm version that supported x86 archictecture like rocm 3.7. Might you know what pytorch version I could use for this?

**Comment by naromero77amd** [comment]
> Unfortunately still issues building without all the extra variables.
> 
Thanks for trying.

> I believe AMD removed x86 support from rocm 3.8 onwards. We tried to install 3.7 to no avail.
Not sure what this statement means "AMD removed x86 support from rocm 3.8 onwards."

We are closing this issue as we are not in a position to provide support for older Intel processor. Again, I recommend you file a separate upstream issue regarding pre-Skylake (e.g. Westmere processors) in the PyTorch installation.
