### ISSUE TITLE
Meet “No module named'tools. setup_helpers‘“ when installing caffe2

### ISSUE THREAD

**Issue by ChrisHuang96** [pytorch/pytorch#134640]
### 🐛 Describe the bug

I pulled the branch  v 2.4.0 and compiled on ARM64 platform. Similar problem in [#707](https://github.com/pytorch/pytorch/issues/707) happened. 

Have USED `export FULL_CAFFE2=1` firstly and build wheel from sorce. Torch install and  work well but when I use `pip install caffe2`，I get

```shell
Collecting caffe2
  Using cached caffe2-0.5.0a0.dev100.tar.gz (10.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-i_faspwa/caffe2_6bf5d76bcddc4318b88e7aef5c343901/setup.py", line 108, in <module>
          from tools.setup_helpers.env import check_env_flag, check_negative_env_flag
      ModuleNotFoundError: No module named 'tools.setup_helpers'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
Waiting for any suggestion :) .

### Versions

Environment Info:
- OS: Ubuntu 22.04
- Python: 3.10.14
- CUDA: 12.2
- gcc: 11.4.0
- glibc: 2.35
- arch: aarch64
- numpy: 1.26.4
- torch: 2.4.0（build from source）
- torchvision: 2.4.0（build from source）
- torchaudio: 0.19.0（build from source）

cc @malfet @snadampal @milpuz01

**Comment by malfet** [comment]
`caffe2` has been deprecated for the last 3+ years, see https://caffe2.ai, we stopped building PyTorch with caffe2 integration in last 1.5 years (i.e. about 8 releases ago) and I think about 6 month ago we started removing old caffe2 codebase, so I don't expect 2.4 source tree could be used to build working caffe2 library , see https://github.com/pytorch/pytorch/commit/f95dbc12761cb4466099b0e9a3667057ca39272b for example.
