### ISSUE TITLE
Deduce Tangents Stride For Channels Last Tensor

### ISSUE THREAD

**Issue by alpha0422** [pytorch/pytorch#134644]
### 🚀 The feature, motivation and pitch

We are working on the performance of Diffusion models, and find that one of the `torch.compile` performance issue is that AOTAutograd forces tangents to be contiguous. This introduces a lot of performance overhead for CNN models if there's graph break around channels last tensors, resulting in quite some `direct_copy_kernel` during back-propagation.

### Alternatives

As AOT has to guess the tangents stride, I'd propose to guess the stride using the forward-propagation output instead of forcing contiguous. Because most of operators work on channels last expect `grad_output` as channels last too. Thus guessing the stride using output tensor of forward-propagation can avoid those `direct_copy_kernel` introduced during back-propation.

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @zou3519 @bdhirsh

**Comment by jansel** [comment]
I agree that this behavior is not ideal, there should be a better way to decide layouts for tangents.

cc @Chillee

**Comment by Chillee** [comment]
I think we should do this yeah. I think it wouldn't be *that* hard, although needs to be done within AOTAutograd.

cc: @bdhirsh as well

**Comment by bdhirsh** [comment]
At first I was going to say this might actually be partially fixed as part of https://github.com/pytorch/pytorch/issues/91469 (which I'm going to start on pretty soon but will take a while). The idea is that we will generate pre-dispatch graph of the backward at compile, time, and "re-trace" it into a normal, "post-dispatch ATen graph" at runtime of the backward, once we have accurate runtime tangents to trace with.

But actually I don't think this is true. if there are any backward formulas that specialize on contiguity (including custom ops with a custom backward formula), we will be forced to burn it into the graph, which basically requires us to fix up the strides in the backward if we guessed them incorrectly.

So I think probably the easiest fix would be a one-off change in AOTDispatcher, where:

Today: we always force tangents to be channels-first contiguous (both at trace time and runtime), here: https://github.com/pytorch/pytorch/blob/main/torch/_functorch/_aot_autograd/runtime_wrappers.py#L1441

Better: we can instead detect at compile time if any of our forward-outputs are channels-last contiguous, and stash that info in the `OutputInfo` of each forward output. Then at runtime, we can use that to decide if we should coerce our tangent to be channels-last contiguous instead (which would be a no-op if our tangent actually were channels-last).

@IvanKobzarev interesting in a taking a look?
