### ISSUE TITLE
[Compiled_autograd] Input stack for backward graph having unknown symint inputs when compiled autograd used with dynamic shape

### ISSUE THREAD

**Issue by joyalbin** [pytorch/pytorch#134676]
### 🐛 Describe the bug

This issue able to see with below example code:

```
def test_op_compiled_autograd():
    from torch._dynamo import compiled_autograd
    input_shapes = [
        [(3, 6, 4), (3, 24), (2, 1)],
        [(3, 8, 4), (3, 32), (2, 2)],
        [(3, 10, 4), (3, 40), (2, 3)],
    ]

    def raw_function(t0, t1, t2):
        t = t0.shape
        t0 = torch.relu(t0)
        shape = (t[0], int(t[1] * t[2]))
        reshape_t = t0.reshape(shape)
        o1 = torch.add(reshape_t, t1)
        o2 = torch.add(t2, t2)
        return o1, o2

    compiled_fn = torch.compile(raw_function, backend="hpu_backend", dynamic=True)

    with compiled_autograd.enable(compiled_fn):
        for s in input_shapes:
            t0 = torch.randn(s[0], requires_grad=True).to("hpu")
            t1 = torch.randn(s[1], requires_grad=True).to("hpu")
            t2 = torch.randn(s[2], requires_grad=True).to("hpu")
            o1, o2 = compiled_fn(t0, t1, t2)
            grad = torch.ones_like(o2)
            o2.backward(grad)
			
```
Backward FX graph module:
```
class fused_0(torch.nn.Module):
    def forward(self, primals_6: "Sym(s4)", relu: "f32[s0, s1, s2]", tangents_2: "f32[s4, 1]", tangents_1: "f32[s0, s1*s2]", primals_1: "Sym(s0)", primals_2: "Sym(s1)", primals_3: "Sym(s2)"):
        alias: "f32[s0, s1, s2]" = torch.ops.aten.alias.default(relu);  relu = None
        add_2: "f32[s4, 1]" = torch.ops.aten.add.Tensor(tangents_2, tangents_2);  tangents_2 = None
        view_1: "f32[s0, s1, s2]" = torch.ops.aten.view.default(tangents_1, [primals_1, primals_2, primals_3]);  tangents_1 = primals_1 = primals_2 = primals_3 = None
        alias_1: "f32[s0, s1, s2]" = torch.ops.aten.alias.default(alias);  alias = None
        alias_2: "f32[s0, s1, s2]" = torch.ops.aten.alias.default(alias_1);  alias_1 = None
        alias_3: "f32[s0, s1, s2]" = torch.ops.aten.alias.default(alias_2);  alias_2 = None
        threshold_backward: "f32[s0, s1, s2]" = torch.ops.aten.threshold_backward.default(view_1, alias_3, 0);  view_1 = alias_3 = None
        return (add_2, threshold_backward)
```

Backward graph input arguments:
`input_stack: , (s8, FakeTensor(..., device='hpu:0', size=(s1, s2, s3)), FakeTensor(..., device='hpu:0', size=(2, 1)), FakeTensor(..., device='hpu:0', size=(3, 24)), s5, s6, s7)`

Here , in the graph, 1st input is primals_6: "Sym(s4)", but the input stack is not an int. Its a new symbol created with name s8. Same happend of 5th, 6th and 7th input arguments.
Please help to fix the issue:

The above test case is with "hpu" tensor, the same scenario could not verify on cpu as it was giving another error "TypeError: test_op_compiled_autograd.<locals>.raw_function() missing 2 required positional arguments: 't1' and 't2'"

### Versions

Collecting environment information...
PyTorch version: 2.4.0a0+git91246ca
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.5 (ssh://gerrit.habana-labs.com:29418/tpc_llvm10 c55f3b366b16b7448a4ffbd095e6bbce39b10fab)
CMake version: version 3.29.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-117-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

cc @ezyang @chauhang @penguinwu @xmfan

**Comment by jansel** [comment]
@xmfan is this something you can look at?

**Comment by xmfan** [comment]
Hey, thanks for trying out the feature. The snippet is specifying the torch.compile API incorrectly for compiled autograd.

```python
compiled_fn = torch.compile(raw_function, backend="hpu_backend", dynamic=True)   # compiled_fn is the compiled forward
# we should instead pass in the torch.compile function we want to compile autograd with
with compiled_autograd.enable(torch.compile(backend="hpu_backend", dynamic=True):  ```

**Comment by jansel** [comment]
Feel free to reopen if that didn't answer your question.  You had an incorrect arg to `compiled_autograd.enable()`.
