### ISSUE TITLE
autograd branch: Memory leak

### ISSUE THREAD

**Issue by ankitkv** [pytorch/pytorch#1346]
The following code (based on test suit code) leaks memory in the autograd branch:
```
from __future__ import print_function

import torch
from torch.autograd import Variable
import torch.nn as nn


i = 0
while True:
    if i % 1000 == 0:
        print(i)
    i += 1
    x = Variable(torch.randn(2, 2).cuda(), requires_grad=True)
    y = Variable(torch.randn(2, 2).cuda(), requires_grad=True)

    z = x ** 2 + y * x + y ** 2
    z.backward(Variable(torch.ones(2, 2).cuda(), requires_grad=True), retain_variables=True)

    x_grad = 2 * x.data + y.data
    y_grad = x.data + 2 * y.data

    grad_sum = 2 * x.grad + y.grad
    grad_sum = grad_sum[:, :-1]
    grad_sum.backward(torch.ones(2, 1).cuda())  # leaks memory
```

**Comment by apaszke** [comment]
It's not a leak, that's only caused because the `.grad` is never detached and keeps accumulating the graphs of all iterations. Adding
```python
x.grad.detach_()
y.grad.detach_()
```
(or calling any `zero_grad()` function) frees the history and the memory usage stays constant.

**Comment by ankitkv** [comment]
But everything is defined inside the loop body, and should be destroyed after each iteration. Also, taking out the specific `grad_sum = grad_sum[:, :-1]` line doesn't result in increasing memory anymore.

**Comment by chenzhekl** [comment]
Python doesn't have a variable scope for `while`. I agree it is not a bug.

**Comment by apaszke** [comment]
It doesn't, but the references are overwritten so they should be freed anyway. I realized it's because of a reference cycle in autograd's C data structures. It's already fixed and I'll push it today

**Comment by chenzhekl** [comment]
Oh.. `x` and `y` reference different new `Variable`s in every loop. Sorry I overlooked it.

**Comment by jadore801120** [comment]
Hi, I am also facing the GPU memory problem. 
The following is my code, I tried to build a seq2seq model.
I put data into GPU only when I extract each batch.

```
for i in range(epoch_num):

    print('Epoch', i)

    total_loss = 0

    for batch_i, train_batch in enumerate(training_data):

        print("Batch#:", batch_i)

        data_tensor, data_lens = train_batch

        src_var = Variable(data_tensor).cuda()
        tgt_var = Variable(data_tensor).cuda()

        src = (src_var, data_lens)
        output_logit = nmt_model(src, tgt_var)

        cre_loss = criterion(output_logit.view(-1, vocab_size), tgt_var.view(-1))

        loss = cre_loss 
        loss.backward()

        nn.utils.clip_grad_norm(nmt_model.parameters(), 0.25)

        optimizer.step()
        optimizer.zero_grad()                                            
```

However, I get the `out of memory` error every time.

```
Epoch 0
Batch#: 0
Batch#: 1
...
Batch#: 17
THCudaCheck FAIL file=/py/conda-bld/pytorch_1490903321756/work/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    loss.backward()
  File "/home/yhhuang/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 146, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
  File "/home/yhhuang/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/thnn/auto.py", line 171, in backward
    grad_input = input.new().resize_as_(input)
RuntimeError: cuda runtime error (2) : out of memory at /py/conda-bld/pytorch_1490903321756/work/torch/lib/THC/generic/THCStorage.cu:66
```

I think my model is not that big, because I tested it with a much smaller trial data.
The GPU memory usage is about 1590MiB, according to the `nvidia-smi` command.

But with a huge real data, the memory will keep growing, and finally more than 6000 MiB and get the error above.

Seems the memory usage is growing as more batch data fed in.

Did I miss any house cleaning routine in this `for` loop?
Is there any suggestion about a more efficient GPU memory usage?

Any help will be appreciated! Please help me.

Yu-Hsiang

**Comment by Kaleidophon** [comment]
I feel like I am currently stuck on a very similar problem. Could someone help me understand why creating a new Variable for x and y in every loop might be harmful? Thanks!
