### ISSUE TITLE
[inductor][cpu]inductor_max_autotune xcit_large_24_p8_224 multiple thread AMP static shape default wrapper performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#134686]
### 🐛 Describe the bug

<p>AMP static shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>xcit_large_24_p8_224</td>
      <td>multiple</td>
      <td>16</td>
      <td>1.844225</td>
      <td>0.347939503</td>
      <td>0.6416787299201749</td>
      <td>70.358923</td>
      <td>16.0</td>
      <td>2.107447</td>
      <td>0.309641143</td>
      <td>0.652552297891921</td>
      <td>59.310145</td>
      <td>0.88</td>
      <td>1.02</td>
      <td>0.89</td>
      <td>0.84</td>
    </tr>
  </tbody>

</table>

the bad commit c22f51ce7c77ef23d9add8fc7c525145efd52230
```
running benchmark: 100%|██████████████████████████████████████████████████| 50/50 [00:40<00:00,  1.24it/s]
1.592x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,xcit_large_24_p8_224,16,1.591776,311.873558,105.495911,0.987995,1819.712307,1841.824154,1108,1,0,0,0,0,1
```

</table>

the last good commit 8f7cf796eaafc8e1b77c2d7815291f2721ccb377
```
running benchmark: 100%|██████████████████████████████████████████████████| 50/50 [00:39<00:00,  1.25it/s]
1.670x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,xcit_large_24_p8_224,16,1.669862,299.543120,65.827989,0.988743,1819.984691,1840.705536,1108,1,0,0,0,0,1
```

</table>

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>23512dbe</td>
      <td>main</td>
      <td>23512dbe</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>92151c814ba715fe7d1f5648b0ae6950dceee6b7</td>
      <td>main</td>
      <td>1d1d074072ecb0aa6ca95e3f43221d2275e16d74</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.4.0a0+b3f6f51</td>
      <td>main</td>
      <td>2.4.0a0+69b2a0a</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>fea73cb</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob//weizhuoz/enable_max_autotune_for_guilty/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference performance timm_models xcit_large_24_p8_224 amp first static default 0 inductor_max_autotune
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/c22f51ce7c77ef23d9add8fc7c525145efd52230
[timm_models-xcit_large_24_p8_224-inference-amp-static-default-multiple-performance-drop_guilty_commit.log](https://github.com/user-attachments/files/16786042/timm_models-xcit_large_24_p8_224-inference-amp-static-default-multiple-performance-drop_guilty_commit.log)
cc @ezyang @chauhang @penguinwu @WeizhuoZhang-intel @chuanqi129 @chunyuan-w

**Comment by chunyuan-w** [comment]
Hi @jgong5 here's a max-autotune regression issue and the guilty commit points to this PR: https://github.com/pytorch/pytorch/pull/132729
