### ISSUE TITLE
Question about AMD Support

### ISSUE THREAD

**Issue by Bebra777228** [pytorch/pytorch#134763]
Unfortunately, I don't fully understand how everything is set up and works, but I have a question:
**Will ROCm or any other device for supporting AMD GPUs be added to the main branch?**

Currently, to support AMD GPUs, I have to create different installation files and scripts need to be created to ensure everything works smoothly. It would be nice if everything were integrated into one place, **similar to how MPS is handled for macOS**, so that there is no need to create multiple identical files for installing different versions of torch.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by malfet** [comment]
Not sure I understand the ask here? Is this about building from source? Or binary wheels requiring a lot of external components to be usable?

**Comment by Bebra777228** [comment]
I meant building from source code, but this doesn't necessarily have to be related to Linux. I'm interested in whether support for ROCm or other devices for AMD GPUs will be integrated into the main branch of the project so that there is no need to create different installation files and scripts for each platform. This would significantly simplify the installation and usage process.

I also have a question regarding Windows: can AMD GPUs be used without issues on Windows with Torch without installing separate libraries? If yes, what steps need to be taken for this (at least roughly)? Currently, I have to use DML (DirectML) for more or less normal operation with AMD GPUs.

**Comment by jithunnair-amd** [comment]
@Bebra777228 To understand your pain point better, can you please elaborate on what kind of items come under "Currently, to support AMD GPUs, I have to create different installation files and scripts need to be created to ensure everything works smoothly"?

**Comment by Bebra777228** [comment]
Currently, to support AMD GPUs, I have to create different installation files and scripts:

1. **Three Files for Dependencies**:
   - For `torch`.
   - For `torch` with `ROCm`.
   - For `torch` with `torch-directml`.

2. **Three Config Files**:
   - For setting up the environment for CUDA.
   - For setting up the environment for ROCm.
   - For setting up the environment for CUDA and DirectML (fortunately, there are no conflicts).

3. **Three .bat Files**:
   - For the automatic installation and launching of the interface for CUDA.
   - For the automatic installation and launching of the interface for ROCm.
   - For the automatic installation and launching of the interface for DirectML.

Integrating support for AMD GPUs into the main branch would greatly simplify this process.

Again, I'm not very familiar with this topic, so if this is not possible or very difficult to implement, that's okay. The question is just out of curiosity. I'm only just starting to get into the field of programming and am still experimenting.

**Comment by hongxiayang** [comment]
We may have to close this issue. It needs different configs or setups for your use case as you are using different type of GPUs (Nvidia and AMD), and you need build separately for them and then deploy them.
