### ISSUE TITLE
Flexattention: creating mask[1,1,96000,96000] causes OOM error

### ISSUE THREAD

**Issue by foreverpiano** [pytorch/pytorch#134756]
### 🐛 Describe the bug

in the blog https://pytorch.org/blog/flexattention/, it says `For example, for a sequence length of 1 million, the BlockMask would only use 60MB of additional memory`.

however, when I try to use create_block_mask(mask_mod, 1, 1, S, S, device=query.device) S =96000, and it gives OOM.

### Versions

flexattention

cc @ezyang @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh

**Comment by janeyx99** [comment]
cc @drisspg

**Comment by Chillee** [comment]
@foreverpiano The OOM is coming from the *instantiation* of the mask. There's a couple of things you can do (see here: https://pytorch.org/blog/flexattention/#q-how-can-we-compute-blockmask-quicker) - the simplest is to pass `_compile=True`.

**Comment by foreverpiano** [comment]
Thanks for your help. I don't really understand by passing `_compile=True`. Does we materialize whole mask in this way or create mask / BLOCK_SIZE_Q / BLOCK_SIZE_KV? There is a function in the code but it creates full mask before creating block-mask. What I want is to avoid creating full mask and I wonder if `_compile=True` can ensure this. Is there any core code I can refer to? @Chillee 
```
def _create_block_mask_inner(
    mask_mod: Callable,
    B: int,
    H: int,
    Q_LEN: int,
    KV_LEN: int,
    device: str,
    KV_BLOCK_SIZE: int,
    Q_BLOCK_SIZE: int,
):
    r"""Work around for being unable to instantiate __torch_function__ mode under compile.
    `create_block_mask` will compile this inner function and wrap the call to this
    with the __torch_function__ mode.
    """
    mask_tensor = create_mask(mask_mod, B, H, Q_LEN, KV_LEN, device, _compile=True)
    full_block_mask, partial_block_mask = _convert_mask_to_block_mask(
        mask_tensor,
        KV_BLOCK_SIZE=KV_BLOCK_SIZE,
        Q_BLOCK_SIZE=Q_BLOCK_SIZE,
        separate_full_blocks=True,
    )
    return _create_sparse_block_from_block_mask(
        (full_block_mask, partial_block_mask), mask_mod
    )
```

**Comment by foreverpiano** [comment]
One more question: does flexattention call `flash_attention` or xformer mem_efficient attention in its backend?

**Comment by Chillee** [comment]
@foreverpiano Yes, with `_compile=True` we avoid materializing the mask, since it usually gets fused into one kernel by the compiler.

> does flexattention call flash_attention or xformer mem_efficient attention in its backend?

We have our own kernel written in Triton, but it follows the flashattention algorithm.

**Comment by foreverpiano** [comment]
@Chillee I find your code in the backend for flexattention. 
> since it usually gets fused into one kernel by the compiler.
I don't understand what's the meaning of usually. Is it a determimned process of compiling? Is there any code about the fused creating mask with `compile=True`?

**Comment by drisspg** [comment]
Going to close this as completed, it is not necessarily deterministic because mask_mod functions can contain arbitrary code. We also no longer need the _compile=true flag and the function can be compiled like normal.

**Comment by foreverpiano** [comment]
@drisspg Hi drisspg, does it mean we do not need _compile =True now and it can automatic compile? which pr did it fixed?thanks

**Comment by Chillee** [comment]
@foreverpiano You can just do `torch.compile(create_block_mask)`
