### ISSUE TITLE
torch.export didn't fully preserve "custom" metadata during re-export and run_decomposition

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#134778]
### 🐛 Describe the bug

see https://github.com/pytorch/pytorch/pull/134776

### Versions

main branch

cc @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by ydwu4** [comment]
Probably a different subject: can this pr be helpful https://github.com/pytorch/pytorch/pull/132860? It basically preserves the metadata with a hop, which makes the metadata more explicit and less likely to be lost.

**Comment by zhxchen17** [comment]
@jerryzh168 

@tugsbayasgalan mentioned that this PR https://github.com/pytorch/pytorch/pull/132901/files might already fix your issue. Do you mind rebasing and see if it works? thanks!

**Comment by jerryzh168** [comment]
@zhxchen17 yeah it looks like the run decomposition test passed, but the re-export error is still there

**Comment by jerryzh168** [comment]
> Probably a different subject: can this pr be helpful #132860? It basically preserves the metadata with a hop, which makes the metadata more explicit and less likely to be lost.

the metadata we are talking about here is per node so probably not practical to make them higher order op?

**Comment by zhxchen17** [comment]
> @zhxchen17 yeah it looks like the run decomposition test passed, but the re-export error is still there

@jerryzh168 did you try to use export_for_training instead in the re-export test? That API might work.

**Comment by dulinriley** [comment]
I added a new PR with a unittest on a simple model that exhibits this behavior: https://github.com/pytorch/pytorch/pull/134864.
It is incorrectly copying the numeric_debug_handle from a conv2d to its bias and weight placeholders

**Comment by dulinriley** [comment]
Swapping the export function to export_for_training does not change the debug handles, it still has the bug in that PR

**Comment by yiming0416** [comment]
@jerryzh168 just want to make sure we are on the same page. 

`test_run_decompositions_preserve_handle` passes on my end. 

I was able to reproduce the error by running `test_re_export_preserve_handle`. So the goal is to fix this test right?

**Comment by yiming0416** [comment]
@zhxchen17 @jerryzh168 @dulinriley using non-strict `export` or `export_for_training` will pass the test. I am investigating why...

**Comment by yiming0416** [comment]
Reopen the issue. The previous fix is reverted in https://github.com/pytorch/pytorch/pull/135634
