### ISSUE TITLE
Seemingly Random success rate of DistributedDataParallel (1.0.0.dev20181029 - 1.0.0.dev20181105) 

### ISSUE THREAD

**Issue by SinghJasdeep** [pytorch/pytorch#13471]
## 🐛 Bug
Dear Pytorch team, 

I am trying to run a multi-gpu job using torch.nn.parallel.distributed. I would like to use pytorch 1.0+ because of: (https://github.com/pytorch/pytorch/pull/13056, https://github.com/pytorch/pytorch/issues/6419) and well because its awesome :) 

I am running the following commands in separate tmux sessions on the same cloud machine with 8 GPUs: 

```
1. nvidia-docker ... "CUDA ... DEVICES=0 python train.py  ... --devices 0 --rank_ 0 --world_size 8"
2. nvidia-docker ... "CUDA ... DEVICES=1 python train.py  ... --devices 0 --rank_ 1 --world_size 8"
.
.
.
8. nvidia-docker ... "CUDA ... DEVICES=7 python train.py  ... --devices 0 --rank_ 7 --world_size 8"
```

The programs execute as expected up until:
```
line xxx:   torch.distributed.init_process_group(...)
```

At which point they (**usually**) hang. I have checked to make sure that all of the programs are getting the same file for torch.distributed.init_process_group(init_method= ...) 

I have yet to get this working with a world_size of 8, but I can get this working with smaller world_size's (2-7). To do so I just run the exact same command a number of times until the programs just (seemingly) randomly get past torch.distributed.init_process_group(...). At first glance the average number failed tries before a success seems to increase with the world_size. 

This code was working consistently on 0.4.1 however the gloo timeout needed to be larger for my application. 

Do not know what is causing this. Would really appreciate you hep. 

Thank you!

## To Reproduce

1) Run the following commands in separate tmux sessions on the same cloud machine with 8 GPUs: 

```
1. nvidia-docker ... "CUDA ... DEVICES=0 python train.py  ... --devices 0 --rank_ 0 --world_size 8"
2. nvidia-docker ... "CUDA ... DEVICES=1 python train.py  ... --devices 0 --rank_ 1 --world_size 8"
.
.
.
8. nvidia-docker ... "CUDA ... DEVICES=7 python train.py  ... --devices 0 --rank_ 7 --world_size 8"
```
2) If the programs get hung on the line with:
```
torch.distributed.init_process_group(...)
```
You have reproduced the issue. 

## Expected behavior

I expected the programs to continue training more than ~ 10% of the time. 
Also would be nice to be able to use a world_size of 8

## Environment

PyTorch version: 1.0.0.dev20181029
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 396.44
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.15.2)
[pip] torch (1.0.0.dev20181029)
[conda] pytorch-nightly           1.0.0.dev20181029 py3.6_cuda9.0.176_cudnn7.1.2_0    pytorch

## Additional context

Please feel free to ask for more :)

**Comment by zou3519** [comment]
cc @teng-li maybe?

**Comment by SinghJasdeep** [comment]
This is still an issue in **1.0.0.dev20181105**-py3.6_cuda9.0.176_cudnn7.1.2_0 pytorch

This usually does not happen for 4 gpus and below. But usually always occurs for 7+ 

I have noticed that for 4 gpus if the processes do hang they will still recover after ~5 minutes. This leads me to believe perhaps there is some communication issue between the GPU's and coordinating more GPU's is simply more likely to get at least one of them out of sync, therefore, the much longer (possibly infinite) wait times for 8+ gpus.

**Comment by teng-li** [comment]
@SinghJasdeep Is this for mixed-precision fp16 training?

**Comment by SinghJasdeep** [comment]
@teng-li Nope, its fp32

**Comment by teng-li** [comment]
@SinghJasdeep  Can you share your training script such that I can try to repro?

**Comment by SinghJasdeep** [comment]
Hey @teng-li  Sorry been really busy. I am not allowed to share the code but I will write a stripped down version over the weekend and post it. I will also retry with the newest version, etc. 

Thank you for your help. Please give me another few days :)

**Comment by pietern** [comment]
@SinghJasdeep What backend are you using? Where is the file located? Can you specify the full command line you're using to reproduce? And can you sample a stack when they are hanging? You can do so by attaching gdb to one of the stuck processes and seeing where it is stuck specifically.

**Comment by SinghJasdeep** [comment]
@pietern Hey Sorry Pieter. Unfortunately I no longer have access to the exact set up that was used to reproduce this and am not working out of that code base anymore. 

1) I was using gloo backend. 

2) The file was stored in export/{DockerContainerName}/logs/{year}/{day}/{special_distributed_name_token}
{DockerContainerName}/ was a directory with the project code etc I mounted to the container. 
{special_distributed_name_token} is a runtime argument so I can have multiple runs on the same day. 

3) The exact command is this repeated X number of times on different tmux sessions, changing the cuda device each time: 
```
nvidia-docker run -it --rm -v `pwd`:/decaNLP/ -v /export/home/jasdeep/data/:/decaNLP/data/   -u $(id -u):$(id -g) decanlp bash -c " CUDA_VISIBLE_DEVICES=0     python   /decaNLP/train.py --train_tasks multi_trans --train_batch_tokens 4000 --val_every 5000000000 --val_batch_size 24   --save_every 1000   ...  --dropout_ratio 0.05 --warmup 500 --devices 0 --rank_ 0 --world_size_ 8 --distributed  --special_distributed_name_token 8 --no_tensorboard"
```
4) Also I'm sorry I can't check exactly where it was getting stuck since I am not on this project anymore. 


Thanks for all your help Pieter! However, given that I am unable to work on this anymore I will go ahead and close the issue. If I ever run into this, I can reopen it, or if you guys ever figure out what was happening please let me know.
