### ISSUE TITLE
x.sum(64) now raises a bitset error

### ISSUE THREAD

**Issue by fritzo** [pytorch/pytorch#13478]
## 🐛 Bug

`torch.sum(dim)` no longer works when dim >= 64.

## To Reproduce

```py
>>> torch.ones((2,) + (1,) * 62 + (2,)).sum(63).dim()
63
>>> torch.ones((2,) + (1,) * 63 + (2,)).sum(64).dim()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: bitset set argument out of range
```

## Expected behavior

An ugly workaround is to squeeze and reshape.
```py
def workaround_sum(x, dim):
    result_shape = x.shape[:dim] + x.shape[1+dim:]
    x = x.reshape((-1,) + x.shape[dim:])
    x = x.reshape(x.shape[0], x.shape[1], -1)
    x = x.sum(1)
    return x.reshape(result_shape)
```

## Environment

PyTorch version: 1.0.0a0+99ce499
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.3
GCC version: Could not collect
CMake version: version 3.12.0

Python version: 2.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.0                     <pip>

**Comment by fritzo** [comment]
@neerajprad this breaks Pyro's HMM example

**Comment by colesbury** [comment]
Why are you making a tensor with 64 dimensions? We were planning on limiting the maximum number of dimensions. (But if we go that path, we'll need a better error message)

**Comment by fritzo** [comment]
What's your plan on the tensor dim limit?

Pyro makes tensors with dimension `O(#statements)` in a probabilistic program, so if a probabilistic program for a time series has 1000 sample statements then Pyro will create a tensor of 1000 dimensions. It works great in PyTorch 0.4. If you plan to drop support for unbounded dim tensors, then @eb8680 and I will prioritize finding a workaround in Pyro.

**Comment by fritzo** [comment]
OK, closing since 1.0 release will be dropping support for tensors of dim>64.
