### ISSUE TITLE
Build Linux aarch64 wheels with CUDA enabled

### ISSUE THREAD

**Issue by saagarjha** [pytorch/pytorch#134790]
### 🚀 The feature, motivation and pitch

PyTorch is built with CUDA support for x86-64 but not for arm64. Since there are CUDA toolchains that run on this platform, it would be nice if the wheels could include support for this.

### Alternatives

Building from source, which is what I'm doing right now. This takes forever.

### Additional context

I'm looking at https://pypi.org/project/torch/2.4.0/#files and it's not there

cc @seemethere @malfet @osalpekar @atalman

**Comment by Aidyn-A** [comment]
@tinglvv has added the nightly aarch64 wheels with CUDA enabled. You can pip-install them as:
```
pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu124
```

**Comment by saagarjha** [comment]
Excellent, thank you so much!
