### ISSUE TITLE
[inductor][cpu]inductor_max_autotune float32 models accuracy crash in 2024-08-26 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#134998]
### 🐛 Describe the bug

<p>fp32 static shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>huggingface</td>
      <td>AlbertForMaskedLM</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>AlbertForMaskedLM, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>huggingface</td>
      <td>ElectraForCausalLM</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>ElectraForCausalLM, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>huggingface</td>
      <td>T5ForConditionalGeneration</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>T5ForConditionalGeneration, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>huggingface</td>
      <td>T5Small</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>T5Small, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>huggingface</td>
      <td>XGLMForCausalLM</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>XGLMForCausalLM, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>hf_Albert</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>hf_Albert, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>hf_Bert</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>hf_Bert, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>hf_DistilBert</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>hf_DistilBert, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>hf_T5</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>hf_T5, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>speech_transformer</td>
      <td>multiple</td>
      <td>X</td>
      <td>X</td>
      <td>speech_transformer, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>huggingface</td>
      <td>AlbertForMaskedLM</td>
      <td>single</td>
      <td>X</td>
      <td>√</td>
      <td>AlbertForMaskedLM, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>hf_Albert</td>
      <td>single</td>
      <td>X</td>
      <td>√</td>
      <td>hf_Albert, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>speech_transformer</td>
      <td>single</td>
      <td>X</td>
      <td>√</td>
      <td>speech_transformer, KeyError: '_frozen_param0'</td>
    </tr>
  </tbody>

</table>

<p>fp32 dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>huggingface</td>
      <td>AlbertForMaskedLM</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>AlbertForMaskedLM, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>huggingface</td>
      <td>ElectraForCausalLM</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>ElectraForCausalLM, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>speech_transformer</td>
      <td>multiple</td>
      <td>X</td>
      <td>X</td>
      <td>speech_transformer, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>huggingface</td>
      <td>AlbertForMaskedLM</td>
      <td>single</td>
      <td>X</td>
      <td>√</td>
      <td>AlbertForMaskedLM, KeyError: '_frozen_param0'</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>hf_Albert</td>
      <td>single</td>
      <td>X</td>
      <td>√</td>
      <td>hf_Albert, KeyError: '_frozen_param0'</td>
    </tr>
  </tbody>

</table>

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>23512dbe</td>
      <td>main</td>
      <td>23512dbe</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>2553278bae5993bd94bae4f04bf4586fb3f30d57</td>
      <td>main</td>
      <td>b4a1673a6741e183856cf3503f0574d3ac881ce0</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.4.0a0+b3f6f51</td>
      <td>main</td>
      <td>2.4.0a0+b3f6f51</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob//weizhuoz/enable_max_autotune_for_guilty/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh **thread** inference accuracy **suite** **name** float32 first static/dynamic default 0 inductor_max_autotune
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/c42ac54d9e817bf0a0366eb78e6c8beba4d5eff5
[torchbench-hf_T5-inference-float32-static-default-multiple-accuracy-crash_guilty_commit.log](https://github.com/user-attachments/files/16845453/torchbench-hf_T5-inference-float32-static-default-multiple-accuracy-crash_guilty_commit.log)
cc @ezyang @chauhang @penguinwu @WeizhuoZhang-intel @chuanqi129 @chunyuan-w
```[tasklist]
### Tasks
```

**Comment by malfet** [comment]
Just curious, what is "accuracy crash"?

**Comment by leslie-fang-intel** [comment]
> Just curious, what is "accuracy crash"?

I guess it crashes when running with accuracy mode.

**Comment by leslie-fang-intel** [comment]
In https://github.com/pytorch/pytorch/commit/c42ac54d9e817bf0a0366eb78e6c8beba4d5eff5, we have deleted the prepack weight after constant folding in FX Graph to save memory (especially useful for LLM inference with CPP Backend max-autotune mode). @chunyuan-w could you help take a look is there any special for these models?

**Comment by chunyuan-w** [comment]
The AMP static accuracy failure of `GoogleFnet` in HF is also caused by this PR.

**Comment by leslie-fang-intel** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/135100 and PR landed, @zxd1997066 please help to verify

**Comment by zxd1997066** [comment]
fp32 dynamic shape default wrapper issues fixed, waiting for fp32 static shape report.

**Comment by zxd1997066** [comment]
The issue is fixed on the latest main branch.
