### ISSUE TITLE
torch.linalg.solve() generates very wrong result (float32, CPU)

### ISSUE THREAD

**Issue by lddllddl** [pytorch/pytorch#134905]
### 🐛 Describe the bug

[A,B hardcoded as lists in linked gist](https://gist.github.com/lddllddl/6621ce796e09903e7794366d60449ea4)
```
import torch as t
import numpy as np

Xt = t.linalg.solve(t.Tensor(A),t.Tensor(B))
print('torch ',t.__version__,Xt.min(),Xt.max(),(t.Tensor(A) @ Xt - t.Tensor(B)).pow(2).sum())
Xt32 = t.linalg.solve(t.Tensor(A).to(t.float32),t.Tensor(B).to(t.float32))
print('torch 32',t.__version__,Xt32.min(),Xt32.max(),(t.Tensor(A).to(t.float32) @ Xt32 - t.Tensor(B).to(t.float32)).pow(2).sum())
Xt64 = t.linalg.solve(t.Tensor(A).to(t.float64),t.Tensor(B).to(t.float64))
print('torch 64',t.__version__,Xt64.min(),Xt64.max(),(t.Tensor(A).to(t.float64) @ Xt64 - t.Tensor(B).to(t.float64)).pow(2).sum())

Xn = np.linalg.solve(np.array(A),np.array(B))
print('numpy',np.__version__,Xn.min(),Xn.max(),((np.array(A) @ Xn - np.array(B))**2).sum())
Xn32 = np.linalg.solve(np.array(A,dtype=np.float32),np.array(B,dtype=np.float32))
print('numpy 32',np.__version__,Xn32.min(),Xn32.max(),((np.array(A,dtype=np.float32) @ Xn32 - np.array(B,dtype=np.float32))**2).sum())
Xn64 = np.linalg.solve(np.array(A,dtype=np.float64),np.array(B,dtype=np.float64))
print('numpy 64',np.__version__,Xn64.min(),Xn64.max(),((np.array(A,dtype=np.float64) @ Xn64 - np.array(B,dtype=np.float64))**2).sum())
```
prints

```
torch  2.0.1 tensor(-51507864.) tensor(89152944.) tensor(6.1853e+10)
torch 32 2.0.1 tensor(-51507864.) tensor(89152944.) tensor(6.1853e+10)
torch 64 2.0.1 tensor(-114.8141, dtype=torch.float64) tensor(4.7188, dtype=torch.float64) tensor(1.5626e-16, dtype=torch.float64)
numpy 1.26.1 -114.81414097643905 4.7187721908800935 2.0824782870486846e-16
numpy 32 1.26.1 -114.81414 4.7187724 3.8884506
numpy 64 1.26.1 -114.81414097643905 4.7187721908800935 2.0824782870486846e-16
```

Obviously the fp32 solution from pytorch is wildly wrong.

### Versions

Sorry I don't want to expose too much details of my runtime environment.
And the provided case should be easily reproducible on another machine.
But roughly the environment is Python 3.11.8, x86_64 Linux with Intel i9.
PyTorch 2.0.1 (I haven't found a similar bug report or issue to suggest this may have been fixed though)

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano

**Comment by lddllddl** [comment]
Also the torch fp64 solution has a similar precision of the numpy fp32 solution.

**Comment by lddllddl** [comment]
Also tried CUDA:

```
Xt32cu = t.linalg.solve(t.Tensor(A).to(t.float32).cuda(),t.Tensor(B).to(t.float32).cuda())
print('torch 32 cuda',t.__version__,Xt32cu.min(),Xt32cu.max(),(t.Tensor(A).to(t.float32).cuda() @ Xt32cu - t.Tensor(B).to(t.float32).cuda()).pow(2).sum())
Xt64cu = t.linalg.solve(t.Tensor(A).to(t.float64).cuda(),t.Tensor(B).to(t.float64).cuda())
print('torch 64 cuda',t.__version__,Xt64cu.min(),Xt64cu.max(),(t.Tensor(A).to(t.float64).cuda() @ Xt64cu - t.Tensor(B).to(t.float64).cuda()).pow(2).sum())
```

```
torch 32 cuda 2.0.1 tensor(-2.6919e+08, device='cuda:0') tensor(1.5214e+08, device='cuda:0') tensor(2.2435e+11, device='cuda:0')
torch 64 cuda 2.0.1 tensor(-114.8141, device='cuda:0', dtype=torch.float64) tensor(4.7188, device='cuda:0', dtype=torch.float64) tensor(8.2635e-17, device='cuda:0', dtype=torch.float64)
```

Seems to fail in a similar way to that on CPU.

**Comment by hustc12** [comment]
Confirmed to reproduce this issue from the latest source code. I built the PyTorch from the source code and the results are shown in the below:

torch  2.5.0a0+gitcbee9c1 tensor(-8094135.) tensor(14480713.) tensor(6.7718e+08)
torch 32 2.5.0a0+gitcbee9c1 tensor(-8094135.) tensor(14480713.) tensor(6.7718e+08)
torch 64 2.5.0a0+gitcbee9c1 tensor(-114.8141, dtype=torch.float64) tensor(4.7188, dtype=torch.float64) tensor(5.5413e-17, dtype=torch.float64)
numpy 2.0.0 -114.81414097646719 4.7187721908814435 2.1754394025006162e-16
numpy 32 2.0.0 -114.81414 4.7187724 5.3345637
numpy 64 2.0.0 -114.81414097646719 4.7187721908814435 2.1754394025006162e-16

**Comment by lddllddl** [comment]
Just out of curiosity how Tensorflow fares

```
>>> Xtf32 = tf.linalg.solve(tf.convert_to_tensor(A,dtype=tf.float32),tf.convert_to_tensor(B,dtype=tf.float32)[:,None])
>>> print('tensorflow 32',tf.__version__,tf.reduce_min(Xtf32),tf.reduce_max(Xtf32),
...     tf.reduce_sum((tf.convert_to_tensor(A,dtype=tf.float32) @ Xtf32 - tf.convert_to_tensor(B,dtype=tf.float32)[:,None])**2))
tensorflow 32 2.17.0 tf.Tensor(-7224.5776, shape=(), dtype=float32) tf.Tensor(12481.284, shape=(), dtype=float32) tf.Tensor(608.6341, shape=(), dtype=float32)
>>> Xtf64 = tf.linalg.solve(tf.convert_to_tensor(A,dtype=tf.float64),tf.convert_to_tensor(B,dtype=tf.float64)[:,None])
>>> print('tensorflow 64',tf.__version__,tf.reduce_min(Xtf64),tf.reduce_max(Xtf64),
...     tf.reduce_sum((tf.convert_to_tensor(A,dtype=tf.float64) @ Xtf64 - tf.convert_to_tensor(B,dtype=tf.float64)[:,None])**2))
tensorflow 64 2.17.0 tf.Tensor(-114.8141409765533, shape=(), dtype=float64) tf.Tensor(4.718772190885021, shape=(), dtype=float64) tf.Tensor(1.1391063518181607e-16, shape=(), dtype=float64)
```

Not exploding as much but still unusable result for 32-bit.

**Comment by lddllddl** [comment]
Cross references to TensorFlow and JAX (which gives a much more reasonable result but still wrong)

https://github.com/tensorflow/tensorflow/issues/74965

https://github.com/google/jax/issues/23367

**Comment by lezcano** [comment]
It's probably because the matrix is very badly condition. If that is the case, this is somewhat expected as per https://pytorch.org/docs/stable/notes/numerical_accuracy.html#extremal-values-in-linalg.

We do not implement these algorithms in PyTorch, we dispatch them to external libraries like the different implementations of BLAS and cuSolver. As such, it would be better suited to report this issue to these libraries.

**Comment by lddllddl** [comment]
Yes it is badly conditioned as the JAX maintainer initially pointed out, whereas numpy secretly converts to double precision.
However, is it indeed solved by BLAS in this case? It would be interesting if BLAS completely lost numerical stability while JAX was able to sort of maintain stability (even still wrong).
