### ISSUE TITLE
Numerical ODE solvers

### ISSUE THREAD

**Issue by stefanwebb** [pytorch/pytorch#13491]
## 🚀 Feature
It would be useful to have a library of numerical ODE solvers that are compatible with PyTorch.

## Motivation
Neural networks are increasingly being combined with ODEs. For example, when modelling ODEs that form part of a probabilistic model, or when defining a derivative with a neural network (neural ODEs).

You may want to get a speedup by using the GPU with PyTorch for this, and it's useful to be able to differentiate through these algorithms too.

## Pitch
I'm proposing to create a `torch.ode` module that contains half a dozen common ODE solvers. For instance, you could call `torch.ode.forward_euler(f, t0, tn, x0, n)` to calculate `n` points from `t0` to `tn` for the equation `dx/dt = f(t, x)`

**Comment by stefanwebb** [comment]
I was intending to contribute some general ODE solvers first, which are more widely applicable than to Neural ODEs. Would that be better suited for the `contrib` repo? It's not so much implementing a specific deep learning paper

However, I would like to understand the paper more fully and write an implementation of neural ODEs after that...

I think in general it would be good to have basic numerical algorithms in PyTorch so you can get the GPU speedup! And some like numerical differentiation would be useful for testing PyTorch components

**Comment by soumith** [comment]
if it's generalized ODE solvers, I put them similar to our `spectral` ops like FFT, they can go into pytorch core as long as we can iterate on the design / API.

If it's Neural ODEs / a particular paper, we should put them in `contrib`

**Comment by alicanb** [comment]
@stefanwebb have you seen this? https://github.com/rtqichen/torchdiffeq

**Comment by stefanwebb** [comment]
Yes, thanks! I'm going to ask the author if he would consider merging it into PyTorch...
