### ISSUE TITLE
lib/libtorch_cpu.so: undefined reference to `c10::cuda::CUDACachingAllocator::getDeviceStats(int)’

### ISSUE THREAD

**Issue by SwibonX** [pytorch/pytorch#134970]
## Issue description

In PyTorch 1.13, when I call `c10::cuda::CUDACachingAllocator::getDeviceStats(0)` in a .cpp file under aten/src/ATen, I encounter the error "lib/libtorch_cpu.so: undefined reference to `c10::cuda::CUDACachingAllocator::getDeviceStats(int)'". How can I configure my setup to call `c10::cuda`? 

## Code example

#include <c10/cuda/CUDACachingAllocator.h>
long current_memory() {
  STATS.track("current_memory");
  auto device_stat = c10::cuda::CUDACachingAllocator::getDeviceStats(0);
  return device_stat.allocated_bytes[0].current;
}

## System Info
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.30.2
Libc version: glibc-2.31

Python version: 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35)  [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-6.6.0-1-generic-x86_64-with-glibc2.10
Is CUDA available: N/A
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090

Nvidia driver version: 555.58.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

- PyTorch or Caffe2:Pytorch
- How you installed PyTorch (conda, pip, source):source
- Build command you used (if compiling from source):USE_CUDA=1 python setup.py install
- OS:Ubuntu 20.04.4 LTS (x86_64)
- PyTorch version:1.13
- Python version:3.8.19
- CUDA/cuDNN version:11.7.99
- GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090、GPU 1: NVIDIA GeForce RTX 4090
- GCC version (if compiling from source):(Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- CMake version:3.30.2
- Versions of any other relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.13.0a0+d321be6
[conda] magma-cuda117             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-include               2024.2.1           ha957f24_103    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] numpy                     1.22.4           py38h99721a1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] torch                     1.13.0a0+d321be6          pypi_0    pypi

cc @jbschlosser

**Comment by ruohan12345** [comment]
I met the same problem when building DTR with PyTorch1.13+CUDA11.8+CUDNN8.6，how did you solve this problem?
