### ISSUE TITLE
The following problems were encountered when compiling from the source code

### ISSUE THREAD

**Issue by BiophiliaSWDA** [pytorch/pytorch#134963]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

[3/23] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/utils/tensor_numpy.cpp.o
FAILED: caffe2/torch/CMakeFiles/torch_python.dir/csrc/utils/tensor_numpy.cpp.o 
/usr/bin/c++ -DAT_PER_OPERATOR_HEADERS -DBUILDING_TESTS -DBUILD_ONEDNN_GRAPH -DFMT_HEADER_ONLY=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DIDEEP_USE_MKL -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTHP_BUILD_MAIN_LIB -DUSE_C10D -DUSE_C10D_GLOO -DUSE_C10D_MPI -DUSE_C10D_NCCL -DUSE_CUDA -DUSE_CUDNN -DUSE_DISTRIBUTED -DUSE_EXPERIMENTAL_CUDNN_V8_API -DUSE_EXTERNAL_MZCRC -DUSE_ITT -DUSE_NCCL -DUSE_NUMPY -DUSE_RPC -DUSE_TENSORPIPE -DUSE_VALGRIND -D_FILE_OFFSET_BITS=64 -Dtorch_python_EXPORTS -I/pytorch/build/aten/src -I/pytorch/aten/src -I/pytorch/build -I/pytorch -I/pytorch/cmake/../third_party/benchmark/include -I/pytorch/third_party/onnx -I/pytorch/build/third_party/onnx -I/pytorch/third_party/foxi -I/pytorch/build/third_party/foxi -I/pytorch/torch/.. -I/pytorch/torch/../aten/src -I/pytorch/torch/../aten/src/TH -I/pytorch/build/caffe2/aten/src -I/pytorch/build/third_party -I/pytorch/torch/../third_party/valgrind-headers -I/pytorch/torch/../third_party/gloo -I/pytorch/torch/../third_party/onnx -I/pytorch/torch/../third_party/flatbuffers/include -I/pytorch/torch/../third_party/kineto/libkineto/include -I/pytorch/torch/csrc -I/pytorch/torch/csrc/api/include -I/pytorch/torch/lib -I/pytorch/torch/lib/libshm -I/pytorch/torch/csrc/api -I/pytorch/c10/.. -I/pytorch/c10/cuda/../.. -I/pytorch/torch/lib/libshm/../../../torch/lib -I/pytorch/third_party/fmt/include -I/pytorch/build/nccl/include -isystem /pytorch/build/third_party/gloo -isystem /pytorch/cmake/../third_party/gloo -isystem /pytorch/cmake/../third_party/tensorpipe/third_party/libuv/include -isystem /pytorch/cmake/../third_party/googletest/googlemock/include -isystem /pytorch/cmake/../third_party/googletest/googletest/include -isystem /pytorch/third_party/protobuf/src -isystem /root/miniconda3/envs/torchcov/include -isystem /pytorch/third_party/gemmlowp -isystem /pytorch/third_party/neon2sse -isystem /pytorch/third_party/XNNPACK/include -isystem /pytorch/third_party/ittapi/include -isystem /pytorch/cmake/../third_party/eigen -isystem /usr/local/cuda/include -isystem /pytorch/third_party/ideep/mkl-dnn/include/oneapi/dnnl -isystem /pytorch/third_party/ideep/include -isystem /root/miniconda3/envs/torchcov/include/python3.10 -isystem /root/miniconda3/envs/torchcov/lib/python3.10/site-packages/numpy/_core/include -isystem /pytorch/cmake/../third_party/pybind11/include -isystem /pytorch/cmake/../third_party/cudnn_frontend/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -D_GLIBCXX_USE_CXX11_ABI=1 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow -DHAVE_AVX512_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -std=gnu++17 -fPIC -DMKL_HAS_SBGEMM -DTORCH_USE_LIBUV -DCAFFE2_USE_GLOO -fno-strict-aliasing -Wno-strict-aliasing -pthread -MD -MT caffe2/torch/CMakeFiles/torch_python.dir/csrc/utils/tensor_numpy.cpp.o -MF caffe2/torch/CMakeFiles/torch_python.dir/csrc/utils/tensor_numpy.cpp.o.d -o caffe2/torch/CMakeFiles/torch_python.dir/csrc/utils/tensor_numpy.cpp.o -c /pytorch/torch/csrc/utils/tensor_numpy.cpp
In file included from /pytorch/torch/csrc/utils/tensor_numpy.cpp:5:
/pytorch/torch/csrc/utils/numpy_stub.h:19:10: fatal error: numpy/arrayobject.h: No such file or directory
   19 | #include <numpy/arrayobject.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by colesbury** [comment]
You are missing NumPy

**Comment by fzimmermann89** [comment]
It used to be possible to compile without numpy installed, see for example #56102
Is this a regression or a planned behavior  change?

**Comment by colesbury** [comment]
I don't know if we still support building without NumPy. Maybe @malfet knows?
