### ISSUE TITLE
[inductor][cpu] AlbertForMaskedLM, DebertaV2ForMaskedLM and timm_vision_transformer_large AMP AOT inductor crash issue

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#135027]
### 🐛 Describe the bug

<p>AMP static shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>huggingface</td>
      <td>AlbertForMaskedLM</td>
      <td>multiple</td>
      <td>X</td>
      <td>X</td>
      <td>AlbertForMaskedLM, Error: weights_offset must be aligned to 16K boundary</td>
    </tr>
    <tr>
      <td>huggingface</td>
      <td>DebertaV2ForMaskedLM</td>
      <td>multiple</td>
      <td>pass_due_to_skip</td>
      <td>X</td>
      <td>DebertaV2ForMaskedLM, Error: weights_offset must be aligned to 16K boundary</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>timm_vision_transformer_large</td>
      <td>multiple</td>
      <td>pass_due_to_skip</td>
      <td>X</td>
      <td>timm_vision_transformer_large, Error: weights_offset must be aligned to 16K boundary</td>
    </tr>
    <tr>
      <td>huggingface</td>
      <td>AlbertForMaskedLM</td>
      <td>single</td>
      <td>X</td>
      <td>X</td>
      <td>AlbertForMaskedLM, Error: weights_offset must be aligned to 16K boundary</td>
    </tr>
    <tr>
      <td>huggingface</td>
      <td>DebertaV2ForMaskedLM</td>
      <td>single</td>
      <td>pass_due_to_skip</td>
      <td>X</td>
      <td>DebertaV2ForMaskedLM, Error: weights_offset must be aligned to 16K boundary</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>timm_vision_transformer_large</td>
      <td>single</td>
      <td>pass_due_to_skip</td>
      <td>X</td>
      <td>timm_vision_transformer_large, Error: weights_offset must be aligned to 16K boundary</td>
    </tr>
  </tbody>

</table>

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>23512dbe</td>
      <td>main</td>
      <td>23512dbe</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>f9f85bfc0b5b63274fa3fdd22afb0a456abf53f4</td>
      <td>main</td>
      <td>920ebccca2644881ece4f9e07b4a4b4787b8f2b1</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.4.0a0+69b2a0a</td>
      <td>main</td>
      <td>2.4.0a0+b829e93</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>fea73cb</td>
      <td>main</td>
      <td>fea73cb</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob//weizhuoz/enable_max_autotune_for_guilty/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference accuracy huggingface AlbertForMaskestatic default 0 aot_inductor
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/b7d287fbec0a05a3d4c9524006e6bfd1de6a71a0
[huggingface-AlbertForMaskedLM-inference-amp-static-default-multiple-accuracy-crash_guilty_commit.log](https://github.com/user-attachments/files/16851723/huggingface-AlbertForMaskedLM-inference-amp-static-default-multiple-accuracy-crash_guilty_commit.log)
cc @ezyang @chauhang @penguinwu @WeizhuoZhang-intel @chuanqi129 @chunyuan-w

**Comment by malfet** [comment]
@zxd1997066 when you create those issue, do you mind adding respective oncall labels?

**Comment by chunyuan-w** [comment]
cc @leslie-fang-intel

**Comment by chuanqi129** [comment]
> @zxd1997066 when you create those issue, do you mind adding respective oncall labels?

Hi @malfet, could you please help to add the permission to @zxd1997066? He don't have the permission now. Thanks.

**Comment by leslie-fang-intel** [comment]
verified the fix in https://github.com/pytorch/pytorch/pull/135205
