### ISSUE TITLE
Load a TorchScriptModule in C++, can I change batch size?

### ISSUE THREAD

**Issue by liuhuaiyu** [pytorch/pytorch#13502]
When I serialized my module, the instance's dimension I passed to it was (4, 9, 32, 32), which '4' represented batch size.
After I loaded it in C environment, I found I could only forward a tensor's dimension exactly the (4, 9, 32, 32).
So is there any way I could forward an arbitrary batch size tensor in C environment.
Besides, originally the input size was (4, 1, 9, 32, 32), but it couldn't work, so I changed it to (4, 9, 32, 32) and worked. So does it means that the torchscript module loaded in c++ can only forward a 4 dimension tensor? 

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by zou3519** [comment]
Can we get a repro?

**Comment by liuhuaiyu** [comment]
> Can we get a repro?

Can I send to you in private?

**Comment by abhiutd** [comment]
Is there any update on this ? Are we restricted (in terms of batch size) by the random input we passed into our model for tracing?

**Comment by liuhuaiyu** [comment]
I found that we use `Tensor.view()` in module which used batch size, and I removed it and now batch size can be changed.
