### ISSUE TITLE
Infrastructure update for Channel Cloning/CDN sync

### ISSUE THREAD

**Issue by morremeyer** [pytorch/pytorch#135012]
Hey everyone, 

we (Anaconda) have been working on upgrades for the channel cloning/CDN sync infrastructure of anaconda.org, which is is used for pytorch, too.

## What's changing?

* The codebase has been updated to make the cloning more fault-tolerant and reliable
* The new infrastructure is more tightly integrated into our observability stack, enabling us to detect problems earlier and more granularly (e.g. a specific package that fails to clone instead of just a general cloning error)
* We're adding a `last-updated.json` file at the channel root, which contains the last update time both as UNIX and ISO8601 timestamps. We are using this directly to monitor the updates end-to-end. Check it out for the [anaconda](https://conda.anaconda.org/anaconda/last-updated.json) channel if you're interested!

We have already made this change for multiple channels: anaconda, r, bioconda, and conda-forge have already been migrated successfully, proving that both the maintenance process and the new infrastructure work as desired.

There will **not** be any downtime during the migration.

## Next steps

I have prepared this change on the new infrastructure already, it is now running in a dry-run mode to keep its caches up to date.

We are proposing to implement the change next **Monday, 2024-09-09 at 11:00 UTC**.

The switch to the new infrastructure will take about 30 minutes, with some follow up work afterwards.
We will keep you up to date about progress here.

Looking forward to any questions and/or feedback you have.

/cc @malfet @seemethere, @seemethere, @atalman

**Comment by morremeyer** [comment]
Hey everyone, 

I'd very much like your input on this, since we don't want to run this migration at a random point in time.

The current time window we have closes next Wednesday and then reopens after October 21st. Ideally we can run the migration before next Wednesday.

**Comment by atalman** [comment]
hi @morremeyer Any time between now and Sept 17 is a good time. We do have PyTorch conference on Sept 18 and Sept 19, hence please don't migrate during these days.

**Comment by morremeyer** [comment]
Sounds good, thanks! I’ll take care of the migration tomorrow then.

Will update here with progress

**Comment by morremeyer** [comment]
I'm starting the migration process now.

**Comment by morremeyer** [comment]
The migration has been successfully completed. Thanks everyone!
