### ISSUE TITLE
[inductor][cpu]basic_gnn_gcn AMP performance regression in 2024-09-03 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#135177]
### 🐛 Describe the bug

<p>AMP dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_gcn</td>
      <td>single</td>
      <td>1</td>
      <td>1.988919</td>
      <td>0.040752683</td>
      <td>0.081053785519677</td>
      <td>18.641713</td>
      <td>1</td>
      <td>2.43721</td>
      <td>0.033776429999999996</td>
      <td>0.08232025296029999</td>
      <td>18.648295</td>
      <td>0.82</td>
      <td>1.02</td>
      <td>0.83</td>
      <td>1.0</td>
    </tr>
  </tbody>

</table>

<p>AMP static shape cpp wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_gcn</td>
      <td>single</td>
      <td>1</td>
      <td>2.817591</td>
      <td>0.029532886999999997</td>
      <td>0.083211596615217</td>
      <td>53.242262</td>
      <td>1</td>
      <td>3.307254</td>
      <td>0.024911499</td>
      <td>0.082388654713746</td>
      <td>53.319635</td>
      <td>0.85</td>
      <td>0.99</td>
      <td>0.84</td>
      <td>1.0</td>
    </tr>
  </tbody>

</table>

<p>AMP dynamic shape cpp wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_gcn</td>
      <td>single</td>
      <td>1</td>
      <td>2.82653</td>
      <td>0.029541781</td>
      <td>0.08350073024993</td>
      <td>53.235308</td>
      <td>1</td>
      <td>3.318361</td>
      <td>0.024830922999999998</td>
      <td>0.08239796647720299</td>
      <td>53.219392</td>
      <td>0.85</td>
      <td>0.99</td>
      <td>0.84</td>
      <td>1.0</td>
    </tr>
  </tbody>

</table>

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>23512dbe</td>
      <td>main</td>
      <td>23512dbe</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>c140fa1426603322a5a69ef91300f13489db5970</td>
      <td>main</td>
      <td>2553278bae5993bd94bae4f04bf4586fb3f30d57</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.5.0a0+97ed7b3</td>
      <td>main</td>
      <td>2.4.0a0+b3f6f51</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single inference performance torchbench basic_gnn_gcn amp first static cpp
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/1ff226d88c70e66434ed9ce50deb5ae09e7e766c
[torchbench-basic_gnn_gcn-inference-amp-dynamic-default-single-performance-drop_guilty_commit.log](https://github.com/user-attachments/files/16883519/torchbench-basic_gnn_gcn-inference-amp-dynamic-default-single-performance-drop_guilty_commit.log)
cc @ezyang @chauhang @penguinwu @WeizhuoZhang-intel @chuanqi129 @zhuhaozhe

**Comment by leslie-fang-intel** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/126502
