### ISSUE TITLE
ban native ops from having python reserved kwargs as names

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#135127]
cc @ezyang @bhosmer @bdhirsh @kadeng

**Comment by malfet** [comment]
@zou3519 mind adding a bit more details here? And the ask is to add a lint or fix existing ones? Though in general it sounds very reasonable

**Comment by zou3519** [comment]
The ask is, in torchgen, error out if any new native operators get added where their argnames are reserved Python keywords.

**Comment by ishon19** [comment]
Thanks guys! I linked the PR above to close the issue.

**Comment by axsseldz** [comment]
hey @ishon19 are u still working on this one?

**Comment by ishon19** [comment]
> hey @ishon19 are u still working on this one?

Hello @axsseldz, I appreciate the check-in, yup I had created the PR, but it's definitely been a while, so I'll update the PR ASAP and would let you know if something blocks me.
