### ISSUE TITLE
An illegal memory access with CudaHalf Tensors bigger than 1/2 of total memory

### ISSUE THREAD

**Issue by AleximusOrloff** [pytorch/pytorch#13511]
On Pascal Cards pytorch(and torch7 as well) fails when acessing memory after following steps

On machine #1 I have GTX1080 with 8Gb onboard (30mln of 128D vectors actually occupy about 7,2Gb)
```
device = torch.device("cuda")
Tensor=torch.cuda.HalfTensor(30*1000*1000,128)
out=torch.mv(Tensor,Tensor[0])
print(out[0])
```
And here Cuda FAIL on print(!!) (actually on access to out[0]):
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorCopy.cpp line=70 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
File “test_pytorch.py”, line 112, in 
main()
File “test_pytorch.py”, line 26, in main
print(out[0])
File “/home/integral/.local/lib/python3.5/site-packages/torch/tensor.py”, line 57, in repr
return torch._tensor_str._str(self)
File “/home/integral/.local/lib/python3.5/site-packages/torch/_tensor_str.py”, line 256, in _str
formatter = _Formatter(get_summarized_data(self) if summarize else self)
File "/home/integral/.local/lib/python3.5/site-packages/torch/tensor_str.py", line 82, in init
copy = torch.empty(tensor.size(), dtype=torch.float64).copy(tensor).view(tensor.nelement())
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/generic/THCTensorCopy.cpp:70

On another machine same issue with Torch7, GTX1080ti

If Tensor size smaller than 1/2 of total GPU memory error doesn't occur.

**Comment by ezyang** [comment]
This is probably because we are using 32-bit indexing on one of the relevant kernels.

**Comment by AleximusOrloff** [comment]
I also checked that I can make 2 tensors sized (15\*1000\*1000,128)
and make 2 subsequental torch.mv()
And this case no error arieses

**Comment by SsnL** [comment]
cublas uses `int`, so once you get out of 32 bit range, it breaks..

**Comment by AleximusOrloff** [comment]
What do you mean by that?
2^32 ~ 4.3E+09, which is significantly bigger than 30mln

**Comment by SsnL** [comment]
30*1000*1000*128 is larger than 2^31-1

**Comment by AleximusOrloff** [comment]
30\*1000\*1000\*128 = 3.84E+09 < 2^32-1

**Comment by SsnL** [comment]
Max of signed int 32 is 2^31-1, not 2^32-1.

**Comment by AleximusOrloff** [comment]
Yep, it seems that torch.Tensor cannot have more than 2^32 elements

```
require 'cutorch'
Tensor0=torch.CudaHalfTensor(16777216,128):zero()
result=torch.mv(Tensor0,Tensor0[1])
print(result[1])

```
Fine

```
require 'cutorch'
Tensor0=torch.CudaHalfTensor(16777217,128):zero()
result=torch.mv(Tensor0,Tensor0[1])
print(result[1])

```
Fails

**Comment by soumith** [comment]
what is `require 'cutorch'`? are you using Lua?

**Comment by AleximusOrloff** [comment]
Yes, As I mentioned - issue also appears in Torch7, so I checked SsnL's hypothesis in Lua.

**Comment by AleximusOrloff** [comment]
Now I received
THCudaCheck FAIL file=/home/integral/torch/extra/cutorch/lib/THC/generic/THCStorage.c line=32 error=77 : an illegal memory access was encountered
/home/integral/torch/install/bin/luajit: cuda runtime error (77) : an illegal memory access was encountered at /home/integral/torch/extra/cutorch/lib/THC/generic/THCStorage.c:32


with tensorsize only 490648x128

**Comment by AleximusOrloff** [comment]
After some research I found out that at least some of such errors are connected to nan amounts.
i.e. If CudaHalfTensor has some nan figures within, it leads to error in some place in code.

**Comment by ngimel** [comment]
Closing due to age
