### ISSUE TITLE
BypassFxGraphCache: During handling of the above exception, another exception occurred...

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#135172]
### 🐛 Describe the bug

There's something weird about how the try-except handlers are setup, such that the BypassFxGraphCache is getting chained to subsequent exceptions. Example traceback: https://gist.github.com/ezyang/a2b68050a3972e1fb3eeb58ca7410577

Don't do the non-cache path inside except block. Get out of except and then do it.

cc @chauhang @penguinwu @oulgen @jamesjwu 

### Versions

main

**Comment by oulgen** [comment]
Do you have a quick repro so that I can make sure it is fixed?

**Comment by ezyang** [comment]
It is a reliable repro but you have to install fbgemm and torchrec. Probably easiest to just fix it and I can check it for you.

**Comment by oulgen** [comment]
Try https://github.com/pytorch/pytorch/pull/135175
