### ISSUE TITLE
Flexattention: compilation fails when using block mask

### ISSUE THREAD

**Issue by dabeschte** [pytorch/pytorch#135206]
### 🐛 Describe the bug

I get an BackendCompilerFailed error when trying to compile flexattention with a block mask. 

Here is a minimal working sample to reproduce the error:

```
import torch
from torch.nn.attention.flex_attention import create_block_mask, flex_attention
import numpy as np

B, H, S, D = 4, 16, 2048, 128
data_dtype = torch.bfloat16
paddings_tensor = torch.zeros((B), device="cuda")

def truncate_block_mask(b, h, q_idx, kv_idx):
    return torch.where(q_idx < paddings_tensor[b], torch.where(kv_idx < paddings_tensor[b], True, False), False)

def flex_attn_wrapper(q, k, v):
    return flex_attention(q, k, v)

def flex_attn_block_mask_wrapper(q, k, v, block_mask):
    return flex_attention(q, k, v, block_mask=block_mask)

flex_attn_compiled = torch.compile(flex_attn_wrapper, dynamic=True)
flex_attn_block_mask_compiled = torch.compile(flex_attn_block_mask_wrapper, dynamic=True)

q = torch.randn(B, H, S, D, device="cuda", dtype=data_dtype, requires_grad=True)
k = torch.randn(B, H, S, D, device="cuda", dtype=data_dtype, requires_grad=True)
v = torch.randn(B, H, S, D, device="cuda", dtype=data_dtype, requires_grad=True)

for _ in range(10):        
    paddings_tensor[:B] = torch.tensor(np.random.randint(0.7*S, S, size=B), device="cuda")
    block_mask = create_block_mask(truncate_block_mask, B, H=None, Q_LEN=S, KV_LEN=S, device="cuda", _compile=True)

    # this works
    out_vanilla = flex_attn_compiled(q, k, v)
    # this fails
    out_masked = flex_attn_block_mask_compiled(q, k, v, block_mask)
```

Full error message:
```
Exception has occurred: BackendCompilerFailed
backend='inductor' raised:
LoweringException: NoValidChoicesError: No choices to select, please consider adding ATEN into max_autotune_gemm_backends config (defined in torch/_inductor/config.py) to allow at least one choice. 
  target: flex_attention
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='primals_3', layout=FixedLayout('cuda', torch.bfloat16, size=[s0, 16, s2, 128], stride=[2048*s2, 128*s2, 128, 1]))
  ))
  args[1]: TensorBox(StorageBox(
    InputBuffer(name='primals_4', layout=FixedLayout('cuda', torch.bfloat16, size=[s0, 16, s2, 128], stride=[2048*s2, 128*s2, 128, 1]))
  ))
  args[2]: TensorBox(StorageBox(
    InputBuffer(name='primals_5', layout=FixedLayout('cuda', torch.bfloat16, size=[s0, 16, s2, 128], stride=[2048*s2, 128*s2, 128, 1]))
  ))
  args[3]: Subgraph(name='sdpa_score0', graph_module=<lambda>(), graph=None)
  args[4]: (TensorBox(StorageBox(
    InputBuffer(name='primals_7', layout=FixedLayout('cuda', torch.int32, size=[s0, 1, 16], stride=[16, 16, 1]))
  )), TensorBox(StorageBox(
    InputBuffer(name='primals_8', layout=FixedLayout('cuda', torch.int32, size=[s0, 1, 16, 16], stride=[256, 256, 16, 1]))
  )), TensorBox(StorageBox(
    InputBuffer(name='primals_9', layout=FixedLayout('cuda', torch.int32, size=[s0, 1, 16], stride=[16, 16, 1]))
  )), TensorBox(StorageBox(
    InputBuffer(name='primals_10', layout=FixedLayout('cuda', torch.int32, size=[s0, 1, 16, 16], stride=[256, 256, 16, 1]))
  )), TensorBox(StorageBox(
    InputBuffer(name='primals_11', layout=FixedLayout('cuda', torch.int32, size=[s0, 1, 16], stride=[16, 16, 1]))
  )), TensorBox(StorageBox(
    InputBuffer(name='primals_12', layout=FixedLayout('cuda', torch.int32, size=[s0, 1, 16, 16], stride=[256, 256, 16, 1]))
  )), TensorBox(StorageBox(
    InputBuffer(name='primals_13', layout=FixedLayout('cuda', torch.int32, size=[s0, 1, 16], stride=[16, 16, 1]))
  )), TensorBox(StorageBox(
    InputBuffer(name='primals_14', layout=FixedLayout('cuda', torch.int32, size=[s0, 1, 16, 16], stride=[256, 256, 16, 1]))
  )), s4, s5, Subgraph(name='sdpa_mask0', graph_module=<lambda>(), graph=None))
  args[5]: 0.08838834764831843
  args[6]: {'ROWS_GUARANTEED_SAFE': False, 'PRESCALE_QK': False, 'OUTPUT_LOGSUMEXP': True}
  args[7]: ()
  args[8]: (TensorBox(StorageBox(
    InputBuffer(name='primals_6', layout=FixedLayout('cuda', torch.float32, size=[s0], stride=[1]))
  )),)
```

### Versions

Collecting environment information...
PyTorch version: 2.5.0.dev20240903
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.31

Python version: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1062-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 2: NVIDIA H100 80GB HBM3

Nvidia driver version: 535.183.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.5.0.dev20240903
[pip3] torchao==0.3.1
[pip3] torchaudio==2.5.0.dev20240903
[pip3] torcheval==0.0.7
[pip3] torchtune==0.2.1
[pip3] torchvision==0.20.0.dev20240903
[pip3] triton==3.0.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    https://aws-ml-conda.s3.us-west-2.amazonaws.com
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.26.4          py310hb13e2d6_0    conda-forge
[conda] pytorch                   2.5.0.dev20240903 py3.10_cuda12.4_cudnn9.1.0_0    pytorch-nightly
[conda] pytorch-cuda              12.4                 hc786d27_7    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchao                   0.3.1                    pypi_0    pypi
[conda] torchaudio                2.5.0.dev20240903     py310_cu124    pytorch-nightly
[conda] torcheval                 0.0.7                    pypi_0    pypi
[conda] torchtriton               3.0.0+dedb7bdf33           py310    pytorch-nightly
[conda] torchtune                 0.2.1                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20240903     py310_cu124    pytorch-nightly
[conda] triton                    3.0.0                    pypi_0    pypi

Edit: I tried pytorch-cuda 12.1 too, but ran into the same issue.

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki @ezyang @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @Chillee @yanboliang @BoyuanFeng

**Comment by SamGalanakis** [comment]
Think this is the same as  #134560, so not a fix but it seems to work with dynamic disabled.

**Comment by Chillee** [comment]
This seems to work now.
