### ISSUE TITLE
1.0 preview does not support for jupyter notebook

### ISSUE THREAD

**Issue by cableyang** [pytorch/pytorch#13536]
## 🐛 Bug

conda install pytorch1.0,and does not work well on jupyter notebook

## To Reproduce

1.conda install pytorch_nightly 
2.source activate torch1
3.jupyter notebook

then the juypter notebook doesnot work
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.0preview
 - OS (e.g., Linux):Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Build command you used (if compiling from source):
 - Python version:3.6
 - CUDA/cuDNN version:9.0/2.4
 - GPU models and configuration:gtx1080ti
 - Any other relevant information:

**Comment by cableyang** [comment]
I Find the reason is conda install on new cond-env does not have jupyter install 
_============
solution add：
`conda install -n myenv ipython jupyter`
then start jupyter notebook the solved 

Thanks

**Comment by fmassa** [comment]
Closing as doesn't look like a problem with PyTorch
