### ISSUE TITLE
foreach=True + fused=True raises RuntimeError for Adam, AdamW and SGD, despite note in docs

### ISSUE THREAD

**Issue by cgoemaere** [pytorch/pytorch#135340]
### 📚 The doc issue

In the documentation for Adam, AdamW and SGD, there is a special note to explain the functionality of `fused` and `foreach`. Among other things, it explicitly states:

> If the user specifies True for both foreach and fused, we will prioritize fused over foreach, as it is typically faster.

Yet, setting both options to True raises a RuntimeError, caused by this (shortened) code snippet in the `__init__` of the three optimizers:
```python
if fused:
    ...
    if foreach:
        raise RuntimeError("`fused` and `foreach` cannot be `True` together.")
```

### Suggest a potential alternative/fix

If `fused` and `foreach` cannot both be set to True: rewrite the note.
Otherwise: remove the unnecessary check from the code.

cc @svekars @brycebortree @tstatler @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by janeyx99** [comment]
lol fair, let's change the docs as having the check is less confusing anyway
