### ISSUE TITLE
bitwise_xor  does not work for uint32

### ISSUE THREAD

**Issue by alexshtf** [pytorch/pytorch#135436]
### 🐛 Describe the bug

The following code snipper produces an error when run on my MacBook Pro using Apple M2 Pro chip:
```python
a = torch.tensor(1, dtype=torch.uint32)
b = torch.tensor(2, dtype=torch.uint32)
torch.bitwise_xor(a, b)
```
The error I'm getting is:
```
Traceback (most recent call last):
  File "/Users/ashtoff/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
RuntimeError: "bitwise_xor_cpu" not implemented for 'UInt32'
```
The same for uint64 and uint16.

### Versions

Collecting environment information...
PyTorch version: 2.4.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 18.1.8
CMake version: version 3.29.3
Libc version: N/A

Python version: 3.9.6 (default, Feb  3 2024, 15:58:27)  [Clang 15.0.0 (clang-1500.3.9.4)] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==2.0.2
[pip3] torch==2.4.1
[conda] No relevant packages

**Comment by malfet** [comment]
@ezyang added a bunch of unsigned types to PyTorch but I'm not really sure what's the story behind adding eager ops for it. Adding `triage review` as I'm unsure what label to assign to it. But PR to add implementation is trivial, let me propose it in a few

**Comment by ezyang** [comment]
@malfet The policy I set for myself is that if someone asked for it, we'd add it. https://github.com/pytorch/pytorch/pull/123643 is a better reference PR, you want to use the new AT_DISPATCH_V2 specifically.

Add me as reviewer if you send it.

**Comment by malfet** [comment]
Ok, removing triage review and grabbing for myself. Feels reasonable to extend all bitwise ops to unsigned types
