### ISSUE TITLE
Setting a wrong type value instead of a correct integer typed value to `in_features` or `out_features` argument of `nn.Linear()` gets indirect error messages

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#135463]
### 🐛 Describe the bug

Setting a wrong type value instead of a correct `float` type value to `in_features` and `out_features` argument of [nn.Linear()](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html) gets the indirect error messages as shown below:

```python
import torch
from torch import nn

my_tensor = torch.tensor([2., 7., 4.])
                             # ↓↓
linear = nn.Linear(in_features=3., out_features=5)
```

> TypeError: empty(): argument 'size' failed to unpack the object at pos 2 with error "type must be tuple of ints,but got float"

```python
import torch
from torch import nn

my_tensor = torch.tensor([2., 7., 4.])
                                             # ↓↓↓↓↓↓
linear = nn.Linear(in_features=3, out_features=5.+0.j)
```

```
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
```

So, the error messages should be something like as shown below:

> `in_features` must be `float`.

> `out_features` must be `float`.

### Versions

```python
import torch

torch.__version__ # 2.4.0+cu121
```

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @malfet

**Comment by sanskarmodi8** [comment]
Hi @hyperkai ,
You're suggesting that the error message should show following errror message directly instead of indirect errors right?-

`in_features must be float`
`out_features must be float`

I think I can work on this. Let me know if somebody else is working on it or my interpretation of the issue here is wrong.

**Comment by malfet** [comment]
Again, I'm quite divided what to do here, perhaps one should just coerce in_features/out_features to int, to make something like `nn.Linear(in_feautres="2", out_features=3.14)` work vs error out that inputs are of unexpected type

**Comment by malfet** [comment]
We will accept the PR that makes error message better here

**Comment by 0xD4rky** [comment]
I would like to take this up

**Comment by sanskarmodi8** [comment]
> We will accept the PR that makes error message better here

That's good. I'm working on it

**Comment by sanskarmodi8** [comment]
Hi @hyperkai and @malfet ,

I have opened a Pull Request to make error messages better considering this issue https://github.com/pytorch/pytorch/pull/135596
