### ISSUE TITLE
Unefined reference to C10::Error::Error when linking against libTorch 

### ISSUE THREAD

**Issue by ShahriarSS** [pytorch/pytorch#13541]
## 🐛 Bug

Hi
I just dowloaded libTorch to work with the C++ API of pytorch. I tried to link against it in qt creator and include <torch/torch.h> but ran into an error. Here it is:

error: undefined reference to `c10::Error::Error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*)'

I thought that the problem was that I didn't link against c10 but after I did that the error still remained.

here is how I link against libTorch in my .pro file:
INCLUDEPATH += $$PWD/include
INCLUDEPATH += $$PWD/include/torch/csrc/api/include

LIBS += -L$$PWD/lib

LIBS += -ltorch -lnvrtc -lc10
LIBS += -lcudnn -lcuda -lcudart -lcublas -lcurand -lcusolver

Here  $$PWD/ is the path to libTorch directory.

I know that i can use cmake but I didn't try that. I want to be able to use pytorch with qmake system because it is easier and more clean to work with. 
My OS is Fedora 28 and I have CUDA 9.2 installed on my system

**Comment by goldsborough** [comment]
I think you're missing `"-D_GLIBCXX_USE_CXX11_ABI=0"` in your build flags. We provide this in our TorchConfig.cmake, which is why we recommend cmake as the easiest way to build LibTorch. That said, you can add that to your QtCreator config. See https://github.com/pytorch/pytorch/blob/master/cmake/TorchConfig.cmake.in for the relevant file

**Comment by ShahriarSS** [comment]
@goldsborough 
Thank you that fixed the problem. Here is how to apply the flag for those who have the same problem:
QMAKE_CXXFLAGS += -D_GLIBCXX_USE_CXX11_ABI=0

**Comment by sky-fun** [comment]
@goldsborough what should i do if i need to use libtorch in my project which must set "-D_GLIBCXX_USE_CXX11_ABI=1" ? anything suggestion？

**Comment by goldsborough** [comment]
@sky-fun compile PyTorch from source

**Comment by libichong** [comment]
@goldsborough How can i use the flag in msbuild? Do you have any suggestion

**Comment by martinruenz** [comment]
@goldsborough
Similar to @sky-fun I would like to set `-D_GLIBCXX_USE_CXX11_ABI=1`. However, when I compile pytorch myself (`-D_GLIBCXX_USE_CXX11_ABI=1` is default on my platform) I keep running into a typical ABI related error:

> c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

On one of the platforms I tested the error appeared at runtime, on another platform at compile-time. (Which is also kind of weird)

Is there a flag that I am missing? It seems that c10 is not build with the new ABI, whilst the rest is? Since `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)` looks like a missing C++11 ABI definition.

**Comment by Kuldaen** [comment]
We are getting this problem too. It is not an abi issue. The cxx11 namespace only applies to std:: eg. std:: basic_string. Looking at libc10.so it seems this constructor is missing altogether

**Comment by jinfagang** [comment]
It's not ABI issue at all....

```
: In function `torch::jit::SourceRange::highlight(std::ostream&) const':
wavehands_stop.cc:(.text._ZNK5torch3jit11SourceRange9highlightERSo[_ZNK5torch3jit11SourceRange9highlightERSo]+0x1b8): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
wavehands_stop.cc:(.text._ZNK5torch3jit11SourceRange9highlightERSo[_ZNK5torch3jit11SourceRange9highlightERSo]+0x2a6): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
wavehands_stop.cc:(.text._ZNK5torch3jit11SourceRange9highlightERSo[_ZNK5torch3jit11SourceRange9highlightERSo]+0x3f3): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
wavehands_stop.cc:(.text._ZNK5torch3jit11SourceRange9highlightERSo[_ZNK5torch3jit11SourceRange9highlightERSo]+0x538): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/wavehands_stop_node.dir/src/wavehands_stop.cc.o: In function `torch::jit::Value::setType(std::shared_ptr<c10::Type>)':
wavehands_stop.cc:(.text._ZN5torch3jit5Value7setTypeESt10shared_ptrIN3c104TypeEE[_ZN5torch3jit5Value7setTypeESt10shared_ptrIN3c104TypeEE]+0xba): undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/wavehands_stop_node.dir/src/wavehands_stop.cc.o: In function `torch::jit::script::SimpleValue::SimpleValue(torch::jit::Value*)':
wavehands_stop.cc:(.text._ZN5torch3jit6script11SimpleValueC2EPNS0_5ValueE[_ZN5torch3jit6script11SimpleValueC5EPNS0_5ValueE]+0x1f): undefined reference to `vtable for torch::jit::script::SimpleValue'
collect2: error: ld returned 1 exit status

```

I keep getting this issue

**Comment by jinfagang** [comment]
OK, I am to young to simple, sometimes naive. I tried add a flag to override like this:

```
set(TORCH_CXX_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=1")

```

It has no effect...... When I comment out this in libtorch Torch.cmake:

```
# When we build libtorch with the old GCC ABI, dependent libraries must too.
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
  # set(TORCH_CXX_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=0")
endif()

```

It can link libtorch..........

```

**Comment by amin-amani** [comment]
on cmake u can use 
set(CMAKE_CXX_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=0")

**Comment by 3014214149** [comment]
I met similar error. I looked up the file "TorchConf.cmake", it said "
# When we build libtorch with the old GCC ABI, dependent libraries must too.
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
  set(TORCH_CXX_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=0")
endif()
"
But I still could not link the library. 
The error still exist.
/home/cbq/OpenFOAM/cbq-4.1/platforms/linux64GccDPInt32Opt/lib/libreynoldsnet.so: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

Could anyone help me ? Thanks a lot.

**Comment by ajinkyaambatwar** [comment]
I am trying to build custom torch functions with cuda dynamic parallelism support.As per [this](https://stackoverflow.com/questions/22115197/dynamic-parallelism-undefined-reference-to-cudaregisterlinkedbinary-linking) suggestion, I am compiling my CUDA code with the cpp code.
Basically it has three commands
```
nvcc -arch=sm_35 -rdc=true -c geo_query_gpu.cu -I libtorch/include/ -I ../include/ -L /usr/local/cuda-10.2/lib -lcudart -lcudadevrt

nvcc -arch=sm_35 -dlink -o geo_link.o geo_query_gpu.o -lcudadevrt -lcudart

g++ geo_query_gpu.o geo_link.o geo_query.cpp -I /libtorch/include/ -I ../include -I /libtorch/include/torch/csrc/api/include/ -I /home/ajinkya/anaconda3/envs/env/include/python3.6m/ -I /usr/local/cuda-10.2/include/ -D_GLIBCXX_USE_CXX11_ABI=0 -L /libtorch/lib/ -lc10 -lc10_cuda -ltorch_cpu -L /usr/local/cuda-10.2/lib64/ -lcudart -lcudadevrt
```
 My cpp code has following inclusions
```
#include "geo_query.h"
#include "utils.h"
#include <stdio.h>
```
where geo_query.h is
```
#pragma once
#include <torch/extension.h>
```
The utils.h has
```
#pragma once
#include <ATen/cuda/CUDAContext.h>
#include <torch/extension.h>
```
So to build this I am needed to use libtorch and libc10.

I tried to set the ```-D_GLIBCXX_USE_CXX11_ABI=0``` flag during build.
I still get the error
```undefined reference to `c10::detail::torchCheckFail``` and mutiple other errors related to c10::<somthing>

My torch is installed from pip directly. Despite that having the ABI issue is very counterproductive :(
Is there any way to solve this?

**Comment by wzcwd** [comment]
> I think you're missing `"-D_GLIBCXX_USE_CXX11_ABI=0"` in your build flags. We provide this in our TorchConfig.cmake, which is why we recommend cmake as the easiest way to build LibTorch. That said, you can add that to your QtCreator config. See https://github.com/pytorch/pytorch/blob/master/cmake/TorchConfig.cmake.in for the relevant file
> 
> Please let me know if that fixes the issue.

It works, thanks you sooooo much!!!
