### ISSUE TITLE
Do I have to recompile (source build) to use pytorch when transfer to another machine?

### ISSUE THREAD

**Issue by PeterHuang2015** [pytorch/pytorch#13542]
Currently, I am using a portable hard drive, bootin different machine at home/company to work, one with 96 0M and another with Titan Xp. The conda version pytorch works well on both machine but the source build one report `RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device` error, any idea about fixing the problem to make the source build one portable between different machines, I tried recompile and it works but would not like to compile for hours each time to get it work.

__CUDA 10.0, cuDNN 7.3, Ubuntu 16.04, source code at v1.0rc1.__

Thx!

**Comment by soumith** [comment]
both machines have different graphics cards.

What you need to do is use this command:
https://github.com/pytorch/pytorch/blob/master/docker/pytorch/Dockerfile#L28-L30

It will make sure that PyTorch is built not just for the local machine's GPU type, but all GPU types

**Comment by PeterHuang2015** [comment]
Thx @soumith !
