### ISSUE TITLE
[RFC] Switch batched inverse to cuBLAS instead of MAGMA

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#13546]
#9949 added batched inverse support, and seems to be facing some issue with large batches (#13276). This seems to be a MAGMA-related issue.

Considering the importance of the inverse operation, I am proposing that we modify batched inverse to use cuBLAS rather than MAGMA. There are functions in cuBLAS that enable batched inverse - [getri](https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-getribatched) and [getrf](https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-getrfbatched). Furthermore, they seem to provide an [optimization](https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-matinvbatched) for small matrices (size less than 32 x 32).

Please let me know your thoughts about this.

cc: @zou3519 @SsnL @soumith

**Comment by zou3519** [comment]
@soumith said something about bad performance of batched inverse in cublas?

**Comment by vishwakftw** [comment]
@zou3519 apologies for the delay in the reply. Yes, @soumith did mention about the batched inverse being slower on cuBLAS when compared with MAGMA. This is the [comment](https://github.com/pytorch/pytorch/issues/13276#issuecomment-435645148).

**Comment by vishwakftw** [comment]
I went through Tensorflow's code, and this is what they seem to have done:
- Use cuBLAS for very large batch sizes with small matrices
- Use cuSolver otherwise

i thought I'll leave this here, just in case.

**Comment by ngimel** [comment]
This has been done IIUC
