### ISSUE TITLE
[ONNX] Verify handling of zero output ops

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#135419]
`aten._assert_scalar`

**Comment by titaiwangms** [comment]
I had test case here https://github.com/pytorch/pytorch/pull/126889

**Comment by justinchuby** [comment]
aten._assert_scalar Seems to be a different op that we didn’t handle before

**Comment by justinchuby** [comment]
In the graph construction logic we can make sure it doesn’t fail the whole thing

**Comment by titaiwangms** [comment]
Do you have a minimum repro? I tried to create one, but it fails on torch.export.

**Comment by justinchuby** [comment]
I wasn't able to either. I saw this in one of the models. Will post when I see it again.

**Comment by justinchuby** [comment]
@titaiwangms For now I think we should just add it to the removal list in https://github.com/pytorch/pytorch/blob/1d9fefff19c96483ebeaabb8f3e4c5aa4a7dc0c9/torch/onnx/_internal/exporter/_fx_passes.py#L40-L43
