### ISSUE TITLE
KL Divergence for Independent

### ISSUE THREAD

**Issue by didriknielsen** [pytorch/pytorch#13545]
## 🚀 Feature

It would be useful to be able to compute the KL divergence between two instances of `torch.distributions.Independent`.

## Motivation

Currently, computing the KL divergence between two instances of `torch.distributions.Independent` raises a `NotImplementedError`, even if the KL divergence is well defined for the base distributions.  
The example code below illustrates the problem:
```python
import torch
from torch.distributions import Normal, Independent, kl

# Normals with batch_shape=(3,) and event_shape=()
dist1 = Normal(torch.zeros(3), torch.ones(3))
dist2 = Normal(torch.zeros(3), 5*torch.ones(3))

# Normals with batch_shape=() and event_shape=(3,)
dist1_indep = Independent(dist1, 1)
dist2_indep = Independent(dist2, 1)

# Works fine, returns KL with shape (3,), one for each Normal
kl_divergence = kl.kl_divergence(dist1, dist2) 

# Raises NotImplementedError, should return KL with shape (), the sum of the KL for each Normal
kl_divergence_indep = kl.kl_divergence(dist1_indep, dist2_indep)
```
It would make sense to let `kl.kl_divergence` for two instances of `torch.distributions.Independent` return the sum of the KL divergences for each of the base distributions.

**Comment by zou3519** [comment]
cc @fritzo

**Comment by fritzo** [comment]
This should be pretty easy. @didriknielsen do you want to create a PR with tests in test/test_distributions.py
```py
@register_kl(Independent, Independent)
def _kl_independent_independent(p, q):
    if p.reinterpreted_batch_ndims != q.reinterpreted_batch_ndims:
        raise NotImplementedError
    result = kl_divergence(p.base_dist, q.base_dist)
    return _sum_rightmost(result, p.reinterpreted_batch_ndims)
```

**Comment by vishwakftw** [comment]
Closed via https://github.com/pytorch/pytorch/commit/8045b3eb143ed70ab1873e148d266d56e0e1481f.
