### ISSUE TITLE
[𝔽𝔸ℚ𝕤]𝕎𝕙𝕒𝕥 𝕚𝕤 𝕥𝕙𝕖 𝟚𝟜-𝕙𝕠𝕦𝕣 𝕣𝕦𝕝𝕖 𝕗𝕠𝕣 𝕃𝕦𝕗𝕥𝕙𝕒𝕟𝕤𝕒?@𝕊𝕦𝕡𝕡𝕠𝕣𝕥 

### ISSUE THREAD

**Issue by Denny0001** [pytorch/pytorch#135493]
### 🐛 Describe the bug

Lufthansa provides a 24-hour flexibility policy that lets you modify or cancel your booking without a fee if changes are made within 24 hours of your initial reservation. 🛫 For help, you can contact their live support team at 📞 +1-855-590-0778, +1-855-550-0903, or +1-855^590^0778 (no wait time).

### Versions

Lufthansa provides a 24-hour flexibility policy that lets you modify or cancel your booking without a fee if changes are made within 24 hours of your initial reservation. 🛫 For help, you can contact their live support team at 📞 +1-855-590-0778, +1-855-550-0903, or +1-855^590^0778 (no wait time).

**Comment by hvaara** [comment]
@Denny0001 has been reported to GitHub for spam. Same thing happened in https://github.com/microsoft/vstest, where it's become a huge problem:
<img width="1248" alt="image" src="https://github.com/user-attachments/assets/362d580a-31a4-4fce-8019-3e177b86cb7b">
