### ISSUE TITLE
`bias` argument of `nn.Linear()` works with an `int`, `float` and `complex` value against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#135483]
### 🐛 Describe the bug

[The doc](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html) of `nn.Linear()` says `bias` argument is `bool` as shown below:

> - bias ([bool](https://docs.python.org/3/library/functions.html#bool)) – If set to `False`, the layer will not learn an additive `bias`. Default: `True`

But `bias` argument with an `int`, `float` and `complex` value works as shown below:

```python
my_tensor = torch.tensor([2., 7., 4.])
                                                     # ↓↓
linear = nn.Linear(in_features=3, out_features=5, bias=10)
                                                     # ↓↓↓
linear = nn.Linear(in_features=3, out_features=5, bias=10.)
                                                     # ↓↓↓↓↓↓↓
linear = nn.Linear(in_features=3, out_features=5, bias=10.+0.j)
linear(input=my_tensor)
# tensor([ 5.1104,  1.2912, -0.8506, -1.9801, -5.2040], grad_fn=<ViewBackward0>)
```

### Versions

```python
import torch

torch.__version__ # 2.4.0+cu121
```

cc @svekars @brycebortree @tstatler @malfet

**Comment by malfet** [comment]
I'm tempted to close it as `works as expected` vs slapping `good first issue`.
Currently it's implemented as 
https://github.com/pytorch/pytorch/blob/dfb2b661f76372c821bfdd47f1beafb0b06f35ac/torch/nn/modules/linear.py#L108-L111
And all of the above mentioned examples are indeed truthy:
```
% python3 -c "print(True if 10 else False)"
True
```
