### ISSUE TITLE
torch._dynamo.exc.Unsupported: builtin: eq [<class 'torch._dynamo.variables.misc.GetAttrVariable'>, <class 'torch._dynamo.variables.constant.EnumVariable'>] False

### ISSUE THREAD

**Issue by yuwenzho** [pytorch/pytorch#135573]
### 🐛 Describe the bug

```python
import torch
import enum

class SampleEnum(enum.Enum):
    A = 0
    B = 1

class Sample:
    _enum: SampleEnum

    def is_a(self) -> bool:
        return self._enum == SampleEnum.A

    def is_b(self) -> bool:
        return self._enum == SampleEnum.B

class ASample(Sample):
    _enum = SampleEnum.A

current_sample = ASample()

def foo():
    is_a = torch.tensor(0)
    if current_sample.is_a():
        is_a = torch.tensor(1)
    return is_a

print(torch.compile(foo, fullgraph=True)())
```
fail with:
`torch._dynamo.exc.Unsupported: builtin: eq [<class 'torch._dynamo.variables.misc.GetAttrVariable'>, <class 'torch._dynamo.variables.constant.EnumVariable'>] False
`

### Versions

torch==2.4.1

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec

**Comment by xmfan** [comment]
This repro works in PyTorch nightly, it'll be available in the next stable release
