### ISSUE TITLE
Assertion fails when using DataParallel with nn.Embedding and max_norm != None

### ISSUE THREAD

**Issue by adefossez** [pytorch/pytorch#13569]
## 🐛 Bug

When using `DataParallel` with `nn.Embedding` with `max_norm` set to a non `None` value, the following assertion is triggered:

`RuntimeError: output_nr_ == 0 ASSERT FAILED at /opt/conda/conda-bld/pytorch-nightly_1541411195070/work/torch/csrc/autograd/variable.cpp:196, please report a bug to PyTorch.`

## To Reproduce

To reproduce, use the following script:

```python
import torch
from torch import nn


def main():
    device = "cuda"
    embedding = nn.Embedding(128, 16, max_norm=1).to(device)
    batch = torch.randint(128, (32, ), device=device)

    embedding.forward(batch)
    print("OK")

    parallel = nn.DataParallel(embedding)
    parallel.forward(batch)


if __name__ == "__main__":
    main()
```

This will output the following:

    OK
    Traceback (most recent call last):
    File ".../lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
    File ".../lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
    File ".../minimal.py", line 20, in <module>
        main()
    File ".../minimal.py", line 16, in main
        parallel.forward(batch)
    File ".../lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
        outputs = self.parallel_apply(replicas, inputs, kwargs)
    File ".../lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
        return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
    File ".../lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
        raise output
    File ".../lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
        output = module(*input, **kwargs)
    File ".../lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
        result = self.forward(*input, **kwargs)
    File ".../lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 113, in forward
        self.norm_type, self.scale_grad_by_freq, self.sparse)
    File ".../lib/python3.7/site-packages/torch/nn/functional.py", line 1233, in embedding
        return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
    RuntimeError: output_nr_ == 0 ASSERT FAILED at /opt/conda/conda-bld/pytorch-nightly_1541411195070/work/torch/csrc/autograd/variable.cpp:196, please report a bug to PyTorch.a

## Expected behavior

I expect the `forward` call to work the same whether I use `DataParallel` or not.

## Environment

PyTorch version: 1.0.0.dev20181105
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 396.51
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.2)
[pip] torch (1.0.0.dev20181105)
[pip] torchvision (0.2.1)
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py37_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
[conda] pytorch-nightly           1.0.0.dev20181105 py3.7_cuda9.2.148_cudnn7.1.4_0  [cuda92]  pytorch
[conda] torchvision               0.2.1                    py37_1    pytorch

**Comment by nairbv** [comment]
@adefossez my attempt to repro failed with latest master, is this still an issue?

**Comment by adefossez** [comment]
Hi @nairbv, thanks for looking into this. Let me try that. I have never compiled pytorch from source so I'll do that and come back to you.

**Comment by adefossez** [comment]
That was my mistake. Indeed the bug is not present on nightly, I wrongly assumed I was using the nightly.
Thanks @soumith and @nairbv, sorry for the false alarm.
Cheers

**Comment by nairbv** [comment]
OK, closing this issue then.

**Comment by boscotsang** [comment]
I have encountered this problem with torch-1.0.1.post2. Even I set max_norm=None, the problem still exisit.

**Comment by boscotsang** [comment]
In torch-1.0.1.post2 the problem still exisit.

**Comment by enk100** [comment]
In pytorch-nightly (1.0.0.dev20190201) the problem still exist.
