### ISSUE TITLE
torch._dynamo.exc.Unsupported: Graph break due to unsupported Python builtin _warnings.warn.

### ISSUE THREAD

**Issue by mieshkiwrk** [pytorch/pytorch#135688]
### 🐛 Describe the bug

torch._dynamo.exc.Unsupported: Graph break due to unsupported Python builtin _warnings.warn. Please file an issue on GitHub so the PyTorch team can add support for it.

### Minified repro

```python
import torch
import warnings


def fn():
    warnings.warn("aaa")

def repro():
    compiled_fn = torch.compile(fn)
    compiled_fn()

repro()
```

### Versions

torch==2.4.1

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec

**Comment by ezyang** [comment]
Try 

```
# A set of logging functions which will be reordered to the end of graph breaks,
# allowing dynamo to construct larget graph. Note that there are some
# limitations to this, such as how it does not correctly print objects that were
# mutated after the print statement.
reorderable_logging_functions: Set[Callable[[Any], None]] = set()
```

in torch._dynamo.config

cc @angelayi @yanboliang

**Comment by mieshkiwrk** [comment]
It does help, thanks
