### ISSUE TITLE
`in_channels` and `kernel_size` argument of `nn.Conv1d()` with a bool value work against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#135650]
### 🐛 Describe the bug

[The doc](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html) of `nn.Conv1d()` says about the type of `in_channels` and `kernel_size` argument as shown below:

> - in_channels ([int](https://docs.python.org/3/library/functions.html#int)) – Number of channels in the input image

> - kernel_size ([int](https://docs.python.org/3/library/functions.html#int) or [tuple](https://docs.python.org/3/library/stdtypes.html#tuple)) – Size of the convolving kernel

`in_channels` and `kernel_size` with a `bool` value work against the doc as shown below:

```python
import torch
from torch import nn

my_tensor = torch.tensor([[0., 1., 2.]])

torch.manual_seed(42)        # ↓↓↓↓                            # ↓↓↓↓ 
conv1d = nn.Conv1d(in_channels=True, out_channels=3, kernel_size=True)
conv1d(input=my_tensor)
# tensor([[-0.7336, -1.2205, -1.7073],
#         [0.8692, 1.4565, 2.0438],
#         [0.1872, 1.0687, 1.9502]], grad_fn=<SqueezeBackward1>)

torch.manual_seed(42)        # ↓↓↓↓                             # ↓↓↓↓ 
conv1d = nn.Conv1d(in_channels=True, out_channels=3, kernel_size=(True,))
conv1d(input=my_tensor)
# tensor([[-0.7336, -1.2205, -1.7073],
#         [0.8692, 1.4565, 2.0438],
#         [0.1872, 1.0687, 1.9502]], grad_fn=<SqueezeBackward1>)
```

In addition, [the doc](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html) of `nn.Conv1d()` says about the type of `out_channels` argument as shown below:

> - out_channels ([int](https://docs.python.org/3/library/functions.html#int)) – Number of channels produced by the convolution

Then, `out_channels` with a `bool` value gets the error properly as shown below:

```python
import torch
from torch import nn

my_tensor = torch.tensor([[0., 1., 2.]])

torch.manual_seed(42)                        # ↓↓↓↓                      
conv1d = nn.Conv1d(in_channels=1, out_channels=True, kernel_size=1)
conv1d(input=my_tensor)
```

```
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
```

### Versions

```python
import torch

torch.__version__ # 2.4.0+cu121
```

**Comment by malfet** [comment]
Duplicate of https://github.com/pytorch/pytorch/issues/135648
