### ISSUE TITLE
Support dist.barrier with NCCL backend

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#13573]

**Comment by SsnL** [comment]
Because it is reasonable to provide a mechanism for users to know when the process group has initialized. In old THD days, I used to log a line after `init_process_group` because it used to block until all processes reaches that call (at least for NCCL). In c10d, it becomes nonblocking. So I wanted to use a dist.barrier but NCCL doesn't support it.

**Comment by teng-li** [comment]
In the old THD days, NCCL backend doesn't support barrier as well.  I don't see the difference here @SsnL Basically, all torch.distributed calls are still synchronous if async=False

**Comment by SsnL** [comment]
Oh I see. Then I should add `async=False` to `init_process_group`, right?

**Comment by SsnL** [comment]
It feels that it makes more sense for `init_process_group` to be synchronous by default..

**Comment by teng-li** [comment]
init_process_group is synchronous by default, @SsnL, but we just don't have a barrier support for NCCL backend, that's all

**Comment by teng-li** [comment]
@SsnL  No, only the ops can be async, init_process_group is always synchronous

**Comment by teng-li** [comment]
@SsnL To be clear, Being synchronous and barrier are two completely different things. 

Being synchronous means that the function's job is done (init_process_group function call) once the function exit, vs. returning a future or something 

Barrier means that each rank needs to hit this code point after the barrier call.

I see here you are asking for a barrier call for init_process_group, is that right?  NCCL doesn't have barrier call within and all NCCL calls are async, so it's not super straightforward to get this implemented.

**Comment by soumith** [comment]
@teng-li while NCCL doesn't have a barrier, it's easy to implement a barrier using NCCL right -- you just allreduce 1 byte and CUDA-synchronize

**Comment by teng-li** [comment]
@soumith The reason I have been hesitated about doing this since the beginning (THD NCCL backend) is that every process needs a GPU access. If @SsnL only needs a barrier after init_process_group, I feel it's an overkill since there is no GPU access in "init_process_group", when there is not GPU access "init_process_group". So ideally, for this case, the barrier should happen on the CPU.  Of course I am open to hearing more suggestions and we can go with this easy solution if that unblocks people faster.

**Comment by SsnL** [comment]
>  you are asking for a barrier call for init_process_group

@teng-li Yes exactly. Currently there is no way to correctly log that the ranks have successfully created the process group. IIRC, in THD days, `init_process_group` blocks until so.

>  If @SsnL only needs a barrier after init_process_group, I feel it's an overkill since there is no GPU access in "init_process_group". So ideally, for this case, the barrier should happen on the CPU.

I don't really mind if `barrier` is specific to `init_process_group`. All I want is a way to block all ranks until they have reached a certain point after initialization. In fact, I think, for the general purpose NCCL `barrier`, it makes sense for it to use GPU.

**Comment by teng-li** [comment]
@SsnL See my implementation, there are two scenarios that need to be considered and I think this should be good to go.

**Comment by teng-li** [comment]
This should be good to close
