### ISSUE TITLE
`aot_compile` automatically (and implicitly) turns off dynamic shapes if a non-tensor is passed in.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#135796]
### 🐛 Describe the bug

```
import torch
from triton.testing import do_bench

torch.set_default_device("cuda")

def f(x, y):
    return x.repeat([2])

x = torch.randn(20)
torch._dynamo.mark_dynamic(x, 0)
so_path = torch._export.aot_compile(f, (x, True))
fn = torch._export.aot_load(so_path, "cuda")
out = fn(torch.randn(40), True) 
assert out.shape[0] == 80 # Returns 40(!) instead of 80
```
This is because of this code (https://github.com/pytorch/pytorch/blob/6535f112591810866dfdf9fe722ae80128974517/torch/_inductor/compile_fx.py#L1285), which only converts the input tensor to fake tensors if all inputs are fake (which a non-tensor won't be).

cc: @ezyang @aakhundov @SherlockNoMad 

### Versions

N/A

cc @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @desertfire @chenyang78

**Comment by angelayi** [comment]
Hmm, this doesn't seem to repro on my local checkout of pytorch (commit: 7647c398ff87daf70260854cf0a7f7993b3abc76)

**Comment by Chillee** [comment]
@angelayi What are you running? I updated with a working repro.

**Comment by yushangdi** [comment]
@Chillee Do you still see this error? I cannot reproduce it neither. 

I'm on 5ba61d7fb8870d2ca479b27dcb30d1ae1d2915dc 
Date:   Tue Dec 10 09:29:16

**Comment by yushangdi** [comment]
fwiw, the aot_compile API is deprecated, and the new API should be like below. Both old and new APIs work fine for me.

```
class MyModule(torch.nn.Module):
    def forward(self, x):
        return x.repeat([2])

x = torch.randn(20)
torch._dynamo.mark_dynamic(x, 0)
ep = torch.export.export(MyModule(), (x,))
so_path =  torch._inductor.aoti_compile_and_package(ep)
fn = torch._inductor.aoti_load_package(so_path)
out = fn(torch.randn(40), True) 
assert out.shape[0] == 80 # Returns 40(!) instead of 80
```
