### ISSUE TITLE
dist.all_reduce([tensor]) throws confusing error message

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#13574]
```
TypeError: allreduce(): incompatible function arguments. The following argument types are supported:
1. (self: torch.distributed.ProcessGroup, arg0: List[at::Tensor], arg1: torch.distributed.AllreduceOptions) -> c10d::ProcessGroup::Work
2. (self: torch.distributed.ProcessGroup, tensor: at::Tensor, op: torch.distributed.ReduceOp = ReduceOp.SUM) -> c10d::ProcessGroup::Work
```

It seems internally the input is wrapped in another list, but this error is confusing.

**Comment by SsnL** [comment]
@teng-li No, the problem is that `all_reduce` python code always wraps the input into a list, and then calls the pybind function. So the pybind function sees a list of list of tensors and then throw such error. It is really confusing because users who don't know the implementation details will be very confused since they send in a list of tensors, and the error message says that its type doesn't match a list of tensors.

**Comment by teng-li** [comment]
@SsnL  I understand what you mean, an easier fix I can think about is to add a type check before every collective? Any better thoughts?

**Comment by SsnL** [comment]
@teng-li Maybe simply adding an `isinstance(tensor, torch.Tensor)` in `allreduce` python code?

**Comment by teng-li** [comment]
@SsnL can you review / stamp that PR?

**Comment by SsnL** [comment]
@teng-li Thanks for fixing! Sorry I was asleep then...
