### ISSUE TITLE
ConvNd C implementation doesn't check tensor types

### ISSUE THREAD

**Issue by angelleng** [pytorch/pytorch#1357]
the error only happens in very specific conditions. (change the view of input tensor and use weight converted from numpy array.)
```
import torch
import torch.nn as nn
import numpy as np
from torch.autograd import Variable
filter_size = 5
a = torch.randn(3,3,64,64) 
weights = np.random.rand(25).reshape(5,5)
weights = torch.from_numpy(weights.reshape(1,1,5,5)) 
out1 = nn.functional.conv2d(Variable(a.view(9,1,64,64)), Variable(weights)) 
psi = nn.Conv2d(1,1, filter_size, bias=True) 
psi.weight.data.copy_(weights) 
psi.bias.data.fill_(0)
out2 = psi(Variable(a.view(9,1,64,64))) 
print(out1.mean())
print(out2.mean()) 
``` 
The output of functional conv2d is far off in scale (e12 or so.)

**Comment by szagoruyko** [comment]
this happens because `np.random.rand` generates double precision tensor by default, whereas torch generates single precision. We need to add guards for tensor types in THNN and THCUNN.

**Comment by apaszke** [comment]
It's a problem with `checkTypes` function, that only [checks if the arguments are all on CUDA or CPU, but ignores the requested type](https://github.com/pytorch/pytorch/blob/master/torch/csrc/nn/THNN_generic.inc.h#L32-L54). Should be a simple fix.

**Comment by colesbury** [comment]
Whoops! Yeah it just ignores the "thpp::Type type" parameter

**Comment by angelleng** [comment]
what type is expected here?

**Comment by colesbury** [comment]
a is a FloatTensor but weights is a DoubleTensor.

Change:
`weights = torch.from_numpy(weights.reshape(1,1,5,5))`
to:
`weights = torch.from_numpy(weights.reshape(1,1,5,5)).float()`

**Comment by angelleng** [comment]
cool thanks!
