### ISSUE TITLE
Why not Enable non_blocking h2d copy By Default

### ISSUE THREAD

**Issue by CCCCarpediem** [pytorch/pytorch#135794]
### 🚀 The feature, motivation and pitch

Use tensor.cuda() to place a host tensor to device. But synchronize is always called during aten::copy_ , which  often trigger  host bound issues .  Why not enable asynchronous copy (tensor.cuda(non_blocking=True))by default?  Is there a limit to page lock memory? thanks.

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by awgu** [comment]
Yes, there is a limit to page lock memory. That memory cannot be used for other applications, so if you pin too much memory, then you can freeze your system.

**Comment by kwen2501** [comment]
The definition of `Tensor.cuda()` is that it will return a **copy** of the data in CUDA memory.
Thus, a user may call it like: `y = x.cuda()`.

From the user's perspective, when `x.cuda()` is returned, they may expect that `x` can be modified and they would still get an intended `y`.

If the function is made asynchronous, the above would become false.
