### ISSUE TITLE
xpu: incorrect stats tracking in CachingDeviceAllocator

### ISSUE THREAD

**Issue by dvrogozh** [pytorch/pytorch#135726]
First noted at https://github.com/pytorch/pytorch/pull/135567#issuecomment-2342434911

With:
* https://github.com/pytorch/pytorch/commit/16c3b8f87cfa9cb5acee8104820baa389e7ee2bd
* https://github.com/intel/torch-xpu-ops/commit/12065904d4c3c870059d746eb0fb45a0459f1d6d
* https://github.com/huggingface/accelerate/commit/4b4c036933f7c50fe3a7027b0380fcec53c6975e
* https://github.com/huggingface/safetensors/commit/5db3b92c76ba293a0715b916c16b113c0b3551e9

Running:
```
$ python3 -m pytest --pspec tests/test_utils.py::UtilsTester::test_dynamo --capture=no
````

Fails with this assert:
```
tests/test_utils.py terminate called after throwing an instance of 'c10::Error'
  what():  current >= 0 INTERNAL ASSERT FAILED at "/home/dvrogozh/git/pytorch/pytorch/c10/core/CachingDeviceAllocator.h":19, please report a bug to PyTorch. Negative tracked stat in device allocator (likely logic error).
Exception raised from decrease at /home/dvrogozh/git/pytorch/pytorch/c10/core/CachingDeviceAllocator.h:19 (most recent call first):
```

Assert from here:
https://github.com/pytorch/pytorch/blob/16c3b8f87cfa9cb5acee8104820baa389e7ee2bd/c10/core/CachingDeviceAllocator.h#L17-L21

CC: @gujinghui @EikanWang @fengyuan14 @guangyey @jgong5

cc @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by guangyey** [comment]
@dvrogozh Thank you! Fixed in https://github.com/pytorch/pytorch/pull/135818.
cc @albanD
