### ISSUE TITLE
[torchao]AssertionError: tensor(2.3359, dtype=torch.float16) not greater than 40 : _int8wo_api failed when compiled with dtype=torch.float16, (m, k, n)=(32, 64, 32)

### ISSUE THREAD

**Issue by yanbing-j** [pytorch/pytorch#135831]
### 🐛 Describe the bug

I find there are still errors in torch 2.5.0.dev20240911+cpu and torchao 0.6.0+git3e9746cf.

```
$ python test/integration/test_integration.py -k test_int8_weight_only_quant_subclass_api
.FFsss
======================================================================
FAIL: test_int8_weight_only_quant_subclass_api_1_cpu (__main__.TestSubclass.test_int8_weight_only_quant_subclass_api_1_cpu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yanbingj/miniforge3/envs/optest/lib/python3.11/site-packages/parameterized/parameterized.py", line 620, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanbingj/project/ao/test/integration/test_integration.py", line 821, in test_int8_weight_only_quant_subclass_api
    self._test_lin_weight_subclass_api_impl(
  File "/home/yanbingj/miniforge3/envs/optest/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanbingj/project/ao/test/integration/test_integration.py", line 160, in wrapper
    return test_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanbingj/project/ao/test/integration/test_integration.py", line 804, in _test_lin_weight_subclass_api_impl
    self.assertGreater(
AssertionError: tensor(2.3359, dtype=torch.float16) not greater than 40 : _int8wo_api failed when compiled with dtype=torch.float16, (m, k, n)=(32, 64, 32)

======================================================================
FAIL: test_int8_weight_only_quant_subclass_api_2_cpu (__main__.TestSubclass.test_int8_weight_only_quant_subclass_api_2_cpu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yanbingj/miniforge3/envs/optest/lib/python3.11/site-packages/parameterized/parameterized.py", line 620, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanbingj/project/ao/test/integration/test_integration.py", line 821, in test_int8_weight_only_quant_subclass_api
    self._test_lin_weight_subclass_api_impl(
  File "/home/yanbingj/miniforge3/envs/optest/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanbingj/project/ao/test/integration/test_integration.py", line 160, in wrapper
    return test_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanbingj/project/ao/test/integration/test_integration.py", line 804, in _test_lin_weight_subclass_api_impl
    self.assertGreater(
AssertionError: tensor(2.1562, dtype=torch.bfloat16) not greater than 40 : _int8wo_api failed when compiled with dtype=torch.bfloat16, (m, k, n)=(32, 64, 32)

----------------------------------------------------------------------
Ran 6 tests in 8.452s

FAILED (failures=2, skipped=3)
```

### Versions

$ python collect_env.py
Collecting environment information...
PyTorch version: 2.5.0.dev20240911+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 15.0.0 ([git@github.com](mailto:git@github.com):llvm/llvm-project.git 4ba6a9c9f65bbc8bd06e3652cb20fd4dfc846137)
CMake version: version 3.30.0
Libc version: glibc-2.35

Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.16.0-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Address sizes: 52 bits physical, 57 bits virtual
Byte Order: Little Endian
CPU(s): 224
On-line CPU(s) list: 0-223
Vendor ID: GenuineIntel
Model name: Intel (R) Xeon (R) CPU Max 9480
CPU family: 6
Model: 143
Thread(s) per core: 2
Core(s) per socket: 56
Socket(s): 2
Stepping: 8
CPU max MHz: 3500.0000
CPU min MHz: 800.0000
BogoMIPS: 3800.00
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr avx512_fp16 amx_tile flush_l1d arch_capabilities
Virtualization: VT-x
L1d cache: 5.3 MiB (112 instances)
L1i cache: 3.5 MiB (112 instances)
L2 cache: 224 MiB (112 instances)
L3 cache: 225 MiB (2 instances)
NUMA node(s): 2
NUMA node0 CPU(s): 0-55,112-167
NUMA node1 CPU(s): 56-111,168-223
Vulnerability Itlb multihit: Not affected
Vulnerability L1tf: Not affected
Vulnerability Mds: Not affected
Vulnerability Meltdown: Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1: Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2: Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds: Not affected
Vulnerability Tsx async abort: Not affected

Versions of relevant libraries:
[pip3] bert_pytorch==0.0.1a4
[pip3] flake8==7.1.0
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy==1.11.2
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] onnx==1.16.2
[pip3] optree==0.12.1
[pip3] pytorch-labs-segment-anything-fast==0.2
[pip3] torch==2.5.0.dev20240911+cpu
[pip3] torch_geometric==2.4.0
[pip3] torchao==0.6.0+git3e9746cf
[pip3] torchaudio==2.5.0a0+97ed7b3
[pip3] torchaudio==2.5.0a0+97ed7b3
[pip3] torchmultimodal==0.1.0b0
[pip3] torchvision==0.20.0a0+838ad6c
[pip3] torchvision==0.20.0a0+838ad6c
[pip3] triton-nightly==3.0.0.post20240716052845
[conda] bert-pytorch 0.0.1a4 dev_0
[conda] functorch 1.14.0a0+b71aa0b pypi_0 pypi
[conda] mkl-include 2024.2.0 ha957f24_665 conda-forge
[conda] mkl-static 2024.2.0 ha770c72_665 conda-forge
[conda] numpy 1.26.4 pypi_0 pypi
[conda] optree 0.12.1 pypi_0 pypi
[conda] pytorch-labs-segment-anything-fast 0.2 pypi_0 pypi
[conda] torch 2.5.0.dev20240911+cpu pypi_0 pypi
[conda] torch-geometric 2.4.0 pypi_0 pypi
[conda] torchao 0.6.0+git3e9746cf dev_0
[conda] torchaudio 2.5.0a0+97ed7b3 pypi_0 pypi
[conda] torchmultimodal 0.1.0b0 pypi_0 pypi
[conda] torchvision 0.20.0a0+838ad6c pypi_0 pypi
[conda] triton-nightly 3.0.0.post20240716052845 pypi_0 pypi

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @msaroufim

**Comment by yanbing-j** [comment]
@msaroufim @bdhirsh @jerryzh168 Could you please take a look?
cc @leslie-fang-intel

**Comment by jerryzh168** [comment]
@yanbing-j please open the issue in torchao directly next time: https://github.com/pytorch/ao
