### ISSUE TITLE
No module named _dl found in MAC OSX (with cuda and cudnn)

### ISSUE THREAD

**Issue by navneet1083** [pytorch/pytorch#1358]
Hi,

MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install

After installing pytorch (which went in success), getting following error:
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "torch/__init__.py", line 48, in <module>
    import torch._dl as _dl_flags
ImportError: No module named _dl

Have following libs in miniconda/lib/python2.7/site-packages/torch:

_C.so             _tensor_docs.py   _thnn             _utils.pyc        distributed       lib               serialization.py  storage.pyc       version.py
__init__.py       _tensor_docs.pyc  _torch_docs.py    autograd          functional.py     multiprocessing   serialization.pyc tensor.py         version.pyc
__init__.pyc      _tensor_str.py    _torch_docs.pyc   backends          functional.pyc    nn                sparse            tensor.pyc
_dl.so            _tensor_str.pyc   _utils.py         cuda              legacy            optim             storage.py        utils

**Comment by apaszke** [comment]
You must have imported torch from the repository root. Move to a different directory and try again.

**Comment by ShivaliGoel** [comment]
@apaszke if i move to a different directory, I get an error saying no module named torch. Please help !

**Comment by fmassa** [comment]
@ShivaliGoel it probably means that there was a problem when installing PyTorch. Did it raise any errors during compilation?

**Comment by eliksr** [comment]
@navneet1083 Did you resolve this issue? by moving to which directory?

**Comment by navneet1083** [comment]
@eliksr i moved to one up directory (i.e cd ..).
