### ISSUE TITLE
ProcessGroupGloo RuntimeError: Wait timeout

### ISSUE THREAD

**Issue by forhonourlx** [pytorch/pytorch#13583]
## 🐛 Bug

When I was trying: "dist.init_process_group(rank=0,backend="gloo",init_method='file:///home/simon/Desktop/shared_folder/gloo_shared_file',world_size=2)", "RuntimeError: Wait timeout" came out.
The above path is a shared folder on Ubuntu and samba, it works well.
gloo_shared_file is found and found.

Traceback (most recent call last):
  File "/home/simon/Desktop/dist_rl/dist_rl.py", line 13, in <module>
    dist.init_process_group(rank=0,backend="gloo",init_method='file:///home/simon/Desktop/shared_folder/gloo_shared_file',world_size=2)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 283, in init_process_group
    _default_pg = ProcessGroupGloo(store, rank, world_size)
RuntimeError: Wait timeout

Could somebody give me a hand? Thanks indeed.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by forhonourlx** [comment]
Hi pietern, sorry for the cross post, I will keep in mind after.
Thank you for your reply. 
I tested the above only on one machine.
Do you mean that I must run pytorch.distributed.init_process_group simultaneously(or within limited time)?
For example, time=0, machine=1, run:
python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=0 --master_addr="192.168.1.1" --master_port=1234 OUR_TRAINING_SCRIPT.py
time=0, machine=2, run:
python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=1 --master_addr="192.168.1.1" --master_port=1234 OUR_TRAINING_SCRIPT.py

**Comment by pietern** [comment]
Yes, correct. Specifying `world_size=2` means that it expects 2 processes are started with ranks 0 and 1.

You can either use `torch.distributed.launch` or start the processes manually if you want. This doesn't make a difference for how `init_process_group` works.

**Comment by forhonourlx** [comment]
Thank you indeed, and have a nice day.
Please close this issue.

**Comment by pietern** [comment]
You too :)

**Comment by mosjoker** [comment]
> Hi pietern, sorry for the cross post, I will keep in mind after.
> Thank you for your reply.
> I tested the above only on one machine.
> Do you mean that I must run pytorch.distributed.init_process_group simultaneously(or within limited time)?
> For example, time=0, machine=1, run:
> python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=0 --master_addr="192.168.1.1" --master_port=1234 OUR_TRAINING_SCRIPT.py
> time=0, machine=2, run:
> python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=1 --master_addr="192.168.1.1" --master_port=1234 OUR_TRAINING_SCRIPT.py

Did you make a mistake when running the example? like unhandled error?

**Comment by forhonourlx** [comment]
Since I have not made other machines ready, I set world_size=1, no runtime error is seen.
I compiled v1.0rc1.
