### ISSUE TITLE
Possible UB in TensorImpl constructor

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#13605]
## 🐛 Bug

I was reading TensorImpl and I found this line:
https://github.com/pytorch/pytorch/blob/2398a3255eed2750ebe62f467d40ba5fc0211a33/aten/src/ATen/core/TensorImpl.cpp#L30

Isn't it unspecified in which order the arguments to the functions is evaluated? If so, it is possible that on some systems `storage` is moved before `storage.dtype()` is called, leading to UB.

**Comment by ezyang** [comment]
It's not UB, although for a subtle reason.

`std::move` doesn't actually move anything; it simply makes a variable eligible to be moved from (e.g., so we can call `TensorImpl` with a `Storage&&` argument. Storage doesn't actually get moved out from until we start running the constructors for the field in Tensor, at which point `storage.dtype()` has already been evaluated.

**Comment by apaszke** [comment]
Well unless the delegated constructor takes `decltype(storage)&&` (in which case the move won’t occur before the call) this is a bug. I don’t think that we should depend no this, because someone might remove the rvalue reference in the future and accidentally introduce this bug.

**Comment by apaszke** [comment]
And if you really think that fixing this would be harder, we should at least sprinkle a fair amount of comments to explain why is this safe, and what you should watch out for to keep it that way.

**Comment by mruberry** [comment]
@zou3519 can we close this issue?

**Comment by zou3519** [comment]
I don't know enough about C++ to understand Adam's comment. @ezyang @swolchok what are your thoughts?

**Comment by ezyang** [comment]
The line here doesn't exist anymore.
