### ISSUE TITLE
Tensor `isin` and `unique` missing bfloat16 support and half support on CPU

### ISSUE THREAD

**Issue by Skylion007** [pytorch/pytorch#136090]
### 🚀 The feature, motivation and pitch

Noticed this odd gap in coverage when looking at optests: https://github.com/CaoE/pytorch/blob/a1394be10096b91c0b5528fccf709e6e73078832/torch/testing/_internal/common_methods_invocations.py#L13575C1-L13576C1

Not sure why we don't have kernels build here for bfloat16 (or more types in CPU for that matter).

* This blocked by lack of GPU support for bfloat16 for unique, so I also added that in my fix PR

**Comment by malfet** [comment]
Historically CPUs performance of half precision type ops were really bad, so op coverage was/is limited. But something like `isin` should be available  alongside with equality op
