### ISSUE TITLE
ValueError: Pointer argument (at 3) cannot be accessed from Triton

### ISSUE THREAD

**Issue by foreverpiano** [pytorch/pytorch#136078]
### 🐛 Describe the bug

![图片](https://github.com/user-attachments/assets/1697053c-6eeb-48eb-8999-e1151350fe81)
https://github.com/Dao-AILab/flash-attention/issues/523
when I try to use flexattention
how can I fix this? it happenped randomly. 

### Versions

nightlyversion pytorch

triton=2.1.0
H100

cc @ezyang @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @Chillee @drisspg @yanboliang @BoyuanFeng

**Comment by drisspg** [comment]
I am going to close this for now since it is not very actionable.  Feel free to re-open if you have a minimal/ runnable repro
