### ISSUE TITLE
[ONNX] `dynamo_export` `Unknown call_function target: <function sym_float at 0x7a47c206c860>`

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#136089]
### 🐛 Describe the bug

I am trying to export a model with `torch.onnx.dynamo_export`. How we could better debug this error message?

### Versions

nightly

**Comment by malfet** [comment]
It'll be nice to share some sort of minimal example, though I agree error message should have been better

**Comment by bhack** [comment]
I suppose that we need to:
https://pytorch.org/tutorials/beginner/onnx/onnx_registry_tutorial.html

But it is really not clear  in this case with that "address" what the operator is.

How we could identify it without sharing the whole model?

**Comment by justinchuby** [comment]
Please test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!

**Comment by bhack** [comment]
Using `torch.onnx.export(..., dynamo=True, report=True)` it seems different from `torch.onnx.dynamo_export`.

Now it is failing at `torch.export.export` stage. 

I set  dynamic input for image W and H. 

Is there a way to satisfy the constrain  `//32`?

Cause if not in the export phase we are going to have issues with  inserted guards

```python
Not all values of height = L['image'].size()[2] in the specified range satisfy the generated guard Mod(32 - Mod(L['image'].size()[2], 32), 32) <= 0
```

**Comment by bhack** [comment]
Same model using the export API directly I've tried to constrain  it with a workaround but I don't know if we could use the same wiith onnx. See https://github.com/pytorch/pytorch/issues/136113

**Comment by bhack** [comment]
The strange thing is that the export is going to fail but it seems onnx passes. How is it posibbile?

![immagine](https://github.com/user-attachments/assets/794798a0-2d06-4ea0-a9e2-23946099237b)

**Comment by justinchuby** [comment]
If you look into source (capture_strategies) we will apply some of the recommended constraints for you if you are using dynamic inputs. This seems to be what is happening.

**Comment by justinchuby** [comment]
> Same model using the export API directly I've tried to constrain it with a workaround but I don't know if we could use the same wiith onnx. See #136113

If you can get an ExportedProgram you can supply that to the onnx export api

**Comment by bhack** [comment]
> If you look into source (capture_strategies) we will apply some of the recommended constraints for you if you are using dynamic inputs. This seems to be what is happening. 

Yes but why we have a lot of errors about the guards? Are these just warnings instead?

**Comment by justinchuby** [comment]
Because the second run is the refinement of the first run with constraints. If the model exports you can consider it to be successful

**Comment by bhack** [comment]
So we can we  change `E` to `W` or not?

**Comment by justinchuby** [comment]
> So can we change `E` to `W` or not?

I don't understand this question? You can always validate the exported model and make sure it behaves the same as the pytorch model. Even nicer is the ONNXProgram you get as a return object to torch.onnx.export is now callable with torch tensors if you have onnxruntime installed.

**Comment by bhack** [comment]
I meant from a user perspective point of view seeing all these `E` (error) codes in the guard insertion phase it is quite alarming.

Can we just emit these as warnings?
