### ISSUE TITLE
[inductor] gradient numeric discrepency when fusing Transfromer (Embedding, LayerNorm, Linear)

### ISSUE THREAD

**Issue by weifengpy** [pytorch/pytorch#136121]
### 🐛 Describe the bug

In Transformer, we have 3 basic modules (Embedding, LayerNorm, Linear) (see `EmbNormLinear` below). Graident numerics are different betwen `torch.compile(backend='inductor')` and eager

The numerics are important because I want to compare float8 numerics with high precision numerics. If high precision numerics itself is not accurate, it would be hard to attribute numeric loss

repro: `TORCH_LOGS="output_code" CUBLAS_WORKSPACE_CONFIG=:4096:8 TORCHINDUCTOR_FORCE_DISABLE_CACHES=1 python test_emb_numerics.py`
* bisecting on PT2 stack, backend='aot_eager' have exact numerics. Just backend='inductor' yield different numerics
* bisecting on code, removing 1 of the modules will yield exact numerics
* bisecting on forward/backward, forward has exact numerics, just backward is different. There is no optimizer.step

```
self.tok_embeddings = nn.Embedding(32, 768)
self.norm = nn.LayerNorm(768)
self.output = nn.Linear(768, 32, bias=False)
```

```
import torch
import torch.nn as nn
import copy

class EmbNormLinear(nn.Module):
    def __init__(self):
        super().__init__()
        self.tok_embeddings = nn.Embedding(32, 768)
        self.norm = nn.LayerNorm(768)
        self.output = nn.Linear(768, 32, bias=False)

    def forward(self, tokens):
        _, seq_len = tokens.size()
        h = self.tok_embeddings(tokens)
        h = self.norm(h)
        output = self.output(h).float()
        return output

backend = "inductor" # "aot_eager" works fine
torch.use_deterministic_algorithms(True)

for i in range(100):
    torch.manual_seed(42)
    eager_model = EmbNormLinear().cuda()
    compiled_model = torch.compile(copy.deepcopy(eager_model), backend=backend)

    inp = torch.randint(0, 32, (16, 16), device="cuda")

    eager_model(inp).sum().backward()
    eager_param_sum = torch.stack([p.sum() for p in eager_model.parameters()]).sum() 
    eager_grad_sum = torch.stack([p.grad.sum() for p in eager_model.parameters()]).sum()

    compiled_model(inp).sum().backward()
    compiled_param_sum = torch.stack([p.sum() for p in compiled_model.parameters()]).sum() 
    compiled_grad_sum = torch.stack([p.grad.sum() for p in compiled_model.parameters()]).sum()

    assert torch.equal(eager_param_sum, compiled_param_sum), f"{i=} {eager_param_sum} vs {compiled_param_sum}"
    assert torch.equal(eager_grad_sum, compiled_grad_sum), f"{i=} {eager_grad_sum} vs {compiled_grad_sum}"
    # print(f"{compiled_grad_sum=} {eager_grad_sum=}")
```

### Versions

`python -c "import torch;print(torch.__version__)"`: 2.5.0a0+git94d2471

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by masnesral** [comment]
@weifengpy do you think this deserves to be hi-pri (and discussed at triage review)?

**Comment by eellison** [comment]
torch.compile will not produce bitwise equal numerics. when switched to torch.testing.assert_allclose the repro passes.

The diverence here is very small: `AssertionError: i=0 774.6301879882812 vs 774.6292114257812`
