### ISSUE TITLE
[torch.export] `torch._export.serde.serialize.SerializeError: Serializing <built-in function truediv> is not supported`

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#136113]
### 🐛 Describe the bug

It is not clear where this is coming from.

Exporting with fixed resolution is working. 
But exporting with dynamism like this is going to generate that error:
```python
    image = torch.randn(1, 3, 224, 224).to(device)  # Example image tensor
    extra_image = torch.randn(1, 1, 224, 224).to(device)   # Example mask tensor

    # Define root dimensions that are multiples of 16
    height_base = Dim("height_base", min=14, max=64)  # min 14 * 16 = 224, max 64 * 16 = 1024
    width_base = Dim("width_base", min=14, max=64)

    # Derived dimensions ensuring divisibility by 16
    height = height_base * 16
    width = width_base * 16

    # Use ShapesCollection to define dynamic height and width
    dynamic_shapes = ShapesCollection()
    dynamic_shapes[image] = (Dim.STATIC, Dim.STATIC, height, width)
    dynamic_shapes[extra_image] = (Dim.STATIC, Dim.STATIC, height, width)
    ```

```python
Failed to export the model: Failed serializing node truediv in graph: %truediv : [num_users=193] = call_function[target=operator.truediv](args = (%floordiv_3, %floordiv_3), kwargs = {})
 Original exception Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/torch/_export/serde/serialize.py", line 1314, in serialize_graph
    getattr(self, f"handle_{node.op}")(node)
  File "/opt/conda/lib/python3.11/site-packages/torch/_export/serde/serialize.py", line 549, in handle_call_function
    raise SerializeError(f"Serializing {node.target} is not supported")
torch._export.serde.serialize.SerializeError: Serializing <built-in function truediv> is not supported
```

### Versions

nightly

cc @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by bhack** [comment]
@ezyang I remeber you revamped the promotion of `truediv`. Is it expected to be `floattruediv` at this point?

**Comment by ezyang** [comment]
The small brain fix is add it to:

```
_SYM_INT_OPS = {
    operator.mul,
    operator.add,
    operator.sub,
    operator.floordiv,
    operator.mod,
    operator.pow,
    torch.sym_int,
    torch.sym_float,
    torch.sym_ite,
    torch.sym_max,
    torch.sym_min,
    torch.sym_sqrt,
}
```

The big brain fix is if it's not size-y compute, use https://github.com/pytorch/pytorch/issues/107277 to eliminate it from the graph. But that won't work if the truediv is for sizey stuff.

**Comment by bhack** [comment]
> python
 _SYM_INT_OPS = {
    operator.mul,
    operator.add,
    operator.sub,
    operator.floordiv,
    operator.mod,
    operator.pow,
    torch.sym_int,
    torch.sym_float,
    torch.sym_ite,
    torch.sym_max,
    torch.sym_min,
    torch.sym_sqrt,
}

Hot patching this we have.

```python
 serialize_sym_int
    raise SerializeError(
torch._export.serde.serialize.SerializeError: SymInt should be either symbol or int, got `IntTrueDiv(((2*s4)//(((2*s4 + Mod(14 - Mod(2*s4, 14), 14))//14))), ((2*s4)//(((2*s4 + Mod(14 - Mod(2*s4, 14), 14))//14))))` of type `<class 'torch.SymFloat'>`
```

**Comment by bhack** [comment]
Do you know why the `torch.exprot` code path in onnx dynamo is not going to trigger this issue?
See https://github.com/pytorch/pytorch/issues/136089#issuecomment-2351762082

**Comment by ezyang** [comment]
That looks like progress. So it looks like you've managed to capture everything, but the serialization format doesn't know how to serialize it. Not sure about ONNX, but they have a different serialization format so maybe they added support of all of these things.

**Comment by bhack** [comment]
> So it looks like you've managed to capture everything, but the serialization format doesn't know how to serialize it.

I am not sure about this as the serialization could be just a side effect if we compare to onnx.
- export is working correctly fixed input `Dim` same code
- onnx is falling back with `suggested_fixes` API. We don't have this directly for export (see https://github.com/pytorch/pytorch/issues/136210).
- If I am going to use the same onnx internal fallback approach (`suggested_fixes`) with `export` also the fallback is failing
- I am not be able to let `export` to detect internal implicit constrains like described at https://github.com/pytorch/pytorch/issues/136216. So I needed to use the `Dim` workaround in this ticket that is going to generate the serialization error.

**Comment by pianpwk** [comment]
Hey @bhack, this is a known issue where torch.export doesn't support SymFloat serialization yet (either for runtime asserts, or for example values). We're gonna work on this soon.

**Comment by bhack** [comment]
> Hey @bhack, this is a known issue where torch.export doesn't support SymFloat serialization yet (either for runtime asserts, or for example values). We're gonna work on this soon.

Is this impacting also https://github.com/pytorch/pytorch/issues/136216?

**Comment by bhack** [comment]
Can you look at my draft PR https://github.com/pytorch/pytorch/pull/136364?
I don't know the these internal but at last is was serialized.

**Comment by pianpwk** [comment]
@bhack could you actually send a repro for the serialization errors? For some reason I'm unable to repro on my side when de/serializing.

**Comment by bhack** [comment]
> @bhack could you actually send a repro for the serialization errors? For some reason I'm unable to repro on my side when de/serializing.

The well known pytodch compiler stack millennium issue. 
How are we going to isolate it without sharing the model that I cannot share? 😉

**Comment by bhack** [comment]
Let me know if you can give me any support on the deserializzation issue in the PR

**Comment by bhack** [comment]
> That looks like progress. So it looks like you've managed to capture everything, but the serialization format doesn't know how to serialize it. Not sure about ONNX, but they have a different serialization format so maybe they added support of all of these things.

I think it was a sort false negative in the ONNX case cause it was running at fixed resolution as the new exported API on nightly with  `dynamo=True` seems to not working well with `dynamic_axes` (I can inference the onnx only at fixed resolution).
So now  I've used `dynamic_shapes` arg as in `export`. And now we have a new bug with `onnx`
```python
<class 'torch.onnx._internal.exporter._errors.DispatchError'>: No ONNX function found for <built-in function mod>. Failure message: No decompositions registered for the real-valued input
⬆️
<class 'torch.onnx._internal.exporter._errors.ConversionError'>: Error when translating node %mod_10 : [num_users=1] = call_function[target=operator.mod](args = (150528, %mul_28455), kwargs = {}). See the stack trace for more information.
```

As it is related to onnx  I think  we could open a new thicket  and keep this is connected to my PR for the discussed serialization issue of `export`.

**Comment by avikchaudhuri** [comment]
Can this issue be closed? @bhack

**Comment by bhack** [comment]
There is a connect PR https://github.com/pytorch/pytorch/pull/136364 to close this but still no review.

**Comment by bhack** [comment]
Just to recap we are failing on both `torch.export` and `torch.export.onnx` with dynamo on the same model.

For `torch.exoprt`:
- https://github.com/pytorch/pytorch/pull/136364
- https://github.com/pytorch/pytorch/issues/136628

For `onnx` with dynamo:
- https://github.com/pytorch/pytorch/issues/136524#issuecomment-2372646288

**Comment by bhack** [comment]
I've tried again to export the model with today nightly and the status is the same:
- it still require my PR at https://github.com/pytorch/pytorch/pull/136364
- We still need to solve https://github.com/pytorch/pytorch/issues/136628
