### ISSUE TITLE
GPU Memery leak

### ISSUE THREAD

**Issue by stephane-archer** [pytorch/pytorch#13613]
in 0.4.0 and the nightly version of pytorch

if I do a lot of inference on the **GPU** and I accumulate the result with `torch.cat` on the **CPU** like that:
`y_predlabel = torch.cat((y_predlabel, batch_y_predlabel.cpu()))`

the **GPU** memory increase over time and until I have a `Runtime Error: cuda out of memory` but if I comment the previous line I have no problem.

The tensors on the **GPU** looks to never be free but I do `batch_y_predlabel.cpu()`

**Comment by iammarvelous** [comment]
I also experienced this issue. This happens when conducting massive inference. Below is an example showing what I did. A process that takes 79Mb GPU mem would be created periodically. 
```
model = torchvision.models.resnet50()
model = torch.nn.DataParallel(model)
model.cuda()
model.eval()
result = []
for input in dataloader:
    output = model(input)
    result.append(output.data.cpu().numpy())
```

**Comment by SsnL** [comment]
@iammarvelous What's in your dataloader?

**Comment by iammarvelous** [comment]
@SsnL They are just my testing data. I think you can use `input = torch.randn(32, 3, 224, 224)` instead.

**Comment by SsnL** [comment]
> A process that takes 79Mb GPU mem would be created periodically.
@iammarvelous You said this though so it seems to me that your data loader worker is doing some CUDA stuff. We don't use any multiprocessing other than data loader.

**Comment by stephane-archer** [comment]
i find a solution yesterday

batch_y_predlabel has to be **detach** so the GPU memory can be free.

I don't know if it's normal that a GPU tensor transfer to the CPU in the compute graph still take GPU memory?
for gradient compute I imagine?

**Comment by soumith** [comment]
> for gradient compute I imagine?

Yes.

**Comment by stephane-archer** [comment]
In the training loop that make sense,
but after the training I do inference on the test dataset.
I aggregate all the predicted labels to compute some metrics.

Right now I do **detach after each prediction**.

Is there clever way to do that?

**Comment by Kaixhin** [comment]
If you're only doing inference then you probably want to wrap your testing code with [`with torch.no_grad():`](https://pytorch.org/docs/stable/autograd.html?highlight=no_grad#torch.autograd.no_grad) anyway - no need to detach because no graphs are kept.

**Comment by stephane-archer** [comment]
@Kaixhin If it's after after an epoc is it fine? (a new training step will start just after)
