### ISSUE TITLE
[Build error] libcudnn.so: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by bryankimspeech** [pytorch/pytorch#13615]
## Issue description

When building Caffe2 from source, there are build errors like below. 

[ 96%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/operators/sqrt_op_gpu.cc.o
[ 96%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/operators/stop_gradient_gpu.cc.o
[ 96%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/operators/tensor_protos_db_input_gpu.cc.o
[ 96%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/operators/while_op_gpu.cc.o
[ 96%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/operators/zero_gradient_op_gpu.cc.o
[ 96%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/operators/rnn/recurrent_op_cudnn.cc.o
[ 96%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/operators/rnn/recurrent_network_blob_fetcher_op_gpu.cc.o
[ 97%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/operators/rnn/recurrent_network_executor_gpu.cc.o
[ 97%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/queue/queue_ops_gpu.cc.o
[ 97%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/sgd/iter_op_gpu.cc.o
[ 97%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/sgd/learning_rate_op_gpu.cc.o
[ 97%] Linking CXX shared library ../lib/libcaffe2_gpu.so
**/usr/local/cuda-9.0/lib64/libcudnn.so: error adding symbols: File in wrong format**
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:4756: recipe for target 'lib/libcaffe2_gpu.so' failed
make[2]: *** [lib/libcaffe2_gpu.so] Error 1
CMakeFiles/Makefile2:1567: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Q: Is this a compatibility issue? Would it be suggested to change from CUDA 9.0 / cuDNN 7.1 possibly to lower versions (e.g., CUDA 8.0 / cuDNN 6.0)? Any thoughts and/or suggestions?

## System Info
- PyTorch or Caffe2: Caffe2
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): 
$ mkdir build && cd build
$ cmake ..
$ sudo make -j"$(nproc)" install
- OS: Ubuntu 16.04
- Python version: 2.7 and 3.5
- CUDA/cuDNN version: 9.0.176 / 7.1.4
- GPU models and configuration: GeForce GTX 1080
- GCC version (if compiling from source): 5.4.0
- CMake version: 3.12.0

**Comment by Oldpan** [comment]
@bryankimspeech  Can you tell me how to solve the problem ? thanks~

**Comment by Dinovan-dev** [comment]
Anyone find something ? Got the same problem on my Jetson nano.

Thanks

**Comment by ParmpalGill** [comment]
One Way to install it without cuda is use
cmake .. -DDLIB_USE_CUDA=0 -DUSE_AVX_INSTRUCTIONS=1
