### ISSUE TITLE
Clarify torch.linalg.qr documentation for QR factorization to be well-defined/unique

### ISSUE THREAD

**Issue by redwrasse** [pytorch/pytorch#136120]
### 📚 The doc issue

My linear algebra textbook (Advanced Linear Algebra,Steven Roman, pg. 217) says for QR factorization: any real or complex matrix is amenable to a decomposition A = QR, with Q orthonormal columns and R upper triangular with non-negative real entries in the main diagonal. If A is square, Q is orthogonal/unitary. If A is non-singular, R can be chosen to have positive entries in the main diagonal, and the decomposition is unique. If A is real, Q and R are real.

In particular, two points:
- Any matrix is amenable to a QR factorization
- If A is non-singular, can have a unique decomposition.

The Pytorch docs for (https://pytorch.org/docs/stable/generated/torch.linalg.qr.html) on the other hand says:

'Warning: The elements in the diagonal of R are not necessarily positive. As such, the returned QR decomposition is only unique up to the sign of the diagonal of R. Therefore, different platforms, like NumPy, or inputs on different devices, may produce different valid decompositions.'

'Warning: The QR decomposition is only well-defined if the first k = min(m, n) columns of every matrix in A are linearly independent. If this condition is not met, no error will be thrown, but the QR produced may be incorrect and its autodiff may fail or produce incorrect results.'

### Suggest a potential alternative/fix

On the face of it the textbook definition and Pytorch docs don't appear to square (no pun intended).

It'd be helpful to distinguish in docs what is limitations of the implementation/platform/device-dependent  vs mathematically true for a QR factorization- it's hard to tell from the existing docs and testcases. This makes it doubly hard to understand differentiability. The ideal scenario would seem to be to guarantee (and document) a unique decomposition if A is non-singular.

cc @svekars @brycebortree @tstatler @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano

**Comment by lezcano** [comment]
The documentation defines the function `linalg.qr` as a mathematical function. If you want to implement the function from your textbook on top of it you should be able to do so, but these may be different. I don't think there is any issue here tho.

**Comment by redwrasse** [comment]
Hi @lezcano, thanks for your response. Summarizing my interpretation of the docs- if A is of rank k=min(m,n), this QR implementation gives a decomposition unique up to the sign of the diagonals of R, which may differ across device/platform?

**Comment by lezcano** [comment]
that's correct. If you multiply by the appropriate matrix of 1s and -1s (given by sign(diag(R))) Q and R you can normalise it to the standard QR decomposition. We don't do that internally to avoid incurring unnecessary costs if that normalisation is not needed

**Comment by redwrasse** [comment]
Excellent, thank you!
