### ISSUE TITLE
Corrupt Traces Due to PyTorch Inductor Config Name Control Characters

### ISSUE THREAD

**Issue by mvpatel2000** [pytorch/pytorch#136180]
### 🐛 Describe the bug

I am running the PyTorch profiler in a simple setup. When I export chrome traces, I sometimes cannot load it as I get an invalid character. 
>       "ph": "X", "cat": "python_function", "name": "torch/_inductor/config.py(0): �", "pid": 80168, "tid": 15401563,

### Versions

PyTorch 2.4.1

cc @robieta @chaekit @aaronenyeshi @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by masnesral** [comment]
@mvpatel2000 is that invalid character always in `torch/_inductor/config.py`? Do you have a simple repro?

**Comment by mvpatel2000** [comment]
@masnesral unfortunately i don't have a good repro -- the codebase is private, and I haven't easily been able to generate a minimal repro :( 

it is always for that file -- i have not seen it for anything else

**Comment by ezyang** [comment]
What I would probably suggest is finding the code that is writing this JSON and hack in something to filter out non-ASCII characters. Once you find the right spot feel free to send us a PR for it

**Comment by sraikund16** [comment]
It looks like this is similar to https://github.com/pytorch/pytorch/issues/121219
There is a solution in that thread you may want to try in output_json.cpp in kineto. Thanks!

**Comment by mvpatel2000** [comment]
Closing as this is a duplicate of https://github.com/pytorch/pytorch/issues/121219 which has a far better writeup :) 

Will try to dig into it per suggestion in free time
