### ISSUE TITLE
[ONNX] Export with error unhashable list

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#136131]
Model: basic_gnn_gcn

`Failed to convert the exported program to an ONNX model. [96mThis is step 2/2[0m of exporting the model to ONNX. Next steps:- If there is a missing ONNX function implement it and register it to the registry.- If there is an internal error during ONNX conversion debug the error and summit a PR to PyTorch.- Save the ExportedProgram as a pt2 file and create an error report with `export(... report=True)`. Create an issue in the PyTorch GitHub repository against the [96m*onnx*[0m component. Attach the pt2 model and the error report.## Exception summary<class 'TypeError'>: unhashable type: 'list'<class 'torch.onnx._internal.exporter._errors.GraphConstructionError'>: Error processing Python constants for operator 'pkg.onnxscript.torch_lib::aten_expand'. named_inputs={'self': SymbolicTensor('view_2' type=Tensor(INT64) shape=[u1 + 100001] producer=node_Reshape_98 index=0) 'size': [SymbolicTensor('add_6' type=Tensor(INT64) shape=[] producer=node_Add_43 index=0) 64]} named_attrs={} opset= op_signature=pkg.onnxscript.torch_lib::aten_expand(self: TTensor size: TInt) -> (TTensor) where TTensor=COMPLEX128 | BOOL | INT32 | INT16 | INT8 | INT64 | FLOAT16 | UINT8 | FLOAT | DOUBLE | COMPLEX64 | BFLOAT16 TInt=INT32 | INT64 | INT16 | INT8.<class 'torch.onnx._internal.exporter._errors.GraphConstructionError'>: Error calling function 'aten_expand' with args (SymbolicTensor('view_2' type=Tensor(INT64) shape=[u1 + 100001] producer=node_Reshape_98 index=0) [SymbolicTensor('add_6' type=Tensor(INT64) shape=[] producer=node_Add_43 index=0) 64]) and kwargs {}. The function is defined at '/opt/conda/envs/ptca/lib/python3.11/site-packages/onnxscript/function_libs/torch_lib/ops/core.py:3314'.<class 'torch.onnx._internal.exporter._errors.GraphConstructionError'>: Error when calling function 'OnnxFunction(<function aten_expand at 0x7fb05ca193a0>)' with args '[SymbolicTensor('view_2' type=Tensor(INT64) shape=[u1 + 100001] producer=node_Reshape_98 index=0) [SymbolicTensor('add_6' type=Tensor(INT64) sha...`

**Comment by justinchuby** [comment]
1. Handle [SymbolicTensor('add_6' type=Tensor(INT64) shape=[] producer=node_Add_43 index=0) 64]  properly.

**Comment by Unexp1ainable** [comment]
Did you manage to solve this? I have the exact same problem.

**Comment by justinchuby** [comment]
Please test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!

**Comment by Unexp1ainable** [comment]
Hi, I tested it and with torch-nightly it exports without errors. Thank you.
