### ISSUE TITLE
[inductor] assert_close numerics failed when fusing abs,max,clamp,mul,reciprocal (needed by float8)

### ISSUE THREAD

**Issue by weifengpy** [pytorch/pytorch#136181]
### 🐛 Describe the bug

for float8 workstream, we calculate scale from high precision tensor using following ops: abs/max/clamp/mul/reciprocal. While eager and backend='aot_eager' works fine, the numerics failed with backend=`inductor`. I am using `torch.testing.assert_close`. Absolute and relative difference are significant
* this problem only exists in dtype=bfloat16. But it's critical as we use bfloat16 in TorchTitan and TorchAO
* the numerics are critical as we see more float8 benchmarks from AWS and IBM

```
Expected 104.642333984375 but got 104.5.
Absolute difference: 0.142333984375 (up to 1e-05 allowed)
Relative difference: 0.0013601950468369048 (up to 1.3e-06 allowed)
```

repro command: `TORCH_LOGS="output_code" python test_compile_amax.py`
`test_compile_amax.py` is defined as follows:
```
import torch

def calculate_scale(inp):
    amax = torch.abs(torch.max(inp))
    scale = 448.0 / torch.clamp(amax, min=1e-12)
    scale = scale.to(torch.float32)
    return scale

dtype = torch.bfloat16
torch.manual_seed(0)
inp = torch.randn(16, 16, 768, dtype=dtype, device="cuda")
eager_scale = calculate_scale(inp)
compile_scale = torch.compile(calculate_scale)(inp)
torch.testing.assert_close(eager_scale, compile_scale)
```

output code: `triton_red_fused_max_0` and `triton_per_fused__to_copy_abs_clamp_max_mul_reciprocal_1` 
```
def call(args):
    arg0_1, = args
    args.clear()
    assert_size_stride(arg0_1, (16, 16, 768), (12288, 768, 1))
    with torch.cuda._DeviceGuard(0):
        torch.cuda.set_device(0)
        buf0 = empty_strided_cuda((24, ), (1, ), torch.float32)
        # Topologically Sorted Source Nodes: [max_1], Original ATen: [aten.max]
        stream0 = get_raw_stream(0)
        triton_red_fused_max_0.run(arg0_1, buf0, 24, 8192, grid=grid(24), stream=stream0)
        del arg0_1
        buf2 = empty_strided_cuda((), (), torch.float32)
        # Topologically Sorted Source Nodes: [max_1, amax, clamp, res, scale], Original ATen: [aten.max, aten.abs, aten.clamp, aten.reciprocal, aten.mul, aten._to_copy]
        triton_per_fused__to_copy_abs_clamp_max_mul_reciprocal_1.run(buf0, buf2, 1, 24, grid=grid(1), stream=stream0)
        del buf0
    return (buf2, )
```

### Versions

torch.__version__: 2.5.0a0+git94d2471

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by bdhirsh** [comment]
from a bit of looking around:

(1) i tried comparing with an fp64 baseline ([script](https://www.internalfb.com/phabricator/paste/view/P1593062975)), and compile seems to be more accurate (which is kind of expected)

(2) Running with `TORCHINDUCTOR_FORCE_SAME_PRECISION=1` didn't actually replicate the eager precision though, which seems unexpected (with that flag, we were still getting different results from eager, but closer to fp64 baseline). maybe cc @eellison

**Comment by eellison** [comment]
The typical way we test precision is by comparing against a more precise fp32 baseline. If you compare to that torch.compile is more accurate than eager. We do have a flag `emulate_precision_casts` which will reintroduce the downcasts and upcasts that make the numerics more similar to eager.
```
import torch

def calculate_scale(inp):
    amax = torch.abs(torch.max(inp))
    scale = 448.0 / torch.clamp(amax, min=1e-12)
    scale = scale.to(torch.float32)
    return scale

dtype = torch.bfloat16
torch.manual_seed(0)
inp = torch.randn(16, 16, 768, dtype=dtype, device="cuda")
eager_scale = calculate_scale(inp)
compile_scale = torch.compile(calculate_scale)(inp)
fp32_scale = calculate_scale(inp.to(torch.float))

torch.testing.assert_close(fp32_scale, compile_scale)

print("Max divergence from fp32, compile: ", torch.max(torch.abs(fp32_scale - compile_scale)))
# 0.
print("Max divergence from fp32, eager: ", torch.max(torch.abs(fp32_scale - eager_scale)))
# 0.1423

torch._dynamo.reset()

from torch._inductor import config
config.emulate_precision_casts = True

compile_scale = torch.compile(calculate_scale)(inp)
torch.testing.assert_close(fp32_scale, compile_scale)
# passes
```

**Comment by weifengpy** [comment]
@bdhirsh @eellison thanks for explaining inductor numerics. `config.emulate_precision_casts = True` is particularly useful. I can give it a try in the original code in TorchAO

**Comment by bdhirsh** [comment]
Interestingly that script above failed for me (when setting `config.emulate_precision_casts = True`):
```
(/home/hirsheybar/local/a/pytorch-env) [hirsheybar@devgpu001.lla3 ~/local/a/pytorch (add_keep_graph_binding)]$ python tmp.py
Max divergence from fp32, compile:  tensor(0., device='cuda:0')
Max divergence from fp32, eager:  tensor(0.1423, device='cuda:0')
Traceback (most recent call last):
  File "/home/hirsheybar/local/a/pytorch/tmp.py", line 29, in <module>
    torch.testing.assert_close(fp32_scale, compile_scale)
  File "/home/hirsheybar/local/a/pytorch/torch/testing/_comparison.py", line 1530, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Scalars are not close!

Expected 104.5 but got 104.642333984375.
Absolute difference: 0.142333984375 (up to 1e-05 allowed)
Relative difference: 0.001362047697368421 (up to 1.3e-06 allowed)
```

My commit is ~a week old - I can try again on a newer main commit?

**Comment by bdhirsh** [comment]
(yeah still fails for me on tip-of-trunk)

**Comment by eellison** [comment]
Oops @bdhirsh, yea edited, it should read `torch.testing.assert_close(eager_scale, compile_scale)` at the bottom

**Comment by eellison** [comment]
I'm going to close this. feel free to reopen as you see fit.
