### ISSUE TITLE
[Build error] libnccl.so: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by vladTeplitski** [pytorch/pytorch#13617]
Hi,
Trying to build TORCH_VERSION: 1.0.0, with the following error:

[ 77%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/sgd/iter_op_gpu.cc.o
[ 77%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/queue/queue_ops_gpu.cc.o
[ 77%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/sgd/learning_rate_op_gpu.cc.o
[ 77%] Linking CXX shared library ../lib/libcaffe2_gpu.so
/usr/local/cuda/libnccl.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libcaffe2_gpu.so] Error 1
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-qnnpack caffe2'

The file: /usr/local/cuda/libnccl.so is present.
nccl version: nccl_2.3.5-2

System:
Environment: Conda, python 3.6
CMake version         : 3.9.4
C++ compiler version  : 4.8.5
CUDA version: 9.0
cudnn version: 7.3.1
OS: RHEL 7.5
Arch: ppc64le

**Comment by zou3519** [comment]
How did you install libnccl?

**Comment by soumith** [comment]
it's very likely that you installed x64 libnccl, instead of ppc64 version

**Comment by leriomaggio** [comment]
> it's very likely that you installed x64 libnccl, instead of ppc64 version

I do believe @soumith is right!
I did the very same mistake, accidentally picking ppc64 version instead of x86. 

I would suggest to close this issue and marked as solved 👍
