### ISSUE TITLE
NaN in Flex Attention backward if BlockMask is larger than first run seq_len when return_lse=True and torch compiled

### ISSUE THREAD

**Issue by cora-codes** [pytorch/pytorch#136232]
### 🐛 Describe the bug

We've came across a NaN in the backward pass of Flex Attention. In order to trigger it, you need all of the following:

- BlockMask slightly larger than actual first run's seq_len
- return_lse = True
- Torch compile

```py
import torch
from torch.nn.attention.flex_attention import create_block_mask, flex_attention
torch.set_default_device('cuda')
def causal_mask(b, h, q_idx, kv_idx):
    causal_mask = q_idx >= kv_idx
    return causal_mask
def create_qkv(seq_len):
    q = torch.randn(1, 12, seq_len, 64, requires_grad=True)
    k = torch.randn(1, 12, seq_len, 64, requires_grad=True)
    v = torch.randn(1, 12, seq_len, 64, requires_grad=True)
    return q, k, v
causal_block_mask = create_block_mask(causal_mask, B=None, H=None, Q_LEN=4096, KV_LEN=4096)
def forward(q, k, v, mask):
    out, lse = flex_attention(q, k, v, block_mask=mask, return_lse=True)
    return out * torch.exp(lse)[..., None]
def repro(seq_len, backend):
    print("Repro at seq_len", seq_len)
    compiled = torch.compile(forward, backend=backend)
    for i in range(10):
        q, k, v = create_qkv(seq_len)
        out = compiled(q, k, v, causal_block_mask)
        loss = out.sum()
        loss.backward()
        assert not q.grad.isnan().any(), "Q has NaN"
        assert not k.grad.isnan().any(), "K has NaN"
        assert not v.grad.isnan().any(), "V has NaN"
    print("Done")

for backend in ["inductor", "eager"]:
    print(backend, "4096 then 4096 - 128")
    torch.compiler.reset()
    repro(4096, backend)
    repro(4096 - 128, backend)

    print(backend, "just 4096 - 128")
    torch.compiler.reset()
    try:
        repro(4096 - 128, backend)
    except AssertionError as e:
        print("ERROR", e)
```

```
inductor 4096 then 4096 - 128
Repro at seq_len 4096
Done
Repro at seq_len 3968
Done
inductor just 4096 - 128
Repro at seq_len 3968
ERROR K has NaN
eager 4096 then 4096 - 128
Repro at seq_len 4096
Done
Repro at seq_len 3968
Done
eager just 4096 - 128
Repro at seq_len 3968
Done
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @ydwu4 @bdhirsh @Chillee @drisspg @yanboliang @BoyuanFeng

### Versions

'2.6.0.dev20240916+cu124'

**Comment by masnesral** [comment]
@yanboliang: assigning to you so you can triage appropriately.

**Comment by yanboliang** [comment]
Checked this issue a bit, I think it's a kernel bug. This only happens when ```return_lse=True``` and the number of iteration is larger than 1. I found the offset is larger than Q_LEN under this condition. I'm looking for the reason of the offset index out of bound now.

**Comment by ag1988** [comment]
I'm also getting NaNs with flex attention.

**Comment by Chillee** [comment]
@ag1988 what's your pytorch version?

**Comment by ag1988** [comment]
> @ag1988 what's your pytorch version?

torch.__version__ :  2.5.0.dev20240824+cu124

Also updated my comment to highlight that I am not getting NaNs immediately - I am getting large grads which eventually lead to NaNs. No such issues when I fall back to native sdpa.

**Comment by ag1988** [comment]
@Chillee Apologies for not updating to the latest nighly before commenting - I'll update now and retry.

**Comment by DelinQu** [comment]
Hi, this issue still exist in the latest version of `torch == 2.7.0`
