### ISSUE TITLE
error: "TORCH_EXTENSION_NAME" redefined in test_cpp_extensions

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#13622]
## 🐛 Bug

The latest pull from master commit a7ee632dff135a169031bccc8d04339a6a9bbf10 fails in test_cpp_extensions with 

building 'torch_test_cpp_extension.cpp' extension
creating build/temp.linux-ppc64le-3.6
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/freddie/miniconda/lib/python3.6/site-packages/torch/lib/include -I/home/freddie/miniconda/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/freddie/miniconda/lib/python3.6/site-packages/torch/lib/include/TH -I/home/freddie/miniconda/lib/python3.6/site-packages/torch/lib/include/THC -I/home/freddie/miniconda/include/python3.6m -c extension.cpp -o build/temp.linux-ppc64le-3.6/extension.o -g -Werror -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=cpp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=cuda -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
<command-line>:0:0: error: "TORCH_EXTENSION_NAME" redefined [-Werror]
<command-line>:0:0: note: this is the location of the previous definition
cc1plus: all warnings being treated as errors
error: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "run_test.py", line 420, in <module>
    main()
  File "run_test.py", line 412, in main
    raise RuntimeError(message)
RuntimeError: test_cpp_extensions failed!

## To Reproduce

clone the latest master and build from source

## Expected behavior

should pass all tests

## Environment
 - PyTorch Version (e.g., 1.0):  latest commit from master a7ee632dff135a169031bccc8d04339a6a9bbf10
 - OS (e.g., Linux):  Red Hat 7.4
 - How you installed PyTorch (`conda`, `pip`, source):  source
 - Build command you used (if compiling from source):   .jenkins/pytorch/build.sh
 - Python version:   3.6/3.7
 - CUDA/cuDNN version:   cuda 9.2   cuDNN 7
 - GPU models and configuration:    P100
 - Any other relevant information:

**Comment by avmgithub** [comment]
Looks like this is caused by the change in #13482.  In particular the line https://github.com/pytorch/pytorch/blob/7b9d755d88d708e5ee25f5990e0a24733552f659/test/cpp_extensions/setup.py#L12    brings in the extra  flags :  -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=cuda    .  If I bring it back to   look like       extra_compile_args=['-g']),   it works.

Does this not fail on x86 ?

**Comment by avmgithub** [comment]
@goldsborough Please have a look at this for x86.  Your CI does not look like its running the cpp_extensions test because the docker container does not have ninja.  Here is a log of one of the PR executions :  

https://circleci.com/gh/pytorch/pytorch/192430?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Nov 06 22:18:42 Ninja is not available. Skipping C++ extensions test. Install ninja with 'pip install ninja' or 'conda install ninja'.
Nov 06 22:18:42 Running test_cpp_extensions ... [2018-11-06 22:18:42.199646]
Nov 06 22:18:42 Running test_c10d ... [2018-11-06 22:18:42.202386]

**Comment by goldsborough** [comment]
@avmgithub Thanks for bringing to my attention that the tests aren't running in CircleCI. It looks like we only have coverage on macOS right now (https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-macos-10.13-py3-test1/14585/console), where this error was not raised. I'll fix the CI of course.

As for you issue, I'll try to reproduce it.

**Comment by goldsborough** [comment]
So, https://github.com/pytorch/pytorch/pull/13646 fixes the CI to run C++ extension tests. But you error does not show up anywhere.

**Comment by avmgithub** [comment]
@goldsborough ok?  Are you running it on a system with GPU?  If only on CPU machine, it does not happen.  Only happens when testing on systems with GPU.   Does CircleCI have GPU?     Another question,  what is your ninja version ?

**Comment by avmgithub** [comment]
@goldsborough I got myself an x86 system with GPU and built pytorch from scratch,  looks like it also happens on x86 and fails.   It seems the problem is the line : CXX_FLAGS = [] if sys.platform == 'win32' else ['-g', '-Werror']

Which is being used in both the CppExtension and CUDAExtension in setup.py .   The side effect of this is it adds the extra :  -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=cuda  to the CppExtension build.    And that errors out because TORCH_EXTENSION_NAME is being redifined.

If I do something like: 

ext_modules = [
    CppExtension(
        'torch_test_cpp_extension.cpp', ['extension.cpp'],
        extra_compile_args=[] if sys.platform == 'win32' else ['-g', '-Werror']),
]

that works fine.

**Comment by goldsborough** [comment]
Looks like it's failing in CircleCI too now: https://circleci.com/gh/pytorch/pytorch/194955?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Thanks for the hint about how you fixed it. I should have a fix to master very soon.
