### ISSUE TITLE
Inductor pattern doesn't match on dynamic tensor marked with torch.dynamo.mark_dynamic 

### ISSUE THREAD

**Issue by laithsakka** [pytorch/pytorch#136329]
Question from VLLM.

Hello! I've run into some strange, to me at least, behavior with how dynamic dimensions interact with torch compile and would like to get some clarity as to what's going on and how I can use dynamic dimensions with the inductor pattern matcher. I'm on version 2.4
The code snippet attached here is a very basic example. The naive_dual_mul function slices up the b matrix, runs a gemm with each slice, and then adds those two output matrices together. The naive_dual_mul, dual_mul_pattern, and dual_mm functions are all completely identical.
The key here is that I want the n dimension, or b.shape[1], to be dynamic. I attempted to do this using torch.dynamo.mark_dynamic on the b tensor before calling naive_dul_mul. I also set the same dimension to be dynamic when constructing example inputs in the custom_pass function. The pattern doesn't match and I'm not really sure why.
Any insights you all can provide would be extremely appreciated :slightly_smiling_face:. It's totally possible that I just made some obvious mistake and so even getting some general pattern-doesnt-match-when-it-should debugging tips would be helpful. Thanks!

```
import torch
from torch._inductor.pattern_matcher import PatternMatcherPass, register_replacement, fwd_only

torch.set_default_device("cuda")

@torch.library.custom_op("neuralmagic::dual_mm", mutates_args=())
def dual_mm(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
    n = b.shape[1] // 2
    b_1 = b[(Ellipsis, slice(None, n, None))]
    b_2 = b[(Ellipsis, slice(n, None, None))]

    out_1 = a @ b_1
    out_2 = a @ b_2
    return out_1 + out_2

@dual_mm.register_fake
def dual_mm(a, b): 
    return torch.empty(a.shape[0], b.shape[1] // 2)

def dual_mul_replacement(a, b):
    print("MATCHED")
    return torch.ops.neuralmagic.dual_mm(a, b)

def dual_mul_pattern(a, b):
    n = b.shape[1] // 2
    b_1 = b[(Ellipsis, slice(None, n, None))]
    b_2 = b[(Ellipsis, slice(n, None, None))]

    out_1 = a @ b_1
    out_2 = a @ b_2
    return out_1 + out_2

def custom_pass(graph):
    my_patterns = PatternMatcherPass()
    a = torch.empty((512, 128))
    b = torch.empty((512, 128)).t()
    torch._dynamo.mark_dynamic(b, 1)
    register_replacement(dual_mul_pattern, 
                         dual_mul_replacement, 
                         [a, b], 
                         fwd_only, 
                         [my_patterns])
    my_patterns.apply(graph)
    print(f"AFTER: \n {graph}")
    print(f"CODE: \n {graph.python_code(graph.owning_module).src}")

def test_backend(graph, example_inputs):
    print(f"GRAPH: \n {graph}")
    from torch._inductor import config
    current_config = config.shallow_copy_dict()
    from torch._inductor.compile_fx import compile_fx
    current_config['post_grad_custom_post_pass'] = custom_pass
    return compile_fx(graph, example_inputs, config_patches=current_config)


@torch.compile(backend=test_backend)
def naive_dual_mul(a, b):
    n = b.shape[1] // 2
    b_1 = b[(Ellipsis, slice(None, n, None))]
    b_2 = b[(Ellipsis, slice(n, None, None))]

    out_1 = a @ b_1
    out_2 = a @ b_2
    return out_1 + out_2


m = 512
k = 128
n = 512

a = torch.randn((m, k))
b = torch.randn((n, k)).t()

torch._dynamo.mark_dynamic(b, 1)

c = naive_dual_mul(a, b)
````

cc @ezyang @chauhang @penguinwu @zou3519

**Comment by ezyang** [comment]
please try guidance at https://docs.google.com/document/d/1y5CRfMLdwEoF1nTk9q8qEu1mgMUuUtvhklPKJ2emLU8/edit#heading=h.usdkciy5xgk0

**Comment by SageMoore** [comment]
Hi, Edward! Thanks for posting the doc. I'm the vllm contributor who originally sent this question to Laith. 

I think there might be a misunderstanding here. My question is specifically around pattern matching. I'm having trouble getting the pattern in the example above, which is just a copy paste of the naive implementation, to match. I originally posted this question thinking it was an issue with the symbolic shape, but it actually looks like the problem may be with the slice. 

```import torch
from torch._inductor.pattern_matcher import PatternMatcherPass, register_replacement, fwd_only

torch.set_default_device("cuda")

k = 128
n = 512

@torch.library.custom_op("neuralmagic::half_slice", mutates_args=())
def half_slice(b: torch.Tensor) -> torch.Tensor:
    n = 256
    b_1 = b[(Ellipsis, slice(None, n, None))]
    return b_1.clone()

@half_slice.register_fake
def half_slice(b): 
    return torch.empty(b.shape[0], b.shape[1] // 2)

def slice_replacement(b):
    print("MATCH")
    return torch.ops.neuralmagic.half_slice(b)

def slice_pattern(b):
    n = 256
    b_1 = b[(Ellipsis, slice(None, n, None))]
    return b_1.clone()

b = torch.empty((n, k)).t()

my_patterns = PatternMatcherPass()
register_replacement(slice_pattern, 
                     slice_replacement, 
                     [b], 
                     fwd_only, 
                     [my_patterns])

def custom_pass(graph):
    my_patterns.apply(graph)

def test_backend(graph, example_inputs):
    graph.print_readable()
    from torch._inductor import config
    current_config = config.shallow_copy_dict()
    from torch._inductor.compile_fx import compile_fx
    current_config['post_grad_custom_post_pass'] = custom_pass
    return compile_fx(graph, example_inputs, config_patches=current_config)


@torch.compile(backend=test_backend)
def naive_slice(b):
    n = 256
    b_1 = b[(Ellipsis, slice(None, n, None))]
    return b_1.clone()

b = torch.randn((n, k)).t()
c = naive_slice(b)
```

The above example runs with static shapes and cuts out everything but the slice. FWIW I'm using version 2.4. I found this line in the doc you linked that leads me to believe that slices may not be supported?

"For example, if you an integer that you use to index into a Python list, this is going to force a specialization as PT2 does not support dynamic accesses into Python data structures."

Thanks again for your help. Any insights that you can give would be greatly appreciated :)

**Comment by ezyang** [comment]
Why is there a clone() in your slice pattern?

To debug patterns I would make it print out the FX graph you're matching on, and the "compiled" FX pattern you're matching with.

**Comment by SageMoore** [comment]
The clones are just to make it so that the custom op output is not a modified version of its input. Without them I get the following error from inductor.
```
RuntimeError: Tensors returned from custom ops (1) must not be inputs to the custom op and (2) may not alias any inputs or other returns. Please clone the the offending output tensors (e.g. output.clone()) or refactor your code. Offending op: half_slice (with implementation in <module ‘__main__’ from ‘/home/sage/git/nm-vllm/slice_test.py’>)
```
I’ve run `graph.print_tabular()` on the graph at the beginning of the inductor pass and this is the output.
```
opcode         name     target              args                 kwargs
-------------  -------  ------------------  -------------------  --------
placeholder    arg0_1   arg0_1              ()                   {}
call_function  slice_1  aten.slice.Tensor   (arg0_1, 1, 0, 256)  {}
call_function  clone    aten.clone.default  (slice_1,)           {}
output         output   output              ((clone,),)          {}
```
I do want to reiterate that the pattern and the naive implementation are identical
```
n = 256
b_1 = b[(Ellipsis, slice(None, n, None))]
return b_1.clone()
```
I don’t know how to print the fx representation of the pattern other than to manually wrap it in torch.compile and print the fx graph in a dummy backend pass. This gives the same result for both the pattern and the naive implementation. I’m not seeing any obvious modifications to the graph that would make the pattern not match.

To be clear, we can probably get away with adding a custom op that thinly wraps the slice, so we aren’t necessarily blocked by this, but it would be cool if we could get this pattern working without that :slightly_smiling_face:.

**Comment by ezyang** [comment]
@jansel do you know off the top of your head what's going on here?

**Comment by jansel** [comment]
I haven't seen this one before, though sounds custom op related?  cc @zou3519

**Comment by eellison** [comment]
@SageMoore there are a couple issues: 

1) we are running the pass in `post_grad_custom_post_pass` instead of `post_grad_custom_pre_pass`. Because we are running it after post grad passes have already run, the graph has been changed. If you run with `TORCH_LOGS=post_grad_graphs` you'll see:

```
[DEBUG]:TRACED GRAPH
 ===== AFTER POST GRAD =====
 /home/eellison/pytorch/torch/fx/_lazy_graph_module.py class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: "Sym(s0)", arg1_1: "f32[128, s0][1, 128]cuda:0", arg2_1: "f32[512, 128][128, 1]cuda:0"):
        floordiv: "Sym((s0//2))" = arg0_1 // 2;  arg0_1 = None        
        slice_1: "f32[128, (s0//2)][1, 128]cuda:0" = torch.ops.aten.slice.Tensor(arg1_1, 1, 0, floordiv)        
        mm: "f32[512, (s0//2)][(s0//2), 1]cuda:0" = torch.ops.aten.mm.default(arg2_1, slice_1);  slice_1 = None        
        slice_2: "f32[128, s0 - (s0//2)][1, 128]cuda:0" = torch.ops.aten.slice.Tensor(arg1_1, 1, floordiv, 9223372036854775807);  arg1_1 = floordiv = None        
        addmm_default: "f32[512, s0 - (s0//2)][s0 - (s0//2), 1]cuda:0" = torch.ops.aten.addmm.default(mm, arg2_1, slice_2);  mm = arg2_1 = slice_2 = None
        return (addmm_default,)
````

The add(mm, mm) has been transformed into addmm [from this logic]( https://github.com/pytorch/pytorch/blob/be169f743b43917a8ecad8806ee1b2c4d8131600/torch/_inductor/fx_passes/post_grad.py#L1030-L1052).

We already do a [bit of canonicalization](https://github.com/pytorch/pytorch/blob/be169f743b43917a8ecad8806ee1b2c4d8131600/torch/_inductor/pattern_matcher.py#L1838-L1840) of generated patterns but we do not run the full post grad passes. 


2) You do not need to mark_dynamic inside the registered pattern. If you generate a pattern with static shapes, that should work for dynamic shapes as well. See, [these](https://github.com/pytorch/pytorch/pull/115441) [two](https://github.com/pytorch/pytorch/pull/116158) PRs. Basically, we lift computation of symints to inputs on the graph, and we ignore int inputs when pattern matching. Then, after a pattern matched, we retrace with the correct symints and insert into the graph.

With the [updates](https://gist.github.com/eellison/99814d28f4f8f55b1607eca7e8574eca)

```
diff --git a/custom_pass.py b/custom_pass.py
index 4eee1196871..ecf568fca6f 100644
--- a/custom_pass.py
+++ b/custom_pass.py
@@ -34,7 +34,6 @@ def custom_pass(graph):
     my_patterns = PatternMatcherPass()
     a = torch.empty((512, 128))
     b = torch.empty((512, 128)).t()
-    torch._dynamo.mark_dynamic(b, 1)
     register_replacement(dual_mul_pattern, 
                          dual_mul_replacement, 
                          [a, b], 
@@ -49,7 +48,7 @@ def test_backend(graph, example_inputs):
     from torch._inductor import config
     current_config = config.shallow_copy_dict()
     from torch._inductor.compile_fx import compile_fx
-    current_config['post_grad_custom_post_pass'] = custom_pass
+    current_config['post_grad_custom_pre_pass'] = custom_pass
     return compile_fx(graph, example_inputs, config_patches=current_config)
 ```
 
 You get:
 ```
 MATCHED
AFTER: 
 graph():
    %arg0_1 : [num_users=1] = placeholder[target=arg0_1]
    %arg1_1 : [num_users=1] = placeholder[target=arg1_1]
    %arg2_1 : [num_users=1] = placeholder[target=arg2_1]
    %floordiv : [num_users=0] = call_function[target=operator.floordiv](args = (%arg0_1, 2), kwargs = {})
    %dual_mm_default : [num_users=1] = call_function[target=torch.ops.neuralmagic.dual_mm.default](args = (%arg2_1, %arg1_1), kwargs = {})
    return (dual_mm_default,)
CODE: 
```

**Comment by eellison** [comment]
@SageMoore closing but please reopen if you would like to further discuss.

**Comment by SageMoore** [comment]
Thanks for the insights @eellison! This was extremely informative. Definitely feel free to close the question.
