### ISSUE TITLE
Tensor subclass object's __dict__ is cleared when gc.collect is called

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#136358]
### 🐛 Describe the bug

NOTE - After commenting out `gc.collect` in the repro, everything works (or just disabling the gc). Also, the freed tensor has to be part of reference cycle for this to fail.

```python
import torch

class IdentityFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):

        class Node():
            pass

        a = Node()
        b = Node()
        # Induce a reference cycle
        a.b = b
        b.a = a

        s = torch.zeros(1,)
        s._attrs = {"key": "value"}
        # If the tensor is not part of ref cycle, then it is ok
        a.s = s  # Comment this line and it works fine.
        ctx.save_for_backward(s)
        return x

    @staticmethod
    def backward(ctx, grad_output):
        return grad_output

t = torch.ones(1, device='cpu', requires_grad=True)

y = IdentityFunction.apply(t)

print(y.grad_fn.saved_tensors[0]._attrs)
import gc

print(gc.collect())
print(y.grad_fn.saved_tensors[0])  # This is ok
print(y.grad_fn.saved_tensors[0]._attrs)  # This fails

```

Output
```
{'key': 'value'}
11
tensor([0.])
Traceback (most recent call last):
  File "scratchpad/test.py", line 36, in <module>
    print(y.grad_fn.saved_tensors[0]._attrs)  # This fails
AttributeError: 'Tensor' object has no attribute '_attrs'
```

Maybe related : https://github.com/pytorch/pytorch/issues/47117

cc: @ezyang @albanD (potentially related to PyObject preservation)

### Versions

main 462b727d1e5912949e21814f2b229af45b43b660

cc @ezyang @albanD

**Comment by ezyang** [comment]
This suuuure looks like PyObject preservation 🤔

**Comment by albanD** [comment]
Can you check if you see the same when using `_raw_saved_tensors`? That could also be due to the generation of the saved_tensor from the raw data

**Comment by kshitij12345** [comment]
Thank you very much for looking into this. 

> What Python version are you on? The repro script doesn't repro on 3.10

Even I am unable to repro it. I think I had some incorrect change applied (on updating this repro passes). However, I can still see the error on the larger repro (with more dependencies than just pytorch). I will try to narrow it down and update here.

It would be great to have any pointers if you know the part of code which I should be looking at. Currently, I am looking mostly at this file - https://github.com/pytorch/pytorch/blob/main/torch/csrc/autograd/python_variable.cpp (for tp_dealloc and tp_clear implementations)

> Can you check if you see the same when using _raw_saved_tensors? That could also be due to the generation of the saved_tensor from the raw data

If I am correct, the _raw_saved_tensor are `SavedTensor` instances which don't seem to have any thing on them - https://github.com/pytorch/pytorch/blob/fd182b90a74918d60d598383dcdc4af7c6dc73b7/torch/_C/_autograd.pyi#L87-L88
https://github.com/pytorch/pytorch/blob/fd182b90a74918d60d598383dcdc4af7c6dc73b7/torch/csrc/autograd/init.cpp#L512-L513

Did you mean to check it from the C++ side?

**Comment by albanD** [comment]
> If I am correct, the _raw_saved_tensor are SavedTensor instances which don't seem to have any thing on them -

Yes, I meant checking the identity for it.
Checking things like "{id(o.grad_fn.saved_tensors[0])}" is dangerous because you don't explicit ensure that the object you get the id of (the Tensor here) is kept alive until later. So you might be checking the id of a temporary object here and so it's id's value is going to be re-used.

```
print(id([1]))
print(id([1, 2]))
print(id([3]))
print(id([]))
```
will give you
```
$ python foo.py 
140249843344448
140249843344448
140249843344448
140249843344448
```
Even though each is a different list !


If you do have a hold to this Tensor in your repro, you can use https://mg.pov.lt/objgraph/#quick-start to nicely visualize what owns what at the python level.

**Comment by ezyang** [comment]
tp_dealloc and tp_clear are good. Because it's GC related I'm expecting that the proximal mechanism is that you trigger GC, it clears the dict in tp_clear, and then whoops someone resurrects and then it doesn't die. If your large reproducer isn't cancer to run you should be able to observe this with extra logging.

**Comment by kshitij12345** [comment]
Have updated the PR description with the repro which actually fails. We need the tensor/subclass tensor to be part of a reference cycle for the `__dict__` to be cleared.

<details>

<summary>Updated Repro for convenience</summary>

```python
import torch

class IdentityFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):

        class Node():
            pass

        a = Node()
        b = Node()
        # Induce a reference cycle
        a.b = b
        b.a = a

        s = torch.zeros(1,)
        s._attrs = {"key": "value"}
        # If the tensor is not part of ref cycle, then it is ok
        a.s = s  # Comment this line and it works fine.
        ctx.save_for_backward(s)
        return x

    @staticmethod
    def backward(ctx, grad_output):
        return grad_output

t = torch.ones(1, device='cpu', requires_grad=True)

y = IdentityFunction.apply(t)

print(y.grad_fn.saved_tensors[0]._attrs)
import gc

print(gc.collect())
print(y.grad_fn.saved_tensors[0])  # This is ok
print(y.grad_fn.saved_tensors[0]._attrs)  # This fails

```

</details>

Looking at the code for resurrection, I see that it happens in `tp_dealloc`.

https://github.com/pytorch/pytorch/blob/ef3142d2a03d3cf8576751d6a66788cb56c03cd7/torch/csrc/autograd/python_variable.cpp#L1902-L1904

However, I found this note in Python's [doc ](https://docs.python.org/3.12/extending/newtypes.html#finalization-and-de-allocation)regarding defining your own extension types 

> Note There are limitations to what you can safely do in a deallocator function. First, if your type supports garbage collection (using [tp_traverse](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_traverse) and/or [tp_clear](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_clear)), some of the object’s members can have been cleared or finalized by the time [tp_dealloc](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_dealloc) is called. Second, in [tp_dealloc](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_dealloc), your object is in an unstable state: its reference count is equal to zero. Any call to a non-trivial object or API (as in the example above) might end up calling [tp_dealloc](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_dealloc) again, causing a double free and a crash.
Starting with Python 3.4, it is recommended not to put any complex finalization code in [tp_dealloc](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_dealloc), and instead use the new [tp_finalize](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_finalize) type method.

So, I am wondering if `tp_dealloc` is the correct place to resurrect the PyObject as it might be too late and few members could have been cleared already.

**Comment by albanD** [comment]
Thanks for the repro!
The reason I don't think this is us being unlucky with the gc triggering on this object is because it seems to be consistently failing on all python versions I have from 3.9 to 3.13. And I really don't think gc randomness is that consistent haha

**Comment by albanD** [comment]
Found it, PR inc

**Comment by kit1980** [comment]
Verified with 2.6 release candidate.
