### ISSUE TITLE
Torch installation fails while installing VLLM

### ISSUE THREAD

**Issue by samin-batra** [pytorch/pytorch#136311]
### 🐛 Describe the bug

While installing TGI from source, VLLM needs to be installed. When the CMake command is run, Torch needs to be imported. Torch version 2.3 is needed. While importing, this error is coming:
CMAKE_CUDA_ARCHITECTURES must be non-empty if set.

It's coming at line 67 of CMakeLists.txt which has this code:
`find_package(Torch REQUIRED)
`

Cuda 12.6 is installed on my machine.

### Versions

2.3

cc @malfet @seemethere

**Comment by samin-batra** [comment]
https://github.com/huggingface/text-generation-inference/?tab=readme-ov-file#local-install

This is the guide being followed to build TGI from source.
The CMakeLIsts file is here:
https://github.com/vllm-project/vllm/blob/main/CMakeLists.txt#L70

**Comment by colesbury** [comment]
This doesn't sound like a bug in PyTorch to me. VLLM and TGI are not projects maintained by PyTorch.

We use github issues only for bug reports or feature requests for PyTorch. You can ask in the PyTorch forums (https://discuss.pytorch.org) or in the relevant projects
