### ISSUE TITLE
Accessing dynamo configs is 10x+ slower than accessing a regular global variable

### ISSUE THREAD

**Issue by xmfan** [pytorch/pytorch#136384]
### 🐛 Describe the bug

```python
import torch
import torch._dynamo.config as config

x = 5

def access_global():
    global x
    if x == 5:
        pass

def access_config():
    if torch._dynamo.config.compiled_autograd:
        pass

def access_config2():
    if config.compiled_autograd:
        pass

def access_state():
    if torch._dynamo.compiled_autograd.in_compiled_autograd_region:
        pass

import sys
import timeit
print("local file global:", min(timeit.repeat(access_global)))
print("dynamo config global: ", min(timeit.repeat(access_config)))
print("dynamo config global 2:", min(timeit.repeat(access_config2)))
print("dynamo file global", min(timeit.repeat(access_state)))
```

Measurements in seconds
```
local file global: 0.026871912996284664
dynamo config global:  0.5411160900257528
dynamo config global 2: 0.5001895349705592
dynamo file global 0.04922863305546343
```

### Versions

main

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec

**Comment by ezyang** [comment]
This is not that surprising because the config variable goes through a getter that does... stuff. Why do you need the access fast?

**Comment by xmfan** [comment]
There are some internal tests that benchmark overhead... Tests like 3 training loops should remain within 2000ms, and if you're checking a dynamo config 3 times, that's already 1500ms, and your PR gets reverted

**Comment by ezyang** [comment]
My mental model for Dynamo config is that it should only be consulted in the "slow path" (compilation proper). So maybe if you are needing to check it in the hotpath we need some other mechanism. Is this for compiled autograd enablement or something else?

**Comment by xmfan** [comment]
That sounds reasonable. The PR was https://github.com/pytorch/pytorch/pull/135795 where we tried to check compiled autograd on every autograd call. But there's an alternative in this case

**Comment by ezyang** [comment]
One final thing I'll note: we do have a fast path for critical path config patching, which is used by things like dynamic= argument in torch.compile

```
    def _make_closure_patcher(self, **changes: Dict[str, Any]) -> Any:
        """ 
        A lower-overhead version of patch() for things on the critical path.
                
        Usage:      
                    
            # do this off the critical path
            change_fn = config.make_closure_patcher(foo=True)
                        
            ...

            revert = change_fn()
            try:
              ...
            finally:
                revert()

        """
        config = self._config

        def change() -> Callable[[], None]:
            prior = {k: config[k] for k in changes}
            config.update(changes)

            def revert() -> None:
                config.update(prior)

            return revert

        return change
```
