### ISSUE TITLE
slice+view causes view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by jthakurH** [pytorch/pytorch#136327]
### 🐛 Describe the bug

```
import torch
tensor = torch.randn(23, 20, 34, 15)
tensor = tensor[:,:-3, :-2, ]
tensor = tensor.view(32, 15, 23, 17)
```

issues:
```
tensor = tensor.view(32, 15, 23, 17)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

Please use above repro to check the issue

### Versions

[pip3] torch==2.4.0
[pip3] torchaudio==2.4.0
[pip3] torchdata==0.7.1
[pip3] torchtext==0.18.0
[pip3] torchvision==0.19.0

**Comment by colesbury** [comment]
This is the expected behavior. As the error message says "Use .reshape(...) instead"

`.view()` requires reinterpreting a contiguous slice of memory as a different shape, but once you slice the middle dimensions the memory for the tensor is no longer contiguous.
