### ISSUE TITLE
Compile hipBLASlt to support gfx1100

### ISSUE THREAD

**Issue by letter-v** [pytorch/pytorch#136347]
### 🚀 The feature, motivation and pitch

According to [this post](https://github.com/pytorch/torchtune/discussions/1108#discussioncomment-9851037), it's just a matter of compiling for the gfx1100 architecture and it will work. Supposedly the gfx1100 architecture also exists in the `CMakeLists.txt` file in the upstream sources, so it should be readily supported.

cc @malfet @seemethere @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by naromero77amd** [comment]
@letter-v Could you please elaborate on your request and problem? Is this issue the issue that hipBLASLt is not supported on gfx1100 or are you making a feature request that PyTorch build hipBLASLt when it is not available on the AMD GPU architecture that is specified by `PYTORCH_GPU_ARCH` ?

**Comment by letter-v** [comment]
> @letter-v Could you please elaborate on your request and problem? Is this issue the issue that hipBLASLt is not supported on gfx1100 or are you making a feature request that PyTorch build hipBLASLt when it is not available on the AMD GPU architecture that is specified by `PYTORCH_GPU_ARCH` ?

Is the gfx1100 architecture not supported on hipBLASLt? On the [hipBLASLt repo README](https://github.com/ROCm/hipBLASLt), it lists gfx110x as a required hardware. It's also present in the `CMakeLists.txt` file referenced earlier. Either way, I'm making a feature request that PyTorch be built with support for gfx1100, because as it stands it reverts to hipBLAS when run on a gfx1100 card.
