### ISSUE TITLE
Type Error in ```_maybe_convert_to_dtype``` with Mixed Tensor and Number Sequence

### ISSUE THREAD

**Issue by Samuels-Account** [pytorch/pytorch#136487]
### 🐛 Describe the bug

When using _maybe_convert_to_dtype with a Sequence containing mixed types (e.g., a combination of tensors and numbers), the function raises a ValueError, although this case should either be handled or the error message should be more descriptive.

```
import torch
import torch._prims_common as utils

# Sample tensor and number mixed in a sequence
mixed_input = [torch.tensor([1, 2, 3]), 5]

# Function call that raises an error
# Expect this to fail due to mixed input types
result = _maybe_convert_to_dtype(mixed_input, torch.float32)
```

The error message that occurs when running the code:

`ValueError: Received type <class 'int'> that is neither a tensor or a number!`

The function should handle sequences containing both tensors and numbers, or the error message should be clearer about unsupported mixed types. Ideally, it would either process both or explicitly disallow mixed types.

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
python collect_env.py

cc @svekars @brycebortree @sekyondaMeta

**Comment by soulitzer** [comment]
Making the error better for now sounds good, happy to accept a PR
