### ISSUE TITLE
[Flex attention] RuntimeError with vmap when using torch.compile in create_mask

### ISSUE THREAD

**Issue by kebijuelun** [pytorch/pytorch#136427]
### 🐛 Describe the bug

**Issue Description**:  
I encountered a `RuntimeError` related to `vmap` when using `torch.compile` in a custom document causal attention mask function. The error occurs when calling `create_mask` with `_compile=True`. If I remove `_compile=True`, the code runs without issue.

**Error message**:
```
RuntimeError: vmap: It looks like you're calling .item() on a Tensor. We don't support vmap over calling .item() on a Tensor, please try to rewrite what you're doing with other operations. If error is occurring somewhere inside PyTorch internals, please file a bug report.
```

**Minimal reproducible code**:
```python
import torch
from typing import List, Union
from torch import Tensor
from torch.nn.attention.flex_attention import create_mask

def _offsets_to_doc_ids_tensor(offsets):
    device = offsets.device
    counts = offsets[1:] - offsets[:-1]
    return torch.repeat_interleave(
        torch.arange(len(counts), device=device, dtype=torch.int32), counts
    )

def length_to_offsets(lengths: List[int], device: Union[str, torch.device]) -> Tensor:
    offsets = [0]
    offsets.extend(lengths)
    offsets = torch.tensor(offsets, device=device, dtype=torch.int32)
    offsets = torch.cumsum(offsets, dim=-1)
    return offsets

def generate_doc_mask_mod(offsets: Tensor):
    document_id = _offsets_to_doc_ids_tensor(offsets)
    def doc_mask_mod(b, h, q_idx, kv_idx):
        return document_id[q_idx] == document_id[kv_idx]
    return doc_mask_mod

def main(device: str = "cpu"):
    import random
    random.seed(0)

    def generate_random_lengths(total_length, num_documents):
        lengths = [1] * num_documents
        remaining_length = total_length - num_documents
        for _ in range(remaining_length):
            index = random.randint(0, num_documents - 1)
            lengths[index] += 1
        return lengths

    max_seq_len, doc_count = 128, 4
    B, H, SEQ_LEN, HEAD_DIM = 1, 1, max_seq_len, 8

    lengths = generate_random_lengths(max_seq_len, doc_count)
    offsets = length_to_offsets(lengths, device)

    def make_tensor():
        return torch.ones(B, H, SEQ_LEN, HEAD_DIM, device=device)

    query, key = make_tensor(), make_tensor()
    document_causal_mask = generate_doc_mask_mod(offsets)

    # Error occurs when `_compile=True` is set
    mask = create_mask(document_causal_mask, 1, 1, SEQ_LEN, SEQ_LEN, device=query.device, _compile=True)

main()
```

**Workaround**:  
Removing `_compile=True` in the `create_mask` function avoids the error. However, the issue seems related to the interaction between `torch.compile` and the `vmap` functionality when using `create_mask`.

**Expected behavior**:  
The code should run with `torch.compile` enabled without triggering the `vmap` error.

### Versions

**PyTorch version**: 2.5.0.dev20240907+cu12

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] intel-extension-for-pytorch==2.2.0
[pip3] msgpack-numpy==0.4.8
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] open_clip_torch==2.26.1
[pip3] pytorch-triton==3.0.0+757b6a61e7
[pip3] pytorchvideo==0.1.5
[pip3] torch==2.5.0.dev20240907+cu121
[pip3] torchaudio==2.5.0.dev20240907+cu121
[pip3] torchvision==0.20.0.dev20240907+cu121
[conda] intel-extension-for-pytorch 2.2.0                    pypi_0    pypi
[conda] msgpack-numpy             0.4.8                    pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] open-clip-torch           2.26.1                   pypi_0    pypi
[conda] pytorch-triton            3.0.0+757b6a61e7          pypi_0    pypi
[conda] torch                     2.5.0.dev20240907+cu121          pypi_0    pypi
[conda] torchaudio                2.5.0.dev20240907+cu121          pypi_0    pypi
[conda] torchvision               0.20.0.dev20240907+cu121          pypi_0    pypi

cc @zou3519 @ezyang @chauhang @penguinwu @Chillee @samdow @kshitij12345 @ydwu4 @bdhirsh @drisspg @yanboliang @BoyuanFeng

**Comment by yanboliang** [comment]
This is because we have a different handling for pattern like ```A[q_idx]``` where ```A``` is a tensor and ```q_idx``` is a scalar tensor, however, this handling is implemented by ```__torch_function__``` which is not supported by compile mode at that moment. @mlazos is working on supporting ```__torch_function__``` mode under compile. We can remove this constraint when it's ready.

**Comment by Chillee** [comment]
This works now. Although, to be clear, to create the block mask for use with FlexAttention you should call `create_block_mask`
