### ISSUE TITLE
New test added inductor/test_memory not called correctly, breaks linux-aarch64 ciflow

### ISSUE THREAD

**Issue by robert-hardwick** [pytorch/pytorch#136464]
### 🐛 Describe the bug

New test added in #134874 is not being called correctly which results in 

`ERROR: file or directory not found: inductor/test_memory`

See https://github.com/pytorch/pytorch/actions/runs/10993222179/job/30523088135 for full stacktrace.

The test should be added before `--shard` along with other tests.

Should be a quick fix for someone.

@xuanzhang816 @yf225

### Versions

Seen on viable/strict branch.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @snadampal @milpuz01

**Comment by xuanzhang816** [comment]
Oops. Sorry about this. Fixing it now

**Comment by malfet** [comment]
Once again, it begs to run aarch64 CI at least as periodic, rather than opt in
