### ISSUE TITLE
Inductor handling of large (13K+) nodes graph resulted in nccl timeout (10mins)

### ISSUE THREAD

**Issue by IvanKobzarev** [pytorch/pytorch#136447]
### 🚀 The feature, motivation and pitch

Originally coming from internal Intermediate Logging team.

Users have added custom logging ops after each tensor operation, that signficantly increased the size of the graph and inductor compilation processing increase resulted in nccl timeouts (10 minutes).

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by ezyang** [comment]
When you post these please xref with the relevant internal post

**Comment by eellison** [comment]
I'm looking into slow perf of fuse_nodes, that may help here. It might also be possible to speed this up with fewer logging nodes, potentially variadic operators

**Comment by eellison** [comment]
The large graph was filled with extern, unfusable operators. This pr should help: https://github.com/pytorch/pytorch/pull/136682. I'm closing, also because there is no attached repro for it. Can reinvestigate as it comes up.
