### ISSUE TITLE
Nightly aarch64 cuda builds are failing since 09.19.2024

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#136432]
### 🐛 Describe the bug

This is a failure: https://github.com/pytorch/pytorch/actions/runs/10936493689/job/30360266788

```
/pytorch/build/aten/src/ATen/native/cpu/FlashAttentionKernel.cpp.SVE256.cpp
during RTL pass: expand
In file included from /pytorch/build/aten/src/ATen/native/cpu/FlashAttentionKernel.cpp.SVE256.cpp:1:
/pytorch/aten/src/ATen/native/cpu/FlashAttentionKernel.cpp: In lambda function:
/pytorch/aten/src/ATen/native/cpu/FlashAttentionKernel.cpp:555:57: internal compiler error: in emit_move_insn, at expr.c:3821
  555 |   at::parallel_for(0, batchSize * num_head * qSlice, 1, [&](int64_t begin, int64_t end) {
      |                                                         ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/ccKlkazo.out file, please attach this to your bugreport.

```

Seems to be related to: [Extending the Pytorch vec backend for SVE (ARM)](https://github.com/pytorch/pytorch/pull/119571) 
Which landed on 09.18.2024

### Versions

2.6.0

cc @seemethere @malfet @osalpekar @snadampal @milpuz01

**Comment by abhishek-iitmadras** [comment]
Hi @malfet 

the exact similar issue occurred during the development of of https://github.com/pytorch/pytorch/pull/119571, but it was with the CPU Linux build.

I was able to resolve that issue with PR [#132434](https://github.com/pytorch/pytorch/pull/132434), and 
it might provide useful insights for debugging this CUDA-related build issue.

**Comment by malfet** [comment]
@abhishek-iitmadras thank you for the pointer. Though, to be frank, if SVE causes so many internal compiler errors I would just disable it for certain compiler versions...

**Comment by abhishek-iitmadras** [comment]
> @abhishek-iitmadras thank you for the pointer. Though, to be frank, if SVE causes so many internal compiler errors I would just disable it for certain compiler versions...

Hi @malfet 

In the PR https://github.com/pytorch/pytorch/pull/132434

I added the the following check :
`#if __GNUC__ == 11 && __GNUC_MINOR__ >= 4 && defined(__ARM_FEATURE_SVE)`

So this fix work with GNU compiler >= 11.4

And this issue with cude build has used following compiler :
-- The CXX compiler identification is GNU 11.2.1
-- The C compiler identification is GNU 11.2.1

I am not sure, but it might fix if we are adjusting the Preprocessor Condition either to 
`#if __GNUC__ == 11 && defined(__ARM_FEATURE_SVE)`

OR

`#if __GNUC__ == 11 && defined(__aarch64__)`

Correct me if I am wrong.

**Comment by malfet** [comment]
Thank for all the tips @abhishek-iitmadras , I'm trying to get runner very similar to the one used during the nightly builds in order not to submit tentative fixes, but applying the workarounds for all gcc-11 builds make sense. I wonder if you are aware of upstream gcc issue

**Comment by maajidkhann** [comment]
> Thank for all the tips @abhishek-iitmadras , I'm trying to get runner very similar to the one used during the nightly builds in order not to submit tentative fixes, but applying the workarounds for all gcc-11 builds make sense. I wonder if you are aware of upstream gcc issue to reference in the PR

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95528

The issue seemed to exist with gcc 11 and also with gcc 10.

I can confirm that this bug wont happen with gcc 12 and clang compiler.

**Comment by malfet** [comment]
Sounds great, I validated that extending workarounds to entire GCC-11 fixes the problem, will create PR in a few

**Comment by malfet** [comment]
@atalman , @tinglvv any reason why CPU builds are using GCC-9 and CUDA ones are on GCC-11? Would it be possible to move both to GCC-12?
