### ISSUE TITLE
[Pytorch]Speeding up inference?

### ISSUE THREAD

**Issue by zwx8981** [pytorch/pytorch#13658]
Hi, as we know, we only need to calculate forward in inference process, hence it is expected that the computation complexity in inference should be much lower than that in training. However, it seems that in Pytorch there is no obvious difference between training and inference in terms of computation complexity (running time). I have already executed the inference under the context manager 'with torch.no_grad()：'. Is there any possible way to speed-up inference in Pytorch?

**Comment by SsnL** [comment]
> hence it is expected that the computation complexity in inference should be much lower than that in training.

This is not true. Things like #13470 will allow this in some functions, but generally, for most ops, the values needed to compute backward are also naturally computed in forward. So generally, needing to do backprop or not doesn't affect speed, but memory usage.
