### ISSUE TITLE
[ONNX] Support `operator.mod`

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#136524]
### 🐛 Describe the bug

Debugging `export` vs `dynamo=true` ONNX export It seems that the model export stage is going to work  but then the onnx graph translation on is failing. 

More details at https://github.com/pytorch/pytorch/issues/136113#issuecomment-2369811687

### Versions

nightly

**Comment by justinchuby** [comment]
You can register the op (`operator::mod`) here: https://github.com/microsoft/onnxscript/blob/99ae64e9befd77706e62f547b4eeb1d395496668/onnxscript/function_libs/torch_lib/ops/core.py#L7076

**Comment by bhack** [comment]
Do you mean `_operator::mod` ?

**Comment by justinchuby** [comment]
ah yes that's right

**Comment by bhack** [comment]
Ok now is eq ` No ONNX function found for <built-in function eq>. Failure message: No decompositions registered for the real-valued input`

**Comment by bhack** [comment]
Now is `sym_not`

```
<class 'torch.onnx._internal.exporter._errors.DispatchError'>: No ONNX function found for <function sym_not at 0x78511359e520>. Failure message: No decompositions registered for the real-valued input
⬆️
<class 'torch.onnx._internal.exporter._errors.ConversionError'>: Error when translating node %sym_not_3 : [num_users=0] = call_function[target=torch.sym_not](args = (%eq_21087,), kwargs = {}). See the stack trace for more information.
```

**Comment by bhack** [comment]
I've already added eq and mod ops at https://github.com/microsoft/onnxscript/pull/1879

What we need to do for `sym_not`?

**Comment by justinchuby** [comment]
`torch.sym_not` does not belong to a namespace so that is a little tricky. We have some hacks possible but I need to think more carefully.

**Comment by bhack** [comment]
Ok let me know,  If you want you can change the issue title.

**Comment by justinchuby** [comment]
Tracked at https://github.com/pytorch/pytorch/issues/136572

**Comment by bhack** [comment]
OK as the onnx conversion it is fail fast we don't know what is behind the corner so we could keep this a meta ticket up until the conversion is full covered.

P.s. Also an extra note. the conversion stage is super slow probably cause it is single core and we need to wait a lot of time just to re-test what is missing the next round.

**Comment by justinchuby** [comment]
You may save the exported program to a file. Every time you export again, load the exported program first and send that directly to the onnx export api. This is make it much faster.

**Comment by justinchuby** [comment]
Additionally, I would set `report=True`. In the generated report you will find a full list of unimplemented ops.

**Comment by bhack** [comment]
It is not the export so much  it is the coversion stange `[torch.onnx] Translate the graph into ONNX`

Also if it was the export we cannot serialize with the current code cause it is the same model as the `export` at https://github.com/pytorch/pytorch/issues/136113

**Comment by bhack** [comment]
> Additionally, I would set report=True. In the generated report you will find a full list of unimplemented ops.

I will try to see this later but are you sure that this is really going to workaround the fail fast?

**Comment by justinchuby** [comment]
Yes. There is an additional analysis step to gather all ops

**Comment by bhack** [comment]
So in the  report markdown
- `aten.upsample_linear1d.vec`:     No decompositions registered for the real-valued input. Example node: `%upsample_linear1d`
- ` Failed to match overload `OnnxFunction(<function aten_mul at 0x7a1a77123380>)`: Parameter type not compatible with argument: param=`other: TReal`, assigned_types=`{'TReal': Tensor(INT64)}`, arg=`FLOAT`
-  Failed to match overload `OnnxFunction(<function aten_mul_bool at 0x7a1a77123420>)`: Parameter type not compatible with argument: param=`self: T_self`, assigned_types=`{}`, arg=`INT64
-`aten.linear.default`:     No decompositions registered for the real-valued input.`
- `aten.cudnn_batch_norm.default`:     No decompositions registered for the real-valued input.`
- `aten._assert_scalar.default`:     No decompositions registered for the real-valued input.`
- `sym_not`
- `sym_float`

**Comment by justinchuby** [comment]
Thanks. The only ops needed are `aten.upsample_linear1d.vec`, `sym_not` and `sym_float`. The rest is handled by torch decomp.

**Comment by bhack** [comment]
Do we need new issues?

**Comment by justinchuby** [comment]
No. We are able to track them. Thanks

**Comment by justinchuby** [comment]
You are also welcomed to contribute the `aten.upsample_linear1d.vec` op. Most likely a copy-paste and slight modification of 

https://github.com/microsoft/onnxscript/blob/500ed627194eece692818e8dded9007021562ab4/onnxscript/function_libs/torch_lib/ops/nn.py#L2482

**Comment by justinchuby** [comment]
Registering `aten::upsample_linear1d.vec` to this function should work:

https://github.com/microsoft/onnxscript/blob/500ed627194eece692818e8dded9007021562ab4/onnxscript/function_libs/torch_lib/ops/nn.py#L2482-L2483

**Comment by bhack** [comment]
> Registering `aten::upsample_linear1d.vec` to this function should work:
> 
> https://github.com/microsoft/onnxscript/blob/500ed627194eece692818e8dded9007021562ab4/onnxscript/function_libs/torch_lib/ops/nn.py#L2482-L2483

After that at  https://github.com/microsoft/onnxscript/pull/1881 I have
```python
 aten/src/ATen/RegisterCompositeImplicitAutograd.cpp:5567: SymIntArrayRef expected to contain only concrete integers

While executing %upsample_linear1d : [num_users=1] = call_function[target=torch.ops.aten.upsample_linear1d.vec](args = (%permute_8, [%add_45211], False, None), kwargs = {})
```

**Comment by justinchuby** [comment]
In that case you may revert `upsample_linear1d.vec`. It should be decomposed by pytorch already. for the sym methods you can hack https://github.com/pytorch/pytorch/blob/1cb265fafae115cc8acec28205e6244179a6b9c1/torch/onnx/_internal/exporter/_registration.py#L224 to return the corresponding onnx ops for them.

**Comment by bhack** [comment]
> For the sym methods you can hack

I prefer to wait for what we choose at #136113 cause I cannot maintain an hotpatched custom version of pytorch. If there is an official solution I could eventually try to make a PR.

**Comment by justinchuby** [comment]
Closing for now. sym ops support tracked by #136572.
