### ISSUE TITLE
[inductor][cpu]jx_nest_base fp32 inductor_max_autotune accuracy failure in 2024_09_23 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#136639]
### 🐛 Describe the bug

<p>fp32 dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>jx_nest_base</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>jx_nest_base, fail_accuracy</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>jx_nest_base</td>
      <td>single</td>
      <td>X</td>
      <td>√</td>
      <td>jx_nest_base, fail_accuracy</td>
    </tr>
  </tbody>

</table>

<p>fp32 static shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>reason(reference only)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>jx_nest_base</td>
      <td>multiple</td>
      <td>X</td>
      <td>√</td>
      <td>jx_nest_base, fail_accuracy</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>jx_nest_base</td>
      <td>single</td>
      <td>X</td>
      <td>√</td>
      <td>jx_nest_base, fail_accuracy</td>
    </tr>
  </tbody>

</table>

```
E0924 09:34:51.975206 75424 torch/_dynamo/utils.py:1837] RMSE (res-fp64): 0.11059, (ref-fp64): 0.00000 and shape=torch.Size([8, 1000]). res.dtype: torch.float32, multiplier: 2.000000, tol: 0.001000, use_larger_multiplier_for_smaller_tensor: 0
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
fail_accuracy
```

</table>

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>23512dbe</td>
      <td>main</td>
      <td>23512dbe</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>c140fa1426603322a5a69ef91300f13489db5970</td>
      <td>main</td>
      <td>2553278bae5993bd94bae4f04bf4586fb3f30d57</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.5.0a0+97ed7b3</td>
      <td>main</td>
      <td>2.4.0a0+b3f6f51</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob//weizhuoz/enable_max_autotune_for_guilty/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single inference accuracy timm_models jx_nest_base float32 first static default 0 inductor_max_autotune
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/6c5669903f47cffa0f1ac82adab08bb0d5d4be07
[timm_models-jx_nest_base-inference-float32-static-default-single-accuracy-crash_guilty_commit.log](https://github.com/user-attachments/files/17134446/timm_models-jx_nest_base-inference-float32-static-default-single-accuracy-crash_guilty_commit.log)
cc @WeizhuoZhang-intel @chuanqi129 @chunyu

**Comment by leslie-fang-intel** [comment]
cc @chunyuan-w could you help to take a look of this guilty commit?

**Comment by chunyuan-w** [comment]
Hi @zxd1997066 I checked in the 2024_09_30 report, for `jx_nest_base`, the max_autotune accuracy for `jx_nest_base` pass for FP32 single and multiple thread, both static and dynamic shape. Could you help double confirm and close this issue if that's the case?

**Comment by zxd1997066** [comment]
yes, the issue is fixed in 2024_09_30 report.
