### ISSUE TITLE
torch.nn.utils.clip_grad_norm_ super slow with PyTorch distributed

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#13666]
When I run my code with PyTorch distributed on 8 GPUs, adding `torch.nn.utils.clip_grad_norm_(model.parameters(), clip)` before the optimizer step makes my code about 3 times slower, while I observe no difference with 1 GPU.

Any ideas why?

**Comment by mfuntowicz** [comment]
I observe the same behaviour too (on 4xV100 3s/it compared to just one (1s/it)).

**Comment by zou3519** [comment]
cc @nairbv

**Comment by fmassa** [comment]
I'd start by seeing how much we gain [by removing this sync point](https://github.com/pytorch/pytorch/blob/master/torch/nn/utils/clip_grad.py#L33) before we start considering implementing a custom kernel for this.

**Comment by mfuntowicz** [comment]
Hi @nairbv, 

Thanks for having a look. 

I'm using a slightly modified version of the DenseNet on machines with 4xV100 interconnected through NCCL but without InfiniteBand. Also, I compile my pytorch environment especialy for those machines running on the cluster.

I'll try to have a closer look tomorrow, and I'll follow up on this thread, hopefully with some more hints.
Morgan

**Comment by mfuntowicz** [comment]
Hi @nairbv, 

I was not able to reproduce on the latest build 1.0.0, so I would say that for me, it's fine to close.
I let some other guys take the appropriate actions :).

Thanks for having a look,
Morgan
