### ISSUE TITLE
`input` parameter of `index_select()` with a 0D tensor works

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#136636]
### 🐛 Describe the bug

[The doc](https://pytorch.org/docs/stable/generated/torch.index_select.html) of `index_select()` says that `index` parameter is fro a 1D tensor as shown below:

> index (IntTensor or LongTensor) – the 1-D tensor containing the indices to index

And, the error message caused by a 2D tensor for `input` parameter also says that `input` parameter is for a 1D tensor as shown below:

```python
import torch

my_tensor = torch.tensor([8, -3, 0, 1, 5, -2, -1, 4])
                                         # ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓
torch.index_select(input=my_tensor, dim=0, index=torch.tensor([[0, 2, 4]])) # Error
```

> IndexError: index_select(): Index is supposed to be a vector

But `input` parameter with a 0D tensor works as shown below:

```python
import torch

my_tensor = torch.tensor([8, -3, 0, 1, 5, -2, -1, 4])
                                         # ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓
torch.index_select(input=my_tensor, dim=0, index=torch.tensor(4))
# tensor([5])
```

### Versions

```python
import torch

torch.__version__ # '2.3.0'
```

cc @svekars @brycebortree @sekyondaMeta @albanD

**Comment by lezcano** [comment]
This is expected as the 0-D tensor broadcasts
