### ISSUE TITLE
Discrepancy between scaled_dot_product_attention and flex_attention outputs

### ISSUE THREAD

**Issue by notnotsamuel** [pytorch/pytorch#136651]
## Description 🐛
I've noticed a discrepancy between the outputs of `nn.functional.scaled_dot_product_attention` and `torch.nn.attention.flex_attention.flex_attention` when used in equivalent contexts. While the shapes are consistent, there is a non-zero mean absolute difference between the outputs.

## Code to Reproduce
```python
from torch.nn.attention.flex_attention import flex_attention
import torch.nn.functional as F
import torch
import torch.nn as nn
import math
torch.manual_seed(42)

class MHAPyTorchScaledDotProduct(nn.Module):
    def __init__(self, d_in, d_out, num_heads, dropout=0.0, qkv_bias=False):
        super().__init__()
        assert d_out % num_heads == 0, "embed_dim is indivisible by num_heads"
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads
        self.d_out = d_out
        self.qkv = nn.Linear(d_in, 3 * d_out, bias=qkv_bias)
        self.proj = nn.Linear(d_out, d_out)
        self.dropout = dropout

    def forward(self, x):
        batch_size, num_tokens, embed_dim = x.shape
        qkv = self.qkv(x)
        qkv = qkv.view(batch_size, num_tokens, 3, self.num_heads, self.head_dim)
        qkv = qkv.permute(2, 0, 3, 1, 4)
        queries, keys, values = qkv
        use_dropout = 0. if not self.training else self.dropout
        context_vec = nn.functional.scaled_dot_product_attention(
            queries, keys, values, attn_mask=None, dropout_p=use_dropout, is_causal=False, scale= 1 / math.sqrt(self.head_dim))
        context_vec = context_vec.transpose(1, 2).contiguous().view(batch_size, num_tokens, self.d_out)
        context_vec = self.proj(context_vec)
        return context_vec

d_model = 256
nhead = 4
seq_len = 1024
batch_size = 1
full_context_attention = MHAPyTorchScaledDotProduct(d_model, d_model, nhead, dropout=0.0)
x = torch.randn(batch_size, seq_len, d_model)
output_1 = full_context_attention(x)

qkv = full_context_attention.qkv(x)
qkv = qkv.view(batch_size, seq_len, 3, nhead, d_model // nhead)
qkv = qkv.permute(2, 0, 3, 1, 4)
queries, keys, values = qkv

output_2 = flex_attention(queries, keys, values, block_mask=None, scale=1 / math.sqrt(d_model // nhead))
output_2 = output_2.transpose(0, 1).contiguous().view(batch_size, seq_len, d_model)
output_2 = full_context_attention.proj(output_2)

diff = torch.abs(output_1 - output_2)
print(f"Max absolute difference: {diff.max().item()}")
print(f"Mean absolute difference: {diff.mean().item()}")
```

## Current Behavior
The code produces non-zero differences between the outputs:
- Max absolute difference: ~0.07
- Mean absolute difference: ~0.013

## Expected Behavior
Given that both functions are implementing the same attention mechanism, we would expect the outputs to be identical or have negligible differences.

## Questions
1. Is this discrepancy expected? If so, why?
2. If not expected, what could be causing this difference?
3. Are there any known limitations or differences between `scaled_dot_product_attention` and `flex_attention` that could explain this behavior?

## Environment
- PyTorch Version: 2.6.0.dev20240923
- Python Version: 3.9.6

### Versions

PyTorch version: 2.6.0.dev20240923
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.3 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: version 3.27.7
Libc version: N/A

Python version: 3.9.6 (default, Aug 11 2023, 19:44:49)  [Clang 15.0.0 (clang-1500.0.40.1)] (64-bit runtime)
Python platform: macOS-14.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.6.0.dev20240923
[pip3] torchaudio==2.5.0.dev20240923
[pip3] torchvision==0.20.0.dev20240923

**Comment by Chillee** [comment]
You have a bug in your code.

```
output_2 = output_2.transpose(0, 1).contiguous().view(batch_size, seq_len, d_model)
```
this should be `output_2.transpose(1,2)`, like the above code.
