### ISSUE TITLE
`slow` workflow has been broken for 4+ weeks

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#136694]
### 🐛 Describe the bug

According to https://github.com/pytorch/pytorch/actions/workflows/slow.yml?query=is%3Asuccess
last successful run of the workflow on main branch was on Aug 20th for https://github.com/pytorch/pytorch/commit/3caf3baabbc3af145d0551e47657f2a3ae39abef

If nobody pays attention to signal on that workflow and looks like it does not block `viable/strict` promotions either, I propose deleting it

### Versions

CI

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
+1 to this. If no one cares that these are broken then we should stop spending the infrastructure.

**Comment by huydhn** [comment]
Slow jobs also include slow-gradcheck, and historically speaking the current failure with memory leak could be legit https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=slow-gradcheck

**Comment by malfet** [comment]
Here is list of tests that has been marked as slow automatically: https://github.com/pytorch/test-infra/blob/generated-stats/stats/slow-tests.json

**Comment by zou3519** [comment]
Notes from triage review: @pytorch/pytorch-dev-infra could someone tell us if it's OK for us to move these jobs to trunk? If so, someone from the pytorch core team will go fix stuff until we can do the move.

**Comment by huydhn** [comment]
I have pushed several PRs throughout the week to fix slow and periodic workflows:

* https://github.com/pytorch/pytorch/pull/137447
* https://github.com/pytorch/pytorch/pull/137433
* https://github.com/pytorch/pytorch/pull/137633
* https://github.com/pytorch/pytorch/pull/137815
* https://github.com/pytorch/pytorch/pull/137835

The last one test_nestedtensor.py::TestNestedTensorSubclassCUDA::test_sdpa_backwards_cuda_bfloat16 [GH job link](https://github.com/pytorch/pytorch/actions/runs/11317598787/job/31472057192) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/08ce3aac6222bc044a34289be0885e37229d98a2) comes from https://github.com/pytorch/pytorch/pull/136875#discussion_r1797542869, and I have reached out to @jbschlosser for his insight.  Once that's fixed, we will have these workflow back in a good state.

**Comment by jbschlosser** [comment]
@huydo FYI I reverted and reopened #136875 with a fix for the memory leak. Relanding now

**Comment by huydhn** [comment]
Thank everyone for your help restoring trunk greeness!

As of today, all issues with periodic and slow job have been resolved.  I will continue to monitor them till the end of the week before resolving this issue.  New failures might come but I will fix them as they come until we have a plan to run them more frequently in trunk or get rid of them.

**Comment by huydhn** [comment]
I'll close this now as slow jobs has been recovered since last week.  The follow up discussion on what is the next step for slow jobs is scheduled on Oct 24th https://fburl.com/gdoc/g1r4uu2x
