### ISSUE TITLE
`windows.g4dn.xlarge` are periodically unavailable

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#136693]
### 🐛 Describe the bug

See 
<img width="745" alt="image" src="https://github.com/user-attachments/assets/4c8a80e4-490e-4658-8eea-217f486f5998">
And graph is so repeated, which makes me wonder that there is clearly some infra issue at play

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
Interesting chart.  This is very likely to be nightly PT binary Windows https://github.com/pytorch/test-infra/blob/main/.github/workflows/trigger_nightly_core.yml.  From its shape, a few more hours and the queue will pile up and spill over to the next  day :)

**Comment by ZainRizvi** [comment]
Resolving this issue since this was mitigated and these particular machines are no longer periodically unavailable.

Here's the issue for the proper fix for this class of problem: https://github.com/pytorch/test-infra/issues/5798
