### ISSUE TITLE
Can cuda10 use pytorch-0.4.1?

### ISSUE THREAD

**Issue by acodercat** [pytorch/pytorch#13661]
### Please note that this issue tracker is not a help form and this issue will be closed.
Can cuda10 use pytorch-0.4.1?

**Comment by soumith** [comment]
no

**Comment by acodercat** [comment]
How can I use cuda10?

**Comment by tengerye** [comment]
May I ask when will Cuda 10 be supported for conda install?

**Comment by nanditam1** [comment]
Hi, I am trying to install pytorch 0.4.1 from source, in an RTX2080 Ti with cuda-10.0. Keep getting this error : THCAtomics.cuh(100): error: cannot overload functions distinguished by return type alone . Kindly help me debug this. Thank you.

**Comment by mamunctg** [comment]
conda install pytorch=0.4.1 cuda92 -c pytorch

**Comment by Elfsong** [comment]
> conda install pytorch=0.4.1 cuda92 -c pytorch

It's useful!
