### ISSUE TITLE
JIT unable to compile range with 2 arguments

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#13674]
## 🐛 Bug

JIT is unable to compile range with more than 1 argument.

JIT can compile `range(10)` and cannot compile `range(0, 10)`

## To Reproduce

```
range() expects 1 argument but got 2:
@torch.jit.script_method
def inference(self, line_tensor):
    # type: (torch.Tensor) -> torch.Tensor
    hidden = self.init_hidden()

    # TODO: Question: how do you initialize output
    # below is needed to delcare the type of output to be Tensor
    output = torch.zeros(0)
    for i in range(1, line_tensor.size(0)):
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
        output, hidden = self(line_tensor[i], hidden)

    return output
```

## Expected behavior

Should support 2 arguments

## Environment

Please copy and paste the output from our

PyTorch version: 1.0.0a0+f282fa1
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 14.04.5 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
CMake version: version 3.12.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 396.24.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/lib/x86_64-linux-gnu/libcudnn_static_v6.a
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.15.3)
[pip] numpydoc (0.8.0)
[pip] torch (1.0.0a0+f282fa1)
[pip] torchvision (0.2.1)
[conda] magma-cuda80              2.3.0                         1    pytorch
[conda] pytorch                   0.4.1           py27__9.0.176_7.1.2_2    pytorch
[conda] torch                     1.0.0a0+f282fa1           <pip>
[conda] torchvision               0.2.1                    py27_1    pytorch

**Comment by eellison** [comment]
Thanks for noticing this - range currently only supports one parameter, but this is not documented. I have an update to the docs landing now. 

I'm closing the issue and I will comment when support for multiple parameters is added.

**Comment by sidazhang** [comment]
@eellison Can I just make a contribution to enable it? Is this something that you can point me to?

**Comment by eellison** [comment]
It's kind of an involved changed because you would have to make changes in the compiler, loop unrolling pass, interpreter, and ONNX export. 

Can you do something like: 

for i in range(end - start):
   i_adj = i + start

Until support is added ?

**Comment by Mikelew88** [comment]
What version of torch should we install to avoid this error (assuming it's resolved)?
