### ISSUE TITLE
Undefined symbols for architecture x86_64: "torch::jit::load"

### ISSUE THREAD

**Issue by Suhail** [pytorch/pytorch#13678]
## 🐛 Bug

```
make
Scanning dependencies of target mnist-app
[ 50%] Building CXX object CMakeFiles/mnist-app.dir/mnist.cpp.o
[100%] Linking CXX executable mnist-app
ld: warning: ignoring file ../libtorch/lib/libcaffe2.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): ../libtorch/lib/libcaffe2.so
ld: warning: ignoring file ../libtorch/lib/libtorch.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): ../libtorch/lib/libtorch.so
ld: warning: ignoring file ../libtorch/lib/libc10.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): ../libtorch/lib/libc10.so
Undefined symbols for architecture x86_64:
  "torch::jit::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      _main in mnist.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mnist-app] Error 1
make[1]: *** [CMakeFiles/mnist-app.dir/all] Error 2
make: *** [all] Error 2
```

## To Reproduce

Going through this tutorial: https://pytorch.org/tutorials/advanced/cpp_export.html

## Expected behavior

To build a binary correctly

## Environment

Please copy and paste the output from our
Collecting environment information...
PyTorch version: 1.0.0.dev20181029
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch                   0.4.1           py36_cuda0.0_cudnn0.0_1    pytorch
[conda] pytorch-nightly           1.0.0.dev20181029         py3.6_0    pytorch
[conda] pytorch-nightly-cpu       1.0.0.dev20181014         py3.6_0    pytorch
[conda] torch                     0.3.1                     <pip>
[conda] torch                     0.4.0                     <pip>
[conda] torchtext                 0.2.3                     <pip>
[conda] torchvision               0.2.1                     <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch
[conda] torchvision-nightly       0.2.1                     <pip>
[conda] torchvision-nightly-cpu   0.2.1              pyh19dea27_0    fastai

**Comment by Suhail** [comment]
fwiw, I was able to make this work on linux so maybe it's an OS X specific thing. It'd be helpful to make the tutorial work with that platform.

**Comment by suo** [comment]
Could you maybe post a link to the sample

**Comment by Suhail** [comment]
It’s identical to the tutorial code but just running on OS X.

**Comment by Suhail** [comment]
I think instructions to create our own libtorch extension by compiling from source on OS X probably would resolve this..

**Comment by Suhail** [comment]
Looks like the answer is to build pytorch & use the shared libs on OS X that you've built since the download is for x86.
