### ISSUE TITLE
Onnx exporting bug

### ISSUE THREAD

**Issue by JYS997760473** [pytorch/pytorch#136737]
### 🐛 Describe the bug

When I try to export Sparse4D's model to onnx, it shows:
![image](https://github.com/user-attachments/assets/b97f4831-f652-41e6-b320-ad03f7a1cf96)

### Versions

Python version is 3.8.19 and torch's version is 1.13.0+cu116

**Comment by titaiwangms** [comment]
Hi @JYS997760473,

Could you please try a newer version of PyTorch?
