### ISSUE TITLE
Long queue for Linux runners

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#136762]
## Current Status
Resolved. Pending Jobs triggered before 9:40 am PST can be run sooner if they're manually cancelled and restarted

## Error looks like
Long queue time for `linux` instances

## Incident timeline (all times pacific)
Detected 26 Sep 18:00 CET
Mitigated 26 Sep 18:40 CET with https://github.com/pytorch/pytorch/pull/136764

## User impact
* Linux jobs would be queued for hours, waiting for a runner to become available

## Root cause
* Hardcoded AMI images that reached EoL by Amazon.  Turns out AWS deprecates specific AMI images after 3 months and expects you to use a wildcard for the date portion of the AMI

## Mitigation
* Converted AMI images to be referenced by wildcard in scale-config.yml

## Prevention/followups
* Only use public images with wildcards in them

**Comment by jeanschmidt** [comment]
Issue mitigated, we expect queuing to start improving from now on

**Comment by malfet** [comment]
I don't think it is, there are 5+ hour queue for linux.2xlarge runners
<img width="766" alt="image" src="https://github.com/user-attachments/assets/8112d6e8-28d9-42ed-85e3-d44976258550">

**Comment by malfet** [comment]
Ok, I see the confusion, it was mitigated for LF runners by https://github.com/pytorch/pytorch/pull/136764, but not for ours as https://github.com/pytorch/test-infra/pull/5719 stayed open until 5 min ago, just merged it

**Comment by malfet** [comment]
Noob question: how to see similar graphs (that shows increase rate of error logs) in one of our dashboards (screenshot below is from AWS Lamba error rate monitor)
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/d7ddfc69-16cc-4784-8fd5-e828f6fe8ccd">

**Comment by malfet** [comment]
And queuing for linux.2xlarge is trending downwards now (purple is similar for `lf.linux.2xlarge` runners that were mitigated by https://github.com/pytorch/pytorch/pull/136764 , yellow if `linux.2xlarge` that were mitigated by https://github.com/pytorch/test-infra/pull/5719 )
<img width="762" alt="image" src="https://github.com/user-attachments/assets/57deff4c-9b26-425f-b514-b4956ff02207">
