### ISSUE TITLE
Cleanup stale Dynamo feature flags

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#136862]
### 🐛 Describe the bug

The following Dynamo feature flags in torch._dynamo.config are stale (they were associated with gradual bringup, but have now been defaulted to True and no one should be using the False configuration). I've ordered these from oldest to newest

- [x] #136864
- [ ] `dead_code_elimination` (essentially never used) @williamwen42 
- [ ] `raise_on_ctx_manager_usage` (essentially never used) @williamwen42 
- [ ] `error_on_nested_fx_trace` (as of Nov 1, 2022: https://github.com/pytorch/pytorch/pull/87797) - WARNING: this has Meta-internal usages
- [x] `capture_autograd_function` (as of Mar 19, 2023: https://github.com/pytorch/pytorch/pull/99483)
- [x] `capture_func_transforms` (as of Jun 21, 2023: https://github.com/pytorch/pytorch/pull/102264)
- [ ] `guard_nn_modules_using_dict_tags` (as of Sep 25, 2023: https://github.com/pytorch/pytorch/pull/110039) - @anijain2305 
- [x] `error_on_nested_jit_trace` (as of Oct 14, 2023: https://github.com/pytorch/pytorch/pull/111321)
- [ ] `use_lazy_graph_module` (as of Jan 26, 2024: https://github.com/pytorch/pytorch/pull/117911)
- [ ] `enable_cpp_guard_manager` (as of Mar 18, 2024: https://github.com/pytorch/pytorch/pull/120726) - @anijain2305 
- [ ] `skip_code_recursive_on_cache_limit_hit` (as of Sep 4, 2024: https://github.com/pytorch/pytorch/pull/135144 ) @williamwen42 
- [ ] `guard_nn_modules` (as of Sep 5, 2024 https://github.com/pytorch/pytorch/pull/134928)

It is good to remove unused feature flags, as it simplifies our code and reduces the combinatorial explosion of code paths to test. To safely remove a flag, you should not *actually* remove the flag from config.py, but instead make it do nothing (inline its default value to all call sites, eliminate dead code, delete tests that check the non-default behavior) and leave the flag as a stub that does nothing. It would be good to collect all dead stubs at one part of the config file; there are some existing dead stubs that are just hanging out.

For safety, it's probably better to work on the oldest flags first, and then work your way up. You should check if there are nontrivial uses of the flag at Meta, which may indicate that the flag is actually load bearing and shouldn't be removed.

You could also make an equivalent version of this issue for Inductor.

Comment on the issue to claim a task. Add me as reviewer.

### Versions

main

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec

**Comment by yuzcat01** [comment]
Hello, I would like to take a shot at this. I am fairly new to open source. Any additional information or guidance would be appreciated.

**Comment by bobrenjc93** [comment]
Heads up that I put up 4 draft PRs for 

`capture_autograd_function`: https://github.com/pytorch/pytorch/pull/136959
`capture_func_transforms`: https://github.com/pytorch/pytorch/pull/136960
`error_on_nested_jit_trace`: https://github.com/pytorch/pytorch/pull/136961
`use_lazy_graph_module`: https://github.com/pytorch/pytorch/pull/136962

I'll wait for CI to turn green before publishing.

**Comment by zeshengzong** [comment]
Deprecate `skip_code_recursive_on_cache_limit_hit` #136970

**Comment by augustboland** [comment]
take guard_nn_modules

**Comment by anijain2305** [comment]
@augustboland we will wait a few more months before we deprecate guard_nn_nodukes. So, please choose some other flag if you are interested.

**Comment by anijain2305** [comment]
@ezyang should we wait one release cycle to deprecate the flags. Sometimes flag are introduced just to control the behavior in case some corner case is very wrong. 3-4 months of release cycle is good to hash out such corner cases.

**Comment by benjamintli** [comment]
Can I try taking `raise_on_ctx_manager_usage`?

**Comment by ezyang** [comment]
@anijain2305 sure, go ahead and edit issue description

**Comment by prak74** [comment]
Hi, new to open source contribution and excited to contribute. I can try picking up `use_lazy_graph_module`. I'd be grateful for any pointers/advice. Thanks!

**Comment by Mikiya0515** [comment]
Hi, I'm new here, but can I try enable_cpp_guard_manager?

**Comment by joldov** [comment]
Hello, I am excited to contribute! can I take use_lazy_graph_module?

**Comment by wwwbai** [comment]
Hey can i take raise_on_ctx_manager_usage?

**Comment by Ayush-Parhi** [comment]
Hi @ezyang, 

Heads up, Submitted a PR cleaning up `raise_on_ctx_manager_usage` : #[140470](https://github.com/pytorch/pytorch/pull/140470)

Please review and let me know if any changes is required.
