### ISSUE TITLE
Tensor.gather() doesn't check for out-of-bound indices on GPU

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#1368]
Gather/scatter kernels are missing some asserts.

**Comment by killeent** [comment]
I will take a look.

**Comment by killeent** [comment]
@apaszke Is this issue referring to the user specifying and index `>=` the size of the tensor along the scatter/gather dimension?

**Comment by soumith** [comment]
correct. in kernels such as indexCopy or NLLLoss, we have asserts in the CUDA device kernels. gather and scatter need to have these device asserts too.

**Comment by killeent** [comment]
@soumith this can be closed?
