### ISSUE TITLE
Time cost bug in "torch.linalg.cholesky()"

### ISSUE THREAD

**Issue by Axceeds** [pytorch/pytorch#136823]
### 🐛 Describe the bug

When i try the API `torch.linalg.cholesky`  in pytorch `2.0.0`, I find that if i try to use it for the Tensor after network process，such as：
```
z = EWDNet(tensor).squeeze(0)
conv = z@z.transpose(-1, -2)
L = torch.linalg.cholesky(conv)
```
The time cost is **0.03s**.
it will be much slower than that Tensor which is not processed by network such as  being created by `torch.rand` as:
```
z = torch.randn(1, 32, 100, device=device)
conv = z@z.transpose(-1, -2)
L = torch.linalg.cholesky(conv)
```
The time cost is **0.0011s**.
All data and model are on `cuda`, and `with torch.no_grad()`.
I try to convert the Tensor to numpy and then convert it back to torch.tensor, amazingly, the time cost is so close to the tensor which is 0.0012s. 
It should be that the network has introduced some additional cost, resulting in a decrease in the speed of matrix decomposition.

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 专业版
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: Could not collect
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.14 | packaged by Anaconda, Inc. | (main, Mar 21 2024, 16:20:14) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: 10.1.243
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 536.67
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:

Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.15.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h6b88ed4_46358  
[conda] mkl-service               2.4.0           py310h2bbff1b_1  
[conda] mkl_fft                   1.3.8           py310h2bbff1b_0  
[conda] mkl_random                1.2.4           py310h59b6b97_0  
[conda] numpy                     1.26.4          py310h055cbcc_0  
[conda] numpy-base                1.26.4          py310h65a83cf_0  
[conda] pytorch                   2.0.0           py3.10_cuda11.8_cudnn8_0    pytorch
[conda] pytorch-cuda              11.8                 h24eeafa_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.0                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.15.0                   pypi_0    pypi

Process finished with exit code 0

**Comment by albanD** [comment]
Hey!
I don't think you are profiling this correctly. Please see https://pytorch.org/docs/stable/notes/cuda.html#asynchronous-execution for details.
Feel free to re-open if the issue still happens after proper synchronization or post on discuss.pytorch.org if you have any question!
