### ISSUE TITLE
In the forward(query, key, value, key_padding_mask=None, need_weights=True, attn_mask=None, average_attn_weights=True, is_causal=False) method of MultiheadAttention, there is an issue with the key_padding_mask parameter.||

### ISSUE THREAD

**Issue by sealoongleft** [pytorch/pytorch#136816]
### 🐛 Describe the bug

DESCRIPTION:
When using the key_padding_mask parameter:
(1) If using [[1., 0.]] that conforms to the description in the API is normal, [1., 0.] will be added to the corresponding key.
(2) However, if [0., 1.] is used, an error will occur. [0., 1.] is not simply added to the key, and even the result returns the value of attn_output_weights, which does not add up to 1, seriously deviating from the description in the API.
In the API, it is stated that if key_padding_mask is a floating-point number, it will be added to the corresponding key. Obviously, there is a bug in (2).
api link is https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html#torch.nn.MultiheadAttention.merge_masks

CODE:
``` Python
import torch
import torch.nn as nn

mha=nn.MultiheadAttention(embed_dim=1, num_heads=1, dropout=0, bias=False, add_bias_kv=False,
                          add_zero_attn=False, kdim=None, vdim=None, batch_first=True,
                          device=None)
mha.in_proj_weight.data =torch.tensor([[1],[3],[2]],dtype=torch.float)
mha.out_proj.weight.data=torch.tensor([[2]],dtype=torch.float)
inputdata=torch.tensor([[[1.],[2.]]])
out=mha(inputdata,inputdata,inputdata,average_attn_weights=False,need_weights=True,
        is_causal=None,attn_mask=None,key_padding_mask=torch.tensor([[0.,1]],dtype=torch.float))#issue is over here "key_padding_mask=torch.tensor([[0.,1]],dtype=torch.float)" which is wrong output,however key_padding_mask=torch.tensor([[1.,0]],dtype=torch.float) is normal output as described in api. 
print('inputdata:',inputdata,'in_proj_weight:',mha.in_proj_weight,
      'out_proj.weight:',mha.out_proj.weight)
print(out)
```
OUTPUT:
``` Shell
>>> %Run VALZ.py
inputdata: tensor([[[1.],[2.]]]) in_proj_weight: Parameter containing:
tensor([[1.],
        [3.],
        [2.]], requires_grad=True) out_proj.weight: Parameter containing:
tensor([[2.]], requires_grad=True)
(tensor([[[7.9281],
         [7.9964]]], grad_fn=<TransposeBackward0>), tensor([[[[1.7986e-02, 9.8201e-01],
          [9.1105e-04, 9.9909e-01]]]], grad_fn=<ViewBackward0>))
```

### Versions

Collecting environment information...
PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home China
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1650 Ti
Nvidia driver version: 556.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2496
DeviceID=CPU0
Family=205
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2496
Name=Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] mypy==1.5.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.3
[pip3] torch==2.3.1+cu121
[pip3] torchaudio==2.3.1+cu121
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.18.1+cu121
[conda] Could not collect
cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by sealoongleft** [comment]
this  is really a bug

**Comment by sealoongleft** [comment]
hello？

**Comment by drisspg** [comment]
All of these are returning an attnetion weight that sums to 1


```
import torch
import torch.nn as nn

mha = nn.MultiheadAttention(
    embed_dim=1,
    num_heads=1,
    dropout=0,
    bias=False,
    add_bias_kv=False,
    add_zero_attn=False,
    kdim=None,
    vdim=None,
    batch_first=True,
    device=None,
)

mha.in_proj_weight.data = torch.tensor([[1], [3], [2]], dtype=torch.float)
mha.out_proj.weight.data = torch.tensor([[2]], dtype=torch.float)

input_data = torch.tensor([[[1.0], [2.0]]])
key_padding_mask = torch.tensor([[False, True]], dtype=torch.bool)
key_padding_mask = torch.tensor([[0.,1]],dtype=torch.float)
# key_padding_mask = torch.tensor([[1,0.]],dtype=torch.float)

out, attn_weights = mha(
    input_data,
    input_data,
    input_data,
    average_attn_weights=False,
    need_weights=True,
    is_causal=None,
    attn_mask=None,
    key_padding_mask=key_padding_mask,
)

print("Input data:", input_data)
print("in_proj_weight:", mha.in_proj_weight)
print("out_proj.weight:\n", mha.out_proj.weight)
print("Output:\n", out)
print("Attention weights:\n", attn_weights)
print("Attention weights sum:\n", torch.sum(attn_weights, dim=-1))

```
