### ISSUE TITLE
cannot find torch 2.4.x in https://download.pytorch.org/whl/torch_stable.html

### ISSUE THREAD

**Issue by siriusa51** [pytorch/pytorch#136939]
### 🚀 The feature, motivation and pitch

cannot find torch 2.4.x in https://download.pytorch.org/whl/torch_stable.html

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
@atalman , @kit1980 can you please check why that is the case? 
Looks like updates to torch_stable finished around 2.4 timeframe

Also, do we still want to support those?

**Comment by atalman** [comment]
@siriusa51 Please use instructions from https://pytorch.org/get-started/locally/ 

These are instructions for pip download cpu, cuda 12.1, cuda 11.8, cuda 12.4:
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
pip3 install torch torchvision torchaudio 
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
```

The [download.pytorch.org/whl/torch_stable.html](https://download.pytorch.org/whl/torch_stable.html) support was deprecated by this PR: https://github.com/pytorch/test-infra/pull/5296

**Comment by siriusa51** [comment]
> @siriusa51 Please use instructions from https://pytorch.org/get-started/locally/
> 
> These are instructions for pip download cpu, cuda 12.1, cuda 11.8, cuda 12.4:
> 
> ```
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
> pip3 install torch torchvision torchaudio 
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
> ```
> 
> The [download.pytorch.org/whl/torch_stable.html](https://download.pytorch.org/whl/torch_stable.html) support was deprecated by this PR: [pytorch/test-infra#5296](https://github.com/pytorch/test-infra/pull/5296)

Thanks a lot for your reply!
