### ISSUE TITLE
FSDP2 does not copy custom Parameter attributes when sharding

### ISSUE THREAD

**Issue by santhnm2** [pytorch/pytorch#136929]
### 🐛 Describe the bug

When sharding a model using the `fully_shard` API any custom parameter attributes set in the unsharded model are not copied over to the sharded model. This can be observed here where `self.sharded_param` is instantiated as a new `Parameter` without copying any of the additional custom attributes: https://github.com/pytorch/pytorch/blob/156ca01e51f766b1b069c5c6f3d57112a5c8f9ff/torch/distributed/_composable/fsdp/_fsdp_param.py#L355

Self-contained script to reproduce:
```
import torch
import torch.nn as nn
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.distributed._composable.fsdp import fully_shard

def run(rank, world_size):
    dist.init_process_group(
        backend='nccl',
        init_method='tcp://localhost:29500',
        rank=rank,
        world_size=world_size
    )

    device = torch.device(f'cuda:{rank}' if torch.cuda.is_available() else 'cpu')
    torch.cuda.set_device(device) if torch.cuda.is_available() else None

    class MyModel(nn.Module):
        def __init__(self):
            super(MyModel, self).__init__()
            self.linear1 = nn.Linear(10, 5)
            self.linear2 = nn.Linear(5, 2)

        def forward(self, x):
            x = self.linear1(x)
            x = torch.relu(x)
            return self.linear2(x)

    model = MyModel().to(device)

    model.linear1.weight.custom_attr = 'custom_value_linear1_weight'
    model.linear1.bias.custom_attr = 'custom_value_linear1_bias'
    model.linear2.weight.custom_attr = 'custom_value_linear2_weight'
    model.linear2.bias.custom_attr = 'custom_value_linear2_bias'

    def check_custom_attrs(model, stage):
        for name, param in model.named_parameters():
            exists = hasattr(param, 'custom_attr')
            value = getattr(param, 'custom_attr', None)
            print(f"Rank {rank} - {stage} - {name}: custom_attr exists? {exists}, value: {value}")

    print(f"\nRank {rank} - Before fully_shard:")
    check_custom_attrs(model, "Before fully_shard")

    fully_shard(model)

    print(f"\nRank {rank} - After fully_shard:")
    check_custom_attrs(model, "After fully_shard")

    dist.destroy_process_group()

if __name__ == '__main__':
    world_size = 2
    mp.spawn(run, args=(world_size,), nprocs=world_size, join=True)
```

The output I see from this script:
```
Rank 1 - Before fully_shard:
Rank 1 - Before fully_shard - linear1.weight: custom_attr exists? True, value: custom_value_linear1_weight
Rank 1 - Before fully_shard - linear1.bias: custom_attr exists? True, value: custom_value_linear1_bias
Rank 1 - Before fully_shard - linear2.weight: custom_attr exists? True, value: custom_value_linear2_weight
Rank 1 - Before fully_shard - linear2.bias: custom_attr exists? True, value: custom_value_linear2_bias

Rank 1 - After fully_shard:
Rank 1 - After fully_shard - linear1.weight: custom_attr exists? False, value: None
Rank 1 - After fully_shard - linear1.bias: custom_attr exists? False, value: None
Rank 1 - After fully_shard - linear2.weight: custom_attr exists? False, value: None
Rank 1 - After fully_shard - linear2.bias: custom_attr exists? False, value: None

Rank 0 - Before fully_shard:
Rank 0 - Before fully_shard - linear1.weight: custom_attr exists? True, value: custom_value_linear1_weight
Rank 0 - Before fully_shard - linear1.bias: custom_attr exists? True, value: custom_value_linear1_bias
Rank 0 - Before fully_shard - linear2.weight: custom_attr exists? True, value: custom_value_linear2_weight
Rank 0 - Before fully_shard - linear2.bias: custom_attr exists? True, value: custom_value_linear2_bias

Rank 0 - After fully_shard:
Rank 0 - After fully_shard - linear1.weight: custom_attr exists? False, value: None
Rank 0 - After fully_shard - linear1.bias: custom_attr exists? False, value: None
Rank 0 - After fully_shard - linear2.weight: custom_attr exists? False, value: None
Rank 0 - After fully_shard - linear2.bias: custom_attr exists? False, value: None
```

### Versions

Ran with PyTorch 2.5.0 on 2 H100 GPUs.

cc @zhaojuanmao @mrshenli @rohan-varma @awgu @fegin @kwen2501 @chauhang

**Comment by santhnm2** [comment]
A proposed fix would be to save the custom attributes from the unsharded parameter like so:
```
attrs = vars(param)
custom_attrs = {k: v for k, v in attrs.items()}
```
and then restore like so:
```
for attr_name, attr_value in custom_attrs.items():
    setattr(self.sharded_param, attr_name, attr_value)
```

**Comment by awgu** [comment]
Thanks for filing this issue! 

I think that this is a problem for any API that changes the parameter to a new tensor object. I wonder if the custom tensor attributes can be set after calling `fully_shard`?

Otherwise you will encounter the same issue when applying other PyTorch APIs too (e.g. `DTensor` or some of the torchao quantization APIs) or even if doing meta-device initialization with `torch.Tensor`.

**Comment by santhnm2** [comment]
> Thanks for filing this issue! 
> 
> 
> 
> I think that this is a problem for any API that changes the parameter to a new tensor object. I wonder if the custom tensor attributes can be set after calling `fully_shard`?
> 
> 
> 
> Otherwise you will encounter the same issue when applying other PyTorch APIs too (e.g. `DTensor` or some of the torchao quantization APIs) or even if doing meta-device initialization with `torch.Tensor`.

Thanks for taking a look! That is the solution we went with for now, but we were surprised by this behavior because the parameter values remained intact with the original FSDP API as long as we set `use_orig_params=True` but with FSDP2 this is no longer the case. If it doesn't make sense to change this in the FSDP2 code itself maybe clarifying the documentation would still be helpful.

**Comment by awgu** [comment]
Ah, yes that behavior for `use_orig_params=True` was implicit because we were using `orig_param.data = <view into FlatParameter>`. I think we wanted that to be considered undefined behavior since we did not want that `orig_param.data = ...` to be part of the user-facing API, but it makes sense that people may have relied on it.

**Comment by awgu** [comment]
going to close this for now
