### ISSUE TITLE
PyTorch Testing Nodes Undergoing ROCm 6.2.1 Upgrades

### ISSUE THREAD

**Issue by amdfaa** [pytorch/pytorch#136928]
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
preemptive

## Error looks like
ROCm pytorch jobs will take a long time to queue due to a subset of ROCm PyTorch nodes undergoing upgrades

## Incident timeline (all times pacific)
28th Sept 2024 3:06 PM - 30th Sept 2024 ~12:30PM

## User impact
Queue jobs will take a long time to be picked up by runners.

## Root cause
ROCm pytorch nodes are undergoing ROCm upgrades.

## Mitigation
Completing the upgrade.

## Prevention/followups
N/A

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

**Comment by kit1980** [comment]
@amdfaa Please don't create CI SEVs without consulting with PyTorch Dev Infra team, and especially please don't create merge blocking SEVs - they block all merges to PyTorch for everybody.

**Comment by malfet** [comment]
Let me clarify the above: if one wants to create a merge blocking SEV, it must be resolved on the same date it was created.

**Comment by ZainRizvi** [comment]
Hi @amdfaa, are you expecting the ROCm fleet to be unavailable during that time range?  Instead of a sev, what about marking the jobs as unstable? That would be in line with the mitigation step when a particular instance type is unavailable for an extended time due to any infrastructure issue

**Comment by jithunnair-amd** [comment]
We can follow whichever is the best practice recommended: "ci sev" or "unstable". Only one option would be best (instead of both). The intention is to convey to developers that ROCm CI runners might not be available or be undergoing upgrades.

@ZainRizvi Can you help clarify how we should think of a CI SEV as different from moving CI jobs to unstable?

**Comment by malfet** [comment]
> Instead of a sev, what about marking the jobs as unstable? That would be in line with the mitigation steps when a particular instance type is unavailable for an extended time due to any infrastructure issue

This feels inconsistent with what PyTorch infra team usually does, when preemptive SEV (non merge blocking though) are created to highlight lack of signal for the duration of the migration, because remediation might require some revert to bring back CI sanity

**Comment by malfet** [comment]
@jithunnair-amd just checking, can this one be closed or is migration still ongoing?

**Comment by amdfaa** [comment]
> @jithunnair-amd just checking, can this one be closed or is migration still in progress?

It's still in progress.

**Comment by malfet** [comment]
Hmm, I don't see any queueing on ROCm runners right now, is this because workflow is disabled? If that's the case, I propose to close the SEV
<img width="759" alt="image" src="https://github.com/user-attachments/assets/9bae37bf-7883-45ce-9e90-fd35aa343989">

**Comment by malfet** [comment]
@amdfaa as author of the SEV, can you provide some updates into what is going on?

**Comment by amdfaa** [comment]
The migration has been completed. As for queue times, I see jobs on the runners.

**Comment by malfet** [comment]
> The migration has been completed. As for queue times, I see jobs on the runners.

Closing the SEV then

**Comment by ZainRizvi** [comment]
> @ZainRizvi Can you help clarify how we should think of a CI SEV as different from moving CI jobs to unstable?

@jithunnair-amd IMO it depends on what you expect the fleet availability to look like during this outage:

1. If you’re making changes that _might_ break CI (which includes unacceptably long queueing), then filing a preemptive SEV would be appropriate
2. If you’re making changes that _will_ temporarily break CI then disable jobs to minimize user pain would be more appropriate (of course if that would disable everything, then that’s a merge blocking sev and one should consider if there’s a better upgrade path instead)

In this case, the issue description made it sound like this was a case of #2, but in practice there seems to have been practically no queueing (looking at http://hud.pytorch.org/metrics) so this was actually a case of #1
