### ISSUE TITLE
Getting fspd state dict warning despite using recommanded function

### ISSUE THREAD

**Issue by samsja** [pytorch/pytorch#136907]
### 🐛 Describe the bug

I am using fsdp 1. While trying to checkpoint I got the warning.

```bash
/home/samsja/workspace/pi/ZeroBand/.venv/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:689: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html
```

even though I am using `torch.distributed.checkpoint.get_state_dict` as a function to save my checkpoint.

### Versions

pytorch 2.4.1+cu121

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by awgu** [comment]
cc: @fegin @wz337

**Comment by ppwwyyxx** [comment]
fixed in https://github.com/pytorch/pytorch/pull/132621

**Comment by samsja** [comment]
nice thanks !

**Comment by steveepreston** [comment]
@ppwwyyxx Are you sure this is fixed?

Still getting this warning in `2.5.1+cu124`

**Comment by fegin** [comment]
@steveepreston Do you have a minirepro for the issue?

**Comment by steveepreston** [comment]
I'm following this guide: https://www.philschmid.de/fsdp-qlora-llama3

Base script: https://github.com/philschmid/deep-learning-pytorch-huggingface/blob/main/training/scripts/run_fsdp_qlora.py

**Comment by steveepreston** [comment]
@fegin Thanks for attention

I'm following this guide: https://www.philschmid.de/fsdp-qlora-llama3

Base script: https://github.com/philschmid/deep-learning-pytorch-huggingface/blob/main/training/scripts/run_fsdp_qlora.py
