### ISSUE TITLE
The inductor UT `test_unspec_inputs_cuda_cuda_wrapper`  fails on main branch but not tested in trunk.

### ISSUE THREAD

**Issue by etaf** [pytorch/pytorch#136940]
### 🐛 Describe the bug

The following failed inductor test cases is reproduced in main branch and I don't know why it is not exposed on ciflow/trunk test.:
[inductor / cuda12.1-py3.10-gcc9-sm86 / test (inductor_cpp_wrapper_abi_compatible, 1, 1, lf.linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/135318#30794469038) ([gh](https://github.com/pytorch/pytorch/actions/runs/11081724720/job/30794469038))
inductor/test_cuda_cpp_wrapper.py::TestGpuWrapper::test_dtypeview_cuda_gpu_wrapper
[pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 2, 5, lf.linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/135318#30794419929) ([gh](https://github.com/pytorch/pytorch/actions/runs/11081724355/job/30794419929))
inductor/test_cuda_cpp_wrapper.py::TestGpuWrapper::test_dtypeview_cuda_gpu_wrapper
[pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 3, 5, lf.linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/135318#30794420062) ([gh](https://github.com/pytorch/pytorch/actions/runs/11081724355/job/30794420062))
inductor/test_cuda_cpp_wrapper.py::DynamicShapesGpuWrapperGpuTests::test_unspec_inputs_cuda_dynamic_shapes_gpu_wrapper
[pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 4, 5, lf.linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/135318#30794420219) ([gh](https://github.com/pytorch/pytorch/actions/runs/11081724355/job/30794420219))
inductor/test_cuda_cpp_wrapper.py::TestGpuWrapper::test_unspec_inputs_cuda_gpu_wrapper
[trunk / linux-focal-cuda12.4-py3.10-gcc9-sm86 / test (default, 2, 5, lf.linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/135318#30794446703) ([gh](https://github.com/pytorch/pytorch/actions/runs/11081724739/job/30794446703))
inductor/test_cuda_cpp_wrapper.py::TestGpuWrapper::test_dtypeview_cuda_gpu_wrapper
[trunk / linux-focal-cuda12.4-py3.10-gcc9-sm86 / test (default, 3, 5, lf.linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/135318#30794446851) ([gh](https://github.com/pytorch/pytorch/actions/runs/11081724739/job/30794446851))
inductor/test_cuda_cpp_wrapper.py::DynamicShapesGpuWrapperGpuTests::test_unspec_inputs_cuda_dynamic_shapes_gpu_wrapper
[trunk / linux-focal-cuda12.4-py3.10-gcc9-sm86 / test (default, 4, 5, lf.linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/135318#30794446992) ([gh](https://github.com/pytorch/pytorch/actions/runs/11081724739/job/30794446992))
inductor/test_cuda_cpp_wrapper.py::TestGpuWrapper::test_unspec_inputs_cuda_gpu_wrapper

By bisect the commits on main branch, I found first bad commit: [2521cd387482a70d30e4ea922fa4fe3b488c9f6d]

### Versions

PyTorch version: 2.6.0a0+gite9e2464
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
Clang version: Could not collect
CMake version: version 3.30.4
Libc version: glibc-2.31

Python version: 3.10.15 | packaged by conda-forge | (main, Sep 20 2024, 16:37:05) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-97-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB
Nvidia driver version: 550.54.15

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @desertfire @chenyang78

**Comment by desertfire** [comment]
@muchulee8 , I verified that reverting https://github.com/pytorch/pytorch/pull/136389 locally makes test_unspec_inputs_cuda_gpu_wrapper pass. The reason they are not shown in trunk test is because they are only run on "@slow", see https://hud.pytorch.org/hud/pytorch/pytorch/main/3?per_page=50&name_filter=slow
