### ISSUE TITLE
[CI][Docker] Build manywheel docker images failure due to "unauthorized: incorrect username or password"

### ISSUE THREAD

**Issue by nWEIdia** [pytorch/pytorch#136932]
### 🐛 Describe the bug

Failure log: https://github.com/pytorch/pytorch/actions/runs/11076913528/job/30781049008 

https://hub.docker.com/r/pytorch/manylinuxaarch64-builder/tags (cuda12.4-main) last update was 3 days ago (Sep 25th).

### Versions

https://github.com/pytorch/pytorch/commit/e512eac410802d8adfba5ae0cffd6f908cbb50cd is supposed to update aarch64 cuda 12.4 docker images with cusparselt 0.6.2, but it failed to push the tag. 

cc @kit1980 @atalman @malfet

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by atalman** [comment]
@nWEIdia This looks like flaky issue, rerunning this is successful: https://github.com/pytorch/pytorch/actions/runs/11076913528/job/30818244399

**Comment by nWEIdia** [comment]
Thank you @atalman ! That is good to hear. I restarted one more time to see if this is somehow related to a controlled access group, e.g. would it fail for me 100% of the time.

**Comment by nWEIdia** [comment]
Verified that the docker image now contains libcusparseLt 0.6.2.3 (docker.io/pytorch/manylinuxaarch64-builder:cuda12.4-main)

# ls libcusparseLt*
libcusparseLt.so  libcusparseLt.so.0  libcusparseLt.so.0.6.2.3  libcusparseLt_static.a
