### ISSUE TITLE
Where can I found a version table?

### ISSUE THREAD

**Issue by ZhuShaoQiang** [pytorch/pytorch#137069]
I was using pytorch 1.13.1, and now I want to do a new RL work, so I want to get start from your [Mario code](https://pytorch.org/tutorials/intermediate/mario_rl_tutorial.html).
So I install torchrl according to your tutorial, and `pip install torchrl` uninstall my torch==1.13.1.
But I want to use torch==1.13.1.
and I tried torchrl 0.1.0   0.1.1   0.2.0,
they all uninstall my torch==1.13.1 and install torh==2.4.1.
Could you please give a table about how to choose those version?

**Comment by drisspg** [comment]
This seems like a better question for: https://github.com/pytorch/rl
