### ISSUE TITLE
[Bug] wrong calculations in torch.bfloat16

### ISSUE THREAD

**Issue by mariovas3** [pytorch/pytorch#137035]
### 🐛 Describe the bug

I encountered a strange error with `torch.bfloat16` arithmetic. I tested it both on CPU and T4 GPU. Basically, when doing arithmetic in `torch.bfloat16` I get `(692 + 720) / 2 = 704` while in reality it should be `706` as shown in the images below. The wrong output of similar operations feeds into further components of my pipeline, exacerbating the effect of the error.

CPU version:

![bad_bfloat16_cpu](https://github.com/user-attachments/assets/8881aabd-a437-40e6-be53-ad18abcf7940)

GPU version:

![bad_bfloat_arithmetic_colab_gpu](https://github.com/user-attachments/assets/7f83516b-325c-4a68-bfe7-78d5ab4a9ea3)

Please provide clarity on what's going on. I couldn't find obvious reasons why this happens.

### Versions

The GPU error is tested in Google Colab while the CPU error is tested on my local PC with the following specs:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

with kernel version:
```
5.15.0-122-generic
```

cpu info:
```
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Byte Order:                           Little Endian
Address sizes:                        39 bits physical, 48 bits virtual
CPU(s):                               8
On-line CPU(s) list:                  0-7
Thread(s) per core:                   2
Core(s) per socket:                   4
Socket(s):                            1
NUMA node(s):                         1
Vendor ID:                            GenuineIntel
CPU family:                           6
Model:                                142
Model name:                           Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Stepping:                             12
CPU MHz:                              1800.000
CPU max MHz:                          3900.0000
CPU min MHz:                          400.0000
BogoMIPS:                             3600.00
Virtualisation:                       VT-x
L1d cache:                            128 KiB
L1i cache:                            128 KiB
L2 cache:                             1 MiB
L3 cache:                             6 MiB
NUMA node0 CPU(s):                    0-7
```

**Comment by malfet** [comment]
Thank you for filing the issue, but this is an expected behavior, as 692+720=1412, but best way to represent it as bfloat16 is 1408, see https://en.wikipedia.org/wiki/Bfloat16_floating-point_format

**Comment by mariovas3** [comment]
Thanks for the quick response. I looked it up; I knew these simple low-precision flags that are thrown around would come to bite me at some point. :D

So far haven't had problems with LLMs, but for more precision-critical stuff, it's not ideal.

**Comment by malfet** [comment]
To finish this discussion:
```
python -c "import torch; x=torch.tensor(692 + 720, dtype=torch.bfloat16); print(f'value={x.item()} ulp={(x.nextafter(torch.full_like(x, torch.inf))-x).item()}')"
value=1408.0 ulp=8.0
```
