### ISSUE TITLE
[Bug] RandomCrop  on (torchvision\transforms\transforms.py .. line 411)

### ISSUE THREAD

**Issue by dori2063** [pytorch/pytorch#13704]
## To Reproduce

1. I'm following https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html 
2. And   I changed 
      trainloader.dataset.transform = transforms.Compose([
                                         transforms.RandomCrop(size=32, padding=(0,1,2,3)),            
                                         transforms.RandomHorizontalFlip(),transforms.ToTensor(),
                                         transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
3. Error apeared in \torchvision\transforms\transforms.py .. line 411
self.padding > 0 do not work, because I inserted tuple..

4. I just erased that line and code is working well.

5. Isn't it bug? I think that line should be erased or add some lines for sequances.

## Environment

 - PyTorch Version : 0.4.1
 - torchvision Version : 0.2.1
 - OS (e.g., Linux): window, anaconda, spyder, prompt
 - Python version: 3.6

**Comment by soumith** [comment]
> transforms.RandomCrop(size=32, padding=(0,1,2,3)),

This is incorrect usage, this is not expected to work.
Refer to https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.RandomCrop for correct usage, maybe you want `padding=(1,1,1,1)` or something like that
