### ISSUE TITLE
Weirdly strided input and mark_unbacked don't play well together

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#137087]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/6829516587176185/permalink/1502206057084267/

Repro:

```
    def test_mark_unbacked_slice(self):
        @torch.compile(backend="inductor", mode="reduce-overhead", fullgraph=True)
        def f(x):
            return x.sum()
            
        x = torch.empty_strided((1, 4), (5, 1), device="cuda")
        torch._dynamo.decorators.mark_unbacked(x, 0)
        f(x)
```

Fails with:

```
  File "/data/users/ezyang/b/pytorch/torch/_inductor/compile_fx.py", line 572, in codegen_and_compile
    complex_memory_overlap_inputs = any(
  File "/data/users/ezyang/b/pytorch/torch/_inductor/compile_fx.py", line 573, in <genexpr>
    complex_memory_overlap(t)
  File "/data/users/ezyang/b/pytorch/torch/_inductor/compile_fx.py", line 132, in complex_memory_overlap
    if torch._debug_has_internal_overlap(t) != 0:
  File "/data/users/ezyang/b/pytorch/torch/fx/experimental/sym_node.py", line 449, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/data/users/ezyang/b/pytorch/torch/fx/experimental/recording.py", line 262, in wrapper
    return retlog(fn(*args, **kwargs))
  File "/data/users/ezyang/b/pytorch/torch/fx/experimental/symbolic_shapes.py", line 5856, in evaluate_expr
    return self._evaluate_expr(
  File "/data/users/ezyang/b/pytorch/torch/fx/experimental/symbolic_shapes.py", line 5998, in _evaluate_expr
    raise self._make_data_dependent_error(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
GuardOnDataDependentSymNode: Could not guard on data-dependent expression False (unhinted: Eq(IsNonOverlappingAndDenseIndicator(u0, 4, s0, 1), 1)).  (Size-like symbols: none)

Caused by: (_inductor/compile_fx.py:132 in complex_memory_overlap)
```

There's a few things going on here.

First, despite not marking anything dynamic, the stride[0] on the input tensor got a dynamic value anyway. While this is a policy decision, there's no way to force the stride to specifically be static. Need to give some more API tools for specifying this (this would coincide with a general rework of how we mark things dynamic).

Second, we're doing a memory overlap computation here

```
def complex_memory_overlap(t: torch.Tensor) -> bool:
    # if torch._debug_has_internal_overlap thinks this tensor potentially has
    # memory overlap internally, let's dig deeper to find out whether it's true.
    #               
    # Call squeeze() so that dimension with size 1 does not cause false positive.
    t = index_expanded_dims(t, get_expanded_dims(t)).squeeze()
    if torch._debug_has_internal_overlap(t) != 0:
        strides = t.stride()
        sizes = t.shape
        indices = list(range(len(strides)))
        indices = [x for _, x in sorted(zip(strides, indices))]
        for i in range(len(strides)):
            prev_stride = 1 if i == 0 else strides[indices[i - 1]]
            prev_size = 1 if i == 0 else sizes[indices[i - 1]]
            if strides[indices[i]] < prev_stride * prev_size:
                return True 
    return False 
```

It is an approximation. So we can potentially just give up and say True here (which would cause CUDA graphs to be disabled). But also, we actually statically know overlap is impossible; overlap is entirely predicated on `s0 >= 4` (which it is, in the underlying value). The u0 value is irrelevant. So we can also just make IsNonOverlappingAndDenseIndicator smarter.

Third, the computation here actually ends up being pointless. Even if you say that there is no complex memory overlap, you have:

```
skipping cudagraphs due to ['incompatible ops']
```

so all of this computation was pointless! It wouldn't have made a difference in the end anyway. So maybe we should catch GuardOnDataDependent errors when testing CUDA graph conditions, and wait and see if we can make a determination by other methods.

cc @chauhang @penguinwu @bobrenjc93 @eellison 

### Versions

main

**Comment by eellison** [comment]
Specializing on symints is the intended behavior of cudagraphs, but we can move those after the other checks.

**Comment by ezyang** [comment]
looks like someone fixed this??
