### ISSUE TITLE
UNSTABLE Lint / Test `run_test.py` is usable without boto3/rockset

### ISSUE THREAD

**Issue by amjames** [pytorch/pytorch#137101]
Linter jobs seem to be failing across every? branch right now with the same message. 

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
@amjames what's the error message? And I've fixed something similar yesterday, haven't I? (I.e. rebase should help)

**Comment by amjames** [comment]
@malfet See here https://hud.pytorch.org/pr/pytorch/pytorch/136055#30918747463

**Comment by malfet** [comment]
@amjames that was fixed yesterday by https://github.com/pytorch/pytorch/pull/137023 rebase should help
