### ISSUE TITLE
`nn.Transformer().generate_square_subsequent_mask()` doesn't care `set_default_device()` and `set_default_dtype()`

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#137186]
### 🐛 Describe the bug

[nn.Transformer().generate_square_subsequent_mask()](https://pytorch.org/docs/stable/generated/torch.nn.Transformer.html#torch.nn.Transformer.generate_square_subsequent_mask) doesn't care [set_default_device()](https://pytorch.org/docs/stable/generated/torch.set_default_device.html) and [set_default_dtype()](https://pytorch.org/docs/stable/generated/torch.set_default_dtype.html), getting `cpu` and `float32` instead of `cuda` and `float64` as shown below. *I know I can set `device` and `dtype` manually to `nn.Transformer().generate_square_subsequent_mask()`:

```python
import torch
from torch import nn

torch.set_default_device(device='cuda')
torch.set_default_dtype(d=torch.float64)

tran = nn.Transformer().generate_square_subsequent_mask(sz=3)
tran.device, tran.dtype
# (device(type='cpu'), torch.float32) # Here
```

In addition, [torch.tensor()](https://pytorch.org/docs/stable/generated/torch.tensor.html) cares `set_default_device()` and `set_default_dtype()` as shown below:

```python
import torch

torch.set_default_device(device='cuda')
torch.set_default_dtype(d=torch.float64)

my_tensor = torch.tensor([0., 1., 2.])
my_tensor.device, my_tensor.dtype
# (device(type='cuda', index=0), torch.float64)
```

### Versions

```python
import torch

torch.__version__ # 2.4.1+cu121
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by janeyx99** [comment]
Marking hipri tentatively for silent incorrectness

**Comment by ezyang** [comment]
Shouldn't be too hard to fix probably

**Comment by FinlaySanders** [comment]
I'd love to contribute.  Will have a look :)

**Comment by FinlaySanders** [comment]
Have found the problem.
