### ISSUE TITLE
FSDP and Distributed check pointing create memory overhead with micro batch size 1

### ISSUE THREAD

**Issue by samsja** [pytorch/pytorch#137151]
### 🐛 Describe the bug

Distributed check pointing create memory overhead with micro batch size 1. Here is a minimal reproducible example

```python
import gc
import os
import warnings
import torch
import torch.distributed as dist


from torch.distributed.fsdp import (
    FullyShardedDataParallel as FSDP,
    MixedPrecision,
    ShardingStrategy
)
import torch.distributed.checkpoint as dcp
from torch.distributed.checkpoint.state_dict import get_model_state_dict

import torch.nn.functional as F


local_rank = int(os.environ["LOCAL_RANK"])
torch.cuda.set_device(local_rank)


dist.init_process_group()


class FakeTransformer(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.embedding = torch.nn.Embedding(32_000, 1024)
        self.linear = torch.nn.Sequential(*[torch.nn.Linear(1024, 1024) for _ in range(50)])
        self.lm_head = torch.nn.Linear(1024, 32_000)

    def forward(self, x):
        x = self.embedding(x)
        for layer in self.linear:
            x = layer(x)
        x = self.lm_head(x)
        return x

model = FakeTransformer().cuda()

model = FSDP(module=model, mixed_precision=MixedPrecision(param_dtype=torch.bfloat16))#, sharding_strategy=ShardingStrategy.SHARD_GRAD_OP)

optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)


MICRO_BS = 1


def save(model):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        states = {"model": get_model_state_dict(model)}
        dcp.save(state_dict=states, checkpoint_id="checkpoint")
    
    torch.cuda.empty_cache()
    gc.collect()

for i in range(5):
    batch = torch.randint(0, 32_000, (MICRO_BS, 2048)).to(torch.cuda.current_device())
    logits = model(batch)
    
    logits = logits.view(-1, logits.size(-1))
    targets = batch.view(-1)
    loss = F.cross_entropy(logits, targets) # fake target

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if i == 2 or i == 4:
        if local_rank == 0:
            print("save")
        save(model)

    cuda_info = torch.cuda.memory_stats("cuda")
    max_active = cuda_info["active_bytes.all.peak"]
    max_reserved = cuda_info["reserved_bytes.all.peak"]

    if local_rank == 0:
        print(f"Step {i+1}: max_active: {max_active/1e9:.2f} GiB, max_reserved: {max_reserved/1e9:.2f} GiB")

dist.destroy_process_group()
```

```
torchrun --nproc_per_node=2 file.py 
W1001 19:45:04.082000 140067924980160 torch/distributed/run.py:779] 
W1001 19:45:04.082000 140067924980160 torch/distributed/run.py:779] *****************************************
W1001 19:45:04.082000 140067924980160 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1001 19:45:04.082000 140067924980160 torch/distributed/run.py:779] *****************************************
Step 1: max_active: 1.38 GiB, max_reserved: 2.61 GiB
Step 2: max_active: 1.75 GiB, max_reserved: 2.74 GiB
save
Step 3: max_active: 1.75 GiB, max_reserved: 3.37 GiB
Step 4: max_active: 1.76 GiB, max_reserved: 3.37 GiB
save
Step 5: max_active: 1.76 GiB, max_reserved: 3.37 GiB
```

Notice how the max_reservered increases after the first saving.

The issue exists for micro-batch sizes between 1 and 7. With 8 there is no memory overhead.

Comment out the garbace collector and the empty_cache does not change the results.

### Versions

torch version 2.4.1.

Issue was reproduced on 3090 and h100 sxm

cc @zhaojuanmao @mrshenli @rohan-varma @awgu @fegin @kwen2501 @chauhang @LucasLLC @MeetVadakkanchery @mhorowitz @pradeepfn

**Comment by samsja** [comment]
Here is a bit more context on the issue:

It seems to be a bug at least from pytorch 2.0. (tested all versions in the middle)

Swapping DDP with FSDP produces the same bug (The base model is not problematic)

The checkpointing is not directly the problem, calling `get_model_state_dict` is. Calling `model.state_dict` is problematic as well. 

**The memory overhead only appear after the backward post save**

**Comment by awgu** [comment]
Perhaps this is simply because for FSDP1, we must do all-gather and reshard for sharded state dict saving. cc: @fegin

**Comment by samsja** [comment]
> reshard for sharded state dict saving

but its still not clear to me why there is not memory increase when using micro_bs >= 8

**Comment by awgu** [comment]
caching allocator probably :)

**Comment by awgu** [comment]
Sorry to give you more details, you can take a look at the memory snapshot to understand this better.
```diff
+import pickle
...
dist.init_process_group()
+torch.cuda.memory._record_memory_history()
...
for i in range(5):
    ...
+    snapshot = torch.cuda.memory._snapshot()
+    with open(f"snapshot_{i}_{local_rank}.pickle", "wb") as f:
+        pickle.dump(snapshot, f)
```
You can look at the allocations corresponding to the state dict all-gather and reshard, which I highlighted with a red box in the step 2 rank 0 snapshot:
<img width="1491" alt="Screenshot 2024-10-02 at 3 53 11 PM" src="https://github.com/user-attachments/assets/f837c8ca-5658-4a3f-976a-6309ed23c717">
I suspect that with larger microbatch size, then some segments allocated for activations can fit the allocations from all-gather/reshard, avoiding allocating new segments and increasing reserved memory.

By the way, using expandable segments can help:
```
PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" torchrun --nproc_per_node=2 repro_fsdp.py
```

Expandable segments helps:
```
NCCL version 2.21.5+cuda12.0
Step 1: max_active: 1.38 GiB, max_reserved: 2.62 GiB
Step 2: max_active: 1.75 GiB, max_reserved: 2.67 GiB
save
Step 3: max_active: 1.75 GiB, max_reserved: 2.88 GiB
Step 4: max_active: 1.75 GiB, max_reserved: 2.88 GiB
save
Step 5: max_active: 1.75 GiB, max_reserved: 2.88 GiB
```

P.S. Using FSDP2 also helps 😆  (also with expandable segments)
```
Step 1: max_active: 1.38 GiB, max_reserved: 1.97 GiB
Step 2: max_active: 1.75 GiB, max_reserved: 2.62 GiB
save
Step 3: max_active: 1.75 GiB, max_reserved: 2.64 GiB
Step 4: max_active: 1.75 GiB, max_reserved: 2.64 GiB
save
Step 5: max_active: 1.75 GiB, max_reserved: 2.64 GiB
```

**Comment by awgu** [comment]
Even more details: The way I read the snapshot to understand the allocator state and fragmentation is, for example:

<img width="1715" alt="Screenshot 2024-10-02 at 3 57 35 PM" src="https://github.com/user-attachments/assets/1089433b-0b7a-4ab8-a865-0a79e45eac1c">

switch tabs:

<img width="455" alt="Screenshot 2024-10-02 at 3 59 30 PM" src="https://github.com/user-attachments/assets/3ab210b4-44cf-4480-829c-e4b0f1489704">

search for copied address (via command + f) and look for the `alloc` event:

<img width="1709" alt="Screenshot 2024-10-02 at 4 00 14 PM" src="https://github.com/user-attachments/assets/ff847d98-d579-47b2-a68f-9e4f5f672f31">

now can see all segments allocated at the time of that allocation

A few notes:
- When expandable segments is disabled, one segment (rectangle) is backed by one `cudaMalloc`. The segment can have 0+ blocks in it allocated. If a segment shows white, then that means that that memory is not actively used, but the existence of the segment contributes to the reserved memory. In my understanding, `torch.cuda.empty_cache()` can only free segments that have 0 active allocations in it.
- When expandable segments is enabled, there should be 1 segment per CUDA stream. The segment will expand (and possibly contract) via different CUDA APIs (`cuMemCreate_`, `cuMemRelease_`, `cuMemMap_`).
- If you have a lot of unused parts of segments (white) at the point of peak memory, then that is a sign that you are suffering from fragmentation. Generally, expandable segments can help.
- Using more reserved memory without OOM-ing is not inherently a bad thing, but it is good to understand what causes higher reserved memory.

**Comment by samsja** [comment]
oh wow, thanks @awgu for all the details it's really helpful.

Will try the `expandable_segments` as well as fsdp2

**Comment by awgu** [comment]
will close for now since we have some understanding of what the issue was
feel free to reopen if there are more issues
