### ISSUE TITLE
Full precision display of long tensors

### ISSUE THREAD

**Issue by mdouze** [pytorch/pytorch#13714]
## 🚀 Feature

It would be nice if long tensors were displayed in full precision instead of scientific notation. 

## Motivation

This is the default way that numpy displays int tensors

## Pitch

When I call 
```
(train_labels != train_labels_0).sum()
```
I want a count, but I get `tensor(2.7653e+05)` (on Torch 0.5.0a0+61a15cb). This is particularly annoying for 1-component tensors like here. And it is even more annoying because torch's scientific display format keeps few (5) digits.

## Alternatives

convert the tensor to numpy prior to display

**Comment by vishwakftw** [comment]
This seems to be fixed on `master`. Could you please update your version of PyTorch and check?

**Comment by mdouze** [comment]
If `torch.tensor([123456], dtype=torch.int64)` does display all digits, then the issue can be closed (sorry, I can't upgrade right now).

**Comment by vishwakftw** [comment]
```python
>>> import torch
>>> torch.tensor([123456], dtype=torch.int64)
tensor([123456])
>>> torch.__version__
'1.0.0a0+2698625'
```

I think it seems to work as expected now.
