### ISSUE TITLE
[Bug] RandomCrop(padding), list error

### ISSUE THREAD

**Issue by dori2063** [pytorch/pytorch#13719]
## To Reproduce

1. I'm following https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html 
2. And I changed 
      trainloader.dataset.transform = transforms.Compose([
                                         transforms.RandomCrop(size=32, padding=[1,1,1,1]),            
                                         transforms.RandomHorizontalFlip(),transforms.ToTensor(),
                                         transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
3. Error apeared in \torchvision\transforms\transforms.py .. line 411
self.padding > 0 do not work, because I inserted list.

4. Isn't it bug?

## Environment

 - PyTorch Version : 0.4.1
 - torchvision Version : 0.2.1
 - OS (e.g., Linux): window, anaconda, spyder, prompt
 - Python version: 3.6

**Comment by soumith** [comment]
bug reports to torchvision go here https://github.com/pytorch/vision

It is indeed a bug in `torchvision` v0.2.1, and is fixed on `torchvision` master. It'll be part of the next release.
