### ISSUE TITLE
SymmetricMemory can silently corrupt data when all-to-all followed by all-gather

### ISSUE THREAD

**Issue by lw** [pytorch/pytorch#137171]
### 🐛 Describe the bug

This picture shows a potential timeline of two nodes doing an all-to-all followed by an all-gather, where one node takes too long to recv the data in the all-to-all, leading to the other node going ahead and overwriting the data that's being copied.
![image](https://github.com/user-attachments/assets/81891931-c910-48b0-88f7-27dd8421043e)

The fundamental issue is that these ops have a barrier after the data has been written, in order for the other ranks to wait before reading, but the ops are _missing_ a barrier after the data has been read, in order for the other ranks to wait before overwriting.

### Versions

PyTorch 2.5.0-rc6 from the `pytorch-test` conda channel, built for CUDA 12.4.

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @ptrblck @msaroufim

**Comment by lw** [comment]
CC @yifuwang

**Comment by awgu** [comment]
closed in https://github.com/pytorch/pytorch/pull/137199 I think
