### ISSUE TITLE
Bug in scatter_add_ 

### ISSUE THREAD

**Issue by tanaka-jp** [pytorch/pytorch#13717]
I am using pytorch 0.4.1 .

The scatter_add_  works different from cpu to gpu.

============================

import torch
x = torch.rand(2, 5)
torch.ones(3, 5).scatter_add_(1, torch.tensor([[1], [2]]), x)

tensor([[1.0000, 1.8184, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.3166, 1.0000, 1.0000],
        [1.0007, 1.0000, 1.0000, 1.0000, 1.0000]])

x = x.to(torch.device('cuda:0'))
torch.ones(3, 5).scatter_add_(1, torch.tensor([[1], [2]]), x)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #4 'src'

============================

The cpu mode is bug which is not the same as document.
But I think it is more convenient.

**Comment by zou3519** [comment]
This is a user error: 

> x = x.to(torch.device('cuda:0'))
torch.ones(3, 5).scatter_add_(1, torch.tensor([[1], [2]]), x)

torch.ones(3, 5) is creating a CPU tensor, but x is a CUDA tensor. This error message is complaining about mismatched devices.

**Comment by tanaka-jp** [comment]
My examle is wrong. Sorry.
This is the correct one.

======================================
import torch
x = torch.rand(2, 5).to(torch.device('cuda:0'))
x2 = torch.ones(3, 5).to(torch.device('cuda:0'))
x3 = torch.tensor([[1], [2]]).to(torch.device('cuda:0'))
x2.scatter_add_(1, x3, x)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: invalid argument 3: Index tensor must have the same size as input tensor. at c:\programdata\miniconda3\con
da-bld\pytorch_1533090623466\work\aten\src\thc\generic/THCTensorScatterGather.cu:208


x = torch.rand(2, 5).to(torch.device('cpu'))
x2 = torch.ones(3, 5).to(torch.device('cpu'))
x3 = torch.tensor([[1], [2]]).to(torch.device('cpu'))
x2.scatter_add_(1, x3, x)
tensor([[1.0000e+00, 1.2632e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.9192e+00, 1.0000e+00, 1.0000e+00],
        [1.1930e+30, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00]])
======================================

**Comment by Kailianghu** [comment]
I meet the similar problem on scatter_add_ using on GPU
I have tested the same input  to the scatter_add_ function will produce no same output on when using on GPU(1e -6 difference), but get the same output when using CPU

**Comment by soumith** [comment]
@Kailianghu 1e-6 difference shouldn't be a bug -- it's within floating point error

**Comment by soumith** [comment]
sure, but that's irrelevant. on GPU it's doing a parallel algorithm and the order of adds will be different. on CPU it'll be same order.

**Comment by Kailianghu** [comment]
> sure, but that's irrelevant. on GPU it's doing a parallel algorithm and the order of adds will be different. on CPU it'll be same order.

hi, soumit,  i have notice that if  i use torch.Tensor.scatter_add_() , the result will not be reproducible,
same code run twice and get a different result on GPU. how can i solve the reproducible problem when  use torch.Tensor.scatter_add_() on GPU?

**Comment by soumith** [comment]
@Kailianghu no, it is not easy to solve this problem, as scatter_add_ uses atomicAdd on GPU side which is non-deterministic

**Comment by Kailianghu** [comment]
@soumith  does some other function can do the same thing as scatter_add_ , because i implemented an algorithm(DeepStack), I want to get a deterministic result, which I can evaluate its perform.

**Comment by Kailianghu** [comment]
@soumith I have found if the data is double rather than float the scatter_add_ is deterministic
