### ISSUE TITLE
Env var to shut up "for more info run with TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL"

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#137159]
### 🐛 Describe the bug

When the envvar is set, we wouldn't print the help text and only the main payload

### Versions

main

cc @chauhang @penguinwu @bobrenjc93

**Comment by readmyname95** [comment]
Hi I am interested at this one. Can I help for this question?
