### ISSUE TITLE
Something like mark_unbacked but only does size oblivious

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#137100]
### 🐛 Describe the bug

Let's say you have some code where you need the inputs to not 0/1 specialize. Today, we tell you to do `torch._dynamo.mark_unbacked` to avoid 0/1 specialization. But doing this actually triggers two *orthogonal* mechanisms:

* You opt into the alternate size oblivious semantics, which allows you to avoid doing specializations on 0/1 in many situations
* You say no guards allowed on this value at all

But the second is not at all necessary! For example, if I have:

```
def f(x):
  if x.size(0) >= 10:
    return x + x
  else:
   return x * 3
```

If I didn't want x to 0/1 specialize, I might still be perfectly happy to install a guard `u0 >= 10`. Now, if I'm using mark_unbacked to avoid situations where I'd have to compile exponentially many kernels, I'd have to make sure that I don't actually trigger too many of these guards, but this is something I'd like be more than happy to solve for at some later point in time.

Sort of related to hybrid unbacked SymInts.

### Versions

main

cc @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @bobrenjc93

**Comment by ezyang** [comment]
@Microve mentioned to me a problem https://interncache-all.fbcdn.net/manifold/tlparse_reports/tree/logs/aps-ig_fm_v4_shrunk-4dc43f8c1d/attempt_5/version_0/rank_0/1_25_0/recompile_reasons_428.json which potentially could benefit from this (assuming they actually manage to mark_unbacked it)

**Comment by ezyang** [comment]
**WARNING:** Thinking out loud ahead.

This is actually a bit difficult to create a coherent semantics for. The problem is that when you allow for peeking at hints, you can potentially end up with symbolic expression evaluations that are inconsistent with size oblivious (in stock size oblivious with unbacked symints, you will always be "internally consistent" because you never can guard).

Here's an example. Suppose we have:

```
# zs0 is size oblivious, hint = 1
b1 = guard_size_oblivious(zs0 == 1)
b2 = True if zs0 == 1 else False
```

By size oblivious semantics, `guard_size_oblivious(zs0 == 1)` is always False. But if we actually trigger a guard on this in the conventional way, the fact that its hint is 1 means that we would actually report b2 as True. This doesn't seem like good semantics.

The next though I had in this situation was, well, if someone passes me a size oblivious value which is 0/1, let me force its hint to be something else, say 2. But with a hint of two, I could in fact *force specialization* on the value being 2, which is bad because the value isn't actually 2, it's 1!

So, this brings me to another idea we had in the past, for a different context: what if we maintain a "hint set"? A hint set generalizes the concept of hint so that instead of being one value, it is multiple values. The intention in the previous (unrelated) context is to suppose we encounter an optional optimization that requires `s0 % 4 == 0`, where Inductor will only apply the optimization if this equation is statically known to be true. A hint set would let us be more aggressive with here, where we would check that the formula would satisfies all the hints; if it did, we'd proceed anyway with the guard. Hint set would be computed via automatic dynamic.

OK, so the idea here would be to maintain a hint set, so instead of having a `hint = 1`, we'd want something like `hint_set = {1, 2}`. Except that putting two in the hint set is not actually good; what if you have a size oblivious program but it only works for odd integers, then you'd want a hint set like `{1, 3}` because we truly need a different compilation for the 2 case. Abstractly, we could imagine that we maintain an infinite set of integers specifying all the possible hints this program could have taken. This set gets reduced as we apply runtime asserts. Suppose that we now need to do a guard and peek at the hint. In an ideal, mathematical sense, we would want to run the guard in question on the set of all hints. This would result in a new set of hints that would be consistent with the evaluation of the guard at the true hint. So long as this set contains at least one element besides 0/1, we are OK and can proceed. The idea is this semantics can abstractly "discover" what the morally equivalent value that can be used as a stand-in for 0/1 is, and then we simply argue that size oblivious handling of 0/1 is equivalent that stand-in value.

Now, actually maintaining an infinite set of integers won't fly for implementation. We can't ask the user for the stand-in value because they often don't know (and I want these size oblivious integers for automatic dynamic). A simpler way to do it is always use 2 as the stand-in hint. Now, we ONLY raise GuardOnDataDependent error when we request a non size-oblivious guard where the behavior at 2 and the behavior at 1 is inconsistent. This breaks the size oblivious program that only works for odd integers, but that's a weird thing to do anyway so whatever.

So, concretely, here is what is proposed:

1. A size oblivious shape variable has a hint, but we attempt to treat as an unbacked variable
2. If we would raise a GuardOnDataDependent exception, we instead peek at its hint. If its hint is not 0/1, we evaluate the hint directly. If the hint is 0/1, we evaluate the hint at that value, but we ALSO evaluate the hint at 2. If the evaluations are inconsistent, we raise anyway. (NB: This is kind of similar to propagate real tensors! Perhaps there should be an extra warning there when the evaluations are inconsistent.)

cc @bobrenjc93 @laithsakka @jansel @Chillee

**Comment by laithsakka** [comment]
we have similar issue with backed size oblivious, while we could solve it with this approach, 
it could be not ideal for some case, 

n some situations even if hinted eval and size oblivios eval diverge it could be ok. 

Ex: we hit a non material contig check, we do not want to specialize for contig, 
but in this approach we would due to divergence.
