### ISSUE TITLE
[torch.addmm] [torch.cat] Abnormal random output when using torch.compile()

### ISSUE THREAD

**Issue by shaoyuyoung** [pytorch/pytorch#137254]
### 🐛 Describe the bug

When I use `torch.compile()` to compile a model like below, the output is **random tensor** but actually they should be **zero**. 
I made some ablations which are write in the comment

### Error logs

<details>
<summary>click here to view the error log</summary>

```
----------original model----------
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
----------compiled model----------
tensor([[10.7629,  9.2306, 10.7629,  9.2306],
        [ 6.0779,  6.1903,  6.0779,  6.1903]])
```
</details>

### Minified repro

```python
import torch

class Model(torch.nn.Module):

    def forward(self, x):
        s1 = torch.addmm(x, x, x, beta=0.0, alpha=0.0)
        s2 = torch.addmm(x, x, x, beta=0.0, alpha=0.0)
        return torch.cat((s1, s2), -1)  # If dim=0, the res is OK!


x = torch.randn(2, 2)
test_inputs = [x]

func = Model().to('cuda')  # If I use CPU, the result is same
compiled_func = torch.compile(func, backend="inductor")  # backend="cudagraphs" is OK

print("-" * 10 + "original model" + "-" * 10)
print(func(*test_inputs))

print("-" * 10 + "compiled model" + "-" * 10)
print(compiled_func(*test_inputs))

```

### Versions

<details>
<summary>click here to view the version env</summary>
Collecting environment information...
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 16.0.1
CMake version: version 3.26.0
Libc version: glibc-2.31

Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-196-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.6.68
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 560.35.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      40 bits physical, 48 bits virtual
CPU(s):                             20
On-line CPU(s) list:                0-19
Thread(s) per core:                 1
Core(s) per socket:                 20
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
Stepping:                           7
CPU MHz:                            2499.998
BogoMIPS:                           4999.99
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          640 KiB
L1i cache:                          640 KiB
L2 cache:                           80 MiB
L3 cache:                           16 MiB
NUMA node0 CPU(s):                  0-19
Vulnerability Gather data sampling: Unknown: Dependent on hypervisor status
Vulnerability Itlb multihit:        KVM: Vulnerable
Vulnerability L1tf:                 Mitigation; PTE Inversion
Vulnerability Mds:                  Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:             Mitigation; PTI
Vulnerability Mmio stale data:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:             Mitigation; IBRS
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; IBRS; IBPB conditional; STIBP disabled; RSB filling; PBRSB-eIBRS Not affected; BHI SW loop, KVM SW loop
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch topoext cpuid_fault invpcid_single pti ssbd ibrs ibpb fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat umip pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.12.1
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] triton==3.0.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
</details>

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by eellison** [comment]
Issue was that the cat mm planning didnt pass along the alpha, beta args. Fixed by deleting that code path in  https://github.com/pytorch/pytorch/pull/132554.

**Comment by yinxinyang100** [comment]
Sorry to disturb you, but I discovered an interesting phenomenon when I try your repro. I find that if I use `print()` in the codes compiled, the bug won't happen yet. I don't know whether it is a characteristic of the function `torch.compile()` and whether it can help you.
### Repro
```python
import torch

class Model(torch.nn.Module):

    def forward(self, x):
        s1 = torch.addmm(x, x, x, beta=0.0, alpha=0.0)
        s2 = torch.addmm(x, x, x, beta=0.0, alpha=0.0)
        print(s1, '\n', s2)
        return torch.cat((s1, s2), -1)  # If dim=0, the res is OK!


x = torch.randn(2, 2)
test_inputs = [x]

func = Model().to('cuda')  # If I use CPU, the result is same
compiled_func = torch.compile(func, backend="inductor")  # backend="cudagraphs" is OK

print("-" * 10 + "original model" + "-" * 10)
print(func(*test_inputs))

print("-" * 10 + "compiled model" + "-" * 10)
print(compiled_func(*test_inputs))
```
### Result
```txt
----------original model----------
tensor([[0., 0.],
        [0., 0.]]) 
 tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
----------compiled model----------
tensor([[0., 0.],
        [0., 0.]]) 
 tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
```

**Comment by shaoyuyoung** [comment]
@yinxinyang100 
Hi, thanks for your attention.
It's very interesting! 
As eellison above you said. 


> Fixed by deleting that code path

I think when you `print` `s1` and `s2`. The code path is `implicitly` deleted?

More details maybe can be found in the PR #132554

**Comment by yinxinyang100** [comment]
@shaoyuyoung 
OK, sure, I see. I have tried it just now. In pytorch-nightly, it has been fixed and there is no difference now. Thank you!
