### ISSUE TITLE
onnx_graph_to_caffe2_net takes a model, not a graph

### ISSUE THREAD

**Issue by dllehr81** [pytorch/pytorch#13726]
## 🐛 Bug

I'm not sure if the naming was intentional or not.  But in https://github.com/pytorch/pytorch/blob/master/caffe2/python/onnx/backend.py#L910

A function named `onnx_graph_to_caffe2_net` takes a model, instead of a specific graph.  

## To Reproduce

make call to `onnx_graph_to_caffe2_net` with the model.graph instead of the model

For example

`init_net, predict_net = Caffe2Backend.onnx_graph_to_caffe2_net(onnx_model.graph, device="CPU")`

The error you will get is 
`onnx.onnx_cpp2py_export.checker.ValidationError: The model does not have an ir_version set properly.`

As the graph doesn't have a value `ir_version`, the model does.

The correct behavior would be to call 
`init_net, predict_net = Caffe2Backend.onnx_graph_to_caffe2_net(onnx_model, device="CPU")`

Which works, but the function name may is still misleading.

**Comment by Nimitz14** [comment]
I'm guessing you did the conversion for android? Could you get the model to run?

**Comment by dllehr81** [comment]
Actually I was just trying a simple pytorch to caffe2 test, documented here
https://github.com/onnx/tutorials/blob/master/tutorials/CorrectnessVerificationAndPerformanceComparison.ipynb

I experienced a second issue with 
`caffe2_time = benchmark_caffe2_model(init_net, predict_net)`

The error was 
```
RuntimeError: [enforce fail at operator.cc:46] blob != nullptr. op Conv: Encountered a non-existing input blob: 0
```
which appears to be caused by the fact that `benchmark_caffe2_model` creates a new workspace and tries to call `ws.CreateNet(init_net)` without passing in any input blobs.

**Comment by liute62** [comment]
> Actually I was just trying a simple pytorch to caffe2 test, documented here
> https://github.com/onnx/tutorials/blob/master/tutorials/CorrectnessVerificationAndPerformanceComparison.ipynb
> 
> I experienced a second issue with
> `caffe2_time = benchmark_caffe2_model(init_net, predict_net)`
> 
> The error was
> 
> ```
> RuntimeError: [enforce fail at operator.cc:46] blob != nullptr. op Conv: Encountered a non-existing input blob: 0
> ```
> which appears to be caused by the fact that `benchmark_caffe2_model` creates a new workspace and tries to call `ws.CreateNet(init_net)` without passing in any input blobs.

I experienced the same issue!
