### ISSUE TITLE
Allow passing CUDA stream to the NCCL collectives (specially the functional collectives)

### ISSUE THREAD

**Issue by mayank31398** [pytorch/pytorch#137390]
### 🚀 The feature, motivation and pitch

Currently, I dont see any way to run a NCCL collective on a custom stream.
This is a big limitation and leading frameworks like vLLM have completely ditched PyTorch distributed API and use their own NCCL wrappers like here: https://github.com/vllm-project/vllm/blob/a95354a36ee65523a499b3eb42f70a4a0ea4322d/vllm/distributed/device_communicators/pynccl.py#L104

Is it possible to run the NCCL collectives on the stream that is set by the user context in PyTorch?
This would be a great addition.

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by awgu** [comment]
I think @yifuwang had some concern regarding how this would affect the semantics in the `torch.compile` stack.

@mayank31398 could you share more why you want to run the collective on a user-specified stream for us to understand the motivation?

**Comment by kwen2501** [comment]
Following @awgu's question --
If the motivation is to run multiple collectives in parallel (by using multiple streams), this may disappoint you:
NCCL would internally serialize those collectives if they are issued to the same communicator.

That means, currently the only way to achieve concurrent collectives is to create multiple communicators, i.e multiple ProcessGroups in PyTorch's term.

If you want to overlap compute with communication, there is the `async_op=True` flag for the collective APIs today.

Please let us know if there are other limitations we failed to think of.

**Comment by mayank31398** [comment]
I dont think thats true if 1 op is across nodes and another is within node.
Ic ould be wrong about this.

**Comment by wconstab** [comment]
@mayank31398 are you specifically referring to P2P ops?

The reason I ask is because P2P ops already fall into a special case.

For P2P ops, ProcessGroupNCCL already creates one cuda stream per P2P peer rank.  That means if you are rank0 and you want to send to rank1 (e.g. in-node) and also send to rank 10 (e.g. another node), there will be a separate cuda stream and nccl_comm object for these operations automatically, so they will be parallelized.

For collective ops, if you want to do an in-node collective and a cross node collective, the only way to do that in pytorch is to create 2 process group objects, with different sets of ranks.  Then once you do that, each pg already has its own separate stream internally, so again you would get overlap.

One more thing:  though not technically what you asked for, you can get a mostly equivalent thing by doing 
```
with my_stream()
   # this call will record a cuda event (e_begin) on 'my_stream' and then synchronize 'the process_group's stream' against that event.  Then it will enqueue the kernel on the process_group's stream, and record another cuda event (e_end) on the process_group's stream.
   work = dist.all_reduce(..., async_op=True)
   
   # this call will synchronize 'my_stream' against 'e_end'
   work.wait()
```

Under the hood, we use a separate stream.  But due to the stream-synchronization, it would look equivalent to using 'my_stream' in most ways.  The exception would be if you exit the 'my_stream' context before calling 'work.wait()' and then enqueue other collectives on the process group.

**Comment by mayank31398** [comment]
oh I see @wconstab this makes sense.
I was not referring to p2p ops.
feel free to close this issue.


btw as a side question: is there any plan on supporting async NCCL ops with torch compile.
I tried this and I found out that if you use the functional collectives, if you are in a torch compile region, PT immediately triggers a wait operation on the ACT.

**Comment by wconstab** [comment]
> btw as a side question: is there any plan on supporting async NCCL ops with torch compile.
I tried this and I found out that if you use the functional collectives, if you are in a torch compile region, PT immediately triggers a wait operation on the ACT.

cc @yf225 @yifuwang @bdhirsh to add more detail, hopefully there is a doc or issue to link to as well.  But in short, there are plans.  Current state is I think if you pass an ACT _into_ a  compiled region, it will do put a wait_tensor at the beginning of the dynamo graph, but inductor is allowed to reorder it for maximal overlap.  If compile wants to return an ACT, i'm not sure if that is (yet) supported.  Also not sure how good the inductor reordering it.

> oh I see @wconstab this makes sense.
I was not referring to p2p ops.
feel free to close this issue.

OK- closing. thanks for following up.  And I take it to mean that you are unblocked now and can get the parallelization you want?  Please feel free to reopen if there is some case that we aren't able to support well today.

**Comment by kwen2501** [comment]
> I dont think thats true if 1 op is across nodes and another is within node. I could be wrong about this.

That is a multi-communicator case. Today that case can achieve comm-comm concurrency with the `async_op=True` flag.
For example:
```
work1 = dist.all_reduce(x1, group=intra_group, async_op=True)
work2 = dist.all_reduce(x2, group=inter_group, async_op=True)
# The two all-reduce will overlap in CUDA profiler
work1.wait()
y1 = func(x1)
work2.wait()
y2 = func(x2)
```

**Comment by bdhirsh** [comment]
> I tried this and I found out that if you use the functional collectives, if you are in a torch compile region, PT immediately triggers a wait operation on the ACT.


yep, we will immediately trigger a wait after the collective when the collective is being invoked from inside a compiled region.

Compile will end up capturing a graph that looks something like:


x = torch.ops.c10d_functional.all_gather(local_x)
# synchronization shows up in the graph immediately after the collective
x = c10d_functional.wait_tensor(x)

It’s then up to the compiler (inductor) to reorder the wait_tensor ops in the graph for better overlap
