### ISSUE TITLE
[binary] cuSPARSELt increases manywheel binary size signifantly

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#137374]
### 🐛 Describe the bug

Related to CusparseLt integration PR: https://github.com/pytorch/pytorch/pull/134022
Looks like size increased significantly from verison 0.5.2 to 0.6.2
<img width="1087" alt="Screenshot 2024-10-04 at 3 59 06 PM" src="https://github.com/user-attachments/assets/16547feb-9770-4fe2-b2d5-167b1add5f66">

Proposal Move CusparseLt out of the pytorch wheel package. And bring down our Linux Manywheel package size. From 860mb to ~700MB. Limit for pypi package is 1GB.

1. Skip bundling it here: https://github.com/pytorch/builder/blob/main/manywheel/build_cuda.sh#L126
2. Add pypi depdendency here: https://github.com/pytorch/pytorch/blob/main/.github/scripts/generate_binary_build_matrix.py#L79
3. This is pypi package for this library: https://pypi.org/project/nvidia-cusparselt-cu12/
4. Make sure version of cusparse installed here: https://github.com/pytorch/pytorch/blob/main/.ci/docker/common/install_cuda.sh#L33 matches with the one from pypi

### Versions

2.6.0

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim

**Comment by malfet** [comment]
Why can't we use the dependencies here?  https://pypi.org/project/nvidia-cusparselt-cu12/ seems to be available, isn't it?

**Comment by Skylion007** [comment]
@malfet Historically because they didn't have binaries for cu11, but we are dropping support in the next version anyway?

**Comment by Skylion007** [comment]
@atalman I'd like to remind us of https://github.com/pytorch/pytorch/issues/93955 this solution if we are worried about binary size. Saw up to 10-20% binary size reduction when I last tried this locally.

**Comment by atalman** [comment]
Reopening to check looks like binary size is still around 900mb

**Comment by nWEIdia** [comment]
It has PTX on. Does release turn on PTX as well? 

See the artifacts in https://github.com/pytorch/pytorch/actions/runs/11827498285 (test PR), the size without PTX is around 730MB

**Comment by nWEIdia** [comment]
Both CUDA 12.4 and CUDA 12.6 by default (targeting night) were built with PTX on. Release should NOT use PTX but that is release specific change.

**Comment by malfet** [comment]
Indeed PTX size is 300Mb:
```
$ python ~/git/pytorch/builder/analytics/cubinsizes.py libtorch_cuda.so 
Analyzing libtorch_cuda.so
.nv_fatbin size 1.0GiB
  sm_50: 113.4MiB
  sm_60: 113.9MiB
  sm_70: 86.2MiB
  sm_75: 82.0MiB
  sm_80: 117.5MiB
  sm_86: 116.1MiB
  ptx_90: 306.1MiB
  sm_90: 121.6MiB
__nv_relfatbin size 0.0B
```

**Comment by nWEIdia** [comment]
For reference: https://[download.pytorch.org/whl/nightly/cu124/torch-2.6.0.dev2024920%2Bcu124-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu124/torch-2.6.0.dev2024920%2Bcu124-cp310-cp310-linux_x86_64.whl) was 1.1G+

**Comment by malfet** [comment]
Ok, perhaps we can close this one again, but I want to understand what is the motivation for building nightlies with PTX, but stripping it for release. Perhaps we should strip PTX from cuda-12.4 nighlies to keep an eye on the actual binary size

**Comment by nWEIdia** [comment]
Background on adding PTX: https://github.com/pytorch/builder/pull/1932

**Comment by nWEIdia** [comment]
Since cuda 12.6 added PTX, I will send a PR to remove PTX from cuda 12.4 nightly

**Comment by atalman** [comment]
Nightly validations: https://github.com/pytorch/test-infra/actions/runs/12910501492/job/36000666004
test validations: https://github.com/pytorch/test-infra/actions/runs/12835591635/job/35795355730#step:4:13
Binary size ~733mb
