### ISSUE TITLE
Creating sparse tensor inside child process deadlocks when using numpy from conda-forge 

### ISSUE THREAD

**Issue by ostrokach** [pytorch/pytorch#13739]
## 🐛 Bug

When using PyTorch in combination with numpy from the conda-forge channel, creating a sparse tensor in a child process after an `os.fork` leads to a deadlock.

## To Reproduce

Create conda environment:

```bash
conda create -n pytorch-deadlock -c conda-forge \
    conda-forge::numpy \
    pytorch::pytorch-nightly-cpu=1.0.0.dev20181108=py3.6_cpu_0
source activate pytorch-deadlock
```

Create a `demo.py` file to demonstrate the problem:

```python
import os
import time

import torch


def check():
    indices = torch.LongTensor([[0, 1, 1], [2, 0, 2]])
    values = torch.FloatTensor([3, 4, 5])
    tensor = torch.sparse_coo_tensor(indices, values, torch.Size([2,4]))


def main():
    check()  # Note: this line is required to reproduce behavior!
    pid = os.fork()
    if pid:
        print(f"Starting check pid: {pid}")
        check()
        print(f"Done check pid: {pid}")
        time.sleep(10)
    else:
        print(f"Starting check pid: {pid}")
        check()
        print(f"Done check pid: {pid}")
        time.sleep(10)


if __name__ == '__main__':
    main()
```

Run `demo.py`:

```
$ python demo.py
Starting check pid: 0
Starting check pid: 85604
Done check pid: 85604
```

The forked process never gets past the `check()` step. 

## Expected behavior

The expected output is shown below. This is the output that is produced when using numpy from the defaults channel.

```
$ python demo.py
Starting check pid: 84364
Starting check pid: 0
Done check pid: 84364
Done check pid: 0
```

## Environment

```
PyTorch version: 1.0.0.dev20181108
Is debug build: No
CUDA used to build PyTorch: None

OS: CentOS Linux 7 (Core)
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch-nightly-cpu       1.0.0.dev20181108     py3.6_cpu_0    pytorch
```

**Comment by weiyangfb** [comment]
I can't repro this issue via your script

**Comment by ostrokach** [comment]
Did you check on a computer that has multiple cores?

I created a GitLab repo with a CI script which can reproduce the bug: https://gitlab.com/ostrokach/pytorch-deadlock.

However, the bug is only reproduced when the docker image is ran on a machine with more that one core (see: [119515407](https://gitlab.com/ostrokach/pytorch-deadlock/-/jobs/119515407)). It runs fine on a machine with only one core (see: [119522205](https://gitlab.com/ostrokach/pytorch-deadlock/-/jobs/119522205)). Using numpy from the `defaults` channel works fine on both cases (see [119515408](https://gitlab.com/ostrokach/pytorch-deadlock/-/jobs/119515408) and [119522206](https://gitlab.com/ostrokach/pytorch-deadlock/-/jobs/119522206), respectively).

**Comment by mruberry** [comment]
Closing due to age; if this still occurs on the current version of PyTorch please reopen and update the issue
