### ISSUE TITLE
index_select_backward with bfloat16 data much slower under compile

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#137425]
internal xref: https://fb.workplace.com/groups/1075192433118967/permalink/1516427078995498/

repro:
```
import torch

@torch.compile
def f(x, y):
    return torch.index_select(x, 0, y)

x = torch.randn(2000, 384, dtype=torch.bfloat16, device='cuda', requires_grad=True)
y = torch.ones(713268, dtype=torch.int64, device='cuda')

x_ref = x.clone().detach().requires_grad_(True)
out = f(x_ref, y)
out.sum().backward()
out = f(x_ref, y)
out.sum().backward()

from torch.profiler import ProfilerActivity

with torch.profiler.profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True, with_stack=True) as prof:
    out = f(x, y)
    out.sum().backward()
prof.export_chrome_trace("trace3.json")
```

In eager, `index_select`'s backward formula eventually calls `aten.index_add_`, which has a gpu execution time of of 14.28ms (from my local trace: `jf download GBAaiRv6VrKZTCUFAKJfCTIiU4ZhbsIXAAAz --file "trace_eager.json"`)

Under compile, the corresponding backward kernel takes 740ms (local trace: `jf download GOdNkBulizdS89QEAL31CnAlyRgQbsIXAAAz --file "trace_compile.json"`)

It looks like:

(1) we decompose `aten.index_add` into `aten.index_put` ([code](https://github.com/pytorch/pytorch/blob/main/torch/_decomp/decompositions.py#L2726))

(2) inductor needs to run the aten fallback for `aten.index_put_` if its input has `bfloat16` dtype ([code](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/utils.py#L1836))

And it looks like our ATen implementation for `index_put_` is much slower than `index_add_` (when there is a lot of contention (due to repeated indices?). In the example repro above I use an index tensor full of 1s for maximum contention.

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by bdhirsh** [comment]
I'm sure if we should:

(1) figure out why the `aten.index_put_` kernel is so much slower than `aten.index_add_` here and try to figure the eager ATen kernel

(2) don't try to improve `aten.index_put_` and have inductor avoid that decomposition when it knows it needs to fall back.

**Comment by mlazos** [comment]
@eellison and I discussed this - there is a third option: for bf16 if we emit the right asm instructions in triton we won't need to fallback any more. I will prototype this in the next few days.
