### ISSUE TITLE
c10d FileStore - Race among processes to create the file if the file doesn't exist

### ISSUE THREAD

**Issue by teng-li** [pytorch/pytorch#13750]
Repro by 8 processes single node training
```
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
Using device: 3
Traceback (most recent call last):
  File "/private/home/tengli/github_issues/nccl_hang/main_distributed_dp_nodataloader.py", line 213, in <module>
    main()
  File "/private/home/tengli/github_issues/nccl_hang/main_distributed_dp_nodataloader.py", line 116, in main
    broadcast_buffers=False)
  File "/private/home/tengli/pytorch/torch/nn/parallel/distributed.py", line 150, in __init__
    self.broadcast_bucket_size)
  File "/private/home/tengli/pytorch/torch/nn/parallel/distributed.py", line 266, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: open(/private/home/tengli/new_store_test.txt): No such file or directory
Using device: 0
Using device: 5
Using device: 2
Using device: 1
Using device: 6
Using device: 4
Using device: 7
```

One process says it's not able to open the file

**Comment by SsnL** [comment]
If helpful, I use lockf to worked around the bug
```py
                f = open(state.distributed_init_file, 'a+')

                # lockf interpretation
                #   1st byte: the truncating lock, exclusively grabbed by the
                #             truncating process
                #             NB: never release this lock
                #   2st byte: the joining lock, sharedly grabbed by all after
                #             truncating to ensure truncating finishes before
                #             init process group on all ranks
                #             NB: never release this lock

                # lockf API: lockf(file, option, length, start)
                truncating_proc = False
                try:
                    # grab both bytes exclusively
                    fcntl.lockf(f, fcntl.LOCK_EX | fcntl.LOCK_NB, 2, 0)
                    truncating_proc = True
                except IOError:
                    pass
                if truncating_proc:
                    f.truncate(0)

                # truncating proc: downgrad to shared lock on 2nd byte
                # others         : grab a shared lock on 2nd byte
                fcntl.lockf(f, fcntl.LOCK_SH, 1, 1)
                assert os.path.getsize(state.distributed_init_file) == 0

                def release_distributed_file_init_handle():
                    fcntl.lockf(f, fcntl.LOCK_UN)
                    f.close()

                atexit.register(release_distributed_file_init_handle)  # well, not necessary
```

**Comment by pietern** [comment]
@SsnL This depends on locking byte ranges, which I think is some kind of POSIX extension that is not guaranteed to work on NFS (or at least some older version of NFS). I really like the trick though :+1: 

I don't see how this trick can work around the issue that @teng-li describes here though, only how it ensures you can reuse the same file across multiple runs.

**Comment by pietern** [comment]
@teng-li Does this trigger with torch.distributed.launch, or torch.multiprocessing.spawn, or... I'm trying to repro but some additional info here would be helpful.

**Comment by teng-li** [comment]
```
for i in {0..7}; do (nohup python -u ~/github_issues/nccl_hang/main_distributed_dp_nodataloader.py -j 32 -a resnet50 --print-freq 1 --batch-size 192 --world-size 8 --dist-url 'file:///private/home/tengli/new_store_test.txt' /datasets01/imagenet_full_size/061417/ --epochs 1 --dist-backend 'nccl' --rank $i --fp16 &); done
```

**Comment by pietern** [comment]
The file store is hosted on an NFS v3 share here.

**Comment by pietern** [comment]
@SsnL You mention you use that to workaround a bug, which bug is that?

**Comment by SsnL** [comment]
@pietern Oh I thought this issue is talking abut having to delete the init file before using file system init. Probably I was wrong..

**Comment by pietern** [comment]
@SsnL This one is not, but I think you bring up a valid point. Having to delete the file before using is not great and the lock + truncate trick you posted fixes it. The problem I think with the byte range locks is that usually the file store will be used on NFS (as is the case in this example) and byte range locks on NFS are sparingly supported to my knowledge, if at all.

**Comment by pietern** [comment]
A naive search leads me to https://docstore.mik.ua/orelly/networking_2ndEd/nfs/ch11_02.htm, containing:

>  NLM supports only advisory whole file and byte range locking, and until NFS Version 4 is deployed, this means that the NFS environment cannot support mandatory whole file and byte range locking. The reason goes back to how mandatory locking interacts with advisory fcntl calls.

**Comment by pietern** [comment]
From http://nfs.sourceforge.net/:

>  NFS Version 4 introduces support for byte-range locking and share reservation. Locking in NFS Version 4 is lease-based, so an NFS Version 4 client must maintain contact with an NFS Version 4 server to continue extending its open and lock leases. 

Another resource on the various mechanisms for file locking: https://gavv.github.io/blog/file-locks/

**Comment by SsnL** [comment]
@pietern :( That is unfortunate. Thanks for doing the research though! Would it be possible to
1. Once the proc group is initialized, change some flag in the init file.
2. When initializing proc group with file, if the file exists and says that the init is already done (from 1), then 
    1. rank 0 truncates it / clears it.
    2. other ranks enter a read-sleep loop until it reads a valid file.

**Comment by teng-li** [comment]
I am working on a fix now

**Comment by teng-li** [comment]
Good to close
