### ISSUE TITLE
Avoid generating guards for  conjunction expression involving dynamic shapes if the whole expression yields false regardless of guards satisfaction..

### ISSUE THREAD

**Issue by laithsakka** [pytorch/pytorch#137513]
if we have something like:
if(x.size() ==b.size() and false):
    do ...
    
 
and X.size() is a SymInt, then we do add guards even though we do not take the branch.
```
import torch
from torch import Tensor
from typing import List, Type

@torch.compile(fullgraph=True, dynamic=True, backend="inductor")
def f(x):
   if(x.size()[0]==10 and False):
      return x
   return x*2

inputs = [
                    torch.rand(10, 10),
                    torch.rand(100, 100),
                    torch.rand(10, 2),
                    torch.rand(1000, 1000),
                ]
for i in inputs:
   f(i)
```
TORCH_LOGS="recompiles, guards"  python example.py 
```
Ne(L['x'].size()[0], 10)  # if(x.size()[0]==10 and False):  # example.py:15 in f (_dynamo/variables/tensor.py:1124 in evaluate_expr)
```
How did I encounter this?

I was doing something in functionalization that is similar to the above and it was coausing recompilations (guards not added due to user code), instead of False I had other conditions that do not have symbols and turn out false.

for now I re-ordered the check but it would be nice to have better solutions so other folks dont hit the issue. 

cc @ezyang @chauhang @penguinwu @bobrenjc93 @zou3519

**Comment by ezyang** [comment]
This is a bit difficult. Let me modify your sample slightly:

```
import torch
from torch import Tensor
from typing import List, Type

y = False

def side_effect():  # NEW
  global y
  y = True

@torch.compile(fullgraph=True, dynamic=True, backend="inductor")
def f(x):
   if(x.size()[0]==10 and side_effect() and False):  # NEW
      return x
   return x*2

inputs = [
                    torch.rand(10, 10),
                    torch.rand(100, 100),
                    torch.rand(10, 2),
                    torch.rand(1000, 1000),
                ]
for i in inputs:
   f(i)
```

Now, I have a situation where the value of the size in question doesn't matter for whether or not we take the branch, but it DOES affect the short circuiting behavior of the "and", and short circuiting has an observable effect.

It is hard for me to imagine an algorithm that can drop the guard in your example, but NOT drop the guard in this case.

**Comment by laithsakka** [comment]
seems like this does it lol 
```
def parallel_or(*args: BoolLikeType) -> BoolLikeType:
    """
    Evaluate the logical OR of several arguments, avoiding guarding on
    unbacked SymInts if another argument is definitely True.
    """
    if any(statically_known_true(a) for a in args):
        return True
    if any(definitely_true(a) for a in args):
        return True
    return any(args)


def parallel_and(*args: BoolLikeType) -> BoolLikeType:
    """
    Evaluate the logical FALSE of several arguments, avoiding guarding on
    unbacked SymInts if another argument is definitely False.
    """
    if any(statically_known_true(torch.sym_not(a)) for a in args):
        return False
    if any(definitely_false(a) for a in args):
        return False
    return all(args)

```

**Comment by laithsakka** [comment]
seems like at least for the auto_functionalize use case that I have I can use
```
def parallel_and(*args: BoolLikeType) -> BoolLikeType:
    """
    Evaluate the logical FALSE of several arguments, avoiding guarding on
    unbacked SymInts if another argument is definitely False.
    """
    if any(statically_known_true(torch.sym_not(a)) for a in args):
        return False
    if any(definitely_false(a) for a in args):
        return False
    return all(args)
 ```
 while this does not exactly do what I have above in the example, it is sufficient for the use case here , statically_known should be good  https://github.com/pytorch/pytorch/blob/main/torch/_higher_order_ops/auto_functionalize.py#L93

**Comment by ezyang** [comment]
yes, if we're talking internal tests in functorch tracing you have more latitude. My statement here is purely about user facing python code
