### ISSUE TITLE
Actually no-op custom ops when torch::deploy is on

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#137536]
some of the decorators assume the custom op is registered, we need to audit them

cc @ezyang @gchanan @kadeng @msaroufim @dzhulgakov @chauhang @penguinwu @bdhirsh @yf225

**Comment by malfet** [comment]
I guess it's related to https://github.com/pytorch/pytorch/pull/136910

**Comment by zou3519** [comment]
probably hi-pri for almost causing a SEV
