### ISSUE TITLE
When will pytorch support pip install python3.13(no gil) version on macos and windows? (linux nightlies already work)

### ISSUE THREAD

**Issue by splinter21** [pytorch/pytorch#137699]
### 🚀 The feature, motivation and pitch

More effective utilization of multi-core

cc @seemethere @malfet @osalpekar @atalman

**Comment by ezyang** [comment]
@colesbury

**Comment by colesbury** [comment]
You can install nightly PyTorch on Linux with nogil (free threading) support. For example:

`pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu`

For other configurations, see the "Preview (nightly)" install instructions at https://pytorch.org/.

(You can also use [`uv`](https://github.com/astral-sh/uv) if you prefer faster installs.)

cc @albanD who has done a lot of work to enable this

**Comment by albanD** [comment]
That is correct, nightlies linux support 3.13t, you can follow the usual instructions on the getting started page to get that!
We are still working on getting macos and windows binaries (more complex within our Infra).

We are not planning on providing 3.13t binaries for 2.5 that is about to be released as we were not able to put in all the fix needed  by the branch cut last month.

Note that while basic enablement is there and most things should not horribly fail. We don't have full testing yet. Please report any issues you encounter!

**Comment by atalman** [comment]
@colesbury @splinter21 3.13t binaries are available for both cpu and cuda linux binaries:
https://hud2.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=3_13t

```
pip3 install torch --index-url https://download.pytorch.org/whl/nightly/cu121
pip3 install torch --index-url https://download.pytorch.org/whl/nightly/cu124
pip3 install torch --index-url https://download.pytorch.org/whl/nightly/cu118
pip3 install torch --index-url https://download.pytorch.org/whl/nightly/cpu
```

**Comment by albanD** [comment]
Closing this one in favor of https://github.com/pytorch/pytorch/issues/130249 where there is a summary for all platforms and binary releases.
