### ISSUE TITLE
ImportError: No module named transforms

### ISSUE THREAD

**Issue by Needrom** [pytorch/pytorch#1376]
something wrong with import torchvision
```
import torchvision
import torchvision.transforms as transforms
```
Traceback (most recent call last):
  File "torchvision.py", line 3, in <module>
    import torchvision
  File "/Users/liangguoyu/PycharmProjects/pytorch/torchvision.py", line 4, in <module>
    import torchvision.transforms as transforms
ImportError: No module named transforms

**Comment by soumith** [comment]
you have a file called torchvision.py for some reason. delete it or change your pythonpath to ignore it.

**Comment by yannadani** [comment]
Hey,

I have the same problem persisting when I import torchvision. I have no other file by the same name. 

`import torch
from torch.utils.data.dataset import Dataset
from torch.utils.data import DataLoader
from torchvision import transforms`

ImportError  Traceback (most recent call last)
<ipython-input-6-3baf6837d8f1> in <module>()
      8 from torch.utils.data.dataset import Dataset
      9 from torch.utils.data import DataLoader
---> 10 from torchvision import transforms

ImportError: No module named torchvision

**Comment by ngimel** [comment]
Do you have torchvision installed (it is a separate package)?

**Comment by y3mnx** [comment]
pip Install torchvision 

try this

**Comment by kunaalgupta** [comment]
from data import BaseTransform,VOC_CLASSES as labelmap
this is not working

**Comment by p4vlos** [comment]
> pip Install torchvision
> 
> try this

pip install torchvision
