### ISSUE TITLE
CPU_CAPABILITY_NEON isn't defined for PyTorch core builds, only via inductor

### ISSUE THREAD

**Issue by swolchok** [pytorch/pytorch#137704]
### 🐛 Describe the bug

We have code in aten/src/ATen/cpu/vec/ gated on CPU_CAPABILITY_NEON, such as https://github.com/pytorch/pytorch/blob/bcf15d1bb415f5df30037a2c3f3ea9375e812e54/aten/src/ATen/cpu/vec/vec256/vec256_convert.h#L302 . Nothing except torchinductor appears to define this macro, and it's certainly not defined during `python setup.py install` on my Mac (as determined by putting an `#error` in one of the blocks gated on `#if defined(CPU_CAPABILITY_NEON)`.

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.7 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.3)
CMake version: version 3.30.4
Libc version: N/A

Python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.7-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] executorch==0.4.0a0+9d9cda0
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] optree==0.12.1
[pip3] torch==2.6.0a0+gitccca3de
[pip3] torchao==0.5.0+git0916b5b
[pip3] torchaudio==2.4.0.dev20240716
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0.dev20240716
[conda] executorch                0.4.0a0+9d9cda0          pypi_0    pypi
[conda] numpy                     2.0.1                    pypi_0    pypi
[conda] numpy-base                1.26.4          py312he047099_0
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] torch                     2.6.0a0+gitccca3de          pypi_0    pypi
[conda] torchao                   0.1                      pypi_0    pypi
[conda] torchaudio                2.4.0.dev20240716          pypi_0    pypi
[conda] torchsr                   1.0.4                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20240716          pypi_0    pypi

cc @malfet @seemethere @snadampal @milpuz01 @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by swolchok** [comment]
looks like in order to fix this we just need to check NEON_FOUND / ASIMD_FOUND as set here:
https://github.com/pytorch/pytorch/blob/bcf15d1bb415f5df30037a2c3f3ea9375e812e54/cmake/Modules/FindARM.cmake#L11

 and if either is true, add NEON to [the list in cmake/Codegen.cmake](https://github.com/pytorch/pytorch/blob/bcf15d1bb415f5df30037a2c3f3ea9375e812e54/cmake/Codegen.cmake#L267)

**Comment by swolchok** [comment]
alternatively, *should* we be using CPU_CAPABILITY_NEON as a gate? it's implied by __aarch64__ IIUC.

**Comment by malfet** [comment]
It's a bit weird, but unsure why this is a problem. All ARMv8 are capable of running NEON, so this should be enabled by default, but inductor can generate serial code unless CPU_CAPABILITY_NEON is defined by 
https://github.com/pytorch/pytorch/blob/a919742149601888c793447c1a6ab262979f1dde/torch/_inductor/cpu_vec_isa.py#L154
But VecConvert is also only used by Inductor, so...
