### ISSUE TITLE
Pytorch Python style guide/conventions for contributors

### ISSUE THREAD

**Issue by redwrasse** [pytorch/pytorch#137709]
### 📚 The doc issue

There's a fair bit of style variation in Python code across modules in Pytorch. 

Is there a style guide or implicit conventions available for Python code? This would help knowing what's worth improving (and justify raising an issue/opening a PR), and encourage contributors to work across modules originally developed by different individuals/periods of time.

There are tips in the contributing guide (https://pytorch.org/docs/stable/community/contribution_guide.html#), though not finding style conventions.

Some example style questions:

- camel case vs lower case: `testFoo()` vs `test_foo`
- prefer table-driven tests?
- naming conventions for real vs generalized complex operators (exampe: transpose vs (generalized) hermitian conjugate).
- what properties of an API method should be documented, and tested?

**Comment by ezyang** [comment]
* Lower case overwhelmingly preferred per https://peps.python.org/pep-0008/#function-and-variable-names
* If there's pre-existing table driven infrastructure like OpInfo, do use it. But we also have a lot of one offs. Do what is easiest.
* Most of our code is intended to work with complex numbers, so internal framework code should talk about hermitian conjugates
* Not sure I understand, but we overwhelmingly prefer only documenting and testing public API, unit tests for internal functions is not that common

**Comment by redwrasse** [comment]
This is informative, thank you. It sounds like the implicit convention is to follow roughly Pep 8 style guide. 

Concerning complex numbers support, does a given python API method support complex inputs if it doesn't raise an error on complex inputs? Or must it be explicitly specified in documentation that the given API method supports complex inputs, and could otherwise produce a mathematically incorrect output on complex inputs?
