### ISSUE TITLE
if any plan to publish wheel file of pytorch 2.4.1 for python 3.13 in macos 15.0.1

### ISSUE THREAD

**Issue by assassinleo** [pytorch/pytorch#137853]
### 🐛 Describe the bug

hi all
i have upgraded to python 3.13 in my local env(macos 15.0.1), but can not install pytorch 2.4.1
may i know if any plan to publish related wheel file for python 3.13 on macos?
<img width="887" alt="no macos wheel file for python 3 13" src="https://github.com/user-attachments/assets/78e5321c-bc4c-455e-b946-497467af5c5b">

download files(wheel) in pypi: https://pypi.org/project/torch/#files

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 15.0.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.3)] (64-bit runtime)
Python platform: macOS-15.0.1-arm64-arm-64bit-Mach-O
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M2

Versions of relevant libraries:
[pip3] No relevant packages
[conda] Could not collect

cc @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
No, per https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix binaries are not getting re-build with newer versions of dependencies (Python in this case), but upcoming 2.5 should have some experimental Python-3.13 support

**Comment by albanD** [comment]
FYI Added more details for future version support https://github.com/pytorch/pytorch/issues/130249
