### ISSUE TITLE
[CI] pytorchbot -f should not bypass EasyCLA

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#137883]
### 🐛 Describe the bug

A prticular PR had some issues with EasyCLA (for some reason it did not run), when pytorchbot -f was issued, it did merge it, ignoring the EasyCLA failure.

We should fix pytorchbot to never ignore EasyCLA jobs

https://github.com/pytorch/pytorch/pull/137791

### Versions

master

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
It was not the case in the past, so this is clearly a regression. Who issues `merge -f` I wonder?
