### ISSUE TITLE
torch dot function consistent with numpy

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#138]
That would be nice to have the dot function in pytorch consistent with the numpy one:

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation). For N dimensions it is a sum product over the last axis of a and the second-to-last of b.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

So that with:
x = torch.Tensor(5, 3, 4).normal_()
y = torch.Tensor(4, 7).normal_()

x.dot(y) returns a tensor of shape (5, 3, 7)

**Comment by dDua** [comment]
Is there a way to do this currently in pytorch ? I was trying to implement Minibatch discrimination(https://arxiv.org/pdf/1606.03498.pdf) where I need to multiply M1(n x a) with M2(a x b x c) to get M3(n x b x c).

**Comment by fmassa** [comment]
@dDua yes, there is. For your specific case, you can simply merge dimensions 2 and 3 of your M2 matrix, do a matrix multiply, and then reshape the resulting tensor.
```python
r = torch.mm(M1, M2.view(a, -1)).view(n, b, c)
```

**Comment by dDua** [comment]
@fmassa  Thanks for your reply!

**Comment by fmassa** [comment]
This has been fixed via https://github.com/pytorch/pytorch/pull/1563 , if we consider that we should follow the behavior of `numpy.matmul` instead of `numpy.dot`, according to the thread pointed out by @ngimel.

**Comment by DNXie** [comment]
Could anyone tell me where can I find the source code of torch.matmul?

**Comment by ngimel** [comment]
https://github.com/pytorch/pytorch/blob/22506ae71d0982018b9c7db8fa31813772a0c451/aten/src/ATen/native/LinearAlgebra.cpp#L355-L464
