### ISSUE TITLE
AttributeError: Can't pickle local object 'make_opaque_unary_fn.<locals>.OpaqueUnaryFn'

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#138070]
### 🐛 Describe the bug

Full dynamo log at https://github.com/pytorch/pytorch/issues/136797#issuecomment-2408616629

### Error logs

```python 
site-packages/torch/utils/_sympy/interp.py:159] [0/1] failed while executing pow_by_natural([VR[0, int_oo], VR[-1, -1]])
site-packages/torch/_inductor/codecache.py:609] [0/1] Can't pickle
site-packages/torch/_inductor/codecache.py:609] [0/1] Traceback (most recent call last):
site-packages/torch/_inductor/codecache.py:609] [0/1]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 605, in dumps
site-packages/torch/_inductor/codecache.py:609] [0/1]     pickler.dump(obj)
site-packages/torch/_inductor/codecache.py:609] [0/1] AttributeError: Can't pickle local object 'make_opaque_unary_fn.<locals>.OpaqueUnaryFn'
site-packages/torch/utils/_sympy/interp.py:159] [0/1] failed while executing pow_by_natural([VR[0, int_oo], VR[-1, -1]])
```

### Versions

nightly

cc @ezyang @chauhang @penguinwu @bobrenjc93 @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by ezyang** [comment]
Not hard to fix just need to set `__name__` correctly on the metaprogrammed funcs

**Comment by ezyang** [comment]
but tbh I'm not sure why export is pickling these in the first place

**Comment by bhack** [comment]
> but tbh I'm not sure why export is pickling these in the first place

This one is just compile, no export. Or do you mean https://github.com/pytorch/pytorch/issues/136797 ?

**Comment by ezyang** [comment]
Oh it's codecache pickle okey dokey

**Comment by bhack** [comment]
This is why I've commented https://github.com/pytorch/pytorch/issues/136797#issuecomment-2408565197.

Cause if we are not going to emit `pow_by_natural` we don't have the pickle code-cache etc.. So it is a chain of issues with a common root but different side effects that we could be interested to solve in general or not.
Of course if we are not going to not emit anymore  `pow_by_natural`  in the end I am less interested in tracking all of these side issues in my current use case.
