### ISSUE TITLE
The doc of `save()` should say the default value of `pickle_protocol` parameter is `2`

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#138013]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.save.html) of `save()` says the default value of `pickle_protocol` parameter is `DEFAULT_PROTOCOL` as shown below:

> torch.save(..., pickle_protocol=DEFAULT_PROTOCOL, ...)

But `DEFAULT_PROTOCOL` has `2` by default according to [the source code](https://pytorch.org/docs/stable/_modules/torch/serialization.html) as shown below:

```python
...
import copyreg
import pickle
import torch._weights_only_unpickler as _weights_only_unpickler

DEFAULT_PROTOCOL = 2 # Here

LONG_SIZE = struct.Struct('=l').size
INT_SIZE = struct.Struct('=i').size
SHORT_SIZE = struct.Struct('=h').size

...

[[docs]](https://pytorch.org/docs/stable/generated/torch.save.html#torch.save)def save(
    obj: object,
    f: FILE_LIKE,
    pickle_module: Any = pickle,
    pickle_protocol: int = DEFAULT_PROTOCOL,
    _use_new_zipfile_serialization: bool = True,
    _disable_byteorder_record: bool = False
) -> None:
```

### Suggest a potential alternative/fix

So, [the doc](https://pytorch.org/docs/stable/generated/torch.save.html) of `save()` should say the default value of `pickle_protocol` parameter is `2` as shown below:

> torch.save(..., pickle_protocol=2, ...)

cc @svekars @brycebortree @sekyondaMeta @mruberry @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Marking actionable to make this fix
