### ISSUE TITLE
stride after slice op

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#138027]
### 🐛 Describe the bug

@jainapurva and I were debugging some issues related to slice operation in torchao, and found that the stride is not updated after we do slice, is this expected?

```Python
import torch

t = torch.randn(1024, 2048)
# - func: slice.Tensor(Tensor(a) self, int dim=0, SymInt? start=None, SymInt? end=None, SymInt step=1) -> Tensor(a)
print("before slice:", t.shape, t.stride())
# slicing dim=1 with start=0, end=512, step=1
t = torch.ops.aten.slice.Tensor(t, 1, 0, 512)
print("after slice:", t.shape, t.stride())
print("after slice + contiguous:", t.shape, t.contiguous().stride())
```

Output
```Python
before slice: torch.Size([1024, 2048]) (2048, 1)
# here the stride for sliced tensor is (2048, 1), is this expected?
after slice: torch.Size([1024, 512]) (2048, 1)
after slice + contiguous: torch.Size([1024, 512]) (512, 1)
```

### Versions

main

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

**Comment by bdhirsh** [comment]
In this particular example, that looks expected. Slice.tensor(t, 1, 0, 512) will return a 2D tensor, where:

- each row is contiguous (so the inner stride is 1)
- the start of each row is at the same offset as the start of each row in the base tensor (they’re all offset by 2048)

Is the question about whether slice in general is always guaranteed to return a tensor with the same strides?

**Comment by jerryzh168** [comment]
> In this particular example, that looks expected. Slice.tensor(t, 1, 0, 512) will return a 2D tensor, where:
> 
> * each row is contiguous (so the inner stride is 1)
> * the start of each row is at the same offset as the start of each row in the base tensor (they’re all offset by 2048)
> 
> Is the question about whether slice in general is always guaranteed to return a tensor with the same strides?

oh I see, that makes sense, thanks for the explanation.

yeah I was a bit surprised to see that slice did not change the stride at all, 

I understand now it's more of view of the base tensor after slice unless we call contiguous() on it.

**Comment by drisspg** [comment]
@jerryzh168  Do we have assumptions that AQT's data is always contiguous?

**Comment by jerryzh168** [comment]
> @jerryzh168 Do we have assumptions that AQT's data is always contiguous?

no we don't, I think the behavior of AQT should be aligned with normal op

**Comment by drisspg** [comment]
Then I still don't understand why we need to call `contiguous` here: https://github.com/pytorch/ao/blob/d2526126fd064f3a01d864184bf56613ffe9fdb9/torchao/dtypes/affine_quantized_tensor.py#L1141

**Comment by jerryzh168** [comment]
I see, this is a mistake probably, we want to call contiguous() before the kernel, instead of here I think, cc @jainapurva
