### ISSUE TITLE
Huge precision errors in ppc64le tests

### ISSUE THREAD

**Issue by brunoalr** [pytorch/pytorch#1380]
At least these tests fail randomly due to a huge precision error (approximately 1 fail every 100 executions):

`test_Conv1d`:
```
FAIL: test_Conv1d (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_nn.py", line 2330, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/brosa/pytorch/test/common_nn.py", line 571, in __call__
    self._do_test(test_case, module, input)
  File "test/test_nn.py", line 69, in _do_test
    test_case.check_jacobian(module, input, self.jacobian_input)
  File "/home/brosa/pytorch/test/common_nn.py", line 459, in check_jacobian
    PRECISION
AssertionError: 597828.9410372106 not less than or equal to 1e-05
```
`test_Conv2d_groups_thnn`:
```
FAIL: test_Conv2d_groups_thnn (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_nn.py", line 2330, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/brosa/pytorch/test/common_nn.py", line 571, in __call__
    self._do_test(test_case, module, input)
  File "test/test_nn.py", line 69, in _do_test
    test_case.check_jacobian(module, input, self.jacobian_input)
  File "/home/brosa/pytorch/test/common_nn.py", line 459, in check_jacobian
    PRECISION
AssertionError: 512396.96441206516 not less than or equal to 1e-05
```
`test_Conv2d_padding`:

```
FAIL: test_Conv2d_padding (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 2330, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/brosa/pytorch/test/common_nn.py", line 571, in __call__
    self._do_test(test_case, module, input)
  File "test_nn.py", line 69, in _do_test
    test_case.check_jacobian(module, input, self.jacobian_input)
  File "/home/brosa/pytorch/test/common_nn.py", line 459, in check_jacobian
    PRECISION
AssertionError: 1149022.966940353 not less than or equal to 1e-05
```
Summary list of failing NN tests with similat outputs:
```
FAIL: test_Conv1d_groups (__main__.TestNN)
FAIL: test_Conv1d (__main__.TestNN)
FAIL: test_Conv1d_pad1 (__main__.TestNN)
FAIL: test_Conv1d_pad2 (__main__.TestNN)
FAIL: test_Conv1d_stride (__main__.TestNN)
FAIL: test_Conv2d_groups (__main__.TestNN)
FAIL: test_Conv2d_groups_thnn (__main__.TestNN)
FAIL: test_Conv2d (__main__.TestNN)
FAIL: test_Conv2d_no_bias (__main__.TestNN)
FAIL: test_Conv2d_padding (__main__.TestNN)
FAIL: test_Conv2d_strided (__main__.TestNN)
```

I'll update the issue if/when I find more failing tests.

**Comment by apaszke** [comment]
All these tests use `SpatialConvolutionMM` from [THNN](https://github.com/pytorch/pytorch/blob/master/torch/lib/THNN/generic/SpatialConvolutionMM.c). Does `test_torch.py` pass? Maybe it's a bug in `THVector_(fill)` (used [here](https://github.com/pytorch/pytorch/blob/master/torch/lib/THNN/generic/SpatialConvolutionMM.c#L100-L102))? That seems to be the only architecture specific part here.

**Comment by brunoalr** [comment]
I just ran `test_torch.py` 100 times and it passed. I'll take a look at `SpatialConvolutionMM` and `THVector_(fill)` then. Thanks for the info.

**Comment by brunoalr** [comment]
This issue is related to the usage of openmp. For initial tests I commented out some pragmas and the issue was gone. Inspecting closer, I found out that we had to use critical sections.

**Comment by soumith** [comment]
that's interesting. I cant fathom why that section needs to be marked critical, because we made sure that each of the inner code of `#pragma omp` doesn't have another nest of `#pragma omp`. Nice find / fix.

**Comment by brunoalr** [comment]
The problem here is that in the event of two threads calling the methods marked as critical it is possible that a race condition arise when writing to the output variable.

**Comment by pavanky** [comment]
@soumith There's an `addmm` inside the `#pragma omp parallel`, do you think that may cause an issue?

@brunoalr the current fix has a critical around the entirety of the computation inside the loop. Won't that make the entire loop serial in practice ?

**Comment by brunoalr** [comment]
@pavanky I didn't do a performance evalution after that as I am more concerned with correctness at this point and this fixed the issue. 
I'm not an opemp expert, but it seems that you are correct. Perhaps the `critical` pragma should be used on a more granular level.

**Comment by pavanky** [comment]
@brunoalr Either that or remove the `#pragma omp parallel` up top instead of adding a critical section.

**Comment by brunoalr** [comment]
@pavanky should we move this discussion to the PR page instead? https://github.com/pytorch/pytorch/issues/1947
