### ISSUE TITLE
Mergebot often fails to fetch DrCI status

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#138057]
### 🐛 Describe the bug

Noticed following in the [log](https://github.com/pytorch/pytorch/actions/runs/11358848522/job/31594026283):
```
Error fetching https://hud.pytorch.org/api/drci/drci?prNumber=137992 HTTP Error 405: Method Not Allowed
Attempt 0 of 3 to call get_drci_classifications failed with "HTTP Error 405: Method Not Allowed"
Error fetching https://hud.pytorch.org/api/drci/drci?prNumber=137992 HTTP Error 405: Method Not Allowed
Attempt 1 of 3 to call get_drci_classifications failed with "HTTP Error 405: Method Not Allowed"
Error fetching https://hud.pytorch.org/api/drci/drci?prNumber=137992 HTTP Error 405: Method Not Allowed
Attempt 2 of 3 to call get_drci_classifications failed with "HTTP Error 405: Method Not Allowed"
```
It feels like link needs to be updated or something else have gone wrong
cc: @huydhn 

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
Let me take a look.  This might explain some curious instances I have seen so far when the PR had only unrelated failures as reported by Dr.CI while mergebot counted it as a force merge

**Comment by clee2000** [comment]
I think I fixed this in https://github.com/pytorch/test-infra/pull/5793, recent logs seem to be able to fetch Dr. CI https://github.com/pytorch/pytorch/actions/runs/11522466138/job/32078405813
