### ISSUE TITLE
Cross-GPU copies failing silently

### ISSUE THREAD

**Issue by nikitakit** [pytorch/pytorch#13803]
## 🐛 Bug

I'm trying to build a model where different layers are located on different GPU devices. However, any attempt to copy tensors between devices fails silently unless the copy uses the CPU as in intermediate.

## To Reproduce

```python
>>> import torch
>>> torch.cuda.device_count()
2
>>> cuda0 = torch.device('cuda:0')
>>> cuda1 = torch.device('cuda:1')
>>> t = torch.ones(5, device=cuda1)
>>> t
tensor([1., 1., 1., 1., 1.], device='cuda:1')
>>> t.to(cuda0)
tensor([0., 0., 0., 0., 0.], device='cuda:0')
>>> t.cpu().to(cuda0)
tensor([1., 1., 1., 1., 1.], device='cuda:0')
```

In general, any attempt to copy tensors by doing `.to(different_cuda_device)` results in a tensor with the correct device/shape/dtype but where all of the values are set to zero.

## Expected behavior

I would expect `t.to(cuda0)` and `t.cpu().to(cuda0)` to both result in `tensor([1., 1., 1., 1., 1.], device='cuda:0')`.

Alternatively, if there's something wrong with the software setup or I'm not using the API correctly, an error message would be more appropriate than the current behavior of populating the tensor with all-zero values.

## Environment

PyTorch version: 0.4.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Scientific Linux 7.4 (Nitrogen)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80

Nvidia driver version: 384.90
cuDNN version: Could not collect

Versions of relevant libraries:
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    pytorch

**Comment by SsnL** [comment]
I couldn't repro using a master build. However, this is likely environment dependent...

**Comment by ezyang** [comment]
Yeah, I couldn't repro either. Is this a source build of PyTorch or are you using our binaries?

**Comment by nikitakit** [comment]
This is a binary I downloaded. I double-checked an older anaconda environment with pytorch 0.3, and it has the same issue. There is likely something about the machine that's causing this issue, but I can't tell what that might be.

**Comment by ezyang** [comment]
Closing for now, but feel free to reopen if you have more details.
