### ISSUE TITLE
failed while executing int_truediv

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#138069]
### 🐛 Describe the bug

With the last days nightlies this quite spammy message started to appear in the logs
.
```python
ite-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_27), MetaProxy(add_tensor_1)])
[rank1]:W1016 12:11:19.665000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_7), MetaProxy(scalar_tensor_default_7)])
[rank1]:W1016 12:11:19.665000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_7), MetaProxy(scalar_tensor_default_7)])
[rank1]:W1016 12:11:19.665000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_7), MetaProxy(scalar_tensor_default_7)])
[rank1]:W1016 12:11:19.666000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_28), MetaProxy(add_tensor)])
[rank1]:W1016 12:11:19.666000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_3), MetaProxy(scalar_tensor_default_3)])
[rank1]:W1016 12:11:19.666000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_3), MetaProxy(scalar_tensor_default_3)])
[rank1]:W1016 12:11:19.666000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_3), MetaProxy(scalar_tensor_default_3)])
[rank1]:W1016 12:11:19.667000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_29), MetaProxy(add_tensor_1)])
[rank1]:W1016 12:11:19.667000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_7), MetaProxy(scalar_tensor_default_7)])
[rank1]:W1016 12:11:19.667000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_7), MetaProxy(scalar_tensor_default_7)])
[rank1]:W1016 12:11:19.667000 47 site-packages/torch/utils/_sympy/interp.py:159] [0/10] failed while executing int_truediv([MetaProxy(scalar_tensor_default_7), MetaProxy(scalar_tensor_default_7)])
.....
```

### Versions

nightly

cc @ezyang @chauhang @penguinwu @bobrenjc93

**Comment by isuruf** [comment]
Do you have a link to the log?

**Comment by bhack** [comment]
Not the full log. I am following nightly day by day and it appeared only just 2 or 3 days ago same model.

Are you looking for `TORCH_LOGS="+dynamo`?

**Comment by isuruf** [comment]
I was looking for a way to reproduce.

**Comment by bhack** [comment]
I cannot share the model what alternative we have other than the dynamo log?
 Is there a bisector to understand the root cause of this in the source code?

**Comment by isuruf** [comment]
I guess the issue is in `torch/utils/_sympy/reference.py:519`.

**Comment by ezyang** [comment]
So the code here

```
    try:
        if handler_name in ASSOCIATIVE_OPS:
            assert len(args) > 1
            acc = handler(args[0], args[1])
            for i in range(2, len(args)):
                acc = handler(acc, args[i])
            log.debug("%s(%s) -> %s", handler_name, args, acc)
            return acc
        else:
            r = handler(*args)
            log.debug("%s(%s) -> %s", handler_name, args, r)
            return r
    except Exception:
        log.warning("failed while executing %s(%s)", handler_name, args)
        raise
```

can you add this clause before Exception:

```
except NotImplementedError:
  raise
```

I bet it will fix it. And yes, tensorify scalars seems like a culprit

**Comment by ezyang** [comment]
it should also not be hard to write a minimal repro if this is true root cause

**Comment by bhack** [comment]
> except NotImplementedError:
  raise

ok, It seems that we have entered in this new exception.

**Comment by ezyang** [comment]
so that one does suppress it? @bobrenjc93 then that means that all you need to repro is have a float tensor which gets a div done on it triggering the not implemented and then feed it to tensor add or something

**Comment by bhack** [comment]
Yes it seems that we are in the `NotImplementedError` error.

**Comment by bhack** [comment]
Ping-pong

**Comment by bobrenjc93** [comment]
@jgvinholi or @bhack if you could provide me a small repro that'd help speed up the process. Regardless I'll try and get out a fix by EOD today.

**Comment by bobrenjc93** [comment]
@bhack My first attempt at the repro doesn't seem to be spewing those messages.

```r1.py
import torch

def fn(x, y, z):
    return x + (y / 2)

fn_opt = torch._dynamo.optimize("inductor")(fn)

print(fn_opt(torch.randn(3), torch.tensor(0.8), torch.tensor(0.8)))
```

I'm running it with `TORCH_LOGS="+dynamo" python r1.py`

That's why I specifically said a repro would "help speed up the process". No worries if you don't have time, but this is one of those "help me help you cases".

**Comment by bhack** [comment]
If we don't have a bisect tool to identify the root cause in the source code I cannot share the whole code as it is a `torch.compile` of a full model/module

**Comment by jgvinholi** [comment]
Same as @bhack . I am compiling my network in multiple separate blocks with @torch.compile(options=compile_options). I am adding here the compile options I am using if this could help somehow. Also the compilation seems to be slower in this latest release, idk if it is related to the error above. Thank you for your help.

`torch._dynamo.config.cache_size_limit = 10000
import torch._inductor.config

torch._dynamo.config.capture_scalar_outputs = True
compile_options = {
    "TYPE_CHECKING": False,
    "enable_auto_functionalized_v2": True,
    "debug": False,
    "disable_progress": False,
    "verbose_progress": True,
    "fx_graph_cache": True,
    "fx_graph_remote_cache": None,
    "autotune_local_cache": True,
    "autotune_remote_cache": None,
    "force_disable_caches": False,
    "sleep_sec_TESTING_ONLY": None,
    "custom_op_default_layout_constraint": "needs_fixed_stride_order",
    "triton_kernel_default_layout_constraint": "flexible_layout",
    "cpp_wrapper": False,
    "c_shim_version": "2",
    "dce": False,
    "static_weight_shapes": True,
    "size_asserts": True,
    "nan_asserts": False,
    "pick_loop_orders": True,
    "inplace_buffers": True,
    "allow_buffer_reuse": True,
    "memory_planning": False,
    "memory_pool": "intermediates",
    "benchmark_harness": True,
    "epilogue_fusion": True,
    "epilogue_fusion_first": False,
    "pattern_matcher": True,
    "b2b_gemm_pass": False,
    "post_grad_custom_pre_pass": None,
    "post_grad_custom_post_pass": None,
    "joint_custom_pre_pass": None,
    "joint_custom_post_pass": None,
    "pre_grad_custom_pass": None,
    "_pre_fusion_custom_pass": None,
    "split_cat_fx_passes": True,
    "efficient_conv_bn_eval_fx_passes": False,
    "is_predispatch": False,
    "group_fusion": False,
    "batch_fusion": True,
    "pre_grad_fusion_options": {},
    "post_grad_fusion_options": {},
    "reorder_for_locality": True,
    "dynamic_scale_rblock": True,
    "force_fuse_int_mm_with_mul": False,
    "use_mixed_mm": True,
    "fx_passes_numeric_check": {
        "pre_grad": False,
        "precision": 0.0001,
        "num_iterations": 1,
        "requires_optimizer": True,
    },
    "mixed_mm_choice": "heuristic",
    "reorder_for_compute_comm_overlap": False,
    "reorder_for_compute_comm_overlap_passes": [
        "reorder_compute_for_overlap",
        "sink_waits",
        "raise_comms",
    ],
    "reorder_for_peak_memory": False,
    "estimate_op_runtime": "default",
    "intra_node_bw": 300,
    "inter_node_bw": 25,
    "max_autotune": False,
    "max_autotune_pointwise": False,
    "max_autotune_gemm": False,
    "force_same_precision": True,
    "max_autotune_gemm_backends": "ATEN,TRITON",
    "max_autotune_conv_backends": "ATEN,TRITON",
    "max_autotune_gemm_search_space": "DEFAULT",
    "autotune_fallback_to_aten": True,
    "unbacked_symint_fallback": 8192,
    "search_autotune_cache": True,
    "save_args": False,
    "autotune_in_subproc": False,
    "max_autotune_subproc_result_timeout_seconds": 60.0,
    "max_autotune_subproc_graceful_timeout_seconds": 1.0,
    "max_autotune_subproc_terminate_timeout_seconds": 2.0,
    "autotune_multi_device": False,
    "coordinate_descent_tuning": True,
    "coordinate_descent_check_all_directions": True,
    "coordinate_descent_search_radius": 1,
    "autoheuristic_collect": "",
    "autoheuristic_use": "mixed_mm",
    "autoheuristic_log_path": "DEFAULT",
    "layout_opt_default": "1",
    "layout_optimization": True,
    "force_layout_optimization": False,
    "keep_output_stride": True,
    "warn_mix_layout": False,
    "realize_reads_threshold": 4,
    "realize_opcount_threshold": 30,
    "realize_acc_reads_threshold": 8,
    "fallback_random": False,
    "implicit_fallbacks": True,
    "aggressive_fusion": False,
    "debug_fusion": False,
    "benchmark_fusion": False,
    "enabled_metric_tables": "",
    "loop_ordering_after_fusion": False,
    "benchmark_epilogue_fusion": True,
    "max_epilogue_benchmarked_choices": 1,
    "max_fusion_size": 256,
    "max_pointwise_cat_inputs": 8,
    "unroll_reductions_threshold": 8,
    "comment_origin": False,
    "conv_1x1_as_mm": False,
    "split_reductions": True,
    "benchmark_kernel": False,
    "constant_and_index_propagation": True,
    "always_keep_tensor_constants": False,
    "assert_indirect_indexing": True,
    "compute_all_bounds": False,
    "combo_kernels": False,
    "benchmark_combo_kernel": False,
    "combo_kernels_autotune": 1,
    "combo_kernel_allow_mixed_sizes": 1,
    "combo_kernel_foreach_dynamic_shapes": False,
    "joint_graph_constant_folding": True,
    "debug_index_asserts": False,
    "emulate_precision_casts": False,
    "is_nightly_or_source": True,
    "developer_warnings": True,
    "optimize_scatter_upon_const_tensor": True,
    "worker_start_method": "subprocess",
    "_fuse_ddp_communication": False,
    "_fuse_ddp_bucket_size": 25,
    "_fuse_ddp_communication_passes": ["fuse_ddp_with_concat_op", "schedule_comm_wait"],
    "_micro_pipeline_tp": False,
    "compile_threads": 72,
    "global_cache_dir": None,
    "kernel_name_max_ops": 10,
    "shape_padding": True,
    "comprehensive_padding": True,
    "pad_channels_last": True,
    "disable_padding_cpu": True,
    "padding_alignment_bytes": 128,
    "padding_stride_threshold": 1024,
    "pad_outputs": False,
    "bw_outputs_user_visible": True,
    "force_shape_pad": False,
    "permute_fusion": False,
    "profiler_mark_wrapper_call": False,
    "generate_intermediate_hooks": False,
    "debug_ir_traceback": False,
    "_raise_error_for_testing": False,
    "_profile_var": "",
    "profile_bandwidth": False,
    "profile_bandwidth_regex": "",
    "profile_bandwidth_output": None,
    "profile_bandwidth_with_do_bench_using_profiling": False,
    "disable_cpp_codegen": False,
    "freezing": False,
    "freezing_discard_parameters": False,
    "allow_stack_allocation": False,
    "use_minimal_arrayref_interface": False,
    "decompose_mem_bound_mm": False,
    "assume_aligned_inputs": False,
    "unsafe_ignore_unsupported_triton_autotune_args": False,
    "check_stack_no_cycles_TESTING_ONLY": False,
    "cpp.threads": -1,
    "cpp.no_redundant_loops": True,
    "cpp.dynamic_threads": False,
    "cpp.simdlen": None,
    "cpp.min_chunk_size": 4096,
    "cpp.cxx": (
        None,
        "/home/vinholi/miniconda3/envs/chameleon/bin/x86_64-conda-linux-gnu-c++",
    ),
    "cpp.enable_kernel_profile": False,
    "cpp.weight_prepack": True,
    "cpp.inject_relu_bug_TESTING_ONLY": None,
    "cpp.inject_log1p_bug_TESTING_ONLY": None,
    "cpp.vec_isa_ok": None,
    "cpp.descriptive_names": "original_aten",
    "cpp.max_horizontal_fusion_size": 16,
    "cpp.fallback_scatter_reduce_sum": True,
    "cpp.enable_unsafe_math_opt_flag": True,
    "cpp.enable_floating_point_contract_flag": False,
    "cpp.enable_tiling_heuristics": True,
    "cpp.gemm_max_k_slices": 1,
    "cpp.gemm_cache_blocking": None,
    "cpp.gemm_thread_factors": None,
    "cpp.enable_loop_tail_vec": True,
    "triton.cudagraphs": False,
    "triton.cudagraph_trees": True,
    "triton.cudagraph_skip_dynamic_graphs": True,
    "triton.slow_path_cudagraph_asserts": True,
    "triton.cudagraph_trees_history_recording": False,
    "triton.cudagraph_support_input_mutation": True,
    "triton.cudagraph_unexpected_rerecord_limit": 128,
    "triton.cudagraph_dynamic_shape_warn_limit": 50,
    "triton.force_cudagraph_sync": False,
    "triton.force_cudagraphs_warmup": False,
    "triton.fast_path_cudagraph_asserts": False,
    "triton.skip_cudagraph_warmup": False,
    "triton.debug_sync_graph": False,
    "triton.debug_sync_kernel": False,
    "triton.dense_indexing": False,
    "triton.max_tiles": 2,
    "triton.prefer_nd_tiling": False,
    "triton.autotune_pointwise": True,
    "triton.autotune_cublasLt": True,
    "triton.autotune_at_compile_time": None,
    "triton.tiling_prevents_pointwise_fusion": True,
    "triton.tiling_prevents_reduction_fusion": True,
    "triton.unique_kernel_names": True,
    "triton.descriptive_names": "original_aten",
    "triton.persistent_reductions": True,
    "triton.multi_kernel": 0,
    "triton.divisible_by_16": True,
    "triton.min_split_scan_rblock": 256,
    "triton.store_cubin": False,
    "triton.spill_threshold": 16,
    "triton.use_block_ptr": False,
    "triton.inject_relu_bug_TESTING_ONLY": None,
    "triton.codegen_upcast_to_fp32": True,
    "aot_inductor.output_path": "",
    "aot_inductor.debug_compile": False,
    "aot_inductor.debug_dump_consts_bin": False,
    "aot_inductor.debug_intermediate_value_printer": "0",
    "aot_inductor.filtered_kernel_names": None,
    "aot_inductor.serialized_in_spec": "",
    "aot_inductor.serialized_out_spec": "",
    "aot_inductor.use_runtime_constant_folding": False,
    "aot_inductor.force_mmap_weights": False,
    "aot_inductor.package": False,
    "aot_inductor.package_cpp_only": False,
    "aot_inductor.metadata": {},
    "cuda.arch": None,
    "cuda.version": None,
    "cuda.compile_opt_level": "-O3",
    "cuda.enable_cuda_lto": True,
    "cuda.enable_ptxas_info": False,
    "cuda.enable_debug_info": False,
    "cuda.use_fast_math": True,
    "cuda.cutlass_dir": "/home/vinholi/miniconda3/envs/chameleon/lib/python3.11/site-packages/third_party/cutlass",
    "cuda.cutlass_max_profiling_configs": None,
    "cuda.cuda_cxx": None,
    "cuda.cutlass_backend_min_gemm_size": 1,
    "cuda.generate_test_runner": True,
    "cuda.cutlass_op_allowlist_regex": None,
    "cuda.cutlass_op_denylist_regex": "pingpong",
    "rocm.arch": [],
    "rocm.ck_supported_arch": ["gfx90a", "gfx940", "gfx941", "gfx942"],
    "rocm.compile_opt_level": "-O2",
    "rocm.is_debug": False,
    "rocm.save_temps": False,
    "rocm.use_fast_math": True,
    "rocm.flush_denormals": True,
    "rocm.print_kernel_resource_usage": False,
    "rocm.rocm_home": None,
    "rocm.ck_dir": None,
    "rocm.n_max_profiling_configs": None,
    "rocm.use_preselected_instances": False,
    "cpu_backend": "cpp",
    "cuda_backend": "triton",
    "halide.cpu_target": "host",
    "halide.gpu_target": "host-cuda",
    "halide.scheduler_cuda": "Anderson2021",
    "halide.scheduler_cpu": "Adams2019",
    "halide.asserts": False,
    "halide.debug": False,
    "halide.scan_kernels": False,
    "trace.enabled": False,
    "trace.debug_dir": None,
    "trace.debug_log": False,
    "trace.info_log": False,
    "trace.fx_graph": True,
    "trace.fx_graph_transformed": True,
    "trace.ir_pre_fusion": True,
    "trace.ir_post_fusion": True,
    "trace.output_code": True,
    "trace.graph_diagram": False,
    "trace.draw_orig_fx_graph": False,
    "trace.dot_graph_shape": None,
    "trace.log_url_for_graph_xform": None,
    "trace.compile_profile": False,
    "trace.upload_tar": None,
    "trace.log_autotuning_results": False,
    "_save_config_ignore": [
        "trace.upload_tar",
        "post_grad_custom_post_pass",
        "post_grad_custom_pre_pass",
        "joint_custom_pre_pass",
        "joint_custom_post_pass",
        "pre_grad_custom_pass",
    ],
    "_cache_config_ignore_prefix": [
        "trace",
        "cuda.cutlass_dir",
        "worker_start_method",
        "compile_threads",
    ],
    "external_matmul": [],
}`

**Comment by bobrenjc93** [comment]
I serendipitously came across a test case that exhibits this behavior

```
    @xfail_if_triton_cpu
    def test_builtins_round_float_ndigits_pos(self):
        def fn(x, i):
            return x + round(i / 2 * 123.4567, 1)

        cfn = torch.compile(fullgraph=True, dynamic=True)(fn)

        x = torch.zeros(2, device=self.device)
        i = 2

        with torch.no_grad():
            self.assertEqual(cfn(x, i), fn(x, i))
```

Produces 

```
(pytorch) [11:36] devgpu006:/home/bobren/local/pytorch tlp python test/inductor/test_torchinductor_dynamic_shapes.py DynamicShapesCpuTests.test_builtins_round_float_ndigits_pos_dynamic_shapes_cpu
W1018 11:37:07.847000 3263612 torch/utils/_sympy/interp.py:159] [0/0] failed while executing int_truediv([MetaProxy(scalar_tensor_default_1), MetaProxy(scalar_tensor_default_2)])
```
