### ISSUE TITLE
DISABLED __main__.TestFullyShardCompile

### ISSUE THREAD

**Issue by kwen2501** [pytorch/pytorch#138163]
Most of the tests in this TestClass (`TestFullyShardCompile`) failed in [CI machine upgrade](https://github.com/pytorch/pytorch/pull/137161) ([recent examples](https://ossci-raw-job-status.s3.amazonaws.com/log/31640268847)).

Repro:
`python test/distributed/_composable/fsdp/test_fully_shard_compile.py`

Cc: @yf225 

cc @XilunWu @H-Huang @awgu @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by kwen2501** [comment]
Cc: @huydhn 

I am trying to disable a whole test class here as there are quite some tests in it and perhaps too hard to open issue 1 by 1.

Please let me know if the title, i.e. `DISABLED __main__.<TestClass>`, works.

**Comment by huydhn** [comment]
Unfortunately, you can only disable test one at time using issue like this as it is mainly used by the bot and it doesn't need to disable a whole class of tests.  It will be easier if you skip or xfail these tests directly in your PR.  Doing so is better for maintenance too as it is usually not obvious to devs that a test is disabled on CI with an open issue like this.

**Comment by kwen2501** [comment]
Thanks for the quick reply!

Yep I am doing skip in file:
```
@unittest.skip("This test failed during CI machine upgrade and needs to be fixed")
class TestFullyShardCompile(FSDPTest):
```

**Comment by yf225** [comment]
Commented in PR: https://github.com/pytorch/pytorch/pull/137161#pullrequestreview-2374091368. Sorry I think we should fix these tests first before CI machine migration.
