### ISSUE TITLE
HUD CI signals out of date due to S459646

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#138107]
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
*Status could be: preemptive, ongoing, mitigated, closed. Also tell people if they need to take action to fix it (i.e. rebase)*.
Ongoing

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*
HUD and Dr. CI not updating or missing CI signals even though Github says it's done or the job exists

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*
probably see internal sev

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment]
Can someone please confirm that it's limited to just DrCI/HUD? I.e. merge bot should work, `DISABLED` issue works, etc...

**Comment by clee2000** [comment]
Closing this as it is mitigated.  We still need to get the exception approved but HUD is back
