### ISSUE TITLE
DISABLED test_ddp_tp (__main__.DDP_TP_Test)

### ISSUE THREAD

**Issue by kwen2501** [pytorch/pytorch#138144]
This test was disabled because it is failing in [CI machine upgrade](https://github.com/pytorch/pytorch/pull/137161) ([recent examples](https://ossci-raw-job-status.s3.amazonaws.com/log/31640268847)).

cc @XilunWu @H-Huang @awgu @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by yf225** [comment]
Commented in PR: https://github.com/pytorch/pytorch/pull/137161#pullrequestreview-2374091368. Sorry I think we should fix these tests first before CI machine migration.

**Comment by yf225** [comment]
hmm it doesn't seem to work, will add skip decorator for `test_ddp_tp` directly in https://github.com/pytorch/pytorch/pull/138178 instead.

**Comment by janeyx99** [comment]
@kwen2501 Why the reopen?

**Comment by kwen2501** [comment]
Talked with @yf225 . I will defer the decision to @yf225 .
