### ISSUE TITLE
[ROCm] pytorch-nightly container is not updated every night

### ISSUE THREAD

**Issue by OrenLeung** [pytorch/pytorch#138244]
### 🐛 Describe the bug

Hi @powderluv @hliuca ,

Unfortunately the `rocm/pytorch-nightly` container image is not updated every night. As of right now, **the last update from 6 days ago**. Thus users need to add pytorch nightly from pypi inside an older container which may not have the latest dependencies.

<img width="619" alt="image" src="https://github.com/user-attachments/assets/c0fc32b9-7c3e-436d-ab2e-6a49b7e9d91e">

# Current WorkAround

```bash
# use old image as base
FROM rocm/pytorch:rocm6.2_ubuntu22.04_py3.10_pytorch_release_2.3.0 

RUN pip3 uninstall -y torch

RUN pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/rocm6.2
```

### Versions

https://hub.docker.com/r/rocm/pytorch-nightly
<img width="818" alt="image" src="https://github.com/user-attachments/assets/f1d66a20-b545-4dcd-8ca9-9b6c08402257">

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

**Comment by naromero77amd** [comment]
I am closing this issue as I have checked online (https://hub.docker.com/r/rocm/pytorch-nightly/tags) and it is being updated every night now.
