### ISSUE TITLE
torch.histc doesn't work if input tensor on gpu

### ISSUE THREAD

**Issue by karim-ahmed** [pytorch/pytorch#1382]
torch.histc(input,....) works only if input is of type torch.FloatTensor but not torch.cuda.FloatTensor, it gives following error: Type FloatTensor doesn't implement stateless method histc

**Comment by KaiyuYue** [comment]
The reason for this is `torch.histc()` does not yet support the CUDA tensor now. The missing math functions in `THC` can be found [here](https://github.com/torch/cutorch/issues/70) to check out.

**Comment by sjain-stanford** [comment]
I'm facing the same issue - unable to run `torch.histc()` on input of type `torch.cuda.FloatTensor`. 
```
TypeError: Type torch.cuda.FloatTensor doesn't implement stateless method histc
```
When will this be supported in `THC`?

Thanks!

**Comment by johnsrude** [comment]
What is the workaround for this?

**Comment by GuillaumeLeclerc** [comment]
Any update ? Is there anything blocking. It seems to be an operation where GPUs are well suited or am I missing something (especially if min, max are provided) ?

**Comment by mario98** [comment]
Oh no...
I just recently had a case where I needed histograms of a large amount of data and found np.histogram too slow for this. Then I found this torch function which I hoped would accelerate my algorithm but now I must read that exactly this function is not implemented...

I think the priorities are definitely wrong here. On the one side, new version are released which contain breaking changes of already working stuff, but on the other side, important functionality is not implemented at all...

**Comment by GuillaumeLeclerc** [comment]
I'm curious to know about the difficulties of implementing an histogram.
Can we split the data in tiles, Have multiple histograms and then just sum
them ?

**Comment by ezyang** [comment]
There is a bincount PR getting close to completion in  https://github.com/pytorch/pytorch/pull/6688 ; I am told this may be useful for implementing histogram too.

**Comment by themightyoarfish** [comment]
There is [this document](http://developer.download.nvidia.com/compute/cuda/1.1-Beta/x86_website/projects/histogram64/doc/histogram.pdf) from Nvidia describing histogram computation in CUDA, can this be of help?

**Comment by themightyoarfish** [comment]
Also, there is [this Numba implementation,](https://numba.pydata.org/numba-examples/examples/density_estimation/histogram/results.html) not sure if this is helpful. I'm trying to run it on tensors by use of the [cuda array interface](https://numba.pydata.org/numba-doc/dev/cuda/cuda_array_interface.html#cuda-array-interface).

**Comment by themightyoarfish** [comment]
@HekpoMaH It seems to be in progress: https://github.com/pytorch/pytorch/pull/14249

**Comment by zou3519** [comment]
Completed by #15842, it will be in the next release

**Comment by xvdp** [comment]
Thank you for the implementation, it is present in latest release, but there's an inconsistency in behaviour you may want to fix: cuda and cpu return different types
```
import torch
import sys
print(sys.version_info)
print(torch.__version__)
normalcpu = torch.zeros(100, dtype=torch.float32, device="cpu", requires_grad=False).normal_(0., 1.)
h_cpu = torch.histc(normalcpu, bins=10)
normalcuda = normalcpu.to(device="cuda")
h_cuda = torch.histc(normalcuda, bins=10)
print(h_cpu, h_cpu.dtype)
print(h_cuda, h_cuda.dtype)
```

```
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
1.1.0
tensor([ 2.,  5., 15., 26., 17., 18., 10.,  4.,  2.,  1.]) torch.float32
tensor([ 2,  5, 15, 26, 17, 18, 10,  4,  2,  1], device='cuda:0') torch.int64
```

**Comment by ezyang** [comment]
@xvdp I refiled this as a new issue for you https://github.com/pytorch/pytorch/issues/20208

**Comment by xvdp** [comment]
@ezyang thank you. The python "fix" is trivial .to(dtype=...) but imo inconsistencies lead to code rot.
