### ISSUE TITLE
Pytorch1.0  torch/csrc/cuda/nccl.cpp: No such file or directory. 

### ISSUE THREAD

**Issue by lijie6030803** [pytorch/pytorch#13835]
## 🐛 Bug

When I run the distributed training on multi GPU,  the program errors and says  'torch/csrc/cuda/nccl.cpp: No such file or directory'
## To Reproduce

1. run main.py -a alexnet --lr 0.01 --world-size 2 /home/lee
world-size: distributed-flags
2.Thread 25 "python3" received signal SIGSEGV, Segmentation fault.
![image](https://user-images.githubusercontent.com/15613558/48335581-23cfb600-e699-11e8-8da9-29ab15ff8c92.png)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Liunx
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: python3.6
 - CUDA/cuDNN version: CUDA Patch Version 9.2.148.1
 - GPU models and configuration: multi GPU   NVIDIA Corporation GK210GL [Tesla K80]
 - Any other relevant information:

**Comment by pietern** [comment]
No response, closing the issue.
