### ISSUE TITLE
Investigate performance regression in CI benchmarking, caused by #136534

### ISSUE THREAD

**Issue by benjaminglass1** [pytorch/pytorch#138365]
This issue is to track and document progress towards resolving the CPU performance regression in the `functorch_maml_omniglot` benchmark when enabling cpp_wrapper ABI-compatible mode. See https://github.com/pytorch/pytorch/pull/136534 for the changed benchmark threshold value.

To date, I have been unable to reproduce this performance regression outside of the pipeline environment, although investigation is ongoing.

cc: @desertfire 

cc @msaroufim @ezyang @chauhang @penguinwu

**Comment by benjaminglass1** [comment]
Current test script:

```bash
TEST_REPORTS_DIR=$(pwd)/test/test-reports
mkdir -p "$TEST_REPORTS_DIR"

cores=$(echo "$(($(lscpu | grep 'Socket(s):' | awk '{print $2}') * $(lscpu | grep 'Core(s) per socket:' | awk '{print $4}')))")

JEMALLOC_LIB="$(find /usr/lib -name libjemalloc.so.2)"
export LD_PRELOAD="$JEMALLOC_LIB":"$LD_PRELOAD"
export MALLOC_CONF="oversize_threshold:1,background_thread:true,metadata_thp:auto,dirty_decay_ms:-1,muzzy_decay_ms:-1"

# Use Intel OpenMP for x86
IOMP_LIB="$(dirname "$(which python)")/../lib/libiomp5.so"
export LD_PRELOAD="$IOMP_LIB":"$LD_PRELOAD"
export KMP_AFFINITY=granularity=fine,compact,1,0
export KMP_BLOCKTIME=1

export OMP_NUM_THREADS=$cores
end_core=$((cores-1))
export TASKSET="taskset -c 0-$end_core"

model_name=functorch_maml_omniglot
data_type=float32
backend=inductor
export TORCHINDUCTOR_FORCE_DISABLE_CACHES=1
export TORCHINDUCTOR_CPP_WRAPPER=1
#export TORCHINDUCTOR_ABI_COMPATIBLE=0
output_name="$TEST_REPORTS_DIR/inductor_inference_${model_name}_${backend}_${data_type}_dynamic_cpu_smoketest.csv"

$TASKSET python benchmarks/dynamo/torchbench.py \
  --inference --performance --"$data_type" -dcpu -n5000 --only "$model_name" --dynamic-shapes \
  --dynamic-batch-only --freezing --timeout 9000 --"$backend" --output "$output_name"
cat "$output_name"
```

This mimics what's done in the CI pipeline, with the exception of increasing the benchmark duration from 50 reps to 5000 to get an adequately large long-term sample.

**Comment by desertfire** [comment]
cc @jgong5 @EikanWang @chunyuan-w @leslie-fang-intel ,  if you think this is a problem and can reproduce it, let us know.

**Comment by benjaminglass1** [comment]
@desertfire @chunyuan-w I'm going to close this issue in favor of the more complete #138227, since that contains an actual reproduction of the pipeline issue.
