### ISSUE TITLE
Changes in type annotations break downstream code

### ISSUE THREAD

**Issue by lw** [pytorch/pytorch#138478]
### 🐛 Describe the bug

xFormers just upgraded PyTorch to 2.5.0 and mypy in our CI started failing with these errors:
```
xformers/ops/unbind.py:28: error: Unsupported operand types for - ("int" and "SymInt")  [operator]
xformers/ops/unbind.py:28: note: Both left and right operands are unions
xformers/ops/unbind.py:44: error: Unsupported operand types for * ("int" and "SymInt")  [operator]
xformers/ops/unbind.py:44: note: Right operand is of type "int | SymInt"
xformers/ops/unbind.py:44: note: Left operand is of type "int | SymInt"
```
The relevant lines are
https://github.com/facebookresearch/xformers/blob/77c1da7fe5c9a25f613bd4045bb1da4856310aab/xformers/ops/unbind.py#L28
and
https://github.com/facebookresearch/xformers/blob/77c1da7fe5c9a25f613bd4045bb1da4856310aab/xformers/ops/unbind.py#L44

I'm surprised to see that SymInts don't support being added and/or multiplied with regular ints. Are we doing something wrong? Or is this a bug?

### Versions

PyTorch 2.5.0.

cc @ezyang @malfet @xuzhao9 @gramster @chauhang @penguinwu @bobrenjc93

**Comment by Skylion007** [comment]
It's actually the problem where it's confsued that int and Sympy is not supported.... ie. not detecting `__rsub__` etc, right?

**Comment by ezyang** [comment]
Nothing wrong with your code, we must have messed up our type annotations on SymInt

**Comment by lw** [comment]
@ezyang Your PR covers `__rsub__` but our failures seem to hint that `__rmul__` is missing too?

**Comment by kit1980** [comment]
2.5.1 is an emergency patch release to address known large regressions, moving this to 2.6.0

**Comment by ezyang** [comment]
@lw  but class SymInt already has rmul...

```
    def __rmul__(self, other) -> "SymInt":
        raise TypeError("type stub not overridden")
```

To double check, the mul error still repros after that small patch?

**Comment by kit1980** [comment]
For release 2.6 I verified that the fix is present in https://github.com/pytorch/pytorch/blob/v2.6.0-rc9/torch/__init__.py
