### ISSUE TITLE
XPU wheel link not available

### ISSUE THREAD

**Issue by iori2333** [pytorch/pytorch#138416]
### 📚 The doc issue

In [Getting Started on Intel GPU](https://pytorch.org/docs/stable/notes/get_start_xpu.html), it states that binary release wheels for Linux/Windows can be installed from [https://download.pytorch.org/whl/xpu](https://download.pytorch.org/whl/xpu), which is not accessible:
```
> pip3 install torch --index-url https://download.pytorch.org/whl/xpu
Looking in indexes: https://download.pytorch.org/whl/xpu
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

### Suggest a potential alternative/fix

Add hint stating that release wheels are not available currently, or make wheel link accessible.

cc @seemethere @malfet @osalpekar @atalman @svekars @brycebortree @sekyondaMeta @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by ZhaoqiongZ** [comment]
Hi @malfet , the updated link in this #137479 is already cherry-picked to releases/2.5, but somehow the article in the website documentation is not updated yet. Is there any further steps to make it updated correctly?

**Comment by iori2333** [comment]
> Hi @iori2333 , please try pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/test/xpu

Thanks! This works for me.

**Comment by svekars** [comment]
Fixed in stable: https://pytorch.org/docs/stable/notes/get_start_xpu.html
