### ISSUE TITLE
DISABLED test_dynamo_trace_use_training_state (__main__.TestFullyShardCompile)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#138409]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22distributed%2F_composable%2Ffsdp%2Ftest_fully_shard_compile.py%3A%3ATestFullyShardCompile%3A%3Atest_dynamo_trace_use_training_state%22%5D)).

I see that you are disabling some failing distributed tests in trunk like https://github.com/pytorch/pytorch/issues/138397.  This one is another failing on ROCm

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

**Comment by fduwjj** [comment]
maybe @yf225 do you mind taking a look, also cc: @kwen2501
