### ISSUE TITLE
The calculation process of key_padding_mask does not match the document description

### ISSUE THREAD

**Issue by sealoongleft** [pytorch/pytorch#138566]
### 📚 The doc issue

https://github.com/pytorch/pytorch/issues/137887#issue-2585710320

Technical experts, this is the question I raised. The description in the document does not match what I actually tested. Please kindly provide an answer when you have free time. Thank you very much.

### Suggest a potential alternative/fix

Thank you very much to all the experts, as I myself have not fully understood the mysteries involved. I hope the experts can provide guidance
```[tasklist]
### Tasks
```

**Comment by sealoongleft** [comment]
please help me

**Comment by colesbury** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions:[ https://discuss.pytorch.org/](https://discuss.pytorch.org/)
