### ISSUE TITLE
PyTorch doc should have a dark theme setting like Github to reduce eye strain

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#138554]
### 🚀 The feature, motivation and pitch

[PyTorch doc](https://pytorch.org/docs/stable/index.html) should have a dark theme setting like Github as shown below to reduce eye strain:

![Screenshot 2024-10-22 151403](https://github.com/user-attachments/assets/19d13f29-a7d4-486c-80e9-8a51dec8a71d)

cc @svekars @brycebortree @sekyondaMeta

**Comment by malfet** [comment]
Closing as duplicate of https://github.com/pytorch/pytorch/issues/120407
