### ISSUE TITLE
[ROCm] MI300X Tunable ops causes 100GB of Memory Leak leading to OOM

### ISSUE THREAD

**Issue by OrenLeung** [pytorch/pytorch#138532]
### 🐛 Describe the bug

Hi AMD Team,

Turning on tunableop causes OOM.  When not enabling it, it does not OOM. I have tried it on torch nightly.

Can you take a look?

Thanks,
Oren

cc: @hliuca 

## Without enabling tunable ops working Command
```bash
python ./reprod_oom.py --bsz=28
```
## Enabling Tunable Op causes OOM Command
```bash
PYTORCH_TUNABLEOP_ENABLED=1 PYTORCH_TUNABLEOP_VERBOSE=1 python ./reprod_oom.py --bsz=28
```

## Stack Trace
```python
Traceback (most recent call last):
  File "/workspace/llm-train-bench/./reprod_oom.py", line 99, in <module>
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/llm-train-bench/./reprod_oom.py", line 87, in train
    
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/llm-train-bench/./reprod_oom.py", line 57, in forward
    
torch.OutOfMemoryError: HIP out of memory. Tried to allocate 2.69 GiB. GPU 0 has a total capacity of 191.98 GiB of which 170.00 MiB is free. Of the allocated memory 97.66 GiB is allocated by PyTorch, and 2.30 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
additional tuning results available, rewriting file tunableop_results0.csv
```

## Reprod Script
```python
import torch
import torch.nn.functional as F
import torch.nn as nn

class CausalSelfAttention(nn.Module):
    def __init__(self, d_embd, n_heads, **kwargs):
        super().__init__()
        self.d_head = d_embd // n_heads  # D
        self.attn_proj = nn.Linear(d_embd, 3*d_embd)
        self.out_proj = nn.Linear(d_embd, d_embd)
 
    def forward(self, x_BTE):
        qkv = self.attn_proj(x_BTE).split(x_BTE.size(-1), -1)
        split_attn_head = lambda z: z.unflatten(-1, [-1, self.d_head]).transpose(1, 2)
        q_BHTD, k_BHTD, v_BHTD = map(split_attn_head, qkv)
        o_BHTD = F.scaled_dot_product_attention(q_BHTD, k_BHTD, v_BHTD, dropout_p=0.0, is_causal=True)
        o_BTE = o_BHTD.transpose(1, 2).flatten(-2)
        y_BTE = self.out_proj(o_BTE)
        return y_BTE

class GPTBlock(nn.Module):
    def __init__(self, d_embd, **kwargs):
        super().__init__()
        self.attn_norm = nn.LayerNorm(d_embd)
        self.attn = CausalSelfAttention(d_embd, **kwargs)
        self.ffn_norm = nn.LayerNorm(d_embd)
        self.ffn = nn.Sequential(
            nn.Linear(d_embd, 4*d_embd),
            nn.GELU(),
            nn.Linear(4*d_embd, d_embd)
        )

    def forward(self, x_BTE):
        x_BTE = x_BTE + self.attn(self.attn_norm(x_BTE))
        y_BTE = x_BTE + self.ffn(self.ffn_norm(x_BTE))
        return y_BTE

class GPT(nn.Module):
    def __init__(self, vocab_size, max_seq_len, n_layers, d_embd, **kwargs):
        super().__init__()
        self.tok_embd = nn.Embedding(vocab_size, d_embd)
        self.pos_embd = nn.Embedding(max_seq_len, d_embd)
        self.tsfmr_blks = nn.ModuleList(GPTBlock(d_embd, **kwargs) for _ in range(n_layers))
        self.out_norm = nn.LayerNorm(d_embd)

    def forward(self, idx_BT):
        pos_T = torch.arange(idx_BT.size(1), dtype=torch.int64, device=idx_BT.device)
        x_BTE = self.tok_embd(idx_BT) + self.pos_embd(pos_T).unsqueeze(0)

        for tsfmr_blk in self.tsfmr_blks:
            x_BTE = tsfmr_blk(x_BTE)

        x_BTE = self.out_norm(x_BTE)
        logits_BTV = x_BTE @ self.tok_embd.weight.T  # Weight tying

        return logits_BTV


def train(
    bsz: int = 28,
):
    torch.manual_seed(3985)
    torch.cuda.set_device(0)

    cfg_json = {
        "n_layers": 48,
        "n_heads": 25,
        "d_embd": 1600,
        "max_seq_len": 1024,
        "vocab_size": 50304,
    }

    model = GPT(**cfg_json).to('cuda:0')

    optimizer = torch.optim.AdamW(model.parameters(), fused=True)

    model.train()

    for step_idx in range(100):
        input_BT = torch.randint(50304, [bsz, 1024], dtype=torch.int64).to('cuda:0')
        label_BT = torch.randint(50304, [bsz, 1024], dtype=torch.int64).to('cuda:0')

        with torch.amp.autocast('cuda', torch.bfloat16):
            logits_BTV = model(input_BT)
            loss = F.cross_entropy(logits_BTV.flatten(0, 1), label_BT.flatten())
        loss.backward()

        optimizer.step()
        optimizer.zero_grad(set_to_none=True)

        torch.cuda.synchronize()
        print(f"finish {step_idx} step")

if __name__ == "__main__":
    import fire
    fire.Fire(train)
```

## Pytorch Nightly Version

```bash
$ pip list | grep torch
pytorch-triton-rocm     3.1.0+cf34004b8a
torch                   2.6.0.dev20241021+rocm6.2
torchvision             0.18.0a0+68ba7ec
```

## Dockerfile (uses 2.3 release as base image then install pytorch nightly)
```bash
FROM rocm/pytorch:rocm6.2_ubuntu22.04_py3.10_pytorch_release_2.3.0

RUN apt install -y nano wget

RUN pip install uv

RUN uv pip install --system ipython pytest fire pydantic pybind11

RUN pip3 uninstall -y torch

RUN pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/rocm6.2

WORKDIR /workspace/llm-train-bench/

CMD ["/usr/bin/bash"]
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

**Comment by OrenLeung** [comment]
I have also confirmed that this is not an issue of a zombie process holding on hbm memory by confirming that VRAM% is at 0% before I ran the reprod script

```bash
============================================ ROCm System Management Interface ============================================
====================================================== Concise Info ======================================================
Device  Node  IDs              Temp        Power     Partitions          SCLK    MCLK    Fan  Perf  PwrCap  VRAM%  GPU%  
              (DID,     GUID)  (Junction)  (Socket)  (Mem, Compute, ID)                                                  
==========================================================================================================================
0       2     0x74a1,   28851  38.0°C      128.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
1       3     0x74a1,   23018  40.0°C      128.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
2       4     0x74a1,   29122  37.0°C      126.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
3       5     0x74a1,   22683  35.0°C      123.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
4       6     0x74a1,   53458  36.0°C      122.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
5       7     0x74a1,   63883  37.0°C      122.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
6       8     0x74a1,   53667  38.0°C      124.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
7       9     0x74a1,   63738  38.0°C      125.0W    NPS1, SPX, 0        132Mhz  900Mhz  0%   auto  750.0W  0%     0%    
==========================================================================================================================
================================================== End of ROCm SMI Log ===================================================
```

**Comment by OrenLeung** [comment]
I tried offline tuning as described in https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/cuda/tunable/README.md#offline-tuning and got a 10TFLOP/s boost 

gpt2-xl batch size 28:
- mi300x torch.compile max-autotune-no-cudagraphs: 230 TFLOP/s
- mi300x torch.compile max-autotune-no-cudagraphs with tunable ops: 244 TFLOP/s

I am not sure why doing online tunable ops causes it to OOM as auto tuning process be reusing the existing input operand buffers?

Let me know if OOMing for online tunable ops is the expected behaviour and I will close this issue. Thanks!

**Comment by naromero77amd** [comment]
Hello @OrenLeung  You are not the only one who has reported OOM when using _in situ_ TunableOp. Unfortunately, there are workloads where TunableOp's use of hipBLASLt and rocBLAS leads to OOM.

I am glad that offline tuning has worked for you. As far as @jeffdaily and I know, there are no memory leaks in TunableOp. 

Could you please try your work load again with _in situ_ TunableOp again, but all so set this environment variable:
`PYTORCH_NO_CUDA_MEMORY_CACHING=1`

Let us know if you still get the OOM issue with this environment variable.

**Comment by OrenLeung** [comment]
Thanks for the quick reply @naromero77amd !

Is there a way to disable rocBLAS and have tunableOps only try hipBLASLt? seems like tunableops always chooses hipblaslt anyways.

I am not too sure why enabling TunableOp would cause OOMs tbh as shouldn't it just be reusing the existing operand buffers during tuning?

> Could you please try your work load again with in situ TunableOp again, but all so set this environment variable:

Will do & get back to you. thank you for the suggestion

**Comment by OrenLeung** [comment]
Hi @naromero77amd ,

Unfortunately, I still OOM when enabling the `PYTORCH_NO_CUDA_MEMORY_CACHING=1` flag.

What does this indicate?

## Reprod Command
```bash
PYTORCH_NO_CUDA_MEMORY_CACHING=1 PYTORCH_TUNABLEOP_ENABLED=1 PYTORCH_TUNABLEOP_VERBOSE=1 python ./reprod_oom.py --bsz=28
```


## Error Trace
```python
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/llm-train-bench/./reprod_oom.py", line 84, in train
    logits_BTV = model(input_BT)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/llm-train-bench/./reprod_oom.py", line 54, in forward
    logits_BTV = x_BTE @ self.tok_embd.weight.T  # Weight tying
RuntimeError: HIP error: out of memory
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

**Comment by naromero77amd** [comment]
> Thanks for the quick reply @naromero77amd !
> 
> Is there a way to disable rocBLAS and have tunableOps only try hipBLASLt? seems like tunableops always chooses hipblaslt anyways.
> 
> I am not too sure why enabling TunableOp would cause OOMs tbh as shouldn't it just be reusing the existing operand buffers during tuning?
> 
> > Could you please try your work load again with in situ TunableOp again, but all so set this environment variable:
> 
> Will do & get back to you. thank you for the suggestion

These are all the environment variables:
https://github.com/pytorch/pytorch/tree/main/aten/src/ATen/cuda/tunable

To ignore rocBLAS in the tuning process, try this:
`PYTORCH_TUNABLEOP_ROCBLAS_ENABLED=0`

**Comment by naromero77amd** [comment]
> Hi @naromero77amd ,
> 
> Unfortunately, I still OOM when enabling the `PYTORCH_NO_CUDA_MEMORY_CACHING=1` flag.
> 
> What does this indicate?
> 
> ## Reprod Command
> ```shell
> PYTORCH_NO_CUDA_MEMORY_CACHING=1 PYTORCH_TUNABLEOP_ENABLED=1 PYTORCH_TUNABLEOP_VERBOSE=1 python ./reprod_oom.py --bsz=28
> ```
> 
> ## Error Trace
> ```python
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "/workspace/llm-train-bench/./reprod_oom.py", line 84, in train
>     logits_BTV = model(input_BT)
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/workspace/llm-train-bench/./reprod_oom.py", line 54, in forward
>     logits_BTV = x_BTE @ self.tok_embd.weight.T  # Weight tying
> RuntimeError: HIP error: out of memory
> HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing AMD_SERIALIZE_KERNEL=3
> Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
> ```

Its basically an OOM error again. originally the OOM error came from PyTorch's caching allocator but this time it is coming from the ROCm software stack. Thanks for trying the environment variable.

**Comment by OrenLeung** [comment]
> These are all the environment variables: https://github.com/pytorch/pytorch/tree/main/aten/src/ATen/cuda/tunable
> 
> To ignore rocBLAS in the tuning process, try this: `PYTORCH_TUNABLEOP_ROCBLAS_ENABLED=0`

Yep. This works without OOMing. 

But upon further analysis, it seems like rocBLAS is still better on some shapes on my model so just ignoring rocBLAS probably won't work.

What is the reasoning that autotuning on both hipblaslt & rocblas causes OOM? seems like an interesting implementation edge case lol
 
![image](https://github.com/user-attachments/assets/8b81f1d9-ee84-4d11-8036-a9fc117ac7b9)

**Comment by naromero77amd** [comment]
Unfortunately, I have not been able to create an isolated test case.

**Comment by hliuca** [comment]
PYTORCH_TUNABLEOP_ENABLED=1 PYTORCH_TUNABLEOP_VERBOSE=1 python3 gemm.py 55500 28672 1600 bf16 tn

`import torch
import sys
import time
import torch.nn.functional as F

M, N, K = [int(arg) for arg in sys.argv[1:4]]
PRECISION = sys.argv[4]
FORM = sys.argv[5]

DTYPE_MAP = {
    'fp32': torch.float32,
    'fp16': torch.float16,
    'bf16': torch.bfloat16,
}

DTYPE = DTYPE_MAP[PRECISION]
DEVICE = torch.device('cuda:0')

# in torch, switch
mat_A = None
mat_B = None

if FORM == "nn":
    mat_A = torch.rand((N, K), dtype=DTYPE, device=DEVICE)
    mat_B = torch.rand((K, M), dtype=DTYPE, device=DEVICE)
elif FORM == "nt":
    mat_A = torch.rand((K, N), dtype=DTYPE, device=DEVICE).t()
    mat_B = torch.rand((K, M), dtype=DTYPE, device=DEVICE)
elif FORM == "tn":
    mat_A = torch.rand((N, K), dtype=DTYPE, device=DEVICE)
    mat_B = torch.rand((M, K), dtype=DTYPE, device=DEVICE).t()
elif FORM == "tt":
    mat_A = torch.rand((K, N), dtype=DTYPE, device=DEVICE).t()
    mat_B = torch.rand((M, K), dtype=DTYPE, device=DEVICE).t()
else:
    print("wrong form")
    quit()

# benchmark
torch.matmul(mat_A, mat_B)
`

**Comment by hliuca** [comment]
The following code is for a simple C=A^t*B. The 3 matrices are small, and use 3.5GB memory. When doing tuning, it uses 100+ GB, which is huge. Even over 80% of mem in the beginning, **too crazy**.

PYTORCH_TUNABLEOP_ENABLED=1 PYTORCH_TUNABLEOP_VERBOSE=1 python3 gemm.py 55500 28672 1600 bf16 tn

```import torch
import sys
import time
import torch.nn.functional as F

M, N, K = [int(arg) for arg in sys.argv[1:4]]
PRECISION = sys.argv[4]
FORM = sys.argv[5]

DTYPE_MAP = {
    'fp32': torch.float32,
    'fp16': torch.float16,
    'bf16': torch.bfloat16,
}

DTYPE = DTYPE_MAP[PRECISION]
DEVICE = torch.device('cuda:0')

# in torch, switch
mat_A = None
mat_B = None

if FORM == "nn":
    mat_A = torch.rand((N, K), dtype=DTYPE, device=DEVICE)
    mat_B = torch.rand((K, M), dtype=DTYPE, device=DEVICE)
elif FORM == "nt":
    mat_A = torch.rand((K, N), dtype=DTYPE, device=DEVICE).t()
    mat_B = torch.rand((K, M), dtype=DTYPE, device=DEVICE)
elif FORM == "tn":
    mat_A = torch.rand((N, K), dtype=DTYPE, device=DEVICE)
    mat_B = torch.rand((M, K), dtype=DTYPE, device=DEVICE).t()
elif FORM == "tt":
    mat_A = torch.rand((K, N), dtype=DTYPE, device=DEVICE).t()
    mat_B = torch.rand((M, K), dtype=DTYPE, device=DEVICE).t()
else:
    print("wrong form")
    quit()

# benchmark
torch.matmul(mat_A, mat_B)
```

**Comment by OrenLeung** [comment]
thank you @hliuca for providing an isolated example of massive memory usage issue. 

Seems like there could be a potential mem leak problem

**Comment by naromero77amd** [comment]
@hliuca We can take a look at the use case and try to triage. Does deactivating either hipblaslt or rocblas alleviate the memory pressure?

**Comment by hliuca** [comment]
The memory usage could be over 90%, that is **170GB**.

After I disabled rocBLAS,

**PYTORCH_TUNABLEOP_ROCBLAS_ENABLED=0** PYTORCH_TUNABLEOP_ENABLED=1 PYTORCH_TUNABLEOP_VERBOSE=1 PYTORCH_TUNABLEOP_MAX_TUNING_ITERATIONS=5 python3 gemm.py 55500 28672 1600 fp16 tn

Memory usage drops to 4%. This is a critical bug related to rocBLAS. If I disable hipblaslt, and use rocblas only, the same mem usage.

**Comment by hliuca** [comment]
**PYTORCH_TUNABLEOP_ROCBLAS_ENABLED=0** PYTORCH_TUNABLEOP_ENABLED=1 PYTORCH_TUNABLEOP_VERBOSE=1 python ./reprod_oom.py --bsz=28

In the beginning, mem usage is 5%. That is good. After 1 solution is found and another tuning starts, mem usage increases to 47%. It should have un-necessary tensor creation between Gemms, or mem leaks.

Now mem is 53%. There is memory leak between tunings.
![image](https://github.com/user-attachments/assets/e70fe104-9558-4dd1-887a-77d7ad71907d)

Memory keeps increasing.
![image](https://github.com/user-attachments/assets/84d2c44f-af4f-4988-a986-a27d87cadfa6)

There is mem leak between tunings.

**Comment by naromero77amd** [comment]
@hliuca Do you know which version of rocBLAS you are using?

**Comment by naromero77amd** [comment]
Can you please try one more test with your workload?

Run TunableOp _in situ_ but also set this environment variable.
```
ROCBLAS_DEVICE_MEMORY_SIZE=32000000
```
It should limit the amount of memory that rocBLAS can use to 32GB, however it could also lead to an error from the HIP runtime if a rocBLAS allocation exceeds this limit.

**Comment by hliuca** [comment]
@naromero77amd I have disabled rocblas and I still saw huge memory, above comment.

But I can try this one. Thanks.

**Comment by hliuca** [comment]
I tried, memory usage is the same. After 1 tuning, mem usage increased to 48%.... there is huge mem leak between tunings. Mem usage keeps increasing....

**Comment by naromero77amd** [comment]
> @naromero77amd I have disabled rocblas and I still saw huge memory, above comment.
> 
> But I can try this one. Thanks.

oh sorry -- misread the comment. There is also a hipblaslt environment variable that might help.
```
HIPBLASLT_WORKSPACE_SIZE
```

But what I have seen in the past is that particular rocBLAS and/or hipBLASLt solutions cause the memory to usage to sky rocket.

**Comment by hliuca** [comment]
> > @naromero77amd I have disabled rocblas and I still saw huge memory, above comment.
> > But I can try this one. Thanks.
> 
> oh sorry -- misread the comment. There is also a hipblaslt environment variable that might help.
> 
> ```
> HIPBLASLT_WORKSPACE_SIZE
> ```
> 
> But what I have seen in the past is that particular rocBLAS and/or hipBLASLt solutions cause the memory to usage to sky rocket.

this one is different... it is a small mem for hipblaslt, dozens of Mb.

**Comment by naromero77amd** [comment]
We are investigating and will get back to you as soon as possible.

**Comment by jeffdaily** [comment]
The root cause is rocblas’s workspace settings. We do not currently have PyTorch set a rocblas workspace limit.  This allows rocblas to allocate any size workspace it needs for a given solution. Some solutions are requiring significant workspace. 

The temporary workaround is to set the env var ROCBLAS_DEVICE_MEMORY_SIZE=<bytes>. There is no default, but rocblas internally starts with 32MiB. 

I am working on a PR that will align cublas and rocblas behavior.  PyTorch already enforces workspace limits on cublas but that code was ifdef’d away for rocm.

**Comment by OrenLeung** [comment]
Thanks @jeffdaily for looking into this!

> Some solutions are requiring significant workspace.

I don't quite understand how any solution that the autotuner picks to try use anywhere near 100GB of workspace. Is there any insight you can provide into this?

> I am working on a PR that will align cublas and rocblas behavior. PyTorch already enforces workspace limits on cublas but that code was ifdef’d away for rocm.

Awesome! thank you jeff!

**Comment by naromero77amd** [comment]
> 000

@hliuca Can you clarify if you were referring here to the original reproducer (reprod_oom.py) or the simpler one (gemm.py)?

**Comment by hliuca** [comment]
@naromero77amd my code is simpler as it has 1 gemm only, it can show the huge mem usage issue. Thank you.
