### ISSUE TITLE
Nightly job `linux-binary-manywheel / manywheel-py3_10-xpu-build / build` is currently broken

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#138695]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/actions/runs/11415735761/job/31768246145

Requires additional investigation

Seems to have introduced Windows build breakages as well

### Versions

nightly branch

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by atalman** [comment]
This is fixed: https://hud2.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=linux-binary-manywheel&mergeLF=true
