### ISSUE TITLE
torch.cond works, but would still print a misleading warning 

### ISSUE THREAD

**Issue by henrylhtsang** [pytorch/pytorch#138782]
### 🐛 Describe the bug

EDIT: You might need https://github.com/pytorch/pytorch/pull/138765 and https://github.com/pytorch/pytorch/pull/138760 to repro.

This example is pretty peculiar. `torch.cond` handles it pretty well, but I still get the warning that was a bit misleading.

logs:
```
torch/_higher_order_ops/cond.py:140] Pred is a Python constant. When used with torch.cond, it executes only one of the branches. If you want torch.cond to perserve two branches, please make the predicate a boolean tensor or a SymBool.
WARNING:root:expected_output: tensor([0.8917], device='cuda:0'), actual_output: tensor([0.8917], device='cuda:0')
torch/_higher_order_ops/cond.py:140] Pred is a Python constant. When used with torch.cond, it executes only one of the branches. If you want torch.cond to perserve two branches, please make the predicate a boolean tensor or a SymBool.
WARNING:root:expected_output: tensor([-0.], device='cuda:0'), actual_output: tensor([-0.], device='cuda:0')
```

repro:
```python
class M(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.flag = False

    def forward(self, x, flag):
        self.flag = flag.item()
        return torch.cond(
            self.flag,
            lambda x: x * 0.0,
            lambda x: 2 * x,
            (x,),
        )

input1 = (
    torch.randn(1).cuda(),
    torch.tensor([0], dtype=torch.bool),
)
model = M().cuda()
_ = model(*input1)
```

EDIT1: edited the repro to make it smaller

### Versions

trunk

cc @albanD @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by ydwu4** [comment]
The warning is probably caused by the eager run "expected_output = model(*input)" here. When running the model eagerly, flag is a bool so the warning seems correct?

**Comment by henrylhtsang** [comment]
> The warning is probably caused by the eager run "expected_output = model(*input)" here. When running the model eagerly, flag is a bool so the warning seems correct?

It was indeed caused by running it in eager mode. However, this is not something we can actually merge in trunk, since users can run it in eager mode and in pt2 env. Since it will print a warning log every iteration.

**Comment by ydwu4** [comment]
ok, i can have a PR to suppress the warning in eager mode.

**Comment by henrylhtsang** [comment]
> ok, i put up a PR to suppress the warning in eager mode.

I guess an alternative is only print for first 10 iterations.

**Comment by ydwu4** [comment]
em...I guess I don't understand why is it misleading?

**Comment by henrylhtsang** [comment]
> hm...I guess I don't understand why is it misleading?

Oh nevermind, it would throw the warning even in the following case.
```
def forward(self, x, flag):
    return torch.cond(
        flag.item(),
        lambda x: x * 0.0,
        lambda x: 2 * x,
        (x,),
    )
```

I guess it is hard to check if a constant is a symbool or an actual constant...

**Comment by ydwu4** [comment]
> I guess it is hard to check if a constant is a symbool or an actual constant

yeah, I agree. Its type is determined by whether we're tracing the code (or you can think of it as compilation time vs runtime). if flag is a tensor, tensor.item() returns a python constant in eager mode (runtime) and returns a symbol during tracing (compilation time).

**Comment by ydwu4** [comment]
For this particular change, I feel we should only throw warnings during compilation time. For eager run users, they don't care about whether we're preserving two branches.

**Comment by henrylhtsang** [comment]
> For this particular PR, I feel we should only throw warnings during compilation time. For eager run users, they don't care about whether we're preserving two branches.

make sense

**Comment by henrylhtsang** [comment]
I assumed it is fixed in https://github.com/pytorch/pytorch/pull/138837

closing
