### ISSUE TITLE
Illegal Memory Access w/ efficient Attention + compile

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#138772]
# Summary

The base repro: 
`PYTORCH_NO_CUDA_MEMORY_CACHING=1 CUDA_LAUNCH_BLOCKING=1 python benchmark.py --model maxvit_nano_rw_256 --precision bfloat16 --torchcompile --bench train --no-retry -b 64 `

This is producing :
```Shell
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /home/drisspg/meta/pytorch/c10/cuda/CUDAException.cpp:43 (most
frame #6: at::native::_efficient_attention_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, long, long, at::Tensor const&, double, at::Tensor const&, at::Tensor const&, long, bool, std::optional<double>, std::optional<long>, std::optional<long>, bool) + 0x2338 (0x7f0a1e35b418 in /home/drisspg/meta/pytorch/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x344cbc7 (0x7f0a1e44cbc7 in /home/drisspg/meta/pytorch/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x347bb1d (0x7f0a1e47bb1d in /home/drisspg/meta/pytorch/torch/lib/libtorch_cuda.so)
frame #9: at::_ops::_efficient_attention_backward::call(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, c10::SymInt, c10::SymInt, at::Tensor const&, double, at::Tensor const&, at::Tensor const&, long, bool, std::optional<double>, std::optional<long>, std::optional<long>, bool) + 0x350 (0x7f0a2b292490 in /home/drisspg/meta/pytorch/torch/lib/libtorch_cpu.so)
frame #10: at::native::_scaled_dot_product_efficient_attention_backward_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, double, std::array<bool, 4ul>, bool, std::optional<double>) + 0x2b3 (0x7f0a1e1bef23 in 
```

## Current Debugging
Verified that this is specific to inductor:
1. No error in Eager
2. No error when compiling with: `aot_eager_decomp_partitioner`

The actual IMA is an out of bounds read.

### Smaller ish repro
https://gist.github.com/drisspg/49d5bec4fdadeace206455267e1ef135
IF you run this with `PYTORCH_NO_CUDA_MEMORY_CACHING=1 CUDA_LAUNCH_BLOCKING=1` you should hit the same IMA

**Comment by drisspg** [comment]
Update: Good old printfing
https://www.diffchecker.com/wmGjuBOD/

The only difference between good run (eager) and bad run (inductor) is that the output strides is changed

**Comment by drisspg** [comment]
Strangely at the time of lowering, the meta['val']'s stride for the out tensor that is saved for backwards and and in put to the backward kernel dont match what eager is seeing:

```
fx_node.args[5].meta["val"].stride()
(32768, 1, 512, 16)
```

**Comment by drisspg** [comment]
Update:

Suggested by @Chillee , setting https://github.com/pytorch/pytorch/blob/0a38c0ec89ab393be91619393063ea30908a5d55/torch/_inductor/config.py#L398 
To False appears to fix the issue

@eellison

**Comment by Chillee** [comment]
cc: @shunting314

**Comment by shunting314** [comment]
I also tried the other repro by running the generated wrapper directly. It can repro. But if the root cause is layout optimization (since we see the strides difference), I think I need run the original compiled model to exercise thru lowering

**Comment by eellison** [comment]
This might be a good opportunity to the do the general stride fixes that we have been talking about with @zou3519, @yifuwang  

For nodes which are sensitive to striding (soon to be - all custom ops)

- Record the strides of all inputs on the node after joint graph tracing. (passes can manipulate strides, so we want to record on the node itself)
- For aliases/non-owning layouts, both `require_exact_strides` and `require_stride_order` need fixing today. See [here](https://github.com/pytorch/pytorch/blob/e7f1e306dfd1675e4fbe126ca01a9bbbeb49ecc5/torch/_inductor/ir.py#L4807-L4808) where we just unwrap the view but dont make the same changes to the stride that is required. I'm not sure what the general fix is... For instance, if you were to index only the last dimension, that leaves the other dimension strides unconstrained. but at least for something like permute we should be able to constrain the original layout in a way that makes sense with the requested strides. Potentially we could also realize the exact stride on the definition of the alias as well.

**Comment by shunting314** [comment]
> Strangely at the time of lowering, the meta['val']'s stride for the out tensor that is saved for backwards and the out passed to the backward kernel don't match eager/meta of forward result

@drisspg  this is  expected behavior for layout optimization since Inductor may change the layout for tensors not visible to user (e.g. saved activations)

What's the constraint upon argument layouts for _scaled_dot_product_efficient_attention_backward_cuda ?

BTW, back out this PR can make the command work: https://github.com/pytorch/pytorch/pull/112045/files . But I would like to understand the layout constraints of the attention backward kernel more. Hopefully we can get a better fix

**Comment by shunting314** [comment]
Also this PR forces SDPA kernels' argument to have stride==1 for the last dimension: https://github.com/pytorch/pytorch/pull/111721 . But it seems not taking effect? cc @eellison

**Comment by drisspg** [comment]
cc @danthe3rd is there an additional constrain that the grad_out strides must match the out_strides?

**Comment by shunting314** [comment]
BTW, I manually force all tensor inputs to the _scaled_dot_product_efficient_attention_backward to be contiguous, it still crashes: https://gist.githubusercontent.com/shunting314/72af91e7cd796402f0b9e2bafe6350b5/raw/197365faa1f2dffa112b98fbf7e046dd00ef0a63/w.py . It crashes before the line 'breakpoint()' I added.

It seems some extra strides/layout requirement is needed for this kernel
