### ISSUE TITLE
MacOS runners queue again

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#138724]
### 🐛 Describe the bug

Which feels like a repetition of https://github.com/pytorch/pytorch/issues/129957
Here is the current queue: 
![image](https://github.com/user-attachments/assets/abfc3317-f0ed-453c-bdec-7ecee91f78cb)
And looks like there only 35 runners registered in github and 45 on EC2

### Versions

CI

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
And looks like as of 6:30AM PST we've lost all the runners, but I wonder if it actually affects people, or just myself...

**Comment by malfet** [comment]
And sill 0 runners (one M1-13, but it's useless as it can not drive the build)
```
% python3 build_aarch64_wheel.py --list-instances --instance-type mac2.metal
All instances of type mac2.metal
i-0c3a638fd38b2e323 gh-ci-pet-action-runner ec2-35-153-99-133.compute-1.amazonaws.com running
```

**Comment by malfet** [comment]
Funny thing is, while we are experiencing the crunch, some of the runners are use to re-run disabled tests on pytorch-canary (service repo with a stale fork of pytorch that is used as a testbed for CI Infa changes, see https://github.com/pytorch/pytorch-canary/actions/runs/11495651431/job/32027981268 and screenshot below (as it's a private repo, though nothing is really secret about it)
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/0eeb149c-e594-479a-96e0-c20f9d7a09a3">

**Comment by huydhn** [comment]
Let me disable these workflows on canary if you haven't done that yet

**Comment by malfet** [comment]
Around 10AM yesterday morning 18 runners were allocated and this is still the case as of 7AM today
<img width="645" alt="image" src="https://github.com/user-attachments/assets/4cf06838-56a4-4b40-8176-11d42dca6189">

Even though we have about 40 runners available in EC2:
```
% python3 build_aarch64_wheel.py --list-instances --instance-type mac2.metal      
All instances of type mac2.metal
i-0fd4402cceceb54e7 gh-ci-sonoma-pet-action-runner  running us-east-1a
i-0bb3676fdda018a63 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0a9f5ece9061ed2ec gh-ci-sonoma-pet-action-runner running us-east-1a
i-0fc3ec016d3c41cea gh-ci-sonoma-pet-action-runner running us-east-1a
i-06167a0de097ba707 gh-ci-sonoma-pet-action-runner running us-east-1a
i-00d033f7a4fe043c7 gh-ci-sonoma-pet-action-runner running us-east-1a
i-02eb7244edc6f8cc9 gh-ci-sonoma-pet-action-runner running us-east-1a
i-054b18a8bd53929f6 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0bde69e2577371a4b gh-ci-sonoma-pet-action-runner running us-east-1a
i-097d5c1499424d332 gh-ci-pet-action-runner running us-east-1a
i-0db71eeb484fac037 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0a437dcdd7e97612e gh-ci-sonoma-pet-action-runner running us-east-1a
i-0a7aa797794821df8 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0b94a9ea480cd2693 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0623edd568c534737 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0263e19776378ecd3 gh-ci-sonoma-pet-action-runner running us-east-1a
i-041c95e4aab7fe31b gh-ci-sonoma-pet-action-runner running us-east-1a
i-0395379c82bbd2fa3 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0075691d787b787b9 gh-ci-pet-action-runner running us-east-1a
i-0705390d018009855 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0bbb6428f39d86671 gh-ci-sonoma-pet-action-runner running us-east-1a
i-034cef3db13f53f59 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0b5de105de167697d gh-ci-sonoma-pet-action-runner running us-east-1a
i-0d3c50b21b1a146be gh-ci-pet-action-runner running us-east-1a
i-0bff673b957cd10f3 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0c498fd360262127d gh-ci-pet-action-runner running us-east-1a
i-0f65152837eca2521 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0310f9859f1739f77 gh-ci-sonoma-pet-action-runner running us-east-1a
i-019f7481049f36555 gh-ci-sonoma-pet-action-runner running us-east-1a
i-01ba4bbf44d4d4393 gh-ci-sonoma-pet-action-runner running us-east-1a
i-096b9440ed6feaf52 gh-ci-pet-action-runner running us-east-1a
i-0c58c3e6e20280837 gh-ci-sonoma-pet-action-runner running us-east-1a
i-00cbe9480099c6b75 gh-ci-sonoma-pet-action-runner running us-east-1a
i-0ca7e484b550daae1 gh-ci-sonoma-pet-action-runner running us-east-1a
i-075beeefd14ed2ae0 gh-ci-pet-action-runner running us-east-1a
i-02191f703f88df0e6 gh-ci-sonoma-pet-action-runner running us-east-1a
i-025a23af286e08b70 gh-ci-sonoma-pet-action-runner running us-east-1a
i-01eeb8dfde6ba086a gh-ci-sonoma-pet-action-runner running us-east-1a
i-0fdb796744564037b gh-ci-sonoma-pet-action-runner running us-east-1a
i-04927245e5e5f3c26 gh-ci-sonoma-pet-action-runner running us-east-1a
```

**Comment by malfet** [comment]
We have 70+ runners now, not sure what have changed...

**Comment by malfet** [comment]
Feedback I'm seeking for triage review today: had anyone noticed it? If not, perhaps we can stop treating this as hi-pri issues in the future and let the queue accumulate

**Comment by ezyang** [comment]
This kind of outage it's useful to have a SEV banner so that people can see that there's a problem and what intervention they should have

**Comment by huydhn** [comment]
This one has been resolved. A feedback for oncall is that we need to create a CI sev for this because it affects other devs and 2.5 release works.
