### ISSUE TITLE
[Caffe2]How to use ‘Split Operator’ with the second input tensor? I got a segment fault

### ISSUE THREAD

**Issue by zhonhel** [pytorch/pytorch#13880]
The second Blob’s tensor is on GPU(I think), and its shape is (2,) with content [1000 200], int32 type, I used workspace.FeedBlob and numpy to create it.

And the tensor I want to split has 1200 length on the axis I want to split.

But I got a segment fault when runing this Operator. 

Can anyone help me? Thank you very much. Here is my code fragment:
```
workspace.FeedBlob(core.ScopedName('split'), np.array([1000,200],dtype=np.int32))
```
```
model.net.Split(['theBlobToBeSplited','split'],['part1','part2'],axis=0)
```
And if I use `split=(1000,200)` as argument, it runs correctly.

**Comment by mruberry** [comment]
Closing this due to age and since caffe2 has been deprecated in favor of PyTorch.
