### ISSUE TITLE
Inductor needs to be updated to work with upstream triton's AttrsDescriptor

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#138895]
### 🐛 Describe the bug

@alexbaden made a first attempt at this in https://github.com/pytorch/pytorch/pull/137757, but we still need additional changes.

1. The current implementation passes an invalid dict to AttrsDescriptor.from_dict. AttrsDescriptor.from_dict expects a dict in the format `{"cls": "AttrsDescriptor", "arg_properties": {"tt.divisibility": ..., "tt.equal_to": ...}}` but currently gets just the arg_properties, `{"tt.divisibility": ..., "tt.equal_to": ...}`
2. Backends can provide different versions of AttrsDescriptor, like HIPAttrsDescriptor: https://github.com/triton-lang/triton/blob/152ef2deb8852d5c84f9ffba217b3a7c8f398c5f/third_party/amd/backend/compiler.py#L75-L77. We may need to update the implementation to look up the correct version of the AttrsDescriptor.
3. In the current implementation, the AttrsDescriptor is serialized and dumped into the `triton_meta` of the `@triton_heuristics.[...]` decorator. Currently, `AttrsDescriptor` gets serialized as `<triton.backends.compiler.AttrsDescriptor object at 0x7fac4a6268e0>`, which of course can't be loaded when we try to run the code-generated triton.

I imagine a reasonable approach would be:
* Identify the right AttrsDescriptor object during codegen time. I'm not sure how to do this - it may require importing triton and initializing some runtime stuff to get the appropriate backend?
* Serialize with `.to_dict()`, and put this in the [triton_meta dict](https://github.com/pytorch/pytorch/blob/907f001a682c4e0893fa2c999ac4c9ff16581835/torch/_inductor/codegen/wrapper.py#L1372)
* in triton_heuristics.py (i.e. at runtime), load using AttrsDescriptor.from_dict().

### Versions

main branch triton, viable/strict as of oct 24, 2024. H100

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov @bertmaher @int3 @nmacchioni @embg @peterbell10

**Comment by alexbaden** [comment]
The current Inductor changes should work for Triton prior to this commit: https://github.com/triton-lang/triton/commit/692143cd869f2fa1501edb1db76fb452b85ac914#diff-1a65816e07c3edd682068b66cea6ad616daa7f1f4abf13052272a40f69deb1c8 but you also need this PR: https://github.com/triton-lang/triton/pull/4888

I initially tried using the `toDict` method in the `AttrsDescriptor` class, but we want to use the deserialized `AttrsDescriptor` after we read it from the config in several places, and it was difficult to support both the new and old `AttrsDescriptor` without specialized code - `__repr__` was cleaner, but needs to be added to the class in Triton. 

I am working on updating the Triton PR + adding some tests there for the additional changes to `AttrsDescriptor` in Triton.

**Comment by davidberard98** [comment]
Thanks! I'll patch your triton PR for now.

**Comment by alexbaden** [comment]
I made the changes in #139193 and updated the Triton PR - this probably duplicates #139179.

**Comment by alexbaden** [comment]
fixed w/ 77e25d57b0df67940d796aacbc8d39e9851fcbd9
