### ISSUE TITLE
Adjust install_user script for Ubuntu 24.04 support

### ISSUE THREAD

**Issue by iupaikov-amd** [pytorch/pytorch#138812]
### 🚀 The feature, motivation and pitch

Ubuntu 24.04 now ships with user "ubuntu" that has id 1000 by default. Pytorch CI uses the same id and this causes failure on the [last line](https://github.com/pytorch/pytorch/blob/5c88a9f6c0b65984d0e5ac96fd199d2aabd96a93/.ci/docker/common/install_user.sh#L33) of install_user.sh.

I propose to add a workaround for this issue like the one below:
```
if [[ $UBUNTU_VERSION == 24.04 ]]; then
    # touch is used to disable harmless error message
    touch /var/mail/ubuntu && chown ubuntu /var/mail/ubuntu && userdel -r ubuntu
fi
```

It removes the default user and enables the CI to run as usual. More info can be found here: https://askubuntu.com/a/1515958

### Alternatives

Alternatively the proper way would be to change user id for jenkins but I don't know how significant the impact would be on the whole CI.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Thank you for the report. Please do not hesitate to propose a PR that fixes the problem

**Comment by iupaikov-amd** [comment]
Sure, here it is: https://github.com/pytorch/pytorch/pull/138815
