### ISSUE TITLE
weights_only=True allow set as well as dict

### ISSUE THREAD

**Issue by AngledLuffa** [pytorch/pytorch#138851]
### 🚀 The feature, motivation and pitch

`pytorch.load` with `weights_only=True` allows for loading of lists & dicts

I would expect the builtin `set` to be just as safe as a `dict`

### Alternatives

Another alternative would be to convert sets to lists before saving, then converting back to a set when loading if the model needs a set internally

### Additional context

```
WeightsUnpickler error: Unsupported global: GLOBAL builtins.set was not an allowed global by default. Please use `torch.serialization.add_safe_globals([set])` to allowlist this global if you trust this class/function.
```

cc @mruberry @mikaylagawarecki @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
I'm of two minds here: Sets indeed sounds reasonable, but on the other hand, do you know if any models which are serialized with property sets rather than property lists?

**Comment by AngledLuffa** [comment]
The Stanza (Stanford NLP toolkit) tokenizer models use `set` to store known words in a language.  We can change it to `list` pretty easily, though

**Comment by AngledLuffa** [comment]
Thanks for the quick turnaround!

**Comment by kit1980** [comment]
Verified for 2.6.0 release candidate:

```
In [3]: torch.save({1, 2, 3}, "foo.pt")
   ...: torch.load("foo.pt", weights_only=True)
Out[3]: {1, 2, 3}
```
