### ISSUE TITLE
arange.start is annotated with scalar on inputs but got torch.SymInt

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#138827]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/blob/fe458eef8032f993b155d836538c60b5beddc569/aten/src/ATen/native/native_functions.yaml#L780-L782

But when dynamic shapes is enabled in torch.export.export, the input `start` and `end` can be `sym_size_int_1`. However, they are not annotated as SymInt, like here

https://github.com/pytorch/pytorch/blob/fe458eef8032f993b155d836538c60b5beddc569/aten/src/ATen/native/native_functions.yaml#L936

Is this a bug, or does it mean scalar includes SymInt?

### Versions

main branch

cc @ezyang @malfet @xuzhao9 @gramster

**Comment by ezyang** [comment]
Scalar can accept SymInt (or SymFloat/SymBool, for that matter)

**Comment by justinchuby** [comment]
So how does one decide if they annotate the argument as `SymInt` vs `Scalar`? Is `SymInt` a subset of `Scalar`?
