### ISSUE TITLE
[inductor][cpu]llama amp single thread inductor_max_autotune performance regression in 2024-10-16 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#138823]
### 🐛 Describe the bug

<p>amp static shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>llama</td>
      <td>single</td>
      <td>1</td>
      <td>3.992154</td>
      <td>0.013228828</td>
      <td>0.052811518615512004</td>
      <td>81.807902</td>
      <td>1</td>
      <td>6.126736</td>
      <td>0.008996031</td>
      <td>0.055116306984816</td>
      <td>85.39452</td>
      <td>0.65</td>
      <td>1.04</td>
      <td>0.68</td>
      <td>1.04</td>
    </tr>
  </tbody>

</table>

<p>amp dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>llama</td>
      <td>single</td>
      <td>1.0</td>
      <td>4.138349</td>
      <td>0.013100655</td>
      <td>0.054215082518595</td>
      <td>80.950906</td>
      <td>1</td>
      <td>5.796402</td>
      <td>0.008985967000000001</td>
      <td>0.052086277090734004</td>
      <td>84.002409</td>
      <td>0.71</td>
      <td>0.96</td>
      <td>0.69</td>
      <td>1.04</td>
    </tr>
  </tbody>

</table>

the bad commit 4e8997744cee18c0c5d8112951d2f5a93175e63e
```
/workspace/pytorch# bash inductor_single_run.sh single inference performance torchbench llama amp first static default 0 inductor_max_autotune
Testing with inductor_max_autotune.
single-thread testing....
loading model: 0it [00:01, ?it/s]
cpu  eval  llama
AUTOTUNE linear_unary(32x512, 512x512)
  cpp_packed_gemm_0 0.0092 ms 100.0%
  _linear_pointwise 0.0236 ms 38.9%
SingleProcess AUTOTUNE benchmarking takes 0.2465 seconds and 1.1770 seconds precompiling
AUTOTUNE linear_unary(32x512, 1536x512)
  cpp_packed_gemm_4 0.0666 ms 100.0%
  _linear_pointwise 0.0906 ms 73.5%
SingleProcess AUTOTUNE benchmarking takes 0.2477 seconds and 1.2338 seconds precompiling
AUTOTUNE linear_unary(32x512, 1536x512)
  cpp_packed_gemm_5 0.0351 ms 100.0%
  _linear_pointwise 0.0724 ms 48.5%
SingleProcess AUTOTUNE benchmarking takes 0.2469 seconds and 1.1682 seconds precompiling
AUTOTUNE linear_unary(32x1536, 512x1536)
  cpp_packed_gemm_6 0.0312 ms 100.0%
  _linear_pointwise 0.0651 ms 47.9%
SingleProcess AUTOTUNE benchmarking takes 0.2473 seconds and 1.2679 seconds precompiling
running benchmark: 100%|███████████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 17.07it/s]
3.361x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,llama,1,3.361405,13.407840,36.131100,0.967607,310.090138,320.471040,531,1,0,0,0,0,0
```
</table>

the last good commit 383eba522922f0b7c525b88ed4348c64b40b95cf
```
/workspace/pytorch# bash inductor_single_run.sh single inference performance torchbench llama amp first static default 0 inductor_max_autotune
Testing with inductor_max_autotune.
single-thread testing....
loading model: 0it [00:01, ?it/s]
cpu  eval  llama
AUTOTUNE linear_unary(1x512, 32000x512)
  cpp_packed_gemm_56 1.0281 ms 100.0%
  _linear_pointwise 1.1298 ms 91.0%
SingleProcess AUTOTUNE benchmarking takes 0.2845 seconds and 1.1767 seconds precompiling
running benchmark: 100%|███████████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 19.26it/s]
5.041x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,llama,1,5.041319,8.474715,29.246236,0.964513,309.932851,321.336115,531,1,0,0,0,0,0
```

</table>

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>23512dbe</td>
      <td>main</td>
      <td>23512dbe</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>e8b1409dcfbc7609110c9c332d6038a957b8dd9f</td>
      <td>main</td>
      <td>1d6e0412f5</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.5.0a0+3f05699</td>
      <td>main</td>
      <td>2.5.0a0+ba696ea</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>1d6e0412f5205b1cd709e034526d7f21d6f2d56f</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob//main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single inference performance torchbench llama amp first static default 0 inductor_max_autotune
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/4e8997744cee18c0c5d8112951d2f5a93175e63e
[torchbench-llama-inference-amp-dynamic-default-single-performance-drop_guilty_commit.log](https://github.com/user-attachments/files/17509267/torchbench-llama-inference-amp-dynamic-default-single-performance-drop_guilty_commit.log)
cc @ezyang @chauhang @penguinwu @chuanqi129 @chunyuan-w

**Comment by leslie-fang-intel** [comment]
@zxd1997066 will help to double confirm the guilty commit.

**Comment by leslie-fang-intel** [comment]
The suspected commit turns on `coordinate_descent_tuning` by default when compile mode is `max-autotune`.
In this model, the last linear with shape: `[1, 512 ]` and `[512, 32000]` has been decomposed into `mul + sum` as in https://github.com/pytorch/pytorch/blob/e6e140c3d731a15fbdb1a8df93a288915c4c0e97/torch/_inductor/decomposition.py#L289-L293 which cause 2 issues here:

1.  Autocast will not cast act and wgt into BF16 for `mul` when turns on AMP.
2. `mul + sum` pattern can't be fused and hit the onednn which will be codegen by cpp backend with low performance.

**Comment by leslie-fang-intel** [comment]
Here is the graph after decomposition
```
    convert_element_type_304 = torch.ops.prims.convert_element_type.default(arg74_1, torch.bfloat16);  arg74_1 = None
    convert_element_type_305 = torch.ops.prims.convert_element_type.default(slice_147, torch.bfloat16);  slice_147 = None
    permute_120 = torch.ops.aten.permute.default(convert_element_type_304, [1, 0]);  convert_element_type_304 = None
    convert_element_type_306 = torch.ops.prims.convert_element_type.default(convert_element_type_305, torch.float32);  convert_element_type_305 = None
    convert_element_type_307 = torch.ops.prims.convert_element_type.default(permute_120, torch.float32);  permute_120 = None
    unsqueeze_2 = torch.ops.aten.unsqueeze.default(convert_element_type_306, 2);  convert_element_type_306 = None
    unsqueeze_3 = torch.ops.aten.unsqueeze.default(convert_element_type_307, 0);  convert_element_type_307 = None
    mul_66 = torch.ops.aten.mul.Tensor(unsqueeze_2, unsqueeze_3);  unsqueeze_2 = unsqueeze_3 = None
    sum_9 = torch.ops.aten.sum.dim_IntList(mul_66, [1]);  mul_66 = None
    convert_element_type_308 = torch.ops.prims.convert_element_type.default(sum_9, torch.bfloat16);  sum_9 = None
    convert_element_type_309 = torch.ops.prims.convert_element_type.default(convert_element_type_308, torch.float32);  convert_element_type_308 = None
```

- Autocast will insert node to cast act/wgt to bf16
- Since the decomposition has been registered as `pw_cast_for_opmath`, it will cast inputs to fp32 and cast output to bf16.

Here is the graph after constant folding and before we do the weight prepack
```
    %convert_element_type_default_1 : [num_users=1] = call_function[target=torch.ops.prims.convert_element_type.default](args = (%select, torch.float32), kwargs = {})
    %unsqueeze_2 : [num_users=1] = call_function[target=torch.ops.aten.unsqueeze.default](args = (%convert_element_type_default_1, 2), kwargs = {})
    %_frozen_param133 : [num_users=1] = get_attr[target=_frozen_param133]
    %mul_66 : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%unsqueeze_2, %_frozen_param133), kwargs = {})
    %sum_9 : [num_users=1] = call_function[target=torch.ops.aten.sum.dim_IntList](args = (%mul_66, [1]), kwargs = {})
    %convert_element_type_default : [num_users=1] = call_function[target=torch.ops.prims.convert_element_type.default](args = (%sum_9, torch.float32), kwargs = {})
```
There is no node to cast act to bf16 and `_frozen_param133` has been folded back to fp32.

**Comment by jgong5** [comment]
> A quick solution might be disable this decomposition on CPU for now, cc @jgong5

Sounds good to me.

**Comment by leslie-fang-intel** [comment]
https://github.com/pytorch/pytorch/pull/139537 landed to fix this issue @zxd1997066 please help to verify.

**Comment by zxd1997066** [comment]
The issue is fixed
