### ISSUE TITLE
How to Implement multi-card parallel Inference by torchrun?

### ISSUE THREAD

**Issue by lcf2610** [pytorch/pytorch#138888]
Hello everyone, I'm trying to achieve a goal of using trochrun for dual-card parallel inference. Then I have two questions. First, I found that torchrun is mainly used for model training, so can it be used for model inference? If can, my inference process is divided into two parts: model loading and inference. I only want to load the model once and then infer multiple times. How can I implement it? Thank you.

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by awgu** [comment]
@kwen2501 I think you would have things to say here :)

**Comment by lcf2610** [comment]
> Hello everyone, I'm trying to achieve a goal of using trochrun for dual-card parallel inference. Then I have two questions. First, I found that torchrun is mainly used for model training, so can it be used for model inference? If can, my inference process is divided into two parts: model loading and inference. I only want to load the model once and then infer multiple times. How can I implement it? Thank you.

for example:
`
# method1
def func1():
    runner = model(config)
    runner.infer()
run(args, func1)

#method2
runner = model(config)
def func2(runner):
    runner.infer()
run(args, func2, runner)
`
method1 works well while method2 doesn't work. And the function 'run' is the api of torchrun

**Comment by kwen2501** [comment]
> I found that torchrun is mainly used for model training, so can it be used for model inference?
Yes you can. Same cmd interface.

**Comment by kwen2501** [comment]
In infer.py:

```
def init_model(config):
    return Model(config)  # or load model from somewhere

def main(...):
    config = ...
    model = init_model(config)
    while(condition):
        output = model(input)

if __name__ == "__main__":
    main(...)
```

**Comment by lcf2610** [comment]
> In infer.py:
> 
> ```
> def init_model(config):
>     mod = Model(config)  # or load model from somewhere
>     # Perform parallelism as needed
>     return mod
> 
> def main(...):
>     config = ...
>     model = init_model(config)
>     while(condition):
>         output = model(input)
> 
> if __name__ == "__main__":
>     main(...)
> ```

Thanks，I'm trying your method. If it works, I'll come back and tell you.

**Comment by lcf2610** [comment]
> > I found that torchrun is mainly used for model training, so can it be used for model inference?
> 
> Yes you can. Same cmd interface:
> 
> ```
> torchrun --nproc-per-node 2 infer.py
> ```

I have another question.  The purpose of using torchrun is to speed up, so if I run infer.py with the command above and do inference only once in the infer.py, can I speed up the infer process? And what are the reasons for whether or not? Thanks

**Comment by wconstab** [comment]
Doing multi card inference requires you to add logic to your model to make it run in a distributed way. For example using tensor or pipeline parallelism. @kwen2501 is working on this area.

I did not understand your point about doing loading in one process and inference in another. You would need to load the model (or at least part of the model) onto each card, before doing inference.

**Comment by lcf2610** [comment]
> Doing multi card inference requires you to add logic to your model to make it run in a distributed way. For example using tensor or pipeline parallelism. @kwen2501 is working on this area.
> 
> I did not understand your point about doing loading in one process and inference in another. You would need to load the model (or at least part of the model) onto each card, before doing inference.

I don't have a clear understanding of the "Using tensor or pipeline parallelism". Where should I make these changes? In the model code, torchrun source code, or the startup script infer.py?
And I didn't mean "doing loading in one process and inference in another". The two are not parallel, but serial. My understanding is that in the inference process, you need to load the model first, and then use the loaded model for inference. Model loading is time-consuming, so I want to load the model only at the first inference and leave the loaded model there so that later inferences can be made directly using the loaded model instead of taking time to load it again.

**Comment by kwen2501** [comment]
Yeah, you need to somehow make your model parallel. 
1. For a general notion of Tensor Parallel and the torch API available today, you can refer to this [documentation](https://pytorch.org/docs/stable/distributed.tensor.parallel.html).
2. For how to apply TP, there are multiple reference implementation:
- in torchchat (an inference library):
It has a `model.distribute()` call, which recursively apply TP to each submodule, [link](https://github.com/pytorch/torchchat/blob/f20f5e792d1114c9ee501f92b6fed3f2e840c99e/torchchat/model.py#L679-L695)
- in torchtitian (a pretraining library):
It has an out-of-model `apply_tp` function which applies TP per submodules' Fully Qualified Name, [link](https://github.com/pytorch/torchtitan/blob/d7cabfb6cc987f9310a4bfa5b87b1dbb8974b10c/torchtitan/parallelisms/parallelize_llama.py#L137).
- or some efforts we are recently collaborating with Hugging Face, where you get a tensor parallelized model out of the box: [link](https://github.com/huggingface/transformers/pull/34184).

**Comment by lcf2610** [comment]
> > > I found that torchrun is mainly used for model training, so can it be used for model inference?
> > 
> > 
> > Yes you can. Same cmd interface:
> > ```
> > torchrun --nproc-per-node 2 infer.py
> > ```
> 
> I have another question. The purpose of using torchrun is to speed up, so if I run infer.py with the command above and do inference only once in the infer.py, can I speed up the infer process? And what are the reasons for whether or not? Thanks

Further, when I run infer.py with the command above and do inference only once in the infer.py, and the model used is InternVL2-8B from huggingface. Whether '--nproc-per-node 2' will infer only once and about twice as fast as '--nproc-per-node 1' or do the inference twice and each inference is just as fast as '--nproc-per-node 1'

**Comment by lcf2610** [comment]
> > > > I found that torchrun is mainly used for model training, so can it be used for model inference?
> > > 
> > > 
> > > Yes you can. Same cmd interface:
> > > ```
> > > torchrun --nproc-per-node 2 infer.py
> > > ```
> > 
> > 
> > I have another question. The purpose of using torchrun is to speed up, so if I run infer.py with the command above and do inference only once in the infer.py, can I speed up the infer process? And what are the reasons for whether or not? Thanks
> 
> Further, when I run infer.py with the command above and do inference only once in the infer.py, and the model used is InternVL2-8B from huggingface. Whether '--nproc-per-node 2' will infer only once and about twice as fast as '--nproc-per-node 1' or do the inference twice and each inference is just as fast as '--nproc-per-node 1'

I followed your suggestion and got the results (although I still don't know how my model run in parallel). I found that compared with using 1 node, using 2 nodes will make the inference latency decreases by 26%.  However, using 4 nodes will only make the inference latency decreases by 18%. So my another question is: why is the latency of using 4 nodes more than that of using 2?  Is this caused by the time-consuming communication between different nodes?

**Comment by kwen2501** [comment]
What do you mean by "node" here? Do you actually mean a GPU?
Nevertheless, yes, communication overhead negating computation sharing is possible. Particularly when on system with slow interconnects.

**Comment by lcf2610** [comment]
> What do you mean by "node" here? Do you actually mean a GPU? Nevertheless, yes, communication overhead negating computation sharing is possible. Particularly when on system with slow interconnects.

Yes, and more precisely is NPU, I guess using torchrun may gain better  performance on GPUs, but adaptation on NPUs is still insufficient.

**Comment by lcf2610** [comment]
> What do you mean by "node" here? Do you actually mean a GPU? Nevertheless, yes, communication overhead negating computation sharing is possible. Particularly when on system with slow interconnects.

But I still don't know why the inference latency is reduced (though not much), because I didn't make any changes to the model, just using the command "torchrun --nproc_per_node 2 infer.py". What exactly did torchrun do?
