### ISSUE TITLE
torch.masked_select result in out of memory when using cuda

### ISSUE THREAD

**Issue by HyacinthJingjing** [pytorch/pytorch#13882]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
Here are my source codes:
    def forward(self, prob, target, reward):
        """
        Args:
            prob: (N, C), torch Variable
            target : (N, ), torch Variable
            reward : (N, ), torch Variable
        """
        N = target.size(0)
        C = prob.size(1)
        one_hot = torch.zeros((N, C))
        if prob.is_cuda:
            one_hot = one_hot.cuda()
        one_hot.scatter_(1, target.data.view((-1,1)), 1)
        one_hot = one_hot.type(torch.ByteTensor)
        one_hot = Variable(one_hot)
        if prob.is_cuda:
            one_hot = one_hot.cuda()
        loss = torch.masked_select(prob, one_hot)
        loss = loss * reward
        loss =  -torch.sum(loss)
        return loss
When N=2000 and C=240755, once the line "loss = torch.masked_select(prob, one_hot)" runs, the memory of GPU seems doubled. Is this phenomena normal and how to prevent it?

**Comment by soumith** [comment]
https://discuss.pytorch.org/
