### ISSUE TITLE
Using shape dependent conditionals with export resulted in weird KeyError

### ISSUE THREAD

**Issue by henrylhtsang** [pytorch/pytorch#138847]
### 🐛 Describe the bug

Hi, I know this isn't supposed to work, but just want to report the error. The right way is to use torch.cond, which works pretty well.

repro:
```python
class M(torch.nn.Module):
    def forward(self, x):
        if x.size(0) % 2 == 0:
            return x.clone() * 2
        else:
            return x.clone() * 0

input1 = (torch.rand(size=(4,), device="cuda"),)
model = M().cuda()

_ = model(*input1)

dynamic_shapes = {
    "x": {0: torch.export.Dim.DYNAMIC},
}
ep = torch.export.export(model, input1, dynamic_shapes=dynamic_shapes, strict=False)
```

errors:
```
torch/fx/experimental/symbolic_shapes.py", line 2441, in solve
    tmp_name = f"_{self._dcp.source_name_to_debug_name[self._dcp.symbol_to_source[s][0].name()]}"
KeyError: "L['args'][0][0].size()[0]"
```

### Versions

trunk

cc @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by pianpwk** [comment]
I don't think there's anything wrong with the program itself, putting this up: https://github.com/pytorch/pytorch/pull/139104

**Comment by henrylhtsang** [comment]
> I don't think there's anything wrong with the program itself, putting this up: #139104

Umm I think my example is not supposed to work, since it is a shape dependent thing? I have seen errors like "cannot conditionals on shape" etc

**Comment by pianpwk** [comment]
There's a distinction between Python branching conditions in the code like you wrote, and usage of `torch.cond()`. In the 1st case the program will just specialize on the branch taken during initial compilation (in this case based on the sample inputs, the case where `x.size(0) % 2 == 0`), and add a guard to the program. With `torch.cond()` both paths are traced and "kept alive" in the program, and control flow is available at runtime.

I think data-dependent control flow (e.g. `if x.item() > 0`) doesn't work with torch.cond, but shape-dependent like this should be fine.

**Comment by henrylhtsang** [comment]
closing cuz fixed in https://github.com/pytorch/pytorch/pull/139104/files
