### ISSUE TITLE
Importing an opencv GpuMat

### ISSUE THREAD

**Issue by leconteur** [pytorch/pytorch#13898]
## 🐛 Bug

Contrary to opencv Mat objects, GpuMat are strided in memory. It seems impossible to tell the torch::from_blob method from the c++ api this information. We used to build our tensor directly with A10 which provided this options. 

## To Reproduce

```
#include <torch/script.h> // One-stop header.

#include <iostream>
#include <memory>
#include <opencv2/opencv.hpp>
#include <opencv2/core/cuda.hpp>
//#include "opencv2/gpu/gpu.hpp"

using namespace cv;

int main(int argc, const char* argv[]) {
    Mat gray_image = Mat::ones(9, 9, CV_32FC1); 
    Mat image;
    cvtColor(gray_image, image, COLOR_GRAY2RGB);

    cuda::GpuMat gImage;
    gImage.upload(image);
    std::vector<int64_t> sizes = {static_cast<int64_t>(gImage.channels()),
                              static_cast<int64_t>(gImage.rows),
                              static_cast<int64_t>(gImage.cols)};

    auto options = torch::TensorOptions().dtype(torch::kFloat32).device(torch::kCUDA);
    auto tensor_image = torch::from_blob(gImage.data, torch::IntList(sizes), options);
    std::cout << tensor_image << std::endl;
    return 0;
}
```
This produced the following output.
```
(1,.,.) = 
  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0

(2,.,.) = 
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1
  1  1  0  0  0  0  0  0  0

(3,.,.) = 
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
[ Variable[CUDAFloatType]{3,9,9} ]
Segmentation fault (core dumped)
```

## Expected behavior

If I use only opencv Mat, I get a tensor filled with ones.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0 nightly
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.5
 - CUDA/cuDNN version: CUDA runtime version: 8.0.61
 - GPU models and configuration: Tesla K40

**Comment by soumith** [comment]
cc: @goldsborough 
I guess we need a way to expose `strides` to `from_blob`

**Comment by goldsborough** [comment]
Wait what about [this guy](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/templates/NativeFunctions.h#L34):

```cpp
inline Tensor from_blob(
    void* data,
    IntList sizes,
    IntList strides,
    const std::function<void(void*)>& deleter,
const TensorOptions& options = {})
```

**Comment by leconteur** [comment]
That seems to be what I am looking for. Is there documentation somewhere on what is the deleter argument?

**Comment by leconteur** [comment]
Thank you for your help. It does work with those modifications.
```
#include <torch/script.h> // One-stop header.

#include <iostream>
#include <memory>
#include <opencv2/opencv.hpp>
#include <opencv2/core/cuda.hpp>
#include <ATen/ATen.h>

using namespace cv;

void deleter(void* arg) {};

int main(int argc, const char* argv[]) {
    Mat gray_image = Mat::ones(9, 9, CV_32FC1); 
    Mat image;
    cvtColor(gray_image, image, COLOR_GRAY2RGB);

    cuda::GpuMat gImage;
    gImage.upload(image);
    std::vector<int64_t> sizes = {1, static_cast<int64_t>(gImage.channels()),
                              static_cast<int64_t>(gImage.rows),
                              static_cast<int64_t>(gImage.cols)};
    long long step = gImage.step / sizeof(float);
    std::vector<int64_t> strides = {1, step, static_cast<int64_t>(gImage.channels())};

    auto options = torch::TensorOptions().dtype(torch::kFloat32).device(torch::kCUDA);
    auto tensor_image = at::from_blob(gImage.data, torch::IntList(sizes), torch::IntList(strides), deleter,  options);
    std::cout << tensor_image << std::endl;
    return 0;
}

```

However, I did not manage to import it from <torch/script.h> and had to import it with aten and I had to write a deleter empty function. I think that exposing directly a version of from_blob with the strides could be a plus.

**Comment by goldsborough** [comment]
@leconteur You need to change `at::from_blob` to `torch::from_blob`. That will create a variable instead of a tensor. If you upgrade to the latest nightly you can just use `torch::` instead of `at::` for everything and avoid such details. So just change

```cpp
auto options = torch::TensorOptions().dtype(torch::kFloat32).device(torch::kCUDA);
auto tensor_image = at::from_blob(gImage.data, torch::IntList(sizes), torch::IntList(strides), deleter,  options);
```

to

```cpp
auto tensor_image = torch::from_blob(gImage.data, sizes, strides, deleter,  torch::kCUDA);
```

Notice I removed the explicit `at::IntList()` conversions -- those happen implicitly. An you can reduce the whole line about creating tensor options to just `torch::kCUDA` -- float32 is the default already. Also see https://pytorch.org/cppdocs/notes/tensor_creation.html for a tutorial on how to create tensors.

I'll also send a PR to make the deleter an optional argument for the overload that takes strides.

**Comment by goldsborough** [comment]
Oh wait, I see there is no `torch::` version of this overload you need. Let me add that.

**Comment by goldsborough** [comment]
Fixing in https://github.com/pytorch/pytorch/pull/13982

**Comment by jxmelody** [comment]
hi, @leconteur 
I am using OpenCV to load images too, but got some troubles in ***cmake & make*** , my CMakeList.txt looks like this
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(custom_ops)
find_package(OpenCV )
find_package(Torch  )
add_executable(example-app test.cpp)
target_link_libraries(example-app "${TORCH_LIBRARIES}" "${OPENCV_LIBRARIES}")
set_property(TARGET example-app PROPERTY CXX_STANDARD 11)
                                                                        
```  

I used ```cmake -DCMAKE_PREFIX_PATH="/usr/local/cv;../libtorch .." ``` to produce MakeFile.I've got no errors after this,  but when I did ```make```, It showed me some strange errors:
```fatal error: opencv2/core.hpp: no such a file or directory```

Could you please letting me know how you wrote CMakeFile and cmake commands? Or more generally, do you know what is wrong in my situation? 

Also I've tired  to use gcc or qmake with including the ```include``` and ```lib```dir ,It would turn out 
>/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: warning: libnvToolsExt-3965bdd0.so.1, needed by /home/xiaojin/workspace/download/libtorch/lib/libtorch.so, not found (try using -rpath or -rpath-link)
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: warning: libcaffe2_gpu.so, needed by /home/xiaojin/workspace/download/libtorch/lib/libtorch.so, not found (try using -rpath or -rpath-link)
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: warning: libc10.so, needed by /home/xiaojin/workspace/download/libtorch/lib/libtorch.so, not found (try using -rpath or -rpath-link)
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: warning: libgomp-7bcb08ae.so.1, needed by /home/xiaojin/workspace/download/libtorch/lib/libcaffe2.so, not found (try using -rpath or -rpath-link)
test.o：in function ‘c10::intrusive_ptr_target::~intrusive_ptr_target()’：
test.cpp:(.text._ZN3c1020intrusive_ptr_targetD2Ev[_ZN3c1020intrusive_ptr_targetD5Ev]+0x126)：‘c10::Error::Error(c10::SourceLocation, std::string const&)’undefined reference
test.cpp:(.text._ZN3c1020intrusive_ptr_targetD2Ev[_ZN3c1020intrusive_ptr_targetD5Ev]+0x256)：‘c10::Error::Error(c10::SourceLocation, std::string const&)’undefined reference
test.o：In function ‘c10::Device::Device(c10::DeviceType, short)’：
test.cpp:(.text._ZN3c106DeviceC2ENS_10DeviceTypeEs[_ZN3c106DeviceC5ENS_10DeviceTypeEs]+0xe4)：‘c10::Error::Error(c10::SourceLocation, std::string const&)’undefined reference
test.cpp:(.text._ZN3c106DeviceC2ENS_10DeviceTypeEs[_ZN3c106DeviceC5ENS_10DeviceTypeEs]+0x1f7)：‘c10::Error::Error(c10::SourceLocation, std::string const&)’undefined reference

Thanks!

**Comment by jxmelody** [comment]
Thanks, @leconteur 
I use qmake to compile and succeed . 
But I still have one question: Have you load images by OpenCV correctly?  I got a tensor filled with ones ( just like you post above).

**Comment by goldsborough** [comment]
https://github.com/pytorch/pytorch/pull/13982 landed. `from_blob` with strides is now available.
