### ISSUE TITLE
Cannot load a saved torch.jit.trace using C++'s torch::jit::load

### ISSUE THREAD

**Issue by hagerrady13** [pytorch/pytorch#13897]
## 🐛 Bug

I saved a model in PyTorch python using torch.jit.save. I tried to load the model in C++ using    torch::jit::load("model.pt"); but it produced the following error.

## To Reproduce
Follow the tutorial here: https://shiftlab.github.io/pytorch_tutorials/advanced/cpp_export.html

1. [Converting a torch model via tracing](https://shiftlab.github.io/pytorch_tutorials/advanced/cpp_export.html#converting-to-torch-script-via-tracing)
2. [Serializing the model](https://shiftlab.github.io/pytorch_tutorials/advanced/cpp_export.html#step-2-serializing-your-script-module-to-a-file)
3. [Loading the script module in C++](https://shiftlab.github.io/pytorch_tutorials/advanced/cpp_export.html#step-3-loading-your-script-module-in-c)

## Error Message 
terminate called after throwing an instance of 'c10::Error'
  what():  read_bytes == 8 ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.h:182, **please report a bug to PyTorch**. Expected to read 8 bytes but got %llu bytes0 (read64BitIntegerLittleEndian at /pytorch/caffe2/serialize/inline_container.h:182)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f39eaf7ecd1 in /**/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f39eaf7e59a in /**/libtorch/lib/libc10.so)
frame #2: <unknown function> + 0x58df5b (0x7f39f478ff5b in /**/libtorch/lib/libtorch.so.1)
frame #3: <unknown function> + 0x58ecc5 (0x7f39f4790cc5 in /**/libtorch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x58f0e3 (0x7f39f47910e3 in /**/libtorch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x58c41d (0x7f39f478e41d in /**/libtorch/lib/libtorch.so.1)
frame #6: torch::jit::load(std::istream&) + 0xb4 (0x7f39f478f5d4 in /**/libtorch/lib/libtorch.so.1)
frame #7: torch::jit::load(std::string const&) + 0x27 (0x7f39f478f6a7 in /**/libtorch/lib/libtorch.so.1)
frame #8: main + 0x68 (0x40125b in ./mnist)
frame #9: __libc_start_main + 0xf0 (0x7f39eb1aa830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #10: _start + 0x29 (0x401089 in ./mnist)

Aborted (core dumped)

## Expected behavior

https://shiftlab.github.io/pytorch_tutorials/advanced/cpp_export.html#step-4-executing-the-script-module-in-c

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.0.0.dev20181029
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: Quadro M2000

Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] torch (1.0.0.dev20181029)
[pip] torch-vision (0.1.6.dev0)
[pip] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] pytorch-nightly           1.0.0.dev20181029 py3.6_cuda9.0.176_cudnn7.1.2_0    pytorch
[conda] torch                     0.3.0.post4               <pip>
[conda] torch                     0.4.1                     <pip>
[conda] torch-vision              0.1.6.dev0                <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by soumith** [comment]
cc: @houseroad @suo

**Comment by houseroad** [comment]
@hagerrady13 did you serialize the same model as in the tutorial? If not, is there any chance, you can upload your model so I can use it to reproduce the problem?

**Comment by hagerrady13** [comment]
@houseroad The model is serialized exactly the same way as in the tutorial.

**Comment by hagerrady13** [comment]
@houseroad any updates regarding this issue?

**Comment by houseroad** [comment]
@hagerrady13 I have tested resnet18 and mnist locally (just followed the tutorials https://pytorch.org/tutorials/advanced/cpp_export.html), and they work well. I am wondering how you save your models. Could you please paste the code you used to store the models?

**Comment by hagerrady13** [comment]
@houseroad I have upgraded both pytorch python API and libtorch to version **1.0.0.dev20181121** and now my code works fine. Thank you!

However, I am getting inference time much slower than the python model, is this normal? 
For Resnet50 for example, the python model gets makes 200 ms per frame but the serialized model gets 600 ms per frame after the de-serialization in C++.

**Comment by soumith** [comment]
@hagerrady13 this is not normal, and not expected either. I cant reproduce it on my side.

**Comment by hagerrady13** [comment]
@soumith I don't know why you can't reproduce it and I found some people facing the same thing in [this issue](https://github.com/pytorch/pytorch/issues/14033).

**Comment by soumith** [comment]
@hagerrady13 i know it's been a while, but the resnet50 slowdown was related to 1.0 not having aliasing / mutation passes. Can you give 1.1 a try, and see if that fixes things (and reopen the issue if it doesn't)
