### ISSUE TITLE
[Caffe2] SSD models inference

### ISSUE THREAD

**Issue by ArutyunovG** [pytorch/pytorch#13896]
Hi,

I'm considering to implement SSD models inference (but not training) in Caffe2. The models are trained either in TF OD API or in Caffe SSD branch. In both cases, they do essentially the same, with some minor implementation differences. I was able to port models directly from TF OD API to Caffe SSD with identical results, so they do the same.

As far as I know, at the moment, there is no DetectionOutput layer (with class agnostic nms) equivalent. Also, Mask R-CNN's use im_info and input FM height and width to figure out, how to tile anchors, which are implemented as separate blob. So there is no PriorBox layer as well, which performs tiling.

There seem to be three solutions here: 1) modify BoxWithNMSLimit/GenerateProposals and related stuff, 2) write separate PriorBoxOp and DetectionOutputOp; 3) don't change anything in Caffe2: just write separate utility code that implements detection output (priorboxes are tiled just in this code based on input size). In this case the code runs over concats of bbox deltas and confidences after the network is finished.

Is there any interest in such contribution? How is it better for you to implement those if there is interest?
In any case, at the moment I'm interested in porting Caffe2 with max existing fucntionality to Windows, so this is a question on possible future continuation of Caffe2 usage.

**Comment by ArutyunovG** [comment]
Hi @BIT-silence,
Can you please provide your thoughts on this?

**Comment by orionr** [comment]
Also cc @newstzpz

**Comment by BIT-silence** [comment]
Hi @ArutyunovG. I'm sorry that I am on a vocation now. I will review it later today, is that fine?

**Comment by ArutyunovG** [comment]
@BIT-silence  
Oh, sure, thank you! This is not a hurry anyhow, just discussion of Caffe2's part of a broader work. 
Have a nice vacation.

**Comment by ArutyunovG** [comment]
Thanks for adding enough changes to update our branch of caffe2 without conflicts. 

For those, coming outside this is the branch with SSD implementation:
https://github.com/ArutyunovG/pytorch/tree/iss
