### ISSUE TITLE
[Inductor][AOTInductor] `test_constant_folding_abi_compatible_cpu` surfaces `CUDA error: invalid argument` on H100

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#138958]
### 🐛 Describe the bug

I see that this test seems to have been removed about 3 days ago in #138016 @desertfire was this intentional and an expected failure? It was not marked as a skip apparently

### Versions

builds before #130816

cc @ptrblck @msaroufim @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by eqy** [comment]
CC @nWEIdia @tinglvv as we have observed this failure in our CI

**Comment by desertfire** [comment]
Similar to my comment at https://github.com/pytorch/pytorch/pull/138016#issuecomment-2422995500, there was a test renaming. It should be `test_constant_folding_cpu` now. Also since it is a cpu test, I don't see why it triggers a CUDA error.
