### ISSUE TITLE
Better error messaging for requiring ModuleList to be constant

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#13899]
## 🚀 Feature
```
def __init__
        // ....
        self.conv_lstms = nn.ModuleList(conv_lstms)
        // ...

def forward()
        for i in range(len(self.cell_n)):
            cell = self.conv_lstms[i]
```

```
python value of type 'ModuleList' cannot be used as a value:
def forward(self, inputs, hidden):
    for i in range(len(self.cell_n)):
        cell = self.conv_lstms[i]
               ~~~~~~~~~ <--- HERE
        hidden[i] = cell(step_input, hidden[i])
        step_input = hidden[i][0]

    return step_input, hidden
```

The fix in the above case is to declare `__constants__ = ["conv_lstms"]`

So the error message should say that `ModuleList` should be declared constant

## Motivation
The error message is very unclear for new users.

**Comment by sto-chastic** [comment]
My code (follows) appends to ModuleList, therefore when I declare ModuleList as constant, I get the error:
> AttributeError: _ConstModuleList object has no attribute append

Is there a work arround for this?
Code:

`class resblock(ScriptModule):
    __constants__ = ["module_list"]

    def __init__(self, ch, nblocks=1, shortcut=True):

        super().__init__()
        self.shortcut = shortcut
        self.module_list = nn.ModuleList()
        for i in range(nblocks):
            resblock_one = nn.ModuleList()
            resblock_one.append(add_conv(ch, ch//2, 1, 1))
            resblock_one.append(add_conv(ch//2, ch, 3, 1))
            self.module_list.append(resblock_one)

    @script_method
    def forward(self, x):
        for i in range(len(self.module_list)):
            module = self.module_list[i]
            h = x
            for res in module:
                h = res(h)
            x = x + h if self.shortcut else h
        return x`

**Comment by sidazhang** [comment]
You need to append the resnet blocks into an array and then initialize the module_list

For example

m = []
m.append(blah)
self.module_list = nn.ModuleList(m)

**Comment by eellison** [comment]
https://github.com/pytorch/pytorch/pull/17167 suggests add to `__constants__` when a module list is used as a tuple
