### ISSUE TITLE
In-place matrix multiplication gives erroneous results.

### ISSUE THREAD

**Issue by rhaps0dy** [pytorch/pytorch#13892]
## To Reproduce

Run the following snippet.

```python
import torch
torch.random.manual_seed(1)
N=4
b = torch.randn([N, N], device='cpu')
print(b @ b.t())
torch.mm(b, b.t(), out=b)
print(b)
```

Output:
```
tensor([[ 5.9084,  3.8404,  1.7716, -1.8287],
        [ 3.8404,  3.9303,  1.0525, -1.9818],
        [ 1.7716,  1.0525,  1.2668,  0.3756],
        [-1.8287, -1.9818,  0.3756,  3.1666]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
```

CUDA seems to work well in this case, maybe because the matrix is small, but you can make it fail too:

```python
import torch
torch.random.manual_seed(1)
N=5000
b = torch.randn([N, N], device='cuda')
print(torch.any(torch.isnan(b @ b.t())))
torch.mm(b, b.t(), out=b)
print(torch.any(torch.isnan(b)))
```

Output:
```
tensor(0, device='cuda:0', dtype=torch.uint8)
tensor(1, device='cuda:0', dtype=torch.uint8)

```

## Expected behavior

We would expect the two matrices to have the same result. In the second one, we would not expect a NaN to appear after a Matrix multiplication.

Probably storing the result to the same place where you're reading it from is unrealistic, in this case, an exception or warning should be raised if the user does this. Or it should be written in the documentation (maybe it is? I haven't read _all_ of it).

## Environment

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

PyTorch was installed using pip.

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 396.44
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.3
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

**Comment by SsnL** [comment]
Setting `out` to overlap with input is highly advised against. It is really unstable.

**Comment by soumith** [comment]
Yes, we dont expect this to work.

**Comment by soumith** [comment]
closing as `wontfix`

**Comment by mrTsjolder** [comment]
Any chance this instability could be reflected in the docs? E.g. by explicitly stating that `out` should be different from any of the inputs.
