### ISSUE TITLE
Weights only load numpy.float64 fails in torch 2.4.0

### ISSUE THREAD

**Issue by JohannesTheo** [pytorch/pytorch#138985]
## torch.load(weights_only=True) fails for numpy.float64 in  torch 2.4.0

Loading a checkpoint with `weights_only=True` fails for a `numpy.float64` value even after adding the requested modules with `add_safe_globals`. I'm using torch 2.4.0 and numpy 1.26.3. I've seen the [comment in the main branch](https://github.com/pytorch/pytorch/blob/main/torch/_weights_only_unpickler.py#L153) and probably this is a numpy issue and its dtypes but since the error message suggest to open an issue I did. My workaround is to save the value in question as tensor. 

Feel free to close with short comment, thx :)

```bash
UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
 Please file an issue with the following so that we can make `weights_only=True` compatible with your use case: WeightsUnpickler error: Can only build Tensor, parameter or OrderedDict objects, but got <class 'numpy.dtypes.Float64DType'>

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
```

## reproduce

torch 2.4.0, numpy 1.26.3

```python
import torch
import numpy as np

checkpoint = { 'test': np.float64(0) }
torch.save(checkpoint, './test.pth')

# unsafe load
checkpoint = torch.load('./test.pth', weights_only=False)
t = checkpoint['test']
m = f"{type(t).__module__}.{type(t).__name__}"
print(t, type(t), m)

# safe load
from numpy.core.multiarray import scalar
from numpy import dtype
torch.serialization.add_safe_globals([scalar, dtype])
checkpoint = torch.load('./test.pth', weights_only=True)
```

### Versions

Shortened output:

PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1

OS: Debian GNU/Linux 12 (bookworm) (x86_64)

Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.1.0-22-amd64-x86_64-with-glibc2.36

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==2.4.0+cu121

**Comment by vulkomilev** [comment]
I am on it

**Comment by vulkomilev** [comment]
can you please provide the files relevant to the issue(test.pth)

**Comment by JohannesTheo** [comment]
Hey, you can create the file with: `torch.save({ 'test': np.float64(0) }, './test.pth')`

**Comment by JohannesTheo** [comment]
After some testing, it seems I fooled myself. The following does work.

```python
from numpy.core.multiarray import scalar
from numpy import dtype
from numpy.dtypes import Float64DType
from _codecs import encode
torch.serialization.add_safe_globals([scalar, dtype, Float64DType, encode])

checkpoint = torch.load('./test.pth', weights_only=True)
```
