### ISSUE TITLE
ImportError: /home/caomeng/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch.so.1: undefined symbol: _ZTIN2at10TensorImplE

### ISSUE THREAD

**Issue by rookiecm** [pytorch/pytorch#13893]
## To Reproduce

After executing the following command in the command line:

conda install pytorch-nightly -c pytorch

I install the pytorch1.0

However when I tried to import torch, I get the following mistake:

Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import torch
  File "/home/caomeng/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: /home/caomeng/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/lib/libtorch.so.1: undefined symbol: _ZTIN2at10TensorImplE

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source):  conda
 - Build command you used (if compiling from source): 
 - Python version: 3.7
 - CUDA/cuDNN version:  CUDA 8
 - GPU models and configuration:
 - Any other relevant information:

**Comment by soumith** [comment]
you have a mix of pytorch-nightly and pytorch packages, maybe because of installing a library after installing pytorch-nightly that installed pytorch 0.4.1.

Do this:

```
conda uninstall -y pytorch-nightly
conda uninstall -y pytorch
pip uninstall -y torch
pip uninstall -y torch
pip uninstall -y torch

conda install -y pytorch-nightly
```

**Comment by daydayjump** [comment]
Same problem. And it does not work even I uninstall pytorch

**Comment by soumith** [comment]
@daydayjump you have a spurious libaten somewhere on your system. Find it and delete it.

**Comment by daydayjump** [comment]
> @daydayjump you have a spurious libaten somewhere on your system. Find it and delete it.

Thank you so much. I found a wrong LD_LIBRARY_PATH in the ~/.bashrc. When I deleted it, the problem was solved.

**Comment by Baby47** [comment]
@ daydayjump
Hi, I have installed caffe2 and update my pytorch version to 1.0. When I import torch under Python 3.7, the error is : File "/home/babychen/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: /home/babychen/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so.1: undefined symbol: _ZTIN2at10TensorImplE
I wonder which LD_LIBRARY_PATH in the ~/.bashrc is exactly needed. Thanks a lot !

**Comment by Soar-Sir** [comment]
Me,too. I also meet the same problem, and I want to know which  LD_LIBRARY_PATH in the ~/.bashrc is exactly needed. Thanks a lot !
