### ISSUE TITLE
Bug in Maxpool2d Operator Exhibited During Metamorphic Testing

### ISSUE THREAD

**Issue by Lynn-zkx** [pytorch/pytorch#139078]
## Introduction
I am using metamorphic testing based on a methodology called Meta. The metamorphic relation I applied is described as follows:

> MP(data) * delta = MP(data * delta). 

+ **delta** is a random number selected within a defined threshold, which I set to **10**.

For the maxpool2d operator in PyTorch, I fed the same input data into both the original and mutated operators. After calculating the L1 distance between their outputs, I noticed that the L1 distance is sometimes significantly larger than expected,with some values reaching the magnitude of **1e5**. Based on the provided metamorphic relation, the two outputs should be equal; therefore, the excessive L1 distance indicates the presence of a bug.

This inconsistency raises concerns about the correctness of the operator.

## Code
Here is a simplified version of the code below:

```
import sys
import numpy as np
import torch
from torch import tensor
from torch.nn import MaxPool2d

DEVICE = "cpu" # gpu
FORMAT = "NCHW" # NHWC
DTYPE = "float32"
DELTA = 10 # [100, 50, 10, 1, 0.1, 0.01, 0.001]
SHAPE = (10, 3, 32, 32)
DATA_RANGE = [-1, 1]

def norm_dis(source_result, follow_result, ord="l1"):
    if ord == "l1":
        dis = torch.sum(torch.abs_(source_result-follow_result))
    elif ord == "l2":
        dis = torch.norm(source_result - follow_result)
    return dis

def generate_data(shape, device):
    return torch.from_numpy(np.random.uniform(DATA_RANGE[0], DATA_RANGE[1], shape).astype(DTYPE)).float().to(device)

def SourceModel():
    pool_size = np.random.randint(1, 5)
    strides = np.random.randint(1, 5)
    pool = MaxPool2d(kernel_size=(pool_size, pool_size), stride=(strides, strides))
    return pool


def maintest():
    torch.set_printoptions(precision=8)

    device = torch.device('cuda' if DEVICE == "gpu" else "cpu")
    shape = SHAPE
    d_format = torch.channels_last if FORMAT == "NHWC" else torch.contiguous_format
    for i in range(100):
        source_model = SourceModel().to(device).to(memory_format=d_format).eval()
        data = generate_data(shape, device).to(memory_format=d_format)

        delta = tensor(np.random.uniform(-DELTA, DELTA, 1)[0]).to(device)
        source_result = source_model.forward(data) * delta
        follow_result = source_model.forward(data * delta)
        dis = norm_dis(source_result, follow_result).cpu().detach().numpy()[()]
        if dis >= 1:
            print(dis)


if __name__ == "__main__":
    maintest()
    print("end")
```

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-213-generic-x86_64-with-glibc2.27
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
Stepping:            7
CPU MHz:             2299.998
BogoMIPS:            4599.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch topoext cpuid_fault invpcid_single pti ssbd ibrs ibpb fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat umip pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] numpy==1.25.1
[pip3] optree==0.13.0
[conda] numpy                     1.25.1                   pypi_0    pypi
[conda] optree                    0.13.0                   pypi_0    pypi

**Comment by ezyang** [comment]
The proposed relation is only valid when the operator in question is linear, which is not here.
