### ISSUE TITLE
[inductor][rocm] Cooperative reductions on AMD GPUs

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#139099]
#137756 adds support for generating cooperative reductions in Triton, something like:
```py
@triton.jit
def triton_unk_fused_add_sum_0(in_ptr0, in_ptr1, out_ptr0, ws_ptr, semaphores_ptr, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr, RSPLIT : tl.constexpr):
    xnumel = 1
    rnumel = 1048576
    rsplit_id = tl.program_id(0)
    num_rblocks = (rnumel + RBLOCK - 1) // RBLOCK
    rsplit_chunk = (num_rblocks + RSPLIT - 1) // RSPLIT * RBLOCK
    rsplit_start = rsplit_chunk * rsplit_id
    rsplit_end = rsplit_chunk * (rsplit_id + 1)
    xoffset = tl.program_id(1) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
    xmask = tl.full([XBLOCK, RBLOCK], True, tl.int1)
    rbase = tl.arange(0, RBLOCK)[None, :]
    _tmp4 = tl.full([XBLOCK, RBLOCK], 0, tl.float32)
    for roffset in range(rsplit_start, rsplit_end, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r0 = rindex
        tmp0 = tl.load(in_ptr0 + (r0), rmask, eviction_policy='evict_first', other=0.0)
        tmp1 = tl.load(in_ptr1 + (r0), rmask, eviction_policy='evict_first', other=0.0)
        tmp2 = tmp0 + tmp1
        tmp3 = tl.broadcast_to(tmp2, [XBLOCK, RBLOCK])
        tmp5 = _tmp4 + tmp3
        _tmp4 = tl.where(rmask, tmp5, _tmp4)
    tmp4 = tl.sum(_tmp4, 1)[:, None]
    if RSPLIT > 1:
        tmp4_ws = (ws_ptr + 0).to(tl.pointer_type(tl.float32))
        tl.store(tmp4_ws + (xindex * RSPLIT + rsplit_id), tmp4, None)
    if RSPLIT > 1:
        triton_helpers.gpu_barrier(semaphores_ptr + (2 * tl.program_id(1) + 0), RSPLIT, True)
    if RSPLIT > 1:
        tmp4_peers = tl.load(tmp4_ws + (xindex * RSPLIT + tl.arange(0, RSPLIT)[None,:]), None, eviction_policy='evict_first')
        tmp4 = tl.sum(tmp4_peers, 1)[:, None]
    if rsplit_id == (0 % RSPLIT):
        tl.store(out_ptr0 + (tl.full([XBLOCK, 1], 0, tl.int32)), tmp4, None)
```
where you have a grid-wide barrier allowing multiple thread groups to exchange data.

According to https://github.com/pytorch/pytorch/pull/137756#issuecomment-2441579322 these kernels time out on ROCM.

Can someone from the AMD team take a look at getting cooperative reductions working on AMD hardware?

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov

**Comment by tenpercent** [comment]
@jansel could you share a runnable repro script, e.g. the generated wrapper code, for the cases which are timing out? AMD's Triton folks could look into that

**Comment by jansel** [comment]
Once that PR lands you should be able to repro with:
```bash
# remove Rocm skips
sed -i '/@skipIfRocm/d' test/inductor/test_cooperative_reductions.py

# run tests
python test/inductor/test_cooperative_reductions.py
```

**Comment by jataylo** [comment]
Thanks we will will take a look, this could be that we need a commit bump.

Quick question @jansel I know that we skipped the cooperative reduction unit tests on ROCm (https://github.com/pytorch/pytorch/pull/137756) but will this cause other regressions? i.e. do we need to get your PR updated to disable this change on ROCm not just skip the UTs?

**Comment by jataylo** [comment]
The odd thing is that these test pass locally...
```
Ran 45 tests in 26.951s

OK
```

I'm thinking the timeouts may be unrelated...or from another suite.

**Comment by jansel** [comment]
@jataylo cooperative reductions are off by default.  This hope is to turn them on soon though.   I'm trying to get ahead of things by fixing AMD early.

Interesting that you can't reproduce.  I don't have AMD hardware, I was just going by the diff getting reverted due to AMD CI hanging.  Though cooperative reductions will deadlock if only part of the grid is launched, so a hang is plausible.  Maybe the AMD CI machines are a very small GPU?

I put up a PR to re-enable the tests, lets see if they have an issue:
https://github.com/pytorch/pytorch/pull/139230

**Comment by jansel** [comment]
Weird, the tests seem to pass now.  Let's try landing it and see if there are issues.

**Comment by jataylo** [comment]
> Weird, the tests seem to pass now. Let's try landing it and see if there are issues.

Sorry for the late reply here. We had some strange observations on this, locally the UTs passed. Even on the merge they passed but it look like the pytest "non serial" runs hung, we couldn't reproduce this locally again. Seems that it was a flakey issue?

Curious...
