### ISSUE TITLE
Deepwise convolution with `torch.compile` has inconsistent numerical precision with eager mode

### ISSUE THREAD

**Issue by Thinksky5124** [pytorch/pytorch#139169]
### 🐛 Describe the bug

When I use depthwise separable convolutions by setting the convolution's group to the number of input channels, the computation results from the compiled computation graph using `torch.compile` differ from those in eager mode, failing to achieve numerical consistency. However, if I set the group to a value less than the number of input channels(e.g. < 128), numerical consistency is maintained. This issue can be reproduced in versions torch 2.1, torch 2.3, torch 2.4, and torch 2.5. Other versions have not been tested.

```python
# mini case
import torch
import torch.nn as nn

b = 2
value = torch.ones(b, 128, 512, 256, requires_grad=True).cuda()
value.grad = torch.ones_like(value)

model = nn.Conv2d(128, 128, 3, padding=1, groups=128).cuda().train()

res = model(value)
res.backward(torch.ones_like(res))
value_grad = model.weight.grad.detach().clone()

model.weight.grad = None

model_compile = torch.compile(model)

res_ = model_compile(value)
res_.backward(torch.ones_like(res_))
value_grad_ = model.weight.grad.detach().clone()
print(f"Total diff: {torch.mean(res - res_)}, Max diff: {torch.max(res - res_)}")
print(f"Total grad diff: {torch.sum(value_grad - value_grad_)}")
assert torch.allclose(res, res_)
assert value_grad.allclose(value_grad_)
```
Report
```bash
Total diff: 1.0518241833068487e-10, Max diff: 2.384185791015625e-07
Total grad diff: 0.0
Traceback (most recent call last):
  File "/home/users/wujun.wen/exps_saturnv_compile/HAT-internal/.hat_logs/test.py", line 24, in <module>
    assert torch.allclose(res, res_)
AssertionError

## or
Total diff: -3.3587829739722963e-10, Max diff: 1.1920928955078125e-07
Total grad diff: 0.0
```
Sometimes it can pass the allclose check, but the values are not consistent, which is related to the random seed.

But, if set groups < 128, for example `groups=64`. The numerical results are completely consistent.
```bash
Total diff: 0.0, Max diff: 0.0
Total grad diff: 0.0
```
I believe depthwise convolutions are very common and may be present in large numbers within models. If the numerical results are not fully consistent with eager mode under `torch.compile`, it could render `torch.compile` unusable for some convolution neural network.

### Versions

PyTorch version: 2.3.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.1
Libc version: glibc-2.17

Python version: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 535.98
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                96
On-line CPU(s) list:   0-95
Thread(s) per core:    2
Core(s) per socket:    24
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
Stepping:              7
CPU MHz:               3599.853
CPU max MHz:           4000.0000
CPU min MHz:           1200.0000
BogoMIPS:              6000.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0-23,48-71
NUMA node1 CPU(s):     24-47,72-95
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==3.9.2
[pip3] flake8-bugbear==21.4.3
[pip3] flake8-comprehensions==3.6.0
[pip3] flake8-polyfill==1.0.2
[pip3] flake8-tidy-imports==4.5.0
[pip3] horizon-plugin-pytorch==2.4.10+cu118.torch230
[pip3] msgpack-numpy==0.4.8
[pip3] mypy==0.910
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] nvidia-cublas-cu11==11.11.3.6
[pip3] nvidia-cuda-cupti-cu11==11.8.87
[pip3] nvidia-cuda-nvrtc-cu11==11.8.89
[pip3] nvidia-cuda-runtime-cu11==11.8.89
[pip3] nvidia-cudnn-cu11==8.7.0.84
[pip3] nvidia-cufft-cu11==10.9.0.58
[pip3] nvidia-curand-cu11==10.3.0.86
[pip3] nvidia-cusolver-cu11==11.4.1.48
[pip3] nvidia-cusparse-cu11==11.7.5.86
[pip3] nvidia-nccl-cu11==2.20.5
[pip3] nvidia-nvtx-cu11==11.8.86
[pip3] pytorch3d==0.7.7
[pip3] torch==2.3.0+cu118
[pip3] torchaudio==2.3.0+cu118
[pip3] torchmetrics==0.5.0
[pip3] torchvision==0.18.0+cu118
[pip3] triton==2.3.0
[conda] horizon-plugin-pytorch    2.4.10+cu118.torch230          pypi_0    pypi
[conda] msgpack-numpy             0.4.8                    pypi_0    pypi
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] nvidia-cublas-cu11        11.11.3.6                pypi_0    pypi
[conda] nvidia-cuda-cupti-cu11    11.8.87                  pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu11    11.8.89                  pypi_0    pypi
[conda] nvidia-cuda-runtime-cu11  11.8.89                  pypi_0    pypi
[conda] nvidia-cudnn-cu11         8.7.0.84                 pypi_0    pypi
[conda] nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
[conda] nvidia-curand-cu11        10.3.0.86                pypi_0    pypi
[conda] nvidia-cusolver-cu11      11.4.1.48                pypi_0    pypi
[conda] nvidia-cusparse-cu11      11.7.5.86                pypi_0    pypi
[conda] nvidia-nccl-cu11          2.20.5                   pypi_0    pypi
[conda] nvidia-nvtx-cu11          11.8.86                  pypi_0    pypi
[conda] pytorch3d                 0.7.7                    pypi_0    pypi
[conda] torch                     2.3.0+cu118              pypi_0    pypi
[conda] torchaudio                2.3.0+cu118              pypi_0    pypi
[conda] torchmetrics              0.5.0                    pypi_0    pypi
[conda] torchvision               0.18.0+cu118             pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi

cc @ezyang @chauhang @penguinwu

**Comment by masnesral** [comment]
@Thinksky5124 can you take a look at this: https://docs.google.com/document/d/1y5CRfMLdwEoF1nTk9q8qEu1mgMUuUtvhklPKJ2emLU8/edit?tab=t.0#heading=h.ei2lynvpn1i7

**Comment by masnesral** [comment]
No response, so gonna close this out. Please reopen if you've followed the advice in the gdoc and you still think there's a problem.
