### ISSUE TITLE
caffe2/aten/src/THC/THCReduce.cuh(161): warning: dynamic initialization is not supported for a function-scope

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#13913]
I'm seeing this warning on builds:

```
caffe2/aten/src/THC/THCReduce.cuh(161): warning: dynamic initialization is not supported for a function-scope 
static __shared__ variable within a __device__/__global__ function
          detected during:
            instantiation of "void kernelReduceNoncontigDim_shared<T,IndexType,AccT,ModifyOp,ReduceOp,Finalize
Op,ADims,BDims>(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, IndexType, IndexType, IndexType, AccT, Mod
ifyOp, ReduceOp, FinalizeOp, volatile AccT *, int *) [with T=c10::Half, IndexType=unsigned int, AccT=WelfordDa
ta<float, c10::Half>, ModifyOp=ModifyWelford<WelfordData<float, c10::Half>>, ReduceOp=ReduceWelford<float, c10
::Half>, FinalizeOp=VarianceWelford<float, c10::Half>, ADims=2, BDims=2]" 
(603): here
            instantiation of "__nv_bool THC_reduceDim<ScalarType,TensorType,ModifyOp,ReduceOp,FinalizeOp,AccT>
(THCState *, TensorType *, TensorType *, ModifyOp, ReduceOp, FinalizeOp, AccT, int, int) [with ScalarType=c10:
:Half, TensorType=at::TensorImpl, ModifyOp=ModifyWelford<WelfordData<float, c10::Half>>, ReduceOp=ReduceWelfor
d<float, c10::Half>, FinalizeOp=VarianceWelford<float, c10::Half>, AccT=WelfordData<float, c10::Half>]" 
caffe2/aten/src/THC/generic/THCTensorMathReduce.cu(91): here
```

CC @jjsjann123 who modified this code recently

**Comment by jjsjann123** [comment]
I'm suspecting it's because of this https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCTensorMathReduce.cuh#L30-L32
I have default constructor initializing values, which is intended to be used here: https://github.com/pytorch/pytorch/blob/master/aten/src/THC/generic/THCTensorMathReduce.cu#L95

But I can't figure out how this becomes a `static __shared__ variable`: https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCReduce.cuh#L161

Let me first try to remove the assignment in the default constructor and see if it get rid of all those warning.

**Comment by jjsjann123** [comment]
Okey, compiler warning seems a little crazy to me.

I can repro the same warning with code like
```
template <typename T>
struct Data {
  T x_;
  __device__ Data() {}
};

__device__ void test() {
  __shared__ Data<int> q[10];
}
```
Which seem legit to me. Replacing it with a template function does remove the warning.
```
template <typename T>
struct Data {
  T x_;
  __device__ Data() {}
};

template <typename Q>
__device__ void test() {
  __shared__ Q q[10];
}

template __device__ void test<Data<int>>();
```
Inserting an assignment in the default constructor `__device__ Data() { x = T(0)}` would give me this warning again.

**Comment by jjsjann123** [comment]
#13967 get rid of the warning for me. @ezyang Let me know if you are having issue with it.
