### ISSUE TITLE
[ROCm] [Upstream Triton] num_stages=0 deprecation with stream pipeliner v2

### ISSUE THREAD

**Issue by jataylo** [pytorch/pytorch#139182]
### 🐛 Describe the bug

Since https://github.com/triton-lang/triton/commit/76ed94df1924b2262be9b37d778b6e0ccccb1180 AMD backend has removed stream pipeliner v1 in favour of v2. This change impacts PyTorch as we should no longer default to num_stages=0 for mm configs as this will now error out.

```
assert options.num_stages != 0, ("Triton AMD backend pipeliner has been updated. "
                                 "We used to trigger software pipelining with "
                                 "num_stages == 0. Now it will not happen anymore; "
                                 "please update to use num_stages == 2 for "
                                 "equivalent behavior in the past.")
```

Opening an issue to track updating the PyTorch code to match the new pipeliner as part of the triton upgrade for release/2.6 (https://github.com/pytorch/pytorch/issues/139175)

Ideally we should resolve this in a way that allows older triton to still use num_stages==0

### Versions

Triton commit: 3549db850c7daf86624a624378e12d2a5a2bd236
PyTorch commit: https://github.com/pytorch/pytorch/commit/4dd04db5d0962fb8a1925cee831b9eb4f41ca4fd

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang @naromero77amd @bertmaher @int3 @davidberard98 @nmacchioni @chenyang78 @embg @peterbell10 @aakhundov

**Comment by aakhundov** [comment]
I'm looking into the fix.
