### ISSUE TITLE
Calculate speed

### ISSUE THREAD

**Issue by digbangbang** [pytorch/pytorch#139282]
### 🐛 Describe the bug

![image](https://github.com/user-attachments/assets/ca2cf36d-0dbd-4c6b-9913-97a25e754747)

I test the speed when calculating the matrix multiplication or dot multiplication, it is so strange and counterintuitive, why the tensor is larger and the speed is faster?

I am working on a pruning method on LLM and could make it a 0.3 sparsity LLM, means the parameters will be reduced to 0.7. And when test the forward it is slower.

Why could it happen?

### Error logs

No

### Versions

2.0.1+cu118

cc @ezyang @chauhang @penguinwu
```[tasklist]
### Tasks
```

**Comment by masnesral** [comment]
@digbangbang there's not much to go on here with the title or the summary. Can you add detail on the actual problem / request?

**Comment by masnesral** [comment]
Since there are no actionable details, I'm going to close this out. Please reopen if you can provide the context.
