### ISSUE TITLE
No macOS 12 wheels available, cannot use torch binary wheels on GitHub Actions

### ISSUE THREAD

**Issue by bact** [pytorch/pytorch#139288]
### 🚀 The feature, motivation and pitch

- GitHub Actions drops support for macOS 11
  https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
- The newest macOS version for prebuilt torch wheels is macOS 11
  https://download.pytorch.org/whl/torch/
- This makes it impossible to use the prebuilt wheels in GitHub Actions infrastructure

### Alternatives

- Please provide wheels for macOS 12
- And even better, with 13 and 14 as well
- `macos-latest` on GitHub Actions is now 14.7

cc @seemethere @malfet @osalpekar @atalman @albanD

**Comment by malfet** [comment]
@Skylion007 please don't use `topic: *` labels on issues, those, together with `release notes: *` are dedicated to pull request to categorize them to release notes

**Comment by malfet** [comment]
@bact can you please elaborate what do you mean? Wheels we are currently building are installable on MacOS 12, 13, 14, and 15... For example see https://github.com/malfet/deleteme/actions/runs/11389705294/job/31689627771

**Comment by malfet** [comment]
Just to clarify `macosx_11_0` platform tag means that wheel is compatible with MacOS11 or newer, not that it could only run on MacOS 11

For more information see https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#platform-tag

**Comment by bact** [comment]
@malfet Thank you for feedback.

Please see the error messages from two workflows below, both run on `macos-latest` (14.7) with Python 3.9.13.

If I install with `python -m pip install torch` ([workflow #1](https://github.com/PyThaiNLP/pythainlp/actions/runs/11599160451/job/32296683274?pr=947)), I will get this:

```text
  python -m pip install torch
  shell: /bin/bash -l {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    PKG_CONFIG_PATH: /opt/homebrew/opt/icu4c/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    ICU_VER: 74.2
  
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

If I specified the wheel URL to pip install ([workflow #2](https://github.com/PyThaiNLP/pythainlp/actions/runs/11599267810/job/32297026871?pr=947)), I will get this:

```text
  python -m pip install http://download.pytorch.org/whl/cpu/torch-2.5.1-cp39-none-macosx_11_0_arm64.whl
  shell: /bin/bash -l {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    PKG_CONFIG_PATH: /opt/homebrew/opt/icu4c/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.9.13/arm64
    ICU_VER: 74.2
  
ERROR: torch-2.5.1-cp39-none-macosx_11_0_arm64.whl is not a supported wheel on this platform.
```

**Comment by bact** [comment]
Noted that on macOS 14.6.1 on x86 architecture, with Python 3.9, `pip install torch` runs fine.
It will pick up `torch-2.2.2-cp39-none-macosx_10_9_x86_64.whl` and install it successfully.

**Comment by malfet** [comment]
@bact I don't know what is going on with your setup but I can pip install PyTorch on GH Mac runners just fine, see
https://github.com/malfet/deleteme/actions/runs/11599847514/job/32298924191
And here is a workflow file:
https://github.com/malfet/deleteme/blob/0d1e8f5fd49624722cbcfd05b7870454e9d66479/.github/workflows/install_torch.yml

**Comment by bact** [comment]
Thank you. I will learn from your workflow file and check mine again.

**Comment by bact** [comment]
@malfet I have changed the macOS version to `macos-15` (same as your workflow), and now can install PyTorch with `pip install torch`

https://github.com/PyThaiNLP/pythainlp/actions/runs/11600952258/job/32302577453?pr=947

**Comment by bact** [comment]
I think for my immediate use, I can switch to `macos-15` (thanks again to make me realized that that option is available).

But I'm not sure if others experienced the same issue as mine with macOS 14, etc. or not.
Feel free to close this if you have found on your side that it works just fine with macOS 14, etc (i.e. cannot reproduce).

**Comment by bact** [comment]
Thank you for your help.

**Comment by bact** [comment]
Oh. Got it. It uses Python 3.13.0 under the hood. That's why.

**Comment by malfet** [comment]
@bact try using python3 vs python alias, may be that will help

**Comment by bact** [comment]
Thank you malfet. Thank you glennwester.
