### ISSUE TITLE
[Enhancement] Allow Dict[str, Any] format for `transforms` argument in `torchvision.transforms.v2.Compose`

### ISSUE THREAD

**Issue by geezah** [pytorch/pytorch#139291]
### 🚀 The feature, motivation and pitch

Currently, creating transform pipelines requires defining transforms in a list, which can be verbose and less maintainable for complex configurations. Allowing `Dict[str, Any]` input would enable loading transforms directly from config files (e.g. with an additional helper function `_init_from_dict` in `Compose`), making it easier to manage and modify transform pipelines, especially in experiment settings.

Example use case:
```python
# Current approach
transforms = Compose([
    RandomHorizontalFlip(p=0.5),
    RandomCrop(size=(224, 224)),
    Normalize(mean=[0.485], std=[0.229])
])

# Proposed approach
transforms = Compose({
    "RandomHorizontalFlip": {"p": 0.5},
    "RandomCrop": {"size": (224, 224)},
    "Normalize": {"mean": [0.485], "std": [0.229]}
})
```

This would streamline integration with configuration management tools and improve experiment reproducibility by making transform configurations more explicit and easier to serialize.

### Alternatives

Considered alternatives:
2. A new class `DictCompose`: Adds unnecessary complexity
3. YAML-specific parser: Too narrow, doesn't solve general config case

The dict approach is preferred as it:
- Maintains compatibility
- Requires minimal code changes
- Integrates naturally with existing config systems

### Additional context

Initial implementation would focus on built-in torchvision transforms for simplicity and safety. The transform lookup would check against a predefined set of built-in transforms (e.g., `torchvision.transforms.v2.__all__`).

Future extension could support custom transforms through e.g. import path specifications.

**Comment by Skylion007** [comment]
This would also make it so your linter is unable to detect invalid str keys if you misspell any operators in your Compose pipeline, so I don't really see an advantage.

**Comment by geezah** [comment]
You're certainly right, thank you for the quick feedback! How about adding a factory method `Compose.from_config()` that provides config support while preserving type safety of the main interface? Runtime validation would catch misspelled transforms immediately during initialization.

**Comment by geezah** [comment]
I just realized that I submitted this issue to the wrong repository. Will close this issue here and resubmit in `pytorch/vision`.

**Comment by geezah** [comment]
Closing as not planned.
