### ISSUE TITLE
libtorch. Executing at::sum after multiplying the slices yields different results

### ISSUE THREAD

**Issue by HongliWu** [pytorch/pytorch#139459]
### 🐛 Describe the bug

```
#include <torch/torch.h>
#include <iostream>
#include <c10/cuda/CUDAStream.h>

int main()
{
    // creat two tensors, and take their slices
    at::Tensor tAiF = at::randn({ 200, 3, 1080, 1440 }).to(at::kCUDA);
    at::Tensor tGrad = at::randn({ 200, 3, 1080, 1440 }).to(at::kCUDA);
    at::Tensor tAiFTmp = at::slice(tAiF, 2, 0, 100);
    at::Tensor tGradTmp = at::slice(tGrad, 2, 0, 100);

    // multiplication
    tAiF = tAiF * tGrad;
    tAiFTmp = tAiFTmp * tGradTmp;
    
    // Compare the results of multiplication
    // The result of multiplication is exactly the same
    // sample output
    //     tAiFTmpSub max abs 0.00000000000000000000
    //     tAiFTmpSub mean abs 0.00000000000000000000
    at::Tensor tAiFTmp2 = at::slice(tAiF, 2, 0, 100);
    at::Tensor tAiFTmpSub = tAiFTmp2 - tAiFTmp;
    at::Tensor tAiFTmpSubAbs = at::abs(tAiFTmpSub);
    std::cout << std::fixed << std::setprecision(20) << "tAiFTmpSub max abs " << at::max(tAiFTmpSubAbs).item() << std::endl;
    std::cout << std::fixed << std::setprecision(20) << "tAiFTmpSub mean abs " << at::mean(tAiFTmpSubAbs).item() << std::endl;

    // Sum over dimension 0
    at:: Tensor tAiFSum = at::sum(tAiF, 0);
    at::Tensor tAiFTmpSum = at::sum(tAiFTmp, 0);

    // Print the result of the sum
    // The results of the sum will vary
    // sample output
    //     tAiFSum[0, 0, 0] 14.05858135223388671875
    //     tAiFTmpSum[0, 0, 0] 14.05858039855957031250
    std::cout << std::fixed << std::setprecision(20) << "tAiFSum[0, 0, 0] " << tAiFSum.index({ 0, 0, 0 }).item() << std::endl;
    std::cout << std::fixed << std::setprecision(20) << "tAiFTmpSum[0, 0, 0] " << tAiFTmpSum.index({ 0, 0, 0 }).item() << std::endl;

    return 0;
}
```

### Versions

Collecting environment information...
PyTorch version: 1.8.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 企业版 (10.0.19044 64 位)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: False
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 546.65
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Manufacturer: GenuineIntel
Family: 198
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 4201
MaxClockSpeed: 4201
L2CacheSize: 1024
L2CacheSpeed: None
Revision: None

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] pytorch2caffe==0.1.0
[pip3] torch==1.8.0
[conda] Could not collect

**Comment by zou3519** [comment]
this is expected, see https://pytorch.org/docs/stable/notes/numerical_accuracy.html
