### ISSUE TITLE
Recompilation exausted with `size mismatch at index 2`

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#139474]
### 🐛 Describe the bug

I am going to exhaust recompilation also with extended `torch._dynamo hit config.cache_size_limit (64)` on this module

Just enabling the compilation on this module
https://github.com/hustvl/ViTMatte/blob/main/modeling/decoder/detail_capture.py#L132-L140

### Error logs

```python
 function: 'forward' (/workspace/modeling/decoder/detail_capture.py:131)
[rank6]:W1101 02:43:39.336000 143 site-packages/torch/_dynamo/convert_frame.py:896] [1/64]    last reason: 1/0: tensor 'L['images']' size mismatch at index 2. expected 1696, actual 1248
[rank6]:W1101 02:43:39.336000 143 site-packages/torch/_dynamo/convert_frame.py:896] [1/64] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank6]:W1101 02:43:39.336000 143 site-packages/torch/_dynamo/convert_frame.py:896] [1/64] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
[rank3]:W1101 02:43:40.706000 140 site-packages/torch/_dynamo/convert_frame.py:896] [1/64] torch._dynamo hit config.cache_size_limit (64)
[rank3]:W1101 02:43:40.706000 140 site-packages/torch/_dynamo/convert_frame.py:896] [1/64]    function: 'forward' (/workspace/modeling/decoder/detail_capture.py:131)
[rank3]:W1101 02:43:40.706000 140 site-packages/torch/_dynamo/convert_frame.py:896] [1/64]    last reason: 1/0: tensor 'L['images']' size mismatch at index 2. expected 1248, actual 1376
````

### Versions

nightly

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @chauhang @penguinwu @ezyang @bobrenjc93

**Comment by bhack** [comment]
From the log it could be also interesting:

```python
W1101 02:46:53.657000 138 site-packages/torch/_dynamo/convert_frame.py:896] [1/64] torch._dynamo hit config.cache_size_limit (64)
W1101 02:46:53.657000 138 site-packages/torch/_dynamo/convert_frame.py:896] [1/64]    function: 'forward' (/workspace/modeling/decoder/detail_capture.py:131)
W1101 02:46:53.657000 138 site-packages/torch/_dynamo/convert_frame.py:896] [1/64]    last reason: 1/14: Eq(512, ((L['images'].size()[3] - 1)//4) + 1)  # (_meta_registrations.py:2262 in pick_memory_format)
```

**Comment by ezyang** [comment]
Post a TORCH_TRACE for it please

**Comment by bhack** [comment]
The full trace is going to share a lot of model details. Any alternative?

**Comment by bhack** [comment]
I have reduced enough the tracing section to reproduce the exhaustion.  
Here you can find trace in the attachment up to the exhaustion with default `torch._dynamo.config.cache_size_limit` but it is going to be exhausted also extending to `64`.
[dedicated_log_torch_trace_rank_0_a57hrd2d.zip](https://github.com/user-attachments/files/17611772/dedicated_log_torch_trace_rank_0_a57hrd2d.zip)

**Comment by bhack** [comment]
Also I guess why some of this `please file a bug` messages appear only in the verbose trace log:
```python
	+- LAMBDA_GUARD: L['images'].stride()[0] == 4*L['images'].size()[2]*L['images'].size()[3]  # (unknown source L['images'].stride()[0], please file a bug)
	+- LAMBDA_GUARD: L['images'].stride()[1] == L['images'].size()[2]*L['images'].size()[3]  # (unknown source L['images'].stride()[1], please file a bug)
	+- LAMBDA_GUARD: L['images'].stride()[2] == L['images'].size()[3]  # (unknown source L['images'].stride()[2], please file a bug)
	+- LAMBDA_GUARD: L['features'].stride()[0] == 768*L['features'].size()[2]*L['features'].size()[3]  # (unknown source L['features'].stride()[0], please file a bug)
	+- LAMBDA_GUARD: L['features'].stride()[1] == L['features'].size()[2]*L['features'].size()[3]  # (unknown source L['features'].stride()[1], please file a bug)
	+- LAMBDA_GUARD: L['features'].stride()[2] == L['features'].size()[3]  # (unknown source L['features'].stride()[2], please file a bug)
```

**Comment by bdhirsh** [comment]
Opening up the recompile logs from the tlparse output, I see:
```
[
  "0/6: Eq(512, ((L['images'].size()[3] - 1)//4) + 1)  # (_meta_registrations.py:2262 in pick_memory_format)",
  "0/0: tensor 'L['images']' size mismatch at index 2. expected 1568, actual 2848",
  "0/5: Eq(576, ((L['images'].size()[3] - 1)//4) + 1)  # (_meta_registrations.py:2262 in pick_memory_format)",
  "0/4: Eq(960, ((L['images'].size()[3] - 1)//4) + 1)  # (_meta_registrations.py:2262 in pick_memory_format)",
  "0/3: Eq(840, ((L['images'].size()[3] - 1)//4) + 1)  # (_meta_registrations.py:2262 in pick_memory_format)",
  "0/2: Eq(720, ((L['images'].size()[3] - 1)//4) + 1)  # (_meta_registrations.py:2262 in pick_memory_format)",
  "0/1: Eq(720, ((L['images'].size()[3] - 1)//4) + 1)  # (_meta_registrations.py:2262 in pick_memory_format)"
]
```

**Comment by bdhirsh** [comment]
yup it is - that log just contained info about a single recompile vs the tlparse output gave me a nice consolidated view of all 6 recompiles on that frame (so clearly we a recompiling many times on that same condition, not immediately clear why `automatic_dynamic` didn't "avoid" the recompiles)

**Comment by ezyang** [comment]
You want to TORCH_LOGS=dynamic and look for the line of code that adds the guard on `(L['images'].size()[3] - 1)//4) + 1`

**Comment by bhack** [comment]
> You want to TORCH_LOGS=dynamic and look for the line of code that adds the guard on (L['images'].size()[3] - 1)//4) + 1

Here part of the dynamic log. What you see?

[dynamic.log](https://github.com/user-attachments/files/17640099/dynamic.log)

**Comment by bdhirsh** [comment]
fwiw here's the tlparse https://interncache-all.fbcdn.net/manifold/tlparse_reports/tree/logs/.tmp0H3iGG/index.html

I haven't figured out exactly why this line is causing a specialization (I think it's this line) https://github.com/pytorch/pytorch/blob/main/torch/_meta_registrations.py#L2268. I also see DDPOptimizer stuff in the tlparse, not immediately clear if it's relevant.

One thing that might give you more info as well is running with `TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Eq(1024, ((s1 - 1)//4) + 1) TORCHDYNAMO_EXTENDED_DEBUG_CPP=1` (which will hopefully give a C++ stacktrace of where that specialization happens)

**Comment by bhack** [comment]
I am running again with these flags. But what do you think about https://github.com/pytorch/pytorch/issues/139474#issuecomment-2453553509 ?

**Comment by bdhirsh** [comment]
that looks worth fixing as well (although it seems independent of the issue). I tried making my own repro but I haven't been able to repro it. By any chance are you able to make a repro that just relies on compiling the code here? https://github.com/hustvl/ViTMatte/blob/main/modeling/decoder/detail_capture.py#L132-L140 (you would probably need to compile it, run it in a script that uses ddp, and run it repeatedly with images/features of the sizes in your failing example). I made an attempt at making a repro myself off of that file, but I had to guess some input shapes to use, and with my guess I wasn't able to properly repro.

**Comment by bhack** [comment]
Here the extend log of `eval Eq(1024, ((s1 - 1)//4) + 1)`

[1024_guard_debug.log](https://github.com/user-attachments/files/17650680/1024_guard_debug.log)

**Comment by bhack** [comment]
Let me know if it is more clear now.

**Comment by bdhirsh** [comment]
@bhack those logs definitely help. I still haven't been able to repro though.

The logs point to the specialization happening [here](https://github.com/pytorch/pytorch/blob/main/c10/core/Contiguity.h#L24), where `sym_eq(strides[d], z)` turns into the guards `Eq(1024, ((s1 - 1)//4) + 1)`. This points to the stride being static.

And the tlparse confirms this theory, where you can see:

(1) we are running with DDPOptimizer turned on (the integration between DDP and compile), which tries to split the graph into regions to bucket

(2) the output of the first graph looks like this:
```
cat_1: "bf16[1, 352, ((s0 - 1)//4) + 1, ((s1 - 1)//4) + 1][352*(((s0 - 1)//4) + 1)*(((s1 - 1)//4) + 1), (((s0 - 1)//4) + 1)*(((s1 - 1)//4) + 1), ((s1 - 1)//4) + 1, 1]cuda:0"
```
but when it becomes an input to the second graph, it shows up as this:
```
arg0_1: "bf16[1, 352, ((s0 - 1)//4) + 1, ((s1 - 1)//4) + 1][121651200, 345600, 720, 1]cuda:0"
```


So for some reason, we have forced all of the strides to be static between the DDPOptimizer graph boundaries. Then when we issue an equality guard between a (dynamic) size and (static) stride, we effectively force our sizes to be static too.

**Comment by bdhirsh** [comment]
As I said above, I haven't been able to repro this based off of your repro. I tried copy-pasting some of your code to make my own repro, which is here:
```
import torch
from torch.nn.parallel import DistributedDataParallel as DDP
from contextlib import contextmanager

class FakeDDP(torch.nn.Module):
    def __init__(self, module, bucket_cap_mb=25):
        super().__init__()
        self.module = module
        self.bucket_bytes_cap = int(bucket_cap_mb * 1024 * 1024)

    @contextmanager
    def _inside_ddp_forward(self):
        DDP._active_ddp_module = self
        try:
            yield
        finally:
            DDP._active_ddp_module = None

    def forward(self, *inputs, **kwargs):
        with self._inside_ddp_forward():
            return self.module.forward(*inputs, **kwargs)

class Basic_Conv3x3(torch.nn.Module):
    def __init__(
        self,
        in_chans,
        out_chans,
        stride=2,
        padding=1,
    ):
        super().__init__()
        self.conv = torch.nn.Conv2d(in_chans, out_chans, 3, stride, padding, bias=False)
        self.bn = torch.nn.BatchNorm2d(out_chans)
        self.relu = torch.nn.ReLU(True)

    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        x = self.relu(x)
        return x

class Block(torch.nn.Module):
    def __init__(
        self,
        in_chans,
        out_chans,
    ):
        super().__init__()
        self.conv = Basic_Conv3x3(in_chans, out_chans, stride=1, padding=1)

    def forward(self, x, D):
        F_up = torch.nn.functional.interpolate(x, scale_factor=2, mode='bilinear', align_corners=False)
        out = torch.cat([D, F_up], dim=1)
        out = self.conv(out)
        return out

class Matting_Head(torch.nn.Module):
    def __init__(
        self,
        in_chans = 32,
        mid_chans = 16,
    ):
        super().__init__()
        self.matting_convs = torch.nn.Sequential(
            torch.nn.Conv2d(in_chans, mid_chans, 3, 1, 1),
            torch.nn.BatchNorm2d(mid_chans),
            torch.nn.ReLU(True),
            torch.nn.Conv2d(mid_chans, 1, 1, 1, 0)
            )

    def forward(self, x):
        x = self.matting_convs(x)
        return x


class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.convs = torch.nn.ModuleList([
            Basic_Conv3x3(4, 48),
            Basic_Conv3x3(48, 96),
            Basic_Conv3x3(96, 192),
        ])
        self.blocks = torch.nn.ModuleList([
            Block(in_chans=384+96, out_chans=192),
            Block(in_chans=192+48, out_chans=96),
            Block(in_chans=96+4, out_chans=32),
        ])
        self.matting_head = Matting_Head(in_chans=32)

    def forward(self, x, features):
        out_dict = {'D0': x}
        for i in range(len(self.convs)):
            x = self.convs[i](x)
            name_ = 'D'+str(i+1)
            out_dict[name_] = x

        for i in range(len(self.blocks)):
            d_name_ = 'D'+str(len(self.blocks)-i-1)
            features = self.blocks[i](features, out_dict[d_name_])

        phas = torch.sigmoid(self.matting_head(features))
        return {"phas": phas}

model = Model()
model = FakeDDP(model)

opt_model = torch._dynamo.optimize("aot_eager")(model)
with torch.no_grad():
    x = torch.randn(1, 4, 1568, 2240)
    torch._dynamo.mark_dynamic(x, 2)
    torch._dynamo.mark_dynamic(x, 3)
    features = torch.randn(1, 384, 196, 280)
    torch._dynamo.mark_dynamic(features, 2)
    torch._dynamo.mark_dynamic(features, 3)
    opt_model(x, features)
```

That didn't repro for me though (I don't see the strides getting specialized when I print the AOT graphs with `TORCH_LOGS="aot"`

**Comment by bdhirsh** [comment]
A few things that would help:

(1) are you able to create a standalone repro with the recompiles using your code from `detail_capture.py`? (that is what I tried and failed to do)

(2) You linked some logs above (`dynamic.log`) - but I think they look a bit incomplete? Would it be possible to run with `TORCH_LOGS="graph_code,aot,+dynamic"` and upload the full set of logs? (I'm wondering if the full logs will indicate at what point we end up specializing the strides)

**Comment by bhack** [comment]
@bdhirsh Can you simulate you code with many input sized instead of `1568, 2240` with batch size 1?

**Comment by bhack** [comment]
I don't want that the explicit `torch._dynamo.mark_dynamic` is enforcing something that workaround the problem.

**Comment by bdhirsh** [comment]
@bhack I actually just realized that as written, the repro that I put above requires those fixed shapes (even if I run that repro above in eager mode, and I twak `1568, 2240` to `1569, 2241`, I get an error):
```
Traceback (most recent call last):
  File "/home/hirsheybar/local/b/pytorch/tmp6.py", line 115, in <module>
    model(x, features)
  File "/home/hirsheybar/local/b/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hirsheybar/local/b/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hirsheybar/local/b/pytorch/tmp6.py", line 21, in forward
    return self.module.forward(*inputs, **kwargs)
  File "/home/hirsheybar/local/b/pytorch/tmp6.py", line 100, in forward
    features = self.blocks[i](features, out_dict[d_name_])
  File "/home/hirsheybar/local/b/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hirsheybar/local/b/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hirsheybar/local/b/pytorch/tmp6.py", line 53, in forward
    out = torch.cat([D, F_up], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 393 but got size 392 for tensor number 1 in the list.
```

So I'm probably not replicating your code correctly. If you're able to figure out how to tweak it to make it more representative of your modeling code (or otherwise create a repro script) that would help a bunch

**Comment by bhack** [comment]
Can you try to ddp warp this and feed it with changing fake inputs? 
https://github.com/hustvl/ViTMatte/blob/main/inference.py

As I suppose `TORCH_LOGS="graph_code,aot,+dynamic"`  it is going to expose all the model arch right?

**Comment by bhack** [comment]
@bdhirsh In the case you don't have the bandwidth to DDP wrap that inference here the `TORCH_LOGS="graph_code,aot,+dynamic"` log you have requested up to the cache limit hit.
[torch_logs.zip](https://github.com/user-attachments/files/17685457/torch_logs.zip)

**Comment by bhack** [comment]
Is this last log enough?

**Comment by bdhirsh** [comment]
It's a bit hard to tell, but https://github.com/pytorch/pytorch/issues/140229 seems to be proximally the same issue and has a full repro that I started looking into. Once I root cause it, let's see if fixing that also fix your model (and if not I'll come back to this)

**Comment by bdhirsh** [comment]
@bhack can you give this PR a shot? (or otherwise wait for it to land before trying again) https://github.com/pytorch/pytorch/pull/140751

**Comment by bhack** [comment]
If it is python only we have https://github.com/pytorch/pytorch/blob/main/tools/nightly_hotpatch.py

**Comment by bhack** [comment]
```bash 
wget -qO-  https://raw.githubusercontent.com/pytorch/pytorch/refs/heads/main/tools/nightly_hotpatch.py | python - 140751
``` 

Is going to solve 
```python
 function: 'forward' (/workspace/modeling/decoder/detail_capture.py:131)
[rank6]:W1101 02:43:39.336000 143 site-packages/torch/_dynamo/convert_frame.py:896] [1/64]    last reason: 1/0: tensor 'L['images']' size mismatch at index 2. expected 1696, actual 1248
[rank6]:W1101 02:43:39.336000 143 site-packages/torch/_dynamo/convert_frame.py:896] [1/64] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank6]:W1101 02:43:39.336000 143 site-packages/torch/_dynamo/convert_frame.py:896] [1/64] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
[rank3]:W1101 02:43:40.706000 140 site-packages/torch/_dynamo/convert_frame.py:896] [1/64] torch._dynamo hit config.cache_size_limit (64)
[rank3]:W1101 02:43:40.706000 140 site-packages/torch/_dynamo/convert_frame.py:896] [1/64]    function: 'forward' (/workspace/modeling/decoder/detail_capture.py:131)
[rank3]:W1101 02:43:40.706000 140 site-packages/torch/_dynamo/convert_frame.py:896] [1/64]    last reason: 1/0: tensor 'L['images']' size mismatch at index 2. expected 1248, actual 1376
```

As you have all the extended log do you find anything else interesting for a new ticket? If not you can close this.

**Comment by bdhirsh** [comment]
Are you asking if I think that my linked PR is enough to fix this current issue, given the logs you linked?

I think it is pretty likely that https://github.com/pytorch/pytorch/pull/140751 fixes this issue, but unfortunately I can't 100% confirm that just from the linked logs. If you're able to test your code with that hotpatch that would be helpful.

**Comment by bhack** [comment]
No I meant that I've applied it with:
`wget -qO-  https://raw.githubusercontent.com/pytorch/pytorch/refs/heads/main/tools/nightly_hotpatch.py | python - 140751`

And we don't have more the exhausted recompilation for  tensor 'L['images']' size mismatch at index 2.`

So if from the shared log you don't see any other additional interesting things for opening new tickets you can close it.

**Comment by bdhirsh** [comment]
Ah great - yep, I don't see anything else in the logs worth keeping this issue open over.

**Comment by bdhirsh** [comment]
(whoops, we can close when that PR lands)
