### ISSUE TITLE
PyTorch 2.5.1 cannot find MPS device on a MacOS 12.7.6 arm64

### ISSUE THREAD

**Issue by rafaelvareto** [pytorch/pytorch#139425]
Is there a way to run the recently released PyTorch 2.5.1 with MPS enabled without upgrading the MacOS?

I have a MacBook M1 (macOS-12.7.6-arm64-arm-64bit), but whenever I try to move a tensor to a MPS device, I come across the following error:

```bash
RuntimeError: The MPS backend is supported on MacOS 12.3+.
Current OS version can be queried using `sw_vers`.

>> sw_vers
ProductName:	macOS
ProductVersion:	12.7.6
BuildVersion:	21H1320
```

Basically, I have a OS version satisfying PyTorch requirements, still, it does not find a MPS device.

_Originally posted by @rafaelvareto in https://github.com/pytorch/pytorch/issues/78343#issuecomment-2450741927_

cc @seemethere @malfet @osalpekar @atalman @kulinseth @albanD @DenisVieriu97 @jhavukainen

**Comment by malfet** [comment]
Wow, this is really unfortunate, it should have say that you need MacOS 13.0`
