### ISSUE TITLE
Add ci-no-td label on reland PR

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#139492]
Report by @desertfire in https://github.com/pytorch/pytorch/pull/139458#issuecomment-2452127782.  We have the bot to automatically stick `ci-no-td` label on a reverted PR like https://github.com/pytorch/pytorch/pull/139224#issuecomment-2450811914, but another usage pattern from ghstack users is to reland the stack in separate PRs instead and they won't have `ci-no-td`.

Some potential fixes:

* Check for `reland` in the PR title and stick `ci-no-td` there
* Check for the PR title?

cc @ZainRizvi @kit1980 @clee2000

**Comment by malfet** [comment]
EZ solution is just to just add  a rule to
https://github.com/pytorch/test-infra/blob/a3d30d6fe42d1f5abdfc40d9d3f294451c6c911c/torchci/lib/bot/autoLabelBot.ts#L15

but this would apply it indiscriminately to both issues and PRs as well as to all repos that use mergebot
