### ISSUE TITLE
how to uninstall caffe2 which is installed from source?

### ISSUE THREAD

**Issue by lilichu** [pytorch/pytorch#13956]
hi! I install caffe2 from source by the [tutorial](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile) such as:
```
git clone https://github.com/pytorch/pytorch.git && cd pytorch
git submodule update --init --recursive
python setup.py install
```
now I want to uninstall caffe2. how to do it? thanks!

**Comment by soumith** [comment]
@lilichu do `pip uninstall -y torch` `pip uninstall -y caffe2`
