### ISSUE TITLE
Setting an `int` and `bool` value to `rtol` and `atol` argument of `isclose()` works against the error message

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#139562]
### 🐛 Describe the bug

Setting a `complex` value to `rtol` and `atol` argument of [isclose()](https://pytorch.org/docs/stable/generated/torch.isclose.html) gets the error messages as shown below:

```python
import torch

tensor1 = torch.tensor([0., 1., 2.])
tensor2 = torch.tensor([0., 1., 2.])

                                          # ↓↓↓↓↓↓↓↓↓↓↓
torch.isclose(input=tensor1, other=tensor2, rtol=4.+0.j) # Error

                                          # ↓↓↓↓↓↓↓↓↓↓↓
torch.isclose(input=tensor1, other=tensor2, atol=3.+0.j) # Error
```

> TypeError: isclose(): argument 'rtol' must be float, not complex

> TypeError: isclose(): argument 'atol' must be float, not complex

But setting an `int` and `bool` value to `rtol` and `atol` argument of `isclose()` works against the error message above as shown below:

```python
import torch

tensor1 = torch.tensor([0., 1., 2.])
tensor2 = torch.tensor([0., 1., 2.])

                                          # ↓↓↓↓↓↓  ↓↓↓↓↓↓
torch.isclose(input=tensor1, other=tensor2, rtol=3, atol=4)
# tensor([True, True, True])
                                          # ↓↓↓↓↓↓↓↓↓  ↓↓↓↓↓↓↓↓↓↓
torch.isclose(input=tensor1, other=tensor2, rtol=False, atol=False)
# tensor([True, True, True])
```

### Versions

```python
import torch

torch.__version__ # '2.5.1'
```

**Comment by janeyx99** [comment]
This is one of those issues where it's about Python arg parsing vs having PyTorch be aware of type promotions of python scalars. I think I had commented on one of your issues saying that the most productive way to get action from this concern is to open one umbrella issue that tracks all of these incidents, and to link these to that umbrella issue.

Closing this issue and all other similar issues until there is such an issue with a link.
