### ISSUE TITLE
[JIT] torch.tensor doesn't trace devices correctly

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#13969]
## 🐛 Bug

```python
def x(a):
    b = torch.tensor((1.,), device=a.device)
    return a+b
y = torch.jit.trace(x, (torch.randn(1, device='cuda'),))
```
## Expected behavior

Work.

## Environment

Todayish master.

(found this while trying to trace maskrcnn on GPU https://github.com/facebookresearch/maskrcnn-benchmark/pull/138 )

**Comment by t-vi** [comment]
I have a tentative fix, that, unless someone explains me that this is a bad idea, I'll make into a PR.
The basic idea is to use a bit more tensor methods (in particular `Tensor.to(...)`) instead of doing this manually.

```
iff --git a/torch/csrc/utils/tensor_new.cpp b/torch/csrc/utils/tensor_new.cpp
index f9d6ffc62..d8c939232 100644
--- a/torch/csrc/utils/tensor_new.cpp
+++ b/torch/csrc/utils/tensor_new.cpp
@@ -244,7 +244,9 @@ Tensor internal_new_from_data(
       (char*)tensor.data_ptr(), tensor.sizes(), tensor.strides(), 0,
       scalarType, tensor.type().elementSizeInBytes(), data);
   const auto& type_to_use = type_inference ? type.toScalarType(scalarType) : type;
-  return new_with_type_conversion(type_to_use, tensor, device_index);
+  auto device = device_opt.has_value() ? *device_opt : tensor.device();
+  return tensor.to(device, type_to_use.scalarType(), /*blocking=*/false, /*copy=*/false);
+  //return new_with_type_conversion(type_to_use, tensor, device_index);
 }
 
 Tensor new_from_data_copy(
```

**Comment by fmassa** [comment]
@t-vi does this also work for non-tensor input data, like lists or numpy arrays?

**Comment by t-vi** [comment]
This is for lists, but I'd go through the other cases of the function, too.

**Comment by zou3519** [comment]
@SsnL do you know if there's a semantic difference between `new_with_type_conversion` and `tensor.to(...)`?

**Comment by t-vi** [comment]
So as far as I can tell, the main difference is that I might need to `AutoNoGIL` but I think I don't need to do the `DeviceGuard` myself.
The next thing is that I think I can do the same trick for `new_with_tensor_copy` by using the `copy` flag for `Tensor.to`.

**Comment by SsnL** [comment]
@gchanan please correct me if I am wrong.

@zou3519 There is not much difference afaict (except for the `AutoNoGIL` pointed out by @t-vi). We have two implementations for historical reasons. Python `.to` is implemented with [`dispatch_type_conversion` ](https://github.com/pytorch/pytorch/blob/1bafa6236f60d6a356edb61ef885fe5d39b166ce/torch/csrc/utils/tensor_conversion_dispatch.cpp#L14) outside of ATen. Then, to maintain parity in C++ API, we added it as an ordinary method on `at::Tensor`, without touching `dispatch_type_conversion`. Afterwards, to support JIT, we changed the `at::Tensor` method to become a [native function](https://github.com/pytorch/pytorch/blob/1bafa6236f60d6a356edb61ef885fe5d39b166ce/aten/src/ATen/native/TensorConversions.cpp). I be very happy if we can remove `dispatch_type_conversion` to and use `.to` directly.

**Comment by SsnL** [comment]
@t-vi I was in the middle of refactoring `tensor_new.cpp` to use `TensorOptions` and `Device` objects, before, you know, the unfortunate event happened. :) I might picked it up again sometime in December.

**Comment by t-vi** [comment]
@SsnL So I don't understand the meaning of the various flags yet. Hopefully I can figure it out before December.
My immediate interest is being able to trace constants created through torch.tensors on the cuda backend, which doesn't work at the moment, so I'm at a more minimal approach here.

**Comment by SsnL** [comment]
@t-vi Yes. I wasn't saying that you should get rid of `dispatch_type_conversion`. Sorry if I sounded like that.

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/14097
