### ISSUE TITLE
[JIT] Behavior of .view operation in the JIT

### ISSUE THREAD

**Issue by nerox8664** [pytorch/pytorch#13963]
A type of `Tensor.size()` is different in the runtime and in the jit:
`<class 'int'>` - in runtime
`<class 'torch.Tensor'>` - with jit.trace

## To Reproduce

1. Run the code below in runtime
2. Run the code below with jit.trace

```
class TestView(nn.Module):
    def __init__(self):
        super(TestView, self).__init__()
        self.conv2d = nn.Conv2d(22, 32, kernel_size=1, bias=True)
        self.fc = nn.Linear(15488, 3)

    def forward(self, x):
        x = self.conv2d(x)
        
        print(type(x.size()[0]))

        x = x.view([x.size(0), -1])
        x = self.fc(x)
        return x
```

## Environment

pytorch nightly

**Comment by zou3519** [comment]
@nerox8664 how does this impact the view operation?

**Comment by nerox8664** [comment]
@zou3519 the difference in `jit graph`:

without cast (`x = x.view([x.size(0), -1])`): 

```
 %15 : Long() = onnx::Constant[value={0}](), scope: TestView
  %16 : Dynamic = onnx::Shape(%14), scope: TestView
  %18 : Long() = onnx::Gather[axis=0](%16, %15), scope: TestView
  %19 : Long() = onnx::Constant[value={-1}](), scope: TestView
  %26 : Dynamic = onnx::Unsqueeze[axes=[0]](%18)
  %27 : Dynamic = onnx::Unsqueeze[axes=[0]](%19)
  %28 : Dynamic = onnx::Concat[axis=0](%26, %27)
  %21 : Float(1, 15488) = onnx::Reshape(%14, %28), scope: TestView
```

with cast (`x = x.view([int(x.size(0)), -1])`):

```
%16 : Float(1, 15488) = onnx::Flatten[axis=1](%14), scope: TestView
```

**Comment by soumith** [comment]
cc: @houseroad

**Comment by houseroad** [comment]
I have checked the case, the reason is that view cannot optimize this into a flatten op with existing symbolic. I am working on a more complicated case to catch this common pattern.

**Comment by bhack** [comment]
@houseroad What is the current effect on `view` in the original example?

**Comment by houseroad** [comment]
check this pattern, and turn it into a Flatten op, it will be done in the symbolic.py

**Comment by bhack** [comment]
So is it just performance? Currently is it not going to broke anything right?

**Comment by houseroad** [comment]
Yes, it's just for performance, right now the export is correct.

**Comment by houseroad** [comment]
Hi @nerox8664 and @bhack, if you would like to flatten the tensor using pattern `x.view([x.size(0), -1])`, I would recommend [`torch.flatten`](https://pytorch.org/docs/stable/torch.html#torch.flatten). With https://github.com/pytorch/pytorch/pull/16240, you should be able to export `torch.flatten(x, 1)` as ONNX Flatten operator.
