### ISSUE TITLE
aten.full_like can not be decomposed to core aten ops

### ISSUE THREAD

**Issue by haowang5128** [pytorch/pytorch#139617]
### 🐛 Describe the bug

Hello, I noticed that according to the documentation (https://pytorch.org/docs/2.4/torch.compiler_ir.html#core-aten-ir), aten.full_like is not listed as a core aten op. However, it appears that it cannot be decomposed into core aten ops.
```import torch

class M(torch.nn.Module):
    def forward(self, x):
        return torch.full_like(x, 1)

ep = torch.export.export(M(), (torch.rand(3,3),))
print(ep) # aten::full_like in the graph
ep = ep.run_decompositions()
print(ep) # aten::full_like still in the graph

decomp = torch._decomp.get_decompositions([torch._ops.ops.aten.full_like]) # it is empty

exit()
```
I’m wondering, should all non-core aten ops ideally be decomposable into core aten ops? 

### Versions

torch version: 2.4.1

cc @svekars @brycebortree @sekyondaMeta @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by janeyx99** [comment]
This might be more of a docs fix than anything

**Comment by avikchaudhuri** [comment]
tagging @tugsbayasgalan

**Comment by tugsbayasgalan** [comment]
cc: @SS-JIA Looks like this op doesn't have the decomp and hasn't been tagged as core aten operator.

**Comment by larryliu0820** [comment]
I think we should add the core tag to this op
