### ISSUE TITLE
ImportError: libcurand.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lilichu** [pytorch/pytorch#13964]
I install pytorch from source. 
when I run:
`import torch`
I encounter the issue such as:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/python2/lib/python2.7/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: libcurand.so.9.0: cannot open shared object file: No such file or directory
```
how to solve it? thanks!!!!

**Comment by lilichu** [comment]
@ezyang  thanks for your help. I think it is because that I used to install old caffe2.  The old caffe2 `libcaffe2.so`, `libcaffe2_detectron_ops_gpu.so`,` libcaffe2_gpu.so`, `libcaffe2_module_test_dynamic.so`, `libcaffe2_observers.so` is in `/usr/local/lib`, but now new installed caffe2 they all in `pytorch/build/lib`. I delete all in  `/usr/local/lib`. Now it seems OK. do you think my approach is correct? thanks!

**Comment by soumith** [comment]
@lilichu it definitely makes sense to delete the old installed .so files. Your approach is correct.

**Comment by lilichu** [comment]
@soumith  thanks for your response!  To be safe, do you think what else remains from old caffe2 I need to delete? I used to install caffe2 from source on about May 22, and I only delete` pytorch/` directly. thanks!
