### ISSUE TITLE
Aliasing is not being prevented in onnx.export(dynamo=True) - potentially wrong graph exported 

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#139646]
### 🐛 Describe the bug

Here, I ran into this issue trying to export a module with same Tensor in input example for multiple inputs - it seems export() does generate a graph where those inputs are not independent (ignoring all inputs but the last one).

Here's the repro. If you swap comment lines with uncommented, the problem goes away. 

```
y1 = torch.rand(1024, 20, 16).to(device)
z1 = torch.rand(1024, 20, 16).to(device)

input_names = ["x_0", "x_1", "x_2", "y", "z", "bs"]


# onnx_program = torch.onnx.export(model, ([x1,y1,z1], y, z, 0.2), "xyz_legacy.onnx",                                                                                          
onnx_program = torch.onnx.export(model, ([x,y,z], y, z, 0.2), "xyz_legacy.onnx",
                                 input_names=input_names, dynamo=False, verbose=True)

# onnx_program = torch.onnx.export(model, ([x1,y1,z1], y, z, 0.2), "xyz.onnx",                                                                                                 
onnx_program = torch.onnx.export(model, ([x,x,x], x, x, 0.2), "xyz.onnx",
                                 input_names=input_names,
                                 dynamo=True, verify=True, report=True) 
                                 

### Versions

Pytorch nightly

**Comment by borisfom** [comment]
When running the resulting xyz.onnx graph, ONNXruntime does not give any warnings, but TensorRT does :

[W] Unused Input: x_0
[W] Unused Input: x_1
[W] Unused Input: x_2
[W] Unused Input: y
[W] [RemoveDeadLayers] Input Tensor x_0 is unused or used only at compile-time, but is not being removed.
[W] [RemoveDeadLayers] Input Tensor x_1 is unused or used only at compile-time, but is not being removed.
[W] [RemoveDeadLayers] Input Tensor x_2 is unused or used only at compile-time, but is not being removed.
[W] [RemoveDeadLayers] Input Tensor y is unused or used only at compile-time, but is not being removed.
[I] Finished engine building in 4.020 seconds
[W] Input tensor: __z | Buffer name (z) does not match expected input name (__z).
[

**Comment by justinchuby** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/139905
