### ISSUE TITLE
Why the torch.sparse code is deleted?  

### ISSUE THREAD

**Issue by luckyq** [pytorch/pytorch#13965]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soumith** [comment]
it's not deleted

**Comment by luckyq** [comment]
OK.... And Why torch.sparse directory only has one file __init__.py ?
