### ISSUE TITLE
[study] Are we calling DeviceGuard too much?

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#13974]
This is a followup to #13049, where I discovered that one big aten overhead is calling DeviceGuard a lot. I've been removing unnecessary DeviceGuard calls, but reached a point where it is not obvious what can be removed. In this issue I investigate exactly where DeviceGuard is being called to come up with potential solutions to improve the overhead.

### Some numbers
- benchmarking DeviceGuard with gbenchmark: ~200ns per DeviceGuard. Some DeviceGuards don't actually cost anything, but let's ignore those for now.
- cudnn/aten fused implementation/JIT LSTM with typical sizes (100 seq_len, 64 batch_size, 512 input_size, 512 hidden_size) take the following times on my machine:
```
Benchmarking LSTMs... (ms)
            name          avg_fwd          std_fwd          avg_bwd          std_bwd
           cudnn            5.549           0.1538            10.09           0.2957
            aten            6.822            0.337            20.07            0.335
             jit            9.152           0.1486            15.49          0.06995
```

| LSTM | # DeviceGuard calls | Total theoretical overhead (us) | % of total runtime |
| ------------- | ------------- | ---- | ---- |
| jit  | 2580  | 516 | 2.5 |
| aten  | 3643  | 728 | 2.6 |

### Breakdown of DeviceGuard top callsites
aten:
```
100     at::CUDAFloatType::_thnn_fused_lstm_cell(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&) const
100     at::CUDAFloatType::_thnn_fused_lstm_cell_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool)
const
100     at::TypeDefault::sum(at::Tensor const&, at::ArrayRef<long>, bool) const
200     at::TypeDefault::matmul(at::Tensor const&, at::Tensor const&) const
495     torch::autograd::InputBuffer::add(unsigned long, torch::autograd::Variable)
495     at::TypeDefault::add(at::Tensor const&, at::Tensor const&, at::Scalar) const
495     at::TensorIterator::allocate_outputs()
499     at::TypeDefault::mm(at::Tensor const&, at::Tensor const&) const
499     at::native::resize_cuda_(at::Tensor&, at::ArrayRef<long>)
600     at::CUDAFloatType::empty(at::ArrayRef<long>, at::TensorOptions const&) const
```
jit:
```
32      at::TypeDefault::sum(at::Tensor const&, at::ArrayRef<long>, bool) const
49      at::TypeDefault::cat(at::ArrayRef<at::Tensor>, long) const
75      torch::autograd::InputBuffer::add(unsigned long, torch::autograd::Variable)
75      at::TypeDefault::add(at::Tensor const&, at::Tensor const&, at::Scalar) const
75      at::TensorIterator::allocate_outputs()
312     torch::jit::fuser::cuda::FusedKernelCUDA::launch_raw(unsigned int, std::vector<void*, std::allocator<void*> >&) const
432     at::TypeDefault::mm(at::Tensor const&, at::Tensor const&) const
432     at::native::resize_cuda_(at::Tensor&, at::ArrayRef<long>)
1045    at::CUDAFloatType::empty(at::ArrayRef<long>, at::TensorOptions const&) const
```

[DeviceGuard callsites for aten LSTM forward pass + backward pass full data](https://gist.github.com/zou3519/d042e5280e150033adfabf9da71c7afc)
[DeviceGuard callsites for JIT LSTM forward pass + backward pass full data](
https://gist.github.com/zou3519/4c878d18158fbd3050f647eefb373981)

### Analysis
Since these are all running on the same device, we don't need all the DeviceGuard calls in theory. 

There used to be around 3x as many DeviceGuard calls for JIT LSTM. However, since the overhead is only 2.5% of the runtime now, one solution is to just do nothing about the DeviceGuard calls and leave them as-is.

**Comment by zdevito** [comment]
Nice analysis! I think the conclusion is correct: we should leave it as is until we speed everything else up.
