### ISSUE TITLE
DISABLED test_linear_binary_dynamic_shapes_cpp_wrapper (__main__.DynamicShapesCppWrapperCpuTests)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#139812]
Platforms: linux

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_cpu_cpp_wrapper.py%3A%3ADynamicShapesCppWrapperCpuTests%3A%3Atest_linear_binary_dynamic_shapes_cpp_wrapper%22%5D)).

This test is failing in trunk after https://github.com/pytorch/pytorch/pull/139136

cc @shunting314

**Comment by huydhn** [comment]
Reopen as the fix has been reverted

**Comment by Valentine233** [comment]
The UT can pass now with https://github.com/pytorch/pytorch/pull/141334.

**Comment by leslie-fang-intel** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/141334
