### ISSUE TITLE
misleading error message for custom torch.nn.Module property (incorrect property reported as missing)

### ISSUE THREAD

**Issue by juniorrojas** [pytorch/pytorch#13981]
## 🐛 Bug

Properties defined in classes that inherit from `torch.nn.Module` raise a misleading error message if non-existent properties are used inside the property definition. The error message reports the incorrect property as missing.

## To Reproduce

Run the following code snippet:

```py
import torch.nn as nn

class CustomModule(nn.Module):
    def __init__(self):
        super().__init__()
    
    @property
    def property_a(self):
        return self.property_b

m = CustomModule()
print(m.property_a)
```

## Expected behavior

Running the code snippet results in the following error message:

```
AttributeError: 'CustomModule' object has no attribute 'property_a'
```

This is misleading because the missing attribute is actually `property_b`. If the same code is implemented in a class that doesn't inherit from `torch.nn.Module`, the resulting error message is more appropriate since it reports `property_b` as missing. For example:

```py
class CustomModule2:
    def __init__(self):
        pass

    @property
    def property_a(self):
        return self.property_b

m2 = CustomModule2()
print(m2.property_a)
```

Displays the following error message:

```
AttributeError: 'CustomModule2' object has no attribute 'property_b'
```

## Environment

```
PyTorch version: 1.0.0.dev20181018
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.9.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: TITAN Xp
Nvidia driver version: 390.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy (1.15.2)
[pip3] numpydoc (0.8.0)
[pip3] torch (1.0.0.dev20181018)
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.1.85_cudnn7.1.2_1  [cuda91]  pytorch
[conda] pytorch-nightly           1.0.0.dev20181018 py3.7_cuda9.0.176_cudnn7.1.2_0    pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch
```

**Comment by asmeurer** [comment]
I am working on this.

This is an issue with the way Python handles attribute errors and `__getattr__`. Here is a simple example:

```py
>>> class Test:
...     def __getattr__(self, name):
...         raise AttributeError(name)
>>> class Test2(Test):
...     @property
...     def test(self):
...         return self.test1
>>> Test2().test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __getattr__
AttributeError: test
```

https://stackoverflow.com/questions/25115366/property-and-getattr-compatibility-issue-with-attributeerror suggests returning `self.__getattribute__(name)` from `__getattr__`. That does indeed seem to fix this specific issue

```pytb
>>> m.property_a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./torch/nn/modules/module.py", line 536, in __getattr__
    return self.__getattribute__(name)
  File "<stdin>", line 9, in property_a
  File "./torch/nn/modules/module.py", line 536, in __getattr__
    return self.__getattribute__(name)
AttributeError: 'CustomModule' object has no attribute 'property_b'
```

but I'm not sure what the implications of doing that are. I need to think about this some more.

**Comment by asmeurer** [comment]
We can also optimize for the fact that `register_parameter` and so on will not allow dynamic attributes that are already defined by removing the `try` and moving the `super().__getattribute__` call to the end. This makes dynamically defined attribute lookups just as fast as they are now, at the expense of making lookups for normally defined attributes even slower (about 10x, at 1.55 µs) (undefined attribute lookup time is still the same).

**Comment by asmeurer** [comment]
There is a slight performance improvement using `object.__getattribute__` instead of `super().__getattribute__()` (400 ns for regular attributes). It would only matter if someone does a multiple inheritance with another class that defines `__getattribute__`, and it can be worked around by the subclass redefining `__getattribute__` (but probably that would never happen anyway).

**Comment by asmeurer** [comment]
Fix at https://github.com/pytorch/pytorch/pull/16823

**Comment by fmassa** [comment]
@asmeurer nice write up and analysis!

I'm ccing @apaszke here, this is the related issue to #16823 where @asmeurer expands on the reasoning for the PR.

**Comment by apaszke** [comment]
Based on the discussion from #16823, I think we should close this as a wontfix. Thanks for everyone's comments and a PR!
