### ISSUE TITLE
DataLoaderTest.EnforcesOrderingAmongThreadsWhenConfigured is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14002]
Sample log:

```
Nov 14 22:58:37 /var/lib/jenkins/workspace/test/cpp/api/dataloader.cpp:885: Failure
Nov 14 22:58:37 Expected equality of these values:
Nov 14 22:58:37   value
Nov 14 22:58:37     Which is: 1
Nov 14 22:58:37   index++
Nov 14 22:58:37     Which is: 0
Nov 14 22:58:37 [  FAILED  ] DataLoaderTest.EnforcesOrderingAmongThreadsWhenConfigured (1 ms)
```

Full log: https://circleci.com/gh/pytorch/pytorch/245209?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SsnL** [comment]
previously reported at https://github.com/pytorch/pytorch/issues/13634 and #13819 . @goldsborough  claimed that it should be fixed in https://github.com/pytorch/pytorch/pull/13919

**Comment by goldsborough** [comment]
Yes yes I know. I will look

**Comment by ezyang** [comment]
Another occurrence: https://circleci.com/gh/pytorch/pytorch/247841?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment]
One more: https://circleci.com/gh/pytorch/pytorch/247797?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment]
Looking at CI HUD, it looks like all of these failures occur specifically on the Trusty py3.6 gcc7 configuration; something like a 30% failure rate. It's quite obvious: https://ezyang.github.io/pytorch-ci-hud/build/pytorch-master
