### ISSUE TITLE
cannot run a script which was named as dis.py

### ISSUE THREAD

**Issue by TuXiaokang** [pytorch/pytorch#14014]
## 🐛 Bug

the content in `dis.py` is

```
import torch
```
run 
```
python dis.py
```
While the error is:

```
Traceback (most recent call last):
  File "dis.py", line 1, in <module>
    import torch
  File "/usr/local/lib/python3.7/site-packages/torch/__init__.py", line 183, in <module>
    from .serialization import save, load
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 2, in <module>
    import inspect
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 56, in <module>
    for k, v in dis.COMPILER_FLAG_NAMES.items():
AttributeError: module 'dis' has no attribute 'COMPILER_FLAG_NAMES'
```

but if i modify the filename to another name （e.g. `abc.py`）, its ok.

 - PyTorch Version (e.g., 1.0): 1.0.0a0+e3bb6ff
 - OS (e.g., Linux): MacOS 10.14
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): MACOSX_DEPLOYMENT_TARGET=10.14 CC=clang  CXX=clang++ python setup.py install
 - Python version: python3.7.1
 - CUDA/cuDNN version: no
 - GPU models and configuration: 
 - Any other relevant information:

**Comment by soumith** [comment]
`dis` is the name of a python standard library package (disassembler for Python bytecode).
Hence you cant name a file dis.py in current working directory, as `import dis` will import this file instead
