### ISSUE TITLE
UserWarning: ONNX export failed on ATen operator _argmax because torch.onnx.symbolic._argmax does not exist

### ISSUE THREAD

**Issue by mathmanu** [pytorch/pytorch#14013]
## 🐛 Bug

A model containing argmax cannot be converted to ONNX. 
 
## To Reproduce

To reproduce the error, place the following in a python code and execute it:

import torch
import torch.nn
class ArgMaxModule(torch.nn.Module):
    def forward(self, x):
        pred = torch.argmax(x, dim=1, keepdim=True)
        return pred

model = ArgMaxModule()
input_rand = torch.rand((1, 3, 512, 1024))
torch.onnx.export(model, input_rand, 'argmax_model.onnx', verbose=True)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: CUDA 9.0
 - GPU models and configuration: GTX1080Ti
 - Any other relevant information:

## Additional context

The error reported is:

/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py:501: UserWarning: ONNX export failed on ATen operator _argmax because torch.onnx.symbolic._argmax does not exist
  .format(op_name, op_name))
graph(%x : Float(1, 3, 512, 1024)) {
  %1 : Long() = onnx::Constant[value={1}](), scope: ArgMaxModule
  %2 : Long() = onnx::Constant[value={1}](), scope: ArgMaxModule
  %3 : Long(1, 1, 512, 1024) = aten::_argmax(%x, %1, %2), scope: ArgMaxModule
  return (%3);
}

Traceback (most recent call last):
  File "./scripts/test_onnx.py", line 14, in <module>
    torch.onnx.export(model, input_rand, 'argmax_model.onnx', verbose=True)
  File "/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py", line 287, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::_argmax

Defined at:
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/functional.py(533): argmax
./scripts/test_onnx.py(7): forward
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py(467): _slow_forward
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py(477): __call__
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/jit/__init__.py(225): forward
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py(479): __call__
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/jit/__init__.py(172): get_trace_graph
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py(192): _trace_and_get_graph_from_model
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py(224): _model_to_graph
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py(281): _export
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py(104): export
/user/files/apps/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/onnx/__init__.py(27): export
./scripts/test_onnx.py(14): <module>

Graph we tried to export:
graph(%x : Float(1, 3, 512, 1024)) {
  %1 : Long() = onnx::Constant[value={1}](), scope: ArgMaxModule
  %2 : Long() = onnx::Constant[value={1}](), scope: ArgMaxModule
  %3 : Long(1, 1, 512, 1024) = aten::_argmax(%x, %1, %2), scope: ArgMaxModule
  return (%3);
}

**Comment by mathmanu** [comment]
If I add the following function into torch/onnx/symbolic.py

def _argmax(g, self, dim, keepdim=None):
    return g.op("ArgMax", self, dim, keepdim)

Then the export is able to proceed without error.

**Comment by soumith** [comment]
cc: @houseroad

**Comment by houseroad** [comment]
https://github.com/pytorch/pytorch/pull/17382 will fix the problem.

**Comment by spandantiwari** [comment]
https://github.com/pytorch/pytorch/pull/17382 has been merged and has fixed the problem. @houseroad @mathmanu This is can be closed.

**Comment by houseroad** [comment]
@spandantiwari thanks, closing.
