### ISSUE TITLE
why pytorch model file is very small< 20M>, but runtime much more than tensorflow<200+M> model file?

### ISSUE THREAD

**Issue by mlinxiang** [pytorch/pytorch#14020]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by fmassa** [comment]
The model file only contains the weights of the model.

During execution (and specially during training), we need to keep intermediate activations of the model in order to be able to compute backpropagation. This can take a significant amount of memory, specially if the model is deep.
