### ISSUE TITLE
"hiddenlayer" module issue

### ISSUE THREAD

**Issue by Bobbycraft** [pytorch/pytorch#140254]
### 🚀 The feature, motivation and pitch

I was using pytorch and the code is like

> model_graph = hl.build_graph(model, (naive1, naive2))

it cannot run right and it shows

> UnsupportedOperatorError
> Exporting the operator 'aten::randint' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues

it happens after i changed "_optimize_trace" to "_optimze_graph" in .../hiddenlayer/pytorch_builder.py, while it should be changed (i assume?) because it is called "_optimze_graph" in new version of Pytorch

**Comment by justinchuby** [comment]
This seems to be a custom use of an internal api, which is not supported. If you have access to where the torch.onnx.export function is called, consider update and test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!
