### ISSUE TITLE
cmake error about rocrand

### ISSUE THREAD

**Issue by NIEYALI** [pytorch/pytorch#14025]
When I ran        cmake ..
I met problems like this
CMake Error at cmake/public/LoadHIP.cmake:110 (find_package):
  By not providing "Findrocrand.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "rocrand", but
  CMake did not find one.

  Could not find a package configuration file provided by "rocrand" with any
  of the following names:

    rocrandConfig.cmake
    rocrand-config.cmake

  Add the installation prefix of "rocrand" to CMAKE_PREFIX_PATH or set
  "rocrand_DIR" to a directory containing one of the above files.  If
  "rocrand" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  cmake/public/LoadHIP.cmake:153 (find_package_and_print_version)
  cmake/Dependencies.cmake:671 (include)
  CMakeLists.txt:200 (include)

-- Configuring incomplete, errors occurred!

Should I have to install rocrand?

**Comment by iotamudelta** [comment]
You can just install the rocrand package from the ROCm repositories (either yum or apt) on `repo.radeon.com`

**Comment by NIEYALI** [comment]
@iotamudelta I installed ROCm from here
https://rocm.github.io/ROCmInstall.html
but same problem I met.

**Comment by bddppq** [comment]
Could you try putting /opt/rocm/bin and /opt/rocm/hcc/bin in your PATH?

**Comment by bddppq** [comment]
If it still doesn't work, would you be able to use docker? We have a well tested docker image at bddppq/pytorch-rocm:230-ubuntu

**Comment by bddppq** [comment]
@NIEYALI Sorry actually I'm a little bit confused. Is it you actually don't want to do rocm build but just ran into this cmake failure?

**Comment by bddppq** [comment]
Also could you check whether rocblas is actually installed in your system? (look at whether /opt/rocm/rocrand exists)

**Comment by NIEYALI** [comment]
@bddppq Thank you Sir, it doesn't exist.

**Comment by bddppq** [comment]
@NIEYALI I see. So to do ROCm build rocblas is a required dependency, so you need to install that. If you don't want to do ROCm build (but just happens you have partially installed ROCm before in your system), I have put up #14261 to allow disabling ROCm build with USE_ROCM=0 environment variable.

**Comment by Borda** [comment]
having the same error while compiling on the Kaggle platform... :flags:
