### ISSUE TITLE
[C10D] Add better profiling title for NCCL barrier

### ISSUE THREAD

**Issue by x41lakazam** [pytorch/pytorch#140257]
### 🚀 The feature, motivation and pitch

I'm working on analyzing distributed applications based on torch c10d, and the profiling title of the NCCL barrier is confusing.

Currently the NCCL barrier implementation calls an [allreduce operation](https://github.com/pytorch/pytorch/blob/565a7942eee1ddc23067cdbae597443d0f2290a0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L4418) but the [profiling title](https://github.com/pytorch/pytorch/blob/565a7942eee1ddc23067cdbae597443d0f2290a0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L3661) is left to be 'nccl:all_reduce', it would help debugging distributed applications if there would be an hint that this call is a barrier call.

I suggest changing the title to something like 'nccl:all_reduce_barrier'

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by mori360** [comment]
Thank you for putting this issue, we are working on it now. 
Do you have any repro for the profiling title?

**Comment by mori360** [comment]
Issue if solve by PR #140785
