### ISSUE TITLE
[feature request] Shifted Softplus

### ISSUE THREAD

**Issue by Tony-Y** [pytorch/pytorch#14028]
## 🚀 Feature
The shifted softplus activation function

SSP(x) = Softplus(x) - Softplus(0)

![fig_ssp](https://user-images.githubusercontent.com/11532812/48595087-a6f15480-e996-11e8-9141-9ca29b8187d9.png)

## Motivation
SchNet (https://arxiv.org/abs/1712.06113) uses a shifted softplus
<img width="408" alt="ssp" src="https://user-images.githubusercontent.com/11532812/48593239-4b6f9880-e98f-11e8-9a9c-342002293dc9.png">
as activation functions. This is like ELU(alpha=log2), but allows the use of the smooth derivatives of any order for training because it have infinite order of continuity. The SSP activation function would be usable instead of ELU where ELU is effective and the smooth derivates are required. Generally, SSP and Softplus are preferable for the following problem: 

<img width="828" alt="fitting_problem" src="https://user-images.githubusercontent.com/11532812/48655443-ef257b00-ea59-11e8-9211-45e82b9dfd70.png">

Sample code: https://github.com/Tony-Y/PotFit.git

## Pitch
It can be defined in torch.nn.modules.activation as follows:
```python
class SSP(Softplus):
    def __init__(self, beta=1, threshold=20):
        super(SSP, self).__init__(beta, threshold)
    def forward(self, input):
        sp0 = F.softplus(torch.zeros(1), self.beta, self.threshold).item()
        return F.softplus(input, self.beta, self.threshold) - sp0
```

## Alternatives
torch.nn.functional.softplus is defined as
```python
softplus = _add_docstr(torch._C._nn.softplus, r"""
softplus(input, beta=1, threshold=20) -> Tensor
""")
```
I think its sources are
pytorch/aten/src/THNN/generic/SoftPlus.c
pytorch/aten/src/THCUNN/SoftPlus.cu
pytorch/aten/src/THCUNN/generic/SoftPlus.cu

So, we can also add SSP.c and SSP.cu to ATEN, but I don’t  have enough knowledge of ATEN. It might be preferable that SSP is implemented as an option of Softplus like `Softplus(shifted=True)`.

**Comment by soumith** [comment]
torchcontrib might be a better place for this, rather than pytorch core. See our line of reasoning here: https://github.com/pytorch/pytorch/pull/3182#issuecomment-337982454

https://github.com/pytorch/contrib/

**Comment by Tony-Y** [comment]
@soumith I added a text that mentions a SSP variant more similar to ELU. I am not sure it is effective for any real applications.
