### ISSUE TITLE
binary_cross_functional throws "Unwrapping null optional"

### ISSUE THREAD

**Issue by siegebell** [pytorch/pytorch#14032]
## 🐛 Bug

[`torch.nn.functional.binary_cross_functional`](https://github.com/pytorch/pytorch/blob/6d094224b990b78d1629a86d3e21cb9f188a3a8b/torch/nn/functional.py#L1772) throws "Unwrapping null optional" if exactly one of `reduce` or `size_average` is not `None`. This was introduced by [#13707](https://github.com/pytorch/pytorch/commit/5163a289172efa3079f2e6169970db743a3e1001#diff-c66288b9ce36978f377a1a20d32ec53dR1772).

## To Reproduce

1. `binary_cross_entropy(torch.ones(3, 3), torch.ones(3, 3), reduce=False)`
2. `binary_cross_entropy(torch.ones(3, 3), torch.ones(3, 3), size_average=False)`

**Comment by driazati** [comment]
Fixed in #14003

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/14003
