### ISSUE TITLE
Visible devices are not respected on AMD systems

### ISSUE THREAD

**Issue by tbennun** [pytorch/pytorch#140318]
### 🐛 Describe the bug

When running distributed (or multi-process) jobs on AMD GPU systems with GPU isolation (i.e., the `*_VISIBLE_DEVICES` environment variable), PyTorch still tries to set the seed of all the devices it finds. This causes the following exception to be raised:

```
File "/path/to/torch/random.py", line 46, in manual_seed                                                                                               
  torch.cuda.manual_seed_all(seed)                                                                                                                                                                      
File "/path/to/torch/cuda/random.py", line 131, in manual_seed_all                                                                                    
  _lazy_call(cb, seed_all=True)                                                                                                                                                                        
File "/path/to/torch/cuda/__init__.py", line 249, in _lazy_call                                                                                       
  callable()                                                                                                                                                                                            
File "/path/to/torch/cuda/random.py", line 128, in cb                                                                                                  
  default_generator = torch.cuda.default_generators[i]                                                                                                                                                 
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^                                                                                                                                                 
IndexError: tuple index out of range
```

The underlying issue is that the visible devices are not properly detected due to reading the wrong environment variable name: `HIP_VISIBLE_DEVICES` should be renamed to `ROCR_VISIBLE_DEVICES` (see https://rocm.docs.amd.com/en/latest/conceptual/gpu-isolation.html#rocr-visible-devices ). On many batch schedulers and clusters, the ROCr environment variable is the one that is set.

This was likely introduced in #119182 (cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd)

I will push a pull request to fix this later today.

### Versions

PyTorch version: 2.5.1+rocm6.2

**Comment by jataylo** [comment]
Hey @tbennun, could you share a bit more details on the use case and how specifically ROCR_VISIBLE_DEVICES is being set.

```
python test.py
**GPU 0: UUID = 39343831-6166-3238-3063-306432653239**
GPU 1: UUID = 63393030-3436-3762-3630-616538653331
GPU 2: UUID = 63323363-3931-3661-3965-356636656331
GPU 3: UUID = 34343836-3031-6533-3032-383564333863
GPU 4: UUID = 39633466-3432-6662-3632-663664363461
GPU 5: UUID = 32656439-3764-3637-3633-306231306438
GPU 6: UUID = 39613263-6465-6637-6536-623861366564
**GPU 7: UUID = 64633334-3430-3137-3133-666431666333**
```

```
ROCR_VISIBLE_DEVICES="0,7" HIP_VISIBLE_DEVICES="0,1" python tes
t.py
GPU 0: UUID = 39343831-6166-3238-3063-306432653239
GPU 1: UUID = 64633334-3430-3137-3133-666431666333
```

My understanding here is that ROCR_VISIBLE_DEVICES will limit gpus available from the runtime, they can be used in conjunction and from pytorch perspective we should respect the HIP/CUDA_VISIBLE_DEVICES selection as this is application specific control.

e.g.
```
ROCR_VISIBLE_DEVICES="0,7,3,1" HIP_VISIBLE_DEVICES="0,1,2" pyth
on test.py
GPU 0: UUID = 39343831-6166-3238-3063-306432653239
GPU 1: UUID = 64633334-3430-3137-3133-666431666333
GPU 2: UUID = 34343836-3031-6533-3032-383564333863
```

I'm not sure I fully appreciate why we need to read this in during visible devices being set as suggested in the PR https://github.com/pytorch/pytorch/pull/140320.

Although looking at this I do see some clear issues

PyTorch 2.5
```
ROCR_VISIBLE_DEVICES="0" HIP_VISIBLE_DEVICES="0,1" 
print(torch.cuda.device_count())
>2
```

PyTorch 2.0
```
ROCR_VISIBLE_DEVICES="0" HIP_VISIBLE_DEVICES="0,1" 
print(torch.cuda.device_count())
>1
```

So it does seem that HIP_VISIBLE_DEVICES is now incorrectly overiding ROCR_VISIBLE_DEVICES, but I'm not sure simply adding this env var into an option is `_parse_visible_devices` as in https://github.com/pytorch/pytorch/pull/140320 is the correct solution...

cc: @jithunnair-amd @pruthvistony @jeffdaily

**Comment by tbennun** [comment]
@jataylo Thank you for the extensive testing and the new PR!

For your previous comment, `ROCR_VISIBLE_DEVICES` is currently set by batch schedulers when used in HPC systems (supercomputers, cloud service providers). You can see it used in the source codes of SLURM's `srun`/`sbatch` (https://github.com/SchedMD/slurm/blob/master/src/plugins/gres/common/gres_common.c#L307), mpibind (https://github.com/LLNL/mpibind/blob/master/src/mpibind.c#L1052), sarus (https://github.com/eth-cscs/sarus/blob/master/src/hooks/amdgpu/AmdGpuHook.cpp#L66), and others. 

The end result is that a simple `srun -N2 -n16 python myscript.py` (i.e., the standard use case for running on 8 GPUs with two nodes) should show each process its own GPU. This works on an NVIDIA-based system but not an AMD-based system.

From what I understand in the documentation, the source code of the ROCm platform, and your examples, `ROCR_VISIBLE_DEVICES` is the lower driver-level API and `HIP_VISIBLE_DEVICES` was added as a compatibility layer for HIP to be in parity with CUDA.

I will check if your PR works and report back, but looking at the code, I think it should. Thanks again!

**Comment by tbennun** [comment]
@jataylo Side note on the work on this issue, why create a second PR rather than give comments on mine? Given that your #140398 is very similar to my #140320, could you please at least make me a co-contributor on the PR? In that case, I am happy to close my PR.

**Comment by ausellis0** [comment]
Hi @jataylo, I think @tbennun's co-contributor suggestion is fair. Thanks!

**Comment by jataylo** [comment]
> @jataylo Side note on the work on this issue, why create a second PR rather than give comments on mine? Given that your #140398 is very similar to my #140320, could you please at least make me a co-contributor on the PR? In that case, I am happy to close my PR.

Hey @tbennun, mostly for speed here. More than happy to have you as co-contributor on this PR, or if you feel that it's more fair please feel free to cherry-pick my commits into your PR and you can add me as co-author.

**Comment by tbennun** [comment]
@jataylo I don't mind either way, so go ahead and add me to yours instead (so you can keep track of the comments).

I can verify that your PR works!

**Comment by tbennun** [comment]
OK, #140320 is at parity with yours, you can use mine.

**Comment by tbennun** [comment]
@jataylo I pushed another commit that fixed the linter issue from before, adds some tests, and makes the behavior match what you demonstrated above:
```sh
$ ROCR_VISIBLE_DEVICES=0 python -c 'import torch; print(torch.cuda._parse_visible_devices())'
[0]
$ ROCR_VISIBLE_DEVICES=1,2 python -c 'import torch; print(torch.cuda._parse_visible_devices())'
[1, 2]
$ ROCR_VISIBLE_DEVICES=1,2 HIP_VISIBLE_DEVICES=1 python -c 'import torch; print(torch.cuda._parse_visible_devices())'
[2]
$ HIP_VISIBLE_DEVICES=1 python -c 'import torch; print(torch.cuda._parse_visible_devices())'
[1]
$ ROCR_VISIBLE_DEVICES=GPU-DEADBEEFDEADBEEF,GPU-DEADBEEFDEADBEEF,GPU-DEADBEEFDEADBEEA HIP_VISIBLE_DEVICES=2,1 python -c 'import torch; print(torch.cuda._parse_visible_devices())'
['GPU-DEADBEEFDEADBEEA', 'GPU-DEADBEEFDEADBEEF']
```

**Comment by jataylo** [comment]
@tbennun I think its probably worth listing this as a cherry pick commit for release/2.6 also as I think we probably just missed this

**Comment by jataylo** [comment]
Reopening until the PR re-lands
