### ISSUE TITLE
`eval("L['self'].state[Parameter containing:", ...)` breaks the guard setting in dynamo

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#140393]
### 🐛 Describe the bug

When creating an optimizer with multiple param groups and optimizing just one, I'm getting:

```python
  File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 1184, in get
    return eval(name, self.scope, _get_closure_vars())
torch._dynamo.exc.InternalTorchDynamoError: SyntaxError: invalid syntax. Perhaps you forgot a comma? (<string>, line 1)
```

from the call to

```
E1112 11:57:34.250000 95829 torch/_guards.py:300] [5/0]   File "/Users/vmoens/venv/rl/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 1184, in get
E1112 11:57:34.250000 95829 torch/_guards.py:300] [5/0]     return eval(name, self.scope, _get_closure_vars())
```

where the error comes from the fact that eval is called with the following string:
```
E1112 11:57:34.250000 95829 torch/_guards.py:300] [5/0]     L['self'].state[Parameter containing:
E1112 11:57:34.250000 95829 torch/_guards.py:300] [5/0]                     ^^^^^^^^^^^^^^^^^^^^
E1112 11:57:34.250000 95829 torch/_guards.py:300] [5/0] SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

Not entirely sure what to do with this. Is this normal that putting guards involves executing code retrieved from `obj.__repr__`? Isn't that a bit dangerous (I could malitiously put in my repo a `__repr__` that executes any code I want at compile time then)?

I tried to produce a MRE but couldn't. Here is the [code that causes that](https://github.com/pytorch/rl/blob/b52276cd3fc58ab83f4cfefd175424b7fdbb8a57/sota-implementations/crossq/crossq.py#L111-L132).

### Versions

nightly

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by janeyx99** [comment]
cc @mlazos

**Comment by mlazos** [comment]
Yeah we should not be calling repr, we should be using sources to generate a python expression. I'll take a look - not sure where this is coming from
