### ISSUE TITLE
[Aten] at::randint doesn't return a variable

### ISSUE THREAD

**Issue by alcinos** [pytorch/pytorch#14031]
## 🐛 Bug

There is a behavior mismatch between at::normal (for example), which returns  a variable, and at::randint, that doesn't.

## To Reproduce

```
auto v1 = at::normal(torch::zeros({23, 32}));
std::cout << v1.type().toString() << std::endl;
// prints Variable[CPUFloatType]

auto v2 = at::randint(100, {45, 2});
std::cout << v2.type().tString() << std::endl;
// prints CPUFloatType
```
## Expected behavior

Both functions should return variables

## Environment

Happens on recent master.

**Comment by vishwakftw** [comment]
The variable in the case of `at::normal` is because of `torch::zeros`. Functions in the `torch` namespace are by default `Variable`s.

**Comment by alcinos** [comment]
Oh, ok I was not expecting the type of the mean to leak into the return type of `at::normal`, thanks for the hint.
`torch::randint` seems to be the way to go. I thought that every function would be returning a Variable, even  from `at::`, but apparently that's not the case (yet?).

Thanks for your help anyways :)
