### ISSUE TITLE
Aten ops might not support non-contiguous inputs, this is a problem for fallbacks.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#140462]
### 🚀 The feature, motivation and pitch

https://github.com/pytorch/pytorch/issues/140452 is caused by `aten._weight_norm_interface_backward` not supporting non-contiguous inputs.

adding `make_fallback(aten._weight_norm_interface_backward, require_contiguous)` to lowerings.py fixed the issue.

But this seems like a broader problem - I don't think we strictly require that all operators support non-contiguous inputs in PyTorch. Comprehensive padding exacerbates this problem significantly.

cc: @shunting314 

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov

**Comment by ezyang** [comment]
If https://github.com/pytorch/pytorch/issues/140913 is same root cause as this, fixing only weight norm is not enough, there are several norm backwards that are affected equivalently (group norm at least).

**Comment by ngimel** [comment]
And the ops that don't support contiguous inputs don't throw the errors when they get discontiguous inputs? Or the inputs were made contiguous at higher level dispatch, and aten impls rely on inputs guaranteed to be contiguous with eager execution?

**Comment by ezyang** [comment]
@ngimel since it's silent correctness problem, it looks like the latter.

@shunting314 when you fix, please also see if it fix the test in here: https://www.internalfb.com/diff/D66050788

**Comment by zou3519** [comment]
Yes, eager-mode execution generally supports contiguous and discontiguous inputs by adding .contiguous calls in various places. This does not mean that aten ops support all contiguities. Furthermore, inductor will optimize (ignore) .contiguous calls it sees.

**Comment by shunting314** [comment]
Here is a PR that fixes for 'weight norm backward': https://github.com/pytorch/pytorch/pull/140996 . I'll try in on the other cases:
- https://github.com/pytorch/pytorch/issues/140913
- https://www.internalfb.com/diff/D66050788

**Comment by shunting314** [comment]
@ezyang https://www.internalfb.com/diff/D66050788 probably is caused by something else since
1. I applied my fix and it still fail
2. I disable the padding (TORCHINDUCTOR_COMPREHENSIVE_PADDING = 0) and it still fail
3. I printed all implicit fallbacks, there are just two (aten.normal_functional.default , prims.normal.default ) . It's unlikely that these ops works incorrectly due to input strides.

**Comment by shunting314** [comment]
Confirmed that the group norm issue is unrelated: https://github.com/pytorch/pytorch/issues/140913#issuecomment-2484562819

**Comment by ezyang** [comment]
> I printed all implicit fallbacks, there are just two (aten.normal_functional.default , prims.normal.default ) . It's unlikely that these ops works incorrectly due to input strides.

OK, this seems pretty definitive to me, thanks.
