### ISSUE TITLE
☂️ Many ecosystem libraries started to fail with `std::bad_alloc` after Nov 1st

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#140590]
### 🐛 Describe the bug

See:
 - https://hud.pytorch.org/hud/pytorch/vision/7d077f131217dc03813d97d7524ea3aeba7dd7e1/1?per_page=50&name_filter=docs&mergeLF=true
 - https://hud.pytorch.org/hud/pytorch/torchrec/be4b9c743128373532f151869d1be92ea5ceb7b0/1?per_page=50&name_filter=CPU%20unit%20test&mergeLF=true
 - TorchAO issue https://github.com/pytorch/ao/issues/1229
 - TorchBench: https://github.com/pytorch/benchmark/actions/runs/11807380851/job/32893936489?pr=2534#step:6:861
 - Triton built from source: https://github.com/pytorch/pytorch/issues/140423

### Versions

CI

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim

**Comment by atalman** [comment]
Latest build failure with torchrec: https://github.com/pytorch/torchrec/actions/runs/11897072317/job/33150462304?pr=2567#step:14:5224

**Comment by malfet** [comment]
If it's limited to the JIT script, one needs to check that parts of libstdc++ runtime are not linked separately for libtorch_cpu and libtorch_python

**Comment by malfet** [comment]
Per @davidberard98 this issues is probably related: https://github.com/pytorch/pytorch/issues/140423

**Comment by FindHao** [comment]
https://github.com/pytorch-labs/tritonbench/actions/runs/12055925374/job/33617344431
tritonbench ci with triton stable version also has such issue.

**Comment by atalman** [comment]
> If it's limited to the JIT script, one needs to check that parts of libstdc++ runtime are not linked separately for libtorch_cpu and libtorch_python

@malfet could you please provide more details, what exactly we should check ? ldd command will probably help here.

**Comment by atalman** [comment]
Could this PR caused the failure: https://github.com/pytorch/pytorch/pull/127936 ?  Here is the PR where I reverted some of the changes landed on Nov 2 nightly: https://github.com/pytorch/pytorch/pull/141782  . Looks like after revert of https://github.com/pytorch/pytorch/pull/127936 I can't repro the std:bad_alloc anymore with repro I use executing this workfow: https://github.com/pytorch/vision/blob/main/.github/workflows/docs.yml

**Comment by jerryzh168** [comment]
looks like the issue comes back again: https://github.com/pytorch/ao/actions/runs/12123456248/job/33798989902 after we migrate to linux_job_v2: https://github.com/pytorch/ao/pull/1302

**Comment by atalman** [comment]
Revert landed in Dec 3 nightly, closing this issue.

**Comment by leslie-fang-intel** [comment]
Hi @atalman, since this failure only caught by CI in Torch Library, do you have any suggestion to add some accept testing to PyTorch Core CI to gate this kind of issue?
