### ISSUE TITLE
Unable to pickle torch dtype objects in Python 3.5

### ISSUE THREAD

**Issue by BarclayII** [pytorch/pytorch#14057]
## 🐛 Bug

When pickling a `torch.dtype` object, Python 3.5 reports an obscure error "can't pickle int objects".

## To Reproduce

```python
In [1]: import torch

In [2]: import pickle

In [3]: with open('/tmp/a', 'wb') as f:
   ...:     pickle.dump(torch.float32, f)
   ...:     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-769b4901f38c> in <module>()
      1 with open('/tmp/a', 'wb') as f:
----> 2     pickle.dump(torch.float32, f)
      3 

~/anaconda3/envs/tmp/lib/python3.5/copyreg.py in _reduce_ex(self, proto)
     63     else:
     64         if base is self.__class__:
---> 65             raise TypeError("can't pickle %s objects" % base.__name__)
     66         state = base(self)
     67     args = (self.__class__, base, state)

TypeError: can't pickle int objects
```

## Expected behavior

In Python 3.6 one can pickle torch dtypes successfully.

## Environment

```
Collecting environment information...
PyTorch version: 0.4.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Fedora release 29 (Twenty Nine)
GCC version: (GCC) 8.2.1 20181011 (Red Hat 8.2.1-4)
CMake version: version 3.12.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 410.73
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.2)
[pip] torch (0.4.1.post2)
[conda] pytorch                   0.4.1           py35_py27__9.0.176_7.1.2_2    pytorch
```

**Comment by soumith** [comment]
cc: @gchanan is this going to be fixed? @ailzhang fixed it for device here https://github.com/pytorch/pytorch/pull/7713

**Comment by jermainewang** [comment]
Hi, here is another example:
```python
import networkx as nx  # if this line is removed, it works !!
import torch
import pickle
import io

def _reconstruct_pickle(obj):
    f = io.BytesIO()
    pickle.dump(obj, f)
    f.seek(0)
    obj = pickle.load(f)
    f.close()
    return obj

def test():
    x = torch.float32
    new_bg = _reconstruct_pickle(x)

test()
```
It raised error:
```
Traceback (most recent call last):
  File "t.py", line 18, in <module>
    test()
  File "t.py", line 16, in test
    new_bg = _reconstruct_pickle(x)
  File "t.py", line 8, in _reconstruct_pickle
    pickle.dump(obj, f)
TypeError: can't pickle module objects
```

My environment:
```
Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Arch Linux
GCC version: (GCC) 8.2.1 20181127
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: Quadro K2000
GPU 1: Tesla K20c

Nvidia driver version: 415.27
cuDNN version: /usr/lib/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip3] numpy==1.14.6
[pip3] torch==1.0.1.post2
[conda] Could not collect
```

**Comment by BarclayII** [comment]
The example above seems to fail in all pickle protocols except 4 in Python 3.

**Comment by ailzhang** [comment]
Actually torch dtype object is already serializable. Closing....
```
In [6]: b = copy.deepcopy(a)

In [7]: id(b)
Out[7]: 139818768678472

In [8]: id(a)
Out[8]: 139818768678472

In [9]: import pickle

In [10]: with open('/tmp/a', 'wb') as f:
    ...:     pickle.dump(torch.float32, f)
    ...:
```

**Comment by ailzhang** [comment]
Hmmm I will leave this open as the example script is failing for python 2.7. 
```
import torch
import pickle
import io

def _reconstruct_pickle(obj):
    f = io.BytesIO()
    pickle.dump(obj, f)
    f.seek(0)
    obj = pickle.load(f)
    f.close()
    return obj

def test():
    x = torch.float32
    new_bg = _reconstruct_pickle(x)

test()
```

**Comment by jackroos** [comment]
@ailzhang please see this example gived by @jermainewang: https://github.com/dmlc/dgl/issues/438#issuecomment-472177987 . 
Actually, when some library like 'networkx' is imported, torch.dtype will failed to be pickled.

**Comment by ailzhang** [comment]
@jackroos I tried the example script with networkx in python3.6 and it worked without an issue. There might be some env difference here causing the problem.

**Comment by jermainewang** [comment]
Yeah, it's also weird that not all the import causes this problem. For example, `import numpy` has no problem. Do you know how could we debug into this? so maybe we could provide more accurate reason.

**Comment by ailzhang** [comment]
Yea I spent more time on this and it might be related to the difference between import semantics in python2 and 3. (at least for the python2.7 failure that I can repro locally). 
What's happening now is python2 fails to find out `torch.float32` is in module `torch`. Basically it's trying to look for `torch.float32` as a string in module `__main__`, which what it should do is looking for `float32` in module `torch`. 
Similar thing I saw when implementing `torch.hub` is python2 fails to handle dotted structure when parsing module structures in importing... Python3 handles this well. 
I think it could potentially be solved by setting `__module__` manually on torch.dtype to let python2 know the right module to look for. I'm trying to find out how to do it. I will let you know if this works or not. :D

**Comment by ailzhang** [comment]
@jackroos @jermainewang Would you mind trying out the fix above and see if it fixes your issue? It's mainly for fixing python2.7 one that I reproed locally, but if you could get me a repro for the `networkx` with python3, happy to look into that as well.

**Comment by jermainewang** [comment]
Hi @ailzhang , do you know where `torch.dtype` is defined? I don't know the exact place to put `__module__`.

**Comment by ailzhang** [comment]
@jermainewang Yea could you checkout #18045 and build from source to see if it fixes your issue? I realized `__module__` is defined but python2.7 failed to parse it because our dtype name is a bit confusing.

**Comment by ailzhang** [comment]
I'm closing this as #18045 has landed. Please feel free to reopen if it doesn't fix your issue. Thanks!
