### ISSUE TITLE
do pytorch c++ jit trace run model need more gpu memory than python env of the same model?

### ISSUE THREAD

**Issue by mlinxiang** [pytorch/pytorch#14067]
i have a nvidia 1070 gpu/8G memory, i have a pytorch model for inference, and i directly run it the gpu memory cost as follow
![image](https://user-images.githubusercontent.com/6283983/48594685-92a85a00-e98c-11e8-8270-e53264439789.png)

then i first load the model and then use follow code to do jit trace, and use jit module run the gpu memory cost as follow
![image](https://user-images.githubusercontent.com/6283983/48594713-bb305400-e98c-11e8-8031-cac04988b4a2.png)
![image](https://user-images.githubusercontent.com/6283983/48594734-d3a06e80-e98c-11e8-8208-2ce3d6e9afd2.png)

**### when i use pytorch c++ api to load the saved jit trace model.pt error as follow, does c++ need more gpu memory?**
![image](https://user-images.githubusercontent.com/6283983/48594777-05193a00-e98d-11e8-866d-1adf6273aed2.png)

when i gdb the c++ example and step by step to the forward() cause fault, and gpu memory as follow
![image](https://user-images.githubusercontent.com/6283983/48594961-d354a300-e98d-11e8-90f4-b99d8df1651d.png)

**Comment by SsnL** [comment]
It is possible, if you model has a bunch of in-place ops like relu_. We are adding mutability to JIT so this will be fixed eventually. cc @zou3519

**Comment by mlinxiang** [comment]
will this has plan to fix?

**Comment by SsnL** [comment]
Yes, as I said above, this will be fixed when we have mutability.

**Comment by soumith** [comment]
@suo are we tracking mutability in any other issue? if we are, I can close this as duplicate.

**Comment by suo** [comment]
Not on github, we can keep this one open for now

**Comment by mlinxiang** [comment]
do this feature has any timeline?

**Comment by apaszke** [comment]
What kind of model are you using?

**Comment by mlinxiang** [comment]
any progress?
do there have a timeline?

**Comment by suo** [comment]
Support for mutable ops in the hybrid front-end will be in the 1.0 stable release, due early December.

**Comment by mlinxiang** [comment]
@suo i use the master branch to replay up experiment, found that the memory phenomenon had gone. the feature had merged?

**Comment by soumith** [comment]
closing because mutable ops support is now merged, and the symptoms should not be present anymore
