### ISSUE TITLE
Check input size for CUDA convolutions

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#1406]
For example:

```python
import torch
input = torch.autograd.Variable(torch.randn(3, 3, 7, 7))
x = torch.nn.Conv2d(1, 10, 3, 3)
```

The CPU version correctly gives an error:

```python
>>> x(input)
RuntimeError: Need input of dimension 4 and input.size[1] == 1 but got input to be of shape: [3 x 3 x 7 x 7]
```

But the CUDA/cuDNN version gives an ambiguous error `RuntimeError: CUDNN_STATUS_BAD_PARAM`:

```python
>>> x.cuda()(input.cuda())
RuntimeError: CUDNN_STATUS_BAD_PARAM
```

**Comment by alykhantejani** [comment]
This problem seems to be only with the CUDNN version not the CUNN version as all of the THCUNN and THNN *Convolution functions have a `*Convolution_shapeCheck` function. 

Maybe the checks for CUDNN can go in the `Convolution` constructor in `pytorch/torch/csrc/cudnn/Conv.cpp`?

@colesbury I'm happy to send a PR if this seems like a sensible approach

**Comment by apaszke** [comment]
Yes, patches welcome! I don't think you can do this check in the constructor, because it doesn't have the input yet. The checks should probably go into the `apply` function.

**Comment by alykhantejani** [comment]
@apaszke I think the constructor is also passed the input, here's the signature:

```
Convolution::Convolution(
    cudnnDataType_t dataType, THVoidTensor* input, THVoidTensor* weight,
    THVoidTensor* bias, THVoidTensor* output, std::vector<int> pad,
    std::vector<int> stride, std::vector<int> dilation, int groups, bool transposed)
  : idesc(), odesc(), odesc_bias(), bdesc(), wdesc(), cdesc(), groups(groups)
  , transposed(transposed)
```

I thought this would be a good place to a) not pollute convolution.cpp with cudnn specific things and b) as the constructor is already doing input dim checks. (Unless I am misunderstanding something)

**Comment by apaszke** [comment]
Ok, adding it in the constructor sounds good if it's already doing shape checks.

**Comment by alykhantejani** [comment]
@apaszke is it ok to now assume that the input tensor is always batched. For example in `VolumetricDilatedConvolution.c` it has the `dimf` variable to see which index in the input tensor should  match the `nInputPlanes` (0 if non-batched input). 

As the cudnn Convolution is pretty generic, I can't see how we can tell if an input is batched or not, but if we can assume batched adding the dim checks is quite easy.

**Comment by fmassa** [comment]
@alykhantejani pytorch assumes that all inputs are batched, contrary to lua torch.
