### ISSUE TITLE
cannot change the device of Tensor

### ISSUE THREAD

**Issue by szupzp** [pytorch/pytorch#14068]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by SsnL** [comment]
you can never change device in-place. methods like .to give you a new tensor on desired device.

**Comment by szupzp** [comment]
@SsnL  forget to describe my issue.
