### ISSUE TITLE
torch.cuda.memory_usage() returns percent of time over the past sample period global memory being read/written for Nvidia and MegaBytes for AMD

### ISSUE THREAD

**Issue by yuguo68** [pytorch/pytorch#140638]
### 🐛 Describe the bug

torch.cuda.memory_usage source code: https://github.com/pytorch/pytorch/blob/2f1dbfea020e8db7fbeaf0767962055d8ce0779b/torch/cuda/__init__.py#L1153C5-L1153C17

For AMD, amdsmi_get_gpu_vram_usage() API "Returns the VRAM usage (both total and used memory) in MegaBytes."
https://rocm.docs.amd.com/projects/amdsmi/en/docs-5.7.1/doxygen/docBin/html/group__gpumon.html#ga1408b9ef1dcc59bea2ce3e37fb1d19e2

On the other hand, for Nvidia, nvmlDeviceGetUtilizationRates(handle)
https://github.com/pytorch/pytorch/blob/2f1dbfea020e8db7fbeaf0767962055d8ce0779b/torch/cuda/__init__.py#L1169
actually returns the "
Percent of time over the past sample period during which global (device) memory was being read or written." from https://docs.nvidia.com/deploy/nvml-api/structnvmlUtilization__t.html#structnvmlUtilization__t

It seems that we need to use nvmlDeviceGetMemoryInfo instead. 
https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g2dfeb1db82aa1de91aa6edf941c85ca8

If we do return the size of used memory, the used memory is in bytes instead, e.g., https://docs.nvidia.com/deploy/nvml-api/structnvmlMemory__t.html#structnvmlMemory__t

### Versions

main branch

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

**Comment by ezyang** [comment]
Oops! Send us a patch?

**Comment by yuguo68** [comment]
> Oops! Send us a patch?

@ezyang I realized that for Nvidia the current API (`pynvml.nvmlDeviceGetUtilizationRates(handle).memory`) actually returns percent of time over the past sample period global memory being read/written instead of used memory size. Shall we change it to `pynvml.nvmlDeviceGetMemoryInfo(handle).used` which represents the used memory size?

**Comment by jataylo** [comment]
It depends which is truely the correct metric we want to return, memory utilisation or memory usage.

I have a draft PR to bring AMD in line with NVIDIA https://github.com/pytorch/pytorch/pull/139900

But if actual memory usage in MB is what was intended perhaps we should change the NV implementation?

**Comment by hongxiayang** [comment]
Thank you @jataylo . This PR https://github.com/pytorch/pytorch/pull/139900 helps a lot.

**Comment by xw285cornell** [comment]
Great, looks like we're thinking about the same thing :)  https://github.com/pytorch/pytorch/pull/140685 Let's go with this PR. I agree on the memory utilization (i actually changed the API to be memory utilization in my PR but yes it's BC-breaking so let's probably go with this.

**Comment by ezyang** [comment]
yes please don't change the existing api
