### ISSUE TITLE
`torch._transformer_encoder_layer_forward` usage of SDPA attention instead of native_MHA

### ISSUE THREAD

**Issue by michaelfeil** [pytorch/pytorch#140768]
### 🚀 The feature, motivation and pitch

Discussion about attention usage of: https://github.com/pytorch/pytorch/blob/02d0c43c3243f967856798fa8622a8727f9d36a3/aten/src/ATen/native/transformers/transformer.cpp#L109C1-L122C19

It is not clear to me what kind of attention version is dispatched with _transformer_encoder_layer_forward (transformer encoder layer) - it seems that `at::_native_multi_head_attention` is used, which could potentially open up a optimization opportunity in case this not the SDPA backend.
I could not find the code for `at::_native_multi_head_attention` in the Github repo.

Potentially, triton_multi_head_attention dispatches SDPA or multi_head_attention_cuda, which make use of a fused attention:
https://github.com/pytorch/pytorch/blob/217d328764be9a8a4c5f846f762e83100a595905/aten/src/ATen/native/transformers/attention.cpp#L1008

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by drisspg** [comment]
we dispatch to sdpa when it is using the fused version: https://github.com/pytorch/pytorch/blob/bf78a0fa968103cff9e2652316071d6cdb0e6296/aten/src/ATen/native/transformers/cuda/attention.cu#L572
