### ISSUE TITLE
Batched triu, tril

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#14071]
## 🚀 Feature
Batched `triu` and `tril` for batches of matrices.

## Motivation

We have more batched linear algebra operations than earlier, and it would be nice to add to this to the suite as well.

## Additional Context

This would also help simplify code in batched Cholesky.

**Comment by vishwakftw** [comment]
I'll take this up.

@t-vi I will expand on portion of your batch potrf PR for that. Hope you don't mind.

**Comment by t-vi** [comment]
@vishwakftw Please do, thanks!

**Comment by mrshenli** [comment]
closed by #15257
