### ISSUE TITLE
I install caffe2 from conda, but why does it use the path in which I install caffe2 from source?

### ISSUE THREAD

**Issue by lilichu** [pytorch/pytorch#14073]
hi! I install caffe2 by conda:
`conda install pytorch-nightly cuda90 -c pytorch`.
But when I run `from caffe2.python import core` in python, the issue is:
```
(envs1) user@ubuntu:~$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.python import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/pytorch/build/caffe2/python/__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
  File "/home/user/pytorch/build/caffe2/proto/caffe2_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google'
```
`/home/user/pytorch/build/` is the path in which I used to install caffe2 from source.
why does it use the path from source when I run caffe2 in conda environment?  What should I do? thanks!

**Comment by FastStim** [comment]
Hello @lilichu!  Several solutions in this:
- Use python version on conda.  example  ~/anaconda2/bin/python script.py
- Change default python version.
- add path for caffe2 library. my path: ~/anaconda2/envs/pytorch/lib/python3.7/site-packages/caffe2
you path probably: ~/anaconda2/lib/python3.7/site-packages/caffe2

I do not understand this well, but think it will help.

**Comment by lilichu** [comment]
I run `unset PYTHONPATH` in conda, then it is OK.
