### ISSUE TITLE
Make nvidia pypi dependencies optional?

### ISSUE THREAD

**Issue by eval-dev** [pytorch/pytorch#140737]
### 🚀 The feature, motivation and pitch

Today, when installing torch whl, it automatically installs many nvidia-* packages, like nvidia-cuda-runtime-cu12. However, there're scenarios where our docker image already has correct nvidia bits installed in the system (for example, cuda in /usr/local/cuda) and we don't want to add another copy of binaries to python package dir.

So can we make the nvidia denpendencies optional by moving these into `setup(extras_require={"nvidia": ...}`? As a result, `pip install torch` will install the torch bits only, and `pip install torch[nvidia]` installs everything.

cc @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
This would work wonders in your case, but it will ruin the experience for majority of the users who do not have cuda toolkit installed, or have one that is different from the one PyTorch was build against

**Comment by BartoszJanuszNA** [comment]
I agree with eval-dev, currently installing cpu-only pytorch with tools like Poetry is a nightmare. Having CUDA dependencies as extras would be perfect. Tensorflow does that:
https://www.tensorflow.org/install/pip

```
# CPU only:
python3 -m pip install tensorflow
# GPU support:
python3 -m pip install tensorflow[and-cuda] 
```

**Comment by eval-dev** [comment]
@BartoszJanuszNA thank you for mentioning #139761 , now I will close this thread.
