### ISSUE TITLE
No Python3.8 build for Pytorch 2.5.x

### ISSUE THREAD

**Issue by ghostplant** [pytorch/pytorch#140798]
### 🐛 Describe the bug

`pip3.8 install torch==2.5.0 --index-url https://download.pytorch.org/whl/cu118` returns failure.

### Versions

I am using Ubuntu 20.04 whose python3 environment is 3.8
Hope to add 3.8 support for Pytorch 2.5.x

cc @seemethere @malfet @osalpekar @atalman @svekars @brycebortree @sekyondaMeta @AlannaBurke

**Comment by antoniojkim** [comment]
+1

We're also unfortunately stuck on python 3.8 at the moment. So, we need a 2.5.1 cpu build of PyTorch available as well.

The minimum python version for 2.5.1 is still set to 3.8.0
https://github.com/pytorch/pytorch/blob/a8d6afb511a69687bbb2b7e88a3cf67917e1697e/setup.py#L217
So, was this an oversight? Or was it announced somewhere that support for python 3.8 would be dropped for 2.5?

CC: @malfet @atalman

**Comment by malfet** [comment]
@antoniojkim Python-3.8 has reached it's end of life in October 2024, and therefore PyTorch stopped supporting it, as one can clearly see in https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix so it's not an oversight, though it was an oversight not to update the metadata for 2.5 release

**Comment by malfet** [comment]
@ghostplant , @antoniojkim can you please provide a bit more detail on why and for how long you might rely on a Python version after it reaches end of life. And say what new framework features you are planning to use after it happens.

PyTorch drops support for Python/OS after they reach end of life, but if there are good reasons when it has to be extended, one can make an exception.

**Comment by antoniojkim** [comment]
We're currently in the middle of doing a major upgrade that will likely not be finished for a couple months. But in the meantime, we would still like to be on the latest Pytorch version.

We thought that torch 2.5 would still support Python 3.8 because of the minimum specified in the `setup.py` and were surprised to see that there were no available builds.

Knowing that torch 2.6's minimum supported version is Python 3.9, our target for the migration was to do it by the torch 2.6 release date.

**Comment by atalman** [comment]
@antoniojkim @ghostplant Here is the issue tracker for deprecation of Python 3.8: https://github.com/pytorch/pytorch/issues/120718 also included in Release notes: https://github.com/pytorch/pytorch/releases/tag/v2.5.0

**Comment by malfet** [comment]
@ghostplant I'm on Ubuntu-20.04, but it has a python-3.9 as part of the distro, though it's not installed by default: https://packages.ubuntu.com/focal/python3.9
