### ISSUE TITLE
torch.full and torch.randint are inconsistent in arg order

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#14085]
`torch.full(size, fill_value, ...)` and `torch.randint(low=0, high, size, ...)` are inconsistent. `full` put `size` before parameters of the values, and `randint` put size after those. 

cc @ezyang @gchanan @mruberry @rgommers @heitorschueroff

**Comment by fmassa** [comment]
There is also one subtle difference on numpy compared to pytorch that for me makes sense: `randint` accepts not passing the `shape`, returning a scalar.

**Comment by mruberry** [comment]
@vishwakftw is correct, we want to be consistent with NumPy (which may be internally inconsistent, unfortunately).
