### ISSUE TITLE
Nightly builds missing from PyTorch cu121 repository since November 12, 2024

### ISSUE THREAD

**Issue by celestinoxp** [pytorch/pytorch#140885]
### 🐛 Describe the bug

I noticed that the [PyTorch nightly repository for cu121](https://download.pytorch.org/whl/nightly/cu121/torch/) has not been updated since November 12, 2024. The most recent file available is torch-2.6.0.dev20241112+cu121-cp39-cp39-win_amd64.whl.

Could you confirm if this is an expected delay or if there's an issue with the build pipeline?

### Versions

na

cc @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
Yes, this is expected, and result of https://github.com/pytorch/pytorch/pull/138899 
See https://github.com/pytorch/pytorch/issues/138609 : for upcoming 2.6 release, CUDA-11.8, CUDA-12.4 and CUDA-12.6 binaries will be released
