### ISSUE TITLE
[feature request] np.repeat like function

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#14093]
We have `tensor.repeat`, which is really `np.tile`. :)

It seems that it could be implemented via `expand`s + a `cat`, if `cat` doesn't contiguous-fy the inputs...

**Comment by Kaixhin** [comment]
Yep parity with numpy naming on these functions in particular would make things less confusing.

**Comment by zasdfgbnm** [comment]
numpy like repeat will be very helpful to me, please, please, please add this to pytorch :)
