### ISSUE TITLE
Not all methods from `mps/operations/MultiTensorApply.h` are covered by tests

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#140971]
### 🐛 Describe the bug

While working on https://github.com/pytorch/pytorch/pull/140896
I've accidentally deleted body of
https://github.com/pytorch/pytorch/blob/e80b1b2870ad568aebdbb7f5205f6665f843e0ea/aten/src/ATen/native/mps/operations/MultiTensorApply.h#L76-L85 (see https://github.com/pytorch/pytorch/pull/140896/commits/44c516332926e856ee5a456c20a5d6dfea0e5706#diff-13e6ddc055c896f13df4431cb5cd90f6432ac0ab32ac77d726f75a25fa470667 ), but CI turned out green.

I see three explanations for this behavior:
 - MultiTensorApply for MPS is not covered by tests
 - MTA tests are not executed during `ciflow/mps` (or TD decided to skip the test)
 - This method is not used at all by the codebase, and should be deleted

### Versions

CI

cc @mruberry @ZainRizvi @crcrpar @mcarilli @janeyx99 @kulinseth @albanD @DenisVieriu97 @jhavukainen

**Comment by malfet** [comment]
@qqaatw as an author of this thing, do you mind having a look?
Also do you know why in the same file you always casts bools to uint8s before passing them to Metal:
https://github.com/pytorch/pytorch/blob/e80b1b2870ad568aebdbb7f5205f6665f843e0ea/aten/src/ATen/native/mps/operations/MultiTensorApply.h#L33

**Comment by qqaatw** [comment]
Sure I'll take a look. The reason of casting was that I was worried about the sizes of bool in cpp & metal are misaligned. Though now I see bool takes 1 byte in MSL specs, we couldn't use static assert from cpp to confirm that, could we?

**Comment by qqaatw** [comment]
Also from your diff link, I only see a code formatting change, where the body in question is not deleted, am I missing something?

**Comment by malfet** [comment]
Thank you confirming, I guess it's a question of `test_optim.py` is not running on MPS shard
