### ISSUE TITLE
Behavior not completely documented for torch.nn.Fold()

### ISSUE THREAD

**Issue by tomahawk810** [pytorch/pytorch#14096]
## 📚 Documentation
The documentation says:
_This operation combines these local blocks into the large output tensor_ 

I believe it could be clearer, especially when the local blocks overlap in the large output tensor. In that case **the local blocks will be summed**, this would be nice to mention this **explicitly**.

I was looking for exactly that behavior and could not guess it from the doc, instead I had to come across this explanation: https://github.com/pytorch/pytorch/issues/7519

**Comment by SsnL** [comment]
Doc explicitly says
> This operation combines these local blocks into the large output tensor of shape (N, C, \text{output\_size}[0], \text{output\_size}[1], \dots)(N,C,output_size[0],output_size[1],…) by summing the overlapping values. Similar to Unfold, the arguments must satisfy ...

**Comment by tomahawk810** [comment]
Well, no it doesn't, or at least not the one I am looking at. As can be seen on that link:
https://pytorch.org/docs/stable/nn.html#torch.nn.Fold

I am copy-pasting the section you seem to refer, where I don't see "by summing the overlapping values":
>  This operation combines these local blocks into the large output tensor of shape (N,C,output_size[0],output_size[1],…). Similar to Unfold, the arguments must satisfy

Is the link above the wrong way to look for documentation on `torch.nn.Fold`?
