### ISSUE TITLE
Error reported by strict ONNX shape inference: [ShapeInferenceError] (op_type:MatMul)

### ISSUE THREAD

**Issue by CuddleSabe** [pytorch/pytorch#140925]
### 🐛 Describe the bug

/root/picasso/xxx/python3.10/site-packages/torch/onnx/utils.py:1636: UserWarning: The exported ONNX model failed ONNX shape inference.The model will not be executable by the ONNX Runtime.If this is unintended and you believe there is a bug,please report an issue at https://github.com/pytorch/pytorch/issues.Error reported by strict ONNX shape inference: [ShapeInferenceError] (op_type:MatMul, node name: /encoder_level1/encoder_level1.0/attn/MatMul_1): B has inconsistent type tensor(float16) (Triggered internally at ../torch/csrc/jit/serialization/export.cpp:1407.)
  _C._check_onnx_proto(proto)
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

and here is the code:
```
    b,c,h,w = x.shape
    qkv = self.qkv_dwconv(self.qkv(x))
    q,k,v = qkv.chunk(3, dim=1)
    if self.down_scale != 1:
        q = self.pool(q)
        k = self.pool(k)
    q = rearrange(q, 'b (head c) h w -> b head c (h w)', head=self.num_heads, h=h//self.down_scale, w=w//self.down_scale)
    k = rearrange(k, 'b (head c) h w -> b head c (h w)', head=self.num_heads, h=h//self.down_scale, w=w//self.down_scale)
    v = rearrange(v, 'b (head c) h w -> b head c (h w)', head=self.num_heads)
    q = torch.nn.functional.normalize(q, dim=-1)
    k = torch.nn.functional.normalize(k, dim=-1)
    attn = (q @ k.transpose(-2, -1)) * self.temperature
    attn = attn.softmax(dim=-1)
    out = (attn @ v)
    out = rearrange(out, 'b head c (h w) -> b (head c) h w', head=self.num_heads, h=h, w=w)
    out = self.project_out(out)
    return out
```

### Versions

torch                    2.0.1

**Comment by justinchuby** [comment]
Please test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!
