### ISSUE TITLE
When I upgraded torch to 2.3.1, [F.conv2d] performance got really bad!

### ISSUE THREAD

**Issue by MrXsc** [pytorch/pytorch#140934]
### 🐛 Describe the bug
Thx 4 watching：

When I upgraded torch to 2.3.1, conv2d performance got really bad! 
It calls on the cpu.
There is a demo:
```python
import torch
import torch.nn.functional as F

import time
filters = torch.ones(1, 1, 67, 67)
inputs = torch.randn(1, 1, 1410, 1280)
start_time_total = time.time()
for i in range(100):
    start_time = time.time()
    res = F.conv2d(inputs, filters, padding=1)
    print(f"conv2d: {time.time() - start_time} s")
print(f"----------conv2d: {(time.time() - start_time_total)/100} s")
```

average performance is  over **0.8**s，
Meanwhile, the performance on **torch==2.1.0** is just  **0.18**s

If it's not easy to reproduce the ascend env,  thanks for some ideas.

### Versions
torch 2.3.1；python 3.10.6；Ascend 910B4

cc @msaroufim @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by malfet** [comment]
@MrXsc can you elaborate where you got the binaries? (Or run `torch.utils.collect_env` and publish results here)

**Comment by malfet** [comment]
Can not reproduce it on neither x86 nor ARM cpus, and to the best of my knowledge we do not build binaries for Ascend 910B4, which likely include some code which is missing in this repository. So please file an issue against project that produces those builds. If they will get back to you with "It's a pure PyTorch build with such and such flags", please reopen this issue or create a new one.
