### ISSUE TITLE
Flex attention blocksize 

### ISSUE THREAD

**Issue by liuxin99** [pytorch/pytorch#140940]
There seems to be a bug here, if my Q_LEN < 128, then Q_BLOCK_SIZE will be Q_LEN and KV_BLOCK_SIZE will be BLOCK_SIZE, which is 128.  Am I understanding this correctly？

In pytorch 2.5.1 

https://github.com/pytorch/pytorch/blob/a8d6afb511a69687bbb2b7e88a3cf67917e1697e/torch/nn/attention/flex_attention.py#L842C8-L842C13

<img width="574" alt="image" src="https://github.com/user-attachments/assets/743c3da2-b42b-4f67-aa8c-7f056f312f52">

cc @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @yf225 @Chillee @drisspg @yanboliang @BoyuanFeng

**Comment by Chillee** [comment]
I believe we've also changed/fixed(?) this behavior on nightly, so closing this issue for now. Feel free to re-open if there's another issue here!
