### ISSUE TITLE
Runtime error when trying to swap first two axes of a four dimensional Tensor with torch.transpose.

### ISSUE THREAD

**Issue by woxuankai** [pytorch/pytorch#14098]
## 🐛 Bug

Unable to swap first two axes of a four dimensional Tensor with torch.transpose.

## To Reproduce
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.randn(5, 12, 64, 64)
>>> a.transpose(1, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kylexuan/.local/lib/python3.5/site-packages/torch/tensor.py", line 57, in __repr__
    return torch._tensor_str._str(self)
  File "/home/kylexuan/.local/lib/python3.5/site-packages/torch/_tensor_str.py", line 256, in _str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/kylexuan/.local/lib/python3.5/site-packages/torch/_tensor_str.py", line 216, in get_summarized_data
    start = [get_summarized_data(self[i]).view(-1) for i in range(0, PRINT_OPTS.edgeitems)]
  File "/home/kylexuan/.local/lib/python3.5/site-packages/torch/_tensor_str.py", line 216, in <listcomp>
    start = [get_summarized_data(self[i]).view(-1) for i in range(0, PRINT_OPTS.edgeitems)]
RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /pytorch/aten/src/TH/generic/THTensor.cpp:237
```
## Expected behavior

Tensor of shape (12, 5, 64, 64)

## Environment

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Debian GNU/Linux 9.5 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: version 3.7.2

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 384.130
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy (1.15.2)
[pip3] numpydoc (0.6.0)
[pip3] torch (0.4.1)
[pip3] torchvision (0.2.1)
[conda] Could not collect

## Additional context

None

**Comment by vishwakftw** [comment]
I could not reproduce this on master. Could you try upgrading and see if the issue persists?

**Comment by SsnL** [comment]
This is a printing issue... We fixed it on master. Sorry about it.
