### ISSUE TITLE
aten::avg_pool3d.out for the MPS

### ISSUE THREAD

**Issue by moshafieeha** [pytorch/pytorch#141044]
### 🚀 The feature, motivation and pitch

NotImplementedError: The operator 'aten::avg_pool3d.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by malfet** [comment]
Please just mention the missing op in https://github.com/pytorch/pytorch/issues/77764
