### ISSUE TITLE
fail to build for android(arm64-v8a)

### ISSUE THREAD

**Issue by My-captain** [pytorch/pytorch#141016]
### 🐛 Describe the bug

Dear PyTorch developers,

Hello. I am writing a C++ program for a vision-language large model targeted at the Android platform, which depends on libtorch. Therefore, I want to compile the libtorch library for the Android platform (arm64-v8a). 

Following the steps mentioned in the link （https://pytorch.org/mobile/android/#building-pytorch-android-from-source）, I set up the four environment variables, including JAVA_HOME. However, I encountered the following error during compilation. I am not very proficient in C++, so could someone please help me? I would be extremely grateful.

Thank you!

```shell
(aimet134) zliu@Jarvis:~/Applications/pytorch-main$ ./scripts/build_pytorch_android.sh arm64-v8a
+++ dirname ./scripts/build_pytorch_android.sh
++ cd ./scripts/..
++ pwd -P
+ PYTORCH_DIR=/home/zliu/Applications/pytorch-main
+ PYTORCH_ANDROID_DIR=/home/zliu/Applications/pytorch-main/android
+ echo PYTORCH_DIR:/home/zliu/Applications/pytorch-main
PYTORCH_DIR:/home/zliu/Applications/pytorch-main
+ source /home/zliu/Applications/pytorch-main/android/common.sh
++ set -eux
++ '[' -z /home/zliu/Applications/pytorch-main ']'
+ check_android_sdk
+ '[' -z /home/zliu/Android/Sdk ']'
+ '[' '!' -d /home/zliu/Android/Sdk ']'
+ echo ANDROID_HOME:/home/zliu/Android/Sdk
ANDROID_HOME:/home/zliu/Android/Sdk
+ check_gradle
+ GRADLE_PATH=/home/zliu/Applications/pytorch-main/android/gradlew
+ echo GRADLE_PATH:/home/zliu/Applications/pytorch-main/android/gradlew
GRADLE_PATH:/home/zliu/Applications/pytorch-main/android/gradlew
+ parse_abis_list arm64-v8a
+ ABIS_LIST=armeabi-v7a,arm64-v8a,x86,x86_64
+ CUSTOM_ABIS_LIST=false
+ '[' 1 -gt 0 ']'
+ ABIS_LIST=arm64-v8a
+ CUSTOM_ABIS_LIST=true
+ echo ABIS_LIST:arm64-v8a
ABIS_LIST:arm64-v8a
+ echo CUSTOM_ABIS_LIST:true
CUSTOM_ABIS_LIST:true
+ build_android
+ PYTORCH_ANDROID_DIR=/home/zliu/Applications/pytorch-main/android
+ BUILD_ROOT=/home/zliu/Applications/pytorch-main
+ echo BUILD_ROOT:/home/zliu/Applications/pytorch-main
BUILD_ROOT:/home/zliu/Applications/pytorch-main
+ LIB_DIR=/home/zliu/Applications/pytorch-main/android/pytorch_android/src/main/jniLibs
+ INCLUDE_DIR=/home/zliu/Applications/pytorch-main/android/pytorch_android/src/main/cpp/libtorch_include
+ rm -rf /home/zliu/Applications/pytorch-main/android/pytorch_android/src/main/jniLibs
+ mkdir -p /home/zliu/Applications/pytorch-main/android/pytorch_android/src/main/jniLibs
+ rm -rf /home/zliu/Applications/pytorch-main/android/pytorch_android/src/main/cpp/libtorch_include
+ mkdir -p /home/zliu/Applications/pytorch-main/android/pytorch_android/src/main/cpp/libtorch_include
++ echo arm64-v8a
++ tr , '\n'
+ for abi in $(echo "$ABIS_LIST" | tr ',' '\n')
+ echo abi:arm64-v8a
abi:arm64-v8a
+ ANDROID_BUILD_ROOT=/home/zliu/Applications/pytorch-main/build_android_arm64-v8a
++ which ccache
+ ANDROID_ABI=arm64-v8a
+ BUILD_ROOT=/home/zliu/Applications/pytorch-main/build_android_arm64-v8a
+ /home/zliu/Applications/pytorch-main/scripts/build_android.sh -DANDROID_CCACHE= -DUSE_LITE_INTERPRETER_PROFILER=OFF
Build with ANDROID_ABI[arm64-v8a], ANDROID_NATIVE_API_LEVEL[21]
Bash: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Python: 3.10.15 (main, Nov  6 2024, 17:05:55) [GCC 11.4.0]
Caffe2 path: /home/zliu/Applications/pytorch-main
Using Android NDK at /home/zliu/Applications/android-ndk-r26d
Android NDK version: 26
-- Could not find ccache. Consider installing ccache to speed up compilation.
CMake Warning at CMakeLists.txt:668 (message):
  INTERN_BUILD_MOBILE is on, disabling BUILD_LAZY_TS_BACKEND


-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- Compiler does not support SVE extension. Will not build perfkernels.
-- Trying to find preferred BLAS backend of choice: Eigen
-- Using pocketfft in directory: /home/zliu/Applications/pytorch-main/third_party/pocketfft/
CMake Error at cmake/Dependencies.cmake:399 (add_subdirectory):
  The source directory

    /home/zliu/Applications/pytorch-main/third_party/pthreadpool

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:859 (include)


CMake Error at cmake/Dependencies.cmake:402 (set_property):
  set_property could not find TARGET pthreadpool.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  CMakeLists.txt:859 (include)


CMake Error at cmake/Dependencies.cmake:440 (add_subdirectory):
  The source directory

    /home/zliu/Applications/pytorch-main/third_party/cpuinfo

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:859 (include)


CMake Error at cmake/Dependencies.cmake:445 (set_property):
  set_property could not find TARGET cpuinfo.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:859 (include)


CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:351 (add_subdirectory):
  The binary directory

    /home/zliu/Applications/pytorch-main/build_android_arm64-v8a/confu-deps/cpuinfo

  is already used to build a source directory.  It cannot be used to build
  source directory

    /home/zliu/Applications/pytorch-main/third_party/cpuinfo

  Specify a unique binary directory name.


CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:361 (add_subdirectory):
  The binary directory

    /home/zliu/Applications/pytorch-main/build_android_arm64-v8a/confu-deps/pthreadpool

  is already used to build a source directory.  It cannot be used to build
  source directory

    /home/zliu/Applications/pytorch-main/third_party/pthreadpool

  Specify a unique binary directory name.


CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:381 (add_subdirectory):
  The source directory

    /home/zliu/Applications/pytorch-main/third_party/FXdiv

  does not contain a CMakeLists.txt file.


CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:396 (add_subdirectory):
  The source directory

    /home/zliu/Applications/pytorch-main/third_party/psimd

  does not contain a CMakeLists.txt file.


CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:413 (add_subdirectory):
  The source directory

    /home/zliu/Applications/pytorch-main/third_party/FP16

  does not contain a CMakeLists.txt file.


CMake Error at cmake/Dependencies.cmake:468 (set_property):
  set_property could not find TARGET cpuinfo.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:859 (include)


-- Brace yourself, we are building NNPACK
CMake Error at cmake/External/nnpack.cmake:65 (add_subdirectory):
  The source directory

    /home/zliu/Applications/pytorch-main/third_party/NNPACK

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:478 (include)
  CMakeLists.txt:859 (include)


CMake Error at cmake/External/nnpack.cmake:70 (set_property):
  set_property could not find TARGET nnpack.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:478 (include)
  CMakeLists.txt:859 (include)


CMake Error at cmake/External/nnpack.cmake:71 (set_property):
  set_property could not find TARGET pthreadpool.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:478 (include)
  CMakeLists.txt:859 (include)


CMake Error at cmake/External/nnpack.cmake:72 (set_property):
  set_property could not find TARGET cpuinfo.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:478 (include)
  CMakeLists.txt:859 (include)


CMake Error at cmake/Dependencies.cmake:542 (add_subdirectory):
  The source directory

    /home/zliu/Applications/pytorch-main/third_party/XNNPACK

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:859 (include)


-- VULKAN_INCLUDE_DIR:/home/zliu/Applications/android-ndk-r26d/sources/third_party/vulkan/src/include
-- Vulkan_ANDROID_NDK_WRAPPER_DIR:/home/zliu/Applications/android-ndk-r26d/sources/third_party/vulkan/src/common
CMake Warning at cmake/Dependencies.cmake:746 (message):
  Turning USE_FAKELOWP off as it depends on USE_FBGEMM.
Call Stack (most recent call first):
  CMakeLists.txt:859 (include)


CMake Error at cmake/Dependencies.cmake:798 (add_subdirectory):
  The source directory

    /home/zliu/Applications/pytorch-main/third_party/FP16

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:859 (include)


-- Using third party subdirectory Eigen.
-- Using third_party/pybind11.
-- pybind11 include dirs: /home/zliu/Applications/pytorch-main/cmake/../third_party/pybind11/include
-- Could NOT find OpenTelemetryApi (missing: OpenTelemetryApi_INCLUDE_DIRS) 
-- Using third_party/opentelemetry-cpp.
-- opentelemetry api include dirs: /home/zliu/Applications/pytorch-main/cmake/../third_party/opentelemetry-cpp/api/include
CMake Error at cmake/Dependencies.cmake:1536 (add_subdirectory):
  The source directory

    /home/zliu/Applications/pytorch-main/third_party/fmt

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:859 (include)


CMake Error at cmake/Dependencies.cmake:1545 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  fmt-header-only
Call Stack (most recent call first):
  CMakeLists.txt:859 (include)


-- Not using libkineto in a mobile build.
-- don't use NUMA
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY) 
-- headers outputs: 
-- sources outputs: 
-- declarations_yaml outputs: 
CMake Warning (dev) at cmake/VulkanCodegen.cmake:42 (set):
  Only the first value argument is used when setting an environment variable.
  Argument '/home/zliu/Applications/pytorch-main/cmake/..' and later are
  unused.
Call Stack (most recent call first):
  caffe2/CMakeLists.txt:6 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

glslc cmd: ['/home/zliu/Applications/android-ndk-r26d/shader-tools/linux-x86_64/glslc', '-fshader-stage=compute', '/home/zliu/Applications/pytorch-main/build_android_arm64-v8a/vulkan/spv/add_scalar.glsl', '-o', '/home/zliu/Applications/pytorch-main/build_android_arm64-v8a/vulkan/spv/add_scalar.spv', '--target-env=vulkan1.0', '-Werror', '-I', '/home/zliu/Applications/pytorch-main/cmake/../aten/src/ATen/native/vulkan/glsl']
// cut for too long
glslc cmd: ['/home/zliu/Applications/android-ndk-r26d/shader-tools/linux-x86_64/glslc', '-fshader-stage=compute', '/home/zliu/Applications/pytorch-main/build_android_arm64-v8a/vulkan/spv/hardswish_.glsl', '-o', '/home/zliu/Applications/pytorch-main/build_android_arm64-v8a/vulkan/spv/hardswish_.spv', '--target-env=vulkan1.0', '-Werror', '-I', '/home/zliu/Applications/pytorch-main/cmake/../aten/src/ATen/native/vulkan/glsl']
-- Using ATen parallel backend: NATIVE
disabling CUDA because USE_CUDA is set false
AT_INSTALL_INCLUDE_DIR include/ATen/core
core header install: /home/zliu/Applications/pytorch-main/build_android_arm64-v8a/aten/src/ATen/core/TensorBody.h
core header install: /home/zliu/Applications/pytorch-main/build_android_arm64-v8a/aten/src/ATen/core/aten_interned_strings.h
core header install: /home/zliu/Applications/pytorch-main/build_android_arm64-v8a/aten/src/ATen/core/enum_tag.h
disable aten test when BUILD_LITE_INTERPRETER is enabled
CMake Error at caffe2/CMakeLists.txt:94 (add_subdirectory):
  The source directory

    /home/zliu/Applications/pytorch-main/third_party/FXdiv

  does not contain a CMakeLists.txt file.


CMake Warning at CMakeLists.txt:1280 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.  Other settings may generate files that are not well
  tested.


CMake Warning at CMakeLists.txt:1344 (message):
  Generated cmake files are only available when building shared libs.


-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.22.1
--   CMake command         : /usr/bin/cmake
--   System                : Android
--   C++ compiler          : /home/zliu/Applications/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
--   C++ compiler id       : Clang
--   C++ compiler version  : 17.0.2
--   Using ccache if found : ON
--   Found ccache          : CCACHE_PROGRAM-NOTFOUND
--   CXX flags             : -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -frtti -fexceptions  -ffunction-sections -fdata-sections -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DUSE_VULKAN_WRAPPER -DUSE_X86_SIMD_SORT -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN -DUSE_VULKAN_API -DBUILD_LITE_INTERPRETER -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=braced-scalar-init -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-strict-overflow -Wno-strict-aliasing -Wvla-extension -Wsuggest-override -Wnewline-eof -Winconsistent-missing-override -Winconsistent-missing-destructor-override -Wno-pass-failed -Wno-error=old-style-cast -Wconstant-conversion -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -faligned-new -Wno-unused-but-set-variable -fno-math-errno -fno-trapping-math -Werror=format -g0
--   Shared LD flags       : -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments  -rdynamic
--   Static LD flags       : 
--   Module LD flags       : -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments 
--   Build type            : Release
--   Compile definitions   : FLASHATTENTION_DISABLE_ALIBI
--   CMAKE_PREFIX_PATH     : /home/zliu/.venvs/aimet134/lib/python3.10/site-packages;/home/zliu/Applications/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64
--   CMAKE_INSTALL_PREFIX  : /home/zliu/Applications/pytorch-main/build_android_arm64-v8a/install
--   USE_GOLD_LINKER       : OFF
-- 
--   TORCH_VERSION         : 2.6.0
--   BUILD_STATIC_RUNTIME_BENCHMARK: OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : OFF
--     Protobuf compiler   : 
--     Protobuf includes   : 
--     Protobuf libraries  : 
--   BUILD_PYTHON          : OFF
--   BUILD_SHARED_LIBS     : OFF
--   CAFFE2_USE_MSVC_STATIC_RUNTIME     : ON
--   BUILD_TEST            : OFF
--   BUILD_JNI             : OFF
--   BUILD_MOBILE_AUTOGRAD : OFF
--   BUILD_LITE_INTERPRETER: ON
--   INTERN_BUILD_MOBILE   : ON
--   TRACING_BASED         : OFF
--   USE_BLAS              : 1
--     BLAS                : 
--     BLAS_HAS_SBGEMM     : 
--   USE_LAPACK            : 0
--   USE_ASAN              : OFF
--   USE_TSAN              : OFF
--   USE_CPP_CODE_COVERAGE : OFF
--   USE_CUDA              : OFF
--   USE_XPU               : OFF
--   USE_ROCM              : OFF
--   BUILD_NVFUSER         : 
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_X86_SIMD_SORT     : ON
--   USE_FBGEMM            : OFF
--     USE_FAKELOWP          : OFF
--   USE_KINETO            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LITE_PROTO        : OFF
--   USE_PYTORCH_METAL     : OFF
--   USE_PYTORCH_METAL_EXPORT     : OFF
--   USE_MPS               : OFF
--   CAN_COMPILE_METAL     : 
--   USE_MKL               : 
--   USE_MKLDNN            : OFF
--   USE_UCC               : OFF
--   USE_ITT               : OFF
--   USE_NCCL              : OFF
--   USE_NNPACK            : ON
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : OFF
--   USE_OPENCL            : OFF
--   USE_OPENMP            : OFF
--   USE_MIMALLOC          : OFF
--   USE_VULKAN            : ON
--     USE_VULKAN_FP16_INFERENCE    : OFF
--     USE_VULKAN_RELAXED_PRECISION : OFF
--   USE_PROF              : OFF
--   USE_PYTORCH_QNNPACK   : ON
--   USE_XNNPACK           : ON
--   USE_DISTRIBUTED       : OFF
--   Public Dependencies  : 
--   Private Dependencies : Threads::Threads;eigen_blas;pthreadpool;cpuinfo;pytorch_qnnpack;XNNPACK;VulkanWrapper;fp16;log;fmt::fmt-header-only;dl
--   Public CUDA Deps.    : 
--   Private CUDA Deps.   : 
--   USE_COREML_DELEGATE     : OFF
--   BUILD_LAZY_TS_BACKEND   : OFF
--   USE_ROCM_KERNEL_ASSERT : OFF
-- Configuring incomplete, errors occurred!
See also "/home/zliu/Applications/pytorch-main/build_android_arm64-v8a/CMakeFiles/CMakeOutput.log".
See also "/home/zliu/Applications/pytorch-main/build_android_arm64-v8a/CMakeFiles/CMakeError.log".

```

### Versions

os：ubuntu22.04

**Comment by malfet** [comment]
Please note that PyTorch mobile support is deprecated/in-maintenance mode. Have you tried ExecuTorch?

**Comment by My-captain** [comment]
Hi, malfet! Thanks for your reply.
The above errors were due to my overlooking the third-party dependency libraries when using `git clone`. After struggling for two days, I successfully compiled PyTorch v2.5.1 into a static library targeting arm64-v8a. However, when I tried to build my own C++ project using ndk-build, various strange errors still occurred. Anyway, thank you very much for your response.

**Comment by fiberflow** [comment]
> Please note that PyTorch mobile support is deprecated/in-maintenance mode. Have you tried ExecuTorch?

ExecuTorch, in its current state, feels incomplete and immature as software. It suffers from a variety of issues that hinder its usability and reliability across different platforms. Below are some key concerns:

- Portability Issues
    Despite claims of portability, ExecuTorch heavily relies on GCC-specific extensions, which makes it incompatible with certain platforms, such as Windows, where it cannot be compiled. This contradicts the stated goal of being a portable solution. A truly portable system should avoid platform-specific dependencies or provide clear workarounds for unsupported environments.

- Missing Features
    ExecuTorch lacks support for several fundamental operators. For instance, it does not include even basic functionality like FFT (Fast Fourier Transform), which is critical for many machine learning applications. Missing such essential features significantly limits its utility for developers.

- Poor Documentation
    The documentation fails to address critical pitfalls that users may encounter, which can lead to frustrating runtime issues. For example:
        The model buffer must be 16-byte aligned—an important requirement that is not clearly mentioned in the documentation. This can result in segmentation faults when running on actual devices.
        The file data loader uses mlock, which may fail on older devices with limited memory, causing unexpected errors that are difficult to debug.

- Lack of Threading Support
    ExecuTorch does not internally support threading, leading to higher latency. This makes it less suitable for applications requiring low-latency inference, especially when compared to other frameworks that prioritize multi-threaded execution.

- Backend-Specific Models
    Models in ExecuTorch are backend-specific, meaning developers must maintain multiple copies of the same model for different targets. This creates unnecessary overhead and complexity for users who are trying to deploy models on multiple platforms.

- No Support for Data-Dependent Flow
    One of the core reasons for PyTorch's popularity is its dynamic nature and support for data-dependent control flow. However, ExecuTorch does not support data-dependent flows, which undermines one of the key advantages of the PyTorch ecosystem. This limitation makes it less appealing for scenarios where flexibility is required.

- "[Data-Dependent Shape Puzzles](https://github.com/ezyang/data-dependent-shape-puzzles)"
    The existence of tools like Data-Dependent Shape Puzzles highlights the complexity of handling models with data-dependent shapes in ExecuTorch. While such puzzles may serve as a learning opportunity, they expose a deeper issue: converting models should be straightforward and intuitive, not a convoluted process that forces users to solve puzzles. This detracts from the user experience and creates unnecessary barriers to adoption.

- Issues with PyTorch Mobile
    While not directly related to ExecuTorch, PyTorch Mobile appears to suffer from deliberate limitations that restrict its usability. Even simple models like MobileNet or ResNet often produce incorrect results or encounter segmentation faults when running custom models. Developers are left questioning whether PyTorch Mobile is intentionally designed to be frustrating, as it fails in areas where lightweight frameworks like TensorFlow Lite excel.

- Pre-Alpha Stability
    Overall, ExecuTorch feels more like a pre-alpha release rather than a production-ready technology. Encouraging developers to adopt it at this stage is premature and may result in wasted time addressing fundamental issues. Users face constant roadblocks, from missing features to platform-specific errors, making it difficult to justify its use in real-world projects.

**Comment by My-captain** [comment]
> > Please note that PyTorch mobile support is deprecated/in-maintenance mode. Have you tried ExecuTorch?
> 
> ExecuTorch, in its current state, feels incomplete and immature as software. It suffers from a variety of issues that hinder its usability and reliability across different platforms. Below are some key concerns:
> 
> * Portability Issues
>   Despite claims of portability, ExecuTorch heavily relies on GCC-specific extensions, which makes it incompatible with certain platforms, such as Windows, where it cannot be compiled. This contradicts the stated goal of being a portable solution. A truly portable system should avoid platform-specific dependencies or provide clear workarounds for unsupported environments.
> * Missing Features
>   ExecuTorch lacks support for several fundamental operators. For instance, it does not include even basic functionality like FFT (Fast Fourier Transform), which is critical for many machine learning applications. Missing such essential features significantly limits its utility for developers.
> * Poor Documentation
>   The documentation fails to address critical pitfalls that users may encounter, which can lead to frustrating runtime issues. For example:
>   The model buffer must be 16-byte aligned—an important requirement that is not clearly mentioned in the documentation. This can result in segmentation faults when running on actual devices.
>   The file data loader uses mlock, which may fail on older devices with limited memory, causing unexpected errors that are difficult to debug.
> * Lack of Threading Support
>   ExecuTorch does not internally support threading, leading to higher latency. This makes it less suitable for applications requiring low-latency inference, especially when compared to other frameworks that prioritize multi-threaded execution.
> * Backend-Specific Models
>   Models in ExecuTorch are backend-specific, meaning developers must maintain multiple copies of the same model for different targets. This creates unnecessary overhead and complexity for users who are trying to deploy models on multiple platforms.
> * No Support for Data-Dependent Flow
>   One of the core reasons for PyTorch's popularity is its dynamic nature and support for data-dependent control flow. However, ExecuTorch does not support data-dependent flows, which undermines one of the key advantages of the PyTorch ecosystem. This limitation makes it less appealing for scenarios where flexibility is required.
> * "[Data-Dependent Shape Puzzles](https://github.com/ezyang/data-dependent-shape-puzzles)"
>   The existence of tools like Data-Dependent Shape Puzzles highlights the complexity of handling models with data-dependent shapes in ExecuTorch. While such puzzles may serve as a learning opportunity, they expose a deeper issue: converting models should be straightforward and intuitive, not a convoluted process that forces users to solve puzzles. This detracts from the user experience and creates unnecessary barriers to adoption.
> * Issues with PyTorch Mobile
>   While not directly related to ExecuTorch, PyTorch Mobile appears to suffer from deliberate limitations that restrict its usability. Even simple models like MobileNet or ResNet often produce incorrect results or encounter segmentation faults when running custom models. Developers are left questioning whether PyTorch Mobile is intentionally designed to be frustrating, as it fails in areas where lightweight frameworks like TensorFlow Lite excel.
> * Pre-Alpha Stability
>   Overall, ExecuTorch feels more like a pre-alpha release rather than a production-ready technology. Encouraging developers to adopt it at this stage is premature and may result in wasted time addressing fundamental issues. Users face constant roadblocks, from missing features to platform-specific errors, making it difficult to justify its use in real-world projects.

yes，failed in execuTorch too. Lots of ops missed in portable.
