### ISSUE TITLE
`torch.distributed.barrier(group)` hangs with multiple nodes when using `torch==2.2.0` or later

### ISSUE THREAD

**Issue by yyl9510** [pytorch/pytorch#141020]
### 🐛 Describe the bug

# Bug Report: `torch.distributed.barrier(group)` hangs with multiple nodes when using `torch==2.2.0` or later

## Environment Setup

1. **Create a Conda environment:**
    ```bash
    conda create -n pytest python=3.10.15 -y
    source activate pytest
    ```

2. **Install required packages:**
    ```bash
    pip install torch==2.2.0
    pip install numpy==1.23.0  # This is only to remove warnings
    ```

## Test Script

Add the following content to a file named `test_torchrun.py`:

```python
import os
import torch
import torch.distributed as dist

def distributed_init(rank, local_rank, world_size):
    dist.init_process_group('nccl', init_method='env://', rank=rank, world_size=world_size)
    
    if torch.cuda.is_available():
        torch.cuda.set_device(local_rank)
        dist.all_reduce(torch.zeros(1).cuda())

def distributed_main(rank, local_rank, world_size):
    distributed_init(rank, local_rank, world_size)
    tmp_ranks = list(range(world_size))
    tmp_group = dist.new_group(tmp_ranks)
    dist.barrier(tmp_group)

if __name__ == "__main__":
    world_size = int(os.environ['WORLD_SIZE'])
    rank = int(os.environ['RANK'])
    local_rank = int(os.environ['LOCAL_RANK'])
    print("rank: ", rank, "local_rank: ", local_rank, "world_size: ", world_size)
    distributed_main(rank, local_rank, world_size)
```

## Running the Script

Run the script on two nodes:
    ```
    torchrun --nnodes=2 --nproc-per-node=1 --master-addr=<first-node-ip> --node_rank=<node-rank> test_torchrun.py
    ```

## Issue Description

The script hangs at `dist.barrier(tmp_group)`. The `tmp_group` represents a group containing all cards, making it equivalent to `dist.barrier()`. However, while `dist.barrier()` does not hang, `dist.barrier(tmp_group)` does, causing the second card of the second node to be incorrectly barriered.

## Observations

- If any distributed communication (e.g. `torch.all_reduce`) occurs before `dist.barrier(group)`, `dist.barrier(group)` will hang.
- Setting env `CUDA_VISIBLE_DEVICES=0` or just `dist.barrier()` without group in each node get around this bug.
- The issue occurs with `torch>=2.2.0` and not occur with `torch<=2.1.2`. So it appears to have been introduced in `torch 2.2.0`.

### Versions

Versions
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Libc version: glibc-2.35

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by kwen2501** [comment]
I just tried nightly (or main). The hang cannot reproduce. Maybe the easiest way would be to upgrade your torch version.
Between 2.2 and now, we did fix a couple bugs around barrier.

**Comment by yyl9510** [comment]
I have tried torch nightly version torch==2.6.0.dev20241112+cu121, this bug has been fixed, thanks.
