### ISSUE TITLE
torch._dynamo.exc.Unsupported: skip function is_dataclass

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#141158]
Example error message: https://gist.github.com/zou3519/4e4a4dfa62aa2ae3de36d876cfe73748
Repro:
```py
import torch
import dataclasses

def f(x):
    if dataclasses.is_dataclass(x):
        return x
    return x.sin()

x = torch.randn(3)
torch.compile(f, fullgraph=True)(x)
```

Side note: we should probably do a pass to make builtin_skiplist more fine-grained. We want to skip a lot of things, but there are a lot of things that we should just be able to inline.

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by StrongerXi** [comment]
Closed by #141294
