### ISSUE TITLE
conda downloads from cuda75 channel

### ISSUE THREAD

**Issue by 0entr0py** [pytorch/pytorch#1411]
I am using pytorch with CUDA 8.0  

When I run `conda install -c soumith pytorch`  the downloaded package is `0.1.12-py35_1cu75 soumith` instead of the cu80 version. I have to download and install locally to get the correct version. 

What is way to get the correct version using the conda command ?

**Comment by soumith** [comment]
if you go to pytorch.org and choose cuda 8.0 in the selector, then it'll show you the conda command to execute to get the cuda 8.0 version
