### ISSUE TITLE
[FlexAttention] Wrong results for simple block-sparse mask

### ISSUE THREAD

**Issue by alexdremov** [pytorch/pytorch#141126]
### 🐛 Describe the bug

Bellow is full reproduce code, I get quite high error. The mask in question is block-context like this (left context will be limited at some point)

![urCeflhA3-42SOI-To7J0](https://github.com/user-attachments/assets/1ad98fd7-e67c-44e3-b90e-fe1b27ac009f)

I do an assert between the reference mask and flex attention mask to make sure that I implemented block mask correctly.

```
Mismatched elements: 369638 / 1048576 (35.3%)
Greatest absolute difference: 2.760780096054077 at index (13, 23, 477) (up to 1e-05 allowed)
Greatest relative difference: 41235.46484375 at index (28, 23, 41) (up to 1.3e-06 allowed)
```

```python
import torch
import os
import einops
import functools
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.attention.flex_attention import (
    flex_attention,
    create_block_mask,
    create_mask,
    _round_up_to_multiple as round_up_to_multiple
)

torch.random.manual_seed(42)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.allow_tf32 = False
torch.backends.cuda.matmul.allow_tf32 = False
torch.use_deterministic_algorithms(True, warn_only=True)
torch.set_float32_matmul_precision('highest')
os.environ['CUBLAS_WORKSPACE_CONFIG'] = ":4096:8"

class MHA(nn.Module):
    def __init__(self, hid=64, nheads=4, use_flex=False):
        super().__init__()
        self.proj = nn.Linear(
            hid,
            3 * hid
        )
        self.out_proj = nn.Linear(
            hid,
            hid
        )

        self.hid = hid
        self.nheads = nheads
        self.head_dim = hid // nheads
        assert hid % nheads == 0

        self.use_flex = use_flex
        self.scaling = 1 / (self.head_dim ** 0.5)

    def forward(self, x, attn_mask):
        q, k, v = self.proj(x).chunk(3, -1)
        pattern = "b t (n h) -> b n t h"
        q = einops.rearrange(
            x,
            pattern,
            n=self.nheads,
            h=self.head_dim,
        )
        k = einops.rearrange(
            x,
            pattern,
            n=self.nheads,
            h=self.head_dim,
        )
        v = einops.rearrange(
            x,
            pattern,
            n=self.nheads,
            h=self.head_dim,
        )

        if self.use_flex:
            x = flex_attention(q, k, v, block_mask=attn_mask, scale=self.scaling,)
        else:
            x = F.scaled_dot_product_attention(
                q,
                k,
                v,
                attn_mask=attn_mask.unsqueeze(1),
                scale=self.scaling,
            )
        x = einops.rearrange(
            x,
            "b n t h -> t b (n h)",
            n=self.nheads,
            h=self.head_dim,
        )
        return self.out_proj(x)


def _flex_attention_chunked_mask_generator(b, h, q_idx, kv_idx, block_size, left_context_blocks_count, input_lengths):
    q_block_idxes = torch.div(q_idx, block_size, rounding_mode="floor")
    kv_block_idxes = torch.div(kv_idx, block_size, rounding_mode="floor")
    diff = q_block_idxes - kv_block_idxes

    blocks = (diff >= 0) & (diff < left_context_blocks_count)
    if input_lengths is None:
        return blocks

    padding_condition = (q_idx < input_lengths[b]) & (kv_idx < input_lengths[b])
    return blocks & padding_condition


def lengths_to_flex_attn_mask(
    input_lengths: torch.Tensor,
    block_context: tuple[int, int],
    device,
    max_time: int | None = None,
):
    left_context, right_context = block_context
    block_size = (right_context + 1)
    left_context = left_context
    assert left_context % block_size == 0
    left_context_blocks_count = left_context // block_size

    if max_time is None:
        assert input_lengths is not None
        max_time = torch.max(input_lengths).item()

    sparse_block_size = block_size
    sparse_block_size = round_up_to_multiple(sparse_block_size, 128)
    max_time = round_up_to_multiple(max_time, sparse_block_size)

    block_mask = create_block_mask(
        functools.partial(
            _flex_attention_chunked_mask_generator,
            block_size=torch.as_tensor(block_size, device=device),
            left_context_blocks_count=torch.as_tensor(left_context_blocks_count, device=device),
            input_lengths=torch.as_tensor(input_lengths, device=device) if input_lengths is not None else None,
        ),
        device=device,
        B=len(input_lengths) if input_lengths is not None else None,
        H=None,  # invariant
        Q_LEN=max_time,
        KV_LEN=max_time,
        BLOCK_SIZE=sparse_block_size,  # this is crucial to have full blocks
    )
    return block_mask


def lengths_to_attn_mask(
    input_lengths: torch.Tensor,
    block_context: tuple[int, int],
    device,
    max_time: int | None = None,
):
    if device is None:
        device = input_lengths.device

    if max_time is None:
        max_time = torch.max(input_lengths).item()

    left_context, right_context = block_context
    block_size = (right_context + 1)
    left_context = left_context
    assert left_context % block_size == 0
    left_context_blocks_count = left_context // block_size

    block_idxes = torch.div(torch.arange(max_time), block_size, rounding_mode="floor")
    block_idxes_diff = block_idxes.unsqueeze(1) - block_idxes.unsqueeze(0)
    attn_mask = (block_idxes_diff >= 0) & (block_idxes_diff < left_context_blocks_count)
    attn_mask = ~attn_mask
    key_padding_mask = (torch.arange(T).unsqueeze(0) >= input_lengths.unsqueeze(-1)).unsqueeze(-1)
    return ~(attn_mask.unsqueeze(0) | (key_padding_mask | key_padding_mask.transpose(-1, -2)))

heads = 8
B, T, features = 32, 64, 64 * heads

x = torch.randn(B, T, features)
input_lengths = torch.tensor([64, 47, 35, 31, 36,  3, 35, 18,  5, 49, 51, 16, 31, 58, 16, 11, 21, 10,
        44, 61,  1,  6, 34, 36, 40, 41, 59,  2, 58, 21,  5,  4])
max_time = x.size(1)
block_context = (90, 9)

flex_mask = lengths_to_flex_attn_mask(
    input_lengths=input_lengths,
    block_context=block_context,
    device='cuda',
    max_time=max_time,
)
mask_mod = flex_mask.mask_mod
flex_mask_dense = create_mask(mask_mod, B=B, H=None, Q_LEN=max_time, KV_LEN=max_time, device='cuda').squeeze(1).long().cpu()

regular_mask = lengths_to_attn_mask(
    input_lengths=input_lengths,
    block_context=block_context,
    device='cpu',
    max_time=max_time,
)

torch.testing.assert_close(
    regular_mask.long(),
    flex_mask_dense
)
default_model = MHA(
    hid=features,
    nheads=heads,
    use_flex=False
).eval().cpu()

flex_model = MHA(
    hid=features,
    nheads=heads,
    use_flex=True
).eval().cuda()
flex_model.load_state_dict(default_model.state_dict())

torch.testing.assert_close(
    actual=default_model(x, attn_mask=regular_mask).cuda(),
    expected=flex_model(x.cuda(), attn_mask=flex_mask)
)

torch.testing.assert_close(
    actual=default_model(x, attn_mask=regular_mask).cuda(),
    expected=torch.compile(flex_model)(x.cuda(), attn_mask=flex_mask)
)

```

### Versions

PyTorch version: 2.5.0
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.11.10 (main, Sep  7 2024, 18:35:41) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.210-39.1-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB
GPU 2: NVIDIA A800-SXM4-80GB
GPU 3: NVIDIA A800-SXM4-80GB
GPU 4: NVIDIA A800-SXM4-80GB
GPU 5: NVIDIA A800-SXM4-80GB
GPU 6: NVIDIA A800-SXM4-80GB
GPU 7: NVIDIA A800-SXM4-80GB

Nvidia driver version: 550.54.14
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          120
On-line CPU(s) list:             0-119
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7662 64-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       120
Stepping:                        0
BogoMIPS:                        3992.18
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr wbnoinvd arat npt nrip_save umip rdpid arch_capabilities
Virtualization:                  AMD-V
L1d cache:                       7.5 MiB (120 instances)
L1i cache:                       7.5 MiB (120 instances)
L2 cache:                        60 MiB (120 instances)
L3 cache:                        1.9 GiB (120 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-29
NUMA node1 CPU(s):               30-59
NUMA node2 CPU(s):               60-89
NUMA node3 CPU(s):               90-119
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.5.0
[pip3] torch-tb-profiler==0.4.3
[pip3] triton==3.1.0
[conda] Could not collect

cc @crcrpar @mcarilli @janeyx99 @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @yf225 @Chillee @drisspg @yanboliang @BoyuanFeng

**Comment by drisspg** [comment]
Just ran you repro script on main + newish triton version and all asserts pass for me. Can you try using a nighlty version of pytorch

**Comment by alexdremov** [comment]
> Just ran you repro script on main + newish triton version and all asserts pass for me. Can you try using a nighlty version of pytorch

Which triton version are you using? (aka nightly, main branch from sources or pypi stable)?

**Comment by drisspg** [comment]
Actually nvm thats just noise, fresh install with 
` pip install -U --pre torch --index-url https://download.pytorch.org/whl/nightly/cu124 `
and then running your script all tests pass

**Comment by alexdremov** [comment]
> pip install -U --pre torch --index-url https://download.pytorch.org/whl/nightly/cu124

Yes, can confirm that this is not reproducible on nightly build. Related issue with low speed is reproducible.

**Comment by drisspg** [comment]
Sounds good. I'm going to close this one and leave open the performance one.

**Comment by alexdremov** [comment]
Sure, I'll reopen if could reproduce with different hyperparams
