### ISSUE TITLE
torch.var doesn't wrap unbiased flag

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#1412]
The `unbiased` flag is currently implemented in [`autograd`](https://github.com/pytorch/pytorch/blob/master/torch/autograd/variable.py#L489) and in both [`TH`](https://github.com/pytorch/pytorch/blob/master/torch/lib/TH/generic/THTensorMath.c#L2811) and [`THC`](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/generic/THCTensorMathReduce.cu#L95), but it's not exposed to [pytorch](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/methods/TensorMath.cwrap#L499).
Maybe it would be good to expose it there as well? Note though that the meaning of the flag is inversed in TH / THC compared to autograd.

**Comment by lantiga** [comment]
I'll take this one, if nobody's on it.

**Comment by soumith** [comment]
go for it.
