### ISSUE TITLE
[inductor][cpu] amp/amp_fp16 performance regression in 2024-11-18 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#141222]
### 🐛 Describe the bug

<p>amp static shape cpp wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>shufflenet_v2_x1_0</td>
      <td>multiple</td>
      <td>64</td>
      <td>2.537466</td>
      <td>0.010730228999999999</td>
      <td>0.027227591259714</td>
      <td>17.470544</td>
      <td>64</td>
      <td>2.876879</td>
      <td>0.009069634</td>
      <td>0.026092239592286</td>
      <td>17.572227</td>
      <td>0.88</td>
      <td>0.96</td>
      <td>0.85</td>
      <td>1.01</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>Super_SloMo</td>
      <td>multiple</td>
      <td>6</td>
      <td>1.032684</td>
      <td>0.229767659</td>
      <td>0.237277385166756</td>
      <td>27.019539</td>
      <td>6</td>
      <td>1.194091</td>
      <td>0.199764877</td>
      <td>0.23853744174180702</td>
      <td>27.207285</td>
      <td>0.86</td>
      <td>1.01</td>
      <td>0.87</td>
      <td>1.01</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>shufflenet_v2_x1_0</td>
      <td>single</td>
      <td>1</td>
      <td>3.166121</td>
      <td>0.003873212</td>
      <td>0.012263057850652</td>
      <td>16.222689</td>
      <td>1</td>
      <td>3.601001</td>
      <td>0.003419612</td>
      <td>0.012314026231612</td>
      <td>16.244421</td>
      <td>0.88</td>
      <td>1.0</td>
      <td>0.88</td>
      <td>1.0</td>
    </tr>
  </tbody>

</table>

<p>amp dynamic shape cpp wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>shufflenet_v2_x1_0</td>
      <td>single</td>
      <td>1</td>
      <td>3.158312</td>
      <td>0.003915195</td>
      <td>0.01236540735084</td>
      <td>16.153606</td>
      <td>1</td>
      <td>3.620155</td>
      <td>0.0034262109999999998</td>
      <td>0.012403414882704999</td>
      <td>16.179824</td>
      <td>0.87</td>
      <td>1.0</td>
      <td>0.88</td>
      <td>1.0</td>
    </tr>
  </tbody>

</table>

<p>amp_fp16 static shape cpp wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>shufflenet_v2_x1_0</td>
      <td>multiple</td>
      <td>64</td>
      <td>2.648366</td>
      <td>0.02387262</td>
      <td>0.06322343513892001</td>
      <td>59.549544</td>
      <td>64</td>
      <td>2.966687</td>
      <td>0.0206696</td>
      <td>0.0613202336152</td>
      <td>60.026376</td>
      <td>0.89</td>
      <td>0.97</td>
      <td>0.87</td>
      <td>1.01</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_gcn</td>
      <td>single</td>
      <td>1</td>
      <td>1.837054</td>
      <td>0.047721980000000004</td>
      <td>0.08766785424692</td>
      <td>78.320497</td>
      <td>1</td>
      <td>2.230323</td>
      <td>0.04047754</td>
      <td>0.09027798844542</td>
      <td>79.910189</td>
      <td>0.82</td>
      <td>1.03</td>
      <td>0.85</td>
      <td>1.02</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>Background_Matting</td>
      <td>single</td>
      <td>1</td>
      <td>1.709493</td>
      <td>3.19020124</td>
      <td>5.45362668837132</td>
      <td>47.723786</td>
      <td>1</td>
      <td>2.014685</td>
      <td>2.72976672</td>
      <td>5.4996200642832</td>
      <td>46.431005</td>
      <td>0.85</td>
      <td>1.01</td>
      <td>0.86</td>
      <td>0.97</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>doctr_det_predictor</td>
      <td>single</td>
      <td>1</td>
      <td>4.086563</td>
      <td>0.95522034</td>
      <td>3.90356809829142</td>
      <td>64.725399</td>
      <td>1</td>
      <td>4.464748</td>
      <td>0.85025308</td>
      <td>3.79616573842384</td>
      <td>66.383939</td>
      <td>0.92</td>
      <td>0.97</td>
      <td>0.89</td>
      <td>1.03</td>
    </tr>
  </tbody>

</table>

<p>amp_fp16 dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_gcn</td>
      <td>multiple</td>
      <td>1</td>
      <td>1.12969</td>
      <td>0.010413157999999999</td>
      <td>0.011763640461019999</td>
      <td>32.021382</td>
      <td>1</td>
      <td>1.146111</td>
      <td>0.009186986</td>
      <td>0.010529305711446</td>
      <td>32.220003</td>
      <td>0.99</td>
      <td>0.9</td>
      <td>0.88</td>
      <td>1.01</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>shufflenet_v2_x1_0</td>
      <td>multiple</td>
      <td>64</td>
      <td>2.264811</td>
      <td>0.022603352</td>
      <td>0.051192320246471995</td>
      <td>43.678762</td>
      <td>64</td>
      <td>2.48406</td>
      <td>0.019864012</td>
      <td>0.04934339764872</td>
      <td>43.204043</td>
      <td>0.91</td>
      <td>0.96</td>
      <td>0.88</td>
      <td>0.99</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>Background_Matting</td>
      <td>single</td>
      <td>1</td>
      <td>1.680371</td>
      <td>2.880739765</td>
      <td>4.840711559652815</td>
      <td>50.16649</td>
      <td>1</td>
      <td>1.956941</td>
      <td>2.4907366189999998</td>
      <td>4.874224609922479</td>
      <td>48.728337</td>
      <td>0.86</td>
      <td>1.01</td>
      <td>0.86</td>
      <td>0.97</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>basic_gnn_gcn</td>
      <td>single</td>
      <td>1</td>
      <td>1.835839</td>
      <td>0.040765593</td>
      <td>0.074839065487527</td>
      <td>33.268975</td>
      <td>1</td>
      <td>2.134891</td>
      <td>0.034357286</td>
      <td>0.073349060665826</td>
      <td>32.15738</td>
      <td>0.86</td>
      <td>0.98</td>
      <td>0.84</td>
      <td>0.97</td>
    </tr>
    <tr>
      <td>torchbench</td>
      <td>doctr_det_predictor</td>
      <td>single</td>
      <td>1</td>
      <td>4.044143</td>
      <td>0.857683021</td>
      <td>3.468592785596003</td>
      <td>54.840956</td>
      <td>1</td>
      <td>4.6629</td>
      <td>0.748766216</td>
      <td>3.4914219885863997</td>
      <td>55.272061</td>
      <td>0.87</td>
      <td>1.01</td>
      <td>0.87</td>
      <td>1.01</td>
    </tr>
  </tbody>

</table>

the bad commit: 263a5bf95e8b0160f22f29039235e7fa523a1048
```
/workspace/pytorch# bash inductor_single_run.sh single inference performance torchbench shufflenet_v2_x1_0 amp first static cpp
Testing with cpp wrapper.
Testing with inductor.
single-thread testing....
loading model: 0it [00:00, ?it/s]
cpu  eval  shufflenet_v2_x1_0
running benchmark: 100%|███████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 60.73it/s]
3.125x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,shufflenet_v2_x1_0,1,3.125110,3.915668,18.889813,0.825000,46.714061,56.623104,273,1,0,0,0,0,0
```
the last good commit: 29114e44fa7a17a3a2112d76937ae3b4cf9d33ce
```
/workspace/pytorch# bash inductor_single_run.sh single inference performance torchbench shufflenet_v2_x1_0 amp first static cpp
Testing with cpp wrapper.
Testing with inductor.
single-thread testing....
loading model: 0it [00:00, ?it/s]
cpu  eval  shufflenet_v2_x1_0
running benchmark: 100%|███████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 62.93it/s]
3.558x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,shufflenet_v2_x1_0,1,3.557891,3.422257,18.912550,0.821577,46.714061,56.859034,273,1,0,0,0,0,0
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>766a5e3a</td>
      <td>main</td>
      <td>766a5e3a</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>2fc692b3dd42bf92c4f92dcec862bae7ae1c7995</td>
      <td>main</td>
      <td>5ef33e40b3c3fd2608552d3301c7255826c0e7f6</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.5.0a0+332760d</td>
      <td>main</td>
      <td>2.5.0a0+fa44bda</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob//main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh single inference performance torchbench shufflenet_v2_x1_0 amp first static cpp
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/263a5bf95e8b0160f22f29039235e7fa523a1048
[torchbench-shufflenet_v2_x1_0-inference-amp-static-cpp-single-performance-drop_guilty_commit.log](https://github.com/user-attachments/files/17842867/torchbench-shufflenet_v2_x1_0-inference-amp-static-cpp-single-performance-drop_guilty_commit.log)
cc @chauhang @penguinwu @chuanqi129

**Comment by chunyuan-w** [comment]
cc @Valentine233

**Comment by Valentine233** [comment]
For the guilty commit, some regressions are expected, as we removed a compiler flag. I have already resolved the large regressions before landing the PR. The rest speedups are all above 0.8, and the geomean remains almost the same.
