### ISSUE TITLE
AttributeError: module 'distutils' has no attribute '_msvccompiler'

### ISSUE THREAD

**Issue by EikanWang** [pytorch/pytorch#141319]
### 🐛 Describe the bug

When we trigger Windows CI, we happen to encounter a build failure and error message is as follows:
```bash
AttributeError: module 'distutils' has no attribute '_msvccompiler'
```

Since the `_msvccompiler` has bee deprecated in `setuptools` from `72.1.0`(exclusive) and Intel team submitted a PR to fix the version of `setuptools` - https://github.com/pytorch/pytorch/pull/136489

It seems like Windows CI scripts do not apply this fix by sticking `setuptools` to a particular compatible version.

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Enterprise (10.0.22631 64-bit)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Name: 12th Gen Intel(R) Core(TM) i7-1270P
Manufacturer: GenuineIntel
Family: 198
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 1711
MaxClockSpeed: 2200
L2CacheSize: 9216
L2CacheSpeed: None
Revision: None

Versions of relevant libraries:
[pip3] torch==2.5.0a0+git32f585d
[conda] Could not collect

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
@atalman this was caused by Windows AMI update, wasn't it? I wonder why we haven't detected it? Is it because XPU builds are different that regular ones?

**Comment by malfet** [comment]
Actually, IMO the correct fix is not to use the deprecated method, rather than trying to pin to older disutils forever

**Comment by malfet** [comment]
And looks like it affects both regular and XPU builds, but somehow not nightlies, see https://github.com/pytorch/pytorch/pull/141286#issuecomment-2494414883
