### ISSUE TITLE
The GIF example on http://pytorch.org/about/ seems to have a couple of mistakes in it

### ISSUE THREAD

**Issue by oleg-trott** [pytorch/pytorch#1413]
The GIF example on http://pytorch.org/about/ seems to have a couple of mistakes in it:

- W_h and W_x don't have "requires_grad=True", leading to an error
- the last line has "1, 20" instead of "20, 1", leading to an obscure size mismatch error elsewhere

**Comment by soumith** [comment]
thanks. i'll fix it (eventually). that used to be the old API, several months before release :)

**Comment by AndriyLin** [comment]
Besides, I think the "i2h" and "h2h" box in gif should be inverted.
![image](https://user-images.githubusercontent.com/1215792/30837854-f9e78b7c-a235-11e7-83f6-9b7e876dc050.png)

**Comment by Yoark** [comment]
Agree with above, the gif in README.md and  "http://pytorch.org/about/" seems to be wrong, "i2h" and "h2h" should be inverted
