### ISSUE TITLE
[Export] torch.export of a model with torch.cond doesn't work

### ISSUE THREAD

**Issue by henrylhtsang** [pytorch/pytorch#141305]
**EDIT:** This seems to be a non-strict mode issue. Got nothing to do with AMD.

### 🐛 Describe the bug

Example is from test_cond_symint_input in test_aot_inductor.py. It works on nvidia gpu. 

repro:
```python
class M(torch.nn.Module):
    def forward(self, x, y, z):
        a = y.shape[0]
        b = z.shape[0]

        def true_fn(x):
            return x + a

        def false_fn(x):
            return x + b * z

        return torch.cond(x.shape[0] > 5, true_fn, false_fn, (x,))

input1 = (torch.ones(3, 3), torch.ones(5), torch.ones(3, 3))
model = M().cuda()
dynamic_shapes = {"x": {0: Dim("d")}, "y": {0: Dim("d1")}, "z": {0: Dim("d")}}

ep = torch.export.export(model, input1, dynamic_shapes=dynamic_shapes, strict=False)
```

Internal repro: D66313979

errors: https://gist.github.com/henrylhtsang/f11c79128b66e526e3245bec33370479
```
NotImplementedError: UserDefinedObjectVariable(SymInt)

torch._dynamo.exc.Unsupported: call_function args: TensorVariable() UserDefinedObjectVariable(SymInt) 

torch._dynamo.exc.UncapturedHigherOrderOpError: Cond doesn't work unless it is captured completely with torch.compile. Scroll up to find out what causes the graph break.
```

@ydwu4 

### Versions

trunk

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by hongxiayang** [comment]
@henrylhtsang  How is Dim defined in your reproducer?

**Comment by henrylhtsang** [comment]
> D66313979

its `from torch.export import Dim`

I should be just following https://github.com/pytorch/pytorch/blob/main/test/inductor/test_aot_inductor.py?L=1263#L1251-L1274

**Comment by henrylhtsang** [comment]
Ok. It seems like it is a non-strict mode issue. If I switched to strict mode, then the problem disappears. It has nothing to do with AMD or not.

**Comment by henrylhtsang** [comment]
error:
```
Traceback (most recent call last):
/torch/_dynamo/utils.py", line 776, in proxy_args_kwargs
    proxy_args = tuple(arg.as_proxy() for arg in args)
/torch/_dynamo/utils.py", line 776, in <genexpr>
    proxy_args = tuple(arg.as_proxy() for arg in args)
/torch/_dynamo/variables/base.py", line 341, in as_proxy
    raise NotImplementedError(str(self))
NotImplementedError: UserDefinedObjectVariable(SymInt)
```
