### ISSUE TITLE
Could you make a new release for lintrunner?

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#141395]
@palic @suo 

- https://github.com/suo/lintrunner/issues/75

Would appreciate a new release after https://github.com/suo/lintrunner/commit/a4d6b7469307acae7228d95ee08a4764b1e655f2 is merged to add the win64 wheel? Currently the latest lintrunner on pypi does not have a windows x64 wheel and requires compilation from rust source when installed.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by justinchuby** [comment]
I think just uploading the wheel without bumping version will work

**Comment by malfet** [comment]
Fixed CI (which got a bit rusty :) in https://github.com/suo/lintrunner/commit/3770be65ee7b1186b83cf3873d47a439b275369d about to push the tags..

**Comment by malfet** [comment]
Ok, there is a lintrunner windows binaries now: https://pypi.org/project/lintrunner/0.12.7/#files
