### ISSUE TITLE
DISABLED test_matmul_small_brute_force_tunableop_cuda_float16 (__main__.TestLinalgCUDA)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#141458]
Platforms: rocm, linux

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22test_linalg.py%3A%3ATestLinalgCUDA%3A%3Atest_matmul_small_brute_force_tunableop_cuda_float16%22%5D)).

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

**Comment by bdhirsh** [comment]
test failure looks like it manifests as silent correctness

**Comment by naromero77amd** [comment]
Closing again to re-enable test. Test failed this time due to OOM PyTorch Caching Allocator. Unlikely that issue is related to this UT.
