### ISSUE TITLE
FlexAttention with compiled block mask is slow when varying sequence lengths

### ISSUE THREAD

**Issue by samvanstroud** [pytorch/pytorch#141486]
### 🐛 Describe the bug

I understand from https://github.com/pytorch/pytorch/issues/134756 that it's necessary to compile `create_block_mask` to avoid materialising the full NxM mask. However when doing this with a changing sequence length, recompilation is happening at every step which is costly. Are there any plans to avoid this without adding padding?

In particular I'm using sliding window attention, so I think the block mask could be independent of the sequence length.

I can try using the new `create_nested_block_mask` interface added in https://github.com/pytorch/pytorch/pull/136792, but it's not clear to me that this would support changing total sequence lengths batch to batch. 

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @soulitzer @davidberard98 @YuqingJ @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @yf225 @Chillee @yanboliang @BoyuanFeng

### Versions

`torch==2.5.1`

**Comment by drisspg** [comment]
Do you have some repro code? For instance if you compile the `create_block_mask_func` with default settings and not `dynamic=False` I imagine that automatic dynamic dims should kick in here and you shouldnt need to reocmpile

**Comment by drisspg** [comment]
Okay so you do need to create a new block mask every time the sequence changes but ideall this shouldnt force a recompile and rather just call the fast block_mask creation function.

I fixed your script to work:
```Python
import torch
from torch.nn.attention.flex_attention import create_block_mask, flex_attention

flex_attention = torch.compile(flex_attention)
create_block_mask = torch.compile(create_block_mask)

B = 1
S = 10_000
H = 8
D = 16

def sliding_window_mask(window_size: int):
    def mask_fn(b, h, q_idx, kv_idx):
        return (q_idx - kv_idx <= window_size // 2) & (kv_idx - q_idx <= window_size // 2)
    return mask_fn
mask_mod = sliding_window_mask(1024)
fast_create = torch.compile(create_block_mask, fullgraph=True)
# Warmpup
fast_create(mask_mod, B=None, H=None, Q_LEN=S, KV_LEN=S, device="cuda")

xs = [torch.randn(B, H, i, D, dtype=torch.float16, device="cuda", requires_grad=True) for i in range(10_000, 100_000, 10_000)]
for x in xs:
    block_mask = fast_create(mask_mod, B=None, H=None, Q_LEN=x.size(-2), KV_LEN=x.size(-2), device="cuda")
    out = flex_attention(x, x, x, block_mask=block_mask)
    bwd = out.sum().backward()

```

However I do see the recompiles happening so something is not working correctly with dynamic shapes

@yanboliang Do you think you could take a look, here is the tlparse:

https://manifold.edge.x2p.facebook.net/v0/read/tree/logs/drisspg/custom/index.html?bucketName=tlparse_reports&apiKey=tlparse_reports-key&withPayload=1&timeoutMsec=100

**Comment by jbschlosser** [comment]
@samvanstroud running your repro gives me:
```
...
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: AssertionError: Q seqlen must be smaller than the block_mask size in the Q dimension, considering pass a larger block_mask.
```

> Ok I think I was recalling create_block_mask at each step, which is probably not correct.

This is generally correct to do if your max sequence length changes across iterations, especially if it grows, which it looks like it does from the above error. To avoid recompiles, dynamic shapes needs to kick in as @drisspg mentioned. You could try:

```python
...
flex_attention = torch.compile(flex_attention, dynamic=True)
create_block_mask = torch.compile(create_block_mask, dynamic=True)
```

and create the block mask per iteration:
```
xs = [torch.randn(B, H, i, D, dtype=torch.float16, device="cuda", requires_grad=True) for i in range(10_000, 100_000, 10_000)]
for x in xs:
    S = x.size(2)
    block_mask = create_block_mask(mask_mod, B=None, H=None, Q_LEN=S, KV_LEN=S, device="cuda")
    out = flex_attention(x, x, x, block_mask=block_mask)
    bwd = out.sum().backward()
```

Running this with `TORCH_LOGS="recompiles"` shows me no recompiles of `create_block_mask()` and a single recompile of `flex_attention()`.

```
[1/1] [__recompiles] Recompiling function flex_attention in .../torch/nn/attention/flex_attention.py:1128
[1/1] [__recompiles]     triggered by the following guard failure(s):
[1/1] [__recompiles]     - 1/0: L['query'].size()[2] < 128*L['block_mask'].kv_num_blocks.size()[2]  # query.size(-2)  # nn/attention/flex_attention.py:1244 in flex_attention (_dynamo/variables/tensor.py:1201 in evaluate_expr)
```

This recompile comes from the block_mask readjustment logic here:
https://github.com/pytorch/pytorch/blob/000d4e9d43276964f3ae4e2ffabc1dbb8829e517/torch/nn/attention/flex_attention.py#L1243-L1247

@drisspg / @yanboliang it seems unfortunate that this logic would cause a recompile, as my understanding is it's an optimization to avoid the need for subsequent `create_block_mask()` calls if new inputs have smaller max sequence length than that of the first run.

That said, once there's one compiled graph for entering this logic and one for not entering it, there shouldn't be a further need to recompile.

**Comment by samvanstroud** [comment]
Thanks @drisspg @jbschlosser, I fixed the issue using your code and switching to the latest nightly. Performance is not far from FA2 which is great to see. I ran into nans when using float16 which did not occur with FA2, but using bfloat16 seems to be running ok.
