### ISSUE TITLE
masked_fill() only takes Variable as input

### ISSUE THREAD

**Issue by kennysong** [pytorch/pytorch#1415]
The [docs](http://pytorch.org/docs/tensors.html?highlight=copy#torch.Tensor.masked_fill_) suggest that `masked_fill()` takes a `ByteTensor` as a parameter, but it actually must be wrapped in a Variable first.

**Comment by soumith** [comment]
you are looking at the Tensor docs. When operating on Variable, it is implied from the tutorials that all functions operating on Variables have to use Variables. We didn't write separate docs for Variable itself.
