### ISSUE TITLE
How to implement 'Signed Sqrt' under the Tensor level

### ISSUE THREAD

**Issue by KaiyuYue** [pytorch/pytorch#1416]
Hi,
Are there any good methods to implement the `signed sqrt function`  in pytorch or torch? 

```bash
th> net:add(nn.Sqrt())
nn.Sequential {
  [input -> (1) -> output]
  (1): nn.Sqrt
}

th> a
 4  -4
[torch.DoubleTensor of size 1x2]

th> net:forward(a)
2.000000 nan
```
Would like to achieve the result like:
```bash
th> 
2.000000 -2.000000
```

**Comment by jekbradbury** [comment]
In PyTorch you can use `y = torch.sqrt(F.relu(x)) - torch.sqrt(F.relu(-x))` or write your own `Function` if that's too inefficient.

**Comment by KaiyuYue** [comment]
Sorry about that. And many thanks for your solution. Thanks very much.

**Comment by MichaelLiang12** [comment]
How about the following codes?
```
# signed sqrt
 x = torch.mul(torch.sign(x),torch.sqrt(torch.abs(x)+1e-12)) 
```
BTW, I am implementing bilinear CNN. Do you know anything about it? Can you help me about the problem? [click here](https://discuss.pytorch.org/t/unkonwn-probelm-of-bilinear-cnn-not-error-but-problem-in-my-implemention-of-algorithm/11704)  @KaiyuYue
