### ISSUE TITLE
Documentation on torch.library.register_autograd and torch.library.register_kernel

### ISSUE THREAD

**Issue by Hprairie** [pytorch/pytorch#141618]
### 📚 The doc issue

Currently, the interaction of torch.library.register_autograd and torch.library.register_kernel is not well documented. For example, if I want to define a forward and backward pass for a C++ CPU extension and then also a forward and backward pass for a CUDA GPU extension all using `torch.library.register_autograd` and `torch.library.register_kernel` is not well defined. Specifically if I want to make an `add` function with different functions for the fwd/bwd pass for different devices it is not clear how I should do that with `custom_ops` all under the same name (e.g., "mylib::add"). 

### Suggest a potential alternative/fix

Better documentation on the usage of `torch.library.custom_op`, `torch.library.register_autograd`, `torch.library.register_kernel` would be amazing and would clear up confusion. Thanks!

cc @svekars @brycebortree @sekyondaMeta @AlannaBurke @anjali411 @chauhang @penguinwu @zou3519 @bdhirsh @yf225

**Comment by joldov** [comment]
I am interested in working on this issue - if that is okay, please let me know!

**Comment by Hprairie** [comment]
I will also say that some of the examples for the documentation are just plain wrong. For instance, in the example for `torch.library.custom_op` the documentation references a function `numpy_sin`, which doesn't exist in the example. This is also really confusing with the fact that it is create a function `numpy_add` with the library backend of `mylib::numpy_mul`. As PyTorch transfers from `torch.autograd.Function` to `torch.library.custom_op` strong documentation will really help early adoption.

**Comment by zou3519** [comment]
>  Specifically if I want to make an add function with different functions for the fwd/bwd pass for different devices it is not clear how I should do that with custom_ops all under the same name (e.g., "mylib::add").

I'd recommend having two separate custom operators in that case. It get difficult to debug when a custom operator has different autograd behavior depending on devices.

**Comment by Hprairie** [comment]
@zou3519 That makes sense. If this is the recommended way then it might also be of use to update the [custom_op manual](https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU/edit?tab=t.0#heading=h.84f2ecjg2mf9), as currently in the appendix it references AutogradCPU and AutogradCUDA as the current method to do this. It would still be nice to have documentation on this method. Thanks for the response.

**Comment by zou3519** [comment]
> @zou3519 That makes sense. If this is the recommended way then it might also be of use to update the [custom_op manual](https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU/edit?tab=t.0#heading=h.84f2ecjg2mf9), as currently in the appendix it references AutogradCPU and AutogradCUDA as the current method to do this. It would still be nice to have documentation on this method. Thanks for the response.

Thannk you for the feedback. I updated the section in the manual. Please let us know if there's anything else you have feedback on.
