### ISSUE TITLE
[inductor][cpu] fp32 performance regression in 2024-11-25 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#141671]
### 🐛 Describe the bug

<p>fp32 static shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>pit_b_224</td>
      <td>multiple</td>
      <td>64</td>
      <td>0.24581</td>
      <td>2.546582235</td>
      <td>0.62597537918535</td>
      <td>24.523595</td>
      <td>64</td>
      <td>1.115</td>
      <td>0.555996339</td>
      <td>0.619935917985</td>
      <td>13.819709</td>
      <td>0.22</td>
      <td>0.99</td>
      <td>0.22</td>
      <td>0.56</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>visformer_small</td>
      <td>multiple</td>
      <td>128</td>
      <td>0.129709</td>
      <td>5.213160349</td>
      <td>0.676193815708441</td>
      <td>37.717272</td>
      <td>128</td>
      <td>1.548867</td>
      <td>0.43342591700000005</td>
      <td>0.6713190997860391</td>
      <td>14.766124</td>
      <td>0.08</td>
      <td>0.99</td>
      <td>0.08</td>
      <td>0.39</td>
    </tr>
  </tbody>

</table>

<p>fp32 dynamic shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>pit_b_224</td>
      <td>multiple</td>
      <td>64</td>
      <td>0.242484</td>
      <td>2.5945244429999996</td>
      <td>0.6291306650364119</td>
      <td>29.596023</td>
      <td>64</td>
      <td>1.010343</td>
      <td>0.6167406009999999</td>
      <td>0.623119549036143</td>
      <td>18.770694</td>
      <td>0.24</td>
      <td>0.99</td>
      <td>0.24</td>
      <td>0.63</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>visformer_small</td>
      <td>multiple</td>
      <td>128</td>
      <td>0.123001</td>
      <td>5.516411281</td>
      <td>0.678524103974281</td>
      <td>47.107563</td>
      <td>128</td>
      <td>1.526256</td>
      <td>0.43996378700000005</td>
      <td>0.6714973696914721</td>
      <td>21.267385</td>
      <td>0.08</td>
      <td>0.99</td>
      <td>0.08</td>
      <td>0.45</td>
    </tr>
  </tbody>

</table>

<p>fp32 static shape cpp wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>pit_b_224</td>
      <td>multiple</td>
      <td>64</td>
      <td>0.248796</td>
      <td>2.3010095059999998</td>
      <td>0.5724819610547759</td>
      <td>27.297208</td>
      <td>64</td>
      <td>1.127848</td>
      <td>0.510184414</td>
      <td>0.575410470961072</td>
      <td>18.294733</td>
      <td>0.22</td>
      <td>1.01</td>
      <td>0.22</td>
      <td>0.67</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>visformer_small</td>
      <td>multiple</td>
      <td>128</td>
      <td>0.132074</td>
      <td>5.011374743999999</td>
      <td>0.6618723079390559</td>
      <td>41.060466</td>
      <td>128</td>
      <td>1.692617</td>
      <td>0.39430855200000003</td>
      <td>0.667413358360584</td>
      <td>17.864199</td>
      <td>0.08</td>
      <td>1.01</td>
      <td>0.08</td>
      <td>0.44</td>
    </tr>
  </tbody>

</table>

<p>fp32 dynamic shape cpp wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>pit_b_224</td>
      <td>multiple</td>
      <td>64</td>
      <td>0.250292</td>
      <td>2.297130196</td>
      <td>0.574953311017232</td>
      <td>32.317291</td>
      <td>64</td>
      <td>1.029626</td>
      <td>0.551279098</td>
      <td>0.5676112925573479</td>
      <td>22.379496</td>
      <td>0.24</td>
      <td>0.99</td>
      <td>0.24</td>
      <td>0.69</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>visformer_small</td>
      <td>multiple</td>
      <td>128</td>
      <td>0.13158</td>
      <td>5.039935903</td>
      <td>0.66315476611674</td>
      <td>48.908014</td>
      <td>128</td>
      <td>1.697627</td>
      <td>0.386665408</td>
      <td>0.656413636586816</td>
      <td>24.674601</td>
      <td>0.08</td>
      <td>0.99</td>
      <td>0.08</td>
      <td>0.5</td>
    </tr>
  </tbody>

</table>

the bad commit: f708e92ba10d4cd200059922ad926604e4c1dec9
```
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance timm_models visformer_small float32 first static cpp
Testing with cpp wrapper.
Testing with inductor.
multi-threads testing....
loading model: 0it [00:01, ?it/s]
cpu  eval  visformer_small
running benchmark: 100%|███████████████████████████████████████████████████████| 50/50 [04:39<00:00,  5.60s/it]
0.133x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,visformer_small,128,0.133083,4937.318110,42.891330,0.988093,1209.557402,1224.132608,291,1,0,0,0,0,0
```
the last good commit: 5ab5a61671289f898ed69ca1a06db491dd9e3ea9
```
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance timm_models visformer_small float32 first static cpp
Testing with cpp wrapper.
Testing with inductor.
multi-threads testing....
loading model: 0it [00:01, ?it/s]
cpu  eval  visformer_small
running benchmark: 100%|███████████████████████████████████████████████████████| 50/50 [00:52<00:00,  1.04s/it]
1.704x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,visformer_small,128,1.703771,384.049530,20.355307,0.990680,1209.337856,1220.714906,291,1,0,0,0,0,0
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>766a5e3a</td>
      <td>main</td>
      <td>766a5e3a</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>c513f01516673898d551818c8ca6085cf07e4006</td>
      <td>main</td>
      <td>2fc692b3dd42bf92c4f92dcec862bae7ae1c7995</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.5.0a0+332760d</td>
      <td>main</td>
      <td>2.5.0a0+332760d</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob//main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference performance timm_models visformer_small float32 first static cpp
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/f708e92ba10d4cd200059922ad926604e4c1dec9
[timm_models-visformer_small-inference-float32-static-cpp-multiple-performance-drop_guilty_commit.log](https://github.com/user-attachments/files/17932105/timm_models-visformer_small-inference-float32-static-cpp-multiple-performance-drop_guilty_commit.log)
cc @chauhang @penguinwu @chuanqi129

**Comment by leslie-fang-intel** [comment]
Hi @jiayisunx, could you help to take a look?
