### ISSUE TITLE
[ONNX] Fix sequence handling logic in  _building

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#141729]
@justinchuby I was trying to debug an error that was hitting this line, and was wondering if `arg` here is supposed to be `val`? Changing that locally seemed to fix the problem for me, and it seems from the wider context of the function that `val` might be intended here, but I don't really understand enough to say for sure. It also seems like `arg` might need to be changed to `val` a few lines above in `elif isinstance(arg, (ir.Tensor, ir.TensorProtocol)):` for the same reason?

_Originally posted by @JackDunnNZ in https://github.com/pytorch/pytorch/pull/135378#discussion_r1861213284_

**Comment by justinchuby** [comment]
@JackDunnNZ Also need to make sure the latest code still needs fixing. 

cc @titaiwangms @xadupre if this needs fixing it would be good to be included in 2.6

**Comment by titaiwangms** [comment]
I think it's fixed in nightly.

**Comment by titaiwangms** [comment]
https://github.com/pytorch/pytorch/pull/138656/files
