### ISSUE TITLE
Batched SVD using cuSolver

### ISSUE THREAD

**Issue by jjbouza** [pytorch/pytorch#14175]
It seems there are several people working on batch mode linear algebra routines, i.e. #11796 and #14071 are active. 

Any plans for adding a batch mode SVD? This would be useful for certain implementations of group equivariant networks. 

I'm not completely familiar with the PyTorch codebase, but if I'm not mistaken the usual backend used for linear algebra computations on the GPU is MAGMA. I don't think MAGMA implements a batch SVD operation, but [cuSolver](https://docs.nvidia.com/cuda/cusolver/index.html) does for small matrices (max 32x32). For larger matrices we can just fall back to the current approach. 

If no one else is planning on working on this I can take a look at it. The correct way to do this would be to model something like #9949, right? 

I realize several others have made similar suggestions: #10172, #4689. Those issues don't seem active however.

**Comment by vishwakftw** [comment]
@soumith sure I would be happy to mentor @jjbouza . One question, how will we achieve batched SVD on GPU for matrices larger than 32x32?

**Comment by jjbouza** [comment]
Hello @vishwakftw, thanks for the help. 

The easy solution is to fall back to CPU for matrices larger than 32x32. 

There might be some other options though. For example, using CUDA streams I think we can parallelize the regular (non-batch) SVD operation provided by cuSolver. AFAIK this is what was done before cuSolver provided the batch mode SVD natively. For an example of this see e.g. see the first answer [here](https://stackoverflow.com/questions/17401765/parallel-implementation-for-multiple-svds-using-cuda). 

I would need to test and benchmark this approach though.

**Comment by vishwakftw** [comment]
I think it wouldn't be wise to paralyze users by asking them to use CPU for matrices larger than 32x32, and advocate for a uniform API use across CPU and GPU.

Your idea utilizing `cuSolver` is a good one. On a related note, I think we can use MAGMA for SVD for batches with matrices larger than 32x32. The code would be very similar to LAPACK code for batching in a loop, which you should be able to find in `aten/src/ATen/native/BatchLinearAlgebra.cpp`. As far as the code base goes, I don't think `cuSolver` has been extensively used.

**Comment by jjbouza** [comment]
Agreed, using MAGMA+for loop on GPU would work. I can benchmark the cuSolver CUDA streams approach against this. First I'm going to implement the batched cuSolver routine for batch size <= 32x32. I'll model your batched inverse implementation to do this, so I'll let you know if I have any questions.

**Comment by vishwakftw** [comment]
Great, that's sounds good to me! Please feel free to ping here or on Slack :)

**Comment by vishwakftw** [comment]
Hey @jjbouza . This path sounds good to me!

**Comment by fmassa** [comment]
One quick comment: if possible, try not to add new things to THC, but instead do them directly in ATen

**Comment by vishwakftw** [comment]
@jjbouza , just as @fmassa has suggested, please add the functionality to ATen instead of THC. This means you will have to move the caching logic from THC to ATen for the cuSolver handle. You can still use functions from THC in ATen, so this should not be an issue.

**Comment by vishwakftw** [comment]
@jjbouza any updates?

**Comment by daniyar-niantic** [comment]
Would the batched SVD still be differentiable?

**Comment by vishwakftw** [comment]
Yes, it should be. It is effectively batch_count number of SVDs performed at once; I don't see why it shouldn't be differentiable. Of course, there is always the edge case comprising of ill-conditioned matrices.

**Comment by Balandat** [comment]
this would be great to have!

**Comment by KinglittleQ** [comment]
Hey, guys. I've implemented a batch version of SVD by cuSolver as a individual package, including `forward` and `backward` function. It's not perfect now and only support `torch.CudaFloatTensor` as input but it may be helpful. 

Torch-batch-svd: https://github.com/KinglittleQ/torch-batch-svd

**Comment by vishwakftw** [comment]
This is awesome! Thanks for doing this. For inputs of size greater than 32 x 32, we can probably perform the SVD computation in a loop.

For CPU, this has to be performed in a loop anyways, so I think this is a pretty good implementation!

Do you mind sending in a PR for this? I'd be happy to clarify any questions that you may have about porting this is PyTorch / ATen.

**Comment by KinglittleQ** [comment]
I can try to port it into Pytorch if you could tell me where should I add the forward and backward function. But I'm not sure I have time to complete it as there's other work for me to do now.

**Comment by vishwakftw** [comment]
Is it fine if I complete the port on your behalf?

**Comment by KinglittleQ** [comment]
Of course, it's OK.

**Comment by vishwakftw** [comment]
Thank you, I'll ping you when I send in the pull request.

**Comment by SaiK95** [comment]
@vishwakftw Hi, can you tell me if there's a resolution to this thread? 
Or what the best way to perform batch SVD on small tensors (smaller than 32*32) is?

**Comment by vishwakftw** [comment]
Hi @SaiK95. Sorry I haven’t been able to get to this in the past few months due to college. I’ll get to it in the summer, within a month.

Currently, the best and only possible way to do it would be to run a loop.

**Comment by SaiK95** [comment]
@vishwakftw No problem, thanks for the quick reply!

**Comment by vishwakftw** [comment]
Closing this since the feature is available on master. The current implementation uses sequential MAGMA calls in a for-loop.
