### ISSUE TITLE
AttributeError: 'function' object has no attribute 'save'

### ISSUE THREAD

**Issue by dlml** [pytorch/pytorch#14174]
import torch
import torchvision
from crnn import cnn
# An instance of your model.
model = cnn.CRNN(32, 1, 3343, 256)
model.load_state_dict(torch.load('pytorch-crnn.pth'))
model.eval()
# An example input you would normally provide to your model's forward() method.
example = torch.rand(1, 1, 32, 280)
# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
traced_script_module = torch.jit.trace(model, example)
traced_script_module.save("model.pt")

Traceback (most recent call last):
  File "E:/train_pytorch/test.py", line 16, in <module>
    traced_script_module.save("model.pt")
AttributeError: 'function' object has no attribute 'save'

**Comment by SsnL** [comment]
Version?

**Comment by soumith** [comment]
you have a version that's not our "Preview" build. It's probably version 0.4.1 or earlier.
