### ISSUE TITLE
[AOTI] Temporary files generated by the AOTI package loader are never cleaned up

### ISSUE THREAD

**Issue by etaf** [pytorch/pytorch#141772]
### 🐛 Describe the bug

The Temporary files generated in `AOTIModelPackageLoader::AOTIModelPackageLoader(
    const std::string& model_package_path,
    const std::string& model_name = "model")` are never cleaned and never be reused.

https://github.com/pytorch/pytorch/blob/0f261e8f77c3b374fd8fec3c389f2cefbdabd280/torch/csrc/inductor/aoti_package/model_package_loader.cpp#L279C2-L292C44

When running a benchmark suite, for example:
```
python benchmarks/dynamo/huggingface.py --inference --bfloat16 --accuracy -d cuda  --export-aot-inductor
```
The generated temporary files eg. `/tmp/UUw6E0`,  `/ tmp/HsJ6PV` ... are never cleaned.

![image](https://github.com/user-attachments/assets/c3287c63-7430-454f-b52f-fd093054c7ba)

### Versions

PyTorch version: 2.6.0a0+git6a096a0
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.31.0
Libc version: glibc-2.35

Python version: 3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:49:10)  [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-125-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.4.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB
Nvidia driver version: 550.120
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

cc @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @desertfire @chenyang78

**Comment by EikanWang** [comment]
@etaf , what's the impact? Will it lead to any failure?

**Comment by etaf** [comment]
> @etaf , what's the impact? Will it lead to any failure?

It'll impact E2E test if the disk space for `/tmp` is not large enough.
