### ISSUE TITLE
Missing wheels / wrong requirement specifications on PyPI for `torch` 2.5.0 and 2.5.1

### ISSUE THREAD

**Issue by ThomasHezard** [pytorch/pytorch#141781]
`torch` [2.5.0](https://pypi.org/project/torch/2.5.0/#files) and [2.5.1](https://pypi.org/project/torch/2.5.1/#files) both declare `Python >=3.8.0` requirement, however no wheel or sdit are available for Python 3.8.

- Seen on the web interface:
![Screenshot_20241128-234637.png](https://github.com/user-attachments/assets/43a231fa-5c7b-41ca-9a69-584b146c6c6e)

- Seen in the json API: https://pypi.org/pypi/torch/2.5.1/json and https://pypi.org/pypi/torch/2.5.0/json both contain `"requires_python": ">=3.8.0",`, but no Python 3.8 wheel

It seems that it makes package installation fail with some dependency resolvers (in my case [`uv`](https://github.com/astral-sh/uv)) as version 2.5.1 may be selected for `torch` with Python 3.8 but no wheel or sdist is found when trying to download.

Thank you.

**Comment by mikaylagawarecki** [comment]
Seems related to https://github.com/pytorch/pytorch/issues/140798

**Comment by malfet** [comment]
> Seems related to #140798

No, it's different, we published the wheels with metadata that says that python-3.8 is still supported.

**Comment by ZainRizvi** [comment]
The metadata was a bug unfortunately, sorry for the confusion there. PyTorch 2.5 does NOT support python 3.8

**Comment by ZainRizvi** [comment]
@atalman for 2.6 can you please add a test/release process to ensure that we have the correct metadata published?

**Comment by kit1980** [comment]
This is a duplicate for https://github.com/pytorch/pytorch/issues/139005
You can use a workaround provided in that issue, and we will make sure for 2.6.0 the metadata is correct.
