### ISSUE TITLE
Doc or Examples for torch.utils.trainer

### ISSUE THREAD

**Issue by Jiaming-Liu** [pytorch/pytorch#1417]
This feature seems to be cool but there isn't any documentation or examples about this.

**Comment by moskomule** [comment]
See https://github.com/pytorch/examples/blob/27e2a46c1d1505324032b1d94fc6ce24d5b67e97/imagenet/main.py#L87,  this would be helpful.

**Comment by fmassa** [comment]
This trainer is an experimental module and will be removed soon from master. If you want such functionalities, have a look at github.com/pytorch/tnt

**Comment by YuhengZhi** [comment]
Here's an issue. This module seems to lack the support for GPU, but you may modify the 57 and 58 lines of `trainer.py` to be:
```
input_var = Variable(batch_input.cuda())
target_var = Variable(batch_target.cuda())
```
to support GPU. Of course, it would be better if we could conveniently choose whether we want to use GPU upon the initiation of a `trainer`.
