### ISSUE TITLE
[MPS] Autocast fails for `F.scaled_dot_product_attention`

### ISSUE THREAD

**Issue by hvaara** [pytorch/pytorch#141774]
### 🐛 Describe the bug

In https://github.com/pytorch/pytorch/issues/141471#issuecomment-2504976472 @malfet discovered that SDPA fails when using autocast with the MPS backend. Autocast was introduced in #99272, and later extended to `bfloat16` in #139390. While autocast no longer raises warnings for `bfloat16`, `F.scaled_dot_product_attention` is not supported by autocast, resulting in a runtime error. Disabling autocast resolves the issue, suggesting that `scaled_dot_product_attention` lacks proper support within the autocast mechanism.

#### Minimal reproducer

```python
import torch
import torch.nn.functional as F

device = "mps"
# Test both bfloat16 and float16 for SDPA compatibility with autocast. See below output examples.
# dtype = torch.bfloat16
dtype = torch.float16

query = torch.rand(4, 4, 8, dtype=torch.float32, device=device)
key = torch.rand(4, 4, 8, dtype=torch.float32, device=device)
value = torch.rand(4, 4, 8, dtype=dtype, device=device)

with torch.amp.autocast(device_type=device):
    hidden_states = F.scaled_dot_product_attention(query, key, value)
# RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: float key.dtype: float and value.dtype: c10::BFloat16 instead.
# RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: float key.dtype: float and value.dtype: c10::Half instead.
```

Adding a kernel mapping for `scaled_dot_product_attention` in `aten/src/ATen/autocast_mode.cpp` resolves the issue:

```diff
diff --git a/aten/src/ATen/autocast_mode.cpp b/aten/src/ATen/autocast_mode.cpp
index 1129892dd25..6649708c706 100644
--- a/aten/src/ATen/autocast_mode.cpp
+++ b/aten/src/ATen/autocast_mode.cpp
@@ -236,6 +236,7 @@ TORCH_LIBRARY_IMPL(aten, AutocastMPS, m) {
   KERNEL_MPS(chain_matmul, lower_precision_fp)
   KERNEL_MPS(linalg_multi_dot, lower_precision_fp)
   KERNEL_MPS(lstm_cell, lower_precision_fp)
+  KERNEL_MPS(scaled_dot_product_attention, lower_precision_fp)

   // fp32
   KERNEL_MPS(acos, fp32)
```

This issue focuses on fixing autocast support for SDPA. Another issue will be opened to identify and fix support for other ops in a holistic approach.

### Versions

PyTorch version: 2.6.0a0+git45ed7c1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.4)
CMake version: version 3.30.2
Libc version: N/A

Python version: 3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:32:50) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-15.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] clip-anytorch==2.6.0
[pip3] dctorch==0.1.2
[pip3] flake8==7.1.1
[pip3] mypy==1.11.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] torch==2.6.0a0+git45ed7c1
[pip3] torch-stoi==0.2.1
[pip3] torchaudio==2.5.0a0+ba696ea
[pip3] torchdiffeq==0.2.4
[pip3] torchsde==0.2.6
[pip3] torchvision==0.20.0a0+e9a3213
[pip3] triton==3.0.0
[conda] clip-anytorch             2.6.0                    pypi_0    pypi
[conda] dctorch                   0.1.2                    pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.6.0a0+git45ed7c1           dev_0    <develop>
[conda] torch-stoi                0.2.1                    pypi_0    pypi
[conda] torchaudio                2.5.0a0+ba696ea           dev_0    <develop>
[conda] torchdiffeq               0.2.4                    pypi_0    pypi
[conda] torchsde                  0.2.6                    pypi_0    pypi
[conda] torchvision               0.20.0a0+e9a3213           dev_0    <develop>
[conda] triton                    3.0.0                    pypi_0    pypi

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by hvaara** [comment]
Fix incoming.

@pytorchbot label "module: mps" "module: amp (automated mixed precision)"

**Comment by malfet** [comment]
Do you mind just proposing this PR and I'll merge it in today's nightly?

**Comment by hvaara** [comment]
Added a proposal in #141776.

cc @malfet
