### ISSUE TITLE
Will there still be an available arm package with cxx11-abi=0 after the manylinux2_28 switch?

### ISSUE THREAD

**Issue by dilililiwhy** [pytorch/pytorch#141810]
### 🐛 Describe the bug

As for https://github.com/pytorch/pytorch/pull/140743, it seems that cxx11-abi is involved in workflow generated-linux-aarch64-binary-manywheel-nightly with the manylinux2_28 switch.

Will there still be an available arm package with cxx11-abi=0 after the manylinux2_28 switch?

### Versions

PyTorch version: 2.6.0.dev20241120+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: AlmaLinux 8.10 (Cerulean Leopard) (aarch64)
GCC version: (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Clang version: Could not collect
CMake version: version 3.31.0
Libc version: glibc-2.28

Python version: 3.9.20 (main, Nov 13 2024, 23:03:23)  [GCC 13.3.1 20240611 (Red Hat 13.3.1-2)] (64-bit runtime)
Python platform: Linux-4.14.0-115.el7a.0.1.aarch64-aarch64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              192
On-line CPU(s) list: 0-191
Thread(s) per core:  1
Core(s) per cluster: 48
Socket(s):           -
Cluster(s):          4
NUMA node(s):        4
Model:               0
Stepping:            0x1
CPU max MHz:         2600.0000
CPU min MHz:         200.0000
BogoMIPS:            200.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            24576K
NUMA node0 CPU(s):   0-47
NUMA node1 CPU(s):   48-95
NUMA node2 CPU(s):   96-143
NUMA node3 CPU(s):   144-191
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.6.0.dev20241120+cpu

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @malfet @osalpekar @atalman @snadampal @milpuz01

**Comment by malfet** [comment]
@dilililiwhy everything is possible, but I'm curious whats the motiviation? I.e. all manylinux2_28 compatible platforms will have C++11 compatible runtime, so what's the reason for using old one?

**Comment by atalman** [comment]
Hi @dilililiwhy So far there is no plan on supporting this flag for Manylinux 2.28 aarch64 builds. Please see: https://dev-discuss.pytorch.org/t/pytorch-linux-wheels-switching-to-new-wheel-build-platform-manylinux-2-28-on-november-12-2024/2581

**Comment by dilililiwhy** [comment]
@malfet @atalman Thansk for reply. Because if the original version is still retained, external adaptation should handle the compatibility issue. It is glad to see this update.

**Comment by dilililiwhy** [comment]
@malfet @atalman Thansk for reply. Because if the original version is still retained, external adaptation should handle the compatibility issue. It is glad to see this update.
