### ISSUE TITLE
Why pytorch does not accept input image as uint8 type

### ISSUE THREAD

**Issue by anbai106** [pytorch/pytorch#14186]
## 🐛 Bug

I just may have a stupid question about fitting uint8 datatype into a CNN by pytorch. We know that a RGB image is often with a datatype of uint8.  When I force to fit the original data into a CNN, it gave me error said that 'con2d does not accept the type of torch.ByteTensor'… So I have to transfer my image into float: `omg.float`. 

The problem is that my data is MRI, when converting the image into float, the visualization results get strange… I do not know if this is because of the viewer or from pytorch… I check the value between different datatype, float or int8, the value did not change, (e.g., 144.0 to 144).

Thanks in advance for your help..

Hao

**Comment by SsnL** [comment]
Integral dtypes are inherently discrete... So about every DL framework use floating points because they need gradients. 

> The problem is that my data is MRI, when converting the image into float, the visualization results get strange… I do not know if this is because of the viewer or from pytorch… I check the value between different datatype, float or int8, the value did not change, (e.g., 144.0 to 144).

If this is standard RGB image we are talking about, you need to divide by 255 after casting into float.
