### ISSUE TITLE
[C++ Extensions] Accepted compilers doesn't handle Python 2

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#14188]
## 🐛 Bug

The result of [sys.platform in python 2 and python < 3.3](https://stackoverflow.com/questions/10415942/python-sys-platform-linux2-but-not-linux3) used to return `linux2` or `linux3` depending on the version of python.
In [ACCEPTED_COMPILERS_FOR_PLATFORM](https://github.com/pytorch/pytorch/blob/5b1b8682a303379e8f52c282399540750e0b8200/torch/utils/cpp_extension.py#L138), we currently [hard-code `linux`](https://github.com/pytorch/pytorch/blob/5b1b8682a303379e8f52c282399540750e0b8200/torch/utils/cpp_extension.py#L87), which breaks when using Python 2 with errors such as 
```
check_compiler_abi_compatibility(compiler)
File "/home/deep/anaconda2/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 160, in check_compiler_abi_compatibility
if not check_compiler_ok_for_platform(compiler):
File "/home/deep/anaconda2/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform
accepted_compilers = ACCEPTED_COMPILERS_FOR_PLATFORM[sys.platform]
KeyError: 'linux2'
```
see https://github.com/facebookresearch/maskrcnn-benchmark/issues/174 for an example where this broke.

cc @goldsborough

**Comment by fmassa** [comment]
Another issue (which I think is unrelated to this particular problem) but which was raised up recently was https://github.com/facebookresearch/maskrcnn-benchmark/issues/176

**Comment by goldsborough** [comment]
I just noticed this! I was totally not aware of this Python2/3 discrepancy. I am fixing it.
