### ISSUE TITLE
nn.parallel.DistributedDataParallel raise CUDA error

### ISSUE THREAD

**Issue by senhui-guo** [pytorch/pytorch#14187]
## 🐛 Bug

Here's my code
```python
import argparse
import torch
import torch.nn as nn

parser = argparse.ArgumentParser()
parser.add_argument('--local_rank', metavar='int', type=int, dest='rank', default=0, help='rank')
args = parser.parse_args()


torch.cuda.set_device(args.rank)
torch.distributed.init_process_group(backend='nccl')
class test(nn.Module):
    def __init__(self):
        super().__init__()
        self.l = nn.Linear(10,10)

    def forward(self, data):
        return self.l(data)

net = nn.parallel.DistributedDataParallel(test(), device_ids=[args.rank], output_device=args.rank)
```

this raise RuntimeError: Only CUDA dense tensor is supported for NCCL collective operations
I don't know what I was doing wrong, but I checked the test class, and the buffer & gradient are all not sparse.

**Comment by SsnL** [comment]
The problem is not dense vs. sparse, but cpu vs. cuda. Use `.to('cuda')` to put the network on gpu.

**Comment by senhui-guo** [comment]
@SsnL Just out of curiosity, how come nn.DataParallel doesn't require the model sent to cuda device first?

**Comment by jalajthanaki** [comment]
Hi All,

I'm facing similar issue. @SsnL Did you able to fix it?
