### ISSUE TITLE
Enable unused variable checking in ruff

### ISSUE THREAD

**Issue by rec** [pytorch/pytorch#141821]
### 🚀 The feature, motivation and pitch

pytorch uses ruff, but with several potentially useful flags turned off.

In particular, [F841](https://docs.astral.sh/ruff/rules/unused-variable/#unused-variable-f841) detects unused variables, which have caused issues in the past (e.g. https://github.com/pytorch/pytorch/pull/132744) and are if nothing else a waste of space.

There are a few hundred unused variables in the pytorch code; most are trivial, a few are real issues.

I have already started on doing this as a spare-time project. The main pull requests follow:

- [x] https://github.com/pytorch/pytorch/pull/133492
- [x] https://github.com/pytorch/pytorch/pull/136963
- [x] https://github.com/pytorch/pytorch/pull/134665
- [x] https://github.com/pytorch/pytorch/pull/136964
- [x] https://github.com/pytorch/pytorch/pull/136359
- [x] https://github.com/pytorch/pytorch/pull/136965

In addition, several tiny commits were extracted from this on request in code reviews:

- [x] https://github.com/pytorch/pytorch/pull/138480
- [x] https://github.com/pytorch/pytorch/pull/138473
- [x] https://github.com/pytorch/pytorch/pull/138474
- [x] https://github.com/pytorch/pytorch/pull/138475
- [x] https://github.com/pytorch/pytorch/pull/138094
- [x] https://github.com/pytorch/pytorch/pull/138086
- [x] https://github.com/pytorch/pytorch/pull/138085
- [x] https://github.com/pytorch/pytorch/pull/138000
- [x] https://github.com/pytorch/pytorch/pull/137998
- [x] https://github.com/pytorch/pytorch/pull/137989
- [x] https://github.com/pytorch/pytorch/pull/137985
- [x] https://github.com/pytorch/pytorch/pull/143191
- [x] https://github.com/pytorch/pytorch/pull/143389
- [x] https://github.com/pytorch/pytorch/pull/143396
- [x] https://github.com/pytorch/pytorch/pull/143399
- [x] https://github.com/pytorch/pytorch/pull/143407

### Alternatives

Leaving things the way they were. :-)

**Comment by albanD** [comment]
With the last PR landing, this is now all done.
Thanks a lot @rec for relentlessly going through all of these!
