### ISSUE TITLE
cross_entropy - class weights is a bit unclear

### ISSUE THREAD

**Issue by kasparlund** [pytorch/pytorch#14184]
## 📚 Documentation
The weights are ignored with reduction = "elementwise_mean" - this is actually what the documentation says but it would be much clearer to provide either:

- a warning that the weight are being ignored with "elementwise_mean" and suggest the use of reduction = "sum"
- or provide a reduction="mean" which result in the weigths being used in a weighed mean. I guess this is the behaviour that most users would expect

**Comment by zou3519** [comment]
@ailzhang I think @eellison is moving cross_entropy to ATen

**Comment by ailzhang** [comment]
I believe `elementwise_mean` has been removed from `reduction` options now. https://pytorch.org/docs/stable/nn.html?highlight=cross_entropy#torch.nn.CrossEntropyLoss
Closing, please feel free to reopen if you have other questions. Thanks!
