### ISSUE TITLE
BFloat16 Unsupported on MPS (macOS Sequoia 15.1.1, Intel, AMD)

### ISSUE THREAD

**Issue by SkyForceCoder** [pytorch/pytorch#141864]
### 🐛 Describe the bug

I am encountering the error `TypeError: BFloat16 is not supported on MPS` while using PyTorch with Apple's Metal Performance Shaders (MPS) backend. This issue arises across multiple projects, specifically **Stable Diffusion WebUI Forge** and **ComfyUI**, both of which depend on PyTorch for GPU acceleration.

> **Processor:**

Model: Intel(R) Xeon(R) W-2140B CPU
Speed: 3.20 GHz
Cores: 8 cores (with Hyper-Threading enabled)

> **Memory (RAM):**

Total RAM: 32 GB (34359738368 bytes)

> **GPU:**

Model: Radeon Pro Vega 56
VRAM: 8 GB
Bus: PCIe (x16)
Metal Support: Metal 3 (supports Apple's graphics framework)

#### Projects where this issue occurs:

1. [[Stable Diffusion WebUI Forge Issue #2399](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/2399)](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/2399)
2. [[ComfyUI Issue #5829](https://github.com/comfyanonymous/ComfyUI/issues/5829)](https://github.com/comfyanonymous/ComfyUI/issues/5829)

#### Steps to Reproduce:

1. Use macOS with an MPS-supported GPU.
2. Run ComfyUi or Forge  that utilize BFloat16 operations during processing.
3. The error consistently appears during model sampling or inference:
   TypeError: BFloat16 is not supported on MPS

#### Observations:
- The error suggests that the MPS backend in PyTorch doesn't support BFloat16 precision.
- This issue is critical because many ML pipelines and UIs default to BFloat16 or use it for performance reasons.

**System:**
 macOS : Sequoia (15.1.1) Intel, AMD

#### Request:
Can BFloat16 support be added to MPS in PyTorch, CPU is very very slow for this type of operations.

### Versions

2.1.2
ALL VERSIONS

cc @seemethere @malfet @osalpekar @atalman @albanD @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @kulinseth @DenisVieriu97 @jhavukainen

**Comment by hvaara** [comment]
Your PyTorch version is very old. Does it work if you update?

**Comment by SkyForceCoder** [comment]
@hvaara 

<img width="886" alt="Screenshot 2024-12-07 at 12 30 27 PM" src="https://github.com/user-attachments/assets/612244ab-2720-4448-b162-dc805daadc64">

I see latest version is 2.5.1 but it's not instaling 

% pip install torch==2.3.1                                                                                
ERROR: Could not find a version that satisfies the requirement torch==2.3.1 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.3.1


% pip3 install torch torchvision torchaudio

Successfully installed torch-2.2.2 torchaudio-2.2.2 torchvision-0.17.2

% python -c "import torch; print(f'PyTorch Version: {torch.__version__}'); print(f'MPS Available: {torch.backends.mps.is_available()}')"

PyTorch Version: 2.2.2
MPS Available: True


Error

Traceback (most recent call last):
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/modules/txt2img.py", line 131, in txt2img_function
    processed = processing.process_images(p)
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/modules/processing.py", line 842, in process_images
    res = process_images_inner(p)
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/modules/processing.py", line 990, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/modules/processing.py", line 1387, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 198, in sample
    sampling_prepare(self.model_wrap.inner_model.forge_objects.unet, x=x)
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 383, in sampling_prepare
    memory_management.load_models_gpu(
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/backend/memory_management.py", line 684, in load_models_gpu
    loaded_model.model_load(model_gpu_memory_when_using_cpu_swap)
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/backend/memory_management.py", line 516, in model_load
    bake_gguf_model(self.real_model)
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/backend/memory_management.py", line 347, in bake_gguf_model
    gguf_cls.bake(p)
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/packages_3rdparty/gguf/quants.py", line 152, in bake
    cls.bake_inner(parameter)
  File "/Volumes/Spidy/GitHub/AI/stable-diffusion-webui-forge/packages_3rdparty/gguf/quants.py", line 310, in bake_inner
    d = d.view(torch.float16).to(parameter.computation_dtype).view(torch.uint8)
TypeError: BFloat16 is not supported on MPS
BFloat16 is not supported on MPS

**Comment by hvaara** [comment]
I think you tried to install `2.3.1`, not `2.5.1`. Alternatively run `pip3 install -U torch`.

**Comment by SkyForceCoder** [comment]
@hvaara but for me latest version is 2.2.2 is downloading

% python --version                           
Python 3.10.14

% pip3 install --no-cache-dir -U torch torchvision torchaudio  
Collecting torch
  Downloading torch-2.2.2-cp310-none-macosx_10_9_x86_64.whl.metadata (25 kB)
Collecting torchvision
  Downloading torchvision-0.17.2-cp310-cp310-macosx_10_13_x86_64.whl.metadata (6.6 kB)
Collecting torchaudio
  Downloading torchaudio-2.2.2-cp310-cp310-macosx_10_13_x86_64.whl.metadata (6.4 kB)
Requirement already satisfied: filelock in ./venv/lib/python3.10/site-packages (from torch) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in ./venv/lib/python3.10/site-packages (from torch) (4.12.2)
Requirement already satisfied: sympy in ./venv/lib/python3.10/site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in ./venv/lib/python3.10/site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in ./venv/lib/python3.10/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in ./venv/lib/python3.10/site-packages (from torch) (2024.10.0)
Requirement already satisfied: numpy in ./venv/lib/python3.10/site-packages (from torchvision) (1.26.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./venv/lib/python3.10/site-packages (from torchvision) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.10/site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./venv/lib/python3.10/site-packages (from sympy->torch) (1.3.0)
Downloading torch-2.2.2-cp310-none-macosx_10_9_x86_64.whl (150.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.8/150.8 MB 26.1 MB/s eta 0:00:00
Downloading torchvision-0.17.2-cp310-cp310-macosx_10_13_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 33.5 MB/s eta 0:00:00
Downloading torchaudio-2.2.2-cp310-cp310-macosx_10_13_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 34.3 MB/s eta 0:00:00
Installing collected packages: torch, torchvision, torchaudio
Successfully installed torch-2.2.2 torchaudio-2.2.2 torchvision-0.17.2

**Comment by hvaara** [comment]
Oh sorry, I just realized this was for an Intel Mac. I'm afraid bfloat16 isn't supported for that architecture.

**Comment by ghsanti** [comment]
Wasn't this solved with 2.6, i.e pytorch nightly in the selection matrix? I had a bfloat16 warning that disappeared, for ARM though.

**Comment by SkyForceCoder** [comment]
@ghsanti the latest version is 2.2.2

 % pip install torch==2.6.0
ERROR: Could not find a version that satisfies the requirement torch==2.6.0 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.6.0


% conda install pytorch=2.6.0 -c pytorch     
Channels:
 - pytorch
 - intel
 - conda-forge
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by ghsanti** [comment]
You need to is the nightly install:


```python
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
```

@SkyForceCoder

**Comment by SkyForceCoder** [comment]
@ghsanti 
 % pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
Looking in indexes: https://download.pytorch.org/whl/nightly/cpu
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

**Comment by ghsanti** [comment]
Thats strange. You can click in the index and check which mac os they have. I guess your processor isnt ARM but x86_64 right? 

For apple silicon arm64 that command runs just fine, assuming python 3.10+

**Comment by SkyForceCoder** [comment]
@ghsanti 
% uname -m
x86_64

**Comment by ghsanti** [comment]
@malfet was mps/bfloat16 support in 2.6 dev only for arm64 CPU or also for amd / x64_86 architectures?

Cc @SkyForceCoder

**Comment by SkyForceCoder** [comment]
@ghsanti It appears that version 2.6 is not available for macOS x86_64. The latest version for Mac is 2.2.2. Yes, MPS is supported in 2.2.2, but not bfloat16

**Comment by SkyForceCoder** [comment]
@ghsanti problem occurs for flux_dev because it uses bfloat16 and flux is best

**Comment by ghsanti** [comment]
> @ghsanti problem occurs for flux_dev because it uses bfloat16 and flux is best

I manually checked the indices, pytorch does not have amd support for mac os since 2.2.2 I think, so that's that.

I tried bfloat16 though and didn't improve training only memory.

**Comment by SkyForceCoder** [comment]
@ghsanti now what is solution

**Comment by ghsanti** [comment]
> @ghsanti now what is solution

None, just sell it and get a second hand M1 and a monitor (just kidding, idk.) [Here is the announcement](https://dev-discuss.pytorch.org/t/pytorch-macos-x86-builds-deprecation-starting-january-2024/1690) if i understand correctly.

**Comment by malfet** [comment]
One can build PyTorch from source (as binary builds are no longer available, at least on PyPI, see https://dev-discuss.pytorch.org/t/pytorch-macos-x86-builds-deprecation-starting-january-2024/1690 ), though I don't know if bfloat16 is something that is supported by the HW on x86 MacOS

Closing the issue, but please do not hesitate to file an issue if you encounter a problem with PyTorch on a supported hardware

**Comment by malfet** [comment]
> Was mps/bfloat16 support in 2.6 dev only for arm64 CPU or also for amd / x64_86 architectures?


I don't know. You can try building it from source and see what will happen, but my x86 Mac is too old and can not be upgraded to MacOS Sonoma, so I don't know.

**Comment by ghsanti** [comment]
Thanks for replying, yeah I understand.

**Comment by SkyForceCoder** [comment]
@malfetI will check by building it from the source and will provide updates here.

**Comment by SkyForceCoder** [comment]
@malfet @ghsanti 

System Configuration:
macOS Version: Sequoia 15.2
Python Version: 3.9.4 (installed via Conda)
Architecture: x86_64 (64-bit)

MPS is working on it.

torch-2.4.0a0+gitee1b680-cp39-cp39-macosx_15_0_x86_64.whl
torchaudio-2.4.0a0+69d4077-cp39-cp39-macosx_15_0_x86_64.whl
torchvision-0.19.0a0+48b1edf-cp39-cp39-macosx_10_9_x86_64.whl

I uploaded it on archive.org 
https://archive.org/details/torch-2.4.0a0gitee1b680-cp39-cp39-macosx_15_0_x86_64_20241231

**Comment by hvaara** [comment]
@SkyForceCoder are you saying bfloat16 is working on x86_64? If so, how did you test it?

**Comment by SkyForceCoder** [comment]
@hvaara I encountered another error. It seems that a new version of Torch is not available for Mac intel amd, so I used the source code to create the wheel files for the new version. However, I’m now facing a different error. I'll share the details with you shortly

**Comment by SkyForceCoder** [comment]
@hvaara this error now
The operator 'aten::__rshift__.Tensor' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

**Comment by hvaara** [comment]
@SkyForceCoder I didn't think bfloat16 was supported on that hardware, but apparently it is. That's great to know. Does adding `PYTORCH_ENABLE_MPS_FALLBACK=1` to your environment give you any progress?

**Comment by sturmfink** [comment]
@SkyForceCoder 
Accidentally stumbled over this today while searching for something very different on the big G. 😅

First of all I want to **thank you** very much for sharing your progress and the torch 2.4 build from source!
(Was facing the same issue. A few days ago.)

I am working on another project right now, but I will test it soon with the fallback and see what toll it takes.

Also I am very excited for your updates on the issue.
Have a great day 🙃

**Comment by fengerzh** [comment]
No, it's not related to Intel CPU, my m4 CPU also report this error.
