### ISSUE TITLE
Warning/Exception for torchtext.data.metrics.bleu_score 

### ISSUE THREAD

**Issue by Rajinish0** [pytorch/pytorch#141962]
### 🚀 The feature, motivation and pitch

I was working on calculating bleu_score, however, due to a bug in my code I did not realize that my references_corpus wasn't a list of list of words; I think it would be helpful for this function to either give a warning or raise an Exception if the references_corpus is not in the desired format.

Thanks!

**Comment by cpuhrsch** [comment]
Hello @Rajinish0 - thank you for opening this issue! Please direct issues related to torchtext to the torchtext repository directly. Thank you!
