### ISSUE TITLE
[feature request] Some automatic type conversions

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#14190]
What are coredevs thoughts about allowing automatic type conversions for some cases (like scalar upcasting)?

```python
torch.FloatTensor([0.0, 1.0]) > 0  # works
# tensor([0, 1], dtype=torch.uint8)

torch.FloatTensor([0.0, 1.0]) > torch.tensor(0) # fails
# RuntimeError: Expected object of scalar type Float but got scalar type Long for argument #2 'other'
```

**Comment by vadimkantorov** [comment]
(Multiplying a float tensor by a byte tensor (masks) is also quite common)

**Comment by vadimkantorov** [comment]
I have a fairly recent PyTorch install (from September) and the example in the original post still seems to fail. Given that now type promotion is being worked on, probably this can also be fixed soon: `torch.FloatTensor([0.0, 1.0]) * torch.tensor(0)` works fine

Another type promotion thing: `torch.exp(torch.tensor(3))` - `RuntimeError: exp_vml_cpu not implemented for 'Long'`

**Comment by gchanan** [comment]
the first example works fine now.

Do you mind filing an issue for torch.exp?  Our current type promotion doesn't cover that case, it only looks at the dtypes of (actual) arguments.  There's a similar issue with supporting e.g. true_division.

**Comment by vadimkantorov** [comment]
By the first you mean `torch.FloatTensor([0.0, 1.0]) > torch.tensor(0)`, right?

I'll file a separate issue about torch.exp

**Comment by gchanan** [comment]
Sorry for not being clear, I meant:
`torch.FloatTensor([0.0, 1.0]) * torch.tensor(0)` works

`torch.FloatTensor([0.0, 1.0]) > torch.tensor(0)` also works now, although it gives you a `torch.bool` result now.

**Comment by vadimkantorov** [comment]
Cool! If `torch.FloatTensor([0.0, 1.0]) > torch.tensor(0)` works, I'll close this issue!
