### ISSUE TITLE
torch.norm named arguments do not work as expected

### ISSUE THREAD

**Issue by szagoruyko** [pytorch/pytorch#1419]
torch.norm only accepts `p, dim`, giving only `dim` results in error
```
In [3]: torch.autograd.Variable(torch.randn(4,8)).norm(dim=1)
Out[3]:
Variable containing:
 2.1210
 3.0991
 2.4054
 2.1048
[torch.FloatTensor of size 4x1]

In [4]: torch.randn(4,8).norm(dim=1)

TypeError: norm received an invalid combination of arguments - got (dim=int, ), but expected one of:
 * no arguments
 * (float p)
      didn't match because some of the keywords were incorrect: dim
 * (float p, int dim)

In [8]: torch.randn(4,8).norm(p=2, dim=1)
Out[8]:

 1.9636
 2.1119
 2.8933
 4.0552
[torch.FloatTensor of size 4x1]
```

**Comment by killeent** [comment]
I am taking a look at this.

**Comment by killeent** [comment]
There is an easy way of doing this, we simply provide a default for p in the cwrap:

`
arguments:
    - arg: THTensor* destination
    - output: True
    - THTensor* self
    # before: - real p
    - arg: real p
    default: AS_REAL(2)
    - arg: long dim
    wrap_dim: self
`
However, this is a little weird, as then you have an optional parameter followed by a non-optional parameter, i.e. `norm(input, p=2, dim, out=None)`.

**Comment by lantiga** [comment]
Based on the discussion, do we need to modify cwrap to handle the optional+non optional parameter weirdness or should we just proceed adding the default for the time being?

**Comment by christoph-conrads** [comment]
Named arguments work for me when the first argument to `torch.norm()` is a `torch.autograd.Variable`; using `torch.Tensor` causes exceptions.

MWE:
```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function

import torch
import torch.autograd


t = torch.ones(1, 1)
v = torch.autograd.Variable(t)

print(torch.version.__version__)
torch.norm(v, dim=1)
torch.norm(t, p=2, dim=1)
torch.norm(t, dim=1)
```

Output:
```
christoph:/tmp$ python --version
Python 2.7.13 :: Anaconda, Inc.
christoph:/tmp$ conda --version
conda 4.3.30
christoph:/tmp$ python tensor-vs-variable.py 
0.2.0+547ac8c
Traceback (most recent call last):
  File "tensor-vs-variable.py", line 16, in <module>
    torch.norm(t, dim=1)
TypeError: torch.norm received an invalid combination of arguments - got (torch.FloatTensor, dim=int), but expected one of:
 * (torch.FloatTensor source)
 * (torch.FloatTensor source, float p)
      didn't match because some of the keywords were incorrect: dim
 * (torch.FloatTensor source, float p, int dim)
 * (torch.FloatTensor source, float p, int dim, bool keepdim)
```

**Comment by vadimkantorov** [comment]
also affected by this

**Comment by zou3519** [comment]
Looking into this

**Comment by SsnL** [comment]
This is due to Variable has a specific python method in `variable.py` to handle this. After discussing with @colesbury , we think that it would be best to solve this when we add support for calling these methods on multiple dims.

**Comment by colesbury** [comment]
This is fixed in master now
