### ISSUE TITLE
Nightly torch wheel is not picking up correct pytorch-triton/pytorch-triton-rocm package

### ISSUE THREAD

**Issue by jataylo** [pytorch/pytorch#141956]
### 🐛 Describe the bug

After the latest triton commit bump (https://github.com/pytorch/pytorch/pull/139206) nightly torch packages are not picking up the latest triton package, instead using the previous triton wheel 3.1.0+cf34004b8a:

ROCm:
> Successfully installed pytorch-triton-rocm-3.1.0+cf34004b8a torch-2.6.0.dev20241113+rocm6.2

NV:
```
  Downloading https://download.pytorch.org/whl/nightly/cu124/torch-2.6.0.dev20241113%2Bcu124-cp310-cp310-linux_x86_64.whl (986.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 986.4/986.4 MB 21.4 MB/s eta 0:00:00
Collecting pytorch-triton==3.1.0+cf34004b8a (from torch)
  Downloading https://download.pytorch.org/whl/nightly/pytorch_triton-3.1.0%2Bcf34004b8a-cp310-cp310-linux_x86_64.whl (239.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.6/239.6 MB 77.7 MB/s eta 0:00:00
```

### Versions

Nightly wheels

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang @naromero77amd @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov

**Comment by jataylo** [comment]
cc: @bertmaher @atalman

**Comment by atalman** [comment]
HI @jataylo I see triton binaries are installed in nightly smoke test: https://github.com/pytorch/pytorch/actions/runs/12134985467/job/33837475505#step:17:554

**Comment by jataylo** [comment]
They are built but  the pytorch wheel pulls the wrong triton as a dependency

```pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124```

```
Collecting torch
  Using cached https://download.pytorch.org/whl/nightly/cu124/torch-2.6.0.dev20241113%2Bcu124-cp310-cp310-linux_x86_64.whl (986.4 MB)
Collecting pytorch-triton==3.1.0+cf34004b8a (from torch)
  Using cached https://download.pytorch.org/whl/nightly/pytorch_triton-3.1.0%2Bcf34004b8a-cp310-cp310-linux_x86_64.whl (239.6 MB)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/envs/py_3.10/lib/python3.10/site-packages (from jinja2->torch) (3.0.2)
Installing collected packages: pytorch-triton, torch
Successfully installed pytorch-triton-3.1.0+cf34004b8a torch-2.6.0.dev20241113+cu124
```

Seems to pull  pytorch-triton 3.1.0+cf34004b8a instead of https://download.pytorch.org/whl/nightly/pytorch_triton_rocm-3.2.0%2Bgit35c6c7c6-cp310-cp310-linux_x86_64.whl
