### ISSUE TITLE
SDPA is not automatically choosing CUDNN impl on eligible hardware

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/pytorch#142132]
### 🐛 Describe the bug

According to PyTorch Release Note (https://pytorch.org/blog/pytorch2-5/), CUDNN backend for SDPA will be automatically enabled on eligible hardware. This is not the case, as Tritonbench shows that native sdpa impl is much slower than cudnn or flash_v3 on eligible H100:

```
$ python run.py --op flash_attention --batch 1 --n-heads 24 --seq-len 4608 --d-head 128 --only cudnn,sdpa,flash_v3 --metrics tflops --native-sdpa

  (Batch, Heads, SeqLen, Dhead)    sdpa-tflops    cudnn_90100-tflops    flash_v3-tflops
-------------------------------  -------------  --------------------  -----------------
             (1, 24, 4608, 128)        329.483               631.338            631.827
```

https://github.com/pytorch-labs/tritonbench/pull/97

https://github.com/pytorch-labs/tritonbench/issues/41

### Versions

Pytorch Nightly: 2.6.0.dev20241204+cu124

cc @drisspg @mikaylagawarecki

**Comment by drisspg** [comment]
This is expected, see: https://github.com/pytorch/pytorch/issues/141133

**Comment by xuzhao9** [comment]
Thanks! Closing this as it is duplicated in #141133
