### ISSUE TITLE
Fix broken jit tests in 3.13

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#142143]
https://github.com/pytorch/pytorch/pull/141605 skipped parts of a jit test in 3.13 because they fail.

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @seemethere @malfet @pytorch/pytorch-dev-infra @mruberry @ZainRizvi @albanD

**Comment by davidberard98** [comment]
Merge into https://github.com/pytorch/pytorch/issues/142012
