### ISSUE TITLE
[XPU] model works with 2.5.1 while break with nightly build

### ISSUE THREAD

**Issue by huiyan2021** [pytorch/pytorch#142123]
### 🐛 Describe the bug

HW: Arc770
OS: Windows

[Reproduce Code]
```
import stanza

pos_pipeline = stanza.Pipeline(lang='en', processors='tokenize,pos', use_gpu=True, device='xpu')
sentence = "This caused particular problems in cases involving abused women who killed their abusive husbands as case law demonstrates that they often involved a lapse in time between the provocation and the killing. Subsequent cases sought to extend the defence to battered women by accepting the notion of cumulative provocation and acknowledging that provocation might still be operating on the defendant’s mind, even after a lapse of time. Irrespective of this, there were still concerns that the requirement of a sudden and temporary loss of control made it too difficult for battered women to rely on this defence."
pos_pipeline(sentence)
```

[Environment which works]
conda create -n torch-xpu-2.5 python = 3.10 -y
conda activate torch-xpu-2.5
pip3 install torch --index-url https://download.pytorch.org/whl/test/xpu
pip install stanza

[Environment which does not work]
conda create -n torch-xpu-nightly python = 3.10 -y
conda activate torch-xpu-nightly
pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/xpu
pip install stanza

[Error]
![image](https://github.com/user-attachments/assets/83a119aa-21ca-47cd-ab4a-065f8f31d0ee)

After adding `weights_only=False`, op not implemented error 
![image](https://github.com/user-attachments/assets/5c4fb59a-cc44-40e1-a2e0-30bb12aee151)

### Versions

Collecting environment information...
PyTorch version: 2.6.0.dev20241204+xpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro (10.0.19045 64-bit)
GCC version: (GCC) 13.1.0

Clang version: Could not collect
CMake version: version 3.29.3
Libc version: N/A

Python version: 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:15:49) [MSC v.1941 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
----------------------
Name: Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
Manufacturer: GenuineIntel
Family: 179
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 1000
MaxClockSpeed: 2401
L2CacheSize: 24576
L2CacheSpeed: None
Revision: 21767
----------------------
Name: Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
Manufacturer: GenuineIntel
Family: 179
Architecture: 9
ProcessorType: 3
DeviceID: CPU1
CurrentClockSpeed: 1800
MaxClockSpeed: 2401
L2CacheSize: 24576
L2CacheSpeed: None
Revision: 21767

Versions of relevant libraries:
[pip3] numpy==2.1.3
[pip3] optree==0.13.1
[pip3] torch==2.6.0.dev20241204+xpu
[pip3] torchaudio==2.5.0.dev20241205+xpu
[pip3] torchvision==0.20.0.dev20241205+xpu
[conda] torch                     2.6.0.dev20241204+xpu          pypi_0    pypi
[conda] torchaudio                2.5.0.dev20241205+xpu          pypi_0    pypi
[conda] torchvision               0.20.0.dev20241205+xpu          pypi_0    pypi

cc @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by dvrogozh** [comment]
The error log in text form:
```
Traceback (most recent call last):
  File "/home/dvrogozh/tmp/st.py", line 3, in <module>
    pos_pipeline = stanza.Pipeline(lang='en', processors='tokenize,pos', use_gpu=True, device='xpu')
  File "/home/dvrogozh/pytorch.xpu/lib/python3.10/site-packages/stanza/pipeline/core.py", line 308, in __init__
    self.processors[processor_name] = NAME_TO_PROCESSOR_CLASS[processor_name](config=curr_processor_config,
  File "/home/dvrogozh/pytorch.xpu/lib/python3.10/site-packages/stanza/pipeline/processor.py", line 193, in __init__
    self._set_up_model(config, pipeline, device)
  File "/home/dvrogozh/pytorch.xpu/lib/python3.10/site-packages/stanza/pipeline/pos_processor.py", line 32, in _set_up_model
    self._trainer = Trainer(pretrain=self.pretrain, model_file=config['model_path'], device=device, args=args, foundation_cache=pipeline.foundation_cache)
  File "/home/dvrogozh/pytorch.xpu/lib/python3.10/site-packages/stanza/models/pos/trainer.py", line 34, in __init__
    self.load(model_file, pretrain, args=args, foundation_cache=foundation_cache)
  File "/home/dvrogozh/pytorch.xpu/lib/python3.10/site-packages/stanza/models/pos/trainer.py", line 174, in load
    emb_matrix = pretrain.emb
  File "/home/dvrogozh/pytorch.xpu/lib/python3.10/site-packages/stanza/models/common/pretrain.py", line 50, in emb
    self.load()
  File "/home/dvrogozh/pytorch.xpu/lib/python3.10/site-packages/stanza/models/common/pretrain.py", line 56, in load
    data = torch.load(self.filename, lambda storage, loc: storage)
  File "/home/dvrogozh/git/pytorch/pytorch/torch/serialization.py", line 1480, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
        (1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
        (2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
        WeightsUnpickler error: Unsupported global: GLOBAL numpy.core.multiarray._reconstruct was not an allowed global by default. Please use `torch.serialization.add_safe_globals([_reconstruct])` or the `torch.serialization.safe_globals([_reconstruct])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
```

@huiyan2021 : This issue is not specific to XPU, but is caused by the change in PyTorch itself coming to version 2.6. You should see that working with all other devices unless there is a different code path for XPU in stanza. This is caused by the flipping of default value for `weights_only` from `False` to `True` by https://github.com/pytorch/pytorch/pull/137602 and previous changes to require explicit allowlisted objects on `torch.load`. See https://pytorch.org/docs/stable/notes/serialization.html#torch.serialization.add_safe_globals.

I think the fix should be done on stanza side by creating a list of safe globals and passing it to pytorch. You can refer to the similar change done in Huggingface Transformers:
* https://github.com/huggingface/transformers/pull/34632

I recommend to open an issue in https://github.com/stanfordnlp/stanza repo and/or submitting a PR to stanza.

**Comment by dvrogozh** [comment]
I guess you can comment in this stanza issue:
* https://github.com/stanfordnlp/stanza/issues/1429

They are discussing the warning which now became an error due to the changes I explained above.

**Comment by huiyan2021** [comment]
Got it! Thanks @dvrogozh
