### ISSUE TITLE
"log_softmax_lastdim_kernel_impl" not implemented for 'torch.LongTensor'

### ISSUE THREAD

**Issue by HaleTom** [pytorch/pytorch#14224]
## 🐛 Bug

```
RuntimeError: "log_softmax_lastdim_kernel_impl" not implemented for 'torch.LongTensor'
```

## To Reproduce

```
torch.nn.functional.log_softmax(torch.arange(9), dim=0)
```

Gives:

```
~/.local/share/miniconda3/envs/nndl/lib/python3.6/site-packages/torch/nn/functional.py in log_softmax(input, dim, _stacklevel, dtype)
   1135         dim = torch.jit._unwrap_optional(dim)
   1136     if dtype is None:
-> 1137         ret = input.log_softmax(dim)
   1138     else:
   1139         _dtype = torch.jit._unwrap_optional(dtype)

RuntimeError: "log_softmax_lastdim_kernel_impl" not implemented for 'torch.LongTensor'
```

## Expected behavior

No error, same as if the tensor was of type double.

## Environment
```
PyTorch version: 1.0.0.dev20181116
Is debug build: No
CUDA used to build PyTorch: None

OS: Manjaro Linux
GCC version: (GCC) 8.2.1 20180831
CMake version: version 3.12.4

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch-cpu               0.4.1                py36_cpu_1    pytorch
[conda] pytorch-nightly-cpu       1.0.0.dev20181116     py3.6_cpu_0    pytorch
[conda] torchvision-cpu           0.2.1                    py36_1    pytorch
[conda] torchvision-nightly-cpu   0.2.1              pyh19dea27_0    fastai
```

**Comment by zou3519** [comment]
Softmax doesn't work on a long tensor -- convert it to a float or double tensor first (via `tensor.float()`)

**Comment by kuzand** [comment]
I also get RuntimeError: "softmax_lastdim_kernel_impl" not implemented for 'torch.IntTensor'.

Is there a reason why it's not implemented for integer tensors?

**Comment by zou3519** [comment]
@kuzand It doesn't make sense for it to be implemented for integers. Right now in PyTorch, the outputs are of the same type as the inputs. IF the inputs are integers, than the outputs would also be integers, but based on the softmax formula they would end up being between 0-1, which is not expressable with an int.

**Comment by fmassa** [comment]
note that once https://github.com/pytorch/pytorch/issues/9515 gets implemented, it might be worth revisiting this.

**Comment by Abhishekira** [comment]
if you are using a tensorflow to assign the array then check the  cases like use "torch.Tensor" properly where needed and it will solve the issue

**Comment by insightbuilder** [comment]
I had used torch.float16 for the input tensor like below.
```t1 = torch.tensor([5, 2, 87], dtype=torch.float16)
r1 = torch.tensor([8, 32, -27], dtype=torch.float16)
t2 = torch.tensor([756, 15, 327], dtype=torch.float16)
```
Got the same error with slight modification: "softmax_lastdim_kernel_impl" not implemented for 'Half'
Error got resolved after the float32 was used.
