### ISSUE TITLE
How can I use qmake to compile C++ application linking against OpenCV and libTorch?

### ISSUE THREAD

**Issue by jxmelody** [pytorch/pytorch#14223]
## To Reproduce

Similar to https://github.com/pytorch/pytorch/issues/13541 I'd like to use qmake to build but I still get some errors even if I added ```QMAKE_CXXFLAGS += -D_GLIBCXX_USE_CXX11_ABI=0```,

> /opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: cannot find -lnvrtc

the shared libraries I found  in path/to/libtorch/lib/  is only something like this:
>libnvrtc-007d19c9.so.9.0
  libnvrtc-builtins.so

So I thought  maybe I should linked this as ```-lnvrtc-007d19c9``` or ```-lnvrtc-builtins```  but after I did that the error still exist.

I tried cmake but when I add opencv to it , it can't find opencv's include file.
>fatal error: opencv2/core.hpp: no such a file or directory

## Environment

 - PyTorch Version (e.g., 1.0):**1.0**
 - OS (e.g., Linux):**centos**
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:3.7
 - CUDA/cuDNN version:9.0
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ShahriarSS** [comment]
@jxmelody 
The nvrtc dependency error got fixed when I added -lnvrtc. These are the libs that I add to my projects:

LIBS += -ltorch -lc10 -lnvrtc -lcaffe2 -lcuda -lopencv_core

You can see if these work in your case.

**Comment by ShahriarSS** [comment]
@jxmelody 
I checked and I have libnvrtc.so in /usr/lib64. maybe you can try something like:
LIBS += -L<path to libnvrtc.so directory>

**Comment by jxmelody** [comment]
@ShahriarSS 
Thank you! The problem have been solved, but still thanks !

**Comment by buduo15** [comment]
How did you finally solved this problem ? 
I added both QMAKE_CXXFLAGS += -D_GLIBCXX_USE_CXX11_ABI=0 and  -L/usr/local/cuda-9.2/lib64, besides the path of libtorch/lib for cpp is also added.

**Comment by bhusalsantosh** [comment]
@buduo15 
Were you able to solve the problem? I am having similar issues like yours.
