### ISSUE TITLE
MacOS wheels are no longer built with OpenMP runtime

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#142266]
### 🐛 Describe the bug

I.e.
```
python -c "import torch;print(torch.__version__, torch.backends.openmp.is_available())"
2.5.1 True
```
But
```
% python -c "import torch;print(torch.__version__, torch.backends.openmp.is_available())"
2.6.0.dev20241204 False
```

Hattip to @Jack-Khuu for reporting the problem

### Versions

nightly

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @osalpekar @atalman @albanD

**Comment by malfet** [comment]
Last successful build: 2.6.0.dev20241112 True
First failing build: 2.6.0.dev20241113 False

**Comment by malfet** [comment]
Blast from the past: https://github.com/pytorch/pytorch/issues/123225

**Comment by malfet** [comment]
And I believe I've found the offending PR https://github.com/pytorch/pytorch/pull/140491 (i.e. OpenMP discoverly logic is probably changed in cmake-3.31 and somehow it does not use `cmake/modules/FindOpenMP.cmake`

**Comment by Jack-Khuu** [comment]
Looks like https://github.com/pytorch/pytorch/pull/142277/files is addressing this, will test new wheels tomorrow

**Comment by janeyx99** [comment]
Assigning @malfet as a result of triage discussion to add a test to prevent further regressions

**Comment by Jack-Khuu** [comment]
Just tested 1210, doesn't still missing omp.h

**Comment by atalman** [comment]
Tested with torch final rc:
```
python -c "import torch;print(torch.__version__, torch.backends.openmp.is_available())"                           
2.6.0 True
```
