### ISSUE TITLE
cpu_tensor.std() is single-threaded

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#14220]
Should we do parallelized Welford? cc @zou3519 @colesbury

**Comment by zou3519** [comment]
Looks like we updated std() to use TensorIterator sometime in the past few years: https://github.com/pytorch/pytorch/blob/0e16087064bb1eac9f3b82fc1e47532aaf396ce9/aten/src/ATen/native/ReduceOps.cpp#L1443
