### ISSUE TITLE
Logspam from Dynamo handling context managers

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#142357]
### 🐛 Describe the bug

```
import torch
torch.set_default_device('cuda')
from triton.testing import do_bench


class DoNothing:
    def __enter__(self):
        return self
        
    def __exit__(self, exc_type, exc_val, exc_tb):
        pass

@torch.compile
def f(x):
    with DoNothing():
        x = x* 2
    return x

f(torch.randn(5))
```

results in
```
Fail to import hypothesis in common_utils, tests are not derandomized
```

This comes from here: https://github.com/pytorch/pytorch/blob/fa632766915a3d47e3ed9fe300616405d0802376/torch/_dynamo/variables/user_defined.py#L94-L95

cc: @guilhermeleobas @yanboliang @zou3519 

### Versions

N/A

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by zou3519** [comment]
I ran into this previously, where any warning thrown in Dynamo log-spams (instead of warns once) because Dynamo resets the current warning state

**Comment by zou3519** [comment]
Link to the issue where I ran into this previously: https://github.com/pytorch/pytorch/issues/128427

**Comment by zou3519** [comment]
Fix is simple, we should get this into the release branch so that external users don't see it

**Comment by kit1980** [comment]
I'm removing the milestone as the issue was already in 2.4 release and it's minor annoyance.
