### ISSUE TITLE
`index_select` on flat tensor faster than integer array indexing, even including reshaping

### ISSUE THREAD

**Issue by gngdb** [pytorch/pytorch#14231]
## 🐛 Bug

Integer array indexing appears to be slower than applying `index_select` to the flattened tensor, using flattened indexes, and then reshaping to the expected output size.

## To Reproduce

Reproduced in this gist: https://gist.github.com/gngdb/3d4f5aa27ee5199b0d4b997ffe21a6b4

## Expected behavior

If this is a faster way to implement integer array indexing, it should be the default. It might not be though, there are other uses for integer array indexing where this speed difference might not hold.

## Environment

PyTorch version: 0.4.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Scientific Linux release 7.5 (Nitrogen)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 390.87
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.2)
[pip] torch (0.4.1.post2)
[pip] torchvision (0.2.1)
[conda] pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by soumith** [comment]
this should be fixed after https://github.com/pytorch/pytorch/pull/13420 is merged

**Comment by fmassa** [comment]
#13420 has been merged, and most of the slowdown is over (at least for forward).
