### ISSUE TITLE
Add a bash script linter for -o pipefail

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#142380]
The idea comes from https://github.com/pytorch/pytorch/pull/142377, it's useful to have `-o pipefail` prevent a similar failure in other bash scripts.

There is also `-u` that ExecuTorch is using on their repo that we could adopt too.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ezyang

**Comment by nluu175** [comment]
Hey I wanna give this a try!

**Comment by Grove-YJX** [comment]
I'm a beginner. This task looks relatively easy to solve and I'd like to try it too！Thank you.
