### ISSUE TITLE
Consider not generating DeviceGuard wrappers automatically

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14234]
By default, ATen code generation will generate a DeviceGuard invocation,
which will ensure that kernel code will run with the current device set
to match the device of the first Tensor argument (or first tensor of
the first TensorList argument, if the function takes a list of tensors).
For the most part, this means kernel authors do not have to worry about
setting devices.

However, this means that sometimes we spend a lot of time uselessly setting device guards when it's unnecessary, as @zou3519 discovered while doing performance optimizations in #13049. So maybe it is better to NOT do device guards by default, and force kernel writers to only set it when necessary. We will have to be careful about this because it is very easy to forget to set device guards, and you won't notice unless you run the kernel on not device 0.

**Comment by zou3519** [comment]
After I mowed away some DeviceGuard calls, DeviceGuard overhead isn't noticeable anymore in the models I benchmarked (#13974), but I think this would be nice to prevent a situation in the future where we have a native function call DeviceGuard 5 times instead of 0-1.

**Comment by ezyang** [comment]
I think we're unlikely to do this.
