### ISSUE TITLE
UNSTABLE Lint / workflow-checks / linux-job

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#142485]
The jobs cancels as it times out when running:

```
 python3 /home/ec2-user/actions-runner/_work/pytorch/pytorch/test-infra/.github/scripts/run_with_env_secrets.py ''
```

cc @seemethere @malfet @pytorch/pytorch-dev-infra @huydhn

**Comment by huydhn** [comment]
The fix has been landed https://github.com/pytorch/pytorch/pull/142476, but I will keep this one open a bit as I think it will show up as a failure on PRs until people rebase to include the fix

**Comment by clee2000** [comment]
Can this be closed?

**Comment by huydhn** [comment]
Oops, I forgot to close this
