### ISSUE TITLE
Remove bitwise functions from floating point Tensors

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#1425]
Right now, all the bitwise operators are not really bitwise. They just assume that the ByteTensor contains 0 or 1.

https://github.com/pytorch/pytorch/blob/master/torch/tensor.py#L347-L387

Fix this by exposing the true bitwise functions already existing in TH/THC:
https://github.com/pytorch/pytorch/blob/701e63107fb3c177e83850a0389f0d6580d8fe45/torch/lib/TH/generic/THTensorMath.h#L42-L57
https://github.com/pytorch/pytorch/blob/b46d5e0b04e21f5bf9f3b24b43a7b3866be5ad90/torch/lib/THC/generic/THCTensorMathPairwise.h#L13-L15

**Comment by soumith** [comment]
thanks to @hmansell for catching this.

**Comment by stegben** [comment]
#1556
