### ISSUE TITLE
The same network get different inference time when initialize network with random value or pre-trained weight ?

### ISSUE THREAD

**Issue by VisionZQ** [pytorch/pytorch#14264]
### Please note that this issue tracker is not a help form and this issue will be closed.

I stack a network and have trained it well. Now, I test inference time of network that initialize with pre-trained weight, but it slower than initialization with random value in pytorch 0.4.0.

Then, I check the weight in the two condition. 
Case A, initialize with random value as follow:
It seems that fixed-point;
![image](https://user-images.githubusercontent.com/22951577/48824464-5ebfa100-ed9f-11e8-8384-36531cda2ce3.png)

CaseB, initialize with pre-trained weight as follow:
It seems that float-point;
![image](https://user-images.githubusercontent.com/22951577/48824528-857dd780-ed9f-11e8-9526-6377a176b157.png)

I'm not very good at floating-point arithmetic in pytorch or other framework, but I intuition guess that there maybe some issue?

Thank you for your time and suggestion. 

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soumith** [comment]
> Please note that this issue tracker is not a help form and this issue will be closed.
