### ISSUE TITLE
Can't import pytorch 1.0 "ImportError: /lib64/libc.so.6: version 'GLIBC_2.14'"

### ISSUE THREAD

**Issue by curry111** [pytorch/pytorch#14274]
Hi :sweat_smile: , I installed pytorch 1.0 but when I imported it in python, I saw this error
`File "<stdin>", line 1, in <module> `                                                                 
`File "/home/qwe123/data/conda_packages/lib/python3.6/site-packages/torch/__init__.py",` `line 84, in 
 <module>`
    `from torch._C import *`
`ImportError: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /home/qwe123/data/conda_packages/lib/python3.6/site-packages/torch/lib/libshm.so)`

I used pytorch 4.0 without any problems with python 3.6
`ldd --version` gives me `ldd (GNU libc) 2.12`
`lsb_release -a` prints `CentOS release 6.8 (Final)`
I use CUDA 8 and Cudnn 7

**Comment by soumith** [comment]
Our binaries do not support centos 6 since 0.4.1 and going forward.
You can compile PyTorch from source: https://github.com/pytorch/pytorch#from-source or upgrade atleast to CentOS 7
