### ISSUE TITLE
th.norm and th.renorm `dim` arg is switched?

### ISSUE THREAD

**Issue by ncullen93** [pytorch/pytorch#1427]
It seems that to renormalize a tensor along the 1st axis, you have to use `th.renorm` along the 0th axis. Is this expected behavior?

```python
x = th.randn(5,10)
print(th.norm(x,2,1))

# 3.8096
# 3.1135
# 2.9162
# 2.0999
# 3.5506
#[torch.FloatTensor of size 5x1]

# doesnt work
print(th.norm(th.renorm(x,2,1,3),2,1))
# 3.7102
# 3.0592
# 2.7382
# 2.0993
# 3.5030
#[torch.FloatTensor of size 5x1]

# does work
print(th.norm(th.renorm(x,2,0,3),2,1))
# 3.0000
# 3.0000
# 2.9162
# 2.0999
# 3.0000
#[torch.FloatTensor of size 5x1]
```

**Comment by apaszke** [comment]
`renorm` is a weird function (it's not clipping a norm along a given dim), and should be probably deprecated and renamed to sth else. It's basically looping over the dim you give it, viewing all (n-dimensional) slices as vectors and clipping their norm.
