### ISSUE TITLE
Why t.arange(0,3) create an int type Tensor?

### ISSUE THREAD

**Issue by MrGreensjtu** [pytorch/pytorch#14275]
## Code example
x=torch.autograd.Variable(t.arange(0,3),requires_grad=True)

RuntimeError: Only Tensors of floating point dtype can require gradients

The default type is floatTensor, how this bug happens?

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version : 0.4.1
 - OS : windows
 - How you installed PyTorch :conda
 - IDE: Jupyter notebook
 - Python version: 3.6.2

**Comment by soumith** [comment]
torch.arange returns an int64 tensor by defaut. It mimics numpy behavior. if you want different dtype, give dtype as argument, such as `t.arange(0, 3, dtype=torch.float32)`
