### ISSUE TITLE
[selective activation checkpoint && compiled autograd] Trying to backward an extra time. You are only allowed to backward once on any region computed under selective activation checkpoint.

### ISSUE THREAD

**Issue by yyp0** [pytorch/pytorch#142862]
### 🐛 Describe the bug

When we integrating compiled autograd with selective activation checkpointing as follows:
```python
class mlp(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(10, 10)
        self.layer2 = nn.Linear(10, 10)
        self.layer3 = nn.Linear(10, 10)
        self.layer4 = nn.Linear(10, 10)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        return x

recompute_list = [torch.ops.aten.addmm.default]
def recompute_policy(ctx, op, *args, **kwargs):
    if op in recompute_list:
        return CheckpointPolicy.MUST_RECOMPUTE
    else:
        return CheckpointPolicy.PREFER_SAVE

def context_fn():
    return create_selective_checkpoint_contexts(recompute_policy)

model = mlp().cuda()
input = torch.randn(1, 10).cuda()

for i in range(1):
    out = torch.utils.checkpoint.checkpoint(model, input, use_reentrant=False, context_fn=context_fn)
    with torch._dynamo.compiled_autograd._enable(torch.compile(backend=my_compiler, fullgraph=True)):
        out.sum().backward()
```
The following runtime error is thrown:
```python
Trying to backward an extra time. You are only allowed to backward once on any region computed under selective activation checkpoint.
```
It seems that the number of `PREFER_SAVE`op whose output should be saved in the forward pass is different from the times it occurs in the backward pass.

### Versions

[pip3] numpy==1.26.4
[pip3] optree==0.13.1
[pip3] torch==2.6.0a0+git9b0c3e4
[conda] Could not collect

cc @soulitzer @chauhang @penguinwu @xmfan @yf225

**Comment by xmfan** [comment]
I have a PR to make this stop erroring. 

Btw as of now, compiled autograd doesn't work well with non reentrant checkpointing APIs (that use unpack hooks). Activations marked for recomputation are all recomputed at the start of the backward for compiled autograd, so I don't expect there to be big memory savings if any. We are in the process of landing a pre-requisite change to add support for actual memory savings from checkpointing

**Comment by yyp0** [comment]
> I have a PR to make this stop erroring.
> 
> Btw as of now, compiled autograd doesn't work well with non reentrant checkpointing APIs (that use unpack hooks). Activations marked for recomputation are all recomputed at the start of the backward for compiled autograd, so I don't expect there to be big memory savings if any. We are in the process of landing a pre-requisite change to add support for actual memory savings from checkpointing

Thanks for your work! We are also very curious about when this feature will be supported, looking forward to your reply!

**Comment by xmfan** [comment]
I have a tracking issue here: https://github.com/pytorch/pytorch/issues/143176

**Comment by yyp0** [comment]
> I have a PR to make this stop erroring.
> 
> Btw as of now, compiled autograd doesn't work well with non reentrant checkpointing APIs (that use unpack hooks). Activations marked for recomputation are all recomputed at the start of the backward for compiled autograd, so I don't expect there to be big memory savings if any. We are in the process of landing a pre-requisite change to add support for actual memory savings from checkpointing

Is it possible delaying unpack hooks execution and making all behavior the same as eager?
