### ISSUE TITLE
[Caffe2] Failing to run "./scripts/build_android.sh -DANDROID_TOOLCHAIN=clang"

### ISSUE THREAD

**Issue by Suhail** [pytorch/pytorch#14280]
## 🐛 Bug

I am trying to get this to run: https://github.com/t-vi/AICamera/ -- currently the only supported implementation of AICamera it appears out there since the other one is old & has many compilation issues.

I am following this blog post: https://lernapparat.de/pytorch-android/

When I run ./scripts/build_android.sh -DANDROID_TOOLCHAIN=clang I get this failure:
https://gist.github.com/Suhail/2802c407a2899bae7ba6e8dba9d5ca76

Any ideas? 

Info:

```
Collecting environment information...
PyTorch version: 1.0.0a0+f34c848
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch                   0.4.1           py36_cuda0.0_cudnn0.0_1    pytorch
[conda] pytorch-nightly           1.0.0.dev20181029         py3.6_0    pytorch
[conda] pytorch-nightly-cpu       1.0.0.dev20181014         py3.6_0    pytorch
[conda] torch                     1.0.0a0+f34c848           <pip>
[conda] torch                     0.4.0                     <pip>
[conda] torch                     0.3.1                     <pip>
[conda] torchtext                 0.2.3                     <pip>
[conda] torchvision               0.2.1                     <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch
[conda] torchvision-nightly       0.2.1                     <pip>
[conda] torchvision-nightly-cpu   0.2.1              pyh19dea27_0    fastai

clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

cc: @t-vi

**Comment by t-vi** [comment]
Looks more like a non C++11 / too old clang version to me than a caffe2 bug per se, but others would know better and unfortunately, the clang version isn't printed. Note that this is in the "build host protoc" (=on and for OS X) stage, not in the Android bits/toolchain.

**Comment by t-vi** [comment]
Yeah, I usually do Linux (Debian/sid), it probably used gcc 8 or somesuch.
Your version looks new enough, maybe you could try to convince cmake to pass  `-std=c++11` to clang?

**Comment by Suhail** [comment]
I think I changed it correctly in cmake (I am no compiler/cmake expert):
```
cat third_party/protobuf/cmake/CMakeLists.txt
# Minimum CMake required
cmake_minimum_required(VERSION 2.8.12)
set (CMAKE_CXX_STANDARD 11)

if(protobuf_VERBOSE)
  message(STATUS "Protocol Buffers Configuring...")
endif()
```

Seems like a different error now? https://gist.github.com/Suhail/7ac633dce6ac6415c533bce311b16966

**Comment by soumith** [comment]
Fixed on master via @ljk53 's PRs
