### ISSUE TITLE
MacOS libtorch builds are failing since Nov 12

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#142873]
### 🐛 Describe the bug

See https://hud.pytorch.org/hud/pytorch/pytorch/3bcdb4ed6b7b9d9b19806d2442d8cf7a1e428af8/1?per_page=50&name_filter=macos-arm64-binary-libtorch&mergeLF=true

MacOS nightly builds are failing https://github.com/pytorch/pytorch/actions/runs/12271730101/job/34239111301

### Versions

nightly

cc @seemethere @malfet @osalpekar @atalman @pytorch/pytorch-dev-infra @albanD

**Comment by malfet** [comment]
@jeanschmidt please do not use `ciflow` labels on issues, they are exclusively for adding extra CI workflows on pull requests

**Comment by malfet** [comment]
Grabbing for myself, as I guess they are related to MacOS OpenMP regression
