### ISSUE TITLE
macos-py3-arm64 / test (default, 3, 3, macos-m1-stable) doesn't generate usage stats

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#142877]
### 🐛 Describe the bug

https://hud.pytorch.org/test/insights?jobName=macos-py3-arm64%20%2F%20test%20(default%2C%203%2C%203%2C%20macos-m1-stable)&workflowId=12279573709&jobId=34264707261

macos-py3-arm64 / test (default, 3, 3, macos-m1-stable)

The job didn't generate any usage stats, so there is nothing to analyze. Please submit an issue to PyTorch Dev Infra team.

I'm wondering if this should have gone to test-infra repo, but the link pointed me here?

cc @seemethere @malfet @pytorch/pytorch-dev-infra @huy

### Versions

main

**Comment by malfet** [comment]
I think the repo is right, unless it doesn't work for all workflows, then it's a HUD (and therefore test-infra issue)

**Comment by ZainRizvi** [comment]
The test insights page has been removed, with a new replacement insights page coming 
https://github.com/pytorch/test-infra/pull/6031
