### ISSUE TITLE
vector<T> too long and crash on module->forward, other errors when loading TorchScript model in C++

### ISSUE THREAD

**Issue by aman-tiwari** [pytorch/pytorch#14299]
## 🐛 Bug

I'm trying to load a torchscript module serialized as in the tutorial, but I get `vector<T> too long` when trying to print the modules in the model, as well as a crash if `model->forward` is called:

## To Reproduce

Serialize model as in the tutorial:
```python
(piptorch) C:\...\>python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchvision
>>> model = torchvision.models.resnet18()
>>> example = torch.rand(1, 3, 224, 224)
>>> traced_script_module = torch.jit.trace(model, example)
>>> output = traced_script_module(torch.ones(1, 3, 224, 224))
>>> output[0, :5]
tensor([-0.3891, -0.0314,  0.4143,  0.0229,  0.0064], grad_fn=<SliceBackward>)
>>> traced_script_module.save("model.pt")
>>> exit()
```

My C++ code looks like this:

```cpp
#include "pch.h"
#include <torch/script.h> // One-stop header.
#include <iostream>
#include <memory>
#include "ConsoleApplication1.h"


int main(int argc, const char* argv[]) {
	if (argc != 2) {
		std::cerr << "usage: example-app <path-to-exported-script-module>\n";
		return -1;
	}
	std::cout << "loading: " << argv[1] << '\n';
	std::ifstream in(argv[1], std::ios_base::binary);
	// Deserialize the ScriptModule from a file using torch::jit::load().
	try {
		std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(in);
		in.close();

		assert(module != nullptr);

		auto mods = module->get_modules();
		for (const auto& m : mods) {
			std::cout << m.key() << "\n";
		}

		c10::Device gpu(c10::DeviceType::CUDA, 0);
		module->to(gpu);

		std::cout << "module moved to gpu ok\n";

		torch::jit::Stack inputs;
		auto tensor = torch::ones({ 1, 3, 224, 224 }).to(gpu);
		inputs.push_back(tensor);

		std::cout << "inputs constructed ok\n";

		module->forward(inputs);
		std::cout << "ok\n";
	}
	catch (c10::Error e) {
		in.close();
		std::cerr << e.what() << "\n";
	}
	catch (std::exception exn) {
		in.close();
		std::cerr << exn.what() << "\n";
	}
}
```

But when I run the above I get: 
```powershell
PS C:\Users\a\Documents\libtorch-shared-with-deps-1.0\proj\x64\Debug> .\ConsoleApplication1.exe model.pt
loading: model.pt
vector<T> too long
```

If I remove the get_modules line and the part that prints the module names, I get:

```powershell
PS C:\Users\a\Documents\libtorch-shared-with-deps-1.0\proj\x64\Debug> .\ConsoleApplication1.exe model.pt
loading: model.pt
module moved to gpu ok
inputs constructed ok
PS C:\Users\a\Documents\libtorch-shared-with-deps-1.0\proj\x64\Debug>
```
(i.e, a crash when module->forward() is called)

If I run it in the VS2017 debugger, the crash happens in `std::unordered_map``:
![err0](https://user-images.githubusercontent.com/8798016/48873214-c20afc80-edba-11e8-91d9-af977f24a470.PNG)

Walking up the stacktrace to torch's code:
![err1](https://user-images.githubusercontent.com/8798016/48873223-ccc59180-edba-11e8-8bab-6a8641902e7c.PNG)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).
```
Collecting environment information...
PyTorch version: 1.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Home
GCC version: Could not collect
CMake version: version 3.13.0-rc1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070 With Max-Q Design
Nvidia driver version: 411.70
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     1.0                       <pip>
[conda] torchvision               0.2.1                     <pip>
```

NB: I installed Pytorch 1.0 & LibTorch from https://github.com/peterjc123/pytorch-scripts as I couldn't find an official module or [get it to build myself](https://github.com/pytorch/pytorch/issues/14203)

## Additional context

I had some `'std' ambiguous symbol` errors in some of the headers when I included them in visual studio 2017, of the form `std::vector ...` and `std::unordered_map ...`. I had to convert them to `::std::vector ... and ::std::unordered_map ...` to get it to work.

**Comment by mnboos** [comment]
I have the same problem and any help would be welcome.

**Comment by goldsborough** [comment]
@aman-tiwari @mnboos I will try to reproduce it. Did you investigate whether `module->get_modules().size()` was something unreasonable? The symbol errors sound a bit scary. Could you file a separate issue for it so our Windows experts can take a look? Thanks.

**Comment by mnboos** [comment]
`module->get_modules().size()` returned `304072116609` 🤔

**Comment by aman-tiwari** [comment]
I had a similarly large value in the debugger for the size field in the unordered_map, but my crash is on module->get_modules(), so I don't think I can call module->get_modules().size()

**Comment by Victordmdb** [comment]
The problem seems related to the [extending of std namespace](https://en.cppreference.com/w/cpp/language/extending_std) which seems to only be available for c++20 standard, so a solution might be to change `c++11` to `c++20` at https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L1015, but the compiler would also need to be compatible with that standard.

**Comment by aman-tiwari** [comment]
This isn't for building a c++ extension but instead for building libtorch.

**Comment by soumith** [comment]
cc: @suo @zdevito for visibility / ideas. Also see https://github.com/pytorch/pytorch/issues/14402

**Comment by suo** [comment]
Will take a look in the morning!

**Comment by hyklv** [comment]
Related to #15236 ? Does the crash not occur in a Release build?

**Comment by peterjc123** [comment]
In MSVC, the Debug build and the Release build is not ABI-compatible. So would you please try whether it is reproducible on the Release build?

**Comment by Gr4ph1c** [comment]
> In MSVC, the Debug build and the Release build is not ABI-compatible. So would you please try whether it is reproducible on the Release build?

So  in the next version, Will release the Debug Build?

**Comment by suo** [comment]
Closing as the issue has been found and docs have been updated to reflect that release/debug are not ABI-compatible.

**Comment by peterjc123** [comment]
@Gr4ph1c Now we start to distribute the debug build for CPU, CUDA 9.0 and CUDA 10.0. Please have a try.
