### ISSUE TITLE
torch.randn generate different result on a100 vs h100

### ISSUE THREAD

**Issue by JiancongWang** [pytorch/pytorch#143086]
### 🐛 Describe the bug

Hi, I found that torch.randn generate different random numbers on a100 vs h100 when the sequence length is long. 

`python -c "import torch; generator=torch.Generator('cuda'); generator.manual_seed(1); print(torch.randn(1, 49 * 12 * 112 * 144, device='cuda', generator=generator))"`

h100:
tensor([[-0.2963,  2.6764, -0.1408,  ..., -0.6970, -0.7780,  0.3267]]

a100:
tensor([[-0.2963,  2.6764, -0.1408,  ...,  0.1549, -0.6797, -0.1656]]

Could somebody points me to the actual cuda code inside the pytorch codebase? Thanks! 

### Versions

torch 2.5.1

**Comment by ngimel** [comment]
That's expected https://github.com/pytorch/pytorch/blob/8dce421442667602f79e9871f89792529e9b835d/aten/src/ATen/native/cuda/DistributionTemplates.h#L148
