### ISSUE TITLE
The results of torch.lu_solve are inconsistent between CPU and GPU.

### ISSUE THREAD

**Issue by deepliao** [pytorch/pytorch#143096]
### 🐛 Describe the bug

Different with [#107542](https://github.com/pytorch/pytorch/issues/107542)，we find torch.lu_solve have a different result when run in GPU and CPU without a large negative input tensor.

And this bug has not been resolved yet.

Code:
```
import torch

A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
b = torch.tensor([[1, 2, 3]], dtype=torch.float32).t()
(LU_data, LU_pivots) = torch.lu(A)

x = torch.lu_solve(b, LU_data, LU_pivots)
print(x)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

if torch.cuda.is_available():
    A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32, device=device)
    b = torch.tensor([[1, 2, 3]], dtype=torch.float32, device=device).t()

    LU_data, LU_pivots = torch.lu(A)

    x = torch.lu_solve(b, LU_data, LU_pivots)

    x_cpu = x.cpu()
    print(x_cpu)
```
The result is different !
```
tensor([[-0.3333],
        [ 0.6667],
        [ 0.0000]])
Using device: cuda
tensor([[ 2.1287e-08],
        [-1.9868e-08],
        [ 3.3333e-01]])

```

### Versions

PyTorch version: 2.5.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 专业版 (10.0.22631 64 位)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: False
CUDA runtime version: 11.2.67
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 560.94
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Name: 13th Gen Intel(R) Core(TM) i7-13700K
Manufacturer: GenuineIntel
Family: 198
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 3400
MaxClockSpeed: 3400
L2CacheSize: 24576
L2CacheSpeed: None
Revision: None

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.26.4
[pip3] numpydoc==1.5.0
[pip3] onnxruntime==1.19.2
[pip3] optree==0.11.0
[pip3] rapidocr-onnxruntime==1.3.24
[pip3] torch==2.5.1
[pip3] torchattacks==3.5.1
[conda] blas                      1.0                         mkl    defaults      
[conda] mkl                       2023.1.0         h8bd8f75_46356    defaults      
[conda] mkl-service               2.4.0           py311h2bbff1b_1    defaults      
[conda] mkl_fft                   1.3.6           py311hf62ec03_1    defaults      
[conda] mkl_random                1.2.2           py311hf62ec03_1    defaults      
[conda] numpy                     1.24.3          py311hdab7c0b_1    defaults      
[conda] numpy-base                1.24.3          py311hd01c5d8_1    defaults      
[conda] numpydoc                  1.5.0           py311haa95532_0    defaults

**Comment by ZhaoqiongZ** [comment]
Hi @deepliao , A is a singular matrix, there is no unique solution, result from CPU and CUDA are both correct.

**Comment by deepliao** [comment]
Thank you very much; you are really appreciated. @ZhaoqiongZ
