### ISSUE TITLE
Python's math module is a footgun: Add a warning or error message when applying certain math module functions to tensors

### ISSUE THREAD

**Issue by joshdavham** [pytorch/pytorch#143071]
### 🚀 The feature, motivation and pitch

I was training a custom non-neural network model with pytorch this last week and was applying functions on my tensors such as `math.exp` and `math.pow`. Needless to say, this ultimately led to some unexpected behavior where my gradients weren't propagating correctly. I had no idea that functions from python's math module such as `math.exp` could break things and that functions from the torch module like `torch.exp` had to be swapped in place for things to work. I also didn't receive any kind of warning or error message from pytorch which ultimately could've helped me a lot.

I think it could be a great feature if there was some sort of warning or error message when attempting to apply certain math module functions on tensors during training. For example:

```python
import torch
import math

x = torch.tensor(2.0, requires_grad=True)
y = math.exp(x)
"""
RuntimeError: math.exp is not currently a tensor supported operation. Please use torch.exp instead.
"""
```

I don't know if this idea is all that radical given that you currently get a similar error when you try to use `copy.deepcopy` on graph leaves. I assume that this was also to prevent some sort of footgun.
```python
import torch
from copy import deepcopy

x = torch.tensor(2.0, requires_grad=True)
x = x+1
y = deepcopy(x)
"""
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment.  If you were attempting to deepcopy a module, this may be because of a torch.nn.utils.weight_norm usage, see https://github.com/pytorch/pytorch/pull/103001
"""
```

Anyways, let me know what you think or if you have any questions 👍

cc @ezyang @albanD @gqchen @pearu @nikitaved @soulitzer @Varal7 @xmfan

**Comment by ezyang** [comment]
@albanD don't we give warnings when you convert requires_grad=True tensors into non autograd tracked quantities? Maybe we only do it on conversion to Numpy 🤔

**Comment by Isalia20** [comment]
@ezyang  If you try to do conversion to numpy(of a tensor that requires grad) it gives an error:
`RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead`

I believe same should be done if math.exp() is called on a tensor. Submitted a PR to include the fix

**Comment by albanD** [comment]
We don't warn on `.item()` on a Tensor that requires grad indeed. I think the assumption that user would not expect python number to support auotgrad (contrary to numpy arrays which look very similar to Tensors).
But maybe it is just an oversight

**Comment by joshdavham** [comment]
@albanD 

I'm still relatively new to pytorch, but since
```python
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
```
is a valid operation.

And because
```python


x = torch.tensor(2.0, requires_grad=True)
y = math.pow(x,2)
```
does not cause an error. 

While
```python
x = torch.tensor(2.0, requires_grad=True)
y = np.pow(x,2)
# > RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

does cause an errror. 

I think it's reasonable to consider something like `math.pow` and `math.exp` a footgun.

Of course most people are using pytorch for deep learning models and large matrices, there are still users like me who use it to optimize relatively small custom models and I think we're the most likely demographic to be shooting ourselves in the foot with python's `math` module.

**Comment by albanD** [comment]
I'm a bit concerned with the BC-breaking implication of making this one an error tbh. I don't have a good grasp on how many of our users might be doing this today (and expecting it continue working).

Adding a warning sounds fair given the current numpy behavior. This warning can be added here https://github.com/pytorch/pytorch/blob/fe9365f3f575beeca64d1cef8fe0d3e3fed05195/aten/src/ATen/native/Scalar.cpp#L18 using TORCH_WARN.
Would you be able to send a PR with this?

**Comment by joshdavham** [comment]
@albanD 

> I'm a bit concerned with the BC-breaking implication of making this one an error tbh

I think that's fair.

> Would you be able to send a PR with this?

Sure thing!

**Comment by albanD** [comment]
Ho we are doing a bunch of .item() there to get python number with the Tensor content.
Did you make sure to check both requires_grad=True and grad_mode enabled similarly to what is done here though: https://github.com/pytorch/pytorch/blob/f406207af2bad07c294badef24c2f56680e74442/aten/src/ATen/native/MaxPooling.cpp#L86 ?
All the printing should run under no_grad() and it is fine not to warn in that case as you don't expect gradients to be tracked, even if you're using the math module.

**Comment by joshdavham** [comment]
@albanD 

I think the issue actually traces back to `TORCH_WARN`.

For example, as a test, in Scalar.cpp, if I write
```cpp
Scalar item(const Tensor& self) {
  auto numel = self.sym_numel();
  TORCH_WARN(1==1, "warning!"); // << here
  if (self.is_sparse()) {
    if (self._nnz() == 0) return Scalar(0);
    if (self.is_coalesced()) return at::_local_scalar_dense(self._values());
    return at::_local_scalar_dense(self._values().sum());
  } else if (self.is_quantized()) {
    return self.dequantize().item();
  } else {
    return _local_scalar_dense(self);
  }
}
```

and then after compiling, I go back to python with the previous example, I get:
```python
import torch

x = torch.tensor(2.0, requires_grad=True)
x
"""
/Users/joshuahamilton/open-source/pytorch/torch/_tensor_str.py:145: UserWarning: 1warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  nonzero_finite_vals = torch.masked_select(
/Users/joshuahamilton/open-source/pytorch/torch/_tensor_str.py:159: UserWarning: 1warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  if value != torch.ceil(value):
/Users/joshuahamilton/open-source/pytorch/torch/_tensor_str.py:167: UserWarning: 1warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  nonzero_finite_max / nonzero_finite_min > 1000.0
/Users/joshuahamilton/open-source/pytorch/torch/_tensor_str.py:168: UserWarning: 1warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  or nonzero_finite_max > 1.0e8
/Users/joshuahamilton/open-source/pytorch/torch/_tensor.py:1097: UserWarning: 1warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  return self.item().__format__(format_spec)
/Users/joshuahamilton/open-source/pytorch/torch/_tensor_str.py:225: UserWarning: 1warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)

tensor(2., requires_grad=True)
"""
```

But if I go back and change the following and recompile:
```cpp
Scalar item(const Tensor& self) {
  auto numel = self.sym_numel();
  TORCH_WARN(1==2, "still a warning message!"); // << here
  if (self.is_sparse()) {
    if (self._nnz() == 0) return Scalar(0);
    if (self.is_coalesced()) return at::_local_scalar_dense(self._values());
    return at::_local_scalar_dense(self._values().sum());
  } else if (self.is_quantized()) {
    return self.dequantize().item();
  } else {
    return _local_scalar_dense(self);
  }
}
```

then run the python program again, I still get a warning message.
```python
import torch

x = torch.tensor(2.0, requires_grad=True)
x
"""
/Users/joshuahamilton/open-source/pytorch/torch/_tensor_str.py:145: UserWarning: 1still a warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  nonzero_finite_vals = torch.masked_select(
/Users/joshuahamilton/open-source/pytorch/torch/_tensor_str.py:159: UserWarning: 1still a warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  if value != torch.ceil(value):
/Users/joshuahamilton/open-source/pytorch/torch/_tensor_str.py:167: UserWarning: 1still a warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  nonzero_finite_max / nonzero_finite_min > 1000.0
/Users/joshuahamilton/open-source/pytorch/torch/_tensor_str.py:168: UserWarning: 1still a warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  or nonzero_finite_max > 1.0e8
/Users/joshuahamilton/open-source/pytorch/torch/_tensor.py:1097: UserWarning: 1still a warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  return self.item().__format__(format_spec)
/Users/joshuahamilton/open-source/pytorch/torch/_tensor_str.py:225: UserWarning: 1still a warning message! (Triggered internally at /Users/joshuahamilton/open-source/pytorch/aten/src/ATen/native/Scalar.cpp:18.)
  return formatter1.format(self.item())

tensor(2., requires_grad=True)
"""
```

I'm guessing this isn't expected behavior for `TORCH_WARN`?

**Comment by Isalia20** [comment]
AFAIK TORCH_WARN doesn't have a statement checker inside of it. It's just used to output a warning message. You can first check this with if statement:
`!(at::GradMode::is_enabled() && tensor.requires_grad()), ` 
in your code and then throw a warning if this is satisfied
