### ISSUE TITLE
CUDA 12.6 update and CUDA 12.1 CI/CD Deprecation Tracker

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#143139]
### 🐛 Describe the bug

This is tracker issue which list of PR's for CUDA 12.6 update/ CUDA 12.1 deprecation

### Versions

2.6.0 nightly

**Comment by malfet** [comment]
Not sure why you've closed it, as there are still CUDA-12.1 jobs running in CI right now, see https://hud.pytorch.org/hud/pytorch/pytorch/9f5ebf3fc609105a74eab4ccc24932d6353ff566/1?per_page=50&name_filter=12.1&mergeLF=true
