### ISSUE TITLE
Crash with complex64 tensors and einsum on mps

### ISSUE THREAD

**Issue by James-F1dev** [pytorch/pytorch#143140]
### 🐛 Describe the bug

I'm working with complex valued tensors on mps. 

In my network I have a function that simply does:

`weights = torch.view_as_complex(weights)`
`return torch.einsum("bixyz,ioxyz->boxyz", Input, weights)`

Input is shape 1,16,24,24,24, complex64
weights is shape 16,24,24,24 (after torch.view_as_complex) complex64

This crashes Python, with the following message:

(mpsFileLoc): /AppleInternal/Library/BuildRoots/4b66fb3c-7dd0-11ef-b4fb-4a83e32a47e1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:137:0: error: 'mps.gather' op operand #0 must be tensor of mps native type values, but got 'tensor<2162688xcomplex<f32>>'
(mpsFileLoc): /AppleInternal/Library/BuildRoots/4b66fb3c-7dd0-11ef-b4fb-4a83e32a47e1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:137:0: note: see current operation: %38 = "mps.gather"(%34, %36, %37) <{batch_dims = 0 : ui32}> : (tensor<2162688xcomplex<f32>>, tensor<221184xsi32>, tensor<si32>) -> tensor<221184xcomplex<f32>>
(mpsFileLoc): /AppleInternal/Library/BuildRoots/4b66fb3c-7dd0-11ef-b4fb-4a83e32a47e1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:137:0: error: 'mps.gather' op operand #0 must be tensor of mps native type values, but got 'tensor<2162688xcomplex<f32>>'
(mpsFileLoc): /AppleInternal/Library/BuildRoots/4b66fb3c-7dd0-11ef-b4fb-4a83e32a47e1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:137:0: note: see current operation: %38 = "mps.gather"(%34, %36, %37) <{batch_dims = 0 : ui32}> : (tensor<2162688xcomplex<f32>>, tensor<221184xsi32>, tensor<si32>) -> tensor<221184xcomplex<f32>>
/AppleInternal/Library/BuildRoots/4b66fb3c-7dd0-11ef-b4fb-4a83e32a47e1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphExecutable.mm:988: failed assertion `original module failed verification'
/var/folders/p9/y3pw6wws17z1vf8r12lv3ml40000gn/T/spyder-james/tmpdkad8_ea: line 3:  1508 Abort trap: 6           /opt/anaconda3/envs/pytorch/bin/python -Xfrozen_modules=off -m spyder_kernels.console -f /Users/james/Library/Jupyter/runtime/kernel-d94981e9deec.json

The kernel died, restarting...
 

Fatal Python error: Aborted

Main thread:
Current thread 0x00000001ff8cb840 (most recent call first):
  File "/opt/anaconda3/envs/pytorch/lib/python3.12/site-packages/torch/functional.py", line 402 in einsum

### Versions

PyTorch version: 2.5.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.1.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:22:19) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-15.1.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3

Versions of relevant libraries:
[pip3] configmypy==0.2.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==2.0.1
[pip3] tensorly-torch==0.5.0
[pip3] torch==2.5.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[conda] numpy                     2.0.1           py312h7f4fdc5_1  
[conda] numpy-base                2.0.1           py312he047099_1  
[conda] pytorch                   2.5.1                  py3.12_0    pytorch
[conda] tensorly-torch            0.5.0                    pypi_0    pypi
[conda] torchaudio                2.5.1                 py312_cpu    pytorch
[conda] torchvision               0.20.1                py312_cpu    pytorch

cc @ezyang @anjali411 @dylanbespalko @mruberry @nikitaved @amjames @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by NripeshN** [comment]
Just tried running a sample code on my M2 Max MacBook Pro

```py
import torch

device = torch.device("mps")

input_tensor = torch.randn(1, 16, 24, 24, 24, dtype=torch.float32, device=device) + \
               1j * torch.randn(1, 16, 24, 24, 24, dtype=torch.float32, device=device)

weights_real = torch.randn(16, 24, 24, 24, dtype=torch.float32, device=device)
weights_imag = torch.randn(16, 24, 24, 24, dtype=torch.float32, device=device)
weights = torch.complex(weights_real, weights_imag)

weights = weights.unsqueeze(0)

try:
    result = torch.einsum("bixyz,ioxyz->boxyz", input_tensor, weights)
    print("Yaay")
except Exception as e:
    print("Einsum operation failed with exception:", e)
```
It seems to work for me though. Not sure what is going on though.

**Comment by NripeshN** [comment]
> I also did some tests and it works with random tensors. 
> 
> It also works if I run it with the real data but just in the terminal, outside of the main network. 
> 
> 
> 
> Not sure what's going on here either, but it is reproducible every time. 
> 
> It also works fine (training and inference) on CUDA on Windows. 
> 
> That might be relevant (but not sure why) the model was trained on CUDA and I'm running inference on mps. 
> 
> 
> 
> Any more info I can provide?

This seems like an issue with how MPS handles complex tensors, especially when loading weights trained on CUDA. The error suggests a mismatch in the tensor’s internal representation. Switching devices can sometimes carry over metadata like dtype or precision, which might not translate cleanly between CUDA and MPS.

To debug, try:
	1.	Moving the model to CPU first, then to MPS (model.to('cpu') -> model.to('mps')).
	2.	Ensuring all tensors are float32 and on MPS.
	3.	Reinitializing weights directly on MPS, e.g., torch.complex(real.to('mps'), imag.to('mps')).

This could also be an MPS-specific bug since the backend is less mature than CUDA. If these steps don’t work, the problem might need deeper investigation.

**Comment by NripeshN** [comment]
Can we try these as I am unable to replicate this error on machine:
- Turn off autocast specifically for the `einsum` operation:  
   ```python
   with torch.autocast('mps', enabled=False):
       result = torch.einsum("bixyz,ioxyz->boxyz", input_tensor, weights)
   ```

-  Explicitly set `complex64` for both tensors before passing them to `einsum`:  
   ```python
   input_tensor = input_tensor.to(dtype=torch.complex64, device='mps')
   weights = weights.to(dtype=torch.complex64, device='mps')
   ```

- If we’re sure autocast is the issue, we can test modifying the `einsum` registration in the [MPS backend](https://github.com/pytorch/pytorch/blob/b29fc52f827cc4b4336ecd24cc0a019ec9cf24b6/aten/src/ATen/autocast_mode.cpp#L229) to use `fp32` instead of `lower_precision_fp`:  
   ```cpp
   KERNEL_MPS(einsum, fp32)
   ```

**Comment by NripeshN** [comment]
> Is doing training and inference on different backends usually robust? Or a bit wobbly?

Training on one backend and doing inference on another is usually fine, but it can be wobbly when the backends handle certain edge cases (like complex tensors) differently. CUDA is more mature, so MPS might be struggling here.

**Comment by NripeshN** [comment]
One last thing you can try is force einsum to run on CPU

```py
result = torch.einsum("bixyz,ioxyz->boxyz", input_tensor.cpu(), weights.cpu())
```

**Comment by malfet** [comment]
@James-F1dev do you mind `torch.save({'weights': weights, "inputs": inputs}, "weights_n_inputs.pt")` before the crash and post them here?

**Comment by malfet** [comment]
One line reproducer:
```
% python3 -c "import torch;rc = torch.einsum('bixyz,ioxyz->boxyz', torch.rand(1, 16, 64, 33, 24, dtype=torch.complex64, device='mps')[:,:,:24,:24,], torch.rand(16, 24, 24, 24, 24, dtype=torch.complex64, device='mps'))"
```

**Comment by NekoAsakura** [comment]
@malfet I can reproduce this issue. It may be caused by the tensor is non-contiguous. If you haven’t started working on it yet, I’d be happy to take on this issue.

**Comment by malfet** [comment]
@James-F1dev what are you trying to run? And do you mind creating a separate issue for the correctness?
