### ISSUE TITLE
[docs] Typo in torch.full_like docs

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#14322]
https://pytorch.org/docs/master/torch.html?highlight=full#torch.full_like :

```Returns a tensor with the same size as input filled with fill_value. torch.full_like(input, fill_value) is equivalent to torch.full_like(input.size(), fill_value, dtype=input.dtype, layout=input.layout, device=input.device).```

Should it not be `equivalent to torch.full(...`?

**Comment by SsnL** [comment]
fixed in #14324
