### ISSUE TITLE
Network outage on ROCm runners

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#143233]
## Current Status
Ongoing

## Mitigation

ROCm jobs have been marked as unstable for the time being:

* https://github.com/pytorch/pytorch/issues/143232
* https://github.com/pytorch/pytorch/issues/143231
* https://github.com/pytorch/pytorch/issues/143230
* https://github.com/pytorch/pytorch/issues/143246

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

**Comment by pruthvistony** [comment]
Seeing NW issue in one of the labs where the CI machines are hosted.

**Comment by huydhn** [comment]
This has been resolved, I'm moving ROCm jobs back now.
