### ISSUE TITLE
how to check number of gpu availability in pytorch

### ISSUE THREAD

**Issue by snake-plant-care-indoors** [pytorch/pytorch#143382]
1. **Import PyTorch**:  
   ```python
   import torch
   ```

2. **Check CUDA Availability**: Verify if CUDA is available on your system.  
   ```python
   torch.cuda.is_available()
   ```

3. **Get GPU Count**: Use the function to check the number of GPUs available.  
   ```python
   torch.cuda.device_count()
   ```

4. **Print GPU Count**: Display the number of GPUs in your system.  
   ```python
   print(f"Number of GPUs available: {torch.cuda.device_count()}")
   ```

5. **List GPU Names**: Loop through available GPUs and print their names.  
   ```python
   for i in range(torch.cuda.device_count()):
       print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
   ```

6. **Check Current Device**: Find which GPU is currently active.  
   ```python
   torch.cuda.current_device()
   ```

7. **Select a Specific GPU**: Specify a GPU by its index (if multiple are available).  
   ```python
   torch.cuda.set_device(0)  # Use GPU 0
   ```

8. **Check Memory Allocated**: View how much memory is being used on a specific GPU.  
   ```python
   print(torch.cuda.memory_allocated(0))
   ```

9. **Check Memory Reserved**: See the total reserved memory on a GPU.  
   ```python
   print(torch.cuda.memory_reserved(0))
   ```

10. **Run a Simple Test**: Run a small PyTorch tensor operation on a GPU to confirm availability.  
    ```python
    x = torch.rand(3, 3).cuda()  # Moves tensor to GPU
    print(x)
    ```

**Comment by malfet** [comment]
This does not look like an issue, please use https://discuss.pytorch.org/ to share your receipies on how to use PyTorch
