### ISSUE TITLE
no member named 'shared_ptr' in namespace 'std'

### ISSUE THREAD

**Issue by zhanghang1989** [pytorch/pytorch#1434]
When building from source, I got this error. My system is OSX 10.12.4, conda, CUDA 8.0. Any thoughts? Thanks!
```
torch/csrc/serialization.cpp:2:10: fatal error: 'system_error' file not found
#include <system_error>
         ^
In file included from torch/csrc/autograd/engine.cpp:1:
```
```
pytorch/torch/csrc/autograd/function_hook.h:11:40: error: no member named 'shared_ptr' in namespace 'std'
using variable_list = std::vector<std::shared_ptr<Variable>>;
                                  ~~~~~^
/Users/hangzhang/pytorch/torch/csrc/autograd/function_hook.h:11:51: error: 'Variable' does not refer to a value
using variable_list = std::vector<std::shared_ptr<Variable>>;
```

**Comment by soumith** [comment]
can you try adding `#include <memory>` to the file `pytorch/torch/csrc/autograd/function_hook.h` and see if that fixes things? if so i'll commit it.

**Comment by soumith** [comment]
actually, that file already has memory included.

Are you following instructions from https://github.com/pytorch/pytorch#from-source
Especially: 
```
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install
```

This part is important: `MACOSX_DEPLOYMENT_TARGET=10.9 `

**Comment by zhanghang1989** [comment]
`MACOSX_DEPLOYMENT_TARGET=10.9` works nicely! Thanks a lot!
