### ISSUE TITLE
OpenGL interoperability

### ISSUE THREAD

**Issue by cajoek** [pytorch/pytorch#143419]
### 🚀 The feature, motivation and pitch

Zero-copy transfer of data between PyTorch and OpenGL on GPU by including "OpenGL interoperability" from CUDA in pytorch.

I am working on a real-time machine learning graphics project which uses OpenGL both as an intermediate processing step in the model and to visualize the output. Right now transfer of data between PyTorch and OpenGL is a problem for both training and inference.
Without any additional packages i can copy data from PyTorch CUDA to CPU and then back to OpenGL on GPU, this is very simple but slow.
I can instead use some cuda bindings for python and a separate CUDA Toolkit installation to avoid the data transfer but this is quite complex and there are many competing ways and tools for doing this which makes it hard to navigate.

Old similar issue: https://github.com/pytorch/pytorch/issues/20047
Crosspost: https://github.com/pytorch/vision/issues/8803

### Additional context

The 2 main ways I have been using OpenGL from python are with the packages `moderngl` and `PyOpenGL`.

cc @ptrblck @msaroufim @eqy

**Comment by malfet** [comment]
It feels like a great topic to bing up to https://dev-discuss.pytorch.org/

**Comment by cajoek** [comment]
Alright! https://dev-discuss.pytorch.org/t/opengl-interoperability/2696

**Comment by malfet** [comment]
Considering that OpenGL is a kind of deprecated standard right now, closing the issue, but if someone wants to write a change to implement it, would be happy to review

**Comment by cajoek** [comment]
@malfet maybe Vulkan is a better bet then? Is there something like that already? Seems like Vulkan was a backend for PyTorch before

**Comment by bobbyshop-vui** [comment]
yes, that right but vulkan only for inference
