### ISSUE TITLE
PyTorch example with ONNX/Caffe2 causes an assertion error

### ISSUE THREAD

**Issue by phalexo** [pytorch/pytorch#14347]
## 🐛 Bug
I don't know if the warning below is related to the accuracy problem or not.

/home/developer/anaconda3/envs/PyTorch/lib/python3.6/site-packages/onnx_caffe2/backend.py:521: UserWarning: This version of onnx-caffe2 targets ONNX operator set version 2, but the model we are trying to import uses version 9.  We will try to import it anyway, but if the model uses operators which had BC-breaking changes in the intervening versions, import will fail.
  warnings.warn("This version of onnx-caffe2 targets ONNX operator set version {}, but the model we are trying to import uses version {}.  We will try to import it anyway, but if the model uses operators which had BC-breaking changes in the intervening versions, import will fail.".format(cls._known_opset_version, imp.version))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-3704b893e848> in <module>
     22 
     23 # Verify the numerical correctness upto 3 decimal places
---> 24 np.testing.assert_almost_equal(torch_out.data.cpu().numpy(), c2_out, decimal=3)
     25 
     26 print("Exported model has been executed on Caffe2 backend, and the result looks good!")

~/.local/lib/python3.6/site-packages/numpy/testing/_private/utils.py in assert_almost_equal(actual, desired, decimal, err_msg, verbose)
    566     if isinstance(actual, (ndarray, tuple, list)) \
    567             or isinstance(desired, (ndarray, tuple, list)):
--> 568         return assert_array_almost_equal(actual, desired, decimal, err_msg)
    569     try:
    570         # If one of desired/actual is not finite, handle it specially here:

~/.local/lib/python3.6/site-packages/numpy/testing/_private/utils.py in assert_array_almost_equal(x, y, decimal, err_msg, verbose)
    971     assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
    972              header=('Arrays are not almost equal to %d decimals' % decimal),
--> 973              precision=decimal)
    974 
    975 

~/.local/lib/python3.6/site-packages/numpy/testing/_private/utils.py in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    787                                 verbose=verbose, header=header,
    788                                 names=('x', 'y'), precision=precision)
--> 789             raise AssertionError(msg)
    790     except ValueError:
    791         import traceback

AssertionError: 
Arrays are not almost equal to 3 decimals

(mismatch 99.87975659013605%)
 x: array([0.484, 0.482, 0.51 , ..., 0.317, 0.28 , 0.208], dtype=float32)
 y: array([0.484, 0.403, 2.066, ..., 0.451, 0.39 , 0.208], dtype=float32)

**Comment by phalexo** [comment]
Now I have another problem. When I run the code within Jupyter notebook, it kills the kernel.

jupyter notebook
[I 18:36:34.156 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 2f2b9b3f-0c58-4b8d-aed3-f3c08c33135f restarted
[I 18:36:54.953 NotebookApp] Saving file at /PyTorchToCaffe2.ipynb

**Comment by ngimel** [comment]
Closing due to age
