### ISSUE TITLE
osx-64/pytorch pypi nightly build segfault

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#14359]
**update**: this started as something else and evolved into debugging a segfault on macos pypi pytorch build. Jump to the main content of this issue here: https://github.com/pytorch/pytorch/issues/14359#issuecomment-441924230

------

Hi,

osx-64/pytorch-nightly-cpu is not being updated on conda. 

The last release was made 1.0.0.dev20181014. pytorch-nightly is being updated on osx-64, but not pytorch-nightly-cpu. 

See: https://anaconda.org/pytorch/pytorch-nightly-cpu/files (not being updated)
and: https://anaconda.org/pytorch/pytorch-nightly/files (being updated)

Thank you.

**Comment by stas00** [comment]
Thank you, @soumith. 

Would it be sensible to then delete osx-64/pytorch-nightly-cpu from conda? otherwise it's now misleading users into installing osx-64/pytorch-nightly-cpu, as nightly, except it's very outdated. 

Our CI was configured to install it and there was no way we could have detected this change on your side. The detection happened thanks to another problem which I'm investigating now, which happened on pypi build but not on conda.

I'm double checked that https://pytorch.org/get-started/locally/ gives the correct instructions. So this issue will affect only users who configured their install scripts prior to 20181014.

**Comment by stas00** [comment]
I see you removed the outdated osx-64/pytorch-nightly-cpu from conda, so all is good now. Thank you.

**Comment by stas00** [comment]
And a related question, @soumith.

What's the difference between conda built cpu package for osx and pypi?

We have one of the tests segfaulting on osx with pypi pytorch package for cpu, but it works just fine with the same version of pytorch from conda.


```
tests/test_vision_data_block.py:96:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
fastai/basic_data.py:115: in one_batch
    try:     x,y = next(iter(dl))
fastai/basic_data.py:47: in __iter__
    for b in self.dl:
/Users/vsts/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/torch/utils/data/dataloader.py:631: in __next__
    idx, batch = self._get_batch()
/Users/vsts/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/torch/utils/data/dataloader.py:610: in _get_batch
    return self.data_queue.get()
/Users/vsts/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/multiprocessing/queues.py:94: in get
    res = self._recv_bytes()
/Users/vsts/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/multiprocessing/connection.py:216: in recv_bytes
    buf = self._recv_bytes(maxlength)
/Users/vsts/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/multiprocessing/connection.py:407: in _recv_bytes
    buf = self._recv(4)
/Users/vsts/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/multiprocessing/connection.py:379: in _recv
    chunk = read(handle, remaining)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

signum = 20, frame = <frame object at 0x1050e8048>

    def handler(signum, frame):
        # This following call uses `waitid` with WNOHANG from C side. Therefore,
        # Python can still get and update the process status successfully.
>       _error_if_any_worker_fails()
E       RuntimeError: DataLoader worker (pid 1201) is killed by signal: Unknown signal: 0.

/Users/vsts/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/torch/utils/data/dataloader.py:274: RuntimeError
----------------------------- Captured stderr call -----------------------------
ERROR: Unexpected segmentation fault encountered in worker.
```

**Comment by soumith** [comment]
@stas00 the pypi package is linked to Accelerate BLAS, and the conda package is linked to MKL BLAS. That's the only difference that I remember / can think of.

Any possibility of getting a stack-trace for the segfault?

**Comment by 313v** [comment]
does this work as a stack-trace? looks to me like its dying in addmm

[Python_2018-11-27-135247_tulip.crash.txt](https://github.com/pytorch/pytorch/files/2621458/Python_2018-11-27-135247_tulip.crash.txt)

**Comment by stas00** [comment]
@soumith, is the backtrace provided by @313v sufficient to identify the problem? I eventually managed to get one on the CI machine too and it's identical to the one he provided.

**Comment by soumith** [comment]
hey both. the stack-trace is sufficient, except that I am not sure why it's segfaulting there.
The reason I say I'm not sure is because it's segfaulting deep inside Apple's Accelerate library.

Can you tell me how you installed `numpy`, and what BLAS it's linked against?
I'm wondering if the BLAS library that `numpy` is linked against is somehow different (openblas or MKL) and maybe interfering with the linkage in the PyTorch case

**Comment by stas00** [comment]
It got installed via fastai dependency (pip), quoting the log:

```
Collecting numpy>=1.12 (from fastai)
2018-11-26T15:47:19.0157820Z   Downloading https://files.pythonhosted.org/packages/74/68/2b00ba3c7390354db2a1706291750b6b7e911f6f79c0bd2184ae04f3c6fd/numpy-1.15.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (24.5MB)
```

I unzipped it. I'm not sure which of the files in the package to check. Perhaps this is the info you're after?

`./.dylibs/libopenblasp-r0.3.0.dev.dylib`

`openblas` that is?

**Comment by jph00** [comment]
@soumith apparently there are known issues with using `fork` with Accelerate. e.g. see https://stackoverflow.com/questions/23963997/python-child-process-crashes-on-numpy-dot-if-pyside-is-imported . The only solution I've found is to use OpenBLAS instead. Should PyTorch use OpenBLAS by default on Mac OS perhaps?

**Comment by stas00** [comment]
And then the conda pytorch + conda numpy has no such conflict. Looking at `numpy-base`'s conda package - I think it is linked against `mkl`, since it has `_mklinit.cpython-36m-darwin.so` file in there. 

You can compare:

https://anaconda.org/anaconda/numpy-base/1.15.4/download/osx-64/numpy-base-1.15.4-py36h8a80b8c_0.tar.bz2 

It's odd they use different libraries for pypi and conda packages, isn't it?

**Comment by stas00** [comment]
And to make things even more inconsistent, conda-forge's numpy is linked against openblas!
https://github.com/conda-forge/numpy-feedstock/issues/84
So most likely on macos conda-forge's numpy and conda's pytorch will have the same problem.

**Comment by stas00** [comment]
Also, is there a pytorch config option to give user the information about the  blas library it's linked against (other than looking through ldd and such)? I don't see it here:
https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
I'm looking for something like:

```
python -c 'import numpy; numpy.__config__.show()' 
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/stas/anaconda3/envs/pytorch-dev/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/stas/anaconda3/envs/pytorch-dev/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/stas/anaconda3/envs/pytorch-dev/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/stas/anaconda3/envs/pytorch-dev/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/stas/anaconda3/envs/pytorch-dev/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/stas/anaconda3/envs/pytorch-dev/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/stas/anaconda3/envs/pytorch-dev/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/stas/anaconda3/envs/pytorch-dev/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/stas/anaconda3/envs/pytorch-dev/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/stas/anaconda3/envs/pytorch-dev/include']
```

**Comment by stas00** [comment]
@soumith, so what is the conclusion, document that:

  Do not use pytorch's pypi build on macos unless you get numpy build linked with the same blas library (openblas).

or are you still thinking about a possible resolution?

**Comment by soumith** [comment]
I've been thinking about it, but have been busy with final release.

I think I want to do the following:

- move to the cblas API (instead of blas API) for `dot` (which returns a scalar, and openblas / mkl / accelerate when mixed with each other give undefined behavior, and can even result in incorrect answers)
- always link with MKL in macos binaries, regardless of pip or conda

**Comment by ngimel** [comment]
Closing due to age
