### ISSUE TITLE
[Caffe2] Caffe2 for Android has no include files

### ISSUE THREAD

**Issue by rivergold** [pytorch/pytorch#14353]
## 🐛 Bug

After using **scripts/build_android.sh** build caffe2 for Android, the libs are ok, but there are no include files.

## To Reproduce

Follow [Caff2 installation website](https://caffe2.ai/docs/getting-started.html?platform=android&configuration=compile)

1. `git clone --recursive https://github.com/pytorch/pytorch.git` and then  `git submodule update --init`
2. Change `scripts/build_android.sh` to build with **clang** (new NDK doesn't support gcc) and bash **scripts/build_android.sh**
3. Build, and no include files.

I have tried to copy the whole caffe2 folder into my Android project or copy **libtorch** include files, but it will cause lots of errors.

## Environment

- Ubuntu 18.04
- Android studio 3.2.1
- NDK r16.0

**Comment by rivergold** [comment]
@wangnamu Thanks a lot. I have solved this problem based on your project.

**Comment by gemfield** [comment]
This issule has been fixed in the official repo.
