### ISSUE TITLE
Bug in transferring model from pytorch --> caffe2

### ISSUE THREAD

**Issue by SPark9625** [pytorch/pytorch#14351]
## 🐛 Bug

I'm following through this tutorial:

 [TRANSFERING A MODEL FROM PYTORCH TO CAFFE2 AND MOBILE USING ONNX](https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html)

The problem is that pytorch's network output and that of caffe2 differ. Just before the section on "TRANSFERING SRRESNET USING ONNX", there is this code, which asserts that the pytorch's output and caffe2's output are almost equal:
```
# Verify the numerical correctness upto 3 decimal places
np.testing.assert_almost_equal(torch_out.data.cpu().numpy(), c2_out, decimal=3)

print("Exported model has been executed on Caffe2 backend, and the result looks good!")
```

But I get an error here.

```
AssertionError: 
Arrays are not almost equal to 3 decimals

(mismatch 99.87665639172336%)
 x: array([ 0.387,  0.309,  0.082, ..., -0.089,  0.169,  0.215], dtype=float32)
 y: array([ 0.387, -0.231,  0.363, ...,  1.092, -0.429,  0.215], dtype=float32)
```

I output the arrays and manually checked that they are indeed quite different.

I have one suspect for this problem. When I import onnx_caffe2, I get a warning that says

```
UserWarning: This version of onnx-caffe2 targets ONNX operator set version 2, but the model
we are trying to import uses version 9.  We will try to import it anyway, but if the model uses
operators which had BC-breaking changes in the intervening versions, import will fail.
```
... which has an issue opened just a couple of hours ago (#14347)

## To Reproduce

Even just downloading [this code](https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html#sphx-glr-download-advanced-super-resolution-with-caffe2-py) and running it straight away reproduces the problem for me. I'm not sure what is the exact source of problem, so I'll just list my environment.

## Environment

PyTorch version: 1.0.0a0+60e7d04
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.1
GCC version: Could not collect
CMake version: version 3.12.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by SPark9625** [comment]
Oh and by the way,

onnx-caffe2: pip installed
onnx: built from source (master branch)
pytorch: also built from source (master)

Just tried uninstalling pytorch and installing from the v1.0rc1 branch, but there, there is no `torch.onnx.symbolic.pixel_shuffle`, so it seems I do have to install from the current master branch (Latest commit 60e7d04)

**Comment by SPark9625** [comment]
Since `onnx-caffe2` is now archived, I also tried it with `caffe2.python.onnx.backend`, but still get this exact same error

**Comment by SPark9625** [comment]
I modified the tutorial and removed the `pixel_shuffle` part and composed the network only with ReLU and conv layers (just to see if `pytorch` and `caffe2` give the same output), and now it works fine.

Since `pixel_shuffle` is only on the master branch, I assume that it's still buggy?
Anyway, I'll just test if all the layers I personally need output the same thing between the two frameworks and proceed.

**Comment by paullu** [comment]
I am sure it is a bug now ! The bug happens when exporting pixel_shuffle layer.

`@parse_args('v', 'i')
def pixel_shuffle(g, self, upscale_factor):
    dims = self.type().sizes()
    if len(dims) != 4:
        return _unimplemented("pixel_shuffle", "only support 4d input")
    output_channel = dims[1] // upscale_factor // upscale_factor
    # after_view = view(g, self, [-1, upscale_factor, upscale_factor,
                                output_channel, dims[2], dims[3]])
   after_view = view(g, self, [-1, output_channel,upscale_factor, upscale_factor,
                                dims[2], dims[3]])
    after_transpose = g.op("Transpose", after_view, perm_i=[0, 1, 4, 2, 5, 3])
    return view(g, after_transpose,
                [-1, output_channel, dims[2] * upscale_factor, dims[3] *
                 upscale_factor])`

it would fix

**Comment by ulisesbussi** [comment]
> I found the bug happens when exporting pixel_shuffle layer.
> see the python file in onnx/symbolic.py
> 
> ```
> def pixel_shuffle(g, self, upscale_factor):
>     dims = self.type().sizes()
>     if len(dims) != 4:
>         return _unimplemented("pixel_shuffle", "only support 4d input")
>     output_channel = dims[1] // upscale_factor // upscale_factor
>     # after_view = view(g, self, [-1, upscale_factor, upscale_factor,
>                                 output_channel, dims[2], dims[3]])
>    after_view = view(g, self, [-1, output_channel,upscale_factor, upscale_factor,
>                                 dims[2], dims[3]])
>     after_transpose = g.op("Transpose", after_view, perm_i=[0, 1, 4, 2, 5, 3])
>     return view(g, after_transpose,
>                 [-1, output_channel, dims[2] * upscale_factor, dims[3] *
>                  upscale_factor])
> ```
> 
> it would fix

Sorry, i cant find onnx/symbolic.py are you refering to pythonx.x/site-packages/onnx/ folder? i have no symbolic.py

**Comment by ailias** [comment]
> I found the bug happens when exporting pixel_shuffle layer.
> see the python file in onnx/symbolic.py
> 
> ```
> def pixel_shuffle(g, self, upscale_factor):
>     dims = self.type().sizes()
>     if len(dims) != 4:
>         return _unimplemented("pixel_shuffle", "only support 4d input")
>     output_channel = dims[1] // upscale_factor // upscale_factor
>     # after_view = view(g, self, [-1, upscale_factor, upscale_factor,
>                                 output_channel, dims[2], dims[3]])
>    after_view = view(g, self, [-1, output_channel,upscale_factor, upscale_factor,
>                                 dims[2], dims[3]])
>     after_transpose = g.op("Transpose", after_view, perm_i=[0, 1, 4, 2, 5, 3])
>     return view(g, after_transpose,
>                 [-1, output_channel, dims[2] * upscale_factor, dims[3] *
>                  upscale_factor])
> ```
> 
> it would fix

Yes, It solved the bugs for me when I update the pixel_shuffle function. Thank you very much.

**Comment by ailias** [comment]
> > I found the bug happens when exporting pixel_shuffle layer.
> > see the python file in onnx/symbolic.py
> > ```
> > def pixel_shuffle(g, self, upscale_factor):
> >     dims = self.type().sizes()
> >     if len(dims) != 4:
> >         return _unimplemented("pixel_shuffle", "only support 4d input")
> >     output_channel = dims[1] // upscale_factor // upscale_factor
> >     # after_view = view(g, self, [-1, upscale_factor, upscale_factor,
> >                                 output_channel, dims[2], dims[3]])
> >    after_view = view(g, self, [-1, output_channel,upscale_factor, upscale_factor,
> >                                 dims[2], dims[3]])
> >     after_transpose = g.op("Transpose", after_view, perm_i=[0, 1, 4, 2, 5, 3])
> >     return view(g, after_transpose,
> >                 [-1, output_channel, dims[2] * upscale_factor, dims[3] *
> >                  upscale_factor])
> > ```
> > 
> > 
> > it would fix
> 
> Sorry, i cant find onnx/symbolic.py are you refering to pythonx.x/site-packages/onnx/ folder? i have no symbolic.py

Maybe you should update pytorch to 1.0.1 version

**Comment by shbnm21** [comment]
Verify the numerical correctness upto 3 decimal places
np.testing.assert_almost_equal(torch_out.data.cpu().numpy(), c2_out, decimal=3)

print("Exported model has been executed on Caffe2 backend, and the result looks good!")


On running this function I am getting following error
Attribute Error:'Nonetype' object has no attribute 'data'


W
