### ISSUE TITLE
Caffe 2 build failure for Android

### ISSUE THREAD

**Issue by deepankar1994** [pytorch/pytorch#14354]
## 🐛 Bug
With 
`CMAKE_ARGS+=("-DBUILD_SHARED_LIBS=ON")` the following error is observed 
```
../../lib/libprotobuf.a(common.cc.o): In function `google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)':
pytorch/third_party/protobuf/src/google/protobuf/stubs/common.cc:142: undefined reference to `__android_log_write'
```
## To Reproduce
Used NDK 17b.
Set
`CMAKE_ARGS+=("-DBUILD_SHARED_LIBS=ON")`
in `scripts/build_android.sh `line 67
then 
`./build_android.sh -DANDROID_ABI=arm64-v8a -DANDROID_TOOLCHAIN=clang`

**Comment by t-vi** [comment]
Can you see whether the invocations uses `-llog` as an argument?

**Comment by soumith** [comment]
Fixed on master via @ljk53 's PRs
