### ISSUE TITLE
Expose timeout kwarg for init_process_group in torch.distributed

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#14376]
Per #14297 we can timeout individual ops instead of having one timeout for all of them. This is useful for when you have parts of a program with wildly varying runtime (e.g. some data loading or preprocessing) and need a barrier with a 30 minute timeout, but also want fast fault detection in your training loop.

**Comment by teng-li** [comment]
@pietern Let's just do this in `init_process_group`, instead of per collective operation

**Comment by pietern** [comment]
We already have it in init_process_group, see https://github.com/pytorch/pytorch/blob/0651b594d805a5d4fa51cca4dd360a55ed87670a/torch/distributed/distributed_c10d.py#L347-L351

**Comment by teng-li** [comment]
what I was saying was, let's add this as an option in `init_process_group` and `new_group`, currently, it uses the default pg timeout

**Comment by pietern** [comment]
Ah, yes, good point, I missed that it didn't pull it from the kwargs. Working on a PR.

**Comment by pietern** [comment]
Updated to reflect we're only doing the timeout kwarg on a per process group basis (`init_process_group` and `new_group`) instead of per collective (at first). This is only supported when using the Gloo backend right now, so this should be reflected in the documentation.

**Comment by teng-li** [comment]
Let's also include documentation in this issue, including timeout only works for Gloo at this point.
