### ISSUE TITLE
FlightRecorderEventTest::test_all_events is flaky

### ISSUE THREAD

**Issue by lw** [pytorch/pytorch#143798]
### 🐛 Describe the bug

The test test/distributed/flight_recorder/test_fr_analysis.py::FlightRecorderEventTest::test_all_events is flaky.

You can see here a sample failure: https://github.com/pytorch/pytorch/actions/runs/12470584195/job/34807434998?pr=143747.

This flakiness was introduced in https://github.com/pytorch/pytorch/pull/143354. I left a comment on that PR explaining where it comes from.

I'm applying a band-aid in https://github.com/pytorch/pytorch/pull/143747, but this test needs to be rewritten in order to make sense.

### Versions

main branch

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @clee2000 @wdvr

**Comment by c-p-i-o** [comment]
Fix is landing in https://github.com/pytorch/pytorch/pull/143878

**Comment by c-p-i-o** [comment]
Fix landed in #143878
