### ISSUE TITLE
Flex attention with nested tensors, bug in `create_nested_block_mask`

### ISSUE THREAD

**Issue by VivekPanyam** [pytorch/pytorch#143788]
The following code is from `_nested_mod_func_adapter` which is a helper function used by `create_nested_block_mask`. Conceptually, it wraps a mod function that operates on individual batch items of a nested tensor and transforms the inputs so it works on a single packed item. However, the below code doesn't appear to update the batch argument (`b`) before calling the original mod function.

https://github.com/pytorch/pytorch/blob/6ccb8ed1868984d9d2ea4e48a085508d1027cd9b/torch/nn/attention/flex_attention.py#L985-L990

Since `create_nested_block_mask` effectively packs all the batch items from the nested tensor into a single item, it appears like the helper should do something like `b_nested = q_seq_idx[q_idx]` and pass that in place of `b` to `orig_mod_func`.

Otherwise, it appears that the wrapped mod func has no way of knowing which batch item it's operating on.

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @soulitzer @davidberard98 @YuqingJ @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @yf225 @Chillee @yanboliang @BoyuanFeng

**Comment by oulgen** [comment]
cc @Chillee

**Comment by jbschlosser** [comment]
@VivekPanyam Thanks for the report! Good catch, I agree with your assessment; will put in a fix. Do you have a use case involving batch-specific attention mod that I can use to validate the fix?
