### ISSUE TITLE
python setup.py build fails after commit 9169f60

### ISSUE THREAD

**Issue by brunoalr** [pytorch/pytorch#1437]
After the commit `Parallelize TensorMethods.cpp builds`  `python setup.py build` fails on both ppc64 and x64 server (i.e. with lots of CPU cores) machines with the following messages:

```
x86_64-linux-gnu-gcc: error: /home/brosa/pytorch/torch/csrc/generated/TensorDouble.cpp: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fs
tack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/brosa/pytorch -I/home/brosa/pytorch/torch/csrc -I/home/brosa/pytorch/torch/lib/tmp_install/include -I/home/brosa/pytorch/torch/lib/t
mp_install/include/TH -I/home/brosa/pytorch/torch/lib/tmp_install/include/THPP -I/home/brosa/pytorch/torch/lib/tmp_install/include/THNN -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/incl
ude/python2.7 -c /home/brosa/pytorch/torch/csrc/generated/TensorFloat.cpp -o build/temp.linux-x86_64-2.7/home/brosa/pytorch/torch/csrc/generated/TensorFloat.o -D_THP_CORE -std=c++11 -Wno-write-strings
-DWITH_NUMPY
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
x86_64-linux-gnu-gcc: error: /home/brosa/pytorch/torch/csrc/generated/TensorFloat.cpp: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
```

This does not seem to happen when running `python setup.py build develop`.
I am building on ppc64le VM with 16 cores and a x64 bare-metal machine with 20 cores.

**Comment by soumith** [comment]
what's the command you are using to build?
`python setup.py install` ?

Please see if cleaning helps: `python setup.py clean`

I've been working on x64 server, so i cant think of why that would happen.

**Comment by brunoalr** [comment]
I'm using `python setup clean build`

**Comment by brunoalr** [comment]
I tried `git clean -xdf` before building as well.

**Comment by soumith** [comment]
you need to do `build develop`. Not just `build`

**Comment by brunoalr** [comment]
Will try! It's weird that before this commit, `python setup.py build` worked with no problems, though.

**Comment by brunoalr** [comment]
`python setup.py build develop` seems to work.

**Comment by apaszke** [comment]
I just ran `python setup.py build` on a clean repo and it completed successfully. Can you confirm this is resolved now (even if you don't use `develop`)?

**Comment by brunoalr** [comment]
Yes, it works! Thanks.
