### ISSUE TITLE
[caffe2] How to run graph only till first layer and not further?

### ISSUE THREAD

**Issue by pjavia-iterativescopes** [pytorch/pytorch#14385]
Example in TensorFlow

sess.run([tensor_1, tensor_2, feed_dict:{}])
Output of any layer can be obtained without running the whole graph.
How to do the similar thing in caffe2?

**Comment by yinghai** [comment]
We have this:
https://github.com/pytorch/pytorch/blob/60963c2ecbd3caa3ad2ee225ea334c9dbfaf62e4/caffe2/python/workspace.py#L166

To run the first op of the net, you can do 
```
workspace.RunOperatorOnce(net.op[0])
```

**Comment by pjavia-iterativescopes** [comment]
@yinghai  Is there any other way to do it? Correct me, if I got this wrong but the way caffe2 works is, it will create protocol buffer object without any check of compatibility among the next operations added. For, example it won't throw error if there is dimension mismatch even after I do workspace.CreateNet(net). However, it will throw error when I do workspace.RunNet(net). This make debugging extremely difficult. Can you please suggest some methodology for debugging?

**Comment by pjavia-iterativescopes** [comment]
@yinghai The above command does not work



```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

# We'll also import a few standard python libraries
from matplotlib import pyplot
import numpy as np
import time
import inspect

# These are the droids you are looking for.
from caffe2.python import core, workspace, brew,net_drawer
from caffe2.proto import caffe2_pb2
from caffe2.python.model_helper import ModelHelper

inp = np.random.randn(7, 3, 224, 224).astype(np.float32)
workspace.FeedBlob('X', inp)
model = ModelHelper()
conv1 = brew.conv(model, 'X', 'conv1', 3, 5, 3)
workspace.RunNetOnce(model.param_init_net)
workspace.CreateNet(model.net)
workspace.RunOperatorOnce(model.net.op[0])
```


    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    <ipython-input-10-e5237123faf8> in <module>()
         21 workspace.RunNetOnce(model.param_init_net)
         22 workspace.CreateNet(model.net)
    ---> 23 workspace.RunOperatorOnce(model.net.op[0])
    

    ~/anaconda3/envs/Caffe2/lib/python3.6/site-packages/caffe2/python/core.py in __getattr__(self, op_type)
       2080                 'Method ' + op_type + ' is not a registered operator.' +
       2081                 ' Did you mean: [' +
    -> 2082                 ",".join(workspace.C.nearby_opnames(op_type)) + ']'
       2083             )
       2084         return lambda *args, **kwargs: self._CreateAndAddToSelf(


    AttributeError: Method op is not a registered operator. Did you mean: [Abs,Acos,Add,And,Clip,Conv,Copy,Cos,Cosh,Div,Do,EQ,Elu,Exp,FC,GE,GT,Glu,If,LC,LE,LRN,LT,Load,Log,Max,Min,Mod,Mul,NE,Not,Or,Pow,Sin,Sqr,Sub,Sum,TT,Tan,TopK,Xor]

**Comment by yinghai** [comment]
`workspace.RunOperatorOnce` takes in a protobuf message. `model,net` is a instantiated net. Try
```
workspace.RunOperatorOnce(model.net.Proto().op[0])
```
and you don't even need `workspace.CreateNet(net)`.
