### ISSUE TITLE
[caffe2] Where can I read the code for net->ParseFromArray()?

### ISSUE THREAD

**Issue by Suhail** [pytorch/pytorch#14384]
## ❓ Questions and Help

Hi there, I am trying to search for the source code of this function but haven't been able to: `net->ParseFromArray(data, len)`

### Context:

```c++
void loadToNetDef(AAssetManager* mgr, caffe2::NetDef* net, const char *filename) {
    AAsset* asset = AAssetManager_open(mgr, filename, AASSET_MODE_BUFFER);
    assert(asset != nullptr);

    const void *data = AAsset_getBuffer(asset);
    assert(data != nullptr);

    off_t len = AAsset_getLength(asset);
    assert(len != 0);

    if (!net->ParseFromArray(data, len)) { // <----------- this
        alog("Couldn't parse net from data. Len: %d, File: %s\n", len, filename);
    }

    AAsset_close(asset);
}
```

I went to the old caffe2 repo, checked out the tag v0.8.1 since the code is from the AICamera demo project. I searched for the function but couldn't find any reference to it.

I am trying to solve my own issue here: https://github.com/pytorch/pytorch/issues/14370

**Comment by bddppq** [comment]
This is a function from the protobuf library https://github.com/protocolbuffers/protobuf/blob/0894e07536af88065d462cdc9d8e807c0723ef4d/src/google/protobuf/message_lite.cc#L346
