### ISSUE TITLE
torch.fmax() between MPS tensor and CPU scalar crashes

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#143933]
### 🐛 Describe the bug

Discovered while running `python ../test/inductor/test_torchinductor.py -v -k test_fmin_fmax_mps`
But could be reproduced as single line:
```
python -c "import torch;print(torch.fmax(torch.rand(7, device='mps'), torch.tensor(.3)))"
```
### Versions

2.5.1, nightly

cc @kulinseth @albanD @DenisVieriu97 @jhavukainen

**Comment by atalman** [comment]
Tested with final rc 2.6:
```
 python -c "import torch;print(torch.fmax(torch.rand(7, device='mps'), torch.tensor(.3)))"
tensor([0.3000, 0.9564, 0.9166, 0.3000, 0.3000, 0.3867, 0.6184],
       device='mps:0')

```
