### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator aten::adaptive_avg_pool3d

### ISSUE THREAD

**Issue by John1231983** [pytorch/pytorch#14395]
I am converting the pytorch model to caffe2 using ONNX. It has one operator that is avg_pool3d does not support. I used the code in pytorch

```
avg_pool = nn.AdaptiveAvgPool3d(1)
```

I installed the newest caffe2 yesterday. How should I fix it?

```
/home/john/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py:501: UserWarning: ONNX export failed on ATen operator adaptive_avg_pool3d because torch.onnx.symbolic.adaptive_avg_pool3d does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "convert_pytorch2caffe2.py", line 52, in <module>
    export_params=True)
  File "/home/john/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 22, in _export
    return utils._export(*args, **kwargs)
  File "/home/john/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 287, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::adaptive_avg_pool3d

Defined at:
/home/john/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py(581): adaptive_avg_pool3d

```

**Comment by houseroad** [comment]
Seems the symbolic is missing. @zrphercule would you like to take a look?

**Comment by zrphercule** [comment]
@zrphercule Sure, let me take a look.

**Comment by zrphercule** [comment]
@John1231983 I wonder how you export AdaptiveAvgPool3d? This op is not supported in operator_export_type=ONNX, but is supported in operator_export_type=ONNX_ATEN_FALLBACK.

**Comment by John1231983** [comment]
@zrphercule : I trained the model on pytorch with the `AdaptiveAvgPool3d` layer. Then I install onnx from caffe2 to convert the model to caffe2 format. I got the above error

**Comment by zrphercule** [comment]
@John1231983 For specifically, what is your command of converting AdaptiveAvgPool3d from pytorch to caffe2? Like, "onnx.export(....)" or similar command?

**Comment by John1231983** [comment]
Yes. I used it. This is code
```
torch_out = torch.onnx._export(model,
                                   input,
                                   "model_caff2.onnx",
                                   export_params=False)
```

**Comment by zrphercule** [comment]
@John1231983 I see. Since you are exporting models from pytorch, we have some specially support called Aten for this scenario. I suggest you to take a try of using:

torch_out = torch.onnx._export(model,
                                   input,
                                   "model_caff2.onnx",
                                   export_params=False,
                                  operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK
)

This param will allow you to use ops in Aten when cannot find it in ONNX operator set. It only works when you are exporting models from pytorch, and importing with caffe2.

Please let me know if it works or not :)

**Comment by haiyang-tju** [comment]
Great! It works.

**Comment by haiyang-tju** [comment]
But when I run the exported onnx model in caffe2, it gives me the RuntimeError:

RuntimeError: [enforce fail at aten_op.h:14251] . Attempting to run unknown ATen operator configuration: adaptive_avg_pool3d-2
@zrphercule would you like to take a look? Thanks.

the running code script as follows:

```
import onnx
import caffe2.python.onnx.backend as onnx_caffe2_backend
model = onnx.load(onnx_file_path)
prepared_backend = onnx_caffe2_backend.prepare(model)
W = {model.graph.input[0].name: input_tensor.data.numpy()}
c2_out = prepared_backend.run(W)[0]`
```

**Comment by pietern** [comment]
@houseroad Can you take a look at this as well?

**Comment by PatrickNa** [comment]
A similar error appears when the onnx model is tried to be loaded with onnxruntime:

`Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: ATen is not a registered function/op`

**Comment by luvwinnie** [comment]
does this error have been resolved?

**Comment by garymm** [comment]
Should be fixed for many cases by https://github.com/pytorch/pytorch/pull/17412.

If you have a case that's not supported, please open a new issue with code to repro the problem.
