### ISSUE TITLE
update `sympy` version in `requirement.txt`

### ISSUE THREAD

**Issue by evan0greenup** [pytorch/pytorch#143907]
### 🐛 Describe the bug

Now, sympy version is `1.13.3`, but `torch` is hard required `sympy` version to be `1.13.1`, it will cause inconvenient in an environment which require `sympy` to be latest. 

### Versions

<https://github.com/pytorch/pytorch/blob/a20765a9c1e578beb5e53f9a3ef0c13ea6839768/requirements.txt#L19>

cc @malfet @seemethere @pytorch/pytorch-dev-infra @chauhang @penguinwu

**Comment by malfet** [comment]
Actually, there were an attempt to update sympy, but it caused a lots of compiler tests to fail, see https://github.com/pytorch/pytorch/pull/138338

But let me try it once again, and see what will happen
