### ISSUE TITLE
Allowing the .t transpose shortcut method to take dimensional args

### ISSUE THREAD

**Issue by aa1607** [pytorch/pytorch#14406]
Hi, do you think it might be possible to allow the shortcut method Tensor.t to take arguments (dim0 and dim1) and then to enable it for higher dimensional tensors?

Particularly in attention layers, I find myself using the transpose method back and forth repeatedly and my code frequently looks like this : 

y.matmul(x.transpose(-2,-1)).transpose(-2,-1)

If I could simply write   

y.matmul(x.t(-2,-1)).t(-2,-1) , many sections of my code could be neatly condensed. 

As it is you allow .t to be used only for 2-dimensional tensors, the justification being that allowing it for tensors of greater rank leaves room for misinterpretration, but I can't see how that could be the case if the dimensions to be transposed were both fully specified?

Either way, thanks for a great library!

**Comment by ngimel** [comment]
On the linked PR it was decided to not go ahead with this
