### ISSUE TITLE
Failing to load models due to CUDA out of memory creates unclear-able allocated VRAM and fails to load when enough VRAM is available

### ISSUE THREAD

**Issue by theguruofreason** [pytorch/pytorch#14422]
## 🐛 Bug

When loading a model onto the GPU using nn.DataParallel and .cuda, if there is insufficient VRAM to load the entire model it will be partially loaded and I receive the CUDA error: out of memory. If the python thread is not stopped, the VRAM stays allocated and pytorch doesn't seem to recognize that it is allocated. If sufficient VRAM to load the model is then cleared, the first attempt to load the model onto VRAM allocates all the required VRAM, but yields a "THCTensorCopy.cu line=205 error=2 : out of memory" error, even with over 6 gigs of free VRAM. The next attempt to load the model, again in the same thread, allocates none or possibly 2mb of VRAM and succeeds.

Using torch.cuda.empty_cache() after the partial model load does not clear the VRAM according to nvidia-smi.

## To Reproduce

1. Allocate nearly all of your VRAM.
![no_model_loaded_train](https://user-images.githubusercontent.com/3497875/49111183-438fde00-f244-11e8-9cdc-ba66290287b5.png)
2. Attempt to load a model using torch.nn.DataParallel(model).cuda()
![model_partial_load_train](https://user-images.githubusercontent.com/3497875/49111208-57d3db00-f244-11e8-8b50-114d816b63f8.png)
3. Use try-except to prevent the thread from dying when you hit the CUDA out of memory error
4. Clear allocated VRAM from step 1
![model_partial_load_no_train](https://user-images.githubusercontent.com/3497875/49111248-7043f580-f244-11e8-8a7c-b686c392ccbd.png)
5. Attempt to load the model again as in step 2
![model_fully_loaded_no_train](https://user-images.githubusercontent.com/3497875/49111283-82259880-f244-11e8-978b-51c777485176.png)

after third attempt to load model, below is seen (and THCTensorCopy error is reported):
![model_working_no_train](https://user-images.githubusercontent.com/3497875/49111316-9cf80d00-f244-11e8-9bd6-65f6afe75375.png)

reports during attempts:
![stdout](https://user-images.githubusercontent.com/3497875/49111358-b9944500-f244-11e8-80d5-26f65f964774.png)

The blacked out process is loading the model onto the GPU. Please disregard the changing PIDs, I had code that allowed it to crash after the first 4 screenshots and reran the whole process to produce the last 2. All of this behavior is encapsulated within a single process.

## Expected behavior

The first attempt to load the model to GPU from within the same thread it previously failed in should succeed if enough VRAM is available.

## Environment
PyTorch version: 1.0.0.dev20181102
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 396.54
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0           py35_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] pytorch-nightly           1.0.0.dev20181102 py3.5_cuda9.0.176_cudnn7.1.2_0    pytorch
[conda] torchvision               0.2.1                    py35_1    pytorch

**Comment by bhack** [comment]
Some other references:
https://discuss.pytorch.org/t/is-it-safe-to-recover-from-cuda-oom/12754/9
https://discuss.pytorch.org/t/whats-the-best-way-to-handle-exception-cuda-runtime-error-2-out-of-memory/11891/2

**Comment by bhack** [comment]
https://discuss.pytorch.org/t/how-to-clean-gpu-memory-after-a-runtimeerror/28781

**Comment by ngimel** [comment]
closing due to age
