### ISSUE TITLE
Make it possible to manufacture const Tensor& from TensorImpl* without inducing refcount bump

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14442]
Currently, we have the following function for constructing a TensorImpl* from a Tensor:

```
inline at::Tensor THTensor_wrap(THTensor* tensor) {
  c10::raw::intrusive_ptr::incref(tensor);
  return at::Tensor(c10::intrusive_ptr<at::TensorImpl>::reclaim(tensor));
}
```

(NB: THTensor is a TensorImpl)

This creates a new owning copy of Tensor, necessitating a refcount bump on Tensor.

This is quite distressing, because in many cases the `THTensor*` in question would have stayed live for the entire time `at::Tensor` was live, and we shouldn't have introduced a refcount bump at all in this case. We'd like a way to create a `const at::Tensor&`, without causing a refcount bump. Is it possible to do this? A major barrier to this is the way `Tensor` is implemented today, which is effectively equivalent to the class below:

```
class Tensor {
  intrusive_ptr<TensorImpl> impl_;
}
```

The destructor of `intrusive_ptr<TensorImpl>` decrements the refcount; thus, there is no way to create a Tensor without causing an impending refcount decref.

Here is one possible strategy which could resolve the problem, taking advantage of the fact that Tensor is used purely as a value class. Restructure Tensor in the following way:

```

class Tensor {
  TensorImpl* impl_;
  // NB: Purposely non-virtual
  ~Tensor() {
    c10::raw::intrusive_ptr::decref(impl_);
  }
}

class UnsafeNonOwningTensor : public Tensor {
  UnsafeNonOwningTensor(TensorImpl* impl) : impl_(impl) {}
  ~UnsafeNonOwningTensor() {
    impl_ = UndefinedTensorImpl::singleton();
  }
}

```

The idea is to subclass Tensor into a class that disables the decref of the parent class by reassigning the raw pointer to the undefined tensor (aka nullptr). Because UnsafeNonOwningTensor inherits from Tensor, an UnsafeNonOwningTensor is convertible into a Tensor. However, because UnsafeNonOwningTensor's destructor runs first, it avoids the decref by setting the pointer to something that is (morally) null.

We don't want to use UnsafeNonOwningTensor directly, since both references and rvalue references to UnsafeNonOwningTensor are convertible to references/rvalue references to Tensor. We only want to permit conversion to const Tensor reference. So we introduce another class which declares only the desired implicit conversion:

```
class TensorRef {
public:
  TensorRef(TensorImpl* p) : ref_(p);
  operator const Tensor&() const {
    return ref_;
  }
private:
  UnsafeNonOwningTensor ref_;
}
```

Now, to create a reference, you write:

```
TensorImpl* p; // input
do_some_operation(TensorRef(p));
```

`p` can now be treated as a `const Tensor&`.

**Comment by ezyang** [comment]
cc @smessmer

**Comment by smessmer** [comment]
hm. Is this a confirmed perf issue or just a feeling? This proposal adds considerable complexity and seems very error-prone. Writing `Tensor a = TensorRef(...)` abuses sliced value assignments and will break horribly once somebody decides to add a data member to TensorRef. Also, we actually do sometimes pass `const Tensor&` around, not knowing if you're getting a `Tensor` or `TensorRef` feels like causing us many more problems down the road.

As long as this doesn't give a measurable and significant performance impact, I don't think it's worth it.

**Comment by smessmer** [comment]
Also, still assuming this isn't a significant perf issue, increasing and decreasing the refcount is a good thing because it's safe. Doing this opens the door to loads of bugs where people use `TensorRef`, thinking an object would live long enough, but then it actually doesn't.

**Comment by ezyang** [comment]
At the moment, this is just a feeling, based on general folk knowledge that the atomic increfs/decrefs of reference counting are *the* most important performance cost of reference counting (which is why I want to bootcamp this). So I want to try to convince you that this proposal can be made to not be error-prone (and thus it is easy to use, even if a little complicated to implement).

So first, I think you are right that we should not expose TensorRef directly. In particular, `Tensor a = TensorRef(b)` is even worse than sliced value assignments; because this will select move assignment, the TensorRef will be laundered into a *managed* Tensor pointer, without inducing the (required) increment reference. So we should not expose `TensorRef` (that is subtype of `Tensor`) to user, instead, we should expose a `BetterTensorRef` that is not a subtype of `Tensor`, but IS implicitly convertible to `const Tensor&` (names here are not the actual proposal, they are just illustrative).

```
class BetterTensorRef {
public:
  BetterTensorRef(TensorImpl* p) : ref_(p);
  operator const Tensor&() {
    return p;
  }
private:
  BadTensorRef p;
}
```

A `BetterTensorRef` temporary stays live for the entire expression, so you can use it as `add(BetterTensorRef(x1), BetterTensorRef(x2))`.

There is one case it can be misused: if you *specifically* shoot yourself in the foot with `const Tensor& a = BetterTensorRef(t);` (note that `auto` will infer to `BetterTensorRef`, which would still be OK because of temporary lifetime extension). I think this is unlikely to happen.

> Also, we actually do sometimes pass const Tensor& around, not knowing if you're getting a Tensor or TensorRef feels like causing us many more problems down the road.

Doesn't matter, they're interchangeable. Every TensorRef is a Tensor. And you can't `delete` a `const Tensor&`, so there is no possibility of confusing which destructor you use.

> Doing this opens the door to loads of bugs where people use TensorRef, thinking an object would live long enough, but then it actually doesn't.

I don't see how this follows.

**Comment by ezyang** [comment]
I'm not convinced, but I am going to cede this hill.
