### ISSUE TITLE
compling error with ProcessGroupGlooAsyncTest.cpp

### ISSUE THREAD

**Issue by wsnedy** [pytorch/pytorch#14466]
## Issue description

I follow the guideline for installing PyTorch from source, and I encounter a problem as follow.

<blockquote>
~/qchen/pytorch/torch/lib ~/qchen/pytorch
~/qchen/pytorch
~/qchen/pytorch/torch/lib ~/qchen/pytorch
~/qchen/pytorch/torch/lib/build/c10d ~/qchen/pytorch/torch/lib ~/qchen/pytorch
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.5.0
-- Found CUDA: /usr/local/cuda-9.0 (found suitable version "9.0", minimum required is "7.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda-9.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-9.0
-- Caffe2: Header version is: 9.0
-- Could NOT find CUDNN (missing: CUDNN_INCLUDE_DIR CUDNN_LIBRARY) 
-- Autodetected CUDA architecture(s): 7.0 7.0 7.0 7.0 
-- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70
-- Found Gloo: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/include  
-- Gloo_LIBRARY: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/lib/libgloo_cuda.a
-- Gloo_NATIVE_LIBRARY: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/lib/libgloo.a
-- Gloo_INCLUDE_DIR: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/include
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) 
-- Not able to find MPI, will compile c10d without MPI support
-- Found NCCL: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/include  
-- Determining NCCL version from the header file: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/include/nccl.h
-- Found NCCL (include: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/include, library: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/lib/libnccl.so)
-- NCCL_LIBRARIES: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/lib/libnccl.so
-- NCCL_INCLUDE_DIRS: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/include
-- Found NCCL, but the NCCL version is either not 2+ or not determinable, will not compile with NCCL distributed backend
-- Found CUDA: /usr/local/cuda-9.0 (found version "9.0") 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CAFFE2_LIBRARIES
    CMAKE_DEBUG_POSTFIX
    CMAKE_INSTALL_LIBDIR
    NCCL_EXTERNAL
    NO_NNPACK
    THCS_LIBRARIES
    THCUNN_LIBRARIES
    THCUNN_SO_VERSION
    THC_LIBRARIES
    THC_SO_VERSION
    THD_SO_VERSION
    THNN_LIBRARIES
    THNN_SO_VERSION
    THS_LIBRARIES
    TH_INCLUDE_PATH
    TH_LIBRARIES
    TH_LIB_PATH
    TH_SO_VERSION
    Torch_FOUND
    USE_CUDA
    cwrap_files
    nanopb_BUILD_GENERATOR

-- Build files have been written to: /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/build/c10d
+ make install -j32
Scanning dependencies of target c10d
[ 33%] Building CXX object CMakeFiles/c10d.dir/CUDAUtils.cpp.o
[ 33%] Building CXX object CMakeFiles/c10d.dir/FileStore.cpp.o
[ 33%] Building CXX object CMakeFiles/c10d.dir/TCPStore.cpp.o
[ 33%] Building CXX object CMakeFiles/c10d.dir/Store.cpp.o
[ 33%] Building CXX object CMakeFiles/c10d.dir/ProcessGroup.cpp.o
[ 33%] Building CXX object CMakeFiles/c10d.dir/Utils.cpp.o
[ 38%] Building CXX object CMakeFiles/c10d.dir/ProcessGroupGloo.cpp.o
/nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/c10d/ProcessGroupGloo.cpp: In member function ‘c10d::AlgorithmEntry* c10d::ProcessGroupGloo::
checkout(const c10d::AlgorithmKey&)’:/nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/c10d/ProcessGroupGloo.cpp:445:21: warning: comparison between signed and unsigned integer expr
essions [-Wsign-compare]   if (vec.size() != cacheNumAlgorithmEntries_) {
                     ^
[ 44%] Linking CXX static library libc10d.a
[ 44%] Built target c10d
[ 50%] Building NVCC (Device) object test/CMakeFiles/c10d_cuda_test.dir/c10d_cuda_test_generated_CUDATest.cu.o
Scanning dependencies of target FileStoreTest
[ 55%] Building CXX object test/CMakeFiles/FileStoreTest.dir/FileStoreTest.cpp.o
Scanning dependencies of target TCPStoreTest
[ 61%] Building CXX object test/CMakeFiles/TCPStoreTest.dir/TCPStoreTest.cpp.o
[ 66%] Linking CXX executable FileStoreTest
[ 66%] Built target FileStoreTest
[ 72%] Linking CXX executable TCPStoreTest
[ 72%] Built target TCPStoreTest
Scanning dependencies of target c10d_cuda_test
[ 77%] Linking CXX static library libc10d_cuda_test.a
[ 77%] Built target c10d_cuda_test
Scanning dependencies of target ProcessGroupGlooTest
Scanning dependencies of target ProcessGroupGlooAsyncTest
[ 83%] Building CXX object test/CMakeFiles/ProcessGroupGlooTest.dir/ProcessGroupGlooTest.cpp.o
[ 88%] Building CXX object test/CMakeFiles/ProcessGroupGlooAsyncTest.dir/ProcessGroupGlooAsyncTest.cpp.o
/nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/c10d/test/ProcessGroupGlooTest.cpp: In member function ‘std::shared_ptr<c10d::ProcessGroup::W
ork> SignalTest::run(int, int)’:/nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/c10d/test/ProcessGroupGlooTest.cpp:51:47: warning: ‘at::Tensor at::ones(const at::Type&, at::
IntList)’ is deprecated (declared at /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/include/ATen/Functions.h:3936) [-Wdeprecated-declarations]         at::ones(at::CPU(at::kFloat), {16, 16}),
                                               ^
/nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/c10d/test/ProcessGroupGlooTest.cpp: In function ‘void testAllreduce(const string&, at::Backen
d)’:/nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/c10d/test/ProcessGroupGlooTest.cpp:158:64: warning: ‘at::Tensor at::ones(const at::Type&, at:
:IntList)’ is deprecated (declared at /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/include/ATen/Functions.h:3936) [-Wdeprecated-declarations]     auto tensor = at::ones(at::getType(b, at::kFloat), {16, 16}) * i;
                                                                ^
/nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/c10d/test/ProcessGroupGlooTest.cpp: In function ‘void testBroadcast(const string&, at::Backen
d)’:/nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/c10d/test/ProcessGroupGlooTest.cpp:208:49: warning: ‘at::Tensor at::ones(const at::Type&, at:
:IntList)’ is deprecated (declared at /nfsdata1/home/wangpeisong/qchen/pytorch/torch/lib/tmp_install/include/ATen/Functions.h:3936) [-Wdeprecated-declarations]           inputs[k][l] = at::ones(type, {16, 16}) * (k * stride + l);
                                                 ^
[ 94%] Linking CXX executable ProcessGroupGlooTest
[100%] Linking CXX executable ProcessGroupGlooAsyncTest
CMakeFiles/ProcessGroupGlooTest.dir/ProcessGroupGlooTest.cpp.o: In function `testAllreduce(std::string const&, at::Backend)':
ProcessGroupGlooTest.cpp:(.text+0x149e): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
ProcessGroupGlooTest.cpp:(.text+0x16ef): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
ProcessGroupGlooTest.cpp:(.text+0x1c40): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
CMakeFiles/ProcessGroupGlooTest.dir/ProcessGroupGlooTest.cpp.o: In function `testBroadcast(std::string const&, at::Backend)':
ProcessGroupGlooTest.cpp:(.text+0x2bb7): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
ProcessGroupGlooTest.cpp:(.text+0x2d2e): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
CMakeFiles/ProcessGroupGlooTest.dir/ProcessGroupGlooTest.cpp.o:ProcessGroupGlooTest.cpp:(.text+0x30c1): more undefined references to `at::Error::
Error(at::SourceLocation, std::string)' follow../libc10d.a(ProcessGroupGloo.cpp.o): In function `gloo::BroadcastOneToAll<float>::BroadcastOneToAll(std::shared_ptr<gloo::Context> const&, std::
vector<float*, std::allocator<float*> > const&, int, int, int)':ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIfEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii[_ZN4gloo17BroadcastOneToAllI
fEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii]+0x3b8): undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIfEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii[_ZN4gloo17BroadcastOneToAllI
fEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii]+0x4a8): undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIfEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii[_ZN4gloo17BroadcastOneToAllI
fEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii]+0x8e2): undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIfEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii[_ZN4gloo17BroadcastOneToAllI
fEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii]+0x96b): undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'../libc10d.a(ProcessGroupGloo.cpp.o): In function `gloo::BroadcastOneToAll<double>::BroadcastOneToAll(std::shared_ptr<gloo::Context> const&, std:
:vector<double*, std::allocator<double*> > const&, int, int, int)':ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIdEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPdSaIS8_EEiii[_ZN4gloo17BroadcastOneToAllI
dEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPdSaIS8_EEiii]+0x3b8): undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'../libc10d.a(ProcessGroupGloo.cpp.o):ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIdEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPdSaI
S8_EEiii[_ZN4gloo17BroadcastOneToAllIdEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPdSaIS8_EEiii]+0x4a8): more undefined references to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)' follow../libc10d.a(CUDAUtils.cpp.o): In function `c10d::CUDAEvent::~CUDAEvent()':
CUDAUtils.cpp:(.text+0x23c): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/ProcessGroupGlooTest] Error 1
make[1]: *** [test/CMakeFiles/ProcessGroupGlooTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../libc10d.a(ProcessGroupGloo.cpp.o): In function `c10d::(anonymous namespace)::synchronizeStreams(THCState*, c10d::AlgorithmEntry*)':
ProcessGroupGloo.cpp:(.text+0x1dd1): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
../libc10d.a(ProcessGroupGloo.cpp.o): In function `std::_Function_handler<void (), c10d::ProcessGroupGloo::allreduce(std::vector<at::Tensor, std:
:allocator<at::Tensor> >&, c10d::AllreduceOptions const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&)':ProcessGroupGloo.cpp:(.text+0x2113): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
ProcessGroupGloo.cpp:(.text+0x21d1): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
../libc10d.a(ProcessGroupGloo.cpp.o): In function `std::_Function_handler<void (), c10d::ProcessGroupGloo::broadcast(std::vector<at::Tensor, std:
:allocator<at::Tensor> >&, c10d::BroadcastOptions const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&)':ProcessGroupGloo.cpp:(.text+0x2513): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
ProcessGroupGloo.cpp:(.text+0x25d1): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
../libc10d.a(ProcessGroupGloo.cpp.o):ProcessGroupGloo.cpp:(.text+0x2ca1): more undefined references to `at::Error::Error(at::SourceLocation, std:
:string)' follow../libc10d.a(ProcessGroupGloo.cpp.o): In function `gloo::BroadcastOneToAll<float>::BroadcastOneToAll(std::shared_ptr<gloo::Context> const&, std::
vector<float*, std::allocator<float*> > const&, int, int, int)':ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIfEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii[_ZN4gloo17BroadcastOneToAllI
fEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii]+0x3b8): undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIfEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii[_ZN4gloo17BroadcastOneToAllI
fEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii]+0x4a8): undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIfEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii[_ZN4gloo17BroadcastOneToAllI
fEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii]+0x8e2): undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIfEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii[_ZN4gloo17BroadcastOneToAllI
fEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPfSaIS8_EEiii]+0x96b): undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'../libc10d.a(ProcessGroupGloo.cpp.o): In function `gloo::BroadcastOneToAll<double>::BroadcastOneToAll(std::shared_ptr<gloo::Context> const&, std:
:vector<double*, std::allocator<double*> > const&, int, int, int)':ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIdEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPdSaIS8_EEiii[_ZN4gloo17BroadcastOneToAllI
dEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPdSaIS8_EEiii]+0x3b8): undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'../libc10d.a(ProcessGroupGloo.cpp.o):ProcessGroupGloo.cpp:(.text._ZN4gloo17BroadcastOneToAllIdEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPdSaI
S8_EEiii[_ZN4gloo17BroadcastOneToAllIdEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPdSaIS8_EEiii]+0x4a8): more undefined references to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)' followCMakeFiles/ProcessGroupGlooAsyncTest.dir/ProcessGroupGlooAsyncTest.cpp.o: In function `runAsyncAllreduceTest(std::string const&, unsigned long, u
nsigned long)':ProcessGroupGlooAsyncTest.cpp:(.text+0xf7b): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
ProcessGroupGlooAsyncTest.cpp:(.text+0x107d): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
ProcessGroupGlooAsyncTest.cpp:(.text+0x113b): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
ProcessGroupGlooAsyncTest.cpp:(.text+0x12e6): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
ProcessGroupGlooAsyncTest.cpp:(.text+0x13bd): undefined reference to `at::Error::Error(at::SourceLocation, std::string)'
CMakeFiles/ProcessGroupGlooAsyncTest.dir/ProcessGroupGlooAsyncTest.cpp.o:ProcessGroupGlooAsyncTest.cpp:(.text+0x14d2): more undefined references 
to `at::Error::Error(at::SourceLocation, std::string)' followcollect2: error: ld returned 1 exit status
make[2]: *** [test/ProcessGroupGlooAsyncTest] Error 1
make[1]: *** [test/CMakeFiles/ProcessGroupGlooAsyncTest.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 nanopb libshm gloo THD c10d'
</blockquote>

## Code example

```
git checkout v0.4.1
git submodule update --init
export CUDA_HOME=/usr/local/cuda-9.0
```

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): python setup.py install
- OS: CentOS Linux 7 (Core)
- PyTorch version: 0.4.1
- Python version: 3.6
- CUDA/cuDNN version: CUDA 9.0.176
- GPU models and configuration: Tesla V100-SXM2
- GCC version (if compiling from source): (GCC) 5.4.0
- CMake version: version 3.8.2

**Comment by pietern** [comment]
Did you use a clean build directory when trying this? I suspect this was caused by build artifacts from a newer commit poisoning your build and causing this error. You can run `git clean -fdx` to clean up your tree.

**Comment by wsnedy** [comment]
Yes, and i also try to create a new env, use `git pull` and `git clean -fdx`, and then rebuild, but I got the same error again.

**Comment by pietern** [comment]
I was able to compile from a clean 0.4.1 tree just fine. Is it possible that some headers/libraries are installed system wide (perhaps newer versions) and that those are being picked up here?

Can you confirm if the master build works for you?

**Comment by wsnedy** [comment]
I have build Pytorch sucessfully in a new machine, and yes, there may be some libraries are installed before. When I try to reproduce this, I found that if I first install Pytorch from pip, and uninstall it, then I build from source, this error will appear. Is there any method to clean these libraries installed by pip?

**Comment by pietern** [comment]
I don't know of a method to clean up remaining bits after an uninstall. If that is the only difference between a build working and a build failing (the remaining artifacts from an uninstalled version of PyTorch), then I think there must be some environment setting that is messing things up.

In the mean time there has been significant work done to the build system. If the issue persist then please feel free to reopen this issue or create a new one.
