### ISSUE TITLE
C++ API use model.pt in GPU . When I use lstm in model, there is what():  Expected object of backend CPU but got backend CUDA for argument #2 'mat2' (checked_tensor_unwrap at /pytorch/aten/src/ATen/Utils.h:70)

### ISSUE THREAD

**Issue by joy-yjl** [pytorch/pytorch#14460]
## To Reproduce

C++ code：

module->to(at::kCUDA);
auto gpu_tensor = img_var.to(at::kCUDA);
vector<torch::jit::IValue> inputs;
inputs.push_back(gpu_tensor);
auto  out_tensor = module->forward(inputs).toTensor();

model：

		# LSTM

		self.lstm1 = nn.LSTM(input_size=64, hidden_size=64, num_layers=2, batch_first=True)

		self.lstm2 = nn.LSTM(input_size=64, hidden_size=64, num_layers=2, batch_first=True)

		#self.lstm2 = nn.Sequential(*lstm2)

		self.lstm3 = nn.LSTM(input_size=64, hidden_size=64, num_layers=2, batch_first=True)

and

		im6_1, hidden1 = self.lstm1(img5_1)
		#self.encode5(a)
		im6_2, hidden2 = self.lstm2(img5_2, hidden1)
		#self.encode5(a)
		im6_3, hidden3 = self.lstm3(img5_3, hidden2)

  error：
![image](https://user-images.githubusercontent.com/30424546/49136932-10be1680-f326-11e8-90ca-7bd061b8f8c2.png)

## Environment

 - PyTorch Version ( 1.0):
 - OS ( CentOS):

 - Python version:2.7
 - CUDA/cuDNN version:9.0
 - GCC version:5.4.0

**Comment by ngimel** [comment]
Closing due to age
