### ISSUE TITLE
pip install torch 0.4.0 (Windows) fails.

### ISSUE THREAD

**Issue by developersfox** [pytorch/pytorch#14468]
## 🐛 Bug

On Windows (python 3.6 & no gpu support.), using pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-win_amd64.whl makes http error 403 returns with Forbidden Url. (also checked the "earlier versions" page but could not find a .whl located there as well.)

1. (python 3.6) pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-win_amd64.whl
2. or pip3 install ...

**Comment by peterjc123** [comment]
Cannot reproduce. Is it simply a network error?

**Comment by developersfox** [comment]
I tried on my desktop & several vms, all had the same error. Tried on campus network, and still the same.. If you can actually access torch cpu 0.4.0 .whl file, could you upload it please? I would very much appreciate..

**Comment by soumith** [comment]
can you just download it first, and then do `pip install [downloaded file]`?

**Comment by developersfox** [comment]
Download and installing worked.

**Comment by vakul-singh** [comment]
try pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-win_amd64.whl

**Comment by Sowhardhhonnappa** [comment]
> try pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-win_amd64.whl

I get this on Windows: ERROR: torch-1.1.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

**Comment by shivaprasad123m** [comment]
Use the below link 
"pip3 install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html" 
for windows OS with configuration.
OS : Windows
Package : PIP
Language : Python 3.6
CUDA : None

**Comment by spyderCat** [comment]
torch 0.4.0 only had versions for macos and linux, there was never a windows compatible version.

**Comment by spyderCat** [comment]
Try:
pip install pytorch=0.4.0 -c pytorch

**Comment by ramzeta** [comment]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'pytorch'
