### ISSUE TITLE
[jit] Support enumerate for ModuleList

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#14471]
## 🚀 Feature
Currently we can only do:

```
for module in self.module_list:
   ///
``` 

We should support
```
for i, module in enumerate(self.module_list):
   ///
```
## Motivation

Otherwise, we will have to write:

```
i = 0
for module in self.module_list:
   ///

   i += 1
```

**Comment by driazati** [comment]
Related: #8872

**Comment by zasdfgbnm** [comment]
@sidazhang Is this still an issue? I am using it at https://github.com/aiqm/torchani/blob/master/torchani/nn.py#L36 and it seems to works well with JIT

**Comment by driazati** [comment]
This is fixed on master
