### ISSUE TITLE
NO_DISTRIBUTED=1 is untested in CI

### ISSUE THREAD

**Issue by anderspapitto** [pytorch/pytorch#14496]
currently, after building with `NO_DISTRIBUTED=1 python setup.py build develop`, `python -c "import torch; x = torch.randn(10).cuda()"` fails with the error 

```
RuntimeError: couldn't find libcudart. Make sure CUDA libraries are installed in a default location, or that they're in LD_LIBRARY_PATH.
```

this should be caught by CI, but is apparently untested

**Comment by mrshenli** [comment]
Fixed by #17337. See #14805
