### ISSUE TITLE
embeddings layer with IntTensor / cuda.IntTensor inputs

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#145]
Would it be possible to feed the embedding layer with IntTensors rather than LongTensors only?

**Comment by addisonklinke** [comment]
@apaszke @soumith In my case, the lack of `torch.int32` support causes compatibility issues when exporting to ONNX and running in TensorRT 7. As mentioned in Nvidia's [docs](https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/FoundationalTypes/DataType.html#datatype), int64 is not supported in TensorRT. 

Therefore, when I run the model there are many warnings ""One or more weights outside the range of INT32 was clamped". The outputs are also not as accurate as other inference providers, indicating that the cast from int64 to int32 caused actual degradation in the model accuracy. I only have 150 embedding vectors, so int64 is way overkill

**Comment by LvLs9** [comment]
Guys, please, fix that! 🔥

You did great job here. But if anyone need to use TensorRT, they can't use your embedding layer.

**Comment by Piteryo** [comment]
It seems that for new versions of TensorRT, the engine automatically converts all weights and inputs to int32 and TensorRT works well for int32 input in that case. However, using int64 is still an overkill if you inference you PyTorch model or use ONNX.

**Comment by albanD** [comment]
This was added some time back and is now working just fine on master for `dtype=torch.int`.
