### ISSUE TITLE
Build break on ppc64le  

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#14539]
## 🐛 Bug

I am getting the following below from overnight builds 

[100%] Linking CXX executable ../bin/test_api
/usr/bin/ld: CMakeFiles/test_api.dir/parallel.cpp.o: undefined reference to symbol 'omp_get_num_threads@@OMP_1.0'
/opt/miniconda/lib/libgomp.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [bin/test_api] Error 1
make[1]: *** [test_api/CMakeFiles/test_api.dir/all] Error 2

here is the build log
https://powerci.osuosl.org/user/avmgithub/my-views/view/PyTorch/job/pytorch-linux-cuda9-cudnn7-py3-mpi-build-only-gpu/204/console

## To Reproduce

run :   python setup.py install 

## Expected behavior

Build to completion

## Environment

 - PyTorch Version (e.g., 1.0):  latest from master  possibly commits on Nov 28 or early Nov 29
 - OS (e.g., Linux):  Ubuntu and RH 
 - How you installed PyTorch (`conda`, `pip`, source):   source
 - Build command you used (if compiling from source):  python setup.py install
 - Python version:   2.7 and 3.7
 - CUDA/cuDNN version:    cuda 9.2  cuDNN 7  
 - GPU models and configuration:   P100
 - Any other relevant information:

**Comment by ezyang** [comment]
Hi, can you revert https://github.com/pytorch/pytorch/commit/8901935ad42fe9bf093d1106ea43606008a4024d and see if that fixes the problem

**Comment by avmgithub** [comment]
I'm still getting the error:
/bin/ld: CMakeFiles/test_api.dir/parallel.cpp.o: undefined reference to symbol 'omp_in_parallel@@OMP_1.0'
/home/freddie/miniconda/lib/libgomp.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [bin/test_api] Error 1
make[2]: Leaving directory `/home/freddie/builder/jenkins/pytorch/pytorch/build'
make[1]: *** [test_api/CMakeFiles/test_api.dir/all] Error 2

Let me revert back a bit further

**Comment by avmgithub** [comment]
Using commit 302caef154cdfef621283b1a3a0da7bac0417bd7  builds fine.

**Comment by avmgithub** [comment]
The problem might be the following:
An instance of the -fopenmp flag has been removed when compiling pytorch/test/cpp/api/parallel.cpp 

here is the snippet of the good object build :   (the -fopenmp in **BOLD** was removed ) 
....cut ....
pytorch/third_party/googletest/googletest  -Wno-deprecated -fvisibility-inlines-hidden **-fopenmp** -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -g -fno-omit-frame-pointer -O0 -fPIE   -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DTH_HAVE_THREAD -Wno-maybe-uninitialized -Wno-unused-but-set-parameter -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-unknown-pragmas -Wno-missing-braces -fopenmp -std=gnu++11 -o CMakeFiles/test_api.dir/parallel.cpp.o -c /home/freddie/builder/jenkins/pytorch/pytorch/test/cpp/api/parallel.cpppytorch/third_party/googletest/googletest  -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -g -fno-omit-frame-pointer -O0 -fPIE   -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DTH_HAVE_THREAD -Wno-maybe-uninitialized -Wno-unused-but-set-parameter -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-unknown-pragmas -Wno-missing-braces -fopenmp -std=gnu++11 -o CMakeFiles/test_api.dir/parallel.cpp.o -c pytorch/test/cpp/api/parallel.cpp

here is the snippet of the bad build: (missing -fopenmp flag where it should be.  Even if -fopenmp flag is present towards the end , the flag is not at the correct position)

...cut...
pytorch/third_party/googletest/googletest  -Wno-deprecated -fvisibility-inlines-hidden -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -g -fno-omit-frame-pointer -O0 -fPIE   -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DTH_HAVE_THREAD -Wno-maybe-uninitialized -Wno-unused-but-set-parameter -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-unknown-pragmas -Wno-missing-braces -fopenmp -std=gnu++11 -o CMakeFiles/test_api.dir/parallel.cpp.o -c pytorch/test/cpp/api/parallel.cpp


This is also true for the linking of ../bin/test_api .  
An instance of -fopenmp flag was removed

**Comment by ezyang** [comment]
Do you mind bisecting? Would like to know which commit changed the behavior.

**Comment by avmgithub** [comment]
@ezyang this is the commit that broke the build 8901935ad42fe9bf093d1106ea43606008a40  ,   I'll see if I can find the line with the flags that was removed or changed.

**Comment by ezyang** [comment]
OK. It would be most helpful if you could refine the if-checks so that they handle PPC correctly. I'll review and land it.

**Comment by ngimel** [comment]
Closing due to age

**Comment by zoldaten** [comment]
add to CMakeLists.txt:

```
FIND_PACKAGE( OpenMP REQUIRED)
if(OPENMP_FOUND)
    message("OPENMP FOUND")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
endif()
```
