### ISSUE TITLE
How to use torch.distributed.gather?

### ISSUE THREAD

**Issue by stgzr** [pytorch/pytorch#14536]
I compiled pytorch(1.0.0a0+ff608a9) with openMPI. When I tried to use the `torch.distributed.gather`, I found `gather_list` is required. But I think as sender it seems not necessary to recv `list[Tensor]`. So I just set `gather_list` to `None`. Well, when the script is running, the error comes:
 
> File "test.py", line 216, in train
    dist.gather(outputs, gather_list=None, dst=0, group=new_group)
  File "./lib/python2.7/site-packages/torch/distributed/distributed_c10d.py", line 986, in gather
    work = group.gather([gather_list], [tensor], opts)
TypeError: gather(): incompatible function arguments. The following argument types are supported:
    1. (self: torch.distributed.ProcessGroup, arg0: List[List[at::Tensor]], arg1: List[at::Tensor], arg2: torch.distributed.GatherOptions) -> c10d::ProcessGroup::Work
    2. (self: torch.distributed.ProcessGroup, output_tensors: List[at::Tensor], tensor: at::Tensor, root: int) -> c10d::ProcessGroup::Work
Invoked with: <torch.distributed.ProcessGroupMPI object at 0x7f63064b1a40>, [None], [tensor([[9.2869e-01, 8.5623e-01, 1.0708e+00,  ...

So how can I solve this error? As there is few documents about how to use collective operations, I wonder if there is a wiki or website because current tutorial is outdated.

Thank you!

**Comment by pietern** [comment]
Can you update to the latest nightly? The hash you mention is 2 months old (ff608a9).

I'm double checking to see what happens on latest. This should be covered by unit tests.

**Comment by pietern** [comment]
A bug snuck in somewhere. Working on a fix.

**Comment by stgzr** [comment]
@pietern Thank you for your help!
BTW, the code [distributed_c10d.py:1046](https://github.com/pietern/pytorch/blob/b17ee9ecf593b053ed2e9b317baf407bfe03ea05/torch/distributed/distributed_c10d.py#L1046) use `_check_tensor_list(gather_list, "gather_list")` to check `gather_list` is a list. But [distributed_c10d.py:1058](https://github.com/pietern/pytorch/blob/b17ee9ecf593b053ed2e9b317baf407bfe03ea05/torch/distributed/distributed_c10d.py#L1058) is to make sure `gather_list` is `None`. So how should I set the `gather_list` if the case is `dst != my_rank`?

**Comment by pietern** [comment]
@stgzr The empty list is falsy so you can use that for `gather_list`. Updating the doc to mention this.

@ZhengRui Investigating.

**Comment by ZhengRui** [comment]
Thanks @pietern , that works, didn't thought about that.

**Comment by JoyHuYY1412** [comment]
> @stgzr The empty list is falsy so you can use that for `gather_list`. Updating the doc to mention this.
> 
> @ZhengRui Investigating.

Can I use all_gather to gather the output tensor without discarding its grad_fn? Currently my gathered result's grad_fn is None. I hope to do something like broadcasting the gathered output to each gpu for further training, which needs to use the gathered tensor. It looks like what sync bn does.
