### ISSUE TITLE
Eliminate occurrences of Type::options()

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14548]
As a follow up to #14421, I investigated how difficult it would be to delete the `options` method from `Type` entirely.

Some cases were easy (I sent patches out for them at #14543 and #14544), but some were not:

* TensorIterator seems to rely heavily on the Type interface, storing a Type to represent the target type. Refactoring it to not use type() seems somewhat involved.
* We still generate a bunch of code inside Type itself, and this code frequently needs to allocate tensors. Right now, the most idiomatic way to write it is something like `at::empty(sizes, this->options())`. This probably isn't going to change in the near future (although, we could probably just make `options()` protected in this case)
* (maybe more)

cc @gchanan

**Comment by ngimel** [comment]
Closing due to age
