### ISSUE TITLE
Deduplicate logic in tensor_conversion_dispatch and Tensor::to

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14550]
According to @gchanan, @SsnL was working on this, but this may be in limbo now so I want to write it down before we forget.

The context:
* We have a function `tensor_conversion_dispatch`, which gets invoked when we do a tensor conversion from the PyTorch frontend, e.g., when you want to move something from one device to another, or when you want to change the scalar type
* We also have a function, `Tensor::to`, which also does conversions

These are actually implementing the same functionality, and we should just use `Tensor::to`

However, there are two problems.

First, the API of `tensor_conversion_dispatch` is extremely strange: it takes a `Type` and a `Device`; it should really just take a `TensorOptions` (which is what we actually wanted to record), but this requires us to change some rather grotty call sites. (Fortunately, there's only a few).

Second, `to()` may not trace correctly. See this comment below:

```
  // Dispatch to specialized, traceable cast operators for the JIT. These
  // specialized ops are ATen native and thus have the tracing mechanisms auto-
  // generated, whereas the default case is not traceable since it requires a
  // Type as a parameter/attribute. TODO: support Types in the JIT and remove
  // this once we have that
```

This tracing behavior must be preserved in some way.

**Comment by bhack** [comment]
We have also device move with cuda() cpu(). Right?

**Comment by ezyang** [comment]
Yes, though I think those call `tensor_conversion_dispatch`

**Comment by SsnL** [comment]
Thanks, @ezyang! I won't have time to continue working on refactoring `tensor_new.cpp` until probably mid-December. @t-vi was also looking into something related.

**Comment by t-vi** [comment]
Well #14097 attempts to fix it, but I've had a hard time getting anyone to say it's OK and now it's full of merge conflicts.

**Comment by ngimel** [comment]
Closing due to age
