### ISSUE TITLE
Address multiple process groups from torch.distributed

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#14563]
In `torch.distributed` you can initialize a global process group using the `init_process_group` function. This function takes a backend argument and will initialize **either** the Gloo, NCCL, or MPI backend. You're at a loss if you want to use both Gloo and NCCL through the `torch.distributed` frontend. The only way to do this today is by manually creating ProcessGroup instances and using them directly.

For the case where you're dealing with both CPU and CUDA tensors and want to use Gloo for the CPU ones and NCCL2 for the CUDA ones, we should consider supporting a mode where we don't initialize a single backend, but multiple at the same time. We then use a process group dispatcher class that forwards the calls to the appropriate process group depending on the device type of the tensor arguments. This class should be a subclass of the ProcessGroup base class in C++ such that we can use it both from the Python side as well as from the C++ side.

Have to figure out what is the right way to expose this to the `init_process_group` function.

cc @teng-li

**Comment by pietern** [comment]
This is possible as of #18595.

**Comment by densechen** [comment]
@pietern Can you provide a piece of code to demonstrate how to implement this feature which you described?
I meet the some situation as you described, but still don't know how to create two process groups
