### ISSUE TITLE
pin_memory/is_pinned API is too CUDA-centric

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14560]
Right now, if you want to allocate some pinned CPU memory, you write something like torch.Storage(512).pin_memory(). But wait!! This is pinning memory for CUDA transfer specifically. What if you're working with AMD GPUs and you want to pin memory for HIP transfer? Well, right now the HIP support operates by building a special version of PyTorch that switches the meaning of anywhere you say CUDA to mean HIP, so `pin_memory` refers to HIP. But we're weaning ourselves off of this approach, which means that the API for `pin_memory` is very unsatisfactory.

Probably the easiest thing to do is make `pin_memory` accept a DeviceType which specifies which device you want to pin memory for? (Would be even better if we could make dispatch happen on DeviceType, but that may be difficult.)

See also #2206

CC @bddppq 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @Varal7 @VitalyFedyunin @jamesr66a @ppwwyyxx

**Comment by ezyang** [comment]
For BC reasons, we probably have to default calls to these methods to CUDA. The point is to ensure that we can make them work with other device types.

**Comment by ngimel** [comment]
Marking for triage review, as this has come up more often recently

**Comment by ezyang** [comment]
Extra trouble: we accept `pin_memory` boolean parameter on all factory functions; need to make this a device.

**Comment by garfield1997** [comment]
I see that many pin_memory-related methods now accept the device parameter. When I have time, I will take a look at how to appropriately modify the previous commits.

**Comment by garfield1997** [comment]
One possible solution is to add a new variable called `default_device` in the `globalContext` and provide an interface for users to modify the value of `default_device` when extending custom backends. This way, users can specify the device to be used in device-related interfaces like `empty_cpu` and `GetCPUAllocatorMaybePinned`. What do you think about this? @ezyang

**Comment by ezyang** [comment]
I'm not a big fan of this approach, because it is too confusing what the difference between this and the default device is. I would much rather limp along with the assumption that any given binary PyTorch build supports one 'accelerator' device and we default to that, as it doesn't introduce new API but "does the right thing".

**Comment by garfield1997** [comment]
I agree with you, and personally, I find it unlikely that different types of devices would be used simultaneously. Do you think it might be preferable to maintain the current state for the CPU's empty operator?

**Comment by ezyang** [comment]
Yes, unless you're willing to add the device argument, maintaining the current assumption is better.

**Comment by janeyx99** [comment]
This looks completed by #126376, closing. Please re-open if that's not the case!
