### ISSUE TITLE
Add Kaiming initialization functions to C++ API

### ISSUE THREAD

**Issue by JoshVarty** [pytorch/pytorch#14582]
/cc @goldsborough 

## 🚀 Feature
Most of the [public initialization functions](https://pytorch.org/docs/stable/_modules/torch/nn/init.html) have been exposed to consumers of the C++ API in [torch/csrc/api/include/torch/nn/init.h](https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/nn/init.h). It would be nice to also include the `KaimingUniform` and `KaimingNormal` initialization functions.

## Motivation

Helps the C++ API get closer to feature parity with the Python API.

## Pitch

I think this would be a good candidate for a first PR to PyTorch. If you agree I would like to try to implement this myself. My rough approach would be:

1. Add the following method declarations to [`init.h`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/nn/init.h)

```C++
TORCH_API Tensor kaiming_normal_(Tensor tensor, double a = 0, std::string mode = "fan_in", std::string nonlinearity="leaky_relu" );

TORCH_API Tensor kaiming_uniform_(Tensor tensor, double a = 0, std::string mode = "fan_in", std::string nonlinearity="leaky_relu" );
```

2. Reimplement the [Python implementations](https://github.com/pytorch/pytorch/blob/6302e4001ab54b3ddeca2b608d337fe7077e801c/torch/nn/init.py#L261-L327) in [`init.cpp`](https://github.com/pytorch/pytorch/blob/393ad6582d1876dc995925ef558ba94e954d115e/torch/csrc/api/src/nn/init.cpp)

3. Add tests. I believe the tests for this file are currently in [`misc.cpp`](https://github.com/pytorch/pytorch/blob/master/test/cpp/api/misc.cpp#L47-L54). Maybe I could add tests like these from [`test_nn.py`](https://github.com/pytorch/pytorch/blob/666d383a0066ffb5bee2d2062b7fa1c94c8f1a7e/test/test_nn.py#L6817-L6855)?

## Questions:

 - I notice the C++ implementation doesn't implement [`calculate_gain()`](https://github.com/pytorch/pytorch/blob/6302e4001ab54b3ddeca2b608d337fe7077e801c/torch/nn/init.py#L8-L47). Would we want to include this and expose it as well?
 - The Python implementations have `string` parameters `mode` and `nonlinearity`. How do you handle strings within the C++ API. Do you use the standard library? Would an enum or some other approach make more sense since there are a limited number of valid strings? Or should we change the shape of the API to accept `gain` instead of calculating it within the method itself?

## Alternatives

Users could always implement these features on their own.

**Comment by goldsborough** [comment]
Hey @JoshVarty, thanks for the idea. I'd love it if you tried implementing this! It indeed sounds like a nicely contained, manageable task for a first PR. It shouldn't be too hard to port the Python code to C++ since our C++ tensor API is almost 1:1 the same.

For the enum question, I'd much prefer using C++ enums over strings. You can create an `enum class Mode` in the `torch::nn::init` namespace with the appropriate members.

I'd say, just give it a shot, and I'll give you supportive feedback once you have a minimum viable PR ready.

**Comment by yf225** [comment]
This issue is closed by https://github.com/pytorch/pytorch/pull/14718.
