### ISSUE TITLE
Load model file failed in Mac Libtorch C++ (exported in Ubuntu Libtorch C++)

### ISSUE THREAD

**Issue by xmlyqing00** [pytorch/pytorch#14603]
## 🐛 Bug

Hi everyone! Hope you have a great day.

I trained my model in Ubuntu 18.04 Libtorch C++ with CUDA 10 and exported the model to the disk. I want to test this model in Mac Libtorch C++ with CPU. Both versions are 1.0.0.dev20181129.

Both Libtorch are downloaded from Official Website. I checked the source code in `inline_container.h`, I am not sure whether this error is due to different Libtorch version.

The error is:

libc++abi.dylib: terminating with uncaught exception of type c10::Error: file_format_version >= kMinSupportedFileFormatVersion ASSERT FAILED at /Users/administrator/nightlies/2018_11_15/wheel_build_dirs/libtorch_2.7/pytorch/caffe2/serialize/inline_container.h:215, please report a bug to PyTorch. Attempted to read a PyTorch file with version 1, but the minimum supported version for reading is 2. Your PyTorch script module file is too old. Please re-export it again. (readAndValidateFileHeader at /Users/administrator/nightlies/2018_11_15/wheel_build_dirs/libtorch_2.7/pytorch/caffe2/serialize/inline_container.h:215)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 135 (0x11365c6d7 in libc10.dylib)
frame #1: torch::jit::PyTorchStreamReader::readAndValidateFileHeader() + 852 (0x10bdfbbe4 in libtorch.1.dylib)
frame #2: torch::jit::PyTorchStreamReader::PyTorchStreamReader(std::__1::basic_istream<char, std::__1::char_traits<char> >*) + 107 (0x10bdfb0ab in libtorch.1.dylib)
 

## To Reproduce

1. Train model in Libtorch C++ in Ubuntu. Save the model by:
```c++
string model_path = "model.pt";
serialize::OutputArchive output_archive;
cp_net.save(output_archive);
output_archive.save_to(model_path);
```
1. Read the model in Libtorch C++ in Mac. Code:
```c++
serialize::InputArchive input_archive;
input_archive.load_from(model_path);
cp_net.load(input_archive);
```
1. Errors appear.

## Expected behavior

Stop at `input_archive.load_from(model_path);`

## Environment

**Train and save model env:**
Collecting environment information...
PyTorch version: 1.0.0.dev20181129
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 410.78
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Read and run model env**:
Collecting environment information...
PyTorch version: 1.0.0.dev20181115
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.1
GCC version: Could not collect
CMake version: version 3.12.4

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

## Additional context

Both environment work well. I can write and read model in Ubuntu correctly. I also can train and test, write and read model in Mac too. But I don't know why this happened.

The attachement is the model file. Please remove the suffix ".txt".

Thank you for your time. Any comments appreciate.

[best.pt.txt](https://github.com/pytorch/pytorch/files/2631852/best.pt.txt)

**Comment by ngimel** [comment]
Closing due to age
