### ISSUE TITLE
error sparse matrix multiplication when calling coalesce

### ISSUE THREAD

**Issue by aldopareja** [pytorch/pytorch#14617]
## 🐛 Bug
When call sparse.coalesce() a sparse.mm(dense) multiplication is giving erroneous output. When commenting out norm_adj.coalesce() the code performs correctly.

## To Reproduce
```
norm_adj = torch.tensor([[1., 0., 0., 1.],
                                 [0., 1., 0., 0.],
                                 [0., 1., 1., 0.],
                                 [0., 1., 0., 2.]])

        idx = norm_adj.nonzero()
        vals = norm_adj[norm_adj>0]
        norm_adj = torch.sparse.FloatTensor(idx.t(),vals,torch.Size([4,4]))
        norm_adj = norm_adj.coalesce()
        print(norm_adj.to_dense())    
        # print(norm_adj)
        D = norm_adj.mm(torch.ones(self.num_nodes,1)).view(-1)
        D = D ** -0.5
        D = torch.diag(D)
        print(D)
        print('sparse_mult')
        print(norm_adj.t().mm(D).t())
        print('another dense')
        print(norm_adj.to_dense().t().mm(D).t())
        print('dense mult')
        print(D.mm(norm_adj.to_dense()))
```

## output prints

```
print(norm_adj):
tensor([[1., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 1., 1., 0.],
        [0., 1., 0., 2.]])
print(D):
tensor([[0.7071, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.7071, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.5774]])
```
### WRONG
```
sparse_mult
tensor([[0.7071, 0.7071, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 1.4142, 0.0000, 0.0000],
        [0.0000, 0.5774, 0.0000, 1.1547]])
```
### RIGHT
```
another dense
tensor([[0.7071, 0.0000, 0.0000, 0.7071],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.7071, 0.7071, 0.0000],
        [0.0000, 0.5774, 0.0000, 1.1547]])
dense mult
tensor([[0.7071, 0.0000, 0.0000, 0.7071],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.7071, 0.7071, 0.0000],
        [0.0000, 0.5774, 0.0000, 1.1547]])
```

## Environment

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.1
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.15.2)
[pip] torch (0.4.1)
[conda] pytorch                   0.4.1           py37_cuda0.0_cudnn0.0_1    pytorch

**Comment by weiyangfb** [comment]
I can't repro the results at current master:
```
norm_adj = torch.tensor([[1., 0., 0., 1.],
                         [0., 1., 0., 0.],
                         [0., 1., 1., 0.],
                         [0., 1., 0., 2.]])

idx = norm_adj.nonzero()
vals = norm_adj[norm_adj>0]
norm_adj = torch.sparse.FloatTensor(idx.t(),vals,torch.Size([4,4]))
norm_adj = norm_adj.coalesce()
print(norm_adj.to_dense())    
# print(norm_adj)
D = norm_adj.mm(torch.ones(4,1)).view(-1)
D = D ** -0.5
D = torch.diag(D)
print(D)
print('sparse_mult')
print(norm_adj.t().mm(D).t())
print('another dense')
print(norm_adj.to_dense().t().mm(D).t())
print('dense mult')
print(D.mm(norm_adj.to_dense()))
```

my results:
```
tensor([[1., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 1., 1., 0.],
        [0., 1., 0., 2.]])
tensor([[0.7071, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.7071, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.5774]])
sparse_mult
tensor([[0.7071, 0.0000, 0.0000, 0.7071],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.7071, 0.7071, 0.0000],
        [0.0000, 0.5774, 0.0000, 1.1547]])
another dense
tensor([[0.7071, 0.0000, 0.0000, 0.7071],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.7071, 0.7071, 0.0000],
        [0.0000, 0.5774, 0.0000, 1.1547]])
dense mult
tensor([[0.7071, 0.0000, 0.0000, 0.7071],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.7071, 0.7071, 0.0000],
        [0.0000, 0.5774, 0.0000, 1.1547]])
```

**Comment by aldopareja** [comment]
> I can't repro the results at current master:
> 
> ```
> norm_adj = torch.tensor([[1., 0., 0., 1.],
>                          [0., 1., 0., 0.],
>                          [0., 1., 1., 0.],
>                          [0., 1., 0., 2.]])
> 
> idx = norm_adj.nonzero()
> vals = norm_adj[norm_adj>0]
> norm_adj = torch.sparse.FloatTensor(idx.t(),vals,torch.Size([4,4]))
> norm_adj = norm_adj.coalesce()
> print(norm_adj.to_dense())    
> # print(norm_adj)
> D = norm_adj.mm(torch.ones(4,1)).view(-1)
> D = D ** -0.5
> D = torch.diag(D)
> print(D)
> print('sparse_mult')
> print(norm_adj.t().mm(D).t())
> print('another dense')
> print(norm_adj.to_dense().t().mm(D).t())
> print('dense mult')
> print(D.mm(norm_adj.to_dense()))
> ```
> my results:
> 
> ```
> tensor([[1., 0., 0., 1.],
>         [0., 1., 0., 0.],
>         [0., 1., 1., 0.],
>         [0., 1., 0., 2.]])
> tensor([[0.7071, 0.0000, 0.0000, 0.0000],
>         [0.0000, 1.0000, 0.0000, 0.0000],
>         [0.0000, 0.0000, 0.7071, 0.0000],
>         [0.0000, 0.0000, 0.0000, 0.5774]])
> sparse_mult
> tensor([[0.7071, 0.0000, 0.0000, 0.7071],
>         [0.0000, 1.0000, 0.0000, 0.0000],
>         [0.0000, 0.7071, 0.7071, 0.0000],
>         [0.0000, 0.5774, 0.0000, 1.1547]])
> another dense
> tensor([[0.7071, 0.0000, 0.0000, 0.7071],
>         [0.0000, 1.0000, 0.0000, 0.0000],
>         [0.0000, 0.7071, 0.7071, 0.0000],
>         [0.0000, 0.5774, 0.0000, 1.1547]])
> dense mult
> tensor([[0.7071, 0.0000, 0.0000, 0.7071],
>         [0.0000, 1.0000, 0.0000, 0.0000],
>         [0.0000, 0.7071, 0.7071, 0.0000],
>         [0.0000, 0.5774, 0.0000, 1.1547]])
> ```

Yes, now it's giving me a good output, I don't know if updating to pytorch 1.0 fixed the issue.

**Comment by rgommers** [comment]
This seems fixed, so closing. Thanks for reporting @aldopareja
