### ISSUE TITLE
cpp_extension.py:182: UserWarning: Error checking compiler version for g++: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by JSharp4273** [pytorch/pytorch#14619]
## To Reproduce
See : 
https://github.com/facebookresearch/maskrcnn-benchmark/issues/104#issuecomment-435808084

Follow the instructions describes in the "install.md" of the project refered before. 

## Expected behavior

A warning advertising about an argument concerning g++ that should be set as bytes but not as string, follow by a nvcc compilation error.

## Environment

PyTorch version: 1.0.0.dev20181103
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN Xp COLLECTORS EDITION
GPU 1: GeForce GTX TITAN X

Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/lib64/libcudnn.so.7.3.1
/usr/local/cuda-10.0/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.4
/usr/local/cuda-9.0/lib64/libcudnn_static.a
/usr/local/cuda-9.1/lib64/libcudnn.so
/usr/local/cuda-9.1/lib64/libcudnn.so.7
/usr/local/cuda-9.1/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.1/lib64/libcudnn_static.a
/usr/local/cuda-9.2/lib64/libcudnn.so
/usr/local/cuda-9.2/lib64/libcudnn.so.7
/usr/local/cuda-9.2/lib64/libcudnn.so.7.1.4
/usr/local/cuda-9.2/lib64/libcudnn.so.7.2.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py36_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
[conda] pytorch-nightly           1.0.0.dev20181103 py3.6_cuda9.2.148_cudnn7.1.4_0  [cuda92]  pytorch
[conda] torch                     0.4.0                     <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch

## Additional context

In my original issue I found a very simple way to fix this issue.
Until now I did not had any trouble related to that.

**Comment by fmassa** [comment]
Yes. A simple workaround solution was proposed in https://github.com/facebookresearch/maskrcnn-benchmark/issues/104#issuecomment-435767848

```python
# before
version = subprocess.check_output([compiler, '-dumpfullversion', '-dumpversion'])
# after
version = subprocess.check_output([compiler, '-dumpfullversion', '-dumpversion']).decode('utf-8')
```

**Comment by ngimel** [comment]
Closing due to age
