### ISSUE TITLE
pin_memory_batch converts all Sequences to list and all Mappings to dict

### ISSUE THREAD

**Issue by szali** [pytorch/pytorch#14613]
## 🐛 Bug

I have a namedtuple which is converted to a list by the DataLoader, because pin_memory_batch converts all collections.Sequence to list, and all collections.Mapping to dict.

## To Reproduce

1. Use a torch.utils.data.DataLoader
2. Emit namedtuples from your dataset as samples
3. Observe that they come from the DataLoader as lists

Required changes to current code (torch/utils/data/dataloader.py:243):

def pin_memory_batch(batch):
    if isinstance(batch, torch.Tensor):
        return batch.pin_memory()
    elif isinstance(batch, string_classes):
        return batch
    elif isinstance(batch, container_abcs.Mapping):
        return **type(batch)(**{k: pin_memory_batch(sample) for k, sample in batch.items()}**)**
    **elif is_namedtuple(batch):
        return type(batch)(*[pin_memory_batch(sample) for sample in batch])**
    elif isinstance(batch, container_abcs.Sequence):
        return **type(batch)(**[pin_memory_batch(sample) for sample in batch]**)**
    else:
        return batch

Where is_namedtuple is a heuristic to detect named tuples.

I think namedtuple is a generic enough object for pin_memory_batch to support it.

## Expected behavior

The type of the sequence objects is not changed.

## Environment

PyTorch version: 1.0.0a0+8e1e3ba
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.0-rc2

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)

Nvidia driver version: 396.26
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.2.1
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.13.3)
[pip3] torch (1.0.0a0+8e1e3ba)
[pip3] torchfile (0.1.0)
[pip3] torchvision (0.1.9)
[conda] Could not collect

**Comment by ngimel** [comment]
Closing due to age
