### ISSUE TITLE
Test case bug when run unit test: test_set_dir

### ISSUE THREAD

**Issue by zxb1489479870** [pytorch/pytorch#14610]
## To Reproduce

1. Install pytorch(not install cuda) using the latest source code(commit id 89c3db) as said in github.
1. Install torchvision by pip: `pip3 install torchvision`.
1. Go to test folder and run: `python -m unittest test_utils.TestHub.test_set_dir`.

## Expected behavior

1. There will have a test failed when you first run the command:  `python -m unittest test_utils.TestHub.test_set_dir` , the following is log : 
Downloading: "https://github.com/pytorch/vision/archive/master.zip" to /tmp/master.zipE
ERROR: test_set_dir (test_utils.TestHub)
Traceback (most recent call last):
  File "/home/xiaobinz/Downloads/pytorch/intel_pytorch-pytorch/test/test_utils.py", line 410, in test_set_dir
    pretrained=True)
  File "/home/xiaobinz/anaconda3/envs/pytorch-latest/lib/python3.6/site-packages/torch/hub.py", line 150, in load
    dependencies = _load_attr_from_module('hubconf', 'dependencies')
  File "/home/xiaobinz/anaconda3/envs/pytorch-latest/lib/python3.6/site-packages/torch/hub.py", line 67, in _load_attr_from_module
    m = importlib.import_module(module_name)
  File "/home/xiaobinz/anaconda3/envs/pytorch-latest/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  **ModuleNotFoundError: No module named 'hubconf'** 
  Ran 1 test in 12.958s
  **FAILED  (errors=1)**

2. But if you run the unit test case again, you can get the following result: 
    Using cache found in /tmp/vision_master.
    Ran 1 test in 1.925s
    **OK**

## Environment

 - PyTorch Version (1.0):  latest
 -  Linux
 - Install Pytorch using source code:
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: no cuda

## Additional context

I confused why the unit test case can be passed when running the second time. I find that there will have create the folder **vision_master** in the directory **tmp**  when I first run the test command,  there will be a file named **hubconf.py** , but the test case said **No module named 'hubconf'**. And then if you run the same test command again, the folder **vision_master** will be deleted. 

 Hoping your responds. Thanks.

**Comment by zou3519** [comment]
cc @ailzhang maybe?

**Comment by ailzhang** [comment]
I cannot repro this following the steps. Let me find a new env and try again.

**Comment by ailzhang** [comment]
Asked @weiyangfb to help but the test still runs fine. 
@zxb1489479870 Could you try it in a fresh new environment and let me know how to repro if it still happens? 
The `vision_master`dir was a left over from the failed test. It is supposed to be cleaned up if the test passes. https://github.com/pytorch/pytorch/blob/master/test/test_utils.py#L468

**Comment by zxb1489479870** [comment]
@ailzhang , thanks, I recreate a new virtual environment by conda: `conda create -n pytorch-test python=3.6`, and then following the Installation steps said in pytorch github. Are you install torchvision by :`pip install torchvision` after install pytorch? if you didn't install torchvision, the test case will be skipped. the log datails as:
![image](https://user-images.githubusercontent.com/16217777/49411545-3fb00e80-f7a4-11e8-8651-9316e279acae.png)

But if you install torchvision by pip , and then run the test case, I think you can get the following error:

![image](https://user-images.githubusercontent.com/16217777/49411629-93baf300-f7a4-11e8-8c84-f58da7c1f24a.png)

And I also asked my colleague to test it again, he can get the same result.

**Comment by zxb1489479870** [comment]
I find the **vision_master **  dir will be created  in **/tmp**  when I first run the test, but error said it cannot find the model **hubconf**,  I found the **vision_master **  dir has this model. if I run the test case again, it will use the **vision_master **  dir files, and then delete the folder after the test passes as you said.  
You can see my log, it will download the **vision_master * when I run the test in the first time, it should find the **hubconf** model in **/tmp/vision_master** , but it can not find it. I think it should be a  dir read error.

**Comment by ailzhang** [comment]
@zxb1489479870  Thanks for the details steps. I'm build again to see if I can repro on my end.

**Comment by ailzhang** [comment]
@zxb1489479870 Thanks a lot for the repro! The PR fixes the issue for me, let me know if it works for you or not.

**Comment by zxb1489479870** [comment]
@ailzhang, thanks your help, it works for me now.
