### ISSUE TITLE
use several forward functions in DistributedDataParallel

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#14616]
Hi,

I have a model that can perform several types of forward, and typically I use it this way:

```python
loss1 = model.f1(x1)
loss1.backward()
...
loss2 = model.f2(x2)
loss2.backward()
```

When I use `DistributedDataParallel`, `f1` and `f2` become undefined, so I have to do this:

```python
model = nn.parallel.DistributedDataParallel(model, device_ids=[rank], output_device=rank)
...
loss1 = model.module.f1(x1)
loss1.backward()
...
loss2 = model.module.f2(x2)
loss2.backward()
```

This seems to run, but I'm not confident whether this is the proper way to do it, and I was wondering if this is a fine thing to do, or if there is a cleaner way?

**Comment by soumith** [comment]
@glample in the above, it'll run, but wont use Distributed at all

**Comment by myleott** [comment]
cc @teng-li, under what conditions will this setup work with DDP? I remember we had some issues before in fairseq when combining DDP + conditional computation.

**Comment by teng-li** [comment]
@myleott  DDP doesn't support this, and this needs a bit of work to make it support and work right.

**Comment by mrshenli** [comment]
@glample PyTorch 1.1 added control flow support in DDP see #18953, and what you proposed in the above comments should work. I am closing this issue, but please feel free to reopen if necessary.
