### ISSUE TITLE
Build libtorch with -D_GLIBCXX_USE_CXX11_ABI=1

### ISSUE THREAD

**Issue by xin-xinhanggao** [pytorch/pytorch#14620]
It seems that the latest libtorch lib is build with  -D_GLIBCXX_USE_CXX11_ABI=0 which causes link error with other c++ project build with -D_GLIBCXX_USE_CXX11_ABI=1.

When I build pytorch with gcc 5.4.0 and cmake 3.5.0 like this
```
cd tools
python build_libtorch.py
```
I get the error message like this
```
[ 90%] Built target event_test
[ 90%] Built target net_async_tracing_test
[ 90%] Built target operator_test
[ 98%] Built target torch
[ 98%] Built target test_jit
[100%] Built target test_api
[100%] Built target cuda_packedtensoraccessor_test
[100%] Built target integer_divider_test
[100%] Built target cuda_half_test
[100%] Built target cuda_optional_test
Install the project...
-- Install configuration: "Release"
CMake Error at third_party/ideep/mkl-dnn/cmake_install.cmake:40 (file):
  file INSTALL cannot find
  "/home/xhg/pytorch/third_party/ideep/mkl-dnn/-fopenmp".
Call Stack (most recent call first):
  cmake_install.cmake:86 (include)
  
Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
Traceback (most recent call last):
  File "build_libtorch.py", line 38, in <module>
    subprocess.check_call(command, universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/xhg/pytorch/tools/build_pytorch_libs.sh', '--use-nnpack', '--use-mkldnn', '--use-cuda', 'caffe2']' returned non-zero exit status 2
```

**Comment by goldsborough** [comment]
Try:

```
mkdir build
cd build
python ../tools/build_libtorch.py
```

**Comment by xin-xinhanggao** [comment]
@goldsborough  Thanks for your advice, I build libtorch by myself with CXX flags -D_GLIBCXX_USE_CXX11_ABI=1. ( I add -D_GLIBCXX_USE_CXX11_ABI=1 in tools/build_pytorch_libs.sh line 127)

But When I try to load a module using torch::jit::load
I got the bug report message

> terminate called after throwing an instance of 'c10::Error'
>   what():  memcmp("PYTORCH1", buf, kMagicValueLength) != 0 ASSERT FAILED at /home/xhg/new_pytorch/pytorch/caffe2/serialize/inline_container.cc:75, please report a bug to PyTorch. File is an unsupported archive format from the preview release. (PyTorchStreamReader at /home/xhg/new_pytorch/pytorch/caffe2/serialize/inline_container.cc:75)
> frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x57 (0x7f47d137a1a7 in /home/xhg/libtorch/lib/libc10.so)
> frame #1: torch::jit::PyTorchStreamReader::PyTorchStreamReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::istream*) + 0x629 (0x7f47e46b72c9 in /home/xhg/libtorch/lib/libcaffe2.so)
> frame #2: torch::jit::load(std::istream&) + 0x2ae (0x7f47e8495cce in /home/xhg/libtorch/lib/libtorch.so.1)
> frame #3: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x42 (0x7f47e8495ea2 in /home/xhg/libtorch/lib/libtorch.so.1)
> frame #4: main + 0x54 (0x401557 in ./example-app)
> frame #5: __libc_start_main + 0xf0 (0x7f47d15a7830 in /lib/x86_64-linux-gnu/libc.so.6)
> frame #6: _start + 0x29 (0x401399 in ./example-app)
> 
> Aborted (core dumped)

**Comment by Oldpan** [comment]
@xin-xinhanggao  I meet a same situation with you , do you make a breakthrough on this?

**Comment by xin-xinhanggao** [comment]
@Oldpan  It seems that we should export the model.pt file using the latest pytorch version. I have fixed it.

**Comment by Oldpan** [comment]
Yeah. The same but not necessarily last version of Pytorch will work.

We should export model.pt and build libtorch from the same version of Pytorch. It will work.

**Comment by xin-xinhanggao** [comment]
@Oldpan  Could you plese tell me which file folder do you use as the librotch? When I build as @goldsborough  said, I got the lib file folder in pytorch/torch/lib/tmp_install. But in tmp_install/lib, I cannot find libcaffe2_gpu.so

**Comment by NathanSegerlind** [comment]
> Try:
> 
> ```
> mkdir build
> cd build
> python ../tools/build_libtorch.py
> ```
 I've been having this problem with libtorch,  I tried the suggested today with pytorch the last commit 9e1f4ba1244c196d3e1d94c3142c17c4906fdda5, the build failed  while compiling some of the cuda libraries with "nvlink fatal   : Internal error: reference to deleted section
"
interestingly enough,  I was able to build pytorch proper with `python setup.py install`

not sure if this is related or if it should be another issue

**Comment by mdreammao** [comment]
@Oldpan hello~~I follow the steps as you said,but I can't find the fold  tmp_install  anywhere!!

**Comment by mdreammao** [comment]
and if I use the lib built from the source to replace the released version, lots of error occur.
just like the ABI problems.

**Comment by yf225** [comment]
We just release libtorch binaries with cxx11 ABI: https://github.com/pytorch/pytorch/issues/17492#issuecomment-524692441. Please try it out and let us know if you experience any issues.

**Comment by Gao907** [comment]
Initially I want to use trained model from pytorch to detect hand gesture in C++. My original problem is that I can cmake the code calling either libtorch or OpenCV library successfully, but I cannot make it when I try to cmake the code calling both.
I have solved the similar problems by changing to a lower OpenCV version. Here are some details.

Original problem:

CMakeFiles/ LibtorchTest.dir/main . CPP. O: in the function 'main':
/home/gao/CLionProjects/LibtorchTest/ main.cpp:14 : undefined reference to 'CV:: imread (STD:: String const & int)'
/home/gao/CLionProjects/LibtorchTest/ main.cpp:15 : for 'CV:: imshow (STD:: String const &, CV::_ Undefined reference in inputarray const &) '
collect2: error: ld returned 1 exit status
CMakeFiles/ LibtorchTest.dir/build . make:133 : recipe for target 'LibtorchTest' failed
make[3]: *** [LibtorchTest] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/ LibtorchTest.dir/all ' failed
make[2]: *** [CMakeFiles/ LibtorchTest.dir/all ] Error 2
CMakeFiles/Makefile2:102: recipe for target 'CMakeFiles/ LibtorchTest.dir/rule ' failed
make[1]: *** [CMakeFiles/ LibtorchTest.dir/rule ] Error 2
Makefile:138 : recipe for target 'LibtorchTest' failed
make: *** [LibtorchTest] Error 2

Problem solved:

-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v8.0.3  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Torch library status:
--     libraries: 
-- Found OpenCV: /home/gao/opencv-3.4.12/build (found version "3.4.12") 
-- OpenCV library status:
--     version: 3.4.12
--     libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_viz
--     include path: ...too long, so I omit it)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gao/CLionProjects/LibtorchTest/cmake-build-debug
Scanning dependencies of target LibtorchTest
[ 50%] Building CXX object CMakeFiles/LibtorchTest.dir/main.cpp.o
[100%] Linking CXX executable LibtorchTest
[100%] Built target LibtorchTest

Hope my solved problem may help.

**Comment by latuanvinh1998** [comment]
> Initially I want to use trained model from pytorch to detect hand gesture in C++. My original problem is that I can cmake the code calling either libtorch or OpenCV library successfully, but I cannot make it when I try to cmake the code calling both.
> I have solved the similar problems by changing to a lower OpenCV version. Here are some details.
> 
> Original problem:
> 
> CMakeFiles/ LibtorchTest.dir/main . CPP. O: in the function 'main':
> /home/gao/CLionProjects/LibtorchTest/ main.cpp:14 : undefined reference to 'CV:: imread (STD:: String const & int)'
> /home/gao/CLionProjects/LibtorchTest/ main.cpp:15 : for 'CV:: imshow (STD:: String const &, CV::_ Undefined reference in inputarray const &) '
> collect2: error: ld returned 1 exit status
> CMakeFiles/ LibtorchTest.dir/build . make:133 : recipe for target 'LibtorchTest' failed
> make[3]: *** [LibtorchTest] Error 1
> CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/ LibtorchTest.dir/all ' failed
> make[2]: *** [CMakeFiles/ LibtorchTest.dir/all ] Error 2
> CMakeFiles/Makefile2:102: recipe for target 'CMakeFiles/ LibtorchTest.dir/rule ' failed
> make[1]: *** [CMakeFiles/ LibtorchTest.dir/rule ] Error 2
> Makefile:138 : recipe for target 'LibtorchTest' failed
> make: *** [LibtorchTest] Error 2
> 
> Problem solved:
> 
> -- Caffe2: CUDA detected: 10.2
> -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
> -- Caffe2: CUDA toolkit directory: /usr/local/cuda
> -- Caffe2: Header version is: 10.2
> -- Found cuDNN: v8.0.3 (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
> -- Autodetected CUDA architecture(s): 6.1
> -- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
> -- Torch library status:
> -- libraries:
> -- Found OpenCV: /home/gao/opencv-3.4.12/build (found version "3.4.12")
> -- OpenCV library status:
> -- version: 3.4.12
> -- libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_viz
> -- include path: ...too long, so I omit it)
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/gao/CLionProjects/LibtorchTest/cmake-build-debug
> Scanning dependencies of target LibtorchTest
> [ 50%] Building CXX object CMakeFiles/LibtorchTest.dir/main.cpp.o
> [100%] Linking CXX executable LibtorchTest
> [100%] Built target LibtorchTest
> 
> Hope my solved problem may help.

Tks, you save my day. The problem here is the version of OpenCV, I down version of OpenCV to 3.4 and it work even on CUDA 11.0.

**Comment by Gao907** [comment]
You're welcome.  Glad to hear that my solution works in your problem.

**Comment by jasonbeach** [comment]
I guess I don't quite understand...I can download the binaries with the cxx11 abi: `https://download.pytorch.org/libtorch/cu110/libtorch-cxx11-abi-shared-with-deps-1.7.1%2Bcu110.zip`, but then how does that work it's way into a python installation?  i.e. my python environment is python 3.8.5 created from venv. 

I assume the pytorch versions installed from pip were built with the pre-cxx11 abi?  

Thanks
