### ISSUE TITLE
PyTorcg on Windows 10 : THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=74 error=30 : unknown error

### ISSUE THREAD

**Issue by mAch17** [pytorch/pytorch#14660]
## 🐛 Bug

Hi,

I have installed pytorch on Windows 10 using conda prebuilt versions. pytorch seems to have installed but I cannot execute code on CUDA. 

>>> import torch
>>> import numpy as np
>>> x = torch.FloatTensor(np.array([1.,4.,67.]))
>>> x
tensor([ 1.,  4., 67.])
>>> x.to('cuda')
THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=74 error=30 : unknown error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cuda runtime error (30) : unknown error at ..\aten\src\THC\THCGeneral.cpp:74

## To Reproduce

1. conda create -n ptdl numpy pyyaml mkl mkl-include
2. activate ptdl
3. conda install pytorch cuda92 -c pytorch
4. conda install -c defaults intel-openmp -f <This addresses DLL #1 not found error on importing pytorch>

## Environment
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.2.148
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py36_cuda92_cudnn7he774522_1  [cuda92]  pytorch

**Comment by peterjc123** [comment]
Do you have CUDA 9.2 installed on your machine?

**Comment by mAch17** [comment]
Yes. I have CUDA 9.2 installed.

**Comment by peterjc123** [comment]
Do you have a GPU installed? Please use `wmic path win32_VideoController get` to check.

**Comment by mAch17** [comment]
I think that was the problem. The computer came with a default Nvidia driver installed , but during CUDA 9.2 installation (or maybe some other task), the driver was corrupted.
Reinstalling Nvidia driver solved the problem.
