### ISSUE TITLE
Inconsistent behavior for log_prob when values are outside of support

### ISSUE THREAD

**Issue by chentau** [pytorch/pytorch#14672]
## 🐛 Bug

In Scipy, if you try to calculate the log probability of a value outside of the given distribution's support, scipy will return `-inf`.

The Uniform Distribution for torch follows this behavior, as shown below:
```python
> Uniform(torch.tensor(0.),torch.tensor(1.)).log_prob(torch.tensor(5.))
> tensor(-Inf)
```
However, this behavior does not extend to other distributions that have a constrained support, such as the exponential, beta, and gamma, or discrete distributions such as the geometric. 

```python 
> Beta(torch.tensor(1.),torch.tensor(1.)).log_prob(torch.tensor(5.))
> tensor(nan)
```

```python
> Exponential(torch.tensor(2.)).log_prob(torch.tensor(-5.))
> tensor(11.6094)
```

```python
> Gamma(torch.tensor(1.),torch.tensor(1.)).log_prob(torch.tensor(-1.))
> tensor(nan)
```

```python
> Geometric(torch.tensor(5.)).log_prob(torch.tensor(-1.))
> tensor(nan)
```

These four are the distributions that I've tested; I'm unsure if there are more.  Is this discrepancy in behavior expected?  Please let me know if I've missed something.

### System Info
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.10
GCC version: (Ubuntu 8.2.0-7ubuntu1) 8.2.0
CMake version: version 3.12.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 960M
Nvidia driver version: 415.13
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.4)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.1)
[conda] pytorch                   0.4.1            py37ha74772b_0

cc @fritzo @neerajprad @alicanb @nikitaved

**Comment by vishwakftw** [comment]
Hi @chentc777,

You can consider setting `validate_args` to `True` for the distributions individually, or by setting a global flag using:
```
torch.distributions.Distribution.set_default_validate_args(True)
```

This will raise a `ValueError` if the values are outside the support.

```python
>>> torch.distributions.Distribution.set_default_validate_args(False)
>>> Beta(torch.tensor(1.),torch.tensor(1.)).log_prob(torch.tensor(5.))
tensor(nan)
>>> Exponential(torch.tensor(2.)).log_prob(torch.tensor(-5.))
tensor(11.6094)
>>> Gamma(torch.tensor(1.),torch.tensor(1.)).log_prob(torch.tensor(-1.))
tensor(nan)
>>> Geometric(torch.tensor(5.)).log_prob(torch.tensor(-1.))
tensor(nan)
```

```python
>>> torch.distributions.Distribution.set_default_validate_args(True)
>>> Beta(torch.tensor(1.),torch.tensor(1.)).log_prob(torch.tensor(5.))
ValueError: The value argument must be within the support
>>> Exponential(torch.tensor(2.)).log_prob(torch.tensor(-5.))
ValueError: The value argument must be within the support
>>> Gamma(torch.tensor(1.),torch.tensor(1.)).log_prob(torch.tensor(-1.))
ValueError: The value argument must be within the support
>>> Geometric(torch.tensor(5.)).log_prob(torch.tensor(-1.))
ValueError: The parameter probs has invalid values
```

**Comment by fritzo** [comment]
Closing as validation is now enabled by default.  I believe erroring is probably the more common use case in deep learning.  To reproduce SciPy behavior of returning negative infinity, I believe you can do something like
```py
d = LogNormal(torch.zeros(9), torch.ones(9), validate_args=False)
x = torch.randn(9)  # incorrectly unconstrained
unsafe_log_prob = d.log_prob(x)  # may have NANs
safe_log_prob = torch.where(
    d.support.check(x),
    unsafe_log_prob,
    torch.full_like(unsafe_log_prob, -math.inf),
)
```
