### ISSUE TITLE
Error in conv2d if float32 weights have been transposed

### ISSUE THREAD

**Issue by PedroNoraSilva** [pytorch/pytorch#14677]
## 🐛 Bug

Doing a convolution with weights in float32 if the weights have been transposed in numpy before being assigned to the convolution, the results are incorrect. the same does not happen if its float64 or an "untransposed" array.

## To Reproduce

Create a random weights array in numpy and transpose it.
Create a parameter with it
Assign to conv weights
Run it

FAIL:
```
import torch
import numpy

y = numpy.random.rand(1,416,416,2).astype('float64')
y = numpy.transpose(y, (0,3,1,2))

filters = numpy.random.rand(3,3,2,16).astype('float64')
filterx = numpy.transpose(filters, (3,2,0,1))

x = torch.nn.Conv2d(2, 16, 3,  stride=1, padding=0, dilation=1, groups=1, bias=False) 
x.weight = torch.nn.Parameter(torch.from_numpy(filterx))
l = x(torch.from_numpy(y))
l = l.detach().numpy()

x.weight = torch.nn.Parameter(torch.from_numpy(filterx.astype('float32')))
t = x(torch.from_numpy(y.astype('float32')))
t = t.detach().numpy()

print(t.shape)
print(l.shape)
print(numpy.abs(t-l).max())
```
Result:
(1, 16, 414, 414)
(1, 16, 414, 414)
3.7013630152464088

SUCCESS:
```
import torch
import numpy

y = numpy.random.rand(1,416,416,2).astype('float64')
y = numpy.transpose(y, (0,3,1,2))

filters = numpy.random.rand(3,3,2,16).astype('float64')
filterx = numpy.transpose(filters, (3,2,0,1))

x = torch.nn.Conv2d(2, 16, 3,  stride=1, padding=0, dilation=1, groups=1, bias=False)
x.weight = torch.nn.Parameter(torch.from_numpy(filterx))
l = x(torch.from_numpy(y))
l = l.detach().numpy()

x.weight = torch.nn.Parameter(torch.from_numpy(numpy.array(filterx.tolist()).astype('float32')))
t = x(torch.from_numpy(y.astype('float32')))
t = t.detach().numpy()

print(t.shape)
print(l.shape)
print(numpy.abs(t-l).max())
```
Result:
(1, 16, 414, 414)
(1, 16, 414, 414)
2.0108326364010054e-06

## Expected behavior

The differences between float32 and float64 should be down to precision.

## Environment

PyTorch version: 1.0.0.dev20181201
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by vishwakftw** [comment]
I think this issue has been solved by https://github.com/pytorch/pytorch/pull/16300.

**Comment by yf225** [comment]
@PedroNoraSilva Could you check if the problem still exists on current master? (nightly builds: https://anaconda.org/pytorch/pytorch-nightly)

**Comment by vishwakftw** [comment]
I can confirm that the issue has been resolved in current master.

Environment info below:
Collecting environment information...
PyTorch version: 1.0.0.dev20190125
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 390.25
cuDNN version: Probably one of the following:
/usr/local/MATLAB/R2017b/bin/glnxa64/libcudnn.so.5.1.5
/usr/local/cuda-8.0/lib64/libcudnn.so.5
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.2)
[conda] blas                      1.0                         mkl  
[conda] cuda80                    1.0                  h205658b_0    pytorch
[conda] mkl                       2018.0.3                      1  
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0  
[conda] mkl_random                1.0.1            py36h4414c95_1  
[conda] pytorch-nightly           1.0.0.dev20190125 py3.6_cuda8.0.61_cudnn7.1.2_0  [cuda80]  pytorch

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/16300

**Comment by PedroNoraSilva** [comment]
Seems to be working now. Cheers
