### ISSUE TITLE
libtorch c++API: terminate called after throwing an instance of 'c10::Error'

### ISSUE THREAD

**Issue by IcewineChen** [pytorch/pytorch#14682]
## 🐛 Bug

libtoch:terminate called after throwing an instance of 'c10::Error'

## To Reproduce

When I use libtorch to load .pt model, there is a error like that:
terminate called after throwing an instance of 'c10::Error'
  what():  tag == RecordTags::FOOTER ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.h:234, please report a bug to PyTorch. File footer has wrong record type. Is this file corrupted? (readAndValidateFileFooter at /pytorch/caffe2/serialize/inline_container.h:234)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f574bb44d31 in /home/chr/action-sdk/libs/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f574bb445fa in /home/chr/action-sdk/libs/libtorch/lib/libc10.so)
frame #2: <unknown function> + 0x6755ee (0x7f577cdc15ee in /home/chr/action-sdk/libs/libtorch/lib/libtorch.so.1)
frame #3: <unknown function> + 0x679343 (0x7f577cdc5343 in /home/chr/action-sdk/libs/libtorch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x66e0b9 (0x7f577cdba0b9 in /home/chr/action-sdk/libs/libtorch/lib/libtorch.so.1)
frame #5: torch::jit::load(std::istream&) + 0x7c (0x7f577cdbfc4c in /home/chr/action-sdk/libs/libtorch/lib/libtorch.so.1)
frame #6: torch::jit::load(std::string const&) + 0x130 (0x7f577cdbfe70 in /home/chr/action-sdk/libs/libtorch/lib/libtorch.so.1)
frame #7: main + 0x10e (0x497404 in ./action)
frame #8: __libc_start_main + 0xf0 (0x7f574af33830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: _start + 0x29 (0x471e49 in ./action)

[1]    2337 abort (core dumped)  ./action 

I convert the .pth model as guide of documentation, and I’m sure the version of libtorch(11.28 update version) and pytorch(12.01 update version) is the latest. So what can I do to solve the problem? 

Looking forward for you reply.

 - PyTorch Version :1.0 latest 
 - OS: ubuntu 16.04
 - How you installed PyTorch: conda 
 - Python version: 3.6
 - CUDA/cuDNN version: cudnn6/cuda8.0
 - GPU models and configuration:
 - Any other relevant information:

**Comment by liulizhou** [comment]
I have the same problem.

**Comment by IcewineChen** [comment]
> I have the same problem.

When I degrade to pytorch-nightly-dev11.28 and libtorch(build-version 11.28, gpu version), there is no problem. Maybe you can try this method.

**Comment by rainfalj** [comment]
I have the same problem, can you send me libtorch(build-version 11.28, gpu version)

**Comment by IcewineChen** [comment]
> I have the same problem, can you send me libtorch(build-version 11.28, gpu version)

https://drive.google.com/open?id=13qS1gup6E7nJ-l8Ahf4YUsA9gGGVzKWE , you can use this version of libtorch. I'll close the share link in two days.

**Comment by deitycitian** [comment]
I have the same problem, too. I upgraded the package as you offered(https://drive.google.com/open?id=13qS1gup6E7nJ-l8Ahf4YUsA9gGGVzKWE ), but the bug still appear.   What is wrong with this ?

**Comment by rainfalj** [comment]
I use cuda9 version and solved

**Comment by IcewineChen** [comment]
> I have the same problem, too. I upgraded the package as you offered(https://drive.google.com/open?id=13qS1gup6E7nJ-l8Ahf4YUsA9gGGVzKWE ), but the bug still appear. What is wrong with this ?

Maybe u should use pytorch-dev11.28 to trace the model.  And make sure you have cmake and make your project again? I solve the problem by use libtorch 11.28 under cuda8 and cudnnV6.

**Comment by LvJC** [comment]
> > I have the same problem, too. I upgraded the package as you offered(https://drive.google.com/open?id=13qS1gup6E7nJ-l8Ahf4YUsA9gGGVzKWE ), but the bug still appear. What is wrong with this ?
> 
> Maybe u should use pytorch-dev11.28 to trace the model. And make sure you have cmake and make your project again? I solve the problem by use libtorch 11.28 under cuda8 and cudnnV6.

How to degrade to pytorch-dev11.28?
I am using libtorch downloaded on 11.23, but I still met this error

**Comment by IcewineChen** [comment]
> > > I have the same problem, too. I upgraded the package as you offered(https://drive.google.com/open?id=13qS1gup6E7nJ-l8Ahf4YUsA9gGGVzKWE ), but the bug still appear. What is wrong with this ?
> > 
> > 
> > Maybe u should use pytorch-dev11.28 to trace the model. And make sure you have cmake and make your project again? I solve the problem by use libtorch 11.28 under cuda8 and cudnnV6.
> 
> How to degrade to pytorch-dev11.28?
> I am using libtorch downloaded on 11.23, but I still met this error

u can find the 11.28 version package in conda repository(https://anaconda.org/pytorch/pytorch-nightly/files).

**Comment by deitycitian** [comment]
My libtorch's version is 1.0.0.dev20181128. But the bug still appears in ubuntu1~16.04.4.

**Comment by LvJC** [comment]
> My libtorch's version is 1.0.0.dev20181128. But the bug still appears in ubuntu1~16.04.4.

Me the same. If you solved this, pls let me know how. Thx

**Comment by SPark9625** [comment]
I had a similar problem and read somewhere in git issues which I can find rn, that you need to pass in `-D_GLIBCXX_USE_CXX11_ABI=0`. Could someone try and see if this works?

**Comment by Hansry** [comment]
> My libtorch's version is 1.0.0.dev20181128. But the bug still appears in ubuntu1~16.04.4.

Me the same. If you solved this, pls let me know how. Thx

**Comment by dreamerzz** [comment]
Me the same. If you solved this, pls let me know how. Thx
