### ISSUE TITLE
pytorch for NVIDIA GeForce GT 740M with the old CUDA 

### ISSUE THREAD

**Issue by catafest** [pytorch/pytorch#14681]
## 🚀 Feature

1. pytorch for old CUDA : NVIDIA GeForce GT 740M CUDA 
GPU is GeForce GT 740M | 3.0

## Motivation
Now I can install pytorch with the CUDA 8 and later features.
The pytorch cannot detect the old CUDA.
I can use pytorch just with CPU features but is a bad result.

## Pitch
I have an old NVIDIA GeForce GT 740M with the old CUDA 

## Alternatives
I can use pytorch but only cpu feature and this is a bad result .

## Additional context
https://developer.nvidia.com/cuda-gpus

**Comment by soumith** [comment]
We removed support for 3.0 class GPUs in 0.4.1. Unfortunately, we are not bringing it back.

**Comment by soumith** [comment]
@catafest i'm not sure I understand. Can you explain?
