### ISSUE TITLE
Could libtorch release the version build with  -D_GLIBCXX_USE_CXX11_ABI=1

### ISSUE THREAD

**Issue by xin-xinhanggao** [pytorch/pytorch#14694]
I try to use tools/build_libtorch.py to build libtorch with flags  -D_GLIBCXX_USE_CXX11_ABI=1, but my build lib seems does not work well.

When I load it in other CXX11_ABI=1 project which use boost, I got the error message:
```
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
mitsuba: /usr/include/boost/thread/pthread/condition_variable.hpp:162: boost::condition_variable_any::~condition_variable_any(): Assertion `!pthread_mutex_destroy(&internal_mutex)' failed.
Aborted (core dumped)
```

**Comment by wangchaoxixixi** [comment]
I got a similar error, too. Have you solve this problem?

**Comment by seemethere** [comment]
This should be resolved now since we do now build libtorch variants with `-D_GLIBCXX_USE_CXX11_ABI=1`
