### ISSUE TITLE
Blog content about jit.trace is misleading.

### ISSUE THREAD

**Issue by Jiaming-Liu** [pytorch/pytorch#14696]
In https://pytorch.org/blog/the-road-to-1_0/ , the `trace` feature is illustrated with the following snippet.

``` Python
# This will run your nn.Module or regular Python function with the example
# input that you provided. The returned callable can be used to re-execute
# all operations that happened during the example run, but it will no longer
# use the Python interpreter.
from torch.jit import trace
traced_model = trace(model, example_input=input)
traced_fn = trace(fn, example_input=input)

# The training loop doesn't change. Traced model behaves exactly like an
# nn.Module, except that you can't edit what it does or change its attributes.
# Think of it as a "frozen module".
for input, target in data_loader:
    loss = loss_fn(traced_model(input), target)
```

For me, this snippet implies that I could use trace to accelerate training. However, it is not the case.

**Comment by SsnL** [comment]
Hmm but indeed it may accelerate training because it skips all python interpreter overhead. However, if your model uses large kernels and little python logic, you may not see a big improvement.

**Comment by soumith** [comment]
As Simon mentioned,

> For me, this snippet implies that I could use trace to accelerate training. However, it is not the case.

It depends on the workload, and it can accelerate training. It does not imply that it will always accelerate training.

**Comment by Vermeille** [comment]
Sorry to reopen this. If we are doing this, should training be faster because BN/ReLU/Conv can be merged together? if so what structures are subject to fusion?

**Comment by soumith** [comment]
@Vermeille it **can** be faster when all of our BN/ReLU/Conv fusion optimizations go in. Right now they anything with Conv is not fusable because Conv is dispatched to a blackbox library CuDNN, and no code generation / fusions can happen across the blackbox library boundary.
