### ISSUE TITLE
torch.onnx.export is missing documentation on the docs page

### ISSUE THREAD

**Issue by bfreskura** [pytorch/pytorch#14698]
## 📚 Documentation

`torch.onnx.export` shows no documentation on the docs [page](https://pytorch.org/docs/master/onnx.html#functions), while it has documentation in the [source](https://github.com/pytorch/pytorch/blob/master/torch/onnx/utils.py). It would be useful to have the documentation on the docs page.

**Comment by ezyang** [comment]
When Anders moved the functions to prevent circular imports, this problem arose. A simple fix might just to manually reapply the docstring after the fact. Happy to advise if someone wants to fix this.

**Comment by houseroad** [comment]
Thanks @zhangguanheng66 for fixing the doc. :-)
