### ISSUE TITLE
Glog mixing with libtorch

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#14724]
## 🐛 Bug

Using a third party application with c++ Torchscript is going to conflict with c10 logging
## To Reproduce

pytorch is going to change the logging behavior of the app.
I need to call `c10::ShowLogInfoToStderr()` from the main app to enable again `VLOG(0)` and stderr log but I cannot override anymore the module verbosity with glog `--vmodule=` command line flag. Also I cannot control anymore glog 'log_prefix/FLAGS_log_prefix` that seems disabled. 

## Expected behavior
To still control glog of a class using a Trochscript model.

## Environment

 - PyTorch Version (e.g., 1.0): nightly
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @yf225

**Comment by ezyang** [comment]
You can build Torch without glog support, so it shouldn't interfere with your local logging setup. Does that help?

**Comment by bhack** [comment]
Check also https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L388-L393
