### ISSUE TITLE
issues to run minimal pytorch example

### ISSUE THREAD

**Issue by Arnold1** [pytorch/pytorch#14727]
Hi,

I try to run the following example from here, but run into some issues:
https://pytorch.org/cppdocs/installing.html

ld: warning: ignoring file libtorch/lib/libtorch.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): libtorch/lib/libtorch.so
ld: warning: ignoring file libtorch/lib/libcaffe2.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): libtorch/lib/libcaffe2.so
ld: warning: ignoring file libtorch/lib/libc10.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): libtorch/lib/libc10.so

full error log: https://ideone.com/wqgzzy

i installed pytorch:
```
pip3 install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting torch_nightly
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch_nightly-1.0.0.dev20181203-cp36-none-macosx_10_7_x86_64.whl (61.3MB)
    100% |████████████████████████████████| 61.3MB 33kB/s 
Installing collected packages: torch-nightly
Successfully installed torch-nightly-1.0.0.dev20181203
```

im running pytorch on:
osx 10.11.6

i installed libtorch following these steps:
https://pytorch.org/cppdocs/installing.html

here the cmake output:
https://ideone.com/go44HN

**Comment by Arnold1** [comment]
ok the solution is to use this library:
wget -c https://download.pytorch.org/libtorch/nightly/cpu/libtorch-macos-latest.zip

instead of:
wget -c https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip

**Comment by Arnold1** [comment]
can you confirm that libtorch-shared-with-deps-latest.zip does not work on osx?

**Comment by matheuscandido** [comment]
I've got the same image not found example in this same spot, by following the minimal example of the docs. Running macOS Mojave here.

**Comment by Arnold1** [comment]
we need to build libtorch manually because it doesnt come with all libs...

**Comment by ddetone** [comment]
Getting the same issue as @Arnold1 with macOS High Sierra 10.13.5. When I look in `libtorch/lib` I see `libmkldnn.dylib` but not `libmklml.dylib` as it requires.

**Comment by soumith** [comment]
cc: @pjh5 looks like a missing copying of `libmklml.dylib` in our OSX libtorch builds.

**Comment by yukw777** [comment]
Seeing the same thing.

**Comment by yngtodd** [comment]
Correct me if I am wrong, but that solution is not answering the original issue:

```
ld: warning: ignoring file libtorch/lib/libtorch.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): libtorch/lib/libtorch.so
```

I was having the same issue when trying to run the minimal cpp frontend example here: https://pytorch.org/cppdocs/installing.html

I grabbed libtorch linked on the main pytorch site: 
```
https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.0.1.zip
```

You are right, `libtorch` had neither `libmklml.dylib` nor `libiomp5.dylib` in `libtorch/lib`. However, copying those files to that location did not solve the issue for me.

I was able to get the minimal example by giving cmake the `DCMAKE_PREFIX_PATH` for Pytorch's torch library (compiled from source):
```
cmake -DCMAKE_PREFIX_PATH=/path/to/pytorch/torch ..
```
I am going to try to test compiling the DCGAN example for the cpp frontend in this same way. I assume that this is not going to work, that we will ultimately need to point to `libtorch` for something like data loading or some other utility. 

I am on Mac 10.14.3

**Comment by mark-fangzhou-xie** [comment]
I was facing almost same problems here and managed to fix it by downloading `libmklml.dylib` and `libiomp5.dylib` from [here](https://github.com/intel/mkl-dnn/releases). Just in case anyone needs this, please do NOT download the newest post there! Instead find the `mklml` file instead of `mkldnn` file. 

![image](https://user-images.githubusercontent.com/45321577/62161402-12d8da80-b2e4-11e9-8b2c-bfe505df7f8c.png)

I didn't find the difference between `mklml` and `mkldnn` at first, but succeeded once downloaded the `mklml` ones.

**Comment by ddetone** [comment]
@soumith Any idea whats going on with these missing MKL libraries for the mac c++ libtorch? Somehow this is still an issue dating back since 2018, and even after pytorch 1.3, I just tried it out again.

The workaround done by @mark-fangzhou-xie above works for me, which involves manually copying the dylib files from old (pre v1.0) intel binaries.

**Comment by soumith** [comment]
@ddetone I fixed all such issues for v1.3.0 in https://github.com/pytorch/pytorch/issues/18996 or so I thought. But I only fixed them for pip and conda packages, not libtorch.
I'm looking into it right now and will fix libtorch too.

**Comment by soumith** [comment]
will kick off new binary builds as the fix went in. will close the issue after the builds are uploaded and live.

**Comment by soumith** [comment]
this is fixed now with fixed binaries that are re-uploaded.
