### ISSUE TITLE
Time cost of using libtorch is much longer than python API

### ISSUE THREAD

**Issue by IcewineChen** [pytorch/pytorch#14737]
I used libtorch(gpu version) to load a .pt file that generated from a .pth model(a 3d resnext-101 model), and then move the module and input to gpu, I got a time cost of 2.04084s. But when I use python code to load the same .pth model on the same machine , I just get a 0.09808063507080078s time cost. Here is my c++ code and python code, I'm sure that the module and input in c++ and python code is cuda type:
python : 
```    
    testinpur = torch.rand(size=(1,3,64,112,112)).cuda()
    start = time.time()
    model(testinpur)
    end = time.time()
    # end = datetime.datetime.now()
    print(end-start)
```
c++:
```
    inputs.push_back(_inputFormat);      // the size of _inputFormat is (1,3,64,112,112)
    double t = (double)cv::getTickCount();
    module->forward(inputs).toTensor();    
    t = (double)cv::getTickCount() - t;
```
So what's the problem? Sorry for interrupting you @goldsborough . Thanks for you help.

**Comment by laggui** [comment]
> I used libtorch(gpu version) to load a .pt file that generated from a .pth model(a 3d resnext-101 model), and then move the module and input to gpu, I got a time cost of 2.04084s. But when I use python code to load the same .pth model on the same machine , I just get a 0.09808063507080078s time cost. Here is my c++ code and python code, **I'm sure that the module and input in c++ and python code is cuda type**:
> python :
> 
> ```
>     testinpur = torch.rand(size=(1,3,64,112,112)).cuda()
>     start = time.time()
>     model(testinpur)
>     end = time.time()
>     # end = datetime.datetime.now()
>     print(end-start)
> ```
> 
> c++:
> 
> ```
>     inputs.push_back(_inputFormat);      // the size of _inputFormat is (1,3,64,112,112)
>     double t = (double)cv::getTickCount();
>     module->forward(inputs).toTensor();    
>     t = (double)cv::getTickCount() - t;
> ```
> 
> So what's the problem? Sorry for interrupting you @goldsborough . Thanks for you help.

From bolded part: how exactly are you sure that your model and its inputs are loaded onto your GPU? From the very small C++ sample code you provided, it does not look like you are loading anything on your GPU.

For example
```
// Check for cuda
if (torch::cuda::is_available()) {
    std::cout << "Moving model to GPU" << std::endl;
    module->to(at::kCUDA);
}
...
// Move tensor to CUDA memory
inputs = inputs.to(at::kCUDA);
```

I have some [sample code](https://github.com/laggui/pytorch-cpp/blob/master/libtorch/predict.cpp) from a couple weeks ago I haven't updated, but should still give you a good starting point with libtorch if you want.

**Comment by IcewineChen** [comment]
> > I used libtorch(gpu version) to load a .pt file that generated from a .pth model(a 3d resnext-101 model), and then move the module and input to gpu, I got a time cost of 2.04084s. But when I use python code to load the same .pth model on the same machine , I just get a 0.09808063507080078s time cost. Here is my c++ code and python code, **I'm sure that the module and input in c++ and python code is cuda type**:
> > python :
> > ```
> >     testinpur = torch.rand(size=(1,3,64,112,112)).cuda()
> >     start = time.time()
> >     model(testinpur)
> >     end = time.time()
> >     # end = datetime.datetime.now()
> >     print(end-start)
> > ```
> > c++:
> > ```
> >     inputs.push_back(_inputFormat);      // the size of _inputFormat is (1,3,64,112,112)
> >     double t = (double)cv::getTickCount();
> >     module->forward(inputs).toTensor();    
> >     t = (double)cv::getTickCount() - t;
> > ```
> > So what's the problem? Sorry for interrupting you @goldsborough . Thanks for you help.
> 
> From bolded part: how exactly are you sure that your model and its inputs are loaded onto your GPU? From the very small C++ sample code you provided, it does not look like you are loading anything on your GPU.
> 
> For example
> 
> ```
> // Check for cuda
> if (torch::cuda::is_available()) {
>     std::cout << "Moving model to GPU" << std::endl;
>     module->to(at::kCUDA);
> }
> ...
> // Move tensor to CUDA memory
> inputs = inputs.to(at::kCUDA);
> ```
> I have some [sample code](https://github.com/laggui/pytorch-cpp/blob/master/libtorch/predict.cpp) from a couple weeks ago I haven't updated, but should still give you a good starting point with libtorch if you want.

Thanks for you help, but I'sure that I convert my input and module on gpu with cuda type , I have checked this point. Now I have solved the problem, the cost is caused by the model initialize on gpu.
After the first time of forward, the speed wiil be fast. I'll closed this issue. Sorry for interrupt.
