### ISSUE TITLE
[Caffe2] invalid output constraint build error

### ISSUE THREAD

**Issue by mhs4670go** [pytorch/pytorch#14749]
I'm trying to build Caffe2 with glog looking install guide (Platform: Android, Install Type: Build From Source)

but there are too many errors which too hard to understand for me..

first.. this is my command
./build_android.sh -DUSE_GLOG=ON -DANDROID_ABI=arm64-v8a -DANDROID_TOOLCHAIN=clang -Dpybind11_INCLUDE_DIR=/usr/include/pybind11 -DGLOG_LIBRARY=/usr/lib/x86_64-linux-gnu/libglog.so -DGLOG_INCLUDE_DIR=/usr/include

there are many errors,, but 
/usr/include/bits/mathinline.h:614:9: error: invalid output constraint '=t' in
      asm
                    : "=t" (__value), "=&q" (__ignore), "=m" (__cwtmp),       \
                      ^
/usr/include/bits/mathinline.h:614:9: error: invalid output constraint '=t' in
      asm
/usr/include/bits/mathinline.h:614:9: error: invalid output constraint '=t' in
      asm
/usr/include/bits/mathinline.h:632:9: error: invalid output constraint '=t' in
      asm
                    : "=t" (__value), "=&q" (__ignore), "=m" (__cwtmp),       \
                      ^
[  0%] Built target c10_utils_gpu
/usr/include/bits/mathinline.h:632:9: error: invalid output constraint '=t' in
      asm
/usr/include/bits/mathinline.h:632:9: error: invalid output constraint '=t' in
      asm
/usr/include/bits/mathinline.h:739:3: error: invalid input constraint 't' in asm
  __lrint_code;
  ^
something like,, most of errors are something like that..

before that error, 

summary is here
- std::exception_ptr is supported.
-- NUMA is disabled
-- Turning off deprecation warning due to glog.
-- Use custom protobuf build.
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/home/joe/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- The BLAS backend of choice:Eigen
-- Brace yourself, we are building NNPACK
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Caffe2: Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Using third party subdirectory Eigen.
-- Could NOT find pybind11 (missing: pybind11_DIR)
-- System pybind11 found
-- pybind11 include dirs: /usr/include/pybind11
-- Using custom protoc executable
-- 
-- ******** Summary ********
--   CMake version         : 3.10.2
--   CMake command         : /usr/bin/cmake
--   System                : Android
--   C++ compiler          : /home/joe/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
--   C++ compiler version  : 7.0
--   CXX flags             : -isystem /home/joe/Android/Sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions  -Wno-deprecated -fvisibility-inlines-hidden -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : 
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /home/joe/pytorch/install
--   CMAKE_MODULE_PATH     : /home/joe/pytorch/cmake/Modules
-- 
--   ONNX version          : 1.3.0
--   ONNX NAMESPACE        : onnx_c2
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : OFF
-- NCCL operators skipped due to no CUDA support
-- Excluding ideep operators as we are not using ideep
-- Excluding image processing operators due to no opencv
-- Excluding video processing operators due to no opencv
-- MPI operators skipped due to no MPI support
CMake Warning at CMakeLists.txt:389 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.  Other settings may generate files that are not well
  tested.

CMake Warning at CMakeLists.txt:440 (message):
  Generated cmake files are only available when building shared libs.

-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.10.2
--   CMake command         : /usr/bin/cmake
--   System                : Android
--   C++ compiler          : /home/joe/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
--   C++ compiler version  : 7.0
--   BLAS                  : Eigen
--   CXX flags             : -isystem /home/joe/Android/Sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions  -Wno-deprecated -fvisibility-inlines-hidden -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -Wno-unused-but-set-variable -Wno-maybe-uninitialized
--   Build type            : Release
--   Compile definitions   : ONNX_NAMESPACE=onnx_c2
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /home/joe/pytorch/install
-- 
--   TORCH_VERSION         : 1.0.0
--   CAFFE2_VERSION        : 1.0.0
--   BUILD_ATEN_MOBILE     : ON
--   BUILD_ATEN_ONLY       : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Protobuf compiler   : 
--     Protobuf includes   : 
--     Protobuf libraries  : 
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : OFF
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_SHARED_LIBS     : OFF
--   BUILD_TEST            : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FBGEMM            : OFF
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : ON
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MKLDNN            : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_NCCL              : OFF
--   USE_NNPACK            : ON
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : OFF
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_QNNPACK           : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : ON
--     USE_MPI             : OFF
--     USE_GLOO            : OFF
--     USE_GLOO_IBVERBS    : OFF
--   Public Dependencies  : Threads::Threads;glog::glog
--   Private Dependencies : qnnpack;nnpack;cpuinfo;fp16;log;onnxifi_loader;dl
-- Configuring done
WARNING: Target "libprotoc" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "protoc" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.

I don't know why...... :(

I'm beginner of this field.. so, sorry for not enough information..

please somebody help me..

**Comment by ptrsp** [comment]
nbbn

**Comment by POINTY097** [comment]
I have a similar issue, how did you fix this?
