### ISSUE TITLE
dataloader test is flaky

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#1475]
Seen this twice on contbuilds:

```
======================================================================
FAIL: test_sequential_batch (__main__.TestDictDataLoader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataloader.py", line 252, in test_sequential_batch
    self.assertEqual(set(sample.keys()), {'a_tensor', 'another_dict'})
  File "/home/travis/build/pytorch/pytorch/test/common.py", line 189, in assertEqual
    self.assertEqual(x_, y_, prec, message)
  File "/home/travis/build/pytorch/pytorch/test/common.py", line 186, in assertEqual
    super(TestCase, self).assertEqual(x, y)
AssertionError: 'a_tensor' != 'another_dict'
- a_tensor
+ another_dict
```

**Comment by ethanluoyc** [comment]
@soumith Indeed, my PR https://github.com/pytorch/pytorch/pull/1315 also failed on this error. What can be a potential cause of this problem?

**Comment by apaszke** [comment]
It's probably because `assertEqual` doesn't have a special case for sets, and sets are unordered, so iterating over them doesn't have to yield objects in the same order (even if they have the same contents).

**Comment by ethanluoyc** [comment]
@soumith @apaszke I managed to fix the bug in the test suite. It helps me pass #1315. However, I am not sure if my fix is a good idea. Basically, it has an additional checking to see if the arguments provided are sets.

**Comment by apaszke** [comment]
@ethanluoyc your commit should fix that

**Comment by ngimel** [comment]
I've just hit this error on a freshly rebuilt pytorch from master.
