### ISSUE TITLE
inconsistent sort

### ISSUE THREAD

**Issue by simonm3** [pytorch/pytorch#14756]
The sort order for tensor.unique() defaults to "unsorted" but in practice is ascending on gpu and descending on cpu. It would be clearer if the sort order defaulted to ascending on both; or at least was consistent to avoid unpredictable results when moving between cpu and gpu. 
```
I am on pytorch '1.0.0.dev20180928'

a=tensor([1,1,2,3]).cuda()
b=tensor([1,1,2,3]).cpu()
a.unique(), b.unique()
```
(tensor([1, 2, 3]), tensor([3, 2, 1], device='cpu'))

**Comment by zou3519** [comment]
We don't guarantee it is consistent unless you pass it the `sorted` argument: https://pytorch.org/docs/master/torch.html#torch.unique

**Comment by simonm3** [comment]
Sure I read that already. But most uses will require it sorted; and since it is actually sorted then would make more sense to sort it the same way on GPU and CPU. Otherwise your application produces different results on GPU - which is a pain to diagnose. Would be more user friendly to just sort it ascending on both unless there is some massive efficiency gain from not doing this.

**Comment by soumith** [comment]
yea, it's a no-harm thing to change, though we dont provide such a guarantee.
I'll send in a patch now.

**Comment by fmassa** [comment]
This is actually not a problem I think.

By default, `sorted=False`, and the fact that the output seems to be sorted is an implementation detail.

```python
a=tensor([1,1,2,3]).cuda()
b=tensor([1,1,2,3]).cpu()

print(a.unique(sorted=True))
print(b.unique(sorted=True))
```
returns, as expected
```
tensor([1, 2, 3])
tensor([1, 2, 3], device='cuda:0')
```

See this for example
```python
a = torch.tensor([1.5,1,2,3])
a.unique()
> tensor([3.0000, 2.0000, 1.0000, 1.5000])
a.cuda().unique()
> tensor([1.0000, 1.5000, 2.0000, 3.0000], device='cuda:0')
```

**Comment by fmassa** [comment]
So except if we change the default to `sorted=True` (which is reasonable in my opinion), then I don't think there is nothing we should do about it.

**Comment by simonm3** [comment]
If pytorch is "a replacement for NumPy to use the power of GPUs" then numpy
unique is sorted by default. And arguably that is more intuitive. Certainly
you would expect same on GPU and CPU wherever possible.

**Comment by zou3519** [comment]
Let's change the default to sorted=True

**Comment by fmassa** [comment]
Fixed via https://github.com/pytorch/pytorch/pull/15379
