### ISSUE TITLE
When will the pytorch 1.0 stable version release?

### ISSUE THREAD

**Issue by HuangZhanPeng** [pytorch/pytorch#14791]
### Please note that this issue tracker is not a help form and this issue will be closed.
It said that will release before nips 2018. be eagerly looking forward to the stable version
We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soumith** [comment]
friday
