### ISSUE TITLE
`NO_CUDA` and `USE_CUDA` is not unified

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#14801]
When `NO_CUDA` is set to `1`, it still builds with CUDA. Now that the flag has been replaced by `USE_CUDA`, we should delete the description of it from `setup.py` and unify them into one flag.

**Comment by orionr** [comment]
@peterjc123 we should unify them. setup.py should be converting all USE_CUDA to NO_CUDA and vice versa. If not, we should fix it. Also, we typically do USE_* for things that are default off and NO_* for things that are default on, so NO_CUDA is the right flag name even if it is currently broken.

**Comment by orionr** [comment]
And `NO_CUDA=1 python setup.py build` has worked for some other people, so maybe there's a specific case where this is failing. Can you give more details? Thanks.

**Comment by orionr** [comment]
Got it. That's very possible that libtorch doesn't do the same translation from NO_CUDA to USE_CUDA. cc @goldsborough to confirm. CMake itself just takes in USE_*

**Comment by goldsborough** [comment]
I don't see any mention of `NO_CUDA` in https://github.com/pytorch/pytorch/blob/master/torch/CMakeLists.txt. @orionr should we add this translation?

**Comment by orionr** [comment]
So for libtorch build do we go directly to CMake? I felt like there was a build script somewhere that was called and, if so, we could do the conversion there? In general, we only do the USE_/NO_ conversion in setup.py and hopefully can keep the NO_* version out of CMakeLists.txt

**Comment by peterjc123** [comment]
We should do this conversion in `tools/build_libtorch.py`, just like what we have done in `setup.py`.

**Comment by soumith** [comment]
agree. can you send a PR @peterjc123 ?

**Comment by peterjc123** [comment]
@soumith Sure. Should I extract these function and merge them into `tools.setup_helpers.env`?

**Comment by soumith** [comment]
@peterjc123 sure.
