### ISSUE TITLE
libcudart.so not found when compiling with NO_DISTRIBUTED=1

### ISSUE THREAD

**Issue by mfuntowicz** [pytorch/pytorch#14805]
When compiling PyTorch from sources (a80a46a6d01b792399d5860e00923d096399952f) with the flag NO_DISTRIBUTED=1 it ends up with the Following error : 

`couldn't find libcudart. Make sure CUDA libraries are installed in adefault location, or that they're in LD_LIBRARY_PATH` comming from there : https://github.com/pytorch/pytorch/blob/master/torch/cuda/__init__.py#L66

Compiling with Distributed support makes the error disappear.

Happened on Fedora 29, using GCC/G++ 7.3.1 with CUDA 9.2 / CuDNN 7.4.1 / GTX 1080 Ti

**Comment by suo** [comment]
Heads up @anderspapitto that me, @zou3519, and @yf225 have gotten this problem as well.

**Comment by SsnL** [comment]
I've seen it too. I'm pretty sure @anderspapitto 's aware of it because he submitted #14496 .

**Comment by mfuntowicz** [comment]
Took a look before submitting this issue, but didn't catch #14496...

**Comment by suo** [comment]
Closing as a dupe then

**Comment by SsnL** [comment]
I'll keep this open as there are two separate issues here: (1) build (2) CI coverage.

**Comment by lianghong** [comment]
Same issues , Ubuntu 18.04 with GCC/G++ 7.3, CUDA 10 / CuDNN 7.4 / GTX 1080 Ti

**Comment by obilaniu** [comment]
@soumith This is completely normal.

On Linux, `LoadLibrary(None)` corresponds approximately to `dlopen(NULL, RTLD_NOW|RTLD_LOCAL)`. This gives you a special handle that allows you to search the symbols of the executable, and the symbols exported by shared libraries the executable may have loaded.

- If `libcudart.so` is dynamically linked, then of course its symbols are part of those available to the search.
- But if `libcudart_static.a` is statically linked, then
  - It's definitely not part of the `python` executable
  - It must have been statically linked into one or more dynamic libraries that have already been loaded, such as `libc10_cuda.so`.
  - And at least one of those dynamic libraries _must have publicly **re-exported**_ `libcudart_static.a`'s symbols (`cuda*`) in order for `dlsym()` to be able to find them.

But re-exporting symbols is duplicatively wasteful and error-prone. It seems far better to do the natural thing and require dynamic linking of `libcudart.so`, unless you have some particularly compelling usecase for static linking I'm not aware of.

References:
  - http://man7.org/linux/man-pages/man3/dlopen.3.html
  - https://software.intel.com/sites/default/files/m/a/1/e/dsohowto.pdf

**Comment by soumith** [comment]
@obilaniu that's an awesome explanation, thanks a lot!

**Comment by tz579** [comment]
@soumith @obilaniu @suo @SsnL 
Could anybody provide some hints for a short-term fix of this problem?
Thanks a lot!

**Comment by suo** [comment]
@tz579 Try not setting NO_DISTRIBUTED=1 in your build

**Comment by tz579** [comment]
Thanks @suo for mentioning this.
But is there any other solutions such as re-linking to the .so rather than .a file, as mentioned in one of the comment of @soumith ?
Thanks!

**Comment by mfuntowicz** [comment]
@soumith, @SsnL Commenting on this quite old post, but the problem did reappear yesterday when I was building pytorch from master with NO_DISTRIBUTED=1.

Trying to allocate a tensor on cuda:0 makes the error appear:
`couldn't find libcudart. Make sure CUDA libraries are installed in adefault location, or that they're in LD_LIBRARY_PATH`
