### ISSUE TITLE
[c10d] Use flattenDenseTensors to improve performance of ProcessGroupGloo allgather

### ISSUE THREAD

**Issue by janewangfb** [pytorch/pytorch#14812]
## 🚀 Feature
Currently the code first copies output tensors into temporary tensors on the CPU side and then flattening them. We can use flattenDenseTensors to save one copying.

## Motivation

Improve performance.

## Pitch

With this change, all c10d tests should still work.

## Alternatives

Not implement this.

**Comment by zhaojuanmao** [comment]
looks like it is already using flattenDenseTensors in allgather now
