### ISSUE TITLE
when a Variable is 0, it is determined as 'True'

### ISSUE THREAD

**Issue by zhengyunqq** [pytorch/pytorch#1482]
b = Variable(torch.zeros(1))
if b[0]:
   print 'true'
else:
   print 'false'

above code outputs 'true',  is this a bug?

**Comment by soumith** [comment]
this is expected, as a Variable[0] returns another Variable. You might need to do b.data[0]
This will be solved once we introduce autograd.Scalar, which we are tracking in https://github.com/pytorch/pytorch/issues/1433

**Comment by apaszke** [comment]
Still, we should raise an error if someone attempts to convert a Variable to a bool. I think it's the cause of #1391.

**Comment by lantiga** [comment]
Issue can be closed now.
