### ISSUE TITLE
How to use nn.conv2D with halfTensor?

### ISSUE THREAD

**Issue by bolyor** [pytorch/pytorch#14843]
## ❓ Questions and Help
I want to create some FP16 data with conv 2D but got an error:
RuntimeError: thnn_conv2d_forward is not_implemented for type torch.HalfTensor

Can I simply use FP32 data for conv2D, and just downcasting it to FP16 before I use data? 
Thanks.
Ubuntu 16.04
Python version:2.7
Pytorch version:0.4.1
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soumith** [comment]
please use the discussion forum for questions
