### ISSUE TITLE
Suggested installation command using pip does not use TLS

### ISSUE THREAD

**Issue by cathalgarvey** [pytorch/pytorch#14847]
When using the install-command-builder on (for example) [https://pytorch.org/get-started/locally/][], if one selects `pip` and no-CUDA the suggested command includes an unsecured URL such as `pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl` - I manually changed this to `pip3 install --user https://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl` and installed without issue.

If TLS is available, it should always be used. If it is unavailable, then software cannot be deployed from that endpoint, so installation by URI should be disabled entirely until TLS can be configured. In this case, the fix appears trivial: add an `s` to the template URIs. :)

Thanks!

**Comment by JoelMarcey** [comment]
I will take a look at this.

**Comment by cathalgarvey** [comment]
:) Thanks!

On 10 December 2018 22:21:36 GMT+00:00, Soumith Chintala <notifications@github.com> wrote:
>Closed #14847 via pytorch/pytorch.github.io#143.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pytorch/pytorch/issues/14847#event-2017211441

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
