### ISSUE TITLE
Torch.ge not producing reasonable result with torch.int tensor

### ISSUE THREAD

**Issue by Maphist0** [pytorch/pytorch#14846]
## 🐛 Bug

It seems that while using torch.ge on a torch.int tensor (e.g. converted from a numpy array), the result is not reasonable.
As a reference, applying torch.ge on a torch.FloatTensor performs correctly.
Originally reported in the pytorch [forum](https://discuss.pytorch.org/t/torch-ge-not-producing-reasonable-result-with-torch-int-tensor/31424).

## To Reproduce

```
import torch
import numpy as np

# Create a torch.int tensor from numpy
a_np = np.asarray([0, 1, 1, 0, 0])
a = torch.from_numpy(a_np)

# Create a torch.float tensor directly
b = torch.FloatTensor([0, 1, 1, 0, 0])

# Perform torch.ge on a and b
print(torch.ge(a, 0.5))   # Output: tensor([ 1,  1,  1,  1,  1], dtype=torch.uint8)
print(torch.ge(b, 0.5))   # Output: tensor([ 0,  1,  1,  0,  0], dtype=torch.uint8)
```

## Expected behavior

torch.ge(a, 0.5) should output the same as torch.ge(b, 0.5), i.e. [0, 1, 1, 0, 0].

## Environment

Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration: 
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80

Nvidia driver version: 384.90
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/local/MATLAB/R2017a/bin/glnxa64/libcudnn.so.5.1.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6.0.21
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7.0.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch                   0.4.0            py36hd73e86b_0  
[conda] torchsummary              1.4                       <pip>
[conda] torchvision               0.2.1                    py36_0

**Comment by zou3519** [comment]
We are working on this (see #9515)

**Comment by mruberry** [comment]
This has been fixed!
