### ISSUE TITLE
Document Mistakes List 

### ISSUE THREAD

**Issue by ycszen** [pytorch/pytorch#1484]
We are translating the official documents to Chinese. In this progress, we find some mistake in the official documents, so list as below. Welcome to add some mistake you find in the documents.
**Formate: checkbox+document address+mistake detail**

- [x] [avg_pool3d](http://pytorch.org/docs/nn.html#avg-pool3d1),  the `kt` should be `dt`
- [x] [avg_pool2d](http://pytorch.org/docs/nn.html#avg-pool2d1),  the explanation of parameters `ceil_mode` and `count_include_pad` cannot be understanding.

**Comment by Nintorac** [comment]
![pytorch_spelling](https://cloud.githubusercontent.com/assets/24326299/25989935/c39fc47e-36b2-11e7-8124-183a702291c6.png)

'with' rather than 'width'

**Comment by zou3519** [comment]
Should be fixed now:
![image](https://user-images.githubusercontent.com/5652049/32196111-f03f1876-bd95-11e7-8c45-851e760a81db.png)
