### ISSUE TITLE
Document what is C10

### ISSUE THREAD

**Issue by christoph-conrads** [pytorch/pytorch#14850]
C10 seems to have an increasingly important role throughout the PyTorch code base (e.g., see #6325 or count the number of open issues containing "c10") yet I was unable to find a high-level description about it. There are only "rumors" to be found about C10, see for example [this post](https://discuss.pytorch.org/t/pytorch-and-caffe2-convergence/21713/4) at pytorch.org:
> I read on github, that there is a new backend called C10 in progress which combines features and backends from ATen and Caffe2. This backend should be a more generic one which means that adding new tensor types and similar stuff will be easier (the actual discussion was about introducing complex tensors).

Someone else on [Reddit](https://www.reddit.com/r/MachineLearning/comments/8xurkp/n_tensorflow_190_is_out/e27ewhz/):
> I'd never heard of C10 until you posted this, so caveat emptor, but from the few Google hits available it seems that the major motivations for C10 include:
>
> * Common Tensor ops for PyTorch and Caffe2 (only PyTorch uses ATen)
> * Pluggable tensor ops/backend (maybe easing future AMD, TPU, etc support?)
>
> There's also talk of C10 helping integration of Complex tensor support for PyTorch, which helps give an idea of the level of abstraction they are shooting for.

At the minimum, please add a README to the pytorch/c10 directory briefly describing the project.

**Comment by frams163com** [comment]
c10 may be short for **C**ore **Ten**sor Library.  However,  there is ATen, which is A Tensor Libraray. The naming convention is a little weird.

**Comment by jeffreyksmithjr** [comment]
Interpreting this as a request for documentation.

If you just want an answer to what is C10 for yourself, I would point you to the Discuss forums: https://discuss.pytorch.org/

**Comment by luxe** [comment]
does the 10 imply cuda 10?

**Comment by RomeoV** [comment]
> 
> 
> c10 may be short for **C**ore **TEN**sor Library. However, there is ATen, which is A Tensor Libraray. The naming convention is a little weird.

According to this, no. It's a coincidence that cuda is on the version 10.

**Comment by robertknight** [comment]
According to http://blog.ezyang.com/2019/05/pytorch-internals/, the history of the c10 name is:

> c10/, which is a pun on Caffe2 and A"Ten" (get it? Caffe 10) contains the core abstractions of PyTorch, including the actual implementations of the Tensor and Storage data structures.

**Comment by kevint324** [comment]
[Acronyms Seriously Suck - Elon Musk](https://gist.github.com/anonymous/ca9721fbf27e77667abb)

 (By the way, THP stands for TorcH Python, not to be confused with THPP, TorcH C++). 

Sometimes acronyms can be challenging, like TH, THC, THNN, THCUNN, THP, THPP.

And I'd never thought of that the core module's name is made from a pun.

**Comment by HungNgoCT** [comment]
Hi,

I read an open source code with an error "namespace "c10::gut"  has no member "to_string"" in the statement c10::guts::to_string(p.unsafeGetTensorImpl())

I predict that it relates to version of C10.

Could anyone help me to correct this?

Thank you

**Comment by Downchuck** [comment]
@HungNgoCT It was removed per https://github.com/pytorch/pytorch/pull/108480
