### ISSUE TITLE
JoinTable like operation when combining multiple CNNs

### ISSUE THREAD

**Issue by xypan1232** [pytorch/pytorch#1486]
Hi,

I want to combine multiple CNNs from different branch with different inputs, and want to have a final layer to combine the outputs, could i ask how can i implement it? thanks

**Comment by apaszke** [comment]
Just wrap them in a list or use `torch.cat` in the `forward` method of your model.

Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
