### ISSUE TITLE
distributed data parallel, gloo backend works, but nccl deadlock,

### ISSUE THREAD

**Issue by htlchh** [pytorch/pytorch#14870]
I have encountered a problem when using DistributedDataParallel with multi-processes.
I use two machines, a docker machine A and a physical machine B: 
A is the master and init_method = 'tcp://ip_A:free_port', and B can telnet the address 'tcp://ip_A:free_port'.

with gloo backend, it works well. But with nccl backend, it got stucked.
Runtime environment:
python 3.6 + pytorch-1.0-dev
DistributedDataParallel and multiprocessing,
node A: P40, node B: K40
2 nodes, 4 processes each node and each process runs in a single GPU
world-size 2, rank 0-7

configurations and codes:
```
    if args.multiprocessing_distributed:
        args.world_size = ngpus_per_node * args.world_size
        mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
    else:
        main_worker(args.gpu, ngpus_per_node, args)
```

```
    if args.distributed:
        if args.dist_url == "env://" and args.rank == -1:
            args.rank = int(os.environ["RANK"])
        if args.multiprocessing_distributed:
            args.rank = args.rank * ngpus_per_node + gpu
        dist.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
                                world_size=args.world_size, rank=args.rank)
```

```
            torch.cuda.set_device(args.gpu)
            model.cuda(args.gpu)
            args.batch_size = int(args.batch_size / ngpus_per_node)
            model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
```

**Comment by syed-ahmed** [comment]
Could you please post a log of your run with `NCCL_DEBUG` set to 1 in your environment?

**Comment by htlchh** [comment]
> Could you please post a log of your run with `NCCL_DEBUG=INFO` set in your environment?

machine A:

Use GPU: 3 for training
rank: 3
Use GPU: 2 for training
rank: 2
Use GPU: 0 for training
rank: 0
Use GPU: 1 for training
rank: 1
docker-100-88-66-138:49604:49604 [0] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:49604:49604 [0] INFO NET/IB : Using interface eth1 for sideband communication
docker-100-88-66-138:49604:49604 [0] INFO NET/IB: [0] mlx4_0:2/RoCE 
docker-100-88-66-138:49604:49604 [0] INFO Using internal Network IB
docker-100-88-66-138:49604:49604 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
docker-100-88-66-138:49604:49604 [0] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:49604:49604 [0] INFO NET/Socket : 1 interfaces found
NCCL version 2.2.13+cuda8.0
docker-100-88-66-138:49605:49605 [1] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:49605:49605 [1] INFO NET/IB : Using interface eth1 for sideband communication
docker-100-88-66-138:49604:49871 [0] INFO comm 0x2ad388093600 rank 0 nranks 8
docker-100-88-66-138:49604:49871 [0] INFO CUDA Dev 0, IB Ports : mlx4_0/2(PIX) 
docker-100-88-66-138:49605:49605 [1] INFO NET/IB: [0] mlx4_0:2/RoCE 
docker-100-88-66-138:49605:49605 [1] INFO Using internal Network IB
docker-100-88-66-138:49605:49605 [1] INFO Using NCCL Low-latency algorithm for sizes below 16384
docker-100-88-66-138:49605:49873 [1] INFO comm 0x2b1f3c093600 rank 1 nranks 8
docker-100-88-66-138:49605:49873 [1] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:49605:49873 [1] INFO NET/Socket : 1 interfaces found
docker-100-88-66-138:49605:49873 [1] INFO CUDA Dev 1, IB Ports : mlx4_0/2(PIX) 
docker-100-88-66-138:49606:49606 [2] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:49606:49606 [2] INFO NET/IB : Using interface eth1 for sideband communication
docker-100-88-66-138:49607:49607 [3] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:49607:49607 [3] INFO NET/IB : Using interface eth1 for sideband communication
docker-100-88-66-138:49606:49606 [2] INFO NET/IB: [0] mlx4_0:2/RoCE 
docker-100-88-66-138:49606:49606 [2] INFO Using internal Network IB
docker-100-88-66-138:49606:49606 [2] INFO Using NCCL Low-latency algorithm for sizes below 16384
docker-100-88-66-138:49607:49607 [3] INFO NET/IB: [0] mlx4_0:2/RoCE 
docker-100-88-66-138:49607:49607 [3] INFO Using internal Network IB
docker-100-88-66-138:49607:49607 [3] INFO Using NCCL Low-latency algorithm for sizes below 16384
docker-100-88-66-138:49606:49875 [2] INFO comm 0x2b8e90093600 rank 2 nranks 8
docker-100-88-66-138:49606:49875 [2] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:49606:49875 [2] INFO NET/Socket : 1 interfaces found
docker-100-88-66-138:49606:49875 [2] INFO CUDA Dev 2, IB Ports : mlx4_0/2(PIX) 
docker-100-88-66-138:49607:49877 [3] INFO comm 0x2b6b20093600 rank 3 nranks 8
docker-100-88-66-138:49607:49877 [3] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:49607:49877 [3] INFO NET/Socket : 1 interfaces found
docker-100-88-66-138:49607:49877 [3] INFO CUDA Dev 3, IB Ports : mlx4_0/2(PIX) 
docker-100-88-66-138:49604:49871 [0] INFO Using 256 threads
docker-100-88-66-138:49604:49871 [0] INFO Min Comp Cap 3
docker-100-88-66-138:49604:49871 [0] INFO NCCL_SINGLE_RING_THRESHOLD=131072
docker-100-88-66-138:49604:49871 [0] INFO Ring 00 :    0   1   2   3   4   5   6   7
docker-100-88-66-138:49606:49875 [2] INFO Ring 00 : 2[2] -> 3[3] via P2P/IPC
docker-100-88-66-138:49605:49873 [1] INFO Ring 00 : 1[1] -> 2[2] via P2P/IPC
docker-100-88-66-138:49604:49871 [0] INFO 7 -> 0 via NET/IB/0/GDRDMA
docker-100-88-66-138:49604:49871 [0] INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC
docker-100-88-66-138:49607:49877 [3] INFO NET/IB: Dev 0 Port 2 qpn 613 mtu 3 GID 0 (80FE/E1E30401009A0DEC)

**Comment by syed-ahmed** [comment]
Thanks for posting the log! I am not sure from the log exactly why it's hanging. May be if you could post a minimal reproducing code, we could try looking at it on our end. Also what exact commands are you using? Here are some more environment variables you could try to see if they fixes your issue:
```
export NCCL_SOCKET_IFNAME=^docker0 # MUST needed for running multi-node with docker
export NCCL_DEBUG=INFO # (optional) prints NCCL specific, useful for debugging
export NCCL_IB_HCA=mlx4_0 # (optional) needed if you want to use a specific network interface like RoCE. you can find about available interfaces using ibstatus.
```

**Comment by htlchh** [comment]
The code is exactly the example : https://github.com/pytorch/examples/tree/master/imagenet
I have run experiments with exporting the environment variables: NCCL_SOCKET_IFNAME=^docker0 and NCCL_DEBUG=INFO.
My machines:
rank 0 node : docker machine, cudnn-8, python-3.6, pytorch-1.0, 4 GPU
rank 1 node: docker machine, cudnn-9, python-3.7, pytorch-1.0, 4 GPU


the rank-0 node run log:
python3.7 main.py -a resnet50 --lr 0.01 --multiprocessing-distributed --world-size 2 --rank 0 data
Use GPU: 1 for training
Use GPU: 2 for training
Use GPU: 3 for training
Use GPU: 0 for training
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'

b8b857cb-e016-457b-8d8b-c5b1403413b6:39358:39358 [0] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
b8b857cb-e016-457b-8d8b-c5b1403413b6:39358:39358 [0] NCCL INFO Using internal Network Socket
b8b857cb-e016-457b-8d8b-c5b1403413b6:39358:39358 [0] NCCL INFO NET : Using interface lo:127.0.0.1<0>
b8b857cb-e016-457b-8d8b-c5b1403413b6:39358:39358 [0] NCCL INFO NET : Using interface eth1:9.73.128.149<0>
b8b857cb-e016-457b-8d8b-c5b1403413b6:39358:39358 [0] NCCL INFO NET/Socket : 2 interfaces found
NCCL version 2.3.7+cuda9.0
b8b857cb-e016-457b-8d8b-c5b1403413b6:39358:39358 [0] NCCL INFO rank 0 nranks 8


b8b857cb-e016-457b-8d8b-c5b1403413b6:39361:39361 [3] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
b8b857cb-e016-457b-8d8b-c5b1403413b6:39361:39361 [3] NCCL INFO Using internal Network Socket

b8b857cb-e016-457b-8d8b-c5b1403413b6:39359:39359 [1] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
b8b857cb-e016-457b-8d8b-c5b1403413b6:39359:39359 [1] NCCL INFO Using internal Network Socket
b8b857cb-e016-457b-8d8b-c5b1403413b6:39359:39359 [1] NCCL INFO rank 1 nranks 8
b8b857cb-e016-457b-8d8b-c5b1403413b6:39360:39360 [2] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
b8b857cb-e016-457b-8d8b-c5b1403413b6:39361:39361 [3] NCCL INFO rank 3 nranks 8
b8b857cb-e016-457b-8d8b-c5b1403413b6:39360:39360 [2] NCCL INFO Using internal Network Socket
b8b857cb-e016-457b-8d8b-c5b1403413b6:39360:39360 [2] NCCL INFO rank 2 nranks 8
b8b857cb-e016-457b-8d8b-c5b1403413b6:39358:39405 [0] NCCL INFO comm 0x7f273004b8c0 rank 0 nranks 8
b8b857cb-e016-457b-8d8b-c5b1403413b6:39359:39406 [1] NCCL INFO comm 0x7f6f9804b8c0 rank 1 nranks 8
b8b857cb-e016-457b-8d8b-c5b1403413b6:39359:39406 [1] NCCL INFO NET : Using interface lo:127.0.0.1<0>
b8b857cb-e016-457b-8d8b-c5b1403413b6:39359:39406 [1] NCCL INFO NET : Using interface eth1:9.73.128.149<0>
b8b857cb-e016-457b-8d8b-c5b1403413b6:39359:39406 [1] NCCL INFO NET/Socket : 2 interfaces found
b8b857cb-e016-457b-8d8b-c5b1403413b6:39360:39408 [2] NCCL INFO comm 0x7f782004b8c0 rank 2 nranks 8
b8b857cb-e016-457b-8d8b-c5b1403413b6:39360:39408 [2] NCCL INFO NET : Using interface lo:127.0.0.1<0>
b8b857cb-e016-457b-8d8b-c5b1403413b6:39360:39408 [2] NCCL INFO NET : Using interface eth1:9.73.128.149<0>
b8b857cb-e016-457b-8d8b-c5b1403413b6:39360:39408 [2] NCCL INFO NET/Socket : 2 interfaces found
b8b857cb-e016-457b-8d8b-c5b1403413b6:39361:39407 [3] NCCL INFO comm 0x7fe53804b8c0 rank 3 nranks 8
b8b857cb-e016-457b-8d8b-c5b1403413b6:39361:39407 [3] NCCL INFO NET : Using interface lo:127.0.0.1<0>
b8b857cb-e016-457b-8d8b-c5b1403413b6:39361:39407 [3] NCCL INFO NET : Using interface eth1:9.73.128.149<0>
b8b857cb-e016-457b-8d8b-c5b1403413b6:39361:39407 [3] NCCL INFO NET/Socket : 2 interfaces found



and rank-1 node run log:
python3 main.py -a resnet50 --lr 0.01 --multiprocessing-distributed --world-size 2 --rank 1 data
Use GPU: 2 for training
=> creating model 'resnet50'
Use GPU: 0 for training
=> creating model 'resnet50'
Use GPU: 3 for training
=> creating model 'resnet50'
Use GPU: 1 for training
=> creating model 'resnet50'
docker-100-88-66-138:19123:19123 [2] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:19123:19123 [2] INFO NET/IB : Using interface eth1 for sideband communication
docker-100-88-66-138:19123:19123 [2] INFO NET/IB: [0] mlx4_0:2/RoCE 
docker-100-88-66-138:19123:19123 [2] INFO Using internal Network IB
docker-100-88-66-138:19123:19123 [2] INFO Using NCCL Low-latency algorithm for sizes below 16384
docker-100-88-66-138:19123:19685 [2] INFO comm 0x2b8b20093600 rank 6 nranks 8
docker-100-88-66-138:19123:19685 [2] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:19123:19685 [2] INFO NET/Socket : 1 interfaces found
docker-100-88-66-138:19124:19124 [3] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:19124:19124 [3] INFO NET/IB : Using interface eth1 for sideband communication
docker-100-88-66-138:19124:19124 [3] INFO NET/IB: [0] mlx4_0:2/RoCE 
docker-100-88-66-138:19124:19124 [3] INFO Using internal Network IB
docker-100-88-66-138:19124:19124 [3] INFO Using NCCL Low-latency algorithm for sizes below 16384
docker-100-88-66-138:19122:19122 [1] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:19122:19122 [1] INFO NET/IB : Using interface eth1 for sideband communication
docker-100-88-66-138:19124:19694 [3] INFO comm 0x2b83d0093600 rank 7 nranks 8
docker-100-88-66-138:19124:19694 [3] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:19124:19694 [3] INFO NET/Socket : 1 interfaces found
docker-100-88-66-138:19122:19122 [1] INFO NET/IB: [0] mlx4_0:2/RoCE 
docker-100-88-66-138:19122:19122 [1] INFO Using internal Network IB
docker-100-88-66-138:19122:19122 [1] INFO Using NCCL Low-latency algorithm for sizes below 16384
docker-100-88-66-138:19122:19714 [1] INFO comm 0x2b0b98093600 rank 5 nranks 8
docker-100-88-66-138:19122:19714 [1] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:19122:19714 [1] INFO NET/Socket : 1 interfaces found
docker-100-88-66-138:19121:19121 [0] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:19121:19121 [0] INFO NET/IB : Using interface eth1 for sideband communication
docker-100-88-66-138:19121:19121 [0] INFO NET/IB: [0] mlx4_0:2/RoCE 
docker-100-88-66-138:19121:19121 [0] INFO Using internal Network IB
docker-100-88-66-138:19121:19121 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
docker-100-88-66-138:19121:19716 [0] INFO comm 0x2b014c093600 rank 4 nranks 8
docker-100-88-66-138:19121:19716 [0] INFO NET : Using interface eth1:100.88.66.138<0>
docker-100-88-66-138:19121:19716 [0] INFO NET/Socket : 1 interfaces found

docker-100-88-66-138:19123:19685 [2] include/socket.h:360 WARN Call to connect timeout : Connection refused
docker-100-88-66-138:19123:19685 [2] INFO transport/net_socket.cu:118 -> 2
docker-100-88-66-138:19123:19685 [2] INFO bootstrap.cu:28 -> 2 [Net]
docker-100-88-66-138:19123:19685 [2] INFO bootstrap.cu:238 -> 2
docker-100-88-66-138:19123:19685 [2] INFO init.cu:409 -> 2
docker-100-88-66-138:19123:19685 [2] INFO init.cu:536 -> 2
docker-100-88-66-138:19123:19685 [2] INFO misc/group.cu:70 -> 2 [Async thread]

docker-100-88-66-138:19123:19685 [2] include/socket.h:360 WARN Call to connect timeout : Connection refused
docker-100-88-66-138:19123:19685 [2] INFO transport/net_socket.cu:118 -> 2
docker-100-88-66-138:19123:19685 [2] INFO bootstrap.cu:28 -> 2 [Net]
docker-100-88-66-138:19123:19685 [2] INFO bootstrap.cu:238 -> 2
docker-100-88-66-138:19123:19685 [2] INFO init.cu:409 -> 2
docker-100-88-66-138:19123:19685 [2] INFO init.cu:536 -> 2
docker-100-88-66-138:19123:19685 [2] INFO misc/group.cu:70 -> 2 [Async thread]

docker-100-88-66-138:19124:19694 [3] include/socket.h:360 WARN Call to connect timeout : Connection refused
docker-100-88-66-138:19124:19694 [3] INFO transport/net_socket.cu:118 -> 2
docker-100-88-66-138:19124:19694 [3] INFO bootstrap.cu:28 -> 2 [Net]
docker-100-88-66-138:19124:19694 [3] INFO bootstrap.cu:238 -> 2
docker-100-88-66-138:19124:19694 [3] INFO init.cu:409 -> 2
docker-100-88-66-138:19124:19694 [3] INFO init.cu:536 -> 2
docker-100-88-66-138:19124:19694 [3] INFO misc/group.cu:70 -> 2 [Async thread]
Traceback (most recent call last):
  File "main.py", line 400, in <module>
    main()
  File "main.py", line 112, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/data/home/hanleyzhang/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/data/home/hanleyzhang/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/data/home/hanleyzhang/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data3/chenhui/imagenet/main.py", line 153, in main_worker
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
  File "/data/home/hanleyzhang/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 215, in __init__
    self.broadcast_bucket_size)
  File "/data/home/hanleyzhang/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 377, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1544081127912/work/torch/lib/c10d/ProcessGroupNCCL.cpp:260, unhandled system error

**Comment by htlchh** [comment]
> Thanks for posting the log! I am not sure from the log exactly why it's hanging. May be if you could post a minimal reproducing code, we could try looking at it on our end. Also what exact commands are you using? Here are some more environment variables you could try to see if they fixes your issue:
> 
> ```
> export NCCL_SOCKET_IFNAME=^docker0 # MUST needed for running multi-node with docker
> export NCCL_DEBUG=INFO # (optional) prints NCCL specific, useful for debugging
> export NCCL_IB_HCA=mlx4_0 # (optional) needed if you want to use a specific network interface like RoCE. you can find about available interfaces using ibstatus.
> ```

Hi, this bug disappears if I excute the codes with empty GPUs. However, when there are already some processes in GPUs, eg. runing in GPUs [4,5,6,7], I excute the same codes with GPUs [0,1,2,3]. This bug appears again. Is it necessary to clear all GPUs when use nccl backend?

**Comment by htlchh** [comment]
This is a strange bug. Hope to be fixed in the following version.

**Comment by youkaichao** [comment]
I have run into the same problem. But the GPUs are all empty, except that 11MB memory is used (no process running). 

The code is easy to reproduce:
```
import torch
import sys

dist = '--local_rank' in ''.join(sys.argv)

if dist:
    torch.distributed.init_process_group(backend='nccl')

def get_available_GPUs(N, max_utilization=.5, max_memory_usage=.5):
    '''
    get `N` available GPU ids with *utilization* less than `max_utilization` and *memory usage* less than max_memory_usage
    Arguments:
        N (int): How many GPUs you want to select
        max_utilization (float): GPU with utilization higher than `max_utilization` is considered as not available.
        max_memory_usage (float): GPU with memory usage higher than `max_memory_usage` is considered as not available.

    Returns:
        list containing IDs of available GPUs
    '''
    from subprocess import Popen, PIPE
    cmd = ["nvidia-smi",
           "--query-gpu=index,utilization.gpu,memory.total,memory.used",
           "--format=csv,noheader,nounits"]
    p = Popen(cmd, stdout=PIPE)
    output = p.stdout.read().decode('UTF-8')
    gpus = [[int(x) for x in line.split(',')] for line in output.splitlines()]
    gpu_ids = []
    for (index, utilization, total, used) in gpus:
        if utilization / 100.0 < max_utilization:
            if used * 1.0 / total < max_memory_usage:
                gpu_ids.append(index)
    if len(gpu_ids) < N:
        raise Exception("Only %s GPU(s) available but %s GPU(s) are required!" % (len(gpu_ids), N))
    available = gpu_ids[:N]
    return list(available)

def select_GPUs(N_per_process, max_utilization=.5, max_memory_usage=.5):
    '''
    select `N_per_process` GPUs.
    If distributed training is enabled, GPUs will be assigned properly among different processes.
    Arguments:
        N_per_process (int): How many GPUs you want to select for each process
        max_utilization (float): GPU with utilization higher than `max_utilization` is considered as not available.
        max_memory_usage (float): GPU with memory usage higher than `max_memory_usage` is considered as not available.

    Returns:
        list containing IDs of selected GPUs
    '''
    if not dist:
        return get_available_GPUs(N_per_process, max_utilization, max_memory_usage)
    rank = torch.distributed.get_rank()
    world_size = torch.distributed.get_world_size()
    tensor = torch.zeros(world_size * N_per_process, dtype=torch.int).cuda()
    if rank == 0:
        device_ids = get_available_GPUs(world_size * N_per_process)
        tensor = torch.tensor(device_ids, dtype=torch.int).cuda()
    torch.distributed.broadcast(tensor, 0)
    ids = list(tensor.cpu().numpy().tolist())
    return ids[N_per_process * rank : N_per_process * rank + N_per_process]

import torch.nn as nn
device_ids = select_GPUs(2)
output_device = torch.device(device_ids[0])

x = torch.tensor([5.0, -1.0], dtype=torch.float).cuda(output_device).view(-1, 1)

model = nn.Linear(in_features=1, out_features=1, bias=False).cuda(output_device)

rank = torch.distributed.get_rank()
model.weight.data.zero_()
model.weight.data.add_(rank)

print(f'at rank {rank}, before init, the weight is {model.weight.data.item()}')

model = torch.nn.parallel.DistributedDataParallel(model,device_ids=device_ids, output_device=output_device)

print(f'at rank {rank}, after init, the weight is {model.module.weight.data.item()}')

y = model(x)

label = torch.zeros(2, 1, dtype=torch.float).cuda(output_device)

loss = torch.sum((y - label)**2)

loss.backward()

# print(model.weight.grad)
```

After printing 
```
at rank 0, before init, the weight is 0.0
at rank 1, before init, the weight is 1.0
at rank 0, after init, the weight is 0.0
```
it hangs.

But it works fine with `gloo`.

**Comment by MilesCranmer** [comment]
I have a similar bug - switching to gloo fixes it.

**Comment by yl1991** [comment]
@MilesCranmer Same for me but I feel like gloo is a bit slower than nccl, what do you think?

**Comment by denru01** [comment]
I encountered the same problem in the nightly build, but not in the 1.0 stable build.
- I run the training script on a single machine with 8 GPUs and the training procedure got stuck in the middle of training. The strange thing is that it happened at 70-ish epoch instead of the first few iterations.
- I tried to use a third-party library, apex, and it still got stuck but at different epoch.
