### ISSUE TITLE
what is the algorithm theory of torch.nn.AdaptiveMaxPool2d?

### ISSUE THREAD

**Issue by Kanbo0409** [pytorch/pytorch#14889]
what is the algorithm theory of torch.nn.AdaptiveMaxPool2d?
 Is there any papers about torch.nn.AdaptiveMaxPool2d?
 And how to find the c++ of implementing torch.nn.AdaptiveMaxPool2d in pytorch?

**Comment by fmassa** [comment]
I originally wrote it in lua-torch to be able to reproduce Spatial Pyramid Pooling for Object Detection. I'm not sure if there are any particular papers on that. The original discussion can be found in https://github.com/torch/nn/issues/141

You can find the current implementation in https://github.com/pytorch/pytorch/blob/master/aten/src/THNN/generic/SpatialAdaptiveMaxPooling.c, the cuda implementation is in the THCUNN folder
