### ISSUE TITLE
torch.randint() returns float32 tensor with pytorch ver 0.4.1

### ISSUE THREAD

**Issue by PengFoo** [pytorch/pytorch#14886]
## 🐛 Bug
pytorch version 0.4.1
while calling torch.randint() function, it is supposed to return a long tensor, but a `torch.float32` tensor return instead.

## To Reproduce

```python
idx = torch.randint(low=0, high=vocab_size - 1, size=(2, 3))
print(idx)
print(idx.dtype)
```

and you'll get things like:
`
tensor([[3., 2., 2.],
        [3., 1., 3.]])
torch.float32
`

## Environment

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 14.04.5 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by SsnL** [comment]
I believe the change was merged after 0.4.1. On master it returns a long tensor.
