### ISSUE TITLE
[perf-regression] mnist-hogwild with default settings is slower

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#14884]
## 🐛 Bug

Take https://github.com/pytorch/examples/tree/master/mnist_hogwild

If we dont set the environment flags `OMP_NUM_THREADS=1 MKL_NUM_THREADS=1`, then 0.4.1 vs 1.0.0 is seeing a significant slowdown.

Some settings related to default number of threads used has regressed

## To Reproduce

1. Install 0.4.1, run `python main.py`
1. Install 1.0.0, run `python main.py`
1. notice the speed diffference
1. run `OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python main.py`, notice the lack of speed difference

Ran in Python 2.7

cc @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
Closing due to age
