### ISSUE TITLE
Wrong recursive module::load

### ISSUE THREAD

**Issue by 1ytic** [pytorch/pytorch#14891]
## 🐛 Bug

Parameters and buffers must be checked recursively during the load procedure [module.cpp#L297](https://github.com/pytorch/pytorch/blob/8311bbee7f1dd33346f18c769cfeb8c5b5941874/torch/csrc/api/src/nn/module.cpp#L297). 
For example, like this:
`if (!child.value()->parameters().empty() || !child.value()->buffers().empty())`

**Comment by zou3519** [comment]
I don't understand the problem but marking this as hi-pri for understanding the problem

**Comment by zou3519** [comment]
cc @goldsborough

**Comment by goldsborough** [comment]
That makes sense. I'll send a fix.
