### ISSUE TITLE
Delete THNN direct binding code entirely

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14895]
I am not sure if I have identified all the call sites, but here are three that I know about:

- [ ] Im2Col/Col2Im (`from ._functions.thnn.fold import Col2Im, Im2Col` in torch/nn/functional.py)
- [ ] CrossMapLRN2d (from torch/nn/modules/normalization.py, grep for `_backend`)
- [ ] ConvNd (from torch/nn/modules/conv.py grep for `_backend`)

**Comment by yifuwang** [comment]
@ezyang I think the ConvNd call site is dead code. Submitted a #20965 to remove it.
