### ISSUE TITLE
mac os 10.14.1  build cpp error with pure c++ font-end

### ISSUE THREAD

**Issue by hggq** [pytorch/pytorch#14892]
I made a compilation error on the front end of pure c++.
---------------
**192:build hzq$ make**
Scanning dependencies of target example-app
[ 50%] Building CXX object CMakeFiles/example-app.dir/example-app.cpp.o
[100%] Linking CXX executable example-app
ld: warning: ignoring file /Users/hzq/Documents/www/test/libtorch/lib/libtorch.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /Users/hzq/Documents/www/test/libtorch/lib/libtorch.so
ld: warning: ignoring file /Users/hzq/Documents/www/test/libtorch/lib/libc10.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /Users/hzq/Documents/www/test/libtorch/lib/libc10.so
ld: warning: ignoring file /Users/hzq/Documents/www/test/libtorch/lib/libcaffe2.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /Users/hzq/Documents/www/test/libtorch/lib/libcaffe2.so
Undefined symbols for architecture x86_64:
  "at::UndefinedTensorImpl::_singleton", referenced from:
      at::UndefinedTensorImpl::singleton() in example-app.cpp.o
  "at::print(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, at::Tensor const&, long long)", referenced from:
      at::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, at::Tensor const&) in example-app.cpp.o
  "at::native::rand(c10::ArrayRef<long long>, at::TensorOptions const&)", referenced from:
      at::rand(c10::ArrayRef<long long>, at::TensorOptions const&) in example-app.cpp.o
  "c10::impl::device_guard_impl_registry", referenced from:
      c10::impl::getDeviceGuardImpl(c10::DeviceType) in example-app.cpp.o
  "c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      torch::autograd::make_variable(at::Tensor, bool) in example-app.cpp.o
      torch::jit::Block::appendNode(torch::jit::Node*) in example-app.cpp.o
      torch::jit::Node::inBlockList() const in example-app.cpp.o
      c10::impl::getDeviceGuardImpl(c10::DeviceType) in example-app.cpp.o
      c10::intrusive_ptr<at::TensorImpl, at::UndefinedTensorImpl>::retain_() in example-app.cpp.o
  "c10::Device::validate()", referenced from:
      c10::Device::Device(c10::DeviceType, short) in example-app.cpp.o
  "c10::Symbol::fromQualString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      torch::rand(c10::ArrayRef<long long>, at::TensorOptions const&) in example-app.cpp.o
  "c10::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, c10::DeviceType)", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& c10::detail::_str<c10::DeviceType>(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, c10::DeviceType const&) in example-app.cpp.o
  "torch::jit::Node::insertBefore(torch::jit::Node*)", referenced from:
      torch::jit::Block::appendNode(torch::jit::Node*) in example-app.cpp.o
  "torch::jit::Graph::create(c10::Symbol, unsigned long)", referenced from:
      torch::rand(c10::ArrayRef<long long>, at::TensorOptions const&) in example-app.cpp.o
  "torch::jit::tracer::getTracingState()", referenced from:
      torch::rand(c10::ArrayRef<long long>, at::TensorOptions const&) in example-app.cpp.o
      torch::jit::tracer::isTracing() in example-app.cpp.o
  "torch::jit::tracer::setTracingState(std::__1::shared_ptr<torch::jit::tracer::TracingState>)", referenced from:
      torch::rand(c10::ArrayRef<long long>, at::TensorOptions const&) in example-app.cpp.o
  "torch::jit::tracer::recordSourceLocation(torch::jit::Node*)", referenced from:
      torch::rand(c10::ArrayRef<long long>, at::TensorOptions const&) in example-app.cpp.o
  "torch::jit::tracer::addInputs(torch::jit::Node*, char const*, c10::ArrayRef<long long>)", referenced from:
      torch::rand(c10::ArrayRef<long long>, at::TensorOptions const&) in example-app.cpp.o
  "torch::jit::tracer::addInputs(torch::jit::Node*, char const*, at::TensorOptions const&)", referenced from:
      torch::rand(c10::ArrayRef<long long>, at::TensorOptions const&) in example-app.cpp.o
  "torch::jit::tracer::addOutput(torch::jit::Node*, at::Tensor const&)", referenced from:
      torch::rand(c10::ArrayRef<long long>, at::TensorOptions const&) in example-app.cpp.o
  "torch::autograd::Variable::Impl::Impl(at::Tensor, bool, torch::autograd::Edge)", referenced from:
      c10::intrusive_ptr<torch::autograd::Variable::Impl, c10::detail::intrusive_target_default_null_type<torch::autograd::Variable::Impl> > c10::intrusive_ptr<torch::autograd::Variable::Impl, c10::detail::intrusive_target_default_null_type<torch::autograd::Variable::Impl> >::make<at::Tensor&, bool&>(at::Tensor&&&, bool&&&) in example-app.cpp.o
  "caffe2::detail::_typeMetaDataInstance_preallocated_6", referenced from:
      caffe2::detail::TypeMetaData const* caffe2::TypeMeta::_typeMetaDataInstance<float>() in example-app.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [example-app] Error 1
make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
make: *** [all] Error 2

## Environment
mac os 10.14.1  

`#include <torch/torch.h>
#include <iostream>

int main() {
	std::cout<<"hello world!"<<std::endl;	
  return 0;
}`

test ok
=================
192:build hzq$ make
Scanning dependencies of target example-app
[ 50%] Building CXX object CMakeFiles/example-app.dir/example-app.cpp.o
[100%] Linking CXX executable example-app
ld: warning: ignoring file /Users/hzq/Documents/www/test/libtorch/lib/libtorch.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /Users/hzq/Documents/www/test/libtorch/lib/libtorch.so
ld: warning: ignoring file /Users/hzq/Documents/www/test/libtorch/lib/libcaffe2.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /Users/hzq/Documents/www/test/libtorch/lib/libcaffe2.so
ld: warning: ignoring file /Users/hzq/Documents/www/test/libtorch/lib/libc10.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /Users/hzq/Documents/www/test/libtorch/lib/libc10.so
[100%] Built target example-app
192:build hzq$ ./example-app
**hello world!**
192:build hzq$ 

## Environment
mac os 10.14.1    cmake version 3.13.0-rc3  
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by hggq** [comment]
i use this LibTorch ZIP 
https://pytorch.org/cppdocs/installing.html
=======
wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
unzip libtorch-shared-with-deps-latest.zip
==========
 I think I see. Does this zip file not support MAC os?

**Comment by soumith** [comment]
The MacOS link is different. See https://pytorch.org

<img width="833" alt="screen shot 2018-12-07 at 10 49 28 am" src="https://user-images.githubusercontent.com/1310570/49657551-f105ad00-fa0d-11e8-9ccd-aaef8b0fc829.png">

**Comment by hggq** [comment]
this zip 
 When something goes wrong on my computer, I want to use it. I don't want to compile other libraries. 
libtorch-macos-latest.zip 28M
libtorch-shared-with-deps-latest.zip  62M
i think libtorch-shared-with-deps-latest.zip  included  on maoc lost lib libmklml.dylib.
