### ISSUE TITLE
[docs] make html-stable is broken

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#14901]
`make html` autogenerates fonts and some javascript files that `make html-stable` doesn't do.

**Comment by vishwakftw** [comment]
From what I can see, `make html-stable` is just `make html` with a `RELEASE` variable set to 1. This in turn only uses a different (non-existent?) template for the docs, and switches the logo.

I tried build two copies of the docs, and couldn't find any difference.

**Comment by zou3519** [comment]
Thanks for the check, @vishwakftw. I might just be bad at building the docs, let me check again... The problem I was experiencing 3 days ago is that the fonts weren't installed for `make html-stable`

**Comment by jbschlosser** [comment]
Closing this as stale. Feel free to reopen if still relevant, although I doubt it is :)
