### ISSUE TITLE
"undefined symbol: PySlice_Unpack" of pytorch 1.0.0 on Ubuntu 14.04

### ISSUE THREAD

**Issue by sz128** [pytorch/pytorch#14931]
Python 3.6.0 (default, Nov 17 2017, 11:43:46)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.0.0'
>>> m=torch.randn(2,3)
>>> m
tensor([[-0.3711,  0.5104, -0.8859],
        [-0.5211, -0.6502, -0.5249]])
>>> m[:,1]=1
**python: symbol lookup error: /home/slhome/sz128/ve3_cpu/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack**

I just installed pytorch 1.0.0 by "pip3 install http://download.pytorch.org/whl/cu80/torch-1.0.0-cp36-cp36m-linux_x86_64.whl && pip3 install torchvision" in a new virtualenv.

**Comment by vishwakftw** [comment]
Could you try upgrading to Python 3.6.1 or greater and check if the issue persists?

**Comment by sz128** [comment]
@vishwakftw Thank you. It works when I use Python 3.6.3.

**Comment by benywon** [comment]
I meet the exactly same error

**Comment by kimnoic** [comment]
@vishwakftw Thx! It works when I upgrade Python to 3.6.3.

**Comment by bfujiwara** [comment]
Same error on my side.

There is no fix for Python 3.6.0 ?

**Comment by soumith** [comment]
no there is no fix for python 3.6.0, because it's actually an ABI bug between 3.6.0 and > 3.6.0

**Comment by PhoenixZhao** [comment]
> Could you try upgrading to Python 3.6.1 or greater and check if the issue persists?

@vishwakftw  thanks, it worked for me.
