### ISSUE TITLE
Device is a missing case in toPyObject

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#14934]
## 🐛 Bug

I found this while building the docs. `Device` is not added as a case in `toPyObject`.

## To Reproduce

1. Install PyTorch from source / using a binary
2. `make html` and check the terminal output

> Missing cases in 'toPyObject'! File a bug report.

## Expected behavior

Faultless doc build

**Comment by vishwakftw** [comment]
This affects the `torch.jit.supported_ops` list, from what I gathered.

**Comment by driazati** [comment]
This should be fixed with #14912 which was merged in [this commit](https://github.com/pytorch/pytorch/commit/5837320b7062a360ad9c17e76650f318652d46a2)
