### ISSUE TITLE
CUDA out of memory while training before updating weights(Python 2.7.9, Pytorch 0.4.1, CUDA 8.0)

### ISSUE THREAD

**Issue by MrLeylo** [pytorch/pytorch#14936]
I’m running a Pytorch code for training a model. I’m not loading any specially big tensor, just use a VGG16 and an LSTM over a tensor of 1x224x224x3. I compute the outputs with the following code, without updating any model's loss:

`

def compute_outputs(self, x_train, yoh_train, x_test, yoh_test):

        vxtrain = Variable(x_train, requires_grad=True)
        vytrain = Variable(yoh_train, requires_grad=True)
        size_training_set = vxtrain.size()[0]
        size_testing_set = x_test.size()[0]

        vrxtrain = self.rm_model(vxtrain)

        weights = self.sm_model(vrxtrain)

        nb_ok = 0
        agg_loss = 0
        for nb in range(size_testing_set):
            vx = Variable(x_test.narrow(0, nb, 1).contiguous(),
                          requires_grad=True)
            vryoh = Variable(yoh_test.narrow(0, nb, 1).contiguous(),
                             requires_grad=False)

            # Get representations of examples
            vrx = self.rm_model(vx)

            prediction = self.pm_model(vrxtrain, vytrain, weights, vrx)

            loss = self.criterion(prediction, vryoh)

            if agg_loss is None:
                agg_loss = loss
            else:
                agg_loss += loss

            le_max = prediction.data.max(1)
            predit = le_max[1]
            if predit[0] == problem.yoh_test[nb].data.max(0)[1]:
                    nb_ok = nb_ok + 1

        self_loss = agg_loss / size_testing_set

        self.self_losses.append(self_loss)

        self.accuracy = nb_ok / size_testing_set

        return self.accuracy, self_loss`

Where rm_model is the VGG and sm_model is the LSTM. I run it several times before updating the weights over an average of all computed losses. However, after a few iterations (just at the third in my case) it launches a CUDA out of memory. Am I missing something?

I'm sorry if something is missing on this issue. I'm kind of new in reporting.

Thank you in advanced.

**Comment by MrLeylo** [comment]
> Please use `loss.item()` for aggregating loss instead of `loss` itself. This should alleviate the issue.

Well, the issue is that I need to work with the final loss in self_losses as a true loss (to apply .backward() over it), so if I just aggregate all the losses with the loss.item() it becomes a float and I cannot apply .backward().

**Comment by MrLeylo** [comment]
I tried to, instead of averaging losses, store the tensors for each iteration and compute the loss at the end of the epoch as a loss of a mulidimensional tensor. However, I get the same error. So, now there is no loss involved, so I guess we could discard that it could be an issue related to the loss.

**Comment by soumith** [comment]
https://discuss.pytorch.org

As already mentioned in the issue templates (which you ignored), all questions go onto the forums

**Comment by MrLeylo** [comment]
Ok, I move there. Anyway, I discovered it is an issue about the VGG at training. I am using VGG16 and cannot set it as volatile since I need to backpropagate. Just need to make sure how much memory do I need to train that network.
