### ISSUE TITLE
TorchScriptModule single layer interference. Found no forward method in submodule

### ISSUE THREAD

**Issue by joyliu37** [pytorch/pytorch#14944]
Hi folks, thanks for the powerful script mode. 
I tried to run single layer inference on script mode. But I found there is no `forward` method in a `submodule` of a loaded network in script mode.  In detail, I load a model through `torch::jit::load` and use `get_module("name_string")` to get the submodule's ptr. However, when I call `get_methods()` the return OrderedDict size is zero. I double checked the parameters and did find there is `weight` and `bias` tensor. 
Is it true that we cannot run single layer inference in the script mode? I guess that  the method has been already optimized on the graph during `deserilization` when we load the module.
BTW. Is there a way to transform `torch::jit::script::Module` to  c++ API `torch::nn::Module`? Thanks!

**Comment by soumith** [comment]
> BTW. Is there a way to transform torch::jit::script::Module to c++ API torch::nn::Module

To answer this question, there isn't a way in C++ API to do this, and we very likely wont have such a possibility in the short term.

**Comment by joyliu37** [comment]
@soumith So could I load a pretrained model file `model.pt` to C++ API `torch::nn::Module`.  And refine it?

**Comment by driazati** [comment]
We now enforce that at least a `forward` method is defined on compile modules so this shouldn't be an error anymore. Feel free to re-open if you have a specific repro that's still a problem.
