### ISSUE TITLE
undefined reference to `vmdLog2'  

### ISSUE THREAD

**Issue by hitlxm** [pytorch/pytorch#14954]
## Issue description

/data1/bryanleoliu/pytorch/torch/lib/c10d/ProcessGroupGloo.cpp: In member function ‘c10d::AlgorithmEntry* c10d::ProcessGroupGloo::checkout(const c10d::AlgorithmKey&)’:
/data1/bryanleoliu/pytorch/torch/lib/c10d/ProcessGroupGloo.cpp:445:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (vec.size() != cacheNumAlgorithmEntries_) {
                     ^
[ 42%] Linking CXX static library libc10d.a
[ 42%] Built target c10d
[ 47%] Building NVCC (Device) object test/CMakeFiles/c10d_cuda_test.dir/c10d_cuda_test_generated_CUDATest.cu.o
Scanning dependencies of target ProcessGroupMPITest
Scanning dependencies of target TCPStoreTest
Scanning dependencies of target FileStoreTest
[ 52%] Building CXX object test/CMakeFiles/FileStoreTest.dir/FileStoreTest.cpp.o
[ 57%] Building CXX object test/CMakeFiles/TCPStoreTest.dir/TCPStoreTest.cpp.o
[ 61%] Building CXX object test/CMakeFiles/ProcessGroupMPITest.dir/ProcessGroupMPITest.cpp.o
[ 66%] Linking CXX executable FileStoreTest
/data1/bryanleoliu/pytorch/torch/lib/c10d/test/ProcessGroupMPITest.cpp: In function ‘void testAllreduce(int)’:
/data1/bryanleoliu/pytorch/torch/lib/c10d/test/ProcessGroupMPITest.cpp:19:57: warning: ‘at::Tensor at::ones(const at::Type&, at::IntList)’ is deprecated (declared at /data1/bryanleoliu/pytorch/torch/lib/tmp_install/include/ATen/Functions.h:3936) [-Wdeprecated-declarations]
     auto tensor = at::ones(at::CPU(at::kFloat), {16, 16}) * i;
                                                         ^
/data1/bryanleoliu/pytorch/torch/lib/c10d/test/ProcessGroupMPITest.cpp: In function ‘void testBroadcast(int)’:
/data1/bryanleoliu/pytorch/torch/lib/c10d/test/ProcessGroupMPITest.cpp:61:59: warning: ‘at::Tensor at::ones(const at::Type&, at::IntList)’ is deprecated (declared at /data1/bryanleoliu/pytorch/torch/lib/tmp_install/include/ATen/Functions.h:3936) [-Wdeprecated-declarations]
       auto tensor = at::ones(at::CPU(at::kFloat), {16, 16}) * i;
                                                           ^
/data1/bryanleoliu/pytorch/torch/lib/c10d/test/ProcessGroupMPITest.cpp:64:60: warning: ‘at::Tensor at::zeros(const at::Type&, at::IntList)’ is deprecated (declared at /data1/bryanleoliu/pytorch/torch/lib/tmp_install/include/ATen/Functions.h:4374) [-Wdeprecated-declarations]
       auto tensor = at::zeros(at::CPU(at::kFloat), {16, 16});
                                                            ^
/data1/bryanleoliu/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmdLog2'
/data1/bryanleoliu/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
make[2]: *** [test/FileStoreTest] Error 1
make[1]: *** [test/CMakeFiles/FileStoreTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 71%] Linking CXX executable TCPStoreTest
[ 76%] Linking CXX executable ProcessGroupMPITest
/data1/bryanleoliu/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmdLog2'
/data1/bryanleoliu/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
make[2]: *** [test/TCPStoreTest] Error 1
make[1]: *** [test/CMakeFiles/TCPStoreTest.dir/all] Error 2
/data1/bryanleoliu/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmdLog2'
/data1/bryanleoliu/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
make[2]: *** [test/ProcessGroupMPITest] Error 1
make[1]: *** [test/CMakeFiles/ProcessGroupMPITest.dir/all] Error 2
Scanning dependencies of target c10d_cuda_test
[ 80%] Linking CXX static library libc10d_cuda_test.a
[ 80%] Built target c10d_cuda_test
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 nanopb libshm gloo THD c10d'

## System Info

```

- PyTorch or Caffe2:Pytorch
- How you installed PyTorch (conda, pip, source): source 
- Build command you used (if compiling from source):python setup.py install
- OS: centos 7
- PyTorch version:0.4.1
- Python version:3.6
- CUDA/cuDNN version: 9.0/7.3
- GPU models and configuration: 8 nvidia p40
- GCC version (if compiling from source):4.8.5
- CMake version:3.12.0
- Versions of any other relevant libraries: 


cc @malfet

**Comment by hitlxm** [comment]
I reinstall mkl by conda install mkl & conda install mkl-include , but it doesnt work all the time 
can anyone help me?

**Comment by frankang** [comment]
i have the same issue.

```
- PyTorch or Caffe2:Pytorch
- How you installed PyTorch (conda, pip, source): source 
- Build command you used (if compiling from source):python setup.py install
- OS: Ubuntu 16.04
- PyTorch version:0.4.1
- Python version:3.6.5
- CUDA/cuDNN version: 8.0/6.0.21
- GPU models and configuration: 4 nvidia titan-x
- GCC version (if compiling from source): 4.9.2
- CMake version: 3.6.3
```

error:
```
/home/user/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmdLog2'
/home/user/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
test/CMakeFiles/FileStoreTest.dir/build.make:118: recipe for target 'test/FileStoreTest' failed
make[2]: *** [test/FileStoreTest] Error 1
CMakeFiles/Makefile2:246: recipe for target 'test/CMakeFiles/FileStoreTest.dir/all' failed
make[1]: *** [test/CMakeFiles/FileStoreTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/user/pytorch/torch/lib/c10d/test/ProcessGroupMPITest.cpp: In function ‘void testAllreduce(int)’:
/home/user/pytorch/torch/lib/c10d/test/ProcessGroupMPITest.cpp:19:57: warning: ‘at::Tensor at::ones(const at::Type&, at::IntList)’ is deprecated (declared at /home/user/pytorch/torch/lib/tmp_install/include/ATen/Functions.h:3936) [-Wdeprecated-declarations]
     auto tensor = at::ones(at::CPU(at::kFloat), {16, 16}) * i;
                                                         ^
/home/user/pytorch/torch/lib/c10d/test/ProcessGroupMPITest.cpp: In function ‘void testBroadcast(int)’:
/home/user/pytorch/torch/lib/c10d/test/ProcessGroupMPITest.cpp:61:59: warning: ‘at::Tensor at::ones(const at::Type&, at::IntList)’ is deprecated (declared at /home/user/pytorch/torch/lib/tmp_install/include/ATen/Functions.h:3936) [-Wdeprecated-declarations]
       auto tensor = at::ones(at::CPU(at::kFloat), {16, 16}) * i;
                                                           ^
/home/user/pytorch/torch/lib/c10d/test/ProcessGroupMPITest.cpp:64:60: warning: ‘at::Tensor at::zeros(const at::Type&, at::IntList)’ is deprecated (declared at /home/user/pytorch/torch/lib/tmp_install/include/ATen/Functions.h:4374) [-Wdeprecated-declarations]
       auto tensor = at::zeros(at::CPU(at::kFloat), {16, 16});
                                                            ^
[ 66%] Linking CXX executable TCPStoreTest
/home/user/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmdLog2'
/home/user/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
test/CMakeFiles/TCPStoreTest.dir/build.make:118: recipe for target 'test/TCPStoreTest' failed
make[2]: *** [test/TCPStoreTest] Error 1
CMakeFiles/Makefile2:209: recipe for target 'test/CMakeFiles/TCPStoreTest.dir/all' failed
make[1]: *** [test/CMakeFiles/TCPStoreTest.dir/all] Error 2
[ 70%] Linking CXX executable ProcessGroupMPITest
/home/user/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmdLog2'
/home/user/pytorch/torch/lib/tmp_install/lib/libcaffe2.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
test/CMakeFiles/ProcessGroupMPITest.dir/build.make:118: recipe for target 'test/ProcessGroupMPITest' failed
make[2]: *** [test/ProcessGroupMPITest] Error 1
CMakeFiles/Makefile2:172: recipe for target 'test/CMakeFiles/ProcessGroupMPITest.dir/all' failed
make[1]: *** [test/CMakeFiles/ProcessGroupMPITest.dir/all] Error 2
Scanning dependencies of target c10d_cuda_test
[ 75%] Linking CXX static library libc10d_cuda_test.a
[ 75%] Built target c10d_cuda_test
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack caffe2 nanopb libshm gloo THD c10d'
```

**Comment by frankang** [comment]
@hitlxm 
I'm pretty sure this is caused by some newly updated packages installed by conda.
I copied a miniconda3 installation folder (which was proven to build 0.4.1 pytorch successfully 3 weeks ago) from another machine. Then it went through the build steps smoothly.

**Comment by bombs-kim** [comment]
I have the same problem

**Comment by bombs-kim** [comment]
@hitlxm @frankang If you were using conda virtual environments, you may have to give this a try.
#15548 
> export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}

If you are using a virtual env, `CMAKE_PREFIX_PATH` should be `CONDA_PREFIX` not conda root. Otherwise, cmake gets confused.

**Comment by ddummkopfer** [comment]
Update the mkl, mkl-include, ninja to the newest version and it can be build successfully.

**Comment by izdeby** [comment]
Looks like its an old issue. Please reopen if the problem reproduces.

**Comment by entalent** [comment]
## Issue description

Trying to build PyTorch from source (using branch release/1.10) but failed with the following error:

```
[5899/6718] Linking CXX executable bin/FileStoreTest
FAILED: bin/FileStoreTest : && /usr/bin/c++ -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -rdynamic test_cpp_c10d/CMakeFiles/FileStoreTest.dir/FileStoreTest.cpp.o -o bin/FileStoreTest -L/home/wentian/library/miniconda3/envs/py3.7_torch1.7_vulkan/lib -Wl,-rpath,/home/wentian/library/pytorch_1.10_vulkan/pytorch/build/lib:/home/wentian/library/miniconda3/envs/py3.7_torch1.7_vulkan/lib:  lib/libtorch_cpu.so  lib/libgtest_main.a  -lpthread  lib/libprotobuf.a  lib/libc10.so  -lmkl_intel_lp64  -lmkl_intel_thread  -lmkl_core  /home/wentian/library/miniconda3/envs/py3.7_torch1.7_vulkan/lib/libiomp5.so  /usr/lib/x86_64-linux-gnu/libpthread.so  -lm  /usr/lib/x86_64-linux-gnu/libdl.so  lib/libdnnl.a  -ldl  lib/libgtest.a  -pthread && :
/usr/bin/ld: lib/libtorch_cpu.so: undefined reference to `vmdLog2'
/usr/bin/ld: lib/libtorch_cpu.so: undefined reference to `vmsLog2'
collect2: error: ld returned 1 exit status
```
The environment variable CMAKE_PREFIX_PATH is already set to `${CONDA_PREFIX:-"$(dirname $(which conda))/../"}`.

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): python setup.py install
- OS: Ubuntu 20.04.1 LTS
- PyTorch version: 1.10
- Python version: 3.7.12
- CUDA/cuDNN version: 10.2/7.6.5
- GPU models and configuration: RTX 2070+GTX 1070
- GCC version (if compiling from source): gcc version 8.4.0 (Ubuntu 8.4.0-3ubuntu2)
- CMake version: 3.22.3
- Versions of any other relevant libraries:
