### ISSUE TITLE
libTorch1.0windows: fatal error C1083: Cannot open include file: 'pthread.h'

### ISSUE THREAD

**Issue by kvcuong** [pytorch/pytorch#14951]
## 🐛 Bug

Hi,
I just replay the example in https://pytorch.org/tutorials/advanced/cpp_export.html In window 10x64 VS2015win64 compiler + Cmake 3.10.2 and it end up with "CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h'" in CMakeError.log

## To Reproduce

1. Copy python code with resNet18 in  https://pytorch.org/tutorials/advanced/cpp_export.html 
2. Using trace to save the model in resnet.pt
3. Copy cpp load model in  https://pytorch.org/tutorials/advanced/cpp_export.html 
4. Run cmake-gui to configure env 

## Expected behavior
The C compiler identification is MSVC 19.0.24215.1
The CXX compiler identification is MSVC 19.0.24215.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
### Looking for pthread.h - not found
Found Threads: TRUE  
Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0 (found suitable version "9.0", minimum required is "7.0") 
Caffe2: CUDA detected: 9.0
Caffe2: CUDA nvcc is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/bin/nvcc.exe
Caffe2: CUDA toolkit directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
Caffe2: Header version is: 9.0
Found CUDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include  
Found cuDNN: v7.3.1  (include: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include, library: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib)
Autodetected CUDA architecture(s): 6.1
Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Error at .../libs/libtorch_gpucuda90/share/cmake/Caffe2/public/cuda.cmake:368 (message):
  Unknown cmake build type:
Call Stack (most recent call first):
  ../libs/libtorch_gpucuda90/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  ../libs/libtorch_gpucuda90/share/cmake/Torch/TorchConfig.cmake:39 (find_package)
  CMakeLists.txt:4 (find_package)
Configuring incomplete, errors occurred!

## Environment

 - PyTorch Version 1.0
 - OS (e.g., Linux): Window 10 x64
 - How you installed PyTorch (`conda`):
 - Build command you used (if compiling from source):
 - Python version:3.6.7
 - CUDA/cuDNN version: 9.0/7.1
 - GPU models and configuration: GTX1070

**Comment by peterjc123** [comment]
The actual error is this line:`CMake Error at .../libs/libtorch_gpucuda90/share/cmake/Caffe2/public/cuda.cmake:368 (message):
Unknown cmake build type:`. Please specify this variable, either `Debug` or `Release`.

**Comment by kvcuong** [comment]
You are right! I've set up CMAKE_CONFIGURATION_TYPE = Debug;Release. I didn't see that it uses CMAKE_BUILD_TYPE instead. 

It works now. Thank you. I will close this issue.

**Comment by cuixing158** [comment]
my actual error like this,how to confiigue it, thanks!

CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.


Configuring incomplete, errors occurred!
See also "D:/pytorch1_0/libtorch/example-app/CMakeFiles/CMakeOutput.log".

------------------------------------------------------------------------------
in CMake-gui (verison 3.11.2) configure :
source code path:  D:/pytorch1_0/libtorch/example-app
build binary path:   D:/pytorch1_0/libtorch/example-app

vs2015 x64 complie
