### ISSUE TITLE
Error when using pytorch1.0 built from src

### ISSUE THREAD

**Issue by cindycia** [pytorch/pytorch#14955]
I pulled pytorch from master and built from source using these commands:
```
echo "Compiling pytorch"
USE_OPENCV=1 \
    CMAKE_PREFIX_PATH="/usr/bin/" \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/lib:$LD_LIBRARY_PATH \
    CUDA_BIN_PATH=/usr/local/cuda/bin \
    CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda/ \
    CUDNN_LIB_DIR=/usr/local/cuda/lib64 \
    CUDA_HOST_COMPILER=cc \
    USE_CUDA=1 \
    USE_NNPACK=1 \
    CC=cc \
    CXX=c++ \
    TORCH_CUDA_ARCH_LIST="6.1+PTX" \
    TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    python3 setup.py bdist_wheel

echo "Installing wheel"
pip3 install dist/*.whl

```
But get the following error:

```
Traceback (most recent call last):
  File "model.py", line 1, in <module>
    import torch
  File "/home/panpan/.local/lib/python3.6/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: libiomp5.so: cannot open shared object file: No such file or directory

```

When running
`import torch
`
But the lib file actually exists here:

> ~/.local/lib/python3.6/site-packages/torch/lib/libiomp5.so

System configuration:

Ubuntu 18.04
Cmake 3.12.4
CUDA 9.2.148
gcc g++ 6.4.0
pytorch pulled from master, commit 6651fae

**Comment by ariesadel** [comment]
I have the same problem with the latest master.

**Comment by martinruenz** [comment]
I am having the same issue using the C++ API at the moment. I also used `USE_OPENCV=1` when compiling and I suspect that this might cause the problem. I'll recompile without the flag and see if it helps.
