### ISSUE TITLE
windows libtorch1.0 : cpp_export in Visual studio 2015: error C2397: conversion from 'long' to 'uint32_t' requires a narrowing conversion

### ISSUE THREAD

**Issue by kvcuong** [pytorch/pytorch#14961]
## 🐛 Bug
build the example in https://pytorch.org/tutorials/advanced/cpp_export.html with VS2015. I got an error : error C2397: conversion from 'long' to 'uint32_t' requires a narrowing conversion

## To Reproduce

1. Add emply project in VS2015
2. Add lib and include path in project's properties
3. Add code from https://pytorch.org/tutorials/advanced/cpp_export.html
4. Build with resnet18.pt

## Expected behavior

...libs\libtorch_gpucuda90\include\c10\core\backend.h(79): error C2397: conversion from 'long' to 'uint32_t' requires a narrowing conversion
## Environment
 - PyTorch Version (e.g., 1.0): 1.0 
 - OS (e.g., Linux): Windows 10 x64 
 - How you installed PyTorch (`conda`):
 - Build command you used (if compiling from source):
 - Python version:3.6.4
 - CUDA/cuDNN version: 9.0/7.3.1
 - GPU models and configuration: Gtx1070 Pascal 6.1
 - Any other relevant information:

**Comment by peterjc123** [comment]
Sorry, I don't think VS2015 will work because it doesn't have good support for c++11.

**Comment by soumith** [comment]
closing as unsupported compiler
