### ISSUE TITLE
The number zero (0) looks like a lowercase "o" in some places in the docs

### ISSUE THREAD

**Issue by jameshamm** [pytorch/pytorch#14965]
## 📚 Documentation

In the docs, a keyword parameter with default value of zero looks like a lowercase letter o. For example in [torch.util.data](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader), this is what the definition for dataloader looks like for me.

![image](https://user-images.githubusercontent.com/10179936/49699847-57392e00-fbce-11e8-810b-0622ff8966b1.png)

![image](https://user-images.githubusercontent.com/10179936/49699860-8bacea00-fbce-11e8-8dcd-4b84a0416350.png)

Zero looks fine in the docs for parameters themselves.

![image](https://user-images.githubusercontent.com/10179936/49699870-a1baaa80-fbce-11e8-97f4-5402addffbce.png)

Part of the issue is that numbers are smaller than usual.

**Comment by ezyang** [comment]
![image](https://user-images.githubusercontent.com/13564/122130762-1d33ed00-ce06-11eb-95ab-f134652ddb34.png)

is fixed
