### ISSUE TITLE
set default tensor options in c++

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#14962]
## 🚀 Feature
it used to be possible to access default tensor options and change them via:

```
at::TensorOptions o;
(set options as required..)
at::mutateDefaultTensorOptions().merge(o);
```

is it still possible to do something like the above?
it not, can it be restored/added?

thanks

**Comment by goldsborough** [comment]
No this is not supported. You can set the default dtype via `at::set_default_dtype` to something like ` torch::kFloat32`, but not other options. Just like in Python, we recommend that you create one `TensorOptions` object and pass it around.
