### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by BecketXu** [pytorch/pytorch#1497]
i install the pytorch successfully, but when i import it, error happened.the error is:
>import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 10): Symbol not found: _PySlice_AdjustIndices
  Referenced from: /usr/local/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so

ps: macOS10.12 python3.6 pytorch0.1.12
      i even install in ubuntu17.04, but still failure.

**Comment by apaszke** [comment]
Did you use pip or conda? Can you paste the command you used when installing PyTorch?

**Comment by BecketXu** [comment]
sure, it is
![image](https://cloud.githubusercontent.com/assets/24242652/25776879/b9b171f0-32fd-11e7-8769-f90a92ddffa7.png)

**Comment by apaszke** [comment]
cc @soumith

**Comment by yxonic** [comment]
same problem here

**Comment by AnudeepKonda** [comment]
I have this problem too

**Comment by krishnadusad** [comment]
Same. Installed using pip.

**Comment by triki97** [comment]
Same issue here.

**Comment by jaroslaw-weber** [comment]
Have same problem, updated from  0.1.11.post5 to torch-0.1.12.post2 with pip3, cuda 8.0 osx.

`
Collecting torch==0.1.12.post2 from http://download.pytorch.org/whl/torch-0.1.12.post2-cp36-cp36m-macosx_10_7_x86_64.whl
  Downloading http://download.pytorch.org/whl/torch-0.1.12.post2-cp36-cp36m-macosx_10_7_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 7.0MB/s 
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/site-packages (from torch==0.1.12.post2)
Installing collected packages: torch
  Found existing installation: torch 0.1.11.post5
    Uninstalling torch-0.1.11.post5:
      Successfully uninstalled torch-0.1.11.post5
Successfully installed torch-0.1.12.post2
`

**Comment by jaara** [comment]
Same here, fixed by upgrading Python from 3.6.0 to 3.6.1.
