### ISSUE TITLE
PyTorch 1.0 fails to build with fbgemm enabled

### ISSUE THREAD

**Issue by kleisauke** [pytorch/pytorch#14985]
## 🐛 Bug

Building PyTorch's [v1.0.0 tag](https://github.com/pytorch/pytorch/tree/v1.0.0) (with the `USE_FBGEMM=ON` environment variable) fails with: 

```
CMake Error at cmake/Dependencies.cmake:337 (set_property):
  set_property could not find TARGET fbgemm_generic.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  CMakeLists.txt:201 (include)
```
```
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-fbgemm --use-nnpack --use-mkldnn --use-qnnpack caffe2'
```

Because the fbgemm submodule isn't updated (it's on [0d5a159](https://github.com/pytorch/fbgemm/tree/0d5a159b944252e70a677236b570f291943e0543) instead than
[895646c](https://github.com/pytorch/FBGEMM/tree/895646cfe2b68e42a506c49217a635270d42bd09), where the avx2 specific code was moved to the `fbgemm_generic` target). 
Commit https://github.com/pytorch/pytorch/commit/51d26e76f7c5660e393f6b5e5fb7e0f374a65498 should be included in the v1.0.0 branch.

## To Reproduce

```bash
git clone --recurse-submodules --single-branch -b v1.0.0 https://github.com/pytorch/pytorch.git
export USE_FBGEMM=ON
python setup.py install
```

## Expected behavior

A successful build with fbgemm enabled.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Fedora release 29 (Twenty Nine)
GCC version: (GCC) 8.2.1 20181105 (Red Hat 8.2.1-5)
CMake version: version 3.12.1

Python version: 2.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

**Comment by zou3519** [comment]
cc @jamesr66a maybe?

**Comment by soumith** [comment]
cherry-picked onto v1.0.1. Closing now. Binaries will be out soon.
