### ISSUE TITLE
Build command `python setup.py rebuild_libtorch` does not exist

### ISSUE THREAD

**Issue by bdusell** [pytorch/pytorch#14980]
## 🐛 Bug

The CONTRIBUTING.md file documents a command (`python setup.py rebuild_libtorch`) for re-building only the PyTorch C++ code, but it does not exist.

The command is documented here: https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#build-only-what-you-need

## To Reproduce

1. Build PyTorch from source in development mode using `python setup.py build develop`.
1. Run `python setup.py rebuild_libtorch`

```
$ python setup.py rebuild_libtorch
Building wheel torch-1.0.0a0
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'rebuild_libtorch'
```

## Expected behavior

The command should exist, or the documentation in CONTRIBUTING.md should be updated.

I'm using this command as a workaround:

```
$ ninja -C build libtorch_python.so
```

## Environment

(I'm building this inside of a Docker container.)

PyTorch version: 1.0.0a0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.15.4)
[pip] torch (1.0.0a0, /app/pytorch)
[conda] Could not collect

**Comment by zou3519** [comment]
cc @pjh5 @anderspapitto @orionr did we deprecate this build option?

**Comment by pjh5** [comment]
Yes this has been deprecated. We've been moving setup.py commands into cmake itself. Cmake handles rebuilding only what's needed itself, though there are still some bugs around this related to ninja and nvcc. The only commands now are 'python setup.py build' or 'python setup.py develop'
