### ISSUE TITLE
Blocking: Do modules wait?

### ISSUE THREAD

**Issue by TheDiscoMole** [pytorch/pytorch#14988]
When I call `model(inputs)` does pyTorch create a non-blocking Queue of kernels and then wait for the result at the end or does every custom nested module in a graph have to painstakingly wait for  everything in `forward` to finish executing

 I want to segment my graph into many small executions of cells. When i run the cell on the entire input it is fast, but when i use `torch.narrow` to create views of input slices the model computes much slower.

Am I correct in assuming that `module.forward` is a blocking call?

**Comment by fmassa** [comment]
every (or almost every) operation in CUDA in PyTorch is asynchronous, and thus non-blocking.
Check the `Asynchronous Execution` section in the docs https://pytorch.org/docs/stable/notes/cuda.html
