### ISSUE TITLE
Math doesn't render

### ISSUE THREAD

**Issue by beneyal** [pytorch/pytorch#14991]
## 📚 Documentation

With the new 1.0 documentation up, the formulas in note for torch.optim.SGD isn't being rendered:
![image](https://user-images.githubusercontent.com/3891274/49739907-b022c800-fc9b-11e8-9863-dc42c8e11506.png)

Formulas in other places, e.g., torch.nn, appear fine.

**Comment by brsoff** [comment]
This looks to be fixed on master [torch.optim.SGD](https://pytorch.org/docs/master/optim.html#torch.optim.SGD), which is using the latest version of katex (0.10.0). Stable is still loading 0.9.0 as the latest [sphinxcontrib-katex](https://github.com/hagenw/sphinxcontrib-katex) that includes 0.10.0 was just released a few days ago.

**Comment by rgommers** [comment]
This was fixed a long time ago, closing. Thanks @beneyal and @brsoff
