### ISSUE TITLE
error: unknown type name 'mkldnn_shuffle_desc_t' 

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14995]
**UPDATE:** This issue will happen to anyone who has an old checkout of PyTorch and then updates it past the mkldnn update commit. Solve it with `git submodule update --init --recursive`

----

I was attempting to do the ROCm build on an older version of the Docker container `308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-clang7-rocmdeb-ubuntu16.04:230` but I got this error:

```
In file included from /var/lib/jenkins/pytorch/caffe2/ideep/operators/dropout_op.cc:1:                                              
In file included from /var/lib/jenkins/pytorch/caffe2/ideep/ideep_utils.h:6:                                                        
In file included from /var/lib/jenkins/pytorch/third_party/ideep/include/ideep.hpp:44:                                              
/var/lib/jenkins/pytorch/third_party/ideep/include/ideep/computations.hpp:4229:7: error: unknown type name 'mkldnn_shuffle_desc_t'  
      mkldnn_shuffle_desc_t data;                                                                                                   
      ^                                                                                                                             
/var/lib/jenkins/pytorch/third_party/ideep/include/ideep/computations.hpp:4313:7: error: unknown type name 'mkldnn_shuffle_desc_t'  
      mkldnn_shuffle_desc_t data;                                                                                                   
      ^                     
```

I confirmed that I have updated all submodules.

If you are a user and see this error, please comment below. I'm not sure if this is just my error at the moment.

CC @yinghai

**Comment by gujinghui** [comment]
@ezyang 
The mkldnn_shuffle_desc_t is introduced since mkldnn 0.17.
According to the log, the mkldnn src is too older.

Because the mkldnn is a submodule of ideep, instead of pytorch.
Sometimes, ideep got updated, but not its submodel.
That's why we are trying to make mkldnn a submodule of pytorch directly in #14987

**Comment by yinghai** [comment]
`git submodule update --init --recursive` should fix it?

**Comment by gujinghui** [comment]
Yes. I think so.

**Comment by yinghai** [comment]
Have you installed packages like confu?

**Comment by gujinghui** [comment]
Didn't try this before...

**Comment by vadimkantorov** [comment]
@ezyang I just hit this same issue on a fresh `git clone https://github.com/pytorch/pytorch --recursive`. An excerpt:

```
In file included from .../vadim/env/pytorch/third_party/ideep/include/ideep.hpp:44:0,
                 from .../vadim/env/pytorch/caffe2/ideep/ideep_utils.h:6,
                 from .../vadim/env/pytorch/caffe2/ideep/operators/concat_split_op.cc:1:
.../vadim/env/pytorch/third_party/ideep/include/ideep/computations.hpp: In constructor ‘ideep::channel_shuffle_forward::descriptor::descriptor(const ideep::param::descriptor&, int, int, ideep::prop_kind)’:
.../vadim/env/pytorch/third_party/ideep/include/ideep/computations.hpp:4229:7: error: ‘mkldnn_shuffle_desc_t’ was not declared in this scope
       mkldnn_shuffle_desc_t data;
       ^
.../vadim/env/pytorch/third_party/ideep/include/ideep/computations.hpp:4231:45: error: ‘data’ was not declared in this scope
           mkldnn_shuffle_forward_desc_init(&data,
                                             ^
.../vadim/env/pytorch/third_party/ideep/include/ideep/computations.hpp:4233:68: error: ‘mkldnn_shuffle_forward_desc_init’ was not declared in this scope
               src_desc.get_mkldnn_memory_desc_t(), axis, group_size),
                                                                    ^
.../vadim/env/pytorch/third_party/ideep/include/ideep/computations.hpp: In constructor ‘ideep::channel_shuffle_backward::descriptor::descriptor(const ideep::param::descriptor&, int, int)’:
.../vadim/env/pytorch/third_party/ideep/include/ideep/computations.hpp:4313:7: error: ‘mkldnn_shuffle_desc_t’ was not declared in this scope
       mkldnn_shuffle_desc_t data;
       ^
.../vadim/env/pytorch/third_party/ideep/include/ideep/computations.hpp:4314:60: error: ‘data’ was not declared in this scope
       error::wrap_c_api(mkldnn_shuffle_backward_desc_init(&data,
                                                            ^
.../vadim/env/pytorch/third_party/ideep/include/ideep/computations.hpp:4317:41: error: ‘mkldnn_shuffle_backward_desc_init’ was not declared in this scope
             static_cast<int>(group_size)),
                                         ^

```

**Comment by gujinghui** [comment]
pls confirm the commit hash of mkldnn.
It should be 830a10059a018cd2634d94195140cf2d8790a75a, or later

`cd third_party/ideep/mkl-dnn`
`git log`

if not, try below cmd.

`cd third_party/ideep`
`git submodule update --init mkl-dnn`

**Comment by tunz** [comment]
the same issue for me. everything is up-to-date, but still build fails like https://github.com/pytorch/pytorch/issues/14995#issuecomment-446413669.
pytorch: 479481b6cbcdccbc99c8c45da30033b77502b96b
third_party/ideep/mkl-dnn: 830a10059a018cd2634d94195140cf2d8790a75a

**Comment by gujinghui** [comment]
still cannot repro this issue locally.
The mkldnn_shuffle_desc_t is defined in third_party/ideep/mkl-dnn/include/mkldnn_types.h#714 .
It should be OK with mkl-dnn 830a...
Pls confirm there's no local changes on your host.

**Comment by vadimkantorov** [comment]
Also, `830a10059a018cd2634d94195140cf2d8790a75a` and fails. No local changes.

**Comment by tunz** [comment]
I found what the problem was. there was an instruction to install mkldnn through conda, but it's now removed from README (https://github.com/pytorch/pytorch/commit/5fd69e75516326c2cdb3af9ffa702068adc6fbf6). So, my host had an old version of mkldnn, and pytorch was using it instead of ideep/mkl-dnn. 
now I can successfully build pytorch after removing the old mkldnn by `conda uninstall mkldnn`.

**Comment by vadimkantorov** [comment]
It may be https://github.com/pytorch/pytorch/issues/13188 or something similar preventing the detection of local headers. (A solution would be to have a check in build time that the headers resolve in the local/specified directory and fail fast)

**Comment by dendisuhubdy** [comment]
obtained this issue too on d71fac20ebf6b393e464d312b8a38ae1c45c3386

**Comment by dendisuhubdy** [comment]
Nevermind, so I solved it via 
```
cd third_party/ideep # this is on branch 
 grokmachine@Dendis-MacBook-Pro   ~/dev/facebook/pytorch/third_party/ideep     remotes/origin/mkldnn_0.17  git submodule update --init --recursive
 grokmachine@Dendis-MacBook-Pro   ~/dev/facebook/pytorch/third_party/ideep     remotes/origin/mkldnn_0.17  git checkout master
M	mkl-dnn
Previous HEAD position was d06f361 Fix klocwork issues
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
```
then I did a `MACOSX_DEPLOYMENT_TARGET=10.14 CC=cc MAX_JOBS=25 CXX=c++ python3 setup.py install` and it solved the problem

**Comment by dzung-hoang** [comment]
I encountered this error and found that it is caused by mkldnn include files belonging to the previous install of pytorch. I resolved it by uninstalling pytorch before building the latest version.

**Comment by AshwinAKannan** [comment]
I still encounter this [problem](https://github.com/pytorch/pytorch/issues/14995#issuecomment-446413669)

```
git clone https://github.com/pytorch/pytorch &&\
    cd pytorch && \
    git submodule update --init --recursive  &&\
    pip install pyyaml --user &&\
    pip install -r requirements.txt --user &&\
    USE_OPENCV=1 \
    BUILD_TORCH=ON \
    CMAKE_PREFIX_PATH="/usr/bin/" \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/lib:$LD_LIBRARY_PATH \
    CUDA_BIN_PATH=/usr/local/cuda/bin \
    CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda/ \
    CUDNN_LIB_DIR=/usr/local/cuda/lib64 \
    CUDA_HOST_COMPILER=cc \
    USE_CUDA=1 \
    USE_NNPACK=1 \
    CC=cc \
    CXX=c++ \
    TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1+PTX" \
    TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    python setup.py bdist_wheel
```

I don't have a conda install of mkldnn. Here's the partial output of `conda list`

l```
zo                       2.10                 h49e0be7_2
markupsafe                1.0              py36hd9260cd_1
matplotlib                2.2.2                    pypi_0    pypi
mccabe                    0.6.1            py36h5ad9710_1
mistune                   0.8.3            py36h14c3975_1
mkl                       2019.1                      144
mkl-include               2019.1                      144
mkl-service               1.1.2            py36he904b0f_5
mkl_fft                   1.0.10           py36ha843d7b_0
mkl_random                1.0.2            py36hd81dba3_0
mock                      2.0.0                    pypi_0    pypi
more-itertools            4.1.0                    py36_0
mpc                       1.0.3                hec55b23_5
mpfr                      3.1.5                h11a74b3_2
mpi                       1.0                     openmpi    conda-forge
mpmath                    1.0.0            py36hfeacd6b_2
msgpack                   0.6.0                    pypi_0    pypi
msgpack-python            0.5.6            py36h6bb024c_0
multipledispatch          0.5.0                    py36_0
navigator-updater         0.2.1                    py36_0
nb_conda                  2.2.1                    py36_0    conda-forge
nb_conda_kernels          2.2.0                 py36_1000    conda-forge

```
