### ISSUE TITLE
License unavailable in the installed package

### ISSUE THREAD

**Issue by hanyucui** [pytorch/pytorch#15028]
Hi. I noticed that, after pytorch is installed, the PKG-INFO file says the license is unknown. Our tools rely on this file to obtain the correct license information. Is it possible to put correct license information in it?

For example, `lib/python3.6/site-packages/torch-0.4.1-py3.6.egg-info/PKG-INFO` has:
```
Metadata-Version: 1.0
Name: torch
Version: 0.4.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Description: UNKNOWN
Platform: UNKNOWN
```

**Comment by rgommers** [comment]
Metadata for the `1.7.0` release seems correct, so closing this. Not sure when it got fixed, probably a long time ago.

Thanks for the report @hanyucui
