### ISSUE TITLE
Unknown Error at torch/lib/THC/THCGeneral.c:66

### ISSUE THREAD

**Issue by locosoft1986** [pytorch/pytorch#1503]
My environment is Linux Mint 18.
I followed the tutorial to install Pytorch using virtualenv with python 3.5 and CUDA 8 support.
When I have installed I followed the "autograd" examples in tutorials it was ok.
After a while(watch Youtube videos and other stuff), when I try :
`
x =  Variable(torch.ones(2,2))
`
It outputs:
`
THCudaCheck FAIL file=/b/wheel/pytorch-src/torch/lib/THC/THCGeneral.c line=66 error=30 : unknown error
`
after I reboot my computer or reinstall PyTorch the problem still exists, but when I execute:
`
import tensorflow as tf
`
The cuda messages appear and seems fine.
My Nvidia SMI results:
`
Sun May  7 22:26:10 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    Off  | 0000:01:00.0     Off |                  N/A |
| N/A   40C    P8    N/A /  N/A |    251MiB /  2000MiB |      6%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      2928    G   /usr/lib/xorg/Xorg                             152MiB |
|    0      4383    G   cinnamon                                        34MiB |
|    0      5725    G   nvidia-settings                                  0MiB |
|    0      6066    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    61MiB |
+-----------------------------------------------------------------------------+
`

I have no clue what's wrong.

**Comment by locosoft1986** [comment]
when I am using Keras 1.2.2 with Tensorflow 1.0.0 as backend, I get the following message:
`
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: jeremy-lab
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: jeremy-lab
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 375.39.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.39  Tue Jan 31 20:47:00 PST 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 375.39.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 375.39.0
`
:( 
it seems the Cuda driver crashed

**Comment by soumith** [comment]
cuda error unknown happens for many weird reasons.
Here's one try to fix it:

```
$ sudo python
>>> import torch
>>> a = torch.randn().cuda()
```
Then exit.

This might initialize the device drivers properly. Sometimes, the nvidia device files are not properly created under /dev/ and sudo helps.
