### ISSUE TITLE
RuntimeError: unknown scalar type during JIT fusion code generation

### ISSUE THREAD

**Issue by beichen2012** [pytorch/pytorch#15038]
python3.6(anaconda) + pytorch v1.0.0

the torch script code(torch.jit.ScriptModule) had been compiled. but when forward, I meet the error: 
RuntimeError: unknown scalar type during JIT fusion code generation。

I have no idea about it.
Does any one could me ? please.

thank you.

**Comment by zou3519** [comment]
I can reproduce this, thank you for the script @beichen2012

**Comment by zou3519** [comment]
#14336 (cc @t-vi) introduced support for `aten::_cast_float` for the fuser, but the CUDA fuser doesn't implement bool type. Might be an easy fix, looking into it
