### ISSUE TITLE
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by singlasahil14** [pytorch/pytorch#1504]
Pytorch is giving CUDNN_STATUS_INTERNAL_ERROR when I try to run my program with gpu_id 0 and CUDA_VISIBLE_DEVICES=[1,2,3]. I was running it this way because GPU 0 was fully occupied.

**Comment by apaszke** [comment]
You're using invalid syntax for CUDA_VISIBLE_DEVICES, which makes no GPUs visible to the process and that's why cuDNN fails. It should be `1,2,3` not `[1,2,3]`.
