### ISSUE TITLE
Tracer doesn't work with join/wait

### ISSUE THREAD

**Issue by highker** [pytorch/pytorch#15052]
Reported error: `RuntimeError: output 0 of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.`

To reproduce:
```python
def test_async_script_trace(self):
        class Module(torch.jit.ScriptModule):
            def __init__(self):
                super(Module, self).__init__(False)

            @torch.jit.script_method
            def forward(self, x):
                future = torch.jit._fork(torch.neg, x)
                outputs = []
                outputs.append(torch.jit._wait(future))

                return outputs

        class Tuple(nn.Module):
            def __init__(self):
                super(Tuple, self).__init__()
                self.module = Module()

            def forward(self, x):
                return tuple(self.module(x))

        x = torch.rand(3, 4)
        module = torch.jit.trace(Tuple(), (x), _force_outplace=True)
        self.assertEqual(module(x), torch.neg(x))

**Comment by apaszke** [comment]
Probably because tracing is a thread-local property now. You need to set the tracing state in the worker that will execute the future if you want tracing to continue.

**Comment by highker** [comment]
Yes, thread-local is a problem. In addition to that , the following codepath is also an issue:
https://github.com/pytorch/pytorch/blob/517c7c98610402e2746586c78987c64c28e024aa/torch/csrc/jit/graph_executor.cpp#L531 

From the above example, the output of `Module.forward` is a list of tensors, say `[%1]`. `python_tracer.cpp` will cast this to a tuple `(%1)`, given tracer can only support tuple or tensor. However `%1` is created within `fork` that should not be directly accessed by the parent code. Essentially `%1` is in another tracing state from the root one. The only value that is accessible by the root tracer is the output of `wait`, say `%2`, which points to the same variable of `%1`.
So on making the tuple of the tracer output, we should use `%2` rather than `%1`.
