### ISSUE TITLE
[docs] Delete ffi documentation

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#15066]
there's still a page on it: https://pytorch.org/docs/master/ffi.html?highlight=ffi

**Comment by Leechen2014** [comment]
pytorch 1.0 was realsed in  Dec. 2018.    torch.utils.ffi is deprecated. this link show pytorch1.0 API, 
and you can see ffi API in pytoch0.41
https://pytorch.org/docs/0.4.1/cpp_extension.html?highlight=torch%20utils%20cpp_extension

**Comment by zou3519** [comment]
resolved by #15220

**Comment by acgtyrant** [comment]
But the docs in https://pytorch.org/docs/master/notes/extending.html still mentions: "WRITING CUSTOM C EXTENSIONS Example available at this GitHub repository."
