### ISSUE TITLE
[docs] All upper-case headings are a little weird

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#15061]
https://pytorch.org/docs/master/distributions.html#relaxedonehotcategorical

![image](https://user-images.githubusercontent.com/5652049/49818771-96d45700-fd41-11e8-97cd-8d87f4a5fd8d.png)

**Comment by ezyang** [comment]
![image](https://user-images.githubusercontent.com/13564/122130884-4eacb880-ce06-11eb-82f7-c6100a177922.png)

fixed
