### ISSUE TITLE
Snap Package Support

### ISSUE THREAD

**Issue by mikeroyal** [pytorch/pytorch#15079]
I was thinking in the install and setup could be improved for Ubuntu and other Linux distros by having a [snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I made the snap as a contribution?

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by soumith** [comment]
I'm not generally excited about packaging that we dont control, and make sure it's up to date.
`pip` and `conda` are de-facto Python package managers, and we provide default packages on both.

What makes the install and setup more improved by providing it on Snap?

**Comment by mikeroyal** [comment]
@soumith, security-wise each snap is confined using a range of kernel isolation and security mechanisms, tailored to the snap, ensuring that vulnerabilities in the application are contained to the greatest degree currently possible. A careful review process ensures that snaps only receive the permissions they require to operate. Users do not have to make complex security decisions when installing the snap. You can read more about the security and configurations here [a guide to snap permissions and interfaces](https://blog.ubuntu.com/2018/11/01/a-guide-to-snap-permissions-and-interfaces).

**Comment by soumith** [comment]
@mikeroyal all of what you said make sense for Applications, like Chrome, Spotify app etc. It doesn't make sense for a Python library, unless you are packaging not just PyTorch in the Snap, but all of the Python ecosystem, along with `pip` etc.

**Comment by mikeroyal** [comment]
That's a good point maybe snaps is not a good option for this project. I will close this issue.
