### ISSUE TITLE
Does libtorch support mingw on windows?

### ISSUE THREAD

**Issue by XiaXuehai** [pytorch/pytorch#15099]
I got an error when running the programs on windows with mingw-64. The error is 
```
E:/libtorch/include/torch/csrc/jit/script/module.h:84:36: error: function 'std::shared_ptr<torch::jit::Graph> torch::jit::script::Method::graph() const' definition is marked dllimport
   TORCH_API std::shared_ptr<Graph> graph() const {
                                    ^~~~~
E:/libtorch/include/torch/csrc/jit/script/module.h:88:33: error: function 'const string& torch::jit::script::Method::name() const' definition is marked dllimport
   TORCH_API const std::string & name() const {
                                 ^~~~

```

**Comment by Whu-wxy** [comment]
I also got this error , help !!!!!

**Comment by peterjc123** [comment]
Please remove TORCH_API in `torch/csrc/jit/script/module.h#L84/88` and try again.

**Comment by XiaXuehai** [comment]
Got more error like this:
```
E:\libtorch\include\torch\csrc\jit\script\module.h|102|error: 'graph' was not declared in this scope|
E:\libtorch\include\torch\csrc\jit\script\module.h|202|error: 'const struct torch::jit::script::Method' has no member named 'graph'; did you mean 'graph_'?|
E:\libtorch\include\torch\csrc\jit\script\module.h|212|error: 'const struct torch::jit::script::Method' has no member named 'name'; did you mean 'name_'?|
E:\libtorch\include\torch\csrc\jit\script\module.h|212|error: could not convert '{<expression error>, std::move<std::vector<c10::Argument>&>(args), std::move<std::vector<c10::Argument>&>(returns)}' from '<brace-enclosed initializer list>' to 'c10::FunctionSchema'|
E:\libtorch\include\torch\csrc\jit\script\module.h|217|error: 'graph' was not declared in this scope|
E:\libtorch\include\torch\csrc\jit\script\module.h|223|error: 'getSchema' was not declared in this scope|
E:\libtorch\include\torch\csrc\jit\script\compiler.h|213|error: 'struct torch::jit::script::Method' has no member named 'graph'; did you mean 'graph_'?|
```

**Comment by Whu-wxy** [comment]
#if defined(torch_EXPORTS)
#define TORCH_API  __declspec(dllexport)
#else
#define TORCH_API  __declspec(dllimport)
#endif

I found this usage in CSDN this morning, maybe this is the root of the problem

**Comment by Whu-wxy** [comment]
I found TORCH_API is defined in "WindowsTorchApiMacro.h",  it means exporting a function
. And All four of these are inline functions. I didn't see it before.
You can find it in CSDN,but I don't know what to do next.
https://blog.csdn.net/mniwc/article/details/7993361

**Comment by Whu-wxy** [comment]
It’s really a headache! I used Qt to make an Android app these days, and there was also a strange problem when using caffe.

**Comment by Whu-wxy** [comment]
I've just successfully used CMake to build my program, combining the pytorch with Qt, which is probably a good choice.I haven't used cmake much before, so today I have a general understanding of it.

**Comment by peterjc123** [comment]
@Whu-wxy Congratulations! Could you please show us what have you done to make it work?

**Comment by Whu-wxy** [comment]
I just finished writing a blog about this process and using CMake to build pytorch+Qt, which went well overall.As a beginner, it's a little fulfilling and fun to do this.
https://blog.csdn.net/m0_38133212/article/details/84977505

**Comment by peterjc123** [comment]
@Whu-wxy I thought that you have solved this problem on Windows. However, from your blog post, it seems that you have done that using Ubuntu. Well, I'll try it if I have time.

**Comment by soumith** [comment]
thanks for writing the blogpost @Whu-wxy . Closing via @Whu-wxy 's comment https://github.com/pytorch/pytorch/issues/15099#issuecomment-446544023

**Comment by MatthiasLen** [comment]
On Ubuntu the compilation is no problem, on a windows machine I encounter the same compilation errors as depicted in the last screenshot from @Whu-wxy blog post  https://blog.csdn.net/m0_38133212/article/details/84977505. Following your suggestions unfortunately did not solve the problem.

@Whu-wxy in your blogpost you write that you did not succeed compiling on windows just by chaning the path. Above you write that chaning the paths in the cmake file is sufficient. I am confused =) Can we reopen this topic?

**Comment by MatthiasLen** [comment]
Dear @peterjc123 thank you for your quick response. Ok, I just tired to compile the minimal example from the tutorial page (https://pytorch.org/tutorials/advanced/cpp_export.html) with Visual Studio 14 2015, MSVC 19.0.23026.0. 

Unfortunately this did not work. I get numerous C2334 errors, for example in 
/libtorch/include/c10/util/typeid.h in line 368 ff 

```
  constexpr New* newFn() const noexcept {
    return data_->new_;
  }
  /**
   * Returns the placement new function pointer for individual items.
   */
  constexpr PlacementNew* placementNew() const noexcept {
    return data_->placementNew_;
  }
```

Somehow the compiler has problems handling the constexpr or noexcept specifiers. The compability table 
https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140) indicates that VS2015 should support these c++11 language features. Seems that I am missing something >.<

**Comment by peterjc123** [comment]
IMO although constexpr is said to be supported in MSVC 2015, but we have to use MSVC 2017 in reality. My recommendation is to use MSVC 15.3 that supports various CUDA versions.

**Comment by HudamaoF** [comment]
I have just made a failed attempt. But Visual Studio is supported

**Comment by brccabral** [comment]
I also tried to use mingw without any luck, only Visual Studio compiles.
