### ISSUE TITLE
[Caffe2] How to fetch gradients while doing backward pass

### ISSUE THREAD

**Issue by pjavia-iterativescopes** [pytorch/pytorch#15107]
Example pytorch has torch.autograd.grad. What is the equivalent function in Caffe2? I want to check some gradients in the backward pass, how to do that?

**Comment by RomanSteinberg** [comment]
I think this question is for [forum](https://discuss.pytorch.org/) and not for github. So, I suggest you to close the issue.

When I wish to check gradients in bacward pass I look at tensor attribute .grad and .grad_ in debugger. It has nothing common with torch.autograd.grad. The latter makes numeric calculations of gradients.
