### ISSUE TITLE
[PyTorch/Caffe2] MKL detection for MKLDNN broken

### ISSUE THREAD

**Issue by h6197627** [pytorch/pytorch#15118]
## 🐛 Bug

Building PyTorch or Caffe2 project with MKLDNN fails to link with MKL library.
In [FindMKLDNN.cmake](https://github.com/pytorch/pytorch/tree/master/cmake/Modules/FindMKLDNN.cmake) **MKL_LIBRARIES_gomp_LIBRARY** is evaluated to **-fopenmp** and **MKL_LIBRARIES_iomp5_LIBRARY** is empty. So EXISTS checking fails and MKLIOMP5LIB is set to "" with FORCE in this part of [FindMKLDNN.cmake](https://github.com/pytorch/pytorch/tree/master/cmake/Modules/FindMKLDNN.cmake)
```
  IF (EXISTS "${MKL_LIBRARIES_gomp_LIBRARY}")
    SET(MKLIOMP5LIB ${MKL_LIBRARIES_gomp_LIBRARY} CACHE STRING "Override MKL-DNN omp dependency" FORCE)
  ELSEIF(EXISTS "${MKL_LIBRARIES_iomp5_LIBRARY}")
    SET(MKLIOMP5LIB ${MKL_LIBRARIES_iomp5_LIBRARY} CACHE STRING "Override MKL-DNN omp dependency" FORCE)
  ELSEIF(EXISTS "${MKL_LIBRARIES_libiomp5md_LIBRARY}")
    SET(MKLIOMP5DLL ${MKL_LIBRARIES_libiomp5md_LIBRARY} CACHE STRING "Override MKL-DNN omp dependency" FORCE)
  ELSE(EXISTS "${MKL_LIBRARIES_gomp_LIBRARY}")
    SET(MKLIOMP5LIB "" CACHE STRING "Override MKL-DNN omp dependency" FORCE)
    SET(MKLIOMP5DLL "" CACHE STRING "Override MKL-DNN omp dependency" FORCE)
  ENDIF(EXISTS "${MKL_LIBRARIES_gomp_LIBRARY}")
```
Then while configuring [MKL.cmake](https://github.com/intel/mkl-dnn/tree/830a10059a018cd2634d94195140cf2d8790a75a/cmake/MKL.cmake) it can't redefine **MKLIOMP5LIB** and fails here with fatal error

## To Reproduce

> cmake -D USE_MKLDNN=ON ..
same problem occurs when using setup.py for PyTorch

## Expected behavior

Successful configuration of Caffe2/PyTorch project

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Any other relevant information: Intel MKL 2019.0

**Comment by h6197627** [comment]
I am closing this considering #15347 and #15345

**Comment by gujinghui** [comment]
psl try #15387

**Comment by ezyang** [comment]
@h6197627 Ack, so sorry, I wish I saw your bug report first :)
