### ISSUE TITLE
NNAPI calls on Pytorch?

### ISSUE THREAD

**Issue by abrarmatin** [pytorch/pytorch#15128]
Caffe2 supports function calling into NNAPI. Will Pytorch now follow the same path and also support NNAPI? If so, how do we enable NNAPI builds with Pytorch?

**Comment by soumith** [comment]
we dont expect to support it anytime in the short term. Caffe2 will continue being the NNAPI path.
If we expect to support it in the far future, I'll reopen the issue.

**Comment by abrarmatin** [comment]
I've been trying to find a flag like there is on tensorflow to enable running Pytorch models on NNAPI through caffe2 calls. Is there such thing?
