### ISSUE TITLE
Printing Tensor from traced module results in TypeError: rsplit() takes no keyword arguments

### ISSUE THREAD

**Issue by 1Reinier** [pytorch/pytorch#15135]
## 🐛 Bug
Python 2.7 errors out on printing tensor generate by traced module.

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-43405c9b8ee8> in <module>()
----> 1 print features

/.../lib/python2.7/site-packages/torch/tensor.pyc in __repr__(self)
     67         else:
     68             if hasattr(sys.stdout, 'encoding'):
---> 69                 return torch._tensor_str._str(self).encode(
     70                     sys.stdout.encoding or 'UTF-8', 'replace')
     71             else:

/.../lib/python2.7/site-packages/torch/_tensor_str.pyc in _str(self)
    283         name = type(self.grad_fn).__name__
    284         if name == 'CppFunction':
--> 285             name = self.grad_fn.name().rsplit('::', maxsplit=1)[-1]
    286         suffixes.append('grad_fn=<{}>'.format(name))
    287     elif self.requires_grad:

TypeError: rsplit() takes no keyword arguments
```

## To Reproduce

```python
import torch
import torchvision

resnet = torchvision.models.resnet18()
sample_image = torch.randn(1, 3, 224, 224)
resnet_jit = torch.jit.trace(resnet, sample_image)

features = resnet_jit(sample_image)
print features

```

## Expected behavior

Printed representation of the tensor contents as a string.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: version 3.5.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.0.225
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 390.48
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.0.4
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.0.5
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn_static.a_for_7.0.4

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] torch (1.0.0)
[pip] torchfile (0.1.0)
[pip] torchvision (0.2.1)
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.3                      1
[conda] mkl_fft                   1.0.4            py27h4414c95_1
[conda] mkl_random                1.0.1            py27h4414c95_1
[conda] pytorch                   1.0.0           py2.7_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by driazati** [comment]
This is fixed in #12732, I'll try to get it merged soon
