### ISSUE TITLE
list(tensor) seems to disregard tensor device and initialize the current device instead

### ISSUE THREAD

**Issue by vzhong** [pytorch/pytorch#1513]
The default way of converting a `Tensor` into a list of native type numbers in Python is this:

```python
a = torch.Tensor(5).gpu(2)
a.cpu().numpy().tolist()
``` 

However, there is a less verbose way of doing this:

```python
list(a)
```

While debugging a memory leak, I found that the latter method of using `list` actually leaks memory onto a default GPU:

```python
a = torch.Tensor(5).gpu(2)  # now GPU2 is used
b = list(a)  # now memory has leaked to GPU0
```

Is this behaviour intended? It seems unintuitive that calling `list` on a `Tensor` on GPU 2 would use up storage on GPU 0.

**Comment by colesbury** [comment]
It's not "leaked", but it does initialize the current device. We could avoid this by setting the current device in [THPTensor_(select)](https://github.com/pytorch/pytorch/blob/77035d151e08f7aee97689cf1f29bbf8a968a61e/torch/csrc/generic/methods/Tensor.cwrap#L207).

However, there are a bunch of other calls that initialize the current device too, some of which would be hard to fix.

**Comment by vzhong** [comment]
@colesbury please feel free to change to title!

**Comment by apaszke** [comment]
Ah, I thought we're sending the tensor to GPU0 for some reason, but I think that if it's only a matter of initializing the device then it's ok. If you don't want to use GPU0 at all please set `CUDA_VISIBLE_DEVICES` env var before starting the interpreter.

**Comment by vzhong** [comment]
Well @apaszke @colesbury that is certainly a solution, however I still think it is not intuitive that if my current GPU is 0, `list(torch.Tensor(5).gpu(2)` allocates memory on GPU0 at all.

**Comment by apaszke** [comment]
I know it's not great, but fixing it would be quite complicated and would decrease performance, so I'd rather keep that slightly weird side effect.

**Comment by jekbradbury** [comment]
The best way to get a list is `tensor.tolist()`, right? And that shouldn't allocate anything on a device?

**Comment by apaszke** [comment]
Both don't allocate anything, but they do different things (`list(tensor)` will give you a list of slices along the first dim, `tensor.tolsit()` will recursively convert all dimensions).

The memory increase (from 2MB to ~220MB) is just the NVIDIA driver initializing the device. It initializes the current one when `cudaMemcpy` is called, even if the copy is completely unrelated to the current GPU.

**Comment by vzhong** [comment]
@apaszke OK yeah that sounds very reasonable.
