### ISSUE TITLE
Build simple c++ example-cpp using Libtorch fails on arm with undefined reference to c10::Error::Error

### ISSUE THREAD

**Issue by uvaidya** [pytorch/pytorch#15138]
## To Reproduce

1.Build PyTorch from source.

2.Replace libs folder in Libtorch (https://download.pytorch.org/libtorch/nightly/cu90/libtorch-shared-with-deps-latest.zip) with the pytorch/build/lib (lib folder created on arm after building pytorch).

3.build the example-cpp 

## Error Message

>  nvidia@tegra-ubuntu:~/uvaidya/LibTorch/example-app/build$ make
> [ 50%] Linking CXX executable example-app
> CMakeFiles/example-app.dir/example-app.cpp.o: In function `c10::Device::Device(c10::DeviceType, short)':
> example-app.cpp:(.text._ZN3c106DeviceC2ENS_10DeviceTypeEs[_ZN3c106DeviceC5ENS_10DeviceTypeEs]+0xdc): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
> example-app.cpp:(.text._ZN3c106DeviceC2ENS_10DeviceTypeEs[_ZN3c106DeviceC5ENS_10DeviceTypeEs]+0x1bc): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
> CMakeFiles/example-app.dir/example-app.cpp.o: In function `at::TensorOptions::device() const':
> example-app.cpp:(.text._ZNK2at13TensorOptions6deviceEv[_ZNK2at13TensorOptions6deviceEv]+0x30): undefined reference to `at::getDefaultTensorOptions()'
> CMakeFiles/example-app.dir/example-app.cpp.o: In function `at::TensorOptions::requires_grad() const':
> example-app.cpp:(.text._ZNK2at13TensorOptions13requires_gradEv[_ZNK2at13TensorOptions13requires_gradEv]+0x38): undefined reference to `at::getDefaultTensorOptions()'
> CMakeFiles/example-app.dir/example-app.cpp.o: In function `c10::impl::getDeviceGuardImpl(c10::DeviceType)':
> example-app.cpp:(.text._ZN3c104impl18getDeviceGuardImplENS_10DeviceTypeE[_ZN3c104impl18getDeviceGuardImplENS_10DeviceTypeE]+0x11c): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
> CMakeFiles/example-app.dir/example-app.cpp.o: In function `torch::autograd::make_variable(at::Tensor, bool)':
> example-app.cpp:(.text._ZN5torch8autograd13make_variableEN2at6TensorEb[_ZN5torch8autograd13make_variableEN2at6TensorEb]+0xbc): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
> CMakeFiles/example-app.dir/example-app.cpp.o: In function `torch::jit::SourceRange::highlight(std::ostream&) const':
> example-app.cpp:(.text._ZNK5torch3jit11SourceRange9highlightERSo[_ZNK5torch3jit11SourceRange9highlightERSo]+0x1c0): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
> example-app.cpp:(.text._ZNK5torch3jit11SourceRange9highlightERSo[_ZNK5torch3jit11SourceRange9highlightERSo]+0x2b8): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
> example-app.cpp:(.text._ZNK5torch3jit11SourceRange9highlightERSo[_ZNK5torch3jit11SourceRange9highlightERSo]+0x41c): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
> CMakeFiles/example-app.dir/example-app.cpp.o:example-app.cpp:(.text._ZNK5torch3jit11SourceRange9highlightERSo[_ZNK5torch3jit11SourceRange9highlightERSo]+0x594): more undefined references to `c10::Error::Error(c10::SourceLocation, std::string const&)' follow
> CMakeFiles/example-app.dir/example-app.cpp.o: In function `torch::rand(c10::ArrayRef<long>, at::TensorOptions const&)':
> example-app.cpp:(.text._ZN5torch4randEN3c108ArrayRefIlEERKN2at13TensorOptionsE[_ZN5torch4randEN3c108ArrayRefIlEERKN2at13TensorOptionsE]+0x98): undefined reference to `c10::Symbol::fromQualString(std::string const&)'
> CMakeFiles/example-app.dir/example-app.cpp.o: In function `c10::intrusive_ptr<at::TensorImpl, at::UndefinedTensorImpl>::retain_()':
> example-app.cpp:(.text._ZN3c1013intrusive_ptrIN2at10TensorImplENS1_19UndefinedTensorImplEE7retain_Ev[_ZN3c1013intrusive_ptrIN2at10TensorImplENS1_19UndefinedTensorImplEE7retain_Ev]+0x114): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
> collect2: error: ld returned 1 exit status
> CMakeFiles/example-app.dir/build.make:99: recipe for target 'example-app' failed
> make[2]: *** [example-app] Error 1
> CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/example-app.dir/all' failed
> make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

## Environment

Collecting environment information...
PyTorch version: 1.0.0a0+db5d313
Is debug build: No
CUDA used to build PyTorch: 9.2.78

OS: Ubuntu 16.04 LTS
GCC version: (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.3

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.7.1.2
/usr/lib/aarch64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by huangyuyao** [comment]
I managed to successfully compile it on Jetson TX2 following these steps:

1.Build PyTorch from source. `python3 setup.py build`

2.No need to download LibTorch from the official website, which is the x86_64 build.

3.build the example-cpp using compiled tmp_install directory: `cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/pytorch/torch/lib/tmp_install ..`

**Comment by soumith** [comment]
@uvaidya i ran into a related problem while building torch-android.

You might be building `libtorch` with a compiler that is incompatible with the compiler building your final app.

For example, you built libtorch with gcc 4.9.2 and your final app with gcc 5.1, and the C++ ABI between both of them is not the same, so you are seeing linker errors like these
