### ISSUE TITLE
Mac OSX 10.13.5, CUDA 9.0 , pytorch 

### ISSUE THREAD

**Issue by Danieldemanou** [pytorch/pytorch#15141]
Hello I have an error with the command 
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install 
I'm trying to install Pytorch for Mac I’m following this tutorial : 
https://www.cs.rochester.edu/u/kautz/Installing-Pytorch-Cuda-on-Macbook.html

I’m using macOS 10.13.4
I have installed: 
- xcode 8.3.3 
- Python 3.6.7 with anaconda 
- Cuda 9.0 
- Install Cuda driver 396 
I was supposed to install cuDNN v7.1.4 for cuda 9.0 but this is no longer available for Mac so I took  cuDNN v7.0.4 Library for OSX

I installed pytorch with the following command: 
conda install pytorch=0.4.1 -c pytorch 
I did that because conda install pytorch=0.4.1 cuda90 -c pytorch did not work. I think the whl file is not longer available on https://pytorch.org/get-started/previous-versions/ 
So after I did that, I ran the command line MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install  
Now I get this : 

running install
running build_deps
+ USE_CUDA=0
+ USE_ROCM=0
+ USE_NNPACK=0
+ USE_MKLDNN=0
+ USE_GLOO_IBVERBS=0
+ USE_DISTRIBUTED_MW=0
+ FULL_CAFFE2=0
+ [[ 6 -gt 0 ]]
+ case "$1" in
+ USE_CUDA=1
+ shift
+ [[ 5 -gt 0 ]]
+ case "$1" in
+ USE_NNPACK=1
+ shift
+ [[ 4 -gt 0 ]]
+ case "$1" in
+ break
+ CMAKE_INSTALL='make install'
+ USER_CFLAGS=
+ USER_LDFLAGS=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
++ uname
+ '[' Darwin == Darwin ']'
+ '[' -d /usr/local/opt/ccache/libexec ']'
++ dirname tools/build_pytorch_libs.sh
+ cd tools/..
+++ pwd
++ printf '%q\n' /Users/demanouwamo/Downloads/pytorch
+ PWD=/Users/demanouwamo/Downloads/pytorch
+ BASE_DIR=/Users/demanouwamo/Downloads/pytorch
+ TORCH_LIB_DIR=/Users/demanouwamo/Downloads/pytorch/torch/lib
+ INSTALL_DIR=/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install
+ THIRD_PARTY_DIR=/Users/demanouwamo/Downloads/pytorch/third_party
+ CMAKE_VERSION=cmake
+ C_FLAGS=' -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include"   -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/TH" -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THC"   -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THS" -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THCS"   -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THNN" -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THCUNN"'
+ C_FLAGS=' -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include"   -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/TH" -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THC"   -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THS" -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THCS"   -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THNN" -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ LDFLAGS='-L"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/lib" '
+ LD_POSTFIX=.so
++ uname
+ [[ Darwin == \D\a\r\w\i\n ]]
+ LDFLAGS='-L"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/lib"  -Wl,-rpath,@loader_path'
+ LD_POSTFIX=.dylib
+ CPP_FLAGS=' -std=c++11 '
+ GLOO_FLAGS=
+ THD_FLAGS=
+ NCCL_ROOT_DIR=/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install
+ [[ 1 -eq 1 ]]
+ GLOO_FLAGS='-DUSE_CUDA=1 -DNCCL_ROOT_DIR=/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install'
+ [[ 0 -eq 1 ]]
+ [[ 0 -eq 1 ]]
+ CWRAP_FILES='/Users/demanouwamo/Downloads/pytorch/torch/lib/ATen/Declarations.cwrap;/Users/demanouwamo/Downloads/pytorch/torch/lib/THNN/generic/THNN.h;/Users/demanouwamo/Downloads/pytorch/torch/lib/THCUNN/generic/THCUNN.h;/Users/demanouwamo/Downloads/pytorch/torch/lib/ATen/nn.yaml'
+ CUDA_NVCC_FLAGS=' -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include"   -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/TH" -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THC"   -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THS" -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THCS"   -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THNN" -I"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ [[ -z '' ]]
+ CUDA_DEVICE_DEBUG=0
+ '[' -z 4 ']'
+ BUILD_TYPE=Release
+ [[ -n '' ]]
+ [[ -n '' ]]
+ echo 'Building in Release mode'
Building in Release mode
+ mkdir -p torch/lib/tmp_install
+ for arg in '"$@"'
+ [[ caffe2 == \n\c\c\l ]]
+ [[ caffe2 == \g\l\o\o ]]
+ [[ caffe2 == \c\a\f\f\e\2 ]]
+ pushd /Users/demanouwamo/Downloads/pytorch
~/Downloads/pytorch ~/Downloads/pytorch
+ build_caffe2
+ [[ -z '' ]]
+ EXTRA_CAFFE2_CMAKE_FLAGS=()
+ [[ -n '' ]]
+ [[ -n /anaconda3/envs/ptc/lib/python3.6/site-packages ]]
+ EXTRA_CAFFE2_CMAKE_FLAGS+=("-DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH")
+ mkdir -p build
+ pushd build
~/Downloads/pytorch/build ~/Downloads/pytorch ~/Downloads/pytorch
+ cmake .. -DBUILDING_WITH_TORCH_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_CAFFE2=0 -DBUILD_ATEN=ON -DBUILD_PYTHON=0 -DBUILD_BINARY=OFF -DBUILD_SHARED_LIBS=ON -DONNX_NAMESPACE=onnx_torch -DUSE_CUDA=1 -DCAFFE2_STATIC_LINK_CUDA= -DUSE_ROCM=0 -DUSE_NNPACK=1 -DCUDNN_INCLUDE_DIR=/usr/local/cuda/include -DCUDNN_LIB_DIR=/usr/local/cuda/lib -DCUDNN_LIBRARY=/usr/local/cuda/lib/libcudnn.7.dylib -DUSE_MKLDNN=0 -DMKLDNN_INCLUDE_DIR= -DMKLDNN_LIB_DIR= -DMKLDNN_LIBRARY= -DCMAKE_INSTALL_PREFIX=/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_C_FLAGS= -DCMAKE_CXX_FLAGS= '-DCMAKE_EXE_LINKER_FLAGS=-L"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/lib"  -Wl,-rpath,@loader_path ' '-DCMAKE_SHARED_LINKER_FLAGS=-L"/Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install/lib"  -Wl,-rpath,@loader_path ' -DCMAKE_PREFIX_PATH=/anaconda3/envs/ptc/lib/python3.6/site-packages
-- CLANG_VERSION_STRING:         8.1
-- Need to define long as a separate typeid.
-- std::exception_ptr is supported.
-- NUMA is not available
-- Turning off deprecation warning due to glog.
-- Current compiler supports avx2 extention. Will build perfkernels.
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/Users/demanouwamo/Downloads/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- The BLAS backend of choice:MKL
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /anaconda3/envs/ptc/lib/libmkl_intel_lp64.dylib
--   Library mkl_intel_thread: /anaconda3/envs/ptc/lib/libmkl_intel_thread.dylib
--   Library mkl_core: /anaconda3/envs/ptc/lib/libmkl_core.dylib
--   Library iomp5: /anaconda3/envs/ptc/lib/libiomp5.dylib
--   Library pthread: /usr/lib/libpthread.dylib
--   Library m: /usr/lib/libm.dylib
-- Brace yourself, we are building NNPACK
-- Found system Eigen at /usr/local/include/eigen3
-- Could NOT find pybind11 (missing: pybind11_INCLUDE_DIR) 
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "7.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found cuDNN: v7.0.4  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib/libcudnn.7.dylib)
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX
-- Added CUDA NVCC flags for: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_70,code=compute_70
-- Could NOT find CUB (missing: CUB_INCLUDE_DIR) 
-- Found CUDA with FP16 support, compiling with torch.cuda.HalfTensor
-- Removing -DNDEBUG from compile flags
-- MAGMA not found. Compiling without MAGMA support
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- SSE2 Found
-- SSE3 Found
-- AVX Found
-- AVX2 Found
-- Atomics: using GCC intrinsics
-- Found a library with BLAS API (mkl).
-- Found a library with LAPACK API. (mkl)
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "5.5") 
-- Could NOT find MKLDNN (missing: MKLDNN_INCLUDE_DIR MKLDNN_LIBRARY) 
-- MKLDNN not found. Compiling without MKLDNN support
-- Using python found in /anaconda3/envs/ptc/bin/python
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Configuring build for SLEEF-v3.2
   Target system: Darwin-17.6.0
   Target processor: x86_64
   Host system: Darwin-17.6.0
   Host processor: x86_64
   Detected C compiler: AppleClang @ /Users/demanouwamo/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using option `-Wall -Wno-unused -Wno-attributes -Wno-unused-result -ffp-contract=off -fno-math-errno -fno-trapping-math` to compile libsleef
-- Building shared libs : OFF
-- MPFR : /usr/local/lib/libmpfr.dylib
-- MPFR header file in /usr/local/include
-- GMP : /usr/local/lib/libgmp.dylib
-- RUNNING_ON_TRAVIS : 0
-- COMPILER_SUPPORTS_OPENMP : 
CMake Warning at CMakeLists.txt:346 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.  Other settings may generate files that are not well
  tested.

-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.12.2
--   CMake command         : /anaconda3/envs/ptc/bin/cmake
--   Git version           : 
--   System                : Darwin
--   C++ compiler          : /Users/demanouwamo/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
--   C++ compiler version  : 8.1.0.8020042
--   BLAS                  : MKL
--   CXX flags             :   -msse4.1 -msse4.2   --std=c++11  -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DONNX_NAMESPACE=onnx_torch -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-aliasing -Wno-error=deprecated-declarations
--   Build type            : Release
--   Compile definitions   : USE_GCC_ATOMICS=1;TH_BLAS_MKL;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1
--   CMAKE_PREFIX_PATH     : /anaconda3/envs/ptc/lib/python3.6/site-packages
--   CMAKE_INSTALL_PREFIX  : /Users/demanouwamo/Downloads/pytorch/torch/lib/tmp_install
-- 
--   BUILD_CAFFE2          : 0
--   BUILD_ATEN            : ON
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_PYTHON          : 0
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : OFF
--   USE_ASAN              : OFF
--   USE_ATEN              : OFF
--   USE_CUDA              : 1
--     CUDA static link    : 
--     USE_CUDNN           : ON
--     CUDA version        : 9.0
--     cuDNN version       : 7.0.4
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/local/cuda/lib/libcuda.dylib
--     cudart library      : /usr/local/cuda/lib/libcudart_static.a;-Wl,-rpath,/usr/local/cuda/lib
--     cublas library      : /usr/local/cuda/lib/libcublas.dylib;/usr/local/cuda/lib/libcublas_device.a
--     cufft library       : /usr/local/cuda/lib/libcufft.dylib
--     curand library      : /usr/local/cuda/lib/libcurand.dylib
--     cuDNN library       : /usr/local/cuda/lib/libcudnn.7.dylib
--     nvrtc               : /usr/local/cuda/lib/libnvrtc.dylib
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /Users/demanouwamo/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : 
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_GLOO              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : 1
--   USE_OBSERVERS         : OFF
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : OFF
--   Public Dependencies  : /anaconda3/envs/ptc/lib/libmkl_intel_lp64.dylib;/anaconda3/envs/ptc/lib/libmkl_intel_thread.dylib;/anaconda3/envs/ptc/lib/libmkl_core.dylib;/anaconda3/envs/ptc/lib/libiomp5.dylib;/usr/lib/libpthread.dylib;/usr/lib/libm.dylib
--   Private Dependencies : nnpack;cpuinfo;onnxifi_loader
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/demanouwamo/Downloads/pytorch/build
+ make install -j4
[  1%] Built target js_embed
[  2%] Built target pthreadpool
[  6%] Built target libprotobuf-lite
[  8%] Built target cpuinfo
[  8%] Built target onnxifi_loader
[  9%] Built target common
[  9%] Built target mkrename
[ 20%] Built target libprotobuf
[ 21%] Built target mkdisp
[ 21%] Built target mkalias
[ 21%] Built target ATEN_CPU_FILES_GEN_TARGET
[ 21%] Built target ATEN_CUDA_FILES_GEN_TARGET
[ 21%] Built target mkmasked_gnuabi
[ 21%] Built target mkrename_gnuabi
[ 21%] Built target arraymap
[ 22%] Built target nnpack_reference_layers
[ 26%] Built target nnpack
[ 27%] Built target headers
[ 27%] Built target renamedsp256.h_generated
[ 27%] Built target dispavx.c_generated
[ 28%] Built target renameSSE2.h_generated
[ 28%] Built target renameAVX.h_generated
[ 28%] Built target renameFMA4.h_generated
[ 28%] Built target renameSSE4.h_generated
[ 28%] Built target renameAVX2128.h_generated
[ 41%] Built target libprotoc
[ 41%] Built target renameAVX2.h_generated
[ 41%] Built target dispsse.c_generated
[ 41%] Built target renamedsp128.h_generated
[ 41%] Built target renameAVX512F.h_generated
[ 41%] Generating alias_avx512f.h
[ 41%] Built target caffe2_protos
[ 41%] Built target protoc
[ 41%] Built target dispavx_obj
[ 41%] Built target alias_avx512f.h_generated
[ 41%] Built target sleefsse2
[ 41%] Built target sleefavx
[ 42%] Built target sleeffma4
[ 43%] Built target sleefsse4
[ 44%] Built target sleefavx2128
[ 44%] Built target sleefavx2
[ 45%] Built target dispsse_obj
[ 45%] Built target sleefavx512f
[ 45%] Built target gen_onnx_proto
[ 46%] Built target sleef
[ 47%] Built target onnx_proto
[ 51%] Built target onnx
[ 69%] Built target caffe2
[ 69%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCSleep.cu.o
[ 69%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCReduceApplyUtils.cu.o
[ 69%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCBlas.cu.o
[ 69%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCStorage.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_70'
nvcc fatal   : Unsupported gpu architecture 'compute_70'
CMake Error at caffe2_gpu_generated_THCSleep.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/demanouwamo/Downloads/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCSleep.cu.o

nvcc fatal   : Unsupported gpu architecture 'compute_70'
CMake Error at caffe2_gpu_generated_THCBlas.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/demanouwamo/Downloads/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCBlas.cu.o

CMake Error at caffe2_gpu_generated_THCReduceApplyUtils.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/demanouwamo/Downloads/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCReduceApplyUtils.cu.o

make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCSleep.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCBlas.cu.o] Error 1
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCReduceApplyUtils.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_70'
CMake Error at caffe2_gpu_generated_THCStorage.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/demanouwamo/Downloads/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCStorage.cu.o

make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCStorage.cu.o] Error 1
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack caffe2 nanopb libshm THD

Could you help me please.

**Comment by soumith** [comment]
@Danieldemanou please dont post duplicately. You posted here and in https://github.com/pytorch/pytorch/issues/3047#issuecomment-446773118

Closing this one.
