### ISSUE TITLE
Conv1d unexpected output on Linux CPU with a source build

### ISSUE THREAD

**Issue by lara-hdr** [pytorch/pytorch#15140]
## 🐛 Bug

Conv1 has unexpected results with a simple example on Linux CPU with a source build.

## To Reproduce

1. build pytorch : "python setup.py install" or "python setup.py build develop" 
2. Run the following code :

import torch
model = torch.nn.Conv1d(1, 2, 5, bias=False)
model._parameters['weight'] = torch.ones(2,1,5)
for i in range(5):
	model._parameters['weight'][1][0][i] = 2
input = torch.ones(2, 1, 15)
out = model(input)
print(out)

## Expected behavior

The input and kernel of conv1d are :
kernel :
   tensor([[[1., 1., 1., 1., 1.]],
   [[2., 2., 2., 2., 2.]]])

input :
   [tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
   [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])]

the expected output is :
   [tensor([[[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
   [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]],
   [[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
   [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]]])

the output is : 
   [tensor([[[7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
   [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]],
   [[8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
   [8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]]])]

## Environment

PyTorch version: 1.0.0a0+e8ba01a
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.15.4)
[pip] numpydoc (0.8.0)
[pip] torch (1.0.0a0+e8ba01a, /home/lahaidar/anaconda3/envs/test_clone/lib/python3.6/site-packages)
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] mkl-service               1.1.2                    py36_3  
[conda] mkl_fft                   1.0.10                   py36_0    conda-forge
[conda] mkl_random                1.0.2                    py36_0    conda-forge
[conda] mkldnn                    0.16.1                        0    mingfeima
[conda] torch                     1.0.0a0+e8ba01a           <pip>

## Additional context

I get the unexpected output when I run the code on Linux CPU with a build from source (I tested with torch version 1.0.0a0+c1f9b88 and 1.0.0a0+e8ba01a, and tried building with both mkl enabled and disabled and the results are similar). 
On GPU the problem does not occur and I get the expected output.
However, when I install using pip or conda, the output is the expected output on both CPU and GPU.

I did not have the problem on Windows either (even by building from sources).
 
Thanks

**Comment by soumith** [comment]
@lara-hdr could you do `conda uninstall -y mkldnn`, rebuild pytorch from source, and see if the issue persists?

**Comment by lara-hdr** [comment]
The issue persists after uninstalling mkldnn and rebuilding pytorch from source.

**Comment by ezyang** [comment]
guessing this got fixed in the meantime
