### ISSUE TITLE
ONNX Caffe2backend failed to exit gracefully under GPU mode on windows. it will trigger driver shutting down.

### ISSUE THREAD

**Issue by tiandunx** [pytorch/pytorch#15158]
## 🐛 Bug

When one uses Caffe2 onnx backend to load an onnx model which was converted from PyTorch on Windows GPU, it will complains driver shutting down after the program will end its task.
## To Reproduce
Code:
`import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx
import caffe2.python.onnx.backend as bk
h = 3
w = 3

class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()

    def forward(self, x):
        x = F.interpolate(x, (h + 1, w + 1), mode='nearest')
        return x

if __name__ == '__main__':
    torch_model = TestModel().cuda()
    dummy_input = torch.randn(1, 3, h, w).cuda()
    dummy_input_cpu = dummy_input.cpu().numpy()
    # print(dummy_input[0, 0])
    torch_model.eval()
    torch.onnx.export(torch_model, dummy_input, 'tmp_model.onnx', export_params=True, verbose=True)
    with torch.no_grad():
        torch_out = torch_model(dummy_input).cpu().numpy()
    print('Now the result infered by pytorch is :')
    print('*' * 50)
    print('pytorch result is ')
    print(torch_out[0, 0])
    print('-' * 50)
    onnx_model = onnx.load('tmp_model.onnx')
    onnx.checker.check_model(onnx_model)
    preprared_backend = bk.prepare(onnx_model, device='CUDA')

    c2_out = preprared_backend.run(dummy_input_cpu)[0]
    print('caffe2 result is ')
    print(c2_out[0, 0])
`

After the program executes print(c2_out[0, 0]), then the program will trigger a bug. 
F d:\vsproject\pytorch\caffe2\core\context_gpu.h:154] Check failed: error == cudaSuccess driver shutting down.
## Expected behavior
The program should exit gracefully.

## Environment

 - PyTorch Version (e.g., 1.0): Pytorch1.0
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.6.4
 - CUDA/cuDNN version: CUDA10, cuDNN7.3.1
 - GPU models and configuration: GTX1070
 - Any other relevant information:

## Additional context

@houseroad @zrphercule

**Comment by cristianPanaite** [comment]
Hello @tiandunx,

Unfortunately, I was not able to reproduce this error on the latest versions. Can you please provide some information regarding the steps that I should follow to reproduce it on current versions?

**Comment by cristianPanaite** [comment]
Hello @tiandunx,

Due to a long period of inactivity on this issue, we are going to close it.

If you think the error is still present on the latest versions, please open a new issue with details how to reproduce it.
