### ISSUE TITLE
Windows 1.0.0 binaries fail import caffe2

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#15156]
## 🐛 Bug

Reported by @m3rlin45

```
from caffe2.python import workspace
```

```
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.python import workspace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\m3rlin45\Documents\foo\env\lib\site-packages\caffe2\python\__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
ImportError: cannot import name 'caffe2_pb2'
```

## To Reproduce

Repro on a VM:

- Spin up fresh windows server 2016 VM on azure
- install python 3.6.7 from python.org
- disable path limit during install
- install virtualenv
- install vs15 redist to help virtualenv work
- set up a virtualenv and activated it
- install torch via instructions on pytorch.org, windows, python 3.6, no cuda
- open python
- run: `from caffe2.python import workspace`

**Comment by soumith** [comment]
cc: @peterjc123 to take a look

**Comment by peterjc123** [comment]
Looks like the build script https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.sh and https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.bat are not unified and we lost some source files in `caffe2/proto`. And this code path is not used in the windows tests, too.

**Comment by peterjc123** [comment]
We really should either get these script into CMake or write a Python script to unify them together in the long run.

**Comment by elnazsn1988** [comment]
I realise this has been closed but I am still getting the same error with Python 2.7 and windows 10, is there a way to fix it?

**Comment by peterjc123** [comment]
The problem is for the release binaries, which is unrelated to your question. Please don't add more replies here.
