### ISSUE TITLE
Why nobody fix no code hint in pycham?

### ISSUE THREAD

**Issue by leixd1994** [pytorch/pytorch#15151]
As i knew,the problem have proposed long long ago , from pytorch 0.3 to pytorch 1.0 . nobody fix  them ,i don`t know why , i transfer to tensorflow .

**Comment by driazati** [comment]
Try this fix from the forums https://discuss.pytorch.org/t/how-to-import-torch-in-pycharm/19356

**Comment by soumith** [comment]
the issue is still valid, and the linked thread in the comment is not a solution.

But this issue is also a duplicate, it's being tracked in https://github.com/pytorch/pytorch/issues/12128

**Comment by niushencheng** [comment]
> As i knew,the problem have proposed long long ago , from pytorch 0.3 to pytorch 1.0 . nobody fix them ,i don`t know why , i transfer to tensorflow .

辣鸡 pytorch, I transfer to tensorflow too
