### ISSUE TITLE
build error when using ninja to install pytorch

### ISSUE THREAD

**Issue by zxb1489479870** [pytorch/pytorch#15159]
## To Reproduce

1. export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" # [anaconda root directory]
1. conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
1. **pip install ninja**
1.  python setup install

## Expected behavior
There has an error when build:
+ ninja install -j112
ninja: error: build.ninja:25702: multiple rules generate caffe2/proto/caffe2_pb2.py [-w dupbuild=err]

Failed to run 'bash ../tools/build_pytorch_libs.sh --use-fbgemm --use-nnpack --use-mkldnn --use-qnnpack caffe2'

## Environment

 - PyTorch Version (latest):
 - Linux:
 - Installed PyTorch by source  code :
 - Build command you used (if compiling from source):
 - Python version: 3.6

## Other context about the problem 

It can be build failed when using ninja to install, but  build successful **without installing ninja** .

**Comment by zxb1489479870** [comment]
The ninja version is:
ninja: 1.8.2.post2

**Comment by zou3519** [comment]
https://github.com/pytorch/pytorch/pull/15230 should have fixed this
