### ISSUE TITLE
Building PyTorch on AArch64 doesn't find NEON hardware

### ISSUE THREAD

**Issue by mfuntowicz** [pytorch/pytorch#15162]
Hi everybody, 

In the process of giving a try to PyTorch on my RPi 3 b+, I tried compiling everything from scratch.

In the configure step, it seems that PyTorch finds out that the compiler supports NEON optimized instructions, but then I'm not quite sure about the real inclusion of NEON parameter in the compiler arguments : 

```bash
 Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- asimd/Neon found with compiler flag : -D__NEON__
-- Atomics: using GCC intrinsics
-- Found a library with LAPACK API. (generic)
```

Looking https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindARM.cmake and if I'm not mistaken (correct me otherwise) that FindARM relies exclusively on the information provided by `cat /proc/cpuinfo` to determine if this specific CPU does support NEON instructions.

In my case (**Fedora 29 AArch64 / 4.19.8 / Clang 7.0.0**) here is the output of ```cat /proc/cpuinfo```:
```
[mfuntowicz@pc-1165 ~]$ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
```

```
[mfuntowicz@pc-1165 ~]$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1200.0000
CPU min MHz:         600.0000
BogoMIPS:            38.40
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm crc32 cpuid
```

Thus, looking at the [specification for Cortex-A53](https://developer.arm.com/products/processors/cortex-a/cortex-a53), it should be able to get all the way NEON instrinsics:
```
NEON advanced SIMD
DSP & SIMD extensions
VFPv4 floating point
```

In that configuration, is NEON support correctly passed to the set of compiler arguments ? Or is the Cmake output misleading ? 

Thanks, 
Morgan

cc @malfet @seemethere @walterddr

**Comment by ezyang** [comment]
Hi Morgan, are you cross-compiling? I'm not 100% certain exactly how our cross-compiler support works, but yes, if you are cross-compiling, then it's incorrect for our cmake to be querying /proc/cpuinfo to figure out what capabilities are available. You should manually override the decision here (or, if no manual override is currently available, I'd be happy to review a PR adding such an override to unconditionally turn on NEON.)

**Comment by mfuntowicz** [comment]
Hi @ezyang, I'm compiling directly on the RPI3, so I would assume cmake to pick up the best available options.

I can try to have a look to submit a PR then :)

**Comment by mfuntowicz** [comment]
Hi @ezyang, I'll have some time to give it a try for what we discussed regarding NEON. Can you help me a little bit by pointing out an examples of an equivalent features already provided in PyTorch ? So that I can inspire from it :).

Thanks!

**Comment by ezyang** [comment]
We recently added official ARM support so I'm going to guess this got fixed. Please open new issue if not :)
