### ISSUE TITLE
Problem of torch.gesv on multi-GPUs 

### ISSUE THREAD

**Issue by noUmbrella** [pytorch/pytorch#15164]
Hi, I build a model which contains not only CNN for extracting features, but also a torch.gesv function to solve Ax=B. When I run train this model in single GPU(batch size is 20), the time consuming of torch.gesv is 100ms, however, when train this model in 4 GPUs(batch size is 80, each GPU solve 20 sampls), the time consuming of torch.gesv on each GPU is 300ms. This extremely slow down my training process. Why? Can you help me? Thank you!

**Comment by albanD** [comment]
This is a cross post from the forum [here](https://discuss.pytorch.org/t/problem-of-torch-gesv-on-multi-gpus/32038)
