### ISSUE TITLE
Please update the description of this method:torch.nn.MultiLabelSoftMarginLoss

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#15169]
Please update the description of this method:torch.nn.MultiLabelSoftMarginLoss
I can't understand this class: where i == 0 to x.nElement()-1, y[i] in {0,1}.?

**Comment by albanD** [comment]
Hi,

It means that the value of `i` in the sum above goes from `0` to `x.nElement()-1`.
And that the value `y[i]` is either `0` or `1` (meaning one hot encoding).

How would you update it to make it clearer?

**Comment by laizewei** [comment]
Thanks，now I understand this class.
