### ISSUE TITLE
Raise RuntimeError when performing torch.addmv

### ISSUE THREAD

**Issue by caogang** [pytorch/pytorch#1517]
torch.addmv raise RuntimeError when the matrix M is (1, N), vector V is (N). When calculating M*V using torch.addmv in cpu, it works. However, when calculating in gpu, it raise Runtime Error.

```python
alpha = 0
beta = 1
add_vector = torch.FloatTensor([2]).cuda()
matrix = torch.FloatTensor([2]).cuda()
matrix = matrix.expand(1, 64)
vector = torch.ones(64).cuda()
output = add_vector.new().resize_as_(add_vector)
torch.addmv(alpha, add_vector, beta,
            matrix, vector, out=output)
```

It will raise an error

```python
RuntimeErrorTraceback (most recent call last)
<ipython-input-108-b652d675e3d9> in <module>()
      7 output = add_vector.new().resize_as_(add_vector)
      8 torch.addmv(alpha, add_vector, beta,
----> 9             matrix, vector, out=output)

RuntimeError: Cublas_Sgemv only supports m, n, lda, incx, incyin the range 0 < [val] <= 2147483647 at /home/users/gang.cao/download/pytorch/torch/lib/THC/THCBlas.cu:109
```

When I use cpu tensor or make the matrix M is (t, N)[t > 1], the addmv is worked. I think this maybe a bug in some way.

**Comment by caogang** [comment]
Fixed in #1506

**Comment by caogang** [comment]
Sorry, this bug still exist.

**Comment by colesbury** [comment]
The issue is that `matrix` has stride `(1, 0)` so `lda` is 0, which is not supported by BLAS or cuBLAS. On the CPU side, we have a fallback to a naive for-loop based matrix-vector multiplication, but we don't have that for CUDA.

Making the matrix contiguous fixes the error, but expands the matrix in memory.

**Comment by apaszke** [comment]
Should we add `newContiguous` for BLAS ops in THC?

**Comment by fmassa** [comment]
I don't think so, because BLAS usually supports both rowMajor and columMajor data internally.
We could make contiguous only if specific cases (zero stride), like it's done in [`addmm`](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/generic/THCTensorMathBlas.cu#L267-L275)

**Comment by zou3519** [comment]
This appears to be fixed, but I'm not sure how it was fixed. 

Running the offending code in question doesn't produce a crash on master, and it looks like `matrix` is indeed made contiguous in the [`THCTensor_(addmv)` code](https://github.com/pytorch/pytorch/blame/master/torch/lib/THC/generic/THCTensorMathBlas.cu#L97)
