### ISSUE TITLE
Wrong link on pytorch.org

### ISSUE THREAD

**Issue by kentsyx** [pytorch/pytorch#1518]
Install on Linux through pip (python 2.7) the link for without cuda support
http://download.pytorch.org/whl/cu75/torch-0.1.12.post2-cp27-none-linux_x86_64.whl 
is the same as with cuda-7.5
http://download.pytorch.org/whl/cu75/torch-0.1.12.post2-cp27-none-linux_x86_64.whl 
which will throw an error if you want to install without cuda support.

**Comment by soumith** [comment]
no, our binaries support everything (CUDA, no CUDA). Hence the same link.
