### ISSUE TITLE
reduction in CrossEntropyLoss 

### ISSUE THREAD

**Issue by zontakm** [pytorch/pytorch#15186]
## 📚 Documentation

Based on https://pytorch.org/docs/stable/nn.html  in CrossEntropyLoss reduce and size_average are deprecated. Currently with pytorch 0.4.1 with python 2.7.6, I can still use those, but get a suggestion to switch to reduction. Based on the above documentation I can specify reduction='mean'
However, in that case I am getting - 
ValueError: mean is not a valid value for reduction
In my case, 'elementwise_mean' works 
Thus there is an inconsistency in the documentation.

**Comment by driazati** [comment]
Those docs are accurate for 1.0.0, can you try that version?

If not, the docs for 0.4.1 can be found here: https://pytorch.org/docs/0.4.1/nn.html
