### ISSUE TITLE
Update producer_version in ONNX export to PyTorch 1.0?

### ISSUE THREAD

**Issue by spandantiwari** [pytorch/pytorch#15192]
In ONNX models exported from PyTorch master today, the `producer_version` version shows up as PyTorch 0.4. Would it make sense to update the `producer_version` to PyTorch 1.0?

**Comment by tiandunx** [comment]
Same here

**Comment by spandantiwari** [comment]
There's a PR for bumping this up now. https://github.com/pytorch/pytorch/pull/17410

**Comment by spandantiwari** [comment]
Closing this issue because https://github.com/pytorch/pytorch/pull/17410 PR is merging.
