### ISSUE TITLE
System memory increases when calling model.cuda() method

### ISSUE THREAD

**Issue by pluiez** [pytorch/pytorch#15209]
### Please note that this issue tracker is not a help form and this issue will be closed.

I inspect my PyTorch code where system memory usage gradually increases from about 3.9GB to nearly 40GB during training of 4 days. Thus I use memory_profiler to inspect my code to find out which part is to blame.

Below is the code snippet I use.

```python
import torch, torch.nn as nn
import memory_profiler

@memory_profiler.profile

def main():
    model = nn.GRU(1000, 1000)
    x = torch.randn(10, 10, 1000)
    h = torch.randn(1, 10, 1000)
    model = model.cuda()
    x = x.cuda()
    h = h.cuda()
    model(x, h)

if __name__ == '__main__':
    main()
```

And here is the memory usage information:

```
Filename: test.py

Line #  Mem usage    Increment   Line Contents
================================================
     5    148.1 MiB    148.1 MiB   @memory_profiler.profile
     6                             def main():
     7    172.1 MiB     24.0 MiB       model = nn.GRU(1000, 1000)
     8    172.7 MiB      0.6 MiB       x = torch.randn(10, 10, 1000)
     9    172.7 MiB      0.0 MiB       h = torch.randn(1, 10, 1000)
    10                             
    11   2145.6 MiB   1972.9 MiB       model = model.cuda()
    12   2145.6 MiB      0.0 MiB       x = x.cuda()
    13   2145.6 MiB      0.0 MiB       h = h.cuda()
    14                             
    15   2145.6 MiB      0.0 MiB       model(x, h)

```

As we can see that the initialized model is only of size 24.0MB, however, the 11th line `model.cuda()` shows the memory usage incredibly grows to 1972.9 MB when moving(or copying?) model from CPU to GPU incredibly. But this is not observed in the case of Tensor.cuda() as indicated by 12/13th lines.

Although this doesn't look like the reason that leads to my problem, I couldn't figure out the reason why Module.cuda() increases memory usage so much more than its CPU counterpart. 

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by Arctanxy** [comment]
Did you find the reason?

**Comment by wangwang110** [comment]
Did you find the reason?

**Comment by whria78** [comment]
I heard it is a fixed overhead of the CUDA library. https://discuss.pytorch.org/t/moving-a-tiny-model-to-cuda-causes-a-2gb-host-memory-allocation/61282/2
