### ISSUE TITLE
Installation from source failure on Windows 10 with "The system cannot find the batch label specified - build_caffe2"

### ISSUE THREAD

**Issue by kyeongsoo** [pytorch/pytorch#15207]
## 🐛 Bug

Whenever I run "python setup.py build", it ends up due to the following critical error:

---> snip <----
The system cannot find the batch label specified - build_caffe2
---> snip <----

## To Reproduce

1. git pull && git submodule update --recursive (* as of today: commit 78bf1a906586e137132325a0f39799fdecf219b5 *)
1. python build setup.py clean
1. python build setup.py build

Below are the full error messages:
======================
Building wheel torch-1.0.0a0+78bf1a9
running build
running build_deps

CLINK C:\Users\kks\git\pytorch>cd "C:\Users\kks\git\pytorch\tools\\.." 

CLINK C:\Users\kks\git\pytorch>set PATH=\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;C:\Tools\ConEmu\ConEmu\Scripts;C:\Tools\gnuwin32\bin;C:\Tools\ConEmu;C:\Tools\ConEmu\ConEmu;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Tools\Bin;C:\Users\kks\Bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\dotnet\;C:\Program Files (x86)\AOMEI Backupper;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Tools\Git\cmd;C:\Users\kks\AppData\Local\Microsoft\WindowsApps;C:\texlive\2018\bin\win32;C:\Tools\svn;C:\Program Files\PuTTY;C:\Tools\Git\bin;C:\Tools\Git\mingw64\bin;C:\Tools\Anaconda3;C:\Tools\Anaconda3\Scripts;C:\Tools\Anaconda3\Library\bin;C:\Tools\Julia-1.0.0\bin;C:\Go\bin;C:\Tools\nodejs\;C:\Users\kks\AppData\Roaming\npm;C:\Program Files\gs\gs9.22\bin;C:\Program Files\gs\gs9.22\lib;C:\Program Files\Artifex Software\gsview6.0\bin;C:\Tools\Bin\DeltaCopy;C:\Tools\PDFtk\bin;C:\Tools\ffmpeg\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Tools\cuda\bin;C:\Tools\MongoDB\bin;C:\Program Files\MATLAB\R2017b\bin;C:\Tools\GnuPG\bin;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja 

CLINK C:\Users\kks\git\pytorch>set BASE_DIR=C:/Users/kks/git/pytorch 

CLINK C:\Users\kks\git\pytorch>set TORCH_LIB_DIR=C:/Users/kks/git/pytorch/torch/lib 

CLINK C:\Users\kks\git\pytorch>set THIRD_PARTY_DIR=C:/Users/kks/git/pytorch/third_party 

CLINK C:\Users\kks\git\pytorch>set BASIC_C_FLAGS= 

CLINK C:\Users\kks\git\pytorch>set BASIC_CUDA_FLAGS= 

CLINK C:\Users\kks\git\pytorch>IF NOT DEFINED INSTALL_DIR (set "INSTALL_DIR=C:/Users/kks/git/pytorch/torch/lib/tmp_install" )  ELSE (set "INSTALL_DIR=\=/" ) 

CLINK C:\Users\kks\git\pytorch>set LDFLAGS=/LIBPATH:C:/Users/kks/git/pytorch/torch/lib/tmp_install/lib 

CLINK C:\Users\kks\git\pytorch>set C_FLAGS= /D_WIN32 /Z7 /EHa /DNOMINMAX 

CLINK C:\Users\kks\git\pytorch>set LINK_FLAGS=/DEBUG:FULL 

CLINK C:\Users\kks\git\pytorch>if not exist torch\lib\tmp_install mkdir torch\lib\tmp_install 

CLINK C:\Users\kks\git\pytorch>set /a USE_CUDA=0 

CLINK C:\Users\kks\git\pytorch>set /a USE_FBGEMM=1 

CLINK C:\Users\kks\git\pytorch>set /a USE_ROCM=0 

CLINK C:\Users\kks\git\pytorch>set /a USE_NNPACK=0 

CLINK C:\Users\kks\git\pytorch>set /a USE_QNNPACK=0 

CLINK C:\Users\kks\git\pytorch>set /a USE_GLOO_IBVERBS=0 

CLINK C:\Users\kks\git\pytorch>set /a USE_MKLDNN=0 

CLINK C:\Users\kks\git\pytorch>set _BUILD_ARGS= 

CLINK C:\Users\kks\git\pytorch>if "--use-cuda" == "" (goto :process_args_exit ) 

CLINK C:\Users\kks\git\pytorch>if "--use-cuda" == "--use-cuda" (
set /a USE_CUDA=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>shift

CLINK C:\Users\kks\git\pytorch>goto :process_args 

CLINK C:\Users\kks\git\pytorch>if "--use-fbgemm" == "" (goto :process_args_exit ) 

CLINK C:\Users\kks\git\pytorch>if "--use-fbgemm" == "--use-cuda" (
set /a USE_CUDA=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-fbgemm" == "--use-fbgemm" (
set /a USE_FBGEMM=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>shift

CLINK C:\Users\kks\git\pytorch>goto :process_args 

CLINK C:\Users\kks\git\pytorch>if "--use-nnpack" == "" (goto :process_args_exit ) 

CLINK C:\Users\kks\git\pytorch>if "--use-nnpack" == "--use-cuda" (
set /a USE_CUDA=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-nnpack" == "--use-fbgemm" (
set /a USE_FBGEMM=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-nnpack" == "--use-rocm" (
set /a USE_ROCM=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-nnpack" == "--use-nnpack" (
set /a USE_NNPACK=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>shift

CLINK C:\Users\kks\git\pytorch>goto :process_args 

CLINK C:\Users\kks\git\pytorch>if "--use-mkldnn" == "" (goto :process_args_exit ) 

CLINK C:\Users\kks\git\pytorch>if "--use-mkldnn" == "--use-cuda" (
set /a USE_CUDA=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-mkldnn" == "--use-fbgemm" (
set /a USE_FBGEMM=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-mkldnn" == "--use-rocm" (
set /a USE_ROCM=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-mkldnn" == "--use-nnpack" (
set /a USE_NNPACK=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-mkldnn" == "--use-qnnpack" (
set /a USE_QNNPACK=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-mkldnn" == "--use-mkldnn" (
set /a USE_MKLDNN=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>shift

CLINK C:\Users\kks\git\pytorch>goto :process_args 

CLINK C:\Users\kks\git\pytorch>if "--use-qnnpack" == "" (goto :process_args_exit ) 

CLINK C:\Users\kks\git\pytorch>if "--use-qnnpack" == "--use-cuda" (
set /a USE_CUDA=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-qnnpack" == "--use-fbgemm" (
set /a USE_FBGEMM=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-qnnpack" == "--use-rocm" (
set /a USE_ROCM=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-qnnpack" == "--use-nnpack" (
set /a USE_NNPACK=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "--use-qnnpack" == "--use-qnnpack" (
set /a USE_QNNPACK=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>shift

CLINK C:\Users\kks\git\pytorch>goto :process_args 

CLINK C:\Users\kks\git\pytorch>if "caffe2" == "" (goto :process_args_exit ) 

CLINK C:\Users\kks\git\pytorch>if "caffe2" == "--use-cuda" (
set /a USE_CUDA=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "caffe2" == "--use-fbgemm" (
set /a USE_FBGEMM=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "caffe2" == "--use-rocm" (
set /a USE_ROCM=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "caffe2" == "--use-nnpack" (
set /a USE_NNPACK=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "caffe2" == "--use-qnnpack" (
set /a USE_QNNPACK=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "caffe2" == "--use-mkldnn" (
set /a USE_MKLDNN=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>if "caffe2" == "--use-gloo-ibverbs" (
echo Warning: gloo iverbs is enabled but build is not yet implemented  1>&2  
 set /a USE_GLOO_IBVERBS=1  
 goto :process_args_processed 
) 

CLINK C:\Users\kks\git\pytorch>set _BUILD_ARGS= caffe2 

CLINK C:\Users\kks\git\pytorch>shift

CLINK C:\Users\kks\git\pytorch>goto :process_args 

CLINK C:\Users\kks\git\pytorch>if "" == "" (goto :process_args_exit ) 

CLINK C:\Users\kks\git\pytorch>set BUILD_TYPE=Release 

CLINK C:\Users\kks\git\pytorch>IF "" == "1" (set BUILD_TYPE=Debug ) 

CLINK C:\Users\kks\git\pytorch>IF "" == "1" (set BUILD_TYPE=RelWithDebInfo ) 

CLINK C:\Users\kks\git\pytorch>IF NOT DEFINED MAX_JOBS (set /a MAX_JOBS=40 - 1 ) 

CLINK C:\Users\kks\git\pytorch>IF NOT DEFINED BUILD_SHARED_LIBS (set BUILD_SHARED_LIBS=ON ) 

CLINK C:\Users\kks\git\pytorch>IF "Visual Studio 15 2017 Win64" == "" (
set CMAKE_GENERATOR_COMMAND=  
 set MAKE_COMMAND=msbuild INSTALL.vcxproj /p:Configuration=Release 
)  ELSE (
set CMAKE_GENERATOR_COMMAND=-G "Visual Studio 15 2017 Win64"  
 IF "Visual Studio 15 2017 Win64" == "Ninja" (
IF "" == "" set CC=cl.exe  
 IF "" == "" set CXX=cl.exe  
 set MAKE_COMMAND=cmake --build . --target install --config Release -- -j39 
)  ELSE (set MAKE_COMMAND=msbuild INSTALL.vcxproj /p:Configuration=Release ) 
) 

CLINK C:\Users\kks\git\pytorch>FOR %a IN (caffe2) DO (
echo --------------------------------------------------------------------------------  
 echo |  
 echo |  Building %a  
 echo |  
 echo --------------------------------------------------------------------------------  
 IF "%a" == "caffe2" (call:build_caffe2 %a )  ELSE (IF "%a" == "libshm_windows" (
SET IS_OURS=1  
 pushd torch\lib  
 call:build %a  
 popd
)  ELSE (
pushd third_party  
 call:build %a  
 popd
) ) 
) 

CLINK C:\Users\kks\git\pytorch>(
echo --------------------------------------------------------------------------------  
 echo |  
 echo |  Building caffe2  
 echo |  
 echo --------------------------------------------------------------------------------  
 IF "caffe2" == "caffe2" (call:build_caffe2 caffe2 )  ELSE (IF "caffe2" == "libshm_windows" (
SET IS_OURS=1  
 pushd torch\lib  
 call:build caffe2  
 popd
)  ELSE (
pushd third_party  
 call:build caffe2  
 popd
) ) 
) 
--------------------------------------------------------------------------------
|
|  Building caffe2
|
--------------------------------------------------------------------------------

CLINK C:\Users\kks\git\pytorch>if not "C:/Program Files/NVIDIA Corporation/NvToolsExt/" == "" set NVTOOLEXT_HOME=C:/Program Files/NVIDIA Corporation/NvToolsExt/ 

CLINK C:\Users\kks\git\pytorch>if not "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0\include" == "" set CUDNN_INCLUDE_DIR=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include 

CLINK C:\Users\kks\git\pytorch>if not "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0\lib/x64" == "" set CUDNN_LIB_DIR=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64 

CLINK C:\Users\kks\git\pytorch>if not "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0\lib/x64\cudnn.lib" == "" set CUDNN_LIBRARY=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib 

CLINK C:\Users\kks\git\pytorch>if not "C:\Tools\Anaconda3/libs/python36.lib" == "" set PYTORCH_PYTHON_LIBRARY=C:/Tools/Anaconda3/libs/python36.lib 

CLINK C:\Users\kks\git\pytorch>if not "C:\Tools\Anaconda3\lib\site-packages\numpy\core\include" == "" set NUMPY_INCLUDE_DIR=C:/Tools/Anaconda3/lib/site-packages/numpy/core/include 

CLINK C:\Users\kks\git\pytorch>IF NOT "" == "" call ""  

CLINK C:\Users\kks\git\pytorch>if not exist build mkdir build 

CLINK C:\Users\kks\git\pytorch>pushd build 

CLINK C:\Users\kks\git\pytorch\build>cmake .. -G "Visual Studio 15 2017 Win64"                   -DCMAKE_BUILD_TYPE=Release                   -DTORCH_BUILD_VERSION="1.0.0a0+78bf1a9"                   -DPYTHON_LIBRARY="C:/Tools/Anaconda3/libs/python36.lib"                   -DBUILD_TORCH="ON"                   -DNVTOOLEXT_HOME="C:/Program Files/NVIDIA Corporation/NvToolsExt/"                   -DBUILD_SHARED_LIBS="ON"                   -DBUILD_PYTHON=ON                   -DBUILD_BINARY=OFF                   -DBUILD_TEST=ON                   -DINSTALL_TEST=ON                   -DBUILD_CAFFE2_OPS=ON                   -DONNX_NAMESPACE=onnx_torch                   -DUSE_CUDA=1                   -DUSE_DISTRIBUTED=OFF                   -DUSE_FBGEMM=1                   -DUSE_NUMPY=                   -DNUMPY_INCLUDE_DIR="C:/Tools/Anaconda3/lib/site-packages/numpy/core/include"                   -DUSE_NNPACK=1                   -DUSE_LEVELDB=OFF                   -DUSE_LMDB=OFF                   -DUSE_OPENCV=OFF                   -DUSE_QNNPACK=1                   -DUSE_FFMPEG=OFF                   -DUSE_GLOG=OFF                   -DUSE_GFLAGS=OFF                   -DUSE_SYSTEM_EIGEN_INSTALL=OFF                   -DCUDNN_INCLUDE_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include"                   -DCUDNN_LIB_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64"                   -DCUDNN_LIBRARY="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib"                   -DUSE_MKLDNN=1                   -DATEN_NO_CONTRIB=1                   -DCMAKE_INSTALL_PREFIX="C:/Users/kks/git/pytorch/torch/lib/tmp_install"                   -DCMAKE_C_FLAGS=""                   -DCMAKE_CXX_FLAGS="/EHa "                   -DCMAKE_EXE_LINKER_FLAGS=""                   -DCMAKE_SHARED_LINKER_FLAGS=""                   -DUSE_ROCM=0 
The system cannot find the batch label specified - build_caffe2

CLINK C:\Users\kks\git\pytorch>cd torch\lib 

CLINK C:\Users\kks\git\pytorch\torch\lib>copy /Y "C:/Users/kks/git/pytorch/torch/lib/tmp_install\lib\*" . 
The system cannot find the path specified.

CLINK C:\Users\kks\git\pytorch\torch\lib>IF EXIST "C:/Users/kks/git/pytorch/torch/lib/tmp_install\bin" (copy /Y "C:/Users/kks/git/pytorch/torch/lib/tmp_install\bin\*" . ) 

CLINK C:\Users\kks\git\pytorch\torch\lib>xcopy /Y /E "C:/Users/kks/git/pytorch/torch/lib/tmp_install\include\*.*" include\*.* 
File not found - *.*
0 File(s) copied

CLINK C:\Users\kks\git\pytorch\torch\lib>xcopy /Y ..\..\aten\src\THNN\generic\THNN.h  . 
..\..\aten\src\THNN\generic\THNN.h
1 File(s) copied

CLINK C:\Users\kks\git\pytorch\torch\lib>xcopy /Y ..\..\aten\src\THCUNN\generic\THCUNN.h . 
..\..\aten\src\THCUNN\generic\THCUNN.h
1 File(s) copied

CLINK C:\Users\kks\git\pytorch\torch\lib>cd ..\.. 

CLINK C:\Users\kks\git\pytorch>goto:eof
setup.py::build_deps::run()
error: cannot copy tree 'torch/lib/tmp_install/share': not a directory

## Expected behavior

PyTorch should be installed without any issues.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): lastest version: commit 78bf1a906586e137132325a0f39799fdecf219b5 (also tested with v1.0.0)
 - OS (e.g., Linux): Windows 10 Pro Version 1803 (OS Build 17134.471)
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py build (or install)
 - Python version: Python 3.6.7 :: Anaconda custom (64-bit)
 - CUDA/cuDNN version:  CUDA V9.0.176 / cuDNN MAJOR 7-MINOR 4-PATCHLEVEL 1
 - GPU models and configuration:  Quadro K4200 with Driver Version: 411.81
 - Any other relevant information: Microsoft Visual Studio 2017 Community Edition

**Comment by peterjc123** [comment]
Maybe this post is [helpful](https://stackoverflow.com/questions/232651/why-the-system-cannot-find-the-batch-label-specified-is-thrown-even-if-label-e).

**Comment by peterjc123** [comment]
@kyeongsoo Then what about changing the name of the section? Replace `build_caffe2` in that file with `bc` or something else.

**Comment by kyeongsoo** [comment]
> @kyeongsoo Then what about changing the name of the section? Replace `build_caffe2` in that file with `bc` or something else.

Thanks for your further suggestion, and at the same time, very sorry for the late response.

Per your advice, I replaced the said label with `bc` and try the build again. The results, however, are the same. Below are the excerpts from the build messages:
---> snip <---
C:\Users\kks\git\pytorch\build>cmake .. -G "Visual Studio 15 2017 Win64"                   -DCMAKE_BUILD_TYPE=Release                   -DTORCH_BUILD_VERSION="1.0.0a0+656b565"                   -DPYTHON_LIBRARY="C:/Tools/Anaconda3/libs/python36.lib"                   -DBUILD_TORCH="ON"                   -DNVTOOLEXT_HOME="C:/Program Files/NVIDIA Corporation/NvToolsExt/"                   -DBUILD_SHARED_LIBS="ON"                   -DBUILD_PYTHON=ON                   -DBUILD_BINARY=OFF                   -DBUILD_TEST=ON                   -DINSTALL_TEST=ON                   -DBUILD_CAFFE2_OPS=ON                   -DONNX_NAMESPACE=onnx_torch                   -DUSE_CUDA=1                   -DUSE_DISTRIBUTED=OFF
                -DUSE_FBGEMM=1                   -DUSE_NUMPY=                   -DNUMPY_INCLUDE_DIR="C:/Tools/Anaconda3/lib/site-packages/numpy/core/include"                   -DUSE_NNPACK=1                   -DUSE_LEVELDB=OFF
      -DUSE_LMDB=OFF                   -DUSE_OPENCV=OFF                   -DUSE_QNNPACK=1                   -DUSE_FFMPEG=OFF                   -DUSE_GLOG=OFF                   -DUSE_GFLAGS=OFF                   -DUSE_SYSTEM_EIGEN_INSTALL=OFF                   -DCUDNN_INCLUDE_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include"                   -DCUDNN_LIB_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64"                   -DCUDNN_LIBRARY="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib"                   -DUSE_MKLDNN=1                   -DATEN_NO_CONTRIB=1                   -DCMAKE_INSTALL_PREFIX="C:/Users/kks/git/pytorch/torch/lib/tmp_install"
                  -DCMAKE_C_FLAGS=""                   -DCMAKE_CXX_FLAGS="/EHa "                   -DCMAKE_EXE_LINKER_FLAGS=""                   -DCMAKE_SHARED_LINKER_FLAGS=""                   -DUSE_ROCM=0
The system cannot find the batch label specified - bc
---> snip <---

**Comment by peterjc123** [comment]
@kyeongsoo Sorry, I have no idea then. Because I have never faced this problem before. I will be grateful if you could reproduce it in a virtual machine (VMware, VirtualBox) and send the image to me.

**Comment by cristianPanaite** [comment]
Hello @kyeongsoo,

I tried to replicate this error, but unfortunately I could not. I think this problem is solved with the latest versions.

My environment:

PyTorch version: 1.12.0+cu116   
CUDA used to build PyTorch: 11.6
OS: Microsoft Windows 11 Enterprise
CMake version: version 3.24.1
Python version: 3.10.8
Python platform: Windows-10-10.0.22621-SP0
CUDA runtime version: 11.8.89

![image](https://user-images.githubusercontent.com/57230852/196931596-5967f4ac-fb37-4e5a-aa30-74469633dbd3.png)

You can try this options and if you still encounter this error, please open a new issue with details on how to reproduce it on the latest version.

**Comment by cristianPanaite** [comment]
Hello @kyeongsoo,

I tried to replicate this error, but unfortunately I could not. I think this problem is solved with the latest versions.

My environment:

PyTorch version: 1.12.0+cu116   
CUDA used to build PyTorch: 11.6
OS: Microsoft Windows 11 Enterprise
CMake version: version 3.24.1
Python version: 3.10.8
CUDA runtime version: 11.8.89

![image](https://user-images.githubusercontent.com/57230852/196931596-5967f4ac-fb37-4e5a-aa30-74469633dbd3.png)

You can try this options and if you still encounter this error, please open a new issue with details on how to reproduce it on the latest version.
