### ISSUE TITLE
MultiLabelSoftMarginLoss computational formula

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#15205]
MultiLabelSoftMarginLoss
If(reduce=True)
 {   n=input.size(0)
     for i=,0 to input.size(0){
        for j=,0 to input.size(1){
       sum=sum-(target[i][j]*log(pow(1+exp(-input[i][j]),-1))+(1-target[i][j])*log(exp(-input[i][j])/(1+exp(-input[i][j]))))/input.size(0)
       } 
    }
   if(size_average=True){
    ret.add(sum/(input.size(0)*input.size(0)))
  }
 else{
  ret.add(sum/input.size(0))
}
}
-------------------------------------------------------------------- 
questions: 
I'm trying to recover the formula and I find a question.
ret.add(sum/(input.size(0)*input.size(0)))    
Why divide by input.size(0) twice.
Is it correct?
----------------------------------
import torch 
import torch.nn.functional as F
a=[[1.,2.,3.,4.],[1.,2.,3.,4.]]
b=[[1.,1.,1.,1.],[2.,1.,1.,1.]]
input=torch.tensor(a,requires_grad=True)
print(input.size())
target = torch.tensor(b)
output = F.multilabel_soft_margin_loss(input,target,reduce=True,size_average=True)
print(output)
----------------------
tensor(0.0017, grad_fn=<MeanBackward1>)

**Comment by driazati** [comment]
If you're looking for the formula you can find it in the code here

https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L2222
