### ISSUE TITLE
torch::jit::script::Module not thread-safe

### ISSUE THREAD

**Issue by SPark9625** [pytorch/pytorch#15210]
## 🐛 Bug

I need to run `torch::jit::script::Module::forward()` in a multithreaded environment. Each thread must run `forward()` independent of each other.

When I have a single `torch::jit::script::Module` instance and call `forward()` from multiple threads at the same time, it throws an error which I guess is because `forward()` is not thread safe. So I tried creating multiple instances of `torch::jit::script::Module`, assign one to each thread, and then call the respective `forward()`.

Here is an MVCE that I've come up with:

    #include <string>
    #include <memory>
    #include <iostream>
    #include <thread>
    #include <vector>
    #include <torch/script.h>

    void foo(const std::vector<std::shared_ptr<torch::jit::script::Module>>& modules, int idx)
    {
        for (int i = 0; i < 10; i++) {
            torch::Tensor X = torch::rand({2,51,13,13});
            auto out = modules[idx]->forward({X}).toTuple()->elements();
        }
    }

    int main() {

        std::string model_path = "path/to/your/model";
        
        std::vector<std::shared_ptr<torch::jit::script::Module>> modules;
        for (int i = 0; i < 10; i++){
            modules.push_back(torch::jit::load(model_path));
        }

        std::cout << "Module loaded. So far so good" << std::endl;

        std::vector<std::thread> vec;
        for (int i = 0; i < 10; i++) {
            std::thread t(foo, std::ref(modules), i);
            vec.push_back(std::move(t));
        }
        
        for (auto& t: vec)
            t.join();

        return 0;
    }

This results in
```
Module loaded. So far so good
Segmentation fault: 11
```

Is this intended? If so, is sequential run (or batching) the only solution?

## Environment

PyTorch version: 1.0.0a0+db5d313
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.1
GCC version: Could not collect
CMake version: version 3.12.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by zdevito** [comment]
Module's `foward` method should be thread safe, but it seems like there is a bug somewhere. Can you share what model is being loaded, so that we can debug the crash?

**Comment by suo** [comment]
Going to close this out as we don't have a repro to move forward with. @SPark9625, if you (or anyone else) continue to have this problem, please reopen and comment with a repro.

**Comment by hhbyyh** [comment]
Thanks @SPark9625 for creating the issue.
I can still see the issue in Pytorch 1.0.1

```
#include "torch/torch.h"
#include "torch/script.h"
#include <iostream>
#include <thread>

using namespace std;

void run() {
  torch::set_num_threads(1);
  std::shared_ptr<torch::jit::script::Module> module = torch::jit::load("/pts/resNet18.pt");
  std::cout << "model loaded" << std::endl;
  assert(module != nullptr);

  std::cout << "forwarding" << std::endl;

  std::vector<torch::jit::IValue> inputs;
  inputs.push_back(torch::ones({4, 3, 224, 224}));
		
  at::Tensor output = module->forward(inputs).toTensor();
  std::cout << output.slice(/*dim=*/1, /*start=*/0, /*end=*/5) << '\n';
  std::cout << "forward end " << std::endl; 
}


int main() {
  std::cout << "started" << std::endl;

  for (uint8_t i = 0; i < 4; i++)
    {
        thread t(run);
        t.detach(); 
    }
 
  getchar();
  std::cout << "main exit" << std::endl;
}
```

error info:
`Segmentation fault (core dumped)`


PyTorch version: 1.0.1
Is debug build: No
CUDA used to build PyTorch: None

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

libtorch 1.0.1

**Comment by yjhjstz** [comment]
```c++
#include <string>
#include <memory>
#include <iostream>
#include <thread>
#include <vector>
#include <torch/script.h>

void foo(const std::vector<std::shared_ptr<torch::jit::script::Module>>& modules, int idx)
{
        torch::Tensor X = torch::rand({1, 3, 224, 224});
        auto out = modules[idx]->forward({X};
}


int main() {

    std::string model_path = "model.pt";

    std::vector<std::shared_ptr<torch::jit::script::Module>> modules;
    for (int i = 0; i < 10; i++){
        modules.push_back(torch::jit::load(model_path));
    }

    std::cout << "Module loaded. So far so good" << std::endl;

    std::vector<std::thread> vec;
    for (int i = 0; i < 10; i++) {
        std::thread t(foo, std::ref(modules), i);
        vec.push_back(std::move(t));
    }

    for (auto& t: vec)
        t.join();

    return 0;
}
```

this would be ok , because forward may return Tensor or Tuple , we can replace like :
```c++
if (v.isTensor()) {
          at::Tensor output = v.toTensor();
          outputs->push_back(output.to(at::kCPU));
 } else if (v.isTuple()) {
          for(size_t i = 0; i < v.toTuple()->elements().size(); ++i) {
              auto output = v.toTuple()->elements()[i].toTensor();
              outputs->push_back(output.to(at::kCPU));
         }  
} else {
      }
```
