### ISSUE TITLE
how to realize  "torch.Concat"  in parallel？

### ISSUE THREAD

**Issue by zira-wang** [pytorch/pytorch#15211]
I want to realize "torch.Concat" in parallel. So, the time that my model costs is max(time(net1), time(net2), time(net3)).  my model topo is ：

input  
  ------------>net1
  ------------>net2
  ------------>net3
  ------------------->cat(net1_out, net2_out, net3_out) 
  ----------------------------> .......

**Comment by zou3519** [comment]
Probably a better question for the forums, please ask over there.
