### ISSUE TITLE
Pytorch 1.0.0 with Serverless and AWS Lambda timeout; Error in cpuinfo

### ISSUE THREAD

**Issue by norahsakal** [pytorch/pytorch#15213]
## 🐛 Bug

I am running an image classification model with Serverless and AWS Lambda. Receiving following error upon calling the Serverless function; **"Error in cpuinfo: failed to parse the list of present procesors in /sys/devices/system/cpu/present"** - I did not misspell this, the spelling is copied from the error message I received and appear with the same spelling here; 
https://github.com/pytorch/cpuinfo/blob/master/src/linux/processors.c

Suspected it might be something with Pytorch 1.0.0 so I switched back to Pytorch 0.4.1 which made it work.

## To Reproduce

1.  Run Pytorch in a Lambda with following whl in the requirements.txt; 
Pillow==5.3.0
PyYAML==3.13
**https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl**
torchvision==0.2.1

2. Load optional model and predict an image, this error should arise; **"Error in cpuinfo: failed to parse the list of present procesors in /sys/devices/system/cpu/present"**
and you will also get a timeout from the Lambda, regardless of how long timeout that is chosen; **"Process exited before completing request"**

No stack trace available, I only receive **"Error in cpuinfo: failed to parse the list of present procesors in /sys/devices/system/cpu/present"**
and a timeout error; **"Process exited before completing request"**

## Expected behavior

Expected image prediction from the model every time a new image is uploaded.

## Environment

 - PyTorch Version (e.g., 1.0): **1.0.0**
 - OS (e.g., Linux): **Linux**
 - How you installed PyTorch (`conda`, `pip`, source): **pip3**
 - Build command you used (if compiling from source):
 - Python version: **3.6**
 - CUDA/cuDNN version: **No CUDA**
 - GPU models and configuration: **No GPU**
 - Any other relevant information: **Deployed with Serverless and AWS Lambda, 3008 GB memory and 30 second timeout, works with Pytorch 0.4.1**

## Additional context

Suspected it might be something with Pytorch 1.0.0 so I switched back to Pytorch 0.4.1 which made the image prediction work.

Let me know if I can provide any additional information.

**Comment by soumith** [comment]
once the bug is fixed on the cpuinfo repo, we can update the submodule, and you can get the fix either from our nightly builds, or we'll push it into 1.0.1

**Comment by norahsakal** [comment]
Thanks @soumith!

**Comment by Maratyszcza** [comment]
@norahsakal @bendidi: could you test on a nightly or master build of PyTorch and tell us if its fixed? The nightly builds are here: https://anaconda.org/pytorch/pytorch-nightly

**Comment by bendidi** [comment]
Hi @Maratyszcza , still get the same Error : 
![image](https://user-images.githubusercontent.com/22003440/50339729-68603400-0518-11e9-89b7-bfcf6a2140ab.png)

the version of pytorch I'm installing : 
```bash
Step 8/37 : RUN pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
 ---> Running in fe6c1bc6796e
Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting torch_nightly
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch_nightly-1.0.0.dev20181220-cp36-cp36m-linux_x86_64.whl (88.6MB)
Installing collected packages: torch-nightly
Successfully installed torch-nightly-1.0.0.dev20181220
```
+ `numpy==1.11`
+ `torchvision_nightly==0.2.1`

**Comment by Maratyszcza** [comment]
@bendidi: cpuinfo reports the error, but now it has a work-around (I should probably downgrade it to a warning). Is anything wrong besides error reported on the log?

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/16107
Patch will be part of v1.0.1 release and also part of tomorrow's nightly builds.

**Comment by mattmcclean** [comment]
@norahsakal did you manage to get this to work? Am interested to know how you got your package size under the AWS Lambda limit of 250 MB. Already PyTorch (216 MB) + Numpy (63 MB) is more than the limit

**Comment by bendidi** [comment]
Hi @mattdawkins, yes cpuinfo errors are fixed 👍 (thx @Maratyszcza )

for the aws limits, one way to do it is to build your env in a docker file, package it in a zip file and save it to s3, and for each lambda call, your script will download the zip packages, unzip it (in `/tmp/`) and then `sys.append(path/to/req)`, 
the docker can be something like this : 
```Docker
FROM lambci/lambda:build-python3.6

# install all your python dependencies (i used numpy 1.11 for it's smaller size) 
RUN pip install numpy==1.11.3 
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# install pytorch and torchvision
RUN pip install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp36-cp36m-linux_x86_64.whl
RUN pip install torchvision==0.2.1

# copy site-packages to /deps
RUN mkdir -p /deps/
RUN cp -a -r /var/lang/lib/python3.6/site-packages/. /deps

# some cleaning for smaller footprint
RUN du -sch /deps
RUN find /deps/. -type d -name "tests" -exec rm -rf {} +
RUN rm -rf /deps/{caffe2,wheel,pkg_resources,boto*,aws*,pip,pipenv}
RUN rm /deps/torch/lib/libtorch.so
RUN rm -rf /deps/{*.egg-info,*.dist-info}
RUN find /deps/. -name \*.pyc -delete
RUN du -sch /deps

# zip it 
RUN cd /deps && zip -9 -q -r /pytorch1.0.1_lambda_deps.zip .

# save it in s3 : 
RUN pip install awscli
ARG AWS_ACCESS_KEY_ID=""
ARG AWS_SECRET_ACCESS_KEY=""
RUN aws s3 cp /pytorch1.0.1_lambda_deps.zip s3://YOUR_BUCKET/pytorch1.0.1_lambda_deps.zip
```

in your code it will then be just : 
```python
import os
import shutil
import sys
import zipfile
import boto3

s3 = boto3.client('s3')

zip_requirements = "/tmp/pytorch1.0.1_lambda_deps.zip"
pkgdir = '/tmp/sls-py-req'
sys.path.append(pkgdir)
if not os.path.exists(pkgdir):
    tempdir = '/tmp/_temp-sls-py-req'
    if os.path.exists(tempdir):
        shutil.rmtree(tempdir)

    s3.download_file(
                YOUR_BUCKET,"pytorch1.0.1_lambda_deps.zip", zip_requirements)
    zipfile.ZipFile(zip_requirements, 'r').extractall(tempdir)
    os.remove(zip_requirements)
    os.rename(tempdir, pkgdir)  # Atomic
print("Deps extracted successfully !")
```

personnaly I package pytorch+numpy=1.11.3 directly with the lambda to take advantage of the 250Mb availlable, and download the rest of the requirement as above.

hope it helps !

**Comment by bendidi** [comment]
one problem that I've run into @soumith @Maratyszcza if you have any idea or advice to solve it, is that   the gcc in aws lambda runtime in `gcc==4.8.5` while to use cpp extensions with pytorch the minimum version required for gcc is `4.9` (cf [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L53) ), I'm trying to run [maskrcnn-benchmark]( https://github.com/facebookresearch/maskrcnn-benchmark) models in lambda and it uses cpp scripts (if you have any idea @fmassa  too) , the error I get is : 

```bash
Unable to import module 'lambda/inference': /usr/lib64/libstdc++.so.6: version` GLIBCXX_3.4.20' not found (required by /var/task/lambda/lib/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so)
```

some of the things I tried is to package `libstdc++.so.6` with maskrcnn-benchmark and add 
```python
extra_compile_args = {"cxx": [
        '-Wl,-rpath,$ORIGIN'
    ]}
```
to setup of maskrcnn-benchmark , but `_C.cpython-36m-x86_64-linux-gnu.so` still looks for system `libstdc++.so.6` instead of teh one in $ORIGIN 

thank you

**Comment by norahsakal** [comment]
> @norahsakal did you manage to get this to work? Am interested to know how you got your package size under the AWS Lambda limit of 250 MB. Already PyTorch (216 MB) + Numpy (63 MB) is more than the limit


Hej! @mattmcclean I just tried it out, and it works with PyTorch 1.0.0 
A trick to reduce the size of the packages (except for the excellent explanation by @bendidi) is to use the following in your `requirements.txt`;
```
https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
```

This PyTorch Linux binary is without CUDA and is therefore, <100 MB

Visit; [dealing-with-lambdas-size-limitations](https://www.npmjs.com/package/serverless-python-requirements#dealing-with-lambdas-size-limitations) to read about how to compress the libraries, it only requires a minor change to your `serverless.yml` code;

```
custom:
  pythonRequirements:
    zip: true
```

And then the following at the top of your handler module;
```
try:
  import unzip_requirements
except ImportError:
  pass
```

My entire package file is currently **98.11 MB** + **86.78 MB** and includes all of this;
```
Pillow==5.3.0
PyYAML==3.13
https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
torchvision==0.2.1
```

For additional PyTorch Linux binaries without CUDA visit; https://pytorch.org/get-started/previous-versions/

**I hope it'll work for you!**

**Comment by mattmcclean** [comment]
Thanks @norahsakal & @bendidi. Got it working 😄 Created a Lambda layer with the zipped **.requirements.zip**  file (with PyTorch + associated libs) and **unzip_requirements.p**y file so can be reused by other Lambda functions. 

Now super easy as I only need the ` import unzip_requirements` statement at the beginning of the file

**Comment by soumith** [comment]
@bendidi I'm curious about this line:

> for each lambda call, your script will download the zip packages, unzip it (in `/tmp/`) and then `sys.append(path/to/req)`,

Doesn't that add a lot of overhead, if it's for each user side request?

**Comment by bendidi** [comment]
@soumith usually when the lambda is "hot" it will be called just one time per batch-of-requests (as the zip file will stay in /tmp/ and can be reused by subsequent calls), so it is generally just downloaded for the first few parallel calls and reused for subsequent calls when the first ones finish.

Another thing is I try to keep the deps package as small as possible normally (30Mb in my case) and with the download speed in aws Lambda it's quite fast and doesn't impact much the performance (knowing that the inference on an image in my case takes 30-40 seconds, so it's pretty much negligible) 

@mattdawkins cool ! that was my plan too(after fixing the bug above 😅 ) , it's probably the best way to do it !

**Comment by mattmcclean** [comment]
@soumith no you don't need to do this. I modified mine to bundle a zip inside another zip to get around the 250 MB problem so there is no need to download packages when the Lambda execution context is created. All it needs to do is unzip an 80 MB zip file contained in the Lambda layer using the **unzip_requirements.py** script. As long as you do this at the beginning of the script and not in the lambda handler method then it is done only once on execution context creation.

For subsequent invocations there is no penalty and the PyTorch model is already loaded in memory.  I will create a project and share soon..

**Comment by norahsakal** [comment]
> Thanks @norahsakal & @bendidi. Got it working 😄 Created a Lambda layer with the zipped **.requirements.zip** file (with PyTorch + associated libs) and **unzip_requirements.p**y file so can be reused by other Lambda functions.
> 
> Now super easy as I only need the ` import unzip_requirements` statement at the beginning of the file

I'm glad the solution I suggested worked out for you 🙌

**Comment by Con-Mi** [comment]
I have made a Docker image that runs a shell script and packages PyTorch 1.0.1 and all the necessary packages that come with it (Pillow, numpy, etc). The total package exceeds the uncompressed size of 250MB but if you use the strip command it will reduce the size to around 230MB and it fits.

You can find the scripts here: 
https://github.com/Con-Mi/data_science_aws_lambda_packs/tree/master/pytorch1.0.1

**Comment by mattmcclean** [comment]
Created an example project here showing how to deploy using [Serverless Application Model (SAM)](https://github.com/awslabs/serverless-application-model) which deploys your AWS Lambda functions + API GW easily here - https://github.com/mattmcclean/sam-pytorch-example
