### ISSUE TITLE
Tutorial code for C++ crashes on Windows in Debug builds

### ISSUE THREAD

**Issue by hyklv** [pytorch/pytorch#15236]
## 🐛 Bug

I'm trying to get started with some tutorials on the C++ api of PyTorch on Windows but they crash in Debug builds. **Release builds work fine.**

Crash:

![image](https://user-images.githubusercontent.com/45884850/50026516-8b0abe00-ffe9-11e8-8390-520969b0b8b4.png)

With this call stack:

```
 	[External Code]	
>	example-app.exe!torch::OrderedDict<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::shared_ptr<torch::nn::Module> >::insert<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::shared_ptr<torch::nn::LinearImpl> >(std::basic_string<char,std::char_traits<char>,std::allocator<char> > && key, std::shared_ptr<torch::nn::LinearImpl> && value) Line 358	C++
 	example-app.exe!torch::nn::Module::register_module<torch::nn::LinearImpl>(std::basic_string<char,std::char_traits<char>,std::allocator<char> > name, std::shared_ptr<torch::nn::LinearImpl> module) Line 535	C++
 	example-app.exe!torch::nn::Module::register_module<torch::nn::LinearImpl>(std::basic_string<char,std::char_traits<char>,std::allocator<char> > name, torch::nn::ModuleHolder<torch::nn::LinearImpl> module_holder) Line 543	C++
 	example-app.exe!Net::Net() Line 9	C++
 	example-app.exe!`dynamic initializer for 'net''() Line 27	C++
 	[External Code]	

```

Source code:

```
#include <torch/torch.h>
#include <iostream>


// Define a new Module.
struct Net : torch::nn::Module {
  Net() {
    // Construct and register two Linear submodules.
    fc1 = register_module("fc1", torch::nn::Linear(8, 64));
    fc2 = register_module("fc2", torch::nn::Linear(64, 1));
  }

  // Implement the Net's algorithm.
  torch::Tensor forward(torch::Tensor x) {
    // Use one of many tensor manipulation functions.
    x = torch::relu(fc1->forward(x));
    x = torch::dropout(x, /*p=*/0.5, true);
    x = torch::sigmoid(fc2->forward(x));
    return x;
  }

  // Use one of many "standard library" modules.
  torch::nn::Linear fc1{nullptr}, fc2{nullptr};
};

// Create a new Net.
Net net;


int main() {
}
```

## Expected behavior

Expected to either have support for debug builds or have specific dlls for debug builds. 

## Environment

```
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 385.54
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] mkl-service               1.1.2            py37hb217b18_5
[conda] mkl_fft                   1.0.6            py37h6288b17_0
[conda] mkl_random                1.0.2            py37h343c172_0
[conda] pytorch                   1.0.0           py3.7_cuda90_cudnn7_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch
```
## Additional context

The crash happens because the object layout of the `std::` members in `OrderedDict`  in `torch::nn::Module` differ in debug and release builds. The header defined function `register_module` is then the first to crash when `children_.insert` expects a different layout of `children_`.

**Comment by mnboos** [comment]
Seems to be the same problem: https://github.com/pytorch/pytorch/issues/14402

**Comment by suo** [comment]
cc @goldsborough

**Comment by peterjc123** [comment]
Sorry for late reply. This problem may be caused by the mismatch of the configuration Debug and Release. In MSVC, they are not ABI-compatible. So actually this is not a bug.

**Comment by hyklv** [comment]
Ok, So I should stick to only using Release builds. Thanks for the clarification!

**Comment by slaweku** [comment]
Hi,
I do not get it why it is closed. How one can develop without running a Debug version?
If Debug and Release torch binaries are not compatible, you should provide information how to build both, and properly link them.

**Comment by suo** [comment]
Hi @slaweku, check out our documentation on Windows builds: https://pytorch.org/docs/stable/notes/windows.html. If they are not sufficient for you, let us know and we can improve them. Thanks!

**Comment by slaweku** [comment]
Michael,
Thank you very much. I will attempt to build it today. But my point is that
someone should write a few line explaining the situation and the workaround
at https://pytorch.org/cppdocs/installing.html.
Because if I follow instructions there, I will get hit with the issue, and
it is a runtime issue with a cryptic message.

Regards,
Slawek

**Comment by suo** [comment]
That's good feedback, thanks! I updated the cpp tutorial but not the base docs, that was a mistake. I'll update the cpp tutorial :)
________________________________

**Comment by slaweku** [comment]
Thank you!

**Comment by suo** [comment]
#17452
