### ISSUE TITLE
doc err:torch.nn.BCELoss

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#15262]
pytorch 1.0
-------------
DOC:This is used for measuring the error of a reconstruction in for example an auto-encoder. Note that the targets y should be numbers between 0 and 1.
--------------
import torch 
import torch.nn.functional as F
b=[[0.2,0.1]]
c=[[1.,3.]]
aa = torch.tensor(b,requires_grad=True)
target = torch.tensor(c)
output = F.binary_cross_entropy(aa,target,reduce=True,size_average=True)
z=output.sum()
z.backward()
print(output)
-----------------------
tensor(4.1532, grad_fn=<BinaryCrossEntropyBackward>)
---------------
target value is 1 and 3.,not between 0 and 1.

**Comment by Ir1d** [comment]
https://pytorch.org/docs/stable/nn.functional.html#binary-cross-entropy The docs changed and this issue can be closed.
