### ISSUE TITLE
Support arbitrary file-like objects in torch.save and torch.load

### ISSUE THREAD

**Issue by alcinos** [pytorch/pytorch#1526]
Hi,

I've tried with no success to use compression (gzip, bz2,...) when saving a model with torch.save, but with no success.
When using ```gzip.open("file",'wb')``` and then passing the resulting file to ```torch.save```, it does not work presumably because the C++ saving method do not use directly the file object.
My other idea was to pass a buffer to the save method and compress it afterwards, but this doesn't work for the same reason.

Am I missing something ?

Thanks in advance.

**Comment by apaszke** [comment]
Yes, our current code requires that the file object supports the `fileno` method, so we can recover the file descriptor and write directly to it. This would need to be improved. A workaround for now would be to save the file on disk, compress it and remove the original version (I assume that if it fits in your memory, then it will fit on HDD too).

**Comment by xuancong84** [comment]
Thanks to @alcinos , I also encounter the same problem. Upon examining into the problem, I found that the following operations in torch.save have actually succeeded:
```
    pickle_module.dump(MAGIC_NUMBER, f, protocol=pickle_protocol)
    pickle_module.dump(PROTOCOL_VERSION, f, protocol=pickle_protocol)
    pickle_module.dump(sys_info, f, protocol=pickle_protocol)
    pickler = pickle_module.Pickler(f, protocol=pickle_protocol)
    pickler.persistent_id = persistent_id
    pickler.dump(obj)
```

What fails is the last operation:
```
    for key in serialized_storage_keys:
        serialized_storages[key]._write_file(f)
```
This calls the native serialized storage writer which is implemented in C, it writes to the file directly using fileno, thus, it has bypassed the gzip wrapper. Thus, the resultant GZIP file is corrupted.

**Comment by elanmart** [comment]
@soumith  I think this can be closed via https://github.com/pytorch/pytorch/pull/5466
