### ISSUE TITLE
Win10 source code compilation pytorch importerror: no module named 'torch'

### ISSUE THREAD

**Issue by CNGU-wang** [pytorch/pytorch#15274]
I compiled the source code successfully with the anaconda prompt, but I wrote the error "ImportError: No module named 'torch'" in python. I couldn't find the pytorch in the conda list, but I found "pytorch-" in the pkgs directory of anacoda. 1.0.0-py3.5_cuda90_cudnn7_1" This folder, I don't know what the reason for the import error is.
![image](https://user-images.githubusercontent.com/38982792/50044074-87df0300-00b9-11e9-8ca4-66558ead4d52.png)
![image](https://user-images.githubusercontent.com/38982792/50044082-94635b80-00b9-11e9-8f3d-b631ade8490c.png)

**Comment by peterjc123** [comment]
The installed package should reside in `[Anaconda Root]\Lib\site-packages` with the name `torch`. How did you compile it? Is there more than one Python environment on your machine?

**Comment by CNGU-wang** [comment]
![image](https://user-images.githubusercontent.com/38982792/50090298-116e0c80-0243-11e9-9b02-e090e486858b.png)
![image](https://user-images.githubusercontent.com/38982792/50090306-18951a80-0243-11e9-99ad-c2aba9a61788.png)
I am using python setup.py build, I understand, I just build, and there is no install, thank you for your answer, I am very grateful

**Comment by peterjc123** [comment]
@CNGU-wang Would you please close this PR?
