### ISSUE TITLE
[JIT] Support of optional parameters in script methods

### ISSUE THREAD

**Issue by norpadon** [pytorch/pytorch#15278]
## 🚀 Feature
It would be great to be able to pass optional parameters to the `forward` method, for example:
```
class Attention(jit.ScriptModule):
    @jit.script_method
    def forward(self, attender, attendee, seq_length=None, mask=None):
        if mask is not None:
            ...
        if seq_length is not None:
            ...
        ...
```

## Motivation

For operations such as self-attention, it is common to pass optional arguments, such as mask which enforces an autoregressive structure of the model. A lot of existing code already uses this approach, so this feature will make switching to JIT an easier task.

## Pitch

Arguments to the script methods can take a default value of `None`. Any use of the underlying tensor can occur only inside the enclosing `if ... is not None` expression. I suppose it is possible to implement a separate compiled function for each combination of provided arguments, with specific implementation being chosen depending on which variant is being called.

**Comment by driazati** [comment]
This is some support for this already, but as of now is undocumented since the API is unstable. Currently, the types must be explicitly annotated with a Python 3 type hint or mypy style type comment and manually unwrapped. You can find some examples here [torch/nn/functional.py:2099](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L2099).

**Comment by driazati** [comment]
Feature will be added by #15587, but it's going to need some documentation to match

**Comment by eellison** [comment]
Closed - check the docs for [details](https://pytorch.org/docs/stable/jit.html#types)! It may take a little while for the website to update
