### ISSUE TITLE
Please make Slerp function available for generative model sampling

### ISSUE THREAD

**Issue by rahulbhalley** [pytorch/pytorch#15287]
## 🚀 Feature
I see that [`torch.lerp`](https://pytorch.org/docs/stable/torch.html?highlight=lerp#torch.lerp) function is available but `torch.slerp` does not exist in PyTorch 1.0.

## Motivation
This feature request is motivated from the current research requirements and the way generative models are being developed (GANs specifically) i.e. the manipulation of output samples is made from latent input space. 
The paper [DCGAN](https://arxiv.org/abs/1511.06434) performed latent interpolation linearly ([`torch.lerp`](https://pytorch.org/docs/stable/torch.html?highlight=lerp#torch.lerp) would suffice) but [Sampling Generative Networks](https://arxiv.org/abs/1609.04468) paper suggests to use [Slerp function](https://en.wikipedia.org/wiki/Slerp) for interpolation. Moreover the following recent works go for Slerp too, for instance recently introduced [GAN 2.0](https://arxiv.org/abs/1812.04948), etc.

## Pitch
Please make [Slerp](https://en.wikipedia.org/wiki/Slerp) function available so that we can sample generative networks more effectively. 

## Alternatives
As an alternative please provide a PyTorch `Tensor`-based code snippet to compute [Slerp function](https://en.wikipedia.org/wiki/Slerp) effectively and easily.

## Additional context

Here is a Wikipedia's article showing example of [C++ and Python-NumPy code snippet](https://en.wikipedia.org/wiki/Slerp#Source_code) for [Slerp](https://en.wikipedia.org/wiki/Slerp).

**Comment by soumith** [comment]
Hi Rahul,

The NumPy code snippet given for slerp can be translated 1-to-1 into a PyTorch snippet.
Slerp is not common enough that I think has value to add it as a standard function into PyTorch.

**Comment by rahulbhalley** [comment]
> The NumPy code snippet given for slerp can be translated 1-to-1 into a PyTorch snippet.

Ok. Can someone help me in writing one in PyTorch? I don't understand how to from that Wikipedia's NumPy snippet.

**Comment by soumith** [comment]
you can post on https://discuss.pytorch.org to see if anyone would help, though it looks like a literal translation with minor changes needed
