### ISSUE TITLE
python3 PyTorch installation - cuda-convnet2 not python3 ready

### ISSUE THREAD

**Issue by h6197627** [pytorch/pytorch#15285]
## 🐛 Bug

cuda-convnet2 from caffe2 contrib, which is now also installed during PyTorch installation, is not python3 ready. Number of **SyntaxError: invalid syntax** occurs during byte-compiling while installing.

## To Reproduce

1. python3 setup.py install

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Python version: 3.5

**Comment by soumith** [comment]
closing this with a `wontfix` tag. We might just remove those bits soon.

**Comment by ezyang** [comment]
Hmm, I don't understand why this file would trigger an error on install though

**Comment by gottbrath** [comment]
These are easy fixes. I have the patch for this and am getting a clean install on ubuntu 18.04. I will clean it up and share them shortly.

**Comment by h6197627** [comment]
@ezyang, I am not using pip. I do
> sudo python3 setup.py install

It builds normally but when performing installation it copies files and do byte-compilation (with error).
This particular cuda-convnet2 issue already addressed in this pull request #15784

**Comment by gottbrath** [comment]
ok .. it looks like this is getting fixed by being removed in pull request #15784

**Comment by gottbrath** [comment]
I uploaded the fix in my private fork of pytorch. in case anyone wants them sometime.

**Comment by gottbrath** [comment]
resolved with https://github.com/pytorch/pytorch/commit/a9438ba62f02af5032171c3773bfc54c348de298
