### ISSUE TITLE
how to batch multi 3d tensor to 4d tensor  by tensorFromBlob c++ api? 

### ISSUE THREAD

**Issue by ismymajia** [pytorch/pytorch#15299]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cv::Mat a;
cv::Mat b;
auto vTensor = torch::CPU(torch::kFloat32).tensorFromBlob(c.data, { 2, h, w, 3 });
??
how to gen c.data ??
i want process batch tensor.

**Comment by SsnL** [comment]
`tensorFromBlob` them separately then `torch::cat`.
