### ISSUE TITLE
Conv2d bug with group > 1

### ISSUE THREAD

**Issue by guohengkai** [pytorch/pytorch#15297]
## 🐛 Bug

The results of F.conv2d with group > 1 is strange.

## To Reproduce

In [1]: import torch

In [2]: import torch.nn.functional as F

In [3]: dx = torch.Tensor([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1.]])

In [4]: dx = (dx * 0.125).unsqueeze(0).expand(8, -1, -1).unsqueeze(1)

In [5]: inputs = torch.randn(1,8,5,5)

In [6]: F.conv2d(inputs, dx, groups=8)

## Expected behavior

In 0.4.1:
tensor([[[[ 0.4119, -0.4022, -0.5092],
          [ 1.2456, -0.1181, -1.1184],
          [ 1.1484,  0.6212, -0.8608]],

         [[ 0.5733, -0.1322, -0.4641],
          [ 0.4117,  0.3309, -0.4845],
          [ 0.3492,  0.3291, -0.3306]],

         [[ 0.1463, -0.2549, -0.2952],
          [ 0.1048,  0.1420,  0.0386],
          [-0.6000,  0.3802,  0.4664]],

         [[ 0.1368,  0.8860, -0.0975],
          [ 0.2206,  0.8493, -0.1972],
          [ 0.3737,  0.6972, -0.1271]],

         [[-1.3357, -0.4393,  0.1974],
          [-0.2722,  0.0696,  0.0812],
          [ 0.3726, -0.5581, -0.0688]],

         [[-0.1332, -1.1372, -0.2584],
          [-0.6551, -0.6942,  0.0089],
          [-0.4276, -0.2241, -0.1934]],

         [[-0.3422, -0.3853, -0.0875],
          [ 0.2579,  0.0665, -0.1295],
          [ 0.4803,  0.3685,  0.3161]],

         [[ 0.4988, -0.2632, -0.5304],
          [ 0.1402, -0.2246,  0.1812],
          [-0.4755,  0.1462,  0.3375]]]])

But in 1.0.0:
tensor([[[[ 4.7747e-02, -6.5122e-02, -3.0083e-03],
          [-8.1758e-02,  8.8408e-02, -1.6651e-01],
          [ 3.6202e-01,  3.4218e-01, -3.1302e-01]],

         [[-1.9467e+29, -1.6233e+29,  2.1921e+29],
          [-8.6063e+28,  8.2235e+28, -4.1196e+29],
          [-2.4968e+29,  8.6508e+27,  1.7153e+29]],

         [[-7.6571e+30, -4.1644e+31,  1.7866e+31],
          [ 1.0889e+32, -6.1872e+31,  1.0363e+32],
          [ 2.8425e+31, -1.0478e+32, -1.1115e+32]],

         [[-3.0504e+31, -1.7218e+31, -7.7394e+30],
          [ 3.6995e+31, -8.5841e+30,  1.3978e+31],
          [ 2.9446e+31, -4.6502e+30, -2.5080e+30]],

         [[-2.9951e+30,  3.1599e+30, -4.2981e+29],
          [ 5.3519e+30,  8.7338e+30,  1.4847e+30],
          [ 2.3451e+29, -1.4605e+30, -1.8420e+30]],

         [[-5.3504e+30, -9.1470e+29, -2.2875e+30],
          [ 5.2828e+30, -3.3225e+30, -3.7776e+30],
          [-6.2590e+30, -7.1090e+30, -7.9281e+30]],

         [[-2.8818e+31, -1.1245e+32,  1.0156e+32],
          [ 7.1740e+31,  6.1316e+31,  2.9348e+31],
          [ 4.2056e+31, -3.6838e+31, -1.5117e+32]],

         [[ 1.5956e+33, -6.4368e+33,  2.4740e+33],
          [-1.0512e+33, -5.2669e+33,  7.0033e+33],
          [-1.1067e+33,  1.6537e+33, -2.8912e+33]]]])

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.12.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by guohengkai** [comment]
@zou3519  I just use pip3 to install the torch. Do you have any idea to check it?

**Comment by guohengkai** [comment]
@zou3519 And I can reproduce it on Linux:
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Debian GNU/Linux 8.7 (jessie)
GCC version: (Debian 4.9.2-10) 4.9.2
CMake version: Could not collect

Python version: 3.5
Is CUDA available: No
CUDA runtime version: 8.0.61
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 381.22
cuDNN version: Probably one of the following:
/usr/local/cudnn-v5.1/lib64/libcudnn.so.5.1.5
/usr/local/cudnn-v5.1/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip3] msgpack-numpy (0.4.3.1)
[pip3] numpy (1.14.5)
[pip3] torch (1.0.0)
[pip3] torchfile (0.1.0)
[pip3] torchsample (0.1.3)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by guohengkai** [comment]
Any update?

**Comment by soumith** [comment]
@guohengkai we couldn't reproduce it. Can you try the PyTorch Preview build (from the website selector), and see if it fixes things?
