### ISSUE TITLE
torch.meshgrid behaves differently with numpy.meshgrid 

### ISSUE THREAD

**Issue by harryhan618** [pytorch/pytorch#15301]
```
import torch
import numpy as npt
x = torch.arange(3)
y = torch.arange(10,14)
print(torch.meshgrid([x,y]))
print(np.meshgrid(x.numpy(), y.numpy()))
```

which gives:
```
(tensor([[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]]), 
 tensor([[10, 11, 12, 13],
         [10, 11, 12, 13],
         [10, 11, 12, 13]]))
```
and 
```
[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]), 
 array([[10, 10, 10],
        [11, 11, 11],
        [12, 12, 12],
        [13, 13, 13]])]
```

I think numpy's behavior makes more sense, when I'm implementing object detection algorithm YOLO and trying to recover the bounding boxes from the offsets to the grids.
Also, this inconsistence will cause wrong results to those who don't check the pytorch behavior

Correct me if there is a better indention to implement like this. Thank you!

Pytorch version: 0.4.1.  I just download 1.0 and it behaves just the same as 0.4.1

**Comment by fmassa** [comment]
We might want to add the [`indexing` option to `meshgrid`, similarly to numpy](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.meshgrid.html).
The current behavior of PyTorch meshgrid is `ij`, while numpy defaults to `xy`.

**Comment by geyang** [comment]
`torch.meshgrid` makes more sense when you extend `meshgrid` to higher dimensions. We recently ran into this problem from two directions, in one case `numpy` ordering was preferrable, and later when we realized the value of the `torch.meshgrid` ordering.
