### ISSUE TITLE
Kaiming init of conv and linear layers, why gain = sqrt(5)

### ISSUE THREAD

**Issue by mratsim** [pytorch/pytorch#15314]
cc @fmassa as he introduces those in https://github.com/pytorch/pytorch/pull/9038.

Looking into the initialisation of Linear and Convolution layers we have the following

Linear: https://github.com/pytorch/pytorch/blob/3df79f403e8b9621d5adb0447266becd10d633b0/torch/nn/modules/linear.py#L58-L63

Convolution: https://github.com/pytorch/pytorch/blob/3df79f403e8b9621d5adb0447266becd10d633b0/torch/nn/modules/conv.py#L45-L51

Notice the sqrt(5) scaling factor.

## Kaiming paper
https://arxiv.org/abs/1502.01852

The standard deviation should be sqrt(2 / fan_in)
![2018-12-17_22-45-34](https://user-images.githubusercontent.com/22738317/50117507-86464400-024d-11e9-9c6a-981b6898160a.png)

Using the same principle as [Glorot et al](http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf) paper, for an uniform distribution we should use bounds of `±√3 * sqrt(2 / fan_in)`

This is what is done here: https://github.com/pytorch/pytorch/blob/700271d0e92c33a4cce3fee34b39ad5baa179b00/torch/nn/init.py#L288-L293

## Diving deeper into the implementation

It seems like the a = √5 is used in https://github.com/pytorch/pytorch/blob/700271d0e92c33a4cce3fee34b39ad5baa179b00/torch/nn/init.py#L8-L47

The `a` is only used for leaky_relu, which actually is the default if we don't pass any activation to `kaiming_uniform`:
https://github.com/pytorch/pytorch/blob/700271d0e92c33a4cce3fee34b39ad5baa179b00/torch/nn/init.py#L261

Furthermore this √5 factor conflicts with the recommended `sqrt(2.0 / (1 + negative_slope ** 2))` in calculate_gains, and I suspect this is unintentional.

# Docs

Whether the √5 factor is intentional or not, the documentation is wrong for the weights.

## Linear

![2018-12-17_22-52-08](https://user-images.githubusercontent.com/22738317/50117993-acb8af00-024e-11e9-9f74-f6bdb250c26c.png)

While for bias `k = 1/in_features` is true, for the weight, `k = 6/in_features` assuming pure Kaiming, or `k = 6 * 5/in_features` at the moment.

## Convolution

![2018-12-17_22-50-39](https://user-images.githubusercontent.com/22738317/50118128-0faa4600-024f-11e9-9749-adcc4abcc05a.png)

Same remark

## Closing thoughts

Plenty of tutorials uses ReLU and not LeakyReLU, having the default initialisation for `kaiming_uniform` to leaky relu would create suboptimal training for those.

At the very least it should be noted in the documentation that Linear and Conv layers initialisation is done assuming it is followed by a leaky relu activation.

Finally the √5 should be explained.

**Comment by eugeneware** [comment]
I agree, I've also being trying to work out where the `sqrt(5)` factor comes from for Linear layer initialisation. 

In the [PR that updates this value](https://github.com/pytorch/pytorch/pull/9038/files), there is no indication of why it was changed, and as @mratsim has noted, the documentation doesn't reflect this either. Is this a typo/bug that needs to be fixed?

I change in the default initialisation for Linear layers is likely to have a large impact on the default performance of models, so if this is an issue, it probably should be rectified with a high priority.

**Comment by soumith** [comment]
closing via @eugeneware 's comment.

the code refactor from jramseyer changes the default pytorch initialization from manually initializing the weights by calling random number generator function `uniform` to using `torch.nn.init.kaiming` -- but it wanted to have the same end-result in weights, because we wanted to preserve backward-compatibility. So the sqrt(5) is nothing more than giving the code the same end-result as before.

The initialization itself comes from torch7  and torch5 and is a modified version of initialization fro Lecun'98 Efficient Backprop. This post gives more context: https://plus.google.com/106447253626219410322/posts/RZfdrRQWL6u

**Comment by dguera** [comment]
The G+ link no longer works. Alternative Internet Archive link follows: https://web.archive.org/web/20170721060953/https://plus.google.com/+SoumithChintala/posts/RZfdrRQWL6u
