### ISSUE TITLE
torch.gesv forward handles singleton dimension, but backward doesn't

### ISSUE THREAD

**Issue by jacobrgardner** [pytorch/pytorch#15328]
## 🐛 Bug

I'm running in to an issue where `torch.gesv` accepts a `torch.Size([n])` right hand side (with an `n x n` left hand side) in the forward pass, but the backward pass will fail. Unsqueezing the right hand side to `torch.Size([n, 1])` and then squeezing the output gets me the same size output (`torch.Size([n])`), but the backward pass also works.

## To Reproduce
```python
import torch

A = torch.randn(5, 5, requires_grad=True)
b = torch.randn(5, requires_grad=True)

solve = torch.gesv(b.unsqueeze(-1), A)[0].squeeze(-1) # Works
solve.sum().backward() # Works

solve2 = torch.gesv(b, A)[0] # Works
solve2.sum().backward() # Doesn't work
```
```python
Traceback (most recent call last):
  File "gesv_bug.py", line 10, in <module>
    solve2.sum().backward() # Doesn't work
  File "/home/jrg365/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jrg365/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function GesvBackward returned an invalid gradient at index 0 - got [5, 1] but expected shape compatible with [5]
```

## Expected behavior

Either (a) torch.gesv should require `b` to have the trailing singleton dimension in the forward pass (e.g. be `torch.Size([5, 1])` or (b) the backward pass should work if `b` doesn't have the singleton dimension.

## Environment

Reproducible on `pytorch-1.0.0` installed via conda.

**Comment by vishwakftw** [comment]
I am siding with torch.gesv requiring at least two dimensions. Another alternative would be to reshape the output to be of the same shape as the RHS tensor, but this needs to be done in TH/THC.
