### ISSUE TITLE
THE 'http://pytorch.org/docs/' should change to 'https://pytorch.org/docs/'

### ISSUE THREAD

**Issue by mengjiexu** [pytorch/pytorch#15325]
All URL in the official site show change from 'http://...' to 'https://...'

**Comment by soumith** [comment]
where did you see the http:// link?

**Comment by mengjiexu** [comment]
Go to 'https://pytorch.org/' and click 'DOCS' in the nav bar, It becomes 'http://pytorch.org/docs/'.

**Comment by soumith** [comment]
it takes me to https://pytorch.org/docs/stable/index.html if I do that.

**Comment by mengjiexu** [comment]
OK, May be my computer's problem, I use QQ browser.
