### ISSUE TITLE
(VS2017) error C2397: conversion from 'long' to 'uint32_t' requires a narrowing conversion on Debug env

### ISSUE THREAD

**Issue by skyser2003** [pytorch/pytorch#15330]
## 🐛 Bug
The same issue #14961(windows libtorch1.0 : cpp_export in Visual studio 2015: error C2397: conversion from 'long' to 'uint32_t' requires a narrowing conversion) was closed, but it happens the same on most recent Visual Studio 2017, version 15.9.4.
It only occurs on Debug environment, and runs fine on Release.

## To Reproduce
```
#pragma once
#include "torch/nn.h"
```

Detailed code explanation below

## Environment
 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Windows 10 x64
 - How you installed PyTorch (`conda`, `pip`, source): Libtorch
 - CUDA/cuDNN version: 10, 7.3
 - GPU models and configuration: 1050
 - Any other relevant information:

## Additional context

According to MSDN, error C2397 happens when narrowing down occurs on uniform initialization.
So I digged down the code and found the code which causes this error.

```
// c10/util/Exception.h
// Line 49
Error(SourceLocation source_location, const std::string& msg);

// Line 120
#define AT_ERROR(...) \
  throw ::c10::Error({__func__, __FILE__, __LINE__}, ::c10::str(__VA_ARGS__))

// c10/util/StringUtil.h
// Line 69
struct C10_API SourceLocation {
  const char* function;
  const char* file;
  uint32_t line;
};
```

It seems that \_\_LINE\_\_ macro value is treated as long type, so it tries to narrow down to the 'uint32_t line' constructor parameter, which causes this error.

**Comment by peterjc123** [comment]
I think we may add a conversion here for MSVC. It's safe because this [post](https://en.cppreference.com/w/cpp/preprocessor/line) says that it is UB when `__LINE__` is larger than `INT32_MAX`.

**Comment by HannH** [comment]
same error, it happen in both vs2015 and vs2017

**Comment by EmreOzkose** [comment]
Same error, any solution?

**Comment by peterjc123** [comment]
You could try PR #15333, though it's not merged yet.
