### ISSUE TITLE
Inconsistent behavior of clamp on CPU / GPU with nans

### ISSUE THREAD

**Issue by DianeBouchacourt** [pytorch/pytorch#15338]
The behavior of clamp is not consistent on CPU and GPU when nan's are involved. See the following code snippet

```python
import torch
a = torch.tensor([float('nan')])
print(a.clamp(0, 1)) # prints nan
print(a.cuda().clamp(0, 1)) # prints 1
```
This doesn't happen if we clamp only with a min or max, but only when both are passed.

I believe the problem is in https://github.com/pytorch/pytorch/blob/517c7c98610402e2746586c78987c64c28e024aa/aten/src/THC/THCTensorMathPointwise.cuh#L309 . If we compare it to the CPU implementation in https://github.com/pytorch/pytorch/blob/517c7c98610402e2746586c78987c64c28e024aa/aten/src/TH/generic/THTensorMath.cpp#L122, we see that the order of the ternary operator is inversed, which doesn't propagate nans on the CUDA case.

A simple fix would be to invert the order of the ternary operator in the CUDA kernel.

Thanks @fmassa for helping me out identifying the root cause of the issue.

**Comment by surgan12** [comment]
@fmassa Let Me handle this.

**Comment by fmassa** [comment]
@surgan12 sure, go for it!

**Comment by fmassa** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/15479
