### ISSUE TITLE
How do I understand the convolution layer derivative?

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#15341]
pytorch 1.0
conv1d or conv2d.
Now I'm trying to write the convolution layer derivative function. I can write the derivative code without the stride and padding parameters, but I can't write the code with the stride and padding parameters. Is there any document to explain the derivative formula? Or link to a paper.
我现在尝试写卷积层求导函数.在没有stride和padding参数情况下，我可以写出求导代码.但是带上stride和padding参数时，我无法写出代码。请问能否有文档对求导公式进行说明呢？或者链接到论文.

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
