### ISSUE TITLE
inspect.getargspec() is deprecated in Python 3

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#15344]
## 🐛 Bug

inspect.getargspec() is deprecated in Python 3 (in favor of inspect.getfullargspec until 3.2 and in favor of inspect.signature since 3.3).

## To Reproduce

Run any CUDA test case to see a mountain of warnings
```
pytest test/test_nn.py -v -k "variable_sequence_cuda"

```
  return inspect.getargspec(func).args
/scratch/rzou/pt/sort-packing/test/common_utils.py:181: DeprecationWarning: inspect.getargspec() is deprecated
use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(func).args
/scratch/rzou/pt/sort-packing/test/common_utils.py:181: DeprecationWarning: inspect.getargspec() is deprecated
use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(func).args
/scratch/rzou/pt/sort-packing/test/common_utils.py:181: DeprecationWarning: inspect.getargspec() is deprecated
use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(func).args
/scratch/rzou/pt/sort-packing/test/common_utils.py:181: DeprecationWarning: inspect.getargspec() is deprecated
use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(func).args
/scratch/rzou/pt/sort-packing/test/common_utils.py:181: DeprecationWarning: inspect.getargspec() is deprecated
use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(func).args
/scratch/rzou/pt/sort-packing/test/common_utils.py:181: DeprecationWarning: inspect.getargspec() is deprecate$
use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(func).args
/scratch/rzou/pt/sort-packing/test/common_utils.py:181: DeprecationWarning: inspect.getargspec() is deprecated
use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(func).args
/scratch/rzou/pt/sort-packing/test/common_utils.py:181: DeprecationWarning: inspect.getargspec() is deprecated
use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(func).args
/scratch/rzou/pt/sort-packing/test/common_utils.py:181: DeprecationWarning: inspect.getargspec() is deprecated
use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(func).args
/scratch/rzou/pt/sort-packing/test/common_utils.py:181: DeprecationWarning: inspect.getargspec() is deprecated
use inspect.signature() or inspect.getfullargspec()
```
```

## Expected behavior

No mountain of warnings...

The callsite is here:
https://github.com/pytorch/pytorch/blob/54d8ce94ee7ca7e8f2bbc0a329da00ecf65fec20/test/common_utils.py#L180-L181 , we should change it to use inspect.getargspec for python < 3.4 and inspect.signature for python >= 3.4. It is okay that we'll have warning messages for python 3 to 3.3; these messages are developer-facing and I don't think the extra complexity of using all three of `(inspect.getargspec(), inspect.getfullargspec, inspect.signature)` is worth it

## Environment
CUDA might be necessary because we use this function in our CUDA leak detector.

**Comment by epicfaace** [comment]
Since `inspect.getfullargspec` is no longer deprecated, I think it would be sufficient just to replace `inspect.getargspec` with `inspect.getfullargspec`. I've went ahead and done that in PR #15396.
