### ISSUE TITLE
Tracking bug for upgrading MKL-DNN to 0.17

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#15345]
Upgrading MKL-DNN to 0.17 as in #14308 causes MKL detection in upstream MKL-DNN to break. This does not reproduce when cmake'ing MKL-DNN's CMakeLists.txt directly. There are multiple issues here:

* The error is nondeterministic because failure to find MKL when building MKL-DNN is sometimes a warning, and sometimes an error. The problem here is tracked in #15347.
* The above wouldn't be a problem if we were able to find MKL in the first place. I verified that when I cmake mkl-dnn directly, in this environment, it is able to find MKL. So there is some bad interaction with the cmake in our project.

The inability to find MKL seems to be related to the following block of code:

```
# The OMP-related variables of MKL-DNN have to be overrode here
# if MKL is used. Then, the OMP version can be defined by MKL.
# MKL_LIBRARIES_xxxx_LIBRARY is defined by MKL.
IF (EXISTS "${MKL_LIBRARIES_gomp_LIBRARY}")
  SET(MKLIOMP5LIB ${MKL_LIBRARIES_gomp_LIBRARY} CACHE STRING "Override MKL-DNN omp dependency" FORCE)
ELSEIF(EXISTS "${MKL_LIBRARIES_iomp5_LIBRARY}")
  SET(MKLIOMP5LIB ${MKL_LIBRARIES_iomp5_LIBRARY} CACHE STRING "Override MKL-DNN omp dependency" FORCE)
ELSEIF(EXISTS "${MKL_LIBRARIES_libiomp5md_LIBRARY}")
  SET(MKLIOMP5DLL ${MKL_LIBRARIES_libiomp5md_LIBRARY} CACHE STRING "Override MKL-DNN omp dependency" FORCE)
ELSE(EXISTS "${MKL_LIBRARIES_gomp_LIBRARY}")
  SET(MKLIOMP5LIB "" CACHE STRING "Override MKL-DNN omp dependency" FORCE)
  SET(MKLIOMP5DLL "" CACHE STRING "Override MKL-DNN omp dependency" FORCE)
ENDIF(EXISTS "${MKL_LIBRARIES_gomp_LIBRARY}")
```

Specifically, when I delete these blocks, MKLDNN is able to successfully find MKL.

I pushed a minimized test case to https://github.com/ezyang/pytorch/tree/test/mkldnn-minimized-case
This test case deletes all cmake that is not related to MKLDNN.

You can reproduce the problem with:

```
mkdir build
cd build
cmake .. -DUSE_MKLDNN=ON
```

and checking to see if mkl was detected or not. If the problem does not reproduce in your environment, consult #15347 for more information on our environment with conda. Reproduce the "fix" by editing cmake/Modules/FindMKLDNN.cmake to delete the quoted block above.

**Comment by ezyang** [comment]
CC @yinghai @gujinghui

**Comment by ezyang** [comment]
Please CC me and @soumith on any subsequent PRs here, thanks.

**Comment by ezyang** [comment]
Also cc @JerryShih, because I know you've also been working on OpenMP related things.

**Comment by gujinghui** [comment]
psl try #15387
