### ISSUE TITLE
+= operates incorrectly on expand-ed tensors

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#15358]
## 🐛 Bug

Modifying an expand-ed tensor (e.g. with `+=`) gives unexpected behavior. There's no way to do this operation correctly in place, so should this raise an error? In Numpy it raises an error.

## To Reproduce

>>> a = torch.arange(4).expand(5,4)
>>> b = torch.arange(20).view(5,4)
>>> a
tensor([[0, 1, 2, 3],
[0, 1, 2, 3],
[0, 1, 2, 3],
[0, 1, 2, 3],
[0, 1, 2, 3]])
>>> a += b
>>> a
tensor([[40, 46, 52, 58],
[40, 46, 52, 58],
[40, 46, 52, 58],
[40, 46, 52, 58],
[40, 46, 52, 58]])

**Comment by surgan12** [comment]
refer to #3569 .
Do a = a + b or torch.add for the solution.

**Comment by soumith** [comment]
@gchanan @colesbury does it not satisfy you if I close this as `wontfix`????????????????????

**Comment by gchanan** [comment]
I don't remember numpy doing this in the past, but it seems to have at least some guarding:
```
>>> x = np.broadcast_to(np.ones(1), shape=(3,))
>>> x+=1

ValueError: output array is read-only
```

maybe we should do similar?

**Comment by ngimel** [comment]
This raises an error now.
