### ISSUE TITLE
Error building pytorch:  "THCudaHostAlloc" is undefined

### ISSUE THREAD

**Issue by zhanghang1989** [pytorch/pytorch#1535]
`pytorch/torch/lib/THC/generic/THCTensorMath.cu(200): error: identifier "THCudaHostAlloc" is undefined`
Any thoughts about this error?

**Comment by apaszke** [comment]
If you're building from source and see some library errors try removing `torch/lib/build` and `torch/lib/tmp_install` (or `git clean -xfd`, but this might destroy your local changes if you have any).

**Comment by zhanghang1989** [comment]
Thanks a lot @apaszke ! It works.
