### ISSUE TITLE
Bernoulli with zero probability can yield 1s

### ISSUE THREAD

**Issue by Kegnarok** [pytorch/pytorch#15356]
## 🐛 Bug

Bernoulli samples with P(1) = 0 can sometimes yield 1.

## To Reproduce

```
import torch as th
p = th.zeros((1024))
while True:
    if p.bernoulli().max() > 0:
        print('!')
```
You see some prints, which should not appear.

I believe the error comes from here, you should replace <= with <.
https://github.com/pytorch/pytorch/blob/517c7c98610402e2746586c78987c64c28e024aa/aten/src/TH/THRandom.cpp#L315

## Environment

```
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.10
GCC version: (Ubuntu 8.2.0-7ubuntu1) 8.2.0
CMake version: version 3.12.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] mkl                       2018.0.3                      1  
[conda] mkl-service               1.1.2            py36h90e4bf4_5  
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0  
[conda] mkl_random                1.0.1            py36h4414c95_1  
[conda] pytorch                   1.0.0           py3.6_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch
```

**Comment by jcjohnson** [comment]
Maybe this is related to https://github.com/pytorch/pytorch/issues/13867?

**Comment by j-min** [comment]
@jcjohnson probably it is not. [multinomial](https://github.com/pytorch/pytorch/blob/517c7c9861/aten/src/TH/generic/THTensorRandom.cpp#L247) does not internally use [`THRandom_bernoulli`](https://github.com/pytorch/pytorch/blob/517c7c9861/aten/src/TH/THRandom.cpp#L312) which is blamed here.

**Comment by zou3519** [comment]
#16075 might have fixed this

**Comment by yf225** [comment]
@Kegnarok @j-min Do you mind checking this on current master? (nightly builds: https://anaconda.org/pytorch/pytorch-nightly)
