### ISSUE TITLE
Run CUDA tests on non-default stream

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#15352]
No kernel in PyTorch should hardcode the legacy default CUDA stream. An easy way to test if this has occurred is to switch PyTorch's current stream to a stream that is not the legacy default stream; you will usually manifest the data race immediately when this occurs. We should do this.

A good place to add this interposition is in the same place where `_do_cuda_memory_leak_check` is handled.

We need to expose a non-bracketed "set CUDA stream" function, because we can't use context managers in unittest style tests in setUp/tearDown.

**Comment by SsnL** [comment]
You can always assign the ctx manager as the attribute, and call
self.stream_ctx.__enter__() in setUp, and self.stream_ctx.__exit__() in
tearDown though.

**Comment by ezyang** [comment]
This now is happening with CudaNonDefaultStream
