### ISSUE TITLE
Test that OpenMP is actually enabled

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#15351]
Prior to 71ee882157ea06b0e8facb510c44b5a3a55e5d91 we accidentally had disabled OpenMP in PyTorch builds. This is really bad. We should have a test checking that OpenMP is working.

Related: #4440

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by ezyang** [comment]
CC @gchanan

**Comment by zym1010** [comment]
I found that setting OMP_NUM_THREADS or `torch.set_num_threads` does not work in the official pip wheel of PyTorch 1.0 for CUDA10. Is my problem related to this disabling of OpenMP?

**Comment by JerryShih** [comment]
@zym1010 
I think 71ee882 should reenable the openmp.

**Comment by zym1010** [comment]
@JerryShih  so using nightly-build should work, right?

**Comment by ezyang** [comment]
Yes

**Comment by malfet** [comment]
Closing, as I think we do test for it already:
https://github.com/pytorch/pytorch/blob/7188d84ccfa54760c1078c171993b1dd9ad471ed/.jenkins/pytorch/macos-test.sh#L39-L44
