### ISSUE TITLE
GPU out of memory when data is on RAM

### ISSUE THREAD

**Issue by wddabc** [pytorch/pytorch#1537]
Hi, I'm running the following snippet
```python
import time
import torch
import numpy
torch.set_default_tensor_type("torch.FloatTensor")
w = 5000
h = 4000
assert torch.cuda.is_available()
#large_mtx=numpy.random.rand(10000, 10000)
allocation = time.time()
a = torch.rand(w,h)
b = torch.rand(h,w)
a_cu = a.cuda()
b_cu = b.cuda()
start = time.time()
print("Allocation ", allocation - start)
c = a_cu.mm(b_cu)
cu_blas = time.time()
print("Torch cuBlas ", cu_blas - allocation)
```
on my laptop, which works fine. However, when I uncomment the `large_mtx=numpy.random.rand(10000, 10000)`, which declares some CPU memory and run again. I got:

> THCudaCheck FAIL file=/Study/tools/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
> Traceback (most recent call last):
>   File "mem_test.py", line 16, in <module>
>     c = a_cu.mm(b_cu)
> RuntimeError: cuda runtime error (2) : out of memory at /Study/tools/pytorch/torch/lib/THC/generic/THCStorage.cu:66

Looks like pytorch tries to allocate that numpy array into GPU. 

I'm using pytorch 0.1.11+4e693d1, cuda version 8.0, macOs 10.12.4

**Update**. when I comment that line back, it no longer works and throws error on a different line:

> THCudaCheck FAIL file=/Study/tools/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
> Traceback (most recent call last):
>   File "mem_test.py", line 13, in <module>
>     b_cu = b.cuda()
>   File "/Study/tools/anaconda2/lib/python2.7/site-packages/torch/_utils.py", line 65, in _cuda
>     return new_type(self.size()).copy_(self, async)
> RuntimeError: cuda runtime error (2) : out of memory at /Study/tools/pytorch/torch/lib/THC/generic/THCStorage.cu:66

Looks like the GPU memory leaks on the previous run and never recycled.

**Comment by apaszke** [comment]
Can't reproduce. I can't see how allocating a CPU numpy array could interfere with cuda OOM errors. I wouldn't recommend using CUDA on macOS, there's hardly any GPU memory and it's often occupied by other programs for some reason.

**Comment by wddabc** [comment]
Thanks for the reply.  This is actually a minimal example---I'm having this issue on a Linux machine with K80. Also, looks like not only a CPU numpy array can cause, a large python built-in data structure (like dictionary) can also trigger the OOM GPU error.

**Comment by apaszke** [comment]
Can't reproduce. The memory is freed after the process exits (drops to 0MB in nvidia-smi) and adding that large numpy array has no effect 😕 Are you sure you really have enough free memory on your GPU?

**Comment by wddabc** [comment]
I'm pretty sure the GPU memory is large enough.

Seems like the given minimal example is irrelevant as I cannot reproduce it on the Linux machine either. But my main code still keep fails. The behavior of the issue is, I have a python built-in dictionary to keep track of my training procedure. It causes the GPU OOM very stably after some epochs. If I manually clean up the dictionary every several epochs, this OOM doesn't happen.

I will reopen the issue once I have a better reproducible snippet.

**Comment by rraallvv** [comment]
I'm having a [similar issue](https://github.com/r9y9/wavenet_vocoder/issues/18) with a GPU enabled Jupyter Notebook running on [Google's Collaboratory site](https://colab.research.google.com/notebooks/welcome.ipynb#recent=true) which happens to have the K80 GPU
