### ISSUE TITLE
AttributeError: Can't get attribute '_rebuild_parameter' on 

### ISSUE THREAD

**Issue by abdoelsayed2016** [pytorch/pytorch#15375]
AttributeError: Can't get attribute '_rebuild_parameter' on <module 'torch._utils' from '/opt/conda/lib/python3.6/site-packages/torch/_utils.py'>
AttributeError                            Traceback (most recent call last)
<ipython-input-1-76fbd445e7d1> in <module>()
     14 from collections import OrderedDict
     15 
---> 16 checkpoint = torch.load('/home/workspace/resnet50-transfer-4.pt')
     17 model = models.resnet50(pretrained=True)
     18

**Comment by soumith** [comment]
please report using the Bug Report template that we provide (when you open a new issue, there's a button for Bug Report). We need more info about your environment

**Comment by abdoelsayed2016** [comment]
ty 
i found solution 
i created my model with  version 1.0
when i upload it in machine ,pytorch version is 0.4

**Comment by xiangtaowong** [comment]
> ty
> i found solution
> i created my model with version 1.0
> when i upload it in machine ,pytorch version is 0.4

**Comment by xiangtaowong** [comment]
> ty
> i found solution
> i created my model with version 1.0
> when i upload it in machine ,pytorch version is 0.4

hello,i meet the same quesition, how did u solved it , using torch 1.0? 
when i use " new" it shows
![image](https://user-images.githubusercontent.com/82792833/133748949-d6e0ba9a-248a-4ae9-ac8e-249ba086a863.png)
the "old": 'module' object has no attribute '_rebuild_parameter',
looking forward to your reply!
