### ISSUE TITLE
Slower speeds using FP16 (cuDNN)

### ISSUE THREAD

**Issue by SeanNaren** [pytorch/pytorch#1539]
I created a script that benchmarks the speed of 1 LSTM on GPU [here](https://gist.github.com/SeanNaren/2918811074aa59fa1d6a0e114bbe1277). It seems to be that with cuDNN I achieve slower performance using FP16 than FP32 on a Tesla P100 (POWER8, but I've tried a DGX-1 P100 and saw similar behaviour). I've reported results below:

P100 (POWER8) CUDA 8.0 cuDNN 6.0.5(RC)

| Batch Size | FP32 Fwd (s)  | FP32 Bwd (s)  | FP16 Fwd (s)  | FP16 Bwd (s) 
|-----------------|:--------:|:--------:|:--------:|:--------:|
| 32     | 0.10    | 0.28 | 0.16    | 0.27 |
| 64     | 0.10   | 0.14 | 0.11    | 0.28 |
| 128     | 0.13    | 0.20 | 0.13    | 0.33 |

P100 (POWER8) CUDA 8.0 cuDNN 6.0.21(GA)

| Batch Size | FP32 Fwd (s)  | FP32 Bwd (s)  | FP16 Fwd (s)  | FP16 Bwd (s) 
|-----------------|:--------:|:--------:|:--------:|:--------:|
| 32     | 0.09    | 0.12 | 0.16    | 0.27 |
| 64     | 0.10   | 0.15 | 0.11    | 0.28 |
| 128     | 0.13    | 0.25 | 0.13    | 0.33 |

I'd expect true FP16 on the P100s to give a much better performance boost! Not sure if batch size or other parameter tuning is needed to see this performance boost. Going to get extra benchmarks using larger of layers as well

**Comment by ngimel** [comment]
You should not expect performance boost with fp16, because cudnn LSTM uses fp32 math even for fp16 inputs, but the fact that you are seeing regressions for fp16 points to perf regressions in cublas for SGemmEx calls (when your inputs are fp16, and math is done in fp32). Thanks for reporting.

**Comment by SeanNaren** [comment]
Thanks for that @ngimel are any of the RNNs made to use FP16?

**Comment by ngimel** [comment]
fp16 compute, you mean? Not in cudnn. If you go through LSTMCell, it will likely use Hgemm for matrix-matrix multiplies. But a) for typical LSTM sizes the Hgemms are not nearly 2x performance of Sgemms or SgemmEx b) it is really hard to make your network train using fp16 math.

**Comment by SeanNaren** [comment]
Great thanks for that, will close out the issue :)

**Comment by protoget** [comment]
@ngimel: please comment if my understanding is correct:
1. For CuDNN 6 and CUDA 8, RNN classes always uses computeType=fp32 (seems CuDNN RNN doesn't use computeType? only Conv ops have computeType)
2. For CUDA 9, CUDNN 7 and Volta, can one specify fp16 compute type for CuDNN RNN? (I couldn't find compute type for RNN from the manual.)

**Comment by ngimel** [comment]
1. Correct
2. One can use cudnnSetRNNMatrixMathType to switch between fp32 math and Tensor Core operations https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#tensor_ops

**Comment by posenhuang** [comment]
@ngimel, sorry I couldn't find the discussion in torch (not pytorch). Can CUDA 9, CUDNN 7 and Volta support on LSTM with torch for fp16? If so, can you give me some pointers to doing that in torch? Thanks!

**Comment by ngimel** [comment]
Yes, but you'd need to set cudnnSetRNNMatrixMathType, similarly to how it is done here https://github.com/SeanNaren/pytorch/blob/rnn-volta/torch/backends/cudnn/__init__.py#L260-L263

**Comment by posenhuang** [comment]
@ngimel, it sounds like it's quite involved. It needs to change cutorch? Will it be something on the roadmap for you and your team? Thanks!

**Comment by ngimel** [comment]
No, cutorch does not need to be changed, only RNN.lua in cudnn bindings. Lua torch is not developed anymore, so it's not on the roadmap.

**Comment by posenhuang** [comment]
@ngimel, so to be specific, I should change here:
 [https://github.com/soumith/cudnn.torch/blob/master/RNN.lua#L90](https://github.com/soumith/cudnn.torch/blob/master/RNN.lua#L90) ?
Thanks!

**Comment by ngimel** [comment]
As I've said, CudaTensors are hardcoded in a few places https://github.com/soumith/cudnn.torch/blob/master/RNN.lua#L32-L40, may be somewhere else, and yes, you should also change the descriptor creation, and tensor descriptor creation, as self.datatype is hardcoded to CUDNN_DATA_FLOAT https://github.com/soumith/cudnn.torch/blob/master/RNN.lua#L16

**Comment by ajhool** [comment]
@posenhuang did you ever find success with lua and volta? My lua/torch code is currently taking 10 minutes to configure the volta GPUs, although the actual runtime is extremely fast. I'm not sure what is causing the GPU configuration to run so slowly -- it takes a split second on k80's.

The GPU's configuration occurs in this cutorch init code (i'm pretty sure - https://github.com/torch/cutorch/blob/master/init.lua) and is executed when I call `require cutorch`.

**Comment by ezyang** [comment]
Usually this is because it is compiling PTX on the fly, because your binaries do not have PTX for volta. You will need to rebuild from source if you want to avoid this. We don't support luatorch anymore, try PyTorch :)
