### ISSUE TITLE
Cannot create operator of type 'ReduceL2' on the device 'CUDA' when use caffe2 to run export model

### ISSUE THREAD

**Issue by liangt** [pytorch/pytorch#15395]
## 🐛 Bug

I use torch.nn.functional.normalize method in my model and I want to export it to onnx, and then run it with caffe2. In PyTorch 1.0.0, the problem of "export of expand_as"  is fixed and I can export my model without any problem. However, when I run the export model with caffe2 on GPU, I get an error:

`RuntimeError: [enforce fail at operator.cc:213] op. Cannot create operator of type 'ReduceL2' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing.`

But, when I run the model with caffe2 on CPU, everything goes well.

## To Reproduce

1. define a model which uses torch.nn.functional.normalize method
2. export the model to onnx
3. run it with caffe2 on GPU

`
import onnx
import caffe2.python.onnx.backend as backend
import numpy as np

model = onnx.load('image_embedding_debug.onnx')
rep = backend.prepare(model, device='CUDA:0')
outputs = rep.run(np.random.randn(1, 3, 224, 224).astype(np.float32))
`

## Environment

Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.2 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 375.39
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so
/usr/local/cuda-8.0/lib64/libcudnn.so.6
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch-ignite            0.1.0                     <pip>
[conda] torch                     1.0.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

**Comment by liangt** [comment]
Thanks, I will try. And can you show me some piece of code?

**Comment by tiandunx** [comment]
Sorry to reply late. Sure. Here is my implementation.  It works fine for me right now, but I simplify it, hope it may help you.

**Comment by liangt** [comment]
Thanks, but it seems that the link to the code is missing?

**Comment by tiandunx** [comment]
Sorry for this mistake. Keep me informed if you find any bug please.
`// simple implementation of ReduceL2
template <typename T>
__device__ void warpReduce(volatile T* sdata, int tid) {
  sdata[tid] += sdata[tid + 32];
  sdata[tid] += sdata[tid + 16];
  sdata[tid] += sdata[tid + 8];
  sdata[tid] += sdata[tid + 4];
  sdata[tid] += sdata[tid + 2];
  sdata[tid] += sdata[tid + 1];
}
template <typename T>
__global__ void
kRowwiseL2Reduce(const T* data, T* output, int nrows, int ncols) {
  extern __shared__ T sh[];
  int tid = threadIdx.x;
  // int rid = blockIdx.x; // each block process one row of the matrix
  for (int rid = blockIdx.x; rid < nrows; rid += gridDim.x) {
    const T* x = data + rid * ncols;
    //T* y = output + rid * ncols;
    sh[tid] = 0.0f;
    __syncthreads();
    float tmp = 0.0f;
    for (int j = tid; j < ncols; j += blockDim.x) {
      tmp += x[j] * x[j];
    }
    sh[tid] = tmp;
    __syncthreads();
    for (int s = blockDim.x / 2; s > 32; s >>= 1) {
      if (tid < s) {
        sh[tid] += sh[tid + s];
      }
      __syncthreads();
    }
    if (tid < 32) {
      warpReduce(sh, tid);
    }
    if (tid == 0) {
      output[rid] = sqrtf(sh[tid]);
      // sh[tid] = sqrtf(sh[tid]);
    }
    //__syncthreads();
  }
}
template <typename T>
__global__ void
kColwiseL2Reduce(const T* data, T* output, int nrows, int ncols) {
  extern __shared__ T sh[];
  int tid = threadIdx.x;
  // int rid = blockIdx.x; // each block process one row of the matrix
  for (int cid = blockIdx.x; cid < ncols; cid += gridDim.x) {
    //const T* x = data + rid * ncols;
    //T* y = output + cid * ncols;
    sh[tid] = 0.0f;
    __syncthreads();
    T tmp = 0.0f;
    for (int j = tid; j < nrows; j += blockDim.x) {
      tmp += data[j * ncols + cid] * data[j * ncols + cid];
    }
    sh[tid] = tmp;
    __syncthreads();
    for (int s = blockDim.x / 2; s > 32; s >>= 1) {
      if (tid < s) {
        sh[tid] += sh[tid + s];
      }
      __syncthreads();
    }
    if (tid < 32) {
      warpReduce(sh, tid);
    }
    if (tid == 0) {
      output[cid] = sqrtf(sh[tid]);
      // sh[tid] = sqrtf(sh[tid]);
    }
    //__syncthreads();
  }
}


#define CAFFE2_SPECIALIZED_CUDA_REDUCE_L2(T)                                   \
  template <>                                                                  \
  C10_EXPORT void ReduceL2<T, CUDAContext>(                                    \
      const int num_dims,                                                      \
      const int* dims,                                                         \
      const int num_axes,                                                      \
      const int* axes,                                                         \
      const T alpha,                                                           \
      const T* X,                                                              \
      T* Y,                                                                    \
      CUDAContext* context) {                                                  \
    CAFFE_ENFORCE_LE(num_axes, num_dims);                                      \
    std::vector<int> Y_dims_vector(dims, dims + num_dims);                     \
    for (int i = 0; i < num_axes; ++i) {                                       \
      Y_dims_vector[axes[i]] = 1;                                              \
    }                                                                          \
    const int* X_dims = dims;                                                  \
    const int* Y_dims = Y_dims_vector.data();                                  \
    const int X_size =                                                         \
        std::accumulate(X_dims, X_dims + num_dims, 1, std::multiplies<int>()); \
    const int Y_size =                                                         \
        std::accumulate(Y_dims, Y_dims + num_dims, 1, std::multiplies<int>()); \
    if (X_size == 0) {                                                         \
      Set<T, CUDAContext>(Y_size, 0, Y, context);                              \
      return;                                                                  \
    }                                                                          \
    if (alpha == T(0)) {                                                       \
      Set<T, CUDAContext>(Y_size, 0, Y, context);                              \
      return;                                                                  \
    }                                                                          \
    if (std::equal(X_dims, X_dims + num_dims, Y_dims)) {                       \
      Abs<T, CUDAContext>(X_size, X, Y, context);                              \
      Scale<T, T, CUDAContext>(Y_size, alpha, Y, Y, context);                  \
      return;                                                                  \
    }                                                                          \
    int rows;                                                                  \
    int cols;                                                                  \
    if (utils::IsRowwiseReduce(num_dims, X_dims, Y_dims, &rows, &cols)) {      \
      kRowwiseL2Reduce<T>                                                      \
          <<<CAFFE_GET_BLOCKS(rows),                                           \
             CAFFE_CUDA_NUM_THREADS,                                           \
             sizeof(T) * CAFFE_CUDA_NUM_THREADS,                               \
             context->cuda_stream()>>>(X, Y, rows, cols);                      \
      return;                                                                  \
    }                                                                          \
    if (utils::IsColwiseReduce(num_dims, X_dims, Y_dims, &rows, &cols)) {      \
      kColwiseL2Reduce<T>                                                      \
          <<<CAFFE_GET_BLOCKS(cols),                                           \
             CAFFE_CUDA_NUM_THREADS,                                           \
             sizeof(T) * CAFFE_CUDA_NUM_THREADS,                               \
             context->cuda_stream()>>>(X, Y, rows, cols);                      \
      return;                                                                  \
    }                                                                          \
    int pre;                                                                   \
    int mid;                                                                   \
    int nxt;                                                                   \
    if (utils::IsBothEndsReduce(num_dims, X_dims, Y_dims, &pre, &mid, &nxt)) { \
      LOG(FATAL) << "Currently ReduceL2 only supports row/col wise reduce";    \
      return;                                                                  \
    }                                                                          \
    LOG(FATAL) << "Currently ReduceL2 only supports row/col wise reduce";      \
  }
CAFFE2_SPECIALIZED_CUDA_REDUCE_L2(float)`

**Comment by tiandunx** [comment]
In math_gpu.cu, you may insert the code above at tail.

**Comment by pfrendl** [comment]
This hasn't been fixed, has it?
