### ISSUE TITLE
torch.jit.trace() does not support variant length input?

### ISSUE THREAD

**Issue by jamestang0219** [pytorch/pytorch#15391]
I'm using torch.jit.trace to store model, and then load it on libtorch C++ library.

I found it only support input tensor which have the same size as the example inputs tensor in python torch.jit.trace() when the model inference in C++ program.

In another words, libtorch does not support variant length inputs?

thank you for the reply.

**Comment by driazati** [comment]
Certain operations may require the same shape as the example inputs, and data-dependent control flow in tracing is [not supported](https://pytorch.org/docs/stable/jit.html#torch.jit.ScriptModule) (for that you can instead use TorchScript). What is the error text you are seeing?
