### ISSUE TITLE
ndk set CMAKE_CXX_COMPILER_VERSION conflict with MiscCheck.cmake

### ISSUE THREAD

**Issue by gromzhu** [pytorch/pytorch#15427]
## 🐛 Bug

ndk set CMAKE_CXX_COMPILER_VERSION conflect with MiscCheck.cmake
so can't run the build_android.sh 

## To Reproduce

1.scripts/build_android.sh  -DBUILD_BINARY=ON

## Expected behavior
build will interrupt and print messege

 "Please use GCC 6 or higher on Ubuntu 17.04 and higher. "
 "For more information, see: "
  "https://github.com/caffe2/caffe2/issues/1633"

## Environment

ubuntu 18.4
gcc7
ndk r17c

## Additional context
in /android-ndk-r17c/build/cmake/android.toolchain.cmake
it set(CMAKE_CXX_COMPILER_VERSION 3.8)
but in /pytorch/cmake/MiscCheck.cmake
it has code to check if CMAKE_CXX_COMPILER_VERSION is higher than "6.0"
(https://github.com/zdevito/ATen/commit/c3ea3c8aab82f49eec32fbe63fd68ecfb972cf89)
it conflict

**Comment by FunmiKesa** [comment]
This worked for me 

./scripts/build_android.sh -DBUILD_BINARY=ON -DANDROID_TOOLCHAIN=clang -DCMAKE_CXX_COMPILER=/opt/android/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -DCMAKE_C_COMPILER=/opt/android/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

**Comment by VitalyFedyunin** [comment]
Going to be fixed in #15509

**Comment by soumith** [comment]
Fixed on master via @ljk53 's PRs
