### ISSUE TITLE
libtorch, register_parameter fails

### ISSUE THREAD

**Issue by slaweks17** [pytorch/pytorch#15420]
Hi,
I try to execute
register_parameter("w_x", torch::rand({4,2}), true);
but this causes
Microsoft C++ exception: c10::Error at memory location 0x00000024CF115020

Under Windows 10, Visual Studio 2017, Python 1.0.
BTW, a lot of warnings during compilation, is it expected?

Cheers,
Slawek

**Comment by syshensyshen** [comment]
i get the crash lines code as fallows:

  auto& base_module = children_.insert(std::move(name), std::move(module));

and error is: vector subscript out of range

**Comment by syshensyshen** [comment]
it seems like c plusplus right value error, visual stidio lack of support for this？

**Comment by peterjc123** [comment]
Are you using a Debug build? Please switch to Release instead.

**Comment by goldsborough** [comment]
Yes we are noticing some issues with the Debug build which go away with Release. You can pass `-DCMAKE_BUILD_TYPE=Release` or `-DCMAKE_BUILD_TYPE=RelWithDebInfo` (which preserves debug symbols) to the CMake command to change the build mode when using CMake.

**Comment by slaweks17** [comment]
Hi, thanks. But I really want to debug my code :-) 
RelWithDebInfo is not the same as Debug.

**Comment by zlinwei** [comment]
> Yes we are noticing some issues with the Debug build which go away with Release. You can pass `-DCMAKE_BUILD_TYPE=Release` or `-DCMAKE_BUILD_TYPE=RelWithDebInfo` (which preserves debug symbols) to the CMake command to change the build mode when using CMake.

Hi, It works when I use Rel, but why Debug build has this error?  If I compile the pytorch myself, will this problem still occur?

**Comment by peterjc123** [comment]
@zlinwei Are you using the debug version on pytorch.org when we switch to the debug configuration?

**Comment by vladimir-aubrecht** [comment]
@slaweks17 I couldn't reproduce same issue with latest versions of stack and ticket is stale for some time, so I am closing it. Please create new ticket if problem is still relevant with newest versions.

**Comment by Z-XQ** [comment]
> Are you using a Debug build? Please switch to Release instead.

Thanks a lot. It works for me.
