### ISSUE TITLE
Incompatible argument for IntList type

### ISSUE THREAD

**Issue by zzd1992** [pytorch/pytorch#15434]
I work on PyTorch1.0.
I build c++ extensions based on the code of Aten.
The input argument of the original c++ function should be `IntList` type.
When I call this function in Python, I pass a Python list to this function.
However, it raises an "Incompatible argument" error.
How to match `IntList` type in Python?

**Comment by kris-singh** [comment]
Maybe this helps https://github.com/pytorch/extension-cpp/issues/19

**Comment by ngimel** [comment]
Closing due to age
