### ISSUE TITLE
Distributed operations fail when computational graph is different across processes

### ISSUE THREAD

**Issue by ducksoup** [pytorch/pytorch#15435]
## Potential 🐛 Bug

When a dynamic network containing distributed operations such as `distributed.all_reduce` is executed with `DistributedDataParallel`, the distributed operations will fail after the first forward / backward pass.
When the back-end is `gloo`, this will take the form of an `'gloo::EnforceNotMet'` error being thrown, while with `nccl` there will be a deadlock.

## To Reproduce

```python
import argparse

import torch
import torch.nn as nn
import torch.distributed as distributed
import torch.autograd as autograd


class TestFunction(autograd.Function):
    @staticmethod
    def forward(ctx, x):
        print("forward_start")
        distributed.all_reduce(x, distributed.ReduceOp.SUM)
        torch.cuda.synchronize()
        print("forward_done")
        return x
    
    @staticmethod
    def backward(ctx, dx):
        print("backward_start")
        distributed.all_reduce(dx, distributed.ReduceOp.SUM)
        torch.cuda.synchronize()
        print("backward_done")
        return dx


class TestModule(nn.Module):
    def forward(self, x):
        return TestFunction.apply(x)


class TestNet(nn.Module):
    def __init__(self, rank):
        super(TestNet, self).__init__()
        self.rank = rank
        self.mod1 = nn.Conv2d(4, 4, 1)
        self.mod2 = TestModule()
        self.mod3 = nn.Conv2d(4, 4, 1)
    
    def forward(self, x):
        x = self.mod1(x)
        x = self.mod2(x)
        if self.rank == 0:
            x = self.mod3(x)
        return x


parser = argparse.ArgumentParser()
parser.add_argument("--local_rank", type=int)
args = parser.parse_args()
    
distributed.init_process_group(backend='nccl', init_method='env://') # backend='gloo' also fails
device_id, device = args.local_rank, torch.device(args.local_rank)
rank = distributed.get_rank()
torch.cuda.set_device(device_id)

net = TestNet(rank).cuda(device)
net = nn.parallel.DistributedDataParallel(net, device_ids=[device_id], output_device=device_id)
net.train()
    
for i in range(100):    
    x = torch.randn(4, 4, 4, 4).cuda()
    x = net(x)
    x.mean().backward()
```

Here `TestFunction` is a simple function that performs `all_reduce` both in the forward and the backward. This function is then wrapped into `TestModule`. `TestNet` contains two convolutions and a `TestModule`, but the second convolution is only called from the process with `rank == 0`. The network is wrapped in `DistributedDataParallel`, and the default process group is initialized as per pytorch documentation. The loop at the end of the script performs forward / backward passes with random input data.

To reproduce the issue simply launch the script with:
`python -m torch.distributed.launch --nproc_per_node=2 test.py`

This will print:
```
forward_start
forward_start
forward_done
forward_done
backward_start
backward_start
backward_done
backward_done
forward_start
forward_start
```
then, depending on the back-end it will either remain stuck in a deadlock (nccl) or print an error message and crash (gloo).

Note that this can be reproduced with any number of `nproc_per_node` (we tested from 2 to 8).

## Expected behavior

The distributed operations should be able to complete properly, since they are always called by all processes, in the same order and with the same input data shapes.
The fact that the rest of the network being different has an effect on `all_reduce` is definitely unexpected and doesn't seem to be documented anywhere.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 396.37
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/lib64/libcudnn.so.7.2.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  
[conda] cuda92                    1.0                           0    pytorch
[conda] mkl                       2018.0.3                      1  
[conda] mkl_fft                   1.0.6            py37h7dd41cf_0  
[conda] mkl_random                1.0.1            py37h4414c95_1  
[conda] pytorch                   1.0.0           py3.7_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by ducksoup** [comment]
Additional note: the same thing also happens if one replaces `all_reduce` with `barrier`. In general, any distributed synchronization point seems to trigger this.

**Comment by ducksoup** [comment]
I did some additional tests to better pinpoint where the deadlock occurs.
By modifying `TestFunction` as follows:
```python
class TestFunction(autograd.Function):
    @staticmethod
    def forward(ctx, x):
        torch.cuda.synchronize()
        print("forward_start")
        distributed.all_reduce(x)
        torch.cuda.synchronize()
        print("forward_done")
        return x
    
    @staticmethod
    def backward(ctx, dx):
        torch.cuda.synchronize()
        print("backward_start")
        distributed.all_reduce(dx)
        torch.cuda.synchronize()
        print("backward_done")
        return dx
```
and attaching gdb to the running processes, I can see that they are both stuck in the second `torch.cuda.synchronize()` call of the forward.

I guess this could mean that `distributed.all_reduce(x)` launches some kernel on the GPU that never terminates?

**Comment by teng-li** [comment]
@ducksoup  `DustrubutedDataParallel` currently does not support conditional graph, which makes the graph different across different ranks. We are planning on adding this support soon.

**Comment by ducksoup** [comment]
@teng-li thanks for your answer, this confirms what I also guessed by digging into `DistributedDataParallel`'s internal code in the past couple of days. For now I was able to work around the issue by forcing "fake" backward passes through the conditional part of the graph, but I'm looking forward to proper support for conditional execution!

I'm closing the issue for now.
