### ISSUE TITLE
Type Conversions

### ISSUE THREAD

**Issue by Olamyy** [pytorch/pytorch#15436]
## 🐛 Bug

I'm quite new to pytorch so I'm not exactly sure if this is a bug or just an error on my end.

I'm attempting to build a simple LogisticRegression Module on the `make_classification` dataset in sklearn but for some reason, I keep getting this.

> RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #2 'mat2'

I've tried to convert the both my X and y variables to `double` but it still seems to think it's float for some reason.

## To Reproduce

```
X, y = make_classification(n_samples=60000,n_features=10, n_redundant=0, n_informative=2)
```

```
X_train,y_train, X_test, y_test = train_test_split(X, y, stratify=y, random_state=42)
X_train = Variable(torch.from_numpy(X_train)).double()
y_train = Variable(torch.from_numpy(y_train)).double()
X_test = Variable(torch.from_numpy(X_test)).double()
y_test = Variable(torch.from_numpy(y_test)).double()
```

```
input_dim = 40000
output_dim = 2
criterion = nn.CrossEntropyLoss()
learning_rate = 0.001
batch_size = 100
n_iters = 3000
num_epochs = int(n_iters / (len(X_train) / batch_size))

model = SingleLayeredNetwork(input_dim, output_dim)
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

class SingleLayeredNetwork(nn.Module):
    def __init__(self, input_dimension, output_dimension):
        super(SingleLayeredNetwork, self).__init__()
        self.layer = nn.Linear(input_dimension, output_dimension)

    def forward(self, x):
        out = self.layer(x)
        return out


iter = 0
for epoch in range(num_epochs):
    for train, test in zip(X_train, y_train):
        print(train.dtype)
        print(torch.typename(train))
        optimizer.zero_grad()
        
        outputs = model(train)
        loss = criterion(outputs, test)
        
        loss.backward()

        # Updating parameters
        optimizer.step()

        iter += 1

        if iter % 500 == 0:
            # Calculate Accuracy         
            correct = 0
            total = 0
            # Iterate through test dataset
            for tra, tes in zip(X_test, y_test):
                # Load images to a Torch Variable
                tra = tra

                # Forward pass only to get logits/output
                outputs = model(train)

                # Get predictions from the maximum value
                # 100 x 1
                _, predicted = torch.max(train, 1)

                # Total number of labels
                total += labels.size(0)

                # Total correct predictions
                correct += (predicted == test).sum()

            accuracy = 100 * correct.item() / total

            # Print Loss
            print('Iteration: {}. Loss: {}. Accuracy: {}'.format(iter, loss.item(), accuracy))


```

The error generated is:

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-122-c1edd1a76c76> in <module>
>      10         optimizer.zero_grad()
>      11 
> ---> 12         outputs = model(train)
>      13         loss = criterion(outputs, test)
>      14 
> 
> ~/miniconda3/envs/mlbook/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     487             result = self._slow_forward(*input, **kwargs)
>     488         else:
> --> 489             result = self.forward(*input, **kwargs)
>     490         for hook in self._forward_hooks.values():
>     491             hook_result = hook(self, input, result)
> 
> <ipython-input-117-fca446c51ad3> in forward(self, x)
>       5 
>       6     def forward(self, x):
> ----> 7         out = self.layer(x)
>       8         return out
> 
> ~/miniconda3/envs/mlbook/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     487             result = self._slow_forward(*input, **kwargs)
>     488         else:
> --> 489             result = self.forward(*input, **kwargs)
>     490         for hook in self._forward_hooks.values():
>     491             hook_result = hook(self, input, result)
> 
> ~/miniconda3/envs/mlbook/lib/python3.6/site-packages/torch/nn/modules/linear.py in forward(self, input)
>      65     @weak_script_method
>      66     def forward(self, input):
> ---> 67         return F.linear(input, self.weight, self.bias)
>      68 
>      69     def extra_repr(self):
> 
> ~/miniconda3/envs/mlbook/lib/python3.6/site-packages/torch/nn/functional.py in linear(input, weight, bias)
>    1352         ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
>    1353     else:
> -> 1354         output = input.matmul(weight.t())
>    1355         if bias is not None:
>    1356             output += torch.jit._unwrap_optional(bias)
> 
> RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #2 'mat2'

## Expected behavior
Train and test the data on the network

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.3
GCC version: Could not collect
CMake version: version 3.13.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.0)
[pip] numpydoc (0.7.0)
[pip] torch (1.0.0)
[pip] torchvision (0.2.1)
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.1             hfbd8650_4
[conda] mkl-service               1.1.2            py36h7ea6df4_4
[conda] pytorch                   1.0.0                   py3.6_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch

## Additional context

When I attempt to check the datatype at each point, I get `torch.float64` and 
`torch.DoubleTensor` respectively.

**Comment by soumith** [comment]
@ChunML answers the above question.

In the future if you have doubts or questions, reach out at https://discuss.pytorch.org
