### ISSUE TITLE
No helpful error message for convolution with too small input

### ISSUE THREAD

**Issue by mdraw** [pytorch/pytorch#15446]
## 🐛 Bug

When performing convolution on inputs that are too small for the given convolution kernel, no useful error message is provided.

## To Reproduce

Code examples for CUDA and CPU (file paths in tracebacks are shortened):

```
>>> import torch
>>> # On CUDA
>>> x = torch.randn(1, 1, 2, 2, device='cuda')
>>> torch.nn.Conv2d(1, 2, 3).to('cuda')(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
>>> # Equivalent code on CPU
>>> x = torch.randn(1, 1, 2, 2)
>>> torch.nn.Conv2d(1, 2, 3)(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: std::exception
```

This behavior is not limited to `Conv2d`, it also applies to some other modules (e.g. `Conv1d`).

## Expected behavior

It would be nice if running the code above caused a more descriptive error message that provides a hint what the user is doing wrong here." "RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM" and especially "std::exception" are not helpful.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 410.73
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda100                   1.0                           0    pytorch
[conda] pytorch                   1.0.0           py3.6_cuda10.0.130_cudnn7.4.1_1  [cuda100]  pytorch

**Comment by Ridhwanluthra** [comment]
any progress on this?

**Comment by colesbury** [comment]
The error message with CUDA is also confusing:

```
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
```

**Comment by hikjik** [comment]
Hi, I'm new to pytorch and would like to start contributing. If the issue is still open, can I take a look at this and try to fix it?

**Comment by soumith** [comment]
this is foxed on master:

```
RuntimeError: Calculated padded input size per channel: (2 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size
```

**Comment by rotem154154** [comment]
> this is fixed on master:
> 
> ```
> RuntimeError: Calculated padded input size per channel: (2 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size
> ```

i'm getting the same No helpful error message, could you please explain how to fix it so it will be helpful like you got? thanks

**Comment by Dhawgupta** [comment]
Yeah I am also getting the same error, in my case the kernel size is same as the input size, sadly it had been working earlier but now its not.
```
File "/home1/tulika/anaconda2/envs/pt/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: std::exception
```

**Comment by mdraw** [comment]
@rotem154154 @Dhawgupta I can confirm that there is now a meaningful error message on the master branch (unreleased). Perhaps you are running a released version of PyTorch? The fix is currently only available in nightly versions but will probably land in the PyTorch 1.1.0 release, which is expected end of this month IIRC.
