### ISSUE TITLE
torch.eq_() get wrong result in 1.0.0

### ISSUE THREAD

**Issue by pallashadow** [pytorch/pytorch#15464]
## 🐛 Bug

>>> a = torch.Tensor([1,2,3])
>>> b = torch.Tensor([2,2,2])
>>> c = a.eq(b) # get correct result in v1.0.0
>>> c
tensor([0, 1, 0], dtype=torch.uint8) # expected behavior
>>> a.eq_(b) # get wrong result in v1.0.0. correct in v0.4.0
tensor([0., 1., 1.])

 - PyTorch Version (e.g., 1.0): stable 1.0 installed from "conda install pytorch torchvision -c pytorch"
 - OS (e.g., Linux): Ubuntu 16.04
 - Python version: python 3.7

**Comment by surgan12** [comment]
the fault is here https://github.com/pytorch/pytorch/blob/f52f68bcf9fa490578539fd42c3e050bd5a5f68a/aten/src/ATen/native/LegacyDefinitions.cpp#L114

**Comment by surgan12** [comment]
i think the problem is here
https://github.com/pytorch/pytorch/blob/f52f68bcf9fa490578539fd42c3e050bd5a5f68a/aten/src/ATen/native/LegacyDefinitions.cpp#L114
