### ISSUE TITLE
Caffe2 Int8Conv Y description changes during rebuild

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#15462]
During each rebuild the operator output description for `Int8Conv`:`Y` changes to a different path:
 
```import caffe2.python.core
op_schema = caffe2.python.workspace.C.OpSchema.get('Int8Conv')
for output_desc in op_schema.output_desc:
    if output_desc[0] == 'Y':
        print(output_desc[1])
```

`/private/var/folders/n9/387w3nks67lgpncz_ty30t1w0000gn/T/pip-req-build-w_0ceff7/caffe2/operators/quantized/int8_conv_op.cc`.

**Expected**
Description string stays the same for each build so rerunning doc generators will create the same result.

**Actual**
Each rebuild returns a different string.

@Maratyszcza

**Comment by yinghai** [comment]
Is it ok the case for `Int8Conv`? How about other ops?

**Comment by Maratyszcza** [comment]
cc @harouwu who wrote the schema for this operator

**Comment by lutzroeder** [comment]
> Is it just the case for `Int8Conv`? How about other ops?

Other `Int8` operators are having issues too but the errors are different. See #13229 for example.
