### ISSUE TITLE
JIT Tensor .to not functioning, confusing error message

### ISSUE THREAD

**Issue by Coolnesss** [pytorch/pytorch#15478]
## 🐛 Bug

When using `torch.jit.script_method` or `torch.jit.script` moving Tensors to GPU / CPU via the `.to()` method does not function. Also, the resulting error message might be wrong?

## To Reproduce

This script
```python
import torch

@torch.jit.script
def test(device: str):
    torch.ones(1,2,3).to(device)

test("cpu")
```

Run with `PYTORCH_JIT=0 python jittest.py`, works as expected, and `PYTORCH_JIT=1 python jittest.py` gives error

```
Traceback (most recent call last):
  File "jittest.py", line 4, in <module>
    def test(device: str):
  File "/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 691, in script
    _jit_script_compile(mod, ast, _rcb, get_default_args(fn))
RuntimeError:
arguments for call are not valid:

  for operator aten::to(Tensor self, Tensor other, bool non_blocking=<default>, bool copy=<default>) -> Tensor:
  expected a value of type Tensor for argument 'other' but found string
  @torch.jit.script
  def test(device: str):
      torch.ones(1,2,3).to(device)
                           ~~~~~~ <--- HERE

  for operator aten::to(Tensor self, int dtype, bool non_blocking=<default>, bool copy=<default>) -> Tensor:
  expected a value of type int for argument 'dtype' but found string
  @torch.jit.script
  def test(device: str):
      torch.ones(1,2,3).to(device)
                           ~~~~~~ <--- HERE

  for operator aten::to(Tensor self, Device device, int dtype, bool non_blocking=<default>, bool copy=<default>) -> Tensor:
  argument dtype not provided.
  @torch.jit.script
  def test(device: str):
      torch.ones(1,2,3).to(device)
      ~~~~~~~~~~~~~~~~~~~~ <--- HERE

  for operator aten::to(Tensor self, *, int dtype=<default>, int layout=<default>, Device device=<default>, bool non_blocking=<default>, bool copy=<default>) -> Tensor:
  expected at most 0 arguments but found 1 positional arguments.
  @torch.jit.script
  def test(device: str):
      torch.ones(1,2,3).to(device)
      ~~~~~~~~~~~~~~~~~~~~ <--- HERE

for call at:
@torch.jit.script
def test(device: str):
    torch.ones(1,2,3).to(device)
    ~~~~~~~~~~~~~~~~~~~~ <--- HERE
```
## Expected behavior
The code should run without error

## Environment

Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.13.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.3                      1
[conda] mkl-service               1.1.2            py37h6b9c3cc_5
[conda] mkl_fft                   1.0.6            py36hb8a8100_0
[conda] mkl_random                1.0.1            py36h5d10147_1
[conda] pytorch                   1.0.0                   py3.6_1    pytorch
[conda] pytorch-nightly           1.0.0.dev20181121         py3.6_0    pytorch
[conda] torchtext                 0.3.1                     <pip>
[conda] torchvision               0.2.1                      py_2    pytorch

## Additional context
Why would `.to` expect a Tensor as an argument?

**Comment by highker** [comment]
@Coolnesss try `device=device`; for example:
```python
@torch.jit.script
def test(device):
    # type: (str) -> None
    torch.ones(1,2,3).to(device=device)

test("CPU")

**Comment by highker** [comment]
@Coolnesss, the syntaxes are slightly different. For script functions, we explicitly distinguish inputs (tensors, tuples, lists, etc) and [attributes](https://pytorch.org/docs/stable/tensor_attributes.html). For attributes, named parameters (e.g., `device=device`) are enforced.
