### ISSUE TITLE
GPU allocated memory is not released

### ISSUE THREAD

**Issue by EpicDima** [pytorch/pytorch#15482]
I create CNN to work with images. This network is of the U-Net type for segmentation, which by its architecture saves intermediate calculations. This leads to the conclusion that with a small amount of memory you need to either reduce the size of the image, the number of layers, the size of the batch.
![default](https://user-images.githubusercontent.com/37583380/50356634-ccf4b080-0563-11e9-824a-44f7ef669087.png)
If you give the network a single image of a small size, the memory becomes slightly larger, which is logical.
![default](https://user-images.githubusercontent.com/37583380/50356532-5d7ec100-0563-11e9-95d2-9c7e27bd1558.png)
When you restart with the same image, the amount of allocated memory does not change, only the occupied part of the memory cache increases.
![default](https://user-images.githubusercontent.com/37583380/50356677-ed246f80-0563-11e9-8595-8eb10b651868.png)
Error text:
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-8ba8cee8f3f0> in <module>()
      1 test = np.random.sample([1, 3, 1280, 1280]) * 0.5
----> 2 out = net(torch.FloatTensor(test).to(device))
      3 out.shape

E:\Python\Anaconda\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

<ipython-input-12-552150536d36> in forward(self, x)
     50         x = self.maxpool(d1)
     51 
---> 52         d2 = self.down2(x)
     53         x = self.maxpool(d2)
     54 

E:\Python\Anaconda\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

E:\Python\Anaconda\lib\site-packages\torch\nn\modules\container.py in forward(self, input)
     90     def forward(self, input):
     91         for module in self._modules.values():
---> 92             input = module(input)
     93         return input
     94 

E:\Python\Anaconda\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

E:\Python\Anaconda\lib\site-packages\torch\nn\modules\activation.py in forward(self, input)
     48     @weak_script_method
     49     def forward(self, input):
---> 50         return F.threshold(input, self.threshold, self.value, self.inplace)
     51 
     52     def extra_repr(self):

E:\Python\Anaconda\lib\site-packages\torch\nn\functional.py in threshold(input, threshold, value, inplace)
    838         result = _VF.threshold_(input, threshold, value)
    839     else:
--> 840         result = _VF.threshold(input, threshold, value)
    841     return result
    842 

RuntimeError: CUDA out of memory. Tried to allocate 100.00 MiB (GPU 0; 2.00 GiB total capacity; 1.34 GiB already allocated; 5.20 MiB free; 12.75 MiB cached)

After a large image again give the network image smaller and again get the same error:
![default](https://user-images.githubusercontent.com/37583380/50356722-2230c200-0564-11e9-8fba-54855c20de9f.png)
Things with memory become like this:
![default](https://user-images.githubusercontent.com/37583380/50356785-67ed8a80-0564-11e9-8a9c-895b453410ba.png)

Without restarting jupyter notebook in which I work, the memory does not clear out.

**Comment by XiaomoWu** [comment]
I also have this annoying problem. The memory just doesn't get cleared out even I `del` every possible object that could live in the GPU memory. The only solution, as stated by @EpicDima , is to restart the Jupyter notebook.

**Comment by fmassa** [comment]
This is expected -- we use a memory caching allocator for the GPU, because `cudaFree` implies a synchronization point, which would make the whole program much slower.

If you want to free the cached memory, you can call `torch.cuda.empty_cache()`
