### ISSUE TITLE
vs2015 + windows 10 Error C4146

### ISSUE THREAD

**Issue by HannH** [pytorch/pytorch#15497]
## 🐛 Bug
Get error C4146 in release mode with visual studio 2015.
 Error "C4146: unary minus operator applied to unsigned type, result still unsigned"
it occur at libtorch\include\c10/Half.h(396):
```
 if (!limit::is_signed && std::numeric_limits<From>::is_signed) {
    // allow for negative numbers to wrap using two's complement arithmetic.
    // For example, with uint8, this allows for `a - b` to be treated as
    // `a + 255 * b`.
    return f > limit::max() ||
        (f < 0 && -static_cast<uint64_t>(f) > limit::max());<----- error occored here
  } else {
    return f < limit::lowest() || f > limit::max();
  }
```

## To Reproduce

1.wirter example code from https://pytorch.org/tutorials/advanced/cpp_export.html with vs2015
2.select release mode \ x64 architecture 
3.import torch.lib and torch\include
4.generate than get error

## environment
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 教育版
GCC version: Could not collect
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: Quadro K2200
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 388.19
cuDNN version: Probably one of the following:
D:\lib\CUDA\v9.1\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     1.0.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

## Additional context
I delete the '-' and then build sucessfully, so it is the last error.

**Comment by cuixing158** [comment]
thanks @peterjc123 ,I encountered the same problem as the landlord, but then solved it according to your fix solution. it does't occur error
