### ISSUE TITLE
 Feature request: sparse x sparse -> sparse

### ISSUE THREAD

**Issue by fourpartswater** [pytorch/pytorch#1550]
I would like to implement MCL https://micans.org/mcl/index.html in pytorch. 

It relies on sparse x sparse -> sparse

Thanks!

Peter

**Comment by soumith** [comment]
do you mean SxS multiply or matrix-multiply?

**Comment by fmassa** [comment]
I think sparse matrix-matrix multiply yielding sparse matrices is difficult to implement efficiently, because it's not trivial to estimate which indices in the result matrix are non-zero. But maybe we could leverage existing implementations, if there are any?

**Comment by soumith** [comment]
probably from csparse and cusparse, which both support sparse gemm

**Comment by pavanky** [comment]
I know [cusparse](http://docs.nvidia.com/cuda/cusparse/#cusparse-lt-t-gt-csrgemm) has this. I am not familiar with csparse.

**Comment by pavanky** [comment]
But even cusparse seems to be generating a dense matrix as the output. So I am not sure if there are any libraries that support what @fourpartswater is asking.

**Comment by apaszke** [comment]
Isn't `csrgemm` computing a sparse output matrix?

**Comment by pavanky** [comment]
@apaszke you are right. I don't know how I misread that..

**Comment by fourpartswater** [comment]
I would be very happy to help out on this if I can (bearing in mind I am new to pytorch...)

**Comment by soumith** [comment]
@fourpartswater we're definitely down for a Pull Request :)

**Comment by fourpartswater** [comment]
What is the best bit of current code to act as a template to build  this?

**Comment by apaszke** [comment]
You need to implement it in THS/THCS (for CPU and CUDA tensors) and expose it to Python. I don't think we link with cblas at the moment so I guess we could leave the CPU function that only raises an error that it's no implemented (using `THError`). Here are some pointers:
* [Implementation of sparse dense multiplication in C backend](https://github.com/pytorch/pytorch/blob/0f458ee3c498444c3519841b7300cb9e7e6f67f1/torch/lib/THCS/generic/THCSTensorMath.cu#L43-L153)
* [Its Python bindings](https://github.com/pytorch/pytorch/blob/743e4894d2865108dc0ea2a1f344d9f34eb2b29d/torch/csrc/generic/methods/SparseTensor.cwrap#L201-L215)

**Comment by weiyangfb** [comment]
closing this because it is unclear which op is needed: mm(S, S) or mul(S, S), where the later is already implemented. Please reopen this or create a new issue if needed in the future.

**Comment by jhonygiraldo** [comment]
Hi, is there any update of torch.mm(S,S) in PyTorch? I am trying to perform matrix multiplication of two sparse matrices, and I get the following error "RuntimeError: sparse tensors do not have strides". I am using PyTorch 1.8.0+cu111.

**Comment by jaynanavati-az** [comment]
Is there any update of torch.mm(S,S) in PyTorch?
