### ISSUE TITLE
Use CuDNN when we are doing Depthwise Convolution, when they get fast

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#15513]
## 🚀 Feature

CuDNN 7 has support for Depthwise convolutions.

However, according to @ngimel [here](https://github.com/pytorch/pytorch/issues/1708#issuecomment-384015108), those aren't faster than PyTorch's kernels on average.

This tracking task ensures that once CuDNN kernels get faster (and maybe they add support for group convolutions), we switch the internals to dispatch to them

cc @SsnL

**Comment by pbelevich** [comment]
Tested #18631 with cuDNN 7.6.0 - no difference

**Comment by yaysummeriscoming** [comment]
@pbelevich, I was able to reproduce the speedup on depthwise convolution, but only saw ~10% on MobileNet V2.  Did you use FP16 and a Volta or Turing card?

Here is the PR where this feature was implemented.  It includes some test code you can use for benchmarking:
https://github.com/pytorch/pytorch/pull/22302

**Comment by XIEYUNSCUT** [comment]
> ## 🚀 Feature
> CuDNN 7 has support for Depthwise convolutions.
> 
> However, according to @ngimel [here](https://github.com/pytorch/pytorch/issues/1708#issuecomment-384015108), those aren't faster than PyTorch's kernels on average.
> 
> This tracking task ensures that once CuDNN kernels get faster (and maybe they add support for group convolutions), we switch the internals to dispatch to them
> 
> cc @SsnL

According to cudnn v7.6.3 release notes，the latest cudnn seems to support depth-wise convolution well。can you check it？thank you very much!

**Comment by ngimel** [comment]
#22302 enables cudnn for depthwise separable convolutions on Volta and Turing cards with fp16 inputs. Cudnn kernels for other cases are not very fast.

**Comment by 13952522076** [comment]
So, if there is any method to speed up group convolution in PyTorch? Thanks a lot.

**Comment by 13952522076** [comment]
> So, if there is any method to speed up group convolution in PyTorch? Thanks a lot.

I have tested cuDNN 7.6.3 + PyTorch1.3, there is almost no improvement for ResNeXt.

**Comment by yaysummeriscoming** [comment]
I tested with MobileNet V2 & ShuffleNet V2, saw maybe 10%
