### ISSUE TITLE
`torch.hub` cannot download if branch name starts with `v`

### ISSUE THREAD

**Issue by moskomule** [pytorch/pytorch#15519]
GitHub renames archived zip files of branch or tag whose names start with `vX.Y.zip` to `REPONAME-X.Y.zip`. Thus `torch.hub` cannot find the downloaded files.

For example, https://github.com/pytorch/pytorch/archive/v1.0.0.zip is automatically renamed to `pytorch-1.0.0.zip`, not `pytorch-v1.0.0.zip` as `torch.hub` expects.

**Comment by zou3519** [comment]
cc @ailzhang

**Comment by moskomule** [comment]
Thanks! I'm not certain if `v` is the only exception.

**Comment by soumith** [comment]
@moskomule the fix is written in a way that we dont rely on special-casing `v`, so we should be good.
