### ISSUE TITLE
Can't open discuss.pytorch.org

### ISSUE THREAD

**Issue by mreeew** [pytorch/pytorch#15515]
Hello!
Can't open discuss.pytorch.org
Tried from Chrome(Version 71.0.3578.98 (Official Build) (64-bit)) and from Safari (Version 12.0.1 (14606.2.104.1.1))
Also tried from 2 different mobile browsers.
Always I get such error:

> This site can’t be reached The connection was reset.
> Try:
> Checking the connection
> Checking the proxy and the firewall
> ERR_CONNECTION_RESET

`ping discuss.pytorch.org ` works well

**Comment by zou3519** [comment]
Try with https maybe? https://discuss.pytorch.org/

**Comment by soumith** [comment]
we cant reproduce this across machines and networks. I think it's your local network settings, maybe proxy settings of your mobile network provider or so.

**Comment by ildarlomov** [comment]
I can not get discuss.pytorch.org via chrome on my mac pro but it is reachable for example by opera

**Comment by Xetd71** [comment]
+

**Comment by jinga-lala** [comment]
Does anyone have a solution to this problem? Whenever I try to access https://discuss.pytorch.org/ it says:

It looks like the webpage at https://discuss.pytorch.org/ might be having issues, or it may have moved permanently to a new web address.

**Comment by sethcoast** [comment]
@jinga-lala I am currently dealing with the same issue. Have been for a couple days now. Located in NYC.

**Comment by mostafa-saad** [comment]
I am suffering from this problem so far for some time!
I can see it on my Ubuntu 18, but not on my Windows 10
So weird

**Comment by haruishi43** [comment]
I also suffered from this for chrome and safari, but restarting my browser solved the issue.

**Comment by Technorocker** [comment]
I am having a close problem with the PyTorch discuss website as well, it loads but I cant click on anything or scroll the page, Its like the whole page is just one big image. I checked out the inspect element feature in the browser and seen this error in the issues tab. Not sure if its related or not. I'm using edge browser

![PyTorch Website Error](https://github.com/pytorch/pytorch/assets/35610201/f5e8f529-24c4-4c03-a16d-0e53c29445a6)
