### ISSUE TITLE
pytorch is crashed, how to solve?

### ISSUE THREAD

**Issue by ismymajia** [pytorch/pytorch#15517]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

#0  0x00007f5e227961d7 in raise () from /lib64/libc.so.6
#1  0x00007f5e227978c8 in abort () from /lib64/libc.so.6
#2  0x00007f5e238d99d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007f5e238d7946 in ?? () from /lib64/libstdc++.so.6
#4  0x00007f5e238d7973 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007f5e238d7be9 in __cxa_rethrow () from /lib64/libstdc++.so.6
#6  0x00007f5e7f2bdb52 in void std::vector<c10::FunctionSchema, std::allocator<c10::FunctionSchema> >::_M_emplace_back_aux<c10::FunctionSchema>(c10::FunctionSchema&&) () from /data/libtorch/lib/libtorch.so.1
#7  0x00007f5e7f2b7fb8 in torch::jit::parseSchema(std::string const&) () from /data/libtorch/lib/libtorch.so.1
#8  0x00007f5e7f2b6f0b in torch::jit::Operator::schema() const () from /data/libtorch/lib/libtorch.so.1
#9  0x00007f5e7f2b8da0 in torch::jit::registerOperator(torch::jit::Operator&&) () from /data/libtorch/lib/libtorch.so.1
#10 0x00007f5e7ee37380 in __static_initialization_and_destruction_0(int, int) [clone .constprop.4594] () from /data/libtorch/lib/libtorch.so.1
#11 0x00007f5e7fb461e3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#12 0x00007f5e7fb3821a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#13 0x0000000000000002 in ?? ()
#14 0x00007ffd9f4acbc0 in ?? ()
#15 0x00007ffd9f4acc10 in ?? ()
#16 0x0000000000000000 in ?? ()

**Comment by yjhjstz** [comment]
+1

**Comment by zou3519** [comment]
Please provide a minimal repro for the crash

**Comment by ismymajia** [comment]
gcc version : 4.8
i use pytorch v1 stable libtorch that  is got from:
![image](https://user-images.githubusercontent.com/17922949/50501577-1e38fe80-0a94-11e9-9146-4668a663c5b7.png)

**Comment by soumith** [comment]
@ismymajia I still dont know what OS you are running on. If you followed our Bug Report template, we wouldn't have had to go back and forth asking you more details!

Run the commands in https://github.com/pytorch/pytorch/issues/new?template=bug-report.md and please paste them below

**Comment by ismymajia** [comment]
fix it when gcc version > 5
