### ISSUE TITLE
install error: calling a __host__ function("std::_Head_base.....) is not allowed

### ISSUE THREAD

**Issue by raninbowlalala** [pytorch/pytorch#15528]
## 🐛 Bug

I use git clone to download the pytorch source code, and use "sudo python setup.py install" to install but I got error like below.

## To Reproduce

1. pip clone ***
2.sudo python setup.py install

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):N/A
 - OS (e.g., Linux):Ubuntu 14.04.5 LTS
 -GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
 -CMake version: version 3.9.1
 - How you installed PyTorch (`conda`, `pip`, source):source
 - Build command you used (if compiling from source):sudo python setup.py install
 - Python version:2.7
 - CUDA/cuDNN version:9.0
 - GPU models and configuration
   GPU 0: GeForce GTX TITAN X
   GPU 1: GeForce GTX TITAN X
 - Any other relevant information:

## Additional context

--
-- ******** Summary ********
-- General:
--   CMake version         : 3.9.1
--   CMake command         : /usr/cmake-3.9.1/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 4.8.4
--   BLAS                  : MKL
--   CXX flags             :  -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized
--   Build type            : Release
--   Compile definitions   : ONNX_NAMESPACE=onnx_torch;USE_GCC_ATOMICS=1;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /usr/lib/python2.7/dist-packages
--   CMAKE_INSTALL_PREFIX  : /home/liufang/venv_dir/pytorch/torch/lib/tmp_install
--
--   TORCH_VERSION         : 1.0.0
--   CAFFE2_VERSION        : 1.0.0
--   BUILD_ATEN_MOBILE     : OFF
--   BUILD_ATEN_ONLY       : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.6
--     Python executable   : /usr/bin/python
--     Pythonlibs version  : 2.7.6
--     Python library      : /usr/lib/libpython2.7.so.1.0
--     Python includes     : /usr/include/python2.7
--     Python site-packages: lib/python2.7/dist-packages
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ASAN              : OFF
--   USE_CUDA              : 1
--     CUDA static link    : 0
--     USE_CUDNN           : ON
--     CUDA version        : 9.0
--     cuDNN version       : 7.0.4
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     cudart library      : /usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
--     cublas library      : /usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a
--     cufft library       : /usr/local/cuda/lib64/libcufft.so
--     curand library      : /usr/local/cuda/lib64/libcurand.so
--     cuDNN library       : /usr/local/cuda/lib64/libcudnn.so.7
--     nvrtc               : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : 0
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FBGEMM            : OFF
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : OFF
--   USE_MKLDNN            : OFF
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : ON
--   USE_NNPACK            : 1
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_QNNPACK           : 1
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : ON
--     USE_MPI             : ON
--     USE_GLOO            : ON
--     USE_GLOO_IBVERBS    : OFF
--   Public Dependencies  : Threads::Threads
--   Private Dependencies : qnnpack;nnpack;cpuinfo;fp16;/usr/lib/libmpi_cxx.so;/usr/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libhwloc.so;gloo;aten_op_header_gen;onnxifi_loader;rt;gcc_s;gcc;dl
-- Configuring done
.......
[ 74%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cuda/caffe2_gpu_generated_Distributions.cu.o
/usr/include/c++/4.8/tuple(264): error: calling a __host__ function("std::_Head_base<(unsigned long)1ul,  ::at::Tensor, (bool)0> ::_Head_base< ::at::Tensor &> ") from a __device__ function("std::_Tuple_impl<(unsigned long)1ul,  ::at::Tensor > ::_Tuple_impl< ::at::Tensor &  , void> ") is not allowed

/usr/include/c++/4.8/tuple(264): error: identifier "std::_Head_base<(unsigned long)1ul,  ::at::Tensor, (bool)0> ::_Head_base< ::at::Tensor &> " is undefined in device code

/usr/include/c++/4.8/tuple(264): error: calling a __host__ function("std::_Head_base<(unsigned long)0ul,  ::at::Tensor, (bool)0> ::_Head_base< ::at::Tensor &> ") from a __device__ function("std::_Tuple_impl<(unsigned long)0ul,  ::at::Tensor,  ::at::Tensor > ::_Tuple_impl< ::at::Tensor &,  ::at::Tensor & , void> ") is not allowed

/usr/include/c++/4.8/tuple(264): error: identifier "std::_Head_base<(unsigned long)0ul,  ::at::Tensor, (bool)0> ::_Head_base< ::at::Tensor &> " is undefined in device code

4 errors detected in the compilation of "/tmp/tmpxft_00007ead_00000000-6_BatchLinearAlgebra.cpp1.ii".
CMake Error at caffe2_gpu_generated_BatchLinearAlgebra.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/liufang/venv_dir/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cuda/./caffe2_gpu_generated_BatchLinearAlgebra.cu.o

make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cuda/caffe2_gpu_generated_BatchLinearAlgebra.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/include/c++/4.8/tuple(264): error: calling a __host__ function("std::_Head_base<(unsigned long)1ul,  ::at::Tensor, (bool)0> ::_Head_base< ::at::Tensor &> ") from a __device__ function("std::_Tuple_impl<(unsigned long)1ul,  ::at::Tensor > ::_Tuple_impl< ::at::Tensor &  , void> ") is not allowed

/usr/include/c++/4.8/tuple(264): error: identifier "std::_Head_base<(unsigned long)1ul,  ::at::Tensor, (bool)0> ::_Head_base< ::at::Tensor &> " is undefined in device code

/usr/include/c++/4.8/tuple(264): error: calling a __host__ function("std::_Head_base<(unsigned long)0ul,  ::at::Tensor, (bool)0> ::_Head_base< ::at::Tensor &> ") from a __device__ function("std::_Tuple_impl<(unsigned long)0ul,  ::at::Tensor,  ::at::Tensor > ::_Tuple_impl< ::at::Tensor &,  ::at::Tensor & , void> ") is not allowed

/usr/include/c++/4.8/tuple(264): error: identifier "std::_Head_base<(unsigned long)0ul,  ::at::Tensor, (bool)0> ::_Head_base< ::at::Tensor &> " is undefined in device code

4 errors detected in the compilation of "/tmp/tmpxft_00007ea3_00000000-6_Activation.cpp1.ii".
CMake Error at caffe2_gpu_generated_Activation.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/liufang/venv_dir/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cuda/./caffe2_gpu_generated_Activation.cu.o

make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cuda/caffe2_gpu_generated_Activation.cu.o] Error 1
/usr/include/c++/4.8/tuple(257): error: calling a __host__ function("std::_Head_base<(unsigned long)0ul,  ::at::Tensor, (bool)0> ::_Head_base") from a __device__ function("std::_Tuple_impl<(unsigned long)0ul,  ::at::Tensor > ::_Tuple_impl") is not allowed

/usr/include/c++/4.8/tuple(257): error: identifier "std::_Head_base<(unsigned long)0ul,  ::at::Tensor, (bool)0> ::_Head_base" is undefined in device code

/usr/include/c++/4.8/tuple(264): error: calling a __host__ function("std::_Head_base<(unsigned long)0ul,  ::at::Tensor, (bool)0> ::_Head_base< ::at::Tensor> ") from a __device__ function("std::_Tuple_impl<(unsigned long)0ul,  ::at::Tensor > ::_Tuple_impl< ::at::Tensor  , void> ") is not allowed

/usr/include/c++/4.8/tuple(264): error: identifier "std::_Head_base<(unsigned long)0ul,  ::at::Tensor, (bool)0> ::_Head_base< ::at::Tensor> " is undefined in device code

4 errors detected in the compilation of "/tmp/tmpxft_00007f66_00000000-6_Distributions.cpp1.ii".
CMake Error at caffe2_gpu_generated_Distributions.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/liufang/venv_dir/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cuda/./caffe2_gpu_generated_Distributions.cu.o

make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cuda/caffe2_gpu_generated_Distributions.cu.o] Error 1
/home/liufang/venv_dir/pytorch/aten/src/ATen/native/cuda/DistanceKernel.cu(30): warning: function "at::native::<unnamed>::dists<scalar_t>::sign [with scalar_t=float]" was declared but never referenced

/home/liufang/venv_dir/pytorch/aten/src/ATen/native/cuda/DistanceKernel.cu(30): warning: function "at::native::<unnamed>::dists<scalar_t>::sign [with scalar_t=double]" was declared but never referenced

make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-fbgemm --use-nnpack --use-mkldnn --use-qnnpack caffe2'

**Comment by raninbowlalala** [comment]
commit 521894c490289dfdd4cd2e812113e028a61c8169

**Comment by jbschlosser** [comment]
Closing as out-of-date; feel free to reopen if this is still an issue in a newer version of PyTorch.
