### ISSUE TITLE
Feature Request: Nested state_dict (OrderedDict) for nested modules

### ISSUE THREAD

**Issue by w9** [pytorch/pytorch#15526]
The `OrderedDict` expored from `module.state_dict()` is currently flattened. It would make weight transferring between different models / different variants of models much easier if the `stat_dict` has a nested structure just like a module does.

For example, imaging you can simply do:

```python
parent_state = torch.load('./parent_module.pt')
child_module = ChildModule()
child_module.load_state_dict(parent_state['child'])
```

instead of manually (and awkwardly) renaming all the keys in the flattened `OrderedDict`.

**Comment by shivam13juna** [comment]
I'd like to work on this issue if moderators can assign me this.

**Comment by soumith** [comment]
We discussed this in the early days, when implementing `state_dict`. The conclusion was that we dont want to complicate the `state_dict` API by adding nesting (or other schemes that were under discussion).
The nesting is already given in the keys of the dict, such as `layer1.layer2.layer3.conv1.weight`, and it's trivial to filter the keys according to the nesting you want.
We wanted to keep it simple and stupid, and let users refilter / reorder as they want.

**Comment by apaszke** [comment]
Also, note that you can traverse the module tree yourself by using `named_modules()` and `named_parameters()`.

**Comment by carlosgmartin** [comment]
In case it helps anyone, here's a helper function:
```python3
def descend(state_dict, prefix):
    return {
        k[len(prefix):]: v
        for k, v in state_dict.items()
        if k.startswith(prefix)
    }
child.load_state_dict(descend(parent_state_dict, 'child.'))
```
