### ISSUE TITLE
RandomSampler length

### ISSUE THREAD

**Issue by jbaron** [pytorch/pytorch#15537]
## 🐛 Bug

The random sampler (torch.utils.data.RandomSampler) allows the user to define how many samples are drawn (when replacement is set to True). However the __len__ method always returns the length of the dataset ad doesn't take this parameter into consideration.

Ideally when the user specifies the num_samples parameter, this value should be returned in the __len__ method (right now the length of the sampler and returned iterator don't match if num_samples is set). 

Since num_samples is anyway set to the length of datasource if not specified explicitly, the following is a simple fix:

```
def __len__(self):
    return self.num_samples
```

Tested with pytorch version 1.0

**Comment by fmassa** [comment]
I think your fix is the right solution, and this indeed seems like a problem in the current code

**Comment by truskovskiyk** [comment]
Hi @fmassa @jbaron ! I can send a PR with a fix if nobody minds

**Comment by jbaron** [comment]
For sure I don't mind and would be grateful.

**Comment by truskovskiyk** [comment]
done, her is PR #15991

**Comment by soumith** [comment]
i'm landing #15991, so closing the issue. Closed via #15991 
Thanks @truskovskiyk
