### ISSUE TITLE
Memory leak in torch.cholesky

### ISSUE THREAD

**Issue by ozzzp** [pytorch/pytorch#15539]
## 🐛 Bug

There exists memory leak of GPU memory in torch.cholesky

## Code

```python
import torch

def main():
    def test_cholesky():
        A = torch.rand([4, 1280, 1280]).cuda()
        H = A.matmul(A.transpose(1, 2)) + torch.eye(1280).cuda()
        decomposition = torch.cholesky(H, upper=False)
        b = torch.rand([4, 1280]).cuda()
        return torch.potrs(b.unsqueeze(2), decomposition, upper=False).squeeze(2), decomposition

    for i in range(10000):
        test_cholesky()
        print(i)


if __name__ == '__main__':
    main()
```

## output

```bash
python: /opt/conda/conda-bld/magma-cuda100_1544135857751/work/interface_cuda/interface.cpp:730: void magma_queue_create_internal(magma_device_t, magma_queue**, const char*, const char*, int): Assertion `queue->dAarray__ != __null' failed.
bash: line 1: 64633 Aborted                 (core dumped) env "PYCHARM_HOSTED"="1" "PYTHONUNBUFFERED"="1" "PYTHONIOENCODING"="UTF-8" "PYCHARM_MATPLOTLIB_PORT"="61780" "JETBRAINS_REMOTE_RUN"="1" "PYTHONPATH"="/home/ubuntu/Unitary Architecture Network:/home/ubuntu/.pycharm_helpers/pycharm_matplotlib_backend" '/home/ubuntu/anaconda3/bin/python' '-u' '/home/ubuntu/Unitary Architecture Network/playground.py'
```

in `nvidia-smi`, the GPU memory is blowed up.

## Environment

```bash
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 410.79
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

**Comment by akahard2dj** [comment]
Hello.
I have checked `pytorch/third_parth/eigen/lapack/cholesky.cpp`.

[line 14 in cholesky.cpp](https://github.com/eigenteam/eigen-git-mirror/blob/f59336cee358f92b959de6a0daf07c4ab2318022/lapack/cholesky.cpp#L14)


```cpp
EIGEN_LAPACK_FUNC(potrf,(char* uplo, int *n, RealScalar *pa, int *lda, int *info))
{
  *info = 0;
        if(UPLO(*uplo)==INVALID) *info = -1;
  else  if(*n<0)                 *info = -2;
  else  if(*lda<std::max(1,*n))  *info = -4;
  if(*info!=0)
  {
    int e = -*info;
    return xerbla_(SCALAR_SUFFIX_UP"POTRF", &e, 6);
  }

  Scalar* a = reinterpret_cast<Scalar*>(pa);
  MatrixType A(a,*n,*n,*lda);
  int ret;
  if(UPLO(*uplo)==UP) ret = int(internal::llt_inplace<Scalar, Upper>::blocked(A));
  else                ret = int(internal::llt_inplace<Scalar, Lower>::blocked(A));

  if(ret>=0)
    *info = ret+1;

  // delete *a is new line
  delete *a;

  return 0;
}
```

[line 41 in cholesky.cpp](https://github.com/eigenteam/eigen-git-mirror/blob/f59336cee358f92b959de6a0daf07c4ab2318022/lapack/cholesky.cpp#L41)
```cpp
EIGEN_LAPACK_FUNC(potrs,(char* uplo, int *n, int *nrhs, RealScalar *pa, int *lda, RealScalar *pb, int *ldb, int *info))
{
  *info = 0;
        if(UPLO(*uplo)==INVALID) *info = -1;
  else  if(*n<0)                 *info = -2;
  else  if(*nrhs<0)              *info = -3;
  else  if(*lda<std::max(1,*n))  *info = -5;
  else  if(*ldb<std::max(1,*n))  *info = -7;
  if(*info!=0)
  {
    int e = -*info;
    return xerbla_(SCALAR_SUFFIX_UP"POTRS", &e, 6);
  }

  Scalar* a = reinterpret_cast<Scalar*>(pa);
  Scalar* b = reinterpret_cast<Scalar*>(pb);
  MatrixType A(a,*n,*n,*lda);
  MatrixType B(b,*n,*nrhs,*ldb);

  if(UPLO(*uplo)==UP)
  {
    A.triangularView<Upper>().adjoint().solveInPlace(B);
    A.triangularView<Upper>().solveInPlace(B);
  }
  else
  {
    A.triangularView<Lower>().solveInPlace(B);
    A.triangularView<Lower>().adjoint().solveInPlace(B);
  }

  // delete *a/delete *b is new line
  delete *a;
  delete *b;

  return 0;
}
```
In my option, some variables are not freed in that function.
Should I scratch this issue?

**Comment by ozzzp** [comment]
umm..., I don't think the problem is caused of `pytorch/third_parth/eigen/lapack/cholesky.cpp`, 
One reason is that the memory leak was only happened when matrix is large enough(ie, 1280*1280).   Eigen bug does not make sense.
@akahard2dj, which variable do you think are not freed? `MatrixType`?

**Comment by vishwakftw** [comment]
Hi @ozzzp @akahard2dj,

This is not related to Eigen, but related to MAGMA. Unfortunately, this seems to be a bug in their internal routine `magma_spotrf_batched`. I will forward this issue to the maintainers, who will perhaps take a look at it.

I used this script to detect the memory leak:
```python
import torch
import gc
import resource

def test_cholesky():
    A = torch.rand(4, 1280, 1280).cuda()
    H = A.matmul(A.transpose(1, 2))
    decomp = torch.cholesky(H)

if __name__ == '__main__':
    for i in range(0, 100):
        gc.collect()
        test_cholesky()
        print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
```

cc: @soumith for transparency

**Comment by akahard2dj** [comment]
@ozzzp @vishwakftw Yes, All of you are right.
I am totally wrong. It seems to be not related with Eigen.
@vishwakftw has already mentioned above, I also agree with a relation to MAGMA.
I am so sorry for wrong point out a problem.

**Comment by vishwakftw** [comment]
No worries @akahard2dj , thanks for investigating as much as you could.

FYI, I have posted this on the MAGMA forum: 
https://icl.cs.utk.edu/magma/forum/viewtopic.php?f=2&t=2086&sid=0976189c4faae7604ff9fdcfbae55387.

**Comment by SsnL** [comment]
@soumith MAGMA has fixed the leak from their side. Maybe you need to rebuild the MAGMA packages...

**Comment by vishwakftw** [comment]
@soumith Just FYI, MAGMA 2.5.0 has been released. https://icl.utk.edu/magma/software/index.html

**Comment by soumith** [comment]
v1.0.1 ships with MAGMA 2.5.0, and the memory leak should be gone.

**Comment by SsnL** [comment]
@soumith what do I need to do if I build form source?

**Comment by vishwakftw** [comment]
I think upgrading the MAGMA binary should suffice.

**Comment by Mr-DDDAlKilanny** [comment]
I have memory leak now on v1.0.1. Before, on v.1.0.0, I was able to run 40 batch size without any problems on my model. Now if I run I get out of memory after 20 steps. Decreasing batch size to even 15 still getting out of memory after ~450 steps. I think there is memory leak.

**Comment by vishwakftw** [comment]
Have you updated your MAGMA installation? Please try doing so, if you haven't done it.

**Comment by Mr-DDDAlKilanny** [comment]
Sorry for confusion, I don't use MAGMA in my code, just pytorch itself

**Comment by ccccchange** [comment]
I have the same problem as you. Can you tell me how you solved it ?

**Comment by vishwakftw** [comment]
@ccccchange have you updated your magma installation?

**Comment by ccccchange** [comment]
I installed pytorch in the virtual environment of anaconda. I just found some .h files related to MAGMA, but I didn't find libmagma. Could you please tell me how I should update it

**Comment by ccccchange** [comment]
I found a magma-related .h file under the path shown in the picture, but I didn't find a magma-related library
![magma](https://user-images.githubusercontent.com/54473539/71499182-6141d380-289a-11ea-883d-456720654385.png)

**Comment by AlexanderMath** [comment]
**Bug:** Same issue as above but for ```torch.svd``` instead of ```torch.cholesky```.  

**Code: ** Same as above but with ```torch.svd```

```
import torch
import gc
import resource

def test_svd():
    A = torch.rand(1280, 1280).cuda()
    torch.svd(A)

if __name__ == '__main__':
    for i in range(0, 100):
        gc.collect()
        test_svd()
        print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
```

**Output: **
3517572
3564656
3589708
3627400
3650356
3680136
3705964
3721080
3740656
3765636
3783540
3797584
3830488
3836276
3847300

**Environment. ** 
python 3.7.3
pytorch 1.7.0
nvcc -V V10.0.130

**Comment by linminhtoo** [comment]
> Let me know if you want me to open a seperate issue for this, it just seemed to be so similar that it wasn't really worth it.
> 
> **Bug:** Same issue as above but for `torch.svd` instead of `torch.cholesky`.
> 
> **Workaround/quickfix.** If lowrank svd is sufficient `torch.svd_lowrank` does not have memory leak.
> 
> **Code:** Same as above but with `torch.svd`
> 
> ```
> import torch
> import gc
> import resource
> 
> def test_svd():
>     A = torch.rand(1280, 1280).cuda()
>     torch.svd(A)
> 
> if __name__ == '__main__':
>     for i in range(0, 100):
>         gc.collect()
>         test_svd()
>         print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
> ```
> 
> **Output:** 3517572 3564656 3589708 3627400 3650356 3680136 3705964 3721080 3740656 3765636 3783540 3797584 3830488 3836276 3847300
> 
> **Environment.** python 3.7.3 pytorch 1.7.0 nvcc -V V10.0.130

has this been fixed?
