### ISSUE TITLE
caffe2/perfkernels/math_cpu_avx2.cc:105:44: error: '_mm256_extract_epi64' was not declared in this scope

### ISSUE THREAD

**Issue by gromzhu** [pytorch/pytorch#15533]
i try to run `./scripts/build_android.sh -DANDROID_ABI=x86`
but build is faild
### the faild messeage is below:
/pytorch/caffe2/perfkernels/math_cpu_avx2.cc: In function 'void caffe2::math::quantize_and_compress__avx2(const float*, uint8_t*, size_t, size_t, bool, const float*)':
/pytorch/caffe2/perfkernels/math_cpu_avx2.cc:105:44: error: '_mm256_extract_epi64' was not declared in this scope                _mm256_extract_epi64(orval_v, 0);
                                                                                  ^
/pytorch/caffe2/perfkernels/math_cpu_avx2.cc:146:44: error: '_mm256_extract_epi64' was not declared in this scope               _mm256_extract_epi64(orval_v, 0);
                                                                                  ^

### the Configuring infomation is here

-- std::exception_ptr is supported.
-- NUMA is disabled
-- Turning off deprecation warning due to glog.
-- Current compiler supports avx2 extension. Will build perfkernels.
-- Use custom protobuf build.
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/data1/zhenyu18/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- The BLAS backend of choice:Eigen
-- Brace yourself, we are building NNPACK
-- Using third party subdirectory Eigen.
-- Could NOT find pybind11 (missing: pybind11_DIR)
-- Could NOT find pybind11 (missing: pybind11_INCLUDE_DIR) 
-- Using third_party/pybind11.
-- Using custom protoc executable
-- 
-- ******** Summary ********
--   CMake version         : 3.9.20170718
--   CMake command         : /data1/sina_recmd/local/cmake_3.9/bin/cmake
--   System                : Android
--   C++ compiler          : /data1/zhenyu18/android-ndk-r17c/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-g++
--   C++ compiler version  : 4.9.0
--   CXX flags             : -isystem /data1/zhenyu18/android-ndk-r17c/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -fno-strict-aliasing -frtti -fexceptions  -Wno-deprecated -fvisibility-inlines-hidden -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : 
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /data1/zhenyu18/pytorch/install
--   CMAKE_MODULE_PATH     : /data1/zhenyu18/pytorch/cmake/Modules
-- 
--   ONNX version          : 1.3.0
--   ONNX NAMESPACE        : onnx_c2
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : OFF
-- don't use NUMA
-- NCCL operators skipped due to no CUDA support
-- Excluding ideep operators as we are not using ideep
-- Excluding image processing operators due to no opencv
-- Excluding video processing operators due to no opencv
-- ******** Summary ********
-- General:
--   CMake version         : 3.9.20170718
--   CMake command         : /data1/sina_recmd/local/cmake_3.9/bin/cmake
--   System                : Android
--   C++ compiler          : /data1/zhenyu18/android-ndk-r17c/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-g++
--   C++ compiler version  : 4.9.0
--   BLAS                  : Eigen
--   CXX flags             : -isystem /data1/zhenyu18/android-ndk-r17c/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -fno-strict-aliasing -frtti -fexceptions  -Wno-deprecated -fvisibility-inlines-hidden -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -s
--   Build type            : Release
--   Compile definitions   : ONNX_NAMESPACE=onnx_c2
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /data1/zhenyu18/pytorch/install
-- 
--   TORCH_VERSION         : 1.0.0
--   CAFFE2_VERSION        : 1.0.0
--   BUILD_ATEN_MOBILE     : ON
--   BUILD_ATEN_ONLY       : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Protobuf compiler   : 
--     Protobuf includes   : 
--     Protobuf libraries  : 
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : OFF
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_SHARED_LIBS     : OFF
--   BUILD_TEST            : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FBGEMM            : OFF
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MKLDNN            : 
--   USE_NCCL              : OFF
--   USE_NNPACK            : ON
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : OFF
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_QNNPACK           : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : ON
--     USE_MPI             : OFF
--     USE_GLOO            : OFF
--     USE_GLOO_IBVERBS    : OFF
--   Public Dependencies  : Threads::Threads
--   Private Dependencies : qnnpack;nnpack;cpuinfo;fp16;log;onnxifi_loader;dl
-- Configuring done

**Comment by soumith** [comment]
@gromzhu see https://github.com/pytorch/pytorch/pull/15509 for fix
