### ISSUE TITLE
Please use torch.load with map_location to map your storages to an existing device.

### ISSUE THREAD

**Issue by Jasperty** [pytorch/pytorch#15541]
i train my model on gpu 0, but i reload it to continue train to gpu3, but i get the error:

 RuntimeError: Attempting to deserialize object on CUDA device 3 but torch.cuda.device_count() is 2. Please use torch.load with map_location to map your storages to an existing device.

i have 4 gpus, and gpu 3 is work

**Comment by soumith** [comment]
as mentioned, `torch.cuda.device_count()` is only 2. Probably `nvidia-smi` will also show that only 2 GPUs are visible to the driver?
How are you checking that `GPU 3` is working?

**Comment by alwynmathew** [comment]
I got the same error while In trained a model in another system(GPU server) and loaded the trained weights in my system(Personal system) using `model.load_state_dict(state['state_dict']` for inference. 

```
RuntimeError: Attempting to deserialize object on CUDA device 6 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.
```

When I googled it I found [this](https://stackoverflow.com/questions/53186736/runtimeerror-attempting-to-deserialize-object-on-cuda-device-2-but-torch-cuda-d) to add `map_location` to solve the issue but it didn't. 

GPU server:
CUDA 7.5
Driver 384.130
Pytorch 1.1.0
Trained on GPU ID: 6

Personal system:
CUDA 10.1
Driver 418.67
Pytroch 1.1.0
Inference on GPU ID: 0

Any idea, why?

**Comment by VitalyFedyunin** [comment]
Closing this as answered. Feel free to reopen if you have more details or it din't solve your issue.

**Comment by mengxiangyudlut** [comment]
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

**Comment by yz-cnsdqz** [comment]
I have experienced this problem again. My pytorch version is 1.6.0.
what I run is
`torch.load(model_path, map_location='cuda:0')`
What it outputs is
`*** RuntimeError: Attempting to deserialize object on CUDA device 6 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.`
