### ISSUE TITLE
main.exe ,which was made  from main.py by pyinstaller , faced on error  

### ISSUE THREAD

**Issue by YoshikiKatou** [pytorch/pytorch#15557]
## ❓ Questions and Help
I made main.exe ,which is made from main.py by the pyinstaller.
But I did main.exe,then it faced  "main.exe: error: unrecognized arguments: --multiprocessing-fork
parent_pid=7056 pipe_handle=1188" erroe and stopped.

How do I change main.py code to operate main.exe without this error?

I'd really appreciate it if anyone will give me the advice as soon as possile

・CUDA9, Python3.6 ,Pytorch Windows for CUDA9,
・OS　Windows10 Pro 64bit
・Nvidia GTX980

**Comment by peterjc123** [comment]
Please read this [post](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing). The issue should actually be sent to pyinstaller. Because it isn't a pytorch problem.

**Comment by YoshikiKatou** [comment]
Thank you for your advice ,peterjc123.
I understood this error isn't pytorch problem , it is pyinstaller problem.
