### ISSUE TITLE
torch.ormqr returns single tensor, documentation  shows tuple -> (Tensor, Tensor)

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#15565]
## 📚 Documentation

underlying aten routine in c++ indicates a single tensor is returned:

`Tensor ormqr(const Tensor & self, const Tensor & input2, const Tensor & input3, bool left=true, bool transpose=false);
`

**Comment by ezyang** [comment]
@meganset The Python docs are wrong.
