### ISSUE TITLE
Build pauses at a certain percentage and nothing further happens

### ISSUE THREAD

**Issue by amrit-das** [pytorch/pytorch#15564]
## ❓ Questions and Help

My Build Pauses at a certain percentage between 50 to 60% and nothing further happens. It throws no error, it just pauses. I did wait for around 4 hours but nothing happened. I tried it for 5 to 6 times. Everytime the same problem. For the first 40%, it took around 40-45mins. For 40% to 50% it takes around 30 min and after that, it gets slower and pauses. But doesn't throw any error. 

Raspberry Pi 3B+ 
The environment is properly set. I installed using the same setting on another similar board. 
16 GB sd card. Needed requirements Installed.

**Comment by amrit-das** [comment]
https://medium.com/hardware-interfacing/how-to-install-pytorch-v4-0-on-raspberry-pi-3b-odroids-and-other-arm-based-devices-91d62f2933c7

This is how I installed on my second boards and it works fine.

**Comment by soumith** [comment]
I cant think of anything, I'd suggest debugging further by seeing what it's doing while it looks paused. You can use utilities like `strace` or `perf top` to debug further.

**Comment by amrit-das** [comment]
Yes, Sir, the issue wasn't due to PyTorch files, rather due to lack of memory in the dev board. Due to some reason, apparently while building the memory gets filled up due to which the issue is caused.
