### ISSUE TITLE
qr,geqrf not in torch namespace

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#15566]
## 🚀 Feature
qr,geqrf not in torch namespace (or i need some extra compiler include(?)

i need to refer to at::qr & at::geqrf to compile

**Comment by gchanan** [comment]
CC @goldsborough @yf225.

**Comment by goldsborough** [comment]
I assume you are on a pre-1.0 release? The symbols from the `at::` namespace began being exported to `torch::` in October, so `torch::qr` and `torch::geqrf` should be available if you use the PyTorch 1.0 release. For previous versions, you indeed have to use `at::` instead of `torch::`.

**Comment by meganset** [comment]
No, I was using a 1.0 release (from Dec 8) and all the other BLAS routines were available from the torch namespace at the time.  But, using a newer release now(Dec 30), and I see the routines in torch,
so maybe I had some problem in my environment.

I'll close this,
thanks.
