### ISSUE TITLE
Cuda Out of Memory Error after few successful batches

### ISSUE THREAD

**Issue by kaustav1987** [pytorch/pytorch#15563]
## 🐛 CUDA throwing out of memory error after executing 140 batches successfully

 RuntimeError: CUDA out of memory. Tried to allocate 496.38 MiB (GPU 0; 6.00 GiB total capacity; 3.87 GiB already allocated; 348.64 MiB free; 401.80 MiB cached)

#I have tried the following:

I have used item method to avoid storing tensor. Used empty_cache, gc collect, retain_graph as False while calling backward. I have also tried to provide drop_last=True in the DataLoader function. But all in vain. Kindly suggest. 

Reducing Batch Size does help. But any other alternatives.

Here is my code:

```
for epoch in range(1, n_epochs+1):
    train_loss = 0.0
    model.train()
    for batch_idx, (image,label) in enumerate(loaders['train']):
        # move to GPU
        if use_cuda:
            image,label = image.cuda(), label.cuda()
        if (batch_idx +1) % 20 == 0:
            print('Batch Id '+ str(batch_idx +1))
        ## find the loss and update the model parameters accordingly
        ## record the average training loss, using something like
        ## train_loss = train_loss + ((1 / (batch_idx + 1)) * (loss.data - 
        ## train_loss))
        optimizer_scratch.zero_grad()
        output = model_scratch(image)
        loss = criterion_scratch(output,label)
        ##loss.backward(retain_graph=False)
        loss.backward()

        optimizer_scratch.step()
        train_loss = train_loss + ((1 / (batch_idx + 1)) * (loss.item() - 
        train_loss))
        torch.cuda.empty_cache() 
        ##gc.collect()
```

## Environment
Anaconda Jupyter Notebook
torch==1.0.0

**Comment by ismymajia** [comment]
i face the same question.

**Comment by ngxbac** [comment]
I have the same problem

**Comment by lixiandea** [comment]
i have the same problem when i trained resnet.

**Comment by soumith** [comment]
@kaustav1987 can you give a complete reproduction, that we can run. Ideally it's small enough that we can also read and debug it in reasonable time.

**Comment by kaustav1987** [comment]
Please find the link containing the code and the error details:

[https://github.com/kaustav1987/Cuda-Error-in-Pytorch/blob/master/dog%20Breed%20Classifier%20-Cuda%20Error.ipynb]

**Comment by cmeister747** [comment]
I'm having this issue as well. Has anyone found a solution yet?

**Comment by ustctf** [comment]
Met the same issue. May we know whether it has been fixed yet? @soumith

**Comment by soumith** [comment]
@ustctf the patch was landed 8 days ago, and is part of the pytorch nightly builds. give it a try.

Reference: https://github.com/pytorch/pytorch/pull/17120

**Comment by hongdd** [comment]
i face the same problem
but my GPU is 0% not used
gpu 1060 6g
anyone can give a docs
thx

**Comment by hongdd** [comment]
okkkk
i got a solution:
my batchsize =128 is too large
i change my batchsize to 24
is okkkk
