### ISSUE TITLE
Thank you for your hard work!

### ISSUE THREAD

**Issue by TwoAbove** [pytorch/pytorch#15579]
Hey!

I have been using PyTorch since 0.10, and would like to say that it has been a great tool in my education and work. I've seen PyTorch grow and become something that I'd like to use in production for my first ever product that is in development, and it's really exiting! 

I'd like to thank all of the maintainers and devs that contribute to this project, and all related ones.

Cheers!
❤️ 

(no issue, just wanted to show my gratitude, you can close this whenever)

**Comment by yashkumaratri** [comment]
Go PYTORCH

**Comment by soumith** [comment]
Thanks a lot for your support, we really appreciate it :)
