### ISSUE TITLE
CUDA error: invalid device function

### ISSUE THREAD

**Issue by kennysong** [pytorch/pytorch#1557]
I built PyTorch from source for CUDA 7.5, but get the following runtime error when trying to add GPU tensors:

```
>>> torch.__version__
'0.1.12+0ba2043'

>>> torch.cuda.is_available()
True

>>> x = torch.rand(5, 3).cuda()
>>> y = torch.rand(5, 3).cuda()
>>> x + y
THCudaCheck FAIL file=/gpfsnyu/home/ks3286/pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu line=247 error=8 : invalid device function
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfsnyu/home/ks3286/.conda/envs/conda_root/lib/python2.7/site-packages/torch/tensor.py", line 267, in __add__
    return self.add(other)
RuntimeError: cuda runtime error (8) : invalid device function at /gpfsnyu/home/ks3286/pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:247
```

**Comment by soumith** [comment]
what GPU are you running this on? I cant reproduce this.

**Comment by pavanky** [comment]
@kennysong Did you by chance compile the module on a different machine ?

**Comment by kennysong** [comment]
@pavanky Yes, thanks for pointing this out, this was the issue. PyTorch was running on a different cluster node than it was compiled on. I re-built in the correct place and now all is working perfectly.

**Comment by zm379096736** [comment]
> @pavanky Yes, thanks for pointing this out, this was the issue. PyTorch was running on a different cluster node than it was compiled on. I re-built in the correct place and now all is working perfectly.

How do you solve it?
