### ISSUE TITLE
build error, THCTensorTopK.cuh

### ISSUE THREAD

**Issue by KongCDY** [pytorch/pytorch#1558]
When I build from source code, 
pytorch/torch/lib/THC/THCTensorTopK.cuh(122): error: identifier "__half_as_ushort" is undefined
pytorch/torch/lib/THC/THCTensorTopK.cuh(134): error: identifier "__ushort_as_half" is undefined

**Comment by KongCDY** [comment]
I can build the v0.1.11 version, the v0.1.12 and master version will appear those errors.

**Comment by apaszke** [comment]
What's your CUDA driver/toolkit version?

**Comment by KongCDY** [comment]
It's 8.0.27 version.

**Comment by soumith** [comment]
thats a release candidate build. you need atleast 8.0.44 which are stable versions

**Comment by KongCDY** [comment]
OK, Thanks, I'll try.
