### ISSUE TITLE
c++ gpu memory do not be released ?

### ISSUE THREAD

**Issue by ismymajia** [pytorch/pytorch#15586]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

i build pytorch v1 source code and use c++ api. but occur to need a big gpu memory, as below:
![image](https://user-images.githubusercontent.com/17922949/50501688-feeea100-0a94-11e9-8031-f6c5dd3bcbf4.png)

c++ gpu memory do not be released ?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
