### ISSUE TITLE
Encounter the problem "IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number".

### ISSUE THREAD

**Issue by ZealACMer** [pytorch/pytorch#15585]
I encountered the problem as shown in the following pic:
![image](https://user-images.githubusercontent.com/16794553/50501317-458ecc00-0a92-11e9-989d-afd991ed96d6.png)
When I tried to change loss.data[0] to loss.item(), but encountered another problem, error message is shown as follows:
![image](https://user-images.githubusercontent.com/16794553/50501412-ea110e00-0a92-11e9-9363-89344b8615cb.png)
How can I solve this, thank you very much.

**Comment by vishwakftw** [comment]
Just as specified in the error message, perform `prec1.item()` instead of `prec1[0]`.

Please post such questions on the [forums](https://discuss.pytorch.org) instead, where such questions are answered faster.

**Comment by ZealACMer** [comment]
Thank you very much for your reply. Thank you !
