### ISSUE TITLE
Is there any ImageDataGenerator function like that is available in Keras?

### ISSUE THREAD

**Issue by sayoojbala** [pytorch/pytorch#15596]
is there anything like   a ImageDataGenerator  as in Keras which allows run time image loading and stuff thus giving the flexibility of training models on limited memory system ?

**Comment by chicm** [comment]
Yes, you can use torch.utils.data.DataLoader,  for example: https://github.com/pytorch/examples/blob/master/imagenet/main.py

**Comment by sayoojbala** [comment]
But does that work like an image generator in a sense like when I m using that it hangs my system because I think it is loading the whole data at once.

**Comment by chicm** [comment]
Yes, the ImageFolder dataset works like generator (it does not load data at once), you can also implement your own dataset in a generator way, just derive your class from torch.utils.data.Dataset

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
