### ISSUE TITLE
how to deal with input image of arbitrary size with the JIT and LibTorch C++ API

### ISSUE THREAD

**Issue by xinheblue** [pytorch/pytorch#15594]
In many situations, like image enhancement, super-resolution, We need to deal with input image with arbitrary size,  Training and testing in python is not a problem, but when i want to export the model with JIT and load in LibTorch C++ API, I couldn't find a way to deal with this

The official demo have a predefined input size, if we want to to deal with arbitrary size, how can we manage to do that?

**Comment by an-kumar** [comment]
The JIT trace is just for arriving at a static network configuration. Some networks dynamically determine their parameters based on the input size; for example, CNNs with fully connected layers at the end will have a different fully connected size for different input sizes.

The networks you're talking about don't dynamically determine parameters based on input size. Instead the same network configuration works on arbitrary image size. So you can run the JIT trace with any input size and receive a network configuration that will work on any other input size; then when you load it in C++, you can pass any input size in and it will still work.

**Comment by driazati** [comment]
You can also write TorchScript directly without providing any input sizes via [scripting](https://pytorch.org/docs/stable/jit.html#torch.jit.ScriptModule)

**Comment by xinheblue** [comment]
thanks for @an-kumar  and @driazati , it works!
