### ISSUE TITLE
[caffe2] Caffe2 relies on futures

### ISSUE THREAD

**Issue by louisabraham** [pytorch/pytorch#15618]
## 🐛 Bug

    "caffe2/python/core.py", line 9, in <module>
        from past.builtins import basestring
    ModuleNotFoundError: No module named 'past'

With latest version `pytorch-nightly=1.0.0.dev20181227=py3.7_cuda9.0.176_cudnn7.4.1_0`

futures should be added to the dependencies

**Comment by soumith** [comment]
we dont add all caffe2 dependencies to the wheel dependencies (only the pytorch ones). you can install the caffe2 deps with`pip install -r https://raw.githubusercontent.com/pytorch/pytorch/master/requirements.txt`

**Comment by willprice** [comment]
This seems to be an issue with the new tensorboard support

```
  File "train_cifar.py", line 11, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/will/.miniconda3/envs/env/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 6, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa F401
  File "/home/will/.miniconda3/envs/env/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 18, in <module>
    from ._convert_np import make_np
  File "/home/will/.miniconda3/envs/env/lib/python3.7/site-packages/torch/utils/tensorboard/_convert_np.py", line 12, in <module>
    from caffe2.python import workspace
  File "/home/will/.miniconda3/envs/env/lib/python3.7/site-packages/caffe2/python/workspace.py", line 15, in <module>
    from past.builtins import basestring
```

I'd argue that pytorch should depend on `past` if its now a transitive dependency.

**Comment by soumith** [comment]
this seems like a huge oversight. cc: @lanpa @orionr why exactly is `from ._convert_np import make_np` importing `caffe2.python`?

**Comment by orionr** [comment]
The caffe2 import should have been done internal to one of the functions in that file. I'm going to put up a PR to fix this, but it implies that our CI tests don't cover the fact the scenario where people don't have `feature` installed.

**Comment by soumith** [comment]
@kostmo can you work with @orionr to open up one of the cases to cover this setting (where requirements.txt deps are not installed in the test environment)

**Comment by orionr** [comment]
cc @sanekmelnikov to work with @kostmo as well.

**Comment by geetickachauhan** [comment]
Just following up on this: It does not seem like `conda install tensorboard` has removed the hard dependency on caffe2 yet because I still get the above issue referenced in this issue.

**Comment by orionr** [comment]
@geetickachauhan is this the equivalent of PyTorch nightly? Not sure how you'd still be getting this... can you post a stack trace for the error? Thanks.
