### ISSUE TITLE
[C++] better slice or advanced indexing support

### ISSUE THREAD

**Issue by Rikorose** [pytorch/pytorch#15613]
## 🚀 Feature

Add methods for better accessing slices.

## Motivation

Python makes it very easy to access specific rows, columns or other slices with different shapes. E.g.
- `x[:, 1]`
- `x[2:5]`

The C++ api lacks this functionality. Workarounds are available, but require a lot more code and are difficult to read (e.g. [here](https://discuss.pytorch.org/t/row-wise-element-indexing-in-pytorch-for-c/30705)). 

There is a rust implementation of an ndarray ([here](https://github.com/bluss/ndarray)), that uses a `slice` method and a specific macro ([see here](https://docs.rs/ndarray/0.12.1/ndarray/macro.s.html)), that could provide some inspiration.

## Pitch

Additional methods or maybe macros that enable an easier way of accessing slices.
E.g.
- `get_axis(dim, index)`
- `slice(dim, start, end)`

Both should be assignable with `tensor` that have the correct shape and `scalar` values.

cc @yf225 @glaringlee

**Comment by fmassa** [comment]
There is a function called `narrow` that allows you to slice one dimension, very similar to the `slice` function that you mentioned, the difference being that we pass a size, and not an end

**Comment by Rikorose** [comment]
Thanks I did not know this. Maybe this should be documented with an example in [Tensor Basics](https://pytorch.org/cppdocs/notes/tensor_basics.html)?

**Comment by ezyang** [comment]
Also, slices are assignable, by the magic of ref-qualification. E.g., just as `x[1] = y` does the right thing, `x.narrow(...) = y` also does the right thing. Though it's a lot clearer if you just use `copy_` instead...

**Comment by ezyang** [comment]
this is now fixed, Will added an advanced indexing api to c++
