### ISSUE TITLE
Cuda Error when Calculating Mean After SVD in Script, but not on command line

### ISSUE THREAD

**Issue by bgoodman44** [pytorch/pytorch#15616]
I believe there is synchrnoniziation error withing PyTorch - Cuda.

If I run this simple script, I get the following error:
```
import torch
device = torch.device('cuda:0')
x = torch.randn((10000,10),device=device)
u,s,v = x.svd();
mean = u.mean(0)
```
I get the following error:

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-2-7e6aac6325ea> in <module>()
> ----> 1 mean = u.mean(dim=0)
> 
> RuntimeError: CUDA error: invalid argument

If I immediately re-run the mean calculation within the notebook, it works fine, which leads me to believe there is a synchronization issue, i.e the mean is being calculated before the SVD is complete when it is all run within a single script.  If i switch the device to CPU, everything works fine.

I'm running Ubuntu gnome 16.04, Python 3.5, RTX-2070 w/ 410.78 Nvida Drivers.  
PyTorch 1.0.0 and torch.version.cuda = 9.0.176

**Comment by vishwakftw** [comment]
I am not able to reproduce this error locally. Could you please provide the version of MAGMA that you have installed?

**Comment by bgoodman44** [comment]
I never explicitly installed it.  Could you advise how I check the installed version?

**Comment by vishwakftw** [comment]
Please run [this script](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py), and paste the output here.

You can use `wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py` to obtain the script via the terminal or download it from the link specified above.

**Comment by bgoodman44** [comment]
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 410.78
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by bgoodman44** [comment]
pip3 --version
pip 18.0 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)

**Comment by vishwakftw** [comment]
Could yoy tell how you installed PyTorch?

**Comment by bgoodman44** [comment]
sudo pip3 install torch torchvision

**Comment by vishwakftw** [comment]
I think the issue here best relates to a CUDA version mismatch.

Please try installing using the commands below:

pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
pip3 install torchvision

You can add —user too if required

**Comment by vishwakftw** [comment]
cc: @soumith for pointers?

**Comment by bgoodman44** [comment]
Fixed it!  Installed the pytorch with CUDA 10 support, and also installed the nvidia cuda 10 drivers...all is well!  Sorry for the false alarm!
