### ISSUE TITLE
Consider supporting OSX SDK 10.9

### ISSUE THREAD

**Issue by hmaarrfk** [pytorch/pytorch#15614]
## 🚀 Feature
Support for OSX SDK 10.9.

## Motivation
OSX SDK 10.9 is used in Anaconda's default channels:
https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#macos-sdk
While there isn't a clear cut requirement for wheel files, it might be good to support an SDK a little older than 10.12.
Python.org installers are apparently built for OSX 10.9 in 3.7.

> Up until Python 3.7, Python.org installers were built to be compapatible with macOS 10.6, and were dual architecture (i386 and x86_64 == 32- and 64- bit). Python.org Python 3.7 has an alternative installer compatible with Python 10.9 and above, and only containing x86_64 / 64 bit architecture.

See https://github.com/MacPython/wiki/wiki/Spinning-wheels

## Pitch

I think the only patch that is needed is for `clock_gettime`.

A patch like this one might do, but the clock isn't really monotonic, so there might be unintended consequences when timezone changes occur.

```patch
diff --git a/torch/csrc/autograd/profiler.h b/torch/csrc/autograd/profiler.h
index 2fd623a43..0750cdff7 100644
--- a/torch/csrc/autograd/profiler.h
+++ b/torch/csrc/autograd/profiler.h
@@ -35,11 +35,21 @@ constexpr inline size_t ceilToMultiple(size_t a, size_t b) {
   return ((a + b - 1) / b) * b;
 }
 
+#if defined(__MACH__) && !defined(CLOCK_REALTIME)
+#include <sys/time.h>
+// clock_gettime is not implemented on older versions of OS X (< 10.12).
+// If implemented, CLOCK_REALTIME will have already been defined.
+#endif
+
 inline int64_t getTime() {
 #ifdef _WIN32
   using namespace std::chrono;
   using clock = std::conditional<high_resolution_clock::is_steady, high_resolution_clock, steady_clock>::type;
   return duration_cast<nanoseconds>(clock::now().time_since_epoch()).count();
+#elif defined(__MACH__) && !defined(CLOCK_REALTIME)
+  struct timeval now;
+  gettimeofday(&now, NULL);
+  return static_cast<int64_t>(now.tv_sec) * 1000000000 + static_cast<int64_t>(now.tv_usec) * 1000;
 #else
   // clock_gettime is *much* faster than std::chrono implementation on Linux
   struct timespec t{};
```

## Alternatives

Keep supporting 10.12 only.

## Additional context

XREF: Intended desire to support wheels on linux: https://github.com/pytorch/pytorch/issues/15294
XREF: conda-forge build for mac OSX: https://github.com/conda-forge/staged-recipes/pull/7398

**Comment by soumith** [comment]
@hmaarrfk thanks a lot for researching why 10.9 started failing and the workaround.

If you send the patch that you already wrote as a PR, I'll merge and include in the 1.0.1 dot release
