### ISSUE TITLE
Libtorch: Segfault when using thrust function in torch.script c++ ops

### ISSUE THREAD

**Issue by traveller59** [pytorch/pytorch#15626]
## 🐛 Bug

When I write a torch.jit op with thrust::sort function and use it in python:
```Python
import torch
torch.ops.load_library("./build/libtest.so")
a = torch.rand([3, 2]).cuda()
b = torch.rand([2, 3]).cuda()
c = torch.rand([8000]).cuda()
print(torch.ops.test.mm(a, b))
print(torch.ops.test.sort(c))
```
seg fault.

**If I preload the lib before import torch:**
```Python
import ctypes
ctypes.CDLL("./build/libtest.so")
import torch
torch.ops.load_library("./build/libtest.so")
a = torch.rand([3, 2]).cuda()
b = torch.rand([2, 3]).cuda()
c = torch.rand([8000]).cuda()
print(torch.ops.test.sort(c))
print(torch.ops.test.mm(a, b))
```
The sort function works fine. BUT the at::Tensor::mm will start to produce segfault.
## To Reproduce

1. download [cmake project](https://gist.github.com/traveller59/a25292fab88e44b48861c35c3bb798b5)
2. build, run test.py

## Expected behavior

no segfault.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
CMake version: version 3.13.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 390.77
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.3.1
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] msgpack-numpy (0.4.3.2)
[pip] numpy (1.15.4)
[pip] numpydoc (0.8.0)
[pip] torch (1.0.0)
[pip] torchvision (0.2.1)
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.3                      1  
[conda] mkl-service               1.1.2            py36h90e4bf4_5  
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0  
[conda] mkl_random                1.0.1            py36h4414c95_1  
[conda] pytorch                   1.0.0           py3.6_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] torchvision               0.2.1                     <pip>

cc @yf225 @glaringlee @ngimel

**Comment by goldsborough** [comment]
Having trouble building your example

```
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
/home/psag/pytorch/a25292fab88e44b48861c35c3bb798b5-985752deee06c6006645857783ed92d013a2515b/test.cu(25): error: explicit type is missing ("int" assumed)

/home/psag/pytorch/a25292fab88e44b48861c35c3bb798b5-985752deee06c6006645857783ed92d013a2515b/test.cu(25): error: no suitable conversion function from "thrust::cuda_cub::execute_on_stream" to "int" exists

/home/psag/pytorch/a25292fab88e44b48861c35c3bb798b5-985752deee06c6006645857783ed92d013a2515b/test.cu(26): error: no instance of overloaded function "thrust::sort" matches the argument list
```

Could you instead run your program under gdb with `gdb --args python test.py` and print the stack trace (`bt` command in gdb) once it segfaults? That may help us to debug.

**Comment by traveller59** [comment]
@goldsborough you may need to use cuda 9.0
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffbb0a53bd in cudart::configData::addArgument(void const*, unsigned long, unsigned long) ()
   from /home/xxx/anaconda3/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
(gdb) bt
#0  0x00007fffbb0a53bd in cudart::configData::addArgument(void const*, unsigned long, unsigned long) ()
   from /home/xxx/anaconda3/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
#1  0x00007fffbb092d97 in cudart::cudaApiSetupArgument(void const*, unsigned long, unsigned long) ()
   from /home/xxx/anaconda3/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
#2  0x00007fffbb0c6325 in cudaSetupArgument () from /home/xxx/anaconda3/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
#3  0x00007fffbaca38eb in void thrust::cuda_cub::cub::DeviceRadixSortSingleTileKernel<thrust::cuda_cub::cub::DeviceRadixSortPolicy<int, thrust::cuda_cub::cub::NullType, int>::Policy620, false, int, thrust::cuda_cub::cub::NullType, int>(int const*, int*, thrust::cuda_cub::cub::NullType const*, thrust::cuda_cub::cub::NullType*, int, int, int) ()
   from /home/xxx/anaconda3/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so
#4  0x00007fffad96938b in thrust::cuda_cub::cub::DispatchRadixSort<false, int, thrust::cuda_cub::cub::NullType, int>::InvokeSingleTile<thrust::cuda_cub::cub::DeviceRadixSortPolicy<int, thrust::cuda_cub::cub::NullType, int>::Policy350, void (*)(int const*, int*, thrust::cuda_cub::cub::NullType const*, thrust::cuda_cub::cub::NullType*, int, int, int)> (
    single_tile_kernel=0x7fffbaca38b0 <void thrust::cuda_cub::cub::DeviceRadixSortSingleTileKernel<thrust::cuda_cub::cub::DeviceRadixSortPolicy<int, thrust::cuda_cub::cub::NullType, int>::Policy620, false, int, thrust::cuda_cub::cub::NullType, int>(int const*, int*, thrust::cuda_cub::cub::NullType const*, thrust::cuda_cub::cub::NullType*, int, int, int)>,
    this=0x7fffffffc3c0) at /usr/local/cuda/include/thrust/system/cuda/detail/cub/device/dispatch/dispatch_radix_sort.cuh:863
```

**Comment by ngimel** [comment]
Closing due to age, reopen if still an issue.
