### ISSUE TITLE
inaccurate description of torch.mul(tensor, tensor)

### ISSUE THREAD

**Issue by elad663** [pytorch/pytorch#15636]
## 📚 Documentation for `torch.mul()`

The [doc](https://pytorch.org/docs/stable/torch.html#torch.mul) for `torch.mul(tensor, tensor)` is inaccurate.

There are two issues.
1. The doc says that 
>Each element of the tensor input is multiplied by each element of the Tensor other

i.e. a Cartesian product but then the doc provides the equation:

>out_i = input_i * other_i. 

and then the example provided in the doc does not match the math...
```
>>> a = torch.randn(4, 1)
>>> a
tensor([[ 1.1207],
        [-0.3137],
        [ 0.0700],
        [ 0.8378]])
>>> b = torch.randn(1, 4)
>>> b
tensor([[ 0.5146,  0.1216, -0.5244,  2.2382]])
>>> torch.mul(a, b)
tensor([[ 0.5767,  0.1363, -0.5877,  2.5083],
        [-0.1614, -0.0382,  0.1645, -0.7021],
        [ 0.0360,  0.0085, -0.0367,  0.1567],
        [ 0.4312,  0.1019, -0.4394,  1.8753]])
```

2. There is a case when the math is correct and the multiplication is the naive element-wise product.
```
>>> a
tensor([[ 0.6680,  0.6326],
        [-0.5282, -0.2136],
        [ 0.1368,  1.3523],
        [ 0.7610, -0.1188]])
>>> b
tensor([[-0.5711, -1.2996],
        [ 1.4009,  0.5595],
        [-0.6578,  0.9210],
        [-0.4245,  0.9258]])
>>> torch.mul(a,b)
tensor([[-0.3815, -0.8222],
        [-0.7400, -0.1195],
        [-0.0900,  1.2455],
        [-0.3231, -0.1100]])
```

IMHO a multiplication function that is sometime element-wise and sometime a matrix multiplication is open to undesired behavior if the user has an undetected issue with dimensions. Perhaps in the second case torch.mul() should complain about dimensions. But in any case the inconsistency should be documented.

**Comment by soumith** [comment]
PyTorch uses and implements full broadcasting semantics, similar to NumPy.

The first example you have, where a (1, 4) is multiplied to (4, 1) -- first both inputs are broadcasted such that they expand to (4, 4), and then they are element-wise multiplied.

you can read more about it here: https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

**Comment by elad663** [comment]
Thank you for the clarification that there is a broadcasting step before, I missed it.

The broadcasting works as 
>Each element of the tensor input is multiplied by each element of the Tensor other

when the dimensions are [4x1] [1x4]. 
But if the dimensions are already [4x4][4x4] then the resulting tensor should be [4x4x4x4] and not [4x4] if every element is multiplied by every element.

If the doc said that the tensors are broadcasted to match dimensions and then it is a simple element-wise multiplication then it would be clearer, in my opinion.

**Comment by soumith** [comment]
yea, I agree, the wording there is a bit off.
Would you mind sending a Pull Request improving the doc?

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/15664 which is landing
