### ISSUE TITLE
torch.jit.load() cannot load saved model only on 'cpu'

### ISSUE THREAD

**Issue by AmitRozner** [pytorch/pytorch#15642]
I'm trying to load a torch script model in python using:

`loaded_network = torch.jit.load(network_path)`

The saving was done using:
```
network = torch.jit.trace(self.model, img_list_torch)
network.save(network_path)
```
I manage to load it only when the network was saved from the GPU. When I load the network that was saved from cpu memory I get an error:

>     torch.jit.load(network_path)
>   File ".../python3.5/site-packages/torch/jit/__init__.py", line 133, in load
>     torch._C.import_ir_module(module_lookup, f, map_location)
> RuntimeError: 
> Lists must contain only a single type, expected: Float(2, 2) but found Tensor instead:
>     ret_2 = output_4
>   theta_6 = torch.tanh(ret_2)
>   theta_2 = torch.view(theta_6, [-1, 4, 2])
>   input_10 = torch.mul(x1, y_3)
>   _171 = torch.slice(theta_2, 0, 0, 9223372036854775807, 1)
>   theta_i_1 = torch.slice(torch.select(_171, 1, 0), 1, 0, 9223372036854775807, 1)
>   _172 = torch.select(torch.select(theta_i_1, 0, 0), 0, 0)
>   _173 = torch.select(torch.select(theta_i_1, 0, 0), 0, 1)
>   theta_tmp_1 = torch.unsqueeze(torch.stack([_172, _173], 0), 1)
>   _174 = torch.cat([CONSTANTS.c0, theta_tmp_1], 1)
>                    ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>   theta_3 = torch.unsqueeze(_174, 0)
>   _175 = ops.prim.NumToTensor(torch.size(result_48, 0))
>   _176 = ops.prim.NumToTensor(torch.size(result_48, 1))
>   _177 = ops.prim.NumToTensor(torch.size(result_48, 2))
>   _178 = ops.prim.NumToTensor(torch.size(result_48, 3))
>   _179 = [int(_175), int(_176), int(_177), int(_178)]
>   grid_1 = torch.affine_grid_generator(theta_3, _179)
>   input_2 = torch.grid_sampler(result_48, grid_1, 0, 0)
>   input_3 = torch.upsample_bilinear2d(input_2, [24, 28], True)
> 

I should also note that I checked the network before I saved it and it did inference fine even on cpu.

OS: ubuntu 16.04
python: 3.5
CUDA: 9.2
pytorch: 1.0
GPU: Nvidia 1080TI

**Comment by suo** [comment]
Thanks for the report! Can you try to create the smallest model that can reproduce your issue so we can better investigate?

**Comment by AmitRozner** [comment]
I kind of worked around this bug. Instead of:

```
theta_tmp = torch.stack([theta_i[0, 0], theta_i[0, 1]]).unsqueeze(1)
theta = torch.cat([scale_factors, theta_tmp], dim= 1).unsqueeze(0)
```

I've used:

```
theta_tmp = torch.stack([theta_i[0, 0], theta_i[0, 1]])
theta_tmp = theta_tmp.unsqueeze(1)
theta = torch.cat((scale_factors.transpose(0, 1), theta_tmp.transpose(0, 1))).transpose(0, 1)
theta = theta.unsqueeze(0)
```

It seems to me that there is a problem with torch.cat when using dim=1. If I transpose it works fine. This problem occurs only when I saved from cpu which is very strange.

**Comment by suo** [comment]
@AmitRozner Do you mind attaching the saved module file so I can take a look at what you're loading?

**Comment by AmitRozner** [comment]
Sure.
[hacnn.pth.tar.zip](https://github.com/pytorch/pytorch/files/2749042/hacnn.pth.tar.zip)

**Comment by suo** [comment]
I'm having trouble opening that file, it might be corrupted?

Could you try creating a minimal repro (just the parts of the model that trigger the problem) and giving the exact steps necessary to reproduce the issue? It would help us a lot.

**Comment by cuixing158** [comment]
I also encountered the same problem and reported "torch.jit.load()" an error. Can you help me find it?

from models import resnext
model = resnext.resnet50(num_classes=7, shortcut_type= 'A', cardinality=32,
                         sample_size=112, sample_duration=30,
                         last_fc=True)
model_data = torch.load(r'./save_1.pth')
model.load_state_dict(model_data['state_dict'])
model.eval()
input = torch.rand(1,3,30,112,112) # input size, 训练模型的大小
traced_script_module = torch.jit.trace(model,input)
traced_script_module.save("tennis_model.pt")
output = traced_script_module(torch.ones(1,3,30,112,112))
print(output[0,:5])
loaded_network = torch.jit.load("tennis_model.pt") # error??? 加载模型报错？？？

my model and script is here: 
https://drive.google.com/file/d/1M3kXuGWksQUkWqMxKXY0B0cCroW0kpox/view?usp=sharing
https://drive.google.com/file/d/1N8ACLBEgxDEODgSQ5KMtUR8SJfhEWrYD/view?usp=sharing
https://drive.google.com/file/d/1Uw6ZbzFnego4URLqrMHupFSkqueFsFYu/view?usp=sharing

**Comment by cuixing158** [comment]
@suo  I also meet the same problem,"torch.jit.load" can't load the model, could you help me ?

from models import resnext
model = resnext.resnet50(num_classes=7, shortcut_type= 'A', cardinality=32,
                         sample_size=112, sample_duration=30,
                         last_fc=True)
model_data = torch.load(r'./save_1.pth')
model.load_state_dict(model_data['state_dict'])
model.eval()
input = torch.rand(1,3,30,112,112) # input size, 训练模型的大小
traced_script_module = torch.jit.trace(model,input)
traced_script_module.save("tennis_model.pt")
output = traced_script_module(torch.ones(1,3,30,112,112))
print(output[0,:5])
loaded_network = torch.jit.load("tennis_model.pt") # error??? 

my model and scripts is here:
https://drive.google.com/file/d/1M3kXuGWksQUkWqMxKXY0B0cCroW0kpox/view?usp=sharing
https://drive.google.com/file/d/1N8ACLBEgxDEODgSQ5KMtUR8SJfhEWrYD/view?usp=sharing
https://drive.google.com/file/d/1Uw6ZbzFnego4URLqrMHupFSkqueFsFYu/view?usp=sharing

**Comment by vishwakftw** [comment]
This can be closed now.
