### ISSUE TITLE
I installed pytorch of cuda9.0, why appear libcurand.so.8.0 not found when import torch?

### ISSUE THREAD

**Issue by Mhaiyang** [pytorch/pytorch#15640]
I installed pytorch of cuda9.0, why appear libcurand.8.0.0 not found when import torch?

Traceback (most recent call last):
  File "/home//train.py", line 4, in <module>
    import torch
  File "/usr/local/lib/python3.5/dist-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: libcurand.so.8.0: cannot open shared object file: No such file or directory

**Comment by soumith** [comment]
please follow our issue templates, there's very little information that we can help with.
Follow the Bug Report template.
