### ISSUE TITLE
dataparallel cannot split the model to multiple gpus

### ISSUE THREAD

**Issue by isalirezag** [pytorch/pytorch#15643]
It would be nice if dataparalel can split the model to multiple gpus when the model cannot fit to one gpu.
lets say my model 20GB and each GPU is 12, and I have 4 gpus.
 mxnet and tensorflow can easily split the model among 4 gpus so it does not throw out of memory error. it would be nice if pytorch consider to add this as well
Thanks

**Comment by SsnL** [comment]
I'm confused. Why should the data loader do this? If you want model parallelism, then it is natively supported in pytorch... just put different model parts on different gpus.

**Comment by isalirezag** [comment]
I am sorry i meant dataparallel..

**Comment by deepaks4077** [comment]
@isalirezag : You can build your model as a series of submodules and transfer them to different devices during initialization. In the forward phase, collect the outputs to a single device (e.g. .cuda(1)).
Check out [this](https://discuss.pytorch.org/t/model-parallelism-in-pytorch-for-large-r-than-1-gpu-models/778/2) comment.

**Comment by isalirezag** [comment]
@deepaks4077 
yeah,I knew this method, thats not as easy as we think for complicated models, it is painful actually :)

**Comment by soumith** [comment]
@isalirezag what you are asking for is called model parallelism, not data parallelism.

I might not be fully aware, but the APIs TF / MXNet has are decorators, such as

```
with device('gpu:1'):
    out = conv(inp)
```

PyTorch also has the same API, as Deepak tried to explain.
If I misunderstand, please tell what API you are expecting

**Comment by isalirezag** [comment]
@soumith Thanks for the explanation, 
I understand, the only difference between Pytorch and Mxnet/TF for model paralllism is that in the later one we dont have to specifically tell what gpu has what part ogf the model. in other words, TF/MXNet are able to automatically parallelize the workloads if the model is bigger than one gpu (e.g. [link1](https://gluon.mxnet.io/chapter07_distributed-learning/multiple-gpus-scratch.html) and [link2](https://mxnet.incubator.apache.org/faq/multi_devices.html) ) but in pytorch if our model is bigger than one gpu we have to do it by ourselves and that sometimes is not quite easy

**Comment by soumith** [comment]
What you are asking for is automatic workload scheduling algorithms. These are very active research in literature are very experimental, and their performance can be pretty bad in the average case and worst case. Hence, we dont have any plans to implement them at the moment (and give users hell-ish perf characteristics).

The recommended practice in TF and MXNet are still what I described above, where the user places the workload on the device themselves.
