### ISSUE TITLE
Libtorch is missing ThreadPool.h header

### ISSUE THREAD

**Issue by zoidor** [pytorch/pytorch#15641]
## 🐛 Bug
The Libtorch archive downloadable from https://pytorch.org/get-started/locally/ (I used the following cconfiguration: LibTorch, C++, CUDA: None, both Nightly and 1.0) is missing ThreadPool.h included by the file include/caffe2/core/workspace.h in the archive.

## To Reproduce

1. Download the zip file from  https://pytorch.org/get-started/locally/ . Last version tested by me: 1.0.0.dev20181230
2. Uncompress
3. Add libtorch/include to the include_directories of your CMakeLists.txt
4. Try to compile, you can create a main.cc that includes caffe2/core/net.h for example. You should get something like

/libtorch/include/caffe2/core/workspace.h:19:10: fatal error: caffe2/utils/threadpool/ThreadPool.h: No such file or directory
 #include "caffe2/utils/threadpool/ThreadPool.h"

## Expected behavior
ThreadPool.h should be available in the archive. I was able to get it to compile including caffe2/utils/thread_pool.h in ThreadPool.h place but I have no idea whether the runtime behaviour is correct or not.

## Environment
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Linux Mint 19 Tara
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.15.4)
[pip3] torch (1.0.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by ezyang** [comment]
cc @goldsborough @yf225

**Comment by ezyang** [comment]
guessing this got fixed in the interim
