### ISSUE TITLE
How to specify the cuda PATH in pytorch?

### ISSUE THREAD

**Issue by Zhujunnan** [pytorch/pytorch#1564]
Hi,  I have installed two versions of CUDA. But I want to use one of it, can I specify it during setup process?

**Comment by pavanky** [comment]
Try running `CUDA_HOME=/path/to/cuda-version python setup.py install`

**Comment by Zhujunnan** [comment]
I have tried it,  torch.cuda.is_available() still returns False.  Thx for your reply!

**Comment by pavanky** [comment]
Do you have the cuda driver installed?

**Comment by Zhujunnan** [comment]
Of course I do.  It raise assertion error which shows "The NVIDIA driver on your system is too old(found version 8000)".

**Comment by soumith** [comment]
that's the answer to your problem. upgrade your driver.

**Comment by Zhujunnan** [comment]
Thx!
