### ISSUE TITLE
[Feature Request] Asynchronous torch.save()

### ISSUE THREAD

**Issue by Jiaming-Liu** [pytorch/pytorch#1567]
Saving huge models costs a lot of IO time. It would be helpful if we could first pickle everything in RAM and then use another process to actually store them.

**Comment by apaszke** [comment]
I'm not sure how would you like to do this. If you want to guarantee consistency of snapshots you have to either clone all parameters and objects or stop the training while the serialization is performed, and both these options will have fairly high overhead (with the first one also significantly increasing memory pressure). If you're worried about time spent in pickling you can only save the `state_dict` which should have a very small `pickle` overhead (there's only a dict, a few strings and tensors). Additionally, `torch.save` accepts a `file` object and asynchronous operation could result in it being closed in the main thread before all the data is flushed e.g.
```python
with open('my_file', 'wb') as f:
    torch.save(model, f)
# torch.save will return immediately, f will be closed and the thread will be unable to write to the file
```

**Comment by apaszke** [comment]
I don't think there's a universally good solution to this problem, so I'm closing the issue.

**Comment by nicolasdespres** [comment]
@Jiaming-Liu If you fork your process, memory pages modified by either the parent or child process will be copied on write. So in theory, a snapshot is achieved. That is for central memory. I do not know what's going on for video memory. This will not work if you are using shared memory. If you want to first pickle in memory you can use a `io.BytesIO` and then dump it to disk. That should be slightly faster than dumping to disk directly even with an SSD.

**Comment by apaszke** [comment]
You'll get a snapshot, but assuming the main process will continue training, it will need to copy all pages that contain the model data (and python data structures), which in turn will end up being even less efficient than doing a clone on all tensors from the state dict.

**Comment by sbhaaf** [comment]
In the case that you send a state_dict over a network, pickled or otherwise, it seems there's no good way to force the model on the receiving end to load it into CPU without first saving it to disk. If torch.load() could take a BytesIO object then this could be accomplished with map_location.

**Comment by apaszke** [comment]
`torch.load` can take a `ByteIO` object. You can either give it a file path or a file-like object (BytesIO satisfies the second requirement)

**Comment by sbhaaf** [comment]
`torch.save` won't take a BytesIO object.
```
>>> import torch
>>> from io import BytesIO
>>> bio = BytesIO()
>>> torch.save(torch.nn.Linear(10,1).state_dict(), bio)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<>/.installs/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 120, in save
    return _save(obj, f, pickle_module, pickle_protocol)
  File "/home/<>/.installs/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 192, in _save
    serialized_storages[key]._write_file(f)
RuntimeError: _write_file couldn't retrieve a file descriptor from given object
```
You can pickle the `state_dict` to a buffer and send it in, say, a post request, but the receiving end can't use `torch.load` and the `map_location` feature

**Comment by apaszke** [comment]
Ah, my bad! I forgot about this limitation. I opened an issue to track it

**Comment by GuanhuaWang** [comment]
So what is the solution here? What I did is like this:

```
torch.save(A, A_dir)
B =  open(A_dir, "rb")
data_buffer = io.BytesIO(B.read())
torch.load(data_buffer)
```

which gives me the same error as people mentioned above:
```
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 427, in _load
    deserialized_objects[key]._set_from_file(f, offset)
RuntimeError: _set_from_file couldn't retrieve a file descriptor from given object
```
