### ISSUE TITLE
Tests for Vec256 classes

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#15676]
## 🚀 Feature
We should have tests in C++ for the Vec256 classes.

## Motivation
Currently, the Vec256 code is only tested indirectly through operators that use it. This has led to insufficient test coverage and a number of recent bugs in Vec256 and the operators that use it. We should add sufficient test infrastructure so that we can easily add test cases for new functions on Vec256. It's important that the tests cover the different data types (float, double, int32, int64, etc.) and instruction sets (generic, avx, avx2).

This will require changes to CMake since the current test cases don't enable the AVX/AVX2 instruction sets.

cc @VitalyFedyunin

**Comment by quickwritereader** [comment]
I need this, too. I want to add power VSX support. Adding These tests definitely would be helpful for correctness check.

**Comment by VitalyFedyunin** [comment]
Totally agree that we need it. Just curious have you seen any implementations mistakes which could be detected by such tests?

**Comment by ezyang** [comment]
@quickwritereader I think it would be a very useful activity for unit tests to come into existence as part of the POWER work, if you can put that into your work scope.

**Comment by quickwritereader** [comment]
I will start to add test cases and modify Cmake.

**Comment by quickwritereader** [comment]
I already added many test cases. I try to PR it on coming weeks. Right now I am trying to add check for float math functions as its' precision is implementation-dependent and tied to argument domains. 
The test will use random initialization and rely on the correctness of the aligned load/store of vec256.
As union like type puning is discouraged.

**Comment by quickwritereader** [comment]
#41541
