### ISSUE TITLE
Crash with stackoverflow when using WeightedRandomSampler 

### ISSUE THREAD

**Issue by BloodAxe** [pytorch/pytorch#15678]
## 🐛 Bug

A stackoverflow error occurs when using WeightedRandomSampler with large (65K) number of samples and multiprocessing. Python interpreter dies badly with message `Process finished with exit code -1073741571 (0xC00000FD)`.

## To Reproduce

```
import torch
from torch.utils.data import Dataset, WeightedRandomSampler, DataLoader
from tqdm import tqdm


class DummyDataset(Dataset):
    def __init__(self, n_samples=100):
        self.n_samples = n_samples

    def __getitem__(self, item):
        return item

    def __len__(self):
        return self.n_samples


def main():
    dataset = DummyDataset(20000)
    w = torch.rand(len(dataset)).abs() + 0.1
    dataloader = DataLoader(dataset,
                            sampler=WeightedRandomSampler(w, 65536),
                            num_workers=4,
                            pin_memory=True,
                            batch_size=10,
                            drop_last=True)

    for _ in tqdm(dataloader, total=len(dataloader)):
        pass


if __name__ == '__main__':
    main()

```

## Expected behavior

No crash, all samples processed.

## Environment

Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: version 3.13.0-rc2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 416.94
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

## Additional context

- Issue is not reproducing when `num_workers=0`
- Maximum number of crashes which triggers a crash lies somewhere in between 31500..32000 samples.

cc @SsnL @VitalyFedyunin @ejguan @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by peterjc123** [comment]
Maybe related to https://github.com/pytorch/pytorch/issues/12085?

**Comment by cristianPanaite** [comment]
Hello @BloodAxe ,

Closing this ticket as the ticket hasn't had any activity for a long period of time and it seems that it is not valid anymore. I tried to replicate this issue, but on the latest versions I don't get this error.

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.
