### ISSUE TITLE
error while loading pickled dataset

### ISSUE THREAD

**Issue by p-rit** [pytorch/pytorch#15687]
## Additional context

I am using ImageFolder for loading pickled data, could'nt found any other way to load it .
error: TypeError: listdir: path should be string, bytes, os.PathLike, integer or None, not dict

**Comment by soumith** [comment]
ImageFolder is in https://github.com/pytorch/vision

Either ways, we wouldn't provide this feature in torchvision, it's too niche. If you'd like this feature, you can copy over imagefolder.py and make it a custom class in your project with the changes.
