### ISSUE TITLE
Stream operations in torch/cuda/streams.py are incorrect for non-current device

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#15682]
## 🐛 Bug
Some of the operations in the PyTorch Python Stream API (torch/cuda/streams.py) are incorrect when they're called from a different device from the stream's device.

The problem is specific to the default stream because it's represented as a nullptr in the CUDA API level.

## To Reproduce

```python
import torch
d0 = torch.device('cuda:0')
d1 = torch.device('cuda:1')

with torch.cuda.device(d0):
   s0 = torch.cuda.current_stream()

with torch.cuda.device(d1):
    s1 = torch.cuda.current_stream()
    torch.cuda._sleep(1000000000)  # spin for about 1 sec on device1

print('everything finished (called on device 0)', s0.query(), s1.query())  # should be True, False
with torch.cuda.device(d1):
    print('everything finished (called on device 1)', s0.query(), s1.query())  # should be True, False
```

## Additional context

One fix would be to set the current device to the stream's device before calling into the CUDA runtime API. An alternative would be to push the operations down to C++/ATen.

**Comment by mrshenli** [comment]
Hi @colesbury 

Could you please help shed some more light on how we can `push the operations down to C++/ATen`?

It seems `Stream.query` now calls [cuda lib](https://github.com/pytorch/pytorch/blob/656b565a0f53d9f24547b060bd27aa67ebb89b88/torch/cuda/streams.py#L78), which I think we cannot directly modify (??).  So, are we going to implement something like `torch.cuda.stream(some_stream).query()`, or is it possible to change `CUDARTAPI`'s behavior by modifying member functions in `THCPStream`?

**Comment by mrshenli** [comment]
@colesbury Shall we close this issue now?

**Comment by colesbury** [comment]
Yes, please
