### ISSUE TITLE
Consolidate flag/environment variable handling in setup.py

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#15698]
Now that most of the heavy lifting of the PyTorch build happens in cmake, I'd like to see setup.py get substantially slimmed down and simplified, and in the process make it clearer how environment variables get propagated to cmake.

What lead me to report this bug is that I cannot build PyTorch on account of #14486. I want to disable NCCL build entirely, but `NO_DISTRIBUTED=1` (the documented option) does not do this. I read `setup.py` and I see `USE_NCCL`. But this variable is not computed from an environment variable at all. I modify it so that it is respected. I discover cmake is still building NCCL. I find this is because `USE_NCCL` is not propagated to the cmake in `build_pytorch_libs.sh`. Nonsense.

Here's what I would like to see: Every cmake option that we advertise as `option` in the top-level CMakeLists.txt, should be toggleable in some way from setup.py in an officially documented (and hopefully intuitive) way. It should be hard for developers adding new flags to break this invariant. My suggestion is that setup.py respect and translate identically named environment variables into their cmake equivalents automatically. (It might be somewhat tricky to ensure that setup.py and CMakeLists.txt always stay in sync.)

CC @orionr @soumith @anderspapitto @pjh5

**Comment by anderspapitto** [comment]
one step towards this that I'm working on is removing the middle layer (build_pytorch_libs.sh)

**Comment by t-vi** [comment]
For the specific case of NCCL, I think #17295 might be a fix until you do this more systematically.

**Comment by ezyang** [comment]
this got fixed, thanks to xuhdev
