### ISSUE TITLE
Segmentation fault (core dumped) using code of CycleGAN on CPU

### ISSUE THREAD

**Issue by SunHaozhe** [pytorch/pytorch#15699]
## 🐛 Bug

I encountered a problem of segmentation fault (core dumped) when I tried to train a model of CycleGAN [https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix](url) on CPU mode. In fact, it is not only a problem with training of CycleGAN, I have the same problem when I tried to train on other datasets provided by CycleGAN or to test the pretrained models of CycleGAN. As requested by @SsnL , I open an issue here.
The related issue report is [https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/484](url)

## To Reproduce

1. Create an empty Google Cloud Platform Compute Engine VM instance with 2vCPU (around 7.5 GB RAM), Ubuntu 16.04 LTS, no GPU, without built-in image environment
2. wget http://repo.continuum.io/archive/Anaconda3-4.3.0-Linux-x86_64.sh 
3. bash Anaconda3-4.3.0-Linux-x86_64.sh
4. source ~/.bashrc
5. git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix
6. cd pytorch-CycleGAN-and-pix2pix
7. pip install -r requirements.txt
8. bash ./scripts/download_cyclegan_model.sh horse2zebra
9. bash ./datasets/download_cyclegan_dataset.sh horse2zebra
10. python test.py --dataroot datasets/horse2zebra/testA --name horse2zebra_pretrained --model test --no_dropout --gpu_ids -1

<img width="695" alt="1" src="https://user-images.githubusercontent.com/26926814/50642032-47f99600-0f6a-11e9-8fc0-7eaaac6af6d0.png">
<img width="518" alt="2" src="https://user-images.githubusercontent.com/26926814/50642041-4d56e080-0f6a-11e9-8cb5-c00c4787c73b.png">
<img width="1115" alt="3" src="https://user-images.githubusercontent.com/26926814/50642048-5051d100-0f6a-11e9-8695-b52eff4dd1cd.png">
<img width="1115" alt="4" src="https://user-images.githubusercontent.com/26926814/50642056-53e55800-0f6a-11e9-8955-3be2a780bc03.png">
<img width="1120" alt="5" src="https://user-images.githubusercontent.com/26926814/50642062-56e04880-0f6a-11e9-99a8-ce2565c059e4.png">
<img width="1113" alt="6" src="https://user-images.githubusercontent.com/26926814/50642068-59db3900-0f6a-11e9-98f0-696d394b0d8d.png">

I expected to see the training process start. But I observe a segmentation fault error immediately after I run the above commands.

## Environment

 - PyTorch Version: 1.0.0
 - OS (e.g., Linux): Ubuntu 16.04 LTS
 - How you installed PyTorch : pip
 - Build command you used : pip install -r requirements.txt
 - Python version: Python 3.6.0 (Anaconda 4.3.0 (64-bit))
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: None

## Additional context

None

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by fmassa** [comment]
Hi,

Can you try doing
```python
import torch

a = torch.rand(2, 2)
print(torch.matmul(a, a))
```
and see if it works out of the box?

**Comment by ezyang** [comment]
on original issue it looks like they just didn't have enough memory
