### ISSUE TITLE
Libtorch: ASSERT FAILED at /pytorch/c10/impl/DeviceGuardImplInterface.h: DeviceGuardImpl for cuda is not available

### ISSUE THREAD

**Issue by szali** [pytorch/pytorch#15702]
## 🐛 Bug

In libtorch, my program crashes when trying to move a tensor to CUDA.

## To Reproduce

I can't share the whole code but here is some context. This is the constructor of CustomOp, where the error happens: 

CustomOp()
: filter(torch::zeros({1, 1, 4, 4}))
{
	.................
	
	auto accessor = filter.accessor<float,4>();
	for (int x = 0; x < 4; ++x) {
		for (int y = 0; y < 4; ++y) {
			accessor[0][0][x][y] = ............;
		}
	}
	
	filter = filter.to(at::kCUDA);
}

The program crashes on the line "filter = filter.to(at::kCUDA);".

This CustomOp instance is created as a member of the Network class, which has no superclass (just like CustomOp), with its default (and only) constructor, at the very beginning of main():

#include "network.h"

int main() {
    Network network;
    ......................

Error message:

terminate called after throwing an instance of 'c10::Error'
  what():  p ASSERT FAILED at /pytorch/c10/impl/DeviceGuardImplInterface.h:130, please report a bug to PyTorch. DeviceGuardImpl for cuda is not available (getDeviceGuardImpl at /pytorch/c10/impl/DeviceGuardImplInterface.h:130)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fd1101802e1 in ~/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fd11017fc1a in ~/libtorch/lib/libc10.so)
frame #2: at::native::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) + 0x1604 (0x7fd110b4d704 in ~/libtorch/lib/libcaffe2.so)
frame #3: at::TypeDefault::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const + 0x17 (0x7fd110cf7f57 in ~/libtorch/lib/libcaffe2.so)
frame #4: torch::autograd::VariableType::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const + 0x17a (0x7fd11980a16a in ~/libtorch/lib/libtorch.so.1)
frame #5: at::Tensor::to(c10::TensorOptions const&, bool, bool) const + 0x68 (0x439c36 in ./aten_app)
frame #6: custom_ops::CustomOp::CustomOp() + 0x214 (0x43b3fc in ./aten_app)
frame #7: Network::Network() + 0x44 (0x424498 in ./aten_app)
frame #8: main + 0x2b (0x441ec2 in ./aten_app)
frame #9: __libc_start_main + 0xf0 (0x7fd10f81e830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #10: _start + 0x29 (0x41e4f9 in ./aten_app)

Aborted (core dumped)

## Expected behavior

The app does not crash.

## Environment

Collecting environment information...
PyTorch version: 1.0.0a0+5e62494
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.0-rc2

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)

Nvidia driver version: 396.26
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.2.1
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.13.3)
[pip3] torch (1.0.0a0+5e62494)
[pip3] torchfile (0.1.0)
[pip3] torchvision (0.1.9)
[conda] Could not collect

**Comment by NathanSegerlind** [comment]
I'm seeing that as well, using the Jan 2nd nightlies

**Comment by ezyang** [comment]
Can either of you `ldd` your binary and post the result here?

**Comment by szali** [comment]
Here is mine:

	linux-vdso.so.1 =>  (0x00007ffc675a2000)
	libtorch.so.1 => ~/libtorch/lib/libtorch.so.1 (0x00007fc8b4bd4000)
	libcaffe2.so => ~/libtorch/lib/libcaffe2.so (0x00007fc8abbab000)
	libc10.so => ~/libtorch/lib/libc10.so (0x00007fc8ab976000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc8ab5f4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc8ab3de000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc8ab014000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc8aadf7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc8aaaee000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc8aa8ea000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc8b5935000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc8aa6e2000)
	libgomp-7bcb08ae.so.1 => ~/libtorch/lib/libgomp-7bcb08ae.so.1 (0x00007fc8aa4b8000)

**Comment by szali** [comment]
Is there any progress regarding this issue?

**Comment by szali** [comment]
Any progress? Sorry for the polling but it really puzzles me why this simple code is crashing.
In the meanwhile I will try to find a last working libtorch version.

**Comment by szali** [comment]
I think I found the issue. 
In the tutorial (https://pytorch.org/cppdocs/installing.html) the following link is provided:

> wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip

Notice "cpu" in the link url (I did not at first). The tutorial never mentions that this package is not good for CUDA, and the error message (DeviceGuardImpl etc.) is also not very descriptive.

However if I download the libtorch release from here:

https://pytorch.org/get-started/locally/

I get the following url: https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-latest.zip (which has "cu90" in place of "cpu") and it really works.

Please update the tutorial documentation so it links to the CUDA version (or at least includes a warning that it will only work on CPU), and also a better error message would be great.
