### ISSUE TITLE
Make resize_ and resize_as_ internal methods

### ISSUE THREAD

**Issue by nicolasdespres** [pytorch/pytorch#1570]
Calling `resize_` on a non-contiguous tensor potentially do not what you want as demonstrated below. I do not know if it is a bug or a feature but that IMHO that should at least be mentioned in the documentation.

```python
>>> import torch as th
>>> th.__version__
'0.1.12+368ecb4'
>>> t = th.LongTensor([[1,2],[3,4]])
>>> t

 1  2
 3  4
[torch.LongTensor of size 2x2]

>>> t.narrow(1, 1, 1)

 2
 4
[torch.LongTensor of size 2x1]
```

Resizing the narrowed tensor leads to an expected results:

```python
>>> t.narrow(1, 1, 1).resize_(2)

 2
 3
[torch.LongTensor of size 2]
```

Whereas doing so on a contiguous copy of the tensor works as expected:

```python
>>> t.narrow(1, 1, 1).contiguous().resize_(2)

 2
 4
[torch.LongTensor of size 2]
```

**Comment by jekbradbury** [comment]
IMO `resize_` should not be exposed at all; if it needs to be used internally it should be used as a private method `_resize`. Are there any user-side uses for it that aren't mistakes? (It's useful in framework code when you know a resize is safe and want the equivalent of an in-place view)

**Comment by apaszke** [comment]
The behaviour is expected, but I agree that it'd be better to make it an internal method. It might still be worth documenting it, so that more advanced users are still guaranteed to have access to them. It'd be like `_sparse_mask`.

**Comment by nicolasdespres** [comment]
Indeed, the behaviour is expected but I cannot imagine a use-case where it is what the users want. Why not raising an exception like the `view` method does?: `RuntimeError: input is not contiguous at...`

**Comment by apaszke** [comment]
I think it might be used internally even when the tensor is not contiguous (sometimes it might be valid), but I'll need to make sure

**Comment by nicolasdespres** [comment]
Could `Storage.resize_` do the job in such case?

**Comment by albanD** [comment]
I personally use this function to resize buffers before using them (considering that the content after the resize is garbage). It is really convenient because I know that in the case where the buffer is big enough this function does nothing.

**Comment by colesbury** [comment]
I think this is a step in the right direction, but we should provide the operations that people want and are trying to use `resize_` for:

* numpy.reshape: basically equivalent to x.contiguous().view(sizes)
* numpy.empty: create an empty (uninitialized) tensor of the same size

**Comment by apaszke** [comment]
@f0k please do. We should at least have a big red warning right next to `resize_`.
