### ISSUE TITLE
cuda10 version of 1.0 doesn't work on linux

### ISSUE THREAD

**Issue by solomatov** [pytorch/pytorch#15709]
## 🐛 Bug
The installation goes fine but when I run my program, I get the following error:

    from torch._C import *                                                             
E   ImportError: libnvToolsExt.so.1: cannot open shared object file: No such file or directory

## To Reproduce
Do anything with cuda

## Environment
 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): pip (pipenv)
 - Build command you used (if compiling from source): no command
 - Python version: 3.6.7
 - CUDA/cuDNN version: 10.0, I didn't install cudnn and cuda manually, only with pytorch
 - GPU models and configuration:
 - Any other relevant information:

## Additional context
Everything works fine if I install the default version

**Comment by stefan-it** [comment]
You really need to install cudnn and CUDA 10 (CUDA 10 support in PyTorch means that you can access the cudnn/CUDA library). Here's a good [tutorial](https://www.pugetsystems.com/labs/hpc/How-To-Install-CUDA-10-together-with-9-2-on-Ubuntu-18-04-with-support-for-NVIDIA-20XX-Turing-GPUs-1236/) for that :)

**Comment by solomatov** [comment]
@stefan-it I know how to install at. But I prefer for it to work with just pip like it used to work with previous pytorch versions. Could you please reopen the issue?

**Comment by jl2922** [comment]
You have to install Cuda manually

**Comment by solomatov** [comment]
@jl2922 Yes, I understand that. But it used to work with older version, and it doesn't work with cuda 10.

**Comment by stefan-it** [comment]
Then you should use a virtual environment like conda/miniconda. After you created a new environment + activate it, you can run `conda install pytorch torchvision cuda100 -c pytorch` and it will install a `cuda10` package.

**Comment by soumith** [comment]
@solomatov this is a bug in our packaging i think, I'll try to get it fixed for 1.0.1 release. cc: @pjh5 for visibility.

In the meanwhile, you can use the `anaconda` version via `conda install` and it works because we also pull the anaconda `cudatoolkit` dependency.

**Comment by solomatov** [comment]
@soumith Thank you so much. I will install cuda 10 on my machines for now. For me, being able to just start working on a new machine without installing/updating anything except nvidia driver is a very nice convenience feature of pytorch. All I need to do is just add torch to Pipfile, and it will work on all platforms (I use Fedora, Ubuntu, and OSX).

**Comment by soumith** [comment]
fixed in v1.0.1 release.

**Comment by soumith** [comment]
nope, didn't get fixed in v1.0.1 wheels (got fixed on conda).
I'm looking at regenerating wheels with a fix and uploading.

**Comment by soumith** [comment]
actually, I double-checked, it did get fixed.
