### ISSUE TITLE
torch.Tensor.bernoulli_ gives different results in mac and linux

### ISSUE THREAD

**Issue by alasdairtran** [pytorch/pytorch#15714]
## 🐛 Bug

Running the following commands

```python
import torch
torch.manual_seed(0)
a = torch.zeros(5).long()
a.bernoulli_()
```

give different samples in linux and mac. On my Ubuntu 18.04, I get `tensor([1, 0, 0, 1, 1])`. On my MacOS Mojave, I get `tensor([0, 0, 1, 0, 0])`. On the same machine, it always gives the same sample, but it's not reproducible across machines.

I sampled from other distributions such as `normal_()`, `uniform_()` and `random_()`, and they all work fine (i.e. give the same sample across machines). The non-inplace version of Bernoulli `bernoulli()` works fine too.

This non-reproducible problem seems to only occur with the in-place `bernoulli_()` function.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.0
 - How you installed Pytorch: conda
 - Python version: 3.7

**Comment by SsnL** [comment]
Determinism is not guaranteed across version/hardware/platforms.

**Comment by ailzhang** [comment]
Close via @SsnL 's comment
