### ISSUE TITLE
LibTorch C++ does not run on Windows

### ISSUE THREAD

**Issue by oroojlooy** [pytorch/pytorch#15711]
## 🐛 Bug

I used `cmake4eclipse` to build torch C++ version 1.0 stable in Windows 10. Basically, I have the following CMakeLists.txt to build the mnist example:

```

    cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
    project(mnist)
    
    set(CMAKE_PREFIX_PATH "C:/rl/libtorch/share/cmake/Torch")
    set(Torch_DIR "C:/rl/libtorch")
    
    find_package(Torch REQUIRED)
    
    option(DOWNLOAD_MNIST "Download the MNIST dataset from the internet" ON)
    if (DOWNLOAD_MNIST)
      message(STATUS "Downloading MNIST dataset")
      execute_process(
        COMMAND python ${CMAKE_CURRENT_LIST_DIR}/download_mnist.py
          -d ${CMAKE_BINARY_DIR}/data
        ERROR_VARIABLE DOWNLOAD_ERROR)
      if (DOWNLOAD_ERROR)
        message(FATAL_ERROR "Error downloading MNIST dataset: ${DOWNLOAD_ERROR}")
      endif()
    endif()
    
    set(CMAKE_BUILD_TYPE Debug) 
    add_executable(mnist mnist.cpp)
    target_compile_features(mnist PUBLIC cxx_range_for)
    set_property(TARGET mnist PROPERTY CXX_STANDARD 14)
    target_link_libraries(mnist ${TORCH_LIBRARIES})

```

## To Reproduce

load the `CmakeLists.txt` along with the `mnist.cpp` and `download_mnist.py` files in a folder and start a project in `eclipse IDE for C/C++`, version `2018-09 (4.9.0)`. In **project_properties->C/C++ Build->Tool Chain Editor**, set `CMake Builder (GNU Make)` and select `MinGW GCC`. Then, in **project_properties->C/C++ General->Preprocessor Include Paths Macros etc.->Providers** select `CMAKE_EXPORT_COMPILE_COMMANDS Parser [Shared]` and move it up, as it is explained in 
https://stackoverflow.com/questions/9453851/how-to-configure-eclipse-cdt-for-cmake/38716337 

Then, you can compile the `mnist` project without any error. But, when you run it get `<terminated> (exit value 390) a.exe [some address]`. I tried to debug this code to find out the problem, but I cannot see the debug screen, and instead I get a page, containing: 

`No source available for "main() at 0x401463" `
`view Disassembly...`
`Configure when this editor is shown` `Preferences` 

Running the debug mode to the end results in a same error. 

## Expected behavior
It should start running the code and train a NN for MNIST.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0 stable C++
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): I downloaded the C++ stable version. 
 - Build command you used (if compiling from source): NA
 - Python version: NA
 - CUDA/cuDNN version: I just CPU 
 - GPU models and configuration: NA
 - Any other relevant information:

## Additional context

I can run `mnist.cpp` in Linux without any problem, though I use `cmake -G "Eclipse CDT4 - Unix Makefiles" ./` to create a `eclipse` project. I did not know how I can use `cmake -G "Eclipse CDT4 - Unix Makefiles" ./` in Windows and I used `cmake4eclipse`, but seems that it is all right. I also tried a simple example to just create a tensor with random values, but got same error. I appreciate any help or comments.

**Comment by peterjc123** [comment]
I don't think you could you could build that with MinGW because the code is written in c++ and MinGW is not abi-compatible with MSVC. So I think you may need to compile with MSVC. And also in MSVC, the configuration debug and release could not be mixed. So you will have to choose Release as we only provide library with the Release configuration.

**Comment by soumith** [comment]
closing based on peterjc123's comment

**Comment by lel4866** [comment]
I tried building and running this using Visual Studio on Windows 10. It builds fine (after you set the configuration to x64), but gets and exception in the first call to register_module("conv1", conv) in the Net constructor:

![image](https://user-images.githubusercontent.com/1310042/50726731-3e456f00-10df-11e9-9412-55a7875a2c95.png)

**Comment by anguoyang** [comment]
@peterjc123  I used visual studio/libtorch on both release and debug mode, all failed to load the model, it seems that the latest libtorch has bug on it.
