### ISSUE TITLE
Gradient size mismatch for nn.Bilinear

### ISSUE THREAD

**Issue by Nilabhra** [pytorch/pytorch#1571]
The weights of the Bilinear layer are of the shape (inp1, inp2, op) while the gradients are of the shape (inp1, inp2). A possible implementation error in the backward function of the Bilinear layer here: https://github.com/pytorch/pytorch/blob/5bb13485b8484a37f9afad67582512cf53ed13cb/torch/nn/_functions/linear.py#L35

**Comment by peterGuang** [comment]
I have got the problem when using Bilinear layer. How to solve it?

#!coding=utf8
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
dim = 5
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.T1 = nn.Parameter(torch.randn(dim,dim,dim),requires_grad=True)
    def forward(self,x1,x2):
        return F.tanh(F.bilinear(x1,x2,self.T1))
import torch.optim as optim
net = Net()
optimizer = optim.SGD(net.parameters(), lr = 0.01)
for p in net.parameters():
    print(p.size())
for x in [1]:
    optimizer.zero_grad()
    x1 = Variable(torch.randn(1,5))
    x2 = Variable(torch.randn(5,1))
    loss = net(x1,x2)
    print(loss)
    loss.backward(torch.randn([1,5]))
    optimizer.step()


The output:

(5L, 5L, 5L)
Variable containing:
 0.3141  0.9993  1.0000  0.9987 -0.9995
[torch.FloatTensor of size 1x5]

Traceback (most recent call last):
  File "/home/peter/workspace/stocktrend/model/test_torch.py", line 25, in <module>
    loss.backward(torch.randn([1,5]))
  File "/home/peter/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 145, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/peter/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/home/peter/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/linear.py", line 80, in backward
    grad_weight = torch.mm(buff.t(), input2)
RuntimeError: size mismatch, m1: [5 x 1], m2: [5 x 1] at /home/peter/下载/pytorch-master/torch/lib/TH/generic/THTensorMath.c:1237

Process finished with exit code 1

**Comment by Nilabhra** [comment]
Thanks for the fix!
