### ISSUE TITLE
Error in error information

### ISSUE THREAD

**Issue by MilesQLi** [pytorch/pytorch#15720]
When I use model.load_state_dict(checkpoint['model_state_dict']) to load params, I get 

RuntimeError: Error(s) in loading state_dict for hierarchical_transformer:
	size mismatch for block_level.position_enc.weight: copying a param of torch.Size([51, 30]) from checkpoint, where the shape is torch.Size([18290, 30]) in current model.

But in fact, it is just the opposite. The shape in the checkpoint is [18290,30], in the current model is [51,30]

**Comment by ezyang** [comment]
This sounds easy enough to fix. Would you like to submit a PR?

**Comment by MilesQLi** [comment]
I just checked it. It's fixed in the current version. I used the stable version.
