### ISSUE TITLE
how to call libtorch by makefile

### ISSUE THREAD

**Issue by ismymajia** [pytorch/pytorch#15727]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

now libtorch is used by cmake, eg: cmake -DCMAKE_PREFIX_PATH=xxx
but if i need to use libtorch by Makefile. i set below:
LIB       +=-L/data/libtorch/lib -ltorch -lc10 -lcaffe2 -lmkldnn -lgomp -lcaffe2_gpu -lnvToolsExt
LIB  	  +=-L/usr/local/cuda/lib64 -lcudnn -lcudart -lcublas -lcurand -lcusolver -lnvrtc
LIB  	  +=-L/usr/local/cuda/lib64/stubs/ -lcuda
but occur error when runing program ,
initialize error:CUDA error (35): CUDA driver version is insufficient for CUDA runtime version (getNumGPUs at /data/svn/pytorch/aten/src/ATen/cuda/detail/CUDAHooks.cpp:202)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7febfae1cdf5 in /data/libtorch/lib/libc10.so)
frame #1: at::cuda::detail::CUDAHooks::getNumGPUs() const + 0xbb (0x7feb9987e4bb in /data/libtorch/lib/libcaffe2_gpu.so)
frame #2: torch::cuda::device_count() + 0x1a (0x7febfb7cd01a in /data/libtorch/lib/libtorch.so.1)
frame #3: torch::cuda::is_available() + 0x9 (0x7febfb7cd039 in /data/libtorch/lib/libtorch.so.1)

how to use libtorch in makefile？？

**Comment by ismymajia** [comment]
help!

**Comment by ismymajia** [comment]
fix it

**Comment by soumith** [comment]
> CUDA driver version is insufficient for CUDA runtime version 

the error message is right there. Upgrade your CUDA driver.

If you have questions, post on https://discuss.pytorch.org
