### ISSUE TITLE
how to build cuda extension (without at::tensor)?

### ISSUE THREAD

**Issue by JackieQiang** [pytorch/pytorch#15729]
### Please note that this issue tracker is not a help form and this issue will be closed.

I write an CUDA code about Connected Component Labeling(CCL).Now I want to use this CUDA code to extension pytorch.I seen the "CUSTOM C++ AND CUDA EXTENSIONS" tutorial(https://pytorch.org/tutorials/advanced/cpp_extension.html)。but this tutorial seem use Aten with at::Tensor operation.I CUDA code include atomicMin. atomicMin function need input is int or int*. I don't know how to transform at:Tensor to int*!!
someone could help me? tell me how to transform at::Tensor to int*. 
or
how build cuda extension(without at::tensor input)

**Comment by ezyang** [comment]
You can get a pointer to tensor contents using `tensor.data<int32_t>()` (assuming that this is an IntTensor).

**Comment by JackieQiang** [comment]
@ezyang Thank you.It's very helpful! 
now I have another question. How can I use the texture memory in cuda extension?
I try to use the cuda function "cudaBindTextureToArray()" but this function need GPU array.I don't know how transform at:Tensor to a GPU array.

**Comment by ezyang** [comment]
I don't know how to do this. Maybe someone on the forums will know.
