### ISSUE TITLE
[JIT] @script tensor.cpu() raises unknown builtin op error

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#15754]
## 🐛 Bug

`tensor.cpu()`, `tensor.cuda()` are not available in jit script methods despite `tensor.to(device=...)` is ok.

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    @torch.jit.script
  File "/home/qbx2/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 691, in script
    _jit_script_compile(mod, ast, _rcb, get_default_args(fn))
RuntimeError:
unknown builtin op:
@torch.jit.script
def test(tensor):
    return tensor.cuda()
           ~~~~~~~~~~~ <--- HERE

```

## To Reproduce

```python
import torch


@torch.jit.script
def test(tensor):
    return tensor.cpu()
```

## Expected behavior

Should work same as `tensor.to(device='cpu')`

## Environment

Collecting environment information...
PyTorch version: 1.0.0a0+db5d313
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 410.48
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/lib64/libcudnn.so.7.4.1
/usr/local/cuda-10.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] magma-cuda100             2.4.0                         1    pytorch
[conda] torch                     1.0.0a0+db5d313           <pip>

**Comment by suo** [comment]
Thanks for the report! Seems like a good feature enhancement to make, we'll put it in our queue.

**Comment by suo** [comment]
This feature is in master
