### ISSUE TITLE
Can not install the PyTorch 1.0 

### ISSUE THREAD

**Issue by MrLinNing** [pytorch/pytorch#15752]
## 🐛 Bug
``` 
>>>import torch 
     from torch._C import *
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

```

 - PyTorch Version 1.0:
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): pip install torch torchvision 
 - Python version: python 3.6.7
 - CUDA/cuDNN version: cuda 9.0 / cuDNN 7.1
 - GPU models and configuration: GPU TITAN xp
 - Any other relevant information:

## Additional context

The PyTorch 0.4.0 is ok. But I need to use the new version of it.

**Comment by amiltonwong** [comment]
@MrLinNing , I came across the same issue as yours, how do you solve it?
