### ISSUE TITLE
[caffe2] Add blacklist capability for smaller mobile binaries

### ISSUE THREAD

**Issue by h6197627** [pytorch/pytorch#15755]
## 🚀 Feature
Caffe2 has whitelisting mechanism (https://github.com/facebookarchive/caffe2/pull/228) to reduce final binary size which is very useful for mobile apps. However, in my opinion, it is not really convenient to list all files to be compiled and is more appropriate to do the opposite - blacklisting file to exclude from compilation. It is easier to know what you don't really need and can exclude than to know every file that you need or needed by others as dependency.
Also with blacklisting it is more probable that after updating from master user won't have problems when building new version - it will include all newly added files into build automatically, but with whitelisting list should be updated every time to include newly added files.

Considering that in general it is functionality duplication (all that is possible to archive with whitelist is achievable with blacklist and vice versa) but with better convenience, I am opening this proposal to discuss addition of this functionality. Or it might be more relevant to replace whitelisting with blacklisting to avoid functionality duplication.

I have implemented this change locally for my project and able to provide pull requests for both variants.

**Comment by Palmitoxico** [comment]
It seems that the CAFFE2_WHITELIST flag is broken (I coudn't successfully link an executable even with all caffe2 source files listed on my whitelist file). However I've found a workaround: just strip the final executable.

I've tested with the Android NDK 16b, and calling ```arm-linux-androideabi-strip``` reduced the final binary from 480MiB to just 8MiB and everything worked as expected.

**Comment by h6197627** [comment]
In general I found using whitelisting very complicated. Almost every configuration change require new whitelist which will include newly added files. By applying blacklisting only to caffe2 operators which I am not using I am able to reduce final so file from 8mb to ~4.5mb. With more thorough file analysis I think it is possible to reduce more.
Also I can recommend passing this flags to compiler (through CMAKE_CXX_FLAGS) for android building -DCAFFE2_NO_GRADIENT_OPS -DCAFFE2_NO_OPERATOR_SCHEMA

**Comment by h6197627** [comment]
PyTorch mobile now has ability to compile only subset of needed ops.
