### ISSUE TITLE
Local build fails with module 'torch' has no attribute 'potrs'

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#15763]
## 🐛 Bug

Build on macOS fails with error below.

@vishwakftw @soumith could this be related to #15334?

## To Reproduce

```
git clone --recursive https://github.com/pytorch/pytorch.git
cd pytorch
pip3 install future leveldb numpy protobuf pydot python-gflags pyyaml scikit-image setuptools six hypothesis typing tqdm
pip3 install torchvision
python3 setup.py install

> python3
Python 3.7.1 (default, Nov  6 2018, 18:46:03) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxxx/Desktop/pytorch_virtualenv/lib/python3.7/site-packages/torch/__init__.py", line 301, in <module>
    from . import _torch_docs, _tensor_docs, _storage_docs
  File "/Users/xxxx/Desktop/pytorch_virtualenv/lib/python3.7/site-packages/torch/_torch_docs.py", line 3414, in <module>
    add_docstr(torch.potrs, r"""
AttributeError: module 'torch' has no attribute 'potrs'
```

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Mac OSX 10.14.2
GCC version: Could not collect
CMake version: version 3.13.2

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by lutzroeder** [comment]
Still repros after running uninstall twice.

```
~: python3 -c 'import sys; print("\n".join(sys.path))'

/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7
/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
/Users/xxxxxxxxxx/Library/Python/3.7/lib/python/site-packages
/usr/local/lib/python3.7/site-packages
```

**Comment by vishwakftw** [comment]
This is weird, because `torch.potrs` can't be found in [the file](https://github.com/pytorch/pytorch/blob/master/torch/_torch_docs.py) that the error message claims to read it from.

**Comment by lutzroeder** [comment]
Running `pip3 install torchvision` after `python3 setup.py install` makes it work. Could it be that `torchvision` installs the 1.0 release which now conflicts with rebuilding from source?

**Comment by vishwakftw** [comment]
I suppose if PyTorch is not available when installing torchvision, it installs the latest available release as a requirement. As you have mentioned, this conflicts with the source build.

**Comment by bisandud** [comment]
Please I have same problem but after doing all the suggestions here this is what i am having
Epochs: 0%
0/100 [00:00<?, ?it/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\Dropbox\Implement2020\Codes\DNNETSC\matic_pytorch.py in <module>
     13     for sample in lc_database: # data samples
     14         targets = torch.tensor(sample['label']).repeat(net.n_mc_samples)
---> 15         output = net(sample)
     16         optimizer.zero_grad()
     17         loss = criterion(output, targets)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~\Dropbox\Implement2020\Codes\DNNETSC\matic_pytorch.py in forward(self, sample, return_gp)
     92         err = lcdata[:, 2]
     93         # Gaussian process fit
---> 94         mu, R, reg_points = self.GP_fit_posterior(mjd, mag, err, P)
     95         # Sampling layer
     96         z = self.sample_from_posterior(mu, R)

~\Dropbox\Implement2020\Codes\DNNETSC\matic_pytorch.py in GP_fit_posterior(self, mjd, mag, err, P, end, jitter)
     66         Ktx = self.stationary_kernel(mjd, reg_points, non_trainable_kparams)
     67         Kxx = self.stationary_kernel(reg_points, reg_points, non_trainable_kparams)
---> 68         Ltt =  torch.potrf(Ktt, upper=False)  # Cholesky lower triangular
     69         # posterior mean and covariance
     70         tmp1 = torch.t(torch.trtrs(Ktx, Ltt, upper=False)[0])

AttributeError: module 'torch' has no attribute 'potrf'
