### ISSUE TITLE
Documentation is slow and scroll-jumpy

### ISSUE THREAD

**Issue by guillaume-chevalier** [pytorch/pytorch#15760]
## 📚 Documentation

When a documentation page loads, I need to wait a few seconds before being able to CTR+F (find in page) what I want. While it loads, things jump around. I preferred the old documentation website, I don't like the upgrade, although the upgrade looks way nicer, it was previously more functional.

**Comment by soumith** [comment]
cc: @brucejlin @brianjo

**Comment by rgommers** [comment]
This was fixed in the doc restructure in gh-37419. https://pytorch.org/docs/master/nn.html loads fast now. And a duplicate issue with gh-14686. So closing this. Thanks for the report @guillaume-chevalier
