### ISSUE TITLE
macOS Caffe2 Python doesn't work with 'pip install .' (originally: Build fails on macOS with Library not loaded: @rpath/libcaffe2.dylib)

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#15762]
## 🐛 Bug

Build on macOS fails with error below.

## To Reproduce

```
virtualenv --quiet -p python3 ./pytorch_virtualenv
source ./pytorch_virtualenv/bin/activate
git clone --recursive https://github.com/pytorch/pytorch.git
cd pytorch
pip3 install future leveldb numpy protobuf pydot python-gflags pyyaml scikit-image setuptools six hypothesis typing tqdm
pip3 install .
cd ..
python3 -c "import caffe2.python.core"
```

Error:
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
CRITICAL:root:Cannot load caffe2.python. Error: dlopen(/Users/xxxx/Desktop/pytorch_virtualenv/lib/python3.7/site-packages/caffe2/python/caffe2_pybind11_state.cpython-37m-darwin.so, 10): Library not loaded: @rpath/libcaffe2.dylib
  Referenced from: /Users/xxxx/Desktop/pytorch_virtualenv/lib/python3.7/site-packages/caffe2/python/caffe2_pybind11_state.cpython-37m-darwin.so
  Reason: image not found
```

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Mac OSX 10.14.2
GCC version: Could not collect
CMake version: version 3.13.2

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by lutzroeder** [comment]
```
~/Desktop: find . -name "libcaffe2.dylib"
./Desktop/pytorch_virtualenv/lib/python3.7/site-packages/torch/lib/libcaffe2.dylib
```

2. Yes, using `python3 setup.py install` works. `pip3 install .` worked as well until recently.

**Comment by ezyang** [comment]
That's pretty weird, but helps narrow it down a bunch for us, thanks. CC @pjh5 @anderspapitto @soumith

**Comment by sklipnoty** [comment]
I seem to have the same problem. 

(veenv) $ python2 detectron/tests/test_spatial_narrow_as_op.py
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
CRITICAL:root:Cannot load caffe2.python. Error: dlopen(DensePose/DensePose/veenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so, 10): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from:  DensePose/DensePose/veenv/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so
  Reason: image not found

**Comment by pjh5** [comment]
@sklipnoty you have a different problem. Can you open a new issue?

**Comment by lutzroeder** [comment]
No longer repros at TIP.
