### ISSUE TITLE
"Trying to resize storage that is not resizable" when calling pin_memory() on some zero-dimensional tensors

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#15770]
## 🐛 Bug

"Trying to resize storage that is not resizable" error raises when calling `pin_memory()` on some zero-dimensional tensors

## To Reproduce

```
$ python
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> x = torch.randn(2, 1); x.pin_memory()
tensor([[-0.0747],
        [ 0.4300]])
>>> x = torch.randn(0); x.pin_memory()
tensor([])
>>> x = torch.randn(0, 0); x.pin_memory()
tensor([], size=(0, 0))
>>> x = torch.randn(1, 0); x.pin_memory()
tensor([], size=(1, 0))
>>> x = torch.randn(0, 1); x.pin_memory()
tensor([], size=(0, 1))
>>> x = torch.randn(0, 5); x.pin_memory()
tensor([], size=(0, 5))
>>> x = torch.randn(0, 50); x.pin_memory()
tensor([], size=(0, 50))
>>> x = torch.randn(50, 0); x.pin_memory()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Trying to resize storage that is not resizable at /home/qbx2/pytorch/aten/src/TH/THStorageFunctions.cpp:70
>>> x = torch.randn(2, 0); x.pin_memory()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Trying to resize storage that is not resizable at /home/qbx2/pytorch/aten/src/TH/THStorageFunctions.cpp:70
>>> x = torch.randn(0, 2); x.pin_memory()
tensor([], size=(0, 2))
```

## Expected behavior

All zero-dimensional tensors should behave in same way.

## Environment

PyTorch version: 1.0.0a0+db5d313
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 410.48
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/lib64/libcudnn.so.7.4.1
/usr/local/cuda-10.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] magma-cuda100             2.4.0                         1    pytorch
[conda] torch                     1.0.0a0+db5d313           <pip>

**Comment by gchanan** [comment]
CC @yf225.

**Comment by yf225** [comment]
@qbx2 This bug seems to be fixed on master, could you try installing PyTorch via `pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html` and then run the code again?

**Comment by qbx2** [comment]
Yes, it works. Thank you

**Comment by zmabzug** [comment]
Has this bugfix been integrated into a stable (i.e., non-nightly) release yet?

**Comment by xieshuaix** [comment]
Got this error top when constructing a float32 tensor from float64 numpy array, torch.FloatTensor(array), torch.from_numpy(array).type(torch.float32) and torch.from_numpy(array.astype(np.float32)) all give this error. Constructing a float64 tensor instead seems fine.

**Comment by huanghonggit** [comment]
I also got this error 
`    batch_bert_features = torch.from_numpy(batch_bert_features).type(torch.float32)  # .float
RuntimeError: Trying to resize storage that is not resizable at /opt/conda/conda-bld/pytorch_1550796191843/work/aten/src/TH/THStorageFunctions.cpp:70`

**Comment by Julia1211** [comment]
@huanghonggit have you solved the problem,and how?
