### ISSUE TITLE
Implementation of ISTFT

### ISSUE THREAD

**Issue by mravanelli** [pytorch/pytorch#15778]
Hi,
is there any plan to implement the inverse short-time fourier transform (ISTFT)?  I saw that STFT is already implemented, but I cannot find the inverse transform. This would be a very important feature for people working on audio and speech.

Thank you!

Mirco

**Comment by SsnL** [comment]
Yes, we want to do this, but no one has spent time to actually implement it yet.... Duplicate of https://github.com/pytorch/pytorch/issues/3775

**Comment by mravanelli** [comment]
Great! I can help you debug it!

**Comment by vadimkantorov** [comment]
@SsnL Seems that ISTFT has been implemented in torchaudio: https://pytorch.org/audio/functional.html#istft

It would be great if it was relocated to the core

**Comment by vincentqb** [comment]
Closing since duplicate of #3775
