### ISSUE TITLE
how to get C10 OPERATOR's gradient op in caffe2

### ISSUE THREAD

**Issue by dongfangduoshou123** [pytorch/pytorch#15783]
## ❓ Questions and Help
I find now caffe2 add the ability to registry c10 op for caffe2 to dispatch use macro like: REGISTER_C10_OPERATOR_FOR_CAFFE2_DISPATCH....
1、My question is that  how to get C10  forward op's gradient op in caffe2? 
2、Is the Purpose of add c10 op dispatcher is to share the torch op to caffe2 or else purpose ?

thankyou!

**Comment by ezyang** [comment]
This mechanism is currently experimental and not supported. For caffe2 use cases you should use the standard mechanism for now. The eventual plan is to make all Torch operators callable from Caffe2 and vice versa. CC @smessmer

**Comment by dongfangduoshou123** [comment]
Very very thank you for your authority anwser!

**Comment by smessmer** [comment]
Yes, please don't use the c10 op dispatcher yet, this is very experimental.

**Comment by dongfangduoshou123** [comment]
c10 subproject's purpose is to share ops between pytorch and caffe2; I wonder why this dispatching project is named c10; what's the meaning?

**Comment by dongfangduoshou123** [comment]
"Ultimately, all operators should be c10 operators and use the c10 dispatcher" ,Is this mean Ultimately, use caffe2's standard op in caffe2 will also use the c10 dispatcher?
