### ISSUE TITLE
cuda tensor to cpu is very time-consuming

### ISSUE THREAD

**Issue by ismymajia** [pytorch/pytorch#15789]
how to convert cuda tensor to cv::Mat ?

now i use cputensor = cudatensor.cpu(); then convert cputensor to cv::Mat, but i found that cudatensor.cpu() is very time-consuming. eg: it cost 100ms when i convert 500x300 image to cpu data from cudatensor.

any other fast method ? how to get cudatensor data fastly?

**Comment by ismymajia** [comment]
cpu tensor  to cuda tensor is very fast. eg: 500x300 image from cpu to cuda tensor cost 2ms.
but 500x300 image from cuda to cpu tensor cost 100ms.

**Comment by fmassa** [comment]
The CUDA operations are asynchronous, so you are also measuring the time to run the network in your `.cpu()` timing.

**Comment by fmassa** [comment]
If you run your exemple with `CUDA_LAUNCH_BLOCKING=1 ./my_script`, you'll make all CUDA operations synchronous, and the time for the `.cpu()` call will show to be much smaller

**Comment by soumith** [comment]
please move discussion to https://discuss.pytorch.org
