### ISSUE TITLE
libtorch memory leak with torch::load optimizer

### ISSUE THREAD

**Issue by ShigekiKarita** [pytorch/pytorch#15792]
## 🐛 Bug

torch::load optimizer does memory leak in CPU and GPU.

## To Reproduce

```c++
#include <torch/torch.h>

// you can play with CUDA memory using .to(torch::Device(torch::kCUDA))
int main() {
    auto model = torch::nn::Linear(4096, 4096);
    auto optimizer = torch::optim::Adam(model->parameters(), 0.01);

    auto loss = model->forward(torch::zeros({1, 4096})).sum();
    loss.backward();
    optimizer.step();
    optimizer.zero_grad();
    torch::save(optimizer, "/tmp/optimizer.pt");
    while (true) {
        torch::load(optimizer, "/tmp/optimizer.pt");
    }
}
```

1. run this snippet with conda pytorch 1.0.0 or latest libtorch zip
1. you will see OOM or memory increasing in top
1. I also tested model loading but it did not leak the memory

## Expected behavior

torch::load should not leak it. maybe it should release previous optimizer states.

## Environment

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 2.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

I used libtorch with build-version 1.0.0 as above.
Or conda's pytorch as follows

```
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] torch (1.0.0)
[pip] torch-autograd-solver (0.1.0)
[pip] torchvision (0.2.1)
[pip] warpctc-pytorch (0.1.1)
[conda] Could not collect
```

## Additional context

none

**Comment by ShigekiKarita** [comment]
P.S. I think that optimizer's serialization can be similar to module's `register_parameter` way instead of hard coded serialization lines like
```c++
  // these two functions only calls `static void serialize(..)`
  void save(serialize::OutputArchive& archive) const override;
  void load(serialize::InputArchive& archive) override;

  template <typename Self, typename Archive>
  static void serialize(Self& self, Archive& archive) {
    TORCH_OPTIM_SERIALIZE(step_buffers);
    TORCH_OPTIM_SERIALIZE(exp_average_buffers);
    TORCH_OPTIM_SERIALIZE(exp_average_sq_buffers);
    TORCH_OPTIM_SERIALIZE(max_exp_average_sq_buffers);
 }
 // TORCH_OPTIM_SERIALIZE calls torch::optim::detail::serialize and assumes that the variable self is defined
```
This is little bit too nested and complex . I do not want to call `detail` namespace (even wrapped in that macro) when I define my own optimizer because it seems to be private conventionally. https://stackoverflow.com/questions/26546265/what-is-the-detail-namespace-commonly-used-for

**Comment by ShigekiKarita** [comment]
https://github.com/pytorch/pytorch/blob/fe15d6a2c231a7bc1b32781217ed336ccf9adff7/torch/csrc/api/include/torch/optim/serialize.h#L46-L60

I suspect this `emplace_back` just appends tensors to optimizer's buffers without `.clear()` existing tensors. This can result in the constant increasing of memory allocation. However, I do not have time to debug this now. Has anyone reproduces this memory leak yet?

**Comment by ezyang** [comment]
cc @goldsborough

**Comment by goldsborough** [comment]
https://github.com/pytorch/pytorch/pull/15926 fixes the bug. I also moved the serialize functions out of the detail namespace. The macro is really a convenience for the library implementation. I've prefixed it with an underscore to make this clearer. You can just call the function yourself or define your own macro.

The `register_parameter` approach might be viable although optimizers don't just have one type of buffer, but tensor buffers, int buffers, float buffers which would each need to be stored separately. I think a registration-based API would be a little easier on users, but defining your own optimizers is rare enough that I wouldn't rewrite the whole API for this right now.

**Comment by ShigekiKarita** [comment]
Thanks for the fix. I agree with your thoughts on the API.
