### ISSUE TITLE
Sudden decrease in performance after N numbers of consecutive calls to forward (on GPU)

### ISSUE THREAD

**Issue by AchkanSalehi** [pytorch/pytorch#15793]
## 🐛 Bug

Given the simple implementation (provided below) of a separable `3x3` convolution as two consecutive convolutions with kernels of size `(3,1)` and `(1,3)`, performance suddenly gets worse after `N` consecutive calls to forward (on GPU), where `N` seems to usually be in the `[150, 250]` interval. This is illustrated by the figure below (generated by the provided snippet). This pattern seems to hold with different channel or batch numbers, as well as different width/height. 

![figure_1](https://user-images.githubusercontent.com/12658388/50775999-b2bf1000-128f-11e9-9ec7-dc41eea37ab5.png)

## To Reproduce

Just run the code below.

```
import torch
import time
import matplotlib.pyplot as plt


class RankSeparable(torch.nn.Module):
    def __init__(self, channels, kernel_size=3):
        super().__init__()
        self.conv1 = torch.nn.Conv2d(
            channels,
            channels,
            kernel_size=(kernel_size, 1),
            padding=((kernel_size - 1) // 2, 0),
            bias=True,
            stride=1)

        self.conv2 = torch.nn.Conv2d(
            channels,
            channels,
            kernel_size=(1, kernel_size),
            padding=(0, (kernel_size - 1) // 2),
            bias=True,
            stride=1)

    def forward(self, in_tensor):
        output = self.conv1(in_tensor)
        output = self.conv2(output)
        return output


if __name__ == '__main__':

    torch.cuda.set_device(0)

    num_channels = 256
    batch = torch.rand(1, 256, 256, 512)
    batch = batch.cuda()

    separable = RankSeparable(num_channels, kernel_size=3)
    separable = separable.cuda()
    separable = separable.eval()

    times = [] 
    num_runs = 2000
    skip = 1  # We will just skip the first execution because it is usually slower
    with torch.no_grad():
        avg_time = 0
        for i in range(num_runs):
            start = time.time()
            separable.forward(batch)
            end = time.time()
            #torch.cuda.empty_cache() #this just increases the execution time
            if (i >= skip):
                elapsed = (end - start) * 1000
                avg_time += elapsed
                times.append(elapsed)
        avg_time /= (num_runs - skip)
        print("avg_time=={}ms, num_runs=={}".format(avg_time, num_runs))
    plt.plot(times)
    plt.show()
```

## Expected behavior

The execution time should stay more or less constant, the huge jump shouldn't happen.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GT 710

Nvidia driver version: 396.37
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/lib64/libcudnn.so
/usr/local/cuda-9.2/lib64/libcudnn.so.7.1.4
/usr/local/cuda-9.2/lib64/libcudnn.so.7_back
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.15.4)
[pip3] torch (1.0.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect

## Additional context

This seem to happen with both version 0.4.1 and 1.0 of pytorch, as well as with cuda 10.0.

**Comment by colesbury** [comment]
You are not measuring timing accurately. CUDA launches are asynchronous with respect to the CPU so you are only measuring the time it takes to enqueue the operation, not to execute it. Eventually the internal queue in the CUDA driver gets full and enqueuing waits on a past operation to finish. To measure timing of CUDA operations you should use something like:

```
            torch.cuda.synchronize()
            start = time.time()
            separable.forward(batch)
            torch.cuda.synchronize()
            end = time.time()
```

to ensure that all previous operations are finished before `start` and all `separable.forward` operations are finished before `end`.

Alternatively, you could use nvprof or the PyTorch autograd profiler (https://pytorch.org/docs/stable/autograd.html#torch.autograd.profiler)

**Comment by AchkanSalehi** [comment]
@colesbury Thank you very much for your answer, that was really useful.
