### ISSUE TITLE
Libtorch: how can I define my own datasets and dataloader

### ISSUE THREAD

**Issue by apchenstu** [pytorch/pytorch#15801]
## ❓ Questions and Help
Hi all, anyone knows how to define my dataset, as I want to train models on c++ platform, and the example gave an "MNIST" dataset class, but how can I define a dataset base on my input and target folder? Thanks!

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

**Comment by ChopinSharp** [comment]
> please use https://discuss.pytorch.org for questions

He/She asked here because there isn't a single answer in the forums ...
