### ISSUE TITLE
DataLoader freezes randomly when num_workers > 0 (Multiple threads train models on different GPUs in separate threads)

### ISSUE THREAD

**Issue by simonhessner** [pytorch/pytorch#15808]
## 🐛 Bug

I wrote a script that is performing gridsearch on some hyperparameters for an image regression network. It creates a thread for each available GPU (I have 4 Titan X in this machine) and each thread trains a model according to a configuration that was assigned to this thread (via a threadsafe queue that contains all possible hyperparameter configurations).

Each thread loads the dataset from a h5 file and iterates over it using a DataLoader. When I use num_workers = 0, everything works perfectly (but is slow). When I use num_workers > 0, my threads freeze while iterating over the DataLoader (at random positions). As soon as 3 out of my 4 threads have frozen, the last one continues running without any problems. I have tried pin_memory = True and False, no difference. The higher num_workers, the earlier threads start freezing.

I am not using docker, just a standard Ubuntu 16.04 with Python 3.7 in a conda virtualenv.

I also wrote a Thread in the forum (https://discuss.pytorch.org/t/training-freezes-when-using-dataloader-with-num-workers-0/34055), but I think it better fits here. Feel free to close any of those.

## To reproduce

1. Create a thread for each of your available GPUs
1. Use DataLoader in each thread to iterate over your data set
1. Train a model on a different GPU in every thread, using the DataLoader

The most important parts of my code are:

```
        trainTransform = transforms.Compose([ transforms.ToTensor() ])
        testTransform = transforms.Compose([ transforms.ToTensor() ])

        with h5py.File(self.data, 'r') as f:
            train_dataset = MyDataset(f['train'], transform=trainTransform, gpu=self.gpu_id)
            val_dataset = MyDataset(f['test'], transform=testTransform, gpu=self.gpu_id)
            
        dataloader_params = {
            'batch_size' : config['batch_size'],
            'pin_memory' : True,
            'num_workers' : 32
        }

        train_loader = DataLoader(train_dataset, shuffle=True, **dataloader_params)
        val_loader = DataLoader(val_dataset, shuffle=False, **dataloader_params)
```

And MyDataset

```
from torch.utils.data import Dataset
class MyDataset(Dataset):
     def __init__(self, f, idxl=None,idxr=None, transform=None, gpu=None):
        if not idxl and idxr:
            self.images, self.coords = f['images'][:], f['coords'][:]
        elif idxr:
            self.images, self.coords = f['images'][:idxr], f['coords'][:idxr]
        else:
            self.images, self.coords = f['images'][idxl:], f['coords'][idxl:]

        if transform is None:
            self.images = np.transpose(self.images, (0, 3, 1, 2))   # B x H x W x C -> B x C x H x W

        self.transform = transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image=self.images[idx]
        landmark=self.coords[idx]
        if self.transform:
            image = self.transform(image)
        sample = {'image': image, 'landmarks': landmark}
        return sample
```

When iterating over train_loader and val_loader, the thread freezes randomly (and not reproducable)

## Expected behavior

Each thread should be able to train a model on a independent GPU. I have one thread per GPU and the assignment GPU <-> thread never changes

## Environment

> PyTorch version: 1.0.0
> Is debug build: No
> CUDA used to build PyTorch: 9.0.176
> 
> OS: Ubuntu 16.04.5 LTS
> GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
> CMake version: Could not collect
> 
> Python version: 3.7
> Is CUDA available: Yes
> CUDA runtime version: Could not collect
> GPU models and configuration: 
> GPU 0: GeForce GTX TITAN X
> GPU 1: GeForce GTX TITAN X
> GPU 2: GeForce GTX TITAN X
> GPU 3: GeForce GTX TITAN X
> 
> Nvidia driver version: 390.67
> cuDNN version: Probably one of the following:
> /usr/lib/x86_64-linux-gnu/libcudnn.so.7.2.1
> /usr/lib/x86_64-linux-gnu/libcudnn_static.a
> 
> Versions of relevant libraries:
> [pip] Could not collect
> [conda] 4.5.12

## Summarization

- One thread per GPU
- Each thread trains independent model
- Each thread has its own DataLoader
- Freezes randomly when num_worker > 0, works fine (but too slow) when num_worker = 0

If you need more information, please let me know.

**Comment by simonhessner** [comment]
I have solved the problem by using processes instead of threads. So in my main python file where I generate all possible hyperparameter combinations and then train each combination on a different GPU, I do not create a new thread and train a model in each thread. Instead, I fork new processes (one for each GPU) and create a `multiprocessing.Queue` that is passed to each subprocess. This queue contains hyperparameters to be trained. Each process is working on the same queue and training models on a dedicated GPU. 

In my tests, this works. There was no freezing for 3 hours now. Usually it freezed much earlier (after a few minutes), so I hope that it is really fixed.

**Comment by KunlinY** [comment]
Hi! I also met this problem. How do you replace process with thread in DataLoader? Could you please share your snippet?

**Comment by decowboy** [comment]
I am also experiencing this issue.
I feel it should be reopened.

**Comment by mkumar10** [comment]
Experiencing the same issue

**Comment by takatosp1** [comment]
+1

**Comment by wcneill** [comment]
Is a solution to this going to be published? One that the average person can implement. talking about "Processes and threads" is not helpful without further explanation.

**Comment by reverseark** [comment]
Got the same issue in cpu-only environment. It freezes when num_worker is ever set (even set to be 1!). When I do not set num_workers, everything goes well.

**Comment by korabelnikov** [comment]
> Got the same issue in **cpu-only** environment. It freezes when num_worker is ever set (even set to be 1!). When I do not set num_workers, everything goes well.
> 
> `torch.__version__: `'1.7.0'`
> 
> `sys.version: '3.8.3 (default, Jul 2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]'`

try 0 instead. Are you under Windows OS?

**Comment by ricardobatistad** [comment]
> Got the same issue in **cpu-only** environment. It freezes when num_worker is ever set (even set to be 1!). When I do not set num_workers, everything goes well.
> 
> `torch.__version__: `'1.7.0'`
> 
> `sys.version: '3.8.3 (default, Jul 2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]'`

Same issue. MacOS. This issue didn't occur in 1.6.0.

**Comment by mobassir94** [comment]
no helpful answer yet,
Dear @ptrblck 
i am having exact same issue : https://stackoverflow.com/questions/63674120/pytorch-dataloader-hangs-when-num-workers-0

i used,
anaconda virtual environment where i have,
python 3.8.5
pytorch 1.7.0
cuda 11.0
cudnn 8004
gpu rtx 3060ti
Is CUDA available: Yes

**Comment by mcclumpherty** [comment]
Same issue on 4Gb Jetson Nano.  Training halts after random period of time with workers > 0.  Without workers, the training takes roughly 2-3 times longer.

This really needs to be fixed.

**Comment by ghandzhipeng** [comment]
Hi, any solutions yet? I also met the same issue :)

**Comment by JonasFrey96** [comment]
Hello are here any news ? I am faceing same issue using PyTorch 1.7 and the current nightly version. 
4x 1080Ti and 2080Ti CUDA10.0 DDP. The error only occures if num_workers > 0

**Comment by mobassir94** [comment]
@JonasFrey96 i am using spyder now and it is working fine for me,it didn't work for me on jupyter notebook but it works on spyder.

**Comment by xsacha** [comment]
I seem to be getting the same issue since PyTorch 1.7 on Linux but it's working if num_workers is set to 1.

**Comment by RafailFridman** [comment]
Same issue here. Observed that the processes disappear from `top` command output when the training hangs. Any solutions?

**Comment by mhmtsarigul** [comment]
same problem on Ubuntu 20.04, pytorch 1.11, cuda 11.5. 

I downgrade torch to 1.10 stable and put "cv2.setNumThreads(0)" wherever i use cv2(this desceared number of threads on the system from 480 to 280) and the problem solved.

**Comment by nfrumkin** [comment]
same issue here. System Config:
8 A5000s
Ubuntu 20.04
Pytorch 1.10.0
Cuda 11.4

However, my script works on a single GPU, and it works on a different setup (2 A100s or 2 V100s, earlier Ubuntu/Pytorch versions).

**Comment by xsacha** [comment]
Same problem here @nfrumkin 
I also found if I try to kill the frozen process it takes down my system because one of the GPUs is stuck in the NVIDIA driver.
Possibly it is related to CUDA.

**Comment by nfrumkin** [comment]
@xsacha My problem was fixed by setting NCCL_P2P_DISABLE=1 before my training script. It seems that there's currently an issue with the P2P communication between GPUs in my case. https://github.com/pytorch/pytorch/issues/1637#issuecomment-730423426.

for example:  `NCCL_P2P_DISABLE=1  python3 train.py`

**Comment by xsacha** [comment]
Hope that works. Life saver!

**Comment by xsacha** [comment]
Unfortunately that didn't help at all :(

**Comment by GGGGGGXY** [comment]
same issue here
randomly hanging during the epoch
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/15215819/170950606-0d47f3c5-412f-412a-8944-36c8f74c17a2.png">

**Comment by thistlillo** [comment]
Same here. In my case it happens every time I use the dataloader inside of Python classes instead of a simple script, even if I do not see how that could be the case. I have tried pin_memory True/False .to(non_blocking True/False). Python 3.8 here, it is quite annoying that his behaviour has been being described everywhere for years without a single reply.

**Comment by thomassajot** [comment]
I am also experiencing the same issue. No workaround so far except running with `num_workers=0`
```
OS:            Ubuntu 18.4
notebook: 6.4.11
torch:        1.7.1
```

**Comment by xsacha** [comment]
None of the solutions I found anywhere on the internet ever worked.

I upgraded to a new server machine with a Threadripper Pro and Tesla GPUs at the start of the year and can now use num_workers=2 with nothing else changed.

The machine that requires num_workers=0 uses multiple GeForce 2080Ti and a regular Threadripper.

**Comment by paapu88** [comment]
Yes, the same here with two separate GPU machines. Also only working solution ` num_workers=0`.
My system
Ubuntu 22.04 Cuda 11.6 Tesla v100
and
Ubuntu 22.04 Cuda 11.6 NVIDIA GeForce
Using pytorch lightning with pytorch dataloader.
Terveisin, Markus

**Comment by SimonMen65** [comment]
Problem Solved !!
My system is
- Ubuntu 20.04
- CUDA 11.7
- Tesla V100
- python 3.6
- Nvidia 515
The trick to solve this is to add constrains on the starting script
`OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python train.py`
Now I can use `num_workers=6` and it really doubled the speed.
Hope this helps.

**Comment by insomniaaac** [comment]
None of the solutions above worked for me.
either
```
NCCL_P2P_DISABLE=1
```
or
```
OMP_NUM_THREADS=1 
MKL_NUM_THREADS=1
``` 
not worked!
