### ISSUE TITLE
ModuleList slows down with number of modules

### ISSUE THREAD

**Issue by senthilps8** [pytorch/pytorch#15811]
## 🐛 Bug
Forward pass on each module in an `nn.ModuleList` seems to slow down with increasing number of modules. 

## To Reproduce
Minimal example to reproduce:
```
import torch
import time
class BugModule(torch.nn.Module):
    def __init__(self, num_mod):
        torch.nn.Module.__init__(self)
        self.modlist = torch.nn.ModuleList(
            [torch.nn.Linear(1000, 50) for _ in range(num_mod)])

    def forward(self, x):
        out = self.modlist[0](x)
        return out


model2 = BugModule(2)
model200 = BugModule(200)
model2 = model2.cuda()
model200 = model200.cuda()
model2 = torch.nn.DataParallel(model2)
model200 = torch.nn.DataParallel(model200)

model2_times = []
model200_times = []
out = model2(torch.FloatTensor(50, 1000))
out = model200(torch.FloatTensor(50, 1000))
for i in range(200):
    t = time.time()
    out = model2(torch.FloatTensor(50, 1000))
    model2_times.append(time.time() - t)

for i in range(200):
    t = time.time()
    out = model200(torch.FloatTensor(50, 1000))
    model200_times.append(time.time() - t)

print('Model 2 takes {} sec'.format(sum(model2_times) / 200.0))
print('Model 200 takes {} sec'.format(sum(model200_times) / 200.0))

```

## Expected behavior
Model 2 takes 0.002837667465209961 sec
Model 200 takes 0.02810930848121643 sec

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 390.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.0)
[pip] torch (1.0.0)
[pip] torchfile (0.1.0)
[pip] torchvision (0.2.1)
[conda] blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] faiss-gpu                 1.3.0           py36_cuda9.0.176_1  [cuda90]  pytorch
[conda] mkl                       2018.0.3                      1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.0.10                   py36_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
[conda] mkl_random                1.0.2                    py36_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
[conda] pytorch                   1.0.0           py3.6_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] torchfile                 0.1.0                      py_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by fmassa** [comment]
I don't think the problem is with `ModuleList` per se, but with the fact that you are using `DataParallel`. In fact, `DataParallel` synchronizes all the parameters of the model between all GPUs before forward.
Thus, for larger number of parameters (as is the in your `model200` case), the synchronization will take longer.

**Comment by senthilps8** [comment]
That makes sense, thanks.

**Comment by XiaoTailong** [comment]
I have the same problem. I delete the DPP, and the speed is also slow.
