### ISSUE TITLE
Change of directory structure breaks Caffe2 installation.

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#15816]
## Bug

PR #14553 changes `include` to `lib/include`.
This is not in-sync with caffe2's target properties, e.g.
https://github.com/pytorch/pytorch/blob/71ee882157ea06b0e8facb510c44b5a3a55e5d91/caffe2/CMakeLists.txt#L231

As a result, when installing Caffe2, almost all headers go to `/usr/local/lib/include` instead of `/usr/local/include`, and `find_package(Caffe2)` failed since it's still looking for `<prefix>/include`.

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): CentOS 7
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake + ninja
 - Python version: 3.6

**Comment by soumith** [comment]
reverted offending PR at https://github.com/pytorch/pytorch/pull/15847
