### ISSUE TITLE
[QUESTION] Should _dummy_type use name instead of storage_name?

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#15817]
Should [_dummy_type](https://github.com/pytorch/pytorch/blob/55baca57d2af8b1f7268befd379aabeed165ff20/torch/cuda/__init__.py#L476) in `torch/cuda/__init__.py` use `name` instead of `storage_name` as the type name? I tried to make that change, but it leads to a 50% reproducible test failure in `test_dag_net_forking` on `py2-devtoolset7-rocmrpm-centos7.5` [[failed example](https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/5439/)][[passed example](https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/5460/)]. Error message is shown below:

```
21:05:50 ../../../../usr/local/caffe2/lib/python2.7/site-packages/caffe2/python/hypothesis_test.py::TestOperators::test_dag_net_forking ./.jenkins/caffe2/test.sh: line 96:  4908 Aborted                 (core dumped) "$PYTHON" -m pytest -x -v --disable-warnings --junit-xml="$pytest_reports_dir/result.xml" --ignore "$CAFFE2_PYPATH/python/test/executor_test.py" --ignore "$CAFFE2_PYPATH/python/operator_test/matmul_op_test.py" --ignore "$CAFFE2_PYPATH/python/operator_test/pack_ops_test.py" --ignore "$CAFFE2_PYPATH/python/mkl/mkl_sbn_speed_test.py" ${rocm_ignore_test[@]} "$CAFFE2_PYPATH/python" "${EXTRA_TESTS[@]}"
```

**Comment by ezyang** [comment]
Are you sure the 50% failure rate has anything to do with your change? That's a Caffe2 test and it shouldn't be exercising `torch/cuda/__init__.py` at all

**Comment by mrshenli** [comment]
@ezyang I am not sure. What I saw is that after that change, it failed twice in 4 runs. Reverting that change leads to two consecutive test success (yes, very limited sample). It's only my suspicion, but I can run that test some more times to gather more info.

**Comment by mrshenli** [comment]
I think I actually have never seen that failure when working on other PRs (i.e., using `storage_name`). So, it looks a little weird.

**Comment by zou3519** [comment]
That test `py2-devtoolset7-rocmrpm-centos7.5` has been really weird for me lately, but I haven't seen it fail with the exact same error

**Comment by mrshenli** [comment]
I hit this error [again](https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/8146/console), but this time I did not touch `_dummy_type`.

**Comment by ezyang** [comment]
I also am confirming that this test is independently flaky. You should make your originally suggested change.
