### ISSUE TITLE
[JIT] Support Meta programming on If self.training to conditionally NOT compile training only code

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#15815]
Follow up on pull request #14533

## 🚀 Feature
Support metaprogramming for `if self.training`. Cos many many models have different training code vs inference code.

## Example

 ```
class MyJITModule(torch.jit.ScriptModule):
     def __init__(self):
         super(MyJITModule, self).__init__()
         self.lnorm = nn.LayerNorm([10, 10, 10])

     @torch.jit.script_method
     def forward(self, x):
         if self.training:
             self.training_code_only(x)
         return x

     def training_code_only(self, x):
         # do some torchscript incompatible logic
         arr = [1,2,3]
         for i, k in enumerate(arr):
             x[k] += x[k]

         return self.lnorm(x)


 print MyJITModule().graph
 MyJITModule().save("./conditional.pt")

graph(%x : Tensor
      %1 : Tensor) {
  %2 : bool = prim::Bool(%1)
   = prim::If(%2)
    block0() {
      %3 : () = ^training_code_only()(%x)
      -> ()
    }
    block1() {
      -> ()
    }
  return (%x);
}

RuntimeError:
could not export python function call training_code_only. Remove calls to python functions before export.:
@torch.jit.script_method
def forward(self, x):
    if self.training:
        self.training_code_only(x)
        ~~~~~~~~~~~~~ <--- HERE
    return x

```

## Pitch

If we support metaprogramming, the most obvious use case of metaprogramming is the separate training code from inference code. Hence, we should be able to support this.

## Alternatives

Or maybe you can suggest a workaround?

**Comment by wanchaol** [comment]
Hi @sidazhang, thanks for reporting this. Actually `self.training` is already supported in JIT, training and inference subgraph should be both exists in the generated IR, and will depend on the actual value of self.training to execute the corresponding if branch. So we don't need to meta program it. 

The problem or workaround on your example is that, you should also annotate the function `training_code_only` with `@torch.jit.script_method`, because although we can run it without making it a script_method, we cannot serialize a python function call if you want to save the graph.

**Comment by sidazhang** [comment]
@wanchaol 

Hi, 

Thank you for your response. The problem is that training_code_only is has very complex logic. I just still don't want to spend the time to convert it to be torchscript compatible.

It might:

1. Use certain python list functions like list.reverse()
2. Use Python libraries like opencv, matplotlib or tensorboard
3. Do things like `zip`

The point being, it is just my training code, I should have the freedom to do whatever I want without the overhead of comply with torchscript.

So to illustrate my point further, one potential solution that would work for me is, for pytorch to provide some sort of ability to indicate that something should never be compiled like

### Example 1

```
@torch.jit.do_not_jit
def trainining_code_only(self, x):
    ....

@torch.jit.script_method
def forward(self, x):
    if self.training:
       # I can guarantee that during inference, we will never hit this branch
       # and if we do, you can panic, cos that is clearly a bug
       return self.trainining_code_only(x)
```


### Example 2

```
@torch.jit.script_method
def forward(self, x):
   with torch.jit.do_not_jit:  
       # like torch.no_grad
       # Just optinally do not run this branch during script mode
       if self.training:
          return self.trainining_code_only(x)

```

**Comment by driazati** [comment]
At this point we don't want to expand the capabilities of metaprogramming since it could lead to some confusing behavior down the line, so inline non-TorchScript isn't supported. We recommend calling out to a non-jit Python function to do any unsupported training behavior.

I'll look into adding an explicit flag/pass to remove Python functions with no outputs to support your example.

**Comment by sidazhang** [comment]
Oh got it. This looks pretty good.

```class PythonValuesJIT3(torch.jit.ScriptModule):
    __constants__ = ['training_now']
    def __init__(self):
        super(PythonValuesJIT3, self).__init__()
        self.training_now = True
        self.lnorm = nn.LayerNorm([10, 10, 10])

    @torch.jit.script_method
    def forward(self, x, y):
        # type: (torch.Tensor, Tuple[torch.Tensor, torch.Tensor]) -> Tuple[torch.Tensor, torch.Tensor]

        if not self.training_now:
            # I expect this function to be treated as python value
            # and therefore just don't care about it
            return self.training_only_code(x, y)

        return y

    def training_only_code(self, x, y):
        # type: (torch.Tensor, Tuple[torch.Tensor, torch.Tensor]) -> Tuple[torch.Tensor, torch.Tensor]
        return y

m = PythonValuesJIT3()
print "Normal Graph with python ops"
print m.graph

print "Pass constant propagation"
torch._C._jit_pass_constant_propagation(m.graph)
print m.graph

m.save("./condition.pt")```



```Normal Graph with python ops
graph(%x : Tensor
      %y : (Tensor, Tensor)) {
  %2 : bool = prim::Constant[value=1]()
  %3 : bool = aten::__not__(%2)
  %5 : (Tensor, Tensor) = prim::If(%3)
    block0() {
      %4 : (Tensor, Tensor) = ^training_only_code()(%x, %y)
      -> (%4)
    }
    block1() {
      -> (%y)
    }
  return (%5);
}

Pass constant propagation
graph(%x : Tensor
      %y : (Tensor, Tensor)) {
  return (%y);
}```

**Comment by sidazhang** [comment]
This is very useful. Maybe have it as a flag?

`m.graph(pass_constant_propagation=True)`
or
`m.save("module.pt", pass_constant_propagation=True)`

**Comment by sidazhang** [comment]
This pull request basically resolves this feature request
https://github.com/pytorch/pytorch/pull/16055
