### ISSUE TITLE
Error applying np.any() to a pytorch Tensor: *** TypeError: any() missing 1 required positional arguments: "dim"

### ISSUE THREAD

**Issue by ThomasMiconi** [pytorch/pytorch#15810]
## 🐛 Bug

Cannot apply np.any() to a pytorch Tensor in 1.0.0 with numpy 1.15.4: *** TypeError: any() missing 1 required positional arguments: "dim"

## To Reproduce

Steps to reproduce the behavior (seems to require numpy 1.15, error disappears under numpy 1.14.0 !):

1- a = torch.randn(1, 3).byte() % 2
2- np.any(a) 
```

In [20]: a = torch.randn(1, 3).byte() % 2
In [21]: a.any()  # Works fine
Out[21]: tensor(1, dtype=torch.uint8)
In [22]: np.any(a)  # Fails
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-2d4269856f32> in <module>()
----> 1 np.any(a)

/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py in any(a, axis, out, keepdims)
   2011 
   2012     """
-> 2013     return _wrapreduction(a, np.logical_or, 'any', axis, None, out, keepdims=keepdims)
   2014 
   2015 

/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     79                 return reduction(axis=axis, dtype=dtype, out=out, **passkwargs)
     80             else:
---> 81                 return reduction(axis=axis, out=out, **passkwargs)
     82 
     83     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

TypeError: any() missing 1 required positional arguments: "dim"

```

## Expected behavior

np.any(a) should work without hiccups and without specifying dimensions, just like np.isnan(a) does ?

## Environment

Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.3
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip3] numpy (1.15.4)
[pip3] torch (1.0.0)
[pip3] torchtext (0.2.3)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by soumith** [comment]
aren't you asking for a feature in numpy?

**Comment by fmassa** [comment]
I believe this is a problem with numpy, as @soumith mentioned.

Indeed, the error originates from [this part of the code](https://github.com/numpy/numpy/blob/b94e65906c6790527aa4fc6eb107140c39035800/numpy/core/fromnumeric.py#L75), where our tensors indeed do have a `any` attribute, which then gets dispatched to [`reduction` but assuming that this follows numpy API](https://github.com/numpy/numpy/blob/b94e65906c6790527aa4fc6eb107140c39035800/numpy/core/fromnumeric.py#L84)

For me, the right fix would live in numpy, by leveraging the `__array__` method.
If we really want to make this work in PyTorch without modifying numpy, it would require modifying the API of `torch.any` to match the API of numpy, namely replacing `dim` by `axis` etc.
But this would be a pretty big breaking change.

**Comment by fmassa** [comment]
Closing as it's related to a problem in numpy, and the best solution would be to fix it there I believe
