### ISSUE TITLE
torch.Tensor should have the `ravel` function

### ISSUE THREAD

**Issue by acgtyrant** [pytorch/pytorch#1582]
I know `view(-1)` can produce the same result. However `ravel` is a better name!

If developer agree with this proposal, I can make a relative request pull.

**Comment by soumith** [comment]
`ravel` is not like `view(-1)` as it might make copies if needed (non-contiguous case). Should we really have a `ravel` function? I'm not sure.

**Comment by acgtyrant** [comment]
You are right, `ravel` is not like `view(-1)`.

**Comment by vishwakftw** [comment]
Isn't this closed via https://github.com/pytorch/pytorch/pull/8578 ?
