### ISSUE TITLE
Windows10 with cuda9.2 build Error 

### ISSUE THREAD

**Issue by micro-step** [pytorch/pytorch#15828]
## To Reproduce

1.build_windows.bat  use vs2017
2.the generated project reference Error cuda library 
like :
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib64\libcufft_static.a
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib64\libcurand_static.a
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib64\libculibos.a

**Comment by peterjc123** [comment]
Are you using gcc since the suffix of the libs are `.a`? Please use VS 2017 instead.

**Comment by rgommers** [comment]
> Are you using gcc since the suffix of the libs are `.a`?

I think this is a valid bug report. Every mention of `libculibos` in the CMake files explicitly hardcodes `.a`. It probably should be using `CMAKE_SHARED_LIBRARY_SUFFIX` instead. Related to gh-15476, should be taken along when fixing that.

**Comment by peterjc123** [comment]
Yes, I see. Since it's the same problem as #15476, let's close this one.

**Comment by rgommers** [comment]
Yep, it's a variation of the same thing. Not having a Windows box available so it took a bit of hunting, but the [cusparse docs](https://docs.nvidia.com/cuda/cusparse/index.html#static-library) say:

_Starting with release 6.5, the cuSPARSE Library is also delivered in a static form as `libcusparse_static.a` on Linux and Mac OSes. The static cuSPARSE library and all others static maths libraries depend on a common thread abstraction layer library called `libculibos.a` on Linux and Mac and `culibos.lib` on Windows. _

So the suffix is indeed wrong.
