### ISSUE TITLE
MyPy Type Hinting Stub Files?

### ISSUE THREAD

**Issue by ashermancinelli** [pytorch/pytorch#15839]
### (should this be a feature request?)

Having `.pyi` type annotated stub files ([PEP561](https://www.python.org/dev/peps/pep-0561/)) and type hinted source ([PEP484](https://www.python.org/dev/peps/pep-0484/)) would be beneficial for maintainability, new users, and making contributions easier.

**Comment by ashermancinelli** [comment]
Would the stubs or annotating the current code base be a better first step?

**Comment by t-vi** [comment]
#7318 is a bug report asking for it.

The open PR #12500 implements this, but there might be work to do.
