### ISSUE TITLE
.mean() for large tensors (where subiterators are used) produces wrong results

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#15837]
## To Reproduce

```
import torch
a=torch.ones([838860800], dtype = torch.float, device="cuda")
print(a.mean())
```
produces 0.5 on the gpu and 0.8 on the cpu
## Expected behavior

produce 1

## Environment
current master, compiled from source
cc @jjsjann123 @umanwizard

**Comment by cpuhrsch** [comment]
cc @colesbury

**Comment by umanwizard** [comment]
will take a look at this today

**Comment by umanwizard** [comment]
#16023 should fix this for CUDA. Investigating CPU now.

**Comment by umanwizard** [comment]
OK, I figured out that this fails on CPU because for float32, 1 + ... + 1 can never exceed 16777216.

That issue predates moving `mean` to `TensorIterator`.
