### ISSUE TITLE
torch_nightly pip installs broken

### ISSUE THREAD

**Issue by anurag** [pytorch/pytorch#15846]
## 🐛 Bug

The instructions to install torch_nightly on pytorch.org stopped working around 2 hours ago.

## To Reproduce

```shell
$ pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html

Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting torch_nightly
  Could not find a version that satisfies the requirement torch_nightly (from versions: )
No matching distribution found for torch_nightly
```

## Expected behavior

The install should not error out.

## Environment
OS: Mac OSX 10.14.2
Python version: 3.7
Is CUDA available: No

**Comment by anurag** [comment]
Seems to be fixed now. Closing.

**Comment by makamkkumar** [comment]
I am also facing the same issue its not isntalling on ubuntu 16.04 with a GPU P4000
