### ISSUE TITLE
How to load a model trained on GPU 0 (cuda: 0) to GPU 1 (cuda:1) for inference?

### ISSUE THREAD

**Issue by AlenUbuntu** [pytorch/pytorch#15848]
## ❓ Questions and Help

Hello, Sir or Madam:

I have a machine with 4 GPUs and recently trained a ResNet on GPU 0 (cuda: 0) which is then saved using torch.save. I am wondering if it is possible load this model from disk to GPU 1 (cuda: 1) for inference?

**Comment by dashesy** [comment]
You can use `map_location` to [change device](https://discuss.pytorch.org/t/on-a-cpu-device-how-to-load-checkpoint-saved-on-gpu-device/349). I always read as cpu and then move to the device as needed.

**Comment by migalo22** [comment]
when i try to run my varitionnal auto-encoder i get this error : 

test_and_train.py:None (test_and_train.py)
test_and_train.py:102: in <module>
    model_net = VoxceptionNet(n_classes=40).to(device)
..\..\..\Anaconda3\envs\lib\site-packages\torch\nn\modules\module.py:381: in to
    return self._apply(convert)
..\..\..\Anaconda3\envs\lib\site-packages\torch\nn\modules\module.py:187: in _apply
    module._apply(fn)
..\..\..\Anaconda3\envs\lib\site-packages\torch\nn\modules\module.py:193: in _apply
    param.data = fn(param.data)
..\..\..\Anaconda3\envs\lib\site-packages\torch\nn\modules\module.py:379: in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
E   RuntimeError: CUDA error: invalid device ordinal

**Comment by ezyang** [comment]
In all likelihood your `device` value is nonsense. Print it out and see what the problem is.
