### ISSUE TITLE
Operation is not cleaned up when exception raised in file THTensorRandom.c

### ISSUE THREAD

**Issue by xmfbit** [pytorch/pytorch#1584]
I was reading the documentation of `torch.multinomial()` method in the [online documentation](http://pytorch.org/docs/torch.html?highlight=multinomial#torch.multinomial).

I tried this in IPython environment.

```
weights = torch.Tensor([0, 10, 3, 0])
print weights   # out: [torch.FloatTensor of size 4]
torch.multinomial(weights, 5)
```

Of course, error occurs because 5 is larger than the size of weights and I didn't set `replacement=True`. The error message is like this:
```
RuntimeError: cannot sample n_sample > prob_dist:size(1) samples without replacement at /home/me/pytorch/pytorch/torch/lib/TH/generic/THTensorRandom.c:94
```
But after this, the dimensions of weights changed.
```
print weights  # out: [torch.FloatTensor of size 1x4]
```

If I run as following without runtime exception, then the dimensions of weights do not change.
```
weights = torch.Tensor([0, 10, 3, 0]) 
print weights # out: [torch.FloatTensor of size 4]
torch.multinomial(weights, 4)
print weights # out: [torch.FloatTensor of size 4]
```

This is caused by not cleaning up after exception raised in this [operation](https://github.com/pytorch/pytorch/blob/156fe2866665c55557e41bb46603fef3e39bfb35/torch/lib/TH/generic/THTensorRandom.c#L81-L84).

Maybe the solution is adding cleaning up code in the [code block](https://github.com/pytorch/pytorch/blob/156fe2866665c55557e41bb46603fef3e39bfb35/torch/lib/TH/generic/THTensorRandom.c#L91-L95).

**Comment by MicaelCarvalho** [comment]
The problem emerged in two other situations as well, here are the examples:

```
import torch
weights = torch.Tensor([0, 10, 3, 0])
print(weights)
torch.multinomial(weights, 5)
print(weights)

weights = torch.Tensor([0, 10, 3, 0])
print(weights)
torch.multinomial(weights, 0)
print(weights)

weights = torch.Tensor([0, 0, 0, 0])
print(weights)
torch.multinomial(weights, 2)
print(weights)
```

I'm sending a pull request with the fix. Thanks for reporting the problem. :)
