### ISSUE TITLE
Feature request : Profiler 

### ISSUE THREAD

**Issue by Coderx7** [pytorch/pytorch#15857]
## 🚀 Feature
It is often helpful to understand what operations take how much time while running a model. This helps optimize the model to run faster or spot bugs in the model itself or the framework the model is being run on.  

## Motivation

MXNet has a profiler feature which is very handy and easy to use. Just yesterday such feature, helped me identify a bug in MXNet and ultimately helped save an immense amount of time used for debugging and what not. The way it is implemented allows to be used in all and every single models, without even altering  a thing in the aforementioned models. using an environment variable, one can easily profile his/her model and see what needs to be done. If any granularity level is needed, he/she can easily specify that and get the exact information he/she needs.

## Pitch

Implementing the same or similar functionality as explained in : https://mxnet.incubator.apache.org/tutorials/python/profiler.html with the same level of ease and granularity

**Comment by jekbradbury** [comment]
MXnet’s profiler is almost certainly based on (or at least inspired by) the PyTorch profiler https://pytorch.org/docs/stable/autograd.html#torch.autograd.profiler.profile

**Comment by soumith** [comment]
closing via James' comment above. We do have a profiler for quite some time now :)
