### ISSUE TITLE
Improving docs for MultiLabelSoftMarginLoss

### ISSUE THREAD

**Issue by DNGros** [pytorch/pytorch#15863]
## 📚 Documentation

There seems to be a lot of confusion around Mutilabel losses. 
- https://discuss.pytorch.org/t/multi-label-classification-in-pytorch/905
- https://discuss.pytorch.org/t/help-about-multi-classification/14418 
- https://discuss.pytorch.org/t/why-multilabelmarginloss-take-torch-long-has-arguments/28970
- https://discuss.pytorch.org/t/multilabelmarginloss-input-formation/9155/2

One area in particular is it looks like there needs to be more clarity on what the target format of MultiLabelMarginLoss and MultiLabelSoftMarginLoss. One top-search-result example https://gist.github.com/bartolsthoorn/36c813a4becec1b260392f5353c8b7cc has over 1500 link follows on the forums but actually implements it incorrectly (uses a onehot instead of class indices with negative number padding).

It might be useful to explicitly point out in https://github.com/pytorch/pytorch/blob/cb3241866917024a59955a5099a8eab461357d9c/torch/nn/modules/loss.py#L941 that it is not a onehot target, and perhaps provide an example in the docs.

**Comment by JamesTrick** [comment]
I'm happy to take on this issue if no one else wants it?

**Comment by soumith** [comment]
@JamesTrick go for it!
