### ISSUE TITLE
GPU memory usage is very high at the beginning of training.

### ISSUE THREAD

**Issue by samson-wang** [pytorch/pytorch#15872]
## 🐛 Bug

At the beginning of the training, the GPU memory usage is high, i.e. about 9GB. After some iterations, the consumption is stable at 1.4 GB. 

So I can't set a larger batch size.

## To Reproduce
Change crop size to `334` on  https://github.com/pytorch/examples/blob/0.4/imagenet/main.py#L122 can reproduce the problem to some extent, i.e. 7.5GB at beginning and 4.5GB at stable.

My training scripts only has a more complicated dataset process.

## Environment
```
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 384.66
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

**Comment by ezyang** [comment]
This is because you are using cudnn.benchmark, which needs a bit of memory to figure out what the best cudnn algorithm is. Once it has found a good algorithm, it caches it and no longer needs to test for it.

**Comment by samson-wang** [comment]
I see. Thanks!
Disabling the cudnn.benchmark save a lot GPU memory. However, the performance drops a little as well.
So can I set the algorithm manually by cache it to disk?

**Comment by ezyang** [comment]
Unfortunately there is no way of currently doing this. #4392 may be of interest to you.
