### ISSUE TITLE
fail to import pytorch

### ISSUE THREAD

**Issue by igorvere** [pytorch/pytorch#1587]
Got a very cryptic error when loading pytorch built from sources:
python
Python 2.7.8 (default, May 15 2016, 12:46:09)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../penv2/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: ../penv2/lib/python2.7/site-packages/torch/_C.so: undefined symbol: _ZNSt12bad_weak_ptrD1Ev

**Comment by soumith** [comment]
your libstdc++ that you built and linked with is not the same being loaded. I dont know why that's the case in your environment.

**Comment by igorvere** [comment]
Indeed we have some over complicated environment setup, setting up anaconda and recompiling pytorch helped. Thanks

**Comment by pkuCactus** [comment]
Hi @igorvere , have you solved it. I encountered same problem but i am python3.6 and the latest pytorch 0.4.0 and the libstdc++ is same. Could you give me some advice. Thanks a lot.

**Comment by igorvere** [comment]
Hi @pkuCactus. In my case I had pytorch compiled against different libstdc++ to what python was loading because we have some custom gcc set up. We resolved it by setting up anaconda (initially I tried it on bare python) and compiled pytorch against anaconda's gcc and Intel MKL.
