### ISSUE TITLE
Errors occur when run 'build.py'

### ISSUE THREAD

**Issue by Dee-Ma** [pytorch/pytorch#15877]
## 🐛 Bug

Hi,

I am just running 'build.py' through the website https://github.com/lxx1991/pytorch-voxel-flow/blob/master/README.md. However, I got those errors:
![capture5](https://user-images.githubusercontent.com/37693236/50911841-99050080-1428-11e9-9c18-e540cd2a3bf4.PNG)
 
Could you help me with this? Thank you in advance!
## To Reproduce
To reproduce this code, just need to run 'build.sh' as introduced in website: https://github.com/lxx1991/pytorch-voxel-flow/blob/master/README.md

## Environment

 - PyTorch Version :0.4.1
 - OS :Windows 7
 - How you installed PyTorch :pip
 - Python version: 3.5
 - CUDA/cuDNN version: 9.0.167/7.0.5
 - GPU models and configuration: Quadro P6000 (391.35)

**Comment by peterjc123** [comment]
https://pytorch.org/docs/stable/notes/windows.html#cffi-extension

**Comment by smilefenglei** [comment]
Actually, I don't solve it. I reproduce the result of the paper by the code of tensorflow shared by the author  https://github.com/liuziwei7/voxel-flow. I think it easier to understand. 

This is the reply from Dr. Xiaoxiao Li (lxx1991@gmail.com):

"nvcc" is the standard Nvidia cuda compiler.
Have you installed the cuda correctly? And is there any error message after executing that command?

I hope it can help you.

**Comment by Dee-Ma** [comment]
> yes,that's enough.

@peterjc123 
Hi,

Many thanks for your reply.

**Comment by Dee-Ma** [comment]
> Actually, I don't solve it. I reproduce the result of the paper by the code of tensorflow shared by the author https://github.com/liuziwei7/voxel-flow. I think it easier to understand.
> 
> This is the reply from Dr. Xiaoxiao Li ([lxx1991@gmail.com](mailto:lxx1991@gmail.com)):
> 
> "nvcc" is the standard Nvidia cuda compiler.
> Have you installed the cuda correctly? And is there any error message after executing that command?
> 
> I hope it can help you.

@smilefenglei 

Hi Feng Lei,

Many thanks for your help. I just noticed that the TensorFlow version for DVF is different from the method introduced in their paper (didn't include skip connections, multi-scale, etc.), so we have to try using pytorch version instead... 

Yes, we have successfully installed the CUDA (9.0.167) and there are also other error after executing command 'build.sh', for example: fatal error c1021: invalid preprocessor command 'THCState'

Do you also try to reproduce DVF method? Could you perhaps give your email address? We could discuss it further and share our experiences in running this code.

Thanks.

Di

**Comment by peterjc123** [comment]
@Dee-Ma Please close this issue. I've answered your question in another related issue #15919.
