### ISSUE TITLE
Two errors occur when run 'build.py'

### ISSUE THREAD

**Issue by Dee-Ma** [pytorch/pytorch#15894]
## 🐛 Bug

Hi,

I am just running 'build.py' through the website https://github.com/lxx1991/pytorch-voxel-flow/blob/master/README.md. However, I got those errors:

![capture5](https://user-images.githubusercontent.com/37693236/50934315-2e6fb700-1460-11e9-858d-4eff7bd87ffc.PNG)

One is: 'fatal error c1021: invalid preprocessor command 'THCState'.

Another one is: 'distutils.errors.DistutilsExecError: command failed with exit status 2'

Could you please help me with this? Thanks in advance!
## To Reproduce

1. run the 'build.sh'

Code Sample:

#include <THC/THC.h>
#include "cuda/sync_bn_kernel.h"
#include <THC/THCGeneral.h>
#THCState *state=at::globalContext().thc_state;
extern THCState *state;
extern "C" int my_lib_add_forward_cuda(THCudaTensor *input1, THCudaTensor *input2,
                                        THCudaTensor *output)
{
    if (!THCudaTensor_isSameSizeAs(state, input1, input2))
    return 0;
    THCudaTensor_resizeAs(state, output, input1);
    THCudaTensor_cadd(state, output, input1, 1.0, input2);
    return 1;
}

extern "C" int my_lib_add_backward_cuda(THCudaTensor *grad_output, THCudaTensor *grad_input)
{
    THCudaTensor_resizeAs(state, grad_input, grad_output);
    THCudaTensor_fill(state, grad_input, 1);
    return 1;
}

void get_sizes(const THCudaTensor *t, int *N, int *C, int *S)
{
  // Get sizes
  *S = 1;
  *N = THCudaTensor_size(state, t, 0);
  *C = THCudaTensor_size(state, t, 1);
  if (THCudaTensor_nDimension(state, t) > 2)
  {
    for (int i = 2; i < THCudaTensor_nDimension(state, t); ++i)
    {
      *S *= THCudaTensor_size(state, t, i);
    }
  }
}

int bn_forward_mean_before_allreduce(const THCudaTensor *bottom, THCudaTensor *mean, const int allreduce_num)
{
  cudaStream_t stream = THCState_getCurrentStream(state);
  int HW, N, C;
  get_sizes(bottom, &N, &C, &HW);

  // Get pointers
  const float *_bottom = THCudaTensor_data(state, bottom);
  float *_mean = THCudaTensor_data(state, mean);

  return bn_forward_mean_before_allreduce_cuda(N, HW, C, allreduce_num, _bottom, _mean, stream);
}

int bn_forward_var_before_allreduce(const THCudaTensor *bottom, const THCudaTensor *mean, THCudaTensor *var, THCudaTensor *top, const int allreduce_num)
{
  cudaStream_t stream = THCState_getCurrentStream(state);
  int HW, N, C;
  get_sizes(bottom, &N, &C, &HW);

  // Get pointers
  const float *_bottom = THCudaTensor_data(state, bottom);
  const float *_mean = THCudaTensor_data(state, mean);
  float *_var = THCudaTensor_data(state, var);
  float *_top = THCudaTensor_data(state, top);

  return bn_forward_var_before_allreduce_cuda(N, HW, C, allreduce_num, _bottom, _mean, _var, _top, stream);
}

int bn_forward_after_allreduce(const THCudaTensor *mean, THCudaTensor *history_mean, const THCudaTensor *var, THCudaTensor *history_var,
                               THCudaTensor *x_norm, THCudaTensor *x_std, const THCudaTensor *scale, const THCudaTensor *shift, THCudaTensor *top,
                               const float var_eps, const float decay)
{
  cudaStream_t stream = THCState_getCurrentStream(state);
  int HW, N, C;
  get_sizes(top, &N, &C, &HW);

  // Get pointers
  const float *_mean = THCudaTensor_data(state, mean);
  float *_history_mean = THCudaTensor_data(state, history_mean);
  const float *_var = THCudaTensor_data(state, var);
  float *_history_var = THCudaTensor_data(state, history_var);
  float *_x_norm = THCudaTensor_data(state, x_norm);
  float *_x_std = THCudaTensor_data(state, x_std);
  const float *_scale = THCudaTensor_data(state, scale);
  const float *_shift = THCudaTensor_data(state, shift);
  float *_top = THCudaTensor_data(state, top);

  return bn_forward_after_allreduce_cuda(N, HW, C, var_eps, decay, _top, _mean, _history_mean, _var, _history_var, _x_norm, _x_std, _scale, _shift, stream);
}

//backward

int bn_backward_before_allreduce(const THCudaTensor *top_diff, const THCudaTensor *x_norm, const THCudaTensor *mean,
                                 const THCudaTensor *x_std, THCudaTensor *bottom_diff, THCudaTensor *local_scale_diff, THCudaTensor *local_shift_diff,
                                 THCudaTensor *scale_diff, THCudaTensor *shift_diff)
{
  cudaStream_t stream = THCState_getCurrentStream(state);
  int HW, N, C;
  get_sizes(top_diff, &N, &C, &HW);

  // Get pointers
  const float *_top_diff = THCudaTensor_data(state, top_diff);
  const float *_x_norm = THCudaTensor_data(state, x_norm);
  const float *_mean = THCudaTensor_data(state, mean);
  const float *_x_std = THCudaTensor_data(state, x_std);
  float *_bottom_diff = THCudaTensor_data(state, bottom_diff);
  float *_local_scale_diff = THCudaTensor_data(state, local_scale_diff);
  float *_local_shift_diff = THCudaTensor_data(state, local_shift_diff);
  float *_scale_diff = THCudaTensor_data(state, scale_diff);
  float *_shift_diff = THCudaTensor_data(state, shift_diff);

  return bn_backward_before_allreduce_cuda(N, HW, C, _top_diff, _x_norm, _mean, _x_std, _bottom_diff, _local_scale_diff, _local_shift_diff, _scale_diff, _shift_diff, stream);
}

int bn_backward_after_allreduce(const THCudaTensor *top_diff, const THCudaTensor *x_norm,
                                const THCudaTensor *local_scale_diff, const THCudaTensor *local_shift_diff,
                                const THCudaTensor *scale_data, const THCudaTensor *x_std, THCudaTensor *bottom_diff,
                                const int allreduce_num)
{
  cudaStream_t stream = THCState_getCurrentStream(state);
  int HW, N, C;
  get_sizes(top_diff, &N, &C, &HW);

  // Get pointers
  const float *_top_diff = THCudaTensor_data(state, top_diff);
  const float *_x_norm = THCudaTensor_data(state, x_norm);
  const float *_local_scale_diff = THCudaTensor_data(state, local_scale_diff);
  const float *_local_shift_diff = THCudaTensor_data(state, local_shift_diff);
  const float *_scale_data = THCudaTensor_data(state, scale_data);
  const float *_x_std = THCudaTensor_data(state, x_std);
  float *_bottom_diff = THCudaTensor_data(state, bottom_diff);

  return bn_backward_after_allreduce_cuda(N, HW, C, _top_diff, _x_norm, _local_scale_diff, _local_shift_diff, _scale_data, _x_std, _bottom_diff, allreduce_num, stream);
}
## Environment

PyTorch Version :0.4.1
OS :Windows 7
How you installed PyTorch :pip
Python version: 3.5
CUDA/cuDNN version: 9.0.167/7.0.5
GPU models and configuration: Quadro P6000 (391.35)

**Comment by peterjc123** [comment]
You are missing the line in the doc: Changing the source file from c to c++. And why do you open two issues at the same time on only one problem?

**Comment by Dee-Ma** [comment]
> You are missing the line in the doc: Changing the source file from c to c++. And why do you open two issues at the same time on only one problem?

@peterjc123 

Hi,

Many thanks for your reply. Sorry for confusion, I just met other two different errors after posting this issue-so I re-open a new issue.

**Comment by Dee-Ma** [comment]
> You are missing the line in the doc: Changing the source file from c to c++. And why do you open two issues at the same time on only one problem?

@peterjc123 

Hi perterjc123,

I followed the website that you given: https://pytorch.org/docs/stable/notes/windows.html#cffi-extension

For "First, specify additional libraries in Extension object to make it build on Windows.", may I ask if I just copy this code to my source file? I am not sure how to realise this step.

In addition, I followed the second step to change the source file from c to c++ (copy their code and use 'extern C' to define some function like THCudaTensor_isSameSizeAs) , however, another error occurs:

"error c2059: syntax error: 'string' (indicate a syntax error on extern "C")

Do you have any idea about this?

Many thanks!

**Comment by peterjc123** [comment]
> For "First, specify additional libraries in Extension object to make it build on Windows.", may I ask if I just copy this code to my source file? I am not sure how to realise this step.
No, you should append the libraries in `build.py`.

> In addition, I followed the second step to change the source file from c to c++ (copy their code and use 'extern C' to define some function like THCudaTensor_isSameSizeAs) , however, another error occurs:
"error c2059: syntax error: 'string' (indicate a syntax error on extern "C")
Could you show me the final code after the edit?

**Comment by peterjc123** [comment]
@Dee-Ma I've compiled the extension for you. Please unzip the file and put the directory `_ext` under `core\ops\sync_bn`.
[_ext.zip](https://github.com/pytorch/pytorch/files/2746159/_ext.zip)

**Comment by peterjc123** [comment]
And here are the modified files if you want to compile it by yourself.

```python
####################
## build.py
####################
import os.path as osp

import torch
from torch.utils.ffi import create_extension

sources = []
headers = []
defines = []
with_cuda = False

if torch.cuda.is_available():
    print('Including CUDA code.')
    sources += ['src/sync_bn.cpp']
    headers += ['src/sync_bn.h']
    defines += [('WITH_CUDA', None)]
    with_cuda = True

assert with_cuda

current_dir = osp.dirname(osp.realpath(__file__))
extra_objects = ['src/cuda/sync_bn_kernel.o']
extra_objects = [osp.join(current_dir, fname) for fname in extra_objects]

ffi = create_extension(
    '_ext.sync_bn_lib',
    headers=headers,
    sources=sources,
    define_macros=defines,
    relative_to=__file__,
    with_cuda=with_cuda,
    extra_objects=extra_objects,
    extra_compile_args=['/MT'],
    libraries=['caffe2_gpu', 'cudart', '_C', 'caffe2'] )

if __name__ == '__main__':
    ffi.build()
```

```cpp
//////////////////////////
// sync_bc.cpp
/////////////////////////

#include <THC/THC.h>
#include <ATen/ATen.h>
#include "cuda/sync_bn_kernel.h"

// extern THCState *state;
THCState *state = at::globalContext().getTHCState();

extern "C" void get_sizes(const THCudaTensor *t, int *N, int *C, int *S)
{
  // Get sizes
  *S = 1;
  *N = THCudaTensor_size(state, t, 0);
  *C = THCudaTensor_size(state, t, 1);
  if (THCudaTensor_nDimension(state, t) > 2)
  {
    for (int i = 2; i < THCudaTensor_nDimension(state, t); ++i)
    {
      *S *= THCudaTensor_size(state, t, i);
    }
  }
}

extern "C" int bn_forward_mean_before_allreduce(const THCudaTensor *bottom, THCudaTensor *mean, const int allreduce_num)
{
  cudaStream_t stream = THCState_getCurrentStream(state);
  int HW, N, C;
  get_sizes(bottom, &N, &C, &HW);

  // Get pointers
  const float *_bottom = THCudaTensor_data(state, bottom);
  float *_mean = THCudaTensor_data(state, mean);

  return bn_forward_mean_before_allreduce_cuda(N, HW, C, allreduce_num, _bottom, _mean, stream);
}

extern "C" int bn_forward_var_before_allreduce(const THCudaTensor *bottom, const THCudaTensor *mean, THCudaTensor *var, THCudaTensor *top, const int allreduce_num)
{
  cudaStream_t stream = THCState_getCurrentStream(state);
  int HW, N, C;
  get_sizes(bottom, &N, &C, &HW);

  // Get pointers
  const float *_bottom = THCudaTensor_data(state, bottom);
  const float *_mean = THCudaTensor_data(state, mean);
  float *_var = THCudaTensor_data(state, var);
  float *_top = THCudaTensor_data(state, top);

  return bn_forward_var_before_allreduce_cuda(N, HW, C, allreduce_num, _bottom, _mean, _var, _top, stream);
}

extern "C" int bn_forward_after_allreduce(const THCudaTensor *mean, THCudaTensor *history_mean, const THCudaTensor *var, THCudaTensor *history_var,
                               THCudaTensor *x_norm, THCudaTensor *x_std, const THCudaTensor *scale, const THCudaTensor *shift, THCudaTensor *top,
                               const float var_eps, const float decay)
{
  cudaStream_t stream = THCState_getCurrentStream(state);
  int HW, N, C;
  get_sizes(top, &N, &C, &HW);

  // Get pointers
  const float *_mean = THCudaTensor_data(state, mean);
  float *_history_mean = THCudaTensor_data(state, history_mean);
  const float *_var = THCudaTensor_data(state, var);
  float *_history_var = THCudaTensor_data(state, history_var);
  float *_x_norm = THCudaTensor_data(state, x_norm);
  float *_x_std = THCudaTensor_data(state, x_std);
  const float *_scale = THCudaTensor_data(state, scale);
  const float *_shift = THCudaTensor_data(state, shift);
  float *_top = THCudaTensor_data(state, top);

  return bn_forward_after_allreduce_cuda(N, HW, C, var_eps, decay, _top, _mean, _history_mean, _var, _history_var, _x_norm, _x_std, _scale, _shift, stream);
}

//backward

extern "C" int bn_backward_before_allreduce(const THCudaTensor *top_diff, const THCudaTensor *x_norm, const THCudaTensor *mean,
                                 const THCudaTensor *x_std, THCudaTensor *bottom_diff, THCudaTensor *local_scale_diff, THCudaTensor *local_shift_diff,
                                 THCudaTensor *scale_diff, THCudaTensor *shift_diff)
{
  cudaStream_t stream = THCState_getCurrentStream(state);
  int HW, N, C;
  get_sizes(top_diff, &N, &C, &HW);

  // Get pointers
  const float *_top_diff = THCudaTensor_data(state, top_diff);
  const float *_x_norm = THCudaTensor_data(state, x_norm);
  const float *_mean = THCudaTensor_data(state, mean);
  const float *_x_std = THCudaTensor_data(state, x_std);
  float *_bottom_diff = THCudaTensor_data(state, bottom_diff);
  float *_local_scale_diff = THCudaTensor_data(state, local_scale_diff);
  float *_local_shift_diff = THCudaTensor_data(state, local_shift_diff);
  float *_scale_diff = THCudaTensor_data(state, scale_diff);
  float *_shift_diff = THCudaTensor_data(state, shift_diff);

  return bn_backward_before_allreduce_cuda(N, HW, C, _top_diff, _x_norm, _mean, _x_std, _bottom_diff, _local_scale_diff, _local_shift_diff, _scale_diff, _shift_diff, stream);
}

extern "C" int bn_backward_after_allreduce(const THCudaTensor *top_diff, const THCudaTensor *x_norm,
                                const THCudaTensor *local_scale_diff, const THCudaTensor *local_shift_diff,
                                const THCudaTensor *scale_data, const THCudaTensor *x_std, THCudaTensor *bottom_diff,
                                const int allreduce_num)
{
  cudaStream_t stream = THCState_getCurrentStream(state);
  int HW, N, C;
  get_sizes(top_diff, &N, &C, &HW);

  // Get pointers
  const float *_top_diff = THCudaTensor_data(state, top_diff);
  const float *_x_norm = THCudaTensor_data(state, x_norm);
  const float *_local_scale_diff = THCudaTensor_data(state, local_scale_diff);
  const float *_local_shift_diff = THCudaTensor_data(state, local_shift_diff);
  const float *_scale_data = THCudaTensor_data(state, scale_data);
  const float *_x_std = THCudaTensor_data(state, x_std);
  float *_bottom_diff = THCudaTensor_data(state, bottom_diff);

  return bn_backward_after_allreduce_cuda(N, HW, C, _top_diff, _x_norm, _local_scale_diff, _local_shift_diff, _scale_data, _x_std, _bottom_diff, allreduce_num, stream);
}
```

**Comment by peterjc123** [comment]
@Dee-Ma Does it solve your problem? If yes, please close this issue.

**Comment by Dee-Ma** [comment]
> @Dee-Ma Does it solve your problem? If yes, please close this issue.

@peterjc123  

Hi Peter,

Many thanks for your great help! The problem has been solved. I am a new PhD student (come from Yunnan Province, China) at Bristol, UK. My research interests include image and video processing, deep learning, computer vision.

I have sent an email to your Gmail and 163 email addresses. Would you mind to add a 'friend' in WeChat or QQ with me? We could discuss technique and academic problems in the future.

Thanks.

Dee

**Comment by Dee-Ma** [comment]
> @Dee-Ma Does it solve your problem? If yes, please close this issue.

@peterjc123 

Hi Peter,

I just tried to compile the codes ('sync_bn.cpp' and 'build.py') that you given to me before. However, there are two types of errors:
1. the first error is : Sync_bn.cpp(6): error c2039: 'getTHCState': is not a member of 'at::COntext'
2. the second type of error is: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2'

Could you please help me with this?

In addition, if I use your compiled  '_ext' folder, then I run 'train.py' based on the introduction from the author: https://github.com/lxx1991/pytorch-voxel-flow/blob/master/README.md, it also indicated error:
''File "E:\Di\pytorch-voxel-flow-master\core\ops\sync_bn\_ext\sync_bn_lib\__init__.py", line 3, in <module>
    from ._sync_bn_lib import lib as _lib, ffi as _ffi
ImportError: No module named 'core.ops.sync_bn._ext.sync_bn_lib._sync_bn_lib'

It seems that from previous 'build.sh' function, it should generate two files 'lib' and 'ffi', however, these two files are not generated successfully. 

May I ask if you could run this 'train.py' successfully?

I really appreciate your great help.

Many thanks.

Best regards,

Dee

**Comment by Dee-Ma** [comment]
> > For "First, specify additional libraries in Extension object to make it build on Windows.", may I ask if I just copy this code to my source file? I am not sure how to realise this step.
> 
> No, you should append the libraries in `build.py`.
> 
> > In addition, I followed the second step to change the source file from c to c++ (copy their code and use 'extern C' to define some function like THCudaTensor_isSameSizeAs) , however, another error occurs:
> > "error c2059: syntax error: 'string' (indicate a syntax error on extern "C")
> 
> Could you show me the final code after the edit?

@peterjc123 

Hi Peter,

Thank you so much!!! I am currently studying your code.

**Comment by peterjc123** [comment]
@Dee-Ma 
> the first error is : Sync_bn.cpp(6): error c2039: 'getTHCState': is not a member of 'at::COntext'

It should be `Context`. Is there a typo?

> It seems that from previous 'build.sh' function, it should generate two files 'lib' and 'ffi', however, these two files are not generated successfully.

That is not correct. _sync_bn_lib is a DLL, and `lib` and `ffi` are two functions inside it. 

> from ._sync_bn_lib import lib as _lib, ffi as _ffi
ImportError: No module named 'core.ops.sync_bn._ext.sync_bn_lib._sync_bn_lib'

I tried directly importing (cd into `core/ops/sync_bn/_ext/sync_bn_lib` and then `from ._sync_bn_lib import lib as _lib, ffi as _ffi`) and it works. So I don't think there is any problem with the extension I built. Did you put the directory `_ext` under the right location?

Additional notes:
The extension you provided is a CFFI extension, which is deprecated in the latest PyTorch. If you are a developer of that repo, then you should use the cpp extension instead.

**Comment by fmassa** [comment]
I believe this is a problem with an external library, so it might be better directing questions there.

I'm closing this issue, but let me know if you disagree.

**Comment by Dee-Ma** [comment]
> @Dee-Ma
> 
> > the first error is : Sync_bn.cpp(6): error c2039: 'getTHCState': is not a member of 'at::COntext'
> 
> It should be `Context`. Is there a typo?
> 
> > It seems that from previous 'build.sh' function, it should generate two files 'lib' and 'ffi', however, these two files are not generated successfully.
> 
> That is not correct. _sync_bn_lib is a DLL, and `lib` and `ffi` are two functions inside it.
> 
> > from ._sync_bn_lib import lib as _lib, ffi as _ffi
> > ImportError: No module named 'core.ops.sync_bn._ext.sync_bn_lib._sync_bn_lib'
> 
> I tried directly importing (cd into `core/ops/sync_bn/_ext/sync_bn_lib` and then `from _sync_bn_lib import lib as _lib, ffi as _ffi`) and it works. So I don't think there is any problem with the extension I built. Did you put the directory `_ext` under the right location?
> 
> Additional notes:
> The extension you provided is a CFFI extension, which is deprecated in the latest PyTorch. If you are a developer of that repo, then you should use the cpp extension instead.

@peterjc123 

Hi Peter,

Many thanks for your reply.

> the first error is : Sync_bn.cpp(6): error c2039: 'getTHCState': is not a member of 'at::COntext'

Sorry, this is my typo, the previous error was 'getTHCState': is not a member of 'at::Context'. Anyway, I tried to use your compiled '_ext' folder instead. 

I copied the your '_ext' folder to the path: 'E:\Di\pytorch-voxel-flow-master\core\ops\sync_bn'. Then run the 'train.py' code. However, it still got error:

' File "E:\Di\pytorch-voxel-flow-master\core\ops\sync_bn\_ext\sync_bn_lib\__init__.py", line 3, in <module>
    from ._sync_bn_lib import lib as _lib, ffi as _ffi
ImportError: DLL load failed: The specified module could not be found.' 

It seems the '_sync_bn_lib.pyd' file could not be loaded successfully.

I also followed your instructions from:https://gist.github.com/peterjc123/6b804651288e76db7b5fabe5348e1f03, (installed mkl 2019.0, intel-openmp2019.0, numpy1.15.4, VC2017 Redist), however, the error still occurred.

Do you have any ideas about this?

Thanks.

Dee

**Comment by peterjc123** [comment]
@Dee-Ma Please copy the dlls under `[python root]\Lib\site-packages\torch\lib` to that dir.
