### ISSUE TITLE
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-fbgemm --use-nnpack --use-mkldnn --use-qnnpack caffe2'

### ISSUE THREAD

**Issue by CF2220160244** [pytorch/pytorch#15911]
## 🐛 Bug

Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-fbgemm --use-nnpack --use-mkldnn --use-qnnpack caffe2'

## To Reproduce

i install pytorch use: 
python setup.py install
and have this error.

[ 66%] Building CXX object caffe2/CMakeFiles/caffe2.dir/operators/rnn/recurrent_network_op.cc.o
[ 66%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/activation_distribution_observer.cc.o
[ 66%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/batch_matmul_dnnlowp_op.cc.o
[ 66%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/caffe2_dnnlowp_utils.cc.o
/home/chenfei/pytorch/caffe2/quantization/server/activation_distribution_observer.cc: In constructor ‘caffe2::RegisterQuantizationParamsWithHistogramNetObserver::RegisterQuantizationParamsWithHistogramNetObserver(caffe2::NetBase*, const string&, bool, const string&)’:
/home/chenfei/pytorch/caffe2/quantization/server/activation_distribution_observer.cc:500:7: error: use of deleted function ‘std::basic_istringstream<char>& std::basic_istringstream<char>::operator=(const std::basic_istringstream<char>&)’
   ist = istringstream(first_line);
       ^
In file included from /home/chenfei/pytorch/c10/util/Logging.h:8:0,
                 from /home/chenfei/pytorch/caffe2/core/logging.h:2,
                 from /home/chenfei/pytorch/caffe2/core/observer.h:6,
                 from /home/chenfei/pytorch/caffe2/quantization/server/activation_distribution_observer.h:3,
                 from /home/chenfei/pytorch/caffe2/quantization/server/activation_distribution_observer.cc:1:
/usr/include/c++/4.9/sstream:272:11: note: ‘std::basic_istringstream<char>& std::basic_istringstream<char>::operator=(const std::basic_istringstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istringstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/4.9/sstream:272:11: error: use of deleted function ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’
In file included from /usr/include/c++/4.9/sstream:38:0,
                 from /home/chenfei/pytorch/c10/util/Logging.h:8,
                 from /home/chenfei/pytorch/caffe2/core/logging.h:2,
                 from /home/chenfei/pytorch/caffe2/core/observer.h:6,
                 from /home/chenfei/pytorch/caffe2/quantization/server/activation_distribution_observer.h:3,
                 from /home/chenfei/pytorch/caffe2/quantization/server/activation_distribution_observer.cc:1:
/usr/include/c++/4.9/istream:58:11: note: ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Preprocessed source stored into /tmp/cco989cm.out file, please attach this to your bugreport.
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/_usr_lib_gcc_x86_64-linux-gnu_4.9_cc1plus.1000.crash'
caffe2/CMakeFiles/caffe2.dir/build.make:7870: recipe for target 'caffe2/CMakeFiles/caffe2.dir/quantization/server/conv_dnnlowp_acc16_op.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2.dir/quantization/server/conv_dnnlowp_acc16_op.cc.o] Error 1
CMakeFiles/Makefile2:5568: recipe for target 'caffe2/CMakeFiles/caffe2.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-fbgemm --use-nnpack --use-mkldnn --use-qnnpack caffe2'

## Environment

 - PyTorch Version (e.g., 1.0):  1.0
 - OS (e.g., Linux):      ubuntu16.04
 - How you installed PyTorch (`conda`, `pip`, source):  source
 - Build command you used (if compiling from source):
 - Python version:   3.6
 - CUDA/cuDNN version: 9.0, 7.0
 - GPU models and configuration: use CUDA
 - Any other relevant information: gcc4.9

**Comment by yinghai** [comment]
@CF2220160244, could you change this line 
https://github.com/pytorch/pytorch/blob/master/caffe2/quantization/server/activation_distribution_observer.cc#L500
to 
```
ist.str(first_line);
```
And see if it works for you?

**Comment by CF2220160244** [comment]
thanks @yinghai , but i  change this line, it has the same error.

**Comment by ashermancinelli** [comment]
@yinghai I'm having the same issue and this did not work for me

**Comment by jspark1105** [comment]
@CF2220160244  that's strange. Are you sure you're getting the error from the same line 500? Can you check if the error is now generated from line 508. If so, please also try with "ist.str(first_line)" in line 508 as well. Anyway let me create a PR to fix this issue.

**Comment by jspark1105** [comment]
Please see if #15953 fixes it.

**Comment by yinghai** [comment]
> thanks @yinghai , but i change this line, it has the same error.

The error message cannot possibly be the same. Could you paste you new error msg?

**Comment by CF2220160244** [comment]
@yinghai @jspark1105 , after i change the line,  the error msg is:
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/conv_relu_op.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/dequantize_dnnlowp_op.cc.o
/home/chenfei/pytorch/caffe2/quantization/server/conv_dnnlowp_acc16_op.cc: In lambda function:
/home/chenfei/pytorch/caffe2/quantization/server/conv_dnnlowp_acc16_op.cc:750:5: internal compiler error: in gimplify_var_or_parm_decl, at gimplify.c:1741
     }; // f2
     ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/dnnlowp.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/dnnlowp_partition.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/elementwise_add_dnnlowp_op.cc.o
/home/chenfei/pytorch/caffe2/quantization/server/conv_dnnlowp_op.cc: In lambda function:
/home/chenfei/pytorch/caffe2/quantization/server/conv_dnnlowp_op.cc:646:5: internal compiler error: in gimplify_var_or_parm_decl, at gimplify.c:1741
     }; // f2
     ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/elementwise_linear_dnnlowp_op.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/elementwise_mul_dnnlowp_op.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/elementwise_sum_dnnlowp_op.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/elementwise_sum_relu_op.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/fbgemm_pack_matrix_cache.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/fbgemm_pack_op.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/fully_connected_dnnlowp_acc16_op.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/fully_connected_dnnlowp_op.cc.o
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/fully_connected_fake_lowp_op.cc.o
Preprocessed source stored into /tmp/ccEoPdW8.out file, please attach this to your bugreport.
[ 65%] Building CXX object caffe2/CMakeFiles/caffe2.dir/quantization/server/fully_connected_rowwise_dnnlowp_op.cc.o
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/_usr_lib_gcc_x86_64-linux-gnu_4.9_cc1plus.1000.crash'
caffe2/CMakeFiles/caffe2.dir/build.make:7870: recipe for target 'caffe2/CMakeFiles/caffe2.dir/quantization/server/conv_dnnlowp_acc16_op.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2.dir/quantization/server/conv_dnnlowp_acc16_op.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Preprocessed source stored into /tmp/ccaQ3vgD.out file, please attach this to your bugreport.
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/_usr_lib_gcc_x86_64-linux-gnu_4.9_cc1plus.1000.crash'
caffe2/CMakeFiles/caffe2.dir/build.make:7883: recipe for target 'caffe2/CMakeFiles/caffe2.dir/quantization/server/conv_dnnlowp_op.cc.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2.dir/quantization/server/conv_dnnlowp_op.cc.o] Error 1
CMakeFiles/Makefile2:5568: recipe for target 'caffe2/CMakeFiles/caffe2.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-fbgemm --use-nnpack --use-mkldnn --use-qnnpack caffe2'

**Comment by jspark1105** [comment]
@CF2220160244  thanks for the information. That's a compiler internal error. Can you try with #15953 ?

**Comment by CF2220160244** [comment]
@jspark1105, I compiled with #15953, but  had the error i mentioned. can you help me?
.

**Comment by jspark1105** [comment]
I was able to reproduce the same error with gcc4.9 and verified #15996 together with #15953 should be able to fix it. We will try to merge them soon. But, I'm seeing other issues when trying to compile gcc4.9 internal compiler errors for c10/test/core/DeviceGuard_test.cpp c10/test/core/impl/InlineDeviceGuard_test.cpp (maybe this is just for me).

**Comment by CF2220160244** [comment]
thanks @jspark1105 ,  #15996 and #15953 fixed this error very well!

**Comment by EchoAmor** [comment]
@CF2220160244 Hello ! I have met this problem too, I am new to segmantation, I have seen #15996 and #15953,and changed 5 files they mentioned,but the problem still exits, can you tell me how you solved this problem,I really need your help! Thank you very much!!!
