### ISSUE TITLE
Where to download pytorch=0.2.0_4

### ISSUE THREAD

**Issue by wanshun123** [pytorch/pytorch#15916]
I specifically need pytorch=0.2.0_4 to test a project built on this version (https://github.com/oawiles/X2Face) but can't find this anywhere on https://pytorch.org/get-started/previous-versions/, nor does `conda install pytorch=0.2.0_4` work. Is there any way I can install this specific version?

**Comment by t-vi** [comment]
I'd recommend to use the latest 0.2 version from the page you link and see if that works.

**Comment by soumith** [comment]
0.2.0_4 or 0.2.0 have the same exact code. _4 is just the build number, you can ignore it.

**Comment by safermi** [comment]
How did you solve this?
