### ISSUE TITLE
Cannot use LBFGS in C++ (clang, torch 1.0.0)

### ISSUE THREAD

**Issue by jbmouret** [pytorch/pytorch#15923]
## 🐛 Bug

I want to use the LBFGS optimizer in C++. My code is working fine in python and with SGD, but I get ``terminating with uncaught exception of type c10::Error: a leaf Variable that requires grad has been used in an in-place operation. (check_inplace at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/libtorch_2.7/pytorch/torch/csrc/autograd/VariableTypeUtils.h:49)`` in C++

### MWE:
```c++
#include <iostream>
#include <torch/torch.h>

int main()
{
    int n_actions = 10;
    auto target = torch::randn({n_actions, 1});

    std::vector<torch::Tensor> q_dot = {torch::randn({n_actions, 1}, torch::requires_grad())};
    //torch::optim::SGD optimizer(q_dot, /*lr=*/0.01);
    torch::optim::LBFGS optimizer(q_dot, 1);

    auto cost = [&](){
        optimizer.zero_grad();
        auto d = torch::pow(q_dot[0] - target, 2).sum();
        d.backward();
        return d;
    };

    for (int i = 0; i < 50; ++i){
        optimizer.step(cost);//for LBFGS
        //cost(); optimizer.step(); // for SGD
    }
    std::cout << cost() << std::endl;
}
```
I compiled with:
```
clang++  -std=c++11 -I libtorch/include/torch/csrc/api/include -I libtorch/include  -Llibtorch/lib   -ltorch -lc10   -lcaffe2    ./test_pytorch.cc
```
Everything compiles fine.

### Result:
```
libc++abi.dylib: terminating with uncaught exception of type c10::Error: a leaf Variable that requires grad has been used in an in-place operation. (check_inplace at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/libtorch_2.7/pytorch/torch/csrc/autograd/VariableTypeUtils.h:49)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 135 (0x110091f37 in libc10.dylib)
frame #1: torch::autograd::check_inplace(at::Tensor const&) + 231 (0x10ed97137 in libtorch.1.dylib)
frame #2: torch::autograd::VariableType::add_(at::Tensor&, at::Tensor const&, c10::Scalar) const + 109 (0x10ef3a7cd in libtorch.1.dylib)
frame #3: torch::optim::LBFGS::add_grad(at::Tensor const&, at::Tensor const&) + 389 (0x10f596b75 in libtorch.1.dylib)
frame #4: torch::optim::LBFGS::step(std::__1::function<at::Tensor ()>) + 6214 (0x10f598566 in libtorch.1.dylib)
frame #5: main + 1198 (0x10ec74c4e in a.out)
frame #6: start + 1 (0x7fff7265ded9 in libdyld.dylib)
```

## Expected behavior

The cost should converge to some small value. It works with SGD and in python:
```python
import time
import torch
import numpy as np
from torch.autograd import Variable


n_actions = 22
dt = 0.01

jac_t = torch.randn(6, n_actions)
state = torch.randn(6, 1)
target = torch.matmul(jac_t, torch.randn(n_actions, 1)) * dt + state

print("target:", target)

t0 = time.perf_counter()
q_dot = Variable(torch.randn(n_actions, 1), requires_grad=True)
v = [q_dot]
optimizer = torch.optim.LBFGS(v)#, lr=0.1)
for i in range(0, 10):
    def cost():
        optimizer.zero_grad()
        next_state = torch.matmul(jac_t, q_dot) * dt + state
        d = torch.pow(next_state - target, 2).sum()
        d.backward()
        return d
    optimizer.step(cost)
    d = cost()
    if d < 1e-3:
        break
print(time.perf_counter() - t0, " s")
```
## Environment
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.2
GCC version: Could not collect
CMake version: version 3.13.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] gpytorch                  0.1.0rc1                  <pip>
[conda] mkl                       2019.0                      118
[conda] mkl_fft                   1.0.6            py37hb8a8100_0
[conda] mkl_random                1.0.1            py37h5d10147_1
[conda] pytorch                   0.4.1           py37_cuda0.0_cudnn0.0_1    pytorch
[conda] pytorch-nightly           1.0.0.dev20180929         py3.7_0    pytorch
[conda] pytorch-utils             0.4                       <pip>
[conda] torchvision               0.2.1                    py37_1    pytorch

## Additional context
```
otool -L ./a.out
./a.out:
	@rpath/libtorch.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libc10.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libcaffe2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

**Comment by gchanan** [comment]
CC @yf225 @goldsborough.

**Comment by goldsborough** [comment]
Context: I have to admit LBFGS is not well tested as opposed to all other optimizers. I also know this error comes from some in-place operations in the algorithm which have to be done without breaking autograd.

**Comment by MiroFurtado** [comment]
I fixed this problem using a `NoGradGuard` in LBFGS before the parameter update, I'll submit a pull request soon
