### ISSUE TITLE
stable 1.0 with cuda 10 successfully, but cannot pip3 install torchvision!

### ISSUE THREAD

**Issue by 2909638069** [pytorch/pytorch#15958]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
I installed pytorch stable 1.0, linux, pip, python 3.6, successfully. However, when I pip3 install torchvision, it began downloading pytorch for cpu.
So I cancelled the installing torchvision!

Waiting for help!

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
