### ISSUE TITLE
storage  is 0x0 when torch::jit::script::module::forward  in gpu

### ISSUE THREAD

**Issue by deitycitian** [pytorch/pytorch#15957]
Hi, I found out that I can not get the result of torch::jit::script::module::forward  in GPU. I use module::to(torch::kCUDA),  and tensor.to(at::kCUDA) to move to device. The result of module.forward: tensor.impl_.target_'s  storage  is 0x0 when torch::jit::script::module::forward  in GPU

**Comment by zou3519** [comment]
Could you share a minimal repro script or program that demonstrates this? Also, more context about what you're trying to accomplish would be helpful
