### ISSUE TITLE
torch.utils.data.dataloader doesn't support multiprocessing with multiple workers

### ISSUE THREAD

**Issue by fmigneault** [pytorch/pytorch#15950]
When already using many workers of the main process, calling a dataloader iterator with sub-workers will cause : 
`AssertionError: daemonic processes are not allowed to have children`

generated with: 
```
def func(loader):
    for sample_idx, sample in enumerate(loader):
        <code>
```
where `func` is already running on a specific worker of the main application.

similar issue, but not on the same code section (`torch.multiprocessing.spawn`):  #14390

**Comment by SsnL** [comment]
It’s impossible to set your subprocess as daemonic and also ask to use multiprocessing workers. You should either not set your subprocess as daemonic or use num_workers=0. This isn’t a bug at all.
