### ISSUE TITLE
[jit] `for in` for lists

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#15952]
## 🚀 Feature
The JIT currently doesn't support `for in` for list elements. 

i.e. this is not supported:
```python
@torch.jit.script
def fn(a, b):
    # type: (List[int]) -> int
	sum = torch.zeros_like(b[0])
	for item in b:
		sum += item
	return sum
```

Currently, the un-ergonomic workaround is:
```python
@torch.jit.script
def fn(a, b):
    # type: (List[int]) -> int
	sum = torch.zeros_like(b[0])
	for i in range(len(b)):
		sum += b[i]
	return sum
```

**Comment by zou3519** [comment]
It would also be nice to support `enumerate` and `zip`, they make working with python lists a better experience

**Comment by apaszke** [comment]
And list comprehensions! They can be easily desugared into for loops.
