### ISSUE TITLE
unexpected keyword argument 'keepdim'

### ISSUE THREAD

**Issue by shawnjhenry** [pytorch/pytorch#1597]
Hi,

In the docs it appears that reduction operations should accept a boolean parameter "keepdim" that controls whether the number of dimensions is reduced.  I have the latest version of PyTorch and I get an unexpected keyword argument error for all of them.  Is it not implemented yet?

Thanks,
Shawn

**Comment by gchanan** [comment]
What version are you using?  Can you give an example?

**Comment by shawnjhenry** [comment]
I'm using 1.12.  

Something as simple as:
```
x = torch.randn(5, 5)
y = torch.max(x, 1, keepdim=False)
```
throws the error.

**Comment by gchanan** [comment]
It will be available in the next release.  The docs aren't currently versioned, we're working on it.

**Comment by shawnjhenry** [comment]
Ok, thanks.  Just making sure nothing is broken.
