### ISSUE TITLE
[cpp api] clip grad

### ISSUE THREAD

**Issue by mhubii** [pytorch/pytorch#15972]
is it true that clipping gradients is not supported in the cpp api right now?

cheers

martin

**Comment by soumith** [comment]
it's not true. we have [clamp](https://pytorch.org/cppdocs/api/function_namespaceat_1a20be2de650096933b7c01c4d943fda11.html?highlight=clamp) in the C++ API which would comfortably allow you to clip gradients.

**Comment by mhubii** [comment]
a great @soumith. Thank you very much :+1:
