### ISSUE TITLE
Why does ONNX export modifies the behavior of Tensor.shape?

### ISSUE THREAD

**Issue by jasonlovescoding** [pytorch/pytorch#15988]
It seems that when exporting an ONNX model, the output of a torch.Tensor.shape returns a tensor object, whereas it usually returns a simple integer.
Is there a particular reason for the difference?

In fact, exporting x.view(x.size(0), -1) and x.view(x.data.size(0), -1) does return different ONNX models.
I am asking this question because the model returned by x.data.size(0) seems more clear and reasonable to me, and is the same as what pytorch0.4.0 returns without the ".data" part. The difference only starts after 0.4.1. I suspect the behavior of returning a tensor caused onnx export to trace some unnecessary additional nodes.

Code to reproduce the difference 

```
import torch
import torch.nn as nn
import torch.nn.functional as F

class LeNet5(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 6, 5, padding=2, bias=True)
        self.conv2 = nn.Conv2d(6, 16, 5, bias=False)

        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), (2, 2))
        print("x.size(0): ", x.size(0))
        x = x.view(x.size(0), -1)

        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s.item()
        return num_features

model = LeNet5()
inp = torch.ones((1,1,28,28))
model(inp)
torch.onnx.export(model, (inp,), 'test.onnx')
```

Expected Output 
x.size(0):  1
x.size(0):  tensor(1)

cc @BowenBao @neginraoof

**Comment by BowenBao** [comment]
The reason is to accurately support models with dynamic tensor shape. Consider

```python
def forward(self, x):
    return x.size(0)

...

out1 = m(torch.randn(2,3))  # 2
out2 = m(torch.randn(3,3))  # 3

```

Indeed at the cost of additional nodes that may be unnecessary. That's why in latest PyTorch version we added shape analysis to fold these nodes when we are certain the shapes are static.

**Comment by BowenBao** [comment]
Closing, feel free to reopen if there are additional questions.
