### ISSUE TITLE
No module named torch

### ISSUE THREAD

**Issue by Avalon7** [pytorch/pytorch#15999]
I have an issue when I run pytorch in python 2.7. It indicates that "ImportError: No module named torch". I installed by using pip. However, if I use pip3 to install pytorch and run in python 3.7, everything is fine. Any help?

**Comment by SsnL** [comment]
Your pip probably doesn’t match your py2 install.

**Comment by Avalon7** [comment]
> Your pip probably doesn’t match your py2 install.

What do you mean for that? After I installed pytorch via pip, I use "pip list" command, it indicates that I have installed torch package. Thx.

**Comment by peterjc123** [comment]
Run the following commands and you will know the reason.
```bash
which pip
which python

which pip3
which python3
which python3.7
```

**Comment by soumith** [comment]
We have a clear issue template that needs to be used when you open a new Bug Report. It looks like this: https://github.com/pytorch/pytorch/issues/new?template=bug-report.md

If you dont fill that out, we will have to go back and forth asking you a bunch of questions, which is not worth it.

Re-file an issue by properly filling the bug report template.
