### ISSUE TITLE
torch is not linked against caffe2_gpu when USE_CUDA is ON

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#15992]
Originally reported in #15858 by @HapeMask. The CUDA functionality won't work if no functionality in caffe2_gpu was used.
Test code:
```cpp
#include <iostream>
#include <torch/torch.h>

int main() {
	if (!torch::cuda::is_available()) {
		std::cerr << "NO CUDA?" << std::endl;
		return 1;
	}
	if (!torch::cuda::cudnn_is_available()) {
		std::cerr << "NO CUDNN?" << std::endl;
		return 1;
	}
	return 0;
}
```
Output using LibTorch:
```
NO CUDA?
```

**Comment by peterjc123** [comment]
The current dependency graph for PyTorch:
![image](https://user-images.githubusercontent.com/9998726/51075886-8ca0d200-16cc-11e9-892b-96d3d8b97743.png)

**Comment by peterjc123** [comment]
Any thoughts on this? @orionr @ezyang

**Comment by HapeMask** [comment]
I should add that this may only be an issue on Windows. Visual Studio has a few options that are supposed to force linking of all library dependencies but they didn’t work when I tried them here.

**Comment by orionr** [comment]
@peterjc123, thanks for the diagram. torch.dll should be depending on caffe2.dll and caffe2_gpu.dll as well as torch_python.dll. Otherwise torch.dll wouldn't have access to ATen, for example, which is all in caffe2.dll and caffe2_gpu.dll. Sounds like a Windows-specific issue? cc @goldsborough as well as an FYI.

**Comment by peterjc123** [comment]
@orionr Thanks for the clarification. So this is a bug, right? I'll try if doing `WHOLEARCHIVE` during the linking of `torch.dll` helps.

**Comment by orionr** [comment]
Looks like it although I’m not sure how it happens.

On Jan 14, 2019, at 8:32 PM, peterjc123 <notifications@github.com<mailto:notifications@github.com>> wrote:


@orionr<https://github.com/orionr> Thanks for the clarification. So this is a bug, right? I'll try if doing WHOLEARCHIVE during the linking of torch.dll helps.

**Comment by peterjc123** [comment]
@orionr  It seems that the fact that the code in the target `torch` is not using the code in the target `caffe2_gpu` that caused this problem. Could you please show me which part of `torch/csrc` should be using it?

**Comment by orionr** [comment]
I'm not sure, but @ezyang or @zdevito might know. From a CMake perspective the link seems to be there in `torch/CMakeLists.txt`:

```
target_link_libraries(torch caffe2_gpu_library ${TORCH_CUDA_LIBRARIES})
```

**Comment by peterjc123** [comment]
Well, I believe this is another linking issue. `torch::cuda::is_available` is implemented in https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/src/cuda.cpp and it is actually referencing `at::detail::getCUDAHooks()` in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/detail/CUDAHooksInterface.cpp#L12. Near the end of that source file, we can see `C10_DEFINE_REGISTRY` is used here. Then from https://github.com/pytorch/pytorch/blob/master/c10/util/Registry.h#L225 we can see it is using `C10_EXPORT`. 
`CUDAHooksInterface.cpp` is not in c10 so that the C10_EXPORT is useless here. The problem then becomes the following one. In which project do we want to export this one, torch or caffe2_gpu?

**Comment by HapeMask** [comment]
@peterjc123 thanks!
