### ISSUE TITLE
Issues with tutorial “Installing C++ Distributions of PyTorch”

### ISSUE THREAD

**Issue by clemgrt** [pytorch/pytorch#16002]
Good evening everybody,

I’m new to PyTorch and CMake and desperately trying to carry out the tutorial “[Installing C++ Distributions of PyTorch](https://pytorch.org/cppdocs/installing.html)”. It has been now 6 hours i’ve been solving problems one after the other.

Now, I’m trying to execute these commands :

"We can now run the following commands to build the application from within the example-app/ folder:
`mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/libtorch …
make`

"
First, it took me many hours to solve issues with cmake but the right command i had to write is :slight_smile:
“cmake -DCMAKE_PREFIX_PATH=…/libtorch … -Ax64 - DCMAKE_BUILD_TYPE=Debug”

And it finally seems to work fine
This is the output I have 👍 

'
– Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
– Caffe2: CUDA detected: 10.0
– Caffe2: CUDA nvcc is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/bin/nvcc.exe
– Caffe2: CUDA toolkit directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
– Caffe2: Header version is: 10.0
– Found cuDNN: v7.4.2 (include: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include, library: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudnn.lib)
– Autodetected CUDA architecture(s): 5.0
– Added CUDA NVCC flags for: -gencode;arch=compute_50,code=sm_50
CMake Warning (dev) at D:/Yggdrasil/Programmation/PyTorch/libtorch/share/cmake/Caffe2/public/utils.cmake:57 (if):
Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted. Run “cmake --help-policy CMP0054” for policy
details. Use the cmake_policy command to set the policy and suppress this
warning.

Quoted variables like “MSVC” will no longer be dereferenced when the policy
is set to NEW. Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
D:/Yggdrasil/Programmation/PyTorch/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:121 (caffe2_interface_library)
D:/Yggdrasil/Programmation/PyTorch/libtorch/share/cmake/Torch/TorchConfig.cmake:39 (find_package)
CMakeLists.txt:3 (find_package)
This warning is for project developers. Use -Wno-dev to suppress it.

CMake Warning (dev) at D:/Yggdrasil/Programmation/PyTorch/libtorch/share/cmake/Torch/TorchConfig.cmake:72 (if):
Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted. Run “cmake --help-policy CMP0054” for policy
details. Use the cmake_policy command to set the policy and suppress this
warning.

Quoted variables like “MSVC” will no longer be dereferenced when the policy
is set to NEW. Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
CMakeLists.txt:3 (find_package)
This warning is for project developers. Use -Wno-dev to suppress it.

– Configuring done
– Generating done
– Build files have been written to: C:/Users/Clément/Documents/Visual Studio 2017/Projects/PyTorchTest/build
'

Yet the “make” command still doesn’t find anything afterward...

Thanks again for your interest

**Comment by peterjc123** [comment]
If you use MSVC, then the alternative command for make is `msbuild` (or `ninja` if you use Ninja-build). The complete command is `msbuild INSTALL.vcxproj /p:Configuration=Release`, which is used in the script https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.bat#L118.

**Comment by clemgrt** [comment]
Thank you for your answer
> 
> usually the only thing needed to get you going, is to make sure, that your project is able to find libtorch via the associated TorchConfig.cmake file. This can be done in a number of ways, among which the easiest is probably to append the path to your root libtorch directory via the -DCMAKE_PREFIX_PATH flag.

This is what I did -DCMAKE_PREFIX_PATH = ... (absolute path to torchlib)

> to build in debug is your choice ; )
What do you mean ? is there any consequence ?


> 
> 
> If you use MSVC, then the alternative command for make is `msbuild` (or `ninja` if you use Ninja-build). The complete command is `msbuild INSTALL.vcxproj /p:Configuration=Release`, which is used in the script https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.bat#L118.

Thank you sooooo much it is working now !!!

**Comment by peterjc123** [comment]
Glad it worked. Close it, please.
