### ISSUE TITLE
torch.norm doesn't work with "dim" as tuple ints when explicit p is passed

### ISSUE THREAD

**Issue by srb-cv** [pytorch/pytorch#16001]
## 🐛 Bug

 torch.norm doesn't work with "dim" as tuple ints when explicit argument "p" is passed.
## To Reproduce

1. d = torch.arange(8, dtype= torch.float).reshape(2,2,2)
2. torch.norm(d, p=1, dim=(1,2))

Error Trace:
TypeError                                 Traceback (most recent call last)
<ipython-input-264-db5f143404f7> in <module>
----> 1 torch.norm(d,p=1,dim=[1,2])

~/anaconda3/envs/py36/lib/python3.6/site-packages/torch/functional.py in norm(input, p, dim, keepdim, out)
    730     else:
    731         if out is None:
--> 732             return torch._C._VariableFunctions.norm(input, p, dim, keepdim=keepdim)
    733     return torch._C._VariableFunctions.norm(input, p, dim, keepdim=keepdim, out=out)
    734 

TypeError: norm(): argument 'dim' (position 3) must be int, not list

**Comment by soumith** [comment]
cc: @gchanan seems like an argparser / codegen bug?

**Comment by zasdfgbnm** [comment]
Does `aten::norm` support tuple dim?
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Declarations.cwrap#L1558
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L1900

**Comment by srb-cv** [comment]
Just to add, 

> torch.norm(d, dim=(1,2))

works fine as per the documrntation.
Its only when one explicitly pass argument **p** gives the above error with  

> torch.norm(d, p=1, dim=(1,2))

**Comment by gchanan** [comment]
I looked into this briefly.  All combinations of parameters are not supported and it is decently complex (the original PR should have split functions into coherent parts to avoid the complication).  At a minimum we should update the documentation.

**Comment by gchanan** [comment]
This was fixed by https://github.com/pytorch/pytorch/pull/15414.
