### ISSUE TITLE
disabled-configs.txt and enabled-configs.txt is not respected anymore

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#16011]
An example of the CI build: https://github.com/pytorch/pytorch/pull/16009.
I changed `disabled-configs.txt` and `enabled-configs.txt` under `.jenkins/pytorch` and they don't seem to work. Is this a bug or the way to use this feature has changed?

**Comment by soumith** [comment]
cc: @yf225 @ezyang

**Comment by peterjc123** [comment]
Looks like it's solved now.
