### ISSUE TITLE
unexpected behaviour of torch.autograd.grad when computing hessian

### ISSUE THREAD

**Issue by i-cherkasov** [pytorch/pytorch#16015]
## To Reproduce

Consider the following example:

```python
import numpy as np
import torch

torch.manual_seed(42)

n = 2
m = 1000000

x = torch.tensor(range(1, n + 1), dtype=torch.float64, requires_grad=True)
print(x)
k = torch.tensor(0.1, dtype=torch.float64)

f = torch.mean(torch.max(torch.max((x**1).reshape([n, 1]) * torch.exp(torch.randn(n, m, dtype=torch.float64)), dim=0)[0], k))
print(f)

g = torch.autograd.grad(f, x, create_graph=True)[0]
print(g)
h1 = torch.autograd.grad(g[0], x, retain_graph=True)[0]
h2 = torch.autograd.grad(g[1], x, retain_graph=True)[0]
h = torch.stack([h1, h2])
print(h)
```

The output is:

```
tensor([1., 2.], dtype=torch.float64, requires_grad=True)
tensor(3.8796, dtype=torch.float64, grad_fn=<MeanBackward1>)
tensor([0.9656, 1.4570], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)
```

Note that computed hessian is a zero matrix, which is unexpected. Also note the `x**1` thing, without it, just `x`, there is an error:

```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

## Expected behavior

Now consider numpy version:

```python
import numpy as np
import numdifftools as nd

np.random.seed(42)

n = 2
m = 1000000

x = np.array(range(1, n + 1))
print(x)
k = 0.1

f = lambda x: np.mean(np.maximum(np.amax((x.reshape([n, 1]) * np.exp(np.random.randn(n, m))), axis=0), k))
print(f(x))

g = nd.Gradient(f)
print(g(x))

h = nd.Hessian(f)
print(h(x))
```

The output is:

```
[1 2]
3.883462096496137
[0.9871435  1.46039303]
[[ 0.33673737 -0.2455471 ]
 [-0.2455471   0.09991793]]
```

Note, that function `f` value and its first derivative agree in both numpy and pytorch version.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0.0
 - OS (e.g., Linux): Ubuntu 18.04.1 LTS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by apaszke** [comment]
In the NumPy script you keep resampling the random data, while in the PyTorch script it's hardcoded. This is what confuses the numerical differentiation that NumPy uses, while PyTorch returns the true hessian, which is all 0 for this function (you can verify this by hand, but a simple argument is that if you disregard the non-linearity of max, it is basically linear).

**Comment by i-cherkasov** [comment]
Well, you can factor out the random part, I guess I just made the example too concise. In the modified snippet below, I believe, the random part is not resampled any longer when function is evaluated inside the numdifftools routines. 

This function `f` is basically a simplified E[max(x*exp(z) - k, 0)], which is nonlinear, that's kind of the point of trying to compute Hessian here.

```python
import numpy as np
import numdifftools as nd

np.random.seed(42)

n = 2
m = 1000000

x = np.array(range(1, n + 1))
print(x)
k = 0.1

z = np.random.randn(n, m)

f = lambda x: np.mean(np.maximum(np.amax((x.reshape([n, 1]) * np.exp(z)), axis=0), k))
print(f(x))

g = nd.Gradient(f)
print(g(x))

h = nd.Hessian(f)
print(h(x))
```

```
[1 2]
3.883462096496137
[0.96332632 1.46006589]
[[ 0.45540183 -0.22805133]
 [-0.22805133  0.11386603]]
```
