### ISSUE TITLE
CPU convolution (MKL-DNN) with non-contiguous weights is incorrect

### ISSUE THREAD

**Issue by yangkky** [pytorch/pytorch#16018]
## 🐛 Bug

If I load convolution weights from a NumPy float32 array, the result of the forward pass does not match that of a layer with the same weights loaded from a NumPy float64 array or of a Keras convolution layer with the same weights. Casting the layer to `double` fixes the discrepancy, even after casting back to `float`. Comparing the convolution weights before and after casting shows that they have not changed. 

## To Reproduce
```python
import numpy as np
import torch
from torch import nn

d_in = 25
d_out = 64
k = 7
B = 2
L = 10

conv = nn.Conv1d(d_in, d_out, k, stride=2, padding=0)
pad = nn.ConstantPad1d((2, 3), 0)
np.random.seed(1034)
X = np.random.random((B, L, d_in))
X = torch.as_tensor(X).transpose(-1, -2)
X = pad(X)
w = np.random.random((k, d_in, d_out))
w = w.astype('float32')
b = np.random.random((d_out, ))

w = torch.as_tensor(w).permute(2, 1, 0).float()
b = torch.as_tensor(b).float()

conv.weight = nn.Parameter(w)
conv.bias = nn.Parameter(b)

out1 = conv(X.float()).detach().numpy()
w1 = conv.weight.detach().numpy()
out2 = conv.double()(X).detach().numpy()
w2 = conv.weight.detach().numpy()
out3 = conv.float()(X.float()).detach().numpy()
w3 = conv.weight.detach().numpy()
print('w == w1?')
print(np.allclose(w.detach().numpy(), w1))
print('w1 == w2?')
print(np.allclose(w1, w2))
print('w2 == w3?')
print(np.allclose(w2, w3))
print('out1 == out2?')
print(np.allclose(out1, out2, atol=1e-6))
print('out2 == out3?')
print(np.allclose(out2, out3, atol=1e-6))
```

Result: 

```
w == w1?
True
w1 == w2?
True
w2 == w3?
True
out1 == out2?
False
out2 == out3?
True
```

Some notes: 
1. The type for the bias doesn't seem to matter. 
2. `out2` and `out3` match the result for a Keras convolution layer with the same weights. 

## Expected behavior

`out1` should be within machine precision of `out2` and `out3`. 

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.2
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-service               1.1.2            py37hfbe908c_5  
[conda] mkl_fft                   1.0.6            py37h27c97d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0  
[conda] pytorch                   1.0.0                   py3.7_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch
[conda] numpy                    1.15.4

**Comment by yangkky** [comment]
I also tried this on an AWS Ubuntu Deep Learning AMI running on a p3. When running on CPU, I still get the same bug. If I move things to Cuda though, it goes away. 

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609                                                       
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 410.79
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/lib64/libcudnn.so.7.4.1
/usr/local/cuda-10.0/lib64/libcudnn_static.a
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so.7.3.1
/usr/local/cuda-9.0/lib64/libcudnn_static.a
/usr/local/cuda-9.2/lib64/libcudnn.so.7.3.1
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] numpydoc (0.8.0)
[pip] torch (1.0.0)
[pip] torchvision (0.2.1)
[conda] blas                      1.0                         mkl                                                  
[conda] cuda100                   1.0                           0    pytorch                                       
[conda] mkl                       2018.0.2                      1                                                  
[conda] mkl-service               1.1.2            py36h17a0993_4                                                  
[conda] mkl_fft                   1.0.1            py36h3010b51_0                                                  
[conda] mkl_random                1.0.1            py36h629b387_0                                                  
[conda] pytorch                   1.0.0           py3.6_cuda10.0.130_cudnn7.4.1_1  [cuda100]  pytorch              
[conda] torchvision               0.2.1                      py_2    pytorch

## Output running the same mwe as above
```
w == w1?
True
w1 == w2?
True
w2 == w3?
True
out1 == out2?
False
out2 == out3?
True
```

## Running on Cuda

```python
import numpy as np
import torch
from torch import nn

d_in = 25
d_out = 64
k = 7
B = 2
L = 10

conv = nn.Conv1d(d_in, d_out, k, stride=2, padding=0)
pad = nn.ConstantPad1d((2, 3), 0)
np.random.seed(1034)
X = np.random.random((B, L, d_in))
X = torch.as_tensor(X).transpose(-1, -2).cuda()
X = pad(X)
w = np.random.random((k, d_in, d_out))
w = w.astype('float32')
b = np.random.random((d_out, ))

w = torch.as_tensor(w).permute(2, 1, 0).float().cuda()
b = torch.as_tensor(b).float().cuda()

conv.weight = nn.Parameter(w)
conv.bias = nn.Parameter(b)

out1 = conv(X.float()).detach().cpu().numpy()
w1 = conv.weight.detach().cpu().numpy()
out2 = conv.double()(X).detach().cpu().numpy()
w2 = conv.weight.detach().cpu().numpy()
out3 = conv.float()(X.float()).detach().cpu().numpy()
w3 = conv.weight.detach().cpu().numpy()
print('w == w1?')
print(np.allclose(w.detach().cpu().numpy(), w1))
print('w1 == w2?')
print(np.allclose(w1, w2))
print('w2 == w3?')
print(np.allclose(w2, w3))
print('out1 == out2?')
print(np.allclose(out1, out2, atol=1e-6))
print('out2 == out3?')
print(np.allclose(out2, out3, atol=1e-6))
```

Now everything is as it should be: 

```
w == w1?
True
w1 == w2?
True
w2 == w3?
True
out1 == out2?
True
out2 == out3?
True
```

**Comment by colesbury** [comment]
This appears to be a regression since 0.4. The issue is that `conv.weight` is non-contiguous. Internally, we should make sure that "weight" is contiguous before calling into MKL-DNN.
