### ISSUE TITLE
No error when selecting a stream that belongs to a different device

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#16019]
## 🐛 Bug

[doc](https://pytorch.org/docs/stable/cuda.html) says:

> Streams are per-device, and this function changes the “current stream” only for the currently selected device. It is illegal to select a stream that belongs to a different device.

But it just silently change current stream on that "different" device to the given one, and no error was raised. The context stays the same as if `torch.cuda.stream(Stream)` was not called, which might lead to unexpected behavior. 

## To Reproduce

```python
import torch

s0 = torch.cuda.current_stream()
s1 = torch.cuda.Stream(device=1)

with torch.cuda.stream(s1):
    torch.cuda._sleep(500000000)

print(s0.query())  # prints False
print(s1.query())  # prints True
```

## Expected behavior

Option 1: prints an error when stream device and context device does not match?
Option 2: automatically switch to the inner most context?

@colesbury any preference?

## Environment
Collecting environment information...
PyTorch version: 1.1.0a0+43b7a5e
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration: 
GPU 0: Tesla M40
GPU 1: Tesla M40

Nvidia driver version: 396.26
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.1.2
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/fbcode/gcc-5-glibc-2.23/lib/libcudnn.so.6
/usr/local/fbcode/gcc-5-glibc-2.23/lib/libcudnn.so.6.0.20
/usr/local/fbcode/gcc-5-glibc-2.23/lib/libcudnn.so.6.0.21
/usr/local/fbcode/gcc-5-glibc-2.23/lib/libcudnn.so.7.1.2
/usr/local/fbcode/gcc-5-glibc-2.23/lib/libcudnn.so.7.1.4
/usr/local/fbcode/platform007/lib/libcudnn.so.7.1.4

**Comment by ezyang** [comment]
As a data point, in the current C++ API for CUDAStreamGuard, if you pass a stream that lives on a different device, we change *both* the device and the stream.

**Comment by colesbury** [comment]
The CUDAStreamGuard semantics (changing both device and stream) seem reasonable and more friendly than raising an error
