### ISSUE TITLE
_grad_input_padding does not consider the dilation.

### ISSUE THREAD

**Issue by ozzzp** [pytorch/pytorch#16012]
in https://github.com/pytorch/pytorch/blob/f8086845aacdb6e5c3e46313899105255a5a9822/torch/nn/grad.py#L7-L31
`dim_size` does not consider dilation hence it only return the correct result when `dilation = 1`, the correction should be `((grad_output.size(d + 2) - 1) * stride[d] - 2 * padding[d] + 
                 1 + dilation[d] *  (kernel_size[d] -1))`

Further More, https://github.com/pytorch/pytorch/blob/f8086845aacdb6e5c3e46313899105255a5a9822/torch/nn/grad.py#L164-L214

line 194 waste too much GPU memory cause of the repeat operator. I have a faster version but only support  the case that `in_channels % groups == 0 and out_channels % groups == 0 `. For this optimization issue, does anyone has some ideas?.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by ggggggggbahugoa** [comment]
Thank you very much!!!

**Comment by adler-j** [comment]
Could you please post your solution to the repeat issue? I'm also finding this very slow.

**Comment by albanD** [comment]
We should add check that the dilation is 1 before calling this function.

**Comment by gchanan** [comment]
actionable to update the PR to include tests.
