### ISSUE TITLE
More readable error message for index error of nn.Embedding  in CUDA

### ISSUE THREAD

**Issue by tamuhey** [pytorch/pytorch#16027]
## 🚀 Feature
More readable error message for index error of nn.Embedding  in CUDA

## Motivation

If nn.Embedding received a tensor containing larger values than `num_embeddings`, raise an error as follows:

```
RuntimeError: index out of range at ...
```

However, if nn.Embedding exists in CUDA, raises error message as follows:

```
RuntimeError: cuda runtime error (59) : device-side assert triggered ...
```

This error message is too hard to know why the error is occurred.
I spent a lot of time to find out the reason, so I created this feature request.

**Comment by zou3519** [comment]
It's complicated; if we do specific error checks then the code becomes much slower because we'd have to launch a kernel just to do the error checking.
