### ISSUE TITLE
mseloss

### ISSUE THREAD

**Issue by yyhlvdl** [pytorch/pytorch#16030]
hi, I face this situation:
given two pictures:(64,2,101,200), then I cal their mseloss. And the loss is 6*10^8, however I want the mean loss, but it  didn't work, thus my model won't update.
 And I use pytorch=0.4.0,python=2.7.

Could anyone solve my problem,plz?

**Comment by albanD** [comment]
Hi,

Please use the [forum](https://discuss.pytorch.org/) for questions, we only use github issues for bug tracking. Thanks
