### ISSUE TITLE
torch.autograd.backward does not handle dependent Variables correctly

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#1605]
Here's a failure case on master:

```python
import torch
from torch.autograd import Variable

x = Variable(torch.randn(10), requires_grad=True)
y = x ** 2
z = y ** 3

torch.autograd.backward([y, z], [torch.randn(10), torch.randn(10)])
```

and here's the stack-trace:
```
Traceback (most recent call last):
  File "foo.py", line 10, in <module>
    torch.autograd.backward([y, z], [torch.randn(10), torch.randn(10)])
  File "/home/soumith/code/pytorch/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/home/soumith/code/pytorch/torch/autograd/function.py", line 90, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/soumith/code/pytorch/torch/autograd/_functions/basic_ops.py", line 209, in backward
    var, = ctx.saved_variables
RuntimeError: Trying to backward through the graph second time, but the buffers have already been freed. Please specify retain_variables=True when calling backward for the first time.
```

**Comment by zym1010** [comment]
is this well defined? I think grad of `z` implicitly defines grad of `y`. So supplying grad for both doesn't make sense mathematically.

**Comment by abhinavgupta94** [comment]
What if you want to have more than one gradient for y (one coming from z and one from another variable)...

**Comment by apaszke** [comment]
It is well defined. You could apply an identity function to `y` and it would be equivalent to a common use case of `torch.autograd.backward`. I suspect that we're adding all the grad_fns of Variables given to `backward` to the `ready` queue, even if they should wait for part of the graph to be computed.

**Comment by zym1010** [comment]
@apaszke I see what you mean. Currently I can overcome the issue like this.

~~~
import torch
from torch.autograd import Variable

x = Variable(torch.randn(10), requires_grad=True)
y = x ** 2
z = y ** 3
k = y ** 1

torch.autograd.backward([k, z], [torch.randn(10), torch.randn(10)])
~~~

When I change `k = y**1` to `k = y`, then it breaks. But in any case, I think setting the grad of `y` and setting the grad of a (maybe trivial) function of `y` are totally different. Maybe we want the semantics of PyTorch is such that, if we set the grad of some intermediate variable, it's understood that we have some additional auxiliary output that is identity function of that variable?

**Comment by zym1010** [comment]
> Maybe we want the semantics of PyTorch is such that, if we set the grad of some intermediate variable, it's understood that we have some additional auxiliary output that is identity function of that variable?

I think this would also introduce some messy problems. Consider the meaning of

```
torch.autograd.backward([y, y, y], [torch.randn(10), torch.randn(10), torch.randn(10)])
```

I think the best approach is to explicitly declare that we want to create some identity function.

**Comment by ezyang** [comment]
@zym1010 I think it is clearer to think about the meaning of multiple parameters to `backward` as introducing an on-the-fly loss function operating on the parameters which has a gradient equal the arguments you pass. So, your example is equivalent to this:

```
loss = f(y, y, y)
torch.autograd.backward(loss)
# where df/dloss = [torch.randn(10), torch.randn(10), torch.randn(10)]
```

Now it should be pretty clear what the intended semantics of your example above should be.
