### ISSUE TITLE
torch.cuda.device not working but torch.cuda.set_device works

### ISSUE THREAD

**Issue by SelvamArul** [pytorch/pytorch#1608]
I have four GPU cards:
```
import torch as th

print ('Available devices ', th.cuda.device_count())
print ('Current cuda device ', th.cuda.current_device())
```

```
Available devices  4
Current cuda device  0
```

When I use `torch.cuda.device` to set GPU device, the current device remains the same. Whereas when I use `torch.cuda.set_device` ,  it works:

```
for i in range(1,4):
    print ('set device (th.cuda.device)-->{}'.format(i))
    th.cuda.device(i)
    print ('Current cuda device ' ,th.cuda.current_device())

    print ('set device (th.cuda.set_device)-->{}'.format(i))
    th.cuda.set_device(i)
    print ('Current cuda device ' ,th.cuda.current_device())
    print ('--------------------')
```

```
set device (th.cuda.device)-->1
Current cuda device  0
set device (th.cuda.set_device)-->1
Current cuda device  1
--------------------
set device (th.cuda.device)-->2
Current cuda device  1
set device (th.cuda.set_device)-->2
Current cuda device  2
--------------------
set device (th.cuda.device)-->3
Current cuda device  2
set device (th.cuda.set_device)-->3
Current cuda device  3
--------------------
```

**Comment by albanD** [comment]
Hi,

`torch.cuda.device()` is a context manager:
```
torch.cuda.set_device(0)
# On device 0
with torch.cuda.device(1):
    print("Inside device is 1")    
    # On device 1
print("Outside is still 0")
# On device 0
```

**Comment by SelvamArul** [comment]
@albanD 

ah ya. Sorry, I overlooked it.

**Comment by isalirezag** [comment]
@albanD so if i want to use gpu 0 and 1 what should i do?

**Comment by SelvamArul** [comment]
@isalirezag Could you please elaborate on what you mean by using gpu 0 and 1. Tensors lie on just one card. The device context manager controlls the card to used for creating a new tensor.

Do you mean only card 0 and 1 should be made available to your PyTorch program?
Is [CUDA_VISIBLE_DEVICES](https://devblogs.nvidia.com/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) what your are looking for?

**Comment by sevenguin** [comment]
> Hi,
> 
> `torch.cuda.device()` is a context manager:
> 
> ```
> torch.cuda.set_device(0)
> # On device 0
> with torch.cuda.device(1):
>     print("Inside device is 1")    
>     # On device 1
> print("Outside is still 0")
> # On device 0
> ```

If i just have 1 GPU card, and i use with torch.cuda.device(1), what happend? It's OK?
