### ISSUE TITLE
Understanding performance of Sparse Matrix 

### ISSUE THREAD

**Issue by soulslicer** [pytorch/pytorch#16114]
Hi all,

I wish to use Pytorch to perform some GPU large sparse matrix vector multiplication. My object is of float size say (130 * 50000). I want to know the performance of this compared to say that of Eigen::Sparse

**Comment by soumith** [comment]
go ahead and benchmark it against Eigen::Sparse.
Please use https://discuss.pytorch.org if you need any guidance on how to benchmark pytorch side of things.
