### ISSUE TITLE
"**" is much slower than "*" on my Macbook Air

### ISSUE THREAD

**Issue by carefree0910** [pytorch/pytorch#1612]
I'm learning PyTorch from scratch today and find something strange to me:
![screen shot 2017-05-22 at 23 06 04](https://cloud.githubusercontent.com/assets/15677328/26314964/32fd3b5c-3f42-11e7-8f6d-c8e938d6ec64.png)
![screen shot 2017-05-22 at 23 06 32](https://cloud.githubusercontent.com/assets/15677328/26314971/35ccdc48-3f42-11e7-84ca-d46095c324d3.png)
But Numpy will not:
![screen shot 2017-05-22 at 23 08 07](https://cloud.githubusercontent.com/assets/15677328/26315074/90d22a6c-3f42-11e7-9426-48095ff381bb.png)
Is this 'normal' ?

**Comment by soumith** [comment]
this is normal. NumPy uses special SIMD instructions on the CPU or uses cachelines better for accelerating pow. We will get there eventually, but haven't.
You might find something slower or faster on either library depending on the workflow. Given enough time and effort, we'll converge on the same speed.

**Comment by carefree0910** [comment]
Thanks for the quick responding and the detailed explanation!

**Comment by apaszke** [comment]
It's actually something different. In your second example you're raising the input to 2nd power, not to the third, which triggers an optimized path in NumPy. When I change `** 2` to `** 3`, the run time raises from 3ms to 30ms

**Comment by fmassa** [comment]
Also, your comparison is not fair, because you compared `**2` on numpy with `** 3` in pytorch.

**Comment by fmassa** [comment]
```python
In [7]: y = np.random.random([1000, 1000])

In [8]: %timeit y * y * y
100 loops, best of 3: 11.5 ms per loop

In [9]: %timeit y ** 3
10 loops, best of 3: 73.2 ms per loop

In [10]: yt = torch.from_numpy(y)

In [11]: %timeit yt ** 3
10 loops, best of 3: 81.5 ms per loop

In [12]: %timeit yt * yt * yt
100 loops, best of 3: 4.18 ms per loop
```

**Comment by carefree0910** [comment]
I'm sorry for my imprecision, here's the performance of `**2` in torch:
![screen shot 2017-05-23 at 00 09 48](https://cloud.githubusercontent.com/assets/15677328/26317852/74f2c0dc-3f4b-11e7-865f-ef6784397f23.png)
Thanks for your replies, they really inspired me a lot!
