### ISSUE TITLE
legacy MM.py index error

### ISSUE THREAD

**Issue by tcosmo** [pytorch/pytorch#1613]
Hi I think that in 
https://github.com/pytorch/pytorch/blob/master/torch/legacy/nn/MM.py

lines 28 and 30:

`if self.transA:
                a = a.transpose(2, 3)
            if self.transB:
                b = b.transpose(2, 3)`

should be:

`if self.transA:
                a = a.transpose(1, 2)
            if self.transB:
                b = b.transpose(1, 2)`

Indeed in that branch the tensor has 3 dimension and thus the code crashes.
Maybe an indexing error when translating from lua ?
Thank you very much,

**Comment by apaszke** [comment]
Yes, you're right. Could you send a PR with a fix? Thanks!

**Comment by tcosmo** [comment]
Yes of course, just done, thank you very much.
