### ISSUE TITLE
[C++ Frontend] Cannot load and save model if non shared pointer

### ISSUE THREAD

**Issue by blackccpie** [pytorch/pytorch#16147]
## 🐛 Bug

Cannot load and save a `nn::Module` herited model if instanciated on the stack.

## To Reproduce

try to compile the following code:

```cpp
struct M : torch::nn::Module {};

M out; // DOES NOT COMPILE
//auto out = std::make_shared<M>(); // COMPILES OK
std::stringstream ss;
torch::save(out, ss);
```

## Expected behavior

The only workaround I found is to work with `shared_ptr` of `M`, but I think it would be nice if we could work with a stack allocated `nn::Module`

## Environment

 - PyTorch Version : LibTorch 1.0 (nightly)
 - OS : Win10
 - How you installed PyTorch : downloaded precompiled LibTroch from official site 
- compiler : Visual C++ 2017

**Comment by CDitzel** [comment]
Take a look at the official C++ front end tutorial.

https://pytorch.org/tutorials/advanced/cpp_frontend.html

there is a section there explaining the ownership model that works behind the scene and answers your question

**Comment by blackccpie** [comment]
@CDitzel : thanks for the link, now it's clearer for me, and the link mentions that `torch::save` only supports module holders or or plain `shared_ptr`. But it could be nice to have this information more explicitly through the Library API documentation of [torch::save](https://pytorch.org/cppdocs/api/function_namespacetorch_1a99dc9f736064b2179cc58e6436f7a021.html?highlight=torch%3A%3Asave#_CPPv3N5torch4saveERK5ValueDpRR10SaveToArgs).

**Comment by wesboyt** [comment]
This took me quite awhile to figure out. All of the central tutorial examples rely on simple linear model saves. I found a random example elsewhere the used std::make_shared to save the module but it is not clear in the examples that this is necessary. And the code itself is anything but well documented. I would recommend adding a self rolled module save example. I can ever provide a pr if needed.
