### ISSUE TITLE
[Bug] CPU memory keeps increasing when using gloo backend

### ISSUE THREAD

**Issue by stgzr** [pytorch/pytorch#16144]
## 🐛 Bug
I found CPU memory keeps increasing when using `dist.all_gather` in `gloo` backend.
Update: it seems that `gather` and `all_reduce` have the same issue.

## To Reproduce
``` python
""" test.py """
import os
import sys
import gc
import logging
import time
import torch
import torch.distributed as dist
from torch.distributed import get_rank, get_world_size

from mpi4py import MPI
comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()
print (rank, size)
os.environ['CUDA_VISIBLE_DEVICES'] = str(rank)
os.environ['MASTER_ADDR'] = '127.0.0.1'
os.environ['MASTER_PORT'] = '23333'
os.environ['WORLD_SIZE'] = str(size)
os.environ['RANK'] = str(rank) 
dist.init_process_group(backend="gloo")

print ("initialize gloo successfully [rank {}] pid({})".format(rank, os.getpid()))

torch.backends.cudnn.benchmark = True

if __name__ == "__main__":
    batch_size = 16
    feat_dim = 2048
    pid = os.getpid()
    prev_mem = 0
    tensor_list = [torch.FloatTensor(batch_size, feat_dim) for _ in range(get_world_size())]
    values = torch.FloatTensor(batch_size, feat_dim)
    for idx in range(10000):
        if idx % 20 == 0 and get_rank() == 0:
            cur_mem = (int(open('/proc/%s/statm' % pid, 'r').read().split()[1]) + 0.0) / 256
            add_mem = cur_mem - prev_mem
            prev_mem = cur_mem
            print ("train iterations: %s, added mem: %s M" % (idx, add_mem))
        dist.all_gather(tensor_list=tensor_list, tensor=values)
```
``` bash
mpirun -n 4 python test.py
```
Result:
>...
train iterations: 2340, added mem: 10.0546875 M
train iterations: 2360, added mem: 10.0546875 M
train iterations: 2380, added mem: 9.796875 M
train iterations: 2400, added mem: 10.0546875 M
train iterations: 2420, added mem: 10.0546875 M
train iterations: 2440, added mem: 10.0546875 M
train iterations: 2460, added mem: 10.0546875 M
train iterations: 2480, added mem: 10.0546875 M
train iterations: 2500, added mem: 9.796875 M
train iterations: 2520, added mem: 10.0546875 M
train iterations: 2540, added mem: 10.0546875 M
...

## Expected behavior
CPU memory keeps increasing (`added mem` has positive value)

## Environment
 - PyTorch Version: 1.0.0
 - OS: CentOS 7.2
 - GCC version: (GCC) 4.8.5 20150623
 - CMake version: version 3.12.2
 - How you installed PyTorch: `conda` and source
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 2.7.15
 - CUDA/cuDNN version: CUDA 9.0 / cuDNN 7.2
 - GPU models and configuration:
     GPU 0: Tesla P100-PCIE-16GB
     GPU 1: Tesla P100-PCIE-16GB 
     GPU 2: Tesla P100-PCIE-16GB
     GPU 3: Tesla P100-PCIE-16GB
     GPU 4: Tesla P100-PCIE-16GB
     GPU 5: Tesla P100-PCIE-16GB
     GPU 6: Tesla P100-PCIE-16GB
     GPU 7: Tesla P100-PCIE-16GB

## Additional context
It works well when I use PyTorch v0.4.0.

**Comment by soumith** [comment]
cc: @pietern

**Comment by pietern** [comment]
Thanks for the report. I'll investigate shortly.

**Comment by pietern** [comment]
I'm able to reproduce. Haven't zeroed in on the cause yet. Removing the `gloo::allgather` call fixes the problem, so this hints at something in Gloo holding on to memory. At the same time, when I run the Gloo tests through Valgrind it's free of leaks. I'll update here with anything I find.

**Comment by pietern** [comment]
The memory leak is internal to the Gloo transport and is triggered by the communication tag increasing and entries to send/recv operations not being cleaned up properly. This is why it doesn't show up in Valgrind; it's a logical leak, not a conventional leak. I'm working on a fix.

**Comment by stgzr** [comment]
@pietern I recompiled PyTorch with the modified version of Gloo. It seems that the memory leak issue won't happen again. I will try `reduce` and `gather` later. Thank you very much👍

**Comment by pietern** [comment]
@stgzr With the fix landed this should now be resolved. Separately, I added a test to Gloo to test for memory growth. Also, we'll include it as part of the manual verification for big releases. This one slipped through the cracks on 1.0. Thanks again for reporting!

**Comment by soumith** [comment]
just fyi this patch will be part of the v1.0.1 release.
