### ISSUE TITLE
Document torch.Generator()

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#1614]
Right not it's not mentioned anywhere in the docs. Also, random functions don't have a generator argument in their signature.

**Comment by colesbury** [comment]
Should `generator` be a keyword-only argument (like `out`)?

I would lean towards makings it keyword-only. It seems awkward in Python to have optional arguments at position 0.

**Comment by soumith** [comment]
yes let's make it keyword only

**Comment by apaszke** [comment]
I think it's already keyword only (except that long_args disable it altogether).

**Comment by syed-ahmed** [comment]
It's now documented in master: https://pytorch.org/docs/master/torch.html#generators.

**Comment by fmassa** [comment]
Closing this via @Syed-Ahmed comment
