### ISSUE TITLE
Port UpsamplingNearest to ATen

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#16158]
It would be good to port UpsamplingNearest to ATen because backward kernels for half have very bad performance, and it will be easier to fix them while they are in ATen.

**Comment by bhack** [comment]
Also it could be nice to have interpolate exposed in `at::`:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/register_prim_ops.cpp#L1490

**Comment by ezyang** [comment]
CPU part was ported in #18020

**Comment by jjsjann123** [comment]
Now #19630 is in, I'll start looking at porting faster kernel implementation.

**Comment by xmnlab** [comment]
I am applying some suggestion from #19630 on a new PR #20505 .. basically changing the order of some parameters and fixing the kernel launching
