### ISSUE TITLE
torch.rand and torch.randn don't accept generator kwarg

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#1616]
Even though it's declared in cwrap

**Comment by colesbury** [comment]
For anyone working on the issue, this is because `long_args: True` in cwrap disables keyword arguments.

**Comment by stegben** [comment]
If it don't support `long_args: True`, does that mean we should use them in such way:
```python
torch.randn(size=(10, 5, 5))
```
instead of
```python
torch.randn(10, 5, 5)
```
?
