### ISSUE TITLE
Dependencies of ramenv

### ISSUE THREAD

**Issue by JMVS1996** [pytorch/pytorch#16188]
Hi, i am trying to activate an enviroment (ramenv) from de Anaconda cloud: https://anaconda.org/apetros.

When i use the command:  "conda env create apetros/ramenv" on the anaconda prompt the problem the next message appears: 

**"UnsatisfiableError: The following specifications were found to be in conflict:
  - mkl==2019.0=118
  - numpy==1.15.2=py37ha559c80_0 -> mkl_fft[version='>=1.0.4'] -> mkl[version='>=2019.1,<2020.0a0']
Use "conda info <package>" to see the dependencies for each package."**

I tryed to install mkl==mkl==2019.0=118, but then a similiar error appeared. 

¿How can i solve this?

Thanks for your help,

**Comment by soumith** [comment]
this is the pytorch issue tracker. we have no relation to the above.
