### ISSUE TITLE
[Feature Request] Add `__getitem__()` to `nn.Module`

### ISSUE THREAD

**Issue by yukkyo** [pytorch/pytorch#16181]
## 🚀 Feature

Enable to call each layer in nn.Module like python dict.

`self.__getattr__(layer_name)` or `getattr(self, layer_name)`
-> `self[layer_name]`

## How

Add bellow function to `nn.Module` .
- reference: [chainer.Chain](https://github.com/chainer/chainer/blob/v5.1.0/chainer/link.py#L871-L873)

```python
    def __getitem__(self, name):
        """Equivalent to getattr."""
        return getattr(self, name)
```

## Motivation

Access each layer in network easily (Especially for beginners).

#### old

```python
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        ...

    def forward(self, x):
        ...
        # Apply each conv<number>_1, conv<number>_2
        for i in range(10, 11 + 1):
            output_tmp = outputs[-1]
            output_tmp = F.relu(getattr(self, f'conv{i:d}_1')(output_tmp))
            output_tmp = F.relu(getattr(self, f'conv{i:d}_2')(output_tmp))
            outputs.append(output_tmp)
        return outputs
```

#### new

```python
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        ...

    def forward(self, x):
        ...
        # Apply each conv<number>_1, conv<number>_2
        for i in range(10, 11 + 1):
            output_tmp = outputs[-1]
            output_tmp = F.relu(self[f'conv{i:d}_1'](output_tmp))
            output_tmp = F.relu(self[f'conv{i:d}_2'](output_tmp))
            outputs.append(output_tmp)
        return outputs
```

Maybe this is different from the concept of PyTorch?

**Comment by zou3519** [comment]
We are not against this, this should be helpful in some cases like the one you described.

**Comment by yukkyo** [comment]
Thank you for checking this issue !
I am looking forward to it :)

**Comment by hikjik** [comment]
Hi, I'm new to pytorch and would like to start contributing. If the issue is still open, can I take a look at this and try to fix it?

**Comment by zou3519** [comment]
@hikjik yes, please go ahead

**Comment by soumith** [comment]
see linked PR for context, and I apologize to @hikjik for putting the effort and having the PR closed.

Reasoning as to not having this (from #18102):

> I'd agree with Adam here. nn.Module is a class, and it's not normal or expected to have a __getitem__ like a dict. If you generally want a dict, you'd stick it in a nn.ModuleDict, if not you're better off simply using getattr
