### ISSUE TITLE
ppc64le CI build failure (possibly due to #16006

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#16198]
## 🐛 Bug

ppc64le CI build fails with psutil not found.

Running test_dataloader ... [2019-01-20 15:16:53.873206]
Traceback (most recent call last):
  File "test_dataloader.py", line 24, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

pytorch version : pull from master for last 3 days.
here is the CI log:
https://powerci.osuosl.org/user/avmgithub/my-views/view/PyTorch/job/pytorch-linux-cuda92-cudnn7-py3-mpi-build-test-gpu/269/console

CC:  @SsnL

**Comment by soumith** [comment]
@avmgithub the docker image for the contbuild has to be updated with `pip install psutil`

**Comment by SsnL** [comment]
This is expected. Any env invoking `.jenkins/pytorch/common.sh` is assumed to be a PyTorch CI env. For PyTorch CI env, we require `psutil` to be installed.
