### ISSUE TITLE
Modifying Intermediate outputs during Inference

### ISSUE THREAD

**Issue by ecotones** [pytorch/pytorch#16197]
I am trying to modify the computation of neural nets during inference or testing phase. During Inference I want to access intermediate layer outputs and replace some percent of the values in the vector with zero or random values. How can I build a custom layer so that I can train normally using usual layers but during testing(maybe use a flag to distinguish between train and test), I replace some intermediate values(the activations)? A code snippet would be really helpful.

Thanks

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
