### ISSUE TITLE
Dimension error always says dimension 0

### ISSUE THREAD

**Issue by AliengirlLiv** [pytorch/pytorch#16192]
## 🐛 Bug

Out of bounds dimension errors while indexing always mention dimension 0, regardless of the dimension being accessed

## To Reproduce

    test_indexing = torch.tensor([[1,2,3],[4,5,6]])
    print(test_indexing[7,0]) 

This gives the message `IndexError: index 7 is out of bounds for dimension 0 with size 2`.

    print(test_indexing[0,7])

This gives the error `IndexError: index 7 is out of bounds for dimension 0 with size 3`

   
## Expected behavior

I assume the second print statement should reference dimension 1, not 0.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 410.79
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.4.2
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] faster-rcnn (0.1, /home/mehdi2277/Documents/HarveyMuddWork/Neural_Nets_Research/temp-pedro-ci/gan-image-metrics/faster-rcnn.pytorch-pytorch-1.0/lib)
[pip3] msgpack-numpy (0.4.3.1)
[pip3] numpy (1.15.4)
[pip3] pytorch-pretrained-bert (0.3.0)
[pip3] torch (1.0.0)
[pip3] torchfold (0.1.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by zou3519** [comment]
I think what is going on is that the tensor gets indexed multiple times in that pathway and then the error message becomes wrong.

**Comment by bhushan23** [comment]
@colesbury 
In python_variable_indexing, applySelect always works on top most dimension and modifies the tensor
In that case, we can force it to always use 0th dimension (which is always passed) and use dim argument to error out correct dimension (which will be increamented outside)
what do you think?
