### ISSUE TITLE
torch.load(model_file): _pickle.UnpicklingError: invalid load key, '<'

### ISSUE THREAD

**Issue by IssamLaradji** [pytorch/pytorch#16203]
## 🐛 Bug

For an old `state_dict` file, using torch.load returns `_pickle.UnpicklingError: invalid load key, '<'`

## To Reproduce
Run the following in terminal:
```
git clone https://github.com/Wanger-SJTU/FCN-in-the-wild.git
cd FCN-in-the-wild/FCN/pretrain_model
```
Then start python and run the following commands,

```
import torch
torch.load("vgg16_from_caffe.pth")
```
This returns 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.
```

## Expected behavior

`torch.load("vgg16_from_caffe.pth")` should return state_dict instead

## Environment

 - PyTorch Version 1.0:
 - OS: Ubuntu 16.04
 - Python 3.7

**Comment by skywalker023** [comment]
Is there any fix to this?
I'm also having the same problem.

**Comment by pietern** [comment]
Take a look at the [contents of vgg16_from_caffe.pth](https://github.com/Wanger-SJTU/FCN-in-the-wild/blob/master/FCN/pretrain_model/vgg16_from_caffe.pth).

It's an HTML file for some Google Drive error...

**Comment by dheerajmpai** [comment]
The problem still exists. Any solution to the problem? I am facing thins while loading s3fd face detector

**Comment by zxq99799** [comment]
How to solve it? i have the same problem. Thanks.

**Comment by nimpy** [comment]
I just got the same error and realised the problem was me :D That is, the file was trying to load was not a model file but an html file (similarly to OP). So indeed, as @pietern suggested, it's probably the issue with the file mix-up which can be solved by having the correct file :)

**Comment by domef** [comment]
Any update?

**Comment by limetence** [comment]
I got the same error.

**Comment by watreyoung** [comment]
Same error...

**Comment by LiuMY13** [comment]
This is because the file is too big. Trying to use the process:1. git lfs install 2.git clone ....

**Comment by LiuMY13** [comment]
https://huggingface.co/docs/hub/models-downloading

**Comment by MarilynKeller** [comment]
For me the model I was trying to load was corrupted, hence the fail. (The file was 4kb instead of 500Mb) I redownloaded the model and it worked.
