### ISSUE TITLE
Typo in " Using the PyTorch C++ Frontend"

### ISSUE THREAD

**Issue by clemgrt** [pytorch/pytorch#16212]
Good evening,
I think there is a typo in the code 
in the Defining a Module and Registering Parameters[(https://pytorch.org/tutorials/advanced/cpp_frontend.html#defining-a-module-and-registering-parameters)]

at line 7

`#include <torch/torch.h>

struct Net : torch::nn::Module {
  Net(int64_t N, int64_t M) {
    W = register_parameter("W", torch::randn({N, M}));
    b = register_parameter("b", torch::randn(M));
  }
  torch::Tensor forward(torch::Tensor input) {
    return torch::admm(b, input, W);
  }
  torch::Tensor W, b;
};`

Line 9 : admm should be replaced by addmm (?)

**Comment by soumith** [comment]
thanks for reporting, this is fixed now and tutorials are being regenerated.
