### ISSUE TITLE
RuntimeError: std::exception when forward through Conv2d

### ISSUE THREAD

**Issue by themightyoarfish** [pytorch/pytorch#16211]
## 🐛 Bug

I have version `1.1.0a0+fb68d81`. The following code fails with `RuntimeError: std::exception`, which is neither helpful, nor is it clear to me what the problem is.
```
import torch
torch.manual_seed(0)
data = torch.randn([512, 3, 32, 32])   # cifar-shaped batch
module = torch.nn.Conv2d(3, 4, kernel_size=3, padding=0)
module(data)
```
The problem disappears when running the same code with cuda.

Can I somehow use GDB to peek into aten to figure out where exactly this error is coming from?

## Expected behavior

Either a more informative error message, or the code should run. Especially it should not run on the GPU but not on the CPU.

## Environment

PyTorch version: 1.1.0a0+fb68d81
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 8.1.0-5ubuntu1~16.04) 8.1.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 396.37
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.2.1
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.4.2
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] magma-cuda90              2.3.0                         1    pytorch
[conda] mkl                       2019.1                      144
[conda] mkl-include               2018.0.3                      1
[conda] mkl_fft                   1.0.10           py36ha843d7b_0
[conda] mkl_random                1.0.1            py36h629b387_0
[conda] mkldnn                    0.14.0                        0    mingfeima
[conda] torch                     0.5.0a0+a853a74           <pip>
[conda] torch                     0.5.0a0+138d69c           <pip>
[conda] torch                     0.5.0a0+4070005           <pip>
[conda] torch                     0.5.0a0+e767b18           <pip>
[conda] torch                     1.1.0a0+fb68d81           <pip>
[conda] torch                     0.5.0a0+4ad6e53           <pip>
[conda] torch                     0.5.0a0+f607794           <pip>
[conda] torch                     1.0.0a0+4f0434d           <pip>
[conda] torch                     0.5.0a0+a5d7abe           <pip>
[conda] torchvision               0.2.1                     <pip>

**Comment by soumith** [comment]
this issue has been fixed in latest master, or nightly builds, as we switched to MKL-DNN static build.
Your commit should've fixed the issue, but apparently not (and really strange).

Try: `conda uninstall -y mkldnn` and that should fix your issue.
