### ISSUE TITLE
Onnx export error

### ISSUE THREAD

**Issue by bloodymeli** [pytorch/pytorch#16218]
Hi,

## Issue description

I tried to export a model to ONNX as a stepping stone towards using it in TensorRT.
Converting the model directly to ONNX creates some Long() layers, similar to the problem described [here](https://github.com/pytorch/pytorch/issues/14937).
I've realized this is due to the num_batches_tracked field in BatchNorm, which is set to int64.
I tried to convert this field to int32 by:
> x=torch.tensor(0,dtype=torch.int)
> layer_names=list()
>     for name, param_tensor in pose_model.state_dict().items():
>         if param_tensor.dtype == torch.int64:
>             layer_names.append(name)
>     for name in layer_names:
>         rsetattr(pose_model, name, x)

where rsetattr is  recurrsive set_attr. Note that num_batches_tracked value is 0.
When I tried to run this code and convert the model to onnx, I get:

> RuntimeError: block->inputs().size() >= num_initializers ASSERT FAILED at /pytorch/torch/csrc/jit/export.cpp:289, please report a bug to PyTorch. (EncodeBlock at /pytorch/torch/csrc/jit/export.cpp:289)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fc49ab42fe1 in /home/eli/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fc49ab42dfa in /home/eli/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x550231 (0x7fc47ae76231 in /home/eli/.local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #3: <unknown function> + 0x550988 (0x7fc47ae76988 in /home/eli/.local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #4: torch::jit::export_onnx(std::shared_ptr<torch::jit::Graph> const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, long, bool, torch::onnx::OperatorExportTypes) + 0x37 (0x7fc47ae77247 in /home/eli/.local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x382b24 (0x7fc48863fb24 in /home/eli/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x116fac (0x7fc4883d3fac in /home/eli/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: _PyCFunction_FastCallDict + 0x35c (0x565d5c in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #8: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x503073]
frame #9: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #10: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x504c28]
frame #11: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502540]
frame #12: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #13: _PyEval_EvalFrameDefault + 0x1231 (0x507641 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #14: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x504c28]
frame #15: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x58650d]
frame #16: PyObject_Call + 0x3e (0x59ebbe in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x1807 (0x507c17 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #18: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x504c28]
frame #19: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502540]
frame #20: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #21: _PyEval_EvalFrameDefault + 0x1231 (0x507641 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #22: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x504c28]
frame #23: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x511eca]
frame #24: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502d6f]
frame #25: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #26: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x504c28]
frame #27: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502540]
frame #28: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #29: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #30: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x504c28]
frame #31: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502540]
frame #32: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #33: _PyEval_EvalFrameDefault + 0x1231 (0x507641 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #34: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x504c28]
frame #35: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x511eca]
frame #36: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502d6f]
frame #37: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #38: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502209]
frame #39: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #40: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #41: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x504c28]
frame #42: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502540]
frame #43: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #44: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #45: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502209]
frame #46: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #47: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #48: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502209]
frame #49: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #50: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #51: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x504c28]
frame #52: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502540]
frame #53: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #54: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #55: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502209]
frame #56: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #57: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #58: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502209]
frame #59: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x502f3d]
frame #60: _PyEval_EvalFrameDefault + 0x449 (0x506859 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #61: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x504c28]
frame #62: PyEval_EvalCode + 0x23 (0x506393 in /media/eli/Windows/code/AlphaPose/venv/bin/python)
frame #63: /media/eli/Windows/code/AlphaPose/venv/bin/python() [0x634d52]

Any solutions? Workaround?
I'm going to use this model only in eval mode, so I don't need the num_batches_tracked at all.

## System Info
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070 with Max-Q Design
Nvidia driver version: 410.78
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.4.1
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so.7.4.1
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.15.4)
[pip3] torch (1.0.0)
[pip3] torchfile (0.1.0)
[pip3] torchsample (0.1.3, /media/eli/Windows/code/AlphaPose/src/torchsample)
[pip3] torchvision (0.2.1)
[conda] Could not collect

cc @BowenBao @neginraoof

**Comment by ajaysg** [comment]
can u provide info of how u converted the model to onnx
