### ISSUE TITLE
Installing pytorch 0.4.1 without cuda.

### ISSUE THREAD

**Issue by jack17529** [pytorch/pytorch#16234]
## 📚 Documentation

I tried this command as is listed on the site - "conda install pytorch=0.4.1 -c pytorch"
But it is telling me to install -
"The following NEW packages will be INSTALLED:

    pytorch: 0.4.1-py37_cuda90_cudnn7he774522_1 pytorch"

which I think is with cuda, can someone please tell me how can I install Pytorch 0.4.1 without cuda?
I am working on Windows 10 with conda.

Thank You

**Comment by soumith** [comment]
the same package works for CPU-only settings. Just install it and forget CUDA is there :)

**Comment by jack17529** [comment]
@soumith , I am getting this error, which I don't know how to solve, please help.

`Loading snapshot.
Loading data.
THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "code/test_on_video_dlib.py", line 72, in <module>
    model.cuda()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 185, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 191, in _apply
    param.data = fn(param.data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at ..\aten\src\THC\THCGeneral.cpp:74`

**Comment by soumith** [comment]
> RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version

You are running a program where CUDA is trying to be used.
Check your code that it doesn't have `.cuda()` calls, which will obviously try to use CUDA and fail.

**Comment by soumith** [comment]
the error actually points to where in your code it's a problem. read the error message.

**Comment by jack17529** [comment]
@soumith , thanks for the response. Please ensure one last thing for me.
I am trying to run this repository - https://github.com/natanielruiz/deep-head-pose
But I can't use it because I am an AMD card user and the repository uses CUDA which only works for NVIDIA gpu users. I have to convert the code to OpenCL to use it, right?

Is there any other way to run it?

**Comment by ezyang** [comment]
Hypothetically, you may be able to use HIPify to transpile the CUDA code into HIP code. This is a very advanced technique and unfortunately, you'll have to figure this out on your own.

**Comment by PawanKuma** [comment]
Importing torch with cuda has issues. Trying to get around with that, can anyone help
