### ISSUE TITLE
C++/CUDA extension error: Expected tensor's dynamic type to be Variable, not Tensor

### ISSUE THREAD

**Issue by jerrybai1995** [pytorch/pytorch#16238]
Hi! While I'm writing CUDA extension for a module, I received the following error when calling the `forward` function of my module: "Expected tensor's dynamic type to be Variable, not Tensor".

After bug tracing, I found that the problem is with the following line:
```
at::Tensor out = at::zeros({batch_size, dim1, dim2, dim3}, torch::dtype(torch::kFloat32));
```

If I replace the line above with:
```
at::Tensor out = at::zeros_like(x)
```
then the module will run fine. However, the dimensions of x are not what I want (which needs to be dim1 x dim2 x dim3, and I have to use `at::zeros`.

I'm not sure what's the cause of this problem (I've read https://github.com/pytorch/pytorch/issues/6103; but it seems the interface has changed a lot in the past 10 months). Since `Variable` is no longer used in PyTorch, what can I do to fix this issue? 

Thanks!

**Comment by vishwakftw** [comment]
You could pass `x.options()`, instead of passing the type alone.

**Comment by SsnL** [comment]
I think you should use `torch::zeros` not `at::zeros`.

**Comment by soumith** [comment]
the fix is ssnl's comment, use `torch::zeros` which are "variable"

**Comment by raminrasoulinezhad** [comment]
It solved my problem a well

**Comment by shaik0440** [comment]
Hi,
I'm trying to mimic the memory allocation done in pytorch convolution implementation in C++/CUDA extension.

auto check_ = c10::make_intrusive<at::TensorImpl, at::UndefinedTensorImpl>(c10::CUDATensorId(), caffe2::TypeMeta::Make<float>(), at::globalContext().getTHCState()->cudaDeviceAllocator, false).release();
at::Tensor check = at::Tensor(c10::intrusive_ptr<at::TensorImpl, at::UndefinedTensorImpl>::reclaim(check_));

and i am resizing it to required size later. I'm able to use the memory allocated in my custom Cuda implementation, but while returning the variable to python side it showing the error "Expected tensor's dynamic type to be Variable, not Tensor". 

@soumith, @SsnL 

Thanks in advance
