### ISSUE TITLE
incompatibility between Pytorch 0.1.12 and cuda 8.0.61/cudnn 5.1.10 ?

### ISSUE THREAD

**Issue by gongbudaizhe** [pytorch/pytorch#1623]
Hi,

I have two linux servers. My code works in one machine but not the other. In the one that it doesn't work, the error message is: `RuntimeError: CUDNN_STATUS_BAD_PARAM` occured during batch normalization( convolution is fine). Also, the same code works in CPU but not in GPU. 

I guess this problem is mainly related to GPU libraries like cuda or cudnn. *The one that doesn't work has the following configurations*:
- Nvidia driver 375.26
- cuda 8.0.61
- cudnn 5.1.10

*While in the one it does work*, I have the following configurations:
- Nvidia driver 367.48
- cuda 8.0.44
- cudnn 5.1.5

TensorFlow can run in the above environment flawless though. So I am wondering if this is caused by the incompatibility between PyTorch 0.1.12 and cuda 8.0.61/cudnn 5.1.10 ?

**Comment by soumith** [comment]
1. if you use the pytorch binaries, we ship cudnn6 in them, use it it's great.
2. cudnn 5.1.10 maybe has a bug. cc: @ngimel . @gongbudaizhe do you have a small test case to reproduce this?
3. TensorFlow does not use CuDNN batchnorm by default, so maybe that's why?

**Comment by ngimel** [comment]
Small test case would help, thanks.

**Comment by gongbudaizhe** [comment]
After some experimentation, I have pin pointed where exactly the error comes from. It seems batch norm in cudnn 5.1.10 doesn't support eps as small as 1e-6. 

A small test case would be:
```python
import torch
from torch import nn
from torch.autograd import Variable

class TestModel(nn.Module):
  def __init__(self):
    super(TestModel, self).__init__()
    self.bn = nn.BatchNorm2d(96, eps=1e-6) # Bug here
    # self.bn = nn.BatchNorm2d(96, eps=1e-5) # No Bug version

  def forward(self, x):
    out = self.bn(x)
    return out

if __name__ == '__main__':
  feat = Variable(torch.rand((8, 96, 59, 59))).cuda()
  model = TestModel().cuda()
  out = model(feat)
```

**Comment by ngimel** [comment]
Yes, cudnn.h for 5.1.10 defines CUDNN_BN_EPSILON to be 1e-5 (minimum allowable value). I can't check header for 5.1.5. Even with 1e-5 epsilon for many input data distributions the results become pretty unstable. Is there a case for this restriction to be lifted, does using very small epsilon provide benefits?

**Comment by gongbudaizhe** [comment]
I see. Not sure if small epsilon is necessary. I am using 1e-6 just to replicate others' configurations. 

Should PyTorch provide more informative error message about this restriction?

**Comment by ngimel** [comment]
Ideally, CUDNN should provide more informative error messages (pytorch can not know why cudnn is returning an error code in each particular case) , but that's a long standing discussion.

**Comment by gongbudaizhe** [comment]
It just hits on me. As mentioned by @soumith , TensorFlow does not use CuDNN batchnorm by default. So is this possible in Pytorch, to not use default CuDNN batchnorm?

**Comment by gongbudaizhe** [comment]
Never mind. I found the switch in `torch._C._functions.BatchNorm`.
