### ISSUE TITLE
docker image fails to start after successful build

### ISSUE THREAD

**Issue by MiladAlshomary** [pytorch/pytorch#16256]
## 🐛 Bug

After building the docker image successfully. Starting it fails throwing the following error:

`Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=12024 /var/lib/docker/aufs/mnt/d2908c9e766c150ae3685c2854e349e58fd5ffa2287095449bc34cfa41307ccc]\\\\nnvidia-container-cli: requirement error: invalid expression\\\\n\\\"\"": unknown
`
## To Reproduce

1. git pull the repo.
2. build using the command: ` docker build -t pytorch -f docker/pytorch/Dockerfile .`
3. Create an image:  `nvidia-docker run -e LANG=C.UTF-8 --name ulmfit-pytorch -e LC_ALL=C.UTF-8 -it -v /path/to/some/folder/:/workspace/code -v /path/to/data:/workspace/data --net=host pytorch` this throws error

## Environment

[environment collection script]
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: N/A
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080
GPU 2: GeForce GTX 1080
GPU 3: GeForce GTX 1080
GPU 4: GeForce GTX 1080
GPU 5: GeForce GTX 1080
GPU 6: GeForce GTX 1080
GPU 7: GeForce GTX 1080

Nvidia driver version: 396.44
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn_static.a
/usr/local/cuda-8.0-cudnn6/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0-cudnn6/lib64/libcudnn_static.a
/usr/local/cuda-8.0/lib64/libcudnn.so
/usr/local/cuda-8.0/lib64/libcudnn.so.5
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.5
/usr/local/cuda-8.0/lib64/libcudnn.so.6
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

Thanks for help!

**Comment by ngimel** [comment]
Dockerfile is now updated to use cuda 10, and requires corresponding driver. Your host has an insufficient driver version.

**Comment by soumith** [comment]
closed via ngimel's comment.
