### ISSUE TITLE
Unexpected result with tensor::Tensor::eq_ in C++

### ISSUE THREAD

**Issue by dfalbel** [pytorch/pytorch#16264]
## 🐛 Bug

In place op `eq_` in c++ has unexpected behavior when comparing to zeros. This behavior is also different than python version.

## To Reproduce

Here's a small c++ program compiled with latest c++ distribution from pytorch home page.

```
#include <torch/torch.h>
#include <iostream>

int main() {
  auto x = torch::arange(1, 4, torch::kInt);
  std::cout << "x: " << x << std::endl;
  auto y = torch::zeros_like(x);
  std::cout << "y: " << y << std::endl;
  x.eq_(y);
  std::cout << x << std::endl;
}
```

This returns:

```
dani@dfalbel-System-Product-Name:~/torch2/example-app/build$ ./example-app
x:  1
 2
 3
[ Variable[CPUIntType]{3} ]
y:  0
 0
 0
[ Variable[CPUIntType]{3} ]
 1
 1
 1
[ Variable[CPUIntType]{3} ]
```

## Expected behavior

I would expect a vector of zeros like in python:

```
>>> x = torch.tensor([1,2,3], dtype = torch.int32)
>>> y = torch.zeros_like(x)
>>> x
tensor([1, 2, 3], dtype=torch.int32)
>>> y
tensor([0, 0, 0], dtype=torch.int32)
>>> x.eq_(y)
tensor([0, 0, 0], dtype=torch.int32)
>>> x
tensor([0, 0, 0], dtype=torch.int32)
```

## Environment

This happens on MacOs and Linux testes with latest file from pytorch website.

**Comment by vishwakftw** [comment]
This has been fixed in https://github.com/pytorch/pytorch/pull/15479, and is available in the nightly version of LibTorch.

Below is the output I get with the nightly version:
```
x:  1
 2
 3
[ Variable[CPUIntType]{3} ]
y:  0
 0
 0
[ Variable[CPUIntType]{3} ]
 0
 0
 0
[ Variable[CPUIntType]{3} ]
```
