### ISSUE TITLE
max() index should not be tensor?

### ISSUE THREAD

**Issue by makeyourownneuralnetwork** [pytorch/pytorch#1627]
The result of calling torch.max() or tensor.max() gives an index that is a Tensor, wrapped in a Variable.

To make use of the actual index, we need to extract via numpy and index into the resultant bumpy array.

When we have a simple 1-dimensional tensor (vector) this leads to too much code:

```
maxval, idx = outputs.max(1)

if (idx.data.numpy()[0][0] == correct_label):
    ...
```

I suspect this will be a common user-story .. .could it be made easier?
Most people don't need the index to be a tensor, in my humble opinion.

You can't actually do the `==` comparison with the `idx` or `int(idx)` and this leads to bugs because no error is raised, it quietly continues with a true bool ...

**Comment by soumith** [comment]
1. you dont need to use numpy: `if (idx.data[0][0] == correct_label)`
2. We are planning to introduce a scalar type (tracked in a different issue), and when we do that, if a single index is returned it probs will be a scalar. https://github.com/pytorch/pytorch/issues/1433

**Comment by soumith** [comment]
we cannot return scalars out of autograd (yet), because we need outputs to be Variables
