### ISSUE TITLE
Inconsistency in inception model

### ISSUE THREAD

**Issue by ShahriarSS** [pytorch/pytorch#16277]
## 🐛 Bug

Hi
I was going through the torchvision code to implement c++ API and I noticed an Inconsistency.

In line 298 of inception.py stddev of a class of type BasicConv2d is set to 0.01:

``` python
self.conv1.stddev = 0.01
```

But in line 60 it checks if it's conv2d or linear which a BasicConv2d is none:

``` python
if isinstance(m, nn.Conv2d) or isinstance(m, nn.Linear):
   import scipy.stats as stats
   stddev = m.stddev if hasattr(m, 'stddev') else 0.1
```

I put this code inside the previous if statement:

``` python
if hasattr(m, 'stddev'):
    print(m)
```

and it only printed:

```
Linear(in_features=768, out_features=1000, bias=True)
```

so convs inside conv1 BasicConv2d of InceptionAux get initialized with stddev=0.1

is this an error or is it intentional?

**Comment by soumith** [comment]
hi, please report / ask in https://github.com/pytorch/vision
