### ISSUE TITLE
spurious tensor broadcasting, and inconsistent behavior with numpy

### ISSUE THREAD

**Issue by zym1010** [pytorch/pytorch#1629]
although officially PyTorch doesn't support broadcasting, seems that still it can compare arrays of different shapes, and it gave different behaviors as numpy. Is this expected?

~~~
In [23]: a = np.arange(5).astype(np.float32)

In [24]: b= a.copy().reshape(5,1)

In [25]: a_torch=torch.Tensor(a)

In [26]: b_torch=torch.Tensor(b)

In [27]: a==b
Out[27]:
array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]], dtype=bool)

In [28]: a_torch==b_torch
Out[28]:

 1
 1
 1
 1
 1
[torch.ByteTensor of size 5]
~~~

more weird problems.
~~~
In [45]: a_torch==b_torch.t()
Out[45]:

 1
 1
 1
 1
 1
[torch.ByteTensor of size 5]

In [46]: b_torch.t()==a_torch
Out[46]:

 1  1  1  1  1
[torch.ByteTensor of size 1x5]
~~~

**Comment by fmassa** [comment]
This is expected at the moment, and is documented in the docs, check the **Note** in
http://pytorch.org/docs/torch.html?highlight=add#torch.add for example. But this behavior will change with the upcoming broadcast feature in https://github.com/pytorch/pytorch/pull/1563

**Comment by fmassa** [comment]
Almost, if by flattening you mean flattening the contiguous version of the tensor.
Currently the only requirement for point-wise operations is that the number of elements match, and the shape will be the one of the first input.

**Comment by zym1010** [comment]
@fmassa so you mean I don't have to worry about underlying storage, strides, etc.?

**Comment by apaszke** [comment]
No, right now it works for all kind of tensors (including non-contiguous). It's going to be changed soon, so I'm closing this.
