### ISSUE TITLE
Input and output tensors to `torch._C.Node`

### ISSUE THREAD

**Issue by rahul99** [pytorch/pytorch#16306]
## 📚 Documentation

How to get the input and output tensors of the Node of type `torch._C.Node`?

Node is extracted from the graph using `jit` API as follows:

```
model = torchvision.models.Resnet18()
trace, out = torch.jit.get_trace_graph(model, args=(input,))
torch.onnx._optimize_trace(trace, torch.onnx.OperatorExportTypes.ONNX)
graph = trace.graph()
for node in graph.nodes():
    print(node.attributeNames())
    # how to get input and output tensors to this node?
```

**Comment by apaszke** [comment]
You can use `.inputs()` and `.outputs()` to get the input and output values, but there are no tensors since you're inspecting a representation of a program that's not running yet. Those APIs are internal, so we won't be writing documentation for them just yet.
