### ISSUE TITLE
Please remove pytorch from pypi

### ISSUE THREAD

**Issue by bw-matthew** [pytorch/pytorch#16316]
## 🐛 Bug

I tried to install pytorch using pipenv (see https://github.com/pypa/pipenv/issues/3476).

You have put in a fancy thing which is supposed to open the browser. It did not. Instead there was no output and I believed that the installation was broken.

## To Reproduce

1. pipenv install pytorch

You will see something like this:

```
➜ pipenv install pytorch
Installing pytorch…
⠇ Installing...
```

## Expected behavior

If you don't want people installing it from pypi then don't put it there.
Don't break dependency management tools.

## Environment

Collecting environment information...
PyTorch version: N/A  
Is debug build: N/A                    
CUDA used to build PyTorch: N/A                
                                        
OS: Ubuntu 18.04 LTS            
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.5.1   
                       
Python version: 3.7      
Is CUDA available: N/A                  
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

## Additional context

I can understand your desire to be helpful. Trying to make a non interactive activity (dependency management) into an interactive activity is inevitably going to result in situations like this.

Please just make the installation fail promptly and noisily.

**Comment by soumith** [comment]
pipenv install torch

thats the correct command.
the package pytorch was put as a placeholder because several people confused as to why pip install pytorch was failing. we’ll try to improve the message.

**Comment by bw-matthew** [comment]
Ah right thank you.

**Comment by mruberry** [comment]
Closing due to age and apparent resolution. If you're still experiencing an issue please file a new issue, @bw-matthew
