### ISSUE TITLE
Eliminate "enrich declarations with additional information" in gen_autograd.py

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#16321]
cc @cpuhrsch @gchanan 

I was attempting to reuse some code that was ingesting Declarations.yaml, and it was complaining that `simple_type` was not set. Why wasn't it set? Well, that's because the script I was running had loaded the YAML file from scratch, rather than use `load_aten_declarations`, which adds in a bunch of extra information to Declarations.yaml after loading it:

```
    # enrich declarations with additional information
    selected_declarations = []
    for declaration in declarations:
        if declaration.get('deprecated'):
            continue

        for arg in declaration['arguments']:
            arg['simple_type'] = get_simple_type(arg)
        for ret in declaration['returns']:
            ret['simple_type'] = get_simple_type(ret)
```

We... probably shouldn't do this? This is a code smell suggesting downstream clients might need this information too, but aren't getting it easily.

**Comment by mruberry** [comment]
@ezyang is this still relevant?
