### ISSUE TITLE
Error during import torch, NameError: name '_C' is not defined

### ISSUE THREAD

**Issue by dusty-nv** [pytorch/pytorch#1633]
After building from source on ubuntu 16.04 x86_64 and python 2.7.12, when I try to `import torch` I get the following error:

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dusty/workspace/jetson-reinforcement/build/pytorch/torch/__init__.py", line 55, in <module>
    __all__ += [name for name in dir(_C)
NameError: name '_C' is not defined
```

It seems to be surrounding this code in `torch/__init__.py`:

```
from torch._C import *

__all__ += [name for name in dir(_C)
            if name[0] != '_' and
            not name.endswith('Base')]
```

Any ideas of a workaround?

**Comment by soumith** [comment]
you probably need to change directory before calling `import torch`.

```
cd test
python
>>> import torch
```

**Comment by dusty-nv** [comment]
@soumith thanks, checks out.  After running it once from `test` dir, now I can `import torch` regardless of cwd.  Closing issue #1633

**Comment by isalirezag** [comment]
Why that is the reason?
Why changing the directory solved the question?

**Comment by fmassa** [comment]
@isalirezag it's because when you are in pytorch folder, `import torch` picks up the `torch` folder for the import, and not the installed `torch` package.

**Comment by SundusJ** [comment]
I am running my code in jupyter notebook and getting same error.
Can you tell me how to resolve this issue?

**Comment by nwpuhq** [comment]
thanks,your reply perfectly solved my problem same as the up.

**Comment by nwpuhq** [comment]
> I am running my code in jupyter notebook and getting same error.
> Can you tell me how to resolve this issue?

  when i'm running in spyder with the same error.i go to 'cmd' and input'cd test','python','import torch'.then close the spyder and reopen it running more one time,and it works.

**Comment by zameel123** [comment]
I'm having the same issue on windows 10 and python 3.7.2.i had change the directory but it doesn't work.is there any other solution?

**Comment by dileepmatha** [comment]
Hey , I am getting the same error even after installing cython. in jupyter notebook

**Comment by XieZixiUSTC** [comment]
yeah, i am getting the same problem too,may be is the problem of version or the path

**Comment by secdevelop** [comment]
same here i tried to solve the problem in jupyter
Requirement already satisfied: Cython in c:\users\hamza\anaconda3\lib\site-packages (0.29.13)

NameError                                 Traceback (most recent call last)
<ipython-input-10-eb42ca6e4af3> in <module>
----> 1 import torch

~\Anaconda3\lib\site-packages\torch\__init__.py in <module>
     81 from torch._C import *
     82 
---> 83 __all__ += [name for name in dir(_C)
     84             if name[0] != '_' and
     85             not name.endswith('Base')]

NameError: name '_C' is not defined

**Comment by PrashantDandriyal** [comment]
I guess running it on terminal works after uninstalling and installing numpy as mentioned here
https://github.com/tensorflow/tensorflow/issues/25942#issuecomment-563413326

**Comment by yyhhlancelot** [comment]
If you use Spyder, try to delete the project and recon it again. It occured when I  rebooted my computer last time because of Spyder's frozing.

**Comment by paulsturdza** [comment]
I also ran into this issue in google colab. which is basically also a jupyter notebook. for me factory resetting the runtime and then rerunning the import without any changes worked.

**Comment by zeyger** [comment]
I just restarted google colab runtime and it works now lol

**Comment by anyongjin** [comment]
in my case, it's due to a circular import
(name of my python conflicts with other modules)

**Comment by ajason08** [comment]
In my case it was due to intensive uses of CPUs (Im using a cluster), probably that's why resetting Colab works.

**Comment by TheIceHole** [comment]
in my case ,I add the path of Anaconda to the system environment variable,it works to me.(Pycharm,WIndows)

**Comment by jarunm** [comment]
Restarting the kernel worked for Jupyter Notebooks.

**Comment by wolvido** [comment]
Navigate to: \Users\user\AppData\Roaming\Python 
then delete all uninstalled python files

**Comment by SankhaJay** [comment]
Colab TPU instance worked fine after restarting the runtime

**Comment by Akshatha-Jagadish** [comment]
This happened to me due to anaconda update which added prefix 100 to all the packages:
https://github.com/ContinuumIO/anaconda-issues/issues/12513

**Comment by wyt1900** [comment]
i meet same question in my code, even install Cython.
i solution this problem in this way, pip install numpy==1.19.2

**Comment by clarkzinzow** [comment]
If anyone is curious, this problem is also caused by concurrently importing pytorch, e.g. across multiple threads or before and after handling an interrupt signal (such as CTRL + C in a Collab/Jupyter notebook), since it appears that the pytorch import is not reentrant.

In either case, starting a new Python process (e.g. resetting the Collab runtime, restarting a Jupyter Notebook kernel, etc.) will fix it.

**Comment by Sam-Smith-01** [comment]
Maybe it is a environment problem. I set my environment and the problem solved.

**Comment by lwmcal** [comment]
@clarkzinzow I run into the same problem as op. I followed your advice to close all other tools such as the Qt Console, which I test import torch before, and also did the following to reinstall some dependencies. Restart everything, and now it works now for both my IDLE Shell and Qt Console. 

pip uninstall matplotlib
pip uninstall pillow
pip uninstall numpy
pip install matplotlib
pip install pillow
pip install numpy

**Comment by bianca-li-bupt** [comment]
@lwmcal  It works for me. Thank you!

**Comment by haosong001** [comment]
> Resetting the runtime actually worked for me after i tried everything

me too! just restart will do!

**Comment by picaso26** [comment]
Im working in google colab ,it isnt working for me

**Comment by valmetisrinivas** [comment]
> Hey , I am getting the same error even after installing cython. in jupyter notebook

Try restart the kernel and rerun your code.

**Comment by MadhumithaKolkar** [comment]
For me - pip install Cython , and then restarting jupyter notebook worked.
