### ISSUE TITLE
Variable.clone() does not clone to the same device

### ISSUE THREAD

**Issue by el3ment** [pytorch/pytorch#1634]
We have a custom Function that passes input and output memory to a cuda kernel. In order for the backward pass to work we need the output memory (which is allocated in the function) to be on the same device as the input. Calling input1.clone() put it on the last device.

**Comment by soumith** [comment]
this is expected. Read http://pytorch.org/docs/notes/cuda.html

What you want to do is:

```
with torch.cuda.device_of(input1.data):
   input2 = input1.clone()
```

**Comment by apaszke** [comment]
It's not expected. `clone()` should operate within a single device

**Comment by soumith** [comment]
wouldn't `clone()` be creating Tensors on the current device?
If so I always misunderstood it :)
my bad.

**Comment by apaszke** [comment]
I think it never did. I just tried it with a tensor and it put the clone on the same dev (which is what I expected).

**Comment by apaszke** [comment]
@el3ment can you please get us a small script that reproduces it?

**Comment by el3ment** [comment]
You are correct. Sorry about that. My original issue was embeded in a Function but the issue is definitely not with what I labeled this issue as.

That said, this example code does actually raise the opposite problem that using with device() is ignored by clone(). I'm not sure if this is expected or not.

 
```
import torch

A = torch.randn(5)
A = A.cuda()
print(A.get_device())

with torch.cuda.device(1):
	A2 = torch.randn(5)
	A2 = A2.cuda()
	print(A2.get_device())
	
D = A.clone()
E = A2.clone()
print(D.get_device(), E.get_device())
```
outputs:
```
('should be 0', 0)
('should be 1', 1)
('should be (0, 1)', 0, 1)
('should be (0, 0):', 0, 1)
```

**Comment by apaszke** [comment]
It prints
```
0
1
0 1
```
for me and it makes sense. Not sure where the `should be` messages are coming from. Are you sure you pasted the correct script?

**Comment by el3ment** [comment]
Bah, sorry

```
import torch

A = torch.randn(5)
A = A.cuda()
print('should be 0', A.get_device())

with torch.cuda.device(1):
	A2 = torch.randn(5)
	A2 = A2.cuda()
	print('should be 1', A2.get_device())

D = A.clone()
E = A2.clone()
print('should be (0, 1)', D.get_device(), E.get_device())

with torch.cuda.device(0):
	H = A.clone()
	J = A2.clone()
	print('should be (0, 0):', H.get_device(), J.get_device())
```

**Comment by apaszke** [comment]
It looks good. Result of `clone()` is always on the same device as the cloned tensor and this is exactly what's happening in here. The `with torch.cuda.device(0):` is a no-op in this context.
