### ISSUE TITLE
cannot set num_threads in 1.0.0

### ISSUE THREAD

**Issue by guolinke** [pytorch/pytorch#16358]
## To Reproduce
```
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.set_num_threads(8)
>>> torch.get_num_threads()
1
>>> torch.__version__
'1.0.0'
>>>
```
Also try ```OMP_NUM_THREADS=8 MKL_NUM_THREADS=8```, cannot work as well.

**Comment by yf225** [comment]
@guolinke This bug is fixed on master. Could you try installing the nightly builds (`pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`) ?
