### ISSUE TITLE
Add an argument 'beta' in smooth L1 loss?

### ISSUE THREAD

**Issue by wangg12** [pytorch/pytorch#16357]
Now the default beta is 1 in smooth l1 loss, it would be better if we could change the value.

**Comment by yf225** [comment]
@fmassa

**Comment by fmassa** [comment]
This sounds good to me.

The beta argument in `smooth_l1_loss` is the the argument which controls where the frontier between the L1 and the L2 losses are switched.
The (python) implementation (take from [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/layers/smooth_l1_loss.py)) is as follows:
```python
def smooth_l1_loss(input, target, beta=1. / 9, size_average=True):
    """
    very similar to the smooth_l1_loss from pytorch, but with
    the extra beta parameter
    """
    n = torch.abs(input - target)
    cond = n < beta
    loss = torch.where(cond, 0.5 * n ** 2 / beta, n - 0.5 * beta)
    if size_average:
        return loss.mean()
    return loss.sum()
```
This can be preferably solved as follows:
1 - Modify the CPU implementation for the forward https://github.com/pytorch/pytorch/blob/17e3ab957aa6d493582572eb4a2b9c6712797b8a/aten/src/THNN/generic/SmoothL1Criterion.c#L18 to take beta into account
2 - Modify the backwards for the CPU https://github.com/pytorch/pytorch/blob/17e3ab957aa6d493582572eb4a2b9c6712797b8a/aten/src/THNN/generic/SmoothL1Criterion.c#L48-L78
3 - Modify the GPU implementation for and backward similarly in https://github.com/pytorch/pytorch/blob/master/aten/src/THCUNN/SmoothL1Criterion.cu
4 - Adapt the GPU code to dispatch to the right function signature https://github.com/pytorch/pytorch/blob/master/aten/src/THCUNN/generic/SmoothL1Criterion.cu#L21
5 - Change the python dispatch for targets which requires gradient to also take the beta into account https://github.com/pytorch/pytorch/blob/17e3ab957aa6d493582572eb4a2b9c6712797b8a/torch/nn/functional.py#L2117
6 - Finish pushing the beta in https://github.com/pytorch/pytorch/blob/17e3ab957aa6d493582572eb4a2b9c6712797b8a/torch/nn/functional.py#L2129-L2136

**Comment by fmassa** [comment]
Yes, definitely!

**Comment by TrigonaMinima** [comment]
@wangg12 are you working on this?

**Comment by dai-dao** [comment]
Hi @fmassa , i'm working on this issue for practice, I ran into a problem that perhaps you would know

In aten/src/THNN/generic/SmoothL1Criterion.c, I make the following change. Same with SmoothL1Criterion_updateGradInput

```
void THNN_(SmoothL1Criterion_updateOutput)(
          THNNState *state,
          THTensor *input,
          THTensor *target,
          THTensor *output,
          accreal beta_,
          int64_t reduction)
{
  THNN_CHECK_SHAPE(input, target);
  scalar_t beta = TH_CONVERT_ACCREAL_TO_REAL(beta_);

  if (reduction == Reduction::None) {
    THTensor_(resizeAs)(output, input);
    TH_TENSOR_APPLY3(scalar_t, input, scalar_t, target, scalar_t, output,
      scalar_t z = fabs(*input_data - *target_data);
      *output_data = z < beta ? 0.5 * z * z : z - 0.5;
    );
    return;
  }

  THTensor_(resize0d)(output);

  scalar_t sum = 0;
  TH_TENSOR_APPLY2(scalar_t, input, scalar_t, target,
    scalar_t z = fabs(*input_data - *target_data);
    sum += z < beta ? 0.5*z*z : z - 0.5;
  );

  if (reduction == Reduction::Mean)
    sum /= THTensor_(nElement)(input);

  THTensor_(set0d)(output, sum);
}
```

and I changed the aten/src/THNN/generic/THNN.h to include the beta argument:

```
TH_API void THNN_(SmoothL1Criterion_updateOutput)(
          THNNState *state,
          THTensor *input,
          THTensor *target,
          THTensor *output,
          accreal beta,
          int64_t reduction);

TH_API void THNN_(SmoothL1Criterion_updateGradInput)(
          THNNState *state,
          THTensor *input,
          THTensor *target,
          THTensor *gradOutput,
          THTensor *gradInput,
          accreal beta,
          int64_t reduction);
```

I'm rebuilding with python setup.py rebuild_libtorch and I get the error:
```
RuntimeError: SmoothL1Criterion_updateOutput: can't find binding for 'beta'
```

Perhaps I'm missing a step somewhere? I simply follow how SoftPlus implementation defines its beta argument. Please advice 👍 

Cheers

**Comment by dai-dao** [comment]
Hi @fmassa , i'm working on this issue for practice, I ran into a problem that perhaps you would know
In ```aten/src/THNN/generic/SmoothL1Criterion.c```, I make the following change. Same with ```SmoothL1Criterion_updateGradInput```
```
void THNN_(SmoothL1Criterion_updateOutput)(
          THNNState *state,
          THTensor *input,
          THTensor *target,
          THTensor *output,
          accreal beta_,
          int64_t reduction)
{
  THNN_CHECK_SHAPE(input, target);
  scalar_t beta = TH_CONVERT_ACCREAL_TO_REAL(beta_);
  if (reduction == Reduction::None) {
    THTensor_(resizeAs)(output, input);
    TH_TENSOR_APPLY3(scalar_t, input, scalar_t, target, scalar_t, output,
      scalar_t z = fabs(*input_data - *target_data);
      *output_data = z < beta ? 0.5 * z * z : z - 0.5;
    );
    return;
  }
  THTensor_(resize0d)(output);
  scalar_t sum = 0;
  TH_TENSOR_APPLY2(scalar_t, input, scalar_t, target,
    scalar_t z = fabs(*input_data - *target_data);
    sum += z < beta ? 0.5*z*z : z - 0.5;
  );
  if (reduction == Reduction::Mean)
    sum /= THTensor_(nElement)(input);
  THTensor_(set0d)(output, sum);
}
```
and I changed the ```aten/src/THNN/generic/THNN.h``` to include the beta argument:
```
TH_API void THNN_(SmoothL1Criterion_updateOutput)(
          THNNState *state,
          THTensor *input,
          THTensor *target,
          THTensor *output,
          accreal beta,
          int64_t reduction);
TH_API void THNN_(SmoothL1Criterion_updateGradInput)(
          THNNState *state,
          THTensor *input,
          THTensor *target,
          THTensor *gradOutput,
          THTensor *gradInput,
          accreal beta,
          int64_t reduction);
```
I'm rebuilding with ```python setup.py rebuild_libtorch``` and I get the error:
```
RuntimeError: SmoothL1Criterion_updateOutput: can't find binding for 'beta'
```
Perhaps I'm missing a step somewhere? I simply follow how SoftPlus implementation defines its beta argument. Please advice 👍 
Cheers

**Comment by fmassa** [comment]
Hi @dai-dao ,

Sorry, I think I forgot to mention a few things. (lot's of code that is autogenerated!)

I think you also need to update the signature in https://github.com/pytorch/pytorch/blob/f83556bb7b08aded1c729678c4e75414ba89330a/aten/src/ATen/nn.yaml#L47-L51
in 
https://github.com/pytorch/pytorch/blob/4404762d7dd955383acee92e6f06b48144a0742e/aten/src/ATen/native/LegacyNNDefinitions.cpp#L148-L163
and also adjust the formula for the double backpropagation in
https://github.com/pytorch/pytorch/blob/cca247635c6edb323176eeac7a18d3e9ab71c558/torch/nn/_functions/thnn/auto_double_backwards.py#L206-L221
and then in
https://github.com/pytorch/pytorch/blob/4404762d7dd955383acee92e6f06b48144a0742e/tools/autograd/derivatives.yaml#L957-L958
and
https://github.com/pytorch/pytorch/blob/4404762d7dd955383acee92e6f06b48144a0742e/tools/autograd/derivatives.yaml#L1264-L1266
and finally in 
https://github.com/pytorch/pytorch/blob/ac00e85e36c236f141d0621bfbbbbe8c9ffeefd1/aten/src/ATen/native/native_functions.yaml#L3975-L3987

Phew, there are a number of small modifications that need to be propagated! But they should be fairly easy, the hardest one would be the double backwards, let me know if you have questions!

**Comment by dai-dao** [comment]
Thanks, I got it to build now 👍 I'm testing and should make a PR soon. Cheers

**Comment by whoiscris** [comment]
@dai-dao is this still open ?

**Comment by gingerboredman** [comment]
@fmassa @dai-dao is this still open/unassigned? if it is id like to take a shot at it.

**Comment by mrshenli** [comment]
Looks like there is no progress on this one for a while. I self-assigned to reserve for bootcamp. Please let me know if anyone already has a PR for this.

**Comment by mruberry** [comment]
Smooth l1 loss now supports a beta parameter.
