### ISSUE TITLE
Jacobian should be Jacobian transpose (at least according to wikipedia)

### ISSUE THREAD

**Issue by altosaar** [pytorch/pytorch#16352]
Wikipedia: https://en.wikipedia.org/wiki/Jacobian_matrix_and_determinant

<img width="860" alt="screenshot 2019-01-24 19 24 14" src="https://user-images.githubusercontent.com/5317244/51717139-a9fb6780-200d-11e9-95b6-589ba859b221.png">

PyTorch docs: https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

![image](https://user-images.githubusercontent.com/5317244/51717148-b4b5fc80-200d-11e9-90d4-74f663d5a59d.png)

Why deviate from the convention? 

Had to stare at it for a bit to realize the definition of the Jacobian is the transpose in PyTorch.

**Comment by altosaar** [comment]
I think the simple change is to rename the Jacobian-vector product to the vector-Jacobian product in the docs. This will align with convention.

**Comment by altosaar** [comment]
Ah, I should have read the PyTorch paper a while ago! It says here that it is indeed vector-Jacobian products. The docs should be updated to reflect this.

https://openreview.net/pdf?id=BJJsrmfCZ

**Comment by soumith** [comment]
thanks @sidhantnagpal
