### ISSUE TITLE
ReduceLROnPlateau should clone "current" when saving "best"

### ISSUE THREAD

**Issue by sorenrasmussenai** [pytorch/pytorch#16364]
## 🐛 Bug
ReduceLROnPlateau fails when the variable passed to `.step()` is reused outside the LR scheduler.

## To Reproduce

```
import torch
t = torch.tensor(0.)
optimizer = torch.optim.SGD([t],lr=.1)
lr_sched = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer,verbose=True,patience=3)

print("---- First step, all good. ----")
loss = torch.Tensor([1.])
print(f"loss = {loss}")
print(f"id(loss) is {hex(id(loss))}.\nid(best) is {hex(id(lr_sched.best))}.")
lr_sched.step(loss)
best1 = lr_sched.best.item()
print(f"best1 = {best1}")

print("\n---- Second step, failure. ----")
loss += 1 #This is equivalent to lr_sched.best += 1, which is bad
print(f"loss = {loss}")
print(f"id(loss) is {hex(id(loss))}.\nid(best) is {hex(id(lr_sched.best))}.")
lr_sched.step(loss)
best2 = lr_sched.best.item()
print(f"best2 = {best2}")

print("\n---- Third step, mitigation ----")
loss = torch.Tensor([3.]) #New tensor
print(f"loss = {loss}")
print(f"id(loss) is {hex(id(loss))}.\nid(best) is {hex(id(lr_sched.best))}.")
lr_sched.step(loss)
best3 = lr_sched.best.item()
print(f"best3 = {best3}")

#Result check
assert best1 == best2 == best3 == 1., "On no, 'best' got worse :("
```

Output:
```
---- First step, all good. ----
loss = tensor([1.])
id(loss) is 0x7f5def805828.
id(best) is 0x7f5e93e2d318.
best1 = 1.0

---- Second step, failure. ----
loss = tensor([2.])
id(loss) is 0x7f5def805828.
id(best) is 0x7f5def805828.
best2 = 2.0

---- Third step, mitigation ----
loss = tensor([3.])
id(loss) is 0x7f5def7364c8.
id(best) is 0x7f5def805828.
best3 = 2.0

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-60-463288f194a2> in <module>
     29 
     30 #Result check
---> 31 assert best1 == best2 == best3 == 1., "On no, 'best' got worse :("

AssertionError: On no, 'best' got worse :(
```

## Expected behavior

`best1 == best2 == best3 == 1`

## Environment

PyTorch version: 1.0.0
Python version: 3.6
Versions of relevant libraries:
[conda] torch                     1.0.0                     <pip>

## Proposed fix: 

```
class ReduceLROnPlateau(object):
    #....
    def step(self, metrics, epoch=None):
        current = metrics
        #....
        if self.is_better(current, self.best):
            self.best = current.clone() ########## added `.clone()` #############
            self.num_bad_epochs = 0
        #....
```

**Comment by cosmin-pascaru** [comment]
.clone() would only work for Tensors, but the user can use any object implementing comparison as loss item (although indeed, probably the most common usages are ndarrays, Tensors, or default float or int values).

**Comment by sorenrasmussenai** [comment]
How about `copy.deepcopy(current)` then?
It seems to work for tensors (cpu and cuda), and will work for ndarrays, floats, etc.
This incurs a small overhead, in cases where copying is not necessary. If that's a problem, it could be handled with a switch, e.g. `step(self, metrics, epoch=None, clone=True)`

**Comment by yf225** [comment]
@sorenrasmussenai `copy.deepcopy(current)` is a good idea

**Comment by sorenrasmussenai** [comment]
@yf225 `copy.deepcopy()` causes `test/test_optim.py:_test_basic_cases_template` to fail:

`RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol`

Any suggestions?

**Comment by ashermancinelli** [comment]
You could copy over the `__slots__` and `__dict__` of `current` to `best` as a workaround

**Comment by sorenrasmussenai** [comment]
@ashermancinelli I don't think explicitly copying private attributes is the way to go..
I opted for a solution, which clones tensors and deepcopies anything else.

**Comment by jagans94** [comment]
Hi @sorenrasmussenai , @ashermancinelli. Is this issue considered resolved. I'm curious does the above solution passes the tests?

**Comment by soumith** [comment]
I'm landing #16697 as a fix for this
