### ISSUE TITLE
[RFC] Adding MKL-DNN Int8 functions to PyTorch/Caffe2 backend 

### ISSUE THREAD

**Issue by Jianhui-Li** [pytorch/pytorch#16361]
## 🚀 Feature

Extend the current ideep/MKL-DNN operation to support the Caffe2 Int8 op following the same semantics as defined by DNNLOWP engine.  

## Motivation

The MKL-DNN int8 functions complements the FBGEMM, as the implementation difference may fit different workloads/hardware for performance and accuracy. For Pytorch user, MKL-DNN int8 allows more backend choices to pick for reduced precision solution. The MKL-DNN Int8 functions are tuned for Skylake and Cascadelake/VNNI. 

## Pitch

Extend the current ideep/MKL-DNN operation to support the Caffe2 Int8 op 

## Additional context

We have aligned with FBGEMM team on using the same Caffe2 Int8 op semantics and quantization methodology. 

Performance result varies according to the workload/hardware/environment setting. As a rule of thumb, for Resnet-50 we expect the int8 speed-up to be ~1.8x on Skylake and ~3x on Cascadelake.

**Comment by jgong5** [comment]
We submitted a couple of PRs for the MKL-DNN INT8 kernels below.
Conv: #16314 #16309
Fused SumRelu: #16315 
Quantize/dequantize: #16312 
INT8 Tensor Fill: #16313 
NCHW2NHWC: #16310 
IDEEP/DNNLOWP Op registration: #16311 
All the PRs above except for #16310 depend on MKL-DNN bridge (i.e. IDEEP) upgrade PR #16308.

We are also working on two additional PRs to extend current DNNLOWP op semantics. We will put a link when these two PRs are submitted.
1. Add fused Conv+SUM+Relu op
2. Extend channel-wise scale/zp for INT8 Tensor Fill for weights
@gujinghui

**Comment by yinghai** [comment]
@jgong5 Have you compared with int8 implementation of Fbgemm? I'm curious in which kind of workload mkldnn works better. Thanks.

**Comment by Jianhui-Li** [comment]
@yinghai   Since the whole topology performance depends on multiple factors, below I am giving a high level view on the performance comparison.  I am copying Jongsoo and Daya in case I miss anything. @dskhudia @jspark1105

Fbgemm uses outlier aware quantilization which maps the weight matrix to a dense matrix with small values and a sparse matrix with outlier large values, and the partial value of matrix multiplication is reduced to 16 bits for the dense matrix part, and 32 bits for the sparse matrix part. On BDW and SKX, we need 3 instruction to reduce to 32 bit, and only 2 instructions to reduce to 16 bits, so Fbgemm can get the performance benefit for the dense matrix assuming the sparse matrix multiplication takes little time. However with Cascadelake, the VNNI instruction reduces to 32 bit partial value with one single instruction. This could offsets the performance benefits of outlier aware quantilization. 

MKL-DNN convolution works directly on the input tensor without im2col step. It only works when the input data is quantized with zero offset. Most CNN workload doesn't require asymmetric quantization which produces quantilized tensors with none-zero offset.  So MKL-DNN could be benefit from the direct convolution without doing im2col.  MKL-DNN works on its private format so there might be some reordering overhead happening on the boundary of a sequence of MKL-DNN ops. 

For both library, the direct convolution and matrix multiplication might be optimized and specialized for specific shape depending on the workloads they have tuned for.  MKL-DNN int8 has been used for a large set of CNN workload and get desired accuracy (<0.5%).  With the MKL-DNN int8 supporting the same caffe2 int8 semantics, two libraries can complement and learn from each other and bring value to the Pytorch ecosystem.

**Comment by Jianhui-Li** [comment]
wrong button, sorry

**Comment by yinghai** [comment]
@Jianhui-Li Yeah, but I think VNNI support is also coming. I understand those details but have you tried benchmarking with fbgemm on resnet50? And what other workload did you try?

**Comment by Jianhui-Li** [comment]
@Yinghai  We checked the FBGEMM performance a while ago on resnet-50 on Skylake, our result shows that the MKL-DNN performance is better.

**Comment by Jianhui-Li** [comment]
@yinghai  The current performance setting is to run single batch or multi-batch on all cores in one socket. We have synced with FBGEMM team on the performance setting and measure on the new settings.  Performance number varies according to workload/hardware/env setting, we expect that FBGEMM and MKL-DNN complements each other on different settings.
