### ISSUE TITLE
[CPP] Support CPP <> Python serialization

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#16367]
## 🚀 Feature
Officially support the ability to serialize a tensor (or any JIT::IValue) in CPP or Python and then load it in CPP / Python.

## Motivation

This is very useful for debugging. For example, 

1. I want to use python to generate input data and load it in CPP (which is my production envrionment) for testing and debugging.
2. I want to use CPP to dump model outputs and load it in Python so that I can use jupyter notebook / matplotlib for visualization and debugging.
3. I want to dump inputs from CPP and load it in Python to compare to with the Python input. To make sure that the data preprocessing is the same between CPP and Python (because I serve the model in CPP but I train the model in Python)

Traditionally, we do this kind of debugging purely in python and we serialize using pickle. But with C++, we need a serialization format that works in both CPP and PyTorch

**Comment by sidazhang** [comment]
It would be good if the serialization scheme is more general than just tensor. It should be able to serialize any jit::IValue. So for example, we should be able to serialize `std::vector<std::vector<Tensor>>` and after https://github.com/pytorch/pytorch/pull/16208 lands. it should be able to support `map<string, Tensor>` as well (in both directions)

**Comment by zdevito** [comment]
We are working on the ability to serialize any IValue, and allow any IValue to exist as an attribute on a script::Module. This should allow for the serialization of models that rely on non-tensor members such as dictionaries.

**Comment by sidazhang** [comment]
Could you explain why people want to serialize a script::Module? The only module that I want to serialize is jit.ScriptModule, no? Why serialize a CPP module?

**Comment by zdevito** [comment]
jit.ScriptModule is just the python wrapper around script::Module. So they are the same thing. But adding attributes to script::Module will allow the use of non-tensor attributes in ScriptModules and the ability to save/load them.

**Comment by sidazhang** [comment]
As a side question, Does it mean that if you allow any IValue to exist as an attribute on script::Module. And if you allow mutable dictionary as an IValue. Then you will essentially allow mutable dictionary as an attribute in ScriptModule?

**Comment by sidazhang** [comment]
@driazati @eellison @suo Additional feature request:

Is it possible to make serialization part of the torchscript and compilable. Use case looks like this:

```
class ModelThatNeedsDebugging(jit.ScriptModule)
  def __init__(self)
      ///
  def forward(self, x):
         y =  self.conv(x)
         y.save("./attention_input.pt")
         output = self.attention(y)
         output.save("./attention_feature_map.pt")
         return output
```

This way it allows me to conveniently debug the model inside a production workflow

```
auto module = torch::jit::load("./ModelThatNeedsDebugging.pt");
module->forward(input);
```

**Comment by suo** [comment]
@sidazhang That's not something that's easy to do in the near future unfortunately. If you'd like you can file a separate issue for that and we can track it there.

**Comment by sidazhang** [comment]
@driazati Quick Qs: 

1. Do we actually support CPP <> Python serialization? Like in both directions?
2. Is there backwards compatibility on IValue serialization format across PyTorch versions?
