### ISSUE TITLE
Add Shift Operation (in ShiftNet) to PyTorch

### ISSUE THREAD

**Issue by kayuksel** [pytorch/pytorch#16408]
## 🚀 Feature

I believe that it would be great to include the Shift operation in PyTorch. Shift operation is a parameter and FLOP-free alternative to spatial convolutions.The shift operation moves each channel of its input tensor in a different spatial direction. A shift-based module interleaves shift operations with point-wise convolutions,  which further mixes spatial information across channels. Unlike spatial convolutions, the shift operation itself requires zero FLOPs and zero parameters. As opposed to depth-wise convolutions, shift operations can be easily and efficiently implemented. 

Paper: https://arxiv.org/abs/1711.08141

CUDA implementation available here: 
https://github.com/peterhj/shiftnet_cuda_v2

ResNet application is available here:
https://github.com/alvinwan/shiftresnet-cifar

Here is another paper where they propose shift-primitives for efficient CNNs:
https://arxiv.org/pdf/1809.08458.pdf

**Comment by soumith** [comment]
this should be doable by generating a fixed grid and using [torch.nn.functional.grid_sample](https://pytorch.org/docs/stable/nn.html?highlight=grid_sample#torch.nn.functional.grid_sample).

We will consider including a dedicate operation / kernel in pytorch core if the method gets more popular.

Thanks for the suggestion.

**Comment by kayuksel** [comment]
@soumith Is it possible if you can give an example on how the F.grid_sample can be used for that purpose?

**Comment by kayuksel** [comment]
@soumith Thank you for your explanation. I recently learnt about "Grouped Convolutional Neural Networks" where they cluster multivariate time series into groups and then use depth-wise convolution. I am curious now if I can use F.grid_sample to train a flow field for grouping the streams of the multivariate time series.

**Comment by kayuksel** [comment]
Ah some people did something very relevant already: 

"AutoShuffleNet:  Learning Permutation Matrices via an Exact Lipschitz Continuous Penalty in Deep Convolutional Neural Network" https://arxiv.org/abs/1901.08624

**Comment by yxchng** [comment]
@soumith Can you explain more how to do this? I don't quite understand your suggestion above? Is torch.roll actually doing this?
