### ISSUE TITLE
cuDNN error when using half precision convolution

### ISSUE THREAD

**Issue by rosinality** [pytorch/pytorch#16437]
## 🐛 Bug

When using half precision convolution on PyTorch nightly (20190125), with torch.backends.cudnn.deterministic = True, CUDNN_STATUS_BAD_PARAM runtime error occurs

I found that when using latest PyTorch 1.0, or using fp32, or use torch.backends.cudnn.deterministic = False then this script runs without problem.

## To Reproduce

```python
import torch
from torch import nn

torch.backends.cudnn.deterministic = True

x = torch.randn(1, 1, 16, 16).to('cuda').half()
conv = nn.Conv2d(1, 1, 3, bias=False).to('cuda').half()

print(conv(x).shape)
```

```python
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    print(conv(x).shape)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 492, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
```

## Expected behavior

Run without error

## Environment

```

PyTorch version: 1.0.0.dev20190125
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla V100-PCIE-32GB
Nvidia driver version: 410.79
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by vishwakftw** [comment]
Could you please run it with `CUDA_LAUNCH_BLOCKING=1` and report the error message?

**Comment by rosinality** [comment]
I run with it,

```python
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    print(conv(x).shape)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 492, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
```

**Comment by soumith** [comment]
cc: @syed-ahmed might be your recent cudnn algorithm selection diff?

**Comment by syed-ahmed** [comment]
Thanks for the cc! I'll try to reproduce and followup on this issue.

**Comment by syed-ahmed** [comment]
Hi, I'm verifying that this was caused by my PR, most probably for not calling cudnnSetConvolutionMathType before cudnnFind/cudnnGet. In the meanwhile, I have verified that with this patch in my PR https://github.com/pytorch/pytorch/pull/15881/commits/436aea6b362255bb203d76f3f1f2e26eec6f3fb5 and with the reproducer script from this issue, the cuDNN error goes away.

**Comment by connorchristopherson** [comment]
@vishwakftw mentioned running with `CUDA_LAUNCH_BLOCKING=1`, how do you do that? Or... where could I find resources to learn how to work with CUDA's environment variables?
