### ISSUE TITLE
Cuda error for 3D conv net of input size >=256x256x*

### ISSUE THREAD

**Issue by Hierakonpolis** [pytorch/pytorch#16443]
## 🐛 Bug

3D convolutional network with size > 256x256x4 returns `cuDNN error: CUDNN_STATUS_EXECUTION_FAILED` when performing `loss.backward()`. Works fine on CPU.

## To Reproduce

With Zsize >=4 (input size 256x256x4), this code results in `cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`. This is not the case for input size 255x255x100, for example. Eliminating all `.cuda` occurences and commenting out `torch.set_default_tensor_type('torch.cuda.FloatTensor')` the code runs smoothly on CPU.
```

import torch
import torch.nn as nn
torch.set_default_tensor_type('torch.cuda.FloatTensor')

class Net(nn.Module):
    
    def __init__(self):
        super(Net,self).__init__()
        self.layer1=nn.Conv3d(1,64,5,padding=2) 
        
        self.layer2 = nn.Conv3d(64,1,1)
        self.sigmoid=nn.Sigmoid()
            
            
    def forward(self,in_vol):
        
        first = self.layer1(in_vol)

        MonoClass=self.layer2(first)
        
        Mask=self.sigmoid(MonoClass)
        
        return Mask


A=Net().cuda()
batch=1

SideSize=256
Zsize=4
X=torch.randn(batch,1,SideSize,SideSize,Zsize)
X=X.cuda()

optimizer=torch.optim.Adam(A.parameters())

optimizer.zero_grad()
Mask = A(X)

loss=torch.sum(Mask)
loss=loss
loss.backward()
optimizer.step()
print(loss)
```

Traceback:

```
Traceback (most recent call last):
  File "Error.py", line 51, in <module>
    loss.backward()
  File "/home/riccardo/.anaconda3/envs/PyTorch/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/riccardo/.anaconda3/envs/PyTorch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
## Expected behavior

Should be capable to compute loss and gradient on GPU.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Linux Mint 19.1 Tessa
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 410.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy (1.16.0)
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.0.0           py3.7_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by yf225** [comment]
cc @ngimel

**Comment by Hierakonpolis** [comment]
> As a workaround, you can add
> `torch.backends.cudnn.benchmark=True` to your script.

Thanks, this seems to work

**Comment by mruberry** [comment]
Would you please try this with cuDNN v7.5.0.42 or greater?

**Comment by ezyang** [comment]
looks fixed
