### ISSUE TITLE
ONNX export failed on ATen operator 

### ISSUE THREAD

**Issue by robbine** [pytorch/pytorch#16442]
Here is the error message: ONNX export failed on ATen operator layer_norm  because torch.onnx.symbolic.layer_norm does not exist

Does pytorch module needs to follow certain rules in order to export using ONNX ?

**Comment by yf225** [comment]
@robbine Can you use the issue template to give us more information?

**Comment by robbine** [comment]
I am trying to export this very large bert transformer module, https://github.com/robbine/allennlp-as-a-library-example/blob/master/my_library/modules/seq2seq_encoders/transformer.py
I would like to upload a full stack info if needed. Here is a short stack trace:
Traceback (most recent call last):
  File "scripts/export_pytorch_script.py", line 87, in <module>
    sys.exit(main())
  File "scripts/export_pytorch_script.py", line 83, in main
    torch.onnx.export(model=model._transformer, args=(dummy_input, dummy_mask), f=args.output_pt, verbose=True)
  File "/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 26, in export
    return utils.export(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    operator_export_type=operator_export_type)
  File "/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 232, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::layer_norm

Defined at:
/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py(1314): layer_norm
/anaconda3/lib/python3.7/site-packages/torch/nn/modules/normalization.py(148): forward
/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(465): _slow_forward
/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(475): __call__
./my_library/modules/layers/common_attention.py(1160): layer_norm_and_dropout
./my_library/modules/layers/common_attention.py(1149): embedding_postprocessor
./my_library/modules/seq2seq_encoders/transformer.py(202): forward
/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(465): _slow_forward
/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(475): __call__
/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py(109): forward
/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(477): __call__
/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py(77): get_trace_graph
/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py(144): _trace_and_get_graph_from_model
/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py(177): _model_to_graph
/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py(226): _export
/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py(94): export
/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py(26): export
scripts/export_pytorch_script.py(83): main
scripts/export_pytorch_script.py(87): <module>

**Comment by robbine** [comment]
Both layer_norm and erf are defined in https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py. However the exporter complaints they are not exist. 
/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py:446: UserWarning: ONNX export failed on ATen operator layer_norm because torch.onnx.symbolic.layer_norm does not exist
  .format(op_name, op_name))
anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py:446: UserWarning: ONNX export failed on ATen operator erf because torch.onnx.symbolic.erf does not exist

**Comment by lawlietAi** [comment]
Hi @robbine , is there any solution about erf exporting?

**Comment by maeotaku** [comment]
@robbine  @lawlietAi did you find a solution to this?

**Comment by lawlietAi** [comment]
> @robbine  @lawlietAi did you find a solution to this?

**erf** does not in onnx basic symbolic set. so you can add a param to modify the domain of symbolic .
but I have forgotten what param you need to add. you may need to try.
