### ISSUE TITLE
Windows LibTorch nightly build contains nothing but DLLs.

### ISSUE THREAD

**Issue by HapeMask** [pytorch/pytorch#16446]
## 🐛 Bug

If you download today's LibTorch nightly build for Windows w/CUDA 10, the zip file is only ~400MB and contains just a few DLLs, nothing else.

## To Reproduce

1. Download the Windows LibTorch nightly binaries: https://download.pytorch.org/libtorch/nightly/cu100/libtorch-win-shared-with-deps-latest.zip
2. Unzip files.
3. Unzipped files are just `libtorch\lib\[cuda_DLLs].dll`

## Expected behavior

Zip file contains DLLs, .lib files, and headers.

## Environment

Windows 10
LibTorch Nightly 20190128 (CUDA 10)

**Comment by yf225** [comment]
cc @peterjc123
