### ISSUE TITLE
RuntimeError: _th_normal_ is not implemented for type torch.HalfTensor

### ISSUE THREAD

**Issue by amd-lthakur** [pytorch/pytorch#16450]
## 🐛 Bug

I Set the default variables in the file to "torch.set_default_tensor_type('torch.HalfTensor')". After the following line give the error described in the title:
 self.bias = torch.nn.Parameter(torch.randn(1))

Request some help here. 
Thanks in advance.

**Comment by soumith** [comment]
`torch.set_default_tensor_type('torch.HalfTensor')` this is not supported -- we dont support any operations other than copy on a CPU HalfTensor, we probably should make this an error.
