### ISSUE TITLE
torch.jit.script is not getting type hint correct

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#16492]
I don't think users would do odd things like below, but it would be nice to fix:
```python
import torch
import typing
from typing import List

Tuple = {torch.Tensor : List[torch.Tensor]}
print(Tuple[torch.Tensor])

def f(x: Tuple[torch.Tensor]):
    return x

@torch.jit.script
def g(x: Tuple[torch.Tensor]):
    return x

print(typing.get_type_hints(f))
print(g.graph)
```

prints

```
typing.List[torch.Tensor]
{'x': typing.List[torch.Tensor]}
graph(%x : (Tensor)) {
  return (%x);
}
```
but it should be
```
typing.List[torch.Tensor]
{'x': typing.List[torch.Tensor]}
graph(%x : Tensor[]) {
  return (%x);
}
```

**Comment by driazati** [comment]
Thanks for reporting! Agreed this is pretty odd but there's some underlying refactoring we should be doing anyways that would help with this.

**Comment by wconstab** [comment]
Verified the expected behavior 
`typing.List[torch.Tensor]
{'x': typing.List[torch.Tensor]}
graph(%x.1 : Tensor[]):
  return (%x.1)`

is observed after PR https://github.com/pytorch/pytorch/pull/39269
