### ISSUE TITLE
Different behavior of torch.round() on CPU and GPU

### ISSUE THREAD

**Issue by xxtemp** [pytorch/pytorch#16498]
## 🐛 Bug

torch.round() seems to be rounding differently for CPU and GPU tensors.
On CPU tensors it rounds [half-to-even](https://en.wikipedia.org/wiki/Rounding#Round_half_to_even) and on GPU it rounds [away-from-zero](https://en.wikipedia.org/wiki/Rounding#Round_half_away_from_zero) as shown in the example below.

## To Reproduce
CPU rounding:
\>>> torch.Tensor([1.5, 2.5, 3.5, 4.5]).round()
**tensor([2., 2., 4., 4.])**

GPU rounding:
\>>> torch.Tensor([1.5, 2.5, 3.5, 4.5])**.cuda()**.round()
**tensor([2., 3., 4., 5.], device=‘cuda:0’)**

## Expected behavior
I expected the function to behave the same on CPU/GPU, either returning [2., 2., 4., 4.] or [2., 3., 4., 5.] on both commands.
It could also be nice to have a way to control the rounding method in future releases, but that's a different issue.

## Environment
 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.5.2
 - CUDA/cuDNN version: 9
 - GPU models and configuration: GeForce GTX 1060
 - Any other relevant information:

**Comment by colesbury** [comment]
The CPU behavior is actually even more inconsistent. Depending on the instruction set it may:
1) Round to nearest even (via _mm256_round_ps with `_MM_FROUND_TO_NEAREST_INT`)
2) Round away from zero (via `std::round`)

**Comment by colesbury** [comment]
For comparison:
- NumPy around rounds to nearest even
- Matlab rounds away from zero
- C and C++ round away from zero (std::round, roundf)
- Lua Torch rounds away from zero (using C's roundf)
- Java rounds to positive infinity

**Comment by vishwakftw** [comment]
Fixed by #17443.
