### ISSUE TITLE
How to get raw pointer from tensors?

### ISSUE THREAD

**Issue by yuandong-tian** [pytorch/pytorch#1649]
Hi all, I want to know how to get raw pointer from PyTorch tensors? 

Background: I want to have multiple C threads writing the network input tensor in parallel.

**Comment by soumith** [comment]
x.data_ptr gives you the raw pointer

**Comment by SuperShinyEyes** [comment]
I'm puzzled how this works when one is using a GPU. Does `data_ptr` loads tensors to CPU from GPU? If that is the case, how does it keep the content synced between CPU and GPU during a runtime?

**Comment by soumith** [comment]
@SuperShinyEyes data_ptr for a GPU Tensor will point to a pointer to GPU memory. You cannot operate on that pointer directly, and have to give it to a CUDA kernel

**Comment by bhilburn** [comment]
@soumith - Thanks so much for your comment about about the pointer being to GPU memory! Just stumbled across this issue, and your comment made post-issue-close was very helpful.

**Comment by zimenglan-sysu-512** [comment]
hi @soumith 
is it a way to get access to the raw GPU data of a tensor for pyCUDA and convert back?
thanks.

**Comment by BarakChamo** [comment]
I've been following this post on looking at other information about interoperability between PyTorch tensors and other CUDA libraries.

Seems like the way to go is to create an empty tensor of the right size and stride and write to its GPU pointer from elsewhere? (i.e. `PyCuda`, `Numba`). I couldn't find any way of creating a Tensor from a pointer.

[This is an example I've ben following from the forums](https://discuss.pytorch.org/t/accelerating-layers-with-numba/13923)
