### ISSUE TITLE
[CPP] Cannot compile TF C API and libtorch into the same target

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#16509]
## 🐛 Bug

Cannot compile TF C API and libtorch into the same target. This makes migration away from TF a little bit annoying. When users (that already use TF) are trying out libtorch, it is just more friction to have to clean up all the TF stuff.

## To Reproduce
```
bazel-out/k8-fastbuild_re/bin/external/tensorflow_repo/_virtual_includes/tensorflow_c_headers/c_api.h:1663:4: error: redefinition of 'INFO'
   INFO = 0,            // base_logging::INFO;
   ^
external/libtorch_repo/include/c10/util/logging_is_not_google_glog.h:27:11: note: previous definition is here
const int INFO = 0;
          ^
```

**Comment by soumith** [comment]
Possibly relevant PR: https://github.com/pytorch/xla/pull/34

**Comment by soumith** [comment]
@sidazhang in your internal bazel build files, add the define `C10_USE_GLOG`

See: https://github.com/pytorch/pytorch/blob/f25322fb9756f2943c00800a086ef2733f864598/c10/util/Logging.h#L25

**Comment by sidazhang** [comment]
What is this `logging_is_google_glog.h` and not glog.h? If I define C10_USE_GLOG and don't compile with TF, does this matter?

**Comment by soumith** [comment]
the c10 logging has a logging API that can use glog, or can use our own shim.

> If I define C10_USE_GLOG and don't compile with TF, does this matter?

No it does not matter, you can always compile / link with glog, even when not using TF, if you want.

**Comment by ezyang** [comment]
pretty sure we fixed these macro conflicts
