### ISSUE TITLE
Undefined GPU Reference when importing torch with caffe2.onnx.backend for cpu-only pytorch

### ISSUE THREAD

**Issue by gauss345** [pytorch/pytorch#16500]
## 🐛 Bug

installed in python pytorch-cpu, torchvision-cpu.

when importing: import caffe2.python.onnx.backend as backend
A warning is issued regarding CPU only mode.
subsequent import of : import torch
then produces an ImportError In Python.

## To Reproduce

Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 03:09:43) 
[GCC 7.3.0] on linux
>>> import caffe2.python.onnx.backend as backend
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxx/.local/lib/python3.6/site-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
ImportError: /home/xxxx/.local/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so: undefined symbol: _ZNK2at10TensorImpl6detachEv

When Running, the below 

Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 03:09:43) 
[GCC 7.3.0] on linux
>>> from caffe2.python import onnx
>>> from onnx import backend as backend
>>> import torch

No error was observed during importing, but the wrong onnx module is imported this way.

It seems pytorch and caffe2 not playing nice... :(
## Expected behavior

Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 03:09:43) 
[GCC 7.3.0] on linux
>>> import caffe2.python.onnx.backend as backend
>>> import torch

## Environment

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Debian GNU/Linux buster/sid
GCC version: (Debian 8.2.0-14) 8.2.0
CMake version: version 3.13.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.2.148
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] mkl                       2019.1                      144  
[conda] pytorch-cpu               1.0.0               py3.6_cpu_1    pytorch
[conda] scipy                     0.19.1          py36_nomklh59deb5f_3  
[conda] torchvision-cpu           0.2.1                      py_2    pytorch

onnx                      1.3.0           py36hf2d0322_1000    conda-forge

**Comment by ujsyehao** [comment]
how to uninstall it?
