### ISSUE TITLE
[docs] torch.nn.functional.one_hot docs missing

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#16508]
https://pytorch.org/docs/master/nn.html#one-hot

**Comment by vishwakftw** [comment]
I believe this can be closed now. 

![image](https://user-images.githubusercontent.com/23639302/52894326-7efbd200-31cd-11e9-900c-9dc059ae6e00.png)

**Comment by heiner** [comment]
I might be blind but currently C-f "hot" on https://pytorch.org/docs/master/nn.html yields no hits?

**Comment by tcc78** [comment]
Just to help those that stumble across this question (like I did), you can find the documentation here:
https://pytorch.org/docs/stable/nn.functional.html
