### ISSUE TITLE
Delete _cudart from torch/cuda/__init__.py

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#16527]
_cudart is the Python ctypes binding to the libcudart.so library. It was previously used for Streams and Events but is now unused. The initialization (in _load_cudart) can sometimes fail. For example, @zou3519 ran into:

```
RuntimeError: couldn't find libcudart. Make sure CUDA libraries are installed in a default location,
or that they're in LD_LIBRARY_PATH.
```

**Comment by SsnL** [comment]
btw, `_cudart` is used by `test_cuda_primary_ctx.py` https://github.com/pytorch/pytorch/blob/ffed8bff6a1df334e371957009dd77af0c5140dd/test/test_cuda_primary_ctx.py.

**Comment by soumith** [comment]
[this is a better fix](https://github.com/pytorch/pytorch/commit/f748654e0e070f9e4c635ffc295d694530bb45cd), that I'll cherry-pick onto master, if we want to keep cudart around.
But if we can indeed delete it, that's double awesome!

**Comment by ezyang** [comment]
we have a new way of doing cudart, this issue is obsolete
