### ISSUE TITLE
bug when using sparse.mm

### ISSUE THREAD

**Issue by keithyin** [pytorch/pytorch#16543]
## 🐛 Bug

when using sparse.mm to do sparse_matrix dense_matrix matrix multiplication, when the sparse_matrix is all zeros, it sometimes gets nan in the result.

## To Reproduce

```python
import torch
from torch import sparse
from torch.nn import init
from torch import nn
from itertools import count


def main():
    idx = torch.LongTensor([[], []])
    values = torch.FloatTensor([])
    sp_tensor = sparse.FloatTensor(idx, values, torch.Size([3, 10]))
    mat2 = nn.Parameter(init.xavier_normal_(torch.empty(10, 150)))
    print(sp_tensor.to_dense())
    for i in count():
        spmm = sparse.mm(sp_tensor, mat2)
        assert bool(torch.sum(torch.isnan(spmm)) == 0), "iter: {} ===> sparse mm nan happened.".format(i)


if __name__ == '__main__':
    main()

```
if you run the above script, sometimes the assertion error will happen.

error messages, stack traces
```
Traceback (most recent call last):
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
  File "/home/keith/PycharmProjects/GCN4MatrixCompletion/model.py", line 78, in <module>
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
    main()
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
  File "/home/keith/PycharmProjects/GCN4MatrixCompletion/model.py", line 74, in main
    assert bool(torch.sum(torch.isnan(spmm)) == 0), "iter: {} ===> sparse mm nan happened.".format(i)
AssertionError: iter: 13 ===> sparse mm nan happened.

Process finished with exit code 1

```

## Expected behavior

all zeros is the correct result

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 16.04 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.9.4

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 8.0.44
GPU models and configuration: GPU 0: GeForce GTX 960M
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so
/usr/local/cuda-8.0/lib64/libcudnn.so.6
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     0.4.0                     <pip>
[conda] torchaudio                0.1                       <pip>
[conda] torchvision               0.2.0                     <pip>

**Comment by gchanan** [comment]
confirmed this is an issue on master, fix incoming.
