### ISSUE TITLE
Windows 10 build using Visual Studio 2017 - THD failing to build, looking for sys/socket.h

### ISSUE THREAD

**Issue by alevonian** [pytorch/pytorch#16544]
## Issue description
There are at least 12 build errors in building THD as the files use sys/socket.h instead of the windows winsock2.h

## Code example

Trying to build pytorch from source in windows using Visual Studio 2017

## System Info
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\base\DataChannel.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\base\Cuda.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\base\init_methods\InitMethodFile.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\base\DataChannelRequest.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\base\ChannelUtils.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\base\init_methods\InitMethod.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\base\data_channels\DataChannelTCP.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\base\init_methods\InitMethodEnv.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\base\init_methods\InitMethodTCP.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\base\init_methods\InitMethodUtils.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\process_group\General.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	
Error	C1083	Cannot open include file: 'sys/socket.h': No such file or directory (compiling source file C:\Projects\pytorch\torch\lib\THD\process_group\Collectives.cpp)	THD	c:\projects\pytorch\torch\lib\thd\base\channelutils.hpp	4	

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): Installing using pip works fine
- Build command you used (if compiling from source): Cmake then Visual Studio 2017
- OS: Windows 10
- PyTorch version: 1.0
- Python version: 3.7
- CUDA/cuDNN version: 10

- CMake version: 3.12.1
- Versions of any other relevant libraries:

**Comment by peterjc123** [comment]
Are you forcing it to build using `USE_DISTRIBUTED=1`? It is not currently supported.

**Comment by alevonian** [comment]
I didn't set it, but it was set to true. I will test it without it and report back....

**Comment by alevonian** [comment]
After building with the USE_DISTRIBUTED=0, this problem is solved.
Thanks.
I will close this issue.

**Comment by xkszltl** [comment]
Run into the same issue today.
Should we consider defaulting this to OFF with MSVC?

**Comment by peterjc123** [comment]
It should be set to OFF on default. Which command are you using during build?

**Comment by xkszltl** [comment]
Just a simple cmake command.
https://github.com/pytorch/pytorch/blob/3d4d7b90820101988b84e0b9a6544aeaa2247ee1/CMakeLists.txt#L124

**Comment by peterjc123** [comment]
Oh, I see. You are using the cmake command. I'll see what I can do to fix this issue.
