### ISSUE TITLE
Errors while installing  from source on Mac 

### ISSUE THREAD

**Issue by lunasdejavu** [pytorch/pytorch#16553]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,4
  Processor Name:	Intel Core i7
  Processor Speed:	2.2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	187.0.0.0.0
  SMC Version (system):	2.29f24
  Serial Number (system):	C02W324ZG8WN
  Hardware UUID:	8373CE22-3B74-59B3-AF45-32E8F3D62424
without GPU python:3.6.7
when I use the instructions 
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install

the errors showed up
/Users/lunasdejavu/pytorch/torch/csrc/WindowsTorchApiMacro.h:15:34: note: expanded from macro 'TORCH_API'
#define TORCH_API __attribute__((__visibility__("default")))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
35 warnings generated.
[ 94%] Building CXX object caffe2/torch/CMakeFiles/torch.dir/csrc/api/src/optim/adagrad.cpp.o
[ 94%] Building CXX object caffe2/torch/CMakeFiles/torch.dir/csrc/api/src/optim/adam.cpp.o
1 warning generated.
[ 94%] Building CXX object caffe2/torch/CMakeFiles/torch.dir/csrc/api/src/optim/lbfgs.cpp.o
12 warnings generated.
[ 94%] Building CXX object caffe2/torch/CMakeFiles/torch.dir/csrc/api/src/optim/optimizer.cpp.o
[ 94%] Building CXX object caffe2/torch/CMakeFiles/torch.dir/csrc/api/src/optim/rmsprop.cpp.o
1 warning generated.
1 warning generated.
[ 94%] Building CXX object caffe2/torch/CMakeFiles/torch.dir/csrc/api/src/optim/serialize.cpp.o
[ 94%] Building CXX object caffe2/torch/CMakeFiles/torch.dir/csrc/api/src/optim/sgd.cpp.o
[ 94%] Building CXX object caffe2/torch/CMakeFiles/torch.dir/csrc/api/src/serialize/input-archive.cpp.o
[ 94%] Building CXX object caffe2/torch/CMakeFiles/torch.dir/csrc/api/src/serialize/output-archive.cpp.o
1 warning generated.
[ 94%] Linking CXX shared library ../../lib/libtorch.dylib
ld: warning: direct access in function 'google::protobuf::internal::ExtensionSet::MutableString(int, unsigned char, google::protobuf::FieldDescriptor const*)' from file '../../lib/libprotobuf.a(extension_set.cc.o)' to global weak symbol 'void google::protobuf::internal::arena_destruct_object<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void*)' from file 'CMakeFiles/torch.dir/csrc/jit/export.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom(int, google::protobuf::internal::ExtensionSet::Extension const&)' from file '../../lib/libprotobuf.a(extension_set.cc.o)' to global weak symbol 'void google::protobuf::internal::arena_destruct_object<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void*)' from file 'CMakeFiles/torch.dir/csrc/jit/export.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'google::protobuf::internal::ExtensionSet::ParseFieldWithExtensionInfo(int, bool, google::protobuf::internal::ExtensionInfo const&, google::protobuf::io::CodedInputStream*, google::protobuf::internal::FieldSkipper*)' from file '../../lib/libprotobuf.a(extension_set.cc.o)' to global weak symbol 'void google::protobuf::internal::arena_destruct_object<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void*)' from file 'CMakeFiles/torch.dir/csrc/jit/export.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'void google::protobuf::internal::RepeatedPtrFieldBase::MergeFrom<google::protobuf::internal::GenericTypeHandler<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >(google::protobuf::internal::RepeatedPtrFieldBase const&)' from file '../../lib/libprotobuf.a(generated_message_reflection.cc.o)' to global weak symbol 'void google::protobuf::internal::arena_destruct_object<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void*)' from file 'CMakeFiles/torch.dir/csrc/jit/export.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'void google::protobuf::internal::RepeatedPtrFieldBase::AddAllocatedSlowWithCopy<google::protobuf::RepeatedPtrField<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::TypeHandler>(google::protobuf::RepeatedPtrField<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::TypeHandler::Type*, google::protobuf::Arena*, google::protobuf::Arena*)' from file '../../lib/libprotobuf.a(message.cc.o)' to global weak symbol 'void google::protobuf::internal::arena_destruct_object<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void*)' from file 'CMakeFiles/torch.dir/csrc/jit/export.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'void google::protobuf::internal::RepeatedPtrFieldBase::MergeFrom<google::protobuf::RepeatedPtrField<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::TypeHandler>(google::protobuf::internal::RepeatedPtrFieldBase const&)' from file '../../lib/libprotobuf.a(type.pb.cc.o)' to global weak symbol 'void google::protobuf::internal::arena_destruct_object<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void*)' from file 'CMakeFiles/torch.dir/csrc/jit/export.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'google::protobuf::internal::ArenaStringPtr::CreateInstance(google::protobuf::Arena*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*)' from file '../../lib/libprotobuf.a(type_resolver_util.cc.o)' to global weak symbol 'void google::protobuf::internal::arena_destruct_object<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void*)' from file 'CMakeFiles/torch.dir/csrc/jit/export.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
[ 94%] Built target torch
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 720, in <module>
    build_deps()
  File "setup.py", line 279, in build_deps
    build_dir='build')
  File "/Users/lunasdejavu/pytorch/tools/build_pytorch_libs.py", line 228, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir)
  File "/Users/lunasdejavu/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '8', 'install']' returned non-zero exit status 2.

help me please

**Comment by jzenn** [comment]
got the same issue is there an update?

**Comment by VitalyFedyunin** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.

**Comment by VitalyFedyunin** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
