### ISSUE TITLE
inconsistent tensor sizes when invoking backward()

### ISSUE THREAD

**Issue by zhang-wen** [pytorch/pytorch#1655]
when i call backward function by using 

``
batch_loss.backward()
``
i got following error, can anyone tell me why, thank you very much .

```
    batch_loss.backward()
  File "/home/wen/anaconda3/lib/python2.7/site-packages/torch/autograd/variable.py", line 146, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
  File "/home/wen/anaconda3/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 546, in backward
    return grad_input.scatter_(self.dim, index, grad_output), None
RuntimeError: inconsistent tensor sizes at /py/conda-bld/pytorch_1493676237139/work/torch/lib/TH/generic/THTensorMath.c:466
```

**Comment by LuZhenHuan** [comment]
when process your data, use `input = trainset[1].clone()`. I think.

**Comment by apaszke** [comment]
do you have a small code snippet that reproduces it?

**Comment by zhang-wen** [comment]
@apaszke @LuZhenHuan  hello , i use ``gather`` function to calculate the loss myself originally , if i calculate loss myself it show the above error, but if i use ``nn.NLLLoss`` , it works , i do not know why . can you tell me ?

**Comment by apaszke** [comment]
It's impossible for me to tell you what's the problem, because I don't even see what kind of ops are you using.

**Comment by zhang-wen** [comment]
@apaszke 3q, i have solved the problem . i need to use nn.NLLLoss,
