### ISSUE TITLE
torch::Tensor backward() does not return 

### ISSUE THREAD

**Issue by c-hofer** [pytorch/pytorch#16552]
## 🐛 Bug

When a Tensor is given from python into a custom cpp function a call to `backward()` in this function does not return . See example. 

## To Reproduce

`sandbox.cpp`:
```
#include <torch/extension.h>
#include <iostream>

torch::Tensor test_f(const torch::Tensor& point_cloud)
{ 

    std::cout << point_cloud.options() << std::endl; // requires_grad == false why?
    auto l = point_cloud.sum();

    l.backward(); // does not return 
    return point_cloud; 
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m)
{
    m.def("test_f", &test_f, "");
}
```

`sandbox.py`:
```
import torch
from torch.utils.cpp_extension import load


__C = load(
    'sandbox',
    ['sandbox.cpp'],
    verbose=True)


x = torch.ones((10,2), requires_grad=True, device="cpu")*2
y = __C.test_f(x)

print(y)
```
What additionally puzzles me is that the `requires_grad` flag in `point_cloud.options()` evaluates to `false` as we enter `test_f`. 

## Expected behavior

return of `backward` or error. 

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 396.37
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.3.1
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch                   1.0.0           py3.7_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by c-hofer** [comment]
Hi @albanD,

i observe that too. 

btw, how do u guys handle custom kernels on multi gpu systems, to be precise, usage of cudaSetDevice and similar functionality. I've studied the sources for some time now but still havn't really an idea how/where u do it when u call kernels. Maybe u can give me a hint? :D

**Comment by albanD** [comment]
For the device setting, I think you should use `at::OptionalDeviceGuard` (used [here](https://github.com/pytorch/pytorch/blob/7d7855ea3124c16862ea7ed4758f4c7a804ca1ac/torch/csrc/autograd/engine.cpp#L439) for example), that will ensure that the device is correct in the scope where it exists and restored on exit of this scope.

For the problem at hand here, something looks wrong with `.options()` and that might make the autograd engine deadlock expecting some work to be done while no work is actually needed and so nothing reports back as having done something ever.
Someone more knowledgeable about this part will need to take a look @ezyang do you know the best person to look into this?

**Comment by c-hofer** [comment]
Thx, u saved me some time :)

**Comment by ezyang** [comment]
It turns out this was a GIL problem. When you run this on master you get:

```
Loading extension module sandbox...
TensorOptions(dtype=float, device=cpu, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))
Traceback (most recent call last):
  File "sandbox.py", line 12, in <module>
    y = __C.test_f(x)
RuntimeError: The autograd engine was called while holding the GIL. If you are using the C++ API, the autograd engine is an expensive operation that does not require the GIL to be held so you should release it with 'pybind11::gil_scoped_release no_gil;'. If you are not using the C++ API, please report a bug to the pytorch team.
```

That would explain why it hangs. Releasing the GIL will fix the test program.
