### ISSUE TITLE
C++ link error

### ISSUE THREAD

**Issue by XuhuiSun95** [pytorch/pytorch#16551]
## To Reproduce

1. Using stable(1.0) Linux LibTorch C++ CUDA9.0
1. Compile my program together with lib glog and thrift
1. glog/gflags line of code in my program
```cpp
FLAGS_log_dir = log_path;
```

Link error:
```sh
CMakeFiles/PytorchClassificationServer.dir/src/main.cpp.o: In function `main':
main.cpp:(.text+0x44a): undefined reference to `fLS::FLAGS_log_dir'
CMakeFiles/PytorchClassificationServer.dir/src/service/Service.cpp.o: In function `ServiceConcurrentClient::recv_RecognizeImage(RST_RCGZ&, int)':
Service.cpp:(.text+0x1d5e): undefined reference to `apache::thrift::async::TConcurrentClientSyncInfo::getPending(std::string&, apache::thrift::protocol::TMessageType&, int&)'
Service.cpp:(.text+0x20b4): undefined reference to `apache::thrift::async::TConcurrentClientSyncInfo::updatePending(std::string const&, apache::thrift::protocol::TMessageType, int)'
collect2: error: ld returned 1 exit status
CMakeFiles/PytorchClassificationServer.dir/build.make:335: recipe for target 'PytorchClassificationServer' failed
make[2]: *** [PytorchClassificationServer] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/PytorchClassificationServer.dir/all' failed
make[1]: *** [CMakeFiles/PytorchClassificationServer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

## Expected behavior

If I comment out 'find_package (Torch REQUIRED)` in my CMake file, which not link the libtorch library, my program could build successfully. However, with libtorch included, the link error related to glog/gflags and thrift code appears.

My CMake file:
```cmake
cmake_minimum_required (VERSION 3.0 FATAL_ERROR)
set (project_name PytorchClassificationServer)
project (${project_name})

# The version number.
set (PROJECT_VERSION_MAJOR 0)
set (PROJECT_VERSION_MINOR 1)

# C++14
set(CMAKE_CXX_STANDARD 14)

# configure a header file to pass some of the CMake settings
# to the source code
configure_file (
    "${PROJECT_SOURCE_DIR}/src/project_config.h.in"
    "${PROJECT_BINARY_DIR}/project_config.h"
    )

# add the binary tree to the search path for include files
# so that we will find config.h
include_directories (
    "${PROJECT_SOURCE_DIR}/include"
    "${PROJECT_BINARY_DIR}"
    )

# add the binary tree to the search path for lib files
# so that we will find *.so
link_directories (${PROJECT_SOURCE_DIR}/lib)

# find dependency packages
# find Torch result glog linking error, not find package for now
find_package (Torch REQUIRED)
find_package (OpenCV REQUIRED)

# add the executable
add_executable (${project_name}
    src/main.cpp
    src/configuration.cpp
    src/system_manager.cpp
    src/server.cpp
    src/service_handler.cpp
    src/service/pytorch_constants.cpp
    src/service/pytorch_types.cpp
    src/service/Service.cpp
    src/classifier.cpp
    )

target_link_libraries (${project_name}
    ${TORCH_LIBRARIES}
    ${OpenCV_LIBS}
    -lglog
    -lstdc++fs
    -lthrift
    -lthriftnb
    -levent
    )
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Ubuntu 16.04.5 LTS
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: 9.0
 - GPU models and configuration: GPU 0: GeForce GTX 760 Ti OEM
 - Any other relevant information:
 -- GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
 -- CMake version: version 3.5.1
 -- LibTorch version: stable(1.0) Linux CUDA9.0
 -- thrift version: 0.9.3 build from source
 -- glog version: 0.3.5 build from source

## Additional context

I don't know if this is related to my CMake settings or this is a bug in the current library. Could someone give some suggestion? 
Thanks.

**Comment by XuhuiSun95** [comment]
In case anyone has a similar issue, build the lib from source.
This seems like an issue which your local project compiler is incompatible with the compiler building libtorch. 
More detail in #15138

**Comment by davidirobinson** [comment]
I had the same issue where introducing TORCH_LIBRARIES are a dependency cases linking issues with other libraries. Building from source and adding 
/absolute/path/to/pytorch/torch/lib/tmp_install to my CMAKE_PREFIX_PATH was the fix!
