### ISSUE TITLE
cannot initialize type "_CudaDeviceProperties" error

### ISSUE THREAD

**Issue by olyaromanyuk** [pytorch/pytorch#16559]
## ❓ Questions and Help

Sometimes while running pytorch code I get an error like this

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/olha/arabidopsis_genomes/script_test_model_gradients_chromosome.py", line 97, in process_batch
    model = torch.load(os.path.join(base_directory, model_folder, 'model.pt'))
  File "/home/olha/.local/lib/python3.6/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/olha/.local/lib/python3.6/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
  File "/home/olha/.local/lib/python3.6/site-packages/torch/serialization.py", line 504, in persistent_load
    data_type(size), location)
  File "/home/olha/.local/lib/python3.6/site-packages/torch/serialization.py", line 113, in default_restore_location
    result = fn(storage, location)
  File "/home/olha/.local/lib/python3.6/site-packages/torch/serialization.py", line 95, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/olha/.local/lib/python3.6/site-packages/torch/_utils.py", line 68, in _cuda
    with torch.cuda.device(device):
  File "/home/olha/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 229, in __enter__
    _lazy_init()
  File "/home/olha/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    torch._C._cuda_init()
RuntimeError: generic_type: cannot initialize type "_CudaDeviceProperties": an object with that name is already defined
```
I was not able to figure out what exactly causes the error, maybe it is connected to threading in some way. There is no mention of this behavior in docs, issues or forums. The only resources I could find that mention the error are these issues in pybind:
 - [https://github.com/pybind/pybind11/issues/608](https://github.com/pybind/pybind11/issues/608)
 - [https://github.com/pybind/pybind11/issues/994](https://github.com/pybind/pybind11/issues/994)

I am using pytorch 1.0.0 and CUDA 10

**Comment by hitlk** [comment]
same issue in pytorch 1.0.1 and cuda 10

**Comment by soumith** [comment]
this sounds like a race condition of some sort. @ezyang any ideas?

**Comment by ezyang** [comment]
The registration in question appears to be GIL protected, so I don't think it's a race.

@olyaromanyuk @hitlk could you paste the output of pip list in the environment with this problem? I want to know if you have multiple copies of PyTorch installed.

**Comment by hitlk** [comment]
@ezyang 

This is my environment:

> Collecting environment information...
> PyTorch version: 1.0.1.post2
> Is debug build: No
> CUDA used to build PyTorch: 10.0.130
> 
> OS: Ubuntu 16.04.5 LTS
> GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
> CMake version: version 3.5.1
> 
> Python version: 3.5
> Is CUDA available: Yes
> CUDA runtime version: 10.0.130
> GPU models and configuration: GPU 0: GeForce RTX 2080
> Nvidia driver version: 410.79
> cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1
> 
> Versions of relevant libraries:
> [pip3] numpy==1.14.5
> [pip3] torch==1.0.1.post2
> [pip3] torchvision==0.2.2.post3

and the model is forwarded in multi thread.

**Comment by olyaromanyuk** [comment]
@ezyang I was not training a lot with pytorch lately, so the last time I encountered the issue was around the date of the post, so the version info might be outdated, but CUDA and driver were definitely the same as @hitlk .
Card were different, I work with 4 GTX 1080 ti.
I had pytorch installed for my user on Ubuntu, another user on the same machine had his own installation

**Comment by ezyang** [comment]
Can either of you please paste the output of `pip list`?

**Comment by hitlk** [comment]
```
absl-py              0.7.0
astor                0.7.1
chardet              2.3.0
Cython               0.29.5
easydict             1.9
gast                 0.2.2
grpcio               1.18.0
h5py                 2.9.0
Keras-Applications   1.0.7
Keras-Preprocessing  1.0.9
Markdown             3.0.1
mock                 2.0.0
numpy                1.14.5
opencv-python        4.0.0.21
pbr                  5.1.2
Pillow               5.4.1
pip                  19.0.3
protobuf             3.6.1
pycurl               7.43.0
pygobject            3.20.0
pytesseract          0.2.6
python-apt           1.1.0b1+ubuntu0.16.4.2
PyYAML               3.13
requests             2.9.1
setuptools           39.1.0
six                  1.12.0
ssh-import-id        5.5
tensorboard          1.13.1
tensorflow-estimator 1.13.0
tensorflow-gpu       1.13.1
termcolor            1.1.0
torch                1.0.1.post2
torchvision          0.2.2.post3
ujson                1.35
urllib3              1.13.1
Werkzeug             0.14.1
wheel                0.29.0
```

**Comment by laggui** [comment]
Hi,
I am having the same issue as OP trying to run the same object detection task (on different inputs) in two worker threads, with only one GPU.

Currently working with pytorch 1.0.1 and cuda 9.0.

**Comment by skyoung** [comment]
same problem when running multi-threads with each thread only one GPU. I am using pytorch0.4.1 and cuda9

**Comment by senhuiguo** [comment]
same here, pytorch1.0.1 cuda9.0

**Comment by ezyang** [comment]
@senhuiguo I agree with this workaround, manually forcing CUDA to initialize should help solve this problem. I am not sure what the root cause of the issue is.

**Comment by npyoung** [comment]
Still an issue with 1.1.0-cuda10. Pre-initializing CUDA in the main thread mitigates the issue, but it's messy.

**Comment by soumith** [comment]
does anyone on this thread have a snippet that reproduces the issue? we can start looking

**Comment by senhuiguo** [comment]
@soumith Here you go
```python
import torch
import threading

def worker(rank):
    torch.tensor([1.]).cuda(rank)

# to fix the isuue, uncomment the following
# torch.tensor([1.]).cuda(0)
# torch.tensor([1.]).cuda(1)


t1 = threading.Thread(target=worker, args=(0,))
t2 = threading.Thread(target=worker, args=(1,))
t1.start()
t2.start()
```

**Comment by soumith** [comment]
@senhuiguo i am on ubuntu 16.04 with pytorch 1.1.0 binaries, and I cannot reproduce with your snippet.

```
In [2]: print(torch.__config__.show())
PyTorch built with:
  - GCC 4.9
  - Intel(R) Math Kernel Library Version 2019.0.3 Product Build 20190125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20)
  - OpenMP 201307 (a.k.a. OpenMP 4.0)
  - NNPACK is enabled
  - CUDA Runtime 9.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.5.1
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=  -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=True, USE_NNPACK=True, USE_OPENMP=ON,

```

Any additional hints about your environment?

**Comment by senhuiguo** [comment]
@soumith 
```
In [1]: import torch 
   ...: import threading 
   ...:  
   ...: def worker(rank): 
   ...:     torch.tensor([1.]).cuda(rank) 
   ...:  
   ...: # to fix the isuue, uncomment the following 
   ...: # torch.tensor([1.]).cuda(0) 
   ...: # torch.tensor([1.]).cuda(1) 
   ...:  
   ...:  
   ...: t1 = threading.Thread(target=worker, args=(0,)) 
   ...: t2 = threading.Thread(target=worker, args=(1,)) 
   ...: t1.start() 
   ...: t2.start() 
   ...:                                                                                                                               

Exception in thread Thread-51:
Traceback (most recent call last):
  File "/mnt/lustre/guosenhui/anaconda3/envs/mixed3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/mnt/lustre/guosenhui/anaconda3/envs/mixed3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-e07912d6ffaf>", line 5, in worker
    torch.tensor([1.]).cuda(rank)
  File "/mnt/lustre/guosenhui/anaconda3/envs/mixed3.7/lib/python3.7/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: generic_type: cannot initialize type "_CudaDeviceProperties": an object with that name is already defined

In [2]: print(torch.__config__.show())                                                                                                
PyTorch built with:
  - GCC 4.9
  - Intel(R) Math Kernel Library Version 2019.0.3 Product Build 20190125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20)
  - OpenMP 201307 (a.k.a. OpenMP 4.0)
  - NNPACK is enabled
  - CUDA Runtime 9.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.5.1
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=  -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=True, USE_NNPACK=True, USE_OPENMP=ON,
```

**Comment by soumith** [comment]
@senhuiguo what OS are you on, and what NVIDIA driver? I will atleast try a repro on docker

**Comment by senhuiguo** [comment]
@soumith CentOS Linux release 7.2.1511 (Core), Driver version: 384.90

**Comment by Usama-Zafar** [comment]
I am getting the same issue. Seem like if you try to create a CUDA tensor in a thread it produces this error.

**Comment by ehion** [comment]
Get the same issue when i use multi-threads with one thread in one gpu

**Comment by agiokas-dbg** [comment]
I am getting the same issue, at random internals.
- ubuntu 18.04
- python 3.6.8
- pytorch 1.2.0
- Driver Version: 418.87.00 
- CUDA Version: 10.1
- libcudnn.so.7.6.3
It seems to be related to threading/workers IMHO, because I have a custom Dataloader, which when I use concurrent futures or threads (or forks) I get this error. The one instance where I run a single thread which loads images from disk and uploads them to the GPU I did not get this error (in repeat tests).

**Comment by agiokas-dbg** [comment]
Furthermore proof that this is thread-related (at least in my case) is that when I try the following:

```python
    futures = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=12) as executor:
        for i in range(len(self.images)):
            file        = self.images[i]
            (co, label) = self.labels[i]
            idx         = self.index.index((co,label))
            future = executor.submit(self.__load__, (file, idx, label_size))
            futures.append(future)
    for f in futures:
       # wait for all futures in order to capture results
       # do something with f.result()
       # which essentially contains the (t_in, t_out) placed in GPU MEM
```

The above is part of my custom dataloader procedure.
The below is the actual load iteration

```python
def __load__(self, args):
        (file, idx, out_size) = args
        image = Image.open(file).convert('RGB')
        t_out       = torch.zeros((out_size,), dtype=torch.long)
        t_out[idx]  = 1
        t_in        = self.tf(image)
        return (t_in.cuda().float(), t_out.cuda().long())
```

This behaviour is triggered. I would assume that the thread context copying the tensors is having synchronisation issues? As soon as the above code is removed and executed only within the main thread, the behaviour disappears. Bear in mind I have prior to all this, done the:

```python
use_cuda = torch.cuda.is_available()
assert use_cuda == True
device = torch.device("cuda:0")
```

**Comment by ezyang** [comment]
I'm able to repro the issue with @senhuiguo's example. Debugging.

**Comment by ezyang** [comment]
OK, it is indeed a race. This diff, for example, "fixes" it:
```
diff --git a/torch/cuda/__init__.py b/torch/cuda/__init__.py
index 411cfb7315..5abb645fc5 100644
--- a/torch/cuda/__init__.py
+++ b/torch/cuda/__init__.py
@@ -165,6 +165,7 @@ def _lazy_init():
     global _initialized, _cudart, _original_pid, _queued_calls
     if _initialized:
         return
+    _initialized = True
     if _in_bad_fork:
         from sys import version_info
         if version_info < (3, 4):
@@ -181,7 +182,6 @@ def _lazy_init():
     _cudart.cudaGetErrorName.restype = ctypes.c_char_p
     _cudart.cudaGetErrorString.restype = ctypes.c_char_p
     _original_pid = os.getpid()
-    _initialized = True
     # Important to do this after _initialized, since some queued calls
     # may themselves call _lazy_init()
     for queued_call, orig_traceback in _queued_calls:
```

If you look at the relevant segment:

```
    torch._C._cuda_init()
    _cudart = _load_cudart()
    _cudart.cudaGetErrorName.restype = ctypes.c_char_p
    _cudart.cudaGetErrorString.restype = ctypes.c_char_p
    _original_pid = os.getpid()
    _initialized = True
```

The problem is that `_cuda_init` release the GIL at some point, which means that another Python thread can come in and trigger the same initialization (we aren't protected against the lock until we set `_initialized = True`.

**Comment by Santhosh1509** [comment]
System Info:
OS: Windows 10
GPU: 1050ti
RAM: 16GB
CUDA: 9.0

Here's the pip list

> Package               Version
> --------------------- -----------
> attrs                 19.1.0
> awscli                1.16.193
> backcall              0.1.0
> bleach                3.1.0
> boto3                 1.9.183
> botocore              1.12.183
> certifi               2019.6.16
> chardet               3.0.4
> Click                 7.0
> colorama              0.3.9
> cycler                0.10.0
> Cython                0.29.11
> decorator             4.4.0
> defusedxml            0.6.0
> docutils              0.14
> entrypoints           0.3
> ffmpeg-python         0.2.0
> Flask                 1.1.0
> Flask-SQLAlchemy      2.4.0
> future                0.17.1
> idna                  2.8
> ipykernel             5.1.1
> ipython               7.6.1
> ipython-genutils      0.2.0
> ipywidgets            7.5.0
> itsdangerous          1.1.0
> jedi                  0.14.0
> Jinja2                2.10.1
> jmespath              0.9.4
> joblib                0.13.2
> jsonschema            3.0.1
> jupyter               1.0.0
> jupyter-client        5.2.4
> jupyter-console       6.0.0
> jupyter-core          4.5.0
> kiwisolver            1.1.0
> lxml                  4.4.1
> MarkupSafe            1.1.1
> matplotlib            3.1.1
> mistune               0.8.4
> nbconvert             5.5.0
> nbformat              4.4.0
> notebook              5.7.8
> numpy                 1.16.4
> object-detection      0.1
> opencv-contrib-python 4.1.0.25
> opencv-python         4.1.0.25
> pandas                0.24.2
> pandocfilters         1.4.2
> parso                 0.5.0
> pickleshare           0.7.5
> Pillow                6.1.0
> pip                   19.2.1
> prometheus-client     0.7.1
> prompt-toolkit        2.0.9
> pyasn1                0.4.5
> Pygments              2.4.2
> pyparsing             2.4.0
> PyQt5                 5.13.0
> PyQt5-sip             4.19.18
> pyrsistent            0.15.2
> python-dateutil       2.8.0
> pytz                  2019.1
> pywinpty              0.5.5
> PyYAML                5.1
> pyzmq                 18.0.2
> qtconsole             4.5.1
> requests              2.22.0
> rsa                   3.4.2
> s3transfer            0.2.1
> scikit-learn          0.21.3
> scipy                 1.3.0
> Send2Trash            1.5.0
> setuptools            41.0.1
> Shapely               1.6.4.post2
> six                   1.12.0
> SQLAlchemy            1.3.5
> terminado             0.8.2
> testpath              0.4.2
> torch                 1.1.0
> torchvision           0.3.0
> tornado               6.0.3
> traitlets             4.3.2
> ubidots               1.6.6
> urllib3               1.25.3
> wcwidth               0.1.7
> webencodings          0.5.1
> Werkzeug              0.15.4
> wheel                 0.33.4
> widgetsnbextension    3.5.0

I have same issue

Using same Yolo V3 in two different files, trying to run them on the same GPU at once

[file](https://github.com/ayooshkathuria/pytorch-yolo-v3/blob/master/video_demo.py)

file 1: called `thread1` which contains a main function `main1()`
file 2: called `thread2` which contains a main function `main2()`

Here's the code to run both these files at the same time using threads
```
from threading import Thread

from threads1 import main1
from threads2 import main2

t1 = Thread(target = main1,name='t1')
t2 = Thread(target = main2,name='t2')

t1.start()
t2.start()

t1.join()
t2.join()
```

I get this error

> 
> C:\Users\Plato\Envs\vt\lib\site-packages\sklearn\utils\linear_assignment_.py:21: DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
>   DeprecationWarning)
> Loading network.....
> Loading network.....
> Network successfully loaded
> Network successfully loaded
> Exception in thread t1:
> Traceback (most recent call last):
>   File "C:\Users\Plato\AppData\Local\Programs\Python\Python37\Lib\threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "C:\Users\Plato\AppData\Local\Programs\Python\Python37\Lib\threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\vt\threads.py", line 722, in main1
>     model.cuda()
>   File "C:\Users\Plato\Envs\vtlib\site-packages\torch\nn\modules\module.py", line 265, in cuda
>     return self._apply(lambda t: t.cuda(device))
>   File "C:\Users\Plato\Envs\vt\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
>     module._apply(fn)
>   File "C:\Users\Plato\Envs\vt\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
>     module._apply(fn)
>   File "C:\Users\Plato\Envs\vt\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
>     module._apply(fn)
>   File "C:\Users\Plato\Envs\vt\lib\site-packages\torch\nn\modules\module.py", line 199, in _apply
>     param.data = fn(param.data)
>   File "C:\Users\Plato\Envs\vt\lib\site-packages\torch\nn\modules\module.py", line 265, in <lambda>
>     return self._apply(lambda t: t.cuda(device))
>   File "C:\Users\Plato\Envs\vt\lib\site-packages\torch\cuda\__init__.py", line 163, in _lazy_init
>     torch._C._cuda_init()
> RuntimeError: generic_type: cannot initialize type "_CudaDeviceProperties": an object with that name is already defined

Then only the `thread2` starts and completes it's task. `thread1` doesn't get completed

Please help

Where and what changes should I make for both `thread1` and `thread2` to start together?

**Comment by ezyang** [comment]
@olyaromanyuk This issue was recently fixed on master. Please try downloading a nightly (or apply the PR to your PyTorch copy; it's a Python only change) and see if that fixes the problem. If not, please file a new issue.

**Comment by Santhosh1509** [comment]
@ezyang I don't see any nightly build for Windows here [torch_nightly](https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html)

Can only find [torch_stable](https://download.pytorch.org/whl/torch_stable.html) for Windows.

Could you please let me know which file I have look into to set `_initialized = True`?

**Comment by ezyang** [comment]
It looks like there might be a problem with the Windows pip nightlies, cc @peterjc123 

Conda nightlies are working https://anaconda.org/pytorch-nightly/pytorch/files

**Comment by peterjc123** [comment]
@Santhosh1509 The CUDA 9.2 binaries are not generated because CUDA 9,2 is not correctly installed on the agents and we don't have direct access to these machines. We have to wait for the upstream to fix this.

**Comment by Santhosh1509** [comment]
@ezyang and @peterjc123 Okay
So have the changes mentioned here also been made to `CUDA 9` version of pytorch in `nightly`?
Just to be clear if i do `conda install pytorch cudatoolkit=9.0 -c pytorch-nightly`  will it solve my issue?

**Comment by Santhosh1509** [comment]
Found a work around for parallel processing.

Due to `GIL (Global Interpreter Lock)` only one threads runs by default at any given time in python. 

Had posted an issue [threads not able to reduce the run time of two function when run at once](https://stackoverflow.com/questions/58005044/threads-not-able-to-reduce-the-run-time-of-two-function-when-run-at-once)

This work around seems to do the job run two processes parallel

Here's the code
```
from threads import main1
from threads1 import main2

import time
from concurrent.futures import ProcessPoolExecutor

def run_in_parallel():
    with ProcessPoolExecutor(max_workers=2) as pool:
        start = time.time()
        fut1 = pool.submit(main1)
        fut2 = pool.submit(main2)
        for fut in (fut1, fut2):
            print(fut.result())
        end = time.time()
        print(f'[Parallel] Took {end-start} seconds')

if __name__ == '__main__':
	run_in_parallel()
```
