### ISSUE TITLE
Apply for translation of the Chinese version, I hope to get authorization!

### ISSUE THREAD

**Issue by jiangzhonglian** [pytorch/pytorch#16550]
## 📚 Documentation

---

I am a fan of pytorch in China.
The purpose of our visit is very simple, apply for translation of the Chinese version, I hope to get the relevant authorization!
(Sorry: the official website did not find your email)

There are several reasons:
1. The English level of many Chinese users is not very good.
2. Network problems, you know (China's magic network)!
3. Online blogs are very messy.

We are [ApacheCN](http://www.apachecn.org), China's open source small organization, and hope to do some translation to help more people learn, our website:  <http://www.apachecn.org>

We have previously translated pytorch:  <https://pytorch.apachecn.org>
If you like, we will continue to help translate the Chinese version of pytorch.

**Comment by wizardforcel** [comment]
In addition: 

It's better that the official can hold translation activities (just like TensorFlow), but we users can also hold one instead if there is no one.

We sincerely hope that our effort can be merged into the official, because it helps to improve this translation and reduce duplicated effort.

**Comment by yf225** [comment]
@jiangzhonglian @wizardforcel Thanks a lot for the proposal and it's also on our internal agenda to discuss the potential collaboration plan this week. We will provide an update on this very soon.

cc @soumith @jspisak

**Comment by jspisak** [comment]
@jiangzhonglian  @wizardforcel thanks so much for this!!! As Will mentioned, we are discussing internally to see if we can get some level of 'official' localization for a Chinese version of pytorch.org. We will definitely be in touch and love to see PyTorch alive and well in China!!

**Comment by jiangzhonglian** [comment]
We are very happy to do this meaningful thing.
We have iterated three Chinese versions, and we are very grateful to the translation and participation of many Chinese contributors. Of course, the most should be the pytorch tutorial, which really helps us to learn more comprehensive and systematic learning of deep learning.
Everyone said that they really like your framework and your team. This is why we have been insisting on translation.
