### ISSUE TITLE
documentation bug for conv2d and conv3d

### ISSUE THREAD

**Issue by zadeck** [pytorch/pytorch#16561]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
documentation bug
Provide a short description.
i believe that the pad parameter description for the multidimensional convolutions are wrong.
it says that the padding is put in as "padh, padw".   I believe that it is really "padw, padh".
This mistake is consistently made for conv2d and conv3d for both nn and functional.
## Code example
not relevant
Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS:linux
- PyTorch version:1
- Python version:3.6
- CUDA/cuDNN version:10
- GPU models and configuration:
- GCC version (if compiling from source):7.3
- CMake version: not relevant
- Versions of any other relevant libraries:
not relevant

**Comment by zadeck** [comment]
please ignore this report, i read it incorrectly.

**Comment by vishwakftw** [comment]
Please close it, if you feel there is no issue to be reported.

**Comment by albanD** [comment]
Closing as this is not an issue.
