### ISSUE TITLE
High scope of error in how view() may be used

### ISSUE THREAD

**Issue by ParticularlyPythonicBS** [pytorch/pytorch#16560]
## 📚 Documentation

[torch.Tensor.view](
https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view) does not work as naively expected since the ordering of the data in memory is not changed in its use. There is a good chance of users confusing its use with that of [torch.transpose](https://pytorch.org/docs/stable/torch.html#torch.transpose)

A cautionary warning about this along with a link to torch.transpose should fix the issue.

**Comment by albanD** [comment]
`view()` is the same as `reshape`, which is the same as [numpy's reshape](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html).

If you feel that more examples should be added to the doc, we will accept PR for that.

**Comment by ParticularlyPythonicBS** [comment]
Hi,
I have submitted a PR adding another example to `view()`
[16563](https://github.com/pytorch/pytorch/pull/16563)
