### ISSUE TITLE
GPUs crashed when running more than one parallel training processes on the same bunch of GPUs

### ISSUE THREAD

**Issue by dontloo** [pytorch/pytorch#1656]
I accidentally ran two parallel training processes on the same bunch of GPUs, then those GPUs stopped responding and I could not `sudo kill` the training processes neither. How can I solve this? 

Many thanks.

Here's the result from `nvidia-smi`, as it shows GPU 2 and 3 (which I ran the training processes on) are of 100% usage and I was not able to terminate the processes.
![screenshot from 2017-07-31 18 02 09](https://user-images.githubusercontent.com/4488555/28774061-86cc7e42-761e-11e7-8f3d-b931f118bb75.png)

**Comment by zou3519** [comment]
You should try not to launch multiple DataParallel jobs on the same GPUs, there are some quirks with the libraries that we use that may cause the GPUs to hang in that case: https://discuss.pytorch.org/t/run-two-different-jobs-in-parallel-on-same-gpus-i-got-my-gpu-locked-up/1232/2

**Comment by apaszke** [comment]
As @zou3519 mentioned it's a problem with NVIDIA's NCCL library that we can't do anything about
