### ISSUE TITLE
Why is `torch.mean()`  so different from `numpy.average()`?

### ISSUE THREAD

**Issue by themightyoarfish** [pytorch/pytorch#16569]
## 🐛 Bug

Maybe again not a bug, but something that surprises me. I have this matrix [here](https://www.dropbox.com/s/fpj3hbalo0js5aa/X.npy?dl=0) and I'm trying to subtract the mean over the columns from each column. The result is that there is a substantial difference in the averages computed by PyTorch and by Numpy, leading to different result, which bites me further down my processing. The difference between the results is up to `0.03742431712057442`, which is a lot in a matrix that consists of number < `0.05`.

## To Reproduce

```
import numpy as np
import torch

X = np.load('X.npy')
avg_np, _ = np.average(X, axis=1, returned=True)

X_th = torch.tensor(X)
avg_th = torch.mean(X_th, dim=1)

assert (X == X_th.numpy()).all()
# assert (avg_np == avg_th.numpy()).all()   # this fails alread

X -= avg_np[:, None]
X_th -= avg_th[:, None]

different = np.abs(X[X != X_th.numpy()])
print(different.max())
```

## Expected behavior

Same result as numpy.

## Environment
```
Collecting environment information...
PyTorch version: 1.1.0a0+fb68d81
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 8.1.0-5ubuntu1~16.04) 8.1.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 396.37
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.2.1
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.4.2
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] magma-cuda90              2.3.0                         1    pytorch
[conda] mkl                       2019.1                      144
[conda] mkl-include               2018.0.3                      1
[conda] mkl_fft                   1.0.10           py36ha843d7b_0
[conda] mkl_random                1.0.1            py36h629b387_0
[conda] torch                     1.1.0a0+fb68d81           <pip>
[conda] torchvision               0.2.1                     <pip>
```
## Additional context

Is there some floating point weirdness going on? I understand that operations in CUDA might give different results, but I am running this on the CPU where I would expect float math to work the same. All datatype are float64 here.

**Comment by albanD** [comment]
Hi,

Please use the [forum](https://discuss.pytorch.org/) to ask questions.

By running your script using float32 (changed the np.load by torch.rand(1, 100).numpy()), the difference between the two mean (the asser that fails) is actually 1e-8 which is below the precision of float.
The final value that you print is very large as you print the largest entry of X for which X and X_th are different. If you print the sum of the absolute difference between the two Tensors, you get something like 1e-6 (for an input tensor containing 100 elements) which is as well at the level of precision for floats.

By running you script using float64 (replacing the load with torch.rand(1, 100).double().numpy()), the the differences get to 0. I'm sure with big enough Tensors you can get a non-zero difference but that should still be very small.

**Comment by themightyoarfish** [comment]
What do you mean with "1e-8 is below the precision of float"? It's clearly a value much larger than the smallest positive 32-bit float. Sure you can lose precision through calculations, but is this magnitude really expected?

**Comment by fmassa** [comment]
@themightyoarfish floating point math is not 100% accurate, and is neither associative nor commutative.

Here is an example using numpy, where I perform the same operations in different order, and the results are slightly different:

```python
np.random.seed(2)
a = np.random.rand(1, 10000).astype('float32')
d = a.mean() - np.ascontiguousarray(a.reshape(50, 5, 40).transpose((1, 0, 2))).mean()

print(d)

# gives -5.9604645e-08
```

**Comment by DanielAtKrypton** [comment]
@themightyoarfish, I developed a [pytorch_math](https://github.com/DanielAtKrypton/pytorch_math) package that bridges the difference gap. See usage example [here](https://github.com/DanielAtKrypton/pytorch_math/blob/master/tests/average_test.py#L58).

**Comment by dansontong** [comment]
i get this error when I use torch.tensor( list_var ), 
reason: the item's shape in the list is not consitent.
