### ISSUE TITLE
Error on backward pass with sparse matmul with transposed tensor

### ISSUE THREAD

**Issue by klicperajo** [pytorch/pytorch#16562]
## 🐛 Bug

Doing backpropagation on `torch.sparse.mm(sp_mat, mat.t())` gives the error `RuntimeError: Expected object of backend CPU but got backend SparseCPU for argument #2 'mat2'` (or the same with CUDA instead of CPU).

## To Reproduce

Run the following code:

    sp_mat = torch.sparse.FloatTensor(
            torch.LongTensor([[0, 0, 1], [0, 1, 2]]),
            torch.FloatTensor([1, 2, 3]),
            torch.Size([3, 3]))
    mat = torch.nn.Parameter(torch.ones(3, 3))
    res = torch.sparse.mm(sp_mat, mat.t())
    print(res)
    res.sum().backward()

This will work when changing `mat.t()` to `mat`.

## Expected behavior

Working backpropagation.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.0
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): -
 - Python version: 3.6

**Comment by gchanan** [comment]
confirmed this is a bug on master.

**Comment by vadimkantorov** [comment]
Maybe a similar issue:
```python
import torch

a = torch.rand(2, 3, 4)
b = torch.rand(4, 6)
b_ = b.to_sparse()

c = torch.matmul(a, b)
# torch.Size([2, 3, 6])

c_ = torch.matmul(b.t(), a.flatten(end_dim = 1).t()).view(-1, *a.shape[:2]).permute(1, 2, 0)
print(torch.eq(c, c_).all()) # 1

#print(torch.matmul(a, b_).shape)
# RuntimeError: Expected object of backend CPU but got backend SparseCPU for argument #2 'mat2'
```

**Comment by klicperajo** [comment]
In your first error you're doing a regular matmul with a sparse tensor. That won't work, use `torch.sparse.mm` instead.

The second error is because you are transposing a sparse tensor, which hasn't been implemented. There are very few methods that work with sparse tensors. Please refer to the [documentation](https://pytorch.org/docs/stable/sparse.html) for an overview.

Both errors are unrelated to the bug I've reported.

**Comment by danieleds** [comment]
Any Milestone for this bug? Thanks

**Comment by soumith** [comment]
cc: @gchanan

**Comment by umanwizard** [comment]
I think I figured out what is causing this, if so will put up a PR to fix it today
