### ISSUE TITLE
Add ability to select default device (run always on GPU or always on CPU)

### ISSUE THREAD

**Issue by themightyoarfish** [pytorch/pytorch#16564]
## 🚀 Feature
It would be useful for a current usecase to have an API like this
```
torch.set_default_device('cuda:0')
```
or something similar, so I don't have to call `.cuda()` on everything and pass `device=torch.cuda.current_device()` to functions which generate a tensor.

## Motivation

I currently have some code that I want portable between NumPy and PyTorch in which I attempt to detect the argument type (if `np.ndarray`, dispatch to numpy version, if `torch.Tensor` use PyTorch). However, If I want to run on the GPU, I have to pass the `device` keyword param to many functions (e.g. `eye`). Now this is difficult to do if you don't know if the function that is being called uses this parameter or not.

**Comment by apaszke** [comment]
This has been discussed multiple times in our issue tracker, and we don't think it's a good idea. Tensors that don't live on CPU have different performance characteristics (e.g. taking elements out one by one will be *extremely* slow), so we'd rather have people be aware of where their array live. If you really want to use CUDA everywhere, you can just hardcode that in your script.
