### ISSUE TITLE
Make it possible to use mypy to typecheck code that uses PyTorch

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#16574]
We generated a type stub for `torch` module in , which is good enough to get autocomplete working in PyCharm. However, the type stub is not that well tested for actually, you know, accurately reflecting the types of our functions (we have light testing, but it's not enough) and it's unlikely that it's actually good enough to actually use mypy to typecheck PyTorch-using code. It seems like this is something that people might be interested in, so I'm creating this issue to track. Please emoji if this is something that you would use.

cc @ezyang @gchanan @zou3519

**Comment by rsokl** [comment]
Is there an emoji for "please god make this available a year ago?"

**Comment by t-vi** [comment]
@rsokl: That means you will do it or you will pay for it?

**Comment by gchanan** [comment]
We probably want to wait for python 2 to go away.

**Comment by zou3519** [comment]
Is there a reason why we didn't mark this issue as "triaged" after removing "triage review"?

**Comment by csvoss** [comment]
Hiya @ezyang! I want to contribute towards this feature.

I've read [CONTRIBUTING.md](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md) and [contribution_guide.rst](https://github.com/pytorch/pytorch/blob/master/docs/source/community/contribution_guide.rst).

Some questions for context on this particular issue – my read of the progress made in https://github.com/pytorch/pytorch/pull/19089 is that while we've considered autogenerating stubs using tools like `gen_pyi.py`, we ultimately settled on simply writing `.pyi` files and keeping them up to date. Is that correct?

Second question – if the above is true, do we have any means of enforcing that the `.pyi` files stay up-to-date with the `.py` files (say, using tests in CI), or would a PR that fixes this issue also need to enforce that property going forwards (by adding more tests to the CI suite)?

**Comment by csvoss** [comment]
It also seems that we're deprioritizing this until Python 2 goes away, but if it's all the same to folks, I'd be interested in doing the work anyways (even if that means adding annotations to Python 2-related code that is soon-to-be-removed.)

**Comment by csvoss** [comment]
> Second question – if the above is true, do we have any means of enforcing that the .pyi files stay up-to-date with the .py files (say, using tests in CI), or would a PR that fixes this issue also need to enforce that property going forwards (by adding more tests to the CI suite)?

I found [`pytorch/test_type_hints.py`](https://github.com/pytorch/pytorch/blob/59b14a762094825613ab061e4ff96586555d15ee/test/test_type_hints.py), I'll see where that leads me.

**Comment by ezyang** [comment]
Hey @csvoss, nice to see a familiar face :)

Here's my personal thinking on the matter. I've worked on a few (smaller than PyTorch) codebases with Python type checking, and the primary way we keep the type annotations correct in these settings is to actually typecheck all of the code in our codebase that uses the types, so you can check both inside and outside the function are consistent with your annotation. So, in the long term, that's the approach I'd want to take for typing PyTorch's external API--eating your own dogfood and all that.

I'm not a mypy expert, so I don't know how doable it is to do this plan with stub files. I do know if I wrote all of the type annotations inline, I could just run mypy and have it take care of the rest, and so the act of refining all of our types would also be the same project as making PyTorch codebase statically typed. Switching to Python 3 only helps a lot, because we can slowly start moving annotations inline to Python code (since annotating Python code also causes it to be typechecked by mypy). In principle we could do this prior to Python 3, using Python 2 annotation syntax, but this would cause a lot of churn in the two months we have left before Python 2 dies... doesn't seem worth it.

But I agree with you that there is some useful legwork we can do before hand, which is to try to make our stubs more useful. The key is to have a corpus of program to typecheck against the stubs. The way `test_type_hints.py` works is it slurps up all of the example programs in our docstrings and then runs mypy on it (against our stubs). That's fine, but there's also a lot of missing coverage. We could add more programs, but I'm not too sure how to structure this. Maybe a good start would be to typecheck all of our tutorials and make sure they typecheck. Getting this all setup in our CI may be quite involved though.

I'm always happy to accept patches that make types better, even if there is no testing for it. So you could push for that. But what would give us more leverage in the long term is figuring out a good testing strategy, e.g., laying the groundwork for typechecking all of pytorch with mypy. But I have no illusions about how much work this would be, so maybe patches to make types better is the right thing for now.

**Comment by henribru** [comment]
There are some functions and methods in Pytorch where the return type depends on the value of an argument. An example is `nonzero` with its `as_tuple` argument. Contrary to this comment in `__init.pyi.in`, these functions can actually be typed correctly:
```
# The return value of this function depends on the value of `as_tuple`,
# (similar to `unique`, `lu`, etc.); as such, it is not
# possible to type correctly
def nonzero(input: Tensor, *, out: Optional[Tensor]=None, as_tuple: Optional[_bool]=None): ...
```
This requires a combination of overloads and the `Literal` type. Unfortunately it doesn't exist in the stdlib until 3.8, but it is included in the `typing-extensions` package. Would including a dependency on `typing-extensions` in addition to `typing` be acceptable?

**Comment by ezyang** [comment]
I personally think `typing-extensions` is OK, but we'll have to update the packaging if/when we add it.

**Comment by ethanjyx** [comment]
now that Python 2 has gone away, shall we start to prioritize this? :) we would highly benefit from this

**Comment by ezyang** [comment]
Yes, though this is blocked on killing some FB internal users of Python 2 before we can move this repository onwards.

**Comment by ethanjyx** [comment]
@ezyang @rgommers glad seeing a PR! and saw in the news today that pytorch 1.5 will drop python 2 support, so very excited about the great progress here.

wondering is there a plan for having the mypy support, what happens after the PR merges above?

**Comment by ezyang** [comment]
Once we land Ralf's PR, we then will begin the process of inlining the pyi definitions into the py files and making the PyTorch codebase itself typecheckable. There will be a lot to do, and we're probably going to run some fixathon for it once we work out the basic playbook.

**Comment by ntenenz** [comment]
@ezyang, thoughts on a PyTorch equivalent of [this](https://github.com/tensorflow/community/blob/master/rfcs/20200211-tf-types.md)?  Even a basic impl such as the one found in the [tf-addons repo](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/utils/types.py) may make for a smoother transition to inlined type hints, especially with the ever-present `Union[str, torch.device]`, etc.

**Comment by ezyang** [comment]
Well, I have zero objections to a `torch.types` module, in principle (in other projects I've done with types, having a types module has been handy). And it is true that generally you want to reduce the dependency a types modules has, so that it can be included anywhere.

That being said, I'm less clear about how you would go about putting the `Tensor` type in `torch.types`, since it has a lot of methods that we generate automatically via a type hinting script. The TF proposal proposes doing this using abstract base classes, but I think there would be technical difficulties with actually doing this in PyTorch, since our classes are bound from Python C API. Someone will have to look into this. BTW, the `tf-addons` script is a lot more practical, and we should definitely consider just putting these definitions directly in the relevant modules (to avoid having to deal with circular dependencies.)

**Comment by rgommers** [comment]
gh-37594 (for review, input very welcome) contains documentation on where we want to end up and how to start improving the type annotations for a module. 

When that PR is merged I plan to add a large checklist here as a tracking issue that people can assign to themselves and check off when done. That seems better than one issue per module, that'd be too noisy and a lot of overhead (some modules can be fixed very quickly).

**Comment by rgommers** [comment]
> a PyTorch equivalent of [this](https://github.com/tensorflow/community/blob/master/rfcs/20200211-tf-types.md)? Even a basic impl such as the one found in the [tf-addons repo](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/utils/types.py) may make for a smoother transition to inlined type hints, especially with the ever-present `Union[str, torch.device]`, etc.

The basic implementation seems useful - those are all unions that are probably needed in other places. The proposal goes a little overboard it looks like to me - things that are objects in the API should mostly be defined inline (like `Tensor`) I'd think. We do need a `TensorLike` like that add-on has.

And minor suggestion: call the module `annotations` rather than `types`. `types` is a stdlib module, and shadowing that isn't the best style usually.

**Comment by ntenenz** [comment]
Fully onboard with the "simpler" solution. I find myself repeatedly creating `DeviceLike`, etc. aliases across projects, so having a single, definitive source of truth would make life easier, especially with 3rd party packages.

**Comment by EricCousineau-TRI** [comment]
Possibly related: Discussion in NumPy about type hints (PEP 484):
https://github.com/numpy/numpy/issues/7370

**Comment by rgommers** [comment]
Here's a summary of the current status:
- mypy currently runs on ~1150 files
- there's 59 `ignore_errors = True` left for modules. Most of those are for `caffe2`, for private modules, or have open PRs to remove the ignores. The main exception is some `nn.modules` submodules. Should be feasible to get through all of those (except `caffe2`, we decided not to bother with those) for the 1.8 release.
- The main issue after that is how to make sure that the annotations are actually correct. Mypy won't catch errors unless the code is exercised. Probably the best way to do that is to make mypy run on test files. Those also contain lots of errors that need fixing, but after that there should be decent coverage, which will prevent a continuous drip of little issues being opened.

**Comment by rgommers** [comment]
> The main issue after that is how to make sure that the annotations are actually correct. Mypy won't catch errors unless the code is exercised. Probably the best way to do that is to make mypy run on test files. Those also contain lots of errors that need fixing, but after that there should be decent coverage, which will prevent a continuous drip of little issues being opened.

@guilhermeleobas suggested using [Typeguard](https://typeguard.readthedocs.io/en/latest/index.html); Numba is apparently using it successfully to verify their annotations. This would use the import hook method and run only as an optional test dependency in some CI jobs - see https://github.com/numba/numba/pull/6458.

If it can be made to work, that's probably more effective than running mypy over the test files, and a lot less work (there's a ton of mypy errors in test files that take time to resolve).

**Comment by rgommers** [comment]
There's another testing approach that should be cleaned up. Currently there are a few dedicated typing tests in `test/type_hint_tests/`, but they're not very useful (they're untyped Python code that won't catch all types of problems) and the one-snippet-per-python-file makes little sense.

Instead, we can adopt what NumPy does. It has a way to write a lot of typing tests very compactly in this format:
```
reveal_type(np.ravel(A))  # E: numpy.ndarray[Any, Any]
reveal_type(np.ravel(B))  # E: numpy.ndarray[Any, Any]
reveal_type(np.nonzero(a))  # E: tuple[numpy.ndarray[Any, Any]]
```
Machinery for it to recognize the `# E:` expected mypy output format is at https://github.com/numpy/numpy/blob/master/numpy/typing/tests/test_typing.py

This will be especially useful for adding good tests for APIs that have more static typing complexity, e.g. multiple overloads, or the `nn.Module.forward` machinery.

**Comment by guilhermeleobas** [comment]
> Instead, we can adopt what NumPy does. It has a way to write a lot of typing tests very compactly in this format:
> 
> ```
> reveal_type(np.ravel(A))  # E: numpy.ndarray[Any, Any]
> reveal_type(np.ravel(B))  # E: numpy.ndarray[Any, Any]
> reveal_type(np.nonzero(a))  # E: tuple[numpy.ndarray[Any, Any]]
> ```
> 
> Machinery for it to recognize the `# E:` expected mypy output format is at https://github.com/numpy/numpy/blob/master/numpy/typing/tests/test_typing.py
> 
> This will be especially useful for adding good tests for APIs that have more static typing complexity, e.g. multiple overloads, or the `nn.Module.forward` machinery.

I've send https://github.com/pytorch/pytorch/pull/52408 porting NumPy `test_typing.py` to PyTorch.

**Comment by rgommers** [comment]
> The main issue after that is how to make sure that the annotations are actually correct.

After gh-52408 and gh-54234 we now have a nice compact way to add tests for type annotations. And anecdotally, the number of type annotation errors slipping through or breaking in CI has reduced over time.

Mypy is upgraded to the latest version (0.812) and runs on almost all files now, there's only a handful of `ignore_errors` for files under `torch/` and (with 2 exceptions for which PRs have been open for some time). So we're in pretty decent shape here.

There are some open issues left with `module: typing`, but those are all smaller things and can be handled like any other issue. I think we can declary victory here and close this tracking issue.

**Comment by sorenmc** [comment]
For anyone experiencing this problem with torch tensors, and if you just want a torch version of 

```python
my_array: np.ndarray = np.array([2,3,4])
```

 a way for mypy to pass is to type annotate as.

```Python
my_tensor: torch.Tensor = torch.tensor([1,2,3])
```

Notice that it is `Tensor` with a capital T
