### ISSUE TITLE
byte_order.cpp: decodeUInt64BE index bug

### ISSUE THREAD

**Issue by PhilippPelz** [pytorch/pytorch#1658]
just spotted while trying to get complex tensor support

data[7] twice

static inline uint64_t decodeUInt64BE(const uint8_t *data) {
  return (((uint64_t)data[7])<< 0) | (((uint64_t)data[7])<< 8) |
         (((uint64_t)data[5])<<16) | (((uint64_t)data[4])<<24) |
         (((uint64_t)data[3])<<32) | (((uint64_t)data[2])<<40) |
         (((uint64_t)data[1])<<48) | (((uint64_t)data[0])<<56);
}

**Comment by colesbury** [comment]
Thanks!
