### ISSUE TITLE
[RFC] Adding input_differentiability field to tools/autograd/derivatives.yaml

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#16581]
We already have output_differentiability. We currently infer input differentiability [by the name of the argument](https://github.com/pytorch/pytorch/blob/33f2ab1fdb5929151219091e6e11325196c866c8/tools/autograd/gen_variable_type.py#L412). This makes sense in obvious cases such as "int" or "float", etc - However, we might have a Tensor argument that we want to mark as not differentiable.

An example of this will be, as we move along with the schema unification of native_functions.yaml's func schema to align with the JIT's signature schema: Anything that currently uses IndexTensor or BoolTensor will be renamed to plain Tensor. native_functions.yaml doesn't need to know about the differentiability of these arguments. The developer who's adding to the native schema should notbe concerned with that, nor would I expect her to, because it doesn't even show up in the generated C++ stubs. 

So we should instead move this information to derivatives.yaml and for that we need input_differentiability as that information then cannot be inferred from IndexTensor or BoolTensor anymore.

**Comment by gchanan** [comment]
Sounds reasonable, I don't think it makes sense to do alignment like `output_differentiability`, we already have input arguments being specified.  We can just make some special thing to indicate it's not differentiable (how does that behavior differ today if you just don't specify a backwards)?

**Comment by cpuhrsch** [comment]
Whether something requires a derivative is determined by [the following code](https://github.com/pytorch/pytorch/blob/482d3a3bf32b0a2711891868dbb943b1ed607e48/tools/autograd/gen_variable_type.py#L431) within `tools/autograd/gen_variable_type.py`

```
    requires_derivative = (
        base_name not in DONT_REQUIRE_DERIVATIVE and name not in DONT_REQUIRE_DERIVATIVE and
        len(differentiable_inputs) > 0 and len(differentiable_outputs) > 0 and
        strategy == 'use_derived')
```

If the number of differentiable inputs increases from 0 to 1, as would be the case if we remove BoolTensor and replace it with Tensor, some functions that currently don't require one, will. This is independent of whether they actually have entry in derivatives.yaml. 

In the case of `_th_eq` that causes the following changes

```
@@ -6220,6 +6222,11 @@ std::tuple<Tensor &,Tensor &> VariableType::_th_eig_out(Tensor & res1, Tensor &
 Tensor VariableType::_th_eq(const Tensor & self, Scalar other) const {
   profiler::RecordFunction profiler("_th_eq", Function::peek_at_next_sequence_nr());
   auto& self_ = unpack(self, "self", 0);
+  std::shared_ptr<NotImplemented> grad_fn;
+  if (compute_requires_grad( self )) {
+    grad_fn = std::shared_ptr<NotImplemented>(new NotImplemented("_th_eq"), deleteFunction);
+    grad_fn->set_next_edges(collect_next_edges( self ));
+  }
   torch::jit::Node* node = nullptr;
   std::shared_ptr<jit::tracer::TracingState> tracer_state;
   if (jit::tracer::isTracing()) {
```

in `torch/csrc/autograd/generated/VariableTypeEverything.cpp`.

That simply means we're incurring checks in place we don't expect. This can lead to unexpected behavior for a user. Adding that argument to the set of non-differentiable input arguments would remove this sort of code-gen. In general, I'd rather add this field then add more complexity to the name schema used within derivatives.yaml, simply because we'll presumably visit that file in context of the schema unification and thus add another set of complexity we'll need to resolve beforehand. If this something we want to be representable by the schema in general, we should revisit that in context of a larger conversation w.r.t. the JIT signature schema.

Now, for functions that already have entries in derivatives.yaml, we have changes of the following kind

```
@@ -1300,9 +1301,9 @@ std::tuple<Tensor,Tensor,Tensor,std::vector<Tensor>> VariableType::_cudnn_rnn_ba
   auto dropout_state_ = unpack_opt(dropout_state, "dropout_state", 18);
   auto& reserve_ = unpack(reserve, "reserve", 19);
   std::shared_ptr<NotImplemented> grad_fn;
-  if (compute_requires_grad( input, weight, weight_buf, hx, cx, output, grad_output, grad_hy, grad_cy, reserve )) {
+  if (compute_requires_grad( input, weight, weight_buf, hx, cx, output, grad_output, grad_hy, grad_cy, dropout_state, reserve )) {
     grad_fn = std::shared_ptr<NotImplemented>(new NotImplemented("_cudnn_rnn_backward"), deleteFunction);
-    grad_fn->set_next_edges(collect_next_edges( input, weight, weight_buf, hx, cx, output, grad_output, grad_hy, grad_cy, reserve ));
+    grad_fn->set_next_edges(collect_next_edges( input, weight, weight_buf, hx, cx, output, grad_output, grad_hy, grad_cy, dropout_state, reserve ));
   }
   Tensor result0;
   Tensor result1;
@@ -2334,6 +2335,7 @@ Tensor VariableType::_s_where(const Tensor & condition, const Tensor & self, con
   auto& condition_ = unpack(condition, "condition", 0);
   auto& self_ = unpack(self, "self", 1);
   auto& other_ = unpack(other, "other", 2);
+  check_no_requires_grad(condition, "condition");
   std::shared_ptr<SWhereBackward> grad_fn;
   if (compute_requires_grad( self, other )) {
```

within `torch/csrc/autograd/generated/VariableTypeEverything.cpp`. Again, we simply incur unexpected checks w.r.t. the previous behavior.

**Comment by ezyang** [comment]
I think this was resolved.
