### ISSUE TITLE
Windows CI Build runs twice

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#16595]
## 🐛 Bug

The windows CI build for pytorch actually builds the entire project twice.

## To Reproduce

Observe a CI run, grep for the 'cmake' call. It happens twice:

(base) zdevito-mbp:~ zdevito$ curl https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-build/38258/consoleText 2>/dev/null | grep "'cmake'"
['cmake',
['cmake',

**Comment by zdevito** [comment]
Note: The CI script uses a USE_CUDA variable that is never set. This makes both if statements that use it true.

**Comment by peterjc123** [comment]
It builds twice for both CPU and CUDA builds. As for the variables, CC. @yf225.

**Comment by yf225** [comment]
In the past, building for both CPU and CUDA configurations had caught interesting bugs, so it's likely useful.

The `USE_CUDA` flag is intended to be set when people are running win-build.sh locally, to avoid building it twice.

**Comment by zdevito** [comment]
This is very surprising behavior then.  I wouldn't think setting USE_CUDA to nothing would trigger _both_ builds to run. At the very least there should be a comment in the file describing the behavior.
