### ISSUE TITLE
Ellipsis encoding fails when printing tensors

### ISSUE THREAD

**Issue by Henry-E** [pytorch/pytorch#1660]
There's something very odd about how torch.zeros throws up an error for square matrices over a certain size. >=32X32 to be exact

> (Pdb) torch.zeros(100,100)        
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 147: ordinal not in range(256)
(Pdb) torch.zeros(45,45)
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 147: ordinal not in range(256)
(Pdb) torch.zeros(40,40)
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 147: ordinal not in range(256)
(Pdb) torch.zeros(39,39)
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 147: ordinal not in range(256)
(Pdb) torch.zeros(38,38) 
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 147: ordinal not in range(256)
(Pdb) torch.zeros(37,37)  
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 147: ordinal not in range(256)
(Pdb) torch.zeros(36,36)
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 147: ordinal not in range(256)
(Pdb) torch.zeros(35,35)
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 147: ordinal not in range(256)
(Pdb) torch.zeros(34,34) 
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 147: ordinal not in range(256)
(Pdb) torch.zeros(32,32)
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 147: ordinal not in range(256)
(Pdb) torch.zeros(31,31)

Columns 0 to 12 
    0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0

**Comment by apaszke** [comment]
It's not a problem with `torch.zeros` it's a problem with printing. There will be no error if you assign it to a variable

**Comment by Henry-E** [comment]
Ah ok, yes I was calling .cuda() on a variable thinking it would change in place rather than assigning it to a new variable. Thanks

**Comment by vadimkantorov** [comment]
I also filed an issue with IPython about this: https://github.com/ipython/ipython/issues/10428

**Comment by Henry-E** [comment]
This doesn't appear to be an issue any more

**Comment by tscohen** [comment]
I ran into this just now. What fixed it for me is to set the environment variable `LANG=C.UTF-8 LC_ALL=C.UTF-8`. This is in a Docker container running Ubuntu.

**Comment by codeislife99** [comment]
@tscohen Thanks a lot. THis solved it for me
