### ISSUE TITLE
torch::serialization.load() doesn't support pathlib.Path object for the input argument

### ISSUE THREAD

**Issue by NySunShine** [pytorch/pytorch#16607]
## 🐛 Bug

When a path is given from pathlib.Path into a torch.load method, the error occurs as below,

`invalid file : PosixPath("models.pth.tar")`

I think it is because of the characteristics of Path object that is only allowed to use like `path.open('rb')`.

## To Reproduce

1. import torch
2. import pathlib
3. f = pathlib.Path("models.pth.tar")
4. params = torch.load(f)

Then, 

```
TypeError: invalid file: PosixPath('models.pth.tar')
```

It operates correctly as below:

`torch/serialization.py` :: 365 line
```
# Under the condition of (sys.version_info[0] == 3 and isinstance(f, pathlib.Path)
(-) f = open(f, 'rb')
(+) f = f.open('rb')
```

## Expected behavior

Load success from the any kind of '*.pth.tar' or some other extensions.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB
GPU 2: Tesla V100-PCIE-32GB
GPU 3: Tesla V100-PCIE-32GB
GPU 4: Tesla V100-PCIE-32GB
GPU 5: Tesla V100-PCIE-32GB
GPU 6: Tesla V100-PCIE-32GB
GPU 7: Tesla V100-PCIE-32GB

Nvidia driver version: 410.78
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.1.4
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by soumith** [comment]
Seems reasonable to add. We'll happily accept a PR with the change and a test.
