### ISSUE TITLE
Accessing intermediate layers for LSUV init

### ISSUE THREAD

**Issue by ducha-aiki** [pytorch/pytorch#1661]
Hi,

I would like to implement LSUV initialization (https://arxiv.org/abs/1511.06422)  for PyTorch. 
However, with my current knowledge of pytorch it looks like as extremely hard task, because I don`t see any easy way to access intermediate feature map (I looked at relevant discussions at https://discuss.pytorch.org/t/accessing-intermediate-data-in-nn-sequential/637 and https://discuss.pytorch.org/t/how-to-extract-features-of-an-image-from-a-trained-model/119/64 ), which is needed to LSUV init.

Could anyone, please, help me with accessing intermediate features for implementing such initialization?

**Comment by apaszke** [comment]
There are plenty of solutions in both threads that you linked. You should be able to extract any layer's output using the code from there

**Comment by ducha-aiki** [comment]
@apaszke I should be able, but it needs too much expertize in PyTorch and much harder that in the rest frameworks. That was a point why I have posted that question, if there is easy way to do it.
Thanks for reacting, anyway.

**Comment by ducha-aiki** [comment]
https://github.com/ducha-aiki/LSUV-pytorch
