### ISSUE TITLE
torch.to_dense() adds random values

### ISSUE THREAD

**Issue by giacomo-domeniconi** [pytorch/pytorch#16621]
## Issue description

I'm working with sparse tensors. I noticed a wrong filling of the tensor when calling the to_dense function. In the example below, it is expected that the dense tensor dense_m has all 0s or 1s (since v is a 0/1 tensor). But some 2 values appear after the to_dense() call. 
Weird is that with smaller sizes, the anomaly doesn't occurs. 

## Code example

size = torch.Size([8000])
i = torch.LongTensor(1000).random_(0, size[0]).unsqueeze(0)
v = torch.LongTensor(1000).random_(0, 2)
print (i.size(), v.size())
sp_m=torch.sparse.LongTensor(i, v, size)
dense_m=sp_m.to_dense()
print (v[v>1].size(),dense_m[dense_m>1].size())
print (v[v==1].size(),dense_m[dense_m==1].size())
print (v[v<1].size(),dense_m[dense_m<1].size())
print (dense_m.size(0), dense_m[dense_m>1])

## Output
torch.Size([1, 1000]) torch.Size([1000])
torch.Size([0]) torch.Size([15])
torch.Size([501]) torch.Size([471])
torch.Size([499]) torch.Size([7514])
8000 tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

**Comment by SsnL** [comment]
Your random indices tensor can generate multiple entries with value `1` but same index, hence the `2`s (and even `3`s if you are lucky enough).
