### ISSUE TITLE
High memory usage generating random numbers

### ISSUE THREAD

**Issue by Elch123** [pytorch/pytorch#16622]
## 🐛 Bug

Pytorch's Distributions lacks a fast method of generating uncorrelated normally distributed values.  MultivariateNormal is able to be fed an Identity matrix to produce this behavior, but this has cubic complexity, and will exhaust all ram on CPU or GPU when generating a large tensor filled wtih random numbers.

## To Reproduce

    import torch
    def make_normal_batch(batch_size,channels,seqlen):
        samples=channels*seqlen
        m = torch.distributions.MultivariateNormal(torch.zeros(samples), scale_tril=torch.eye(samples)) 
        data=m.sample((batch_size,))
        data=data.reshape(batch_size,channels,seqlen)
        return data
    make_normal_batch(10,200,120) #This may use up all ram!!!!!!!

## Expected behavior
I expected this code to run quickly, and not use 8+GB of ram. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Collecting environment information...
PyTorch version: 1.0.0a0+4b7c615
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Linux Mint 18.3 Sylvia
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: GeForce GTX 950M
Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.3
/usr/lib/x86_64-linux-gnu/libcudnn_static_v6.a
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] numpydoc (0.8.0)
[pip] torch (1.0.0a0+4b7c615)
[conda] blas                      1.0                         mkl  
[conda] magma-cuda91              2.3.0                         1    pytorch
[conda] mkl                       2019.0                      118  
[conda] mkl-include               2019.0                      118  
[conda] mkl-service               1.1.2            py37h90e4bf4_5  
[conda] mkl_fft                   1.0.4            py37h4414c95_1  
[conda] mkl_random                1.0.1            py37h4414c95_1  
[conda] mkldnn                    0.16.1                        0    mingfeima
[conda] torch                     1.0.0a0+4b7c615           <pip>

**Comment by SsnL** [comment]
Well.... you asked for the general multivariate gaussian. If you use plain `randn` it will much more efficient.

**Comment by vishwakftw** [comment]
Also adding to @SsnL’s point, you also required uncorrelated samples with the same identity variance, for which `randn` will be very efficient.

**Comment by Elch123** [comment]
Thanks for the help.
