### ISSUE TITLE
feature request: a sensible masked_copy

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#1662]
While working on broadcasting, I found the behavior of masked_copy unintuitive; I expected the same behavior as numpy.copyto (https://docs.scipy.org/doc/numpy/reference/generated/numpy.copyto.html, which also has sensible broadcasting semantics.  In that case the (i,j,k...)th element is copied from the source tensor if (i,j,k,...) is 1 in the mask.  But instead it copies the element the z-th element from the source (when viewed as a 1-d tensor) to (i,j,k) in the destination if (i,j,k) is set in the mask, where z is the number of non-zero elements seen so far in the mask.

I see @apaszke and others have run into the same issue: https://github.com/pytorch/pytorch/issues/1011.

This issue is to come up with some sensible deprecation / renaming strategy for this function.  We may want to do this soon, because broadcasting is changing/deprecating a lot of shape semantics like this anyway and it's better to do all these changes at once imo.

**Comment by fmassa** [comment]
I'm not sure we want to deprecate `masked_copy`. For me, `masked_copy` and `masked_select` works hand in hand, and are necessary to perform operations such as follows:
```python
a = torch.randn(2, 2)
b = torch.randn(2, 2)
a[b > 0] = b[b > 0]
```
In this case, the right-hand side corresponds to `masked_select`, while the left-hand is `masked_copy`.
Also, note that numpy behaves the same when indexing `b[b > 0]` (returns a 1D tensor), so I think we should still keep it around.

**Comment by apaszke** [comment]
We should definitely keep it around, but I think masked_scatter would be a better name. Masked copy should be an op that takes two tensors of matching sizes and only copies values in places that have 1 in a mask
