### ISSUE TITLE
Installing Windows 10

### ISSUE THREAD

**Issue by MohMehrnia** [pytorch/pytorch#16633]
Hi, I try install pytorch on windows 10 1809 and Python 3.7 and VS 2017 15.9.6 with below command:

`pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp37-cp37m-win_amd64.whl`

but show error message:
torch-1.0.0-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

**Comment by JamesTrick** [comment]
Hey @MohMehrnia 

Can you verify that you have the 64-bit installation of Python? By running this command: `python -c "import struct; print(struct.calcsize('P') * 8)"`. If it's 32-bit, try re-installing 64-bit Python.

Others might have another idea well.

Thanks
James

**Comment by peterjc123** [comment]
@MohMehrnia Would you please close this issue?

**Comment by nikich340** [comment]
And what does it mean? That pytorch can't be used absolutely on 32-bit platforms? No any way?

**Comment by peterjc123** [comment]
It can be used on a 32-bit system, but we don't provide packages for that. Considering the desktop OS, Linux is totally x64 now. Considering the memory size, you simply cannot use more than 4GB. Even if CUDA doesn't support cross-compiling 32-bit binaries now. (which means we will need a 32-bit machine to build. That is hard to find.) But anyway, you could compile the CPU/CUDA version if you really need that.
