### ISSUE TITLE
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by edgarriba** [pytorch/pytorch#1664]
I found this runtime error
```
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```
The code reproducing the error is the folowing
```
import torch
import torch.nn as nn
from torch.autograd import Variable

import torch.backends.cudnn as cudnn
cudnn.enabled = True
cudnn.benchmark = False

x = Variable(torch.ones(1,32,192,256,512)).cuda()

model = nn.ConvTranspose3d(32, 1, 3, 2, 1, 1, bias=False).cuda()

y = model(x)
print(y.size())
```

**Comment by ngimel** [comment]
A workaround for this is to use cudnn.benchmark = True, looks like cudnnGet is returning something nonsensical.

**Comment by ngimel** [comment]
That's a cudnn bug, unfortunately, can't be fixed in pytorch.

**Comment by edgarriba** [comment]
@ngimel thanks! so just for the record :smile:

**Comment by ezyang** [comment]
I'm reopening this bug to make it clear that PyTorch is still affected by this problem (although it can't be fixed PyTorch side.)

**Comment by zasdfgbnm** [comment]
fixed in https://github.com/pytorch/pytorch/pull/33073
