### ISSUE TITLE
dataloader: KeyError exception doesn't come through in a readable format 

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#16647]
## 🐛 Bug

if `_process_next_batch` gets an exception that's of type ErrorKey, the exception message is rendered as binary - i.e. new lines are not respected.

## To Reproduce

That would be tricky, as I got it in the middle of someone's notebook, I'm yet to figure out what the problem is, but currently we get something like:

```
KeyError                                  Traceback (most recent call last)
[...]
~/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    635                 self.reorder_dict[idx] = batch
    636                 continue
--> 637             return self._process_next_batch(batch)
    638 
    639     next = __next__  # Python 2 compatibility

~/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    656         self._put_indices()
    657         if isinstance(batch, ExceptionWrapper):
--> 658             raise batch.exc_type(batch.exc_msg)
    659         return batch
    660 
```
and the important part comes out in one binary string (I didn't format it on purpose, otherwise it's one huge line):

KeyError: 'Traceback (most recent call last):\n  File "/home/stas/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/stas/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "<ipython-input-14-30a344740c67>", line 8, in __getitem__\n    item = j2anno(self.j[idx])\n  File "<ipython-input-6-d882ce1bdda0>", line 11, in j2anno\n    orig_bbox = [np.clip(bbox_info[\'x\'], 0, orig_im_width), np.clip(bbox_info[\'y\'], 0, orig_im_height), np.clip(bbox_info[\'x\']+bbox_info[\'width\'], 0, orig_im_width), np.clip(bbox_info[\'y\']+bbox_info[\'height\'], 0, orig_im_height)]\nKeyError: \'width\'\n'

## Expected behavior

A readable exception message.

I researched it some more and apparently `KeyError`'s multiline message is "broken" by design and apparently there are no plans to fix it, see this 10 year old thread https://bugs.python.org/issue2651 (still being discussed these days).

But it doesn't help that python devs don't want to fix it. 

So in `torch/utils/data/dataloader.py` it bails here:
```
    def _process_next_batch(self, batch):
        self.rcvd_idx += 1
        self._put_indices()
        if isinstance(batch, ExceptionWrapper):
            raise batch.exc_type(batch.exc_msg)
        return batch
```
Proposed workaround:
```
    def _process_next_batch(self, batch):
        self.rcvd_idx += 1
        self._put_indices()
        if isinstance(batch, ExceptionWrapper):
            # help with multiline KeyError msg to be readable
            if batch.exc_type == KeyError and "\n" in batch.exc_msg:
                raise Exception("KeyError:" + batch.exc_msg)
            else:
                raise batch.exc_type(batch.exc_msg)
        return batch
```
So that if the exception is of KeyError type and is multiline, rethrow it as base Exception and pass the Exception type as part of the Exception message.

Cons: hides the type of error from potential up-stream try/except block
Pros: the message is readable now.

So now it looks like:

```
Exception                                 Traceback (most recent call last)
[...]
~/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    635                 self.reorder_dict[idx] = batch
    636                 continue
--> 637             return self._process_next_batch(batch)
    638 
    639     next = __next__  # Python 2 compatibility

~/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    657         if isinstance(batch, ExceptionWrapper):
    658             if batch.exc_type == KeyError and "\n" in batch.exc_msg:
--> 659                 raise Exception("KeyError:" + batch.exc_msg)
    660             else:
    661                 raise batch.exc_type(batch.exc_msg)

Exception: KeyError:Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/stas/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "<ipython-input-14-30a344740c67>", line 8, in __getitem__
    item = j2anno(self.j[idx])
  File "<ipython-input-6-d882ce1bdda0>", line 11, in j2anno
    orig_bbox = [np.clip(bbox_info['x'], 0, orig_im_width), np.clip(bbox_info['y'], 0, orig_im_height), np.clip(bbox_info['x']+bbox_info['width'], 0, orig_im_width), np.clip(bbox_info['y']+bbox_info['height'], 0, orig_im_height)]
KeyError: 'width'
```

Thanks.

**Comment by soumith** [comment]
this seems very reasonable to do. Thanks for researching it in detail.
I'd happily accept a PR if you send it, and if not we'll get around to it as well

**Comment by stas00** [comment]
Thank you, @soumith. 
PR: https://github.com/pytorch/pytorch/pull/18557

**Comment by stas00** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/18557
