### ISSUE TITLE
[Feature] Sparse tensor persistence/save.

### ISSUE THREAD

**Issue by sebftw** [pytorch/pytorch#16667]
## 🚀 Feature
I want to be able to save a model with sparse tensors.

## Motivation
I have a module where one of the parameters may be sparse. (It is an option)
All of the parameters are stored with register_buffer, so they are present in the state dict. But when one of them are sparse it cannot be saved to disk.
It throws the error `RuntimeError: sparse tensors do not have storage` for example simply on `torch.save(torch.sparse.FloatTensor(), 'sparse.pt')`.

## Pitch
It would be nice if the sparse matrices worked interchangeably with the dense counterparts.
`torch.save(torch.sparse.FloatTensor(), 'sparse.pt')` should just store the tensor.

## Alternatives
Alternatively a quick fix would be to simply convert the tensor to dense and then store that.

**Comment by colesbury** [comment]
@ezyang if I mark this as high-priority will it get fixed? 😄

**Comment by ezyang** [comment]
Not today, though one of my jobs is to figure out how to make that be true :)

**Comment by lironmo** [comment]
+1

**Comment by jiangyuang** [comment]
A (simplified) solution could be to use this sparse tensor constructor:
```
def _sparse_tensor_constructor(indices, values, size):
    return torch.sparse.FloatTensor(indices, values, size).coalesce()  # not coalesced from the default constructor 
```
and add the following \_\_reduce\_\_ to the torch.sparse.FloatTensor class:
```
def __reduce__(self):
    return _sparse_tensor_constructor, (self._indices(), self._values(), self.size())
```

For a temporary workaround, we can implement a subclass of Pickler:
```
def _sparse_tensor_constructor(indices, values, size):
    return torch.sparse.FloatTensor(indices, values, size).coalesce()  # not coalesced from the default constructor 


def _reduce(x):
    # dispatch table cannot distinguish between torch.sparse.FloatTensor and torch.Tensor (?)
    if isinstance(x, torch.sparse.FloatTensor):
        return _sparse_tensor_constructor, (x._indices(), x._values(), x.size())
    else:
        return torch.Tensor.__reduce_ex__(x, pickle.HIGHEST_PROTOCOL)  # use your own protocol

class ExtendedPickler(pickle.Pickler):
    dispatch_table = copyreg.dispatch_table.copy()
    dispatch_table[torch.Tensor] = _reduce
    # tried to use torch.sparse.FloatTensor instead of torch.Tensor but did not work (?)
```

**Comment by dexterju** [comment]
+1

**Comment by mshuaibii** [comment]
+1

**Comment by pearu** [comment]
Heads up: the PR https://github.com/pytorch/pytorch/pull/27062 resolves this issue.

**Comment by rgommers** [comment]
gh-27062 was merged, closing
