### ISSUE TITLE
[JIT] Additional list methods in script

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#16662]
We'd like to be able to easily write models with, e.g. a stack data structure, which is sometimes used in NLP. Here's an example of code that works now:

```
import torch

@torch.jit.script
def foo():
    a = [torch.tensor([1]), torch.tensor([2]), torch.tensor([3])]
    b = []
    while len(a) > 0:
        b.append(a[-1])
        a = a[:-1]
    return b
```

It would be much cleaner if we could replace `a = a[:-1]` with `pop()`.

Additional methods that would be nice:
- `reversed()`
- `sort()` (with comparator?)
- `any_of()`

**Comment by suo** [comment]
For reverse, here are operations defined on mutable sequence types: https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types

**Comment by suo** [comment]
A good way to start would be by adding methods to `List` rather than implementing the builtin functions.

**Comment by TheCodez** [comment]
Current status:
	
- [x] clear (https://github.com/pytorch/pytorch/pull/17050)
- [ ] pop (https://github.com/pytorch/pytorch/pull/17015)
- [ ] reverse (https://github.com/pytorch/pytorch/pull/17001)
- [ ] copy (https://github.com/pytorch/pytorch/pull/17092)
- [ ] extend (https://github.com/pytorch/pytorch/pull/17092)

I'm working on adding `insert` and `remove`.

**Comment by TheCodez** [comment]
@eellison @driazati would you be okay with a `sort` implementation that just has the reverse parameter? Support for the key parameter could be added later.

**Comment by eellison** [comment]
@TheCodez functions aren't first-class values in TorchScript (yet), so I would personally say it makes more sense to hold off on implementing it. 

Also, by the most common case for lists in torchscript will be Tensors, which don't make a lot of sense to sort without a custom function. Maybe @driazati has other thoughts?

But we appreciate your enthusiasm & hard work! If you're trying to round out list methods for completeness that totally makes sense - we can also document more issues that need work if you're looking for other things.

**Comment by suo** [comment]
Assigning @Krovatkin as he has been driving this from our side

**Comment by suo** [comment]
Nice! It looks like everything but sorting has been done. We've broken that out into a separate thing since the builtin will probably share an implementation: #19372. Closing this issue in favor of that one.

**Comment by pieris98** [comment]
We faced this example [code](https://github.com/facebookresearch/Mask2Former/blob/9b0651c6c1d5b3af2e6da0589b719c514ec0d69a/mask2former/modeling/transformer_decoder/mask2former_transformer_decoder.py#L374) trying to `jit.script` this whole model:
`size_list.append(x[i].shape[-2:])`

Originally the error when we annotated `size_list` as `size_list : List[int]` (which is wrong in this case) gave this error:
```
RuntimeError: 

aten::append.t(t[](a!) self, t(c -> *) el) -> t[](a!):
Could not match type List[int] to t in argument 'el': Type variable 't' previously matched to type Tensor is matched to type List[int].
:
  File "/home/lemon/anomaly/RbA/mask2former/modeling/transformer_decoder/mask2former_transformer_decoder.py", line 410
    
        for i in range(self.num_feature_levels):
            size_list.append(x[i].shape[-2:])
```
We eventually found that `append` on a list of `torch.size`s works with `torch.jit.script` just by type hinting the (originally empty) list `size_list` as `size_list:List[List[int]] = []`. 

Admittedly, the fact that this works is a bit odd as I thought that `torch.Size` is a `tuple` subclass according to the [docs](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) but I'm guessing this has to do with how `torch.jit` parses things statically, or it may just be specific to this example.

Just putting this out there for anyone facing similar issues with `torch.jit.script` and `append`
