### ISSUE TITLE
reset_parameters in various Modules

### ISSUE THREAD

**Issue by koz4k** [pytorch/pytorch#1667]
I'm concerned with the implementation of reset_parameters in many Modules, for example in Linear:
```
    def reset_parameters(self):
        stdv = 1. / math.sqrt(self.weight.size(1))
        self.weight.data.uniform_(-stdv, stdv)
        if self.bias is not None:
            self.bias.data.uniform_(-stdv, stdv)
```
It seems quite arbitrary to me. If the weights were drawn from the uniform distribution with zero mean and standard deviation `stdv`, it would be LeCun initialization, a sensible choice. But `Tensor.uniform_(-stdv, stdv)` samples from the uniform distribution on the `(-stdv, stdv)` interval, which has standard deviation of `stdv/sqrt(3)`.
I think that `stdv` should be scaled by `sqrt(3)`, then we would get LeCun initialization, which would deal better with vanishing gradients.
I realize that this is only a default initalization and it can be easily overriden, but if it can work better out-o-the-box, I think it should.

**Comment by koz4k** [comment]
Bump. I also think that LeCun initialization should be added to nn.init, and/or "gain" parameter be added to kaiming_uniform so we could get LeCun initialization by passing 1 as gain.

**Comment by albanD** [comment]
I'm afraid that for BC reasons, we won't be able to change the default initialization of the Linear layer.
But you can open a new issue if you want to request new methods to be added to the `nn.init` module.
