### ISSUE TITLE
[Feature] 'None' for arbitrarily shaped buffer/parameter when loading models.

### ISSUE THREAD

**Issue by sebftw** [pytorch/pytorch#16675]
## 🚀 Feature
My model takes a path to a model and converts it to pytorch.
There are some variations on this model with different parameter shapes, and I would like to support all of them. It does this already, and they are stored with `self.register_buffer('name', value)`.

But I can't save and load the model with `model.load_state_dict(torch.load(PATH))`. The keys need to be present in self._buffers or self._parameters for this to work, and they need to match in shape, but None values are ignored.

## Motivation
It is already possible to call `self.register_buffer('name', None)`. This is an undocumented feature, and the null-value is simply added to self._buffers, but then ignored everywhere. (if ... is not None)

If I could load the model only knowing the names of the parameters, I could make it work with the two models I need interchangeably, and with all the features offered by pytorch serialization.

## Pitch
My proposal is that `self.register_buffer('name', None)` should prevent the "Unexpected key(s) in state_dict" error and then allow any shape of tensor to be loaded into this buffer with `load_state_dict`.

## Additional context
It seems quite straightforward to implement in `_load_from_state_dict` of module.py.  Since the value None is already present in self._buffers. It is just ignored.
Here's a link: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py

It could be an issue if anyone uses None-valued buffers or parameters and then `load_state_dict` with `strict=True`, so you could add an additional argument to this function for this new functionality (completely safe) or simply only allow it when `strict=False`.

The values that I store with self.register_buffer are constant throughout.
The models I am working with are SMPL ( http://smpl.is.tue.mpg.de/ )
and SMIL ( https://www.iosb.fraunhofer.de/servlet/is/82920/ )

This request may conflict with https://github.com/pytorch/pytorch/issues/8104, if it is implemented.

**Comment by soumith** [comment]
what you are asking for is to legitimize a hacky, possibly removable feature of `register_buffer`, so no :)

I'd say, `state_dict` is such a simple stupid format, that writing a `load_model(model, state_dict)` that works for your model is the way to go
