### ISSUE TITLE
RuntimeError: block->inputs().size() >= num_initializers ASSERT FAILED

### ISSUE THREAD

**Issue by robbine** [pytorch/pytorch#16699]
## To Reproduce

1. initialize a model object by  model = Model()
2. read model state by model_state = torch.load(os.path.join(args.serialization_dir, 'best.th'), map_location=torch.device('cpu'))
3. load model state by model.load_state_dict(model_state)
4. torch.onnx.export(model=model, args=(dummy_input, dummy_mask), f=args.output_pt, verbose=True)

```python
dummy_input = torch.ones(1, 14, 200, dtype=torch.float)
dummy_mask = torch.ones(1, 14, dtype=torch.float)
torch.onnx.export(model=model._transformer, args=(dummy_input, dummy_mask), f=args.output_pt, verbose=True)
```

Failed to export model using export_onnx
```
Traceback (most recent call last):
  File "scripts/export_pytorch_script.py", line 87, in <module>
    sys.exit(main())
  File "scripts/export_pytorch_script.py", line 83, in main
    torch.onnx.export(model=model._transformer, args=(dummy_input, dummy_mask), f=args.output_pt, verbose=True)
  File "/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/onnx/utils.py", line 292, in _export
    proto, export_map = graph._export_onnx(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: block->inputs().size() >= num_initializers ASSERT FAILED at /opt/conda/conda-bld/pytorch-nightly_1549065344879/work/torch/csrc/jit/export.cpp:307, please report a bug to PyTorch. (EncodeBlock at /opt/conda/conda-bld/pytorch-nightly_1549065344879/work/torch/csrc/jit/export.cpp:307)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f1059cd08b5 in /anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x56523c (0x7f10579ef23c in /anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #2: <unknown function> + 0x5658ae (0x7f10579ef8ae in /anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #3: torch::jit::export_onnx(std::shared_ptr<torch::jit::Graph> const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, long, bool, torch::onnx::OperatorExportTypes) + 0x37 (0x7f10579efa77 in /anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x3aea18 (0x7f108cfe8a18 in /anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x113c36 (0x7f108cd4dc36 in /anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xf5 (0x7f109ec94445 in /lib64/libc.so.6)
```
## Environment

PyTorch version: 1.0.0.dev20190201
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 3.6.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration:
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 396.26
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.3.1
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl_fft                   1.0.10           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch-nightly           1.0.0.dev20190201 py3.7_cuda9.0.176_cudnn7.4.1_0    pytorch
[conda] pytorch-pretrained-bert   0.3.0                    pypi_0    pypi

**Comment by suo** [comment]
Thanks for the report! Could you provide a small model/script that reproduces this issue to help us investigate?

**Comment by robbine** [comment]
https://github.com/robbine/allennlp-as-a-library-example/blob/master/scripts/export_pytorch_script.py
The above script shows how I tried to export from pytorch model to onnx model.
The model I want to export is a standard pytorch model which were trained using Chinese corpus.
Do I need to upload it inorder to investigate ?

**Comment by robbine** [comment]
The trained model is too large to upload onto github
However I would like to share it by other means. And my question is why do we need the assertion here ?

`auto num_initializers = initializers.size();
  AT_ASSERT(block->inputs().size() >= num_initializers);
  size_t inputs_count = block->inputs().size() - num_initializers;
  for (auto& tensor : initializers) {
    // TODO: stop using positions to determine which initializers
    // match to which inputs
    std::string name = graph_proto->input(inputs_count++).name();
    auto p = graph_proto->add_initializer();
    p->set_name(name);
    EncodeTensor(p, tensor, name);
  }
`

**Comment by robbine** [comment]
any updates? I would like to help if there are debug tools to report more.

**Comment by suo** [comment]
Sorry for the delay! I will investigate with our onnx experts and let you know if we need more information

**Comment by houseroad** [comment]
Thanks for reporting the problem. Could you help us narrow down the problem and provide a small script to reproduce the problem? It's hard for us to run the whole model just for reproducing.

**Comment by robbine** [comment]
Sure, I've trained a 6 layer model which is much smaller but still exceeds github file upload limit.
Please tell me a way send it along with my script, so that we can investigate more.

**Comment by soumith** [comment]
@robbine we dont need the trained model weights, we just need a way to construct such a model, I believe (random weights are fine).

Can you give us one python script without any dependencies that reproduces the problem?

**Comment by robbine** [comment]
I finally managed to reproduce this issue with two python scripts. One  for model creation and model dump. The other for model conversion using onnx. However allennlp-v0.8.2 is required, please create a conda environment with python=3.7 also. Thanks in advance !
https://github.com/robbine/allennlp-as-a-library-example/blob/master/scripts_for_debug/model.py
https://github.com/robbine/allennlp-as-a-library-example/blob/master/scripts/export_pytorch_script.py

**Comment by robbine** [comment]
also please notice that I installed latest pytorch-nightly 1.0.0.dev20190225

**Comment by robbine** [comment]
If there are any problems with reproducing this issue, please let me know.

**Comment by houseroad** [comment]
@robbine could you check if you apply https://github.com/pytorch/pytorch/pull/18139, whether your problem will go away?

**Comment by robbine** [comment]
The exception disappeared. Thanks a lot !

**Comment by annopackage** [comment]
Hi, I also met similar issue, can you kindly tell me the reason and how to solve it?
