### ISSUE TITLE
GeForce GTX 670M CUDA SDK 8.0 Suported GPU  too old error

### ISSUE THREAD

**Issue by canerkaraguler** [pytorch/pytorch#16712]
I am working on an AI project so I need to use my GPU's for training some models.I have  GeForce GTX 670M, GeForce GT 750M and Quadro 600. Both GPU's have CUDA support. Related to this wikipedia link [ http://www.wikizero.biz/index.php?q=aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvQ1VEQQ](url) I saw that all GPU's that I wrote above have compute capability version 2.1 (Fermi) and suported by CUDA SDK 8.0 or 7.5. For my project I need to use Pytorch version 1.0.0 and it has a hard dependency on CUDA version of GPU's which must be greater or equal than CUDA SDK 8.0. So as I wrote above my GPU's have CUDA SDK 8.0 support but when we tried to train my model I get old GPU error. 

I'm sending the error message that I get on GeForce GTX 670M .

> C:\Users\Caner\Anaconda3\lib\site-packages\torch\cuda\__init__.py:117: UserWarning: 
    Found GPU0 GeForce GTX 670M which is of cuda capability 2.1.
    PyTorch no longer supports this GPU because it is too old. warnings.warn(old_gpu_warn % (d, name, major, capability[1]))

  

`torch.version.cuda`
returns 8.0
`torch.cuda.is_available()`
returns True
`torch.backends.cudnn.enabled`
returns True

and as you can see cuda version is printed as 8.0.

My question is that is there a kind of bug in Fermi GPU's or am I doing something wrong ?

Thanks for your interest

**Comment by zou3519** [comment]
@canerkaraguler we don't support GPUs with compute capability <= 3.0. PyTorch operators rely on some GPU primitives that were introduced after 3.0.

We should change the error message to specifically state the oldest compute capability that we support
