### ISSUE TITLE
[JIT] Assign parameter in nested module

### ISSUE THREAD

**Issue by miguelvr** [pytorch/pytorch#16713]
## ❓ Questions and Help

Is it currently possible with TorchScript to change an argument of a module class within a module?

**e.g.**

```python
import torch
import numpy as np


class LinearScheduler(torch.jit.ScriptModule):

    __constants__ = ['i', 'drop_values']
    def __init__(self, module, start_value, stop_value, nr_steps):
        super(LinearScheduler, self).__init__()
        self.module = module
        self.i = 0
        self.drop_values = np.linspace(start=start_value, stop=stop_value, num=nr_steps).tolist()

    def forward(self, x):
        return self.module(x)

    def step(self):
        if self.i < len(self.drop_values):
            self.module.drop_prob = self.drop_values[self.i]

        self.i += 1
```

I currently get an error saying I can not access a JIT module attribute (or something along those lines).

Is there a workaround for this?

**Comment by sidazhang** [comment]
Why does this need to be a JIT module? It seems like it is training related logic and not a inference related logic?

**Comment by miguelvr** [comment]
@sidazhang you are right, it is training logic, but it is coded in a way that wraps the module itself (maybe could have been achieved in some other way, sure). The question is if it is possible to change the attributes of traced modules.

@suo I'll get back to you tomorrow with a snippet to reproduce it, as I don't have access to code right now.

**Comment by suo** [comment]
Going to close for now to clear our backlog, feel free to reopen if you have a repro
