### ISSUE TITLE
F.conv2d throws C++ side error when shape of weights and input mismatch

### ISSUE THREAD

**Issue by slbinilkumar** [pytorch/pytorch#16715]
I am getting this error
RuntimeError: $ Torch: invalid memory size -- maybe an overflow? at ../aten/src/TH/THGeneral.cpp:188
 I tried with update from master .still issue is there. Can you please share the correct branch to solve this.

**Comment by SsnL** [comment]
Please use the issue template to include your system info and a repro script (e.g., including the input shapes).

**Comment by zou3519** [comment]
Closing this due to not enough information. Please open a new issue once the information has been provided.
