### ISSUE TITLE
Training flag in the JIT script module is not saved in the serialization

### ISSUE THREAD

**Issue by houseroad** [pytorch/pytorch#16742]
## 🐛 Bug

Even we call the eval() before the serialization, the loaded model's training flag is still True.

## To Reproduce
```python
import torch

class TestModule(torch.jit.ScriptModule):
    def __init__(self):
        super(TestModule, self).__init__()
        self.d = torch.nn.Dropout()

    @torch.jit.script_method
    def forward(self, input):
        return self.d(input)

a = TestModule()
a.eval()
torch.jit.save(a, "test_training_flag.pt")

b = torch.jit.load("test_training_flag.pt")
print("a's Training: {}\nb's Training: {}".format(a.training, b.training))
print("a.d's Training: {}\nb.d's Training: {}".format(a.d.training, b.d.training))

input = torch.zeros([10])
print("a(input): ", a(input))
print("b(input): ", b(input))
```

The output is
```
a's Training: False
b's Training: True
a.d's Training: False
b.d's Training: True
a(input):  tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
b(input):  tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

cc: @suo @jamesr66a @zdevito @pritamdamania87

**Comment by zdevito** [comment]
Training tensor is only generated for Modules that use it. What is the value of `a.d.training` before and after? Does it matter that a flag that is not used by a module is not restored in the same way?

**Comment by houseroad** [comment]
@zdevito i have updated the code and output. `a.d.training` is False (before) and True (after).

**Comment by zdevito** [comment]
There is no @torch.jit.script_method annotation on forward, which seems wrong to me.

**Comment by houseroad** [comment]
My bad, have fixed the problem now. The loaded script module (i.e., b) gives the right result. But both b.training and b.d.training are True. This inconsistence may get user confused.

**Comment by zdevito** [comment]
We have a longer-term plan to allow Script modules to have attributes like training directly. This will get rid of the special case logic that is causing this behavior.

**Comment by houseroad** [comment]
I see. Thanks for the explanation. Close the issue since it's a known behavior, and we have a long term plan for general attributes in Script module.

**Comment by pritamdamania87** [comment]
Should we keep this issue open until its resolved? To me this is still a bug since the user might look at the training flag after loading the model and would be confused about which state the model is in.
