### ISSUE TITLE
error in building extention for pytorch with Win10+Cuda9.2+VS2017+anaconda py3.7+amd64

### ISSUE THREAD

**Issue by samhu1989** [pytorch/pytorch#16757]
When I build my extention in Win10 I used same setup.py  as I did in Ubuntu
and the following .bat to set cl compiler 

`@echo off`
`set "VS150COMNTOOLS=D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\"`
`set DISTUTILS_USE_SDK=1`
`call "%VS150COMNTOOLS%\vcvarsall.bat" x64`
`call activate D:\CONDA`
`call activate pytorch`
`python setup.py install`
`pause`

It runs into following link error
> 
D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\CONDA\envs\pytorch\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib/x64" /LIBPATH:D:\CONDA\envs\pytorch\libs /LIBPATH:D:\CONDA\envs\pytorch\PCbuild\amd64 "/LIBPATH:D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64" cudart.lib c10.lib caffe2.lib torch.lib torch_python.lib caffe2_gpu.lib _C.lib /EXPORT:PyInit_chamfer build\temp.win-amd64-3.7\Release\chamfer_cuda.obj build\temp.win-amd64-3.7\Release\chamfer.obj /OUT:build\lib.win-amd64-3.7\chamfer.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\chamfer.cp37-win_amd64.lib
chamfer.obj : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(chamfer_cuda.obj 中)
<
It seems that the compiler options automatically used in pytorch is not correct.
How can I change the option ？
or should I set extra environment vars to make it running correctly?
## Environment
 - PyTorch Version = 1.0:
 - OS = Win10:
 - How you installed PyTorch = conda:
 - Python version = 3.7
 - CUDA/cuDNN version = 9.2 and cuDNN comes within conda 4.5.12
 - GPU models and configuration: RTX2060 6G

**Comment by peterjc123** [comment]
Yes, you could try adding `/MD` or `/MT` into the compiler flags.

**Comment by samhu1989** [comment]
@peterjc123 
I am not familiar with setuptools and custom options for buildextention could you please point me to some doc about it ? thanks ahead

**Comment by peterjc123** [comment]
See `extra_compile_flags` of https://docs.python.org/3/distutils/apiref.html#distutils.core.Extension. And document for Cpp Extension: https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.CppExtension.

**Comment by samhu1989** [comment]
@peterjc123 
Hi, your advice didn't exactly solve my problem.
I do solve the problem by altering the code in cpp_extention.py inside pytorch.
Now, I believe it is kind of a small bug in pytorch's utils instead of my own issue.
`
cmd = [nvcc, '-c', src, '-o', obj, '-Xcompiler', '/wd4819', '-Xcompiler', '/MD' ] + include_list + cflags
`
the above code is in cpp_extention.py and it explicitly add '/MD' for compiling cuda source files
but the same flag is not added for cpp source compiliation and lead to failure of linking in my case.

It can not be solved by add '/MD' in setup.py as extra_compile_flags. Such solution will add extra '/MD' for nvcc and somehow cause nvcc to fail. 

I have to work around it by add the '/MD' flag for other cases inside the cpp_extention.py with
`cmd += ['/MD']` 
for other compilation cases
and the code will be as follows from line 319 in cpp_extention.py
`elif isinstance(self.cflags, dict):`
`      cmd += ['/MD'] ` 
`      cflags = self.cflags['cxx']`
`      cmd += cflags`
`elif isinstance(self.cflags, list):`
`      cmd += ['/MD']`
`      cflags = self.cflags`
`      cmd += cflags`
[cpp_extension.zip](https://github.com/pytorch/pytorch/files/2832858/cpp_extension.zip)

**Comment by peterjc123** [comment]
It is now fixed in master.
