### ISSUE TITLE
Implementing Normalizing Flows with TransformedDistribution

### ISSUE THREAD

**Issue by esling** [pytorch/pytorch#16756]
Since the recent introduction of `TransformedDistribution`, I was hoping to move my implementation of normalizing flows using solely the corresponding classes instead of `nn.Module` ... mostly because it is intellectually pleasing (^^) but also as this allow to nicely consider them as ... distributions

However, it seems not really directly possible for flows with trainable parameters. I tried using a double inheritance to consider these both as Transforms and Modules and put the Transforms in a `ModuleList` but the Transform object is unhashable when passing the overall module parameters to the optimizer as such

```
optimizer = optim.Adam(flow.parameters(), lr=args.lr)
```

I obtain

```
File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 973, in named_modules
    for m in module.named_modules(memo, submodule_prefix):

  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 966, in named_modules
    if self not in memo:

TypeError: unhashable type: 'PlanarFlow'
```

So I am wondering what would be the best way to deal with this, also given the potential future developments of the Transforms objects ? Right now I am thinking on two options

1. Wrapping a distribution inside a module object and constructing both ModuleList and TransformedDistribution
2. Manually keeping the parameters dictionary when constructing the flow to pass it to the optimizer

But of course if anyone has a magically more elegant solution to this conundrum, I would be forever grateful :)

**Comment by vishwakftw** [comment]
cc: @fritzo

**Comment by t-vi** [comment]
Do you have a minimal example of what should work? Maybe one can make multiple inheritance work.

**Comment by esling** [comment]
Okay so for instance let's say that I would like to implement a simple Planar Flow class (here that could be both seen as a Transform and a Module as it embeds some trainable parameters)

```python
class PlanarFlow(tr.Transform, nn.Module):

    def __init__(self, dim):
        tr.Transform.__init__(self)
        nn.Module.__init__(self)
        self.weight = nn.Parameter(torch.Tensor(1, dim))
        self.bias = nn.Parameter(torch.Tensor(1))
        self.scale = nn.Parameter(torch.Tensor(1, dim))

    def _call(self, z):
        f_z = F.linear(z, self.weight, self.bias)
        return z + self.scale * F.tanh(f_z)

    def log_abs_det_jacobian(self, z):
        f_z = F.linear(z, self.weight, self.bias)
        psi = (1 - F.tanh(f_z) ** 2) * self.weight
        det_grad = 1 + torch.mm(psi, self.scale.t())
        return torch.log(det_grad.abs() + 1e-9)
```

Then I could use it in a main type of flow a little bit like this (here I only use the Planar Flow, but the idea would be that this class could contain any sequence of flows)

```python
# Main class for normalizing flow
class NormalizingFlow(nn.Module):

    def __init__(self, dim, flow_length, density):
        super().__init__()
        biject = []
        for f in range(flow_length):
            biject.append(PlanarFlow(dim))
        self.bijectors = ComposeTransform(biject)
        self.modules = nn.ModuleList(biject)
        self.base_density = density
        self.final_density = TransformedDistribution(density, self.bijectors)
        self.log_det = []

    def forward(self, z):
        self.log_det = []
        # Applies series of flows
        for bijector in self.bijector:
            self.log_det.append(bijector.log_abs_det_jacobian(z))
            z = bijector(z)
        return z, self.log_det
```

(Even better would be that this class itself be a form of TransformedDistribution eventually)

The problem is that

```
# Multiple inheretance automatically put __hash__ to None if one of two is None, whatever the order
```

And Transform defines this as None so when I pass the class to the optimizer, I get the aforementioned error. I know that I might get around this (maybe through duck typing), but it looks also a bit hacky.

Even with that solution, I also need to manually handle the log det jacobian along the way ... so I am wondering if there is an elegant way of architecturing this ?

(Also I think that a small tutorial on best practices for flows in pytorch could be great, I can do it when I am sure that I am going down the best coding path possible ^^)

**Comment by t-vi** [comment]
I would suggest that you split the hacks into a class`TransformedDistributionModule` (ugh) and subclass from there (you could just call `Module.__hash__(self)`. Then we can discuss how to do this.
The log det jacobian reminds me a bit of #7313, but I could be wrong and it might be easier when you know the "user".

**Comment by esling** [comment]
Thank you for all the pointers !... it seems that I have to roam down the shameful path of hackiness after all :)

So here is a little example that works (even though my eyes are slightly bleeding)

```python
class Flow(tr.Transform, nn.Module):
    
    def __init__(self):
        tr.Transform.__init__(self)
        nn.Module.__init__(self)
        
    # Hacky hash bypass
    def __hash__(self):
        return nn.Module.__hash__(self)

class PlanarFlow(Flow):

    def __init__(self, dim):
        super(PlanarFlow, self).__init__()
        self.weight = nn.Parameter(torch.Tensor(1, dim))
        self.bias = nn.Parameter(torch.Tensor(1))
        self.scale = nn.Parameter(torch.Tensor(1, dim))

    def reset_parameters(self):
        self.weight.data.uniform_(-0.01, 0.01)
        self.scale.data.uniform_(-0.01, 0.01)
        self.bias.data.uniform_(-0.01, 0.01)

    def _call(self, z):
        f_z = F.linear(z, self.weight, self.bias)
        return z + self.scale * F.tanh(f_z)

    def log_abs_det_jacobian(self, z):
        f_z = F.linear(z, self.weight, self.bias)
        psi = (1 - F.tanh(f_z) ** 2) * self.weight
        det_grad = 1 + torch.mm(psi, self.scale.t())
        return torch.log(det_grad.abs() + 1e-9)
```

I still need to handle the log det jacobian by hand but I will read #7313 more carefully before going further !

**Comment by fritzo** [comment]
Also Pyro uses a similar pattern, defining a [TransformModule](https://github.com/pyro-ppl/pyro/blob/dev/pyro/distributions/torch_transform.py)

**Comment by t-vi** [comment]
Would it make sense to define the TransformModule in PyTorch itself?

**Comment by esling** [comment]
Thanks @fritzo for the follow-up, always liked Pyro so I am delighted that PyTorch seems to be taking this probabilistic direction.

And yes @t-vi, at least for me it makes sense if PyTorch is proposing a solid set of probabilistic modules ... but maybe it could go in a flavor similar to [TensorFlow's Bijectors](https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/bijectors/Bijector) ? (With respect to the optimization aspects, as the major `Transform` interface is already mostly identical)

In any case, I started working on a small set of tutorials for implementing NF with the `torch.distributions` package, I will post it here as soon as I have something slightly fancier to share.

**Comment by esling** [comment]
Hey @fritzo and @t-vi as promised I started a series of tutorials on implementing NF with `torch.distributions`. It might be a bit rough on the edges, and maybe slightly too verbose but at least it is a start
https://github.com/acids-ircam/pytorch_flows/blob/master/flows_01.ipynb

So I am also looking forward to update this on the optimization side when need be

**Comment by vishwakftw** [comment]
Is the issue resolved?

**Comment by fritzo** [comment]
I guess we could move [TransformModule](https://github.com/pyro-ppl/pyro/blob/0.3.1/pyro/distributions/torch_transform.py) into torch/distributions/transforms.py, but other than that I think we can close this issue.
