### ISSUE TITLE
Defined layers by @property to allow better modularity

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [pytorch/pytorch#16755]
## 🐛 Bug
@property fields modules are not added to the `Module`

## To Reproduce
What if I want to define a field as a property to provide a clear way to override it in class that inherits from it?
```python
import torch.nn as nn
class TestModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(1,2)
        
    @property
    def l2(self):
        return nn.Linear(2,3)

test_module = TestModule()

list(test_module.children())
```
output:

```
[Linear(in_features=1, out_features=2, bias=True)]
```
There is no `l2`

## Expected behavior
I would expect `nn.Module` to correct track the @property defined layers.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

 - PyTorch Version (e.g., 1.0): 1.0.0
 - OS (e.g., Linux): MacOsx
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: python 3.6.5
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information:

**Comment by fmassa** [comment]
I don't think this is a great thing to add for a few reasons:
- error messages will be very bad and obscure, see https://github.com/pytorch/pytorch/issues/13981. A solution for fixing it would make things much slower https://github.com/pytorch/pytorch/pull/16823
- in your example, every time you access `test_module.l2`, you return a new `nn.Linear`, which is definitely not what you would expect
- if you want to explicitly enforce that it should be overwritten by the user, you could use `@abstractmethod` instead. This is very clear: an error is raised if it's not overwritten
- Here is a simple way of modifying something in a derived class:
```python
class TestModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(1,2)
        self.l2 = nn.Linear(1,2)

class MyModule(TestModule):
    def __init__(self):
        super().__init__()
        self.l2 = nn.Linear(1, 10)
```

For this, I'm closing this issue, but let me know if you disagree.

**Comment by FrancescoSaverioZuppichini** [comment]
I see your point, and I totally agree! Thank you
