### ISSUE TITLE
Binary jobs are not correctly using Git plumbing to run diagnostics

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#16760]
I see binary jobs occasionally fail with:

```
+ git log --max-count 1
WARNING: terminal is not fully functional

-  (press RETURN)

commit 3796cbaf7ab4c4c30cb99191d55a8b9c50b398dc
Author: Dmytro Dzhulgakov <dzhulgakov@fb.com>
Date:   Mon Feb 4 23:56:00 2019 -0800

    Try to turn off zero-out of tensors fully
    
    Summary: Pull Request resolved: https://github.com/pytorch/pytorch/pull/1660
    
    Reviewed By: ezyang
    
    Differential Revision: D13893776
    
    fbshipit-source-id: 3190258f2591540dc54ad8504ac6ded998bef384
(END)
(END)Too long with no output (exceeded 10m0s)
```

You are probably hanging because Git incorrectly thinks that it is outputting to a terminal, so it opens less and hangs without any keyboard input. The correct way to disable pager is passing `--no-pager` to `git` e.g. https://stackoverflow.com/questions/7736781/how-to-make-git-log-not-prompt-to-continue

cc @pjh5

**Comment by ezyang** [comment]
Sample job: https://circleci.com/gh/pytorch/pytorch/717396?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

**Comment by pjh5** [comment]
Fixed in referenced PR
