### ISSUE TITLE
Pip upgrade to torch 1.0.1 breaks under Python 2.7 (No module named typing)

### ISSUE THREAD

**Issue by dsblank** [pytorch/pytorch#16775]
## To Reproduce

Starting with torch-1.0.0 and python2.

1. `$ python2 -m pip install torch --upgrade`
1. `$ python2`
1. `>>> import torch`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dblank/.local/lib/python2.7/site-packages/torch/__init__.py", line 263, in <module>
    from .functional import *
  File "/home/dblank/.local/lib/python2.7/site-packages/torch/functional.py", line 10, in <module>
    from typing import Optional, Tuple, List, Union
ImportError: No module named typing
```

**Comment by zou3519** [comment]
`pip install typing` should fix your problem.

Did we add a runtime dependency on mypy? cc @ezyang

**Comment by dsblank** [comment]
There are a couple of other ways to fix the issue:

1. `pip install torch --update --upgrade-strategy eager`
2. `pip install torch==1.0.0`

Just reporting here so others may find the solutions.

**Comment by ezyang** [comment]
No, we're not supposed to have a runtime dependency on mypy. I must have messed up the type hints patch merge.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/16776

**Comment by dsblank** [comment]
Thanks for the quick attention! Much appreciated!

**Comment by ezyang** [comment]
This wasn't caught in CI because typing is a mandatory build-time dependency for PyTorch, and we don't subsequently uninstall it when we run tests.

**Comment by soumith** [comment]
I'm working on regenerating 1.0.1 binaries, with a bumped up build number.

**Comment by soumith** [comment]
new binaries uploaded, this should be fixed now.
