### ISSUE TITLE
Conv1d & ConvTranspose1d expect 2nd dimension values.

### ISSUE THREAD

**Issue by educob** [pytorch/pytorch#1680]
I am programming an adversarial convolutional autoencoder and getting all sort of errors for the 2nd dimension of parameters when in theory there should be any 2nd dimension in Conv1d & ConvTranspose1d

I copied and adapted the code from: [https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/deep_convolutional_gan/model.py](url)
I just changed conv2d and ConvTranspose2d to 1d.

My code is: 

```
 def conv(c_in, c_out, k_size, stride=2, pad=1, bn=True):
    """Custom convolutional layer for simplicity."""
    layers = []
    layers.append(nn.Conv1d(c_in, c_out, k_size, (stride, 1), pad, (0, 0)))
    if bn:
        layers.append(nn.BatchNorm1d(c_out))
    return nn.Sequential(*layers)

def deconv(c_in, c_out, k_size, stride=2, pad=1, bn=True):
    """Custom deconvolutional layer for simplicity."""
    layers = []
    layers.append(nn.ConvTranspose1d(c_in, c_out, (k_size, 1), (stride, 1), pad, (0, 0)))
    if bn:
        layers.append(nn.BatchNorm1d(c_out))
    return nn.Sequential(*layers)

##################################
# Define Networks
##################################
# ===== Encoder ===========
class Q_net(nn.Module):
     def __init__(self, conv_dim=64):
         super(Q_net, self).__init__()
         self.conv1 = conv(2, conv_dim, 4, bn=False)
         self.conv2 = conv(conv_dim, conv_dim*2, 4)
         self.conv3 = conv(conv_dim*2, conv_dim*4, 4)
         self.conv4 = conv(conv_dim*4, conv_dim*8, 4)
         self.fc_2 = conv(conv_dim*8, z2_dim, 4, 1, 0, False) #int(image_size/16), 1, 0, False)
         self.fc_cat = conv(conv_dim*8, n_classes, 4, 1, 0, False) #int(image_size/16), 1, 0, False)

     def forward(self, x):                         # If image_size is 64, output shape is as below.
         print("x.shape", x.size())
         out = F.leaky_relu(self.conv1(x), 0.05)    # (?, 64, 32, 32)
         out = F.leaky_relu(self.conv2(out), 0.05)  # (?, 128, 16, 16)
         out = F.leaky_relu(self.conv3(out), 0.05)  # (?, 256, 8, 8)
         out = F.leaky_relu(self.conv4(out), 0.05)  # (?, 512, 4, 4)
         z_2 = self.fc_2(out).squeeze()                #(?, z2_dim, 1, 1)
         zcat = F.softmax(self.fc_cat(out).squeeze())  #(?, n_classes, 1, 1)
         return zcat, z_2


# ========= Decoder ============
class P_net(nn.Module):
    """Generator containing 7 deconvolutional layers."""
    def __init__(self, z_dim=z2_dim+n_classes, conv_dim=64):
        super(P_net, self).__init__()
        self.fc = deconv(z_dim, conv_dim*8, 4, 1, 0, bn=False)
        self.deconv1 = deconv(conv_dim*8, conv_dim*4, 4)
        self.deconv2 = deconv(conv_dim*4, conv_dim*2, 4)
        self.deconv3 = deconv(conv_dim*2, conv_dim, 4)
        self.deconv4 = deconv(conv_dim, 2, 4, bn=False)

    def forward(self, z):
        print("z.size:", z.size())
        z = z.view(z.size(0), z.size(1), 1, 1)      # If image_size is 64, output shape is as below.
        print("z.size:", z.size())
        out = self.fc(z)                            # (?, 512, 4, 4)
        out = F.leaky_relu(self.deconv1(out), 0.05)  # (?, 256, 8, 8)
        out = F.leaky_relu(self.deconv2(out), 0.05)  # (?, 128, 16, 16)
        out = F.leaky_relu(self.deconv3(out), 0.05)  # (?, 64, 32, 32)
        out = self.deconv4(out) #F.tanh(self.deconv4(out)) # (?, 2, 64, 64)
        return out
```

Notice that in conv and deconv functions I had to add a 2nd dimenstion for kernel, stride and dilation otherwise I get these errors:

RuntimeError: output adjustment must be smaller than stride, but got adjH: 0 adjW: 32642 dH: 1 dW: 1 at /py/conda-bld/pytorch_1490903321756/work/torch/lib/THNN/generic/S

RuntimeError: dilation should be greater than zero, but got dilationH: 0, dilationW: 0 at /py/conda-bld/pytorch_1490903321756/work/torch/lib/THNN/generic/SpatialDilatedC

When I add the 2nd dimension to these 3 parameters I get these error:
File "/home/c3po/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 62, in conv1d
    return f(input, weight, bias)
RuntimeError: expected 3D tensor

What drives me mad is that in the doc there is not much info on input & parameters details so it is a guess work.

Thanks for pytorch which is an amazing tool.

ps: code is partially badly shown. No idea why is that.

**Comment by educob** [comment]
Please help.
I cannot continue until I solve this 2d error messages.

**Comment by soumith** [comment]
https://discuss.pytorch.org

This is where generally folks ask for help. Sorry if that was not clear on our website.
I'll happily follow up there.

**Comment by soumith** [comment]
There's a section called Parameters and a section called Shape.
http://pytorch.org/docs/nn.html#conv1d

I would assume Shape would be sufficient to understand things, but if it's not, please let us know what else you'd want to see there so that we can improve the docs.

**Comment by educob** [comment]
Thanks for answering.

I think the shape is ok: 
printing it gives:
x.shape torch.Size([100, 2, 64])
batch_size = 100
channels_in = 2
sequence_lenth = 64 
I think they are ok. Aren't they?

And besides that what about these errors: ?
RuntimeError: output adjustment must be smaller than stride, but got adjH: 0 adjW: 32642 dH: 1 dW: 1 at /py/conda-bld/pytorch_1490903321756/work/torch/lib/THNN/generic/S

RuntimeError: dilation should be greater than zero, but got dilationH: 0, dilationW: 0 at /py/conda-bld/pytorch_1490903321756/work/torch/lib/THNN/generic/SpatialDilatedC

Something must be wrong if I have to make the call like this:
nn.ConvTranspose1d(c_in, c_out, **(k_size, 1)**, **(stride, 1)**, **pad, (0, 0)**)

Maybe the shape error is also a bug.
