### ISSUE TITLE
storage_initialized() ASSERT FAILED when I execute tensor.resize_(-1)

### ISSUE THREAD

**Issue by LongPham7** [pytorch/pytorch#16806]
## 🐛 Bug

When I execute `tensor.resize_(-1)`, I get a run-time error message that tells me to report the bug: `RuntimeError: storage_initialized() ASSERT FAILED at ..\aten\src\ATen/core/TensorImpl.h:656, please report a bug to PyTorch`. Because `-1` is not a valid argument to `resize_()`, it is reasonable that we get an error. However, the above error message seems to suggest that this error is not handled properly in the source code.  

## To Reproduce

1. `import torch`
2. `x = torch.Tensor([1, 2, 3, 4])`
3. `x.resize_(-1)`

## Expected behavior

A proper error message should have been issued. 

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.0
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.6.2
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

**Comment by ezyang** [comment]
Thanks for the report! Happy to review a PR on this.

**Comment by aricheto** [comment]
Thank

**Comment by nmilosev** [comment]
Hey, could I try working on this one? Seems simple enough to get started. :)

**Comment by ezyang** [comment]
@nmilosev yes go for it! Add me as reviewer when you do it

**Comment by nmilosev** [comment]
@ezyang this seems to be fixed already.

```
>>> x.resize_(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/milosevicn/contrib/pytorch/torch/tensor.py", line 84, in __repr__
    return torch._tensor_str._str(self)
  File "/home/milosevicn/contrib/pytorch/torch/_tensor_str.py", line 310, in _str
    tensor_str = _tensor_str(self, indent)
  File "/home/milosevicn/contrib/pytorch/torch/_tensor_str.py", line 209, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/milosevicn/contrib/pytorch/torch/_tensor_str.py", line 79, in __init__
    tensor_view = tensor.reshape(-1)
RuntimeError: Trying to create tensor with negative dimension -1: [-1]
```

Probably close this issue then, I will find something else suitable, or you can point me to it. I've got the whole env ready :)

**Comment by ezyang** [comment]
Thanks. Maybe take a look at this one: https://github.com/pytorch/pytorch/issues/14959 (there's a few parts, but one easy bit is putting the device guards in torch namespace, somewhere).
