### ISSUE TITLE
Scriptmodule version of trace

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#16801]
## 🚀 Feature

It could be useful to know the pytorch/jit code version that emitted a .pt file
## Motivation
If you store traced `.pt` files you want know what was the pytorch/jit from witch they was generated. Currently seems it is not possible.

## Pitch
When we save and load a traced model we could have an API to store retrieve the version.

## Alternatives
Save these metadata yourself

**Comment by wanchaol** [comment]
Thanks for reporting this! We will discuss about this early next week to get back to you.

**Comment by suo** [comment]
We don't have the bandwidth to do this now, but various easy workarounds are available (use a constant, write the version to the file name, track it separately yourself, etc.). 

Going to close this right now, but if anyone feels there is a widespread need for this feature, please reopen and comment with your use case.

**Comment by bhack** [comment]
@suo With all these custom alternatives how  we will handle trace compatibility break?
Could be tracked, as proxy, to the semantic version of pytorch?

**Comment by wanchaol** [comment]
I think trace compatibility won't break if you use the serialization/deserialization that JIT provide, we will actively maintain the backward compatability to ensure nothing breaks. Also JIT serialization encode operator version, which provides some sort of compatibilities on operator versioning.
