### ISSUE TITLE
torch.arange failing for large inputs

### ISSUE THREAD

**Issue by zkolter** [pytorch/pytorch#1681]
When I call torch.arange() for large inputs, it seems to have a bizarre upper limit.  On version 0.1.12_2.

```python
a = torch.arange(0, 20000000)
print(a[-1], a[-2])
""" Outputs:
16777216.0 16777216.0
"""
```

My current workaround.  Since I want integer ranges, this seems to work fine:
```python
a = torch.ones(20000000).nonzero().squeeze()
print(a[-1], a[-2])
""" Outputs:
19999999 19999998
"""
```

Edit: Ok, should have done a quick Google search before posting.  32 bit floats can't represent higher precision than that.  I'll modify this to be a possible (low-priority) request to simply have an integer version of range, for this reason.

**Comment by fmassa** [comment]
You can have integer range by passing the `out` argument.
```python
out = torch.LongTensor()
torch.arange(0, 200000, out=out)
```

**Comment by zkolter** [comment]
Ah, thanks, even better!
