### ISSUE TITLE
How to call libtorch(cuda) in multi-thread?

### ISSUE THREAD

**Issue by hijkzzz** [pytorch/pytorch#16816]
I found that the multithreaded call libtorch(cuda ) seemed to be executed serially.
Is there any way to parallel?
thanks.

**Comment by ezyang** [comment]
Hi @hijkzzz; do you have any sample code you could share?

**Comment by SsnL** [comment]
streams? :)

**Comment by hijkzzz** [comment]
> Hi @hijkzzz; do you have any sample code you could share?

https://github.com/hijkzzz/alpha-zero-gomoku/blob/master/src/libtorch.cpp

I call NeuralNetwork:: infer in multiple threads(use GPU), but found that using the CPU faster.
And GPU usage is almost the same as single-threaded.
thanks.

**Comment by hijkzzz** [comment]
> streams? :)

I am trying to use it, but i only found  torch.cuda.streams in python
where is the document about torch::cuda::streams in c++ api?
thanks

**Comment by hijkzzz** [comment]
```
......
// infer
  torch::Tensor states = torch::cat({state0, state1, state2, state3}, 1);

  if (this->use_gpu) {
    // get a CUDA stream
    at::cuda::CUDAStream stream = at::cuda::getStreamFromPool();
    at::cuda::setCurrentCUDAStream(stream);

    states = states.to(at::kCUDA);
  }

  std::vector<torch::jit::IValue> inputs{states};
  auto result = this->module->forward(inputs).toTuple();
```
when i run it, there is some memory error~
so, is there a tutorial about streams C++ API?

**Comment by hijkzzz** [comment]
related issue #16614

**Comment by YirongMao** [comment]
@ezyang Hi, is there any progress or solution for this issue. I also encounter the same problem in libtorch 1.5.1 + cuda9

**Comment by hijkzzz** [comment]
> @ezyang Hi, is there any progress or solution for this issue. I also encounter the same problem in libtorch 1.5.1 + cuda9

You should combine all tasks and push them to libtorch at once.

**Comment by YirongMao** [comment]
> > @ezyang Hi, is there any progress or solution for this issue. I also encounter the same problem in libtorch 1.5.1 + cuda9
> 
> You should combine all tasks and push them to libtorch at once.

In single-thread? Or could you share some sample code ?
