### ISSUE TITLE
Namedtuples and compatibility for python < 3.2

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#16813]
Just discussed with python developer in https://bugs.python.org/issue35914. 

Starting from https://github.com/pytorch/pytorch/pull/15429, the return of some operators starts to switch from tuple to structseq. Object of structseq is not a tuple on python version < 3.2. Making structseq a subtype of tuple is an enhancement rather than a bugfix for python, so old python versions would never get that feature.

This results in compatibility issue that all user codes that rely on tuple check would fail on these python versions, examples are:

```python
a = tensor.max(dim=0)
if isinstance(a, tuple):
    print("I am a tuple")
```

Also in our code, there are many places that rely on `PyTuple_Check`, which would also fail on structseq. Currently, we are doing a workaround by creating `six::isTuple` and `_six.is_tuple`, to replace failed tuple checks discovered by unit tests. But there are still many tuple checks not handling structseq yet, as discussed in https://github.com/pytorch/pytorch/pull/15429#discussion_r253186184, which might lead to strange behaviors.

cc: @apaszke

**Comment by zasdfgbnm** [comment]
How do we deal with this issue? Do we: 

1. on Python < 3.2, just make python these ops tuples without names, and only enable namedtuple return on python > 3.2, or
2. return structseq on Python < 3.2, break the user code mentioned, and walk through all the occurrence of `PyTuple_Check` and add cases for structseq?

**Comment by ezyang** [comment]
We don't officially support Python <3.5, IIRC. I don't think having this broken in this case is a big deal. But if there is evidence to the contrary, I might reconsider.

**Comment by zasdfgbnm** [comment]
@ezyang python < 3.2 includes 2.7, which is still taking bugfixes, but I don't think this issue they consider a bug.

**Comment by ezyang** [comment]
OK, sorry, I completely misunderstood :)

I think if I had to pick between "disable named tuples solely on 2.7" and "BC-breaking change for Python 2.7 users only", I'd prefer the latter. This preference is tempered by the fact that, apparently, we have a big pile of unsound tuple checks in PyTorch codebase. But if PyTorch is the *only* place we have to deal with these, that's fine, and we should just rip the bandaid off (grepping for the bad functions is pretty easy.)

**Comment by zasdfgbnm** [comment]
This is the result of `grep PyTuple_Check -r .` under the `torch` directory.
```
./csrc/autograd/python_engine.cpp:  THPUtils_assert(PyTuple_Check(tensors), "tensors argument is expected to "
./csrc/autograd/python_engine.cpp:  THPUtils_assert(PyTuple_Check(grad_tensors), "grad_tensors argument is "
./csrc/autograd/python_function.h:  if (PyTuple_Check(obj.get()))
./csrc/autograd/python_hook.cpp:  if (!PyTuple_Check(result)) {
./csrc/autograd/python_function.cpp:  THPFunction_assert(PyTuple_Check(self->dirty_tensors), "autograd "
./csrc/autograd/python_function.cpp:  THPFunction_assert(PyTuple_Check(self->to_save), "autograd internal "
./csrc/autograd/python_function.cpp:  THPFunction_assert(PyTuple_Check(self->non_differentiable), "autograd "
./csrc/autograd/python_function.cpp:    if (!PyTuple_Check(raw_grad_output) || !PyBool_Check(retain_variables)) {
./csrc/autograd/python_variable_indexing.cpp:  if (PyTuple_Check(index)) {
./csrc/utils/invalid_arguments.cpp:    if (!PyTuple_Check(object)) return false;
./csrc/utils/tuple_parser.cpp:  if (!PyTuple_Check(obj)) {
./csrc/utils/tuple_parser.cpp:  if (PyTuple_Check(obj)){
./csrc/utils/pybind.h:    auto tuple = PyTuple_Check(source);
./csrc/utils/python_arg_parser.h:  auto tuple = PyTuple_Check(arg);
./csrc/utils/python_arg_parser.cpp:      if (PyTuple_Check(obj) || PyList_Check(obj)) {
./csrc/utils/six.h:  if (PyTuple_Check(input.ptr())) {
./csrc/jit/pybind_utils.h:      if (!PyTuple_Check(obj.ptr()))
./csrc/DataLoader.cpp:  if (!PyTuple_Check(child_pids)) {
./csrc/Size.cpp:  if (PyTuple_Check(result.get())) {
./csrc/utils.cpp:  bool tuple = PyTuple_Check(arg);
./csrc/utils.cpp:  bool tuple = PyTuple_Check(arg);
./csrc/utils.cpp:  if (!PyTuple_Check(arg)) {
./include/torch/csrc/autograd/python_function.h:  if (PyTuple_Check(obj.get()))
./include/torch/csrc/utils/pybind.h:    auto tuple = PyTuple_Check(source);
./include/torch/csrc/utils/python_arg_parser.h:  auto tuple = PyTuple_Check(arg);
./include/torch/csrc/utils/six.h:  if (PyTuple_Check(input.ptr())) {
./include/torch/csrc/jit/pybind_utils.h:      if (!PyTuple_Check(obj.ptr()))
./include/pybind11/pytypes.h:    PYBIND11_OBJECT_CVT(tuple, object, PyTuple_Check, PySequence_Tuple)
./include/pybind11/pytypes.h:class args : public tuple { PYBIND11_OBJECT_DEFAULT(args, tuple, PyTuple_Check) };
```

**Comment by zasdfgbnm** [comment]
The first two line
```
./csrc/autograd/python_engine.cpp:  THPUtils_assert(PyTuple_Check(tensors), "tensors argument is expected to "
./csrc/autograd/python_engine.cpp:  THPUtils_assert(PyTuple_Check(grad_tensors), "grad_tensors argument is "
```
There is no need to change anything, because they are inside `THPEngine_run_backward`, whose input is constructed by `torch.autograd.backward`, which is guaranteed not to be a structseq.

**Comment by zasdfgbnm** [comment]
The three lines in python arg parser is fixed in https://github.com/pytorch/pytorch/pull/17208:
```
./csrc/utils/python_arg_parser.cpp:    case ParameterType::TENSOR_LIST: return PyTuple_Check(obj) || PyList_Check(obj);
./csrc/utils/python_arg_parser.cpp:      if (PyTuple_Check(obj) || PyList_Check(obj)) {
./csrc/utils/python_arg_parser.h:  auto tuple = PyTuple_Check(arg);
./csrc/utils/python_arg_parser.h:  auto tuple = PyTuple_Check(arg);
./csrc/utils/python_arg_parser.h:  auto tuple = PyTuple_Check(arg);
```

**Comment by zasdfgbnm** [comment]
I am currently reading these lines of tuple checks and report the unexpected behavior right now.

**Comment by zasdfgbnm** [comment]
@ezyang I think we need to reopen this
