### ISSUE TITLE
[JIT] Support mutable operators in shape analysis

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#16836]
![image](https://user-images.githubusercontent.com/4685384/52395641-ccf13700-2a63-11e9-92bc-239319a6fc5f.png)

It doesn't look like in-place operators participate in shape propagation

<sleepy now, will probably flesh this out later>

**Comment by suo** [comment]
When the graph has mutable ops nodes are not referentially transparent, which makes shape analysis tricky (since we run the op in order to find the shape).

**Comment by apaszke** [comment]
It's not the case. We actually have symbolic formulas for most of our ops, and hardly every run anything now.

**Comment by suo** [comment]
Ah ok. In that case we can fix this pretty easily by adding symbolics for the in-place versions of the op, yes? And we can still disallow running nodes that affected by mutation.

**Comment by apaszke** [comment]
Yep

**Comment by suo** [comment]
Closing this as profiling is expected to replace shape analysis.
