### ISSUE TITLE
Unable to configure pytorch with cmake on Windows platform

### ISSUE THREAD

**Issue by positivcheg94** [pytorch/pytorch#16841]
## 🐛 Bug

MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj
CMake Error at third_party/FP16/CMakeLists.txt:94 (ADD_SUBDIRECTORY):
The source directory
    D:/git_clones/pytorch/build/confu-srcs/psimd
does not contain a CMakeLists.txt file.

## To Reproduce

Simply let me configure it

just doing cmake .. from "build" subdirectory

## Expected behavior

I expect it to work properly as on linux machine

## Environment

Current HEAD, Windows machine.

**Comment by peterjc123** [comment]
Is your clone complete? Would you please do `git submodule update --init --recursive` first?

**Comment by positivcheg94** [comment]
> Is your clone complete? Would you please do `git submodule update --init --recursive` first?

I do this `git clone https://github.com/pytorch/pytorch.git --recursive`. Which picks all submodules, but the issue seems to be with this particular psimd. Because if I manually copy this dir into D:/git_clones/pytorch/build/confu-srcs/psimd from third-party it works properly.

**Comment by peterjc123** [comment]
The download process of `psimd` should be done using CMake, which is different from other submodules. cc @orionr @ezyang

**Comment by peterjc123** [comment]
By checking `cmake/Dependencies.cmake` and `third_party/FP16/CMakeLists.txt`, it seems that `PSIMD_SOURCE_DIR` is set to `third_party/psimd`, and then in the latter file, if the previous variable is unset, it will download it into a default location, but, if it isn't, it won't be downloaded.

**Comment by positivcheg94** [comment]
> CMake

But I've got this repo after simply doing git clone.

Submodule path 'third_party/psimd': checked out '90a938f30ba414ada2f4b00674ee9631d7d85e19'

So like that's really strange.

**Comment by peterjc123** [comment]
@positivcheg94 It only happens when you try to clone it with `--recursive`? In that way, it's weird and I think the problem is not on our side.
