### ISSUE TITLE
Attempting to install pytorch-nightly on conda py37 env pulls pytorch py27

### ISSUE THREAD

**Issue by edran** [pytorch/pytorch#16840]
## 🐛 Bug

As per title, attempting to install pytorch-night in a conda environment shipped with python 3.7 pulls pytorch py2.7, and for extra fun breaks also the environment by doing:

```
    certifi:         2018.11.29-py37_0                 --> 2018.11.29-py27_0
    pip:             19.0.1-py37_0                     --> 19.0.1-py27_0
    setuptools:      40.7.3-py37_0                     --> 40.7.3-py27_0
    wheel:           0.32.3-py37_0                     --> 0.32.3-py27_0
```

As you might imagine, hilarity ensues after attempting to utilise the environment in any way.

## To Reproduce

1. conda create -n pytorch-master python=3.7
2. source activate pytorch-master
3. conda install pytorch-nightly -c pytorch
```
$ conda install pytorch-nightly -c pytorch

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.2

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/nantas/.conda/envs/pytorch-nightly

  added / updated specs:
    - pytorch-nightly


The following NEW packages will be INSTALLED:

    blas:            1.0-mkl
    cffi:            1.11.5-py27h6174b99_1
    intel-openmp:    2019.1-144
    libgfortran:     3.0.1-h93005f0_2
    mkl:             2019.1-144
    mkl_fft:         1.0.10-py27h5e564d8_0
    mkl_random:      1.0.2-py27h27c97d8_0
    ninja:           1.8.2-py27h04f5b5a_1
    numpy:           1.15.4-py27hacdab7b_0
    numpy-base:      1.15.4-py27h6575580_0
    pycparser:       2.19-py27_0
    pytorch-nightly: 1.0.0.dev20190205-py2.7_0 pytorch

The following packages will be UPDATED:

    certifi:         2018.11.29-py37_0                 --> 2018.11.29-py27_0
    pip:             19.0.1-py37_0                     --> 19.0.1-py27_0
    setuptools:      40.7.3-py37_0                     --> 40.7.3-py27_0
    wheel:           0.32.3-py37_0                     --> 0.32.3-py27_0

The following packages will be DOWNGRADED:

    python:          3.7.2-haf84260_0                  --> 2.7.15-h8f8e585_6
```

## Expected behavior

* Install pytorch-nightly for python3.7
* Don't kill the environment by pulling python2.7 packages

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Mac OSX 10.14.2
GCC version: Could not collect
CMake version: version 3.13.3

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] # packages in environment at /Users/nantas/.conda/envs/pytorch-nightly:
## Additional context

Conda version: 4.5.12

**Comment by soumith** [comment]
this was fixed
