### ISSUE TITLE
[JIT] Directly using Argument constructors in caffe2 operator definitions does not scale.

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#16865]
Recent changes have added declarations like this to caffe2 operators:

https://github.com/pytorch/pytorch/blob/7ba4aaeacaaa90ba0e41b6a397cf2b92a4d96f7a/caffe2/operators/layer_norm_op.cc#L189

If left unchanged we will eventually have hundreds of sites in the codebase that directly use the constructors for Argument. This API is not intended to be widely used and is very hard to refactor. Furthermore direct use of these constructors as literals bloats compiler time.** Instead, we expect people to write schema declarations, e.g.:
 https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/register_prim_ops.cpp#L284

These are user-exposed and we expect to provide some degree of stability. 

@smessmer @bwasti @dzhulgakov 

** We previously used the direct construct approach in the JIT and it ended up constributing 2 minutes of compile time overhead to build.

**Comment by dzhulgakov** [comment]
So the argument against using string function schemas is that it'd require us to ship parser on mobile deployments and it can unnecessary code size penalty. That being said, we should verify how big it actually is.

Another option is to use "c++ function signature" -> "function schema" template magic that JIT custom ops use. It'd help with avoiding non-public API but likely will make compile time even worse.

P.S. How come it adds 2 mins to the build? It sounds insane.

**Comment by zdevito** [comment]
Discussed in person:
* binary size of explicit constructors is much larger than a string and is one of the reasons for slow compile times doing it this way in the past.
* We should investigate pulling a minimal lexer.h tree.h and schema_parser.cpp (pulled out of operator.cpp) out and seeing how big it is.
* Changes should largely be isolated to the build and avoid moving the files out of the csrc/jit folder  since this has been disruptive in the past.

**Comment by smessmer** [comment]
I agree with points 1 and 2, but I don't agree with point 3. I don't think it's a good idea to have code in c10/ depend on code that lives in csrc/jit/.

**Comment by zdevito** [comment]
I strongly disagree. The changes needed would pull _core concepts of the compiler_ such as the lexer, tokens, the list of valid token identifiers, and SourceRange objects out of the location where people would expect to find these components.  They are primarily used the compiler and serve a secondary role in schema parsing. File movement in the past has been disruptive to developers in JIT and harmful for code understanding. For instance, it is already the case that no one on the project can find our type system because it exists buried on some c10 folder with a header file whose name does not match its cpp file.  These are actual, already felt, downsides.

**Comment by smessmer** [comment]
Refactorings always come at a cost for people having to learn the new structure. In the long term they're still worth it. However, for that it needs to be clear that the new structure is better than the old one.
I agree we shouldn't pull compiler specifics into c10, that doesn't belong there. We can, however, pull a generic lexer and generic parser into c10, move the function schema parser as well, and have the JIT parser (which is using these generic parts) stay in JIT. That would be a better structure and worth the refactoring.
