### ISSUE TITLE
Forward attribute access on DataParallel to underlying `module` attribute.

### ISSUE THREAD

**Issue by manuyavuz** [pytorch/pytorch#16885]
## 🚀 Feature

Forward attribute access on a `DataParallel` object to underlying `module` attribute using Python descriptors `__get__` `__set__`.
## Motivation

Currently, when you wrap your model using `DataParallel` class, you would need to change all attribute access to your original model from `model.attr` to `model.module.attr` as suggested here: https://discuss.pytorch.org/t/how-to-reach-model-attributes-wrapped-by-nn-dataparallel/1373

This might result in a lot changes in your code when you want to extend your model to multiple GPUs, rather than just adding `model = nn.DataParallel(model)` line, which is a super quick way of adding multi-GPU support.

To overcome this difficulty, we can forward access to properties not belonging to `DataParallel` object toward it's underlying `module` attribute, and we can fail it module object also does not have such an attribute.

## Pitch

Be able to continue using `model.custom_attr` after I wrap `model` with `DataParallel` using `model = nn.DataParallel(model)`.
## Alternatives

Convert all attribute access to your model from `model.custom_attr` to `model.module.custom_attr`.

## Additional context

If core team is OK with this approach, I can prepare a PR with this feature.

**Comment by theophilee** [comment]
This would be a great feature!

**Comment by ailzhang** [comment]
CC: @apaszke , do you have any insights on this?

**Comment by apaszke** [comment]
I'm a bit split on this really. On one hand I would like to have `nn.DataParallel` be an invisible wrapper around a module that keeps all the APIs the same, on the other hand propagating attrs through `__getattr__` gets us to some weird places. What if you want to set an attribute? Does this write through the module as well? We won't be able to forward everything perfectly too, because of possible clashes of attribute names (although I guess this one can be fixed by using internal attrs, which is a breaking change). It's a hard decision, but I'd lean on the side of keeping it as is. If you want the fall-through behavior you can always do this as a workaround:

```py
class MyDataParallel(nn.DataParallel):
    def __getattr__(self, name):
        return getattr(self.module, name)
```

**Comment by manuyavuz** [comment]
I was thinking more like `nn.DataParallel` actually being a proxy module which forwards anything to underlying `module` attribute, and doing its data split operation as an internal behavior, where even pytorch classes don't use anything inside `nn.DataParallel`. I think all data split logic even can go into another class such as `DataParallelizer`, and `nn.DataParallel` could call methods from that class in `forward` method.

Why would it be a breaking change? Are there other pytorch classes using attributes of `nn.DataParallel` class itself?

**Comment by apaszke** [comment]
Probably not other PyTorch classes, I'm more afraid of user scripts accessing `.devices` or some other attributes (which were not private previously). Also, you will still keep getting clashes on `.module`, because I really think there should be a way to retrieve the wrapped module as well. Finally, doing that would require us to hack around how state_dicts are built which is pretty bad too. I'm really ambivalent about this.

**Comment by manuyavuz** [comment]
I assume you are mentioning this issue about `state_dict`: https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/2

From @fmassa:
> You probably saved the model using nn.DataParallel, which stores the model in module, and now you are trying to load it without DataParallel. You can either add a nn.DataParallel temporarily in your network for loading purposes, or you can load the weights file, create a new ordered dict without the module prefix, and load it back.

I think `DataParallel` can just have two attributes, `module` and `parallelizer`, and forwards any other calls to `module` attribute (Parallelizer can even be implemented via mixin pattern so that there is no attributes, not sure). Because it still has `module` as attribute, I don't think it would break `state_dict` logic (of course I might be missing some implementation detail that I am not aware of).

You are right that if the original module also has a `module` attribute, it's not clear that it would have to be accessed via `model.module.module`.

I still feel like having a DataParallel working as the suggested way could be really helpful for developers. But I also understand your concerns.

Then, I think DataParallel documentation and tutorial should be updated to remind that if you are accessing any attributes from the original module, you will need to change your code accordingly. Currently, it feels like the only thing that need to be done is `model = nn.DataParallel(model)` for any case.

**Comment by apaszke** [comment]
Wait, so you're suggesting we forward the attributes, but keep the same `state_dict` behavior? That feels weird, because the keys in `state_dict` are supposed to reflect how you access parameters from Python.

**Comment by apaszke** [comment]
Regarding the tutorial, agreed. Please do send a PR if you have time.

**Comment by keunwoochoi** [comment]
@apaszke I made a PR, but I think it'd be nicer if there's a link for the code where people can see what kinds of attributes `DataParallel` adds so that they can avoid using the same name.

**Comment by manuyavuz** [comment]
@keunwoochoi thanks for the PR! I was overwhelmed in last month, couldn't find time to do it.

@apaszke I think we can pass this for now, currently I don't have a very clear implementation idea without introducing breaking changes or other possible subtle problem which I still guess would be rare. Gonna keep still as a nice-to-have feature idea.

**Comment by andrewnaguib** [comment]
@manuyavuz I can give a hand if this would help :)

**Comment by andrewnaguib** [comment]
@apaszke, your workaround does not seem to be working properly.

**Comment by dniku** [comment]
A shorter one:

```python
class DataParallelPassthrough(torch.nn.DataParallel):
    def __getattr__(self, name):
        try:
            return super().__getattr__(name)
        except AttributeError:
            return getattr(self.module, name)
```

**Comment by rudaoshi** [comment]
this solution is not working on 1.9, since self.module is None.
