### ISSUE TITLE
assertion fails when exporting to onnx

### ISSUE THREAD

**Issue by rajarsheem** [pytorch/pytorch#16895]
I am using pytorch nightly and when I am trying to export my model to ONNX, I get the following error. Can you please help? Please let me know if you want to know anything.

File "/home/ramitra2/.conda/envs/deep/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 562, in softmax
    dim = input.type().dim() + dim
RuntimeError: r ASSERT FAILED at /opt/conda/conda-bld/pytorch-nightly_1549566607935/work/aten/src/ATen/core/jit_type.h:135, please report a bug to PyTorch. (expect at /opt/c
onda/conda-bld/pytorch-nightly_1549566607935/work/aten/src/ATen/core/jit_type.h:135)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fb75ebe29e5 in /home/ramitra2/.conda/envs/deep/lib/python3.6/site-packages/torch/lib/libc10.s
o)
frame #1: std::shared_ptr<c10::DimensionedTensorType const> c10::Type::expect<c10::DimensionedTensorType>() const + 0x207 (0x7fb782410e87 in /home/ramitra2/.conda/envs/deep/
lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x39e5c7 (0x7fb78247a5c7 in /home/ramitra2/.conda/envs/deep/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x113e26 (0x7fb7821efe26 in /home/ramitra2/.conda/envs/deep/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #26: <unknown function> + 0x177ac4 (0x7fb782253ac4 in /home/ramitra2/.conda/envs/deep/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #27: torch::jit::BlockToONNX(torch::jit::Block*, torch::jit::Block*, torch::onnx::OperatorExportTypes, std::unordered_map<torch::jit::Value*, torch::jit::Value*, std::
hash<torch::jit::Value*>, std::equal_to<torch::jit::Value*>, std::allocator<std::pair<torch::jit::Value* const, torch::jit::Value*> > >) + 0x4a0 (0x7fb782455000 in /home/ram
itra2/.conda/envs/deep/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #28: torch::jit::ToONNX(std::shared_ptr<torch::jit::Graph>&, torch::onnx::OperatorExportTypes) + 0x406 (0x7fb782456246 in /home/ramitra2/.conda/envs/deep/lib/python3.6
/site-packages/torch/lib/libtorch_python.so)
frame #29: <unknown function> + 0x375b19 (0x7fb782451b19 in /home/ramitra2/.conda/envs/deep/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #30: <unknown function> + 0x113e26 (0x7fb7821efe26 in /home/ramitra2/.conda/envs/deep/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #61: __libc_start_main + 0xf5 (0x7fb79d283f45 in /lib/x86_64-linux-gnu/libc.so.6)
frame #62: python() [0x4009e9]

**Comment by ngimel** [comment]
Closing due to age
