### ISSUE TITLE
Pytorch issue on Windows

### ISSUE THREAD

**Issue by FabyOfficial** [pytorch/pytorch#16898]
I try to install pytorch and after days of trying I`m here with a big, big problem. I read a lot of articles of "how to install pytorch" I try to install with pip install but don`t work for me and after I install it with Anaconda, but in anaconda is pytorch install, when I type: conda list, he is there like this form: pytorch                   1.0.1           py3.7_cuda100_cudnn7_1    pytorch, I have python 3.7, when I run a code with import torch this show me a message like this: 

![problem](https://user-images.githubusercontent.com/46923580/52486017-d2b15e80-2bc2-11e9-96d3-e2f96bda4154.PNG)

And when i try to import torch in python 3.7:

![fdzzddz](https://user-images.githubusercontent.com/46923580/52486084-eeb50000-2bc2-11e9-9bd1-6a95b8b331e3.PNG)

Pip install error:

![dsfdasad](https://user-images.githubusercontent.com/46923580/52486140-0a200b00-2bc3-11e9-8598-5505965aa7c2.PNG)

How to pass this errors? Please Help, thx.

**Comment by JamesTrick** [comment]
@FabyOfficial 

Thanks for the screenshots, it looks as though you may have the 32-bit installation of Python, in which case you're issue is this: #16633. Test is in that issue as well.

Just be aware, that [pyTorch doesn't work on 32-bit systems](https://pytorch.org/docs/stable/notes/windows.html#package-not-found-in-win-32-channel).

**Comment by liangbright** [comment]
try Python 3.7.1

**Comment by ailzhang** [comment]
@FabyOfficial  Could you use the script in our template to collect the environment info, if this is not a 32bit machine? Thanks!

**Comment by peterjc123** [comment]
It is because you are using 32 bit Python. Closing.
