### ISSUE TITLE
Number of CPU threads for the python process

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#16894]
For a test, I didn't use `--cuda` in order to run a cpu version. While the CPU has 8 physical cores (16 threads), I see 400% cpu utilization for the python process.

Is that normal? How can I control the number of threads?
I use `time python main.py  --epochs 1` in word_language_model

**Comment by ezyang** [comment]
In this case, you are seeing multithread usage from OpenMP parallelized CPU kernels, which run on multiple threads. You can control the number of threads with https://pytorch.org/docs/stable/torch.html#torch.set_num_threads although this was broken on some versions of PyTorch.  You can also try setting `OMP_NUM_THREADS=1` and `MKL_NUM_THREADS=1` if that doesn't work for you.

CC @SsnL, in case you have anything to add.

**Comment by SsnL** [comment]
@ezyang ‘s explanation & suggestion above is 100% correct!

**Comment by CoinCheung** [comment]
@ezyang @SsnL  I have tested both methods, but why does setting `torch.set_num_threads(1)` does not work, but using environment variables of `OMP_NUM_THREADS=1` and 'MKL_NUM_THREADS=1` would work ?

**Comment by CarelessParsley** [comment]
I mentioned that we accidentally broke `set_num_threads` on an older version of PyTorch. What version are you running on? (MKL controls MKL only so it won't affect our OpenMP parallelized kernels).

**Comment by ezyang** [comment]
I mentioned that we accidentally broke `set_num_threads` on an older version of PyTorch. What version are you running on? (MKL controls MKL only so it won't affect our OpenMP parallelized kernels).

**Comment by CoinCheung** [comment]
@ezyang 
I used pytorch installed with ananconda `conda install pytorch`, that would be 1.0 for now. Maybe it is the version that has this option broken. I will use the environment variable method. Thanks for explaining !!

**Comment by gchanan** [comment]
closing as this doesn't seem to be a current bug.
