### ISSUE TITLE
cpp api - IntList loses initial values

### ISSUE THREAD

**Issue by mhubii** [pytorch/pytorch#16903]
Hey, here is some super strange behaviour for `at::IntList` that I do not understand. I try to initialize a `at::IntList` of `class A` from `class B`.

Main
```cpp
#include <torch/torch.h>
#include <iostream>

class A {

public:

	A(torch::IntList list) : list_(list) { };

	void Print() { std::cout << list_ << std::endl; };

private:

	torch::IntList list_;
};


class B {

public:

	B(int64_t c, int64_t d) : a_({c, d}) { a_.Print(); };

	void Print() { a_.Print(); };

private:

	A a_;
};


int main() {

	B b(10, 10);

	b.Print();
	
	return 0;
}
```

The output is

```shell
[10, 10]
[140726518609664, 4206890]
```

CMake
```cmake
cmake_minimum_required(VERSION 3.11 FATAL_ERROR)

find_package(Torch REQUIRED)

include_directories(${Torch_INCLUDE_DIRS})

add_executable(main main.cpp)
target_link_libraries(main ${TORCH_LIBRARIES})
```

Is it a mistake or a bug? This thing blows up my whole code as libtorch trys to allocate tons of GB of RAM due to that.

**Comment by mhubii** [comment]
ok, if you switch from `at::IntList`, which is a `typedef` for `at::ArrayRef<int64_t>` to `at::ArrayRef<int>`, everything works fine. `at::IntList` seems to be depracted or something:man_shrugging:

**Comment by apaszke** [comment]
No, that's just UB and has nothing to do with the type you use. Basically, `ArrayRef`s don't own the memory (unlike e.g. `std::vector`s). So in your case, you construct an `ArrayRef` that points to the (stack allocated!) initializer list you pass to `a`, which is destructed immediately after the constructor finishes, so you end up using freed memory in `Print()`. Please use `std::vector` if you need to manage lifetime of your memory.

**Comment by ezyang** [comment]
By the way, this is why we deprecated IntList and now call it IntArrayRef :)
