### ISSUE TITLE
Unexpected set_num_threads behavior

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#16912]
## To Reproduce

```
>>> import torch
>>> torch.set_num_threads(8)
>>> torch.get_num_threads()
1
```

## Expected behavior

It'd be expected for `torch` to throw an error if `set_num_threads` failed or for `get_num_threads` to reflect `set_num_threads`.

```
>>> import torch
>>> torch.set_num_threads(8)
>>> torch.get_num_threads()
8
```

## Environment

Collecting environment information...
PyTorch version: 1.1.0a0+54c981d
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.1
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] numpydoc==0.8.0
[pip] torch==1.1.0a0+54c981d
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] mkl-service               1.1.2            py37hfbe908c_5
[conda] mkl_fft                   1.0.6            py37h27c97d8_0
[conda] mkl_random                1.0.2            py37h27c97d8_0
[conda] torch                     1.1.0a0+54c981d          pypi_0    pypi

**Comment by soumith** [comment]
https://github.com/pytorch/pytorch/pull/16427 and https://github.com/pytorch/pytorch/pull/15425 should fix the issue on master.
On 1.0.1, we shipped a patch that fixes it as well.

**Comment by SsnL** [comment]
> It'd be expected for `torch` to throw an error if `set_num_threads` failed or for `get_num_threads` to reflect `set_num_threads`.

After #16427 is done, we will throw a warning.

**Comment by ngimel** [comment]
Closing due to age, please reopen if bug is still present
