### ISSUE TITLE
ninja: error: '../aten/src/ATen/code_template.py', needed by 'aten/src/ATen/CPUByteType.cpp', missing and no known rule to make it

### ISSUE THREAD

**Issue by Nerothos** [pytorch/pytorch#16925]
## 🐛 Bug

Hello,
I have a problem when I try to build pytorch on windows 10.
I have VS2017 15.9.6 installed, CUDA 10, python 3.7 64 bits.
I have anaconda installed too.

## To Reproduce

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1
call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.16
python setup.py install

```
Building wheel torch-1.1.0a0+23e1c55
-- Building version 1.1.0a0+23e1c55
ninja: error: '../aten/src/ATen/code_template.py', needed by 'aten/src/ATen/CPUByteType.cpp', missing and no known rule to make it
Traceback (most recent call last):
  File "setup.py", line 720, in <module>
    build_deps()
  File "setup.py", line 279, in build_deps
    build_dir='build')
  File "E:\pytorch\tools\build_pytorch_libs.py", line 235, in build_caffe2
    cwd=build_dir, env=my_env)
  File "C:\Users\Nerothos\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '7']' returned non-zero exit status 1.
```

## Expected behavior

Building is working

## Environment

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 970
Nvidia driver version: 416.34
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.1
[conda] Could not collect
```

## Additional context

I cannot find the file CPUByteType.cpp either locally or in the repository
I'm using  -vcvars_ver=14.16 because 14.11 is not working.

Regards

**Comment by peterjc123** [comment]
Hey, would you please check if 'aten/src/ATen/code_template.py' exists? If it doesn't, please clone again.

**Comment by Nerothos** [comment]
Hi,
This file exist but not the CPUByteType.cpp one.
I have redone the manipulation and cloning again but I have the same problem.

**Comment by fa15073** [comment]
double check cmake installed with vs2017 is running (uncheck it in the installer if you don't really need it)
the one installed via anaconda should work
btw, 14.11 should work too

**Comment by Nerothos** [comment]
I got the compilation running.
I'm not sure what changed but this are the 3 actions that I have done :
- Installed linux tool with VS Studio Installer
- Launched the CMD in admin mode
- Cloned the repo once again (maybe something fixed it)

For 14.11 it wouldn't work even when installing the package (which was missing because I had an more recent one).

Thanks for the help.
