### ISSUE TITLE
CUDA tensors sent over multiprocessing channel don't synchronize

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#16926]
@VitalyFedyunin noticed that when he stress tests sending CUDA tensors over multiprocessing, on occasion the tensor contents get corrupted. We further observed that inserting a synchronization before sending a CUDA tensor, we avoid the corruption. The guess is that we are not properly synchronizing CUDA tensors that get sent to other processes, and CUDA kernels queued on another process don't end up on the same stream as the originating one. This needs verification, however.

Vitaly, if you want to fill this issue in with more details, please do!

**Comment by VitalyFedyunin** [comment]
Now we sync on event or thread whenever we are sending CUDA tensors via IPC.
