### ISSUE TITLE
RNN bidirectional parameter non-bool input behavior not coherent to v0.4

### ISSUE THREAD

**Issue by zijwang** [pytorch/pytorch#16933]
## 🐛 Bug

When the input of the bidirectional parameter is _non-bool_, the behavior in v1.0 is not coherent to that in v0.4. Specifically, if you pass `bidirectional=True`, everything is fine. However, if you pass `bidirectional=1`, there will be an error asserting a type mismatch. This leads to a huge pain when switching code from v0.4.x to v1.0.x because the error message does not point the conversion issue. An update could be either add type conversion like line 113 in `rnn.py` in v1.0.1, or add an explicit warning on the type of this parameter before the error message.

## To Reproduce

```
import torch
import torch.nn as nn
lstm = nn.LSTM(3, 3, bidirectional=1)
out = lstm(torch.randn(1, 1, 3))
```

## Expected behavior

Error in v1.0.x, everything is fine in v0.4.x

## Additional context

Could make a pull request on this.

**Comment by zijwang** [comment]
Any updates on this?

**Comment by ngimel** [comment]
Closing due to age
