### ISSUE TITLE
cannot import name '_update_worker_pids' from 'torch._C' 

### ISSUE THREAD

**Issue by Wenhanz** [pytorch/pytorch#16930]
## ❓ cannot import name '_update_worker_pids' from 'torch._C' 
 
I used the command`conda install pytorch torchvision -c pytorch` from the official guide to download Pytorch. While importing torchvision, it shows `cannot import name '_update_worker_pids' from 'torch._C'` 
Here is my code:
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
from torchvision.transforms import transforms
from torch.utils.data import DataLoader
```
Here is the full-log.
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-54-cdaf7ee18e88> in <module>
      4 import torch.optim as optim
      5 
----> 6 import torchvision
      7 from torchvision.transforms import transforms
      8 from torch.utils.data import DataLoader

~/anaconda3/lib/python3.7/site-packages/torchvision/__init__.py in <module>
      1 from torchvision import models
----> 2 from torchvision import datasets
      3 from torchvision import transforms
      4 from torchvision import utils
      5 

~/anaconda3/lib/python3.7/site-packages/torchvision/datasets/__init__.py in <module>
----> 1 from .lsun import LSUN, LSUNClass
      2 from .folder import ImageFolder, DatasetFolder
      3 from .coco import CocoCaptions, CocoDetection
      4 from .cifar import CIFAR10, CIFAR100
      5 from .stl10 import STL10

~/anaconda3/lib/python3.7/site-packages/torchvision/datasets/lsun.py in <module>
----> 1 import torch.utils.data as data
      2 from PIL import Image
      3 import os
      4 import os.path
      5 import six

~/anaconda3/lib/python3.7/site-packages/torch/utils/data/__init__.py in <module>
      3 from .distributed import DistributedSampler
      4 from .dataset import Dataset, TensorDataset, ConcatDataset, Subset, random_split
----> 5 from .dataloader import DataLoader

~/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py in <module>
      2 import torch
      3 import torch.multiprocessing as multiprocessing
----> 4 from torch._C import _set_worker_signal_handlers, _update_worker_pids, \
      5     _remove_worker_pids, _error_if_any_worker_fails
      6 from . import SequentialSampler, RandomSampler, BatchSampler

ImportError: cannot import name '_update_worker_pids' from 'torch._C' (/Users/a/anaconda3/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so)


```
Thanks for any usefel help! I do not know how to deal with it since there is no similar issues online.

**Comment by SsnL** [comment]
Did you have a previous installation of pytorch?

**Comment by Wenhanz** [comment]
@SsnL Yes! I built from the source previously for CUDA support by the following code:
```
export CMAKE_PREFIX_PATH=[anaconda root directory]
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install
```
However, I think it failed since I couldn't import torchvision although I can import torch.
So I used the command for conda again as I have mentioned.

**Comment by SsnL** [comment]
You should remove your previous install first. Try 
```sh
conda remove pytorch torchvision -y
pip uninstall torch -y
pip uninstall torch -y  # yes twice
conda install pytorch torchvision -c pytorch
```

**Comment by SsnL** [comment]
If you want to retain CUDA support on mac, then do this instead:
```sh
conda remove pytorch torchvision -y
git clone --recursive https://github.com/pytorch/vision
cd vision 
python setup.py install
```

**Comment by Wenhanz** [comment]
@SsnL It works! 
Although while using `pip uninstall torch -y`, it shows`Skipping torch as it is not installed.`.
Anyway, thanks!

**Comment by NhanTran96** [comment]
I' having this issue. My setup is below:
+ Ubuntu 18.04
+ CUDA 10.0
+ PyTorch 1.1 build from source

I can import torch and torchvison but when I do:

`from torch._C import _update_worker_pids`

the error came out:

> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name '_update_worker_pids'

Can you help me?

**Comment by ZZprogrammer** [comment]
Hi! I got this problem too. I tried to remove my envs and  reinstall pytorch. But it didn't work....
Thanks for any advice!

**Comment by NhanTran96** [comment]
> Hi! I got this problem too. I tried to remove my envs and reinstall pytorch. But it didn't work....
> Thanks for any advice!

Please refer to my answer [here](https://github.com/pytorch/pytorch/issues/18484).

**Comment by nan-rock** [comment]
I m getting the same error while running on windows platform, please anyone help me.

**Comment by HymavathiG2712** [comment]
> pip uninstall torch -y
> pip uninstall torch -y  # yes twice
 pip install torch
 
 Worked Thank you!!

**Comment by Gson-glitch** [comment]
Disabling `Variables and Files` persistence and setting `Always use latest environment` solved the issue for me in Kaggle
