### ISSUE TITLE
 larger memory consumption and slower running when installing from source

### ISSUE THREAD

**Issue by githubfragments** [pytorch/pytorch#1693]
I install pytorch from source according to the tutorial, but larger gpu memory consumption and slower running than installing from binaries. 
Details:
From source: can run 9 batches, 35 seconds every 20 iterations of training
From binaries: can run 12 batches, 22 seconds every 20 iterations of training
Why the speed and memory consumption has such a big difference?
ps:
Environment: 
ubuntu 14.04, TITAN X, cuda 8.0, cudnn v6

**Comment by apaszke** [comment]
It's hard to say why do you see the slowdown especially that I don't have any information about your script and mode. For example do you use CUDA or just CPU? What kinds of ops do you have? Are you sure you compiled with cuDNN support?

**Comment by githubfragments** [comment]
The same network is used for the two kinds of installed pytorch. And the performing environment is the same, too. The only difference is the installing method.
CUDA is and ordinary convolution operations are used. Cuda mode is certainly adopted. I am sure the cuda8.0 and cudnnv6 is successfully installed.

I follow the official instructions:
    export CMAKE_PREFIX_PATH=[anaconda root directory]
    conda install numpy pyyaml mkl setuptools cmake gcc cffi
    conda install -c soumith magma-cuda80 
    python setup.py install

Could you tell me how to make sure if cuDNN and MKL are complied with? @apaszke

**Comment by albanD** [comment]
Use the forum for further questions: https://discuss.pytorch.org/
