### ISSUE TITLE
Full-range random_() generation broken for cuda.IntTensor, cuda.LongTensor and LongTensor.

### ISSUE THREAD

**Issue by obilaniu** [pytorch/pytorch#16944]
## 🐛 Bug

When generating random integers over the full range of `IntTensor` and `LongTensor` (-2^31 to 2^31-1, and -2^63 to 2^63-1), only `IntTensor` on CPU works as expected; The other three combinations either crash or do not produce actual random numbers.

This seems to be at least partly due to integer overflow, as `max-min+1` of an integer datatype cannot by definition be contained within the same datatype.

## To Reproduce

```
# NOT WORKING: CUDA, LongTensor
>>> torch.cuda.LongTensor(10).random_(-2**63, 2**63)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Overflow when unpacking long

# NOT WORKING: CUDA, IntTensor. All random numbers identical.
>>> torch.cuda.IntTensor(10).random_(-2**31, 2**31)
tensor([2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647,
        2147483647, 2147483647, 2147483647, 2147483647], device='cuda:0',
       dtype=torch.int32)

# NOT WORKING: CPU, LongTensor
>>> torch.LongTensor(10).random_(-2**63, 2**63)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Overflow when unpacking long

# WORKING: CPU, IntTensor
>>> torch.IntTensor(10).random_(-2**31, 2**31)
tensor([ -388064048,  -707636165,   558090412, -1659029973,  2046043448,
         1383561155,  -896567077,  1357117392,   297908810,   601099022],
       dtype=torch.int32)
```

## Expected behavior

Random numbers over the full range of the datatype.

## Environment

PyTorch version: 1.1.0a0+c865d46
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: openSUSE Leap 15.0
GCC version: (SUSE Linux) 7.3.1 20180323 [gcc-7-branch revision 258812]
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 765M
Nvidia driver version: 418.30
cuDNN version: 7.4.1

Versions of relevant libraries:
[pip3] numpy (1.14.0)
[pip3] numpydoc (0.7.0)
[pip3] torch (1.1.0a0+c865d46)
[pip3] torchvision (0.2.0)
[conda] mkl                       2018.0.1             h19d6760_4  
[conda] mkl-service               1.1.2            py36h17a0993_4

**Comment by ngimel** [comment]
cc @syed-ahmed to make sure your refactor covers these cases.

**Comment by SsnL** [comment]
just adding this to the discussion: the error is thrown in `random_` not in printing.

**Comment by ezyang** [comment]
Yes, we should fix this. One hacky way is to special case 2**63 and translate it into None (and change the internal type to `optional<int64_t>`, so that we have enough bits to get the very end of the bound.

**Comment by syed-ahmed** [comment]
Regarding the case,
```
# NOT WORKING: CUDA, IntTensor. All random numbers identical.
>>> torch.cuda.IntTensor(10).random_(-2**31, 2**31)
tensor([2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647,
        2147483647, 2147483647, 2147483647, 2147483647], device='cuda:0',
       dtype=torch.int32)
```
when we overflow, the modulo divisor becomes 0. And it turns out the modulo by zero in CUDA is returning 0xFFFFFFFF or -1. Which gives the value -1-2**31 = 2147483647. Following is a small repro. I'm still trying to figure out why that is the case. This seems to be relevant: https://stackoverflow.com/a/12965050

#### Repro:
```
#include <cuda.h>
#include <cuda_runtime.h>
#include <stdio.h>


__device__ void func(uint32_t* out, uint64_t range, int64_t base) {
  for(uint32_t rand=0; rand < 10; rand++) {
    range++;
    *out = static_cast<uint32_t>(rand % static_cast<uint32_t>(range) + static_cast<int32_t>(base));
    printf("out hex=%X | dec=%u, rand is %u, range is %ld, base is %ld\n", *out, *out, rand, range, base);
    if(rand == 9){
      printf("rand % range when range overflow is %X\n", rand % static_cast<uint32_t>(range));
    }
  }
}

__global__ void myKernel(uint32_t* out, uint64_t range, int64_t base) {
  func(out, range, base);
}

int main() {
  uint32_t* out = nullptr;
  cudaMalloc(&out,sizeof(uint32_t));
  uint64_t range = 0xFFFFFFFF-9;
  int64_t base = -2147483648;
  myKernel<<<1,1>>>(out, range, base);
  cudaDeviceSynchronize();
  cudaError_t ret = cudaGetLastError();
  if(ret!= cudaSuccess) {
    printf("Failed: %s\n", cudaGetErrorString(ret));
  } else {
    printf("OK\n");
  }
}
```
#### Output:
```
nvcc --std=c++11 -O0 test.cu -o test -run
out hex=80000000 | dec=2147483648, rand is 0, range is 4294967287, base is -2147483648
out hex=80000001 | dec=2147483649, rand is 1, range is 4294967288, base is -2147483648
out hex=80000002 | dec=2147483650, rand is 2, range is 4294967289, base is -2147483648
out hex=80000003 | dec=2147483651, rand is 3, range is 4294967290, base is -2147483648
out hex=80000004 | dec=2147483652, rand is 4, range is 4294967291, base is -2147483648
out hex=80000005 | dec=2147483653, rand is 5, range is 4294967292, base is -2147483648
out hex=80000006 | dec=2147483654, rand is 6, range is 4294967293, base is -2147483648
out hex=80000007 | dec=2147483655, rand is 7, range is 4294967294, base is -2147483648
out hex=80000008 | dec=2147483656, rand is 8, range is 4294967295, base is -2147483648
out hex=7FFFFFFF | dec=2147483647, rand is 9, range is 4294967296, base is -2147483648
rand % range when range overflow is FFFFFFFF
OK
```

**Comment by gchanan** [comment]
@nairbv to check if this was fixed.

**Comment by pbelevich** [comment]
Fixed in https://github.com/pytorch/pytorch/commit/095de1e872671c4da2cc0965976058cf752c3be0
[TEST_F(RNGTest, Random64bits)](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/test/cpu_rng_test.cpp#L93) {demonstrates how to generate uint64_t max value, (2^64 - 1)

**Comment by pbelevich** [comment]
```
In [1]: import torch

In [2]: "{0:b}".format(torch.empty(1, dtype=torch.int64, device='cpu').random_(torch.iinfo(torch.int64).max, None)[0])
Out[2]: '111111111111111111111111111111111111111111111111111111111111111'

In [3]: "{0:b}".format(torch.empty(1, dtype=torch.int64, device='cuda').random_(torch.iinfo(torch.int64).max, None)[0])
Out[3]: '111111111111111111111111111111111111111111111111111111111111111'
``````
In [1]: import torch

In [2]: "{0:b}".format(torch.empty(1, dtype=torch.int64, device='cpu').random_(torch.iinfo(torch.int64).max, None)[0])
Out[2]: '111111111111111111111111111111111111111111111111111111111111111'

In [3]: "{0:b}".format(torch.empty(1, dtype=torch.int64, device='cuda').random_(torch.iinfo(torch.int64).max, None)[0])
Out[3]: '111111111111111111111111111111111111111111111111111111111111111'
```
