### ISSUE TITLE
Use of 'self' in legacy (non-static) Python autograd Function leads to function which works on one GPU but not with DataParallel

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#16947]
I recently helped a user debug a problem which boiled down to a bug in the following program:

```
import torch


class NaughtyFun(torch.autograd.Function):
    def forward(self, x):
        self._grad = x.clone()
        return x

    def backward(self, g):
        return self._grad


class MyModule(torch.nn.Module):
    def __init__(self):
        self.fun = NaughtyFun()
        super(MyModule, self).__init__()

    def forward(self, x):
        return self.fun(x)


net = torch.nn.DataParallel(MyModule(), device_ids=[0, 1]).cuda()
output = net(torch.zeros((4, 4), requires_grad=True).cuda())
output.sum().backward()
```

This fails with:

```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    output.sum().backward()
  File "/data/users/ezyang/pytorch-tmp/torch/tensor.py", line 106, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/users/ezyang/pytorch-tmp/torch/autograd/__init__.py", line 93, in
backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function GatherBackward returned an invalid gradient at index 0 -
expected device 1 but got 0
```

Can you figure out what the problem is? The use of legacy autograd function looks suspicious; but the real problem is `self._grad = x.clone()`; because the autograd function is created once in the module its instance is shared between the two DataParallel clones of the module, and so the gradient saved in one is clobbered in the other.

Easiest way to fix the problem is to convert to new style static methods. I think it's a good time for us to consider removing the legacy autograd function form entirely.

**Comment by soumith** [comment]
I'm adding this to the 1.1 milestone. We're about 3 major releases of deprecation on this feature, so it should be okay.

**Comment by gchanan** [comment]
moving milestone to 1.2.

**Comment by gchanan** [comment]
assigning @yf225 to add a warning for 1.2.

**Comment by yf225** [comment]
Warning for legacy autograd function is added in https://github.com/pytorch/pytorch/pull/22922.

**Comment by ezyang** [comment]
I think that's sufficient to close this issue
