### ISSUE TITLE
Building test_cpp_extensions fails for macOS + CUDA

### ISSUE THREAD

**Issue by hameerabbasi** [pytorch/pytorch#16955]
## 🐛 Bug

Tests fail on macOS 10.13 when compiling with CUDA. The `test_cpp_extensions` tests are unable to find `libcudart` due to looking in an incorrect path (possibly coded for Linux).

## To Reproduce

1. Compile for macOS 10.13 with CUDA as detailed in `CONTRIBUTING`.
    - I exported `CUDNN_LIBRARY` and `CUDNN_INCLUDE_DIR` as well.
1. Run `python test/run_test.py`.

I get the following error:

```
clang++ -bundle -undefined dynamic_lookup -L/Users/hameerabbasi/anaconda3/envs/pytorch/lib -arch x86_64 -L/Users/hameerabbasi/anaconda3/envs/pytorch/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/cuda_extension.o build/temp.macosx-10.7-x86_64-3.7/cuda_extension_kernel.o build/temp.macosx-10.7-x86_64-3.7/cuda_extension_kernel2.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.macosx-10.7-x86_64-3.7/torch_test_cpp_extension/cuda.cpython-37m-darwin.so
ld: warning: directory not found for option '-L/usr/local/cuda/lib64'
ld: library not found for -lcudart
```

Whereas  `cudart` definitely exists:
```
$ echo $CUDA_HOME
/usr/local/cuda
$ ls $CUDA_HOME/lib | grep libcudart
libcudart.10.0.dylib
libcudart.dylib
libcudart_static.a
```

## Expected behavior

Tests should succeed.

## Environment

```
$ python collect_env.py
Collecting environment information...
PyTorch version: 1.1.0a0+4335aac
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] torch==1.1.0a0+4335aac
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] mkl_fft                   1.0.10           py37h5e564d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0  
[conda] torch                     1.1.0a0+4335aac           dev_0    <develop>

$ clang -v
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
Found CUDA installation: /usr/local/cuda, version unknown
```

 - PyTorch Version (e.g., 1.0): `1.1.0a0+4335aac`
 - OS (e.g., Linux): macOS 10.13.6 (17G5019)
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py develop`
 - Python version: `3.7.2`
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: GTX 1060 Max-Q

**Comment by ezyang** [comment]
This seems like it should be easy enough to fix.

**Comment by ezyang** [comment]
cc @kostmo

**Comment by xmnlab** [comment]
not sure if it can be helpful, but you maybe can try to install cudatoolkit-dev: 

`conda install -c conda-forge cudatoolkit-dev`

it is just a `helper` it has a post-script that will download locally cudatoolkit from nvidia and install it on conda environment

**Comment by xmnlab** [comment]
@hameerabbasi I have the same problem here (`cannot find -lcudart_static`) on build time, not sure but it seems it was after install ccache.

**Comment by rgommers** [comment]
You both seemed to be saying it's `ccache` related and disappeared after a full rebuild.
https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#use-ccache says "Alternatively, `ccache` provided by newer Linux distributions (e.g. Debian/sid) also works, but the `nvcc` symlink to `ccache` as described above is still required." Did you perhaps miss that symlink?

**Comment by hameerabbasi** [comment]
I never installed CCache on my box.

**Comment by ezyang** [comment]
I was looking at this bug again and I realized there is a more fundamental misunderstanding here. You're building a test with CUDA on a Mac... do you actually have an NVIDIA GPU inside your Mac? If you don't, this whole exercise is pointless and even if you did get it to work (by the way, the bug is valid, in the sense that it should work, nothing wrong with cross-compiling on a Mac with no GPUs) you would have no way of running the test. For this reason, "fixing" this is pretty low priority.

**Comment by hameerabbasi** [comment]
> GPU models and configuration: GTX 1060 Max-Q

;)

**Comment by hameerabbasi** [comment]
I just tested this on Linux, and yes, `ccache` does seem to cause it.

**Comment by myproject24** [comment]
Hi, @hameerabbasi @ezyang @xmnlab @rgommers @ericnakagawa  what is the Mac machine requirements to install caffe2?

I have Mac mini with 500GB storage, 4GB RAM, and Intel Core i5 processor. is it possible to install caffe2 on my Mac mini?

OS: MacOS Mojave 10.14.2
Processor: Intel Core i5 2.5 GHz
Graphics: Intel HD Graphics 4000 1536 MB
RAM: 4GB DDR3
Storage: 500GB SATA

**Comment by rgommers** [comment]
@myproject24 this sounds like a regular install question. See https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=prebuilt.  With only 4 GB of RAM and an i5 processor, I would not recommend trying to build from source.

**Comment by fmassa** [comment]
Bumping this issue, as people are having problems compiling the cpp extensions in TorchVision on OSX with CUDA 10.1, see https://github.com/pytorch/vision/issues/977

We should probably replace https://github.com/pytorch/pytorch/blob/3a8d7463bd024dcbd00d04a323cdb10dfe867f18/torch/utils/cpp_extension.py#L550 with a more robust alternative

**Comment by lemairecarl** [comment]
I'm also having problems compiling with libtorch on a Linux installation where CUDA is not in `/usr/local/cuda`.
Removing the references to that folder in `share/cmake/Caffe2/Caffe2Targets.cmake` works. I use this command:
```
sed -i -e 's/\/usr\/local\/cuda\/lib64\/libculibos.a;dl;\/usr\/local\/cuda\/lib64\/libculibos.a;//g' share/cmake/Caffe2/Caffe2Targets.cmake
```
Also seems related to https://github.com/pytorch/pytorch/pull/22818... not sure.
