### ISSUE TITLE
torch.distributions.Normal repr invalid scale value

### ISSUE THREAD

**Issue by mfuntowicz** [pytorch/pytorch#16952]
According to the following, it seems that __repr__ fails to output the right scale parameter on Normal distribution : 

```
>>> torch.distributions.Normal(torch.tensor([1.0]), torch.tensor([0.1]))
Normal(loc: torch.Size([1]), scale: torch.Size([1]))

>>> torch.distributions.Normal(torch.tensor([1.0]), torch.tensor([0.1])).scale
tensor([0.1000])
```

Edit : Well, in fact it outputs the Size object of the underlying tensor not sure this is the desired behaviour ?

**Comment by Kaixhin** [comment]
While getting the actual values might be more useful, it would also be quite unwieldy in the general case where you have a lot of values, e.g., large batch, multivariate Gaussian?

**Comment by vishwakftw** [comment]
It was discussed about in #10373, that the values were to be displayed if they were scalars, and the size of the tensor if otherwise. The logic is displayed below:

https://github.com/pytorch/pytorch/blob/4335aac6e62c16e13770fe65d1bd365948a849fe/torch/distributions/distribution.py#L262-L267

**Comment by mfuntowicz** [comment]
Thanks for pointing you in the code. Would it make sens to rely on `self.__dict__[p].numel() == 1 `to check if p is a scalar or not ?

**Comment by vishwakftw** [comment]
Yep, this sounds just about right. Do you mind sending in a PR?

**Comment by vishwakftw** [comment]
Hi @mfuntowicz, could you send in a PR implementing this small change?

**Comment by mfuntowicz** [comment]
Sorry for the delay I will do it by today. 

Morgan

**Comment by vishwakftw** [comment]
No worries, thanks for the reply :)

**Comment by mfuntowicz** [comment]
PR opened : https://github.com/pytorch/pytorch/pull/17503

**Comment by vishwakftw** [comment]
Closing issue as the fix has landed.

**Comment by yf225** [comment]
@mfuntowicz Is this issue ready to close?
