### ISSUE TITLE
[JIT] Cannot index into tuple with non constant integer

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#16962]
## 🐛 Bug

[JIT] Cannot index into tuple with non constant integer. Constant array turns it the array into tuple

## To Reproduce
```
 import torch
 
 
 class Normalize(torch.jit.ScriptModule):
     __constants__ = ['mean', 'std']
 
     def __init__(self):
         super(Normalize, self).__init__()
         self.mean = [1, 1, 1]
         self.std = [1, 1, 1]
 
     @torch.jit.script_method
     def forward(self, image):
         # type: (torch.Tensor) -> torch.Tensor
         for i in range(3):
             image[:, i] = image[:, i].sub_(self.mean[i]).div_(self.   std[i])
 
         return image
 
 
 Normalize()

```

```
tuple indices must be integer constants:
@torch.jit.script_method
def forward(self, image):
    # type: (torch.Tensor) -> torch.Tensor
    for i in range(3):
        image[:, i] = image[:, i].sub_(self.mean[i]).div_(self.std[i])
                                       ~~~~~~~~~~~ <--- HERE

    return image
```

**Comment by driazati** [comment]
You can workaround it by hijacking our `Tuple` -> `List` argument coercion by passing `self.mean` through something like:
```python
@torch.jit.script
def make_list(x):
    # type: (Tuple[int, int, int]) -> List[int]
    return x
```

We should support `list(a_tuple)` though, so leaving this open to track that

**Comment by sidazhang** [comment]
@driazati hahah this is actually kind of brilliant. Thank you! :P

**Comment by eellison** [comment]
This would only work with a Tuple of size 3; to hijack Tuple -> List coercion for any size make the input type of make_list a List[int]. 

```python
@torch.jit.script
def make_list(x):
    # type: (List[int]) -> List[int]
    return x
```

But as David said, we should support `list(a_tuple)` / other better solution...

**Comment by sidazhang** [comment]
> This would only work with a Tuple of size 3; to hijack Tuple -> List coercion for any size make the input type of make_list a List[int].
> 
> ```python
> @torch.jit.script
> def make_list(x):
>     # type: (List[int]) -> List[int]
>     return x
> ```
> 
> But as David said, we should support `list(a_tuple)` / other better solution...

lol Even more brilliant.

**Comment by eellison** [comment]
Closed with https://github.com/pytorch/pytorch/pull/20081
