### ISSUE TITLE
Compilation with CUDA fails on ubuntu 17.04

### ISSUE THREAD

**Issue by garibarba** [pytorch/pytorch#1696]
My system:
Ubuntu 17.04
python 3.5.2 from anaconda
Nvidia driver 381, cuda 8.0.44 from nvidia-cuda-toolkit and cudnn v6 installed with the deb package from nvidia for ubuntu 16.04.

If I install the 0.1.12 release it works perfectly on CPU and GPU.
Compilation for CPU works perfectly, but I get the following output when compiling for GPU:

> running install
> running build_deps
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /home/guille/anaconda3/bin/cc
> -- Check for working C compiler: /home/guille/anaconda3/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Checking if C linker supports --verbose
> -- Checking if C linker supports --verbose - yes
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /home/guille/anaconda3/bin/c++
> -- Check for working CXX compiler: /home/guille/anaconda3/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Checking if CXX linker supports --verbose
> -- Checking if CXX linker supports --verbose - yes
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Try OpenMP C flag = [-fopenmp]
> -- Performing Test OpenMP_FLAG_DETECTED
> -- Performing Test OpenMP_FLAG_DETECTED - Success
> -- Try OpenMP CXX flag = [-fopenmp]
> -- Performing Test OpenMP_FLAG_DETECTED
> -- Performing Test OpenMP_FLAG_DETECTED - Success
> -- Found OpenMP: -fopenmp  
> -- Compiling with OpenMP support
> -- Could not find hardware support for NEON on this machine.
> -- No OMAP3 processor on this machine.
> -- No OMAP4 processor on this machine.
> -- Looking for cpuid.h
> -- Looking for cpuid.h - found
> -- Performing Test HAVE_GCC_GET_CPUID
> -- Performing Test HAVE_GCC_GET_CPUID - Success
> -- Performing Test NO_GCC_EBX_FPIC_BUG
> -- Performing Test NO_GCC_EBX_FPIC_BUG - Success
> -- Performing Test C_HAS_SSE1_1
> -- Performing Test C_HAS_SSE1_1 - Success
> -- Performing Test C_HAS_SSE2_1
> -- Performing Test C_HAS_SSE2_1 - Success
> -- Performing Test C_HAS_SSE3_1
> -- Performing Test C_HAS_SSE3_1 - Failed
> -- Performing Test C_HAS_SSE3_2
> -- Performing Test C_HAS_SSE3_2 - Success
> -- Performing Test C_HAS_SSE4_1_1
> -- Performing Test C_HAS_SSE4_1_1 - Failed
> -- Performing Test C_HAS_SSE4_1_2
> -- Performing Test C_HAS_SSE4_1_2 - Success
> -- Performing Test C_HAS_SSE4_2_1
> -- Performing Test C_HAS_SSE4_2_1 - Failed
> -- Performing Test C_HAS_SSE4_2_2
> -- Performing Test C_HAS_SSE4_2_2 - Success
> -- Performing Test C_HAS_AVX_1
> -- Performing Test C_HAS_AVX_1 - Failed
> -- Performing Test C_HAS_AVX_2
> -- Performing Test C_HAS_AVX_2 - Success
> -- Performing Test C_HAS_AVX2_1
> -- Performing Test C_HAS_AVX2_1 - Failed
> -- Performing Test C_HAS_AVX2_2
> -- Performing Test C_HAS_AVX2_2 - Success
> -- Performing Test CXX_HAS_SSE1_1
> -- Performing Test CXX_HAS_SSE1_1 - Success
> -- Performing Test CXX_HAS_SSE2_1
> -- Performing Test CXX_HAS_SSE2_1 - Success
> -- Performing Test CXX_HAS_SSE3_1
> -- Performing Test CXX_HAS_SSE3_1 - Failed
> -- Performing Test CXX_HAS_SSE3_2
> -- Performing Test CXX_HAS_SSE3_2 - Success
> -- Performing Test CXX_HAS_SSE4_1_1
> -- Performing Test CXX_HAS_SSE4_1_1 - Failed
> -- Performing Test CXX_HAS_SSE4_1_2
> -- Performing Test CXX_HAS_SSE4_1_2 - Success
> -- Performing Test CXX_HAS_SSE4_2_1
> -- Performing Test CXX_HAS_SSE4_2_1 - Failed
> -- Performing Test CXX_HAS_SSE4_2_2
> -- Performing Test CXX_HAS_SSE4_2_2 - Success
> -- Performing Test CXX_HAS_AVX_1
> -- Performing Test CXX_HAS_AVX_1 - Failed
> -- Performing Test CXX_HAS_AVX_2
> -- Performing Test CXX_HAS_AVX_2 - Success
> -- Performing Test CXX_HAS_AVX2_1
> -- Performing Test CXX_HAS_AVX2_1 - Failed
> -- Performing Test CXX_HAS_AVX2_2
> -- Performing Test CXX_HAS_AVX2_2 - Success
> -- SSE2 Found
> -- SSE3 Found
> -- AVX Found
> -- AVX2 Found
> -- Performing Test HAS_C11_ATOMICS
> -- Performing Test HAS_C11_ATOMICS - Failed
> -- Performing Test HAS_MSC_ATOMICS
> -- Performing Test HAS_MSC_ATOMICS - Failed
> -- Performing Test HAS_GCC_ATOMICS
> -- Performing Test HAS_GCC_ATOMICS - Success
> -- TH_SO_VERSION: 1
> -- Atomics: using GCC intrinsics
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of void*
> -- Check size of void* - done
> -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
> --   Library mkl_gf_lp64: not found
> -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
> --   Library mkl_gf_lp64: not found
> -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
> --   Library mkl_gf: not found
> -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
> --   Library mkl_gf: not found
> -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
> --   Library mkl_intel_lp64: /home/guille/anaconda3/lib/libmkl_intel_lp64.so
> --   Library mkl_gnu_thread: not found
> -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
> --   Library mkl_intel_lp64: /home/guille/anaconda3/lib/libmkl_intel_lp64.so
> --   Library mkl_intel_thread: /home/guille/anaconda3/lib/libmkl_intel_thread.so
> --   Library mkl_core: /home/guille/anaconda3/lib/libmkl_core.so
> --   Library iomp5: /home/guille/anaconda3/lib/libiomp5.so
> --   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
> --   Library m: /usr/lib/x86_64-linux-gnu/libm.so
> -- Looking for cblas_sgemm
> -- Looking for cblas_sgemm - found
> -- MKL library found
> -- Performing Test BLAS_F2C_DOUBLE_WORKS
> -- Performing Test BLAS_F2C_DOUBLE_WORKS - Failed
> -- Performing Test BLAS_F2C_FLOAT_WORKS
> -- Performing Test BLAS_F2C_FLOAT_WORKS - Success
> -- Found a library with BLAS API (mkl).
> -- Found a library with LAPACK API. (mkl)
> -- Looking for clock_gettime in rt
> -- Looking for clock_gettime in rt - found
> -- Looking for mmap
> -- Looking for mmap - found
> -- Looking for shm_open
> -- Looking for shm_open - found
> -- Looking for shm_unlink
> -- Looking for shm_unlink - found
> -- Looking for malloc_usable_size
> -- Looking for malloc_usable_size - found
> -- Performing Test C_HAS_THREAD
> -- Performing Test C_HAS_THREAD - Success
> -- Configuring done
> -- Generating done
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     CUDA_NVCC_FLAGS
>     NO_CUDA
>     THCS_LIBRARIES
>     THCUNN_SO_VERSION
>     THC_LIBRARIES
>     THC_SO_VERSION
>     THD_SO_VERSION
>     THNN_SO_VERSION
>     THPP_LIBRARIES
>     THS_LIBRARIES
>     TH_INCLUDE_PATH
>     TH_LIB_PATH
>     Torch_FOUND
> 
> 
> -- Build files have been written to: /home/guille/git/pytorch/torch/lib/build/TH
> Scanning dependencies of target TH
> [  5%] Building C object CMakeFiles/TH.dir/THGeneral.c.o
> [ 10%] Building C object CMakeFiles/TH.dir/THHalf.c.o
> [ 15%] Building C object CMakeFiles/TH.dir/THAllocator.c.o
> [ 20%] Building C object CMakeFiles/TH.dir/THStorage.c.o
> [ 25%] Building C object CMakeFiles/TH.dir/THTensor.c.o
> [ 35%] Building C object CMakeFiles/TH.dir/THBlas.c.o
> [ 35%] Building C object CMakeFiles/TH.dir/THLapack.c.o
> [ 40%] Building C object CMakeFiles/TH.dir/THLogAdd.c.o
> [ 45%] Building C object CMakeFiles/TH.dir/THRandom.c.o
> [ 50%] Building C object CMakeFiles/TH.dir/THFile.c.o
> [ 55%] Building C object CMakeFiles/TH.dir/THDiskFile.c.o
> [ 60%] Building C object CMakeFiles/TH.dir/THMemoryFile.c.o
> [ 65%] Building C object CMakeFiles/TH.dir/THAtomic.c.o
> [ 70%] Building C object CMakeFiles/TH.dir/THVector.c.o
> [ 75%] Building C object CMakeFiles/TH.dir/generic/simd/convolve5x5_sse.c.o
> [ 80%] Building C object CMakeFiles/TH.dir/generic/simd/convolve.c.o
> [ 85%] Building C object CMakeFiles/TH.dir/vector/AVX.c.o
> [ 90%] Building C object CMakeFiles/TH.dir/generic/simd/convolve5x5_avx.c.o
> [ 95%] Building C object CMakeFiles/TH.dir/vector/AVX2.c.o
> [100%] Linking C shared library libTH.so
> [100%] Built target TH
> Install the project...
> -- Install configuration: "Release"
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/lib/libTH.so.1
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/lib/libTH.so
> -- Set runtime path of "/home/guille/git/pytorch/torch/lib/tmp_install/lib/libTH.so.1" to ""
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/TH.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THAllocator.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THMath.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THBlas.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THDiskFile.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THFile.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THFilePrivate.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGeneral.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateAllTypes.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateDoubleType.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateFloatType.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateHalfType.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateLongType.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateIntType.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateShortType.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateCharType.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateByteType.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateFloatTypes.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THGenerateIntTypes.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THLapack.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THLogAdd.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THMemoryFile.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THRandom.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THStorage.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THTensor.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THTensorApply.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THTensorDimApply.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THTensorMacros.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THVector.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THAtomic.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/THHalf.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/vector/AVX.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/vector/AVX2.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THBlas.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THBlas.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THLapack.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THLapack.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THStorage.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THStorage.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THStorageCopy.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THStorageCopy.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensor.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensor.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensorConv.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensorConv.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensorCopy.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensorCopy.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensorLapack.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensorLapack.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensorMath.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensorMath.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensorRandom.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THTensorRandom.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THVectorDispatch.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/TH/generic/THVector.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/share/cmake/TH/THConfig.cmake
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /home/guille/anaconda3/bin/cc
> -- Check for working C compiler: /home/guille/anaconda3/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Checking if C linker supports --verbose
> -- Checking if C linker supports --verbose - yes
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /home/guille/anaconda3/bin/c++
> -- Check for working CXX compiler: /home/guille/anaconda3/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Checking if CXX linker supports --verbose
> -- Checking if CXX linker supports --verbose - yes
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- TH_LIBRARIES: /home/guille/git/pytorch/torch/lib/tmp_install/lib/libTH.so.1
> -- THS_SO_VERSION: 1
> -- Configuring done
> -- Generating done
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     CUDA_NVCC_FLAGS
>     NO_CUDA
>     THCS_LIBRARIES
>     THCUNN_SO_VERSION
>     THC_LIBRARIES
>     THC_SO_VERSION
>     THD_SO_VERSION
>     THNN_SO_VERSION
>     THPP_LIBRARIES
>     THS_LIBRARIES
>     TH_SO_VERSION
> 
> 
> -- Build files have been written to: /home/guille/git/pytorch/torch/lib/build/THS
> Scanning dependencies of target THS
> [ 50%] Building C object CMakeFiles/THS.dir/THSTensor.c.o
> [100%] Linking C shared library libTHS.so
> [100%] Built target THS
> Install the project...
> -- Install configuration: "Release"
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/lib/libTHS.so.1
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/lib/libTHS.so
> -- Set runtime path of "/home/guille/git/pytorch/torch/lib/tmp_install/lib/libTHS.so.1" to ""
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THS/THS.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THS/THSGenerateAllTypes.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THS/THSGenerateFloatTypes.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THS/THSGenerateIntTypes.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THS/THSTensor.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THS/generic/THSTensor.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THS/generic/THSTensor.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THS/generic/THSTensorMath.c
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THS/generic/THSTensorMath.h
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /home/guille/anaconda3/bin/cc
> -- Check for working C compiler: /home/guille/anaconda3/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Checking if C linker supports --verbose
> -- Checking if C linker supports --verbose - yes
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /home/guille/anaconda3/bin/c++
> -- Check for working CXX compiler: /home/guille/anaconda3/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Checking if CXX linker supports --verbose
> -- Checking if CXX linker supports --verbose - yes
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- TH_LIBRARIES: /home/guille/git/pytorch/torch/lib/tmp_install/lib/libTH.so.1
> -- Try OpenMP C flag = [-fopenmp]
> -- Performing Test OpenMP_FLAG_DETECTED
> -- Performing Test OpenMP_FLAG_DETECTED - Success
> -- Try OpenMP CXX flag = [-fopenmp]
> -- Performing Test OpenMP_FLAG_DETECTED
> -- Performing Test OpenMP_FLAG_DETECTED - Success
> -- Found OpenMP: -fopenmp  
> -- Compiling with OpenMP support
> CMake Warning (dev) at CMakeLists.txt:61 (LINK_DIRECTORIES):
>   This command specifies the relative path
> 
>     
> 
>   as a link directory.
> 
>   Policy CMP0015 is not set: link_directories() treats paths relative to the
>   source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- THNN_SO_VERSION: 1
> -- Configuring done
> -- Generating done
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     CUDA_NVCC_FLAGS
>     NO_CUDA
>     THCS_LIBRARIES
>     THCUNN_SO_VERSION
>     THC_LIBRARIES
>     THC_SO_VERSION
>     THD_SO_VERSION
>     THPP_LIBRARIES
>     THS_LIBRARIES
>     TH_INCLUDE_PATH
>     TH_LIB_PATH
>     TH_SO_VERSION
> 
> 
> -- Build files have been written to: /home/guille/git/pytorch/torch/lib/build/THNN
> Scanning dependencies of target THNN
> [ 50%] Building C object CMakeFiles/THNN.dir/init.c.o
> [100%] Linking C shared library libTHNN.so
> [100%] Built target THNN
> Install the project...
> -- Install configuration: "Release"
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/lib/libTHNN.so.1
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/lib/libTHNN.so
> -- Set runtime path of "/home/guille/git/pytorch/torch/lib/tmp_install/lib/libTHNN.so.1" to ""
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THNN/THNN.h
> -- Installing: /home/guille/git/pytorch/torch/lib/tmp_install/include/THNN/generic/THNN.h
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /home/guille/anaconda3/bin/cc
> -- Check for working C compiler: /home/guille/anaconda3/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Checking if C linker supports --verbose
> -- Checking if C linker supports --verbose - yes
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /home/guille/anaconda3/bin/c++
> -- Check for working CXX compiler: /home/guille/anaconda3/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Checking if CXX linker supports --verbose
> -- Checking if CXX linker supports --verbose - yes
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Removing -DNDEBUG from compile flags
> -- TH_LIBRARIES: /home/guille/git/pytorch/torch/lib/tmp_install/lib/libTH.so.1
> CMake Error at /home/guille/anaconda3/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
>   Could NOT find CUDA (missing: CUDA_CUDART_LIBRARY) (found suitable version
>   "8.0", minimum required is "5.5")
> Call Stack (most recent call first):
>   /home/guille/anaconda3/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
>   /home/guille/git/pytorch/cmake/FindCUDA/FindCUDA.cmake:1013 (find_package_handle_standard_args)
>   CMakeLists.txt:28 (FIND_PACKAGE)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/guille/git/pytorch/torch/lib/build/THC/CMakeFiles/CMakeOutput.log".
> 

I have tried configuring the environment variables PATH and LD_LIBRARY_PATH, but this does not help:
> export PATH=/home/guille/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/nvidia-381:/usr/lib/nvidia-381/bin
> export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu::/usr/lib/nvidia-381:/usr/lib32/nvidia-381:/usr/lib:/usr/lib32

It might be related to #638 but I have not been able to fix this.

**Comment by apaszke** [comment]
PATH and LD_LIBRARY_PATH have no effect on builds. You need to set `CMAKE_PREFIX_PATH` to where your CUDA is installed.

**Comment by garibarba** [comment]
Thanks so much! (I'll learn some cmake before posting any more compilation errors...).
This made it for my system configuration. #675 helped.
```
export CMAKE_PREFIX_PATH=/usr
export CUDA_HOME=/usr
export CUDA_LIB=/usr/lib/x86_64-linux-gnu
CC=gcc-5 CXX=g++-5 python setup.py install
```
