### ISSUE TITLE
cpp_extension._is_binary_build() is not reliable

### ISSUE THREAD

**Issue by ccoulombe** [pytorch/pytorch#16972]
## 🐛 Bug

cpp_extension._is_binary_build() is not reliable.

## To Reproduce

1. export `PYTORCH_BUILD_VERSION=1.0.0`
2. build Pytorch from source
3. _is_binary_build() will return `True` while it was build from source since the regex from https://github.com/pytorch/pytorch/blob/c90a33b6270cb4bdadef60cfe4de8660216ec2f9/torch/utils/cpp_extension.py#L92 will not match.

## Expected behavior
According to https://github.com/pytorch/pytorch/blob/48c5d0ae8cfa272cbed96b176c18eb2b0c800b8e/torch/utils/cpp_extension.py#L89 and https://github.com/pytorch/pytorch/blob/48c5d0ae8cfa272cbed96b176c18eb2b0c800b8e/torch/utils/cpp_extension.py#L391 `_is_binary_build()` should return `False`

## Environment

 - PyTorch Version (e.g., 1.0): >=1.0.0 
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): as mentionned above
 - Python version: all
 - CUDA/cuDNN version: 10
 - GPU models and configuration: -
 - Any other relevant information: - 

## Additional context

While building torchaudio I stumbled on `ImportError: test_venv/lib/python3.6/site-packages/_torch_sox.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs` which was caused by https://github.com/pytorch/pytorch/blob/48c5d0ae8cfa272cbed96b176c18eb2b0c800b8e/torch/utils/cpp_extension.py#L398 forcing non-C++11 symbols when torch was built from source with `-D_GLIBCXX_USE_CXX11_ABI=1`.

**Comment by ccoulombe** [comment]
This could be resolved by a flag that gets written in `version.py`.

**Comment by soumith** [comment]
but this is expected, we dont expect userland to set `PYTORCH_BUILD_VERSION` environment variable. Why did you build your original PyTorch with that flag?
I'm happy to change it to something else.

**Comment by ccoulombe** [comment]
Primarly since the version is hard coded in `version.py` (which is fine) but it does not follow the git tags/release. For example, for v1.0.1, the version is:
https://github.com/pytorch/pytorch/blob/83221655a8237ca80f9673dad06a98d34c43e546/setup.py#L215
when it is a stable release and to follow PEP 440 that says that a version number suffixed with `a` is an alpha release (pre-release). Plus I've seen a hash appended to signifies a dev version (but this is arbitrary and up to the developers) in some wheels.

In order to follow PEP and be consistent with other wheels we provide to our users I used `PYTORCH_BUILD_VERSION` to override the version, hence inadvertently creating the issue with torchaudio.

I guess there's two point to this:
1. hard code whether torch was built from source on host or downloaded as wheel(binary) (we can then rely on `_is_binary_build()`).
2. versioning must be coherent with git tags (I can open a different issue for this one if you'd like)

**Comment by soumith** [comment]
1. I've stopped relying on `_is_binary_build` for CXX ABI flags, so hopefully it shouldn't matter anymore for cpp extensions purposes.

2. 1.1.0 tag has `1.1.0` as the version, no git hash.
