### ISSUE TITLE
namespaces torch.cuda, torch.device missing from pyi

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#16996]
## 🐛 Bug

Auto-complete / type information for torch.cuda / torch.device are missing, as reported at https://github.com/pytorch/pytorch/issues/7318#issuecomment-462086074

## To Reproduce

Auto-complete `torch.cuda.<TAB>` in pycharm

**Comment by zhezh** [comment]
torch.device()  torch.tensor() are still missing, I believe they are much frequently used.

**Comment by fengyanghe** [comment]
torch.randn() and torch.FloatTensor() are still missing in PyTorch 1.0.1, related to vs code and wing ide

**Comment by t-vi** [comment]
`torch.FloatTensor` is deprecated. Unfortunately, there doesn't seem to be a good mechanism to incorporate deprecation information into type hints, currently. At least that was the case a couple of months ago when I searched for that a bit.

**Comment by Wenlong-Shi** [comment]
torch.from_numpy()、torch.ones are still missing in 1.0.1.post2，related to Pycharm。

**Comment by fmassa** [comment]
@Wenlong-Shi I'd say `torch.from_numpy` is also kind of deprecated, in favor of `torch.as_tensor`

**Comment by Wenlong-Shi** [comment]
@fmassa `torch.as_tensor` is also missing in 1.0.1.post2，related to Pycharm.

**Comment by Luvata** [comment]
torch.no_grad() is also missing in in 1.0.1.post2, related to Pycharm

**Comment by 670373064** [comment]
torch.cuda（）、torch.utils is also missing in in 1.0.1, related to Pycharm

**Comment by magnusjacobsen** [comment]
on 1.0.1, pylint claims *torch.tensor() is not callable*
![Untitled](https://user-images.githubusercontent.com/33226525/54473504-05113580-47d9-11e9-83ec-6e3ab006827f.png)

**Comment by Ajk4** [comment]
On torch 1.0.1 on Windows I don't see `torch.nn` package. When ran code works just fine

<img width="286" alt="torch_nn" src="https://user-images.githubusercontent.com/2959412/54478023-1b85b400-480e-11e9-8d9d-2ddead7a0f92.png">

**Comment by malmaud** [comment]
I'd be happy to manually add the stubs for some of these missing namespaces and submit those as a PR. Would that be acceptable, or are you looking for a more automatic codegen approach?

**Comment by t-vi** [comment]
Thank you for offering to work on these! I'm not sure whether there / what the are plans for a maintenance release, but a great first step would to fix these in master / the nightlies.
- Things related to the automatically wrapped functions would best go in the generation
  `https://github.com/pytorch/pytorch/blob/master/tools/pyi/gen_pyi.py`
- Things like imports and pure Python functions could go here: `https://github.com/pytorch/pytorch/blob/master/torch/__init__.pyi.in`

**Comment by imyhxy** [comment]
I am using `torch==1.0.1.post2` and `Pycharm professional 2019.1`. I tested and sorted out the situation mentioned by everyone in front.

#### can't find reference

* `torch.cat`
* `torch.clamp`
* `torch.exp`
* `torch.FloatTensor` **deprecated**
* `torch.from_numpy` **deprecated**
* `torch.log`
* `torch.LongTensor` **deprecated**
* `torch.max`
* `torch.min`
* `torch.ones`
* `torch.randn`
* `torch.reshape`
* `torch.sum`
* `torch.zeros`

#### not callable

* `torch.tensor`
* `torch.as_tensor`

**Comment by Dessix** [comment]
The message in 1b25fdb does not appear to have intended to close this issue.
"This would close #16996, although comments on that issue reference other missing stubs so maybe it's worth keeping open as an umbrella issue." @malmaud - should this be reopened?

**Comment by malmaud** [comment]
Maybe better to just open a new issue with the things are still missing from the stubs. `torch.cuda` and `torch.device`, which is the title of this issue, have been added.

**Comment by malmaud** [comment]
I went ahead and opened new issues for `nn` and `util.data`. The other missing methods mentioned in this issue are all fixed on master but aren't on a release yet.

**Comment by zhutmost** [comment]
I have updated to the latest version (1.1.0). However, this bug is still not fixed.

**Comment by malmaud** [comment]
What specifically do you mean by 'this bug'? Like, which methods? I did a fresh install of 1.1.0 and all the new type stubs have seemingly been installed correctly.

**Comment by lianghongzhuo** [comment]
can't find reference in 1.1.0, some examples:
```
torch.cuda.manual_seed()
torch.utils.data.dataloader.default_collate()
```

**Comment by bcrchzz** [comment]
> What specifically do you mean by 'this bug'? Like, which methods? I did a fresh install of 1.1.0 and all the new type stubs have seemingly been installed correctly.

@malmaud 

for example, `torch.arange`, `torch.zeros`, `torch.cat`
![image](https://user-images.githubusercontent.com/48672827/57504555-855e9d80-7327-11e9-8b05-49325f11d109.png)

**Comment by lianghongzhuo** [comment]
@bcrchzz `torch.arange`, `torch.zeros`, `torch.cat` works fine in 1.1.0 with the PyCharm IDE.
Did you update your pytorch?

**Comment by lianghongzhuo** [comment]
What still cannot find the reference now is `torch.data` in the 1.1.0 version.

**Comment by bcrchzz** [comment]
> @bcrchzz `torch.arange`, `torch.zeros`, `torch.cat` works fine in 1.1.0 with the PyCharm IDE.
> Did you update your pytorch?

@lianghongzhuo Both my pytorch and pycharm are in the latest version.
![image](https://user-images.githubusercontent.com/48672827/57525215-b4433680-735c-11e9-9e2a-3f12cf293dc0.png)

**Comment by bcrchzz** [comment]
Besides, I find more functions, `torch.sqrt/zeros_like/where`, which cannot be referred correctly.

**Comment by malmaud** [comment]
As @lianghongzhuo says, the type stubs for `torch.arange` etc have been successfully used in pycharm by others and me. If there still an issue for you, it must be on the PyCharm side - there's nothing more that can be done on the PyTorch side than shipping working type stubs.

**Comment by bcrchzz** [comment]
@malmaud Thank you a lot. I re-configured the python interpreter in the PyCharm Preference and reopened it. And the problem solved.
I use a remote python interpreter installed on a server. And I guess Pycharm may cache something locally, which makes it cannot refer the right version for lint.

Thanks again for your great jobs.

**Comment by DavidRuhe** [comment]
@bcrchzz  I'm also use a remote interpreter. How did you reconfigure the remote interpreter? I removed it and re-added it but still have the reference problems.

**Comment by Genius1237** [comment]
I get errors for `torch.tensor`,`torch.float`, `torch.ones`, `torch.zeros` and `torch.zeros` on 1.1.0 installed from pypi on VS Code.

**Comment by DavidRuhe** [comment]
For me torch.log, torch.stack, torch.exp, torch.randn do not work yet.

**Comment by malmaud** [comment]
I think there's no doubt that the stubs of the `torch.*` methods are being installed with 1.1.0. If your editor isn't making use of them, the issue must be with your editor and its interaction with your Python environment - there isn't anything more that can be on the PyTorch side.

**Comment by jakkes** [comment]
Using torch v1.1.0 and VSCode v1.33.1 (latest) with python 3.6.7, pretty much all torch.* methods do not show up (including all posted by the @imyhxy further up), nor is torch.tensor callable. It works fine in pycharm (apart from the callability of torch.tensor).

**Comment by Whisht** [comment]
I found that the stubs of torch.*  works well in **pycharm python console**, but still cannot find reference in the **editor**.  Even I reinstall pycharm as well as remote python interpreter. So confusing.
