### ISSUE TITLE
Batchnormalization fails with CUDA on very large batches

### ISSUE THREAD

**Issue by rainerkelz** [pytorch/pytorch#16998]
## 🐛 Bug
If we use nn.BatchNorm1d() with (very) large batchsizes and torch.cuda.FloatTensors, we get an "invalid configuration argument" error.

## To Reproduce

Steps to reproduce the behavior (paste and run):
``` python
import torch
from torch import nn


def main():
    print('torch version', torch.version.__version__)
    print('cuda version', torch.version.cuda)

    bn = nn.BatchNorm1d(1)
    bn.cuda()
    for i in range(16, 20):
        N = 2 ** i
        print('i, N', i, N)
        A = torch.cuda.FloatTensor(N, 1)
        result = bn(A)


if __name__ == '__main__':
    main()
```

On my machine, for pytorch 1.0.1.post2 this will output:
```
torch version 1.0.1.post2
cuda version 9.0.176
i, N 16 65536
i, N 17 131072
THCudaCheck FAIL file=/pytorch/aten/src/ATen/native/cuda/Normalization.cuh line=467 error=9 : invalid configuration argument
Traceback (most recent call last):
  File "minimal_test_case.py", line 19, in <module>
    main()
  File "minimal_test_case.py", line 15, in main
    result = bn(A)
  File "/media/rainer/heap/Coding/cp/venvs/pytorch-adsr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/rainer/heap/Coding/cp/venvs/pytorch-adsr/lib/python3.5/site-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/media/rainer/heap/Coding/cp/venvs/pytorch-adsr/lib/python3.5/site-packages/torch/nn/functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuda runtime error (9) : invalid configuration argument at /pytorch/aten/src/ATen/native/cuda/Normalization.cuh:467
```

Whereas for pytorch 0.4.1 this outputs:
```
torch version 0.4.1
cuda version 9.0.176
i, N 16 65536
i, N 17 131072
i, N 18 262144
i, N 19 524288
```

## Expected behavior
The same behavior as for version 0.4.1.

## Environment
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Tesla K40c
Nvidia driver version: 387.26
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip3] numpy==1.16.1
[pip3] torch==1.0.1.post2
[conda] Could not collect

**Comment by vishwakftw** [comment]
cc: @jjsjann123

**Comment by jjsjann123** [comment]
https://github.com/pytorch/pytorch/blob/f8d4a14f6dc7c709c86b8bb25ccaaa486470e4a7/aten/src/ATen/native/cuda/Normalization.cuh#L443

This limiter on the grid dimension might exceeds the maximum 65535 on y/z dimension.
Should be a one liner fix. Let me get that.
