### ISSUE TITLE
cuDNN version mismatch (again)

### ISSUE THREAD

**Issue by AAnoosheh** [pytorch/pytorch#17009]
## 🐛 Bug

The latest version of PyTorch downloaded from the official site using the command-line statement has a mismatched CuDNN once again. (Linux, via `conda install pytorch torchvision cudatoolkit=9.0 -c pytorch`)

## To Reproduce

`torch.backends.cudnn.version()`

## Expected behavior

`RuntimeError: cuDNN version mismatch: PyTorch was compiled against 7102 but linked against 7301`

## Environment

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Debian GNU/Linux 9.5 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: version 3.7.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN X (Pascal)
GPU 1: GeForce GTX 1080 Ti
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)
GPU 4: TITAN X (Pascal)
GPU 5: GeForce GTX 1080 Ti
GPU 6: TITAN X (Pascal)
GPU 7: TITAN X (Pascal)

Nvidia driver version: 390.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] numpydoc==0.8.0
[pip] torch==0.4.1
[pip] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.3                      1
[conda] mkl-service               1.1.2            py37h90e4bf4_5
[conda] mkl_fft                   1.0.6            py37h7dd41cf_0
[conda] mkl_random                1.0.1            py37h4414c95_1
[conda] pytorch                   0.4.1            py37ha74772b_0
[conda] torchvision               0.2.1                      py_2    pytorch

## Additional context

The system's own Cuda (9) is not anywhere on my own PATH or LD_LIBRARY_PATH

**Comment by SsnL** [comment]
Hi, your env info suggests that you have pytorch 0.4.1 installed, which is not the latest.

**Comment by AAnoosheh** [comment]
Sorry yes, I was using the Cuda 9.0 version thinking pytorch was still using system Cuda/Cudnn like it did a couple years ago.
Didn't realize 1.0 was only available if you select Cuda 10.0

The website is actually super confusing and doesn't specify anything regarding what the Cuda version actually means anymore.
Anyways, the "latest" 0.4.1 package is still wrongly compiled, no?

**Comment by soumith** [comment]
@AAnoosheh when you do `conda install pytorch torchvision cudatoolkit=9.0 -c pytorch` PyTorch v1.0.1 should be installed (that is compiled with CUDA9), and v0.4.1 should be installed.

The console should look like this:

```
soumith@devfair004:~/local/builder_fresh$ conda install pytorch torchvision cudatoolkit=9.0 -c pytorch
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /private/home/soumith/anaconda3

  added / updated specs:
    - cudatoolkit=9.0
    - pytorch
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.1.23  |                0         126 KB
    conda-4.6.3                |           py36_0         1.7 MB
    pytorch-1.0.1              |py3.6_cuda9.0.176_cudnn7.4.2_2       320.5 MB  pytorch
    torchvision-0.2.1          |             py_2          37 KB  pytorch
    ------------------------------------------------------------
                                           Total:       322.3 MB

The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/linux-64::cudatoolkit-9.0-h13b8566_0
  pytorch            pytorch/linux-64::pytorch-1.0.1-py3.6_cuda9.0.176_cudnn7.4.2_2
  torchvision        pytorch/noarch::torchvision-0.2.1-py_2

The following packages will be UPDATED:

  ca-certificates                               2018.12.5-0 --> 2019.1.23-0
  conda                                        4.6.2-py36_0 --> 4.6.3-py36_0


Proceed ([y]/n)?
```

It's possible that an older version of conda is screwing things up. Can you first try `conda install conda` to upgrade your conda utility to the latest version.

**Comment by AAnoosheh** [comment]
Oh yeah conda and anaconda were both updated to latest prior to installing pytorch.
Then upon installing pytorch I get a message saying it needs to downgrade anaconda and conda.

**Comment by soumith** [comment]
that's really weird . could you give me the full output of the command?

**Comment by AAnoosheh** [comment]
Okay found the issue. Doing "conda update anaconda" messed it up.

Anaconda recommends doing "conda update conda" and "conda update anaconda" in that order, but the latter downgrades almost everything for some reason, and then causes a subsequent pytorch install to be weird.

Without doing that second command, things are all fine.

**Comment by jaechanglim** [comment]
I have the same problem. Is the issue solved?

**Comment by tangxiangru** [comment]
I have the same problem. Is the issue solved?

**Comment by jaechanglim** [comment]
@tangxiangru I installed a lower version of cudnn and it worked in my case
try conda install cudnn=7.1.2
