### ISSUE TITLE
AssertionError : Torch not compiled with CUDA enable.

### ISSUE THREAD

**Issue by CaptLJS** [pytorch/pytorch#17005]
I've provided the screenshot of the code that I'm trying to run and the corresponding error message.
I'm using Mac OSX with no CUDA support GPU so these errors were inevitable. However, I don't know how to rectify the code. Please help!
![screen shot 2019-02-12 at 8 03 03 pm](https://user-images.githubusercontent.com/47562344/52642699-86875680-2f01-11e9-8f54-35da7c4ed787.png)
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by albanD** [comment]
Same as #17006 : ask questions on the [forum](https://discuss.pytorch.org/) please.
