### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by CaptLJS** [pytorch/pytorch#17006]
Trying to execute the following code which gives me the corresponding error.
I'm using Mac OSX which is without a CUDA supporting GPU so the error was inevitable.
However, I don't know how to handle the code. Please help!
![screen shot 2019-02-12 at 8 03 03 pm](https://user-images.githubusercontent.com/47562344/52643676-82f4cf00-2f03-11e9-8310-79b6704e2c9c.png)
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by albanD** [comment]
Hi,

As you can see on the second line of the message you sent: "If you have a question or would like help and support, please ask at our [forums](https://discuss.pytorch.org/)."

Could you please ask your question there and avoid opening multiple issues for something that is not an issue.
