### ISSUE TITLE
`from_numpy` on an empty array with non-trivial shape fails.

### ISSUE THREAD

**Issue by odysseus9672** [pytorch/pytorch#17003]
## 🐛 Bug

Pytorch throws an error when attempting to convert an empty numpy array with non-trivial size using the `from_numpy` routine.

## To Reproduce

```python
>>> import numpy as np
>>> import torch
>>> x = np.array([])
>>> xT = torch.from_numpy(x)
>>> xT
tensor([], dtype=torch.float64)
>>> x = np.array([ [] for i in range(10) ])
>>> xT = torch.from_numpy(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Trying to resize storage that is not resizable at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/wheel_3.6/pytorch/aten/src/TH/THStorageFunctions.cpp:70
```

## Expected behavior
An empty array that can be indexed in a fashion similar to the underlying numpy array. The underlying numpy array shows `array([], shape=(10, 0), dtype=float64)` when entered into an interactive terminal, I'd expect something like `tensor([], shape=(10, 0), dtype=float64)`.

## Environment
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.12.6
GCC version: Could not collect
CMake version: version 3.11.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.14.5
[pip] torch==1.0.0
[pip] torchvision==0.2.1
[conda] Could not collect

**Comment by vishwakftw** [comment]
I am unable to reproduce this on master. Could you try upgrading to 1.0.1 and see if the problem persists?

**Comment by odysseus9672** [comment]
Not right now, but I'll come back to this later if I have time. For now, I'll assume that it's fixed in master and mark this closed.
