### ISSUE TITLE
Tensor class should implement __contains__

### ISSUE THREAD

**Issue by sytelus** [pytorch/pytorch#17000]
## 🐛 Bug

Python's recommended method to check if object is array-like is to use `isinstance(obj, collections.abc.Sequence)`. This works on all of Python's native array-like objects including lists and tuples as well as NumPy's ndarray because they all do [implement](https://github.com/numpy/numpy/blob/4cbced22a8306d7214a4e18d12e651c034143922/numpy/core/src/multiarray/sequence.c#L115) `__contains__`. However  PyTorch's Tensor object is some of the rare object that is array-like but fails above test. The simplest implementation could be,

```
def __contains__(self, val):
    return (val == self).any().item()
```

## To Reproduce

```
>>> import torch
>>> t = torch.Tensor()
>>> import collections.abc
>>> isinstance(t, collections.abc.Sequence)
>>> False
```
## Expected behavior

Above should print True just like NumPy's ndarray.

## Environment

PyTorch Version 1.0

**Comment by colesbury** [comment]
You may also need `__reversed__` in newer versions of Python

**Comment by bhushan23** [comment]
as per https://docs.python.org/3/library/collections.abc.html
index and count also needs to be implemented 
btw, @sytelus index and count are not implemented in ndarray as well

Also, we were supporting very different index that is expected which was removed #7639
I think we should go ahead with __contains__ and __reversed__ as of now
and put index and count aside and add later if required

__contains__ and __reversed__ are indeed useful
following is the profiling details (time in sec) for a (1000000,) tensor

```
Traditional Contains:  6.987905025482178
Vectorized Contains:  0.024022340774536133
Traditional Rev: 0.01307368278503418
Vectorized Rev: 0.008577346801757812

```

**Comment by bhushan23** [comment]
@colesbury @gchanan while going over PR @vishwakftw pointed out regarding checking if row exists in a matrix ([here](https://github.com/pytorch/pytorch/pull/17733#discussion_r263627816)). Certainly, this feature is nice to have, but differs from NumPy's behavior which checks if any one element exists or not.

One option is to support both the operation.
default: Numpy like (any one element present return true)
exact_match = True: ensure all the elements are present and in order (e.g. row in a matrix)

what are your thought on this?

**Comment by soumith** [comment]
@bhushan23 seems reasonable to add default to be numpy-like and then `exact_match=True` to be checking sequence + order

**Comment by gchanan** [comment]
@bhushan23 that's not what I see from NumPy, which seems to conform to @vishwakftw version. 
 Maybe your version of NumPy is different:

```
>>> np.__version__
'1.14.3'

>>> x=np.random.randn(2,3)
>>> x
array([[ 0.42885086, -1.06318633,  0.5106499 ],
       [ 2.44880437,  0.56202168, -0.56775608]])

>>> y=x[1].copy()
>>> y[0]=5
>>> y in x
True

**Comment by gchanan** [comment]
If you want the "all" behavior, you could implement https://docs.scipy.org/doc/numpy/reference/generated/numpy.isin.html.

**Comment by bhushan23** [comment]
@gchanan example you shown is default version I am talking about.
@vishwakftw is suggesting row in a matrix version which will return True only if complete row is present in the matrix which is different from isin as well.
Simplest version could be to use isin and then sum over rows and return True if sum equals to size of row.
