### ISSUE TITLE
'no_grad' missing from stub

### ISSUE THREAD

**Issue by malmaud** [pytorch/pytorch#17007]
## 🐛 Bug

`torch.no_grad` seems to be missing from the new stub. Typing `torch.no_` in VSCode is not bringing up any completion suggestions.

## Environment

Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.3
GCC version: Could not collect
CMake version: version 3.12.4

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.14.5
[pip3] torch==1.0.1.post2
[pip3] torchfile==0.1.0
[conda] Could not collect

**Comment by ezyang** [comment]
I believe this is not a problem on master. https://github.com/pytorch/pytorch/pull/17030 is untested but might fix it. @malmaud could you please give it a try?

**Comment by malmaud** [comment]
Oh ya, can confirm it is fixed on master already, so maybe no need for that PR. In that PR though, I think you'd want `from .autograd ...` instead of `from torch.autograd` though to match how the import is done in  `master` now.

**Comment by fmassa** [comment]
@ezyang can we close this then, given that 1.0.1 is frozen and this has been fixed on master apparently?
