### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by CaptLJS** [pytorch/pytorch#17024]
My Code-

TestArr = np.zeros(patchH*patchW*3)
imout = np.zeros((imD.shape[0],imD.shape[1]))

for i in range(int(imD.shape[0]/patchH)):
    for j in range(int(imD.shape[1]/patchW)):
        for l1 in range(3):
            for l2 in range(patchH):
                for l3 in range(patchW):
                    TestArr[l1*patchH*patchW + l2*patchW + l3] = imD[i*patchH +l2][j*patchW+l3][l1]
        TestTensor = torch.from_numpy(TestArr)
        out = net(Variable(TestTensor.double().cuda()))
        outArr = out.data.cpu().numpy()
        for l2 in range(patchH):
            for l3 in range(patchW):
                imout[i*patchH +l2][j*patchW+l3] = outArr[l2*patchW + l3]

The Error-

AssertionError                            Traceback (most recent call last)
<ipython-input-26-3cb960c5f0ba> in <module>
     11                     TestArr[l1*patchH*patchW + l2*patchW + l3] = imD[i*patchH +l2][j*patchW+l3][l1]
     12         TestTensor = torch.from_numpy(TestArr)
---> 13         out = net(Variable(TestTensor.double().cuda()))
     14         outArr = out.data.cpu().numpy()
     15         for l2 in range(patchH):

~\Anaconda3\lib\site-packages\torch\cuda\__init__.py in _lazy_init()
    159         raise RuntimeError(
    160             "Cannot re-initialize CUDA in forked subprocess. " + msg)
--> 161     _check_driver()
    162     torch._C._cuda_init()
    163     _cudart = _load_cudart()

~\Anaconda3\lib\site-packages\torch\cuda\__init__.py in _check_driver()
     89 Alternatively, go to: https://pytorch.org to install
     90 a PyTorch version that has been compiled with your version
---> 91 of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
     92 
     93 

AssertionError: 
The NVIDIA driver on your system is too old (found version 8000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

Please Help!

**Comment by ezyang** [comment]
The error looks pretty self explanatory. Please upgrade your NVIDIA driver!
