### ISSUE TITLE
Generate CircleCI config.yml from a script

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#17038]
The CircleCI `config.yml` file is huge (currently over 3.5K lines) and has a lot of [repetition in lists of configurations](https://github.com/pytorch/pytorch/blob/21ce1da5e9b357ccfd769e2616b9d6914ab70c83/.circleci/config.yml#L1049).

## Drawbacks of the current state
* It is not easy to determine at a glance of these long lists what dimensions of configuration a list covers.
    * the list of values for each dimension is not programmatically accessible
* some shell scripts are written inline in the YAML format (see #17028 for elaboration of downsides)
* Some content can be deduplicated through the use of function calls in a real programming language

## Proposal
* Generate `config.yml` from a script and commit result to Git
* At build time, enforce that the checked-in `config.yml` is identical to that which would be produced from the script

Precedent for generating configuration through a script is set by our use of Groovy in Jenkins.

**Comment by ezyang** [comment]
Sounds reasonable. It's really funny how you always end up writing a yaml generator for this kind of thing lol
