### ISSUE TITLE
Can not subclass `subclass torch.multiprocessing.Pool()`

### ISSUE THREAD

**Issue by igiloh** [pytorch/pytorch#17048]
## 🐛 Bug

Trying to subclass:
```python
class MyPool(torch.multiprocessing.Pool):
   pass
```
Ends up with:
```bash
TypeError: method expected 2 arguments, got 3
```

This does makes sense, as it is not possible to subclass python's `multiprocessing.Pool` as well - but only `multiprocessing.pool.Pool`.  
`multiprocessing.Pool` is **not** a type, but rather a context method:
```python
print ( torch.multiprocessing.Pool)
#output:
<bound method BaseContext.Pool of <multiprocessing.context.DefaultContext object at 0x10f4bd550>>
```

The main problem is that `torch` doesn't expose the `torch.multiprocessing.pool` module - so it impossible to subclass `torch.multiprocessing.pool.Pool()` 
```bash
AttributeError: module 'torch.multiprocessing' has no attribute 'pool'
```

This might be related to #16954 - but I don't think it's a dupe, as the main problem here is exposing the `torch.pool` module.

## To Reproduce

1. `class MyPool(torch.multiprocessing.Pool):`

## Expected behavior
It should be possible to subclass torch's multiprocessing pool.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04 LTS,
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla P100-PCIE-12GB
Nvidia driver version: 390.30
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.14.3
[pip3] torch==1.0.0
[pip3] torchvision==0.2.1
[conda] Could not collect

**Comment by lerks** [comment]
Doesn't the following work?
```
from torch.multiprocessing.pool import Pool
class MyPool(Pool):
    pass
```
It does for me...

**Comment by igiloh** [comment]
No, it doesn't. At least not on python3.6.

This is what happens when you try to instantiate a `MyPool()` object:
```python
from torch.multiprocessing.pool import Pool
class MyPool(Pool):
    pass
```
output:
```
Traceback (most recent call last):
  File "test_subclass_pool.py", line 5, in <module>
    p = MyPool()
  File "/Users/ilaigiloh/anaconda2/envs/gal3/lib/python3.6/multiprocessing/pool.py", line 157, in __init__
    self._setup_queues()
  File "/Users/ilaigiloh/anaconda2/envs/gal3/lib/python3.6/site-packages/torch/multiprocessing/pool.py", line 23, in _setup_queues
    self._inqueue = SimpleQueue()
TypeError: __init__() missing 1 required keyword-only argument: 'ctx'
```

Please re-open the issue

**Comment by igiloh** [comment]
Oh wait - this is a different problem. Now it seems that I'm hitting #16954. I guess it does work... 😄  
Thanks!

**Comment by fmassa** [comment]
Closing this in favor of #16954
