### ISSUE TITLE
Be able to use "@pytorchbot retest this please" to re-run both CircleCI and Jenkins jobs

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#17057]
This will be useful for external contributors who currently rely on closing and re-opening a PR to re-run all CI jobs.

cc @kostmo @ezyang

**Comment by ezyang** [comment]
I am not sure there is a way to do this without getting CircleCI to play ball, unless we write a bot ourselves to listen and send the appropriate CircleCI API calls.

Note that if you install @driazati's browser extension, you get a button to rerun right on the status.

**Comment by albanD** [comment]
Another trick I use is to redo the last commit locally and force push it. That will trigger a full rebuilt with less noise than closing/reopening the PR.

**Comment by vincentqb** [comment]
> Another trick I use is to redo the last commit locally and force push it. That will trigger a full rebuilt with less noise than closing/reopening the PR.

and thanks for pointing offline out that `git commit --amend` creates a new hash for the last commit :)

**Comment by huydhn** [comment]
Closing this as this is not relevant anymore.  Both CircleCI and Jenkins were things of the past.
