### ISSUE TITLE
Previous dll loading tricks don't work anymore with newer Anaconda Python on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#17051]
Reproduced on Python 3.6.8 and 3.7.2, currently, we are doing this to make the DLL visible to the Python DLL loader.
```python
import os
os.environ['PATH'] += 'ADDITIONAL DIRS'
from torch._C import *
```
If we could not figure out an alternative to this method, we may have to put the DLL files under the same directory of `_C.pyd`.

**Comment by peterjc123** [comment]
Looks like it's caused by an upstream issue of Anaconda https://github.com/ContinuumIO/anaconda-issues/issues/10628. They introduced a solution that uses `AddDllDirectory` at https://github.com/ContinuumIO/anaconda-issues/issues/10628#issuecomment-463840404. I'm not sure whether it should be adopted. cc @ezyang @orionr

**Comment by peterjc123** [comment]
Related changes in Anaconda python package: https://github.com/AnacondaRecipes/python-feedstock/commit/ac293a3a2ad5b1343c62a4462379d5384a4a3abb

**Comment by orionr** [comment]
cc @pjh5 and @kostmo

**Comment by peterjc123** [comment]
Well, the PRs #17191 and #17215 are confirmed to fix this issue in the release CI, would someone please merge these PRs?

**Comment by kostmo** [comment]
Working on it.

**Comment by msarahan** [comment]
Hi, I'm from Anaconda.  We'd like to actually not require this change on your side, if we can avoid it.  It's already gone in, and that's fine, but we want to un-break the existing packages if we can.  We've already done a lot of work to re-sync PATH changes in our latest efforts on that python patch (https://github.com/AnacondaRecipes/python-feedstock/blob/master/recipe/0020-Add-CondaEcosystemModifyDllSearchPath.patch).  For some reason, cuda detection is still not working correctly.  Are there any specific libraries or paths from which loads happen that we should watch out for?  We generally use procmon to debug this stuff, and knowing the name of a library that should be loaded can dramatically reduce the amount of stuff that we need to look through.

**Comment by msarahan** [comment]
What we've found so far is that with an old python build (pre-patch), this particular file gets loaded from system32: ``nvfatbinaryLoader.dll``.  With our python load order patch, we're deferring system32.  Thus, when you load your torch/lib path, it is in front of system32 - and that's new.  With our new python binary with the patch, ``nvfatbinaryLoader.dll`` is getting loaded from ``(env_root)\lib\site-packages\torch\lib``, and it looks like it's not loading all kinds of extra other stuff that the one from system32 does (for example, ``C:\ProgramData\NVIDIA Corporation\Drs\nvdrsdb1.bin``).

What's the purpose of that file in your lib folder?

**Comment by msarahan** [comment]
One more followup: if I rename ``torch/lib/nvfatbinaryLoader.dll`` to ``torch/lib/nvfatbinaryLoader.dll.bak``, then things work fine with pytorch 1.0.1 and our latest python build (on test channels right now)

**Comment by msarahan** [comment]
We're leaning towards disabling the new loader behavior by default, but putting it behind an env var.  We receive a lot of issues saying that numpy isn't working - MKL couldn't be loaded.  What we've found is that there's a few software vendors who install MKL DLLs to the system32 folder, which then preempt ours.  When theirs are older than ours, our stuff breaks.  We wanted to get ahead of that, but it seems like it may be more trouble than it is worth, in terms of potentially unexpected library loads, like we see here.  By putting the different load order behind an env var, we'll force people to make that decision for themselves.

**Comment by ezyang** [comment]
cc @soumith 

I'm not entirely sure, but I seem to recall something about how we distribute some CUDA bits in our binary packages to make things easier. Is this true for Windows @peterjc123 ?

**Comment by soumith** [comment]
@peterjc123 owns this stack, so we'll wait for him to respond (he's in Shanghai timezone)

**Comment by peterjc123** [comment]
@msarahan  We have `nvfatbinaryloader.dll` and `nvcuda.dll` shipped in the binaries. We used to have these dlls in `C:\Windows\System32` loaded first, but in 3.7.2, they seem to use the DLLs in the binaries first, which is not what we expected. They are included just to help users to use our package without having the CUDA package installed.

**Comment by peterjc123** [comment]
@msarahan @mingwandroid https://github.com/pytorch/builder/pull/271 I'm trying to remove them with this change.

**Comment by peterjc123** [comment]
@msarahan 
> Are there any specific libraries or paths from which loads happen that we should watch out for?

We just use `torch\lib` and `[AnacondaRoot]\Library\bin` and sometimes `%NVTOOLSEXT_PATH%` (which is `C:\Program Files\NVIDIA Corporation\NvToolsExt`). And here is the list of our major external dependencies: 
```
libiomp5md.dll (installed using intel-openmp or in torch\lib)
CUDA dlls like cudartXX_64.dll (installed using cudatoolkit or in torch\lib or in PATH)
cudnn64_X.dll (in torch\lib or in PATH)
nvtoolsext64_1.dll (in torch\lib or NVTOOLSEXT_PATH\bin)
nvcuda.dll and nvfatbinaryloader.dll (in System32)
```
