### ISSUE TITLE
Allow DataParallel to wrap CPU modules

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#17065]
## 🚀 Feature

Creating a model on CPU and then wrapping the model with `DataParallel` should automatically replicate the model on destination GPUs. Are there any reason to enforce that `DataParallel`'s input model must be on GPU?

## Motivation

```
model = nn.Linear(2, 2)
net = nn.DataParallel(model, device_ids=[0,1])
input_var = torch.randn(10, 2)
net(input_var)
```

The code above throws `TypeError: Broadcast function not implemented for CPU tensors`. It avoid the error, users need to explicitly call `model.cuda()`.

1. It is confusing whether it is the input tensor or the model tensor that should be placed on GPU.
2. When calling `nn.DataParallel(model, device_ids=[0,1])`, we already have enough info on where the model should be replicated. It can be automatically handles regardless of whether the `model` is stored on CPU or GPU.

## Pitch

Support the above code snippet.

**Comment by mrshenli** [comment]
CC @douwekiela @pietern @soumith

**Comment by SsnL** [comment]
> Creating a model on CPU and then wrapping the model with `DataParallel` should automatically replicate the model on destination GPUs. Are there any reason to enforce that `DataParallel`'s input model must be on GPU?

This is not true. The model is broadcast at the beginning of each forward, not when constructing the `DataParallel` wrapper. The disadvantage of having the model on CPU, of course, is that the gradients are reduced to **CPU** at each iteration, which is slow and undesirable. IMO, automatically convert to one GPU upon construction is also not desirable because:
1. Users may save a pointer to the wrapped module and reasonably expect it to still on the original device.
2. It can initialize a CUDA context, which isn't obvious to users that it should.

**Comment by mrshenli** [comment]
@SsnL 

How about explicitly throwing an error when constructing `DataParallel` if the wrapped model is on CPU?

**Comment by SsnL** [comment]
> How about explicitly throwing an error when constructing `DataParallel` if the wrapped model is on CPU?

This SGTM :)

**Comment by douwekiela** [comment]
Okay, I think we should update the documentation for this then? Also, what is the best way to then move `input_var` to GPU? With the `.to()` semantics, we would have to specify one of the device_ids manually?

**Comment by douwekiela** [comment]
Right. So I guess `.cuda()` assigns the tensor to the correct GPU for `DataParallel` automatically (@SsnL can you confirm?)? If so, that should be part of the code snippet imo ;)

**Comment by mrshenli** [comment]
`.cuda()` moves it to the default GPU [[link](https://pytorch.org/docs/master/notes/cuda.html)].

**Comment by SsnL** [comment]
@douwekiela The recommended way is to define one `device` object and use it throughout your program. https://pytorch.org/blog/pytorch-0_4_0-migration-guide/ is a helpful reading.
