### ISSUE TITLE
Saved PyTorch network does not load in libtorch C++

### ISSUE THREAD

**Issue by sto-chastic** [pytorch/pytorch#17073]
## 🐛 Bug

I trained a model using PyTorch Python implementation. This model was saved using `torch.save()` . I then try to load this model on my C++ libtorch implementation using `torch::jit::load("./location/")` which fails. I also tried using `torch::jit::load(ifstream)`  by previously loading the model first as a ifstream binary, in which case this loading fails with a similar error.

## To Reproduce

1. Train a model using Python Pytorch and save it with `torch.save()`.
2. Try to load the model in C++ libtorch using either  `torch::jit::load("./location/model.pt")` or `std::ifstream is ("./location/model.pt", std::ifstream::binary)`

The error trace in the torch::jit::load case is:

> terminate called after throwing an instance of 'c10::Error'
>   what():  load: could not open file ./training_implementation/checkpoints/model.pt (load at /opt/conda/conda-bld/pytorch_1549281116128/work/torch/csrc/jit/import.cpp:250)
> frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fc89f87dcf5 in /home/davidjimenez/.conda/pkgs/pytorch-1.0.1-py3.6_cuda10.0.130_cudnn7.4.2_0/lib/python3.6/site-packages/torch/lib/libc10.so)
> frame #1: torch::jit::load(std::string const&, c10::optional<c10::Device>) + 0x1e8 (0x7fc8c8748b68 in /home/davidjimenez/.conda/pkgs/pytorch-1.0.1-py3.6_cuda10.0.130_cudnn7.4.2_0/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
> frame #2: main + 0xf6 (0x4f358e in ./yolo-app)
> frame #3: __libc_start_main + 0xf0 (0x7fc89c69a830 in /lib/x86_64-linux-gnu/libc.so.6)
> frame #4: _start + 0x29 (0x4b0fc9 in ./yolo-app)
> 
> Aborted (core dumped)

In the std::ifstream case is:

> terminate called after throwing an instance of 'c10::Error'
>   what():  [enforce fail at inline_container.cc:130] . PytorchStreamReader failed checking magic number.
> frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x59 (0x7f58b8092339 in /home/davidjimenez/.conda/pkgs/pytorch-1.0.1-py3.6_cuda10.0.130_cudnn7.4.2_0/lib/python3.6/site-packages/torch/lib/libc10.so)
> frame #1: torch::jit::PyTorchStreamReader::valid(char const*) + 0xe5 (0x7f58dc1cc5e5 in /home/davidjimenez/.conda/pkgs/pytorch-1.0.1-py3.6_cuda10.0.130_cudnn7.4.2_0/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
> frame #2: torch::jit::PyTorchStreamReader::PyTorchStreamReader(std::string, std::istream*) + 0x199 (0x7f58dc1ce539 in /home/davidjimenez/.conda/pkgs/pytorch-1.0.1-py3.6_cuda10.0.130_cudnn7.4.2_0/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
> frame #3: torch::jit::load(std::istream&, c10::optional<c10::Device>) + 0xa9 (0x7f58e0f5c7c9 in /home/davidjimenez/.conda/pkgs/pytorch-1.0.1-py3.6_cuda10.0.130_cudnn7.4.2_0/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
> frame #4: main + 0xe5 (0x4f357d in ./yolo-app)
> frame #5: __libc_start_main + 0xf0 (0x7f58b4eae830 in /lib/x86_64-linux-gnu/libc.so.6)
> frame #6: _start + 0x29 (0x4b0fc9 in ./yolo-app)
> 
> Aborted (core dumped)

## Expected behavior

I expected it to load the model in order to perform inference using my C++ libtorch implementation.

## Environment
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.12.1
[pip] torch==0.4.0
[pip] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.3                      1  
[conda] pytorch                   0.4.0            py36hdf912b8_0    anaconda
[conda] torchvision               0.2.1                      py_2    pytorch

**HOWEVER, I tried it using PyTorch 1.0.1 as well with the same results.**

**Comment by soumith** [comment]
you must've missed it in the tutorials, `torch.save` saves in python pickle format, it cannot be loaded into `libtorch`. `model.save` of a torch.jit.ScriptModule object can save something in a format that libtorch can loadl

**Comment by alokprasad** [comment]
@soumith most of the model are not easily convertible to scriptmodule object , so i guess @sto-chastic presummed model trained using using c++  should be loadable using torch.jit.load

**Comment by talhairfanbentley** [comment]
@sto-chastic , by any chance were you able to accomplish this use case?

**Comment by Coderx7** [comment]
models saved using `torch.save `can not be loaded easily as you need to retaine the very same structure the model was previously trained and saved with. your best bet is to load and save the model `state_dict` and then load that instead. or convert your model into scriptmodule , save it and then load it using c++.
