### ISSUE TITLE
Numpy-Like RandomState object

### ISSUE THREAD

**Issue by petered** [pytorch/pytorch#17079]
## 🚀 Feature
It would be nice to replicate numpy's RandomState API, which creates an object containing the state of a random number generator.  The object has methods for generating random numbers.  i.e.

```
rng = torch.RandomState(seed=1234)
data = rng.randn(3, 4)  # (create a 3x4 random matrix from a standard normal distribution)
```

Currently, you can actually do this, though the feature is [undocumented](https://pytorch.org/docs/stable/torch.html?highlight=rand#torch.rand) and not quite as nice as numpy's way:

```
rng = torch.Generator()
rng.manual_seed(1234)
data = torch.randn(3, 4, generator=rng) 
```

## Motivation

Pytorch is currently a bit awkward when it comes to random seeds, because the only officially supported option is to globally set random seeds.  For reproducibility and model-comparison, it sometimes makes sense to have separate random number generators for, e.g. initial-parameters and stochastic-inference.

e.g. 

```
model = create_mlp_with_dropout(
    params = initialize_mlp_params(
        layer_sizes = [784, 500, 500, 10], 
        rng = torch.RandomState(param_seed)
        ),
    rng = torch.RandomState(inference_seed)  # random seed for inference
    )
for x, y in sample_minibatches(data, rng=torch.RandomState(data_seed)): 
    model.train(x, y)
```

Of course you could do this by manually reseeding the global random number generator, passing a random number generator object is nicer because it makes the dependence on the seed explicit.

## Alternatives

You could also just document the current solution, though numpy's seems more elegant.  

Another alternative would be just to add a context manager `with torch.use_random_state(generator=rng): ...`, which sets the global generator to `rng` on entrance and reverts to the previous on exit.  However it still seems more pythonic to pass the generator as an optional argument than be messing around with global variables.  

## Additional context

This arose from a discussion [here](https://discuss.pytorch.org/t/is-there-a-randomstate-equivalent-in-pytorch-for-local-random-generator-seeding/37131/4)

**Comment by ezyang** [comment]
Hypothetically Generator is supposed to be this, but it's hella busted. @syed-ahmed was working on fixing this.

**Comment by t-vi** [comment]
Just to add context: #16604 is one of the PRs that work towards improving the status.

**Comment by syed-ahmed** [comment]
torch.Generator() is now documented here: https://pytorch.org/docs/master/torch.html#generators and should behave like numpy `RandomState` now. Following is an example usage. @petered Please feel free to document here if there is something we have missed, otherwise we can close this issue.

```
>>> import torch
>>> a = torch.Generator(device='cuda')
>>> b = torch.FloatTensor(10).cuda().uniform_(generator=a)
>>> b
tensor([0.3931, 0.5116, 0.8851, 0.4404, 0.8998, 0.1218, 0.5304, 0.3333, 0.2389,
        0.5041], device='cuda:0')
>>> a = torch.Generator()
>>> b = torch.FloatTensor(10).cuda().uniform_(generator=a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

>>> a = torch.Generator(device='cuda')
>>> torch.normal(torch.Tensor([0.5]).cuda(), 0.5, generator=a)
tensor([-0.3292], device='cuda:0')

>>> a = torch.Generator()
>>> torch.normal(torch.Tensor([0.5]).cuda(), 0.5, generator=a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

```

**Comment by peteroconnor-bc** [comment]
Nice!
