### ISSUE TITLE
feature request: depthwise separable convolution

### ISSUE THREAD

**Issue by hyqneuron** [pytorch/pytorch#1708]
I don't see an implementation for [depthwise separable convolution](https://arxiv.org/pdf/1610.02357.pdf). Currently it is possible with `Conv2d` by setting `groups=out_channels`. However this is painstakingly slow. See benchmark at bottom. We need an efficient implementation for this.

I realize torch7's `SpatialDepthWiseConvolution` is still slower. However TF seems to have a [slightly optimized implementation](https://github.com/tensorflow/tensorflow/blob/f488419cd6d9256b25ba25cbe736097dfeee79f9/tensorflow/core/kernels/neon/neon_depthwise_conv_op.cc), so their depthwise conv is about 3x-8x faster than the normal conv (comparing 3x3 conv with 3x3 depthwise conv ONLY, without pointwise conv), but still slow.

Benchmark comparing time (in seconds) of different group size (groups=1,2,4,256). We can see that for small number of groups we get reasonable speedup. For large number of groups it gets much slower instead.
```
Sequential (
  (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (7): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (8): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (9): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)
testing model of weight size: torch.Size([256, 256, 3, 3])
3.65793013573
Sequential (
  (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2)
  (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2)
  (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2)
  (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2)
  (4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2)
  (5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2)
  (6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2)
  (7): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2)
  (8): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2)
  (9): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2)
)
testing model of weight size: torch.Size([256, 128, 3, 3])
1.99519991875
Sequential (
  (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
  (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
  (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
  (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
  (4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
  (5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
  (6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
  (7): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
  (8): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
  (9): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
)
testing model of weight size: torch.Size([256, 64, 3, 3])
1.34896993637
Sequential (
  (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
  (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
  (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
  (3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
  (4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
  (5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
  (6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
  (7): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
  (8): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
  (9): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256)
)
testing model of weight size: torch.Size([256, 1, 3, 3])
5.64783811569

```

**Comment by jekbradbury** [comment]
As this underlies https://arxiv.org/abs/1706.03059 the demand for depthwise separable convs will only continue to grow. I believe this is largely a case of cuDNN not providing an optimized implementation; perhaps a new THCUNN kernel is in order -- maybe first for 1D, which should be less complex?

**Comment by fmassa** [comment]
For the record, there is an implementation in [THNN/THCUNN of `SpatialDepthWiseConvolution`](https://github.com/pytorch/pytorch/blob/master/torch/lib/THCUNN/generic/SpatialDepthWiseConvolution.cu) which are mostly performing a for loop over the number of groups, so it shouldn't be any more efficient than our current implementation using `groups=nInputPlane`. But we could maybe modify it to use `bmm` instead of `mm`, as in the Chainer example?

**Comment by soumith** [comment]
making this high pri, looks like demand for this is off the charts.

**Comment by szagoruyko** [comment]
ported caffe depthwise conv2d here https://github.com/szagoruyko/pyinn (needs CuPy)

**Comment by futurely** [comment]
https://github.com/pytorch/pytorch/pull/2263/commits/3522d3a7f8b255592b89f06e9747d822dee0cd89

**Comment by amdcat** [comment]
Anything new about this problem? 
depthwise convolution is still slow in my pytorch environment

**Comment by WendyShang** [comment]
Hi, based on this paper (https://arxiv.org/pdf/1608.04337.pdf, I think this is one of the earliest discovery of such separable convolution but somehow was ignored), we can benefit by adding flexibility in separating channels into non-overlapping subgroups and perform separate convolutions on each separate subgroup, thus not necessarily view each channel separately and perform convolution on each individual depth only. There are similar walkarounds to achieve such design as depth convolution, though also slow. 

This adds more flexibility in architecture design and it would be great if PyTorch may consider a more flexible version than the original Torch depthwise separable convolution :)

**Comment by qianguih** [comment]
Hi,

Just want to check the status of this thread. I tested the latest version of pytorch. Looks like there is no update about separable convolution yet. Please correct me if I'm wrong. : )

**Comment by rkaplan** [comment]
Looking forward to this feature being implemented!

**Comment by soumith** [comment]
this is now added to master via #3057

**Comment by qianguih** [comment]
Hi,
Thanks for your amazing work on this! Just updated my pytorch for a faster depthwise convolution. However, I coudn't find documentations about how to call the new depthwise conv function. Is there any example for this?

**Comment by colesbury** [comment]
@qianguih use `groups= in_channels =out_channels` e.g.:

```python
m = nn.Conv2d(128, 128, kernel_size=3, groups=128)
```

**Comment by qianguih** [comment]
@colesbury  I see. Thank you!

**Comment by elliothe** [comment]
Since the pytorch and torch share the same backend THCUNN file, could I make this spatialdepthwiseconvolution function into Torch? since the orginal function in torch has GPU memory leak problem.

**Comment by killeent** [comment]
@qianguih note that we do support having a depthwise multiplier, so `groups=in_channels` must be true, but `out_channels` can be any multiple of `in_channels`, e.g.:

```
m = nn.Conv2d(128, 256, kernel_size=3, groups=128).cuda()
```

is also valid.

**Comment by killeent** [comment]
@elliothe one potential issue you will likely run into is that the existing `SpatialDepthwiseConvolution` in LuaTorch (the backing implementations are actually removed in this PR) is that the Lua layers have a differing format, see e.g. my thrown away PR here: https://github.com/torch/nn/pull/1277. So you would have to handle some of these differences.

**Comment by elliothe** [comment]
@killeent  Thanks for your answer! What I did is to remake the torch.cunn with the replaced THCUNN library. Then I receive the following errors when I try to call the `SpatialDepthwiseConvolution` function:

```
not found: THNN_CudaSpatialDepthWiseConvolution_updateOutput/home/elliot/torch/install/share/lua/5.1/nn/THNN.lua:108: failed to find function/global THNN_CudaSpatialDepthWiseConvolution_updateOutput	
not found: THNN_CudaSpatialDepthWiseConvolution_updateGradInput/home/elliot/torch/install/share/lua/5.1/nn/THNN.lua:108: failed to find function/global THNN_CudaSpatialDepthWiseConvolution_updateGradInput	
not found: THNN_CudaSpatialDepthWiseConvolution_accGradParameters/home/elliot/torch/install/share/lua/5.1/nn/THNN.lua:108: failed to find function/global THNN_CudaSpatialDepthWiseConvolution_accGradParameters	
not found: THNN_CudaDoubleSpatialDepthWiseConvolution_updateOutput/home/elliot/torch/install/share/lua/5.1/nn/THNN.lua:108: failed to find function/global THNN_CudaDoubleSpatialDepthWiseConvolution_updateOutput	
not found: THNN_CudaDoubleSpatialDepthWiseConvolution_updateGradInput/home/elliot/torch/install/share/lua/5.1/nn/THNN.lua:108: failed to find function/global THNN_CudaDoubleSpatialDepthWiseConvolution_updateGradInput	
not found: THNN_CudaDoubleSpatialDepthWiseConvolution_accGradParameters/home/elliot/torch/install/share/lua/5.1/nn/THNN.lua:108: failed to find function/global THNN_CudaDoubleSpatialDepthWiseConvolution_accGradParameters	
not found: THNN_CudaHalfSpatialDepthWiseConvolution_updateOutput/home/elliot/torch/install/share/lua/5.1/nn/THNN.lua:108: failed to find function/global THNN_CudaHalfSpatialDepthWiseConvolution_updateOutput	
not found: THNN_CudaHalfSpatialDepthWiseConvolution_updateGradInput/home/elliot/torch/install/share/lua/5.1/nn/THNN.lua:108: failed to find function/global THNN_CudaHalfSpatialDepthWiseConvolution_updateGradInput	
not found: THNN_CudaHalfSpatialDepthWiseConvolution_accGradParameters/home/elliot/torch/install/share/lua/5.1/nn/THNN.lua:108: failed to find function/global THNN_CudaHalfSpatialDepthWiseConvolution_accGradParameters	
```
I am wondering whether the formating problem you mentioned leads to this error.

**Comment by ngimel** [comment]
The problem here is that torch.nn is calling SpatialDepth**W**iseConvolution that was removed https://github.com/torch/nn/blob/master/SpatialDepthWiseConvolution.lua#L80. torch.nn has to be fixed to call SpatialDepth**w**iseConvolution routines.

**Comment by KeCh96** [comment]
I have upgrade my pytorch to 0.3.0, but I found `m = nn.Conv2d(128, 256, kernel_size=3, groups=128)` is still 2 times slower than `m = nn.Conv2d(128, 256, kernel_size=3)`.  I am really confused by this problem, should I need to upgrade pytorch to other version? @killeent  @qianguih

**Comment by KeCh96** [comment]
I am using cuda8.0  . Do I need cuda 9?

**Comment by fmassa** [comment]
@KeCh96 I believe the number of input channels should be equal to the number of output channels for the new codepath to be activated

**Comment by ngimel** [comment]
New codepath should be activated for these parameters. The reason non-grouped convolution is still faster likely is that a very efficient winograd kernel from cudnn is used for it. Depthwise-separable convolutions are bandwidth-bound, thus never will have as high performance as compute-bound ones, also, the kernels are very simple, not even using shared memory, so that can be optimized too. I also suspect that perf for the different number of input and output channels is worse than for the same, another avenue for optimization.

**Comment by fmassa** [comment]
@ngimel yes, you are right. I had just looked at the comment in [the code](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Convolution.cpp#L144-L146) and not in the actual code itself. We should probably update that comment.

**Comment by KeCh96** [comment]
I have tested `m = nn.Conv2d(64, 64, kernel_size=3, groups=128)` and `m = nn.Conv2d(64, 64, kernel_size=3, groups=1)` on both GPU and CPU. In my network, input_channel*K = output_channel, where K is 1 or 2. And I set batchsize=1. The result is as below:

GPU:
group=1         examples_per_sec: 83
group=4         examples_per_sec: 67
group=32       examples_per_sec: 91

CPU:
group=1         examples_per_sec: 80
group=4         examples_per_sec: 81
group=32       examples_per_sec: 17

Note: my pytorch is 0.3.0, and anaconda is 3-5.0.1. Both are latest version. My CPU is Intel(R) `Xeon(R) CPU E5-2680 v4 @ 2.40GHz `, and GPU is Tesla K80. My cuda is 8.0



@fmassa @ngimel

**Comment by KeCh96** [comment]
I also test Conv3d operation on both GPU and CPU. Also, input_channel*K = output_channel, where K is 1 or 2. And I set batchsize=8. The result is as below:

GPU:

> group=1            examples_per_sec: 170
> group=4            examples_per_sec: 154
> group=in_channel      examples_per_sec: 22  (where `in_channel` can be 64,128,256,512)

CPU:

> group=1            examples_per_sec: 3
> group=4            examples_per_sec: 3
> group=in_channel       examples_per_sec: 3  (where `in_channel` can be 64,128,256,512)

Note: This experiment is done on another computer, which CPU is `Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz` and GPU is TITAN Xp.

I have checked these experiments and feel great confused. Anyone run into the same problem?

**Comment by KeCh96** [comment]
Does "bandwidth-bound" means transfering data between CPU and GPU? If so, we should not run into "bandwidth-bound" when we only use CPU. But in my experiment above, I found the speed also drops when I use CPU. @ngimel

**Comment by tstandley** [comment]
I'm not sure I buy the "bandwidth bound" explanation either. If you increase the kernal size from 3x3 to say 5x5, your operation needs the same amount of non-cache memory, but takes way longer.

I don't know how to program cuda, but here's how I see the operation working:
Let's say we run a Conv2d(1024, 1024, kernel_size=3, groups=1024) on a shape 20x20x1024 tensor:

Read a single channel from a single layer into cache. That's 400 floats (1600 bytes). It will fit into cache.
Read that channels worth of parameters into cache (that's just 9 floats)

Then we do the following 18x18 times:
  Multiply those 9 floats (weights) by the appropriate 9 floats in the channel from cache.
  Store the output in the appropriate cell in a 18x18 matrix in main memory.

Here we have one main memory read and one main memory write per channel per spacial location.

If we do the same operation with Conv2d(1024, 1024, kernel_size=5, groups=1024), we should still be doing only one read and one write per spacial location per channel from main memory.

The amount of time this takes should be insignificant next to the pointwise convolution that follows the channel wise convolution:
Conv2d(1024, 1024, kernel_size=1, groups=1)

Here we need to read a million floats from main memory and do 400 1024x1024 matrix multiplies.

The channel-wise operation shouldn't even register next to that.

I really wish we could get this working. We could have blazing fast convolutions with arbitrarily large kernels.

**Comment by SeungjunNah** [comment]
Hi,

Currently, pytorch is using thnn implementation of depthwise convolution, [thnn_conv_depthwise2d](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Convolution.cpp#L350), instead of cudnn.

According to recent [cudnn 7.1.1 release notes](http://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_711.html#rel_711), it seems like cudnn has implemented group convolution for groupCount>1 for all forward & backward algorithms.
Also, current [cudnn api reference](http://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnConvolutionForward) says the winograd algorithm supports group count greater than 0.

Is there any plans to switch group convolution backend from thnn to cudnn?

**Comment by ibmua** [comment]
I'm also much interested in this. NVidia guy emailed me a year ago saying they're gonna implement grouping feature. Yet, it's still nowhere to be found.. This is one of the biggest things in DL in the last several years, yet it doesn't come into fruition. Hope you guys are gonna include it fast, and thanks @SeungjunNah for noting the release notes.

**Comment by soumith** [comment]
@colinfang fwiw cudnn hasn't optimized for depthwise convolution, only optimized for group convolution (which is a general case of depthwise)

**Comment by ngimel** [comment]
cudnn has some kernels for depthwise-separable but on average they are no better than pytorch's. Feel free to bring over Tensorflow's tailored implementation to pytorch.

**Comment by colinfang** [comment]
In my case the input is 9x9, kernel is 5x5 and the input channel == output channel == 50000 == groups

**Comment by fmassa** [comment]
I haven't checked the TF implementation, but I believe one reason why it might be faster in his case is because his number of channels is fairly large, and TF use by default NHWC layout?

**Comment by ngimel** [comment]
Also, I don't know how heavily templated tf's is. In pytorch, 5x5 templates are not instantiated and fall to generic case, which might be 2 times slower than if they were instantiated.

**Comment by colinfang** [comment]
I think tf also only does 3x3 kernel templates. But it has special code path for image of size up to 32x32, not sure if it is relevant.   (NHWC or NCHW don't make much difference in trf) 
 https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/depthwise_conv_op_gpu.cu.cc#L41  The fastest algorithm for forward in cudnn7.1 is `conv2d_grouped_direct_kernel`, (spotted from nvprof), not sure what that is. (It might be `CUDNN_CONVOLUTION_FWD_ALGO_DIRECT` but on the sdk it says it is not implementated in cudnn)

**Comment by mmazeika** [comment]
Would it be possible to port this to 3D convolutions?

**Comment by ezyang** [comment]
PyTorch 0.4 with cuDNN should be sufficient.

**Comment by assassint2017** [comment]
cuDNN7？

**Comment by austingg** [comment]
latest cudnn7 patch has supported depthwise conv path

**Comment by Kongsea** [comment]
I have a question.
For example, if my input is (64, 128, 7, 7), then if using depthwise convolution, it will be: nn.Conv2d(128, 256, 3, groups=256).
However, in this situation, there will be 256 different kernels. But if I want this 256 kernels to be a some one kernel (i.e., sharing kernel weights). How to set the parameters in this situation?
Thank you.

**Comment by wandering007** [comment]
@Kongsea 

```
m = nn.Conv2d(128, 256, 3, groups=128)
m.weight.data = m.weight.data[0].expand(256, *m.weight.shape[1:])
```

**Comment by Kongsea** [comment]
@wandering007 Thank you.

**Comment by austingg** [comment]
@myih  [cudnn v7 release note](https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_704.html#rel_704).  `Performance improvements for grouped convolutions when input channels and output channels per group are 1, 2, or 4 for the following algorithms`

**Comment by SeungjunNah** [comment]
@ibmua According to [cudnn v7.3.0](https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_730.html#rel_730) and [cudnn v7.6.0](https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_760.html#rel_760) release notes, NVIDIA doesn't seem to be working on NCHW format.
Looks like it will take some time until cudnn group/depthwise convolution gets faster in PyTorch.

**Comment by XIEYUNSCUT** [comment]
> @ibmua According to [cudnn v7.3.0](https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_730.html#rel_730) and [cudnn v7.6.0](https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_760.html#rel_760) release notes, NVIDIA doesn't seem to be working on NCHW format.
> Looks like it will take some time until cudnn group/depthwise convolution gets faster in PyTorch.

According to cudnn v7.6.3 release notes，the latest cudnn seems to support depth-wise convolution well。can you check it？thank you very much!

**Comment by HansBambel** [comment]
> @ibmua According to [cudnn v7.3.0](https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_730.html#rel_730) and [cudnn v7.6.0](https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_760.html#rel_760) release notes, NVIDIA doesn't seem to be working on NCHW format.
> Looks like it will take some time until cudnn group/depthwise convolution gets faster in PyTorch.

Does this mean with the new PyTorch 1.5 **‘CHANNELS LAST’ MEMORY FORMAT** we can expect group/depthwise convolutions to speed up?

**Comment by tstandley** [comment]
@HansBambel For what it's worth, I just checked for my implementation of Xception using channels last (and apex fp16). It was actually considerably slower. 50% or so slower. I also ran the apex imagenet example, and didn't see a noticeable speedup for resnet50 (which doesn't have grouped convolutions) with channels last. Both tested on two Titan RTX's with nvlink.

**Comment by VitalyFedyunin** [comment]
@tstandley can you please share mode details how you run apex imagenet example, to identify problem. We can do it in separate issue/slack/forum or any other way.

**Comment by tstandley** [comment]
Ok, so I think I've traced the problem to two things. The first is that I have other operations in my network after the encoder portion that are way slower with channels_last. I'm not sure what they are, maybe some of the losses, or ConvTranspose2d. That wasn't tested on the apex imagenet example, but I was using the apex library with O1.

The other "issue" is that I'm using DataParallel, and not doing MPSG training. When I just run with a single GPU and Xception just on imagenet with apex (O1), I do get about a 20% speedup with channels last. That's awesome, but on mnasnet, I get a CUDA illegal memory access with channels last and I don't get that error without that flag.

Also see my other bug on distributed training.

**Comment by ngimel** [comment]
ConvTranspose2d should be as fast as regular conv in channels last, please file an issue if you find out that's not the case. You can try using autograd profiler or pyprof (which unfortunately now lives only in one of the authors forks https://github.com/adityaiitb/pyprof2) to narrow down what's getting slower. 
Also, please file an issue for your illegal memory access. It's unlikely that it's pure apex bug, likely something is buggy with channels-last in pytorch core. 
Thank you, this is extremely helpful!
