### ISSUE TITLE
UCS2 Python version not working 

### ISSUE THREAD

**Issue by pppplin** [pytorch/pytorch#17094]
## 📚 Documentation
Hi,

I am trying to install pytorch with the python2.7 UCS2 version found here: https://download.pytorch.org/whl/cu80/torch-1.0.1.post2-cp27-cp27m-linux_x86_64.whl. But it still gives the undefined symbol: PyUnicodeUCS2_DecodeUTF8 error. I am in Linux, pip, python2.7 and cuda8.0. Thanks!

**Comment by soumith** [comment]
we use an official python 2.7.15 UCS2 built from source.
Maybe python minor versions have symbol additions here? for example 2.7.3 vs 2.7.15.

**Comment by pppplin** [comment]
thanks! its python 2.7.5
