### ISSUE TITLE
where is the code for the implement of loss?

### ISSUE THREAD

**Issue by Jasperty** [pytorch/pytorch#17111]
i want to find the implement of nn.BCEWithLogitsLoss, but it returns F functions , and i cannot find where F functions is , i want to modify the loss

**Comment by zou3519** [comment]
Please ask future questions on our forums.

The implementation is here: https://github.com/pytorch/pytorch/blob/517c7c98610402e2746586c78987c64c28e024aa/aten/src/ATen/native/Loss.cpp#L90
