### ISSUE TITLE
Is the system python (not conda) supported?

### ISSUE THREAD

**Issue by hlzz** [pytorch/pytorch#1711]
I encountered the following issue after the installation. The installation seems fine to me:
(system info: Mac 10.12.5, cuda 8.0, nvcc V8.0.61, clang-800.0.42.1)

> [ 50%] Linking CXX shared library libshm.dylib
> [ 75%] Built target torch_shm_manager
> [100%] Built target shm
> Install the project...
> -- Install configuration: "Release"
> -- Installing: /Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/lib/libshm.dylib
> -- Up-to-date: /Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/libshm.h
> -- Up-to-date: /Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/bin/torch_shm_manager
> Updating install_name for libTH.1.dylib
> Updating install_name for libTHC.1.dylib
> Updating install_name for libTHCS.1.dylib
> Updating install_name for libTHCUNN.1.dylib
> Updating install_name for libTHNN.1.dylib
> Updating install_name for libTHPP.1.dylib
> Updating install_name for libTHS.1.dylib
> Updating install_name for libshm.dylib
> running build
> running build_py
> -- Building version 0.1.12+ac1c674
> copying torch/version.py -> build/lib.macosx-10.12-x86_64-2.7/torch
> copying torch/lib/libshm.dylib -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/libTH.1.dylib -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/libTHC.1.dylib -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/libTHCS.1.dylib -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/libTHCUNN.1.dylib -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/libTHNN.1.dylib -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/libTHPP.1.dylib -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/libTHS.1.dylib -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/torch_shm_manager -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/THCUNN.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/THNN.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib
> copying torch/lib/include/TH/TH.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THAllocator.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THAtomic.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THBlas.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THDiskFile.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THFile.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THFilePrivate.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGeneral.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateAllTypes.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateByteType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateCharType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateDoubleType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateFloatType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateFloatTypes.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateHalfType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateIntType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateIntTypes.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateLongType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THGenerateShortType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THHalf.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THLapack.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THLogAdd.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THMath.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THMemoryFile.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THRandom.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THStorage.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THTensor.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THTensorApply.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THTensorDimApply.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THTensorMacros.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/THVector.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH
> copying torch/lib/include/TH/generic/THBlas.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/TH/generic/THLapack.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/TH/generic/THStorage.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/TH/generic/THStorageCopy.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/TH/generic/THTensor.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/TH/generic/THTensorConv.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/TH/generic/THTensorCopy.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/TH/generic/THTensorLapack.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/TH/generic/THTensorMath.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/TH/generic/THTensorRandom.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/TH/generic/THVector.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/TH/generic
> copying torch/lib/include/THC/THC.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCAllocator.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCBlas.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCCachingAllocator.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCCachingHostAllocator.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGeneral.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGenerateAllTypes.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGenerateByteType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGenerateCharType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGenerateDoubleType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGenerateFloatType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGenerateFloatTypes.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGenerateHalfType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGenerateIntType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGenerateLongType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCGenerateShortType.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCHalf.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCSleep.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCStorage.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCStorageCopy.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCStream.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCTensor.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCTensorConv.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCTensorCopy.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCTensorMath.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCTensorRandom.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/THCThreadLocal.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC
> copying torch/lib/include/THC/generic/THCStorage.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCStorageCopy.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensor.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorCopy.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorIndex.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMasked.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMath.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMathBlas.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMathCompare.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMathCompareT.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMathMagma.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMathPairwise.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMathPointwise.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMathReduce.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMathScan.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorMode.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorRandom.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorScatterGather.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorSort.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> copying torch/lib/include/THC/generic/THCTensorTopK.h -> build/lib.macosx-10.12-x86_64-2.7/torch/lib/include/THC/generic
> running build_ext
> -- Building with NumPy bindings
> -- Detected cuDNN at /usr/local/cuda/lib, /usr/local/cuda/include
> -- Detected CUDA at /usr/local/cuda
> -- Not using NCCL
> building 'torch._C' extension
> clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/STW/Documents/Projects/pytorch -I/Users/STW/Documents/Projects/pytorch/torch/csrc -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/TH -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THPP -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THNN -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c torch/csrc/PtrWrapper.cpp -o build/temp.macosx-10.12-x86_64-2.7/torch/csrc/PtrWrapper.o -D_THP_CORE -std=c++11 -Wno-write-strings -DWITH_NUMPY -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
> clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/STW/Documents/Projects/pytorch -I/Users/STW/Documents/Projects/pytorch/torch/csrc -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/TH -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THPP -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THNN -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c torch/csrc/Generator.cpp -o build/temp.macosx-10.12-x86_64-2.7/torch/csrc/Generator.o -D_THP_CORE -std=c++11 -Wno-write-strings -DWITH_NUMPY -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
> clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/STW/Documents/Projects/pytorch -I/Users/STW/Documents/Projects/pytorch/torch/csrc -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/TH -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THPP -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THNN -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c torch/csrc/Exceptions.cpp -o build/temp.macosx-10.12-x86_64-2.7/torch/csrc/Exceptions.o -D_THP_CORE -std=c++11 -Wno-write-strings -DWITH_NUMPY -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
> clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/STW/Documents/Projects/pytorch -I/Users/STW/Documents/Projects/pytorch/torch/csrc -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/TH -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THPP -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THNN -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c torch/csrc/DynamicTypes.cpp -o build/temp.macosx-10.12-x86_64-2.7/torch/csrc/DynamicTypes.o -D_THP_CORE -std=c++11 -Wno-write-strings -DWITH_NUMPY -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
> error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.9" but "10.12" during configureclang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/STW/Documents/Projects/pytorch -I/Users/STW/Documents/Projects/pytorch/torch/csrc -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/TH -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THPP -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THNN -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c torch/csrc/utils.cpp -o build/temp.macosx-10.12-x86_64-2.7/torch/csrc/utils.o -D_THP_CORE -std=c++11 -Wno-write-strings -DWITH_NUMPY -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
> 
> clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/STW/Documents/Projects/pytorch -I/Users/STW/Documents/Projects/pytorch/torch/csrc -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/TH -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THPP -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THNN -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c torch/csrc/utils/tuple_parser.cpp -o build/temp.macosx-10.12-x86_64-2.7/torch/csrc/utils/tuple_parser.o -D_THP_CORE -std=c++11 -Wno-write-strings -DWITH_NUMPY -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
> clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/STW/Documents/Projects/pytorch -I/Users/STW/Documents/Projects/pytorch/torch/csrc -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/TH -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THPP -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THNN -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c torch/csrc/serialization.cpp -o build/temp.macosx-10.12-x86_64-2.7/torch/csrc/serialization.o -D_THP_CORE -std=c++11 -Wno-write-strings -DWITH_NUMPY -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
> clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/STW/Documents/Projects/pytorch -I/Users/STW/Documents/Projects/pytorch/torch/csrc -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/TH -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THPP -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THNN -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda/include -I/Users/STW/Documents/Projects/pytorch/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c torch/csrc/autograd/engine.cpp -o build/temp.macosx-10.12-x86_64-2.7/torch/csrc/autograd/engine.o -D_THP_CORE -std=c++11 -Wno-write-strings -DWITH_NUMPY -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN

However, when I tried to 'import torch', I got the following error:

> 
> Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
> [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "torch/__init__.py", line 48, in <module>
>     import torch._dl as _dl_flags
> ImportError: No module named _dl
> >>> import torch.nn as nn
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "torch/__init__.py", line 48, in <module>
>     import torch._dl as _dl_flags
> ImportError: No module named _dl

I guess it may be caused by not using conda? Don't know what to do next.

**Comment by apaszke** [comment]
It is supported, but you have to move out of the repository root (just change the directory).

**Comment by hlzz** [comment]
@apaszke Even if I moved out of the root directory, I still got the error: 

> Traceback (most recent call last):
>   File "tensor_tutorial.py", line 24, in <module>
>     import torch
>   File "/Users/STW/Documents/Projects/pytorch/build/lib.macosx-10.12-x86_64-2.7/torch/__init__.py", line 48, in <module>
>     import torch._dl as _dl_flags
> ImportError: No module named _dl

Any idea what have I done wrong during the installation?

**Comment by apaszke** [comment]
What exact commands did you use to install it?

**Comment by hlzz** [comment]
@apaszke Just `MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install`

**Comment by hlzz** [comment]
And I guess no error happens during the installation. If my PYTHONPATH wrong? I've tried to add `pytorch_root` or `pytorch_root/build/lib.macosx-10.12-x86_64-2.7` but neither of them work.

**Comment by cswhjiang** [comment]
how about using `MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install` ?
