### ISSUE TITLE
pytorch not working on Win 10

### ISSUE THREAD

**Issue by tharindu-mathew** [pytorch/pytorch#17116]
## 🐛 Bug
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Miniconda3\envs\pyt\lib\site-packages\torch\__init__.py", line 84, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
>>>

## To Reproduce

(pyt) C:\Users\Tharindu>conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.3

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: D:\Miniconda3\envs\pyt

  added / updated specs:
    - cudatoolkit=10.0
    - pytorch
    - torchvision

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    six-1.12.0                 |           py36_0          22 KB
    pycparser-2.19             |           py36_0         174 KB
    pillow-5.4.1               |   py36hdc69c19_0         698 KB
    numpy-1.15.4               |   py36h19fb1c0_0          47 KB
    olefile-0.46               |           py36_0          49 KB
    mkl_fft-1.0.10             |   py36h14836fe_0         136 KB
    pytorch-1.0.1              |py3.6_cuda100_cudnn7_1       464.6 MB  pytorch
    numpy-base-1.15.4          |   py36hc3f5095_0         3.9 MB
    cffi-1.11.5                |   py36h74b6da3_1         213 KB
    mkl_random-1.0.2           |   py36h343c172_0         318 KB
    ninja-1.8.2                |   py36he980bc4_1         110 KB
    cudatoolkit-10.0.130       |                0       371.0 MB
    ------------------------------------------------------------
                                           Total:       841.3 MB

The following NEW packages will be INSTALLED:

    blas:         1.0-mkl
    cffi:         1.11.5-py36h74b6da3_1
    cudatoolkit:  10.0.130-0
    freetype:     2.9.1-ha9979f8_1
    icc_rt:       2019.0.0-h0cc432a_1
    intel-openmp: 2019.1-144
    jpeg:         9b-hb83a4c4_2
    libpng:       1.6.36-h2a8f88b_0
    libtiff:      4.0.10-hb898794_2
    mkl:          2019.1-144
    mkl_fft:      1.0.10-py36h14836fe_0
    mkl_random:   1.0.2-py36h343c172_0
    ninja:        1.8.2-py36he980bc4_1
    numpy:        1.15.4-py36h19fb1c0_0
    numpy-base:   1.15.4-py36hc3f5095_0
    olefile:      0.46-py36_0
    pillow:       5.4.1-py36hdc69c19_0
    pycparser:    2.19-py36_0
    pytorch:      1.0.1-py3.6_cuda100_cudnn7_1 pytorch
    six:          1.12.0-py36_0
    tk:           8.6.8-hfa6e2cd_0
    torchvision:  0.2.1-py_2                   pytorch
    xz:           5.2.4-h2fa13f4_4
    zlib:         1.2.11-h62dcd97_3
    zstd:         1.3.7-h508b16e_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
six-1.12.0           | 22 KB     | ############################################################################################################################################################################################### | 100%
pycparser-2.19       | 174 KB    | ############################################################################################################################################################################################### | 100%
pillow-5.4.1         | 698 KB    | ############################################################################################################################################################################################### | 100%
numpy-1.15.4         | 47 KB     | ############################################################################################################################################################################################### | 100%
olefile-0.46         | 49 KB     | ############################################################################################################################################################################################### | 100%
mkl_fft-1.0.10       | 136 KB    | ############################################################################################################################################################################################### | 100%
pytorch-1.0.1        | 464.6 MB  | ############################################################################################################################################################################################### | 100%
numpy-base-1.15.4    | 3.9 MB    | ############################################################################################################################################################################################### | 100%
cffi-1.11.5          | 213 KB    | ############################################################################################################################################################################################### | 100%
mkl_random-1.0.2     | 318 KB    | ############################################################################################################################################################################################### | 100%
ninja-1.8.2          | 110 KB    | ############################################################################################################################################################################################### | 100%
cudatoolkit-10.0.130 | 371.0 MB  | ############################################################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(pyt) C:\Users\Tharindu>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 11 2019, 15:03:47) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pytorch'
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Miniconda3\envs\pyt\lib\site-packages\torch\__init__.py", line 84, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
>>>

## Expected behavior

Pytorch working

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Education
GCC version: Could not collect
CMake version: version 3.13.2

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 417.71
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] torch==1.0.1
[pip] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl_fft                   1.0.10           py36h14836fe_0
[conda] mkl_random                1.0.2            py36h343c172_0
[conda] pytorch                   1.0.1           py3.6_cuda100_cudnn7_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by peterjc123** [comment]
related to https://github.com/pytorch/pytorch/issues/17051.

**Comment by tharindu-mathew** [comment]
Thanks for the suggestion. Downgrading python to 3.6.7, makes pytorch work. I believe this should be an acceptable workaround to many.

**Comment by nm46nm** [comment]
> related to #17051. You may downgrade your python to 3.6.7.

I downgrade my python from 3.6.8 to 3.6.7 (Anaconda), but it didn't work. The error
`File "D:\Miniconda3\envs\pyt\lib\site-packages\torch_init_.py", line 84, in 
from torch._C import *
ImportError: DLL load failed: The specified module could not be found.`
still occur.

**Comment by peterjc123** [comment]
@nm46nm It should be caused by some other reasons. Would you please try this script https://gist.github.com/peterjc123/21143c0c9426a025618260dde5b6219a?
