### ISSUE TITLE
Bug with torch.autograd.grad, unable to return gradients with respect to multiple input tensors.

### ISSUE THREAD

**Issue by anirbanl** [pytorch/pytorch#17124]
## 🐛 Bug

When multiple input tensors are used as input to SNLI classifier, computation of gradient with respect to multiple input tensor fails. torch.autograd.grad is unable to recognize that those multiple inputs were present in the graph. The input tensors are embeddings tensor corresponding the the premise and hypothesis sentences. They are of shape [#num_words, 1, embed_dim].

## Details of procedure followed:

    class Simple(torch.nn.Module):
        def __init__(self, input_dim, hid_dim, out_dim):
            super(Simple, self).__init__()
            self.lin1=torch.nn.Linear(input_dim,hid_dim)
            self.lin2=torch.nn.Linear(hid_dim,out_dim)
        def forward(self, x, y):
            i1=self.lin1(x)
            i2=self.lin1(y)
            o1=self.lin2(i1)
            o2=self.lin2(i2)
            return torch.add(torch.max(o1,dim=0)[0],torch.max(o2,dim=0)[0])

    model=Simple(10,100,1)
    t=torch.randn((4,1,10))
    u=torch.randn((5,1,10))

    model.train()
    t.requires_grad=True
    u.requires_grad=True
    o=model(t,u)

    sg=torch.autograd.grad(o,(t,u),retain_graph=True)

The above works fine and I get gradients of o wrt t and u. Shapes are exactly same as t and u respectively. However, for the following network, it doesn't work when executing torch.autograd.grad.

    class Bottle(nn.Module):

        def forward(self, input):
            if len(input.size()) <= 2:
                return super(Bottle, self).forward(input)
            size = input.size()[:2]
            out = super(Bottle, self).forward(input.view(size[0]*size[1], -1))
            return out.view(size[0], size[1], -1)

    class Linear(Bottle, nn.Linear):
        pass

    class Encoder(nn.Module):

        def __init__(self, config):
            super(Encoder, self).__init__()
            self.config = config
            input_size = config.d_proj if config.projection else config.d_embed
            dropout = 0 if config.n_layers == 1 else config.dp_ratio
            self.rnn = nn.LSTM(input_size=input_size, hidden_size=config.d_hidden,
                            num_layers=config.n_layers, dropout=dropout,
                            bidirectional=config.birnn)

        def forward(self, inputs):
            batch_size = inputs.size()[1]
            state_shape = self.config.n_cells, batch_size, self.config.d_hidden
            h0 = c0 =  inputs.new_zeros(state_shape)
            outputs, (ht, ct) = self.rnn(inputs, (h0, c0))
            return ht[-1] if not self.config.birnn else ht[-2:].transpose(0, 1).contiguous().view(batch_size, -1)

    class Embedder(nn.Module):
        def __init__(self, config):
            super(Embedder, self).__init__()
            self.config = config
            self.embedding_dim = config.d_embed
            self.embedding = nn.Embedding(config.n_embed, config.d_embed)

        def forward(self, x):
            return self.embedding(x)

    class SNLIClassifier(nn.Module):

        def __init__(self, config):
            super(SNLIClassifier, self).__init__()
            self.config = config
            # self.embed = nn.Embedding(config.n_embed, config.d_embed)
            self.projection = Linear(config.d_embed, config.d_proj)
            self.encoder = Encoder(config)
            self.dropout = nn.Dropout(p=config.dp_ratio)
            self.relu = nn.ReLU()
            seq_in_size = 2*config.d_hidden
            if self.config.birnn:
                seq_in_size *= 2
            lin_config = [seq_in_size]*2
            self.out = nn.Sequential(
                Linear(*lin_config),
                self.relu,
                self.dropout,
                Linear(*lin_config),
                self.relu,
                self.dropout,
                Linear(*lin_config),
                self.relu,
                self.dropout,
                Linear(seq_in_size, config.d_out))

        def forward(self, prem_embed, hypo_embed):
            if self.config.fix_emb:
                prem_embed =prem_embed.detach()
                hypo_embed =hypo_embed.detach()
            if self.config.projection:
                prem_embed = self.relu(self.projection(prem_embed))
                hypo_embed = self.relu(self.projection(hypo_embed))
            premise = self.encoder(prem_embed)
            hypothesis = self.encoder(hypo_embed)
            scores = self.out(torch.cat([premise, hypothesis], 1))
            return scores

    embedder = Embedder(config)
    model = SNLIClassifier(config)

    emb_p, emb_h = getembeddings(sentence_premise, sentence_hypothesis, embedder) # sizes of each tensor is [num_words, 1, embed_dim] , here 1 is number of elements in the batch.
    model.train()
    # Here p_emb and h_emb have requires_grad=True, so not explicitly setting it.
    so=model(p_emb,h_emb)

    sg=torch.autograd.grad(so[0,2], (p_emb,h_emb), retain_graph=True) #here so[0,2] is just one scalar output.

########## Following error happens ###########
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

If I set allow_unused=True, then there is None returned as gradient. Please help me here. Looks like a bug.

## Stack trace:
	In [30]: sg=torch.autograd.grad(so[0,2], (p_emb,h_emb), retain_graph=True)
	---------------------------------------------------------------------------
	RuntimeError                              Traceback (most recent call last)
	<ipython-input-30-4f4060b4139c> in <module>()
	----> 1 sg=torch.autograd.grad(so[0,2], (p_emb,h_emb), retain_graph=True)

	/dccstor/anirlaha1/deep/apr2018/lib/python2.7/site-packages/torch/autograd/__init__.pyc in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused)
	    143     return Variable._execution_engine.run_backward(
	    144         outputs, grad_outputs, retain_graph, create_graph,
	--> 145         inputs, allow_unused)
	    146 
	    147 

	RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Red Hat Enterprise Linux Server release 7.4 (Maipo)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
CMake version: version 2.8.12.2

Python version: 2.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.1
[pip] numpy==1.16.1
[pip] torch==1.0.0
[pip] torchfile==0.1.0
[pip] torchtext==0.3.1
[pip] torchvision==0.2.1
[conda] Could not collect

**Comment by fmassa** [comment]
Can you post a full example that reproduces the problem? `config` is not defined in here.

**Comment by anirbanl** [comment]
I have figured out the issue. It is due to the following few lines:

        if self.config.fix_emb:
            prem_embed =prem_embed.detach()
            hypo_embed =hypo_embed.detach()
