### ISSUE TITLE
Unable to install from source

### ISSUE THREAD

**Issue by quanvuong** [pytorch/pytorch#1713]
I followed the steps to install from source on CentOS with Cuda 7.5

The step `python setup.py install` returns this error:

```
/gpfsnyu/home/qhv200/pytorch/torch/lib/THPP/tensors/generic/THCTensor.cpp:1643: error: no member function ‘getDevice’ declared in ‘thpp::THCTensor<double>’
/gpfsnyu/home/qhv200/pytorch/torch/lib/THPP/tensors/generic/THCTensor.cpp:1648: error: no member function ‘newTensor’ declared in ‘thpp::THCTensor<double>’
make[2]: *** [CMakeFiles/THPP.dir/tensors/THCTensor.cpp.o] Error 1
make[1]: *** [CMakeFiles/THPP.dir/all] Error 2
make: *** [all] Error 2
```

There were many more errors but these are the last few

**Comment by quanvuong** [comment]
Removed the conda env folder and going through the steps again work

**Comment by xushenkun** [comment]
removed CMAKE_PREFIX_PATH and its folder does not work for me.
same errors

**Comment by quanvuong** [comment]
It completedly remove the conda environment folder (rm -rf) and followed the steps from the beginning
