### ISSUE TITLE
[CPP] allow deepcopy on the jit module in the CPP frontend

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#17149]
## 🚀 Feature

allow deepcopy on the jit module in the CPP frontend

## Motivation

Let's say you have actor centric model which contains a mutable state buffer.

```
class ActorModel(jit.ScriptModule):
   def __init__(self):
       self.register_buffer("state", torch.tensor)

   def forward(self, x):
          // each forward mutates the internal buffer of this actor
          self.state += x
         // and then return some prediction
        return self.fancy_math(self.state, x)
```

You need to instantiate a new instance of said Actor Model for each new actor. This is trivial in python

```
inputs = [..., ...]
actors = [..., ...]
actor = ActorModel()
actors.append(actor)

for i, input in enumerate(inputs):
    actor(input)
```

However, if we use JIT, we cannot do this, because in the CPP frontend, the only way to instantiate a script module is by loading it

```
const auto actor = jit::load("actor.pt");
```

If we allow a deepcopy, I just need to load the torchscript graph once and do deepcopy for each new actor.

```
const auto actor_base = jit::load("actor.pt");
const auto new_actor = actor_base.deep_copy();
```

**Comment by suo** [comment]
@ZolotukhinM, we added this right? (This is an issue from a while ago, just doing a cleanup pass)

**Comment by ZolotukhinM** [comment]
Yes, we've added a `torch::jit::script::Module::clone()` method, which is basically a deep copy of a script module:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/module.h#L324-L325

There is also a `torch::nn::Module::clone()` methods available for deep copies of modules created via C++ API:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/nn/module.h#L96-L113
