### ISSUE TITLE
[Build Error]undefined reference to `__cudaPushCallConfiguration'

### ISSUE THREAD

**Issue by Albert-xy** [pytorch/pytorch#17148]
## 🐛 Bug
[ 81%] Linking CXX executable ../bin/device_test
[ 81%] Linking CXX executable ../bin/conv_op_cache_cudnn_test
/home/fanyixing/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/device_test] Error 1
make[1]: *** [caffe2/CMakeFiles/device_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 81%] Linking CXX executable ../bin/event_gpu_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/conv_op_cache_cudnn_test] Error 1
make[1]: *** [caffe2/CMakeFiles/conv_op_cache_cudnn_test.dir/all] Error 2
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/event_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/event_gpu_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/dead_code_elim_test
[ 81%] Linking CXX executable ../bin/distributed_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/dead_code_elim_test] Error 1
make[1]: *** [caffe2/CMakeFiles/dead_code_elim_test.dir/all] Error 2
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/distributed_test] Error 1
make[1]: *** [caffe2/CMakeFiles/distributed_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/cuda_cudnn_test
[ 81%] Linking CXX executable ../bin/cuda_rng_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cuda_cudnn_test] Error 1
make[1]: *** [caffe2/CMakeFiles/cuda_cudnn_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/common_subexpression_elimination_test
[ 81%] Linking CXX executable ../bin/cuda_stream_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/common_subexpression_elimination_test] Error 1
make[1]: *** [caffe2/CMakeFiles/common_subexpression_elimination_test.dir/all] Error 2
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cuda_rng_test] Error 1
make[1]: *** [caffe2/CMakeFiles/cuda_rng_test.dir/all] Error 2
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cuda_stream_test] Error 1
make[1]: *** [caffe2/CMakeFiles/cuda_stream_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/pattern_net_transform_test
[ 81%] Linking CXX executable ../bin/blob_gpu_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/pattern_net_transform_test] Error 1
make[1]: *** [caffe2/CMakeFiles/pattern_net_transform_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/conv_to_nnpack_transform_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/blob_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/blob_gpu_test.dir/all] Error 2
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/conv_to_nnpack_transform_test] Error 1
make[1]: *** [caffe2/CMakeFiles/conv_to_nnpack_transform_test.dir/all] Error 2
Scanning dependencies of target cuda_integer_divider_test
[ 81%] Linking CXX executable ../bin/cuda_integer_divider_test
[ 81%] Linking CXX executable ../bin/utility_ops_gpu_test
[ 81%] Linking CXX executable ../bin/depthwise3x3_conv_op_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cuda_integer_divider_test] Error 1
make[1]: *** [caffe2/CMakeFiles/cuda_integer_divider_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/batch_matmul_op_gpu_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/utility_ops_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/utility_ops_gpu_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/reshape_op_gpu_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/batch_matmul_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/batch_matmul_op_gpu_test.dir/all] Error 2
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/depthwise3x3_conv_op_test] Error 1
make[1]: *** [caffe2/CMakeFiles/depthwise3x3_conv_op_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/elementwise_op_gpu_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/reshape_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/reshape_op_gpu_test.dir/all] Error 2
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/elementwise_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/nnpack_test
[ 81%] Linking CXX executable ../bin/net_gpu_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/nnpack_test] Error 1
make[1]: *** [caffe2/CMakeFiles/nnpack_test.dir/all] Error 2
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/net_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/net_gpu_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/generate_proposals_op_gpu_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/generate_proposals_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/generate_proposals_op_gpu_test.dir/all] Error 2
Scanning dependencies of target cuda_optional_test
[ 81%] Linking CXX executable ../bin/cuda_optional_test
[ 81%] Linking CXX executable ../bin/roi_align_op_gpu_test
/home/fanyixing/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cuda_optional_test] Error 1
make[1]: *** [caffe2/CMakeFiles/cuda_optional_test.dir/all] Error 2
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/roi_align_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/roi_align_op_gpu_test.dir/all] Error 2
[ 81%] Linking CXX executable ../bin/generate_proposals_op_util_nms_gpu_test
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPushCallConfiguration'
/home/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/generate_proposals_op_util_nms_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 734, in <module>
    build_deps()
  File "setup.py", line 281, in build_deps
    build_dir='build')
  File "/home/pytorch/tools/build_pytorch_libs.py", line 251, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/home/users/wangsu/anaconda3/envs/py37/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '24', 'install']' returned non-zero exit status 2.

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: CentOS release 6.5 (Final)
GCC version: (GCC) 5.2.0
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla M40 24GB
GPU 1: Tesla M40 24GB

Nvidia driver version: 384.81
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.15.4
[conda] blas                      1.0                         mkl  
[conda] magma-cuda92              2.4.0                         1    pytorch
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0

**Comment by Albert-xy** [comment]
@svenstaro

**Comment by Albert-xy** [comment]
@soumith

**Comment by fmassa** [comment]
This probably means that the inconsistent version of NVCC compile and your conda CUDAToolKit package

```
# Check the NVCC compile version(e.g.)
/usr/cuda-9.2/bin/nvcc --version
# Check the CUDAToolKit version(e.g.)
~/anaconda3/bin/conda list | grep cuda

# If you need to update your CUDAToolKit
~/anaconda3/bin/conda install -c anaconda cudatoolkit==9.2
```
Both of them should have the same version. For example, if NVCC==9.2 and CUDAToolKit==9.2, this will be fine while when NVCC==9.2 but CUDAToolKit==9, it fails.

**Comment by AlbertoMQ** [comment]
> This probably means that the inconsistent version of NVCC compile and your conda CUDAToolKit package
> 
> ```
> # Check the NVCC compile version(e.g.)
> /usr/cuda-9.2/bin/nvcc --version
> # Check the CUDAToolKit version(e.g.)
> ~/anaconda3/bin/conda list | grep cuda
> 
> # If you need to update your CUDAToolKit
> ~/anaconda3/bin/conda install -c anaconda cudatoolkit==9.2
> ```
> 
> Both of them should have the same version. For example, if NVCC==9.2 and CUDAToolKit==9.2, this will be fine while when NVCC==9.2 but CUDAToolKit==9, it fails.

Shouldn't we be able to use an older CUDAToolkit with newer CUDA drivers? How would we fix this issue if we plan on using multiple versions of CUDA on our machine?

**Comment by henbucuoshanghai** [comment]
the same error    mine is cuda10.0  nvidia418,cudnn7.6         help


tmpxft_00006b56_00000000-5_maxpool_layer_kernels.compute_70.cudafe1.cpp:(.text+0xff5): undefined reference to `__cudaPushCallConfiguration'
obj/maxpool_layer_kernels.o: In function `__device_stub__Z34forward_local_avgpool_layer_kerneliiiiiiiiPfS_(int, int, int, int, int, int, int, int, float*, float*)':
tmpxft_00006b56_00000000-5_maxpool_layer_kernels.compute_70.cudafe1.cpp:(.text+0x11e9): undefined reference to `__cudaPopCallConfiguration'
obj/maxpool_layer_kernels.o: In function `forward_local_avgpool_layer_gpu':
tmpxft_00006b56_00000000-5_maxpool_layer_kernels.compute_70.cudafe1.cpp:(.text+0x12d2): undefined reference to `__cudaPushCallConfiguration'
obj/maxpool_layer_kernels.o: In function `__device_stub__Z35backward_local_avgpool_layer_kerneliiiiiiiiPfS_(int, int, int, int, int, int, int, int, float*, float*)':
tmpxft_00006b56_00000000-5_maxpool_layer_kernels.compute_70.cudafe1.cpp:(.text+0x1489): undefined reference to `__cudaPopCallConfiguration'
obj/maxpool_layer_kernels.o: In function `backward_local_avgpool_layer_gpu':
tmpxft_00006b56_00000000-5_maxpool_layer_kernels.compute_70.cudafe1.cpp:(.text+0x1582): undefined reference to `__cudaPushCallConfiguration'
obj/avgpool_layer_kernels.o: In function `__device_stub__Z28forward_avgpool_layer_kerneliiiiPfS_(int, int, int, int, float*, float*)':
tmpxft_00006bc8_00000000-5_avgpool_layer_kernels.compute_70.cudafe1.cpp:(.text+0xef): undefined reference to `__cudaPopCallConfiguration'
obj/avgpool_layer_kernels.o: In function `forward_avgpool_layer_gpu':
tmpxft_00006bc8_00000000-5_avgpool_layer_kernels.compute_70.cudafe1.cpp:(.text+0x1d6): undefined reference to `__cudaPushCallConfiguration'
obj/avgpool_layer_kernels.o: In function `__device_stub__Z29backward_avgpool_layer_kerneliiiiPfS_(int, int, int, int, float*, float*)':
tmpxft_00006bc8_00000000-5_avgpool_layer_kernels.compute_70.cudafe1.cpp:(.text+0x30f): undefined reference to `__cudaPopCallConfiguration'
obj/avgpool_layer_kernels.o: In function `backward_avgpool_layer_gpu':
tmpxft_00006bc8_00000000-5_avgpool_layer_kernels.compute_70.cudafe1.cpp:(.text+0x3f6): undefined reference to `__cudaPushCallConfiguration'
collect2: error: ld returned 1 exit status
Makefile:170: recipe for target 'darknet' failed
make: *** [darknet] Error 1
