### ISSUE TITLE
The issue of using torch::upsample in C++ while using the libtorch 

### ISSUE THREAD

**Issue by bill4278** [pytorch/pytorch#17156]
## To Reproduce

1.coding CNN model in C++

at::Tensor test = torch::rand({1,1,2, 10 }).to(torch::kCUDA);

std::cout << test << std::endl;

//torch::upsample_nearest1d(test, { 20 });

torch::upsample_bilinear2d(test, {1,1,2,20 }, true);//this line cause that problem

as you can see in the picture:
![image](https://user-images.githubusercontent.com/32795143/52844593-db181500-313f-11e9-95b1-08e7879f80f2.png)

## Environment

 - PyTorch Version (e.g., 1.0): nightly
 - OS (e.g., Linux): window10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): 
 - Python version: 3.5.4
 - CUDA/cuDNN version: 10.0/7.4
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ezyang** [comment]
Is it possible for you to get a backtrace when this occurs?

**Comment by bill4278** [comment]
> Is it possible for you to get a backtrace when this occurs?
thanks for your attention !
if I step into the code :        torch::upsample_bilinear2d(test, {1,1,2,20 }, true);
and the problem is shown in this line:
![image](https://user-images.githubusercontent.com/32795143/52894965-f0e41380-31ed-11e9-91e5-1f1cd3fff2df.png)

**Comment by bill4278** [comment]
Thanks for your attentions, I have finish this bug,the right way to use upsampling function is :
	at::Tensor test = torch::rand({ 1,1,2, 10 }).to(torch::kCUDA);

	std::cout << test << std::endl;

	//torch::upsample_nearest1d(test, { 20 });

	std::cout << torch::upsample_bilinear2d(test, { 2,20 }, true) << std::endl;
