### ISSUE TITLE
Support torch.zeros with HalfTensor (half)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#17163]
```
>>> import torch
>>> torch.zeros(2, dtype=torch.half)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: _th_zero_ is not implemented for type torch.HalfTensor
```

This might be nontrivial to do because zeros is implemented in terms of vectorized fill on CPU, so you'd have to work out how to make that code work for half.

**Comment by SsnL** [comment]
But... zero is just vector fill of all zero bits! So maybe with some casting trick this isn't that hard.

**Comment by zou3519** [comment]
I remember that the reason why this isn't implemented was because we didn't want to implement halftensor operations on CPU tensors, but I don't remember why that is

**Comment by ezyang** [comment]
In general it's hard to implement everything in half on CPU; especially doing so efficiently. It's mostly a question of slowly expanding capabilities as makes sense.

**Comment by vishwakftw** [comment]
I believe this has been addressed by https://github.com/pytorch/pytorch/commit/e0b44cac1feb55e4e5386fa35c223bbd8af3bb82.
