### ISSUE TITLE
Better API / conversion for c++ objects to correct IValue objects

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#17165]
## 🐛 Bug

Tuple of Tensors fails as input to a traced model with C++ front end

https://discuss.pytorch.org/t/creating-a-tuple-of-tensors-as-input-to-a-traced-model-with-the-c-front-end/37196

When running a model with a tuple of two tensors as an input the following fails:
```
    std::vector<torch::jit::IValue> inputs;
    std::vector<torch::jit::IValue> tuple;
    tuple.push_back(torch::zeros({5, 10}));
    tuple.push_back(torch::zeros({5, 10}));
    inputs.push_back(tuple);
terminate called after throwing an instance of 'c10::Error'
  what():  Type cannot be accurately recovered from this IValue. (incompleteInferTypeFrom at /pytorch/aten/src/ATen/core/type.cpp:149)
```

The fix is to call torch::jit::Tuple::create(tuple), but in general we might want to consider coercing IValues so that the above example would work.

cc @suo

**Comment by supitalp** [comment]
Hi,
I am also trying to run a model with a tuple of two tensors as an input. 
I tried using the code suggested above to build such a tuple: `torch::jit::Tuple::create(tuple)`,  however I get the following compilation error:

```
test_torchscript.cpp:85:34: error: ‘torch::jit::Tuple’ has not been declared
```

I am using libtorch 1.2.0, and it seems that the Tuple object has been removed there. Any idea how to fix this? Any help would be much appreciated.

**Comment by driazati** [comment]
This issue is still a problem, so the API isn't great and may change, but you can do this in v1.2.0:

```cpp
  std::vector<torch::IValue> elements{1, 2};
  auto type = torch::jit::TupleType::create(
      {torch::jit::IntType::get(), torch::jit::IntType::get()});
  auto t = torch::ivalue::Tuple::create(elements, type);
```

**Comment by supitalp** [comment]
Thank you, this works!

**Comment by ccqu** [comment]
> This issue is still a problem, so the API isn't great and may change, but you can do this in v1.2.0:
> 
> ```c++
>   std::vector<torch::IValue> elements{1, 2};
>   auto type = torch::jit::TupleType::create(
>       {torch::jit::IntType::get(), torch::jit::IntType::get()});
>   auto t = torch::ivalue::Tuple::create(elements, type);
> ```

Yes, in 1.3.0 I got:
`error: no matching function for call to 'c10::ivalue::Tuple::create(std::vector<c10::IValue, std::allocator<c10::IValue> >&, std::shared_ptr<c10::TupleType>&)'`

**Comment by akira-l** [comment]
any progress in this problem ???

**Comment by driazati** [comment]
You no longer need to specify the `type`, you can create the tuple directly. For example

```python
@torch.jit.script
def fn(x):
    # type: (Tuple[int, int]) -> int
    return x[0] + x[1]

fn.save('fn.pt')
```


```cpp
int main() {
  auto my_module = torch::jit::load("fn.pt");
  auto my_tuple = torch::ivalue::Tuple::create({3, 4});
  std::cout << my_module.forward({my_tuple}) << "\n";
  return 0;
}
```
