### ISSUE TITLE
index operation is not supported in torch.HalfTensor 

### ISSUE THREAD

**Issue by amrit110** [pytorch/pytorch#17161]
## 🚀 Feature
Currently, an indexing of torch.HalfTensor like half_tensor[indices] gives this runtime error.
RuntimeError: "index" not implemented for 'torch.HalfTensor'. So, requesting for an indexing method. 

## Motivation
It would be great to be able to index half tensors. My current use case for this is while doing large scale similarity metric computations on embeddings on the GPU where I figured I could use float16 to reduce memory usage.

## Pitch
Indexing method added to HalfTensor objects.

## Alternatives
For my use-case the alternative is to chunk up tensors appropriately to do similarity computations. While its works just as well, I can imagine other use cases where indexing on HalfTensor objects are needed.

**Comment by vishwakftw** [comment]
Can you give a script to reproduce the error, and the version of PyTorch that you are using?

**Comment by ezyang** [comment]
FTR, many indexing operations do work on half tensor:

```
>>> x = torch.empty(2,2,dtype=torch.half)
>>> x = torch.empty(2,2,dtype=torch.half)[0]
>>> torch.empty(2,2,dtype=torch.half)[0]
tensor([-1.2450e+02,  1.6546e-03], dtype=torch.float16)
>>> torch.empty(2,2,dtype=torch.half).cuda()[0]
tensor([-1.2450e+02,  1.6546e-03], device='cuda:0', dtype=torch.float16)
>>> torch.empty(2,2,dtype=torch.half)[(0,1)]
tensor(0.0017, dtype=torch.float16)
>>> torch.empty(2,2,dtype=torch.half)[1,:]
tensor([nan, 0.], dtype=torch.float16)
>>> torch.empty(2,2,dtype=torch.half)[:,1]
tensor([0.0017, 0.0000], dtype=torch.float16)
```

**Comment by amrit110** [comment]
```python
x = torch.empty(5, 5, dtype=torch.half)
y = x[[0, 4, 2]]
```
I get `RuntimeError: "index" not implemented for 'torch.HalfTensor`. `1.0.1.post2` was the version I'm running.
