### ISSUE TITLE
Can't import pytorch

### ISSUE THREAD

**Issue by stepseazy** [pytorch/pytorch#1717]
I am trying to import pytorch but I get an error that module does not exist. I installed via anaconda, and the folder "pytorch-0.1.12-py35_2cu80" exist in anaconda3/pkgs folder. why does it not recognize that it is there? should I rename this folder?

-Rik

**Comment by chenyuntc** [comment]
```
import torch
```

**Comment by stepseazy** [comment]
Oh thanks.
