### ISSUE TITLE
forward function can not insert pdb.trace

### ISSUE THREAD

**Issue by DanlanChen** [pytorch/pytorch#17172]
## To Reproduce

1. put `import pdb;pdb.set_trace()` in any `forward` function of your model which inherent from torch.jit.ScriptModule , you can not do `import ` inside the `forward function`, you can not do set_trace inside the `forward` function as well.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.0
 - OS (e.g., Linux):Linux
 - How you installed PyTorch (`conda`, `pip`, source):Source
 - Build command you used (if compiling from source):
 - Python version:3.6.5
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by jamesr66a** [comment]
Hi @DanlanChen,

We do not have deep integration of pdb into our runtime. To debug a ScriptModule, you can do a few things:

1) Remove the `@torch.jit.script_method` decorator from the method and debug the method as Python code
2) Create a free python function, pass in values you're interested to inspect into that function, and within the function call `pdb`. Example:

```
import torch

def debug_fn(a, b, c):
    print(a, b, c)
    import pdb; pdb.set_trace()

class FooMod(torch.jit.ScriptModule):
    @torch.jit.script_method
    def forward(self, x, y):
        z = x + y
        debug_fn(x, y, z)
        return z

fm = FooMod()
fm(torch.rand(3), torch.rand(3))
```

Hope this helps with your debugging!

**Comment by DanlanChen** [comment]
Thanks @jamesr66a
