### ISSUE TITLE
zip not allowed in forward function in torch.jit.ScriptModule

### ISSUE THREAD

**Issue by DanlanChen** [pytorch/pytorch#17179]
## To Reproduce

1.related to this issue: https://github.com/pytorch/pytorch/issues/16123
1.if I want to loop through two moduleList using zip got the error Get this error:RuntimeError:
unexpected expression in variable initialization of for loop:

> ```python
> i = 0
> for mod1, mod2 in zip(self.modules1, self.module2):
>   x = mod1(output[i])
>   x = mod2(x)
>   i += 1
```

<!-- If you have a code sample, error messages, stack traces, please provide it here as well -->

## Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.0
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

<!-- Add any other context about the problem here. -->


cc @suo

**Comment by DanlanChen** [comment]
any updates @facebook-github-bot

**Comment by eellison** [comment]
As a workaround, you can do the following:

```
mod_list = []
for mod1, mod2 in zip(module1, module2):
    mod_list.append(nn.Sequential(mod1, mod2))
self.module = nn.ModuleList(mod_list)
```

**Comment by DanlanChen** [comment]
@eellison thanks! If my previous `forward` is like below, how could i do the sequential one?
> ```python
>def forward(self, x):
> i = 0
> for mod1, mod2 in zip(self.modules1, self.module2):
>   x = mod1(x[:,-1,:])
>   x = mod2(x)
>   i += 1
```

**Comment by eellison** [comment]
The module code would be the same, and you would do 
```
for mod in self.module:
    x = mod(x[:, -1, :]
```

**Comment by DanlanChen** [comment]
@eellison sorry I did not give you a good example, the example should be look like this:
> ```python
>def forward(self, x):
> i = 0
> for mod1, mod2 in zip(self.modules1, self.module2):
>   x = mod1(x)
>   x = mod2(x[:,-1,:])
>   i += 1
```

**Comment by eellison** [comment]
You probably want to have the same ModuleList of sequentials, and then add a module between module1 and module2 that slices the tensor.
```

class Slice(nn.Module):
    def forward(self, input):
        return input[:, -1, :]

slice = Slice()

...
for mod1, mod2 in zip(module1, module2):
    mod_list.append(nn.Sequential(mod1, slice, mod2))
```

**Comment by suo** [comment]
@wanchaol, can we close this? You added `zip()` support right

**Comment by eellison** [comment]
It doesn't work on modules i think

**Comment by wanchaol** [comment]
> @wanchaol, can we close this? You added `zip()` support right

@suo yeah `zip` is supported but as elias said it does not works on modules, mainly because modules polymorphism and we inline them instead of being a separate class object

**Comment by eellison** [comment]
This is now supported! The limitation is that you can only zip with other ModuleLists, or over tuples (lists which are constants of the submodule work here too).

**Comment by volkov-maxim** [comment]
Hi!
How can I zip `ModuleList` and `List` of tensors?
