### ISSUE TITLE
[feature request] lerp with tensor weight

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#17207]
Implementation should be simple and efficient, considering that this is elementwise.

**Comment by fmassa** [comment]
Note that jitting a python implementation can probably be as efficient as a dedicated c++/cuda implementation

**Comment by vishwakftw** [comment]
Should weights be broadcastable in this case, or be the exact size as the inputs?

**Comment by vishwakftw** [comment]
I'll send in a PR if that's fine.

**Comment by soumith** [comment]
i'd start with non-broadcastable weights. go ahead and send a PR

**Comment by fmassa** [comment]
I believe that by using TensorIterator, handling broadcastable weights / a / b should be done automatically

**Comment by vishwakftw** [comment]
This has been merged with master.
