### ISSUE TITLE
from torch._C import * ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by tamimmirza** [pytorch/pytorch#17203]
## 🐛 Bug

I created a Python 3.7 environment inside Anaconda and I installed PyTorch conda package for CUDA 10 from the command presented at PyTorch official website for Windows 10. When I use `import torch` whether in VS Code or the command prompt I get:
```
from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
```

In uninstalled and reinstalled Anaconda3 2018.12 twice before reporting this error and have done sufficient research on the problem but they do not utilize the current stable release of PyTorch, the Anaconda version and the python version.

1. Download Anaconda3 64-bit for Windows 10 (2018.12)
2. Create a new Python 3.7 environment via Anaconda Navigator
3. Install PyTorch via the command `conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
` via the Terminal/CMD in the environment
4. Invoke Python
5. Run the command `import torch`

You should then see the stack trace as below. I have also detailed the packages that have been installed using the command

```
(PyTorch) C:\Users\Tamim Mirza>conda list
# packages in environment at C:\Anaconda3\envs\PyTorch:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2019.1.23                     0
certifi                   2018.11.29               py37_0
cffi                      1.11.5           py37h74b6da3_1
cudatoolkit               10.0.130                      0
freetype                  2.9.1                ha9979f8_1
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2019.1                      144
jpeg                      9b                   hb83a4c4_2
libpng                    1.6.36               h2a8f88b_0
libtiff                   4.0.10               hb898794_2
mkl                       2019.1                      144
mkl_fft                   1.0.10           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
ninja                     1.8.2            py37he980bc4_1
numpy                     1.15.4           py37h19fb1c0_0
numpy-base                1.15.4           py37hc3f5095_0
olefile                   0.46                     py37_0
openssl                   1.1.1a               he774522_0
pillow                    5.4.1            py37hdc69c19_0
pip                       19.0.1                   py37_0
pycparser                 2.19                     py37_0
python                    3.7.2                h8c8aaf0_2
pytorch                   1.0.1           py3.7_cuda100_cudnn7_1    pytorch
setuptools                40.7.3                   py37_0
six                       1.12.0                   py37_0
sqlite                    3.26.0               he774522_0
tk                        8.6.8                hfa6e2cd_0
torchvision               0.2.1                      py_2    pytorch
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wheel                     0.32.3                   py37_0
wincertstore              0.2                      py37_0
xz                        5.2.4                h2fa13f4_4
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

(PyTorch) C:\Users\Tamim Mirza>python
Python 3.7.2 (default, Feb 11 2019, 14:11:50) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\PyTorch\lib\site-packages\torch\__init__.py", line 84, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
>>>
```

## Expected behavior

There should be no import error as all required packages have been installed through the conda command provided by PyTorch

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0.1
 - OS (e.g., Linux): Microsoft Windows 10 Home (Version 10.0.17763.316) 64-bit
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7.2
 - CUDA/cuDNN version: 10.0.130/7.4.2 (installed via CUDA and cuDNN website)
 - GPU models and configuration: NVIDIA GeForce GTX 1050 (4 GB)
 - NVIDIA driver version: 418.91
 - Any other relevant information: I have a separate installation of CUDA Toolkit 10.0 which has been added to my path library along with the installation of Anaconda. But this is for the use of TensorFlow which utilizes CUDA and it has not interfered in any projects using PyTorch.

![untitled](https://user-images.githubusercontent.com/35456031/52902640-848d0280-3235-11e9-8237-f7efc09d7327.png)

![untitled1](https://user-images.githubusercontent.com/35456031/52902686-03823b00-3236-11e9-8abd-05615fd6a7dd.png)

## Additional context

When writing ` import torch` on a text editor such as VS Code then it detects the presence of torch and all of its sub-libraries/functions but the error occurs when compiling it. I have reinstalled PyTorch (from the above conda command) in a new seperate environment and Anaconda twice while the problem still endures.

**Comment by Chiragrankja456** [comment]
I am facing the same problem, tried reinstalling the Anaconda four time
Below is the environment details I got by running the script

```
> PyTorch version: N/A
> Is debug build: N/A
> CUDA used to build PyTorch: N/A
> 
> OS: Microsoft Windows 10 Home Single Language
> GCC version: (x86_64-posix-seh, Built by MinGW-W64 project) 4.9.3
> CMake version: version 3.13.0-rc1
> 
> Python version: 3.6
> Is CUDA available: N/A
> CUDA runtime version: Could not collect
> GPU models and configuration: Could not collect
> Nvidia driver version: Could not collect
> cuDNN version: Could not collect
> 
> Versions of relevant libraries:
> [pip] numpy==1.15.4
> [pip] numpydoc==0.8.0
> [pip] torch==1.0.1
> [pip] torchvision==0.2.1
> [conda] blas                      1.0                         mkl  
> [conda] mkl                       2019.1                      144  
> [conda] mkl_fft                   1.0.10           py36h14836fe_0  
> [conda] mkl_random                1.0.2            py36h343c172_0  
> [conda] pytorch-cpu               1.0.1             py3.6.7_cpu_1    pytorch
> [conda] torchvision-cpu           0.2.1                      py_2    pytorch
```

**Comment by harlecin** [comment]
Same issue here :(

I already had pytorch 1.0 GPU version installed and working two months ago using `conda`. 

I recently added another user to my computer and I cannot get `pytorch` to run for the new user :(

I tried installing pytorch for cpu only and that would not work either.

Any help greatly appreciated:)

Here is the output from your script:
```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] numpydoc==0.8.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl-service               1.1.2            py37hb782905_5
[conda] mkl_fft                   1.0.6            py37h6288b17_0
[conda] mkl_random                1.0.2            py37h343c172_0
```

**Comment by peterjc123** [comment]
please downgrade your python to 3.7.1

**Comment by Chiragrankja456** [comment]
I have edited the __init__.py file using the below link

[Fix dll loading process in newer Python on Windows](https://github.com/pytorch/pytorch/pull/17191/files)

It worked !

**Comment by Chiragrankja456** [comment]
> I have edited the **init**.py file using the below link
> 
> [Fix dll loading process in newer Python on Windows](https://github.com/pytorch/pytorch/pull/17191/files)
> 
> It worked !

I am using below config,

```
> PyTorch version: 1.0.1
> Is debug build: No
> CUDA used to build PyTorch: None
> 
> OS: Could not collect
> GCC version: Could not collect
> CMake version: Could not collect
> 
> Python version: 3.6
> Is CUDA available: No
> CUDA runtime version: No CUDA
> GPU models and configuration: No CUDA
> Nvidia driver version: No CUDA
> cuDNN version: No CUDA
```

**Comment by tamimmirza** [comment]
> please downgrade your python to 3.7.1(or 3.6.7)

Downgrading to Python 3.7.1 from 3.7.2 worked. Thanks

Though why is this error only appearing in 3.7.2, it has been out for quite some time now

**Comment by qiangd6** [comment]
> please downgrade your python to 3.7.1(or 3.6.7)

Works for me! 

I had the same problem while using pytorch with miniconda/win10 64 bit.

**Comment by peterjc123** [comment]
@tamimmirza https://github.com/pytorch/pytorch/issues/17051 Here is the issue with the detailed description.

**Comment by tamimmirza** [comment]
> @tamimmirza #17051 Here is the issue with the detailed description and we are now working on merging the patch @Chiragrankja456 mentioned into the 1.0.1 release and re-generating the binaries.

How soon would the patch be implemented into the official build and if possible the previous stable version (1.0) could be used instead?

**Comment by peterjc123** [comment]
@tamimmirza 

> How soon would the patch be implemented into the official build

You won't wait for too long. I guess it will be done in 1~3 days. 

> if possible the previous stable version (1.0) could be used instead?

I don't get what you mean. Do you mean will the patch go to 1.0.0 too? In this way, I'll say no because 1.0.1 is already a small-patched version for 1.0.0.

**Comment by peterjc123** [comment]
@soumith Please remember to close this issue when you update these binaries for 1.0.1.

**Comment by soumith** [comment]
the new packages for v1.0.1 with peterjc123's patches are now uploaded.
Uninstall pytorch, clear your cache (wheel or conda) and install it again, and you should get the new package that fixes the issue.

**Comment by Exlsunshine** [comment]
For those who face the same problem, if you plan to run python in cpu, please make sure you install the cpu version of pytorch instead of cuda version.

**Comment by caifazhou** [comment]
conda upgrade the python from 3.6 to 3.6.8 works for me.
It seems that a new version of VC package is installed. This might be the relevant point.

**Comment by lfsando** [comment]
I'm having the same issue.
Python 3.7.2 and CUDA 10.0

**Comment by fahruz** [comment]
I have the same issue. Downgrading to Python 3.7.1 didn't work.

**Comment by a5tr1** [comment]
I am having the same issues

I am using virtualenv to install pytorch with CUDA 9.0 and using pip install
install torch 1.1.0

tried
1. change my python to 3.6.7 (before python 3.6.2)
2. install vc_redist
3. install open-mp and add in path
4. install mkl

and no luck, anyone can help?

**Comment by WEIFZH** [comment]
the same issue today
i've tried python 3.6.x and 3.7.1, didn't work.

**Comment by a5tr1** [comment]
> I am having the same issues
> 
> I am using virtualenv to install pytorch with CUDA 9.0 and using pip install
> install torch 1.1.0
> 
> tried
> 
> 1. change my python to 3.6.7 (before python 3.6.2)
> 2. install vc_redist
> 3. install open-mp and add in path
> 4. install mkl
> 
> and no luck, anyone can help?

I succeded with re installing the version as written in this link [https://stackoverflow.com/questions/49395819/import-torch-giving-error-from-torch-c-import-dll-load-failed-the-specif](url) 
look for the end of comment it works for me. 

Looks like torch in windows are very sensitive with the version compatible each package
Package      Version
------------ -----------
intel-openmp 2019.0
mkl          2019.0
numpy        1.16.2
Pillow       6.0.0
pip          19.0.3
setuptools   41.0.0
six          1.12.0
torch        1.0.0
torchvision  0.2.2.post3
wheel        0.33.1

**Comment by a5tr1** [comment]
> the same issue today
> i've tried python 3.6.x and 3.7.1, didn't work.

please try my latest comment, maybe it will works for you

**Comment by Questdream** [comment]
> the same issue today
> i've tried python 3.6.x and 3.7.1, didn't work.

first, install python3.6.7.(other version such as 3.6.0 and 3.6.8 didn't work)
and then ,` pip install --upgrade numpy  and pip install intel-openmp` 
it works for me

**Comment by weilanhanf** [comment]
> > the same issue today
> > i've tried python 3.6.x and 3.7.1, didn't work.
> 
> first, install python3.6.7.(other version such as 3.6.0 and 3.6.8 didn't work)
> and then ,` pip install --upgrade numpy and pip install intel-openmp`
> it works for me

Thank you！ Issue solved successfully.
