### ISSUE TITLE
Error when trying to flip tensor on last dimension

### ISSUE THREAD

**Issue by MetaDev** [pytorch/pytorch#17204]
## 🐛 Bug

The flip method of a tensor does not allow to flip the last dimension through the index -1.

the output:
RuntimeError: expected flip dims axis >= 0, but got min flip dims=-1

## To Reproduce

torch.zeros([2,3,3]).flip(-1)

## Expected behavior

The method could accept -1 as the index for the last axis
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by vishwakftw** [comment]
Could you please fill out the environment details? Or at least specify the version of PyTorch you are using.

**Comment by vishwakftw** [comment]
For the record, with `torch.__version__ == 1.0.0.dev20190125`, negative flip dims work.

**Comment by MetaDev** [comment]
Apologies, it was an outdated pytorch version
