### ISSUE TITLE
[doc] tensor.lerp doc doesn't make sense

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#17205]
## 📚 Documentation

`torch.lerp` takes in `start` and `end`, but so does `tensor.lerp`? Shouldn't the `tensor` be used as `start` (or `end`)? And the doc should be clear which one it is.

<img width="919" alt="screenshot 2019-02-16 16 51 42" src="https://user-images.githubusercontent.com/5674597/52905660-3a8f2700-320b-11e9-914f-ba4246e07548.png">

**Comment by krishnakalyan3** [comment]
I can make this change. According to below it should be `end`.

![image](https://user-images.githubusercontent.com/4648995/52974784-1ece8100-33c3-11e9-8558-a470338aab17.png)
![image](https://user-images.githubusercontent.com/4648995/52974791-22fa9e80-33c3-11e9-8eec-8350ac1542a3.png)

**Comment by zou3519** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/17253
