### ISSUE TITLE
pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:131: NVRTC_ERROR unknown

### ISSUE THREAD

**Issue by Edwardf0t1** [pytorch/pytorch#17211]
## 🐛 Bug

 

When using the trained model(pt) produced by traced_script_module.save("model.pt"), the compiler can successfully build the model. But when using it for inference, there is an error generated in the  
torch/csrc/jit/fuser/cuda/fused_kernel.cpp#

The error message is illustrated as follows:

Cuda: 1 Cudnn: 1 Devices: 1
load model successfully!
terminate called after throwing an instance of 'std::runtime_error'
  what():  /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:131: NVRTC_ERROR unknown
Aborted (core dumped)

## Environment

The C compiler identification is GNU 5.4.0
The CXX compiler identification is GNU 5.4.0
Ubuntu 16.04
Pytorch 1.0.0
cuda 10.0
cudnn:7.3.1
Python 3.5

**Comment by soumith** [comment]
could you please try our nightly binaries (go to pytorch.org and select the "Preview" instead of "Stable" in the version selector) and see if the issue reproduces?

**Comment by suo** [comment]
Going to close this as we don't have enough reproduction information to investigate. Feel free to reopen as you see fit!

**Comment by 1171257311** [comment]
hello,have you solved this problem?
