### ISSUE TITLE
2.7m -> 2.7 in BUILD_ENVIRONMENT for smoke_macos_libtorch_2.7_cpu CircleCI job specification

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#17223]
Found this discrepancy while autogenerating the `config.yml` file (#17038).

Was apparently introduced [here](https://github.com/pytorch/pytorch/pull/16511/files#diff-1d37e48f9ceff6d8030570cd36286a61R2925).

**Comment by fmassa** [comment]
cc @soumith
