### ISSUE TITLE
Does pytorch has a tool showing that a model's input&output's summary? just

### ISSUE THREAD

**Issue by fwz-fpga** [pytorch/pytorch#17227]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by fwz-fpga** [comment]
Just like tensorflow's tool saved_model_cli. 
When I get a pytorch model saved_from torch.save() or torch.jit.save(), I want to konw its'input. Just like input's name,shape,dtype.

Dose anyone knows?
Thanks.

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
