### ISSUE TITLE
testing.assert_allclose should assert tensors have the same devices

### ISSUE THREAD

**Issue by SimLeek** [pytorch/pytorch#17231]
## 🐛 Bug

This unit test should pass:

        ind = tor.LongTensor([110, 125, 235, 333, 404]).cuda()
        nd_shape = tor.LongTensor([10, 10, 10]).cuda()
        xy = array_to_nd_index(ind, nd_shape)
        result = [[1, 1, 0],
                  [1, 2, 5],
                  [2, 3, 5],
                  [3, 3, 3],
                  [4, 0, 4]]
        tortest.assert_allclose(result, xy)

However, I get:

        RuntimeError: expected type torch.LongTensor but got torch.cuda.LongTensor

Here's the solution I wrote in my own assert function, though it may be a bit permissive:

        if a.is_cuda and not b.is_cuda:
            b = b.cuda()
        elif b.is_cuda and not a.is_cuda:
            a = a.cuda()

## Environment

 - PyTorch Version (e.g., 1.0):    1.0.1
 - OS (e.g., Linux):    Windows
 - How you installed PyTorch (`conda`, `pip`, source):    pip
 - Python version:    3.6
 - CUDA/cuDNN version:    0.9

**Comment by ezyang** [comment]
On it's face, this seems like a reasonable UX improvement, but there are some problems.

1. Should we convert to CPU, or convert to CUDA? There are merits in both directions. Conversion to CUDA (as you suggested) will lead to a faster allclose computation but we have to ship the result back to CPU to actually report if it worked or not. Conversion to CPU saves on CUDA space.
2. We're going to soon have other device types besides CUDA running around. What should happen in those cases?

We don't really have any precedent for this case, so it's hard to say what to do.

**Comment by apaszke** [comment]
We should never change the device, right? We can simply check that the device of all arguments matches, and use this for all returns as well. That solves the multi-device case too.

**Comment by SimLeek** [comment]
Asserting the devices match might be a good idea too. It's a little clear for that already, but it could be clearer.

If it was automatically put in a device, I'd prefer the device with the most memory, since it wouldn't have a memory error. So, I think,  server>cpu>gpu.

**Comment by ezyang** [comment]
@SimLeek Yeah, why don't we assert the devices match. Do you want to submit the PR for this?

**Comment by SimLeek** [comment]
Yeah. Sorry it took so long. I'll be submitting a PR soon.

**Comment by mruberry** [comment]
I've updated the title of this issue and its labels. We would accept a PR implementing this, although I expect the design of torch.testing may change in the near future.

**Comment by mruberry** [comment]
Closing this issue because it has been mooted with the addition of testing.assert_close(). See its documentation https://pytorch.org/docs/master/testing.html?highlight=assert_close#torch.testing.assert_close, which supports comparing devices.
