### ISSUE TITLE
Windows pytorch CUDA 10 error

### ISSUE THREAD

**Issue by pratik-r** [pytorch/pytorch#17233]
## 🐛 Bug

I'm running pytorch on Windows 10 with cudatoolkit version 10. I have Nvidia CUDA 10 toolkit and the latest display driver installed. When I do:

>>> import torch
>>> torch.cuda.is_available()

it returns False and gives me the following error:

python.exe - Entry Point Not Found
The procedure entry point fatBinaryCtl_createHandle could not be located in the dynamic link library C:\WINDOWS\system32\nvcuda.dll

I initially thought this was a problem with CUDA or the display driver. I reinstalled everything and tried again, only to get the same error. On the other hand, I'm able to run CUDA enabled models on catboost and numba without any problems, so it's probably an issue with pytorch. Any idea what's wrong here?

Thanks.

**Comment by pratik-r** [comment]
FWIW, I fixed this by reinstalling torch on a fresh installation of miniconda3 (the one available on their website right now). However, when I do conda update --all, the problem comes back. This means the problem has to do with installing the most recent version of one of these packages: cryptography, pyopenssl, python, setuptools. I've managed to get around this for now by installing torch on a clean new environment.

**Comment by gmseabra** [comment]
I confirm that using the packages that come with Miniconda (no updating) seem to correct this. However, I then fall into the issue described at: https://github.com/pytorch/pytorch/issues/17108#issuecomment-463901596.

Either way, PyTorch for Windows doesn't seem to be working correctly.

**Comment by fahruz** [comment]
I have exactly the same issue with Anaconda/conda (environment: Win10, GTX 1080, CUDA 10). Please fix.

**Comment by peterjc123** [comment]
@pratik-r Well, this may be a dll loading problem. The problem may be on the latest python package. So would you please try downgrading python to 3.6.7 or 3.7.1?

**Comment by pratik-r** [comment]
@peterjc123 I can confirm that it works fine with python 3.7.1 (and presumably earlier versions), but not with 3.7.2.

**Comment by peterjc123** [comment]
@pratik-r Well, then that's the problem. Unluckily, they (the Anaconda team) are using `AddDllDirectory` in their PRs so the sequence is not ensured. Would you please open an issue at https://github.com/ContinuumIO/anaconda-issues/issues?

**Comment by mingwandroid** [comment]
@peterjc123, would it be possible for you to explain what you mean by "the sequence is not ensured".

**Comment by wenjunsun** [comment]
I can also confirm that python 3.7.1 works and python 3.7.2 does not. Try downgrading the python version to 3.7.1 and it should work.

**Comment by peterjc123** [comment]
@mingwandroid We have `nvfatbinaryloader.dll` and `nvcuda.dll` shipped in the binaries. We used to have these dlls in `C:\Windows\System32` loaded first, but in 3.7.2, they seem to use the DLLs in the binaries first, which is not what we expected. They are included just to help users to use our package without having the CUDA package installed.

**Comment by xiaocc612** [comment]
I'm running pytorch on Windows 10 with cudatoolkit version cuda_10.1.105_418.96_win10. I have Nvidia CUDA 10 toolkit and the latest display driver installed. When I do:

import torch
torch.cuda.is_available()

And it returns no error.How to solve this?

**Comment by peterjc123** [comment]
@xiaocc What do mean by saying "it returns no error"?

**Comment by soufianesabiri** [comment]
I have this error when I import OpenALPR but what it the relation between Tensorflow GPU and OpenALPR ??

**Comment by traveller59** [comment]
same error in python 3.7.2, works in python 3.6.
