### ISSUE TITLE
Misleading statement regarding state_dict, 'it holds only layers with learnable params'

### ISSUE THREAD

**Issue by KushajveerSingh** [pytorch/pytorch#17230]
In the documentation [link](https://pytorch.org/tutorials/beginner/saving_loading_models.html#what-is-a-state-dict), it is said
> Note that only layers with learnable parameters (convolutional layers, linear layers, etc.) have entries in the model’s state_dict.

Consider the below code
```
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 3, 1, 1)
        self.bn1 = nn.BatchNorm2d(6)
        self.register_buffer('buf1', torch.randn(1))
        
    def forward(self, x):
        x = self.bn1(self.conv1(x))
        return x

model = MyModel()
print(model.state_dict()['buf1'])
```
As you can see buf1 is also in the state_dict.

The docs should be changed to
> Layers with learnable parameters (convolutional layers, linear layers, etc.) have entries in the model’s state_dict along with register buffers.

The dicussion for this issue was done on pytorch forums. [link](https://discuss.pytorch.org/t/difference-between-state-dict-and-parameters/37531)

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/tutorials/commit/7371fea6558a20953b72810388430fd4ffa7fffc
