### ISSUE TITLE
How can I read the .pt file(which save by python script) in C++ by torch::load from libtorch?

### ISSUE THREAD

**Issue by bill4278** [pytorch/pytorch#17248]
## ❓ Questions and Help
How can I read the .pt file(which save by python script) in C++ by torch::load from libtorch?

At first, I have trained a model in python, and have already saved the weight file in .pt format.
So is it possible I read this .pt file in C++ using libtorch with torch::load?

Thanks

**Comment by soumith** [comment]
follow our tutorials, ask questions on https://discuss.pytorch.org

**Comment by bill4278** [comment]
![image](https://user-images.githubusercontent.com/32795143/53076372-7cc9a880-352a-11e9-8479-b5efeb36254d.png)
