### ISSUE TITLE
Broken in-line code in documentation

### ISSUE THREAD

**Issue by seungwonpark** [pytorch/pytorch#17243]
## 🐛 Bug

Description of `torch.distributed.broadcast_multigpu` have broken in-line code, but I can't figure out a way to resolve it.
Possibly a markdown-related issue with Sphinx?

Code: https://github.com/pytorch/pytorch/blob/master/torch/distributed/distributed_c10d.py#L668-L669

Doc. link with problem: https://pytorch.org/docs/stable/distributed.html#torch.distributed.broadcast_multigpu

![image](https://user-images.githubusercontent.com/13394294/52993393-60107080-3457-11e9-917f-ab07f53ac021.png)

**Comment by soumith** [comment]
cc: @brianjo would you mind taking this?

**Comment by brianjo** [comment]
Looking.
