### ISSUE TITLE
 _C._initExtension(manager_path()) RuntimeError: torch.FloatTensor is not enabled.

### ISSUE THREAD

**Issue by my-hello-world** [pytorch/pytorch#17250]
## ❓ Questions and Help
Regardless of whether I installed python3.5\3.6\3.7, pytorch-nightly1.0 or Stable, I get the following error.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vivian/anaconda3/envs/mask_keypoint36/lib/python3.6/site-packages/torch/__init__.py", line 250, in <module>
    _C._initExtension(manager_path())
RuntimeError: torch.FloatTensor is not enabled.

**Comment by soumith** [comment]
I suspect an old install of PyTorch interfering somehow.
Please either provide a way to reproduce (maybe a docker image), or clean all old installs of PyTorch -- you can also try  a fresh environment of PyTorch or anaconda.
