### ISSUE TITLE
GPU Version Nightly Build?

### ISSUE THREAD

**Issue by soulslicer** [pytorch/pytorch#17254]
## 🚀 Feature

Currently, the C++ Pytorch API includes a CPU version of the nightly build. 

https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip

But there is no GPU version

## Motivation

Makes this much easier without having to compile the latest code

**Comment by soumith** [comment]
![screen shot 2019-02-19 at 5 51 33 pm](https://user-images.githubusercontent.com/1310570/53053328-04ea7800-346f-11e9-919b-11b4564a4484.png)
