### ISSUE TITLE
NO_DISTRIBUTED environment variable documentation needs to be updated

### ISSUE THREAD

**Issue by mateuskahler** [pytorch/pytorch#17265]
Since commit https://github.com/pytorch/pytorch/commit/dc186cc9fec7777b1400b09f8bccc6fa507e151e , the variable `NO_DISTRIBUTED` is still referenced in `setup.py`, despite the standardization by the use of `USE_DISTRIBUTED`:
https://github.com/pytorch/pytorch/blob/444039c47bb997f698c2bd9481c8649188038c51/setup.py#L51

A `grep -rli NO_DISTRIBUTED` in root folder show no mention of `NO_DISTRIBUTED` anywhere in the code except in `setup.py` comments.

`tools/setup_helpers/dist_check.py`, line 9, now checks for `USE_DISTRIBUTED`:

https://github.com/pytorch/pytorch/blob/444039c47bb997f698c2bd9481c8649188038c51/tools/setup_helpers/dist_check.py#L9

I suggest changing the setup.py comment on lines 51:52 to:
```
#   USE_DISTRIBUTED
#     enables distributed (c10d, gloo, mpi, etc.) build
```

Or changing line 9 of `(...)/dist_check.py` to:
```
USE_DISTRIBUTED = not check_env_flag("NO_DISTRIBUTED") and not IS_WINDOWS and not check_env_flag("USE_ROCM")
```

**Comment by t-vi** [comment]
I think we standardize on USE_... now, so the first variant would be it. Maybe I'll tack this onto #17295.

**Comment by soumith** [comment]
I just checked, `NO_DISTRIBUTED=1` still works fine, and as intended.
The only thing needed to resolve this issue is to update the documentation in setup.py, I'll send a PR to fix that.

**Comment by mateuskahler** [comment]
Thanks, @soumith .
> I just checked, `NO_DISTRIBUTED=1` still works fine, and as intended.

`NO_DISTRIBUTED=1` is translated to `USE_DISTRIBUTED=0` in `hotpatch_build_env_vars()` from `tools/setup_helpers/env.py` . My mistake saying it was ignored.
