### ISSUE TITLE
torch.exp on CPU is incorrect for tensors with more than 2^31 or more elements

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#17271]
Reported by Ben Graham

```python
import torch
print(torch.__version__) #1.0.0.dev20190207
a=torch.ones(2**31,dtype=torch.float32)
print(a)             #tensor([1., 1., 1.,  ..., 1., 1., 1.])
print(torch.sign(a)) #tensor([1., 1., 1.,  ..., 1., 1., 1.])
print(torch.exp(a))  #tensor([0., 0., 0.,  ..., 0., 0., 0.])  THIS IS WRONG
```

stderr shows

```
Intel MKL ERROR: Parameter 1 was incorrect on entry to vsExp.
```

The other operations implemented by MKL's VML (sin, cos, etc.) are likely to be broken as well.

https://github.com/pytorch/pytorch/blob/0fc03d155a91cbca2c9e23d23463f69fd254c0a3/aten/src/ATen/cpu/vml.h#L140-L158

**Comment by gchanan** [comment]
@cpuhrsch can you take a look?

**Comment by cpuhrsch** [comment]
This is due to the fact that we link against MKL LP64 and not MKL ILP64. As such the MKL VML calls only accept 32bit types. I'll write something that will call into VML repeatedly if this is the case.

**Comment by cpuhrsch** [comment]
https://github.com/pytorch/pytorch/pull/17280

**Comment by ezyang** [comment]
Linked PR was merged.
