### ISSUE TITLE
building pytorch 1 without nccl2

### ISSUE THREAD

**Issue by zeneofa** [pytorch/pytorch#17274]
Hi,

I work on two systems that have a glibc 2.11 and 2.12, respectively, it is therefore incompatible with nccl2 which requires 2.19 or greater. Is there a way to install pytorch without nccl2? I have asked something similar on the forums: https://discuss.pytorch.org/t/the-problem-of-installing-pytorch-on-tx2/28762/2?u=zeneofa 

I have tried to build it using: `USE_NCCL=OFF python setup.py install`, also trying `USE_NCCL=0` and `USE_NCCL=False`, neither of which worked. On these systems I do not have sudo, and I am using a locally installed anaconda environment. Any help would be greatly appreciated, thanks in advance.

**Comment by t-vi** [comment]
This is essentially #15698 .
It's particularly grave due to #14486 - which seems to affect PyTorch, too (?).
