### ISSUE TITLE
CircleCI panel shows 48,600+ lines of expanded YAML configuration above build output

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#17273]
For example, see this page: https://circleci.com/gh/pytorch/pytorch/812808?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The browser becomes sluggish when interacting with that page.
Moving some of the inline shell scripts to their own files (#17028) could help.

**Comment by zou3519** [comment]
+1 for moving the inline shell scripts to their own file. Config.yml is getting pretty long

**Comment by kostmo** [comment]
This is also important to fix because when using the CircleCI API to list recently completed builds, the JSON response includes the full, expanded text of the `config.yml` file for each build entry.  This turns what should be just a few kilobyte-sized query response into dozens of megabytes.

CC @pjh5 @ezyang @yf225

**Comment by pjh5** [comment]
I don't think I understand what you're referring to. What do you mean by "expanded YAML configurations" and "build output"?

**Comment by kostmo** [comment]
If one clicks on the "Configuration" tab on [this page](https://circleci.com/gh/pytorch/pytorch/812808#tests/containers/0), a large number of lines will be shown:
<img width="922" alt="Screen Shot 2019-04-09 at 11 14 06 AM" src="https://user-images.githubusercontent.com/261693/55824987-e2153100-5ab9-11e9-88e7-c1fbd18499be.png">

This is the "expanded" form of the `config.yml` file.  One may locally preview the expanded form as [described on this page](https://circleci.com/docs/2.0/reusing-config/#getting-started-with-config-reuse):

    kostmo@ubuntu:~/github/pytorch-repos/pytorch$ cat .circleci/config.yml | wc -l
    3698
    kostmo@ubuntu:~/github/pytorch-repos/pytorch$ circleci config process .circleci/config.yml | wc -l
    62518

This large expansion makes parts of the CircleCI UI cumbersome.  Regarding my recent comment about the API, however, they have provided an [undocumented](https://circleci.com/docs/api/#api-overview) query parameter as a workaround: `shallow=true` suppresses the expanded `config.yml` content that normally appears in [this API endpoint](https://circleci.com/docs/api/#recent-builds-for-a-single-project)'s response.

**Comment by kostmo** [comment]
Some progress was made toward this end in #18888, in which few scripts were extracted from inline `config.yml` to their own files.  However, in that same PR, dozens of new configurations were added.
In the end, the file was reduced from `62,882` to `58,716` lines with all the new configs.

FYI @pjh5, @yf225 and @marcomorain.

**Comment by pjh5** [comment]
https://github.com/pytorch/pytorch/pull/19674 could substantially reduce the config size further

**Comment by marcomorain** [comment]
Thanks for pinging me on this @kostmo

**Comment by ezyang** [comment]
We landed the reduction, this is fixed now.
