### ISSUE TITLE
The 'defined_if' field in PyTorch's cwrap declaration couples the declarations to TH(C) library implementation details

### ISSUE THREAD

**Issue by killeent** [pytorch/pytorch#1728]
@zdevito and I are working on re-using the PyTorch cwrap declarations in the Tensor Lib. Strings such as:

```
defined_if: defined(TH_REAL_IS_FLOAT) || defined(TH_REAL_IS_DOUBLE) || CUDA_FLOAT || CUDA_HALF || CUDA_DOUBLE
```

in the cwrap are necessary because of the way PyTorch generates code via macros/includes. However, this is an implementation detail. Really, what the code is saying is that the method should be supported for all floating point types across CPU/GPU.

This issue will track a conversion to cwrap declarations that separate which types/devices (and eventually distributed, sparse) support which methods.

- [x] Add additional declaration fields for 'type', 'device', etc. that mimic the defined_if field, for use in the TensorLib
- [x] Modify the plugin engine to translate these fields to the same defined_if strings, and remove the defined_if code for types and devices
- [ ] Extend to sparse, distributed

**Comment by killeent** [comment]
This can be assigned to me.

**Comment by albanD** [comment]
This is no longer in the code base.
