### ISSUE TITLE
Maximum value of torch.rand

### ISSUE THREAD

**Issue by sh0416** [pytorch/pytorch#17289]
## 🐛 Bug

torch.rand contain 1. In doc, torch.rand() sample number from [0, 1).
To my knowledge, that means 1 is excluded in the generated number.

## To Reproduce

```
import torch

x = torch.rand((100, 100, 100))
print(x.max())
```

## Expected behavior

No matter how when calling this API, the maximum value of torch.rand must be 0.9999.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
 - Python version: 3.6
 - CUDA/cuDNN version: default
 - GPU models and configuration: NVIDIA Titan Xp
 - Any other relevant information:

**Comment by sh0416** [comment]
My mistake, It's about print option.

**Comment by vsub21** [comment]
@sh0416 I came across your post when trying to find the absolute max of torch.rand(). Is it verified that the max value of torch.rand() will indeed be 0.9999 (with the specified precision)? I am trying to sample uniformly from (0, 1) instead of [0, 1) -- to rectify this I am considering adding 1e-5 to the result in order to avoid issues with 0 values. Any thoughts?

**Comment by sh0416** [comment]
@vsub21 Not good. What about resample when sampled value is zero?

**Comment by vsub21** [comment]
@sh0416 you're right, that would work well. 

I also found [self.uniform_()](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.uniform_) that might be useful; do you think this would work well too?

`rand_unif = torch.empty(logit_probs.size()).uniform_(1e-5,1. - 1e-5)`

**Comment by sh0416** [comment]
It will work if you use low precision.

PyTorch supports very high precision like 1e-15 or more.

That’s why I confused.

For very precisely, I recommend you to use my method. It’s simple and fast in terms of probablistic points :)

If you don’t mind about sampling 0.0000001, then use your method.

In my experience, sometimes very small value is important.

But it is your choice. :)

**Comment by vsub21** [comment]
@sh0416 Thank you for your help!
