### ISSUE TITLE
issues with converting to torch script via tracing

### ISSUE THREAD

**Issue by lianxxx** [pytorch/pytorch#17292]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
    num_classes = len(labelmap) + 1                      # +1 for background
    net = build_ssd('test', 300, num_classes)            # initialize SSD
    net.load_state_dict(torch.load(args.trained_model))
    net.eval()
    print('Finished loading model!')
    
    example = torch.rand(1, 3, 300, 300)
    traced_script_module = torch.jit.trace(net, example)
    traced_script_module.save("ssd300_129.pt") 

But, 

  File "F:\pytorch\ssd.pytorch\ssd.py", line 104, in forward
    self.priors.type(type(x.data))                  # default boxes
RuntimeError: Attempted to trace Detect, but tracing of legacy functions is not supported

**Comment by soumith** [comment]
It's what the error message says.

**Comment by Tacode** [comment]
I have same problem
