### ISSUE TITLE
CUDA error: illegal instruction at adam.py

### ISSUE THREAD

**Issue by thnkim** [pytorch/pytorch#17301]
## 🐛 Bug

I got the error as follows:
~/anaconda3/lib/python3.7/site-packages/torch/optim/adam.py in step(self, closure)
     91 
     92                 # Decay the first and second moment running average coefficient
---> 93                 exp_avg.mul_(beta1).add_(1 - beta1, grad)
     94                 exp_avg_sq.mul_(beta2).addcmul_(1 - beta2, grad, grad)
     95                 if amsgrad:

RuntimeError: CUDA error: an illegal instruction was encountered

## To Reproduce

Not clearly reproducible. It randomly happens.
I'm using commit 4f45bc73f7d622366c429a4e620cd9c4f9551e9b (source built). 
My adam optimizer is:
    ```torch.optim.Adam(net.parameters(), lr=0.00001, betas=(0.5, 0.49), weight_decay=1e-4)```

## Environment

PyTorch version: 1.1.0a0+4f45bc7
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 410.48
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/lib64/libcudnn.so.7.4.2
/usr/local/cuda-10.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     1.1.0a0+4f45bc7          pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi

**Comment by thnkim** [comment]
It seems that my 2080Ti is dead suddenly. I tried other computation tests, it always fails. I think I should drop it into trash-bin.

**Comment by KimalIsaev** [comment]
Hi, @thnkim 
Please, tell what computation tests did you used?  I suspect my 1080Ti failing, but i want to be sure.
