### ISSUE TITLE
subprocess.CalledProcessError: Command '['make', '-j', '12', 'install']' returned non-zero exit status 2

### ISSUE THREAD

**Issue by yyf8989** [pytorch/pytorch#17326]
File "/home/yyf/pytorch/tools/build_pytorch_libs.py", line 252, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '12', 'install']' returned non-zero exit status 2

**Comment by yyf8989** [comment]
here is the output problems:
In file included from /home/yyf/pytorch/torch/csrc/distributed/c10d/ddp.cpp:6:0:
/home/yyf/pytorch/torch/csrc/cuda/nccl.h:8:18: fatal error: nccl.h: 没有那个文件或目录
 #include <nccl.h>
                  ^
compilation terminated.
caffe2/torch/CMakeFiles/torch_python.dir/build.make:1108: recipe for target 'caffe2/torch/CMakeFiles/torch_python.dir/csrc/distributed/c10d/ddp.cpp.o' failed
make[2]: *** [caffe2/torch/CMakeFiles/torch_python.dir/csrc/distributed/c10d/ddp.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
CMakeFiles/Makefile2:9243: recipe for target 'caffe2/torch/CMakeFiles/torch_python.dir/all' failed
make[1]: *** [caffe2/torch/CMakeFiles/torch_python.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 734, in <module>
    build_deps()
  File "setup.py", line 281, in build_deps
    build_dir='build')
  File "/home/yyf/pytorch/tools/build_pytorch_libs.py", line 252, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '12', 'install']' returned non-zero exit status 2

**Comment by soumith** [comment]
follow issue template and reopen new issue

**Comment by tonmoyborah** [comment]
Same issue when I try to build caffe2 . It happens when I run `python pytorch/setup.py install`

**Comment by vaibhav0195** [comment]
Hi , I solved it by using the build from v1.0.0

**Comment by hufengshuo07** [comment]
@vaibhav0195 Excuse me, where can i get v1.0.0?

**Comment by vaibhav0195** [comment]
you can find it using git tags
and then doing git checkout v1.0.0

**Comment by 2name** [comment]
@yyf8989 I meet the same error,have you solved it?

**Comment by yyf8989** [comment]
> @yyf8989 I meet the same error,have you solved it?

sorry , I didn't remember how to solve it(this was an ignored  problem of many problems when i tried to build caffe from source)， but i think it may be a torch version problem, i finally use caffe installed with the torch nightly version of website of caffe2.
if you are compiling caffe,   I advise you [use nightly version from conda env](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=prebuilt)(link to caffe2 website)(asset you installed anaconda2 or 3)，or  you can follow the steps to build caffe2(caffe2's build from source) 
apologize for not helping your to solve this problem.
good luck to you

**Comment by 2name** [comment]
@yyf8989 
Hi,I think I solved it.
just download pytorch again

**Comment by EchoAmor** [comment]
@2name  hello，I met the same problem when I want to install pytorch from source,and I used anaconda followed Readme.txt,can you tell me how to solve this problem specifically?? Thank you very much!!!

**Comment by 2name** [comment]
@EchoAmor 
Hi,EchoAmor.
just downloading pytorch v1.0.0 again, I think I solved it. 
If not, I apologize for not helping your to solve this problem.
I get other error now.

**Comment by EchoAmor** [comment]
@2name  Thanks ! I have downloaded v1.0.0 and solved this problem,but I have got #15911 now , and haven't solved yet ,so sad .

**Comment by luluyouyue** [comment]
I think we should solve this problem by error hint
