### ISSUE TITLE
RuntimeError: cublas runtime error : the GPU program failed to execute at at pytorch/work/aten/src/THC/THCBlas.cu:258

### ISSUE THREAD

**Issue by YiruS** [pytorch/pytorch#17334]
## 🐛 Bug

 I tried to run the pointnet module on Pytorch [https://github.com/fxia22/pointnet.pytorch](url) but got the error as shown in the title. 

## To Reproduce

I believe the error comes from the following code:

def forward(self, x):
        x, trans = self.feat(x)
        x = F.relu(self.bn1(self.fc1(x)))
        x = F.relu(self.bn2(self.fc2(x)))
        x = self.fc3(x)
        return F.log_softmax(x, dim=0), trans

The whole traceback is:

File “/home/yirus/software/pycharm-community-2018.3.4/helpers/pydev/pydevd.py”, line 1741, in 
main()
File “/home/yirus/software/pycharm-community-2018.3.4/helpers/pydev/pydevd.py”, line 1735, in main
globals = debugger.run(setup[‘file’], None, None, is_module)
File “/home/yirus/software/pycharm-community-2018.3.4/helpers/pydev/pydevd.py”, line 1135, in run
pydev_imports.execfile(file, globals, locals) # execute the script
File “/home/yirus/software/pycharm-community-2018.3.4/helpers/pydev/_pydev_imps/_pydev_execfile.py”, line 18, in execfile
exec(compile(contents+"\n", file, ‘exec’), glob, loc)
File “/home/yirus/Projects/pointnet.pytorch/train_classification.py”, line 78, in 
pred, _ = classifier(points)
File “/home/yirus/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py”, line 489, in call
result = self.forward(*input, **kwargs)
File “/home/yirus/Projects/pointnet.pytorch/pointnet.py”, line 100, in forward
x, trans = self.feat(x)
File “/home/yirus/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py”, line 489, in call
result = self.forward(*input, **kwargs)
File “/home/yirus/Projects/pointnet.pytorch/pointnet.py”, line 100, in forward
x, trans = self.feat(x)
File “/home/yirus/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py”, line 489, in call
result = self.forward(*input, **kwargs)
File “/home/yirus/Projects/pointnet.pytorch/pointnet.py”, line 73, in forward
trans = self.stn(x)
File “/home/yirus/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py”, line 489, in call
result = self.forward(*input, **kwargs)
File “/home/yirus/Projects/pointnet.pytorch/pointnet.py”, line 47, in forward
x = F.relu(self.bn4(self.fc1(x)))
File “/home/yirus/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py”, line 489, in call
result = self.forward(*input, **kwargs)
File “/home/yirus/anaconda3/lib/python3.7/site-packages/torch/nn/modules/linear.py”, line 67, in forward
return F.linear(input, self.weight, self.bias)
File “/home/yirus/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py”, line 1352, in linear
ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.1.post2 (installed by anaconda3)
 - OS (e.g., Linux): Linux (Fedora 28)
 - How you installed PyTorch (`conda`, `pip`, source): anaconda3
 - Build command you used (if compiling from source):
 - Python version: Python 3.7
 - CUDA/cuDNN version: Cuda 9.2/cudnn 7.4
 - GPU models and configuration: GeForce RTX 2080
 - Any other relevant information:

## Additional context

My guess is that something is wrong with the current CUDA or CUDNN version. 
Any information is appreciated!

**Comment by soumith** [comment]
For RTX 2080, you need to use CUDA10, not CUDA 9.2

**Comment by YiruS** [comment]
> For RTX 2080, you need to use CUDA10, not CUDA 9.2

@soumith  Thanks for the quick response! However, I'm using Fedora 28 and from the official CUDA download website there is no CUDA10.0 compatible with Fedora 28. Does that mean that I have to revert to Fedora 27 and then install CUDA10.0? Or is there any workaround of it? Thanks!

**Comment by soumith** [comment]
I dont know the answer (probably can download CUDA10 from nvidia site directly). But 2080Ti is Turing architecture, for that you need CUDA10.

**Comment by hoangcuongbk80** [comment]
I used PyTorch-1.0 and ran ./experiments/scripts/train_ycb.sh from [DenseFusion.](https://github.com/j96w/DenseFusion)

Then I got the error:

pred = torch.add(torch.bmm(model_points, base), points + pred_t) RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:441

My system:

    GeForce RTX 2080 Ti
    nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04

**Comment by hygxy** [comment]
@hoangcuongbk80  I had the same issue as yours on RTX 2080.

**Comment by toosi** [comment]
Same issue
RTX2080 torch 1.1.0 cuda10.0 cudnn7.5 
It happens after running some epochs, seems quite random

**Comment by someAdjectiveNoun** [comment]
I get the same error with CUDA10.

**CUDA version**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Error**
`RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:331`

**Comment by WZHsmile** [comment]
> For RTX 2080, you need to use CUDA10, not CUDA 9
Does TITAN RTX(24G) support cuda9.2 or cuda8.0?

**Comment by WZHsmile** [comment]
> I dont know the answer (probably can download CUDA10 from nvidia site directly). But 2080Ti is Turing architecture, for that you need CUDA10.

Does TITAN RTX(24G) support cuda9.2 or cuda8.0?

**Comment by danielgf0824** [comment]
same question on Tesla T4 with CUDA11.0

**Comment by guess-who-ami** [comment]
> 



> I used PyTorch-1.0 and ran ./experiments/scripts/train_ycb.sh from [DenseFusion.](https://github.com/j96w/DenseFusion)
> 
> Then I got the error:
> 
> pred = torch.add(torch.bmm(model_points, base), points + pred_t) RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:441
> 
> My system:
> 
> ```
> GeForce RTX 2080 Ti
> nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04
> ```

did you have a solution to this issue? i got the same problem

**Comment by Light--** [comment]
any solution? same error

**Comment by julian-q** [comment]
I also encountered this using an A100 gpu and was able to solve it. It was the CUDA version PyTorch was linked to. I ran `nvidia-smi` and saw that I had CUDA 11.7 installed. Then I ran 
```
python -c "import torch; print(torch.version.cuda)"
``` 
and saw that PyTorch was linked to a much older version, (CUDA 9). 

#### Solution
I first uninstalled my existing version of PyTorch:
```
pip uninstall torch
pip uninstall torchvision
pip uninstall torchaudio
```
Then, I reinstalled PyTorch (with pip in my case) following [these instructions](https://pytorch.org), selecting compute platform CUDA 11.3. Note that you might want to choose a different CUDA version, depending on what you have installed (run `nvidia-smi`), which will change the command below.
```
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
```
