### ISSUE TITLE
torch.load on multi-gpu devices does not respect map_location device index if it isn't 0

### ISSUE THREAD

**Issue by danielgordon10** [pytorch/pytorch#17364]
## 🐛 Bug

save_file has some parameters that were saved on device 0.

```python
torch.load(save_file, map_location=0)
```
This opens the parameters on device 0.

```python
torch.load(save_file, map_location=1)
```
This opens the parameters on device 1 and a small amount of GPU ram on device 0 which is never freed.

```python
with torch.cuda.device(1)
  torch.load(save_file)
```
This opens the parameters on device 0 (i.e. the wrong device) and is never freed.

```python
with torch.cuda.device(1)
  torch.load(save_file, map_location=1)
```
This also opens on device 0 (i.e. the wrong device) and is never freed.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.15.0
[pip] numpy-quaternion==2018.11.3.1.0.41
[pip] torch==1.0.0
[pip] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl_fft                   1.0.10           py36ha843d7b_0
[conda] mkl_random                1.0.2            py36hd81dba3_0
[conda] pytorch                   1.0.0           py3.6_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] torch                     1.0.0                     <pip>
[conda] torchvision               0.2.1                     <pip>
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by soumith** [comment]
there is no `device` option to `torch.load`, this is incorrect usage on your end.

Look at `map_location` option to `torch.load` to achieve what you want.

**Comment by danielgordon10** [comment]
You are right that `device` is not the keyword, but the problem still exists. If you pass in a second argument without naming it, you still run into the issue.

**Comment by danielgordon10** [comment]
Some code examples
```python
import torch

def save_dummy(path):
    torch.save([torch.nn.Parameter(torch.randn(1000, 1000))], path)

def load_saved(path, map_location):
    restored_var = torch.load(path, map_location)
    return restored_var

save_dummy('foo.pt')
restored = load_saved('foo.pt', map_location=torch.device(1))
```

nvidia-smi result
```
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     53367      C   python                                       281MiB |
|    1     53367      C   python                                       689MiB |
+-----------------------------------------------------------------------------+
```
---

```python
import torch

def save_dummy(path):
    torch.save([torch.nn.Parameter(torch.randn(1000, 1000))], path)

def load_saved(path, map_location):
    restored_var = torch.load(path, map_location)
    return restored_var

save_dummy('foo.pt')
restored = load_saved('foo.pt', map_location=torch.device(0))
```

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     56063      C   python                                       689MiB |
+-----------------------------------------------------------------------------+
```
---

```python
import torch

def save_dummy(path):
    torch.save([torch.nn.Parameter(torch.randn(1000, 1000))], path)

def load_saved(path, map_location):
    restored_var = torch.load(path, map_location)
    return restored_var

save_dummy('foo.pt')
restored = load_saved('foo.pt', map_location='cuda1')
```

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     56063      C   python                                       689MiB |
+-----------------------------------------------------------------------------+
```

The third example is especially surprising because it seems to ignore the map_location altogether, though I may be calling it wrong.

**Comment by ezyang** [comment]
I think that you are actually tripping over a few issues here. I'm going to split out a few of them into their own issues.

**Comment by ezyang** [comment]
I can't reproduce your initialization of GPU 0 on master.

```
(/home/ezyang/Dev/pytorch-tmp-env) [ezyang@devgpu005.ash6 ~/Dev/pytorch-tmp] cat foo.py
import torch
import pdb

def save_dummy(path):
    torch.save([torch.nn.Parameter(torch.randn(1000, 1000))], path)

def load_saved(path, map_location):
    restored_var = torch.load(path, map_location)
    return restored_var

save_dummy('foo.pt')
restored = load_saved('foo.pt', map_location=torch.device(1))

pdb.set_trace()
(/home/ezyang/Dev/pytorch-tmp-env) [ezyang@devgpu005.ash6 ~/Dev/pytorch-tmp] python foo.py
--Return--
> /data/users/ezyang/pytorch-tmp/foo.py(14)<module>()->None
-> pdb.set_trace()
```

From another terminal, nvidia-smi:

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    1    661256      C   python                                       364MiB |
+-----------------------------------------------------------------------------+
```

My environment:

```
Collecting environment information...
PyTorch version: 1.1.0a0+4dd73e1
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration: 
GPU 0: Tesla M40
GPU 1: Tesla M40
GPU 2: Tesla M40
GPU 3: Tesla M40
GPU 4: Tesla M40
GPU 5: Tesla M40
GPU 6: Tesla M40
GPU 7: Tesla M40

Nvidia driver version: 396.69
cuDNN version: /usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] torch==1.1.0a0+4dd73e1
[conda] blas                      1.0                         mkl  
[conda] magma-cuda92              2.5.0                         1    pytorch
[conda] mkl                       2019.3                      199  
[conda] mkl-include               2019.3                      199  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0
```

Could you please try upgrading PyTorch and see if that resolves your issue? Please reopen this issue if it does not.

#19076 is still a legit issue, I will leave that issue open.

**Comment by danielgordon10** [comment]
I do not see the issue in torch==1.0.1.post2 :)
