### ISSUE TITLE
Remove norm_except_dim (because norm now provides the same functionality)

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#17395]
## 📚 Documentation

`torch.norm_except_dim` is not documented.
It is used for WeightNorm but e.g. StyleGAN has PixelNorm which could use it.

Also, it might be nice to make the power a float to better align with norm.

## Alternative

Make it internal, i.e. `_norm_except_dim`.

@mcarilli Do you have an opinion on whether float would be costly?

cc @ezyang @gchanan @vincentqb @vishwakftw @jianyuh @nikitaved @pearu @mruberry @SsnL

**Comment by SsnL** [comment]
Looking at https://github.com/pytorch/pytorch/blob/517c7c98610402e2746586c78987c64c28e024aa/aten/src/ATen/native/WeightNorm.cpp#L19, I'm a bit confused. What's the difference between `norm_except_dim` and `norm`?

Also, the subtlety in pixel norm is that it divides over #dim before taking sqrt, which I think is different from normal `norm`.

**Comment by t-vi** [comment]
norm contracts on dim and norm_except_dim on all others (if norm didn't have the funny IntList, it probably is very similar).

**Comment by mcarilli** [comment]
It was intended as internal to weight norm (a C++-side implementation of what used to be Python logic, to work alongside the fused kernels).  The Python function that played that role in the original implementation was called "_norm" so I think it makes sense to call mine "_norm_except_dim." 

I also think reductions have since been updated such that you can reduce or norm over an arbitrary set of dimensions (@jjsjann123 is that true?) meaning that `norm_except_dim` is obselete as a user-facing function.  For the purpose of weight norm itself, I don't think it does any harm in its present form, unless you want weightnorm over an internal dim, which is an uncommon case.

**Comment by jjsjann123** [comment]
Yes, `torch.norm` now supports arbitrary dimensions. Fingers crossed that the perf is reasonable. 🙏

**Comment by humandotlearning** [comment]
Hi i would love to do this as my first PR, could you guide me to all the files from which norm_except_dim should be removed? and if this issue is still valid @soumith @VitalyFedyunin

**Comment by VitalyFedyunin** [comment]
To start please compare performance of `torch.norm` vs `_norm_except_dim` both CPU and CUDA. If the comparable, I can provide guidance how to remove this function entirely.

**Comment by VitalyFedyunin** [comment]
BC-breaking as we will mark operator as deprecated.

**Comment by humandotlearning** [comment]
hey @VitalyFedyunin I compared the **performance of torch.norm and torch.norm_except_dim** as you asked me to, through my comparison it is clear that `torch.norm` **is faster** than `torch.norm_except_dim`

you can find the comparison report attached:
[performance report_ torch.norm vs torch.norm_except_dim.xlsx](https://github.com/pytorch/pytorch/files/3672156/performance.report_.torch.norm.vs.torch.norm_except_dim.xlsx)

**Comment by humandotlearning** [comment]
you can 

> hey @VitalyFedyunin I compared the **performance of torch.norm and torch.norm_except_dim** as you asked me to, through my comparison it is clear that `torch.norm` **is faster** than `torch.norm_except_dim`
> 
> you can find the comparison report attached:
> [performance report_ torch.norm vs torch.norm_except_dim.xlsx](https://github.com/pytorch/pytorch/files/3672156/performance.report_.torch.norm.vs.torch.norm_except_dim.xlsx)

you can also find the comparison report at:
https://drive.google.com/open?id=1LIJ4m1_aWK1cQwvSHIR3e6xGd-gJ087obDCFEoyzO5I

**Comment by humandotlearning** [comment]
hey @VitalyFedyunin, @soumith I have done the

> hey @VitalyFedyunin I compared the **performance of torch.norm and torch.norm_except_dim** as you asked me to, through my comparison it is clear that `torch.norm` **is faster** than `torch.norm_except_dim`
> 
> you can find the comparison report attached:
> [performance report_ torch.norm vs torch.norm_except_dim.xlsx](https://github.com/pytorch/pytorch/files/3672156/performance.report_.torch.norm.vs.torch.norm_except_dim.xlsx)

hey @VitalyFedyunin , @soumith I have done the performance compare of norm and norm_except_dim could you guide me as in removing norm_except_dim as it seems redundant now. Thanks.

**Comment by VitalyFedyunin** [comment]
Hi!

Lets start with main things:

1) Please attach benchmarking script to make sure we tested correct thing.
2) Please do same comparison for CUDA, as we need to be absolutely sure, that we safe to update both.
3) If all above is correct, lets start looking into multi-step project:
	a) Bind `norm_except_dim` calls to `norm`
	b) Deprecate `norm_except_dim`

3a will require rewriting https://github.com/pytorch/pytorch/blob/852f8526c52190125446adc9a6ecbcc28fb66182/aten/src/ATen/native/WeightNorm.cpp#L15 function to properly call at::norm matching performance of both.

**Comment by t-vi** [comment]
I think this is not interesting.
