### ISSUE TITLE
How to call pytorch from a wxpython gui

### ISSUE THREAD

**Issue by pietrofusco** [pytorch/pytorch#17394]
## ❓ Hi everyone,
I was wondering if someone can help me to understand how to use/call pytorch from a wxpython GUI.
I have not been finding any suggestion on web so far

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by t-vi** [comment]
I would strongly recommend to ask that on the [https://discuss.pytorch.org](forum). Your question get much broader exposure there and it will be much more likely that someone reads it who knows the answer.
