### ISSUE TITLE
torch.inverse support for half tensor type

### ISSUE THREAD

**Issue by jerrybai1995** [pytorch/pytorch#17413]
## 🚀 Feature

It'd be great if pytorch's `torch.inverse` can support more tensor types (in particular `HalfTensor`). While the documentation here says `torch.inverse` works on `Tensor` type, it actually only works on `FloatTensor` and `DoubleTensor` now (instead of int and half types).

## Motivation

This is mainly motivated by a memory concern. I'm doing an operation that takes a lot of memory and using `half` makes it more space efficient. Currently, I'm just using `float32`.

**Comment by soumith** [comment]
you do not want to do `torch.inverse` in Half precision, it's a highly unstable operation and Half precision pretty sure wont be sufficient.
