### ISSUE TITLE
[JIT] Implement __getstate__ and __setstate__ APIs for ScriptModule

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#17422]
So we can get rid of these hacks: https://github.com/pytorch/pytorch/blob/master/torch/jit/quantized.py#L30

We should define conventions for adding code to be run on (de-)serialization that are universally called in load() and save() APIs. The example here is calling code that creates machine-specific packed matrices for a high-performance GEMM kernel.

**Comment by dzhulgakov** [comment]
Overtaken by #19030 that has more description.
