### ISSUE TITLE
The GPU memory of tensor will not release in libtorch

### ISSUE THREAD

**Issue by justbeu** [pytorch/pytorch#17433]
## To Reproduce

1. build the code below
2. See the result of free memory of GPU

here is my code
#include <torch/script.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <device_launch_parameters.h>
void NetWorkInitRun()
{
	at::Device device = at::Device(at::kCUDA);
	auto img = torch::ones({ 1, 1, 100000, 10000 }, torch::kFloat32);
	//img = img.to(torch::kCPU);
	img = img.to(device, false);

};
void displayGPUMemory()
{
	CUresult uRet;
	size_t free1;
	size_t total1;
	uRet = cuMemGetInfo(&free1, &total1);
	if (uRet == CUDA_SUCCESS)
		printf("FreeMemory = %d Mb in TotalMeory = %d Mb\n", free1 / 1024 / 1024, total1 / 1024 / 1024);
}
void main()
{
	int *dn;
	cudaMalloc((void **)&dn, 1 * sizeof(int));
	displayGPUMemory();
	NetWorkInitRun();
	displayGPUMemory();
}
## Expected behavior
The result of this code is 
FreeMemory = 6667 Mb in TotalMeory = 8192 Mb
FreeMemory = 2852 Mb in TotalMeory = 8192 Mb

the GPU memory after NetWorkInitRun() must be released, but we find the GPU memory is not released. 

## Environment

 - PyTorch Version 1.0 :
 - OS windows10:
 - How you installed PyTorch conda:
 - Build command you used (if compiling from source):
 - Python version: 3.6 
 - CUDA/cuDNN version: 8.0 
 - GPU models and configuration: GTX 1070
 - Any other relevant information:

**Comment by t-vi** [comment]
I think you are looking for `c10::cuda::CUDACachingAllocator::emptyCache();`.

**Comment by justbeu** [comment]
thanks for your reply but i can't find c10::cuda::CUDACachingAllocator::emptyCache(); in libtorch stable 1.0 version and nightly build version. so could you please tell the version number?

> I think you are looking for `c10::cuda::CUDACachingAllocator::emptyCache();`.
> Please don't hesitate to reopen the issue if you find that it's not working when you do release cache memory.

**Comment by ezyang** [comment]
Hi, that's the name of it on master. In 1.0 I believe you want `THCCachingAllocator_emptyCache()`

**Comment by yabinzhangJohn** [comment]
Hi I have tried `c10::cuda::CUDACachingAllocator::emptyCache();`, and it can release the cached memory allocated for `module->forward` in GPU. 
However, when I want to unload the `std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(model_path); module->to(torch::kCUDA);`, simply reset the shared pointer by `module.reset();` has no effect, where the module still lies on GPU.
Unless the whole process is ended, the GPU memory is released.

**Comment by yabinzhangJohn** [comment]
@soumith Since I cannot upload the pt model file, I attached the intermediate information about the cuda memory cache and nvidia-smi. 'c10::cuda::CUDACachingAllocator::emptyCache();' clears the cache, but there is still 589MB left, which is mostly occupied by the loaded module.

```cpp
#include <torch/script.h> // One-stop header.
#include <torch/torch.h>
#include <iostream>
#include <fstream>
#include <memory>
#include <thread>
#include <c10/cuda/CUDACachingAllocator.h>

using namespace std;

void display_c10_cuda_mem_stat(int32_t sleep_time) {
    printf("currentMemoryAllocated/[maxMemoryAllocated]: \t %0.1f/[%0.1f] MB\n ",
        c10::cuda::CUDACachingAllocator::currentMemoryAllocated(0) / 1024.0 / 1024.0,
        c10::cuda::CUDACachingAllocator::maxMemoryAllocated(0) / 1024.0 / 1024.0);
    printf("currentMemoryCached/[maxMemoryCached]: \t %0.1f/[%0.1f] MB\n",
        c10::cuda::CUDACachingAllocator::currentMemoryCached(0) / 1024.0 / 1024.0,
        c10::cuda::CUDACachingAllocator::maxMemoryCached(0) / 1024.0 / 1024.0);
    std::this_thread::sleep_for(std::chrono::milliseconds(1000*sleep_time));
}

int main(int argc, const char* argv[]) {
    int32_t sleep_time = 15;

    string modelFile = "modelfile.pt";
    // Deserialize the ScriptModule from a file using torch::jit::load().
    shared_ptr<torch::jit::script::Module> module = torch::jit::load(modelFile);
    module->to(at::kCUDA);
    
    assert(module != nullptr);

    float * input_img_batch = new float[8*1*224*224];
    load_img(input_img_batch);

    torch::Tensor tensor_img = torch::from_blob(input_img_batch, {8, 1, 224, 224});

    std::vector<torch::jit::IValue> inputs;
    inputs.push_back(tensor_img.cuda());
    display_c10_cuda_mem_stat(sleep_time);
    // Output info
    // currentMemoryAllocated/[maxMemoryAllocated]:    13.9/[13.9] MB
    // currentMemoryCached/[maxMemoryCached]:          28.0/[28.0] MB
    // nvidia-smi
    // | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    // | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    // |===============================+======================+======================|
    // |   0  Tesla P40           On   | 00000000:0F:00.0 Off |                  Off |
    // | N/A   29C    P0    53W / 250W |    425MiB / 24451MiB |      0%      Default |
    // +-------------------------------+----------------------+----------------------+    

    for (unsigned r = 0; r < 1; r++) {
        at::Tensor output;
        output = module->forward(inputs).toTensor();
        output = output.cpu();
    }
    display_c10_cuda_mem_stat(sleep_time);
    // currentMemoryAllocated/[maxMemoryAllocated]:    13.9/[322.9] MB
    // currentMemoryCached/[maxMemoryCached]:          348.0/[348.0] MB
    // nvidia-smi
    // | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    // | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    // |===============================+======================+======================|
    // |   0  Tesla P40           On   | 00000000:0F:00.0 Off |                  Off |
    // | N/A   30C    P0    53W / 250W |    909MiB / 24451MiB |      0%      Default |
    // +-------------------------------+----------------------+----------------------+ 
    
    c10::cuda::CUDACachingAllocator::emptyCache();
    display_c10_cuda_mem_stat(sleep_time);
    // currentMemoryAllocated/[maxMemoryAllocated]:    13.9/[322.9] MB
    // currentMemoryCached/[maxMemoryCached]:          28.0/[348.0] MB
    // nvidia-smi
    // | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    // | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    // |===============================+======================+======================|
    // |   0  Tesla P40           On   | 00000000:0F:00.0 Off |                  Off |
    // | N/A   31C    P0    53W / 250W |    589MiB / 24451MiB |      0%      Default |
    // +-------------------------------+----------------------+----------------------+ 

    delete [] input_img_batch;
    return 0;
}
```

**Comment by soumith** [comment]
@yabinzhangJohn 589MB is pretty likely just the CUDA context and other CUDA-specific initializations. They are not allocations of a Tensor or anything PyTorch related.
The only way to remove that is by removing the CUDA context, which effectively means kill the pytorch process.

**Comment by yabinzhangJohn** [comment]
@soumith Thanks a lot! `cudaDeviceReset()` can release the resource associated with the current process.

**Comment by soumith** [comment]
yes but cudaDeviceReset() will reset the entire GPU. If other processes are on the device, I believe even they will crash. Is it not the case?

**Comment by yabinzhangJohn** [comment]
I checked it again. Other processes on the device can run normally.
In the document, 

> cudaDeviceReset(void) explicitly destroys and cleans up all resources associated with the current device in the current process

**Comment by soumith** [comment]
oh okay, good to know, didn't know this.

**Comment by justbeu** [comment]
> Hi, that's the name of it on master. In 1.0 I believe you want `THCCachingAllocator_emptyCache()`

i find in windows version there is no such function, maybe in linux version, you can find this function

**Comment by jerry4h** [comment]
> 
> 
> > Hi, that's the name of it on master. In 1.0 I believe you want `THCCachingAllocator_emptyCache()`
> 
> i find in windows version there is no such function, maybe in linux version, you can find this function

I found it in `libtorch/include/THC/THCCachingAllocator.h`, and I found his function quite helpful with low time cost.
