### ISSUE TITLE
Is there any API to visualize the architecture of model?

### ISSUE THREAD

**Issue by Pinnh** [pytorch/pytorch#1744]
I know the 'print' method can show the graph of model,but is there any API to visualize(plot) the architecture of pytorch network model? thanks~

**Comment by apaszke** [comment]
There's [@szagoruyko script](https://github.com/szagoruyko/functional-zoo/blob/master/visualize.py) that produces a `dot` file

**Comment by Pinnh** [comment]
OK，Thanks a lot.
