### ISSUE TITLE
Why do I have to install CUDA and CUDNN first before installing pytorch GPU version ?

### ISSUE THREAD

**Issue by BigBigWolf-AI** [pytorch/pytorch#17445]
## 🚀 Feature
    When installing Pytorch using pip, the CUDA and CuDNN libraries needed for GPU support must be installed separately, **adding a burden on getting started.** When the GPU accelerated version of Pytorch is installed using conda, by the command “conda install pytorch-gpu”, these libraries are installed automatically, with versions known to be compatible with the pytorch-gpu package. Furthermore, conda installs these libraries into a location where they will not interfere with other instances of these libraries that may have been installed via another method. Regardless of using pip or conda-installed pytorch-gpu, the NVIDIA driver must be installed separately **which means that all the software except pytorch I have to install is NVIDIA graphic card griver before I begin my deep learning journey. It is really simple.**
    For many versions of pytorch, conda packages are available for multiple CUDA versions,because these libraries are installed via conda, users can easily create multiple environments and compare the performance of different CUDA versions.

## Motivation

It is really annoying to install CUDA and CUDNN separately. It is really hard for a user who is not so much familiar with Linux to set the path of CUDA and CUDNN.

## Pitch

Google's kid tensorflow has achieved that feature. It is really friendly to new user(PS: I know your guys know the 'friendly' means the way of install tensorflow instead of tensorflow thich is definitely not friendly).
I really hope that pytorch can ahieve that feature as soon as possible.

One more question: pytorch supports the MKL and MKL-DNN libraries， right？

**Reference：**
[https://www.anaconda.com/tensorflow-in-anaconda/](url)

**Comment by RicCu** [comment]
Hi,
have you found issues with PyTorch's installation via pip? If so, it might be a regression, because it used to [include CUDA and CuDNN](https://www.anaconda.com/tensorflow-in-anaconda/), the only limitation being that you have to [install numpy separately](https://pytorch.org/get-started/locally/#numpy).

AFAIK you only need to install CUDA and CuDNN separately if you're building PyTorch from source.

**Comment by BigBigWolf-AI** [comment]
> Hi,
> have you found issues with PyTorch's installation via pip? If so, it might be a regression, because it used to [include CUDA and CuDNN](https://www.anaconda.com/tensorflow-in-anaconda/), the only limitation being that you have to [install numpy separately](https://pytorch.org/get-started/locally/#numpy).
> 
> AFAIK you only need to install CUDA and CuDNN separately if you're building PyTorch from source.

Hi,
What I want to know is if I use the command _**conda install**_ to install pytorch GPU version, do I have to install cuda and cudnn first before I begin the installation ?

**Comment by RicCu** [comment]
No, `conda install` will include the necessary cuda and cudnn binaries, you don't have to install them separately. However you do have to specify the cuda version you want to use, e.g. `conda install pytorch cudatoolkit=9.0 -c pytorch`.
See PyTorch's [Get started](https://pytorch.org/get-started/locally/) guide for more info and detailed installation instructions :smile:

**Comment by BigBigWolf-AI** [comment]
Thank you very much! It is really surpriseed to see an emoji on the answer of a issue, how to do that!!!!!

**Comment by n0obcoder** [comment]
> will include the necessary cuda and cudnn binaries, you don't have to in

yes i was able to install pytorch this way, bt i still cant use the GPU while training a model in pytorch

Can you pls help me here ? 
Thanks in advance : )

**Comment by RicCu** [comment]
Hi, 
Do you have a correct version of Nvidia driver installed?
Could you share some more info on your problem?
