### ISSUE TITLE
Sharing GPU tensors among different processes using billiard

### ISSUE THREAD

**Issue by isaacleeai** [pytorch/pytorch#17459]
## 🚀 Feature

Currenlty, pytorch only supports sharing tensors among multiple GPUs using `torch.multiprocessing`. Could you extend this support to `billiard` ( since the taskpool of `billiard` is often found to be more sophisticated and used widely -- ex. `celery` )? 

## Motivation

Being able to use `celery` -- which uses `billiard` -- s.t. processes in the task pool read from shared CUDA tensor, instead of each having a unique copy.

**Comment by soumith** [comment]
do you know what the scope of the work would be? (are you familiar with internal stack of `billiard` etc.?)

This is something that we as core devs wont take up, but if it's reasonably scoped and you want it, let's talk about what code changes might have to be made, to make a decision on yes or no.

**Comment by VitalyFedyunin** [comment]
This seems to be doable by combining code from the https://github.com/celery/billiard/blob/master/billiard/reduction.py with our custom reductions from the
torch/multiprocessing/reductions.py basically all you need to do it copy 
```
    ForkingPickler.register(torch.cuda.Event, reduce_event)

    for t in torch._storage_classes:
        ForkingPickler.register(t, reduce_storage)

    for t in torch._tensor_classes:
        ForkingPickler.register(t, reduce_tensor)

    # TODO: Maybe this should be in tensor_classes? :)
    ForkingPickler.register(torch.Tensor, reduce_tensor)
    ForkingPickler.register(torch.nn.parameter.Parameter, reduce_tensor)
``` 
into the billiard code or separate module

**Comment by VitalyFedyunin** [comment]
Closing because it is out of the project scope and should be implemented as a separate python module as part of billiard.
