### ISSUE TITLE
Cublas runtime error 

### ISSUE THREAD

**Issue by tlatlbtle** [pytorch/pytorch#1745]
Problem when run Pytorch：GPU program failed to execute
I get a run time error showing below:
![2017-06-07 13-57-07](https://user-images.githubusercontent.com/23569606/26866203-aaaf16e6-4b92-11e7-833e-fed3f0dc977b.png)
It seems that GPU failed to execute. I could certain that it doesn't due to the CUDA environment error. Why it occurs and how to solve this problem?:-D

**Comment by Kongsea** [comment]
I met the same problem. How do you solve it finally?

**Comment by KiyoshiKAWASAKI** [comment]
Hi I have the exact same error here, have you solved this problem?

**Comment by frankang** [comment]
I have the same problem here...

**Comment by phohenecker** [comment]
Hi everyone! Just ran into the same problem. Are there any solutions yet?

**Comment by 111qqz** [comment]
same problem here ...
