### ISSUE TITLE
torch.utils.data DataLoader does not index by integers

### ISSUE THREAD

**Issue by otaj** [pytorch/pytorch#17466]
## 📚 Documentation

Hi, it seems DataLoader with shuffle=True does not index dataset by integers but by torch.tensor instances of integers. I suspect, this happens in multiple places, especially samplers. This might seem like unimportant case, however I managed to run out of memory on my 250G server because I was internally actually indexing into dictionary. And since tensor instances don't have reasonable `__hash__`, I was never able to find my loaded item.

See the snippet of the code to illustrate the problem, if option `keep_ram` was passed to the constructor of `LiDARDataset` and the two commented lines in `__getitem__` were not there, the process would grow in memory with every call to `__getitem__`. However, if the check for integer is there, the dataset stays at around 12G, which is actually expected and does not grow.

    class LiDARDataset(torch.utils.data.Dataset):
        def __init__(self, folder, keep_ram=False):
            self.names = sorted(glob.glob(os.path.join(folder, '*.npy')))
            self.keep_ram = keep_ram
            if self.keep_ram:
                self.loaded = dict()
            else:
                self.loaded = weakref.WeakValueDictionary()

        def __len__(self):
            return len(self.names)

        def __getitem__(self, key):
            if not isinstance(key, int): # without these two lines, it would grow
                key = key.item() 
            result = self.loaded.get(key) # because the result would always be None
            if result is None:
                result = self.transform(np.load(self.names[key]), key)
                self.loaded[key] = result
            return result

**Comment by SsnL** [comment]
What's your pytorch version? IIRC, we fixed a bug like this a while ago.

**Comment by otaj** [comment]
1.0.1
What I am saying is that I don't mind not having `__hash__` dependant on tensor's value, that's reasonable.
However, the behavior of at least torch.utils.data.RandomSampler differs from what is said in documentation. You can see it [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/sampler.py#L76) the iterator returned returns 0-D torch.Tensors, when in fact documentation for example [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataset.py#L1`) says it should support indexing by integers.

**Comment by otaj** [comment]
So my proposed solution is to either change the documentation to reflect the fact that it is necessary to be able to index your Dataset by integers wrapped in torch.tensor, maybe with a warning saying indexing to dict won't work as expected, or change `__iter__` of at least RandomSampler, SubsetRandomSampler and WeightedRandomSampler (seems like these three are the only ones in sampler.py, however, there could be more of these instances lurking hidden somewhere I guess)

**Comment by SsnL** [comment]
Thanks for the investigation. We should fix the samplers.

**Comment by otaj** [comment]
It actually seems, the problem might be the random_split and not the RandomSampler (it has tolist() everywhere after all), see this to reproduce:

    class datalist(list):
        def __getitem__(self, key):
            print(type(key))
            return super().__getitem__(key)
    
    import torch.utils.data as data
    dataset = datalist(range(10))
    n_dataset = data.random_split(dataset, [10])[0]
    for batch in data.DataLoader(n_dataset):
        pass # <- this will print torch.tensor ten times because of monkey-patched __getitem__,  cuplrit seems to be random_split

**Comment by bhushan23** [comment]
random_split creates new copy of dataset (number of splits) and maintains index to be used for each.
This is consuming memory.

are you using random_split in your root issue?

**Comment by bhushan23** [comment]
@otaj #17649 does not create copies of original dataset, instead copies the required content into new dataset. Can you give it a try?

**Comment by bhushan23** [comment]
> @otaj #17649 does not create copies of original dataset, instead copies the required content into new dataset. Can you give it a try?

My above comment is invalid now.
We are indeed copying the dataset and storing indices as a list instead of tensor to ensure index indexing as opposed to tensor based indexing. Note that samplers already returns indices as a list and hence have no issues.
