### ISSUE TITLE
The source code for conv2d

### ISSUE THREAD

**Issue by wzn0828** [pytorch/pytorch#17465]
Hi, I wanna to do some work about the conv2d, but the release did not make the source code of con2d available.  What should I do to approach the conv2d?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by bhushan23** [comment]
Convolution base code is present in following file and directory
- aten/src/ATen/native/Convolution.cpp
- aten/src/THNN/generic/

Hope that helps. More importantly, what do you want to work on?

Also,
You are most welcome to post on shttps://discuss.pytorch.org in future for doubts.

Issues are more of for RFEs and bugs.

**Comment by bhushan23** [comment]
Convolution base code is present in following file and directory

- aten/src/ATen/native/Convolution.cpp
- aten/src/THNN/generic/

what do you want to work on?

We have a discussion forum here, https://discuss.pytorch.org
