### ISSUE TITLE
Will the pytorch environment  impacts other environments ?

### ISSUE THREAD

**Issue by BigBigWolf-AI** [pytorch/pytorch#17463]
OS: Ubuntu 16.04(which has installed cuda 9.0 and cudnn 7.5)

First, I create a virtual environment using the following command:
_**conda create -n pytorch_env python=3.6 conda**_
then I activate the pytorch_env and install pytorch using the following command:
_**conda install pytorch torchvision cudatoolkit=10.0 -c pytorch**_
We all know that the conda will install pytorch gpu version and the cuda 10 and cudnn in the virtual environment pytorch_env. What I to know is whether  the cuda 10 in pytorch_env will impact the cuda 9.0 which has been installed in my system ?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
