### ISSUE TITLE
Building libtorch-dependent project with CMake

### ISSUE THREAD

**Issue by hengyuan-hu** [pytorch/pytorch#17479]
## ❓ Questions and Help

I am writing a library depending mainly on torch::Tensor in libtorch. The library will have a python interface so that python program can get access to Tensor object defined in C++ code. A minimal example would look like this:
```
#include <pybind11/pybind11.h>
#include <torch/extension.h>

namespace py = pybind11;

struct TensorWrapper {
  TensorWrapper() {
    tensor = torch::ones({3, 3}, torch::kInt32);
  }

  int size;
  torch::Tensor tensor;
};

PYBIND11_MODULE(a, m) {
 py::class_<TensorWrapper>(m, "TensorWrapper")
     .def(py::init<>())
     .def_readwrite("tensor", &TensorWrapper::tensor)
     .def_readwrite("size", &TensorWrapper::size);
}
```

and my CMakeLists.txt looks like this:
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(a)

set(CMAKE_PREFIX_PATH /path/to/libtorch)
find_package(Torch REQUIRED)
include_directories(${TORCH_INCLUDE_DIRS})

add_subdirectory(/path/to/pybind11)
pybind11_add_module(a source.cc)

target_link_libraries(a PRIVATE "${TORCH_LIBRARIES}")
set_property(TARGET a PROPERTY CXX_STANDARD 11)
```

However, when I try to 'import a' in python, I get the following error:
```
ImportError: dlopen(a.cpython-37m-darwin.so, 2): Symbol not found: _THPVariableClass
  Referenced from: a.cpython-37m-darwin.so
  Expected in: flat namespace
 in a.cpython-37m-darwin.so
```

The source code works if I use `torch.utils.cpp_extension.load_inline` so I guess there is something wrong with the CMake flags. Any suggestions/help is much appreciated.

**Comment by teng-li** [comment]
@orionr @pjh5  Assigning to you guys since this looks like a build issue. Any idea on how easy this can be fixed?

**Comment by orionr** [comment]
Was just talking with @hengyuan-hu about this. cc @kostmo and @goldsborough as well.

You might be able to get some mileage out of looking at https://github.com/pytorch/pytorch/issues/12449  My hint is that you aren't setting the LIBRARY_PATH correctly somehow.

**Comment by pjh5** [comment]
I don't know the answer to this, but I suggest using new cmake 'targets' feature, more like

```
find_package(Torch REQUIRED)

add_library(a)
target_link_libraries(a PRIVATE Torch)
```
instead of messing with TORCH_INCLUDE_DIRS and TORCH_LIBRARIES themselves.

**Comment by hengyuan-hu** [comment]
The solution is to `import torch `before `import a`.

**Comment by FantasyJXF** [comment]
> The solution is to `import torch `before `import a`.

Didnt't work on my case. I successfully compile my project with Pybind11 and Libtorch, and  `import torch` first on my case, but still it run into error like this

```
$ ipython
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch                                                                                                                                               

In [2]: import csrc                                                                                                                                                
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-d690fbebbfb5> in <module>
----> 1 import csrc

ImportError: dlopen(/Users/jingxiaofei/Documents/Learning/PyTorch/libtorch_cpp/csrc/cmake-build-debug/csrc.cpython-37m-darwin.so, 2): Symbol not found: __Z7nms_cpuRKN2at6TensorES2_f
  Referenced from: /Users/jingxiaofei/Documents/Learning/PyTorch/libtorch_cpp/csrc/cmake-build-debug/csrc.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/jingxiaofei/Documents/Learning/PyTorch/libtorch_cpp/csrc/cmake-build-debug/csrc.cpython-37m-darwin.so

```

**Comment by hengyuan-hu** [comment]
I suspect that the libtorch version & pytorch mismatch, if you are using
binary distributions for both of them.

**Comment by FantasyJXF** [comment]
Thank you and I'm so sorry to bother, the answer you gave was right. I use my improper code to test and run into error.

After I fixed the code bug and do as you said  to `import torch` before `import my_ext`, it works OK.

Thanks again and very appreciate your work.
---
From Fantasy

> 在 2019年12月19日，下午1:09，Hengyuan Hu <notifications@github.com> 写道：
> 
> I suspect that the libtorch version & pytorch mismatch, if you are using
> binary distributions for both of them.
>

**Comment by hengyuan-hu** [comment]
Glad it helps. Btw, libtorch is mainly for c++ only applications. If you
use python anyway, you can just compile against pytorch. Libtorch is part
of pytorch. You can use this as an example.

https://github.com/facebookresearch/hanabi_SAD/blob/6e4ed590f5912fcb99633f4c224778a3ba78879b/rela/CMakeLists.txt#L10
