### ISSUE TITLE
Parameter not registering if .to(device) is used

### ISSUE THREAD

**Issue by konstantinosKokos** [pytorch/pytorch#17484]
## 🐛 Bug

During instantiation of a custom module, parameters do not register if they are initialized with a .to('cuda') function call on the parameter level. 

## To Reproduce

```
class A(torch.nn.Module):
    def __init__(self):
        super(A, self).__init__()
        self.par = torch.nn.Parameter(torch.rand(5)).to('cuda')
    def forward(self):
        pass
    
a= A()
a.state_dict()
Out[8]: OrderedDict()
```

On the other hand, if the .to('cuda') is called on the wrapped tensor, everything works as expected.

```
class A(torch.nn.Module):
    def __init__(self):
        super(A, self).__init__()
        self.par = torch.nn.Parameter(torch.rand(5, device='cuda'))
    def forward(self):
        pass
    
a = A()
a.state_dict()
Out[13]: 
OrderedDict([('par',
              tensor([0.0247, 0.8373, 0.2540, 0.9849, 0.5181], device='cuda:0'))])
```

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.5
Is CUDA available: N/A
CUDA runtime version: 7.5.17
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 384.130
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.1
[pip] numpy==1.13.3
[pip] torch==1.0.0
[pip] torchvision==0.2.1
[conda] Could not collect

**Comment by soumith** [comment]
this is totally expected.

Parameters can only be leaf Tensors, not Tensors that are a result of an operation on another Tensor.

What you want is:

```
self.par = torch.nn.Parameter(torch.rand(5, device='cuda'))
```

**Comment by arodriguezca** [comment]
I also run into this issue and it was tricky to debug. @soumith I would recommend putting a small note here: https://pytorch.org/docs/stable/generated/torch.nn.parameter.Parameter.html
