### ISSUE TITLE
Pytorch C++ - Cuda streams

### ISSUE THREAD

**Issue by soulslicer** [pytorch/pytorch#17493]
I have posted this on stackoverflow and on pytorch discussions, but have not gotten a response. I wish to do something like this, but in the Pytorch C++ API:

```
s1 = torch.cuda.Stream()
s2 = torch.cuda.Stream()
# Initialise cuda tensors here. E.g.:
A = torch.rand(1000, 1000, device = ‘cuda’)
B = torch.rand(1000, 1000, device = ‘cuda’)
# Wait for the above tensors to initialise.
torch.cuda.synchronize()
with torch.cuda.stream(s1):
    C = torch.mm(A, A)
with torch.cuda.stream(s2):
    D = torch.mm(B, B)
# Wait for C and D to be computed.
torch.cuda.synchronize()
# Do stuff with C and D.
```

I basically wish to run two `torch::mm` in two different streams simultenously to better use my GPU resource in the C++ Api. I am able to create the cuda stream, but unable to find any documentation on how this can be "passed" into the torch::mm operation

**Comment by soulslicer** [comment]
I've been looking through the Torch Code. It looks like i need to use stuff in <c10/cuda/CUDAStream.h>. Please help!

**Comment by ezyang** [comment]
CUDA streams are not passed to operators; instead, there is a notion of a current CUDA stream which operators use. Check out `CUDAGuard` for how to set the current stream.

**Comment by soulslicer** [comment]
Before you just close this, I would really appreciate some hints. Since this API is not listed anywhere. This would help other developers in the future as well. Am I suppose to instantiate a `CUDAStreamGuard` object? How do I actually pass in my cudaStream_t object?

**Comment by soumith** [comment]
You are supposed to use `CUDAStreamGuard`.

See: https://github.com/pytorch/pytorch/blob/792cb774f152bab5b968f4ec51da0fc21ff9e895/torch/lib/c10d/ProcessGroupNCCL.cpp#L559-L560

Your own cudaStream_t object might not be a thing we support, the references to CUDAStreamGuard are indices into our internal streampool and are objects of type `c10::cuda::CUDAStream`. You can get a stream from our stream-pool, and use it as a cudastream_t: https://github.com/pytorch/pytorch/blob/24f4d3987ec643fe245608625cfbf8997c42e87e/c10/cuda/CUDAStream.h#L133-L134

**Comment by soulslicer** [comment]
Thanks for the response. So it looks like I would have to instantiate my own at::cuda::CUDAStream() object and then set it with `at::cuda::CUDAStreamGuard guard(ncclStream);`

I have two questions on this:

**1.**
How do I actually instantiate a `at::cuda::CUDAStream` object? I assume it's through the `at::cuda::getStreamFromPool()` function, which adds a new stream, or takes from an existing? How many streams are there in the pool to begin with?

**2.** 
Usually Kernels are called with multKernel<<<dim3, dim3, byte, streamX>>(); The stream is passed into this and it's a non blocking call, hence multiple streams can process at once, until I do cudaDeviceSynchronize()

This mechanism does not seem similar to the `CUDAStreamGuard` approach. Is this how one would implement it?

```
        at::cuda::CUDAStreamGuard guard(stream1);
        torch::mm_out(X, a, b);
        at::cuda::CUDAStreamGuard guard(stream2);
        torch::mm_out(Y, c, d);
        cudaDeviceSynchronize(); // Or syncStreams
        torch::add_out(Z, X, Y);
```

I want `torch::mm_out(X, a, b);` and `torch::mm_out(Y, c, d);` to run on two seperate streams.

**Comment by soulslicer** [comment]
I tried to run my code with and without the CUDAStreamGuard commented out and the runtime is the same:

```
std::vector<at::cuda::CUDAStream> streams;
        streams.emplace_back(at::cuda::getStreamFromPool());
        streams.emplace_back(at::cuda::getStreamFromPool());
        streams.emplace_back(at::cuda::getStreamFromPool());

    measuretime();
    {
        torch::mm_out(X, A, B);
        at::cuda::CUDAStreamGuard g0(streams[0]);
        torch::mm_out(Y, A, C);
        at::cuda::CUDAStreamGuard g1(streams[1]);
        torch::mm_out(Z, A, D);
        at::cuda::CUDAStreamGuard g2(streams[2]);
        torch::mm_out(W, A, E);
    }
    measuretime();
```

What am I doing wrong

**Comment by soumith** [comment]
is `measuretime()` synchronizing on the host? For `measuretime()` to be correct, you need a `cudaDeviceSynchronize()`

Depending on the occupancy of the kernels, stream overlap might not achieve better timings, because the GPU might be occupied by the first MM fully with no blocks free for the second MM to run concurrently.

**Comment by soulslicer** [comment]
Yes it has it. I just used that syntax as placeholder. Ok if that's the case that's fine, I just wanted to make sure the syntax was right. Thanks again
