### ISSUE TITLE
Get rid of special 'inplace' handling in Declarations.yaml and corresponding generated code

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#17506]
## 🚀 Feature

We should get rid of special `inplace` handling in Declarations.yaml and corresponding generated code.

## Motivation

The `inplace` entry in Declarations.yaml is essentially a subset of our schema annotations, but the semantics aren't totally clear: does it mean "only the first parameter is an output and only the first parameter is modified?"  But we have examples that are not expressible in that form, e.g.:

`func: rrelu_with_noise_(Tensor self, Tensor noise, Scalar lower=0.125, Scalar upper=0.3333333333333333, bool training=False, Generator? generator=None) -> Tensor`

writes to both `self` and `noise` and only outputs `self`, but that is not expressible without schema annotations, but is perfectly expressible with schema annotations.

Essentially, names just becomes names and the schema tells you what the actual behavior is.  Of course we may want to enforce certain naming rules, but the point is that code gen behavior (outside of naming) is triggered based by the schema annotations, *not* by the name.

This came out of a discussion with @suo.  CC @cpuhrsch @zdevito.

**Comment by ezyang** [comment]
obsolete!
