### ISSUE TITLE
Floating exception (core dumped) when dividing by tensor(0)

### ISSUE THREAD

**Issue by nivha** [pytorch/pytorch#17504]
## 🐛 Bug

Dividing by ```torch.tensor(0)``` results in core dumped (instead of some catchable exception)

## To Reproduce

```
import torch
torch.tensor(3) / torch.tensor(0)
```

## Expected behavior

Raise some Python Exception

## Environment
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 2.8.12.2

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB
GPU 2: Tesla V100-PCIE-32GB
GPU 3: Tesla V100-PCIE-32GB
GPU 4: Tesla V100-PCIE-32GB
GPU 5: Tesla V100-PCIE-32GB

Nvidia driver version: 410.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.14.5
[pip3] numpydoc==0.7.0
[pip3] torch==1.0.0
[pip3] torchvision==0.2.1
[conda] Could not collect

**Comment by soumith** [comment]
we have no immediate or non-immediate plans to fix this.

This is because it's integer divide by zero, and the fix is to audit all of our numerical code and insert a branching (including SIMD code i think).

You can switch to floating point types via:

```
torch.tensor(3.) / torch.tensor(0.)
```
