### ISSUE TITLE
 CUDA error: invalid argument (launch_kernel at /pytorch/aten/src/ATen/native/cuda/Loops.cuh:62)

### ISSUE THREAD

**Issue by windson87** [pytorch/pytorch#17502]
Hi, am running multi-GPU training with pytorch, bu there is some cuda error happened which I dont get why.

My envs are:
Ubuntu 18.04.2 LTS
Running on 1 computer with 2 Tesla K80 Gpus
Cuda 10, pytorch 1.0.1 -post 2 (also CUDA 10 version)
Openmpi 4.0.0
NCCL2: 2.4.2 (the newest)
Horovod: newest 0.16.0

Could someone give a bit hint? THANKS! ;)

~$ mpirun -N 2 -H localhost:2 -bind-to none -map-by slot -x PATH -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH python3 /home/bfadmin/Documents/parallization_test/model4road/road_run_train_resunet_paral.py
Epoch 1/10
----------
LR 0.002
Epoch 1/10
----------
LR 0.002
linux-ml:12735:12795 [0] NCCL INFO NET/Socket : Using [0]eth0:10.1.8.5<0>
linux-ml:12735:12795 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
linux-ml:12735:12795 [0] NCCL INFO NET/IB : No device found.
NCCL version 2.4.2+cuda10.0

linux-ml:12735:12795 [0] include/topo.h:20 NCCL WARN Cuda failure 'invalid argument'
linux-ml:12735:12795 [0] NCCL INFO init.cu:864 -> 1
linux-ml:12735:12795 [0] NCCL INFO init.cu:887 -> 1
linux-ml:12735:12795 [0] NCCL INFO init.cu:911 -> 1
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: invalid argument (launch_kernel at /pytorch/aten/src/ATen/native/cuda/Loops.cuh:62)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f750a419021 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f750a4188ea in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #2: void at::native::gpu_unary_kernel<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, float), &(void at::native::div_constant_impl<float>(at::TensorIterator&, float)), 1u>, float (float), float> >(at::TensorIterator&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, float), &(void at::native::div_constant_impl<float>(at::TensorIterator&, float)), 1u>, float (float), float> const&) + 0x86f (0x7f74b88388ff in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so)
frame #3: <unknown function> + 0x243e3ba (0x7f74b880a3ba in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so)
frame #4: at::native::div_out(at::Tensor&, at::Tensor const&, at::Tensor const&) + 0xcd (0x7f74accb92cd in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so)
frame #5: at::native::div_(at::Tensor&, c10::Scalar) + 0x35 (0x7f74accb9d45 in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so)
frame #6: at::TypeDefault::div_(at::Tensor&, c10::Scalar) const + 0x60 (0x7f74acfc25f0 in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so)
frame #7: torch::autograd::VariableType::div_(at::Tensor&, c10::Scalar) const + 0x2c1 (0x7f74ab9378a1 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so.1)
frame #8: <unknown function> + 0x70444 (0x7f748e00f444 in /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x3fb1e (0x7f748dfdeb1e in /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x480da (0x7f748dfe70da in /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0x4a95b (0x7f748dfe995b in /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so)
frame #12: <unknown function> + 0xbd57f (0x7f750d36857f in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #13: <unknown function> + 0x76db (0x7f7510f706db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #14: clone + 0x3f (0x7f75112a988f in /lib/x86_64-linux-gnu/libc.so.6)

[linux-ml:12735] *** Process received signal ***
[linux-ml:12735] Signal: Aborted (6)
[linux-ml:12735] Signal code:  (-6)
[linux-ml:12735] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7f75111c6f20]
[linux-ml:12735] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f75111c6e97]
[linux-ml:12735] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f75111c8801]
[linux-ml:12735] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c8b7)[0x7f750d3378b7]
[linux-ml:12735] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92a06)[0x7f750d33da06]
[linux-ml:12735] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92a41)[0x7f750d33da41]
[linux-ml:12735] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92c74)[0x7f750d33dc74]
[linux-ml:12735] [ 7] /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so(_ZN2at6native16gpu_unary_kernelI18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIPFvRNS_14TensorIteratorEfEXadL_ZNS0_17div_constant_implIfEEvS5_T_EELj1EEFffEIfEEEEvS5_RKS9_+0x8a9)[0x7f74b8838939]
[linux-ml:12735] [ 8] /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so(+0x243e3ba)[0x7f74b880a3ba]
[linux-ml:12735] [ 9] /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so(_ZN2at6native7div_outERNS_6TensorERKS1_S4_+0xcd)[0x7f74accb92cd]
[linux-ml:12735] [10] /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so(_ZN2at6native4div_ERNS_6TensorEN3c106ScalarE+0x35)[0x7f74accb9d45]
[linux-ml:12735] [11] /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so(_ZNK2at11TypeDefault4div_ERNS_6TensorEN3c106ScalarE+0x60)[0x7f74acfc25f0]
[linux-ml:12735] [12] /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so.1(_ZNK5torch8autograd12VariableType4div_ERN2at6TensorEN3c106ScalarE+0x2c1)[0x7f74ab9378a1]
[linux-ml:12735] [13] /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(+0x70444)[0x7f748e00f444]
[linux-ml:12735] [14] /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(+0x3fb1e)[0x7f748dfdeb1e]
[linux-ml:12735] [15] /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(+0x480da)[0x7f748dfe70da]
[linux-ml:12735] [16] /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(+0x4a95b)[0x7f748dfe995b]
[linux-ml:12735] [17] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd57f)[0x7f750d36857f]
[linux-ml:12735] [18] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f7510f706db]
[linux-ml:12735] [19] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f75112a988f]
[linux-ml:12735] *** End of error message ***
linux-ml:12736:12796 [1] NCCL INFO NET/Socket : Using [0]eth0:10.1.8.5<0>
linux-ml:12736:12796 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
linux-ml:12736:12796 [1] NCCL INFO NET/IB : No device found.

linux-ml:12736:12796 [1] include/topo.h:20 NCCL WARN Cuda failure 'invalid argument'
linux-ml:12736:12796 [1] NCCL INFO init.cu:864 -> 1
linux-ml:12736:12796 [1] NCCL INFO init.cu:887 -> 1
linux-ml:12736:12796 [1] NCCL INFO init.cu:911 -> 1
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: invalid argument (launch_kernel at /pytorch/aten/src/ATen/native/cuda/Loops.cuh:62)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f403e1c3021 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f403e1c28ea in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #2: void at::native::gpu_unary_kernel<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, float), &(void at::native::div_constant_impl<float>(at::TensorIterator&, float)), 1u>, float (float), float> >(at::TensorIterator&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, float), &(void at::native::div_constant_impl<float>(at::TensorIterator&, float)), 1u>, float (float), float> const&) + 0x86f (0x7f404a7bd8ff in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so)
frame #3: <unknown function> + 0x243e3ba (0x7f404a78f3ba in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so)
frame #4: at::native::div_out(at::Tensor&, at::Tensor const&, at::Tensor const&) + 0xcd (0x7f403ec3e2cd in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so)
frame #5: at::native::div_(at::Tensor&, c10::Scalar) + 0x35 (0x7f403ec3ed45 in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so)
frame #6: at::TypeDefault::div_(at::Tensor&, c10::Scalar) const + 0x60 (0x7f403ef475f0 in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so)
frame #7: torch::autograd::VariableType::div_(at::Tensor&, c10::Scalar) const + 0x2c1 (0x7f403d46e8a1 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so.1)
frame #8: <unknown function> + 0x70444 (0x7f401d92c444 in /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x3fb1e (0x7f401d8fbb1e in /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x48862 (0x7f401d904862 in /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0x4a95b (0x7f401d90695b in /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so)
frame #12: <unknown function> + 0xbd57f (0x7f409a4b157f in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #13: <unknown function> + 0x76db (0x7f40a07d76db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #14: clone + 0x3f (0x7f40a0b1088f in /lib/x86_64-linux-gnu/libc.so.6)

[linux-ml:12736] *** Process received signal ***
[linux-ml:12736] Signal: Aborted (6)
[linux-ml:12736] Signal code:  (-6)
[linux-ml:12736] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7f40a0a2df20]
[linux-ml:12736] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f40a0a2de97]
[linux-ml:12736] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f40a0a2f801]
[linux-ml:12736] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c8b7)[0x7f409a4808b7]
[linux-ml:12736] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92a06)[0x7f409a486a06]
[linux-ml:12736] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92a41)[0x7f409a486a41]
[linux-ml:12736] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92c74)[0x7f409a486c74]
[linux-ml:12736] [ 7] /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so(_ZN2at6native16gpu_unary_kernelI18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIPFvRNS_14TensorIteratorEfEXadL_ZNS0_17div_constant_implIfEEvS5_T_EELj1EEFffEIfEEEEvS5_RKS9_+0x8a9)[0x7f404a7bd939]
[linux-ml:12736] [ 8] /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so(+0x243e3ba)[0x7f404a78f3ba]
[linux-ml:12736] [ 9] /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so(_ZN2at6native7div_outERNS_6TensorERKS1_S4_+0xcd)[0x7f403ec3e2cd]
[linux-ml:12736] [10] /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so(_ZN2at6native4div_ERNS_6TensorEN3c106ScalarE+0x35)[0x7f403ec3ed45]
[linux-ml:12736] [11] /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so(_ZNK2at11TypeDefault4div_ERNS_6TensorEN3c106ScalarE+0x60)[0x7f403ef475f0]
[linux-ml:12736] [12] /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so.1(_ZNK5torch8autograd12VariableType4div_ERN2at6TensorEN3c106ScalarE+0x2c1)[0x7f403d46e8a1]
[linux-ml:12736] [13] /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(+0x70444)[0x7f401d92c444]
[linux-ml:12736] [14] /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(+0x3fb1e)[0x7f401d8fbb1e]
[linux-ml:12736] [15] /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(+0x48862)[0x7f401d904862]
[linux-ml:12736] [16] /home/bfadmin/.local/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so(+0x4a95b)[0x7f401d90695b]
[linux-ml:12736] [17] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd57f)[0x7f409a4b157f]
[linux-ml:12736] [18] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f40a07d76db]
[linux-ml:12736] [19] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f40a0b1088f]
[linux-ml:12736] *** End of error message ***

**Comment by ezyang** [comment]
this issue is too old, we won't be able to debug it
