### ISSUE TITLE
Tensor unfold backward is slow

### ISSUE THREAD

**Issue by Coolnesss** [pytorch/pytorch#17501]
## 🐛 Bug

Given the following code, the forward pass is very fast but the backward pass is unreasonably slow. I had a look at the backward pass code and while I am not an expert, I think it could be made significantly faster by writing a custom kernel instead of allocating index arrays, especially since `index_add_` seems to be so slow.

```python
import torch
import time

layer = torch.nn.Conv2d(3, 1, 3)
inp = torch.rand(10, 3, 1000, 1000)

out = layer(inp)
c = 5

res = out.unfold(3, c, 1)
res.sum().backward()

```

```
--------------------------------------------------------------------------------
  Environment Summary
--------------------------------------------------------------------------------
PyTorch 1.0.0.dev20181221 not compiled w/ CUDA
Running with Python 3.6 and

`pip list` truncated output:
Unable to fetch
--------------------------------------------------------------------------------
  cProfile output
--------------------------------------------------------------------------------
         1983 function calls (1400 primitive calls) in 8.831 seconds

   Ordered by: internal time
   List reduced from 79 to 15 due to restriction <15>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    8.216    8.216    8.216    8.216 {method 'run_backward' of 'torch._C._EngineBase' objects}
        1    0.315    0.315    0.315    0.315 {built-in method conv2d}
        1    0.218    0.218    0.218    0.218 {built-in method rand}
        1    0.078    0.078    0.078    0.078 {method 'sum' of 'torch._C._TensorBase' objects}
    102/1    0.001    0.000    0.002    0.002 /anaconda3/lib/python3.6/abc.py:196(__subclasscheck__)
        1    0.000    0.000    0.001    0.001 /anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py:17(__init__)
        2    0.000    0.000    0.000    0.000 /anaconda3/lib/python3.6/site-packages/torch/nn/init.py:178(_calculate_fan_in_and_fan_out)
    98/30    0.000    0.000    0.001    0.000 /anaconda3/lib/python3.6/typing.py:1145(__subclasscheck__)
      202    0.000    0.000    0.000    0.000 /anaconda3/lib/python3.6/_weakrefset.py:70(__contains__)
        1    0.000    0.000    8.831    8.831 minimal.py:1(<module>)
        1    0.000    0.000    0.000    0.000 {method 'unfold' of 'torch._C._TensorBase' objects}
       85    0.000    0.000    0.000    0.000 /anaconda3/lib/python3.6/_weakrefset.py:58(__iter__)
    196/5    0.000    0.000    0.002    0.000 {built-in method builtins.issubclass}
       70    0.000    0.000    0.000    0.000 {method '__subclasses__' of 'type' objects}
       21    0.000    0.000    0.000    0.000 /anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py:537(__setattr__)


--------------------------------------------------------------------------------
  autograd profiler output (CPU mode)
--------------------------------------------------------------------------------
        top 15 events sorted by cpu_time_total

---------------------------------------  ---------------  ---------------  ---------------  ---------------  ---------------
Name                                            CPU time        CUDA time            Calls        CPU total       CUDA total
---------------------------------------  ---------------  ---------------  ---------------  ---------------  ---------------
UnfoldBackward                             7823869.000us          0.000us                1    7823869.000us          0.000us
index_add_                                 7222056.000us          0.000us                1    7222056.000us          0.000us
contiguous                                  370504.000us          0.000us                1     370504.000us          0.000us
clone                                       370501.000us          0.000us                1     370501.000us          0.000us
MkldnnConvolutionBackward                   257265.000us          0.000us                1     257265.000us          0.000us
mkldnn_convolution_backward                 257256.000us          0.000us                1     257256.000us          0.000us
mkldnn_convolution_backward_weights         257251.000us          0.000us                1     257251.000us          0.000us
conv2d                                      249499.000us          0.000us                1     249499.000us          0.000us
convolution                                 249495.000us          0.000us                1     249495.000us          0.000us
_convolution                                249494.000us          0.000us                1     249494.000us          0.000us
mkldnn_convolution                          249477.000us          0.000us                1     249477.000us          0.000us
contiguous                                  170065.000us          0.000us                1     170065.000us          0.000us
clone                                       170061.000us          0.000us                1     170061.000us          0.000us
sum                                          71872.000us          0.000us                1      71872.000us          0.000us
_th_arange                                   19876.000us          0.000us                1      19876.000us          0.000us
```

## To Reproduce

See code above

## Expected behavior

It should be faster

## Environment
Collecting environment information...
PyTorch version: 1.0.0.dev20181221
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.13.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.3                      1
[conda] mkl-service               1.1.2            py37h6b9c3cc_5
[conda] mkl_fft                   1.0.6            py36hb8a8100_0
[conda] mkl_random                1.0.1            py36h5d10147_1
[conda] pytorch                   1.0.0                   py3.6_1    pytorch
[conda] pytorch-nightly           1.0.0.dev20181221         py3.6_0    pytorch
[conda] torchaudio                0.2                       <pip>
[conda] torchtext                 0.3.1                     <pip>
[conda] torchvision               0.2.1                      py_2    pytorch
## Additional context

My real application needs `c=200` but it takes more than 10 minutes to run (i stopped at that point). Let me know if the same operation can be done more efficiently with some other method.

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @VitalyFedyunin @ngimel

**Comment by Coolnesss** [comment]
After testing on GPU, if I set the batch size low enough it runs very fast, but anything over 2 and it runs out of memory (8gb GPU). How would I go about debugging the memory usage?

**Comment by soumith** [comment]
the backward pass of an unfold will involved a lot of atomicAdd CUDA instructions in the unfolded dimension. That is what slows down the backward a lot.

**Comment by Coolnesss** [comment]
Hey @soumith, thanks for your reply.

I notice that on GPU the backward pass runs fast but runs out of memory quickly. Do you have any tips on how to check what exactly is being allocated during the backward pass? `nvprof` hangs indefinitely if I run it with `--track-memory-allocations on`.

**Comment by t-vi** [comment]
> Do you have any tips on how to check what exactly is being allocated during the backward pass
I'd look at the [source](https://github.com/pytorch/pytorch/blob/master/tools/autograd/templates/Functions.cpp#L640-L652)

I think a better strategy could be to formulate the backward in terms of "source locations", so you'd take a pixel location in the forward's input and sum the gradient entries of the stencil locations where the that input has been mapped to. That should be both relatively efficient in terms of computation (because there won't be conflicting adds) and not need any memory. As a bonus you remove the non-determinism that atomicAdd brings. The disadvantage is that you can't just use unfold to get the indices to add from but have to calculate them yourself, but in 1d that should not be too hard.

**Comment by Coolnesss** [comment]
Hey Thomas, thanks for your reply. 

> The disadvantage is that you can't just use unfold to get the indices to add from but have to calculate them yourself, but in 1d that should not be too hard.

I suppose to calculate the indices one can't just use a for loop in the gradient function, as that wouldn't run on GPU?

**Comment by t-vi** [comment]
Well, if you work out the for loop that iterates over "all output entries y that input entry x will map to in unfold", it's easy to write that for loop in a CUDA kernel and run it in parallel on all your input coordinates.
Let's think about that a moment: So you have at most `ceil(size / step)` entries that any input entry maps to. The first (if any) is at `y = x//step`. Now you have to check `y = x//step ... x//step + ceil(size / step)` whether `y*step <= x < y*step+size`, if it is, add the `gradient_out` at position `y` to the input at `x`. Parallelize using the usual `for (x = threadIdx.x+blockIdx.x ; x < size ; x+= blocksize.x + gridsize.x)` (or so, I forget), and there is the cuda kernel for the backward.
You'd need to double check the above for correctness. Also, I haven't thought about the double backward, through with a bit of luck it's unfold again.

**Comment by Coolnesss** [comment]
@t-vi I could try to make a PR out of this. Do you guys have a guide or some example on how to build PT with the improved backward pass? I've built an extension that uses CUDA using the extensions API, but I guess the process is different for actual internal code.

**Comment by t-vi** [comment]
Thanks!
My suggestion would be:
- You'd have to write a new ATen function `unfold_backward`, actually `unfold_backward_cpu` and `unfold_backward_cuda`, probably. You can test those in an extension (that's what I usually do).
Also, I'd write two autogradFunctions `UnfoldFn` and `UnfoldBackwardFn` to see if gradcheck and gradgradcheck (use `UnfoldBackwardFn.apply` and `UnfoldFn.apply` in the backwards) work.
- Maybe `aten/src/ATen/native/TensorTransformations.cpp` and `aten/src/ATen/native/cuda/TensorTransformations.cu` are good places for the function. Then add it to `native_functions.yaml` and edit `tools/autograd/derivatives.yaml` (and remove the old backward from `tools/autograd/templates/Functions.cpp`).
- See if you want new tests for it (e.g. test against the current torch_unfold ported back to Python in test/test_torch.py).

Does that make sense, approximately? Don't hesitate to post here if you need feedback or help (link to your git branch if you want to show code).

**Comment by Coolnesss** [comment]
Thanks for the pointers! I'll get to it by first making an extension and testing if it works against the current implementation.

**Comment by Coolnesss** [comment]
Hey, I've made some progress. I have some questions about how to proceed.

What I've done:
* Implemented the new CPU version in C++ for the case where the input is 1D. I've compared it to the existing version and it yields the same results in my tests.
* The algorithm is roughly 
   * Find the first occurence of the input element at index `i` in the output
   * Use some rules to find the next index `j` at which the element appears
   * Add the incoming gradient at index `j` to the outgoing gradient at index `i`

I plan to still:
* Get rid of division and modulo in the algorithm to make it faster
* Implement it in CUDA.

Questions:
* As far as I could tell, I need to know the dimensions of the data at compile time to be able to use accessors. I could create some sort of large if statement for the different input sizes, but it seems like a bad solution. Is there another way, or will I have to deal with strides, etc by using `.data()`?
* I'm a bit confused about the double backward part. Is there something specific that needs to be done in order to support it? Shouldn't it "just work" by calling backward twice?

Thanks for the help so far! Here is the code https://github.com/Coolnesss/unfold-backward/blob/master/unfold.cpp

**Comment by ezyang** [comment]
@Coolnesss awesome!

> As far as I could tell, I need to know the dimensions of the data at compile time to be able to use accessors. I could create some sort of large if statement for the different input sizes, but it seems like a bad solution. Is there another way, or will I have to deal with strides, etc by using .data()?

I'm not 100% familiar with the kernel you're writing. But if you're in a situation where you only care about indexing into, e.g., the last N dimensions (where N is constant), you can just reshape the tensor to have a fixed number of dimensions and then use accessor. Otherwise, you'll have to use one of our classes specifically for arbitrary dimension indexing (but I cannot remember the name right now)

> I'm a bit confused about the double backward part. Is there something specific that needs to be done in order to support it? Shouldn't it "just work" by calling backward twice?

If all operations in backwards are differentiable, it will just work. Otherwise, you'll need to write a derivative for the `unfold_backward` function you wrote.

**Comment by Coolnesss** [comment]
@t-vi, Now that I think about it, doesn't your method of calculating the indices by hand also involve atomicAdds when actually doing the addition? It occured to me that even if one calculates the indices by hand, there's a race condition when adding them since multiple indices of `grad` may point to a single index of `grad_input`. How does one deal with this, or have I misunderstood something?

**Comment by t-vi** [comment]
No, my proposal was to have all writes to one grad_input entry happen in the same thread. Then you don't need atomicAdd. So you'd parallelize over `i` and dimensions `!= dim`. Regarding the problem of Tesor-accessing the right thing: I guess you could either make the thing 3d (`reshape(everything_before_dim, dim, everything_after_dim)`) or do some offset manipulation for the other dimensions and just instantiate a 1-d tensor afterwards.

**Comment by Coolnesss** [comment]
I've made progress yet again. I have the CPU and CUDA implementations done, with the caveat that everything is for the 1D input case only. He's some preliminary benchmarks (on a single RTX 2070)

With the (arbitrarily chosen) parameters
```
input elements = 1e5
dim = 0
size = 10004
step = 3
```

Old backward:
20.4 ms ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
Peak memory usage 3.60 gb

New backward:
13.6 ms ± 15.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Peak memory usage 1.20 gb

Next up:
* I believe I will need some help in handling the N-D input case. In the actual CUDA kernel I will have to deal with strides etc myself so what is the best way of implementing this? Actually I'm not too sure how to calculate the gradient in this case.
* The double backward needs to be written. I guess I have to write another kernel, but do I also write another `torch.autograd.function`? How does this work in terms of the extension?

**Comment by t-vi** [comment]
Good job!
- For the N-D case in cuda, one thing you can do is to mimic what [OffsetCalculator](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cuda/detail/OffsetCalculator.cuh) does. Not in the sense of the actual computation, but pass in strides and sizes as arrays as fixed-size array (MAX_DIMS is 25 for OffsetCalculator). Then you can just multiply up the position from a linear index. (You could see if you can use OffsetCalculator itself for the initial offset. If not, the division-avoiding computation probably isn't as important.)
- I think you need to differentiate between 32 and 64 bit arithmetic. See e.g. batch norm for how to do that with ATen's utility function.
- I think the double backward is just fold again. To check this, define an `UnfoldBackwardFunction` and use that in the `FoldFunction` backward instead of calling unfold_backward directly. Then in the forward of the `UnfoldBackwardFunction` use the `unfold_backward` you have and in the backward use FoldFunction.apply again. Doing this consistently (i.e. making all indexing, looping use an `typename index_t` template parameter and specializing to int64_t or int32_t) might also give you a speed up in the 32bit case over mixing 32 and 64 bit indexing.

Later, you should probably change the checking etc to the C++ style of ATen.

**Comment by dangpzanco** [comment]
any update on this issue?

**Comment by ezyang** [comment]
paging @albanD who has been doing a lot of work on unfold recently

**Comment by nikitaved** [comment]
Any update? I could have a look at this one...

**Comment by albanD** [comment]
I don't think anyone is looking into this.
It most likely requires to write a specialized cuda kernel to replace the current implementation that call many different kernels.

**Comment by paplhjak** [comment]
I for one would appreciate it, as it would help tremendously with speed of training networks with spatially variant convolution kernels.

**Comment by nikitaved** [comment]
OK, them I will look into it as soon as I get time. Meanwhile, if someone interested, please, feel free to assign yourself!

**Comment by ngimel** [comment]
@paplhjak is it for cpu or gpu? Also it would be helpful if you provided some representative parameters for benchmarking.

**Comment by nikitaved** [comment]
All right, it seems like we have `floor((size - 1) / step)` overlaps. Hence it is easy to tell whether a CUDA index might have a potential overlap with any other index in any slice of size `size`, call it a "problematic" index if there is an overlap. My plan of attack is to leave everything to operate over 1D tensors, as it is right now, but replace `index_add` with a kernel which performs a simple add for "good" indices, and an atomic add for "problematic" indices. 
Do you agree with this approach? Could you please share you suggestions as to how to organize the code?

**Comment by nikitaved** [comment]
@Coolnesss , could you please share your benchmarking scripts for my own testing? Thank you!

**Comment by t-vi** [comment]
@nikitaved A long time ago (see the discussion above) my impression was that it'd be preferable to just parallelize over the `grad_in`, i.e. the have one thread process each backward kernel output (or several outputs in a for loop). That way you'd have many reads (hopefully hitting caching), but the minimal number of writes and no need for atomicAdd at all.

**Comment by nikitaved** [comment]
@t-vi , thank you for your comment! I agree with your approach and I will give it a try.
I would also like to see some generic use cases for this function, just to see what kind of overlap patters are expected.

**Comment by Coolnesss** [comment]
Hey guys, sorry for leaving this thing, I haven't had time to work on it for a while. 

@nikitaved here's the repository I made when I worked on this (https://github.com/Coolnesss/unfold-backward) there's a few benchmarks and some code as well. Hope it helps.

**Comment by nikitaved** [comment]
@Coolnesss, thank you! Just a quick question. From your repro script it follows that your use case assumes heavy overlap, right maybe just a couple entries shift)?

**Comment by nikitaved** [comment]
I have implemented the kernel for CUDA. It is still a bit raw and needs some polishing/optimization, but I can already benchmark. @Coolnesss , @paplhjak , could you please your use cases scripts?

**Comment by nikitaved** [comment]
@t-vi , do you know whether it is a common use case when `step > size`? If so, I think then we need to kernels. In such a case the parallelization over the `grad_in` (in your terminology) is not efficient.

**Comment by t-vi** [comment]
I don't know, people tend to have use cases beyond my imagination.
If you want, you could use a pattern where the threads each take of writing some zeros and then taking care of a potential non-zero. I think it should work well even if it complicates the block/grid layout calculation by a small bit.
I would likely try to have a single integrated kernel that covers both cases. Saves headache and you don't have to think of the decision which to use.

**Comment by nikitaved** [comment]
It will be a single kernel with a decision. It will complicate the code a bit because of slightly different strategies for the TensorIterator creation.

**Comment by nikitaved** [comment]
When I run the script from the header with `c=7` I get 
```
     15     res = out.unfold(3, c, 1)                                    
---> 16     res_sum = res.sum()                                          
     17                                                                  
     18     print(f"c={c}")                                              
                                                                        
RuntimeError: CUDA error: invalid configuration argument                 
```
The error is persistent in both version : master and [#36612](https://github.com/pytorch/pytorch/pull/36612).
Is that normal?

**Comment by ngimel** [comment]
Hm, no, that's definitely not normal. What is your GPU? Can you please run this script with CUDA_LAUNCH_BLOCKING=1? fwiw, I can run it on P100.

**Comment by nikitaved** [comment]
@ngimel , it is Quadro RTX 8000. Could you please try the following script?
```
import torch
from IPython import get_ipython

ipython = get_ipython()

torch.set_num_threads(1)


for c in [3, 4, 5, 6, 7]:
    layer = torch.nn.Conv2d(3, 1, 3).cuda()
    inp = torch.rand(100, 3, 100, 1000).cuda()

    out = layer(inp)

    res = out.unfold(3, c, 1)
    res_sum = res.sum()

    print(f"c={c}")
    ipython.magic("timeit res_sum.backward(retain_graph=True); torch.cuda.synchronize()")

```

**Comment by ngimel** [comment]
Yep, it does fail for me on c=6. Interestingly, when I run c=6 alone it passes.

**Comment by ngimel** [comment]
cc @zasdfgbnm for reduction configuration arguments. Note, the tensor is discontiguous self-overlapping, `size ([100, 1, 98, 992, 7]) stride (97804, 97804, 998, 1, 1) `

**Comment by ngimel** [comment]
@nikitaved to unblock you can do res_sum = res.contiguous().sum(), hopefully you won't get OOM, and we'll work on the fix.

**Comment by nikitaved** [comment]
I see consistent improvement over the original code thanks to the `__restricted__` key word. I hope it is justified to use it in here, since I am not sure anyone will ever use `unfold_backward` in forward, so that the pointer involved will never point to intersecting chunks of memory.

**Comment by nikitaved** [comment]
CPU results..
```python
import torch
from IPython import get_ipython

ipython = get_ipython()

#torch.set_num_threads(1)

layer = torch.nn.Conv2d(3, 1, 3)
inp = torch.rand(500, 3, 500, 500)

out = layer(inp)


for c in [3, 5, 7, 9, 11, 21]:
    res = out.unfold(3, c, 1)
    res_sum = res.contiguous().sum()

    print(f"c={c}")
    ipython.magic("timeit res_sum.backward(retain_graph=True)")

    del res

print()

for c in [3, 5, 7, 9, 11, 21]:
    res = out.unfold(3, c, c)
    res_sum = res.contiguous().sum()

    print(f"c={c}")
    ipython.magic("timeit res_sum.backward(retain_graph=True)")

    del res

```

### Before
```
c=3
18 s ± 290 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=5
27.2 s ± 496 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=7
36.9 s ± 1 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=9
45.9 s ± 914 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=11
55.1 s ± 842 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=21
1min 41s ± 843 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

c=3
8.51 s ± 110 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=5
8.55 s ± 59.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=7
8.55 s ± 18.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=9
8.7 s ± 79.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=11
8.51 s ± 39.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=21
8.43 s ± 53.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
### After
```
c=3
4.18 s ± 142 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=5
4.37 s ± 112 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=7
4.37 s ± 118 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=9
4.39 s ± 141 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=11
4.46 s ± 103 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=21
5.03 s ± 131 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

c=3
4.05 s ± 117 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=5
4.02 s ± 121 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=7
4.03 s ± 93.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=9
4.11 s ± 89.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=11
4.04 s ± 113 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
c=21
3.96 s ± 73.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```

**Comment by nikitaved** [comment]
@ngimel , was the issue detected fixed? If so, then it also improves the performance. The testing time reduced from 5 mins to 1 min!

**Comment by ngimel** [comment]
No, the issue with reductions is not fixed yet. Probably res.contiguous().sum() is faster than res.sum().

**Comment by nikitaved** [comment]
Could be, but the tests I am talking about are the ones generated by the autograd in `torch/testing/_internal/common_methods_invocations.py`. Now they are considerably faster, which is good :)

**Comment by rgommers** [comment]
This was fixed by gh-36612, closing.
