### ISSUE TITLE
Conda did not install cudnn for pytorch

### ISSUE THREAD

**Issue by BigBigWolf-AI** [pytorch/pytorch#17500]
OS: ubuntu 16.04(only installed the graphic card driver, has not install cuda and cudnn)
pytorch version: 1.0.1
Hi,
I use the following command to install pytorch:

_**conda install pytorch torchvision cudatoolkit=10.0 -c pytorch**_

then I use the command **_conda list_** to list the packages that have been installed with pytorch, I found the cudatoolkit but I did not found the cudnn, why? the pytorch do not need the cudnn ?
when I install tensorflow gpu version using the _**conda install**_ command , the cudnn and cudatoolkit are both installed. Why pytorch only need cudatoolkit?

**Comment by RicCu** [comment]
Hi,
even if it's not listed explicitly with `conda list`, your installation should have cudnn. You can check if this is the case executing `torch.backends.cudnn.is_available()`.

**Comment by soumith** [comment]
@BigBigWolf-AI I repeatedly have asked you to use the forums for questions, and yet you keep opening new issues. Redirect all questions to https://discuss.pytorch.org
