### ISSUE TITLE
Accept 0-dimensional tensors with t()

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#17520]
## 🚀 Feature

https://github.com/pytorch/pytorch/pull/17462 made the nice improvement of accepting 1-dimensional tensors with the `t` function.  But there's no reason the same couldn't be done for 0-dimensional tensors, as numpy supports it as well:

```
>>>np.zeros(()).T
array(0.)
```

**Comment by bhushan23** [comment]
sounds good.
@gchanan just to clear, 0-d tensor support only for dense tensors, right?
We don't (can't) have 0-d for sparse.

**Comment by gchanan** [comment]
@bhushan23 you can do 0-d for sparse:

```
>>> torch.empty((), layout=torch.sparse_coo)
tensor(indices=tensor([], size=(0, 0)),
       values=tensor([], size=(0,)),
       size=(), nnz=0, layout=torch.sparse_coo)
```

**Comment by bhushan23** [comment]
thanks @gchanan .
Handling sparse tensors too.
