### ISSUE TITLE
Cannot initial from_blob from std::vector.data()

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#17537]
## To Reproduce

```
torch::Tensor some_function()
{
    std::vector<int> overall_indices;
    // .... fill the vector
    torch::TensorOptions opts(torch::kInt);
    auto t = torch::from_blob(overall_indices.data(), {n, 3}, opts);
    return t
}
```

I end up getting giberrish tensor returned from this function. Once the function returns to Python
```
some_function()
-> tensor([[         5,          0,          0],
        [         0, 1040267192,          0],
        [-966454432,      32681,          1],
        [         4,          0,          0]]```

**Comment by t-vi** [comment]
This is documented behaviour:
https://pytorch.org/cppdocs/api/function_namespacetorch_1aff6f8e6185457b2b67a1a9f292effe6b.html?#_CPPv4N5torch9from_blobEPvN2at11IntArrayRefERKN2at13TensorOptionsE

I'm not an expert, but I take that [it's not possible to acquire the data ownership from a vector](https://stackoverflow.com/questions/22576858/is-there-a-way-to-move-data-from-a-vector-to-a-dynamic-array).

**Comment by sidazhang** [comment]
Question 1:

Is the only solution to do a .clone()

Question 2:

Is there a way to build push_back to a tensor, just like a vector
```
std::vector<int> overall_indices;

// push back into the std::vector unknown number of times
overall_indices.push_back(0);
torch::from_blob(overall_indices.data(), {n, 3}, opts);
```

For example
```
torch::Tensor overall_indices_tensor;

// push back into the the tensor unknown number of times
overall_indices_tensor.push_back(0); 
```

**Comment by t-vi** [comment]
1. Yes.
2. No. If you know the (maximal) size, get an empty tensor. What vector does internally is to realloc and copy as needed, so you could do that if you have to.

Am 27. Februar 2019 16:29:02 MEZ schrieb sidazhang <notifications@github.com>:

**Comment by t-vi** [comment]
If you absolutey wanted some fancy thing, you could allocate an object (with "new") that takes the container and uses dlpack with a deleter to free itself. Then you can unpack the dlpack into a Tensor because the dlpack-created Tensor takes ownership of the memory. That said, `.clone` surely is the right solution except very special cases.
