### ISSUE TITLE
Can not import torch on Python3 Ubuntu18.04

### ISSUE THREAD

**Issue by engineer1109** [pytorch/pytorch#17541]
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 97, in <module>
    from torch._C import *
ImportError: /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so.1: undefined symbol: _ZN10onnx_torch30_TensorProto_default_instance_E

```

 - PyTorch Version 1.0  the lastest git
 - Ubuntu 18.04
 - build by source python3 setup.py install
 - Python version: 3.6
 - CUDA/cuDNN version:  10.0/7.4

**Comment by soumith** [comment]
you have an old version of pytorch that is being loaded first. try cleaning up all other versions of pytorch or caffe2.
