### ISSUE TITLE
Moving pytorch to anaconda.org CDN

### ISSUE THREAD

**Issue by msarahan** [pytorch/pytorch#17546]
Greetings from the Anaconda team.  In an effort to reduce the load on our anaconda.org servers, we'd like to shift your channel over to our CDN.  Here are the implications:

1. Only the "main" label would be on the CDN.
2. Packages on the CDN will have a delay in availability from when they are uploaded, and when the next mirroring/indexing operation happens.  We would try for scheduling those every 20 minutes, but we can't make any sort of service level promise.
3. Packages on the CDN should have much faster download speeds, especially for people who are further from the US East Coast.
4. CDN-enabled channels will benefit from the new package format, while other anaconda.org channels will not, because anaconda.org does not support the new format yet.  This is more of a near-future benefit, rather than a current benefit.
5. You would gain the ability to hotfix your repodata to fix old packages with bad metadata.

Conda-forge has been on the CDN for several months now.  Things seem to be mostly OK for them.

Is this OK with your community?  If so, is there a convenient time for making the switch?  There were a few small hiccups with conda-forge, but it should be smoother now.  Nevertheless, planning for some small potential disruption would be wise.

**Comment by soumith** [comment]
Hi Mike,

This sounds great. All 5 points look good, and (5) seems like a godsend :)

This is completely okay with our community.

Thanks!
