### ISSUE TITLE
Docs for torch.nonzero do not mention if returned indices are sorted row-major

### ISSUE THREAD

**Issue by jhultman** [pytorch/pytorch#17556]
## 📚 Documentation

Hi. Thanks for the great library. I have a short example below detailing my question. I couldn't find any info about this in the docs or on the pytorch forums.

```
import torch
import numpy as np
torch.manual_seed(21)

A = (torch.rand(10, 10, 10) > 0.9)
i, j, k = A.nonzero().t()
ijk = torch.stack((i, j, k), dim=1).numpy()
inds = np.lexsort(ijk[:, ::-1].T)
ijk_sorted = ijk[inds]

print((ijk == ijk_sorted).all())
>> True
```

I was just wondering if this behavior is guaranteed by the API? I would like to depend on the lexicographic ordering in my application without paying for an additional sort. Numpy's documentation for the corresponding `numpy.nonzero` mentions that "The values are always tested and returned in row-major, C-style order." Maybe a similar blurb could be added to the torch docs? Hope my question makes sense.

**Comment by jhultman** [comment]
Just wondering if anyone has had a chance to review this. I think it would be a useful addition to the documentation (if it's true).

**Comment by ezyang** [comment]
I'm OK with committing to this. Send in a PR.

**Comment by jhultman** [comment]
@ezyang I don't see any unit tests guaranteeing this behavior in `test/test_torch.py` but maybe I am looking in the wrong place. I think it would be nice to have such a test in case the implementation of nonzero were to change in the future. What do you think?

**Comment by ezyang** [comment]
Yes please!

**Comment by jhultman** [comment]
Ok, I will put together a PR. Thanks!
