### ISSUE TITLE
Add a torch.matmul function and document broadcast behavior of it and delegated functions

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#1756]
See https://github.com/pytorch/pytorch/pull/1563#discussion_r120843916 for context.

This will include the following changes:
1) Expose a torch.matmul function with semantics of __matmul__ as of PR https://github.com/pytorch/pytorch/pull/1563.
2) Document above torch.matmul function, including broadcast behavior.
3) Document that the following functions do not broadcast:
torch.mm
torch.mv
torch.bmm
torch.dot (this function does flatten)
torch.ger (this function does not flatten or broadcast).

**Comment by apaszke** [comment]
I think we should also disallow flattening in `torch.dot`. It's not really expected, especially if you're used to numpy

**Comment by apaszke** [comment]
adding it to cwrap sounds ok to me. You can use `before_call` to do additional checks and possibly return with an error

**Comment by gchanan** [comment]
that was my initial thought, but I didn't want to drop code straight in `before_call` because it complicates other (potential) backends.  I think I'll just add another plugin or make it part of the broadcast plugin.

**Comment by apaszke** [comment]
what backends do you have in mind?

**Comment by gchanan** [comment]
e.g. https://github.com/zdevito/pytorch/tree/master/torch/lib/TensorLib -- maybe it would work in this specific case (I honestly don't know), but it seems like dropping code directly in the cwrap would make this difficult generally.

**Comment by njin19** [comment]
Has matmul been released yet? I get this error when trying to use it:
module 'torch' has no attribute 'matmul'
although I see it in the documentation here 
http://pytorch.org/docs/master/torch.html?highlight=matmul#torch.matmul 

Thank you!

**Comment by fmassa** [comment]
Yes, `matmul` is present in master and in v0.2
