### ISSUE TITLE
Please test and add the AdaBound optimizer into the next stable release

### ISSUE THREAD

**Issue by xuancong84** [pytorch/pytorch#17560]
Now we have another powerful general purpose optimizer called AdaBound that trains as fast as Adam and as good as SGD, see [https://github.com/Luolc/AdaBound](https://github.com/Luolc/AdaBound).

It appears to work better than Adam in several tasks including NLP and CV, with slightly higher accuracy and smoothier learning curve.

![image](https://user-images.githubusercontent.com/10172392/53534724-08e75b80-3b3b-11e9-87b7-debe21b3908e.png)

I think this would be a great and useful addition, thanks!

**Comment by vishwakftw** [comment]
New implementations such as these can go into pytorch/contrib initially.

**Comment by kayuksel** [comment]
I also agree with the request of adding AdaBound optimizer to contrib.

**Comment by soumith** [comment]
I'd agree, send a PR to https://github.com/pytorch/contrib with unit tests, I'm happy to merge
