### ISSUE TITLE
pytorch/third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.1.20180928/lib/libmklml_intel.so: file not recognized: File truncated

### ISSUE THREAD

**Issue by Adhders** [pytorch/pytorch#17573]
my system config is linux 18.04 ,python 3.6 ,cudn 10.0
Building wheel torch-1.1.0a0+6706e9a
-- Building version 1.1.0a0+6706e9a
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
  File "setup.py", line 710, in <module>
    build_deps()
  File "setup.py", line 282, in build_deps
    build_dir='build')
  File "/u01/package/pytorch/tools/build_pytorch_libs.py", line 255, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/u01/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '32', 'install']' returned non-zero exit status 2.

**Comment by helloworld77** [comment]
Same with @Adhders , and my system is ubuntu16.04, python2.7, cuda10.0, head: 80927fc068
pytorch/third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.1.20180928/lib/libmklml_intel.so: file not recognized: File truncated
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/caffe2.dir/build.make:19170: recipe for target 'lib/libcaffe2.so' failed
make[2]: *** [lib/libcaffe2.so] Error 1
CMakeFiles/Makefile2:5889: recipe for target 'caffe2/CMakeFiles/caffe2.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 710, in <module>
    build_deps()
  File "setup.py", line 282, in build_deps
    build_dir='build')
  File "pytorch/tools/build_pytorch_libs.py", line 255, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '32', 'install']' returned non-zero exit status 2

**Comment by helloworld77** [comment]
I have solved my problem by moving the pytorch in the right path. 
I downloaded pytorch on a cloud server, because it faster, and then scp back to my local computer, since I put the same path as the cloud server, the problem was sovled.

**Comment by 2name** [comment]
@Adhders  I meet the same error,have you solved it? I'm looking forward to your reply,thanks.

**Comment by Adhders** [comment]
> @Adhders I meet the same error,have you solved it? I'm looking forward to your reply,thanks.

you can install pytorch through  the official website https://pytorch.org/get-started/locally/. It's very easy to install pytorch , just one step !

**Comment by 2name** [comment]
@Adhders 
Hi,I think I solved it.
just download pytorch again.
