### ISSUE TITLE
[ci] Docs build should fail if there are warnings

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#17575]
This would have caught https://github.com/pytorch/pytorch/issues/17574

cc @malfet @seemethere @walterddr @brianjo @mruberry

**Comment by ezyang** [comment]
@zou3519 do you know if this got fixed in the meantime?

**Comment by zou3519** [comment]
This indeed has been fixed. Let me go fish up the commit and then we can close this

**Comment by zou3519** [comment]
https://github.com/pytorch/pytorch/pull/41335 fixes this (thanks @mattip!)
