### ISSUE TITLE
NLLLoss reduce default is wrong

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#17577]
## 📚 Documentation

There are 3 parameters documented that all try to solve the same problem: `size_average`, `reduce`, `reduction`.  It's fine to document legacy behavior, but IMO it should be done after the non-legacy behavior has been explained concisely.

Also, some of the documentation is just wrong.  For example:
`If reduce is True (default)`

but the default of `reduce` is `None`.

Also:
` ‘mean’: the sum of the output will be divided by the number of elements in the output`

But as shown in the formula above, it's divided by `weight[targets].sum()`.

cc @brianjo @mruberry @albanD @jbschlosser

**Comment by krishnakalyan3** [comment]
I would like to work on this will send a PR shortly.

**Comment by vishwakftw** [comment]
Does https://github.com/pytorch/pytorch/pull/17300 resolve this issue?

**Comment by ezyang** [comment]
> but the default of reduce is None.

still needs to be fixed

everything else is fixed
