### ISSUE TITLE
torch.broadcast_tensors not rendering correctly

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#17574]
## 📚 Documentation

https://pytorch.org/docs/master/torch.html#torch.broadcast_tensors
![image](https://user-images.githubusercontent.com/5652049/53575547-ca07d480-3b3f-11e9-909d-7eed4e667c07.png)

`_broadcasting-semantics` should be a link to our broadcasting semantics page, but it is not rendered correctly.

**Comment by vishwakftw** [comment]
Closed by #17642.
