### ISSUE TITLE
jit.trace with tensor reference that requires grad

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#17583]
## 🐛 Bug

This used to work, until https://github.com/pytorch/pytorch/commit/1aa90192eae306e4375c68f12f46eb329042e07d. Even if this isn't supported anymore, it shouldn't trigger an `AT_ASSERT`. And I think this should be supported.

cc @yf225 .

```py
In [19]: import torch
    ...:
    ...: param = torch.randn(3).requires_grad_()
    ...: x = torch.randn(3)
    ...:
    ...: def f(x):
    ...:     return x + param
    ...:
    ...: torch.jit.trace(f, x)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-28f3b094f9e7> in <module>
      7     return x + param
      8
----> 9 torch.jit.trace(f, x)

~/miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py in trace(func, example_inputs, optimize, check_trace, check_inputs, check_t
olerance, _force_outplace)
    654     var_lookup_fn = _create_interpreter_name_lookup_fn(0)
    655     module._create_method_from_trace('forward', func, example_inputs,
--> 656                                      var_lookup_fn, _force_outplace)
    657
    658     # Check the trace against new traces created from user-specified inputs

<ipython-input-19-28f3b094f9e7> in f(x)
      5
      6 def f(x):
----> 7     return x + param
      8
      9 torch.jit.trace(f, x)

RuntimeError: !ref.requires_grad() ASSERT FAILED at ../torch/csrc/jit/constants.cpp:28, please report a bug to PyTorch.
```

**Comment by eellison** [comment]
@zdevito @apaszke  @jamesr66a  

I'm not that familiar with tracer - do you think this should be supported behavior or that a better error msg should be provided here ?

**Comment by zdevito** [comment]
Error message should be better but it should probably stay an error.

**Comment by SsnL** [comment]
@zdevito may I ask why? Tracing a Module already supports similar semantics, and sometimes it's nice to not have all leaves in function inputs, and not have the graph represented as a module. E.g., consider I have a deep net as a Module, and have a method that computes the singular values of the conv weights, what should I do if I want to trace that method?

**Comment by apaszke** [comment]
@SsnL because when you trace a module we add all parameters as graph inputs, so they can potentially change between calls. If we were to allow closing over tensors that require grad it means that they would get embedded into the graph as constants, which is almost certainly not what you want (you can't e.g. move them to a different device). Constants are generally quite flawed and I would even be ok with forbidding them altogether (they all suffer from the device issue).

**Comment by SsnL** [comment]
@apaszke I understand all these. So what do you suggest one do in the scenario I described?

**Comment by SsnL** [comment]
@apaszke @zdevito If there is not a good solution for the scenario I described, alternatively, can we support tracing a function with a module as an input?

**Comment by apaszke** [comment]
@SsnL we could, but we would need to support function calls, which we don't. So it's not that easy to have.

**Comment by SsnL** [comment]
So we just killed support for a valid use case without any alternative planned...

**Comment by apaszke** [comment]
> valid use case
Validity (or usability for that matter) of this use case is unclear, and we never even wanted to allow that. It was a bug on our side, and we can't do anything with the fact that some users started to depend on buggy behavior.

**Comment by SsnL** [comment]
@apaszke Ah yeah I understand more about this scenario. So I should probably make this more like a feature request to support such things. 

Out of curiosity, could you explain more the difficulty of supporting passing in a Module? I think we can treat that the same way as passing in collections of parameters and buffers. It is hard to make traced function get those tensors?

**Comment by eellison** [comment]
Close with https://github.com/pytorch/pytorch/pull/18535
