### ISSUE TITLE
[Feature Request] Make dataset support __add__

### ISSUE THREAD

**Issue by acgtyrant** [pytorch/pytorch#1759]
I want to concat the PASCAL VOC 2007 train dataset and PASCAL VOC 2007 val dataset, but COCO only offer two individual JSON for them. I have to create two dataset instances for them and concate them.

However, `itertools.chain` does not work while it does not have `__len__` method. So I have to use [a wrapper class](https://discuss.pytorch.org/t/combine-concat-dataset-instances/1184?u=acgtyrant) to concate them.

If dataset class support `__add__`, then it is so convenient that we can use `trainval_dataset = train_dataset + val_dataset` immediately.

If you agree, I will make the pull request later.

**Comment by fmassa** [comment]
I think you want to use [`tnt.ConcatDataset`](https://github.com/pytorch/tnt/blob/master/torchnet/dataset/concatdataset.py).
We should port some functionalities from `tnt` to core pytorch, `ConcatDataset` should probably be one of them (but it depends on numpy, while pytorch doesn't, so we should probably rewrite some bits of it).

**Comment by esc** [comment]
The `np.cumsum` should be easy enough to replace. `__add__`  could return a `ConcatDataset` with both added.

**Comment by esc** [comment]
Oh `searchsorted` too..

**Comment by esc** [comment]
I started porting the code across but will need some feedback, @fmassa perhaps?

**Comment by fmassa** [comment]
@esc there are some feedback in the PR you opened.

**Comment by esc** [comment]
Thanks, I am on the case.

**Comment by esc** [comment]
Solved by #1902 please close.
