### ISSUE TITLE
Deadlock when running dataloader tests for ChunkDataSet on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#17609]
Sample build log:
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test2/24028/console

Known tests that will cause the deadlock are:
```
DataLoaderTest.ChunkDataSetGetBatch
DataLoaderTest.ChunkDataSetWithEmptyBatch
```

It needs further investigation.

**Comment by yf225** [comment]
cc @xzhu1900 Can you help with debugging this problem?

**Comment by xzhu1900** [comment]
Thanks @yf225. Be happy to take a look.

A few questions:
The last change made to ChunkDataset was 9 days ago, but the test was failing 4 days ago. Were the windows tests just got enabled 4 days ago? Is this the first time seeing this issue? Also, what is the timestamp of this build? Does this build include this fix: https://github.com/pytorch/pytorch/pull/17409 ?

**Comment by peterjc123** [comment]
> Were the windows tests just got enabled 4 days ago?

No, the windows tests are not enabled even now. We just attempt to turn them on in this PR https://github.com/pytorch/pytorch/pull/17102.

> Is this the first time seeing this issue? 

Yes, it didn't happen on other datasets. But it's not a flaky test, because it causes the deadlock every time we run the tests.

> Also, what is the timestamp of this build? Does this build include this fix: #17409 ?

Don't worry. We can do a rebase on #17102 and see it occurs on the latest master.

**Comment by peterjc123** [comment]
@xzhu1900 Have done the rebase on #17102, but the deadlock continues.

**Comment by xzhu1900** [comment]
Thanks @peterjc123. 

I am looking into this. Currently I am working on getting pyTorch build on my windows machine. I will update this thread after I find anything.

**Comment by xzhu1900** [comment]
After successfully build pytorch in windows, I can repro this issue locally. The fix is currently in PR (https://github.com/pytorch/pytorch/pull/17778) for code review. 
Thanks!

**Comment by peterjc123** [comment]
@xzhu1900 Thank you so much. I'll try to let it go through all the tests.

**Comment by xzhu1900** [comment]
Thanks @peterjc123 for verifying this 😃

**Comment by xzhu1900** [comment]
The fix is merged into master.
