### ISSUE TITLE
ONNX exporter for slice operation isses onnx:Slice for dimensions that are not sliced, includiung batch dimension - which breaks TRT5 

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#17606]
## 🐛 Bug

Here, PyTorch ONNX exporter translates slice operation into a series of onnx:Slice() operation for all dimensions, including those not being sliced on:

    audio = z[:, :self.n_remaining_channels, :]
    z = z[:, self.n_remaining_channels:, :]   
....
 %649 : Float(1, 8, 1376, 1) = onnx::Slice[axes=[0], ends=[9223372036854775807], starts=[0]](%1), scope: WaveGlow
  %650 : Float(1!, 4, 1376, 1) = onnx::Slice[axes=[1], ends=[4], starts=[0]](%649), scope: WaveGlow
  %651 : Float(1!, 4, 1376, 1) = onnx::Slice[axes=[2], ends=[9223372036854775807], starts=[0]](%650), scope: WaveGlow
  %652 : Float(1!, 4, 1376, 1) = onnx::Slice[axes=[3], ends=[9223372036854775807], starts=[0]](%651), scope: WaveGlow

As you can see, Pytorch straightforwardly translates every ":" in slice operation into a real Slice() operation for (0,Inf) for that dimension - when it should have been a pass-through (no-op).

Would not be such a big deal, if it weren't doing it for dim=0 (batch dimension) as well - TRT parser crashes on that:

bfomitchev@bfomitchev-dt:~/git/gtc/waveglow$ onnx2trt -o glow.engine -b 1 -w 8000000000 -d 32 -l -vvvvv wave32.onnx
Parsing model
ERROR: builtin_op_importers.cpp:2005 In function importSlice:
[8] Assertion failed: std::find(axes.begin(), axes.end(), BATCH_DIM) == axes.end()

## To Reproduce

1.
1.
1.

## Expected behavior

Would like exporter to optimize out clearly unnecessary Slice operations
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): latest nightly build
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by houseroad** [comment]
Yeah, we should be able to do some optimization here: https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L1334

**Comment by borisfom** [comment]
@houseroad : any ETA on this ?

**Comment by houseroad** [comment]
Try https://github.com/pytorch/pytorch/pull/19155 :-)

**Comment by gottbrath** [comment]
So .. did 19155 work for this?

**Comment by borisfom** [comment]
@gottbrath : well, it fixed most of those occurences. I was still not able to import WaveGlow into TRT without corresponding fix (optimizing out unneeded Slice() ops) on TRT side though.

**Comment by houseroad** [comment]
@borisfom could you provide some snippet for repro? So I can dig and fix it

**Comment by borisfom** [comment]
Looks like it's not an issue with latest TRT6 and parser, so we can close it.
