### ISSUE TITLE
Sharing/Transferring gradients from models across multiple GPU(s) in multiprocessing

### ISSUE THREAD

**Issue by kayuksel** [pytorch/pytorch#17613]
## 🚀 Feature

Currently, I am following the [hogwild] (http://pytorch.org/docs/master/notes/multiprocessing.html#hogwild 18) example to run the asynchronous training. The shared model within the example is in the CPU. The local model is on the GPU and has their own or shared optimizer. Each local model can update the shared model directly. I want to modify the current case to the synchronous version. For example, each local model can upload their gradients to the shared model. After aggregating gradients from multiprocesses, the shared model can be updated, which I have managed to do that with a single GPU. However, I have faced problems while trying to copy or add gradients from local models across processes that are working on different GPU(s) to the shared model. I believe PyTorch lacks the way of doing that; hence I created this issue of a feature request. Otherwise, I would welcome if you can enlighten me about how that can be possible.

**Comment by soumith** [comment]
https://github.com/pytorch/examples/tree/master/mnist_hogwild now supports GPUs. We do support multiprocessing + IPC handles, so there's no issue in doing what you describe afaik.

If you cant do that because of a particular bug, please feel free to reopen the issue describing what error or bug you encounter

**Comment by subho406** [comment]
> https://github.com/pytorch/examples/tree/master/mnist_hogwild now supports GPUs. We do support multiprocessing + IPC handles, so there's no issue in doing what you describe afaik.
> 
> If you cant do that because of a particular bug, please feel free to reopen the issue describing what error or bug you encounter

The MNIST Hogwild is not working on Pytorch 1.0.0. Running on 1.0.0 gives:
`
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    mp.set_start_method('spawn')
  File "/home/metal_geek/anaconda3/envs/omninet/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
`

**Comment by soumith** [comment]
@subho406 seems to work fine for me (with 1.1.0 and the latest `examples` repo), just fyi

**Comment by subho406** [comment]
Yes, was fixed onwards pytorch 1.0.1. Thanks
