### ISSUE TITLE
wrong notations as markdown of jupyter notebooks in tutorials

### ISSUE THREAD

**Issue by eduidl** [pytorch/pytorch#17635]
Jupyter notebooks which can be downloaded at tutorial pages (ex. https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html) contain wrong notations as described below.

```
Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically
```

This is rendered on jupyter notebook as below.

![image](https://user-images.githubusercontent.com/25898373/53683913-06a71c00-3d4a-11e9-8cfa-d36146729862.png)

`###` can be used instead, I think.

Example: https://pytorch.org/tutorials/_downloads/3c2b25b8a9f72db7780a6bf9b5fc9f62/tensor_tutorial.ipynb

Regards.

**Comment by yf225** [comment]
cc @brianjo

**Comment by zou3519** [comment]
This doesn't seem applicable anymore
