### ISSUE TITLE
Download error with CIFAR10/Mnist based on torchvision.datasets

### ISSUE THREAD

**Issue by YunchuZhang** [pytorch/pytorch#17633]
## To Reproduce

1.
1.
1.

import torch
import torchvision
import torchvision.transforms as transforms
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

(.env) zycdeMBP:Downloads zyc$ python3 testtorch.py 
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar-10-python.tar.gz
Traceback (most recent call last):
  File "testtorch.py", line 9, in <module>
    download=True, transform=transform)
  File "/Users/zyc/Downloads/.env/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 63, in __init__
    self.download()
  File "/Users/zyc/Downloads/.env/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 150, in download
    download_url(self.url, self.root, self.filename, self.tgz_md5)
  File "/Users/zyc/Downloads/.env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 73, in download_url
    reporthook=gen_bar_updater(tqdm())
TypeError: __init__() missing 1 required positional argument: 'total'

## Environment
Mac OS python3.7
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by surgan12** [comment]
This issue should be opened here https://github.com/pytorch/vision/issues.

**Comment by vishwakftw** [comment]
See @surgan12's reply.
