### ISSUE TITLE
jupyter kernel died at division

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#17646]
## To Reproduce

```
import torch

x = torch.arange(end=2)
print(x / 0.1)
```

## Expected behavior

The kernel dies.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.0
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
[conda] mkl                       2018.0.3                      1  
[conda] mkl-service               1.1.2                    py36_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
[conda] pytorch                   1.0.0                   py3.6_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by surgan12** [comment]
This is probably due to division by 0 due to conversion of 0.1 to 0.

**Comment by youkaichao** [comment]
@surgan12  yeah, I think you are right. But why not throw a `ZeroDivisionError`?

**Comment by vadimkantorov** [comment]
(also tracked in https://github.com/pytorch/pytorch/issues/6196 )

**Comment by mruberry** [comment]
This no longer occurs as of PyTorch 1.7 because of type promotion. Switching the division to be floor division will throw a ZeroDivisionError as expected.
