### ISSUE TITLE
I want to know how to use the  select(int64_t dim, int64_t index) in at::Tensor?What is the definition of a parameter ?

### ISSUE THREAD

**Issue by SongyiGao** [pytorch/pytorch#17654]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by SsnL** [comment]
it's selecting a slice at a certain index of a certain dimension
