### ISSUE TITLE
torch.arange dtype mismatch with and without jit

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#17662]
```python
import torch

def f():
    return torch.arange(5)

print(f().dtype)
print(torch.jit.script(f)().dtype)
```

prints

```
torch.int64
torch.float32
```

**Comment by suo** [comment]
thanks, we'll look into this!

**Comment by Krovatkin** [comment]
I'll look into it.

**Comment by cpuhrsch** [comment]
@Krovatkin, the PR actually does not add support for this. We merely add syntactic sugar on our way towards schema unification. That means we apply a reverse splat that leads to the same argument (e.g. TensorOptions options) as before. There are many more components we need to get rid off before this works. 

Until then, you can apply the following patch after my PR lands

```
diff --git a/aten/src/ATen/native/native_functions.yaml b/aten/src/ATen/native/native_functions.yaml
index 517b720b4..0154bf51a 100644
--- a/aten/src/ATen/native/native_functions.yaml
+++ b/aten/src/ATen/native/native_functions.yaml
@@ -215,14 +215,11 @@
 - func: any(Tensor self, int dim, bool keepdim=False, *, Tensor(a!) out) -> Tensor(a!)
   matches_jit_signature: True

-- func: arange(Scalar end, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None) -> Tensor
-  matches_jit_signature: True
+- func: arange(Scalar end, *, TensorOptions options=at::kLong) -> Tensor

-- func: arange(Scalar start, Scalar end, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None) -> Tensor
-  matches_jit_signature: True
+- func: arange(Scalar start, Scalar end, *, TensorOptions options=at::kLong) -> Tensor

-- func: arange(Scalar start, Scalar end, Scalar step, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None) -> Tensor
-  matches_jit_signature: True
+- func: arange(Scalar start, Scalar end, Scalar step, *, TensorOptions options=at::kLong) -> Tensor

 - func: arange(Scalar end, *, Tensor(a!) out) -> Tensor(a!)
   matches_jit_signature: True
```

This will then yield the following output

```
$ python /tmp/asdf1.py
torch.int64
torch.int64
```

I can include this update to arange in an upcoming PR.

**Comment by cpuhrsch** [comment]
Ignore my previous comment (deleted). cc @gchanan for a more detailed insight.

**Comment by gchanan** [comment]
@suo I don't think this is really a JIT issue.  The issue is that the dtype inference is done at the PyTorch eager layer, not in ATen.  So independent of binding considerations, there's no way for the JIT to access this functionality and to get equivalent behavior it would have to reimplement the inference, which seems pointless.

Instead we should just move the logic to ATen -- this wasn't possible in the past when we didn't have optional TensorOptions, but we do now.

**Comment by eellison** [comment]
@gchanan I ran into this issue with `randint` as well - I assume for the same reason ?

**Comment by gchanan** [comment]
@eellison yes, I believe so.

**Comment by eellison** [comment]
What is the next steps on this ? @gchanan @Krovatkin ? 

I just ran into this bug. I think we should try to prioritize bugs that silently give the wrong semantics.

**Comment by gchanan** [comment]
@eellison I wrote the next step above:
"Instead we should just move the (type inference) logic to ATen -- this wasn't possible in the past when we didn't have optional TensorOptions, but we do now."

Want to take it up? :).

**Comment by eellison** [comment]
> @eellison I wrote the next step above:
> "Instead we should just move the (type inference) logic to ATen -- this wasn't possible in the past when we didn't have optional TensorOptions, but we do now."
> 
> Want to take it up? :).

Yep i'll take it
