### ISSUE TITLE
Buggy comment

### ISSUE THREAD

**Issue by danpovey** [pytorch/pytorch#17663]
The line below looks like a typo.
(could not do `reference in new issue` as that functionality seems to not work here).

https://github.com/pytorch/pytorch/blob/dec116e96f4af069c8c6568e8f01202a3cafc412/torch/csrc/autograd/variable.h#L233

**Comment by bhushan23** [comment]
No buggy as such but incomplete. 
set_data will copy data and type information
can rename to 'Sets metadata (data and type) of the Variable'

**Comment by danpovey** [comment]
and I assume it sets the shape but not necessarily the strides of the source Variable (e.g. if it had been transposed), and put it on the same device?

**Comment by bhushan23** [comment]
goal of the set_data method is to copy date from `new_data` and set to itself (more like a copy constructor but only restricted to data field)

By type, earlier comment was suggesting that type and type id is being copied. Now, we are changing that with copying metadata (data and type) which should be good enough to give high level idea of what this method is doing. (of course, these two are Variable's field)

I think, this is concise comment for a developer to clear out what this method is suppose to do.

**Comment by danpovey** [comment]
In a big public project such as PyTorch, it's not enough to have
"note-to-oneself" types of documentation, such as a developer would write
as a note to their future self to disambiguate something.  It needs to be
documentation that can be understood by someone who is reading that class
header for the first time and trying to understand how things work.

Even your response to me, that the "type and type id" are being copied, and
that the data field is being set, is extremely unclear without knowledge of
the private implementation of class Variable.  As far as I can tell, by
type id you refer to TypeIdentifier, which is a caffe2 concept and not at
all part of the public interface of PyTorch.  And to refer to the "data
field" in a comment in that header would be insufficient because the data
field is hidden inside the impl method and it is not clear from that header
that such a field even exists.

Here is what I would set that comment to, although it's very nonspecific
because I don't really undertand
deeply what it was doing.  Notice that I am also making two other changes
to that line of code, which I will explain to below.  Consider this as a
random deep-dive into the quality of the code and comments, because I
really thought that my `issue` was about fixing a simple typo, without any
substantive issues.
```
  /// Sets the Tensor held by this Variable (as returned by data()) to a
copy
  /// of the Tensor `new_data`
  void set_data(at::Tensor new_data);
```
Since the type_id_ is part of the Impl class and not in the public
interface, it does not make sense to refer to it in a comment in this
class, it can only lead to confusion (you can document it in the Impl
class).

The code was originally:
```
 /// Sets the type of the Variable.
  void set_data(Tensor new_data) const;
```
And regarding those two change to the line of code, I explain them below.

  - Since this function mutates *this, why the hell was it const?  Even if
C++ lets you do that, semantically it does not make sense.

  - What is class Tensor?  I see many references to at::Tensor in class
Variable, but I can find no class Tensor in namespaces torch or
torch::autograd.  I did not expect that a big project like PyTorch would do
something as bad as a using-directive in headers, but a `git grep` reveals
that that is exactly what is going on.  So it's really at::Tensor.  You'd
have to change the function definition too, I guess, including in the Impl
class, to avoid certain compilers complaining at you.

**Comment by bhushan23** [comment]
Please feel free to send a PR

**Comment by soumith** [comment]
@danpovey the person who responded (bhushan23) was also probably just digging into the code, on your behalf and trying to clarify things. He contributes to PyTorch for fun.

me and my team mates deserve the blame.
PyTorch's internals are in a heavy state of flux, as we merge many parts of Caffe2, ATen and PyTorch csrc.
The structure `Variable` itself is being eliminated in a few refactor PRs, and everything being routed via at::Tensor, which is also c10::Tensor, which is also going to be torch::Tensor.

I'm cc-ing @apaszke @gchanan and @yf225 if they have any more things to add.

**Comment by danpovey** [comment]
Oh OK, thanks.
I did make a PR here
https://github.com/pytorch/pytorch/pull/17761
just to clarify that and something else that was unclear to me from reading
the code.

I did like the fact that at::Tensor was distinct from
torch::autograd::Variable-- it's nice to have a simple object that you feel
you can understand, that is separate from the autograd machinery.

**Comment by gchanan** [comment]
Two things I'd add:

1.
```
 /// Sets the type of the Variable.
 void set_data(Tensor new_data) const;
```

This is indeed a bad comment; if you look through the history you'll see it replaced a function that was actually changing the `type` (`Type`) of a Tensor/Variable.

2.  

```
- Since this function mutates *this, why the hell was it const?  Even if
C++ lets you do that, semantically it does not make sense.
```

Hopefully this entry on the wiki explains what is going on here:
https://github.com/pytorch/pytorch/wiki/Writing-Python-in-cpp-(a-manifesto)
