### ISSUE TITLE
Can i use torch.nn.modules.pixelshuffle for commercial products?

### ISSUE THREAD

**Issue by supersonicai** [pytorch/pytorch#17677]
Hi,

According to the document of torch.nn.modules.pixelshuffle(https://pytorch.org/docs/stable/_modules/torch/nn/modules/pixelshuffle.html), the statement says that
"This is useful for implementing efficient sub-pixel convolution
    with a stride of :math:`1/r`.
...
Look at the paper:
    `Real-Time Single Image and Video Super-Resolution Using an Efficient Sub-Pixel Convolutional Neural Network`_
    by Shi et. al (2016) for more details.

    Args:
        upscale_factor (int): factor to increase spatial resolution by

    Shape:
        - Input: :math:`(N, C \times \text{upscale_factor}^2, H, W)`
        - Output: :math:`(N, C, H \times \text{upscale_factor}, W \times \text{upscale_factor})`

    Examples::

        >>> pixel_shuffle = nn.PixelShuffle(3)
        >>> input = torch.randn(1, 9, 4, 4)
        >>> output = pixel_shuffle(input)
        >>> print(output.size())
        torch.Size([1, 1, 12, 12])

    .. _Real-Time Single Image and Video Super-Resolution Using an Efficient Sub-Pixel Convolutional Neural Network:
        https://arxiv.org/abs/1609.05158"

and i found its correlated patent from google(https://patents.google.com/patent/US20170347060A1/en) which may lead to a patent infringement if i adopt invoking pixelshuffle api in my network.

Is it true that pytorch's implementation of pixelshuffle is protected by US20170347060A1 patent?
Thanks.

**Comment by soumith** [comment]
We are not lawyers and we dont know :) (I didn't open that patent link and I am not going to, fyi)
