### ISSUE TITLE
Torch.multiprocessing pool hangs in Jupyter notebooks

### ISSUE THREAD

**Issue by enoonIT** [pytorch/pytorch#17680]
## 🐛 Bug

Running pool.map() hangs (Torch 1.0.0)

## To Reproduce

```
import torch
import torch.nn as nn
from torch.multiprocessing import Pool, set_start_method
try:
     set_start_method('spawn')
except RuntimeError:
    pass

class Dummy:
    def __init__(self, device):
        self.device = device
        self.layer = nn.Linear(100, 100).to(self.device).share_memory() # removing share_memory doesn't have any effects
    def run(self):
        self.layer(torch.rand(1000, 100).to(self.device))

def run_steps(agent):
    for k in range(100):
        agent.run()

n_gpus = 2
agents = [Dummy("cuda:%d" % k) for k in range(n_gpus)]

# THIS HANGS
pool = Pool(n_gpus)
pool.map(run_steps, agents)
```

If instead I use threads, everything works:
```
# This works:
from multiprocessing.dummy import Pool as dThreadPool
pool = dThreadPool(n_gpus)
pool.map(run_steps, agents)
```

## Expected behavior

I expect the code to run without hanging

## Environment

Pytorch 1.0.0
OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Installed via pip

Python version: 3.5
CUDA 9.0
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 384.145
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1

## Additional context

This happens when running in a jupyter notebook
Might be related to #16954

**Comment by enoonIT** [comment]
I run some tests and it seems the issue only happens in Jupyter notebooks, when run as a standalone everything works correctly:

```
import torch
import torch.nn as nn
from time import time
from torch.multiprocessing import Pool, set_start_method, freeze_support
from multiprocessing.dummy import Pool as dThreadPool
try:
     set_start_method('spawn')
except RuntimeError:
    pass

class Dummy:
    def __init__(self, device):
        self.device = device
        self.layer = nn.Linear(100, 100).to(self.device).share_memory() # removing share_memory doesn't have any effects
    def run(self):
        p = torch.rand(1000, 100).to(self.device)
        p = self.layer(p)

def run_steps(agent):
    for k in range(n_iters):
        agent.run()

n_iters = 100

if __name__ == '__main__':
    freeze_support()
    n_gpus = 2
    agents = [Dummy("cuda:%d" % k) for k in range(n_gpus)]

    start = time()
    pool = Pool(n_gpus)
    pool.map(run_steps, agents)
    print("It took %g" % (time()-start))
    pool.close()
```

**Comment by bhushan23** [comment]
@enoonIT can you verify python version being using in Jupyter notebook?

**Comment by enoonIT** [comment]
Sure, it's 3.5.2

(running:)
```
from platform import python_version
 print(python_version()
```

**Comment by ezyang** [comment]
I think your problem is that you're using `spawn`, but your notebook doesn't have the (mandatory!) `if __name__ == '__main__'` guard. The reason this is important is because the way spawn works is it first *loads* your notebook and runs all of its code (including `pool.map`), and then it actually tries to run the `run_steps` function you requested to be run. Obviously if all your child tasks are running `pool.map`, you're going to deadlock in this situation.

I'm not a notebook expert but if you can replicate `__name__ == '__main__'` somehow in your notebook, that should sovle the problem too.

**Comment by enoonIT** [comment]
Thanks for the explanation, that does make sense
