### ISSUE TITLE
Windows 10 VS 2017 - torch::jit::load works in debug mode, but fails in release mode

### ISSUE THREAD

**Issue by carlosferrazza** [pytorch/pytorch#17682]
## 🐛 Bug

Hi, I successfully built libtorch from source, and I have tried to load a model (exported according to ) in my C++ application. It works fine with debug mode. However, when I try to load the same model in release mode, the program crashes. Should it be actually possible to switch between debug and release mode, or is this a bug? 

## To Reproduce

1. libtorch built via the following commands:
```
git clone --recursive https://github.com/pytorch/pytorch 
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1
set NO_CUDA=1
set DEBUG=1
set BUILD_TEST=OFF
call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
python setup.py install
```

2. 
```
std::string str = "new_model.pt";
std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(str);
```

I have tried to put the entire file path in str, but it did not help. The same code works fine in debug mode.

## Environment

 - PyTorch 1.0
 - Windows 10
 - How you installed PyTorch (see above):
 - Build command you used (see above):
 - Python version: 3.7.1
 - CUDA/cuDNN version: no CUDA
 - GPU models and configuration: no GPU

**Comment by peterjc123** [comment]
Please keep consistent. It is not a bug, just a requirement of MSVC. When you build the debug version of libtorch, then you can only build programs or libraries with the debug configuration. So if you want to use release, then you'll need the release binaries.

**Comment by carlosferrazza** [comment]
I see. My understanding was that setting the flag DEBUG=1 would result in building the debug binaries, in addition to the release ones. Then this is clearly not the case, thanks for clarifying.

**Comment by xsacha** [comment]
I ran in to this issue as well. It doesn't happen when building from CMake because it builds both debug and release but for some reason the nightly builds are separated.

Is it possible to have nightly builds that have both debug and release combined? It should still zip well.
The issue I have is that they have separate Configs, which mean I have to actually switch the files or point to a different directory every time I change configuration to debug something or profile something.

**Comment by mappleKeuj** [comment]
Hi, I currently have a similar problem with TorchLib, visual studio 2017 and windows 7 in Debug.
I downloaded both release and debug lib from https://pytorch.org/get-started/locally/
Loading and executing model is working properly in Release mode. To do so I am linking with torch_cpu and c10 libraries from the Release TorchLib.
However, when linking with same libraries from Debug TorchLib, although compilation is working, TorchLib fails loading the traced model. The error message thrown by Torchlib is "Open File Failed". 
Is it a bug from Debug library ?
