### ISSUE TITLE
[JIT] Allow CPP frontend to access config attributes from the .pt

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#17683]
## 🚀 Feature
Allow CPP frontend to access config attributes from the .pt
Something that looks like this:

```
auto model = torch::jit::load("model.pt");
const int prediction_horizon_s = model.get_attribute("prediction_horizon_s");
```

## Motivation

The configurations related to the model right now needs to be kept in 2 places. Once in the model, and then once in the inference code. Since the inference code is driven by the model anyway, it would be much cleaner if the model itself can carry the configurations. 

In Python, this is trivial because it is just a python class attribute. But this is not possible in JIT right now. It would be great if you could expose that in the CPP front end too.

## Alternatives

Have a config file for the inference code.

**Comment by eellison** [comment]
Thanks for the feature request! We will talk about it and get back to you. @driazati does this relate to what you're working on with attributes ?

**Comment by driazati** [comment]
Yeah this will be added in with attributes. They will work like `Parameter`s, but allow for non-Tensor types. #17309 adds this with `Module:: find_attribute(std::string& name)` which gives back the a struct containing the type and `IValue`, so for the example you'd do something like

```cpp
const int prediction_horizon_s = model.find_attribute("prediction_horizon_s").ivalue.toInt();
```

**Comment by bhack** [comment]
@driazati  Can we recover in the c++ frontend attributes saved with `torch.jit.Attribute` in python?
