### ISSUE TITLE
nn.Embedding broken for half

### ISSUE THREAD

**Issue by akurniawan** [pytorch/pytorch#17699]
## 🐛 Bug

Using the following script will break with error `_th_index_select is not implemented for type torch.HalfTensor`

```
import torch
import torch.nn as nn

b = nn.Embedding(10, 20, 0)
b.half()
b(torch.randint(0, 10, size=(5, 10)))
```

## To Reproduce

1. Run the script above

## Expected behavior

No error

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0.1.post2
 - OS (e.g., Linux): Mac OSX 10.14.3
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ngimel** [comment]
There is very limited support for half datatype on CPU. The script above will work for both nn.Embedding and input on cuda device.
