### ISSUE TITLE
a little bit slow in backward when using multiple nodes training model！

### ISSUE THREAD

**Issue by njtuzzy** [pytorch/pytorch#17704]
Hi,
I followed the guideline to use the 4 nodes (1 titan XP in each node), and using 'gloo' to do the backward communication. It turns that the backward time is a little bit slow from 0.08 (single GPU） to 43s(4 nodes). did i do something wrong? thanks

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by vishwakftw** [comment]
Could you please provide the environment information using [this script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)?

Please provide a script to replicate this behavior.

**Comment by njtuzzy** [comment]
the os env i used is unbuntu 16.04
pytorch 1.0 cuda 9 

and the training code for distrubuted computing  is almost the same with the example provided by pytorch.org

python train.py --batch-size 6 --world-size 4 -- rank 0 --dist-url tcp://192.168.20.77:2222 --dist-backend gloo -- gpu 0 

is this what you want?

Thanks

**Comment by mrshenli** [comment]
Please use [forum](https://discuss.pytorch.org/) for questions. I am closing this issue. Please feel free to open a new issue if this turns out to be a bug report or feature request.
