### ISSUE TITLE
Error using cuda in docker container

### ISSUE THREAD

**Issue by devendrachaplot** [pytorch/pytorch#1771]
I used the Dockerfile to build pytorch
`docker build -t pytorch .`
and ran the image with
`nvidia-docker run --rm -ti --ipc=host pytorch`

Inside the container, I get an error using cuda:

>>> import torch
>>> x = torch.rand(1).cuda()

```
THCudaCheck FAIL file=/tmp/pip-b1neh3fv-build/torch/lib/THC/THCGeneral.c line=66 error=30 : unknown error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/_utils.py", line 65, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/cuda/__init__.py", line 266, in _lazy_new
    _lazy_init()
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/cuda/__init__.py", line 85, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /tmp/pip-b1neh3fv-build/torch/lib/THC/THCGeneral.c:66
```

**Comment by apaszke** [comment]
@ngimel do you have any ideas what might be causing that?

**Comment by pavanky** [comment]
@devendrachaplot can you try running `nvidia-smi` work with nvidia-docker ?

**Comment by ngimel** [comment]
Also, try running a simple cuda problem inside the container:
```
STR=$'#include <cstdio> \n int main() { int n; printf(\"%d\\n\",cudaGetDeviceCount(&n)); }'
echo "$STR" > tmp.cu
nvcc --run tmp.cu
```
If output is something other than 0, the problem is with the setup (driver?), not with pytorch. In a parallel thread someone suggested just rebooting to get rid of error 30.

**Comment by devendrachaplot** [comment]
@pavanky 
nvidia-smi works inside the container.

@ngimel  
The output is 30. I am running everything on DGX-1. Other images and containers are working fine with cuda on the same server. This problem comes only using the pytorch container.

When you say reboot, do you mean restarting the container, or restarting the server?

**Comment by ngimel** [comment]
In #1778 restarting the server seemed to cure error 30 for some users. Does base container that is used for pytorch also work fine (nvidia/cuda:8.0-devel-ubuntu16.04)? Because if you are getting error even on the simple cuda program, it can't be related to pytorch.

**Comment by devendrachaplot** [comment]
I am getting 30 as the output even in the base container. There seems to be an issue with that I guess.

**Comment by khurramHazen** [comment]
@ngimel I am having a  similar issue; `nvidia-smi` is working. When I try to run the sample cuda code I get the following error `bash: nvcc: command not found`. I separately built the cuda image (the first line in pytorch docker file) and there I was able to run the sample cuda code you provided. I am unable to locate `nvcc` in the container. Can you give me some pointers on how to debug it?
