### ISSUE TITLE
How to perform quantization of a model in PyTorch?  

### ISSUE THREAD

**Issue by r3krut** [pytorch/pytorch#17713]
## How to perform quantization of a model in PyTorch?  

Hello everyone!

I have trained the model 'MobileNetV2' in PyTorch from 'https://github.com/qfgaohao/pytorch-ssd/blob/master/vision/nn/mobilenet_v2.py'. Now, I want use it in Raspberry Pi3. 

I converted '.pth' model to Caffe2 model through `ONNX` representation and I got two files: init_net.pb and predict_net.pb for Caffe2 framework.

As far as I know, to accelerate the model on mobile systems such as Rpi3(B/B+) I should use the QNNPACK lib which allows make the low-precision inference using operators with `int8` data type. 

How can I make low-precision inference using QNNPACK? 
Maybe there are some tutorials about it?

Thnx.

**Comment by bhushan23** [comment]
Follow instructions here: https://github.com/pytorch/QNNPACK#raspberry-pi-2-or-3
Questions should rather be asked at https://discuss.pytorch.org/
please close the issue as well.

**Comment by AlexKoff88** [comment]
Look what is available here: https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/nncf. This is Quantization-Aware Training in PyTorch with ability to export the quantized model to ONNX.
