### ISSUE TITLE
Building TorchLib on windows from source

### ISSUE THREAD

**Issue by BarMazal** [pytorch/pytorch#17711]
Hi all,
 I'm trying to work with the LibTorch C++ library.
I develop under windows 10 and visual studio 2017.

I've issues both using the pre-built library and building the library from sources.
Here I'd like to ask about building the library from source.
So I cloned the latest master and there is a script called "build_windows.bat". The scripts works but it does not produce the LibTorch.lib or Torch.lib or caffe2.dll files.
I tried to add in the camke command -DBUILD_TORCH=ON and it doesn't compile anymore. It has problems in the THD/base/ChannelUtils.hpp file including "sys/socket.h".
so I replaced "#include >sys/socket.h>" with
#ifdef __WIN32__
# include <winsock2.h>
#else
# include <sys/socket.h>
#endif
and got more errors about "std::numeric_limits<port_type>::max()" and min etc.
So I changed them too by adding parenthesis around like (std::numeric_limits<port_type>::max)().
Then I got different errors about missing "apra/inet.h" and "sys/poll.h" and unistd.h etc. All linux stuff that should be replaced with windows stuff.

All of that even before trying to compile using CUDA.
without getting into much more details I also tried compiling with CUDA 9.0, so I had issues with visual 2017, so I used tool kit v140 and then I had issues with AVX2. I downloaded cuda 10 but had the same problems.

The main question is:
It is possible to d/l from the site a prebuilt version for windows 10 and both cuda 9.0 and cuda 10.0. 
**How is it compiled?** I'd like to be able to compile it with and without CUDA in release and debug mode so rule out misalignment of run time libraries.

Thanks,
 Guy.

**Comment by peterjc123** [comment]
```cmd
cmd
REM [Optional] The following two lines are needed for Python 2.7, but the support for it is very experimental.
set MSSdk=1
set FORCE_PY27_BUILD=1

REM [Optional] As for CUDA 8, VS2015 Update 3 is required; use the following line.
set "CUDAHOSTCXX=%VS140COMNTOOLS%..\..\VC\bin\amd64\cl.exe"

set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1

REM Run "Visual Studio 2017 Developer Command Prompt"
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.11

python tools\build_libtorch.py
```

**Comment by peterjc123** [comment]
Precompiled version (Release only) :
```
https://download.pytorch.org/libtorch/nightly/cu90/libtorch-win-shared-with-deps-latest.zip
https://download.pytorch.org/libtorch/nightly/cu100/libtorch-win-shared-with-deps-latest.zip
```

**Comment by LJXLJXLJX** [comment]
@peterjc123 

Hello , some error occurred after entered 
> for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.11

> [ERROR:vcvars.bat] Toolset directory for version '14.11' was not found.
> [ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
> [ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
> [ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
> [ERROR:VsDevCmd.bat] Where [value] is:
> [ERROR:VsDevCmd.bat]    1 : basic debug logging
> [ERROR:VsDevCmd.bat]    2 : detailed debug logging
> [ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
> [ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
> [ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1

How to solve it?

**Comment by peterjc123** [comment]
Precompiled version (Debug only) :
```
https://download.pytorch.org/libtorch/nightly/cpu/libtorch-win-shared-with-deps-debug-latest.zip
https://download.pytorch.org/libtorch/nightly/cu90/libtorch-win-shared-with-deps-debug-latest.zip
https://download.pytorch.org/libtorch/nightly/cu100/libtorch-win-shared-with-deps-debug-latest.zip
```

**Comment by peterjc123** [comment]
Please reopen this issue when you have problem.

**Comment by BarMazal** [comment]
Hi,
 I've tried the script you wrote. If I understand correctly you wanted all the lines but the last one to run in command line and then run the last one.
I've put all the lines in *.bat file and ran it and afterward I run "python tools\build_libtorch.py"

The build if not finished successfully. There is no clear indication what is the error.
Here are the last few lines:
"

> [110/1464] Building CXX object caffe2\CMakeFiles\caffe2.di...eOpsKernel.cpp.DEFAULT.cpp.AVX.cpp.AVX.cpp.DEFAULT.cpp.obj
> .\c10/core/TensorTypeId.h(38): warning C4273: 'c10::toString': inconsistent dll linkage
> .\c10/core/TensorTypeId.h(35): note: see previous definition of 'toString'
> ninja: build stopped: subcommand failed.
> Traceback (most recent call last):
>   File "tools\build_libtorch.py", line 25, in <module>
>     build_python=False, rerun_cmake=True, build_dir='.')
>   File "C:\development\NeuralNetworks\pytorch\tools\build_pytorch_libs.py", line 247, in build_caffe2
>     cwd=build_dir, env=my_env)
>   File "C:\development\Continuum\anaconda3\lib\subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '7']' returned non-zero exit status 1.

"

A lot of libs and dlls are created, but I don't see libtorch.lib or torch.lib among them.

I've downloaded the precompiled debug you showed me in the previous message and I'll check it.

Thanks,
 Guy.

**Comment by peterjc123** [comment]
Is there any reproducible code that I can try?
Besides, there's something you need to check before considering this as a bug.
1. Please use the nightly package to save the model.
2. Please verify the path of the model. (e.g, Use absolute path)

**Comment by BarMazal** [comment]
Well, first I can't build from source using the master branch... either with build_windows.bat or the script you wrote above. So the master is the reproducible code for that matter.
 
Second, here is the code I use. Very mundane:

```
#include <iostream>
#include <memory>

#include <torch/script.h> // One-stop header.
#include <torch/torch.h>
int main() {
  // Deserialize the ScriptModule from a file using torch::jit::load().
	try
	{
		std::shared_ptr<torch::jit::script::Module> module = torch::jit::load("C:/Projects/TorchC++/LibTorch/model.pt");
	}
	catch (std::exception &e)
	{
		int a = 8;
		std::string str = e.what();
	}
	catch (...)
	{
		int a = 9;
	}


  torch::Tensor tensor = torch::rand({2, 3});
  at::Tensor t2 = tensor.cuda();
  torch::Tensor t3 = tensor.to(at::kCUDA);
  std::cout << tensor << std::endl;
  std::cout << t2 << std::endl;
  std::cout << t3 << std::endl;

  std::cout << std::endl;

  assert(my_module != nullptr);
  std::cout << "Loaded module\n";

  // Create a vector of inputs.
  std::vector<torch::jit::IValue> inputs;
  inputs.push_back(torch::ones({ 1, 3, 224, 224 }));
  std::cout << "Create input\n";

  // Execute the model and turn its output into a tensor.
  at::Tensor output = my_module->forward(inputs).toTensor();
  std::cout << "After forward\n";

  std::cout << output.slice(/*dim=*/1, /*start=*/0, /*end=*/5) << '\n';
  std::cout << "ok\n";

  return 0;
}
```
And this is the file I'm trying to load (you might want to change the path in the code):
[https://drive.google.com/open?id=1YoQgee1biSA3nh1UcXL-3mRLo_EE5GRV](url)

The file was created following the tutorial here:
[https://pytorch.org/tutorials/advanced/cpp_export.html](url)

now the python code ran with a package installed by python so it might not match the nightly build.
How can I install in python a package that matches the nightly build?

BTW, if I remove the code to load the model and run it, the other code works but there is not much stuff there to fail either :)

In any case I appreciate your help.
Thanks.

**Comment by peterjc123** [comment]
> Well, first I can't build from source using the master branch... either with build_windows.bat or the script you wrote above. So the master is the reproducible code for that matter.

Sorry, what I mean `reproducible` is that the build should fail even when you have the environment correctly configured. The Windows CI is green so I don't think it is such a problem. Would you please give me the full log so that I can give you some hints? 

> How can I install in python a package that matches the nightly build?

```powershell
# If installed through conda
conda uninstall pytorch
# If installed through pip
pip uninstall torch
# Install windows nightlies according to pytorch.org. Please choose `Preview`.
```
