### ISSUE TITLE
Inconsistent results of torch.argmax with tensors that have duplicated values

### ISSUE THREAD

**Issue by hwijeen** [pytorch/pytorch#17738]
## 🐛 Bug
Inconsistent results of torch.argmax with tensors that have duplicated values

## To Reproduce

```
cpu = torch.LongTensor([[2,3,0,3,3], [1,3,1,3,1]])
cpu.argmax(dim=1) # tensor([4, 3])
cuda = torch.cuda.LongTensor([[2,3,0,3,3], [1,3,1,3,1]])
cuda.argmax(dim=1) #tensor([4, 1], device='cuda:0')
```

When I did the same on another machine(pytorch 0.4.1, CUDA 9.0)
```
cpu = torch.LongTensor([[2,3,0,3,0], [1,3,1,3,1]])
cpu.argmax(dim=1) # tensor([4, 1]). 
cuda = torch.cuda.LongTensor([[2,3,0,3,0], [1,3,1,3,1]])
cuda.argmax(dim=1) # tensor([1, 1, device='cuda:0')
```

## Expected behavior
torch.argmax returns the same value for tensors that have same data in it, regardless of devices(or other factors).

## Environment

PyTorch version: 0.4.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 410.79
cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.3.1

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.4.1
[pip3] numpy==1.15.0
[pip3] torch==0.4.1.post2
[pip3] torchtext==0.3.1
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.3                      1
[conda] mkl_fft                   1.0.4            py36h4414c95_1
[conda] mkl_random                1.0.1            py36h4414c95_1
[conda] mxnet-mkl                 1.3.0.post0               <pip>
[conda] pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    pytorch
[conda] torchtext                 0.3.1                     <pip>
[conda] torchvision               0.2.1                    py36_0

## Additional context
It would be helpful if  the documentation describes if torch.argmax returns the last or the first index if a tensor holds duplicated values.

**Comment by vishwakftw** [comment]
This is related to https://github.com/pytorch/pytorch/issues/14147. Perhaps we should add [this comment](https://github.com/pytorch/pytorch/issues/14147#issuecomment-439631144) in the docs..

**Comment by bhushan23** [comment]
@vishwakftw @soumith 
I agree with the [comment](https://github.com/pytorch/pytorch/issues/14147#issuecomment-439631144) but, consistent behavior across devices is also important.

another point is, consistency with NumPy- we are always pushed to have NumPy-like behavior for portability, in such case, returning first occurence is preferable. 
[NumPy's argmax](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html)

**Comment by SsnL** [comment]
There is no easy way to guarantee consistency across device, especially with parallelism-heavy device like GPUs, and many GPUs requiring different launching configs.

**Comment by hwijeen** [comment]
Thank you for the reference and discussions! 

How about inconsistency across different machines? In the above example, the argmax results for two cpu tensors are different.
I also report that the results(argmax with same cpu tensor on different machine)were the same for most tensors and I could not find any regularity in the tensors that results in the inconsistency.

Is there randomness involved in picking a index when there are several answers?

**Comment by soumith** [comment]
the only determinism we aim to have is hashed on device, and for CPU, single-threaded.
Even across different kinds of GPUs, all bets are off.

We cannot guarantee cross-device, cross-CPU-type determinism due to severe performance cliffs that'll result from such a constraint.
