### ISSUE TITLE
torch.max and torch.min inconsistent on cpu/gpu for tensors with zero elements.

### ISSUE THREAD

**Issue by surgan12** [pytorch/pytorch#17750]
###
On cpu:
`g = torch.rand(0,4)`
`torch.max(g)`
###
Behaviour:
`RuntimeError: invalid argument 1: tensor must have one dimension at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:59`

On  Gpu:
`g = torch.rand(0,4).cuda()`
`torch.max(g)`
###
Behaviour:
`tensor(-inf, device='cuda:0')`

Expected Behaviour on GPU:
Some error or an empty tensor as i feel the max/min of a set should belong in the set so -inf is wrong.

PyTorch Version :'1.0.1.post2'

**Comment by ezyang** [comment]
I don't think the GPU behavior is completely wrong, for a mathematical reason: it should be the case that `torch.max(torch.cat(xs, ys)) == torch.max(torch.max(xs), torch.max(ys))` for any xs and ys, including empty. In that case, `-Inf` is the correct neutral element to pick.

The way Numpy gets out of this situation, is they ask you for an initial element to handle the case explicitly, and error if you don't provide it. So in the end I agree with your suggested course of action.

**Comment by gchanan** [comment]
We already have a solution for this when a dimension is passed in, which is what numpy does, but without support for `initial`.  We should make the `maxall` case match that, and we can optionally add support for `initial`.

```
>>> torch.max(torch.randn(0,4), dim=1)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
```

**Comment by gchanan** [comment]
this has been fixed.
