### ISSUE TITLE
[CI] Is approval of reviewers reasonable while one of CI facilities is failure?

### ISSUE THREAD

**Issue by leemgs** [pytorch/pytorch#17794]
I wonder about the review and merging process of the Pytorch repository. What is a review sequence between the CI facility(robot) and the reviewers (developer)?

For example, 
1. Submitting PR --> CI bot inspects the PRs --> Reviewer try to review the code of the PR --> Then, Reject or Accepted --> Merging or Abandoned
1. Submitting PR --> CI bot inspects the PRs --> Reviewer try to review the code of the PR --> Then, Accepted by a reviewer **although CI generates 'failure'** --> Merging or Abandoned

* Case study:
![image](https://user-images.githubusercontent.com/82404/54009847-c7e0ee00-41af-11e9-8b72-09dbd4003d3c.png)

**Comment by ezyang** [comment]
Hi @leemgs, in general, it's OK for people to approve PRs even though CI is not passing; since (1) CI is flaky so often the failures are spurious, and (2) it is generally the responsibility of the patch author (and the person who merges it) to ensure that there are no real failures.

We also have a designation "merge this please" which means "this is passing everything, please merge it now." You're expected to have verified that all failures are indeed spurious before doing this; and only maintainers get this privilege.

**Comment by leemgs** [comment]
> since (1) CI is flaky so often the failures are spurious, and (2) it is generally the responsibility of the patch author (and the person who merges it) to ensure that there are no real failures.

@ezyang , Got it. BTW, What is a key reason that CI is sometimes broken (or slow speed suddenly)? Can not we maintain the CI operation more faster and more stably to help reviewers that participate in the code review voluntarily? Does the existing CI infrastructure of the Pytorch repository uses CircleCI & TravisCI?

**Comment by ezyang** [comment]
There are a few reasons:

1. CircleCI randomly craps out on a small percentage of runs, before we even run any code. We've told CircleCI about this but a fix has been very slow coming
2. We have a few flaky tests. It takes a bit of time to diagnose and disable them, so a few of them stick around and intermittently terrorize diffs. Search for "flaky" to see some standing issues on them. They need some time and debugging to figure out why they are flaky; some involve quite complex multithreaded systems.
3. ROCm is still a little unstable, and is often a culprit.

One of the things I intend to work on in the near future is a better system for reporting failures to users, and letting them know if they are likely spurious or not.
