### ISSUE TITLE
Dilated Convolution 2D runs a lot slower in C++ TorchScript

### ISSUE THREAD

**Issue by JackWindows** [pytorch/pytorch#17819]
## 🐛 Bug

If a model contains dilated convolution and uses JIT trace to export to TorchScript Module, the exported module will run slower in C++ inference than in Python on CPU.
For an internal model the slow down is significant, where Python inference takes ~10s with `OMP_NUM_THREADS=2`, and C++ inference takes ~31s.

## To Reproduce

1. Use the following code to export a ResNet101 model with modified dilation:
```python
import torch
from torchvision import models
import time

net = models.resnet101(pretrained=True).cpu()
# artificially create a dilation layer 
net.conv1.dilation=(3, 3)
net = net.eval()

# 4batch size
example = torch.rand(4, 3, 224, 224).cpu()

with torch.no_grad():
    traced_script_module = torch.jit.trace(net, example)

traced_script_module.save('traced_resnet101_dilation.pt')
```
2. Use the following code for Python inference profiling:
```python
from __future__ import print_function

import os
import sys
import time
import torch

traced_script_module = torch.jit.load(sys.argv[1])
example = torch.rand(4, 3, 224, 224).cpu()

with torch.no_grad():
    for _ in range(5):
        start_ts = time.time()
        with torch.autograd.profiler.profile() as profile:
            traced_script_module(example)
        end_ts = time.time()
        print('inference took {:.2f}ms'.format((end_ts - start_ts) * 1000))

        profile.export_chrome_trace('profile_python_cpu.json')
```
The output is
```
$ OMP_NUM_THREADS=1 python inference.py traced_resnet101_dilation.pt 
inference took 1764.76ms
inference took 1369.52ms
inference took 1363.28ms
inference took 1358.34ms
inference took 1354.14ms
```
The profile tracing file is:
[profile_python_cpu.json.txt](https://github.com/pytorch/pytorch/files/2947609/profile_python_cpu.json.txt)

The profile tracing screenshot is:
![image](https://user-images.githubusercontent.com/1560135/54057937-62e2c380-41c2-11e9-81de-22b9680aa301.png)

3. Use the following code for C++ inference profiling:
```cpp
#include <torch/torch.h>
#include <torch/script.h>

#include <torch/csrc/autograd/profiler.h>

void benchmark(const char* model_name) {
    torch::NoGradGuard no_grad;
    std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(model_name);
    module->to(torch::kCPU);

    std::vector<torch::jit::IValue> batch;
    batch.push_back(torch::randn({4, 3, 224, 224}).set_requires_grad(false).cpu());

    for (int i=0; i<5; i++) {
        std::chrono::high_resolution_clock::time_point begin = std::chrono::high_resolution_clock::now();

        {
            torch::autograd::profiler::RecordProfile profiler("profile_cpp_cpu.json");
            module->forward(batch);
        }

        std::chrono::high_resolution_clock::time_point end = std::chrono::high_resolution_clock::now();
        std::cout << "Inference took " << std::chrono::duration_cast<std::chrono::microseconds>(end - begin).count() / 1000.0 << "ms\n";
    }
}

int main(int argc, const char* argv[]) {
    benchmark(argv[1]);
}
```
The output is:
```
$ OMP_NUM_THREADS=1 ./inference torch_cpu_slowdown/traced_resnet101_dilation.pt 
Inference took 1871.63ms
Inference took 1580.98ms
Inference took 1588.3ms
Inference took 1574.94ms
Inference took 1570.36ms
```
The profile tracing file is:
[profile_cpp_cpu.json.txt](https://github.com/pytorch/pytorch/files/2947614/profile_cpp_cpu.json.txt)

The profile tracing screenshot is:
![image](https://user-images.githubusercontent.com/1560135/54057918-4e9ec680-41c2-11e9-934f-2b021e3c995e.png)

## Expected behavior

The Python and C++ inference using TorchScript Module should have similar performance. However, as the results from step 2 and 3, the dilation convolution layers runs ~29ms on Python but ~291ms on C++. There is a 10x slow down happening on C++ inference.

## Environment

 - PyTorch Version (e.g., 1.0): I think it's 1.0, we are building from commit a3f600e.
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): N/A
 - Python version: 2.7.6
 - CUDA/cuDNN version: 10.0.130 / 7.4.1.5
 - GPU models and configuration: N/A
 - Any other relevant information:

## Additional context

We have an internal model which suffers significant slow down on CPU due to the slow dilation convolution on C++ inference.

**Comment by zou3519** [comment]
Maybe MKLDNN is not being used in libtorch but is being used in pytorch?

**Comment by JackWindows** [comment]
> Maybe MKLDNN is not being used in libtorch but is being used in pytorch?

Do you mean for the `thnn_conv_dilated2d_forward` operation?
If you zoom in the tracing, you can actually see the `mkldnn_convolution` operation afterwards, so I assume both python and C++ are using mkldnn?
Actually the C++ mkldnn operations are faster than Ptyhon's.

![image](https://user-images.githubusercontent.com/1560135/54059346-cb33a400-41c6-11e9-93f2-9f9b3aa45d16.png)

**Comment by sidazhang** [comment]
> Maybe MKLDNN is not being used in libtorch but is being used in pytorch?

The offending op (thnn_dilated2d_forward) is a torch op. Seems like somehow it is slower in CPP frontend.

So neither python nor CPP are using MKL for this op

**Comment by yf225** [comment]
I tested on the nightly builds with `OMP_NUM_THREADS=1` and didn't reproduce the slowdown. @JackWindows @sidazhang Do you mind trying the nightlies?

**Comment by JackWindows** [comment]
@yf225 Thanks for your testing.
To update the issue, we have tested again using PyTorch's official cmake tutorial and cannot reproduce the slowdown.
We dug into our internal build system deeper and found we have an offending link time library `libblas`. We use `clang` and `bazel` to build our C++ inference code, and if we remove `libblas` from the link time library, the slow down goes away.
Strangely, if we move the `-lblas` in `clang` link options to the end of a list of `-l` options, the slow down also goes away. I am very confused about why the order of `-l` options matter here.

I would appreciate any pointer for potential place where we should look at.

**Comment by soumith** [comment]
the order of `-l` options matters because in one case `libblas` is taking precedent / loaded first, and in the other case mkl is being loaded first.

**Comment by JackWindows** [comment]
> the order of `-l` options matters because in one case `libblas` is taking precedent / loaded first, and in the other case mkl is being loaded first.

Can you explain a bit on how `mkl` comes into play?
I thought the slow operation is `thnn_conv_dilated2d_forward`, and there are `mkldnn` convolutions which run fine in C++ inference code.

**Comment by soumith** [comment]
`thnn_conv_dilated2d_forward` uses gemm
