### ISSUE TITLE
Sparse MM not working right

### ISSUE THREAD

**Issue by patrickgrad** [pytorch/pytorch#17825]
I am trying to do a sparse * dense matrix multiply in the following way, "c = a.mm(b)" (where a is sparse, b is dense) and c is coming out as sparse. So then I try to convert it to dense using .to_dense() but it says that's not implemented for CUDA. So I transfer to the cpu using .cpu(). But then it says its not a sparse tensor, so I think great, I transfer it back but CUDA is yelling at me again that its sparse!!!!!!!!! 

All I want to know is how to do a sparse * dense mm on the GPU and have it output as dense, this doesn't seem like a hard request.... Not sure why PyTorch is being so difficult. 

I am using Pytorch 1.0.0

**Comment by zou3519** [comment]
Definitely sounds like there's a bug somewhere... could you provide a code snippet @patrickgrad ?

**Comment by rgommers** [comment]
No follow-up, and there have been a lot of issues and changes related to `sparse.mm`. So I'll close this. Thanks @patrickgrad, @zou3519
