### ISSUE TITLE
[feature request] Make distribution sample consistent with rand

### ISSUE THREAD

**Issue by pgromano** [pytorch/pytorch#17842]
## 🚀 Feature
Change `sample_shape` argument in `sample` (`torch/distributions/distributions.py`) to `*sizes` for consistency with `torch.rand`.

## Motivation

Within `distributions`, the `sample` attribute takes `sample_shape` as a tuple. Whereas in `torch.rand` and `torch.randn` samples are generated by passing `*sizes` is passed as variable length arguments. This creates inconsistency and seems easy to change!

## Pitch

The change should be as simple as...
```python
 def sample(self, *sample_shape):
    pass
```

Because in most of the distributions I explored (Normal, Poisson, Exponential family) the `sample` attributes makes a call to `_extend_shape` which will convert tuples to `torch.Size`.

```python
def _extended_shape(self, sample_shape=torch.Size()):

        if not isinstance(sample_shape, torch.Size): 
            sample_shape = torch.Size(sample_shape) # <-- Right here!
        return sample_shape + self._batch_shape + self._event_shape
```

So really only one line of code needs to be changed?

## Alternatives

Keep it as is, and very little will change. This would be a small quality of life improvement, and I recommend it only because it seems easy to implement.

**Comment by fritzo** [comment]
A backwards-compatible change would require each `sample` and `rsample` implementation to update with a bit more code. This seems like a lot of work.
```diff
- def sample(self, sample_shape=None):
-     if sample_shape is None:
-         sample_shape = torch.Size()
+ def sample(self, *sample_shape):
+     if len(sample_shape) == 1 and isinstance(sample_shape[0], tuple):
+         sample_shape = sample_shape[0]
      ...
```

**Comment by pgromano** [comment]
It looks like all the `sample` and `rsample` methods pass `sample_shape` to `Distribution._extended_shape`. 

```diff
-def _extended_shape(self, sample_shape=torch.Size()):
+def _extended_shape(self, *sample_shape):    
    if not isinstance(sample_shape, torch.Size):
        sample_shape = torch.Size(sample_shape)
    return sample_shape + self._batch_shape + self._event_shape
```

That change should automatically handle the values passed into a tuple which get cast to a `torch.Size` instance. It would definitely require changing every `sample` and `rsample`

```diff
-sample_shape=torch.Size()
+*sample_shape
```

Happy to take that on and test!

**Comment by pgromano** [comment]
I made the following changes described above and the changes below to `torch.distributions.normal.py`

```diff
-def sample(self, sample_shape=torch.Size()):
-    shape = self._extended_shape(sample_shape)
+def sample(self, *sample_shape):
+    shape = self._extended_shape(*sample_shape)
    with torch.no_grad():
        return torch.normal(self.loc.expand(shape), self.scale.expand(shape))

-def rsample(self, sample_shape=torch.Size()):
-    shape = self._extended_shape(sample_shape)
+def rsample(self, *sample_shape):
+    shape = self._extended_shape(*sample_shape)
    eps = _standard_normal(shape, dtype=self.loc.dtype, device=self.loc.device)
    return self.loc + eps * self.scale
```

**Comment by fritzo** [comment]
Hmm it still seems this will break many user-defined distributions. @neerajprad WDYT?

**Comment by neerajprad** [comment]
> Hmm it still seems this will break many user-defined distributions. @neerajprad WDYT?

@pgromano - I don't think that the change above is backwards compatible without incorporating @fritzo's snippet, but combining the two should work fine. I think we should support both varargs as well as list/tuples for backward compatibility, and also to keep things consistent with other pytorch constructors that allow for both varargs and iterable style size specification. 

For user defined distributions, that will lead to a divergence from the interface, but it shouldn't break it unless they are using `Distribution._extended_shape` internally, which seems reasonable to me.

```diff
-    def _extended_shape(self, sample_shape=torch.Size()):
+    def _extended_shape(self, *sample_shape):
+        if len(sample_shape) == 1 and isinstance(sample_shape[0], tuple):
+            sample_shape = sample_shape[0]
```

```diff
-    def rsample(self, sample_shape=torch.Size()):
-        shape = self._extended_shape(sample_shape)
+    def rsample(self, *sizes):
+        shape = self._extended_shape(sizes)
```

**Comment by pgromano** [comment]
Yes, y'all are absolutely right. I hadn't considered user-defined distributions before. Let me know if y'all want to move forward, and I'm happy to take on writing in the changes.

**Comment by neerajprad** [comment]
Sorry, the snippet above should work even for user-defined distributions that are calling `Distribution._extended_shape`, just that the `sample` method's interface will differ. 

>  Let me know if y'all want to move forward, and I'm happy to take on writing in the changes.

Sounds good to me. I think it will be nice to have consistency with other tensor constructors. @fritzo - what do you think?

**Comment by fritzo** [comment]
Hmm, I think it will still be complex to maintain backwards compatibility. E.g. I see lots of code that passes `sample_shape` as a kwarg, and to maintain compatibility we would need something like
```diff
- def sample(self, sample_shape=None):
-     if sample_shape is None:
-         sample_shape = torch.Size()
+ def sample(self, *args, **kwargs):
+     sample_shape = kwargs.pop('sample_shape', args)
+     assert not kwargs
      ...
```
At this point I'm thinking this change doesn't benefit users. Moreover it makes it more difficult to add custom kwargs like `mcmc_samples` for approximate samplers.

Currently torch.distributions has a somewhat easy to use class hierarchy, and it's common for users to create custom distributions for particular applications; e.g. I write custom distributions for about half of the projects I work on. By making `.sample()` param parsing more complex, we would increase the friction required to create custom distributions.

**Pros:** saves two parentheses and one comma, when drawing multiple samples
**Cons:** makes it more complex for users to write custom distributions
