### ISSUE TITLE
Windows code with hooks getting stuck in v1.0.1

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#17840]
## 🐛 Bug

@jph00 reports that fast.ai lesson code gets stuck in Windows with v1.0.1

- full thread is here: https://forums.fast.ai/t/lesson-1-notebook-stuck-in-create-cnn/37486

> seems like it may be due to hooks. we use hooks to automatically find the number of activations to automatically add the appropriate new head for transfer learning

> you can replicate the problem by simply running the lesson 1 notebook, or by creating a cnn learner and trying to fit:

```
learn = cnn_learner(data, models.resnet34, metrics=error_rate)
learn.fit(1,0.1)
```

cc: @peterjc123 can you look / replicate / debug

cc @ezyang @gchanan @peterjc123

**Comment by sgugger** [comment]
I investigated a bit more this bug and it seems to come from the interaction of `torch.set_num_threads` and forward hooks (new with 1.0.1 AFAICT).

Here is a minimal reproducible example in pure PyTorch:
```
import torch
import torch.nn as nn
from torchvision.models import resnet34

class OutputHook():
    "Create a hook on `m` with to store the output."
    def __init__(self, m):
        self.hook = m.register_forward_hook(self.hook_fn)
        self.removed = False

    def hook_fn(self, module, input, output):
        "Applies `hook_func` to `module`, `input`, `output`."
        self.stored = output
        
    def remove(self):
        "Remove the hook from the model."
        if not self.removed:
            self.hook.remove()
            self.removed=True

torch.set_num_threads(4)
model = resnet34(pretrained=True)
hooks = [OutputHook(m) for m in model.children()]
model.eval()(torch.randn(1, 3, 64, 64))
```
the last line hangs forever (on Windows only).

`torch.set_num_threads(1)` solves the problem, and also the code only gets stuck if we register more than one hook, aka
```
torch.set_num_threads(4)
model = resnet34(pretrained=True)
hooks = [OutputHook(m) for m in list(model.children())[-1]]
model.eval()(torch.randn(1, 3, 64, 64))
```
works.

**Comment by peterjc123** [comment]
Thanks. I'll dig into it when I have time.

**Comment by gchanan** [comment]
@peterjc123 did you get a chance to look into this?

**Comment by peterjc123** [comment]
Sorry, I forgot to do it and will take a look later.

**Comment by peterjc123** [comment]
I tried the code with PyTorch 1.2.0 and it cannot be reproduced anymore.
