### ISSUE TITLE
Build option -DBUILD_SHARED_LIBS=OFF not generating libtorch.a

### ISSUE THREAD

**Issue by sausax** [pytorch/pytorch#17845]
I am not able to generate static library libtorch.a by using -DBUILD_SHARED_LIBS=OFF cmake option. Is there some other cmake option that needs to be enabled for it ?

**Comment by peterjc123** [comment]
Please try -DTORCH_STATIC=ON

**Comment by soumith** [comment]
closed via peterjc123's comment

**Comment by sausax** [comment]
Tried `cmake -DTORCH_STATIC=ON` and `cmake  -DBUILD_SHARED_LIBS=OFF -DTORCH_STATIC=ON`. Still not getting libtorch.a.

**Comment by soumith** [comment]
it's pretty much how we build it: https://github.com/pytorch/builder/blob/master/manywheel/build_common.sh#L125-L135
See the rest of invocations in that shell script as well.
