### ISSUE TITLE
Caffe2 building failure when turning off USE_OPENMP

### ISSUE THREAD

**Issue by pf-zheng** [pytorch/pytorch#17853]
I modified CMakelist.txt to turn off USE_OPENMP. I change option(USE_OPENMP "Use OpenMP for parallel code" ON) into (USE_OPENMP "Use OpenMP for parallel code" OFF).  Then I got compilation error as below. 

I need to to run caffe2 without using openmp for stack trace analysis. Any help on this? 

[2077/2480] Linking CXX executable bin/timer_test
FAILED: : && /usr/bin/c++   -fvisibility-inlines-hidden -D_FORCE_INLINES -D_MWAITXINTRIN_H_INCLUDED -D__STRICT_ANSI__ -DUSE_FBGEMM -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -rdynamic caffe2/CMakeFiles/timer_test.dir/core/timer_test.cc.o  -o bin/timer_test -L/home/pz28/bin/anaconda3/lib lib/libgtest_main.a -Wl,--no-as-needed,/home/pz28/pytorch/build/lib/libcaffe2.so -Wl,--as-needed lib/libprotobuf.a lib/libc10.so -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lm /usr/lib/x86_64-linux-gnu/libdl.so lib/libmkldnn.a lib/libgtest.a -lpthread -Wl,-rpath,/home/pz28/pytorch/build/lib:/home/pz28/bin/anaconda3/lib: && :
/home/pz28/pytorch/build/lib/libcaffe2.so: undefined reference to `GOMP_barrier'
/home/pz28/pytorch/build/lib/libcaffe2.so: undefined reference to `GOMP_parallel'
/home/pz28/pytorch/build/lib/libcaffe2.so: undefined reference to `omp_get_max_threads'
/home/pz28/pytorch/build/lib/libcaffe2.so: undefined reference to `omp_in_parallel'
/home/pz28/pytorch/build/lib/libcaffe2.so: undefined reference to `omp_get_thread_num'
/home/pz28/pytorch/build/lib/libcaffe2.so: undefined reference to `omp_get_num_threads'
collect2: error: ld returned 1 exit status

**Comment by lindsayad** [comment]
I'm getting similar failures when trying to disable openmp
```
/home/lindad/binutils-gdb/installed/bin/ld: /home/lindad/pytorch/pytorch-build/lib/libtorch_cpu.so: undefined reference to `GOMP_barrier'
/home/lindad/binutils-gdb/installed/bin/ld: /home/lindad/pytorch/pytorch-build/lib/libtorch_cpu.so: undefined reference to `GOMP_parallel'
/home/lindad/binutils-gdb/installed/bin/ld: /home/lindad/pytorch/pytorch-build/lib/libtorch_cpu.so: undefined reference to `omp_get_max_threads'
/home/lindad/binutils-gdb/installed/bin/ld: /home/lindad/pytorch/pytorch-build/lib/libtorch_cpu.so: undefined reference to `omp_in_parallel'
/home/lindad/binutils-gdb/installed/bin/ld: /home/lindad/pytorch/pytorch-build/lib/libtorch_cpu.so: undefined reference to `omp_get_thread_num'
/home/lindad/binutils-gdb/installed/bin/ld: /home/lindad/pytorch/pytorch-build/lib/libtorch_cpu.so: undefined reference to `omp_get_num_threads'
```

**Comment by lindsayad** [comment]
May not be related to caffe2 though?
