### ISSUE TITLE
Missing bernoulli_ on torch.cuda.ByteTensor for nn.AlphaDropout

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#1785]
I just updated pytorch, tried nn.AlphaDropout module and got an error complaining on absence of `bernoulli_` on a `ByteTensor`. Either a bug, or a type check missing, or I am doing something stupid.

```python
import torch
nn.AlphaDropout().forward(torch.autograd.Variable(torch.zeros(2, 16, 4, 4).cuda()))
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../torch/nn/modules/dropout.py", line 202, in forward
    return F.alpha_dropout(input, self.p, self.training)
  File ".../torch/nn/functional.py", line 421, in alpha_dropout
    noise.bernoulli_(p)
AttributeError: 'torch.cuda.ByteTensor' object has no attribute 'bernoulli_'
```

**Comment by vadimkantorov** [comment]
It's because of [this](https://github.com/pytorch/pytorch/blob/6626881e7a9d430bd37bd67057ba74b6669a7ccf/torch/nn/functional.py#L420-L421) code:
```python
noise = input.data.new().byte().resize_(input.size())
noise.bernoulli_(p)
```
which fails for cuda inputs because `torch.cuda.ByteTensor` doesn't have `bernoulli_` impl at the moment (at least fails on my installation).

**Comment by fmassa** [comment]
Oups...
I believe we have [`bernoulli` in THC for ByteTensors](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/generic/THCTensorRandom.h), so we should maybe just enable it for cuda tensors in [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/methods/TensorRandom.cwrap#L446).
@apaszke I could send a quick fix to AlphaDropout (making it a bit less efficient by casting to `byte` after calling `bernoulli`), but a proper fix would be to enable bernoulli to cuda. Do you think it's as easy as removing the `!IS_CUDA`?

**Comment by apaszke** [comment]
So I think we should really remove `bernoulli_` as it's very ambiguous. In this case, I think we should use `torch.bernoulli(p, out=input.data.new().byte())` (until we add `dtype`)

**Comment by fmassa** [comment]
@apaszke we need to modify `bernoulli` to support `ByteTensor` before fixing AlphaDropout properly, as currently it's enabled only for [floats and doubles](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/methods/TensorRandom.cwrap#L426). Should I put this in a hold while waiting for https://github.com/pytorch/pytorch/issues/1747 to be fixed (you self-assigned yourself)?

**Comment by apaszke** [comment]
You can do that if you want. I think this issue is a 2 line change

**Comment by fmassa** [comment]
The change in `bernoulli` would either add GPU support for `bernoulli_` (which might be deprecated / removed soon) or change the semantics of `bernoulli`. I could give it a try tomorrow (probably adding the CUDA to `bernoulli_`).

**Comment by apaszke** [comment]
I think it's better to just enable it for ByteTensors at the function API level `torch.bernoulli` and deprecate `bernoulli_` immediately (don't bother with modifying it, just raise a warning in `before_call:`)

**Comment by fmassa** [comment]
Reminder to myself: add pointer to documentation in `docs/source/nn.rst` for both AlphaDropout and SELU. I always forget that...
