### ISSUE TITLE
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got NoneType

### ISSUE THREAD

**Issue by ajaysg** [pytorch/pytorch#17858]
My code is

a=torch.randn(1,80,100,requires_grad=True)
torch.onnx.export(waveglow,a, "waveglow.onnx")

I am trying to export a PyTorch model to ONNX format so i can use it in TensorRT. while testing my model in PyTorch the input tensor dimension is (1,80,x) where x varies depending on the input text length(the model i am using is TTS model named waveglow)

when i try to run the above code for exporting the model to onnx, I am always getting this error

RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got NoneType
Please help

**Comment by suo** [comment]
Thanks for the report! Can you provide a script that we can run to reproduce the error you are seeing? That would help us investigate.

**Comment by ajaysg** [comment]
Yes of course
The link to the pretrained model is

https://drive.google.com/file/d/1cjKPHbtAMh_4HTHmuIGNkbOkPBD9qwhj/view?usp=sharing

waveglow=torch.load(model_path)

a=torch.randn(1,80,100,requires_grad=True)

torch.onnx.export(waveglow,a, "waveglow.onnx")

**Comment by suo** [comment]
When I try to load the model, I get the following error:
```
Traceback (most recent call last):
  File "/Users/suo/scratch/test.py", line 3, in <module>
    waveglow=torch.load("/Users/suo/Downloads/waveglow_old.pt")
  File "/Users/suo/pytorch/torch/serialization.py", line 385, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/Users/suo/pytorch/torch/serialization.py", line 572, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'glow_old'
```

Could you try to create a more minimal script that would reproduce the problem? It shouldn't have external dependencies

**Comment by ajaysg** [comment]
Yes sure....I will do it

**Comment by suo** [comment]
Closing as we don't have repro. Feel free to reopen!

**Comment by andreskull** [comment]
Here is the reproducible code that results in the same error:

`import torch.nn.functional as F
import torch.nn as nn
import torch
import math
from torch.utils.tensorboard import SummaryWriter

class Actor(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Sequential(
            nn.Linear(23, 8),
            nn.ReLU(),
            nn.Dropout(p=0.15),
        )
        self.out = nn.Linear(8, 5)
        self._init_param()
        self.optim = torch.optim.Adam(self.parameters())

    def _init_param(self):
        nn.init.normal_(self.hidden[0].weight.data,
                        mean=0., std=math.sqrt(2 / self.hidden[0].in_features))
        nn.init.constant_(self.hidden[0].bias.data, 0.)
        nn.init.constant_(self.out.weight.data, 0.)
        nn.init.constant_(self.out.bias.data, 1.)

    def forward(self, x):
        x = self.hidden(x)
        a = F.softmax(self.out(x), dim=1)
        return a

if __name__ == '__main__':
    writer = SummaryWriter()
    model = Actor()
    writer.add_graph(model)
`

**Comment by suo** [comment]
@andreskull thanks for your repro!

@orionr is this perhaps related to the tensorboard onnx export? Can you or @lanpa take a look

**Comment by orionr** [comment]
@andreskull thank you for the code! For `add_graph`, you need to pass through a sample bit of data in order to trace the graph. Please take a look at https://pytorch.org/docs/stable/tensorboard.html at the  top for an example. Does passing a sample through work for you?

**Comment by ajaysg** [comment]
I was getting the error when I tried a import a pytorch model(. Pt) to onmx
format. Still I could not find out a way

**Comment by ajaysg** [comment]
*onnx fromat
