### ISSUE TITLE
Build error on windows 

### ISSUE THREAD

**Issue by ankur6ue** [pytorch/pytorch#17852]
Trying to build pytorch master on my x64 Windows machine with Python 3.7 64 bit from Anaconda and getting the following build errors:

C:\Telesens\dev\ML\PyTorch\pytorch>call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.11
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.6
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Telesens\dev\ML\PyTorch\pytorch>
C:\Telesens\dev\ML\PyTorch\pytorch>python setup.py install
Building wheel torch-1.1.0a0+81e025d
-- Building version 1.1.0a0+81e025d
['cmake',
 'C:\\Telesens\\dev\\ML\\PyTorch\\pytorch',
 '-GNinja',
 '-DBUILDING_WITH_TORCH_LIBS=ON',
 '-DBUILD_BINARY=False',
 '-DBUILD_CAFFE2_OPS=True',
 '-DBUILD_PYTHON=True',
 '-DBUILD_SHARED_LIBS=ON',
 '-DBUILD_TEST=True',
 '-DBUILD_TORCH=ON',
 '-DCAFFE2_STATIC_LINK_CUDA=False',
 '-DCMAKE_BUILD_TYPE=Release',
 '-DCMAKE_CXX_FLAGS=  /EHa',
 '-DCMAKE_C_FLAGS=  /EHa',
 '-DCMAKE_EXE_LINKER_FLAGS=',
 '-DCMAKE_INSTALL_PREFIX=C:\\Telesens\\dev\\ML\\PyTorch\\pytorch/torch',
 '-DCMAKE_PREFIX_PATH=C:\\Anaconda3\\Lib\\site-packages',
 '-DCMAKE_SHARED_LINKER_FLAGS=',
 '-DINSTALL_TEST=True',
 '-DNCCL_EXTERNAL=False',
 '-DNUMPY_INCLUDE_DIR=C:/Anaconda3/lib/site-packages/numpy/core/include',
 '-DONNX_ML=False',
 '-DONNX_NAMESPACE=onnx_torch',
 '-DPYTHON_EXECUTABLE=C:/Anaconda3/python.exe',
 '-DPYTHON_INCLUDE_DIR=C:/Anaconda3/include',
 '-DPYTHON_LIBRARY=C:/Anaconda3/libs/python37.lib',
 '-DTHD_SO_VERSION=1',
 '-DTORCH_BUILD_VERSION=1.1.0a0+81e025d',
 '-DUSE_CUDA=True',
 '-DUSE_DISTRIBUTED=False',
 '-DUSE_FBGEMM=True',
 '-DUSE_FFMPEG=False',
 '-DUSE_LEVELDB=False',
 '-DUSE_LMDB=False',
 '-DUSE_MKLDNN=True',
 '-DUSE_NCCL=False',
 '-DUSE_NNPACK=True',
 '-DUSE_NUMPY=True',
 '-DUSE_OPENCV=False',
 '-DUSE_QNNPACK=True',
 '-DUSE_ROCM=False',
 '-DUSE_SYSTEM_EIGEN_INSTALL=OFF',
 '-DUSE_SYSTEM_NCCL=False',
 '-DUSE_TENSORRT=False',
 '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON']
-- The CXX compiler identification is MSVC 19.16.27026.1
-- The C compiler identification is MSVC 19.16.27026.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Telesens/dev/ML/PyTorch/pytorch/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/Miniconda3/Library/bin/ninja.exe cmTC_a6060
    [1/2] Building CXX object CMakeFiles\cmTC_a6060.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_a6060.exe
    FAILED: cmTC_a6060.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_a6060.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\link.exe /nologo CMakeFiles\cmTC_a6060.dir\testCXXCompiler.cxx.obj  /out:cmTC_a6060.exe /implib:cmTC_a6060.lib /pdb:cmTC_a6060.pdb /version:0.0  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\link.exe /nologo CMakeFiles\cmTC_a6060.dir\testCXXCompiler.cxx.obj /out:cmTC_a6060.exe /implib:cmTC_a6060.lib /pdb:cmTC_a6060.pdb /version:0.0 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_a6060.dir/intermediate.manifest CMakeFiles\cmTC_a6060.dir/manifest.res" failed (exit code 1120) with the following output:
    testCXXCompiler.cxx.obj : error LNK2001: unresolved external symbol __RTC_InitBase
    testCXXCompiler.cxx.obj : error LNK2001: unresolved external symbol __RTC_Shutdown
    LINK : error LNK2001: unresolved external symbol _mainCRTStartup
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\kernel32.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\user32.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\gdi32.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\winspool.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\shell32.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\ole32.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\oleaut32.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\uuid.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\comdlg32.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\advapi32.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\lib\x64\MSVCRTD.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
    cmTC_a6060.exe : fatal error LNK1120: 3 unresolved externals
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Telesens/dev/ML/PyTorch/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "C:/Telesens/dev/ML/PyTorch/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 715, in <module>
    build_deps()
  File "setup.py", line 287, in build_deps
    build_dir='build')
  File "C:\Telesens\dev\ML\PyTorch\pytorch\tools\build_pytorch_libs.py", line 239, in build_caffe2
    my_env)
  File "C:\Telesens\dev\ML\PyTorch\pytorch\tools\build_pytorch_libs.py", line 219, in run_cmake
    check_call(cmake_args, cwd=build_dir, env=my_env)
  File "C:\Anaconda3\lib\subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Telesens\\dev\\ML\\PyTorch\\pytorch', '-GNinja', '-DBUILDING_WITH_TORCH_LIBS=ON', '-DBUILD_BINARY=False', '-DBUILD_CAFFE2_OPS=True', '-DBUILD_PYTHON=True', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_TEST=True', '-DBUILD_TORCH=ON', '-DCAFFE2_STATIC_LINK_CUDA=False', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_FLAGS=  /EHa', '-DCMAKE_C_FLAGS=  /EHa', '-DCMAKE_EXE_LINKER_FLAGS=', '-DCMAKE_INSTALL_PREFIX=C:\\Telesens\\dev\\ML\\PyTorch\\pytorch/torch', '-DCMAKE_PREFIX_PATH=C:\\Anaconda3\\Lib\\site-packages', '-DCMAKE_SHARED_LINKER_FLAGS=', '-DINSTALL_TEST=True', '-DNCCL_EXTERNAL=False', '-DNUMPY_INCLUDE_DIR=C:/Anaconda3/lib/site-packages/numpy/core/include', '-DONNX_ML=False', '-DONNX_NAMESPACE=onnx_torch', '-DPYTHON_EXECUTABLE=C:/Anaconda3/python.exe', '-DPYTHON_INCLUDE_DIR=C:/Anaconda3/include', '-DPYTHON_LIBRARY=C:/Anaconda3/libs/python37.lib', '-DTHD_SO_VERSION=1', '-DTORCH_BUILD_VERSION=1.1.0a0+81e025d', '-DUSE_CUDA=True', '-DUSE_DISTRIBUTED=False', '-DUSE_FBGEMM=True', '-DUSE_FFMPEG=False', '-DUSE_LEVELDB=False', '-DUSE_LMDB=False', '-DUSE_MKLDNN=True', '-DUSE_NCCL=False', '-DUSE_NNPACK=True', '-DUSE_NUMPY=True', '-DUSE_OPENCV=False', '-DUSE_QNNPACK=True', '-DUSE_ROCM=False', '-DUSE_SYSTEM_EIGEN_INSTALL=OFF', '-DUSE_SYSTEM_NCCL=False', '-DUSE_TENSORRT=False', '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON']' returned non-zero exit status 1.

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by peterjc123** [comment]
Your environment is messed up. It was picking the win64 winsdk library and the x86 toolchain. Please check your PATH and your actvation script to see if there is an error there.
