### ISSUE TITLE
.cuda() cost much more time

### ISSUE THREAD

**Issue by luhc15** [pytorch/pytorch#17854]
when  I warp a  Tensors :
fy, fx = torch.meshgrid(torch.arrange(0, h), torch.arrange(0, w)

when running operation:
new_fx = torch.add(fx.float().cuda(), flow(0)]
new_fy = torch.add(fy.float().cuda(), flow(1)]

b is a gpu Tensor, while fx is a cpu tenor,  so I transform a into a gpu Tensor to add them. while i found .cuda() op takes a lot of time first.  why it takes too many time when a cpu tensor  transitted  into a gpu tensor

**Comment by luhc15** [comment]
also i found  A[c1, :,:,:] takes much more time than A[c1:c1+1, :,:,:,]

**Comment by ezyang** [comment]
The `cuda()` operation has to transmit a tensor from CPU memory to CUDA memory. The larger your tensor is, the longer this transfer will take. There isn't really a way around it. If possible, try to keep your operations in CUDA memory, so that you don't have to do data transfer.

**Comment by ezyang** [comment]
Also, the first time you call cuda(), we must initialize the cuda runtime, which takes some time. If you have a lot of GPUs and you are not using all of them, you can reduce this cost by setting `CUDA_VISIBLE_DEVICES` only to the GPUs you want to use.
