### ISSUE TITLE
[C++ Frontend] ONNX export

### ISSUE THREAD

**Issue by blackccpie** [pytorch/pytorch#17869]
## 🚀 Feature

Having torch onnx feature available through the C++ API.

## Motivation

I have some C++ frontend trained models, and I want to export them in onnx format in order to use them in external inference engines.

## Pitch

Same API as the python's `torch.onnx.export` would be enough.

## Alternatives

An alternative would be to have easy C++ frontend model import in the python side, but I think this is more related to https://github.com/pytorch/pytorch/issues/16367

cc @BowenBao @neginraoof

**Comment by bhilburn** [comment]
Yup, this function would be of great utility. Given that it doesn't currently exist, I'm now looking for some sort of hack-around.

@blackccpie - Did you land on a solution for this?

**Comment by blackccpie** [comment]
@bhilburn : no solution for this issue yet :-( 
One possible idea could be to try to export the model using the C++ frontend JIT API, and then convert from JIT to ONNX using python API, but that's quite cumbersome!

**Comment by ziyuv** [comment]
Is there an update or plan on this?

**Comment by kbthornton** [comment]
I also define and train my NNs in PyTorch C++. I need to do inference with Onnx. Rather cumbersome to (1) export parameters from C++ into custom binary file (cannot use torch::save because not compatible with Python torch.load), (2) define the same NN in PyTorch Python, (3) In Python, read parameters and set into NN, (3) Export model from PyTorch Python to Onnx.

**Comment by garymm** [comment]
@swilson314 could you please upload the .pt file produced by `torch::save` somewhere so I can try to reproduce?

**Comment by swilson314** [comment]
@garymm here you go
[Model.zip](https://github.com/pytorch/pytorch/files/7239083/Model.zip)

**Comment by swilson314** [comment]
@garymm the input for this particular model was incorrect above, but even with fix I still see identical errors. Maybe this will make a difference if you get it working ;)

TestInput = torch.rand((1, 25, 200))

**Comment by swilson314** [comment]
@garymm are you working towards a fix on this? I've got a bunch of pytorch c++ trained models and I'd love it if I didn't have to recreate them in python (by hand) in order to generate onnx versions.

**Comment by garymm** [comment]
No one is currently working on it.

**Comment by henbucuoshanghai** [comment]
how to solve it?

**Comment by swilson314** [comment]
Any progress on this? Is there any way to raise the priority?

**Comment by JinXiaozhao** [comment]
Any progress on this? Is there any way to raise the priority?

**Comment by Zhangzhenzhou96** [comment]
Any progress on this? Is there any way to raise the priority?
Need to export ONNX in C++.
