### ISSUE TITLE
error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated caused by outdated MKL

### ISSUE THREAD

**Issue by jbohnslav** [pytorch/pytorch#17874]
## 🐛 Bug

Building from source fails with Nvidia driver 418.43, CUDA 10.1, on Ubuntu 18.04.

## To Reproduce

1. Uninstall all CUDA versions, Nvidia drivers
2. Reinstall CUDA 10.1, CuDNN 7.5.0, NCCL 2.4.2
3. Make a fresh conda environment
4. `git clone --recursive https://github.com/pytorch/pytorch`
5. `python setup.py install`

End of the error message is as follows:
```
[ 44%] Linking CXX executable ../../bin/c10_intrusive_ptr_test
[ 44%] Built target c10_intrusive_ptr_test
[ 44%] Linking CXX static library ../../../lib/libprotoc.a
[ 44%] Built target libprotoc
[ 44%] Linking CXX static library ../../../lib/libgloo_cuda.a
[ 44%] Built target gloo_cuda
Makefile:140: recipe for target 'all' failed
```

Output of build.log: https://gist.github.com/jbohnslav/af16187a12bd863030134cceaefc157b

## Expected behavior

Expected build to complete

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.105
GPU models and configuration: 
GPU 0: GeForce GT 1030
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 418.43
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip3] numpy==1.15.4
[conda] mkl                       2019.3                intel_199    intel
[conda] mkl-include               2019.3                intel_199    intel

## Additional context

Output of `nvcc --version`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105
```
Output of `nvidia-smi`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.43       Driver Version: 418.43       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 1030     Off  | 00000000:0A:00.0  On |                  N/A |
| 38%   47C    P0    N/A /  30W |    640MiB /  2001MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:0B:00.0 Off |                  N/A |
| 20%   35C    P8    10W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:41:00.0 Off |                  N/A |
| 27%   37C    P8    16W / 250W |      2MiB / 11176MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1609      G   /usr/lib/xorg/Xorg                            28MiB |
|    0      1651      G   /usr/bin/gnome-shell                          48MiB |
|    0      1996      G   /usr/lib/xorg/Xorg                           292MiB |
|    0      2128      G   /usr/bin/gnome-shell                         187MiB |
|    0      2152      G   /opt/teamviewer/tv_bin/TeamViewer              1MiB |
|    0      2615      G   ...uest-channel-token=18044152371549415751    80MiB |
+-----------------------------------------------------------------------------+
```

**Comment by soumith** [comment]
it's kinda weird, but the error is:

```
/home/jim/Documents/python/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:53: error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It looks like your compiler is doing a `-Werror` for deprecated declarations, which isn't normal.

You can workaround the compile with `NO_MKLDNN=1 python setup.py install`

**Comment by jbohnslav** [comment]
Thanks so much @soumith, this works! I'm not sure why my compilation is different from anyone else's. Will operations on CPU be significantly slower due to the lack of MKLDNN?

**Comment by soumith** [comment]
@jbohnslav yes CPU convolutions will be slower by 10x. All other CPU operations will be unaffected.

**Comment by fzd9752** [comment]
> it's kinda weird, but the error is:
> 
> ```
> /home/jim/Documents/python/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:53: error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
>                  weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
>                                     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> It looks like your compiler is doing a `-Werror` for deprecated declarations, which isn't normal.
> 
> You can workaround the compile with `NO_MKLDNN=1 python setup.py install`

Hi @soumith, same error reported with latest build `v1.0rc0-3168-g8895bfba6`. 

Currently, pytorch works well without mkl-dnn. 

---
## Environment

OS: Ubuntu 18.04.2 LTS
GCC version: 7.3.0
CMake version: version 3.10.2

Python version: 3.7
CUDA runtime version: 10.1.105
GPU models and configuration:
GPU 0: GeForce RTX 2079

Nvidia driver version: 418.43
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

**Comment by Bronek** [comment]
I faced the same error, and resolved it with the addition of `-Wno-error=deprecated-declarations` . Since I also use other optimisation flags, my build Dockerfile simple has this extra line
```
ENV CFLAGS="-march=native -mtune=intel -mavx -mavx2 -mfma -msse4.2 -Wno-error=deprecated-declarations"
```

**Comment by jzenn** [comment]
@Bronek I have been trying for several days now to install PyTorch with CUDA 10.1 and did not manage to install it properly. I have to use CUDA 10.1 since it is the version of the cluster I am training on. Since you managed to install PyTorch with CUDA 10.1 would it be ok for you if shared your Dockerfile? Thank you very much in advance.

**Comment by ezyang** [comment]
This is https://github.com/intel/mkl-dnn/issues/440. According to the MKL-DNN developers, this can occur if you're compiling against an outdated MKL library. Try updating your MKL.

**Comment by Bronek** [comment]
Right sorry I missed your question @jzenn  I do not use intel-mkl so I guess that explain why this has worked for me.

**Comment by jzenn** [comment]
@Bronek No Problem. Thanks a lot anyway.

**Comment by jinzhenmu** [comment]
> I faced the same error, and resolved it with the addition of `-Wno-error=deprecated-declarations` . Since I also use other optimisation flags, my build Dockerfile simple has this extra line
> 
> ```
> ENV CFLAGS="-march=native -mtune=intel -mavx -mavx2 -mfma -msse4.2 -Wno-error=deprecated-declarations"
> ```

how to change build Dockerfile? I faced the same error.

**Comment by jinzhenmu** [comment]
@Bronek 
how to change the build Dockerfile? or where is the build Dockerfile?  I faced the same error,qqq
