### ISSUE TITLE
Dataloader halts when used with Keras TensorFlow Backend code

### ISSUE THREAD

**Issue by morawi** [pytorch/pytorch#17871]
## 🐛 Bug
I was using one of the packages written with Keras TensorFlow backend. 
I wrote a `Dataset` class, which invokes a function from the package via `__getitem__` and it worked fine, by testing the `Dataset` and / or the dataloader outside the model. Clearly, to reduce the memory that the `Dataset` needs, I am implementing the function provided via Keras TF-Backend in `__getitem__` in a class I defined for its implementation, to be able to do a few manipulations to the  string called via `__getitem__`. 

However, the dataloader halts when I implement it during testing, have not tried training, as I am measuring chance-level performance prior to training. I have tried this scenario with lots of other `Dataset` classes, i.e. to test prior to train, some provided by PyTorch, and others I wrote myself and everything went well.

NB. Not sure if this is a problem with using PyTorch and Keras TF-Backend, or invoking `__getitem__` twice, one for the `Dataset` class that invokes the function of Keras TF-Backend via `__getitem__`.

## To Reproduce: 

To make it easier for debugging this issue, any Keras Tensorflow package can be used, I guess. But, here's [the one](https://github.com/IntuitionEngineeringTeam/chars2vec) I was using. To reproduce, it is possible to write a `Dataset` class that contains a function to generate 1000 words (strings), then, use the function `vectorize_words`  to produce the `target` value in my code below, by defining another class for this Kers TF-Backed implementation. In the below code snippet, `word_str` is the word, and data is a `PIL` image related to that word. I am using `ResNet-152` from PyTorch, but that is irrelevant as I noticed that the program halts at the line  for `data, target, word_str in test_loader` during debugging and never gets to the next line that moves `data` and `target` to the `device` (I am using the GPU here).

```
        model.eval()  
        with torch.no_grad():
            for data, target, word_str in test_loader: 
                data, target = data.to(device), target.to(device)
                output = model(data)
                loss = criterion(output.float(), target.float())
                total_loss += loss.item()
```

## Expected behavior
I expected the dataloader to work as intended. To get around this problem, I had to save the vectors that I obtained from each string into a torch tensor inside the `Dataset` class, via `self._vector = torch.empty(len(data_idx), len_word_vector)`, and to fill it then with all the values, for each word, prior to using the dataloader, and it worked. 

## Environment

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 7.5.17
GPU models and configuration: 
GPU 0: Quadro P400
GPU 1: TITAN Xp COLLECTORS EDITION

Nvidia driver version: 384.130
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.14.3
[pip3] numpydoc==0.7.0
[pip3] pytorch-nlp==0.3.7.post1
[pip3] torch==0.4.0
[pip3] torchfile==0.1.0
[pip3] torchtext==0.3.1
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.1             h19d6760_4  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] pytorch                   0.4.0           py36_cuda8.0.61_cudnn7.1.2_1    pytorch
[conda] pytorch-nlp               0.3.7.post1              pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchtext                 0.3.1                    pypi_0    pypi
[conda] torchvision               0.2.1                    py36_1    pytorch

```
$ cat /usr/local/cuda/version.txt
CUDA Version 8.0.61

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

$ Python
>>> import tensorflow
>>> tensorflow.__version__
'1.13.1'
>>> import keras
Using TensorFlow backend.
>>> keras.__version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'keras' has no attribute '__version'
>>> keras.__version__
'2.2.4'
>>> import platform; print(platform.platform())
Linux-4.4.0-142-generic-x86_64-with-debian-stretch-sid
>>> import sys; print("Python", sys.version)
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]

```
```
$ cat /home/malrawi/anaconda3/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
```

## Other issues
When running the code, I got the following warning. But, the program is running correctly, as I have checked the visualizations of the words' vectors, in addition to the results I am getting with the deep learning model. 

Using TensorFlow backend.
WARNING:tensorflow:From /home/malrawi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

cc @SsnL @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
Hey @morawi,
Got notification recently by triage. Just wondering if this issue still exists?

**Comment by morawi** [comment]
> Hey @morawi,
> Got notification recently by triage. Just wondering if this issue still exists?

It's been some time since. Don't remember how I worked around it.  Feel free to close the issue.

**Comment by ejguan** [comment]
Sorry about that. Feel free to re-open it whenever needed. Thanks.
