### ISSUE TITLE
ProcessGroupNCCL error/timeout handling

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#17882]
As of NCCL 2.4 there are functions to detect I/O errors and abort running kernels. This is required to implement timeouts and force workers to raise an error or terminate when other workers fail.

See https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/api/comms.html and `ncclCommAbort` and `ncclCommGetAsyncError` and https://devblogs.nvidia.com/massively-scale-deep-learning-training-nccl-2-4/ for an example.

**Comment by pritamdamania87** [comment]
@pietern Should we close this out? @mrshenli created a follow up for error handling within the server: https://github.com/pytorch/pytorch/issues/24906.

**Comment by pietern** [comment]
@pritamdamania87 Yep, sounds good.
