### ISSUE TITLE
LMDB ERROR caffe2

### ISSUE THREAD

**Issue by hongyx11** [pytorch/pytorch#17888]
read database error.
I just use the standard steps to install pytorch and caffe2.

$conda create -n newenv python=3.6
$conda install pytorch-nightly-cpu -c pytorch

run the lmdb test code https://caffe2.ai/doxygen-python/html/lmdb__create__example_8py_source.html
it asks me to install lmdd
$conda install lmdb

Then the error

>>> Read database...
WARNING:root:[====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
WARNING:caffe2.python.workspace:Original python traceback for operator `0` in network `lmdbtest_init` in exception above (most recent call last):
WARNING:caffe2.python.workspace:  File "lmdb_example.py", line 108, in <module>
WARNING:caffe2.python.workspace:  File "lmdb_example.py", line 104, in main
WARNING:caffe2.python.workspace:  File "lmdb_example.py", line 72, in read_db_with_caffe2
WARNING:caffe2.python.workspace:  File "/home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/model_helper.py", line 423, in TensorProtosDBInput
WARNING:caffe2.python.workspace:  File "/home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/helpers/db_input.py", line 14, in db_input
Traceback (most recent call last):
  File "lmdb_example.py", line 108, in <module>
    main()
  File "lmdb_example.py", line 104, in main
    read_db_with_caffe2(args.output_file, checksum)
  File "lmdb_example.py", line 76, in read_db_with_caffe2
    workspace.RunNetOnce(model.param_init_net)
  File "/home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/workspace.py", line 219, in RunNetOnce
    StringifyProto(net),
  File "/home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/workspace.py", line 198, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at db.h:196] db_. Cannot find db implementation of type lmdb (while trying to open test)
Error from operator:
output: "dbreader_test" name: "" type: "CreateDB" arg { name: "db" s: "test" } arg { name: "db_type" s: "lmdb" }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x59 (0x2b87258a9479 in /home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: <unknown function> + 0x17baeea (0x2b8723dafeea in /home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #2: <unknown function> + 0x1617b95 (0x2b8723c0cb95 in /home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #3: caffe2::SimpleNet::Run() + 0x161 (0x2b8723cdf651 in /home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #4: caffe2::Workspace::RunNetOnce(caffe2::NetDef const&) + 0x2b (0x2b8723d164cb in /home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #5: <unknown function> + 0x4feaf (0x2b87222f6eaf in /home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x88fa8 (0x2b872232ffa8 in /home/hongy0a/condaenv/anaconda3/envs/mustwork36/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #29: __libc_start_main + 0xf0 (0x2b8713448830 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by xualan** [comment]
do you have resolve it?

**Comment by xualan** [comment]
i also met this problem

**Comment by hongyx11** [comment]
no

**Comment by svmsunny** [comment]
I solve this problem by installing the PyTorch from Source, https://github.com/pytorch/pytorch#from-source. and  
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ USE_LMDB=ON python setup.py install
The default config of USE_LMDB is OFF.

**Comment by hongyx11** [comment]
> I solve this problem by installing the PyTorch from Source, https://github.com/pytorch/pytorch#from-source. and
> MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ USE_LMDB=ON python setup.py install
> The default config of USE_LMDB is OFF.
> 
> Simiar Issue:
> [#10119 (comment)](https://github.com/pytorch/pytorch/issues/10119#issuecomment-419472461)

proud of you! will try it.

**Comment by shalijiang** [comment]
thanks! this works!
