### ISSUE TITLE
Check that outputs and grad_outputs have same shape in torch.autograd.grad() 

### ISSUE THREAD

**Issue by zplizzi** [pytorch/pytorch#17893]
## 🚀 Feature
If I'm understanding things right, for every item in `outputs`, the corresponding item in `grad_outputs` should have the same shape in the function `torch.autograd.grad()`. If this is the case, there should be a check that the shapes are identical.

## Motivation

I accidentally passed a tensor (of ones) with the wrong shape as `grad_outputs`, and silently got really weird results. Took a while debugging to figure out what the cause was.

**Comment by jalenmorgan** [comment]
This looks like a good idea, as it will help narrow down the problem in the case of unmatched shapes.  The documentation for _torch.autograd.grad_ says, 

> grad_outputs should be a sequence of length matching output containing the pre-computed gradients w.r.t. each of the outputs.

So, you're right, they should be the same shape (Except when grad_outputs = None). I'd be happy to work on implementing this feature.

**Comment by soumith** [comment]
seems reasonable. thanks for working on it @jalenmorgan !
