### ISSUE TITLE
custome collate function cannot get _use_shared_memory

### ISSUE THREAD

**Issue by cy69855522** [pytorch/pytorch#17909]
Thx a lot for such a wonderful package~
But when I wrote a custom function for the Dataloader's collate_fn, I found I cannot get the value of variable - “_use_shared_memory” in torch.utils.data._utils.collate.py
`ModuleNotFoundError: No module named 'torch.utils.data._utils'`
I was thinking if you could give me some suggestions. I don't want to change the original code of pytorch locally.

**Comment by soumith** [comment]
cc: @ssnl

**Comment by SsnL** [comment]
Let’s expose that!

**Comment by cy69855522** [comment]
> Let’s expose that! I’ll add this field to the worker info in the upcoming PR.

Thx a lot~

**Comment by SsnL** [comment]
you can use `torch.utils.data.get_worker_info() != None` to get the same information (whether you are in a worker process) after https://github.com/pytorch/pytorch/pull/19228
