### ISSUE TITLE
torch.distributed.is_available() return False

### ISSUE THREAD

**Issue by LokeZhou** [pytorch/pytorch#17900]
I try at win7 and mac ,but when i 
    print(torch.distributed.is_available()),
    all return False

my Configure the environment ：
win7:.VC++14.0+python3.7+anaconda3+cuda9.0+cudnn7.1+pytorch1.0.0(64 bit)
mac:pyton3.7+anaconda7+pytorch1.0.0

at win7,when i print(torch.cuda.is_available()),return true.i also can use single gpu to run my network。but when i try to use torch.distributed ,return False.On the other hand，at win7  or mac ,when i try:

print(torch._C._c10d_init())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch._C' has no attribute '_c10d_init'

so i think is torch._C is error？

i install pytorch at mac use command:   conda install pytorch torchvision -c pytorch
and offline installation at win7 use command:conda install --offline pytorch-1.0.1-py3.7_cuda90_cudnn7_1.tar.bz2

how to solve the problem？
Thanks for comment！

**Comment by mrshenli** [comment]
In v0.4, `torch.distributed.is_available()` calls [`torch._C._has_distributed`](https://github.com/pytorch/pytorch/blob/3749c581b79cba49f511b19fa02c0f50fa05b250/torch/distributed/__init__.py#L31), which links to [here](https://github.com/pytorch/pytorch/blob/3749c581b79cba49f511b19fa02c0f50fa05b250/torch/csrc/Module.cpp#L243). It seems you installed PyTorch with

**Comment by mrshenli** [comment]
@LokeZhou Gloo is not available on MacOS, but you can still use MPI. To do that, need to compile from source with USE_GLOO=OFF.  (learned from @pietern)
