### ISSUE TITLE
Incorrect behaviour of min() and argmin()

### ISSUE THREAD

**Issue by Markus-Goetz** [pytorch/pytorch#17914]
## 🐛 Bug

PyTorch's implementation of the argmin() function returns incorrect (maybe rather unexpected results) when using the argmin() and the min() function on tensors with dimensions where the minimal value appears multiple times. PyTorch picks the last(!) index with said value, whereas one would assume that the very first occurrence is reported. This is inconsistent with numpy's, Eigen's, C++ STL etc.

## To Reproduce

PyTorch

```
In [80]: a = torch.triu(torch.ones((5,5,)))

In [81]: a
Out[81]: 
tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [82]: a.min(dim=0)
Out[82]: (tensor([0., 0., 0., 0., 1.]), tensor([4, 4, 4, 4, 4]))
```

## Expected behavior

numpy

```
In [83]: b = np.triu(np.ones((5,5,)))

In [84]: b
Out[84]: 
array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

In [85]: b.min(0), b.argmin(0)
Out[85]: (array([0., 0., 0., 0., 1.]), array([1, 2, 3, 4, 0]))
```

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Fedora release 27 (Twenty Seven)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6)
CMake version: version 3.11.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.14.6
[pip3] torch==1.0.0
[conda] Could not collect

## Additional context

See numpy's argmin() documentation: https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html

**Comment by SsnL** [comment]
> PyTorch picks the last(!) index with said value, 
This isn't guaranteed

> whereas one would assume that the very first occurrence is reported. 
The assumption isn't reasonable. No where did pytorch ever make promise about which one it returns. It computes the correct argmin/max according to mathematical definition after all.

**Comment by Markus-Goetz** [comment]
PyTorch does indeed not make any promise about this behaviour and it is indeed mathematically correct as it works now. 

However, I am arguing it should behave as suggested. Several frameworks implement it in the way described and therefore users may silently assume that Torch also does.

**Comment by vishwakftw** [comment]
@SsnL maybe we should consider adding a note to the docs about this non-determinism to clear any ambiguity.

**Comment by soumith** [comment]
@Markus-Goetz repasting my comment from https://github.com/pytorch/pytorch/issues/17738#issuecomment-471365962

the only determinism we aim to have is hashed on device, and for CPU, single-threaded.
Even across different kinds of GPUs, all bets are off.

We cannot guarantee cross-device, cross-CPU-type determinism due to severe performance cliffs that'll result from such a constraint.

For example, to guarantee that we pick the first argmax (or argmin) element, we have to add an additional pass in our CUDA kernel to sort or order the results, which costs performance.

> This is inconsistent with numpy's, Eigen's, C++ STL etc.

If you see, you have given examples of CPU kernels, where this is easy to guarantee without significant performance regression.

**Comment by Markus-Goetz** [comment]
Okay I can understand the reasoning behind this. Would it still be possible to maybe document the above assumption in the docstrings as @vishwakftw suggested?

**Comment by soumith** [comment]
yes, documenting in the docstrings as a Note sounds okay.
