### ISSUE TITLE
How can i convert ‘at::Tensor’ to ‘const float*’ in libtorch?

### ISSUE THREAD

**Issue by Sierkinhane** [pytorch/pytorch#17910]

**Comment by Sierkinhane** [comment]
like ->cpu_data() in caffe
Blob* net_output_blob = net_->blob_by_name("net_output").get();
const float* net_output_data_begin = net_output_blob->cpu_data();

**Comment by Sierkinhane** [comment]
how to serializa a tensor?

**Comment by Sierkinhane** [comment]
how to serialize a tensor?

**Comment by sidazhang** [comment]
Do you mean tensor.data<float>()?

https://pytorch.org/tutorials/advanced/cpp_extension.html

**Comment by SsnL** [comment]
.data<float>()

**Comment by Sierkinhane** [comment]
const float* net_output_begin = output.data<float>()
But when *(net_output_begin) , Segmentation fault (core dumped) happned!(Ubuntu 16.04)
@SsnL @sidazhang

**Comment by Sierkinhane** [comment]
const float* net_output_begin = output.data()
But when *(net_output_begin) , Segmentation fault (core dumped) happend!(Ubuntu 16.04)
@SsnL @sidazhang

**Comment by Sierkinhane** [comment]
float *list = new float(57*8*8);
memcpy(list, net_output_data_begin, 57*8*8 * sizeof(float));

Segmentation fault (core dumped) happend!

**Comment by Sierkinhane** [comment]
float list = new float[57*8*8];
memcpy(list, net_output_data_begin, 57*8*8 * sizeof(float));

Segmentation fault (core dumped) happend!

**Comment by Sierkinhane** [comment]
It seems that I can't get the elements

**Comment by soumith** [comment]
if `output` is a GPU Tensor, then yes it will segfault. You first have to convert `output` to CPU Tensor and then get the data.

**Comment by Sierkinhane** [comment]
thank you. I forgot to receive the return of tenosr.to(device)

**Comment by Sierkinhane** [comment]
thank you. I forgot to receive the return of tensor.to(device)
