### ISSUE TITLE
isTensorList() ASSERT FAILED

### ISSUE THREAD

**Issue by hfengzhi** [pytorch/pytorch#17911]
## To Reproduce

1.After run the forward with c++，i try to turn the tuple to  a TensorList.
1.it report a c10:Errpr
1.

## Expected behavior

  auto oList=module->forward({tensor_img});//return a tuple
    cout<<oList.toTensorList()<<endl;

## Environment

 - PyTorch Version ( 1.0.0 preview):
 - OS (ubuntu 18.04):
 - How you installed PyTorch (TorchLib from web)::
 - Python version: gcc 7.3
 - CUDA/cuDNN version:9.2/7.4.1
 - GPU models and configuration:double  1080Ti

## Additional context

terminate called after throwing an instance of 'c10::Error'
  what():  isTensorList() ASSERT FAILED at /home/super/Work/CLionProjects/lib/libtorch/include/ATen/core/ivalue.h:367, please report a bug to PyTorch. (toTensorList at /home/super/Work/CLionProjects/lib/libtorch/include/ATen/core/ivalue.h:367)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f9995e602b1 in /home/super/Work/CLionProjects/lib/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f9995e5fbea in /home/super/Work/CLionProjects/lib/libtorch/lib/libc10.so)
frame #2: <unknown function> + 0xcfd7 (0x560ed0489fd7 in /home/super/Work/CLionProjects/3d2d/cmake-build-debug/3d2d)
frame #3: <unknown function> + 0xacd9 (0x560ed0487cd9 in /home/super/Work/CLionProjects/3d2d/cmake-build-debug/3d2d)
frame #4: __libc_start_main + 0xe7 (0x7f9994bcfb97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #5: <unknown function> + 0x99da (0x560ed04869da in /home/super/Work/CLionProjects/3d2d/cmake-build-debug/3d2d)

**Comment by ailzhang** [comment]
I doubt we automatically convert a tuple to TensorList object...

**Comment by hfengzhi** [comment]
i hope so,but it's a c10::ivalue::tag::tuple,not a list even not  at::Tensor.

**Comment by suo** [comment]
Thanks for the report! It seems you a trying to cast a tuple to a list of tensors—the `toX` interface on IValue is not for casting, it's for retrieving the tagged C++ type from the ivalue.

`oList.toTuple()->elements()` will give you a vector of tensors. If you want, you can pass the result to the `IValue` constructor to get an IValue containing a TensorList.

**Comment by hfengzhi** [comment]
ok！it works well. thank you .

**Comment by suo** [comment]
Cool, I'm going to close this out then.

**Comment by Yasin40** [comment]
> Thanks for the report! It seems you a trying to cast a tuple to a list of tensors—the `toX` interface on IValue is not for casting, it's for retrieving the tagged C++ type from the ivalue.
> 
> `oList.toTuple()->elements()` will give you a vector of tensors. If you want, you can pass the result to the `IValue` constructor to get an IValue containing a TensorList.

Hi, i have similar problem and similar error but for ```ivalue_inl.h```, which described [here](https://github.com/ultralytics/yolov5/issues/1554#issue-753020980) 

If possible for you, Help me.
