### ISSUE TITLE
In-place operations fail on GPU

### ISSUE THREAD

**Issue by Albert65** [pytorch/pytorch#17933]
## 🐛 Bug

In-place operation cause GPU related memory problem:
**Traceback (most recent call last):
  File "ae5.py", line 389, in <module>
    Main(args)
  File "ae5.py", line 332, in Main
    loss.backward()
  File "/projects/py37torch/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/projects/py37torch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 198.00 MiB (GPU 0; 11.17 GiB total capacity; 9.88 GiB already allocated; 67.12 MiB free; 902.16 MiB cached)
ERROR: ('CUDA out of memory. Tried to allocate 198.00 MiB (GPU 0; 11.17 GiB total capacity; 9.88 GiB already allocated; 67.12 MiB free; 902.16 MiB cached)',)**

## To Reproduce

The error happens after several hundreds iterations. Experimentally the following code
was found responsible (all entities are tensors):

prev.copy_( img )                                      # this variant is ok
prev = img.clamp(0.0, 255.0).clone()      # this is also ok
prev.copy_(img.clamp(0.0, 255.0))          # this variant fails eventually

I can admit that the last line creates a hidden intermediate tensor outside computational graph
causing memory leakage on GPU. But pure in-place version does not work from the beginning (pytorch complains it cannot compute gradient):

prev.copy_(img)
prev.clamp_(0., 255.)

Another piece of code (all entities are tensors):

img = data * weight + prev * (1.0 - weight)         # ok

However, in-place version fails after several hundreds iterations.  

img.copy_(data)
img.sub_(prev)
img.mul_(weight)
img.add_(prev)

## Expected behavior

At first glance, in-place operations neither change the structure of computational
graph, nor they require intermediate buffers.

## Environment

Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Red Hat Enterprise Linux
GCC version: (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: Tesla K40c
Nvidia driver version: 384.111
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

## Additional context

I manually compliled Python 3.7.2 and installed all the packages by Pip.
One can notice that CUDA used to build PyTorch was 9.0.176, by the one
installed system-wide by admin is 8.0.61. Is that might be a problem?

**Comment by soumith** [comment]
The problem is that you run out of memory:

```
RuntimeError: CUDA out of memory. Tried to allocate 198.00 MiB (GPU 0; 11.17 GiB total capacity; 9.88 GiB already allocated; 67.12 MiB free; 902.16 MiB cached)
```

See that there's only 67.12 MiB free and it tried to allocate 198 MiB.
I suggest reducing your batch size or doing something similar.

**Comment by Albert65** [comment]
It runs out of memory with in-place operations, which supposed to save memory. This is strange.

**Comment by soumith** [comment]
it doesn't run out of memory at that particular in-place line.

Because CUDA calls are asynchronous in nature, you get a stack-trace that has the location of the error misplaced.

See this answer for a way to get a better stack-trace: https://discuss.pytorch.org/t/whats-the-meaning-of-this-error-how-can-i-debug-when-i-use-gpu/8052/2?u=smth
