### ISSUE TITLE
Disallow operations if the result tensor has internal memory overlap

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#17935]
See #17185 and #957 for some motivation.

## Motivation
When we do an operation, such as `cos_`, where the output tensor has internal overlap, then the result is usually wrong. For example:

```
import torch
import math
x = torch.tensor(math.pi / 4)
y = x.expand(3)

# Expected output
y.cos()
tensor([0.7071, 0.7071, 0.7071])

# Incorrect output !!
y.cos_()
tensor([0.7247, 0.7247, 0.7247])
```
For `cos_`, the output and input tensors are the same. What ends up happening is that the code will read from the tensor and write to it for each element, resulting in an incorrect computation `(cos(cos(cos(x)))`

## Plan

There are three main cases:
- tensor absolutely does have internal overlap
- tensor absolutely doesn't have internal overlap
- tensor may have internal overlap (we are not sure if it does because it is too expensive to compute this)

_The current plan is to disallow operations if the result tensor absolutely does have internal memory overlap._ If the tensor absolutely doesn't have internal overlap, or if it may have internal overlap, we don't do anything.

This means that right now we do not need to differentiate between the "tensor may have internal overlap" and "tensor absolutely doesn't have internal overlap" cases. In the future we may want to 
 do the following:
- if the "tensor may have internal overlap" we throw a warning or error out
- if the "tensor absolutely does have internal overlap" and/or if the "tensor may have internal overlap", we figure out how to compute the operation correctly.

**Comment by vadimkantorov** [comment]
For elementwise ops (like cos_) for the zero-stride case (with contiguous underlying storage), would applying the operation to the underlying contiguous tensor and re-striding back be semantically correct?

**Comment by zou3519** [comment]
Yes, that should be semantically correct. We have to be a little careful, though -- if we sliced a tensor, then we don't want to apply the operation to the entire underlying tensor, just the sliced part

**Comment by vadimkantorov** [comment]
@zou3519 so e.g. to support an easy case we need to determine if re-strided tensor is a contiguous chunk of memory and determine begin+end storage offsets?

I proposed a similar thing for non in-place ops (e.g. an expanded tensor times a constant should not produce a giant expanded materialized tensor), but @soumith said it was too of a breaking change back then: https://github.com/pytorch/pytorch/issues/4010

Inplace ops on expanded tensors don't have contiguous outputs as expected result, so probably it makes more sense here.

**Comment by zou3519** [comment]
> so e.g. to support this limited case we need to determine if re-strided tensor is a contiguous chunk of memory and determine begin+end storage offsets?

I think it's a little more complicated than that. In the following example,
```
In [1]: import torch
In [2]: x = torch.randn(3, 3)
In [3]: y = x[:, 1].expand(3, 3)
In [6]: y.stride()
Out[6]: (0, 3)
```
the three elements of `x` that we would need to modify if we do `y.cos_()` (for example) are not next to each other in memory, they're 3 elements away from each other

**Comment by zou3519** [comment]
> I proposed a similar thing for non in-place ops (e.g. an expanded tensor times a constant should not produce a giant expanded materialized tensor), but @soumith said it was too of a breaking change back then: #4010

I haven't thought very hard about whether or not it would be semantically correct in this case. Perhaps it would be better to just ignore this case completely and error out. An argument for why applying the operation to parts of the underlying tensor and restriding should happen is that numpy appears to do this

**Comment by vadimkantorov** [comment]
> are not next to each other in memory, they're 3 elements away from each other

In other words, the condition for safe in-place seems to be "if after restriding the tensor's underlying memory is a collection of contiguous chunks of memory" (with possibly some additional zero strides)?


> in general our operators return contiguous tensors and there are many arguments for it.
A compromise could be an operation that returns a view on tensor that is a collection of contiguous chunks of memory, and also gives back an additional stride vector, so that restriding back is easy. E.g:
```python
a = torch.rand(3, 3)
b = a[:, 1]
balmostcontig, bstrideorig = torch.magic_op(b)
c = (balmostcontig * 3).as_strided(bstrideorig) # at maximum, c would have the same amount of raw memory as b, but in case of 0 strides much less
```

**Comment by Baranowski** [comment]
@zou3519 is there a reason why this issue is still open even though a fix has been merged?

**Comment by zou3519** [comment]
Unassigning this because I'm not actively working on this. The issue is open because there still exists operations in PyTorch that don't check for memory overlap.

**Comment by kurtamohler** [comment]
@zou3519 , is the idea to call `at::assert_no_internal_overlap` in every out-variant operation on strided tensors, or only a subset?

If it needs to be all of them, it seems like it would be ideal to have codegen add those calls, right?

**Comment by ngimel** [comment]
Closing, common cases are fixed, general solution can't be done.
