### ISSUE TITLE
Incorrect sparse add when tensor has non-contiguous values

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#17950]
Repro:
```
import torch
indices=torch.tensor([[7, 1, 3]])
values=torch.tensor([[1., 1., 1.],
               [1., 1., 1.],
               [1., 1., 1.]])
x = torch.sparse_coo_tensor(indices, values, size=(10, 3))
values=torch.tensor(1.).expand(3, 3)
y = torch.sparse_coo_tensor(indices, values, size=(10, 3))
z = x + y

tensor(indices=tensor([[7, 1, 3]]),
       values=tensor([[2., 1., 1.],
                      [1., 1., 1.],
                      [1., 1., 1.]]),
       size=(10, 3), nnz=3, layout=torch.sparse_coo)
```

embedding_backward gives a sparse tensor with non-contiguous values so this can lead to problems when using `nn.Embedding`.

**Comment by SsnL** [comment]
Do we really need 3 issues about the same thing? See also #17919 and https://github.com/pytorch/pytorch/issues/17941. I'm closing the other two as this has more debug info. But, please please search before posting an issue next time. Thank you :)

**Comment by SsnL** [comment]
fwiw, I reproduced this on a recent master build

**Comment by zou3519** [comment]
Sorry, I was relying on the github search that pops up when you're typing an issue to identify duplicate issues... I'll do a more thorough search next time
