### ISSUE TITLE
About the C++ frontend API

### ISSUE THREAD

**Issue by ChopinSharp** [pytorch/pytorch#17968]
## 📚 Documentation

The C++ frontend API is not very readable.

First the webpage elements kind of overlap with each other. Like the following example https://pytorch.org/cppdocs/api/classtorch_1_1data_1_1datasets_1_1_dataset.html#exhale-class-classtorch-1-1data-1-1datasets-1-1-dataset.

Second, I can't found the prototype of the class constructor? Maybe because my C++ albility is poor ...

Third, there are NO examples of how to use these APIs AT ALL, which makes the C++ API unusable for C++ newcomers. Maybe this set of API is just developed for C++ expertise? 

Anyway, looking forward for updates.

**Comment by jbschlosser** [comment]
Closing as resolved; see [C++ docs](https://pytorch.org/cppdocs/)
