### ISSUE TITLE
CUDA TEST ERROR

### ISSUE THREAD

**Issue by AnShuai666** [pytorch/pytorch#17976]
It seems like I've got everything right:
build$ sudo make install
[  0%] Built target nccl_external
[  3%] Built target libprotobuf
[  7%] Built target libprotoc
[  7%] Built target protoc
[  8%] Built target libprotobuf-lite
[  8%] Built target clog
[  9%] Built target cpuinfo
[ 11%] Built target qnnpack
[ 12%] Built target cpuinfo_internals
[ 12%] Built target pthreadpool
[ 13%] Built target nnpack
[ 13%] Built target nnpack_reference_layers
[ 14%] Built target gloo
[ 14%] Built target gloo_cuda
[ 14%] Built target gloo_builder
[ 15%] Built target gen_onnx_proto
[ 15%] Built target onnx_proto
[ 17%] Built target onnx
[ 17%] Built target onnxifi_loader
[ 17%] Built target onnxifi_wrapper
[ 18%] Built target onnxifi_dummy
[ 18%] Built target foxi_dummy
[ 18%] Built target foxi_loader
[ 18%] Built target foxi_wrapper
[ 20%] Built target c10
[ 20%] Built target c10_cuda
[ 46%] Built target python_copy_files
[ 46%] Built target Caffe2_PROTO
[ 46%] Built target Caffe2_perfkernels_avx512
[ 46%] Built target caffe2_protos
[ 46%] Built target ATEN_CPU_FILES_GEN_TARGET
[ 46%] Built target __aten_op_header_gen
[ 46%] Built target common
[ 46%] Built target mkrename
[ 46%] Built target renameAVX.h_generated
[ 46%] Built target sleefavx
[ 46%] Built target renamedsp128.h_generated
[ 47%] Built target headers
[ 47%] Built target mkdisp
[ 47%] Built target dispsse.c_generated
[ 47%] Built target dispsse_obj
[ 47%] Built target renamedsp256.h_generated
[ 47%] Built target dispavx.c_generated
[ 47%] Built target dispavx_obj
[ 47%] Built target renameSSE2.h_generated
[ 47%] Built target sleefsse2
[ 47%] Built target renameFMA4.h_generated
[ 47%] Built target sleeffma4
[ 47%] Built target renameAVX2.h_generated
[ 47%] Built target sleefavx2
[ 47%] Built target renameAVX2128.h_generated
[ 47%] Built target sleefavx2128
[ 47%] Built target renameSSE4.h_generated
[ 48%] Built target sleefsse4
[ 49%] Built target sleef
[ 50%] Built target Caffe2_perfkernels_avx2
[ 50%] Built target Caffe2_perfkernels_avx
[ 79%] Built target caffe2
[ 80%] Built target caffe2_pybind11_state
[ 80%] Built target ATEN_CUDA_FILES_GEN_TARGET
[ 98%] Built target caffe2_gpu
[ 98%] Built target caffe2_pybind11_state_gpu
[ 99%] Built target mkrename_gnuabi
[ 99%] Built target mkmasked_gnuabi
[ 99%] Built target mkalias
[ 99%] Built target arraymap
[100%] Built target caffe2_detectron_ops_gpu
[100%] Built target caffe2_observers
Install the project...
-- Install configuration: "Release"

However, when it comes to a test:

1.Test for Caffe2 installation:
cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Success
IT IS SUCCESS!

2.Test for CUDA:
python caffe2/python/operator_test/activation_ops_test.py
NOTHING OUTPUT!

3.Also test for CUDA:
python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
0
IT IS ZERO!
BUT THE LIBRARIES  HAS BEEN BUILT SUCH AS caffe2_gpu! 
I don't know what to do! Anyone help? Thanks a lot!

**Comment by ezyang** [comment]
Please ask for support about this on the forums. https://discuss.pytorch.org/ When you repost there, please also include the output from `nvidia-smi`
