### ISSUE TITLE
problem with the wheel file

### ISSUE THREAD

**Issue by bakhtyarkf** [pytorch/pytorch#17972]
The RECORD in the wheel file, does not contain a record for caffe2 folder and this causes pants (https://github.com/pantsbuild) to fail when I include torch to be added to a project, and this is the error I get:

`Exception caught: (wheel.install.BadWheelFile) (backtrace omitted)
Exception message: No expected hash for file 'caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so'`

**Comment by soumith** [comment]
this is fixed by https://github.com/pytorch/builder/pull/284

The nightly builds already have correct wheels now wrt this issue, and the next stable release will also have fixed builds.
