### ISSUE TITLE
`torch.nn.functional.relu` gives incorrect result

### ISSUE THREAD

**Issue by theFool32** [pytorch/pytorch#17982]
## 🐛 Bug
`torch.nn.functional.relu` gives incorrect result.
It outputs value less than 0 sometimes as seen below.
I'm confused by the result. Hope I don't make mistakes.

## To Reproduce
```
import torch

print(torch.__version__)

a = torch.randint(10, size=(3, 3))
a = a - 5
print(a)
print(torch.nn.functional.relu(a))

b = torch.Tensor([1, -1])
print(b)
print(torch.nn.functional.relu(b))
```
![图片](https://user-images.githubusercontent.com/3063690/54294174-2103b400-45ec-11e9-96b7-af1cdaf777b4.png)

## Expected behavior
Output values greater than 0.

## Environment
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Arch Linux
GCC version: (GCC) 8.2.1 20181127
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.0
[pip3] torch==1.0.0
[pip3] torchvision==0.2.1
[conda] Could not collect

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by soumith** [comment]
this is a bug that affected Integer valued Tensors (i.e. not Floating point Tensors.

For example, if you did `a = a.float()` and then did a ReLU, you wouldn't see the issue.

This is fixed on the latest release of PyTorch, i.e. v1.0.1
