### ISSUE TITLE
randn error with tensorboardX

### ISSUE THREAD

**Issue by JurijsNazarovs** [pytorch/pytorch#17994]
Hello,

I am using pytorch and tensorboardX to create a graph of my network. When I try to create a graph of network, which involves torch.randn(), by .add_graph() I get following error:

```
i_(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Node, arg0: str, arg1: int) -> torch._C.Node

Invoked with: %104 : Tensor = onnx::RandomNormal(), scope: BTCNN
, 'shape', 100 defined in (%100 : int[] = prim::ListConstruct(%87, %91, %95, %99), scope: BTCNN
) (occurred when translating randn)
```

As I understand, message says that problem is with onnx not able to process ```torch.randn```. However, onnx told that they do not have issue with randn, and the issue with pytorch. 

Issue with tensorboardX: https://github.com/lanpa/tensorboardX/issues/359
Issue with onnx: https://github.com/onnx/onnx/issues/1854

**Comment by ailzhang** [comment]
@JurijsNazarovs  Could you provide steps to repro the error? Thanks!

**Comment by lanpa** [comment]
@JurijsNazarovs The following code works on torch 1.1.0.post2

```
import torch

from torch.utils.tensorboard import SummaryWriter

class SimpleModel(torch.nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()

    def forward(self, x):
        return torch.randn(10, 10)

model = SimpleModel()
dummy_input = (torch.zeros(1, 2, 3),)

with SummaryWriter(comment='randModel') as w:
    w.add_graph(model, dummy_input, True)
```

**Comment by zhangguanheng66** [comment]
I will close the issue and feel free to re-open it if you still have the question @JurijsNazarovs . And thanks for the help. @lanpa
