### ISSUE TITLE
libtorch C++ library does not compile properly 

### ISSUE THREAD

**Issue by bobqywei** [pytorch/pytorch#17992]
## 🐛 Bug

After building libtorch from source using build_libtorch.py (latest master as of 1e42720), I am not able to compile my project correctly. Here is my project's CMakeLists.txt:

> cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
> project(model)
> find_package(Torch REQUIRED)
> find_package(OpenCV REQUIRED)
> add_executable(model model.cpp utils.cpp)
> target_link_libraries(model "${TORCH_LIBRARIES}" ${OpenCV_LIBS})
> set_property(TARGET model PROPERTY CXX_STANDARD 11)

I built the project using `cmake -DCMAKE_PREFIX_PATH=~/pytorch/torch/share/cmake/ ..` followed by `make` and everything seems to work fine. However, when I try to run the executable, I get this error:
> error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory

Note that libtorch was working fine on the same machine using the same procedures but on an older iteration of pytorch repo (not sure if that's related, currently trying to reproduce).

## Environment
 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python build_libtorch.py
 - Python version: 3.6
 - CUDA/cuDNN version: CUDA 9.2 / cuDNN 7.5
 - GPU models and configuration: GTX 1060 6GB cuda-396.54 driver
 - Other: cmake 3.10.2

**Comment by ezyang** [comment]
cc @JerryShih since it's libiomp related.

Triage request: could someone attempt to replicate this problem inside of an Ubuntu 18.04 Docker image with a set of repeatable instructions; that would help us greatly in debugging the problem. It shouldn't be necessary to build with CUDA to cause this problem.

@bobqywei Can you run `locate libiomp5.so` and see if this shared object exists on your system at all?

**Comment by bobqywei** [comment]
@ezyang yea it does exist, I get the following when I run it 
`/home/bobw/pytorch/torch/lib/libiomp5.so`
`/home/bobw/pytorch/third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.1.20180928/lib/libiomp5.so`

**Comment by JerryShih** [comment]
I will try to use docker with 18.04 env in Monday.

**Comment by JerryShih** [comment]
@bobqywei 
I can't reproduce this issue.
I just test with this simple libtorch code and your cmake setting.

```
code:
https://pytorch.org/tutorials/advanced/cpp_export.html#a-minimal-c-application
```

```
cmake:
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(model)
find_package(Torch REQUIRED)
add_executable(model model.cpp)
target_link_libraries(model "${TORCH_LIBRARIES}")
set_property(TARGET model PROPERTY CXX_STANDARD 11)
```

And here is the linked lib for that executable file:
```
# ldd model
  ...........
  libtorch.so.1 => /home/jerry.shih/pytorch/torch/lib/libtorch.so.1 (0x00007f5ecdcd2000)
  libcaffe2.so => /home/jerry.shih/pytorch/torch/lib/libcaffe2.so (0x00007f5eca81d000)
  libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5ec9c9e000)
  libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f5ec9537000)
  libmklml_intel.so => /home/jerry.shih/pytorch/torch/lib/libmklml_intel.so (0x00007f5ec05b5000)
  libomp.so.5 => /usr/lib/x86_64-linux-gnu/libomp.so.5 (0x00007f5ec02e9000)
```

Could you show your linked lib list using 'ldd' command? My env doesn't link to libiomp5.so. Maybe that's the difference.

And could you check the path to libiomp5.so is still available when you try to run your executable.

**Comment by bobqywei** [comment]
@JerryShih Thanks for the help! Here's what I get from 'ldd':
`linux-vdso.so.1 (0x00007ffe3915d000)`
`libtorch.so.1 => /home/bobw/pytorch/torch/lib/libtorch.so.1 (0x00007fd28b0de000)`
`libnvrtc.so.9.2 => /usr/local/cuda-9.2/lib64/libnvrtc.so.9.2 (0x00007fd289ad1000)`
`libcaffe2.so => /home/bobw/pytorch/torch/lib/libcaffe2.so (0x00007fd286615000)`
`libcaffe2_gpu.so => /home/bobw/pytorch/torch/lib/libcaffe2_gpu.so (0x00007fd273885000)`
`libc10.so => /home/bobw/pytorch/torch/lib/libc10.so (0x00007fd27364e000)`
`libopencv_imgcodecs.so.4.0 => /usr/local/lib/libopencv_imgcodecs.so.4.0 (0x00007fd272c64000)`
`libopencv_imgproc.so.4.0 => /usr/local/lib/libopencv_imgproc.so.4.0 (0x00007fd271551000)`
`libopencv_core.so.4.0 => /usr/local/lib/libopencv_core.so.4.0 (0x00007fd2702d4000)`
`libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd26ff4b000)`
`libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd26fbad000)`
`libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd26f995000)`
`libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd26f5a4000)`
`libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd26f385000)`
`libnvToolsExt.so.1 => /usr/local/cuda/lib64/libnvToolsExt.so.1 (0x00007fd26f17c000)`
`libcudart.so.9.2 => /usr/local/cuda/lib64/libcudart.so.9.2 (0x00007fd26ef12000)`
`libc10_cuda.so => /home/bobw/pytorch/torch/lib/libc10_cuda.so (0x00007fd26ecf2000)`
`/lib64/ld-linux-x86-64.so.2 (0x00007fd28c4a8000)`
`libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd26eaee000)`
`librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd26e8e6000)`
`libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fd26e6b7000)`
`libmklml_intel.so => /home/bobw/pytorch/torch/lib/libmklml_intel.so (0x00007fd266a54000)`
`libcusparse.so.9.2 => /usr/local/cuda/lib64/libcusparse.so.9.2 (0x00007fd262739000)`
`libcurand.so.9.2 => /usr/local/cuda/lib64/libcurand.so.9.2 (0x00007fd25e7fb000)`
`libcudnn.so.7 => /usr/lib/x86_64-linux-gnu/libcudnn.so.7 (0x00007fd24ba75000)`
`libcufft.so.9.2 => /usr/local/cuda/lib64/libcufft.so.9.2 (0x00007fd24641b000)`
`libcublas.so.9.2 => /usr/local/cuda/lib64/libcublas.so.9.2 (0x00007fd2429cd000)`
`libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fd24279b000)`
`libIlmImf-2_2.so.22 => /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22 (0x00007fd2422d8000)`
`libz.so.1 => /usr/local/lib/libz.so.1 (0x00007fd2420bb000)`
__`libiomp5.so => not found`__
`libHalf.so.12 => /usr/lib/x86_64-linux-gnu/libHalf.so.12 (0x00007fd241e78000)`
`libIex-2_2.so.12 => /usr/lib/x86_64-linux-gnu/libIex-2_2.so.12 (0x00007fd241c5a000)`
`libIlmThread-2_2.so.12 => /usr/lib/x86_64-linux-gnu/libIlmThread-2_2.so.12 (0x00007fd241a53000)`

**Comment by bobqywei** [comment]
It looks like your build isn't linking to the cuda libraries? Also I am linking to opencv libraries as well, so maybe that's the issue?

**Comment by JerryShih** [comment]
@bobqywei
I don't know the difference between libomp and libiomp, but I think it just a env setting problem. Please try to set the ld_library_path to the libiomp folder.
https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/269160

**Comment by bobqywei** [comment]
@JerryShih Thanks! `export LD_LIBRARY_PATH=/home/bobw/pytorch/torch/lib/` (libiomp5.so dir) fixes it for me
