### ISSUE TITLE
[JIT] Allow Serialization to be exportable for debugging

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#18003]
## 🚀 Feature

Make serialization part of the torchscript and compilable. Use case looks like this:
```
class ModelThatNeedsDebugging(jit.ScriptModule)
  def __init__(self)
      ///
  def forward(self, x):
         y =  self.conv(x)
         y.save("./attention_input.pt")
         output = self.attention(y)
         output.save("./attention_feature_map.pt")
         return output
```
This way it allows me to conveniently debug the model inside a production workflow
```
auto module = torch::jit::load("./ModelThatNeedsDebugging.pt");
module->forward(input);
```
## Motivation

A common way of debugging neural networks is to visualize the intermediate feature maps. This is super easy to do in Python. However, if you wanted to debug on the production side. There is no way of doing so.

By allowing serialization to be compilable. It allows us to serialize and debug intermediate tensors.

**Comment by suo** [comment]
We think this is possible using the ivalue serialization format that @driazati is working on.
