### ISSUE TITLE
Using torch.cuda.synchronize causes 6 times slower.

### ISSUE THREAD

**Issue by noahzn** [pytorch/pytorch#18012]
Hello, I want to test the speed of my model, but I find that the speed varies huge depends on whether I use **torch.cuda.synchronize** or not.

```
def test_speed:
    sum_time = list()
    model = MyNetwork(30).cuda()
    bn.eval()
    for i in range(50):
        data = torch.randn(1, 3, 768, 768).cuda()
        torch.cuda.synchronize()
        torch.cuda.synchronize()
        start = time.perf_counter()
        output = model(data)
        # torch.cuda.synchronize()
        end = time.perf_counter()
        print(end - start)
        if i >= 10:
            sum_time.append(end - start)
    print('mean time: ', np.mean(sum_time), 'FPS: ', 1 / np.mean(sum_time))
```
If I run the code without **torch.cuda.synchronize()**, the FPS is about 180, while if I run with **torch.cuda.synchronize()**, FPS is only 30. I also tested other models, but the difference was only 5~10fps. I want to know if the speed difference is caused by my network structure? It's really strange. Thank you.

**Comment by soumith** [comment]
this post gives the answer: https://discuss.pytorch.org/t/doing-qr-decomposition-on-gpu-is-much-slower-than-on-cpu/21213/6
