### ISSUE TITLE
Support Batch Dot Product

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#18027]
## 🚀 Feature
Support batch dot product

## Motivation
Commonly used operation

## Alternatives

Currently, we can do this with bmm. But I think it makes sense to just support batch dot product since it is very commonly used

**Comment by sidazhang** [comment]
@suo  I can implement this if you can point me to where this code should go

**Comment by soumith** [comment]
isn't that just a matrix multiply?

**Comment by SsnL** [comment]
@soumith it's the diagonal of a mm

**Comment by sidazhang** [comment]
Yeah it is just a matrix multiply. But it is annoying to write everytime. It is so commonly used I think we should just have a batch dot method.

```
def bdot(a, b):
    B = a.shape[0]
    S = a.shape[1]
    return torch.bmm(a.view(B, 1, S), b.view(B, S, 1)).reshape(-1)
```

**Comment by zou3519** [comment]
@sidazhang what are the sizes of `a` and `b`? (B, S) and (B, S), and the output is of size (B,) ?

**Comment by SsnL** [comment]
So, afaik, neither bmm nor einsum is efficient for this case. But maybe that has changed from when I heard about this.

**Comment by SsnL** [comment]
@sidazhang what I would suggest is to benchmark for your usecase
1. bmm
2. einsum
3. mul+sum

and just write a helper function using the best one. It's simple enough that I don't know if we should provide in core. Numpy doesn't have a bdot method as well.

**Comment by samuelbroscheit** [comment]
import torch
B = 1024
S = 128
​
x = torch.randn(B, S)
y = torch.randn(B, S)

%%timeit 
​out = torch.einsum('bs,bs->b', x, y)
57.2 µs ± 4.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%%timeit 
out = torch.bmm(x.view(B, 1, S), y.view(B, S, 1)).reshape(-1)
41.8 µs ± 1.41 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%%timeit 
out = (x*y).sum(-1)
30.4 µs ± 440 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


x = torch.randn(B, S).cuda()
y = torch.randn(B, S).cuda()
￼
%%timeit 
out = torch.einsum('bs,bs->b', x, y)
204 µs ± 43.1 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
￼
%%timeit 
out = torch.bmm(x.view(B, 1, S), y.view(B, S, 1)).reshape(-1)
204 µs ± 16.8 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
￼
%%timeit 
out = (x*y).sum(-1)
22.2 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
￼
torch.__version__
'1.0.1.post2'


Maybe -- even if trivial -- a dedicated bdot would be nice, such that users automatically use the most efficient option?

**Comment by zou3519** [comment]
You need to add a synchronise when using timeit with cuda functions. Something like:

```
def fn():
    out = torch.einsum('bs,bs->b', x, y)
    torch.cuda.synchronize()

%timeit fn()
```

**Comment by samuelbroscheit** [comment]
Thanks, I updated the timings.

**Comment by soumith** [comment]
it looks like the `mul + sum` is always cheaper, and sometimes significantly so

**Comment by sidazhang** [comment]
> it looks like the `mul + sum` is always cheaper, and sometimes significantly so

Hence, how do you feel about provding a wrapper for users?

**Comment by fmassa** [comment]
I'm not sure we should be making `torch.dot` support batched tensors.

If we add it, it should preferably follow numpy semantics of `np.dot`.

But `np.dot` is tagged to be deprecated https://github.com/numpy/numpy/issues/5859, and numpy developers [have stated that they regret the current semantics of np.dot](https://github.com/tensorflow/tensorflow/issues/5523)

> matmul's broadcasting is much more general, and in my opinion, also easier to understand. For example, it can do batch matrix-multiplication, but also can still do outer product style broadcasting if you insert dummy dimensions of length 1 (the axes do end up in a different order), e.g.,
batch matmul: [p x q x r] matmul [p x r x t] -> [p x q x t]
outer product matmul: [p x 1 x q x r] matmul [1 x s x r x t] -> [p x s x q x t]
> 
> If we could go back in time as NumPy developers, we assuredly would change dot to work this way (now we cannot, because of backwards compatibility concerns)

So, between having a semantic difference between `torch.dot` and `np.dot`, or copying `np.dot` behavior or not adding batch support for `torch.dot`, I'd go with the last option.

By the way, here was a similar discussion in https://github.com/pytorch/pytorch/issues/138

**Comment by xidulu** [comment]
> it looks like the `mul + sum` is always cheaper, and sometimes significantly so

The `mul + sum` method would use more memory compared with the `bmm` method in my test cases.

`import time

import torch
import torch.nn.functional as F
torch.backends.cudnn.enabled = True


batch_size = 128 * 1000 * 1000
Dimension = 16
use_cuda = True
# perceptron = (torch.nn.Linear(Dimension, 1))
input = torch.randn(batch_size, Dimension)
W = torch.randn(Dimension, Dimension)


start_time = time.time()

if use_cuda:
    # perceptron = perceptron.cuda()
    input = input.cuda()
    W = W.cuda()

load_time = time.time() - start_time
print("Loading time: {} secs".format(load_time))

start_time = time.time()
lhs = torch.matmul(input, W)
rhs = torch.t(input)

# This worked
result = torch.bmm(lhs.view(batch_size, 1, Dimension), input.view(batch_size, Dimension, 1)).reshape(-1)

# GPU got out of memory
# result = (lhs * input).sum(-1)

calc_time = time.time() - start_time
print("Calc time: {}".format(calc_time))

start_time = time.time()
result = result.cpu().data
print(result.shape)
copy_back_time = time.time() - start_time
print("Copy back time: {}".format(copy_back_time))


total_time = calc_time + copy_back_time + load_time
print("Total time: {} secs".format(total_time))
print("Avg throughput:{}".format(128 * 1000 * 1000 /  total_time))
`

**Comment by SsnL** [comment]
Some newer timings using the same setting as @samuelbroscheit, after warming up,

```
In [16]: %%timeit
    ...: out = torch.tensordot(x.T, y, dims=1)
    ...: torch.cuda.synchronize()
    ...:
    ...:
66.7 µs ± 655 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [17]: %%timeit
    ...: torch.einsum('bs,bs->b', x, y)
    ...: torch.cuda.synchronize()
    ...:
    ...:

70.4 µs ± 708 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [18]:

In [18]: %%timeit
    ...: out = torch.bmm(x.view(B, 1, S), y.view(B, S, 1)).reshape(-1)
    ...: torch.cuda.synchronize()
    ...:
    ...:
39.6 µs ± 1.11 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [19]: %%timeit
    ...: out = (x*y).sum(-1)
    ...: torch.cuda.synchronize()
    ...:
    ...:

45.8 µs ± 734 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [20]:

In [21]: %%timeit
    ...: out = torch.tensordot(x, y.T, dims=1)
    ...: torch.cuda.synchronize()
    ...:
    ...:

86.3 µs ± 724 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

```
PyTorch version: 1.4.0.dev20191205
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.4.0.dev20191205
[pip] torchfile==0.1.0
[pip] torchvision==0.5.0a0+7745e73
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-include               2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.4.0.dev20191205 py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch-nightly
[conda] torch                     1.3.0                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.5.0.dev20191205      py37_cu101    pytorch-nightly

```

**Comment by heitorschueroff** [comment]
While working on torch.einsum here #46398 I came across the need for this as well. I added a case in my PR that reduces to torch.dot as it is significantly faster than torch.bmm, but with batched dot this optimization could apply to many more cases.
