### ISSUE TITLE
Excessive call to cudaGetDevice and  cudaSetDevice

### ISSUE THREAD

**Issue by omry** [pytorch/pytorch#18048]
## 🐛 Bug

While profiling my code, I noticed millions of calls to cudaGetDevice which were slowing down my 
code significantly (it's an RL use case and the model I am using is small).
I have a minimal repro that demonstrate that a single forward call on nn.Linear() is triggering 11 cudaGetDevice() calls and 3 cudaSetDevice() calls.

## To Reproduce
See attached code snippet.

/usr/local/cuda/bin/nvprof --profile-from-start off python  cudagetdevice.py
Output:

```
$ /usr/local/cuda/bin/nvprof --profile-from-start off python  cudagetdevice.py 

==112656== NVPROF is profiling process 112656, command: python cudagetdevice.py
==112656== Warning: Profiling results might be incorrect with current version of nvcc compiler used to compile cuda app. Compile with nvcc compiler 9.0 or later version to get correct profiling results. Ignore this warning if code is already compiled with the recommended nvcc version 
==112656== Profiling application: python cudagetdevice.py
==112656== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   73.95%  5.0880us         1  5.0880us  5.0880us  5.0880us  sgemm_32x32x32_NT_vec
                   26.05%  1.7920us         1  1.7920us  1.7920us  1.7920us  _ZN2at4cuda75_GLOBAL__N__51_tmpxft_00005244_00000000_11_Copy_compute_75_cpp1_ii_dd3fb9a321kernelPointwiseApply2IZN75_GLOBAL__N__51_tmpxft_00005244_00000000_11_Copy_compute_75_cpp1_ii_dd3fb9a36CopyOpIffE5applyERNS_6TensorERKS6_EUlRfRKfE_ffjLi1ELi2ELi1EEEvNS0_6detail10TensorInfoIT0_T2_EENSF_IT1_SH_EESH_T_
      API calls:   99.99%  1.03481s         2  517.41ms  12.000us  1.03480s  cudaLaunchKernel
                    0.01%  67.541us        11  6.1400us  4.5000us  13.500us  cudaGetDevice
                    0.00%  14.583us         3  4.8610us  4.5000us  5.5830us  cudaSetDevice
                    0.00%  9.0410us         2  4.5200us  4.5000us  4.5410us  cudaGetLastError
```

## Expected behavior
Number of calls to cudaGetDevice should be minimal, I would argue that it should not be called at most once, if that.

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro P5000
GPU 1: Quadro P5000

Nvidia driver version: 418.39
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] torch==1.0.1.post2
[pip] torchfile==0.1.0
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl_fft                   1.0.6            py36hd81dba3_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.0.1           py3.6_cuda10.0.130_cudnn7.4.2_2    pytorch
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.2                      py_3    pytorch

 - PyTorch Version (e.g., 1.0):
1.0.1
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source):
pip inside a conda env
 - Build command you used (if compiling from source):
 - Python version:
3.6
 - CUDA/cuDNN version:
10.0
 - GPU models and configuration:
Quadro P5000

**Comment by omry** [comment]
Uploading with a .txt extension, thanks github!

[cudagetdevice.py.txt](https://github.com/pytorch/pytorch/files/2968954/cudagetdevice.py.txt)

**Comment by teng-li** [comment]
@ezyang @ngimel 

Any plan on getting this fixed? 11 calls per op is a lot

**Comment by omry** [comment]
for context, this is what it's  doing in my real benchmark:
Note that cudaGetDevice accounts to 25% of the time, and cudaSetDevice is another 7.6%.

```
==41340== Profiling application: python benchmark/compute_trajectories.py
==41340== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   59.29%  227.34ms      1500  151.56us  50.145us  210.18us  sgemm_128x128x8_NT_vec
                   15.23%  58.392ms      1500  38.927us  38.209us  40.193us  void kernelPointwiseApply2<Tensor_tanh_Float_Op, float, float, unsigned int, int=1, int=1>(OffsetInfo<float, unsigned int, int=1>, OffsetInfo<float, unsigned int, int=1>, unsigned int, Tensor_tanh_Float_Op)
                   12.62%  48.394ms      2500  19.357us  2.3040us  31.585us  _ZN2at4cuda75_GLOBAL__N__51_tmpxft_00005244_00000000_11_Copy_compute_75_cpp1_ii_dd3fb9a321kernelPointwiseApply2IZN75_GLOBAL__N__51_tmpxft_00005244_00000000_11_Copy_compute_75_cpp1_ii_dd3fb9a36CopyOpIffE5applyERNS_6TensorERKS6_EUlRfRKfE_ffjLi1ELi2ELi1EEEvNS0_6detail10TensorInfoIT0_T2_EENSF_IT1_SH_EESH_T_
                    9.36%  35.898ms      1000  35.897us  32.480us  41.313us  sgemm_32x32x32_NT_vec
                    1.38%  5.2869ms       800  6.6080us  4.7680us  12.097us  void CatArrayBatchedCopy<float, unsigned int, int=3>(float*, CatArrInputTensor<float, unsigned int>*, OutputTensorSizeStride<unsigned int, unsigned int=4>, int, unsigned int)
                    0.77%  2.9676ms       300  9.8910us  4.6080us  15.969us  _ZN2at6native13reduce_kernelILi512ENS0_8ReduceOpIfZNS0_15sum_kernel_implIffEEvRNS_14TensorIteratorEEUlffE_EEEEvT0_
                    0.45%  1.7183ms       300  5.7270us  2.1760us  8.1600us  _ZN2at6native18elementwise_kernelILi512ELi1EZNS0_17gpu_binary_kernelIZNS0_15mul_kernel_implIfEEvRNS_14TensorIteratorEEUlffE_EEvS5_RKT_EUliE_EEviT1_
                    0.34%  1.3064ms       500  2.6120us  2.4320us  3.1040us  void kernelPointwiseApply2<softPlusupdateOutput_functor<float>, float, float, unsigned int, int=1, int=1>(OffsetInfo<softPlusupdateOutput_functor<float>, float, unsigned int>, OffsetInfo<float, float, int=1>, float, float)
                    0.27%  1.0439ms       200  5.2190us  1.6320us  9.2160us  _ZN2at6native18elementwise_kernelILi512ELi1EZNS0_17gpu_binary_kernelIZNS0_15add_kernel_implIfEEvRNS_14TensorIteratorEN3c106ScalarEEUlffE_EEvS5_RKT_EUliE_EEviT1_
                    0.14%  525.65us       801     656ns     608ns  1.0890us  [CUDA memcpy HtoD]
                    0.09%  335.46us       200  1.6770us  1.5360us  2.3040us  _ZN2at6native18elementwise_kernelILi512ELi1EZNS0_16gpu_unary_kernelIZNS0_17div_constant_implIfEEvRNS_14TensorIteratorET_EUlfE_EEvS5_RKS6_EUliE_EEviT1_
                    0.07%  254.22us       100  2.5420us  2.3360us  2.6880us  void kernelPointwiseApply2<Tensor_sqrt_Float_Op, float, float, unsigned int, int=1, int=1>(OffsetInfo<float, unsigned int, int=1>, OffsetInfo<float, unsigned int, int=1>, unsigned int, Tensor_sqrt_Float_Op)
      API calls:   48.21%  1.14620s      8900  128.79us  6.8330us  1.01876s  cudaLaunchKernel
                   24.70%  587.25ms     64901  9.0480us  4.4580us  688.67us  cudaGetDevice
                   12.59%  299.42ms         1  299.42ms  299.42ms  299.42ms  cudaFree
                    7.60%  180.59ms     19900  9.0740us  4.4580us  400.42us  cudaSetDevice
                    3.78%  89.956ms     10000  8.9950us  4.4580us  599.63us  cudaGetLastError
                    0.95%  22.595ms       799  28.279us  13.458us  400.58us  cudaEventQuery
                    0.76%  17.993ms       800  22.491us  9.9160us  368.88us  cudaMemcpyAsync
                    0.33%  7.7473ms       800  9.6840us  4.4580us  242.83us  cudaEventRecord
                    0.31%  7.4516ms       816  9.1310us  4.4580us  184.58us  cudaEventCreateWithFlags
                    0.30%  7.2414ms        49  147.78us  8.1670us  578.38us  cudaMalloc
                    0.30%  7.1646ms       799  8.9660us  4.4580us  81.000us  cudaEventDestroy
                    0.09%  2.1001ms       186  11.290us  4.4580us  244.29us  cuDeviceGetAttribute
                    0.03%  661.67us         2  330.83us  328.29us  333.38us  cuDeviceTotalMem
                    0.02%  578.13us         1  578.13us  578.13us  578.13us  cudaHostAlloc
                    0.01%  251.96us        11  22.905us  9.0000us  76.458us  cudaDeviceGetAttribute
                    0.00%  86.542us         2  43.271us  30.375us  56.167us  cuDeviceGetName
                    0.00%  22.500us         1  22.500us  22.500us  22.500us  cudaMemcpy
                    0.00%  18.000us         2  9.0000us  4.5000us  13.500us  cuDeviceGetUuid
                    0.00%  9.0000us         2  4.5000us  4.5000us  4.5000us  cuDeviceGet
                    0.00%  4.5000us         1  4.5000us  4.5000us  4.5000us  cuDriverGetVersion
                    0.00%  4.5000us         1  4.5000us  4.5000us  4.5000us  cuInit
                    0.00%  4.5000us         1  4.5000us  4.5000us  4.5000us  cuDeviceGetCount

```

**Comment by ezyang** [comment]
@zou3519 was the last one to investigate this in https://github.com/pytorch/pytorch/issues/13049 and what we discovered was that simply just deleting all of the cudaGetDevice/cudaSetDevice calls didn't actually speed things up much--i.e., the costs from nvprof are hugely distorted and not representative. What *was* expensive is if we were virtual dispatching to the cudaGetDevice/cudaSetDevice call.

If your model is only one GPU device, it would be simple enough for us verify this, simply by rerunning the benchmark numbers with a copy of PyTorch where we deleted all of cudaSetDevice/cudaGetDevice from CUDAGuardImpl. Would you like to try this?

**Comment by ngimel** [comment]
Our experiments also indicate that cudaGet/SetDevice calls do not affect real time too much, however, disabling them requires more than just editing CUDAGuardImpl. E.g., caching allocator (which typically would be called for each output) calls cudaGetDevice https://github.com/pytorch/pytorch/blob/master/c10/cuda/CUDACachingAllocator.cpp#L192, or getCurrentCUDAStream that is called for every kernel launch would call cudaGetDevice from c10's cuda/CUDAFunctions.h, or additional cudaGetDevice's would come from checking that all the tensors are on the same device.

**Comment by omry** [comment]
I wanted to try but fortunately I was not able to build pytorch.
build error: http://paste.ubuntu.com/p/zX3BSmCDWG/
any idea?

**Comment by Alex18947** [comment]
Hi, according to my tests, cudaGet/SetDevice calls are not to blame here - take almost no time for me. I made accessive performance testing of libtorch implementation of some models and found out that I cannot even run some of my model to fully utitlize the GPU (!) because two much CPU time in "lost" is basic objects implementation.

As an example, see [here](https://github.com/ChipsSpectre/chipstorch-yolov3/issues/1)

A.

**Comment by colesbury** [comment]
@omry you don't even need to change PyTorch source code. You can just hot patch the CUDA functions to be no-ops:

https://gist.github.com/colesbury/b10069870419ca1fa9c3a2a8668edbe3

You'll see that outside the profiler the cudaGetDevice and cudaSetDevice functions do not affect performance. You can also use this under nvprof to avoid API tracing those functions.
