### ISSUE TITLE
Question: [rocm]: MIOpen(HIP): Warning [FindRecordUnsafe] File is unreadable: /opt/rocm/miopen/share/miopen/db/gfx803_32.cd.pdb.txt

### ISSUE THREAD

**Issue by aanno** [pytorch/pytorch#18041]
I'm using the ROCM port of pytorch:

```python
>>> torch.cuda.current_device()
0L
>>> torch.cuda.get_device_capability(0)
(3, 0)
>>> torch.cuda.get_device_name(0)
u'Ellesmere [Radeon RX 470/480/570/570X/580/580X]'
>>> torch.cuda.is_available()
True
```
However, when I try to use this port on a ANN, I get the following warning:

```
MIOpen(HIP): Warning [FindRecordUnsafe] File is unreadable: /opt/rocm/miopen/share/miopen/db/gfx803_32.cd.pdb.txt
```

*After this warning, any calculation (ANN training) is stalled.*

There is indeed no such file:

```bash
$ ls /opt/rocm/miopen/share/miopen/db
gfx803_36.cd.pdb.txt  gfx900_56.cd.pdb.txt  gfx906_56.cd.pdb.txt  gfx906_64.cd.pdb.txt
gfx803_64.cd.pdb.txt  gfx900_64.cd.pdb.txt  gfx906_60.cd.pdb.txt
```

**Comment by bddppq** [comment]
@iotamudelta @petrex

**Comment by petrex** [comment]
@aanno A one-time re-tune/re-generate perf database might fix your issue.
To do that add `MIOPEN_FIND_ENFORCE = 3` when you invoke your application (ANN script). It would take a while so stay put.

more info [here](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/perfdatabase.html).

**Comment by bddppq** [comment]
@aanno Doe @petrex's suggested instructions fix your issue?

**Comment by Ukhupacha** [comment]
Hello there, 
I encountered the same problem but instead of gfx803_**16**.cd.pdx.txt I have  gfx803_**8**.cd.pdx.tx
MIOpen(HIP): Warning [FindRecordUnsafe] File is unreadable: /opt/rocm/miopen/share/miopen/db/gfx803_8.cd.pdb.txt

I have a Radeon E9171 MCM  and Fedora 29, using the docker rocm/tensorflow.

Thanks in advance,

**Comment by iotamudelta** [comment]
@Ukhupacha please don't use the `rocm/tensorflow` dockers for PyTorch. Use `rocm/pytorch` ones. Concerning your GPU: I don't think MIOpen tunes for gfx803 with 8 CUs. You should be able to get rid of the warning by creating an empty file in that location.

**Comment by soumith** [comment]
closing via @iotamudelta 's comment
