### ISSUE TITLE
Port SpatialAveragePooling and VolumetricAveragePooling to ATen

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#18066]
See https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide

**Comment by ezyang** [comment]
Happening in #19735

**Comment by rgommers** [comment]
`avg_pool2d` done in gh-21635, `avg_pool3d` being landed in gh-21732

**Comment by skrah** [comment]
#21635 and #21732 are merged.
