### ISSUE TITLE
Port adaptive_avg_pool3d to ATen

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#18065]
adaptive_avg_pool3d is a neural network function that is currently implemented in our legacy THNN (CPU) / THCUNN (CUDA) libraries. It is generally better if these live in our new library ATen, since it is more feature complete and reduces cognitive overhead.

Info about how to port https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide

Note that adaptive_avg_pool2d was ported in #14714

**Comment by crcrpar** [comment]
Can I work on this?

**Comment by ezyang** [comment]
@crcrpar It doesn't look like anyone is working on this yet. Paging @xmnlab and @skrah as heads up; can you two volunteer to review the PR when it comes up?

**Comment by xmnlab** [comment]
sure! :+1:

**Comment by skrah** [comment]
Yes, @crcrpar just add me as a reviewer when it's done.

**Comment by crcrpar** [comment]
Thanks, this will be  my first work on ATen😊
