### ISSUE TITLE
Port adaptive_max_pool1d, adaptive_max_pool2d and adaptive_max_pool3d to ATen

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#18064]
adaptive_max_pool{1,2,3}d are neural network functions that are currently implemented in our legacy THNN (CPU) / THCUNN (CUDA) libraries.  It is generally better if these live in our new library ATen, since it is more feature complete and reduces cognitive overhead. 

Info about how to port https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide

**Comment by skrah** [comment]
This is done in two parts in #19409 and #19547.

I think `adaptive_max_pool1d()` has already been ported,  so there is nothing to do there.

**Comment by skrah** [comment]
Follow up PRs in #19738 and #19748.

**Comment by skrah** [comment]
I think this one is finished.
