### ISSUE TITLE
Torch Inverse C++ - Error in magma_getdevice_arch: MAGMA not initialized

### ISSUE THREAD

**Issue by soulslicer** [pytorch/pytorch#18074]
## 🐛 Bug

I compiled Magma 2.3.0 from source successfully, and compiled Pytorch 1.1 from source successfully where it used Magma. 

When I run my code with the Python API, torch.pinverse(Tensor) seems to work, but when I run it with the C++ Pytorch API torch::inverse(Tensor). it fails with

`Error in magma_getdevice_arch: MAGMA not initialized (call magma_init() first) or bad device`

## To Reproduce

It is stated above

## Environment

```
PyTorch version: 1.1.0a0+444039c
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 390.42
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.2

```

I have tested that Magma's GPU test cases all run, and I checked that Pytorch found Magma correctly. What am I doing wrong? Did I use a wrong version of magma perhaps? If so, it seems to work in Python but not in C++?

If I am using the C++ API, do I need to explicitly call the function here:

https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCTensorMathMagma.cu

@soumith

**Comment by soulslicer** [comment]
Any update on this? Do i need to provide a code example?

**Comment by ezyang** [comment]
It looks like the C++ CUDA API is not calling the magma initialization function (it is done from Python only)

```
macbook-pro-116:pytorch-tmp ezyang$ ag THCMagma_init
torch/csrc/cuda/Module.cpp
382:    THCMagma_init(state);

aten/src/THC/THCTensorMathMagma.cu
21:void THCMagma_init(THCState *state)

aten/src/THC/THCGeneral.h.in
71:THC_API void THCMagma_init(THCState *state);
```

CC @yf225, can you look into this, or delegate it accordingly?

**Comment by soumith** [comment]
is there any manual initialization done via the C++ entry points? I couldn't find any for initializing CUDA context for example.
If we dont, then maybe we can push magma initialization inside lazyInitCUDA

**Comment by soumith** [comment]
I've sent a PR to attempt fix this https://github.com/pytorch/pytorch/pull/18527
