### ISSUE TITLE
A common class in Linear, Conv, LSTM, ... 

### ISSUE THREAD

**Issue by oroojlooy** [pytorch/pytorch#18083]
Hi,

Is there any class that all `torch::nn::Linear, torch::nn::Conv1d, torch::nn::Conv2d, ... torch::nn::GRU, ....` inherit from that? 
I want to create a general `class model`, which has `std::vector<the common class> layers`, so that later I can fill `layers` with any type of layer that I want, e.g., `Linear, Conv2d, etc.` Is there such a capability in the current API? This can be done easily in python, though here we need declaration and this hinders the python's easiness. 

Thanks,
Afshin

**Comment by yf225** [comment]
This question is answered in https://discuss.pytorch.org/t/common-class-of-linear-conv-etc/39987.
