### ISSUE TITLE
[feature request] __getbatch__ for dataset to use with dataloader

### ISSUE THREAD

**Issue by Roulbac** [pytorch/pytorch#18096]
Dataloader call __getitem__ as many times as indices in the current batch. 
In case datasets support a list of indices in one call, or a native python slice object, add a __getbatch__ (optional) to pytorch dataset class. 
If dataloader sees the dataset has such a method implemented, make it fetch the batch corresping to the list of indices with one __getbatch__ call rather than many __getitem__ calls.
This saves the trouble of calling __getitem__ many times in cases where for example a disk file has to be opened then closed for every call and the underlying data structure supports a slicing or lists of indices for example hdf5 files.

**Comment by SsnL** [comment]
#14705 will support something similar

**Comment by gchanan** [comment]
https://github.com/pytorch/pytorch/pull/19228 is the latest version of this.

**Comment by SsnL** [comment]
closed via #19228
