### ISSUE TITLE
parallel_apply fails when input is a dict

### ISSUE THREAD

**Issue by kundan2510** [pytorch/pytorch#1809]
https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/parallel_apply.py#L22

Is this a compulsion to have input to module to be of type variable or nested list of variables? In one of my use cases, I wanted it to have a dict as input.

Please feel free to close the issue if you want to restrict input to module not to include dict.

**Comment by soumith** [comment]
@colesbury what's your take on this? do we want to fix it or treat this as unsupported (in which case we should add a proper assertion)

**Comment by colesbury** [comment]
`parallel_apply` takes in a list of modules and a list of inputs and returns a list of outputs.  We should allow arbitrary inputs; we shouldn't require that they're Variables.

This means getting rid of `get_a_var()`. We can either take in a list of `devices` or try to determine it from the module.

**Comment by colesbury** [comment]
Also see #1992

**Comment by weiyangfb** [comment]
closing because this is fixed by https://github.com/pytorch/pytorch/pull/1880
