### ISSUE TITLE
Is mkl-dnn enabled in the latest binary distribution v1.0.1?

### ISSUE THREAD

**Issue by paulcx** [pytorch/pytorch#18108]
For example, does the latest install wheel 'https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp35-cp35m-linux_x86_64.whl' have mkl-dnn integration?

If so, how to verify the mkl-dnn installation without benchmark?

**Comment by ailzhang** [comment]
cc: @soumith

**Comment by ezyang** [comment]
Yes.

**Comment by ezyang** [comment]
We should add a flag like torch/backends/mkldnn that lets you check this. Should be easy. I can review a patch if you submit.

**Comment by vadimkantorov** [comment]
(related https://github.com/pytorch/pytorch/issues/111 )

**Comment by ezyang** [comment]
Actually, I need this fixed for something I'm working on, will submit PR.
