### ISSUE TITLE
fixed the seed but results are not deterministic

### ISSUE THREAD

**Issue by isalirezag** [pytorch/pytorch#18119]
## 🐛 Bug

 - PyTorch Version (e.g., 1.0): 1.0.1.post2
 - OS (e.g., Linux): 16.04 Ubintu
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
 - Python version: 3.6
 - CUDA/cuDNN version: 9.0/7
 - GPU models and configuration:titan 1080

As we can see despite fixing all the seeds still the results are random...
```

import  torch
import random
import numpy as np

# Set random seem for reproducibility
manualSeed = 9999
print("Random Seed: ", manualSeed)
np.random.seed(manualSeed)
random.seed(manualSeed)
torch.manual_seed(manualSeed)
torch.cuda.manual_seed_all(manualSeed)
torch.cuda.manual_seed(manualSeed)

torch_seed = torch.initial_seed()
print("torch_seed: {}" .format(torch_seed))
print(torch.rand(5))
print(torch.rand(5))
print(torch.rand(5))


Random Seed:  9999
torch_seed: 9999
tensor([0.7876, 0.4498, 0.9623, 0.6187, 0.0540])
tensor([0.6541, 0.7571, 0.7051, 0.5406, 0.3187])
tensor([0.8626, 0.0870, 0.1210, 0.2893, 0.0214])
```

**Comment by SsnL** [comment]
setting a seed doesn't mean all subsequent random ops give same results. It means that the sequence of random numbers is fixed (wrt to the seed).
