### ISSUE TITLE
Variable-length mini-batches in bidirectional RNNs

### ISSUE THREAD

**Issue by root20** [pytorch/pytorch#1811]
As per my understanding, PackedSequence enabled use of variable-length mini-batches without worrying about gradients flowing through the zero-padded frames.
I am curious about if it is also valid in bidirectional RNNs. (bi-RNN)
If it performs reversal of the sequences, I think it should exclude zero-paddings.
If we include zero-paddings during reversal, in the output of the bi-RNN, zero-paddings will be concatenated to the non-paddings in some short sequences in a mini-batch.
This behaviour is different with the case when we use bi-RNNs with mini-batch of size 1.

Example of wrong case (where ● is non-paddng frame; ○ is zero-padding)>
(before reversal)
●●●●○○○○
●●●●●●○○
●●●●●●●○
(after reversal)
○○○○●●●●
○○●●●●●●
○●●●●●●●

Example of correct case> 
(before reversal)
●●●●○○○○
●●●●●●○○
●●●●●●●○
(after reversal)
●●●●○○○○
●●●●●●○○
●●●●●●●○

I don't really know how the bi-RNNs are implemented, but I could not see the part that takes lengths informations to handle this problem.

Thank you.

**Comment by jekbradbury** [comment]
Yes, it's valid for bidirectional RNNs (it follow the "correct case"). Future questions like this are best directed to http://discuss.pytorch.org, btw.

**Comment by root20** [comment]
Thank you!
