### ISSUE TITLE
cuda issue 3d int16 array (from SimpltITK) to torch.FloatTensor

### ISSUE THREAD

**Issue by najeebullahshah** [pytorch/pytorch#18112]
## ❓ Questions and Help
I am trying to run a tensor with cuda on torch like this:

ct_array1 = sitk.GetArrayFromImage(ct1)
ct_array1 = torch.FloatTensor(ct_array1, device='cuda:0').unsqueeze(0)
print(ct_array1.device)

Here ct_array1 is a 3d int16 array 

Error Trace:
RuntimeError: legacy constructor for device type: cpu was passed device type: cuda, but device type must be: cpu

**Comment by ailzhang** [comment]
`torch.FloatTensor` is legacy **cpu** tensor constructor. Please use `torch.tensor(..., device='cuda:0', dtype=torch.float)`. Or if you prefer to use the legacy constructor, try `torch.cuda.FloatTensor(ct_array1)`.

**Comment by najeebullahshah** [comment]
Thanks @ailzhang for the response. Now i am getting this error:

ct_array = torch.tensor(ct_array, device='cuda:0', dtype=torch.float)
RuntimeError: CUDA error: initialization error

**Comment by ezyang** [comment]
Please use https://discuss.pytorch.org/ to debug cuda installation problems.
