### ISSUE TITLE
Training Benchmark

### ISSUE THREAD

**Issue by ameet20** [pytorch/pytorch#18124]
Hello,

 I am just wondering if there is any benchmark on distributed data parallel training:

For example,

What's the speedup with 8 GPUs on 2 machines compared to 1 GPUs on 1 machine?

What's the speedup with 8 GPUs on 2 machines compared to 4 GPUs on 1 machine?

For single machine data parallel, I am also interested about the speedup, for example:

What's the speedup with 4 GPUs on 1 machines compared to 1 GPUs on 1 machine?

**Comment by Protocal13** [comment]
I don't think theres a dufference
im gussing nomatter how many gpus are used within two computers they don't make any difference

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
