### ISSUE TITLE
Descriptive error message for distribution constraint violation

### ISSUE THREAD

**Issue by jhostetler** [pytorch/pytorch#18133]
## 🚀 Feature

The current error message raised by constraint violations in distribution constructors (when `validate_args=True`) is a generic message that doesn't say what the problem is, e.g.:
```
<...>/torch/distributions/distribution.py", line 36, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter probs has invalid values
```

## Motivation

When I see this error, I have to identify the source of the problematic parameter, add logging code, run the program again (which might take a long time), and hope that it fails again in the same place (which it might not due to stochasticity).

## Pitch

The particular error I encountered was for the `Categorical` distribution, where I had a long probability vector (4096 entries) that caused the sum of the normalized probabilities to fall outside the error tolerance in the constraint check. The desired message would be something like:
```
ValueError: The parameter probs has invalid values: |sum(probs) - 1| > 1e-6
```
which describes what the problem actually is. Note that in this case it was the `_Simplex` constraint that failed, but it can fail for two different reasons (negative entries, or normalized sum not close enough to 1).

On a related note, perhaps the error tolerance could account for the number of entries in `probs` to avoid raising a spurious error.

**Comment by apaszke** [comment]
Yes, that's a great request! cc @fritzo @neerajprad @vishwakftw

**Comment by neerajprad** [comment]
Since this happens within the `Distribution` class, I think the easiest way to achieve this would be to use the `__repr__` method for each of the constraints (we will need to add this method for certain constraints that don't have it) and say that it failed. That might still not offer details on which particular check failed (e.g. in the Simplex case above where we have two checks), but I think most constraint checks are fairly simple and even just saying that `|sum(probs) - 1| > 1e-6 or not all(probs >= 0)` should be good enough hint for new users. 

> On a related note, perhaps the error tolerance could account for the number of entries in probs to avoid raising a spurious error.

I think another thing that we could do (which is what scipy does too) is to relax the error threshold but normalize by allocating the remaining mass to the last category. 

```python
p[..., -1] = 1. - p[..., :-1].sum(-1)
```

Then we can just check that none of the entries are negative.

**Comment by fritzo** [comment]
I agree with @neerajprad 's suggestions, but I am wary about the asymetry in
> normaliz[ing] by allocating the remaining mass to the last category.

I like @jhostetler 's idea of an error threshold that depends on number of entries in `probs`. @jhostetler what are your typical number of categories? Did you see this error with e.g. 1e6 categories?

**Comment by jhostetler** [comment]
@fritzo I saw the error with a 4096-element probability vector with roughly uniform probabilities -- all the entries were around 0.0002 or 0.0003. This is using float32 data type. The normalization error was 1.076e-6.

@neerajprad 's suggestion could have a problem if the final element is very small, since subtracting the extra mass could make it negative. You might have to iterate over several elements (potentially all but one?) until you got rid of all of the extra mass. Anyway, the effect is the same as if you just ignore the extra mass, since presumably the multinomial sampling is drawing from `[0,1]` and then comparing to the cumulative sum of probabilities. So if the sum is `> 1`, the last entry/entries will just have a (slightly) smaller chance of being sampled than they would with infinite precision. 

Arguably, exceeding the normalization error tolerance should only trigger a warning, since it just reflects a limitation of finite precision arithmetic, not an error by the caller. Unlike e.g. passing negative / inf / NaN.

**Comment by neerajprad** [comment]
> Arguably, exceeding the normalization error tolerance should only trigger a warning, since it just reflects a limitation of finite precision arithmetic, not an error by the caller. Unlike e.g. passing negative / inf / NaN.

I just checked the multinomial implementation and it does the normalization of the cumulative distribution to ensure that the last value sums to 1. So we can certainly relax the threshold. Note that you can disable the args checking by passing `validate_args=False` for the distribution instance. Raising an error is helpful during model debugging when figuring out where NaNs are coming from etc., but can safely be turned off for a mature model. Also, you could consider using logits directly which shouldn't have this issue.

**Comment by 18445864529** [comment]
So what exactly does this error mean? I also got the same `The parameter scale has invalid values` error with a normal distribution `Normal(loc=m, scale=s)`  my invalid parameter 'scale' looks like something like this: 
tensor([[[9.9296e-01, 9.8803e-01, 9.9348e-01,  ..., 9.9645e-01,
          9.9091e-01, 9.9436e-01],
         [9.9371e-01, 9.6459e-01, 9.9174e-01,  ..., 1.0060e+00,
          9.9427e-01, 1.0133e+00],
         [9.3797e-01, 9.2840e-01, 9.8308e-01,  ..., 1.0676e+00,
          1.0070e+00, 1.0721e+00],
         ...,
And now I cannot figure out what really happened, how its values are invalid, and how I can solve it.

**Comment by fritzo** [comment]
@18445864529 what this means is that `Normal.arg_constraints["scale"].check(s)` is not an entirely true tensor.  You can find the particular bad elements via
```py
ok = Normal.arg_constraints["scale"].check(s)
bad_elements = s[~ok]
print(bad_elements)
```
In your case I would guess there is either a non-positive, infinite, or NAN value somewhere.

**Comment by mablue** [comment]
++ I have this problem I using some unscaled data from... 
from backtesting.test import GOOG
package and In error it sAY To me:


```
 File "/home/mab/mastrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3241, in _set_item
    self._ensure_valid_index(value)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3294, in _ensure_valid_index
    raise ValueError(
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series
(.env) mab@mab-X550VX:~/mastrade$ /home/mab/mastrade/.env/bin/python /home/mab/mastrade/main.py
Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
    0   1   2   3
0 NaN NaN NaN NaN
1 NaN NaN NaN NaN
2 NaN NaN NaN NaN
3 NaN NaN NaN NaN
4 NaN NaN NaN NaN
Traceback (most recent call last):
  File "/home/mab/mastrade/main.py", line 148, in <module>
    model.learn(total_timesteps=100000)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py", line 280, in learn
    return super(PPO, self).learn(
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 227, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 168, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 163, in step
    return self.step_wait()
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 43, in step_wait
    obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 97, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/mab/mastrade/main.py", line 69, in step
    self.monkey_high = self.ropes.iat[self.time, self.monkey_pos]
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 2103, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3126, in _get_value
    series = self._ixs(col, axis=1)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 2962, in _ixs
    label = self.columns[i]
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4297, in __getitem__
    return getitem(key)
IndexError: index 4 is out of bounds for axis 0 with size 4
(.env) mab@mab-X550VX:~/mastrade$ /home/mab/mastrade/.env/bin/python /home/mab/mastrade/main.py
Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
    0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 100      |
|    ep_rew_mean     | nan      |
| time/              |          |
|    fps             | 900      |
|    iterations      | 1        |
|    time_elapsed    | 2        |
|    total_timesteps | 2048     |
---------------------------------
Traceback (most recent call last):
  File "/home/mab/mastrade/main.py", line 148, in <module>
    model.learn(total_timesteps=100000)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py", line 280, in learn
    return super(PPO, self).learn(
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 247, in learn
    self.train()
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py", line 191, in train
    values, log_prob, entropy = self.policy.evaluate_actions(rollout_data.observations, actions)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/common/policies.py", line 610, in evaluate_actions
    distribution = self._get_action_dist_from_latent(latent_pi, latent_sde)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/common/policies.py", line 575, in _get_action_dist_from_latent
    return self.action_dist.proba_distribution(action_logits=mean_actions)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/stable_baselines3/common/distributions.py", line 275, in proba_distribution
    self.distribution = Categorical(logits=action_logits)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/mab/mastrade/.env/lib/python3.8/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter logits has invalid values
(.env) mab@mab-X550VX:~/mastrade$ 
```

**Comment by bjwie** [comment]
Hey mablue,

got the same problem with your repo.
Its because your reward is giving back nan.

Problem start with: 
        self.monkey_high = self.ropes.iat[self.time, self.monkey_pos]

Best regards
Björn

**Comment by Jimmy2027** [comment]
Hi, I also got this error `The parameter probs has invalid values` but have no idea how to debug it. This happens with a OneHotCategorical distribution. When I give the argument `validate_args=False` it gets ignored since it is not passed to the Categorical distribution (in `OneHotCategorical.__init__`), which throws the error:

```
mod.likelihood(x, validate_args=False)
File "python3.9/site-packages/torch/distributions/one_hot_categorical.py", line 41, in __init__
self._categorical = Categorical(probs, logits)
File "python3.9/site-packages/torch/distributions/categorical.py", line 64, in __init__
super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
File "python3.9/site-packages/torch/distributions/distribution.py", line 53, in __init__
raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter probs has invalid values
```

Running 
```
print(x.shape)
ok = mod.likelihood.arg_constraints["probs"].check(x)
bad_elements = x[~ok]
print(bad_elements)
```

gives me 
```
torch.Size([150, 128, 2900])
tensor([[-1.1617e+02, -3.8558e+03, -8.0643e+02,  ..., -7.6817e+00,
         -7.7012e+00, -7.5984e+00],
        [-1.7096e+02, -8.1502e+03, -1.2028e+03,  ..., -7.5718e+00,
         -7.5520e+00, -7.5193e+00],
        [-1.9102e+02, -6.8188e+03, -1.3725e+03,  ..., -7.7245e+00,
         -7.6917e+00, -7.6112e+00],
        ...,
        [-1.2556e+02, -2.0951e+04, -4.5350e+02,  ..., -8.1246e+00,
         -7.7035e+00, -7.9259e+00],
        [-1.2135e+02, -2.0516e+04, -3.9489e+02,  ..., -7.8555e+00,
         -7.6532e+00, -7.9331e+00],
        [-5.4689e+01, -7.4346e+03, -2.4636e+02,  ..., -7.6985e+00,
         -7.7323e+00, -7.7199e+00]], device='cuda:0', grad_fn=<IndexBackward>)
```

How can I find out what is wrong with my input?

**Comment by mablue** [comment]
> Hey mablue,
> 
> got the same problem with your repo.
> Its because your reward is giving back nan.
> 
> Problem start with:
> self.monkey_high = self.ropes.iat[self.time, self.monkey_pos]
> 
> Best regards
> Björn

thanks than how can i fix it?

**Comment by bjwie** [comment]
@mablue 
puuh, long time ago I dont remember, but here is the code.

`import time
from numpy.testing import verbose
from pandas.core.frame import DataFrame
import yfinance as yf
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3 import A2C
import gym
from gym import spaces
from gym.utils import seeding
from gym.envs.classic_control import rendering
import talib as ta
from stable_baselines3.a2c.policies import MlpPolicy

MONKEY_HIGH = 1
NUMBER_OF_ROPES = 4
DoGym = True


class monkeyEnv(gym.Env):
    metadata = {'render.modes': ['human']}

    def __init__(self, monkey_high, n, stock):

        self.monkey_high = monkey_high
        self.viewer = None
        self.n = n
        self.stock = stock

        # actions
        self.action_space = spaces.Discrete(self.n)
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(1,),
            dtype=np.float32)

    def seed(self, seed=None):
        self.np_random, seed = seeding.np_random(seed)
        return [seed]

    def reset(self):
        self.monkey_last_pos = 0
        self.monkey_pos = 0
        self.rope_high = 1
        self.last_rope_high = 1
        self.monkey_last_high = MONKEY_HIGH
        self.monkey_high = MONKEY_HIGH
        self.last_time = 0
        self.time = 0

        self.ropes = pd.DataFrame(
            self.stock,
            columns=list(range(1, NUMBER_OF_ROPES))
        )
        # let assume that is an stable coin like usdt that have 50$ price
        self.ropes.insert(loc=0, column=0, value=[50]*98)

        # for idx, rope in enumerate(self.ropes):
        #     self.ropes[idx] = ta.SMA(rope, 14)
        if self.viewer != None:
            self.viewer.close()
            self.viewer = None
        # print(self.ropes.head())

        return np.array([self.monkey_pos]).astype(np.float32)

    def step(self, action):

        self.monkey_last_pos = self.monkey_pos
        self.monkey_pos = action

        # if self.monkey_last_pos != self.monkey_pos:
        self.monkey_last_high = self.monkey_high
        self.monkey_high = self.ropes.iat[self.time, self.monkey_pos]

        self.time += 1
        done = True if self.time == 98 else False
        reward = 0.01*(self.monkey_high - self.monkey_last_high)

        info = {
            "monkey_last_pos": self.monkey_last_pos,
            "monkey_pos": self.monkey_pos,

            "rope_high": self.rope_high,
            "last_rope_high": self.last_rope_high,

            "monkey_last_high": self.monkey_last_high,
            "monkey_high": self.monkey_high,

            "last_time": self.last_time,
            "time": self.time,

        }

        return np.array([self.monkey_pos]).astype(np.float32), reward, done, info

    def render(self, mode='human'):

        x = self.time - 1
        y = self.monkey_high
        if self.viewer is None:

            self.viewer = rendering.Viewer(2000, 500)

            for i in range(self.n):
                xs = pd.Series(range(100))
                ys = self.ropes.iloc[:, i]
                xys = list(zip(xs*20, ys*5))
                self.track = rendering.make_polyline(xys)
                self.track.set_linewidth(2)
                self.track.set_color(*np.random.rand(3))
                self.viewer.add_geom(self.track)

            self.monkey = rendering.make_circle(radius=5)

            self.monkey.set_color(0, 0, 0)
            self.monkeyT = rendering.Transform(translation=(x*20, y*5))
            self.monkey.add_attr(self.monkeyT)
            self.viewer.add_geom(self.monkey)
        else:
            self.monkeyT.set_translation(x*20, y*5)

        return self.viewer.render(return_rgb_array=mode == 'rgb_array')

    def close(self):
        pass

# --------------------------------------------------------------


symbols = ['BTC-USD', 'ETH-USD', 'BNB-USD', 'XRP-USD']
df = pd.DataFrame([1]*98)

for i in range(len(symbols)):
    symbol = symbols[i]
    s = yf.download(tickers=symbol, period='30h',
                    interval='15m')
    print(s['Close'])
    close = s['Close'].values
    df[i] = close[:98]
    # df.insert(loc=i+1, column=i+1, value=s.Close)

scaler = MinMaxScaler()

x = df.values  # returns a numpy array
x_scaled = scaler.fit_transform(x)
df = pd.DataFrame(x_scaled)

# for example we have 50$ in start
env = monkeyEnv(monkey_high=MONKEY_HIGH, n=NUMBER_OF_ROPES, stock=df)
model = None
if DoGym:
    model = A2C(MlpPolicy, env,verbose=1, device="cuda")
    model.learn(total_timesteps=10000, log_interval=500)
    model.save("ppo_monkey")

#del model  # remove to demonstrate saving and loading

model = A2C.load("ppo_monkey")

obs = env.reset()
import itertools

for _ in itertools.repeat(None, 1000):
    time.sleep(0.1)
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
    print(info['monkey_high'], info['monkey_pos'], rewards)
    if info['time'] >= 98:
        env.reset()
`

**Comment by fritzo** [comment]
@Jimmy2027 nice snippet to isolate the invalid values!  It looks like some of your probs values are negative, which violates `constraints.positive`.

@neerajprad How about we use @Jimmy2027's snippet to print invalid values in the error message #61056?

**Comment by eromoe** [comment]
I meet this error , but there is no input value , how do I debug it ? Below is a piece of code in my note , copied from last year when I learning pyro ,  now I want to review pyro but it can't execute  
```
from torch.optim import Adam

pyro.clear_param_store()
def model():
    mu = param('mu', tensor(0.))
    sig = param('sig', tensor(1.0))
    norm = dist.Normal(mu, sig)
    return sample('x', norm)

model() # Instantiate the mu parameter
cond_model = condition(model, {"x": tensor(5) })

# Large learning rate for demonstration purposes
optimizer = Adam([param("mu"), param('sig')], lr=0.01)
mus = []
sigs = []
losses = []
for _ in range(2000):
    tr = trace(cond_model).get_trace()

    # Optimizer wants to push positive values towards zero,
    # so use negative log probability
    prob = -tr.log_prob_sum()
    prob.backward()

    # Update parameters according to optimization strategy
    optimizer.step()

    # Zero all parameter gradients so they don't accumulate
    optimizer.zero_grad()

    # Record probability (or "loss") along with current mu
    losses.append(prob.item())
    mus.append(param("mu").item())
    sigs.append(param("sig").item())

pd.DataFrame({"mu": mus, "loss": losses}).plot(subplots=True)
pd.DataFrame({"sig": sigs, "loss": losses}).plot(subplots=True)
```

got similar error :
```
ValueError                                Traceback (most recent call last)
~\anaconda3\lib\site-packages\pyro\poutine\trace_messenger.py in __call__(self, *args, **kwargs)
    173             try:
--> 174                 ret = self.fn(*args, **kwargs)
    175             except (ValueError, RuntimeError) as e:

~\anaconda3\lib\site-packages\pyro\poutine\messenger.py in _context_wrap(context, fn, *args, **kwargs)
     11     with context:
---> 12         return fn(*args, **kwargs)
     13 

<ipython-input-20-230312cfa16e> in model()
      6     sig = param('sig', tensor(1.0))
----> 7     norm = dist.Normal(mu, sig)
      8     return sample('x', norm)

~\anaconda3\lib\site-packages\pyro\distributions\distribution.py in __call__(cls, *args, **kwargs)
     17                 return result
---> 18         return super().__call__(*args, **kwargs)
     19 

~\anaconda3\lib\site-packages\torch\distributions\normal.py in __init__(self, loc, scale, validate_args)
     49             batch_shape = self.loc.size()
---> 50         super(Normal, self).__init__(batch_shape, validate_args=validate_args)
     51 

~\anaconda3\lib\site-packages\torch\distributions\distribution.py in __init__(self, batch_shape, event_shape, validate_args)
     54                 if not valid.all():
---> 55                     raise ValueError(
     56                         f"Expected parameter {param} "

ValueError: Expected parameter scale (Tensor of shape ()) of distribution Normal(loc: 5.000012397766113, scale: -0.0036314278841018677) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
-0.0036314278841018677

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-20-230312cfa16e> in <module>
     17 losses = []
     18 for _ in range(2000):
---> 19     tr = trace(cond_model).get_trace()
     20 
     21     # Optimizer wants to push positive values towards zero,

~\anaconda3\lib\site-packages\pyro\poutine\trace_messenger.py in get_trace(self, *args, **kwargs)
    196         Calls this poutine and returns its trace instead of the function's return value.
    197         """
--> 198         self(*args, **kwargs)
    199         return self.msngr.get_trace()

~\anaconda3\lib\site-packages\pyro\poutine\trace_messenger.py in __call__(self, *args, **kwargs)
    178                 exc = exc_type(u"{}\n{}".format(exc_value, shapes))
    179                 exc = exc.with_traceback(traceback)
--> 180                 raise exc from e
    181             self.msngr.trace.add_node(
    182                 "_RETURN", name="_RETURN", type="return", value=ret

~\anaconda3\lib\site-packages\pyro\poutine\trace_messenger.py in __call__(self, *args, **kwargs)
    172             )
    173             try:
--> 174                 ret = self.fn(*args, **kwargs)
    175             except (ValueError, RuntimeError) as e:
    176                 exc_type, exc_value, traceback = sys.exc_info()

~\anaconda3\lib\site-packages\pyro\poutine\messenger.py in _context_wrap(context, fn, *args, **kwargs)
     10 def _context_wrap(context, fn, *args, **kwargs):
     11     with context:
---> 12         return fn(*args, **kwargs)
     13 
     14 

<ipython-input-20-230312cfa16e> in model()
      5     mu = param('mu', tensor(0.))
      6     sig = param('sig', tensor(1.0))
----> 7     norm = dist.Normal(mu, sig)
      8     return sample('x', norm)
      9 

~\anaconda3\lib\site-packages\pyro\distributions\distribution.py in __call__(cls, *args, **kwargs)
     16             if result is not None:
     17                 return result
---> 18         return super().__call__(*args, **kwargs)
     19 
     20     @property

~\anaconda3\lib\site-packages\torch\distributions\normal.py in __init__(self, loc, scale, validate_args)
     48         else:
     49             batch_shape = self.loc.size()
---> 50         super(Normal, self).__init__(batch_shape, validate_args=validate_args)
     51 
     52     def expand(self, batch_shape, _instance=None):

~\anaconda3\lib\site-packages\torch\distributions\distribution.py in __init__(self, batch_shape, event_shape, validate_args)
     53                 valid = constraint.check(value)
     54                 if not valid.all():
---> 55                     raise ValueError(
     56                         f"Expected parameter {param} "
     57                         f"({type(value).__name__} of shape {tuple(value.shape)}) "

ValueError: Expected parameter scale (Tensor of shape ()) of distribution Normal(loc: 5.000012397766113, scale: -0.0036314278841018677) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
-0.0036314278841018677
Trace Shapes:
 Param Sites:
           mu
          sig
Sample Sites:

```

**Comment by neerajprad** [comment]
Your error message shows that that the scale parameter to the normal distribution is negative (it should be positive)

> ValueError: Expected parameter scale (Tensor of shape ()) of distribution Normal(loc: 5.000012397766113, scale: -0.0036314278841018677) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
-0.0036314278841018677

**Comment by wildphoton** [comment]
@neerajprad Hi, I also meet this error message `ValueError: The parameter probs has invalid values                                                                                                                                                            
` even with logits as the input to `OneHotCatergorical`.  Is it a bug? According to the implementation of `Distribution` class, the constrain checking is supposed to ignore the lazy properties e.g. ignore `probs` when initialize with `logits` as `Catergorical` does. https://github.com/pytorch/pytorch/blob/8559d39cf032a9118c470ebe3a5047f89d94fe5c/torch/distributions/distribution.py#L50
I think `OneHotCatergorical` failed to skip the checking for `probs` since neither `probs` or `logits` is in `self.__dict__`. `Catergorical` is implemented in a way without this issue.
