### ISSUE TITLE
inplace function tests in test_autograd don't test inplace in the presence of other default args

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#1814]
The code adds a "True" to the end of the arguments, but this doesn't work if there are other default arguments (https://github.com/pytorch/pytorch/blob/909f31764faf65c80f4d8eaeae8a12c67eb24c17/test/test_autograd.py#L1697-L1698).

For example, TestAutograd.test_AddcmulFunction passes "True" for "scale" (and somehow this passes?).

The "method" tests do the right thing for the inplace tests, however.  Apply doesn't currently take kwargs, so to fix this, we'd have to change that to fix this I think.

I'm sort of confused on why we want both function and method tests in test_autograd, though.  They test similar things (as shown, they both test inplace), although currently only the function tests call gradcheck.  Since users only really interact with the methods (which in turn call the functions anyway), wouldn't it be simpler to just make everything a method test?  I'm probably missing something obvious, here.

**Comment by apaszke** [comment]
1. Yes that's a problem. We can't allow arbitrary kwarg arguments (we need an ordering on input Variables, which dicts don't give us), however we can accept them as long as they're not Variables.
2. They serve different purposes. First are tests for Function classes that make sure they're implemented correctly (including grad formulas). Method tests ensure that Variable methods behave exactly like tensor methods (e.g. give the same results, and really modify the input in case of in-place).

**Comment by gchanan** [comment]
On 2), is there a case where we couldn't do the function checks using the method tests?  (My issue is really the need to specify the same "tests" twice, in two different ways).  What I mean is, the methods (at least the ones I've looked at), end up calling a function at the end anyway, and we can get at the resulting output/grad the same way, right?
