### ISSUE TITLE
[JIT] We don't document that nn.Sequential needs to be in __constants__

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#18147]
if it's used as a submodule of a ScriptModule

**Comment by driazati** [comment]
#17167 was supposed to make this more apparent to users, is there some repro that doesn't go down this path?

**Comment by jamesr66a** [comment]
I mean in the docs. We talk about `ModuleList` but not `Sequential`

**Comment by Krovatkin** [comment]
Let's assign this one to @zdevito for now since he seems to be our heaviest editor.

**Comment by suo** [comment]
This is no longer necessary
