### ISSUE TITLE
Run two GPU task in parallel

### ISSUE THREAD

**Issue by zmonoid** [pytorch/pytorch#18172]
## ❓ Questions and Help
I want do to something like this:

```python
model1 = torch.nn.DataParallel(Net(), device_ids=[0,1]).cuda()
model2 = torch.nn.DataParallel(Net(), device_ids=[2,3]).cuda()

def task(model, data):
  ...
  return out

out1 = task(model1, data1)
out2 = task(model2, data2)
```
I want to get ```out1 out2``` in parallel, using torch.multiprocessing will cause error. Any idea on how to do this

**Comment by VitalyFedyunin** [comment]
Can you please be more specific about the nature of the error you are getting while trying torch.multiprocessing

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
