### ISSUE TITLE
Fail to apply advanced sampler when using torchvision.transforms.Resize with 16-bit images

### ISSUE THREAD

**Issue by ChopinSharp** [pytorch/pytorch#18174]
My input data are 16-bit tiff images. I tried to use torchvision.transforms.Resize to pre-process my data, but it won't work. The reason is that torchvision.transforms.Resize internally uses PIL.Image.resize to resize image, **but for 16-bit images, only nearest-neighbour sampler is available** in pillow. Now I use OpenCV to resize my data and it works fine.
It took me some time to get the things straight. I hope there could be like a hint in the torchvision.transforms.Resize doc to remind users about this issue.
Best regards.

**Comment by vishwakftw** [comment]
Please open this in [torchvision](https://github.com/pytorch/vision).
