### ISSUE TITLE
Undefined symbol "_state"

### ISSUE THREAD

**Issue by personjerry** [pytorch/pytorch#1818]
I'm trying to build on Mac OS X, using

`MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python3 setup.py install`

And I'm running into this error:

```
[  4%] Linking CXX shared library libTHD.dylib
ld: warning: directory not found for option '-L/usr/local/cuda/lib64'
Undefined symbols for architecture x86_64:
  "_state", referenced from:
      _THDTensorDescriptor_newFromTHCudaDoubleTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaFloatTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaLongTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaIntTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaShortTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaCharTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaByteTensor in TensorDescriptor.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libTHD.1.dylib] Error 1
make[1]: *** [CMakeFiles/THD.dir/all] Error 2
make: *** [all] Error 2
```

Is this a bug or did I miss something?

Edit:

This might be relevant:

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: no LC_RPATH load command with path: /usr/local/cuda/lib found in: ~/Desktop/pytorch/torch/lib/tmp_install/lib/libTHPP.1.dylib (for architecture x86_64), required for specified option "-delete_rpath /usr/local/cuda/lib"
```

**Comment by apaszke** [comment]
Yes, this is a bug on our side (appears only on machines without CUDA). For now, you can build with `NO_DISTRIBUTED=1`

**Comment by personjerry** [comment]
Are you sure this bug only appears on machines without CUDA? That's strange because my machine does have CUDA 8 (I have tensorflow-gpu installed). I think my cuda files live in `/usr/local/cuda/lib` and not `/usr/local/cuda/lib64`, but I looked through the default linker arguments and it looks like we include both as -L options?

Also, I started using `MACOSX_DEPLOYMENT_TARGET=10.11` instead of `10.9` because I realized that was the wrong version, but it didn't fix anything.

Also, I ran `install_name_tool -add_rpath /usr/local/cuda/lib ~/Desktop/pytorch/torch/lib/tmp_install/lib/libTHPP.1.dylib` and this seemed to solve the error listed in my edit.

**Comment by kirktsao** [comment]
I got the same problems.
My PC is hacktonish.
E1231 with GPU GTX960.
I had Install Cuda 8.0 and CLT.
Same error.
How to solve this?

**Comment by asawanggaa** [comment]
Same problems in Sierra.
with GPU GT 750M.
CUDA 8.0 installed.

**Comment by zhaopengme** [comment]
Same problems in Sierra.
with GPU GTX 1070.
CUDA 8.0 installed.

**Comment by SShumilin** [comment]
Also the same for GTX 1060

**Comment by elbamos** [comment]
+1

**Comment by soumith** [comment]
@apaszke this seems to be that THD needs to be explicitly linked against CUDA in the cmake on OSX.

**Comment by soumith** [comment]
this is fixed now.

**Comment by soumith** [comment]
I think this is fixed now via https://github.com/pytorch/pytorch/pull/2067
If someone could confirm, i'll close the issue.

**Comment by elbamos** [comment]
The test should simply be install from master with gpu enabled right?

**Comment by elbamos** [comment]
No go so far.  With Xtools 7.3, I get errors related to thread-local storage, which I expect is related to OpenMP?

Command: `MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install git+git://github.com/pytorch/pytorch`
Sample error: 
```
    [ 91%] Building CXX object CMakeFiles/THD.dir/master_worker/worker/Dispatch.cpp.o
    In file included from /private/var/folders/s1/_v14lsc56tv44hm304m07vn40000gq/T/pip-4o3uw7yr-build/torch/lib/THD/master_worker/master/State.cpp:1:
    /private/var/folders/s1/_v14lsc56tv44hm304m07vn40000gq/T/pip-4o3uw7yr-build/torch/lib/THD/master_worker/master/State.hpp:23:3: error: thread-local storage is not supported for the current target
      thread_local static rank_type s_current_worker;
      ^
```

**Comment by soumith** [comment]
hmmm, okay. maybe we need to default to 
`NO_DISTRIBUTED=1 python setup.py install` on OSX. I'll prepare a patch, but you can use this command in the meanwhile.

**Comment by elbamos** [comment]
Let me give that a try before you put in work on a patch.  OS X GPU installation is such Voodoo, its possible something else is going wrong.

**Comment by elbamos** [comment]
It does install with `NO_DISTRIBUTED=1`

**Comment by apaszke** [comment]
@elbamos you're using an old Apple clang version. It now supports thread local storage.

**Comment by elbamos** [comment]
Ah - I see what’s going on.  Nvidia switched from supporting Xcode 7.3 to 8.2.  I just switched and I get a good install w/o `NO_DISTRIBUTED=1`  Thanks!



On July 13, 2017 at 7:03:26 PM, Adam Paszke (notifications@github.com) wrote:

@elbamos you're using an old Apple clang version. It now supports thread local storage.

**Comment by zhaopengme** [comment]
![image](https://user-images.githubusercontent.com/1415418/28195855-73858b82-687f-11e7-8169-cf2f221d1bef.png)

good .perfect!
