### ISSUE TITLE
[CPU] several inplace functions fail since 1.0.1 on certain hw

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#18189]
## To Reproduce

This bug is CPU-related. 

On certain hardware inplace started failing since 1.0.1, works fine with 1.0.0

Here are 2 identical tests, except the first one uses inplace funcs `tanh_`, `sigmoid_` and the second one doesn't.

Both tests should print only 0's (used print instead of torch.allclose() because the assert is loud and messy).

But on my hardware and (occasionally on azure CI) the inplace test fails most of the time, printing non-zero in the last 2 prints (one or both). The behavior is random. When the tensor is large failures are more consistent. I added my cpu-info at the end of this report.

```
import torch
import torch.nn as nn

def test_inplace():
    linear = nn.Linear(20,6)

    x_fwd = torch.randn(7,1,20)
    x_bwd = x_fwd.clone().flip(1)

    y_fwd = linear(x_fwd)
    y_bwd = linear(x_bwd)
    print((y_fwd-y_bwd).abs().sum().item())
    z_gate_fwd,f_gate_fwd,o_gate_fwd = y_fwd.chunk(3, dim=2)
    z_gate_bwd,f_gate_bwd,o_gate_bwd = y_bwd.chunk(3, dim=2)
    print((z_gate_fwd-z_gate_bwd).abs().sum().item())
    print((f_gate_fwd-f_gate_bwd).abs().sum().item())
    print((o_gate_fwd-o_gate_bwd).abs().sum().item())
    z_gate_fwd.tanh_()
    z_gate_bwd.tanh_()
    f_gate_fwd.sigmoid_()
    f_gate_bwd.sigmoid_()
    z_gate_fwd,f_gate_fwd = z_gate_fwd.contiguous(),f_gate_fwd.contiguous()
    z_gate_bwd,f_gate_bwd = z_gate_bwd.contiguous(),f_gate_bwd.contiguous()
    print((z_gate_fwd-z_gate_bwd).abs().sum().item())
    print((f_gate_fwd-f_gate_bwd).abs().sum().item())


def test_non_inplace():
    linear = nn.Linear(20,6)

    x_fwd = torch.randn(7,1,20)
    x_bwd = x_fwd.clone().flip(1)

    y_fwd = linear(x_fwd)
    y_bwd = linear(x_bwd)
    print((y_fwd-y_bwd).abs().sum().item())
    z_gate_fwd,f_gate_fwd,o_gate_fwd = y_fwd.chunk(3, dim=2)
    z_gate_bwd,f_gate_bwd,o_gate_bwd = y_bwd.chunk(3, dim=2)
    print((z_gate_fwd-z_gate_bwd).abs().sum().item())
    print((f_gate_fwd-f_gate_bwd).abs().sum().item())
    print((o_gate_fwd-o_gate_bwd).abs().sum().item())
    z_gate_fwd = z_gate_fwd.tanh()
    z_gate_bwd = z_gate_bwd.tanh()
    f_gate_fwd = f_gate_fwd.sigmoid()
    f_gate_bwd = f_gate_bwd.sigmoid()
    z_gate_fwd,f_gate_fwd = z_gate_fwd.contiguous(),f_gate_fwd.contiguous()
    z_gate_bwd,f_gate_bwd = z_gate_bwd.contiguous(),f_gate_bwd.contiguous()
    print((z_gate_fwd-z_gate_bwd).abs().sum().item())
    print((f_gate_fwd-f_gate_bwd).abs().sum().item())

```

## Expected behavior

Should have identical behavior w/ and w/ inplace and print only 0's:
```
0.0
0.0
0.0
0.0
0.0
0.0
```
But for `test_inplace` getting:

```
0.0
0.0
0.0
0.13790962100028992
0.1261766254901886
```

last 2 rows sometimes 0's sometimes non-zeros.

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX 1070 Ti

Nvidia driver version: 410.104
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.13.3
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl_fft                   1.0.10           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.0.1           py3.7_cuda10.0.130_cudnn7.4.2_2    pytorch
[conda] pytorch-nightly           1.0.0.dev20190319 py3.7_cuda10.0.130_cudnn7.4.2_0    pytorch
[conda] torchvision               0.2.2                      py_3    pytorch

CPU:
     *-cpu
          product: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          size: 2262MHz
          capacity: 4600MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d cpufreq

**Comment by colesbury** [comment]
I can reproduce this with OMP_NUM_THREADS=2. I haven't seen it with OMP_NUM_THREADS=1.

**Comment by cpuhrsch** [comment]
Working on it here: https://github.com/pytorch/pytorch/pull/18309

**Comment by cpuhrsch** [comment]
@stas00 - Could I ask you to try https://github.com/pytorch/pytorch/pull/18309 as a fix? On my end I don't see the bug anymore after patching this.

**Comment by stas00** [comment]
@cpuhrsch, I confirm that this fixes the failing test. Thank you!

**Comment by cpuhrsch** [comment]
With https://github.com/pytorch/pytorch/pull/18309 closed the issue should be resolved. Please let me know if that's not the case. I'm closing the issue for now.

**Comment by stas00** [comment]
I checked with nightly build and it works, thank you @cpuhrsch!
