### ISSUE TITLE
Mixed numpy-pytorch binary operators produce unexpected results

### ISSUE THREAD

**Issue by stepelu** [pytorch/pytorch#1819]
Test case (the order is important):

```
print(type(numpy.exp(1) + Variable(torch.zeros(2, 5))))
# <class 'numpy.ndarray'> (of really strange shape)
```

I understand why this is happening but I'd prefer an error to be thrown here if possible when the "expected" behaviour cannot be achieved.

**Comment by fmassa** [comment]
This is a duplicate of https://github.com/pytorch/pytorch/issues/1294

**Comment by soumith** [comment]
closing because duplicate.
