### ISSUE TITLE
GLOO not optional?

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#18202]
## 🐛 Bug
When disabling GLOO with -DUSE_GLOO=OFF, it fails to compile with the following error:
pytorch/torch/lib/c10d/ProcessGroupGloo.hpp:10:10: fatal error: gloo/algorithm.h: No such file or directory

## To Reproduce

1. Set CMake variable USE_GLOO to off
2. Generate and Compile

## Expected behavior

Compiles

## Environment

PyTorch Version: 1.0.1
OS: Linux x86_64
CMake Flags:
-DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=OFF -DBUILD_TORCH=ON -DUSE_OPENCV=OFF -DBUILD_TEST=OFF -DATEN_NO_TEST=ON -DUSE_QNNPACK=OFF -DUSE_NNPACK=OFF -DUSE_CUDA=OFF -DUSE_LMDB=OFF -DUSE_GLOO=OFF

## Context
https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/CMakeLists.txt#L52 ProcessGroupGloo seems to be compiled in unconditionally.
PR: https://github.com/pytorch/pytorch/pull/18203
```

**Comment by pietern** [comment]
This is fixed in #18203.

Curious to know, which of the distributed backends do you use?

**Comment by xsacha** [comment]
NCCL
