### ISSUE TITLE
error: expected unqualified-id before ‘static_cast’

### ISSUE THREAD

**Issue by xianshunw** [pytorch/pytorch#18205]
## ❓ error: expected unqualified-id before ‘static_cast’

We have the following problem when we use the libtorch built from source.
``
[build] /home/xswang/workspace/FPM_init/libtorch/include/ATen/core/interned_strings.h:271:1: error: expected unqualified-id before ‘static_cast’ 
[build]  FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
[build]  ^
[build] /home/xswang/workspace/FPM_init/libtorch/include/ATen/core/interned_strings.h:271:1: error: expected ‘)’ before ‘static_cast’
``
However when we use the officially released libtorch, the problem disappears. 

Here are some basic infos:
System: Ubuntu 18.04
CUDA: None
BUILD_CAFFE2_OPS=OFF
python: 3.6
g++: 7.3

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by xianshunw** [comment]
I am sorry, it seems that not because of compilation.  the problem from my other code.

**Comment by cemreefe** [comment]
so what was the problem?

**Comment by mihaly-sisak** [comment]
Totally unrelated to pytorch I found this as the google result of "cpp static cast expected unqualified id".
My problem was that I wrote "std::static_cast<>()". But static_cast is a keyword, not some std function so I had to write "static_cast<>()" to fix my problem.
