### ISSUE TITLE
Cannot open include file: 'numa.h': No such file or directory 

### ISSUE THREAD

**Issue by libichong** [pytorch/pytorch#18214]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

I want to build libtorch for windows x64 by using build_windows.bat. I disabled numa and glog but still got the following failure. Could you give some hints how to fix it?

D:\Code\GitHub\pytorch\CMakeFiles\CMakeTmp\src.cxx(1): fatal error C1083: Cannot open include file: 'numa.h': No such file or directory [D:\Code\GitHub\pytorch\CMakeFiles\CMakeTmp\cmTC_3a810.vcxproj]

D:\Code\GitHub\pytorch\CMakeFiles\CMakeTmp\src.cxx(1): fatal error C1083: Cannot open include file: 'glog/stl_logging.h': No such file or directory [D:\Code\GitHub\pytorch\CMakeFiles\CMakeTmp\cmTC_d2d67.vcxproj]

**Comment by peterjc123** [comment]
No, you should not call `build_windows.bat`. You should call `tools\build_libtorch.py` instead. BTW, could you please tell me where the instruction you use (call build_windows.bat) was written?

**Comment by peterjc123** [comment]
I see. It was written here. https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile
 @orionr Is `build_windows.bat` still the case for building caffe2?

**Comment by peterjc123** [comment]
Well, it looks like a bug in `torch/CMakeLists.txt` that turns `USE_NUMA` and `USE_GLOG` on by default. I'll fix them.

**Comment by orionr** [comment]
I agree - we should likely remove build_windows.bat and standardize on setup.py and build_libtorch.py.

**Comment by libichong** [comment]
Thanks @peterjc123 and @orionr for the quick action to fix it.
