### ISSUE TITLE
IndyLSTM & IndyGRU in PyTorch

### ISSUE THREAD

**Issue by kayuksel** [pytorch/pytorch#18219]
## 🚀 Feature

https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/IndyLSTMCell
https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/IndyGRUCell

## Motivation

https://arxiv.org/abs/1803.04831
https://arxiv.org/abs/1903.08023

**Comment by soumith** [comment]
it's not widely used enough yet, to be pushed into core (feel free to reopen once it becomes more of a standard).

Additionally, we are working on a user handwritten RNNs being fast, rather than adding more fundamental multi-layer RNNs into core.
So, I'm closing the feature request.
