### ISSUE TITLE
Octree support

### ISSUE THREAD

**Issue by mdering** [pytorch/pytorch#1824]
it's kind of a niche use case, but some work has been done to implement octrees for volumetric data, this saves a lot of space and can really be helpful if your data is sparse. Some code for torch is here https://github.com/griegler/octnet. Is there a way we can integrate this into pytorch?

**Comment by soumith** [comment]
the best way of integration is to write a separate package (like you've already done).
You can create [a pytorch extension](https://github.com/pytorch/extension-ffi). Here's an example: https://github.com/pytorch/audio
