### ISSUE TITLE
What does "it/s" when downloading pth file? 97913.93it/s?

### ISSUE THREAD

**Issue by yiran7324** [pytorch/pytorch#18260]
## ❓What does "it/s" when downloading pth file?

![img](https://i.loli.net/2019/03/21/5c9309a76f51f.png)

I have search about it but only get some other results due to the grammar of searching. Certainly, it is not a kb/s or mb/s like things, or I guess it is item/s still can not get what is the item.

**Comment by vishwakftw** [comment]
Please open this in [Torchvision](https://github.com/pytorch/vision).

**Comment by eegk** [comment]
What is it/s ?

**Comment by spreck** [comment]
Interesting that this is the top result on google search but no answer... I looked on the Torchvision repo but couldn't find anything. 

Why not just answer the question here and do everyone trying to find it a favor?

**Comment by DanielEdrisian** [comment]
I think it means "iterations per second". The progress bar's change in value seems to correlate to the number. I might be wrong, though.

**Comment by hijabfatima5** [comment]
I believe it/s means 'iterations per second'.
