### ISSUE TITLE
DistributedDataParallel

### ISSUE THREAD

**Issue by chenhuiji** [pytorch/pytorch#18268]
## 🚀 Feature

Would DistributedDataParallel wrapper cost much GPU memory? In my case, the model cost 1133MB when loaded into a GPU. However, when wrapped in DistributedDataParallel and run in the distributed mode, it costs 12000MB GPU momery. Is this correct?  With considering the gradient memory (1133MB) and initilization memroy (567MB), it should not cost 12000MB. 
Is it caused by the  DistributedDataParallel wrapper? Are there any methods to save memory usage? Thanks!

**Comment by fmassa** [comment]
Do you have a minimum example that you can share that reproduces the behavior you are seeing?
Also, what pytorch version are you using?

**Comment by soumith** [comment]
it should not cost that much, you are very likely misusing the class by not setting the GPU correctly.

See our documentation: https://pytorch.org/docs/stable/distributed.html#launch-utility

Especially see the section that says: `Set your device to local rank using either`

**Comment by turboxin** [comment]
@soumith I set up GPU just as the doc you posted, however I still noticed  that DistributedDataParallel wrapper cost more GPU memory:
the model cost around 7300 MB when loaded into one GPU, and 21129 when wrapped in DistributedDataParallel.

**Comment by turboxin** [comment]
@chenhuiji, hi, did you figure it out what's causing the memory problem? Thanks a lot! Or could you reopen this issue

**Comment by chenhuiji** [comment]
Hi, turboxin. what's your environment? GPU, PyTroch, machine version




------------------ 原始邮件 ------------------
发件人: "turboxin"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 晚上8:26
收件人: "pytorch/pytorch"<pytorch@noreply.github.com>;
抄送: "陈辉"<764187653@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [pytorch/pytorch] DistributedDataParallel (#18268)




@chenhuiji, hi, did you figure it out what's causing the memory problem? Thanks a lot! Or could you reopen this issue

**Comment by turboxin** [comment]
hi @chenhuiji, thanks for replying~
My environment is:
GPU: Nvidia v100
Pytorch: 1.1.0
Cuda 9.2
cudnn: 7.2 
ubuntu 16.04

**Comment by chenhuiji** [comment]
Hi, I list my situation below.


Single GPU mode:
When the model is loaded, it costs 2200M GPU memory, and it costs 8174M GPU memory in the training phase.



DDP mode: similar situation. A bit more GPU cost than Single-GPU mode.



It would cost more GPU memory in the training phase. In my situation, around 4 times.
My env: Tesla P40, PyTorch 1.1.0, FloatTensor.
Hope this would help!




------------------ 原始邮件 ------------------
发件人: "turboxin"<notifications@github.com>;
发送时间: 2019年10月15日(星期二) 下午5:21
收件人: "pytorch/pytorch"<pytorch@noreply.github.com>;
抄送: "陈辉"<764187653@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [pytorch/pytorch] DistributedDataParallel (#18268)




hi @chenhuiji, thanks for replying~
 My environment is:
 GPU: Nvidia v100
 Pytorch: 1.1.0
 Cuda 9.2
 cudnn: 7.2
 ubuntu 16.04
