### ISSUE TITLE
Precision loss of large tensor averaging on CPU

### ISSUE THREAD

**Issue by pshvechikov** [pytorch/pytorch#18277]
## 🐛 Bug

Taking `mean()` of a large CPU tensor results in severe precision loss. 
I would like to know if the following behaviour is known and normal. 

## To Reproduce

```
shape = (1000, 1000)
for i  in range(10000):
    if i > 9990: 
        print(tr.ones(*shape).fill_(i).mean(), "   \t",  tr.ones(*shape).fill_(i).cuda().mean())
```

produces 

```
tensor(9991.5693)    	 tensor(9991., device='cuda:0')
tensor(9991.9990)    	 tensor(9991.9990, device='cuda:0')
tensor(9992.4297)    	 tensor(9993., device='cuda:0')
tensor(9993.7197)    	 tensor(9994., device='cuda:0')
tensor(9995.5684)    	 tensor(9995., device='cuda:0')
tensor(9996.)    	 tensor(9996., device='cuda:0')
tensor(9996.4287)    	 tensor(9997.0010, device='cuda:0')
tensor(9998.2793)    	 tensor(9998., device='cuda:0')
tensor(9999.5693)    	 tensor(9999., device='cuda:0')
```

## Expected behavior

Close match between CPU and GPU versions of mean operation. 

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 390.116
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.6            py37hd81dba3_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.0.1           py3.7_cuda9.0.176_cudnn7.4.2_2    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by soumith** [comment]
this definitely looks like normal behavior. It's standard floating point effects at play.
If you want higher precision, you can try to use double precision:

```
print(tr.ones(*shape, dtype=torch.float64).fill_(i).mean(), "   \t",  tr.ones(*shape, dtype=torch.float64).fill_(i).cuda().mean())
```

**Comment by soumith** [comment]
double precision gives the output:

```
tensor(9991., dtype=torch.float64)       tensor(9991., device='cuda:0', dtype=torch.float64)
tensor(9992., dtype=torch.float64)       tensor(9992., device='cuda:0', dtype=torch.float64)
tensor(9993., dtype=torch.float64)       tensor(9993., device='cuda:0', dtype=torch.float64)
tensor(9994., dtype=torch.float64)       tensor(9994., device='cuda:0', dtype=torch.float64)
tensor(9995., dtype=torch.float64)       tensor(9995., device='cuda:0', dtype=torch.float64)
tensor(9996., dtype=torch.float64)       tensor(9996., device='cuda:0', dtype=torch.float64)
tensor(9997., dtype=torch.float64)       tensor(9997., device='cuda:0', dtype=torch.float64)
tensor(9998., dtype=torch.float64)       tensor(9998., device='cuda:0', dtype=torch.float64)
tensor(9999., dtype=torch.float64)       tensor(9999., device='cuda:0', dtype=torch.float64)
```
