### ISSUE TITLE
batch matrix-vector multiplication (bmv)

### ISSUE THREAD

**Issue by ethanluoyc** [pytorch/pytorch#1828]
I checked the documentation online. It appears that although there are methods for 
batch matrix multiplication, there does not seem to have one for batch matrix-vector multiplication?
I guess it is not difficult to implement this, since we can just squeeze the 2D tensor representing the batch vector into 3D and then do `bmm`, but it would be really convenient to have one.

**Comment by gchanan** [comment]
torch.matmul on master should do what you want.

**Comment by ethanluoyc** [comment]
Great! I shall close this then.

**Comment by around1991** [comment]
Sorry to reopen an old thread: but the following code fails:

```
batch1 = torch.randn(10, 5, 20)
batch2 = torch.randn(10, 20)

test = torch.matmul(batch1, batch2)
```

What is the correct way of computing the batched matrix vector product between `batch1` and `batch2`?

**Comment by soumith** [comment]
according to broadcasting rules, batch2 wont auto-expand because you are not prepending dimensions.
I believe you can do:
`batch2 = batch2.unsqueeze(2)`
