### ISSUE TITLE
question about `-D_GLIBCXX_USE_CXX11_ABI` when compiling pytorch and pytorch extensions.

### ISSUE THREAD

**Issue by hubutui** [pytorch/pytorch#18311]
According to #13541, PyTorch is compiled with `-D_GLIBCXX_USE_CXX11_ABI=0` by default. However, https://github.com/pytorch/pytorch/blob/83221655a8237ca80f9673dad06a98d34c43e546/torch/utils/cpp_extension.py#L398 shows that python extension is built with `-D_GLIBCXX_USE_CXX11_ABI=0` too. But if I have pytorch built with `-D_GLIBCXX_USE_CXX11_ABI=1`, I can't override `-D_GLIBCXX_USE_CXX11_ABI=1` when building an extension, thus causing the extension a ABI issue.
Maybe we could add an option to set up this flag?

**Comment by ezyang** [comment]
Yes, this is a legit bug. I'll happily accept a patch to fix this. I don't recall if we publish which ABI we were built with, but assuming there is a way to check, all you need to do is condition the flag on that flag.

**Comment by hubutui** [comment]
Emm, I'm trying to build [apex](https://github.com/NVIDIA/apex) for ArchLinux.  And according to pytorch's [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-pytorch), there is no modify related to this flag. I believe that pytorch is build with `-D_GLIBCXX_USE_CXX11_ABI=0`, which is the default behavior of pytorch official configuration. So it would be OK to build apex extension with the same flag, aka `-D_GLIBCXX_USE_CXX11_ABI=0`. However, it's not. I try to build build apex with `-D_GLIBCXX_USE_CXX11_ABI=1` by manually replace all `-D_GLIBCXX_USE_CXX11_ABI=0` to `-D_GLIBCXX_USE_CXX11_ABI=1` in `/usr/lib/python3.7/site-packages/torch/utils/cpp_extension.py`, and it works as expected. So, it might be a bug? related issue https://github.com/NVIDIA/apex/issues/212

**Comment by ezyang** [comment]
So, I want to reiterate that the bug you reported up top is a legit bug, in and of itself. However, the apex problem you're running into sounds different. If it's true that forcing apex to build with `-D_GLIBCXX_USE_CXX11_ABI=1` fixes your problem, then maybe the root cause is that PyTorch was bbuilt with the new ABI all along.

**Comment by soumith** [comment]
this was fixed via https://github.com/pytorch/pytorch/pull/18994
It is part of 1.1 release.
