### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by LIMr1209** [pytorch/pytorch#18325]
mdoel = torch.load('/opt/checkpoint/ResNet152.pth',map_location='cpu')

Traceback (most recent call last):
  File "/home/tian/pycharm-2018.3.3/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/tian/pycharm-2018.3.3/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/tian/pycharm-2018.3.3/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/tian/pycharm-2018.3.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/opt/project/python/opalus/fff.py", line 3, in <module>
    mdoel = torch.load('/opt/checkpoint/ResNet152_quantize.pth',map_location='cpu')
  File "/home/tian/.conda/envs/jiqi/lib/python3.6/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/home/tian/.conda/envs/jiqi/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'

**Comment by SsnL** [comment]
https://pytorch.org/docs/master/notes/serialization.html#recommended-approach-for-saving-a-model

**Comment by cccober** [comment]
I met the same issue, how to fix it?

**Comment by LIMr1209** [comment]
However in this case, the serialized data is bound to the specific classes and the exact directory structure used, so it can break in various ways when used in other projects, or after some serious refactors. @cccober

**Comment by cccober** [comment]
thanks!

**Comment by jhagege** [comment]
How about if I want to save multiple values with torch.save ? 
I did `torch.save({'model': model.state_dict(), 'acc': best_valid_acc, 'epoch': epoch, 'network_params': network_params, 'drop_path_prob': drop_path_prob}) and encountering the same error.`

**Comment by ericwtlin** [comment]
> How about if I want to save multiple values with torch.save ?
> I did
> 
> ```
> torch.save({'model': model.state_dict(), 'acc': best_valid_acc, 'epoch': epoch, 'network_params': network_params, 'drop_path_prob': drop_path_prob})
> ```
> 
> and encountering the same error.
> 
> ```
> state = torch.load(state_path)
> ModuleNotFoundError: No module named 'cnn'
> ```
> 
> after changing the directory structure.
> I thought using model.state_dict() was robust to directory structure changes..

I met the same problem with problem with @jhagege

**Comment by pinkhamr** [comment]
I'm having the same issue as @jhagege and @ericwtlin, any solutions?

**Comment by Ryuk17** [comment]
I used 
`torch.save(model_object, 'model.pkl')`
but I cannot load the trained model by
`model = torch.load('model.pkl')`

**Comment by Coderx7** [comment]
In order to get rid of such errors, first save your models using `torch.jit.trace(model, example_input)` and then save it using `torch.jit.save(model)`. ultimately load your model using `torch.jit.load('path to new model parameters') `

```python
def convert_weights(model, input=torch.tensor(torch.rand(size=(1,3,112,112)))):
        model = torch.jit.trace(model, input)
        torch.jit.save(model,'/home/coderx7/Documents/models/model_parameters.pt')
```
then load the model 
```python
self.model = torch.jit.load('/home/coderx7/Documents/models/model_parameters.pt')
```

**Comment by Ryuk17** [comment]
thanks

**Comment by Asteria-BCSD** [comment]
Try to construct a module with the same path in your previous project.

**Comment by Pradhy729** [comment]
I'm facing the same issue, did anyone figure out a good way to resolve this? @Coderx7 's solution did not work for me.

**Comment by pinkhamr** [comment]
To load it, I found replicating the original file structure with a dummy file sufficed and would allow me to resave the model with a different method. After I realized this was a problem, I saved the model definition separately from the weights and as long as I loaded them in that order I didn't have the module not found issue.

**Comment by priteshgohil** [comment]
**torch.load() requires model module in the same folder**  pytorch/pytorch#3678

**Comment by azuryl** [comment]
> replicating the original file structure with a dummy file
how to replicating the original file structure with a dummy file

**Comment by GoingMyWay** [comment]
> **torch.load() requires model module in the same folder** #3678

I think you are right.

**Comment by barrelchester** [comment]
I'm getting this error when trying to load a third party checkpoint that I didn't originally save. I have the checkpoint file in the same directory as my code.

checkpoint = torch.load('model_checkpoint.pth.tar')
ModuleNotFoundError: No module named 'models'

Looking through the third party source code I can see that they saved the model this way:
torch.save({'epoch': epoch, 'model': model}, 'model_checkpoint.pth.tar')

I also tried to load it with torch.load_state_dict('model_checkpoint.pth.tar') but that didn't work either.
Any help I could get would be much appreciated.

**Comment by lunaryan** [comment]
I solved it by adding the ckpt path to sys.path

**Comment by wyxscir** [comment]
> 

thank you! it works!

sys.path.append('/mnt/.../my_demo')

**Comment by wyxscir** [comment]
> I solved it by adding the ckpt path to sys.path

thank you! it works!

sys.path.append('/mnt/.../my_demo')
