### ISSUE TITLE
Unserialize autograd

### ISSUE THREAD

**Issue by slaweku** [pytorch/pytorch#18333]
## 🚀 Feature [FR] Unserialize autograd

backward() function is serialized, per device, so also on CPU. A multithreaded learning (e.g. with separate models, trainers) is not possible, no matter how many cores the box has.
My models are small, so GPUs are not that useful, but I would like to train a number of them concurrently, e.g. by manipulating a subset of data presented to each of them. 
Also, evolutionary algorithms/NNs hybrids would benefit.
Multithreading was supposed to be a major use case for C++/Libtorch, but is rather crippled with backward() serialized.

**Comment by ezyang** [comment]
I don't object to this feature on principle (although there are a number of UI problems we would have to solve first), but it is not going to be too easy to do. Here's a relevant comment from autograd engine:

```
// XXX: Changes to the way multithreading works in execute should be done with
// great care. Right now the implementation guarantees that a single function's
// apply will never be entered concurrently (even if multiple graphs are
// executed at the same time). Adding multiple threads per-device or removing
// engine thread affinity to the device can break this invariant, and we depend
// on it in a few places (e.g. AccumulateGrad function).
```

Perhaps one possible way we can skirt around this is by introducing virtual CPU devices (which will help us maintain the invariant once again.) Not obvious to me what the best thing to do is. CC @apaszke

**Comment by yf225** [comment]
Related: https://github.com/pytorch/pytorch/issues/17566

**Comment by ezyang** [comment]
cc @apaszke, if someone implemented a PR like this, do you think we should accept it?

**Comment by apaszke** [comment]
I think it all depends on the complexity, but it is a very reasonable request. However, it needs to take our existing constraints into account. Basically, we can allow parallel execution, but only on disjoint graphs (i.e. no nodes are shared). This can be implemented relatively easily by adding an atomic boolean field on `Function` to allow threads to "lock" them, but I'm afraid it might turn out to be very complicated.

**Comment by slaweks17** [comment]
Hi,
May I ask if there is any progress?

**Comment by ezyang** [comment]
@wanchaol is working on this

**Comment by slaweks17** [comment]
Great news, thank you!

**Comment by slaweks17** [comment]
Thank you very much!!

**Comment by wanchaol** [comment]
@slaweks17 no problem, let me know if you see any issues when you experiment with this feature :)
