### ISSUE TITLE
Pass Multiple Tensors in CPP Module Forward

### ISSUE THREAD

**Issue by eholly1** [pytorch/pytorch#18337]
## 🚀 Feature
Functionality to pass multiple tensors as arguments to cpp module forward.

## Motivation

Used python library torch.jit.ScriptModule to save a module whose forward method takes two inputs, `def forward(self, x, y)`. After loading in cpp with torch::jit::load, I can't figure out how to correctly pass the input to my forward function.

In [issue #15523](https://github.com/pytorch/pytorch/issues/15523), the author @szupzp mentions cat'ing the input tensor, then splitting it inside the function... this approach seems like a workaround.

## Pitch

Is there a proper way to do this? If not, can it be added to the API? If so, is it documented?

**Comment by eholly1** [comment]
[solved] Turned out it works to push multiple input tensors to the IValue like so:

`std::vector<torch::jit::IValue> i;
  std::vector<float> x = {2.0, 1.0, 0.5, 3.0, 4.0};
  std::vector<float> y = {3.0, 2.0};
  i.push_back(torch::tensor(x));
  i.push_back(torch::tensor(y));

  torch::Tensor output = module->forward(i).toTensor();`

**Comment by soumith** [comment]
cc: @yf225 @gchanan maybe we should push docs or examples to cppdocs wrt this

**Comment by yinxiaochuan** [comment]
Thank you @eholly1 !

**Comment by szupzp** [comment]
OK. So How many outputs in your forward function? In addition, you can push
the inputs to  IVALUE orderly!

Ethan Holly <notifications@github.com> 于2019年3月23日周六 上午1:03写道：

**Comment by hhbyyh** [comment]
Thanks @eholly1 .  This resolves my problem.

**Comment by sukuya** [comment]
@eholly1  But I have my input as a `tensor, tuple (tensor, tensor)`. If I give three tensors in a vector of `IValue` then I am getting pickle error: `terminate called after throwing an instance of 'c10::Error'
  what():  Unknown class name for unpickler: build_tensorlist (getClass at /pytorch/torch/csrc/jit/pickler.cpp:21)` Any clue.

**Comment by sukuya** [comment]
> @eholly1
> I am trying to perform forward on two inputs. First is a tensor and second a tuple of two tensors.
> `std::vector<torch::jit::IValue> input;`
> ` std::tuple<torch::Tensor, torch::Tensor> hidden {torch::ones({2, 10, 200}), torch::ones({2, 10, 200})};`
> `torch::Tensor x = torch::ones({10,10}); `
> `input.push_back(x); input.push_back(torch::ones({2, 10, 200}));`
> ` input.push_back(torch::ones({2, 10, 200}));`
> This gives me the following error:
> terminate called after throwing an instance of `'c10::Error' what(): Unknown class name for unpickler: build_tensorlist (getClass at /pytorch/torch/csrc/jit/pickler.cpp:21)`

I realize the error is not in passing the input to the model, but the model itself is not loaded properly.
`shared_ptr<torch::jit::script::Module> module = torch::jit::load(argv[1]);` at this line itself.

**Comment by wanchaol** [comment]
close this in favor of the doc issue

**Comment by kli017** [comment]
hello, I was wondering could y be a int instead of a tensor here?
