### ISSUE TITLE
Port TemporalReplicationPadding to ATen

### ISSUE THREAD

**Issue by ericnakagawa** [pytorch/pytorch#18355]
Medium

**Comment by xmnlab** [comment]
it seems this task was already done in PR #15507 and #15485.

**Comment by rgommers** [comment]
Thanks looks right, thanks @xmnlab. @ezyang can you confirm and close this?

**Comment by ezyang** [comment]
I agree, and in the future, you can close tasks this way :)

**Comment by rgommers** [comment]
thanks

> and in the future, you can close tasks this way :)

I don't have rights to do that. but maybe @xmnlab or @skrah does by now?

**Comment by ezyang** [comment]
I filed a ticket to give you rights.
