### ISSUE TITLE
NCCL uses old(?) CUDA ARCH, causing very slow startup

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#18359]
## 🐛 Bug

On my computer (with GTX1080Ti, CUDA 10) and with today's master, I'm getting extremely slow (60 sec?) startup times. `sudo perf top` (thanks, @soumith) indicates that this is due ptx-jitting. Using NCCL seems to produce sm_30 assembly in the libcaffe2_gpu.so, which I don't get when not using NCCL.

Setting TORCH_CUDA_ARCH=6.1 doesn't help.

## To Reproduce

Compile from source on GTX1080Ti with CUDA 10. With USE_NCCL=1 vs with USE_NCCL=0.
Then initialize any cuda tensor.

**Comment by SsnL** [comment]
relevant: https://github.com/pytorch/pytorch/issues/13763
