### ISSUE TITLE
arange cuda bug

### ISSUE THREAD

**Issue by pfrendl** [pytorch/pytorch#18363]
## 🐛 Bug

torch.arange() does not adhere to the documentation for small stepsizes for cuda tensors.

## To Reproduce

input
```
a = torch.arange(-4.0, 4.0, 0.1, dtype=torch.float32, device='cpu')
b = torch.arange(-4.0, 4.0, 0.1, dtype=torch.float32, device='cuda')
c = torch.arange(-4.0, 4.0, 0.01, dtype=torch.float32, device='cpu')
d = torch.arange(-4.0, 4.0, 0.01, dtype=torch.float32, device='cuda')
a.shape, b.shape, c.shape, d.shape
```

output
`(torch.Size([80]), torch.Size([80]), torch.Size([800]), torch.Size([801]))`

input
`a[0], b[0], c[0], d[0], a[-1], b[-1], c[-1], d[-1]`

output
`(tensor(-4.), tensor(-4., device='cuda:0'), tensor(-4.), tensor(-4., device='cuda:0'), tensor(3.9000), tensor(3.9000, device='cuda:0'), tensor(3.9900), tensor(4.0000, device='cuda:0'))`

## Expected behavior

The method should behave according to the documentation as far as possible (quantization error can probably cause problems).
The method should behave identically to the cpu implementation.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.1
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.6.4
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: 1 x GTX 1080

**Comment by hongzhen1** [comment]
@soumith you only fix arrange shape, range has the same issue, right?
