### ISSUE TITLE
dimension specified as 0 but tensor has no dimensions

### ISSUE THREAD

**Issue by Quadrifoglio-Sha** [pytorch/pytorch#18377]
Traceback (most recent call last):
  File "main.py", line 221, in <module>
    test()
  File "main.py", line 200, in test
    prob = probs[start:stop]
RuntimeError: dimension specified as 0 but tensor has no dimensions

```
<for batch in tqdm(test_iter):
        features,_,summaries,doc_lens = vocab.make_features(batch)
        t1 = time()
        if use_gpu:
            probs = net(Variable(features).cuda(), doc_lens)
        else:
            probs = net(Variable(features), doc_lens)
        t2 = time()
        time_cost += t2 - t1
        start = 0
        for doc_id,doc_len in enumerate(doc_lens):
            stop = start + doc_len
            prob = probs[start:stop]
            # print(prob)
            topk = min(args.topk,doc_len)
            topk_indices = prob.topk(topk)[1].cpu().data.numpy()
            topk_indices.sort()
            doc = batch['doc'][doc_id].split('\n')[:doc_len]
            hyp = [doc[index] for index in topk_indices]
            ref = summaries[doc_id]
            with open(os.path.join(args.ref,str(file_id)+'.txt'), 'w') as f:
                f.write(ref)
            with open(os.path.join(args.hyp,str(file_id)+'.txt'), 'w') as f:
                f.write('\n'.join(hyp))
            
            start = stop
            file_id = file_id + 1
    print('Speed: %.2f docs / s' % (doc_num / time_cost))>
```

I'm testing the model, but it get the error above, it will happen because start = 0, stop = 1. and that tensor is: 
tensor(0.9138, device='cuda:0', grad_fn=<SqueezeBackward0>) 
Could somebody make some helps? I tried 
`prob = probs.unsqueeze(0)[start:stop]`
but it will raise 

Traceback (most recent call last):
  File "main.py", line 221, in <module>
    test()
  File "main.py", line 206, in test
    hyp = [doc[index] for index in topk_indices]
  File "main.py", line 206, in <listcomp>
    hyp = [doc[index] for index in topk_indices]
TypeError: only integer scalar arrays can be converted to a scalar index

Then I tried to fix this by

`hyp = [doc[index] for index in topk_indices[0]]`
but it will raise "int64 is not iteratable".
Any help or idea is appreciate!
Thanks!!!

**Comment by SsnL** [comment]
your probs tensor is a scalar.

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

also Ssnl gave the answer
