### ISSUE TITLE
Inconsistant results between numpy.median() and torch.median()

### ISSUE THREAD

**Issue by lijunzh** [pytorch/pytorch#1837]
Numpy seems to give the correct median of even number of elements (which is the mean of the center two elements) as defined in [Wikipedia](https://en.wikipedia.org/wiki/Median) while torch gives one of the center elements that are closer to their mean (I guessed from the results I see).  I am not sure if this is intended behavior or we need to fix this bug? As least, I think we should have a function that does the standard median for comparision with numpy or any other math programs, such as MATLAB.

```
In [88]: a = np.random.randn(4, 4)

In [89]: a
Out[89]:
array([[ 0.21654775, -2.84948564, -0.89086479,  0.31074037],
       [-2.02333919,  0.59465567,  1.55680421, -0.33646373],
       [ 1.15586001,  0.16046311,  0.01646207, -1.19663499],
       [ 0.7947269 , -0.22558656, -1.25525967, -0.29217645]])

In [90]: b = torch.from_numpy(a)

In [91]: np.median(a, axis=0)
Out[91]: array([ 0.50563732, -0.03256172, -0.43720136, -0.31432009])

In [92]: torch.median(b, dim=0)[0]
Out[92]:

 0.2165 -0.2256 -0.8909 -0.3365
[torch.DoubleTensor of size 1x4]
```

**Comment by lijunzh** [comment]
By the way, it seems that PyTorch's tensor in cuda does not have a median implemenation yet. I got this error message when trying to call it:

```
AttributeError: 'torch.cuda.DoubleTensor' object has no attribute 'median'
```

Maybe it should be a separate issue, but I think I should mention it here since it is also related to median funciton.

**Comment by soumith** [comment]
wrt current behavior, it is intended and we will not be fixing it.

wrt `median` being defined for `cuda`, it is now defined on `master` and will be present in the next release.

**Comment by fmassa** [comment]
@lijunzh for some background on the decision to implement `median` as is, see https://github.com/torch/torch7/pull/182

**Comment by stiv-yakovenko** [comment]
HI! I've learned how to emulate np.median with torch:

```
import torch
import numpy as np
y =[1, 2, 3, 5, 9, 1]
print("numpy=",np.median(y))
print(sorted([1, 2, 3, 5, 9, 1]))
yt = torch.tensor(y,dtype=torch.float32)
ymax = torch.tensor([yt.max()])
print("torch=",yt.median())
print("torch_fixed=",(torch.cat((yt,ymax)).median()+yt.median())/2.)
```

**Comment by lijunzh** [comment]
@stiv-yakovenko Thanks for the suggestion.

> ymax = torch.tensor([yt.max()])

This line can be simplified as `ymax = yt.max()[None]`.

**Comment by sztal** [comment]
Hi, I know this issue is closed already, but I wonder why PyTorch has to implement median in such a inconsistent way with respect to other standard numerical libraries? I just got hit by this weird behavior and it took me a while to figure out what is going on.

I understand that there are some good reasons for this design decision, but I just wonder what they are?

**Comment by fxmarty** [comment]
It should be stated explicitly in the documentation that torch and numpy median behave differently.

**Comment by AsteroidHunter** [comment]
I feel the name should be changed to something like `find_median_element`. It is confusing that other similar torch functions mirror `numpy` and have the same name, but the median one does not.

**Comment by mjyb16** [comment]
Adding another comment as this issue cropped up in my code and was deceptively difficult to find, as it was for @sztal. I agree with @AsteroidHunter that the naming convention implies a behavior (ported from `numpy`) that is different from the actual behavior, which is fairly unique to PyTorch. While I understand that PyTorch (unlike JAX) historically has not attempted to follow `numpy` conventions, I think it would be beneficial to reduce discrepancies where possible. At a minimum, it would be helpful to provide more of a warning then the current note in the docs,

> The median is not unique for input tensors with an even number of elements. In this case the lower of the two medians is returned. 

which, while formally accurate, neglects to warn the user that this is not the behavior implemented in other common Python numerical packages and breaks the statistical community's convention of taking the mean of the middle two values.
