### ISSUE TITLE
[FR] make torch.nn.utils.convert_sync_batchnorm a classmethod of SyncBatchNorm

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#18382]
The function really goes together with SyncBatchNorm, so I think it makes more sense for them to live together. Users would have easier time finding/discovering it too.

https://github.com/pytorch/pytorch/blob/39669316a6fc31c26f5ef1be5c0a0fe862d661cf/torch/nn/utils/sync_batch_norm.py#L4

cc @jjsjann123

**Comment by SsnL** [comment]
Just want to comment. If we do this, we need to do this before next release.

**Comment by iArunava** [comment]
I want to take this. I took a look at https://github.com/pytorch/pytorch/blob/39669316a6fc31c26f5ef1be5c0a0fe862d661cf/torch/nn/modules/_functions.py#L5

And the `convert_sync_batchnorm` function here

https://github.com/pytorch/pytorch/blob/39669316a6fc31c26f5ef1be5c0a0fe862d661cf/torch/nn/utils/sync_batch_norm.py#L4

What are the things I need to take care about?

Thanks,
P.S. This will be my first contribution in pytorch :) Excited :)

**Comment by fmassa** [comment]
@iArunava it should be pretty much moving `convert_sync_batch_norm` to be a classmethod of `SyncBatchNorm`, as you pointed out. Let me know if you have further questions
