### ISSUE TITLE
pip install torch==1.0.1.post2

### ISSUE THREAD

**Issue by saivikas112** [pytorch/pytorch#18384]
Not able to install latest torch version (torch==1.0.1.post2) using the 
"pip3 install torch==1.0.1.post2" on windows system

following error is shown
Could not find a version that satisfies the requirement torch==1.0.1.post2 (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch==1.0.1.post2

**Comment by peterjc123** [comment]
Sorry, pytorch for Windows is currently available through PYPI. You have to enter the commands in https://pytorch.org.

**Comment by Sowhardhhonnappa** [comment]
This works on windows: conda install pytorch torchvision cudatoolkit=10.0 -c pytorch

**Comment by memogamd21** [comment]
> This works on windows: conda install pytorch torchvision cudatoolkit=10.0 -c pytorch

thank you <3

**Comment by MuMiMaNz** [comment]
you can install previous pytorch version here
https://pytorch.org/get-started/previous-versions/
ex. conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch
