### ISSUE TITLE
Can't find `Python.h` when include `torch/extension.h`

### ISSUE THREAD

**Issue by xianshunw** [pytorch/pytorch#18387]
When I include `torch/extension.h` in my C++ code, my compiler reported the following error,

```
/home/xswang/workspace/FPM_init/libtorch/include/torch/csrc/python_headers.h:9:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
```

My system is Ubuntu 18.04 with gcc 7.3, I don't have cuda.

**Comment by soumith** [comment]
well, you need to have Python.h on your system. Maybe you dont have `libpython-dev` package installed.

**Comment by xianshunw** [comment]
It seems that this is not the reason. I have installed `python3-dev`, `python-dev` also `libpython-dev` and `libpython3.6-dev`. But this problem has never disappeared.

<img width="787" alt="Capture" src="https://user-images.githubusercontent.com/17881166/54874650-847eb480-4e2a-11e9-80d5-8ed3cec65c52.PNG">

**Comment by soumith** [comment]
wait, why do you have a `make`? are you using cmake or python setuptools?

**Comment by xianshunw** [comment]
Yes, I am using cmake. I follow your tutorials [here](https://pytorch.org/tutorials/advanced/cpp_export.html#depending-on-libtorch-and-building-the-application).  Do you mean that I need to add the python package by myself in the `CMakeLists.txt`?

**Comment by xianshunw** [comment]
Hi, I solved this problem by adding the python package in my `CMakeLists.txt`. But I don't think this is what the user should do.

**Comment by soumith** [comment]
@xianshunw you are including torch/extension.h which is for python purposes. The tutorial does not recommend that.

**Comment by xianshunw** [comment]
@soumith I see, thanks

**Comment by andyljones** [comment]
Soumith solved the X->Y problem here, but if anyone else arrives here from Google with the same error, the solution is to get the Python include path from
```python
import sysconfig
sysconfig.get_paths()['include']
```
and add it to your includes.
