### ISSUE TITLE
[jit] be more permissive with bool casting.

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#18381]
In the [TorchScript docs](https://pytorch.org/docs/master/jit.html#torch.jit.ScriptModule) there is an example that doesn't compile:
```
import torch
@torch.jit.script
def foo(x, y):
    if x.max() > y.max():
        r = x
    else:
        r = y
    return r
```
because we require explicit casts from tensor to bool. We should either relax that constraint or update the docs.

Thanks to Stepan Ulyanin (@halahup) for reporting this issue

**Comment by suo** [comment]
@zdevito @eellison do you remember why we made this change? Can we change it back? It is a very common confusion for users.

**Comment by halahup** [comment]
Yeah, that would be good to see the behavior depicted in the docs, I am sure I am not the first one to stumble on this issue

**Comment by apaszke** [comment]
IIRC @zdevito didn't like us inheriting semantics of implicit float->bool casts from Python, but I agree it is somewhat inconvenient the way it is.
