### ISSUE TITLE
anaconda prompt crashes after executing 'conda install pytorch-cpu torchvision-cpu -c pytorch'

### ISSUE THREAD

**Issue by rinauoy** [pytorch/pytorch#18386]
Hello, 

I tried to install pytorch with this command 'conda install pytorch-cpu torchvision-cpu -c pytorch' on anaconda prompt. Sadly, now anaconda prompt just crashes and it keeps crashing every time I open it. 

Anyone experiences the same issue ?

**Comment by ezyang** [comment]
This isn't enough information to debug. Try reinstalling Anaconda and try installing again. If you need more support, please go to the support forums, and also report what operating system you're on, and also what you mean by "anaconda prompt just crashes."

**Comment by rinauoy** [comment]
Sorry for not being clear. 

1- I installed python 3.6 from Anaconda suite - Anaconda3-5.2.0-Windows-x86_64.exe. Everything including anaconda prompt works well.

2- Then, I install pytorch by following the instruction on Pytorch website - 'conda install pytorch-cpu torchvision-cpu -c pytorch'

3- After installing pytorch, now anaconda prompt does not work anymore. It closes immediately after I open it. 

![anaconda prompt](https://user-images.githubusercontent.com/9147160/55045825-dd8c5980-5071-11e9-90c3-9bc87fb586b2.JPG)
