### ISSUE TITLE
update from source

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#18388]
## 📚 Documentation

Would it be possible to expand the build from source instructions:
https://github.com/pytorch/pytorch#from-source
to also include 'update' from source instructions for those who already have the source checked out and built it?

Until now I wasn't successful at rebuilding pytorch after git update, and had to repeat the whole wipe out, git clone, build from scratch cycle which takes really long time. Surely, there must be a faster way to update the build from source w/o starting from scratch every time. 

Any other tips that you may have that can speed up the rebuild process are welcome.

Thank you.

**Comment by SsnL** [comment]
Usually this works for me:
```sh
git pull --rebase upstream master  # assuming upstream is the official repo
git submodule sync --recursive
git submodule update --init --recursive
pip uninstall -y torch; pip uninstall -y torch  # **only if** you are doing setup.py install
python setup.py install  # or build
```

If the last step fails, do `python setup.py clean`, then try again.

**Comment by stas00** [comment]
Ah, that explains why it was failing for me, I didn't know I had to do all those steps. 

Would it be possible to add this to the official docs, please? Perhaps an update section under 'Installing from Source'?

Thank you, @SsnL!

Thank you!

**Comment by soumith** [comment]
@stas00 sent a PR here: https://github.com/pytorch/pytorch/pull/18409

**Comment by stas00** [comment]
OK, I got to try @SsnL suggestion and 

1. the first line of the instructions didn't work:

```
git pull --rebase upstream master  # assuming upstream is the official repo
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The repo was created originally with `git clone --recursive https://github.com/pytorch/pytorch` as per your instructions.

This worked:

`git pull --rebase`

2. But also it didn't help with saving any of the prebuilt-stuff, it's now rebuilding everything from scratch.

If only a few files changed since the last build, is there a way to not need rebuild everything? 

Is there a way to work directly with `make`?

Thanks.

**Comment by SsnL** [comment]
1. your remote repo is note labelled as `upstream`, hence the error. since you directly `git clone`'d, just `git pull --rebase` would be fine.

2. depends on how many files changed. and it will be faster if you use `ninja` and `ccache` as per the instructions at https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#use-ccache

**Comment by stas00** [comment]
>     1. your remote repo is note labelled as `upstream`, hence the error. since you directly `git clone`'d, just `git pull --rebase` would be fine.

Yes, please remember we are improving/expanding instructions on how to build from source and update from source. So they should match, by either setting the `upstream` in the initial clone instructions or not using it in the update.

>     2. depends on how many files changed. and it will be faster if you use `ninja` and `ccache` as per the instructions at https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#use-ccache

Fantastic! Thank you! If it's OK perhaps adding a link to this in the build from source instructions?
