### ISSUE TITLE
Using 'with torch.cuda.device' but tensor is created in cpu

### ISSUE THREAD

**Issue by kintaat** [pytorch/pytorch#18399]
## 🐛 Bug

I create a tensor inside `with torch.cuda.device`, but device of the tensor is cpu.

## To Reproduce
```
>>> import torch
>>> with torch.cuda.device(torch.device('cuda', 0)):
...     a = torch.zeros(10, 1)
...     b = torch.zeros(10, 1, device=torch.cuda.current_device())
...     torch.cuda.current_device()
...     a.device
...     b.device
... 
0
device(type='cpu')
device(type='cuda', index=0)
>>> 
```

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB

Nvidia driver version: 384.145
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.2.1

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] torch==1.0.1.post2
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl_fft                   1.0.10           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.0.1           py3.6_cuda9.0.176_cudnn7.4.2_2    pytorch
[conda] torchvision               0.2.2                      py_3    pytorch

**Comment by SsnL** [comment]
This is expected. These are sort of legacy APIs. They only change the default cuda device, which means that it creates on that specified device only if you ask for a cuda tensor. See the documentations.
