### ISSUE TITLE
Regarding porting of functions in ATen directory

### ISSUE THREAD

**Issue by ekagra-ranjan** [pytorch/pytorch#18403]
In reference to #14714 and #18065, can someone clarify my doubts regarding the porting of functions from THNN to native as the functions currently seem to be distributed unevenly across the ATen directory (Adaptive Average pooling is available [here](https://github.com/pytorch/pytorch/tree/master/aten/src/ATen/native) whereas Average Pooling is available [here](https://github.com/pytorch/pytorch/tree/master/aten/src/THNN/generic)).

1) Since Spatial Adaptive Average Pooling is being ported, shouldn't Spatial Adaptive Max Pooling also be ported? 

2) And is it the case that most of the functions from [THNN](https://github.com/pytorch/pytorch/tree/master/aten/src/THNN/generic) should be ported as they are also a neural network functions?

**Comment by soumith** [comment]
about (1), the answer is yes.

about (2), only if they are actually referred to from the frontend (there might be dead code)

**Comment by ekagra-ranjan** [comment]
@soumith I did not get what is meant by frontend in pytorch framework.

**Comment by soumith** [comment]
some backend code is simply not used by any function in python. it's old code from a while ago.

**Comment by ekagra-ranjan** [comment]
Thanks for the clarification!
