### ISSUE TITLE
Unable to locate SpatialAdaptiveAveragePooling.c

### ISSUE THREAD

**Issue by ekagra-ranjan** [pytorch/pytorch#18401]
I am looking for SpatialAdaptiveAveragePooling.c. I found it on this [branch](https://github.com/pytorch/pytorch/tree/949559552004db317bc5ca53d67f2c62a54383f5/aten/src/THNN/generic) but failed to find the same in the [master](https://github.com/pytorch/pytorch/tree/master/aten/src/THNN/generic). Can someone help me with this?

**Comment by vishwakftw** [comment]
SpatialAdaptiveAveragePooling was removed in [this commit](https://github.com/pytorch/pytorch/commit/64b336420918d31ee3da623bbcb7afadc73edb6d).

Please close the issue if you think it is resolved.

**Comment by ekagra-ranjan** [comment]
Thanks a lot!
