### ISSUE TITLE
_unique_dim does not support zero size tensor

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#18408]
Unique without dim works well
```python
>>> a = torch.empty(5, 0)

>>> a
tensor([], size=(5, 0))

>>> a.unique(return_inverse=True)
(tensor([]), tensor([], size=(5, 0), dtype=torch.int64))
```

But unique with dim does not work
```python
>>> a.unique(dim=1, return_inverse=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gaoxiang/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 351, in unique
    dim=dim
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1]

>>> a.unique(dim=0, return_inverse=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gaoxiang/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 351, in unique
    dim=dim
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0]
```

I suggest changing the behavior to:
if `dim` refers to a dimension with size 0, and other dimensions have size > 0, then the output and reverse_indicies should be the same empty tensor as input. If `dim` refers to a dimension with size > 0, or there are other 0 sized dimensions, then reject the input with an error because whether "nothing == nothing" is not defined.

**Comment by codexetreme** [comment]
Can I take this up? I want to try fix it...

**Comment by zasdfgbnm** [comment]
@codexetreme I have no problem with it.

**Comment by codexetreme** [comment]
cool, Ill try to fix it.

**Comment by codexetreme** [comment]
Ok, so I new to this and this is my first time trying to do this and I need some help doing this.
So far I have seen that the function `_unique_dim` is a part of the torch package and that it is defined in `pytorch/aten/src/ATen/native/Unique.cpp` is it here I have to add the functionality to handle the zero size tensor?

**Comment by zasdfgbnm** [comment]
@codexetreme Yes, exactly

**Comment by zasdfgbnm** [comment]
@codexetreme Also https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/Unique.cu

**Comment by codexetreme** [comment]
Ok, so I have thought of something like this:
![Screenshot from 2019-03-25 23-26-54](https://user-images.githubusercontent.com/8681139/54942661-9446e780-4f55-11e9-9995-3704230a7fa1.png)

Here I have 2 questions, 
1. how do I get the size of the `self` tensor? 
2. for `output` and `inverse_indices`, I want to make a zero tensor of shape `[1]`.

PS: I will fix the `.cu` file as well, just need to check if this works on the CPU version first.

**Comment by zasdfgbnm** [comment]
@codexetreme 
1. use `self.dim()` to get the number of dimensions, and use `self.size(i)` to get the size at dimension i
2. I don't think the way you write it works. You want a n-dimensional 0-sized tensor, not just a size 1 tensor containing an element 0.

**Comment by codexetreme** [comment]
I think I get it now, and yes you are right, I need an N-dimensional tensor. I will make the changes accordingly.

**Comment by codexetreme** [comment]
Ok, so far I have come up with this. 
Here my doubt is, I am sure this code is ugly and can be made more efficient and "nicer".
and is this what is wanted?
![Screenshot from 2019-03-26 19-10-48](https://user-images.githubusercontent.com/8681139/55001788-5d2b1180-4ffb-11e9-93a0-fe1ef79bf52d.

**Comment by zasdfgbnm** [comment]
@codexetreme Sorry for not replying you in time. I am refactoring `unique` implementations recently, so the code might change recently. There might be some conflicts. For your work:
1. Why `well_formed_tensor` is true if other dimensions are 0? Shouldn't it be false?
2. `inverse_indices` could not be self, but a LongTensor with the same shape.

**Comment by zasdfgbnm** [comment]
Also, @codexetreme, usually discussions in that detail don't happens inside issue. Could you please submit a pull request first, put your code there, and cc me, and let's discuss there. Also, I am not a Facebook person, so you still need someone inside Facebook to review your code.

**Comment by codexetreme** [comment]
Alright, I will do that.
