### ISSUE TITLE
pytorch's gpu memory usage is ceaselessly grow up

### ISSUE THREAD

**Issue by lawlietAi** [pytorch/pytorch#1840]
i have got the pytorch tutorial code on [http://pytorch.org/tutorials/beginner/nlp/advanced_tutorial.html](url)
and i try to switch it to a **GPU version** but when i run this code, the memory grows unlimitly **until OOM**
the text at the last line is **my gpu version code**
i'm new for pytorch, plz give me some advise,thx all of you
[cuda_bilstmcrf.txt](https://github.com/pytorch/pytorch/files/1083988/cuda_bilstmcrf.txt)

**Comment by rosinality** [comment]
I suspect it occurred at this: sum_log_likelihood += neg_log_likelihood. What about try sum_log_likelihood += neg_log_likelihood.data instead?

**Comment by soumith** [comment]
yes, what @rosinality said is correct. 

```
sum_log_likelihood += neg_log_likelihood
```
This will keep the graph of all previous timesteps forever...
