### ISSUE TITLE
TorchConfig tries to find Caffe2 Config even if it is not written

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#18419]
## 🐛 Bug

Caffe2 Config is only written when using shared libraries as below:
https://github.com/pytorch/pytorch/blob/0fe6e8c8703bc69b8795ba7373dcd5c51812a513/CMakeLists.txt#L437-L479

However, there is no such condition on TorchConfig, so regardless of whether shared libraries is on or not, it attempts find_package(Caffe2):
https://github.com/pytorch/pytorch/blob/master/cmake/TorchConfig.cmake.in#L38-L39

## To Reproduce

1. Build LibTorch with Caffe2 statically
2. Try to use find_package(Torch CONFIG)

## Expected behavior

Find package should work.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake -DBUILD_SHARED_LIBS=OFF
 - Python version: 3.7.2
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Titan V
 - Any other relevant information:

## Additional context

In my limited testing, when using the static build, it appears finding the Caffe2 Config is not required. This is likely due to the note in CMakeLists about how it becomes an interface library and everything is already linked to torch.
With the following modification, everything appeared to work.
https://github.com/xsacha/pytorch/commit/b952e7fe5087be7b16bab47c664b09f3914383c8

**Comment by Omegastick** [comment]
I can confirm this on Ubuntu 16.04.
