### ISSUE TITLE
Padding size should be less than the corresponding input dimension

### ISSUE THREAD

**Issue by abnera** [pytorch/pytorch#18413]
## 🐛 Bug

Reflective padding throws a runtime error when padding is bigger than one of the input sizes. RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (46, 46) at dimension 3 of input [1, 3, 128, 36]

## To Reproduce

1. Use reflection pad 2D with an image that is 3x width than height

`RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (46, 46) at dimension 3 of input [1, 3, 128, 36]`

## Expected behavior

The expected behavior should be a warning to let the user decide if they still want to use this padding mode for images. 

## Environment
Any environment should replicate this bug.

**Comment by SsnL** [comment]
> The expected behavior should be a warning to let the user decide if they still want to use this padding mode for images.

Hmm, really? There is no proper output in this case, and you don't expect an error?

**Comment by abnera** [comment]
I apologize, I guess then it should be on feature request? I'm using fastai as a pytorch wrapper and I'm able to properly see the image batch with the reflect padding but it later crashes when training with the pytorch reflection pad C implementation error. Ideally, it should force the reflection pad and return a warning.

**Comment by fmassa** [comment]
@abnera what behavior would you expect for reflection padding in this case? I don't see any reasonable default that wouldn't be unexpected.

**Comment by abnera** [comment]
Never mind I myself was not understanding the problem well enough. For me, I'm just trying to pad images where I have a 4x1 width to height ratio. With reflection pad that will basically mean reflecting the entire image several. Although this may be crazy from for normal images for the CNN it may or may not be a bad thing. Basically, I can try and square the image but I lose aspect ration and shape of the object/image. I can pad all of them with zeros but the I have I huge amount of padding that I'm passing to the CNN. I guess I just wanted to do reflection pad of the image even if it doesn't make sense.

For the case of a 4x1 relationship. It will first reflect the entire image up and down to have a 3x1 size ratio and then reflect that result to get to the 4x1. Hope this makes sense. It's just something to try probably destroying aspect ratio might still be better for the CNN.

**Comment by fmassa** [comment]
I don't know, I'm not really convinced by this argument.

Your CNN model probably doesn't have the right format / you should upsample your image to a minimum size (while keeping the aspect ratio), and then you'll be fine I believe.

I'm closing this issue, but let me know if you disagree

**Comment by abnera** [comment]
@fmassa Yeah is better to close it. However, what I'm trying to say is that the aspect ration itself will be 4x1 so the image will be (1024, 256) or (224, 56). I just want to pad it so that in the (224, 56) aspect ratio it will be converted into a (224, 224). I can easily do this with pad zeros. But can't with reflection pad cuz even when reflecting the entire image in both direction it will not reach 224. that's why the error. So maybe the method should try to reflect the entire image which will make it (224, 168). Obviously here it crashes cuz even if you have the reflected image in both direction is not enough. Hence the error. However, what if I use the already reflected (224, 168) and reflect that one into (224,224). I know it's going to be one weird looking image, but might be more useful that loosing aspect ration.

I'm trying to classify cars and squishing a super long truck makes it lose it's meaning. a weird looking image of the truck reflected many times my be more useful to the CNN. Emphasis on might.

**Comment by fmassa** [comment]
> a weird looking image of the truck reflected many times my be more useful to the CNN

I'd recommend zero padding first. You are introducing quite some artefacts by reflection padding the image with such a factor

**Comment by abnera** [comment]
Yeah, I already tried zero pad and it's terrible mainly because is too many zeros. Right now squish is my only option but wanted to give padding reflect a try. I understand that I'm introducing some artifacts for my type of problem that might actually be a good thing since I have both global and local features.

**Comment by fred-xue** [comment]
@vishwakftw @SsnL There seems inconsistent behavior between PIL image vs Tensor. PIL image lead to np.pad, apparently handles this situation by repeating the padding, should this be the behavior when input is a Tensor?

**Comment by kserhii** [comment]
Here is my workaround solution for this limitation

```python
def torch_pad_reflect(image: torch.Tensor, paddings: Sequence[int]) -> torch.Tensor:
    paddings = np.array(paddings, dtype=int)

    assert np.all(np.array(image.shape[-2:]) > 1),  "Image shape should be more than 1 pixel"
    assert np.all(paddings >= 0), "Negative paddings not supported"

    while np.any(paddings):
        image_limits = np.repeat(image.shape[::-1][:len(paddings)//2], 2) - 1
        possible_paddings = np.minimum(paddings, image_limits)

        image = torch.nn.functional.pad(image, tuple(possible_paddings), mode='reflect')

        paddings = paddings - possible_paddings

    return image
   ```

**Comment by RSKothari** [comment]
I agree with @fred-xue , this should indeed be a bug. MATLAB pad array handles `symmetric` or `reflect` by repeating the padding if the padding amount exceeds. 

```
im = rand(100, 200, 3);
padFactor = 4;
paddedIm = padarray(im, round(size(im) * padFactor), 'symmetric');
```
