### ISSUE TITLE
TorchConfig does not add c10 to TORCH_LIBRARIES

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#18416]
## 🐛 Bug

When using find_package(Torch CONFIG) and attempting to use the resulting TORCH_LIBRARIES, I find that c10 is not linked in.

The result is my programs will complain about undefined references to all c10 symbols (such as c10::Error, which is thrown from torch::jit::load in libtorch).

## To Reproduce

1. Create sample app that loads a model in libtorch
2. Have the CMakeLists find_package(Torch CONFIG) and link the app to TORCH_LIBRARIES
3. When compiling, notice undefined references

Code:
```C++
#include <torch/script.h>
int main() {
    std::shared_ptr<torch::jit::script::Module> model = torch::jit::load(model_path);
}
```

```CMake
add_executable(test main.cpp)
find_package(Torch CONFIG REQUIRED)
target_link_libraries(test ${TORCH_LIBRARIES})
```

## Expected behavior

Links to what is required

## Environment

 - PyTorch Version (e.g., 1.0): master / nightly
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): Tried from source and libtorch from website
 - Build command you used (if compiling from source):
 - Python version: 3.7.2
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: GTX 1060

## Additional context

Workaround of:
```CMake
set(TORCH_LIBRARIES ${TORCH_LIBRARIES} "${TORCH_ROOT}/lib/c10.lib" "${TORCH_ROOT}/lib/c10_cuda.lib")
```
makes everything work.

**Comment by Omegastick** [comment]
it's worth noting that the examples work fine without explicitly linking c10 on Linux. Maybe it's a Windows thing.

**Comment by xsacha** [comment]
Yes, everything worked fine on Linux.  I only had this issue on Windows.
It may be that it was built static on Linux but I didn't investigate.

**Comment by fmassa** [comment]
@peterjc123 could you have a look?

**Comment by peterjc123** [comment]
@xsacha Could you please try if things still work after removing `c10.a`? If yes, then all the functions of `c10` go into `torch`, which is unexpected for static builds.

**Comment by xsacha** [comment]
Removing c10.a should be fine.
libtorch is still built shared unless you choose TORCH_STATIC. So in my configuration, with BUILD_SHARED_LIBS=OFF I have a libtorch.so that statically linked c10.a.
All the symbols are now in libtorch.so, so it doesn't require linking.

**Comment by peterjc123** [comment]
I see. Then the different behaviour is brought by the different flags.
