### ISSUE TITLE
Inconsistent tensor size while loading data using data loader from torch.utils.data .

### ISSUE THREAD

**Issue by Deepayan137** [pytorch/pytorch#1841]
I am training an OCR using RNN. I am supplying input data as word images of varying dimensions (since each word can be of different lengths) and the size of class labels of each input data is also not consistent. Since each word can have a different number of characters.

```python
   tensor_word_dataset = WordImagesDataset(images, truths, transform = ToTensor())
   dataset_loader = torch.utils.data.DataLoader(tensor_word_dataset,
                                            batch_size=16, shuffle=True,) 
```

This gives me the error:
`RuntimeError: inconsistent tensor size at /py/conda-bld/pytorch_1493673470840/work/torch/lib/TH/generic/THTensorCopy.c:46
`

The image sizes of first 5 input labels and images respectively  are:
```
 torch.Size([2]) torch.Size([32, 41])
 torch.Size([7]) torch.Size([32, 95])
 torch.Size([2]) torch.Size([32, 38])
 torch.Size([2]) torch.Size([32, 53])
 torch.Size([2]) torch.Size([32, 49])
 torch.Size([6]) torch.Size([32, 55])
 ```

Any suggestions as to how should I fix it. I want to shuffle the data and send it in batches instead of supplying them one at a time.

**Comment by soumith** [comment]
discuss.pytorch.org
