### ISSUE TITLE
I'd like to see how 'backward()' code looked like 

### ISSUE THREAD

**Issue by mandal4** [pytorch/pytorch#18428]
Hi i am newbie for Pytorch and i am looking for the structure of 'backward()' code in backend scope. But i couldn't find any way to see it or any documents about it.
Is there anyone who have searched about it or known something else? :)

**Comment by albanD** [comment]
Hi,

Please use the [forum](https://discuss.pytorch.org/) for questions. We use github issues only for bugs and feature requests.
