### ISSUE TITLE
bucket select for topk

### ISSUE THREAD

**Issue by khaotik** [pytorch/pytorch#1843]
I'm reading [this paper](http://www.math.grin.edu/~blanchaj/Research/ABGS_KSelection.pdf). It appears the proposed *bucket selection* algorithm offers better performance than *radix selection*. Is there a reason radix selection is still being used in `torch.topk`?

**Comment by soumith** [comment]
1. topk selects not just from a vector, but also a dimension from a Tensor
2. we likely picked one and implemented it. Implement high perf GPU sorting / topk from scratch takes quite a bit of time/effort.
