### ISSUE TITLE
the default of torch.max keepdim is False, which is  inconsistent with the document

### ISSUE THREAD

**Issue by xwgeng** [pytorch/pytorch#1845]
According to the doc [torch.max](http://pytorch.org/docs/torch.html#torch.max), the default of `keepdim` is `True`, but actually setted to `False` .  Maybe the issue occurs due to [this line](https://github.com/pytorch/pytorch/blob/master/torch/autograd/_functions/reduce.py#L136)
```

In [2]: x = torch.ones(1,2)

In [3]: x
Out[3]: 

 1  1
[torch.FloatTensor of size 1x2]

In [4]: x.max(1)
Out[4]: 
(
  1
 [torch.FloatTensor of size 1], 
  0
 [torch.LongTensor of size 1])

In [5]: x.min(1)
Out[5]: 
(
  1
 [torch.FloatTensor of size 1], 
  0
 [torch.LongTensor of size 1])
```

**Comment by soumith** [comment]
this is a documentation inconsistency of master vs v0.1.2
I'm generating separate docs per version, so hopefully this confusion should be ended soon.

**Comment by xwgeng** [comment]
Thanks for your reply
