### ISSUE TITLE
[MSVC Warning] Inconsistent DLL linkage

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#18461]
## Bug

Get the following warning on VS2017 when using Caffe2 in our application.
Caffe2 is built as DLL.

```
c10\core\tensortypeid.h(38): warning C4273: 'c10::toString': inconsistent dll linkage
c10\core\tensortypeid.h(35): note: see previous definition of 'toString'
```

https://github.com/pytorch/pytorch/blob/e1c272797b1078220b3333386450096062acd27f/c10/core/TensorTypeId.h#L35-L38

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Win10
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake + ninja
 - Python version: 3.7

**Comment by peterjc123** [comment]
Let me fix it.
