### ISSUE TITLE
The latest version of onnx-caffe2 does not support  “pow” ？

### ISSUE THREAD

**Issue by qjchen1972** [pytorch/pytorch#18475]
I converted the pytorh model into onnx, which seems to be all right. But when I converted this onnx model to caffe2 model, it showed the following error:

/root/anaconda2/lib/python2.7/site-packages/caffe2/python/onnx/backend.py:695: UserWarning: This version of onnx-caffe2 targets ONNX operator set version 9, but the model we are trying to import uses version 10.  We will try to import it anyway, but if the model uses operators which had BC-breaking changes in the intervening versions, import will fail.
  warnings.warn("This version of onnx-caffe2 targets ONNX operator set version {}, but the model we are trying to import uses version {}.  We will try to import it anyway, but if the model uses operators which had BC-breaking changes in the intervening versions, import will fail.".format(cls._known_opset_version, imp.version))
No handlers could be found for logger "caffe2.python.workspace"
Traceback (most recent call last):
  File "createnet.py", line 25, in <module>
    outputs = rep.run(np.random.randn(1, 3, 320, 320).astype(np.float32))
  File "/root/anaconda2/lib/python2.7/site-packages/caffe2/python/onnx/backend_rep.py", line 57, in run
    self.workspace.RunNet(self.predict_net.name)
  File "/root/anaconda2/lib/python2.7/site-packages/caffe2/python/onnx/workspace.py", line 63, in f
    return getattr(workspace, attr)(*args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 237, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/root/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 198, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pow_op.h:100] A.sizes() == B.sizes(). [1, 512, 40, 40] vs []. Dimension mismatch - did you forget to set broadcast=1?
Error from operator: 
input: "94" input: "95" output: "96" name: "" type: "Pow" device_option { device_type: 0 device_id: 0 }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x78 (0x7fb2e60bc2d8 in /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: <unknown function> + 0x1b9952c (0x7fb2e830252c in /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #2: <unknown function> + 0x15cef85 (0x7fb2e7d37f85 in /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #3: caffe2::SimpleNet::Run() + 0x181 (0x7fb2e7e07591 in /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #4: caffe2::Workspace::RunNet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x4d (0x7fb2e7e5049d in /root/anaconda2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #5: <unknown function> + 0x45da7 (0x7fb2e9c22da7 in /root/anaconda2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
frame #6: <unknown function> + 0x9071e (0x7fb2e9c6d71e in /root/anaconda2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
<omitting python frames>
frame #24: __libc_start_main + 0xe7 (0x7fb2f93b6b97 in /lib/x86_64-linux-gnu/libc.so.6)

---------------------------------------------------------------
Some details： 

1. ubuntu 18.04
2. the latest version of pytorch

3. the mode is：
class L2Norm(nn.Module):
    def __init__(self,n_channels, scale):
        super(L2Norm,self).__init__()
        self.n_channels = n_channels
        self.gamma = scale or None
        self.eps = 1e-10
        self.weight = nn.Parameter(torch.Tensor(self.n_channels))
        self.reset_parameters()

    def reset_parameters(self):
        init.constant_(self.weight,self.gamma)

    def forward(self, x):
        norm = x.pow(2).sum(dim=1, keepdim=True).sqrt()+self.eps
        #x /= norm
        x = torch.div(x,norm)
        out = self.weight.unsqueeze(0).unsqueeze(2).unsqueeze(3).expand_as(x) * x
        return out

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by maeotaku** [comment]
@qjchen1972 did you find a fix or the cause to this?

**Comment by beekbin** [comment]
A workaround is to use  `x * x ` instead of `x.pow(2)`.

**Comment by shreydesai** [comment]
I'm also having this issue

**Comment by jotline** [comment]
In my case, use onnxruntime instead of onnx-caffe2 solved this error.

**Comment by raviv** [comment]
@qjchen1972 Did you find a solution to convert your L2Norm to be onnx-compatible?

**Comment by qjchen1972** [comment]
> @qjchen1972 Did you find a solution to convert your L2Norm to be onnx-compatible?

yes，it use x * x instead of x.pow(2).  Iconverted this onnx model to caffe2 model

**Comment by vshampor** [comment]
This is still an issue. In particular, Caffe2 is now unable to run the ubiquitous BERT architecture as exported from PyTorch since it uses `torch.nn.LayerNorm`, which in turn is exported into ONNX as a sequence of operations involving an ONNX "Pow" operation:
https://github.com/pytorch/pytorch/blob/36d17f4105f48d264fe085ce3dc0e4e825ebfb42/torch/onnx/symbolic_opset9.py#L1038 
If I change the symbolic op to using `mul` instead of `pow`, I am then stuck with https://github.com/onnx/onnx/issues/2417 while exporting ONNX to caffe2 format.

Pinging contributors - an operation as simple as `Pow` should definitely be functional at all times. 
@ezyang @zou3519 @gchanan

**Comment by zou3519** [comment]
I don't know much about onnx-caffe2. Maybe @bddppq or @houseroad can help or rope in the right people?

**Comment by rameshjesswani** [comment]
I am also facing same issue, any update on this ? Thanks.

**Comment by caojiangxia** [comment]
I am also face the problem when export BERT and run it onnx-caffe2.
