### ISSUE TITLE
CUDA threadidx error from ATen (IndexKernel.cu:53)

### ISSUE THREAD

**Issue by sonsus** [pytorch/pytorch#18472]
## ❓ device-side assert from cuda which so far I cannot find any working solution

I asked to the community about this issue and got a short advice about advanced indexing and asynchronous mode of CUDA operations which I cannot follow up just with it. Please help me to dive into it :sob: I have no knowledge about cuda kernels nor GPU programming 

- [CUDA threadidx error from ATen (IndexKernel.cu:53)](https://discuss.pytorch.org/t/cuda-threadidx-error-from-aten-indexkernel-cu-53/40842)

I tried
- reading cuda semantics
- whole day googling with ATen, and IndexKernel.cu:53 
- removing ./nv folder and reset
- dealing with Tensor types (would byte tensor can cause this problem?) 
- declaring chosen_es Tensor first with the same size needed, adding parentheses to each operations, applying torch.cuda.synchronize() 

```python
## of course all of those are on GPU. **cuda Tensors**
# b_e_idx, b_r_idx, # each 64 long tensor, each has 0~9, 0~2 index   
# h_t:   64 1 256 long tensor , 
# es:   64 10 256 float Tensor
# self.eye = torch.eye(10).long() 
mask1 = (b_r_idx==1) # 64
chosen_stack = es*(mask1.unsqueeze(1).float()) # 64 256
update_loc = (self.eye[b_e_idx].clone().detach().unsqueeze(2)).repeat(1,1, 256)
chosen_es = ((chosen_stack.unsqueeze(1)).repeat(1,10,1)) * (update_loc.float())
```
## The last line throws **device side assert** with detailed stacktrace as follows:

> ::operator()(int)->auto: block: [0,0,0], thread: [4,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1549628766161/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [0,0,0], thread: [5,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1549628766161/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [0,0,0], thread: [6,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1549628766161/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [0,0,0], thread: [7,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
…

## Im using
> CUDA V9.1.85 | Driver Version: 390.116 | ubuntu 1804 | pytorch 1.0.1 (conda) | python 3.6.7

**Comment by SsnL** [comment]
your index is out of bound

**Comment by sonsus** [comment]
I mean, literally it is saying that index is out of bound. But it supposed not to be since the tensors in the last line have the same shape: (64 10 256) * (64 10 256). Is doing this kind of operation problematic? (I dont think it is)

**Comment by sonsus** [comment]
Sorry I think I found what was the problem. It's not about the shape but about the indices used for the self.eye (invalid values were being passed) Thank you so much!
