### ISSUE TITLE
ImportError: cannot import name '_update_worker_pids'

### ISSUE THREAD

**Issue by NhanTran96** [pytorch/pytorch#18484]
## ImportError: cannot import name '_update_worker_pids'

I tried to import with no success. The code I used is:
`from torch._C import _update_worker_pids`

and the error came out:

> ImportError: cannot import name '_update_worker_pids'

## Environment

> PyTorch version: 1.1.0a0+5860fa5
> Is debug build: No
> CUDA used to build PyTorch: 10.0.130
> 
> OS: Ubuntu 18.04.2 LTS
> GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
> CMake version: version 3.12.2
> 
> Python version: 3.5
> Is CUDA available: Yes
> CUDA runtime version: 10.0.130
> GPU models and configuration: GPU 0: Quadro K1100M
> Nvidia driver version: 410.104
> cuDNN version: /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7
> 
> Versions of relevant libraries:
> [pip] numpy==1.14.3
> [pip] torch==1.1.0a0+5860fa5
> [pip] torchvision==0.2.3
> [conda] mkl                       2019.1                      144    anaconda
> [conda] mkl-include               2019.1                      144    anaconda
> [conda] mkl_fft                   1.0.1            py35h3010b51_0  
> [conda] mkl_random                1.0.1            py35h629b387_0  
> [conda] numpy                     1.14.2          py35_nomklh2b20989_1  
> [conda] scipy                     1.1.0           py35_nomklh9d22d0a_0  
> [conda] torch                     1.1.0a0+5860fa5           <pip>

How I can solve it? Thanks.

**Comment by SsnL** [comment]
you likely have a previous install of pytorch that you did not remove.

**Comment by NhanTran96** [comment]
> you likely have a previous install of pytorch that you did not remove.

I built PyTorch from source in conda environment. What do you think I should do right now? Or what is your suggestion? Thanks.

**Comment by NhanTran96** [comment]
I also did [this](https://github.com/pytorch/pytorch/issues/16930#issuecomment-462155099) but problem still exists.

**Comment by soumith** [comment]
@NhanTran96 

```
conda uninstall -y pytorch
pip uninstall -y torch
pip uninstall -y torch
pip uninstall -y torch
```

and then redo the source install.
If still no luck, it seems some files might have been still lingering (maybe from torch_nightly package?), so just nuke your anaconda env

**Comment by NhanTran96** [comment]
> @NhanTran96
> 
> ```
> conda uninstall -y pytorch
> pip uninstall -y torch
> pip uninstall -y torch
> pip uninstall -y torch
> ```
> 
> and then redo the source install.
> If still no luck, it seems some files might have been still lingering (maybe from torch_nightly package?), so just nuke your anaconda env

I found that the problem occurred with **PyTorch 1.1** as referred in [this answer](https://github.com/CSAILVision/semantic-segmentation-pytorch/issues/157#issuecomment-477029931).

I deleted the conda environment and created a new one. Then I built **PyTorch v1.0.0** from source again and it works now. Thank you for your help.

**Comment by yzlyty** [comment]
pip install torch==1.0.1 torchvision==0.2.2

**Comment by Anirudh257** [comment]
This error occurs only for torch==1.1 and gets removed in torch==1.2 as well.

**Comment by chidosky4ril** [comment]
I still get error via colab despite trying all suggestions on this site. 

Code: 
#RIDNET
CUDA_VISIBLE_DEVICES=0 
!python main.py --data_test MyImage --noise_g 1 --model RIDNET --n_feats 64 --pre_train ../experiment/ridnet.pt --test_only --save_results --save 'RIDNET_RNI15' --testpath ../LR/LRBI/ --testset RNI15

Error message:
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import data
  File "/content/drive/MyDrive/RIDNet/TestCode/code/data/__init__.py", line 3, in <module>
    from dataloader import MSDataLoader
  File "/content/drive/MyDrive/RIDNet/TestCode/code/dataloader.py", line 10, in <module>
    from torch._C import _set_worker_signal_handlers, _update_worker_pids, \
ImportError: cannot import name '_update_worker_pids' from 'torch._C' (/usr/local/lib/python3.7/dist-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so)

**Comment by chidosky4ril** [comment]
> I still get error via colab despite trying all suggestions on this site.
> 
> Code: #RIDNET CUDA_VISIBLE_DEVICES=0 !python main.py --data_test MyImage --noise_g 1 --model RIDNET --n_feats 64 --pre_train ../experiment/ridnet.pt --test_only --save_results --save 'RIDNET_RNI15' --testpath ../LR/LRBI/ --testset RNI15
> 
> Error message: Traceback (most recent call last): File "main.py", line 3, in import data File "/content/drive/MyDrive/RIDNet/TestCode/code/data/**init**.py", line 3, in from dataloader import MSDataLoader File "/content/drive/MyDrive/RIDNet/TestCode/code/dataloader.py", line 10, in from torch._C import _set_worker_signal_handlers, _update_worker_pids, ImportError: cannot import name '_update_worker_pids' from 'torch._C' (/usr/local/lib/python3.7/dist-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so)

I still get error via colab despite trying all suggestions on this site.

Code:
#RIDNET
CUDA_VISIBLE_DEVICES=0
!python main.py --data_test MyImage --noise_g 1 --model RIDNET --n_feats 64 --pre_train ../experiment/ridnet.pt --test_only --save_results --save 'RIDNET_RNI15' --testpath ../LR/LRBI/ --testset RNI15

Error message:
Traceback (most recent call last):
File "main.py", line 3, in
import data
File "/content/drive/MyDrive/RIDNet/TestCode/code/data/init.py", line 3, in
from dataloader import MSDataLoader
File "/content/drive/MyDrive/RIDNet/TestCode/code/dataloader.py", line 10, in
from torch._C import _set_worker_signal_handlers, _update_worker_pids,
ImportError: cannot import name '_update_worker_pids' from 'torch._C' (/usr/local/lib/python3.7/dist-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so)
