### ISSUE TITLE
[JIT] JIT is unable to reason about kernels that mutate tensors

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#18490]
## 🐛 Bug

**Note: This problem only happens in JIT, If I run with `PYTORCH_JIT=0`, the problem disappears**

I have a CUDA kernel that uses the input tensor and writes it to an output tensor.

But the output tensor is empty, until I do something with the return

```
torch::Tensor mutate_kernel(torch::Tensor in, torch::Tensor out)
{
   // cuda kernel that mutates the out....
   return out
}
```

```
    @torch.jit.script
    def forward(self, inputs):
        # type: ([List[Tensor]) -> Tensor
        B = len(lidars)

        out = torch.zeros((B, d1, d2, d3),
                          dtype=torch.float,
                          device=torch.device("cuda"))

        for i in range(B):
            returned_out = torch.ops.mutation.mutate_kernel(
                inputs[i],
                out[i],
            )
            print "Out", int(out.sum())

        return out
```

If I don't use the `returned_out`, `out` will remain to be empty. In the above code snippet, the `returned_out` remains unused

```
Out 0
```

BUT, If I do something with the `returned_out`, the original `out` will suddenly have data too

```
            print "Out", int(out.sum()), int(returned_out.sum())
```
```
Out 189757 189757
```

## PyTorch Version
1.1.0a0+84fe206

**Comment by eellison** [comment]
Thanks for raising this issue! @Krovatkin mind taking a look ?

**Comment by Krovatkin** [comment]
Okay

**Comment by suo** [comment]
This is because the custom op stuff creates a schema without proper aliasing/mutation annotations. I'll fix it.

**Comment by suo** [comment]
@sidazhang I've fixed the problem; let me know if you are still seeing issues.
