### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.autograd'

### ISSUE THREAD

**Issue by sbhaaf** [pytorch/pytorch#1851]
Hello. I just did a fresh install on Ubuntu with Anaconda 3.6, and I'm getting the following error:

> Traceback (most recent call last):
>   File "py_test.py", line 2, in <module>
>     from torch.autograd import Variable
> ModuleNotFoundError: No module named 'torch.autograd'

This is with a simple script:

`import torch`
`from torch.autograd import Variable`

Thank you in advance

**Comment by vlasenkov** [comment]
How did you install it?

**Comment by sbhaaf** [comment]
I used `conda install pytorch torchvision -c soumith`

**Comment by vlasenkov** [comment]
Do you have cuda installed or cuda compatible graphics card?
Show output of `conda list pytorch` please

**Comment by soumith** [comment]
i think you might have a folder in your current working directory named `torch`. I cant think of any other reason why this would fail. Definitely cannot reproduce this myself.
Let me know if changing directory (for example `cd ..`) doesn't fix it for you.

**Comment by y3mnx** [comment]
pip install torchvision 

Try This and Be happy ... Its working
