### ISSUE TITLE
torch.stft export bug, using operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK, throws error: ONNX FATAL: [enforce fail at backend.cc:777] . Caffe2 only supports padding 2D Tensor, whereas padding is [0, 0, 160, 0, 0, 160, ]

### ISSUE THREAD

**Issue by tsauri** [pytorch/pytorch#18521]
## 🐛 Bug

Cannot export torch.stft() with ONNX, even with OperatorExportTypes.ONNX_ATEN and OperatorExportTypes.ONNX_ATEN_FALLBACK

Seems that torch.stft produce non 2D tensor, and Caffe2 currently does not support padding for non 2D tensor
Related issue:
https://github.com/onnx/onnx-caffe2/issues/293

## To Reproduce

```
import torch, onnx 
import caffe2.python.onnx.backend as onnx_caffe2_backend      
class Model(torch.nn.Module): 
  def __init_(self): 
    super().__init__() 
  def forward(self,x): 
    return torch.stft(x, 320, 160, window=torch.hann_window(320)) 
m = Model()
x = torch.ones(1,1,512)
x2 = x.reshape(1,-1)
# 0 
torch.onnx.export(m, x2, f="specmodel.onnx", verbose=True,
  operator_export_type=torch.onnx.OperatorExportTypes.ONNX) 

# 1
torch.onnx.export(m, x2, f="specmodel.onnx", verbose=True,
  operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN) 
model = onnx.load('specmodel.onnx')                                                                                                                                             
prepared_backend = onnx_caffe2_backend.prepare(model)                                                                                                                           
W = {model.graph.input[0].name: x2.data.numpy()}                                                                                                                                
c2_out = prepared_backend.run(W)[0]    

# 2 
torch.onnx.export(m, x2, f="specmodel.onnx", verbose=True,
  operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK) 
model = onnx.load('specmodel.onnx')                                                                                                                                             
prepared_backend = onnx_caffe2_backend.prepare(model)                                                                                                                           
W = {model.graph.input[0].name: x2.data.numpy()}                                                                                                                                
c2_out = prepared_backend.run(W)[0]    


```
### error message if run # 0
```
RuntimeError: ONNX export failed: Couldn't export operator aten::stft
```
### error message if run # 1
```
op ATen: Source for input  is unknown for net torch-jit-export_predict, operator input: "21" input: "22" input: "23" input: "" input: "1" input: "25" input: "26" output: "27" name: "" type: "ATen" arg { name: "operator" s: "stft" }
```

### error message if run # 2
```
ONNX FATAL: [enforce fail at backend.cc:777] . Caffe2 only supports padding 2D Tensor, whereas padding is [0, 0, 160, 0, 0, 160, ]
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x59 (0x7fee1c4f8ed9 in /home/raden/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: caffe2::onnx::Caffe2Backend::CreatePad(caffe2::onnx::OnnxNode*, caffe2::onnx::ConversionContext const&) + 0x373 (0x7fedc27a2013 in /home/raden/anaconda3/lib/python3.7/site-packages/torch/lib/libcaffe2.so)
frame #2: caffe2::onnx::Caffe2Backend::OnnxNodeToCaffe2Ops(onnx_torch::ModelProto const&, onnx_torch::ModelProto const&, caffe2::onnx::ConversionContext const&, caffe2::onnx::OnnxNode*) + 0x115 (0x7fedc27a96a5 in /home/raden/anaconda3/lib/python3.7/site-packages/torch/lib/libcaffe2.so)
frame #3: caffe2::onnx::Caffe2Backend::ConvertNode(std::string const&, caffe2::onnx::ConversionContext const&) + 0xe5 (0x7fedc27aa865 in /home/raden/anaconda3/lib/python3.7/site-packages/torch/lib/libcaffe2.so)

```

## Environment
Collecting environment information...
PyTorch version: 1.0.0.dev20190326
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 4.9.4-2ubuntu1~16.04) 4.9.4
CMake version: version 3.12.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB

Nvidia driver version: 384.145
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.3
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6

Versions of relevant libraries:
[pip3] numpy==1.15.4
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.6            py37hd81dba3_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch-nightly           1.0.0.dev20190326 py3.7_cuda9.0.176_cudnn7.4.2_0    pytorch
[conda] torch                     1.0.1.post2              pypi_0    pypi
[conda] torchaudio                0.2                      pypi_0    pypi

**Comment by soumith** [comment]
cc: @houseroad @zrphercule

**Comment by houseroad** [comment]
This is a known issue. In caffe2, we translate pad to PadImage, which only handles 2d. Two options: 1) We should implement a general Pad operator in Caffe2, 2) we can insert a unsqueeze before pad and squeeze after pad

**Comment by tsauri** [comment]
Any updates on this missing non 2D pad operator?

For now I reimplemented STFT with Conv1D, and use zero padding with param padding=(some_value) inside with nn.functional.conv1d params

**Comment by garymm** [comment]
Nobody is working on Caffe2 anymore, so closing this.

**Comment by thelou1s** [comment]
So, What's the recommend method to fix this, thank you:

`torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::stft' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues
`

**Comment by garymm** [comment]
torch.stft support seems to have been added in https://github.com/pytorch/pytorch/pull/92087 so I guess if you have a new enough torch and use a high enough opset version it should work.
