### ISSUE TITLE
DataParallel Problem on Meta Network

### ISSUE THREAD

**Issue by Dataphz** [pytorch/pytorch#18522]
## 🐛 Bug
To implement MetaNetwork, we realize a MetaNet class, which inherits from nn.Module class and use buffer to save parameter of Network instead of Parameter. When we use Dataparallel to run on four gpus[0,1,2,3], the four gpus all get the copy of model, but only the gpu 0's Util is larger than 70% , others are less than 20%.  
## Expected behavior
all the gpus' Util are larger than 70%

## Environment
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 396.37
cuDNN version: /unsullied/sharefs/_admin/cuda/cuda-9.0/cudnn/v7.4.1/lib64/libcudnn.so.7.4.1

Versions of relevant libraries:
[pip3] numpy==1.15.2
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.2.2.post3

Thank you!

**Comment by soumith** [comment]
this is not a bug. the networks are probably small enough to have replication overhead just eat most of the time.

Try using DistributedDataParallel instead https://pytorch.org/docs/stable/distributed.html#launch-utility

**Comment by Dataphz** [comment]
Thanks for your help! There exists others question i want to ask: 
1. the memory of gpu 0 is 2457MB, while other gpus' memory is 1043MB, less than gpu 0

In addition, i print the information when running the model, and find that replication_time really eat most of the time, as:
scatter_time:0.0078, replicas_time:0.37, period_time:0.62
scatter_time:0.0075, replicas_time:0.38, period_time:0.62
scatter_time:0.0089, replicas_time:0.53, period_time:0.46
scatter_time:0.0073, replicas_time:0.37, period_time:0.62

However, we use regular module to realize our network and work normally on four gpus.  Is there any bugs we ignore?
