### ISSUE TITLE
test_torch.py (and other files) are too long; it takes a very long time to lint them

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#18539]
Some experiments I did on OS X:

* A barebones flake8 install takes 4.9s to lint this file
* Add flake8-bugbear and mccabes and it goes up to 5.2s
* Add flake8-comprehensions, flake8-mypy and flake8-pyi and it goes up to 6s
* Run the "full kahuna Facebook flake8" configuration: 8.6s

That is a really long time to wait for lint results to come back. I guess we can complain about how Python is a really slow language but there's another way to fix this problem and that's to make this file smaller :)

**Comment by mruberry** [comment]
See https://github.com/pytorch/pytorch/issues/42847 for a more modern version of this issue. This particular complaint was fixed by the refactoring done to test_torch.py in https://github.com/pytorch/pytorch/pull/47356. As of this writing test_torch.py is 7073 lines.
