### ISSUE TITLE
[docs] torch.(a)range dtype doc is wrong

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#18534]
https://pytorch.org/docs/master/torch.html#torch.arange and https://pytorch.org/docs/master/torch.html#torch.range say that they uses the default floating point dtype, but the default dtype is `int64`

**Comment by iArunava** [comment]
Hi! I would like to take this!
These are the lines that need to be changed:
https://github.com/pytorch/pytorch/blob/1989716ae56a76168291f9f462d4af7852164b4f/torch/_torch_docs.py#L4067

and 

https://github.com/pytorch/pytorch/blob/1989716ae56a76168291f9f462d4af7852164b4f/torch/_torch_docs.py#L4034

And I will also change the default paramter arguments.
And, what the `dtype` should say exactly?

**Comment by soumith** [comment]
@SsnL https://pytorch.org/docs/master/torch.html#torch.arange already says 

```
dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()). If dtype is not given, infer the data type from the other input arguments. If any of start, end, or stop are floating-point, the dtype is inferred to be the default dtype, see get_default_dtype(). Otherwise, the dtype is inferred to be torch.int64.
```

#18604 fixes range though
