### ISSUE TITLE
torch.max with explicit outputs broken

### ISSUE THREAD

**Issue by mys007** [pytorch/pytorch#1853]
I have an issue with using torch.max with explicit outputs, `torch.max(input, dim, keepdim=False, max=None, max_indices=None)`. I'm running PyTorch 0.1.12. The following example:

````
import torch

t = torch.Tensor(3,4)
i = torch.LongTensor(1,4)
r = torch.Tensor(1,4)

a,b=torch.max(t,0)
print(a,b)

torch.max(t,0,max=r,max_indices=i)
````

works for the first part but throws an error in the second part:

````
TypeError: torch.max received an invalid combination of arguments - got (torch.FloatTensor, int, max_indices=torch.LongTensor, max=torch.FloatTensor), but expected one of:
 * (torch.FloatTensor source)
 * (torch.FloatTensor source, torch.FloatTensor other)
 * (torch.FloatTensor source, int dim)
````

**Comment by apaszke** [comment]
I think the docs are incorrect. You can do `torch.max(t,0,out=(r, i))`.

**Comment by mys007** [comment]
Thanks, that indeed works!

**Comment by soumith** [comment]
fixed docs via https://github.com/pytorch/pytorch/commit/8983bf13f41ab36e42d0acc7955c156fa441ac29
