### ISSUE TITLE
torch.std giving incorrect results

### ISSUE THREAD

**Issue by abhaikollara** [pytorch/pytorch#1854]
The results of `torch.std` and as a results `torch.var` are incorrect
```
x = torch.Tensor([2, 4])
torch.std(x)

1.4142135623730951
```
```
np.std([2,4])
1.0
```

Using python3.5, torch 0.1.12_2

**Comment by apaszke** [comment]
They are correct. The difference lies in [Bessel's correction](https://en.wikipedia.org/wiki/Bessel%27s_correction).
