### ISSUE TITLE
c++ output differs from python output

### ISSUE THREAD

**Issue by wait1988** [pytorch/pytorch#18554]
## ❓ Questions and Help
**Pytorch1.0,Ubuntu16.04,Same model,Same transformation,but I got totally different result with python and cpp code.
Anyone can help me out?Thx a lot.**

#========python output======#
tensor(9073.5586, device='cuda:0', grad_fn=<SumBackward0>)
#========c++ output======#
count:2.185325

The code I use is attached.
[predict_cpp .txt](https://github.com/pytorch/pytorch/files/3016030/predict_cpp.txt)
[export_py.txt](https://github.com/pytorch/pytorch/files/3016031/export_py.txt)

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
