### ISSUE TITLE
Checkpointing evaluates irrelevant tasks

### ISSUE THREAD

**Issue by sublee** [pytorch/pytorch#18566]
## 🐛 Bug

When the autograd graph has parallel lanes, and a checkpointing is on one of the lanes, the checkpointing evaluates irrelevant backwards on another lane.

For example, if our autograd graph looks like:
```
          +--> Eval1
Sum --> Cat
          +--> Checkpoint(Eval2)
```

The backward of `Checkpoint(Eval2)` evaluates the backward of `Eval1` recursively.

It's not an expected behavior because there's no any dependency between them. `Eval1` should be evaluated AFTER `Checkpoint(Eval2)`.

## To Reproduce

1. Make parallel lanes in an autograd graph.
1. Use `torch.utils.checkpoint.checkpoint` on the one of the lanes.
1. Insert logs or a race condition to detect the recursion.

Let me show you. Following `Log` function will record the forward and backward event into `timeline`:
```python
timeline = []
class Log(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, name):
        ctx.name = name
        timeline.append('%s:forward' % name)
        return x
    @staticmethod
    def backward(ctx, grad_output):
        name = ctx.name
        timeline.append('%s:backward' % name)
        return grad_output, None
```

Now make an autograd graph like what I attached at the top:
```python
a = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

a = Log.apply(a, 'a')
b = checkpoint(lambda b: Log.apply(b, 'b'), b)
out = torch.cat((a, b)).sum()

#                 +--> Log[a] --> a
# Sum --> Cat[a, b]
#                 +--> Checkpoint(Log[b]) --> b
out.backward()
```

Now check `timeline` to detect the recursion. We can see that the backward of `Log[a]` is evaluated in the backward of `Checkpoint(Log[b])`:
```python
>>> print(timeline)
['a:forward', 'b:forward', 'b:forward', 'a:backward', 'b:backward']
>>> # forward pass -----|  |            |- Log[a] -|             |
>>> #                      |--------- Checkpoint(Log[b]) --------|
```

## Expected behavior

In my reproducing code, `timeline` should follow the below order because there's no dependency between `Checkpoint(Log[b])` and `Log[a]`:
```python
assert timeline == \
    ['a:forward', 'b:forward', 'b:forward', 'b:backward', 'a:backward']
#    |----------------------|  |-----------------------|  |----------|
#          forward pass            Checkpoint(Log[b])        Log[a]
```

I read `autograd/engine.cpp` including the `[Reentrant backwards]` note. If my understanding is correct, nested backwards should evaluate only the tasks which it queued. Because of a specified `graph_task` and the sorting rule of `ReadyQueue`.

## Environment

I reproduced it on ffc7158bf2f97916305217e4203ef846c00161ce (`master`) and bb15580e88cc963df22eab291fbe182f42426ad5 (v1.0.1).
```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 396.44
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1

Versions of relevant libraries:
[pip] numpy==1.16.2
[conda] blas                      1.0                         mkl
[conda] magma-cuda90              2.5.0                         1    pytorch
[conda] mkl                       2019.3                      199
[conda] mkl-include               2019.3                      199
[conda] mkl_fft                   1.0.10           py36ha843d7b_0
[conda] mkl_random                1.0.2            py36hd81dba3_0
```

## Additional context

I think https://github.com/pytorch/pytorch/issues/6959 is related with this issue. As @shubhtuls said, there's no reason for checkpointing to rely on nested recursions.

**Comment by sublee** [comment]
This unexpected behavior may lead to a deadlock or a recursion limit error. I wrote two simple code to reproduce the problems: https://gist.github.com/sublee/e370f3ecadb570eac18a9a0f0cc3b095.

**Comment by sublee** [comment]
I've discussed this issue with @albanD in #18568. We both agree that probably this issue is not possible to be fixed completely. Instead of fixing it, documentation and warning about it would be a better choice.

**Comment by ezyang** [comment]
Thank you for looking into it. Happy to review a PR to this effect.

**Comment by albanD** [comment]
This now has the correct behavior in master.
Please re-open if you see more issues.
