### ISSUE TITLE
torch.manual_seed raises an error in forked processes

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#1856]
Because it tries to init CUDA

**Comment by Kaixhin** [comment]
What's the behaviour of `torch.cuda.manual_seed_all(seed)` when you run one process where this is called, and then another process where this is called - does it affect the randomness in the first process (and hence introduce nondeterminism)?

**Comment by apaszke** [comment]
No. It will raise an error after fork (stopping you from reusing the same CUDA context, which is UB anyway), and will seed a process-local generator if you use spawn

**Comment by alykhantejani** [comment]
How should this behave in a forked process? 

If we check if cuda is initialized and then skip the `torch.cuda.manual_seed_all` part, does this have undefined behaviour?

From the conversation I think it should throw an error in a forked process?

**Comment by apaszke** [comment]
No, I think we should skip CUDA seed in forked process. Calling CUDA functions should raise an error there anyway, but we need a way to seed CPU generators

**Comment by alykhantejani** [comment]
So if we have a way to expose the `_in_bad_fork` flag in `torch.cuda.__init__` then in `torch.manual_seed` we can do:
```python
    if torch.cuda.is_available() and not _in_bad_fork:
        torch.cuda.manual_seed_all(seed)

    return default_generator.manual_seed(seed)
```
?

**Comment by apaszke** [comment]
Yes, that should work. You don't need any special way of exposing that variable. It can be accessed directly through `torch.cuda._in_bad_fork`

**Comment by alykhantejani** [comment]
Yeah, but that's private state no? but I also don't like the idea of `torch.cuda.in_bad_fork()` as that shouldn't be part of the public API either.

**Comment by apaszke** [comment]
It is. You can add a comment next to `_in_bad_fork` saying that if someone wants to change that, they should also modify `torch.manual_seed`

**Comment by alykhantejani** [comment]
ok, will do that.
