### ISSUE TITLE
[FR] warn/error when MAGMA is built with a different CUDA

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#18574]
Recently I found out that `magma-cuda100` is not compatible with CUDA 10.1 (in the sense that some but not all ops don'k work).  It would be good if we can error in cmake when MAGMA and CUDA have mismatching CUDA version.

**Comment by vishwakftw** [comment]
Related to https://github.com/pytorch/pytorch/issues/3990.

**Comment by SsnL** [comment]
closed as duplicate
