### ISSUE TITLE
DataParallel does not support dicts as first (or sole) input

### ISSUE THREAD

**Issue by arunmallya** [pytorch/pytorch#1857]
https://github.com/pytorch/pytorch/blob/d9d50f80c7f162c9c6c6d95c0b51f9e6fd8fccee/torch/nn/parallel/parallel_apply.py#L21-L22 is the culprit. Assumes that the first input is a variable or a sequence containing a variable in index 0 (recursively indexed).

Workaround is to pass a dummy variable as first input, as suggested in https://pytorch.slack.com/archives/C2077MFDL/p1497986173722359

**Comment by csarofeen** [comment]
Could you provide a short reproducer for testing? Think this shouldn't be too hard to fix.

**Comment by arunmallya** [comment]
Sure, here's a gist along with commands/outputs: https://gist.github.com/arunmallya/5e569e4c23ad0567a64764ad70a393b1

**Comment by soumith** [comment]
fixed in master via #1880
