### ISSUE TITLE
Logical bug in the implementation of Threshold

### ISSUE THREAD

**Issue by caogang** [pytorch/pytorch#1860]
Due to my fault of last implementation PR #1507 . :(
The logic of here is wrong.
```python
torch/nn/_functions/thnn/activation.py

         else:
             grad_input = grad_output.masked_fill(input > ctx.threshold, 0)
         return grad_input, None, None, None
```
And this will cause some innormal value in my application.

I will fix it after a while.

**Comment by apaszke** [comment]
Can you elaborate why is it wrong?

**Comment by caogang** [comment]
Because `Threshold` only pass the input which is `input > threshold`. So it only pass the gradient to the `postive_position` where `input[ postive_position ] > threshold`. The gradient passed to other position should be set zero. 

But here, the implementation is doing in the opposite way. The implementation should be `grad_output.masked_fill(input <= ctx.threshold, 0)`
