### ISSUE TITLE
How to Make a Convolution Kernel in a Layer Not Participate in Back Propagation in Convolutional Networks？

### ISSUE THREAD

**Issue by TonightHitTiger1** [pytorch/pytorch#18611]
I'm doing research on model pruning. 
Filter pruning. 
I set the value of some filters to 0, then retrain model. But these values become non-zero in the process of Back Propagation.
What can we do to solve this problem? （Keep these filters at 0 during retraining）

Thanks for your help~~

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
