### ISSUE TITLE
torch.matmul not working in cuda 9.0

### ISSUE THREAD

**Issue by AlenUbuntu** [pytorch/pytorch#18620]
## 🐛 Bug

I am using Pytorch 1.0.1 and cuda 9.0 with a RTX 2080 Ti GPU. If I apply torch.matmul(x1, x2) function to 2 random tensors, i.e. x1 (128, 64, 32) and x2 (128, 32, 64) on GPU, I get following error message: 
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1549635019666/work/aten/src/THC/THCBlas.cu:441

However, if I immediately execute torch.matmul(x1, x2) again, the operation performs correctly.

Moreover, if I upgrade cuda 9.0 to cuda 10.0, the error disappears.

**Comment by SsnL** [comment]
cuda 9 doesn't support RTX cards afaik

**Comment by ngimel** [comment]
This is expected behavior, you need cuda 10 for RTX cards.
