### ISSUE TITLE
torch.utils.cpp_extension does not set CUDA arch

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#18657]
## 🐛 Bug

CPP Extensions are built with whatever default nvcc uses.

## To Reproduce

1. Compile any CUDA extension
2. `cuobjdump --list-elf /tmp/torch_extensions/my_ext/my_ext.so`

It shows something like `my_ext.1.sm_30.cubin`, i.e. CUDA Arch 3.0, when my card has 6.1 and I had compiled PyTorch with `TORCH_CUDA_ARCH_LIST='6.1'`.
I noticed because `__ldg` wasn't supported.

## Expected behavior

Sane behaviour would be to use either the arch from PyTorch compilation (because if you can use PyTorch, it seems to work reasonably well) or one that fits the GPUs (in particular with inline), either would be an improvement over the current behvious.

## Environment

Masterish PyTorch on a machine with a GTX1080Ti

**Comment by xsacha** [comment]
Should be an option to build All architectures too (i.e. 30 35 50 52 60 61 70 75 or whatever FindCUDA finds).
