### ISSUE TITLE
Using EmbeddingBag with 1D input and offests with DataParallel

### ISSUE THREAD

**Issue by PrzemekPobrotyn** [pytorch/pytorch#18685]
## 🐛 Bug

Attempting to parallelise EmbeddingBag with inputs being a tuple (1D LongTensor of indices, 1D LongTensor of offsets) to multiple GPUs results in incorrect chunking of the batch and throws `ValueError: offests[0] has to be 0, i.e., the first sequence in the mini-batch has to start from position 0.`

## To Reproduce
Minimal example below which works on CPU/single GPU but throws an error on two (or more) GPUs.

```import torch
import torch.nn as nn

model = nn.EmbeddingBag(10, 3, mode='sum')
input = torch.LongTensor([1, 2, 4, 5, 4, 3, 2, 9])
offsets = torch.LongTensor([0, 4])

device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")
if torch.cuda.device_count() > 1:
    model = torch.nn.DataParallel(model)

model.to(device)

result = model(input, offsets)
print(result)
```

## Expected behavior

Expected result is:
```
tensor([[ 3.2435,  2.1600, -0.5829],
        [ 1.6799, -1.4256,  0.9595]], grad_fn=<EmbeddingBagBackward

(or some other numbers, depending on your seed)

```
Actual result is the following error:

```
ValueError: offsets[0] has to be 0, i.e., the first sequence in the mini-batch has to start from position 0. However, got 4
```

## Environment

The above snippet was run on GCP ML-Engine with two K80s.

Output of env script:

PyTorch version: 1.0.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176
OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect
Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla K80
GPU 1: Tesla K80
Nvidia driver version: 410.79
cuDNN version: Could not collect
Versions of relevant libraries:
[pip3] numpy==1.16.1
[pip3] torch==1.0.1
[pip3] torchvision==0.2.2
[conda] Could not collect

## Additional context

To the best of my understanding, simply using torch.nn.DataParallel causes the batch to by split as evenly as possible along the batch dimension, which in the case of 1D input to EmbeddingBag won't work as it causes two problems: potentially splits the batch in the middle of a single "bag" and causes the offsets tensors for 2nd and subsequent GPUs to start with a non-zero index. I believe a workaround would be to override the scatter and gather functionalities of nn.parallel. Shouldn't this be a part of regular pytorch API though?

**Comment by soumith** [comment]
this is not expected to work by design. The DataParallel documentation does say that it'll scatter the inputs in one dimension.

If you do want this to work, mirror your inputs and offsets into a fake dimension:

```
input, offsets = input.unsqueeze(0).expand(torch.cuda.device_count(), input.size(0)), offsets.unsqueeze(0).expand(torch.cuda.device_count(), offsets.size(0))
```

and inside your model forward, you'll have to squeeze them again:

```
input, offsets = input.squeeze(0), offsets.squeeze(0)
```
