### ISSUE TITLE
torch.cuda.is_available() is False in container created by pytorch images downloaded from dockerhub

### ISSUE THREAD

**Issue by wkoa** [pytorch/pytorch#18690]
I have pulled pytorch/pytroch:1.0.1-cuda10.0-cudnn7-devel  image from docker hub.
but when I create one container by this images, I found that torch.cuda.is_available() is always False.
this is the command I used to create a container:
NV_GPU=0 nvidia-docker run -it --rm pytorch/pytorch:1.0.1-cuda10.0-cudnn7-devel 

<img width="797" alt="屏幕快照 2019-04-02 上午12 18 43" src="https://user-images.githubusercontent.com/21969193/55343182-2b271d00-54dd-11e9-9e99-390aced7d27c.png">
<img width="521" alt="屏幕快照 2019-04-02 上午12 18 50" src="https://user-images.githubusercontent.com/21969193/55343198-337f5800-54dd-11e9-896e-2d65d7ce8890.png">
<img width="474" alt="屏幕快照 2019-04-02 上午12 18 59" src="https://user-images.githubusercontent.com/21969193/55343205-38440c00-54dd-11e9-875e-5dc628b679cf.png">

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
