### ISSUE TITLE
SpatialDilatedConvolution with Cuda not working

### ISSUE THREAD

**Issue by vaibhav-patel** [pytorch/pytorch#1870]
**FloatSpatialDilatedConvolution_updateOutput received an invalid combination of arguments - got (int, torch.cuda.FloatTensor, torch.FloatTensor, torch.FloatTensor, torch.FloatTensor, torch.FloatTensor, torch.FloatTensor, int, int, int, int, int, int, int, int), but expected (int state, torch.FloatTensor input, torch.FloatTensor output, torch.FloatTensor weight, [torch.FloatTensor bias or None], torch.FloatTensor columns, torch.FloatTensor ones, int kW, int kH, int dW, int dH, int padW, int padH, int dilationW, int dilationH)**

**Comment by ngimel** [comment]
Looks like you have not cast your module to .cuda(), only input.

**Comment by vaibhav-patel** [comment]
And how one does that?
I am using torch.nn and torch.legacy.nn both.

**Comment by ngimel** [comment]
```model.cuda()``` where model is your model.

**Comment by vaibhav-patel** [comment]
Thank you so much. It worked.
