### ISSUE TITLE
[MSVC] Caffe2-Debug Static Size Too Big LNK1248

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#18701]
## 🐛 Bug

pytorch-Debug-build\lib\Debug\caffe2-Debug.lib: fatal error LNK1248: image size (10007FE9E) exceeds maximum allowable size (FFFFFFFF)
## To Reproduce

1. Compile latest master on Windows as static

## Expected behavior

Links

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake -DUSE_CUDA=ON -DBUILD_SHARED_LIBS=OFF
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: GTX 1060
 - Any other relevant information:

## Additional context

Did not have this issue in 1.0.1 but perhaps size has just gone over the threshold.

It appears MSVC has a 4GB code/data file size limit. I'm sure there's a workaround.
Although, Microsoft says to split up the library: https://developercommunity.visualstudio.com/content/problem/332991/static-lib-4gb-file-size-limit-lnk1248-image-size.html

**Comment by peterjc123** [comment]
I think the cause may be that we are using /Z7 in the linking flags. According to the MSVC [document](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2017), `/Z7` will put all the debugging stuff into the object files, thus making large object/libraries. The alternatives are /Zi and /ZI. However, we need sccache to rebuild things quickly in CI, so we cannot use them. But if you don't use sccache, then you can try whether it works.

**Comment by xsacha** [comment]
OK, I will try /Zi

**Comment by peterjc123** [comment]
Are you using Ninja? Have you specified `TORCH_NVCC_ARCH_LIST`? In our CI, the build time for 16 VCPU cores is 20-30 minutes with ninja and sccache.

**Comment by xsacha** [comment]
Well if I used sccache it would be fast for sure. What was the first run speed?
Not using Ninja.

I haven't specified TORCH_NVCC_ARCH_LIST. What is the default? Does it build every arch?

**Comment by peterjc123** [comment]
> I haven't specified TORCH_NVCC_ARCH_LIST. What is the default? Does it build every arch? That could be it if the default behaviour changed.

If you don't specify it, there is a chance that it is not automatically detected. And then, it will build for all arches which will be time-consuming. 

> I haven't seen any benefit in Ninja recently 

Previously, VS doesn't support parallel custom build jobs, so building cuda sources will take a long time. However, looks like it is implemented in a newer version of VS, but I don't know exactly whether it is well supported by CMake.

**Comment by xsacha** [comment]
Yeah, I've enabled parallel builds since it was supported. Since then, I haven't used Ninja (I get similar build time).

On Linux, I get a build time of 20 minutes. Is it possible the card detection only works on Linux? I'm using a Titan V there.
Does it print out which arches it is building for somewhere? That would be a nice addition, like what OpenCV does.

**Comment by peterjc123** [comment]
Yes, it is printed out in `Summary`. And `All` is an acceptable value for TORCH_NVCC_ARCH_LIST.

**Comment by xsacha** [comment]
I'm having trouble finding it in the `Summary`.

From OpenCV:
>     --   NVIDIA CUDA:                   YES (ver 10.1, CUBLAS)
>     --     NVIDIA GPU arch:             30 35 37 50 52 60 61 70 75
>     --     NVIDIA PTX archs:

From Torch:
>   USE_CUDA              :  ON
>     CUDA static link    : OFF
>     USE_CUDNN           : ON
>     CUDA version        : 10.1
>     cuDNN version       : 7.5

**Comment by peterjc123** [comment]
Torch: 
> -- Found CUDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/include  
-- Found cuDNN: v7.2.1  (include: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/include, library: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/lib/x64/cudnn.lib)
-- Added CUDA NVCC flags for: -gencode;arch=compute_50,code=sm_50

**Comment by xsacha** [comment]
Right, that gets printed somewhere above the Summary. No wonder I've never seen it.
So I just checked on my Windows laptop and it's only generating for arch 61.

Too bad, that doesn't explain this issue (static size being so big) or the slow compiles.

**Comment by xsacha** [comment]
@peterjc123, /Zi did work
The PDB was 250MB

Release:
7.5M c10.lib
2.1M c10_cuda.lib
1.1G caffe2.lib
1.7G  caffe2_gpu.lib
5.5M caffe2_protos.lib
384M torch.lib

Debug:
8.4M c10_cuda-Debug.lib
28M c10-Debug.lib
2.1G caffe2_gpu-Debug.lib
8.3M caffe2_protos-Debug.lib
3.4G caffe2-Debug.lib
705M torch-Debug.lib

**Comment by peterjc123** [comment]
I guess I can add an option for the user to choose /Zi over /Z7.
