### ISSUE TITLE
Can someone change the download guide of pytorch in https://pytorch.org ?

### ISSUE THREAD

**Issue by AinzWoolGoun** [pytorch/pytorch#18719]
A couple days ago I want to install PyTorch through pip, so I follow the guide and download the .whl file from _https://pytorch.org_. But when I run `import torch`, it went wrong `from _C import * ImportError: DLL not found` . After using a lot of ways to fix the problem, I finally find that Pytorch is not support Python 3.6.0, which is installed in my laptop. But the download guide didn't say that!
![image](https://user-images.githubusercontent.com/33094900/55387498-1d68aa80-5564-11e9-9896-9f8975089081.png)
So I will be appreciate if the web master of _https://pytorch.org_ can fix it, which may save everybody's time.
By the way, I upgrade to Python 3.6.7 and slove the problem.
Forget about my poor English.

**Comment by peterjc123** [comment]
Would you please send a PR here? https://github.com/pytorch/pytorch.github.io/blob/master/assets/quick-start-module.js#L433-L443
