### ISSUE TITLE
Magic value not found when loading traced model

### ISSUE THREAD

**Issue by jinfei3459** [pytorch/pytorch#18720]
## To Reproduce
I use `traced_script_module = torch.jit.trace(alphaposemodel, x)` transform alphapose model

```python
import torch
import torchvision

from dataloader import Mscoco

from SPPE.src.main_fast_inference import *
from torch.autograd import Variable
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

def LoadModel():
    pose_dataset = Mscoco()
    model = InferenNet_fast(4 * 1 + 1, pose_dataset)

    model = model.cuda()

    return model

if __name__ == '__main__':

    
    model = LoadModel()
    # print("model", model)

    x = Variable(torch.randn(1, 3, 320, 256).cuda(), requires_grad=True)
    result = model(x)
    print("torch result:", result)
    traced_script_module = torch.jit.trace(model, x)
    output = traced_script_module(x)
    print("--------------------------------")
    print("trave result:", output)
    traced_script_module.save("/data4/zjf/code/Pose-Estimation/AlphaPose-pytorch-v2/models/duc_se.pt")
```

then, use pyotrch c++ load the "duc_se.pt"

```
terminate called after throwing an instance of 'c10::Error'
  what():  memcmp("PYTORCH1", buf, kMagicValueLength) != 0 ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:75, please report a bug to PyTorch. File is an unsupported archive format from the preview release. (PyTorchStreamReader at /pytorch/caffe2/serialize/inline_container.cc:75)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fe38f617021 in /data4/zjf/code/Pose-Estimation/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fe38f6168ea in /data4/zjf/code/Pose-Estimation/libtorch/lib/libc10.so)
frame #2: torch::jit::PyTorchStreamReader::PyTorchStreamReader(std::string, std::istream*) + 0x8c6 (0x7fe3c019c316 in /data4/zjf/code/Pose-Estimation/libtorch/lib/libcaffe2.so)
frame #3: <unknown function> + 0x6663b3 (0x7fe3caae23b3 in /data4/zjf/code/Pose-Estimation/libtorch/lib/libtorch.so.1)
frame #4: torch::jit::load(std::istream&, c10::optional<c10::Device>) + 0x7f (0x7fe3caae573f in /data4/zjf/code/Pose-Estimation/libtorch/lib/libtorch.so.1)
frame #5: torch::jit::load(std::string const&, c10::optional<c10::Device>) + 0x6c (0x7fe3caae58cc in /data4/zjf/code/Pose-Estimation/libtorch/lib/libtorch.so.1)
frame #6: main + 0x94 (0x4013d7 in ./example-app)
frame #7: __libc_start_main + 0xf0 (0x7fe38feca830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #8: _start + 0x29 (0x4011d9 in ./example-app)

Aborted (core dumped)
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```bash
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version :1.0 latest
 - OS: ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source):docker
 - Python version:3.6.5
 - CUDA/cuDNN version:cuda 9.1
 - GPU models and configuration:
 - Any other relevant information:

**Comment by jinfei3459** [comment]
alphapose：https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch

**Comment by ailzhang** [comment]
assigning to @driazati for serialization issue, please feel free to pass it on to others

**Comment by jinfei3459** [comment]
`
root@b54eacad8078:/data4/zjf/code# python collect_env.py
Collecting environment information...
PyTorch version: 1.0.0a0+4ec6bd7
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: Tesla P40
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: Tesla P40

Nvidia driver version: 390.25
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.2

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.1
[pip3] numpy==1.15.1
[pip3] torch==1.0.0a0+4ec6bd7
[pip3] torchfile==0.1.0
[pip3] torchtext==0.3.1
[pip3] torchvision==0.2.1
[pip3] torchvision-nightly==0.2.1
[conda] Could not collect
`

**Comment by driazati** [comment]
Can you also post the C++ code you were using the load the module?

**Comment by driazati** [comment]
I can't repro this on master, feel free to re-open if it's still an issue
