### ISSUE TITLE
Is torch.distributed.all_reduce implemented with Ring-AllReduce or Tree-based AllReduce, or others?

### ISSUE THREAD

**Issue by Steamgjk** [pytorch/pytorch#18738]
I am using Gloo as the backend for distributed machine learning. I am curious about the implementation of torch.distributed.all_reduce in detail. Currently the official documentation does not talk about it. I wonder whether it is a ring-based all-reduce or tree-based all-reduce?

Besides, are there any examples to use RoCE for distributed Pytorch?

**Comment by soumith** [comment]
if you want to ask questions, https://discuss.pytorch.org is the right place. Add the `distributed` label to your post once you post it on the forums.
