### ISSUE TITLE
perhaps register_buffer and friends should check if the property already exists on the module

### ISSUE THREAD

**Issue by greaber** [pytorch/pytorch#1874]
I was mistakenly trying to register a buffer that was already defined as a model property, something like this (but there could be less trivial cases):
```
self.foo = torch.Tensor([0])
self.register_buffer('foo', self.foo)
```
I found that if you do this, the model works fine on the CPU, but it breaks when you use the GPU because the buffer is moved but the property isn't.  Perhaps `register_buffer` and the other registration functions should check if the property is already defined on the model and give an error if it is.

**Comment by soumith** [comment]
thanks, this is definitely worth fixing / raising an error. we'll fix it.

**Comment by alykhantejani** [comment]
@soumith I can send a PR for this if no one is currently working on it
