### ISSUE TITLE
[MSVC Static] DeviceGuardImpl for CPU is not available

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#18757]
## 🐛 Bug

After having built a static libtorch.a and loading a model, I get the following exception:
c10::Error: DeviceGuardImpl for CPU is not available.

## To Reproduce

1. Build static libtorch on Windows
2. Attempt to load model

`std::shared_ptr<torch::jit::script::Module> model = torch::jit::load(model_path, torch::kCUDA);`

## Expected behavior

Works

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake -DBUILD_TORCH=ON -DTORCH_STATIC=ON -DBUILD_SHARED_LIBS=OFF
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1/7.5
 - GPU models and configuration: 1060
 - Any other relevant information:

**Comment by ezyang** [comment]
This probably has to do with static initializers running in the wrong order when you link everything statically together. A possible workaround might be to manually call the code responsible for the initialization before you try to do anything in libtorch. I don't know off the top of my head what that would be.

**Comment by ezyang** [comment]
cc @kostmo this is one problem which might be exacerbated when you merge libcaffe2 and libtorch.

**Comment by gchanan** [comment]
@ezyang do we still build libtorch statically on windows?

**Comment by xsacha** [comment]
I would like if it worked :)

**Comment by ezyang** [comment]
@xsacha did you get the workaround to work, at least?

**Comment by xsacha** [comment]
Was that the one with removing the static initializers? I had another problem at the time but haven't tried the latest version.

**Comment by blacksailer** [comment]
> 
> 
> This probably has to do with static initializers running in the wrong order when you link everything statically together. A possible workaround might be to manually call the code responsible for the initialization before you try to do anything in libtorch. I don't know off the top of my head what that would be.

Which initializers do you mean? I met same problem on another linux based OS.

**Comment by mattip** [comment]
PR gh-17783 removed the `BUILD_TORCH` and `TORCH_STATIC` options. In order to reproduce I tried 

```
# Create the test files (see detail below)

# Build a static-version of pytorch
export BUILD_SHARED_LIBS=0;
python setup.py develop

# Compile and run some test code
g++ -I torch/csrc/api/include/ -Itorch/include /tmp/main.cpp -L build/lib \
        -L<path/to/mkl//lib> -lshm -ltorch_cuda -ltorch_cpu -lfbgemm -lcpuinfo \
        -lclog -lc10 -lasmjit -lcaffe2_protos -lpthread -lgomp -lmkl_rt
LD_LIBRARY_PATH=build/lib:/path/to/mkl/lib ./a.out
```

and it all worked fine (no error). @blacksailer, @xsacha could you confirm that your code still fails?

<details><summary> Create the test files </summary>

```
cat << EOF > /tmp/main.cpp
#include <torch/torch.h>
#include <torch/script.h>

int main(int argc, const char * argv[]) {
    auto module = torch::jit::load("/tmp/model.txt", torch::kCUDA);
}
EOF
```
At a python prompt with a functioning torch install:
```python
import torch 
class SingleTensorModel(torch.nn.Module): 
    def forward(self, arg): 
        return arg 


sm = torch.jit.script(SingleTensorModel())
with open('tmp/model.txt', 'wb') as fid:
    torch.jit.save(sm, fid)
```

**Comment by mattip** [comment]
No response from @blacksailer, @xsacha. Should we close this?
