### ISSUE TITLE
Clean up detection of library versions

### ISSUE THREAD

**Issue by jlquinn** [pytorch/pytorch#18760]
## 🐛 Bug

Right now, to determine the cuda library version, you use:

torch.version.cuda

which returns a string.  To detect the cudnn version, you use:

torch.backends.cudnn.version()

which returns an int.

Neither is a documented part of the API.  Could there be a unification of accessors to make this easier, as well as documenting the calls?

**Comment by soumith** [comment]
implemented in https://github.com/pytorch/pytorch/pull/18579 (yet to be merged) and tracked in #111
