### ISSUE TITLE
[Windows] CUDA error: out of memory

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#18766]
Observed in this build: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test1/26892/console

@yf225 says
> it's possible that we are initializing CUDA across multiple processes in Windows tests

**Comment by kostmo** [comment]
Another instance observed in this build: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test1/27224/console

    RuntimeError: CUDA error: out of memory

This is a string that would be easy to find if we set up some log analysis tool to gauge the frequency of different build failure modes.

**Comment by vladimir-aubrecht** [comment]
Could not reproduce with latest stack and considering this ticket is stale, I am closing it. Please create new ticket in case this occurs again with latest stack.
