### ISSUE TITLE
share_memory_ needs a check for empty tensor

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#1878]
```
a=torch.randn(0, 100)
a.share_memory_()
```
```
RuntimeError: $ Torch: unable to mmap memory: you tried to mmap 0GB. at /private/home/soumith/pytorch/torch/lib/TH/THAllocator.c:317
```
This error on linux, on OSX it works.

**Comment by apaszke** [comment]
how is that related to a tensor being empty? `a` has 100 elements

**Comment by soumith** [comment]
no, it has 0 elements. `a = torch.randn(0, 100)`, notice the 0

**Comment by apaszke** [comment]
Oh right... I mistakenly assumed it's `arange` when I saw 0, 100. Do we even allow such calls to `torch.randn`? that makes no sense

**Comment by colesbury** [comment]
I think we can safely change `_map_alloc` in `THAllocator.c`  to return `NULL` if size is 0.

**Comment by apaszke** [comment]
Yeah that should work. It doesnt make a lot of sense though, because these storages are not resizable

**Comment by willwhitney** [comment]
Any ETA on getting a release cut that includes this fix, or do I need to install from source?

**Comment by fmassa** [comment]
I think the new release should be out by next week.
