### ISSUE TITLE
TORCH_CUDA_ARCH_LIST=All should know what is possible

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#18781]
## 🐛 Bug

When setting TORCH_CUDA_ARCH_LIST=All, I expect Torch to compile with all CUDA architectures available to my current version of CUDA. Instead, it attempted to build for cuda 2.0.

See error:
nvcc fatal   : Unsupported gpu architecture 'compute_20'

## To Reproduce

1. Install CUDA >= 9.0
2. TORCH_CUDA_ARCH_LIST=All cmake -DUSE_CUDA=ON ..

## Expected behavior

Filters out 2.x architectures if CUDA >= 9.0

## Environment
CUDA 10.1

**Comment by peterjc123** [comment]
It should be sent here: https://gitlab.kitware.com/cmake/cmake/issues.

**Comment by xsacha** [comment]
It already works correctly in CMake though.
This may be like the Turing issue where the latest version isn't pulled from upstream.

If I am using a new enough CMake, should it not choose the default Find over the pytorch version, for this situation where the pytorch version is outdated?

**Comment by ezyang** [comment]
Sometimes we add patches on top of the cmake file which take some time to get merged upstream.

In this case, we probably should just pull the latest version and see if that fixes the problem.

**Comment by ezyang** [comment]
I checked cmake 7e60e77c3c2a09eb11750616db50d2dc149a9c54 but did not see any logic update to FindCUDA.cmake which would have fixed this problem.

So, it might be that only the "modern" cuda support does this correctly.

Deprioritizing because the fix is not easy, and there's an easy workaround.

**Comment by ezyang** [comment]
@peterjc123 figured out that it was in an auxiliary file :) This is fixed now.

**Comment by Blahblahdenver** [comment]
> @peterjc123 figured out that it was in an auxiliary file :) This is fixed now.

how do i set torch cuda arch list? im getting the same error but i dont know what auxiliary file is? got any tips for me? this is my code.

C:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Checkpoints\InstantMesh\instant_nerf_base.ckpt[0m
2024-08-03 22:01:14.172 [Debug] [ComfyUI-0/STDOUT] Warn!: C:\SwarmUI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
2024-08-03 22:01:14.172 [Debug] [ComfyUI-0/STDOUT] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
2024-08-03 22:01:14.172 [Debug] [ComfyUI-0/STDOUT]   warnings.warn(
2024-08-03 22:01:14.172 [Debug] [ComfyUI-0/STDOUT]
