### ISSUE TITLE
Add container for recurrent nets

### ISSUE THREAD

**Issue by vlasenkov** [pytorch/pytorch#1882]
It is not possible to use `Sequential` container with recurrent networks. TF offers this: [MultiRNNCell](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell). Would be great to tune `Sequential` for such cases or add a separate RNN container.

**Comment by vlasenkov** [comment]
[Here](https://github.com/vlasenkov/pytorch/blob/seq-rnn/torch/nn/modules/container.py#L67-L84) is a very approximate implementation. It seems not reliable. The main problem is that we can't securely infer input and output of recurrent nets. For example whether a hidden state is considered as output?
One workaround is to add to every module some attributes that would contain information about inputs and outputs. This will make automatic stacking of modules very simple. How about such a feature?

**Comment by soumith** [comment]
Truth be told, I despise the usage of Sequential. A for-loop is much more expressive. We were debating whether to include it in the first place (it and other containers such as Concat and Parallel), but in the end we just thought it'd be a dumb convenience wrapper that is lightly used.

I dont think it makes sense to extend Sequential with more features, especially if they are not trivial to implement.

**Comment by vlasenkov** [comment]
But for example Keras is very popular and having such higher level interface would not be useless. Of course when I'm building some sophisticated model I describe the data flow by myself. But people often run commonly used and well studied architectural patterns. For these needs writing a one liner instead of designing a class can be better.
Probably it worths to add a separate MultiRNN? But only if the overall design of the project is not against the usage of containers.

**Comment by apaszke** [comment]
I don't think we should add any additional functionality to `nn.Sequential` (we've probably should have only created `nn.ModuleList`), I think what @vlasenkov proposes is reasonable, but it's hard to get it right. For example your implementation assumes it works with LSTM-like modules that return a tuple of (output, state), but regular RNNs return just a single value that is both. I think we should also finally resolve #711

**Comment by vlasenkov** [comment]
@apaszke, for easy and automatic stacking of arbitrary models we can add some description of inputs and outputs to `Module` class, so it will be possible to explicitly read what an RNN eats and how many states it requires

**Comment by apaszke** [comment]
No, definitely not to `Module`. We can consider adding a base class for RNNs

**Comment by vlasenkov** [comment]
This issue should be resolved within #711 or after it.

**Comment by soumith** [comment]
closing this as it's better to dedup the issues. #711 does capture the situation.
