### ISSUE TITLE
Shape Analysis Error in Dtype

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#18823]
## 🐛 Shape analysis produces Wrong Dtype 

Shape analysis produces c10::ScalarType::Float and observed runtime type is c10::ScalarType::Double.

## To Reproduce

1. Check out #18813
1. Run python test/test_jit.py TestScript.test_rand

> ======================================================================
> ERROR: test_rand (__main__.TestScript)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test/test_jit.py", line 7940, in test_rand
>     self.checkScript(test_rand, ())
>   File "test/test_jit.py", line 457, in checkScript
>     check_expected=check_expected)
>   File "test/test_jit.py", line 467, in checkScript
>     outputs_ge = ge(*inputs)
> RuntimeError: 
> type->scalarType() == ten.scalar_type() ASSERT FAILED at ../torch/csrc/jit/register_special_ops.cpp:141, please report a bug to PyTorch. DIM_TENSOR_FAIL0x564ce374a0e8 (checkDimTensor at ../torch/csrc/jit/register_special_ops.cpp:141)

## Expected behavior

Analyzed dtype and runtime dtype are the same

**Comment by ailzhang** [comment]
cc: @suo Do you have any idea what's happening here?
