### ISSUE TITLE
Shape Analysis Bug in test_time_sequence_prediction

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#18822]
## 🐛 Shape Analysis Failure in number of Dimensions

Shape Analysis produces an incorrectly sized DimensionedTensorType in 
TestEndToEndHybridFrontendModels.test_time_sequence_prediction

## To Reproduce

1. Check out https://github.com/pytorch/pytorch/pull/18813
1. Run python test/test_jit.py TestEndToEndHybridFrontendModels.test_time_sequence_prediction

> ERROR: test_time_sequence_prediction (__main__.TestEndToEndHybridFrontendModels)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/data/users/eellison/pytorch/test/common_utils.py", line 167, in wrapper
>     fn(*args, **kwargs)
>   File "test/test_jit.py", line 11279, in test_time_sequence_prediction
>     export_import=False)
>   File "test/test_jit.py", line 501, in checkTrace
>     _force_outplace=_force_outplace)
>   File "/home/eellison/local/miniconda/envs/ninja/lib/python3.6/site-packages/torch/jit/__init__.py", line 664, in trace
>     var_lookup_fn, _force_outplace)
>   File "/home/eellison/local/miniconda/envs/ninja/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self._slow_forward(*input, **kwargs)
>   File "/home/eellison/local/miniconda/envs/ninja/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in _slow_forward
>     result = self.forward(*input, **kwargs)
> RuntimeError: 
> RuntimeError: 
> type->dim() == ten.dim() ASSERT FAILED at ../torch/csrc/jit/register_special_ops.cpp:140, please report a bug to PyTorch. DIM_TENSOR_FAIL0x564ce03acbf8 (checkDimTensor at ../torch/csrc/jit/register_special_ops.cpp:140)
> 

(The line of failure will change since the shape analysis pr has been updated)
## Expected behavior

No Disparities between Shape analysis and observed tensors in runtime

**Comment by ailzhang** [comment]
cc: @suo for shape analysis?

**Comment by eellison** [comment]
Rebased on master and this no longer throws
