### ISSUE TITLE
How to use libtorch api torch::nn::parallel::data_parallel train on multi-gpu

### ISSUE THREAD

**Issue by DDFlyInCode** [pytorch/pytorch#18837]

**Comment by auroraustc** [comment]
[#19540](https://github.com/pytorch/pytorch/issues/19540) This page may be helpful. I tried the code on this page using stable version of libtorch (v1.1.0). It runs well on single GPU(by setting CUDA_VISIBLE_DEVICES=0 manually), but got an error  `what():  data_parallel not supported without CUDA (data_parallel at /home/Software/libtorch/include/torch/csrc/api/include/torch/nn/parallel/data_parallel.h:171)` if I use two or more GPUs.

**Comment by dmagee** [comment]
I'm getting the same issue on a 4xGPU machine. The program from #19540 prints out "CUDA Available! Training on GPU" and then throws that exception above. If you modify the line:

        auto output = torch::nn::parallel::data_parallel(model, data);
to:
        auto output = model->forward(data); // Serial training 

It all works fine. I'm using:

Windows 10
Visual Studio 2017
Cuda 10
Latest NVIDIA driver (430.86)
libtorch-win-shared-with-deps-latest.zip from yesterday (19/6/19):
    https://pytorch.org/get-started/locally/ ->
    https://download.pytorch.org/libtorch/cu100/libtorch-win-shared-with-deps-latest.zip

I also tried the nightly at:

https://download.pytorch.org/libtorch/nightly/cu100/libtorch-win-shared-with-deps-latest.zip

But this seems to have some other issues and threw an exception:

Exception: max_pool2d_with_indices: internal error: all IntArrayRef sizes must be 2 (max_pool2d_with_indices_out_cuda_template at C:/w/1/s/windows/pytorch/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu:155)

**Comment by jclombar** [comment]
Hi, I am also trying to run the mnist_parallel example, without success so far...
A look at the code shows that data_parallel.h requires  USE_CUDA to be defined to actually scatter inputs and model.
But defining USE_CUDA (the rough way by adding add_definitions(-DUSE_CUDA) in CMakeLists.txt) leads to another error at compile time:
.../include/ATen/Parallel.h:47: error: ‘void at::parallel_for(int64_t, int64_t, int64_t, const F&) [with F = torch::nn::parallel::parallel_apply(std::vector<T>&, const std::vector<at::Tensor>&, const c10::optional<std::vector<c10::Device> >&) [with ModuleType = torch::nn::ModuleHolder<NetImpl>]::<lambda(int64_t, int64_t)>; int64_t = long int]’, declared using local type ‘const torch::nn::parallel::parallel_apply(std::vector<T>&, const std::vector<at::Tensor>&, const c10::optional<std::vector<c10::Device> >&) [with ModuleType = torch::nn::ModuleHolder<NetImpl>]::<lambda(int64_t, int64_t)>’, is used but never defined [-fpermissive]
 inline void parallel_for(
             ^~~~~~~~~~~~

Any idea ? How to define the required at::parallel_for() for the newly defined NetImpl ?

**Comment by dmagee** [comment]
I tried this again with the latest nightly and the example from #19540 works. However, it's really slow. it's actually slower on a multi-GPU machine than a single GPU machine (~7mins vs 1 min). On the 4xGPU machine all 4 GPUs appear to be used but the usage is no where near 100% (more like 2%).

**Comment by mruberry** [comment]
This issue seems to be a question more suitable for the PyTorch forums at https://discuss.pytorch.org/.

**Comment by bootpin** [comment]
Tried using data_parallel and it is much slower on multiple GPUs than on a single one. This is in line with what @dmagee reported. Looking though the code, it appears as if replicas of the modules are cloned and deleted on *every* iteration of training. Is there a way to use data_parallel and avoid this overhead?
