### ISSUE TITLE
How can I crop half using cifar10 images? 

### ISSUE THREAD

**Issue by wonchulSon** [pytorch/pytorch#18847]
I want to crop each cifar10 images half(0-15) and half(16-31) height.
32x32 -> 2x16x32  

I can't solve this with my code..
Because after crop like that, when I put the data in model, dataloder makes problem..

Thank you for your help.

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
