### ISSUE TITLE
[docs] Docs missing not in-place Variable.scatter and some other methods

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#1885]
Variables have copying versions:
- index_fill
- index_add
- index_copy
- scatter
- masked_scatter
- masked_fill
- masked_copy

while Tensors don't. Also these methods are not mentioned in docs.

**Comment by episodeyang** [comment]
I am affected by this issue. Just spend an hour or two trying to get variable.scatter to work. Feels like a complete waste of time since this could be something very straightforwardly documented.

Jumping around the source and seeing only error messages from the C level is also not helping.

**Comment by episodeyang** [comment]
Here is a working example for those looking for one

```python
import numpy as np
import torch
from torch.autograd import Variable

size = [2, 2]
n = 5

# show case scatter method on tensors
input = torch.FloatTensor(*size + [n]).zero_()
mask = torch.LongTensor(np.ones(size, dtype=np.int)).unsqueeze(dim=2).expand_as(input)
print(mask)
input.scatter_(-1, mask, n)
print(input)

# Now test scatter method on variables
input = Variable(torch.FloatTensor(*size + [n]).zero_())
mask = Variable(torch.LongTensor(np.ones(size, dtype=np.int)).unsqueeze(dim=2).expand_as(input))
print(mask)
input.scatter_(-1, mask, 5 * Variable(torch.ones(input.size())))
print(input)

```

**Comment by xssChauhan** [comment]
I would like to help with documenting these issues.

I shall start with adding appropriate docstrings to the functions by tracing their usage in the Tensor module.
This would be my first contribution to PyTorch. Would appreciate some guidelines.

**Comment by apaszke** [comment]
@xssChauhan thanks! However this task is a bit more complicated because of all the changes happening around Tensor/Variable, and the fact that we only list methods on Tensors at the moment. We'll fix that at some point, but I think we should just wait until then.
