### ISSUE TITLE
Request for integer support in functional.threshold

### ISSUE THREAD

**Issue by ThaHypnotoad** [pytorch/pytorch#1886]
`integers = Variable(torch.rand(10)*10).int()'
'print(F.threshold(integers,5,5))'

gives us this stack trace:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/torch/nn/functional.py", line 370, in threshold
    return _functions.thnn.auto.Threshold(threshold, value, inplace)(input)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/_functions/thnn/auto.py", line 110, in forward
    self._backend = type2backend[type(input)]
  File "/usr/local/lib/python3.5/site-packages/torch/_thnn/__init__.py", line 15, in __getitem__
    return self.backends[name].load()
KeyError: <class 'torch.IntTensor'>`

When intuitively I would think there'd be no issues with thresholding integers.

**Comment by fmassa** [comment]
You can probably use `torch.clamp` for that, right?

**Comment by ThaHypnotoad** [comment]
I suppose I could now that I know of it, and in fact perhaps it's base class hardTanh might be suited even better to my purposes.
Regardless though I would think that there are cases in which code that makes use of these two functions for the purpose that threshold was made for would look rather ugly. Is there a particular reason for why threshold is float only? or is it just something that never came up due to the existence of the other two functions?
For the moment though, I believe they will suffice.
However I can't seem to find the backend code for them. Could you point me in its direction so I can be sure of what it does?

**Comment by apaszke** [comment]
Yes. You can't compute derivatives over integers which is why autograd doesn't support non-floating point tensors.

**Comment by ThaHypnotoad** [comment]
> You can't compute derivatives over integers

With all due respect that doesn't sound quite right. Heck, in BNNs even bitwise operations have  defined derivatives.

And do you mean to say that autograd doesn't fully support them or at all? because it looks like at least for some basic cases I've tried gradients seem to be fine.

**Comment by apaszke** [comment]
I'm not aware of any techniques that define derivatives of functions over sets that have no limit points (e.g. all discrete spaces, including integers). Of course it's possible to define derivatives of approximations of bitwise ops (mathematically, bitwise ops have different semantics depending on what's your encoding), however you still need floating-point values to compute the gradients. In `torch.autograd`, the gradient has to be of a type matching the data used in forward computation, so we can't allow integer tensors there. Even if it doesn't crash, I won't guarantee that what you're seeing in `.grad` is correct (because it's undefined in this setting).

**Comment by ThaHypnotoad** [comment]
Got it. So autograd itself doesn't quite care what type it is as long as it matches what came in. I just shouldn't expect "stock" pytorch modules to be defined for operations that aren't floating point? That is to say if I define an integer gradient for a custom operation I should be fine?

**Comment by apaszke** [comment]
I guess? I think the most important assumption we make about functions is that if you ever return one of the inputs unmodified then it would mean that the grad of output of this function w.r.t. this input is all 1s. I can't think of anything else (apart from the linearity of derivative).

**Comment by ThaHypnotoad** [comment]
Alright. Thank you very much for taking the time to explain!
