### ISSUE TITLE
use bash script instead of .bat to simplify failure propagation

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#18861]
> @peterjc123, due to this pitfall, I'm dabbling with replacing .bat files with Bash scripts. [...] Do you think this is a practical direction?

Yes, it is good. But we should remain the env configuration part as batch files, otherwise, it won't work.

_Originally posted by @peterjc123 in https://github.com/pytorch/pytorch/pull/18694#issuecomment-479724341_

**Comment by peterjc123** [comment]
Closed via https://github.com/pytorch/pytorch/pull/18756.
