### ISSUE TITLE
torch.autograd.grad() not present

### ISSUE THREAD

**Issue by euler16** [pytorch/pytorch#1888]
when I try to use torch.autograd.grad() I get the error :- "AttributeError: 'module' object has no attribute 'grad'".
I checked the the following path in this repository 'torch/autograd/__init__.py' and found that the same file in my system is different. It has only backward() implemented. I reinstalled PyTorch (using pip version 0.1.12) and got the same result

**Comment by albanD** [comment]
Hi,

`grad()` is only available from source right now. It will be present in the next release.

**Comment by zhengziqiang** [comment]
What can I do to solve this problem?

**Comment by fmassa** [comment]
You can install from source (instructions in the readme), or wait until the next release

**Comment by udion** [comment]
I installed pytorch-gpu from conda, I am getting the same error, is it resolved yet?
