### ISSUE TITLE
Support for einsum notation

### ISSUE THREAD

**Issue by rockt** [pytorch/pytorch#1889]
As mentioned [here](https://discuss.pytorch.org/t/einstein-summation-in-pytorch/2492), support for [einsum notation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.einsum.html) would be useful. It's in fact a feature that I am missing most after transitioning from TensorFlow. What's needed for the implementation is parsing the einsum string and deciding which PyTorch modules to use for which cases as well as automatically reshaping input tensor back and forth like done [here](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/python/ops/special_math_ops.py#L85).

**Comment by vlasenkov** [comment]
Yeah, Pytorch lacks this. I can implement the feature

**Comment by soumith** [comment]
@vlasenkov that'd be great. please go ahead.

**Comment by MadcowD** [comment]
Any progress @vlasenkov ?

**Comment by vlasenkov** [comment]
@MadcowD unfortunately I'm not able to contribute now, you can check the PR and complete the feature
