### ISSUE TITLE
Multipling long tensor by float scalar

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#18913]
Muplipying long tensor by a float scalar results in a long tensor, leading to information loss:

```
In [2]: t = torch.LongTensor([77])

In [3]: t
Out[3]: tensor([77])

In [4]: t * 0.1
Out[4]: tensor([0])
```
I've found this behavior very surprising and I'm wondering if it's intended, was already discussed, etc.

**Comment by fmassa** [comment]
Yes, this is a known behavior and here is a proposal to improve (fix) it https://github.com/pytorch/pytorch/issues/9515

Closing this as a duplicate.
