### ISSUE TITLE
binary_cross_entropy does not implement double-backwards

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#18945]
## 🚀 Feature

Implement the double backwards for `binary_cross_entropy`.

## Motivation

Most of the losses support double-backwards, but `binary_cross_entropy` seems not to support it.

## Pitch

```python
x = torch.rand(10, 4, requires_grad=True)
y = torch.rand((10, 4))
loss = F.binary_cross_entropy(x, y)
loss2 = torch.autograd.grad(loss, x, create_graph=True)

loss2[0].sum().backward()
```
raises
```python
RuntimeError                              Traceback (most recent call last)
~/tst7.py in <module>()
----> 1 a[0].sum().backward()

~/anaconda3/lib/python3.6/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    105                 products. Defaults to ``False``.
    106         """
--> 107         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    108
    109     def register_hook(self, hook):

~/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     91     Variable._execution_engine.run_backward(
     92         tensors, grad_tensors, retain_graph, create_graph,
---> 93         allow_unreachable=True)  # allow_unreachable flag
     94
     95

RuntimeError: derivative for _thnn_binary_cross_entropy_backward is not implemented
```

## Alternatives

Note that `binary_cross_entropy` can be very easily implemented in Python as follows:
```python
def binary_cross_entropy(x, y):
    loss = -(x.log() * y + (1 - x).log() * (1 - y))
    return loss.mean()
```
which enables double-backprop.

A simple way of implementing it would be to just add an entry for the double-backwards in https://github.com/pytorch/pytorch/blob/master/torch/nn/_functions/thnn/auto_double_backwards.py.

Another (potentially desired) way would involve moving the loss to ATen, and writing the double-backwards as well.

Originally reported by @f-t-s

**Comment by aditya1702** [comment]
@fmassa Is anyone working on this?

**Comment by fmassa** [comment]
@aditya7fb not that I know of, so feel free to take this on!

**Comment by gchanan** [comment]
assigning myself for safe keeping.

**Comment by gchanan** [comment]
This has been fixed.
