### ISSUE TITLE
CUDNN RNN BAD PARAM

### ISSUE THREAD

**Issue by mythreyi22** [pytorch/pytorch#18946]
Hi all, 
I have written a standalone code for RNN with cudnn. I am getting bad param when executing this code.The tensors dimension requirements are verified wrt to cudnn documentation. Please find the attachment.
Thanks in advance!

[RNN_cuda.txt](https://github.com/pytorch/pytorch/files/3047516/RNN_cuda.txt)

**Comment by soumith** [comment]
this is not CuDNN support :)
Because this is not related to the pytorch framework, i'm closing the issue.
