### ISSUE TITLE
Non-repeatable model output using pytorch network

### ISSUE THREAD

**Issue by S-Ellis** [pytorch/pytorch#18947]
## 🐛 Bug

There are two related issues:

1. repeatedly pulling parameters from a pytorch model results in non-identical parameter values.
2. repeatedly running a pytorch model (CPU) on the same input does not produce identical outputs.

## To Reproduce

This minimum working example python script replicates the results:

```
import numpy as np 
import matplotlib.pyplot as plt 
import torch

device = torch.device('cpu')

# function to get all the params from a pytorch model
def getParams(model):
    a = list(model.parameters())
    b = [a[i].detach().cpu().numpy() for i in range(len(a))]
    c = [b[i].flatten() for i in range(len(b))]
    d = np.hstack(c)

    return d

# set up a simple model (9 params)
testModule = torch.nn.Conv2d(1, 1, kernel_size = (3, 3), bias = False, stride = 1, padding = 1).double()
torch.nn.init.normal_(testModule.weight, mean=0, std=1)
testModule = testModule.eval()

# set up a dummy input
patch = torch.from_numpy(np.random.randn(1,1,80,80).astype('double')).to(device)

# apply the model 100 times
testVals = []
testParams = []
testModuleOut = []
for ii in range(100):
    testParams.append(getParams(testModule))
    testModuleOut.append(testModule(patch).cpu().detach()[0,:,:,:].numpy())

testParams = np.stack(testParams)
testModuleOut = np.stack(testModuleOut)

# view the variation of the model parameters and the output values
plt.figure()
plt.plot(np.std(testParams,axis=0))
plt.xlabel('Parameter index')
plt.ylabel('Standard deviation over runs')

plt.figure()
plt.plot(np.std(testModuleOut,axis=0).ravel())
plt.xlabel('Output index')
plt.ylabel('Standard deviation over runs')

```
## Expected behavior

The standard deviations of the outputs is expected to be zero if the results were repeatable. In particular, copying the network parameters multiple times should yield exactly identical results (rather than machine precision values).

## Actual output

The standard deviations are non-zero, and change with every run of the script. Example output graphs show this behaviour:

![std_outputs](https://user-images.githubusercontent.com/45965889/55624016-8fc3cf80-579c-11e9-823b-7cd90ca296b1.png)
![std_params](https://user-images.githubusercontent.com/45965889/55624017-8fc3cf80-579c-11e9-978f-f016e2f51581.png)

 - PyTorch Version 1.0.1:
 - OS Linux:
 - Python version 3.6:

**Comment by fmassa** [comment]
This is expected, and happens because we use multiple threads to compute the result of convolution.

The underlying issue is that floating point math is not commutative, and when using multiple threads to perform a computation the order of accumulation is not guaranteed.

**Comment by S-Ellis** [comment]
Thanks for the answer. That makes sense for the output varying between runs, but why do the model parameters vary? I would expect that since they are just being pulled from RAM they should be identical every time?

Also, can this behaviour aggregate throughout a network, causing significant changes in the output of more complex models?

**Comment by fmassa** [comment]
@S-Ellis well, the problem regarding the model parameters is probably wrt your plotting (which uses `std`), not that the weights are changing.

**Comment by S-Ellis** [comment]
I don't understand, is there some reason `np.std` would not return zero if the values are identical? I'm aware that for float32 values numpy's `std` can be unreliable, but my values are all double precision.

**Comment by S-Ellis** [comment]
@fmassa Okay, after a quick check I find that you're right and numpy's `std` does not output the zero I expect: 

```
arr = np.zeros((100,1),dtype='double')
arr.fill(np.random.randn(1)[0])
print(np.std(arr))
```

My ultimate problem was that I found a pytorch model I had was not outputting repeatable results and I thought I'd isolated the problem, but it seems not. Back to the drawing board for me!

Thank you for your help.
