### ISSUE TITLE
torch.equal() bug - when using randn

### ISSUE THREAD

**Issue by Ashok93** [pytorch/pytorch#18954]
## To Reproduce

1. torch.randn(5) # `torch.tensor([-0.5328,  0.2653, -0.1581, -0.1845, -1.3954])`
1. min = t.min() # `tensor(-1.3954)`
1. t2 = torch.tensor(-1.3954) # `tensor(-1.3954)`
1. torch.equal(t2, min) # `False`

But if I donot use `torch.randn` and use a defined tensor like `torch.tensor([-0.5328,  0.2653, -0.1581, -0.1845, -1.3954])` and repeat the same, I get `torch.equal()` as `True`

## Expected behavior
As in documentation(https://pytorch.org/docs/stable/torch.html#torch.equal), `torch.equal()` must check if two tensors have the same size and elements.

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Quadro 2000
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 384.130
cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.16.1
[pip3] torch==1.0.1.post2
[pip3] torchfile==0.1.0
[pip3] torchvision==0.2.1
[conda] Could not collect

**Comment by SsnL** [comment]
Not a bug. `tensor(-1.3954)` is the output with limited precision, for obvious cleanness reasons. See https://pytorch.org/docs/master/torch.html#torch.set_printoptions
