### ISSUE TITLE
Allow reshape(-1) to behave like view(-1) and resize(-1) and avoid RuntimeError

### ISSUE THREAD

**Issue by HaleTom** [pytorch/pytorch#18984]
## 🚀 Feature

Allow `tensor.reshape(-1)` to behave like `view(-1)` and `resize(-1)`, avoiding the `RuntimeError`.

## Motivation

Consistency and efficiency.

### Consistency

* `t.view(-1)` [won't copy memory, but may not work depending on original size and stride](https://pytorch.org/docs/master/tensors.html?highlight=view#torch.Tensor.view)

* `t.reshape(-1)` works [but may copy memory](https://pytorch.org/docs/master/torch.html#torch.reshape)

* `t.resize(-1)` gives a `RuntimeError` (`torch 1.0.1.post2`):

    > `RuntimeError: requested resize to -1 (-1 elements in total), but the given tensor has a size of 2x2 (4 elements). autograd's resize can only change the shape of a given tensor, while preserving the number of elements.`

### Efficiency

[The Tensor.resize_()` documentation](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.resize_) says:
> If the number of elements is smaller, the underlying storage is not changed. Existing elements are preserved but any new memory is uninitialized.

The size equality case is not mentioned, but I assume that the underlying storage is also unchanged in this case.  I'd welcome confirmations or refutations.

## Pitch

I expect `t.resize(-1)` to *not* give a `RuntimeError`, but instead to return a flattened tensor, just like `view(-1)` and `resize(-1)`.

## Alternatives

The current work around for using `resize(-1)` is:

* `t.resize(t.numel())` will work in all cases, and is [guaranteed not to copy memory](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.resize_)

This is ugly and cumbersome.

## Additional context

[Prior StackOverflow art](https://stackoverflow.com/a/55546874/5353461)

**Comment by HaleTom** [comment]
If this feature is approved, I would be willing to look into a PR.

How does the project measure feature approval?

**Comment by fmassa** [comment]
I'd say that `tensor.resize_` should be used with care, and it's semantics are *not* the same as those from `reshape` / `view`.
Indeed, `tensor.resize_` can allocate new memory, and the newly allocated elements are filled with whatever is in memory, which is most probably not what the user wants.
Also, if the tensor is not contiguous, doing a `resize` will give completely unexpected results to the user, as there won't be any failure, but the results will correspond to those from a different part of the tensor.

Here is an example:
```python
In [9]: a = torch.arange(9).reshape(3, 3).t()

In [10]: a
Out[10]:
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [11]: a.resize_(3)
Out[11]: tensor([0, 1, 2])
```

Numpy's [behavior is safer](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.resize.html#numpy.ndarray.resize).
It forbids non-contiguous tensors to be resized, and do not let tensors with references to be resized.
But it doesn't allow for `-1` values in its dimension either.
```python
a = np.random.rand(3, 3)
a.resize((-1,))
```
gives
```python
<ipython-input-39-bdfbda8c880d> in <module>()
----> 1 a.resize((-1,))

ValueError: negative dimensions not allowed
```

---


That being said, we might want to consider making the behavior of `resize` to follow more closely numpy's behavior, once we remove Storage from Tensor though.

**Comment by SsnL** [comment]
> t.view(-1) won't copy memory, but may not work depending on original size and stride
> t.reshape(-1) works but may copy memory

Yes but `reshape` only does necessary copying, ie, only copying when the underlying data can not be viewed as a flattened tensor.

Just remember, not all tensors can be directly viewed as a flattened tensor. Some have to be copied.

Long story short, use `reshape`, and avoid `resize` as @fmassa mentioned because it is definitely what you want. `resize` doesn't copy, but it doesn't give correct values in cases where `reshape` copies.
