### ISSUE TITLE
pyinstaller with pytorch

### ISSUE THREAD

**Issue by AceCoooool** [pytorch/pytorch#1898]
I want to use `pyinstaller  my.py` (my.py include the code of `import torch`), when run `./some` (after build to exe file), there is an error of **unable to find torch_shm_manager** 
The main problem the torch's file is in '/mypythonloc/site-packages/torch', but the build exe file want to find it in the '/some.py_location/dist/lib'

Could anyone who meet it and deal with it? thank you~

**Comment by AceCoooool** [comment]
I use a very silly method to solve it, add the torch package to my execute path.

**Comment by minghuatang** [comment]
Can you talk about the solution in more detail? Thanks in advance!

**Comment by pandorana** [comment]
@minghuatang He has put his solution in [this issue](https://github.com/pyinstaller/pyinstaller/issues/2666).

**Comment by iamtodor** [comment]
@minghuatang please take a look at my [detailed solution](https://github.com/pyinstaller/pyinstaller/issues/2666#issuecomment-370789381)
