### ISSUE TITLE
Wish that pytorch can adjust its computation according to GPU memory upper bound.

### ISSUE THREAD

**Issue by cjliux** [pytorch/pytorch#18995]
## 🚀 Feature

Wish that pytorch can adjust its computation according to GPU memory upper bound.

## Motivation

It is frustrating when I have several machines that holds GPUs of different memory sizes. Usually, I would like to implement model in a time efficient way while this will cause high GPU memory usage. However, in this way, some machines with lower GPU memory capacity will be unable to run the models because of OOM exception. In such case, it is obvious that there exist some method which can slow down the computation while lower the GPU memory usage requirement. So I just hope that pytorch can have such a feature.

## Possible Solution

Some global coordinators can be implemented with data structures like queue to ensure that the GPU memory usage will not exceed some upper limit at any time, which will automatically make balance between time and memory.

**Comment by ezyang** [comment]
It is not as automatic as you asked for here, but I believe torch.utils.checkpoint is what you are looking for.

**Comment by soumith** [comment]
About a global GPU memory cap for a PyTorch process, we are not planning to implement that.

**Comment by sandias42** [comment]
#18626
