### ISSUE TITLE
Intra-operator parallelism settings in PyTorch

### ISSUE THREAD

**Issue by ilia-cher** [pytorch/pytorch#19001]
(This issue is mainly to clarify how PyTorch sets the number of OMP and MKL threads and fix some discrepancies. For the bigger context on parallelism work please refer to https://github.com/pytorch/pytorch/issues/19002)

As of the moment PyTorch largely relies on OpenMP and MKL/MKL-DNN (use OpenMP) to do intra-op (i.e. within an op) parallelization on CPU.

First, let's consider first how OpenMP and MKL determine number of threads to use.
For the practical purposes, we can assume that OpenMP uses the following steps (OMP dynamic mode is off by default):
1. Checks whether the number of threads was set explicitly with `omp_set_num_threads(n)`;
2. Checks value of env. variable `OMP_NUM_THREADS`, if set;
3. Uses default value, which is typically number of physical threads in the system.

MKL goes through the following steps:
1. Checks whether the number of threads was set explicitly with `mkl_set_num_threads_local(n)`
2. Same check for `mkl_set_num_threads(n)`
3. Then it checks whether we have env. variable `MKL_NUM_THREADS` set
4. If all of the steps above failed, MKL uses number of OMP threads determined by the steps above.

**Note**: MKL has a dynamic mode to determine number of threads which is set through `mkl_set_dynamic(bool)` and `MKL_DYNAMIC` env. variable. By default it is turned on. In this mode MKL is able to change number of threads regardless of user setting. In practice it usually means that the number of threads is capped at the _number of physical cores_ in the system.
**Note**: Changing one of the parameters (e.g. number of OMP threads and/or dynamic mode) later during the execution _will_ affect number of MKL threads used. E.g. if user did not use `mkl_set_num_threads*` functions and did not use `MKL_NUM_THREADS` variable, then MKL would use current number of OMP threads, changing number of OMP threads would result in a different `mkl_get_max_threads()` output. For the same reason, even if user called `mkl_set_num_threads(n)` with n>#cores, `mkl_get_max_threads` would return #cores. If user then calls `mkl_set_dynamic(false)`, the return value of `mkl_get_max_threads` changes to `n`.

Now, let's consider how PyTorch sets number of OMP and MKL threads:
1. `torch` module is initialized in `initModule` in `torch/csrc/Module.cpp`, this function calls `THInferNumThreads` and `at::init`.
**Note**: `THInferNumThreads` is also called by each autograd thread during autograd initialization.
2. `THInferNumThreads` executes `omp_set_num_threads(mkl_get_max_threads())` (if both OMP and MKL are present)
3. `at::init` reads `OMP_NUM_THREADS` and `MKL_NUM_THREADS` env. variables (in order, if present) and calls `at::set_num_threads` which saves the value in a global atomic variable, accessible through `at::get_num_threads`
4. PyTorch also provides an API to get/set number of intra-op threads: `torch.get_num_threads` and `torch.set_num_threads`.
5. `torch.get_num_threads` simply returns `omp_get_max_threads` (or 1 if there's no OMP)
6. `torch.set_num_threads(n)` calls `omp_set_num_threads(n)` followed by `mkl_set_num_threads(n)` followed by `mkl_set_dynamic(false)`
7. The reason for turning off dynamic mode is explained in https://github.com/pytorch/pytorch/issues/13757
8. `torch.set_num_threads(n)` also updates ATen internal variable with `at::set_num_threads`.

Considering all of the above:
1. If both OMP and MKL are present, PyTorch calls `omp_set_num_threads(mkl_get_max_threads())` first. The effect of this call is:
   - If user sets both `OMP_NUM_THREADS` and `MKL_NUM_THREADS` - `OMP_NUM_THREADS` is ignored
   - Let's say there's an environmental variable set to `N`, e.g.:
`OMP_NUM_THREADS=N` or
`MKL_NUM_THREADS=N` or
`OMP_NUM_THREADS=<ignored> MKL_NUM_THREADS=N`
   - Then both OMP and MKL are set to `min(N, #cores)` or `N` if `MKL_DYNAMIC=FALSE` is set
   - If there're no env. variables set, then OMP and MKL are set to `#cores`, or `#phys_threads` if `MKL_DYNAMIC=FALSE` is set
2. If there's only OMP (no MKL), then number of OMP threads is simply `OMP_NUM_THREADS` or `#physical_threads`, any MKL variables are ignored.
3. During the initialization, Aten global variable (checked with `at::get_num_threads`) is set to the value specified in `MKL_NUM_THREADS` or `OMP_NUM_THREADS` (if `MKL_NUM_THREADS` is not present) or is left with its initial value `-1` (if env. variables are not set). Note, that `MKL_NUM_THREADS` is not necessarily the number of threads used by MKL. Also note, that we check these variables _without_ checking first if OpenMP or MKL are used.
4. Subsequent calls to `torch.set_num_threads(N)` will set both OMP and MKL number of threads, as well as Aten variable, to `N`.
The first call to `torch.set_num_threads` also sets MKL dynamic mode to `false`. This might potentially change number of threads used further if some user code explicitly calls `mkl_set_num_threads`, but we _strongly encourage_ users not to use parallelization libraries explicitly and always rely on PyTorch API.

To move further with parallelism work we propose to implement the following changes:
1. Move all library specific calls that initialize number of OMP and MKL threads into `ATen/Parallel.h`, redirect `torch.get/set_num_threads` to `ATen/Parallel.h` implementation.
2. Remove a separate implementation of `at::get/set_num_threads` in `ATen/CPUGeneral.cpp` (as an implementation detail in `ATen/Parallel.h` we might use an internal variable to cache number of threads and avoid calls to OMP). This also fixes a potential issue with uninitialized number of threads and discrepancy between `at::get_num_threads` and `torch.get_num_threads` immediately after initialization.

**Comment by cpuhrsch** [comment]
I'm confused by the distinction between cores and threads. Usually the number of threads is twice the number of cores (due to Hyper-threading). Which one is it?

**Comment by ilia-cher** [comment]
@cpuhrsch that's the meaning used here, number of physical threads = twice the number of cores (if HT is enabled)
