### ISSUE TITLE
I have a piece of code that is written in LUA and  I want to know what is the pytorch equivalent of the code.?How do I implement these lines in pytorch .. Can somebody help me with it? The code is mentioned in the comment

### ISSUE THREAD

**Issue by AshishRMenon** [pytorch/pytorch#19012]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by AshishRMenon** [comment]
real_ctx[{{},{1},{},{}}][mask_global] = 2 * 117.0/255.0 - 1.0 
real_ctx[{{},{2},{},{}}][mask_global] = 2 * 104.0/255.0 - 1.0 
real_ctx[{{},{3},{},{}}][mask_global] = 2 * 123.0/255.0 - 1.0 
input_ctx:copy(real_ctx)

**Comment by albanD** [comment]
Hi,

As you see in the template above, you should use the [forum](https://discuss.pytorch.org/) for such questions.
Thanks
