### ISSUE TITLE
How to select GPU programmatically in code

### ISSUE THREAD

**Issue by magic282** [pytorch/pytorch#1901]
Hi,

I found this https://github.com/pytorch/examples/pull/73/files to set an env variable to choose GPU.
Is there a way to manually choose GPU programmatically in code? Thanks.

**Comment by avijit9** [comment]
```
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="1"
```

Are you looking for this?

**Comment by bartolsthoorn** [comment]
Are you looking for this http://pytorch.org/docs/tensors.html?highlight=cuda#torch.Tensor.cuda ?

In short, when you move a tensor to the GPU with `.cuda()` you can set the destination (which GPU) by simply passing an integer. To use the first GPU, use `.cuda(0)`. The same can be done with everything else CUDA related.

This is also useful to check out, CUDA semantics: http://pytorch.org/docs/notes/cuda.html

**Comment by magic282** [comment]
Thank you @avijit9 @bartolsthoorn , your answers solved my issue.

**Comment by motiur** [comment]
@avijit9 How to add multiple gpu's : 
Is it os.environ["CUDA_VISIBLE_DEVICES"]="1,2"
I am just guessing.

**Comment by ezyang** [comment]
Please ask your question in the support forum https://discuss.pytorch.org/

**Comment by moonlightlane** [comment]
`torch.cuda.set_device(device_id)`
