### ISSUE TITLE
_write_ninja_file_and_build calls check_compiler_abi_compatibility with the wrong default compiler name on Windows

### ISSUE THREAD

**Issue by szali** [pytorch/pytorch#19017]
## 🐛 Bug

When compiling a c++ extension on Windows, in cpp_extension.py, _write_ninja_file_and_build calls check_compiler_abi_compatibility with the default argument "c++" if CXX is not set:

    check_compiler_abi_compatibility(os.environ.get('CXX', 'c++'))

 At another place (in the _check_abi function) the default is correctly set as "cl":

        elif IS_WINDOWS:
            compiler = os.environ.get('CXX', 'cl')
        else:
            compiler = os.environ.get('CXX', 'c++')
        check_compiler_abi_compatibility(compiler)

_write_ninja_file_and_build should also use the default value "cl" if IS_WINDOWS.

## To Reproduce

Try to compile a C++ extension on Windows without setting CXX.

## Expected behavior

cl is selected as the compiler for checking the ABI.

## Environment

Windows, without setting the CXX envvar.

**Comment by soumith** [comment]
cc: @peterjc123
