### ISSUE TITLE
torchvision.transforms.functional.normalize breaks with CUDA tensors

### ISSUE THREAD

**Issue by jadrs** [pytorch/pytorch#19028]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

torchvision.transforms,functional.normalize breaks with cuda tensors

I guess lines 206 and 207 of functional.py should be something like this:

    mean = torch.tensor(mean, dtype=torch.float32, device=tensor.device)
    std = torch.tensor(std, dtype=torch.float32, device=tensor.device)

otherwhise mean and std will be CPU tensors by default, leading to an exception when calling sub_:

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.
Traceback (most recent call last):
  File "detection_flow.py", line 351, in <module>
    main(args)
  File "detection_flow.py", line 339, in main
    img = denormalize(img[0])
  File "/home/jsanchez/workspace/detection_flow_debug/transforms.py", line 129, in __call__
    return super().__call__(input)
  File "/home/jsanchez/.local/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/jsanchez/.local/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source): -
- OS: Ubuntu 18.04
- PyTorch version: 1.0.1
- Python version: 3.7
- CUDA/cuDNN version: 10.0
- GPU models and configuration: -
- GCC version (if compiling from source): -
- CMake version: -
- Versions of any other relevant libraries: -

**Comment by fmassa** [comment]
This has been fixed in torchvision master
