### ISSUE TITLE
Python math module support

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#19026]
## [jit] Python math module support

The python math module is often used in numerical code. It would be nice to support it. I've divided up the math module into relatively higher priority and lower priority functions below. 

Higher-pri:

- [x] acos
- [x] asin
- [x] atan
- [x] atan2
- [x] cos
- [x] fmod
- [x] modf
- [x] remainder
- [x] sin
- [x] tan 
- [x] ceil 
- [x] exp
- [x] floor
- [x] log
- [x] log10
- [x] log1p
- [x] log2
- [x] pow
- [x] sqrt

Lower-Pri

- [x] asinh
- [x] atanh
- [x] copysign 
- [x] acosh
- [x] degrees
- [x] erf
- [x] erfc
- [x] expm1
- [x] fabs
- [x] factorial
- [x] frexp
- [ ] fsum
- [x] gamma
- [x] gcd
- [ ] isclose
- [x] isfinite
- [x] isinf
- [x] isnan
- [x] ldexp
- [x] lgamma
- [x] radians
- [x] sinh
- [x] cosh
- [x] tanh
- [ ] trunc
- [x] hypot

cc @ezyang @gchanan @zou3519 @jerryzh168 @suo

**Comment by eellison** [comment]
You'll need to add the math function to our builtin_table in `torch/jit/__init__.py` (like with math.floor), add an implementation for the int and float version of the function in `register_prim_ops`, and then add tests in test_jit.py. Tag me and @driazati as reviewers

**Comment by soumith** [comment]
@hikjik it looks like not. Pick some of the functions you intend to work on first, and declare here, and then go for it.

**Comment by TheCodez** [comment]
I'll implement  `asin`, `atan`, `atan2`, `cos`, `sin`, `tan`.

**Comment by hikjik** [comment]
I work on ceil, exp, log, log1p, log2, log10, pow, sqrt.

**Comment by kalpanki** [comment]
I would like to pick up the left over functions listed under "Higher-pri" namely: `fmod`, `remainder`, `modf`  and `acos` if you guys are happy. That hopefully covers all the functions listed under "Highper-pri".

**Comment by lhendre** [comment]
I would like to pick up the left over functions listed under "low-pri" namely: isnan, asinh, atanh and cosh, sinh, tanh if that works

**Comment by eugenekoran** [comment]
I would like to work on `copysign`, `erf`, `erfc`, `expm1`,  'fabs`, `gamma`, `gcd`, `lgamma`

**Comment by shiv-gpt** [comment]
Hi I would like to work on this issue. Are there still any functions left? Also, I am a first time contributor so is there any other issue i can work on if this one is done. Thanks!

**Comment by Chillee** [comment]
Since the priorities on these ops were promoted, I'm gonna take all of the "higher-pri" ones, and potentially the "lower-pri" ones as well.

**Comment by lhendre** [comment]
I would just check the open PRs to see what the status are on them before you start, I know I have some of the lower ones under review for example

**Comment by Chillee** [comment]
The internal macros have changed a lot over the last week, and since the priorities on these ops were promoted, I'm going to submit PR's for all the ops (except `fsum`, `trunc`, and `isclose`) in order to avoid churn and finish off this module.

Thanks to @lhendre (for the ops and ideas on how to implement a generalized test framework) and to @kalpanki for his implementations of `fmod, modf, remainder, and acos`. Sorry to steal these ops away from you :'(

**Comment by lhendre** [comment]
@Chillee Could you try to take a look at the existing ones?  Mine appears to be close to done and it may make more sense to work on what is already implemented of stealing the ops and ideas.
