### ISSUE TITLE
C++ torch::Tensor serialization

### ISSUE THREAD

**Issue by SPark9625** [pytorch/pytorch#19025]
## 🚀 Feature

I am building an application where there's basically a producer and a consumer of `std::tuple<torch::Tensor, torch::Tensor>`s.

The producer has to run a neural network to produce the tensors, and the consumer has to train from the output of the producer, occasionally checkpoint to file, which the producer then occasionally reads and updates its own network with the new one. (I'm implementing Alpha Zero)

The only problem is, it seems like pytorch is not thread safe in this regard. Even when I assign two separate (but identical) networks to producer and consumer, I get an error when I run the two concurrently.

Therefore, I'm trying to separate the two as processes. I'm trying to use a message queue so that the producer can send its output to the consumer. However, now I don't know how to serialize `torch::Tensor`s. I think it should be doable with `torch::serialize::InputArchive` and `torch::serialize::OutputArchive`, but the C++ API reference wasn't too kind for me to understand.

Since I wasn't too sure if this is doable or not, I decided to submit as a feature request.

**Comment by soumith** [comment]
cc: @yf225 @gchanan

**Comment by driazati** [comment]
fyi we are working on something similar in #18003 for the JIT

**Comment by yf225** [comment]
@SPark9625  `torch::save` and `torch::load` should be the functions you are looking for (https://pytorch.org/cppdocs/api/function_namespacetorch_1a99dc9f736064b2179cc58e6436f7a021.html). An example:
```
#include <torch/torch.h>
#include <iostream>

int main() {
  auto tensor = torch::ones({3, 4});
  std::stringstream stream;
  torch::save(tensor, stream);

  torch::Tensor tensor2;
  torch::load(tensor2, stream);

  std::cout << tensor2 << std::endl;
}
```

**Comment by mrshenli** [comment]
#19677 supports serializing a vector of tensors.

**Comment by gchanan** [comment]
should this be closed now that you can serialize a vector of tensors?

**Comment by SPark9625** [comment]
Cool!! I just checked that I can both save and load `torch::Tensor`s and `std::vector<torch::Tensor>`s with the latest macOS libtorch! Closing this now :)
