### ISSUE TITLE
How to reproduce a torch RNN net in pytorch

### ISSUE THREAD

**Issue by Andybert** [pytorch/pytorch#1903]
I need to Reproduce the [torch net](https://github.com/Andybert/torch-and-pytorch/blob/master/torch%20net) in pytorch, especially the RNN layer part. 
and this is my [pytorch net](https://github.com/Andybert/torch-and-pytorch/blob/master/pytorch%20net)
when I run it, it produce an error message 
RuntimeError: matrices expected, got 1D, 2D tensors at /b/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:1232
and the error code is 
x7 = self.rnn(x6)
anyone helps me? Thanks!

**Comment by soumith** [comment]
please use https://discuss.pytorch.org/
