### ISSUE TITLE
Support __get_state__/__set_state__ for JIT serialization

### ISSUE THREAD

**Issue by dzhulgakov** [pytorch/pytorch#19030]
## 🚀 Feature
For custom C classes or for complex modules in JIT, there needs to be ability to supply customer serialization code.

## Motivation

We want to support custom opaque representations with the ability to serialize them. This is pretty important for opaque optimized layouts in inference (e.g. when using fbgemm), currently we use a hack with pack/unpack: https://github.com/pytorch/pytorch/blob/master/torch/jit/quantized.py#L27

This functionality will also be useful for custom C class bindings which would need to be serialized as well.

## Pitch

Proposal is to implement get_state/set_state similarly how they are handled in pickle: one can return any value (`IValue`) that will be serialized and later passed to `__set_state__` for deserialization.

```python
class MyLayerPacked(torch.nn.Module):
    # same as before
    def __init__(self, original: MyLayer):
        self.packed_weight = self.__pack__(original.weight) # ByteTensor with pointer
    def forward(self, x):
        return torch.my_mm_fast(self.packed_weight, x)
    # it has to be script method to work in C++
    @torch.jit.script_method
    def __getstate__(self):
        return {'weight': torch.unpack_from_my_mm(self.packed_weight)}
    def __setstate__(self, state):
        # attribute mutability is required here
        self.packed_weight = torch.pack_for_my_mm(state['weight'])
```

## Alternatives

Instead of following Pickle style we can define some other interface for it

**Comment by driazati** [comment]
Fixed in #20242
