### ISSUE TITLE
[Feature Request] sorted_input for torch.unique

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#19045]
Is it good to add a `sorted_input` to `torch.unique`?

Current cuda implementation always sort the input tensor first. But sometimes the input tensor is guaranteed to be already sorted. Sorting is O(n*logn), which is likely to be the most time consuming part of the whole computation, and it would be nice if we allow user to skip this part.

`torch.unique` with `sorted_input=True` would resemble `thrust::unique` and only remove the consecutive duplicate elements.

It might be better to name it `consecutive` instead of `sorted_input`.

**Comment by zasdfgbnm** [comment]
My use case is, I need to first sort a tensor to get the sorted values and indices. The indices would be used later somewhere, and the values would be used an input to a unique to get unique values and count. The benchmark shows that, the two most time consuming part of my function is the unique and sort.

**Comment by soumith** [comment]
i think it's a good idea, and I think `sorted_input` sounds fine.
