### ISSUE TITLE
[CUDNN] Crash when putting in 3x1280x720 tensor in to specific model

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#19095]
## 🐛 Bug

I changed the size of a tensor input so that it was 1280x720 where normally it is dynamic size. Other sizes all seem to work but I have not done a thorough test.

The model was traced in python and loaded via libtorch in C++.

Stack trace is as follows:
```>	torch.dll!torch::jit::InterpreterStateImpl::handleError(std::basic_string<char,std::char_traits<char>,std::allocator<char> > && error_msg, bool is_jit_exception) Line 750	C++
 	torch.dll!`torch::jit::InterpreterStateImpl::runImpl'::`1'::catch$20() Line 719	C++
 	vcruntime140d.dll!00007ffe63321030()	Unknown
 	vcruntime140d.dll!00007ffe6332544a()	Unknown
 	ntdll.dll!00007ffe8e29ed63()	Unknown
 	torch.dll!torch::jit::InterpreterStateImpl::runImpl(std::vector<c10::IValue,std::allocator<c10::IValue> > & stack) Line 682	C++
 	torch.dll!torch::jit::InterpreterStateImpl::run(std::vector<c10::IValue,std::allocator<c10::IValue> > & stack) Line 767	C++
 	torch.dll!torch::jit::InterpreterState::run(std::vector<c10::IValue,std::allocator<c10::IValue> > & stack) Line 844	C++
 	torch.dll!torch::jit::`anonymous namespace'::ExecutionPlan::run(std::vector<c10::IValue,std::allocator<c10::IValue> > & stack) Line 60	C++
 	torch.dll!torch::jit::GraphExecutorImpl::run(std::vector<c10::IValue,std::allocator<c10::IValue> > & stack) Line 356	C++
 	torch.dll!torch::jit::GraphExecutor::run(std::vector<c10::IValue,std::allocator<c10::IValue> > & inputs) Line 592	C++
```

Output is as follows:
```
cuDNN error: CUDNN_STATUS_INTERNAL_ERROR (Handle at ..\aten\src\ATen\cudnn\Handle.cpp:19)
(no backtrace available):
operation failed in interpreter:
op_version_set = 0
def forward(self,
    input_1: Tensor) -> Tuple[Tensor, Tensor, Tensor]:
  input_2 = torch._convolution(input_1, self.conv1.conv.weight, None, [4, 4], [3, 3], [1, 1], False, [0, 0], 1, False, False, True)
            ~~~~~~~~~~~~~~~~~~ <--- HERE
  _0 = torch.add_(self.conv1.bn.num_batches_tracked, CONSTANTS.c0, alpha=1)
  x_1 = torch.batch_norm(input_2, self.conv1.bn.weight, self.conv1.bn.bias, self.conv1.bn.running_mean, self.conv1.bn.running_var, True, 0.10000000000000001, 1.0000000000000001e-05, True)
  input_3 = torch.cat([x_1, torch.neg(x_1)], 1)
  input_4 = torch.relu_(input_3)
  input_5, _1 = torch.max_pool2d_with_indices(input_4, [3, 3], [2, 2], [1, 1], [1, 1], False)
  input_6 = torch._convolution(input_5, self.conv2.conv.weight, None, [2, 2], [2, 2], [1, 1], False, [0, 0], 1, False, False, True)
  _2 = torch.add_(self.conv2.bn.num_batches_tracked, CONSTANTS.c0, alpha=1)
  x_2 = torch.batch_norm(input_6, self.conv2.bn.weight, self.conv2.bn.bias, self.conv2.bn.running_mean, self.conv2.bn.running_var, True, 0.10000000000000001, 1.0000000000000001e-05, True)
  input_7 = torch.cat([x_2, torch.neg(x_2)], 1)
```
## To Reproduce

1. Complicated to reproduce but does reproduce every time. Need specific model and specific input size.

## Expected behavior

Input works as any size

## Environment

 - PyTorch Version (e.g., 1.0): 1.1.0-pre
 - OS (e.g., Linux): Windows 64-bit
 - How you installed PyTorch (`conda`, `pip`, source): nightly
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0/7.5
 - GPU models and configuration: GTX 1060 with Nvidia driver 419.35

## Additional context

Anything I can provide that would help you?

Edit: Could it be related to the values inside the tensor?

**Comment by ngimel** [comment]
Can you please run it with env var CUDA_LAUNCH_BLOCKING set to 1 to know where the error is coming from? Also, can you  please collect cudnn log https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#api-logging and post it here?

**Comment by xsacha** [comment]
My code has since changed and I wasn't able to replicate. So as I am unable to provide the cudnn log you require I will close this.

**Comment by xsacha** [comment]
I believe I have managed to replicate the issue again.
I followed your instructions to collect the errors. Here's the pastebin: https://pastebin.com/BC4qUzHv

**Comment by mruberry** [comment]
For some reason I can't access your pastebin link?

**Comment by xsacha** [comment]
The paste in is still working. Do you have a preferred paste site?

**Comment by mruberry** [comment]
Maybe a gist would work?

**Comment by xsacha** [comment]
https://gist.github.com/xsacha/51646e9921d2b45cb59e84f90b4fbe70

**Comment by mruberry** [comment]
Thanks for posting the gist and following up with details. Unfortunately, we ran the commands through cuDNN 7.5 and were unable to replicate the failure. This suggests that cuDNN is failing (with an unhelpful error message) due to factors outside of cuDNN, like other activity on the GPU. I'm sorry that we're not able to be more helpful.

**Comment by xsacha** [comment]
This bug no longer occurs on the latest version
