### ISSUE TITLE
Is there 0.5.0version of pytorch?

### ISSUE THREAD

**Issue by zixufang** [pytorch/pytorch#19104]
when I tried to use Dataparallel, I came across the problem" Arguments are located on different GPUs",
I found that I should use the 0.5.0 version to solve the problem on the forum.
However ,I have been trying to find the correct version for a long time with no result.Can anyone help me ?
(ps, I tried to run the code on pytorch1.0, but error came in the dataloader part “RandomSampler’ object has no attribute 'replacement”.and I found no solution.
Thank you !!

**Comment by soumith** [comment]
there is no 0.5.0.
1.0 is the 0.5.0
