### ISSUE TITLE
CUDA streams not being executed concurrently

### ISSUE THREAD

**Issue by npyoung** [pytorch/pytorch#19103]
## 🐛 Bug

Queues of operations assigned to different cuda streams are executed in series, not concurrently.

## To Reproduce

1. Create several streams
1. Assign work to be done in each stream (e.g. Fourier transforms)
1. Call `torch.cuda.syncrhonize()` at the very end
1. Run `watch -n 1 nvidia-smi` to see GPU utilization
1. Time execution to compare to explicitly serial code

```python
import numpy as np
import torch
n_gpus = torch.cuda.device_count()
streams = [torch.cuda.Stream(device=i) for i in range(n_gpus)]

x = torch.tensor(np.random.rand(100, 2048, 2048).astype(np.float32))
xs = [x.to(i) for i in range(n_gpus)]
Xgs = []

# Start timing here
for i, s in enumerate(streams):
    with torch.cuda.stream(s):
        for _ in range(100):
            Xg = torch.rfft(xs[i], 2)
    Xgs.append(Xg)

# Indent below to run explicitly in serial
torch.cuda.synchronize()
```

## Expected behavior

GPU utilization for all present GPUs should rise simultaneously, whereas indenting the last line so it runs inside the `for` loop should cause GPU utilization to rise and fall on one device at a time. The loop above should run about `n_gpus` times faster than if the last line were indented.

Instead, GPU utilization rises and falls sequentially and the loop takes the same amount of time to run if the synchronization happens in the `for` loop or not!

## Environment
```
PyTorch version: 1.0.0
debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.4
[conda] blas                      1.0                         mkl  
[conda] cuda100                   1.0                           0    pytorch
[conda] mkl                       2018.0.3                      1  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0  
[conda] mkl_random                1.0.1            py36h629b387_0  
[conda] pytorch                   1.0.0           py3.6_cuda10.0.130_cudnn7.4.1_1  [cuda100]  pytorch
[conda] torchvision               0.2.1                      py_2    pytorch
```

**Comment by colesbury** [comment]
This isn't a bug. 

1) Operations on different GPUs are on different streams. The stream code here do nothing
2) If you want to make effective use of multiple GPUs you should interleave launches to avoid paying 100x overhead for the first 100 launches on GPU 0 before even launching on GPU1. (Or use multiple threads)
3) The operations are running concurrently, you can see this with an outer loop:

```python
for _ in range(1000):
    for i, s in enumerate(streams):
        Xg = torch.rfft(xs[i], 2)
```

**Comment by GLjun** [comment]
> This isn't a bug.
> 
> 1. Operations on different GPUs are on different streams. The stream code here do nothing
> 2. If you want to make effective use of multiple GPUs you should interleave launches to avoid paying 100x overhead for the first 100 launches on GPU 0 before even launching on GPU1. (Or use multiple threads)
> 3. The operations are running concurrently, you can see this with an outer loop:
> 
> ```python
> for _ in range(1000):
>     for i, s in enumerate(streams):
>         Xg = torch.rfft(xs[i], 2)
> ```

Hi, I run the code below. but the measured time is just the same. And I tried torch.mm by small gemm kernel, the torch.cuda.stream() just didn't work. All the stream running interleaved but serial.
`import numpy as np
import torch
import time

k = 4
cuda = torch.device('cuda')
streams = [torch.cuda.Stream(cuda) for i in range(k)]

x = torch.tensor(np.random.rand(100, 2048, 2048).astype(np.float32))
xs = x.to(cuda)
Xgs = []

torch.cuda.synchronize()
st = time.time()
# Start timing here
for _ in range(1000):
    for i, s in enumerate(streams):
        with torch.cuda.stream(s):
            Xg = torch.rfft(xs[i], 2)
    #Xgs.append(Xg)

torch.cuda.synchronize()
et = time.time()
print("warmming up time: ", et-st)

torch.cuda.synchronize()
st = time.time()
# Start timing here
for _ in range(1000):
    for i, s in enumerate(streams):
        with torch.cuda.stream(s):
            Xg = torch.rfft(xs[i], 2)
    #Xgs.append(Xg)

torch.cuda.synchronize()
et = time.time()
print("serial time: ", et-st)

st = time.time()
# Start timing here
for _ in range(1000):
    for i, s in enumerate(streams):
        Xg = torch.rfft(xs[i], 2)
    #Xgs.append(Xg)

torch.cuda.synchronize()
et = time.time()
print("parallel time: ", et-st)
# Indent below to run explicitly in serial
torch.cuda.synchronize()`
