### ISSUE TITLE
torch.Tensor.ndim is missing

### ISSUE THREAD

**Issue by kasparlund** [pytorch/pytorch#19119]
## 🚀 Feature
need this numpy feature for easy plotting with matplotlib: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html

## Motivation
matplotlibs .plot uses .ndim when passing a ndarray

The missing attribute on tensor can be circumvented by the following:
#This monkey-patch is there to be able to plot tensors
torch.Tensor.ndim = property(lambda x: len(x.shape))

**Comment by gsp-27** [comment]
Isn't ```Tensor.ndimension``` giving you the same thing?

**Comment by kasparlund** [comment]
its matplotlib that expects the presence of .ndim

**Comment by danielpcox** [comment]
To clarify, this is the _only_ thing preventing matplotlib from being able to plot tensors, so it would be a nice addition.

![image](https://user-images.githubusercontent.com/56411/61333832-338a3600-a7f6-11e9-93b1-44a9e38c2fcc.png)

**Comment by soumith** [comment]
i think `ndim` might've been added in master by @umanwizard

**Comment by umanwizard** [comment]
Yep. https://pytorch.org/docs/master/tensors.html?highlight=ndim#torch.Tensor.ndim
