### ISSUE TITLE
`torch.irfft` and `np.fft.irfft` disagree

### ISSUE THREAD

**Issue by eigenfoo** [pytorch/pytorch#19111]
## 🐛 Bug

I originally posted this [on the PyTorch forums](https://discuss.pytorch.org/t/torch-irfft-and-np-fft-irfft-disagree/41994), but I suspect it is a bug and belongs here.

Briefly, `torch.irfft` and `np.fft.irfft` produce different results: not only are the results not numerically close, they are not even of the same shape.

## To Reproduce

```python
import numpy as np
import torch
import itertools

x = np.random.randn(100).astype(np.float32)

# irfft(rfft(x)) == x
fft_np = np.fft.rfft(x)
ifft_np = np.fft.irfft(fft_np)
assert np.allclose(x, ifft_np)

# Same thing but in PyTorch
x = torch.tensor(x)
fft_torch = torch.rfft(x, signal_ndim=1)
ifft_torch = torch.irfft(fft_torch, signal_ndim=1).numpy()

# The rffts are np.allclose
fft_torch = fft_torch.numpy()
assert np.allclose(np.real(fft_np), fft_torch[:, 0])
assert np.allclose(np.imag(fft_np), fft_torch[:, 1])

# But the irffts have different shapes
print(ifft_np.shape)     # (100,)
print(ifft_torch.shape)  # (101,)

# And none of their values are np.allclose
print(np.allclose(ifft_np, ifft_torch[:-1]))  # False
print([x for (x, y) in itertools.product(ifft_np, ifft_torch)
       if np.allclose(x, y)])  # []
```

## Expected behavior

I would expect that (in the code snippet above) `ifft_torch` would have the same shape as `x`, and for both tensors to be `torch.allclose` to each other.

I have not included the code here (I can if you would like), but I can verify that `torch.fft` and `torch.ifft` has this expected behavior... just not their real counterparts, `torch.rfft` and `torch.irfft`.

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.0.1.post2
[conda] Could not collect

**Comment by SsnL** [comment]
https://pytorch.org/docs/master/torch.html#torch.irfft

> Due to the conjugate symmetry, input do not need to contain the full complex frequency values. Roughly half of the values will be sufficient, as is the case when input is given by rfft() with rfft(signal, onesided=True). In such case, set the onesided argument of this method to True. Moreover, the original signal shape information can sometimes be lost, optionally set signal_sizes to be the size of the original signal (without the batch dimensions if in batched mode) to recover it with correct shape.

**Comment by eigenfoo** [comment]
Ah, I see! Thank you for the clarification.

I would think it more intuitive to have `onesided=True` be the default, instead of `onesided=False`. I am not sure why the output signal shape may sometimes be incorrect: that seems non-obvious and undesirable to me.

In any case, this isn't a bug. I'll close this issue. Thanks again!
