### ISSUE TITLE
[feature request] torch.trapz or some other method for numerical integration similar to numpy

### ISSUE THREAD

**Issue by chausies** [pytorch/pytorch#19122]
numpy and matlab both have a trapz (and a simps) function, which makes it convenient to integrate y values over some x values. It seems pytorch is lacking this convenient function (even though it has other functions like cumsum). It would be great if we could have an implementation of trapz or simps similar to [numpy's](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.trapz.html). 

One simple motivation is that pytorch is desirable as a significantly faster alternative to numpy, and trapz is a standard and necessary feature in that library.

One main concrete example of its use is for [KDE](https://en.wikipedia.org/wiki/Kernel_density_estimation) when using a non-standard distribution. 

trapz (and simps) should also have a very simple implementation as well. For the 1D case, it's as simple as:
```python
def trapz(y, x=None, dx=1.0):
  y_avg = (y[1:] + y[:-1])/2
  if not (x is None):
    dx = x[1:] - x[:-1]
  return sum(y_avg*dx)
```

**Comment by soumith** [comment]
seems like a good idea.

**Comment by gsp-27** [comment]
Is anyone working on this, I would be happy take this up with some guidance.

**Comment by umanwizard** [comment]
@gsp-27 Hey, sorry nobody responded to you. I am planning on adding this in the next day or two, unless you have already worked on it.

**Comment by umanwizard** [comment]
This has been landed
