### ISSUE TITLE
flat_hash_map.h  error C3203  'templated_iterator'  unspecialized class template

### ISSUE THREAD

**Issue by asa008** [pytorch/pytorch#19156]
## 🐛 Bug

when I build pytorch 1.0 on win10 from source,  encountered following errors:
 pytorch\c10/util/flat_hash_map.h(1383): error C3203: 'templated_iterator': unspecialized class template can't be used as a template argument for template parameter '_Ty1', expected a real type

elementwise_div_op.cu
cl : Command line warning D9025 : overriding '/EHa' with '/EHs'
F:/ProgramFiles/pytorch\c10/util/flat_hash_map.h(1379): error C3203: 'templated_iterator': unspecialized class template can't be used as a template argument for template parameter '_Ty1', expected a real type
F:/ProgramFiles/pytorch\c10/util/flat_hash_map.h(1437): note: see reference to class template instantiation 'ska::flat_hash_map<K,V,H,E,A>' being compiled
F:/ProgramFiles/pytorch\c10/util/flat_hash_map.h(1383): error C3203: 'templated_iterator': unspecialized class template can't be used as a template argument for template parameter '_Ty1', expected a real type
F:/ProgramFiles/pytorch\c10/util/flat_hash_map.h(1391): error C3203: 'templated_iterator': unspecialized class template can't be used as a template argument for template parameter '_Ty1', expected a real type
F:/ProgramFiles/pytorch\c10/util/flat_hash_map.h(1473): error C3203: 'templated_iterator': unspecialized class template can't be used as a template argument for template parameter '_Ty1', expected a real type
F:/ProgramFiles/pytorch\c10/util/flat_hash_map.h(1510): note: see reference to class template instantiation 'ska::flat_hash_set<T,H,E,A>' being compiled
F:/ProgramFiles/pytorch\c10/util/flat_hash_map.h(1478): error C3203: 'templated_iterator': unspecialized class template can't be used as a template argument for template parameter '_Ty1', expected a real type
F:/ProgramFiles/pytorch\c10/util/flat_hash_map.h(1482): error C3203: 'templated_iterator': unspecialized class template can't be used as a template argument for template parameter '_Ty1', expected a real type
F:/ProgramFiles/pytorch\c10/util/flat_hash_map.h(1486): error C3203: 'templated_iterator': unspecialized class template can't be used as a template argument for template parameter '_Ty1', expected a real type
F:/ProgramFiles/pytorch\c10/util/flat_hash_map.h(1490): error C3203: 'templated_iterator': unspecialized class template can't be used as a template argument for template parameter '_Ty1', expected a real type
host_defines.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead.
CMake Error at caffe2_gpu_generated_elementwise_div_op.cu.obj.Release.cmake:279 (message):
  Error generating file
  F:/ProgramFiles/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators/./caffe2_gpu_generated_elementwise_div_op.cu.obj

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 719, in <module>
    build_deps()
  File "setup.py", line 285, in build_deps
    build_dir='build')
  File "F:\ProgramFiles\pytorch\tools\build_pytorch_libs.py", line 268, in build_caffe2
    check_call(build_cmd, cwd=build_dir, env=my_env)
  File "C:\Users\qjhs\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '11']' returned non-zero exit status 1.

corresponding codes are:

1378    using Table::emplace;
1379    std::pair<typename Table::iterator, bool> emplace()
1380    {
1381        return emplace(key_type(), convertible_to_value());
1382    }
1383    template<typename M>
1384    std::pair<typename Table::iterator, bool> insert_or_assign(const key_type & key, M && 1385   m)
1386     {
1387        auto emplace_result = emplace(key, std::forward<M>(m));
1388        if (!emplace_result.second)
1389            emplace_result.first->second = std::forward<M>(m);
1390        return emplace_result;
1391    }
1392    template<typename M>
1393    std::pair<typename Table::iterator, bool> insert_or_assign(key_type && key, M && m)
1394    {
1395        auto emplace_result = emplace(std::move(key), std::forward<M>(m));
1396        if (!emplace_result.second)
1397            emplace_result.first->second = std::forward<M>(m);
1398        return emplace_result;
1399    }

1473    template<typename... Args>
1474    std::pair<typename Table::iterator, bool> emplace(Args &&... args)
1475    {
1476        return Table::emplace(T(std::forward<Args>(args)...));
1477    }
1478    std::pair<typename Table::iterator, bool> emplace(const key_type & arg)
1479    {
1480        return Table::emplace(arg);
1481    }
1482    std::pair<typename Table::iterator, bool> emplace(key_type & arg)
1483    {
1484        return Table::emplace(arg);
1485    }
1486    std::pair<typename Table::iterator, bool> emplace(const key_type && arg)
1487    {
1488        return Table::emplace(std::move(arg));
1489    }
1490    std::pair<typename Table::iterator, bool> emplace(key_type && arg)
1491    {
1492        return Table::emplace(std::move(arg));
1493    }

Can anybody help me to solved it?   thanks a lot

## Environment
win 10,  cuda 10.1, python 3.66, Visual Studio 2017(v141)   pytorch master

**Comment by peterjc123** [comment]
Would you please update your VS 2017 to the latest version? If you don't want to update, then you can try to wrap these code with `#ifndef __CUDACC__ ` and `#endif`. cc @ezyang

**Comment by asa008** [comment]
thank you! it works!
