### ISSUE TITLE
GPU utlization is wacky

### ISSUE THREAD

**Issue by ThisIsIsaac** [pytorch/pytorch#19166]
## 🐛 Bug

Taoctorn2 and Waveglow inference using pytorch produces dramatically different utilization.

here are the comparisons of Taoctorn2 and Waveglow using Nsight Systems. The skyblue bar indicates some sort of work happening on the GPU. the absence of the sky blue bar or the red bar indicates that no computation is happening on the GPU. The “CUDA API” row indicates CPU’s preperation of launching cuda kernels – it is CPU side work in order to launch kernel on the GPU.

**Tacotron2:**
<img width="2560" alt="Screen Shot 2019-04-10 at 17 26 14 PM" src="https://user-images.githubusercontent.com/49523965/55960399-a93aaf00-5ca7-11e9-8799-46db1f014482.png">
zoom in further:

<img width="2560" alt="Screen Shot 2019-04-10 at 17 25 56 PM" src="https://user-images.githubusercontent.com/49523965/55960426-b8b9f800-5ca7-11e9-9c31-70b149ebc904.png">

and further:

<img width="2560" alt="Screen Shot 2019-04-10 at 17 26 03 PM" src="https://user-images.githubusercontent.com/49523965/55960436-bce61580-5ca7-11e9-9d4b-48c35d6ae680.png">

and you see so much gaps.

**Waveglow**
<img width="2560" alt="Screen Shot 2019-04-10 at 17 32 17 PM" src="https://user-images.githubusercontent.com/49523965/55960496-e0a95b80-5ca7-11e9-8680-491254c7ee9d.png">
even if you zoom in further, you see alomost no gaps

<img width="2560" alt="Screen Shot 2019-04-10 at 17 32 25 PM" src="https://user-images.githubusercontent.com/49523965/55960510-e99a2d00-5ca7-11e9-93c3-77d7b88c6834.png">

## To Reproduce

1. git clone from [Nvidia waveglow](https://github.com/NVIDIA/waveglow) and [Nvidia Tacotron2](https://github.com/NVIDIA/tacotron2)
1. follow "Generate audio with our pre-existing model" to run waveglow. To run tacotron2, move to tacotron 2 directory, download the [published model of tacotron2](https://drive.google.com/file/d/1c5ZTuT7J08wLUoVZ2KkUs_VdZuJ86ZqA/view) and run `python inference.py`
1. while running, profile with Nsight systems 

## Expected behavior
For the above two functions to exhibit similar utilization

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): CentOS7
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.5.6
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: single GTX 1080
 - Any other relevant information:

## Additional context

I an a CUDA developer, so I would love to help out with this issue if I can, along with increasing throughput on some CUDA bakcend computations, which I've created another issue about.

**Comment by zhangguanheng66** [comment]
The GPU computation was not launched successfully. Will assign to someone after more discussions during the triage meeting.

**Comment by ezyang** [comment]
@zhangguanheng66 Are you sure it has to do with the GPU computation launching successfully or not? It looks like the scripts are running successfully.

**Comment by zhangguanheng66** [comment]
@ezyang let me edit it and be more accurate. The GPU computation is just pending there.

**Comment by ThisIsIsaac** [comment]
What do you mean by pending? I'm sure you know, but just to be sure, GPU's work is supposed to start after the CUDA API call ( as you can see in the third image, the sky-blue bar starts as soon as the CUDA API block ends , and this pattern repeats ). And CUDA API calls are usually short -- the above mage, the duration of CUDA API call -- to be more specific, the time that CPU spent to launch a CUDA kernel in the GPU -- was 15 micro seconds. It just looks large because it is much larger than the time that it takes to do the actual computation -- 3 micro seconds.

I am not sure if this is just a feature of the design of Pytorch or a bug that some networks utilize GPU better than others with dramatic difference. It was weird to me that Waveglow seemed to be able to make GPU not become idle, but Tacotron2 did. Maybe its just due to the light-weight computation that tacotron2 does compared to Waveglow

**Comment by ThisIsIsaac** [comment]
I think @mkolod explained it well in my cross-post of [this issue](https://github.com/NVIDIA/tacotron2/issues/183#issuecomment-482300056) in Nvidia Tacotron2's github

**Comment by soumith** [comment]
that's a great answer detailed by Marek. Let's continue the discussion there.
