### ISSUE TITLE
better CUDA optimization using read-only cache and __restrict__

### ISSUE THREAD

**Issue by ThisIsIsaac** [pytorch/pytorch#19165]
## 🚀 Feature

for virtual architecture of compute_35 and above, use read-only cache -- `__ldg()` and `__restrict__` for weights

## Motivation
increase throughput

## Pitch
for example, in the `upsampling_op.cu`, we can add `__restrict__` to `X`and use `__ldg` to read from it. I have a working piece of code with this implemented based on pytorch's bilinear upsampling that I would like to contribute..

**Comment by zou3519** [comment]
Our lowest supported compute capability is 3.5, so that should be fine. This sounds like a good idea, please feel free to open some pull requests

**Comment by ThisIsIsaac** [comment]
Thanks :)

There was also some dead code so I'm going to clean that up too and commit in a couple days.

**Comment by ThisIsIsaac** [comment]
Do you guys — Facebook I assume — have some internal ways to micro-benchmark kernels for speed and correctness? I use Nsight Compute for profiling but it doesnt help too much when it comes to measuring the exact speed of such a small kernel.

**Comment by zou3519** [comment]
I've personally used the following approaches:
1) %timeit in ipython + torch.cuda.synchronize()
2) CUDA events (torch.cuda.Event)
3) autograd profiler with use_cuda=True (this uses cuda events)

Timing with CUDA events adds some overhead. I don't have good recommendations for how to microbenchmark smaller kernels so I usually try to give it larger inputs

**Comment by ThisIsIsaac** [comment]
Just a couple clarifications:
1. there are sometimes `.cu` file which has GPU kernel and there is also `cudnn.cc` file that seems to use cuDNN that does the same computation. For example, in [this directory](https://github.com/pytorch/pytorch/tree/master/caffe2/operators), there is both `elu_op.cu` and `elu_op_cudnn.cc`. My guess is, when built without cuDNN, pytorch uses `elu_op.cu`, but when there is cuDNN`, pytorch uses `elu_op_cudnn.cc`. However, if there is only `.cu` file and no `cudnn.cu` file, like for `upsample_op.cu` -- there is no `upsample_op_cudnn.cc`, -- then the `.cu` file would be used as long as there is GPU in the system and is built with CUDA. Am I right?

1. When the variable name suggests that some array is read only, or if it is only read within a kernel, I can assume that: the array is both safe for me to use `__restrict__` and assume to be read-only within the lifespan fo the kernel. For example, inside `upsample_op.cu` (https://github.com/pytorch/pytorch/blob/master/caffe2/operators/upsample_op.cu),  inside the global kernel `UpsampleBilinearKernel`, `X` is only read from within the kernel. Although it doesn't mention explicitly that I can assume `X` and `Y` are not aliases, I think this is sensible for me to assume.

Let me know if I got any of these details wrong.

Thanks again for your help.

**Comment by soumith** [comment]
generally speaking, you can ignore the caffe2/operators in totality, because those ops are not actually hooked into the PyTorch frontend, but are for the caffe2 frontend.

What you want to be looking at is aten/src/

**Comment by ThisIsIsaac** [comment]
Thanks for the clarification.

Can I assume the second point and that compute capability is 35 or greater?

**Comment by soumith** [comment]
yes, the 2nd point holds, and we support only compute capability of 3.5 or greater

**Comment by soumith** [comment]
we used to support compute capability 3.0 until some point, hence it wasn't used from the start.

**Comment by ThisIsIsaac** [comment]
Thanks for the clarification. 

I assume you cannot use loop unrolling since the code is only compiled once thad loop variables cannot be given at compile time.

**Comment by ThisIsIsaac** [comment]
is there a reason why caffe2 front end CUDA kernels have their threads per block set to 128? For bilinear upsampling, simply increasing the number of threads per block by 8 times ( from 128 to 1024) -- i.e. larger block, few number of blocks -- increased throughput about 30%.

**Comment by soumith** [comment]
caffe2 can have parallelly executing operators in multiple streams. it might be 128 to reduce wasted occupancy and maximize throughput even when multiple operators are running in parallel.

**Comment by ThisIsIsaac** [comment]
I want to clarify what you mean by "parallelly executing operators in multiple streams". Do you mean, **within a single kernel launch**, caffe2 uses multiple strams to asynchronously execute the different operatros in parallel? Or do you mean caffe2 launches **multiple kernels in parallel**?

From what I have seen, it seems like caffe2 doesn't configure a single kernel call with multiple streams. If what you mean is: caffe2 launches multiple kernels in parallel, then the above proposal shouldn't be a problem. Kernels launched in parallel don't actually run concurrently. They use time slicing to schedule different kernels at different times, so the kernels do not occupy the GPU at the same time. Robert Crovella from Nividia detailed it [here](https://devtalk.nvidia.com/default/topic/1047816/launching-multiple-kernels-in-same-context-vs-multiple-kernels/?offset=3#5317566).

**Comment by ThisIsIsaac** [comment]
oh sorry for the misunderstanding. I was puzzled because I thought caffe2 was using multiprocessing, each process launching its kernel. In the case of using multiple streams, it makes sense to restrict the number of threads & blocks. So, if I understand you correctly, when optimizing for individual kernel, I shouldn't change the kernel launch configuration. Am I right?

**Comment by ThisIsIsaac** [comment]
@soumith made a pull request.

I am puzzled by:
> Try not to add things here; we're slowly porting these to native.

[here](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md

It says not to add anything to any of the directories under [src](https://github.com/pytorch/pytorch/tree/master/aten/src). But when I go into [native/cuda](https://github.com/pytorch/pytorch/tree/master/aten/src/ATen/native), some cuda functions are missing. 

From my understanding, it seems like not every function inside [src](https://github.com/pytorch/pytorch/tree/master/aten/src) is migrated to [native/cuda](https://github.com/pytorch/pytorch/tree/master/aten/src/ATen/native). So if I want to look at cuda codes that are actually used by python, then should I look at both of the directories?

**Comment by zou3519** [comment]
Yes, you should look at both directories. Our newer implementations live in aten/native/cuda and the other implementations are in our legacy THC / THCUNN folders.

**Comment by ThisIsIsaac** [comment]
Sorry it took so long to get back.

I've profiled a handful most used computations and there was no significant difference in the profiled time (`__restrict__` version was slightly faster but it was not big enough). 

Since Pytorch seems to do the same with `__restrict__` it's likely that we can safely leave it as is.
