### ISSUE TITLE
Torch.tensor.sum() is not accurate enough

### ISSUE THREAD

**Issue by DayChan** [pytorch/pytorch#19164]
## 🐛 Bug

The `sum()` function is not precise when it summarizes a huge amount of numbers which has decimal.

## To Reproduce

```python3
preds = torch.ones(5, 68, 64, 64) * 0.1
preds.sum() * 10
```
The result is `tensor(1392666.)`

## Expected behavior

When the elements don't have decimals.
```python3
preds = torch.ones(5, 68, 64, 64)
preds.sum()
```
The result is `tensor(1392640.)` and it is the expected result.

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 14.04.5 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 384.59
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/lib/libcudnn.so.7.1.4

Versions of relevant libraries:
[pip3] numpy==1.14.6
[pip3] torch==1.0.0
[pip3] torchvision==0.2.2

**Comment by soumith** [comment]
this is expected, because the first operation is being done in floating point, which is lossy math and the second operation is being done in int64 which is not lossy. If you want a more precise floating point, use double precision:

```python
preds = torch.ones(5, 68, 64, 64, dtype=torch.float64) * 0.1
preds.sum() * 10
```

**Comment by soumith** [comment]
(edited and updated comment with a more correct explanation)

**Comment by DayChan** [comment]
I got it, thanks very much.

**Comment by fmassa** [comment]
One thing that is worth investigating is why numpy, for float32 arrays, produces more accurate results than pytorch, when forcing the reduction to be float32 as well.

**Comment by grafi-tt** [comment]
@fmassa NumPy implements pairwise summation.

https://github.com/chainer/chainer/issues/7038#issuecomment-486058099
