### ISSUE TITLE
build from source ubuntu16.04 without GPU error

### ISSUE THREAD

**Issue by CharlesxrWu** [pytorch/pytorch#19192]
## 🐛 Bug

`[ 34%] Linking CXX static library ../../../lib/libprotoc.a
[ 34%] Built target libprotoc
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-nnpack --use-mkldnn --use-qnnpack caffe2'`
## To Reproduce

1. python setup.py install
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.3                      199
[conda] mkl-include               2019.3                      199
[conda] mkl_fft                   1.0.10           py36ha843d7b_0
[conda] mkl_random                1.0.2            py36hd81dba3_0
[conda] mkldnn                    0.16.1                        0    mingfeima
```

 - PyTorch Version (e.g., 1.0): v1.0.1   83221
 - OS (e.g., Linux): ubuntu server 16.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: py3.6
 - CUDA/cuDNN version: NO
 - GPU models and configuration: NO
 - Any other relevant information:

**Comment by CharlesxrWu** [comment]
fixed by pulling the latest code

**Comment by ezyang** [comment]
Can you post the complete build log? You've truncated out the actual error, which means we can't easily help you. Please reopen this issue when you do so.
