### ISSUE TITLE
Difference: torch.Tensor.view() torch.Tensor.reshape()

### ISSUE THREAD

**Issue by Jie-Yuan** [pytorch/pytorch#19193]
Difference: torch.Tensor.view() torch.Tensor.reshape()

**Comment by vishwakftw** [comment]
Please refer to the documentation of [torch.Tensor.view](https://pytorch.org/docs/master/tensors.html?highlight=view#torch.Tensor.view).

Questions like these are better addressed in the [Forums](https://discuss.pytorch.org), so please consider posting it there.

**Comment by fmassa** [comment]
Closing following @vishwakfw comment
