### ISSUE TITLE
Does v1.0.1 support CUDA10.1？

### ISSUE THREAD

**Issue by berylyellow** [pytorch/pytorch#19199]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soumith** [comment]
only if you compile from source

**Comment by berylyellow** [comment]
> only if you compile from source

Do I need to change some code or just install by "python3 setup.py install"? By the way, I don't preinstall annaconda.

**Comment by berylyellow** [comment]
succeed in installing pytorch1.0.1 with cuda10.1

**Comment by CoinCheung** [comment]
Hi, 

I noticed that I should install magma-cudaxx package in order to compile from source. The latest version seems to be magma-cuda100, can this package support cuda10.1?

**Comment by berylyellow** [comment]
@CoinCheung Yes, I succeed in installing pytorch1.0.1 with cuda10.1

**Comment by negan0** [comment]
@berylyellow u compiled from source? or just used conda or pip?
