### ISSUE TITLE
[FR] support base in logspace

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#19220]
This would bring it closer to parity with numpy functionality: https://docs.scipy.org/doc/numpy/reference/generated/numpy.logspace.html

It is also a rather simple change. The kernels currently hardcode `base10 = 10`. Just making it taking in a `double` should work.

**Comment by lkhphuc** [comment]
Would love to get started with this issue. Will send a PR soon.

**Comment by SsnL** [comment]
fixed by #19542
