### ISSUE TITLE
torch.is_tensor(torch.HalfTensor()) returns False. 

### ISSUE THREAD

**Issue by nasimrahaman** [pytorch/pytorch#1922]
The problem is [here](https://github.com/pytorch/pytorch/blob/master/torch/__init__.py#L274).

**Comment by nasimrahaman** [comment]
This is not intentional, is it?

**Comment by gchanan** [comment]
I don't think so?  It's inconsistent with torch7:

```
th> a=torch.HalfTensor()
th> torch.isTensor(a)
true
```

HalfStorage/isStorage looks to have the same issue.

**Comment by nasimrahaman** [comment]
@gchanan Looks like an easy-fix.

**Comment by ethanluoyc** [comment]
@nasimrahaman It appears to be more complicated since some methods on HalfTensor has not been implemented. See the PR. I will take a closer look and attempt to fix them.
