### ISSUE TITLE
The cuFFT plan cache is not CUDA context-aware

### ISSUE THREAD

**Issue by npyoung** [pytorch/pytorch#19224]
## 🐛 Bug

cuFFT Plans are context-specific and need to be used on arrays from the same context. PyTorch's cuFFT plan cache uses the arguments to the plan-creation call to generate a hash, but the plan's CUDA context is not used as part of this hash. So, for example, if you call `torch.fft` on some data on GPU 1, then call `torch.fft` on data of the same shape/type on GPU 2, you get a cache hit and pull up the plan from GPU 1 and then attempt to use it on GPU 2, resulting in a CUFFT_EXEC_FAILED.

## To Reproduce
On a machine with at least two GPUs:
```python
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
import torch

sz = 65

for i in range(2):
    arr = torch.rand((sz, sz//2 + 1, 2), dtype=torch.float32, device=i)
    # Get the crash
    try:
        torch.irfft(arr, 2, signal_sizes=(sz, sz))
    except RuntimeError as e:
        print(str(i))
        raise e
```
Should print "1" indicating the failure on the 2nd GPU, followed by a stack trace:
```python
     12     # Get the crash
     13     try:
---> 14         torch.irfft(arr, 2, signal_sizes=(sz, sz))
     15     except RuntimeError as e:
     16         print(str(i))

RuntimeError: cuFFT error: CUFFT_EXEC_FAILED
```

## Expected behavior

The plan cache should be context-aware and add a new plan to the cache for the CUDA context associated with the 2nd GPU. You can simulate this by setting

```python
torch.backends.cuda.cufft_plan_cache.max_size = 0
```

before the `for` loop to verify that the cache is at fault.

Alternatively, separate caches could be maintained for each context. Not sure if that's easier or not.

## Environment
```
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80
GPU 4: Tesla K80
GPU 5: Tesla K80
GPU 6: Tesla K80
GPU 7: Tesla K80

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.4
[conda] blas                      1.0                         mkl
[conda] cuda100                   1.0                           0    pytorch
[conda] mkl                       2018.0.3                      1
[conda] mkl-service               1.1.2            py36h17a0993_4
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0
[conda] mkl_random                1.0.1            py36h629b387_0
[conda] pytorch                   1.0.0           py3.6_cuda10.0.130_cudnn7.4.1_1  [cuda100]  pytorch
[conda] torchvision               0.2.1                      py_2    pytorch
```

**Comment by SsnL** [comment]
Ah great analysis! Thanks for reporting this!

**Comment by SsnL** [comment]
Per-device cache would be nice. It changes the slightly the behavior, but not much, and won't affect most of the users. @soumith , what do you think?

**Comment by SsnL** [comment]
And just for reference, arrayfire has a separate cache for each device
https://github.com/arrayfire/arrayfire/blob/899b712a8ffb5350f2d7ead20aecab593f06acca/src/backend/cuda/platform.cpp#L429

**Comment by soumith** [comment]
yea, this definitely needs fixing, Thanks for pinpointing the bug @npyoung

**Comment by SsnL** [comment]
The question is, do we want a per-device cache?

**Comment by npyoung** [comment]
@SsnL Per-device cache seems like a good fix to me!

**Comment by SsnL** [comment]
hmm, I can't trigger this error without setting `CUDA_LAUNCH_BLOCKING=1` though

**Comment by npyoung** [comment]
If you don't have launch blocking on, the error surfaces as an illegal GPU memory access and appears well after the offending cuFFT call. I'll try to put another minimal example together. Right now I can only get it to fail without `CUDA_LAUNCH_BLOCKING=1` in my full application.

**Comment by SsnL** [comment]
It’s alright. I figured out a way to trigger it.
