### ISSUE TITLE
Broken Link in tripletmarginloss

### ISSUE THREAD

**Issue by PetroSokirniy** [pytorch/pytorch#19245]
## 📚 Documentation

The link to the under https://pytorch.org/docs/stable/nn.html#tripletmarginloss  pointing to the paper Learning shallow convolutional feature descriptors with triplet losse is broken. Currently its pointing to http://www.iis.ee.ic.ac.uk/~vbalnt/shallow_descr/TFeat_paper.pdf , but that link is dead. Maybe use http://www.bmva.org/bmvc/2016/papers/paper119/paper119.pdf ?

**Comment by sakaia** [comment]
it should use following link
http://www.bmva.org/bmvc/2016/papers/paper119/index.html

**Comment by soumith** [comment]
thanks, I sent a PR and it'll be fixed soon
