### ISSUE TITLE
InstanceNorm, GroupNorm doesn't crash with # of elements == 1

### ISSUE THREAD

**Issue by orybkin** [pytorch/pytorch#19250]
## 🐛 Bug

Classes _InstanceNorm, GroupNorm should throw an error if number of elements over which the statistics are computed is 1. E.g. if you have a batch with shape [64, 256, 1, 1], instance norm and group norm (with num_groups=256) will compute the statistics over last two dimensions, which is just one element. 

The effect of this will be that the output of the normalization operation is an all-zeros tensor. Arguably, if you want your operation to output an all-zeros tensor there are easier ways to do it. On the other side, if this mechanics is triggered unawaredly the activations of the network will become all zeros, which would effectively prevent any learning. In _BatchNorm, computing statistics over 1 element tensors triggers a ValueError

## To Reproduce

```
import torch
x = torch.rand(10)[None,:,None]
print(torch.nn.InstanceNorm1d(10)(x))
print(torch.nn.GroupNorm(10,10)(x))
print(torch.nn.BatchNorm1d(10)(x))
````

## Expected behavior

Lines 3,4 (instance norm, group norm): throw the same error as line 5 (batch norm)

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.14.5
[pip3] numpydoc==0.7.0
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.2.1
[pip3] torchviz==0.0.1
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.3                      1  
[conda] mkl-service               1.1.2                    py36_3  
[conda] mkl_fft                   1.0.6            py36hb8a8100_0  
[conda] mkl_random                1.0.1            py36h5d10147_1  
[conda] pytorch                   1.0.1                   py3.6_2    pytorch
[conda] tensorflow                1.12.0          mkl_py36h2b2bbaf_0  
[conda] tensorflow-base           1.12.0          mkl_py36h70e0e9a_0  
[conda] torchvision               0.2.1                      py_2    pytorch
[conda] torchviz                  0.0.1                     <pip>

**Comment by colesbury** [comment]
@Kaixhin I think you worked on the InstanceNorm implementation. Can you comment on this? Does the proposed change (raise an exception if the norm is only on one element) make sense?

**Comment by Kaixhin** [comment]
Yep the issue and proposal make sense, would be a sensible thing to catch :+1:

**Comment by ptrblck** [comment]
In PyTorch `1.8.0.dev20201109` `nn.InstanceNorm2d` with running stats crashes for a single-input pixel and a batch size of 1:
```python
norm = nn.InstanceNorm2d(3, track_running_stats=True)
x = torch.randn(1, 3, 1, 1)
out = norm(x)
> ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 3, 1, 1])
```
but accepts single pixel inputs for a batch size > 1 and corrupts the `running_var`:
```python
norm = nn.InstanceNorm2d(3, track_running_stats=True)
print(norm.running_mean)
> tensor([0., 0., 0.])

print(norm.running_var)
> tensor([1., 1., 1.])

x = torch.randn(8, 3, 1, 1)
out = norm(x)
print(out)
> tensor([[[[0.]],

           [[0.]],

           [[0.]]],
            ...

print(norm.running_mean)
> tensor([ 0.0194, -0.0310, -0.0516])

print(norm.running_var)
> tensor([nan, nan, nan])
```

Calling `norm.eval()` seems to work fine in this case.

Should we reopen this issue or track it separately? 
CC @albanD (as discussed offline, also sorry for the late report)

**Comment by albanD** [comment]
It might be better to get a fresh issue for that given that it is a slightly different example and the discussion here won't be relevant :)

**Comment by yahyaezzeldin** [comment]
I am not sure if this is an intended consequence of this issue's fix, but to me it seems to break the performance of GroupNorm in evaluation when applied on input with batchsize=1. See the following **example** below

```
import torch
import torch.nn as nn

m = nn.GroupNorm(6, 6)
m.eval()

input = torch.randn(1,6,1)
output = m(input)
```

which gives the **error**

`Expected more than 1 value per channel when training, got input size [1, 6, 1]`
