### ISSUE TITLE
Building for ROCm Fails

### ISSUE THREAD

**Issue by jghawaly** [pytorch/pytorch#19251]
## Issue description

I am trying to install Pytorch with ROCm for perform calculation on an AMD Radeon VII GPU. I first cloned the pytorch repository and then run the following lines in the terminal, the first four of which succeed without error:
- cd pytorch
- git submodule init 
- git submodule update
- python tools/amd_build/build_amd.py
- USE_ROCM=1 python setup.py install

The compilation gets about 71% of the way through and fails with the following errors:
```
/home/CODE/lib/pytorch/aten/src/THH/THHStorage.hip:4:10: fatal error: 'thrust/device_ptr.h' file not found
#include <thrust/device_ptr.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
/home/CODE/lib/pytorch/aten/src/THH/THHTensorMath.hip:11:10: fatal error: 'thrust/copy.h' file not found
#include <thrust/copy.h>
         ^~~~~~~~~~~~~~~
1 error generated.
/home/CODE/lib/pytorch/aten/src/THH/THHStorage.hip:4:10: fatal error: 'thrust/device_ptr.h' file not found
#include <thrust/device_ptr.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
CMake Error at /opt/rocm/hip/cmake/FindHIP/run_make2cmake.cmake:18 (file):
  file failed to open for reading (No such file or directory):

    /home/CODE/lib/pytorch/build/caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THH/caffe2_hip_generated_THHStorage.hip.o.depend.pre


CMake Error at caffe2_hip_generated_THHStorage.hip.o.cmake:134 (message):
  Error generating
  /home/CODE/lib/pytorch/build/caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THH/./caffe2_hip_generated_THHStorage.hip.o


caffe2/CMakeFiles/caffe2_hip.dir/build.make:84: recipe for target 'caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THH/caffe2_hip_generated_THHStorage.hip.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THH/caffe2_hip_generated_THHStorage.hip.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 71%] Building CXX object caffe2/torch/lib/THD/CMakeFiles/THD.dir/base/Cuda.cpp.o
/home/CODE/lib/pytorch/aten/src/THH/THHTensorMath.hip:11:10: fatal error: 'thrust/copy.h' file not found
#include <thrust/copy.h>
         ^~~~~~~~~~~~~~~
1 error generated.
CMake Error at /opt/rocm/hip/cmake/FindHIP/run_make2cmake.cmake:18 (file):
  file failed to open for reading (No such file or directory):

    /home/CODE/lib/pytorch/build/caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THH/caffe2_hip_generated_THHTensorMath.hip.o.depend.pre


CMake Error at caffe2_hip_generated_THHTensorMath.hip.o.cmake:134 (message):
  Error generating
  /home/CODE/lib/pytorch/build/caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THH/./caffe2_hip_generated_THHTensorMath.hip.o
```

## Code example

The above process is what triggers this error, I have tested it with the ROCm fork of pytorch and the official branch, both of which produce the same error.

## System Info

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0

I am using ROCm version 2.3.14 with a Radeon VII GPU (gfx906).

**Comment by colesbury** [comment]
Did you install https://github.com/ROCmSoftwarePlatform/Thrust ?

I believe the recommended method is to use the ROCm PyTorch docker image.

https://rocm-documentation.readthedocs.io/en/latest/Deep_learning/Deep-learning.html#pytorch

**Comment by jghawaly** [comment]
Yes ROCm Thrust is installed. The ROCm pytorch docker does work, however I do not want to have to work with it within a docker, so I was hoping to find a way to compile PyTorch for ROCm. Has there been any reported success doing this recently? All of the tutorials and examples I have seen are either very old or incomplete.

**Comment by colesbury** [comment]
cc @iotamudelta

**Comment by iotamudelta** [comment]
Indeed the recommended method is to use the docker image as discussed here: https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm

We do not currently officially support compilation on the host. A user provided a howto here: https://github.com/ROCmSoftwarePlatform/pytorch/issues/337#issuecomment-467220107 which apparently works well.
