### ISSUE TITLE
[CUDA] torch::stack / torch::cat fails on a single element

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#19252]
## 🐛 Bug

Sometimes my vector is only 1 element, for example:
`std::vector<torch::Tensor> in = { tensor.reshape(1,128,128) };`

When calling torch::stack on this tensor vector when using CUDA, I get a crash.

> CUDA error: invalid argument (copy_device_to_device at C:/w/1/s/windows/pytorch/aten/src/ATen/native/cuda/Copy.cu:101)
> (no backtrace available)

Workaround looks like this:
`auto test = in.size() == 1 ? in.front().reshape({1,1,128,128}) : torch::stack(in);`

## To Reproduce

1. Use CUDA backed tensor
2. `std::vector<torch::Tensor> in= { tensor };`
3. `auto test = torch::stack(in)`
4. Experience crash 

## Expected behavior

Should just reshape to 1,1,128,128 as expected

## Environment

 - PyTorch Version (e.g., 1.0): 1.1.0-pre
 - OS (e.g., Linux): Windows 64-bit
 - How you installed PyTorch (`conda`, `pip`, source): nightly
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0/7.5
 - GPU models and configuration: 1060

## Additional context

Happens with torch::cat as well. Doesn't happen on CPU

**Comment by gchanan** [comment]
fwiw this doesn't reproduce directly in python -- that doesn't mean it's not real, but I can't off the top of my head figure out why it would only happen in C++.

**Comment by xsacha** [comment]
Yes I'm not sure why it is C++ only but I suppose the functions may be implemented differently because of pythons inbuilt operators differing from C++.

**Comment by prasunanand** [comment]
Hi, I am from @quansight team. I would like to work on this issue.

**Comment by xsacha** [comment]
I'm not seeing this issue on the latest master. I assume it was fixed somewhere?
