### ISSUE TITLE
Implement of torch.spmm

### ISSUE THREAD

**Issue by HanYuanyuaner** [pytorch/pytorch#19256]
Hi,

When I use torch.spmm, I can not find the Implement code of it. Dose it call cusparse to speed up sparse multiplication on GPU?

**Comment by colesbury** [comment]
@HanYuanyuaner we use the issue tracker for bug reports and feature requests. Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions.

See also 
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu
