### ISSUE TITLE
checkpoint_sequential doesn't respect nn.Sequential's behavior

### ISSUE THREAD

**Issue by sublee** [pytorch/pytorch#19260]
## 🐛 Bug

There's an inconsistency between `nn.Sequential` and `checkpoint_sequential`:

```python
model = nn.Sequential(...)
model(a, b) # TypeError!
checkpoint_sequential(model, 1, a, b) # OK.
```

`nn.Sequential` passes only one input for each layer regardless of type. If we pass a tuple as an input, the first layer will take the tuple as an argument. `checkpoint_sequential` is a checkpointing helper for a sequential module. So it should work just like a vanilla sequential module. But actually, it unwraps an input if it's a tuple, then passes them to the first layer as `*args`.

Here are 2 inconsistency problems:
- If a layer takes multiple inputs, `nn.Sequential` disallows by `TypeError` while `checkpoint_sequential` works well.
- If a layer takes a 1-tuple as an input, there's no way to use `checkpoint_sequential` because it unwraps every tuple. But `nn.Sequential` works well.

## To Reproduce

1. Make a module which takes two inputs.
1. Wrap the module with `nn.Sequential` and call it with two inputs. It's illegal. `TypeError` will be raised.
1. Wrap the above sequential module with `utils.checkpoint.checkpoint_sequential` and call again. Now it's legal. There's no problem anymore.

```python
import torch
import torch.utils.checkpoint

class Two(torch.nn.Module):
    def forward(self, a, b):
        return a, b
model = torch.nn.Sequential(Two())

a = torch.rand(1)
b = torch.rand(1)

torch.utils.checkpoint.checkpoint_sequential(model, 1, a, b)  # OK
model(a, b)  # TypeError!
# TypeError: forward() takes 2 positional arguments but 3 were given
```

## Expected behavior

One of:
- `checkpoint_sequential` should not change `nn.Sequential`'s input and output restriction.
- `nn.Sequential` supports multiple inputs (`*args`) and outputs. Always unwrap tuples.

## Environment

```
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 410.104
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] torch==1.0.1.post2
[pip] torchvision==0.2.2.post3
[pip] torchviz==0.0.1
[conda] Could not collect
```

## Additional context

Related discussions:
- https://discuss.pytorch.org/t/sequential-lstm-ii/9169 Sequential LSTM II
- https://github.com/pytorch/pytorch/issues/3349#issuecomment-340240011 "Sequential is reserved for the most simple cases."
- #11093 Only one argument is used in checkpoint_sequential
- #14278 Make checkpoint_sequential work with multiple arguments

**Comment by colesbury** [comment]
> If a layer takes a 1-tuple as an input, there's no way to use checkpoint_sequential because it unwraps every tuple. But nn.Sequential works well

This sounds like the crux of the problem to me. I don't think it's worth changing `nn.Sequential`

**Comment by sublee** [comment]
@colesbury Thank you for tagging and your response! :)

My goal is consistency between `nn.Sequential` and `checkpoint_sequential`. I think that one of those should be changed. I wonder why don't you think it's worth changing `nn.Sequential`. Is the inconsistency not so bad? Or `checkpoint_sequential` should be changed rather than `nn.Sequential`?

Actually, I thought wrong about 1-tuple as an argument. There's a way to handle it in `checkpoint_sequential`. If a layer returns `((x,),)`, the next layer will take `(x,)` as an argument. Because `checkpoint_sequential` unwraps an outermost tuple only.

So I prefer `checkpoint_sequential`'s interface (`*args`) rather than `nn.Sequential`'s one (only one argument.) Because it is more flexible: `checkpoint_sequential` supports both one and more inputs without restriction while `nn.Sequential` has no capability to support multiple inputs.

```diff
  class Sequential(Module):
      ...
-     def forward(self, input):
+     def forward(self, *input):
          for module in self._modules.values():
-             input = module(input)
+             input = module(*input)
+             if not isinstance(input, tuple):
+                 input = (input,)
          return input
```

**Comment by sublee** [comment]
Originally, I thought `checkpoint_sequential`'s interface (supporting `*args`) is better than `nn.Sequential`'s one. But if we make `nn.Sequential` also support multiple inputs, it seems to bring one more problem.

Currently, nested sequential models can be flattened. For example, `nn.Sequential(nn.Sequential(a, b), nn.Sequential(c, d))` can be flattened as `nn.Sequential(a, b, c, d)`. Because all the inputs and outputs are always compatible among all layers.

```
ab(x) -> b(a(x))
cd(x) -> d(c(x))
abcd(x) -> cd(ab(x)) = d(c(b(a(x)))
```

But if `nn.Sequential` works like `checkpoint_sequential`, they couldn't be flattened anymore. The tuple unwrapping is not performed at a boundary between two sequential models. Even `b` returns a tuple `args`, `c(args)` instead of `c(*args)` is called. But after flattening, the return value of `b` is unwrapped for `c`. So now, `c(*args)` is called instead.

**Comment by sublee** [comment]
My above comment was wrong.

Even `nn.Sequential` works like `checkpoint_sequential`, nested sequential modules could be flattened without losing semantics. I've lost it calls always `*args` instead of `args`.

```python
class NewSequential(torch.nn.Module):

    def __init__(self, *modules):
        super().__init__()
        for i, module in enumerate(modules):
            self.add_module(str(i), module)

    def forward(self, *args):
        for module in self.children():
            if not isinstance(args, tuple):
                args = (args,)
            args = module(*args)
        return args

model1 = NewSequential(NewSequential(a, b), NewSequential(c, d))
model2 = NewSequential(a, b, c, d)

assert model1(x) == model2(x)
```

Now I agree with both interfaces if they satisfy any consistency.

**Comment by apaszke** [comment]
Honestly I think it's `nn.Sequential` semantics which we should keep. It's way more common and it makes sense to pass the inputs that way when you compose the functions sequentially.

**Comment by sublee** [comment]
@apaszke Thank you for your opinion. I also agree with you. Both approaches work well but `nn.Sequential`'s approach is simpler and more straightforward.

If so, shouldn't we revert the `tuple` specialization of `checkpoint_sequential`?

**Comment by soumith** [comment]
I think we should revert the `tuple` specialization of `checkpoint_sequential`, or provide it as an option` in the constructor.
@sublee are you interested in providing a PR?

**Comment by sublee** [comment]
@soumith Yes, I am. It would be my pleasure.

When `checkpoint_sequential` takes `len(args) != 1`, I think it should raise `DeprecationWarning` for PyTorch 1.1.x. This specialization should be completely reverted at PyTorch 1.2.0. Do you agree with this approach?

**Comment by soumith** [comment]
@sublee i agree with this approach

**Comment by sublee** [comment]
I just deprecated the multiple or no inputs to `checkpoint_sequential` at https://github.com/pytorch/pytorch/commit/ffdce79078438c8722eccc87d9d68396559b97e4.

@soumith Thanks to pulling it. I'll send a new pull request to completely deprecate it when you're releasing PyTorch 1.3.0.
