### ISSUE TITLE
Compiling pytorch from source error:  [Errno 13] Permission denied for SOURCES.txt

### ISSUE THREAD

**Issue by rmchurch** [pytorch/pytorch#19269]
## 🐛 Bug

Compiling pytorch from source in a conda environment compiles the code (i.e. reaches 100%), but fails in the egg install due to a permissions issue. I am the owner of this directory (no need for sudo), its just the SOURCES.txt file which doesn't have write permissions, but this file appears to be created by the install each time. 

## To Reproduce

1. conda create -n pytorch-source python=3.7 anaconda
2. source activate pytorch-source 
3. (follow instructions https://github.com/pytorch/pytorch#from-source)

Error during "python setup.py install":
> running install_egg_info
running egg_info
creating torch.egg-info
writing torch.egg-info/PKG-INFO
writing dependency_links to torch.egg-info/dependency_links.txt
writing entry points to torch.egg-info/entry_points.txt
writing top-level names to torch.egg-info/top_level.txt
writing manifest file 'torch.egg-info/SOURCES.txt'
reading manifest file 'torch.egg-info/SOURCES.txt'
writing manifest file 'torch.egg-info/SOURCES.txt'
Copying torch.egg-info to /scratch/gpfs/me/conda-envs/pytorch-source/lib/python3.7/site-packages/torch-1.1.0a0+68c4ebb-py3.7.egg-info
error:  [Errno 13] Permission denied: '/scratch/gpfs/me/conda-envs/pytorch-source/lib/python3.7/site-packages/torch-1.1.0a0+68c4ebb-py3.7.egg-info/SOURCES.txt'

## Expected behavior

This may be a general conda environments issue, but in a search I couldn't find anything specific to a file like this being written, only where there were obvious folder permission errors (which this is not).

## Environment

Collecting environment information...
PyTorch version: 1.1.0a0+68c4ebb
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Springdale Linux release 7.6 (Verona)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 418.39
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.1.0a0+68c4ebb
[conda] blas                      1.0                         mkl
[conda] magma-cuda90              2.5.0                         1    pytorch
[conda] mkl                       2019.3                      199
[conda] mkl-include               2019.3                      199
[conda] mkl-service               1.1.2            py37he904b0f_5
[conda] mkl_fft                   1.0.10           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0

Not sure why the collect_env.py script doesn't find cuDNN, in the python setup.py install it is found:
-- Found CUDNN: /usr/local/cudnn/cuda-9.0/7.0.3/include
-- Found cuDNN: v7.0.3  (include: /usr/local/cudnn/cuda-9.0/7.0.3/include, library: /usr/local/cudnn/cuda-9.0/7.0.3/lib64/libcudnn.so.7)

**Comment by ezyang** [comment]
This is almost certainly not our problem. Here is how I would debug it:

```
# Double check that it is in fact root owned
ls -l /scratch/gpfs/me/conda-envs/pytorch-source/lib/python3.7/site-packages/torch-1.1.0a0+68c4ebb-py3.7.egg-info/SOURCES.txt
# sudo delete it (if you own the directory, not even necessary; just rm -f)
sudo rm /scratch/gpfs/me/conda-envs/pytorch-source/lib/python3.7/site-packages/torch-1.1.0a0+68c4ebb-py3.7.egg-info/SOURCES.txt
# Run python setup.py install, definitely /don't/ run it with sudo
python setup.py install
```

If the error still occurs after following these steps exactly, I would strace python setup.py install to figure out when the root owned file is being created.

Reopen this issue if you need more help.
