### ISSUE TITLE
[jit] Do not infer empty list(e.g., List[Tuple[int,int]] to be of type List[Tensor]

### ISSUE THREAD

**Issue by yelu** [pytorch/pytorch#19303]
## 🚀 Feature
An empty generic list is deduced to be List[Tensor]. The C++ api infers the element type by inspecting the first element in the list. I don't think this is good design.

As a serious and formal toolkit, it should allow an empty list of **any type**.

**Comment by apaszke** [comment]
It does allow lists of any type, you just need to annotate them if the default doesn't match. Try `torch.jit.annotate(List[Tuple[int, int]], [])`.

**Comment by eellison** [comment]
The C++ API allows empty lists, they need to be constructed correctly, which is currently poorly documented and difficult to do. 

#17165 is open to track that. I'm not sure of the issue you are opening here

**Comment by ailzhang** [comment]
Closing via 

> It does allow lists of any type, you just need to annotate them if the default doesn't match. Try `torch.jit.annotate(List[Tuple[int, int]], [])`.

Please feel free to reopen if it doesn't solve your issue. Thanks!

**Comment by yelu** [comment]
> It does allow lists of any type, you just need to annotate them if the default doesn't match. Try `torch.jit.annotate(List[Tuple[int, int]], [])`.

Let me clarify, to work with a pytorch script, there are two parts:
1. a python script to be future exported to "my_script.pt". This python part is stable. e.g.
```python
@torch.jit.script
def MyScriptFun(input_fs:Tuple[List[Tuple[int,float,int,int]], List[Tuple[str,float,int,int]]]) -> Tuple[Tuple[List[Tuple[int,float,int,int]], List[Tuple[str,float,int,int]]]]:
    sum1, sum2, sum3, sum4 = 0, 0.0, 0, 0
    for i in range(len(input_fs[0])):
        sum1 += input_fs[0][i][0]
        sum2 += input_fs[0][i][1]
        sum3 += input_fs[0][i][2]
        sum4 += input_fs[0][i][3]
    q, sum2, sum3, sum4 = "", 0.0, 0, 0
    for i in range(len(input_fs[1])):
        q += " "
        q += input_fs[1][i][0]
        sum2 += input_fs[1][i][1]
        sum3 += input_fs[1][i][2]
        sum4 += input_fs[1][i][3]
    return (([(sum1, sum2, sum3, sum4)], [(q, sum2, sum3, sum4)]),)
```

2. The libtorch C++ api loads the "my_script.pt". Then you have to construct input with C++ api. Those C++ APIs are buggy. In the forward function, there are some checks. It will fail in two cases:
  * Tuple[List[Tuple[int,float,int,int]], List[Tuple[str,float,int,int]]] cannot pass type check.
  * An empty list is infered to List[Tensor].
```C
// Execute the model and turn its output into a tensor.
auto output_vec = module->forward(input_vec).toTuple()->elements();
```

I feel the C++ apis are not well implemented. Do I use it in the wrong way?

**Comment by yelu** [comment]
> Closing via
> 
> > It does allow lists of any type, you just need to annotate them if the default doesn't match. Try `torch.jit.annotate(List[Tuple[int, int]], [])`.
> 
> Please feel free to reopen if it doesn't solve your issue. Thanks!

I confirm it works with the latest nigthly build. Thanks for your reply.
