### ISSUE TITLE
libtorch gpu efficiency

### ISSUE THREAD

**Issue by LoveZL0512** [pytorch/pytorch#19305]
## To Reproduce
here is my code

auto out = faceDetect->forward({ tensor_image }).toTuple();
c10::cuda::CUDACachingAllocator::emptyCache();
...some tensor ops on gpu
boundingBoxesOfOne = torch::masked_select(boundingBoxesOfOne, mask);

faceDetect is a sfd net,after forward(),if i call emptyCache(),it will cost 170ms time to emptyCache;if i don't call emptyCache(),masked_select will cost 170ms;so i don't know how to optimize this situation，thks！

## Environment

libtorch Version 1.0 :
OS windows10:
CUDA/cuDNN version: 9.0
GPU models and configuration: GTX 1060

**Comment by SsnL** [comment]
CUDA is asynchronous. The time duration you observed is the time needed to forward though the network.

**Comment by LoveZL0512** [comment]
> CUDA is asynchronous. The time duration you observed is the time needed to forward though the network.

forward() has cost time ，the result out has got,so is that cuda need to empty cached memory asynchronously？but 170ms is too long？
or you mean the result out has not got,when i access the variable，it will cost time to wait result out？
if it is the second situation，how to set CUDA operations synchronous？thks！

**Comment by LoveZL0512** [comment]
> > CUDA is asynchronous. The time duration you observed is the time needed to forward though the network.
> 
> forward() has cost time ，the result out has got,so is that cuda need to empty cached memory asynchronously？but 170ms is too long？
> or you mean the result out has not got,when i access the variable，it will cost time to wait result out？
> if it is the second situation，how to set CUDA operations synchronous？thks！

one more question,one image convert to tensor to forward() cost 200ms,three same images cat to a tensor to forward() cost 590ms,that means a batch images to forwad() is serial not parallel?

**Comment by soumith** [comment]
`CUDA_LAUNCH_BLOCKING=1` environment variable will make cuda calls synchronous (at the cost of some performance). You can also do `torch.cuda.synchronize()` or in C++ simply `cudaSynchronize` from the CUDA API.

**Comment by soumith** [comment]
if you have questions, ask on https://discuss.pytorch.org

**Comment by yinxiaochuan** [comment]
I also think this is a bug. I convert a pytorch model to cpp w/ and w/o mask_seleced operator. The inference  time in cpp will increase about 60ms.

**Comment by LoveZL0512** [comment]
CUDA is asynchronous. The time duration you observed is the time needed to forward though the network.




------------------ 原始邮件 ------------------
发件人: "yinxiaochuan"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 晚上6:09
收件人: "pytorch/pytorch"<pytorch@noreply.github.com>;
抄送: "风宇同邹"<634162865@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pytorch/pytorch] libtorch gpu efficiency (#19305)




I also think this is a bug. I convert a pytorch model to cpp w/ and w/o mask_seleced operator. The inference  time in cpp will increase about 60ms.
