### ISSUE TITLE
Libtorch Doc edit Minimal example

### ISSUE THREAD

**Issue by CoderHam** [pytorch/pytorch#19326]
## 📚 Documentation

The documentation for the current nightly version of libtorch (Available at https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip ,
 as mentioned by the docs) is not consistent with the actual way it works. Minor bug. In specific:

https://pytorch.org/cppdocs/installing.html#minimal-example

We can now run the following commands to build the application from within the example-app/ folder:

```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/libtorch ..
make
```

should be:

```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/libtorch ..
cd ..
make
```

Since after running cmake, build files are written one directory above

```-- Build files have been written to: /example-app```
instead of the expected 
```-- Build files have been written to: /example-app/build```

i.e. the `example-app` binary is not found in the `example-app/build` directory but instead is found in the directory one level above it (`example-app`) .

**Comment by VitalyFedyunin** [comment]
Thanks for reporting, will fix shortly.

**Comment by vishwakftw** [comment]
This has been fixed in https://github.com/pytorch/pytorch/commit/ff4a4d615582e9d5d4941405323fea96da04d9d7.
