### ISSUE TITLE
C10_DEPRECATED_USING    error: attribute does not apply to any entity

### ISSUE THREAD

**Issue by asa008** [pytorch/pytorch#19336]
## 🐛 Bug
ArrayRef.h 
C10_DEPRECATED_USING    error: attribute does not apply to any entity
win10, cuda10.0, VS2017 15.7.6, pytorch 1.0.1 source install
## To Reproduce

I install pytorch from newest source to get libtorch library on win10 successfully.
However when I first build a visual studio project, the error occur at line 273:
using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
saying error: attribute does not apply to any entity
if I annotated this line, it will build successfully, will annotating this line lead to any bad result?
How to fix this error appropriately?

If I first annotate the line to build project successfully, then unannotate the line, the project can still build successfully. But if I do nothing at the first time, the project cannot be built because of the mentioned error.

pytorch\torch\include\c10\util\ArrayRef.h 
```
271  // This alias is deprecated because it doesn't make ownership
272  // semantics obvious.  Use IntArrayRef instead!
273  using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
```

## Environment

 - PyTorch Version (e.g., 1.0):  pytorch cpp 1.0.1
 - OS (e.g., Linux): win10
 - How you installed PyTorch (`conda`, `pip`, source): source 
 - Build command you used (if compiling from source):
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.11

python setup.py install

 - Python version: 3.6.6
 - CUDA/cuDNN version:  CUDA10.0  cuDnn 7.5
 - GPU models and configuration:  RTX 2080
 - Any other relevant information:  VS 2017 15.7.6

## Additional context

thanks for any reply

**Comment by asa008** [comment]
this bug can be fixed by turning off /permissive:
Configuration Properties -> C/C++ -> Laguage -> Conformance mode ： No

**Comment by VitalyFedyunin** [comment]
Please reopen this issue if you are not satisfied with provided solution.

**Comment by WillemvJ** [comment]
I have the same problem it seems. I am using cmake, with ninja. Not sure how to turn off /permissive.

**Comment by VitaMusic** [comment]
the problem is not solved for intel compilers. how to do it for intel compilers ? is it possible just comment the line 278 of ArrayRef.h ?

**Comment by ShannonZ** [comment]
I have the same problem using VS2017.  Conformance mode has set  to NO. But I still get the same error: attribute does not apply to any entity

**Comment by JesperLindberg** [comment]
I got the same issue on both "stable" build and nightly build.
First this error and when compiling I get another 388 warnings and 3 more errors.

Anyone got any news on this issue?

**Comment by peterjc123** [comment]
I believe it is a false negative for VS. Because the error is only reported by Intellisense and build succeeds even with this error.

**Comment by zhengge** [comment]
> I have the same problem using VS2017. Conformance mode has set to NO. But I still get the same error: attribute does not apply to any entity
@ShannonZ I have the same problem with you. Did you solve it?
