### ISSUE TITLE
libtorch forward efficiency  synchroni

### ISSUE THREAD

**Issue by LoveZL0512** [pytorch/pytorch#19343]
## 🐛 Bug
![image](https://user-images.githubusercontent.com/11365001/56267119-79b0fa00-6120-11e9-9b1d-cbebf41fb67f.png)

**Comment by VitalyFedyunin** [comment]
Hi! Can you please add url of the original issue and describe what is the problem statement.

**Comment by soumith** [comment]
duplicate of https://github.com/pytorch/pytorch/issues/19305
