### ISSUE TITLE
add .np() instead of ".cpu().numpy()"

### ISSUE THREAD

**Issue by danFromTelAviv** [pytorch/pytorch#19357]
I use .cpu().numpy() very frequently to debug. Its awesome!
I think it would be even more awesome if it was shorter for example : tensor.np() or to_np() or something like that.
Obviously, numpy assumes cpu so there's really no point in writing both of those functions. and "np" is very well recognized as shorthand for numpy.

Thanks and please.

**Comment by VitalyFedyunin** [comment]
We would gladly accept PR changing numpy() call functionality to automatically copy tensor from a GPU device.

**Comment by danFromTelAviv** [comment]
Cool. Can you direct me where the class tensor is defined?

**Comment by danFromTelAviv** [comment]
fatal: HttpRequestException encountered.
   ????? ????? ????? ????? ?????.
remote: Permission to pytorch/pytorch.git denied to danFromTelAviv.
fatal: unable to access 'https://github.com/pytorch/pytorch.git/': The requested URL returned error: 403
Do you need to give me permission to pr?

**Comment by VitalyFedyunin** [comment]
Hi!
1) To make PR you need to fork repo first. Please refer to the github documentation. 
2) Also on the second thought, it is better if you implement own wrapper to make this conversion. 
The reason behind it is the contract of numpy() function. Currently, it returns numpy object which shares memory with CPU Tensor. If we are going to convert Cuda tensors, it is not going to be the case anymore. And users rely on this functionality and might get confused. 

But locally you can always do something like:
```
def copy_as_numpy(x):
  return t.cpu().numpy() 
torch.Tensor.copy_as_numpy = copy_as_numpy
```

**Comment by danFromTelAviv** [comment]
o yeah ... :man_facepalming:
