### ISSUE TITLE
DataLoader consumes much more memory than needed

### ISSUE THREAD

**Issue by h6197627** [pytorch/pytorch#19355]
## ❓ Questions and Help
During training process workers are created for preparing data batches. They are created with multiprocess by forking main process.
Considering ordinary training loop:
```
for epoch in range(...):
    for batch in dataloader: # Here worker processes are created
        # train step
    # Here worker processes are disposed
```
during creation of workers it will copy initialized in main thread model to each of the worker process.
For example, [ImageNet sample from pytorch/examples](https://github.com/pytorch/examples/blob/5df464c46cf321ed1cc3df1e670358d7f5ae1887/imagenet/main.py#L272):
before that line main process with ResNet18 take ~1.2GB, but during execution of that line 4 more processes (4 workers settings) are started each taking the same amount of memory as main process. It is big overhead (bigger models takes even more RAM) as in reality data preparation workers do not need to have model and many other optimizer/solver objects at all.
So I am doubting: is it a PyTorch problem or intended by design or maybe I am simply misusing DataLoader functionality?

**Comment by VitalyFedyunin** [comment]
Hi! Can you please clarify couple things:
 1) We are talking about CPU memory patterns, right?
 2) Are you using torch.multiprocessing or any other method of sharing data?

**Comment by h6197627** [comment]
Hi @VitalyFedyunin,
1. Yes, I am speaking about CPU RAM
2. No, I do not use torch.multiprocessing in my code explicitly. I am able to reproduce such behavior with vanilla ImageNet sample from pytorch/examples

I have tried to move DataLoader initialization code in the beginning of the training code (before model initialization code) and to ask explicitly iterator with **iter(dataloader)** - it starts workers with much lower memory footprint. However, workers are disposed and recreated each epoch, so eventually it will consume more memory

**Comment by h6197627** [comment]
Sorry, I think I am mistaken - probably it is the same shared memory between processes. System monitor showing these processes separately like each owning that much memory and only small amount of shared memory (like in attached picture with 2 workers and main thread).
![memory](https://user-images.githubusercontent.com/44726212/56310441-8bac9000-6154-11e9-89cd-b8137b5fd2eb.png)
However, command line Linux tools shows that the real memory consumption is according to process with highest memory footprint
Really sorry for wasting time!

**Comment by VitalyFedyunin** [comment]
That was my next assumption, if you are using fork, it will use copy-on-write approach and all forked processes will think they own memory.
