### ISSUE TITLE
Linking torch libraries and yaml-cpp gives undefined reference to yaml-cpp libraries

### ISSUE THREAD

**Issue by JunhongXu** [pytorch/pytorch#19353]
I want to use yaml-cpp library to parse some configuration file, but when I link yaml-cpp and libtorch together, I got undefined reference to `YAML::LoadFile()`. 

File main.cpp:
```
#include "yaml-cpp/yaml.h"

int main()
{
    std::string filename = "config.yaml"
    auto node = YAML::LoadFile(filename);
}
```

File CMakeLists.txt
```
cmake_minimum_required(VERSION 3.0)
set(CMAKE_PREFIX_PATH path_to_libtorch)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(PROJECT_NAME test_yaml)

project(${PROJECT_NAME})

find_package(yaml-cpp REQUIRED)
find_package(Torch REQUIRED)

add_executable(${PROJECT_NAME} main.cpp) 

target_link_libraries(${PROJECT_NAME}
    PUBLIC 
    ${YAML_CPP_LIBRARIES}
    ${TORCH_LIBRARIES} # when this is commented out, no error occurs.
    )
target_include_directories(${PROJECT_NAME} 
            PUBLIC 
            ${YAML_CPP_INCLUDE_DIR}
)
```
When I link with both libtorch and yaml-cpp, I got the following error:

> main.cpp:(.text+0xf1): undefined reference to `YAML::LoadFile(std::string const&)'
collect2: error: ld returned 1 exit status

But without linking to libtorch, the build succeeded.

**Comment by VitalyFedyunin** [comment]
Hi! Can you please provide following information:

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:


As well as yaml-cpp library version.

**Comment by JunhongXu** [comment]
Hi. The following is my environment:
```
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.12.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.252
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 396.54
cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] numpydoc==0.8.0
[pip] torch==1.0.1.post2
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-service               1.1.2            py36he904b0f_5  
[conda] mkl_fft                   1.0.11           py36h14c3975_0    conda-forge
[conda] mkl_random                1.0.2            py36h637b7d7_2    conda-forge
[conda] pytorch                   1.0.1           py3.6_cuda9.0.176_cudnn7.4.2_2    pytorch
[conda] torchvision               0.2.2                      py_3    pytorch

```
But I built the program using LibTorch from the link: https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-latest.zip

I downloaded yaml-cpp using the pre-built binary via this command:
`sudo apt-get install libyaml-cpp-dev`

**Comment by farg967** [comment]
Hi, I am having the same problem but with dart libraries (for robotics)

main.cpp
`//#include <torch/torch.h>
#include <iostream>
#include <dart/dart.hpp>
#include <dart/gui/gui.hpp>

using namespace dart::dynamics;
using namespace dart::simulation;

int main() {
  //torch::Tensor tensor = torch::eye(3);
  //std::cout << tensor << std::endl;

  SkeletonPtr vehicle = Skeleton::create("vehicle");
}`

CMakeLists.txt

`cmake_minimum_required(VERSION 3.5.1)

if(DART_IN_SOURCE_BUILD)
  include(${CMAKE_CURRENT_SOURCE_DIR}/InSourceBuild.cmake)
  return()
endif()

project(pyTorchCheck)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)

find_package(DART 6.6.0 REQUIRED COMPONENTS utils-urdf gui CONFIG)
find_package(Qt5Core)
set(CMAKE_PREFIX_PATH /usr/lib/libtorch/share/cmake/Torch)
find_package(Torch REQUIRED)

add_executable(${PROJECT_NAME} "main.cpp")

target_link_libraries(${PROJECT_NAME} PUBLIC dart dart-utils-urdf dart-gui Qt5::Core
  ${TORCH_LIBRARIES}) #When I comment out ${TORCH_LIBRARIES} it works fine `

When I link both I get the following error...

> error: undefined reference to `dart::dynamics::Skeleton::create(std::string const&)'

As above, without linking to torch libraries the build succeeds

I downloaded dart libraries with 

> sudo apt-get install libdart6-all-dev

**Comment by lsrock1** [comment]
I have same error with yaml-cpp and gtest

test subdirectory's cmakelists
`
# Target name
set(target UnitTests)

# Sources
file(GLOB sources
    ${CMAKE_CURRENT_SOURCE_DIR}/*/*.cpp)

# Build executable
add_executable(${target}
    test.cpp
    ${sources})

# Link libraries
target_link_libraries(${target}
    PRIVATE
    gtest
    maskrcnn
    ${TORCH_LIBRARIES})`

in cpp file

`#include "gtest/gtest.h"

#include <defaults.h>

using namespace rcnn::config;

TEST(defaults, SetCFGFromFile)
{
    CFGString model_weight = GetCFG<CFGString>({"MODEL", "WEIGHT"});
    //check if default empty, yaml exists
    EXPECT_STREQ("catalog://ImageNetPretrained/MSRA/R-50", model_weight.get());

    double lr = GetCFG<double>({"SOLVER", "BASE_LR"});
    //check if default exists, yaml exists
    EXPECT_EQ(lr, 0.01);
    
    bool stride1x1 = GetCFG<bool>({"MODEL", "RESNETS", "STRIDE_IN_1X1"});
    //check if default exists, yaml empty
    EXPECT_EQ(stride1x1, true);
}`

**Comment by goncamateus** [comment]
Any update about it?

**Comment by sjdrc** [comment]
We're seeing this same issue occur when linking libtorch and our internal library.

**Comment by sjdrc** [comment]
Could someone from the dev team please comment on this issue? You're currently shipping code that doesn't integrate properly.

**Comment by soumith** [comment]
our shipped binaries are with `_GLIBCXX_USE_CXX11_ABI=0` because they are compiled with gcc 4.9.2. your `yaml-cpp` library was compiled with `_GLIBCXX_USE_CXX11_ABI=1`, so likely gcc >= 5. The function that is failing to link on yaml-cpp side has std::string in it's prototype, and the ABI is different for std::string with and without this flag.

Two solutions exist:
- compile pytorch / libtorch from source with gcc >= 5
- compile the yaml-cpp binary that you are using with gcc < 5 or with gcc >= 5 but with the definition `-D_GLIBCXX_USE_CXX11_ABI=0`.

You can read more at https://docs.computecanada.ca/wiki/GCC_C%2B%2B_Dual_ABI and http://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by sjdrc** [comment]
gcc 4.9.2 was released on October 30, 2014.
Do you plan to switch to a newer version of GCC at some point?

**Comment by soumith** [comment]
we plan to provide CXX11 ABI libtorch binaries, but progress has been slow. this is tracked in https://github.com/pytorch/pytorch/issues/17492

**Comment by federicotomat** [comment]
Hi @soumith,
I have the same problem but none of the solutions listed above works.
My problem consists in linking torch libraries in a project where another internal library is linked (YARP).

**Comment by inflex56** [comment]
@federicotomat,

I've experienced the same issue recently, having a complex project with yarp, gazebo, cuda and fcl. Project was compiling, but adding  ${TORCH_LIBRARIES} in cmake's target_link_libraries resulted in multiple "undefined references" from fcl and yarp. Notably, all problematic functions had std::string in the signature. 
Solution that worked for me: downloading cxx11ABI libtorch (cpu version) from https://pytorch.org/get-started/locally/ (current link - https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.5.1%2Bcpu.zip), and replacing initially installed version (seems to me that by default users still download pre-cxx11abi release).

Hope that helps.

**Comment by federicotomat** [comment]
Hi @inflex56, 

Thank you very much. With your solution I solved all the problems.
