### ISSUE TITLE
Printing gc.get_objects() makes Runtime Error when importing torch

### ISSUE THREAD

**Issue by Ricocotam** [pytorch/pytorch#19351]
## 🐛 Bug

I'd like to print the return of the `gc.get_objects()` function (I have memory issues) but I can't. Whenever I do it, I get the following error :
```python
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(gc.get_objects())
  File "<frozen importlib._bootstrap>", line 302, in _module_repr
  File "<frozen importlib._bootstrap>", line 295, in _module_repr
  File ".../site-packages/torch/_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator __file__::__file__
```
But what's more strange is that using the length are affecting it to a variable (not printing it) doesn't produce an error.

## To Reproduce

I'm using python3.7.0 and latest version of pytorch (1.0.1.post2). Just run the following code in a file :
```python
import gc
import torch
print(len(gc.get_objects))  # Works
a = gc.get_objects()  # works
print(gc.get_objects())  # Fails
for obj in gc.get_objects():
    print(obj)  # Works until encountering torch
                    # Though it works on some files
print(sum(map(sys.getsizeof, gc.get_objects())))  # Works
print(collections.Counter(map(type, gc.get_objects())))  # Works
```

## Possible understanding
I think there's a use of the `__file__` variable somewhere and according to [this](https://stackoverflow.com/a/41546830) answer of SO, if the application is frozen it just fails using the variable.

Hope you can help

Edit : added more working examples
Edit 2 : I conducted some experiments, and it seems it's only due to the printing part. I navigated in the files but don't understand where to look when I encounter torch._C

**Comment by ailzhang** [comment]
This can be reproed with python3.6 on linux. It works fine on python2.7

**Comment by suo** [comment]
I believe this is happening because of how we do dynamic attribute loading for custom operators. @zdevito, I remember you had an idea for easy fix but I forgot what it was

**Comment by zdevito** [comment]
Oh, we probably have torch.ops inherit from Module (the python class), but it isn't really a module so it doesn't have __file__ set. Asking for it then goes through our op lookup path. Solution is probably to simply set `__file__` on torch.jit.ops to _something_.
