### ISSUE TITLE
Provide a context manager to silence PyTorch exporter warning

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#19364]
## 🚀 Feature
Originally reported [here](https://github.com/Microsoft/onnxruntime/issues/822) but this seems like a better repo.
Please provide a way to silence tracing warnings on as-needed basis (for some statements).

## Motivation

The exporter reports a very useful warning, like [this issue](https://github.com/Microsoft/onnxruntime/issues/679). Some times we know that the semantics are correct (for example a constant is a constant always) in which case would be nice to ignore the warning only for that statement. Another example is `assert` statements.
It is better to silence the warning selectively for statements, rather than wholesale, or learn to ignore them!

## Pitch

As a suggestion, something like this would be nice

```python
with tracer.ignore_warnings():
    assert x.shape[0] > 2, "checking"
```

## Alternatives

Use annotations and helper scripts (with those annotations) for assert

## Additional context

I was trying to come up with a `CenterCrop` module [here](https://github.com/Microsoft/onnxruntime/issues/679).

This is the final working  solution that exports well, I have one class that can be used only for fixed input size but another than accepts dynamic shape input correctly too.

```python
@torch.jit.script
def center_slice_helper(x, h_offset, w_offset, h_end, w_end):
    return x[:, :, h_offset:h_end, w_offset:w_end]


class CenterCrop(nn.Module):
    def __init__(self, crop_size):
        """Crop from the center of a 4d tensor
        Input shape can be dynamic
        :param crop_size: the center crop size
        """
        super(CenterCrop, self).__init__()
        self.crop_size = crop_size

    def extra_repr(self):
        """Extra information
        """
        return 'crop_size={}'.format(
            self.crop_size
        )

    def forward(self, x):
        h_offset = (x.shape[2] - self.crop_size) / 2
        w_offset = (x.shape[3] - self.crop_size) / 2
        h_end = h_offset + self.crop_size
        w_end = w_offset + self.crop_size
        return center_slice_helper(x, h_offset, w_offset, h_end, w_end)


class CenterCropFixed(nn.Module):
    def __init__(self, crop_size):
        """Crop from the center of a 4d tensor
        Use this only if the input image size is always fixed
        :param crop_size: the center crop size
        """
        super(CenterCropFixed, self).__init__()
        self.crop_size = crop_size

    def extra_repr(self):
        """Extra information
        """
        return 'crop_size={}'.format(
            self.crop_size
        )

    def forward(self, x):
        h_offset = (x.shape[2] - self.crop_size) / 2
        w_offset = (x.shape[3] - self.crop_size) / 2
        return x[:, :, h_offset:h_offset + self.crop_size, w_offset:w_offset + self.crop_size]
```

I still do not know how best to put this assert statement:

```python
assert x.shape[3] > self.crop_size + 2 and x.shape[2] > self.crop_size + 2, \
            "height: {} or width: {} is less than crop_size: {}".format(x.shape[2], x.shape[3], self.crop_size)
```

without getting a tracer warning like

> TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not g eneralize to other inputs!
> return x[:, :, h_offset:h_offset + self.crop_size, w_offset:w_offset + self.crop_size]

And I do not want to ignore the warning, I just know that it is just an assert statement that will not change anything. Same can be said about the second class, I would like to export it with no warning because for this class I know will be used along with constant-sized inputs.

**Comment by driazati** [comment]
As stated in the onnxruntime issue you might trip the assert when different input shapes are used, so be careful. Closing since ignoring warnings with just the `warning` module is pretty straightforward, you can do something like this to get rid of the `TracerWarning`s:

```python
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings(
        action='ignore',
        category=torch.jit.TracerWarning,
        module=r'.*'
    )
    torch.jit.trace(CenterCrop(3), (torch.ones(6, 6, 6, 6, dtype=torch.long),))
```
