### ISSUE TITLE
[ONNX] RNN activation function exported to ONNX with wrong string case

### ISSUE THREAD

**Issue by spandantiwari** [pytorch/pytorch#19366]
## 🐛 Bug

If we export `nn.RNN` module to ONNX, the `activations` attribute is written is all lower case. Several backends assume these strings to be case-sensitive, where this can be a blocking issue during runtime. There is an open issue (https://github.com/onnx/onnx/issues/1934) in the ONNX repo to make this this explicit in the spec. PyTorch's ONNX exporter should also consider writing strings with correct case in `activations` attribute. 

## To Reproduce

1. Create a simple model with `nn.RNN` module.
1. Export this model to ONNX using `torch.onnx.export`
1. Check the `activations` attribute for the case of the string. As an example, the string will be 'tanh', where ideally it should be 'Tanh'.

## Expected behavior

The `activations` attribute value should match the case specified in ONNX spec. 

## Environment
This can be seen in all environments.

**Comment by spandantiwari** [comment]
cc: @houseroad This is a minor issue, but one that's blocking some models from running in backends such as Onnxruntime. 

Will submit a PR soon.

**Comment by spandantiwari** [comment]
https://github.com/pytorch/pytorch/pull/19368 is in to fix this.

**Comment by houseroad** [comment]
Close it, since the fix is merged.
