### ISSUE TITLE
nn.Linear module weight initialization does not match the documentation

### ISSUE THREAD

**Issue by interesaaat** [pytorch/pytorch#19376]
## 🐛 Bug

The documentation of the [linear module in python](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/linear.py) states that: 
```latex
weight: the learnable weights of the module of shape
            :math:`(\text{out\_features}, \text{in\_features})`. The values are
            initialized from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})`, where
            :math:`k = \frac{1}{\text{in\_features}}`
```
but the code instead does
```python
init.kaiming_uniform_(self.weight, a=math.sqrt(5))
```
The [C++ implementation](https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/src/nn/modules/linear.cpp) instead looks ok:
```c
const auto stdv = 1.0 / std::sqrt(weight.size(1));
  NoGradGuard no_grad;
  for (auto& p : this->parameters()) {
    p.uniform_(-stdv, stdv);
  }
```

**Comment by interesaaat** [comment]
@nairbv if you want you can assign the issue to me and I can submit a PR.

**Comment by soumith** [comment]
@interesaaat go for it. We cant assign it to you in the UI (github doesnt' allow), but just assume you've been assigned.

**Comment by soumith** [comment]
please see the comment on the PR. I apologize for not taking a closer look at the math, until you sent the PR.
