### ISSUE TITLE
[jit] Implement `sorted` for lists

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#19372]
Broken out from #18627 to track separately. This has several parts, in increasing order of complexity:
- [x] Sorting for specialized lists (int/float/Tensor). This should be a simple call to `std::sort`, since the appropriate comparison ops are already defined.
- [ ] Sorting for generic lists. This will require implementing comparison for generic IValues.
- [x] Sorting for ScriptClasses. This is different from generic lists because the operator will need to call the appropriate comparison method (`__gt__` or whatever) on the script class.

**Comment by lamhoangtung** [comment]
Does sort with `key=...` supported yet ?

I have tried `lambda` and function and it still doesn't work ...
