### ISSUE TITLE
numerical stability of CPU implementation of LRN

### ISSUE THREAD

**Issue by zym1010** [pytorch/pytorch#1938]
using a LRN module from <https://github.com/pytorch/pytorch/issues/653#issuecomment-304361386>, which is just wrapper of legacy LRN, I found that, the CPU and GPU results of this module, given same input, are hugely different.

Check <https://github.com/leelabcnbc/pytorch-caffe-models/blob/master/test_LRN.py>, `abs(result_cpu, result_gpu).max()` can be as large as 73, where given exactly the same input in Caffe, `abs(result_cpu, result_gpu).max()` is only as large as 0.0004.

**Comment by pbanavara** [comment]
I can take a look at this. Since the legacy code is no longer available in 1.0 where can I find the SpatialCrossMapLRN implementation ? If I look at the issue #653 the legacy implementation of SpatialCrossMapLRN is also suggested as a workaround. I am currently referencing the code at 

https://github.com/leelabcnbc/pytorch-caffe-models/blob/master/torch_caffe_models/models/layers.py

Is this the correct repo ? Some background information will be helpful. Thank you.

**Comment by zym1010** [comment]
thanks. the implementation for SpatialCrossMapLRN is available in 0.4.1 codebase. <https://github.com/pytorch/pytorch/blob/v0.4.1/torch/legacy/nn/SpatialCrossMapLRN.py>.

**Comment by soumith** [comment]
@pbanavara you can find the code here: https://github.com/pytorch/pytorch/blob/a66669a110a6eeeef8e08293174138ca87dc1a66/torch/nn/functional.py#L1666-L1689

**Comment by pbanavara** [comment]
@soumith @zym1010 Thank you. I just got started and have a quick question for @zym1010. In your test code `https://github.com/leelabcnbc/pytorch-caffe-models/blob/master/test_LRN.py` did you use the Alexnet model for any specific reason ? Is it ok to just use a random tensor to test the norm ?

**Comment by zym1010** [comment]
@pbanavara Yeah you can use random tensor, though I'm not sure if the differences are that big if random weights are used. I used Alexnet that time just for my own use cases, not for testing LRN layer.

Thanks!

**Comment by pbanavara** [comment]
Ok cool. I will use either Tensors with significantly large weights.

**Comment by cpuhrsch** [comment]
@zym1010 - given recent releases, is this issue still current?

**Comment by gchanan** [comment]
not enough here to be "high priority"

**Comment by pbanavara** [comment]
Hey sorry I haven't had anytime to delve deeper into this. If this issue no
longer relevant, please delete the same. I haven't done any work on this.

**Comment by mruberry** [comment]
This issue appears to refer to deprecated functionality. Please reopen if it's still a non-deprecated problem.
