### ISSUE TITLE
Sending small model to GPU leads to 2GB increase in RAM

### ISSUE THREAD

**Issue by Ricocotam** [pytorch/pytorch#19397]
## 🐛 Bug

When using `model.to(device)` I see a + 2 GB in my RAM usage (but only about 100MB on GPU). My model have few parameters (may be 1 000) and weights about 5MB. I can see why there would be an increase in the RAM usage but 2GB is huge.

I don't know if it's a bug or not but it's really strange

**Comment by xsacha** [comment]
Loading CUDNN for the first time will likely load a lot of stuff in to RAM. This should be a once off occurance.

If you then load another model after this, how much does your RAM increase?

**Comment by Ricocotam** [comment]
It doesn't take more, thanks for the answer
