### ISSUE TITLE
[jit] xavier_normal_ and friends not scripted

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#19395]
torch.nn.init.xavier_normal_ and other functions in [nn.init](https://github.com/pytorch/pytorch/blob/master/torch/nn/init.py) are not weak-scripted. Seems like an oversight, since they don't seem that complicated.

**Comment by suo** [comment]
@driazati can you take a look? `xavier_normal_` is blocking for RNNG.

**Comment by driazati** [comment]
Fixed in #19678
