### ISSUE TITLE
i want to parsing waveglow model to onnx but i have a error ㅜㅜ

### ISSUE THREAD

**Issue by wojung** [pytorch/pytorch#19399]
## To Reproduce

I brought in a trained waveglow model in nvidia github
1. import model
2. set input
3. export to onnx

##source
    waveglow = torch.load(waveglow_path)['model']
    waveglow = waveglow.remove_weightnorm(waveglow)
    waveglow.cuda().eval()
    
    dummy_input1 = torch.randn(1, 80, 100, device='cuda' )
    dummy_input2 = torch.randn(1, 80, device='cuda')
    dummy_inputs = [dummy_input1, dummy_input2]

    torch.onnx.export(waveglow, dummy_inputs, "/home/msl/isaac/waveglow/waveglow.onnx")

## Error Message
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'glow.Invertible1x1Conv' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/msl/isaac/waveglow/glow.py:216: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert(spect.size(2) >= audio.size(1))
/home/msl/isaac/waveglow/glow.py:217: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if spect.size(2) > audio.size(1):
/home/msl/isaac/waveglow/glow.py:218: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  spect = spect[:, :, :audio.size(1)]
/home/msl/isaac/waveglow/glow.py:236: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  n_half = int(audio.size(1)/2)
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py:501: UserWarning: ONNX export failed on ATen operator logdet because torch.onnx.symbolic.logdet does not exist
  .format(op_name, op_name))
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.profile = True
Traceback (most recent call last):
  File "inference.py", line 111, in <module>
    args.sampling_rate, args.is_fp16, args.denoiser_strength)
  File "inference.py", line 60, in main
    torch.onnx.export(waveglow, dummy_inputs, "/home/msl/isaac/waveglow/waveglow.onnx")
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py", line 287, in _export
    proto, export_map = graph._export_onnx(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::logdet

Defined at:
/home/msl/isaac/waveglow/glow.py(100): forward
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/nn/modules/module.py(477): _slow_forward
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/nn/modules/module.py(487): __call__
/home/msl/isaac/waveglow/glow.py(233): forward
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/nn/modules/module.py(477): _slow_forward
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/nn/modules/module.py(487): __call__
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/jit/__init__.py(252): forward
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/nn/modules/module.py(489): __call__
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/jit/__init__.py(197): get_trace_graph
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py(192): _trace_and_get_graph_from_model
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py(224): _model_to_graph
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py(281): _export
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py(104): export
/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/__init__.py(27): export
inference.py(60): main
inference.py(111): <module>

Graph we tried to export:
graph(%0 : Float(1, 80, 100)
      %1 : Float(1, 80)
      %2 : Float(80, 80, 1024)
      %3 : Float(80)
      %4 : Float(512)
      %5 : Float(512, 256, 3)
      %6 : Float(512)
      %7 : Float(512, 256, 3)
      %8 : Float(512)
      %9 : Float(512, 256, 3)
      %10 : Float(512)
      %11 : Float(512, 256, 3)
      %12 : Float(512)
      %13 : Float(512, 256, 3)
      %14 : Float(512)
      %15 : Float(512, 256, 3)
      %16 : Float(512)
      %17 : Float(512, 256, 3)
      %18 : Float(512)
      %19 : Float(512, 256, 3)
      %20 : Float(512)
      %21 : Float(512, 256, 1)
      %22 : Float(512)
      %23 : Float(512, 256, 1)
      %24 : Float(512)
      %25 : Float(512, 256, 1)
      %26 : Float(512)
      %27 : Float(512, 256, 1)
      %28 : Float(512)
      %29 : Float(512, 256, 1)
      %30 : Float(512)
      %31 : Float(512, 256, 1)
      %32 : Float(512)
      %33 : Float(512, 256, 1)
      %34 : Float(256)
      %35 : Float(256, 256, 1)
      %36 : Float(512)
      %37 : Float(512, 640, 1)
      %38 : Float(512)
      %39 : Float(512, 640, 1)
      %40 : Float(512)
      %41 : Float(512, 640, 1)
      %42 : Float(512)
      %43 : Float(512, 640, 1)
      %44 : Float(512)
      %45 : Float(512, 640, 1)
      %46 : Float(512)
      %47 : Float(512, 640, 1)
      %48 : Float(512)
      %49 : Float(512, 640, 1)
      %50 : Float(512)
      %51 : Float(512, 640, 1)
      %52 : Float(256)
      %53 : Float(256, 4, 1)
      %54 : Float(8, 256, 1)
      %55 : Float(8)
      %56 : Float(512)
      %57 : Float(512, 256, 3)
      %58 : Float(512)
      %59 : Float(512, 256, 3)
      %60 : Float(512)
      %61 : Float(512, 256, 3)
      %62 : Float(512)
      %63 : Float(512, 256, 3)
      %64 : Float(512)
      %65 : Float(512, 256, 3)
      %66 : Float(512)
      %67 : Float(512, 256, 3)
      %68 : Float(512)
      %69 : Float(512, 256, 3)
      %70 : Float(512)
      %71 : Float(512, 256, 3)
      %72 : Float(512)
      %73 : Float(512, 256, 1)
      %74 : Float(512)
      %75 : Float(512, 256, 1)
      %76 : Float(512)
      %77 : Float(512, 256, 1)
      %78 : Float(512)
      %79 : Float(512, 256, 1)
      %80 : Float(512)
      %81 : Float(512, 256, 1)
      %82 : Float(512)
      %83 : Float(512, 256, 1)
      %84 : Float(512)
      %85 : Float(512, 256, 1)
      %86 : Float(256)
      %87 : Float(256, 256, 1)
      %88 : Float(512)
      %89 : Float(512, 640, 1)
      %90 : Float(512)
      %91 : Float(512, 640, 1)
      %92 : Float(512)
      %93 : Float(512, 640, 1)
      %94 : Float(512)
      %95 : Float(512, 640, 1)
      %96 : Float(512)
      %97 : Float(512, 640, 1)
      %98 : Float(512)
      %99 : Float(512, 640, 1)
      %100 : Float(512)
      %101 : Float(512, 640, 1)
      %102 : Float(512)
      %103 : Float(512, 640, 1)
      %104 : Float(256)
      %105 : Float(256, 4, 1)
      %106 : Float(8, 256, 1)
      %107 : Float(8)
      %108 : Float(512)
      %109 : Float(512, 256, 3)
      %110 : Float(512)
      %111 : Float(512, 256, 3)
      %112 : Float(512)
      %113 : Float(512, 256, 3)
      %114 : Float(512)
      %115 : Float(512, 256, 3)
      %116 : Float(512)
      %117 : Float(512, 256, 3)
      %118 : Float(512)
      %119 : Float(512, 256, 3)
      %120 : Float(512)
      %121 : Float(512, 256, 3)
      %122 : Float(512)
      %123 : Float(512, 256, 3)
      %124 : Float(512)
      %125 : Float(512, 256, 1)
      %126 : Float(512)
      %127 : Float(512, 256, 1)
      %128 : Float(512)
      %129 : Float(512, 256, 1)
      %130 : Float(512)
      %131 : Float(512, 256, 1)
      %132 : Float(512)
      %133 : Float(512, 256, 1)
      %134 : Float(512)
      %135 : Float(512, 256, 1)
      %136 : Float(512)
      %137 : Float(512, 256, 1)
      %138 : Float(256)
      %139 : Float(256, 256, 1)
      %140 : Float(512)
      %141 : Float(512, 640, 1)
      %142 : Float(512)
      %143 : Float(512, 640, 1)
      %144 : Float(512)
      %145 : Float(512, 640, 1)
      %146 : Float(512)
      %147 : Float(512, 640, 1)
      %148 : Float(512)
      %149 : Float(512, 640, 1)
      %150 : Float(512)
      %151 : Float(512, 640, 1)
      %152 : Float(512)
      %153 : Float(512, 640, 1)
      %154 : Float(512)
      %155 : Float(512, 640, 1)
      %156 : Float(256)
      %157 : Float(256, 4, 1)
      %158 : Float(8, 256, 1)
      %159 : Float(8)
      %160 : Float(512)
      %161 : Float(512, 256, 3)
      %162 : Float(512)
      %163 : Float(512, 256, 3)
      %164 : Float(512)
      %165 : Float(512, 256, 3)
      %166 : Float(512)
      %167 : Float(512, 256, 3)
      %168 : Float(512)
      %169 : Float(512, 256, 3)
      %170 : Float(512)
      %171 : Float(512, 256, 3)
      %172 : Float(512)
      %173 : Float(512, 256, 3)
      %174 : Float(512)
      %175 : Float(512, 256, 3)
      %176 : Float(512)
      %177 : Float(512, 256, 1)
      %178 : Float(512)
      %179 : Float(512, 256, 1)
      %180 : Float(512)
      %181 : Float(512, 256, 1)
      %182 : Float(512)
      %183 : Float(512, 256, 1)
      %184 : Float(512)
      %185 : Float(512, 256, 1)
      %186 : Float(512)
      %187 : Float(512, 256, 1)
      %188 : Float(512)
      %189 : Float(512, 256, 1)
      %190 : Float(256)
      %191 : Float(256, 256, 1)
      %192 : Float(512)
      %193 : Float(512, 640, 1)
      %194 : Float(512)
      %195 : Float(512, 640, 1)
      %196 : Float(512)
      %197 : Float(512, 640, 1)
      %198 : Float(512)
      %199 : Float(512, 640, 1)
      %200 : Float(512)
      %201 : Float(512, 640, 1)
      %202 : Float(512)
      %203 : Float(512, 640, 1)
      %204 : Float(512)
      %205 : Float(512, 640, 1)
      %206 : Float(512)
      %207 : Float(512, 640, 1)
      %208 : Float(256)
      %209 : Float(256, 4, 1)
      %210 : Float(8, 256, 1)
      %211 : Float(8)
      %212 : Float(512)
      %213 : Float(512, 256, 3)
      %214 : Float(512)
      %215 : Float(512, 256, 3)
      %216 : Float(512)
      %217 : Float(512, 256, 3)
      %218 : Float(512)
      %219 : Float(512, 256, 3)
      %220 : Float(512)
      %221 : Float(512, 256, 3)
      %222 : Float(512)
      %223 : Float(512, 256, 3)
      %224 : Float(512)
      %225 : Float(512, 256, 3)
      %226 : Float(512)
      %227 : Float(512, 256, 3)
      %228 : Float(512)
      %229 : Float(512, 256, 1)
      %230 : Float(512)
      %231 : Float(512, 256, 1)
      %232 : Float(512)
      %233 : Float(512, 256, 1)
      %234 : Float(512)
      %235 : Float(512, 256, 1)
      %236 : Float(512)
      %237 : Float(512, 256, 1)
      %238 : Float(512)
      %239 : Float(512, 256, 1)
      %240 : Float(512)
      %241 : Float(512, 256, 1)
      %242 : Float(256)
      %243 : Float(256, 256, 1)
      %244 : Float(512)
      %245 : Float(512, 640, 1)
      %246 : Float(512)
      %247 : Float(512, 640, 1)
      %248 : Float(512)
      %249 : Float(512, 640, 1)
      %250 : Float(512)
      %251 : Float(512, 640, 1)
      %252 : Float(512)
      %253 : Float(512, 640, 1)
      %254 : Float(512)
      %255 : Float(512, 640, 1)
      %256 : Float(512)
      %257 : Float(512, 640, 1)
      %258 : Float(512)
      %259 : Float(512, 640, 1)
      %260 : Float(256)
      %261 : Float(256, 3, 1)
      %262 : Float(6, 256, 1)
      %263 : Float(6)
      %264 : Float(512)
      %265 : Float(512, 256, 3)
      %266 : Float(512)
      %267 : Float(512, 256, 3)
      %268 : Float(512)
      %269 : Float(512, 256, 3)
      %270 : Float(512)
      %271 : Float(512, 256, 3)
      %272 : Float(512)
      %273 : Float(512, 256, 3)
      %274 : Float(512)
      %275 : Float(512, 256, 3)
      %276 : Float(512)
      %277 : Float(512, 256, 3)
      %278 : Float(512)
      %279 : Float(512, 256, 3)
      %280 : Float(512)
      %281 : Float(512, 256, 1)
      %282 : Float(512)
      %283 : Float(512, 256, 1)
      %284 : Float(512)
      %285 : Float(512, 256, 1)
      %286 : Float(512)
      %287 : Float(512, 256, 1)
      %288 : Float(512)
      %289 : Float(512, 256, 1)
      %290 : Float(512)
      %291 : Float(512, 256, 1)
      %292 : Float(512)
      %293 : Float(512, 256, 1)
      %294 : Float(256)
      %295 : Float(256, 256, 1)
      %296 : Float(512)
      %297 : Float(512, 640, 1)
      %298 : Float(512)
      %299 : Float(512, 640, 1)
      %300 : Float(512)
      %301 : Float(512, 640, 1)
      %302 : Float(512)
      %303 : Float(512, 640, 1)
      %304 : Float(512)
      %305 : Float(512, 640, 1)
      %306 : Float(512)
      %307 : Float(512, 640, 1)
      %308 : Float(512)
      %309 : Float(512, 640, 1)
      %310 : Float(512)
      %311 : Float(512, 640, 1)
      %312 : Float(256)
      %313 : Float(256, 3, 1)
      %314 : Float(6, 256, 1)
      %315 : Float(6)
      %316 : Float(512)
      %317 : Float(512, 256, 3)
      %318 : Float(512)
      %319 : Float(512, 256, 3)
      %320 : Float(512)
      %321 : Float(512, 256, 3)
      %322 : Float(512)
      %323 : Float(512, 256, 3)
      %324 : Float(512)
      %325 : Float(512, 256, 3)
      %326 : Float(512)
      %327 : Float(512, 256, 3)
      %328 : Float(512)
      %329 : Float(512, 256, 3)
      %330 : Float(512)
      %331 : Float(512, 256, 3)
      %332 : Float(512)
      %333 : Float(512, 256, 1)
      %334 : Float(512)
      %335 : Float(512, 256, 1)
      %336 : Float(512)
      %337 : Float(512, 256, 1)
      %338 : Float(512)
      %339 : Float(512, 256, 1)
      %340 : Float(512)
      %341 : Float(512, 256, 1)
      %342 : Float(512)
      %343 : Float(512, 256, 1)
      %344 : Float(512)
      %345 : Float(512, 256, 1)
      %346 : Float(256)
      %347 : Float(256, 256, 1)
      %348 : Float(512)
      %349 : Float(512, 640, 1)
      %350 : Float(512)
      %351 : Float(512, 640, 1)
      %352 : Float(512)
      %353 : Float(512, 640, 1)
      %354 : Float(512)
      %355 : Float(512, 640, 1)
      %356 : Float(512)
      %357 : Float(512, 640, 1)
      %358 : Float(512)
      %359 : Float(512, 640, 1)
      %360 : Float(512)
      %361 : Float(512, 640, 1)
      %362 : Float(512)
      %363 : Float(512, 640, 1)
      %364 : Float(256)
      %365 : Float(256, 3, 1)
      %366 : Float(6, 256, 1)
      %367 : Float(6)
      %368 : Float(512)
      %369 : Float(512, 256, 3)
      %370 : Float(512)
      %371 : Float(512, 256, 3)
      %372 : Float(512)
      %373 : Float(512, 256, 3)
      %374 : Float(512)
      %375 : Float(512, 256, 3)
      %376 : Float(512)
      %377 : Float(512, 256, 3)
      %378 : Float(512)
      %379 : Float(512, 256, 3)
      %380 : Float(512)
      %381 : Float(512, 256, 3)
      %382 : Float(512)
      %383 : Float(512, 256, 3)
      %384 : Float(512)
      %385 : Float(512, 256, 1)
      %386 : Float(512)
      %387 : Float(512, 256, 1)
      %388 : Float(512)
      %389 : Float(512, 256, 1)
      %390 : Float(512)
      %391 : Float(512, 256, 1)
      %392 : Float(512)
      %393 : Float(512, 256, 1)
      %394 : Float(512)
      %395 : Float(512, 256, 1)
      %396 : Float(512)
      %397 : Float(512, 256, 1)
      %398 : Float(256)
      %399 : Float(256, 256, 1)
      %400 : Float(512)
      %401 : Float(512, 640, 1)
      %402 : Float(512)
      %403 : Float(512, 640, 1)
      %404 : Float(512)
      %405 : Float(512, 640, 1)
      %406 : Float(512)
      %407 : Float(512, 640, 1)
      %408 : Float(512)
      %409 : Float(512, 640, 1)
      %410 : Float(512)
      %411 : Float(512, 640, 1)
      %412 : Float(512)
      %413 : Float(512, 640, 1)
      %414 : Float(512)
      %415 : Float(512, 640, 1)
      %416 : Float(256)
      %417 : Float(256, 3, 1)
      %418 : Float(6, 256, 1)
      %419 : Float(6)
      %420 : Float(512)
      %421 : Float(512, 256, 3)
      %422 : Float(512)
      %423 : Float(512, 256, 3)
      %424 : Float(512)
      %425 : Float(512, 256, 3)
      %426 : Float(512)
      %427 : Float(512, 256, 3)
      %428 : Float(512)
      %429 : Float(512, 256, 3)
      %430 : Float(512)
      %431 : Float(512, 256, 3)
      %432 : Float(512)
      %433 : Float(512, 256, 3)
      %434 : Float(512)
      %435 : Float(512, 256, 3)
      %436 : Float(512)
      %437 : Float(512, 256, 1)
      %438 : Float(512)
      %439 : Float(512, 256, 1)
      %440 : Float(512)
      %441 : Float(512, 256, 1)
      %442 : Float(512)
      %443 : Float(512, 256, 1)
      %444 : Float(512)
      %445 : Float(512, 256, 1)
      %446 : Float(512)
      %447 : Float(512, 256, 1)
      %448 : Float(512)
      %449 : Float(512, 256, 1)
      %450 : Float(256)
      %451 : Float(256, 256, 1)
      %452 : Float(512)
      %453 : Float(512, 640, 1)
      %454 : Float(512)
      %455 : Float(512, 640, 1)
      %456 : Float(512)
      %457 : Float(512, 640, 1)
      %458 : Float(512)
      %459 : Float(512, 640, 1)
      %460 : Float(512)
      %461 : Float(512, 640, 1)
      %462 : Float(512)
      %463 : Float(512, 640, 1)
      %464 : Float(512)
      %465 : Float(512, 640, 1)
      %466 : Float(512)
      %467 : Float(512, 640, 1)
      %468 : Float(256)
      %469 : Float(256, 2, 1)
      %470 : Float(4, 256, 1)
      %471 : Float(4)
      %472 : Float(512)
      %473 : Float(512, 256, 3)
      %474 : Float(512)
      %475 : Float(512, 256, 3)
      %476 : Float(512)
      %477 : Float(512, 256, 3)
      %478 : Float(512)
      %479 : Float(512, 256, 3)
      %480 : Float(512)
      %481 : Float(512, 256, 3)
      %482 : Float(512)
      %483 : Float(512, 256, 3)
      %484 : Float(512)
      %485 : Float(512, 256, 3)
      %486 : Float(512)
      %487 : Float(512, 256, 3)
      %488 : Float(512)
      %489 : Float(512, 256, 1)
      %490 : Float(512)
      %491 : Float(512, 256, 1)
      %492 : Float(512)
      %493 : Float(512, 256, 1)
      %494 : Float(512)
      %495 : Float(512, 256, 1)
      %496 : Float(512)
      %497 : Float(512, 256, 1)
      %498 : Float(512)
      %499 : Float(512, 256, 1)
      %500 : Float(512)
      %501 : Float(512, 256, 1)
      %502 : Float(256)
      %503 : Float(256, 256, 1)
      %504 : Float(512)
      %505 : Float(512, 640, 1)
      %506 : Float(512)
      %507 : Float(512, 640, 1)
      %508 : Float(512)
      %509 : Float(512, 640, 1)
      %510 : Float(512)
      %511 : Float(512, 640, 1)
      %512 : Float(512)
      %513 : Float(512, 640, 1)
      %514 : Float(512)
      %515 : Float(512, 640, 1)
      %516 : Float(512)
      %517 : Float(512, 640, 1)
      %518 : Float(512)
      %519 : Float(512, 640, 1)
      %520 : Float(256)
      %521 : Float(256, 2, 1)
      %522 : Float(4, 256, 1)
      %523 : Float(4)
      %524 : Float(512)
      %525 : Float(512, 256, 3)
      %526 : Float(512)
      %527 : Float(512, 256, 3)
      %528 : Float(512)
      %529 : Float(512, 256, 3)
      %530 : Float(512)
      %531 : Float(512, 256, 3)
      %532 : Float(512)
      %533 : Float(512, 256, 3)
      %534 : Float(512)
      %535 : Float(512, 256, 3)
      %536 : Float(512)
      %537 : Float(512, 256, 3)
      %538 : Float(512)
      %539 : Float(512, 256, 3)
      %540 : Float(512)
      %541 : Float(512, 256, 1)
      %542 : Float(512)
      %543 : Float(512, 256, 1)
      %544 : Float(512)
      %545 : Float(512, 256, 1)
      %546 : Float(512)
      %547 : Float(512, 256, 1)
      %548 : Float(512)
      %549 : Float(512, 256, 1)
      %550 : Float(512)
      %551 : Float(512, 256, 1)
      %552 : Float(512)
      %553 : Float(512, 256, 1)
      %554 : Float(256)
      %555 : Float(256, 256, 1)
      %556 : Float(512)
      %557 : Float(512, 640, 1)
      %558 : Float(512)
      %559 : Float(512, 640, 1)
      %560 : Float(512)
      %561 : Float(512, 640, 1)
      %562 : Float(512)
      %563 : Float(512, 640, 1)
      %564 : Float(512)
      %565 : Float(512, 640, 1)
      %566 : Float(512)
      %567 : Float(512, 640, 1)
      %568 : Float(512)
      %569 : Float(512, 640, 1)
      %570 : Float(512)
      %571 : Float(512, 640, 1)
      %572 : Float(256)
      %573 : Float(256, 2, 1)
      %574 : Float(4, 256, 1)
      %575 : Float(4)
      %576 : Float(512)
      %577 : Float(512, 256, 3)
      %578 : Float(512)
      %579 : Float(512, 256, 3)
      %580 : Float(512)
      %581 : Float(512, 256, 3)
      %582 : Float(512)
      %583 : Float(512, 256, 3)
      %584 : Float(512)
      %585 : Float(512, 256, 3)
      %586 : Float(512)
      %587 : Float(512, 256, 3)
      %588 : Float(512)
      %589 : Float(512, 256, 3)
      %590 : Float(512)
      %591 : Float(512, 256, 3)
      %592 : Float(512)
      %593 : Float(512, 256, 1)
      %594 : Float(512)
      %595 : Float(512, 256, 1)
      %596 : Float(512)
      %597 : Float(512, 256, 1)
      %598 : Float(512)
      %599 : Float(512, 256, 1)
      %600 : Float(512)
      %601 : Float(512, 256, 1)
      %602 : Float(512)
      %603 : Float(512, 256, 1)
      %604 : Float(512)
      %605 : Float(512, 256, 1)
      %606 : Float(256)
      %607 : Float(256, 256, 1)
      %608 : Float(512)
      %609 : Float(512, 640, 1)
      %610 : Float(512)
      %611 : Float(512, 640, 1)
      %612 : Float(512)
      %613 : Float(512, 640, 1)
      %614 : Float(512)
      %615 : Float(512, 640, 1)
      %616 : Float(512)
      %617 : Float(512, 640, 1)
      %618 : Float(512)
      %619 : Float(512, 640, 1)
      %620 : Float(512)
      %621 : Float(512, 640, 1)
      %622 : Float(512)
      %623 : Float(512, 640, 1)
      %624 : Float(256)
      %625 : Float(256, 2, 1)
      %626 : Float(4, 256, 1)
      %627 : Float(4)
      %628 : Float(8, 8, 1)
      %629 : Float(8, 8, 1)
      %630 : Float(8, 8, 1)
      %631 : Float(8, 8, 1)
      %632 : Float(6, 6, 1)
      %633 : Float(6, 6, 1)
      %634 : Float(6, 6, 1)
      %635 : Float(6, 6, 1)
      %636 : Float(4, 4, 1)
      %637 : Float(4, 4, 1)
      %638 : Float(4, 4, 1)
      %639 : Float(4, 4, 1)) {
  %640 : Float(1, 80, 26368) = onnx::ConvTranspose[dilations=[1], group=1, kernel_shape=[1024], pads=[0, 0], strides=[256]](%0, %2, %3), scope: WaveGlow/ConvTranspose1d[upsample]
  %641 : Float(1, 80, 26368) = onnx::Slice[axes=[0], ends=[9223372036854775807], starts=[0]](%640), scope: WaveGlow
  %642 : Float(1, 80, 26368) = onnx::Slice[axes=[1], ends=[9223372036854775807], starts=[0]](%641), scope: WaveGlow
  %643 : Float(1, 80!, 80) = onnx::Slice[axes=[2], ends=[80], starts=[0]](%642), scope: WaveGlow
  %644 : Float(1, 80!, 10, 8) = onnx::ATen[dimension=2, operator="unfold", size=8, step=8](%643), scope: WaveGlow
  %645 : Float(1, 10, 80, 8) = onnx::Transpose[perm=[0, 2, 1, 3]](%644), scope: WaveGlow
  %646 : Long() = onnx::Constant[value={0}](), scope: WaveGlow
  %647 : Tensor = onnx::Shape(%645), scope: WaveGlow
  %648 : Long() = onnx::Gather[axis=0](%647, %646), scope: WaveGlow
  %649 : Long() = onnx::Constant[value={1}](), scope: WaveGlow
  %650 : Tensor = onnx::Shape(%645), scope: WaveGlow
  %651 : Long() = onnx::Gather[axis=0](%650, %649), scope: WaveGlow
  %652 : Long() = onnx::Constant[value={-1}](), scope: WaveGlow
  %653 : Tensor = onnx::Unsqueeze[axes=[0]](%648)
  %654 : Tensor = onnx::Unsqueeze[axes=[0]](%651)
  %655 : Tensor = onnx::Unsqueeze[axes=[0]](%652)
  %656 : Tensor = onnx::Concat[axis=0](%653, %654, %655)
  %657 : Float(1, 10, 640) = onnx::Reshape(%645, %656), scope: WaveGlow
  %658 : Float(1!, 640!, 10!) = onnx::Transpose[perm=[0, 2, 1]](%657), scope: WaveGlow
  %659 : Float(1, 10, 8) = onnx::ATen[dimension=1, operator="unfold", size=8, step=8](%1), scope: WaveGlow
  %660 : Float(1!, 8!, 10!) = onnx::Transpose[perm=[0, 2, 1]](%659), scope: WaveGlow
  %661 : Long() = onnx::Constant[value={0}](), scope: WaveGlow/Invertible1x1Conv
  %662 : Tensor = onnx::Shape(%660), scope: WaveGlow/Invertible1x1Conv
  %663 : Long() = onnx::Gather[axis=0](%662, %661), scope: WaveGlow/Invertible1x1Conv
  %664 : Long() = onnx::Constant[value={2}](), scope: WaveGlow/Invertible1x1Conv
  %665 : Tensor = onnx::Shape(%660), scope: WaveGlow/Invertible1x1Conv
  %666 : Long() = onnx::Gather[axis=0](%665, %664), scope: WaveGlow/Invertible1x1Conv
  %667 : Float(8, 8) = onnx::Squeeze[axes=[2]](%628), scope: WaveGlow/Invertible1x1Conv
  %668 : Long() = onnx::Mul(%663, %666), scope: WaveGlow/Invertible1x1Conv
  %669 : Float() = aten::logdet(%667), scope: WaveGlow/Invertible1x1Conv
  %670 : Float() = onnx::Mul(%668, %669), scope: WaveGlow/Invertible1x1Conv
  %671 : Float(1, 8, 10) = onnx::Conv[dilations=[1], group=1, kernel_shape=[1], pads=[0, 0], strides=[1]](%660, %628), scope: WaveGlow/Invertible1x1Conv/Conv1d[conv]
  %672 : Float(1, 8, 10) = onnx::Slice[axes=[0], ends=[9223372036854775807], starts=[0]](%671), scope: WaveGlow
  %673 : Float(1!, 4, 10) = onnx::Slice[axes=[1], ends=[4], starts=[0]](%672), scope: WaveGlow
  %674 : Float(1!, 4, 10) = onnx::Slice[axes=[2], ends=[9223372036854775807], starts=[0]](%673), scope: WaveGlow
  %675 : Float(1, 8, 10) = onnx::Slice[axes=[0], ends=[9223372036854775807], starts=[0]](%671), scope: WaveGlow
  %676 : Float(1!, 4, 10) = onnx::Slice[axes=[1], ends=[9223372036854775807], starts=[4]](%675), scope: WaveGlow
  %677 : Float(1!, 4, 10) = onnx::Slice[axes=[2], ends=[9223372036854775807], starts=[0]](%676), scope: WaveGlow
     
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (1.0.1):
 - OS (Linux):
 - How you installed PyTorch ( `pip`,):
 - Build command you used (if compiling from source):
 - Python version: 3.5
 - CUDA/cuDNN version: 10.0/7
 - GPU models and configuration: NVIDIA-SMI 410.79
 - Any other relevant information:

## Additional context

cc @BowenBao @neginraoof

**Comment by NoahDrisort** [comment]
Have you solve this? How you deal with this "torch.nn.Module.dump_patches = True", I have a same problem

**Comment by garymm** [comment]
@wojung 

Support for `logdet` was added in https://github.com/pytorch/pytorch/pull/29767 for opset >= 11.

I tried downloading the pretrained model from the link on https://github.com/NVIDIA/waveglow, but loading it into PyTorch failed. If you're still running into issues, please provide full repro instructions and the latest error message when trying with opset >= 11.

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
