### ISSUE TITLE
pip install does not work

### ISSUE THREAD

**Issue by lukad** [pytorch/pytorch#19406]
## 🐛 Bug

I'm trying to install pytorch according to `https://pytorch.org/#pip-install-pytorch` using python 3.7 and pip. When I run `pip3 install pytorch` it gives me an error telling me to install pytorch from http://pytorch.org.

## To Reproduce

1. `pip3 install pytorch`

Produces the following output

```
Collecting pytorch
  Using cached https://files.pythonhosted.org/packages/a9/41/4487bc23e3ac4d674943176f5aa309427b011e00607eb98899e9d951f67b/pytorch-0.1.2.tar.gz
Installing collected packages: pytorch
  Running setup.py install for pytorch ... error
    Complete output from command /Users/luka/.pyenv/versions/3.7.3/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/5n/07fchr7176j_lxd4w2kws4rh0000gp/T/pip-install-fnhpwo9f/pytorch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/5n/07fchr7176j_lxd4w2kws4rh0000gp/T/pip-record-ev0khx5p/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5n/07fchr7176j_lxd4w2kws4rh0000gp/T/pip-install-fnhpwo9f/pytorch/setup.py", line 13, in <module>
        raise Exception(message)
    Exception: You should install pytorch from http://pytorch.org

    ----------------------------------------
Command "/Users/luka/.pyenv/versions/3.7.3/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/5n/07fchr7176j_lxd4w2kws4rh0000gp/T/pip-install-fnhpwo9f/pytorch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/5n/07fchr7176j_lxd4w2kws4rh0000gp/T/pip-record-ev0khx5p/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/5n/07fchr7176j_lxd4w2kws4rh0000gp/T/pip-install-fnhpwo9f/pytorch/
```

and opens https://pytorch.org/#pip-install-pytorch in the browser.

## Expected behavior

Pytorch should install like it says on the website.

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Mac OSX 10.14.3
GCC version: Could not collect
CMake version: version 3.13.2

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.2
[conda] Could not collect

**Comment by soumith** [comment]
`pip3 install torch`, as we mention on our website

**Comment by lukad** [comment]
Ah crap, I missed that. That's a big gotcha. Thanks for the quick reply.

**Comment by visserssam** [comment]
Hey I'm trying this as well and i get the same error if I use pytorch or torch. with pip or pip3

**Comment by oguzaranay** [comment]
I have got the same problem, and solved it by installing from their website pytorch.org.
```
$ pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp36-cp36m-win_amd64.whl
$ pip3 install torchvision
```

**Comment by coffeeshop13** [comment]
> I have got the same problem, and solved it by installing from their website pytorch.org.
> 
> ```
> $ pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp36-cp36m-win_amd64.whl
> $ pip3 install torchvision
> ```

Thanks a lot!

**Comment by CT83** [comment]
This worked for me on WIndows 10 64 bit with Python 3.7

`pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl`

**Comment by JTHEN-DEV** [comment]
pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl
returns:
ERROR: torch-1.0.1-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

**Comment by snijesh** [comment]
> pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl
> returns:
> ERROR: torch-1.0.1-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
browse official website of pytorch... enter your configuration there.
In windows OS with cpu, Python 3.7 :
`pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by NguyenTheBinh1205** [comment]
pip install numpy
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html

**Comment by SophieCXT** [comment]
> pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl
> returns:
> ERROR: torch-1.0.1-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

You can use this:
**pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html**
It worked on my environment.

**Comment by Snopix** [comment]
what is the command for cuda 10.2 in pip

**Comment by ashreid23** [comment]
`PS C:\> nvcc --version                                                                                                  nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_May__6_19:10:02_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.0, V11.0.167
Build cuda_11.0_bu.relgpu_drvr445TC445_37.28358933_0
PS C:\> pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html             Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.5.1 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.5.1
PS C:\>                                                                                                                                                                                                                                                            `
i get errors trying all the above answers,   the code i just post is using the example from pytorch.org

**Comment by satyam78622** [comment]
> pip install numpy
> pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html

it worked for me

**Comment by gailweiss** [comment]
I'm also getting the same problem, trying to install pytorch in python3.9 with macOS Catalina if that's relevant.

What's the 'current' download link for a stable version? I 

(Error prints are:

`Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-wheel-g_u1i7cz
       cwd: /private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py", line 225, in <module>
      setup(name="torch", version="0.1.2.post2",
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp39-cp39-macosx_10_15_x86_64.whl size=44623 sha256=27a191c5d9df245e8d5ca7764ad4e2ba8fd1e7acfa26bb8501c6b96f1c27e6d6
  Stored in directory: /Users/Gail/Library/Caches/pip/wheels/69/60/81/5cd74b8ee068fbe9e04ca0d53148f28f5c6e2c5b177d5dd622
Successfully built pyyaml
Failed to build torch
Installing collected packages: pyyaml, torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-record-qwqhjxg9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/torch
         cwd: /private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py", line 99, in run
        self.run_command('build_deps')
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-install-5_srv_0q/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tb/p0rc6qfs4tl3q88qqn0d1dth0000gn/T/pip-record-qwqhjxg9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/torch Check the logs for full command output.
`

**Comment by Chaz6** [comment]
I have the same problem with `pip3 install torch` with python 3.9 on Linux.

**Comment by Chaz6** [comment]
Looks like this is referenced in #47116.

**Comment by Swedeldsouza** [comment]
just go to pytorch site and select (block)  info  about your system, you will get the link to install pytorch

https://pytorch.org/get-started/locally/
