### ISSUE TITLE
Concerning backward's requirement for the network's output shape

### ISSUE THREAD

**Issue by AlexMetsai** [pytorch/pytorch#19401]
When calculating the gradient using the "backward" feature, if we don't specify the network's output shape, for example:

out = net(input)  # some network and some input
out.backward()

then it is the same thing like give a "torch.Tensor[1]" for input to "backward".
But, if the network has more output than one, we need to specify THAT particular shape. For example, if our network has 5 outputs, we would instead declare:

out.backward(torch.randn(1,5))

What I'm asking is that, could it be so that Torch detects automatically the network's output shape, therefore allowing to simply use "out.backward()" no matter what shape that output is? Is there another reason(that I'm missing) for this shape specification? Can this functionality be added?

**Comment by nairbv** [comment]
Best to check discussion forums for this kind of question:
https://discuss.pytorch.org/t/gradient-argument-in-out-backward-gradient/12742
