### ISSUE TITLE
[pylint] E1101:Module 'torch' has no 'squeeze' member

### ISSUE THREAD

**Issue by hamidfarhid** [pytorch/pytorch#1942]
Hi, 

I am using pytorch version of V-net and I encountered this error:\
[pylint] E1101:Module 'torch' has no 'squeeze' member
It is not critical error and lets my program runs but it doesn't squeeze the output at the end. Any idea?
Thanks

**Comment by soumith** [comment]
is there a code reproduction I can get for this?

**Comment by Leon0824** [comment]
Pylint ignores third-party packages for security reason.
To add a package into the whitelist:
`> pylint --generate-rcfile > .pylintrc
Open .pylintrc, and add torch into the whitelist:
`extension-pkg-whitelist=torch`

Reference:
[Pylint Error Message: “E1101: Module 'lxml.etree' has no 'strip_tags' member'”](https://stackoverflow.com/questions/43280486/pylint-error-message-e1101-module-lxml-etree-has-no-strip-tags-member)

**Comment by siran** [comment]
```On Windows 7, a .pylintrc file in your home directory (typically C:\Users\myusername) will be automatically recognized.

Since creating a file beginning with a dot is not allowed from Windows file explorer, you can create a template using:

pylint --generate-rcfile > .pylintrc```

Similar to what @Leon0824 wrote and https://stackoverflow.com/a/15837092/220949

**Comment by miranthajayatilake** [comment]
On VS code:
Add `"python.linting.enabled": false`  to the settings file. Worked for me.

**Comment by lijunzh** [comment]
I used the following workaround in `.pylintrc`:

```
[OPTIONS]
generated-members=torch.*
```

This simply tells `pylint` not to verify any member function in `torch` which is not a legit solution but is the best I can find so far.
