### ISSUE TITLE
Document that autograd::Profiler::RecordFunction is available in Python

### ISSUE THREAD

**Issue by heiner** [pytorch/pytorch#19422]
## 🚀 Feature

`torch.autograd.profiler.profile().export_chrome_trace` is great. Adding information to it from Python would make it even better.

## Motivation

In multi-threaded PyTorch code, it can be useful to further annotate the tracing output by adding additional information to it.

## Pitch

One easy / cheap way of doing this:

```cc
PYBIND11_MODULE(torch, m) {
  py::class_<torch::autograd::profiler::RecordFunction>(m, "Record")
      .def(py::init<std::string>(), py::arg("name"));
}
```

And then in Python

```python
record = torch.Record("model")
outputs = model(frame)
del record  # Alternatively, turn it into a context manager.
```

**Comment by ezyang** [comment]
We'll accept a PR that does this. A context manager would be better than a faux-RAII object, as you can't easily control scope of objects in Python. How about calling it `torch.autograd.profiler.record_function(label)` for consistency with the C++ name?

**Comment by heiner** [comment]
It seems https://github.com/pytorch/pytorch/commit/f1c8e01524067f6eb0976ade32139e591b907f24 has changed the RecordFunction object in a way that's not immediatly discernible to me. (Thereby also breaking my C++ extension, but I guess there's just  no expectation of API stability for those parts.)

I'm still happy to supply this PR once I've understood what the second argument to the new RECORD_FUNCTION macro is about.

**Comment by ezyang** [comment]
cc @ilia-cher, could you answer the question above?

**Comment by ilia-cher** [comment]
I would definitely prefer a context manager instead of manual 'del' which is easy to forget to call.
Regarding https://github.com/pytorch/pytorch/pull/18717 - motivation for updates to RecordFunction code can be found in https://github.com/pytorch/pytorch/issues/18966. Specifically, https://github.com/pytorch/pytorch/pull/18717 allows us to pass inputs of the profiled function into the callbacks registered in RecordFunction.
Since you just want to pass scope name, you can use the code similar to:

```
torch::autograd::profiler::RecordFunction guard;
guard.before(scope_name);
```
when entering the context manager, and destroy guard when exiting.

**Comment by apaszke** [comment]
We already have `torch.autograd.profiler.range`. It's just not very well documented.
```
with torch.autograd.profiler.range('name'):
  ...
```

**Comment by zhangguanheng66** [comment]
Hey, I will give this a shot.

**Comment by ezyang** [comment]
Reclassifying this as a documentation issue.

**Comment by prasunanand** [comment]
@apaszke I am unable to find `torch.autograd.profiler.range` in the source. Has it been renamed ?

**Comment by rgommers** [comment]
the `range` context manager was added in commit 22f596572, and removed in gh-19378. @apaszke's comment on that PR was:

_This was a user-facing object, and shouldn't have been deleted. It's the only way to actually insert ranges from Python, which is useful._

It was never added back though. So this is not a doc issue anymore. @apaszke @ezyang should it be added back? Looks to me like that would be a good thing to do, although we may want to choose a name that's more descriptive and doesn't shadow a builtin. @ezyang proposed `record_function` above, go with that?

**Comment by rgommers** [comment]
@prasunanand found this by searching for commits with `class range` in their diff in that one file: 
```
git log -S "class range" -- torch/autograd/profiler.py
```

**Comment by apaszke** [comment]
Yes, this definitely needs to be fixed! I think `range` was fine, because I doubt anyone imported it as an unqualified name, but `record` seems fine with me too 🤷‍♂

**Comment by rgommers** [comment]
> because I doubt anyone imported it as an unqualified name

true. but from experience, it's worth it now even just to avoid the drive by contributions from people who run style checkers and think it's really important to not shadow builtins. for numpy and scipy we have the same discussions about the same functions about once every 1-2 years ...
