### ISSUE TITLE
mean of a size-0 tensor

### ISSUE THREAD

**Issue by shuaitang** [pytorch/pytorch#19447]
## 🐛 Bug

if a tensor has a size 0, then the mean of it is 'NaN', which should be 0.

![image](https://user-images.githubusercontent.com/13791278/56399186-6f1a6180-6201-11e9-9277-1c034ba1b138.png)

## To Reproduce

1. import torch
1. a = torch.zeros(0)
1. a.mean()

## Expected behavior

tensor(nan)

**Comment by SsnL** [comment]
but why should it be 0, rather than 0/0=nan?

**Comment by shuaitang** [comment]
Someone else recommended a piece of reading here: [here](https://math.stackexchange.com/questions/909395/what-is-the-average-of-no-numbers). It seems to reasonable to have NaN for the mean of an empty list because there is no observation for the distribution.

**Comment by soumith** [comment]
nan makes sense, and @shuaitang thanks for the reference, it looks like it comes to the same conclusion, that it should be nan
