### ISSUE TITLE
torch.potri example doesn't work because cholesky defaults to lower triangle and potri defaults to upper

### ISSUE THREAD

**Issue by chausies** [pytorch/pytorch#19459]
In https://pytorch.org/docs/stable/torch.html#torch.potri, the provided example will not work, because [`torch.cholesky`](https://pytorch.org/docs/stable/torch.html#torch.cholesky) spits out the lower-triangular `l` by default, whereas `torch.potri` takes the upper-triangular `u` by default.

The example should be fixed to explicitly make the `upper` param the same in both the `torch.potri` and `torch.cholesky` calls.

As a further note, I believe that the default for `upper` should be the same between the two, in anycase. My recommendation is because `potri`, `potrs`, and all the other such functions default to `upper=True`, `cholesky` should bend the knee and also be `upper=True` by default to keep things standardized.

**Comment by vishwakftw** [comment]
Thank you for opening this issue. I will be sending in a PR soon that renames `potri` to `cholesky_inverse` where the `upper` argument will default to `False` to remain consistent with other `cholesky` functions (`cholesky` and `cholesky_solve`).

**Comment by ailzhang** [comment]
@vishwakftw  Thanks for taking care of it! I added it to 1.1 milestone to make sure we include this fix to the 1.1 release.

**Comment by vishwakftw** [comment]
Closed by https://github.com/pytorch/pytorch/commit/c30224ad21db93701da56bd91152dc0e40b28402.
