### ISSUE TITLE
How install old version pytorch 0.4.1 from source?

### ISSUE THREAD

**Issue by MSC19950601** [pytorch/pytorch#19457]
Dear Developers, I want to install pytorch 0.4.1 from source (unfortunately must have to do so). But I got some problems.
After git checkout v0.4.1, I use command "git submodule update --init", I got this.
**Cloning into '/home/kururu/pip-extension/pytorch/third_party/nervanagpu'...
Username for 'https://github.com':** 
And I found nervanagpu module was deleted.
Could you give me a proper solution?

**Comment by colesbury** [comment]
Sorry the 0.4.1 source build is broken. IIRC, the nervanagpu submodule is optional. Here are steps to build:

1. `git clone --branch v0.4.1 https://github.com/pytorch/pytorch.git pytorch-0.4.1`
2. `cd pytorch-0.4.1`
3. `git rm --cached third_party/nervanagpu`
4. Delete these lines:

https://github.com/pytorch/pytorch/blob/v0.4.1/.gitmodules#L19-L21

5. `git submodule update --init --recursive`
6. `python setup.py install`

Be aware that git submodules have some weird state, so if you run into trouble I would recommend deleting your checkout and starting again.

**Comment by colesbury** [comment]
PyTorch team action items:

1. Check out v0.4.1 branch
2. Delete `third_party/nervanagpu` and remove submodule
3. Make sure everything still builds
4. Update v0.4.1 tag

**Comment by colesbury** [comment]
cc @soumith: please comment if you don't think it's a good idea to update the v0.4.1 tag

**Comment by soumith** [comment]
I got yelled at from distro maintainers to not change tags (in a github issue a few months ago). So I am not inclined to changing it.

**Comment by MSC19950601** [comment]
@colesbury Thanks buddy! I'll try!

**Comment by MSC19950601** [comment]
@colesbury It works!  Thank you for help!

**Comment by chagri** [comment]
This dos not seem to be fully fixed yet. After following the above-mentioned steps, I get the following error:
```
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 nanopb libshm gloo THD c10d'
```

**Comment by chagri** [comment]
I was able to resolve it by fully uninstalling cuda and re-installing it (v9.2). And installing the following using conda: 
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing

**Comment by lapetite123** [comment]
@colesbury hello,I tried to install pytorch0.4.1 from source, I follow the above step but when I execute the last step, it appears some error like this:
+ make install -j48
make: *** No rule to make target 'install'.  Stop.
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 nanopb libshm gloo THD c10d'
env: 2080ti  cuda9.2.148  python3.6.4

**Comment by liuqinglong110** [comment]
> 
> 
> @soumith @colesbury
> This dos not seem to be fully fixed yet. After following the above-mentioned steps, I get the following error:
> 
> ```
> Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 nanopb libshm gloo THD c10d'
> ```
> 
> env: Ubuntu 16.04, Cuda 9.0, Python 3

Have you solved this problem yet?

**Comment by linlinlin1993** [comment]
@colesbury Hi, I am trying to install pytorch 0.4.1 with CUDA 10 from source, I follow the steps that you provided, but I met some error:


-- Autodetected CUDA architecture(s): 7.5 
-- Set NVCC_GENCODE for building NCCL: -gencode=arch=compute_75,code=sm_75
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yji/pytorch-0.4.1/third_party/build/nccl
+ make install -j12
[100%] Generating lib/libnccl.so
make[3]: warning: -jN forced in submake: disabling jobserver mode.
Compiling src/libwrap.cu                      > /home/yji/pytorch-0.4.1/third_party/build/nccl/obj/libwrap.o
nvcc fatal   : Unsupported gpu architecture 'compute_75'
Makefile:137: recipe for target '/home/yji/pytorch-0.4.1/third_party/build/nccl/obj/libwrap.o' failed
make[3]: *** [/home/yji/pytorch-0.4.1/third_party/build/nccl/obj/libwrap.o] Error 1
CMakeFiles/nccl.dir/build.make:60: recipe for target 'lib/libnccl.so' failed
make[2]: *** [lib/libnccl.so] Error 2
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/nccl.dir/all' failed
make[1]: *** [CMakeFiles/nccl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 nanopb libshm gloo THD c10d'

Do you have any idea about this error, I have tried long time to solve it ?
My envir: Ubuntu 18.04, Python 3.6, CUDA 10.0 (I know pytorch 0.4.1 only support CUDA<10.0, but I have to use both CUDA 10.0 and torch 0.4.1)
Thanks in advance.

**Comment by linlinlin1993** [comment]
@colesbury Hi, I am trying to install pytorch 0.4.1 with CUDA 10 from source, I follow the steps that you provided, but I met some error:

-- Autodetected CUDA architecture(s): 7.5
-- Set NVCC_GENCODE for building NCCL: -gencode=arch=compute_75,code=sm_75
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yji/pytorch-0.4.1/third_party/build/nccl

    make install -j12
    [100%] Generating lib/libnccl.so
    make[3]: warning: -jN forced in submake: disabling jobserver mode.
    Compiling src/libwrap.cu > /home/yji/pytorch-0.4.1/third_party/build/nccl/obj/libwrap.o
    nvcc fatal : Unsupported gpu architecture 'compute_75'
    Makefile:137: recipe for target '/home/yji/pytorch-0.4.1/third_party/build/nccl/obj/libwrap.o' failed
    make[3]: *** [/home/yji/pytorch-0.4.1/third_party/build/nccl/obj/libwrap.o] Error 1
    CMakeFiles/nccl.dir/build.make:60: recipe for target 'lib/libnccl.so' failed
    make[2]: *** [lib/libnccl.so] Error 2
    CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/nccl.dir/all' failed
    make[1]: *** [CMakeFiles/nccl.dir/all] Error 2
    Makefile:129: recipe for target 'all' failed
    make: *** [all] Error 2
    Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 nanopb libshm gloo THD c10d'

Do you have any idea about this error, I have tried long time to solve it ?
My envir: Ubuntu 18.04, Python 3.6, CUDA 10.0 (I know pytorch 0.4.1 only support CUDA<10.0, but I have to use both CUDA 10.0 and torch 0.4.1)
Thanks in advance.

**Comment by JuanaV** [comment]
Hi @linlinlin1993 , did you solve this?

**Comment by mmaaz60** [comment]
Does anyone was successful in building PyTorch0.4.1 with Cuda10.0? Thanks

**Comment by mrbulb** [comment]
> Does anyone was successful in building PyTorch0.4.1 with Cuda10.0? Thanks

@mmaaz60  it seems that pytorch 0.4.1 is not compatible with cuda 10
You can see https://github.com/pytorch/pytorch/issues/13661

**Comment by Minghao23** [comment]
I successfully compiled torch v0.4.1 NO_CUDA. It works but cannot utilize all cpu cores, the %cpu is between 100% - 150% while running. Normally it should be ~ 900%  in my 12 cores machine. Anyone has the same problem?

**Comment by qhaas** [comment]
> Does anyone was successful in building PyTorch0.4.1 with Cuda10.0? Thanks

No, tried last week since a user needs to run [hrnet](https://github.com/HRNet/HRNet-Semantic-Segmentation) and it requires 0.4.1.  Pytorch 0.4.1 failed to compile with CUDA 10.2.

Unfortunately, my preferred method of running pytorch via optimized [nvidia NGC Containers](https://ngc.nvidia.com/catalog/containers/nvidia:pytorch), wasn't applicable since torch 0.4.1 wasn't available.

Thankfully, CUDA 9.2 is still available in nvidia's CUDA yum repository for RHEL7 ([but not Ubuntu 18.04+](https://docs.nvidia.com/cuda/archive/9.2/cuda-installation-guide-linux/index.html)).  Solution was to `yum install cuda-9-2`, [update the LD_LIBRARY_PATH and PATH](https://docs.nvidia.com/cuda/archive/9.2/cuda-installation-guide-linux/index.html#environment-setup) to point to cuda 9.2, and [deploy pytorch 0.4.1 for cuda 9.2 binaries using conda](https://pytorch.org/get-started/previous-versions/#via-conda).
