### ISSUE TITLE
python Sequential allows duplicate names

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#19463]
## 🐛 Bug

`from collections import OrderedDict`
`from torch.nn import *`

`Sequential(OrderedDict([('A',Linear(1,2)),('B',Conv2d(3,4,5))]))`

_Sequential(
  (A): Linear(in_features=1, out_features=2, bias=True)
 (B): Conv2d(3, 4, kernel_size=(5, 5), stride=(1, 1))
)_

giving the modules the same name:
`Sequential(OrderedDict([('A',Linear(1,2)),('A',Conv2d(3,4,5))]))`

_Sequential(
  (A): Conv2d(3, 4, kernel_size=(5, 5), stride=(1, 1))
)_

it looks like the first module named "A" is dropped (?)
i would have expected an error similar to what happens from c++:

` using namespace torch::nn;`
`Sequential q(modules_ordered_dict({{"A", Linear(1,2)},{"A", Conv2d(3,4,5)}}));`

_'Key 'A' already defined_

**Comment by ailzhang** [comment]
Unfortunately this is not a behavior with `Sequential` but with Python `OrderedDict` instead. We cannot do much with it. 
```

In [15]: a = OrderedDict([('A',Linear(1,2)),('A',Conv2d(3,4,5))])
    ...:
    ...:

In [16]: a
Out[16]: OrderedDict([('A', Conv2d(3, 4, kernel_size=(5, 5), stride=(1, 1)))])
```
Closing as resolved, please feel free to reopen if you have followup questions. Thanks!
