### ISSUE TITLE
For torch.cholesky, switch to upper=True for the default, to standardize with related functions

### ISSUE THREAD

**Issue by chausies** [pytorch/pytorch#19461]
`torch.cholesky` has the `upper` param default to `False`. However, all the related functions, like `torch.potrs` and `torch.potri`, all have `upper` defaulting to `True`. This disconnect has even led to a bug in the example for the documentation of `torch.potri`, as I pointed in #19459. Since the functions feed into each other, their default params should be standardized to avoid such errors.

There's two fixes I propose. 

1. We could set the `upper` param to default to `True` in cholesky, so it falls in line with all its related functions, and makes the least changes to pytorch. 
2. We could change all the related functions to have `upper=False` as the default. This will make the most changes to pytorch, but `upper=False` is the standard used by e.g. numpy.

**Comment by vishwakftw** [comment]
This will be tracked in #19459. I will close the issue for now.
