### ISSUE TITLE
named_any.h should be included in modules.h (?)

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#19462]
## 🐛 Bug

using the c++ api, i have problems finding the function:
modules_ordered_dict()
unless i explicitly include the _any_module.h_ file.

should it be part of _modules.h_ ?

thanks

**Comment by meganset** [comment]
Realized I got the name of the NamedAnyModule header file wrong:
_named_any.h_ not _any_module.h_

I think _named_any.h_ should be included in _modules.h_

**Comment by soumith** [comment]
cc: @yf225 @gchanan
