### ISSUE TITLE
[FR] torch.cuda.synchronize takes in device objects

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#19509]
## 🚀 Feature
Currently it only synchronizes the current device. It would be great if it can  

+ take in a device object and automatically synchronize that device.

**Comment by ezyang** [comment]
We will accept a PR that makes `torch.cuda.synchronize(device=None)`. Make sure it checks that the input device is actually CUDA.

@gchanan is not sure what the point of the stream version of this function is, since `stream.synchronize()` is pretty easy.

**Comment by SsnL** [comment]
This can be easily done with https://github.com/pytorch/pytorch/blob/5d5d67fa3f8e19a2ca972b6c20d4fdba264d560e/torch/cuda/_utils.py#L5, if anyone wants to implement.
