### ISSUE TITLE
Wrong info about amplitude range for torchaudio.load

### ISSUE THREAD

**Issue by f90** [pytorch/pytorch#19507]
## 📚 Documentation

Documentation for [torchaudio.load](https://pytorch.org/audio/index.html?highlight=load#torchaudio.load) says that the resulting audio is normalized to [0,1] range. However, simply loading an audio signal and looking at the output of torch.min(signal) reveals it's actually normalized to [-1,1], so the documentation should be fixed.

**Comment by ailzhang** [comment]
This is an bug report in https://github.com/pytorch/audio. Opened one there. Closing this one. Please feel free to reopen if you see further issues. Thanks!
