### ISSUE TITLE
[feature request] add tuple support for dim specification of squeeze() and unsqueeze()

### ISSUE THREAD

**Issue by erogol** [pytorch/pytorch#1951]
Currently squeeze and unsqueeze functions seem to allow only single dimension as an argument. I think it would be useful, if they allow tuple specification of multiple dimensions. Something like
```python
y = th.squeeze(x, dim=(0,2)) 
```

**Comment by soumith** [comment]
good call, this would indeed be nice.

**Comment by soumith** [comment]
a PR https://github.com/pytorch/pytorch/pull/4692#issuecomment-394927742 attempted to do this, but the semantics and behavior are very unintuitive, so we decided it wasn't worth the user-confusion that results from this.
