### ISSUE TITLE
[jit] Support scope() for scriptModule

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#19527]
## 🚀 Feature
Request scoping information in scriptModule

## Motivation

For graph mode quantization, we need to know the scope of any node in the flattened graph. Currently, this works for traced modules, but not for scripting
## Pitch

node.scope() should return the same value in tracing and scripting. Without this feature, we cannot support quantization with user configuration at the module level in scriptMode.

**Comment by zdevito** [comment]
More context: we should be using the Scope data structure to track the function in which a node was defined, even if we end up inlining the node. Right now this information is being set for traced modules, but nothing equivalent happens for script modules. We should fix this. We should also make it easy to go from  (top-level module, scope) to method being defined.

**Comment by wanchaol** [comment]
I think this is supported already. Closing.
