### ISSUE TITLE
Advanced indexing on the GPU

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#1953]
For advanced indexing with the duplicate indexes, it is expected that the last one should win, e.g. with the input 
```
  0   1   2   3   4
  5   6   7   8   9
 10  11  12  13  14
 15  16  17  18  19
``` 
```indexer = [slice(None, None, None), [0, 1, 1, 2, 2]]``` and val
```
 16  12   0  14  10
 19  17   2   7   4
  5   9   6   1  15
 13  11   3   8  18
```
the expected output of ```input[indexer]=val``` is
``` 
16   0  10   3   4
19   2   4   8   9
 5   6  15  13  14
13   3  18  18  19
```
there are tests checking that. Yet the kernels doing the indexing (indexCopyLargeIndex and indexCopySmallIndex) provide no such guarantee - if the same dstOffset is shared by several threads, there is no guarantee on which write would be last, and no effort is made before launching the kernels to make sure that dstOffsets would be unique for all threads. This is not really fixable until the indices are de-duplicated and only the unique dstOffsets are present in those kernels. I don't know the best way to handle this. Disable advanced indexing with dupes, say results is undefined, de-dupe the indices? @killeent

**Comment by apaszke** [comment]
I'm ok with saying it's UB (so either value can be there).

**Comment by csarofeen** [comment]
We could do a pre-processing kernel with atomics for the indices. Save the max index that accesses a given destination, then in the second pass only write to that address if your index matches the one stored.

This wouldn't be as fast as setting this to UB but would keep parity with Numpy.
