### ISSUE TITLE
using occupancy calculator instead of fixed constant for threads per block

### ISSUE THREAD

**Issue by ThisIsIsaac** [pytorch/pytorch#19543]
## 🚀 Feature

In [THCapply.cuh](https://github.com/pytorch/pytorch/blob/e45e3634d6dff9384d899a6a3623572342af6032/aten/src/THC/THCApply.cuh#L113), I found a comment:
```
// FIXME: use occupancy calculator instead
#define THC_APPLY_THREADS_PER_BLOCK (32 * 16)
#define THC_APPLY_BLOCKS_PER_SM 4
```

How would you like to configure the block launch? to fully saturate all the SMs? or are you finding the balance point between higher throughput and higher occupancy?

Anyhow, if we could talk about how you would like to configure this, I can implement this.

Thanks.

**Comment by ThisIsIsaac** [comment]
I was looking into [THCApply.cuh](https://github.com/pytorch/pytorch/blob/e45e3634d6dff9384d899a6a3623572342af6032/aten/src/THC/THCApply.cuh#L113) which eventually me to the function: `THCudaHalfTensor_new`. This seems to allocate device memory ( some how without taking as input the number of elements ). I have searched in all of github and google, but there seems to be no function definition of `THCudaHalfTensor_new` and other such variants ( like `THCudaByteTensor_new` ).  What does this function do?

**Comment by soumith** [comment]
@ThisIsIsaac it's a constructor for a Tensor. It's generated by C macros, what you probably want to look for is `THCTensor_(new)` or `THCudaTensor_(new)`

**Comment by ThisIsIsaac** [comment]
@soumith 
Thanks!

**Comment by colesbury** [comment]
@ThisIsIsaac  -- I don't think it's worth changing this:

1. We're moving away from the THCApply pattern. 
2. The kernels are already memory-bandwidth bound (for most cases). Messing with the threads-per-block or work-per-thread is not likely to make it any faster.

**Comment by ThisIsIsaac** [comment]
@colesbury 
Sounds good. I won't proceed then.
