### ISSUE TITLE
toch.jit.trace can not handle torch.nn.Unfold

### ISSUE THREAD

**Issue by xin-xinhanggao** [pytorch/pytorch#19553]
## 🐛 Bug

I want to do inference in C++ by the guide of link https://pytorch.org/tutorials/advanced/cpp_export.html. Part of my model use the Unfold operation, which seems can't handled correctly by torch.jit.trace.
## To Reproduce

```
import torch
from torch.autograd import Variable

class UnfoldTestModule(torch.nn.Module):
	def __init__(self):
		super(UnfoldTestModule, self).__init__()
		self.unfold = torch.nn.Unfold(kernel_size=(3,3))

	def forward(self, input):
		output = self.unfold(input)
		return output


if __name__ == '__main__':
	my_module = UnfoldTestModule()
	example_input = torch.randn(2, 5, 3, 4)

	traced_script_module = torch.jit.trace(my_module, example_input)
	traced_script_module.save("model.pt")
```

## Error Report 

I got the error report like this:
```
RuntimeError:
Could not export python function call Im2Col. Revome calls to python functions before export.
/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py(2838):unfold
```

## Environment

 - PyTorch Version (1.0.1.post2):
 - OS (Ubuntu 16.04):
 - How you installed PyTorch (`pip`):
 - Python version (2.7):
 - CUDA/cuDNN version (9.0/7.0.5):
 - GPU models and configuration (NVIDIA RTX 1080 TI):

**Comment by SsnL** [comment]
this probably requires moving `Im2Col` to cpp

**Comment by eellison** [comment]
Thanks for raising the issue. CC @driazati added unfold.

**Comment by driazati** [comment]
Could you try to see if you get the same error on nightly? Your example works fine for me on master. We moved fold/unfold ops to C++ a few months ago in #14597.

**Comment by xin-xinhanggao** [comment]
@driazati  Thanks for your advice, everything is OK with torch-nightly.
