### ISSUE TITLE
Cuda runtime error (8) : invalid device function at THCTensorMathPointwise.cu for latest build

### ISSUE THREAD

**Issue by dendisuhubdy** [pytorch/pytorch#1955]
So I've tried to compile Pytorch locally for development purposes under the (dev) anaconda environment and another one under (lisa) which I install from the instructions from pytorch.org, I've got a recent warning when running the VAE code on Pytorch tutorials when running it on the newest version.

    (dev) [SLURM] suhubdyd@kepler2:~/research/models/pytorch-models/vae$ python main.py 
    THCudaCheck FAIL file=/u/suhubdyd/research/dl-frameworks/pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu line=247 error=8 : invalid device function
    Traceback (most recent call last):
      File "main.py", line 138, in <module>
        train(epoch)
      File "main.py", line 108, in train
        recon_batch, mu, logvar = model(data)
      File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
        result = self.forward(*input, **kwargs)
      File "main.py", line 71, in forward
        mu, logvar = self.encode(x.view(-1, 784))
      File "main.py", line 54, in encode
        h1 = self.relu(self.fc1(x))
      File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
        result = self.forward(*input, **kwargs)
      File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 54, in forward
        return self._backend.Linear.apply(input, self.weight, self.bias)
      File "/u/suhubdyd/.conda/envs/dev/lib/python2.7/site-packages/torch/nn/_functions/linear.py", line 14, in forward
        output.add_(bias.expand_as(output))
    RuntimeError: cuda runtime error (8) : invalid device function at /u/suhubdyd/research/dl-frameworks/pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:247

while it doesn't matter for the stable distribution

    (lisa) [SLURM] suhubdyd@kepler2:~/research/models/pytorch-models/vae$ python main.py 
    Train Epoch: 1 [0/60000 (0%)]   Loss: 549.307800
    Train Epoch: 1 [1280/60000 (2%)]        Loss: 311.565613
    Train Epoch: 1 [2560/60000 (4%)]        Loss: 236.338989
    Train Epoch: 1 [3840/60000 (6%)]        Loss: 225.371078
    Train Epoch: 1 [5120/60000 (9%)]        Loss: 208.993668
    Train Epoch: 1 [6400/60000 (11%)]       Loss: 206.427368
    Train Epoch: 1 [7680/60000 (13%)]       Loss: 208.580597
    Train Epoch: 1 [8960/60000 (15%)]       Loss: 201.324646
    Train Epoch: 1 [10240/60000 (17%)]      Loss: 191.824326
    Train Epoch: 1 [11520/60000 (19%)]      Loss: 195.214188
    Train Epoch: 1 [12800/60000 (21%)]      Loss: 189.770447
    Train Epoch: 1 [14080/60000 (23%)]      Loss: 173.119644
    Train Epoch: 1 [15360/60000 (26%)]      Loss: 179.030197
    Train Epoch: 1 [16640/60000 (28%)]      Loss: 170.247345
    Train Epoch: 1 [17920/60000 (30%)]      Loss: 169.193451
    Train Epoch: 1 [19200/60000 (32%)]      Loss: 162.828690
    Train Epoch: 1 [20480/60000 (34%)]      Loss: 158.171326
    Train Epoch: 1 [21760/60000 (36%)]      Loss: 158.530518
    Train Epoch: 1 [23040/60000 (38%)]      Loss: 155.896255
    Train Epoch: 1 [24320/60000 (41%)]      Loss: 158.835968
    Train Epoch: 1 [25600/60000 (43%)]      Loss: 152.416977
    Train Epoch: 1 [26880/60000 (45%)]      Loss: 153.593964
    Train Epoch: 1 [28160/60000 (47%)]      Loss: 147.944260
    Train Epoch: 1 [29440/60000 (49%)]      Loss: 148.223892
    Train Epoch: 1 [30720/60000 (51%)]      Loss: 145.770905
    Train Epoch: 1 [32000/60000 (53%)]      Loss: 144.410706
    Train Epoch: 1 [33280/60000 (55%)]      Loss: 147.592163
    Train Epoch: 1 [34560/60000 (58%)]      Loss: 149.320328

**Comment by pavanky** [comment]
Did you compile pytorch on one machine and install it on another?

**Comment by dendisuhubdy** [comment]
@pavanky yes, I did a `python setup.py install` one machine, and I did a `conda install pytorch torchvision cuda80 -c soumith` on another, if that is what you mean.

**Comment by pavanky** [comment]
@dendisuhubdy The error you mentioned happens when you build a cuda application using the wrong gpu architecture. I am not sure how that might happen in your case. What GPU are you using?

**Comment by dendisuhubdy** [comment]
@pavanky Quadro P6000

**Comment by ngimel** [comment]
As @pavanky said, this error would appear if you compiled for one architecture, and deploy on another. It should not happen if you compile and run on the same machine (unless you have stale build directories where GPU architecture is somehow set incorrectly). Try removing you build directories (python setup.py clean) and recompiling. Also, make sure that you use CUDA 8, Pascal is not supported in earlier CUDA versions.

**Comment by pavanky** [comment]
@dendisuhubdy  Try to get the latest version of CUDA 8. @ngimel correct me if I am wrong, but I think CUDA 8 pre-releas (8.0.26) didn't support Pascal

**Comment by ngimel** [comment]
@pavanky, it supported Pascal, but as you've pointed out in another issue, compilation with CUDA 8 pre-release is still broken.

**Comment by xuyifeng-nwpu** [comment]
@pavanky @ngimel  As you said, I encounted the same ploblem .
My host's GPU is 980ti, while my other server's GPUs are  k80.  When I transfer my host's docker file to server and run the torch code， the same  error message show.  Can you solve the ploblem between two different GPU？

**Comment by soumith** [comment]
@xuyifeng-nwpu you can set this environment variable before compiling PyTorch in your docker:

```
export TORCH_CUDA_ARCH_LIST="3.0;3.5;5.0;5.2+PTX;6.0;6.1"
```

It will take much longer to compile, but the docker will work everywhere.

**Comment by xuyifeng-nwpu** [comment]
@soumith  Thank your reply. 
1:My code was not PyTorch but Torch.  I worry that the code of Torch  cannot run in the new Pytorch envieroment, so I havn't install PyTorch.   Do I need  install the PyTorch? Is the Torch's code compatible with the PyTorch?
2:Where and when  run the code ` export TORCH_CUDA_ARCH_LIST="3.0;3.5;5.0;5.2+PTX;6.0;6.1` . Forgive me as a new .
3: K80's CC is 3.7. Do the numbur 3.7 add to code as `export TORCH_CUDA_ARCH_LIST="3.0;3.5;3.7;5.0;5.2+PTX;6.0;6.1`

**Comment by pavanky** [comment]
@xuyifeng-nwpu you only need to export it when yo are building Torch / PyTorch. This is not needed during the runtime. And yes you will need to have 3.7 for k80. If you only care about 980 and K80, you can probably just use `export TORCH_CUDA_ARCH_LIST="3.7;5.2+PTX;"` to reduce the build time.

**Comment by dendisuhubdy** [comment]
@pavanky @xuyifeng-nwpu @soumith anything on my side that I could do to help you guys?

**Comment by xuyifeng-nwpu** [comment]
@pavanky@dendisuhubdy   thank your quick reply.
1:Is "building Torch"  equivalent to reinstalling the Torch?

2:Do the number of  3.7 and 5.2  represent the GPU's CC?

3:Where run the export code?
In the host or the docker's container?


Thanks again

**Comment by soumith** [comment]
as everyone on this thread pretty much said, @dendisuhubdy this is pretty much because you are compiling from source on one machine, and running the source-installation on another machine. My workaround is in the comments above. Closing the issue as there's no action to be taken from the pytorch devs side.

**Comment by soumith** [comment]
@YuesongNan even within DataParallel the situation should be the same. I think you might have multiple pytorch versions installed.
