### ISSUE TITLE
How to do prediction/inference for a batch of images at a time with libtorch?

### ISSUE THREAD

**Issue by asa008** [pytorch/pytorch#19561]
Anybody knows how to do prediction/inference for a batch of images at a time with libtorch/pytorch C++?
any reply would be appreciated, thank you!

**Comment by xsacha** [comment]
The input tensor is usually in the shape of (images, channels, width, height). The first dimension is images.
So if you have a tensor image of (1,3,128,128) you can combine with another using torch::cat or torch::stack to produce a tensor of (2,3,128,128).
