### ISSUE TITLE
integer typecast for predicted and target values

### ISSUE THREAD

**Issue by cosai** [pytorch/pytorch#19560]
I am newbie to pytorch and I am trying to get the integer typecast of output and predicted values. I believe that shouldn't be that hard.

## Issue description
I can not get the integer version of output and predicted values

## Code example
def trainNetwork( savedfilename: str, plotsfile: str, trainMatrix: np.array, isCuda ):
    inputs, targets = createInputOutput(trainMatrix)
    net = Net(inputs.shape[1])

    if torch.cuda.is_available() and isCuda:
        print("Cuda is used")
        net.cuda()

    log_interval = 10
    epochrange = 50
    # print(net)
    learning_rate = 1e-5
    optimizer = torch.optim.SGD(net.parameters(), lr=learning_rate, momentum=0.9)
    criterion = nn.MSELoss()
    accuracyPlot = []
    lossPlot = []
    absoluteErrorPlot=[]

    for epoch in range(epochrange):
        # input ve target is shuffled
        s = np.arange(inputs.shape[0])
        np.random.shuffle(s)
        inputs = inputs[s]
        targets = targets[s]
        lossRecorded = 1000000
        lowestmsqe = 1000000
        averageLoss = 0
        totalaccuracy=0
        maxAccuracy=0
        minAbsoluteError=10000000
        for batch_idx in range(len(targets)):
            if torch.cuda.is_available() and isCuda:
                data, target = Variable(torch.from_numpy(inputs[batch_idx])).cuda(), Variable(
                    torch.from_numpy(targets[batch_idx])).cuda()
                net_out = net(data.cuda())
                optimizer.zero_grad()
                criterion = criterion.cuda()
            else:
                data, target = torch.from_numpy(inputs[batch_idx]), torch.from_numpy(targets[batch_idx])
                net_out = net(data)
                optimizer.zero_grad()
            loss = criterion(net_out, target)
            if int(target.item())!=int(net_out.item()):
                loss.backward()
                optimizer.step()
            #print("target: " + str(target.item()) + " output:" + str(net_out.item()) + " loss:" + str(loss.item()))
            accuracytemp=0
            if target.item()!=0:
                accuracytemp = 1 - (math.fabs(target.item() - net_out.item())/target.item())
            else:
                accuracytemp = 1 - (math.fabs(net_out.item())/1e-7)

            absoluteError += math.fabs(target.item() - net_out.item())
            averageLoss += loss.item()
            totalaccuracy += accuracytemp

        averageLoss = averageLoss / len(targets)
        absoluteError = absoluteError / len(targets)
        totalaccuracy = totalaccuracy/len(targets)

        if averageLoss < lossRecorded:
            lossRecorded = averageLoss
            save_model(net, optimizer, savedfilename, epoch)

        if totalaccuracy > maxAccuracy:
            maxAccuracy = totalaccuracy

        if minAbsoluteError > absoluteError:
            minAbsoluteError=absoluteError

        accuracyPlot.append(totalaccuracy)
        lossPlot.append(averageLoss)
        absoluteErrorPlot.append(absoluteError)

    # Writing the plots.txt file
    print(str("Maximum accuracy for training is "+str(maxAccuracy)))
    print(str("Lowest absolute error for training is " + str(minAbsoluteError)))

    f = open(plotsfile, "w")

    f.write("epoch,accuracy,loss\n")
    for i in range(len(accuracyPlot)):
        f.write(str(i + 1) + "," + str(accuracyPlot[i]) + "," + str(lossPlot[i]) + "\n")
    f.close()

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.
Error message of Pycharm

Traceback (most recent call last):
  File "C:/Users/XXX/Desktop/smartpython/feedForwardSmartHouse.py", line 314, in <module>
    AllNetWork(datafile, list(range(0, 24)), i, getColumnNameToGuess(datafile, i))
  File "C:/Users/XXX/Desktop/smartpython/feedForwardSmartHouse.py", line 304, in AllNetWork
    trainNetwork(modelfile, plotsfile, trainMatrix, isCudaUsed)
  File "C:/Users/XXX/Desktop/smartpython/feedForwardSmartHouse.py", line 241, in trainNetwork
    if int(target.item())!=int(net_out.item()):
ValueError: only one element tensors can be converted to Python scalars

## System Info
I am using anaconda 3.Installed from website of anaconda

PyTorch version: 1.0.1
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Microsoft Windows 10 Home
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce GTX 960M
Nvidia driver version: 419.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl-service               1.1.2            py37hb782905_5
[conda] mkl_fft                   1.0.6            py37h6288b17_0
[conda] mkl_random                1.0.2            py37h343c172_0

**Comment by smessmer** [comment]
Thanks for the detailed description. This does not sound like a bug to me though. Can you ask your question in the PyTorch forums?
