### ISSUE TITLE
Too many resources requested for launch

### ISSUE THREAD

**Issue by DragonBornHD** [pytorch/pytorch#1956]
When I tried use the cuda8.0 on Jetson TX1 , report 
`cuda runtime error : too many resources requested for launch`
And I's work's with CPU.
Any help will be appreciated.

**Comment by pavanky** [comment]
One of the functions / modules being used is likely using too much shared memory. Can you share some reproducible code?

**Comment by soumith** [comment]
waiting for code reproduction. closing the issue until i get that.
