### ISSUE TITLE
cuda.FloatTensor constructor with float32 array

### ISSUE THREAD

**Issue by wjaskowski** [pytorch/pytorch#1957]
```python
FloatTensor(np.array([0,1,2], dtype=np.float64))
cuda.FloatTensor(np.array([0,1,2], dtype=np.float64))
FloatTensor(np.array([0,1,2], dtype=np.float32))
```
work as expected, while
```python
cuda.FloatTensor(np.array([0,1,2], dtype=np.float32))
```
fails with
```RuntimeError: tried to construct a tensor from a float sequence, but found an item of type numpy.float32 at index (0)```

PyTorch version: 0.1.12_2

**Comment by lantiga** [comment]
See comment at #2246: any preference between A) always throwing if types don't match, or B) resorting to a C-array cast in case types don't match?
With B, it might not always be obvious when a conversion from numpy is zero-cost.

**Comment by apaszke** [comment]
B has the same problem that we have right now, except the cost starts to be acceptable in most cases. If you want to ensure a zero-code creation use from_numpy

**Comment by wjaskowski** [comment]
I have no clear preference but I expect that if `cuda.FloatTensor(np.array([0,1,2], dtype=np.float32))` fails than `FloatTensor(np.array([0,1,2], dtype=np.float32))` should also fail and vice versa, which is not true right now.

**Comment by lantiga** [comment]
Yeah, good question.

All I can think of is that `TH_REAL_IS_DOUBLE` may be defined when building CUDA Float, so `NUMPY_TYPE_ENUM` gets defined to `NPY_DOUBLE` at https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/Tensor.cpp#L8 and the condition at https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/Tensor.cpp#L231 is true.
I don't have a CUDA machine right now to verify this though.

As soon as the discussion at #2246 is sorted out I'll fix the issue.

**Comment by lantiga** [comment]
In the end the issue is that `NUMPY_TYPE_ENUM` never gets defined for CUDA arrays. I have a PR almost ready to ship.
