### ISSUE TITLE
Serialized TorchScript model size changes every time

### ISSUE THREAD

**Issue by yzhao30** [pytorch/pytorch#19588]
## 🐛 Bug

Using `torch.jit.trace` to export the model, but the size of the serialized model file is changing every time.  

## To Reproduce

Just run the official example code:

```Python
import torch
import torchvision

# An instance of your model.
model = torchvision.models.resnet18()

# An example input you would normally provide to your model's forward() method.
example = torch.rand(1, 3, 224, 224)

# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
traced_script_module = torch.jit.trace(model, example)

traced_script_module.save("resnet18_model.pt")
```

## Expected behavior

The model size should be the same across the execution, right?

But it shows
```
46858910 Apr 22 13:36 resnet18_model.pt
46859168 Apr 22 16:00 resnet18_model_1.pt
```

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.4
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] numpydoc==0.8.0
[pip3] torch==1.0.1.post2
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.2.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl-service               1.1.2            py37hfbe908c_5
[conda] mkl_fft                   1.0.6            py37h27c97d8_0
[conda] mkl_random                1.0.2            py37h27c97d8_0
[conda] pytorch                   1.0.1                   py3.7_2    pytorch
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch

**Comment by suo** [comment]
Thanks for the report! We do not consider serialized model size to be a semantically meaningful property and thus don't make any guarantees about its consistency across traces. 

The serialized model format stores all parameters/buffers/attributes of the modules as well as various metadata about the model, any of which could have caused the 258-byte difference you are observing. For example, even having two different model names will cause a difference in size.

Let me know if you have any additional questions.
