### ISSUE TITLE
LSTM's Variables' sizes mismatch

### ISSUE THREAD

**Issue by LiyuanLucasLiu** [pytorch/pytorch#1961]
The size of weight_ih_l[k] in LSTM seems to be  (4*hidden_size x input_size). And it also happens to weight_hh_l[k]
e.g., 
```
tmp = nn.LSTM(2, 9)
pritn(tmp.weight_hh_l0.size())
```
would return
```
torch.Size([36, 9])
```

**Comment by ngimel** [comment]
That's expected, 4 matrix multiplies with input and with hidden in lstm are combined into 1.

**Comment by LiyuanLucasLiu** [comment]
sorry i didnt make clear, i know it's expected. But it's different from the doc, which describes it to be `input_size x 4*hidden_size`
the link is:
http://pytorch.org/docs/master/nn.html#lstm

**Comment by ruotianluo** [comment]
Yes, the doc is wrong.

**Comment by soumith** [comment]
thanks for reporting this. fixed docs via https://github.com/pytorch/pytorch/commit/e26139b7f77a9b2ba88c52310b8ae41f512e36dd
