### ISSUE TITLE
How to understand the results of model. Eval () and how to obtain the predictive probability value?

### ISSUE THREAD

**Issue by xujiameng** [pytorch/pytorch#19611]
Hello everyone
I've been using tensorflow before, but I met torch when I added functionality to a tool. My ultimate goal was to get the classification probability. On a binary classification problem, I used model. Eval () (inputs). numpy () to get the prediction results.

like this 
2.19903	-2.06323
2.22841	-2.09061
2.20833	-2.07209
2.22888	-2.09125
2.22644	-2.08869

I don't know how to convert it to probability, or should I use other commands to get classification probability?

I hope I can get help. Thank you.

**Comment by jerryzh168** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
