### ISSUE TITLE
Cuda compilation path for building extension

### ISSUE THREAD

**Issue by DarwinSenior** [pytorch/pytorch#1964]
I was trying to compile around other people's code with the ffi module. 
My current system is arch linux and the path for cuda is `/opt/cuda`. 
As I found out that the path for create_extension is hard coded to be `/usr/local/cuda` (debian) and `/Developer/NVIDIA/CUDA-*`(mac os). 
So, I hack around a little bit to add
```python
        cuda_include_dirs += glob.glob('/opt/cuda/include')
```
to make it compile on my system.

I think the proper way to do that is make the library path as a configurable parameter like

```python
def create_extension(name, headers, sources, verbose=True, with_cuda=False,
                     cuda_root_dir=None, # make it as a parameter
                     package=False, relative_to='.', **kwargs):
```
And we could figure out cuda_root_dir (either `/opt/cuda`, `/usr/local/cuda`, `/Developer/NVIDIA/CUDA-*`) by 
1. supply it as a parameter
2. env variable `CUDA_ROOT`
3. Figure it out from common system

**Comment by soumith** [comment]
Here's an example of a pytorch extension with CUDA parts. It allows you to specify `CUDA_HOME` to pickup CUDA path: https://github.com/sniklaus/pytorch-extension
Hope this helps.

**Comment by cpuhrsch** [comment]
@DarwinSenior - is this issue still current?
