### ISSUE TITLE
Problem about the output of packed sequence

### ISSUE THREAD

**Issue by CholoeMoretz** [pytorch/pytorch#19649]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

`import torch
import torch.nn as nn

batch_size = 3
max_length = 3

batch_in = torch.LongTensor(batch_size, max_length).zero_()
batch_in[0] = torch.LongTensor([1, 2, 3])
batch_in[1] = torch.LongTensor([4, 5, 0])
batch_in[2] = torch.LongTensor([6, 0, 0])
seq_lengths = [3, 2, 1]
pack = torch.nn.utils.rnn.pack_padded_sequence(batch_in, seq_lengths, batch_first=True)
print(pack)`

then the output is
`PackedSequence(data=tensor([ 1,  4,  6,  2,  5,  3]), batch_sizes=tensor([ 3,  2,  1]))`
From what I understand, if we put sentences into RNN or LSTM, the sentence should be in order, but from the output, the data is 1,4,6,2,5,3, which pack the sequence in a vertical way. If we put this packed sequence into RNN, how does the RNN read the data?

**Comment by pietern** [comment]
Please post questions (or find existing answers) on https://discuss.pytorch.org/.
