### ISSUE TITLE
Pytorch build fails on Ubuntu 16.04.6 LTS

### ISSUE THREAD

**Issue by sri-oc** [pytorch/pytorch#19642]
## 🐛 Bug
nvcc fatal   : The version ('70100') of the host compiler ('clang') is not supported
using llvm-7.0

## To Reproduce

python3 setup.py install

## Expected behavior
Build shall pass with no error.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: N/A
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1060 6GB
Nvidia driver version: 418.39
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip3] numpy==1.16.3
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.3                      199  
[conda] mkl-service               1.1.2            py27he904b0f_5  
[conda] mkl_fft                   1.0.6            py27hd81dba3_0  
[conda] mkl_random                1.0.2            py27hd81dba3_0  
[conda] pytorch-nightly           1.0.0.dev20190327 py2.7_cuda10.0.130_cudnn7.4.2_0    pytorch

```

**Comment by pietern** [comment]
I believe you can only use LLVM 7 with CUDA 10.

You have the nightly build installed that depends on CUDA 10. Do you have multiple CUDA versions installed on your system by any chance? The CMake output will confirm which versions (both CUDA and LLVM) you're trying to build against.

**Comment by srinivas491-oneconvergence** [comment]
Thanks @pietern . 

it's strange that LLVM 7 has to use only with CUDA10. As you have pointed out I had both CUDA 9 and 10 installed on my system. I removed CUDA 9. The build process is working fine with CUDA 10.
