### ISSUE TITLE
THCudaTensor_cadd(state, output, input1, 1.0, input2) cannot pass when run inWINDOWS,help

### ISSUE THREAD

**Issue by liuchanfeng165** [pytorch/pytorch#19657]
Hi，pytorch pioneer, the code cannot work  using ptrotch0.4.0 in WINDOWS.Could U help me.as follow：
 int my_lib_add_forward_cuda(THCudaTensor *input1, THCudaTensor *input2,
		       THCudaTensor *output)
{
  if (!THCudaTensor_isSameSizeAs(state, input1, input2))
    return 0;
  printf("insert my_lib_add_forward_cuda : ");
  printf("%d", state);
  THCudaTensor_resizeAs(state, output, input1);
  printf("\n THCudaTensor_resizeAs pass ");
//no passing
  THCudaTensor_cadd(state, output, input1, 1.0, input2);
   printf("\n THCudaTensor_cadd pass ");
  return 1;
}
![image](https://user-images.githubusercontent.com/18642811/56627751-b5e0df00-6679-11e9-88d3-1bcb01cfc13d.png)

regards

**Comment by peterjc123** [comment]
CFFI extensions are deprecated now. Please try cpp extensions instead.

**Comment by liuchanfeng165** [comment]
> CFFI extensions are deprecated now. Please try cpp extensions instead.

thanks, i did a example however it contents a bug as follow：
![image](https://user-images.githubusercontent.com/18642811/56632271-8e930d80-668b-11e9-9274-f6a2b3375b39.png)
forked from: https://pytorch.org/tutorials/advanced/cpp_extension.html

**Comment by peterjc123** [comment]
Would you please try if that's still a problem if you use VS 2017?

**Comment by liuchanfeng165** [comment]
> Would you please try if that's still a problem if you use VS 2017?

VS2015 only
