### ISSUE TITLE
interpolate bicubic should follow opencv result

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#19650]
Other interpolate modes(like `bilinear`) are designed to follow the opencv result. We should do that for `bicubic` as well. 
The behavior seem to have changed in TF2.0 as well. cc: @ppwwyyxx 
```
import cv2
import torch
import torch.nn.functional as F

SIZE_HW = (247, 111)
SIZE_WH = (111, 247)

t = torch.rand(1, 17, 64, 64)


pt_result = F.interpolate(t, size=SIZE_HW, mode="bicubic", align_corners=True)
cv_result = torch.from_numpy(cv2.resize(t.squeeze(0).permute(1, 2, 0).numpy(), SIZE_WH, interpolation=cv2.INTER_CUBIC)).permute(2, 0, 1).unsqueeze(0)


print("max abs diff:", (pt_result - cv_result).abs().max())
print("max rel diff:", ((1 - pt_result) / cv_result).abs().max())
print("MSE:", ((pt_result - cv_result) ** 2).mean())
```

**Comment by ailzhang** [comment]
cc: @driazati @fmassa

**Comment by jonmorton** [comment]
Here's the output I get with the test:

```
align_corners=False
max abs diff: tensor(0.5807)
max rel diff: tensor(182545.6875)
MSE: tensor(0.0277)

align_corners=True
max abs diff: tensor(0.5125)
max rel diff: tensor(395947.0938)
MSE: tensor(0.0097)
```

The max absolute difference is more than half the entire range of values. It seems a bit large.

**Comment by fmassa** [comment]
I know of at least one inconsistency between bilinear and bicubic interpolation in PyTorch - the ranges in the bicubic interpolation do not subtract 0.5

I'm not with my computer now, but I have a reimplementation of the interpolate functions which are separable and that reproduce the interpolation results in PyTorch. I can share them here tomorrow and see if by changing the point I mentioned is enough to match opencv results

**Comment by ailzhang** [comment]
@jonmorton FYI the PR above should fix the issue. 
I didn't put exact same repro script as testcase as I feel it's not good to install cv2 just for this baseline so I added a "expected result" check there. 
For referecen, after the patch the script (node with `align_corners=False`) matches opencv result. 
```
('max abs diff:', tensor(7.4208e-06))
('max rel diff:', tensor(80458.5469))
('MSE:', tensor(9.1130e-13))
```

**Comment by VasLem** [comment]
The difference seems to have increased again. In Pytorch 1.13.0, the example code brings:
 ```
max abs diff: tensor(0.4889)
max rel diff: tensor(79371.5156)
MSE: 
tensor(0.0096)
```
