### ISSUE TITLE
Equivalent of tf.gather , tf.scatter, tf.update in pytorch

### ISSUE THREAD

**Issue by Sushobhan04** [pytorch/pytorch#1965]
Is there an equivalent of tensor operations like tf.gather, tf,scatter, tf.update (tensorflow tensor operations) in pytorch without returning the same size tensor?

If yes, that would be a great help for me since I only need a specific part of the tensor. Else it would be a good operations to have, since they add versatility to the operations that can be performed on a tensor.

I am currently using tensorflow for a piece of code, but the dynamic graph of pytorch can be very useful for my application as I can dynamically select parts of the tensor, but I need to be able to tf.gather and tf.scatter. Are there alternative hacks to perform similar operations in pytorch ?

**Comment by soumith** [comment]
have you tried looking for these operations in our documentation? (there is a search box).

**Comment by soumith** [comment]
also, if you have questions: https://discuss.pytorch.org
