### ISSUE TITLE
CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by liuchanfeng165** [pytorch/pytorch#19669]
## ❓ Questions and Help
Hi，Peter
I followed the solution by https://github.com/zhanghang1989/PyTorch-Encoding/issues/161，but it didnot work.
![image](https://user-images.githubusercontent.com/18642811/56656876-3549cf00-66c9-11e9-9518-f9b03ab9df62.png)
give me some advice，pls..

**Comment by liuchanfeng165** [comment]
> ##  Questions and Help
> Hi，Peter
> I followed the solution by [https://github.com/zhanghang1989/PyTorch-Encoding/issues/161，but](https://github.com/zhanghang1989/PyTorch-Encoding/issues/161%EF%BC%8Cbut) it didnot work.
> ![image](https://user-images.githubusercontent.com/18642811/56656876-3549cf00-66c9-11e9-9518-f9b03ab9df62.png)
> give me some advice，pls..
well done:
forked from https://github.com/zhanghang1989/PyTorch-Encoding/issues/70

**Comment by Gowtham171996** [comment]
@liuchanfeng165  Did you found the solution?
