### ISSUE TITLE
nvrtc.h not found

### ISSUE THREAD

**Issue by wujushan** [pytorch/pytorch#19666]
- Ubuntu 18
- CUDA 10.0
- pytorch 1.1.0 (directly clone the latest version from GitHub)
- anaconda 4.6.14

An error occurred when I build pytorch.

In file included from ../torch/csrc/jit/fuser/cuda/thnvrtc.cpp:1:0:
../torch/csrc/jit/fuser/cuda/thnvrtc.h:4:10: fatal error: nvrtc.h: No such file or directory
 #include <nvrtc.h>

But I have installed libnvrtc9.1 by apt. The strange thing is that there is not nvrtc.h in my system. I think the nvrtc is not properly installed in my system. Does anyone know how can I properly install nvrtc or how to fix this problem?

Thanks very much

**Comment by xsacha** [comment]
The lib may not contain the headers. You would need the dev package. Also you said you have CUDA 10, so your nvrtc should match that version.


This is outside the scope of this repository but I will help anyway. The header is available in the package manager. I know as that is what I have used.

If you have any trouble locating files within a package on Ubuntu, you can use the tool: apt-file
sudo apt install apt-file
apt-file search nvrtc.h

**Comment by pietern** [comment]
Thanks for commenting @xsacha!

I ran the following from the `nvidia/cuda:10.0-devel` Docker container (see https://hub.docker.com/r/nvidia/cuda/) to confirm you need the nvrtc development package to pull in the header file.

```
root@b67ce5ba7a4a:/# dpkg -l | grep nvrtc                                                                                                                                                     
ii  cuda-nvrtc-10-0               10.0.130-1                        amd64        NVRTC native runtime libraries                                                                               
ii  cuda-nvrtc-dev-10-0           10.0.130-1                        amd64        NVRTC native dev links, headers                                                                              
root@b67ce5ba7a4a:/# dpkg -L cuda-nvrtc-dev-10-0 | grep nvrtc.h                                                                                                                               
/usr/local/cuda-10.0/targets/x86_64-linux/include/nvrtc.h
```

**Comment by FCInter** [comment]
I just met this problem today. I finally found that my problems was caused by an incomplete installation of the CUDA. Typically the `nvrtc.h` file should be located at directories such as `/usr/local/cuda/include`. If you cannot find it there, you should reinstall the CUDA toolkit. 
Hope this could help.

**Comment by wujushan** [comment]
Hi @FCInter, thank for your reply. As you said, incomplete installation of the CUDA causes it. So I have fixed it by reinstalling the CUDA toolkit.
