### ISSUE TITLE
LSTM batch_first flag does not produce ouputs with the batch as the first dimension.

### ISSUE THREAD

**Issue by al093** [pytorch/pytorch#19675]
**Documentation issue**

In the [documentation](https://pytorch.org/docs/stable/nn.html#lstm) of PyTorch 1.0.1. It is mentioned that:

> batch_first – If True, then the input and output tensors are provided as (batch, seq, feature). Default: False

So I would expect the ouput tensor h_n of shape: (batch, num_layers * num_directions, hidden_size). But it is not the case. The batch is the second dimension, which does not match with the above statement from the documentation.
 
## To Reproduce

```
input = torch.rand([60, 8, 256]) #batch size is 60, sequence size is 8, features are 256
lstm = torch.nn.LSTM(256, 512, batch_first=True)
_, (finalHiddenState, _) = lstm(input)
print(finalHiddenState.shape)
Ouput: torch.Size([1, 60, 512]) 
```
Batch (60) is now the second dimension here

**Comment by zou3519** [comment]
This isn't a bug: (batch, seq, feature) corresponds to the output tensor of lstm:
```
output, (hx, cx) = lstm(input)
```
We could improve the documentation around this, but I'm not sure that the hidden state should also have its batch transposed to be first. Do you have a use case for that, @al093?

**Comment by SsnL** [comment]
Note that there is no notion of `seq` for hidden states. The output shape is just `[num_players x batch x size]`.

**Comment by al093** [comment]
@zou3519 Yes there was a use case for me, but I would not go into the specifics of that, because first its explaination would be long, and second, it can solved easily using permute.

I more or less pointed out this question because - I think the document should explicity say that the h_n and c_n are not in batch first order, even though batch_first is set true. This can be a potential overlooked bug while coding.

**Comment by al093** [comment]
> Note that there is no notion of `seq` for hidden states. The output shape is just `[num_players x batch x size]`.

I dont get your terminology - `num_players and size `- here.
 
But anyways, there is a hidden state for every sequence step, which is available in the output tensor. You might want to have a look at [this](https://stackoverflow.com/questions/48302810/whats-the-difference-between-hidden-and-output-in-pytorch-lstm).

**Comment by SsnL** [comment]
@al093 I don’t know what you are arguing about... the source you linked even says 
> h_n (num_layers * num_directions, batch, hidden_size): tensor containing the hidden state for t=seq_len
> c_n (num_layers * num_directions, batch, hidden_size): tensor containing the cell state for t=seq_len

Which is just consistent with my words. 

Only the last hidden state is returned.

**Comment by SsnL** [comment]
num_layers and num_directions are different dimensions than seq_length. It is natural that they aren’t permuted the same way as seq_length.

**Comment by link2xt** [comment]
Duplicate? #4145

**Comment by zou3519** [comment]
This is indeed a duplicate so I'm closing this. Let's have all discussions in #4145
