### ISSUE TITLE
1 error detected in the compilation of "C:/Users/CS165/A _0000361c_00000000-11_lltm_cuda_kernel.cpp1.ii". error: command 'C:\\Program Files\\NVIDIA GPU Computing \\nvcc.exe' failed with exit status 2

### ISSUE THREAD

**Issue by liuchanfeng165** [pytorch/pytorch#19671]
## ❓ Questions and Help
![image](https://user-images.githubusercontent.com/18642811/56662049-a3948e80-66d5-11e9-8655-fa8acc37bcc7.png)

is it maybe caused by CUDA  version?
CMD: python3 setup.py build_ext

**Comment by pietern** [comment]
Please look back at the template for new issues and fill out details about your environment.

Is the warning shown the error?

**Comment by liuchanfeng165** [comment]
##environment
win7
CUDA8.0
py3.6
ninja 1.9
torch1.0.1

##compiling file lltm_cuda_kernel.cu  
## logs
lltm_cuda_kernel.cu
E:/Python36/lib/site-packages/torch/lib/include\c10/util/Exception.h(27): warnin
g: base class dllexport/dllimport specification differs from that of the derived
 class

E:/Python36/lib/site-packages/torch/lib/include\c10/util/Exception.h(28): warnin
g: field of class type without a DLL interface used in a class with a DLL interf
ace

E:/Python36/lib/site-packages/torch/lib/include\c10/util/Exception.h(29): warnin
g: field of class type without a DLL interface used in a class with a DLL interf
ace
。
。（  same warmings）
。
E:/Python36/lib/site-packages/torch/lib/include\c10/util/Array.h(183): warning:
"constexpr" is ignored here in Microsoft mode

E:/Python36/lib/site-packages/torch/lib/include\c10/util/Array.h(189): warning:
"constexpr" is ignored here in Microsoft mode

E:/Python36/lib/site-packages/torch/lib/include\c10/util/Array.h(198): warning:
"constexpr" is ignored here in Microsoft mode

E:/Python36/lib/site-packages/torch/lib/include\torch/csrc/jit/interpreter.h(42)
: warning: field of class type without a DLL interface used in a class with a DL
L interface

E:/Python36/lib/site-packages/torch/lib/include\torch/csrc/jit/argument_spec.h(5
9): error: static assertion failed with "ArgumentInfo is to be a POD struct"

E:/Python36/lib/site-packages/torch/lib/include\torch/csrc/jit/graph_executor.h(
41): warning: field of class type without a DLL interface used in a class with a
 DLL interface

E:/Python36/lib/site-packages/torch/lib/include/torch/csrc/api/include\torch/ser
ialize/input-archive.h(78): warning: field of class type without a DLL interface
 used in a class with a DLL interface

E:/Python36/lib/site-packages/torch/lib/include/torch/csrc/api/include\torch/ser
ialize/output-archive.h(66): warning: field of class type without a DLL interfac
e used in a class with a DLL interface

1 error detected in the compilation of "C:/Users/CS165/AppData/Local/Temp/tmpxft
_00004630_00000000-11_lltm_cuda_kernel.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin
\\nvcc.exe' failed with exit status 2

**Comment by liuchanfeng165** [comment]
use nvcc9.2  to compile files and modify  fmax( 0。0, z) to ‘’fmax( (scalar_t)0, z)  in the  .cu file
with errors that 
![image](https://user-images.githubusercontent.com/18642811/56786587-0f890b00-682c-11e9-9ecd-bbc62be37505.png)
