### ISSUE TITLE
Unexpected numeric limit for CUDA integral types

### ISSUE THREAD

**Issue by LeviViana** [pytorch/pytorch#19673]
# To Reproduce
```python
import torch
x = torch.ones(0).cuda()
print(x.float().max().item()) # -inf
print(x.int().max().item()) # 0
```
# Expected behavior
`print(x.int().max().item())` should output the `lowest` numeric limit for the integer type.

# Note
The same issue arises for all integral types: byte, short, int and long.
Related to #19612.

**Comment by colesbury** [comment]
See @gchanan's comment here: https://github.com/pytorch/pytorch/issues/17750#issuecomment-486302496

**Comment by gchanan** [comment]
this has been fixed.
