### ISSUE TITLE
ImportError: No module named 'lltm_cuda'

### ISSUE THREAD

**Issue by liuchanfeng165** [pytorch/pytorch#19670]
## ❓ Questions and Help
help help,last error as follow:
![image](https://user-images.githubusercontent.com/18642811/56660692-a2ae2d80-66d2-11e9-890a-fdf6a3a63a9f.png)

thanks...

**Comment by amaanda** [comment]
I am getting the same error when trying to import a module. I can use it on Python, but when I try to use it with Pytorch, it gives me the same error you're getting. My guess is there is some problem with our path?

**Comment by liuchanfeng165** [comment]
> I am getting the same error when trying to import a module. I can use it on Python, but when I try to use it with Pytorch, it gives me the same error you're getting. My guess is there is some problem with our path?

something different was  that complied in default dir by ninja compiler linked to a package  and the default dir is temporary so that i cant  modify its dir...BTW,wating for Peter....

**Comment by liuchanfeng165** [comment]
solution：
add 
build_directory = 'G:\extension-ffi-master\script\extension-cpp-master\cpp',#module of lltm_cpp  compiled  by setup.py is producted and then add add its dir name into jit.py
into jit.py
ok ， it cost a day。。。。
