### ISSUE TITLE
version `GLIBC_2.7' not found when import pytorch

### ISSUE THREAD

**Issue by whitezhang** [pytorch/pytorch#1967]
I have downloaded torch-0.1.12.post2-cp27-none-linux_x86_64.whl(from http://download.pytorch.org/whl/cu75/torch-0.1.12.post2-cp27-none-linux_x86_64.whl ) file and use the following command to install.

```
pip install torch-0.1.12.post2-cp27-none-linux_x86_64.whl
pip install pip install torchvision
```

However, the error occurs when import torch

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/my/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /lib64/tls/libc.so.6: version `GLIBC_2.7' not found (required by /home/my/lib/python2.7/site-packages/torch/lib/libTH.so.1)
```

My Linux kernel is 2.6.32_1-19-0-0 and GCC version is 4.8.3
How can I fix this problem?

**Comment by colesbury** [comment]
Responded on Stackoverflow:

https://stackoverflow.com/questions/44843033/version-glibc-2-7-not-found-when-import-pytorch/44954311#44954311
