### ISSUE TITLE
torch.transpose doesn't shares it’s underlying storage with the original tensor

### ISSUE THREAD

**Issue by BruceK4t1qbit** [pytorch/pytorch#19697]
## 🐛 Bug

This concerns the method:
torch.transpose(input, dim0, dim1) → Tensor

According to the documentation, https://pytorch.org/docs/stable/torch.html :
> The resulting out tensor shares it’s underlying storage with the input tensor, so changing the content of one would change the content of the other.

However, transposed versions of the original tensor are not changed when the original tensor's data is changed via "set_" method (specifically).

## To Reproduce
```
import torch
from torch import Tensor
t = Tensor([[-1,2]])
ttr = t.transpose(0,1)
print(f" t is: \n{t}")
print(f" ttr is: \n{ttr}")
print("-"*20)

t[0,0] = 5
print(f" t is: \n{t}")
print(f" ttr is: \n{ttr}")
print(f"The transposed version was updated, as expected")
print("-"*20)

t[:,:] = Tensor([[10,20]])
print(f" t is: \n{t}")
print(f" ttr is: \n{ttr}")
print(f"The transposed version was updated, as expected")
print("-"*20)

t.add_(Tensor([[2,2]]))
print(f" t is: \n{t}")
print(f" ttr is: \n{ttr}")
print(f"The transposed version was updated, as expected")
print("-"*20)

t.set_(Tensor([[-1,-2]]))
print(f" t is: \n{t}")
print(f" ttr is: \n{ttr}")
print(f"Note that the transposed version was not updated!")
```

>  t is: 
> tensor([[-1.,  2.]])
>  ttr is: 
> tensor([[-1.],
>         [ 2.]])
> --------------------
>  t is: 
> tensor([[5., 2.]])
>  ttr is: 
> tensor([[5.],
>         [2.]])
> The transposed versions were updated, as expected
> --------------------
>  t is: 
> tensor([[10., 20.]])
>  ttr is: 
> tensor([[10.],
>         [20.]])
> The transposed versions were updated, as expected
> --------------------
>  t is: 
> tensor([[12., 22.]])
>  ttr is: 
> tensor([[12.],
>         [22.]])
> The transposed versions were updated, as expected
> --------------------
>  t is: 
> tensor([[-1., -2.]])
>  ttr is: 
> tensor([[12.],
>         [22.]])

## Expected behavior
I expect that "changing the content of one (via set_) would change the content of the other.", as per the documentation.

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.3
GCC version: Could not collect
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.14.5
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

**Comment by SsnL** [comment]
I'd say this is expected. `set_` does not modify the storage content of a tensor, but changes the storage object altogether.... The old storage is shared, but not the new one.

**Comment by BruceK4t1qbit** [comment]
This is not what I understand from this documentation: https://pytorch.org/docs/stable/tensors.html

> Methods which mutate a tensor are marked with an underscore suffix. For example, torch.FloatTensor.abs_() computes the absolute value in-place and returns the modified tensor, while torch.FloatTensor.abs() computes the result in a new tensor.

**Comment by soumith** [comment]
@BruceK4t1qbit 

> Methods which mutate a tensor are marked with an underscore suffix.

Yes, `set_` mutates the Tensor -- by changing it's storage in-place. That's why it has a postfix `_`.

I think what you are looking for is `copy_` instead of `set_`

**Comment by BruceK4t1qbit** [comment]
@soumith thanks
