### ISSUE TITLE
Conv double backwards with groups != 1 fails with size mismatch

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#1972]
Here's a commit that adds conv double backwards checks with groups != 1: https://github.com/gchanan/pytorch/commit/5b1269d65a5f873b31fc8b544dab5b0902d40522

Applying this and running:
```
python test/test_nn.py TestNN.test_conv_double_backward
```

gives me:
```
======================================================================
ERROR: test_conv_double_backward (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_nn.py", line 2439, in test_conv_double_backward
    no_weight, groups = chan_in)
  File "test/test_nn.py", line 2425, in run_conv_double_back_test
    dummy_out = func(*inputs)
  File "test/test_nn.py", line 2414, in func
    out = F.conv2d(lx, lweight, lbias, stride, padding, dilation, groups)
  File "/.../torch/nn/functional.py", line 50, in conv2d
    return f(input, weight, bias)
RuntimeError: Need input of dimension 4 and input.size[1] == 2 but got input to be of shape: [2 x 1 x 6 x 6] at /.../torch/lib/THNN/generic/SpatialConvolutionMM.c:47
```

is this expected @albanD?

**Comment by albanD** [comment]
Hi,

This specific error is because the input is not the right size, you should use `chan_in*groups` for the size of `x` in the test, no?

I expect you get another error after fixing this as I did not checked the implementation for groups (my bad sorry).

**Comment by gchanan** [comment]
You are of course correct; here's a fixed version of the test: https://github.com/gchanan/pytorch/commit/c089cb52c10b45c6543095e7788770f30dbd82e8 which demonstrates the error.

I'll probably put an error message in the double backwards impl similar to how there is one for the transposed case so it's not surprising.
