### ISSUE TITLE
Serialization of tensors with pickle.dumps seems to be inconsistent, leading to inconsistent redis cache hit/miss

### ISSUE THREAD

**Issue by BonShillings** [pytorch/pytorch#19742]
## 🐛 Bug

Scenario: 

Redis cache set up 
call set pickle.dumps(tensor) some_value
call get pickle.dumps(tensor)
call get pickle.dumps(tensor) (different call)

hit on call 1,
potential miss on call 2 

These inconsistent hits/misses occur over O(1000) calls to the the same tensors in objects repeated ~9 times

## To Reproduce

Steps to reproduce the behavior: (skeleton)
0. import redis
0. import time
0. value = torch.tensor(...) 
0. start = time.time()
1. redis_cache = redis.StrictRedis(host="localhost", port=6379, db=0)  # redis_cache
2. redis_cache.set(pickle.dumps(value), pickle.dumps((hidden, cell)))
3. cache_return = redis_cache.get(pickle.dumps(value))
            if cache_return is not None:
                logger.info("Cache hit for {} took {} ms".format(value, time.time()-start))
                return pickle.loads(cache_return)
4. cache_return = redis_cache.get(pickle.dumps(value))
            if cache_return is not None:
                logger.info("Cache hit for {} took {} ms".format(value, time.time()-start))
                return pickle.loads(cache_return)

(Cache miss logging would happen after .set() is called)

Example Log

2019-04-25 14:04:00,344 ID_1 [INFO] cache_encoder: Cache hit for tensor([[ 2, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,  3]]) took 0.00019598007202148438 ms
2019-04-25 14:04:00,347 ID_1 [INFO] cache_encoder: Cache miss for tensor([[ 2, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,  3]]) took 0.001859426498413086 ms

The weird thing is the hit happened before the miss, so it looks like something is unreliable with the serialisation

2019-04-25 14:04:00,303 ID_1 [INFO] cache_encoder: Cache hit for tensor([[ 2, 12,  3]]) took 0.0001957416534423828 ms
2019-04-25 14:04:00,312 ID_1 [INFO] cache_encoder: Cache miss for tensor([[ 2, 12,  3]]) took 0.0018868446350097656 ms

## Expected behavior

Consistent cache hits for the same tensor after: set pickle.dumps() cache_return

## Environment

 - PyTorch Version (e.g., 1.0): 1.01
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip install
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 8
 - GPU models and configuration: GeForce GTX 1050
 - Any other relevant information: 

## Additional context

When using str(value) instead of pickle.dumps(value), the cache hits are consistent (however, for large tensors ... get injected into the str() output, so this ultimately fails). This makes me think the problem is in how pickle.dumps() serializes the tensors. I saw a similar issue: https://github.com/pytorch/pytorch/issues/9168 for changes (improving speed) along these lines (moving to byteIO).

Because of the related issue I thought I would post the issue here.

**Comment by fmassa** [comment]
Can you provide a minimum example that reproduces this behavior and that indicate that this is a PyTorch problem?

From your description, it might imply that `pickle.dumps(tensor)` is not always the same. But I couldn't reproduce this locally.

It could also be that the algorithm that Redis uses to cache large objects is not perfect and is subject to missing it a few times. Hard to say without a repro.

**Comment by soumith** [comment]
we spent some time (@fmassa did) trying to repro it, but couldn't. Hopefully you can carve out a smaller test case. If you end up doing so, please reopen the issue.

**Comment by barrh** [comment]
@soumith @BonShillings  I manage to reproduce this issue _consistently_ on my machine, with pytorch 1.3.1.

```
add11 = lambda: torch.Tensor([1]) + torch.Tensor([1])
add11() == add11()  # return tensor([True])
hash(add11()) == hash(add11())  # returns True
pickle.dumps(add11()) == pickle.dumps(add11())  # returns False
pickle.dumps(add11().data) == pickle.dumps(add11().data)  # returns False
pickle.dumps(torch.Tensor([1])) == pickle.dumps(torch.Tensor([1]))  # returns False
```
but: `pickle.dumps(torch.Tensor([1])) == pickle.dumps(torch.Tensor([1]).data)` is True.

Similarly, this issue reflects on Python's LRU cache.
Example code:
```
@functools.lru_cache(None)
def add(x, y):
 return x + y

for _ in range(10):
 tmp = add(torch.Tensor([1]), torch.Tensor([1]))
add.cache_info().hits  # returns 0
```
