### ISSUE TITLE
How to select cl.exe for a config of cpp_extension?

### ISSUE THREAD

**Issue by liuchanfeng165** [pytorch/pytorch#19744]
## ❓ Questions and Help
Hi, I got this error and dont wanna change vs15 again because  the compiler keeps in OS,if I use  cl.exe of VS2015 not VS2017 to compile my cpp_extension by  setup.py and how to modify setup.py
![image](https://user-images.githubusercontent.com/18642811/56752176-46bed400-67ba-11e9-8852-072930b90dde.png)
## setup.py
from setuptools import setup
import os
#import torch
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

_ext_src_root= ['E:/Program Files (x86)/Microsoft Visual Studio 14.0/VC'] #
cx_path= 'E:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64'
cc = os.environ.get('CC', cx_path+'/cl.exe')
cxx = os.environ.get('CXX', cx_path+'/cl.exe')
cl=os.environ.get('cl', cx_path+'/cl.exe')

print(cxx)
vs_bin= '%VS140COMNTOOLS%/../../VC/bin/amd64'
#nvcc sets --compiler-bindir for compiler ; -ccbin
setup(
    name='lltm_cuda',
    ext_modules=[
        CUDAExtension('lltm_cuda', [
            'lltm_cuda.cpp',
            'lltm_cuda_kernel.cu',
               ],
            # include_dirs=torch.utils.cpp_extension.include_paths(),
            extra_compile_args={'cxx': ['-g'],
                                'nvcc': ['-O2' , '--compiler-bindir' " {}".format(cx_path+'/cl.exe')]}
                      #extra_cflags
             # extra_compile_args ={
             #           "cxx": ["-O2", "-I{}".format("{}/include".format(_ext_src_root))],
             #          # "nvcc": ["-O2", "-I{}".format("{}/include".format(_ext_src_root))],
             #      "cl": ["-O2", "-I{}".format("{}/include".format(_ext_src_root))],
             #  },

              ),
    ],
    cmdclass={
        'build_ext': BuildExtension
    })
##  add list
just to compile ' .cu' not '.cpp ', mabe modify there or not?
line 240 in cpp_extension.py :+1: 
        # Register .cu and .cuh as valid source extensions.
        self.compiler.src_extensions += ['.cu', '.cuh']
        # Save the original _compile method for later.
        if self.compiler.compiler_type == 'msvc':
            self.compiler._cpp_extensions += ['.cu', '.cuh']
            original_compile = self.compiler.compile
            original_spawn = self.compiler.spawn
        else:
            original_compile = self.compiler._compile

## Thanks a lot

**Comment by fmassa** [comment]
Hi,

We use GitHub issues for bug reports and feature requests.

Questions are better suited for the forums https://discuss.pytorch.org/ . Can you post there instead?

Thanks!

**Comment by liuchanfeng165** [comment]
> Hi,
> 
> We use GitHub issues for bug reports and feature requests.
> 
> Questions are better suited for the forums https://discuss.pytorch.org/ . Can you post there instead?
> 
> Thanks!
that 's fine. I solved it.
