### ISSUE TITLE
NO building  and NO module

### ISSUE THREAD

**Issue by liuchanfeng165** [pytorch/pytorch#19757]
## 🐛 Bug
Hi, how to use jit.py to  build cpp&cu into module.No module in my dir built by ninja & cl.exe of vs2015 in win7-x64.

![image](https://user-images.githubusercontent.com/18642811/56759207-074cb380-67cb-11e9-952c-a6fcb0039056.png)
## jit.py : no any module  
from torch.utils.cpp_extension import load
import os 
#os.path.dirname(build_directory)
lltm_cuda = load(
    'lltm_cpp',
    ["lltm.cpp"],
    build_directory = 'G:\extension-ffi-master\script\extension-cpp-master\cpp',
    is_python_module= False,
    verbose=True) #True
help(lltm_cuda)
##

**Comment by fmassa** [comment]
Hi,

Your extensions are built and cached in `/tmp/torch_extensions`.

From your issue report, it's not clear if you have an error while compiling the extensions, could you clarify?

**Comment by fmassa** [comment]
Also, is this related to https://github.com/pytorch/pytorch/issues/19744 ?

**Comment by liuchanfeng165** [comment]
> Hi,
> 
> Your extensions are built and cached in `/tmp/torch_extensions`.
> 
> From your issue report, it's not clear if you have an error while compiling the extensions, could you clarify?

##
it is not  temporary cache, as follow
build_directory = 'G:\extension-ffi-master\script\extension-cpp-master\cpp',
about #19744  , I did  solve it .

**Comment by liuchanfeng165** [comment]
> Also, is this related to #19744 ?
##environment
CUDA9.2 ,VS2015;
CMD: 'python3 setup.py build_ext 'is fine
but 'python3 jit.py ' is not any module in my setting

**Comment by iremyux** [comment]
@liuchanfeng165 
If you are still experiencing the same problem, can you please clarify the issue? A screenshot of the failure, the command you are using etc. might be useful for us to try and reproduce.

**Comment by iremyux** [comment]
Closing this issue as it no longer seems relevant and remained inactive. Please feel free to open a new issue if you encounter any other problems or have any feature requests.
