### ISSUE TITLE
it seem that i can  only use  command in the pytorch-master folder, when i change the folder, i got AttributeError, anyone know why?

### ISSUE THREAD

**Issue by visonpon** [pytorch/pytorch#1977]
in pytorch-master folder:
>>>torch.nn.Conv2d(1,1,1,1)
Conv2d(1,1,,kernei_size=(1,1),stride=(1,1))

but when i use the same command in other folder:
>>>torch.nn.Conv2d(1,1,1,1)
i got an error like this:
```
raise AttributeErrot(name)
AttributeError : creator
```

**Comment by colesbury** [comment]
Please use the forums for support requests and GitHub issues only for bugs and feature requests

https://discuss.pytorch.org/
