### ISSUE TITLE
[Feature Request] LuaRocks style package manager for community made packages

### ISSUE THREAD

**Issue by ankghost0912** [pytorch/pytorch#1978]
Hi, 

I was wondering if there are any plans to have a luarocks style package manager for pytorch. I'm not talking about just installing stuff (which can be easily done via conda, pip) but a package manager specific to PyTorch, which can have community made packages (like Torch has for computer vision etc). 

Any thoughts?

**Comment by hughperkins** [comment]
[bystander comment] Isnt this what conda is for? What advantages do you see to using a proprietary package manager, instead of using conda?  Presumably we can do things like:

```
conda install pytorch-ankghost0912-cool-addon
```
?

**Comment by soumith** [comment]
We have no specific plans to do a separate package manager. Use conda, which allows community channels.
