### ISSUE TITLE
Could Pytorch C++ API load tensor from gpu memory directly?

### ISSUE THREAD

**Issue by xin-xinhanggao** [pytorch/pytorch#19786]
## ❓ Questions and Help
Sorry to post it here, I try to post it on Pytorch Forum but get no response.
I want to load OpenGL framebuffer object into pytorch C++ tensor.

In https://pytorch.org/cppdocs/notes/tensor_basics.html, I find that torch::from_blob can be used to view cuda memory as a tensor in Aten but seems can not work for me.

Could anyone can help, thanks!

**Comment by xsacha** [comment]
Example code that converts a cv::cuda::GpuMat of type 32F to a torch::Tensor:

```C++
    void deleter(void *arg){};
    torch::Tensor matToTensor(const cv::cuda::GpuMat &image)
    {
        std::vector<int64_t> dims = {image.rows, image.cols, image.channels()};
        long long step = image.step;
        std::vector<int64_t> strides = {step, image.channels(), 1};
        return torch::from_blob(image.data, dims, strides, deleter, torch::kCUDA)
    }
```

**Comment by fmassa** [comment]
Closing via @xsacha comments.

**Comment by zhangjinsong3** [comment]
@xsacha I tried your code, and it creates an torch::tensor successfully. But when i run code:
`tensor_image = tensor_image.to(torch::kCPU);`
I get the an SIGSEGV (Segmentation fault);

and I run code:
`input = tensor_image.clone()`
I got  Signal: SIGSEGV (Segmentation fault);

run code:
`torch::jit::Stack features = module->forward({tensor_image}).toTuple()->elements();`
I got 
`terminate called after throwing an instance of 'std::runtime_error'
  what():  
cuDNN error: CUDNN_STATUS_NOT_INITIALIZED (Handle at /pytorch/aten/src/ATen/cudnn/Handle.cpp:19)
Signal: SIGABRT (Aborted)`

all error above do not appear when I use cv::Mat and then upload to(torch::kCUDA).
Could you help me or provide an successful forward demo?

**Comment by panshaohua** [comment]
float* dev_output = NULL;
cudaMalloc((void**)&dev_output, sizeof(float) * N * C * H * W);
at::Tensor output = torch::from_blob(dev_output, {N, C, H, W}, 
 at::TensorOptions(at::DeviceType::CUDA));

**Comment by omaralvarez** [comment]
Was anyone able to do this properly? Is this issue dead?

**Comment by xsacha** [comment]
@omaralvarez The code I supplied works properly and I use it in a production product.
The poster above has an unrelated issue (CUDA not initialised).

**Comment by omaralvarez** [comment]
@xsacha Thanks for the quick answer. Got it, I will try the code out.

**Comment by oelgendy** [comment]
What about reading from a Halide::Runtime::Buffer allocated on GPU memory? I want to read a 2D float32 buffer stored on GPU, so I wrote the following code
``
std::vector<int64_t> dims = {height, width};
std::vector<int64_t> strides = {Buffer.stride(0), Buffer.stride(1) };
auto options = torch::TensorOptions().dtype(torch::kFloat).device(torch::kCUDA);
Tensor = torch::from_blob(Buffer.data(), dims, strides, deleter, options);
``
I get an error at this line of code in Functions.h
``auto options = torch::TensorOptions().dtype(torch::kFloat).device(torch::kCUDA);``

It worksI if I remove device(torch::kCUDA) from options, but I get rubbish data
