### ISSUE TITLE
`Functional` is missing `Embedding`

### ISSUE THREAD

**Issue by hughperkins** [pytorch/pytorch#1979]

**Comment by hughperkins** [comment]
Dabbled in adding this, got as far as:

```
def embedding(input, weight, padding_idx=None,
                 max_norm=None, norm_type=2, scale_grad_by_freq=False,
                 sparse=False):
    assert not sparse, 'sparse not supported in functional embedding for now'
    assert padding_idx is None, 'non-None padding_idx not supported in functional embedding currently'
    if padding_idx is None:
        padding_idx = -1
    return self._backend.Embedding(
        padding_idx, self.max_norm, self.norm_type,
        self.scale_grad_by_freq, self.sparse
    )(input, weight)
```

... but not sure what to put in place of `self._backend.Embedding`?  Presumably this is some property of `Module`?  Hypothesized that tensors might have this property, but seems not:

```
In [12]: a._backend
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-03d251838549> in <module>()
----> 1 a._backend

AttributeError: 'torch.FloatTensor' object has no attribute '_backend'
```

**Comment by hughperkins** [comment]
Seems like functional convolution simply instantiates a functor behind hte scenes:

```
    f = ConvNd(_pair(stride), _pair(padding), _pair(dilation), False,
               _pair(0), groups, torch.backends.cudnn.benchmark, torch.backends.cudnn.enabled)
    return f(input, weight, bias)
```
Wont this end up instantiating a second copy of the weights?  Or does `Parameter` lazily initialize? :
```
            self.weight = Parameter(torch.Tensor(
                out_channels, in_channels // groups, *kernel_size))
```

**Comment by albanD** [comment]
The `ConvNd` that is used here is an `autograd.Function` not an `nn.Module` (this is not the `_ConvNd` from nn/modules/conv.py` but a function declared from cpp), it does not have a state nor knows about `nn.Parameter`.
The `weight`s are given at the same time as the `input` when performing the computation.

In your previous question, the backend (cpp library) that contains the embedding layer is `thnn`, you can find it in `torch.nn.backends.thnn.backend` where you can access the `autograd.Function` called `Embedding` thus replacing `self._backend.Embedding` with `nn.backends.thnn.backend.Embedding`.

**Comment by hughperkins** [comment]
> the backend (cpp library) that contains the embedding layer is thnn, you can find it in torch.nn.backends.thnn.backend where you can access the autograd.Function called Embedding thus replacing self._backend.Embedding with nn.backends.thnn.backend.Embedding.

Awesome, thanks! Question: what happens if the incoming tensors are cuda tensors? will this continue to work ok?

**Comment by albanD** [comment]
yes

**Comment by hughperkins** [comment]
Cool, thanks! :-)

**Comment by soumith** [comment]
added in https://github.com/pytorch/pytorch/pull/1987
