### ISSUE TITLE
Support ceil mode in mkldnn {max,avg}_pool

### ISSUE THREAD

**Issue by bddppq** [pytorch/pytorch#19796]
## 🚀 Feature

Support ceil mode in mkldnn {max,avg}_pool

## Additional context

https://github.com/pytorch/pytorch/pull/19205#discussion_r276903751

**Comment by jingxu10** [comment]
Hi,
This feature had been implemented.
Reference ticket: https://github.com/pytorch/pytorch/pull/21310
