### ISSUE TITLE
Add mkldnn support for adaptive avg pool

### ISSUE THREAD

**Issue by bddppq** [pytorch/pytorch#19797]
## 🚀 Feature
Add mkldnn support for adaptive avg pool

**Comment by mingfeima** [comment]
@bddppq what is the workaround at the moment? Adding `to_dense()` before adaptive_avg_pool2d and `to _mkldnn()` after?

**Comment by bddppq** [comment]
@mingfeima Either do what you said, or change to use AvgPool2d. But I should be able to get #19818 into master soon (waiting for review).
