### ISSUE TITLE
[Caffe2] Compile error: onnxTensorDescriptorV1 has no member named quantizationParams

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#19798]
## Bug

PR #19792 merged recently (about half hour ago) breaks the build:

![image](https://user-images.githubusercontent.com/5203025/56784005-5252d080-67a3-11e9-8238-067490f29667.png)

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake + ninja + gcc-8
 - Python version: 3.6

**Comment by zrphercule** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/19793

**Comment by xkszltl** [comment]
Thanks for the quick response and have a good night!

**Comment by zrphercule** [comment]
Closed by landing target diff

**Comment by xkszltl** [comment]
Verified.
