### ISSUE TITLE
Create Extension Error: Pytorch 0.4.0

### ISSUE THREAD

**Issue by cancam** [pytorch/pytorch#19807]
Hi everyone,

I am trying to user FFI extensions in order to add some CUDA compiled functions. The error I encountered is as follows;

cffi.CDefError: cannot parse "#include <THC/THC.h>"
<cdef source string>:29:1: Directives not supported yet

My environmental configuration is as follows;

Cuda Compilation Tool Version: 9.0, v9.0.176
pycparser version 2.18
PyTorch Version: 0.4.0

Could you please provide assitance about this issue?
Thanks.

**Comment by soumith** [comment]
FFI extensions are removed as of 1.0 release.
in 0.4, the cffi header parser cannot parse macros. You can look at https://github.com/pytorch/extension-ffi

if you have questions, use https://discuss.pytorch.org
