### ISSUE TITLE
Help:  error C3861: “THLongTensor_copyCuda”  #no found

### ISSUE THREAD

**Issue by liuchanfeng165** [pytorch/pytorch#19800]
## ❓ Questions and Help
if torch0.4.0 ,that's ok. and this function is repalced by another one ,which one?
thanks, I cannot find it in   THC  dir.

**Comment by fmassa** [comment]
The copy functions are now in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Copy.cpp , and the CUDA part in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/Copy.cu

**Comment by liuchanfeng165** [comment]
> The copy functions are now in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Copy.cpp , and the CUDA part in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/Copy.cu

## Thanks

**Comment by liuchanfeng165** [comment]
Hi,@fmassa
however,I cannot achive my goal ,see ATen dir:
![image](https://user-images.githubusercontent.com/18642811/56798100-bd0a1780-6848-11e9-8b68-02102be62790.png)
I tried to use function of  copy_from_cpu but failure and others  .for example 'THTensor_copyCuda(state, mask_cpu, mask) ,  THLongTensor_copyCudaLong(state, mask_cpu, mask), THCStorage_copyCudaLong(state, mask_cpu, mask)' dont work together and they are  also  error when compiled.

**Comment by fmassa** [comment]
Check `libtorch.so` in `lib`

```python
nm  libtorch.dylib | grep copy
```

gives, among other things (for my oldish version of PyTorch)
```
000000000078d260 T __ZNK5torch8autograd12VariableType10index_copyERKN2at6TensorExS5_S5_
000000000078d630 T __ZNK5torch8autograd12VariableType11index_copy_ERN2at6TensorExRKS3_S6_
000000000065f5b0 T __ZNK5torch8autograd12VariableType11narrow_copyERKN2at6TensorExxx
000000000081af70 T __ZNK5torch8autograd12VariableType12_s_copy_fromERKN2at6TensorES5_b
00000000006e7690 T __ZNK5torch8autograd12VariableType15_th_index_copy_ERN2at6TensorExRKS3_S6_
00000000000ffe60 T __ZNK5torch8autograd12VariableType16_copy_same_type_ERN2at6TensorERKS3_
00000000006133d0 T __ZNK5torch8autograd12VariableType22copy_sparse_to_sparse_ERN2at6TensorERKS3_b
0000000000127690 T __ZNK5torch8autograd12VariableType27_th_copy_ignoring_overlaps_ERN2at6TensorERKS3_
0000000000819e70 T __ZNK5torch8autograd12VariableType7s_copy_ERN2at6TensorERKS3_b
```

Why are you trying to dispatch to the low-level functions, instead of just `copy_`?

**Comment by liuchanfeng165** [comment]
> Why are you trying to dispatch to the low-level functions, instead of just `copy_`?
## 
Thanks a lot. I always  apply functions in some packes by reading their header files thats why i did that , which is simple to apply functions.

**Comment by fmassa** [comment]
The packages that you are trying to use are for an old version of PyTorch, and do not work anymore with PyTorch 1.0+

**Comment by liuchanfeng165** [comment]
> The packages that you are trying to use are for an old version of PyTorch, and do not work anymore with PyTorch 1.0+
## 
Thanks for u kind response.And could u tell me about how to  use 'copy_cuda' to replace  
THLongTensor_copyCuda with torch1.0.1 if the situation as follow:
## code
  THCState *state;
  THCudaLongTensor * mask = THCudaLongTensor_newWithSize2d(state, boxes_num, col_blocks);
  THLongTensor * mask_cpu = THLongTensor_newWithSize2d(boxes_num, col_blocks);
## to replace  '  THCudaLongTensor_freeCopyTo(state, mask_cpu, mask); '
## Thanks

**Comment by fmassa** [comment]
You'll basically need to change the whole code base, using the ATen tensors instead of THTensor.

Also, those questions are better suited for the discussion forums discuss.pytorch.org

**Comment by liuchanfeng165** [comment]
> You'll basically need to change the whole code base, using the ATen tensors instead of THTensor.
> 
> Also, those questions are better suited for the discussion forums discuss.pytorch.org

ok,thanks
