### ISSUE TITLE
Pytorch pre-compiled release files - Windows Error

### ISSUE THREAD

**Issue by pedromorais17** [pytorch/pytorch#19801]
I'm trying to follow the step 3 of the following pytorch instruction page: https://pytorch.org/tutorials/advanced/cpp_export.html. 

Basically, I created the described example-app.cpp, and then the CMakeLists.txt. 
I'm using pytorch, with CUDA 9.0 in Windows 10. 

While creating the project with the CMake, I'm receiving the following error message. 

CMake Error at C:/Code/ExternalLibraries/libtorch_cuda9/libtorch/share/cmake/Caffe2/public/cuda.cmake:380 (message):
  Unknown cmake build type:

Any suggestion?

**Comment by peterjc123** [comment]
Please add argument when calling cmake `-DCMAKE_BUILD_TYPE=Release`.

**Comment by pedromorais17** [comment]
Hi Pieter,

I'm using CMAKE gui. I'm not sure how to set this option in CMAKE GUI. I tried to use CMAKE.exe, with the following command: cmake.exe -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_GENERATOR="Visual Studio 15 2017 Win64" ..

and I'm receiving the following error message:

detect_cuda_version.obj: fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'

I'm not understanding the problem. Can you help me?

Thank you in advance.

**Comment by peterjc123** [comment]
you need to clean the build cache and try again. If you select Cmake GUI, then remember to select the right generator.

**Comment by xsacha** [comment]
```
set(CMAKE_BUILD_TYPE Release)
find_package(Torch)
```

Or do what I would and download both the Debug and Release torch prebuilt and modify the CMake script to choose the right one. I should probably fix that in a PR.

**Comment by pedromorais17** [comment]
Thank you all. @xsacha: How can I get the debug prebuilt files? For Release it works, but I'm missing the debug options.

**Comment by peterjc123** [comment]
https://pytorch.org/ Select Nightly, Windows, LibTorch, C++ and your CUDA version and then you can see the link to the debug version of LibTorch.

**Comment by xsacha** [comment]
I have found that you can just paste the DLLs and PDBs in to your release folder to debug crashes.
That is, you do not actually need to build it again.

**Comment by pedromorais17** [comment]
Looking to https://pytorch.org/tutorials/advanced/cpp_export.html, it is mentioned that: "On Windows, debug and release builds are not ABI-compatible. If you plan to build your project in debug mode, we recommend building PyTorch from source.".

I download the file from https://pytorch.org (as suggested by @peterjc123) and I'm not seeing any .pdb file. I think that these files were compiled only for release.

**Comment by peterjc123** [comment]
@pedromorais17  They are under the `lib` directory.

**Comment by pedromorais17** [comment]
![pytorch](https://user-images.githubusercontent.com/44382268/56907152-95f75400-6a9b-11e9-85bf-913c24301fff.PNG)

@peterjc123 Please see my lib directory. No .pdf files. 

Thank you in advance.

**Comment by peterjc123** [comment]
Is this the precompiled binary for release? The release one doesn't contain debug symbols, only the debug one includes them.

**Comment by xsacha** [comment]
They were there when I downloaded the prebuilt libtorch Debug version.

**Comment by pedromorais17** [comment]
Looking to the pytorch web page, they mentioned that: "On Windows, debug and release builds are not ABI-compatible. If you plan to build your project in debug mode, we recommend building PyTorch from source."

I'm trying to compile it from the source but I'm having several errors while during the cmake.

Have you tried to compile it from the source?

**Comment by xsacha** [comment]
If building from source, use -DCMAKE_BUILD_TYPE=Debug

**Comment by pedromorais17** [comment]
I will try and then send you my feedback. 
Thank you for all your support.

**Comment by pedromorais17** [comment]
The pytorch webpage has now the Release and Debug pre-compiled files. Thank you for all your support.
