### ISSUE TITLE
[Controversial] `pyyaml` is 6 years old, might be best to switch to `ruamel.yaml`?

### ISSUE THREAD

**Issue by hughperkins** [pytorch/pytorch#1981]
Commit history from pyyaml, as far as I can tell, http://pyyaml.org/log/ 

<img width="733" alt="screen shot 2017-07-05 at 10 34 54 am" src="https://user-images.githubusercontent.com/123560/27858562-9e33dc44-616d-11e7-9525-0cf771d24b31.png">

Commit history from `ruamel.yaml`, https://bitbucket.org/ruamel/yaml/commits/all

<img width="1355" alt="screen shot 2017-07-05 at 10 35 36 am" src="https://user-images.githubusercontent.com/123560/27858592-bd36de8e-616d-11e7-8213-548f81909bd2.png">

ruamel.yaml supports yaml 1.2, and handles round-trip, including comments.

**Comment by soumith** [comment]
it's one of those things where if there's a super smooth transition, then why not...

Have you tried `ruamel.yaml` as a drop-in replacement?

**Comment by pavanky** [comment]
PyYAML has had it's last commit made in February this year: https://github.com/yaml/pyyaml

**Comment by hughperkins** [comment]
> PyYAML has had it's last commit made in February this year: https://github.com/yaml/pyyaml

Fair enough :-)

Coupled with

> Have you tried ruamel.yaml as a drop-in replacement?

Yes... but only with `pip`. With `conda`, I've also tried, but seems to be packaged into a different namespace.

=> I think I'll close this for now.
