### ISSUE TITLE
 How to use torch.tensor(n)  in Python3 to adapt to ’ at::TensorImpl‘  

### ISSUE THREAD

**Issue by liuchanfeng165** [pytorch/pytorch#19822]
## ❓ Questions and Help
Hi ,when nms_cpp compiled  by cpp_extension ,it didnt work  but work in pytorch0.4.0.: 

 
## TypeError: gpu_nms(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::TensorImpl, arg1: at::TensorImpl, arg2: at::TensorImpl, arg3:
float) -> int
## Invoked with: 
tensor([ 2.5353e+09,  2.5238e+09, -4.5295e+18,  ...,  4.7854e+18,
         4.7424e+18,  4.7895e+18]), tensor([ 566]), 
tensor([[ 146.1686,  111.1691,  242.2774,  288.5695,    0.8267],
        [ 144.7030,  108.2768,  244.0824,  282.2564,    0.8234],
        [ 144.5566,  110.4112,  243.3897,  283.4086,    0.8225],
        ...,
        [ 100.9274,   81.2732,  155.0707,  130.5494,    0.0500],
        [   0.0000,  185.7541,   47.3124,  276.2884,    0.0500],
        [   4.5178,   57.4754,   37.1159,  115.0753,    0.0500]], device='cuda:0
'), // 
0.5
## Code
// ------------------------------------------------------------------
// Faster R-CNN
// Copyright (c) 2015 Microsoft
// Licensed under The MIT License [see fast-rcnn/LICENSE for details]
// Written by Shaoqing Ren
// ------------------------------------------------------------------
#include <torch/script.h>
#include<torch/serialize/tensor.h>
#include <THC/THC.h>
#include <ATen/ATen.h>//state
#include <TH/TH.h>
#include <THC/THCTensorCopy.h>
//#include <TH/generic/THTensorCopy.h>
#include <THC/generic/THCTensorCopy.h>//generic/THCTensorCopy.h
#include <THC/THCTensorCopy.hpp>
#include <math.h>
#include <stdio.h>

#include <cstddef>

#include <torch/torch.h>
#include <torch/script.h>

#include "cuda/nms_kernel2.h"
#include "nms.h"

//src/nms_cuda.cpp(27): error C2440: “初始化”: 无法从“
//std::unique_ptr<THCState,void (__cdecl *)(THCState *)>
//THCState *state = at::globalContext().thc_state;
//std::unique_ptr<THCState,void (__cdecl *)(THCState *)> state= at::globalContext().thc_state;
	
 THCState *state;

int gpu_nms(THLongTensor * keep, THLongTensor* num_out, THCudaTensor * boxes, float nms_overlap_thresh) {
  // boxes has to be sorted
  THArgCheck(THLongTensor_isContiguous(keep), 0, "boxes must be contiguous");
  THArgCheck(THCudaTensor_isContiguous(state, boxes), 2, "boxes must be contiguous");
 
  // Number of ROIs
  int64_t boxes_num = THCudaTensor_size(state, boxes, 0);
  int64_t boxes_dim = THCudaTensor_size(state, boxes, 1);

  float* boxes_flat = THCudaTensor_data(state, boxes);

  const int64_t col_blocks = DIVUP(boxes_num, threadsPerBlock);
  printf("100,%d,%d ,%d ,%d "  , *state,boxes_num, boxes_dim, col_blocks);
  //, *state
  THCudaLongTensor * mask = THCudaLongTensor_newWithSize2d(state, boxes_num, col_blocks);
//#unsigned
  unsigned long long* mask_flat = (unsigned long long* )THCudaLongTensor_data(state, mask);

//_mns from 
  _nms(boxes_num, boxes_flat, mask_flat, nms_overlap_thresh);

  THLongTensor * mask_cpu = THLongTensor_newWithSize2d(boxes_num, col_blocks);
  //THCudaTensor_copyFloat
  //THLongTensor_copyCuda(state, mask_cpu, mask); #no found
  //THCTensor_(copyAsyncCPU)
  //THTensor_copyCuda(state, mask_cpu, mask);
  //THLongTensor_copyCudaLong(state, mask_cpu, mask);
  //not found   cu file
  //THCStorage_copyCudaLong(state, mask_cpu, mask);#
  //THCTensor_copy(state, mask_cpu, mask);
  //THCudaTensor_copyLong(state, mask_cpu, mask); 
  
  //THLongTensor_copyCudaLong(state, mask_cpu, mask);
  //copy_from_cpu(state, mask_cpu, mask);
  //ok mask 2 mask_cpu 
  //
  THCudaLongTensor_freeCopyTo(state, mask_cpu, mask);  
  //Copy_Long(state, mask_cpu, mask);  
  //copyAsyncCuda 
  //THTensor_copyLong(state, mask_cpu, mask);
  
  THCudaLongTensor_free(state, mask);
  
//unsigned
   long long * mask_cpu_flat = THLongTensor_data(mask_cpu);

  THLongTensor * remv_cpu = THLongTensor_newWithSize1d(col_blocks);
  //unsigned
   long long* remv_cpu_flat = THLongTensor_data(remv_cpu);
  THLongTensor_fill(remv_cpu, 0);

  int64_t * keep_flat = THLongTensor_data(keep);
  long num_to_keep = 0;

  int i, j;
  for (i = 0; i < boxes_num; i++) {
    int nblock = i / threadsPerBlock;
    int inblock = i % threadsPerBlock;

    if (!(remv_cpu_flat[nblock] & (1ULL << inblock))) {
      keep_flat[num_to_keep++] = i;
       long long *p = &mask_cpu_flat[0] + i * col_blocks;
      for (j = nblock; j < col_blocks; j++) {
        remv_cpu_flat[j] |= p[j];
      }
    }
  }

  int64_t * num_out_flat = THLongTensor_data(num_out);
  * num_out_flat = num_to_keep;

  THLongTensor_free(mask_cpu);
  THLongTensor_free(remv_cpu);

  
  //return 1; 
  return num_to_keep;
}
PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("cpu_nms", &cpu_nms, "nms cpu_nms ");

  m.def("gpu_nms", &gpu_nms, "nms gpu_nms (CUDA)");

}

**Comment by fmassa** [comment]
You are using a code base that was written for pytorch < 1.0.
You should either downgrade PyTorch or update the library to use the new cpp extensions

**Comment by liuchanfeng165** [comment]
> You are using a code base that was written for pytorch < 1.0.
> You should either downgrade PyTorch or update the library to use the new cpp extensions

##
I got it.I also used the new version , and modified it by new grammer and the procedure was   pass , howerver when ran ,it did cause type error that 'at:: tensorImpl' is incompatible with input args that ‘’tensor‘’in python code. I try to sovle it,but it cost all day ,as to push  it  into here..........
Now, I wanna know  typr of the API in cpp ,find exmaples of  torch1.0.1  that no any satisfy thing。。。
help， pls

**Comment by liuchanfeng165** [comment]
> > You are using a code base that was written for pytorch < 1.0.
> > You should either downgrade PyTorch or update the library to use the new cpp extensions
> 
> I got it.I also used the new version , and modified it by new grammer and the procedure was pass , howerver when ran ,it did cause type error that 'at:: tensorImpl' is incompatible with input args that ‘’tensor‘’in python code. I try to sovle it,but it cost all day ,as to push it into here..........
> Now, I wanna know type of the API in cpp ,find exmaples of torch1.0.1 that no any satisfy thing。。。
> help， pls
> 
> ## to modify :
> int gpu_nms(THLongTensor * keep, THLongTensor* num_out, THCudaTensor * boxes, float nms_overlap_thresh) {
> or give me some idea in torch examples
## I gotttt ittttt！！！
https://github.com/Kolkir/mlcpp/blob/master/mask_rcnn_pytorch/nms/nms_cuda.cpp

**Comment by fmassa** [comment]
Btw, you should probably check https://github.com/facebookresearch/maskrcnn-benchmark
There is an implementation of NMS for PyTorch 1.0 there

**Comment by liuchanfeng165** [comment]
> Btw, you should probably check https://github.com/facebookresearch/maskrcnn-benchmark
> There is an implementation of NMS for PyTorch 1.0 there
## great  @fmassa 
And modified it completely,  I foud this error even to  add the line of  "library_dirs= ['torch', 'ATen','_C','cudart']" . 
nms_cuda.obj : error LNK2001: 无法解析的外部符号 "public: unsigned __int64 * __c
decl at::Tensor::data<unsigned __int64>(void)const " (??$data@_K@Tensor@at@@QEBA
PEA_KXZ)
build\lib.win-amd64-3.6\_ext\nms.cp36-win_amd64.pyd : fatal error LNK1120: 1 个
I saw the code about 
![image](https://user-images.githubusercontent.com/18642811/56857483-c27a7580-69a0-11e9-9158-e15e1f429f05.png)

that  as a type template  contects in class Tensor .

I guess it  is containend in  'ATlen.lib' but failure  ,help...

**Comment by liuchanfeng165** [comment]
> > Btw, you should probably check https://github.com/facebookresearch/maskrcnn-benchmark
> > There is an implementation of NMS for PyTorch 1.0 there
> 
> ## great @fmassa
> And modified it completely, I foud this error even to add the line of "library_dirs= ['torch', 'ATen','_C','cudart']" into code build.py .
> 
> nms_cuda.obj : error LNK2001: 无法解析的外部符号 "public: unsigned __int64 * __c
> decl at::Tensor::data(void)const " (??$data@_K@Tensor@at@@qeba
> PEA_KXZ)
> build\lib.win-amd64-3.6_ext\nms.cp36-win_amd64.pyd : fatal error LNK1120: 1 个
> 
> I saw the code about
> ![image](https://user-images.githubusercontent.com/18642811/56857483-c27a7580-69a0-11e9-9158-e15e1f429f05.png)
> 
> that as a type template in Tensor .
> 
> ## code
> at::Tensor mask = at::empty({boxes_num}, boxes.options().dtype(at::kLong).device(at::kCPU));
> // unsigned long long* mask_flat = (unsigned long long* )THCudaLongTensor_data(state, mask);
> unt64_t* mask_flat = mask.data<unt64_t>();
> 
> I guess it is containend in 'ATlen.lib' but failure ,help...

## it  has been resolved
DONE:
unt64_t* mask_flat = (unt64_t*)mask.data<int64_t>();
