### ISSUE TITLE
Random GPU Operations Hang

### ISSUE THREAD

**Issue by Queuecumber** [pytorch/pytorch#19827]
## 🐛 Bug

I'm having an issue where certain GPU operations hang. It doesn't appear to be a multi-GPU problem, I can reproduce it on a single GPU. It doesn't seem to reliably effect the same operations but if I change around their order or cache certain results on the GPU to minimize copies it could cause the hang to move to another command. 

## To Reproduce

For my current code I can reproduce the problem fairly reliably with the following command:

```
horizontal_block_difference = ((im[:, :, :, block_horizontal_positions] - im[:, :, :, block_horizontal_positions + 1])**2).sum(3).sum(2).sum(1)
vertical_block_difference = ((im[:, :, block_vertical_positions, :] - im[:, :, block_vertical_positions + 1, :])**2).sum(3).sum(2).sum(1)
```

e.g. indexing the tensor `im` which is stored on GPU. I should point out that I was seeing this on other commands, usually copying something onto the GPU, but as I mentioned after changing how i was using the GPU by caching certain results to limit copies and reordering things, it is happening on this line. 

Here is the time taken by this command for several different images:

```
0 0.0010721683502197266
0 0.0008690357208251953

0 37.040807008743286
0 0.0005404949188232422

0 37.13724493980408
0 0.0004165172576904297

0 27.397161722183228
0 0.0003788471221923828

0 37.17257356643677
0 0.00034737586975097656

0 37.201823234558105
0 0.0002465248107910156
```

Here's what the above numbers mean. The first `0` is telling me which line is printing, so it can be ignored. The next number is how long it took to execute the offending line in seconds. The images are all of comparable size. Newline separates each image.

So you can see the first image executes both lines without problem. The next one, only the first line is slow and it takes over 30s to execute. This trend continues for the rest of the images.

## Environment

```
PyTorch version: 1.0.1.post2
Is debug build: No             
CUDA used to build PyTorch: 9.0.176

OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
GCC version: (GCC) 6.3.0
CMake version: version 2.8.12.2

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Quadro P6000
GPU 1: Quadro P6000
GPU 2: Quadro P6000
GPU 3: Quadro P6000

Nvidia driver version: 410.93
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.0.1.post2
[pip3] torchjpeg==0.0.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

```

## Additional context

My first thought was that this is something to do with garbage collection on the GPU, or something to do with the multi GPU IOMMU problem other people have had, but I'm not so sure anymore, especially since I can reproduce on a single GPU.

**Comment by fmassa** [comment]
Can you provide a minimal example that enables us to reproduce the problem? The snippet that you shared doesn't contain enough information for us to investigate.

**Comment by Queuecumber** [comment]
Sorry I meant to update this yesterday. I was getting hit with

https://github.com/pytorch/pytorch/issues/15054#

along with lazy evaluation, e.g. the tensor was not evaluated until it was needed (the indexing operation in my example) and at that point cudnn was screwing up. So this isnt a new issue.
