### ISSUE TITLE
improve user experience for selecting CUDA

### ISSUE THREAD

**Issue by makeyourownalgorithmicart** [pytorch/pytorch#19829]
**Problem**
The official documentation and example, as well as the many tutorials and Q&As across the web don't paint a clear picture for how to use CUDA.

The current instructions are also too complex.

.

**Rationale**
Going back to the disciple of user needs -> design, we note that:

- users want to write the same code for use on CUDA and CPU, to the greatest extent possible
- the difference, logically, is a boolean switch: yes or not to CUDA

The requirement for one, or many, or all of the following:

- setting default tensor type to cuda
- using model.to(device)
- explicitly requiring .cpu
- some aspects of pytorch failing in CUDA mode, eg DataLoader, needing a bifurcation of code
- more?

.. is far more complex than the logical decision of yes/no to CUDA. 

.

**Recommendation**
I recommend we simplify the user experience so that:

- the same code works on both GPU and CPU, when the code is correct and follows standard patterns
- there is only one switch for choosing a preference for CUDA over CPU
- there is a simple optional query to confirm which mode has been selected

.

**API Suggestion**
To choose preference for CUDA:

```
torch.options(device='cuda')
```

To confirm which mode is enabled:

```
torch.options(device)
> device = 'cpu'
## (which means GPU selection failed)
```

**Comment by SsnL** [comment]
Using a singe device object, the recommended way in official docs, satisfies all your three needs.

**Comment by fmassa** [comment]
As @SsnL pointed out, having a single `torch.device` is the recommended way, and having device-agnostic code is very straightforward.

**Comment by soumith** [comment]
The reason we dont want to do a "global" mode is because it has side-effects on the user's mental model. GPU memory isn't free, but people do construct Tensors often as if they are from a free memory pool, which is what CPU memory feels like.
A single `torch.device` that if you want, you can set as a global and reference in your code internals -- is the way to go.

**Comment by makeyourownalgorithmicart** [comment]
thanks - @SsnL  could you point me to this documentation? I can't seem to find it.

it would be good if there was an official recommended mental model and usage pattern

I'm not being lazy - I just can't find it!

**Comment by SsnL** [comment]
@makeyourownalgorithmicart In the docs it is indeed a bit hidden at https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code . It is used and recommended (I believe) throughout all of the tutorials https://pytorch.org/tutorials/ . We'd happily accept a PR to make the doc section more evident (and ideally modernizing the section on `torch.cuda.device`)!
