### ISSUE TITLE
Some question about the difference between nn.conv2d and conv layer in caffe

### ISSUE THREAD

**Issue by gittigxuy** [pytorch/pytorch#19834]
I wonder to know the difference between nn.conv2d in pytorch and conv layer in caffe.
I think there are 2 differences between them
1) the padding,nn.conv2d mend around,however the conv layer in caffe mend the left-top
2) the stride,when I convert pytorch model to caffemodel,if the stride is not one,I think I should convert stride=2 to stride=1 +maxpooling.
Am I right?what else did I miss.
Furthermore,how could I do about padding in nn.conv2d

Thanks

**Comment by soumith** [comment]
caffe2 uses the same scheme as pytorch. For Caffe1, your differences dont sound right, it has padding all around as well.
If you have questions, ask in https://discuss.pytorch.org
