### ISSUE TITLE
What conda version does the Getting Started webpage assume I have?

### ISSUE THREAD

**Issue by danilogr** [pytorch/pytorch#19839]
## 📚 Documentation

Hello, I cannot install `pytorch` using the command line provided at https://pytorch.org/get-started/locally/. 

Invoking `conda install pytorch torchvision cudatoolkit=10.0 -c pytorch` gives me a Package not found error.

It could be that my conda version is not the latest available on the website. In fact, I am using an older version (https://repo.continuum.io/archive/Anaconda3-4.3.1-Windows-x86_64.exe).

It would be great if the aforementioned get-started page could tell us what version of conda to use.  I ended up installing `py-torch` using pip.

**Comment by peterjc123** [comment]
Actually, the version of conda doesn't have to exactly match the one that is used during build. The reason that package could not be found is that your conda is just too old. Just try `conda update conda` and then it will be fine.

**Comment by danilogr** [comment]
What a silly mistake from my side. It worked after updating! Thanks!
