### ISSUE TITLE
torch.sqrt() doesnt work on result of full reduction operations.

### ISSUE THREAD

**Issue by hughperkins** [pytorch/pytorch#1985]
torch.sqrt() doesnt work on result of full reduction operations:

Currently:
```
a = torch.rand(3, 2)
print(torch.sqrt(a.sum()))  # Fails
print(sqrt(a.sum()))  # Fails
```
Neither `torch.sqrt` work, nor `sqrt`.  We could do `import math`, and use `math.sqrt`, but it's an additional import. Probably could use `np.sqrt` too, but again, additional import.  Additional cognitive load "is this a torch.Tensor, or a scalar".

**Comment by hughperkins** [comment]
Note that fixing full reduction returning hostside scalars, https://github.com/pytorch/pytorch/issues/1989, would also fix this issue.

**Comment by apaszke** [comment]
Yeah I guess it's going to be solved by our custom scalar types.
