### ISSUE TITLE
Feature request: 3D Adaptive Pooling

### ISSUE THREAD

**Issue by lsqshr** [pytorch/pytorch#1988]
The adpative pooling for 1d and 2d has been implemented. However for object detection in 3D images, e.g. medical images, the 3D version of adaptive pooling is not yet available in pytorch. 

Do you guys think it makes sense to extend the adaptive pooling to 3D?

**Comment by apaszke** [comment]
Yes, we just didn't have time to implement it

**Comment by soumith** [comment]
fixed via #2782 and #2728 by @SsnL
