### ISSUE TITLE
the speed of dataloading imfected by the number of Samples

### ISSUE THREAD

**Issue by Athenaplot** [pytorch/pytorch#19906]
I am  traped in the speed of the dataloading. In my experiment , I have 700k Samples ，one file for one sample. so I rewrite the Dataset and use the Dataloader of pytorch. But, the speed is much much slow. the batch_size is 128, the input image is of 80*80. while I reduce the number of my samples,like just 10k,it turns out to be much faster. so ,I want to figure out what limit the speed of the dataloding. what can I do to speed up my experiment except set the num_workers. begging your help
![图片](https://user-images.githubusercontent.com/31769682/56877886-a8659380-6a83-11e9-92ca-e0f29c450661.png)

![图片](https://user-images.githubusercontent.com/31769682/56877915-e793e480-6a83-11e9-9d36-b1e92f1c0a86.png)

**Comment by Athenaplot** [comment]
i think maybe i have an io bottleneck

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
