### ISSUE TITLE
batches_outstanding=0, so the program quit

### ISSUE THREAD

**Issue by ABigPing** [pytorch/pytorch#19907]
I use pytorch 0.3.0
When I use DataLoader with num_workers==4, the program exits after training hundreds of batches.
I checked the source code and found that batches_outstanding was reduced to 0.
Why does this happen? How should I solve this problem?

**Comment by fmassa** [comment]
It seems that you only trained for an epoch, and training has finished running on this single epoch.

Also, we use GitHub issues for tracking bugs and feature requests, questions are better suited for the forums https://discuss.pytorch.org/
