### ISSUE TITLE
Strange behavior of torch.multinomial on cuda.HalfTensor

### ISSUE THREAD

**Issue by bombs-kim** [pytorch/pytorch#19900]
## 🐛 Bug

`torch.multinomal` raises RuntimeError: CUDA error: misaligned address on certain conditions.

## To Reproduce
Just run this code in your python repl
```
import torch
# n can be any odd number
t = torch.tensor([[1.0/n]*n]).half().cuda()
torch.multinomial(t, 1, True)

# RuntimeError: CUDA error: misaligned address
```
If n is a even number, the above code doesn't raise an error!

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.1.post2
 - OS (e.g., Linux): Ubuntu 16
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.6.8
 - CUDA/cuDNN version: CUDA 10
 - GPU models and configuration: Nvidia V100

**Comment by gchanan** [comment]
I wasn't able to reproduce this on 1.1 -- please reopen if you can reproduce on 1.1 (and provide a specific n please).

**Comment by litianqi715** [comment]
I have reproduced this issue on pytorch 1.1.0

import torch
n = 11
t = torch.tensor([[1.0/n]*n]).half().cuda()
torch.multinomial(t, 1, True)

>>> torch.multinomial(t, 1, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 71, in __repr__
    return torch._tensor_str._str(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 286, in _str
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 201, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 83, in __init__
    value_str = '{}'.format(value)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 386, in __format__
    return self.item().__format__(format_spec)
RuntimeError: CUDA error: misaligned address

-- environment --
PyTorch Version (e.g., 1.0): 1.1.0
OS (e.g., Linux): Ubuntu 16.04
How you installed PyTorch (conda, pip, source): pip
Build command you used (if compiling from source): pip install
Python version: 3.6.7 / 3.6.8
CUDA/cuDNN version: CUDA 10.1
GPU models and configuration: Nvidia 1080Ti
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+

**Comment by cometta** [comment]
i tested in 1.5.1 and still the same error

**Comment by kevinbird15** [comment]
I am getting the same error.  It looks like it only happens if only one sample is taken: 
`torch.multinomial(t,1,True)` <---Broken
`torch.multinomial(t,2,True)` <---Works
-- environment --
PyTorch Version (e.g., 1.0): 1.6.0 (py3.8_cuda10.2.89_cudnn7.6.5_0)
OS (e.g., Linux): Ubuntu 16.04
How you installed PyTorch (conda, pip, source): environment.yml (fastai)
Build command you used (if compiling from source): N/A
Python version: 3.6.7 / 3.6.8
CUDA/cuDNN version: CUDA 10.2
Nvidia Driver version: 430.26
GPU models and configuration: Nvidia 1080Ti Founders

**Comment by KevinMusgrave** [comment]
@kevinbird15 Got the same bug as you, using pytorch 1.6

**Comment by thavlik** [comment]
I am getting this on 1.7.0. Could it be related to a graphics driver? I'm running a 1080 Ti with driver version 27.21.14.5681

**Comment by hstuk** [comment]
@kevinbird15 i still get the same bug as you in pytorch 1.7
