### ISSUE TITLE
New Sampler class suggestion, a.k.a `SequentialIndicesSampler`

### ISSUE THREAD

**Issue by rightx2** [pytorch/pytorch#19957]
## 🚀 Feature

Sequential sampler based on **indices**, not on data

## Motivation
It might be really helpful to have samplers that sample data based on **indexes without randomness** (In short, no-randomness version of `SubsetRandomSampler`), so that it make it possible to generate `Dataloader` for train, valid and test dataset like below:
```
train_loader = DataLoader(train_dataset, batch_size, sampler=SubsetRandomSampler(train_indexes_list))
valid_loader = DataLoader(test_dataset, batch_size, sampler=SequentialIndicesSampler(valid_indexes_list))
test_loader = DataLoader(test_dataset, batch_size, sampler=SequentialIndicesSampler(test_indexes_list))
```
(`len(train_indexes_list) : len(valid_indexes_list) : (len(test_indexes_list) could be 6:2:2`)

Code suggestion:

```
class SequentialIndicesSampler(Sampler):
    def __init__(self, indices):
        self.indices = indices

    def __iter__(self):
        return iter(self.indices)

    def __len__(self):
        return len(self.indices)
```

**Comment by SsnL** [comment]
I'm not sure we want this in core. This can be so easily implemented on user end. The `sampler` arg is specifically used to pass in custom samplers.

**Comment by soumith** [comment]
I'll go with @SsnL 's judgement and close this request.
