### ISSUE TITLE
torch.save is saving too much

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#1995]
If I have a tensor `x` of size (100000000,), and I save it with `torch.save(x[:10])`, it will take a lot of space in the disk (same space than if I save the entire tensor). However, `torch.save(x[:10].clone())` only seems to serialize the relevant part of the tensor.

Is it expected behaviour?

**Comment by soumith** [comment]
this is expected behavior. You are saving a Tensor viewing on a large Storage, when you load back, we will give you the same -- a Tensor viewing on a large Storage.

**Comment by soumith** [comment]
This is especially needed because you can save something like: `torch.save([x[:10], x[2:4]])` and then when you load back, the expectation is that the loaded values will share storage (i.e. be two Tensors viewing a larger storage)

**Comment by galeselee** [comment]
However, it makes me confused :-)
