### ISSUE TITLE
torch._C._demangle("t") needs to return `t` instead of `unsigned short`

### ISSUE THREAD

**Issue by dnlcrl** [pytorch/pytorch#19958]
## 🐛 Bug

I asked in PT's Slack about why the PyTorch profiler returns an `unsigned short` op when performing `torch.t(tensor)`, @t-vi guesses `torch._C._demangle("t")` needs to return `t` instead of `unsigned short`and asked me to open this issue.

Thank you

## To Reproduce

```
import torch
tensor = torch.randn(10).reshape(2, 5)
with torch.autograd.profiler.profile() as prof:
    torch.t(tensor)
print(prof)
```

which outputs:

> ------------------  ---------------  ---------------  ---------------  ---------------  ---------------
> Name                       CPU time        CUDA time            Calls        CPU total       CUDA total
> ------------------  ---------------  ---------------  ---------------  ---------------  ---------------
> unsigned short             15.176us          0.000us                1         15.176us          0.000us
> view                       13.622us          0.000us                1         13.622us          0.000us
> [….]

But when directly using `torch.transpose(tensor, 0, 1)` the profiler doesn’t show any `unsigned short` op:

```
import torch
tensor = torch.randn(10).reshape(2, 5)
with torch.autograd.profiler.profile() as prof:
    torch.transpose(tensor, 0, 1)
print(prof)
```

> --------------  ---------------  ---------------  ---------------  ---------------  ---------------
> Name                   CPU time        CUDA time            Calls        CPU total       CUDA total
> --------------  ---------------  ---------------  ---------------  ---------------  ---------------
> transpose              15.639us          0.000us                1         15.639us          0.000us
> view                    8.079us          0.000us                1          8.079us          0.000us
> abs                     4.948us          0.000us                1          4.948us          0.000us
> [….]

## Environment
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.3
GCC version: Could not collect
CMake version: version 3.11.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.15.1
[pip] torch==0.4.1
[pip] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.3                      1
[conda] mkl_fft                   1.0.4            py37h5d10147_1
[conda] mkl_random                1.0.1            py37h5d10147_1
[conda] pytorch                   0.4.1           py37_cuda0.0_cudnn0.0_1    pytorch
[conda] torchvision               0.2.1                    py37_1    pytorch

## Additional context

from @t-vi: 
> The question would be whether demangle is also used to just convert "mangled types" into types (probably yes), so maybe it'd be easiest to just special case single letters in autograd's python bits before calling demangle

[slack question](https://pytorch.slack.com/archives/C3PDTEV8E/p1556615985203800), [reply](https://pytorch.slack.com/archives/C3PDTEV8E/p1556617413207500)

**Comment by t-vi** [comment]
To be more precise, I think it's one of the two `demangle`s in [`torch.autograd/profiler.py`](https://github.com/pytorch/pytorch/blob/master/torch/autograd/profiler.py) doing it. Finding out which one and special casing single letter function names would be easy, but might not be high quality enough for inclusion into PyTorch. A cleaner solution might be to indicate that we're passing a function name and then adapting demangle to cater to that case.

**Comment by apaszke** [comment]
Or we could special-case `t` 😄 Those conflicts will probably be rare, and adding a flag which says that a name might be mangled or not might complicate things too much. But it's still worth trying to see if there's a simple solution.

**Comment by t-vi** [comment]
I meant that demangle should know whether it demangles an entire function name or just the substring corresponding to a single type (function `t` vs the `t` in `_Z1ft`) so that in the former case it can can skip demangling if the function name doesn't start with `_Z` or `?` (the latter to cover MSVC). Or we could skip the demangling for those cases in `autograd/profiler.py`.

**Comment by apaszke** [comment]
Isn't the `_Z` prefix compiler specific? Or is there an option for c++filt which makes it work with function names only?

**Comment by t-vi** [comment]
Most of the compilers we care about seem part of `_Z`, but MSVC is different:
https://en.wikipedia.org/wiki/Name_mangling#How_different_compilers_mangle_the_same_functions

**Comment by albanD** [comment]
Corresponding PR was merged.
