### ISSUE TITLE
Export AdaptivePool2d[3,3] to ONNX.symbolic with error "Only output_size=[1, 1] is supported"

### ISSUE THREAD

**Issue by weihua04** [pytorch/pytorch#19954]
i'd like to export the pytorch model to onnx,
i have a AdaptiveAvgPool2 but isn't output_size=[1, 1]
"        self.avgpool = nn.AdaptiveAvgPool2d((3, 3))".

how to export the pytorch model to onnx?
does anyone has any good idea?

**Comment by houseroad** [comment]
Right now, we don't have adaptive_pool in ONNX, is it possible, you can use regular pool to express your model?

**Comment by garymm** [comment]
Fixed by #17412
