### ISSUE TITLE
Scatter CUDA Out Of Memory

### ISSUE THREAD

**Issue by Queuecumber** [pytorch/pytorch#19970]
## 🐛 Bug

DataParallel scatter is hitting a CUDA OOM error for reasons I can't figure out.

I am trying to reload a checkpoint from a model which was training without memory issues earlier. Same batch size, same model, same machine. GPUs are 4x Quadro P6000 with 24GB of memory each. Here is the error:

```
Traceback (most recent call last):
  File "experiments/train_model.py", line 75, in <module>
    l = model.train(i, deartifacting_network, device, training_loader, optimizer, summary_writer, stats=stats)
  File "/cfarhomes/maxehr/scratch/jpeg-enhance/model/train.py", line 15, in train
    output, _, _, _, _ = model(x, y)
  File "/vulcan/scratch/maxehr/jpeg-enhance/.venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/vulcan/scratch/maxehr/jpeg-enhance/.venv/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 139, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/vulcan/scratch/maxehr/jpeg-enhance/.venv/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 150, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/vulcan/scratch/maxehr/jpeg-enhance/.venv/lib/python3.5/site-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/vulcan/scratch/maxehr/jpeg-enhance/.venv/lib/python3.5/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    return scatter_map(inputs)
  File "/vulcan/scratch/maxehr/jpeg-enhance/.venv/lib/python3.5/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/vulcan/scratch/maxehr/jpeg-enhance/.venv/lib/python3.5/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/vulcan/scratch/maxehr/jpeg-enhance/.venv/lib/python3.5/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/vulcan/scratch/maxehr/jpeg-enhance/.venv/lib/python3.5/site-packages/torch/cuda/comm.py", line 148, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/THCGeneral.cpp:172
```

So it looks like it's the scatter that's failing, the model loads fine, dataparallel gets set up fine, only when I try to train the batch using scatter do I get this error, and it is the first batch after loading the checkpoint.

The batch is 32 256x256 grayscale images. Before running the training loop, I tried printing out the GPU memory usage to see how it looks, the numbers are:

cuda:0 6.091384410858154GB
cuda:1 0.0GB
cuda:2 0.0GB
cuda:3 0.0GB

so plenty of room. 

If a float is 32bit, or 4 bytes, that should be 4 * 32 * 256 * 256 bytes per batch or 8388608 bytes which is only 8 MB. Divided by 4 GPUs thats 2MB per GPU. Again, there appears to be plenty of space.

So why is scatter OOM?

## To Reproduce

Not sure of a general way to repro since I'm assuming this has been tested and works. I'm also not going to be able to provide much with my specific code at this stage.

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
GCC version: (GCC) 8.1.0
CMake version: version 2.8.12.2

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: Quadro P6000
GPU 1: Quadro P6000
GPU 2: Quadro P6000
GPU 3: Quadro P6000

Nvidia driver version: 418.43
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.0.1.post2
[pip3] torchjpeg==0.0.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

**Comment by Queuecumber** [comment]
I have a feeling this is not scatter that is failing it's just where the exception looks like it's coming from. 

Now the kind of weird thing is that with a batch size of 32, each GPU should get 8 images (32 / 4 = 8), so, with that in mind, if I set

CUDA_VISIBLE_DEVICES=0 and batch size 8, no problem
CUDA_VISIBLE_DEVICES=0,1 and batch size 16 no problem
CUDA_VISIBLE_DEVICES=0,1,2 and batch size 24 no problem
CUDA_VISIBLE_DEVICES=0,1,2,3 and batch size 32 crash

which makes no sense to me unless all the images are being stored on a single GPU before they are scattered?

**Comment by Queuecumber** [comment]
Just an addendum to the above tests, the only batch size that works for 4 devices is batch size **2** even batch size **3** causes a crash. 

I also updated my pytorch to the latest version, which is 1.1.0 I think. The error message changed to

```
RuntimeError: CUDA out of memory. Tried to allocate 1.10 GiB (GPU 0; 23.88 GiB total capacity; 2.38 GiB already allocated; 20.86 GiB free; 21.96 MiB cached)
```
 e.g. it failed to allocate 1.10GB when there were 20.86GB free???

**Comment by Queuecumber** [comment]
Here's the relevant line that is causing the failure

https://github.com/pytorch/pytorch/blob/792cb774f152bab5b968f4ec51da0fc21ff9e895/aten/src/THC/THCGeneral.cpp#L159

when trying to enable peer memory access. The thing is, according to the docs at https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__PEER.html#group__CUDART__PEER_1g2b0adabf90db37e5cfddc92cbb2589f3 OOM isnt even an error that this function can throw

**Comment by Queuecumber** [comment]
OK here's my best guess as to whats happening

Any time it tries to access that 4th GPU, it gets the OOM error. That would explain why 1,2,3 cuda devices work without a problem and it would explain why with four devices I can use a batch size up to 3. I bet that the way scatter works is that it just places each element sequentially on the GPUs, so for batch size three it would only use GPUs 0,1,2 and not touch the 4th one. As soon as I try to go to batch size <= 4, it puts something on that 4th GPU and craps out.

**Comment by zhangguanheng66** [comment]
Thanks for the information. We will discuss this issue during our next triage meeting.

**Comment by Queuecumber** [comment]
I have a feeling this is something to do with cuda and something weird with the compute cluster I am working on, but I'm not sure how to further debug it

After needing to restart it again this morning, I was getting this same crash until I disabled only the *3rd* gpu, so now GPUs 0,1,3, work fine but anything put on 2 causes a crash. Who knows what caused it to change.

**Comment by Queuecumber** [comment]
After working with my IT department, we believe that this is actually a misleading error and that it is actually main memory that is running out, not CUDA memory. We have been unable to reproduce the error when the job is allowed to use more main memory and it explains why the error is coming from a CUDA function which should not throw a cuda OOM error.

**Comment by zhangguanheng66** [comment]
Thanks for the update. I will just close the issue. If you have any questions, please feel free to re-open the issue.
