### ISSUE TITLE
module 'torch.distributed' has no attribute '_compute_bucket_assignment_by_size'

### ISSUE THREAD

**Issue by lxiaorui** [pytorch/pytorch#19972]
## ❓ Questions and Help

I am trying to use the DistributedDataParallel class for distributed training. I tried to run the code from here: 
**https://github.com/pytorch/examples/blob/master/imagenet/main.py** 
by the command:
**python main.py '/mnt/home/Data/' --dataset MNIST  --epoch 5 --multiprocessing-distributed --dist-url 'tcp://127.0.0.1:23456' --world-size 1 --rank 0** 
which supposed to use all GPUs on one machine.
But I got the following error:

File "/mnt/home/examples-master/imagenet/main.py", line 190, in main_worker
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])   #commented
  File "/mnt/home/virtualenvs/wave/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 291, in __init__
    self._ddp_init_helper()
  File "/mnt/home/virtualenvs/wave/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 331, in _ddp_init_helper
    bucket_indices = dist._compute_bucket_assignment_by_size(
AttributeError: module 'torch.distributed' has no attribute '_compute_bucket_assignment_by_size'

To summarize, it is mainly:
**module 'torch.distributed' has no attribute '_compute_bucket_assignment_by_size'**

I am using the PyTorch installed by pip and the version is "1.0.1.post2".
I check the attributes of torch.distributed and it shows:

dir(torch.distributed)

['AllgatherOptions', 'AllreduceOptions', 'Backend', 'BarrierOptions', 'BroadcastOptions', 'FileStore', 'GatherOptions', 'GroupMember', 'PrefixStore', 'ProcessGroup', 'ProcessGroupGloo', 'ProcessGroupNCCL', 'ReduceOp', 'ReduceOptions', 'ScatterOptions', 'Store', 'TCPStore', 'Work', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_backend', '_dist_broadcast_coalesced', '_dist_bucket_tensors', '_queue_reduction', '_sync_params', '_sync_reduction', 'all_gather', 'all_gather_multigpu', 'all_reduce', 'all_reduce_multigpu', 'barrier', 'broadcast', 'broadcast_multigpu', 'deprecated', 'destroy_process_group', 'dist_backend', 'distributed_c10d', 'gather', 'get_backend', 'get_rank', 'get_world_size', 'group', 'init_process_group', 'irecv', 'is_available', 'is_initialized', 'is_mpi_available', 'is_nccl_available', 'isend', 'new_group', 'recv', 'reduce', 'reduce_multigpu', 'reduce_op', 'register_rendezvous_handler', 'rendezvous', 'scatter', 'send', 'string_classes', 'timedelta', 'torch', 'warnings']

There is no attributes "_compute_bucket_assignment_by_size" at all. It seems that this distribute missing. 

Anyone has the same problem with class DistributedDataParallel? Thanks.

**Comment by pietern** [comment]
This looks like a mismatch between Python sources and the C++ library. We always make these updates in lock step, so if you're using the right version of Python sources and the right version of the C++ library, which are always installed side by side, then this wouldn't be an issue. Please reinstall from source, or upgrade to version 1.1, to resolve the issue.

**Comment by lxiaorui** [comment]
Thanks @pietern. I upgrade it to version 1.1 and it works. 

By the way, there are some other issues in **https://github.com/pytorch/pytorch/blob/master/torch/distributed/distributed_c10d.py**.

In both function **gather** and **scatter**, if the node is not the dst/src, it requires the **tensorlist** to be **None** which is ensured by：
`if gather_list:
            raise RuntimeError("non-empty gather_list can be given only "
                               "to gather destination")
`
However, at the beginning of the function, it requires the tensorlist to be a list by:
`_check_tensor_list(gather_list, "gather_list")`

These two requirements are conflict to each other so I think it will never work. But I don't why how it can pass the unit test or does anyone run the test?

I end up by move **_check_tensor_list(gather_list, "gather_list")** into the block which looks like this and it works:
`if dst == my_rank:
        _check_tensor_list(gather_list, "gather_list")
        if gather_list is None:
            raise RuntimeError("gather_list is a required argument in gather "
                               "destination")
        input_tensors = [tensor]
        output_tensors = [gather_list]
    else:
        if gather_list:
            raise RuntimeError("non-empty gather_list can be given only "
                               "to gather destination")
        input_tensors = [tensor]
        output_tensors = []`

**Comment by pietern** [comment]
@lxiaorui It works when you pass an empty list. The empty list evaluates to `False`.
