### ISSUE TITLE
[Bug] make non-default binaries track specific features via X.Y.Z+feature

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#19990]
Right now, PyTorch's cu100 and cpu-only wheels have exactly the same filename as the default cu90 wheels.

Reading this thread https://github.com/pypa/pip/issues/4321#issuecomment-333774919 it is evident that we shouldn't have done this.

We need to fix:
- `download.pytorch.org/whl/cpu/torch-1.1.0-cp27-cp27m-linux_x86_64.whl` -> `download.pytorch.org/whl/cpu/torch-1.1.0+cpuonly-cp27-cp27m-linux_x86_64.whl`
- `download.pytorch.org/whl/cu100/torch-1.1.0-cp27-cp27m-linux_x86_64.whl` -> `download.pytorch.org/whl/cu100/torch-1.1.0+cuda100-cp27-cp27m-linux_x86_64.whl`

**Comment by gchanan** [comment]
@soumith should I assign you to this or is someone else planning to work on this?

**Comment by Halflernation** [comment]
Just as a heads-up: a few threads pointed here for the bugtrack.
Issue also appears when you use the PyTorch wheels (as it would if compiled from source).

Happy to hear news on this soon.
H+

**Comment by ezyang** [comment]
I'll be working on this.

**Comment by ezyang** [comment]
@soumith We can't do this, not as exactly spelled above. The string after the plus is a *local version identifier*, and per https://www.python.org/dev/peps/pep-0440/#local-version-identifiers and so we can't upload them to PyPI (unless you want to stop uploading these to PyPI.)

**Comment by soumith** [comment]
as discussed with Edward irl, we dont need to upload the string+ versions to PyPI, only the default config gets uploaded to PyPI. So, we should be okay.

Additional things to check:

- If we do 1.1.0+cu100, will packages depending on `torch >= 1.1.0` identify the package as installed, or will there be weirdness?
- Can a downstream package depend on `torch == 1.1.0+cu100` and will things be checked correctly?
- if `torch == 1.1.0` is installed (i.e. no feature postfix), and `torchvision 0.4+cu100` is attempted to be installed, what is the result? (it should fail)

**Comment by ezyang** [comment]
> Can a downstream package depend on torch == 1.1.0+cu100 and will things be checked correctly?

PyPI permits packages to have dependencies on local version specifiers. Whether or not this is intentional is another matter...

**Comment by ezyang** [comment]
> If we do 1.1.0+cu100, will packages depending on torch >= 1.1.0 identify the package as installed, or will there be weirdness?

Yes, the package is identified as installed.

**Comment by ezyang** [comment]
OK, it looks like this is indeed the right thing to do, and it has the behavior we want.

**Comment by ezyang** [comment]
@soumith When we do this, should we get rid of `torchvision-cpu-0.4.0` and instead do `torchvision-0.4.0+cpu`?

**Comment by soumith** [comment]
yes
