### ISSUE TITLE
[JIT] tensor.new_* should not be legacy and deprecated

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#19995]
These were created to match numpy and are quite handy to create tensors with the same device & dtype (especially considering that python does not have `.options()`). They are still relatively new (introduced in 0.4) and we are still advocating using them in docs. I don't know why they are not considered "legacy" just because that the current JIT does not support them.

relevant PR: https://github.com/pytorch/pytorch/pull/16770

**Comment by fritzo** [comment]
I just spent half a day rewriting Pyro to avoid using these constructors. It would be great if my team could have stable recommendations for which constructors to use. cc @neerajprad

**Comment by suo** [comment]
Seems like there's some confusion about whether we actually did deprecate these. We can make them work with the JIT if that's the desired behavior—can someone with more context weigh in on what we should do with the `new_*` constructors? @zdevito @apaszke @gchanan

**Comment by SsnL** [comment]
@suo The legacy tensor ctor, I am pretty sure, is `tensor.new(...)`, not the `tensor.new_*` family.

**Comment by soumith** [comment]
@suo i think issuing the warning and calling them legacy was a mistake (it took me by surprise as well, but I was too buried into the release to have time to think through).
We should undo those warnings.
The legacy constructors are `x.new(...)` and `torch.*Tensor(...)`

**Comment by gchanan** [comment]
@soumith's description is correct, those aren't legacy.

This is relatively clear in the implementation (https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/tensor_new.h) -- the implementations of `x.new(...)` and `torch.*Tensor(...)` are called "legacy", and the implementations of e.g. `new_zeros` aren't.

**Comment by suo** [comment]
Okay, we should revert this. @driazati can you take a look?

**Comment by gchanan** [comment]
Just to give a bit more context, I know it would have been a lot clearer for you if we actually put deprecated warnings on `torch.Tensor` in python, but we have shy-ed away from it because it would cause a ton of deprecated warnings for literally every torch program.

But that reasoning doesn't really apply to JIT.

**Comment by driazati** [comment]
Reverting the warnings seems reasonable (#20026), we can do a follow up PR to fix it in the JIT specifically.
