### ISSUE TITLE
issue while exporting torch model to onnx format

### ISSUE THREAD

**Issue by Amir22010** [pytorch/pytorch#20009]
## 🐛 Bug

i am getting error while converting my saved torch model to onnx format

torch.onnx.export(trained_model, dummy_input, "sentiment.onnx")
TypeError: forward() missing 1 required positional argument: 'hidden' 

torch version - '1.0.1.post2'

## To Reproduce

from torch.autograd import Variable
import torch.onnx
# Load the trained model from file
net_save = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)
trained_model = net_save
trained_model.load_state_dict(torch.load('sentiment.pth'))

# Export the trained model to ONNX
dummy_input = Variable(torch.randn(1, 1, 28, 28)) # one black and white 28 x 28 picture will be the input to the model
torch.onnx.export(trained_model, dummy_input, "sentiment.onnx")

## Expected behavior

i should get the onnx format of my model but getting error

cc @BowenBao @neginraoof

**Comment by kalyc** [comment]
Me too: https://github.com/pytorch/pytorch/issues/20031

**Comment by RickyMacharm** [comment]
same here...any updates on this?

**Comment by garymm** [comment]
The `dummy_input` should be a tuple that has the same number of elements as are required by `trained_model.forward()`.
@Amir22010 are you still having an issue? If so please provide code that reproduces the issue, ideally in Google Colab or a git repo.

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
