### ISSUE TITLE
torch.jit.trace returns unwrapped C type

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#20017]
### With pytorch 1.1.0

```
import torch
def f(x):
  return x*2
z = torch.jit.trace(f, (torch.zeros(10),))
print(type(z))
```

Returns `torch._C.Function` and cannot be saved:

`Traceback (most recent call last):
  File "1.py", line 7, in <module>
    torch.jit.save(z, "filename")
  File "/home/vitalyf/local/miniconda/envs/wp_1/lib/python3.7/site-packages/torch/jit/__init__.py", line 198, in save
    m.save(f, _extra_files=_extra_files)
AttributeError: 'torch._C.Function' object has no attribute 'save'
`

### Expected as in pytorch 1.0.1

```
import torch
def f(x):
  return x*2
z = torch.jit.trace(f, (torch.zeros(10),))
print(type(z))
```

Returns `<class 'torch.jit.TopLevelTracedModule'>`

**Comment by eellison** [comment]
cc @wanchaol recently touched save @zdevito first class module support

**Comment by igormq** [comment]
Any news?

**Comment by robert-wagner** [comment]
@VitalyFedyunin This issue is listed as closed but is still broken in the latest nightly build. This issue should be reopened

**Comment by VitalyFedyunin** [comment]
@driazati can you please take a look

**Comment by driazati** [comment]
@robert-wagner are you able to post a repro? The code from the issue works fine for me on master

```python
import torch
def f(x):
    return x*2
z = torch.jit.trace(f, (torch.zeros(10),))
print(type(z))
z.save("out.pt")
```

We have #22269 tracking adding a user-facing wrapper, but that's mostly aesthetic and all the functionality should already work.

**Comment by robert-wagner** [comment]
@driazati I will try building from master. I ran the above code after following the instructions to install the nightly build. I will try again building from master

```
In [1]: import torch

In [2]: torch.__version__
Out[2]: '1.2.0.dev20190709'

In [3]: def f(x):
   ...:     return x*2
   ...:

In [4]: z= torch.jit.trace(f, (torch.zeros(10),))

In [5]: print(type(z))
<class 'torch._C.Function'>
```

**Comment by driazati** [comment]
That's expected (see #22269), but `save` should work now so functionally it's OK. I'm rolling that issue into this one since they're now the same thing.

**Comment by robert-wagner** [comment]
Hey @driazati @Krovatkin Following up on this, the main reason this is relevant for me is being able to call .to on a traced module as was supposedly added by #7354. This does not work on the current nightly.
a minimal example of this is
```
In [1]: import torch

In [2]: def f(x):
   ...:   return x*2
   ...:

In [3]: z = torch.jit.trace(f, (torch.zeros(10),))

In [4]: z.to("cpu")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-c7a8e1e96ced> in <module>
----> 1 z.to("cpu")
```

**Comment by NeilWangziyu** [comment]
Hi, I met a similar problem on saving a function by jit
```bash
AttributeError: 'torch._C.Function' object has no attribute 'save'
```

At first, I thought it is a new feature that a function is no longer supported to be saved as a binary file. But after looking through this issue, I realized that it is a bug that I can not save a function?

around one month ago, it is okay for me to save a function, and I check the update history, the jit.scrip  function is changed and for obj not class, it would call torch._C._jit_script_compile to handle the obj. 

I always use the latest stable version from pytorch.org, Will this bug be fixed? or just keep forbidding the function from being saved?

```python
@torch.jit.script
def foo(x:int, tup:Tuple[int, int])->int:
    t0, t1 = tup
    return t0 + t1 + x

print(foo(3,(3,13)))
print(type(foo))
torch.jit.save(foo, "test.pt")
```

**Comment by robert-wagner** [comment]
Hey @NeilWangziyu I just tried running your code in the latest nightly version of pytorch and it seems to work fine with saving and loading. The issue with saving will be fixed in the next stable release of pytorch whenever it is released.

**Comment by NeilWangziyu** [comment]
@robert-wagner 
I try to install the nightly version of pytorch, however met the error:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\t-ziw\AppData\Local\Continuum\anaconda3\envs\puretorch\lib\site-packages\torch\__init__.py", line 79, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified procedure could not be found.
```bash

but if I use the stable version it is okay, 

I am using win10, cuda:10.0 and had tried both the conda and pip.

**Comment by Krovatkin** [comment]
@NeilWangziyu You could also consider trying building PyTorch from source, if nightly doesn't work for you. Saving should definitely work now. @driazati added it 2 months ago in this PR: https://github.com/pytorch/pytorch/pull/20386

**Comment by bhosmer** [comment]
save now appears to work fine for these repros, closing
