### ISSUE TITLE
RuntimeError:CUDA Error:out of memory

### ISSUE THREAD

**Issue by Kunlun-Zhu** [pytorch/pytorch#20029]
## 🐛 Bug
 With a CUDA 10.1 and RTX GPU. 
When I try even the most simpliest code like
nums = torch.randn(2,2).cuda(), it show the above error
And torch.cuda.is_available() is True.
Any idea?

**Comment by soumith** [comment]
please use our bug report template, we need so much more info that we request in the template to understand what's up

**Comment by Kunlun-Zhu** [comment]
what?
