### ISSUE TITLE
New 'bool' type doesn't support inversion in 1.1.0

### ISSUE THREAD

**Issue by malmaud** [pytorch/pytorch#20024]
```
~torch.tensor(True).to(torch.bool)        
```

TypeError: ~ (operator.invert) is only implemented on byte tensors

**Comment by codexetreme** [comment]
Can I work on this ?

**Comment by abaisero** [comment]
Similar to this, the new torch bool type does not support .all() and .any() in 1.1.0.  Not sure if it's worth opening a separate issue for this?

**Comment by fmassa** [comment]
@abaisero we are aware of the missing functions for bool, and are working on having them implemented

**Comment by xuhdev** [comment]
Fixed in 9c4c9c3af042498144c40b30d64443cca943906a

**Comment by xuhdev** [comment]
Reverted for now, see https://github.com/pytorch/pytorch/pull/22326#issuecomment-510280113

**Comment by xuhdev** [comment]
But you can use Tensor.bitwise_not() as workaround for now

**Comment by xuhdev** [comment]
Fixed in 865c7eea4854fcfb50584e7f19450b4271c1b4f1
