### ISSUE TITLE
Leaking Torch Files

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#20046]
## Bug

When I build from source and install to `/usr/local`, some headers leaks out to `/usr`.

![image](https://user-images.githubusercontent.com/5203025/57054303-88cb9800-6c48-11e9-965c-8d404a5c5854.png)
![image](https://user-images.githubusercontent.com/5203025/57054323-bfa1ae00-6c48-11e9-9181-844c28582d3f.png)

This issue may be caused by the following code:
https://github.com/pytorch/pytorch/blob/725ef26f344588884f9f803d687711af5a7f300a/aten/src/ATen/core/CMakeLists.txt#L10-L20
https://github.com/pytorch/pytorch/blob/725ef26f344588884f9f803d687711af5a7f300a/aten/src/ATen/CMakeLists.txt#L418-L422

## To Reproduce

Set `CMAKE_INSTALL_PREFIX`.

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): CentOS-7
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake + ninja + gcc-8
 - Python version: 3.6

**Comment by eellison** [comment]
cc @kostmo

**Comment by xkszltl** [comment]
@suo @kostmo May I ask for some details about this `triaged` tag?

**Comment by suo** [comment]
Triaged means we have processed the issue and verified that the right labels/owners have been applied.

**Comment by xkszltl** [comment]
Thanks for the clarification

> Triaged means we have processed the issue and verified that the right labels/owners have been applied.

**Comment by ezyang** [comment]
@xkszltl Hey, quick question, what exact commands did you use to build and install PyTorch?  There are a bunch of ways to build libtorch and I want to make sure I know the correct one.

**Comment by ezyang** [comment]
@kostmo Are you actually working on this? If not, please unassign yourself.

**Comment by xkszltl** [comment]
It's plain call to cmake with `-DBUILD_TORCH=ON`.
More details here:
https://github.com/xkszltl/Roaster/blob/af1e5cbc66e68725cc2f6ead78f57e5e176b8eb8/pkgs/pytorch.sh#L64-L104

> @xkszltl Hey, quick question, what exact commands did you use to build and install PyTorch? There are a bunch of ways to build libtorch and I want to make sure I know the correct one.

**Comment by xkszltl** [comment]
Any news on this?
FYI the issue still there so far (from a build yesterday)
![image](https://user-images.githubusercontent.com/5203025/58150972-20efe800-7c1d-11e9-9f28-6ea39a590a57.png)
