### ISSUE TITLE
Libtorch's Interoperability with OpenGL/Cuda 

### ISSUE THREAD

**Issue by xin-xinhanggao** [pytorch/pytorch#20047]
## ❓ Questions and Help
Hello everyone, I want to convert tensor(at::kCuda) to OpenGL texture. But the IO between GPU and CPU is much too slow. Could libtorch interoperate with OpenGL texture or Cuda array in GPU layer?  

I can not find solution in pytorch forum, so post it here for help.

**Comment by xin-xinhanggao** [comment]
Or is there a way to convert libtorch tensor(k::Cuda) to cuda array?

**Comment by ifedan** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
