### ISSUE TITLE
Dockerfile submodule and unicode issue 

### ISSUE THREAD

**Issue by graykode** [pytorch/pytorch#20054]
#### 1. git clone missing
I tried to build [Dockerfile](https://github.com/pytorch/pytorch/blob/master/docker/pytorch/Dockerfile).
First, before `RUN git submodule update --init`, It is not fully functional independently.
 Is it true that the `git clone pytorch.git` was missing before `WORKDIR /opt/pytorch`?

```shell
WORKDIR /opt/pytorch
COPY . . # I think this is 

RUN git submodule update --init
```

I already see https://github.com/pytorch/pytorch/pull/16698
but I want to know why is it closed

#### 2. ENV LANG missing 
There are some language configurare missing.
```shell
# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8
```

Can I fix it rightly by contribution?

## Environment

`Docker version 18.03.0-ce, build 0520e24302` Window 10

**Comment by ifedan** [comment]
To be able to give a flexibility to a user to choose PyTorch version, "git clone" part was not included into Dockerfile.

**Comment by ifedan** [comment]
Can you provide more details on the second point? Why do you think LANG is required?

**Comment by soumith** [comment]
When you provide more details, please re-open the issue. thanks.

**Comment by crcrpar** [comment]
@graykode As to "1. git clone missing", I guess you forgot to pass the `.` to build command because I failed to build when I ran `docker build -t pytorch -f docker/pytorch/Dockerfile`. The right command is **`docker build -t pytorch -f docker/pytorch/Dockerfile .`**.

See: https://github.com/pytorch/pytorch#docker-image

**Comment by graykode** [comment]
@crcrpar No it is not matter, it's same whether `.` is or not.
