### ISSUE TITLE
Tensor.sum() over multiple axes

### ISSUE THREAD

**Issue by vlasenkov** [pytorch/pytorch#2006]
During writing `einsum` I've found that `sum` is able to sum only over single axis. I'm going to add a simple implementation of it:

```
def sum(input, axes, keepdim=False):
    # probably some check for uniqueness of axes
    if keepdim:
        for ax in axes:
            input = input.sum(ax, keepdim=True)
    else:
        for ax in sorted(axes, reverse=True):
            input = input.sum(ax)
    return input
```
1. Is it ok?
2. Where should it be better placed?

**Comment by arogozhnikov** [comment]
Looks very useful

- Numpy uses `keepdims`, is there a reason to use `keepdim` name for parameter?
- probably, same should be done to `torch.prod`
- does it make sense to change `tensor.sum`, `variable.sum` as well?

**Comment by gchanan** [comment]
Right, we should rename keepdim to keepdims if we do this (and support it for both variables and tensors).  Also should do it for all functions with a keepdim parameter.

**Comment by fmassa** [comment]
If we want to add reduction over multiple axis, I think we should permute the axis so that they are consecutive, make contiguous and view those axis as one single dimension, so that we can perform the reduction over the reduced dimension. That would be more efficient than perfoming several reductions.

**Comment by ngimel** [comment]
@fmassa, it depends. .contiguous() for 3+ dimensional tensors is very slow now.

**Comment by fmassa** [comment]
@ngimel hum, that's a good point. Also, we will rarely perform reductions over more than 3 axes, so the number of extra calls is small.

**Comment by vlasenkov** [comment]
I've created a draft. Currently it checks number of dimensions. But it seems that choosing only one of the two (permute vs multiple calls to `.sum()`) solutions is better idea.

**Comment by t-ae** [comment]
We don't need whole tensor to be contiguous.
If we perform 3D `tensor.sum((1, 2))`, can reduce `sum` calls like
```
if tensor.stride(2)*tensor.size(2) == tensor.stride(1):
    output = tensor.view(tensor.size(0), -1).sum(1)
else:
    output = tensor.sum(2).sum(1)
```

And I think `mean`, `median`, `mode`, `min`, `max`, `std`, `var`, (and `norm`?) should have same signature for consistency.
