### ISSUE TITLE
Unable to compile an older version of PyTorch

### ISSUE THREAD

**Issue by Amir-Arsalan** [pytorch/pytorch#20074]
I just tired building PyTorch from source from [this commit](https://github.com/pytorch/pytorch/tree/bad4442) but I got the following messages and error:

```
export BUILD_CAFFE2_OPS=0
git clone https://github.com/pytorch/pytorch
cd pytorch
git checkout 3a01a45
```

Then I get the following messages:

> warning: unable to rmdir third_party/foxi: Directory not empty
> M	third_party/NNPACK
> M	third_party/fbgemm
> M	third_party/ideep
> M	third_party/nccl/nccl
> M	third_party/onnx
> M	third_party/onnx-tensorrt
> Note: checking out '3a01a45'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at 3a01a45... Implement IRParser. (#16987)

Then I do
`git submodule update --init --recursive`

and get the following messages:

> Submodule 'third_party/ComputeLibrary' (https://github.com/ARM-software/ComputeLibrary.git) registered for path 'third_party/ComputeLibrary'
> Cloning into 'third_party/ComputeLibrary'...
> remote: Enumerating objects: 88692, done.
> remote: Total 88692 (delta 0), reused 0 (delta 0), pack-reused 88692
> Receiving objects: 100% (88692/88692), 121.26 MiB | 27.69 MiB/s, done.
> Resolving deltas: 100% (76635/76635), done.
> Checking connectivity... done.
> Submodule path 'third_party/ComputeLibrary': checked out '292227986edb37b01061afcad6df18ba9d6ccbeb'
> Submodule path 'third_party/NNPACK': checked out '1e005b0c2777f39972a4ac15bea03e0e315a3d92'
> Submodule path 'third_party/fbgemm': checked out '83b462ec58e78311ba3b64b48cbd49db0485641f'
> Submodule path 'third_party/ideep': checked out '689e38a124698261087b073068eb04588b9d1c55'
> Submodule path 'third_party/ideep/mkl-dnn': checked out '0c3cb94999919d33e4875177fdef662bd9413dd4'
> Submodule path 'third_party/nccl/nccl': checked out '3c6e25210bb1b544748937e5db74db0b9679b95e'
> Submodule path 'third_party/onnx': checked out '15c33c945851907411619f599900c3852108e7e3'
> fatal: reference is not a tree: 9884f286a236a3b4e3218e4afa17781752e048bd
> Unable to checkout '9884f286a236a3b4e3218e4afa17781752e048bd' in submodule path 'third_party/onnx-tensorrt'

I also tried with `git checkout bad4442` which is a bit older than `3a01a45`  but got the same error at the end.

In the past I used to compile older versions of PyTorch without an issue, but I had not done this for the past 2-3 months until today. I wonder what I should do to be able to compile an older version of PyTorch?

**Comment by zou3519** [comment]
Try `git submodule sync` and then `git submodule update --init`?
