### ISSUE TITLE
[Undesirable behaviour] Allocating a nn.Parameter on gpu inside a nn.Module makes it not to be enlisted as network parameter

### ISSUE THREAD

**Issue by JuanFMontesinos** [pytorch/pytorch#20089]
Short explanation:
Defining a parameter inside a nn.Module produces different a behaviour than a nn.Module if it's allocated on gpu after defined.

Long explanation:
As far as I know registering a parameter inside a nn.Module, in the init method, expects to register that tensor as a parameter of the network. Those parameters are leaf tensors, thus, they get optimized through learning.

Main problem is that if you define a module and a paremeter within, but afterwards this parameter is allocated on gpu, it does not appear as a model parameter since what the attribute registers is a copy of the tensor allocated on gpu. It points to a cpu version and updates ctx version and sets backward function properly good. 

After thinking about it, if user would like to allocate it into gpu, it would be better to define it in cpu and to allocate during the forward pass. Nevertheless, this is not the case with nn.Modules, as they can be allocated of gpu during the init method.

## To Reproduce

```
import torch.nn as nn
import torch.nn.functional as F
import torch

class Gpu(nn.Module):
    def __init__(self):
        super(Gpu,self).__init__()
        self.w = nn.Parameter(torch.ones(10)).cuda()

gpu = Gpu()
# list(gpu.parameters()) --> empty
# gpu.w.grad_fn = <CopyBackwards at 0x7fa0ff2890b8>
# gpu.w._version = 1
# gpu.isleaf = False

class Cpu(nn.Module):
    def __init__(self):
        super(Cpu,self).__init__()
        self.w = nn.Parameter(torch.ones(10))
cpu = Cpu()

# list(cpu.parameters())
# [Parameter containing:
 # tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)]
# cpu.w.grad_fn = None
# cpu.w._version = 0
# cpu.w.isleaf = True

"""
This is obviously expected, however it behaves totally different in case of nn modules
"""

class Wrapped(nn.Module):
    def __init__(self):
        super(Wrapped,self).__init__()
        self.w = Cpu().cuda()

wrp= Wrapped()
"""
Here, as the nn.Parameter is wrapped by a nn.Module it behaves as expected.
model contains all the parameters and they appear when calling wrp.parameters() and so on.
However I find confusing to be able to allocate nn.Modules while defining them but not parameters.
 This may generate problems as users wouldn't realize parameters are not enlisted in model.parameters(), thus, not passed to optimizer.

"""
```

Just write this to check this is the desired behaviour, but considering all tutorials show you can allocate nn.Modules on gpu while defining them, a different behaviour for parameters should at least be warned.

It's possible to bypass this behaviour preallocating the tensor on gpu before setting it as a parameter but I find it's a bad style.

**Comment by soumith** [comment]
```python
# wrong
self.w = nn.Parameter(torch.ones(10)).cuda()

# why is it wrong? it is more like:
x = nn.Parameter(torch.ones(10))
self.w = x.cuda() # non-leaf variable

# correct
self.w = nn.Parameter(torch.ones(10, device='cuda'))
```

**Comment by soumith** [comment]
see https://pytorch.org/docs/stable/tensors.html?highlight=leaf#torch.Tensor.is_leaf for an explanation on leaf vs non-leaf variables
