### ISSUE TITLE
Docker image does not contain torchvision

### ISSUE THREAD

**Issue by mackiem** [pytorch/pytorch#2009]
Torchvision is considered a basic requirement of the tutorials. Perhaps it makes sense to include it in the docker build.

```
# python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'torchvision'

```

**Comment by lynic** [comment]
It's easy to install it by command `conda install torchvision  -c soumith` ;)

**Comment by mackiem** [comment]
It's easy to install torch itself using a similar command? `conda install torch -c soumith` :). I was thinking a docker image should have torchvision included.

**Comment by ngimel** [comment]
Runtime docker file already has torchvision.
