### ISSUE TITLE
Build passing, but runtime failing (at commit ebdec9a837074a303fd5ffb6f319cd593955becc)

### ISSUE THREAD

**Issue by mackiem** [pytorch/pytorch#2011]
Running import torch gives the following error on the latest master:

```
Traceback (most recent call last):
  File "classifier.py", line 1, in <module>
    import torch
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/lib/libTHC.so.1: undefined symbol: THLongStorage_inferSizeN
```

# git log
commit ebdec9a837074a303fd5ffb6f319cd593955becc
Author: lynic <xuanlangjian@gmail.com>
Date:   Fri Jul 7 23:06:56 2017 +0800

    Skip distributed tests if not supported (#2004)

**Comment by soumith** [comment]
this is most definitely that you have an old install of pytorch somewhere that is conflicting with the freshly built source.

Try running these commands in a terminal, and afterwards rebuild pytorch from source:

```
conda uninstall pytorch
pip uninstall torch
pip uninstall torch # yes twice
```
