### ISSUE TITLE
RuntimeError cudnn error cudnn_status_alloc_failed

### ISSUE THREAD

**Issue by wangqi1113** [pytorch/pytorch#20123]
python version: 3.6.4
pytorch version: 1.1.0
cuda version: 9.0
cudnn version: 7
win10

**Comment by vishwakftw** [comment]
Could you please provide a script that can reproduce the issue?

**Comment by cristianPanaite** [comment]
Hello @wangqi1113,

Closing this ticket as the ticket hasn't had any activity for a long period of time and it seems that it is not valid anymore. 

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.
