### ISSUE TITLE
GRUcell has a wrong formula

### ISSUE THREAD

**Issue by kangkang59812** [pytorch/pytorch#20129]
## 📚 Documentation

https://pytorch.org/docs/stable/nn.html?highlight=grucell#torch.nn.GRUCell
$$
\begin{aligned} r &=\sigma\left(W_{i r} x+b_{i r}+W_{h r} h+b_{h r}\right) \\ z &=\sigma\left(W_{i z} x+b_{i z}+W_{h z} h+b_{h z}\right) \\ n &=\tanh \left(W_{i n} x+b_{i n}+r *\left(W_{h n} h+b_{h n}\right)\right) \\ h^{\prime} &=(1-z) * n+z * h \end{aligned}
$$

For the last one , It should be (1-z) * h+z * n. 
$$
h^{\prime}=(1-z) * h+z * n
$$

**Comment by Derek-Wds** [comment]
Hi, in the paper by [Cho](https://arxiv.org/pdf/1406.1078.pdf). The documentation of GRU's formula is correct.

Thanks,
Derek

**Comment by xingzhex** [comment]
There are two papers from the same author: [https://arxiv.org/pdf/1406.1078.pdf], September, 2014 (Cho is the first author) and [https://arxiv.org/pdf/1412.3555.pdf], December, 2014 (Cho is the third author). GRU's formulas are different in these two papers. Wikipedia took the formula from the second paper. I think the first one should be the correct one since it is the original paper.

**Comment by Kaixhin** [comment]
@kyunghyuncho would you be able to settle this?

**Comment by kyunghyuncho** [comment]
either is fine, because it's all about semantics of z. that is, if z is considered an update gate, z * n makes sense, while (1-z)* n makes sense if we think of z as a leaky coefficient. in the end, they are equivalent.

**Comment by xingzhex** [comment]
@kyunghyuncho Aha, yes, they are. Thank you very much for your reply. So z in Equation 7 of the paper <Learning Phrase Representations using RNN Encoder–Decoder
for Statistical Machine Translation> is actually a reset gate if I understand correctly?

**Comment by kyunghyuncho** [comment]
i called r a reset gate. i think calling z either way an update gate is fine, as it's whether we update the existing cell with a new value or update the new value while maintaining the old value by z.

**Comment by xingzhex** [comment]
i see. thank you very much for your explanation.
