### ISSUE TITLE
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp

### ISSUE THREAD

**Issue by ivanwilliammd** [pytorch/pytorch#20133]
Hello, my friend are trying her new RTX 2080 8GB, with nvidia driver 410.57

She's currently running some legacy deep learning model using pytorch 0.4.1 (incompatible with pytorch 1.0) due to NMS and RoI align still using ffi instead of cpp. The nvidia driver 410.57, and still using cuda 9.0.
She gets THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp silent error, while the model still running. But some of the case after she break current process, she need to logout first before running another model because of CUDA:OutOfMemory error.
Do you have some trick to it?

**Comment by izdeby** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
