### ISSUE TITLE
nn.MultiheadAttention has no `_{get,set}_input_buffer` internals

### ISSUE THREAD

**Issue by nrlugg** [pytorch/pytorch#20132]
## 🐛 Bug

Pretty clear from the title: there are no internal methods `_{get,set}_input_buffer` in the new `nn.MultiheadAttention` module,  so you get the following error when passing an `incremental_state` to the module call

```
AttributeError: 'MultiheadAttention' object has no attribute '_get_input_buffer'
```

It would seem that these were lost when porting the [Fairseq implementation](https://github.com/pytorch/fairseq/blob/master/fairseq/modules/multihead_attention.py).

(As a side note: it's completely not obvious what `incremental_state` state is or how to use it.)

**Comment by izdeby** [comment]
@nrlugg, thanks for reporting the issue! Do you have a self-contained script which we could use to reproduce the problem?

**Comment by zhangguanheng66** [comment]
Good catch. I will resolve this issue.

**Comment by zhangguanheng66** [comment]
@nrlugg Thanks for bringing up the problem. To fully support the incremental_state function, we need to implement a few additional utils. And we lack of a unit test for the incremental_state function. Instead, I will disable the function for now. If it's needed in the future, please open a feature request.

**Comment by nrlugg** [comment]
@zhangguanheng66 Will do! Thanks!
