### ISSUE TITLE
Need to include ATen/Parallel.h for get/set_num_threads

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#20130]
## 🐛 Bug

Prior to 1.1.0, the c++ interface was able to reference
```
torch::get_num_threads
torch::set_num_threads
```
without additional includes beyond: _torch/torch.h_

now, it looks like it is necessary to explicitly include:
ATen/Parallel.h

this is easy enough to do, but seems like this should be part of the overall include,
yes(?)

thanks

**Comment by soumith** [comment]
yea this should be fixed. cc: @yf225 @ilia-cher
