### ISSUE TITLE
AvgPool2d: when kernel is NxN while Input is MxN w/o padding : not work right

### ISSUE THREAD

**Issue by hanochk** [pytorch/pytorch#20141]
## To Reproduce

self.model = nn.Sequential((nn.AvgPool2d(kernel_size = 6 )))(x)
1.x = [16,1,3,6]
1.No error message despite the fact that no padding was allowed by configuration

## Expected behavior

 I was expecting an error message like in TF

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by soumith** [comment]
on latest pytorch, the following error is given `RuntimeError: Given input size: (1x3x6). Calculated output size: (1x0x1). Output size is too small`
