### ISSUE TITLE
TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above

### ISSUE THREAD

**Issue by LIMr1209** [pytorch/pytorch#20140]
Traceback (most recent call last):
  File "/home/tian/.conda/envs/jiqi/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
  File "/home/tian/Desktop/ai/machine-learn/Image_recognition/tensorboard.py", line 3, in <module>
    from torch.utils.tensorboard import SummaryWriter
ImportError: cannot import name 'SummaryWriter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tian/Desktop/ai/machine-learn/Image_recognition/tensorboard.py", line 3, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/tian/.conda/envs/jiqi/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    raise ImportError('TensorBoard logging requires TensorBoard with Python summary writer installed. '
ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above

**Comment by LIMr1209** [comment]
tensorboard --logdir=runs
TensorBoard 1.14.0a20190504 at http://tian-ORC:6006/ (Press CTRL+C to quit)

**Comment by GeniusGaryant** [comment]
> tensorboard --logdir=runs
> TensorBoard 1.14.0a20190504 at http://tian-ORC:6006/ (Press CTRL+C to quit)

It seems that you worked? If not, maybe this link https://www.endtoend.ai/pytorch-tensorboard may help you.

**Comment by LIMr1209** [comment]
@GeniusGaryant Thank you very much :blush:

**Comment by SsnL** [comment]
cc @orionr The error message is confusing. Python summary writer isn't in `TensorBoard 1.14.0a20190301 ` (it is in `TensorBoard 1.14.0a20190505`)

**Comment by orionr** [comment]
1.14 hasn't been released yet (the above are just master commits), but will be in the near future. This is what we reference in the message. For now, people should install with `pip install tb-nightly` until the 1.14 release.

**Comment by Maghoumi** [comment]
In case you've already tried `pip install tb-nightly` but still get the error message about `TensorBoard 1.14`, it could be that the TensorBoard packages in your `~/.local` are older than 1.14.

This can happen if you install packages via `pip install --user ...` and some other packages via `sudo pip install ...`, which is known to mess things up.

**Comment by jphdotam** [comment]
Also, you may have the latest `tb-nightly` but you will wrongly get this error message if you're missing google's protobuf.

`conda install -c anaconda protobuf
conda install future`

Fixed it for me.

**Comment by visionscaper** [comment]
Next to `pip install tb-nightly`, I had to `pip install future`.

**Comment by ailearn007** [comment]
I think it's a version problem.
just run this:
`pip install tensorboard==1.14.0`
(not pip install tensorboard==1.14)

**Comment by Garithe** [comment]
I also face this while using ipthon kernal in jupyterlab(under anaconda). But when I use it in console of mac, it worked. No idea how to solve it.

**Comment by goudantongxue** [comment]
> Also, you may have the latest `tb-nightly` but you will wrongly get this error message if you're missing google's protobuf.
> 
> `conda install -c anaconda protobuf`
> `conda install future`
> 
> Fixed it for me.

How to install tb-nightly? i found conda don't have this command. Do I have to use pip install tb-nightly?

**Comment by CyanideBoy** [comment]
> I think it's a version problem.
> just run this:
> `pip install tensorboard==1.14.0`
> (not pip install tensorboard==1.14)

@naqute Does this work for gpu systems which are incompatible with tensorflow 1.14? My CUDA version won't support tf 1.14 :(

**Comment by naqute** [comment]
Sorry, my cuda is compatible with tf 1.14.0. I can not answer your question.



---Original---

**Comment by vtasStu** [comment]
> > tensorboard --logdir=runs
> > TensorBoard 1.14.0a20190504 at http://tian-ORC:6006/ (Press CTRL+C to quit)
> 
> It seems that you worked? If not, maybe this link https://www.endtoend.ai/pytorch-tensorboard may help you.

THX
