### ISSUE TITLE
TripletMarginLoss example isn't clear

### ISSUE THREAD

**Issue by PetroSokirniy** [pytorch/pytorch#20143]
## 📚 Documentation

The example in https://pytorch.org/docs/stable/nn.html#tripletmarginloss isn't very clear. It doesn't specify which input is the anchor, positive, and negative. 
Current:
>>> triplet_loss = nn.TripletMarginLoss(margin=1.0, p=2)
>>> input1 = torch.randn(100, 128, requires_grad=True)
>>> input2 = torch.randn(100, 128, requires_grad=True)
>>> input3 = torch.randn(100, 128, requires_grad=True)
>>> output = triplet_loss(input1, input2, input3)
>>> output.backward()

Proposed:
>>> triplet_loss = nn.TripletMarginLoss(margin=1.0, p=2)
>>> anchor = torch.randn(100, 128, requires_grad=True)
>>> positive = torch.randn(100, 128, requires_grad=True)
>>> negative = torch.randn(100, 128, requires_grad=True)
>>> output = triplet_loss(anchor, positive, negative)
>>> output.backward()

**Comment by SsnL** [comment]
Thanks! Feel free to submit a PR. We will gladly accept it.

**Comment by PetroSokirniy** [comment]
Cool, thank. Never committed to OSS before.
