### ISSUE TITLE
JIT scripted indexing with ellipsis and None is not working correctly

### ISSUE THREAD

**Issue by One-sixth** [pytorch/pytorch#20153]
## To Reproduce

1. use torch.chunk on torch.jit.script_method

```python
import torch

class BatchMod2(torch.jit.ScriptModule):
    def __init__(self, x_dim, z_dim):
        super().__init__()

    @torch.jit.script_method
    def forward(self, x, z):
        mean_scale = z.repeat(1, 2)
        mean, scale = torch.chunk(mean_scale[..., None, None], 2, 1)
        y = x * (scale + 1) + mean
        return y


b = BatchMod2(6, 6)
a1 = torch.ones(2,6,4,4)
a2 = torch.ones(2,6)
c=b(a1, a2)
```

## Expected behavior

No exception.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): win10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.1
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration:gtx970m
 - Any other relevant information:

## Additional context

When I comment @torch.jit.script_method, it can work normally.

**Comment by wanchaol** [comment]
after looking into it, I think it is because of different behaviors on `mean_scale[..., None, None]` for unsqueezing Nones between python and jit, they currently produce different shapes: python side provide `[2, 12, 1, 1]` but jit side provide `[2, 1, 1, 12]`, might be related to a uncovered edge case from #18615, @t-vi can you take a look on this?

**Comment by eellison** [comment]
Is it possible this is related ? https://github.com/pytorch/pytorch/issues/18616

**Comment by wanchaol** [comment]
@eellison I guess it's a slightly different issue, the one you mentioned is that we flattening the list index , which we shouldn't not to. This one is a different behavior mismatch when use None indexing and ellipsis syntax. Agree that we can reassign that one as well and these two issues might can be fixed together.

**Comment by t-vi** [comment]
Uh uh. I think it's ellipsis not being correctly handled. I'll try to figure it out.

**Comment by t-vi** [comment]
@One-sixth  Thank you for reporting this and providing a concise example. That really helps a lot tracking down these bugs!

**Comment by Chillee** [comment]
This is fixed by https://github.com/pytorch/pytorch/pull/22905.

**Comment by driazati** [comment]
Closing since your repro works fine on master / nightly
