### ISSUE TITLE
No module named _msvccompiler

### ISSUE THREAD

**Issue by liqima** [pytorch/pytorch#20155]
## ❓ Questions and Help
I tried to install caffe2 in Windows10, vs2017 following [this](https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile) and got this problem.
![image](https://user-images.githubusercontent.com/31846112/57220828-60b8ac00-702f-11e9-9cf8-12a952064f91.png)

does anyone known how to solve that?
thanks.

**Comment by peterjc123** [comment]
What is the version of your python executable?

**Comment by peterjc123** [comment]
Oh, I see. We don't support building with Python 2.7 on Windows so I don't think a fix is needed here.

**Comment by peterjc123** [comment]
But as a workground, you can take a look here as a reference: https://github.com/pytorch/pytorch/blob/v1.0.1/tools/setup_helpers/ninja_builder.py#L68.

**Comment by liqima** [comment]
> Oh, I see. We don't support building with Python 2.7 on Windows so I don't think a fix is needed here.

thanks very much!
