### ISSUE TITLE
What kind of cuda version needed for Ubuntu 18.04, and pytorch version

### ISSUE THREAD

**Issue by Kunlun-Zhu** [pytorch/pytorch#20167]
## ❓ Questions and Help
Cuda 10.1 seems not working
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by izdeby** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
