### ISSUE TITLE
Get error when do the backward:“RuntimeError: Tensor: invalid storage offset”?

### ISSUE THREAD

**Issue by voyager112** [pytorch/pytorch#20161]
When I use pytorch to do the backward grad, get error: 
`RuntimeError: Tensor: invalid storage offset at c:\users\administrator\downloads\new-builder\win-wheel\pytorch\aten\src\th\generic/THTensor.cpp:761`

and here are part of codes
```
H_grad = torch.autograd.grad(outputs=prediction.sum(), inputs=database_choose, create_graph=True)[0] Ht=H_grad[:,1].reshape(choose,1) Htt=torch.autograd.grad(outputs=Ht.sum(), inputs=database_choose,create_graph=True)[0][:,1].reshape(choose,1) 
loss.backward()
```

**Comment by izdeby** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
