### ISSUE TITLE
Tensor.__floordiv__ missing from pyi

### ISSUE THREAD

**Issue by bryant1410** [pytorch/pytorch#20178]
## 🐛 Bug

`Tensor.__floordiv__` is not provided in pyi files.

## To Reproduce

Divide 2 tensors (or a tensor and an int) with `//` in PyCharm.

**Comment by VitalyFedyunin** [comment]
We would gladly accept PR which is fixing it.

**Comment by bryant1410** [comment]
> We would gladly accept PR which is fixing it.

Can you point out which files should be changed, or give some guidance on the change for a PR author?

**Comment by VitalyFedyunin** [comment]
tools/pyi/gen_pyi.py and torch/__init__.pyi.in are good files to start
