### ISSUE TITLE
caffe2 Build error on windows

### ISSUE THREAD

**Issue by VirginianBlue** [pytorch/pytorch#20195]
Windows build of caffe2 fails. Errors in running build_windows.bat:
[1121/1204] Linking CXX executable bin\data_filler_test.exe
FAILED: bin/data_filler_test.exe
Cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=caffe2\CMakeFiles\data_filler_test.dir --manifests -- C:\PROGRA~2\ MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo caffe2\CMakeFiles\data_filler_test.dir\predictor\emulator\data_filler_test.cc.obj /out :bin\data_filler_test.exe /implib:lib\data_filler_test.lib /pdb:bin\data_filler_test.pdb /version:0.0 /INCREMENTAL:NO /subsystem:console lib\gtest_main.lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/try /pytorch/lib/caffe2.lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/try/pytorch/lib/caffe2_protos.lib lib\cpuinfo.lib lib\clog.lib lib\foxi_loader.lib -WHOLEARCHIVE:E:/opencv_build/ _caffe2_/try/pytorch/lib/onnx.lib lib\onnx_proto.lib lib\libprotobuf.lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/try/pytorch/lib/Caffe2_perfkernels_avx.lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/ Try/pytorch/lib/Caffe2_perfkernels_avx2.lib lib\c10.lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/try/pytorch/lib/C Affe2_perfkernels_avx512.lib lib\gtest.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "C:\PROGRA~2\MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo caffe2\CMakeFiles\data_filler_test.dir\ Predictor\emulator\data_filler_test.cc.obj /out:bin\data_filler_test.exe /implib:lib\data_filler_test.lib /pdb:bin\data_filler_test.pdb /version:0.0 /INCREMENTAL:NO /subsystem:console lib\gtest_main.lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/try/pytorch/lib/caffe2.lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/try/pytorch/lib/caffe2_protos.lib lib\cpuinfo.lib lib\clog.lib lib\ Foxi_loader.lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/try/pytorch/lib/onnx.lib lib\onnx_proto.lib lib\libprotobuf.lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/try/pytorch/lib/Caffe2_perfkernels_avx. Lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/try/pytorch/lib/Caffe2_perfkernels_avx2.lib lib\c10.lib -WHOLEARCHIVE:E:/opencv_build/_caffe2_/try/pytorch/lib/Caffe2_perfkernels_avx512.lib lib\gtest.lib kernel32 .lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib u Uid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:bin\data_filler_test.exe.manifest" failed (exit code 1120) with the following output:
LINK : warning LNK4098: The default library "MSVCRT" conflicts with the use of other libraries; please use /NODEFAULTLIB:library
Caffe2.lib(miniz.c.obj) : warning LNK4217: Locally defined symbol _localtime64_s is imported in function localtime_s
Caffe2.lib(miniz.c.obj) : warning LNK4217: Locally defined symbol _time64 is imported in function mz_zip_writer_add_mem_ex_v2
Caffe2.lib(miniz.c.obj) : warning LNK4217: Locally defined symbol _wassert is imported in function mz_zip_array_ensure_capacity
Caffe2.lib(miniz.c.obj) : warning LNK4217: Locally defined symbol free Imported in function miniz_def_free_func
Caffe2.lib(miniz.c.obj) : warning LNK4217: The locally defined symbol malloc is imported in the function miniz_def_alloc_func
Caffe2.lib(miniz.c.obj) : warning LNK4217: Locally defined symbol realloc is imported in function miniz_def_realloc_func
Caffe2.lib(miniz.c.obj) : error LNK2019: Unresolved external symbol __imp__mktime64, this symbol is referenced in function mktime
Bin\data_filler_test.exe : fatal error LNK1120: 1 external command that cannot be resolved
Ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "tools\build_libtorch.py", line 22, in <module>
    Build_python=False, rerun_cmake=True, build_dir='.')
  File "E:\opencv_build\_caffe2_\try\pytorch\tools\build_pytorch_libs.py", line 268, in build_caffe2
    Check_call(build_cmd, cwd=build_dir, env=my_env)
  File "C:\Users\84206\Anaconda3\lib\subprocess.py", line 311, in check_call
    Raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j' , '7']' returned non-zero exit status 1.
"Caffe2 building failed"

**Comment by peterjc123** [comment]
What flags did you set before build?

**Comment by peterjc123** [comment]
And btw, could you please share the ninja config file `ninja.build`?

**Comment by VirginianBlue** [comment]
> What flags did you set before build?

I just run build_windows.bat form source.And I didn't change anything.
My Environment:
OS (e.g., Linux): win10
Python version: python 3.6.4
CUDA/cuDNN version: CUDA 8.0
Any other relevant information: VS 2017

**Comment by VirginianBlue** [comment]
> And btw, could you please share the ninja config file `ninja.build`?

I can't find it , I'm sorry I don't know what's that thing

**Comment by peterjc123** [comment]
> > And btw, could you please share the ninja config file `ninja.build`?
> 
> I can't find it , I'm sorry I don't know what's that thing

It is usually in the build directory, that is, where you run the command. The reason I ask for it is that all the commands with the arguments could be seen there. 


> > What flags did you set before build?
> 
> I just run build_windows.bat form source.And I didn't change anything.
> My Environment:
> OS (e.g., Linux): win10
> Python version: python 3.6.4
> CUDA/cuDNN version: CUDA 8.0
> Any other relevant information: VS 2017

I don't think you can use CUDA 8.0 with VS 2017 14.16. You'll need to either set `CUDAHOSTCXX` to the compiler of VS 2015 Update 3 or updating CUDA to 10.0.

**Comment by peterjc123** [comment]
You have the same problem with #20420. So I'm going to close this one.

**Comment by wuwuzhijing** [comment]
Thank you
