### ISSUE TITLE
The JIT sometimes does not repeat values in the output_size argument.

### ISSUE THREAD

**Issue by skrah** [pytorch/pytorch#20215]
**Background**

This issue came up during the port of `adaptive_max_pool2d()` to `ATen`. The relevant function signature in `native_functions.yaml` is:

   `func: adaptive_max_pool2d(Tensor self, int[2] output_size) -> (Tensor, Tensor)`

**The issue**

When `output_size` is a single `int` on the Python level (square image H x H), `adaptive_max_pool2d()` receives an `output_size` argument with `output_size.size()==1` instead of `2`.

Currently `adaptive_max_pool2d()` has a workaround that also accepts `output_size.size()==1`  and repeats `H` inside the function.

**How to reproduce**

The cause is difficult to isolate since the tests are generated and quite complex. I think also a module export/import is involved.

1) Apply this diff:

```
diff --git a/aten/src/ATen/native/AdaptiveMaxPooling2d.cpp b/aten/src/ATen/native/AdaptiveMaxPooling2d.cpp
index b3b77c5..ec16c5e 100644
--- a/aten/src/ATen/native/AdaptiveMaxPooling2d.cpp
+++ b/aten/src/ATen/native/AdaptiveMaxPooling2d.cpp
@@ -322,6 +322,7 @@ std::tuple<Tensor, Tensor> adaptive_max_pool2d_cpu(
 {
   Tensor output = at::empty({0}, input.options());
   Tensor indices = at::empty({0}, input.options().dtype(kLong));
+  assert(output_size.size() == 2);
   adaptive_max_pool2d_out_cpu_template(
     output,
     indices,
```

2) Run the relevant test case:

`python3 -m pytest -v test_jit.py::TestJitGeneratedModule::test_nn_AdaptiveMaxPool2d_single`

**Backtrace**

```
(gdb) f 9
#9  0x00007fffcdeb2127 in torch::jit::(anonymous namespace)::<lambda(torch::jit::Stack&)>::operator()(torch::jit::Stack &) const (__closure=0x44ba5580, 
    stack=std::vector of length 2, capacity 2 = {...}) at /home/stefan/pytorch/torch/csrc/jit/generated/register_aten_ops_1.cpp:2948
2948              );
(gdb) f 8
#8  0x00007fffcde9aa4d in at::adaptive_max_pool2d (self=..., output_size=...) at /home/stefan/pytorch/build/aten/src/ATen/Functions.h:5728
5728        return detail::infer_type(self).adaptive_max_pool2d(self, output_size);
(gdb) p output_size.size()
$1 = 1
```

**Comment by skrah** [comment]
The test case that generates the error in `common_nn.py` is this one:

```
dict(
        module_name='AdaptiveMaxPool2d',
        constructor_args=(3,),
        input_fn=lambda: _rand_tensor_non_equal(1, 3, 5, 6),
        desc='single',
    ),
```

**Comment by ailzhang** [comment]
@skrah  I'm trying to understand the problem better, in this example we handle the `int` by https://github.com/pytorch/pytorch/blob/cb8ff2a2b4640fea1981ed2e00ebbc038485c216/aten/src/ATen/native/AdaptiveMaxPooling2d.cpp#L167, is it not the right way to do it?

**Comment by skrah** [comment]
@ailzhang I introduced that line during the port to `ATen` as a workaround.  Most other code in `ATen/native`, for example `adaptive_avg_pool2d()` does not allow `output_size.size() == 1` for the `2d` functions.

I heard from @ezyang that expansion to a list of repeated values should probably happen here:

https://github.com/pytorch/pytorch/blob/864cfbc2162a874fd67b50414205483cb9ac6b5d/torch/csrc/jit/script/schema_matching.cpp#L125

**Comment by ailzhang** [comment]
@skrah I see, that makes sense. I'll look into this tmr if no one with better context beats me on it :D
