### ISSUE TITLE
[jit] torch.tensor doesn't support list of tuples

### ISSUE THREAD

**Issue by TheCodez** [pytorch/pytorch#20230]
## 🐛 Bug

Cannot create a tensor using `torch.tensor` from a list of tuples.

## To Reproduce

```python
import torch

@torch.jit.script
def test():
  li = [(1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12)]
  return torch.tensor(li)
```

gives the following error:
```
RuntimeError: 
Input list to torch.tensor must be of ints, floats, or bools, got (int, int, int, int):
@torch.jit.script
def test():
  li = [(1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12)]
  return torch.tensor(li)
         ~~~~~~~~~~~~ <--- HERE
```

## Expected behavior

Should not give an error. Works in pure python.

## Environment
Pytorch 1.1.0

## Additional context

A workaround is to use a list of lists instead.

**Comment by eellison** [comment]
= low-pri, since `list(tup)` works.
