### ISSUE TITLE
[jit] add support for tuple unpacking in for loops

### ISSUE THREAD

**Issue by TheCodez** [pytorch/pytorch#20239]
## 🚀 Feature
Add support for tuple unpacking in for loops

## Motivation

Makes working with tuples a better experience and the code shorter. 

## Pitch

This should be possible:

```python
import torch

@torch.jit.script
def test():
  fm = [(64, 32), (32, 16), (16, 8)]
  
  for width, height in fm:
    pass
```

## Alternatives

A current workaround is to use:

```python
import torch

@torch.jit.script
def test():
  fm = [(64, 32), (32, 16), (16, 8)]
  
  for f in fm:
	width, height = f
    pass
```

**Comment by Krovatkin** [comment]
@wanchaol is this case going to be supported with your latest `Iterable` changes?

**Comment by wanchaol** [comment]
Yes this will be fixed.

**Comment by wanchaol** [comment]
This is already supported on master
