### ISSUE TITLE
[Feature Request] Add NoisyLinear layer

### ISSUE THREAD

**Issue by jvmncs** [pytorch/pytorch#2024]
An implementation of [Noisy Networks for Exploration](https://arxiv.org/abs/1706.10295).  I've written up a solution at [this gist](https://gist.github.com/jvmancuso/6f088cf8b08f0ce2347cc2db4d3351d2).  I only implemented it for linear layers because the authors used it that way in the paper.  I'll submit a pull request pending approval.

EDIT: Realized I need to add some details around resetting the noise. Hoping this gets some attention before I implement that.

**Comment by jvmancuso** [comment]
Realized I need to add some details around when to reset the noise.  I'll wait until the pull request stage to implement that part.

**Comment by Kaixhin** [comment]
Only just spotted this when browsing the PyTorch forums! I implemented a simple version just for my own needs [here](https://github.com/Kaixhin/NoisyNet-A3C/blob/master/model.py#L10-L37), but a properly designed layer would be nice. As you mentioned, I think picking new noise variables and setting them to 0 are pretty much the only things that you need to add. Perhaps you could have zero noise be triggered when calling `.eval()` and picking new noise when calling `.train()`, but definitely the ability to sample new noise variables needs to be available to the user.

**Comment by soumith** [comment]
if Noisy Networks are getting reasonable adoption, we're happy to merge this into core. The PR for this would need: code, docs, tests.

**Comment by Kaixhin** [comment]
@soumith They've only just appeared in one paper from DM and I'm not totally convinced of the results myself, so "reasonable adoption" might take a while yet. On the other hand, noisy linear layers are fairly generic layers and could see use in problems outside of RL.

**Comment by jvmancuso** [comment]
I'm planning on fixing this up tonight and adding methods for turning the noise off and for resampling the noise.  Will submit a PR once I'm done.

@Kaixhin I believe you mean having the noise variables set to one.  Thanks for the suggestion!

@soumith are there any resources I can look at that will help me build the docs/tests?

**Comment by Kaixhin** [comment]
@jvmancuso With analogy to VAEs, training involves injecting noise via µ + σε, but testing involves taking just the mean σ (which would be equivalent to setting ε to 0 rather than ε ~ N(0, 1)). Unless I'm missing something here, setting ε to 1 would result in adding a constant bias to the weight and bias matrices, which seems wrong, especially considering the expectation of the noise is 0. Either way, it'd be good to send your final implementation to Meire for confirmation.

**Comment by jvmancuso** [comment]
Ah, you're right! Thanks for clarifying. I'll definitely send it to him when it's done.

**Comment by Kaixhin** [comment]
I've had mixed luck replicating the work on Atari, but I know there are many differences between the Gym environments and how DM evaluate, so my findings are inconclusive.

@jvmancuso *her :) Although after looking at your code and the paper the logic for the layer itself seems fine, so it may not be worth sending it someone who doesn't use PyTorch. Once you send in a PR I'll comment further on the code itself.

**Comment by jvmancuso** [comment]
@Kaixhin *takes foot out of mouth* Thank you!

**Comment by gchanan** [comment]
> if Noisy Networks are getting reasonable adoption, we're happy to merge this into core. The PR for this would need: code, docs, tests.

didn't meet the reasonable adoption threshold.
