### ISSUE TITLE
[FR] nn.Module.requires_grad_()

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#20241]
Useful in finetuning, gan training, etc. :)

**Comment by gchanan** [comment]
wait, when do you turn off requires_grad in Modules?

**Comment by SsnL** [comment]
@gchanan freezing modules in finetuning and modular training (e.g. GANs, training each part individually before end-to-end training).

**Comment by SsnL** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/22576#event-2467173622
