### ISSUE TITLE
Cumulative Maximum

### ISSUE THREAD

**Issue by cannon** [pytorch/pytorch#20240]
## 🚀 Feature
Add cumulative maximum for tensors, where each element along an axis is the max of it and everything before it.

## Motivation
This is useful for evaluating mAP by creating precision-recall curves, where precision should be monotonically decreasing with respect to recall. More info: https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173

## Pitch
Torch has .cumsum and .cumprod so I suggest .cummax to be added.

## Alternatives
Numpy supports this with `np.maximum.accumulate()`, so we have to convert to numpy then back.

**Comment by VitalyFedyunin** [comment]
Thank you for the meaningful suggestion. We will try to allocate resources to implement this functionality. Also, we are glad to accept PR which implements this operator.

**Comment by kamathhrishi** [comment]
> Thank you for the meaningful suggestion. We will try to allocate resources to implement this functionality. Also, we are glad to accept PR which implements this operator.

Awesome, I would like to implement this but I am not finding the existing implementation of cumprod and cumsum just to have an understanding of how cummax could follow the standards of PyTorch.

Thank you.

**Comment by fmassa** [comment]
@kamathhrishi they are currently implemented in our legacy library TH / THC, you can find them in https://github.com/pytorch/pytorch/blob/163f0e182c7e092d6b61600e3a5e20347abab848/aten/src/TH/generic/THTensorMoreMath.cpp#L369-L401
for CPU and
https://github.com/pytorch/pytorch/blob/163f0e182c7e092d6b61600e3a5e20347abab848/aten/src/THC/generic/THCTensorMathScan.cu#L108-L120
for CUDA

**Comment by kamathhrishi** [comment]
@fmassa thank you :) I have began working on this. Expect a pr soon.

**Comment by kamathhrishi** [comment]
@fmassa Should I add tests for it? Where are the tests for cumsum and cumprod located?

**Comment by fmassa** [comment]
I would say `cummax`, but it does look weird.

Tests are in `tests/test_tensor.py` or `tests/test_torch py` cant remember the exact one right now

**Comment by kamathhrishi** [comment]
@fmassa tests/test_tensor.py it is. This is my first time contributing to Pytorch so there might be things I might miss out on. Do you think its a good idea to create a draft PR to see if I am going in the right direction?

**Comment by fmassa** [comment]
In general, I'd try first to manage to compile pytorch from source. This should be easy but is a necessary first step.

Note that part of this task requires having a GPU to compile / test the CUDA parts -- this might be difficult to do without access to a GPU.

If you are unsure of some parts of the implementation, just let us know.
I'd ideally open a PR once at least the CPU parts are working.

**Comment by yifuwang** [comment]
I'm interested in working on this. @kamathhrishi are you currently working on it?

**Comment by kamathhrishi** [comment]
@yiruwang yep I am working on this. Just jage a bit more to go.

**Comment by kamathhrishi** [comment]
@yifuwang If you would like to go for it, go ahead. I did begin this pr but then I don't think I will have the time to complete it. If you have any questions or need to know about the progress I have made you can let me know.

**Comment by ashukid** [comment]
@yifuwang are you working on this. If not I'd like to take on this one. Let me know.

**Comment by yifuwang** [comment]
@ashukid no I'm not. Go ahead :)

**Comment by ashukid** [comment]
@kamathhrishi can you tell me what progress you made and where did you get stuck.

**Comment by kamathhrishi** [comment]
@ashukid Basically I did almost the same things cumprod and cumsum did and the required differences. I am not exactly stuck , I don't have the time to complete the PR right now.  If you would like I can push my changes to my repo and you can have a look at it or we can make a joint PR if you like.

**Comment by kamathhrishi** [comment]
Here it is https://github.com/pytorch/pytorch/compare/master...kamathhrishi:master

**Comment by shaz13** [comment]
I want to work on this issue. Should I feel free to push a PR? Thanks!

**Comment by ashukid** [comment]
Yea go ahead. I'm not working on it as of now !

**Comment by pdlive215** [comment]
I'm interested in taking this issue. @fmassa, you noted that `cumsum` and `cumprod` are implemented in the legacy libraries `TH` and `THC`. Should we similarly implement `cummax` in these libraries, or should we implement it in one of the `ATen/native` `.cpp` files? If the latter, should we also implement `cumsum` and `cumprod` natively? I see both `cumsum` and `cumprod` in `native_functions.yaml` and `ReduceOps.cpp`, but some of the `cumsum` and `cumprod` functions in `ReduceOps.cpp` return legacy implementations.

**Comment by agadetsky** [comment]
@pdlive215 do you have any progress?

**Comment by pdlive215** [comment]
@agadetsky I hadn't worked on it since I wasn't sure if this should be implemented in `TH` or `ATen`. However, after consulting [Issue 24507](https://github.com/pytorch/pytorch/issues/24507) I'm pretty sure we'd want to implement `cummax` natively. I can start working on this in the next day or two, though I'm happy to let you take it.

**Comment by agadetsky** [comment]
@pdlive215 Oh, I can't do it, but need it. Will be waiting PR from you!

**Comment by naiveHobo** [comment]
Can I have a go at this one?

**Comment by agadetsky** [comment]
@naiveHobo everyone will be happy if you will do it. Also we can create associated PR with `logcumsumexp` function, it needs `cummax`.

**Comment by igorsyl** [comment]
@agadetsky Here's a proposed commit, however I'm not sure how to write the backward operation. https://github.com/pytorch/pytorch/commit/46cf977d50bed4dcc1bd1a93dbc98f23b6ac7ce2

**Comment by agadetsky** [comment]
@igorsyl Thank you! Can you create PR? I can't find it if you have already did it. About gradient, I think it should be implemented in the same way as for `max`, when we propagate only current maximum (see https://discuss.pytorch.org/t/confused-about-torch-max-and-gradient/14283/7, https://stackoverflow.com/questions/53539348/what-is-the-backward-process-of-max-operation-in-deep-learning).

**Comment by igorsyl** [comment]
@agadetsky https://github.com/pytorch/pytorch/pull/26637  Still convincing myself if backward op is correct.

**Comment by agadetsky** [comment]
@igorsyl thank you! Try to check it numerically with `torch.autograd.gradcheck`. Don't forget to use `torch.DoubleTensor` precision when checking.

**Comment by agadetsky** [comment]
@igorsyl do you have any updates?

**Comment by pandeykartikey** [comment]
Hi, If nobody is working on this issue I would like to take this up along with (#26411).

**Comment by agadetsky** [comment]
@pandeykartikey hi, do you have any progress?

**Comment by pandeykartikey** [comment]
@agadetsky I was going through the codebase meanwhile the issue was assigned to me. I will try to make a PR by the end of this week.(Assuming this has been assigned to me now.)

**Comment by pandeykartikey** [comment]
@agadetsky I think @anjali411 has already made a PR for it #30881

**Comment by agadetsky** [comment]
@pandeykartikey nice! And what about https://github.com/pytorch/pytorch/issues/26411?

**Comment by pandeykartikey** [comment]
Actually, I was going to work on that after this. But as this issue already has an associated PR. I will shift my focus to #26411. 
Shall I self-assign that issue to myself?

**Comment by agadetsky** [comment]
@pandeykartikey I think you can, last message from previous worker was in November, it is unlikely that he is still working

**Comment by ngimel** [comment]
cummin and cummax are implemented.

**Comment by gmichaeljaison** [comment]
Which PyTorch version will this land on?

**Comment by ngimel** [comment]
It is available in nightlies and will be in 1.5.
