### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_trilinear3d

### ISSUE THREAD

**Issue by yxchng** [pytorch/pytorch#20257]
Currently I am facing the error

`
RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_trilinear3d
`

According to the folks at ONNX, this is a bug in PyTorch. https://github.com/onnx/onnx/issues/1999

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by VitalyFedyunin** [comment]
cc @houseroad

**Comment by junwenwu** [comment]
any update on this?

**Comment by spandantiwari** [comment]
Can you please provide the repro steps.

**Comment by garymm** [comment]
Closing due to lack of response from @yxchng . If you still need help, please provide reproduction instructions, ideally runnable in Colab.
