### ISSUE TITLE
tensor.cuda() method errors out in multi-thread dataloader

### ISSUE THREAD

**Issue by JC-S** [pytorch/pytorch#20260]
## 🐛 Bug

I was trying to use GPU for some heavy-lifting pro-processing work so I wrote my own transform function.
The tranform function keeps throwing 'RuntimeError: CUDA error: initialization error' whenever I use num_worker > 0.
The error happens at the line when I try to send tensor to GPU using tensor.cuda()

## To Reproduce

1. Write a customized transform function.
2. Use .cuda() method within.
3. Use num_worker >0.

## Environment

pytorch == 1.1.0 stable
torchvision == 0.2.2.post3
CUDA == 10.0.130
cuDNN == 7501

**Comment by soumith** [comment]
please read the note https://pytorch.org/docs/stable/notes/multiprocessing.html#sharing-cuda-tensors

relevant section:

```
Sharing CUDA tensors between processes is supported only in Python 3, using a spawn or forkserver start methods. multiprocessing in Python 2 can only create subprocesses using fork, and it’s not supported by the CUDA runtime.
```

Basically, add 

```
if __name__ == '__main__':
    torch.multiprocessing.set_start_method('spawn')
```
right at the top of your main script.

Does that help?

**Comment by JC-S** [comment]
> please read the note https://pytorch.org/docs/stable/notes/multiprocessing.html#sharing-cuda-tensors
> 
> relevant section:
> 
> ```
> Sharing CUDA tensors between processes is supported only in Python 3, using a spawn or forkserver start methods. multiprocessing in Python 2 can only create subprocesses using fork, and it’s not supported by the CUDA runtime.
> ```
> 
> Basically, add
> 
> ```
> if __name__ == '__main__':
>     torch.multiprocessing.set_start_method('spawn')
> ```
> 
> right at the top of your main script.
> 
> Does that help?

That did solve the problem. Thanks so much for your timely reply and hope you sleep well :)
