### ISSUE TITLE
Remove static variable definitions to support libtorch dlls delayed loading

### ISSUE THREAD

**Issue by yelu** [pytorch/pytorch#20264]
## 🚀 Feature

Remove static variable definitions to support delayed loading libtorch dlls.

## Motivation
Some dlls required by libtorch are quite big. So when embeding libtorch into a product, we want them to be optional if the user doesn't use any functionalities in libtorch. Users need to have those dlls only when they need libtorch. To achieve the goal, we usually use delayed loading feature(/delayed switch with MSBuild on Win, and there are equivalents on Linux too). 

However, source code of libtorch contains some static definations, e.g.

```C++
#include <torch/csrc/jit/import.h>
...
static script::ExtraFilesMap default_extra_files;
...
```

This will stop the delayed loading to work, even when the user doesn't call any functions in torch explicitly.

Is it possible to find alternatives to remove those static/global variable definitions?

**Comment by zou3519** [comment]
How does a static variable stop delayed loading from working?

**Comment by yf225** [comment]
@peterjc123 Do you have insights on how static variables can stop delayed loading from working on Windows?

**Comment by fmassa** [comment]
We would be willing to accept PRs adding support for this functionality, if it doesn't add overheads or downsides. @peterjc123  what do you think?

**Comment by peterjc123** [comment]
Are you talking about `/DELAYLOAD` in `link.exe`? I didn't find static definitions to be the block of the delay loading feature in the MSDN document. https://docs.microsoft.com/en-us/cpp/build/reference/constraints-of-delay-loading-dlls?view=vs-2019

**Comment by peterjc123** [comment]
I've created one VS 2017 project for validating this idea. [TestDelayLoad.zip](https://github.com/pytorch/pytorch/files/3175925/TestDelayLoad.zip) And from the `Output` part, you can see that the DLL that contains the static definition is actually delay loaded.
Here is my log:
```
'TestDelayLoad.exe' (Win32): Loaded 'TestDelayLoad\x64\Release\TestDelayLoad.exe'. Symbols loaded.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Cannot find or open the PDB file.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
The thread 0x11b0 has exited with code 0 (0x0).
'TestDelayLoad.exe' (Win32): Loaded 'TestDelayLoad\x64\Release\TestDelayLoadLib.dll'. Symbols loaded.
'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
The thread 0x78c has exited with code 0 (0x0).
The thread 0x38c4 has exited with code 0 (0x0).
The program '[21812] TestDelayLoad.exe' has exited with code 0 (0x0).
```

**Comment by yelu** [comment]
> I've created one VS 2017 project for validating this idea. [TestDelayLoad.zip](https://github.com/pytorch/pytorch/files/3175925/TestDelayLoad.zip)
> From the `Output` part, you can see that the DLL that contains the static definition is actually delay loaded.
> Here is my log:
> 
> ```
> 'TestDelayLoad.exe' (Win32): Loaded 'TestDelayLoad\x64\Release\TestDelayLoad.exe'. Symbols loaded.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Cannot find or open the PDB file.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
> The thread 0x11b0 has exited with code 0 (0x0).
> // after pressing any key
> 'TestDelayLoad.exe' (Win32): Loaded 'TestDelayLoad\x64\Release\TestDelayLoadLib.dll'. Symbols loaded.
> 'TestDelayLoad.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
> The thread 0x78c has exited with code 0 (0x0).
> The thread 0x38c4 has exited with code 0 (0x0).
> The program '[21812] TestDelayLoad.exe' has exited with code 0 (0x0).
> ```

This could be closed. Thanks for the detailed test. I thought the entry dll was torch.dll, but they were caffe2.dll/c10.dll. After I set them to be delayed, the issue was gone.

BTW, the test above doesn't imply static global variables in headers are not a problem for delay loading. For pod types, it is fine. But for a class, it may bring side effect.

```C++
extern test();

class A
{
    public:
        A(){ test(); }
}

static A a;
```
