### ISSUE TITLE
Memory (CPU/sys) leak with custom batch norm layer

### ISSUE THREAD

**Issue by MatthiasKohl** [pytorch/pytorch#20275]
## 🐛 Bug

Unreasonable memory increase (probably memory leak) while training a simple CNN with a custom mean-only batch-norm layer on GPU. This is probably related to the module buffer, since removing the buffer stops the problem and training on CPU also seems to work fine.

## To Reproduce

1. Evaluate script below while monitoring CPU memory usage

```python
import torch
import torch.nn as nn

class MeanOnlyBatchNorm(nn.Module):
    def __init__(self, module, momentum=0.1):
        super(MeanOnlyBatchNorm, self).__init__()
        if isinstance(module, nn.Linear):
            self.num_features = module.out_features
        else:
            self.num_features = module.out_channels
        self.do_init = False
        self.momentum = momentum
        self.weight = nn.Parameter(torch.Tensor(self.num_features))
        self.bias = nn.Parameter(torch.Tensor(self.num_features))
        self.register_buffer('running_mean', torch.zeros(self.num_features))
        self.reset_parameters()

    def reset_running_stats(self):
        self.running_mean.zero_()

    def reset_parameters(self):
        self.reset_running_stats()
        nn.init.ones_(self.weight)
        nn.init.zeros_(self.bias)
        self.do_init = False

    def forward(self, x):
        exp_dim = (None, slice(None)) + tuple(None for _ in range(2, x.dim()))
        if self.training:
            red_dim = (0,) + tuple(range(2, x.dim()))
            mean = x.mean(red_dim)
            activation = x - mean[exp_dim]
            self.running_mean = (self.momentum * mean +
                                 (1 - self.momentum) * self.running_mean)
        else:
            activation = x - self.running_mean[exp_dim]

        return activation + self.bias[exp_dim]

    def extra_repr(self):
        return '{num_features}, eps={eps}, momentum={momentum}, affine=True, ' \
               'track_running_stats=True'.format(**self.__dict__)


n_class = 10
batch_size = 100
n_batches = 2000
input_size = (3, 32, 32)
device = torch.device('cuda')
c1 = nn.Conv2d(3, 1000, kernel_size=3, padding=1, stride=4)
bn1 = MeanOnlyBatchNorm(c1)
act1 = nn.ReLU(True)
pool1 = nn.AdaptiveAvgPool2d(1)
n2 = nn.Conv2d(1000, n_class, kernel_size=1)
bn2 = MeanOnlyBatchNorm(n2)
m = nn.Sequential(c1, bn1, act1, pool1, n2, bn2).to(device)
optimizer = torch.optim.Adam(m.parameters())
for _ in range(n_batches):
    t = torch.randn(*((batch_size,) + input_size), device=device)
    x = m(t).view(batch_size, -1)
    loss = torch.nn.functional.cross_entropy(
        x, torch.randint(n_class, (batch_size,), dtype=torch.long,
                         device=device))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
```

EDIT: was able to reproduce with a much smaller example, simplified the script above.

## Expected behavior

There should be no memory leak, just like when training on CPU, or using the `_BatchNorm` modules.

## Environment
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.3
[pip] torch==1.1.0
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl_fft                   1.0.12           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchvision               0.2.2                      py_3    pytorch

## Additional context

To create the `MeanOnlyBatchNorm` layer, I followed more or less what is done here: https://github.com/ptrblck/pytorch_misc/blob/master/batch_norm_manual.py and of course the `_BatchNorm` module.

**Comment by MatthiasKohl** [comment]
I assume that a graph with `self.running_mean` (from the custom batch norm) is retained somehow, which is why the leak is on CPU but I don't really understand why

**Comment by VitalyFedyunin** [comment]
Have you tried to run it for a while? CUDA tensors are using caching allocator which might lead to the eventual memory fragmentation. It should not be noticeable on longer runs.

**Comment by MatthiasKohl** [comment]
It seems like I was able to fix this problem by updating the `self.running_mean` buffer like this:

```python
self.running_mean.mul_(1 - self.momentum).add_(mean.detach() * self.momentum)
```

The important thing is to detach the incoming variable from the graph when applying it to the buffer. I'm still unsure about this though.
Isn't the whole point of buffers vs. parameters that buffers are not supposed to have a graph, so why is one kept here ?
And if the buffer is kept in the graph for the incoming variable, why is it not free'd after the `backward` (I don't retain any graph here, at least I don't want to...)

Also, @ptrblck : the script linked above ([and here](https://github.com/ptrblck/pytorch_misc/blob/master/batch_norm_manual.py)) probably has this issue as well. Maybe not that important in your use case, but might be good to know.

**Comment by MatthiasKohl** [comment]
@VitalyFedyunin : in my toy example, you can just increase the number of batches. It allocates ~7MB per second. That's crazy, I wouldn't expect that from memory fragmentation.

In fact, I ran a larger thing using this custom batch norm long enough (during the night) to go out of memory on the full system (something like 64GB RAM)

**Comment by SsnL** [comment]
Yeah, that `running_mean` update is exactly your problem. You keep extending the graph.

**Comment by ptrblck** [comment]
@MatthiasKohl Thanks for letting me know the bug is still in the code. We've had this issue already in the discussion board, but apparently I've forgotten to fix it in the repo.

**Comment by MatthiasKohl** [comment]
Thank you for your help guys. Even though it was quite surprising to me when I saw it, I understand this is expected behavior, so I'll close the issue.

Just a final question: is there a way here to have the buffer not be part of the graph (maybe with something like `torch.no_grad()` instead of detaching from the graph) ?
I ask this because in some functions, it can be a bit hard to tell which tensor is part of the graph and which is not. So if I could just have a general rule like "use 'torch.no_grad()` when updating the buffer", it would make it easier for me.

**Comment by ptrblck** [comment]
@MatthiasKohl That should also work as it was the solution to the [aforementioned issue](https://discuss.pytorch.org/t/how-does-batchnorm-keeps-track-of-running-mean/40084/16?u=ptrblck).
