### ISSUE TITLE
the capacity of memory when compiling pytorch from source

### ISSUE THREAD

**Issue by kealennieh** [pytorch/pytorch#20296]
how large the capacity of memory is needed when compiling pytorch from source ?

I've got about 5GB available when compiling in ubuntu 18.04.  Each time I compile with **python setup.py install**, the compiling program will occupy all the capacity of memory. Then my screen is stuck. After a while,  the screen becomes dark and my laptop reboots.... 

Is there any way to setup some parameters to use less memory when compiling ? Many thanks.

**Comment by ezyang** [comment]
One thing to try is reduce the parallelism of the build. This can be done by setting `MAX_JOBS=1`, for example.

**Comment by kealennieh** [comment]
Sorry.  MAX_JOBS=1 doesn't work out. I've set "export MAX_JOBS=1" in shell, before typing "python setup.py install".  Still, out of memoy. 
I've even changed all the "MAX_JOBS" parameters in the project to 1. However, it doesn't work out.  

And **I've found that there were many "cicc" and "cc1plus" commands when I used top command in shell**. So I think "MAX_JOBS" cannot reduce the number of threads used to build the project.

**Comment by ezyang** [comment]
Hmm. Can you post your compile log? Here's the logic which handles `MAX_JOBS`

```
def build_caffe2(version,
                 cmake_python_library,
                 build_python,
                 rerun_cmake,
                 build_dir):
    my_env = create_build_env()
    build_test = not check_negative_env_flag('BUILD_TEST')
    max_jobs = os.getenv('MAX_JOBS', None)
    cmake_cache_file = 'build/CMakeCache.txt'
    if rerun_cmake and os.path.isfile(cmake_cache_file):
        os.remove(cmake_cache_file)
    if not os.path.exists(cmake_cache_file) or (USE_NINJA and not os.path.exists('build/build.ninja')):
        run_cmake(version,
                  cmake_python_library,
                  build_python,
                  build_test,
                  build_dir,
                  my_env)
    if IS_WINDOWS:
        build_cmd = ['cmake', '--build', '.', '--target', 'install', '--config', build_type, '--']
        if USE_NINJA:
            # sccache will fail if all cores are used for compiling
            j = max(1, multiprocessing.cpu_count() - 1)
            if max_jobs is not None:
                j = min(int(max_jobs), j)
            build_cmd += ['-j', str(j)]
            check_call(build_cmd, cwd=build_dir, env=my_env)
        else:
            j = max_jobs or str(multiprocessing.cpu_count())
            build_cmd += ['/maxcpucount:{}'.format(j)]
            check_call(build_cmd, cwd=build_dir, env=my_env)
    else:
        if USE_NINJA:
            ninja_cmd = ['ninja', 'install']
            if max_jobs is not None:
                ninja_cmd += ['-j', max_jobs]
            check_call(ninja_cmd, cwd=build_dir, env=my_env)
        else:
            max_jobs = max_jobs or str(multiprocessing.cpu_count())
            check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
```

So what I am expecting to see is a call to ninja/make with `-j 1`.
