### ISSUE TITLE
What’s the difference between the two hypothesis?

### ISSUE THREAD

**Issue by taylover-pei** [pytorch/pytorch#20314]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Resnet has a 4 component: layer1, layer2, layer3, layer4.

Hypothesis one：
And I initialize the layer4 use the same parameters, just like this:
**self.layer4_1 = model_resnet.layer4
self.layer4_2 = model_resnet.layer4**
That means the layer4_1 and layer4_2 pointing to the same parameters, they share the same parameter. I update them alternately.

Hypothesis two：
I just define one layer4 just like this:
**self.layer4 = model_resnet.layer4**
And I update the layer4 two times than Hypothesis one.

![image](https://user-images.githubusercontent.com/27360803/57441996-a4085a00-727d-11e9-961a-414e6c069b9c.png)

In hypothesis 1/top image, the layer4_1 and layer4_2 share the same parameters, which is the same in layer4 in hypothesis 2/down image.

I update layer4_1 and layer4_2 alternatively in hypothesis 1/top image and I update layer4 in hypothesis 2/down image twice to get the the amount of updates compared to hypothesis 1.

And I promise the data are all the same.

I want to ask what’s the difference between the two hypothesis？**Why are the model results different when the model converges？**

My English is poor, if you are chinese, we can talk in chinese.

Looking forward to your reply!!

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
