### ISSUE TITLE
What is the meaning of such a formula in some functions

### ISSUE THREAD

**Issue by heslowen** [pytorch/pytorch#20316]
## 📚 Documentation
What is the meaning of such a formula in some functions？ Just like the formula in the following picture
math::
        v = \frac{v}{\max(\lVert v \rVert_p, \epsilon)}.
![image](https://user-images.githubusercontent.com/22348625/57455073-e8efb900-729c-11e9-895f-588ec050ed4b.png)
Is my chrome lack of some Plug-ins so they can not show correctly??

**Comment by SsnL** [comment]
It's the latex that specifies the math function this API is performing.
