### ISSUE TITLE
Libtorch error in header file

### ISSUE THREAD

**Issue by pedromorais17** [pytorch/pytorch#20326]
I'm creating a class with libtorch members. While including "`#include <torch/script.h>`" into the header, I'm getting the following error:

`1>c:\code\externallibraries\libtorch_cuda10_debug\libtorch\include\aten\core\ivalue.h(713): error C2334: unexpected token(s) preceding '{'; skipping apparent function body (compiling source file GeneratedFiles\Release\moc_ImageProcessingInterface.cpp)`

If I put the include into the cpp part, no compilation error is found. Any suggestion?

Thank you in advance.

**Comment by peterjc123** [comment]
Would you please tell me which line does it exactly point to?

**Comment by peterjc123** [comment]
Also would you tell me which version are you using?

**Comment by pedromorais17** [comment]
@peterjc123  I'm using pytorch 1.1, Visual Studio 2017, Windows 10, Cuda 10.

I have a class termed ImageProcessingInterface. 

When I include "#include <torch/script.h>" in my header I get the abovementioned error message. If I include in the cpp of the class, it works ok. Nevertheless, I need to create some torch members in my class, so I need to include it in my header.

```
#include <torch/script.h>

#include <vector>
#include <algorithm>
#include <array>

#include <opencv2/opencv.hpp>
#include <opencv2/core/hal/interface.h>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/cudaarithm.hpp>

// itk
#include <DijkstraBinaryImage.h>
#include <itkOpenCVImageBridge.h>

class ImageProcessingInterface : public QMainWindow
{
	Q_OBJECT

...
}
```

**Comment by Pipoderoso** [comment]
I think #19405 may help you

**Comment by pedromorais17** [comment]
Indeed, the problem is compatibility with QT. This issue was solved.

**Comment by arnaublanco** [comment]
how did you solve it?
