### ISSUE TITLE
CUDA too slow

### ISSUE THREAD

**Issue by pedromorais17** [pytorch/pytorch#20338]
Hi all,

I'm working with libtorch (pytorch build 1.1) in Visual Studio 2017, Windows 10, NVIDIA Quadro P2000. Hi started by creating an initial model in python. My forward stage required 50 ms (in python with GPU). When moving to C++ (with GPU), I registered a similar result (approximately 50 ms). Then, I moved for a simple network (the original originated a .pt file of approximately 60 mb, and the last one created a file with 3 mb). In python, the forward stage required 10 ms, but in C++ it took 40 ms. I noticed that the model load was much faster (which is logic since the file is small now). I was not waiting for this result. Do you any suggestion? I also tested with the recent nightly version of pytorch, but the forward took 80 ms in C++ (really strange).  

I'm using CUDA 10 and CUDNN7.1. 

Thank you in advance.

**Comment by zou3519** [comment]
Could you provide some more information about what is in your model?

**Comment by pedromorais17** [comment]
I think that I found the problem. Basically, I created a simple C++ code with a for-cycle to repeat the following instruction several times and get the times:

for each index of the cycle, I start by:
1 - read image
2 - transform to gpu tensor
3 - read the model using torch::jit::load
4 - start timer
5 - get output tensor through module-forward(input).toTensor;
6 - end timer
7 - convert data to c++

When performing this strategy, I did not notice any time difference when reducing the complexity of the network. However, I found that the problem was the continuous load of the module (step 3). Indeed, with the abovementioned strategy, my network was slow that python implementation (which is not logic). If I remove step 3 from the for-cycle, the method is much faster (5x times faster). The continuous load of the model highly influence the performance of the GPU. 

Moreover, I noticed another strange behavior. I compiled the pytorch from the source. However, by directly compiling it to my own architecture is slightly slower than the prebuilt-files available in pytorch website. That is not expected, I found other topics reporting the opposite. Possibly I failed on step while performing the cmake of the project, I used the default configurations with CUDA 10.0 and OpenCV. Do you have any idea about this problem.

**Comment by soumith** [comment]
yea, that's probably because your weights are being evicted from cache and they have to be reloaded?
