### ISSUE TITLE
libtorch problem on windows: fatBinaryCtl_CreateHandle

### ISSUE THREAD

**Issue by zhuqiang00099** [pytorch/pytorch#20350]
## Environment
- libtorch version win-cu90-1.1.0
- cuda-driver 10.1
- gpu devices GTX1080 and RTX2070 (on one computer)

## Description
on gtx1080, the trace-model can be loaded through jit, but an error occurs on rtx2070,it says  fatBinaryCtl_CreateHandle can not be located on C:\WINDOWS\system32\nvcuda.dll. I have tested successfully on notebooks with GTX1060,GTX965M,GTX920M,GTX960M,GTX940MX. The issue looks like has something to do with the cuda-driver  or the new RTX card ?

any device or help ? thank you.

**Comment by peterjc123** [comment]
`nvcuda.dll` is managed by your GPU driver. Please keep them constant between devices.

**Comment by peterjc123** [comment]
Wait, I just noticed you are using CUDA 9.0 binaries for RTX cards. I'm afraid you 'll have to use the CUDA 10.0 one instead.

**Comment by zhuqiang00099** [comment]
Yes ..cuda10 works ...
