### ISSUE TITLE
undefined symbol: THLongStorage_inferSizeN

### ISSUE THREAD

**Issue by metalbubble** [pytorch/pytorch#2036]
Installed from the source. When I import torch, I got 

importError: anaconda2/lib/python2.7/site-packages/torch/lib/libTHC.so.1: undefined symbol: THLongStorage_inferSizeN

**Comment by metalbubble** [comment]
linux 14.04, cuda8, cudnn6.

**Comment by ywu36** [comment]
Same problem, install from source.
Ubuntu 14.04, cuda8, cudnn5.1

**Comment by soumith** [comment]
This is so weird, I cant reproduce this in a single machine.

@metalbubble 

Can you tell me the output of:

```
ldd anaconda2/lib/python2.7/site-packages/torch/lib/libTHC.so.1
```

**Comment by ywu36** [comment]
linux-vdso.so.1 =>  (0x00007ffce03fe000)
	libcudart.so.8.0 => /home/yuhang/anaconda2/lib/python2.7/site-packages/torch/lib/libcudart.so.8.0 (0x00007fc3bb8a0000)
	libcublas.so.8.0 => /home/yuhang/anaconda2/lib/python2.7/site-packages/torch/lib/libcublas.so.8.0 (0x00007fc3b8e04000)
	libTH.so.1 => /home/yuhang/anaconda2/lib/python2.7/site-packages/torch/lib/libTH.so.1 (0x00007fc3b8826000)
	libcurand.so.8.0 => /home/yuhang/anaconda2/lib/python2.7/site-packages/torch/lib/libcurand.so.8.0 (0x00007fc3b48af000)
	libcusparse.so.8.0 => /home/yuhang/anaconda2/lib/python2.7/site-packages/torch/lib/libcusparse.so.8.0 (0x00007fc3b1d8e000)
	libstdc++.so.6 => /home/yuhang/anaconda2/lib/libstdc++.so.6 (0x00007fc3b1a78000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc3b1747000)
	libgcc_s.so.1 => /home/yuhang/anaconda2/lib/libgcc_s.so.1 (0x00007fc3b1530000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc3b1167000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f59c6b6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc3b0f62000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc3b0d44000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc3b0b3c000)
	libmkl_intel_lp64.so => /home/yuhang/anaconda2/lib/libmkl_intel_lp64.so (0x00007fc3b0104000)
	libmkl_intel_thread.so => /home/yuhang/anaconda2/lib/libmkl_intel_thread.so (0x00007fc3ae63f000)
	libmkl_core.so => /home/yuhang/anaconda2/lib/libmkl_core.so (0x00007fc3acb0d000)
	libiomp5.so => /home/yuhang/anaconda2/lib/libiomp5.so (0x00007fc3ac762000)
	libgomp.so.1 => /home/yuhang/anaconda2/lib/libgomp.so.1 (0x00007fc3ac553000)

**Comment by soumith** [comment]
okay, what is output of:

```
nm /home/yuhang/anaconda2/lib/python2.7/site-packages/torch/lib/libTH.so.1 | grep THLongStorage_infer
```

**Comment by ywu36** [comment]
@soumith 
0000000000036c80 T THLongStorage_inferExpandGeometry
0000000000036820 T THLongStorage_inferSize2
0000000000036a00 T THLongStorage_inferSizeN

**Comment by soumith** [comment]
weird, this symbol is right there. I dont know why THC cant find it.
Does your LD_LIBRARY_PATH have another `libTH.so.1` somewhere? maybe an old version?

**Comment by ywu36** [comment]
Here is the results of running: 'locate libTH.so.1'
/home/yuhang/anaconda2/lib/python2.7/site-packages/torch/lib/libTH.so.1
/home/yuhang/anaconda2/pkgs/pytorch-0.1.9-py27_2/lib/python2.7/site-packages/torch/lib/libTH.so.1

I previously have Pytorch installed. I upgrade my CUDA and CuDNN, try to reinstall the Pytorch from source again then got the errror. 

I first tried to install the Pytorch from conda first, got a torch ._C error, then I decide to install it from source. Then, I got this error.

Do I need to remove 'pytorch-0.1.9-py27_2‘　?

**Comment by soumith** [comment]
Run these commands: 
```
conda uninstall -y pytorch
pip uninstall torch
pip uninstall torch # yes run this twice
```

Then reinstall pytorch from source.
Let me know if this works.

**Comment by ywu36** [comment]
@soumith 
After tried and failures several times, I deleted and reinstalled Anaconda2 and the problem solved. I guess it was caused by an incomplete uninstallation of Pytorch, or the dual installation of Pytorch, which leads to multiple versions of 'libTH.so.1'.

**Comment by liubenyuan** [comment]
Hi, I experience the same issue when upgrading pytorch 0.1.2 to pytorch 0.2.0

```
----> 1 import torch

/opt/anaconda/lib/python3.6/site-packages/torch/__init__.py in <module>()
     51 sys.setdlopenflags(_dl_flags.RTLD_GLOBAL | _dl_flags.RTLD_NOW)
     52 
---> 53 from torch._C import *
     54 
     55 __all__ += [name for name in dir(_C)

ImportError: /opt/anaconda/lib/python3.6/site-packages/torch/lib/libTHC.so.1: undefined symbol: THLongStorage_inferSizeN
```

and 
```
nm /opt/anaconda/lib/python3.6/site-packages/torch/lib/libTHC.so.1 | grep THLongStorage_infer
                 U THLongStorage_inferExpandGeometry
                 U THLongStorage_inferSizeN
```
however, `THLongStorage_infer` exists in `libTH.so.1`, it seems like torch tries to find `libTHC` instead of `libTH`.
```
nm /opt/anaconda/lib/python3.6/site-packages/torch/lib/libTH.so.1 | grep THLongStorage_infer
0000000000036d40 T THLongStorage_inferExpandGeometry
00000000000368f0 T THLongStorage_inferSize2
0000000000036ac0 T THLongStorage_inferSizeN
```

**Comment by liubenyuan** [comment]
updated.

It seems like your do not need to re-install anaconda, find `libTH*` in your directory, you may find
```
/opt/anaconda/lib/python3.6/site-packages/torch/lib/libTH.so.1
/opt/anaconda/lib/python3.6/site-packages/torch/lib/libTHC.so.1
/opt/anaconda/lib/python3.6/site-packages/torch/lib/libTHCS.so.1
/opt/anaconda/lib/python3.6/site-packages/torch/lib/libTHCUNN.so.1
/opt/anaconda/lib/python3.6/site-packages/torch/lib/libTHD.so.1
/opt/anaconda/lib/python3.6/site-packages/torch/lib/libTHNN.so.1
/opt/anaconda/lib/python3.6/site-packages/torch/lib/libTHPP.so.1
/opt/anaconda/lib/python3.6/site-packages/torch/lib/libTHS.so.1
/opt/anaconda/lib/libTH.so.1
/opt/anaconda/lib/libTHNN.so.1
/opt/anaconda/lib/libTHPP.so.1
/opt/anaconda/lib/libTHS.so.1
/opt/anaconda/pkgs/libtorch-0.1.12-0/lib/libTHS.so.1
/opt/anaconda/pkgs/libtorch-0.1.12-0/lib/libTHPP.so.1
/opt/anaconda/pkgs/libtorch-0.1.12-0/lib/libTHNN.so.1
/opt/anaconda/pkgs/libtorch-0.1.12-0/lib/libTH.so.1
/opt/anaconda/pkgs/pytorch-0.2.0-py36h04dd36b_2cu75/lib/python3.6/site-packages/torch/lib/libTHS.so.1
/opt/anaconda/pkgs/pytorch-0.2.0-py36h04dd36b_2cu75/lib/python3.6/site-packages/torch/lib/libTHNN.so.1
/opt/anaconda/pkgs/pytorch-0.2.0-py36h04dd36b_2cu75/lib/python3.6/site-packages/torch/lib/libTHCS.so.1
/opt/anaconda/pkgs/pytorch-0.2.0-py36h04dd36b_2cu75/lib/python3.6/site-packages/torch/lib/libTHD.so.1
/opt/anaconda/pkgs/pytorch-0.2.0-py36h04dd36b_2cu75/lib/python3.6/site-packages/torch/lib/libTHPP.so.1
/opt/anaconda/pkgs/pytorch-0.2.0-py36h04dd36b_2cu75/lib/python3.6/site-packages/torch/lib/libTH.so.1
/opt/anaconda/pkgs/pytorch-0.2.0-py36h04dd36b_2cu75/lib/python3.6/site-packages/torch/lib/libTHCUNN.so.1
/opt/anaconda/pkgs/pytorch-0.2.0-py36h04dd36b_2cu75/lib/python3.6/site-packages/torch/lib/libTHC.so.1
```

So, it is ok to uninstall `libtorch` from conda, and everything goes ok
```
conda uninstall libtorch
```

Thanks for updating to the exciting `0.2.0`.

**Comment by xusong123** [comment]
@liubenyuan It works! Thank you very much!

**Comment by PranY** [comment]
@liubenyuan Thanks, It worked like a charm!

I couldn't afford re-installing pytorch and torchvision again, extremely slow speeds from source [10-50kbps]

**Comment by unnir** [comment]
I solved that problem by creating a new conda environment.
