### ISSUE TITLE
Installing PyTorch 1.1 into cloned conda env that contained PyTorch 1.0 gives "Getting "module 'torch._C' has no attribute 'BoolStorageBase'" with PyTorch 1.1"

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#20403]
Trying to install and use PyTorch 1.1 on AWS image derived from DLAMI 22 fails with following on `import torch`
```
Traceback (most recent call last):
  File "check_versions.py", line 12, in <module>
    import torch.optim as optim
  File "/home/ubuntu/anaconda3/envs/pytorch_11/lib/python3.6/site-packages/torch/__init__.py", line 222, in <module>
    class BoolStorage(_C.BoolStorageBase, _StorageBase):
AttributeError: module 'torch._C' has no attribute 'BoolStorageBase'
```
Things tried

```
conda create --name=pytorch_11 --clone pytorch_p36
source activate pytorch_11
pip install torch==1.1.0
python -c "import torch"
```

On a different machine
```
conda create --name=pytorch_11 --clone pytorch_p36
source activate pytorch_11
conda install pytorch torchvision -c pytorch
python -c "import torch"
```

Uninstalling torch and reinstalling version 1.0 with pip fixes the issue
Another solution that worked was to install torch 1.1 directly into pytorch_p36 environment instead of cloning it

**Comment by yaroslavvb** [comment]
This seems to be similar issue to https://github.com/pytorch/pytorch/issues/12031 . It looks like you must do `conda uninstall pytorch -y` before `conda install pytorch` or you end up in unrecoverable bad state

**Comment by yaroslavvb** [comment]
Actually even conda uninstall pytorch -y only works sometimes. There's some non-determinism about conda and clone. Ultimately I was able to install a working version of pytorch 1.1 by using "build from source" instructions on a machine where all the other methods failed

**Comment by yaroslavvb** [comment]
On Mac, upgrading pytorch to 1.1 with pip results in
```
(main) ÷19-05-20 15:39:19|ttys007|trippings-mbp-3|~/git0/aws-network-benchmarks\÷ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: dlopen(/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 9): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/torch/lib/libshm.dylib
  Reason: image not found
>>> 
```
Solution for Mac
```
pip uninstall torch
conda install pytorch torchvision -c pytorch
```

**Comment by luccitan** [comment]
Hello, do you have any good news regarding this issue ?

About the Mac situation, you need to install `libomp` via `brew install libomp` (see [this issue](https://github.com/pytorch/pytorch/issues/20030))

I am facing the original issue on Amazon DL instances (as you may too, since you're using  `pytorch_p36` ;) )

**Comment by yaroslavvb** [comment]
My workaround was to build PyTorch from source and install it that way.
But also, DLAMI 23 has PyTorch 1.1 installed by default now

**Comment by policeme** [comment]
@yaroslavvb did u solve this issue, I met this

**Comment by policeme** [comment]
import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\__init__.py", line 268, in <module>
    _C._initExtension(manager_path())
AttributeError: module 'torch' has no attribute 'BoolStorage'
