### ISSUE TITLE
Non blocking tensor copy to GPU not working from torch 1.0

### ISSUE THREAD

**Issue by opherlieber** [pytorch/pytorch#20411]
## 🐛 Bug

The non_blocking option of tensor.cuda()/tensor.to() does not seem to have any effect as of torch 1.0, or possibly something additional needs to be configured for it to work?

## To Reproduce

```
import time
import torch

shape = (128,128)
count = 640

tensors = [torch.randint(255,shape).byte().pin_memory() for i in range(count)]

for i in range(3):
    start = time.time()
    tensors_cuda = [item.cuda(non_blocking = True) for item in tensors]
    torch.cuda.synchronize()
    print("took", (time.time()-start)*1000.)

```

## Expected behavior

In torch 0.4 the time it took is ~5ms (Aside from the 1st iteration), and ~25ms when setting non_blocking=False.
As of torch 1.0 up to nightly the time is ~25ms regardless of the non_blocking being True

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 398.11
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[conda] blas                      1.0                         mkl
[conda] cuda90                    1.0                           0    pytorch
[conda] mkl                       2018.0.2                      1
[conda] mkl-service               1.1.2            py36h57e144c_4
[conda] mkl_fft                   1.0.1            py36h452e1ab_0
[conda] mkl_random                1.0.1            py36h9258bd6_0
[conda] torch                     0.4.0                    pypi_0    pypi

**Comment by colesbury** [comment]
You are not measuring the effect of non_blocking because you are explicitly synchronizing inside your measurement.  You end up measuring some complicated interaction between copy overhead and copy time.

non_blocking=True doesn't make the copy faster. It just allows the copy_ call to return before the copy is completed. If you call `torch.cuda.synchronize()` immediately after a copy you've added back the synchronization you just tried to remove.

Anyways, `non_blocking=True` works in PyTorch 1.0 (from CPU->CUDA). You can see it by adding a GPU delay before your copy:

```python
import time
import torch

DELAY = 100000000 
x = torch.randn((1024, 1024), pin_memory=True)

torch.cuda.synchronize()
start = time.time()
torch.cuda._sleep(DELAY)
x.cuda(non_blocking=True)
end = time.time()

print('non_blocking=True', (end - start)*1000.)  # ~7 ms on my GPU

torch.cuda.synchronize()
start = time.time()
torch.cuda._sleep(DELAY)
x.cuda(non_blocking=False)
end = time.time()


print('non_blocking=False', (end - start)*1000.)  # ~77 ms on my GPU
```
