### ISSUE TITLE
torch.max, the first or the last occurrence?

### ISSUE THREAD

**Issue by miladmozafari** [pytorch/pytorch#20414]
This is not truly a bug, but a change in PyTorch 1.1.0 which I found it by chance. This change was very important to my project [SpykeTorch](https://github.com/miladmozafari/SpykeTorch).
In PyTorch 0.4.1, using max (or min) function results in finding the first occurrence of the max-value, however in PyTorch 1.1.0 (not sure about other versions > 1.0.0) the result is the last occurrence. I search the change-log page and I found that it is not reported.

Here is the execution of a same function on a same data with two different versions of PyTorch:
![change](https://user-images.githubusercontent.com/24203184/57588540-07acb480-7516-11e9-96cf-bc314244323d.png)

**Comment by SsnL** [comment]
`max` is never guaranteed to return the first or the last.

**Comment by jeffreyksmithjr** [comment]
Per @SsnL , this looks to be as designed. Closing.
