### ISSUE TITLE
pytorch 1.0.1.post2 crash at forward on Mac Os after fork 

### ISSUE THREAD

**Issue by lironmo** [pytorch/pytorch#20410]
hello,
i created the following scripts for testing,
not sure what is the source of the problem but it's seems that in some scenario it's happened on linux as well at different but similar scenario(crash on forward after fork)
the following script crash on mac OS (see next comment)

**Comment by lironmo** [comment]
`import torch
import torchvision
import torch.multiprocessing as mp


def test(m):
    # m.share_memory()

    print('3')
    t = torch.ones((1, 3, 224, 224), dtype=torch.float32)
    print('4')
    with torch.no_grad():
        o = m(t)
    print('fun for all')


def run_forward_local():
    print('Start forward_local')
    torch.set_num_threads(1)
    m = torchvision.models.resnet18()
    t = torch.ones((1, 3, 224, 224), dtype=torch.float32)
    print('Start FW')
    with torch.no_grad():
        o = m(t)
        print('End FW')

    print('End running')


def run_forward_in_child_process_with_model():
    print('Start')
    torch.set_num_threads(1)
    m = torchvision.models.resnet18()
    p = mp.Process(target=run_forward_local, args=(m,))
    p.start()
    p.join()


def run_forward_in_child_process():
    print('Start')
    p = mp.Process(target=run_forward_local)
    p.start()
    p.join()


if __name__ == "__main__":
    # run forward local and then fork and run again
    run_forward_local()
    run_forward_in_child_process()
    print("END ALL")`

**Comment by jeffreyksmithjr** [comment]
Please post your logs to allow for some assessment of what is going wrong.

**Comment by jeffreyksmithjr** [comment]
Closing this issue, because we need more information to effectively triage it. When you provide the requested information, feel free to reopen the issue, to let us know that we can continue with assessing the issue. This open/close/open cycle is how we manage the flow of issues, so your reopening of the issue will constitute the signal that lets us know to take a look at the issue again.

**Comment by lironmo** [comment]
hey @jeffreyksmithjr ,
its really simple test that i created to show the problem.

the logs are:
Start forward_local
Start FW
End FW
End running
Start
Start forward_local
Start FW
END ALL

as you see some python process crashed.

excepted logs :
Start forward_local
Start FW
End FW
End running
Start
Start forward_local
Start FW
End FW
End running
END ALL

**Comment by lironmo** [comment]
[run_mp.py.txt](https://github.com/pytorch/pytorch/files/3176550/run_mp.py.txt)

**Comment by lironmo** [comment]
@jeffreyksmithjr please reopen,
i believe that if we find the root of this problem we get a lead for another similar problem i have at linux.

Thanks!

**Comment by soumith** [comment]
I am seeing this output when I ran locally:

```
Start forward_local
Start FW
End FW
End running
Start
Start forward_local
Start FW
End FW
End running
END ALL
```

this seems fine.

**Comment by lironmo** [comment]
Yes it's seems ok, but i still getting crashes.
Do you run it on mac os?
Can you please send me the pytorch version that you use?

**Comment by soumith** [comment]
i ran it on Linux, pytorch version 1.1.0

**Comment by lironmo** [comment]
This tester should works on linux, 
It's only crash on mac os.

**Comment by soumith** [comment]
@lironmo it is not crashing for me on MacOS with PyTorch 1.1.0 either:

```
Start forward_local
Start FW
End FW
End running
Start
Start forward_local
Start FW
End FW
End running
END ALL
```

**Comment by lironmo** [comment]
Ok,
I will upgrade from 1.01.post2 to 1.1.0 and get back to you.

Thanks!
