### ISSUE TITLE
Error downloading MNIST dataset

### ISSUE THREAD

**Issue by attibalazs** [pytorch/pytorch#20423]
hi all,

having problems downloading the MNIST dataset, also tried with FashionMNIST which works fine.

```

from torchvision.datasets import MNIST
from torchvision import transforms

train_dataset = MNIST('data/', train=True, download=True,
                             transform=transforms.Compose([
                                 transforms.ToTensor(),
                                 transforms.Normalize((mean,), (std,))
                             ]))
```
error message

> 
> Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to data/MNIST/raw/train-images-idx3-ubyte.gz
> Extracting data/MNIST/raw/train-images-idx3-ubyte.gz
> 
> 
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-30-1dca197de290> in <module>()
>       7                              transform=transforms.Compose([
>       8                                  transforms.ToTensor(),
> ----> 9                                  transforms.Normalize((mean,), (std,))
>      10                              ]))
>      11 test_dataset = MNIST('data/', train=False, download=True,
> 
> /anaconda/envs/py36/lib/python3.6/site-packages/torchvision/datasets/mnist.py in __init__(self, root, train, transform, target_transform, download)
>      66 
>      67         if download:
> ---> 68             self.download()
>      69 
>      70         if not self._check_exists():
> 
> /anaconda/envs/py36/lib/python3.6/site-packages/torchvision/datasets/mnist.py in download(self)
>     142             file_path = os.path.join(self.raw_folder, filename)
>     143             download_url(url, root=self.raw_folder, filename=filename, md5=None)
> --> 144             self.extract_gzip(gzip_path=file_path, remove_finished=True)
>     145 
>     146         # process and save as torch files
> 
> /anaconda/envs/py36/lib/python3.6/site-packages/torchvision/datasets/mnist.py in extract_gzip(gzip_path, remove_finished)
>     123         print('Extracting {}'.format(gzip_path))
>     124         with open(gzip_path.replace('.gz', ''), 'wb') as out_f, \
> --> 125                 gzip.GzipFile(gzip_path) as zip_f:
>     126             out_f.write(zip_f.read())
>     127         if remove_finished:
> 
> /anaconda/envs/py36/lib/python3.6/gzip.py in __init__(self, filename, mode, compresslevel, fileobj, mtime)
>     161             mode += 'b'
>     162         if fileobj is None:
> --> 163             fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
>     164         if filename is None:
>     165             filename = getattr(fileobj, 'name', '')
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'data/MNIST/raw/train-images-idx3-ubyte.gz'
> 
> 

using:

torch==1.0.1.post2
torchvision==0.2.2

**Comment by sakaia** [comment]
Works fine for me on Google Colab.

```
!git clone http://github.com/pytorch/examples
!cd examples/mnist;python main.py
```

```
import torch
print(torch.__version__)
print(torchvision.__version__)
```

1.1.0
0.2.2

**Comment by attibalazs** [comment]
yes it works fine on colab, maybe its something to do with the machine i am using.

**Comment by smritiRGI** [comment]
Gives me this error on colab

Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to data/MNIST/raw/train-images-idx3-ubyte.gz
0it [00:00, ?it/s]
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-5-97a905300148> in <module>()
      6                              transform=transforms.Compose([
      7                                  transforms.ToTensor(),
----> 8                                  transforms.Normalize((0.5,), (0.5,))
      9                              ]))

11 frames
/usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden

**Comment by wlmqjiyizh** [comment]
> Gives me this error on colab
> 
> ## Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to data/MNIST/raw/train-images-idx3-ubyte.gz
> 0it [00:00, ?it/s]
> HTTPError Traceback (most recent call last)
> in ()
> 6 transform=transforms.Compose([
> 7 transforms.ToTensor(),
> ----> 8 transforms.Normalize((0.5,), (0.5,))
> 9 ]))
> 
> 11 frames
> /usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
> 648 class HTTPDefaultErrorHandler(BaseHandler):
> 649 def http_error_default(self, req, fp, code, msg, hdrs):
> --> 650 raise HTTPError(req.full_url, code, msg, hdrs, fp)
> 651
> 652 class HTTPRedirectHandler(BaseHandler):
> 
> HTTPError: HTTP Error 403: Forbidden

Hello, I got the same question. How do you solve it finally?

**Comment by wlmqjiyizh** [comment]
> > Gives me this error on colab
> > ## Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to data/MNIST/raw/train-images-idx3-ubyte.gz
> > 0it [00:00, ?it/s]
> > HTTPError Traceback (most recent call last)
> > in ()
> > 6 transform=transforms.Compose([
> > 7 transforms.ToTensor(),
> > ----> 8 transforms.Normalize((0.5,), (0.5,))
> > 9 ]))
> > 11 frames
> > /usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
> > 648 class HTTPDefaultErrorHandler(BaseHandler):
> > 649 def http_error_default(self, req, fp, code, msg, hdrs):
> > --> 650 raise HTTPError(req.full_url, code, msg, hdrs, fp)
> > 651
> > 652 class HTTPRedirectHandler(BaseHandler):
> > HTTPError: HTTP Error 403: Forbidden
> 
> Hello, I got the same question. How do you solve it finally?

Well...  Finally I found a solution in this link https://github.com/pytorch/vision/issues/1938

**Comment by kevingoh** [comment]
> hi all,
> 
> having problems downloading the MNIST dataset, also tried with FashionMNIST which works fine.
> 
> ```
> 
> from torchvision.datasets import MNIST
> from torchvision import transforms
> 
> train_dataset = MNIST('data/', train=True, download=True,
>                              transform=transforms.Compose([
>                                  transforms.ToTensor(),
>                                  transforms.Normalize((mean,), (std,))
>                              ]))
> ```
> 
> error message
> 
> > Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to data/MNIST/raw/train-images-idx3-ubyte.gz
> > Extracting data/MNIST/raw/train-images-idx3-ubyte.gz
> > 
> > FileNotFoundError                         Traceback (most recent call last)
> >  in ()
> > 7                              transform=transforms.Compose([
> > 8                                  transforms.ToTensor(),
> > ----> 9                                  transforms.Normalize((mean,), (std,))
> > 10                              ]))
> > 11 test_dataset = MNIST('data/', train=False, download=True,
> > /anaconda/envs/py36/lib/python3.6/site-packages/torchvision/datasets/mnist.py in **init**(self, root, train, transform, target_transform, download)
> > 66
> > 67         if download:
> > ---> 68             self.download()
> > 69
> > 70         if not self._check_exists():
> > /anaconda/envs/py36/lib/python3.6/site-packages/torchvision/datasets/mnist.py in download(self)
> > 142             file_path = os.path.join(self.raw_folder, filename)
> > 143             download_url(url, root=self.raw_folder, filename=filename, md5=None)
> > --> 144             self.extract_gzip(gzip_path=file_path, remove_finished=True)
> > 145
> > 146         # process and save as torch files
> > /anaconda/envs/py36/lib/python3.6/site-packages/torchvision/datasets/mnist.py in extract_gzip(gzip_path, remove_finished)
> > 123         print('Extracting {}'.format(gzip_path))
> > 124         with open(gzip_path.replace('.gz', ''), 'wb') as out_f, 
> > --> 125                 gzip.GzipFile(gzip_path) as zip_f:
> > 126             out_f.write(zip_f.read())
> > 127         if remove_finished:
> > /anaconda/envs/py36/lib/python3.6/gzip.py in **init**(self, filename, mode, compresslevel, fileobj, mtime)
> > 161             mode += 'b'
> > 162         if fileobj is None:
> > --> 163             fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
> > 164         if filename is None:
> > 165             filename = getattr(fileobj, 'name', '')
> > FileNotFoundError: [Errno 2] No such file or directory: 'data/MNIST/raw/train-images-idx3-ubyte.gz'
> 
> using:
> 
> torch==1.0.1.post2
> torchvision==0.2.2

Hi I am facing the same issue.. in fact when I checked it seems like the downloaded file was automatically decompressed or the gz extension was removed so running gzip went into exception...

However, downloading FashionMNIST dataset was successfully completed without any issue...

Please help!

**Comment by kevingoh** [comment]
I solved my own problem too...
there was a mismatch of torchvision I installed using pip...it was 0.2.2 with torch 1.8.0...
I then built and installed torchvision 0.9.0 from source and it works correctly

**Comment by ArturoPardoGIF** [comment]
Currently using Torch 1.8.0 and Torchvision 0.9.0, I am having the same problem. It doesn't download the dataset. 
Will continue searching for a solution :/

**Comment by uchar** [comment]
Same Error here in Kaggle
```
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ./data/mnist/MNIST/raw/train-images-idx3-ubyte.gz
|          | 0/? [00:00
HTTPError
HTTP Error 503: Service Unavailable
```

**Comment by mlelarge** [comment]
@uchar : a turnaround is to download the dataset manually (but you need first to turn internet on for your Kaggle notebook), see:
https://twitter.com/marc_lelarge/status/1370340616215859203?s=20
or
https://gist.github.com/mlelarge/60ddefa9e16bc06f7f4fc7bff769bdb1

**Comment by Yutaaa76** [comment]
> @uchar : a workaround is to download the dataset manually (but you need first to turn internet on for your Kaggle notebook), see:
> https://twitter.com/marc_lelarge/status/1370340616215859203?s=20
> or
> https://gist.github.com/mlelarge/60ddefa9e16bc06f7f4fc7bff769bdb1

I just solved this problem by the 100%-python way in twitter's comment.

**Comment by KAJURAMBO** [comment]
My god... I was dealing with same problem and just changes the internet connectivity literally and its worked...
