### ISSUE TITLE
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '7']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by wuwuzhijing** [pytorch/pytorch#20420]
When compiling the pytorch from github, after I excute 
> python setup.py

after a few minuters, the following problem occurs:

> [364/2489] C:\PROGRA~2\MICROS~3.0\VC\bin\amd64\cl.exe   /TP -DONNX_NAMESPACE=onnx_torch -DUSE_MSC_ATOMICS=1 -D_CRT_SECURE_NO_DEPRECATE=1 -I..\aten\src -I. -I..\ -I..\third_party\protobuf\src -I..\cmake\..\third_party\benchmark\include -Icaffe2\contrib\aten -I..\third_party\onnx -Ithird_party\onnx -I..\third_party\foxi -Ithird_party\foxi -I..\c10\.. -I..\cmake\..\third_party\googletest\googlemock\include -I..\cmake\..\third_party\googletest\googletest\include -I..\cmake\..\third_party\eigen -IF:\Program\Codes\Anaconda\envs\python37forPytorch\include -IF:\Program\Codes\Anaconda\envs\python37forPytorch\lib\site-packages\numpy\core\include -I..\cmake\..\third_party\pybind11\include -I..\cmake\..\third_party\cub -I..\third_party\googletest\googlemock\include -I..\third_party\googletest\googlemock -I..\third_party\googletest\googletest\include -I..\third_party\googletest\googletest /EHa -openmp /MP /bigobj /MD /O2 /Ob2  /MP /bigobj   -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DUSE_AVX -DTH_HAVE_THREAD /showIncludes /Foc10\test\CMakeFiles\c10_either_test.dir\util\either_test.cpp.obj /Fdc10\test\CMakeFiles\c10_either_test.dir\ /FS -c ..\c10\test\util\either_test.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.00.24215.1 版
版权所有(C) Microsoft Corporation。保留所有权利。

> ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 728, in <module>
    build_deps()
  File "setup.py", line 294, in build_deps
    build_dir='build')
  File "J:\Projects\caffe2\pytorch\tools\build_pytorch_libs.py", line 283, in build_caffe2
    check_call(build_cmd, cwd=build_dir, env=my_env)
  File "F:\Program\Codes\Anaconda\envs\python37forPytorch\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '7']' returned non-zero exit status 1.

I find some similar problems, but none solved the one I  encounters.

Does anyone have any idea about it? It takes so long to complie pytorch, so I want to know the  reason why this happend, so it will not happen next time I excute a comlilation....

comments:

> The cmake package havebeen updated to the latest version, so does ninja.

> cuda cudnn and python env  is correct.

**Comment by peterjc123** [comment]
Full log, please.

**Comment by peterjc123** [comment]
> `C:\PROGRA2\MICROS3.0\VC\bin\amd64\cl.exe`
Are you using VS 2015? Please read this section carefully. https://github.com/pytorch/pytorch#install-pytorch

**Comment by wuwuzhijing** [comment]
> > `C:\PROGRA2\MICROS3.0\VC\bin\amd64\cl.exe`
> 
> Are you using VS 2015? Please read this section carefully. https://github.com/pytorch/pytorch#install-pytorch

sorry,  I  don't read the guide carefully.  I will try to install vs2017update3 community and try compile again.  By the way is there any way to fix the vs2015 and make it work?

**Comment by peterjc123** [comment]
Yes, but we don't want to do this.  The support for C++ 11 is poor in VS 2015, and we don't want to add those hacks any more because VS 2017 is already supported.

**Comment by wuwuzhijing** [comment]
> Yes, but we don't want to do this. The support for C++ 11 is poor in VS 2015, and we don't want to add those hacks any more because VS 2017 is already supported.

OK, thank you. I will try vs2017 15.4 and give some feedback later.

**Comment by wuwuzhijing** [comment]
> Yes, but we don't want to do this. The support for C++ 11 is poor in VS 2015, and we don't want to add those hacks any more because VS 2017 is already supported.

How long it takes for the entire process? I've wait for almost 1 hour....

**Comment by peterjc123** [comment]
It depends on how many CPU cores the machine has. Usually, with an 8-core CPU and Ninja, a CUDA build should take 2-3 hrs, while a CPU build takes 1-2 hrs.

**Comment by wuwuzhijing** [comment]
mine:
>4-core CPU
Ninja
CUDA

It seems my build will end till evening..OK, I will keep patient...

**Comment by wuwuzhijing** [comment]
Ops, an error occured just now
> Traceback (most recent call last):
  File "setup.py", line 728, in <module>
    build_deps()
  File "setup.py", line 294, in build_deps
    build_dir='build')
  File "J:\Projects\caffe2\pytorch\tools\build_pytorch_libs.py", line 283, in build_caffe2
    check_call(build_cmd, cwd=build_dir, env=my_env)
  File "F:\Program\Codes\Anaconda\envs\python37forPytorch\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '7']' returned non-zero exit status 1.
Exception ignored in: <_io.TextIOWrapper name='<stdout>' encoding='cp936'>
PermissionError: [Errno 13] Permission denied


how can I modify permission?
[build.log](https://github.com/pytorch/pytorch/files/3171771/build.log)

**Comment by wuwuzhijing** [comment]
> It depends on how many CPU cores the machine has. Usually, with an 8-core CPU and Ninja, a CUDA build should take 2-3 hrs, while a CPU build takes 1-2 hrs.

An error occured just now. I've paste my building log, please check and config why this happened..
Thank you!

**Comment by peterjc123** [comment]
Sorry, I could not find any useful information from your log. Did you forget to redirect stderr to stdout, that is `python setup.py 2>&1 > build.log`?

**Comment by wuwuzhijing** [comment]
> Sorry, I could not find any useful information from your log. Did you forget to redirect stderr to stdout, that is `python setup.py 2>&1 > build.log`?

I redirect like this:
> python setup.py install > build.log

**Comment by peterjc123** [comment]
> > Sorry, I could not find any useful information from your log. Did you forget to redirect stderr to stdout, that is `python setup.py 2>&1 > build.log`?
> 
> I redirect like this:
> 
> > python setup.py install > build.log

That way, the stderr stream won't be written to the file. (sad)

**Comment by wuwuzhijing** [comment]
> > > Sorry, I could not find any useful information from your log. Did you forget to redirect stderr to stdout, that is `python setup.py 2>&1 > build.log`?
> > 
> > 
> > I redirect like this:
> > > python setup.py install > build.log
> 
> That way, the stderr stream won't be written to the file. (sad)

I excute
> python setup.py 2>&1 > build.log

but error like this
![image](https://user-images.githubusercontent.com/13216845/57606358-505a8100-759b-11e9-9a28-00a00d6b957e.png)
(stupid...)

**Comment by peterjc123** [comment]
@wuwuzhijing Sorry, it should be `python setup.py > build.log 2>&1`.

**Comment by wuwuzhijing** [comment]
@peterjc123 excellent, it worked and waiting...  I think the pytorch  compilation is 
incremental compilation, so you'll be disturbed again once the next error occurs....

**Comment by wuwuzhijing** [comment]
@peterjc123 stopped again, log:
[build2.log](https://github.com/pytorch/pytorch/files/3171920/build2.log)

**Comment by peterjc123** [comment]
The actual error here is `Host compiler targets unsupported OS`. It is caused by the incompatibility of the versions between CUDA and VS. Unfortunately, CUDA 8 is broken on Windows. You'll need to update CUDA to 10.0 or downgrade your VS to 14.11 (15.4.5 Update).

**Comment by wuwuzhijing** [comment]
@peterjc123 I notice somewhere that the Nsight of cuda should be installed before vs2017, but now I have 2017 installed, does it matter I install Nsight after vs2017？ If not, why they have this conclusion...

**Comment by peterjc123** [comment]
No, actually nsight needs to be installed after vs 2017 because it depends on that.

**Comment by wuwuzhijing** [comment]
@peterjc123 
Now  my env:
> vs2017  15.9.1
> cuda10.1 && cudnn 10.1
> python 3.7

Is there any problem?

**Comment by peterjc123** [comment]
LGTM

**Comment by wuwuzhijing** [comment]
@peterjc123 
OK, one more question, should I rebuild from very begin or continue the build process before?

**Comment by peterjc123** [comment]
Rebuild from the beginning because the generator has changed.

**Comment by wuwuzhijing** [comment]
@peterjc123 Thank you for your guiding, finally I made it. 
> It takes about 129 minutes on my 4-core CPU(CUDA on).
> I build for 3 times.  No code problems, just environment problems.The first time I use vs2015 rather than vs2017, and failed. Then I use the wrong cuda version(8.0). The third time I make it.

![image](https://user-images.githubusercontent.com/13216845/57620682-12218980-75bc-11e9-89af-369085e30e71.png)

Next I will do some classification works with caffe2.  I am a freshman on this kind of project. So I got your email address and then you may be disturbed on github or email...
Thank you!
