### ISSUE TITLE
"derivative for _thnn_fused_lstm_cell_backward is not implemented" while using GPU

### ISSUE THREAD

**Issue by myy920213** [pytorch/pytorch#20449]
## 🐛 Bug
I got RuntimeError : "derivative for _thnn_fused_lstm_cell_backward is not implemented" while computing second order derivative of LSTMcell. 
This works fine while using cpu, but got this error while using GPU. 
Very confusing about this issue. Is this mean second order derivative of LSTMcell is not available on CUDA?

**Comment by pietern** [comment]
Can you confirm if this is the same as #5261?

**Comment by myy920213** [comment]
> Can you confirm if this is the same as #5261?

Thanks for reply. I think this is the same issue.

**Comment by ngimel** [comment]
Actually I think this issue is different - #5261 is about cudnn rnn, _thnn_fused_lstm_cell_backward is backward for non-cudnn path.

**Comment by ngimel** [comment]
Apparently, double backward on gpu has been broken for some time. What's happening is in the forward _thnn_fused_lstm_cell is called https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/RNN.cpp#L259-L265, and it has its derivative specified in derivatives.yaml, it's _thnn_fused_lstm_cell_backward. _thnn_fused_lstm_cell_backward does not have derivative, and throws an error. 
The easiest fix would be to determine that there would be double backward and not use fused cell in forward, but I don't think there's a way to tell in forward if there will be double backward or not. So it looks like it's necessary to define differentiable backward functions for rnn cells, similarly to how it's done for weight norm, and fall back to them if `GradMode::is_enabled()`.

**Comment by IRNLPCoder** [comment]
derivative for _thnn_fused_gru_cell_backward is not implemented

Meta-learning needs this feature!

**Comment by ngimel** [comment]
Fixed in #26660
