### ISSUE TITLE
resnet50 export to ONNX messes up Flatten layer

### ISSUE THREAD

**Issue by vuzelac-cadence** [pytorch/pytorch#20453]
Converting resnet50, (similar issue for vgg16, densenet201, squeezenet as well) from examples directory into ONNX.  What's supposed to be simple flattening at the end of the model turns out to be a complicated network:

Model prints this as last two layers:
```
(avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
(fc): Linear(in_features=2048, out_features=1000, bias=True)
```
ONNX produced model final layers: 
```
GlobalAveragerPool->Shape->Gather->Unsqueeze->Concat->Reshape->Gemm
                                  Unsqueeze -^
```

Isn't the converter just supposed to insert a Flatten layer ?

Some frameworks/compilers don't support non-constant reshape caused by this network (e.g. Facebook Glow) and adding such support by folding the nodes (e.g. starting from Shape) seems too patchy. 

Details:
resnet50 obtained  using `examples/imagenet/main.py` . Converted using:
```
model.train(False)
input = torch.randn(1, 3, 224, 224, requires_grad=True)
output = model(input)
torch_out = torch.onnx._export(model, input, "model.onnx", export_params=True)
```

**Comment by pietern** [comment]
cc @houseroad

**Comment by houseroad** [comment]
this is caused by the support of dynamic shape in pytorch jit tracer. We are working on a flag to turn this off. cc: @spandantiwari

**Comment by borisfom** [comment]
Any ETA on this ?

**Comment by pkohli2405** [comment]
hey, any updates on this issue.  is this resolved?

**Comment by cullenwren** [comment]
@houseroad any update on this?

**Comment by cullenwren** [comment]
Or has anyone come up with any work arounds?

**Comment by garymm** [comment]
Seems this got fixed at some point.
Exporting torchvision.models.resnet50 on the latest nightly PyTorch produces a `GlobalAveragePool->Flatten->Gemm` at the end, no `Reshape`:

```python
import torch
model = torchvision.models.resnet50()
model.eval()
x = torch.zeros((1, 3, 300, 300))
torch.onnx._export(model, x, "/tmp/resnet50.onnx", verbose=True)
```

Opening the model in Netron shows this at the end:
![image](https://user-images.githubusercontent.com/421339/142704589-10528389-c51b-4116-8f8a-435dc9340f3d.png)

Feel free to open a new issue with specific repro instructions.

**Comment by harshdhamecha** [comment]
@garymm I'm facing a similar issue. Unfortunately, the `torch==2.3.1`  `_export` method exports flatten as reshape node. May I know which torch version did you use?
