### ISSUE TITLE
Corner case in matmul optimization

### ISSUE THREAD

**Issue by skrah** [pytorch/pytorch#20452]
If the shape contains multiple zeros (which can happen as a result of slicing), the `matmul` optimization for `A.ndim >= 3 && B.ndim <= 2` fails.

First an example *without* optimization:

```
>>> import torch
>>> x = torch.arange(0).reshape(0, 0, 0)
>>> y = torch.arange(0).reshape(0, 0, 0)
>>> x @ y
tensor([], size=(0, 0, 0), dtype=torch.int64)
```

The optimization gives a `Runtime` error:

```
>>> x = torch.arange(0).reshape(0, 0)
>>> y = torch.arange(0).reshape(0, 0, 0)
>>> x @ y
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous
```

This is the error location:

https://github.com/pytorch/pytorch/blob/824d4f9957b1e2b5d812b7b7b0379bf0f7e270a9/aten/src/ATen/native/LinearAlgebra.cpp#L427

**Comment by gchanan** [comment]
This has been addressed (the code above works).
