### ISSUE TITLE
Second order gradient cuda error

### ISSUE THREAD

**Issue by michaelklachko** [pytorch/pytorch#20465]
## 🐛 Bug
Convnet training on GPU: when penalizing gradient growth (backpropagating a gradient of a gradient) the following error happens:

```
/opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/THCTensorScatterGather.cu:100: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 3]: block: [40,0,0], thread: [31,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/generic/THCTensorScatterGather.cu line=71 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "cudafail.py", line 47, in <module>
    grad_sum.backward(retain_graph=False)
  File "/home/michael/miniconda2/envs/pt/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/michael/miniconda2/envs/pt/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/generic/THCTensorScatterGather.cu:71
```

## To Reproduce

```
import torch
from torch import nn
from torchvision import datasets, transforms

class Net(nn.Module):
	def __init__(self):
		super(Net, self).__init__()
		self.conv1 = nn.Conv2d(3, 20, kernel_size=5, bias=False)
		self.conv2 = nn.Conv2d(20, 40, kernel_size=5, bias=False)
		self.linear1 = nn.Linear(40 * 5 * 5, 300, bias=False)
		self.linear2 = nn.Linear(300, 10, bias=False)
		self.pool = nn.MaxPool2d(2, 2)
		self.relu = nn.ReLU()

	def forward(self, input):
		x = self.relu(self.pool(self.conv1(input)))
		x = self.relu(self.pool(self.conv2(x)))
		x = x.view(x.size(0), -1)
		x = self.relu(self.linear1(x))
		return self.linear2(x)

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
trainset = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True, num_workers=8)

model = Net().cuda()
optimizer = torch.optim.SGD(model.parameters(), lr=1, momentum=0, nesterov=False)

for epoch in range(100):
        print(epoch)
	model.train()
	for i, (images, labels) in enumerate(trainloader, 0):
		images = images.cuda()
		labels = labels.cuda()
		outputs = model(images)
		loss = nn.CrossEntropyLoss()(outputs, labels)
		optimizer.zero_grad()
		loss.backward(retain_graph=True)

		grads = torch.autograd.grad(loss, model.parameters(), create_graph=True)
		grad_sum = 0
		for grad in grads:
			grad_sum += 0.1 * grad.pow(2).sum()
		grad_sum.backward(retain_graph=False)

		optimizer.step()
```

## Environment
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.6.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 418.56
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.3
/usr/local/cuda-9.0/lib64/libcudnn.so.7.2.1

Versions of relevant libraries:
[pip3] numpy==1.15.0
[pip3] torch==1.1.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.2.2
[conda] blas                      1.0                         mkl
[conda] cuda92                    1.0                           0    pytorch
[conda] mkl                       2018.0.3                      1
[conda] mkl_fft                   1.0.4            py36h4414c95_1
[conda] mkl_random                1.0.1            py36h4414c95_1
[conda] pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchfile                 0.1.0                      py_0    conda-forge
[conda] torchvision               0.2.2                      py_3    pytorch
## Additional context

If I change the coefficient in `grad_sum += 0.1 * grad.pow(2).sum()` from 0.1 to 10 the error does NOT happen (at least not before ~40 epochs), same if I reduce the learning rate from 1 to 0.001.

**Comment by pietern** [comment]
Adding back the autograd label since the conditions appears to be triggered there.

@li-roy @zou3519 Could you take a look at this?

**Comment by skrah** [comment]
The device-side assert is triggered here:

https://github.com/pytorch/pytorch/blob/14ecf92d4212996937a9a1ceadd2202bd828636e/aten/src/THC/THCTensorScatterGather.cu#L100

In the reproducer (thanks!), `indexValue` is `-1` when things start to go awry.  This suggests that somewhere negative indices aren't adjusted; the question is whether `index.data` should **only contain indices that are in range or allow negative indices**.


Some other kernels adjust indices, example:

https://github.com/pytorch/pytorch/blob/14ecf92d4212996937a9a1ceadd2202bd828636e/aten/src/ATen/native/cuda/IndexKernel.cu#L60


Indeed the reproducer passes at least 40 epochs with this diff:

```
diff --git a/aten/src/THC/THCTensorScatterGather.cu b/aten/src/THC/THCTensorScatterGather.cu
index baec8cb..d6d1fd7 100644
--- a/aten/src/THC/THCTensorScatterGather.cu
+++ b/aten/src/THC/THCTensorScatterGather.cu
@@ -97,6 +97,9 @@ __global__ void THCudaTensor_gatherKernel(
                                                           src, &srcOffset);
 
     int64_t indexValue = index.data[indexOffset];
+    if (indexValue < 0) {
+        indexValue += src.sizes[dim];
+    }
     assert(indexValue >= 0 && indexValue < src.sizes[dim]);
     srcOffset += indexValue * src.strides[dim];
```

**Comment by fps7806** [comment]
I'm running into the same issue in a very similar setting. like @michaelklachko in my case it seems to be triggered (more often) when learning rate is high.
I'm curious about what is calling that kernel to see if we can get around it.

**Comment by skrah** [comment]
@fps7806 The reproducer script produces `NaNs` in `grad_sum`. Here is an example run:

```
tensor(0.3012, device='cuda:0', grad_fn=<AddBackward0>) torch.float32
tensor(0.0048, device='cuda:0', grad_fn=<AddBackward0>) torch.float32
tensor(2.2294, device='cuda:0', grad_fn=<AddBackward0>) torch.float32
tensor(241.6396, device='cuda:0', grad_fn=<AddBackward0>) torch.float32
tensor(2.6122e+13, device='cuda:0', grad_fn=<AddBackward0>) torch.float32
tensor(inf, device='cuda:0', grad_fn=<AddBackward0>) torch.float32
tensor(nan, device='cuda:0', grad_fn=<AddBackward0>) torch.float32
```

Actually the `autograd.detect_anomaly()` context manager detects those `NaNs` **before** the device assert happens.

So this issue seems to be about behaving gracefully once an anomaly has occurred. CPU and CUDA behave differently:  The CPU kernels continue to produce all `NaNs`, in CUDA the `indices` kernel arg is all `-1` for some reason, which I'm currently investigating.

The CPU behavior looks correct to me, unless all behavior is undefined one an anomaly has occurred.

**Comment by skrah** [comment]
The cause was a bit difficult to locate.  Contrary to the previous message, I could also reproduce the issue on the CPU by inserting `torch.manual_seed(8017)` at the top of @michaelklachko's script.

So both CPU and CUDA kernels currently can produce negative indices. The issue is in the max_pool() kernels, which leave `maxindex==-1` if all input values are `-inf` or `-FLOAT_MAX`.

It has always been that way (before porting to ATen), so there's a chance that the behavior was intentional.  But I can't see the reason. :)

So #23161 changes the behavior to allow `-inf` in the output values and set the indices properly.

**Comment by michaelklachko** [comment]
@skrah thank you! On a higher level, is there a way to enable a warning message when any of the values in the graph are NaNs or infs? Similar to how numpy warns when we try to calculate "a mean of an empty slice", etc?

**Comment by skrah** [comment]
@michaelklachko Yes, in your example you can use this context manager:

```python
                with autograd.detect_anomaly():
                    grads = torch.autograd.grad(loss, model.parameters(), create_graph=True)

                    grad_sum = 0
                    for grad in grads:
                        grad_sum += 0.1 * grad.pow(2).sum()

                    grad_sum.backward(retain_graph=False)
```

This detects `NaNs` and `infs`:

```
Traceback (most recent call last):
  File "adb.py", line 48, in <module>
    grads = torch.autograd.grad(loss, model.parameters(), create_graph=True)
  File "/home/stefan/rel2/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in grad
    inputs, allow_unused)
RuntimeError: Function 'LogSoftmaxBackward' returned nan values in its 0th output.
```

**Comment by michaelklachko** [comment]
Oh wow! This is very useful!
