### ISSUE TITLE
ubuntu Build Libtorch source error

### ISSUE THREAD

**Issue by xiaoranchenwai** [pytorch/pytorch#20469]
[ 25%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/python/python_generator.cc.o
[ 25%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/ruby/ruby_generator.cc.o
[ 25%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/subprocess.cc.o
[ 25%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/zip_writer.cc.o
[ 25%] Linking CXX static library ../../../lib/libprotoc.a
[ 25%] Built target libprotoc
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "../tools/build_libtorch.py", line 30, in <module>
    subprocess.check_call(command, universal_newlines=True, env=my_env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/xiaoran/pytorch/tools/build_pytorch_libs.sh', '--use-cuda', '--use-nnpack', '--use-mkldnn', '--use-qnnpack', 'caffe2']' returned non-zero exit status 2

**Comment by pietern** [comment]
The logs you posted doesn't actually contain the error in question; could you post your full logs?

**Comment by xiaoranchenwai** [comment]
I have solved the question,thank you.

**Comment by huolianchu** [comment]
> 我已经解决了这个问题，谢谢。

How did you solve it?
