### ISSUE TITLE
Implementing GELU activation

### ISSUE THREAD

**Issue by ghost** [pytorch/pytorch#20464]
Gaussian Error Linear Unit (GELU) has become really mainstream with models such as BERT using it. But nn.modules.activation doesn't have a GELU implementation. Feature request to expand the arsenal of activation functions available right off the bat in Pytorch :)

I could work on it, to get it merged upstream if assigned.

**Comment by Kaixhin** [comment]
This is fairly simple (see below for what would need to be added to `functional.py`), but seeing as it is common enough now could be worthwhile. If you're able to submit a PR with this (including a Module that wraps this and tests as necessary) then that would be useful.

```py
def gelu(x):
  return 0.5 * x * (1 + torch.tanh(math.sqrt(math.pi / 2) * (x + 0.044715 * x ** 3)))
```

**Comment by jidroid404** [comment]
@Kaixhin How come it's to be added to `functional.py` and not `activation.py`?

**Comment by Kaixhin** [comment]
The default is to create a functional interface in `functional.py` first. You'll see that many activation modules are basically wrappers around a function.

**Comment by jidroid404** [comment]
@Kaixhin Could you please point me to a PR on some other activation function that was eventually merged so that I could wrap my head around the workflow and pulling it off ! Thanks

**Comment by Kaixhin** [comment]
You can have a look at https://github.com/pytorch/pytorch/pull/8551 . I haven't contributed in a long time so can't give you more detailed advice - do your best and open a PR and a maintainer should be able to help you from there.

**Comment by soumith** [comment]
fixed via PR https://github.com/pytorch/pytorch/pull/20665

**Comment by Jagerjaque** [comment]
Seems like this was mistakenly left open.

**Comment by mruberry** [comment]
Closing since we now have gelu.

**Comment by luoshao23** [comment]
> ```python
> 0.044715
> ```

the definition is wrong,  `math.sqrt(math.pi / 2)` should be `math.sqrt(2 / math.pi)`
