### ISSUE TITLE
THCudaCheck FAIL in torch.sort()

### ISSUE THREAD

**Issue by zsrkmyn** [pytorch/pytorch#2049]
`torch.sort()` reports error when the tensor to be sorted is large:
```
(ins)>>> import torch
(ins)>>> r = torch.randn(1,2000).cuda()
(ins)>>> s, i = torch.sort(r)
THCudaCheck FAIL file=/tmp/makepkg/python-pytorch-git/src/pytorch/torch/lib/THC/generated/../generic/THCTensorSort.cu line=153 error=7 : too many resources requested for launch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cuda runtime error (7) : too many resources requested for launch at /tmp/makepkg/python-pytorch-git/src/pytorch/torch/lib/THC/generated/../generic/THCTensorSort.cu:153
(ins)>>> 
```
When the size of the tensor is small, say 1x1000, the error won't occur.

I tried it with both version 0.1.12 and the latest commit 1ef1dd9. The PyTorch is built with cuda 8.0.61 and cudnn 6.0.21. The Python version is 3.6.1. And the device is Tesla K40c. Should I provide more details? :)

**Comment by soumith** [comment]
this is sufficient to reproduce the issue. thanks, we'll fix this soon.
