### ISSUE TITLE
Install only a specific version via pip

### ISSUE THREAD

**Issue by pdilyard** [pytorch/pytorch#20494]
Including `torch==1.1.0` as a requirement ends up installing ~500mb package which is not desirable in a production environment (we build a lot of containers and this makes them way larger than necessary).

I know you can install a wheel directly like this: `pip install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp36-cp36m-linux_x86_64.whl`, however, when you run `pip freeze` you end up with `torch==1.0.1` again, which means that this package doesn't fit into our normal workflow (`pip freeze > requirements.txt`).

Is there a way to just install the CPU version of PyTorch that we need in prod? Something like `pip install torch-cpu`, for example.

**Comment by wanchaol** [comment]
quoting this from https://pytorch.org, you can run the following to install the cpu only version of 1.1.0
```
pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
pip3 install torchvision
```

**Comment by pdilyard** [comment]
Yep, but as described in my issue, if you do that and then run `pip feeze > requirements.txt`, you end up with `torch==1.1.0` in your requirements file, which means that other users and build tools will still be downloading the full package.

**Comment by soumith** [comment]
@pdilyard we cannot upload pytorch's cpu-only wheels to pypi under a different package name, if that's what you are asking. this is because pypi has a 60MB package limit. For current `pip install torch`, we got special one-time permission to bump up the limit.

**Comment by soumith** [comment]
would conda work for you? we ship `pytorch-cpu` package on conda in our `pytorch` channel

**Comment by mrava87** [comment]
Hi, any plans to add v1.2.0 to the condo channel?

**Comment by soumith** [comment]
@mrava87 it's already in the conda `pytorch` channel. We dont know when it will be ready on the default anaconda channel.

**Comment by mrava87** [comment]
@soumith thanks a lot for reply. Sorry I was not clear, I meant pytorch-cpu. All I can find is this that seem to be still at 1.1.0 (https://anaconda.org/pytorch/pytorch-cpu)

**Comment by soumith** [comment]
@mrava87 our commands for `cpu` build have changed, see `pytorch.org` for updated commands.

**Comment by soumith** [comment]
it is something like `conda install pytorch  cpuonly -c pytorch-nightly`

**Comment by mrava87** [comment]
Fantastic, thanks a lot

**Comment by soumith** [comment]
this issue can now be closed, because we use local version identifiers. 
For example, CPU-only version is:
```
pip3 install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```

So, in `requirements.txt`, having a constraint such as `1.2.0+cpu` should be good.

We dont ship the variant wheels via PyPI though, and have no plans to do so (PyPI doesn't allow local version identifiers to be uploaded live)
