### ISSUE TITLE
[Feature request] Module.cuda() sets the Module._cuda flag

### ISSUE THREAD

**Issue by meownoid** [pytorch/pytorch#2050]
There is some situations where tensors are dynamically created in the forward pass. [VAE](https://github.com/pytorch/examples/tree/master/vae) for example. The proposed feature eliminates the need to explicitly pass a *cuda* parameter.

**Comment by soumith** [comment]
this isn't a great idea, it doesn't generalize to multi-GPU models, and likely adds to confusion.

You can manually set a `_cuda` `@property` in your particular models using this code in your class definition: 

```
@property
def _cuda(self):
    return next(self.parameters()).is_cuda
```

**Comment by jekbradbury** [comment]
@meownoid in general the easiest way to do what you want is to use `tensor.new(sizes)`, which creates a new tensor on the same device as `tensor`.
