### ISSUE TITLE
MobileNetV2 export to ONNX fails

### ISSUE THREAD

**Issue by vuzelac-cadence** [pytorch/pytorch#20516]
## 🐛 Bug
Converting mobilenet_v2  from examples directory into ONNX fails with:
```
 ...
File "...\torch\onnx\utils.py", line 189, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
File "...\torch\onnx\__init__.py", line 57, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
File "...\torch\onnx\utils.py", line 593, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
File "...\torch\onnx\symbolic_opset9.py", line 208, in symbolic
    dim, keepdim = sym_help._get_const(dim, 'i', 'dim'), sym_help._get_const(keepdim, 'i', 'keepdim')
File "...torch\onnx\symbolic_helper.py", line 114, in _get_const
    return _parse_arg(value, desc)
File "...\torch\onnx\symbolic_helper.py", line 73, in _parse_arg
    return int(tval)
ValueError: only one element tensors can be converted to Python scalars
```

## To Reproduce

mobilenet_v2 obtained using `examples/imagenet/main.py` . Converted using:
```
model.train(False)
input = torch.randn(1, 3, 224, 224, requires_grad=True)
output = model(input)
torch_out = torch.onnx._export(model, input, "model.onnx", export_params=True, do_constant_folding=True)
```
## Environment
PyTorch version: 1.1.0a0+6e82b1c
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
CMake version: version 3.13.3

Python version: 3.7
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVS 310
Nvidia driver version: 353.62
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[pip3] torch-nightly==1.1.0.dev20190513
[pip3] torchvision==0.2.2.post3
[pip3] torchvision-nightly==0.2.3

**Comment by BowenBao** [comment]
Thanks for providing the repro. Seems this part needs to be updated to handle multi dims https://github.com/pytorch/pytorch/blob/62af37aa8896848bb808a33f9205d71bccf8c969/torch/onnx/symbolic_opset9.py#L211

**Comment by Wong-Charles** [comment]
Have you solved this problem? I also encountered the same problem.

**Comment by frizk123** [comment]
look into the mobilenet.py in torchvision, change the forward function:
    def forward(self, x):
        x = self.features(x)
        # x = x.mean([2, 3])   this line will result in bug
        x = x.mean(2).mean(3)
        x = self.classifier(x)
        return x

**Comment by Wong-Charles** [comment]
> look into the mobilenet.py in torchvision, change the forward function:
> def forward(self, x):
> x = self.features(x)
> # x = x.mean([2, 3]) # this line will result in bug
> x = x.mean(3).mean(2)
> x = self.classifier(x)
> return x

Thank you for you answer, it works for me.

**Comment by sdews** [comment]
> look into the mobilenet.py in torchvision, change the forward function:
> def forward(self, x):
> x = self.features(x)
> # x = x.mean([2, 3]) # this line will result in bug
> x = x.mean(3).mean(2)
> x = self.classifier(x)
> return x

It works. Thanks。

**Comment by spandantiwari** [comment]
Closing this issue as it seems to be resolved.
