### ISSUE TITLE
nn.Upsample scale_factor does not support tuple inputs

### ISSUE THREAD

**Issue by amirmk89** [pytorch/pytorch#20523]
## 🐛 Bug

When adding an nn.Upsample module with different scale factors per axis, i.e. a tuple of floats matching input size, a TypeError is raised.

## To Reproduce

import torch.nn as nn
upsample_layer = nn.Upsample(scale_factor=(2,2))

Fails and raises: 
TypeError: float() argument must be a string or a number, not 'tuple'

According to the docs, it should handle, and in previous versions (0.4.0) it did. Broke after upgrading to 1.1.0

Likely to be caused by the added type check not supporting tuples in nn/modules/upsampling.py line 125:
        self.scale_factor = float(scale_factor) if scale_factor else None
Which cannot handle tuple inputs.

## Environment
PyTorch 1.1.0

**Comment by vishnusanjayrs** [comment]
which version has the fix ? upsampling with tuples for scale factor is still not working in latest pytorch version
