### ISSUE TITLE
Segmentation fault (core dumped) when passing empty Tensors to pack_padded_sequence

### ISSUE THREAD

**Issue by JamieCT** [pytorch/pytorch#20529]
Passing an empty tensor (so with shape (0,n,m)) to pack_padded_sequence causes a "segmentation fault (core dumped)"

Produce the error:
```
import torch
from torch.nn.utils.rnn import pack_padded_sequence
#bs, max_sequence_len, emb_dim
x = torch.zeros([16,10,20])
length = torch.zeros([16])
mask = [length != 0]
masked_x = x[mask]
masked_length = length[mask]
print(masked_x.shape, masked_length.shape)
pack_padded_sequence(masked_x, masked_length, batch_first = True)
```

Expected behavior:
An exception raised stating that the input tensor must not be empty.

Environments created on:
-PyTorch 1.0, Windows (installed via conda), CUDA (9.0)
-PyTorch 1.0, Linux (installed via pip), CUDA ('9.0.176')

Thanks,
Jamie

**Comment by ezyang** [comment]
Reproduced on 5fcd37bd8fcd0d392e2fcacf4ab11dd43bb0d108, this should be fixed.

**Comment by t-vi** [comment]
I'll take a stab at fixing this.
@JamieCT thank you for reporting this and the reproduction script. This is very useful!

**Comment by LeviViana** [comment]
@t-vi I saw your great video where you fix this bug, thanks for that BTW. But, I noticed something that might improve the error report. Indeed, in the following line we assume that `input` has at least 2 dimensions: 

https://github.com/t-vi/pytorch/blob/eb0fea38493102e2278a1142329e9544b08d605f/aten/src/ATen/native/PackedSequence.cpp#L21

I was wandering whether it could be useful to insert something like:

```
TORCH_CHECK(input.dim() > 1, "The input must have at least 2 dimensions.");
```

**Comment by t-vi** [comment]
@LeviViana sounds like a good addition, the `IndexError` currently thrown certainly isn't optimal. More to your point, it might be worth going over all the functions in `torch.nn.utils.rnn` / `PackedSequence.cpp` and seeing how well they check their inputs. Do ping me If you want to put up a PR. (I don't think you need to file a separate issue report.)

**Comment by LeviViana** [comment]
@Dorozhko-Anton
