### ISSUE TITLE
nn.CTCLoss RuntimeError on GPU

### ISSUE THREAD

**Issue by ypw-rich** [pytorch/pytorch#20522]
## 🐛 Bug

nn.CTCLoss Run the official documentation sample code works fine on the CPU but  RuntimeError on the GPU.

## To Reproduce

```py
import torch
import torch.nn as nn
import torch.nn.functional as F

>>> T = 255      # Input sequence length
>>> C = 20      # Number of classes (excluding blank)
>>> N = 16      # Batch size
>>> S = 30      # Target sequence length of longest target in batch
>>> S_min = 10  # Minimum target length, for demonstration purposes
>>>
>>> # Initialize random batch of input vectors, for *size = (T,N,C)
>>> input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()
>>>
>>> # Initialize random batch of targets (0 = blank, 1:C+1 = classes)
>>> target = torch.randint(low=1, high=C+1, size=(N, S), dtype=torch.long)
>>>
>>> input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)
>>> target_lengths = torch.randint(low=S_min, high=S, size=(N,), dtype=torch.long)

input = input.cuda()
target = target.cuda()
input_lengths = input_lengths.cuda()
target_lengths = target_lengths.cuda()

>>> ctc_loss = nn.CTCLoss()
>>> loss = ctc_loss(input, target, input_lengths, target_lengths)
>>> loss.backward()
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-24c5c245c677> in <module>
      1 ctc_loss = nn.CTCLoss()
      2 loss = ctc_loss(input, target, input_lengths, target_lengths)
----> 3 loss.backward()

~/anaconda3/lib/python3.7/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    105                 products. Defaults to ``False``.
    106         """
--> 107         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    108 
    109     def register_hook(self, hook):

~/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     91     Variable._execution_engine.run_backward(
     92         tensors, grad_tensors, retain_graph, create_graph,
---> 93         allow_unreachable=True)  # allow_unreachable flag
     94 
     95 

RuntimeError: setStorage: sizes [16, 255, 31], strides [15045, 59, 2], and storage offset 0 requiring a storage size of 240722 are out of bounds for storage with numel 240720
```

See https://gist.github.com/ypw-rich/faafe22d108c4fe24f128ecb4aaabda3

## Expected behavior

Expect same grad on CPU.

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.56
cuDNN version: /data/ocr/bin/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] numpydoc==0.8.0
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2.post3
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.3                      199
[conda] mkl-service               1.1.2            py37he904b0f_5
[conda] mkl_fft                   1.0.10           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torchvision               0.2.2.post3              pypi_0    pypi

**Comment by ngimel** [comment]
cc @t-vi

**Comment by ngimel** [comment]
There's something fishy with the strides, strides [...,59,2] for a tensor with the last dimension [...,31] indicate self-overlapping tensor, which is very rarely the intention.

**Comment by t-vi** [comment]
@ypw-rich thank you for reporting the bug with a repro! This is very helpful.

So what happens is that max_target_size isn't the max target length passed (which it should be) but taken from the targets shape. I'll fix this.
Also the example has a bug regarding the shape of input, the last dim should be C+1.

**Comment by nguyenvulebinh** [comment]
@t-vi I found that version torch 1.1.0 still get this error but it's fine if I install version nightly. The problem is if I install the nightly version, I can't use torchvison 0.3.0. How can I deal with this situation?

**Comment by t-vi** [comment]
@fmassa might know if there are nightlies for torchvision or you might compile torchvision from source (it's a breeze).
As a workaround you could use a hook zeroing gradients outside the mask.
Sorry about the inconvenience.

**Comment by nguyenvulebinh** [comment]
Perfect! I compile torchvision from source and it works well. Thanks you @t-vi
