### ISSUE TITLE
Wrong CMake version in libtorch C++ binary packages

### ISSUE THREAD

**Issue by blackccpie** [pytorch/pytorch#20525]
## 🐛 Bug

CMake version (in `TorchConfigVersion.cmake`) seems stuck to 1.0.0 in the latest libtorch C++ windows packages (CUDA or not).
This problem may also have affected the previous 1.0.1 packages.

Another big problem for me is that I can't find any more link to download libtorch C++ 1.0.1 packages, 
upon which I based all my current developments.

## To Reproduce

Download the latest package here:
https://download.pytorch.org/libtorch/cu90/libtorch-win-shared-with-deps-latest.zip

## Expected behavior

`TorchConfigVersion.cmake` with correct version.

## Environment

 - PyTorch Version: 1.1
 - OS: Windows
 - How you installed PyTorch: binary package
 - CUDA/cuDNN version: 9

Thanks for your help,

 Albert

**Comment by peterjc123** [comment]
cc. @pjh5

**Comment by pjh5** [comment]
The 1.0.1 packages are still, just the latest does not point to them. The link will be like https://download.pytorch.org/libtorch/cu90/libtorch-win-shared-with-deps-1.0.1.zip . We'll look into the version difference

**Comment by pjh5** [comment]
cc @soumith

**Comment by soumith** [comment]
I can confirm that the binary being linked is correct (i.e. `latest` is from v1.1.0).

@peterjc123 for some reason somewhere in the Windows build scripts 1.0.0 is being hard-coded as the cmake `TORCH_VERSION` variable. Any ideas where it's hard-coded from?

**Comment by peterjc123** [comment]
@soumith Is it set here? https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L224

**Comment by soumith** [comment]
yes, let's do that
