### ISSUE TITLE
[MacOS] datasets.ImageFolder() silently fails conversion for 16-bit PNG

### ISSUE THREAD

**Issue by neoinmtv** [pytorch/pytorch#20524]
The following code falsely converts my 16-bit PNG (0-65535, mean ~40000) into weird (0-1, mean 0.99) distributions. This wasted me ~3 hours to debug !!! Please at least show error message instead of silently fail !!!!
I attached the pngs, when I converted my PNG to 8-bit, it works.

Note that standalone `transforms.ToTensor()(PIL Image)` always works, see below.

My code following https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html:
```
import torch,PIL
from PIL import Image
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import numpy as np
import cv2
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
from collections import Counter
import copy
print(PIL.__version__)
print(torch.__version__)
print(torchvision.__version__)

plt.ion()   # interactive mode

# Data augmentation and normalization for training
# Just normalization for validation
data_transforms = {
    'train': transforms.Compose([
#         transforms.RandomResizedCrop(224),
        transforms.Resize((256,256)),
#         transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
#         transforms.Normalize((0,0,0), (0.1,0.1,0.1))
    ]),
    'val': transforms.Compose([
#         transforms.RandomResizedCrop(224),
        transforms.Resize((256,256)),
#         transforms.CenterCrop(224),
        transforms.ToTensor(),
#         transforms.Normalize((0.5,0.5,0.5), (1,1,1))
#         transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
#         transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

data_dir = 'data/hymenoptera_data'
data_dir = 'data/m_data'
image_datasets = {x: datasets.ImageFolder(os.path.join(data_dir, x),
                                          data_transforms[x])
                  for x in ['train', 'val']}
dataloaders = {x: torch.utils.data.DataLoader(image_datasets[x], batch_size=4,
                                             shuffle=0, num_workers=4)
              for x in ['train', 'val']}
dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'val']}
class_names = image_datasets['train'].classes

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

def imshow(inp, title=None):
    """Imshow for Tensor."""
    print(inp.shape) # m_data = torch.Size([3, 260, 1034])
    s(inp.numpy())
    # ants = torch.Size([3, 260, 1034])
    inp = inp.numpy().transpose((1, 2, 0))
#     mean = 0#np.array([0.485, 0.456, 0.406])
#     std = 0.1#np.array([0.229, 0.224, 0.225])
#     inp = std * inp + mean
#     inp = np.clip(inp, 0, 1)
#     s(inp)
    plt.imshow(inp)
    if title is not None:
        plt.title(title)
    plt.pause(0.001)  # pause a bit so that plots are updated


# Get a batch of training data
inputs, classes = next(iter(dataloaders['train']))
a=inputs.numpy()[0,:,:,:].transpose((1, 2, 0))
s(a)
plt.imshow(a), plt.pause(0.001)

# Make a grid from batch
out = torchvision.utils.make_grid(inputs)

d1 = 'data/hymenoptera_data'
d2 = 'data/m_data'
im = transforms.ToTensor()(Image.open(d2+'/train/benign/0.png')).numpy().transpose((1,2,0))
s(im)
def s(a):
    print(a.shape, a.max(), a.min(), a.mean(), a.std(), Counter(a.ravel()).most_common()[:10])
```

//print(PIL.__version__)
//print(torch.__version__)
//print(torchvision.__version__)
5.4.1
1.1.0
0.2.2

#Code Output (WRONG output when using 16-bit PNG): 
cpu
(256, 256, 3) 1.0 0.0 **0.96930856 0.16557895** [(1.0, 188979), (0.0, 4488), (0.3137255, 144), (0.56078434, 135), (0.8117647, 117), (0.9372549, 114), (0.6862745, 114), (0.0627451, 108), (0.4392157, 93), (0.1882353, 69)]

(224, 224, 1) 65535 0 **42820.1917450574 14888.386293001755** [(0, 1511), (54708, 117), (54611, 116), (54489, 114), (54513, 113), (55001, 111), (54002, 109), (54172, 108), (53660, 107), (53391, 107)]

#Code Output (correct when using 8-bit PNG): 
cpu
(256, 256, 3) 0.9607843 0.0 **0.65344715 0.22703604** [(0.0, 5157), (0.827451, 4164), (0.83137256, 4098), (0.8235294, 4041), (0.8352941, 3846), (0.81960785, 3714), (0.8392157, 3639), (0.7764706, 3432), (0.8156863, 3375), (0.77254903, 3303)]

(224, 224, 1) 1.0 0.0 **0.65339714 0.22718629** [(0.0, 1539), (0.83137256, 1087), (0.8235294, 970), (0.8392157, 966), (0.827451, 941), (0.81960785, 937), (0.8156863, 896), (0.78039217, 895), (0.8352941, 855), (0.7647059, 832)]

 - OS (e.g., Linux): Mac
 - How you installed PyTorch (`conda`, `pip`, source): pip

![0_8bit](https://user-images.githubusercontent.com/4177403/57758574-d1556d80-76ac-11e9-946e-35e9cc13784f.png)
![0_16bit](https://user-images.githubusercontent.com/4177403/57758587-d6b2b800-76ac-11e9-828f-78e800d44666.png)

**Comment by soumith** [comment]
it's well-documented in the torchvision docs: https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.ToTensor

Also, the issue should be on https://github.com/pytorch/vision

**Comment by myproject24** [comment]
Hi, @ezyang @apaszke @neoinmtv @soumith what is the Mac machine requirements to install caffe2?

I have Mac mini with 500GB storage, 4GB RAM, and Intel Core i5 processor. is it possible to install caffe2 on my Mac mini?

**Comment by williford** [comment]
The relevant issue in pytorch/vision is: https://github.com/pytorch/vision/issues/2218
