### ISSUE TITLE
Unfork sleef

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#20535]
We are currently tracking a fork of sleef that lives in https://github.com/zdevito/sleef This is bad because it prevents us from easily taking upstream fixes; e.g., the fix for https://github.com/pytorch/pytorch/issues/20404 We should unfork.

We are running two patches:
- https://github.com/zdevito/sleef/commit/191f655caa25526ae226cf88dd2529265176014a it is fixed upstream by 79df29e3a2f9a4ef9c4220a70c1b40cf120e7e17
- https://github.com/zdevito/sleef/commit/9b249c53a80343cc1a394ca961d7d5696ea76409 reported upstream at https://github.com/shibatch/sleef/issues/261 but we haven't submitted the PR upstream yet

cc @zdevito @colesbury

**Comment by colesbury** [comment]
zdevito/sleef@9b249c5 is out as a PR: https://github.com/shibatch/sleef/pull/262

**Comment by colesbury** [comment]
Both changes are now merged upstream

**Comment by jerryzh168** [comment]
close?

**Comment by zdevito** [comment]
This shouldn't be closed until https://github.com/pytorch/pytorch/blob/master/.gitmodules#L84 no longer points to /zdevito/sleef. It would need a PR to switch the submodule and to test it doesn't break anything.
