### ISSUE TITLE
Saving state_dicts should capture shared state

### ISSUE THREAD

**Issue by nmatthews-asapp** [pytorch/pytorch#20546]
## 🚀 Feature
Add metadata to the state_dict to support round trip saving and loading. Specifically, if the same object appears more than once in the object hierarchy, then that fact should be captured in the state_dict representation so that an object produced via `load_state_dict` is equivalent to the original object.

## Motivation

In a hierarchy of nn.Modules wherein one object can appear in multiple places, the state_dict shows the state in all places, but when the object is mutated via one of its attribute aliases, the state will update in all places. This is good and correct, but when you save this state_dict this information is lost; If you load the state_dict from a file, what was once a single object is now multiple objects that are completely separate in memory. This means that saving and loading in PyTorch is not round-trip equivalent.

Ideally, saving an object x, and then loading x's state into a new object y should produce two objects that are completely equivalent, in other words x should equal y (besides the memory address)

Here is an example in code:
```python
class A(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.x = nn.Linear(2, 2)
class B(nn.Module):
    def __init__(self, *args, a=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.a = A() if a is None else a
class C(nn.Module):
    def __init__(self, *args, a=None, b=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.a = A() if a is None else a
        self.b = B() if b is None else b
```
And the actual behavior is:
```
>>> a = A()
>>> b = B(a=a)
>>> c = C(a=a, b=b)
>>> c.b.a is c.a
True
>>> c.b.a.x[0][0] = 0.1111
>>> c.a.x[0][0]
0.1111
>>> s = c.state_dict()
>>> c2 = C()
>>> c2.load_state_dict(s)
>>> c2.b.a is c2.a
False
```
Ideally, the final check would produce:
```
>>> c2.b.a is c2.a
True
>>> c2.b.a.x[0][0] = 0.2222
>>> c2.b.a.x[0][0] == c2.a.x[0][0]
True
```

## Pitch

Using the `state_dict._metadata`, we could add information about children modules being equivalent. This information can be duplicated across all common ancestors. Then, either before or after loading state in `load_state_dict` or its helper methods, you could check
`if self.b.a is not self.a: self.b.a = self.a`

## Alternatives

[TODO?]

**Comment by soumith** [comment]
from what I know, this is already true for Tensors, i.e. a state_dict saved will only save a given storage once. So, if two Tensors are sharing a single Storage, their "sharing" mechanism should be preserved even after reloading.

If that's not the case as of today, we have regressed.

**Comment by soumith** [comment]
okay, so I looked into this, with the following snippet:

```
import torch
import torch.nn as nn

class A(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.x = nn.Linear(2, 2)
class B(nn.Module):
    def __init__(self, *args, a=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.a = A() if a is None else a
class C(nn.Module):
    def __init__(self, *args, a=None, b=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.a = A() if a is None else a
        self.b = B() if b is None else b


a = A()
b = B(a=a)
c = C(a=a, b=b)
print(c.b.a is c.a)
c.b.a.x.weight[0][0] = 0.1111
print(c.a.x.weight[0][0])
s = c.state_dict()
c2 = C()
c2.load_state_dict(s)
print(c2.b.a is c2.a)
c2.b.a.x.weight[0][0] = 0.2222
print(c2.b.a.x.weight[0][0] == c2.a.x.weight[0][0])
print("^^ shuld be 0.2222")
```

What we do support is doing `torch.save(C, 'c.pth')` and reloading it with `torch.load` will preserve state. I guess we dont support it with `state_dict` and `load_state_dict` yet, but we should

**Comment by nmatthews-asapp** [comment]
Actually I realized under a specific circumstance this does work, and the following snippet clarifies:
```
a = A()
b = B(a=a)
c = C(a=a, b=b)
assert c.b.a is c.a
c.b.a.x.weight[0][0] = 0.1111
assert c.a.x.weight[0][0] == 0.1111
s = c.state_dict()
a2 = A()
b2 = B(a=a2)
c2 = C(a=a2, b=b2)
c2.load_state_dict(s)
assert c2.b.a is c2.a
c2.b.a.x.weight[0][0] = 0.2222
assert c2.b.a.x.weight[0][0] == c2.a.x.weight[0][0]
c3 = C()
c3.load_state_dict(s)
# Note the NOT and != in the following checks
assert c3.b.a is not c3.a
c3.b.a.x.weight[0][0] = 0.3333
assert c3.b.a.x.weight[0][0] != c3.a.x.weight[0][0]
```
this code passes in `torch==1.1.0` with no assertion errors

**Comment by colesbury** [comment]
I don't see anything we should change in PyTorch. `load_state_dict` doesn't change the structure of the Module and **should not** change the structure.

If you create your first version with:

```
a = A()
b = B(a=a)
c = C(a=a, b=b)
```

Then your second version of C needs to be created with the same structure:

```
a2 = A()
b2 = B(a=a2)
c2 = C(a=a2, b=b2)
```

If you instead do:

```
c2 = C()
```

You've create a different structure and shouldn't expect it to work the same as your first incarnation.

**Comment by nmatthews-asapp** [comment]
Ok this makes sense to me. Sounds like this can be closed
