### ISSUE TITLE
zero-dimensional numpy arrays should raise exception on from_numpy

### ISSUE THREAD

**Issue by serhii-havrylov** [pytorch/pytorch#2055]
It seems that the way how slicing is handled in pytorch is a little bit inconsistent with numpy and with pytorch itself. For example, one can create a tensor with empty dimension like 0x3 matrix (in numpy and pytroch). However, when trying to get a slice that will lead to no dimension tensor "ValueError: result of slicing is an empty tensor" error occurs. Is there any reason for implementing it differently compare to numpy?

**Comment by soumith** [comment]
pytorch doesn't have zero-dimensional Tensors. You cannot have any dimension be of size 0.

**Comment by serhii-havrylov** [comment]
I see, then I believe this line of code `a = torch.from_numpy(np.zeros((0,3)))` should raise an exception. Having zero-dimensional Tensors is quite convenient sometimes. I was just wondering is there any particular reason for not having them?

**Comment by ml9951** [comment]
As @serhii-havrylov mentioned:

> Having zero-dimensional Tensors is quite convenient sometimes. I was just wondering is there any particular reason for not having them?

This would be a very convenient feature and would also be consistent with what numpy does.  For example when doing object localization, I represent the targets as a two dimensional tensor where each row represents the coordinates of the bounding box of a particular target.  If a particular sample doesn't have any targets, then we need to add a bunch of extra checks to see if the tensor is empty.  Instead, it would be great, if I could just do `targets[:, :2]` to get all of the upper left coordinates and have this return an empty tensor if `targets` is empty.  

Is there something fundamental to torch that would make this difficult?  If not I'd be willing to look into submitting a PR.

**Comment by soumith** [comment]
> Is there something fundamental to torch that would make this difficult? If not I'd be willing to look into submitting a PR.

The Tensor backend is not aware of zero-dim tensors, so a bunch of things in the backend need to be fixed fundamentally. changes are going to be hard, prob 100s or 1000s of lines touched.
