### ISSUE TITLE
Can't build caffe2 on windows

### ISSUE THREAD

**Issue by VirginianBlue** [pytorch/pytorch#20568]
I update my CUDA from 8.0 to 10.0 but get the same problem.
I excute 

> scripts\build_windows.bat`

And got this error:

> [1149/1232]` Linking CXX executable bin\kernel_functor_test.exe
FAILED: bin/kernel_functor_test.exe
Cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=caffe2\CMakeFiles\kernel_functor_test.dir --rc=C:\PROGRA~2\WI3CF2 ~1\10\bin\100177~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\mt.exe --manifests -- C :\PROGRA~2\MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo caffe2\CMakeFiles\kernel_functor_test.dir\__\aten\src \ATen\core\op_registration\kernel_functor_test.cpp.obj /out:bin\kernel_functor_test.exe /implib:lib\kernel_functor_test.lib /pdb:bin\kernel_functor_test.pdb /version:0.0 /INCREMENTAL:NO /subsystem:console lib\ Gtest_main.lib -WHOLEARCHIVE:E:/opencv_build/pytorch-zip/pytorch/lib/caffe2.lib -WHOLEARCHIVE:E:/opencv_build/pytorch-zip/pytorch/lib/caffe2_protos.lib lib\cpuinfo.lib lib\clog. Lib lib\foxi_loader.lib -WHOLEARCHIVE:E:/opencv_build/pytorch-zip/pytorch/lib/onnx.lib lib\onnx_proto.lib lib\libprotobuf.lib -WHOLEARCHIVE:E:/opencv_build/pytorch-zip/pytorch/lib /Caffe2_perfkernels_avx.lib -WHOLEA RCHIVE: E:/opencv_build/pytorch-zip/pytorch/lib/Caffe2_perfkernels_avx2.lib lib\c10.lib -WHOLEARCHIVE:E:/opencv_build/pytorch-zip/pytorch/lib/Caffe2_perfkernels_avx512.lib lib\gtest.lib kernel32.lib User32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "C:\PROGRA~2\MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo caffe2\CMakeFiles\kernel_functor_test.dir\ __\aten\src\ATen\core\op_registration\kernel_functor_test.cpp.obj /out:bin\kernel_functor_test.exe /implib:lib\kernel_functor_test.lib /pdb:bin\kernel_functor_test.pdb /version:0.0 /INCREMENTAL:NO / Subsystem:console lib\gtest_main.lib -WHOLEARCHIVE:E:/opencv_build/pytorch-zip/pytorch/lib/caffe2.lib -WHOLEARCHIVE:E:/opencv_build/pytorch-zip/pytorch/lib/caffe2_protos.lib lib\cpuinfo. Lib lib\clog.lib lib\foxi_loader.lib -WHOLEARCHIVE:E:/opencv_build/pytorch-zip/pytorch/lib/onnx.lib lib\onnx_proto.lib lib\libprotobuf.lib -WHOLEARCHIVE:E:/opencv_build/pytorch- Zip/pytorch/lib/Caffe2_perfkernels_avx.lib -WHOLEARCHIVE:E:/opencv_build/pytorch-zip/pytorch/lib/Caffe2_perfkernels_avx2.lib lib\c10.lib -WHOLEARCHIVE:E:/opencv_build/pytorch-zip/pytorch/lib/Caffe2_perfkernels_avx512 .lib lib\gtest.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32 .lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:bin\kernel_functor_test.exe.manifest" failed (exit code 1120) with the following output:
LINK : warning LNK4098: The default library "MSVCRT" conflicts with the use of other libraries; please use /NODEFAULTLIB:library
Caffe2.lib(miniz.c.obj) : warning LNK4217: Locally defined symbol _localtime64_s is imported in function localtime_s
Caffe2.lib(miniz.c.obj) : warning LNK4217: Locally defined symbol _time64 is imported in function mz_zip_writer_add_mem_ex_v2
Caffe2.lib(miniz.c.obj) : warning LNK4217: Locally defined symbol _wassert is imported in function mz_zip_array_ensure_capacity
Caffe2.lib(miniz.c.obj) : warning LNK4217: Locally defined symbol free Imported in function miniz_def_free_func
Caffe2.lib(miniz.c.obj) : warning LNK4217: The locally defined symbol malloc is imported in the function miniz_def_alloc_func
Caffe2.lib(miniz.c.obj) : warning LNK4217: Locally defined symbol realloc is imported in function miniz_def_realloc_func
Caffe2.lib(miniz.c.obj) : error LNK2019: Unresolved external symbol __imp__mktime64, this symbol is referenced in function mktime
Bin\kernel_functor_test.exe : fatal error LNK1120: 1 external command that cannot be resolved
Ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "tools\build_libtorch.py", line 22, in <module>
    build_python=False, rerun_cmake=True, build_dir='.')
  File "E:\opencv_build\pytorch-zip\pytorch\tools\build_pytorch_libs.py", line 268, in build_caffe2
    check_call(build_cmd, cwd=build_dir, env=my_env)
  File "C:\Users\84206\Anaconda3\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '7']' returned non-zero exit status 1.
"Caffe2 building failed"

This ,https://github.com/pytorch/pytorch/issues/20420#issue-443213714, can't solve my problem.

I transforms my project from pytroch version to caffe2 version in python.And then,I want to use caffe2 in C++ project.How am I supposed to do?

My Environment:
Win10
VS2017 
CUDA10 whith cudnn7.5
Anaconda3 , python 3.6.8
Cmake 3.14.4

**Comment by VirginianBlue** [comment]
My build.ninjia:
[build.log](https://github.com/pytorch/pytorch/files/3185244/build.log)

**Comment by peterjc123** [comment]
From the log, looks like `miniz` is built with `/MD`, which should be `/MT`.

```
build caffe2\CMakeFiles\caffe2.dir\__\third_party\miniz-2.0.8\miniz.c.obj: C_COMPILER__caffe2 third_party\miniz-2.0.8\miniz.c || cmake_object_order_depends_target_caffe2
  DEFINES = -DAT_CORE_STATIC_WINDOWS=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DONNX_NAMESPACE=onnx_c2 -DUSE_MSC_ATOMICS=1 -D_CRT_SECURE_NO_DEPRECATE=1
  FLAGS = /EHa -openmp /MD /O2 /Ob2    -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -DCAFFE2_BUILD_MAIN_LIB -O2
  INCLUDES = -Iaten\src -I. -Ithird_party\protobuf\src -Icmake\..\third_party\benchmark\include -Icaffe2\contrib\aten -Ithird_party\onnx -Ithird_party\foxi -Icaffe2\aten\src\TH -Iaten\src\TH -Icaffe2\aten\src -Iaten\..\third_party\catch\single_include -Iaten\src\ATen\.. -Icaffe2\aten\src\ATen -Icaffe2\core\nomnigraph\include -Ithird_party\miniz-2.0.8 -Ic10\.. -Ithird_party\cpuinfo\include -Ithird_party\FP16\include -Icmake\..\third_party\googletest\googlemock\include -Icmake\..\third_party\googletest\googletest\include -Icmake\..\third_party\eigen -Icmake\..\third_party\pybind11\include -Icaffe2
  OBJECT_DIR = caffe2\CMakeFiles\caffe2.dir
  OBJECT_FILE_DIR = caffe2\CMakeFiles\caffe2.dir\__\third_party\miniz-2.0.8
  TARGET_COMPILE_PDB = caffe2\CMakeFiles\caffe2.dir\caffe2.pdb
  TARGET_PDB = lib\caffe2.pdb
```

**Comment by peterjc123** [comment]
Hey, would you please try if #20574 solves your problem?

**Comment by VirginianBlue** [comment]
> Hey, would you please try if #20574 solves your problem?

Thank you for that. It solve this problem. 
I get it at last:

> [1231/1232] Install the project...
-- Install configuration: "Release"
"Caffe2 built successfully"

But now,I am confused how to use caffe2 in VS2017. I can't follow the install introduction on[https://caffe2.ai/docs/cplusplus_tutorial.html](url) to use it on VS2017. And there is no build directory , no caffe2.sln or such this thing.And I add 

> $PYTORCH_DIRECTORY\caffe2\
> $PYTORCH_DIRECTORY\caffe2\core

to the Additional Including Directory. It still can't find <caffe2/core/predictor.h>
Am I miss some thing important or I make some mistakes?
And is there a new version install introduction for caffe2 using in VS2017?

**Comment by peterjc123** [comment]
Since you are using Ninja, there won't be `Caffe2.sln`. You just need to find `ninja.build`. The directory of that file is the build directory.
