### ISSUE TITLE
build: `cp _C.cpython-36m-x86_64-linux-gnu.so _C.so` after build

### ISSUE THREAD

**Issue by MInner** [pytorch/pytorch#2056]
For some reason otherwise the line `import torch._C` failed and it wasn't done during build. I am using `Ubuntu 14.04, Anaconda 3, Python 3.6`. Thanks.

**Comment by killeent** [comment]
@MInner Can you post the full flow that yields the import failure from a clean repo?

**Comment by soumith** [comment]
this is a weird python install. Under Python 3.6, _C.so shouldn't be called _C.so, but actually be called: `_C.cpython-36m-x86_64-linux-gnu.so`. That's what Python expects from it's extensions.

**Comment by davidmascharka** [comment]
I've seen this error if you try to `import torch` from inside the pytorch repo directory.

**Comment by kaiquewdev** [comment]
After the installation using `conda install pytorch` with `regression` examples the same stack trace error occurs this is the case message:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import torch
  File "/media/kaique/756ecb3f-4df3-4151-8967-572e968ec005/anaconda3/envs/chap/lib/python3.6/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: /media/kaique/756ecb3f-4df3-4151-8967-572e968ec005/anaconda3/envs/chap/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: nvrtcGetProgramLogSize

**Comment by kaiquewdev** [comment]
After that using conda: `conda install libtorch` tha same `regression` example works.
