### ISSUE TITLE
Is there a way to utilize ATen full lib by calling caffe2.python.core.CreateOperators?

### ISSUE THREAD

**Issue by zieitokk** [pytorch/pytorch#20577]
Hi I just wondering if there is a way to utilize ATen full lib by creating like
```
op = core.CreateOperator(
    "ATen",
    ["X2", "X1"],
    ["Y"],
    operator="grid_sampler"
)
```
I wanted to use grid_sampler function in ATen lib and I have checked the `native_functions.yaml` in `aten/src/ATen/native` which has function `grid_sampler`.

However when I run operators above, it shows an error claimed that

> Attempting to run unknown ATen operator configuration: grid_sampler

It's really appreciated that if someone can answer my question!

**Comment by li-roy** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
