### ISSUE TITLE
Change function that truncate to scalar_t on each atomicAdd

### ISSUE THREAD

**Issue by xmnlab** [pytorch/pytorch#20590]
## 🚀 Feature

at https://github.com/pytorch/pytorch/pull/19630/files#diff-5092da792c30694ee4adf0d0ae2a37c6R206 it is truncating to scalar_t on each atomicAdd call. It would be good to change that. See comments by @ngimel https://github.com/pytorch/pytorch/pull/19630#discussion_r281426912

## Motivation

Performance improving

**Comment by xmnlab** [comment]
@ngimel please feel free to add any more details about your thoughts on ths issue. Thank you so much!

**Comment by mruberry** [comment]
Closing due to age. @xmnlab, would you please update and reopen this with additional details if this issue still exists?

**Comment by xmnlab** [comment]
@mruberry IIRC I opened this issue to take notes from a PR review for a follow up task. Not sure if it is still relevant. Thanks!
