### ISSUE TITLE
Error: Could not find a version that satisfies the requirement torch==0.3.1 (from versions: 0.1.2, 0.1.2.post1) ERROR: No matching distribution found for torch==0.3.1

### ISSUE THREAD

**Issue by sshikha23** [pytorch/pytorch#20631]
I am trying to install torch=0.3.1

>pip install torch==0.3.1
Collecting torch==0.3.1
  ERROR: Could not find a version that satisfies the requirement torch==0.3.1 (from versions: 0.1.2, 0.1.2.post1)
ERROR: No matching distribution found for torch==0.3.1

I tried all the available answers to this questions but still i am unable to install it.
I am not getting what "**matching environment** and **what version** means.
I am using python=3.6

**Comment by colesbury** [comment]
Please provide the details requested in the issue template (operating system, etc.) and re-open the issue.
