### ISSUE TITLE
The item() operation changes the value?Is this a bug?

### ISSUE THREAD

**Issue by catqaq** [pytorch/pytorch#20639]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by catqaq** [comment]
a=torch.tensor(1.2000, device='cuda:0')
a.item()
got: 1.2000000476837158

How to avoid this?

**Comment by catqaq** [comment]
a=torch.tensor(1.2000, device='cuda:0')
a.item()
got: 1.2000000476837158

How to avoid this? It is caused by python or pytorch?

**Comment by fmassa** [comment]
This is not a bug. It's just that when we print, we truncated the displaying to a few digits. You can control it via `torch.set_printoptions` or something like that.
