### ISSUE TITLE
Build error with MSVC (aten\src\ATen\native\quantized\Copy.cpp)

### ISSUE THREAD

**Issue by Jonas1312** [pytorch/pytorch#20642]
## 🐛 Bug

```
..\aten\src\ATen\native\quantized\Copy.cpp(18): error C2065: 'src_data': undeclared identifier
..\aten\src\ATen\native\quantized\Copy.cpp(18): error C2672: 'at::quantize_val': no matching overloaded function found
..\aten\src\ATen\native\quantized\Copy.cpp(26): error C2780: 'T at::quantize_val(float,int32_t,float)': expects 3 arguments - 2 provided
```

## To Reproduce

```
set CMAKE_GENERATOR="Visual Studio 16 2019" x64

set DISTUTILS_USE_SDK=1

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64

set CMAKE_GENERATOR=Ninja

set REL_WITH_DEB_INFO=1

python setup.py install
```

**Comment by Jonas1312** [comment]
Might be related to @jerryzh168 last push #19932 and #19816

**Comment by jerryzh168** [comment]
Thanks for reporting, I will take a look

**Comment by ygwangthu** [comment]
move the sentence "float* src_data = src.data<float>();" into the function of "AT_DISPATCH_QINT_TYPES ..." solves my problem. It looks like:

  AT_DISPATCH_QINT_TYPES(self.scalar_type(), "Copy", [&]() {
    **float* src_data = src.data<float>();**
	scalar_t* self_data = self.data<scalar_t>();
    for (int i = 0; i < self.numel(); ++i) {
      self_data[i] = quantize_val<scalar_t>(
          self.q_scale().to<float>(),
          self.q_zero_point().to<int32_t>(),
          src_data[i]);
    }
  });

 Hope that will help you.

**Comment by Jonas1312** [comment]
I can confirm that @ygwangthu workaround works

**Comment by jerryzh168** [comment]
@Jonas1312 @ygwangthu could any of you submit a pr? I don't have windows environment setup right now so could not repro the compilation error.

**Comment by peterjc123** [comment]
@jerryzh168 I can repro the error if I build the caffe2 ci win job with ninja. Just add `pip install ninja` in `scripts\build_windows.bat`.

**Comment by jerryzh168** [comment]
@peterjc123 I'm landing the change by @Jonas1312 now.
