### ISSUE TITLE
torch.cat disconnecting graph 

### ISSUE THREAD

**Issue by uhmwpe** [pytorch/pytorch#20663]
### Bug
torch.cat appears to disconnect the graph. In effect, graph of each variable is cutoff when concatenated with another variable. 

### To Reproduce

    import torch
    from torch.autograd import Variable
    
    a = Variable(torch.Tensor([1., 3., 5.]), requires_grad=True)
    b = Variable(torch.Tensor([2., 4., 6.]), requires_grad=True)
    a = a.unsqueeze(1)
    b = b.unsqueeze(1)
    c = torch.matmul(a.t(), b)

    
    print(torch.autograd.grad(c, a, retain_graph=True)[0]) #returns b
    print(torch.autograd.grad(c, b, retain_graph=True)[0]) #returns a
    z = torch.cat((a,b), dim=1)
    print(torch.autograd.grad(c, z)[0]) 

The last line of code gives the error: "RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior."

### Expected Result
Prints a gradient corresponding to the gradient of the individual components

**Comment by colesbury** [comment]
You are asking for the derivative of `c` w.r.t. `z` but `c` is not specified as a function of `z`. I don't see a bug here.

You don't need `cat` or higher order differentiation to see this behavior:

```python
import torch

x = torch.tensor([1.], requires_grad=True)
y = x.clone()
z = x * 2
print(torch.autograd.grad(z, x))  # 2, OK
print(torch.autograd.grad(z, y))  # RuntimeError
```

**Comment by colesbury** [comment]
If you want to get the derivative w.r.t. to the cat operation you have to make `z` a function of the `cat` operation. For example:

```python
import torch

a = torch.tensor([1., 3., 5.], requires_grad=True)
b = torch.tensor([2., 4., 6.], requires_grad=True)
a = a.unsqueeze(1)
b = b.unsqueeze(1)
z = torch.cat((a, b), dim=1)
a1 = z[:, 0]
b1 = z[:, 1]
c = torch.matmul(a1.t(), b1)

print(torch.autograd.grad(c, a, retain_graph=True)[0]) #returns b
print(torch.autograd.grad(c, b, retain_graph=True)[0]) #returns a
print(torch.autograd.grad(c, z)[0]) 
```
