### ISSUE TITLE
Inconsistent behavior between jit loaded model and the one to be saved

### ISSUE THREAD

**Issue by zakizhou** [pytorch/pytorch#20676]
## To Reproduce

```
import torch
from torch import jit
from torch import nn
import numpy as np


class SubContainsVariable(jit.ScriptModule):
    def __init__(self):
        super(SubContainsVariable, self).__init__()
        self.v = nn.Parameter(torch.from_numpy(np.array(1.)))

    @jit.script_method
    def forward(self, x):
        return self.v * x


class ContainsVariable(jit.ScriptModule):
    def __init__(self):
        super(ContainsVariable, self).__init__()
        self.submodule = SubContainsVariable()
        self.submodule1 = jit.ScriptModule()
        self.submodule1.submodule2 = self.submodule
        self.v = nn.Parameter(torch.from_numpy(np.array(2.)))

    @jit.script_method
    def forward(self, x):
        return x + self.v + self.submodule(x) + self.submodule1.submodule2(x)


cv = ContainsVariable()
# both print True
print(cv.submodule is cv.submodule1.submodule2)
print(cv.submodule.v is cv.submodule1.submodule2.v)

jit.save(cv, "save/torchmodel.zip")
load = jit.load("save/torchmodel.zip")
# both print False
print(load.submodule is load.submodule1.submodule2)
print(load.submodule.v is load.submodule1.submodule2.v)
```

## Expected behavior
The results should be consistent between the saved and loaded

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0.1.post2
 - OS (e.g., Linux): mac osx
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):  from binary
 - Python version: 3.6
 - CUDA/cuDNN version: None
 - GPU models and configuration:None
 - Any other relevant information:None

**Comment by soumith** [comment]
@suo fyi it was labeled jit 9 days ago, but not triaged

**Comment by suo** [comment]
@zakizhou thanks for the report! This is because when we load the model, we create copies of each submodule. Can you explain your use case a little bit? e.g. why do you want to use the same module as a submodule in two different places.

**Comment by zakizhou** [comment]
@suo just for curiosity, no special use cases. So the dependencies of jit modules should be a tree not a DAG, is it right?

**Comment by suo** [comment]
Yes. Possibly we could fix serialization to more accurately track submodule identity, but absent a use case I think we'll put it on the back burner for now. Anyone feel free to comment if they need this functionality!

**Comment by zakizhou** [comment]
Thanks!
