### ISSUE TITLE
data loader wait for all workers

### ISSUE THREAD

**Issue by ali-r** [pytorch/pytorch#20687]
i am testing pytorch data loader in google colab platform
it seems higher workers have marginal improvement

this code is printing the time when each batch is delivered:

```
import time
t0=time.time()
for x in batch_gen:
  print('%.1fs from start' % (time.time()-t0))
```

here is the result for 2 and 4 workers

num_workers=2 :
10.2s from start
10.4s from start
21.3s from start
21.3s from start
32.0s from start
32.0s from start
42.6s from start
42.9s from start
...

num_workers=4 :
22.7s from start
22.7s from start
22.7s from start
22.7s from start
45.6s from start
45.6s from start
45.8s from start
45.8s from start
67.4s from start
67.8s from start
67.8s from start
67.8s from start
....

i can understand this kind of threading can improve speed in some cases (not mine)
but it is kind of bad practice and have lower value then queue threading

here is another test:

```
t0=time.time()
for x in batch_gen:
  time.sleep(2)
  print('%.1fs from start' % (time.time()-t0))
```

with num_workers=4 :
batch1: 24.1s from start
batch2: 26.1s from start
batch3: 28.1s from start
batch4: 30.1s from start
batch5: 45.2s from start
batch6: 47.3s from start
batch7: 49.3s from start
batch8: 51.3s from start
batch9: 66.7s from start
batch10: 68.7s from start
batch11: 70.7s from start
batch12: 72.8s from start
...

with num_workers=2:
batch1: 13.7s from start
batch2: 15.7s from start
batch3: 25.4s from start
batch4: 27.4s from start
batch5: 35.9s from start
batch6: 37.9s from start
batch7: 46.8s from start
batch8: 48.8s from start
batch9: 57.3s from start
batch10: 59.4s from start
batch11: 68.0s from start
batch12: 70.0s from start

pytorch version  :  '1.1.0'  

hope this help

**Comment by soumith** [comment]
Colab by default only gives 2 cpu cores, from what I know.

please use https://discuss.pytorch.org for questions

**Comment by ali-r** [comment]
I see 
this is not a question
maybe i should put it under a feature-request 

think of it in this way:
workers are independent from main process so they can process parallel to other parts
the dominant Latency in a loader is normally waiting for disk read not cpu time
you can prepare next batch in background before the iterator call
that means you can process loader part parallel to main process (not only to themselves)
it will save a big time
you can also made workers independent or made priority between them
in the way when one worker is finished it put it out and don't wait for all workers
