### ISSUE TITLE
Memory leak after index_select and assignment

### ISSUE THREAD

**Issue by hongzimao** [pytorch/pytorch#2068]
It seems the memory quickly gets occupied when I run the following testing code

```
import numpy as np
import torch
from torch.autograd import Variable

a = np.random.rand(1000, 1000)

for i in xrange(10000):
    b = Variable(torch.from_numpy(a).clone(), requires_grad=False)
    c = torch.index_select(b, 0, Variable(torch.LongTensor([4])))

    for t in xrange(1000):
        b[t, :] = c
```

within 2 minutes it eats up 128GB of my memory. 

Basically what I wanted to do is dynamically modify parts of a tensor from some other parts of the same tensor. There's a severe memory leak when I do that. I may be very likely doing something not intended for the pytorch framework but not sure what the workaround is. 

I'm using pytorch version 0.1.12_2, installed from pip. OS is Ubuntu 16.04.2 LTS.

Thanks for the help!

**Comment by hongzimao** [comment]
[update] it looks if I add a line after variable `b` and change the assignment of `c` to be
    d = Variable(torch.from_numpy(a).clone(), requires_grad=False)
    c = torch.index_select(d, 0, Variable(torch.LongTensor([4])))
memory usage will become stable

**Comment by soumith** [comment]
this example creates a reference cycle between `b` and `c`, and hence the garbage collector needs to be kicked in to free the held tensors. You can invoke the gc by doing:

```
import gc
gc.collect()
```
