### ISSUE TITLE
Compiling NCCL does not obey MAX_JOBS, makes machine unresponsive

### ISSUE THREAD

**Issue by jamt9000** [pytorch/pytorch#20692]
## 🐛 Bug

Compiling pytorch causes my laptop to become unresponsive, requiring a hard restart. This is because NCCL is compiled with `make -j` (without a number) which is [dangerous behaviour](https://unix.stackexchange.com/questions/316644/is-make-j-with-no-argument-dangerous) since it causes an unbounded number of processes to be spawned.

This is the line:

https://github.com/pytorch/pytorch/blob/7b9ee598d64bd35cad9afea8276ebd1c069620d9/cmake/External/nccl.cmake#L45

## To Reproduce

1. Compile on any machine with modest resources, and when the bundled NCCL is built rather than an existing one used.

## Expected behavior

The machine should not grind to a halt. It should probably obey the MAX_JOBS environment variable used elsewhere, and have a reasonable default.

## Environment

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Ubuntu 16.04.6
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `make all` or `MAX_JOBS=1 make all` or `python setup.py install`
 - Python version: 3.7.3
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Quadro K2000M
 - Any other relevant information:

**Comment by soumith** [comment]
fix posted in https://github.com/pytorch/pytorch/pull/20693

**Comment by jamt9000** [comment]
Just ran in to this problem again - anything stopping the fix from being merged?

**Comment by jamt9000** [comment]
Fixed in #44167

**Comment by ldv1** [comment]
I just ran into this problem with PyTorch I cloned a few days ago. Is the fix merged ? maybe not working; I had to set "-j" to "-j 4" manually, otherwise my machine would hang;

**Comment by Costor** [comment]
I confirm the bug still exists for 1.7 in the current version.

The bugfix provided in ~/pytorch/cmake/External/nccl.cmake  around line 40 in the make statement below is non functional.  
Workaround is - as said above: edit in nccl.cmake to "--jobs=2"  and delete the trailing $ENV{MAX_JOBS}.

Problems seem to be  1) $ENV{MAX_JOBS) does not pick up the value of the environment variable 2) having a space between -j and the argument might cause loss of the arg, when the file ~/pytorch/build/CMakeFiles/nccl_external.dir/build.make  is build.
I recommend using "--jobs=N" to definitely eliminate the latter problem, and MAX_JOBS should default to a sensible value.
