### ISSUE TITLE
nn.functional.conv functions do not take a padding_mode argument

### ISSUE THREAD

**Issue by linzwatt** [pytorch/pytorch#20694]
## 📚 Documentation

As mentioned in [this post ](https://discuss.pytorch.org/t/a-possible-bug-in-torch-nn-functional-conv1d-2d/44066)

[These docs for functional conv opperations](https://pytorch.org/docs/stable/nn.html?highlight=conv1d#torch.nn.functional.conv1d) show a optional argument `padding_mode`. However when specifying this argument an exception is raised:

`TypeError: conv1d() got an unexpected keyword argument 'padding_mode'`

Upon inspection of the modular Conv layers code, it can be seen that the `padding_mode` argument is used to apply padding before calling the functional conv:
https://github.com/pytorch/pytorch/blob/v1.1.0/torch/nn/modules/conv.py#L192

So I believe the `padding_mode` argument should be removed from the **functional** conv docs, as this argument applies to the **modular** Conv layers only

Thanks

**Comment by gchanan** [comment]
looks like a real issue.

**Comment by yifuwang** [comment]
@gchanan I'd like to help with this one. I created a pull request which removes the argument from the documentation. Please let me know if we want to actually add support for the argument instead.

**Comment by soumith** [comment]
@yifuwang 
The way to fix it is to actually do what BatchNorm does, i.e. introduce [version 2](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/batchnorm.py#L16) for the module and have a custom [_load_from_state_dict](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/batchnorm.py#L89-L102) function that handles this

**Comment by soumith** [comment]
@yifuwang whoops, ignore my comment, they were meant for a different issue
