### ISSUE TITLE
tf.nn.embedding_lookup_sparse C++ 

### ISSUE THREAD

**Issue by songziqin** [pytorch/pytorch#20699]
I have two questions:
question one : I decide to  use libtorch for my  training problems, and I want to use the function that have implemented in tensorflow,that is sparse tensor embedding. and I want to know if libtorch have the same interface. 

question two: tensorflow have the function tf.concat
,and I want to know if libtorch have the similar interface.

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
