### ISSUE TITLE
[Feature request] Zero diagonal tensor elements

### ISSUE THREAD

**Issue by helgehatt** [pytorch/pytorch#20703]
## 🚀 Feature
Remove diagonal elements or replace diagonal elements with zero

## Motivation
Using tensors to represent network structure (e.g. sociomatrix) it is often useful to remove information on the diagonal.

## Alternatives
One simple alternative is to subtract the diagonal from the tensor itself.

    def nodiag(input):
        return input.sub(input.diag().diag())

**Comment by vishwakftw** [comment]
You can probably try this:
```python
input.diagonal(dim1=-2, dim2=-1).zero_()
```

This makes the diagonal elements zero inplace.

**Comment by gchanan** [comment]
seems to be supported.
