### ISSUE TITLE
pythonb -m torch.distributed.launch doesn't propagate non-0 status of child process

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#20728]
Right now if child process crashes, with `python -m torch.distributed.launch script.py` will return with a 0 return code. It should instead propagate non-zero exit status so that the launching environment could detect the failure

```
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/pytorch_p36/bin/python', '-u', 'pytorch_bench.py', '--local_rank=0', '--num_tasks=2', '--logdir', '/ncluster/runs/unnamedrun-0-ogf2l.06']' returned non-zero exit status 1.
(pytorch_p36) ubuntu@ip-172-31-12-237:~$ echo $?
0
(pytorch_p36) ubuntu@ip-172-31-12-237:~$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
im>>> import torch
>>> torch.__version__
'1.1.0'

```

**Comment by ezyang** [comment]
This sounds reasonable to me, I can review such a PR if it is submitted.

**Comment by JanuszL** [comment]
It seems to work in 1.1.0 - https://github.com/pytorch/pytorch/blob/v1.1.0/torch/distributed/launch.py#L229, while in 1.0.0 return value is disregarded https://github.com/pytorch/pytorch/blob/v1.0.0/torch/distributed/launch.py#L215.

**Comment by yaroslavvb** [comment]
Interesting...it seems it should indeed be propagated, will reopen this with more details once I can reproduce it again
