### ISSUE TITLE
torch.hub does not close the resource before removing

### ISSUE THREAD

**Issue by nv-kkudrynski** [pytorch/pytorch#20757]
## 🐛 Bug

In the hub.py, line 169 should be preceded by:
cached_zipfile.close()
Otherwise on Windows, it will crash with PermissionException

## To Reproduce

1. Call torch.hub.load() on external repo on windows

File "...\python36pytorch\lib\site-packages\torch\hub.py", line 83, in _remove_if_exists
    os.remove(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '.../.cache\\torch\\hub\\master.zip'

**Comment by ezyang** [comment]
cc @ailzhang

**Comment by whimian** [comment]
The bug is still not solved in version 1.1.0.

**Comment by ezyang** [comment]
I think the fix didn't make it to 1.1.0 release. Try patching it in yourself.

**Comment by a-whitej** [comment]
In the _get_cache_or_reload function, add the "cached_zipfile.close()" call after the cached_zipfile.extractall(hub_dir) function to fix the bug.

**Comment by wwyi1828** [comment]
I have the same error...and I don't know why...

**Comment by ailzhang** [comment]
@wwyi1828 The fix should have been released with 1.2. Would you mind try that version and see if it works?

**Comment by wwyi1828** [comment]
> 
> 
> @wwyi1828 The fix should have been released with 1.2. Would you mind try that version and see if it works?

I updated PyTorch from 1.1 to 1.2. It works perfectly now! Thanks a lot.
