### ISSUE TITLE
AttributeError: 'Conv2d' object has no attribute 'padding_mode' when loading model from pytorch 1.0 to 1.1

### ISSUE THREAD

**Issue by trougnouf** [pytorch/pytorch#20756]
Loading a model created with pytorch 1.0 fails on pytorch 1.1 with the error "AttributeError: 'Conv2d' object has no attribute 'padding_mode'".

This issue was also reported on https://github.com/jacquelinelala/GFN/issues/11 .

complete backtrace:
```
Traceback (most recent call last):
  File "run_nn.py", line 213, in <module>
    loss = criterion(model(batch_y)[:,:,loss_crop_lb:loss_crop_up, loss_crop_lb:loss_crop_up], batch_x[:,:,loss_cro
p_lb:loss_crop_up, loss_crop_lb:loss_crop_up]).cuda()
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/orb/Dev/mthesis-denoise/networks/Hul.py", line 511, in forward
    l126 = self.enc128to126std(x)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 331, in forward
    if self.padding_mode == 'circular':
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'Conv2d' object has no attribute 'padding_mode'

```
Example of problematic model: https://github.com/trougnouf/mthesis-denoise/blob/master/networks/Hul.py , loaded with model = torch.load(args.load_g_path, map_location=device)

A workaround is to comment out the lines that use self.padding_mode in module.py, the model can then be imported, and saving the state_dictionary instead of the whole model allows loading into an unmodified version of pytorch 1.1.

**Comment by ezyang** [comment]
This should work, we can probably fix it by making the deserializer smarter.

**Comment by soumith** [comment]
The way to fix it is to actually do what BatchNorm does, i.e. introduce [version 2](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/batchnorm.py#L16) for the module and have a custom [_load_from_state_dict](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/batchnorm.py#L89-L102) function that handles this

**Comment by ezyang** [comment]
I don't think `_load_from_state_dict` is the correct mechanism here; the loading was done with `torch.load` which will use Pickle, which doesn't use state dict loading.

**Comment by LalehSeyyed** [comment]
I have the same issue while loading the densenet model of https://github.com/jrzech/reproduce-chexnet/tree/master/pretrained. ahow can we fix it?

**Comment by ezyang** [comment]
This is fixed on master; try applying the patch that fixed to your copy of PyTorch.
