### ISSUE TITLE
Pytorch 1.1 change the pre-model path?

### ISSUE THREAD

**Issue by kangkang59812** [pytorch/pytorch#20754]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
the previous path is  root/.torch/model , now in Pytorch 1.1  I found that the path is he root/.cache/torch/checkpoints/. How to change this to the previous one?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

you can specify $TORCH_HOME environment variable that points to previous path and we will respect it. It's written in the documentation
