### ISSUE TITLE
[JIT] Better Python String Support

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#20769]
## [JIT] Support All Python String methods

Tracking issue for parity with python strings. 

- [x] capitalize()
- [ ] casefold() - skipped
- [x] center()
- [x] count()
- [ ] ~~encode()~~ - maybe skip this one since everything is already unicode
- [x] endswith()
- [x] expandtabs()
- [x] find()
- [x] format()
- [ ] format_map() - skipped
- [x] index()
- [x] isalnum()
- [x] isalpha()
- [x] isdecimal()
- [x] isdigit()
- [x] isidentifier()
- [x] islower()
- [x] isnumeric()
- [x] isprintable()
- [x] isspace()
- [x] istitle()
- [x] isupper()
- [ ] join()
- [x] ljust()
- [x] lower()
- [x] lstrip()
- [ ] maketrans() - skipped
- [x] partition()
- [x] replace()
- [x] rfind()
- [x] rindex()
- [x] rjust()
- [x] rpartition()
- [x] rsplit()
- [x] rstrip()
- [x] split()
- [x] splitlines()
- [x] startswith()
- [x] strip()
- [x] swapcase()
- [x] title()
- [ ] translate() - skipped
- [x] upper()
- [x] zfill()

## Motivation

Users have run been blocked by lack of these methods in the past. 

cc @suo

**Comment by pandeykartikey** [comment]
Hey @eellison Would like to work on the `count()` function here? Is it up for grab?

**Comment by eellison** [comment]
@bwasti just submitted a PR for `count` and a bunch others here https://github.com/pytorch/pytorch/pull/21059
