### ISSUE TITLE
Installation Error: Failed to get generated_cpp list

### ISSUE THREAD

**Issue by chengdazhi** [pytorch/pytorch#2076]
Using python 3.5.2, error occurred when installing pytorch.
CMake Error at CMakeLists.txt:128 (message):
  Failed to get generated_cpp list

-- Configuring incomplete, errors occurred!

**Comment by chengdazhi** [comment]
I notice an issue of the same problem : https://github.com/pytorch/pytorch/issues/2062
But that came from a too old python version, yet mine can't be solved that way.

**Comment by killeent** [comment]
@chengdazhi I cannot repro on PyTorch master using Python `3.5.2` can you send me the exact build command and error stack trace that yields your build failure?

**Comment by chengdazhi** [comment]
Thanks for your prompt reply. Actually, I was following the 'build from source' option and I installed anaconda. Anaconda ignored my already-existing python3.5.2 and installed another 3.5.2 in its own path. When I first tried to install pytorch, I used my own python. After I failed(and submitted this issue), I tried with the python installed by anaconda and it worked. So do you think that this is the problem? That I should use the python from anaconda?

**Comment by chengdazhi** [comment]
If you don't think it's a bug you can close this now, I can work with the anaconda python.

**Comment by soumith** [comment]
given that the default python on Ubuntu 14.04 is 2.7.3, i think this is worth fixing.

**Comment by killeent** [comment]
@chengdazhi Great! Do you happen to have the full error log when building with the other version of Python so I can confirm its the same issue as #2062?

**Comment by chengdazhi** [comment]
Yes, but the log is rather succinct. And I can only give you the last few lines, hope they are enough for you. I believe only the last two lines are of use, but I give you all I have anyway.

```
[ 50%] Building CXX object CMakeFiles/shm.dir/core.cpp.o
[ 75%] Linking CXX shared library libshm.so
[ 75%] Built target shm
[100%] Linking CXX executable torch_shm_manager
CMakeFiles/torch_shm_manager.dir/manager.cpp.o: In function `main':
manager.cpp:(.text.startup+0x35): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
[100%] Built target torch_shm_manager
Install the project...
-- Install configuration: "Release"
-- Installing: /unsullied/sharefs/chengdazhi/exp/pytorch/torch/lib/tmp_install/lib/libshm.so
-- Set runtime path of "/unsullied/sharefs/chengdazhi/exp/pytorch/torch/lib/tmp_install/lib/libshm.so" to ""
-- Up-to-date: /unsullied/sharefs/chengdazhi/exp/pytorch/torch/lib/tmp_install/include/libshm.h
-- Installing: /unsullied/sharefs/chengdazhi/exp/pytorch/torch/lib/tmp_install/bin/torch_shm_manager
-- TH_LIBRARIES: /unsullied/sharefs/chengdazhi/exp/pytorch/torch/lib/tmp_install/lib/libTH.so.1
-- THNN_LIBRARIES: /unsullied/sharefs/chengdazhi/exp/pytorch/torch/lib/tmp_install/lib/libTHNN.so.1
-- THC_LIBRARIES: /unsullied/sharefs/chengdazhi/exp/pytorch/torch/lib/tmp_install/lib/libTHC.so.1
-- THCS_LIBRARIES: /unsullied/sharefs/chengdazhi/exp/pytorch/torch/lib/tmp_install/lib/libTHCS.so.1
-- THCUNN_LIBRARIES: /unsullied/sharefs/chengdazhi/exp/pytorch/torch/lib/tmp_install/lib/libTHCUNN.so.1
--
CMake Error at CMakeLists.txt:128 (message):
  Failed to get generated_cpp list


-- Configuring incomplete, errors occurred!
See also "/unsullied/sharefs/chengdazhi/exp/pytorch/torch/lib/build/ATen/CMakeFiles/CMakeOutput.log".
```

The CMakeOutput.log is overridden by the correct installation, so I'm not listing it here.

**Comment by soumith** [comment]
this is now properly merged into master, thanks to Trevor's fix: https://github.com/pytorch/pytorch/commit/6db960fbcff7ae194c6827c73113c222391f2c3e
