### ISSUE TITLE
Support One step transform to numpy

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#20778]
## 🚀 Feature
Writing         `print tensor.detach().cpu().numpy()` gets really annoying. Can you provide a method that just takes you to numpy in one step?

Like `fnumpy` (force to numpy). So if it has gradient, it will detach it for you, if it is cuda, it will move to CPU for you etc.

**Comment by fmassa** [comment]
maybe pass an argument to `.numpy()`, something like `.numpy(force=True)`?

**Comment by ezyang** [comment]
This seems reasonable to me. More context at issue #9934 where our implicit conversion accidentally allowed conversion to CPU, and we rejected PR #20395 because it would have affected implicit conversion.

Actually, let me say something controversial: I think that if you *explicitly* say `x.numpy()`, we should do the "force" behavior. It's just implicit conversions where they need to be O(1).

**Comment by sidazhang** [comment]
> Actually, let me say something controversial: I think that if you _explicitly_ say `x.numpy()`, we should do the "force" behavior. It's just implicit conversions where they need to be O(1).

I agree. Like, if I am calling `.numpy()`, I am already explictly saying `detach` and if in cuda, move to cpu.

**Comment by vadimkantorov** [comment]
I think a useful framing is: should the same operation `numpy` be strictly zero-overhead or sometimes causing a copy from CUDA to CPU? Another question is: should an implicit conversion do the same thing that the explicit one (e.g. sometimes incurring a GPU-CPU copy).

Many answers make sense, but it should be well-documented.

**Comment by sidazhang** [comment]
As a follow up.

If I am going to numpy. I clearly don't care about the grad. Just want to take a look at it

```
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.
```

**Comment by ezyang** [comment]
OK, we discussed this at our triage meeting, we will accept this patch. Make sure not to accidentally change the behavior of implicit conversion too.

**Comment by sidazhang** [comment]
@ezyang what do you accept the patch? There is no diff. Would you like me to put up a diff?

**Comment by ezyang** [comment]
Yes, please do! (We're just saying explicitly, if someone were to put up a PR for this, we would accept and merge it.)

**Comment by apaszke** [comment]
I think we can add a `force` argument, but we shouldn't allow cross-device copies implicitly! Currently there's an invariant of "if a `.numpy()` call succeeds then the returned array _shares memory with the source tensor_". This is sometimes important, and I'd like to make it easy for users to verify that.

**Comment by fmassa** [comment]
@apaszke I think the contract would be that the assumption of sharing memory is not valid anymore with the `force=True` argument.

This might mean that we might want to always return a copy of the data, even if it is on the CPU. Or we just put a big warning in the documentation saying that the memory can be shared or not, like what happens with functions like `reshape`.

**Comment by apaszke** [comment]
Well if we make `force=False` the default, then we can keep up the same semantics as today, and provide an escape path for those who want it (but they will have to say that explicitly). It's much nicer than a chain of `.detach().cpu().numpy()`.

**Comment by fmassa** [comment]
@apaszke yes, that was exactly my thoughts
