### ISSUE TITLE
Version 1.1.0 get "No grad accumulator for a saved leaf!" in ScriptModule

### ISSUE THREAD

**Issue by draplater** [pytorch/pytorch#20798]
## 🐛 Bug

When using LayerNorm in ScriptModule in version 1.1.0, I get "RuntimeError: No grad accumulator for a saved leaf!". But it's OK in 1.0.1.

## To Reproduce

```python
import torch
from torch.nn import LayerNorm, Linear
from torch.jit import ScriptModule, script_method

class Test(ScriptModule):
    def __init__(self, dim):
        super().__init__()
        self.layer_norm = LayerNorm(dim)
        self.projection = Linear(dim, dim)
    
    @script_method
    def forward(self, inputs):
        return self.layer_norm(inputs + self.projection(inputs))


if __name__ == "__main__":
    m = Test(512)
    input_tensor = torch.randn((10, 11, 512))
    output_tensor = m(input_tensor)
    output_tensor.sum().backward()
```

## Expected behavior

Get "RuntimeError: No grad accumulator for a saved leaf!" in 1.1.0. But it's OK in 1.0.1,or with torch.jit removed in 1.1.0.

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 980 Ti
GPU 1: GeForce GTX TITAN X

Nvidia driver version: 390.116
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.1
[pip3] numpy==1.16.3
[pip3] numpydoc==0.8.0
[pip3] torch==1.1.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.2.2.post3
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
[conda] pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch

**Comment by wanchaol** [comment]
@draplater yeah that's a known bug and this already been fixed on the master. Can you try the lastest nightly builds to see if the error still persist?

**Comment by draplater** [comment]
@wanchaol It's OK on the master. Thanks!
