### ISSUE TITLE
libtorch terminate called after throwing an instance of 'c10::Error'

### ISSUE THREAD

**Issue by xiaoxiaotao** [pytorch/pytorch#20792]
## 🐛 Bug
I use the libtorch(version 1.1.0) inference faceboxes(https://github.com/XiaXuehai/faceboxes),it can normally generate faceboxes.pt model,but when I inference the model  faceboxes.pt ,it report some error.my code:
`from networks import FaceBox
from encoderl import DataEncoder
import torch
import numpy as np
import torch.nn.functional as F
import cv2
import time

import torchvision
im=cv2.imread("/home/tao/useful/faceboxes_tensorrt_cuda/pytorch/picture/22.jpg")
h, w, _ = im.shape
dim_diff = np.abs(h - w)
pad1, pad2 = dim_diff // 2, dim_diff - dim_diff // 2
pad = ((pad1, pad2), (0, 0), (0, 0)) if h <= w else ((0, 0), (pad1, pad2), (0, 0))
input_img = np.pad(im, pad, 'constant', constant_values=128)
input_img = cv2.resize(input_img,(1024,1024))/255
net = FaceBox()
use_gpu = torch.cuda.is_available()
if use_gpu:
   net.cuda()
net.load_state_dict(torch.load('weight/faceboxes.pt', map_location=lambda storage, loc:storage), strict=False) 
data_encoder = DataEncoder()
im_tensor = torch.from_numpy(input_img.transpose((2,0,1))).float()
verbose=True,input_names=input_names,output_names=output_names)
traced_script_module = torch.jit.trace(net, im_tensor.unsqueeze(0).cuda())
traced_script_module.save("faceboxes.pt")
`
the libtorch code:
`#include <torch/script.h>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/opencv.hpp>
#include <cmath>
#include <iostream>
#include <memory>
#include <string>
#include <vector>

#define kIMAGE_SIZE 1024
#define kCHANNELS 3

bool LoadImage(std::string file_name, cv::Mat &image) {
  image = cv::imread(file_name);  // CV_8UC3
  if (image.empty() || !image.data) {
    return false;
  }
  cv::cvtColor(image, image, CV_BGR2RGB);
  std::cout << "== image size: " << image.size() << " ==" << std::endl;

  // scale image to fit
  cv::Size scale(kIMAGE_SIZE, kIMAGE_SIZE);
  cv::resize(image, image, scale);
  std::cout << "== simply resize: " << image.size() << " ==" << std::endl;

  // convert [unsigned int] to [float]
  image.convertTo(image, CV_32FC3, 1.0f / 255.0f);

  return true;
}
int main(int argc, const char *argv[]) {

  std::string modelpath="/home/tao/libtorch/example/faceboxes_pytorch_c++/pytorch/faceboxes.pt";
  std::shared_ptr<torch::jit::script::Module> module =
      torch::jit::load(modelpath);
  std::cout << "== Switch to GPU mode" << std::endl;
  // to GPU
  module->to(at::kCUDA);

  assert(module != nullptr);

  std::string file_name = "/home/tao/libtorch/example/faceboxes_pytorch_c++/pytorch/picture/22.jpg";
  cv::Mat image;
  if (LoadImage(file_name, image)) {
      auto input_tensor = torch::from_blob(image.data, {1, kIMAGE_SIZE, kIMAGE_SIZE, kCHANNELS});
      input_tensor = input_tensor.permute({0, 3, 1, 2});
      input_tensor[0][0] = input_tensor[0][0];
      input_tensor[0][1] = input_tensor[0][1];
      input_tensor[0][2] = input_tensor[0][2];

      // to GPU
      input_tensor = input_tensor.to(at::kCUDA);
      std::cout<<"it is here "<<std::endl;
      torch::Tensor out_tensor = module->forward({input_tensor}).toTensor();
      std::cout<<out_tensor<<std::endl;
  }
}
`
errors:
`terminate called after throwing an instance of 'c10::Error'
  what():  isTensor() ASSERT FAILED at /home/tao/libtorch/include/ATen/core/ivalue.h:205, please report a bug to PyTorch. (toTensor at /home/tao/libtorch/include/ATen/core/ivalue.h:205)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f9a840d4441 in /home/tao/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f9a840d3d7a in /home/tao/libtorch/lib/libc10.so)
frame #2: c10::IValue::toTensor() && + 0x1f0 (0x40f300 in /home/tao/libtorch/example/build-faceboxes_pytorch_c++-Desktop_Qt_5_7_0_GCC_64bit-Default/facebox)
frame #3: main + 0x66a (0x40abfa in /home/tao/libtorch/example/build-faceboxes_pytorch_c++-Desktop_Qt_5_7_0_GCC_64bit-Default/facebox)
frame #4: __libc_start_main + 0xf0 (0x7f9a20c67830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #5: _start + 0x29 (0x40b139 in /home/tao/libtorch/example/build-faceboxes_pytorch_c++-Desktop_Qt_5_7_0_GCC_64bit-Default/facebox)`

##CMakeLists.txt:
cmake_minimum_required(VERSION 2.8)
project(faceboxes)
set(CMAKE_BUILD_TYPE "Debug")
SET(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-std=c++11 -O3")
set(Torch_DIR /home/tao/libtorch/share/cmake/Torch)
set(OpenCV_DIR /home/tao/opencv-3.4.2/build)
find_package(OpenCV REQUIRED)
find_package(Torch REQUIRED)
include_directories( ${OpenCV_INCLUDE_DIRS} )
add_executable(facebox prediction.cpp)
target_link_libraries(facebox ${OpenCV_LIBS} ${TORCH_LIBRARIES})

## Environment

 - PyTorch Version (e.g., 1.0):1.1.0
 - OS (e.g., Linux):ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip3
 - Build command you used (if compiling from source):no
 - Python version:python 3.5
 - CUDA/cuDNN version: 9.0/9.2
 - GPU models and configuration: GeForce GTX 930MX 2GB

**Comment by xsacha** [comment]
This is the correct error.

The return value of model->forward is a C10::IValue.
Faceboxes model returns a Tuple, not a Tensor.

You need to do this:

```C++
torch::jit::Stack outputs = model->forward({input}).toTuple()->elements();
```

The variable `outputs` now contains your bounding boxes and your confidence tensors.

**Comment by xiaoxiaotao** [comment]
@xsacha,thank you !
