### ISSUE TITLE
torch.Size is not pickleable in Python 2

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#20823]
## 🐛 Bug

torch.Size objects (returned by Tensor.shape) are not pickleable in Python 2.7. They can be pickled in Python 3.

## To Reproduce

```python
import torch
import pickle

pickle.dumps(torch.randn(10).shape)  # TypeError: can't pickle Size objects
```

## Environment

PyTorch 1.0.1.post2 (but I believe it also is present in master as of 5/22/19)
Python 2.7.15 on Mac OS X

**Comment by ezyang** [comment]
From internal discussion:

@fmassa: Maybe it's time to consider removing torch.Size and make tensor.shape return a tuple? I believe torch.Size was necessary to support legacy constructors, like torch.Tensor(a.size()), which overloaded torch.Tensor with both a size and a data constructor.

Removing torch.Size would probably imply removing torch.Tensor and tensor.new though. Or am I missing something and torch.Size has other use-cases?

Thoughts?
(sure, we can make torch.Size picklable, my question is more like, do we still want / need it? People have asked in the past why we don't have torch.Stride as well)

@colesbury:
Removing torch.Tensor constructor would be a big change. It would need to happen over at least two releases.

@ezyang:
we still use it in our tests lol
If it's not causing problems I'm inclined to just keep it forever

@colesbury:
Another options is to only deprecate the torch.Tensor() data overload. e.g. torch.Tensor([2, 3, 4, 5]). It's used less often than the size-based constructor and would still allow for eventually getting rid of torch.Size.

It would still be a significant change that would have to happen over multiple releases

**Comment by colesbury** [comment]
@ezyang removing `torch.Size` or the `torch.Tensor` constructors are different issues. We need to be able to pickle `torch.Size` while it exists in Python 2.

I've removed topic: bc-breaking because I don't think fixing pickling is bc-breaking.

**Comment by ailzhang** [comment]
In case it's helpful, I've seen a similar issue for torch.dtype. #14057 Sadly python3 and python2 are very different in terms of pickle(also import :( 
If it's something worth supporting, I can look into this early next week.

**Comment by colesbury** [comment]
@ailzhang yes that would be great!
