### ISSUE TITLE
[feature request] a function to empty all the cuda buffer

### ISSUE THREAD

**Issue by Stonesjtu** [pytorch/pytorch#20837]
## 🚀 Feature

At present the pytorch process uses about 900MB after `lazy_init` cuda context. I was searching on internet whether the CUDA context can be shutdown, but seems like such API is not provided yet. Here I'm asking if we can do a `pytorch` side context clear, so the minimal CUDA memory should be allocated to pytorch runtime.

## Motivation

I'm developing an interesting function that each pytorch worker interacts with a scheduling server, dynamically moving the workload from/to GPU, so that the CUDA memory can be used for tasks with higher priority. 

## Pitch

```python
tensor = torch.Tensor(100,100).cuda()  # lazy_init happens here
del tensor
torch.cuda.de_init()  # clear all the CUDA memory maintained by pytorch runtime
```

**Comment by colesbury** [comment]
I don't think we should provide such a function. The way to do what you're describing is to reset the CUDA context, for example by `cudaDeviceReset()`, but that invalidates all pointers which means that any accesses to any CUDA tensors or internal CUDA state will crash.

**Comment by Stonesjtu** [comment]
I think it's users' responsibilities to ensure no CUDA tensors are going to be accessed after calling such a function.

how about such semantic:

```python
with torch.cuda.temp_context():
    do_something_on_cuda()

# cuda context is automatically released so this task does not occupy any memory
```

Without the context deleting feature, there will always be a context in `cuda:0` when someone wants to transfer all work loads from `cuda:0` to `cuda:1`, while `cuda:0` should be free.

There should at least exist such a mechanism when users can delete the cuda context by themselves. We can make this API a low-level and underlined one, so most people won't care about it.

Or is it available for me to delete the context outside `pytorch`'s code.

**Comment by gchanan** [comment]
just registering that I agree with @colesbury's take here.

**Comment by VitalyFedyunin** [comment]
@colesbury I'm not telling that we are going to write this code. But it is possible to check if there are any active allocations in CUDACachingAllocator.cpp and error out if any of the tensors remains. 
(besides that developer would need to check all streams and events). 

@Stonesjtu I don't think anyone will start implementing this functionality any time soon. But if you are ready to submit PR I would gladly help you with the review.

**Comment by Stonesjtu** [comment]
@VitalyFedyunin Quite happy to implement, i think we can check the cuda memory allocation like this:

```python
torch.cuda.synchronize()  # ensures all streams and events are finished
can_be_freed = torch.cuda.memory_allocated() == 0
```

**Comment by colesbury** [comment]
I don't think that's sufficient. CUDA resources also include things like streams, cuBLAS handles, and cuDNN handles.

**Comment by Stonesjtu** [comment]
Are these different types of CUDA resources managed individually.

**Comment by ezyang** [comment]
Yeah, there is no centralized location.

I don't think we're going to do this. If you realllly want it, just make the CUDA API call yourself.
