### ISSUE TITLE
Pytorch error when compiling libtorch library for android

### ISSUE THREAD

**Issue by andywangII** [pytorch/pytorch#20849]
## 🐛 Bug

When I option(BUILD_CAFFE2_MOBILE "Build libcaffe2 for mobile (deprecating)" OFF) I want to compile and generate libtorch.so, Aten compile error when running build_anroid.sh. Error: Cmake Error at cmake/Codegen.cmake:162(message): Failed to get generated_cpp list Call Stack(most recent call first): caffe2/CmakeLists.txt:2(include)

**Comment by alokprasad** [comment]
@andywangII Where you able to compile libtorch for android>? where to find source of libtorch for Android ? I dont see it seems they are already precompiled for different arch?

**Comment by alokprasad** [comment]
This worked for me

``

git clone --recurse-submodules -j8 https://github.com/pytorch/pytorch.git
cd pytorch/
git checkout 3ac4d928248a4b5949b5fafe0d2f43c649cd0cd9
export ANDROID_NDK=/opt/android-ndk-r19c
export ANDROID_ABI=arm64-v8a
build_args+=("-DBUILD_CAFFE2_MOBILE=OFF")
build_args+=("-DCMAKE_BUILD_TYPE=Release")   
build_args+=("-DCMAKE_PREFIX_PATH=$(python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())')")
build_args+=("-DPYTHON_EXECUTABLE=$(python -c 'import sys; print(sys.executable)')")
pip install typing --user
./scripts/build_android.sh "${build_args[@]}"

**Comment by fatalfeel** [comment]
also need 
ln -sf /usr/bin/python3.7 /usr/bin/python
or can not find module
