### ISSUE TITLE
 [TensorRT] ERROR: Network must have at least one output

### ISSUE THREAD

**Issue by float123** [pytorch/pytorch#20857]
I use the torch.onnx.export() method to convert the Alexnet to the onnx format, but when I use tensorrt, I get an error, [TensorRT] ERROR: Network must have at least one output.
How can I solve it?  thanks

this is my code：

```python
import torch
import torchvision

dummy_input = torch.randn(10, 3, 224, 224, device='cuda')
model = torchvision.models.alexnet(pretrained=True).cuda()

input_names = [ "actual_input_1" ] + [ "learned_%d" % i for i in range(16) ]
output_names = [ "output1" ]

torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)
```

```python
import tensorrt as trt

TRT_LOGGER = trt.Logger(trt.Logger.WARNING)

def GiB(val):
    return val * 1 << 30

def build_engine_onnx(model_file):
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network() as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
        builder.max_workspace_size = GiB(1)
        with open(model_file, 'rb') as model:
            parser.parse(model.read())
        return builder.build_cuda_engine(network)

build_engine_onnx("alexnet.onnx")
```

![image](https://user-images.githubusercontent.com/39334643/58239456-a9849a80-7d7b-11e9-9bd7-4063d2318b99.png)

cc @BowenBao @neginraoof

**Comment by BowenBao** [comment]
Seems like related issue to [this](https://devtalk.nvidia.com/default/topic/1045064/tensorrt/onnx-and-tensorrt-error-network-must-have-at-least-one-output/1). Do you also observe errors like ```Unsupported ONNX data type: INT64 (7)```?

Another thing I'm not sure, and it may or may not affect this error, is that why are you exporting with 17 input names?

**Comment by float123** [comment]
> Seems like related issue to [this](https://devtalk.nvidia.com/default/topic/1045064/tensorrt/onnx-and-tensorrt-error-network-must-have-at-least-one-output/1). Do you also observe errors like `Unsupported ONNX data type: INT64 (7)`?
> 
> Another thing I'm not sure, and it may or may not affect this error, is that why are you exporting with 17 input names?

Yes, there will be an erro：Unsupported ONNX data type: INT64 (7) , but if upgrade tensorrt to 5.1.5.0, the problem will be solved.

I just found out the ONNX Parser shipped with TensorRT 5.1.x supports ONNX IR version 0.0.3，But the onnx version of Torch exports is 0.04.

**Comment by float123** [comment]
So, I have a new problem. How to convert an onnx model - IR version4 to IR version3?

**Comment by mrshenli** [comment]
cc @houseroad

**Comment by qnkhuat** [comment]
Hi guys, do we have any update on this?

**Comment by garymm** [comment]
@float123 is this still an issue with the latest versions of PyTorch and TensorRT?

**Comment by garymm** [comment]
This seems to work with tensorrt 8.0.1.6 and torch 1.9.0+cu102:

```python
import tensorrt as trt
import torch
print("tensorrt version:", trt.__version__, "torch version:", torch.__version__)
import torchvision

dummy_input = torch.randn(10, 3, 224, 224, device='cuda')
model = torchvision.models.alexnet(pretrained=True).cuda()

input_names = [ "actual_input_1" ] + [ "learned_%d" % i for i in range(16) ]
output_names = [ "output1" ]

torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)


TRT_LOGGER = trt.Logger(trt.Logger.WARNING)

def GiB(val):
    return val * 1 << 30

def build_engine_onnx(model_file):
    with trt.Builder(TRT_LOGGER) as builder, builder.create_builder_config() as config, builder.create_network() as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
        config.max_workspace_size = GiB(1)
        with open(model_file, 'rb') as model:
            parser.parse(model.read())
        return builder.build_engine(network, config)

build_engine_onnx("alexnet.onnx")
```

Please open a new issue with repro instructions if needed.
