### ISSUE TITLE
Pytorch error when compiling libtorch library for android

### ISSUE THREAD

**Issue by andywangII** [pytorch/pytorch#20856]
When I option(BUILD_CAFFE2_MOBILE "Build libcaffe2 for mobile (deprecating)" OFF) I want to compile and generate libtorch.so, Aten compile error when running build_anroid.sh. Error: Cmake Error at cmake/Codegen.cmake:162(message): Failed to get generated_cpp list Call Stack(most recent call first): caffe2/CmakeLists.txt:2(include)

**Comment by mrshenli** [comment]
@andywangII 

Could you share the detailed repro steps and your environment (by run and paste the output of https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py) ?

cc @ezyang @yf225

**Comment by t-vi** [comment]
So given that this didn't see any response and we now have PyTorch mobile with an [official instructions page](https://pytorch.org/mobile/android/#building-pytorch-android-from-source), I'm closing the issue.
If the instructions linked above, please do reopen.
