### ISSUE TITLE
torch.jit.trace crash in presence of hooks, even in well determined models.

### ISSUE THREAD

**Issue by jeremycochoy** [pytorch/pytorch#20862]
## 🐛 Bug

If one want to compile a model using hook but with a well determined behavior while traced, the trace function raise anyway. There doesn't seams to be a way to force the trace function to ignore the raise:
```python
if orig._backward_hooks or orig._forward_hooks or orig._forward_pre_hooks:
    raise ValueError("Modules that have hooks assigned can't be compiled")
```

## To Reproduce

Just take a model with a dummy hook. Trace will fail.

## Expected behavior

Trace should only warn, or ask a special argument (something like `torch.jit.trace(model, dummy, ignore_hooks=True)` )

## Additional context

A quick fix would be to transform the raise into a warning. A better fix would be to ask the user to explicitly tell he want trace to ignore the presence of hooks.

Best regards,

**Comment by eellison** [comment]
CC @Krovatkin
