### ISSUE TITLE
torch.empty(n, dtype=torch.int) produces non-deterministic arrays, not empty ones

### ISSUE THREAD

**Issue by baalimago** [pytorch/pytorch#20905]
## Code To Reproduce
```
import torch
for i in range(10):
    l = torch.empty(10, dtype=torch.int)
    print(l)
```

## Expected behavior
Output when i run above:

```
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor([6619251, 7536754, 7077980, 6881387, 6553710, 3014748, 7274595, 6553710,
        6029409, 7209061], dtype=torch.int32)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor([15,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=torch.int32)
tensor([6619251, 7536754, 7077980, 6881387, 6553710, 3014748, 7274595, 6029409, 7209061], dtype=torch.int32)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
tensor([1702521088,7536640,6226012,4456540,0,0,15,0, -992612760,564], dtype=torch.int32)
tensor([6619251, 7536754, 7077980, 6881387, 6553710, 3014748, 7274595, 6553710,
        6029409, 7209061], dtype=torch.int32)
tensor([1702521088,    7536640,    6226012,4456540, 0,15,0, -992612760,dtype=torch.int32)
tensor([6619251, 7536754, 7077980, 6881387, 6553710, 3014748, 7274595, 6029409, dtype=torch.int32)
```

## Environment
PyTorch version: torch.\_\_version\_\_ = 1.1.0
Is debug build: No
CUDA used to build PyTorch: Yes

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 430.64
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.16.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.3                      203
[conda] mkl-service               1.1.2            py37hb782905_5
[conda] mkl_fft                   1.0.10           py37h14836fe_0
[conda] mkl_random                1.0.2            py37h343c172_0

**Comment by fmassa** [comment]
That's the expected behavior. `torch.empty` doesn't initialize the data, and just returns whatever was in that position in memory. If you want the data to be initialized with some number, use `torch.zeros` or `torch.full`

**Comment by baalimago** [comment]
I see. Thank you!
