### ISSUE TITLE
sizes vs size for tensor creation

### ISSUE THREAD

**Issue by shagunsodhani** [pytorch/pytorch#20921]
## 📚 Documentation

For tensor creation ops like `torch.zeros` and `torch.ones`, the docs [0], [1] use `sizes` as the first argument to the function call while the correct argument is `size`.  This is tested for pytorch 1.1 installed using pip on ubuntu 19.04

An example

```
>>> torch.zeros(2, 3)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
>>> torch.zeros(sizes = (2, 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: zeros() missing 1 required positional arguments: "size"
>>> torch.zeros(size = (2, 3))
tensor([[0., 0., 0.],
        [0., 0., 0.]])
>>> torch.ones(sizes = (2, 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ones() missing 1 required positional arguments: "size"
>>> torch.ones(size = (2, 3))
tensor([[1., 1., 1.],
        [1., 1., 1.]])
```

[0]: https://pytorch.org/docs/master/torch.html#torch.zeros
[1]: https://pytorch.org/docs/master/torch.html#torch.ones

**Comment by shagunsodhani** [comment]
I realised that there are some other tensor creation ops which have the same issue of `sizes` vs `size`. I submitted a new [PR](https://github.com/pytorch/pytorch/pull/21686/) which fixes them.

**Comment by gchanan** [comment]
This was fixed in the referenced PR.
