### ISSUE TITLE
NCCL bug. Need to upgrade NCCL submodule?

### ISSUE THREAD

**Issue by amsword** [pytorch/pytorch#20927]
Based on the following two threshods. NCCL 2.4 has some issues. Wondering if pytorch needs to upgrade NCCL submodule. 

https://github.com/horovod/horovod/issues/893
https://github.com/NVIDIA/nccl/pull/185

**Comment by mrshenli** [comment]
Yes, a PR was submitted. See #20882

**Comment by mrshenli** [comment]
closed by #20882
