### ISSUE TITLE
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:405

### ISSUE THREAD

**Issue by xhuvom** [pytorch/pytorch#20966]
## To Reproduce

1. conda create -n gan
2. conda activate gan
3. conda install -c pytorch pytorch-nightly
4. conda install -c fragcolor cuda10.0
5. python2 >> import torch

## Expected behavior
Torch should be imported

## Environment

PyTorch version: 1.0.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
CMake version: version 3.14.20190523-gf03a8

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 418.56
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.16.3
[pip] torch==1.1.0
[pip] torchfile==0.1.0
[pip] torchvision==0.2.2.post3
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch-nightly           1.2.0.dev20190526 py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch

**Comment by ailzhang** [comment]
@xhuvom  would you mind double check your pytorch install? The latest one you can get from conda should be 1.1.0, it sounds like there's some discrepancy in the environment. 
Please feel free to reopen this issue you you can consistently repro the behavior with the latest pytorch release.

**Comment by ShijianXu** [comment]
@xhuvom Hi, have you solved this problem? I also meet with the same problem when testing cycleGAN. My PyTorch version is: 1.0.1.post2.

I will try to check the latest version later if the problem can not be solved. Thanks.
