### ISSUE TITLE
[Bug] Error using .view(-1) after torch.meshgrid

### ISSUE THREAD

**Issue by dashidhy** [pytorch/pytorch#20960]
## To Reproduce
```bash
>>> import torch
>>> ax = torch.arange(4)
>>> ay = torch.arange(5)
>>> x, y = torch.meshgrid(ax, ay)
```
when using .view(-1):
```bash
>>> x.view(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /opt/conda/conda-bld/pytorch_1549630534704/work/aten/src/TH/generic/THTensor.cpp:213
```

However, there is no error when resizes to other shapes

```bash
>>> x.view(2, 2, 5)
tensor([[[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3]]])
```

## Environment
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] torch==1.0.1.post2
[pip] torch-cluster==1.2.4
[pip] torch-geometric==1.1.1
[pip] torch-scatter==1.1.2
[pip] torch-sparse==0.2.4
[pip] torch-spline-conv==1.0.6
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.1                      144    defaults
[conda] mkl_fft                   1.0.10           py36ha843d7b_0    defaults
[conda] mkl_random                1.0.2            py36hd81dba3_0    defaults
[conda] pytorch                   1.0.1           py3.6_cuda10.0.130_cudnn7.4.2_2    pytorch
[conda] torch-cluster             1.2.4                    pypi_0    pypi
[conda] torch-geometric           1.1.1                    pypi_0    pypi
[conda] torch-scatter             1.1.2                    pypi_0    pypi
[conda] torch-sparse              0.2.4                    pypi_0    pypi
[conda] torch-spline-conv         1.0.6                    pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch

**Comment by colesbury** [comment]
As the error message says "Call .contiguous() before .view()". Or **use reshape()** which will do that for you when necessary.

view() is only guaranteed to succeed on contiguous tensors. x is not contiguous. Check out x.stride(), and x.storage(). Note that it uses stride 0 to repeat elements without repeating them in memory (i.e. the storage). 

See https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.strides.html for some more explanation about strides

**Comment by colesbury** [comment]
Also see https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view
