### ISSUE TITLE
assignment to a twice-sliced tensor does nothing

### ISSUE THREAD

**Issue by fuzic** [pytorch/pytorch#20962]
## 🐛 Bug

Assignment to a twice sliced tensor (for example, masking a tensor and then slicing that masked tensor) drops the assignment altogether.

The same thing is true when `tensor[][].copy_()` is invoked - nothing is actually assigned to any portion of `tensor`

## To Reproduce

>>> a = torch.arange(10)
>>> mask = (a < 4)
>>> a[mask][1:] = -1
>>> a
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Expected behavior

>>> a = torch.arange(10)
>>> mask = (a < 4)
>>> a[mask][1:] = -1
>>> a
tensor([0, -1, -1, -1, 4, 5, 6, 7, 8, 9])
## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): centos
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by colesbury** [comment]
Indexing using a mask is not slicing -- it returns a copy not a view.

You may want to refer to https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

**Comment by fuzic** [comment]
@colesbury that would make sense, but then why does assigning to a masked tensor work? wouldn't that be assigning to a copy, which would be a temp/discarded?

>>> a = torch.arange(10)
>>> mask = (a < 4)
>>> a[mask] = -1
>>> a
tensor([-1, -1, -1, -1,  4,  5,  6,  7,  8,  9])

**Comment by soumith** [comment]
assignment will call  __newindex__ on the same tensor

**Comment by colesbury** [comment]
Soumith is referring to [`__setitem__`](https://docs.python.org/3/reference/datamodel.html#object.__setitem__). (newindex is Lua)

`a[mask] = -1` is is evaluated as single operation  `a.__setitem__(mask, -1)`

This is notably different from C++ where the same syntax would be two operations (`operator[]` and `operator=`)

**Comment by fuzic** [comment]
thanks for explaining! that makes sense.
