### ISSUE TITLE
HTTPS error in pytorch.org

### ISSUE THREAD

**Issue by iamgeo92** [pytorch/pytorch#20970]
There is https error on https://www.pytorch.org/ 
If you remove "www" , the error goes. 
This should not happen.

![http_pt](https://user-images.githubusercontent.com/7668755/58385881-0949a280-8015-11e9-8bc9-574d3c01e81b.png)

**Comment by soumith** [comment]
this is expected. Our host Github Pages doesn't generate https cert for *.pytorch.org, just pytorch.org
If we hosted the site on our own, we could generate the cert to also cover www.pytorch.org
