### ISSUE TITLE
How to do matrix multiplication between two 2D sparse directly and quickly

### ISSUE THREAD

**Issue by Louis-udm** [pytorch/pytorch#20988]
## 🚀 Feature
I want a function like torch.sparse.mm(sparse_matrix1, sparse_matrix2)

## Motivation
I know torch.sparse.mm(sparse_magrix1, sparse_matrix2.to_dense()) , but this will spend a lot of memory when sparse_matrix2's shape is large.

**Comment by Louis-udm** [comment]
I found the TensorFlow has this function:
tf.sparse_matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    name=None
)
I sincerely hope that PyTorch also has it!

**Comment by rgommers** [comment]
@aocsa this is complete right, or is there any follow-up left to do?

**Comment by aocsa** [comment]
@rgommers, yes this PR is completed, and it's merged.
