### ISSUE TITLE
Compile from source failed on NVIDIA TX1:  class "__half" has no member "x"

### ISSUE THREAD

**Issue by KnowingNothing** [pytorch/pytorch#20986]
I want to build pytorch v1.0.1 on NVIDIA TX1, the configs are:
Install the project...
-- Install configuration: "Release"
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Found CUDA: /usr/local/cuda-9.0 (found suitable version "9.0", minimum required is "5.5")
-- Autodetected CUDA architecture(s): 5.3
-- got cuda version 9.0
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- CUDA_NVCC_FLAGS:  -DTH_INDEX_BASE=0 -I/home/nvidia/sd/pytorch/torch/lib/tmp_install/include   -I/home/nvidia/sd/pytorch/torch/lib/tmp_install/include/TH -I/home/nvidia/sd/pytorch/torch/lib/tmp_install/include/THC   -I/home/nvidia/sd/pytorch/torch/lib/tmp_install/include/THS -I/home/nvidia/sd/pytorch/torch/lib/tmp_install/include/THCS   -I/home/nvidia/sd/pytorch/torch/lib/tmp_install/include/THPP;-D__CUDA_NO_HALF_OPERATORS__;-gencode;arch=compute_53,code=sm_53;-DCUDA_HAS_FP16=1
-- THC_SO_VERSION: 1

and the errors are:
/home/nvidia/pytorch/torch/lib/THC/THCHalf.cu(40): error: class "__half" has no member "x"

/home/nvidia/pytorch/torch/lib/THC/THCHalf.cu(41): error: class "__half" has no member "x"

/home/nvidia/pytorch/torch/lib/THC/THCHalf.cu(42): error: class "__half" has no member "x"

/home/nvidia/pytorch/torch/lib/THC/THCHalf.cu(80): error: class "__half" has no member "x"

/home/nvidia/pytorch/torch/lib/THC/THCHalf.cu(88): error: class "__half" has no member "x"

/home/nvidia/pytorch/torch/lib/THC/THCHalf.cu(92): error: class "__half" has no member "x"

/home/nvidia/pytorch/torch/lib/THC/THCHalf.cu(122): error: class "__half" has no member "x"

7 errors detected in the compilation of "/tmp/tmpxft_00003d2f_00000000-6_THCHalf.cpp1.ii".
CMake Error at THC_generated_THCHalf.cu.o.cmake:267 (message):
  Error generating file
  /home/nvidia/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCHalf.cu.o

CMakeFiles/THC.dir/build.make:546: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o' failed
make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/THC.dir/all' failed
make[1]: *** [CMakeFiles/THC.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I tried to use  export TORCH_NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__" but the same errors occurred again.
Could anybody give me some hints?

**Comment by soumith** [comment]
i think you have a botched CUDA install. `__half.x` is pretty much what nvidia ships.
reinstall your cuda

**Comment by colesbury** [comment]
Or maybe your PyTorch checkout? I think THCHalf.cu was removed sometime between v0.4.1 and v1.0.0.
