### ISSUE TITLE
The true value is not what it looks like

### ISSUE THREAD

**Issue by Woolseyyy** [pytorch/pytorch#20993]
## 🐛 Bug

The true value of the element of tensor seems not to be what it looks like and what it should be. 
The debuger shows that a variable x is 1.0000, while `torch.sqrt(1.0 - torch.pow(x, 2))` is nan and `x > 1` is true.  What's worse, some other 1.0000 variable shows the opposite. They are all produced by computing cos, which means they should be no more than 1.

## To Reproduce
```
x = _l2_norm(x, 1)
cosine = torch.matmul(x, x.transpose(0, 1))
sine = torch.sqrt(1.0 - torch.pow(cosine, 2))
```
```
def _l2_norm(input, axis=1):
    norm = torch.norm(input, 2, axis, True)
    output = torch.div(input, norm)
    return output
```

## Expected behavior

There are some `nan` in diagonal of sine and `cosine < 1` behaves strange.
I am wondering whether there are some tricks about storage I don't know.

## Environment

PyTorch version: 0.3.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.1 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 396.37
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl    defaults
[conda] cuda92                    1.0                           0    pytorch
[conda] mkl                       2019.1                      144    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] mkl-service               1.1.2            py37h90e4bf4_5    defaults
[conda] mkl_fft                   1.0.10           py37h14c3975_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] mkl_random                1.0.2            py37h637b7d7_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] pytorch                   0.4.1           py37_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
[conda] torchfile                 0.1.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] torchsample               0.1.3                    pypi_0    pypi
[conda] torchvision               0.2.1                 py37_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

**Comment by Woolseyyy** [comment]
The bug can't be avoid with clamp.
`(cosine.clamp(-1, 1) < 1)[1][1] = tensor(0, device='cuda:2', dtype=torch.uint8)`

**Comment by vadimkantorov** [comment]
A hypothesis: some of the x are actually > 1 (because of numerical issues of L2-normalization), but are shown as "1.00000" because of rounding.

The easiest fix is to add a small epsilon before taking a square root. Beware of clamp, because it would produce no gradients if the value is clamped.

**Comment by ailzhang** [comment]
I remember fixing a similar issue for cosine #18250, since you are on 0.3.1, could you please try 1.1.0 and see if the issue still persists? 
Please feel free to reopen if it's still there! Thanks!
