### ISSUE TITLE
Unable to use Pytorch with CUDA

### ISSUE THREAD

**Issue by rohanpandey** [pytorch/pytorch#20990]
I am unable to use pytorch with CUDA despite having installed it.

OS: Windows 10
Pytorch Version: 1.1.0
CUDA Version: 10.0

I get the following error. Any help would be appreciated. 

![image](https://user-images.githubusercontent.com/31413869/58431540-f5ad4300-80cb-11e9-8f04-cc6fe98acb1e.png)

**Comment by Jonas1312** [comment]
Duplicate #20635

**Comment by rohanpandey** [comment]
Where should this addition be done? In the main file?

**Comment by rohanpandey** [comment]
I'm trying to run openNMT train file. And I am encountering the same issue.

**Comment by rohanpandey** [comment]
@Jonas1312. The previous command works now. But I have this error. Any ideas?

![image](https://user-images.githubusercontent.com/31413869/58434040-60b04700-80d7-11e9-9438-8dcb560d5cbc.png)

**Comment by rohanpandey** [comment]
I was able to solve this simply by using the torch.cuda.current_device() command. Thanks

**Comment by smanj2** [comment]
I was facing the same issue and i tried using torch.cuda.current_device() which outputs 0.
Not the same code 
```
torch._C._cuda_init()
```
throws the following error:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-16503520507d> in <module>
----> 1 torch._C._cuda_init()

RuntimeError: CUDA error: unknown error
```

Any clue how to fix this ?

**Comment by peterjc123** [comment]
@smanj2 
Would you please put the following code block in front of all the other code and try again? 
```python
import torch
torch.cuda.current_device()
torch.cuda._initialized = True
```

**Comment by nonstopfor** [comment]
I met this problem, too. And I found that calling torch.cuda.current_device() could solve this problem because the function calls _lazy_init(). So the core problem is the cuda is not initialized correctly(maybe due to the version of cuda). So you just need to add the following code at the beginning.
`torch.cuda._lazy_init() `
or 
`torch.cuda.init()`
because torch.cuda.init() only calls _lazy_init() inside
