### ISSUE TITLE
PTX JIT compilation failed when running FasterRCNN

### ISSUE THREAD

**Issue by MinHyung-Kang** [pytorch/pytorch#21004]
## 🐛 Bug

Trying to run FasterRCNN newly released in torchvision 0.3 runs into PTX JIT compilation failed error. This fails on my Google Cloud instance using GPU, but does not fail using CPU

## To Reproduce

Simple code that fails
```
import torch 
import torchvision
import torch.nn as nn
    
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model =torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True).to(device)
    
images = list(torch.randn((1,3,512,512)).to(device))
targets = [{
        "boxes": torch.randn((1,4)),
        "labels": torch.randn((1)),
        "image_id": torch.randn((1)),
        "area": torch.randn((1)),
        "iscrowd": torch.randn((1))
    }]
targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

loss_dict = model(images, targets)
```

Error output:
```
File "debug2.py", line 19, in <module>
    loss_dict = model(images, targets)
  File "/opt/anaconda3/envs/nuscenes/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/nuscenes/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 48, in forward
    features = self.backbone(images.tensors)
  File "/opt/anaconda3/envs/nuscenes/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/nuscenes/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/opt/anaconda3/envs/nuscenes/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/nuscenes/lib/python3.7/site-packages/torchvision/models/_utils.py", line 58, in forward
    x = module(x)
  File "/opt/anaconda3/envs/nuscenes/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:202: a PTX JIT compilation failed
```

## Expected behavior

To run

## Environment
```
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Debian GNU/Linux 9.8 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 410.72
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] intel-numpy==1.15.1
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torchvision               0.3.0                    pypi_0    pypi
```

**Comment by janacht** [comment]
For me this issue occured with CUDA 10.0 and installing PyTorch from pip. Installing PyTorch 1.1 and Torchvision according to the instructions on https://pytorch.org/ (for Linux, CUDA 10.0, Python 3.6 and pip):
```
pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
```
solved it for me.

**Comment by ngimel** [comment]
This is a cuda initialization error in disguise, not really JIT compilation error, so making sure driver + pytorch cuda version + torch vision cuda version match usually solves it. It would be great to have a more helpful error message, but so far we are unable to repro.

**Comment by MinHyung-Kang** [comment]
Thank you for taking a look! It seems like I cannot install the wheels on my current google cloud instance. I can try to create a new image with new installations and will report back if that solves it

**Comment by MinHyung-Kang** [comment]
I was able to run it successfully after install using correct conda commands. Thank you for the help!

**Comment by FantasyJXF** [comment]
> For me this issue occured with CUDA 10.0 and installing PyTorch from pip. Installing PyTorch 1.1 and Torchvision according to the instructions on https://pytorch.org/ (for Linux, CUDA 10.0, Python 3.6 and pip):
> 
> ```
> pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
> pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
> ```
> 
> solved it for me.


`pip uninstall torch torchvision` and reinstall as you said solve my problem. Maybe I used the wrong source before.

**Comment by AlexTS1980** [comment]
I switched to CUDA 9.0 and it worked

**Comment by denfromufa** [comment]
seems like some incompatibility between cupy and pytorch at least on cuda 10.1
