### ISSUE TITLE
RuntimeError: isTensor() ASSERT FAILED when torch.jit.trace with torch.jit.script

### ISSUE THREAD

**Issue by One-sixth** [pytorch/pytorch#21009]
## 🐛 Bug

I don't know which caused this problem.

## To Reproduce

1. 

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.jit


@torch.jit.script
def resize_ref(x, shortpoint, method: str='bilinear', align_corners: bool=True):
    """
    :type x: torch.Tensor
    :type shortpoint: torch.Tensor
    :type method: str
    :type align_corners: bool
    """
    hw = shortpoint.shape[2:4]
    ihw = x.shape[2:4]
    if hw != ihw:
        x = F.interpolate(x, hw, mode=method, align_corners=align_corners)
    return x


class Net(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x2 = F.interpolate(x, scale_factor=2)
        y = resize_ref(x, x2)
        return y


a = torch.rand(1, 3, 6, 6)
net = Net()
net = torch.jit.trace(net, a)
b = net(a)
print(b.shape)

```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.1.0
 - OS (e.g., Linux):win10
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:3.7
 - CUDA/cuDNN version:10
 - GPU models and configuration:gtx970m
 - Any other relevant information:

**Comment by peterjc123** [comment]
Are you trying to mix the debug/release build? When you build with the debug configuration, you'll need the debug binaries. Go to https://pytorch.org, select Stable, Windows, LibTorch, C++ and download the debug version of LibTorch.

**Comment by One-sixth** [comment]
> Are you trying to mix the debug/release build? When you build with the debug configuration, you'll need the debug binaries. Go to https://pytorch.org, select Stable, Windows, LibTorch, C++ and download the debug version of LibTorch.

I installed pytorch using pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp37-cp37m-win_amd64.whl. Not built by myself. I don't use libtorch.

**Comment by peterjc123** [comment]
Then you'll need to build with Release configuration in VS.

**Comment by peterjc123** [comment]
Oh, sorry, I didn't see this carefully.

**Comment by wanchaol** [comment]
thanks for raising this issue, there's some bug currently on mixing tracing and scripting for not properly inline the constants for non tensor types, we will look into it.

**Comment by wanchaol** [comment]
This should already been fixed now :)
