### ISSUE TITLE
Stop using "AAA" prefix for builds

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#21017]
I've been seeing build names like "AAA_pytorch_linux_trusty_py3_5_build". A dig through the source code indicates that the "AAA" prefix just means that the build is "important".

Could we change "AAA" to "important" so that not everyone needs to dig through the source code to understand what this test is?  cc @kostmo

**Comment by colesbury** [comment]
It's the old Yellow Pages trick to make them show up first alphabetically...

(FWIW, I like that the important builds show up on top)

**Comment by kostmo** [comment]
+@suo

**Comment by suo** [comment]
Someone mentioned that `_IMPT` works just as well for putting things first, maybe we can change it to that

**Comment by clee2000** [comment]
Closing since this naming convention is no longer used
