### ISSUE TITLE
can torch.logdet() and  torch.cholesky_inverse() support batch operations

### ISSUE THREAD

**Issue by mzhaoshuai** [pytorch/pytorch#21011]
### can `torch.logdet()`  support batch operations
```
torch.logdet(A) → Tensor
Parameters
    A (Tensor) – The input 2D square tensor
```
Can `torch.logdet()` support batch operations?
This function now is a little wired cause `torch.cholesky()` already support batch operations.
Then we can get a batch version according to `tensorflow`s implementation:
```
def log_det_by_cholesky(matrix):
	"""
	Args:
		matrix: matrix must be a symmetric positive define matrix.
				shape [N, C, D, D].
	Ref:
		https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/ops/linalg/linalg_impl.py
	"""
	# This uses the property that the log det(A) = 2 * sum(log(real(diag(C))))
	# where C is the cholesky decomposition of A.
	chol = torch.cholesky(matrix)
	return 2.0 * torch.sum(torch.log(torch.diagonal(chol, dim1=-2, dim2=-1)), dim=-1)
```

### can `torch.cholesky_inverse()`  support batch operations

```
torch.cholesky_inverse(u, upper=False, out=None) → Tensor
Parameters
    u (Tensor) – the input 2-D tensor, a upper or lower triangular Cholesky factor
```
Can `torch.cholesky_inverse` support batch operations?

## Motivation
To accelerate the computation when doing matrix operations.
Also motivated by [PyTorch for Scientific Computing](https://www.pugetsystems.com/labs/hpc/PyTorch-for-Scientific-Computing---Quantum-Mechanics-Example-Part-3-Code-Optimizations---Batched-Matrix-Operations-Cholesky-Decomposition-and-Inverse-1225/#matrix-version-of-cholesky-decomposition-in-pytorch).

**Comment by vishwakftw** [comment]
Hi @mzhaoshuai, thank you for your suggestion.

We support `torch.logdet` for general matrices, and not just symmetric positive semi-definite matrices. We are constrained by the lack of batch SVD which is used for the derivative in the general scenario. But when that's done, we should be able to support a variety of linear algebra methods in batch mode.

I will close this issue in interest of #7500, which is a feature tracker for batched linear algebra ops. I'll add your suggestions in the task list there.

Thank you.
