### ISSUE TITLE
Visual noise being introduced by Bicubic interpolation

### ISSUE THREAD

**Issue by mdlockyer** [pytorch/pytorch#21044]
## 🐛 Bug

It seems that the new Bicubic interpolation is introducing some noise/artifacts into images.

## To Reproduce

[gist](https://gist.github.com/mdlockyer/100194e984e0a44c0fdd51fa74ef03fe) that demonstrates the issue.

## Expected behavior

The image should look great! Bicubic interp rocks. Obviously there are plenty of examples out there(e.g., OpenCV, Pillow,...).

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Mac OSX 10.14.4
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[conda] blas 1.0 mkl
[conda] mkl 2019.3 199
[conda] mkl-service 1.1.2 py37hfbe908c_5
[conda] mkl_fft 1.0.10 py37h5e564d8_0
[conda] mkl_random 1.0.2 py37h27c97d8_0

## Additional context

Here is the original image:
![dog](https://user-images.githubusercontent.com/30844227/58517545-5c386c80-8171-11e9-9fcb-fdd2bd765f55.jpg)
And the result when using Bicubic interpolation:
![bad_dog](https://user-images.githubusercontent.com/30844227/58517492-31e6af00-8171-11e9-9b7e-04030d36fd8a.png)
Same image using Bilinear interpolation:
![good_dog](https://user-images.githubusercontent.com/30844227/58517625-acafca00-8171-11e9-9564-5f37117ec2ae.png)

**Comment by ailzhang** [comment]
@MichaelDylan77 For bicubic we tried to match opencv implementation. Would you mind give that a try and see if the result matches?

**Comment by MichaelDylan77** [comment]
@ailzhang OpenCV does not produce the noise. The results look identical everywhere else though. I've updated the [gist](https://gist.github.com/MichaelDylan77/100194e984e0a44c0fdd51fa74ef03fe) to show results from both.

**Comment by ailzhang** [comment]
Thanks for reporting! @MichaelDylan77 I will put this in my queue for now and get to it maybe early next week.

**Comment by MichaelDylan77** [comment]
Thanks! I’m really excited to have bicubic in pytorch. I’ve been hoping for this for a while. Also the addition of “area” as well. I’ve testing the new implementation and it’s great. Awesome results for down sampling

**Comment by S-aiueo32** [comment]
I have the same one.
It seems to be caused by over/undershooting.

**Comment by ailzhang** [comment]
Hi I've confirmed it's indeed caused by overshoot. Given pytorch takes float tensor as input, we'd prefer to keep the unclamped result and let users do clamp as needed. In this case adding a `.clamp(0)` before displaying fixes it. So I'm updating the doc to include it as a note. 
Instead our `to_pil_image` could potentially be updated to do an implicit type conversion to avoid visual overshoot. See the issue reference above to track discussion there.
