### ISSUE TITLE
ImportError (undefined symbol: ...LongTensor) when importing torch

### ISSUE THREAD

**Issue by ntomita** [pytorch/pytorch#2104]
Hi all,
I'm having a problem with importing torch after updated packages to latest. Here's trackback:
`>>> import torch`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
 ` File "/home/ntomita/pytorch-env/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *`
`ImportError: /home/ntomita/pytorch-env/lib/python2.7/site-packages/torch/_C.so: undefined symbol: _ZN4thpp10THCSTensorIlEC1EP8THCStateP14THCSLongTensor`

I got this error after I updated pytorch/torchvision as follows
`    pytorch:     0.1.12-py27_0 --> 0.1.12-py27_2cu75 soumith`
`    torchvision: 0.1.8-py27_0  --> 0.1.8-py27_2      soumith`
using `conda update pytorch torchvision -c soumith`

Clean-install didn't help either. I believe there's something wrong with the latest package.

Is anybody had same problem? (I could roll back to older version but that version has a problem with torchvision.transforms.Scale, which says `TypeError: unsupported operand type(s) for /: 'list' and 'int'` when feeding a list of int as a size. So I really want to use the latest modules.)

**Comment by soumith** [comment]
Sorry for this, please use the workaround in this comment. Also this issue is being tracked there, so closing this thread: https://github.com/pytorch/pytorch/issues/2091#issuecomment-315227119
