### ISSUE TITLE
is there an equivalent of `tf.nn.embedding_lookup` in Caffe2 Python API?

### ISSUE THREAD

**Issue by shalijiang** [pytorch/pytorch#21043]
## ❓ Questions and Help

I'm trying to find an equivalent of tf.nn.embedding_lookup` in Caffe2. 
Seems there is a C++ interface, but couldn't find the python interface. 

BTW, does this link (https://caffe2.ai/doxygen-python/html/annotated.html) contain all python APIs for Caffe2? Seems I couldn't find the documentation of certain functions, e.g., `core.C.create_db`

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
