### ISSUE TITLE
Segfault on multiple threads calling `select` and `to` on different tensors

### ISSUE THREAD

**Issue by n-west** [pytorch/pytorch#21063]
## 🐛 Bug

Memory corruption between two threads: one calling select and another moving a tensor to `kCUDA`.

## To Reproduce

Build the attached file and execute it. I've included a small CMakeLists.txt that can be used for an easy build

1. Save the following as test_threading_safety.cpp

```c++
#include <thread>
#include <chrono>
#include <torch/torch.h>

static bool run = true;

void assign_to_tensor() {
        while (run) {
            torch::Tensor tensor_to_fill = torch::ones({8192});
            for (size_t fill_index = 0; fill_index < 8192; ++fill_index) {
                tensor_to_fill.select(0, fill_index) = 4.2;
            }
        }
}

void move_tensor() {
    std::vector<torch::Tensor> x;
    while(run) {
        auto tensor_to_move = torch::ones(10000);
        tensor_to_move = tensor_to_move.to(torch::kCUDA);
    }
}

int main() {
    std::vector<std::thread> t1;
    // 1 thread has a reasonably high chance of triggering a segfault, more threads makes it more or less 100%
    for (size_t thread_count = 0; thread_count < 10; ++thread_count) {
        t1.emplace_back(std::thread(assign_to_tensor));
        t1.emplace_back(std::thread(move_tensor));
    }

    std::cout << "Waiting 5 seconds." << std::endl;
    std::this_thread::sleep_for(std::chrono::seconds(5));
    std::cout << "Done... notifying threads to stop." << std::endl;
    run = false;

    for (auto &thread : t1) {
        thread.join();
    }
    return 0;
}
```
2. Save the following as CMakeLists.txt
```
cmake_minimum_required(VERSION 3.0)

set(CMAKE_CXX_STANDARD 14)

execute_process(COMMAND python -c "import torch; print(torch.__path__[0])"
        OUTPUT_STRIP_TRAILING_WHITESPACE
        OUTPUT_VARIABLE torch_cmake_dir)
set(torch_cmake_dir "${torch_cmake_dir}/share/cmake")

if(NOT CMAKE_PREFIX_PATH)
    set(CMAKE_PREFIX_PATH "${torch_cmake_dir}" CACHE CMAKE_PREFIX_PATH "Expand Prefix Path" FORCE)
endif()

find_package(Torch)

add_executable(test_thread_safety test_thread_safety.cpp)
target_link_libraries(test_thread_safety ${TORCH_INCLUDE_DIRS})
target_link_libraries(test_thread_safety ${TORCH_LIBRARIES})
```
3. `mkdir build && cd build && cmake && make`
4. `./test_thread_safety`

## Expected behavior

The messages "Waiting 5 seconds." and "Done... notifying threads to stop" should print and a return code of 0.

I actually get
```
./test_thread_safety 
Waiting 5 seconds.
Segmentation fault (core dumped)
```

80% of the time (can be increased by adding more threads).

## Environment

```
PyTorch version: 1.0.0a0+8322165
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 410.79
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.1

Versions of relevant libraries:
[pip] numpy==1.16.3
[pip] torch==1.0.0a0+8322165
[conda] Could not collect
```

## Additional context

I typically use accessors for this kind of work, but some code that used `operator[]` which delegates to `select(int, int)` triggered erratic behavior in a more complex codebase. This narrows it down to the simplest case I could find. According to the very last example on https://pytorch.org/cppdocs/notes/tensor_basics.html I think this should still be valid code. It appears that the trigger involves *both* the select assignment and the movement to GPU even though they are different tensors.

**Comment by colesbury** [comment]
@n-west thanks for the self contained repro. Have you tried this on PyTorch 1.1.0? I wasn't able to reproduce the issue on master even after increasing the number of threads

**Comment by n-west** [comment]
I just got around to building v1.1.0 (previous was v1.0.1) and I'm not seeing the segfault anymore in the example code. I'll check v1.1.0 with the larger application tomorrow and close if that appears OK. Thanks!

**Comment by n-west** [comment]
@colesbury after upgrading to libtorch 1.1 all of the segfaults I saw in the larger application and minimal repro seem to go away. closing the issue. Thanks for all the great work on pytorch! :-)
