### ISSUE TITLE
What is Mac system requirement to install caffe2?

### ISSUE THREAD

**Issue by myproject24** [pytorch/pytorch#21060]
Hi, @ezyang @apaszke @neoinmtv @soumith what is the Mac machine requirements to install caffe2?

I have Mac mini with 500GB storage, 4GB RAM, and Intel Core i5 processor. is it possible to install caffe2 on my Mac mini?

> OS: MacOS Mojave 10.14.2
> Processor: Intel Core i5 2.5 GHz
> Graphics: Intel HD Graphics 4000 1536 MB
> RAM: 4GB DDR3
> Storage: 500GB SATA

**Comment by ailzhang** [comment]
Hi please reopen the question in pytorch forum. Thanks!
