### ISSUE TITLE
tensor.pin_memory always copies even when it is already pinned

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#21076]
## 🐛 Bug
Doc says that it copies if the data is not in pinned memory, but...

```
In [27]: x = torch.randn(3)

In [28]: x.is_pinned()
Out[28]: False

In [29]: x = x.pin_memory()

In [30]: x.is_pinned()
Out[30]: True

In [31]: x.pin_memory().storage().data_ptr()
Out[31]: 139755750687744

In [32]: x.storage().data_ptr()
Out[32]: 139755182358528

```

**Comment by codexetreme** [comment]
Can I fix this issue if it turns out to be a bug?

**Comment by ailzhang** [comment]
@codexetreme Go ahead! Feel free to ping us on this thread if you have questions/need help!

**Comment by codexetreme** [comment]
Cool, I am going to try and fix it :)

**Comment by codexetreme** [comment]
Ok, so from what I understand, the code goes from `storage.py`'s `pin_memory(self)` to `copy_()`. But I found many implementations of the copy_ function, so could you tell me where is it located? 

One potential location I found was in `Memory.cpp`  and `Copy.cpp` (both in ATen/Native) , is this the right place to look?

**Comment by VitalyFedyunin** [comment]
The goal is to avoid copy, so you need to update aten/src/ATen/native/Memory.cpp . And instead of creating new storage, you can get storage of `self` and use it to construct new tensor.

**Comment by SsnL** [comment]
I think it should just return the original tensor in this case, like what
.contiguous does

**Comment by codexetreme** [comment]
I have a doubt, If we return the original tensor directly , it won't be copied into the pinned memory right?, Because we haven't set the storage to do anything with the pinned memory

**Comment by VitalyFedyunin** [comment]
I'm comfortable with both options (reusing storage or returning same tensor). 

@codexetreme You need to check if it already pinned, and if it is, return self. Otherwise follow old behavior.
