### ISSUE TITLE
Tensorboard add_scalar function also appends into self.scalar_dict

### ISSUE THREAD

**Issue by neherh** [pytorch/pytorch#21089]
## 🚀 Feature
Append scalar using add_scalar into self.scalar_dict in SummaryWriter class.

## Motivation

Appending a scalar value in the scalar_dict allows the user to export the data into a json file. Exporting scalar data, however, is only featured by calling the add_scalars (multiple together) function. It seems to me that the scalar_dict should hold all scalar data and not data reserved only in the add_scalars function.

## Pitch
While calling add_scalar, the data is appended into the scalar_dict of SummaryWriter in order for **ALL** scalar data to be exported.

**Comment by lanpa** [comment]
Hi, all numbers saved by add_scalar can be downloaded by tensorboard by clicking on the `Show data download links` on the top left corner. Since add_scalar is used by almost all tensorboard users and is usually called frequently, I don't recommend adding overhead on this function. cc @orionr

**Comment by orionr** [comment]
That's correct - we specifically don't want to have the overhead of a local `scalar_dict`. Theoretically you could do this yourself outside the SummaryWriter. I don't think `add_scalars` does this either in the `torch.utils.tensorboard` implementation.
