### ISSUE TITLE
[discussion][cuda] pin_memory() asks for ctx on current device

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#21081]
`tensor.pin_memory()` always asks for a context on the current device. This means that even if you use `torch.device('cuda:1')` everywhere in the program, a simple `DataLoader(..., pin_memory=True)` will create a context on GPU 0. 

A little dig into [`cudaHostAlloc`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gb65da58f444e7230d3322b6126bb4902) and our `THCCachingHostAllocator` tells me that:
+ We allocate pinned memory with [`cudaHostAlloc(ptr, size, cudaHostAllocDefault)`.](https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCCachingHostAllocator.cpp#L87)
+ [Such allocated pointers can be directly used by any device, regardless of the current device at the time of allocation, since we assume unified addressing. ](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__UNIFIED.html)

Therefore, I wonder, instead of always asking for a context on the current device, if `tensor.pin_memory()` should just grab any CUDA context if exists.

@colesbury pointed out that many other functions also create context on current device. But I think they are not as frequent as this.

**Comment by colesbury** [comment]
> @colesbury pointed out that many other functions also create context on current device

I actually can't think of any other functions that aren't device-specific. (I keep thinking cudaEventCreate is independent of device, but I think you can only record an event on the same device that it was created on)

**Comment by colesbury** [comment]
> tensor.pin_memory() should just grab any CUDA context if exists

Is there a way to do this?

**Comment by SsnL** [comment]
> Is there a way to do this?

One way is to use `cuDevicePrimaryCtxGetState`, but maybe just looking at the caching allocator is enough.
