### ISSUE TITLE
RuntimeError: CUDA error: initialization error

### ISSUE THREAD

**Issue by Hananel-Hazan** [pytorch/pytorch#21092]
## 🐛 Bug

Trying to make the default tensor location to cuda, `torch.utils.data.DataLoader` produce `RuntimeError: CUDA error: initialization error`

## To Reproduce

1. copy MNIST example [link](https://github.com/pytorch/examples/blob/master/mnist/main.py). 
2. add the lines:
device_id = 0
if use_cuda:
        torch.cuda.set_device(torch.device("cuda:" + str(device_id) if torch.cuda.is_available() else "cpu"))
        torch.set_default_tensor_type('torch.cuda.FloatTensor')

Before (or after) [line](https://github.com/pytorch/examples/blob/97304e232807082c2e7b54c597615dc0ad8f6173/mnist/main.py#L87) in the example 

## Result
cause to a error `RuntimeError: CUDA error: initialization error`

## workaround 
In order to solve it `kwargs` need to be empty
[line ](https://github.com/pytorch/examples/blob/97304e232807082c2e7b54c597615dc0ad8f6173/mnist/main.py#L89) meet to be `kwargs = {}`

## Expected behavior
default location should not create an error

## Environment
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.10.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: 
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X

Nvidia driver version: 410.104
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.1

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] Could not collect

Process finished with exit code 0

**Comment by ailzhang** [comment]
cc: @SsnL  is this a valid use case for dataloader?

**Comment by SsnL** [comment]
use spawn start method. see docs.
https://pytorch.org/docs/master/notes/multiprocessing.html#cuda-in-multiprocessing

**Comment by Hananel-Hazan** [comment]
@SsnL Thanks for the answer. 
Can you elaborate more about your answer?

**Comment by SsnL** [comment]
@Hananel-Hazan Please see the link I posted above.

**Comment by Hananel-Hazan** [comment]
@SsnL Thank you very much for the link. The explanation was very illuminating, useful and helpful.

**Comment by zuoxingdong** [comment]
@SsnL For me, `spawn` method gives me error `AttributeError: Can't pickle local object 'make_vec_env.<locals>.f'`, I have a method `make_vec_env` imported in the main file. 

Why spawn method tries to pickle this method ? Because it not called within the individual processes.

**Comment by mbchang** [comment]
After putting in
```
import torch.multiprocessing as mp
mp.set_start_method('spawn')
```
I also get the same error `AttributeError: Can't pickle local object`. Would anyone have any ideas how to fix this?

**Comment by SsnL** [comment]
Hi, for pickling errors, you likely are using some objects that python
pickled can not handle, e.g. objects that has pointers to functions defined
in local scopes. In some cases the code can be modified so that the object
become picklable, e.g by moving locally-defined functions to global scope.
Alternatively you can investigate using other pickers like cloudpickle or
dill.

**Comment by renesax14** [comment]
> use spawn start method. see docs.
> https://pytorch.org/docs/master/notes/multiprocessing.html#cuda-in-multiprocessing

Can you explain to us **what the error means in the first place**?

What does

```
RuntimeError: CUDA driver error: initialization error” 
```

mean? 

https://discuss.pytorch.org/t/what-does-runtimeerror-cuda-driver-error-initialization-error-mean/87505

**Comment by renesax14** [comment]
> @SsnL Thank you very much for the link. The explanation was very illuminating, useful and helpful.

How was that link useful at all?

Threads are dangerous, ok I already knew that. What exactly did you get out of it?

**Comment by renesax14** [comment]
> ## 🐛 Bug
> Trying to make the default tensor location to cuda, `torch.utils.data.DataLoader` produce `RuntimeError: CUDA error: initialization error`
> 
> ## To Reproduce
> 1. copy MNIST example [link](https://github.com/pytorch/examples/blob/master/mnist/main.py).
> 2. add the lines:
>    device_id = 0
>    if use_cuda:
>    torch.cuda.set_device(torch.device("cuda:" + str(device_id) if torch.cuda.is_available() else "cpu"))
>    torch.set_default_tensor_type('torch.cuda.FloatTensor')
> 
> Before (or after) [line](https://github.com/pytorch/examples/blob/97304e232807082c2e7b54c597615dc0ad8f6173/mnist/main.py#L87) in the example
> 
> ## Result
> cause to a error `RuntimeError: CUDA error: initialization error`
> 
> ## workaround
> In order to solve it `kwargs` need to be empty
> [line ](https://github.com/pytorch/examples/blob/97304e232807082c2e7b54c597615dc0ad8f6173/mnist/main.py#L89) meet to be `kwargs = {}`
> 
> ## Expected behavior
> default location should not create an error
> 
> ## Environment
> Collecting environment information...
> PyTorch version: 1.1.0
> Is debug build: No
> CUDA used to build PyTorch: 9.0.176
> 
> OS: Ubuntu 16.04.6 LTS
> GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
> CMake version: version 3.10.0
> 
> Python version: 3.6
> Is CUDA available: Yes
> CUDA runtime version: 8.0.61
> GPU models and configuration:
> GPU 0: GeForce GTX TITAN X
> GPU 1: GeForce GTX TITAN X
> 
> Nvidia driver version: 410.104
> cuDNN version: Probably one of the following:
> /usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
> /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.1
> 
> Versions of relevant libraries:
> [pip3] numpy==1.16.3
> [pip3] torch==1.1.0
> [pip3] torchvision==0.3.0
> [conda] Could not collect
> 
> Process finished with exit code 0

What did you end up doing to solve your problem? Why did it happen? Did you use `pin_memory=True`?

**Comment by cod3licious** [comment]
@renesax14 the workaround in the initial report helped. I had the same error when initialising the dataloader with
`DataLoader(my_torch_dataset, batch_size=32, shuffle=True, num_workers=1, pin_memory=True)`
but it worked with the default arguments, i.e.
`DataLoader(my_torch_dataset, batch_size=32, shuffle=True)`
(I think `num_workers` was the main problem; setting `pin_memory` didn't make a difference.)

I don't have an idea as to why, but at least it works...
Btw, this was on a single GPU, so at least in my case it had nothing to do with any multiprocessing stuff.

**Comment by yasser-h-khalil** [comment]
> After putting in
> 
> ```
> import torch.multiprocessing as mp
> mp.set_start_method('spawn')
> ```
> 
> I also get the same error `AttributeError: Can't pickle local object`. Would anyone have any ideas how to fix this?

Hello,

I am getting the same issue. Did anyone find a solution for this?

Thanks.
