### ISSUE TITLE
One libtorch FindTorch.cmake module to support multi-configs(both debug and release)

### ISSUE THREAD

**Issue by yelu** [pytorch/pytorch#21119]
## 🐛 Bug

Libtorch is excellent to provide cmake for multiple configs on windows. 

  * Download here (Release version): 
    https://download.pytorch.org/libtorch/cu90/libtorch-win-shared-with-deps-latest.zip
  * Download here (Debug version): 
    https://download.pytorch.org/libtorch/cu90/libtorch-win-shared-with-deps-debug-latest.zip

However, it is quite inconvenient. Usually, I need to copy different versions to switch between different configurations, which is annoying during development. Can we support both configs inside **one FindTorch.cmake**?

**Comment by soumith** [comment]
no, we explicitly dont aim to cover that. The binary files are already pretty large.
