### ISSUE TITLE
[reopen][utils.bottleneck] throws initialization error for cuda profiling

### ISSUE THREAD

**Issue by sakaia** [pytorch/pytorch#21112]
## 🐛 Bug
Reopen following issue
Problem still keeps
[utils.bottleneck] throws initialization error for cuda profiling #21016
https://github.com/pytorch/pytorch/issues/21016

## To Reproduce

See above

## Expected behavior

See above

## Environment

See above

## Additional context

See above

**Comment by sakaia** [comment]
This issue reproduce just two line on Colab
```
!git clone http://github.com/pytorch/examples
!python -m torch.utils.bottleneck examples/mnist/main.py --epochs 1 --batch-size=256
```

**Comment by sakaia** [comment]
If this issue is not reproduced, Please write your environment before close this issue.

**Comment by soumith** [comment]
reopened the other issue
