### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator aten::var

### ISSUE THREAD

**Issue by InnerPeaceStudios** [pytorch/pytorch#21139]
I want to export a model in the repo below to onnx (and export to coreml later on):

https://github.com/Yijunmaverick/CartoonGAN-Test-Pytorch-Torch

and produced the error, I am using latest version of pytorch.

I am really new to pytorch and deep learning, it took me days to get to this far, any help is appreciated.

**Comment by li-roy** [comment]
Can you provide a minimal repro for your issue?

**Comment by ezyang** [comment]
Or at the very least, what the error message is, and the script you're using to do the export.
