### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

### ISSUE THREAD

**Issue by c553094942** [pytorch/pytorch#21136]
Hi, when I trained Yolov3 with Caltech Pedestrian dataset, I encounter a problem:

```
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/media/yons/DATA/PycharmProjects/PyTorch-YOLOv3-master/train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/yons/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/yons/DATA/PycharmProjects/PyTorch-YOLOv3-master/models.py", line 259, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/home/yons/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/yons/DATA/PycharmProjects/PyTorch-YOLOv3-master/models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "/media/yons/DATA/PycharmProjects/PyTorch-YOLOv3-master/utils/utils.py", line 306, in build_targets
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0
RuntimeError: CUDA error: device-side assert triggered
```

Is there any solution?

**Comment by ngimel** [comment]
This means that you are sending out of bounds indices to your indexing operation. Likely b,g,or gi tensors contain wrong data.

**Comment by c553094942** [comment]
> This means that you are sending out of bounds indices to your indexing operation. Likely b,g,or gi tensors contain wrong data.

yeah,you are right. I found the error data.
Thank you!

**Comment by bingnoi** [comment]
could you please tell me how to locate the wrong place of data? i met the same trouble,

**Comment by igo312** [comment]
@jiaxiangshang  @bingnoi I run a few steps the error comes out. So what I do is just check every target.

And my error is the num limitation. my target coords sometimes will be a negative num or num bigger than image size. the coords will be a index for array. In result, the error comes out. 

Hoping it will help you.

**Comment by Kerwin0621** [comment]
This is caused by your discontinuous numbers defined in your ground truth label. It should be start from 0 then added by 1, for example : [0,1,2,...,], but your label might be: [0,1,3,101,...], which caused the index is out of bounds during CUDA calculation.
