### ISSUE TITLE
Add dynamic infer shape for nn.Linear

### ISSUE THREAD

**Issue by VoVAllen** [pytorch/pytorch#2117]
It's quite inconvenient for user to calculate the shape of tensor manually. I think it would be better to entitle nn.Linear with the ability to infer shape from the input tensor.
One possible solution is like numpy's reshape function, which is nn.Linear(-1, hidden_size) or nn.Linear(None, hidden_size) means automatic inferring.

My preliminary implementation for this is at here:
https://gist.github.com/VoVAllen/1420e410e3dfd368b8dc9061ad0c206a

This implementation doesn't create any overhead during the training process. Also I think this kind of style can be used in other layers such as nn.Conv.
Feel free to add any comments.

**Comment by VoVAllen** [comment]
Wrong implementation

**Comment by soumith** [comment]
we cannot have a dynamic inferring of the Linear layer weight sizes, because `parameters()` always have to return the full size of the linear layer. usually the optimizer is constructed with `model.parameters()` before a `forward` of the model is run.

**Comment by VoVAllen** [comment]
I think it's possible to first add placeholder in model.parameter() and then add in the real parameter later in first forward process. Since nobody will execute optimization before first forward process.  Kind of Mock Parameter, build an intermediate wrapper over parameter in optimizer setting.

**Comment by soumith** [comment]
it's not just the optimizer. We actually charter into a few other side-effects. hogwild will be broken for the linear layers:
- you create model
- send model to all processes (the weights have `.share_memory_()` called on them)
- then you train model in each of these subprocesses.

This will be broken as well, because once you share a Tensor through, you cant resize it (and if you replace the placeholder with a new Tensor, sharing is broken).

**Comment by VoVAllen** [comment]
Get it. Thank you for your explanation. It's more complicated than I thought. Hogwild's behavior is more likely a static graph construction. However I still feel regret that a dynamic graph framework cannot implement such infer shape things.

**Comment by VoVAllen** [comment]
Hope you could find a better solution for this later
