### ISSUE TITLE
pytorch image does not have cuda

### ISSUE THREAD

**Issue by antran89** [pytorch/pytorch#21259]
## To Reproduce

1. nvidia-docker run --rm -ti --ipc=host pytorch/pytorch:latest
1. python
1. import torch
1. torch.cuda.is_available()

It returns False because CUDA is not existing.

## Expected behavior

The docker of PyTorch should have CUDA to run training efficiently.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by soumith** [comment]
the problem isn't that. the problem is likely  that it didn't find a CUDA GPU on your machine.

**Comment by antran89** [comment]
Thank @soumith
