### ISSUE TITLE
'package not found error',while installing pytorch on anaconda python 3.7

### ISSUE THREAD

**Issue by Luiz-HSSD** [pytorch/pytorch#21254]
## 🐛 Bug
>conda install pytorch-cpu torchvision-cpu -c pytorch

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch-cpu
  - torchvision-cpu -> pytorch-cpu[version='>=1.0.0']

Current channels:

  - https://conda.anaconda.org/pytorch/win-32
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page

**Comment by soumith** [comment]
we dont support 32-bit operating systems with binaries.

**Comment by Luiz-HSSD** [comment]
the system is 64 bit

**Comment by soumith** [comment]
@Luiz-HSSD according to the message you posted above, you have anaconda python 32-bit installed

**Comment by erjan** [comment]
> we dont support 32-bit operating systems with binaries.

hi, does it mean i can't install pytorch on win32 machine at all?

**Comment by soumith** [comment]
@erjan correct

**Comment by brando90** [comment]
@soumith what about on this one:

```
$ conda install -y pytorch torchvision cudatoolkit=10.2 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch

Current channels:

  - https://conda.anaconda.org/pytorch/linux-ppc64le
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/linux-ppc64le
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-ppc64le
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

````

**Comment by soumith** [comment]
@brando90 looks like you are on a ppc64le which we don't have binaries for on the default pytorch channel (maybe IBM has them in their ppc64le channel)

**Comment by brando90** [comment]
> @brando90 looks like you are on a ppc64le which we don't have binaries for on the default pytorch channel (maybe IBM has them in their ppc64le channel)

Yes, they do here (https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/#/) but I just can't conda to install the right version though for some reason. There is a longer discussion here that might be useful for peeps in the future: https://github.com/IBM/powerai/issues/268#issuecomment-698291320
