### ISSUE TITLE
Add torchvision to pip index page

### ISSUE THREAD

**Issue by allegroai** [pytorch/pytorch#21260]
## 🚀 Feature
`torchvision` links should be added to `https://download.pytorch.org/whl/cuX/stable` pages.
## Motivation
`torchvision` packages are now parametrized by cuda version. For example, in the "Getting Started" table, for parameters stable/linux/pip/python3.6/cuda10, the wheel URL is `https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl`. Not having these in the index page means that automatic tools have to maintain a hard-coded copy of the "Getting Started" table in their own code. This is the same motivation for adding these links to the `torchvision` package.

**Comment by soumith** [comment]
fixed
