### ISSUE TITLE
Use of Tensor.contiguous() unconditionally results in Mypy linting errors

### ISSUE THREAD

**Issue by sdraper-CS** [pytorch/pytorch#21261]
## 🐛 Bug

In `tools/pyi/gen_pyi.py` there is no type hint provided for `Tensor.contiguous()` (`Tensor.is_contiguous()` is there however).  As a result uses of `.contiguous()` cause Mypy linting errors.  

In the case I had the line (the context and details of the tensors doesn't matter):

```
re_batched = seq_first.contiguous().view(expanded_tokens.size(1), -1).transpose(0, 1)
```

gives the linting error:

```
error: "Tensor" has no attribute "contiguous"; maybe "is_contiguous"?
```

## To Reproduce

Any use of `Tensor.contiguous` will produce this when linted with MyPy

## Expected behavior

No error should be reported

## Environment

PyTorch Version (e.g., 1.0): 1.1.0
OS (e.g., Linux): MacOS
How you installed PyTorch (conda, pip, source): conda
Build command you used (if compiling from source): N/A
Python version: 3.6
CUDA/cuDNN version: N/A
GPU models and configuration: None
Any other relevant information: None

**Comment by ezyang** [comment]
`contiguous` is marked `SKIP_PYTHON_BINDINGS` so it needs to get a handwritten declaration in `unsorted_function_hints.update`. @sdraper-CS do you think you could submit a patch? Add me as reviewer.

**Comment by sdraper-CS** [comment]
@ezyang  I would, but it seems someone beat me to it!  Next time I'll construct a pull request directly if the fix is obvious.  Thanks for the prompt update though

**Comment by shihongzhi** [comment]
@sdraper-CS   I seen this issue,  then fixed this bug last week. Thank you for your bug report.
