### ISSUE TITLE
SparseTensor multiplication with 1D vector

### ISSUE THREAD

**Issue by ryan112358** [pytorch/pytorch#21266]
## 🐛 Bug

Not sure if this should be a bug or a feature, but sparse tensors can only be multiplied with a 2D dense tensors, not 1D ones.  This is inconsistent with the the ordinary tensor multiplication, as well as numpy and scipy multiplication.

## To Reproduce

>>> i = torch.LongTensor([[0, 1, 1],
                          [2, 0, 2]])
>>> v = torch.FloatTensor([3, 4, 5])
>>> A = torch.sparse.FloatTensor(i, v, torch.Size([2,3]))
>>> x = torch.ones(3)
>>> A @ x[:,None] # this works
>>> A @ x # this doesn't work, but should

## Expected behavior

For a m x n sparse tensor A and a n-length dense tensor x, A @ x should give a m-length dense tensor.

**Comment by ezyang** [comment]
Should be simple enough to fix. I'll be happy enough to review a patch that does so. Don't forget to add tests.

**Comment by ryan112358** [comment]
I'd be happy to give it a shot, but am a bit new to PyTorch and am actually having trouble finding the implementation of __matmul__ for sparse tensors in the source... would it require writing C++ code?

**Comment by zou3519** [comment]
`__matmul__` calls https://github.com/pytorch/pytorch/blob/87690d2b77d7f61e0939f074ca9b128e97a3c23e/aten/src/ATen/native/LinearAlgebra.cpp#L338 which then should call a sparse-specific matrix multiply function somewhere down the line. yes, there is c++ code involved.
