### ISSUE TITLE
NameError: name 'long' is not defined

### ISSUE THREAD

**Issue by dthboyd** [pytorch/pytorch#2127]
show(make_grid(imglist, padding=100))
NameError                                 Traceback (most recent call last)
<ipython-input-107-e27809616e9d> in <module>()
----> 1 show(make_grid(imglist, padding=100))
      2 

//anaconda/lib/python3.5/site-packages/torchvision-0.1.8-py3.5.egg/torchvision/utils.py in make_grid(tensor, nrow, padding, normalize, range, scale_each)
     26         tensorlist = tensor
     27         numImages = len(tensorlist)
---> 28         size = torch.Size(torch.Size([long(numImages)]) + tensorlist[0].size())
     29         tensor = tensorlist[0].new(size)
     30         for i in irange(numImages):

NameError: name 'long' is not defined

**Comment by soumith** [comment]
dup of https://github.com/pytorch/vision/issues/202
