### ISSUE TITLE
Floating inference time on NVIDIA Jetson Nano

### ISSUE THREAD

**Issue by banderlog** [pytorch/pytorch#21286]
## 🐛 Bug

We have custom network which is based on yolov3-tiny model implemented in `pytorch`. We run it on Jetson Nano, without any problems, except that we had jumping FPS -- from 7 to 30 in some kind of cycle. It was suspicious, thus I tested it inference speed in `ipython3` using `%timeit` and got pretty strange results which corresponds to what we have seen on video processing:

```python
    In [54]: %timeit -n1 -r1 pred, _ = model(img2)
    23.9 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

    In [55]: %timeit -n1 -r2 pred, _ = model(img2)
    18.5 ms ± 4.15 ms per loop (mean ± std. dev. of 2 runs, 1 loop each)

    In [56]: %timeit -n1 -r5 pred, _ = model(img2)
    15.9 ms ± 3.53 ms per loop (mean ± std. dev. of 5 runs, 1 loop each)

    In [57]: %timeit -n1 -r10 pred, _ = model(img2)
    15.6 ms ± 2.45 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)

    In [58]: %timeit -n1 -r20 pred, _ = model(img2)
    The slowest run took 4.69 times longer than the fastest. This could mean that an intermediate result is being cached.
    28.6 ms ± 17.1 ms per loop (mean ± std. dev. of 20 runs, 1 loop each)

    In [59]: %timeit -n1 -r30 pred, _ = model(img2)
    The slowest run took 4.60 times longer than the fastest. This could mean that an intermediate result is being cached.
    35 ms ± 17.4 ms per loop (mean ± std. dev. of 30 runs, 1 loop each)

    In [60]: %timeit -n1 -r40 pred, _ = model(img2)
    38.7 ms ± 16 ms per loop (mean ± std. dev. of 40 runs, 1 loop each)

    In [61]: %timeit -n1 -r50 pred, _ = model(img2)
    40.8 ms ± 14.9 ms per loop (mean ± std. dev. of 50 runs, 1 loop each)

    In [62]: %timeit -n1 -r75 pred, _ = model(img2)
    The slowest run took 5.96 times longer than the fastest. This could mean that an intermediate result is being cached.
    43.5 ms ± 17.1 ms per loop (mean ± std. dev. of 75 runs, 1 loop each)

    In [63]: %timeit -n1 -r200 pred, _ = model(img2)
    The slowest run took 5.82 times longer than the fastest. This could mean that an intermediate result is being cached.
    47.5 ms ± 10.7 ms per loop (mean ± std. dev. of 200 runs, 1 loop each)

    In [64]: %timeit -n1 -r500 pred, _ = model(img2)
    The slowest run took 5.86 times longer than the fastest. This could mean that an intermediate result is being cached.
    48.7 ms ± 9.01 ms per loop (mean ± std. dev. of 500 runs, 1 loop each)
```

This also applies to standard `pytorch` models, i.e MobileNetv2 (see below).

## To Reproduce

```python
    import torch
    import torchvision.models as models
    import numpy as np

    device = torch.device('cuda:0')

    mobilenet = models.mobilenet_v2(pretrained=True)
    mobilenet.to(device)

    # create random image 
    tmp = (np.random.standard_normal([1, 3, 416, 416]) * 255).astype(np.uint8)
    img = torch.from_numpy(tmp.astype(np.float32)).to(device)

    outs = mobilenet(img)


    %timeit -n1 -r1 out = mobilenet(img)
    >> 40.9 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

    %timeit -n1 -r2 out = mobilenet(img)
    >> 40.5 ms ± 850 µs per loop (mean ± std. dev. of 2 runs, 1 loop each)

    %timeit -n1 -r10 out = mobilenet(img)
    >> 82.4 ms ± 32.8 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)

    %timeit -n1 -r20 out = mobilenet(img)
    >> The slowest run took 10.94 times longer than the fastest. This could mean that an intermediate result is being cached.
    95.8 ms ± 34.6 ms per loop (mean ± std. dev. of 20 runs, 1 loop each)
```

## Expected behavior

Deterministic inference time, as if you run above code on GeForce 1080ti.

```python
# Output of above code on GeForce 1080ti
%timeit -n1 -r1 out = mobilenet(img)
>> 12 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

%timeit -n1 -r10 out = mobilenet(img)
>> 10.7 ms ± 1.7 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)

%timeit -n1 -r20 out = mobilenet(img)
>> 10.5 ms ± 2.04 ms per loop (mean ± std. dev. of 20 runs, 1 loop each)

%timeit -n1 -r100 out = mobilenet(img)
>> 9.59 ms ± 743 µs per loop (mean ± std. dev. of 100 runs, 1 loop each)

%timeit -n1 -r1000 out = mobilenet(img)
>> 9.51 ms ± 615 µs per loop (mean ± std. dev. of 1000 runs, 1 loop each)
```

### Jetson Nano

PyTorch version: 1.0.0a0+bb15580
Is debug build: No
CUDA used to build PyTorch: 10.0.117

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/aarch64-linux-gnu/libcudnn.so.7.3.1

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.0.0a0+bb15580
[pip3] torchvision==0.3.0a0+3d56103
[conda] Could not collect

Also tried (with same results):

- PyTorch version: 1.0.0a0+bb15580
- PyTorch version: 1.1.0a0+b457266
- PyTorch version: 1.1.0a0+862aff6

### PC with GeForce1080ti

PyTorch version: 1.2.0.dev20190530
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.56
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip3] numpy==1.16.1
[pip3] torch-nightly==1.2.0.dev20190530
[pip3] torchvision-nightly==0.2.3
[conda] Could not collect

Also tried (with same result):
- PyTorch version: 1.1.0 with torchvision-0.3.0

## Additional context

Also I asked this question to NVIDIA developers: <https://devtalk.nvidia.com/default/topic/1054847/jetson-nano/strange-jumping-results-on-fps-and-inference-time/>

**Comment by soumith** [comment]
what you need to timeit is:
```
torch.cuda.synchronize(); pred, _ = model(img2); torch.cuda.synchronize(); 
```

otherwise you just get wrong timings all over the place because of CUDA API's asynchronous nature.

**Comment by banderlog** [comment]
@soumith many thanks, it solved `%timeit` floating, may I conclude that it is a proper way to measure theoretical maximum of network inference speed?

But I still unable to understand why I have so different behavior on Jetson Nano and GeForce 1080ti, they are both have same API, are they?

**Comment by colesbury** [comment]
Yes, if you are timing GPU you should use `torch.cuda.synchronize()`. You need it on both Jetson and the GeForce card. Otherwise you might only be measuring the time to enqueue the operations on the GPU and not the time to actually execute them.

Jetson and GeForce 1080ti have the same API, but different CPUs and different number of CUDA cores. Both of these affect timing. (Just because the 1080 ti numbers seemed stable doesn't mean they were accurate).

**Comment by banderlog** [comment]
Grand merci, @colesbury
