### ISSUE TITLE
torch.topk _demands_ a dimension if `largest` is specified

### ISSUE THREAD

**Issue by bnsh** [pytorch/pytorch#2131]
Hi..

I think this is a bug:

```
data = torch.randn(5,10)
srtd, indices = torch.sort(data) # This is fine.

srtd, indices = torch.sort(data, 1, descending=False) # This is also fine.
srtd, indices = torch.sort(data, 1, descending=True) # This is also fine.

# But, these both fail:
srtd, indices = torch.sort(data, descending=False) # This fails
srtd, indices = torch.sort(data, descending=True) # This fails
```

So, it doesn't matter if descending is True _or_ False, just specifying it explicitly _requires_ dimension to be specified.. It would be better (I think) if descending could be specified alone..

**Comment by vadimkantorov** [comment]
Same issue for `topk` if `largest = False` is used

**Comment by soumith** [comment]
sort was fixed in https://github.com/pytorch/pytorch/pull/2329

topk is still a problem.
