### ISSUE TITLE
Recurrent issue: using `torch.ge` etc, instead of `nn.relu`

### ISSUE THREAD

**Issue by hughperkins** [pytorch/pytorch#2132]
Recurrent issue: using `torch.ge` etc, instead of `nn.relu`.  eg:
- https://discuss.pytorch.org/t/torch-ge-triggers-there-are-no-graph-nodes-that-require-computing-gradients-in-loss-function/4960
- https://discuss.pytorch.org/t/how-to-make-the-parameter-of-torch-nn-threshold-learnable/4729
- probably others...

Seems like maybe `torch.ge` should wrap `nn.relu`, or somehow use it, if the inputs are `Variable`s perhaps?

(Note that i'm not intending to fix this; just flagging it for now, since comes up a lot)

Edit: well... since these calls actually go via `Variable` wrappers (I think?), it seems like `Variable.ge` etc could interecept these calls, and send them to `.Threshold` etc?

**Comment by apaszke** [comment]
I think it's a bug that is fixed in master, but not in 0.12 that most people use. Can you please verify that?

**Comment by hughperkins** [comment]
Oh, nice! :-)
