### ISSUE TITLE
[Test] Allowing import Testcase for Unit testing Custom Autograd Functions

### ISSUE THREAD

**Issue by lcetinsoy** [pytorch/pytorch#2133]
Hi ! 

When developing custom Autograd Function one cannot use default unittest.TestCase.assertEqual functions to check for equality between tensors. 

Therefore it would be nice to be able to use your TestCase class by adding and __init__ file in the folder or to move the common file elsewhere

Kind regards

**Comment by apaszke** [comment]
It should be quite straightforward to code such function as a one-liner:
```python
def assertTensorEqual(a, b, tolerance=1e-4):
    return a.sub(b).abs().max() < tolerance
```

**Comment by lcetinsoy** [comment]
Thank you for your answer, I could indeed have made up one myself ! 
Nevertheless, since the TestCase class exists, I think it would be nice to be able to import it : no need to c/c it between projects. And the TestCase class handles other datatypes such as sparse tensor. Lastly by documenting it, it could help promote software quality and unit testing among the scientific community which would be not bad. But maybe I am nitpicking : ) 
So thank you again for your answer and you can close my issue if I could not convince you : )

**Comment by colesbury** [comment]
It's been ~2.5 years so I don't think we're likely to expose this at this point.

[`torch.autograd.gradcheck`](https://pytorch.org/docs/stable/autograd.html#torch.autograd.gradcheck) is a good tool for testing autograd functions. I don't remember if that existed at the time this issue was filed.
