### ISSUE TITLE
Make DDP failure recoverable

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#21344]
@kuttas @pietern and I had a discussion on how to make DDP failure recoverable. The process involves the following steps:

```python
m = SomeModel()
dist.init_process_group()
ddp = DistributedDataParallel(m)
# got error
dist.destroy_process_group()
dist.init_process_group()
del ddp
ddp = DistributedDataParallel(m)
```

This does not work in today's DDP. Currently, to get better performance, DDP assigns the [original module](https://github.com/pytorch/pytorch/blob/fa4ca4e70e98fbe944d1435929ea4fd17c7bed7d/torch/nn/parallel/distributed.py#L316) to the first module replica instead of creating a new one. Then, it creates a new `Reducer` to [add post hooks](https://github.com/pytorch/pytorch/blob/fa4ca4e70e98fbe944d1435929ea4fd17c7bed7d/torch/csrc/distributed/c10d/reducer.cpp#L108-L112) to sync params. However, because every reconstructed DDP instance wraps the same original module, all their reducers will add hooks to the same set of variables. Hence, after 10 recoveries, each param (variable) in the original module will have 11 hooks introduced by 11 different reducers, where only the last one is still alive. We thought about several potential solutions:

#### Solution 1: Force Module Replication

Force DDP to create new module replicas instead of using the original module. In this way, those variables in the replicas will die together with the DDP instance. But it will make the DDP slower. Maybe make it an option?

#### Solution 2: Delete Hooks in Destructor

I feel the best way would be deleting those hooks from model variables when destructing a `Reducer`, but I didn't find a clean way to do that. The [`add_post_hook`](https://github.com/pytorch/pytorch/blob/fa4ca4e70e98fbe944d1435929ea4fd17c7bed7d/torch/csrc/autograd/function.h#L250) function takes unique parameters, and we can get those hooks through [`post_hooks`](https://github.com/pytorch/pytorch/blob/fa4ca4e70e98fbe944d1435929ea4fd17c7bed7d/torch/csrc/autograd/function.h#L254). Directly looping through the the hooks vector and find the target to delete seems to be too hackish.

#### Solution 3: Create New Variables (?)

Not sure if this can work. Instead of creating replica (as in Solution 1), let DDP create a new variable for every parameter in the original module. All DDP forward and backward pass will use those new variables. I think this won't work if the application only wraps part of the model using DDP, because there will be two disjoint autograd graphs (?)

@soumith @gchanan @ezyang  thoughts?

**Comment by MichaelDylan77** [comment]
I recently posted about this in the discussion form [here](https://discuss.pytorch.org/t/safely-removing-a-module-from-ddp/45753). This issue actually both answers my question and confirms what I suspected was the case when either remove the module, or in this case, trying to redo the DDP wrapping.

**Comment by kuttas** [comment]
@MichaelDylan77  what are you doing to work around it currently? Re-create the inner model and transfer the parameters over?

The usage pattern you have above is similar to the use case I have. I need to be able to re-create the DDP module-wrapper with a new set of worker machines and keep training.

**Comment by MichaelDylan77** [comment]
That's exactly right. I have to re-instantiate the model and copy params. It's a pain right now. It's nice to know someone else has a use case in which they would need to extract the model from DDP 👍.

**Comment by mrshenli** [comment]
## Trying Solution 2

#21534 seems addressed the problem but in quite a dirty way. A better solution might need to satisfy the following requirements:

1. As mentioned by @pietern, the hook deletion function should be implemented in `torch/csrc/autograd/function.h`, as it owns the data. 
2. We should not slow down existing use cases of `add_post_hook` and `post_hooks()`.

I initially thought about using an `OrderedDict` to store named hooks, as what we did for params, buffers, and children in `nn/Module.h`, but that would violate the second requirement.

Another possibility is that, instead of using the default deleter, we create a special deleter for the hook unique ptr in DDP, e.g., `ReducerHookDeleter`, that wraps the default deleter.  The `add_post_hook` and `post_hooks()` APIs would stay the same, then we add one `delete_post_hook<DeleterType>()` API to `torch/csrc/autograd/function.h`, which loops over all post hooks, and only delete the ones with matching deleter type, i.e., `ReducerHookDeleter`. This would be slow, but is OK, as we only need this on failures, where timeout delay will dominate. Any comments?

**Comment by pietern** [comment]
@MichaelDylan77 Could you give the code in #21591 a try and see if it works for you?

**Comment by MichaelDylan77** [comment]
@pietern I’ll test it out this afternoon!

**Comment by MichaelDylan77** [comment]
Everything seems to work fine on my end. No obvious issues. Memory usage looks relatively constant after removing and re-wrapping the model in DDP

**Comment by pietern** [comment]
@MichaelDylan77 Thanks for confirming it works for you!

**Comment by knagrecha** [comment]
Same issue is now coming up for FSDP - but I suspect it'll be a harder fix there due to how FSDP recursively injects itself. Can't just pull it out in this way.
