### ISSUE TITLE
`tanh` doesnt use all cores

### ISSUE THREAD

**Issue by hughperkins** [pytorch/pytorch#2136]
When I run this script:

    import torch

    a = torch.rand(1000, 10000)
    while True:
        print('.')
        a.tanh_()

and then open `htop`, I expect to see all 8 cores running at 100%, but only 4 seem to be running? :

<img width="772" alt="screen shot 2017-07-17 at 9 01 08 am" src="https://user-images.githubusercontent.com/123560/28297475-263370f0-6b3c-11e7-80c1-4099260abf01.png">

In addition, those cores that are running, are only running at ~30-40%.

(Note that I'm not submitting a fix for this, just flagging it)

**Comment by jekbradbury** [comment]
What happens when you fiddle around with the pertinent environment variables (some subset of `OPENBLAS_NUM_THREADS`, `MKL_NUM_THREADS`, and `OPENMP_NUM_THREADS`)?

**Comment by hughperkins** [comment]
I think this should be handled automatically really?  At least, I dont see anything in any of the doc I've read suggesting one needs to do this.  So, either the doc needs to be updated, or else this should be handled automatically, I reckon.

**Comment by hughperkins** [comment]
That said, with `MKL_NUM_THREADS=8`, no change:
<img width="765" alt="screen shot 2017-07-17 at 10 24 40 pm" src="https://user-images.githubusercontent.com/123560/28297984-c7d19dae-6b3e-11e7-8b02-2521bf9239af.png">

`OPENBLAS_NUM_THREADS=8 MKL_NUM_THREADS=8 OPENMP_NUM_THREADS=8 python test_tanh.py`: no change:

<img width="785" alt="screen shot 2017-07-17 at 10 25 37 pm" src="https://user-images.githubusercontent.com/123560/28298012-e9d7551a-6b3e-11e7-817f-f61aede6d384.png">

**Comment by hughperkins** [comment]
(tanh shouldnt be using blas? I would think it uses some combination of SSE and OpenMP?)

**Comment by jekbradbury** [comment]
Oh of course, sorry. Yeah, this is a good question then!

**Comment by apaszke** [comment]
It seems that Tanh doesn't use OpenMP at all. It calls into TH, and it uses `TH_TENSOR_APPLY_2` which is single-threaded. TH could use some multi-core optimizations, but we don't have enough hands to do it right now.

We could provide some guidance if anyone wants to take a stab. We already have macros that extend `TH_TENSOR_APPLY` to make use of all cores in the contiguous case, so at least this improvement should be easy to add.

**Comment by ruotianluo** [comment]
I submitted a PR, check if it looks like what's expected. @apaszke

**Comment by fmassa** [comment]
If one wants to use OMP on `TH_TENSOR_APPLY2`, one could look into improving on top of https://github.com/torch/torch7/pull/395 . But I think that having better support for AVX/SSE would be best.

**Comment by weiyangfb** [comment]
Closing since this has been fixed vix https://github.com/pytorch/pytorch/pull/2792
