### ISSUE TITLE
[Quick fix] Add CUDA support for arange

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#2139]
Since https://github.com/pytorch/pytorch/commit/fb32164a72004e63ebfe1f9ca8366ff12f8fbec2 , `arange` now has a dedicated C implementation in TH that uses `range` internally, instead of relying on cwrap to perform the range modification.
But even though [`range` has a CUDA implementation](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/generic/THCTensorMath.cu#L435-L450), there was no THC implementation for `arange`. It would roughly consist of almost the exact same code as `arange` for the CPU, and we should also modify the cwrap to work on both [CPU and GPU](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/methods/Tensor.cwrap#L692)

**Comment by fmassa** [comment]
cc @alykhantejani

**Comment by alykhantejani** [comment]
I can take this one

**Comment by fmassa** [comment]
This would also fix https://github.com/pytorch/pytorch/issues/1925 
Also, we can enable CUDA support for `range` as well (even though it's deprecated)
