### ISSUE TITLE
Type mismatch of aten::mul backward

### ISSUE THREAD

**Issue by nict-wisdom** [pytorch/pytorch#21408]
## 🐛 Bug

``aten::mul`` accepts ``Double`` as the second argument, but always returns ``Float`` when backwarding.

## To Reproduce

The following reproduces the problem.

```python
import torch

def f(x, y):
    d = y.sum()
    return x * d

x = torch.randn(3,3, requires_grad=True)
y = torch.randn(3,3, requires_grad=True, dtype=torch.float64)
tf = torch.jit.trace(f, (x, y))
z = tf(x, y)
z.backward(torch.randn_like(x))
```

This gives you an error:
```
Traceback (most recent call last):
  File "mul_type.py", line 11, in <module>
    z.backward(torch.randn_like(x))
  File "/home01/mtnk/miniconda3/envs/PTv1.2.0.dev20190605/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home01/mtnk/miniconda3/envs/PTv1.2.0.dev20190605/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function MulBackward0 returned an invalid gradient at index 1 - expected type torch.DoubleTensor but got torch.FloatTensor
```

The graph of the traced module was: 
```
graph(%x : Float(3, 3),
      %y : Double(3, 3)):
  %d : Double() = aten::sum(%y)
  %3 : Float(3, 3) = aten::mul(%x, %d)
  return (%3)
```

## Expected behavior

I think aten::mul should return a Double value while running backward if the second argument of forward is Double.

## Environment

PyTorch version: 1.2.0.dev20190605
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux release 7.5.1804 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 3.14.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration:
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 396.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.2.0.dev20190605
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch-nightly           1.2.0.dev20190605 py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch

**Comment by eellison** [comment]
Thanks again for the minimial issue & repro!

**Comment by Chillee** [comment]
Is this really a JIT issue? It still fails even with the JIT stuff removed
```python
def f(x, y):
    d = y.sum()
    return x * d

x = torch.randn(3,3, requires_grad=True)
y = torch.randn(3,3, requires_grad=True, dtype=torch.float64)
z = f(x, y)
z.backward(torch.randn_like(x))
```
this results in the same error `RuntimeError: Function MulBackward0 returned an invalid gradient at index 1 - expected type torch.DoubleTensor but got torch.FloatTensor`

**Comment by eellison** [comment]
Closing per @Chillee comment. Reopen if you think it is still relevant.
