### ISSUE TITLE
[onnx] convert pytorch to onnx. (pytorch nightly 1.1.0)

### ISSUE THREAD

**Issue by TTMRonald** [pytorch/pytorch#21409]
## ❓ Questions and Help

I want to convert pytorch to onnx in pytorch nightly 1.1.0. The input type is ImageList. The outputput type is BoxList. 
The convert code is
`
dummy_input = torch.autograd.Variable(torch.randn(1, 3, 640, 800).cuda())
torch.onnx.export(self.model, dummy_input, "convert_models/onnx_model.onnx")
`
But I meet an error.

> RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got BoxList.

Thanks.

**Comment by cpuhrsch** [comment]
Helo @TTMRonald, could you provide more details including a minimal and reproducible code snippet? Also note that we [don't use Variable anymore](https://github.com/pytorch/pytorch/wiki/Breaking-Changes-from-Variable-and-Tensor-merge).

**Comment by TTMRonald** [comment]
@cpuhrsch Hi, I try convert FCOS model to onnx. The self.model output type is BoxList. I add the convert code after the "predictions = self.model(image_list)".
 
https://github.com/tianzhi0549/FCOS/blob/fdfc912474e2fff863b8d2dadbba11567fafd758/demo/predictor.py#L205

The convert code is
`
dummy_input = torch.autograd.Variable(torch.randn(1, 3, 640, 800).cuda()) torch.onnx.export(self.model, dummy_input, "convert_models/onnx_model.onnx")
`

The code have an error, when the code runing in the "torch.onnx.export()"
The error is

> RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got BoxList.

Is there any way to solve the compatibility problem between the the model output type (BoxList) and type torch.onnx.expor requested?
Thanks.

**Comment by houseroad** [comment]
Can you use plan tensors here, and wrapper it up within the model? like the warning mentioned... the input/output of the model can only support tuples, lists and tensors.

**Comment by garymm** [comment]
@TTMRonald if you wrap the model in another class that unpacks the BoxList into just tensors then you should be able to export that wrapped model.
ONNX will never support arbitrary python types as inputs / outputs.
