### ISSUE TITLE
torch.bilinear not in documentation

### ISSUE THREAD

**Issue by cdancette** [pytorch/pytorch#21413]
## 📚 Documentation
torch.bilinear is not in the documentation.

`torch.nn.functional.bilinear` is in the doc, but there isn't any information about it, and looking at the source, it calls torch.bilinear.

**Comment by soumith** [comment]
this is expected. it's a C-side function, that actually should've been exposed under torch._C.nn.bilinear namespace, but is exposed as torch.bilinear for legacy reasons. One should not document or use it directly.

**Comment by soumith** [comment]
the main function you want to use for any and all interpolations is `torch.nn.functional.interpolate`
