### ISSUE TITLE
NCCL process groups don't support `.group_ranks()`

### ISSUE THREAD

**Issue by slayton58** [pytorch/pytorch#21415]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by fmassa** [comment]
I don't have much background on `distributed`, but from a quick look it seems that this might be the case for both NCCL and GLOO
https://github.com/pytorch/pytorch/blob/2573e695b085e98b619c74eb9318b5a428aef8ac/torch/distributed/distributed_c10d.py#L467-L499

@pietern @mrshenli is this something we should be fixing?

**Comment by mrshenli** [comment]
@fmassa We can expose a `pg.group_ranks()` API in Python if necessary. @slayton58, could you please share a little more context of your use case? For quick unblock, you can try the following:

```python
import torch.distributed.distributed_c10d as c10d
list(c10d._pg_group_ranks[pg].values())
```

**Comment by slayton58** [comment]
@mrshenli My use-case is from an abstraction standpoint -- I want to pass the minimum amount of information around, an especially not repeated information.

In a more concrete sense, I have an initialisation chunk of code that sets up all the process groups, that are then passed around. In one case I need to do a splitting based on how many ranks are in the passed process group - the easiest way imo to do this would be to query the process group rather than move additional data around. Your WAR should be ok, but it feels strange that the process group itself can't provide this directly.

**Comment by mrshenli** [comment]
@slayton58 thanks for sharing the context, and it makes sense to me. @pietern If this looks OK to you as well, I will create a PR to expose the API.

**Comment by pietern** [comment]
@slayton58 The `group_ranks` function was only used in `ProcessGroupMPI` to provide a mapping from global ranks to local ranks for subgroups. In #14809 I made this obsolete by only allowing construction of the `ProcessGroupMPI` if you know which ranks participate in it. This means full symmetry between the underlying process group implementations and doesn't leak any details about rank mapping into the process group itself. 

W.r.t. your issue, would it be enough to use the rank and size of the subgroups directly, or do you strictly need the corresponding global ranks?

**Comment by slayton58** [comment]
In my use-case I don't strictly need the global ranks (more I actually just need to know how many ranks are in the subgroup) -- I understand why you might want to abstract out exactly what's happening under the hood :)

**Comment by pietern** [comment]
In that case you should be able to use `torch.distributed.get_world_size(group=pg)` directly.

The `pg` is still to be considered an abstract object. In reality it's an instance of the C++ `c10d::ProcessGroup` class, and you can also call `pg.size` to get the same information. This is not considered public API so please prefer going through the `torch.distributed` function instead.

**Comment by pietern** [comment]
@slayton58 Does this work for you?

**Comment by slayton58** [comment]
Yes, this works for me -- sorry, I didn't think further input was required :)

**Comment by pietern** [comment]
@slayton58 Thanks! Asking so I can close the issue :)
