### ISSUE TITLE
Where is the algorithm for conv being selected?

### ISSUE THREAD

**Issue by snippler** [pytorch/pytorch#21456]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Hi,
I would like to deploy PyTorch on some specific HW. Problem is it is very slow if the algorithms for conv are not changed. I'd like to rely to some specific algorithms - optimized for the HW. My problem is I cannot figure out where in PyTorch code of conv2d for example the actual algorithm is selected.
Thank you.

**Comment by fmassa** [comment]
Here is where the different algorithms for convolution are selected https://github.com/pytorch/pytorch/blob/12528990f8c56deb7ce1c699e6da63d82c115968/aten/src/ATen/native/Convolution.cpp#L403-L477

Also, note that we use GitHub issues for tracking bugs and feature requests. Questions are better suited to the discussion forums https://discuss.pytorch.org

**Comment by snippler** [comment]
Thank you.

**Comment by snippler** [comment]
I have a follow-up question: do I read correctly that the default case for CPU is **at::mkldnn_convolution**? So if I have an ARM processor I simply have to replace this line by an ARM convolution?

**Comment by fmassa** [comment]
If your system doesn't have MKLDNN supported, it will dispatch to our custom implementation of convolution which is based on `im2col + matmul` https://github.com/pytorch/pytorch/blob/12528990f8c56deb7ce1c699e6da63d82c115968/aten/src/ATen/native/Convolution.cpp#L464

**Comment by snippler** [comment]
I see, I thought, this was dws conv, now I see it's a different kind of "group"

Is there something for ARM processors inside Caffe2 that could be used here?

**Comment by fmassa** [comment]
maybe NNPack, but I'm not sure.

**Comment by snippler** [comment]
Is there any way of knowing which function my script is actually using, that is if it is using nnpack for instance?

**Comment by fmassa** [comment]
Run your code with autograd profiler, it will show which kernel was used

**Comment by snippler** [comment]
Actually I found a very easy way now:

y = net(x)
print(y.grad_fn)

Outputs: <ThnnConv2DBackward object at 0x70d75c10>

So I am using THNN instead of NNPACK. But how to force to use NNPACK?

**Comment by fmassa** [comment]
@snippler I don't know, you should probably open a different issue for that
