### ISSUE TITLE
RuntimeError when trying to reuse a buffer

### ISSUE THREAD

**Issue by ifedan** [pytorch/pytorch#21469]
## 🐛 Bug

The code snippet below throws error. I'm trying to see if I could reuse a buffer.

## To Reproduce

```
b = torch.randn(3, requires_grad=True)
c = torch.zeros(3) 
c[[1,2]] = b[[1,1]]
c.sum().backward() # ok
c.sum().backward() # fail

RuntimeError: ntensor >= 3 INTERNAL ASSERT FAILED at caffe2/aten/src/ATen/native/cpu/IndexKernel.cpp:51, please report a bug to PyTorch. 
```

**Comment by gchanan** [comment]
My expectation is that you would have gotten an error about reusing grad buffers.

**Comment by fmassa** [comment]
Don't we need to pass `retain_graph=True` to backward if we want to compute the derivative again?

This solves the error for me:

```python
b = torch.randn(3, requires_grad=True)
c = torch.zeros(3) 
c[[1,2]] = b[[1,1]]
c.sum().backward(retain_graph=True) # ok
c.sum().backward() # ok
```

But I believe we should have raised a different error here in this case, like in the following example

```python
b = torch.randn(3, requires_grad=True)
c = b * 2
c.sum().backward() # ok
c.sum().backward() # fail
```
with the error
```
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
```

**Comment by ifedan** [comment]
> Don't we need to pass `retain_graph=True` to backward if we want to compute the derivative again?
> 
> This solves the error for me:
> 
> ```python
> b = torch.randn(3, requires_grad=True)
> c = torch.zeros(3) 
> c[[1,2]] = b[[1,1]]
> c.sum().backward(retain_graph=True) # ok
> c.sum().backward() # ok
> ```
> 
> But I believe we should have raised a different error here in this case, like in the following example
> 
> ```python
> b = torch.randn(3, requires_grad=True)
> c = b * 2
> c.sum().backward() # ok
> c.sum().backward() # fail
> ```
> 
> with the error
> 
> ```
> RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
> ```

Agree

**Comment by kittipatv** [comment]
I posted the original error internally, which was:

```
b = torch.randn(3, requires_grad=True)
c = torch.zeros(3) 
c[[1,2]] = b[[1,1]]
c.sum().backward() # ok
c[[1,2]] = b[[1,1]]
c.sum().backward() # fail
```

It shouldn't need the previous graph in this case.

**Comment by ifedan** [comment]
Working on fix: https://github.com/pytorch/pytorch/pull/21533

**Comment by ifedan** [comment]
Fixed
