### ISSUE TITLE
No continuous integration coverage for Python 2 CUDA

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#21467]
We appear to have no CI configurations that run tests on Python 2 CUDA. This is a big problem; c.f. #21466.

**Comment by ezyang** [comment]
This might be high priority, but I'm deprioritizing it because it hasn't been shown that we keep breaking this.

**Comment by clee2000** [comment]
Closing because we no longer support Python 2 and Python 2 has been sunsetted
