### ISSUE TITLE
JIT torch.stft calls aten::stft which throws error

### ISSUE THREAD

**Issue by jamarshon** [pytorch/pytorch#21478]
## JIT torch.stft calls aten::stft which throws error

When I call torch.stft or torch.functional.stft, JIT tries to call aten::stft.

The former has the [signature](https://pytorch.org/docs/stable/_modules/torch/functional.html#stft):
`
type: (Tensor, int, Optional[int], Optional[int], Optional[Tensor], bool, str, bool, bool) -> Tensor
`

and the latter has the [signature](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/TensorMethods.h#L587):
`
type: (Tensor, int, Optional[int], Optional[int], Optional[Tensor], bool, bool) -> Tensor:
`

which causes an error due to the mismatching argument types.

Example:
```
@torch.jit.script
def f():
  torch.stft(...)
```

## Stack Trace
```
  File "/home/travis/build/jamarshon/audio/torchaudio/functional.py", line 103, in <module>
    @torch.jit.script
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1050, in script
    fn = torch._C._jit_script_compile(ast, _rcb, get_default_args(obj))
RuntimeError: 
arguments for call are not valid:
  
  for operator aten::stft(Tensor self, int n_fft, int? hop_length=<default>, int? win_length=<default>, Tensor? window=<default>, bool normalized=<default>, bool onesided=<default>) -> Tensor:
  expected a value of type 'bool' for argument 'onesided' but instead found type 'str'.
  at /home/travis/build/jamarshon/audio/torchaudio/functional.py:134:31
      """
      assert sig.dim() == 2
  
      if pad > 0:
          # TODO add "with torch.no_grad():" back when JIT supports it
          sig = torch.nn.functional.pad(sig, (pad, pad), "constant")
  
      # default values are consistent with librosa.core.spectrum._spectrogram
      spec_f = torch.stft(sig, n_fft, hop, ws, window,
                          True, 'reflect', False, True).transpose(1, 2)
                                ~ <--- HERE
  
      if normalize:
          spec_f /= window.pow(2).sum().sqrt()
      spec_f = spec_f.pow(power).sum(-1)  # get power of "complex" tensor (c, l, n_fft)
      return spec_f
```

## Expected behavior

The torch.stft function should be called not the aten one.

## Environment
PyTorch version: 1.2.0a0+1252899
Is debug build: Yes
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] pytorch-sphinx-theme==0.0.24
[pip] torch==1.2.0a0+1252899
[pip] torchaudio==0.2
[conda] blas                      1.0                         mkl  
[conda] magma-cuda100             2.5.0                         1    pytorch
[conda] mkl                       2019.3                      199  
[conda] mkl-include               2019.3                      199  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     1.2.0a0+1252899           dev_0    <develop>
[conda] torchaudio                0.2                       dev_0    <develop>

**Comment by suo** [comment]
@wanchaol  can you take a look

**Comment by wanchaol** [comment]
I don't know the underlying reason why you need to call `torch.functional.stft`, we did not export the `torch.functional` library to torchscript yet. You will need to call `torch.stft` in JIT and pass all the necessary arguments for it.

**Comment by jamarshon** [comment]
@wanchaol Well it does not work in either case `torch.functional.stft` or `torch.stft`

**Comment by wanchaol** [comment]
@jamarshon I tried the `torch.stft`, it does work for torchscript:

```
import torch

@torch.jit.script
def test_stft(input, n_fft):
    # type: (Tensor, int) -> Tensor
    return torch.stft(input, n_fft)

print(test_stft.graph)

inp = torch.randn(4, 5)
res = test_stft(inp, 4)

print(res)
```

```
graph(%input.1 : Tensor,
      %n_fft.1 : int):
  %11 : bool = prim::Constant[value=1]()
  %10 : bool = prim::Constant[value=0]()
  %9 : Tensor? = prim::Constant()
  %5 : int? = prim::Constant()
  %12 : Tensor = aten::stft(%input.1, %n_fft.1, %5, %5, %9, %10, %11) # /private/home/wanchaol/test.py:6:12
  return (%12)

tensor([[[[-2.2333,  0.0000],
          [-5.4910,  0.0000]],
          ......
```
Can you help providing a minimal example that is not working?

**Comment by jamarshon** [comment]
@wanchaol Here is a small example 
```
import torch

input = torch.rand((1,100))
n_fft = 20
hop_length=None
win_length=None
window=None
center=True
pad_mode='reflect'
normalized=False
onesided=True

output = torch.stft(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided)
print(output.size()) # prints torch.Size([1, 11, 21, 2])


@torch.jit.script
def foo(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided):
	# type: (Tensor, int, Optional[int], Optional[int], Optional[Tensor], bool, str, bool, bool) -> Tensor
	output = torch.stft(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided)
	return output

output = foo(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided)
print(output.size())
```
and the output:
```
torch.Size([1, 11, 21, 2])
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    @torch.jit.script
  File "/Users/jamarshon/Documents/GitHub/pytorch/torch/jit/__init__.py", line 1050, in script
    fn = torch._C._jit_script_compile(ast, _rcb, get_default_args(obj))
RuntimeError: 
arguments for call are not valid:
  
  for operator aten::stft(Tensor self, int n_fft, int? hop_length=<default>, int? win_length=<default>, Tensor? window=<default>, bool normalized=<default>, bool onesided=<default>) -> Tensor:
  expected a value of type 'bool' for argument 'onesided' but instead found type 'str'.
  at test.py:20:76
  @torch.jit.script
  def foo(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided):
  	# type: (Tensor, int, Optional[int], Optional[int], Optional[Tensor], bool, str, bool, bool) -> Tensor
  	output = torch.stft(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided)
                                                                             ~~~~~~~~ <--- HERE
  	return output
for call at:
at test.py:20:11
@torch.jit.script
def foo(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided):
	# type: (Tensor, int, Optional[int], Optional[int], Optional[Tensor], bool, str, bool, bool) -> Tensor
	output = torch.stft(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided)
          ~~~~~~~~~~ <--- HERE
	return output
```

**Comment by wanchaol** [comment]
@jamarshon I digged into this a bit. I noticed that our operator schema for `stft` does not contains `pad_mode` and `center` as documented [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L1853). JIT will only take the schema for ATen and the two additional args that is handled by torch.functional is not exposed to JIT. so that's why you are having that error. 

For workaround, since our new API is there, you can try to use our new API and script the `stft` under `torch.functional`.  in order to pass all arguments

**Comment by jamarshon** [comment]
@wanchaol do you mean use `torch.functional.stft`? because that does not work either

**Comment by eellison** [comment]
Fix in here https://github.com/pytorch/pytorch/pull/33504
