### ISSUE TITLE
Expand(), memory keeps increasing

### ISSUE THREAD

**Issue by IouJenLiu** [pytorch/pytorch#2148]
When I run the following code, the memory usage keeps increasing iteration by iteration.

```
while True:
  a = Variable(torch.FloatTensor(32,16).cuda())  
  r = Variable(torch.FloatTensor(1).cuda())
  c = r.expand(a.size())
```

If I use r.exapnd([32, 16]), memory usage does not increase.
Did I use expand() incorrectly? Does anyone have the same issue?

**Comment by nitishgupta** [comment]
I don't know about the memory issue, but you should instead by using 
`c = r.expand_as(a)`

**Comment by colesbury** [comment]
This is not happening on `master` or `v0.2.0`

(Neither CUDA memory or CPU memory is increasing)
