### ISSUE TITLE
output_device = device_ids[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#2150]
Hi, all:

Sorry about my entry-level question on how to use 
**torch.nn.DataParallel(model).cuda()?**

The code is as:

```
import argparse
import os
import shutil
import time

import torch
import torch.nn as nn
import torch.nn.parallel
import torch.backends.cudnn as cudnn
import torch.optim
import torch.utils.data
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torchvision.models as models


model_names = sorted(name for name in models.__dict__
    if name.islower() and not name.startswith("__")
    and callable(models.__dict__[name]))

model = models.__dict__['resnet18']()

model = torch.nn.DataParallel(model).cuda()
```

And, the final line of the codes failed with the following message:

> File "train.py", line xxx, in <module>
>     model = torch.nn.DataParallel(model).cuda()
>   File "yyy/condaenv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 48, in __init__
>     output_device = device_ids[0]
> IndexError: list index out of range

Can anybody give me a hand?
I'm using a GTX980M under Ubuntu 16.04, with up-to-date anaconda with Python 3.6.1, Pytorch 0.1.12 .

Thank you very much
Pei

**Comment by jekbradbury** [comment]
`nn.DataParallel` requires a list of GPU indexes.

**Comment by jiapei100** [comment]
@jekbradbury 
Thank you for you prompt reply... jekbradbury...

I actually follow the example here [](https://github.com/pytorch/examples/blob/master/imagenet/main.py)

Now, the following line is working properly.
`net = torch.nn.DataParallel(model, device_ids=[0, 1])`
but what's weird is:
`net = torch.nn.DataParallel(model, device_ids=[0])`
went wrong...

Also, according to [](https://github.com/pytorch/examples/blob/master/imagenet/main.py),
**model = torch.nn.DataParallel(model).cuda()**
should be working, but if I add **cuda()** at the back like this:
`net = torch.nn.DataParallel(model, device_ids=[0, 1]).cuda()`
it's wrong again.

Can you please help to explain it with a bit more details?

Thank you...
Pei

**Comment by mangdian** [comment]
@jiapei100  I have run into the same problem. How did you fix this?

**Comment by asaluja** [comment]
I'm getting the same error. @jekbradbury @soumith can we please reopen?
