### ISSUE TITLE
How to disable MKL-DNN 64-bit compilation?

### ISSUE THREAD

**Issue by baqwas** [pytorch/pytorch#21551]
My build from current source on RPi 3B fails because the compilation is selecting the 64-bit option for the Intel MKL-DNN library. Is there an _option/flag_ to disable this selection during the **make** process?

Thanks.

```
-- MIOpen not found. Compiling without MIOpen support
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   621    0   621    0     0   1408      0 --:--:-- --:--:-- --:--:--  1411
100 66.4M  100 66.4M    0     0  8019k      0  0:00:08  0:00:08 --:--:-- 9169k
Downloaded and unpacked Intel(R) MKL small libraries to /home/pi/projects/pytorch/third_party/ideep/mkl-dnn/external
CMake Error at third_party/ideep/mkl-dnn/CMakeLists.txt:59 (message):
  Intel(R) MKL-DNN supports 64 bit platforms only
```

**Comment by xuhdev** [comment]
Could you try

    USE_MKLDNN=0 python setup.py install

**Comment by baqwas** [comment]
The suggestion by xuhdev to disable MDLDNN worked.
Many thanks and kind regards.

**Comment by jinfagang** [comment]
@xuhdev  Why `export USE_MKLDNN=0` not work but `USE_MKLDNN=0 python setup.py install --cmake` can work??


I am totally confused by them..... shouldn't them be same?

**Comment by jinfagang** [comment]
OK, this not work:

```
USE_MKLDNN=0 USE_DISTRIBUTED=0 USE_C10D_GLOO=0 sudo python3 setup.py install --cmake

```

**Comment by xuhdev** [comment]
@jinfagang Have you tried `python setup.py clean` first?

**Comment by jinfagang** [comment]
I runed, and I remove `build`. But somehow I alway hit this ghost:

```
-- Found MKL-DNN: TRUE

```

How could this be?? I totally can not found MKLDNN and I have not it installed at all......  Anyway this will throw an error of `mkl_vsl.h` not found error in the end....

**Comment by jinfagang** [comment]
I have noting to say:

```
pytorch/third_party/ideep/include/ideep/utils.hpp:15:21: fatal error: mkl_vsl.h: No such file or directory
 #include <mkl_vsl.h>
                     ^
compilation terminated.
caffe2/CMakeFiles/torch.dir/build.make:2729: recipe for target 'caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/Version.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/Version.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:5759: recipe for target 'caffe2/CMakeFiles/torch.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/torch.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 321, in build_deps
    cmake=cmake)
  File "//pytorch/tools/build_pytorch_libs.py", line 63, in build_caffe2
    cmake.build(my_env)
  File "/pytorch/tools/setup_helpers/cmake.py", line 330, in build
    self.run(build_args, my_env)
  File "pytorch/tools/setup_helpers/cmake.py", line 143, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '12']' returned non-zero exit status 2
[15:19:45] fagangjin:pytorch git:(master) $ USE_MKLDNN=0 USE_DISTRIBUTED=0 sudo python3 setup.py install --cmake

```

**Comment by jinfagang** [comment]
I have runned clean and remove build folder, can anyone indicates me why this command has no effect???????

**Comment by xuhdev** [comment]
It may be caused by the use of `sudo` here, because some configuration of sudo would drop or only keep some current environment variables. Normally you shouldn't run the build command with `sudo`; but if you have to do so, you can try `sudo -E` to force `sudo` to preserve environment variables.

**Comment by jinfagang** [comment]
@xuhdev  You seems saved my life!!!

But without sudo, I can not install the built pytorch python package, does it generates wheels so that I can install after build? (I tried several times, it broken says permission denied without sudo)
