### ISSUE TITLE
Conv2d Breakdown

### ISSUE THREAD

**Issue by WeiHao97** [pytorch/pytorch#21569]
## ❓ Questions and Help

Hi I am trying to make a breakdown of the overhead of Conv2d operation on both cpu and gpu. Simply, I think I should do this by putting timers around im2col and gemm operations as they are them two main operations in Conv2d?

In the source code, I can trace it back to patialDilatedConvolution.c and SpatialFullDilatedConvolution.c. However, I am confused by the diffrence between THNN_(SpatialDilatedConvolution_updateOutput)()
 and THNN_(SpatialFullDilatedConvolution_updateOutput)(). 

It seems that the former one is what I would like to put timers in for my purpose as that one dose im2col + gemm sequentially?
Thank you for the response and other suggestions you may have.

**Comment by WeiHao97** [comment]
*put timers

**Comment by gheaeckkseqrz** [comment]
**Take it with a pinch of salt as I'm no expert.**

I don't think you'll be able to time the GPU code, as the execution is somewhat asynchronous.
The C code will add a CUDA kernel to the queue and return, you can time the adding operation, but you'll not be able to time the actual operation without performing a synchrosination next (which I expect is gonna be a bit of work).

AFAIK (correct me if I'm wrong) SpatialDilatedConvolution and SpatialFullDilatedConvolution is just a difference in padding. You should get simillar result with both.

If using https://github.com/torch/nn/blob/master/lib/THNN/generic/SpatialDilatedConvolution.c

You should be able to time IM2COL on line 148 and GEMM on line 161.
But take your timing with a pinch of salt too, as adding the timing code may change the way code gets optimised by the compiler and give misleading results.

**Comment by WeiHao97** [comment]
I tried to add printf statement in SpatialDilatedConvolution and run "python setup.py build". However, nothing is get printed while I am applying conv2d to a tensor. Maybe conv2d is using another function? I am really not sure about this. Please help me out.

**Comment by fmassa** [comment]
Depending on the setup, we might dispatch to MKLDNN or CUDNN implementations. Check `Convolution cpp` in the ATen native folder

**Comment by jeffreyksmithjr** [comment]
I read this issue as a question. Please use https://discuss.pytorch.org for questions. Feel free to reopen this issue if I misunderstood.
