### ISSUE TITLE
`torch.arange` output shape 

### ISSUE THREAD

**Issue by ksanjeevan** [pytorch/pytorch#21579]
## 📚 Documentation

As described [here](https://pytorch.org/docs/stable/torch.html#torch.arange) the output size of `torch.arange` is `int((end-start)/step)` (i.e. the floor). But it's the ceiling:

```python
import torch
import numpy as np
def verify_out_shape(start, end, steps): 
    for s in steps: 
        dif = end-start 
        assert torch.arange(start, end, step=s).size(0) == np.ceil(dif/s)

verify_out_shape(1, 400, [0.5, 0.7, 0.3, 1.3])  
verify_out_shape(23, 731, [0.5, 0.7, 0.3, 1.3])  
```

**Comment by umanwizard** [comment]
Yep, the doc seems wrong here. @ksanjeevan Thanks for reporting it.

**Comment by umanwizard** [comment]
Landed a fix to the docs. Closing this out.
