### ISSUE TITLE
[Feature Request] : conditional overall argmax() & overall argmin()

### ISSUE THREAD

**Issue by xiaoyuchhusky** [pytorch/pytorch#21573]
I would like to request one "conditional overall argmax()" function. Like the example below:

let's say we have a tensor Q with shape (4,4,4):

![Snip20190609_3](https://user-images.githubusercontent.com/22250129/59160183-7a6f6800-8aa1-11e9-8707-2195076ba132.png)

then, given a **conditional index vector, [0,1,:]**, we pick out the corresponding part by **Q[0,1,:]**. If we do the argmax() now, it returns "**tensor(2)**". However, I hope there is one "overall argmax()" can return "tensor(6)" instead, which is the corresponding index under the overall flatten Q.view(-1)[6]:

![Snip20190609_4](https://user-images.githubusercontent.com/22250129/59160352-e7cfc880-8aa2-11e9-9510-67484134418f.png)

The function should work for **any arbitrary conditional index vector**. 

Also, this function should be able to receive any number of Q and the corresponding conditional vector, and then return the corresponding conditional overall argmax().

For example, if we have 1000 Q with shape (1000, 4, 4, 4) and 1000 condition index vector, the function should return me a tensor with shape (1000, 1) which is the conditional overall argmax() for each Q.

This function will be very helpful in Reinforcement Learning for the Multi-agent case when we learn a joint-Q-value and select the max one conditioned on certain agent's action.

Thank you!

**Comment by fmassa** [comment]
I'm not sure if I understand it correctly, but this seems similar to computing the argmax over a single dimension, via `argmax(2)`. Or am I missing something?

**Comment by fmassa** [comment]
(With a potential extension of argmax over multiple dimensions)

**Comment by xiaoyuchhusky** [comment]
@fmassa，it is not over single or multiple dimensions. Given a original Q matrix and a conditional arbitrary vector (e.g. [1,:,:]; [3,:,1]), the vector is used to select out the values ( let’s call these values selected_Q) from which we want to find the index of the maximal value, but the index should be under the original Q matrix, not under the selected_Q.

**Comment by fmassa** [comment]
I see. One option is to mask the elements that are not in `Q` with `-inf`, so you can apply `argmax` right away.
