### ISSUE TITLE
Pytorch Dockerfile not building

### ISSUE THREAD

**Issue by lmc5190** [pytorch/pytorch#21578]
## 🐛 Bug

Pytorch Dockerfile not building. Getting error **fatal: Not a git repository (or any of the parent directories): .git**

## To Reproduce

I ran 

> docker build .

  with the Dockerfile for pytorch
[Dockerfile](https://github.com/pytorch/pytorch/blob/master/docker/pytorch/Dockerfile)

Here is the output of running docker build

```
Step 1/13 : FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04
 ---> c963dc0723b7
Step 2/13 : ARG PYTHON_VERSION=3.6
 ---> Using cache
 ---> fe4ceab2399f
Step 3/13 : RUN apt-get update && apt-get install -y --no-install-recommends          build-essential          cmake          git          curl          ca-certificates          libjpeg-dev          libpng-dev &&      rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 03c70406ef3c
Step 4/13 : RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  &&      chmod +x ~/miniconda.sh &&      ~/miniconda.sh -b -p /opt/conda &&      rm ~/miniconda.sh &&      /opt/conda/bin/conda install -y python=$PYTHON_VERSION numpy pyyaml scipy ipython mkl mkl-include ninja cython typing &&      /opt/conda/bin/conda install -y -c pytorch magma-cuda100 &&      /opt/conda/bin/conda clean -ya
 ---> Using cache
 ---> 8ee07cba5f55
Step 5/13 : ENV PATH /opt/conda/bin:$PATH
 ---> Using cache
 ---> 98684eaec1b3
Step 6/13 : WORKDIR /opt/pytorch
 ---> Using cache
 ---> 5a095d4a5e62
Step 7/13 : COPY . .
 ---> a04c9d96430b
Step 8/13 : RUN git submodule update --init --recursive
 ---> Running in 85ae5ad0beb1
**fatal: Not a git repository (or any of the parent directories): .git**
```

## Expected behavior

I expected it to build since the image on dockerhub works.

## Environment

CentOS 7. Docker CE 18.09.6. Since i'm building a dockerfile, i think these are the only relevant environment pieces.

## Additional context

None

**Comment by xuhdev** [comment]
Did you follow [README](https://github.com/pytorch/pytorch#docker-image)?

> Build from pytorch repo directory as docker needs to copy git repo into docker filesystem while building the image.

>     docker build -t pytorch -f docker/pytorch/Dockerfile .

**Comment by lmc5190** [comment]
Nope! That would be my issue. Thanks!

**Comment by alexlana** [comment]
I had the same error, even building from repository folder. In my case, when I downloaded a zip file it don't have a .git folder inside. When I opened it in GitHub Desktop the folder .git is there and all works.
