### ISSUE TITLE
Using Ninja instead of Make results in inability to find correct headers when building from source on Linux

### ISSUE THREAD

**Issue by HenryJia** [pytorch/pytorch#21574]
## 🐛 Bug

Build from source fails on Linux systems and results in either #20005 or #13061 if ninja is present on the system and USE_NINJA=OFF is not passed to setup.py

## To Reproduce

1. Install ninja
2. python setup.py install

## Expected behavior

If USE_NINJA=OFF is not passed, cmake will default to using ninja when it is installed, causing either #13061 or #20005. Otherwise the build completes normally.

## Environment

```
Collecting environment information...
PyTorch version: 1.2.0a0+37ab35c
Is debug build: No
CUDA used to build PyTorch: 10.1.105

OS: Arch Linux
GCC version: (GCC) 8.3.0
CMake version: version 3.14.5

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce RTX 2070

Nvidia driver version: 430.14
cuDNN version: /usr/lib/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] pytorch-ignite==0.1.2
[pip3] torch==1.2.0a0+37ab35c
[pip3] torchaudio==0.2
[pip3] torchfile==0.1.0
[pip3] torchvision==0.2.1
[conda] Could not collect (not installed)
```

From what I observed, it seems to be some issue with using Ninja instead of Make on linux can result in files failing to find the correct include directory for caffe2, resulting it including the placeholder headers in caffe2/ instead of the generated headers in build/caffe2

**Comment by xuhdev** [comment]
Does everything work if you simply add `USE_NINJA=OFF`? I have no problem using Ninja on Linux.

I personally think the unpredictable errors are at least partially caused by inconsistent system environment check between the python setup scripts (e.g., `setup.py`) and cmake scripts (e.g., `CMakeLists.txt`). I'm actually trying to eradicate this inconsistency (e.g., #21493 as a preparation step).

**Comment by HenryJia** [comment]
Yes it seems to all work normally with USE_NINJA=OFF so far

**Comment by xuhdev** [comment]
Could you try the latest version? A lot have changed in the build scripts.

**Comment by HenryJia** [comment]
Just tried it, same issue

**Comment by xuhdev** [comment]
Could you run `git clean -fdX` first? Also, what are the error messages you have got?

**Comment by passion3394** [comment]
same issue


../caffe2/perfkernels/common_avx.cc:17:2: error: #error ( "You found a build system error: __AVX__ is defined (via e.g. -mavx) " "but CAFFE2_PERF_WITH_AVX is not defined.");
 #error( \
  ^

**Comment by HenryJia** [comment]
As of c89301a6250ca17c568f11e52f715f939c08d7ce
This issue seems to have been resolved.
I'm going to close this for now.
If it shows up again I'll reopen it
