### ISSUE TITLE
test_triangular_solve is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#21577]
Failure:

```
Jun 08 06:44:19 ======================================================================
Jun 08 06:44:19 FAIL: test_triangular_solve (__main__.TestCuda)
Jun 08 06:44:19 ----------------------------------------------------------------------
Jun 08 06:44:19 Traceback (most recent call last):
Jun 08 06:44:19   File "/var/lib/jenkins/workspace/test/common_utils.py", line 399, in wrapper
Jun 08 06:44:19     method(*args, **kwargs)
Jun 08 06:44:19   File "/var/lib/jenkins/workspace/test/common_utils.py", line 399, in wrapper
Jun 08 06:44:19     method(*args, **kwargs)
Jun 08 06:44:19   File "test_cuda.py", line 2686, in test_triangular_solve
Jun 08 06:44:19     _TestTorchMixin._test_triangular_solve(self, lambda t: t.cuda())
Jun 08 06:44:19   File "/var/lib/jenkins/workspace/test/test_torch.py", line 5426, in _test_triangular_solve
Jun 08 06:44:19     self.assertEqual(res1, tb, 0)
Jun 08 06:44:19   File "/var/lib/jenkins/workspace/test/common_utils.py", line 547, in assertEqual
Jun 08 06:44:19     assertTensorsEqual(x, y)
Jun 08 06:44:19   File "/var/lib/jenkins/workspace/test/common_utils.py", line 539, in assertTensorsEqual
Jun 08 06:44:19     self.assertLessEqual(max_err, prec, message)
Jun 08 06:44:19 AssertionError: tensor(12.3821, device='cuda:0') not less than or equal to 0 : 
```

Occurences:
- https://circleci.com/gh/pytorch/pytorch/1951146?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console
- https://circleci.com/gh/pytorch/pytorch/1950373?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- https://circleci.com/gh/pytorch/pytorch/1955789?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console
- https://circleci.com/gh/pytorch/pytorch/1949948?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- https://circleci.com/gh/pytorch/pytorch/1947969?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- https://circleci.com/gh/pytorch/pytorch/1946219?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by vishwakftw** [comment]
I will take a look at this.

**Comment by ezyang** [comment]
Another occurrence: https://circleci.com/gh/pytorch/pytorch/1955789?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

**Comment by vishwakftw** [comment]
As far as I can tell, this doesn't seem to be an error with library calls. The part of the test deals with reuse of the tensor from `out`.

**Comment by vishwakftw** [comment]
It's strange that this test doesn't fail on CPU.

**Comment by vishwakftw** [comment]
This seems to be the first occurrence: https://circleci.com/gh/pytorch/pytorch/1946219?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment]
We suspect this was triggered by https://github.com/pytorch/pytorch/pull/21474

**Comment by vishwakftw** [comment]
Closing this, since this issue is a specific case of https://github.com/pytorch/pytorch/issues/21821.
