### ISSUE TITLE
printf in cfiles in/pytorch/aten/src/THNN/generic/

### ISSUE THREAD

**Issue by WeiHao97** [pytorch/pytorch#21575]
## ❓ Questions and Help

Hi I am trying to make breakdowns of the overheads about the operations happened inside conv2d.
I am trying to print something so that I added 'printf' in SpatialDilatedConvolution.c but But nothing is printed when I call conv2d after  "python setup.py build" or "python setup.py develop".
Did I focus on the wrong c file or Should I do other things to print things out?
Please help me.
Thank you

**Comment by jeffreyksmithjr** [comment]
I read this issue as a question. Please use https://discuss.pytorch.org for questions. Feel free to reopen this issue if I misunderstood.
