### ISSUE TITLE
(closed) PyTorch 0.1.12 version has different Math APIs (e.g. sum, max) in different OS

### ISSUE THREAD

**Issue by eagle705** [pytorch/pytorch#2160]
I used PyTorch 0.1.12 version. 

What I found is Math API in PyTorch(0.1.12) installed in Linux, MacOS, windows  is different.

I printed PyTorch version information by using "print(torch.__version__)

MacOS version : 0.1.12 (conda install pytorch torchvision -c soumith)
Windows version : 0.1.12 (conda install -c peterjc123 pytorch=0.1.12)
Linux version: 0.1.12_2

When I used math API such as sum and max, I found some version(MacOS) has argument options (keepdim) and others(Windows, Linux) has not.

As a result, the output dimension of mat API operation is different. 

Please check the issue :)

**Comment by moskomule** [comment]
Currently the [doc](http://pytorch.org/docs/master/) says the master is `0.2+5254846` so may be something confused. `keepdim` is 0.2's syntax.

**Comment by eagle705** [comment]
I installed PyTorch on MacOS from source to use GPU. Maybe I installed the master branch. Is there any way (like "torch.__version__") to check that my version is 0.2 or 0.2+5254846 ?

**Comment by moskomule** [comment]
How is `pip list`? In my environment, `torch (0.1.12+4e35652)` is shown.

**Comment by fmassa** [comment]
The problem as you said is that you installed different versions of pytorch in different machines. I think this issue can be vlosed
