### ISSUE TITLE
Support all_reduce a list of same-device tensors 

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#21640]
[`distributed_c10d.py`](https://github.com/pytorch/pytorch/blob/master/torch/distributed/distributed_c10d.py) provides APIs to reduce a single tensor per process, or multiple tensors per process where each of them needs to reside on a different device. It will be useful (e.g., for model averaging) to support reducing a list of tensors per process where all of them are on the same device. The implementation should apply bucketing under the hood to get better performance.

**Comment by pietern** [comment]
This wouldn't allreduce them together (as is the case for the multi device one) but rather concatenate them and allreduce them in a single call, as opposed to N separate calls. We can call this `allreduce_coalesced`, similar to the existing `broadcast_coalesced`.

**Comment by pietern** [comment]
This has been added in #24949.
