### ISSUE TITLE
How to solve "torch.cuda.FloatTensor doesn't implement stateless method range"?

### ISSUE THREAD

**Issue by shwoo93** [pytorch/pytorch#2165]
Hello

When I was working on my code with GPU mode(using cuda) I got an error saying like below

"torch.cuda.FloatTensor doesn't implement stateless method range"?

It seems like pytorch GPU mode does not supports torch.range, since when I changed to CPU mode no error was occurred.

Then what should be the solution in order to use range in GPU mode?

Thanks in advance

**Comment by soumith** [comment]
this is fixed in master, will be in the next release.

**Comment by Jiaming-Liu** [comment]
Similarly, "Type torch.cuda.FloatTensor doesn't implement stateless method eye"

**Comment by fmassa** [comment]
@Jiaming-Liu did you try using it as follows:
```python
res = torch.eye(3, 3, out=torch.cuda.FloatTensor())
```
?

**Comment by Jiaming-Liu** [comment]
@fmassa 
```
import torch
res = torch.eye(3, 3, out=torch.cuda.FloatTensor())
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2820, in run_code
    exec code_obj in self.user_global_ns, self.user_ns
  File "<ipython-input-3-887930d01e31>", line 1, in <module>
    res = torch.eye(3, 3, out=torch.cuda.FloatTensor())
TypeError: Type torch.cuda.FloatTensor doesn't implement stateless method eye

torch.__version__
Out[4]: '0.2.0+4a4d884'

**Comment by fmassa** [comment]
@Jiaming-Liu silly on me, the PR with `eye` has not yet been merged into master, see https://github.com/pytorch/pytorch/pull/2395
