### ISSUE TITLE
[Feature Request] PyTorch RNN State Dropout

### ISSUE THREAD

**Issue by Deepblue129** [pytorch/pytorch#2166]
Deepmind released a paper researching the effectiveness of LSTMs: https://arxiv.org/pdf/1707.05589.pdf

For the paper, they used RNN dropout for the RNN hidden state. Without manually unrolling the RNN, could the LSTM and GRU cell include `state_dropout`?

Looks like the current RNN cells only support between layer dropout.

**Comment by jekbradbury** [comment]
This isn't supported by cuDNN right now, so the computation would have to use unrolled modules anyway.

**Comment by Deepblue129** [comment]
@jekbradbury Could it be unrolled in a more efficient manner than in Python? Prevent a massive drop in speed.

**Comment by apaszke** [comment]
No, there's no specialized backend in PyTorch that supports it at the moment, so you need to use Python. But we're working on making all kinds of RNNs faster, so it should be getting better over the next few months :blush:

**Comment by diegovalenzuelaiturra** [comment]
what about now ?
