### ISSUE TITLE
I met thie error when run onnx inference. 

### ISSUE THREAD

**Issue by bemoregt** [pytorch/pytorch#21677]
Hi, @svenstaro @eklitzke @dreiss @huitseeker @jfsantos 

My Code (onnx model converted from pytorch model)-

```python
import time
import numpy as np
import onnxruntime as rt

im = np.random.rand(1, 3, 256, 384).astype('uint8')

sess = rt.InferenceSession("model.onnx")

t0 = time.time()
output = sess.run(['prob'], {'data': im})[0]
print (time.time() - t0)
```

I met thie error when run onnx inference. -
`RuntimeError: Method run failed due to: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:data`

What's wrong to me ??

Best,
@bemoregt.

**Comment by pietern** [comment]
Are you sure the arguments you pass to `sess.run` are valid? Does the shape of the input match the expected shape of the ONNX model?

**Comment by svenstaro** [comment]
Why would you highlight me?

**Comment by garymm** [comment]
Please file issues relating to ONNX Runtime in https://github.com/microsoft/onnxruntime
