### ISSUE TITLE
Import ONNX model to Pytorch

### ISSUE THREAD

**Issue by hossein1387** [pytorch/pytorch#21683]
## 🚀 Feature

Importing ONNX models into Pytorch.
## Motivation

Almost all other frameworks already support this. Importing ONNX models into Pytorch makes Pytorch much more flexible.

## Pitch

In `torch.onnx`, a function should be created to take the ONNX model and outputs a Pytorch model. 

cc @BowenBao @neginraoof

**Comment by davidtranno1** [comment]
Hi everyone,
As i know caffe2 fully supports ONNX import/export and caffe 2 is a part of PyTorch recently. However, I can not import onnx model file to Pytorch and run inference properly. How can resolve this issue?

**Comment by olegmikul** [comment]
Agreed. I was kind a shocked when I have learnt PyTorch doesn't have that.

**Comment by rahul99** [comment]
@soumith, any plans to roll out this functionality anytime soon?

**Comment by gordinmitya** [comment]
+ to motivation
I need to convert an onnx model to torchscript (.pt) so I can run it on pytorch mobile. 
How can I do this now? Any workarounds?

**Comment by jcowles** [comment]
+1, not supporting ONNX import feels like half of the ONNX implementation is missing

**Comment by kooyunmo** [comment]
Is there any ongoing PR for this issue?

**Comment by borhanMorphy** [comment]
As a heavy torch user,  this feature sounds nice.

**Comment by IguanaAzul** [comment]
This feature is relevant, it should be implemented.

**Comment by LyricZhao** [comment]
Looking forward to have it in torch

**Comment by JVGD** [comment]
This feature is very relevant, my motivation:

- Load ONNX models into pytorch to compare models against same test cases

**Comment by solarflarefx** [comment]
@gordinmitya Have you found a solution to your problem?  I am trying to do something similar.

**Comment by gordinmitya** [comment]
@solarflarefx no ):
pytorch mobile suddenly stoped working without any changes from my side, so I decide to just skip it until mobile version become stable

**Comment by touchwolf** [comment]
onnxruntime may helps

**Comment by Franzis39** [comment]
Anyone figured a simple way to do this ?

**Comment by ay27** [comment]
I think it will be a huge challenge to restore the runtime graph in PyTorch. But if we focus on the model parameters, likes that we only load the parameters stored in an onnx file rather than load the full model, maybe more easy.

Maybe this snippet will help:
```python
import onnx
from onnx import numpy_helper
import torch
from torchvision import models

model = models.resnet18()
torch.onnx.export(model, torch.randn(1, 3, 224, 224), 'resnet18.onnx')

onnx_model = onnx.load('resnet18.onnx')

graph = onnx_model.graph
initalizers = dict()
for init in graph.initializer:
    initalizers[init.name] = numpy_helper.to_array(init)

for name, p in model.named_parameters():
    p.data = (torch.from_numpy(initalizers[name])).data
```

**Comment by pram991** [comment]
Found a not-perfect but working solution.
https://gist.github.com/qinjian623/6aa777037534c1c1dccbb66f832e93b8

**Comment by zczjx** [comment]
+1

**Comment by WilliamTambellini** [comment]
Now 151 likes but no sign of step forward. I dont know how the pytorch project works but is a minimum of reply from the project maintainers to be expected ?

**Comment by matfeb** [comment]
A temporary not perfect time consuming idea I'm going to try is to convert onnx -> keras (onnx2keras) then keras -> pytorch (MMdnn).

**Comment by ShairozS** [comment]
It is absolutely ridiculous that this issue is still open honestly. I exported a very time consuming model to Onnx for use with RT and now need to make some modifications to it in Pytorch and I realize that for some reason this is a missing capability. I fully expected that **if I can export to onnx format from pytorch that I should also be able to import it** - rarely have I ever encountered a framework that lets you export to a format without also being able to read that format and it is frankly bad practice.

**Comment by itsjoshthedeveloper** [comment]
@gchanan any updates on if/when this will be implemented in the future?

**Comment by gineshidalgo99** [comment]
+1 to this request, any ETA?

**Comment by madhavajay** [comment]
This looks like a pretty new and solid effort to achieve onnx to pytorch conversion: https://github.com/ToriML/onnx2pytorch

**Comment by fumihwh** [comment]
Hi folks, I create a repo for generating pytorch code from onnx.
https://github.com/fumihwh/onnx-pytorch
Different from `ToriML/onnx2pytorch`, my repo GENERATE pytorch code, not Module instance in stack.

**Comment by calvinmccarter-at-lightmatter** [comment]
Just a heads-up that v0.4 of onnx2pytorch ([https://github.com/ToriML/onnx2pytorch](https://github.com/ToriML/onnx2pytorch)) was released today. In addition to now supporting Loop, LSTM, and a lot more, this release has improved memory management by removing activations that are no longer required by any following operations. We're nearing full ONNX operator coverage, and now all the MLPerf Datacenter Inference ONNX models can be successfully imported into PyTorch.

**Comment by mike-burl** [comment]
Another +1 for this feature.  I've gotten pretty far into a project on the assumption that if I could export to onnx that I'd be able to go the other direction.  I don't think it's unreasonable to think this functionality should be included in pytorch itself

**Comment by h-grieve** [comment]
Another +1 from me, really surprised it isn't a feature.

**Comment by alledoubleL** [comment]
I'm very surprised this can't be done 😮 
+1

**Comment by Thunfischpirat** [comment]
Just ran into the issue, and I'm surprised that this hasn't been addressed in more than three years...

**Comment by ZeroAda** [comment]
There is another lib: [onnx2torch](https://github.com/ENOT-AutoDL)
It works for me and I can use it to continue train on my onnx model.

**Comment by natwille1** [comment]
Would love this feature!

**Comment by ngoanpv** [comment]
+1

**Comment by chr4ss12** [comment]
+1

**Comment by akshaytrikha** [comment]
Why was this issue closed? It seems like there is a lot of support from the community for it.

**Comment by GeorgeS2019** [comment]
[onnx2torch](https://github.com/ENOT-AutoDL/onnx2torch)

**Comment by Sandjan** [comment]
Whats the current status of this issue? Why was it closed?

**Comment by kolabit** [comment]
This feature is obviously non-trivial, but would be great to have

**Comment by santoshcoder23** [comment]
any reason why this issue is closed ?

**Comment by vdoom** [comment]
Why this issue is closed?! It's MUST be resolved!

**Comment by ashvardanian** [comment]
+1

**Comment by vladimirrotariu** [comment]
+1

**Comment by quaternio** [comment]
+1

**Comment by benoitboidin** [comment]
I would like to use this feature too, does someone have any news about this issue?

**Comment by garrettbyrd** [comment]
@BowenBao @neginraoof Bumping this yet again, and echoing that I am not sure why this was closed.

**Comment by DomHudson** [comment]
+1

**Comment by takeraparterer** [comment]
+1

**Comment by soumith** [comment]
this is non-trivial to both implement and maintain. The PyTorch core team are unlikely to do it.
There are community projects like https://github.com/ENOT-AutoDL/onnx2torch which plug this gap to an extent, and folks should contribute to those to make them more feature-complete.

**Comment by dakinevich** [comment]
+1
