### ISSUE TITLE
[JIT] Optimize assert statements by __debug__ flag

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#21681]
## 🐛 Bug

`assert` statements are not removed in jit graph even if -O is provided to python interpreter.

## To Reproduce

```python
import torch.jit as jit


@jit.script
def test():
    assert 1 == 1
    return 1


print(test.graph)
```
Output:
```
graph():
  %2 : string = prim::Constant[value="Exception"]()
  %0 : int = prim::Constant[value=1]()
  %1 : bool = aten::eq(%0, %0)
   = prim::If(%1)
    block0():
      -> ()
    block1():
       = prim::RaiseException(%2)
      -> ()
  return (%0)
```

## Expected behavior

The assert statements should be removed when `__debug__` is False. Please refer to https://docs.python.org/3/using/cmdline.html#cmdoption-o and https://docs.python.org/3/reference/simple_stmts.html#assert .

## Environment

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 410.48
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/lib64/libcudnn.so.7.4.1
/usr/local/cuda-10.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchtext                 0.3.1                    pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch

**Comment by eellison** [comment]
We have to be careful with this, because in the future we will make `assert x is not None` refine Optional types.

**Comment by suo** [comment]
As @eellison said, I don't think we can support this, because assertions have important meaning in the type system. `assert x is not None` will refine `x` to be `Tensor` instead of `Optional[Tensor]`, which is nice from a UX perspective because you don't have to constantly unwrap `x` anymore.

I'm going to close this for now as we don't have a good path to support this. Feel free to comment/reopen if anyone really really wants this.
