### ISSUE TITLE
EmbeddingBag Doesn't Work

### ISSUE THREAD

**Issue by shawnjhenry** [pytorch/pytorch#2169]
The title says it all.  Every input I've tried breaks it.

**Comment by apaszke** [comment]
Can you please send us a small snippet to reproduce it?

**Comment by killeent** [comment]
I tried the simple code snippet from Soumith's original PR: https://github.com/pytorch/pytorch/pull/1803 and it works. Additionally, the unit test for EmbeddingBag pass works. Waiting for input from @shawnjhenry to followup.

**Comment by amrsharaf** [comment]
I think the problem is that when the input is a 2D tensor, and offsets=None, the created offsets are of type LongTensor not Variable of LongTensor, and the code breaks in the forward path with the error: RuntimeError: expected a Variable argument, but got torch.LongTensor

**Comment by amrsharaf** [comment]
I tried to fix the Variable vs LongTensor issue, but seems like EmbeddingBag doesn't support 2D tensors at all! 

In torch/nn/modules/sparse.py, line 149, there is an assertion that the input indices are of dimension = 1:

`assert indices.dim() == 1`

**Comment by killeent** [comment]
cc @soumith as I don't know enough about EmbeddingBag to know if it should support 2D Tensors.

**Comment by soumith** [comment]
EmbeddingBag should support 2D Tensors as `inputs` as docs mention.
When `inputs` is 2D, `offsets` is not given by the user.
Then the code here: https://github.com/pytorch/pytorch/blob/f3f478960e35920affebe7c2ddc00f6edd768d2b/torch/nn/modules/sparse.py#L194-L201
is supposed to create an offsets Tensor for you correctly.
Indeed, as @amrsharaf mentions, this possibly needs to wrapped in a Variable: https://github.com/pytorch/pytorch/blob/f3f478960e35920affebe7c2ddc00f6edd768d2b/torch/nn/modules/sparse.py#L201 and the 1D input Tensor possibly needs to be re-viewed as 1D.

**Comment by soumith** [comment]
PR#2429 fixes this in master. thanks @ajfisch !
