### ISSUE TITLE
Better CMake integration

### ISSUE THREAD

**Issue by xuhdev** [pytorch/pytorch#21702]
(This is a feature that I've been working on (see https://github.com/pytorch/pytorch/pull/21493#issuecomment-500513129). I open this issue so that relevant PRs can be better tracked.)

## 🚀 Feature and Motivation

Better CMake integration. Currently there are a lot of inconsistency and redundancy between the Python setup scripts and CMake scripts (duplicated env check, overriding env check, inconsistent treatment of which results of checking will be used, etc.). I would like to improve the integration.

## Pitch

The improvement I would like to implement includes:

- Allowing build options to be directly specified using options specified in CMakeLists.txt (without explicitly being processed in Python setup scripts).
- Allowing users to adjust build options directly via cmake-gui/ccmake/editing CMakeCache.txt (currently users must take care of both options in CMakeCache.txt and environmental variables passed to setup.py and ensure they are consistent upon rebuild).
- removing a lot of system and library environment checks in Python setup scripts while CMake can already handle them pretty well.
- ...

## Existing PRs (including those that were made to clear the path)

#21034
#21296
#21417 
#21493 
#21653 
#21877
#22153
#22154
#22215
#22360

**Comment by ezyang** [comment]
One small thing I noticed recently, when trying to build directly using cmake: `PYTHON_EXECUTABLE` detection doesn't seem to work, I have to say `-DPYTHON_EXECUTABLE=$(which python)` to get it to point at the right place.

**Comment by xuhdev** [comment]
@ezyang Do you mean running the following in a clean source tree? It actually worked for me (`PYTHON_EXECUTABLE` in `CMakeCache.txt` was set correctly).

```bash
mkdir build
cmake ..
```

**Comment by ezyang** [comment]
Yeah, that didn't work for me. Interesting!

Excerpts from Hong Xu's message of 2019-06-12 15:00:44 -0700:
> @ezyang Do you mean running the following in a clean source tree? It actually worked for me (`PYTHON_EXECUTABLE` in `CMakeCache.txt` was set correctly).
> 
> ```bash
> mkdir build
> cmake ..
> ```
>

**Comment by xuhdev** [comment]
I believe that this issue has been largely resolved (if I'm not mistaken), except NumPy as a special case in which we should rely on the Python script. The next step may be to resolve #23512

**Comment by ezyang** [comment]
OK, SGTM!
