### ISSUE TITLE
Dict Attribute does not work in PYTORCH_JIT=0

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#21717]
## 🐛 Bug

AttributeError: 'Attribute' object has no attribute 'keys'

A dictionary Attribute in PYTORCH_JIT=0 is not a dictionary but a Attribute object

**Comment by sidazhang** [comment]
@suo  @driazati I know that you are refactoring this right now to get rid of attribute. I am just filing this to track it and make sure that in your new refactor, dictionary is treated correctly. No need to fix this bug with attribute

**Comment by suo** [comment]
Closing as `Attribute` is no longer necessary with the new API, and with the impending doom of Python 2 you can just use Py3 type annotations.
