### ISSUE TITLE
Caffe2 APIs are being deprecated

### ISSUE THREAD

**Issue by dongfangduoshou123** [pytorch/pytorch#21726]
I see in website caffe2.ai say that 'Caffe2 APIs are being deprecated', Is this mean caffe2 is abandoned or other mean? I want to know caffe2's future.

Thank you!

**Comment by dongfangduoshou123** [comment]
@kostmo

**Comment by soumith** [comment]
it means what it says -- the API is being deprecated. Eventually the caffe2 frontend will receive no support.

**Comment by dongfangduoshou123** [comment]
But, The caffe2's subdir 'the https://github.com/pytorch/pytorch/tree/master/caffe2' is still updating， means caffe2's api is being deprecated and its all features will be used by pytorch/libtorch frontend?

**Comment by soumith** [comment]
we are making no commitments on what part of that code will be used by libtorch
