### ISSUE TITLE
libAten undefined symbol

### ISSUE THREAD

**Issue by BestSonny** [pytorch/pytorch#2172]
After `sudo python setup.py install` the latest master pytorch.
Get the following errors when running a pytorch program

from torch._C import *
ImportError: /usr/local/lib/python2.7/dist-packages/torch/lib/libATen.so.1: undefined symbol: THNN_CudaDoubleSpatialClassNLLCriterion_updateGradInput

Anyone knows how to solve this?

**Comment by ezyang** [comment]
CC @zdevito @killeent 

Usually when I see an error like this it is because I'm picking up a stale version of the library in question. But this shouldn't happen if you ran `setup.py install`.

**Comment by zdevito** [comment]
Yeah, I found that removing the build and torch/lib/build folders and rebuilding fixed it. I do not know why the normal install procedure doesn't pick up the change.
