### ISSUE TITLE
CUDA out of memory error while loading VGG model.

### ISSUE THREAD

**Issue by mansoorkhansitar** [pytorch/pytorch#21733]
Hello,

I have this issue where I get a CUDA error while loading my model. I'm using Amazon ec2 p2.8x large server. I have used the nn.Dataparallelism module in pytorch with device_ids = 0,1,2,3,4,5,6,7 specified. However, the model is fit and consuming all of the GPU memory of only the first GPU. And when I start the training process within a few iterations throws a CUDA out of memory error. How do I make sure that my model gets distributed over the 8 cores? Is there a way to do it? 

Best,
Mansoor

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
