### ISSUE TITLE
Missing documentation for cdist

### ISSUE THREAD

**Issue by simonepri** [pytorch/pytorch#21730]
## 📚 Documentation

Following the discussions in https://github.com/facebookresearch/PyTorch-BigGraph/issues/51#issuecomment-501293200, I'm opening this issue to let you know that the `cdist` function introduced in the last release of PyTorch [it has not been documented yet](https://pytorch.org/docs/stable/search.html?q=cdist&check_keywords=yes&area=default).

**Comment by gchanan** [comment]
@ifedan can you take a look?

**Comment by ifedan** [comment]
Fixed https://github.com/pytorch/pytorch/pull/25221
