### ISSUE TITLE
support slicing on nn.Sequential

### ISSUE THREAD

**Issue by silky** [pytorch/pytorch#2174]
it'd be great to pick out elements of of a sequential with array slicing:

```
s = nn.Sequential(...)
# Drop the last element
a = s[0:-1]
```

**Comment by acgtyrant** [comment]
I agree this idea!

**Comment by acgtyrant** [comment]
However, [the official seems does not agree...](https://github.com/pytorch/pytorch/issues/1114#issuecomment-289487843)

**Comment by soumith** [comment]
@colesbury this has come up again (last in https://github.com/pytorch/pytorch/issues/1114). Shall we reconsider?

**Comment by vishwakftw** [comment]
I attempted getting a `slice` to work. Is this fine?
```
def __getitem__(self, inp):
    if isinstance(inp, slice):
        ret_seq = nn.Sequential()
        seq_list = list(self._modules.items())
        for i in range(*inp.indices(len(self._modules))):
            ret_seq.add_module(seq_list[i][0], seq_list[i][1])
        return ret_seq
```

**Comment by vishwakftw** [comment]
cc: @soumith This issue has been open for quite sometime.
