### ISSUE TITLE
torch.load: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1105: ordinal not in range(128)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#21743]
Steps to reproduce: run this test:

```
      def test_conv_backcompat(self):
          from torch.serialization import SourceChangeWarning
          # This file was generated by running on PyTorch 1.0.1 on Python 2:
          #
          #     import torch
          #     from torch import nn
          #     m = nn.Conv2d(1, 1, 1)
          #     torch.save(m, 'legacy_conv2d.pt')
          #
          path = download_file('https://download.pytorch.org/test_data/legacy_conv2d.pt')
          with warnings.catch_warnings():
              warnings.simplefilter('ignore', SourceChangeWarning)
              m = torch.load(path)
          input = torch.randn((1, 1, 1, 1), dtype=torch.float)
          self.assertEqual(m(input).size(), (1, 1, 1, 1))
```

The problem is that the docstring in the module has a Unicode character and our unpickler doesn't specify any encoding (thus defaulting to ascii).

**Comment by SsnL** [comment]
see the 2nd note of torch.load: https://pytorch.org/docs/master/torch.html#torch.load

**Comment by ezyang** [comment]
You're right. I'm not the only one to have this problem https://github.com/CSAILVision/places365/issues/25

Maybe we should catch this error and point at the documentation on the matter.

**Comment by nmilosev** [comment]
@ezyang does this look OK to you?

```py
>>> path = 'legacy_conv2d.pt'
>>> m = torch.load(path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/milosevicn/contrib/pytorch/torch/serialization.py", line 422, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/milosevicn/contrib/pytorch/torch/serialization.py", line 612, in _load
    raise RuntimeError("Failed to unpickle module; The docstring in the module you are trying to load has a Unicode character and our unpickler defaults to ascii. Please see the 2nd note of torch.load: https://pytorch.org/docs/master/torch.html#torch.load") from None
RuntimeError: Failed to unpickle module; The docstring in the module you are trying to load has a Unicode character and our unpickler defaults to ascii. Please see the 2nd note of torch.load: https://pytorch.org/docs/master/torch.html#torch.load

```

I have suppressed the original `UnicodeDecodeError` as we are explaining it better here, although maybe the position of the character is important for the user? Let me know what you think.

**Comment by ezyang** [comment]
A few notes:

1. Raise from is Python 3 only, and we're going to keep supporting Python 2 up until its EOL. We have a portable version in `torch/_six.py`.
2. You should raise from the original UnicodeError; that would satisfy your question about the position of character as this information would be retained
3. I don't think the error message written here conveys the most important points to the user.  Here's the most important steps: (1) what failed? (2) how should I fix it? (3) where can I find more information?
4. Minor copyedit nits (don't capitalize after semicolon, capitalize ASCII, use second rather than 2nd)

**Comment by nmilosev** [comment]
First of all thank you for your help, I realize this is a minor issue but it's really nice of you to point me in the correct direction. :)

Here is the new trace:

```py
>>> path = 'legacy_conv2d.pt'; import torch
>>> m = torch.load(path)
Traceback (most recent call last):
  File "/home/milosevicn/contrib/pytorch/torch/serialization.py", line 611, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1105: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/milosevicn/contrib/pytorch/torch/serialization.py", line 423, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/milosevicn/contrib/pytorch/torch/serialization.py", line 613, in _load
    raise_from(RuntimeError("Module unpickle has failed because the module's docstring has a Unicode character and our unpickler defaults to ASCII. Please see the second note of torch.load: https://pytorch.org/docs/master/torch.html#torch.load for more information. Use pickle_load_args paramater to specify encoding to fix this error (e.g. encoding='latin1')."), ude)
  File "<string>", line 3, in raise_from
RuntimeError: Module unpickle has failed because the module's docstring has a Unicode character and our unpickler defaults to ASCII. Please see the second note of torch.load: https://pytorch.org/docs/master/torch.html#torch.load for more information. Use pickle_load_args paramater to specify encoding to fix this error (e.g. encoding='latin1').
```

Thanks for the pointer about `_six`.

If this is OK, I am ready to prepare the PR. Another question I have, should I add a test that tests this functionality or modify the mentioned test?

**Comment by ezyang** [comment]
Modifying the existing one sounds fine :) (Also, technically I don't think it is "our pickler", it is the "Python 2 pickler")

**Comment by nmilosev** [comment]
@ezyang Let me know it is ok. And thank you again for the help!

**Comment by driazati** [comment]
@SsnL  What's the reason we don't use `utf-8` as a default encoding instead of `ascii`?

https://github.com/pytorch/pytorch/blob/df338f80a6319cbc4f411df5ca4469c56fd8ec87/torch/serialization.py#L553

**Comment by SsnL** [comment]
@driazati the exact reason escapes me, but if I had to guess, I think they are only used for the few internal keys that are always in `ascii` anyways.

**Comment by driazati** [comment]
Is there any harm in making the `Unpickler` default to `utf-8` instead of `ascii` if no encoding is provided? That would fix this issue without users having to do anything.

https://github.com/pytorch/pytorch/blob/df338f80a6319cbc4f411df5ca4469c56fd8ec87/torch/serialization.py#L608

**Comment by SsnL** [comment]
@driazati I'm not sure if I understand the relation between your proposal and the code linked. The encoding in `persistent_load` should not matter, as it it only used to decode several internal keys.

**Comment by driazati** [comment]
Missed the `Unpickler` creation line by 1, passing `encoding='utf-8'` should be backwards compatible (unless someone was relying on this error) and fix the issue

https://github.com/pytorch/pytorch/blob/df338f80a6319cbc4f411df5ca4469c56fd8ec87/torch/serialization.py#L607

**Comment by nmilosev** [comment]
@driazati what would happen if I (using py2) had some modules encoded with ASCII and wanted to decode them with UTF-8? All good?

**Comment by driazati** [comment]
Yeah, ASCII is a subset of utf-8

**Comment by SsnL** [comment]
Some unicode encodings can be decoded by utf-8 (to wrong char), but not ascii. So it could break user-side error handling code.

**Comment by SsnL** [comment]
that said, it probably won't be a big deal if we switch default.

**Comment by nmilosev** [comment]
Okay the pull #26421 has some failures it seems (if anyone of you can help that would be great!) but then if we all agree to change the default it is probably best to scrap that and change the default encoding, and setup some tests? Let me know! :)

**Comment by ezyang** [comment]
Note that, for some reason, the docs explicitly recommend using `latin-1`, rather than `utf-8`. I don't know why they suggest this. It would be good to at least check the commit that added this line and see if there is some back story.

**Comment by SsnL** [comment]
@ezyang I think I wrote that... with no real reason.

**Comment by ezyang** [comment]
OK, let's default to utf-8 then :)

**Comment by SsnL** [comment]
Make sure to explicitly mention it in docs :)

**Comment by nmilosev** [comment]
This should be save to close now. :)

**Comment by sadanand-singh** [comment]
enforcing encoding='utf-8' breaks down the case when one uses the dill module for pickling, as dill does not take 'encoding' as an argument!

**Comment by ezyang** [comment]
@sadanand-singh Thanks, that sounds serious. Can you please open a new issue and cc me on it

**Comment by sadanand-singh** [comment]
Thanks @ezyang. I have opened a new issue #28313 and CCed you.
