### ISSUE TITLE
compile error when using Libtorch 1.1 on windows 7 vs2015

### ISSUE THREAD

**Issue by njtuzzy** [pytorch/pytorch#21768]
## ❓ Questions and Help
I followed the guidence from pytorch.org to make a project which recall the libtorch using Vs2015. Cuda version 8.0 cudnn 7.0 libtorch version 1.1

but when i compile the project, lots of error in typeid.h popped oput which seems to related caffe2? for example:

C2134 caffe2:TypeIdentifier::TypeIdentifier:call does not result in a constant expression
C2071 caffe2:TypeMeta:: New: illegal storage class

and so on

is there anything wrong? or how to fix it?

Thanks

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by peterjc123** [comment]
If you use VS 2015, make sure you have Update 3 installed.

**Comment by peterjc123** [comment]
Wait, you are using CUDA 8. Starting from v1.1.0, we have stopped the support for CUDA 8.

**Comment by njtuzzy** [comment]
@ peterjc123 even i use the pytorch 1.0 before, it is the same problems: do you think that it may be caused by my VS stidio version? 
and i will try cuda 9.0  

Thanks

**Comment by peterjc123** [comment]
> @ peterjc123 even i use the pytorch 1.0 before, it is the same problems: do you think that it may be caused by my VS stidio version?
> and i will try cuda 9.0
> 
> Thanks

If you use VS 2015, make sure you have Update 3 installed.

**Comment by njtuzzy** [comment]
@peterjc123
 After i updated the VS2015 to update3, it works. thanks very much. But i  got another question. It is the "unpack" function in variadic.h. C2951: template declarations are only permitted at global or namespace scope. ? is it caused by the VS2015 version?

Thanks

**Comment by peterjc123** [comment]
Looks like it is caused by the missing of some C++ 11/14 features. So you'll have to use VS 2017. BTW, if you use VS 2017 with the latest update, you'll have to use CUDA >= 10.0.

**Comment by njtuzzy** [comment]
> Looks like it is caused by the missing of some C++ 11/14 features. So you'll have to use VS 2017. BTW, if you use VS 2017 with the latest update, you'll have to use CUDA >= 10.0.


@peterjc123  thanks  for telling that!
