### ISSUE TITLE
should weight norm only recompute weights at the beginning and after each call to backward?

### ISSUE THREAD

**Issue by greaber** [pytorch/pytorch#2176]
I haven't tried the new pytorch implementation of weight norm, but I was having problems applying a similar implementation to RNNs because the weight recomputation with each call to `forward` was causing me to run out of memory.  The solution seemed to be to only recompute weights after each call to `backward`.  The version I was having problems with and my fix are both here: https://gist.github.com/rtqichen/b22a9c6bfc4f36e605a7b3ac1ab4122f
(I should warn that I am not totally sure I didn't do something wrong in my implementation since the results I got from weight norm in my model were much worse than I expected.)  Should the official pytorch implementation of weight norm also recompute weights only after a call to `backward`?

cc @VitalyFedyunin @ngimel @mruberry

**Comment by soumith** [comment]
according to the code, it recomputes the weights before each call to `forward`: https://github.com/pytorch/pytorch/blob/ea563c1df171e6e84844e78aa34aa0043df01755/torch/nn/utils/weight_norm.py#L44-L45

cc: @colesbury to follow up on this (see the gist). I'm not sure why reallocating storage is a problem.

**Comment by greaber** [comment]
Doesn't recomputing the weights on every ``forward`` mean that you are going to use O(N^2s) space instead of O(N^2 + Ns) space, where N is the number of neurons and s is the number of BPTT steps you do?

**Comment by colesbury** [comment]
Right, so in recurrent nets we're recomputing the `weight` multiple times, which is unnecessary and leads to extra memory usage.

The backward hook solution isn't robust: `weight` needs to be re-computed if `weight_v` or `weight_g` changes, not after they're gradients are computed. For example:

```python
output = module(input)  # 1
output.backward()  
output2 = module(input)  # 2
optimizer.step()
output3 = module(input)  # 3
```

With the backward hook, weight would be recomputed at (2) when it should be recomputed at (3).

**Comment by mruberry** [comment]
This should be subsumed by the discussion in https://github.com/pytorch/pytorch/issues/7313.
