### ISSUE TITLE
UserWarning: ONNX export failed on primitive operator ListUnpack; please report a bug

### ISSUE THREAD

**Issue by TTMRonald** [pytorch/pytorch#21778]
## ❓ Questions and Help

Hi, I want to convert model to onnx in pytorch 1.0.0. But i meet an error.

> UserWarning: ONNX export failed on ATen operator group_norm because torch.onnx.symbolic.group_norm does not exist

Then, I added a definition as described in this document. 
https://github.com/onnx/tutorials/blob/master/tutorials/PytorchAddExportSupport.md#fail-to-export-the-model-in-pytorch

The added code is
`@parse_args('v', 'i', 'v', 'v', 'f', 'i')
  def group_norm(g, input, num_groups, weight, bias, eps, cudnn_enabled):
      return g.op("Group_norm", input, weight, bias, num_groups_i=num_groups, eps_f=eps, cudnn_enabled_i=cudnn_enabled, operator_s="group_norm")`

But I meet the error.

> UserWarning: ONNX export failed on primitive operator ListUnpack; please report a bug

How can I solve it? Thanks.

cc @BowenBao @neginraoof

**Comment by garymm** [comment]
@TTMRonald please provide code to reproduce the problem. If possible please test on the latest pytorch nightly.

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
