### ISSUE TITLE
Problem when using DataLoader with a 1-dimensional FloatTensor

### ISSUE THREAD

**Issue by benjamin-work** [pytorch/pytorch#2178]
When I use `DataLoader` with a 1-dimensional `FloatTensor`, the resulting batches will be `DoubleTensor`. Here is a snippet:

```python
import torch
from torch.utils.data import DataLoader, TensorDataset
from torch.utils.data.dataloader import default_collate

X = torch.zeros(100, 10)  # 2-dimensional
y = torch.zeros(100)  # 1-dimensional

type(X), type(y)  # (torch.FloatTensor, torch.FloatTensor)  <- so far so good

dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=10)
xx, yy = next(iter(loader))
type(xx), type(yy)  # (torch.FloatTensor, torch.DoubleTensor)  <- unexpected
```

This was unexpected, since the incoming `y` is float and its batches are double.

The reason for this behavior seems to be that `DataLoaderIter` sends each row separately to `default_collate`. A row from the dataset in this case is a tuple of `FloatTensor` (from `X`) and float (from `y`). `default_collate` hits the last condition and transposes the data. For `X`, this is okay, but `y` now becomes a list of floats, which `default_collate` converts to a `DoubleTensor`.

This behavior can be replicated like this:

```
xi, yi = default_collate([(X[i], y[i]) for i in range(100)])
type(xi), type(yi)  # (torch.FloatTensor, torch.DoubleTensor)
```

I'm not sure whether this is a bug or a user error.

**Comment by soumith** [comment]
When you call next(iter(loader)), it calls `__getitem__(self, index)` on your dataset, which returns `self.data_tensor[index], self.target_tensor[index]`. 
However, `self.target_tensor[index]` will become a Python scalar of precision double. Then, when the mini-batch is collated, it puts all these doubles together in a `torch.DoubleTensor`.

A fix / workaround is to make `y` to be `torch.zeros(100, 1)` and then squeeze the last dimension once you get the mini-batch.

I'm not sure we can solve this / if this is a bug.

**Comment by apaszke** [comment]
We can solve this once we get scalars

**Comment by benjamin-work** [comment]
> A fix / workaround is to make `y` to be `torch.zeros(100, 1)` and then squeeze the last dimension once you get the mini-batch.

This is my current workaround.

> We can solve this once we get scalars

Nice, then I will close this issue.
