### ISSUE TITLE
Support torch.where(condition) as an alias for NumPy-like nonzero

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#21798]
## 🚀 Feature
Implement `torch.where(condition)` as an alias for a NumPy-like nonzero. Currently, we only support `torch.where(condition, x, y)` with the second and third arguments.

## Motivation
NumPy supports numpy.where(condition) without the x and y arguments. It's behaves like numpy.nonzero.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html

## Pitch
Maybe @alexpeys will stop bugging me if you implement this

## Alternatives
Move @alexpeys's desk farther away

**Comment by umanwizard** [comment]
am I missing something, how is this different from the `as_tuple` parameter I added in `nonzero` ?

```python
>>> import torch
>>> x=torch.tensor([[1,2,3,4,0],[0,5,6,7,0]])
>>> x
tensor([[1, 2, 3, 4, 0],
        [0, 5, 6, 7, 0]])
>>> x.nonzero(as_tuple=True)
(tensor([0, 0, 0, 0, 1, 1, 1]), tensor([0, 1, 2, 3, 1, 2, 3]))
>>> import numpy as np
>>> x.numpy().nonzero()
(array([0, 0, 0, 0, 1, 1, 1]), array([0, 1, 2, 3, 1, 2, 3]))
>>> np.where(x.numpy())
(array([0, 0, 0, 0, 1, 1, 1]), array([0, 1, 2, 3, 1, 2, 3]))
```

**Comment by fmassa** [comment]
Yes, the request is just to dispatch to `nonzero(as_tuple=True)` when there is only a single argument to `where`.
This is very common in numpy, and I believe most people use `where` instead of `nonzero`

**Comment by umanwizard** [comment]
Ok, I should be able to do this easily

**Comment by SsnL** [comment]
fixed in https://github.com/pytorch/pytorch/pull/21986
