### ISSUE TITLE
Add torch.fill_diagonal

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#21796]
## 🚀 Feature
Implement torch.fill_diagonal based on numpy.fill_diagonal

See https://docs.scipy.org/doc/numpy/reference/generated/numpy.fill_diagonal.html

## Motivation
Alex asked me how to do this today.

## Alternatives
The following works but isn't obvious and may not work for non-strided Tensors:

```python
torch.diagonal(x).fill_(value)
```

**Comment by HsunGong** [comment]
See here for some refer https://discuss.pytorch.org/t/replace-diagonal-elements-with-vector/15311
