### ISSUE TITLE
I hope pytorch support operation tf.scatter_nd

### ISSUE THREAD

**Issue by songziqin** [pytorch/pytorch#21815]
I want to implement the deep interest network, I encounter a problem,I want to use the function that is same to  tf.scatter_nd,but pytorch do not implement. I have read the document,torch only hava scatter_,but that is different from tf.scatter_nd. So I want to know if you can  offer this op in the next release.

**Comment by fmassa** [comment]
Have a look at [`torch.index_add_`](https://pytorch.org/docs/stable/tensors.html?highlight=index_add_#torch.Tensor.index_add_), looks similar to what you are looking for.

From the TF docs:
> This operation is similar to tensor_scatter_add, except that the tensor is zero-initialized. Calling tf.scatter_nd(indices, values, shape) is identical to tensor_scatter_add(tf.zeros(shape, values.dtype), indices, values)

Also, we use GitHub issues for tracking bug reports and feature requests. Questions are better suited for the forums https://discuss.pytorch.org

**Comment by ngimel** [comment]
`index_add_` does not support all the cases that gather_nd/scatter_nd support, however, advanced indexing (for gather_nd and scatter_nd without repeating indices) and index_put_ (for scatter_nd with repeating indices) implement required functionality, though indices have to be modified compared to indices expected by tf.scatter_nd.
