### ISSUE TITLE
[doc] torch.unique's return value doc is broken

### ISSUE THREAD

**Issue by henon** [pytorch/pytorch#21822]
## 📚 Documentation
I am working on [Torch.NET](https://github.com/SciSharp/Torch.NET) which is generated from the docs. Here is another bug I noticed: https://pytorch.org/docs/stable/torch.html#torch.unique

![image](https://user-images.githubusercontent.com/44090/59552925-7fdf1d80-8f8d-11e9-8eb2-af0919e37b00.png)

unique_consecutive is OK, so the correct doc string could be copied from there:

![image](https://user-images.githubusercontent.com/44090/59552942-b7e66080-8f8d-11e9-95b6-52979a5994d1.png)

**Comment by zhangguanheng66** [comment]
@henon thanks. If you could, please submit a PR and fix it. Appreciate it.

**Comment by henon** [comment]
I'll leave it to other volunteers.
