### ISSUE TITLE
Stream safety of MAGMA functions

### ISSUE THREAD

**Issue by skrah** [pytorch/pytorch#21821]
#21785 showed that `at::svd()` is not stream-safe.  `at::svd()` uses `magma_dgesdd()`.

According to  http://icl.cs.utk.edu/magma/forum/viewtopic.php?f=2&t=1080, the old way of making MAGMA functions stream-safe is:

```
lock()
magmablasSetKernelStream( s1 )
magma_dgemm( ... )
unlock() 
```

The new way is using a `magma_queue_t`, but not all functions have it.  In particular `magma_dgesdd()` doesn't appear to have this parameter.

I'm not sure if either of these methods can be integrated into `pytorch`.  Meanwhile, the functions should probably raise an error if a non-default stream is detected.

**Comment by vishwakftw** [comment]
Another related thread: http://icl.cs.utk.edu/magma/forum/viewtopic.php?f=2&t=1034

**Comment by ngimel** [comment]
The problem is not so much with a stream safety, as with magma not setting a stream at all (e.g. the failing test is not multithreaded, so the locks in the old way that are supposed to provide stream safety under multithreaded operation are irrelevant). Rather than throwing an error on encountering non-default stream, I think it is better to synchronize default stream (on which magma would run its kernels) with the current pytorch stream. It is unfortunate that it seems to be impossible to set streams to magma kernels directly.

**Comment by vishwakftw** [comment]
For all of the batched kernels in MAGMA, a `magma_queue_t` object is taken as an argument, which is constructed using the current stream, cuBLAS and cuSparse handles. However, all MAGMA functions don’t support batching.

**Comment by ezyang** [comment]
Comments from @skrah:

> Scoped the issue and tried Natalia's suggestion, so far without success. Documentation for old-style Magma stream safety is poor. Issue seems magically fixed in some cases after port of batched_svd.

**Comment by skrah** [comment]
Yes, I just want to explain the "magically fixed" part as briefly as possible. I'm not working on `pytorch` this week so there may be some inaccuracies.

I could not replicate #21638 (i.e. the problematic test passed with cuda-memcheck and the stream tests re-enabled).

I'm not sure if @vishwakftw has taken extra steps to ensure stream safety in the `svd` port, but I didn't notice anything explicit.

So perhaps the memory allocation in

https://github.com/pytorch/pytorch/blob/896cd1c51071a13a465e3c54ef7c49abf4f1d0c0/aten/src/ATen/native/cuda/BatchLinearAlgebra.cu#L1347

provides some extra safety (I suspect that it performs an implicit synchronization) that makes the issue harder to trigger or indeed eliminates the issue.

**Comment by vishwakftw** [comment]
To echo @skrah, I didn't take care of any stream safety issues during the port, so just could have been the fact that multiple SVD calls were replaced by a single one.
