### ISSUE TITLE
  what():  another list already started (listInsert at /pytorch/torch/csrc/jit/interpreter.cpp:563)

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#21823]
What does this happen:

  what():  another list already started (listInsert at /pytorch/torch/csrc/jit/interpreter.cpp:563)

My situation is that I am training on pytorch and meanwhile try to inference on a libtorch demo. Does they can not co-exist?

**Comment by zdevito** [comment]
Hi, is it possible to post an example that causes this issue, or to post the entire error message? Thanks!

**Comment by jinfagang** [comment]
@zdevito  Same traced pt model, same c++ program, different machine on of them got this error. I can not even debug for why. I will udpate an error message when logging on to problem machine.

**Comment by suo** [comment]
Going to close this out as there has not been much activity and the issue is not reproducible. Feel free to reopen if you want us to take another look!
