### ISSUE TITLE
Mini image net, tiered image net

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#21829]
Hello,

Is it possible to add omniglot, mini imagenet and tiered imagenet datasets to torchvision.

And is it possible to upload these datasets to google drive, and share that link, so that people using google colab do not need to download these datasets. they access them directly by adding the dataset to their drives.

This would reduce the time taken to download datasets, as they would be directly available through google drive in untarred manner, making life easy.

Thanks

**Comment by vishwakftw** [comment]
Could you please open this issue in [torchvision](https://github.com/pytorch/vision)?
