### ISSUE TITLE
TorchScript segfault when using recursive custom classes

### ISSUE THREAD

**Issue by sidharthms** [pytorch/pytorch#21833]
Hi,

Following the comments in [this question](https://discuss.pytorch.org/t/is-there-support-of-recursive-custom-classes-like-tree-in-tree-lstm/47418), I was trying to create a class that has attributes of the same class type as shown below:

```
import torch
from typing import Dict, List, Optional


@torch.jit.script
class JSONValue(object):
    def __init__(self):
        self.value = torch.jit.annotate(Optional[JSONValue], None)

class TestModule(torch.jit.ScriptModule):
    @torch.jit.script_method
    def forward(self, input):
        # type: (JSONValue) -> JSONValue
        return input

m = TestModule()

m.save("test.pt")
```

But this code results in a segfault with message `Segmentation fault: 11`. 

Environment:
 - PyTorch Version: 1.2.0.dev20190615
 - OS: Mac
 - How you installed PyTorch: Conda
 - Python version: 3.6

**Comment by suo** [comment]
Hi @sidharthms, as I said on the forums, we do not currently support class types that contain themselves. https://github.com/pytorch/pytorch/pull/21842 should clarify the error msg.

**Comment by sidharthms** [comment]
Yup, thanks for the clarification!
