### ISSUE TITLE
DataParallel tests are currently broken 

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#2184]
https://github.com/pytorch/pytorch/pull/2121/commits/d69669efcfe4333c223f53249185c2e22f76ed73 has broken DataParallel tests. Now that device_ids are explicitly sent to parallel_apply, this assert https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/parallel_apply.py#L30 gets triggered if inputs are not big enough to be on all devices (e.g. batch size of 20 on 8 GPUs gets chunked into 6*3+2, so that 8-th GPU is idle, and assert gets triggered).

**Comment by soumith** [comment]
@apaszke your latest fix in https://github.com/pytorch/pytorch/pull/2193 doesn't fix this completely.

Here's a failing stack-trace:
```
FAIL: test_data_parallel_nested_output (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 1299, in test_data_parallel_nested_output
    output = dp.data_parallel(Net(), i, gpus)
  File "/data/users/soumith/pytorch/torch/nn/parallel/data_parallel.py", line 104, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, device_ids)
  File "/data/users/soumith/pytorch/torch/nn/parallel/parallel_apply.py", line 30, in parallel_apply
    assert len(modules) == len(devices)
AssertionError
```

**Comment by apaszke** [comment]
How is it possible that the tests didn't catch that in the PR?

**Comment by soumith** [comment]
it's because our build box which only has 2 GPUs doesn't hit this case. It's failing on 4-GPU setting (maybe batch size becomes too small then)
