### ISSUE TITLE
CTCLoss CUDA backward throws setStorage: storage size mismatch error

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [pytorch/pytorch#21859]
## 🐛 Bug

When running a code for (CNN + RNN model with CTCLoss) on Google Colab, I obtain following exception:

```
Traceback (most recent call last):
  File "train.py", line 469, in <module>
    train(LINES_RNN_CTC_CONFIG_2)
  File "train.py", line 245, in train
    trainer.run(train_loader, max_epochs=n_epochs)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 359, in run
    self._handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 324, in _handle_exception
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 346, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 313, in _run_once_on_dataset
    self._handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 324, in _handle_exception
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 305, in _run_once_on_dataset
    self.state.output = self._process_function(self, batch)
  File "../text_recognizer/tasks/line_prediction_ctc_task.py", line 130, in _update
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag

RuntimeError: setStorage: sizes [128, 67, 35], strides [4489, 67, 2], and storage offset 0 requiring a storage size of 574594 are out of bounds for storage with numel 574592
```

The pytorch version on google colab, where I execute GPU version, is 1.1.0

## To Reproduce

Steps to reproduce the behaviour:

Code, in which behaviour is observed, is attached
[Min.zip](https://github.com/pytorch/pytorch/files/3297672/Min.zip)
Steps to perform on google colab

Upload attached file Min.zip 
Perform the following commands in google colab:
```
!mkdir best_models
!pip install pytorch-ignite
!unzip /content/Min.zip
cd /content/training
!python train.py

```
During the execution of the script, the exception provided above is attached.

## Expected behaviour

I would expect the code to run, because it executes without problems on CPU (or, in case, when the issue is as well affecting the CPU, to throw identical exception with better explanation what is wrong)

## Environment
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 410.79
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] pytorch-ignite==0.2.0
[pip3] torch==1.1.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.3.0
[conda] Could not collect

**Comment by serhiy-yevtushenko** [comment]
I was able to localize exception as being caused by usage on torch.nn.CTCLoss (replacing torch.nn.CTCLoss with torch-baidu-ctc (and adjusting call to torch-baidu-ctc to convert tensors to CPU according  to torch-baidu-ctc requirements leads to disappearence of exception)

**Comment by serhiy-yevtushenko** [comment]
Workaround for usage of torch.nn.CTCLoss - convert all arguments during the call to CTCLoss to cpu. This allows avoiding exceptions when doing computation on GPU

**Comment by SsnL** [comment]
cc @t-vi

**Comment by t-vi** [comment]
Sounds like #20522, can you try with the nightlies, please? Thank you.

**Comment by umanwizard** [comment]
@serhiy-yevtushenko Let me know if you still have the issue with the nightly builds. If not, I can close this.

**Comment by serhiy-yevtushenko** [comment]
Unfortunately, i could not verify whether the nightly build fixes issue due to dependency of my code on torchvision, and current nightly build does not function with torchvision 0.3.0

Could you please clarify, whether there is a way to use torchvision with nightly build?

**Comment by t-vi** [comment]
The canonical way is to build torchvision from source, it's really easy (much more so than PyTorch itself).

**Comment by serhiy-yevtushenko** [comment]
I confirm that with nightly build and torchvision built from source the problem is no longer reproducible.
The issue could be closed.
Are there any timelines, when this code would get to stable version of pytorch?
