### ISSUE TITLE
[iDeep] Compile error with iDeep

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#21850]
## Bug

Got `error: expected ',' or ';' before 'vecwise_binary_op'` recently.

This is likely to be the commit causing this issue.
https://github.com/pytorch/pytorch/commit/731670f40a396b36304d8cdf0a47213042e10110

The version of iDeep in this commit does miss a `;` after lambda `auto a = [](){}`.
![image](https://user-images.githubusercontent.com/5203025/59568485-0d734980-9030-11e9-8cea-6346c0ebf421.png)

https://github.com/intel/ideep/blob/14b9dfeddd71dc431ebf3cf0ceb9a92edfd35055/include/ideep/fast_math.hpp#L278
![image](https://user-images.githubusercontent.com/5203025/59573351-6c07ea00-9067-11e9-9fd8-9fe8ef576ce3.png)

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): CentOS 7 / Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja+gcc8
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1

**Comment by umanwizard** [comment]
this should be fixed by #21854 , I will close it once that lands.

**Comment by bddppq** [comment]
Fixed in #21854

**Comment by xkszltl** [comment]
@bddppq It's broken again.
