### ISSUE TITLE
 Caffe2 - devtoolset8- depthwise3x3_conv_op_test failure

### ISSUE THREAD

**Issue by jaglinux** [pytorch/pytorch#21873]
## To Reproduce

1. Create devtoolset-8 docker image with ROCm 2.5 installed
./build.sh py2-devtoolset8-glibc2.26-rocmrpm-centos7.5
2. Run container and build Caffe2, run unit tests.

## Error message
/home/caffe2/caffe2/share/contrib/depthwise/depthwise3x3_conv_op_test.cc:145: Failure

Value of: relErr <= maxRelErr || (relErr > maxRelErr && absErr <= absErrForRelErrFailure)

  Actual: false

Expected: true

25 20 (rel err 0.2222222238779068) (0 0 0 0) running N 1 inputC 2 H 50 W 37 outputC 2 kernelH 3 kernelW 3 strideH 1 strideW 1 padT 2 padL 2 padB 2 padR 2 group 2

/home/caffe2/caffe2/share/contrib/depthwise/depthwise3x3_conv_op_test.cc:145: Failure

Value of: relErr <= maxRelErr || (relErr > maxRelErr && absErr <= absErrForRelErrFailure)

  Actual: false

Expected: true

All the sub tests fails with difference in actual and expected values.

## Additional context

1. This test is run on CPU.
2. Issue not reproducible on devtoolset-7 environment.

**Comment by gottbrath** [comment]
Discussion in bug meeting: This is just in Contrib .. so this shouldn't block forward progress. Go ahead and skip this test.

**Comment by jaglinux** [comment]
Sure, Thanks.
