### ISSUE TITLE
cmake error build failed

### ISSUE THREAD

**Issue by garimss** [pytorch/pytorch#21893]
how to solve this problem

Error log file says The system is: Windows - 10.0.17763 - AMD64

CAFFE2_ROOT=D:\pytorch\scripts\..
CMAKE_GENERATOR=Visual Studio 15 2017
CMAKE_BUILD_TYPE=Release
cmake -GNinja -DMSVC_Z7_OVERRIDE=False -DBUILDING_WITH_TORCH_LIBS=OFF -DBUILD_BINARY=False -DBUILD_CAFFE2_OPS=True -DBUILD_PYTHON=False -DBUILD_SHARED_LIBS=OFF -DBUILD_TEST=True -DCAFFE2_STATIC_LINK_CUDA=False -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=  /EHa -DCMAKE_C_FLAGS=  /EHa -DCMAKE_EXE_LINKER_FLAGS= -DCMAKE_INSTALL_PREFIX=D:\pytorch\torch -DCMAKE_PREFIX_PATH=C:\Users\Garima\Anaconda3\envs\caffe2\Lib\site-packages -DCMAKE_SHARED_LINKER_FLAGS= -DINSTALL_TEST=True -DNAMEDTENSOR_ENABLED=False -DNCCL_EXTERNAL=False -DNUMPY_INCLUDE_DIR=C:/Users/Garima/Anaconda3/envs/caffe2/lib/site-packages/numpy/core/include -DONNX_ML=True -DONNX_NAMESPACE=onnx_c2 -DPYTHON_EXECUTABLE=C:/Users/Garima/Anaconda3/envs/caffe2/python.exe -DPYTHON_INCLUDE_DIR=C:/Users/Garima/Anaconda3/envs/caffe2/include -DTHD_SO_VERSION=1 -DUSE_ASAN=False -DUSE_CUDA=False -DUSE_DISTRIBUTED=False -DUSE_FBGEMM=True -DUSE_FFMPEG=False -DUSE_LEVELDB=False -DUSE_LMDB=False -DUSE_MKLDNN=True -DUSE_NCCL=False -DUSE_NNPACK=True -DUSE_NUMPY=True -DUSE_OPENCV=False -DUSE_QNNPACK=True -DUSE_ROCM=False -DUSE_SYSTEM_EIGEN_INSTALL=OFF -DUSE_SYSTEM_NCCL=False -DUSE_TENSORRT=False -DMKLDNN_ENABLE_CONCURRENT_EXEC=ON D:\pytorch
CMake Error at C:/Users/Garima/Anaconda3/envs/caffe2/Library/share/cmake-3.14/Modules/CMakeDetermineCXXCompiler.cmake:48 (message):
  Could not find compiler set in environment variable CXX:

  cl.

Call Stack (most recent call first):
  CMakeLists.txt:11 (project)

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "D:/pytorch/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "tools\build_libtorch.py", line 23, in <module>
    rerun_cmake=True, cmake_only=False, cmake=CMake('build'))
  File "D:\pytorch\tools\build_pytorch_libs.py", line 61, in build_caffe2
    rerun_cmake)
  File "D:\pytorch\tools\setup_helpers\cmake.py", line 342, in generate
    self.run(args, env=my_env)
  File "D:\pytorch\tools\setup_helpers\cmake.py", line 110, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\Users\Garima\Anaconda3\envs\caffe2\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DMSVC_Z7_OVERRIDE=False', '-DBUILDING_WITH_TORCH_LIBS=OFF', '-DBUILD_BINARY=False', '-DBUILD_CAFFE2_OPS=True', '-DBUILD_PYTHON=False', '-DBUILD_SHARED_LIBS=OFF', '-DBUILD_TEST=True', '-DCAFFE2_STATIC_LINK_CUDA=False', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_FLAGS=  /EHa', '-DCMAKE_C_FLAGS=  /EHa', '-DCMAKE_EXE_LINKER_FLAGS=', '-DCMAKE_INSTALL_PREFIX=D:\\pytorch\\torch', '-DCMAKE_PREFIX_PATH=C:\\Users\\Garima\\Anaconda3\\envs\\caffe2\\Lib\\site-packages', '-DCMAKE_SHARED_LINKER_FLAGS=', '-DINSTALL_TEST=True', '-DNAMEDTENSOR_ENABLED=False', '-DNCCL_EXTERNAL=False', '-DNUMPY_INCLUDE_DIR=C:/Users/Garima/Anaconda3/envs/caffe2/lib/site-packages/numpy/core/include', '-DONNX_ML=True', '-DONNX_NAMESPACE=onnx_c2', '-DPYTHON_EXECUTABLE=C:/Users/Garima/Anaconda3/envs/caffe2/python.exe', '-DPYTHON_INCLUDE_DIR=C:/Users/Garima/Anaconda3/envs/caffe2/include', '-DTHD_SO_VERSION=1', '-DUSE_ASAN=False', '-DUSE_CUDA=False', '-DUSE_DISTRIBUTED=False', '-DUSE_FBGEMM=True', '-DUSE_FFMPEG=False', '-DUSE_LEVELDB=False', '-DUSE_LMDB=False', '-DUSE_MKLDNN=True', '-DUSE_NCCL=False', '-DUSE_NNPACK=True', '-DUSE_NUMPY=True', '-DUSE_OPENCV=False', '-DUSE_QNNPACK=True', '-DUSE_ROCM=False', '-DUSE_SYSTEM_EIGEN_INSTALL=OFF', '-DUSE_SYSTEM_NCCL=False', '-DUSE_TENSORRT=False', '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON', 'D:\\pytorch']' returned non-zero exit status 1
"Caffe2 building failed"

**Comment by peterjc123** [comment]
You were using Ninja but you didn't activate the environment and thus the build error. Please read this [section](https://github.com/pytorch/pytorch#install-pytorch) carefully before build.

**Comment by garimss** [comment]
hi peterjc123

I have forced ninja to off and now showing below error:
CAFFE2_ROOT=D:\pytorch\scripts\..
CMAKE_GENERATOR=Visual Studio 16 2019
CMAKE_BUILD_TYPE=Release
When you specify `CMAKE_GENERATOR_TOOLSET_VERSION`, you must also activate the vs environment of this version. Please read the notes in the build steps carefully.
"Caffe2 building failed"

**Comment by garimss** [comment]
> You were using Ninja but you didn't activate the environment and thus the build error. Please read this section carefully before build. It is also possible that the VC toolchain is not installed.

hi peterjc123
I have forced ninja to off and now showing below error:
CAFFE2_ROOT=D:\pytorch\scripts..
CMAKE_GENERATOR=Visual Studio 16 2019
CMAKE_BUILD_TYPE=Release
When you specify CMAKE_GENERATOR_TOOLSET_VERSION, you must also activate the vs environment of this version. Please read the notes in the build steps carefully.
"Caffe2 building failed"

**Comment by peterjc123** [comment]
Two options available: 
1. unset `CMAKE_GENERATOR_TOOLSET_VERSION` 
```cmd
set CMAKE_GENERATOR_TOOLSET_VERSION=
```
2. activate the env.
```cmd
set DISTUTILS_USE_SDK=1
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%
```
It is clearly written in the doc through the previous link. If it is still broken, then please check your VS installation.
