### ISSUE TITLE
cpp frontend torch::nll_loss2d memory leak

### ISSUE THREAD

**Issue by chennian32** [pytorch/pytorch#21894]
## 🐛 Bug
`torch::nll_loss2d` memory leak

When I use classification, there is no memory leak using nll_loss,But when I train with semantics segmentation, memory leaks occur when I use nll_loss2d.
## To Reproduce

1.semantics segmentation
2.torch::nll_loss2d
3.cpp frontend

```c++
model_->train();				
auto data = batch.data.to(d), targets = batch.target.to(d);	
optimizer_->zero_grad();
auto prediction = model_->forward(data);	
loss = torch::nll_loss2d(torch::log_softmax(prediction, 1), targets);
loss.backward();//If I comment on this line, there will be no memory leak
optimizer_->step();
float lossIn = loss.item<float>();
lr = optimizer_->options.learning_rate();
```

 - PyTorch Version (e.g., 1.0):1.1
 - OS (e.g., Linux):windows 10
 - How you installed PyTorch (`conda`, `pip`, source):libtorch
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:cu100
 - GPU models and configuration:cuda cudnn
 - Any other relevant information:

**Comment by chennian32** [comment]
Does anybody handle this issue?

**Comment by VitalyFedyunin** [comment]
This might take time to debug. Do you happen to have model example as well?
Are you leaking CUDA or CPU memory?

**Comment by chennian32** [comment]
`if (options.momentum_ != 0) {
				const auto dampening = iteration_ == 0 ? 1 : 1 - options.dampening_;
				auto& momentum = buffer_at(momentum_buffers, i);
				momentum = (options.momentum_ * momentum) + (dampening * update);
				if (options.nesterov_) {
					update += options.momentum_ * momentum;
				}
				else {
					update = momentum;
				}
				momentum_buffers[i]=momentum.detach_();//sgd step function If I add it here, I can't see the memory leak.
			}`

**Comment by chennian32** [comment]
the function is void torch::optim::SGD::step

**Comment by chennian32** [comment]
https://github.com/chennian32/fast_torch/blob/master/optimizer.h

**Comment by yf225** [comment]
This is likely the same issue as https://github.com/pytorch/pytorch/issues/20146. Adding `NoGradGuard guard;` before https://github.com/pytorch/pytorch/blob/1a164bf30bc82a0476520f39eb0bcbe31a2b9f02/torch/csrc/api/src/optim/sgd.cpp#L29 should fix this issue.

**Comment by yf225** [comment]
This is fixed by https://github.com/pytorch/pytorch/pull/23007.
