### ISSUE TITLE
bug? dataloader causes mutliple global prints

### ISSUE THREAD

**Issue by ntatsisk** [pytorch/pytorch#21903]
## 🐛 Bug

I am new to pytorch and so I am not sure if it is an actual bug or a normal thing. However, when I have a print statement outside of any function and I iterate over a Dataloader then the print statement is invoked multiple times. 

## To Reproduce
```
import torch
import torchvision
import torchvision.transforms as transforms

print("Hello World!")

def main():
    transform = transforms.ToTensor() 
    trainset = torchvision.datasets.MNIST(root='./data/', train=True,
                                          download=True, transform=transform)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=64,
                                                     shuffle=True, num_workers=4)
    for i, data in enumerate(trainloader):
        pass

if __name__ == '__main__':
    main()

```

The output:

```
Hellow World!
Hellow World!
Hellow World!Hellow World!

Hellow World!
```

## Expected behavior

The print statement should be invoked only once.

## Environment
 - PyTorch Version 1.1.0
 - Windows 10
 - Conda installation
 - Python 3.7
 - CUDA 10.0
 - GPU Quadro K1200

**Comment by SsnL** [comment]
not a bug, you are on windows so be aware of the default `spawn` start method executes the script again.
