### ISSUE TITLE
ONNX export of `nn.LSTMCell` on CUDA device fails on `_thnn_fused_lstm_cell`

### ISSUE THREAD

**Issue by NikitaSemenov** [pytorch/pytorch#21909]
## 🐛 Bug
When i trying to export my taco2 model to onnx i got this error.
How can i add symbolic and where i can do it? 
 UserWarning: ONNX export failed on ATen operator _thnn_fused_lstm_cell because torch.onnx.symbolic._thnn_fused_lstm_cell does not exist

## To Reproduce

1. cloned nvidia/Tacotron2 repo https://github.com/NVIDIA/tacotron2
1. create export script
```python
    hparams = create_hparams()
    hparams.sampling_rate = 22050
    checkpoint_path = "checkpoint_21500"
    model = load_model(hparams)
    model.load_state_dict(torch.load(checkpoint_path)['state_dict'])
    model.eval()
    model.cuda()

    text_inputs = torch.ones(2, 100, device='cuda').long()
    text_legths = torch.ones(2, device='cuda').long()
    mels = torch.randn(2, 80, 851, device='cuda')
    max_len = torch.FloatTensor(100)
    output_lengths = torch.ones(2, device='cuda').long()
    dummy_input = [text_inputs, text_legths, mels, max_len, output_lengths]
    input_names = ['actual_input']
    output_names = ["output1"]

    torch.onnx.export(model, dummy_input, "taco.onnx", verbose=True, input_names=input_names,
                      output_names=output_names)
```

3. get error
```
Traceback (most recent call last):
  File "/home/nikita/repos/нагрузка/ttsNero/app/export_onnx.py", line 40, in <module>
    output_names=output_names)
  File "/home/nikita/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/home/nikita/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "/home/nikita/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/home/nikita/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 278, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/home/nikita/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/nikita/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 48, in _run_symbolic_function
    def _run_symbolic_function(*args, **kwargs):
```
## Environment

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source):  pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0 
 - GPU models and configuration: 1060 gtx
 - Any other relevant information:

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by ThisIsIsaac** [comment]
ping!

**Comment by borisfom** [comment]
ping!

**Comment by suo** [comment]
Hi sorry, looks like this slipped through the cracks 😢. I'll take a look today.

**Comment by houseroad** [comment]
Seems the onnx symbolic is missing for this aten function. @lara-hdr @BowenBao @neginraoof could someone please take a look?

**Comment by atanx** [comment]
ping!  someone please take a look?

**Comment by anasvaf** [comment]
any updates regarding this issue?

**Comment by Akshaysharma29** [comment]
any updates or any suggestion?

**Comment by spandantiwari** [comment]
@suo - We have some high-priority items that the team is working on, but we will take a look as soon as we have some cycles.
@NikitaSemenov @Akshaysharma29 - would it be possible for you to use `torch.nn.LSTM` or `torch.nn.GRU` for your scenario? They are supported in the exporter today.

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
