### ISSUE TITLE
Downloading 3rd party packages

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#21907]
Although I have recursively downloaded pytorch via `git clone --recursive https://github.com/pytorch/pytorch`, by running `python3 setup.py install` it goes to download some third party packages.
How can I fully download the source code from internet and then build it without internet connection?

**Comment by xuhdev** [comment]
I don't think it would download anything if all dependencies are met.

**Comment by VitalyFedyunin** [comment]
You can also do `git submodule update --init --recursive` just to be sure

Also, please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
