### ISSUE TITLE
Module to device can not move function list to device.

### ISSUE THREAD

**Issue by Windaway** [pytorch/pytorch#21905]
## 🐛 Bug

if i define a function list like below in a module,  and use to device. 

        for x in range(layn):
            temp1=nn.Linear(input_size, 3 * hidden_size, bias=self.bias)
            temp2=nn.Linear(hidden_size, 3 * hidden_size, bias=self.bias).to("cuda:0" )
            self.x2h.append(temp1)
            self.h2h.append(temp2)

then self.x2h.weight cannot be moved to device.

 - PyTorch Version (e.g., 1.0): 1.1
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0 7.5.1

**Comment by SsnL** [comment]
use nn.ModuleList
