### ISSUE TITLE
Any way to install Windows build without conda.

### ISSUE THREAD

**Issue by DakshMiglani** [pytorch/pytorch#2192]
I tried installing it using peterjc123's conda repo but download is so slow that it gets to 1kb/s and doesn't download. I'm on a 50mbps connection still this happened. I tried using tar.bz2 file but it gave uncompressing errors. So I was wondering if I can do it manually by cloning or something? 
Let me know.

**Comment by soumith** [comment]
you can try asking on the windows thread, that's prob the best place where the windows devs hang.
