### ISSUE TITLE
Bug in saving indexed torch tensors makes it much slower than numpy.

### ISSUE THREAD

**Issue by Spandan-Madan** [pytorch/pytorch#21926]
## 🐛 Bug

I am indexing tensors and storing each element of the batch separately so that they can be read individually from disk. The output of the model is a tensor of size (40,100,256,256). When I index one element from it and store the (100,256,256) dimensional tensor using torch.save() it takes the exact same time as it takes to save the whole (40,100,256,256) object.

On the other hand, if I do a .numpy() and do the same process in numpy it is much faster.

May be some thing to do with how torch handles indexed sub-tensors. Is it a separate object, or the same one? 

Dummy code below reproduces the issue with PyTorch 1.0.1.

## To Reproduce
```
import time
import torch
import numpy as np

a = torch.rand((40,100,256,256))
b = np.ones((40,100,256,256))
c = a.cpu()

t1 = time.time()
torch.save(a[0],open('torch1.p','wb'))
t2 = time.time()
print(t2 - t1)

a = a.cuda()
torch.save(a[0],open('torch2.p','wb'))
t3 = time.time()
print(t3 - t2)

np.save(open('numpy1.p','wb'),c[0])
t4 = time.time()
print(t4 - t3)

np.save(open('numpy2.p','wb'),b[0])
t5= time.time()
print(t5 - t4)
```

## Expected behavior
I'd expect torch and numpy to not be SO different.

## Environment
PyTorch version: 1.0.1
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 14.04.6 LTS
GCC version: (GCC) 5.2.0
CMake version: version 3.10.20171205-gd06b8

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl_fft                   1.0.10           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.0.1           cuda100py36he554f03_0  
[conda] torchfile                 0.1.0                     <pip>
[conda] torchnet                  0.0.4                     <pip>
[conda] torchvision               0.2.1                    py36_0

## Additional context

Saving indexed sub-tensors can be important when storing features of images etc. Due to large dataset sizes, things are usually done in batches, but it may be important to extract each element out of the batch it was processed in.

**Comment by soumith** [comment]
this is not a bug, it's actually by design.

when you index individual elements into a Tensor, then you are holding a view into the original Tensor.

```
a = torch.randn(10, 20)
b = a[0]
b.add_(10) # changes `a`
```

If you actually do `torch.save([a, b], 'foo.pt')` then PyTorch makes sure that this "view" property is actually preserved across serialization / deserialization.
So, 

```
a = torch.randn(10, 20)
b = a[0]
b.add_(10) # changes `a`

torch.save((a, b), 'foo.pt')
a, b = torch.save('foo.pt')

b.add_(10) # still changes `a`
```

So, what you are seeing is that even when you are indexing, the whole original Storage is saved.

You can make pytorch only save the particular element with `torch.save(a[0].clone()`

**Comment by Spandan-Madan** [comment]
Interesting, what was the reason behind doing this?

Thanks,
Spandan

**Comment by soumith** [comment]
if you do a `torch.save(my_model, ...)` where your model has parameters that are views, or if you do `torch.save([my_model, my_optimizer], ...)`, when you load the model back, you want the preserving property that these both continue to work as expected

**Comment by Spandan-Madan** [comment]
Thanks!
