### ISSUE TITLE
how to use mkl-dnn after installing by conda?

### ISSUE THREAD

**Issue by HITerStudy** [pytorch/pytorch#21945]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
how to use mkl-dnn after installing by conda "conda install mkl-dnn"? And I don`t know what to do in the next step for using mkl-dnn on the pytorch?

**Comment by mrshenli** [comment]
If you build PyTorch with MKLDNN [enabled](https://github.com/pytorch/pytorch/blob/0408697317de6146ed9e5445faaeab49828310b1/setup.py#L45), you can then create MKLDNN tensors by `tensor.to_mkldnn()`. And, operations like [linear](https://github.com/pytorch/pytorch/blob/0408697317de6146ed9e5445faaeab49828310b1/aten/src/ATen/native/Linear.cpp#L15) would automatically use mkldnn.

I am closing this issue, but please feel free to post followup questions in the [forum](https://discuss.pytorch.org/).
