### ISSUE TITLE
Getting 1 as an ouput on running torch.cuda.device_count() but still able to pass 2 as an argument in torch.cuda.device()

### ISSUE THREAD

**Issue by anubhav1772** [pytorch/pytorch#21948]
## 📚 Documentation

Hi,
When I ran `torch.cuda.device_count()`, I got `1` in output but still able to pass` 2`(which is greater than device count) as an argument in the `torch.cuda.device()` method. The documentation here says its a `context-manager` that changes the selected device but I have just `1` cuda device available, i.e., `cuda:0`. Then, why am I not getting any error when I passed `2` as an argument in `torch.cuda.device()`?

```
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())
x = torch.cuda.device(2)
print(x)
print(x.idx)
```
output:

```
True
1
<torch.cuda.device object at 0x000001873064F2B0>
2
```
And, what does `torch.cuda.device(device).idx` means? It’s value is same as what I am inputting as an argument in `torch.cuda.device()`.

**My thoughts:** `torch.cuda.device(device)` is a `context-manager` that facilitates the proper handling of resources, i.e., automatic setup and release of resources after usage. So, the argument you are passing in this function doesn't mean you are switching/setting to that device. In order to set current device, you should use `torch.cuda.set_device(device)` or `CUDA_VISIBLE_DEVICES `environmental variable as per the official documentation.

Please, help me undestand this. Thanks!

**Comment by VitalyFedyunin** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
