### ISSUE TITLE
CUDA error (10): invalid device ordinal

### ISSUE THREAD

**Issue by Usmaniatech** [pytorch/pytorch#21955]
I am using cuda to work on MADDPG and it gives following error:

> CUDA error (10): invalid device ordinal

I am using:

> device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
> #device = "cpu"

to train on cuda. but i get the error.

I have checked:

> torch.cuda.device_count()
> 1
> 
> torch.cuda.is_available()
> True
> 
> torch.cuda.current_device()
> 0

**Comment by mrshenli** [comment]
Hi @Usmaniatech, can you share the call stack to that error and steps to reproduce?

**Comment by mrshenli** [comment]
Same error was reported in #21954

**Comment by soumith** [comment]
please reopen the issue (or file a new issue) by following our bug-report template (or pick a different template).

There's not enough info in this issue to understand why the problem shows up or what pytorch version and os you are using

**Comment by Usmaniatech** [comment]
I am running this file
https://github.com/kotogasy/unity-ml-tennis/blob/master/Multi%20Agent%20Deep%20Deterministic%20Policy%20Gradient.ipynb

Instead of

**Comment by JunaidRana** [comment]
i also have the same error.
My insllation pkgs are

Torch 0.4.0
tensorflow-gpu 1.7.1
cuda 9.0
cudnn 7.0.5

Torch is connected with CUDA and Tensorflow is also built with cuda.

**Comment by Usmaniatech** [comment]
Unityagents support protobuf==3.5.2 and unity mlagents supports protobuf>=3.6,<3.7
I require both unityagents and mlagents. How do I fix this
