### ISSUE TITLE
Non-root installation

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#21966]
I want to install pytorch for a user. However, the default `python3 setup.py install` seems to require root access.
```
creating /usr/local/lib/python3.6/dist-packages/torch
error: could not create '/usr/local/lib/python3.6/dist-packages/torch': Permission denied
```
How can I do that?

**Comment by zou3519** [comment]
Please ask questions over at our forums in the future: https://discuss.pytorch.org/

You can create a python virtual environment that lives in a local directory that you have permission to write to. Then, install PyTorch in said virtual environment. See https://docs.python.org/3/tutorial/venv.html for more details.
