### ISSUE TITLE
CuDNN CTC implementation ignores grad_out completely

### ISSUE THREAD

**Issue by zh217** [pytorch/pytorch#21961]
## 🐛 Bug

Say we have

```python
import torch

loss_fn = torch.nn.CTCLoss(reduction='none')
inp = torch.randn(10, 2, 10)
tar = torch.randint(10, (4,))
inp_len = torch.full((2,), 10, dtype=torch.long)
tar_len = torch.full((2,), 2, dtype=torch.long)
```

When grad_out are all 1, everything is OK:
```python
inp_cpu = inp.clone().detach()
inp_cpu.requires_grad = True
loss_fn(inp_cpu, tar, inp_len, tar_len).sum().backward()
print(inp_cpu.grad.abs().sum().item())

inp_cudnn = inp.cuda().detach()
inp_cudnn.requires_grad = True
loss_fn(inp_cudnn, tar.cuda(), inp_len.cuda(), tar_len.cuda()).sum().backward()
print(inp_cpu.grad.abs().sum().item())
```

this prints
```
316.4911193847656
316.4911193847656
```

But now let's try to make grad_out 0.5:

```python
inp_cudnn = inp.cuda().detach()
inp_cudnn.requires_grad = True
loss_fn(inp_cudnn, tar.cuda(), inp_len.cuda(), tar_len.cuda()).sum().backward()
print(inp_cpu.grad.abs().sum().item())

inp_cpu = inp.clone().detach()
inp_cpu.requires_grad = True
loss_fn(inp_cpu, tar, inp_len, tar_len).mean().backward()
print(inp_cpu.grad.abs().sum().item())
```

Note the `.mean()` instead of `.sum()`. Now the result is:
```
316.4911193847656
158.2455596923828
```

The CuDNN implementation gives wrong result.

**Comment by zh217** [comment]
Due to the way CuDNN is implemented, it may be impossible to cater for the case of

```python
loss = (loss_by_sample * sample_weight).sum()
loss.backward()
```

But at least we should tell the user that.

**Comment by t-vi** [comment]
We should fix it...

**Comment by siddalmia** [comment]
Hi @zh217 , 

Is there a mistake in your code for the mean part of cudnn? You seem to not have used `mean()` but used `sum()` instead.
 
> But now let's try to make grad_out 0.5:
> 
> ```python
> inp_cudnn = inp.cuda().detach()
> inp_cudnn.requires_grad = True
> loss_fn(inp_cudnn, tar.cuda(), inp_len.cuda(), tar_len.cuda()).sum().backward()
> print(inp_cpu.grad.abs().sum().item())
> 
> inp_cpu = inp.clone().detach()
> inp_cpu.requires_grad = True
> loss_fn(inp_cpu, tar, inp_len, tar_len).mean().backward()
> print(inp_cpu.grad.abs().sum().item())
> ```
> 
> Note the `.mean()` instead of `.sum()`. Now the result is:
> 
> ```
> 316.4911193847656
> 158.2455596923828
> ```
> 
> The CuDNN implementation gives wrong result.

**Comment by zh217** [comment]
You are right, the code was wrong, thanks.  But the output is the same even if you fix it -- so the issue is still valid.

The second part should be

```python
inp_cudnn = inp.cuda().detach()
inp_cudnn.requires_grad = True
loss_fn(inp_cudnn, tar.cuda(), inp_len.cuda(), tar_len.cuda()).mean().backward()
print(inp_cpu.grad.abs().sum().item())

inp_cpu = inp.clone().detach()
inp_cpu.requires_grad = True
loss_fn(inp_cpu, tar, inp_len, tar_len).mean().backward()
print(inp_cpu.grad.abs().sum().item())
```

**Comment by zh217** [comment]
It seems that I was doing things wrong, there is actually no problem in this case.
