### ISSUE TITLE
Implement covariance_matrix for Independent distributions

### ISSUE THREAD

**Issue by justindomke** [pytorch/pytorch#21971]
## 🚀 Feature
For distributions created by calling `torch.distributions.Independent`, support `covariance_matrix`

## Motivation

This will make it easier to treat multivariate distributions in a uniform way. Of course, this covariance matrix will just be a diagonal of the variance of (batched) distribution that was used to create the Independent distribution.

## Pitch

I think the implementation is just something like the following. (I guess this only works when `reinterpreted_batch_ndims==1`.)

```python
@lazy_property
def covariance_matrix(self):
    return tt.diag(self.base_dist.variance))
```

**Comment by vishwakftw** [comment]
cc: @fritzo

**Comment by fritzo** [comment]
Hmm `Independent` makes sense for both discrete and continuous distributions, e.g. `Independent(Categorical(...))`. I guess if neither `.covariance_matrix` nor `.variance` are defined for the base distribution, then this will raise a `NotImplementedError`?

Additionally there may be multiple independent dimensions, and I'm not sure what data structure should hold a general covariance tensor? Is the `event_shape+event_shape`-shaped covariance-tensor concept at used anywhere else in PyTorch?

**Comment by justindomke** [comment]
I think it would be fine to throw `NotImplementedError` unless `parent_dist` has an `event_shape` of `[]` or perhaps just a single dimension.

It seems like the current design of `Distributions` isn't really intended for arbitrarily complex joint distributions, so doing this "right" in the general case would probably involve some significant design? I reckon most of the value here is probably in the "easy" cases for now, anyway.

**Comment by fritzo** [comment]
Ok, that sounds reasonable, especially to make `Independent(Normal(...))` more palatable. How about this version:
```py
@lazy_property
def covariance_matrix(self):
    if self.reinterpreted_batch_ndims == 0:
        return self.base_dist.covariance_matrix
    if self.reinterpreted_batch_ndims == 1 and self.base_dist.event_shape == ():
        return tt.diag(self.base_dist.variance)
    raise NotImplementedError
```

**Comment by justindomke** [comment]
It would be nice to handle the case where `batch_dims` is arbitrary. For example, I can do the following using `MultivariateNormal`:

```python
>>mu  = tt.zeros(3,2)
>>Cov = tt.eye(2).unsqueeze(0).repeat(3,1,1)
>>d = tt.distributions.MultivariateNormal(mu,Cov)
>>d.covariance_matrix
tensor([[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]])
```

It seems like this wouldn't work with the above implementation? I'm not quite sure how to fix this, though... the problem is that I don't know of a nice syntax for creating a "batch" of diagonal matrices in PyTorch.

**Comment by fritzo** [comment]
@fehiepsi showed me this trick for batch-compatible `torch.diag()` (I think that's what you're asking for, @justindomke )
```py
def batch_diag(batched_variance):
    batch_shape = batched_variance.shape[:-1]
    event_size = batched_variance.size(-1)
    cov = batched_variance.new_zeros(batch_shape + (event_size * event_size,))
    cov[..., ::1 + event_size] = batched_variance
    return cov.reshape(batch_shape + (event_size, event_size))
```

**Comment by VitalyFedyunin** [comment]
@justindomke can we close this one?

**Comment by justindomke** [comment]
Certainly (in fact I'll do it for you). Thanks very much!
