### ISSUE TITLE
PyTorch should provide CUDA 9.2 binaries.

### ISSUE THREAD

**Issue by umanwizard** [pytorch/pytorch#21973]
Currently, the only 9.x series CUDA that we target in our distributed binaries is 9.0.

It would be better to ship a CUDA 9.2 version of PyTorch instead, since, according to Nvidia, it has various bugfixes and improvements.

**Comment by SsnL** [comment]
Out of curiosity, I know that we have `magma-cuda92`, which is great and useful for building this binary. But where does it come from? I am not able to find it in pytorch/builder. 

I'm asking since I have long been hoping for a `magma-cuda101` (https://github.com/pytorch/pytorch/issues/20103)

**Comment by soumith** [comment]
i built it locally and pushed. `magma-cuda101` can happen, i have to build the docker image for CUDA 10.1 which I was lazy to do (so many other backlog binary tasks).
If you push a magma-cuda101 recipe and build the conda binary, i am happy to push it upstream to the pytorch channel

**Comment by GengDavid** [comment]
Hi, @soumith. The PyTorch 1.1-cu90 binary is not compatible with cu9.2 when I have some customized OPs. I also think providing an official PyTorch 1.1-cu92 binary is necessary.

**Comment by soumith** [comment]
@GengDavid can you move to CUDA 10? Soon CUDA11 will come at some point, at which point we will remove CUDA9 builds

**Comment by GengDavid** [comment]
Got it. Thanks.

**Comment by SsnL** [comment]
Marking this as resolved for now. Feel free to reopen if you have further questions.
