### ISSUE TITLE
pip doesn't seem to detect pytorch1.2.0dev on CUDA 10

### ISSUE THREAD

**Issue by MiroFurtado** [pytorch/pytorch#21980]
## 🐛 Bug

When running a docker container from pytorch/pytorch like pytorch/pytorch:pytorch/pytorch:nightly-devel-cuda10.0-cudnn7, pip does not seem to detect the pytorch binary and will install over it if you try to install any other package.

## To Reproduce

1. Pull the docker image `pytorch/pytorch:pytorch/pytorch:nightly-devel-cuda10.0-cudnn7` and get a shell
2. run `python -c 'import torch; print(torch.__version__)'` and see 1.2.0dev
3. run something like `pip install pytorch-pretrained-bert`  (depends on pytorch>=0.4)
4. run `python -c 'import torch; print(torch.__version__)'` again and see 1.1.0

**Comment by mrshenli** [comment]
Hi @yf225, are you familiar with this?

**Comment by yf225** [comment]
@MiroFurtado The best way to solve this problem is to run the following:
```
pip install tqdm boto3 requests regex  # Depedencies based on https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/requirements.txt
pip install pytorch-pretrained-bert --no-deps
```
If we do it this way, all other dependencies of `pytorch-pretrained-bert` are installed except `torch`, and `torch_nightly` from the nightly docker image is used.
