### ISSUE TITLE
Builing for a specific SM number

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#22018]
I would like to install PyTorch from source for a specific sm number. I mean the nvcc options. I don't want to use the default settings which use multiple sm and arch numbers.

As I grep, I also see many such options in the third party packages. Is there any way to force all of them to use my sm number? For example, some thing like `python setup.py -gencode=sm_52 install`

**Comment by soumith** [comment]
Yes. By example:
```
TORCH_CUDA_ARCH_LIST="5.2;6.1;7.0" python setup.py install
```
