### ISSUE TITLE
MSVC Warning C4834 in ATen

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#22053]
## Bug

Got this warning when used caffe2 in our application.

```
aten\core\list_inl.h(112): warning C4834: discarding return value of function with 'nodiscard' attribute
```

![image](https://user-images.githubusercontent.com/5203025/59891972-1e072500-938c-11e9-9d04-3cbb8f13c898.png)

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Win10
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): vs2017

**Comment by xuhdev** [comment]
Does #22061 fix the issue for you?

**Comment by xkszltl** [comment]
Thanks.
Looks like it will. I can have a try tomorrow.
