### ISSUE TITLE
CI failure points to nonexistent code...

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#22052]
This has to be the weirdest CI failure I have seen. On #22043 , a PR filed today, one of the CI test run fails with
```
Jun 21 00:31:06 ======================================================================
Jun 21 00:31:06 ERROR: test_clip_grad_norm (__main__.TestNN)
Jun 21 00:31:06 ----------------------------------------------------------------------
Jun 21 00:31:06 Traceback (most recent call last):
Jun 21 00:31:06   File "test_nn.py", line 1830, in test_clip_grad_norm
Jun 21 00:31:06     norm = clip_grad_norm_(l.parameters(), max_norm, norm_type=norm_type)
Jun 21 00:31:06   File "/opt/conda/lib/python3.6/site-packages/torch/nn/utils/clip_grad.py", line 36, in clip_grad_norm_
Jun 21 00:31:06     clip_coef = torch.tensor(max_norm, device=device) / (total_norm + 1e-6)
Jun 21 00:31:06 UnboundLocalError: local variable 'device' referenced before assignment
Jun 21 00:31:06 
```

The PR doesn't touch this line. And this line of code printed in error trace
```
clip_coef = torch.tensor(max_norm, device=device) / (total_norm + 1e-6
```
does not even match what the line is on master, which is 
https://github.com/pytorch/pytorch/blob/d4119f8fcbde15569b8f2993973439f2961ea22a/torch/nn/utils/clip_grad.py#L35
and is 2 years old.
The latest update to that file `clip_grad.py` is on March 1st, and doesn't even touch this line. 

Here is link to the build: https://circleci.com/gh/pytorch/pytorch/2043106?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Any ideas why?  @ezyang @yf225 

Hmm, commit hash collision?

**Comment by ezyang** [comment]
The usual explanation is that somewhere, somehow in our CI, we installed
another copy of PyTorch (the last time this happened, it was because of
the torchvision install).

Excerpts from Tongzhou Wang's message of 2019-06-20 18:08:56 -0700:
> This has to be the weirdest CI failure I have seen. On #22043 , a PR filed today, one of the CI test run fails with
> ```
> Jun 21 00:31:06 ======================================================================
> Jun 21 00:31:06 ERROR: test_clip_grad_norm (__main__.TestNN)
> Jun 21 00:31:06 ----------------------------------------------------------------------
> Jun 21 00:31:06 Traceback (most recent call last):
> Jun 21 00:31:06   File "test_nn.py", line 1830, in test_clip_grad_norm
> Jun 21 00:31:06     norm = clip_grad_norm_(l.parameters(), max_norm, norm_type=norm_type)
> Jun 21 00:31:06   File "/opt/conda/lib/python3.6/site-packages/torch/nn/utils/clip_grad.py", line 36, in clip_grad_norm_
> Jun 21 00:31:06     clip_coef = torch.tensor(max_norm, device=device) / (total_norm + 1e-6)
> Jun 21 00:31:06 UnboundLocalError: local variable 'device' referenced before assignment
> Jun 21 00:31:06 
> ```
> 
> The PR doesn't touch this line. And this line of code does not even match what is on master
> ```
> clip_coef = torch.tensor(max_norm, device=device) / (total_norm + 1e-6
> ```
> and the latest update to that file `clip_grad.py` is on March 1st, and doesn't even touch this line. 
> 
> Here is link to the build: https://circleci.com/gh/pytorch/pytorch/2043106?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> 
> Any ideas why?  @ezyang @yf225 
>

**Comment by SsnL** [comment]
@ezyang I had thought about that possibility. Yet none of the commits that touched that file has a line similar to the one in the trace. So I doubt it comes from an accidentally installed release.

**Comment by SsnL** [comment]
Also happened on master https://circleci.com/gh/pytorch/pytorch/2046711?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

**Comment by SsnL** [comment]
Happened again https://circleci.com/gh/pytorch/pytorch/2110112?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SsnL** [comment]
I'm lost... I checked all branches and tags existing on pytorch/pytorch. None of them contains this line.

**Comment by SsnL** [comment]
It is always `pytorch_linux_trusty_py3_6_gcc5_4` build

**Comment by xuhdev** [comment]
Perhaps we can have PyTorch version printed before running tests?

**Comment by ezyang** [comment]
Happened again at https://circleci.com/gh/pytorch/pytorch/2167985?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by vishwakftw** [comment]
Happened again here: https://circleci.com/gh/pytorch/pytorch/2210078?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by rgommers** [comment]
> It is always `pytorch_linux_trusty_py3_6_gcc5_4` build

From https://github.com/pytorch/ossci-job-dsl#cheat-sheet:
_Search for DOCKER_IMAGE: line at the top of the Test phase; it should have a line like 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.6-gcc5.4:tmp-173-5910; this is your docker image. (If the tag is tmp-###-####, it comes with a build of your source; if it's ### that's the stock image.)_

From the CircleCI logs:
```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.6-gcc5.4:300-eebcd1649e8f66ea28c803fa41abf2cc7559fc79
```
The commit (in this case `eebcd164`) changes per failure, and is the correct one (the commit is in the PR that triggered the CI run). So that all seems correct.

Here's a hypothesis: 

- 2 days before these occasional failures started to happen, #21928 was opened.
- it deletes all CI jobs except the `pytorch_linux_trusty_py3_6_gcc5_4` one that's the problem here. 
- it also deletes an `ensure_consistency.py` script, and it uses the `persist_to_workspace` CircleCI feature to persist `pytorch_linux_trusty_py3_6_gcc5_4_build` between jobs.
- that persists the Docker image that is used in the failing runs (`308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.6-gcc5.4:300`) for ~30 days

And after I wrote the above, here a second (probably better) one:

The failing line is mysterious because it's not in this repo. XLA patches the code in this repo to introduce it: https://github.com/pytorch/xla/blob/master/torch_patches/X10-clip_grad.diff#L23

The `pytorch_linux_trusty_py3_6_gcc5_4` job has an XLA variant. So these jobs somehow get confused.

**Comment by rgommers** [comment]
#20930 recently changed how the XLA jobs get run, and persisting them via `~/workspace`. Hope these hints trigger someone.

**Comment by soumith** [comment]
cc: @kostmo

**Comment by ezyang** [comment]
That is very good sleuthing.  I bet it definitely has to do with XLA.

Excerpts from Ralf Gommers's message of 2019-07-22 23:38:45 -0700:
> > It is always `pytorch_linux_trusty_py3_6_gcc5_4` build
> 
> From https://github.com/pytorch/ossci-job-dsl#cheat-sheet:
> _Search for DOCKER_IMAGE: line at the top of the Test phase; it should have a line like 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.6-gcc5.4:tmp-173-5910; this is your docker image. (If the tag is tmp-###-####, it comes with a build of your source; if it's ### that's the stock image.)_
> 
> From the CircleCI logs:
> ```
> DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.6-gcc5.4:300-eebcd1649e8f66ea28c803fa41abf2cc7559fc79
> ```
> The commit (in this case `eebcd164`) changes per failure, and is the correct one (the commit is in the PR that triggered the CI run). So that all seems correct.
> 
> Here's a hypothesis: 
> 
> - 2 days before these occasional failures started to happen, #21928 was opened.
> - it deletes all CI jobs except the `pytorch_linux_trusty_py3_6_gcc5_4` one that's the problem here. 
> - it also deletes an `ensure_consistency.py` script, and it uses the `persist_to_workspace` CircleCI feature to persist `pytorch_linux_trusty_py3_6_gcc5_4_build` between jobs.
> - that persists the Docker image that is used in the failing runs (`308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.6-gcc5.4:300`) for ~30 days
> 
> And after I wrote the above, here a second (probably better) one:
> 
> The failing line is mysterious because it's not in this repo. XLA patches the code in this repo to introduce it: https://github.com/pytorch/xla/blob/master/torch_patches/X10-clip_grad.diff#L23
> 
> The `pytorch_linux_trusty_py3_6_gcc5_4` job has an XLA variant. So these jobs somehow get confused.
>

**Comment by zou3519** [comment]
https://github.com/pytorch/pytorch/pull/23304 should solve this (thanks for pointing it out, @bddppq

**Comment by SsnL** [comment]
fixed via https://github.com/pytorch/pytorch/pull/23304 by @zou3519  :D

**Comment by pietern** [comment]
Also see pytorch/xla#848 for the culprit.
