### ISSUE TITLE
pytorch 1.1 on Anaconda

### ISSUE THREAD

**Issue by SaschaStenger** [pytorch/pytorch#22067]
## 📚 Documentation

Regarding the installation info in the
[https://pytorch.org/get-started/locally/#anaconda]( https://pytorch.org/get-started/locally/#anaconda )
The version of pytorch, that is supposed to install with the given command:
`conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`
is supposed to be pytorch 1.1, but it does install 1.0

**Comment by peterjc123** [comment]
What is the result of `conda info`?

**Comment by SaschaStenger** [comment]
active environment : Thesis
    active env location : C:\ProgramData\Anaconda3\envs\Thesis
            shell level : 2
       user config file : C:\Users\sasch\.condarc
 populated config files : C:\Users\sasch\.condarc
          conda version : 4.6.14
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\sasch\.conda\pkgs
                          C:\Users\sasch\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\sasch\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\sasch\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

**Comment by peterjc123** [comment]
I cannot reproduce it on my side. Would you please clean the cache first? Please do `conda clean -t` first and try again.

**Comment by SaschaStenger** [comment]
I can't reproduce it anymore either. Might have been a cache issue. Sorry for the false alarm
