### ISSUE TITLE
Add method to allocate uninitialized pinned memory

### ISSUE THREAD

**Issue by kazimuth** [pytorch/pytorch#2206]
If you call:
```
torch.Storage(512).pin_memory()
```
pinned memory will be allocated, and then have your uninitialized tensor copied into it, which is unnecessary.

It's possible to to directly allocate pinned memory using:

```
torch.Storage(512, allocator=torch.cuda._host_allocator())
```

But it would be nice if there was a stable method to call that did this, maybe similar to [`Storage.from_file()`](http://pytorch.org/docs/master/storage.html#torch.FloatStorage.from_file). Maybe `Storage.pinned()`? Or `Storage(512, pinned=True)`?

I'd be happy to implement this if I'm told what the API should look like.

**Comment by apaszke** [comment]
How about `Storage.new_pinned`?

**Comment by soumith** [comment]
@kazimuth does `Storage.new_pinned` work for you to implement this? We're definitely green-lighting your proposal.

**Comment by JesseTG** [comment]
Is anyone working on this?  If not, I can give it a go.  This is a matter of adding a `Storage.new_pinned` function and adding some `pinned` flags to functions that generate `Tensor`s, right?

**Comment by JesseTG** [comment]
@soumith @apaszke Thoughts?  Is what I described the general shape of it?

**Comment by zou3519** [comment]
cc @ezyang @colesbury should we go ahead with @JesseTG's implementation?

**Comment by colesbury** [comment]
Yes, I think we want this functionality, but I think we should add it as a Tensor factory argument instead of to the Storage API. For example:

```
torch.empty(shape, pinned_memory=True)
```

In C++, it could be part of TensorOptions.

In the future, we will probably want to do the same thing for shared memory allocations.

@gchanan

**Comment by colesbury** [comment]
The context is that since the original post, we've been moving away from Tensor and Storage constructors in favor of the factory methods.

**Comment by JesseTG** [comment]
Ok, I will work on this over the weekend.

**Comment by ezyang** [comment]
I don't think anyone is actively working on it, but we'd be happy to accept it. Sam's proposed interface might be a bit involved though, because both TensorOptions and our options argument parsing would need to be adjusted to handle this properly.

**Comment by VitalyFedyunin** [comment]
Seems to be required to remove Storage.

**Comment by VitalyFedyunin** [comment]
I will take care of creating appropriate bootcamp task.

**Comment by VitalyFedyunin** [comment]
Going to be done in #18455
