### ISSUE TITLE
thrift with libtorch will generate Segmentation fault 

### ISSUE THREAD

**Issue by chinafei** [pytorch/pytorch#22068]
## To Reproduce

1.if program use thrift and  dependent on libtorch ,it will generate segmentation fault ,event no code with libtorch in program.
2. if CMakeList like :
   target_link_libraries(demo_server ${TORCH_LIBRARIES} thrift).
 Program will generate segmentation fault.  
But if CMakeList like this: 
   target_link_libraries(demo_server  thrift).  
 Program will run success.  

## Expected behav
[TestThriftAndLibtorch.tar.gz](https://github.com/pytorch/pytorch/files/3313983/TestThriftAndLibtorch.tar.gz)

This is my test code,run command
cmake -DCMAKE_PREFIX_PATH=/home/...your libtorch dir ...
make
./demo_server
./demo_client
if without dependecy on ${TORCH_LIBRARIES}, server will output "aaa"

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1060 6GB
Nvidia driver version: 396.54
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] torch==1.0.1.post2
[pip] torchvision==0.2.2
[conda] mkl                       2019.3                      199    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.0.1           py2.7_cuda9.0.176_cudnn7.4.2_2    pytorch
[conda] torchvision               0.2.2                      py_3    pytorch

**Comment by VitalyFedyunin** [comment]
Can you please provide thrift library information, such as compiler used, version etc.
Also please consider compiling pytorch yourself within your dev. environment, that could help with such issue.

**Comment by chinafei** [comment]
> Can you please provide thrift library information, such as compiler used, version etc.
> Also please consider compiling pytorch yourself within your dev. environment, that could help with such issue.

thrift version is 0.13.0 , you can get like this:
git clone https://github.com/apache/thrift.git
cd thrift
sudo apt-get install automake bison flex g++ git libboost1.55 libevent-dev libssl-dev libtool make pkg-config

./configure --with-cpp --with-boost --with-java --without-python --without-csharp  --without-erlang --without-perl --without-php --without-php_extension --without-ruby --without-haskell --without-go 

make 
make install


libtorch: https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-latest.zip

**Comment by yf225** [comment]
@chinafei Could you try compiling libtorch with your local copy of gcc-5 and g++-5? (instruction is at https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst#libtorch-c-only) The segmentation fault could come from ABI incompatibility issue.

**Comment by chinafei** [comment]
> @chinafei Could you try compiling libtorch with your local copy of gcc-5 and g++-5? (instruction is at https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst#libtorch-c-only) The segmentation fault could come from ABI incompatibility issue.



It works on me, Tank you !!!
https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst#libtorch-c-only
