### ISSUE TITLE
ExpTransform log_abs_det_jacobian, is it correct?

### ISSUE THREAD

**Issue by gamerDecathlete** [pytorch/pytorch#22060]
## ❓ Questions and Help

I was going through the implementation for the Transform functions, and I don't think the log absolute determinant of the jacobin of the "ExpTransform" is correct:

def log_abs_det_jacobian(self, x, y):
        return x

presumably, x is input and y is the output, but just kind of quickly doing some calculations, I think there should be a sum operation over the last dimension of x based on my understanding of the determinant. Then again, my math is not...quite up to snuff lately so I just wanted to ask about this to clarify before submitting an issue (which may not be an issue and you know, a mistake in my math). Thank you!

**Comment by VitalyFedyunin** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
