### ISSUE TITLE
[ONNX] BUG for Upsample operator export re-used by caffe2

### ISSUE THREAD

**Issue by ygwangthu** [pytorch/pytorch#22070]
I can succesfully save the PyTorch model into ONNX file now. However, The ONNX file can not be used by caffe2. This bug is about Upsample operator. @pk-g @houseroad

Acturally, I note that bugs for upsample operator into ONNX has been for a long time. Recently, it seems to be solved (I can save without error information). However, I will tell you that it still has bugs!!!

Error information is:

> RuntimeError: Tensor type mismatch, caller expects elements to be float, while tensor contains int64_t. Error from operator:
> input: "164" output: "165" name: "" type: "Floor" device_option { device_type: 1 device_id: 0 } (data at D:/usefullib/pytorch\c10/core/TensorImpl.h:599)
> (no backtrace available)

The 164 and 165 operator is:

> %164 : Tensor = onnx::Mul(%162, %163)
> %165 : Float() = onnx::Floor(%164), scope: MyNet # C:\Python37\Lib\site-packages\torch\nn\functional.py:2526:0

which is part of Upsample.

I traced the Upsample operator saved by ONNX, it has

> %160 = Constant[value = <Scalar Tensor []>]()
>   %161 = Shape(%159)
>   %162 = Gather[axis = 0](%161, %160)
>   %163 = Constant[value = <Scalar Tensor []>]()
>   %164 = Mul(%162, %163)
>   %165 = Floor(%164)
>   %166 = Constant[value = <Scalar Tensor []>]()
>   %167 = Shape(%159)
>   %168 = Gather[axis = 0](%167, %166)
>   %169 = Constant[value = <Scalar Tensor []>]()
>   %170 = Mul(%168, %169)
>   %171 = Floor(%170)
>   %172 = Unsqueeze[axes = [0]](%165)
>   %173 = Unsqueeze[axes = [0]](%171)
>   %174 = Concat[axis = 0](%172, %173)
>   %175 = Constant[value = <Tensor>]()
>   %176 = Cast[to = 1](%174)
>   %177 = Shape(%159)
>   %178 = Slice[axes = [0], ends = [4], starts = [2]](%177)
>   %179 = Cast[to = 1](%178)
>   %180 = Div(%176, %179)
>   %181 = Concat[axis = 0](%175, %180)
>   %182 = Upsample[mode = 'nearest'](%159, %181)

I am not sure why upsample need so many operators? Acturally, I only use the factor of 2. %159 is the 2D map I want to upsample.

The 'torch\nn\functional.py:2526:0' has the code

>     if torch._C._get_tracing_state():
>             return [(torch.floor(input.size(i + 2) * torch.tensor(float(scale_factors[i])))) for i in range(dim)]
>     else:
>             return [int(math.floor(int(input.size(i + 2)) * scale_factors[i])) for i in range(dim)]

It seems the 'else' has been excucted, which has the **int** type.  and

> torch._C._nn.upsample_nearest2d(input, _output_size(2))

use the **int** type

I've no idea about the definition of the function **torch._C._nn.upsample_nearest2d**, which I can change the check for input types.

Hope for your solutions!

**Comment by VolodymyrAhafonov** [comment]
Same problem. Some solution?
