### ISSUE TITLE
ProcessGroup wrapper that aids collectives desynchronization

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#22071]
## 🚀 Feature

In torch.distributed/c10d we should have some sort of ProcessGroup proxy that creates a fingerprint of the collective to be run, the input tensors (device type, data type, shape, etc), and executes an allgather on that fingerprint to verify the call is valid.

## Motivation

Currently a user can call different collectives, or the same collective with different tensor shapes, and cause a crash that reports a daunting error message. If we provide a way to debug where this desynchronization is happening then we'll be able to better help out users who experience this and perhaps even make it entirely self-debuggable. For example, if we perform an allgather on the collective fingerprint and allgather it, every process can raise an exception and log their stack. This alone is a direct view into *where* the desynchronization is happening.

## Pitch

A ProcessGroup wrapper that takes 2 process groups for initialization: a Gloo process group that can be used to share the fingerprints, and a process group to call into if the fingerprints match. Calls to the underlying process group should be fully serialized, since this will be a tool for debugging only. We can catch and re-raise exceptions from process groups if they still fail and add some message about this debugging facility. Users can enable this by calling `init_process_group` with `debug=True` (for example).

## Alternatives

We could choose to do this entirely in Python, since it doesn't need to be fast, but then again it wouldn't be applicable for C++ users. I'd rather have the implementation in C++ so it can be used everywhere.

**Comment by pietern** [comment]
Listing issues where this would have been helpful:

* #22788
* #22834

**Comment by pietern** [comment]
@zhaojuanmao Unassigning you while there is no work in progress.

**Comment by rohan-varma** [comment]
This would also likely be useful to debug https://github.com/pytorch/pytorch/issues/39706

**Comment by hizukiayaka** [comment]
We tried the signl trap method as the post from a topic discuss topic and starting each rank in a different terminal console.
It would work when the program runs normally, but when it is frozen even SIGINT(I always set a trap for  it to enter pdb) won’t work, neither the second process(rank 1) can enter pdb. Sometimes it would be a hard to kill the master(rank 0) process.

Any more idea for debugging ?

**Comment by rohan-varma** [comment]
@hizukiayaka Thanks for the report! It would be best if you can file an issue (if this is a bug) or a post on http://discuss.pytorch.org/c/distributed/ if it is a specific question, in order to have a more detailed discussion about your specific use case.

**Comment by rohan-varma** [comment]
Done by https://github.com/pytorch/pytorch/pull/58224
