### ISSUE TITLE
Inplace error if DistributedDataParallel module that contains a buffer is called twice

### ISSUE THREAD

**Issue by HapeMask** [pytorch/pytorch#22095]
## 🐛 Bug

If you have a DistributedDataParallel module which contains a buffer used in the forward pass, and that module's forward method gets called twice in your training script, the following `backward()` call will fail claiming that a variable that requires grad has been modified by an inplace operation.

## To Reproduce

1. Run the following minimal repro: `python -m torch.distributed.launch test.py`
2. Observe `RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 32]] is at version 3; expected version 2 instead.`
3. Run with `python test.py`, observe no errors.

```python
import os
import argparse

import torch as th

th.autograd.set_detect_anomaly(True)

class Mod(th.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = th.nn.Linear(256, 32)
        self.register_buffer("buf", th.zeros(1, 32))

        # If buf is a Parameter instead of a buffer, there will be no inplace
        # error.
        #self.buf = th.nn.Parameter(th.zeros(1, 32))

    def forward(self, z):
        return (self.lin(z) * self.buf).sum()

        # If this line is substituted for the one above, there will be no
        # inplace error.
        #return (self.lin(z) * self.buf.clone()).sum()

def run(distributed=False, local_rank=None):
    mod = Mod().cuda()
    optim = th.optim.Adam(mod.parameters(), lr=1e-3)

    if distributed:
        mod = th.nn.parallel.DistributedDataParallel(mod,
                device_ids=[local_rank], output_device=local_rank)

    z1 = th.zeros(7, 256).cuda()
    z2 = th.zeros(7, 256).cuda()
    out = mod(z1)

    mod(z2) # <<---- The presence of this unused call causes an inplace error in backward() below if dec is a DDP module.

    loss = (out**2).mean()

    optim.zero_grad()
    loss.backward()
    optim.step()

    print("Stepped.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--local_rank", type=int, default=0)
    args = parser.parse_args()

    world_size = int(os.environ.get("WORLD_SIZE", 0))
    args.distributed = world_size >= 1
    if args.distributed:
        print(f"[Main] Distributed across {world_size} GPUs")
        th.cuda.set_device(args.local_rank)
        th.distributed.init_process_group(backend="nccl", init_method="env://")

    run(distributed=args.distributed, local_rank=args.local_rank)
```
Note that the module must contain a buffer and the output of the second call to the module need not be used. Using the output doesn't stop the crash. Replacing the buffer with a parameter does stop the crash, even though neither was used inplace (visibly). Cloning the buffer will stop the crash.

## Environment
 - PyTorch Version (e.g., 1.0): master (nightly 1.2.0.dev20190621)
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.7
 - CUDA/cuDNN version: 10 /  7.5
 - GPU models and configuration: Titan RTX

**Comment by HapeMask** [comment]
The cause here is that by default DDP modules broadcast the contents of the root process module's buffers to all processes at every forward pass, and this broadcasting counts as an inplace operation for the purposes versioning. The fix is to disable the broadcasting by setting `broadcast_buffers=False` in the DDP module constructor. Thanks @pietern for the help.

**Comment by makslevental** [comment]
note that this also happens with `nn.BatchNorm2d` layers if `track_running_stats` because of 

```python
            self.register_buffer('running_mean', torch.zeros(num_features))
            self.register_buffer('running_var', torch.ones(num_features))
            self.register_buffer('num_batches_tracked', torch.tensor(0, dtype=torch.long))
```

**Comment by pietern** [comment]
@makslevental Did you also have the additional call to forward in between?

If not, please open an issue and we can figure out what's up.

**Comment by makslevental** [comment]
@pietern i'm sorry in between what and what?

**Comment by pietern** [comment]
@makslevental A call to the model that will mutate the buffers, like `mod(z2)` in the example above.

**Comment by makslevental** [comment]
@pietern no i have no unused calls like this in my code. i'll open the issue soon.

**Comment by Hzzone** [comment]
same problem, thanks a lot!!!!!

**Comment by ShaoTengLiu** [comment]
I have the same problem, thank you so much. I want to know will the parameters of nn.BatchNorm2d still update after setting broadcast_buffers=False in DDP.

**Comment by ShaoTengLiu** [comment]
Hi, what can I do if I want to both **update the Batchnorm stats** and **call Batchnorm twice**.

**Comment by yaox12** [comment]
> Hi, what can I do if I want to both **update the Batchnorm stats** and **call Batchnorm twice**.

When I use `SyncBatchNorm ` and call the model twice, it will not throw an error. But I'm not sure whether it produces the expected results.

**Comment by louisace** [comment]
@HapeMask I set broadcast_buffers=False in the DDP module constructor. But the error does not solve.  Is there anything else that could cause the problem?

**Comment by jiangzhengkai** [comment]
broadcast_buffers=False in the DDP solves my problem

**Comment by hologerry** [comment]
Saved my life!

**Comment by rubencart** [comment]
For me `nn.BatchNorm2d` also gave the mentioned error when used in a model that is wrapped by `DistributedDataParallel`. Simply setting `broadcast_buffers=False` in the DDP constructor did not solve it. Using [`SyncBatchNorm`](https://pytorch.org/docs/stable/generated/torch.nn.SyncBatchNorm.html) does, but only when `process_group` is explicitly set to `torch.distributed.new_group()` or `torch.distributed.new_group(list(range(torch.distributed.get_world_size())))`, and not left to its default value. I'm not so familiar with `DistributedDataParallel`, but would the synchronization still happen correctly when `process_group` is set to `torch.distributed.new_group()` (because the list of rank_ids is empty)?

**Comment by GloryyrolG** [comment]
> Hi, what can I do if I want to both **update the Batchnorm stats** and **call Batchnorm twice**.

I am also wondering does this operation cause problems in the training, e.g., hurting the performance? Thanks.

**Comment by lcxywfe** [comment]
> Hi, what can I do if I want to both **update the Batchnorm stats** and **call Batchnorm twice**.

@ShaoTengLiu Hi, have you solved it? I have the same problem as you.

**Comment by 4-0-4-notfound** [comment]
use `nn.SyncBatchNorm` instead of `nn.BatchNormxD`  in DDP

**Comment by omsrisagar** [comment]
I have used nn.SyncBatchNorm, but the error is still there. I am using BatchNorm2D along with LSTM. So BatchNorm2D needs to be called for `n` number of timesteps.

**Comment by liuzhy71** [comment]
thanks a lot!!! This solves my problem.

**Comment by TissueC** [comment]
This solves my problem. I wonder if there would be any side effects. Thanks for any reply.

**Comment by syamamo1** [comment]
I was getting an error on BatchNorm2D but setting broadcast_buffers=False in DDP fixed this problem

**Comment by chenerg** [comment]
Still solved my problem.
