### ISSUE TITLE
Memory leak when utilizing pandas indices

### ISSUE THREAD

**Issue by fps7806** [pytorch/pytorch#22105]
## 🐛 Bug

There is a memory leak when utilizing pandas.Int64Index + pytorch on windows (haven't tested Linux + mac)

## To Reproduce
```
import numpy as np
import torch
import pandas as pd


idx = pd.core.indexes.numeric.Int64Index(np.arange(10000))
arr = torch.zeros(len(idx))

while True:
    arr[idx]
```

## Environment

 - PyTorch Version (e.g., 1.0):1.1.0
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Python version:3.6
 - Any other relevant information:
pandas==0.20.3

cc @peterjc123

**Comment by VitalyFedyunin** [comment]
Same on the Linux. Likely pyref leaks. As remedy please cast Index to list before usage `arr[list(idx)]`.

**Comment by cristianPanaite** [comment]
Hello @fps7806,

Closing this ticket as the ticket hasn't had any activity for a long period of time and it seems that it is not valid anymore. I tried to replicate this issue, but on the latest versions I don't get this error.

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.
