### ISSUE TITLE
this is my error "libtorch.so: error adding symbols: File in wrong format"

### ISSUE THREAD

**Issue by taotaohan** [pytorch/pytorch#22116]
I use TX2，this is my list:
Ubuntu 16.04.5 LTS
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
cmake version 3.5.1
pytorch C++ v1.1
can you tell me what happened?

**Comment by VitalyFedyunin** [comment]
TX2 is ARM and you likely took i386 binaries. You need to compile for right architecture or use another binaries.

**Comment by taotaohan** [comment]
> 
> 
> TX2 is ARM and you likely took i386 binaries. You need to compile for right architecture or use another binaries.

but in this web(https://pytorch.org/), I can't find source code to compile?where can i find the file or source code for right architecture?

**Comment by VitalyFedyunin** [comment]
https://discuss.pytorch.org/t/tx2-arm64-install-for-python-3-cont-from-nvidia-forum/27631

**Comment by taotaohan** [comment]
> 
> 
> https://discuss.pytorch.org/t/tx2-arm64-install-for-python-3-cont-from-nvidia-forum/27631

thanks

**Comment by BillyMazotti** [comment]
I'm running into a similar error for a different setup:
Hardware: MacbookPro M1 
OS: Ubuntu 20.04.5 via VMware Fusion (followed this [guide](https://dev.to/daud99/installing-ubuntu-using-vmware-fusion-tech-preview-on-mac-m1-silicon-4b0e))

Followed the official documentation [here](https://pytorch.org/cppdocs/installing.html) and received the following error after running "cmake --build . --config Release":


`(spslam3) bmazotti@ubuntu20045:~/Documents/spslam/example-app/build$ cmake --build . --config Release
Scanning dependencies of target example-app
[ 50%] Building CXX object CMakeFiles/example-app.dir/example-app.cpp.o
[100%] Linking CXX executable example-app
/usr/bin/ld: /home/bmazotti/Documents/spslam/libtorch/lib/libtorch.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/example-app.dir/build.make:88: example-app] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/example-app.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`


Any help would be greatly appreciated, thanks in advance!
