### ISSUE TITLE
Building from source failed. Multiple errors in the printout

### ISSUE THREAD

**Issue by taojiashu** [pytorch/pytorch#22129]
## 🐛 Bug
I am trying to build Pytorch from source on a Ubuntu 18.04 GPU server. However, after I have followed the steps listed [here](https://github.com/pytorch/pytorch#from-source), running `python setup.py install` keeps failing. 

## To Reproduce
I have two CUDA installed in my system, the default one is CUDA 9.0. I have switched to CUDA9.2 when building PyTorch. Then I followed the instructions by cloning the repo, fetching submodules, installing dependencies in conda and setting conda prefix,  followed by `python setup.py install`. But it always gives a long list of warnings and errors. The following is a summary of CMake.

```
--   CMake version         : 3.14.0
--   CMake command         : /home/jiashu/anaconda3/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/g++-7
--   C++ compiler version  : 7.4.0
--   CXX flags             :   -fvisibility-inlines-hidden -fopenmp -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL
--   CMAKE_PREFIX_PATH     : /home/jiashu/anaconda3
--   CMAKE_INSTALL_PREFIX  : /home/jiashu/Documents/pytorch/torch
--   CMAKE_MODULE_PATH     : /home/jiashu/Documents/pytorch/cmake/Modules;/home/jiashu/Documents/pytorch/cmake/public/../Modules_CUDA_fix
-- 
--   ONNX version          : 1.5.0
--   ONNX NAMESPACE        : onnx_torch
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
-- 
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : OFF
-- 
-- ******** Summary ********
--   CMake version         : 3.14.0
--   CMake command         : /home/jiashu/anaconda3/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/g++-7
--   C++ compiler version  : 7.4.0
--   CXX flags             :   -fvisibility-inlines-hidden -fopenmp -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL
--   CMAKE_PREFIX_PATH     : /home/jiashu/anaconda3
--   CMAKE_INSTALL_PREFIX  : /home/jiashu/Documents/pytorch/torch
--   CMAKE_MODULE_PATH     : /home/jiashu/Documents/pytorch/cmake/Modules;/home/jiashu/Documents/pytorch/cmake/public/../Modules_CUDA_fix
-- 
--   ONNX version          : 1.4.1
--   ONNX NAMESPACE        : onnx_torch
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : 
--   Protobuf includes     : 
--   Protobuf libraries    : 
--   BUILD_ONNX_PYTHON     : OFF
```

## Errors
Some of the recurring errors are:
1. Cannot generate a safe runtime search path due to a cycle in the constraint graph.
e.g:
CMake Warning at cmake/Modules_CUDA_fix/upstream/FindCUDA.cmake:1889 (add_executable):
  Cannot generate a safe runtime search path for target
  generate_proposals_op_util_nms_gpu_test because there is a cycle in the
  constraint graph:
    dir 0 is [/usr/local/cuda-9.2/lib64]
      dir 1 must precede it due to runtime library [libnvToolsExt.so.1]
    dir 1 is [/home/jiashu/anaconda3/lib]
      dir 0 must precede it due to runtime library [libcudart.so.9.2]
    dir 2 is [/home/jiashu/Documents/pytorch/build/lib]
    dir 3 is [/home/jiashu/anaconda3/bin/../lib]
      dir 0 must precede it due to runtime library [libcudart.so.9.2]

2. [-Wunused-parameter]
I have seen hundreds of lines of warnings printed out with this [-Wunused-parameter] tag.
e.g:
``` 
../third_party/protobuf/src/google/protobuf/inlined_string_field.h: In member function ‘void google::protobuf::internal::InlinedStringField::SetNoArena(const string*, const string&)’:
../third_party/protobuf/src/google/protobuf/inlined_string_field.h:229:26: warning: unused parameter ‘default_value’ [-Wunused-parameter]
     const ::std::string* default_value, const ::std::string& value) {
                          ^~~~~~~~~~~~~
../third_party/protobuf/src/google/protobuf/inlined_string_field.h: In member function ‘void google::protobuf::internal::InlinedStringField::SetNoArena(const string*, std::__cxx11::string&&)’:
../third_party/protobuf/src/google/protobuf/inlined_string_field.h:235:26: warning: unused parameter ‘default_value’ [-Wunused-parameter]
     const ::std::string* default_value, ::std::string&& value) {
                          ^~~~~~~~~~~~~
../third_party/protobuf/src/google/protobuf/inlined_string_field.h: In member function ‘std::__cxx11::string* google::protobuf::internal::InlinedStringField::UnsafeArenaRelease(const string*, google::protobuf::Arena*)’:
../third_party/protobuf/src/google/protobuf/inlined_string_field.h:254:48: warning: unused parameter ‘arena’ [-Wunused-parameter]
     const ::std::string* default_value, Arena* arena) {
                                                ^~~~~
../third_party/protobuf/src/google/protobuf/inlined_string_field.h: In member function ‘void google::protobuf::internal::InlinedStringField::UnsafeArenaSetAllocated(const string*, std::__cxx11::string*, google::protobuf::Arena*)’:
../third_party/protobuf/src/google/protobuf/inlined_string_field.h:259:70: warning: unused parameter ‘arena’ [-Wunused-parameter]
```

3. The final Traceback:
ninja: build stopped: subcommand failed.
```
Traceback (most recent call last):
  File "setup.py", line 754, in <module>
    build_deps()
  File "setup.py", line 327, in build_deps
    cmake=cmake)
  File "/home/jiashu/Documents/pytorch/tools/build_pytorch_libs.py", line 64, in build_caffe2
    cmake.build(my_env)
  File "/home/jiashu/Documents/pytorch/tools/setup_helpers/cmake.py", line 360, in build
    self.run(build_args, my_env)
  File "/home/jiashu/Documents/pytorch/tools/setup_helpers/cmake.py", line 110, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/jiashu/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '48']' returned non-zero exit status 1.
```

## Full printout
Due to the length of the printout (3770 lines), I have uploaded it [here](https://www.dropbox.com/s/qbih6yi3sfbg0eh/Error%20printout.txt?dl=0). I have been stuck here for more than two weeks and cannot figure out a way to solve it. Really appreciate for some explanations of these errors and suggestions on how to solve them.

**Comment by VitalyFedyunin** [comment]
You can find good answer here: https://github.com/torch/torch7/issues/1190#issuecomment-498934400 (credits to @talkenig)

Copy pasting for future reference:

Had the same problem and got to the bottom of it. My configuration is a Tesla T4 with 410.92 driver and CUDA 9.2, Ubuntu 18.10.
The thing is, the torch installer tries for some reason to use the highest compute capability supported by the device (or the driver - not sure which), but ignores the compute capability supported by the CUDA toolkit.
So, in my case the device supports compute capability 7.5, but CUDA 9.2 supports only 7.0 or 7.2 (not sure which one). You can guess I got the same nvcc fatal : Unsupported gpu architecture 'compute_75'
The solution is to force the nvcc compile options to use a lower compute capability. This can be achieved by setting the following environment variable:

`export TORCH_CUDA_ARCH_LIST="7.0"`

Just before running ./install.sh from the torch directory.
Note that the list may contain more than one compute capability, e.g. it can be "6.0 6.2 7.0 7.2". This will be reflected in the CUDA_NVCC_FLAGS -gencode arch=compute_70,code=sm_70 and those will be outputted to the terminal during the build.

**Comment by talkenig** [comment]
Thanks, Vitaly.
That answer you cited is actually mine. I figured it out and posted the
solution for the good of mankind...

**Comment by VitalyFedyunin** [comment]
Please reopen if it doesn't solve your issue.
