### ISSUE TITLE
Segfault on Ubuntu 14.04 Trusty

### ISSUE THREAD

**Issue by gheaeckkseqrz** [pytorch/pytorch#22123]
## 🐛 Bug

Simple example segfault on Ubuntu 14.04 (Trusty).
Exact same code runs on Ubuntu 16.04 (Xenial).

## To Reproduce

Bug came to my attention while using Travis.

Broken version : https://travis-ci.org/gheaeckkseqrz/StyleTransfer-CPP/builds/549412118
Working version : https://travis-ci.org/gheaeckkseqrz/StyleTransfer-CPP/builds/549465910

The only difference between the two is the Ubuntu version : https://github.com/gheaeckkseqrz/StyleTransfer-CPP/compare/90fb75931a9a...30ffd6485ff6

## Expected behavior

Expected to work, or fail at compile time on 14.04

## Environment

 - PyTorch Version : 1.2.0.dev20190623
 - OS (e.g., Linux): Ubuntu 14.04 (Trusty) -- As provided by Travis
 - How you installed PyTorch :  ```wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip```
 - Build command you used (if compiling from source): https://github.com/gheaeckkseqrz/StyleTransfer-CPP/blob/4e449e36cdcb1eca076cbb33cd504ee1544e9ef7/.travis.yml
 - Python version: N/A
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

## Additional context

Sorry I can't give much more details, Travis doesn't allow to poke around too much, but hopefully this should be easy to reproduce.

**Comment by soumith** [comment]
my first guess would be that Trusty (14.04) by default uses gcc 4.8 which has known ABI bugs.

`libtorch` binaries are compiled with gcc 4.9.2.

While using `libtorch` binaries to compile your program, you can either use gcc 4.9.x or you can gcc >= 5.1 and set the flag `-D_GLIBCXX_USE_CXX11_ABI=0`.

**Comment by gheaeckkseqrz** [comment]
Indeed ```-- The CXX compiler identification is GNU 4.8.4```

So this looks more like a GCC bug that a PyTorch bug.
Closing the issue.
