### ISSUE TITLE
pytorch dataloader create new num_workers python process every epoch

### ISSUE THREAD

**Issue by LU4E** [pytorch/pytorch#22133]
## ❓ Questions and Help
pytorch dataloader create new num_workers python process every epoch.
for example in my issue: i set the num_workers 15. Every epoch , about 15 the python processes will be created insteading of using the existing process, which leads to the memory is out.

**Comment by VitalyFedyunin** [comment]
Looks like a bug in your code, for example, you are creating DataLoader instance inside the loop. Could you please attach an example so we can reproduce the issue.

**Comment by LU4E** [comment]
yes, its my mistake.
i've alredy solve the problem.
thank you any way.
