### ISSUE TITLE
legacy Tensor.new for alternative layouts is broken

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#22158]
## To Reproduce
```
>>> torch.randn(2,3).to_mkldnn().new((2,3))
tensor([2., 3.])
```

## Expected behavior

I would expect the following to either work or through an error message (probably just throw an error message, since the method is deprecated).

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by jingxu10** [comment]
Hi,
Could you clarify why the method (to_mkldnn().new()) is deprecated?

**Comment by gchanan** [comment]
`new` is deprecated.
