### ISSUE TITLE
How can I delete a Tensor in GPU?

### ISSUE THREAD

**Issue by ztf-ucas** [pytorch/pytorch#22181]
## ❓How to delete a Tensor in GPU to free up memory？
 I can get a Tensor in GPU by Tensor.cuda(), but it just returns a copy in GPU. I wonder how can I delete this Tensor in GPU? I try to delete it with "del Tnesor" but it doesn't work.

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
