### ISSUE TITLE
Performance issue of inverse of cuda tensor.

### ISSUE THREAD

**Issue by ethanluoyc** [pytorch/pytorch#2219]
```
import torch
import time

t = torch.rand(3,3)
ct = t.cuda()

start = time.time()
for i in range(100):
    t.inverse()

print('cpu: %f' % (time.time() - start))

start = time.time()
for i in range(100):
    ct.inverse()

print('gpu: %f' % (time.time() - start))
```

On my machine (nVidia GeForce GTX 1080) it produces the following output:

```
cpu: 0.003675
gpu: 2.056742
```

PyTorch version : 0.1.12+6f6d70f

**Comment by soumith** [comment]
GPU ops are slow in many cases, especially for such small Tensors i expect CPU ops to be much faster. I dont think we can do much optimization for something like 3x3 Tensors.

**Comment by IssamLaradji** [comment]
This is expected, the time it takes to launch the GPU threads and establishing shared memory is the bottleneck for computing the inverse of this small matrix. The GPU is much faster when the matrix is large enough.
