### ISSUE TITLE
libtorch is conflict with ros

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#22197]
## 🐛 Bug

on ros, this issue happens.

errors:

```
undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
```

this only happens when I link to TORCH_LIBRARIES:

```
set(CMAKE_PREFIX_PATH $ENV{HOME}/libtorch)
find_package(Torch REQUIRED)
include_directories(include/)
if (NOT Torch_FOUND)
    message(FATAL_ERROR "you should change CMAKE_PREFIX_PATH to libtorch dir")
else ()
    message(STATUS "found libtorch at " ${TORCH_LIBRARIES})
endif ()


add_executable(w_stop_node src/*.cc )
target_link_libraries(
        w_stop_node
        ${catkin_LIBRARIES}
        ${TORCH_LIBRARIES}
        glog
        thor
)

```

Once I comment out ${TORCH_LIBRARIES}, the program can build, otherwise it says undefined errors.

Not sure what caursed this error, but on ROS, this is an issue. Hope someone could help me out.

I do not know why linked to TORCH will wipe out catkin libs....................... (abviously those ROS related undefined errors are caused by unlink to catkin libs)

**Comment by jinfagang** [comment]
there were 2 mainly problems integrate libtorch in ros:

- TORCH_LIBRARIES will wipe catkin libs since it using some relative link path and catkin libs can not parsed by cmake;
- include can not be properly parsed in cmake since `torch/torch.h` is deeply inside `/torch/csrc/api/cinlude`.

However, using standalone c++ project does not have those issue, and totally no idea why... It can be easily reproduced in any ROS project which using libtorch

**Comment by aqrliu** [comment]
hello! do you solved this problem? I have the similar problem with you , libtorch conflict with log4cxx when I build this poroject.
if add torch like this 
target_link_libraries(main ${TORCH_LIBRARIES} log4cxx)
link will failed.there will many indefined reference about log4cxx;
if remove torch
build and link will successfull.

If you know why ,let me know ,please!

**Comment by maxwellfrom** [comment]
> there were 2 mainly problems integrate libtorch in ros:
> 
> * TORCH_LIBRARIES will wipe catkin libs since it using some relative link path and catkin libs can not parsed by cmake;
> * include can not be properly parsed in cmake since `torch/torch.h` is deeply inside `/torch/csrc/api/cinlude`.
> 
> However, using standalone c++ project does not have those issue, and totally no idea why... It can be easily reproduced in any ROS project which using libtorch

Hi @jinfagang 
Have you solved the problem? I met the same problem recently, looking forward to  your help, Thank you!

**Comment by phamdat09** [comment]
Hi everyone!!

Have you fixed it ? I also have the same problem !!

Thanks!!!

**Comment by FedeAi** [comment]
Why is it marked as closed ? I've the exactly the same problem...
