### ISSUE TITLE
BCELoss target requires float format

### ISSUE THREAD

**Issue by zzzace2000** [pytorch/pytorch#2220]
Hi,

I find that BCELoss target require float tensor, which is wierd. It should accept LongTensor or IntTensor for a binary classification (0 or 1) right?

This is the error message I get.

TypeError: FloatBCECriterion_updateOutput received an invalid combination of arguments - got (int, torch.FloatTensor, torch.LongTensor, torch.FloatTensor, bool, NoneType), but expected (int state, torch.FloatTensor input, torch.FloatTensor target, torch.FloatTensor output, bool sizeAverage, [torch.FloatTensor weights or None])

**Comment by shrshore** [comment]
I met similar problem. Let's look at the source code of function binary_cross_entropy_with_logits here: http://pytorch.org/docs/master/_modules/torch/nn/functional.html#binary_cross_entropy_with_logits

The ``input`` should be a Torch.FloatTensor, whose element should be a real number between 0 and 1, but the ``target`` should be a Torch.LongTensor, whose element is either 0 or 1. The FloatTensor and LongTensor is not compatible so the first size check cannot pass, neither the following multilication operation. So I think this could be a bug. Is there a version which fix this problem?

Thanks very much if anyone can help!

**Comment by bheinzerling** [comment]
The docs say "the targets t[i] should be numbers between 0 and 1".

Sometimes it's useful not to enforce binary constraints on the targets, for example if you're doing label scaling.

**Comment by shrshore** [comment]
@bheinzerling Sounds reasonable. Thanks for your advice very much!

**Comment by alykhantejani** [comment]
@zzzace2000 @shrshore Also see the discussion from @fmassa on this topic [here](https://github.com/pytorch/pytorch/issues/2272).

**Comment by soumith** [comment]
i think we'll leave it as `float` requirement. See: https://github.com/pytorch/pytorch/issues/2272#issuecomment-319766578
