### ISSUE TITLE
[feature request] Inplace bitwise negation operator 

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#22246]
Currently `~mask` is possible, but not inplace, if I understand well. 

NumPy equivalent would be https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.invert.html

**Comment by xuhdev** [comment]
Fixed in 9c4c9c3af042498144c40b30d64443cca943906a

**Comment by xuhdev** [comment]
Reverted for now, see https://github.com/pytorch/pytorch/pull/22326#issuecomment-510280113

But you can use Tensor.bitwise_not() as workaround for now

**Comment by xuhdev** [comment]
Tensor.bitwise_not_() is available now
