### ISSUE TITLE
Schema not found for node torch::eye

### ISSUE THREAD

**Issue by ferrine** [pytorch/pytorch#22255]
## 🐛 Bug

Testing geoopt against torch-nightly fails probably due to backward incompatible changes from torch side

## To Reproduce

Installing torch_nightly for some reason allowed to import geoopt locally, hmm

https://travis-ci.com/geoopt/geoopt/jobs/210289618#L1310

## Expected behavior

no error

## Environment

Please copy and paste the output from our
https://travis-ci.com/geoopt/geoopt/jobs/210289618#L823

## Additional context

testing in a docker container

**Comment by driazati** [comment]
Are you able to extract a smaller repro?

`import geoopt` works fine on master, and re-producing the code causing the failure runs fine as well

```python
@torch.jit.script
def test(A):
    return torch.eye(A.shape[1], dtype=A.dtype, device=A.device)
```

**Comment by ferrine** [comment]
I'll check that soon, sure

**Comment by ferrine** [comment]
Looks like the build is passing with master branch, I close the issue
