### ISSUE TITLE
Do Standard pretrained models be trained with L2?

### ISSUE THREAD

**Issue by huyalvchuan** [pytorch/pytorch#22253]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by fmassa** [comment]
We use GitHub issues to track bugs and feature requests. Questions are better suited for the forums discuss.pytorch.org

But in general, the pre-trained models are trained with `weight_decay`, which is the L2 regularization

**Comment by huyalvchuan** [comment]
Thanks!
