### ISSUE TITLE
Development setup - docs

### ISSUE THREAD

**Issue by Shekharrajak** [pytorch/pytorch#22263]
Hello team,

I am trying to build the docs without installing PyTorch in my system(actually isolated environment). I installed Sphinx and followed [this steps](https://github.com/pytorch/pytorch#building-the-documentation) : 

```
cd docs/
pip install -r requirements.txt
````
it installed perfectly and then I run `make html`

but I got error

```
➜  make html
Traceback (most recent call last):
  File "source/scripts/build_activation_images.py", line 8, in <module>
    import torch.nn.modules.activation
ModuleNotFoundError: No module named 'torch'
Makefile:17: recipe for target 'figures' failed
make: *** [figures] Error 1

````

Is it possible to build the docs without installing the PyTorch or directly use the cloned folder to get the necessary modules?

Regards,
Shekhar

**Comment by soumith** [comment]
it isn't possible to build the docs without installing PyTorch at the moment. we likely wont want to support that case in the near future.
