### ISSUE TITLE
Support data parallel for heterogeneous GPU

### ISSUE THREAD

**Issue by KaitoHH** [pytorch/pytorch#22296]
## 🚀 Feature

Hopefully, `torch.nn.DataParallel` can support data parallel on multiple heterogeneous GPU.

## Motivation

I'm currently working on a big model and would like to use `torch.nn.DataParallel` to speed up training. However, I use two different GPU on my computer, i.e, GTX 1060 and GTX 1080, when I train the model, 1060 becomes a bottleneck and slows down the whole training process.

## Pitch
It will be great that `nn.Dataparallel` can automatically assign tasks according to computation power or support manually specifying mini-batch size on each GPU.

**Comment by ezyang** [comment]
@pietern @fmassa and @soumith think we should not do this.

**Comment by pietern** [comment]
@KaitoHH Thanks for creating the issue. To add a bit more context, using heterogeneous GPUs is not that common, and therefore I think we shouldn't overspecialize `nn.DataParallel` for this use case. You know the performance imbalance for your particular setup, so you could try to do manual or automatic load balancing yourself by tuning the batch size per GPU, for example. I would start with a copy of `nn.DataParallel` and scatter an input batch based on throughput (or some other characteristic you care about).
