### ISSUE TITLE
How to define a new backward function in libtorch ?

### ISSUE THREAD

**Issue by buduo15** [pytorch/pytorch#22290]
###  In pytorch, a new backward function can  be defined
`

class new_function(torch.autograd.Function):

         def ....

         def forward(self,...)

         def backward(self, ...)

`
However, in libtorch,  how to define a new backward function?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions.

for the C++ API, tag the forum questions with the `c++` tag
