### ISSUE TITLE
[c++] Can't use Sequential inside Sequential 

### ISSUE THREAD

**Issue by ShahriarSS** [pytorch/pytorch#22298]
Hi. I was implementing MNASNet for C++ side in torchvision and I ran into this problem. apparently using ```nn::Sequential``` inside ```nn::Sequential``` is not possible. Here is the minimal code:

```
torch::nn::Sequential layers;
auto S = torch::nn::Sequential();
layers->push_back(S);
```

@yf225 Can you have a look?

**Comment by ShahriarSS** [comment]
Apparently the problem is that nn::Sequential has templated forward function.

**Comment by ShahriarSS** [comment]
@soumith Can anyone else have a look? This is keeping me from completing MNASNet

**Comment by yf225** [comment]
@ShahriarSS I will look into it

**Comment by yf225** [comment]
@ShahriarSS Could you share the MNASNet example that you are working on? `nn::Sequential` in C++ API is not nestable by design, but we might be able to find a workaround for this issue.

**Comment by ShahriarSS** [comment]
@yf225 C++ version:
```
    layers->push_back(torch::nn::Conv2d(
        Options(3, 32, 3).padding(1).stride(2).with_bias(false)));
    layers->push_back(torch::nn::BatchNorm(
        torch::nn::BatchNormOptions(32).momentum(BN_MOMENTUM)));
    layers->push_back(torch::nn::Functional(modelsimpl::relu_));
    layers->push_back(torch::nn::Conv2d(
        Options(32, 32, 3).padding(1).stride(1).groups(32).with_bias(false)));
    layers->push_back(torch::nn::BatchNorm(
        torch::nn::BatchNormOptions(32).momentum(BN_MOMENTUM)));
    layers->push_back(torch::nn::Functional(modelsimpl::relu_));
    layers->push_back(torch::nn::Conv2d(
        Options(32, 16, 1).padding(0).stride(1).with_bias(false)));
    layers->push_back(torch::nn::BatchNorm(
        torch::nn::BatchNormOptions(16).momentum(BN_MOMENTUM)));

    layers->push_back(stack(16, depths[0], 3, 2, 3, 3, BN_MOMENTUM));
    layers->push_back(stack(depths[0], depths[1], 5, 2, 3, 3, BN_MOMENTUM));
    layers->push_back(stack(depths[1], depths[2], 5, 2, 6, 3, BN_MOMENTUM));
    layers->push_back(stack(depths[2], depths[3], 3, 1, 6, 2, BN_MOMENTUM));
    layers->push_back(stack(depths[3], depths[4], 5, 2, 6, 4, BN_MOMENTUM));
    layers->push_back(stack(depths[4], depths[5], 3, 1, 6, 1, BN_MOMENTUM));

    layers->push_back(torch::nn::Conv2d(
        Options(depths[5], 1280, 1).padding(0).stride(1).with_bias(false)));
    layers->push_back(torch::nn::BatchNorm(
        torch::nn::BatchNormOptions(1280).momentum(BN_MOMENTUM)));
    layers->push_back(torch::nn::Functional(modelsimpl::relu_));

    classifier = torch::nn::Sequential(torch::nn::Dropout(dropout),
                                       torch::nn::Linear(1280, num_classes));
```

Python code:
```
        layers = [
            # First layer: regular conv.
            nn.Conv2d(3, 32, 3, padding=1, stride=2, bias=False),
            nn.BatchNorm2d(32, momentum=_BN_MOMENTUM),
            nn.ReLU(inplace=True),
            # Depthwise separable, no skip.
            nn.Conv2d(32, 32, 3, padding=1, stride=1, groups=32, bias=False),
            nn.BatchNorm2d(32, momentum=_BN_MOMENTUM),
            nn.ReLU(inplace=True),
            nn.Conv2d(32, 16, 1, padding=0, stride=1, bias=False),
            nn.BatchNorm2d(16, momentum=_BN_MOMENTUM),
            # MNASNet blocks: stacks of inverted residuals.
            _stack(16, depths[0], 3, 2, 3, 3, _BN_MOMENTUM),
            _stack(depths[0], depths[1], 5, 2, 3, 3, _BN_MOMENTUM),
            _stack(depths[1], depths[2], 5, 2, 6, 3, _BN_MOMENTUM),
            _stack(depths[2], depths[3], 3, 1, 6, 2, _BN_MOMENTUM),
            _stack(depths[3], depths[4], 5, 2, 6, 4, _BN_MOMENTUM),
            _stack(depths[4], depths[5], 3, 1, 6, 1, _BN_MOMENTUM),
            # Final mapping to classifier input.
            nn.Conv2d(depths[5], 1280, 1, padding=0, stride=1, bias=False),
            nn.BatchNorm2d(1280, momentum=_BN_MOMENTUM),
            nn.ReLU(inplace=True),
        ]
```
The problem is with the stack function that returns a Sequential. Here is stack:
```
torch::nn::Sequential stack(int64_t input, int64_t output, int64_t kernel,
                            int64_t stride, double exp_factor, int64_t repeats,
                            double bn_momentum)
{
    assert(repeats >= 1);

    torch::nn::Sequential seq;
    seq->push_back(MNASNetInvertedResidual(input, output, kernel, stride,
                                           exp_factor, bn_momentum));

    for (int64_t i = 1; i < repeats; ++i)
        seq->push_back(MNASNetInvertedResidual(output, output, kernel, 1,
                                               exp_factor, bn_momentum));

    return seq;
}
```

I can wrap the inner sequential inside another Module but the output python model must be loadable in C++ model.

**Comment by yf225** [comment]
@ShahriarSS Is the Python code also implemented by us? I think wrapping the inner sequential inside another Module would be a good solution for this problem, but Python side needs to have the same structure as well.

**Comment by ShahriarSS** [comment]
@yf225 yes the python model exists in torchvision. I can start start a PR changing the python code. Should I?
@fmassa  what do you think?

**Comment by yf225** [comment]
@fmassa Do you think it's okay to wrap any inner `nn.Sequential` inside another `nn.Module` for torchvision Python models? This is mostly because of a fundamental limitation in C++ frontend - in order to support the `nn::Sequential` returning any type, its `forward()` method has to be templatized, which prevents `nn::Sequential` from being nested.

An alternative approach would be to not support `nn::Sequential` returning any type (and only return Tensor type), but I think we should support it because the same works in Python frontend:
```python
class M(torch.nn.Module):
    def forward(self, x):
        return 1

model = torch.nn.Sequential(
    torch.nn.Linear(3, 5),
    M(),
)

a = model(torch.randn(3))
```

**Comment by ShahriarSS** [comment]
@yf225 How about this?

```
struct StackSequentailImpl : torch::nn::SequentialImpl
{
    using SequentialImpl::SequentialImpl;

    torch::Tensor forward(torch::Tensor x)
    {
        return SequentialImpl::forward(x);
    }
};

TORCH_MODULE(StackSequentail);

StackSequentail stack(int64_t input, int64_t output, int64_t kernel,
                      int64_t stride, double exp_factor, int64_t repeats,
                      double bn_momentum)
```

And then we can use StackSequential inside the main Sequential.

**Comment by yf225** [comment]
@ShahriarSS I think adding `StackSequential` as a custom module in the example is a good idea, as currently we don't want to un-templatize the forward function of `nn::Sequential`. In the future, if we have more user requests for nested `nn::Sequential` without custom wrapper, we might consider adding `nn::Sequential` with special return types, such as `nn::TensorSequential`, although it would be a divergence from the Python API because Python side doesn't have it.

**Comment by soumith** [comment]
> @fmassa Do you think it's okay to wrap any inner nn.Sequential inside another nn.Module for torchvision Python models? 

No, we shouldn't do this for Python / torchvision

I would actually propose that we de-templatize `nn::Sequential` and assume it returns a `Tensor`, and then introduce a `nn::MultiSequential` or something that allows returning anything

**Comment by ShahriarSS** [comment]
So @yf225 what is the course of action here? If the changes that @soumith proposed are as simple as renaming ```nn::Sequential``` and adding a ```nn::MultiSequential``` under wrapping it I can make the changes.

**Comment by yf225** [comment]
@ShahriarSS I think we should take the following actions here:

1. Rename the current `nn::Sequential` to `nn::AnySequential` (which might be more consistent with the naming of other modules such as `AnyModule`).
2. Add a new `nn::Sequential` class that wraps `nn::AnySequential` and only returns a `Tensor` from its `forward` method.

**Comment by ShahriarSS** [comment]
@yf225 I will start a PR fixing this. Also how will we do an ```static_assert``` when forward function of ```nn::Sequential``` is not a template? There will be a compilation error when using forward function as template.

**Comment by yf225** [comment]
@ShahriarSS I am not entirely sure if this would work, but perhaps we could make `forward` function of `nn::Sequential` contain a template type with a default value, and then in the function body check if the template type is equal to the default value. This way we can catch the `float output = sequential->forward<float>(input)` use cases. Note that the return type of `forward` of `nn::Sequential` is still `Tensor`, so nesting `nn::Sequential` should work.

**Comment by yf225** [comment]
Discussed with @ShahriarSS offline, and the resolution is:

If you need to use `nn::Sequential`s inside each other you can subclass `nn::Sequential` and write a non-templatized forward function for it. You can checkout https://github.com/pytorch/vision/blob/2f46070f3cb1ea894d82578f3dc5677f82f34958/torchvision/csrc/models/mnasnet.cpp#L59 for an example on how to do this.

Docs for this resolution is added by https://github.com/pytorch/pytorch/pull/23939.
