### ISSUE TITLE
AT_ERROR macro changed, now causes g++/clang compilation errors

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#22300]
## 🐛 Bug

This code pattern:

```
void errfail() {
 if(true)
  AT_ERROR("err");
 else
  AT_ERROR("false");
}
```
generates 
fatal error: expected expression

on gcc & clang.

The workaround is to introduce braces, e.g.
```
 if(true) {
  AT_ERROR("err");
 } else {
  AT_ERROR("false");
 }
```
This error was not present in version 1.1.0 but I see it now from Tues (Jun 25) build.
(?)

**Comment by colesbury** [comment]
@ezyang the issue is the extra semicolon in the `do {...} while(false)`. it makes the single statement into a compound statement.

**Comment by ezyang** [comment]
Aha! So we should not have a trailing semicolon. That makes sense to me. Patch coming.

**Comment by meganset** [comment]
Thanks for the quick fix.

Not sure if AT_ERROR going away completely in favor of TORCH_CHECK(false,..)
but I would find it useful to still have
TORCH_ERROR(...)
