### ISSUE TITLE
Installing previous versions of pytorch using conda throws HTTP 400 bad request

### ISSUE THREAD

**Issue by geetickachauhan** [pytorch/pytorch#22311]
## 📚 Documentation

As per the description at `https://pytorch.org/get-started/previous-versions/` I use `conda install pytorch=0.4.1 cuda90 -c pytorch` but keep getting the following error:

```
Fetching package metadata ...

CondaHTTPError: HTTP 400 BAD REQUEST for url <https://conda.anaconda.org/pytorch/linux-64/repodata.json>
Elapsed: 00:00.193385
CF-RAY: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
HTTPError('400 Client Error: Bad Request for url: https://conda.anaconda.org/pytorch/linux-64/repodata.json',)
```
I attempted to `conda install` pytorch from other channels, but 0.4 version does not seem available anymore.

**Comment by soumith** [comment]
0.4.0 and before were served from the `-c soumith` channel historically
