### ISSUE TITLE
torch::tensor(std::vector) does not work properly in Microsoft Visual Studio Windows

### ISSUE THREAD

**Issue by oroojlooy** [pytorch/pytorch#22318]
## 🐛 Bug
Given a `std::vector<long> vect = {1,2,3,4}`, I can use `auto tensor_ = torch::tensor(vect);` to create a tensor in Linux, but same code results in an error in Windows, and I get 
`E0304 no instance of overloaded function "torch::tensor" matches the argument list `
## To Reproduce

In the mnist code, in the beginning of main function add 
```
  std::vector<long> vect = { 1,2,3,4 };
  torch::Tensor tmp = torch::tensor(vect);
```
and build the code in Windows through `Microsoft Visual Studio 2019`.

## Expected behavior

It should create a tensor which contain the values from the `std:vector`. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): Windows 
 - How you installed PyTorch (`conda`, `pip`, source): I have downloaded built version of C++ 1.1 stable version 
 - Build command you used (if compiling from source): NA
 - Python version: NA
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA
 - Any other relevant information:

**Comment by ezyang** [comment]
What if you declare it as a vector of int rather than long? (Or `int64_t`, if you actually wanted 64-bit integers?)

**Comment by oroojlooy** [comment]
`int64_t` works fine.
