### ISSUE TITLE
Error installing pytorch vision

### ISSUE THREAD

**Issue by Six-wars** [pytorch/pytorch#2231]
Trying to install vision, I'm following guide from [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) and I get an error

	Processing dependencies for torchvision==0.1.8
	Searching for torch
	Reading https://pypi.python.org/simple/torch/
	Best match: torch 0.1.2.post1
	Downloading https://pypi.python.org/packages/5f/e9/bac4204fe9cb1a002ec6140b47f51affda1655379fe302a1caef421f9846/torch-0.1.2.post1.tar.gz#md5=e410e539fee324552e8099f24744ac93
	Processing torch-0.1.2.post1.tar.gz
	Writing /tmp/easy_install-9luKDK/torch-0.1.2.post1/setup.cfg
	Running torch-0.1.2.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9luKDK/torch-0.1.2.post1/egg-dist-tmp-GJ8cvk
	Traceback (most recent call last):
	  File "setup.py", line 34, in <module>
	    install_requires=requirements,
	  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    ....
    ....

     RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

     Please follow the instructions at http://pytorch.org/ to install with miniconda instead.

**Comment by chenzhekl** [comment]
PyTorch is not available on PyPI. Your should install it before torchvision.

http://pytorch.org/

**Comment by entrity** [comment]
@chenzhekl : Could you provide additional information in your response?

1. I visit http://pytorch.org/
1. On the form, I set (Linux, pip, 3.6, 8)
1. The form gives me the following 2 lines to run
1. I enter it, but the second line (`pip3 install pytorch`) fails with the message that @Six-wars posted

```
pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl 
pip3 install torchvision
```

So how can I install pytorch before installing torchvision?

**Comment by bharadwaj003** [comment]
@entrity I am also stuck with the same problem. Did you find any solution ?

**Comment by entrity** [comment]
@bharadwaj003 : I ended up installing minconda and then using the instructions at [http://pytorch.org/](http://pytorch.org/) to install with conda instead of pip.

For my system, then:

```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
./Miniconda3-latest-Linux-x86_64.sh
# Follow prompts
. $HOME/.bashrc
conda install pytorch torchvision -c pytorch
```

**Comment by soumith** [comment]
@stiv-yakovenko what's the output of `pip install torchvision`?

**Comment by Kandarp2516** [comment]
Try pip install with  --no-deps 
Courtsey: https://discuss.pytorch.org/t/failed-instalation-with-pip3-for-torchvision/12667/6

**Comment by tiangexiao** [comment]
my pip version is 9.0.1 , so i use   `pip install torchvision `  instead of `pip3 install torchvision`  and successful

**Comment by ortizbje** [comment]
Follow the instructions here : https://pytorch.org/get-started/locally/

**Comment by BilalSaeedLM10** [comment]
So after **pip install torchvision** i was able to install only torchvision and 1 or 2 more packages but not the **torch**.. The error is given below:
Collecting torch (from torchvision)
  Using cached https://files.pythonhosted.org/packages/5f/e9/bac4204fe9cb1a002ec6140b47f51affda1655379fe302a1caef421f9846/torch-0.1.2.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\BILALS~1\AppData\Local\Temp\pip-install-4i_yh5l9\torch\setup.py", line 11, in <module>
        raise RuntimeError(README)
    RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

    Please follow the instructions at http://pytorch.org/ to install with miniconda instead.


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\BILALS~1\AppData\Local\Temp\pip-install-4i_yh5l9\torch\

**Comment by soumith** [comment]
@BilalSaeedLM10 please follow instructions at https://pytorch.org to install pytorch on windows correctly.

**Comment by Sowhardhhonnappa** [comment]
This works->
pip install torchvision --no-deps

**Comment by borhan-kazimipour** [comment]
This worked for me (to install torch and then torchvision separately): `pip --default-timeout=1000 install torch===1.5.0 -f https://download.pytorch.org/whl/torch_stable.html`
