### ISSUE TITLE
unable to load istream by using torch::jit::load(istream)

### ISSUE THREAD

**Issue by HappyKerry** [pytorch/pytorch#22327]
I saved a model in PyTorch V1.0.1 python using torch.jit.save. I tried to load the model in C++ using torch::jit::load("model.pt");it works, but it produced the following error while using torch::jit::load(istream)

 
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at inline_container.cc:130] . PytorchStreamReader failed checking magic number.

**Comment by HappyKerry** [comment]
@lantiga

**Comment by lantiga** [comment]
Hi @HappyKerry, can you share a minimal source snippet for the C++ part?

**Comment by HappyKerry** [comment]
@lantiga
 I have solved it ，thanks
1. read pt model to char buffer by using ifstream
2.change buffer to istream  
strstreambuf  buf(pModelData,length);
    std::istream in(&buf);
3、load istream using torch::jit::load

**Comment by vraivon** [comment]
> @lantiga
> I have solved it ，thanks
> 
> 1. read pt model to char buffer by using ifstream
> 
> 2.change buffer to istream
> strstreambuf buf(pModelData,length);
> std::istream in(&buf);
> 
> 3、load istream using torch::jit::load

I tried with what you said, but catch an exception as well.
Would you mind post the code that can load model with istream successfully？
