### ISSUE TITLE
Build source but can not found libcaffe2_gpu.so

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#22336]
![image](https://user-images.githubusercontent.com/21303438/60333135-deaf8880-99ca-11e9-9af5-8423db1b25c3.png)

Why there was no libcaffe2_gpu.so??

**Comment by peterjc123** [comment]
Because libcaffe2_gpu.so is now merged into libcaffe.so. As for the reasons, please refer to this post. https://github.com/pytorch/pytorch/pull/20774

**Comment by jinfagang** [comment]
@peterjc123  But I can not found libcaffe either, BTW, why 2019 we still have libcaffe?

**Comment by jinfagang** [comment]
If you mean libcaffe2.so I still can not find it either...

**Comment by peterjc123** [comment]
Oh sorry, it's now `libtorch.so`.

**Comment by mvmnt** [comment]
Hi @peterjc123 
Thanks for your info there about this.

I have a question however: for projects that depend on the libcaffe2_gpu.so, do we have to change those places that ask for the library to say libtorch.so instead of libcaffe2_gpu.so?
