### ISSUE TITLE
"post" releases break pipenv

### ISSUE THREAD

**Issue by frankcarey** [pytorch/pytorch#22344]
## 🐛 Bug

Same issue addressed in #10443 

## To Reproduce

`pipenv install torch` (current version is `1.1.0-post2`)

## Expected behavior

pytorch should install

## Additional context

It seems the support of pipenv resolving "post" releases is the true bug per the other ticket, but as a sanity check, is there a reason to create "post" releases in the first places instead of incrementing the patch version?

**Comment by soumith** [comment]
as a timeline guidance, i dont likely have time to push a non `post*` release until the next pytorch release end of july.

**Comment by soumith** [comment]
> but as a sanity check, is there a reason to create "post" releases in the first places instead of incrementing the patch version?

As posted on the other ticket, it's because we dont have any new commits, but we botched the binaries. The PEP says that in such a case one increments the build number, not the version number. And if you bump the build number, the PEP convention makes you add a `.postX`

**Comment by frankcarey** [comment]
@soumith Thanks for the feedback/reasoning so we understand why we're seeing those releases. Also thanks for a timeline which is helpful!

I guess that also means that me pegging the version to `1.1.0` isn't going to solve anything either as you say the binaries were botched, so I'll have to go back a full version where there was no `post` release. Feel free to close this ticket if you like.

**Comment by soumith** [comment]
@frankcarey the binaries were only botched on OSX, and they were botched in the sense that you'll just get an error on `import torch` unless you have `libomp.dylib` on your system. So it might be okay in your case, fyi.
