### ISSUE TITLE
Is it possible to build PyTorch with Caffe2 as a shared system library

### ISSUE THREAD

**Issue by kgizdov** [pytorch/pytorch#22366]
Seems like currently PyTorch can only build with Caffe2 built as a submodule and statically linked. As one of the maintainers of PyTorch for Arch Linux, I've been trying to provide Caffe2 and PyTorch together - basically having Caffe2 as a system lib and then having PyTorch build and link against it. However, so far those efforts have failed. Is this supported/possible at all? Could you point me in the direction to make this work?

**Comment by soumith** [comment]
this is not supported, and unlikely will be (by design). in fact, the objects are now compiled together in the same library.

I suggest you make the caffe2 package a stub, that depends on pytorch and have pytorch packaged the same way as we do our binaries

**Comment by kgizdov** [comment]
Cheers, thanks!
