### ISSUE TITLE
[doc] CTCLoss documentation format completely inconsistent with rest of documentation

### ISSUE THREAD

**Issue by henon** [pytorch/pytorch#22371]
## 📚 Documentation

Here is a screenshot of [CTCLoss](https://pytorch.org/docs/stable/nn.html#torch.nn.CTCLoss) with some of the inconsistencies / bugs highlighted:

![image](https://user-images.githubusercontent.com/44090/60384538-458e7980-9a7f-11e9-9d3e-3340ada665da.png)

Looking at all other modules it is clear that this module is formatted totally incorrectly / inconsistently. This is from a different module, but shows how it should be:

![image](https://user-images.githubusercontent.com/44090/60384577-afa71e80-9a7f-11e9-941d-c48d3aa6fc06.png)

**Comment by zhangguanheng66** [comment]
@zhiqwang Do you mind if you could take a look at this issue? Thanks for your contribution.

**Comment by zhiqwang** [comment]
@zhangguanheng66 @henon Actually it is debugged in the [master](https://pytorch.org/docs/master/nn.html#torch.nn.CTCLoss) branch of CTCLoss.

**Comment by zhangguanheng66** [comment]
@zhiqwang Thanks. So I will just close the issue.
