### ISSUE TITLE
[doc] nn.MultiheadAttention.forward parameters formatting incorrect

### ISSUE THREAD

**Issue by henon** [pytorch/pytorch#22373]
## 📚 Documentation

[MultiheadAttention.forward](https://pytorch.org/docs/stable/nn.html#torch.nn.MultiheadAttention.forward) parameters are not formatted as a bullet list which is inconsistent:

![image](https://user-images.githubusercontent.com/44090/60387557-4d611480-9aa5-11e9-91ae-f38b7504dfda.png)

also the description of some parameters doesn't make sense to me

**Comment by sebamenabar** [comment]
I think this may be fixed, see https://pytorch.org/docs/master/nn.html#transformer-layers

**Comment by SsnL** [comment]
yes, fixed on master :)
