### ISSUE TITLE
Dependency issues with torch.utils.tensorboard: "No module named past" and "No module named 'PIL'"

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#22389]
```
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> torch.__version__
'1.2.0.dev20190607'
```

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch.utils.tensorboard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 6, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa F401
  File "/miniconda/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 17, in <module>
    from ._convert_np import make_np
  File "/miniconda/lib/python3.7/site-packages/torch/utils/tensorboard/_convert_np.py", line 12, in <module>
    from caffe2.python import workspace
  File "/miniconda/lib/python3.7/site-packages/caffe2/python/workspace.py", line 15, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'
```

`pip install future` fixes this problem, but it should rather be added to the requirements.txt or mentioned explicitly in the docs.

However then another issue happens:
```
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    import torch.utils.tensorboard
  File "/miniconda/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 6, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa F401
  File "/miniconda/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 18, in <module>
    from ._embedding import make_mat, make_sprite, make_tsv, append_pbtxt
  File "/miniconda/lib/python3.7/site-packages/torch/utils/tensorboard/_embedding.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

Docs mention dependency on `pillow`, but only for `add_image` and `add_images`. I think it should not break during import.

**Comment by apaszke** [comment]
Note that the right fix for the `past.stringbase` is really to stop using the deprecated API (which is not that hard too...)

**Comment by vadimkantorov** [comment]
@apaszke You mean the `past` usage within ``torch.utils.tensorboard`, right? The tensorboard package itself hopefully is not deprecated yet :) :)

**Comment by apaszke** [comment]
Well the last frame that actually causes the error is `/miniconda/lib/python3.7/site-packages/caffe2/python/workspace.py`, so it originates from C2 not from TensorBoard bindings (they import C2 bits). `stringbase` is deprecated, so C2 is using those polyfills, but they should be relatively easy to replace.

**Comment by vadimkantorov** [comment]
should this not be more like `topic: dependency bug`? (at least about PIL - it could be lazily imported at `add_image` call, no?) cc @apaszke

**Comment by vadimkantorov** [comment]
cc @orionr

**Comment by orionr** [comment]
cc @lanpa @natalialunova @sanekmelnikov

**Comment by orionr** [comment]
Looks like `future` is already in requirements.txt? The list I'm seeing is

```
future
numpy
pyyaml
setuptools
six
typing
```

I agree that we should move `from PIL import Image` into make_sprite where it's required. Making the change.

**Comment by vadimkantorov** [comment]
@orionr Hmm. You are right. I've used a nightly build (I think it was from conda), maybe somehow it's not used as dependency for the package there?

**Comment by orionr** [comment]
@pjh5 or @kostmo, do you know whether conda uses the requirements.txt?

**Comment by pjh5** [comment]
Conda doesn't use requirements.txt ; they're built with conda-build so it uses this meta.yaml, specifically https://github.com/pytorch/builder/blob/master/conda/pytorch-nightly/meta.yaml#L31 .

But more generally, I don't think we'll add anything as a req for the nightlies unless they're needed by core functionality are necessary for decent performance (like numpy). i.e. Caffe2 doesn't work out of the box on the nightlies without installing additional python packages either.

**Comment by vadimkantorov** [comment]
Somehow the future requirement in meta.yaml is ignored? I just installed the yesterday's nightly, and it seems to ignore the metal.yaml requireement.

Why should nightlies be much different from the regular builds in this respect? (I think switching from nightlies and back should be seamless wrt dependencies required from the user) @soumith
