### ISSUE TITLE
How to apply transfer learning for custom  object detection ?

### ISSUE THREAD

**Issue by spatiallysaying** [pytorch/pytorch#22381]
## ❓ Questions and Help

Is there an example to apply transfer learning for **custom**  object detection.
[https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html](https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html)

Reference:-
https://www.learnopencv.com/faster-r-cnn-object-detection-with-pytorch/

**Comment by zhangguanheng66** [comment]
@fmassa Do you have an example for it? Thanks.
@spatiallysaying You could also ask the questions in [pytorch/vision](https://github.com/pytorch/vision) as more vision expert users are there.
