### ISSUE TITLE
[jit] NameError: name '_CachedForward' is not defined

### ISSUE THREAD

**Issue by jamarshon** [pytorch/pytorch#22399]
## [jit] NameError: name '_CachedForward' is not defined
I install pytorch 1.1.0 using conda and then I try importing pytorch with jit disabled by calling PYTORCH_JIT=0. Specifically in torchaudio, I call
```
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ PYTORCH_JIT=0 python setup.py develop
```
and I get the following error:
```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from torch.utils.cpp_extension import BuildExtension, CppExtension
  File "/Users/jamarshon/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 291, in <module>
    import torch.jit
  File "/Users/jamarshon/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1501, in <module>
    class TopLevelTracedModule(TracedModule):
  File "/Users/jamarshon/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1502, in TopLevelTracedModule
    forward = _CachedForward()
NameError: name '_CachedForward' is not defined
```
It seems `_CachedForward` is defined in the jit `_enabled` if statement branch and `TopLevelTracedModule` depends on it. This causes an error as  `TopLevelTracedModule` is in the global scope and does not rely on `_enabled`.

## Environment
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Mac OSX 10.14.5
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: 1.1.0
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.1.0
[pip] torchaudio==0.2
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl-include               2019.4                      233  
[conda] mkl-service               1.1.2            py37hfbe908c_5  
[conda] mkl_fft                   1.0.10           py37h5e564d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0  
[conda] pytorch                   1.1.0                   py3.7_0    pytorch
[conda] torchaudio                0.2                       dev_0    <develop>
[conda] torchvision               0.3.0             py37_cuNone_1    pytorch

**Comment by driazati** [comment]
Could you try the nightly version instead? This should be fixed in #20120. Feel free to re-open this issue if you still have problems.
