### ISSUE TITLE
sort method with descending equal true got a wrong result

### ISSUE THREAD

**Issue by tiandiweizun** [pytorch/pytorch#22393]
## To Reproduce

1. when using lstm, we need to sort the input sentence by length, but I get a wrong result.
1. length=torch.tensor([9, 6, 2, 2, 3, 2, 1, 1, 3, 2, 1, 1, 2, 2, 2, 3, 1, 1, 2, 1, 2, 2, 2, 1,
        1, 1, 3, 1, 1, 2, 2, 2])
Out:
tensor([9, 6, 2, 2, 3, 2, 1, 1, 3, 2, 1, 1, 2, 2, 2, 3, 1, 1, 2, 1, 2, 2, 2, 1,
        1, 1, 3, 1, 1, 2, 2, 2])
1. length.sort(descending=True)
Out:
torch.return_types.sort(
values=tensor([9, 6, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1]),
indices=tensor([ 0,  1,  8, 26, 15,  4,  3, 18, 30, 29,  2, 22, 21, 20,  5, 13, 31,  9,
        12, 14, 27, 25,  7, 17, 28, 19, 10,  6, 24, 16, 11, 23]))

1. torch.tensor(range(b.size(0))).long().mul(b.eq(3).long())
Out:
tensor([ 0,  0,  0,  0,  4,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0, 15,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0, 26,  0,  0,  0,  0,  0])

## Expected behavior

I think the result should be 
[0,  1,  4,  8,  15,  26,  2,  3,  5,  9,   12, 13, 14, 18,  20, 21, 22,  29, 30, 31,  6,  7, 10, 11, 16, 17, 19,  23, 24, 25, 27, 28]

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): win10
 - How you installed PyTorch (`conda`, `pip`, source): pip3
 - Build command you used (if compiling from source): 
 - Python version: 3.6.5
 - CUDA/cuDNN version: cpu
 - GPU models and configuration:
 - Any other relevant information:

**Comment by colesbury** [comment]
The behavior is correct. The values are sorted in descending order and the indices are the location of the values.

torch.sort does not use a [stable sorting](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability) algorithm so the choice of which '3's come first is arbitrary
