### ISSUE TITLE
Error building torch from source for python 2.7 on macOS

### ISSUE THREAD

**Issue by Fuchai** [pytorch/pytorch#2240]
Hello,

Here is the error.
I'm running macOS 10.12.6 (16G29), python 2.7 on anaconda 3, CUDA 8.0.90, Apple LLVM version 8.0.0 (clang-800.0.42.1). I installed LLVM 8.0.0 specifically since it's the one listed on cuda docs.
I have successfully built pyTorch from source for python 3.6 on this computer before, so I'm clueless how this is happening.
I will just use python 3 for now. Hope this information is helpful to you.

`torch/csrc/autograd/functions/convolution.cpp:188:20: error: no viable
      conversion from 'std::vector<long>' to 'IntList' (aka
      'ArrayRef<long long>')
    output.resize_(output_size(input, weight));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen/ArrayRef.h:34:9: note: 
      candidate constructor (the implicit copy constructor) not viable: no known
      conversion from 'std::vector<long>' to 'const at::ArrayRef<long long> &'
      for 1st argument
  class ArrayRef {
        ^
/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen/ArrayRef.h:34:9: note: 
      candidate constructor (the implicit move constructor) not viable: no known
      conversion from 'std::vector<long>' to 'at::ArrayRef<long long> &&' for
      1st argument
/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen/ArrayRef.h:57:18: note: 
      candidate constructor not viable: no known conversion from
      'std::vector<long>' to 'const long long &' for 1st argument
    /*implicit*/ ArrayRef(const T &OneElt)
                 ^
/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen/ArrayRef.h:83:18: note: 
      candidate constructor not viable: no known conversion from
      'std::vector<long>' to 'const std::initializer_list<long long> &' for 1st
      argument
    /*implicit*/ ArrayRef(const std::initializer_list<T> &Vec)
                 ^
/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen/ArrayRef.h:70:18: note: 
      candidate template ignored: could not match 'long long' against 'long'
    /*implicit*/ ArrayRef(const std::vector<T, A> &Vec)
                 ^
/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen/ArrayRef.h:75:28: note: 
      candidate template ignored: could not match 'array' against 'vector'
    /*implicit*/ constexpr ArrayRef(const std::array<T, N> &Arr)
                           ^
/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen/ArrayRef.h:80:28: note: 
      candidate template ignored: could not match 'const long long [N]' against
      'std::vector<long>'
    /*implicit*/ constexpr ArrayRef(const T (&Arr)[N]) : Data(Arr), Length(N) {}
                           ^
/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen/TensorMethods.h:13:41: note: 
      passing argument to parameter 'size' here
inline Tensor & Tensor::resize_(IntList size) {
                                        ^
clang -fno-strict-aliasing -I/Users/JasonHu/anaconda3/envs/condapy2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/JasonHu/Downloads/pytorch-master -I/Users/JasonHu/Downloads/pytorch-master/torch/csrc -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/TH -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THPP -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THNN -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen -I/Users/JasonHu/anaconda3/envs/condapy2/lib/python2.7/site-packages/numpy/core/include -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/Users/JasonHu/anaconda3/envs/condapy2/include/python2.7 -c /Users/JasonHu/Downloads/pytorch-master/torch/csrc/generated/TensorHalf.cpp -o build/temp.macosx-10.7-x86_64-2.7/Users/JasonHu/Downloads/pytorch-master/torch/csrc/generated/TensorHalf.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
clang -fno-strict-aliasing -I/Users/JasonHu/anaconda3/envs/condapy2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/JasonHu/Downloads/pytorch-master -I/Users/JasonHu/Downloads/pytorch-master/torch/csrc -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/TH -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THPP -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THNN -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen -I/Users/JasonHu/anaconda3/envs/condapy2/lib/python2.7/site-packages/numpy/core/include -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/Users/JasonHu/anaconda3/envs/condapy2/include/python2.7 -c /Users/JasonHu/Downloads/pytorch-master/torch/csrc/generated/TensorInt.cpp -o build/temp.macosx-10.7-x86_64-2.7/Users/JasonHu/Downloads/pytorch-master/torch/csrc/generated/TensorInt.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
1 error generated.
clang -fno-strict-aliasing -I/Users/JasonHu/anaconda3/envs/condapy2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/JasonHu/Downloads/pytorch-master -I/Users/JasonHu/Downloads/pytorch-master/torch/csrc -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/TH -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THPP -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THNN -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/ATen -I/Users/JasonHu/anaconda3/envs/condapy2/lib/python2.7/site-packages/numpy/core/include -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/Users/JasonHu/Downloads/pytorch-master/torch/lib/tmp_install/include/THCUNN -I/usr/local/cuda/include -I/Users/JasonHu/anaconda3/envs/condapy2/include/python2.7 -c /Users/JasonHu/Downloads/pytorch-master/torch/csrc/generated/TensorChar.cpp -o build/temp.macosx-10.7-x86_64-2.7/Users/JasonHu/Downloads/pytorch-master/torch/csrc/generated/TensorChar.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib -DWITH_CUDNN
error: command 'clang' failed with exit status 1`

**Comment by fabianmurariu** [comment]
Any luck getting past this one?

**Comment by fabianmurariu** [comment]
going back to f1fd4ac7edeb2477404883b21c3c4fe8420c0757 makes the build work

**Comment by kureta** [comment]
I am getting the same error while trying to compile on MacOS 10.12.6. Any suggestions?

**Comment by qbx2** [comment]
Succeeded building torch from source on the latest commit. Don't forget to `python3 setup.py clean` before build.

**Comment by alykhantejani** [comment]
@Fuchai I think [this PR](https://github.com/pytorch/pytorch/pull/2319) fixes your issue and has now been merged. Please try and build again from master and let us know :)

**Comment by Fuchai** [comment]
Yes the build from master was successful on both python 3 and python 2. Thank you!
`python setup.py clean` could be helpful. Not sure whether I did it last time.
