### ISSUE TITLE
Implementing hashing (2016 paper) to improve computational performance by 95%

### ISSUE THREAD

**Issue by devinbostIL** [pytorch/pytorch#2241]
I've been looking into this technique: [Scalable and Sustainable Deep Learning via Randomized Hashing](https://arxiv.org/pdf/1602.08194.pdf) that allegedly "uses only 5% of the total multiplications, while
keeping on average within 1% of the accuracy of the original model." It looks pretty straightforward and appears to be suitable for PyTorch, so I'd like some guidance on how we might go about implementing this functionality unless it would have undesirable consequences that are not immediately apparent to me.

**Comment by soumith** [comment]
questions and discussions are usually better at https://discuss.pytorch.org
