### ISSUE TITLE
[ROCm] Package hipification scripts in distribution

### ISSUE THREAD

**Issue by iotamudelta** [pytorch/pytorch#22417]
## 🚀 Feature
Distribute the hipification scripts in `tools/amd_build/pyHIPIFY` to access them for hipification of extensions such as torchvision.

## Motivation
In #22091 , we aim to port the CUDAExtensions feature to support the HIP/ROCm stack. To make it easier for users, @ezyang proposed to add the hipification script to the distribution to get access to it from CUDAExtensions, thereby allowing us to hipify the extension sources (such as torchvision) on the fly as opposed to ahead of time.

## Pitch

Distribute the `pyHIPIFY` sources, make them accessible from CUDAExtensions.

## Alternatives

The alternative is to hipify extension sources ahead of time, creating HIP and CUDA sources.

## Additional context

Primary focus/target is to get torchvision including CUDA sources to work on ROCm.

**Comment by iotamudelta** [comment]
CC @ashishfarmer

**Comment by ezyang** [comment]
For the record: I support this plan.  It seems like the only reasonable
way to get torchvision to work under AMD.

Excerpts from iotamudelta's message of 2019-07-01 15:39:03 -0700:
> CC @ashishfarmer
>

**Comment by iotamudelta** [comment]
Resolved with #27425
