### ISSUE TITLE
1 - bool tensor should throw an error

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#22432]
This [PR](https://github.com/pytorch/pytorch/pull/21113) raised a question about how should we treat bool tensor with respect to other types and operations with them. One of this question was what to do with a case like this: 

```
a = torch.tensor([1, 1, 0], dtype=torch.bool)
print(1 - a)
```

After couple offline discussions with the team, we decided to forbid this behavior for now.

**Comment by gchanan** [comment]
It would be good to document why this is the case.

**Comment by izdeby** [comment]
@gchanan, after checking with the numpy im not sure if we should ban this behavior or if we should do type promotion. Please see this comparison between numpy behavior and ours 

```
numpyA            :  [ True False]                                                                                          
1 - numpyA        :  [0 1]                                                                                                 
numpyA - 1        :  [ 0 -1]                                                                               

torchA     :  tensor([ True, False])
1 - torchA :  tensor([True, True])
torchA - 1 :  tensor([True, True])

```

**Comment by nairbv** [comment]
Some examples:

```
>>> b
array([ True,  True])
>>> -b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.
>>> b - b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
>>> b + b
array([ True,  True])
>>>
>>>
>>> import torch
>>> bt = torch.ones(2, dtype=torch.bool)
>>> bt - bt
tensor([True, True])
>>> -bt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "neg_cpu" not implemented for 'Bool'
>>> bt + bt
tensor([True, True])
>>>
```

The main current differences I'm noticing are that we support `bool_tensor - bool_tensor` where numpy does not, and that numpy has explicit recommendations in the error messages for `-`

Python itself just treats these like ints:
```
>>> True - True
0
>>> True + False
1
>>> True + True
2
>>> -True
-1
```

It would be nice if we could be consistent with python, but python treatment isn't consistent with numpy, so we have to decide. 

Neither is consistent with our current odd behavior where `true_tensor - true_tensor => true_tensor`. No matter what we do we should fix that particular case to return something sensible.

**Comment by gchanan** [comment]
This has been completed.
