### ISSUE TITLE
linux python3.6 pip install command wrong

### ISSUE THREAD

**Issue by sshuair** [pytorch/pytorch#2243]
the official site install instruction wrong:
- OS : linux
- Package Manager : pip   
- Python: 3.6  
- CUDA: None

and the `Run this command` is:

```
pip install http://download.pytorch.org/whl/cu75/torch-0.1.12.post2-cp36-cp36m-linux_x86_64.whl 
pip install torchvision
```

It's a GPU version not CPU version.

Hope fix it.

<img width="1032" alt="2017-07-29 10 28 00" src="https://user-images.githubusercontent.com/5787131/28745575-8c8e523c-74ad-11e7-9aaa-cfad3726bbe0.png">

**Comment by CDLuminate** [comment]
+1. The GPU version ships many big blobs such as libcudnn and MKL etc.
Providing a pure CPU version may decrease the whl package size significantly.

**Comment by soumith** [comment]
@sshuair we provide one package that has everything and supports GPU and CPU. This is better and consistent packaging in our opinion. This is not a typo/mistake.
