### ISSUE TITLE
RuntimeError when using multiple DistributedDataParallel model

### ISSUE THREAD

**Issue by krumo** [pytorch/pytorch#22436]
## 🐛 Bug

I'm trying to implement distributed adversarial training in PyTorch. Thus, in my program pipeline I need to forward the output of one DDP model to another one. When I run the code in distributed setting, the following error is throwed:

> RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /opt/conda/conda-bld/pytorch-nightly_1561957689202/work/torch/csrc/distributed/c10d/reducer.cpp:518)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fa248f906d5 in /export/home/haoran/anaconda3/envs/torch1.2/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::prepare_for_backward(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0x666 (0x7fa26f9d0896 in /export/home/haoran/anaconda3/envs/torch1.2/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x6df3b8 (0x7fa26f9c43b8 in /export/home/haoran/anaconda3/envs/torch1.2/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x1fc7f0 (0x7fa26f4e17f0 in /export/home/haoran/anaconda3/envs/torch1.2/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #31: main + 0x16d (0x400c1d in /export/home/haoran/anaconda3/envs/torch1.2/bin/python)
frame #32: __libc_start_main + 0xf5 (0x7fa285e06c05 in /lib64/libc.so.6)
frame #33: /export/home/haoran/anaconda3/envs/torch1.2/bin/python() [0x4009e9]

## To Reproduce
Running the following code with DistributedDataParallel

```
import argparse
import torch
import torch.nn as nn
import torch.backends.cudnn as cudnn

def get_arguments():
    """Parse all the arguments provided from the CLI.

    Returns:
      A list of parsed arguments.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--local_rank", type=int, default=0)
    return parser.parse_args()

args = get_arguments()

def main():
    """Create the model and start the training."""
    torch.manual_seed(0)

    cudnn.enabled = True
    cudnn.deterministic = True

    # Create network    
    class LinearNet(nn.Module):
        def __init__(self, input_nc, output_nc):
            super(LinearNet, self).__init__()
            self.l1 = nn.Linear(
                    input_nc,
                    output_nc
                )
            self.l2 = nn.Linear(
                    output_nc,
                    output_nc
                )
        def forward(self, x):
            x = self.l1(x)
            y = self.l2(x)
            return x, y
            
    num_gpus = int(torch.cuda.device_count())
    args.distributed = num_gpus > 1
    if args.distributed:
        torch.cuda.set_device(args.local_rank)
        torch.distributed.init_process_group(
                backend="nccl", init_method="env://"
            )

    model = LinearNet(3, 2)
    model_D = LinearNet(2, 1)
    model = model.to(torch.device("cuda"))
    model_D = model_D.to(torch.device("cuda"))

    if args.distributed:
        model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
        pg1 = torch.distributed.new_group(range(torch.distributed.get_world_size()))
        model = torch.nn.parallel.DistributedDataParallel(
            model, device_ids=[args.local_rank], output_device=args.local_rank,
            broadcast_buffers=True, process_group=pg1
        )
        pg2 = torch.distributed.new_group(range(torch.distributed.get_world_size()))
        model_D = torch.nn.parallel.DistributedDataParallel(
            model_D, device_ids=[args.local_rank], output_device=args.local_rank,
            broadcast_buffers=True, process_group=pg2
        )
    
    L1_loss = torch.nn.L1Loss(reduction="mean")
    bce_loss = torch.nn.BCEWithLogitsLoss()

    optimizer = torch.optim.SGD(model.parameters(),
                          lr=1e-2, momentum=0.9, weight_decay=5e-4)
    optimizer.zero_grad()
    optimizer_D = torch.optim.Adam(model_D.parameters(), lr=1e-2, betas=(0.9, 0.99))
    optimizer_D.zero_grad()

    model.train()
    model_D.train()
    
    real_label = 1
    fake_label = 0
    
    for epoch in range(5):
        src_input_data = torch.randn((1,3)).cuda()
        src_label = torch.randn((1,2)).cuda()
        tgt_input_data = torch.randn((1,3)).cuda()

        optimizer.zero_grad()
        optimizer_D.zero_grad()
        model.zero_grad()
        model_D.zero_grad()
        
        # train generator
        fea, pred = model(src_input_data)
        loss1 = L1_loss(pred, src_label)
        loss1.backward()
        
        tgt_fea, tgt_pred = model(tgt_input_data)
        _, tgt_D_pred = model_D(tgt_fea)
        loss_adv = bce_loss(tgt_D_pred, tgt_D_pred.new_full(tgt_D_pred.size(), real_label))
        loss_adv.backward()
        
        optimizer.step()

        # # train discriminator
        # ...

if __name__ == '__main__':
    main()

```

## Expected behavior
The code could run successfully without throwing error.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.2.0.dev20190701
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 5.4.0
CMake version: version 3.6.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla P40
GPU 1: Tesla P40
GPU 2: Tesla P40
GPU 3: Tesla P40

Nvidia driver version: 390.25
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.2.0.dev20190701
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.4                      243    defaults
[conda] mkl_fft                   1.0.12           py36ha843d7b_0    defaults
[conda] mkl_random                1.0.2            py36hd81dba3_0    defaults
[conda] pytorch-nightly           1.2.0.dev20190701 py3.6_cuda9.0.176_cudnn7.5.1_0    pytorch

**Comment by ifedan** [comment]
Please, try one of the suggested options:

(1) passing the keyword argument find_unused_parameters=True to torch.nn.parallel.DistributedDataParallel; 
(2) making sure all forward function outputs participate in calculating loss. 
If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's forward function. Please include the loss function and the structure of the return value of forward of your module when reporting this issue (e.g. list, dict, iterable). 

If the issue will still exist, please, reopen this issue.

**Comment by pietern** [comment]
@krumo I double checked your repro to figure out if this is a real issue or not and found that even setting `find_unused_parameters=True` won't help you here. It's a simple example of course, but you're not using the `tgt_pred` variable in your loss computation. The model's forward function returns it which is an indication for DDP that it will receive a gradient. Then when it doesn't, and you try to run the next iteration, it raises an error, because the previous iteration didn't finish. I recommend you return only the tensor you plan to use in the loss computation.

**Comment by liming312** [comment]
Is there any way to see which parameters on earth are unused? It is useless to simply give this RuntimeError or simply set find_unused_parameters to True.

**Comment by QiuSYang** [comment]
> @krumo I double checked your repro to figure out if this is a real issue or not and found that even setting `find_unused_parameters=True` won't help you here. It's a simple example of course, but you're not using the `tgt_pred` variable in your loss computation. The model's forward function returns it which is an indication for DDP that it will receive a gradient. Then when it doesn't, and you try to run the next iteration, it raises an error, because the previous iteration didn't finish. I recommend you return only the tensor you plan to use in the loss computation.

@pietern I had the same problem with just one GPU，I have modified the code according to what you said。

**Comment by Philipflyg** [comment]
> Is there any way to see which parameters on earth are unused? It is useless to simply give this RuntimeError or set find_unused_parameters to True.

https://discuss.pytorch.org/t/how-to-find-the-unused-parameters-in-network/63948

I met the same problem and I found this topic. It works for me. (though it's been a long time for you)
