### ISSUE TITLE
onnx converter，all layers name change to num，any way to do not use number as layer name

### ISSUE THREAD

**Issue by tianylijun** [pytorch/pytorch#22438]
During i do quantization, I want to use original layer name to get quantization param, but onnx converter change the layer name to number, how to map ？ any way to do not use number as layer name ?  does Pytorch has it's own model format ?

**Comment by ifedan** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
