### ISSUE TITLE
fused multiply add returns wrong result for bool tensor

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#22430]
**`torch.add(torch.zeros(2,3, dtype=torch.bool), torch.ones(2,3, dtype=torch.bool), alpha=0)`**

Expected result:
```
tensor([[False, False, False],
             [False, False, False]], dtype=torch.bool)
```

Actual result:
```
tensor([[True, True, True],
             [True, True, True]], dtype=torch.bool)
```

**Comment by gchanan** [comment]
The actual and expected result are the same?  I think the expected result should be Falses.

**Comment by izdeby** [comment]
Fixed via https://github.com/pytorch/pytorch/pull/23044
