### ISSUE TITLE
Add derivatives for the `weight` parameter of `torch.lerp`

### ISSUE THREAD

**Issue by chenzhekl** [pytorch/pytorch#22444]
## 🚀 Feature

Add derivatives for the `weight` parameter of `torch.lerp`.

## Motivation

It's common to optimize not only the two end points but also the `weight` when using `torch.lerp`, and it seems to be straightforward to define the gradients as well.

## Pitch

Add the derivates for `weight` in `torch.lerp`

## Alternatives

I'm currently calculating `lerp` by manually computing the formula `out = start + weight * (end - start)`

## Additional context

```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> start = torch.tensor([1.0, 2.0, 3.0])
>>> end = torch.tensor([5.0, 5.0, 5.0])
>>> weight = torch.tensor([0.5, 0.5, 0.5])
>>> torch.lerp(start, end, weight)
tensor([3.0000, 3.5000, 4.0000])
>>> weight.requires_grad_(True)
tensor([0.5000, 0.5000, 0.5000], requires_grad=True)
>>> torch.lerp(start, end, weight)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: the derivative for 'weight' is not implemented
>>> 
```

**Comment by Ridhwanluthra** [comment]
I can volunteer to work on this. It would really help me if someone could give me a direction towards where to look for to begin working on this.
thanks
