### ISSUE TITLE
2 tensors for the output...Abou the libtorch | torch.jit.trace 

### ISSUE THREAD

**Issue by MenGuangwen-CN-0411** [pytorch/pytorch#22440]
I use torch.jit.trace as follow:

import torch
import torch.nn as nn

class simpleNet(nn.Module):
def init(self):
super(simpleNet, self).init()
self.layer1 = nn.Conv2d(3,16,3)
self.layer2 = nn.Conv2d(16,32,3)
self.layer3 = nn.Conv2d(32,64,3)

def forward(self, x):
    x = self.layer1(x)
    x1 = self.layer2(x)
    x2 = self.layer3(x1)
    return x1,x2
img = torch.rand(1, 3, 416, 416)
model = simpleNet()

traced_script_module = torch.jit.trace(model, img)
traced_script_module.save(“val_libtorch.pt”)

But i think there may be something wrong because there are two tensor about the model out put…
and in c++ api :
std::shared_ptr<torch::jit::script::Module> module = torch::jit::load("D:\\lib_test\\tensor_libtorch\\val_libtorch.pt");
	assert(module != nullptr);
	std::vector<torch::jit::IValue> inputs;
	inputs.push_back(torch::ones({ 1, 3, 416, 416 }));
	auto out_put = module->forward(inputs).toTensor();
    ...  
I will get  wrong

**Comment by zdevito** [comment]
Since you are returning two Tensors, the result value is actually going to be a Tuple, not a Tensor, so toTensor will fail. You can call `toTuple` to get the Tuple object and then extract the tensor:
```
auto output = module->forward(inputs);
auto t = output.toTuple()->elements()[0].toTensor(); // 1st output;
```

**Comment by soumith** [comment]
closing based on @zdevito's comment

**Comment by qinb** [comment]
@zdevito @soumith  But how to get 2rd output with libtorch-1.1.0 ?
I use this code: 
```
auto t = output.toTuple()->elements()[1].toTensor(); // 2rd output;
```
but i meet the error:
```
terminate called after throwing an instance of 'c10::Error'
  what():  isTensor() ASSERT FAILED at /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/include/ATen/core/ivalue.h:209, 
please report a bug to PyTorch. (toTensor at /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/include/ATen/core/ivalue.h:209)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f97fb6df441 in /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f97fb6ded7a in /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/lib/libc10.so)
frame #2: c10::IValue::toTensor() const & + 0x99 (0x454951 in ./roi_align_layer)
frame #3: main + 0xe60 (0x4506aa in ./roi_align_layer)
frame #4: __libc_start_main + 0xf5 (0x7f97d51bb3d5 in /usr/lib64/libc.so.6)
frame #5: ./roi_align_layer() [0x44d3d9]
```

**Comment by qinb** [comment]
> @zdevito @soumith But how to get 2rd output with libtorch-1.1.0 ?
> I use this code:
> 
> ```
> auto t = output.toTuple()->elements()[1].toTensor(); // 2rd output;
> ```
> 
> but i meet the error:
> 
> ```
> terminate called after throwing an instance of 'c10::Error'
>   what():  isTensor() ASSERT FAILED at /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/include/ATen/core/ivalue.h:209, 
> please report a bug to PyTorch. (toTensor at /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/include/ATen/core/ivalue.h:209)
> frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f97fb6df441 in /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/lib/libc10.so)
> frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f97fb6ded7a in /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/lib/libc10.so)
> frame #2: c10::IValue::toTensor() const & + 0x99 (0x454951 in ./roi_align_layer)
> frame #3: main + 0xe60 (0x4506aa in ./roi_align_layer)
> frame #4: __libc_start_main + 0xf5 (0x7f97d51bb3d5 in /usr/lib64/libc.so.6)
> frame #5: ./roi_align_layer() [0x44d3d9]
> ```

i'm so sorry, i solve this problem. i found that 2rd output is tuple tensor.

**Comment by billamiable** [comment]
I also encountered the error when converting to tensor having two tensors as output. It took me almost 2 days to solve that... Really recommend to mark this situation in the tutorial of libtorch, which can save others time in the future.. @soumith

**Comment by YongyuG** [comment]
> > @zdevito @soumith But how to get 2rd output with libtorch-1.1.0 ?
> > I use this code:
> > ```
> > auto t = output.toTuple()->elements()[1].toTensor(); // 2rd output;
> > ```
> > 
> > 
> > but i meet the error:
> > ```
> > terminate called after throwing an instance of 'c10::Error'
> >   what():  isTensor() ASSERT FAILED at /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/include/ATen/core/ivalue.h:209, 
> > please report a bug to PyTorch. (toTensor at /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/include/ATen/core/ivalue.h:209)
> > frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f97fb6df441 in /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/lib/libc10.so)
> > frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f97fb6ded7a in /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/lib/libc10.so)
> > frame #2: c10::IValue::toTensor() const & + 0x99 (0x454951 in ./roi_align_layer)
> > frame #3: main + 0xe60 (0x4506aa in ./roi_align_layer)
> > frame #4: __libc_start_main + 0xf5 (0x7f97d51bb3d5 in /usr/lib64/libc.so.6)
> > frame #5: ./roi_align_layer() [0x44d3d9]
> > ```
> 
> i'm so sorry, i solve this problem. i found that 2rd output is tuple tensor.

hi，how did you get your 2rd output, i got the same error as yours

**Comment by TomKrogmann** [comment]
@qinb @billamiable @YongyuG 
I ran into the exact same error. Can you tell me how to fix that? 
My forward method returns two tensors and I'm trying to load those two tensors properly in my C++ implementation. I only need to acess the first tensor of them afterwards.
