### ISSUE TITLE
Pytorch-C++ MaxPool2d

### ISSUE THREAD

**Issue by Michael-Bianconi** [pytorch/pytorch#22453]
## 🚀 Feature

A Pytorch-C++ implementation of torch.nn.MaxPool2d.

## Motivation

I'm unable to find an appropriate function in the C++ front-end that's analogous to torch.nn.MaxPool2d.

**Comment by ifedan** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.”
