### ISSUE TITLE
undefined symbol: THFloatTensor_expand in pytorch 0.4.1

### ISSUE THREAD

**Issue by Blade6570** [pytorch/pytorch#22452]
## ❓ Questions and Help
While writing custom c++ extension in Pytorch 0.3.1, it could find  THFloatTensor_expand in <TH.h>, however, in v0.4.1, it reports it as missing. Any suggestion? 

Note: I installed the Pytorch from pip/Ubuntu 18.04/cuda9.2

**Comment by soumith** [comment]
we no longer offer support for 0.3.1 or 0.4.1. Please use the latest PyTorch version
