### ISSUE TITLE
Comparisons no longer output ByteTensor

### ISSUE THREAD

**Issue by Atcold** [pytorch/pytorch#22450]
## 📚 Documentation
Comparisons used to output a `ByteTensor`, as pointed out by the doc (see below).

<img width="871" alt="Screenshot 2019-07-02 15 58 47" src="https://user-images.githubusercontent.com/2119355/60518807-8d610b00-9ce2-11e9-9dc0-6e85a0b4b526.png">

It looks it's not longer the case, as `dtype=uint8`.
Moreover, can anyone point me to the PR for this change as well?.

Still editing, hang on.

**Comment by vishwakftw** [comment]
cc: @izdeby

**Comment by Atcold** [comment]
Okay, something else happened.
`torch.sum()` does no longer output its input tensor type.

<img width="235" alt="Screenshot 2019-07-02 16 06 46" src="https://user-images.githubusercontent.com/2119355/60519284-8dadd600-9ce3-11e9-9461-f308fa6b00dd.png">

**Comment by Atcold** [comment]
Okay, I'm even more confused now.
No casting is performed by default.

<img width="869" alt="Screenshot 2019-07-02 16 15 34" src="https://user-images.githubusercontent.com/2119355/60520004-e92c9380-9ce4-11e9-9943-bcd1fa3db52e.png">

But, if I actually specify it I get an error.

<img width="777" alt="Screenshot 2019-07-02 16 17 20" src="https://user-images.githubusercontent.com/2119355/60520048-ffd2ea80-9ce4-11e9-8145-7ec605fcb0c4.png">

**Comment by izdeby** [comment]
@Atcold, 

> It looks it's not longer the case, as dtype=uint8.

as of right now comparison ops are returning ByteTensor (dtype=uint8). This behavior is about to change once this [PR](https://github.com/pytorch/pytorch/pull/21113) will be landed and BoolTensor will be returned instead.

> So, I guess there's an automatic casting going on now?
ByteTensor is the same thing as dtype=uint8

> But, if I actually specify it I get an error.
You are specifying invalid dtype "None". Please see all available dtypes [here](https://pytorch.org/docs/stable/tensors.html)

**Comment by Atcold** [comment]
Hi @izdeby,

From the documentation: `torch.sum(input, dtype=None) → Tensor`.

Also, it looks like `torch.sum(ByteTensor, dtype=None).dtype == torch.int64`, but the documentation says it should be `== torch.uint8`.

**Comment by izdeby** [comment]
@Atcold, if i understand your concern correctly, in` torch.sum(input, dtype=None) → Tensor` the `dtype=None` part means that its optional and if you wont pass anything, it will be ignored. 

Regarding 

> but the documentation says it should be == ByteTensor
Can you, please, point to a place where it says that? In case, when the return type is not specified, casting will take place and if the desired return type was specified - you will get what you are asking for. 

I agree that it might be a bit confusing, so maybe we should point out the fact the return type might differ from the source more direct. What do you thing, @ezyang?

**Comment by fmassa** [comment]
We have (since 0.4 or 1.0) type promotion for reduction, so the result of summing any integer type (including `uint8`) returns a `int64` by default.

This is the same behavior as in numpy.

If you want to return the same type, you can specify a `dtype` in the function.

**Comment by ifedan** [comment]
The documentation for "sum" says: dtype (torch.dtype, optional) – the desired data type of returned tensor. If specified, the input tensor is casted to dtype before the operation is performed. 
It doesn't say anything about return type. 

Please, reopen this issue if you find that the behaviour doesn't correspond to the doc.

**Comment by Atcold** [comment]
@ifedan, don't you find inconsistent a mathematical operation that perform auto-casting?
Yeah, I guessed it was intended, @fmassa, but I think it should be specified somewhere, no?

If I have `a + b + c`, and all `a`, `b`, `c` have the same type, it would be expected that `a + b + c`, or `sum(a, b, c)`, would retain the same `dtype`.

**Comment by fmassa** [comment]
@Atcold well, it is usually more surprising to users if `torch.sum(torch.ones(256, dtype=torch.uint8))` is equal to 0 and not 256, right?

But if it's not present in the documentation, we should mention the casting behavior somewhere, yes.

**Comment by Atcold** [comment]
Haha, for new users I guess you're right.
For us, oldies, the new behaviour looks magical, though 😝
