### ISSUE TITLE
Fork start method is susceptible to deadlocks

### ISSUE THREAD

**Issue by Louis-Tian** [pytorch/pytorch#2245]
## Versions
```
Ubuntu 16.04
Python 3.6.2 
pytorch 0.1.12_2
```
## Issue description

```python
import torch
import torch.multiprocessing as mp
import torch.functional as f
import threading
import numpy as np
from timeit import timeit

def build(cuda=False):
    nn = torch.nn.Sequential(
        torch.nn.Linear(1024, 1024),
        torch.nn.Linear(1024, 1)
    )

    return nn.cuda() if cuda else nn

def train(nn, X, y, epoch=100):
    X = torch.autograd.Variable(X)
    y = torch.autograd.Variable(y)
    optim = torch.optim.SGD(nn.parameters(), lr=0.1)
    for i in range(epoch):
        yhat = nn(X)
        loss = ((yhat - y) ** 2).mean()
        loss.backward()
        optim.step()

def data(cuda=False):
    X = torch.Tensor(np.random.randn(10, 1024))
    y = torch.Tensor(np.random.randn(10, 1))
    return (X.cuda(), y.cuda()) if cuda else (X, y)

def cpu_run(i=None):
    nn = build(cuda=False)
    d = data(cuda=False)
    train(nn, *d)

def seq_cpu_run():
    for i in range(5):
        cpu_run()

def multiprocess_cpu_run():
    pool = torch.multiprocessing.Pool(processes=1)
    result = pool.map(cpu_run, [() for i in range(1)])
    pool.close()
    pool.join()
    return result

if __name__ == "__main__":
    print(timeit(seq_cpu_run, number=1)) # 1
    print(timeit(multiprocess_cpu_run, number=1))  # 2
``` 

#1 run okay alone.
#2 run okay alone.
#2 then #1 runs okay.
#1 then #2 never terminate.

where
#1 = seq_cpu_run, #2 = multiprocess_cpu_run

**Comment by Louis-Tian** [comment]
`mp.set_start_method('spawn')` seems to resolve the issue.

**Comment by apaszke** [comment]
The default start method (fork) is pretty dangerous in multi-threaded programs. It's a reasonable default for mp, because it's cheap and people usually don't use multiple threads in Python, but we do - both in our autograd code and in our backends that use OpenMP (which doesn't support forking). This would explain this behaviour. I can leave this issue open, but with a very low priority, because it's possible that it's OpenMP that's left in inconsistent state, and there's nothing we can do about that

**Comment by Louis-Tian** [comment]
@apaszke Thanks for the explanation. It's much appreciated. I am definitely not seasoned when comes to parallel computing. So my apology if this is obvious. I read the multiprocessing section of on the doc, where you mentioned about the 'fork' is susceptible to deadlock. However, I was assuming that if there is no sharing (model and data are created inside the child processes) among the processes, we would be fine since there would be no competition among process to access resources.

**Comment by apaszke** [comment]
It's not so much about contention on shared resources, but more on leaving some global library data in an inconsistent state. `fork()` isn't really meant to be used in multi-threaded programs (it's undefined behaviour IIRC)

**Comment by mruberry** [comment]
Closing this issue due to age, and because it seems to be resolved. If this is incorrect, please file a new issue using a more recent version of PyTorch.
