### ISSUE TITLE
Pytorch 1.1 with distributed data parallel

### ISSUE THREAD

**Issue by mileyan** [pytorch/pytorch#22451]
## 🐛 Bug

I used distributed data parallel (DDP) with 8 V100 to train ResNet 50 on ImageNet dataset. But Pytorch 1.1 has lower speed than Pytorch 1.0 .

## To Reproduce

1. download code from here https://github.com/pytorch/examples/blob/master/imagenet/main.py
2. `python imagenet.py  -a resnet50 --dist-url 'tcp://127.0.0.1:32212' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 path-to-imagenet -j 32`

## Expected behavior
When I used 8 V100 GPUs to resnet50 with DDP on a single node, the time of one epoch was shown in the table. 

| Version | Total Time /s | Data Loading Time /s |
| ------------- | ------------- |------------- |
| Pytorch 1.1 |   2012  | 305 |
| Pytorch 1.0  | 606  | 42 |

### Pytorch 1.0
"""
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.0.0
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl
[conda] cuda100                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.0.0           py3.7_cuda10.0.130_cudnn7.4.1_1  [cuda100]  pytorch
[conda] torchvision               0.2.2                      py_3    pytorch
"""
### Pytorch 1.1
"""
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchvision               0.3.0           py37_cu10.0.130_1    pytorch
"""

**Comment by labor00** [comment]
Hi. Have you tried to set the value of the environment variable OMP_NUM_THREADS to one (1).
(If using OpenMPI you can define OMP_NUM_THREADS=1 and use the -x OMP_NUM_THREADS to export this environment variables to all processes when running the mpirun).

**Comment by mrshenli** [comment]
Hi @mileyan, does @labor00's suggestion work for your?

**Comment by mileyan** [comment]
Yes, `export OMP_NUM_THREADS=1` works for me.
