### ISSUE TITLE
torch.stack is slower than torch.cat().view() 

### ISSUE THREAD

**Issue by czxttkl** [pytorch/pytorch#22462]
I just find that using `torch.stack` is much slower than `torch.cat().view()`. Is this a bug or an expected behavior?

```
import time
import torch
data = [torch.rand(22) for _ in range(10240)]
t1 = time.time()
for i in range(300): d = torch.stack(data)  
t2 = time.time()
for i in range(300): d = torch.cat(data).view(-1, 22) 
t3 = time.time()
print("torch.stack time: {}, torch.cat time: {}".format(t2 - t1, t3 - t2))

# result under my Mac laptop:
torch.stack time: 3.844403028488159, torch.cat time: 0.5380599498748779
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @VitalyFedyunin @ngimel @heitorschueroff

**Comment by soumith** [comment]
this is a performance bug. At some point, we optimized `torch.cat` on CPU, but we didn't do the same for `torch.stack`. cc: @VitalyFedyunin

**Comment by colesbury** [comment]
It's just a matter of operator overhead. torch.stack(data) is equivalent to `torch.cat([x.unbind(0) for x in data])`.

The unbind() overhead is ~1us. 1us * 10240 * 300 = ~3 seconds

**Comment by fmassa** [comment]
If this issue is still present due to operator overhead, why not re-implementing `stack` as `cat` + `reshape` instead, as proposed by OP?
```python
def stack(data, dim=0):
    shape = data[0].shape  # need to handle empty list
    shape = shape[:dim] + (len(data),) + shape[dim:]
    x = torch.cat(data, dim=dim)
    x = x.reshape(shape)
    # need to handle case where dim=-1
    # which is not handled here yet
    # but can be done with transposition
    return x
```

On the same benchmark from OP in my laptop, I got
```
In [24]: %timeit d = torch.stack(data)
5.21 ms ± 218 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [25]: %timeit d = stack(data, 0)
1.43 ms ± 24.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
which is a 3.5x improvement.

**Comment by ngimel** [comment]
Tracked in T98738497

**Comment by ngimel** [comment]
Fixed on master
