### ISSUE TITLE
CUDA not enabled on GeForce GTX 970M

### ISSUE THREAD

**Issue by GlebSBrykin** [pytorch/pytorch#22486]
OS: Windows 7 Ultimate x64
GPU: NVIDIA GeForce GTX 970M
I installed PyTorch 0.4.1 with CUDA support, but when I run a simple program, the Python freezes, and then opens a Windows error window with a message about the inability to extract the GPU, since it is not a removable device. Immediately after closing this window, the program comes to life and displays False. How can I fix the problem?
Code:
```
import torch
print(torch.cuda.is_available())
```

**Comment by GlebBrykin** [comment]
All drivers, including CUDA at me are installed.

**Comment by Jonas1312** [comment]
Hi,
please specify nvidia drivers, cuda and python versions. You should probably update pytorch to torch-nightly, many fixes for windows have been submitted since 1.1.0

**Comment by GlebBrykin** [comment]
I have updated PyTorch to the latest version as You recommended, however I got a known DLL not found error when importing torch. Version CUDA - 9.0

**Comment by peterjc123** [comment]
Please try https://github.com/lucasg/Dependencies and open `[PYTHON ROOT]\LIB\SITE-PACKAGES\TORCH\_C.PYD`.

**Comment by GlebBrykin** [comment]
What am I supposed to do?

**Comment by Jonas1312** [comment]
> 
> 
> I have updated PyTorch to the latest version as You recommended, however I got a known DLL not found error when importing torch. Version CUDA - 9.0

By "last version" do you mean 1.1.0 or nightly?
Please try 
```
pip uninstall torch
pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu90/torch_nightly.html
```

**Comment by GlebBrykin** [comment]
The problem persists. ImportError: DLL load failed.

**Comment by cristianPanaite** [comment]
Hello @GlebSBrykin,

One of my teammate tried to reproduce this error using a similar GPU and it works fine on the latest versions.

Environment:
GPU: GTX 970
OS: Windows 10
PyTorch: 1.12.1
CUDA: 11.3
GPU drivers version: 516.94

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.
