### ISSUE TITLE
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect

### ISSUE THREAD

**Issue by t-m-k** [pytorch/pytorch#22485]
Question:
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  **if nms_pre > 0 and scores.shape[0] > nms_pre:**

here nms_pre is a python value and nms_pre = 1000;
scores is a Tensor variable with different shape in a loop. 
scores.shape[0] is a python value when it is in pytorch but a Tensor  in the trace process.
From the question, we can know scores.shape[0] will be a constant in the  c++ trace model. 
But scores is a variable with different shape every time in a loop, if it is a constant in the  c++,I will get a out of range error.
How to solve this problem.
Thank you very much.

**Comment by izdeby** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.

**Comment by chouxianyu** [comment]
i met the same problem too.
