### ISSUE TITLE
Why am I missing the libcaffe2.so and libcaffe2_gpu.so library files ?

### ISSUE THREAD

**Issue by haiyang-tju** [pytorch/pytorch#22523]
I downloaded libtorch from [here](https://pytorch.org/get-started/locally/), but there will be a C++ ABI problem. So I recompile the lib from sources by myself. My system configuration is CUDA10.0 and cudnn7.3.1, and I run the command `mkdir build && cd build && python3 ../tools/build_libtorch.py` and get the libs:

build/lib/.
├── libbenchmark.a
├── libbenchmark_main.a
├── libc10_cuda.so
├── libc10.so
├── libcaffe2_detectron_ops_gpu.so
├── libcaffe2_module_test_dynamic.so
├── libcaffe2_observers.so
├── libcaffe2_protos.a
├── libclog.a
├── libcpuinfo.a
├── libcpuinfo_internals.a
├── libfoxi_dummy.so
├── libfoxi_loader.a
├── libfoxi.so
├── libgmock.a
├── libgmock_main.a
├── libgtest.a
├── libgtest_main.a
├── libnnpack.a
├── libnnpack_reference_layers.a
├── libonnx.a
├── libonnxifi_dummy.so
├── libonnxifi_loader.a
├── libonnxifi.so
├── libonnx_proto.a
├── libprotobuf.a
├── libprotobuf-lite.a
├── libprotoc.a
├── libpthreadpool.a
├── libqnnpack.a
├── libshm.so
├── libthnvrtc.so
├── libtorch_python.so
└── libtorch.so

There is the libtorch.so file, but no libcaffe2.so and libcaffe2_gpu.so library files. WHY?

Has the latest version of the source code compilation structure changed significantly?

I found the official libtorch files also have this problem:

Stable-cu90, Stable-cu100 and Nightly-cu100 version libtorch have libcaffe2.so and libcaffe2_gpu.so file, but Nightly-cu90 version is not. 

Why is it different? And how can I compile and get these files?

THS

**Comment by peterjc123** [comment]
AFAIK, caffe2 and torch got merged recently and the final library was renamed to `libtorch.so`. So Nightly-cu90 is appearing normal. I guess the build for Nightly-cu100 is failing. cc @pjh5

**Comment by haiyang-tju** [comment]
Is the old version of the caffe2 C++ interface still usable? Is it only necessary to change the link library to libtorch.so at compile time? @peterjc123

**Comment by peterjc123** [comment]
For the first question, it depends on the code you are trying to build against. The answer to the second one is yes.

**Comment by haiyang-tju** [comment]
@peterjc123 Thanks for your kind reply! And I will give it a try.
