### ISSUE TITLE
Allocated GPU memory doesn't increase proportionally to the number of models

### ISSUE THREAD

**Issue by luyiming** [pytorch/pytorch#22524]
I find that loading more models in one python process consume far less GPU memory than loading each model in different python process.

Suppose the following code is executed in two python processes:

```python
import torch
import time
import torchvision.models as models

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = models.densenet161(pretrained=False).to(device)

print('loaded')

time.sleep(1000)
```

The nvidia-smi output would be:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     12546      C   python                                       773MiB |
|    0     13218      C   python                                       773MiB |
+-----------------------------------------------------------------------------+
```

It is reasonable because we have loaded two models. But if I load two models in one process, i.e., running the following code:
```python
import torch
import time
import torchvision.models as models

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = models.densenet161(pretrained=False).to(device)
model2 = models.densenet161(pretrained=False).to(device)

print('loaded')

time.sleep(1000)
```

The nvidia-smi output shows that it consumes far less memory than the previous situation.
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     13448      C   python                                       885MiB |
+-----------------------------------------------------------------------------+
```

Is this some kind of cache reuse technique used by pytorch? 
P.S. I have observed this phenomenon in tensorflow models too.

The problem is, I have a bunch of pytorch models to deploy and each of them requires a lot of GPU memory. I don't want to put all those models in one server process. I want to manage each of the model using docker containers. But if I deploy the model in different docker containers, those models would consume far more GPU memory than I can offer. What is the solution of my situation?

**Comment by soumith** [comment]
Yes, we have caching. See https://pytorch.org/docs/stable/cuda.html#torch.cuda.empty_cache

**Comment by jesen8** [comment]
hi, @soumith ,i have the same question, But I hope that the capacity of the graphics card can be doubled when i load two model in same python process,how i solve it? thanks.
