### ISSUE TITLE
torch.distributions.Normal cuda sampling broken

### ISSUE THREAD

**Issue by pfrendl** [pytorch/pytorch#22529]
## 🐛 Bug

Normal distribution returns wrong samples if provided cuda tensors, and all the samples take the same value.

## To Reproduce

```
>>> mean = torch.tensor([0.0, 2.0], device='cuda')
>>> std = torch.tensor([1.0, 2.0], device='cuda')
>>> dist = torch.distributions.Normal(mean, std)
>>> dist.sample((10,))
tensor([[0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.]], device='cuda:0')
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.2.0.dev20190703 (nightly)
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip3
 - Python version: 3.5.2
 - CUDA/cuDNN version: 10.0/7 
 - GPU models and configuration: 2 x GTX 1080 Ti

**Comment by vishwakftw** [comment]
Thank you for the bug report. The fix is available in #22533.
