### ISSUE TITLE
Enable system NCCL detection when ldconfig is not in the path

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#2252]
Hello,

on Debian (and possibly Ubuntu and other systems), `ldconfig` is in `/sbin` and not in non-root users' search paths.
Thus this line:
`if WITH_NCCL and subprocess.call('ldconfig -p | grep libnccl >/dev/null', shell=True) == 0:`
at https://github.com/pytorch/pytorch/blob/master/setup.py#L285
does not do what it should when compiling not as root.
Either writing `/sbin/ldconfig` or adding a second check with the directory would help building pytorch on these systems.

Would such a change be acceptable?

Thank you & best regards

Thomas

**Comment by CDLuminate** [comment]
Or fix this by exporting `PATH=$PATH:/sbin`?

**Comment by soumith** [comment]
such a chance would be absolutely acceptable.

**Comment by t-vi** [comment]
fixed in PR #2276
