### ISSUE TITLE
Is it possible to send a model as argument to a CUDA kernel?

### ISSUE THREAD

**Issue by ivandrodri** [pytorch/pytorch#22530]
Hello,

I am new with pytorch and I am trying to implement pytorch c++ with a cuda/c++ project.

My question is the following, is it possible to do something like this:

//// Neural Net. definition ////

struct Net : torch::nn::Module
{
     Net(int inputSize, int hiddenSize, int numClasses):
     fc1(register_module(“fc1”, torch::nn::Linear(inputSize, hiddenSize))),
     fc2(register_module(“fc2”, torch::nn::Linear(hiddenSize, numClasses))) {};

     torch::nn::Linear fc1;
     torch::nn::Linear fc2;

    torch::Tensor forward(torch::Tensor input) 
   {
       auto out = fc1(input);
       out = torch::relu(out);
       out = fc2(out);
 
       return out;    

     }
};

//// Use Neural Net in CUDA kernel

__global__ void testKernel (Net model)
{
… use model here …
}

Or create the model on the device directly, i.e.

__global__ void testKernel()
{
   Net model(....);
}

Thanks for any help!!

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
