### ISSUE TITLE
DataLoader runs too many threads

### ISSUE THREAD

**Issue by vlasenkov** [pytorch/pytorch#22535]
## 🐛 Bug

DataLoader launches 22 threads when num_workers=0

## To Reproduce

Run this

```python
import numpy as np
import torch
import torch.utils.data
import os
import re


PID = os.getpid()
STAT = f'/proc/{PID}/status'


def PRINT():
    with open(STAT, 'r') as f:
        print(re.search(r'Threads:[ \t]*\d+', f.read()).group(0))


class Dataset:

    def __len__(self):
        return 1000

    def __getitem__(self, index):
        x = np.random.randn(1, 512, 512)
        return torch.from_numpy(x)


dataset = Dataset()
loader = iter(torch.utils.data.DataLoader(
    dataset, batch_size=16, shuffle=True, num_workers=0, pin_memory=True, drop_last=True))


PRINT()

next(loader)

PRINT()
```

After the `next(loader)` there will be 22 threads.

## Expected behavior

I would expect only 1 thread, however this script initially runs in two threads by some reason. So, having the same 2 threads in the end would be ok.

## Environment

```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: Tesla V100-DGXS-32GB
GPU 1: Tesla V100-DGXS-32GB
GPU 2: Tesla V100-DGXS-32GB
GPU 3: Tesla V100-DGXS-32GB

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.15.3
[pip] torch==1.1.0
[pip] torchtext==0.3.0
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl  
[conda] magma-cuda100             2.1.0                         5    local
[conda] mkl                       2019.0                      118  
[conda] mkl-include               2019.0                      118  
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0  
[conda] mkl_random                1.0.1            py36h4414c95_1  
[conda] pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torch                     1.0.0a0                  pypi_0    pypi
[conda] torchtext                 0.3.0                    pypi_0    pypi
[conda] torchvision               0.2.1                    pypi_0    pypi
```

**Comment by mrshenli** [comment]
cc @cpuhrsch

**Comment by SsnL** [comment]
There are some queues that launches putter threads, but I suppose that most threads is either from the `permutation` call in `RandomSampler` and/or the `from_numpy` call. Both are just using the pytorch thread pool. So the threads are not specific to data loader. What is your expected behavior?

**Comment by vlasenkov** [comment]
When I remove `from_numpy` call, the situation does not change. I expect that the number of threads in much less than 22. That huge threads number floods the shared machine, and I suppose it reduces performance of the data transformations themselves, because they are done on CPU. Anyway none of the steps performed by `DataLoader` really need to be done in parallel.

**Comment by SsnL** [comment]
As I said, the threads are not specifically for data loader uses. The sampler could call arrange and/or randperm, both of which could be parallelized. That is, these threads are used by ops internally where they think such parallelism is helpful. I just wan to make it clear that this behavior is not related with the data loader. These threads will be reused by other ops that want multi threading, so it is not like the data loader adds these many threads. 

If you want to limit the number of threads used by program, use set_num_threads. Furthermore, if you are using workers, each worker automatically reduces that to 1. 

And I don’t know why you think CPU ops shouldn’t be multithreaded. Having multiple CPU threadS is only useful for CPU ops.

**Comment by vlasenkov** [comment]
I see, thanks. But there are two points.

Firstly, when I use workers, the number of threads is still huge, so that each worker does not automatically reduce that to 1.

Secondly, I observe that all 40 CPUs are 100% loaded. They are loaded with something that is going on within the sampler. Therefore, the actual data reading and transformation is slowed down, because these threads occupy the computational capacity that could be fully employed by the actual data transforms otherwise. At the same time, I suppose that what sampler is doing is a quite light computation, especially compared to what is done in workers (where I read data from disk, resize it with Numpy, etc).

Finally, my point is that these threads called by the sampler slow down the worker threads that do the main job.

**Comment by SsnL** [comment]
First of all, I want to apologize for an inaccuracy in my previous reply. The threads (apart from the few `Queue` putter threads) could come from either the sampler or the possible copy in `pin_memory`. 

Both the sampler and the copy, if they actually occur, are necessary. So there is no such thing as slowing data processing down. Sampler initialization is one time at construction time, and the copy is after fetching each batch. They are not blocking data processing because they are part of the process of fetching data.

**Comment by vlasenkov** [comment]
Thanks. So, if this is not a performance bug, I'm closing the issue.

**Comment by SsnL** [comment]
Actually this could also be due to #25010 !

**Comment by 0400H** [comment]
A proven solution:

class _DataLoaderIter(object):
    def __next__(self):
        if self.num_workers == 0:
            num_threads = torch.get_num_threads()
            torch.set_num_threads(4)  # set threads num you want (1, 2, 3 ...)
            . . . . . .
            torch.set_num_threads(num_threads)
            return batch
