### ISSUE TITLE
RuntimeError: expected backend CPU and dtype Double but got backend CPU and dtype Float - in torch normalize function

### ISSUE THREAD

**Issue by ameyabp** [pytorch/pytorch#22539]
## 🐛 Bug
Pytorch normalize function expects mean and std arguments as double data type but itself casts them in float32 data type

## To Reproduce

1. Just use the torch.transforms Normalize function with some mean and stdev values

**Call stack:**
```
  File "/home/ameya/Documents/image-exploration-prediction/iep/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 164, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/ameya/Documents/image-exploration-prediction/iep/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: expected backend CPU and dtype Double but got backend CPU and dtype Float
```

Here is the Normalize function implementation in functional.py:
```python
    mean = torch.as_tensor(mean, dtype=torch.float32, device=tensor.device)
    std = torch.as_tensor(std, dtype=torch.float32, device=tensor.device)
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
    return tensor
```

## Expected behavior
It should not raise such an error if it is itself converting arguments to other data types.
I modified the functional.py file to have the following lines instead
    mean = torch.as_tensor(mean, dtype=**torch.double**, device=tensor.device)
    std = torch.as_tensor(std, dtype=**torch.double**, device=tensor.device)

and it started working as expected

## Environment

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 410.104
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] Could not collect

#define CUDNN_MAJOR 7
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 1

## Additional context
NA

**Comment by mrshenli** [comment]
cc @fmassa

**Comment by SsnL** [comment]
it should get the dtype from `tensor`

**Comment by vishwakftw** [comment]
I think this issue should be opened in [pytorch/vision](https://github.com/pytorch/vision).

**Comment by fmassa** [comment]
This has been fixed in the master version of torchvision
