### ISSUE TITLE
How to programmatically check PyTorch version

### ISSUE THREAD

**Issue by srossi93** [pytorch/pytorch#22549]
## 📚 Documentation

[Minor minor detail]
In the reproducibility section of the docs or in the FAQ, I would add a simple subsection/snippet of code to show how to programmatically check the running version of PyTorch. 
This can also encourage users to take into account heterogeneity of PyTorch versions in their code.

By the way, a simple regex on `torch.__version__` is enough (this assuming version numbering will not change).
```python
import torch
import re
if int(re.search(r'([\d.]+)', torch.__version__).group(1).replace('.', '')) < 100:
    raise ImportError('Your PyTorch version is not supported. '
                      'Please download and install PyTorch 1.x')
```

**Comment by SsnL** [comment]
Use `packaging.version.parse` https://stackoverflow.com/a/11887885
