### ISSUE TITLE
Is there any functions which can covert caffe model to pytorch model？

### ISSUE THREAD

**Issue by yichuan9527** [pytorch/pytorch#2256]
There are many great models these are pre-trianed in caffe. Do you have to develop some converters that can convert  caffe models to  pytorch models?

**Comment by CDLuminate** [comment]
LuaTorch has a module `loadcaffe`, maybe you can try to convert the caffemodel into luatorch format, then try to load that model in pytorch somehow.

**Comment by soumith** [comment]
the short answer is no. The best we have is what @CDLuminate suggests. What models are you looking for?
