### ISSUE TITLE
raise RuntimeError("ONNX symbolic expected a constant value in the trace")

### ISSUE THREAD

**Issue by InstantWindy** [pytorch/pytorch#22568]
Version :pytorch version 1.0.0
Error:raise RuntimeError("ONNX symbolic expected a constant value in the trace")

**Comment by garymm** [comment]
This is not actionable without reproduction instructions. @InstantWindy please provide full reproduction instructions, ideally something we can run in Colab.

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
