### ISSUE TITLE
pytorch on python 3.7.3 

### ISSUE THREAD

**Issue by catafest** [pytorch/pytorch#22575]
## 🚀 Feature

pytorch with python 3.7.3 
(install using pip) 
## Motivation
I change to python 3.7.3 and I think this is easy to implement from 3.6 to 3.7.3 by the pytorch team.

I want to use the https://github.com/pytorch/audio on python 3.7.3

**Comment by xuhdev** [comment]
PyTorch has been supporting Python 3.7.3 :)

See https://pytorch.org/get-started/locally/ , select pip and Python 3.7

**Comment by zou3519** [comment]
Closing due to @xuhdev's comment. Please let us know if we misunderstood your question.
