### ISSUE TITLE
Segmentation Fault for "import torch" on Ubuntu 16.0.4 + prime-select intel

### ISSUE THREAD

**Issue by JubilantJerry** [pytorch/pytorch#22571]
## Bug
The bug is similar to #4101, but it is not fixed on 0.4.1 and persists on the latest public release of PyTorch. When I switch my graphics settings to use my integrated GPU with prime-select, then I cannot import torch at all - Python will instantly segfault. I run Ubuntu 16.0.4 and Python 3.5.

## Workaround and Possible Cause

The bug is resolved if I remove these files:
/usr/lib/x86_64-linux-gnu/libcuda.so*

However, doing so makes PyTorch unable to use my discrete GPU when I switch back with "prime-select nvidia".

Could you make PyTorch fail gracefully in this situation? Enabling the discrete GPU eats battery power very quickly, and I would like to run CPU based experiments with the GPU disabled, which the segmentation fault prevents me from doing.

## Environment

I'll run the environment script and update the ticket soon, when I get access to the problematic computer. From what I remember, I use the nvidia-396 driver, CUDA 9.1, and Ubuntu 16.0.4.

**Comment by ezyang** [comment]
What is the specific hardware model of computer/gpu you're using?

**Comment by ezyang** [comment]
@fmassa suggests running PyTorch with `CUDA_VISIBLE_DEVICES=` (that's empty), as a way of "disabling" GPUs.

**Comment by JubilantJerry** [comment]
Something must have been misconfigured on the machine. A re-installation appeared to have fixed the problem.
