### ISSUE TITLE
pytorch creating 1st tensor slow

### ISSUE THREAD

**Issue by zeroexcuses** [pytorch/pytorch#22583]
## 🐛 Bug

It takes 4 seconds to initialize CUDA + create first Tensor.

## To Reproduce

See script:

```
cat test.py ; echo "=====" ; time python3 test.py
import torch;
import sys;

print ("python version: ", sys.version)
print ("torvh version: ", torch.__version__)

print(torch.zeros(5, 3).cuda());

=====
python version:  3.7.2 (default, Mar 21 2019, 10:09:12) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
torvh version:  1.1.0
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

real    0m4.980s
user    0m4.238s
sys     0m2.636s

```

## Expected behavior

I expect this to take < 1s.

## Environment

Fedora 29.

Python 3.7

Pytorch 1.1.0

Cuda 10

Installed via Pip + https://pytorch.org/get-started/locally/

```
 nvidia-smi
Mon Jul  8 01:57:57 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 00000000:01:00.0 Off |                  N/A |
| 26%   37C    P8    12W / 250W |      1MiB /  6083MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0  On |                  N/A |
| 17%   56C    P0    61W / 250W |    764MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:83:00.0 Off |                  N/A |
|  0%   40C    P8    10W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    1      1969      G   /usr/libexec/Xorg                            537MiB |
|    1      3391      G   /opt/google/chrome/chrome --typ              220MiB |
|    1     31722      G   ...ools/idea-IC-191.6183.87/jre64/bin/java     3MiB |
+-----------------------------------------------------------------------------+
```

**Comment by colesbury** [comment]
Unfortunately, there's not much we can do about this. CUDA initialization scales with the number of kernels and PyTorch provides a lot of CUDA kernels.

**Comment by zeroexcuses** [comment]
I want to make sure I am understanding this correctly (as in my other CUDA experiences, I'm generally using < 10 kernels). What you're saying is:

1. PyTorch CUDA init time is lower bounded by time it takes to load all PyTorch CUDA kernels (perfectly reasonable).

2. PyTorch CUDA has so many kernels, the mere act of loading all the kernels will take seconds of time (instead of milliseconds) <-- I find this statement surprising, but I have no idea how many kernels PyTorch is loading, nor do I know how much work CUDA has to do per loaded kernel.

**Comment by colesbury** [comment]
Yes. PyTorch has 100s of high level operations and O(10,000) CUDA kernels. (Plus all the kernels provided by cuBLAS, cuDNN, and CUDA). An operation like torch.add has something like 8 * 3 * 2 = 48 kernels. (8 data types, 3 combinations of tensor/scalar, 2 specializations for strides). Older kernels may have even more specializations. The large number of kernels per op is because we care about completeness (lots of data types, support for non-contiguous tensors) and speed (optimizations for the common case).

One could imagine splitting the library into "common" kernels and "uncommon" kernels and only loading the "uncommon" kernels when necessary. However, that requires a lot of engineering work and it's likely that most applications would use at least one "uncommon" kernel, which would require loading the whole library.

We'd love to make initialization faster, but I don't think there's much we can currently do about it.

**Comment by zeroexcuses** [comment]
Thanks for the detailed explanation. Closing bug report.

**Comment by interestingLSY** [comment]
You can try to enable the persistence mode. `sudo nvidia-smi -pm ENABLED`
