### ISSUE TITLE
Extending torch.utils.trainer with Visdom

### ISSUE THREAD

**Issue by alexsax** [pytorch/pytorch#2258]
I'm planning on writing a lightweight extension to PyTorch. The goal is to speed up my research in 2 ways
1) Testing many models should be easy, and it should be easy to keep track of the parameters used to train the models
2) I would like to reuse my nice logging code across projects and models

I see that there is a feature, torch.utils.trainer, that implements some of these ideas, and I'd like to extend it to be more fully-featured. For visualizations and logging, similar to Tensorboard, I'd like to integrate [Visdom](https://github.com/facebookresearch/visdom). For me, the superior logging of TensorBoard is the biggest reason that I would still use TF for research. 

I'm imagining something like [this](https://github.com/jingweiz/pytorch-rl) which is a great start. The final version would be more general, and work with the existing torch.utils.trainer.Trainer. 

I'd also like to add some code to the trainer that supports saving out checkpoints, and nice-to-have features that will make the trainer more friendly.

Is there interest in integrating this into the main PyTorch repo? If there is, then I will write a nice version and submit a pull request :)

**Comment by alexsax** [comment]
I'm working on it [here](https://github.com/alexsax/pytorch-nice/tree/dev) if you'd like to take a peek.

**Comment by jekbradbury** [comment]
There are a couple TensorBoard plugins for PyTorch, with this one the furthest along: https://github.com/lanpa/tensorboard-pytorch

**Comment by alexsax** [comment]
I've actually used that one! It's a great library but does something different than what I'm proposing.  

I'm proposing a wrapper which encapsulates the typical training procedure so that I don't have to rewrite the 'glue' code over and over again. Similar to the `train` function in [tf-slim](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim). PyTorch already has a skeletal implementation of a training loop in `torch.utils.trainer`. It's not sufficiently fully-featured or flexible for anything except the most basic use cases, but I'd like to extend it. I'm proposing to extend this into something very generic which still able to provide some of the more common requirements (e.g. checkpointing, saving the best model) for off-the-shelf use. 
So if you wanted to run something totally weird, every 3 epochs, you should be able to do it with:
```
plug = PluginFactory((3, 'epoch'), fn=myWeirdFunction)
trainer.register(plug)
```

And checkpointing with a complex save function could be a one-liner!
```
trainer.register(Saver((1, 'epoch'), filename='checkpoint.pth.tar', save_function=myCrazySaveFunction)
```


Then there's a separate part that concerns visual logging, which is the niche that Tensorboard fills. The visualization could be powered with TensorBoard via a `TensorboardLogger` class which would log statistics out to TensorBoard periodically. Tf-slim has a great tool, summaries, which do exactly that (in TF). However, TensoBoard has a limited range of plots and isn't readily extensible. That makes it hard to interact with it using python. 

Visdom, which is also from Facebook, allows more customization and chart types. In particular, it allows images and videos, which means that users could view CNN filters or sample episodes from an A3C model. 

Sorry that I didn't communicate that clearly before! In short, since PyTorch already has the trainer, it might as well be fully featured! As for Visdom v. Tensorboard, someone else might want to incorporate the TensorBoard plugins at a future time, but I think that Visdom fits in better with the "Extensions without Pain" and "Python First" parts of PyTorch.

**Comment by Alexandersax** [comment]
Thanks for these!  I hadn't seen TNT and may have missed a critical citation :) I'll take a look at them and then follow up here.

**Comment by nasimrahaman** [comment]
We've been working on [something along those lines](https://github.com/nasimrahaman/inferno). It's a training bench with support for callbacks (__Tensorboard included__!). There are a few rough edges, but we're getting there.

**Comment by alexsax** [comment]
Awesome, TNT looks like the type of training loop that I am looking for. It's got nice callbacks that don't abstract away too much. @nasimrahaman, Inferno also looks promising. Do you plan to support RL use cases, as well?

Since there are already libraries which encapsulate the training loop, perhaps the most flexible way to integrate visual logging is to write a separate library of plugins that could be used with all of the above. 
e.g.
```
# Training loop variants gather the data from the state dict
vl = VisdomLogger("heatmap", ["conv4.activations"], register=state) # TNT version
vl = VisdomLogger("heatmap", ["conv4.activations"], register=state, (2, "epoch")) #Existing PyTorch trainer/Inferno version
trainer.train(**kwargs)

# Version for no training loop still eliminates the need to carry around parameters all the time
vl = VisdomLogger("heatmap") 
for i in count():
    # do stuff
    vl.log(data)
```

**Comment by nasimrahaman** [comment]
@alexsax Thanks. Support for some common RL algorithms (e.g. PG, Q-Learning, A3C) is definitely on the todo list.

**Comment by soumith** [comment]
I am happy to give commit rights to tnt to @nasimrahaman and @alexsax so that you can shape that package further. the torch.utils.trainer in the core repo, i think we'll deprecate that.
