### ISSUE TITLE
[jit] zeros_like/one_like don't handle their kwargs correctly.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#22608]
```python
import torch

@torch.jit.script
def foo(x):
    return torch.ones_like(torch.randn(x), dtype=torch.double)

foo()
```
This currently results in 
```python
RuntimeError: 
Arguments for call are not valid.
The following operator variants are available:
  
  aten::ones_like(Tensor self) -> Tensor:
  Keyword argument dtype unknown.
  
  aten::ones_like(Tensor self, *, int dtype, int layout, Device device, bool pin_memory=<default>) -> Tensor:
  Argument layout not provided.

The original call is:
at /Users/chilli/Downloads/t.py:7:12
@torch.jit.script
def foo(x):
    return torch.ones_like(torch.randn(x), dtype=torch.double)
           ~~~~~~~~~~ <--- HERE
```

It appears that this may be a regression since 1.0.1, as this issue https://github.com/pytorch/pytorch/issues/22587  provides code that contains code like this.

cc @suo

**Comment by eellison** [comment]
@ailzhang mind taking a look?

**Comment by zou3519** [comment]
@Chillee there's no `x` in your snippet above, was that intentional?

**Comment by Chillee** [comment]
@zou3519 🤦‍♂ I ran into this bug earlier and tried to reproduce it, clearly didn't think too much about the error message I was pasting.

**Comment by ailzhang** [comment]
Remove my assignment for now as I won't have bw for this in a week. 
I can check back to this in 2 weeks if this is not taken care of by then.

**Comment by suo** [comment]
Closing this out as https://github.com/pytorch/pytorch/issues/30763 is a more general tracking of this issue.
