### ISSUE TITLE
Combination of torch.cat with almost zero tensor and torchvision.transforms leeds to zero tensor

### ISSUE THREAD

**Issue by JohnStuartMillx** [pytorch/pytorch#22611]
## 🐛 Bug

If I create a Tensor with a fourth layer where (almost) all entries are zero, and I use transforms. transforms.RandomResizedCrop(), transforms.ToTensor() the hole tensor becomes a zero tensor.

## To Reproduce

Code to reproduce the behavior:

```python
import torch
from torchvision import transforms

height = 3
width = 4
resize = 2
tensor3 = torch.rand(3,height,width)
tensor1 = torch.zeros(1,height,width)
#tensor1 = torch.rand(1,height,width)

imageToTensor = transforms.ToTensor()
tensorToImage = transforms.ToPILImage()

train_transform = transforms.Compose([
    transforms.RandomResizedCrop(resize, scale=(1.0, 1.0)),
    transforms.ToTensor(),
])

tensor4 = torch.cat((tensor3,tensor1),0)

image4 = tensorToImage(tensor4)
transformed_image4 = train_transform(image4)

print(tensor4)
print(transformed_image4)
```
Output:
```
tensor([[[0.6774, 0.5293, 0.4420, 0.2463],
         [0.1391, 0.7481, 0.3436, 0.9391]],

        [[0.0652, 0.2061, 0.2931, 0.6126],
         [0.2618, 0.3506, 0.5095, 0.7351]],

        [[0.8555, 0.6320, 0.9461, 0.0928],
         [0.2094, 0.3944, 0.0528, 0.7900]],

        [[0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

```

## Expected behavior

I would the first three layer change like there is no 4th layer. I.e. the first three layer are croped and resized and not zero since all the single entries are > 0. 

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 410.79
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] numpydoc==0.9.1
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2.post3
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.3                      1
[conda] mkl-service               1.1.2            py37h90e4bf4_5
[conda] mkl_fft                   1.0.6            py37h7dd41cf_0
[conda] mkl_random                1.0.1            py37h4414c95_1
[conda] pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torchvision               0.2.2.post3              pypi_0    pypi

## Additional context

If I choose `tensor1 = torch.rand(1,height,width)` I do not have this problem. With some non zero entries but with most entries are zero I have. With `scale=(0.5, 1.0)` I don't have the problem either.

`tensor1 = torch.rand(1,height,width)/1000` does also lead to an odd change in the first three layers.

I tried transforms.Resize(resize) as a substiturte. 

With the following entries there is no resizing:
``` 
height= 2
width = 4
resize = 2 
```

With the following entries I do have the same issue:

``` 
height= 3
width = 4
resize = 2 
```

**Comment by fmassa** [comment]
This issue should be opened in torchvision instead.

But long story short, we do not support multi-dimensional images in torchvision, like the one you are creating. We are currently limited to the types of image that PIL support.
