### ISSUE TITLE
[Bug] torch.from_numpy fails to convert np.int32 when np.dtype.num=7

### ISSUE THREAD

**Issue by ihexx** [pytorch/pytorch#22615]
## 🐛 Bug

I ran into the following error when trying to convert an integer numpy ndarray to a torch tensor:
`>>> torch.from_numpy(b)`

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
> TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.
> 

## To Reproduce
Here's some example code that triggers it

```python
import numpy as np
import torch
a = np.array([1,2,3])
torch.from_numpy(a) # This works fine
```

> tensor([1, 2, 3], dtype=torch.int32)

```python
b = a % 2
b
```

> array([1, 0, 1], dtype=int32)
```python
torch.from_numpy(b)
```

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
> TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.

---

I was looking through the members/properties of the dtype in a debugger, and I notice
`np.dtype.num` changed from 7 to 5 after the modulus:

```python
b.dtype , b.dtype.num
```
> (dtype('int32'), 5)
```python
a.dtype, a.dtype.num
```
> (dtype('int32'), 7)

---

I can work around it by using `b.astype(int)` and this works fine, but it's just confusing that the error message in torch complains it's not an int32 when it is.

## Environment
windows10
Anaconda python 3.6 env 
torch                1.1.0 (installed via conda)
numpy                1.16.2+mkl

**Comment by ezyang** [comment]
Yeah, we should fix this. The error message is in torch/csrc/utils/tensor_numpy.cpp, if someone could put up a PR and put me as reviewer, I'd be quite happy to land it.
