### ISSUE TITLE
Loading nvidia_waveglow model from torch hub on cpu fails without CUDA

### ISSUE THREAD

**Issue by padmalcom** [pytorch/pytorch#22613]
## 🐛 Bug

I try to load the nvidia_waveglow model as described here:
https://pytorch.org/hub/nvidia_deeplearningexamples_waveglow/

My VM has no CUDA support so I use the gpu as device.

My code is:
```
import torch
waveglow = torch.hub.load('nvidia/DeepLearningExamples', 'nvidia_waveglow', map_location='cpu')
```

The model downloads successfully but at the end it fails with the following error:

> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

Seems like map_location is not really taken into account.

## Environment

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl_fft                   1.0.12           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch-cpu               1.1.0               py3.6_cpu_0    pytorch
[conda] torchvision-cpu           0.3.0             py36_cuNone_1    pytorch

**Comment by soumith** [comment]
nvidia's waveglow models explicitly don't work on cpu. it was their choice of implementation
