### ISSUE TITLE
Make torch.lu_solve differentiable with respect to the LU-factorized matrix

### ISSUE THREAD

**Issue by arvidfm** [pytorch/pytorch#22620]
## 🚀 Feature
Currently trying to call `torch.lu_solve` with a matrix that requires a gradient leads to the following error:

```
>>> x = torch.randn(10)
>>> pivot = (torch.arange(10) + 1).int()
>>> w = torch.randn(10, 10, requires_grad=True)
>>> torch.lu_solve(x, w, pivot)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: the derivative for 'LU_data' is not implemented
```

It would be good if `torch.lu_solve` could be differentiated with respect to the LU-factorized matrix.

## Motivation

My model involves computing the inverse of a series of parametric transforms, in part involving linear transforms. Simply using `torch.inverse` proved to be too unstable with 16-bit precision even with small matrices, so I hoped `torch.lu_solve` would help here by directly parameterizing the linear transform as an LU-factorized matrix, but it turns out it doesn't support differentiating with respect to the matrix. Thus it seems my model can't be implemented in a stable way at all using PyTorch.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @vincentqb @vishwakftw @jianyuh @mruberry @heitorschueroff

**Comment by vishwakftw** [comment]
You can try using torch.solve as a drop in replacement. It internally uses the partially pivoted LU decomposition.

**Comment by ezyang** [comment]
We'll accept a PR that implements this, but @zou3519's off the cuff thought is that, actually implementing this might be hard.

**Comment by JesseLivezey** [comment]
A related +1 on this issue. I have a use case where I have a matrix that I'm using both in a `solve` and then a `logdet`. I was thinking that I could calculate the logdet by hand from the LU decomposition and not have to compute an extra logdet (which does an LU decomposition internally). This works fine in the forward pass, but the derivative w.r.t. the LU part of solve is not defined.

**Comment by nikitaved** [comment]
Off the top of my head I can see how to make `LU` analytically differentiable, but only if the input matrix is full-rank. Given that PyTorch has many algorithms with stable backward only with the full-rank input (say, Cholesky (supports wide matrices, but only with the first columns linearly independent), QR), maybe it could be a good start at least.
@JesseLivezey , given that you work with logdets, I presume, your inputs are mostly full-rank, right?

**Comment by JesseLivezey** [comment]
@nikitaved That's correct, for my use, the inputs would always be full-rank.

**Comment by nikitaved** [comment]
When the input is full-rank, the gradient wrt LU could be implemented like this:
```python
import torch                                                                                                                              [8/1903]
from torch.autograd import gradcheck, gradgradcheck                                                                                               
torch.random.manual_seed(123)                                                                                                                     
                                                                                                                                                  
class LU(torch.autograd.Function):                                                                                                                
    @staticmethod                                                                                                                                 
    def forward(ctx, A):                                                                                                                          
        lu, pivots = A.lu()                                                                                                                       
        p, l, u = torch.lu_unpack(lu, pivots)                                                                                                     
        ctx.save_for_backward(l, u, p)
        ctx.mark_non_differentiable(p)
        return l, u, p

    @staticmethod
    def backward(ctx, L_grad, U_grad, P_grad):
        L, U, P = ctx.saved_tensors

        Ltinv = L.inverse().transpose(-1, -2)
        Utinv = U.inverse().transpose(-1, -2)

        phi_l = (L.transpose(-1, -2) @ L_grad).tril_()
        phi_l.diagonal(dim1=-2, dim2=-1).mul_(0.0)

        phi_u = (U_grad @ U.transpose(-1, -2)).triu_()

        A_grad = Ltinv @ (phi_l + phi_u) @ Utinv

        return P @ A_grad

for i in range(5):
    size = 6
    S = torch.rand(2, size, size, dtype=torch.double).requires_grad_(True)

    gradcheck(LU.apply, S)
    gradgradcheck(LU.apply, S)

```
You can see that `lu_unpack` is used. However, `lu_unpack` comes from `torch`, not `ATen`.

Does it make any sense to wrap LU and LU_solve into a Function?

**Comment by albanD** [comment]
For things that are too tricky to implement on the c++ side, it is fine to have a python-only version that is differentiable.
Similarly to what we did for lobpcg: if no input requires_grad, use the old codepath via c++. Otherwise, use a custom Function to enable autograd.

**Comment by nikitaved** [comment]
`torch.lu` returns a packed LU decomposition. In the differentiable version of `torch.lu` we receive LU_grad in the backward step. If you look at the diagonal of LU_grad, it is not possible to decouple the contributions of L_grad and U_grad. In order to separate these contributions, we need a new function that returns L and U separately, so that we receive explicit L_grad and U_grad in the backward step. Same holds for `lu_solve`, of course. What are your thoughts on the new functions' names?

**Comment by albanD** [comment]
>  In the differentiable version of torch.lu we receive LU_grad in the backward step. If you look at the diagonal of LU_grad, it is not possible to decouple the contributions of L_grad and U_grad.

Does that mean that you can't write a backward for `lu_unpack` itself?
And you can only write the backward if the forward is the pair `lu` + `lu_unpack` ?

**Comment by nikitaved** [comment]
Yes, lu + lu_unpack in forward is required for a well-defined backward.

**Comment by albanD** [comment]
> Oh, wait, I think there might be a workaround, as, essentially LU = L - I + U!

But is that unique? Does it matter if it's not?
Note that if you write it this way, the same gradient as the ones in LU will flow for both L and U :D

**Comment by nikitaved** [comment]
And now I am having an issue that `gradcheck` passes, but `gradgradcheck` does not.

**Comment by nikitaved** [comment]
@alban, this is really weird. Check out this script:
```python
import torch                                                                                                                                      
from torch.autograd import gradcheck, gradgradcheck                                                                                               
                                                                                                                                                  
class LU(torch.autograd.Function):                                                                                                                
    @staticmethod                                                                                                                                 
    def forward(ctx, A):                                                                                                                          
        lu, pivots = A.lu()                                                                                                                       
        p, l, u = torch.lu_unpack(lu, pivots)                                                                                                     
        ctx.save_for_backward(l, u, p)                                                                                                            
        ctx.mark_non_differentiable(pivots)
        return lu, pivots

    @staticmethod
    def backward(ctx, LU_grad, pivots_grad):
        L, U, P = ctx.saved_tensors

        Ltinv = L.inverse().transpose(-1, -2)
        Utinv = U.inverse().transpose(-1, -2)

        phi_l = (L.transpose(-1, -2) @ LU_grad).tril_()
        phi_l.diagonal(dim1=-2, dim2=-1).mul_(0.0)

        phi_u = (LU_grad @ U.transpose(-1, -2)).triu_()

        A_grad = Ltinv @ (phi_l + phi_u) @ Utinv

        return P @ A_grad, None

for i in range(5):
    print(i)
    size = 2
    S = torch.rand(2, size, size, dtype=torch.double).requires_grad_(True)

    gradcheck(LU.apply, S)
    gradgradcheck(LU.apply, S, [torch.rand(2, size, size, dtype=torch.double)])

```


When I use `gradgradcheck(LU.apply, S)` I get
```
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 0.0000e+00,  1.1102e-10, -1.3529e-01,  1.3814e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -5.5511e-11,  1.1102e-10,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-1.3529e-01,  0.0000e+00,  1.5474e-02, -7.8998e-02,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.3814e+00,  0.0000e+00, -7.8998e-02,  1.1102e-10,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          1.3878e-11, -3.6904e+01,  8.4449e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00, -1.1102e-10],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, -3.6904e+01,
          0.0000e+00,  1.6676e+01, -1.9081e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  8.4449e-01,
          0.0000e+00, -1.9081e-01,  0.0000e+00]], dtype=torch.float64)
analytical:tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

```

Now I call `gradgradcheck(LU.apply, S, [torch.rand(2, size, size, dtype=torch.double)])` and I get:
```
RuntimeError: Numerical gradient for function expected to be zero
```

Finally, with `gradgradcheck(LU.apply, S, [torch.zeros(2, size, size, dtype=torch.double)])` I get a pass.

Is there something I am doing super wrong in backward?

**Comment by albanD** [comment]
> Oh, could it be these in-place operations actually???

If it was, you would see "value that is required for backward has been modified by an inplace op".

> "Numerical gradient for function expected to be zero"

IIRC from the gradcheck code, this happens when the output of the function does not require gradients.
Did you checked that running backward with `create_graph=True` creates gradients that require grads?

**Comment by nikitaved** [comment]
Could you please elaborate? The gradgradcheck creates grad_outputs if they are not provide. I get this `Numerical gradient for function expected to be zero` when I provide grad_outputs.

**Comment by albanD** [comment]
> It is also weird that analytic solution is all zeros...

The error "Numerical gradient for function expected to be zero" happens if your function returns nothing that requires grad. See the check [here](https://github.com/pytorch/pytorch/blob/e1c9aa918a7a0a5a06d9d276206f42341f1ea714/torch/autograd/gradcheck.py#L322-L331).

So the error comes from the fact that your forward saves for backward something that is neither an input or output.
Why don't you just save the lu and pivots and move the `lu_unpack` in the backward?

**Comment by JesseLivezey** [comment]
#46284 closes this for the full rank case!

**Comment by nikitaved** [comment]
@JesseLivezey , unfortunately, not yet. It is the combination of `lu` and `lu_solve` in forward which is required to propagate to the original input you call `lu` on. So, the next step is to implement backward for `lu_solve`.

Since `lu_solve` is implemented in ATen, the easiest way to implemented is to make an ATen version of `lu_unpack`.
