### ISSUE TITLE
Add unit tests that load jit models to protect against issues with API changes

### ISSUE THREAD

**Issue by nairbv** [pytorch/pytorch#22650]
We should have tests that load jit models such that we would catch the kind of issue that arose when we made changes to an interface of log_softmax in:

https://github.com/pytorch/pytorch/pull/22237

cc @suo

**Comment by suo** [comment]
Closing as we now have tests that do this as well as backcompat tests for operators.

**Comment by nairbv** [comment]
@suo is there a particular PR?
