### ISSUE TITLE
JIT type

### ISSUE THREAD

**Issue by NeilWangziyu** [pytorch/pytorch#22678]
## ❓ Questions and Help

1.  Since jit support int, float, string, List , dict, etc, how can I write a template that allows an input with different types?

I wish I can write something like template in C++, is it possible?

2. why can not save a funtion in the binary file?  for example,  
```python
@torch.jit.script
def foo(x, tup):
  # type: (int, Tuple[Tensor, Tensor]) -> Tensor
  t0, t1 = tup
  return t0 + t1 + x

foo.save("test.pt")
```

3. when I use that function, it said please report a bug
```python
@torch.jit.script
def test_jit(input_fs1:Tuple[str]) -> Tuple[str]:
    res = ""
    for i in range(len(input_fs1)):
        res += input_fs1[i]
    return (res)
```
Traceback (most recent call last):
  File "c:\Users\t-ziw\Documents\myCode\simplepytorch\GenericANewtype.py", line 213, in <module>
    def test_jit_for_document(input_fs1:Tuple[str]) -> Tuple[str]:
  File "C:\Users\t-ziw\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\jit\__init__.py", line 824, in script
    fn = torch._C._jit_script_compile(ast, _rcb, get_default_args(obj))
RuntimeError: v->type()->isSubtypeOf(elem_type) ASSERT FAILED at ..\torch\csrc\jit\ir.cpp:1272, please report a bug to PyTorch. (createList at ..\torch\csrc\jit\ir.cpp:1272)

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by wanchaol** [comment]
Hi @NeilWangziyu 

For your questions:
1. it's not possible, TorchScript now is a statically typed language, if you want to add different handling for different input types, you can add an different overload in python. 
2. I tried your script it works fine on my side, which version of pytorch you are in? maybe consider switching to recent nightly builds?
3. We can add a support for `len` on Tuple, but it's ultimately not too much use, your `input_fs1` is a `Tuple[str]`, which is apparently only one element inside.

**Comment by NeilWangziyu** [comment]
Hi @wanchaol , 

for 2, the function I want to save, 
```python
@torch.jit.script
def foo(x:int, tup:Tuple[int, int])->int:
    t0, t1 = tup
    return t0 + t1 + x

print(foo(3,(3,3)))
torch.jit.save(foo, "test.pt")
```

I have the error info:
```bash
Traceback (most recent call last):
  File "c:\Users\t-ziw\Documents\myCode\simplepytorch\usingJit.py", line 160, in <module>
    torch.jit.save(foo, "test.pt")
  File "C:\Users\t-ziw\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\jit\__init__.py", line 198, in save
    m.save(f, _extra_files=_extra_files)
AttributeError: 'torch._C.Function' object has no attribute 'save'
```
I am currently using  pytorch latest version 1.1.0

I am curiosity because I chase to the scrip class definition, if I want to save a class, it can be done, and if i want to save  a function, it will switch to another direction. I check the history, around 2 months ago those codes are changed. Previously a function can be saved.

**Comment by soumith** [comment]
> I am currently using pytorch latest version 1.1.0

pytorch master branch fixed it, i think.

**Comment by NeilWangziyu** [comment]
I try to install torch-nightly, however, I meet that problem
```bash
(puretorch) C:\Users\t-ziw>python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\t-ziw\AppData\Local\Continuum\anaconda3\envs\puretorch\lib\site-packages\torch\__init__.py", line 79, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified procedure could not be found.
```
I install torch-nightly in conda env, meanwhile, I tried install by pip, and build myself, same problem occurs.
