### ISSUE TITLE
CUDNN_STATUS_BAD_PARAM and LSTM/RNN or any recurrent structure

### ISSUE THREAD

**Issue by rasoolfa** [pytorch/pytorch#2267]
I am getting a very strange error when using bidirectional lstm in which it deals with a very long sequence:

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import torch.autograd as autograd

def Variable(data, *args, **kwargs):
    if torch.cuda.is_available():
        return autograd.Variable(data.cuda(), *args, **kwargs)
    else:
        return autograd.Variable(data, *args, **kwargs)

class LSTM_MEM_LEAK(nn.Module):
    
    def __init__(self):
      
        super(LSTM_MEM_LEAK, self).__init__()
        self.h_size = 600
        self.e_size = 900
        self.l1 = nn.Linear(256, self.e_size)
        self.lstm =nn.LSTM(self.e_size, self.h_size, batch_first = True, num_layers = 2, bidirectional = 1)
        self.l2 = nn.Linear(self.h_size*2, 300)
            
    def forward(self, input):
        
        hidden = (Variable(torch.zeros(2*2, 16, self.h_size)),
                Variable(torch.zeros(2*2, 16, self.h_size))) 
        l1 = F.relu(self.l1(input.view(-1, 256)))
        lstm_out, h = self.lstm(l1.view(16, -1, self.e_size), hidden)
        l2  = F.relu(self.l2(lstm_out.contiguous().view(-1, self.h_size*2)))
        
        return l2    
    
net = LSTM_MEM_LEAK()
net.cuda()
input = Variable(torch.rand(16, 6000, 256))
print(input.requires_grad)
out = net(input)
```
and here is the error:

```
Traceback (most recent call last):
File "test.py", line 38, in 
out = net(input)
File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in call
result = self.forward(*input, **kwargs)
File "test.py", line 29, in forward
lstm_out, h = self.lstm(l1.view(16, -1, self.e_size), hidden)
File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in call
result = self.forward(*input, **kwargs)
File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 162, in forward
output, hidden = func(input, self.all_weights, hx)
File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/_functions/rnn.py", line 351, in forward
return func(input, *fargs, **fkwargs)
File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/autograd/function.py", line 284, in doforward
flat_output = super(NestedIOFunction, self).doforward(*flat_input)
File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/autograd/function.py", line 306, in forward
result = self.forward_extended(*nested_tensors)
File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/nn/_functions/rnn.py", line 293, in forward_extended
cudnn.rnn.forward(self, input, hx, weight, output, hy)
File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/backends/cudnn/rnn.py", line 305, in forward
ctypes.c_void_p(fn.reserve.data_ptr()), fn.reserve.size(0)
File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 255, in check_error
raise CuDNNError(status)
torch.backends.cudnn.CuDNNError: 3: b'CUDNN_STATUS_BAD_PARAM'

```
This error happens when h_size >=600 and using bi-LSTM.
I guess there is a bug somewhere. 
In addition, I believe this is related to the following issue:
https://github.com/pytorch/pytorch/issues/2198
and I asked in the forum as well:
https://discuss.pytorch.org/t/cudnn-status-bad-param-and-lstm/5604
Any idea what is the problem?

**Comment by ngimel** [comment]
It is not related to #2198, it is an overflow in reserve size (reserve size becomes more than 2^32). Happens likely on the python ctypes side, because in cudnn argument type for reserveSpaceSizeInBytes is size_t (should not overflow), and even though reserve_size.value is 4730880000, cudnn sees it as 435912704 (via ltrace, for sequence length of 5600 instead of 6000).

**Comment by rasoolfa** [comment]
Thanks.
That is interesting it doesn't **usually*** happen when "torch.backends.cudnn.enabled = False". Another observation, when this torch.backends.cudnn.enabled is true, the memory usage increases way faster than the time this flag is false which is I guess should be the case?!.

** sometimes segmentation fault happens.

**Comment by ngimel** [comment]
Of course if you turn off cudnn backend, you can not get CUDNN_STATUS_BAD_PARAM error. Memory use of pytorch's cudnn rnn module has been a topic of a long standing discussion, still not quite resolved, to the best of my knowledge. You are trying to run very long sequences (6000) through a reasonably large network, you are working somewhere at the memory limit. I agree segfaults should not happen, and if you have a repro, please post it, but your problem is pushing hardware to the limit.

**Comment by rasoolfa** [comment]
Thanks, @ngimel.
The segfaults sometimes happen if you run above code [multiple times ] with .cudnn.enabled = False. If you weren't able to reproduce, try to increase h_size and e_size.

**Comment by Xiaolong-Li** [comment]
I had the same error. In my case, it was caused by the date type of the input data. The model expected float32, while my input was float64.

**Comment by spandan2** [comment]
When I and @Culeshovi checked on this error, we found that while our data was float64, we were padding it with float32, when we made the both types the same, the error was avoided.

**Comment by yydxlv** [comment]
The same error "cuDNN error: CUDNN_STATUS_BAD_PARAM" occured when i use LSTM , when i changed the dtype from torch.float64 to torch.float32. The error was avoided.

**Comment by another-dark-knight** [comment]
To get more sensible error messages pin pointing the problems, we could just disable the cudnn backend.
