### ISSUE TITLE
Stuck when backward

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#22679]
```
# parameter
GPU: [0,1,2,3]
world_size:1
rank=0
url:"tcp://127.0.0.1:10087"
# don't use multi processing mode
```
The code converting model to support distribute mutli gpu:
```
torch.cuda.set_device(0)
model.cuda()
# gpu_ids =  [0,1,2,3]
model = torch.nn.parallel.DistributedDataParallel(model, device_ids=gpu_ids)
```
When I exec "loss.backward()", the program stuck sometimes(Probability：3/4).  

When I modify to single node multi gpu, so that change `DistributedDataParallel` to `DataParallel` the program run.

 When I use multi process, the program also can run.
···
# use multi process
mp.spawn(train, nprocs=4)

# don't use multi process
train(gpu_ids)
···

**Comment by as754770178** [comment]
I run in `nvidia-docker`

**Comment by pietern** [comment]
If I understand correctly:
* Your program works if you run a single copy and use `nn.DataParallel`.
* Your program works if you launch 4 copies and use `nn.DistributedDataParallel`.
* Your program does NOT work if you launch a single copy and use `nn.DistributedDataParallel`.

Can you confirm?

Also please include the details about your environment prompted in the issue template (e.g. PT version).

**Comment by mrshenli** [comment]
@as754770178 Is the error still bothering you? BTW, when you run DDP, does each process exclusively uses its gpus? In the code snippet above, it seems you call `torch.cuda.set_device(0)` in all processes?

**Comment by as754770178** [comment]
Yes, I call `torch.cuda.set_device（0）` in all processes. `torch.cuda.set_device` is setting the main gpu, `gpu_ids` in `torch.nn.parallel.DistributedDataParallel(model, device_ids=gpu_ids)` is setting which gpu training. Is this wrong?

**Comment by pietern** [comment]
Yes. If you use multiple processes, each process should set its own GPU. You can use the process rank to figure out which GPU device to use. Then that's also the device you pass to the `DistributedDataParallel` constructor. Then, every process will use a single GPU, and they will average their gradients on every backward pass.

This also explains why you were seeing hangs: you probably had N processes trying to use M GPUs, for a total of N*M model replicas. All these instances would then call into NCCL, which doesn't guarantee it works under any amount of concurrency.

**Comment by as754770178** [comment]
```code
if dist:
  if isinstance(gpu_ids, int):
    # if use torch.multiprocessing run this
    torch.cuda.set_device(gpu_ids)
    model.cuda(gpu_ids)
   elif isinstance(gpu_ids, list):
      torch.cuda.set_device(gpu_ids[0])
      model.cuda()
      model = torch.nn.parallel.DistributedDataparallel(model, device_ids=gpu_ids)
  else:
     model.cuda()
     model = torch.nn.parallel.DistributedDataparallel(model, find_unused_parameters=True)
elif  isinstance(gpu_ids, int):
  torch.cuda.set_device(gpu_ids)
  model.cuda(gpu_ids)
  model = torch.nn.DataParallel(model, device_ids=gpu_ids)
elif  isinstance(gpu_ids, int):
  torch.cuda.set_device(gpu_ids[0])
  model.cuda()
  model = torch.nn.DataParallel(model, device_ids=gpu_ids)
else:
  model.cuda()
  model = torch.nn.DataParallel(model)
```

I refer to the pytorch imagenet example. Can you explain the using of ` torch.cuda.set_device()`. I read in document, this function only set the device to use. This function is not setting the main gpu to use. Can I think ` torch.cuda.set_device(gpu_ids[0])` is useless, if `isinstance(gpu_ids, list)`?

**Comment by pietern** [comment]
It's not useless, as we expect the input to the model to be loaded on the first GPU to let DDP subsequently scatter it to the other GPUs in the list.

Coming back to the original issue, did the advice resolve your hang problem?

**Comment by as754770178** [comment]
Yes, the program not stuck.

**Comment by pietern** [comment]
@as754770178 Thanks for confirming and closing the issue.

**Comment by as754770178** [comment]
@pietern 
my program still sometimes stuck, when I run in distributed. when i run in one node, the program not stuck.

**Comment by pietern** [comment]
@as754770178 Can you provide more details?

**Comment by as754770178** [comment]
Thanks 
I use
```
inputs = inputs.cuda()
labels= labels.cuda()

 model.cuda()
 model = torch.nn.parallel.DistributedDataparallel(model, find_unused_parameters=True)

# or 

model.cuda(0)
model = torch.nn.parallel.DistributedDataparallel(model, device_ids=[0,1,2,3,4,5,6,7,8])
```
The program all stuck.
Now I clone one program that use
```
device = torch.device("cuda")
inputs = inputs.to(device)
labels= labels.to(device)

model = model.to(device)
 model = torch.nn.parallel.DistributedDataparallel(model, find_unused_parameters=True)
```

I want to kown what different bewteen `to(device)` and `cuda()`

**Comment by as754770178** [comment]
@pietern 
I want to know when exec `loss.backward()`, whether use nccl to synchronize gradients. If synchronize gradients, I check whether is  a communication error.

**Comment by pietern** [comment]
If you use `torch.nn.parallel.DistributedDataparallel`, calling `loss.backward()` after doing a forward pass means you'll trigger gradient synchronization. Whether or not that's executed by NCCL depends on how you have initialized the distributed package. The backend is the first argument to `torch.distributed.init_process_group`.

The difference between `to(device)` and `cuda()` is that `cuda()` moves the model or tensor to the current CUDA device (set by `torch.cuda.set_device`), whereas `to(device)` takes an explicit device.

**Comment by pietern** [comment]
It's not clear whether or not you've solved the hang issue and under what exact circumstances it occurred for you. If this is still an issue please report back with the exact way you're launching these jobs (e.g. number of processes, how many machines, how do you launch, how do you initialize, etc). In the mean time, I'll close the issue.

**Comment by meiluzhu** [comment]
> If you use `torch.nn.parallel.DistributedDataparallel`, calling `loss.backward()` after doing a forward pass means you'll trigger gradient synchronization. Whether or not that's executed by NCCL depends on how you have initialized the distributed package. The backend is the first argument to `torch.distributed.init_process_group`.
Hi @pietern , Where is the script of gradient synchronization after calling backward() in pytorch source code? I was confused about this problem for few days.

**Comment by pietern** [comment]
> Hi @pietern , Where is the script of gradient synchronization after calling backward() in pytorch source code? I was confused about this problem for few days.

Please post questions to the discussion forums at https://discuss.pytorch.org/.

**Comment by Luonic** [comment]
@gemfield have you resolved your issue? I experience exactly same issues on fresh CUDA 11 and Pytorch 1.7.0 installation. Nvidia driver is 455.something version. My code were running perfectly before.
I have tried to run it with Pytorch 1.5.1 in docker container but issue persists.
Maybe problem is newer driver that breaks NCCL?

**Comment by gemfield** [comment]
@Luonic Yes, solved this issue by the nvidia driver upgrade. But be noted that this was happend on Sep, don't know if is still ok with the latest drivers.

**Comment by Hzzone** [comment]
I met this problem, \ie, the GPU utilization suddenly reached 100%, the DDP stoped at `process.wait()` and I have to use ctrl+c to stop them. This problem happens sometimes but not in a special iteration or epoch. I trained my model on four v100 with NVLink. I figured it out as others pointed out: Updating your nvidia-driver and cuda version. Originally, mine is 418 and cuda 10.1, and I solved this problem with the updated driver, \ie, 440 and cuda 10.2

**Comment by Hzzone** [comment]
Sorry for my mistake. I have updated the cuda and driver but found it useless. When I tried to use other GPUs, \eg, from 0,1,2,3 to 0,1,4,5, I found that the 2,3 GPUs have been allocated about 1G memory, although I used torch.cuda.set_device(id) at the beginning of main function. Luckily, setting the CUDA_VISIBLE_DEVICES environments solved my problem. That's a so annoying experience.  😓

**Comment by dishofchicken** [comment]
I've been in this situation several times. Most recently, I used conditional statements in my program so that some network parameters were not trained in some cases. 
The strange thing is that the program used to raise the error of "RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss", but this time I didn't get any information. It took me a long time to debug. I hope this information is useful.

**Comment by Hzzone** [comment]
Update: I have found that it is the problem of the GPUs. I have tested a simple demo with a classification task on each GPU one by one, and I found that the one GPU stuck for some iterations.

**Comment by JohnHerry** [comment]
> Update: I have found that it is the problem of the GPUs. I have tested a simple demo with a classification task on each GPU one by one, and I found that the one GPU stuck for some iterations.

One GPU stuck will cause all GPU show 100%?
