### ISSUE TITLE
[docs] torch.lerp typo

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#22697]
## 📚 Documentation

https://pytorch.org/docs/master/torch.html#torch.lerp

`The shapes of start and end must be broadcastable. If weight is a tensor, then the shapes of start, end must be broadcastable.`

Should probably be `weight, start, end` must be broadcastable at the end.

**Comment by fmassa** [comment]
Agree, it should probably be `weight, start, end`

**Comment by vishwakftw** [comment]
I am marking this as a “good first issue”. Please feel free to remove if you think this is not valid.

**Comment by ilhamfp** [comment]
I have opened a pull request #23477

**Comment by ryokugyu** [comment]
@vishwakftw if it is already resolved. why it is still open?

I am just looking for something to get started for contributing.

**Comment by vishwakftw** [comment]
https://github.com/pytorch/pytorch/pull/23268 has fixed this. Sorry about leaving this open.
