### ISSUE TITLE
randperm on cuda looks buggy

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#22710]
I was looking at https://github.com/pytorch/pytorch/pull/22103 (thanks @xuhdev!) and I noticed a couple of issues with the previous implementation (i.e. https://github.com/pytorch/pytorch/pull/22103 didn't introduce them).

1) The code looks wrong for non-contiguous tensors; it does a resize but that's not guaranteed to give you a contiguous tensor.
2) It's surprising (and does it not cause a problem in all cases?) to use a CPU generator when you passed (potentially) in the CUDA one.  And it would at least be surprising to mess with a different pseudo random stream than you passed in, even if it doesn't cause a problem.

**Comment by xuhdev** [comment]
I've sent a PR to fix point 1 in #23043. Are you sure about point 2? I saw random also uses the random generator in this way:

https://github.com/pytorch/pytorch/blob/fcfefc34394a6edd8dca8a33a76307bf3f83c245/aten/src/ATen/core/Tensor.h#L685
