### ISSUE TITLE
SSL Handshake Error when getting pretrained model

### ISSUE THREAD

**Issue by petered** [pytorch/pytorch#2271]
When I run the script, 

    import torchvision.models
    
    vgg16 = torchvision.models.vgg16(pretrained=True)

I get a "sslv3 alert handshake failure".

> Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /home/petered/.torch/models/vgg16-397923af.pth
> Traceback (most recent call last):
>   File "/home/petered/projects/spint/scripts/get_vgg16_test.py", line 3, in <module>
>     vgg16 = torchvision.models.vgg16(pretrained=True)
>   File "/home/petered/projects/spint/venv/local/lib/python2.7/site-packages/torchvision/models/vgg.py", line 124, in vgg16
>     model.load_state_dict(model_zoo.load_url(model_urls['vgg16']))
>   File "/home/petered/projects/spint/venv/local/lib/python2.7/site-packages/torch/utils/model_zoo.py", line 56, in load_url
>     _download_url_to_file(url, cached_file, hash_prefix)
>   File "/home/petered/projects/spint/venv/local/lib/python2.7/site-packages/torch/utils/model_zoo.py", line 61, in _download_url_to_file
>     u = urlopen(url)
>   File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
>     return _opener.open(url, data, timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 404, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 422, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
>     return self.do_open(httplib.HTTPSConnection, req)
>   File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
>     raise URLError(err)
> urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
> 

Any idea what the problem is?

**Comment by petered** [comment]
Note: I was able to temporarily hack around the problem with:

    import torchvision.models
    from torchvision.models.vgg import model_urls
    
    model_urls['vgg16'] = model_urls['vgg16'].replace('https://', 'http://')
    vgg16 = torchvision.models.vgg16(pretrained=True)

**Comment by vadimkantorov** [comment]
It's an issue with some Python installs related to OpenSSL not shipping some certificate roots.

Sometimes upgrading Python version would help, sometimes it can be more nasty (you may need to build Python from source and link it to a specific version of OpenSSL).

So maybe it'd be cool if the model_urls used plain http if security here isn't an issue.

**Comment by vra** [comment]
You can download model directly according urls in this file: <https://github.com/pytorch/vision/blob/master/torchvision/models/vgg.py>

**Comment by apaszke** [comment]
Worked just fine for me 😕 Probably some problems with your local configuration of OpenSSL. Our certs seem to be alright. See e.g. https://stackoverflow.com/questions/35405092/sslerror-sslv3-alert-handshake-failure
