### ISSUE TITLE
How to convert at::Tensor (one element) type into a float type in c++ libtorch?

### ISSUE THREAD

**Issue by FightStone** [pytorch/pytorch#22731]
When I take an element A (eg: x[1][2][3][4], also type at::Tensor) from a four-dimensional variable x(at::Tensor), I want to compare (or multiply) A and B (float type) , how do I convert A (at::Tensor) to float? Thanks a lot!

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

**Comment by Wendroff** [comment]
I met this problem, too. Have you got the answer?
