### ISSUE TITLE
Installing pytorch nightly with pip fails

### ISSUE THREAD

**Issue by fuzzyBatman** [pytorch/pytorch#22738]
## 🐛 Bug

Instaling pytorch nightly using the method suggested on the [website](https://pytorch.org/get-started/locally/) results in a **404 error**

## To Reproduce

1. Run
```
pip3 install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html --user
```

## Expected behavior

Install pytorch nightly. This procedure worked a few weeks ago.

## Observed behavior

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/torch-nightly/
```

## Environment

 - PyTorch Version (e.g., 1.0): Nightly
 - OS (e.g., Linux): Debian 9 on a Google cloud VM
 - Python version: 3.5
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: Tesla T4

**Comment by fuzzyBatman** [comment]
Temporarily resolved by downloading the wheel manually

```
wget https://download.pytorch.org/whl/nightly/cu100/torch_nightly-1.2.0.dev20190710-cp35-cp35m-linux_x86_64.whl
```

**Comment by xuhdev** [comment]
Still haven't fixed yet...

**Comment by rgommers** [comment]
This works fine as of right now, and the nightly is up-to-date (built July 24th):
```
$ pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
Looking in links: https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
Collecting torch_nightly
  Downloading https://download.pytorch.org/whl/nightly/cu100/torch_nightly-1.2.0.dev20190724-cp37-cp37m-linux_x86_64.whl (742.2MB)
     |████████████████████████████████| 742.3MB 84kB/s 
Installing collected packages: torch-nightly
Successfully installed torch-nightly-1.2.0.dev20190724
```

> `Client Error: Not Found for url: https://pypi.org/simple/torch-nightly/`

this error is a little confusing. @fuzzyBatman this should work now, but if you add `--no-index` you should get a more comprehensible error if the custom wheel index server for the nightlies isn't found:
```
pip install torch_nightly --no-index -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
```

Also note that these kind of errors can depend on the version of `pip` that you use (e.g. https://github.com/pypa/pip/issues/4580). The nightly is definitely present, so if it doesn't work for you please upgrade to the latest pip and try again.

**Comment by fuzzyBatman** [comment]
@rgommers Thanks. Updating pip fixed that issue.

**Comment by Borda** [comment]
Hello,
 is there a way how to install PT nightly (1.8) from pip? We can do it with Conda, but I have troubles with pip, I have found and tried...
```
pip install "torch==1.8.*" --use-feature=2020-resolver --pre --extra-index-url https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
```
but this gives an error with not matching distribution, then I have tried exact version `torch==1.8.0.dev20201110` which I can see on the web with the same failure
For the record, I am using NVIDIA Ubuntu based docker image `nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04` and python 3.7

**Comment by johndpope** [comment]
@Borda 
just digging around google - found this https://discuss.pytorch.org/t/rtx-3000-support/98158/5

`pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html`
