### ISSUE TITLE
libtorch gpu lstm bidirectional questions

### ISSUE THREAD

**Issue by cbigeyes** [pytorch/pytorch#22739]
Hello.
When I tried libtorch for bilstm, I set the options as below:
`torch::nn::LSTM(torch::nn::LSTMOptions(emb_size,hidd_size).bidirectional(true)))`
But I got this error:

> terminate called after throwing an instance of 'c10::Error' what():  Expected cell size [2, 10, 100], got [1, 10, 100]

10 is batch size, 100 is hidden size.
What should I do to deal with it?

**Comment by jerryzh168** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply
