### ISSUE TITLE
[docs] torch.tensordot example is a little confusing

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#22748]
## 📚 Documentation

![image](https://user-images.githubusercontent.com/5652049/61066216-1bb84980-a3d3-11e9-9a9e-1f4ff38da81c.png)

It would be good for the example to do a contraction over three dimensions instead of two. Looking at the example alone, it isn't clear if you're supposed to pass in a collection of pairs or a pair of collections. There is one line in the docs that mentions this, but making the example clearer would be nice.

**Comment by wenting-zhao** [comment]
Found the doc confusing too...
