### ISSUE TITLE
nn.Conv2d allocate huge memory for some shapes and data type on V100 

### ISSUE THREAD

**Issue by kingder** [pytorch/pytorch#22741]
## 🐛 Bug

We found huge memory needed to run Conv2d when some specific shapes and data type used  on V100. 
I've found this when debug a wired OOM issue, the memory will suddenly jump 4-5x during training on V100 with mixed precision. 
After some debugging, I've found it was caused by the `cudnnGetConvolutionBackwardFilterAlgorithm` in `Conv.cpp` in PyTorch 0.4.1 with cudnn 7.4 / 7.5 that will return algorithm 2 (CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT), and then `getWorkspaceSize` will return a huge size (>8G) for this setting. It may be a cudnn issue. (it works fine with cudnn 7.0, but will have this issue with 7.4 or 7.5)

PyTorch 1.1.0 with cudnn 7.5 also has this issue.

## To Reproduce

```
import torch
import time
import torch.nn as nn
#print("cudnn version", torch.backends.cudnn.version())

conv = nn.Conv2d(128,128,(3,3),dilation=(1,1), padding=(1,1)).cuda().half()
#torch.backends.cudnn.benchmark=True

input = torch.randn(1,128,168,64, device="cuda").half()
out=conv(input)
gO=torch.rand_like(out)
torch.cuda.synchronize()
#torch.backends.cudnn.benchmark=True
s = time.time()
out = conv(input.detach())
print("before bp: cuda memory: alloc: {}, cached: {}".format(torch.cuda.memory_allocated(), torch.cuda.memory_cached()))
out.backward(gO)
print("after bp: cuda memory: alloc: {}, cached: {}".format(torch.cuda.memory_allocated(), torch.cuda.memory_cached()))
torch.cuda.synchronize()
e = time.time()
print((e-s)/100)
```

### Output
```
before bp: cuda memory: alloc: 9418240, cached: 23068672
after bp: cuda memory: alloc: 9713664, cached: 8686403584
0.0013481926918029784
```

## Expected behavior

It should not need so much memory to run a single conv2d op or let us control not to use the memory heavy algorithms in cudnn.

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.9.4
CMake version: version 2.8.12.2

Python version: 3.6

cuDNN version: 7.5

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[pip] torchvision==0.2.2.post3
[conda] torch                     1.1.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

## Additional context

cc @csarofeen @ptrblck

**Comment by sefira** [comment]
I‘ve encountered the same problem on V100.
Is there any cue for solving this?

**Comment by mruberry** [comment]
@ptrblck - any ideas?

**Comment by ptrblck** [comment]
This might have been a known issue for cudnn7.5.
I tried to reproduce it using the provided code snippet with all supported binaries and it seems the memory usage is alright:
| pytorch version | cuda | cudnn | before mem print | after mem print |
|---------------------------|----------|------------|----------------------------------------------------------------|--------------------------------------------------------------|
| pytorch 1.6.0             | cuda9.2  | cudnn7.6.3 | before bp: cuda memory: alloc: 8.15MB, cached: 22.0MB | after bp: cuda memory: alloc: 8.43MB, cached: 34.0MB |
| pytorch 1.6.0             | cuda10.1 | cudnn7.6.3 | before bp: cuda memory: alloc: 8.15MB, cached: 22.0MB | after bp: cuda memory: alloc: 8.43MB, cached: 34.0MB |
| pytorch 1.6.0             | cuda10.2 | cudnn7.6.5 | before bp: cuda memory: alloc: 8.15MB, cached: 22.0MB | after bp: cuda memory: alloc: 8.43MB, cached: 34.0MB |
| pytorch 1.8.0.dev20201012 | cuda11.0 | cudnn8.0.3 | before bp: cuda memory: alloc: 8.15MB, cached: 22.0MB | after bp: cuda memory: alloc: 8.43MB, cached: 22.0MB |

**Comment by mruberry** [comment]
Thank you, @ptrblck. @kingder, is updating cuDNN an option?

**Comment by kingder** [comment]
> Thank you, @ptrblck. @kingder, is updating cuDNN an option?

Thanks for looking into it, seems like a cuDNN issue.
