### ISSUE TITLE
Use Caffe2 function in PyTorch possible?

### ISSUE THREAD

**Issue by snippler** [pytorch/pytorch#22746]
My question is with regard of compatibility of PyTorch and Caffe2. Is it possible to import functions of Caffe2 into a PyTorch program. Obviously it does not work directly but is there any workaround?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soumith** [comment]
not supported officially
