### ISSUE TITLE
Dose Pytorch supports lstm with projection layer

### ISSUE THREAD

**Issue by Marcovaldong** [pytorch/pytorch#22740]
As the title, dose PyTorch supports [lstm with projection layer](https://static.googleusercontent.com/media/research.google.com/zh-CN//pubs/archive/43905.pdf) now? There are a lot of models using this variant of lstm, is there a plan to support it? 

@soumith @ngimel @Kaixhin

**Comment by soumith** [comment]
no. there is no plan to support it. the guidance is to ask people to write custom LSTM: https://pytorch.org/blog/optimizing-cuda-rnn-with-torchscript/
