### ISSUE TITLE
NDEBUG is not set in Release mode

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#22745]
## 🐛 Bug

The generated VariableType has debug code that looks like:

```
  #ifndef NDEBUG
  c10::optional<Storage> self_storage_saved =
    self.has_storage() ? c10::optional<Storage>(self.storage()) : c10::nullopt;
  c10::intrusive_ptr<TensorImpl> self_impl_saved;
  if (self.defined()) self_impl_saved = self.getIntrusivePtr();
  c10::optional<Storage> other_storage_saved =
    other.has_storage() ? c10::optional<Storage>(other.storage()) : c10::nullopt;
  c10::intrusive_ptr<TensorImpl> other_impl_saved;
  if (other.defined()) other_impl_saved = other.getIntrusivePtr();
  #endif
```

We don't define `NDEBUG` in Release mode so this code always runs. It adds ~100 ns to the overhead of every operation. 

It's generated by:
 https://github.com/pytorch/pytorch/blob/89d6e8804267d467e39529d710e2da39982905fa/tools/autograd/gen_variable_type.py#L263-L267

cc @ezyang @gchanan @zou3519 @yf225

**Comment by colesbury** [comment]
cc @kimishpatel @zheng-xq 

I'm not sure if we define `NDEBUG` in Facebook's internal build of PyTorch either.

**Comment by yf225** [comment]
Should we add `NDEBUG` to Release mode? The debug code is useful for maintaining the invariant that any ATen operator should not change the TensorImpl or Storage pointer of an input tensor. It's gated with `#ifndef NDEBUG` because we only want to test it in debug mode.

**Comment by colesbury** [comment]
@yf225, yes that seems reasonable. We'd also want to make sure that Facebook's build also uses NDEBUG. Be aware that NDEBUG will affect additional files and some included third-party headers (like pybind11)

**Comment by ezyang** [comment]
We are still not compiling open source with NDEBUG. However, in fbcode we are compiling with NDEBUG. Raising priority as we saw this saw some asserts that are commented out with NDEBUG are a major performance problem for small models internally

**Comment by Baranowski** [comment]
I would like to work on this. But if it's urgent and there are other candidates, they should probably take it since I might take my time on this.
