### ISSUE TITLE
Confusing example of broadcasting in torch.matmul

### ISSUE THREAD

**Issue by chmendoza** [pytorch/pytorch#22763]
## 📚 Documentation

I think this example given in https://github.com/pytorch/pytorch/blob/9c4c9c3af042498144c40b30d64443cca943906a/torch/_torch_docs.py about broadcasting is confusing:

In lines 3174 to 3176:

> 
For example, if :attr:`tensor1` is a :math:`(j \times 1 \times n \times m)` tensor and :attr:`tensor2` is a :math:`(k \times m \times p)` tensor, :attr:`out` will be an :math:`(j \times k \times n \times p)` tensor.

the first and second trailing dimensions of `tensor1` and `tensor2` don't match, assuming obviously that `m` is not equal to neither `p` or  `n`, and neither of those three dimensions is 1.

**Comment by vishwakftw** [comment]
I think the docs need to specify that broadcasting of batch dimensions is permitted.

**Comment by bdhirsh** [comment]
marking as closed since this was fixed by https://github.com/pytorch/pytorch/pull/45699
