### ISSUE TITLE
torch_default_collate is slow when net is runing at multi gpu

### ISSUE THREAD

**Issue by guanfuchen** [pytorch/pytorch#22789]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

torch_default_collate is slow when net is runing at multi gpu

just fake data [64, 3, 720, 1280], one gpu about 620 fps, but when it is running at 8gpu, just 300fps, I see the different is torch_default_collate, when it is removed, it is fast but can not stack all data into one batch 64.

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by guanfuchen** [comment]
And I see the torch_default_collate function use torch.stack, and it costs a lot, about 0.3s when the size is 32x3x720x1280

**Comment by SsnL** [comment]
Are you loading data to GPU in dataset? Most dataset code should return CPU tensors.

**Comment by fmassa** [comment]
Please provide a minimum working example illustrating the slowdown, as without further code it is very hard for us to identify what could be possibly wrong.
