### ISSUE TITLE
ONNX export of NVidia Tacotron2

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#22786]
## 🐛 Bug
Reference bug report: https://github.com/onnx/onnx/issues/1956

Traceback (most recent call last):
  File "inference.py", line 49, in <module>
    torch.onnx.export(model, dummy_input, "tacotron.onnx", verbose=True )
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py", line 281, in _export
    example_outputs, propagate)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py", line 224, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/onnx/utils.py", line 192, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/jit/__init__.py", line 197, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace)(*args, **kwargs)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/torch/jit/__init__.py", line 243, in forward
    in_vars, in_desc = _flatten(args)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got int`

Update:
The error shows:
in_vars, in_desc = _flatten(args)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got int`
However, I tried to print(type(args)), and it shows args is tuple type.

## To Reproduce

1. git clone https://github.com/NVIDIA/tacotron2
2. download tacotron2 model from the above github page
3. run the following code sample.

```python
import sys
sys.path.append('waveglow/')
import numpy as np
import torch

from hparams import create_hparams
from model import Tacotron2
from train import load_model

hparams = create_hparams()
hparams.sampling_rate = 22050
checkpoint_path = "tacotron2_statedict.pt"
model = load_model(hparams)
model.load_state_dict(torch.load(checkpoint_path, map_location='cpu')['state_dict'])
_ = model.eval()

text_inputs = torch.randn(64, 163, device='cpu')
text_legths = torch.randn(64, device='cpu')
mels = torch.randn(64, 80, 851, device='cpu')
max_len = 163
output_lengths = torch.randn(64, device='cpu')
dummy_input = (text_inputs, text_legths, mels, max_len, output_lengths)

torch.onnx.export(model, dummy_input, "tacotron.onnx", verbose=True)
```

## Expected behavior

No error occurs.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - Is CUDA available: No
 - CUDA runtime version: No CUDA
 - GPU models and configuration: No CUDA
 - Nvidia driver version: No CUDA
 - cuDNN version: No CUDA
 - Versions of relevant libraries:
   [pip3] numpy==1.16.4
   [pip3] torch==1.1.0
   [pip3] torchvision==0.3.0
   [conda] Could not collect

**Comment by jerryzh168** [comment]
@houseroad

**Comment by jingxu10** [comment]
@houseroad 
Update:
The error shows:
in_vars, in_desc = _flatten(args)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got int`
However, I tried to print(type(args)), and it shows args is tuple type.

**Comment by houseroad** [comment]
The error message shows that you cannot use int as part of the input or output of the model if you export the model with tracing. You may want to change the interface to tensor.

**Comment by pranv12** [comment]
I tried the above code with little changes (converting max_len to tensor). 
But got this error.

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-58-b25defeeab14> in <module>()
     23 output_lengths = torch.randn(64, device='cpu')
     24 dummy_input = (text_inputs, text_legths, mels, max_len, output_lengths)
---> 25 torch.onnx.export(model, dummy_input, "tacotron.onnx", verbose=True)

10 frames
/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
    146                         operator_export_type, opset_version, _retain_param_name,
    147                         do_constant_folding, example_outputs,
--> 148                         strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
    149 
    150 

/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
     64             _retain_param_name=_retain_param_name, do_constant_folding=do_constant_folding,
     65             example_outputs=example_outputs, strip_doc_string=strip_doc_string,
---> 66             dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
     67 
     68 

/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, propagate, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size)
    414                                                         example_outputs, propagate,
    415                                                         _retain_param_name, do_constant_folding,
--> 416                                                         fixed_batch_size=fixed_batch_size)
    417 
    418         # TODO: Don't allocate a in-memory string for the protobuf

/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, training, input_names, output_names, operator_export_type, example_outputs, propagate, _retain_param_name, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size)
    277             model.graph, tuple(in_vars), False, propagate)
    278     else:
--> 279         graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
    280         state_dict = _unique_state_dict(model)
    281         params = list(state_dict.values())

/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py in _trace_and_get_graph_from_model(model, args, training)
    234     # training mode was.)
    235     with set_training(model, training):
--> 236         trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
    237         warn_on_static_input_change(inputs_states)
    238 

/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py in _get_trace_graph(f, args, kwargs, _force_outplace, return_inputs, _return_inputs_states)
    275     if not isinstance(args, tuple):
    276         args = (args,)
--> 277     outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
    278     return outs
    279 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py in forward(self, *args)
    358             in_vars + module_state,
    359             _create_interpreter_name_lookup_fn(),
--> 360             self._force_outplace,
    361         )
    362 

/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py in wrapper(*args)
    345             if self._return_inputs_states:
    346                 inputs_states.append(_unflatten(args[:len(in_vars)], in_desc))
--> 347             outs.append(self.inner(*trace_inputs))
    348             if self._return_inputs_states:
    349                 inputs_states[0] = (inputs_states[0], trace_inputs)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    528                 input = result
    529         if torch._C._get_tracing_state():
--> 530             result = self._slow_forward(*input, **kwargs)
    531         else:
    532             result = self.forward(*input, **kwargs)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    514                 recording_scopes = False
    515         try:
--> 516             result = self.forward(*input, **kwargs)
    517         finally:
    518             if recording_scopes:

TypeError: forward() takes 2 positional arguments but 6 were given`

**Comment by garymm** [comment]
Tracked internally at Microsoft by https://msdata.visualstudio.com/Vienna/_workitems/edit/1472827

This may be blocked by https://github.com/pytorch/pytorch/issues/21909. Not sure if any other work is needed.

**Comment by zwtttttt** [comment]
看看是不是torch.onnx.export()参数出错了:
我遇到相同错误的代码:
```python
torch.onnx.export(
        model, 
        torch.zeros(batch_size, img_channel, *img_size).shape,
        "./", 
        opset_version=12,
        verbose=False,
        input_names=['images'],
        output_names=['output'],
    )
```

修改后代码:

```python
torch.onnx.export(
        model, 
        torch.zeros(batch_size, img_channel, *img_size),
        "./", 
        opset_version=12,
        verbose=False,
        input_names=['images'],
        output_names=['output'],
    )
```

然后问题就解决了 🙄

**Comment by AllenTiTaiWang** [comment]
We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
