### ISSUE TITLE
Do  pytorch implemented losses   contain  Global loss (pairwise similarity) of Siamesenetworks?

### ISSUE THREAD

**Issue by swg209** [pytorch/pytorch#22793]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
