### ISSUE TITLE
How can i fix libtorch 'undefined reference' problem in qmake?   

### ISSUE THREAD

**Issue by mesut92** [pytorch/pytorch#22792]
### Please note that this issue tracker is not a help form and this issue will be closed.

 I use qmake to build but I  get some errors. 

Firstly, i got one errors;
libtorch\include\torch\csrc\jit\ir.h:1077: error: function 'torch::jit::Value* torch::jit::Graph::insertGetAttr(torch::jit::Value*, const string&)' definition is marked dllimport
   TORCH_API Value* insertGetAttr(Value* obj, const std::string& field)

Then i run project on debug, i got errors below (like 93 errors)

These are first 7 errors:
error: undefined reference to `caffe2::detail::TypeMetaData const* caffe2::TypeMeta::_typeMetaDataInstance<caffe2::detail::_Uninitialized>()'
undefined reference to `__imp__ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
undefined reference to `__imp__ZN3c106Device8validateEv'
undefined reference to `__imp__ZN5torch3jit4loadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN3c108optionalINS9_6DeviceEEERSt13unordered_mapIS6_S6_St4hashIS6_ESt8equal_toIS6_ESaISt4pairIS7_S6_EEE'
undefined reference to `__imp__ZN2at6native6tensorEN3c108ArrayRefIdEERKNS1_13TensorOptionsE'
undefined reference to `__imp__ZN3c1019UndefinedTensorImpl10_singletonE'
undefined reference to `__imp__ZN3c1019UndefinedTensorImpl10_singletonE'

I added libtorch to .pro file:

QMAKE_CXXFLAGS += -DGLIBCXX_USE_CXX11_ABI=0

INCLUDEPATH += "$$PWD\libtorch\include"
INCLUDEPATH += "$$PWD\libtorch\include\torch\csrc\api\include"

LIBS += -L$$PWD/libtorch/lib
LIBS += -ltorch -lc10 

Enviroment:
OS: windows10
I downloaded CPU version.

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soumith** [comment]
cc: @peterjc123

**Comment by peterjc123** [comment]
No, the libs are not available for GCC on Windows.

**Comment by mesut92** [comment]
Is there any way? How can i  add my torch project to QT?

**Comment by peterjc123** [comment]
Sorry, I'm not a QT guy. However, I've seen somebody playing with QT and LibTorch in this [post](https://github.com/pytorch/pytorch/issues/20326). Once MSVC is used, I believe there shouldn't be any big problem integrating the LibTorch code.
