### ISSUE TITLE
Port `addcdiv` operator from the TH code to Aten

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#22796]
`addcdiv` is the point-wise math operator so porting if from the TH code to Aten (and TensorIterator) expected to be easy. Such migration will help to clean up the code, simplify dispatch as well as provide immediate 2-3x operator performance gain.

Porting guide: https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide

Example PR with porting of the adaptive_avg_pool2d: https://github.com/pytorch/pytorch/pull/14714

How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator

**Comment by vishwakftw** [comment]
Also worth mentioning addcmul as well.

**Comment by VitalyFedyunin** [comment]
Kamino cloned this issue to [pytorch/pytorch](https://github.com/pytorch/pytorch/issues/22797)

**Comment by VitalyFedyunin** [comment]
Kamino cloned this issue to [pytorch/pytorch](https://github.com/pytorch/pytorch/issues/22799)

**Comment by VitalyFedyunin** [comment]
Kamino cloned this issue to [pytorch/pytorch](https://github.com/pytorch/pytorch/issues/22800)

**Comment by VitalyFedyunin** [comment]
Kamino cloned this issue to [pytorch/pytorch](https://github.com/pytorch/pytorch/issues/22801)

**Comment by VitalyFedyunin** [comment]
Kamino cloned this issue to [pytorch/pytorch](https://github.com/pytorch/pytorch/issues/22802)

**Comment by VitalyFedyunin** [comment]
Kamino cloned this issue to [pytorch/pytorch](https://github.com/pytorch/pytorch/issues/22803)

**Comment by VitalyFedyunin** [comment]
Kamino cloned this issue to [pytorch/pytorch](https://github.com/pytorch/pytorch/issues/22804)

**Comment by VitalyFedyunin** [comment]
Kamino cloned this issue to [pytorch/pytorch](https://github.com/pytorch/pytorch/issues/22805)

**Comment by VitalyFedyunin** [comment]
Kamino cloned this issue to [pytorch/pytorch](https://github.com/pytorch/pytorch/issues/22806)

**Comment by VitalyFedyunin** [comment]
Done in #23683
