### ISSUE TITLE
Port `sign` operator from the TH code to Aten

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#22806]
`sign` is the point-wise math operator so porting if from the TH code to Aten (and TensorIterator) expected to be easy. Such migration will help to clean up the code, simplify dispatch as well as provide immediate 2-3x operator performance gain.

Porting guide: https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide

Example PR with porting of the adaptive_avg_pool2d: https://github.com/pytorch/pytorch/pull/14714

How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator

**Comment by mfuntowicz** [comment]
Would it be ok for a first ATen PR ? If yes, I may want to have a look :)

**Comment by fmassa** [comment]
@mfuntowicz yes, this would be a good first PR!

There might be better examples on how to port. I don't have a single PR at hand, but here are a few extra pointers:
https://github.com/pytorch/pytorch/pull/19041 and https://github.com/pytorch/pytorch/pull/21115
(even though they don't port the GPU part, it should follow the same flow).

@VitalyFedyunin can you maybe get a more representative example PR for porting those unary ops?

**Comment by mfuntowicz** [comment]
Thanks @fmassa, I started working on this and CPU backend is available there (draft #22861)

I'll be looking at CUDA later today.

**Comment by VitalyFedyunin** [comment]
@fmassa I will make example PR (using different function ofc)
@mfuntowicz so far you are on the right path with PR

**Comment by VitalyFedyunin** [comment]
#24761 and  #24626
