### ISSUE TITLE
Error installing branch v0.2.0 from source 

### ISSUE THREAD

**Issue by chsasank** [pytorch/pytorch#2281]
I'm on ubuntu 16.04 with titan X. I am trying to install v0.2.0 branch from source.

I created new conda env `pytorch` and followed the instructions on Readme.md.

python setup.py install fails with error which look like this:
```
... /pytorch/torch/lib/THCUNN/generic/SpatialFullConvolution.cu(18): error: identifier "THNN_CudaHalfSpatialFullDilatedConvolution_updateOutput" is undefined

...

 ... /pytorch/torch/lib/THCUNN/generic/SpatialFullConvolution.cu(55): error: identifier "THNN_CudaHalfSpatialFullDilatedConvolution_accGradParameters" is undefined
```

I'm attaching complete log file: [log_file.txt](https://github.com/pytorch/pytorch/files/1196589/log_file.txt)

Sasank.

**Comment by CDLuminate** [comment]
Maybe you should clean your directory and try again.

Run `git clean -xdf` or `python3 setup.py clean` and try again?

**Comment by chsasank** [comment]
Wow, how did I miss this! 

Thanks a lot @CDLuminate !
