### ISSUE TITLE
Remove deprecated linear algebra wrappers

### ISSUE THREAD

**Issue by xuhdev** [pytorch/pytorch#22832]
## 🐛 Bug

A bunch of functions in `torch/functional.py` print the message

    :func:`yyy` is deprecated in favour of :func:`zzz` and will be removed in the next release.

All of them seem to be written before release 1.1.0. Now might be a good time to remove them.

cc @vishwakftw

**Comment by vishwakftw** [comment]
@zou3519 also mentioned this in Slack, I’ll send PRs for these this weekend.
