### ISSUE TITLE
Can't install pytorch torchvision with conda

### ISSUE THREAD

**Issue by KARIMSUNEEL** [pytorch/pytorch#22847]
Hi,

I am trying to install torchvision using Conda environment. but it got stuck after the below lines.

I have waited for quit some time but it  is not going further. Can someone help me in solving the below problem.

base) C:\>conda install -c pytorch torchvision
Collecting package metadata (current_repodata.json): done
Solving environment: |
Warning: 8 possible package resolutions (only showing differing packages):
  - anaconda::ca-certificates-2019.5.15-0, anaconda::certifi-2019.6.16-py37_0, anaconda::conda-4.7.5-py37_0
  - anaconda::ca-certificates-2019.5.15-0, anaconda::certifi-2019.6.16-py37_0, defaults::conda-4.7.5-py37_0
  - anaconda::certifi-2019.6.16-py37_0, anaconda::conda-4.7.5-py37_0, defaults::ca-certificates-2019.5.15-0
  - anaconda::certifi-2019.6.16-py37_0, defaults::ca-certificates-2019.5.15-0, defaults::conda-4.7.5-py37_0
  - anaconda::conda-4.7.5-py37_0, defaults::ca-certificates-2019.5.15-0, defaults::certifi-2019.6.16-py37_0
  - defaults::ca-certificates-2019.5.15-0, defaults::certifi-2019.6.16-py37_0, defaults::conda-4.7.5-py37_0
  - anaconda::ca-certificates-2019.5.15-0, anaconda::conda-4.7.5-py37_0, defaults::certifi-2019.6.16-py37_0
  - anaconda::ca-certificates-2019.5.15-0, defaults::certifi-2019.6.16-py37_0, defaults::conda-4.7.5-py37done

Thanks in advance.

Y K Suneel

**Comment by soumith** [comment]
this looks like a botched conda environment. I have no other suggestion than to try a fresh conda environment
