### ISSUE TITLE
Inconsistent behavior of tools.setup_helpers.cuda.CUDA_HOME and torch.utils.cpp_extension.CUDA_HOME

### ISSUE THREAD

**Issue by silent567** [pytorch/pytorch#22844]
## 🐛 Bug

`tools.setup_helpers.cuda.CUDA_HOME` checks two guesses: `CUDA_HOME` then `which(nvcc)`; while `torch.utils.cpp_extension.CUDA_HOME` checks three guesses: `CUDA_HOME` then `/usr/local/cuda` and at last `which(nvcc)`.

## To Reproduce

Multiple versions of CUDA are installed in a shared server. CUDA9 in `/usr/local/cuda-9.0` linked to `/usr/local/cuda`; CUDA10 in `/usr/local/cuda-10.0`; and a newer CUDA10 in `~/.local/cuda-10.0`. 

The environment variables including `PATH`, `CPATH`, `LD_LIBRARY_PATH` are all assigned to the newer CUDA10 i.e. `~/.local/cuda-10.0`. `CUDA_HOME` is not set.

While installing pytorch, it automatically learns to use the newer CUDA10 by calling `tools.setup_helpers.cuda.CUDA_HOME`, which calls `which(nvcc)`.

The bug showed up while installing [torch_scatter](https://github.com/rusty1s/pytorch_scatter). That project utilizes the `torch.utils.cpp_extension.CUDA_HOME` to identify the cuda path in setup.py, which then results in a different cuda path from the one utilized for installing pytorch. 

Typically, in the above server, here are the sample output:
```
$ python -c "from torch.utils.cpp_extension import CUDA_HOME; print(CUDA_HOME)"
/usr/local/cuda
$ cd pytorch && python -c "from tools.setup_helpers.cuda import CUDA_HOME; print(CUDA_HOME)"
/home/haotang/.local/cuda-10.0
```

## Expected behavior

Same output for the two functions.

## Environment
```
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 410.66
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.1.0
[pip] torch-cluster==1.4.2
[pip] torch-geometric==1.3.0
[pip] torch-scatter==1.3.1
[pip] torch-sparse==0.4.0
[pip] torch-spline-conv==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.3                      199
[conda] mkl-service               1.1.2            py37he904b0f_5
[conda] mkl_fft                   1.0.10           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torch-cluster             1.4.2                    pypi_0    pypi
[conda] torch-geometric           1.3.0                    pypi_0    pypi
[conda] torch-scatter             1.3.1                    pypi_0    pypi
[conda] torch-sparse              0.4.0                    pypi_0    pypi
[conda] torch-spline-conv         1.1.0                    pypi_0    pypi
[conda] torchvision               0.3.0                    pypi_0    pypi
```

**Comment by peterjc123** [comment]
I wonder how we can unify them together by eliminating the copies of the function? Any ideas? @ezyang

**Comment by ezyang** [comment]
cc @xuhdev; Hong's plan has been to subsume all of these copies with the cmake detection logic so we don't have this problem. But we should probably take the bandaid fix.

**Comment by silent567** [comment]
Resolved by pull request https://github.com/pytorch/pytorch/pull/22845
