### ISSUE TITLE
Zero gradients beyond a certain buffer size on CUDA

### ISSUE THREAD

**Issue by calincru** [pytorch/pytorch#22843]
## 🐛 Bug

There is an issue with how blocks/buffers are being allocated on CUDA. This leads to zeroed gradients in the example below for those matrices that are beyond the `65535`th entry. 

This only seems to affect the nightly build. 

## To Reproduce

In the example below the assert fails because the last entry is all zeros instead of the identity matrix.  Decrement `n` by 1 and it works as expected.

```python
import torch
n = (1 << 16) # - 1
x = torch.rand(n, 2, 2, device='cuda').requires_grad_()
a = x[:, [0], [0]]
b = x[:, [1], [1]]
s = (a + b).sum()
s.backward()
assert torch.allclose(x.grad, torch.eye(2, out=x.new(2, 2)))  # fails
```

It's probably related to the following which works on the nightly build for `n` up to `2^19 - 7` while the limit on the lastest release is `2^16`:

```python
n = (1 << 19) - 7 # - 1
x = torch.rand(n, 2, 2, device='cuda')
x = (x @ x.transpose(-2, -1)).add_(torch.eye(2, out=x.new(2, 2)))
y = x.detach().requires_grad_()
l = y.cholesky()  # <-- fails here
logdet = 2 * l.diagonal(dim1=1, dim2=2).log().sum()
logdet.backward()
assert torch.allclose(y.grad, y.inverse())
```

Note that here, other than the change in the limit, I get an error when the threshold is passed: `RuntimeError: CUDA error: invalid configuration argument`. (Which becomes clear after one pastes it in their favorite search engine.)  So I would expect something like this for the first code snippet too.

## Environment

Last nightly build with CUDA 10 and cuDNN 7.5.

**Comment by soumith** [comment]
seems like a grave issue. needs to be given the high-priority++ tag.

**Comment by vishwakftw** [comment]
Coincidentally, MAGMA’s potrf_batched routine fails for batches of 2^19 - 7 or larger. I’ve opened an issue on MAGMA’s forum about this too.

**Comment by calincru** [comment]
Could someone at least clarify whether the limit is supposed to be 2^16 or not in the first code snippet?  If that's the case, then I'll end up adapting my code anyway, so I might as well do it now. But if it's supposed to work, then I prefer to keep using larger batch sizes.

**Comment by colesbury** [comment]
@calincru It's supposed to work

**Comment by ezyang** [comment]
This is probably specific to advanced indexing, because this program is OK:

```
import torch
n = (1 << 16)
x = torch.rand(n, 2, 2, device='cuda', requires_grad=True)
a = x[:, 0, 0]
b = x[:, 1, 1]
s = (a + b).sum()
s.backward()
assert torch.allclose(x.grad, torch.eye(2, device='cuda'))
```

**Comment by colesbury** [comment]
Yes, in particular probably the specialization for "accum=True":

https://github.com/pytorch/pytorch/blob/2ee0f0bc3a8b81e554e9cf7eded598ac7ecf33be/aten/src/ATen/native/cuda/Indexing.cu#L30-L40

The `y` and `z` components of a grid of thread blocks have a maximum value of 65535.
(https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#features-and-technical-specifications)

cc @ngimel

**Comment by ezyang** [comment]
Simpler repro:

```
import torch

n = (1 << 16)
x = torch.rand(n, 1, device='cuda', requires_grad=True)
a = x[:, [0]]
a.sum().backward()
print(x.grad)
assert torch.allclose(x.grad, torch.ones(n, 1, device='cuda'))
```

CC'ing @ngimel since she worked on indexing recently.

**Comment by ezyang** [comment]
I've confirmed that reverting #20557 solves the problem.
