### ISSUE TITLE
cpp_export tutorial uses `std::shared_ptr<Module>`

### ISSUE THREAD

**Issue by LJXLJXLJX** [pytorch/pytorch#22855]
I have noticed that the shared_ptr of Module has been removed.
https://github.com/pytorch/pytorch/pull/21934

But your tutorial doesn't update and it won't work now.
https://pytorch.org/tutorials/advanced/cpp_export.html

I hope you can update it in time, thank you!

**Comment by NeilWangziyu** [comment]
yes, I thought the Jit Part's tutorial has out of date, many functions are changed recently. I wonder when will the next stable version released?

**Comment by LJXLJXLJX** [comment]
@NeilWangziyu Maybe. I found the inference of pytorch is extremly SLOW with CPU. I tested the same model, tensorflow 80ms, but pytorch 1.2s. I hope this can be fixed, it's abnormal.

**Comment by Krovatkin** [comment]
I'll update the tutorial. @LJXLJXLJX  please consider filing an issue, so we can investigate this.

**Comment by LJXLJXLJX** [comment]
> I'll update the tutorial. @LJXLJXLJX please consider filing an issue about your performance issue, so we can investigate this.

Yes, thank you! I will open another issue about performance these days.
