### ISSUE TITLE
Argmax is not deterministic

### ISSUE THREAD

**Issue by TommeyChang** [pytorch/pytorch#22853]
## 🐛 Bug
Applying torch.argmax to a list of same value leads to wrong result.

## To Reproduce

import torch
for i in range(-10, 10):
    test = torch.tensor([i] * 16)
    print(torch.argmax(test))
The outputs are tensor(15)

## Expected behavior
The outputs are tensor(0)

## Environment
 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: 1080Ti
 - Any other relevant information:

**Comment by SsnL** [comment]
There is no guarantee which max it returns.

**Comment by colesbury** [comment]
NumPy returns the first occurrence. It might be worth matching their behavior.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html

"In case of multiple occurrences of the maximum values, the indices corresponding to the first occurrence are returned."

**Comment by TommeyChang** [comment]
Although it makes sense in some extent, but I think this is not in line with general logic and may lead to some weired problems. @SsnL 
I support the opinion with @colesbury.

**Comment by taras-sereda** [comment]
well, on gpu it can return even random indexes. Pretty inconsistent behavior...

```
In [11]: a = torch.cat([torch.zeros([2]), torch.full([20], 1e-6)])                                                                                                

In [12]: a                                                                                                                                                         
Out[12]: 
tensor([0.0000e+00, 0.0000e+00, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
        1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
        1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
        1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06])

In [13]: a.argmax()                                                                                                                                                
Out[13]: tensor(21)

In [14]: a.cuda().argmax()                                                                                                                                         
Out[14]: tensor(16, device='cuda:0')
```

**Comment by soumith** [comment]
@taras-sereda it's not random, it's deterministic. it can pick any value that is the argmax, but the cuda implementation wont pick the first one.

**Comment by soumith** [comment]
@colesbury for numpy, that's easy, because it's CPU-only code. for GPU, you'd be eating a performance hit.

**Comment by taras-sereda** [comment]
@soumith well, anyway cpu and gpu implementations behave differently. cpu implementation returns **highest** index of max value instead of **lowest**, while argmax() has a well defined behavior in numpy.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html

**Comment by SamMuq** [comment]
I had the same problem on GPU. The torch.max function returns indices and behaves differently to torch.argmax.

Using argmax:  tensor([[3, 3, 3, 3]], device='cuda:0')

Using torch.max: values=indices=tensor([[0, 0, 0, 0]], device='cuda:0')

torch.max appears to behave in a more predictable way.

**Comment by leockl** [comment]
Hey guys, looks like this issue has been going on for ages. Is this ever going to get fixed?

**Comment by colesbury** [comment]
@kshitij12345 just put up a PR so it might? Won't be in time for 1.6 though.

**Comment by leockl** [comment]
Ok many thanks for this. That sounds good as long as it won't be another couple of months :)
