### ISSUE TITLE
What is the abbreviation of CI?

### ISSUE THREAD

**Issue by 137996047** [pytorch/pytorch#22858]
## ❓ Questions and Help
I ma sorry, I don't understand the sentence: ` On CI, we test with BUILD_SHARED_LIBS=OFF.`
What is the CI ?
What is the BUILD_SHARED_LIBS?
Could someone explain it for me?
Thank you very much!
![image](https://user-images.githubusercontent.com/30762967/61199981-868abd00-a712-11e9-9fc3-fc3d3e25446d.png)

**Comment by t-vi** [comment]
Continuous Integration.
