### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator Im2Col

### ISSUE THREAD

**Issue by Aaron4Fun** [pytorch/pytorch#22862]
When I used torch.onnx to transform my PyTorch model, I met an error: RuntimeError: ONNX export failed: Couldn't export Python operator Im2Col. 
![image](https://user-images.githubusercontent.com/42711020/61223694-1893c500-a715-11e9-90a2-50aa310f29b4.png)
In my model, I used F.unfold() function to connect CNN with BiLSTM. Im2Col is a function inside F.unfold. But I found that torch.onnx has supported the unfold function, are they different? 
![image](https://user-images.githubusercontent.com/42711020/61223851-64df0500-a715-11e9-9338-ecdb56d3d0e2.png)
What should I do next? Has anyone also met this problem?  Any suggestion will be appreciated.

**Comment by saurav4098** [comment]
@Aaron4Fun  Did you resolve im2col operator. I am stuck with the same problem .

**Comment by garymm** [comment]
On PyTorch 1.10, this works on opset_version >= 11:

```python
import torch
from torch import nn
import torch.nn.functional as F

class M(nn.Module):
  def forward(self, x):
    return F.unfold(x, kernel_size=(2, 3))

input = torch.randn(2, 5, 3, 4)
torch.onnx.export(M(), input, "/dev/null", verbose=True, opset_version=11)
```

@Aaron4Fun can you please try again?

**Comment by thiagocrepaldi** [comment]
@garymm Given we are adding [`Col2Im` to ONNX spec](https://github.com/onnx/onnx/pull/3948), do you think it makes sense to also add `Im2Col`

**Comment by garymm** [comment]
@thiagocrepaldi we can export `unfold` already so I don't see a use case. Unless there's something that we can't export otherwise.

Closing due to lack of response from reporter.
