### ISSUE TITLE
CuDNN backend version seems incorrect

### ISSUE THREAD

**Issue by chouzhupk** [pytorch/pytorch#2286]
Prior to installation, I have Cuda 8.0 and CuDNN 5.1 installed already. In order to be compatible, I install pytorch with 
`conda install pytorch cuda80 -c soumith`
and then remove the redundant cuda80 from conda
It works normally while 
`torch.backends.cudnn.version()` shows '6021'. I double check my **LD_LIBRARY_PATH** and only  **libcudnn.so.5.1.10** found

**Comment by chouzhupk** [comment]
Just realize that Pytorch include a CuDNN 6.0.21 in its own directory, closed.

**Comment by Dxye** [comment]
@chouzhupk  hi, do you know how can i change the CuDNN version which was included by Pytorch? I have some other code need CuDNN version higher than 7.1.4, but Pytorch seems force the CuDNN to 7.0.5, even though I already installed 7.1.4 manually.

**Comment by chouzhupk** [comment]
@Dxye I'm assuming it's installed from conda, which includeds a cuda subfolder in the package directory, that's why pytorch is always using this built-in version (7.0.5 in your case). You may remove the cuda folder and pytorch should be able to reference system settings (7.1.4).
