### ISSUE TITLE
Build Fails for Raspberry Pi 4 B: libcaffe2.so: undefined reference to `__atomic_xxx_8'

### ISSUE THREAD

**Issue by BeibinLi** [pytorch/pytorch#22898]
Raspberry Pi 4 Model B (4 GB RAM version).
Python 3.7.3
Architecture: armv7l

Settings:
NO_MLKDNN=1
NO_CUDA=1
NO_QNNPACK=1
NO_NNPACK=1
NO_DISTRIBUTED=1
python3 setup.py build

========================================
The last few lines for the results:

[ 71%] Building CXX object caffe2/CMakeFiles/caffe2.dir/transforms/pattern_net_transform.cc.o
[ 72%] Building CXX object caffe2/CMakeFiles/caffe2.dir/transforms/single_op_transform.cc.o
[ 72%] Linking CXX shared library ../lib/libcaffe2.so
[ 72%] Built target caffe2
Scanning dependencies of target caffe2_pybind11_state
Scanning dependencies of target pattern_net_transform_test
[ 72%] Building CXX object caffe2/CMakeFiles/pattern_net_transform_test.dir/transforms/pattern_net_transform_test.cc.o
[ 72%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o
[ 72%] Linking CXX executable ../bin/pattern_net_transform_test
/usr/bin/ld: /home/pi/pytorch/build/lib/libcaffe2.so: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: /home/pi/pytorch/build/lib/libcaffe2.so: undefined reference to `__atomic_load_8'
/usr/bin/ld: /home/pi/pytorch/build/lib/libcaffe2.so: undefined reference to `__atomic_exchange_8'
/usr/bin/ld: /home/pi/pytorch/build/lib/libcaffe2.so: undefined reference to `__atomic_fetch_sub_8'
/usr/bin/ld: /home/pi/pytorch/build/lib/libcaffe2.so: undefined reference to `__atomic_compare_exchange_8'
collect2: error: ld returned 1 exit status
make[2]: *** [caffe2/CMakeFiles/pattern_net_transform_test.dir/build.make:88: bin/pattern_net_transform_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:2058: caffe2/CMakeFiles/pattern_net_transform_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 72%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_dlpack.cc.o
[ 72%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_nomni.cc.o
[ 72%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_registry.cc.o
[ 72%] Linking CXX shared module python/caffe2_pybind11_state.cpython-37m-arm-linux-gnueabihf.so
[ 72%] Built target caffe2_pybind11_state
make: *** [Makefile:141: all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh caffe2'
pi@raspberrypi:~/pytorch $

**Comment by BeibinLi** [comment]
I spent a whole day and resolved this issue by the following steps:
1. sudo apt-get install libatomics-ops-dev
2. Change CMAKE_CXX_FLAGS variable in CMakeLists.txt file (in the main directory). i.e. line 216, from "-O2 -fPIC" to "-O2 -fPIC **-latmoic**"

I also uploaded the torch 1.0.0 .whl file if anyone needs it: https://drive.google.com/file/d/1D3A5YSWiY-EnRWzWbzSqvj4YdY90wuXq/view?usp=sharing

**Comment by JiahanLiu** [comment]
Here's a 1.3 Wheel for armv7l: 

https://github.com/JiahanLiu/JiahanLiuThesis/blob/master/RaspberryPi4/torch-1.3.0a0%2Bde394b6-cp37-cp37m-linux_armv7l.whl

**Comment by SArham** [comment]
Thanks @JiahanLiu 

For downloading with wget. Changed blob to raw in the url.

https://github.com/JiahanLiu/JiahanLiuThesis/raw/master/RaspberryPi4/torch-1.3.0a0%2Bde394b6-cp37-cp37m-linux_armv7l.whl

@coriolan-cs Via your terminal, go to the pytorch folder. 
copy and paste this command 
`sed -i '/set(CMAKE_EXPORT_COMPILE_COMMANDS ON)/a set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -latomic")' CMakeLists.txt
`
Additionally, try `LD_PRELOAD=</usr/lib/arm-linux-*/libatomic.so.x.y> python setup.py build`

This gives priority to this specific library version for building. 

This same problem happens with mxnet on the raspberry pi too.

**Comment by jrcichra** [comment]
> I spent a whole day and resolved this issue by the following steps:
> 
> 1. sudo apt-get install libatomics-ops-dev
> 2. Change CMAKE_CXX_FLAGS variable in CMakeLists.txt file (in the main directory). i.e. add line ` set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -latomic")`
> 
> I also uploaded the torch 1.0.0 .whl file if anyone needs it: https://drive.google.com/file/d/1D3A5YSWiY-EnRWzWbzSqvj4YdY90wuXq/view?usp=sharing

For me it was libatomic-ops-dev on a raspberry pi 4
