### ISSUE TITLE
flip a Tensor

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#229]
Sometimes it's convenient to do stuff like `y = x[::-1]` to inverse the order of the elements of a tensor, even on another axis like: `y = x[:, ::-1]`
Would it be possible to add this feature to pytorch?

**Comment by rtqichen** [comment]
To add another use case for strides other than 1 (not just -1): accessing diagonals of a `n by n` matrix `X` would be very easy with `X[::n+1]`. The current torch.diag function returns a copy of the diagonal.

**Comment by fmassa** [comment]
@rtqichen I believe we can pass a `stride` parameter in the constructor of tensor initalization, meaning that from a storage, you can create a tensor with the sizes ans strides that you want (as long as they are positive). I just think that the slicing operator in pytorch doesn't allow that, but I'd need to double check that. I think it's something like
```python
torch.Tensor(storage, sizes, strides)
```

**Comment by rtqichen** [comment]
@fmassa Thanks, but I think that's also not implemented yet. #215

**Comment by fmassa** [comment]
I see, but as mentioned in the issue you pointed out, it is possible to use `set_` for that.
Anyway, I agree that allowing strides in slicing is going to be handy

**Comment by apaszke** [comment]
Non-negative strides should be easy to add. I'll do that today.

**Comment by soumith** [comment]
non-negative strides are now supported in master

**Comment by aosokin** [comment]
Without negative strides, is there any relatively efficient way to reverse the 1-dimensional tensor (sequence)?

**Comment by fmassa** [comment]
@aosokin the most efficient way at the moment is to use `index_select` in the tensor, which will make a copy of it.
```python
inv_idx = torch.arange(tensor.size(0)-1, -1, -1).long()
# or equivalently torch.range(tensor.size(0)-1, 0, -1).long()
inv_tensor = tensor.index_select(0, inv_idx)
# or equivalently
inv_tensor = tensor[inv_idx]
```

**Comment by aosokin** [comment]
@fmassa Thanks!

**Comment by authman** [comment]
Still holding out hope.

**Comment by ruotianluo** [comment]
It seems it's not still supported in 0.2?

**Comment by soumith** [comment]
it is not :( sorry.

**Comment by antigol** [comment]
How to inverse a cuda tensor ?
The method given by **fmassa** works well on cpu but not on cuda (#2412)

**Comment by dmarnerides** [comment]
Is there a better (more efficient) way of flipping an arbitrary dimension than this?

```python
def flip(x, dim):
    dim = x.dim() + dim if dim < 0 else dim
    return x[tuple(slice(None, None) if i != dim
             else torch.arange(x.size(i)-1, -1, -1).long()
             for i in range(x.dim()))]
```

Code to test it with:

```python
a = torch.Tensor([range(1, 25)]).view(1, 2, 3, 4)
print(a)
print(flip(a, 0)) # Or -4
print(flip(a, 1)) # Or -3
print(flip(a, 2)) # Or -2
print(flip(a, 3)) # Or -1
```

**Comment by wassname** [comment]
Here's @dmarnerides code but with cuda support

```py
# https://github.com/pytorch/pytorch/issues/229
def flip(x, dim):
    dim = x.dim() + dim if dim < 0 else dim
    inds = tuple(slice(None, None) if i != dim
             else x.new(torch.arange(x.size(i)-1, -1, -1).tolist()).long()
             for i in range(x.dim()))
    return x[inds]

# Code to test it with cpu
a = torch.Tensor([range(1, 25)]).view(1, 2, 3, 4)
print(a)
print(flip(a, 0)) # Or -4
print(flip(a, 1)) # Or -3
print(flip(a, 2)) # Or -2
print(flip(a, 3)) # Or -1

# Code to test it with cuda
a = torch.Tensor([range(1, 25)]).view(1, 2, 3, 4).cuda()
print(a)
print(flip(a, 0)) # Or -4
print(flip(a, 1)) # Or -3
print(flip(a, 2)) # Or -2
print(flip(a, 3)) # Or -1
```

**Comment by Evpok** [comment]
The solution could come from https://github.com/pytorch/pytorch/pull/3750, though negative strides are not implemented atm.

**Comment by sytrus-in-github** [comment]
To make it work also with `torch.autograd.Variable`which does not have `new` attribute, I had to change the code from @dmarnerides  and @wassname as follows:

```
# https://github.com/pytorch/pytorch/issues/229
import torch
from torch.autograd import Variable
def flip(x, dim):
    dim = x.dim() + dim if dim < 0 else dim
    inds = tuple(slice(None) if i != dim
             else getattr(torch.arange(x.size(i)-1, -1, -1), 
                          ('cpu','cuda')[x.is_cuda])().long()
             for i in range(x.dim()))
    return x[inds]

# Code to test it with cuda Variable
a = Variable(torch.Tensor([range(1, 25)]).view(1, 2, 3, 4).cuda())
print(a)
print(flip(a, 0)) # Or -4
print(flip(a, 1)) # Or -3
print(flip(a, 2)) # Or -2
print(flip(a, 3)) # Or -1
```
It would be really nice to have the negative strides though.

**Comment by Alok** [comment]
Any updates for this?

**Comment by MaximArtemev** [comment]
Still waiting :(

**Comment by ivan-bilan** [comment]
@sytrus-in-github thank you for the flip function. How would I have to adapt it to get `a[..., ::-1, :]` for the matrix `a[batch_size, x_size, y_size]`. I would need to flip x and y, and leave the batch dimension untouched.

**Comment by sytrus-in-github** [comment]
@ivan-bilan does [this](https://discuss.pytorch.org/t/optimizing-diagonal-stripe-code/17777/17?u=sytrus-pytorch) answer your question?

**Comment by wangg12** [comment]
Any update for this?

**Comment by Oktai15** [comment]
@soumith torch.flip change the order of dims in tensor, but doesn't change the order in concrete axis like torch.tensor([1,2,3]) -> torch.tensor([3,2,1]). Why did you close this issue?

**Comment by willprice** [comment]
```
>>> import torch
>>> xs = torch.rand(5)
>>> xs
tensor([0.1820, 0.4174, 0.6118, 0.2575, 0.5187])
>>> torch.flip(xs, (0,))
tensor([0.5187, 0.2575, 0.6118, 0.4174, 0.1820])
```
What is it that you expect flip to do? Flip reverses the order of elements along a dimension. Do you want to reverse the order of dimensions, e.g. THWC -> CWHT ?

**Comment by dmarnerides** [comment]
@Oktai15 I think the function that changes the order of the dimensions is [torch.permute](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.permute) and not [torch.flip](https://pytorch.org/docs/stable/torch.html?highlight=flip#torch.flip).

**Comment by Oktai15** [comment]
@dmarnerides @willprice yes, you are right, sorry, misunderstanding.

**Comment by drscotthawley** [comment]
I know this is closed, but I'm finding torch.flip() to be a very compute-intensive operation -- profiling my code shows that 30% of the computing ops are being used on flip().  

@soumith Is this operation actually copying data?  If so, would it be more efficient to use a view?

Related: np.flip() claims that it's producing a view, and yet it runs at least 5 times slower than just using negative step slicing (e.g. "a[::-1]").  cf. https://stackoverflow.com/questions/6771428/most-efficient-way-to-reverse-a-numpy-array

I tried using negative step slicing but I get the error

> ValueError: negative step not yet supported

@ezyang Any update on the negative stride support?

Thanks!

**Comment by soumith** [comment]
torch.flip() is copying data, as we dont have negative stride support.
I think it's unlikely that we'll ever get to adding negative strides

**Comment by bsugerman** [comment]
I've been timing a number of options for flipping a tensor and so far, the fastest on my GPU has been either explicit selection or grid_sample. Say I have a tensor with just 2 indices at the end and I want to invert the order (like swapping x,y) then

     in = th.arange(5*4*2).view(5,4,2)
     reverse_index = th.tensor([1,0],device='cuda:0')
     out=in[..., reverse_index] 

is the fastest. Using `grid_sample` to perform a mirror-image affine transform also works but is 10-20% slower. :-(

**Comment by hellojialee** [comment]
@bsugerman What if we use python integer indexing, let's say `in[;;;, [1, 0]`

**Comment by myhakureimu** [comment]
maybe get x[::-1] :D

**Comment by Hadar933** [comment]
PS - there is also torch.fliplr(tensor). For example - taking `t = torch.arange(12).view(2,3,4)` and then `torch.fliplr(t)` is the equivalent of `t[:,::-1,:]`, if negative indexing was possible.

**Comment by Weijiang-Xiong** [comment]
another vote for this feature from 2024
