### ISSUE TITLE
[caffe2] Caffe2 building fail

### ISSUE THREAD

**Issue by vichgy** [pytorch/pytorch#22952]
##

## To Reproduce

1.edit ‘\scripts\build_windows.bat’ and set BUILD_PYTHON to ON
2.run the Developer Command Prompt for VS 2017, browse to the repo’s \scripts folder and execute:     build_windows.bat
1.

CMAKE_GENERATOR=Visual Studio 15 2017
CMAKE_BUILD_TYPE=Release
Traceback (most recent call last):
  File "tools\build_libtorch.py", line 14, in <module>
    from tools.build_pytorch_libs import build_caffe2
ModuleNotFoundError: No module named 'tools.build_pytorch_libs'
"Caffe2 building failed"

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Home
GCC version: (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] Could not collect

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): 
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by peterjc123** [comment]
Do you have `tools/build_pytorch_libs.py` under the PyTorch repo you cloned? I have Python3.6 too, but I cannot reproduce this problem.

**Comment by vichgy** [comment]
Yes, I can find the tools/build_pytorch_libs.py under the PyTorch repo.

**Comment by Turkishvein** [comment]
How do you resolve it? I use Python 2.7
