### ISSUE TITLE
Export Upsample op to ONNX's Resize op

### ISSUE THREAD

**Issue by Aeroxander** [pytorch/pytorch#22959]
## 🚀 Feature

When exporting to an ONNX model, instead of converting the Upsample op to ONNX [Upsample](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Upsample) op, use the ONNX [Resize](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize) op instead.
## Motivation

ONNX is deprecating the Upsample op and eventually PyTorch has to deal with that in order to keep being compatible with ONNX in the future.

## Pitch

PyTorch can keep the Upsample op, but it just needs to change to ONNX's Resize when exporting.

## Alternatives

If the nn.functional.interpolate function can be mapped to Resize that would be great too, right now it just converts to ONNX's Upsample.

**Comment by fmassa** [comment]
cc @houseroad @bddppq

**Comment by houseroad** [comment]
Reize op was introduced in opset 10, and we are able to correctly export Resize op already, see https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset10.py#L132.

For opset 9, it's right to export the ops as Upsample. If you want to change the opset version, there is a parameter to control in torch.onnx.export: https://github.com/pytorch/pytorch/blob/master/torch/onnx/utils.py#L107

**Comment by fucker007** [comment]
> Reize op was introduced in opset 10, and we are able to correctly export Resize op already, see https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset10.py#L132.
> 
> For opset 9, it's right to export the ops as Upsample. If you want to change the opset version, there is a parameter to control in torch.onnx.export: https://github.com/pytorch/pytorch/blob/master/torch/onnx/utils.py#L107

I export pytorch model to onnx model ,  however ,I find pytorch's Upsample Module is different from onnnx's Upsample.  that's  shocking me. the opset is 9, interpolate is bilinear ;  then I set  model='nearest'. they are the same, so, is bilinear not supported with PyTorch to onnx with opset 9.
