### ISSUE TITLE
libtorch performance seems strange to me

### ISSUE THREAD

**Issue by songziqin** [pytorch/pytorch#22968]
in my training code: the code include 3 parts :
-  part one :   request params from ps, that is io operation and some simple cpu operation
-  part two:    do forward and backward compute that is heavy cpu operation
-  part three:  just get the grad and upload the param to ps that is heavy io operation

```
void train( std::shared_ptr<Train_Variable_Data>  train_data,WideAndDeepNetWork* wideAndDeepNetWork){
   /**
    1. some operation make the data can feed into the model，and request params from ps
  **/

  2.

    torch::Tensor prediction = wideAndDeepNetWork->forward(user_vector_tensor, forwardArgs);
    std::vector<float> pred;
    get_grad(prediction, pred);
    std::cout << "auc:" << auc(train_data->labels, pred) << "\n";
    auto target = get_tensor(train_data->labels);
    auto loss = torch::nll_loss(prediction, target);
    std::cout << "loss:";
    std::cout << loss << std::endl;
    loss.backward();

3.

   /***  update params to ps
***/
}
```
 and the code is multi-threading. and I set the training thread  num is 10 , that is 10 threads run method train. and I also new 10 WideAndDeepNetWork model object, that is one model for one thread and I run
the program I  find the qps is about 10 batchs per second and the cpu load is about 50% and about cpu core num is 40,that is 20 cores are not used,and cpu is not very busy. and I want to improve the cpu load , I   set training thread  num 15 and the cpu load is not improve at all.

I want to know if  the bottleneck is part 1 and part 3 that is io , so  I just skip 2 that is not do forward and backward ,and  the qps can reach 28 batchs per second, and is so fast.  so I want to know why. can you give me some suggestion to improve the qps.

**Comment by fmassa** [comment]
You might want to set `OMP_NUM_THREADS=1` before running your program if it is internally using multiple threads.

Also, we use GitHub to track bugs and feature requests. Questions are better suited to the discussion forums https://discuss.pytorch.org
