### ISSUE TITLE
tensor.to(device) 's time is unstable.

### ISSUE THREAD

**Issue by qinb** [pytorch/pytorch#22967]
## ❓ Questions and Help

i run the following code in libtorch-1.1.0:
```
auto img_tensor =  torch::from_blob(img_float.data, torch::IntList(dims), options);
img_tensor = img_tensor.transpose(3, 2).transpose(2, 1);
gettimeofday(&end_prep1,` NULL);
std::vector<torch::jit::IValue> inputs;
img_tensor = img_tensor.to(at::kCUDA);
gettimeofday(&end_prep, NULL);
cout << "prep_2: " << (1000000*(end_prep.tv_sec-end_prep1.tv_sec)+end_prep.tv_usec-end_prep1.tv_usec)/1000.0 << endl;
```

i loop the code serval times in a image,  the time(ms) is:
```
prep_2: 6.994
prep_2: 4.394
prep_2: 13.675
prep_2: 9.993
prep_2: 5.94
prep_2: 14.433
prep_2: 13.907
prep_2: 7.145
prep_2: 14.269
prep_2: 5.551
prep_2: 11.109
prep_2: 25.72
prep_2: 14.551
prep_2: 15.384
prep_2: 14.321
prep_2: 14.392
prep_2: 11.469
prep_2: 14.015
prep_2: 8.367
prep_2: 17.946
prep_2: 14.445
prep_2: 7.291
prep_2: 14.562
prep_2: 14.01
```
because i only test imge_tensor.to(at::kCUDA), so feeling time of the function is unstable.
i 'm very appreciated for your help.

**Comment by fmassa** [comment]
I've tried the following snippet and I got the following results:
```python
In [2]: a = torch.rand(400, 800, 3)

In [8]: %timeit a.permute(2, 0, 1).cuda()
753 µs ± 5.31 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

which seems to indicate that, for those image sizes, the variance is pretty low.

Those numbers might depend on a number of factors, including the utilization of the GPU (maybe there were other concurrent threads running on the same GPU / machine?).

Without a self-contained minimum working example illustrating the problem, there is not much more we can do.

If you think this is a problem for you, please re-open a new issue with a full snippet that reproduces this variability.
