### ISSUE TITLE
[jit] Serialization format improvements 

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#22979]
This is a placeholder issue for serialization format improvements we want to get in before the 1.2 branch cut.

We want to enforce a clean separation between code and data. Modules and classes will get defined in `libs/`. During import, all code should be loaded first, and then any data will get unpickled and the actual module objects will get initialized.

**Comment by driazati** [comment]
What's the fate of the `model.json` and associated protos? We can encode all types on a class as inline type annotations and the module hierarchy is defined by the code, so we can probably delete it.

**Comment by suo** [comment]
Okay, we have decided to push this until after the release. Closing for now.
