### ISSUE TITLE
Substraction returns wrong result for bool tensors

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#22975]
**Repro:**
`torch.ones(5, dtype=torch.bool) - torch.ones(5, dtype=torch.bool)`

**Expected Result:**
`tensor([False, False, False, False, False])`

**Actual Result:**
`tensor([True, True, True, True, True])`

**Comment by colesbury** [comment]
Note that NumPy doesn't allow subtraction for bool:

```
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

I'm not sure we should allow it either.

**Comment by izdeby** [comment]
I agree with @colesbury, i think we should follow the numpy behavior. 
I've checked a bunch of related ops and looks like we have some differences. 
```
numpyA            :  [ True False]                                                                                          
1 - numpyA        :  [0 1]                                                                                                 
numpyA - 1        :  [ 0 -1]
~numpyA           :  [False  True]
numpyA - (~numpyA): ERROR                                                                                                   
numpyA ^ (~numpyA):  [ True  True]                                                                                          

torchA     :  tensor([ True, False])
1 - torchA :  tensor([True, True])
torchA - 1 :  tensor([True, True])
~torchA    :  tensor([False,  True])
torchA - (~torchA):  tensor([True, True])
torchA ^ (~torchA):  tensor([True, True])


sum(torchA) :  tensor(True)
torchA.sum() :  tensor(1)
```

**Comment by izdeby** [comment]
`>>> torch.ones(5, dtype=torch.bool) ^ torch.ones(5, dtype=torch.bool)`
tensor([False, False, False, False, False])

 `>>> torch.ones(5, dtype=torch.bool) - torch.ones(5, dtype=torch.bool)`
RuntimeError: Subtraction, the `-` operator, with two bool tensors is not supported. Use the `^` or `logical_xor()` operator instead.

PyTorch v.1.2

**Comment by gchanan** [comment]
I don't think that's v1.2 -- we didn't get the logical operators in AFAIR.
