### ISSUE TITLE
libtorch can work with CPU normally but there is an error when working with GPU

### ISSUE THREAD

**Issue by zhangpengju0316** [pytorch/pytorch#23009]
## 🐛 Bug
I compile libtorch by source on ubuntu18.04, I don't see any error while compiling it. when I use libtorch with CPU in my own project, it can output correct results. But when I use `module->to(device); `and `data = data.to(device); `to put module and data in GPU, it occurs an error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  ../torch/csrc/jit/fuser/cuda/fused_kernel.cpp:196: NVRTC_ERROR unknown
```
then I recompile the libtorch in Debug mode, I realize that this error occur in this line:
`auto output = module->forward(data).toTensor();`
and the error message is:
![screenshot](https://user-images.githubusercontent.com/20679750/61427620-6d238400-a951-11e9-891e-a6329809e376.png)

## Environment
 - OS (e.g., Linux):ubuntu18.04
 - Build libtorch command I used:
```
git submodule update --init --recursive
mkdir build
cd build
python ../tools/build_libtorch.py
```
 - CUDA/cuDNN version:10.0/7.5
 - GPU : 2080ti
How can I fix it, can anybody help me? 
thanks very much!

**Comment by suo** [comment]
Can you provide a script to reproduce the issue? That way we can investigate.

**Comment by zhangpengju0316** [comment]
> Can you provide a script to reproduce the issue? That way we can investigate.

@sue, Thanks for your reply, maybe I have found the problem is! when I use **clion** to run my project, it can't work with GPU, but when I rebuild and run my project in terminal, it works!!! So maybe this is a bug of **clion** ?!
