### ISSUE TITLE
Abnormal performance with C++ API on win32 

### ISSUE THREAD

**Issue by LJXLJXLJX** [pytorch/pytorch#23004]
OS: Windows 10
torch version: 1.1.0
CPU ONLY (I don't have GPU)

I have define the same model both with torch and tf.
And I test them with the same input.

>  PS D:\OneDrive\share\crnn> python .\tf_test.py
> D:\Anaconda3x64\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> 2019-07-18 09:20:36.582544: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> (25, 1, 5990)
> time: 0.03291153907775879s
> PS D:\OneDrive\share\crnn> python .\torch_test.py
> torch.Size([25, 1, 5990])
> time: 0.04887127876281738s
> PS D:\OneDrive\share\crnn>

The performance is OK.

Then I use torch.jit.trace and save the model , and test it on C++ api (I build it from source my self release 32bit)
```C++
#include <torch/script.h> // One-stop header.
#include <iostream>
#include <memory>
#include <chrono>

using namespace std;

int main(int argc, const char* argv[]) {

	// Deserialize the ScriptModule from a file using torch::jit::load().
	torch::jit::script::Module model = torch::jit::load("./model/crnn.pt");

	std::vector<torch::jit::IValue> inputs;
	//inputs.push_back(torch::ones({ 1, 3, 224, 224 }));
	inputs.push_back(torch::ones({ 1, 3, 32, 120 }));

	auto start = chrono::high_resolution_clock::now();

	// Execute the model and turn its output into a tensor.
	at::Tensor output = model.forward(inputs).toTensor();

	auto end = chrono::high_resolution_clock::now();

	cout << chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << endl;

	//std::cout << output.argmax(2) << '\n';


	std::cout << "ok\n";
	system("pause");
}
```
The output is 

> 1197
> ok

Here is my test script, libs, dlls.
https://1drv.ms/f/s!AsUq39SrlQ1g5He0o1Ml4_xgPbEk
(Please @ me if it is invalid)

By the way, my python API of torch was also really slow like C++ API(1000ms+) previously. 
But I found there are 1.0.0 and 1.1.0 version of torch both exist in my PC. Then I uninstall them and pip install the newest version torch and numpy, it become normal (about 50ms) now.
Then I build the C++ API again, but it is still SLOW...

@Krovatkin 
I hope this could be fixed, thank you!

**Comment by LJXLJXLJX** [comment]
I build the x64 Release, it is slow as well.

**Comment by LJXLJXLJX** [comment]
I tried the official libtorch https://pytorch.org/get-started/locally/
it's ok. But why it is so slow if I build it myself?

**Comment by soumith** [comment]
I'm pretty sure the reason is that when you are building it yourself you are not linking against MKL and MKL-DNN.

cc: @peterjc123 let me know if I can close the issue

**Comment by LJXLJXLJX** [comment]
@soumith I use the cmake with default config, should I build link MKL myself? I think MKL is the submodule.

**Comment by soumith** [comment]
>should I build and link MKL myself? I think MKL is the submodule.

Yes you should. We dont ship MKL as submodule

**Comment by LJXLJXLJX** [comment]
> > should I build and link MKL myself? I think MKL is the submodule.
> 
> Yes you should. We dont ship MKL as submodule


MKL support 64bit only, so I use openBLAS instead, it's slow as well.

**Comment by LIANGXINKAI** [comment]
> > > should I build and link MKL myself? I think MKL is the submodule.
> > 
> > 
> > Yes you should. We dont ship MKL as submodule
> 
> MKL support 64bit only, so I use openBLAS instead, it's slow as well.

Can u share the experience how to settle the problem?

**Comment by LJXLJXLJX** [comment]
@LIANGXINKAI  I have not solved this problem.
