### ISSUE TITLE
Wrong input to Categorical makes Python quit unexpectedly

### ISSUE THREAD

**Issue by czxttkl** [pytorch/pytorch#23002]
I pass a zero tensor to Categorical, which I expect torch should throw me some exception. Instead, Python quits unexpectedly

```
(base) czxttkl-mbp:Horizon czxttkl$ python3
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 00:48:40) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.1.0.post2'
>>> from torch.distributions.categorical import Categorical
>>> Categorical(torch.tensor([0]))
Floating point exception: 8

# Python completely quits
```

**Comment by czxttkl** [comment]
![Screen Shot 2019-07-17 at 3 57 28 PM](https://user-images.githubusercontent.com/3657457/61417473-0ef09580-a8ac-11e9-81ce-ac8dd3c74a70.png)

**Comment by soumith** [comment]
this is expected, division by zero on integers generates a Hardware FPE.

I think you meant to do `Categorical(torch.tensor([0.0]))`
