### ISSUE TITLE
BN weight is exactly a same value when use mp+DistributedDataParallel

### ISSUE THREAD

**Issue by 644517236** [pytorch/pytorch#23014]
### But when I use torch.multiprocessing (mp.spawn )  and torch.nn.parallel.DistributedDataParallel for 4 gpus(single node), it's wired that all BN weight in a layer is the same value.

I use pytorch1.2.0, ubuntu16,cuda10.

I use multiprocessing and DistributedDataParallel in my code like https://github.com/pytorch/examples/blob/master/imagenet/main.py.

Someone can help me??

**Comment by soumith** [comment]
follow our issue template and give more details.
Our issues follow a template so that we can understand and reproduce your issue better: https://github.com/pytorch/pytorch/issues/new/choose
