### ISSUE TITLE
error LNK2001 while executing PointRCNN

### ISSUE THREAD

**Issue by candisjesus** [pytorch/pytorch#23013]
I AM trying to execute buid_and_install.sh from github https://github.com/sshaoshuai/PointRCNN on windows10, pytorch 1.1, gcc 8.1.0, VS2017
the second task, iou3d.
I met problem of unresolved external symbol,  "public: long * __cdecl at::Tensor::data<long>(void)const "
ALL THESE libs have been found, cudart.lib c10.lib c10_cuda.lib caffe2.lib torch.lib torch_python.lib caffe2_gpu.lib _C.lib, but I think I DO miss one lib, according to the problem.
is it possible that the author use pytorch 1.0?
and I have read quite a lot issue with error LNK2001, BUT no idea how to solve mine
plz, help...

**Comment by peterjc123** [comment]
I guess you'll need to change that `long` to `int64_t` on Windows, because for Linux x64 desktop/server, `long` == `int64_t` but for Windows, `long` == `int32_t`.
