### ISSUE TITLE
Out of memory when extract features from pictures, only on ubuntu.

### ISSUE THREAD

**Issue by xwzy** [pytorch/pytorch#2302]
I use res152-net to extract features from pictures, but with an 8G memory ubuntu PC, can only extract less than 30 pics and my PC will crash with 8G + 8G(swap) memory full.

Is there any way to free some memory when inference?

Note: This problem only occurs on ubuntu, my mac with 16G memory is good to predict with high memory pressure.(Later I found that the virtual memory on mac is allocated dynamically, and It can use more than 50G memory in total.)

Code:
```
import torchvision, torch, os
from torch import nn
from torch.autograd import Variable
from dataset import DATASET
from tqdm import tqdm

mydata = DATASET(os.getcwd())
model = torchvision.models.resnet152(pretrained=True)
new_classifier = nn.Sequential(*list(model.children())[:-1])
model.classifier = new_classifier
model.eval()

pos1 = model(Variable(mydata[0][0].view(1, 3, 224, 224)))
for index in tqdm(range(1, 1000)):
    f = model(Variable(mydata[index][0].view(1, 3, 224, 224)))
    pos1 = torch.cat((pos1, f))

with open('pos1_fea.pt', 'wb') as f:
    torch.save(pos1, f)
```

**Comment by chenzhekl** [comment]
Possible solution:

Do not store classification in the `Variable` `pos1`. This may prevent PyTorch from releasing memory. Instead extract data from `pos1` and store it in a Python list.

**Comment by xwzy** [comment]
Thanks, I changed my code, however It still used total 30-40GB memory to forward 100 pictures.

This is my code, is there still some problem?
```
pos1 = []
for index in tqdm(range(200)):
    f = model(Variable(mydata[index][0].view(1, 3, 224, 224)))
    pos1.append(f)

```

**Comment by chenzhekl** [comment]
Try this:

```
pos1.append(f.data)
```

**Comment by xwzy** [comment]
It works! Thank you!
