### ISSUE TITLE
Different behavior of variable sort and tensor sort.

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#2303]
```
import torch
x = torch.randn(10)
y = torch.autograd.Variable(x)

y.sort(descending=True)
x.sort(descending=True)
```

Got error when executing last line.

> TypeError: sort received an invalid combination of arguments - got (descending=bool, ), but expected one of:
>  * ()
>       didn't match because some of the keywords were incorrect: descending
>  * (int dim)
>  * (int dim, bool descending)

torch version 0.2.0_1

**Comment by lantiga** [comment]
You're right, #2329 fixes it
