### ISSUE TITLE
Versioned nightly URL for LibTorch with CUDA 10.0 doesn't work

### ISSUE THREAD

**Issue by VivekPanyam** [pytorch/pytorch#23039]
## 🐛 Bug

The following URLs work for the latest nightly build:
- https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
- https://download.pytorch.org/libtorch/nightly/cu90/libtorch-shared-with-deps-latest.zip
- https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-latest.zip

and versioned URLs work for CPU and CUDA 9.0:
- https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-1.2.0.dev20190601.zip
- https://download.pytorch.org/libtorch/nightly/cu90/libtorch-shared-with-deps-1.2.0.dev20190601.zip

but versioned URLs don't work for CUDA 10.0:
- https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-1.2.0.dev20190601.zip

**Comment by zhangguanheng66** [comment]
libtorch needs to work with CUDA 10.0. Better to fix this early.

**Comment by pjh5** [comment]
The versioned URL doesn't work because the binary was not uploaded on that specific day. If we ever have a circleci outage or bug appear (in the case of the libtorch builds it's usually timeout issues) then the binaries won't be uploaded for a day. In this case, 20190604 and 20190606 have both been uploaded, but nothing in between 20190530 and 20190604. 

FYI, for the pip wheels you can check the torch_nightly.html file to see what dates have uploaded packages. We don't have this for libtorch since they aren't installed by pip, but perhaps we can add html files anyways just to make this easier to discover.

**Comment by VivekPanyam** [comment]
It seems like between `20190601` and `20190722`, there are:
- 46 valid CPU builds
- 39 valid CUDA 9.0 builds
- only 2 valid CUDA 10.0 builds

out of a total of 52 possible nightly builds.

Any idea why CUDA 10.0 builds seem to fail so much more than the other ones?

(Here's a simple script to generate the above data: https://gist.github.com/VivekPanyam/0d22430c0b8052d590924c6640f8c402)

**Comment by pjh5** [comment]
Yes. It's because the CUDA 10 builds take longer so they are more susceptible to timeout problems. See https://github.com/pytorch/pytorch/blob/master/.circleci/README.md#note-on-libtorch . It's totally fixable, just no one has had cycles to work on it. Rewriting the build scripts is always a pain because of the long iteration time.

**Comment by VivekPanyam** [comment]
Understood.

Unfortunately, that means the CUDA 10 nightly builds aren't particularly useful (since there have been only 2 successful builds in the last ~2 months and the last success was ~1.5 months ago)

Is there a way to increase the timeout as an intermediate fix?

**Comment by soumith** [comment]
@VivekPanyam massive hack: you can download the CUDA10 wheel, unzip it and grab the libtorch / headers off of it

**Comment by rgommers** [comment]
The CUDA 10 build timing got fixed by gh-23348, see last night's run at https://circleci.com/workflow-run/33d0a24a-b77c-4a8f-9ecd-5646146ce684. The only failures there are on the upload stage, which got fixed by gh-23368.

So there should be fresh binaries in about 20 hours (I'll verify tomorrow).

**Comment by VivekPanyam** [comment]
Great! Thank you so much!

RE
> @VivekPanyam massive hack: you can download the CUDA10 wheel, unzip it and grab the libtorch / headers off of it

@soumith Are they actually drop in replacements of each other? In the past, I ran into issues with missing symbols when using the wrong `libtorch.so`. This was a while ago though so maybe it's not an issue anymore.

It seems like there are some differences on a recent nightly, but I haven't looked into it too much:

```
$ wget https://download.pytorch.org/whl/nightly/cu90/torch_nightly-1.2.0.dev20190722-cp27-cp27m-linux_x86_64.whl
$ wget https://download.pytorch.org/libtorch/nightly/cu90/libtorch-shared-with-deps-1.2.0.dev20190722.zip
$ unzip torch*.whl
$ unzip libtorch*.zip
$ abidiff --stat torch/lib/libtorch.so libtorch/lib/libtorch.so
Functions changes summary: 0 Removed, 0 Changed, 0 Added function
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
Function symbols changes summary: 10088 Removed, 10043 Added function symbols not referenced by debug info
Variable symbols changes summary: 38 Removed, 21 Added variable symbols not referenced by debug info
```

**Comment by pjh5** [comment]
@VivekPanyam the wheels include more optional dependencies; probably MKL and stuff like that. But, I'm building a new set right now, so you shouldn't need to try that anymore.

**Comment by rgommers** [comment]
New CUDA 10  nightlies are up, `latest` and with dates:
https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-1.2.0.dev20190725%2Bcu100.zip

See https://github.com/pytorch/pytorch/pull/23388#issuecomment-515297875 for the explanation of `%2B` in the link.

**Comment by VivekPanyam** [comment]
Thank you!

When was the CUDA version added to the version strings? That makes it a little harder to generate urls for nightly builds because it requires some special casing based on the date. Is there a way you could reupload old builds with the new naming? It's not a huge deal, but that would be helpful. Happy to open another issue if that makes more sense than talking about it here.

(Also, for anyone else looking at this issue, it appears that `cu90` is no longer a thing and `cu92` should be used instead for new nightlies)

Here are working URLs for nightly builds from today:
- `CPU`: https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-1.2.0.dev20190726%2Bcpu.zip
- `CUDA 9.2`: https://download.pytorch.org/libtorch/nightly/cu92/libtorch-shared-with-deps-1.2.0.dev20190726%2Bcu92.zip
- `CUDA 10.0`: https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-1.2.0.dev20190726%2Bcu100.zip

**Comment by rgommers** [comment]
> When was the CUDA version added to the version strings? That makes it a little harder to generate urls for nightly builds because it requires some special casing based on the date. Is there a way you could reupload old builds with the new naming? It's not a huge deal, but that would be helpful. Happy to open another issue if that makes more sense than talking about it here.

this should be easy to check with your `validate_nightly_builds.py` script linked above. Based on the output of that, it happened on `20190723`.

**Comment by pjh5** [comment]
The version string was added in https://github.com/pytorch/pytorch/pull/23325 .

CUDA 9.0 was removed recently for other reasons, in https://github.com/pytorch/pytorch/pull/22784 , in order to enable AVX512 support in the nightlies.

**Comment by VivekPanyam** [comment]
Okay, thanks. It seems like the mac builds don't have `+cpu` in the version string. (The mac nightly url for today is `https://download.pytorch.org/libtorch/nightly/cpu/libtorch-macos-1.2.0.dev20190726.zip`)

Is that a bug or intentional? I know that all the Mac builds are on CPU, but it would be good if the naming was consistent.

Also, I don't believe that these URLs are documented anywhere. I’m happy to put up a PR if you can point me to the right doc to add it to.

In #23325 @soumith mentioned putting all the builds in the same directory so maybe we can do something like this?
- https://download.pytorch.org/libtorch/nightly/libtorch-shared-with-deps-1.2.0.dev20190726+cpu.zip
- https://download.pytorch.org/libtorch/nightly/libtorch-shared-with-deps-1.2.0.dev20190726+cu92.zip
- https://download.pytorch.org/libtorch/nightly/libtorch-shared-with-deps-1.2.0.dev20190726+cu100.zip
- https://download.pytorch.org/libtorch/nightly/cpu/libtorch-macos-1.2.0.dev20190726+cpu.zip

(and reupload all the old nightlies so we don't need any special casing)

**Comment by pjh5** [comment]
Yes, the mac builds do not have the +cpu on them, since all mac builds are cpu only. This was intentional, since it's redundant and the + can mess up old pips. Fwiw the naming is already inconsistent across mac and linux; linux conda cpus are pytorch-nightly-cpu but mac conda cpus are just pytorch-nightly.

I don't think we ever really wanted to advertise the urls down to specific dates. We have the https://....libtorch...-latest.zip urls on the Pytorch getting-started page. This allows us to change the name of the urls underneath and /most/ people shouldn't notice.

I believe that adding the +cuda_version was the first step towards putting everything in the same directory.

**Comment by ezyang** [comment]
I'm planning to move them all into the same directory. But maybe not for a little bit.

**Comment by ezyang** [comment]
@VivekPanyam Starting from today the nightlies will be in a current directory.

If there was some stable URL which you could pass configuration and date and get the nightly tarball, that would be sufficient for your use case, is that right? Can you file a new issue about this and CC me?

**Comment by ezyang** [comment]
@VivekPanyam We're thinking of making the latest nightly file names available in a structured JSON file. Is that sufficient for your use case? It kind of sounds like you also want access to the old nightly wheels. What exactly do you want to be supported?

> (and reupload all the old nightlies so we don't need any special casing)

This is a bit more involved, because the wheel filename has to agree with the internal version of the package, so we'd also have to do some surgery on the wheels to get everything to line up.

**Comment by VivekPanyam** [comment]
> @VivekPanyam Starting from today the nightlies will be in a current directory.
> 
> If there was some stable URL which you could pass configuration and date and get the nightly tarball, that would be sufficient for your use case, is that right? Can you file a new issue about this and CC me?

That sounds great! Do you still want me to file a new issue?

> @VivekPanyam We're thinking of making the latest nightly file names available in a structured JSON file. Is that sufficient for your use case? It kind of sounds like you also want access to the old nightly wheels. What exactly do you want to be supported?
> 
> > (and reupload all the old nightlies so we don't need any special casing)
> 
> This is a bit more involved, because the wheel filename has to agree with the internal version of the package, so we'd also have to do some surgery on the wheels to get everything to line up.

A stable URL pattern that works for all the libtorch nightly packages (including old ones) would be preferable to a JSON index. Similarly for torch nightly wheels.

If that's difficult to do, then a JSON file that maps a  configuration to a libtorch tarball and a torch whl would work as well.

Thanks again!

**Comment by ezyang** [comment]
Yes, please file a new issue, and cc me.

**Comment by ezyang** [comment]
@VivekPanyam BTW, you aren't using pip to download these wheels, is that right? (pip has some problems if you pass it a URL that doesn't agree with the true wheel filename)

**Comment by VivekPanyam** [comment]
I am using pip to download and install the wheels. We're already special casing for CPU/GPU builds and nightly/release.

@ezyang Would it be easier to chat in more detail on Slack?

**Comment by ezyang** [comment]
If you only need the latest wheel, the new structure changes in https://github.com/pytorch/pytorch/issues/23656 ought to help. I tried to ping you on slack but couldn't find your username.
