### ISSUE TITLE
0.2 building from source

### ISSUE THREAD

**Issue by kefirski** [pytorch/pytorch#2304]
0.2.0 doesn't build from source (0.1.12 does)

```
Traceback (most recent call last):
File "/home/daniil/pytorch-0.2.0/torch/lib/ATen/gen.py", line 2, in <module>
import yaml
ImportError: No module named yaml
--
CMake Error at CMakeLists.txt:136 (message):
Failed to get generated_cpp list

— Configuring incomplete, errors occurred!
See also "/home/daniil/pytorch-0.2.0/torch/lib/build/ATen/CMakeFiles/CMakeOutput.log".
```

The issue is that I have `yaml`

`$ cat y_test.py`
`import yaml`

`$ python3 y_test.py`
`$`

**Comment by CDLuminate** [comment]
What about `python -c 'import yaml'`?

If the command fails, you need the python2 version yaml.

**Comment by kefirski** [comment]
```
daniil@ml1080:~$ python -c 'import yaml'
daniil@ml1080:~$
```

**Comment by CDLuminate** [comment]
Weird...

**Comment by nhynes** [comment]
I think that the real question is why python2 is being used to build when the invoking interpreter was python3!

**Comment by soumith** [comment]
it's because while building ATen, it invokes "python" instead of which python was invoked in setup.py install.

worth fixing via an env variable that's set in setup.py. cc: @zdevito @killeent

**Comment by killeent** [comment]
@soumith I can fix that.
