### ISSUE TITLE
Indexing by list problems

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#2305]
```
import torch
x = torch.randn(3)
y = torch.randn(4,1)

print y[[0,1,2], :] # works
print y[[0,1,2]] # doesn't works

print x[[0,1,2]] # doesn't work
print x[torch.LongTensor([0,1,2])] # works
```

torch version 0.2.0

**Comment by killeent** [comment]
Hi @ruotianluo -

In order to trigger advanced indexing, you must pass a sequence of indexing elements. So the correct way to index a single list is:

`y[[0,1,2],] # note trailing comma`

**Comment by ruotianluo** [comment]
Thanks.
