### ISSUE TITLE
pytorch keeps running unknown processes in other gpus

### ISSUE THREAD

**Issue by mutasem-mattar** [pytorch/pytorch#23059]
I am trying to train a model in a spicific GPU by using CUDA_VISIBLE_DEVICES in my script. However, unknown processes start running on other gpus that are not specified in the CUDA_VISIBLE_DEVICES. When they start running, batch training time takes very long time. When I kill those processes, batch training time goes back normal. However, the processes keep starting randomly.

Same problem is happening in other Machine as we. It is worth mentioning I am running pytorch inside docker using nvidia-docker.

Error messages and stack traces are also helpful.
I only specified CUDA_VISIBLE_DEVICES=0. however, those other process keep running randomly even after I kill them.

<img width="724" alt="Screen Shot 2019-07-19 at 7 49 21 AM" src="https://user-images.githubusercontent.com/8367757/61510048-ef678300-a9f9-11e9-9956-0fc0c1139a56.png">

Training time before those processes started and after I killed them. You can see how they make batch training time explode.

<img width="736" alt="Screen Shot 2019-07-19 at 7 50 15 AM" src="https://user-images.githubusercontent.com/8367757/61510162-76b4f680-a9fa-11e9-92d0-372b1a8bcab1.png">

## System Info
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X

Nvidia driver version: 410.78
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.1

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[pip] torchvision==0.3.0

**Comment by SsnL** [comment]
PyTorch literally has no ways to access other GPUs if you `CUDA_VISIBLE_DEVICES=0`.... It restricts which GPU NVIDIA driver exposes to the program.

**Comment by mutasem-mattar** [comment]
I really dont know what is going on. Even when I open a python notebook. I still get the same problem even when I specify the environment variable.

**Comment by soumith** [comment]
the environment variable has to be specified before you start the notebook, i.e. to the ipython notebook process itself.

for example in your terminal:

```
CUDA_VISIBLE_DEVICES=0 jupyter notebook
```
