### ISSUE TITLE
libtorch cannot find CUDA

### ISSUE THREAD

**Issue by minty99** [pytorch/pytorch#23066]
## Issue description
libtorch installation failed. The given sample code not working

## Code example
I followed this guide: https://pytorch.org/cppdocs/installing.html
When I run `cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/libtorch ..`,
This error is shown: (from cmake 3.5)
```
-- Could NOT find CUDA (missing: CUDA_CUDART_LIBRARY) (found version "10.0")
CMake Warning at /home/ubuntu/minty99/libtorch/share/cmake/Caffe2/public/cuda.cmake:31 (message):
  Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
  or a Caffe2 dependent library, the next warning / error will give you more
  info.
Call Stack (most recent call first):
  /home/ubuntu/minty99/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/ubuntu/minty99/libtorch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:4 (find_package)


CMake Error at /home/ubuntu/minty99/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:90 (message):
  Your installed Caffe2 version uses CUDA but I cannot find the CUDA
  libraries.  Please set the proper CUDA prefixes and / or install CUDA.
Call Stack (most recent call first):
  /home/ubuntu/minty99/libtorch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/minty99/tacotron2_cpp/CMakeFiles/CMakeOutput.log".
```

I tried to use latest cmake (3.15) then I got almost same error, only difference is  `missing: CUDA_CUDART_LIBRARY` changed to `missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY`

## System Info
```
- PyTorch or Caffe2: PyTorch
- OS: Ubuntu 16.04
- PyTorch version: 1.1
- Python version: 3.5
- CUDA/cuDNN version: 10.0
- GPU models and configuration: V100
- CMake version: 3.5.2 (tried 3.15.0)

**Comment by xuhdev** [comment]
What is your path to CUDA? If it is non-standard path, you can set `CUDA_HOME` before you run cmake.

**Comment by xuhdev** [comment]
Or edit the generated `build/CMakeCache.txt` to modify paths relevant to CUDA.

**Comment by minty99** [comment]
I set CUDA_HOME, it's working now. I thought I already set it but it wasn't properly set for some reason.

Thanks for your help!

**Comment by minty99** [comment]
It works some minutes ago, but now not. I used same script...
exact script here:
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(tacotron2-cpp)
set(ENV{CUDA_HOME} "/usr/local/cuda-10.0")
set(CUDA_HOME "/usr/local/cuda-10.0")
set(CMAKE_PREFIX_PATH "/home/ubuntu/minty99/libtorch")
message(STATUS $ENV{CUDA_HOME})
find_package(Torch REQUIRED)

add_executable(tacotron2-cpp tacotron2.cpp)
target_link_libraries(tacotron2-cpp "${TORCH_LIBRARIES}")
set_property(TARGET tacotron2-cpp PROPERTY CXX_STANDARD 11)
```

I set the environment variable in the script(of course, I added it in .bashrc too) but not working with same error.

**Comment by minty99** [comment]
I found that if I set CUDA_HOME in already opened terminal, then cmake fails to find CUDA. We should add the export lines in .bashrc

**Comment by HuaizhengZhang** [comment]
> I found that if I set CUDA_HOME in already opened terminal, then cmake fails to find CUDA. We should add the export lines in .bashrc

@minty99 Hi, I set the CUDA_HOME, but it still fails to find CUDA. Do you have any suggestions?

**Comment by pranaymodukuru** [comment]
Could you please provide a source on how to add CUDA_HOME .

**Comment by caelinsutch** [comment]
@pranaymodukuru `export CUDA_HOME=/usr/local/cuda`

**Comment by caelinsutch** [comment]
I'm also having this issue still

**Comment by pfeatherstone** [comment]
me too. Is there a fix?

**Comment by liubamboo** [comment]
generate soft link of cuda in /usr/local
eg: sudo ln -s /usr/local/cuda-10.2 /usr/local/cuda

and change the ~/.bashrc like:
export PATH=/usr/local/cuda-10.2/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda

my system is ubuntu. and my environment is cuda 10.2, libtorch 1.6.0

now it can work

**Comment by Rinnekioku** [comment]
I still have this issue even after extending .bashrc

**Comment by andreabonvini** [comment]
If you already set the CUDA_HOME, remember to delete your building directory (which contains the CMakeCache.txt file) first!

**Comment by kush930** [comment]
Hi all,

`I cloned master branch of pytorch from link`:- [GitHub - pytorch/pytorch: Tensors and Dynamic neural networks in Python with strong GPU acceleration](https://github.com/pytorch/pytorch.git)

I am building pytorch on riscv64, I am facing issue:-

```
In file included from /home/root/kush/pytorch/third_party/cpuinfo/src/x86/init.c:5:
/home/root/kush/pytorch/third_party/cpuinfo/src/x86/cpuid.h:5:11: fatal error: cpuid.h: No such file or directory
    5 |  #include <cpuid.h>
      |           ^~~~~~~~~
compilation terminated.
make[2]: *** [confu-deps/cpuinfo/CMakeFiles/cpuinfo_internals.dir/build.make:121: confu-deps/cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/init.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1788: confu-deps/cpuinfo/CMakeFiles/cpuinfo_internals.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
if anyone know, where i am wrong, please guide me to build pytorch on riscv64.

T&R
Kush

**Comment by kush930** [comment]
Hi all,

`I cloned pytorch version v1.10.0 from link`:- https://github.com/pytorch/pytorch/tree/v1.10.0

I am `building pytorch on riscv64`, I am facing issue:-

```
FAILED: confu-deps/QNNPACK/CMakeFiles/qnnpack.dir/src/init.c.o 
/usr/bin/cc -DCPUINFO_SUPPORTED_PLATFORM=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -I../third_party/QNNPACK/include -I../third_party/QNNPACK/src -I../third_party/cpuinfo/deps/clog/include -I../third_party/cpuinfo/include -I../third_party/pthreadpool/include -I../third_party/FXdiv/include -I../third_party/psimd/include -I../third_party/FP16/include -isystem ../third_party/protobuf/src -O3 -DNDEBUG -fPIC -Wno-deprecated-declarations -pthread -std=gnu99  -Os -MD -MT confu-deps/QNNPACK/CMakeFiles/qnnpack.dir/src/init.c.o -MF confu-deps/QNNPACK/CMakeFiles/qnnpack.dir/src/init.c.o.d -o confu-deps/QNNPACK/CMakeFiles/qnnpack.dir/src/init.c.o -c ../third_party/QNNPACK/src/init.c
../third_party/QNNPACK/src/init.c: In function 'init':
../third_party/QNNPACK/src/init.c:240:4: error: #error "Unsupported architecture"
  240 |   #error "Unsupported architecture"
      |    ^~~~~
[214/3715] Building C object confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/src/portable-api.c.o
```
if anyone know, where i am wrong, please guide me to build pytorch on riscv64.

T&R
Kush

**Comment by DirtyVoid** [comment]
It is still a persisting problem. No matter what I do it does not work. 

```
Aspire-VX5-591G% echo $LD_LIBRARY_PATH
/usr/local/cuda-11.8/lib64:/usr/local/lib
Aspire-VX5-591G% echo $CUDA_HOME
/usr/local/cuda-11.8
Aspire-VX5-591G% echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dirtyvoid/.local/bin:/usr/local/cuda-11.8/bin
Aspire-VX5-591G% nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```
I have everything it cannot find CUDA. Can you please help?

**Comment by mamba824824** [comment]
> It is still a persisting problem. No matter what I do it does not work.
> 
> ```
> Aspire-VX5-591G% echo $LD_LIBRARY_PATH
> /usr/local/cuda-11.8/lib64:/usr/local/lib
> Aspire-VX5-591G% echo $CUDA_HOME
> /usr/local/cuda-11.8
> Aspire-VX5-591G% echo $PATH
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dirtyvoid/.local/bin:/usr/local/cuda-11.8/bin
> Aspire-VX5-591G% nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2022 NVIDIA Corporation
> Built on Wed_Sep_21_10:33:58_PDT_2022
> Cuda compilation tools, release 11.8, V11.8.89
> Build cuda_11.8.r11.8/compiler.31833905_0
> ```
> 
> Error:
> 
> ```
> -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR) (found version "11.8")
> CMake Warning at /media/dirtyvoid/FileHub/Universal_Data/Codes/C_C++/C++/LLM/thirdparty/libtorch/share/cmake/Caffe2/public/cuda.cmake:31 (message):
>   Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
>   or a Caffe2 dependent library, the next warning / error will give you more
>   info.
> Call Stack (most recent call first):
>   /media/dirtyvoid/FileHub/Universal_Data/Codes/C_C++/C++/LLM/thirdparty/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
>   /media/dirtyvoid/FileHub/Universal_Data/Codes/C_C++/C++/LLM/thirdparty/libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
>   CMakeLists.txt:13 (find_package)
> 
> 
> CMake Error at /media/dirtyvoid/FileHub/Universal_Data/Codes/C_C++/C++/LLM/thirdparty/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:90 (message):
>   Your installed Caffe2 version uses CUDA but I cannot find the CUDA
>   libraries.  Please set the proper CUDA prefixes and / or install CUDA.
> Call Stack (most recent call first):
>   /media/dirtyvoid/FileHub/Universal_Data/Codes/C_C++/C++/LLM/thirdparty/libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
>   CMakeLists.txt:13 (find_package)
> ```
> 
> However I do the same thing in GOOGLE colab it works https://colab.research.google.com/drive/1gfXmZ6ZgG8Bid_Zkx9DWyNRvpKKhXihM?usp=sharing
> 
> I have everything it cannot find CUDA. Can you please help?

I have the similar problem, do you resolve that.

**Comment by ndming** [comment]
I solved this by adding `find_package(CUDA REQUIRED)` right before `find_package(Torch REQUIRED)`. I didn't set `CUDA_HOME` as suggested by @minty99.
```
find_package(CUDA REQUIRED) <-- add this line
find_package(Torch REQUIRED)
```

The reason could be that Caffe2 is trying to find CUDA via the deprecated `find_package(CUDA REQUIRED)`. Note that this may only work for CMake `<3.27`, as CMake `3.27+` completely removes the FindCUDA module.
