### ISSUE TITLE
adam.py KeyError: 'betas'

### ISSUE THREAD

**Issue by Dhanachandra** [pytorch/pytorch#23070]
## 🐛 Bug

File "STS_main.py", line 196, in <module>
    model, optimizer, loss = train(model, train_iter, optimizer, criterion)
  File "STS_main.py", line 72, in train
    optimizer.step()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/optim/adam.py", line 85, in step
    beta1, beta2 = group['betas']
KeyError: 'betas'

**Comment by vishwakftw** [comment]
Could you please provide environment information or copy-paste the output from [the environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)?

**Comment by Dhanachandra** [comment]
@vishwakftw 
OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1) 7.4.0
CMake version: version 3.13.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] numpydoc==0.8.0
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] pytorch-transformers==0.7.0
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[pip3] torchwordemb==0.0.9
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.2                      1  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.1            py36h3010b51_0  
[conda] mkl_random                1.0.1            py36h629b387_0  
[conda] pytorch-pretrained-bert   0.6.2                     <pip>
[conda] pytorch-transformers      0.7.0                     <pip>
[conda] torch                     1.1.0                     <pip>
[conda] torchvision               0.3.0                     <pip>
[conda] torchwordemb              0.0.9                     <pip>

**Comment by vishwakftw** [comment]
Could you provide a reproduction script?

**Comment by Dhanachandra** [comment]
What  is reproduction script?

**Comment by vishwakftw** [comment]
> What is reproduction script?

A code example to help produce the same error you are getting.

**Comment by Dhanachandra** [comment]
`optimizer = optim.SGD(model.parameters(), lr = Param.lr)
for epoch in range(1, 100):
       train(model, optimizer)`
error occurs in the 2nd epoch
if th optimizer is initialised inside the train() module, then there is no such error.

**Comment by vincentqb** [comment]
I am unable to reproduce the error. Can you provide a small but complete and self-contained code that reproduces the error?

**Comment by sethd1** [comment]
From the initial bug shown, it seems as if in the "group" dictionary, there is no key "betas" that you are trying to find the value of. Also, every key in a dictionary has one value (1:1), so can you explain why you are equating both "beta1" and "beta2" to the value that you are trying to get from the key "betas."

**Comment by soumith** [comment]
@Dhanachandra you have modifed adam.py yourself, or you loaded an incorrect checkpoint into your constructed optimizer. Either ways, it's your code's bug.

**Comment by soumith** [comment]
@sethd1 `betas` is a tuple of 2 elements, so `beta1, beta2 = betas` will unpack `betas`

**Comment by rajeshds1972** [comment]
This happened once with me. I had saved a  model (checkpoint) that was trained with  SGD optimizer and I was trying to retrain (while transfer learning) the model (using the checkpoint)  using Adam optimizer by mistake.

**Comment by rajeshds1972** [comment]
After realizing my mistake things went well

**Comment by sammlapp** [comment]
I encountered the same error when trying to use AdamW to continue training after initially using SGD optimizer. Is switching optimizers not allowed? 

```
File ~/miniconda3/envs/opso0120/lib/python3.10/site-packages/torch/optim/adamw.py:230, in AdamW.step(self, closure)
    [228](https://vscode-remote+ssh-002dremote-002belf.vscode-resource.vscode-cdn.net/home/sml161/song1/protopnet/~/miniconda3/envs/opso0120/lib/python3.10/site-packages/torch/optim/adamw.py:228) state_steps: List[Tensor] = []
    [229](https://vscode-remote+ssh-002dremote-002belf.vscode-resource.vscode-cdn.net/home/sml161/song1/protopnet/~/miniconda3/envs/opso0120/lib/python3.10/site-packages/torch/optim/adamw.py:229) amsgrad: bool = group["amsgrad"]
--> [230](https://vscode-remote+ssh-002dremote-002belf.vscode-resource.vscode-cdn.net/home/sml161/song1/protopnet/~/miniconda3/envs/opso0120/lib/python3.10/site-packages/torch/optim/adamw.py:230) beta1, beta2 = cast(Tuple[float, float], group["betas"])
```

this occurs when calling step on GradScaler, even though the GradScaler is disabled! (`scaler=torch.amp.GradScaler(enabled=False)`)

This seems odd, is it a bug or is this behavior expected?

The training loop is something like
```python
scaler = torch.amp.GradScaler(enabled=False)

for batch in dataloader:
    output = self.network(batch_tensors)
    loss = self.loss_fn(output, batch_labels)
    scaler.scale(loss).backward()
    scaler.step(self.optimizer)
    scaler.update()
    optimizer.zero_grad()
```
