### ISSUE TITLE
torch/nn/quantized/modules/conv.py should not depend on Numpy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#23080]
We support building PyTorch without Numpy, and none of our core library code should use Numpy.  It doesn't even seem to be imported for a good reason, just to run `np.floor`...

**Comment by vishwakftw** [comment]
It seems like we could use floor division for the function that uses np.floor...

**Comment by vishwakftw** [comment]
I think this is being worked on in https://github.com/pytorch/pytorch/pull/23115
