### ISSUE TITLE
Neither 2.7 wheel works for me on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by bnsh** [pytorch/pytorch#2308]
Hi.. So, I tried downloading both

 * http://download.pytorch.org/whl/cu80/torch-0.2.0.post1-cp27-cp27m-manylinux1_x86_64.whl 
 * http://download.pytorch.org/whl/cu80/torch-0.2.0.post1-cp27-cp27mu-manylinux1_x86_64.whl

on my box.. And, neither seems to be working.

I looked at how to figure out whether I have ucs2 or not, and it looks like I have ucs4:

```
binesh@client:/tmp/$ python2.7
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.maxunicode
1114111
>>> 
binesh@client:/tmp$ cat /etc/issue
Ubuntu 16.04.2 LTS \n \l
```

But

```
root@client:/tmp/dlframeworks/pytorch/gpu# pip2.7 install -U torch-0.2.0.post1-cp27-cp27m-manylinux1_x86_64.whl 
torch-0.2.0.post1-cp27-cp27m-manylinux1_x86_64.whl is not a supported wheel on this platform.
root@client:/tmp/dlframeworks/pytorch/gpu# pip2.7 install -U torch-0.2.0.post1-cp27-cp27mu-manylinux1_x86_64.whl 
torch-0.2.0.post1-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform.
root@client:/tmp/dlframeworks/pytorch/gpu# md5sum torch-0.2.0.post1-cp27-cp27m*
80410b051620b53b6513469c4390e73a  torch-0.2.0.post1-cp27-cp27m-manylinux1_x86_64.whl
f007d96a78a841de9abdc6d1e35ea353  torch-0.2.0.post1-cp27-cp27mu-manylinux1_x86_64.whl
root@client:/tmp/dlframeworks/pytorch/gpu# 
```

I _am_ able to use the 3.5 version... (But, I need the 2.7 one to work as well, unfortunately.)

any ideas?

Thanks!

**Comment by soumith** [comment]
what's the output of `pip --version`? (or in your case `pip2.7 --version` I suspect some misconfiguration around that.

**Comment by bnsh** [comment]
A-ha! Yep! That was it! Thanks! (I just assumed pip2.7 was for python2.7, but it says it's for pypy.. D-oh! Thanks!

**Comment by Deepakchawla** [comment]
but in my case pip version is pip 9.0.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)
what should I have to do..?

**Comment by alykhantejani** [comment]
@Deepakchawla I don't think Python 3.4 is supported. There are only wheels build for 2.7, 3.5 and 3.6
