### ISSUE TITLE
_C.so: undefined symbol: _ZTVSt12bad_weak_ptr 

### ISSUE THREAD

**Issue by zhengyunqq** [pytorch/pytorch#2310]
I tried the the new version v0.2.0 by 
pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp27-cp27m-manylinux1_x86_64.whl 
I got the following error message, when running import torch
_C.so: undefined symbol: _ZTVSt12bad_weak_ptr

**Comment by soumith** [comment]
What is your Operating System name/version, 
also the output of `python --version`?
Also the output of `gcc --version`?

**Comment by zhengyunqq** [comment]
python version:
2.7 (r27, May 27 2013, 20:02:53) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-46)]

**Comment by soumith** [comment]
that gcc is reallllly old. what os are you running on? rhel5?

**Comment by zhengyunqq** [comment]
Yes，rhel5.  I installed the latest manylinux release of scipy, numpy, pillow etc. There are no such problems.

**Comment by soumith** [comment]
unfortunately we cannot support rhel5. the reason for this is because CUDA doesn't support rhel5. I've looked into this extensively and tried to find a solution. The packages you mention do not use CUDA or gpus.

**Comment by zhengyunqq** [comment]
In this case, I only need the cpu version of pytorch. Could it possible to build a version which only supports cpu ?

**Comment by soumith** [comment]
you can build from source using the instructions in our readme
