### ISSUE TITLE
input_names Bug for Converting PyTorch Model to ONNX

### ISSUE THREAD

**Issue by shawzhan** [pytorch/pytorch#23107]
## 🐛 Bug

I want to convert my pyTorch model to ONNX. However, I get an error saying that 
> RuntimeError: number of input names provided (9) exceeded number of inputs (7) However, my code runs perfectly if I take out the two Dropout layers from my model. 

I believe that this is an error with the Dropout Layer.
## To Reproduce

1. I defined the following sequential model:
```
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.2),  # problem with dropout layer
    torch.nn.Linear(H, H),
    torch.nn.LeakyReLU(),
    torch.nn.Dropout(0.2),  # problem with dropout layer
    torch.nn.Linear(H, D_out),
    torch.nn.Sigmoid()
)
```
2. After training, then I want to export this model to ONNX:
```
model.eval()
input_names = ['input_1']
output_names = ['output_1']
for key, module in model._modules.items():
    input_names.append("l_{}_".format(key) + module._get_name())
torch_out = torch.onnx.export(model, 
                         features, 
                         "onnx_model.onnx", 
                         export_params = True, 
                         verbose = True, 
                         input_names = input_names, 
                         output_names = output_names,
                        )
```

However, this does not work. BUT it does work if I take out the two Dropout layers when defining the model.

## Expected behavior
I expect the model to only have 7 layers (without the Dropout) when exporting, especially because it's in eval() mode.

**Comment by CanoeFZH** [comment]
Can you give some more specific output details about runtime environment? @shawzhan

**Comment by shawzhan** [comment]
Yes, here is the error.

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-855-805274846b14> in <module>()
>      15                          verbose = True,
>      16                          input_names = input_names,
> ---> 17                          output_names = output_names,
>      18                         )
> 
> ~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/__init__.py in export(*args, **kwargs)
>      23 def export(*args, **kwargs):
>      24     from torch.onnx import utils
> ---> 25     return utils.export(*args, **kwargs)
>      26 
>      27 
> 
> ~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, strip_doc_string)
>     129             operator_export_type=operator_export_type, opset_version=opset_version,
>     130             _retain_param_name=_retain_param_name, do_constant_folding=do_constant_folding,
> --> 131             strip_doc_string=strip_doc_string)
>     132 
>     133 
> 
> ~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, propagate, opset_version, _retain_param_name, do_constant_folding, strip_doc_string)
>     361                                                         output_names, operator_export_type,
>     362                                                         example_outputs, propagate,
> --> 363                                                         _retain_param_name, do_constant_folding)
>     364 
>     365         # TODO: Don't allocate a in-memory string for the protobuf
> 
> ~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, training, input_names, output_names, operator_export_type, example_outputs, propagate, _retain_param_name, do_constant_folding, _disable_torch_constant_prop)
>     285             output.inferTypeFrom(tensor)
>     286 
> --> 287     _set_input_and_output_names(graph, input_names, output_names)
>     288 
>     289     # make sure that the param dict and the graph match each other
> 
> ~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/utils.py in _set_input_and_output_names(graph, input_names, output_names)
>     417             if node.uniqueName() != name:
>     418                 node.setUniqueName(name)
> --> 419     set_names(list(graph.inputs()), input_names, 'input')
>     420     set_names(list(graph.outputs()), output_names, 'output')
>     421 
> 
> ~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/onnx/utils.py in set_names(node_list, name_list, descriptor)
>     413             raise RuntimeError(
>     414                 "number of %s names provided (%d) exceeded number of %ss (%d)"
> --> 415                 % (descriptor, len(name_list), descriptor, len(node_list)))
>     416         for name, node in zip(name_list, node_list):
>     417             if node.uniqueName() != name:
> 
> RuntimeError: number of input names provided (9) exceeded number of inputs (7)

**Comment by BowenBao** [comment]
> RuntimeError: number of input names provided (9) exceeded number of inputs (7)

The error appears as you are providing input(initializer) names for the dropout probability as well. On the other hand as you mentioned the dropout layer is removed during export, that's why it complains 2 extra. 

> for key, module in model._modules.items():
>     input_names.append("l_{}_".format(key) + module._get_name())

commenting out the above two lines resolves the issue.

**Comment by spandantiwari** [comment]
@shawzhan - can you confirm that your issue is resolved?

**Comment by garymm** [comment]
Closing due to lack of response from @shawzhan.
Feel free to comment here if this is still an issue.

**Comment by moe-sani** [comment]
Hi
I am having the same issue.
to replicate, I tried running the example above (but needed to modify it to get it work)
```Python


`model = torch.nn.Sequential(
    torch.nn.Linear(10, 10),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.2),  # problem with dropout layer
    torch.nn.Linear(10, 10),
    torch.nn.LeakyReLU(),
    torch.nn.Dropout(0.2),  # problem with dropout layer
    torch.nn.Linear(10, 2),
    torch.nn.Sigmoid()
)

# Input to the model
x = torch.randn(1, 1, 10,10, requires_grad=True)
torch_out = model(x)


model.eval()
input_names = ['input_1','input_2','input_3','input_4','input_5','input_6','input_7','input_8','input_9','input_10']
output_names = ['output_1', 'output_2']

torch_out = torch.onnx.export(model, 
                         x, 
                         "onnx_model.onnx", 
                         export_params = True, 
                         verbose = True, 
                         input_names = input_names, 
                         output_names = output_names,
                        )

```  
and the result is:


```python


============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?0c6cd694-66cf-454d-97ae-25f82d5613e8)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[59], line 5
      2 input_names = ['input_1','input_2','input_3','input_4','input_5','input_6','input_7','input_8','input_9','input_10']
      3 output_names = ['output_1', 'output_2']
----> 5 torch_out = torch.onnx.export(model11, 
      6                          x, 
      7                          "onnx_model.onnx", 
      8                          export_params = True, 
      9                          verbose = True, 
     10                          input_names = input_names, 
     11                          output_names = output_names,
     12                         )

File ~/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/onnx/utils.py:506, in export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, custom_opsets, export_modules_as_functions)
    188 @_beartype.beartype
    189 def export(
    190     model: Union[torch.nn.Module, torch.jit.ScriptModule, torch.jit.ScriptFunction],
   (...)
    206     export_modules_as_functions: Union[bool, Collection[Type[torch.nn.Module]]] = False,
    207 ) -> None:
    208     r"""Exports a model into ONNX format.
    209 
    210     If ``model`` is not a :class:`torch.jit.ScriptModule` nor a
   (...)
...
   1670     )
   1672 # Mark if the output node DebugName is set before.
   1673 output_node_set = set()

RuntimeError: number of input names provided (10) exceeded number of inputs (7) ```
