### ISSUE TITLE
DataLoader leaking Semaphores.

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#23117]
Following off of this error report: https://github.com/pytorch/pytorch/issues/11727

We concluded that `multiprocessing.set_start_method('spawn')` needed to be included in `if __name__ == '__main__'` for the error to go away; however, that's no longer the case with `torch.multiprocessing.spawn`.

## 🐛 Bug

```python
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```

## To Reproduce

```python
from torch import multiprocessing
from torch.utils.data import DataLoader
import torch

mp_lock = multiprocessing.Lock()

def main(device_index):
    list(DataLoader([torch.tensor(i) for i in range(10)], num_workers=4))


if __name__ == '__main__':
    torch.multiprocessing.spawn(main)
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.1.post2
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7.3

**Comment by soumith** [comment]
cc: @SsnL

**Comment by SsnL** [comment]
cc @pietern who added `torch.mp.spawn`

**Comment by SsnL** [comment]
Also, not sure what we can do tho. This is a purely python (no pytorch) repro:


```py
import multiprocessing as mp

mp_lock = mp.Lock()

def w():
    pass

def main():
    ps = [mp.Process(target=w) for _ in range(4)]
    for p in ps:
        p.daemon = True
        p.start()
    for p in ps:
        p.join()

if __name__ == '__main__':
    p = mp.get_context('spawn').Process(target=main)
    p.start()
    p.join()


```

**Comment by SsnL** [comment]
I would say that you just should not use global locks.

**Comment by PetrochukM** [comment]
I'm trying to avoid instantiating the lock, the example below more accurately reflects my problem with the `object`.

```
import multiprocessing as mp


class DecoratorThatNeedsLock():

    def __init__(self):
        self.mp_lock = mp.Lock()


l_ = DecoratorThatNeedsLock()


def w():
    pass


def main():
    ps = [mp.Process(target=w) for _ in range(4)]
    for p in ps:
        p.daemon = True
        p.start()
    for p in ps:
        p.join()


if __name__ == '__main__':
    p = mp.get_context('spawn').Process(target=main)
    p.start()
    p.join()
```

For Python problems like this, where is the go-to to get help?

**Comment by PetrochukM** [comment]
Okay, I fixed my problem. Now there is a `Lock` or something in one of my dependencies!

https://github.com/librosa/librosa/issues/924

**Comment by vadimkantorov** [comment]
I also experienced the issue with leaked semaphores/librosa/spawn: https://github.com/pytorch/pytorch/issues/22131

**Comment by soumith** [comment]
> For Python problems like this, where is the go-to to get help?

@PetrochukM unfortunately nowhere

**Comment by PetrochukM** [comment]
Thanks for your guy's help! 

Numba has responded and is fixing the issue. In the future, I hope this GitHub issue will provide clarity to anyone facing this issue in the future.
