### ISSUE TITLE
Repeat operation causes rounding

### ISSUE THREAD

**Issue by Sudsakorn123** [pytorch/pytorch#23129]
## To Reproduce

1. a = torch.rand(10,100)
we can get
tensor([[9.7914e-01, 4.2170e-01, 8.6023e-01, 5.6672e-01, 3.7669e-01, 4.4089e-01,
         8.1361e-01, 8.5139e-01, 8.3456e-01, 6.6393e-01, 8.8118e-01, 4.5309e-02,
         6.1380e-01, 6.9232e-02, 5.9977e-01, 7.4882e-01, 4.0679e-02, 7.2255e-01,
         7.7446e-01, 5.5719e-01, 8.4385e-01, 3.0668e-01, 5.0991e-01, 8.9780e-01,
         1.5546e-01, 3.8197e-01, 3.5928e-02, 7.6844e-01, 7.6060e-01, 9.3948e-01,
         2.2191e-01, 6.7028e-01, 5.1958e-01, 8.1589e-01, 3.0646e-01, 2.9752e-01,
         7.3885e-01, 5.9322e-01, 1.2655e-01, 7.7938e-01, 1.5305e-01, 2.6022e-01,
         6.1147e-01, 2.3651e-01, 2.0804e-01, 8.4600e-01, 7.4812e-01, 4.6446e-01,
         3.3259e-01, 2.2243e-01, 4.7918e-01, 3.7567e-01, 2.4212e-01, 5.1283e-01,
         5.6828e-01, 4.6127e-01, 1.4283e-01, 1.0642e-01, 9.6579e-01, 1.4335e-01,
         3.7578e-01, 6.4500e-01, 5.7741e-01, 8.9962e-01, 5.4083e-01, 7.2646e-01,
         4.8825e-01, 7.0372e-01, 9.9282e-01, 5.0060e-02, 6.7119e-01, 5.3972e-01,
         2.3060e-01, 2.8317e-01, 1.8694e-01, 8.4176e-01, 3.5567e-01, 1.7676e-01,
         1.3262e-01, 8.0692e-01, 6.8638e-02, 5.4456e-01, 9.4624e-01, 4.9810e-01,
         1.2011e-01, 7.6218e-02, 5.9771e-01, 5.4707e-01, 1.1320e-01, 4.1658e-02,
         6.3505e-01, 1.6260e-01, 2.4112e-01, 9.9180e-01, 7.0273e-03, 6.9397e-01,
         3.8652e-01, 7.0930e-01, 7.3298e-01, 7.9046e-02],
        [7.2470e-01, 4.7703e-01, 8.6047e-01, 3.6453e-01, 1.2923e-01, 6.2217e-01,
         9.1408e-01, 9.1069e-01, 5.4004e-02, 5.3360e-01, 4.5052e-01, 1.9276e-01,
         3.0798e-01, 9.4930e-01, 5.6814e-01, 2.7779e-01, 2.6797e-02, 3.8524e-01,
         8.1142e-01, 7.0198e-01, 1.3449e-01, 3.3866e-01, 9.9050e-01, 1.1547e-01,
         3.2577e-01, 5.9287e-01, 3.9199e-01, 3.3681e-01, 2.8518e-01, 6.4487e-01,
         4.2055e-01, 2.9557e-01, 2.2429e-01, 7.7110e-01, 9.4697e-01, 8.9555e-01,
         5.8724e-01, 6.6316e-01, 1.6983e-01, 9.7747e-01, 9.6894e-01, 7.0742e-01,
         4.2532e-01, 4.6472e-01, 4.0806e-01, 9.2941e-01, 8.3817e-02, 9.3459e-01,
         9.5648e-02, 1.4812e-01, 6.8011e-01, 9.2762e-01, 4.6263e-01, 4.3903e-01,
         5.8678e-01, 2.7453e-01, 5.9360e-01, 3.2480e-01, 2.8113e-01, 2.1966e-01,
         5.1492e-01, 5.5184e-01, 8.4804e-01, 3.8983e-01, 8.6692e-01, 3.6450e-01,
         4.8672e-01, 3.4275e-01, 7.2255e-01, 3.4994e-01, 2.6186e-01, 7.5610e-03,
         5.3200e-01, 2.2288e-02, 2.9068e-01, 6.4108e-02, 4.8900e-01, 3.2787e-01,
         7.5855e-02, 3.7513e-01, 7.4621e-01, 8.1552e-01, 8.3069e-02, 1.0759e-01,
         4.2107e-01, 5.1753e-01, 4.9805e-01, 1.0073e-01, 5.4269e-01, 6.0791e-01,
         1.7497e-01, 8.8874e-01, 9.5406e-03, 8.6896e-01, 9.1386e-01, 9.4153e-01,
         1.5192e-01, 9.0609e-03, 4.6439e-01, 7.1264e-01],
        [4.6143e-01, 3.9809e-01, 8.1118e-01, 1.5970e-01, 2.9832e-01, 7.9151e-01,
         2.4855e-01, 5.1344e-01, 4.1192e-01, 2.0200e-01, 2.4549e-01, 8.0596e-01,
         4.8714e-01, 4.9783e-01, 7.5329e-01, 7.8557e-02, 1.1941e-01, 9.3186e-01,
         4.1575e-01, 9.7742e-01, 4.8824e-01, 2.2053e-01, 6.6668e-01, 4.1472e-01,
         6.7807e-01, 2.7984e-01, 3.5479e-01, 7.6334e-01, 9.3352e-01, 1.1428e-01,
         5.2186e-01, 4.1268e-01, 7.8900e-01, 1.2760e-01, 7.7556e-01, 4.1262e-01,
         2.6310e-01, 4.8309e-01, 3.8940e-01, 3.8403e-01, 8.2441e-01, 3.2306e-01,
         1.6506e-01, 5.6562e-01, 9.8740e-01, 7.2267e-01, 9.7838e-01, 4.3231e-01,
         1.8582e-01, 1.8470e-01, 6.3047e-01, 6.7307e-01, 8.6683e-01, 2.9540e-01,
         9.2681e-01, 9.2273e-01, 1.1866e-01, 1.2488e-01, 7.2618e-01, 7.2994e-01,
         7.6344e-01, 9.2041e-01, 8.9930e-01, 3.7005e-01, 3.9479e-01, 1.8518e-01,
         5.2884e-01, 3.7831e-01, 9.7797e-01, 2.9997e-01, 8.9903e-01, 5.3983e-01,
         7.7121e-01, 6.1893e-01, 6.1208e-01, 5.7834e-01, 7.8134e-01, 7.2989e-01,
         7.2065e-01, 3.4786e-01, 8.8231e-01, 4.8917e-03, 9.4674e-01, 8.6879e-01,
         5.6005e-01, 6.4558e-01, 6.6408e-01, 4.2266e-01, 7.8352e-01, 7.4859e-01,
         9.3303e-01, 6.1386e-01, 8.2525e-01, 2.4019e-01, 4.2252e-01, 1.3084e-01,
         8.8780e-02, 3.8231e-01, 6.5462e-01, 3.4419e-01],
        [4.8890e-01, 3.8905e-01, 3.4575e-01, 9.8697e-01, 3.4123e-01, 9.2151e-01,
         2.9642e-01, 4.1829e-01, 4.5203e-01, 8.5881e-02, 7.8388e-01, 3.7711e-01,
         3.9305e-01, 7.0525e-01, 7.6278e-01, 9.2868e-01, 3.7266e-01, 8.5300e-01,
         8.5777e-01, 7.7372e-01, 4.0366e-01, 7.0456e-01, 4.1403e-01, 5.3486e-01,
         3.4536e-01, 1.5865e-01, 7.9456e-01, 6.6802e-01, 9.5743e-01, 3.5674e-01,
         1.2124e-01, 6.2554e-02, 8.4905e-01, 7.4969e-01, 5.8969e-01, 6.7757e-01,
         5.5445e-01, 2.7088e-01, 4.8980e-01, 6.0946e-01, 5.9020e-01, 8.1869e-03,
         5.0955e-01, 2.9888e-01, 8.6026e-01, 9.7689e-01, 3.6655e-01, 8.9496e-01,
         6.9697e-01, 7.5478e-01, 8.2682e-01, 3.6881e-01, 6.9922e-01, 2.9373e-01,
         1.3003e-01, 8.4381e-03, 4.5474e-01, 5.2764e-01, 4.7312e-01, 3.9753e-01,
         5.1099e-01, 7.3537e-02, 9.1238e-01, 5.7588e-03, 7.4291e-01, 8.9902e-01,
         5.4588e-01, 7.9523e-01, 4.9441e-01, 7.0223e-01, 2.9556e-01, 7.4996e-01,
         5.0406e-01, 3.6913e-01, 9.9252e-01, 2.3722e-01, 8.5251e-01, 9.1300e-01,
         9.0261e-01, 4.9033e-01, 3.7905e-01, 7.0572e-01, 7.2684e-01, 7.7622e-01,
         4.0855e-01, 4.5531e-01, 1.1855e-01, 1.5528e-02, 4.6176e-01, 6.1351e-01,
         8.2282e-01, 5.6528e-01, 4.6927e-01, 9.3556e-02, 7.2716e-01, 7.6554e-01,
         6.8779e-02, 7.4748e-02, 8.0860e-01, 4.1382e-01],
        [5.6431e-01, 8.5799e-01, 9.9967e-01, 6.1221e-01, 7.7367e-01, 3.1299e-01,
         8.7324e-02, 6.6023e-01, 8.5876e-01, 5.9140e-01, 9.6612e-01, 5.6570e-01,
         7.9158e-01, 9.1055e-01, 8.2701e-01, 4.7041e-01, 7.1581e-01, 6.6090e-01,
         3.1172e-01, 2.6346e-01, 9.5880e-02, 3.2321e-01, 2.8984e-01, 7.5465e-01,
         9.8734e-02, 5.5409e-01, 6.4679e-01, 4.9905e-01, 7.7172e-01, 1.4207e-01,
         8.2044e-01, 3.4233e-02, 5.1992e-01, 2.1992e-01, 3.4657e-01, 4.8869e-01,
         8.5407e-01, 5.4154e-01, 9.0646e-01, 7.9567e-01, 3.2566e-01, 2.3670e-01,
         1.5864e-01, 5.2299e-02, 2.8798e-01, 8.3460e-01, 4.1184e-01, 7.4573e-01,
         4.9688e-01, 9.6964e-01, 1.7678e-01, 7.4378e-03, 2.3393e-01, 8.4490e-01,
         8.8473e-01, 4.8899e-01, 9.0370e-01, 7.6337e-01, 8.2354e-01, 9.7611e-01,
         9.5210e-01, 7.5390e-01, 8.0376e-01, 5.8918e-02, 3.4673e-01, 9.9137e-01,
         3.7871e-01, 7.6767e-01, 7.5250e-01, 9.2928e-01, 4.9345e-02, 5.0886e-01,
         4.2187e-02, 2.3501e-01, 3.4611e-01, 3.0139e-01, 4.1408e-03, 8.3784e-03,
         3.4194e-01, 6.8865e-01, 9.2917e-01, 3.2052e-01, 9.4459e-01, 4.7535e-02,
         7.1213e-01, 4.6214e-01, 7.5571e-01, 7.9925e-01, 6.4504e-01, 4.2962e-01,
         8.9463e-01, 3.3993e-01, 3.0180e-01, 8.2016e-01, 6.6611e-01, 7.9363e-02,
         9.1177e-01, 1.5425e-01, 6.6965e-02, 6.5691e-01],
        [7.0085e-01, 2.9649e-01, 7.0921e-01, 1.8676e-01, 9.7448e-01, 5.3593e-01,
         6.2291e-01, 1.2772e-01, 1.8836e-01, 7.1927e-01, 9.2498e-01, 6.1896e-01,
         2.5310e-01, 5.1814e-02, 1.4088e-01, 2.2143e-01, 9.2180e-01, 3.1595e-01,
         4.1147e-01, 8.7701e-01, 9.9825e-01, 2.9776e-01, 1.5074e-02, 6.5817e-01,
         2.3001e-01, 4.0755e-01, 3.3722e-01, 2.3432e-01, 4.8462e-01, 4.1243e-01,
         8.3835e-01, 5.7175e-01, 2.8275e-01, 7.9053e-01, 5.8876e-01, 7.3509e-01,
         1.4374e-01, 8.0521e-01, 6.7097e-01, 8.9204e-01, 3.3718e-01, 6.7152e-01,
         2.7234e-01, 4.4115e-01, 1.6760e-01, 1.1650e-01, 3.9044e-01, 9.7525e-01,
         4.9959e-01, 1.1361e-01, 2.2119e-01, 6.3246e-01, 6.8087e-01, 4.7144e-01,
         4.9005e-01, 4.4908e-01, 2.3712e-01, 2.1986e-01, 8.4413e-01, 6.1361e-01,
         7.7509e-01, 2.3190e-01, 9.8642e-01, 8.2264e-01, 3.6192e-02, 1.1841e-02,
         5.3125e-01, 3.4463e-02, 8.7931e-01, 8.9996e-02, 2.4062e-01, 2.2132e-01,
         4.7331e-01, 7.9189e-01, 3.1757e-01, 4.6911e-01, 7.4004e-01, 5.3422e-01,
         9.1961e-01, 7.4906e-02, 4.7276e-01, 3.7888e-01, 4.7304e-01, 6.6491e-02,
         6.0500e-01, 3.3116e-01, 1.5697e-02, 8.6686e-01, 9.9969e-02, 5.2096e-01,
         2.3376e-01, 4.7938e-01, 4.4359e-01, 7.1026e-01, 1.8015e-01, 9.2361e-01,
         5.9958e-01, 6.6749e-01, 8.3832e-01, 7.8779e-01],
        [3.6145e-03, 7.1832e-01, 6.3694e-01, 1.2812e-01, 6.8437e-01, 2.0799e-01,
         6.4701e-01, 6.7515e-01, 3.0418e-01, 1.6274e-01, 2.8701e-01, 8.9361e-01,
         5.9699e-01, 2.1621e-01, 5.0927e-01, 7.4555e-01, 9.9762e-01, 3.1088e-01,
         5.4361e-01, 1.6153e-02, 8.1851e-01, 5.8178e-01, 2.9441e-01, 9.2007e-01,
         4.4109e-01, 5.4025e-01, 7.9749e-01, 4.4659e-01, 5.8990e-01, 2.0249e-01,
         5.3371e-02, 1.6997e-01, 8.1190e-01, 2.1844e-01, 3.8802e-01, 5.8872e-01,
         4.8252e-01, 2.6930e-01, 7.1882e-01, 6.0977e-01, 7.2841e-01, 6.8975e-02,
         4.4360e-01, 2.8807e-02, 5.3145e-01, 9.8784e-01, 1.4338e-02, 1.5627e-01,
         4.3143e-01, 2.4131e-01, 2.5731e-04, 7.6741e-01, 1.0832e-01, 2.7159e-01,
         2.0133e-01, 3.4780e-01, 6.8586e-01, 1.3100e-01, 7.9859e-02, 8.3896e-01,
         9.6003e-01, 9.6232e-01, 3.5670e-01, 9.9271e-01, 3.4787e-01, 2.1934e-02,
         6.1646e-01, 6.9655e-01, 7.5841e-01, 6.3881e-01, 9.1731e-01, 2.4031e-01,
         4.9716e-01, 1.2627e-01, 1.4756e-01, 7.1506e-01, 4.3376e-01, 2.6383e-01,
         4.2154e-01, 5.8208e-01, 1.7096e-01, 9.3484e-01, 9.5241e-01, 4.4751e-01,
         6.4243e-01, 9.1548e-01, 3.3412e-01, 5.1734e-01, 8.2012e-01, 1.8547e-01,
         6.2867e-01, 5.7414e-01, 6.1220e-01, 1.4542e-01, 4.5809e-01, 4.0166e-02,
         7.8735e-01, 8.2243e-01, 3.8098e-01, 9.1131e-01],
        [7.2266e-01, 8.2333e-01, 7.8614e-01, 6.9749e-01, 5.4023e-01, 6.5877e-01,
         2.4436e-01, 7.4040e-01, 3.8202e-01, 7.2957e-02, 7.7740e-01, 5.6450e-01,
         5.8614e-01, 4.1266e-01, 1.4654e-01, 9.1465e-01, 8.9241e-01, 5.7104e-01,
         8.7124e-01, 9.3570e-02, 4.6410e-01, 8.7251e-01, 6.5429e-02, 6.3580e-01,
         1.3031e-02, 2.8597e-01, 1.5957e-02, 9.6258e-01, 9.5709e-01, 9.7842e-01,
         3.8529e-02, 7.2645e-01, 7.4339e-01, 7.8006e-01, 1.7390e-02, 5.8046e-01,
         6.5155e-01, 9.6733e-01, 8.2268e-01, 7.8843e-01, 2.7005e-01, 4.9848e-01,
         4.1757e-01, 1.2939e-01, 3.3711e-01, 5.2721e-01, 9.2481e-01, 7.0528e-01,
         2.3463e-01, 2.7003e-01, 2.2138e-01, 5.2428e-01, 2.8373e-01, 1.2453e-01,
         9.3249e-02, 7.1050e-02, 4.5726e-01, 4.8249e-02, 8.3857e-01, 4.4419e-01,
         3.2105e-01, 7.5506e-01, 4.6338e-01, 1.7487e-01, 4.2511e-02, 6.9565e-02,
         7.6037e-01, 4.3415e-01, 3.6334e-01, 8.4151e-01, 6.3815e-01, 6.2322e-01,
         2.6379e-01, 3.2484e-01, 6.0471e-01, 9.2881e-01, 9.2061e-01, 5.7712e-01,
         5.0019e-01, 7.4033e-01, 7.0352e-02, 2.1742e-01, 1.9927e-01, 8.4661e-01,
         1.7178e-01, 3.9395e-01, 5.8877e-01, 5.7316e-01, 1.4482e-01, 4.6781e-01,
         6.2531e-01, 3.7276e-01, 2.8889e-01, 1.7349e-01, 1.8404e-02, 2.8089e-01,
         1.8556e-01, 8.6549e-01, 2.0254e-01, 4.7955e-01],
        [1.6583e-01, 8.7001e-01, 8.1745e-01, 4.3628e-01, 9.2811e-01, 1.3903e-01,
         8.6492e-01, 2.9965e-01, 9.1516e-01, 8.5886e-01, 7.1457e-01, 6.3053e-01,
         5.6314e-01, 8.2828e-02, 8.9765e-01, 5.7264e-01, 7.3879e-01, 2.3932e-03,
         5.3045e-01, 2.3282e-02, 6.1363e-01, 8.8849e-01, 1.2305e-01, 9.7665e-01,
         7.0245e-03, 7.0034e-02, 8.8321e-01, 2.0111e-01, 8.6727e-01, 1.5655e-01,
         4.0427e-01, 8.1785e-01, 1.4904e-01, 2.5523e-01, 1.6202e-02, 5.6103e-01,
         8.9245e-01, 8.3501e-01, 7.7954e-01, 5.2842e-01, 9.9908e-01, 2.7543e-01,
         5.0787e-01, 5.9155e-01, 9.6129e-01, 2.7114e-01, 2.6542e-01, 6.3262e-01,
         8.0960e-01, 5.2246e-01, 6.0527e-01, 8.3036e-01, 6.8261e-01, 1.1562e-01,
         1.3438e-01, 7.3527e-01, 6.4233e-01, 9.7930e-01, 6.9291e-01, 1.8861e-01,
         1.9099e-01, 9.4397e-01, 7.1821e-02, 2.3936e-01, 1.9417e-01, 3.8864e-01,
         1.6996e-01, 2.9781e-01, 8.9587e-01, 8.8212e-01, 5.5760e-01, 5.2153e-01,
         2.3198e-01, 9.9431e-01, 6.0470e-01, 2.3555e-01, 6.5524e-01, 6.0355e-01,
         5.4428e-01, 5.3432e-01, 3.0228e-01, 2.6389e-01, 6.4815e-01, 3.7416e-01,
         1.9997e-01, 9.1676e-01, 7.1323e-01, 2.7986e-01, 4.0755e-01, 2.9395e-01,
         9.4653e-03, 4.9331e-01, 7.1075e-01, 9.3095e-01, 7.9794e-01, 9.5633e-02,
         5.8701e-01, 1.9304e-01, 6.3333e-01, 3.5801e-01],
        [4.7529e-02, 8.2987e-01, 7.8228e-01, 1.3190e-01, 2.9728e-01, 1.4871e-01,
         5.7609e-01, 3.6935e-01, 9.5888e-01, 8.1937e-01, 2.1223e-01, 6.8114e-01,
         2.3648e-01, 6.1574e-01, 2.7558e-01, 7.1343e-01, 6.2346e-01, 8.7397e-02,
         6.7057e-01, 1.7403e-01, 6.8983e-01, 3.2010e-01, 4.5905e-01, 9.1214e-01,
         6.6665e-01, 4.2741e-01, 4.4329e-02, 6.9334e-01, 7.7859e-01, 1.4305e-01,
         7.6589e-01, 6.2519e-01, 4.0628e-01, 4.5913e-01, 2.6554e-01, 7.8223e-01,
         6.9766e-01, 5.9012e-01, 2.2534e-01, 7.6478e-01, 4.6316e-01, 4.3933e-01,
         1.5935e-01, 3.8244e-01, 2.3926e-01, 5.3176e-01, 8.6189e-01, 6.6293e-01,
         1.9735e-01, 9.8304e-01, 5.4601e-01, 5.7853e-01, 9.1844e-01, 4.4039e-01,
         3.0161e-01, 2.9849e-01, 9.3575e-01, 4.3387e-01, 8.5619e-01, 9.2436e-01,
         5.8551e-01, 7.0167e-01, 9.4760e-01, 2.7051e-01, 3.9353e-01, 3.0136e-01,
         3.6005e-01, 5.5214e-01, 5.5466e-01, 9.4974e-01, 2.0626e-01, 1.5771e-01,
         9.4492e-01, 2.9970e-01, 5.9789e-01, 9.0244e-01, 1.8304e-01, 7.9067e-01,
         6.0511e-01, 4.8535e-01, 1.0417e-01, 6.5007e-02, 6.4734e-01, 2.6149e-01,
         4.6905e-01, 4.7624e-01, 3.2607e-01, 9.5666e-01, 6.5883e-01, 5.1043e-01,
         9.8921e-01, 9.8326e-01, 6.4763e-01, 8.5193e-01, 1.8035e-01, 6.5715e-01,
         6.2093e-01, 6.1664e-01, 7.0738e-01, 3.8245e-01]])
2. a.repeat(10,1)
tensor([[0.9791, 0.4217, 0.8602,  ..., 0.7093, 0.7330, 0.0790],
        [0.7247, 0.4770, 0.8605,  ..., 0.0091, 0.4644, 0.7126],
        [0.4614, 0.3981, 0.8112,  ..., 0.3823, 0.6546, 0.3442],
        ...,
        [0.7227, 0.8233, 0.7861,  ..., 0.8655, 0.2025, 0.4795],
        [0.1658, 0.8700, 0.8175,  ..., 0.1930, 0.6333, 0.3580],
        [0.0475, 0.8299, 0.7823,  ..., 0.6166, 0.7074, 0.3824]])

All numbers are kept to four decimal places. I have a big error in my calculations.

**Comment by fmassa** [comment]
This is just the print that rounded up the values. You can configure the printing options with `torch set_printopts` or something like that
