### ISSUE TITLE
torch.jit.trace_module creates only one method

### ISSUE THREAD

**Issue by manipopopo** [pytorch/pytorch#23122]
## 🐛 Bug

`torch.jit.trace_module` creates only one method as [`return` is in the `for` loop](https://github.com/pytorch/pytorch/blob/77353636de32a207cf0a332395f91011bc2f07fb/torch/jit/__init__.py#L890-L906):

```python
for method_name, example_inputs in inputs.items():
    # ...
    
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
    
    # ...
    
    return module
```

## To Reproduce

```python
import torch
from torch import nn


class Module(nn.Module):

    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x

    def mul_100(self, x):
        return x * 100

    def add_100(self, x):
        return x + 100


x = torch.ones(1)
module = torch.jit.trace_module(Module(),
                                {'forward': x, 'mul_100': x, 'add_100': x})
# print False
print(all(hasattr(module, method_name)
          for method_name in ['forward', 'mul_100', 'add_100']))
```

## Expected behavior
The `module` has methods `forward`, `mul_100` and `add_100`.

## Environment

Collecting environment information...
PyTorch version: 1.2.0.dev20190719
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

**Comment by zdevito** [comment]
Bumping to high priority. This is an easy fix and but needs to be in by the release or trace_modules does not work.

**Comment by Krovatkin** [comment]
will be fixed as https://github.com/pytorch/pytorch/pull/23358 lands

**Comment by SsnL** [comment]
fixed by https://github.com/pytorch/pytorch/pull/23358
