### ISSUE TITLE
[BUG]pytorch with cudnn7.6.1, set_storage is not allowed on Tensor created from .data or .detach()

### ISSUE THREAD

**Issue by illcat** [pytorch/pytorch#23126]
File "~/python3.7/site-packages/torch/nn/modules/rnn.py", line 123, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: set_storage is not allowed on Tensor created from .data or .detach()

Pytorch does not seem to support cudnn7.6.1.

**Comment by soumith** [comment]
this has nothing to do with CuDNN 7.6.1.

Also, please use our bug report template and create a new bug report
