### ISSUE TITLE
using and working on libaten isolated for development

### ISSUE THREAD

**Issue by quickwritereader** [pytorch/pytorch#23136]
Hi
I would like to know how I could test and work  on  aten. 
I tried to compile it isolated but then I've read that on the current version it is impossible.
Which version I can use for that purpose. I want to work on vector headers mostly for a different architecture and to see how generates them and check for correctness.
`/aten/src/ATen/cpu/vec256/` 
I don't want to compile the whole library for that purpose.
It would be also good if someone could provide me minimalist options for building cpu c++ library version. Or Readme or info section where it is mentioned
thanks for guidance in advance. Sorry if it is a repetitive question and if I skipped ReadMe section for that purpose.

**Comment by soumith** [comment]
ATen is no longer compilable isolated. You probably are looking for `libtorch` compilation.

Best advice we have is https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#c-development-tips
