### ISSUE TITLE
DistributedDataParallel: resume training from a checkpoint results in additional processes on GPU 0

### ISSUE THREAD

**Issue by qchenclaire** [pytorch/pytorch#23138]
Hi,

When I was trying the[ imagenet example](https://github.com/pytorch/examples/tree/master/imagenet) with DistributedDataParallel, using single node with 4 gpus, I found that when I add `--resume /path/to/checkpoint `to the command, gpu 0 has additional processes like below, the pid of each process is exactly the same as running on every other gpu, and each process consumes ~725M. These additional processes keep lingering on gpu 0 instead of disapear when loading finished. Is there any way to solve this? If there are 8 gpus, that means ~5G on gpu 0 are wasted.

> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0     62250      C   /usr/bin/python3.6                          4903MiB |
> |    0     62251      C   /usr/bin/python3.6                           725MiB |
> |    0     62252      C   /usr/bin/python3.6                           725MiB |
> |    0     62253      C   /usr/bin/python3.6                           725MiB |
> |    1     62251      C   /usr/bin/python3.6                          4693MiB |
> |    2     62252      C   /usr/bin/python3.6                          4693MiB |
> |    3     62253      C   /usr/bin/python3.6                          4693MiB |
> 
> 

If I train from scratch, there is no such issue.

> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      2080      C   /usr/bin/python3.6                          4687MiB |
> |    1      2081      C   /usr/bin/python3.6                          4687MiB |
> |    2      2082      C   /usr/bin/python3.6                          4687MiB |
> |    3      2083      C   /usr/bin/python3.6                          4687MiB |
>

**Comment by panfeng-hover** [comment]
Hi @qchenclaire, I met the similar issue, could you share your solution? Thanks!

**Comment by panfeng-hover** [comment]
I solved it, for my case, if you load the model state dict before apply ddp to model, you need to specify the `checkpoint = torch.load(checkpoint_path, map_location='cuda:{}'.format(opts.local_rank))`.

**Comment by MJITG** [comment]
> I solved it, for my case, if you load the model state dict before apply ddp to model, you need to specify the cuda device as the local rank. `checkpoint = torch.load(checkpoint_path, map_location='cuda:{}'.format(opts.local_rank))`.

Works for me! Thanks!

**Comment by arunsubk** [comment]
> I solved it, for my case, if you load the model state dict before apply ddp to model, you need to specify the cuda device as the local rank. `checkpoint = torch.load(checkpoint_path, map_location='cuda:{}'.format(opts.local_rank))`.

Hi, In your reply, the statement, "if you load the model state dict BEFORE you apply ddp.." sounds like, there is a choice of apply AFTER you apply ddp. Is it possible to load model state dict after applying ddp? If yes, would still face the issue of gpu:0 being burdened with extra memory etc?

**Comment by brando90** [comment]
> I solved it, for my case, if you load the model state dict before apply ddp to model, you need to specify the cuda device as the local rank. `checkpoint = torch.load(checkpoint_path, map_location='cuda:{}'.format(opts.local_rank))`.

what about just loading it to CPU and then doing `mdl.to(gpu_id)` for each process and then for each process calling `DDP(model)`?

**Comment by brando90** [comment]
> 

why do you want to do this? What you want is all the processes to have the same model. So load them in all first then call ddp to make sure they are in sync - is my guess why the original solution works.

**Comment by brando90** [comment]
fyi, related question: https://stackoverflow.com/questions/70386800/what-is-the-proper-way-to-checkpoint-during-training-when-using-distributed-data
