### ISSUE TITLE
Does tensors got from torch.distributed.all_gather in order?

### ISSUE THREAD

**Issue by charlesCXK** [pytorch/pytorch#23144]
## ❓ Do tensors got from torch.distributed.all_gather in order?

If I use 16 GPUs to train a model with torch.distributed, the size of tensor on each GPU is (1, 3, 24, 24). I want to use **torch.distributed.all_gather** to gather all the tensors to get a tensor named **result** with size (16, 3, 24, 24). Now here is my question: Do tensors got from 16 GPUs in order? That is, if a tensor is from the 1-th GPU, then it should be placed in the **result[1, :, :, :]**. if a tensor is from the 8-th GPU, then it should be placed in the **result[8, :, :, :]**. Does  torch.distributed.all_gather implement this? Thank you!

**Comment by pietern** [comment]
Please use https://discuss.pytorch.org/ for future questions you may have. This is used for tracking issues.

To answer your question, though: yes, that is correct. But double check the API for `all_gather`, since you don't get back a single tensor, but a list of tensors. If you want to combine them into a single tensor, check out [`torch.cat`](https://pytorch.org/docs/stable/torch.html#torch.cat).

**Comment by ZhiyuanChen** [comment]
> To answer your question, though: yes, that is correct. But double check the API for `all_gather`, since you don't get back a single tensor, but a list of tensors. If you want to combine them into a single tensor, check out [`torch.cat`](https://pytorch.org/docs/stable/torch.html#torch.cat).

Hi, thank you for answering. But in our expeiments, it looks like returned in random order. Is it a bug?

**Comment by linminhtoo** [comment]
Any update on this? I am intending to do a similar operation and have a use case where I absolutely need to be sure of the final order of tensors

**Comment by GMonster0905** [comment]
> > To answer your question, though: yes, that is correct. But double check the API for `all_gather`, since you don't get back a single tensor, but a list of tensors. If you want to combine them into a single tensor, check out [`torch.cat`](https://pytorch.org/docs/stable/torch.html#torch.cat).
> 
> Hi, thank you for answering. But in our expeiments, it looks like returned in random order. Is it a bug?
I also find the gathered tensors are in random order rather than following the rank order, is there a method to gather tensors in order up to now ?

**Comment by ZhiyuanChen** [comment]
@pietern
