### ISSUE TITLE
Make Module:: register_module public in the c++ frontend?

### ISSUE THREAD

**Issue by joker-xii** [pytorch/pytorch#23140]
## 🚀 Feature
Make protected functions public in torch::nn::Module

## Motivation

In python they are public methods

## Pitch

As described in the title

## Additional context
None

**Comment by soumith** [comment]
cc: @yf225

**Comment by joker-xii** [comment]
> cc: @yf225

Thanks for the response, could you also make `register_parameter` and `register_buffer` public?
