### ISSUE TITLE
'Variable' object has no attribute 'shape' [v0.2]

### ISSUE THREAD

**Issue by miguelvr** [pytorch/pytorch#2315]
Apparently x.shape works if x is a tensor, but not if it is a Variable. 
It is possible to do x.data.shape and x.size() is x is a Variable, but not x.shape
This should be the same for consistency, no matter if Variable or Tensor.

**Comment by fmassa** [comment]
This has just been fixed on master, and will be present in the next release https://github.com/pytorch/pytorch/pull/2306

**Comment by acgtyrant** [comment]
What is the next release, 0.3 or 0.2.x?

**Comment by fmassa** [comment]
@acgtyrant probably 0.2.x
