### ISSUE TITLE
[feature request] Load pretrained layer weight by name

### ISSUE THREAD

**Issue by Lseu** [pytorch/pytorch#23155]
Name parameters can be added when defining the network layer to facilitate loading the specified layer when loading the pre-training weight.

**Comment by gchanan** [comment]
I don't know how to interpret this request (for example, I don't know which API you are referring to, python, JIT, C++).  Perhaps you could give some pseudo-code for what you are trying to do.

**Comment by ifedan** [comment]
Please kindly feel encouraged to reopen this issue with more details.
