### ISSUE TITLE
Advanced Indexing Error

### ISSUE THREAD

**Issue by snowyday** [pytorch/pytorch#2316]
Grateful thanks for new various features!

Advanced Indexing does not support vector?:

    >>> x = torch.Tensor(5)
    >>> x[[0, 3]]
   Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
  TypeError: indexing a tensor with an object of type list. The only supported types are integers, slices,, numpy scalars and torch.LongTensor or torch.ByteTensor as the only argument.

**Comment by chenzhekl** [comment]
Related to #2305. Use `x[[0, 3],]` instead.

**Comment by snowyday** [comment]
@chenzhekl Thank you!!
But, I think the expression is non-trivial.

**Comment by killeent** [comment]
@snowyday by definition, advanced indexing requires a sequence, so the behavior without sequences in PyTorch is unchanged. The currently supported way of doing what you want is:

```
x = torch.Tensor(5)
x[torch.LongTensor([0, 3])]
```

**Comment by fmassa** [comment]
@killeent Numpy seems not to use tuples for advanced indexing, but lists or arrays
So
```python
a = np.random.rand(3,3)
a[[1, 2]] == a[np.array([1, 2])] != a[(1, 2)]
```
Can't we modify the behavior in pytorch to be more in line with numpy's?

**Comment by apaszke** [comment]
We should fix that to work as in numpy

**Comment by killeent** [comment]
@fmassa can you clarify what the difference is in behavior for PyTorch?

**Comment by killeent** [comment]
Actually, to correct myself, I guess this is considered a form of advanced indexing, so I will address this either way...

**Comment by vadimkantorov** [comment]
A few other things that don't work:
```python
a = torch.zeros(2, 2)
a[[0,1], 0] # doesn't work
a[torch.LongTensor([0, 1]), 0] # doesn't work
a[torch.LongTensor([0, 1])][:, 0] # works

a[[0, 1]][:, 0] # doesn't work
a[[0, 1], :1] # doesn't work
a[[0, 1], 0:1] # doesn't work
a[[0, 1], 0:2] # works
```

**Comment by killeent** [comment]
@vadimkantorov this is to be expected. We only support a subset of advanced indexing - including no mixing of basic and advanced indexing, or support for non-empty slice objects.

**Comment by snowyday** [comment]
@killeent Thank you so much for #2323!

**Comment by fmassa** [comment]
@micklexqg are you using pytorch 0.4?

**Comment by micklexqg** [comment]
@fmassa , no, maybe 0.2. so it need to be under pytorch 0.4?

**Comment by fmassa** [comment]
Preferably. Full support for advanced indexing was added in 0.4
Previous versions had some support for it, but many cases were missing
