### ISSUE TITLE
[BUG] CosineAnealingLr -> CosineAnealingLR

### ISSUE THREAD

**Issue by maaft** [pytorch/pytorch#23160]
## Issue description

**CosineAnealingLr** in `torch/optim/lr_scheduler.pyi` must be renamed to **CosineAnealingLR**

## Code example

from torch.optim.lr_scheduler import CosineAnealingLr

## Error Message
ImportError: cannot import name 'CosineAnnealingLr' from 'torch.optim.lr_scheduler'

## System Info
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.1

Versions of relevant libraries:
[pip] efficientnet-pytorch==0.3.0
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] efficientnet-pytorch      0.3.0                    pypi_0    pypi
[conda] mkl                       2019.3                      199  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torchvision               0.3.0                    pypi_0    pypi

**Comment by pbelevich** [comment]
@maaft fixed, please test
