### ISSUE TITLE
What is the torchvision version  for pytorch-nightly? Use 0.3.0 to report errors

### ISSUE THREAD

**Issue by zymale** [pytorch/pytorch#23218]
The official website does not provide the torchvison version installation method.
Here is the error message  when torchvison 0.3.0 is used.
torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeERKNS_6TensorE

That should be caused by the mismatch version  between pytorch-nightly and torchvision  0.3.0.

**Comment by peterjc123** [comment]
It should be `torchvision-nightly` that matches with `pytorch-nightly`, but they are not provided currently.

**Comment by abster95** [comment]
I tried installing it with pip as per [this issue](https://github.com/pytorch/vision/issues/833#issuecomment-500681269), but now I get `undefined symbol: __cudaRegisterFatBinaryEnd` when importing `_C`.

I did a similar thing on June 25th. It worked then.

Any known fix for this?

**Comment by gchanan** [comment]
@fmassa do we document what to do here?

**Comment by abster95** [comment]
I finally solved this by building from source with `pip install -e .`
Before running that make sure to upgrade `pytorch-nightly` and `cudatoolkit` to use `cuda-10-0`.

Note: this will **not** work if you have `cuda-10-1` on your system when building `torchvision` since you'd get version mismatch between `pytorch-nightly` and `torchvision`.

Tested only on `ubuntu 18.04`.

**Comment by zymale** [comment]
> I finally solved this by building from source with `pip install -e .`
> Before running that make sure to upgrade `pytorch-nightly` and `cudatoolkit` to use `cuda-10-0`.
> 
> Note: this will **not** work if you have `cuda-10-1` on your system when building `torchvision` since you'd get version mismatch between `pytorch-nightly` and `torchvision`.
> 
> Tested only on `ubuntu 18.04`.

@abster95   you build pytorch from source or just torchvision? or  both of them.

**Comment by abster95** [comment]
I installed `pytorch-nightly` from conda with:
`conda install pytorch-nightly cudatoolkit=10.0 -c pytorch`

I then cloned the `torchvision` repo and ran `pip install -e .` inside the repo. I guess this would also work if you do `pip install git+https://github.com/pytorch/vision.git`, but I haven't tried it.

**Comment by youkaichao** [comment]
Just a reminder (what I encountered just now): one should uninstall previous ``torchvision`` when they build the ``torchvision`` from source, or they can mix up and mess up everything.

**Comment by peterjc123** [comment]
There are nightlies for torchvision under Windows now.

**Comment by GMetola** [comment]
I have **problems** using Pytorch with my Geforce RTX 3060, (**sm_86**).
> GeForce RTX 3060 with CUDA capability sm_86 is not compatible with the current PyTorch installation.

I tried to install with help of https://github.com/pytorch/pytorch/issues/23218#issuecomment-514576736 :
-  Create a new venv, based on python 3.7.10. Activate it.
- conda install pytorch-nightly cudatoolkit=10.0 -c pytorch  (I also did it without the "=10.0")
Now pytorch detects the sm_86 with no errors, **problem sm_86 solved with pytorch-nightly**
`torch.cuda.get_device_name()
'GeForce RTX 3060'`

Now, I have a **problem with torchvision**.
I tried installing torchvision version 0.3.0, from https://github.com/pytorch/vision, but an error rose: 
> OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\metol\.conda\envs\env_torch-nightly\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

I tried installing torchvision at origin/mater, but another error rose:
> ModuleNotFoundError: No module named 'torch.utils.hipify'

Here is the list of packages installed:
```
(env_torch-nightly) C:\repo\vision>conda list
packages in environment at C:\Users\metol\.conda\envs\env_torch-nightly:
Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2021.1.19            haa95532_1
certifi                   2020.12.5        py37haa95532_0
cffi                      1.14.5           py37hcd4344a_0
cudatoolkit               10.0.130                      0
intel-openmp              2020.2                      254
mkl                       2020.2                      256
mkl-service               2.3.0            py37h196d8e1_0
mkl_fft                   1.3.0            py37h46781fe_0
mkl_random                1.1.1            py37h47e9c7a_0
ninja                     1.10.2           py37h6d14046_0
numpy                     1.19.2           py37hadc3359_0
numpy-base                1.19.2           py37ha3acd2a_0
openssl                   1.1.1j               h2bbff1b_0
pillow                    8.1.2                    pypi_0    pypi
pip                       21.0.1           py37haa95532_0
pycparser                 2.20                       py_2
python                    3.7.10               h6244533_0
pytorch-nightly           1.0.0.dev20190328 py3.7_cuda100_cudnn7_0    pytorch
setuptools                52.0.0           py37haa95532_0
six                       1.15.0           py37haa95532_0
sqlite                    3.33.0               h2a8f88b_0
torch                     1.8.0                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py37_0
zlib                      1.2.11               h62dcd97_4
```
