### ISSUE TITLE
Single GPU per Node for Distributed Training is not working

### ISSUE THREAD

**Issue by ArEsKay3** [pytorch/pytorch#2321]
I am trying to use the imagenet example to run distributed training across compute nodes. However, when each node only has one GPU attached I'm seeing problems running the example. The failure I see is related to the module expecting CPU Tensors, but getting CUDA Tensors. This problem goes away if I use 2 GPUs per node. My guess is that it has something to do with the fact that when there is only one device per node the code skips all parameter syncing?

```python    
def forward(self, *inputs, **kwargs):
        if len(self.device_ids) == 1:
            return self.module(*inputs, **kwargs)
        inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
        self._sync_params()
        outputs = self.parallel_apply(self._module_copies, inputs, kwargs)
        return self.gather(outputs, self.output_device) 
```

**Comment by soumith** [comment]
ah yes this is a small bug in the imagenet example where it activates the DataParallel route only if its gpu > 1. moving the if conditionals around should fix it.
thanks for reporting

**Comment by ArEsKay3** [comment]
Oh really? I see it only conditioned on the world_size > 1 which it is in this case, but I didn't see a condition based on CUDA device count.

**Comment by Scitator** [comment]
@soumith 
Could you please provide correct code for imagnet distributed training?
It also would be great, if someone updates readme for this example. For now, it's unclear how to run it correctly. Thanks!

**Comment by Scitator** [comment]
@ArEsKay3 @soumith Have anyone solve this issue?

**Comment by ArEsKay3** [comment]
I haven't taken a closer look yet. But was waiting for confirmation about my previous comment re: world_size argument.
