### ISSUE TITLE
C++ strange model load error

### ISSUE THREAD

**Issue by iamwangyabin** [pytorch/pytorch#23219]
## To Reproduce

Firstly I want to say I had already successfully load my first model from ".pt",so there should not problem I don't know how to load pytorch model in c++ programe.
Then, The thrown error is as follows:
```
terminate called after throwing an instance of 'c10::Error'
  what():  INVALID_ARGUMENT:main_module.submodules[0][19]: Cannot find field. (deserialize at /home/wang/software/pytorch/torch/csrc/jit/import.cpp:95)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f2951ac043a in /home/wang/software/pytorch/torch/lib/tmp_install/lib/libc10.so)
frame #1: <unknown function> + 0x62701f (0x7f296b67c01f in /home/wang/software/pytorch/torch/lib/tmp_install/lib/libtorch.so.1)
frame #2: torch::jit::load(std::istream&, c10::optional<c10::Device>) + 0x392 (0x7f296b67c662 in /home/wang/software/pytorch/torch/lib/tmp_install/lib/libtorch.so.1)
frame #3: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>) + 0x70 (0x7f296b67c820 in /home/wang/software/pytorch/torch/lib/tmp_install/lib/libtorch.so.1)
frame #4: main + 0xff4 (0x408e94 in ./rfnet)
frame #5: __libc_start_main + 0xf0 (0x7f295116a830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: _start + 0x29 (0x409869 in ./rfnet)
```
My model is a very simply network :
```

class HardNetNeiMask(nn.Module):
    def __init__(self, MARGIN, C):
        super(HardNetNeiMask, self).__init__()
        self.MARGIN = MARGIN
        self.C = C
        self.features = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(32, affine=False),
            nn.ReLU(),
            nn.Conv2d(32, 32, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(32, affine=False),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(64, affine=False),
            nn.ReLU(),
            nn.Conv2d(64, 64, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(64, affine=False),
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(128, affine=False),
            nn.ReLU(),
            nn.Conv2d(128, 128, kernel_size=8, bias=False),
            nn.BatchNorm2d(128, affine=False),
        )
    @staticmethod
    def input_norm(x):
        eps = 1e-8
        flat = x.view(x.size(0), -1)
        mp = torch.mean(flat, dim=1)
        sp = torch.std(flat, dim=1) + eps
        return (x - mp.detach().unsqueeze(-1).unsqueeze(-1).unsqueeze(-1).expand_as(x)
                ) / sp.detach().unsqueeze(-1).unsqueeze(-1).unsqueeze(1).expand_as(x)
    def forward(self, input):
        features = self.features(self.input_norm(input))
        x = features.view(features.size(0), -1)
        feature = x / torch.norm(x, p=2, dim=-1, keepdim=True)
        return feature
```
My first model which did't have any problem is a bigger network,I think there should be some bugs when jit dealing with my network but I cant find.

When I change the last conv layer with 8 x 8 width kernal size to two conv layers which have 3 x 3 and 4 
x 4 kernal sizes . The error was solved.
So I think must be some error in JIT which can't deal with big kernal .

## Environment
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 7.5.17
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 390.87
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl_fft                   1.0.12           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.1.0           py3.6_cuda9.0.176_cudnn7.5.1_0    pytorch
[conda] torchvision               0.3.0           py36_cu9.0.176_1    pytorch

**Comment by zdevito** [comment]
This looks like it might be a protobuffer error reporting a missing field in the file format. Is it possible that the model is being saved with a newer version of pytorch than the C++ library that is loading it?

**Comment by iamwangyabin** [comment]
@zdevito Thank you,you are right ,I recompile libtorch to V 1.1.0 as same as my pytorch version.and this error was solved!

**Comment by HZY302** [comment]
> @zdevito Thank you,you are right ,I recompile libtorch to V 1.1.0 as same as my pytorch version.and this error was solved!

Can you tell me how to load  libtorch V1.1.0
