### ISSUE TITLE
TorchScript model includes unused tensors

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#23220]
## 🐛 Bug

When exporting `inception_v3` via TorchScript the resulting file contains unreferenced tensors.

## To Reproduce

```
import torch
import torchvision
model = torchvision.models.inception_v3(pretrained=True).eval()
torch.save(model, 'inception_v3.pth')
torch.jit.trace(model, torch.rand([ 1, 3, 299, 299 ])).save('inception_v3.pt')
```

The generated TorchScript model `inception_v3.pt` contains `tensors/216` to `tensor/223` which are not referenced in `code/inception_v3.py`.

<a href="http://github.com/lutzroeder/netron"><img width="1136" alt="screenshot" src="https://user-images.githubusercontent.com/438516/61692631-dead5a80-ace2-11e9-9600-c19de1e5d173.png"></a>

**Comment by zdevito** [comment]
A traced model will contain all tensors that are either used as constants in the code or exist as buffers/parameters/attributes on the model.  Are these tensors not referenced in any of those locations?

**Comment by lutzroeder** [comment]
The tensors are referenced in `model.json` in modules that are not referenced in code. Shouldn't they get removed from the file?

**Comment by eellison** [comment]
Pretty sure this still repros. I tried the model and there 579 tensors saved, and the model code just looked like this:
```
class Module(Module):
  __parameters__ = ["weight", ]
  weight : Tensor
  training : bool
  def forward(self: __torch__.torch.nn.modules.module.Module,
    input: Tensor) -> Tensor:
    input0 = torch._convolution(input, self.weight, None, [2, 2], [0, 0], [1, 1], False, [0, 0], 1, False, False, True)
    return input0
```
