### ISSUE TITLE
Maybe there is a problem when using random.shuffle()

### ISSUE THREAD

**Issue by LaoYang1994** [pytorch/pytorch#23222]
## 🐛 Bug

When I applied the random.shuffle to a 1-D tensor, the num in the tensor was changed.

## To Reproduce

1.Do as follows:
->a = torch.arange(10)
->random.shuffle(a)

## Expected behavior
Expected: 
  tensor([1, 8, 5, 3, 9, 0, 2, 6, 4, 7])
but I got:
  tensor([0, 1, 2, 1, 4, 5, 1, 5, 7, 4])

I am not sure whether it's a bug.

## Environment

Python 3.7.0
torch 1.1.0

**Comment by vishwakftw** [comment]
This is pertinent to this issue https://github.com/pytorch/pytorch/issues/17008.

The implementation of random.shuffle performs pythonic element swapping, which causes the issue.

**Comment by LaoYang1994** [comment]
@vishwakftw Thanks.

**Comment by soumith** [comment]
closing in favor of #17008
