### ISSUE TITLE
Add collective communication APIs for Python objects. 

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#23232]
## 🚀 Feature

Support `gather`, `all_gather`, `broadcast`, and `scatter` general python objects. Instead of overloading existing API, it might be clearer to make them explicit, e.g.: `gather_object`, `all_gather_object`, `broadcast_object`, and `scatter_object`.

## Motivation

Sharing objects across processes is a very common use case. People actually started building their own solutions by serializing meta and object into tensors and then using tensor collective comm APIs to share them (see, `_broadcast_object ` in #22490, `_collect_worker_names` in #23228). 

## Pitch

Python object on different processes might not be of the same size. So this needs to be done in multiple steps:

1. Pickle local python object into byte tensors. 
2. Communicate the tensor sizes across processes. Then, each process allocates local buffer tensors using the max size.
3. Copy local tensor to the buffer tensor and communicate. 
4. Extract results from the buffer tensors and unpickle them back into Python objects.

cc @pietern @zhaojuanmao @pritamdamania87

**Comment by pietern** [comment]
This came up in https://discuss.pytorch.org/t/gathering-dictionaries-of-distributeddataparallel/51381.

**Comment by fmassa** [comment]
Another example of where `all_gather` is used with arbitrary Python objects is in [`maskrcnn_benchmark`](https://github.com/facebookresearch/maskrcnn-benchmark/blob/24c8c90efdb7cc51381af5ce0205b23567c3cd21/maskrcnn_benchmark/utils/comm.py#L48-L88)

**Comment by pietern** [comment]
@rohan-varma This one might be interesting to you.
