### ISSUE TITLE
Equations in the document do not display properly: Their LaTeX code is shown instead

### ISSUE THREAD

**Issue by xuhdev** [pytorch/pytorch#23294]
The current master document does not display equations properly. Rather, their LaTeX code is displayed. For example, [torch.sin()](https://pytorch.org/docs/master/torch.html#torch.sin).

**Comment by vishwakftw** [comment]
This seems to be a recent regression. Could https://github.com/pytorch/pytorch/commit/174f7a586fd5d3b7b5b185a52f31ebb021631f33 have caused it?

cc: @ezyang

**Comment by t-vi** [comment]
Wouldn't pre-rending KaTeX be a good alternative? I must admit node isn't my favourite build-dependency, but it still seems nicer than images.

**Comment by ezyang** [comment]
This is probably caused by the imgmath change. Investigating.

**Comment by ezyang** [comment]
It's because LaTeX isn't installed on the Docker image:

```
Jul 24 07:15:38 WARNING: LaTeX command 'latex' cannot be run (needed for math display), check the imgmath_latex setting
```

**Comment by ezyang** [comment]
@t-vi I don't think the sphinx-katex plugin supports prerendering. I asked about it here: https://github.com/hagenw/sphinxcontrib-katex/issues/11

**Comment by t-vi** [comment]
@ezyang should have thought you likely already considered it. Thank you!

**Comment by ezyang** [comment]
The LaTeX imgs do look pretty ugly (anti-aliasing isn't really working), so if we can figure out how to patch sphinxcontrib-katex to support prerendering I think we should definitely use it.

**Comment by t-vi** [comment]
From a cursory look one would need to popen2/3 the [cli](https://katex.org/docs/cli.html) in the [two rendering functions](https://github.com/hagenw/sphinxcontrib-katex/blob/ba0db20a7a15be1eb975d642d121d3faa867b8ae/sphinxcontrib/katex.py#L85-L102) which seem to just append to a string or so. The difficulty is probably configuring...

**Comment by xuhdev** [comment]
Do we have an interest in switching to imgmath? To make equations look nicer, we can set [imgmath_image_format](https://shimizukawa-sphinx.readthedocs.io/en/latest/ext/math.html#confval-imgmath_image_format) to svg.

Alternatively, `sphinx.ext.mathjax` should also work, but this requires a lot of work from browser.

**Comment by vishwakftw** [comment]
@xuhdev in https://github.com/pytorch/pytorch/pull/8848 we switched from `sphinx.ext.mathjax` to katex because `mathjax` was even slower.

**Comment by hagenw** [comment]
`mathjax` is indeed much slower, that was the main motivation in creating [sphinxcontrib-katex](https://github.com/hagenw/sphinxcontrib-katex) in the first place.

At the moment we are adding pre-rendering as an option to it as well, see https://github.com/hagenw/sphinxcontrib-katex/pull/13
So, maybe this would be one solution afterwards.

**Comment by ezyang** [comment]
Yeah, given how nicely prerendered katex is shaping up, I think I'm going to just revert the imgmath change and then wait until we can deploy using prerendered katex.

**Comment by hagenw** [comment]
Server side pre-rendering is now included in sphinxcontrib-katex:
https://github.com/hagenw/sphinxcontrib-katex/releases/tag/0.5.0

Thanks for suggesting it.

**Comment by ezyang** [comment]
This particular bug is fixed, we'll continue the rest of the discussion at #20984
