### ISSUE TITLE
Potentially missing else

### ISSUE THREAD

**Issue by alexeyr** [pytorch/pytorch#23300]
### Issue 1

In https://github.com/pytorch/pytorch/blob/f924fc6eb10577cc119ab388873ebdb7c8f57151/torch/lib/c10d/Store.cpp#L12-L17
the `if` has no effect because line 17 always reassigns `timeout_`. So either it can be removed or it should be

    timeout_ = timeout.count() == 0 ? kNoTimeout : timeout

Unless I am misunderstanding something?

### Issue 2

In https://github.com/pytorch/pytorch/blob/9a281451ed7f00d052212695ea112ebe872776f6/caffe2/quantization/server/tanh.cc#L17-L48
all code after line 22 is unreachable. This doesn't seem to be intentional (maybe someone added it for testing and forgot to remove it?).

**Comment by mrshenli** [comment]
@pietern why do we need the `if` clause in `Store::setTimeout`? It seems to me [`kNoTimeout`](https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/Store.hpp#L15) is just `std::chrono::milliseconds::zero()`.

**Comment by pietern** [comment]
@mrshenli It can be removed. Thanks for noticing and creating the issue @alexeyr!

**Comment by alexeyr** [comment]
The second problem (in tanh.cc) doesn't seem to be fixed.

**Comment by pietern** [comment]
@alexeyr Can you create a separate issue for that?

**Comment by alexeyr** [comment]
@pietern Done: #23429
