### ISSUE TITLE
Can pytorch support the GPU acceleration of tree-structured RNN models?

### ISSUE THREAD

**Issue by penelope24** [pytorch/pytorch#2331]
As the title suggest, since tree-structured RNN such as tree-lstm has arbitrary batch size for each input, I want to know if pytorch are capable of GPU acceleration fro this situation?

**Comment by CDLuminate** [comment]
A typical CNN has a static computation graph and a fixed input size requirement. Such that the samples in a batch could be processed by every operator (e.g. conv2) simultaneously to speed up forward/backward pass.

Tree-LSTM will never have a static computation graph. Different sentences have different syntax trees -- they differ in both span and depth. Each sample must be forwarded and backwarded along to its tree individually. This makes acceleration difficult. In my fuzzy memory there is a paper in ICLR2017 which discusses about generating a tree from a embedding. That paper also declares that acceleration for such tree-structured algorithm is hard.

One idea is to process the samples in a batch with several parallel threads. I didn't investigate or try this, and I'm not sure the pytorch supports safely sharing a module to several threads.

**Comment by apaszke** [comment]
I can't think of anything that would prevent you from training TreeRNNs on GPUs.

Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
