### ISSUE TITLE
bitwise_not documentation is not rendering correctly

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#23311]
`torch.bitwise_not()
bitwise_not(input, out=None) -> Tensor

Computes the bitwise NOT of the given input tensor. The input must be of integer or Boolean types.

Parameters
{input} –

{out} –

Example:

>>> torch.bitwise_not(torch.tensor([-1, -2, 3], dtype=torch.int8))
tensor([ 0,  1, -4], dtype=torch.int8)`

See the substitutions are being displayed raw.

**Comment by jspisak** [comment]
cc @brianjo - Please add this to the list for 1.2 release.

**Comment by pbelevich** [comment]
fixed
