### ISSUE TITLE
[Feature Request] Gabor Layer

### ISSUE THREAD

**Issue by iKintosh** [pytorch/pytorch#23313]
## 🚀 Feature
Add new layer - Gabor Layer - to PyTorch library. It is a layer with learnable Gabor fuction parameters, where Gabor function generates 2D convolutional kernel, thus number of parameters stays the same no matter the kernel size.

## Motivation

I've made a research, you may find it on [arxiv](https://arxiv.org/abs/1904.13204).

This research on deep convolutional neural networks proposes a modified architecture that focuses on improving convergence and reducing training complexity. The filters in the first layer of network are constrained to fit the Gabor function. The parameters of Gabor functions are learnable and updated by standard backpropagation techniques. The proposed architecture was tested on several datasets and outperformed the common convolutional networks

## Pitch
Add new layer as standard layer to PyTorch library. I already implemented the layer using PyTorch, you may find code here: https://github.com/iKintosh/GaborNet .
However, I couldn't solve one problem: fix GaborLayer weights in evaluate or no_grads mode. 
The issue: https://github.com/iKintosh/GaborNet/issues/2

**Comment by gchanan** [comment]
Our general criteria for acceptance:

The method has to be well-established (we ask people to submit new or low-cited methods to https://github.com/pytorch/contrib )
For example, if you see #13213 above, we reject those at that point of time, as they were fresh off the press
The method has to match the paper
The method has to have a consistent and thoughtful interface
Sometimes, leaving a very well oiled and super high-touch API like optim.SGD as-is and putting advanced options, regularization specializations and other stuff into a separate API make sense as well, to de-risk newly introduced bugs to a very small set of people.

Given in this case there isn't a lot of citations, I'm going to close for now.
