### ISSUE TITLE
Can pytorch support GPU acceleration for tree-lstm models?

### ISSUE THREAD

**Issue by penelope24** [pytorch/pytorch#2335]
As mentioned in title, I want to make sure if pytorch can deal with the situation that each input in a batch has different shapes and thus different computation graphs.

**Comment by CDLuminate** [comment]
https://github.com/dasguptar/treelstm.pytorch

https://github.com/ttpro1995/TreeLSTMSentiment

Please don't open duplicated issue for discussion. Context will be missed.
Try to discuss about it here:  https://discuss.pytorch.org/
