### ISSUE TITLE
Fatal error gloo/transport/tcp/device.h: no such file or directory build from source

### ISSUE THREAD

**Issue by snippler** [pytorch/pytorch#23374]
## To Reproduce

1. Build from source on Raspberry Pi 4 B
2. I use flag NO_DISTRIBUTED=1
3. Version 1.1.0

Message:
/home/pi/pytorch_install/pytorch/torch/lib/c10d/test/ProcessGroupGlooTest.cpp:12:10 fatal error: gloo/transport/tcp/device.h no such file or directory
#include <gloo/transport/tcp/device.h>

I did not get this on Raspberry Pi 3B+

**Comment by mrshenli** [comment]
@snippler can you try `USE_DISTRIBUTED=0` flag instead?

**Comment by mrshenli** [comment]
Some more context, [USE_DISTRIBUTED](https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L150) -> [USE_GLOO](https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L155) -> [USE_C10D_GLOO](https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/CMakeLists.txt#L19) -> [ProcessGroupGlooTest.cpp](ProcessGroupGlooTest.cpp)

**Comment by mrshenli** [comment]
Hi @snippler, does `USE_DISTRIBUTED=0` work for you?

**Comment by yoloBurning** [comment]
Hi @mrshenli I met the same problem and I tried it. I did not work.

**Comment by yoloBurning** [comment]
Hi @mrshenli  I met the same problem and I tried it. It did not work.

**Comment by yoloBurning** [comment]
@mrshenli btw, I tried to install pytorch **v1.1.0** on Raps. 3 B+.

**Comment by yoloBurning** [comment]
@mrshenli btw, I tried to install pytorch **v1.1.0** on Raspberry Pi **3 B+**.

**Comment by mrshenli** [comment]
Hi @orionr, do you know if there is anything special for installing on Raspberry Pi?

**Comment by orionr** [comment]
USE_DISTRIBUTED=0 is definitely a flag  you'd want to set. Generally, look at the Android mobile build and what flags are set in that case. @ljk53 might be able to help here.

**Comment by snippler** [comment]
In the end I built on Raspberry 3 B+ and put the SD card into Raspberry 4 B and it works. It is weird.
