### ISSUE TITLE
cpp_extension should use ninja for setup.py builds too

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#23384]
cpp extension uses ninja for JIT builds, but defers to regular old setuptools for normal C++ extension builds. This is bad because normal setuptools doesn't run in parallel. Ninja does. We should run ninja.

torchvision and probably our other domain libraries are affected by this. I can't believe y'all have suffered under single threaded builds for this long.

**Comment by cpuhrsch** [comment]
I'm going to start looking into this in context of NestedTensors

**Comment by ezyang** [comment]
This is fixed by @zou3519 !
