### ISSUE TITLE
Torchlib with ROS

### ISSUE THREAD

**Issue by sanketgujar** [pytorch/pytorch#23385]
I am having a hard time running pytorch model with ROS in C++. The torchlib breaks the ROS when I try to include it in my package cmakelist. I included the moden ABI by “add_compile_options(-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1)” but it didn’t help too.

After many tries I decided to built pytorch but then I got a new error for c10, the error log can be found here https://gist.github.com/sanketgujar/8c55c8536910a0ede84133688fb5af41. I tried changes in the previous similar post but nothing is helping. The TORCH_CXX_FLAGS D_GLIBCXX_USE_CXX11_ABI=1 flag is already 1 for me as default in the TorchConfig.cmake.

I am using ROS Kinetic and my gcc version is 5.4

**Comment by izdeby** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.

**Comment by yjhdhr** [comment]
OK？
