### ISSUE TITLE
Cannot install pytorch with magma

### ISSUE THREAD

**Issue by lburzawa** [pytorch/pytorch#23411]
## 🐛 Bug

The installation fails at the end when trying to compile pytorch with magma. I just installed magma 2.5.1-alpha1 and tried to install pytorch from master branch today (07/25). The error is:
 
[2978/3153] Linking CXX shared library lib/libtorch.so
FAILED: lib/libtorch.so 
....................... (huge continuous dump of object paths in the middle)
/usr/bin/ld: /usr/local/magma/lib/libmagma.a(thread_queue.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Any ideas what is the issue?

## To Reproduce

Try to compile pytorch with newest magma.

## Environment

 - PyTorch Version (e.g., 1.0): 1.2.0 (master branch)
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): sudo python setup.py install
 - Python version: 3.6.8
 - CUDA/cuDNN version: 10.1 and 7.6.2
 - GPU models and configuration: 2080 Ti

**Comment by peterjc123** [comment]
cc @soumith

**Comment by vishwakftw** [comment]
@lburzawa could you provide the make.inc file that you used for compiling MAGMA?

**Comment by soumith** [comment]
the error is pretty self-explanatory, you have to recompile magma with `-fPIC` enabled.
See my patches for magma 2.5.0 and roughly do the same: https://github.com/pytorch/builder/blob/master/conda/magma-cuda90-2.5.0/cmakelists.patch#L34

**Comment by lburzawa** [comment]
thanks

**Comment by javadba** [comment]
LInk is dead

**Comment by peterjc123** [comment]
New link: https://github.com/pytorch/builder/tree/master/magma.
