### ISSUE TITLE
BenchmarkCache for other kernels 

### ISSUE THREAD

**Issue by ThisIsIsaac** [pytorch/pytorch#23413]
## 🚀 Feature

Further improve throughput increase from setting `torch.backends.cudnn.benchmark = True`.

## Pitch

Turning `torch.backends.cudnn.benchmark = True` seesm to greatly improve throughput (30 ~ 40%).

I dug into the source code trying to find how it is implemented, and came across BenchmarkCache defined [here](https://github.com/pytorch/pytorch/blob/358fb51e773b8ad509ec270caee5ec1c51d82f38/aten/src/ATen/native/cudnn/Conv.cpp#L340). The cache only seems to cache convolutional algorithms. If this is true, I want to expand the cache to other computations, at least RNNs, in order to further accelerate the thoughput increase when we turn `torch.backends.cudnn.benchmark = True`.

## Questions

@SsnL  , I have a few questions regarding improving `BenchmarkCache`:

1. Is `BackendCache` defined in [Conv.cpp](https://github.com/pytorch/pytorch/blob/358fb51e773b8ad509ec270caee5ec1c51d82f38/aten/src/ATen/native/cudnn/Conv.cpp#L340) the only cache that is turned on by `torch.backends.cudnn.benchmark = True`?

2. Is there a specific reason why `BackendCache` only caches CNNs? I assume it is because the overhead of choosing a CNN kernel is the highest, but correct me if I'm wrong.

3. Does `BackendCache` cache all CNN computations, including all the supported dimensions?

**Comment by ThisIsIsaac** [comment]
Okay, so it seems like searching kernel search of cuDNN is only invoked when using CNN. Other computations such as RNN do not require this heuristic search, so that's the reason why we only cache for CNNs. If this is the case, then I will simply close the issue as there would be no point in trying to cache other cuDNN kernel choices.

**Comment by soumith** [comment]
CuDNN limitation, it only implemented kernel search + cache for Convolutions.

**Comment by ThisIsIsaac** [comment]
@soumith 
From my reading of [Conv.cpp](https://github.com/pytorch/pytorch/blob/358fb51e773b8ad509ec270caee5ec1c51d82f38/aten/src/ATen/native/cudnn/Conv.cpp#L340), the cache is implemented in Pytorch, and not in cuDNN. Or do you mean only convolutions are cacheable?
