### ISSUE TITLE
why there's SparseFtrlOp and FtrlOp but only GFtrlOp without SparseGFtrlOp

### ISSUE THREAD

**Issue by sjtusmartboy** [pytorch/pytorch#23419]
FtrlOp:
https://github.com/pytorch/pytorch/blob/519570def878eb48cc9a50183f90f7009c3afdb8/caffe2/sgd/ftrl_op.cc#L60

SparseFtrlOp:
https://github.com/pytorch/pytorch/blob/519570def878eb48cc9a50183f90f7009c3afdb8/caffe2/sgd/ftrl_op.cc#L84

GFtrlOp:
https://github.com/pytorch/pytorch/blob/519570def878eb48cc9a50183f90f7009c3afdb8/caffe2/sgd/gftrl_op.cc#L72

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
