### ISSUE TITLE
ONNX export failed: Couldn't export operator aten::flatten

### ISSUE THREAD

**Issue by blackxer** [pytorch/pytorch#23427]
When i exported my model to onnx. I got this error.
My pytorch version is 1.0.1.
```
# out.shape: [1,256,1,1]
out = out.flatten(1, -1)  # the code does not convert to onnx
```

**Comment by colesbury** [comment]
@houseroad does Tensor.flatten work in the latest PyTorch?

**Comment by blackxer** [comment]
I have updated my pytorch to version 1.1.0. 
It works in the latest PyTorch(1.1.0)
