### ISSUE TITLE
how to  process c++ forward multiple return values

### ISSUE THREAD

**Issue by kakaluote** [pytorch/pytorch#23423]
my model return value like this  , it is detection model
output = (
                tensor1,                   # loc preds
                tensor2          # conf preds
 )

how to get return values in c++

**Comment by t-vi** [comment]
Please use the [forum](https://discuss.pytorch.org/) for this. In fact, you'll get a tuple in this case and then `auto outputs = module->forward(inputs).toTuple();` works.

**Comment by kakaluote** [comment]
think you
