### ISSUE TITLE
C++ protoc.exe fail with .proto files

### ISSUE THREAD

**Issue by nurettinabaci** [pytorch/pytorch#23432]
Hello, I want to use Caffe2 C++ API with Visual Studio 2015, I made instructions that described [here](https://caffe2.ai/docs/cplusplus_tutorial.html). At the bottom of this page, it says we should run `protoc –cpp_out=./ $FILENAME.proto` in directory of `$CAFFE2_DIRECTORY\caffe2\proto` . When I want to create .cc and .h files with this command, other file's .cc and .h files are created but that two gives error as below,

```
C:\pytorch\caffe2\proto>protoc --cpp_out=./ torch.proto
caffe2/proto/caffe2.proto: File not found.
torch.proto:3:1: Import "caffe2/proto/caffe2.proto" was not found or had errors.
torch.proto:17:12: "caffe2.TensorProto.DataType" is not defined.
torch.proto:50:12: "caffe2.NetDef" is not defined.

C:\pytorch\caffe2\proto>protoc --cpp_out=./ metanet.proto
caffe2/proto/caffe2.proto: File not found.
metanet.proto:3:1: Import "caffe2/proto/caffe2.proto" was not found or had errors.
metanet.proto:22:12: "NetDef" is not defined.
metanet.proto:27:12: "PlanDef" is not defined.
```

I tried to run with that condition this code and it seems to fail at importing header:
```
#include <iostream>
#include <caffe2/core/init.h>
int main(int argc, char** argv){
	caffe2::GlobalInit(&argc, &argv);
	return 0;
}
```
and gave error :
```
Error (active)      cannot open source file "c10/macros/cmake_macros.h" test2   c:\pytorch\c10\macros\Export.h  44  
Error (active)      cannot open source file "c10/macros/cmake_macros.h" test2   c:\pytorch\c10\macros\Macros.h  21  
Error C1083 Cannot open include file: 'c10/macros/cmake_macros.h': No such file or directory    test2   c:\pytorch\c10\macros\macros.h  21
```

Note: I installed protocol buffers with vcpkg.

- Additional Include Directories:
```
C:\pytorch\
C:\pytorch\caffe2\
C:\pytorch\caffe2\core
```

- OS: Windows 10
- PyTorch version: 1.1
- CMake version: 3.15

**Comment by nurettinabaci** [comment]
in the `C:\pytorch\c10\macros directory`, the header file `cmake_macros.h.in` exists but gives error , any solution?
```
#include "stdafx.h"
#include "c10/macros/Macros.h" 
int main(int argc, char** argv) {
	// gives same error
	return 0;
}
```

**Comment by red0orange** [comment]
Run the following command in the proto folder to change the root directory of your own pytorch
`protoc --cpp_out=./ --proto_path=/home/red0orange/allLib/pytorch caffe2/proto/caffe2_legacy.proto`
