### ISSUE TITLE
[C++] Consider accessing qint data with underlying data type.

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#23440]
Currently we do things like:
https://github.com/pytorch/pytorch/blob/34f53564b4e5937780a9784e7694c4df98c217cb/aten/src/ATen/native/quantized/cpu/qconv_unpack.cpp#L43-L44

it's probably cleaner to just directly access the data as the underlying type, as long as we check that only the underlying type is allowed.

**Comment by supriyar** [comment]
This has been updated since reported to use `data_ptr` to access the underlying type. Closing the issue.
