### ISSUE TITLE
DataLoader with sparse matrices adds a dimension to the batch

### ISSUE THREAD

**Issue by juselec** [pytorch/pytorch#23459]
## 🐛 Bug

I do not know if this is actually a bug or it is the expected behavior. I am experimenting with sparse data. I create a Dataset class that stores a scipy.sparse.csr_matrix (csr because it is able to slice the matrix and create minibatches). The `__getitem__` method transforms the csr matrix into a minibatch of class tensor.sparse.FloatTensor. If I slice the dataloader the dimensions are the expected. When I feed the Dataset into a DataLoader, it adds an extra dimension to the returned minibatch. With the example code I will put now, the explanation will be more clear.

## To Reproduce

1. Install scipy and pytorch inside a conda environment (in my case I have the gpu version of pytorch but the same is valid with the cpu version).
```
conda install pytorch cudatoolkit=10.0 -c pytorch
conda install scipy
```
2. Run the following code:

```
import torch
from torch.utils.data import Dataset, DataLoader
from scipy.sparse import random


class SparseData(Dataset):
    def __init__(self, rows, cols, density=0.01):
        self.rows = rows
        # csr format for being able to slice the matrix
        self.x = random(rows, cols, density, format='csr')

    def __len__(self):
        return self.rows

    def __getitem__(self, idx):
        x_coo = self.x[idx, :].tocoo()
        ind = torch.LongTensor([x_coo.row, x_coo.col])
        data = torch.FloatTensor(x_coo.data)
        return torch.sparse.FloatTensor(ind, data, list(x_coo.shape))


data = SparseData(200, 10, 0.02)
dataloader = DataLoader(data, batch_size=5, shuffle=False, num_workers=0)

for i, x in enumerate(dataloader):
    print("Batch {} shape {}".format(i, x.shape))
    break
```
The resulting shapes are:

```
(base) [pr@pr-pc SparsePytorch]$ python SparsePytorch.py 
Shape of the slice torch.Size([6, 10])
Batch 0 shape torch.Size([5, 1, 10])
```
As the output shows, the shape of the batch has one dimension more (3 instead of 2) than the slice. This *I think* should not be the case.

## Expected behavior

Batch should have the same dimensions as a slice of the dataset, as it happens with dense tensors:

```
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np


class Data(Dataset):
    def __init__(self, rows, cols):
        self.rows = rows
        self.x = torch.from_numpy(np.random.normal(size=(rows, cols)))

    def __len__(self):
        return self.rows

    def __getitem__(self, idx):
        return self.x[idx, :]


data = Data(200, 10)
print("Shape of the slice {}".format(data[0:6].shape))
dataloader = DataLoader(data, batch_size=5, shuffle=False, num_workers=0)

for i, x in enumerate(dataloader):
    print("Batch {} shape {}".format(i, x.shape))
    break
```

Output:

```
(base) [pr@pr-pc SparsePytorch]$ python NoSparsePytorch.py 
Shape of the slice torch.Size([6, 10])
Batch 0 shape torch.Size([5, 10])
```

Here we see that the batch dimension is the same as the dimension taken directly from the dataset.

## Environment

```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Arch Linux
GCC version: (GCC) 9.1.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 430.34
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.0.2            py37h7b6447c_0  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] mxnet-cu101mkl            1.4.1                    pypi_0    pypi
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
```

**Comment by soumith** [comment]
it's not a bug, it's dependent on how our `default_collate` function handles the Tensor batching.
If you want different behavior, you can give a custom `collate_fn` that you define to `DataLoader`.

Here's the code pointer to the `default_collate` function:

https://github.com/pytorch/pytorch/blob/058beae4115afb76ee5f45dfa42c6ab4ee01895c/torch/utils/data/_utils/collate.py#L43-L82

**Comment by juselec** [comment]
Ohh, didn't know about that. Thanks a lot!

**Comment by qoVA** [comment]
How do i establish a custom collate function? is there a way around this?
I am facing a similar issue
