### ISSUE TITLE
import failure (macOS)

### ISSUE THREAD

**Issue by mark-fangzhou-xie** [pytorch/pytorch#23466]
## 🐛 Bug
I was using pytorch without any issue, but I just found out today that when importing torch, it threw me an error. Possibly regarding MKL library. I could not figure out why.

## To Reproduce

1. `import torch`
1.
1.
Below are the error message:
```
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: dlopen(/anaconda3/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 9): Symbol not found: _mkl_serv_inspector_loaded
  Referenced from: /anaconda3/lib/python3.7/site-packages/torch/lib/../../../../libmkl_intel_thread.dylib
  Expected in: flat namespace
 in /anaconda3/lib/python3.7/site-packages/torch/lib/../../../../libmkl_intel_thread.dylib
>>> 
```

## Expected behavior

Clearly, it should not be happening.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Mac OSX 10.14.5
GCC version: Could not collect
CMake version: version 3.14.5

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.4
[conda] mkl                       2019.4                      233  
[conda] pytorch                   1.1.0                   py3.7_0    pytorch
[conda] torchvision               0.3.0             py37_cuNone_1    pytorch
```

 - PyTorch Version (e.g., 1.0): 1.1.0 (although not shown above, this is the version I installed from conda)
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

I have no idea what happened but probably because I was using julia and trying to install ubuntu on my Mac. Maybe somehow I messed up with my environment?

**Comment by mark-fangzhou-xie** [comment]
After searching on google I found that it is possibly because I add the following into `~/.bash_profile`:
`export LD_LIBRARY_PATH=/opt/arrayfire/lib:$LD_LIBRARY_PATH`.

I added this line when trying to use ArrarFire for julia. After commenting it out, everything works fine now.

Thank you!

**Comment by matteocollina** [comment]
My workaround
`
$ conda activate [MYENV]
$ pip uninstall torch
$ pip install torch
`
