### ISSUE TITLE
is it possible to add c++ api to load .pth model directly?

### ISSUE THREAD

**Issue by anguoyang** [pytorch/pytorch#23467]
is it possible to add c++ api to load .pth model directly?
Currently, we have to convert from pth to pt by way of torchscript, I really puzzled why pytorch DO NOT want to provide unified interface for both .pth and .pt, which is not difficult to implement

**Comment by soumith** [comment]
we dont plan to provide an interface other than the one via TorchScript.

> I really puzzled why pytorch DO NOT want to provide unified interface for both .pth and .pt, which is not difficult to implement

Without re-implementing Python, it's simply not possible. So, no you are wrong, it **is** difficult to implement.
