### ISSUE TITLE
logdet & slogdet is not numerically stable occasionally 

### ISSUE THREAD

**Issue by Gsunshine** [pytorch/pytorch#23473]
## 🐛 Bug

It seems the implementation of the sign of determinant is not numerical stable for a large symmetric positive-definite matrix.

## To Reproduce

```
In [16]: M = torch.rand(256, 256)

In [17]: M = torch.matmul(M, M.transpose(0, 1))

In [18]: M.logdet()
Out[18]: tensor(nan)

In [19]: M
Out[19]:
tensor([[75.1178, 64.0427, 60.7506,  ..., 53.5633, 60.8235, 57.2295],
        [64.0427, 91.5975, 72.8763,  ..., 61.9161, 70.7397, 67.5642],
        [60.7506, 72.8763, 93.8879,  ..., 62.6111, 71.5651, 66.6507],
        ...,
        [53.5633, 61.9161, 62.6111,  ..., 77.7719, 62.9280, 59.0837],
        [60.8235, 70.7397, 71.5651,  ..., 62.9280, 90.5574, 64.9320],
        [57.2295, 67.5642, 66.6507,  ..., 59.0837, 64.9320, 85.6822]])

In [20]: M.slogdet()
Out[20]:
torch.return_types.slogdet(
sign=tensor(-1.),
logabsdet=tensor(530.7049))

In [21]: M.svd()[1].min()
Out[21]: tensor(0.0010)
```

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176

Nvidia driver version: 430.26
cuDNN version: /usr/local/cuda-9.0/lib64/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.1.0
[pip] torchcontrib==0.0.2
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.3                      199
[conda] mkl-service               1.1.2            py37he904b0f_5
[conda] mkl_fft                   1.0.10           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torchcontrib              0.0.2                    pypi_0    pypi
[conda] torchvision               0.3.0                    pypi_0    pypi

cc @vincentqb @vishwakftw @jianyuh @nikitaved @pearu @mruberry @heitorschueroff

**Comment by vishwakftw** [comment]
Is the matrix possibly ill-conditioned?

Also what is the output of M.symeig()[0].sum()?

**Comment by Gsunshine** [comment]
Yeah..

```
In [30]: M.svd()[1].max()
Out[30]: tensor(16324.6006)

In [31]: M.symeig()[0].sum()
Out[31]: tensor(21721.5977)
```

> Is the matrix possibly ill-conditioned?
> 
> Also what is the output of M.symeig()[0].sum()?

**Comment by Gsunshine** [comment]
```
In [30]: M.svd()[1].max()
Out[30]: tensor(16324.6006)

In [31]: M.symeig()[0].sum()
Out[31]: tensor(21721.5977)
```

> Is the matrix possibly ill-conditioned?
> 
> Also what is the output of M.symeig()[0].sum()?

**Comment by vishwakftw** [comment]
The condition number seems to be 1.6 * 1e7. So, it is possible that the value of the slogdet is correct. logdet result seems to be consistent with slogdet as sign is -1.

By the way, I’m sorry, I wanted M.symeig()[0].prod() (and not .sum()).

**Comment by Gsunshine** [comment]
I see. So I report `M.svd()[1].max()`. 
Here I mean why not support `logdet` only for SPD matrix, regardless of its sign. We can conduct detailed check in `slogdet`, even via svd.

**Comment by vishwakftw** [comment]
Oh, I missed how you generated M. It seems to be PSD and symmetric, in which case, sign should be 1 or 0. So, yes this is incorrect behavior.

Regarding your pitch for logdet supporting only SPD matrices, I think that would be bc-breaking as logdet can also take certain negative definite symmetric matrices (for example: the negative identity matrix).

**Comment by Gsunshine** [comment]
Oh, sorry for the wrong abbreviation. I mean a symmetric positive definite matrix. 

Actually it could be a positive semi-definite matrix from this generating process. But I have checked its min singular value. 

> Oh, I missed how you generated M. It seems to be PSD and symmetric, in which case, sign should be 1 or 0. So, yes this is incorrect behavior.
> 
> Regarding your pitch for logdet supporting only SPD matrices, I think that would be bc-breaking as logdet can also take certain negative definite symmetric matrices (for example: the negative identity matrix).

**Comment by colesbury** [comment]
Yeah, this seems bad. PRs are more than welcome. I noticed that NumPy does not have this issue and that logdet still computes NaN if the matrix is converted to double precision.

https://gist.github.com/colesbury/b14b04e8eb4e43240bf0f39ebcbf7cf8

**Comment by vishwakftw** [comment]
@colesbury The gist compares the output of NumPy's slogdet and our logdet.

Furthermore, the matrix obtained at the end of the loop is still a positive semi-definite matrix, and hence the det should be >= 0. However, the output from NumPy's slogdet seems to indicate (just as PyTorch's implementation) that the matrix has a very small negative determinant. Below is the output I see locally:

```python
>>> M.det()
tensor(-inf)
>>> M.logdet()
tensor(nan)
>>> M.slogdet()
torch.return_types.slogdet(
sign=tensor(-1.),
logabsdet=tensor(533.9559))
>>> numpy.linalg.slogdet(M.numpy())
(-1.0, 534.2159)
```

**Comment by Gsunshine** [comment]
@vishwakftw Did you change the behaviors in your batched det/logdet/slogdet?

@colesbury It is noteworthy that `svd` is numeracally stable. It produce correct min singular value (>=0) for a positive semi-definite matrix. And the value of abs of log det in `slogdet` is nearly correct (But not always the same as numpy!).

**Comment by Lezcano** [comment]
Closing this one as it seems solved. As a pointer for anyone finding this, see https://github.com/pytorch/pytorch/issues/22848#issuecomment-1032737956 for how to implement a faster version of `logdet` if the matrix is SPD.
