### ISSUE TITLE
Indexing tensor by a boolean np.array or boolean torch.Tensor is different

### ISSUE THREAD

**Issue by xiaodongww** [pytorch/pytorch#23489]
## 🐛 Bug

The result of indexing pytorch tensor by a boolean  `np.array` or boolean `torch.Tensor`  is different. This may cause bugs possibly. Is it better to make the result consistent whenever the type of indicator is `np.array` or `torch.Tensor` ? 
## To Reproduce

1. run the following code 

```python
import torch
import numpy as np

# select elements according to flag
flag1 = torch.Tensor([0, 1, 0, 1, 0])
flag2 = np.array([0, 1, 0, 1, 0])
values = torch.arange(len(flag1))

selected1 = values[flag1 == 1]
selected2 = values[flag2 == 1]
selected3 = values.numpy()[flag2 == 1]

print(selected1)  # tensor([1, 3])
print(selected2)  # tensor([0, 1, 0, 1, 0])
print(selected3)  # [1, 3]
```
## Expected behavior
I expect `selected2` to be the same as `selected1`, but the result does not seem so. 

We can see that the indexing array is both boolean for `selected1` and `selected2`,  so is it better to get same indexing result? 
## Environment
```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration:
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X
GPU 2: GeForce GTX TITAN X
GPU 3: GeForce GTX TITAN X

Nvidia driver version: 410.66
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] efficientnet-pytorch==0.3.0
[pip] numpy==1.16.4
[pip] pytorch-ignite==0.1.2
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] efficientnet-pytorch      0.3.0                     <pip>
[conda] pytorch-ignite            0.1.2                     <pip>
[conda] torch                     1.1.0                     <pip>
[conda] torchvision               0.3.0                     <pip>
```

**Comment by colesbury** [comment]
Thanks for the bug report. This is fixed in the master branch and will be in the PyTorch 1.2 release.

cc @gchanan: I'm not sure if any PR explicitly mentioned fixing this. I think the fix is implicit because of the conversion from NumPy np.bool -> torch.bool
