### ISSUE TITLE
Inconsistent dimension argument numbering between function

### ISSUE THREAD

**Issue by ilhamfp** [pytorch/pytorch#23481]
## 📚 Documentation

Both [torch.diag_embed](https://pytorch.org/docs/stable/torch.html#torch.diag_embed) and [torch.diagonal](https://pytorch.org/docs/stable/torch.html#torch.diagonal) use dim1 & and dim2 meanwhile [torch.transpose](https://pytorch.org/docs/stable/torch.html#torch.transpose), _mkldnn_transpose, transpose_, and _mkldnn_transpose_ use dim0 & dim1. Shouldn't the naming of the dimension consistent across function?

If this is indeed was a problem, I can help you and work on fixing this.

**Comment by vishwakftw** [comment]
Duplicate of #23072

**Comment by ilhamfp** [comment]
@vishwakftw well, there's some overlap. The issue you mentioned didn't address  torch.diag_embed.

**Comment by colesbury** [comment]
Let's track this in #23072

**Comment by ilhamfp** [comment]
Sure
