### ISSUE TITLE
Why warning on torch.tensor(another_tensor)?

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#23495]
When we do `torch.tensor(another_tensor)`, we see a warning:

```
UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
```

Is this warning really a good idea? `torch.tensor(another_tensor)` has a neat use case:
```python
import torch

ensure_tensor = torch.tensor

print(ensure_tensor([1, 3, 5]))
print(ensure_tensor(3.0))
print(ensure_tensor(torch.tensor(1.0)))
```

The code above is simpler than

```python
def ensure_tensor(x):
    if torch.is_tensor(x):
        return x
    return torch.tensor(x)
```

**Comment by SsnL** [comment]
For that use you should do `torch.as_tensor`. The `ensure_tensor` fn you have is different with `torch.tensor` in that `torch.tensor` always copies.

**Comment by zasdfgbnm** [comment]
@SsnL Thanks for the explanation!
