### ISSUE TITLE
torch-0.2.0.post1-cp27-cp27m-manylinux1_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by isalirezag** [pytorch/pytorch#2349]
I am trying to upgrade my pytorch via using pip command from the website.
I have ubuntu 16.04.
Should I remove my pytorch first? 
when I run the command on the website  I receive this error:
torch-0.2.0.post1-cp27-cp27m-manylinux1_x86_64.whl is not a supported wheel on this platform.

Any suggestion what I need to do?
Also pip --version gives me: pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

Thanks

**Comment by soumith** [comment]
did you try the other command suggested if the first command doesn't work? python 2.7 comes in two flavors cp27m and cp27mu.
<img width="745" alt="screen shot 2017-08-08 at 9 42 41 pm" src="https://user-images.githubusercontent.com/1310570/29101785-8ba3a16a-7c82-11e7-9543-77488de499b3.png">

**Comment by isalirezag** [comment]
actually not!!
I tried it now and it works.
Thanks

**Comment by LilJing** [comment]
hey I tried the second command nut still the same error,do you know why?Thank you

**Comment by isalirezag** [comment]
probably you may need to uninstall it first and retry again
