### ISSUE TITLE
[Feature request] Default dimension size for expand

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#2350]
```
x = torch.randn(3,1)
# I want to expand it to 3,4
y = x.expand(3, 4) # current
# Can we do?
y = x.expand(-1, 4) #instead
```

**Comment by ruotianluo** [comment]
Any idea?

**Comment by apaszke** [comment]
Why not. I understand that `-1` would mean "don't change the size" in this case, right?

**Comment by gchanan** [comment]
Since expand can take more dimension sizes than are currently there, need to check/document/test that -1 isn't allowed in a leading, non-existing dimension.
